### PR TITLE
virt: detect qemu/kvm as 'kvm'

### LINKED ISSUE #5318: kvm is detected as qemu
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> buildroot 2017.02-git

### In case of bug report: Expected behaviour you didn't see

> systemd[1]: Detected virtualization kvm.

### In case of bug report: Unexpected behaviour you saw

> systemd[1]: Detected virtualization qemu.

Looking at the code at https://github.com/systemd/systemd/blob/master/src/basic/virt.c#L166, it checks /sys/class/dmi/id/product_name, which contains qemu-kvm's machine type:
```
# cat /sys/class/dmi/id/product_name
Standard PC (i440FX + PIIX, 1996)
# cat /sys/class/dmi/id/sys_vendor 
QEMU
```

This is with qemu 2.80.

If I recall correctly this used to work, probably because the cpuid flags where checked first before dmi, and this is a regression caused by  050e65ada2e0023a1a4c953522f39846c6bdebf8

### PR DESCRIPTION
**Pull request by eworm-de**
In commit 050e65a we swapped order of detect_vm_{cpuid,dmi}(). That
fixed Virtualbox but broke qemu with kvm, which is expected to return
'kvm'. So check for qemu/kvm first, then DMI, CPUID last.

This fixes #5318.

### CODE REVIEW

File: src/basic/virt.c [hunk 1]
```diff
@@ -316,28 +316,33 @@ static int detect_vm_zvm(void) {
...
         if (r != VIRTUALIZATION_NONE)
                 goto finish;
 
-        r = detect_vm_cpuid();
-        if (r < 0)
-                return r;
-        if (r != VIRTUALIZATION_NONE)
+        if (cpuid < 0)
+                return cpuid;
+        if (cpuid != VIRTUALIZATION_NONE)
```
Comment (poettering) [inline src/basic/virt.c]: there's an `r = cpuid` missing here, no?

**Comment by eworm-de** [comment]
Updated with little modification to man systemd-detect-virt.

File: src/basic/virt.c (hunk 1 above)
Comment (eworm-de) [reply src/basic/virt.c]: Yes, missed your comment. Updated again.

**Comment by poettering** [comment]
lgtm

**Comment by tixxdz** [comment]
lgtm
