### PR TITLE
udev,login: update ACL on static device nodes

### LINKED ISSUE #39043: Steaminput no longer works after update to 258-1.1
### systemd version the issue has been seen with

258-1.1

### Used distribution

EndeavouOS

### Linux kernel version used

6.12.47-1.1-lts

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

On steam, the controller hardware is detected in the settings > controller. All inputs work when tested there. But once a game loads, the inputs from controllers to do not register. Changing proton version has no impact. Rebooting has no impact.

**Workaround:**  Turning off steam input immediately allows controller to work. 

Only relevant update since yesterday when it worked have been the following:

`[2025-09-19T03:30:42-0400] [ALPM] upgraded systemd-libs (257.9-1.1 -> 258-1.1)
[2025-09-19T03:30:42-0400] [ALPM] upgraded lib32-systemd (257.9-1.1 -> 258-1.1)
[2025-09-19T03:30:42-0400] [ALPM] upgraded libtiff (4.7.0-1.1 -> 4.7.1-1.1)
[2025-09-19T03:30:42-0400] [ALPM] upgraded ntp (4.2.8.p18-3.1 -> 4.2.8.p18-4.1)
[2025-09-19T03:30:42-0400] [ALPM] warning: /etc/systemd/logind.conf installed as /etc/systemd/logind.conf.pacnew
[2025-09-19T03:30:42-0400] [ALPM] upgraded systemd (257.9-1.1 -> 258-1.1)
[2025-09-19T03:30:43-0400] [ALPM] upgraded systemd-resolvconf (257.9-1.1 -> 258-1.1)
[2025-09-19T03:30:43-0400] [ALPM] upgraded systemd-sysvcompat (257.9-1.1 -> 258-1.1)`

I updated system after I had just completed a gaming session with no issues(Yes at 3 am - sorry).  Errors also observed by others on [reddit](https://www.reddit.com/r/linux_gaming/comments/1nkk62a/controller_isnt_working_in_rocket_league/). They seem to have solved the issue by downgrading.

### Unexpected behaviour you saw

I am also getting these 'journalctl' errors. 

`Sep 19 17:53:29 Shariar-PC-Lin systemd-udevd[618]: /usr/lib/udev/rules.d/55-Argyll.rules:161 Group 'colord' is not a system group, ignoring.`

`Sep 19 17:53:29 Shariar-PC-Lin systemd-udevd[618]: /usr/lib/udev/rules.d/69-cd-sensors.rules:105 Group 'colord' is not a system group, ignoring.`

`Sep 19 17:56:32 Shariar-PC-Lin (udev-worker)[2738]: controlC4: /usr/lib/udev/rules.d/78-sound-card.rules:5 ATTR{../uevent}="change": Could not chase sysfs attribute "/sys/devices/pci0000:00/0000:00:02.1/0000:05:00.0/0000:06:0c.0/0000:0d:00.0/usb1/1-2/1-2.1/1-2.1:1.0/sound/card4/controlC4/../uevent", ignoring: No such file or directory`

These could be unrelated, but I have not seen these errors before. Could indicate some issues with how `/usr/lib/udev/rules.d` is handled since that is where `steam-input` also lives.

### Steps to reproduce the problem

Just launch any steam game with steam input enabled. 

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes regression caused by #36444.
Fixes #39043.

### CODE REVIEW

File: src/shared/acl-util.c [hunk 1]
```diff
@@ -6,12 +6,106 @@
...
+                changed = true;
+        }
+
+        if (!changed)
+                return 0;
+
+        if (acl_calc_mask(&acl) < 0)
+                return -errno;
+
+        if (acl_set_file(FORMAT_PROC_FD_PATH(fd), ACL_TYPE_ACCESS, acl) < 0)
```
Comment (poettering) [inline src/shared/acl-util.c:103]: hmm, i wonder if acl_set_fd() works these days?

(but maybe let's do that independently, in particular to make this simple to break point)

Comment (poettering) [reply src/shared/acl-util.c:103]: (the reason we use acl_set_file() here was either some O_PATH messiness around libacl, or because xattr syscalls didn't do fd-based stuff originally, i don't remember. but i think both are nowadays solved in libacl, but dunno)

File: src/login/logind-seat.c [hunk 2]
```diff
@@ -321,12 +324,85 @@ static int seat_trigger_devices(Seat *s) {
...
+                }
+
+                r = stat_verify_device_node(&st);
+                if (r < 0) {
+                        RET_GATHER(ret, log_debug_errno(fd, "'/run/udev/static_node-tags/uaccess/%s' points to a non-device node: %m", de->d_name));
+                        continue;
+                }
+
+                _cleanup_(sd_device_unrefp) sd_device *dev = NULL;
+                if (sd_device_new_from_stat_rdev(&dev, &st) >= 0) {
```
Comment (poettering) [inline src/login/logind-seat.c]: maybe make this stronger, at least for debugging purposes, i.e.:

```c
r = sd_device_new_from_stat_rdev(…);
if (r >= 0) {
        …
}
if (!ERRNO_IS_NEG_DEVICE_ABSENT_OR_EMPTY(r)) {
        …
}

File: src/shared/acl-util.c (hunk 1 above)
Comment (yuwata) [reply src/shared/acl-util.c:103]: Ok, will check and update later in another PR.

**Comment by keszybz** [comment]
Backport queued for v258.1
