### PR TITLE
fstab-generator: fixes for systemd.mount-extra=

### LINKED ISSUE #28516: systemd.mount-extra= does not work
### systemd version the issue has been seen with

254~rc3

### Used distribution

Fedora rawhide

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

x86_64

### Component

_No response_

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

Originally posted by @bmr-cymru in https://github.com/systemd/systemd/issues/27260#issuecomment-1649986565.

I'm trying to test the new `systemd.mount-extra` in Fedora Rawhide with systemd-254~rc3-1.fc39.x86_64 and LVM2 logical volumes and I'm running into some problems.

Firstly, when using command line mount units and `nofstab` nothing pulls in `systemd-remount-fs.service`, which leaves the root fs mounted read-only: I think that unit should be pulled in if command line or credentials fstab entries are present. Other than that the basic case of booting a system with the fstab entries on the kernel command line seems to work as expected:

```
root=/dev/fedora/root ro rd.lvm.lv=fedora/root rd.lvm.lv=fedora/var rd.lvm.lv=fedora/home fstab=no systemd.mount-extra=/dev/fedora/root:/:ext4:rw systemd.mount-extra=/dev/vda2:/boot:ext4:defaults systemd.mount-extra=/dev/fedora/var:/var:ext4:defaults systemd.mount-extra=/dev/fedora/home:/home:ext4:defaults
```

The system boots normally and file systems are mounted as expected:

```
# grep fedora /proc/mounts 
/dev/mapper/fedora-root / ext4 ro,seclabel,relatime 0 0
/dev/mapper/fedora-home /home ext4 rw,seclabel,relatime 0 0
/dev/mapper/fedora-var /var ext4 rw,seclabel,relatime 0 0
```

Attempting to boot into a snapshot of the system state fails unpredictably: in some cases the system appears to boot normally but systemd attempts to unmount the command line mounts after switching root. In other cases the devices for the command line mount units time out. I'm struggling to debug this: the generated unit files seem sane and I can't figure out why the umounts and timeouts are occurring.

The snapshot command line looks like this:

```
root=/dev/fedora/root-snap ro rd.lvm.lv=fedora/root-snap rd.lvm.lv=fedora/var-snap rd.lvm.lv=fedora/home-snap fstab=no systemd.mount-extra=/dev/fedora/root-snap:/:ext4:rw systemd.mount-extra=/dev/vda2:/boot:ext4:defaults systemd.mount-extra=/dev/fedora/var-snap:/var:ext4:defaults systemd.mount-extra=/dev/fedora/home-snap:/home:ext4:defaults
```

In the case that file systems are unmounted the logs look like this:

```
Jul 25 14:49:36 fedora systemd[1]: Mounting sys-kernel-config.mount - Kernel Configuration File System...
Jul 25 14:49:36 fedora systemd[1]: Mounted sys-kernel-config.mount - Kernel Configuration File System.
Jul 25 14:49:36 fedora systemd[1]: Mounting boot.mount - /boot...
Jul 25 14:49:36 fedora kernel: EXT4-fs (vda2): recovery complete
Jul 25 14:49:36 fedora kernel: EXT4-fs (vda2): mounted filesystem cbb2caf6-429f-4a6a-acc4-9a20564c3f58 r/w with ordered data mode. Quota mode: none.
Jul 25 14:49:36 fedora systemd[1]: Mounted boot.mount - /boot.
Jul 25 14:49:37 fedora systemd[1]: var.mount: Directory /var to mount over is not empty, mounting anyway.
Jul 25 14:49:37 fedora systemd[1]: Mounting var.mount - /var...
Jul 25 14:49:37 fedora kernel: EXT4-fs (dm-8): mounted filesystem 0b8645c2-60d4-4d3a-bcdb-eb2355965ac4 r/w with ordered data mode. Quota mode: none.
Jul 25 14:49:37 fedora systemd[1]: Mounted var.mount - /var.
Jul 25 14:49:37 fedora systemd[1]: Starting dracut-pre-mount.service - dracut pre-mount hook...
Jul 25 14:49:37 fedora systemd[1]: Finished dracut-pre-mount.service - dracut pre-mount hook.
Jul 25 14:49:37 fedora systemd[1]: Mounting home.mount - /home...
Jul 25 14:49:37 fedora systemd[1]: Mounting sysroot.mount - /sysroot...
Jul 25 14:49:37 fedora kernel: EXT4-fs (dm-12): mounted filesystem c8c018f9-a3fc-4cab-9f71-700be61ee322 r/w with ordered data mode. Quota mode: none.
Jul 25 14:49:37 fedora systemd[1]: Mounted home.mount - /home.
Jul 25 14:49:37 fedora kernel: EXT4-fs (dm-3): orphan cleanup on readonly fs
Jul 25 14:49:37 fedora kernel: EXT4-fs (dm-3): mounted filesystem 89564248-d7dc-4e98-ba3a-f5901ef1f756 ro with ordered data mode. Quota mode: none.
Jul 25 14:49:37 fedora systemd[1]: Mounted sysroot.mount - /sysroot.
Jul 25 14:49:37 fedora systemd[1]: Starting initrd-parse-etc.service - Mountpoints Configured in the Real Root...
Jul 25 14:49:37 fedora systemd[1]: Finished initrd-parse-etc.service - Mountpoints Configured in the Real Root.
Jul 25 14:49:37 fedora systemd[1]: dracut-mount.service - dracut mount hook was skipped because no trigger condition checks were met.
Jul 25 14:49:37 fedora systemd[1]: dracut-pre-mount.service: Deactivated successfully.
Jul 25 14:49:37 fedora systemd[1]: Stopped dracut-pre-mount.service - dracut pre-mount hook.
Jul 25 14:49:37 fedora systemd[1]: Starting plymouth-switch-root.service - Plymouth switch root service...
Jul 25 14:49:37 fedora systemd[1]: Finished plymouth-switch-root.service - Plymouth switch root service.
Jul 25 14:49:37 fedora systemd[1]: Reached target initrd-switch-root.target - Switch Root.
Jul 25 14:49:37 fedora systemd[1]: Starting initrd-switch-root.service - Switch Root...
Jul 25 14:49:38 fedora kernel: EXT4-fs (vda2): unmounting filesystem cbb2caf6-429f-4a6a-acc4-9a20564c3f58.
Jul 25 14:49:38 fedora kernel: EXT4-fs (dm-8): unmounting filesystem 0b8645c2-60d4-4d3a-bcdb-eb2355965ac4.
Jul 25 14:49:38 fedora kernel: EXT4-fs (dm-12): unmounting filesystem c8c018f9-a3fc-4cab-9f71-700be61ee322.
Jul 25 14:49:38 fedora systemd[1]: Stopped initrd-switch-root.service - Switch Root.
Jul 25 14:49:38 fedora systemd[1]: Set up automount proc-sys-fs-binfmt_misc.automount - Arbitrary Executable File Formats File System Automount Point.
Jul 25 14:49:38 fedora systemd[1]: Stopped target initrd-switch-root.target - Switch Root.
Jul 25 14:49:38 fedora systemd[1]: Mounting dev-hugepages.mount - Huge Pages File System...
Jul 25 14:49:38 fedora systemd[1]: Mounting dev-mqueue.mount - POSIX Message Queue File System...
Jul 25 14:49:38 fedora systemd[1]: Mounting sys-kernel-debug.mount - Kernel Debug File System...
Jul 25 14:49:38 fedora systemd[1]: Mounting sys-kernel-tracing.mount - Kernel Trace File System...
Jul 25 14:49:38 fedora systemd[1]: Stopped plymouth-switch-root.service - Plymouth switch root service.
Jul 25 14:49:38 fedora systemd[1]: Mounted dev-hugepages.mount - Huge Pages File System.
Jul 25 14:49:38 fedora systemd[1]: Mounted dev-mqueue.mount - POSIX Message Queue File System.
Jul 25 14:49:38 fedora systemd[1]: Mounted sys-kernel-debug.mount - Kernel Debug File System.
Jul 25 14:49:38 fedora systemd[1]: Mounted sys-kernel-tracing.mount - Kernel Trace File System.
Jul 25 14:49:38 fedora systemd[1]: Mounting sys-fs-fuse-connections.mount - FUSE Control File System...
Jul 25 14:49:38 fedora systemd[1]: Mounted sys-fs-fuse-connections.mount - FUSE Control File System.
Jul 25 14:49:38 fedora systemd[1]: Mounting home.mount - /home...
Jul 25 14:49:38 fedora systemd[1]: Mounting var.mount - /var...
Jul 25 14:49:38 fedora kernel: EXT4-fs (dm-12): mounted filesystem c8c018f9-a3fc-4cab-9f71-700be61ee322 r/w with ordered data mode. Quota mode: none.
Jul 25 14:49:38 fedora kernel: EXT4-fs (dm-8): mounted filesystem 0b8645c2-60d4-4d3a-bcdb-eb2355965ac4 r/w with ordered data mode. Quota mode: none.
Jul 25 14:49:38 fedora systemd[1]: Mounted home.mount - /home.
Jul 25 14:49:38 fedora systemd[1]: Mounted var.mount - /var.
Jul 25 14:49:38 fedora systemd[1]: tmp.mount: Directory /tmp to mount over is not empty, mounting anyway.
Jul 25 14:49:38 fedora systemd[1]: Mounting tmp.mount - Temporary Directory /tmp...
Jul 25 14:49:38 fedora systemd[1]: Mounted tmp.mount - Temporary Directory /tmp.
Jul 25 14:49:38 fedora systemd[1]: Unmounting home.mount - /home...
Jul 25 14:49:38 fedora kernel: EXT4-fs (dm-12): unmounting filesystem c8c018f9-a3fc-4cab-9f71-700be61ee322.
Jul 25 14:49:38 fedora kernel: EXT4-fs (vda2): mounted filesystem cbb2caf6-429f-4a6a-acc4-9a20564c3f58 r/w with ordered data mode. Quota mode: none.
Jul 25 14:49:38 fedora systemd[1]: Mounting boot.mount - /boot...
Jul 25 14:49:38 fedora systemd[1]: home.mount: Deactivated successfully.
Jul 25 14:49:38 fedora systemd[1]: Unmounted home.mount - /home.
Jul 25 14:49:38 fedora systemd[1]: Mounted boot.mount - /boot.
Jul 25 14:49:38 fedora systemd[1]: Unmounting var.mount - /var...
Jul 25 14:49:38 fedora umount[807]: umount: /var: target is busy.
Jul 25 14:49:38 fedora systemd[1]: var.mount: Mount process exited, code=exited, status=32/n/a
Jul 25 14:49:38 fedora systemd[1]: Failed unmounting var.mount - /var.
```

(the umount for /var fails since the target is busy but /home is unmounted at the end of booting).

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #28516.

### CODE REVIEW

File: src/fstab-generator/fstab-generator.c [hunk 1]
```diff
@@ -987,13 +987,13 @@ static int parse_fstab(bool prefix_sysroot) {
...
                                     prefix_sysroot, /* use_swap_enabled = */ true);
-                if (r < 0 && ret >= 0)
+                if (r != 0 && ret >= 0)
                         ret = r;
                 if (arg_sysroot_check && r > 0)
                         return true;  /* We found a mount or swap that would be started… */
         }
 
-        return ret;
+        return ret; /* Return positive at least one entry found. */
```
Comment (bluca) [inline src/fstab-generator/fstab-generator.c]: "if at least one", same below

**Review by bluca — APPROVED** [review]

**Review by YHNdnzj — APPROVED** [review]

**Comment by yuwata** [comment]
@bluca @YHNdnzj Thank you for the review. I added one more fix and several test cases. Hence, dropped the green label. Please take another look.

File: src/fstab-generator/fstab-generator.c [hunk 2]
```diff
@@ -842,7 +850,8 @@ static int parse_fstab_one(
                 const char *fstype,
                 const char *options,
                 int passno,
-                bool initrd,
+                bool prefix_sysroot,
+                bool accept_root, /* This takes an effect only when prefix_root is true. */
```
Comment (YHNdnzj) [inline src/fstab-generator/fstab-generator.c]:
```suggestion
                bool accept_root, /* This takes an effect only when prefix_sysroot is true. */
```

**Review by YHNdnzj — APPROVED** [review]

File: src/fstab-generator/fstab-generator.c [hunk 3]
```diff
@@ -1544,21 +1548,18 @@ static int run_generator(void) {
                         ret = r;
         }
 
-        /* Honour /etc/fstab only when that's enabled */
-        if (arg_fstab_enabled) {
```
Comment (keszybz) [inline src/fstab-generator/fstab-generator.c:1548]: Hmm, I'm looking at the commit message, and it doesn't seem to agree with the code change. The commit message say "also honor fstab=no", which implies that some additional codepath is covered by the check. But in fact, the change moves the call to `generator_enable_remount_fs_service()` to not use the check.

File: man/systemd-fstab-generator.xml [hunk 4]
```diff
@@ -242,11 +242,14 @@
...
       <varlistentry>
         <term><varname>systemd.mount-extra=<replaceable>WHAT</replaceable>:<replaceable>WHERE</replaceable>[:<replaceable>FSTYPE</replaceable>[:<replaceable>OPTIONS</replaceable>]]</varname></term>
+        <term><varname>rd.systemd.mount-extra=<replaceable>WHAT</replaceable>:<replaceable>WHERE</replaceable>[:<replaceable>FSTYPE</replaceable>[:<replaceable>OPTIONS</replaceable>]]</varname></term>
 
         <listitem>
           <para>Specifies the mount unit. Takes at least two and at most four fields separated with a colon
           (<literal>:</literal>). Each field is handled as the corresponding fstab field. This option can be
-          specified multiple times.</para>
+          specified multiple times. <varname>rd.systemd.mount-extra=</varname> is honored only in the initrd,
+          while <varname>systemd.mount-extra=</varname> is honored by both the main system and the initrd.
```
Comment (keszybz) [inline man/systemd-fstab-generator.xml:251]: I think this needs to mention that in the initrd, `/sysroot` prefix is added automatically. Users might be surprised otherwise.

File: src/fstab-generator/fstab-generator.c [hunk 5]
```diff
@@ -1313,14 +1313,16 @@ static int add_mounts_from_cmdline(void) {
...
         _cleanup_free_ void *b = NULL;
         struct mntent *me;
         int r, ret = 0;
         size_t bs;
 
+        assert(in_initrd() || !prefix_sysroot);
+
         r = read_credential_with_decryption(
-                        in_initrd() ? "fstab.extra.initrd" : "fstab.extra",
+                        (in_initrd() && !prefix_sysroot) ? "fstab.extra.initrd" : "fstab.extra",
```
Comment (keszybz) [inline src/fstab-generator/fstab-generator.c]: `()` is not needed. I think it's well-known that `?:` has very low precedence.

File: src/fstab-generator/fstab-generator.c [hunk 6]
```diff
@@ -1347,11 +1347,11 @@ static int add_mounts_from_creds(bool prefix_sysroot) {
                                 /* prefix_sysroot = */ prefix_sysroot,
                                 /* accept_root = */ true,
                                 /* use_swap_enabled = */ true);
-                if (r < 0 && ret >= 0)
+                if (r != 0 && ret >= 0)
                         ret = r;
         }
 
-        return ret;
+        return ret; /* Return positive if at least one entry found. */
```
Comment (keszybz) [inline src/fstab-generator/fstab-generator.c]: I don't think this is going to work. We return the first error, or the true/false state. But we need to return both in parallel, i.e. we should set `enable_remount_fs` even if an unrelated error occured. I think the true/false info needs to be set via an output param.

**Review by keszybz — CHANGES_REQUESTED** [review]
Looks reasonable in general, but this is quite a bit of code churn. Do you want this for v254?

**Comment by bmr-cymru** [comment]
These changes fix `systemd.mount-extra=` for me and I can successfully boot a snapshot of the system with `fstab=no` and command line mount units as requested in #27260. Without these fixes the feature is not usable.

I confirmed with debug logging that the `systemd.mount-extra=` units are handled after switching root and that the generated units look sane. The system boots correctly into the snapshot state.

E.g. with `systemd.mount-extra=/dev/fedora/root-snap:/` I end up with the following generated unit

```
# Automatically generated by systemd-fstab-generator

[Unit]
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
SourcePath=/proc/cmdline
Before=local-fs.target
After=blockdev@dev-fedora-root\x2dsnap.target

[Mount]
What=/dev/fedora/root-snap
Where=/
Type=ext4
```

```
# systemctl status -- -.mount
● -.mount - Root Mount
     Loaded: loaded (/proc/cmdline; generated)
     Active: active (mounted)
      Where: /
       What: /dev/mapper/fedora-root--snap
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)
```

File: src/fstab-generator/fstab-generator.c (hunk 3 above)
Comment (yuwata) [reply src/fstab-generator/fstab-generator.c:1548]: OK. The change is dropped at least now. I will revisit here after the next release.

File: src/fstab-generator/fstab-generator.c (hunk 6 above)
Comment (yuwata) [reply src/fstab-generator/fstab-generator.c]: I noticed that systemd-remount-fs.service should not enabled when fstab=no even if systemd.mount-extra= or credential specifies mount points, as add_mount() honors specified mount options. The change is also dropped.

**Comment by yuwata** [comment]
@bmr-cymru Thank you for testing. Could you retest with the newer version of the patch set? I dropped the change about systemd-remount-fs.service, as the generator always honor the specified mount options, hence in your setup I guess the service is not necessary to be enabled.

**Comment by yuwata** [comment]
> Looks reasonable in general, but this is quite a bit of code churn. Do you want this for v254?

Unfortunately, yes. The current implementation of the systemd.mount-extra= or so is completely broken and cannot be used. Now I dropped two commits. And remaining commits are one trivial cleanup (renaming variables), clear bug fix (mount target of /sysroot/usr), implementation design fix (that's new part in this release, so we can and should fix), and test improvements.

**Review by keszybz — APPROVED** [review]
LGTM.

**Comment by keszybz** [comment]
The mkosi/ci (opensuse, tumbleweed) failure looks related:
```
[  OK  ] Mounted sysroot.mount.
         Mounting sysroot-usr.mount...
[  OK  ] Reached target initrd-root-fs.target.
         Starting initrd-parse-etc.service...
[FAILED] Failed to mount sysroot-usr.mount.
See 'systemctl status sysroot-usr.mount' for details.
[DEPEND] Dependency failed for initrd-fs.target.
```

Centos ci (centos stream 8) doesn't seem to be related, but seems like a real error too:
```
18:44:16 ======================================================================
18:44:16 FAIL: test_interleaved (__main__.ExecutionResumeTest)
18:44:16 ----------------------------------------------------------------------
18:44:16 Traceback (most recent call last):
18:44:16   File "./test/test-exec-deserialization.py", line 166, in test_interleaved
18:44:16     self.check_output(expected_output)
18:44:16   File "./test/test-exec-deserialization.py", line 112, in check_output
18:44:16     self.assertEqual(output, expected_output)
18:44:16 AssertionError: 'foo\n' != 'foo\nbar\n'
18:44:16   foo
18:44:16 + bar
```
I'll set the red flag, please unset it if the failures are unrelated.

**Comment by bmr-cymru** [comment]
The boot succeeds but the root filesystem remains read-only so it seems `systemd-remount-fs.service` is needed: a unit for the root file system is generated with the correct mount options but these are never applied.

Command line:

```
root=/dev/fedora/root-snap ro rd.lvm.lv=fedora/root-snap fstab=no systemd.mount-extra=/dev/fedora/root-snap:/:ext4:rw systemd.mount-extra=/dev/vda2:/boot:ext4:defaults systemd.mount-extra=/dev/fedora/var-snap:/var:ext4:defaults systemd.mount-extra=/dev/fedora/home-snap:/home:ext4:defaults
```

```
# grep fedora /proc/mounts 
/dev/mapper/fedora-root--snap / ext4 ro,seclabel,relatime 0 0
/dev/mapper/fedora-var--snap /var ext4 rw,seclabel,relatime 0 0
/dev/mapper/fedora-home--snap /home ext4 rw,seclabel,relatime 0 0
```

Root mount unit:

```
# Automatically generated by systemd-fstab-generator

[Unit]
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
SourcePath=/proc/cmdline
Before=local-fs.target
After=blockdev@dev-fedora-root\x2dsnap.target

[Mount]
What=/dev/fedora/root-snap
Where=/
Type=ext4
Options=rw
```

**Comment by bluca** [comment]
the suse sysroot-mount is pre-existing, has been failing since last week but it just used to get stuck and be cancelled, I've made it fail immediately instead with https://github.com/systemd/systemd/pull/28525

**Comment by yuwata** [comment]
@bmr-cymru `root=/dev/fedora/root-snap` needs to be dropped, otherwise the root mount specified in -extra is ignored.

**Comment by bluca** [comment]
> @bmr-cymru `root=/dev/fedora/root-snap` needs to be dropped, otherwise the root mount specified in -extra is ignored.

@bmr-cymru did you have a chance to try this?

**Comment by bmr-cymru** [comment]
Dropping `root=` causes the root file system to be mounted rw in the initramfs, and no fsck takes place:

```
Jul 27 11:56:09 fedora systemd[1]: Mounting sysroot.mount - /sysroot...
Jul 27 11:56:09 fedora systemd[1]: Mounted sysroot.mount - /sysroot.
Jul 27 11:56:09 fedora kernel: EXT4-fs (dm-3): mounted filesystem 9e2f7c99-9fa7-4dce-9c8f-f54b901a7948 r/w with ordered data mode. Quota mode: none.
Jul 27 11:56:09 fedora systemd[1]: Reached target initrd-root-fs.target - Initrd Root File System.
```

In a normal boot of the same system the initial ro is honoured as expected and systemd-fsck-root.service runs:

```
Jul 27 11:55:18 fedora systemd[1]: Starting systemd-fsck-root.service - File System Check on /dev/mapper/fedora-root...
Jul 27 11:55:18 fedora systemd-fsck[536]: /dev/mapper/fedora-root: clean, 38497/589824 files, 349388/2359296 blocks
Jul 27 11:55:18 fedora systemd[1]: Finished systemd-fsck-root.service - File System Check on /dev/mapper/fedora-root.
Jul 27 11:55:18 fedora systemd[1]: Mounting sysroot.mount - /sysroot...
Jul 27 11:55:18 fedora kernel: EXT4-fs (dm-1): orphan cleanup on readonly fs
Jul 27 11:55:18 fedora kernel: EXT4-fs (dm-1): mounted filesystem 9e2f7c99-9fa7-4dce-9c8f-f54b901a7948 ro with ordered data mode. Quota mode: none.
Jul 27 11:55:18 fedora systemd[1]: Mounted sysroot.mount - /sysroot.
Jul 27 11:55:18 fedora systemd[1]: Reached target initrd-root-fs.target - Initrd Root File System.
```

This isn't the behaviour I expect - I think this should mirror the case with normal fstab handling where root is mounted read-only, fscked and then remounted.

**Comment by bmr-cymru** [comment]
The behaviour with `root=` and pulling in `systemd-remount-fs.service` seems correct and very close to the normal case. It's also a lot less surprising for users and tools that manage boot entries.

**Comment by yuwata** [comment]
fsck + remount-fs.service thing needs to be addressed in other PR, possibly after the next release.
I will open an issue for reminder.

**Comment by bluca** [comment]
So is this ready to merge for the release then?

**Comment by poettering** [comment]
Hmm, I am pretty sure the non-prefixed kernel cmdline option should only be applied on the host, not the initrd. i.e. mount "rd." stuff only in initrd, and non-"rd." stuff only on host. Why that? simply because people might use this for loopback files or using fuse file systems which only work on the host because the files/infra only exists there. Trying to mount this ahead of time from the initrd sounds problematic hence, and likely wll result in failures.

Yes, I know we already released this, but I'd still change this.

**Comment by keszybz** [comment]
> Yes, I know we already released this, but I'd still change this.

Yeah, this is all still fresh and we can treat that as bugfix that'd go into v254.1 or .2.

**Comment by bmr-cymru** [comment]
fwiw in spite of what the documentation says I don't see mount units specified with `systemd.mount-extra=` being handled in the initrd on Fedora Rawhide with systemd-254.

Booting with the following command line:

```
root=/dev/fedora/root-snap ro rd.lvm.lv=fedora/root-snap fstab=no systemd.mount-extra=/dev/vda2:/boot:ext4:defaults systemd.mount-extra=/dev/fedora/var-snap:/var:ext4:defaults systemd.mount-extra=/dev/fedora/home-snap:/home:ext4:defaults console=tty1 console=ttyS1 rd.break
```

And stopping in the initrd with `rd.break` I see the following in `/run/systemd/generator`:

```
'dev-fedora-root\x2dsnap.device.d'
 initrd-root-device.target.d
 initrd-root-fs.target.requires
 initrd-usr-fs.target.requires
 initrd.target.wants
 sysroot.mount
 systemd-fsck-root.service
'systemd-fsck@dev-fedora-root\x2dsnap.service.d'
```
The `sysroot.mount` unit looks like this:

```
# Automatically generated by systemd-fstab-generator

[Unit]
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
SourcePath=/proc/cmdline
Before=initrd-root-fs.target
Requires=systemd-fsck-root.service
After=systemd-fsck-root.service
After=blockdev@dev-fedora-root\x2dsnap.target

[Mount]
What=/dev/fedora/root-snap
Where=/sysroot
Options=ro
```

The remaining command line units show up in `/run/systemd/generator` following the switch root:

```
boot.mount
dev-zram0.swap
getty.target.wants
home.mount
local-fs.target.requires
local-fs.target.wants
swap.target.wants
systemd-zram-setup@zram0.service.d
var.mount
```

**Comment by bmr-cymru** [comment]
Seems unrelated but I'm also seeing some breakage during shutdown on Rawhide for systems using LVM (doesn't happen with the default btrfs layout):

```
Failed to move /run/initramfs to /: Invalid argument
Failed to switch root to "/run/initramfs": Invalid argument
Unable to finalize remaining DM devices, ignoring.
```

Any idea what may be up here? This is a change from F38 (systemd-253) which seems to shut down cleanly and unmounts `/oldroot`:

```
[   16.575501] systemd-shutdown[1]: Cannot finalize remaining DM devices, continuing.
[   16.582055] systemd-shutdown[1]: Successfully changed into root pivot.
[   16.582611] systemd-shutdown[1]: Returning to initrd...
[   16.626087] dracut Warning: Killing all remaining processes
dracut Warning: Killing all remaining processes
[   16.666921] XFS (dm-0): Unmounting Filesystem c9c57660-4896-41e0-85af-3726333b3096
[   16.691707] dracut Warning: Unmounted /oldroot.
dracut Warning: Unmounted /oldroot.
[   16.703149] dracut: Disassembling device-mapper devices
[   16.706106] dm-0: detected capacity change from 18432000 to 0
Halting.
[   16.720147] kvm: exiting hardware virtualization
[   16.731507] reboot: System halted
```

**Comment by yuwata** [comment]
> Seems unrelated but I'm also seeing some breakage during shutdown on Rawhide for systems using LVM (doesn't happen with the default btrfs layout):
> 
> ```
> Failed to move /run/initramfs to /: Invalid argument
> Failed to switch root to "/run/initramfs": Invalid argument
> Unable to finalize remaining DM devices, ignoring.
> ```
> 
> Any idea what may be up here? This is a change from F38 (systemd-253) which seems to shut down cleanly and unmounts `/oldroot`:
> 
> ```
> [   16.575501] systemd-shutdown[1]: Cannot finalize remaining DM devices, continuing.
> [   16.582055] systemd-shutdown[1]: Successfully changed into root pivot.
> [   16.582611] systemd-shutdown[1]: Returning to initrd...
> [   16.626087] dracut Warning: Killing all remaining processes
> dracut Warning: Killing all remaining processes
> [   16.666921] XFS (dm-0): Unmounting Filesystem c9c57660-4896-41e0-85af-3726333b3096
> [   16.691707] dracut Warning: Unmounted /oldroot.
> dracut Warning: Unmounted /oldroot.
> [   16.703149] dracut: Disassembling device-mapper devices
> [   16.706106] dm-0: detected capacity change from 18432000 to 0
> Halting.
> [   16.720147] kvm: exiting hardware virtualization
> [   16.731507] reboot: System halted
> ```

That's #28645 and already fixed.

**Comment by yuwata** [comment]
> fwiw in spite of what the documentation says I don't see mount units specified with `systemd.mount-extra=` being handled in the initrd on Fedora Rawhide with systemd-254.
> 
> Booting with the following command line:
> 
> ```
> root=/dev/fedora/root-snap ro rd.lvm.lv=fedora/root-snap fstab=no systemd.mount-extra=/dev/vda2:/boot:ext4:defaults systemd.mount-extra=/dev/fedora/var-snap:/var:ext4:defaults systemd.mount-extra=/dev/fedora/home-snap:/home:ext4:defaults console=tty1 console=ttyS1 rd.break
> ```
> 
> And stopping in the initrd with `rd.break` I see the following in `/run/systemd/generator`:
> 
> ```
> 'dev-fedora-root\x2dsnap.device.d'
>  initrd-root-device.target.d
>  initrd-root-fs.target.requires
>  initrd-usr-fs.target.requires
>  initrd.target.wants
>  sysroot.mount
>  systemd-fsck-root.service
> 'systemd-fsck@dev-fedora-root\x2dsnap.service.d'
> ```
> 
> The `sysroot.mount` unit looks like this:
> 
> ```
> # Automatically generated by systemd-fstab-generator
> 
> [Unit]
> Documentation=man:fstab(5) man:systemd-fstab-generator(8)
> SourcePath=/proc/cmdline
> Before=initrd-root-fs.target
> Requires=systemd-fsck-root.service
> After=systemd-fsck-root.service
> After=blockdev@dev-fedora-root\x2dsnap.target
> 
> [Mount]
> What=/dev/fedora/root-snap
> Where=/sysroot
> Options=ro
> ```
> 
> The remaining command line units show up in `/run/systemd/generator` following the switch root:
> 
> ```
> boot.mount
> dev-zram0.swap
> getty.target.wants
> home.mount
> local-fs.target.requires
> local-fs.target.wants
> swap.target.wants
> systemd-zram-setup@zram0.service.d
> var.mount
> ```

That's expected, as in initrd mounts specified in systemd.mount-extra= are only taken into account if only it is for `/` or `/usr`. Though, that's not documented. But the behavior is the same as how we handle system's fstab file in initrd phase.

**Comment by yuwata** [comment]
> Hmm, I am pretty sure the non-prefixed kernel cmdline option should only be applied on the host, not the initrd. i.e. mount "rd." stuff only in initrd, and non-"rd." stuff only on host. Why that? simply because people might use this for loopback files or using fuse file systems which only work on the host because the files/infra only exists there. Trying to mount this ahead of time from the initrd sounds problematic hence, and likely wll result in failures.
> 
> Yes, I know we already released this, but I'd still change this.

@poettering and @keszybz 

I cannot follow. As commented in the above, currently mounts specified in systemd.mount-extra= are taken into account if it is only for `/` or `/usr`. That is, only necessary for switching root are mounted in initrd. The behavior is the same as how we handle system's fstab or `fstab.extra` creds.
If people wants to specify loopback block device, then that should be OK with the current form of the implementation. If people want to use loopback device as `/` or `/usr`, then the image must be accessible from initrd (same as fuse or so, people needs to install necessary files in initrd). There is nothing special. As if we want to mount btrfs from initrd, we need to install relevant kernel module and mount command into initrd. Conversely, if a loopback device is specified for non root or usr mount point, then it is completely ignored in initrd phase, and will be mounted after switching root.
I've not tested such setup, but loopback or fuse mount should also work in the current form, and I think there is nothing we need to 'revert' the change in this PR.

**Comment by poettering** [comment]
> fwiw in spite of what the documentation says I don't see mount units specified with `systemd.mount-extra=` being handled in the initrd on Fedora Rawhide with systemd-254.

did you rebuild the initrd with the new systemd inside it?

**Comment by poettering** [comment]
> I cannot follow. As commented in the above, currently mounts specified in systemd.mount-extra= are taken into account if it is only for `/` or `/usr`.

Ah, I didn't grok this. Makes sense then. (Though really documented, I guess)

It might make sense to introduce a proper "rd." prefix though

**Comment by bmr-cymru** [comment]
> > fwiw in spite of what the documentation says I don't see mount units specified with `systemd.mount-extra=` being handled in the initrd on Fedora Rawhide with systemd-254.
> 
> did you rebuild the initrd with the new systemd inside it?

Yes - I had the same misunderstanding that only `/` and `/usr` are handled in the initramfs, so that's behaving as I expected it.

**Comment by bmr-cymru** [comment]
> That's #28645 and already fixed.

Thanks! I just tested with the patches from #28645 and that fixes the problem for me.
