### PR TITLE
network: honor specified route table

### LINKED ISSUE #9552: SLAAC on VRF interfaces connected to the same network get routes wrong
**systemd version the issue has been seen with**
> 237-3ubuntu10

**Used distribution**
 > Ubuntu 18.04

**Config**

vrf-red.netdev:
```
[NetDev]
Name=red
Kind=vrf

[VRF]
Table=100
```
red.network:
```
[Match]
Name=red
```

vrf-blue.netdev:
```
[NetDev]
Name=blue
Kind=vrf

[VRF]
Table=101
```

blue.network:
```
[Match]
Name=blue
```

ens224.network:
```
[Match]
Name=ens224

[Network]
VRF=red
DHCP=no
Address=172.20.16.90/24
```

ens256.network:
```
[Match]
Name=ens256

[Network]
VRF=blue
DHCP=no
Address=172.20.16.91/24
```

**Expected behaviour you didn't see**

IPv6 network routes for interfaces bound into the VRF should only be installed in the VRFs routing table, not in the main table.

**Unexpected behaviour you saw**
 
IPv6 routes for VRF interfaces leaking into the main table:
```
$ ip -6 route
local ::1 dev lo proto kernel metric 256 pref medium
2001:470:7720:16::/64 dev ens256 proto ra metric 1024 pref medium
2001:470:7720:16::/64 dev ens224 proto ra metric 1024 pref medium
2001:470:7720:16::/64 dev ens192 proto ra metric 1024 pref medium
default proto ra metric 1024 
	nexthop via fe80::250:56ff:fea0:6a0a dev ens256 weight 1 
	nexthop via fe80::250:56ff:fea0:6a0a dev ens224 weight 1 
	nexthop via fe80::250:56ff:fea0:6a0a dev ens192 weight 1 
```

```
$ ip -6 route show vrf red
fe80::/64 dev ens224 proto kernel metric 256 pref medium
ff00::/8 dev ens224 metric 256 pref medium
```

```
$ ip -6 route show vrf blue
fe80::/64 dev ens256 proto kernel metric 256 pref medium
ff00::/8 dev ens256 metric 256 pref medium
```

**Steps to reproduce the problem**

* have two network interfaces connected to the same network segment
* have IPv6 SLAAC enable on that network segment
* configure VRFs (see above)
* restart networkd
* check main routing table, IPv6 routes for interfaces bound into VRFs should not be present in main table

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #9552.

### CODE REVIEW

**Comment by yuwata** [comment]
I've added tests for #9552, and it seems fixed now.

**Comment by yuwata** [comment]
@ssahani Could you review this?

File: src/network/networkd-dhcp6.c [hunk 1]
```diff
@@ -300,8 +302,19 @@ static int dhcp6_lease_pd_prefix_acquired(sd_dhcp6_client *client, Link *link) {
...
-                                  0, 0, 0, &route);
+                        table = link->network->dhcp_route_table;
+                        if (!link->network->dhcp_route_table_set && link->network->vrf)
+                                table = VRF(link->network->vrf)->table;
+
+                        r = route_add(link, AF_INET6, &pd_prefix, pd_prefix_len,
+                                      0, 0, table, &route);
+                        if (r < 0) {
+                                log_link_warning_errno(link, r, "Failed to add unreachable route for DHCPv6 delegated subnet %s/%u: %m",
+                                                       strnull(buf),
```
Comment (ssahani) [inline src/network/networkd-dhcp6.c:314]: Should not be the log like "Failed to add route "then errno should explain why failed ?

File: src/network/networkd-network.c [hunk 2]
```diff
@@ -1454,6 +1457,40 @@ int config_parse_dhcp_route_table(const char *unit,
...
+                           "Unable to read RouteTable, ignoring assignment: %s", rvalue);
+                return 0;
+        }
+
+        network->ipv6_accept_ra_route_table = rt;
+        network->ipv6_accept_ra_route_table_set = true;
+
+        return 0;
+}
+
```
Comment (ssahani) [inline src/network/networkd-network.c]: I think ```config_parse_ipv6_accept_ra_route_table``` and ```config_parse_dhcp_route_table``` can be merged depending on the section we set the value.

**Comment by ssahani** [comment]
Overall looks pretty good.  ```semaphoreci``` is falling  for some reason.  Please do a good round of test since it touching some critical modules.

File: src/network/networkd-manager.c [hunk 3]
```diff
@@ -558,34 +558,33 @@ int manager_rtnl_process_address(sd_netlink *rtnl, sd_netlink_message *message,
...
                                                     USEC_PER_SEC);
-        }
 
         (void) address_get(link, family, &in_addr, prefixlen, &address);
 
         switch (type) {
         case RTM_NEWADDR:
                 if (address)
-                        log_link_debug(link, "Updating address: %s/%u (valid %s%s)", buf, prefixlen,
+                        log_link_debug(link, "Updating address: %s/%hhu (valid %s%s)", buf, prefixlen,
```
Comment (poettering) [inline src/network/networkd-manager.c]: hmm, interesting. I wasn't aware of "hh" I must admit. And I am puzzled by it. I was sure there was the rule in C that integers shorter than "int"/"unsigned int" get expanded to "int"/"unsigned int" anyway when passed via varargs. So what does "hh" actually provide us with?

Comment (poettering) [reply src/network/networkd-manager.c]: Hmm, there's a discussion here:

https://stackoverflow.com/questions/4586962/what-is-the-purpose-of-the-h-and-hh-modifiers-for-printf

It's inconclusive, the way I read it?

i am tempted to say, adding "hh" everywhere is probably not worth the trouble? Or am I missingsomething?

File: src/network/networkd-ndisc.c [hunk 4]
```diff
@@ -300,6 +305,8 @@ static int ndisc_router_process_route(Link *link, sd_ndisc_router *rt) {
 
         route->family = AF_INET6;
         route->table = link->network->ipv6_accept_ra_route_table;
+        if (!link->network->ipv6_accept_ra_route_table_set && link->network->vrf)
+                route->table = VRF(link->network->vrf)->table;
```
Comment (poettering) [inline src/network/networkd-ndisc.c]: maybe add a helper macro/inline function NETWORK_VRF_TABLE() or so that checks for NULL as necessary, and dereives the table from the Network object in one go?

File: src/network/networkd-dhcp6.c (hunk 1 above)
Comment (yuwata) [reply src/network/networkd-dhcp6.c:314]: Hmm? What do you mean? The message already contains `%m`.

File: src/network/networkd-network.c (hunk 2 above)
Comment (yuwata) [reply src/network/networkd-network.c]: Nice!

File: src/network/networkd-manager.c (hunk 3 above)
Comment (yuwata) [reply src/network/networkd-manager.c]: OK. The changes are dropped at least from this PR.

File: src/network/networkd-ndisc.c (hunk 4 above)
Comment (yuwata) [reply src/network/networkd-ndisc.c]: Not inline or macro, but I've introduced helper functions in networkd-link.c.

**Comment by yuwata** [comment]
@ssahani and @poettering Thank you for the review. I've force-pushed the revised version. I hope most of the comments are addressed. PTAL.

File: src/network/networkd-dhcp6.c (hunk 1 above)
Comment (ssahani) [reply src/network/networkd-dhcp6.c:314]: ```unreachable ``` should not be there.

File: src/network/networkd-link.c [hunk 5]
```diff
@@ -70,6 +70,9 @@ static bool link_dhcp6_enabled(Link *link) {
         if (!link->network)
                 return false;
 
+        if (streq_ptr(link->kind, "vrf"))
+                return false;
```
Comment (ssahani) [inline src/network/networkd-link.c]: Why we want to disable on vrf  ?

**Comment by poettering** [comment]
looks good to me, but leaving unmerged, because @ssahani had questions

File: src/network/networkd-dhcp6.c (hunk 1 above)
Comment (yuwata) [reply src/network/networkd-dhcp6.c:314]: Why? The route will be set to `RTN_UNREACHABLE`. Of course, at this time the type is not set...
Note that I just copied the message from the above.

File: src/network/networkd-link.c (hunk 5 above)
Comment (yuwata) [reply src/network/networkd-link.c]: Oh, dropped.

Not sure, but `LinkLocalAddressing=` does not work on vrf devices. So, I thought vrf devices do not support addressing. But, it is wrong, hence, dropped. Thank you.

**Comment by yuwata** [comment]
Updated. Still @ssahani's comment about `unreachable` is not addressed. Changes are
- One more missing error check is added.
- Drop disabling vrf addressing.
- Disabling `LinkLocalAddressing=` in 25-vrf.network, as it does not work, though I do not know why.

File: src/network/networkd-dhcp6.c (hunk 1 above)
Comment (ssahani) [reply src/network/networkd-dhcp6.c:314]: yes .

File: src/network/networkd-link.c (hunk 5 above)
Comment (ssahani) [reply src/network/networkd-link.c]: No it's correct. Please include that .  I also didn't knew that they don't have LL addresses.
https://elixir.bootlin.com/linux/latest/source/drivers/net/vrf.c#L1089

**Comment by ssahani** [comment]
Please merge this including the VRF patch.

**Comment by yuwata** [comment]
@ssahani Thank you for the reference! Now the link local addressing is disabled on vrf devices. PTAL.

**Comment by ssahani** [comment]
Please merge. Thanks much.

**Comment by yuwata** [comment]
@ssahani Thank you for reviewing this so many times!

**Comment by yuwata** [comment]
I set the green label for this, but leave to merge for other reviewers. @poettering?
