### PR TITLE
networkd: fix DHCP on InfiniBand interfaces

### LINKED ISSUE #17322: networkd: DHCP on InfiniBand(IPoIB) interface does not work
**systemd version the issue has been seen with**
 > 246

**Used distribution**
 > Gentoo

**Linux kernel version used** (`uname -a`)
 > 5.4.70

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**

I was expecting networkd with DHCP=yes on an IB interface to successfully request an IP from a DHCP Server.
The DHCP server (Mellanox-Patched ISC DHCPd) is working fine for PXE boot and via dhclient.

**Unexpected behaviour you saw**

The DHCP server never sees any kind of request from the machine running the networkd DHCP client.
Additionally, when enabling debug logging in networkd, I can see it starting the "DHCP CLIENT", but after that it only ever logs about IPv6 RA. No sign of it actually sending any DHCP request(s).

**Steps to reproduce the problem**

Run networkd on any machine with an IPoIB interface, with the most basic DHCP=yes networkd config for the respective interface.
The used IB card is a ConnectX-4 VPI running with the in-kernel mlx5 driver with IPoIB enhancements enabled in my case.

### PR DESCRIPTION
**Pull request by BtbN**
With these patches applied, networkd is successfully able to get an address from a DHCP server on an IPoIB interface.

For one, networkd-dhcp4.c simply didn't pass on the actual interface type, and instead had it hardcoded to ARPHRD_ETHER.

On top of that, the dhcp handling code did not handle the MAC address entirely correct.
It insisted on its size in dhcp_network_bind_raw_socket, where it didn't even use it.

And in sd_dhcp_client_set_mac it also insists on it being the full 20 bytes, even though the systemd network code passes the "emulated" standard MAC address. Which for everything the DHCP client uses it for, is perfectly fine to use.

Fixes #17322.

### CODE REVIEW

**Comment by BtbN** [comment]
There's two things that are potentially still missing for full proper support.
One is reading and passing on the actual full 20 byte MAC address. Or at least the last 8 bytes of it.
For Client-ID generation only the last 8 bytes of that need to be passed on. Right now it will not generate the correct ClientID expected by a DHCP server which is assigning static leases.

The other is reading the broadcast address from the device somehow.
The default broadcast address built into the code right now is not always correct, and the actual one needs to be fetched from the device.

Both of these changes appear to require larger changes to the entire netlink interface, so I'm omitting them here.
Might take a look at them at some later point.

**Comment by BtbN** [comment]
Turns out the netlink stuff is fine, just cannot use the _ether functions to get the addresses.
So adding the full hw and bcast addresses to the Link struct is simple enough.

Passing in the actual broadcast address required some slightly wider changes, but nothing too crazy luckily.
With those additional changes DHCP now works even on interfaces which use a non-default broadcast address.
MAC-Based ClientID now also works correctly and matches what other DHCP clients send, instead of the truncated, always identical, first 6 byte of the Interface MAC.

What probably still does not work, because it uses the hardcoded 6 byte Ether-MAC-Struct, is DAD. Changing that seems like a much bigger endevaour.

File: src/libsystemd-network/sd-dhcp-client.c [hunk 1]
```diff
@@ -297,7 +300,9 @@ int sd_dhcp_client_set_mac(
                 return -EINVAL;
 
         if (client->mac_addr_len == addr_len &&
-            memcmp(&client->mac_addr, addr, addr_len) == 0)
+            memcmp(&client->mac_addr, addr, addr_len) == 0 &&
+            !!client->bcast_addr_len == !!bcast_addr &&
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-client.c]: `bcast_addr_len` is not a boolean or pointer, so please do as the following:
```
client->bcast_addr_len > 0 == !!bcast_addr
```

File: src/libsystemd-network/sd-dhcp-client.c [hunk 2]
```diff
@@ -306,6 +311,13 @@ int sd_dhcp_client_set_mac(
                 client_stop(client, SD_DHCP_CLIENT_EVENT_STOP);
         }
 
+        if (bcast_addr) {
+                client->bcast_addr_len = addr_len;
+                memcpy(&client->bcast_addr, bcast_addr, addr_len);
+        } else {
+                client->bcast_addr_len = 0;
+        }
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-client.c]: Please drop unnecessary `{}`:
```
} else
        client->bcast_addr_len = 0;
```

File: src/network/networkd-link.c [hunk 3]
```diff
@@ -421,6 +421,14 @@ static int link_new(Manager *manager, sd_netlink_message *message, Link **ret) {
...
 
+        r = sd_netlink_message_read_data(message, IFLA_ADDRESS, &link->hw_addr_len, (void **)&link->hw_addr);
+        if (r < 0)
+                log_link_debug_errno(link, r, "Hardware address not found for new device, continuing without");
+
+        r = sd_netlink_message_read_data(message, IFLA_BROADCAST, &link->bcast_addr_len, (void **)&link->bcast_addr);
+        if (r < 0)
+                log_link_debug_errno(link, r, "Broadcast address not found for new device, continuing without");
+
         r = sd_netlink_message_read_ether_addr(message, IFLA_ADDRESS, &link->mac);
```
Comment (yuwata) [inline src/network/networkd-link.c]: Hmm, the same attribute is read to `link->mac` and `link->hw_addr`. I think these should be merged.

File: src/libsystemd-network/dhcp-network.c [hunk 4]
```diff
@@ -115,34 +115,42 @@ static int _bind_raw_socket(int ifindex, union sockaddr_union *link,
...
-                bcast_addr = ib_bcast;
-                bcast_addr_len = INFINIBAND_ALEN;
+                default_bcast_addr = ib_bcast;
+                expected_bcast_addr_len = INFINIBAND_ALEN;
         } else
                 return -EINVAL;
 
+        if (bcast_addr && bcast_addr_len > 0) {
+                assert_return(bcast_addr_len == expected_bcast_addr_len, -EINVAL);
+        } else {
```
Comment (yuwata) [inline src/libsystemd-network/dhcp-network.c]: Please drop unnecessary `{}`:
```
if (bcast_addr && bcast_addr_len > 0)
        assert_return(...);
else {
        ...;
}
```

**Review by yuwata — CHANGES_REQUESTED** [review]
Superficially OK. But please address the several minor cosmetic issues below.
Also, please squash the commits.

File: src/libsystemd-network/dhcp-network.c [hunk 5]
```diff
@@ -104,9 +104,9 @@ static int _bind_raw_socket(int ifindex, union sockaddr_union *link,
                 .sll_protocol = htobe16(ETH_P_IP),
                 .sll_ifindex = ifindex,
                 .sll_hatype = htobe16(arp_type),
-                .sll_halen = mac_addr_len,
+                .sll_halen = bcast_addr_len,
         };
-        memcpy(link->ll.sll_addr, bcast_addr, mac_addr_len);
+        memcpy(link->ll.sll_addr, bcast_addr, bcast_addr_len);
```
Comment (poettering) [inline src/libsystemd-network/dhcp-network.c:109]: hmm, binding to the broadcast addr? can you explain?

File: src/libsystemd-network/dhcp-network.c [hunk 6]
```diff
@@ -19,9 +19,9 @@
 #include "unaligned.h"
```
Comment (poettering) [inline src/libsystemd-network/dhcp-network.c:19]: can you extend the commit msg here? i.e. move the explanatory stuff from the PR description into the commit descriptions please? (applies here and to the other commits a bit, too)

File: src/libsystemd-network/dhcp-network.c (hunk 5 above)
Comment (BtbN) [reply src/libsystemd-network/dhcp-network.c:109]: It's a raw/packet socket, and the broadcast address in this case is the hardware broadcast address (6 bytes of 0xFF in case of ethernet, something rather complex and not set in stone in the case of IB).
The initial discover is broadcasted out via this socket. Once the DHCP server is known normal UDP unicast is used.

**Comment by BtbN** [comment]
I can squash this down to one if that's preferred.
My idea with this split was to improve bisectability.

File: src/network/networkd-link.c (hunk 3 above)
Comment (BtbN) [reply src/network/networkd-link.c]: There are a lot of instances in the code which expect the "struct ether_addr". I guess one could just cast the uint8_t* to the struct whereever it's expected, since the memory layout seems compatible otherwise.
But I'm not sure if such a change should be part of this PR, or a follow up?

**Comment by poettering** [comment]
idea:

For IPv4/IPv6 addresses we added `union in_addr_union` as a type that can store either an ipv4 or an ipv6 address. Maybe we should take inspiration from that, and least in our internal code add `union hw_addr` that then consist of  a `struct ether_addr` or a `uint8_t infiniband[INFINIBAND_ALEN]` as alternatives (and whatever other hw addresses sooner or later for sure will pop up). 

The sd-dhcp API should probably stick to generic `uint8_t* hw_addr` style parameters, but at least the internal code would become a lot easier if we could just use a union that is appropriately sized.

**Comment by BtbN** [comment]
Yes, that would definitely be the cleaner solution.
The struct + union would also need a way to hold the length of the address though, unless you always want to infer that from the interface type.

**Comment by BtbN** [comment]
Added a union and struct, based on how it's done for in_addr_union/data and started using it for the Link struct.
Obviously there's _a lot_ of places where a 6 byte ethernet mac is a hardcoded expectation. For those I just pass it as is, which will behave like it behaves right now.
In the future, those places and functions can be gradually migrated to be aware of arbitrarily sized hardware addresses.

File: src/systemd/sd-netlink.h [hunk 7]
```diff
@@ -29,6 +29,8 @@
 
 _SD_BEGIN_DECLARATIONS;
 
+typedef struct hw_addr_data hw_addr_data;
```
Comment (yuwata) [inline src/systemd/sd-netlink.h]: Please do not export our internal data structure.

File: src/systemd/sd-netlink.h [hunk 8]
```diff
@@ -96,6 +98,7 @@ int sd_netlink_message_append_in6_addr(sd_netlink_message *m, unsigned short typ
 int sd_netlink_message_append_sockaddr_in(sd_netlink_message *m, unsigned short type, const struct sockaddr_in *data);
 int sd_netlink_message_append_sockaddr_in6(sd_netlink_message *m, unsigned short type, const struct sockaddr_in6 *data);
 int sd_netlink_message_append_ether_addr(sd_netlink_message *m, unsigned short type, const struct ether_addr *data);
+int sd_netlink_message_append_hw_addr(sd_netlink_message *m, unsigned short type, const hw_addr_data *data);
```
Comment (yuwata) [inline src/systemd/sd-netlink.h]: Please move this and `_read_hw_addr()` to src/libsystemd/sd-netlink/netlink-util.h.
Ans also drop `sd_` prefixes. See, e.g. `netlink_message_append_in_addr_union()` in netlink-util.h.

File: src/basic/ether-addr-util.h [hunk 9]
```diff
@@ -1,11 +1,25 @@
 /* SPDX-License-Identifier: LGPL-2.1+ */
 #pragma once
 
+#include <linux/if_infiniband.h>
 #include <net/ethernet.h>
 #include <stdbool.h>
 
 #include "hash-funcs.h"
 
+#define HW_ADDR_MAX_SIZE INFINIBAND_ALEN
```
Comment (yuwata) [inline src/basic/ether-addr-util.h]: Not a matter, but I prefer `CONST_MAX(ETH_ALEN, INFINIBAND_ALEN)` for readability. The macro is defined in macro.h.

File: src/network/networkd-address.c [hunk 10]
```diff
@@ -21,16 +22,24 @@ int generate_ipv6_eui_64_address(const Link *link, struct in6_addr *ret) {
         assert(link);
         assert(ret);
 
+        if (link->iftype == ARPHRD_INFINIBAND) {
+            /* see RFC4391 section 8 */
+            memcpy(&ret->s6_addr[8], &link->hw_addr.addr.infiniband[12], 8);
+            ret->s6_addr[8] ^= 1 << 1;
+
+            return 0;
+        }
```
Comment (yuwata) [inline src/network/networkd-address.c]: Indentation.

File: src/network/networkd-link.c [hunk 11]
```diff
@@ -2756,19 +2756,19 @@ int link_update(Link *link, sd_netlink_message *m) {
 
         /* The kernel may broadcast NEWLINK messages without the MAC address
            set, simply ignore them. */
-        r = sd_netlink_message_read_ether_addr(m, IFLA_ADDRESS, &mac);
-        if (r >= 0 && memcmp(link->mac.ether_addr_octet, mac.ether_addr_octet, ETH_ALEN) != 0) {
+        r = sd_netlink_message_read_hw_addr(m, IFLA_ADDRESS, &hw_addr);
+        if (r >= 0 && memcmp(link->hw_addr.addr.bytes, hw_addr.addr.bytes, hw_addr.length) != 0) {
```
Comment (yuwata) [inline src/network/networkd-link.c]: Please also compare the length.
```
if (r >= 0 && (link->hw_addr.length != hw_addr.length || memcmp(link->hw_addr.addr.bytes, hw_addr.addr.bytes, hw_addr.length) != 0))
```

File: src/network/networkd-link.c [hunk 12]
```diff
@@ -2756,19 +2756,19 @@ int link_update(Link *link, sd_netlink_message *m) {
...
-                               mac.ether_addr_octet[2],
-                               mac.ether_addr_octet[3],
-                               mac.ether_addr_octet[4],
-                               mac.ether_addr_octet[5]);
+                               hw_addr.addr.ether.ether_addr_octet[0],
+                               hw_addr.addr.ether.ether_addr_octet[1],
+                               hw_addr.addr.ether.ether_addr_octet[2],
+                               hw_addr.addr.ether.ether_addr_octet[3],
+                               hw_addr.addr.ether.ether_addr_octet[4],
+                               hw_addr.addr.ether.ether_addr_octet[5]);
```
Comment (yuwata) [inline src/network/networkd-link.c]: Not a matter, but maybe print all bytes (or last 8 bytes?) for infiniband case?

File: src/network/networkd-ndisc.c [hunk 13]
```diff
@@ -593,7 +594,11 @@ static int make_stableprivate_address(Link *link, const struct in6_addr *prefix,
         l = MAX(DIV_ROUND_UP(prefix_len, 8), 8);
         siphash24_compress(prefix, l, &state);
         siphash24_compress_string(link->ifname, &state);
-        siphash24_compress(&link->mac, sizeof(struct ether_addr), &state);
+        /* Only last 8 bytes of IB MAC are stable */
+        if (link->iftype == ARPHRD_INFINIBAND)
+            siphash24_compress(&link->hw_addr.addr.infiniband[12], 8, &state);
+        else
+            siphash24_compress(link->hw_addr.addr.bytes, link->hw_addr.length, &state);
```
Comment (yuwata) [inline src/network/networkd-ndisc.c]: Indentation.

**Review by yuwata — CHANGES_REQUESTED** [review]

File: src/basic/ether-addr-util.h (hunk 9 above)
Comment (BtbN) [reply src/basic/ether-addr-util.h]: That works, yeah.
I initially had it defined as `CONST_MAX(sizeof(struct ether_addr), INFINIBAND_ALEN)` which for some reason does not work.

File: src/systemd/sd-netlink.h (hunk 8 above)
Comment (BtbN) [reply src/systemd/sd-netlink.h]: There are a whole bunch of `sd_` prefixed functions which right now take a `struct ether_addr`.
For example `sd_ndisc_set_mac`, `sd_ipv4ll_set_mac` and a couple other.
To in the future migrate those to arbitrarily sized hardware addresses, wouldn't it be better to have the hw_addr_data structures at the same access level?
Or should they just take a uint8_t* and a length parameter?

**Comment by BtbN** [comment]
Changed it to internal functions now, making it more public is something that can be decided and done later on and is not really in the scope of fixing DHCP for IB anyway.

File: src/systemd/sd-netlink.h (hunk 8 above)
Comment (yuwata) [reply src/systemd/sd-netlink.h]: Let's update them later if necessary.

**Comment by yuwata** [comment]
LGTM, though I cannot test this, as I do not have infiniband interfaces. Maybe, we need to update `sd_xxx_set_mac()` for other engines, e.g., DHCP6 client. But let's do that later.

@poettering What do you think the above comment https://github.com/systemd/systemd/pull/17444#discussion_r511927542?

File: src/basic/ether-addr-util.h [hunk 14]
```diff
@@ -1,11 +1,25 @@
...
 
 #include "hash-funcs.h"
 
+#define HW_ADDR_MAX_SIZE CONST_MAX(ETH_ALEN, INFINIBAND_ALEN)
+
+union hw_addr_union {
+        struct ether_addr ether;
+        uint8_t infiniband[INFINIBAND_ALEN];
+        uint8_t bytes[HW_ADDR_MAX_SIZE];
+};
```
Comment (poettering) [inline src/basic/ether-addr-util.h:18]: makes sense

File: src/basic/ether-addr-util.h [hunk 15]
```diff
@@ -1,11 +1,25 @@
...
+
+typedef struct hw_addr_data {
+        union hw_addr_union addr;
+        size_t length;
+} hw_addr_data;
```
Comment (poettering) [inline src/basic/ether-addr-util.h:23]: why this? shouldn't the size be clear from context?

Comment (poettering) [reply src/basic/ether-addr-util.h:23]: mayba add:

```c
static inline size_t hw_addr_size(int iftype) {
        if (iftype == ARPHRD_ETHER)
                return sizeof(struct ether_addr);
        if (iftype == ARPHRD_INFINIBAND)
                return INFINIBAND_ALEN;
        return 0;
}
```

or so, to have a simple macro-like helper that derives the right size from the iftype?
}

File: src/network/networkd-link.c [hunk 16]
```diff
@@ -2756,19 +2756,35 @@ int link_update(Link *link, sd_netlink_message *m) {
...
+                                       hw_addr.addr.infiniband[18], hw_addr.addr.infiniband[19]);
+                else
+                        log_link_debug(link, "Gained new MAC address: "
+                                       "%02hhx:%02hhx:%02hhx:%02hhx:%02hhx:%02hhx",
+                                       hw_addr.addr.ether.ether_addr_octet[0],
+                                       hw_addr.addr.ether.ether_addr_octet[1],
+                                       hw_addr.addr.ether.ether_addr_octet[2],
+                                       hw_addr.addr.ether.ether_addr_octet[3],
+                                       hw_addr.addr.ether.ether_addr_octet[4],
+                                       hw_addr.addr.ether.ether_addr_octet[5]);
```
Comment (poettering) [inline src/network/networkd-link.c]: maybe add hw_addr_format() or so, that does this formatting?

**Review by poettering — CHANGES_REQUESTED** [review]

File: src/basic/ether-addr-util.h (hunk 15 above)
Comment (BtbN) [reply src/basic/ether-addr-util.h:23]: I think it's worth having the size there still, even if purely as a sanity check.
There's a couple places that sanity-check the address length against the interface type already, so if that length then gets derived from the iftype initially, that becomes kinda pointless.

It also simplifies the code a bit, specially when the hw_addr is to be used in places that right now use the iftype.

File: src/network/networkd-link.c (hunk 16 above)
Comment (BtbN) [reply src/network/networkd-link.c]: Yeah, something that dynamically prints it is definitely needed.
I'll see if I can come up with something nicer.

File: src/basic/ether-addr-util.h (hunk 15 above)
Comment (yuwata) [reply src/basic/ether-addr-util.h:23]: Hmm, I agree with the suggestion by @poettering. The functions `netlink_message_read_in_addr_union()` or `_append_` take family `AF_INET` or `AF_INET6`. So, similarly, the new functions should take iftype.

Comment (BtbN) [reply src/basic/ether-addr-util.h:23]: I'm really not sure about that.
Doing it that way would add a lot of complexity and logic in places that don't otherwise need it.
See for example the print functions I just added and their example usage in the networkctl status output.
That code right now does not need to care about the iftype, but if it would, it would need changed every time a new iftype gets supported.

Comment (BtbN) [reply src/basic/ether-addr-util.h:23]: I'm also somewhat afraid that changing it to behave like it does for in_addr_union, where the family, or in this case iftype, is passed along everywhere causes a chain of regressions where formally implicitly supported interface types that behave like ethernet (I see references to CAN, PPP, WiFi-Devices and probably some tunnel devices) will then cause assertions because it's neither ETHER nor INFINIBAND, and compiling the full list everywhere seems way worse than just carrying along the size.

Comment (yuwata) [reply src/basic/ether-addr-util.h:23]: OK. After grepping kernel codes, the length of `IFLA_ADDRESS` may have variety of length. I changed my mind. Let's keep this as is at least now.

File: src/basic/ether-addr-util.c [hunk 17]
```diff
@@ -9,6 +10,20 @@
...
 
+char* hw_addr_to_string(const hw_addr_data *addr, char buffer[HW_ADDR_TO_STRING_MAX]) {
+        assert(addr);
+        assert(buffer);
+        assert(addr->length <= HW_ADDR_MAX_SIZE);
+
+        for (size_t i = 0; i < addr->length; i++) {
+            sprintf(&buffer[3*i], "%02"PRIx8, addr->addr.bytes[i]);
+            if (i < addr->length - 1)
+                buffer[3*i + 2] = ':';
```
Comment (yuwata) [inline src/basic/ether-addr-util.c]: indentation.

File: src/basic/ether-addr-util.h [hunk 18]
```diff
@@ -1,11 +1,31 @@
...
+
+#define HW_ADDR_TO_STRING_MAX (3*HW_ADDR_MAX_SIZE)
+char* hw_addr_to_string(const hw_addr_data *addr, char buffer[HW_ADDR_TO_STRING_MAX]);
+
+/* Use only as function argument, never stand-alone! */
+#define HW_ADDR_TO_STR(hw_addr) hw_addr_to_string((hw_addr), (char[HW_ADDR_TO_STRING_MAX]){0})
```
Comment (yuwata) [inline src/basic/ether-addr-util.h]: Hmm, I do not like this... Why do not you do like the following? At least, we usually drop 0 in `{}`.
```
char buf[HW_ADDR_TO_STRING_MAX] = {};

log_link_debug("...: %s", hw_addr_to_string(&hw_addr, buf));
```

**Review by yuwata — CHANGES_REQUESTED** [review]

**Comment by BtbN** [comment]
For reference, log of a successful DHCP session on an IPoIB device:

<details>

```
sd-device-monitor: No permission to stat PID1's netns, unable to determine if we are in host netns: Permission denied
Bus bus-api-network: changing state UNSET → OPENING
sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Bus bus-api-network: changing state OPENING → AUTHENTICATING
Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
timestamp of '/etc/systemd/network' changed
Failed to read $container of PID 1, ignoring: Permission denied
Found container virtualization none.
No virtualization found in DMI
No virtualization found in CPUID
Virtualization XEN not found, /proc/xen does not exist
This platform does not support /proc/device-tree
UML virtualization not found in /proc/cpuinfo.
This platform does not support /proc/sysinfo
Found VM virtualization none
/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
ibp1s0: New device has no master, continuing without
ibp1s0: Permanent MAC address not found for new device, continuing without: Operation not supported
ibp1s0: Flags change: +UP +LOWER_UP +RUNNING +MULTICAST +BROADCAST
ibp1s0: Link 4 added
ibp1s0: udev initialized link
ibp1s0: State changed: pending -> initialized
ibp1s0: Saved original MTU: 4092
eno2np1: New device has no master, continuing without
eno2np1: Flags change: +MULTICAST +BROADCAST
eno2np1: Link 3 added
eno2np1: udev initialized link
eno2np1: State changed: pending -> initialized
eno2np1: Saved original MTU: 1500
eno1np0: New device has no master, continuing without
eno1np0: Flags change: +UP +LOWER_UP +RUNNING +MULTICAST +BROADCAST
eno1np0: Link 2 added
eno1np0: udev initialized link
eno1np0: State changed: pending -> initialized
eno1np0: Saved original MTU: 9000
lo: New device has no master, continuing without
lo: Failed to get driver, continuing without: Operation not supported
lo: Flags change: +LOOPBACK +UP +LOWER_UP +RUNNING
lo: Link 1 added
lo: udev initialized link
lo: State changed: pending -> initialized
lo: Saved original MTU: 65536
ibp1s0: Remembering foreign address: fe80::e207:1bff:ff70:54e0/64 (valid forever)
ibp1s0: link_check_ready(): link is in initialized state.
ibp1s0: Gained IPv6LL
ibp1s0: link_check_ready(): link is in initialized state.
eno1np0: Remembering foreign address: fe80::3eec:efff:fe46:891c/64 (valid forever)
eno1np0: link_check_ready(): link is in initialized state.
eno1np0: Gained IPv6LL
eno1np0: link_check_ready(): link is in initialized state.
lo: Remembering foreign address: ::1/128 (valid forever)
lo: link_check_ready(): link is in initialized state.
ibp1s0: Remembering foreign address: 10.110.10.202/24 (valid forever)
ibp1s0: link_check_ready(): link is in initialized state.
eno1np0: Remembering foreign address: 10.110.12.2/24 (valid forever)
eno1np0: link_check_ready(): link is in initialized state.
lo: Remembering foreign address: 127.0.0.1/8 (valid forever)
lo: link_check_ready(): link is in initialized state.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
eno1np0: Remembering route: dst: ff00::/8, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: boot, type: unicast
ibp1s0: Remembering route: dst: ff00::/8, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: boot, type: unicast
eno1np0: Remembering route: dst: fe80::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
ibp1s0: Remembering route: dst: fe80::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
ibp1s0: Remembering route: dst: fe80::e207:1bff:ff70:54e0/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: local
eno1np0: Remembering route: dst: fe80::3eec:efff:fe46:891c/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: local
lo: Remembering route: dst: ::1/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
lo: Remembering route: dst: ::1/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: local
lo: Remembering route: dst: 127.255.255.255/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: link, table: local, proto: kernel, type: broadcast
lo: Remembering route: dst: 127.0.0.1/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: host, table: local, proto: kernel, type: local
lo: Remembering route: dst: 127.0.0.0/8, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: host, table: local, proto: kernel, type: local
lo: Remembering route: dst: 127.0.0.0/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: link, table: local, proto: kernel, type: broadcast
eno1np0: Remembering route: dst: 10.110.12.255/32, src: n/a, gw: n/a, prefsrc: 10.110.12.2, scope: link, table: local, proto: kernel, type: broadcast
eno1np0: Remembering route: dst: 10.110.12.2/32, src: n/a, gw: n/a, prefsrc: 10.110.12.2, scope: host, table: local, proto: kernel, type: local
eno1np0: Remembering route: dst: 10.110.12.0/32, src: n/a, gw: n/a, prefsrc: 10.110.12.2, scope: link, table: local, proto: kernel, type: broadcast
ibp1s0: Remembering route: dst: 10.110.10.255/32, src: n/a, gw: n/a, prefsrc: 10.110.10.202, scope: link, table: local, proto: kernel, type: broadcast
ibp1s0: Remembering route: dst: 10.110.10.202/32, src: n/a, gw: n/a, prefsrc: 10.110.10.202, scope: host, table: local, proto: kernel, type: local
ibp1s0: Remembering route: dst: 10.110.10.0/32, src: n/a, gw: n/a, prefsrc: 10.110.10.202, scope: link, table: local, proto: kernel, type: broadcast
eno1np0: Remembering route: dst: 10.110.12.0/24, src: n/a, gw: n/a, prefsrc: 10.110.12.2, scope: link, table: main, proto: kernel, type: unicast
ibp1s0: Remembering route: dst: 10.110.10.0/24, src: n/a, gw: n/a, prefsrc: 10.110.10.202, scope: link, table: main, proto: kernel, type: unicast
ibp1s0: Remembering route: dst: n/a, src: n/a, gw: 10.110.10.250, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
rtnl: received rule message with invalid family 128, ignoring.
Remembering foreign routing policy rule: priority: 32767, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: 253
Remembering foreign routing policy rule: priority: 32766, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: 254
Remembering foreign routing policy rule: priority: 0, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: 255
Enumeration completed
Bus bus-api-network: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RequestName cookie=2 reply_cookie=0 signature=su error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=4 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=5 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=6 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=7 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=8 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=10 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=11 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=12 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=13 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=14 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=15 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=16 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
ibp1s0: Link state is up-to-date
ibp1s0: found matching network '/etc/systemd/network/50-internal.network'
Setting '/proc/sys/net/ipv6/conf/ibp1s0/disable_ipv6' to '0'
Setting '/proc/sys/net/ipv6/conf/ibp1s0/use_tempaddr' to '0'
Setting '/proc/sys/net/ipv6/conf/ibp1s0/accept_ra' to '0'
Setting '/proc/sys/net/ipv6/conf/ibp1s0/proxy_ndp' to '0'
ibp1s0: Setting nomaster
ibp1s0: Setting address genmode for link
ibp1s0: Failed to read sysctl property stable_secret: Input/output error
Got message type=method_return sender=org.freedesktop.DBus destination=:1.283 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus bus-api-network: changing state HELLO → RUNNING
Got message type=signal sender=org.freedesktop.DBus.Local destination=n/a path=/org/freedesktop/DBus/Local interface=org.freedesktop.DBus.Local member=Connected cookie=4294967295 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.DBus destination=:1.283 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.DBus destination=:1.283 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.283 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=2 signature=u error-name=n/a error-message=n/a
Successfully acquired requested service name.
Got message type=method_return sender=org.freedesktop.DBus destination=:1.283 path=n/a interface=n/a member=n/a cookie=5 reply_cookie=3 signature=n/a error-name=n/a error-message=n/a
Match type='signal',sender='org.freedesktop.login1',path='/org/freedesktop/login1',interface='org.freedesktop.login1.Manager',member='PrepareForSleep' successfully installed.
eno2np1: Link state is up-to-date
eno2np1: State changed: initialized -> unmanaged
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=17 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
eno1np0: Link state is up-to-date
eno1np0: found matching network '/etc/systemd/network/50-failover.network'
Setting '/proc/sys/net/ipv6/conf/eno1np0/disable_ipv6' to '0'
Setting '/proc/sys/net/ipv6/conf/eno1np0/use_tempaddr' to '0'
Setting '/proc/sys/net/ipv6/conf/eno1np0/accept_ra' to '0'
Setting '/proc/sys/net/ipv6/conf/eno1np0/proxy_ndp' to '0'
eno1np0: Setting nomaster
LLDP: Started LLDP client
eno1np0: Started LLDP.
eno1np0: Setting address genmode for link
eno1np0: Failed to read sysctl property stable_secret: Input/output error
lo: Link state is up-to-date
lo: State changed: initialized -> unmanaged
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=18 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
ibp1s0: Setting nomaster done.
ibp1s0: Setting address genmode done.
ibp1s0: Removing address 10.110.10.202
ibp1s0: Removing route: dst: n/a, src: n/a, gw: 10.110.10.250, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
ibp1s0: State changed: initialized -> configuring
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=19 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
ibp1s0: Acquiring DHCPv4 lease
DHCP CLIENT (0x328fcecd): STARTED on ifindex 4
ibp1s0: Discovering IPv6 routers
NDISC: Started IPv6 Router Solicitation client
ibp1s0: link_check_ready(): static addresses are not configured.
ibp1s0: link_check_ready(): static addresses are not configured.
ibp1s0: link_check_ready(): DHCP4 or DHCP6 is enabled but no dynamic address is assigned yet.
DHCP CLIENT (0x328fcecd): DISCOVER
eno1np0: Setting nomaster done.
eno1np0: Setting address genmode done.
eno1np0: State changed: initialized -> configuring
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=20 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
eno1np0: Discovering IPv6 routers
NDISC: Started IPv6 Router Solicitation client
eno1np0: link_check_ready(): static addresses are not configured.
eno1np0: link_check_ready(): static addresses are not configured.
eno1np0: Updating address: 10.110.12.2
eno1np0: Setting addresses
ibp1s0: Forgetting address: 10.110.10.202/24 (valid forever)
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=21 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
ibp1s0: Forgetting route: dst: 10.110.10.0/24, src: n/a, gw: n/a, prefsrc: 10.110.10.202, scope: link, table: main, proto: kernel, type: unicast
ibp1s0: Forgetting route: dst: 10.110.10.255/32, src: n/a, gw: n/a, prefsrc: 10.110.10.202, scope: link, table: local, proto: kernel, type: broadcast
ibp1s0: Forgetting route: dst: 10.110.10.0/32, src: n/a, gw: n/a, prefsrc: 10.110.10.202, scope: link, table: local, proto: kernel, type: broadcast
ibp1s0: Forgetting route: dst: 10.110.10.202/32, src: n/a, gw: n/a, prefsrc: 10.110.10.202, scope: host, table: local, proto: kernel, type: local
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
eno1np0: Remembering updated address: 10.110.12.2/24 (valid forever)
eno1np0: link_check_ready(): static addresses are not configured.
eno1np0: Addresses set
eno1np0: link_check_ready(): dynamic addresses or routes are not configured.
DHCP CLIENT (0x328fcecd): OFFER
NDISC: Sent Router Solicitation, next solicitation in 3s
NDISC: Sent Router Solicitation, next solicitation in 4s
DHCP CLIENT (0x328fcecd): REQUEST (requesting)
DHCP CLIENT (0x328fcecd): ACK
DHCP CLIENT (0x328fcecd): lease expires in 59min 57s
DHCP CLIENT (0x328fcecd): T2 expires in 52min 27s
DHCP CLIENT (0x328fcecd): T1 expires in 29min 58s
ibp1s0: DHCPv4 address 10.110.10.170/24 via 10.110.10.250
ibp1s0: Updating address: 10.110.10.170
ibp1s0: Remembering updated address: 10.110.10.170/24 (valid for 1h)
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=22 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
ibp1s0: link_check_ready(): static routes are not configured.
ibp1s0: Remembering route: dst: 10.110.10.170/32, src: n/a, gw: n/a, prefsrc: 10.110.10.170, scope: host, table: local, proto: kernel, type: local
ibp1s0: Remembering route: dst: 10.110.10.255/32, src: n/a, gw: n/a, prefsrc: 10.110.10.170, scope: link, table: local, proto: kernel, type: broadcast
ibp1s0: Remembering route: dst: 10.110.10.0/24, src: n/a, gw: n/a, prefsrc: 10.110.10.170, scope: link, table: main, proto: kernel, type: unicast
ibp1s0: Remembering route: dst: 10.110.10.0/32, src: n/a, gw: n/a, prefsrc: 10.110.10.170, scope: link, table: local, proto: kernel, type: broadcast
ibp1s0: DHCP: No routes received from DHCP server: No data available
ibp1s0: Configuring route: dst: 10.110.10.250/32, src: n/a, gw: n/a, prefsrc: 10.110.10.170, scope: link, table: main, proto: dhcp, type: unicast
ibp1s0: Configuring route: dst: n/a, src: n/a, gw: 10.110.10.250, prefsrc: 10.110.10.170, scope: global, table: main, proto: dhcp, type: unicast
ibp1s0: link_check_ready(): dynamic addresses or routes are not configured.
ibp1s0: Received remembered route: dst: 10.110.10.250/32, src: n/a, gw: n/a, prefsrc: 10.110.10.170, scope: link, table: main, proto: dhcp, type: unicast
ibp1s0: Received remembered route: dst: n/a, src: n/a, gw: 10.110.10.250, prefsrc: 10.110.10.170, scope: global, table: main, proto: dhcp, type: unicast
ibp1s0: link_check_ready(): dhcp4:yes dhcp6_addresses:no dhcp_routes:no dhcp_pd_addresses:no dhcp_pd_routes:no ndisc_addresses:no ndisc_routes:no
ibp1s0: State changed: configuring -> configured
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=23 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
LLDP: Successfully processed LLDP datagram.
NDISC: Sent Router Solicitation, next solicitation in 7s
rtnl: received non-static neighbor, ignoring.
NDISC: Sent Router Solicitation, next solicitation in 8s
NDISC: Sent Router Solicitation, next solicitation in 13s
NDISC: No RA received before link confirmation timeout
NDISC: Invoking callback for 'timeout' event.
ibp1s0: NDisc handler get timeout event
NDISC: No RA received before link confirmation timeout
NDISC: Invoking callback for 'timeout' event.
eno1np0: NDisc handler get timeout event
eno1np0: link_check_ready(): dhcp4:no dhcp6_addresses:no dhcp_routes:no dhcp_pd_addresses:no dhcp_pd_routes:no ndisc_addresses:yes ndisc_routes:yes
eno1np0: State changed: configuring -> configured
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=24 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
NDISC: Started IPv6 Router Solicitation client
ibp1s0: link_check_ready(): static addresses are not configured.
ibp1s0: link_check_ready(): static addresses are not configured.
ibp1s0: link_check_ready(): DHCP4 or DHCP6 is enabled but no dynamic address is assigned yet.
DHCP CLIENT (0x328fcecd): DISCOVER
eno1np0: Setting nomaster done.
eno1np0: Setting address genmode done.
eno1np0: State changed: initialized -> configuring
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=20 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
eno1np0: Discovering IPv6 routers
NDISC: Started IPv6 Router Solicitation client
eno1np0: link_check_ready(): static addresses are not configured.
eno1np0: link_check_ready(): static addresses are not configured.
eno1np0: Updating address: 10.110.12.2
eno1np0: Setting addresses
ibp1s0: Forgetting address: 10.110.10.202/24 (valid forever)
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=21 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
ibp1s0: Forgetting route: dst: 10.110.10.0/24, src: n/a, gw: n/a, prefsrc: 10.110.10.202, scope: link, table: main, proto: kernel, type: unicast
ibp1s0: Forgetting route: dst: 10.110.10.255/32, src: n/a, gw: n/a, prefsrc: 10.110.10.202, scope: link, table: local, proto: kernel, type: broadcast
ibp1s0: Forgetting route: dst: 10.110.10.0/32, src: n/a, gw: n/a, prefsrc: 10.110.10.202, scope: link, table: local, proto: kernel, type: broadcast
ibp1s0: Forgetting route: dst: 10.110.10.202/32, src: n/a, gw: n/a, prefsrc: 10.110.10.202, scope: host, table: local, proto: kernel, type: local
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
eno1np0: Remembering updated address: 10.110.12.2/24 (valid forever)
eno1np0: link_check_ready(): static addresses are not configured.
eno1np0: Addresses set
eno1np0: link_check_ready(): dynamic addresses or routes are not configured.
DHCP CLIENT (0x328fcecd): OFFER
NDISC: Sent Router Solicitation, next solicitation in 3s
NDISC: Sent Router Solicitation, next solicitation in 4s
DHCP CLIENT (0x328fcecd): REQUEST (requesting)
DHCP CLIENT (0x328fcecd): ACK
DHCP CLIENT (0x328fcecd): lease expires in 59min 57s
DHCP CLIENT (0x328fcecd): T2 expires in 52min 27s
DHCP CLIENT (0x328fcecd): T1 expires in 29min 58s
ibp1s0: DHCPv4 address 10.110.10.170/24 via 10.110.10.250
ibp1s0: Updating address: 10.110.10.170
ibp1s0: Remembering updated address: 10.110.10.170/24 (valid for 1h)
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=22 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
ibp1s0: link_check_ready(): static routes are not configured.
ibp1s0: Remembering route: dst: 10.110.10.170/32, src: n/a, gw: n/a, prefsrc: 10.110.10.170, scope: host, table: local, proto: kernel, type: local
ibp1s0: Remembering route: dst: 10.110.10.255/32, src: n/a, gw: n/a, prefsrc: 10.110.10.170, scope: link, table: local, proto: kernel, type: broadcast
ibp1s0: Remembering route: dst: 10.110.10.0/24, src: n/a, gw: n/a, prefsrc: 10.110.10.170, scope: link, table: main, proto: kernel, type: unicast
ibp1s0: Remembering route: dst: 10.110.10.0/32, src: n/a, gw: n/a, prefsrc: 10.110.10.170, scope: link, table: local, proto: kernel, type: broadcast
ibp1s0: DHCP: No routes received from DHCP server: No data available
ibp1s0: Configuring route: dst: 10.110.10.250/32, src: n/a, gw: n/a, prefsrc: 10.110.10.170, scope: link, table: main, proto: dhcp, type: unicast
ibp1s0: Configuring route: dst: n/a, src: n/a, gw: 10.110.10.250, prefsrc: 10.110.10.170, scope: global, table: main, proto: dhcp, type: unicast
ibp1s0: link_check_ready(): dynamic addresses or routes are not configured.
ibp1s0: Received remembered route: dst: 10.110.10.250/32, src: n/a, gw: n/a, prefsrc: 10.110.10.170, scope: link, table: main, proto: dhcp, type: unicast
ibp1s0: Received remembered route: dst: n/a, src: n/a, gw: 10.110.10.250, prefsrc: 10.110.10.170, scope: global, table: main, proto: dhcp, type: unicast
ibp1s0: link_check_ready(): dhcp4:yes dhcp6_addresses:no dhcp_routes:no dhcp_pd_addresses:no dhcp_pd_routes:no ndisc_addresses:no ndisc_routes:no
ibp1s0: State changed: configuring -> configured
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=23 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
LLDP: Successfully processed LLDP datagram.
NDISC: Sent Router Solicitation, next solicitation in 7s
rtnl: received non-static neighbor, ignoring.
NDISC: Sent Router Solicitation, next solicitation in 8s
NDISC: Sent Router Solicitation, next solicitation in 13s
NDISC: No RA received before link confirmation timeout
NDISC: Invoking callback for 'timeout' event.
ibp1s0: NDisc handler get timeout event
NDISC: No RA received before link confirmation timeout
NDISC: Invoking callback for 'timeout' event.
eno1np0: NDisc handler get timeout event
eno1np0: link_check_ready(): dhcp4:no dhcp6_addresses:no dhcp_routes:no dhcp_pd_addresses:no dhcp_pd_routes:no ndisc_addresses:yes ndisc_routes:yes
eno1np0: State changed: configuring -> configured
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=24 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
NDISC: Sent Router Solicitation, next solicitation in 15s
NDISC: Sent Router Solicitation, next solicitation in 28s
NDISC: Sent Router Solicitation, next solicitation in 32s
LLDP: Successfully processed LLDP datagram.
```

</details>

networkctl status output for the device:

<details>

```
# ./build/networkctl status ibp1s0
● 4: ibp1s0
                     Link File: /lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/50-internal.network
                          Type: infiniband
                         State: routable (configured)
                          Path: pci-0000:01:00.0
                        Driver: mlx5_core[ib_ipoib]
                        Vendor: Mellanox Technologies
                         Model: MT27700 Family [ConnectX-4]
                    HW Address: 00:00:03:2a:fe:80:00:00:00:00:00:00:xx:xx:xx:ff:ff:xx:xx:xx
                           MTU: 4092 (min: 68, max: 65520)
                         QDisc: mq
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 256/32
              Auto negotiation: no
                         Speed: 100Gbps
                        Duplex: full
                       Address: 10.110.10.170 (DHCP4 via 10.110.10.251)
                                fe80::x2xx:xxff:ffxx:xxxx
                       Gateway: 10.110.10.250
                           DNS: 10.110.10.250
                                10.110.10.249
               DHCP4 Client ID: ARP/LL
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab112xxx...
```

</details>

File: src/basic/ether-addr-util.h [hunk 19]
```diff
@@ -1,11 +1,31 @@
 /* SPDX-License-Identifier: LGPL-2.1+ */
 #pragma once
 
+#include <linux/if_infiniband.h>
 #include <net/ethernet.h>
 #include <stdbool.h>
 
 #include "hash-funcs.h"
 
+#define HW_ADDR_MAX_SIZE CONST_MAX(ETH_ALEN, INFINIBAND_ALEN)
```
Comment (yuwata) [inline src/basic/ether-addr-util.h]: I noticed that linux/netdevice.h has `MAX_ADDR_LEN`. Maybe we should use it.

Comment (BtbN) [reply src/basic/ether-addr-util.h]: That's unfortunately a bit problematic.
net/if_arp.h also defines MAX_ADDR_LEN, but as 7. So using that macro seems risky.

File: src/basic/ether-addr-util.h (hunk 18 above)
Comment (BtbN) [reply src/basic/ether-addr-util.h]: It's purely a convenience macro for cases where you just want to log/printf/... the address, so you can save the explicit buffer declaration.

If the explicit style is preferred, I got no issues with that either.

Comment (yuwata) [reply src/basic/ether-addr-util.h]: Hmm, I do not have any strong opinion about this. If I remember correctly, our coding style does not prohibit such a implicit declaration, but at least this is the first time I see it in our code.

@poettering and @keszybz WDYT?

File: src/basic/ether-addr-util.h (hunk 19 above)
Comment (yuwata) [reply src/basic/ether-addr-util.h]: Ugh... So, let's explicitly define this 32, and add a comment about why we cannot use MAX_ADDR_LEN here.

**Comment by yuwata** [comment]
LGTM.
