### PR TITLE
network: set link state configuring before setting addresses

### LINKED ISSUE #11272: networkd hits an assert and crashes starting an ubuntu 16.04 container
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > arch linux

**Expected behaviour you didn't see**
 > networkd does not crash when starting a container with --network-veth

**Unexpected behaviour you saw**
 > networkd crashes when starting an ubuntu 16.04 container with --network-veth

**Steps to reproduce the problem**
Try booting an ubuntu container with --network-veth.

Here is a stack trace:
> #0  0x00007f73a877ad7f in raise () from /usr/lib/libc.so.6
#1  0x00007f73a8765672 in abort () from /usr/lib/libc.so.6
#2  0x00007f73a8504efa in log_assert_failed_realm (realm=<optimized out>, text=0x5566031e9f60 "IN_SET(link->state, LINK_STATE_CONFIGURING, LINK_STATE_FAILED, LINK_STATE_LINGER)", 
    file=0x5566031e40a8 "../systemd-stable/src/network/networkd-link.c", line=934, func=0x5566031ec110 <__PRETTY_FUNCTION__.17558> "address_handler") at ../systemd-stable/src/basic/log.c:795
#3  0x00005566031ba8c1 in address_handler (rtnl=<optimized out>, m=0x556603e4ddd0, link=0x556603e36a60) at ../systemd-stable/src/network/networkd-link.c:933
#4  0x00007f73a85415c4 in process_reply (m=<optimized out>, rtnl=0x556603e1b470) at ../systemd-stable/src/libsystemd/sd-netlink/sd-netlink.c:347
#5  process_running (ret=0x0, rtnl=0x556603e1b470) at ../systemd-stable/src/libsystemd/sd-netlink/sd-netlink.c:414
#6  sd_netlink_process (rtnl=0x556603e1b470, ret=ret@entry=0x0) at ../systemd-stable/src/libsystemd/sd-netlink/sd-netlink.c:443
#7  0x00007f73a85418a3 in io_callback (s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=<optimized out>, s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=<optimized out>)
    at ../systemd-stable/src/libsystemd/sd-netlink/sd-netlink.c:712
#8  0x00007f73a8534620 in source_dispatch (s=s@entry=0x556603e1b620) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:2816
#9  0x00007f73a853490f in sd_event_dispatch (e=e@entry=0x556603e19520) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:3229
#10 0x00007f73a8534ad8 in sd_event_run (e=e@entry=0x556603e19520, timeout=timeout@entry=18446744073709551615) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:3286
#11 0x00007f73a8534cfb in sd_event_loop (e=0x556603e19520) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:3308
#12 0x0000556603187a3c in run (argv=<optimized out>, argc=<optimized out>) at ../systemd-stable/src/network/networkd.c:110
#13 main (argc=<optimized out>, argv=<optimized out>) at ../systemd-stable/src/network/networkd.c:117

At frame 3, link->state has value LINK_STATE_CONFIGURED, hence the assertion failure.

### PR DESCRIPTION
**Pull request by yuwata**
As `link_request_set_neighbors()` may set link state 'configured'.

Fixes #11272.

cc @wkennington and @ssahani.

### CODE REVIEW

**Comment by ssahani** [comment]
It's a bit tricky. We are forcefully making state to be unconfigured before going to the function . Should we do this ? I am still thinking about this.

**Comment by wkennington** [comment]
The cause of the original bug doesn't make sense to me. We shouldn't be able to set LINK_STATE_CONFIGURED until we have set all of the addresses, neighbors, and routes as the conditions for making it through link_check_ready() requires all of those to be set.

**Comment by wkennington** [comment]
Is this not a bug caused by not resetting the *_configured booleans to false before running through the configure routines again?

**Comment by yuwata** [comment]
@wkennington and @ssahani Thank you for the comments. I have updated this. PTAL.

@aroig If possible, please test the new version. Thank you.

**Comment by yuwata** [comment]
Or, maybe we should drop `*_configured`. They seem to be equivalent to `*_messages == 0`, at least for addresses, neighbors, and static_routes.

**Comment by aroig** [comment]
I confirm that the last changes in this PR fix  #11272 for me.

**Comment by ssahani** [comment]
I think this should be OK

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -913,10 +917,9 @@ static int link_request_set_neighbors(Link *link) {
                 }
         }
 
-        if (link->neighbor_messages == 0) {
+        if (link->neighbor_messages == 0)
                 link->neighbors_configured = true;
-                link_check_ready(link);
```
Comment (wkennington) [inline src/network/networkd-link.c]: You shouldn't get rid of this in case we re-arrange the logic for setting neighbors. All of the other functions perform the same check which should be safe regardless of where it is executed.

File: src/network/networkd-link.c [hunk 2]
```diff
@@ -794,6 +794,8 @@ static int link_set_routing_policy_rule(Link *link) {
         assert(link);
         assert(link->network);
 
+        link->routing_policy_rules_configured = false;
```
Comment (wkennington) [inline src/network/networkd-link.c:798]: These should all be set to false at the same location in the codebase, likely when networkd determines that we need to reconfigure a link. Otherwise the invariant for link_check_ready() might not hold.

File: src/network/networkd-link.c [hunk 3]
```diff
@@ -902,7 +906,7 @@ static int link_request_set_neighbors(Link *link) {
         assert(link->network);
         assert(link->state != _LINK_STATE_INVALID);
 
-        link_set_state(link, LINK_STATE_CONFIGURING);
```
Comment (wkennington) [inline src/network/networkd-link.c]: You should be able to leave this once we correct the invariants on link_check_ready(). Just in case we decide to re-arrange the ordering of the link_set_* functions in the future. There is no reason why link_set_neighbors should depend on link_set_addresses setting this state.

File: src/network/networkd-link.c (hunk 1 above)
Comment (yuwata) [reply src/network/networkd-link.c]: > which should be safe regardless of where it is executed.

Good point.

**Comment by wkennington** [comment]
This looks functionally good, but I'm not terribly happy with having the configuration functions needing to know exactly what to deconfigure. It would be nice if the caller which is performing the link configuration just called `link_set_unconfigured` or something,

**Comment by yuwata** [comment]
@wkennington Hmm, I'd like to keep setting `*_configured` at the relevant functions for the readability.
Now, except for addresses, all `link_request_set_*()` set link state `CONFIGURING` and the relevant `_configured` flag false. So, when we implement, for example, `networkctl set-neighbor` or something, then the relevant function just need to parse the input and call `link_request_set_neighbors()`.

**Comment by yuwata** [comment]
@wkennington So, anyway, I would like to leave further cleanups in other PRs. Because, initially, this is intended to fix issue #11272. What do you think about?

**Comment by yuwata** [comment]
Just rebased and update comments.

**Comment by wkennington** [comment]
Seems fine to me

**Comment by nfnty** [comment]
Can this be backported to stable? It's not ok to have networkd crashing repeatedly.

**Comment by ssahani** [comment]
Ohhh please provide the dump.

**Comment by nfnty** [comment]
@ssahani Same as #11272.

**Comment by ssahani** [comment]
@nfnty you mean including this PR networkd crashing ? If so please provide your minimal conf so that we can fix this in current git.

**Comment by nfnty** [comment]
@ssahani No, I just want this PR to be backported to https://github.com/systemd/systemd-stable, so that distros that use the stable branch get this issue fixed.

**Comment by ssahani** [comment]
@nfnty ok . we have not reported any crash till now as per I know @yuwata is there any ? Please test with down stream if you still face it report back. we will work on it . Thanks !

**Comment by yuwata** [comment]
@nfnty https://github.com/systemd/systemd-stable/pull/40
