### PR TITLE
network: fix routing policy rule issue

### LINKED ISSUE #16784: RoutingPolicyRule not applied on reconfigure
**systemd version the issue has been seen with**
> systemd 245 (245.6-1~bpo10+1)

**Used distribution**
 > Armbian

**Expected behaviour you didn't see**
 > ip rules have to be applied on reconfigure (as they do on `systemctl restart systemd-networkd.service`)

**Unexpected behaviour you saw**
 > ip rules not applied after `networkctl reconfigure IFNAME`

**Steps to reproduce the problem**
Create any `.network` config with RoutingPolicyRule, e.g.
```
[RoutingPolicyRule]
Table=42
Priority=42
FirewallMark=42
```
After boot or systemd-networkd.service restart, you see the rule.
Then either delete the rule by `ip rule del pri 42` AND/OR add new `[RoutingPolicyRule]` to .network file - after `networkctl reconfigure IFNAME` OR `networkctl reload` you see it/them unaplied.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #16784.

### CODE REVIEW

File: src/network/networkd-routing-policy-rule.c [hunk 1]
```diff
@@ -333,37 +333,48 @@ static int routing_policy_rule_remove_handler(sd_netlink *rtnl, sd_netlink_messa
...
+
+        if (DEBUG_LOGGING) {
+                _cleanup_free_ char *from = NULL, *to = NULL;
+
+                (void) in_addr_to_string(rule->family, &rule->from, &from);
+                (void) in_addr_to_string(rule->family, &rule->to, &to);
+
+                log_link_debug(link,
+                               "Configuring routing policy rule: priority: %"PRIu32", %s/%u -> %s/%u, iif: %s, oif: %s, table: %"PRIu32,
+                               rule->priority, from, rule->from_prefixlen, to, rule->to_prefixlen, strna(rule->iif), strna(rule->oif), rule->table);
```
Comment (poettering) [inline src/network/networkd-routing-policy-rule.c]: doesn't matter much, but given that you ignore in_addr_to_string() errors above, you should probably enclose `to` and `from` in `strna()` or so here

File: src/network/networkd-routing-policy-rule.c [hunk 2]
```diff
@@ -657,7 +657,7 @@ int routing_policy_rule_section_verify(RoutingPolicyRule *rule) {
 
 static int parse_fwmark_fwmask(const char *s, uint32_t *ret_fwmark, uint32_t *ret_fwmask) {
         _cleanup_free_ char *fwmark_str = NULL;
-        uint32_t fwmark, fwmask = 0;
+        uint32_t fwmark, fwmask = UINT32_MAX;
```
Comment (poettering) [inline src/network/networkd-routing-policy-rule.c]: shouldn't the function refuse `/0` specs, i.e. when no bits match?
