### PR TITLE
sd-journal: fix sd_journal_seek_monotonic_usec()

### LINKED ISSUE #30337: API: sd_journal_seek_realtime_usec() fails if the realtime goes backward
### systemd version the issue has been seen with

254

### Used distribution

buntu 23.04

### Linux kernel version used

6.2.0-37-generic

### CPU architectures issue was seen on

aarch64

### Component

journalctl

### Expected behaviour you didn't see

If the system clock goes backward while journal entries are being created, those entries may not be found by `sd_journal_seek_realtime_usec()`[1].

For example,

If the system time goes backward like this.

```
sudo journalctl --vacuum-time=1s
<wait for a while to clear up journal>

date -s "<backward-time>"

date -s "<forward-time>"
```

Journal entries are

```
{
        "MESSAGE_ID" : "39f53479d3a045ac8e11786248231fbf",
        "MESSAGE" : "Started Time & Date Service.",
        "__REALTIME_TIMESTAMP" : "1699839632179843",
        "_SOURCE_REALTIME_TIMESTAMP" : "1699839632179536",
}

---Backward Begin
{
        "_SOURCE_REALTIME_TIMESTAMP" : "1699839632004914",
        "MESSAGE" : "Clock change detected. Flushing caches.",
        "__REALTIME_TIMESTAMP" : "1699839632005117",
}
...
{
        "__REALTIME_TIMESTAMP" : "1699839632056655",
        "MESSAGE_ID" : "c7a787079b354eaaa9e77b371893cd27",
        "MESSAGE" : "Changed local time to Mon 2023-11-13 01:40:32 UTC",
        "_SOURCE_REALTIME_TIMESTAMP" : "1699839632018027",
}
---End of backward
{
        "__REALTIME_TIMESTAMP" : "1699839662049861",
        "MESSAGE_ID" : "7ad2d189f7e94e70a38c781354912448",
        "_SOURCE_REALTIME_TIMESTAMP" : "1699839662049794",
        "MESSAGE" : "systemd-timedated.service: Deactivated successfully.",
}
```

### Unexpected behaviour you saw

Then, this may be failing.

```
     uint64_t curTs = 1699839632005117UL;
    sd_journal* journal;
     int ret = sd_journal_open(&journal, SD_JOURNAL_LOCAL_ONLY);
     ret = sd_journal_get_realtime_usec(journal, &curTs);
```

Is this a limitation of `sd_journal_get_realtime_usec()` - as the journal needs to be timely-sorted?

### Steps to reproduce the problem

```
sudo journalctl --vacuum-time=1s
<wait for a while to clear up journal>

date -s "<backward-time>"

date -s "<forward-time>"
```

Get journal output as json-pretty

```
$ journalctl -o json-pretty > js.out
```

Find the entry whose time goes backward

```
{
        "_RUNTIME_SCOPE" : "system",
        "MESSAGE" : "Clock change detected. Flushing caches.",
        "SYSLOG_IDENTIFIER" : "systemd-resolved",
....
        "__REALTIME_TIMESTAMP" : "1701754200000785",
        "_SYSTEMD_SLICE" : "system.slice",
        "_BOOT_ID" : "5c30ffc3d8ab4c2a8ea1be0f32001872",
        "_SOURCE_REALTIME_TIMESTAMP" : "1701754200000446",
...
        "_CMDLINE" : "/lib/systemd/systemd-resolved",
        "TID" : "582",
        "__MONOTONIC_TIMESTAMP" : "6517497947",
....
}
```

It may fail with `1701754200000785`.

$ test-realtime-seek 1701754200000785
 input TS=1701754200000785
sd_journal_seek_realtime_usec with timestamp=1701754200000785 is failing with r=0

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Test program: test-realtime-seek.c

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <systemd/sd-journal.h>

/* Compile: gcc test-realtime-seek.c -lsystemd */

int main(int argc, const char *argv[]) {
  sd_journal *j;
  sd_id128_t boot_id;
  int r;

  uint64_t ts = 0;

  char *end;
  ts = strtoull(argv[1], &end, 10);
  printf(" input TS=%lu\n", ts);

  r = sd_journal_open(&j, SD_JOURNAL_LOCAL_ONLY);
  assert(r >= 0);
  r = sd_journal_seek_realtime_usec(j, ts);
  if (r < 0) {
    printf("sd_journal_seek_realtime_usec with timestamp=%lu is failing with "
           "r=%d\n",
           ts, r);
    return 1;
  }

  for (uint64_t i = 0; i <= 5; i++) {
    sd_journal_next(j);
    uint64_t curTs = 0;
    r = sd_journal_get_realtime_usec(j, &curTs);
    if (r < 0) {
      printf("sd_journal_seek_realtime_usec with timestamp=%lu is failing with "
             "r=%d\n",
             ts, r);
      return 1;
    }
    if (curTs == ts) {
      printf("sd_journal_seek_realtime_usec with timestamp=%lu is successful\n",
             ts);
      return 0;
    }
  }
  printf(
      "sd_journal_seek_realtime_usec with timestamp=%lu is failing with r=%d\n",
      ts, r);

  return 1;
}
```

### PR DESCRIPTION
**Pull request by yuwata**
Prompted by #30337.
Closes #30337.

### CODE REVIEW

File: src/libsystemd/sd-journal/test-journal-interleaving.c [hunk 1]
```diff
@@ -113,64 +101,52 @@ static void append_unreferenced_data(JournalFile *f, const sd_id128_t *boot_id)
         ts.monotonic = usec_sub_unsigned(previous_ts.monotonic, 10);
         ts.realtime = usec_sub_unsigned(previous_ts.realtime, 10);
 
-        assert_se(q = strjoin("_BOOT_ID=", SD_ID128_TO_STRING(*boot_id)));
+        ASSERT_NOT_NULL(q = strjoin("_BOOT_ID=", SD_ID128_TO_STRING(*boot_id)));
         iovec = IOVEC_MAKE_STRING(q);
 
-        assert_se(journal_file_append_entry(f, &ts, boot_id, &iovec, 1, NULL, NULL, NULL, NULL) == -EREMCHG);
+        ASSERT_EQ(journal_file_append_entry(f, &ts, boot_id, &iovec, 1, NULL, NULL, NULL, NULL), -EREMCHG);
```
Comment (daandemeyer) [inline src/libsystemd/sd-journal/test-journal-interleaving.c]: We have `ASSERT_ERROR` for this

File: src/shared/tests.h [hunk 2]
```diff
@@ -332,6 +314,9 @@ static inline int run_test_table(void) {
                 }                                                                                               \
         })
 
+#define ASSERT_TRUE(expr)  ASSERT_EQ((int) (expr), 1)
+#define ASSERT_FALSE(expr) ASSERT_EQ((int) (expr), 0)
```
Comment (daandemeyer) [inline src/shared/tests.h]: I'm not a big fan of this because the error will not be very informative if the function call with negative errno fails. I'd prefer we add `ASSERT_OK_POSITIVE` and `ASSERT_OK_ZERO` instead.

File: src/libsystemd/sd-journal/sd-journal.c [hunk 3]
```diff
@@ -899,11 +956,26 @@ static int find_location_with_matches(
                 r = journal_file_move_to_entry_by_monotonic(f, j->current_location.boot_id, j->current_location.monotonic, direction, ret, offset);
                 if (r != 0)
                         return r;
+                /* If not found, fall back to realtime if set, or go to the first entry of the next boot
```
Comment (daandemeyer) [inline src/libsystemd/sd-journal/sd-journal.c:954]: Missing newline before the comment

File: src/libsystemd/sd-journal/sd-journal.c [hunk 4]
```diff
@@ -899,11 +956,26 @@ static int find_location_with_matches(
...
         }
         if (j->current_location.realtime_set)
                 return journal_file_move_to_entry_by_realtime(f, j->current_location.realtime, direction, ret, offset);
 
-        return journal_file_next_entry(f, 0, direction, ret, offset);
+        uint64_t p = 0;
+        if (j->current_location.monotonic_set) {
+                /* If not found in the above, first move to the last (or first when DIRECTION_UP) entry for the boot. */
+                r = journal_file_move_to_entry_by_monotonic(f, j->current_location.boot_id,
+                                                            direction == DIRECTION_DOWN ? USEC_INFINITY: 0,
```
Comment (daandemeyer) [inline src/libsystemd/sd-journal/sd-journal.c]: Missing whitespace after `USEC_INFINITY`

File: src/libsystemd/sd-journal/sd-journal.c [hunk 5]
```diff
@@ -763,6 +763,59 @@ static int next_for_match(
...
+                                                            direction == DIRECTION_DOWN ? DIRECTION_UP : DIRECTION_DOWN,
+                                                            NULL, &p);
+                if (r < 0)
+                        return r;
+                if (r == 0 && found_boot)
+                        return -EBADMSG; /* Huh?? We found the boot previously... */
+                found_boot = true;
+
+                /* Then, move to the first entry of the next boot (or the last entry of the previous boot with DRECTION_UP). */
```
Comment (daandemeyer) [inline src/libsystemd/sd-journal/sd-journal.c]: Typo

File: src/libsystemd/sd-journal/sd-journal.c [hunk 6]
```diff
@@ -763,6 +763,59 @@ static int next_for_match(
...
+                Object *entry;
+                r = journal_file_next_entry(f, p, direction, &entry, NULL);
+                if (r <= 0) /* r == 0 means that no next (or previous) boot found. That is, HEAD or TAIL now. */
```
Comment (daandemeyer) [inline src/libsystemd/sd-journal/sd-journal.c]: That is, we are at HEAD or TAIL now

**Comment by DaanDeMeyer** [comment]
Can we add some more information to the commit message and the test cases?

Specifically, I found the following in the man page:

```
sd_journal_seek_monotonic_usec() seeks to a position with the specified monotonic timestamp, i.e. CLOCK_MONOTONIC. Since monotonic time restarts on every reboot a boot ID needs to be specified as well.
```

Yet you're moving to the next/previous boot here which seems wrong if the user explicitly specified a boot ID to search in for the given monotonic timestamp.

**Comment by yuwata** [comment]
> Yet you're moving to the next/previous boot here which seems wrong if the user explicitly specified a boot ID to search in for the given monotonic timestamp.

- `sd_journal_seek_monotonic_usec()` accepts arbitrary boot ID and timestamp, and sets cursor to the boot and timestamp, even if matching entry does not exist.
- A journal file can contain entries from multiple boots. And `sd_journal_next()` can move from the last entry of a boot to the first entry of the next boot. If it is prohibited, `journalctl` only shows entry of the first boot.
- Boot ID filtering must be done by `_BOOT_ID=xxxxxxxxxxxxxx` filter, which is used by `journalctl -b`.
- Hence, if `sd_journal_seek_monotonic_usec()` is called with a timestamp that is after the last timestamp of a boot, then subsequent `sd_journal_next()` should return the first entry of the _next_ boot.

**Review by DaanDeMeyer — CHANGES_REQUESTED** [review]
Forgot to post review comments

File: src/libsystemd/sd-journal/test-journal-interleaving.c [hunk 7]
```diff
@@ -877,6 +877,423 @@ TEST(generic_array_bisect) {
...
+} TestEntry;
+
+static bool find_entry_monotonic_one(
+                const TestEntry* e,
+                bool next,
+                sd_id128_t boot_id,
+                usec_t usec,
+                unsigned data,
+                bool *boot_found) {
+
```
Comment (bluca) [inline src/libsystemd/sd-journal/test-journal-interleaving.c:896]: assert(e)

File: src/libsystemd/sd-journal/test-journal-interleaving.c [hunk 8]
```diff
@@ -877,6 +877,423 @@ TEST(generic_array_bisect) {
...
+static size_t find_entry_monotonic(
+                const TestEntry *entries,
+                size_t n_entries,
+                bool next,
+                sd_id128_t boot_id,
+                usec_t usec,
+                unsigned data) {
+
+        bool boot_found = false;
+
```
Comment (bluca) [inline src/libsystemd/sd-journal/test-journal-interleaving.c:921]: assert(entries || n_entires == 0)

Comment (bluca) [reply src/libsystemd/sd-journal/test-journal-interleaving.c:921]: same below

File: src/libsystemd/sd-journal/test-journal-interleaving.c [hunk 9]
```diff
@@ -877,6 +877,423 @@ TEST(generic_array_bisect) {
...
+        return SIZE_MAX;
+}
+
+static void verify_entry(sd_journal *j, const TestEntry *entry) {
+        _cleanup_free_ char *s = NULL, *e = NULL;
+        sd_id128_t id;
+        usec_t t;
+        const void *d;
+        size_t l;
+
```
Comment (bluca) [inline src/libsystemd/sd-journal/test-journal-interleaving.c:995]: assert(entry)

**Review by bluca — COMMENTED** [review]
Given the many unrelated changes, this is going to be difficult to backport. It would be better to do the bug fix first, and then later do unrelated cleanups.

**Comment by yuwata** [comment]
@bluca Thank you for the review. The commits are reordered, and several more assertions suggested in the above are added.

File: src/shared/tests.h [hunk 10]
```diff
@@ -217,6 +217,37 @@ static inline int run_test_table(void) {
...
+#define ASSERT_OK_ZERO(expr)                                                                                    \
+        ({                                                                                                      \
+                typeof(expr) _result = (expr);                                                                  \
+                if (_result < 0) {                                                                              \
+                        log_error_errno(_result, "%s:%i: Assertion failed: expected \"%s\" to succeed but got the following error: %m", \
+                                        PROJECT_FILE, __LINE__, #expr);                                         \
+                        abort();                                                                                \
+                }                                                                                               \
+                if (_result != 0) {                                                                             \
+                        log_error("%s:%i: Assertion failed: expected \"%s\" to be zero.",                       \
```
Comment (daandemeyer) [inline src/shared/tests.h]: This should log the actual value of `_result` as well

File: src/shared/tests.h [hunk 11]
```diff
@@ -217,6 +217,37 @@ static inline int run_test_table(void) {
...
+#define ASSERT_OK_POSITIVE(expr)                                                                                \
+        ({                                                                                                      \
+                typeof(expr) _result = (expr);                                                                  \
+                if (_result < 0) {                                                                              \
+                        log_error_errno(_result, "%s:%i: Assertion failed: expected \"%s\" to succeed but got the following error: %m", \
+                                        PROJECT_FILE, __LINE__, #expr);                                         \
+                        abort();                                                                                \
+                }                                                                                               \
+                if (_result <= 0) {                                                                             \
+                        log_error("%s:%i: Assertion failed: expected \"%s\" to be positive.",                   \
```
Comment (daandemeyer) [inline src/shared/tests.h]: The actual value of `_result` should be included in the log message.

**Review by DaanDeMeyer — APPROVED** [review]
LGTM, one suggestion
