### PR TITLE
vconsole: introduce Context and its helper functions

### LINKED ISSUE #26945: vconsole: ASAN detects memory leak
### systemd version the issue has been seen with

HEAD

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/665/artifact/systemd-centos-ci/index.html
```
[   19.953900] systemd-vconsole-setup[812]: ==812==ERROR: LeakSanitizer: detected memory leaks
[   19.953900] systemd-vconsole-setup[812]: Direct leak of 64 byte(s) in 1 object(s) allocated from:
[   19.953900] systemd-vconsole-setup[812]:     #0 0x7f7766d0ea0a  (/usr/lib/clang/15.0.7/lib/linux/libclang_rt.asan-x86_64.so+0x10ea0a) (BuildId: faf0f22f6ed3e575962cd50bcfba6f2e17878558)
[   19.953900] systemd-vconsole-setup[812]:     #1 0x7f77661b6c47 in greedy_realloc /systemd-meson-build/../build/src/basic/alloc-util.c:70:13
[   19.953900] systemd-vconsole-setup[812]:     #2 0x7f77661e49e9 in parse_env_file_internal /systemd-meson-build/../build/src/basic/env-file.c:127:38
[   19.953900] systemd-vconsole-setup[812]:     #3 0x7f77661e652d in parse_env_filev /systemd-meson-build/../build/src/basic/env-file.c:357:13
[   19.953900] systemd-vconsole-setup[812]:     #4 0x7f77661e652d in parse_env_file_sentinel /systemd-meson-build/../build/src/basic/env-file.c:373:13
[   19.953900] systemd-vconsole-setup[812]:     #5 0x55849ec88309 in main /systemd-meson-build/../build/src/vconsole/vconsole-setup.c:450:13
[   19.953900] systemd-vconsole-setup[812]:     #6 0x7f776583c78f  (/usr/lib/libc.so.6+0x2378f) (BuildId: 4a4bec3d95a1804443e852958fe59ed461135ce9)
[   19.953900] systemd-vconsole-setup[812]: SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).

```

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes memleaks introduced by 01771226c202183ff447da712f43d2fad8874484 and ea575e176aac9fa8f430bb30a3e8abd8da767a10

Fixes #26945.

### CODE REVIEW

File: src/vconsole/vconsole-setup.c [hunk 1]
```diff
@@ -36,6 +36,148 @@
 #include "terminal-util.h"
 #include "virt.h"
 
+typedef enum VCMeta{
```
Comment (YHNdnzj) [inline src/vconsole/vconsole-setup.c]:
```suggestion
typedef enum VCMeta {
```

File: src/vconsole/vconsole-setup.c [hunk 2]
```diff
@@ -36,6 +36,148 @@
...
+        VC_FONT_UNIMAP,
+        _VC_META_MAX,
+        _VC_META_INVALID = -EINVAL,
+} VCMeta;
+
+typedef struct Context {
+        char *config[_VC_META_MAX];
+} Context;
+
+#define CONTEXT_NULL ((Context) {})
```
Comment (YHNdnzj) [inline src/vconsole/vconsole-setup.c]: Hmm, is this really needed? Currently it is only used for initialization, so a plain `{}` would be sufficient.

Comment (yuwata) [reply src/vconsole/vconsole-setup.c]: Yeah. I was planning to add more components into Context.

**Review by DaanDeMeyer — APPROVED** [review]
