### PR TITLE
network: two fixes for configuring address correctly

### LINKED ISSUE #17803: [systemd-networkd] dhcp failed to configure route
**systemd version the issue has been seen with**
 > systemd-247.1

systemd-246.6 works fine on the same host (the only difference is systemd version), also `dhcpcd` works fine with both versions (but I don't use it).

**Used distribution**
 > Archlinux x86_64

**Linux kernel version used** (`uname -a`)
 > Linux node2.bkoty.ru 5.9.11-zen2-1-zen #1 ZEN SMP PREEMPT Sat, 28 Nov 2020 02:08:52 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64 (kvm, VPS)

**Expected behaviour you didn't see**
 > network interface configured and default route is added.

**246.6**:
```
$ ip -4 addr
...
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    altname enp0s3
    inet 195.201.98.54/32 scope global dynamic ens3
       valid_lft 84779sec preferred_lft 84779sec
$ ip -4 route
default via 172.31.1.1 dev ens3 proto dhcp src 195.201.98.54 metric 1024 
172.31.1.1 dev ens3 proto dhcp scope link src 195.201.98.54 metric 1024
```

**Unexpected behaviour you saw**
 > address is added but no route.

**247.1**:
```
$ ip -4 addr
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    altname enp0s3
    inet 195.201.98.54/32 scope global dynamic ens3
       valid_lft 86374sec preferred_lft 86374sec
$ ip -4 route
```
(yes, last command outputs nothing.)

**Steps to reproduce the problem**
 > (Not completely sure): (?VPS, ?kvm), getting IPv4 from DHCP server,

systemd-networkd.service configuration:
<details>

```
$ systemctl cat systemd-networkd.service
# /usr/lib/systemd/system/systemd-networkd.service
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Network Service
Documentation=man:systemd-networkd.service(8)
ConditionCapability=CAP_NET_ADMIN
DefaultDependencies=no
# systemd-udevd.service can be dropped once tuntap is moved to netlink
After=systemd-udevd.service network-pre.target systemd-sysusers.service systemd-sysctl.service
Before=network.target multi-user.target shutdown.target
Conflicts=shutdown.target
Wants=network.target

[Service]
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW
DeviceAllow=char-* rw
ExecStart=!!/usr/lib/systemd/systemd-networkd
LockPersonality=yes
MemoryDenyWriteExecute=yes
NoNewPrivileges=yes
ProtectClock=yes
ProtectControlGroups=yes
ProtectHome=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectSystem=strict
Restart=on-failure
RestartSec=0
RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET AF_INET6 AF_PACKET AF_ALG
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
RuntimeDirectory=systemd/netif
RuntimeDirectoryPreserve=yes
SystemCallArchitectures=native
SystemCallErrorNumber=EPERM
SystemCallFilter=@system-service
Type=notify
RestartKillSignal=SIGUSR2
User=systemd-network
WatchdogSec=3min

[Install]
WantedBy=multi-user.target
Also=systemd-networkd.socket
Alias=dbus-org.freedesktop.network1.service

# We want to enable systemd-networkd-wait-online.service whenever this service
# is enabled. systemd-networkd-wait-online.service has
# WantedBy=network-online.target, so enabling it only has an effect if
# network-online.target itself is enabled or pulled in by some other unit.
Also=systemd-networkd-wait-online.service

# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
</details>

network configuration:
```
$ cat /etc/systemd/network/50-hetzner.network
[Match]
Name=en*
# Name=ens3
# Name=*
# Type=ether

[Network]
DHCP=ipv4
Address=2a01:4f8:c2c:c813::2/64
Gateway=fe80::1
...
```
(rest are `[Address]` sections with IPv6 addresses).

Below is for **246.6** version (works fine),
output of `networkctl status ens3
```
● 2: ens3                                                                  
                     Link File: /usr/lib/systemd/network/99-default.link   
                  Network File: /etc/systemd/network/50-hetzner.network    
                          Type: ether                                      
                         State: routable (configured)                      
             Alternative Names: enp0s3                                     
                          Path: pci-0000:00:03.0                           
                        Driver: virtio_net                                 
                        Vendor: Red Hat, Inc.                              
                         Model: Virtio network device                      
                    HW Address: 96:00:00:2f:43:96                          
                           MTU: 1500 (min: 68, max: 65535)                 
                         QDisc: fq_codel                                   
  IPv6 Address Generation Mode: eui64                                      
          Queue Length (Tx/Rx): 1/1                                        
              Auto negotiation: no                                         
                         Speed: n/a                                        
                       Address: 195.201.98.54 (DHCP4 via 172.31.1.1)       
                                ... # (IPv6 address, irrelevant, I think; besides, IPv6 are set manually and works fine)
                       Gateway: 172.31.1.1                                 
                                fe80::1                                    
                           DNS: 213.133.99.99                              
                                213.133.98.98                              
                                213.133.100.100                            
               DHCP4 Client ID: IAID:0xb55e67ff/DUID                       
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab11be0add03856e57d70000

дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:104/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static routes are not configured.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Setting routes
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:104/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Routes set
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): dhcp4:yes dhcp6_addresses:no dhcp_routes:no dhcp_pd_addresses:no dhcp_pd_routes:no ndisc_addresses:no ndisc_routes:no
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: State changed: configuring -> configured
дек 02 09:11:01 node2.bkoty.ru systemd-networkd[222]: ens3: NDisc handler get timeout event
```
output of `systemctl status systemd-networkd.service`:
```
● systemd-networkd.service - Network Service
     Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/systemd-networkd.service.d
             └─override.conf
     Active: active (running) since Wed 2020-12-02 09:10:48 CET; 2min 5s ago
TriggeredBy: ● systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
   Main PID: 222 (systemd-network)
     Status: "Processing requests..."
      Tasks: 1 (limit: 4587)
     Memory: 2.6M
        CPU: 78ms
     CGroup: /system.slice/systemd-networkd.service
             └─222 /usr/lib/systemd/systemd-networkd

дек 02 09:12:10 node2.bkoty.ru systemd-networkd[222]: Got message type=method_call sender=:1.10 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=3 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 09:12:10 node2.bkoty.ru systemd-networkd[222]: Sent message type=error sender=n/a destination=:1.10 path=n/a interface=n/a member=n/a cookie=19 reply_cookie=3 signature=s error-name=org.freedesktop.DBus.Error.UnknownProperty error-message=Unknown interface org.freedesktop.network1.DHCPServer or property Leases.
дек 02 09:12:15 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:12:22 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:12:22 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:12:25 node2.bkoty.ru systemd-networkd[222]: Got message type=method_call sender=:1.12 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 09:12:25 node2.bkoty.ru systemd-networkd[222]: Sent message type=method_return sender=n/a destination=:1.12 path=n/a interface=n/a member=n/a cookie=20 reply_cookie=2 signature=v error-name=n/a error-message=n/a
дек 02 09:12:25 node2.bkoty.ru systemd-networkd[222]: Got message type=method_call sender=:1.12 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=3 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 09:12:25 node2.bkoty.ru systemd-networkd[222]: Sent message type=error sender=n/a destination=:1.12 path=n/a interface=n/a member=n/a cookie=21 reply_cookie=3 signature=s error-name=org.freedesktop.DBus.Error.UnknownProperty error-message=Unknown interface org.freedesktop.network1.DHCPServer or property Leases.
дек 02 09:12:51 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
```
Output of `journalctl -b -0 -u systemd-networkd.service`:
<details>

```
-- Logs begin at Sun 2020-11-29 04:20:58 CET, end at Wed 2020-12-02 09:13:30 CET. --
дек 02 09:10:48 node2.bkoty.ru systemd[1]: Starting Network Service...
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: sd-device-monitor: No permission to stat PID1's netns, unable to determine if we are in host netns: Permission denied
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Bus bus-api-network: changing state UNSET → OPENING
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Bus bus-api-network: changing state OPENING → WATCH_BIND
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: timestamp of '/etc/systemd/network' changed
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: timestamp of '/usr/lib/systemd/network' changed
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: No virtualization found in DMI
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Virtualization found, CPUID=KVMKVMKVM
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Found VM virtualization kvm
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: /usr/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: eth0: New device has no master, continuing without
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: eth0: Flags change: +MULTICAST +BROADCAST
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: eth0: Link 2 added
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: eth0: link pending udev initialization...
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: eth0: Saved original MTU: 1500
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: New device has no master, continuing without
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Failed to get driver, continuing without: Operation not supported
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Flags change: +LOOPBACK +UP +LOWER_UP +RUNNING
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Link 1 added
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: link pending udev initialization...
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Saved original MTU: 65536
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Remembering foreign address: ::1/128 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: link_check_ready(): link is in pending state.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Remembering foreign address: 127.0.0.1/8 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: link_check_ready(): link is in pending state.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Remembering route: dst: ::1/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Remembering route: dst: ::1/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Remembering route: dst: 127.255.255.255/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: link, table: local, proto: kernel, type: broadcast
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Remembering route: dst: 127.0.0.1/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: host, table: local, proto: kernel, type: local
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Remembering route: dst: 127.0.0.0/8, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: host, table: local, proto: kernel, type: local
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Remembering route: dst: 127.0.0.0/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: link, table: local, proto: kernel, type: broadcast
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: rtnl: received rule message with invalid family 129, ignoring.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: rtnl: received rule message with invalid family 128, ignoring.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Enumeration completed
дек 02 09:10:48 node2.bkoty.ru systemd[1]: Started Network Service.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: eth0: Interface name change detected, eth0 has been renamed to ens3.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: eth0: State changed: pending -> linger
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: eth0: Link removed
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: New device has no master, continuing without
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Flags change: +MULTICAST +BROADCAST
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Link 2 added
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Interface is being renamed, pending initialization.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Saved original MTU: 1500
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: 3
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus/system_bus_socket on bus bus-api-network: -1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus on bus bus-api-network: 3
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Added inotify watch for /run/dbus/system_bus_socket on bus bus-api-network: 4
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got inotify event on bus bus-api-network.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Bus bus-api-network: changing state WATCH_BIND → AUTHENTICATING
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: udev initialized link
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: State changed: pending -> initialized
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: Link state is up-to-date
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: lo: State changed: initialized -> unmanaged
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Interface is under renaming, wait for the interface to be renamed.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Bus bus-api-network: changing state AUTHENTICATING → HELLO
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RequestName cookie=2 reply_cookie=0 signature=su error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=4 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=5 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=6 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=7 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=8 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=10 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.1 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Bus bus-api-network: changing state HELLO → RUNNING
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got message type=signal sender=org.freedesktop.DBus.Local destination=n/a path=/org/freedesktop/DBus/Local interface=org.freedesktop.DBus.Local member=Connected cookie=4294967295 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got message type=signal sender=org.freedesktop.DBus destination=:1.1 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got message type=signal sender=org.freedesktop.DBus destination=:1.1 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.1 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=2 signature=u error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Successfully acquired requested service name.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.1 path=n/a interface=n/a member=n/a cookie=5 reply_cookie=3 signature=n/a error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Match type='signal',sender='org.freedesktop.login1',path='/org/freedesktop/login1',interface='org.freedesktop.login1.Manager',member='PrepareForSleep' successfully installed.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: udev initialized link
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: State changed: pending -> initialized
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=11 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Link state is up-to-date
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: found matching network '/etc/systemd/network/50-hetzner.network'
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Setting '/proc/sys/net/ipv6/conf/ens3/disable_ipv6' to '0'
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: IPv6 successfully enabled
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Setting '/proc/sys/net/ipv6/conf/ens3/proxy_ndp' to '0'
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Setting '/proc/sys/net/ipv6/conf/ens3/use_tempaddr' to '0'
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Setting '/proc/sys/net/ipv6/conf/ens3/accept_ra' to '0'
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Setting address genmode for link
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Failed to read sysctl property stable_secret: Input/output error
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Setting address genmode done.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: State changed: initialized -> configuring
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=12 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Bringing link up
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Flags change: +UP +LOWER_UP +RUNNING
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=13 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Link UP
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: LLDP: Started LLDP client
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Started LLDP.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Gained carrier
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Acquiring DHCPv4 lease
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: DHCP CLIENT (0x4b2df819): STARTED on ifindex 2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::141
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::142
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::14f
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::3a21
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::3a22
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::3a2f
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::1:101
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::1:102
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::1:103
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::1:104
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::1:105
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::1:106
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::2:101
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::2:102
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::2:103
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::2:104
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::2:105
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: 2a01:4f8:c2c:c813::2:106
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: fdb9:1981:930::2:2
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring address: fdb9:1981:930::2:17
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Setting addresses
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=14 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: DHCP CLIENT (0x4b2df819): DISCOVER
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: ff00::/8, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: boot, type: unicast
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: fe80::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::141/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::142/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::14f/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::3a21/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::3a22/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::3a2f/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:101/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:102/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:103/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:104/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:105/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:106/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:101/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:102/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:103/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:104/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:105/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:106/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: fdb9:1981:930::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: fdb9:1981:930::2:2/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: fdb9:1981:930::2:17/64 (valid forever)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static addresses are not configured.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Addresses set
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::1:101/64 is not ready
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: DHCP CLIENT (0x4b2df819): OFFER
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: DHCP CLIENT (0x4b2df819): REQUEST (requesting)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: DHCP CLIENT (0x4b2df819): ACK
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: DHCP CLIENT (0x4b2df819): lease expires in 23h 59min 57s
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: DHCP CLIENT (0x4b2df819): T2 expires in 20h 59min 58s
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: DHCP CLIENT (0x4b2df819): T1 expires in 11h 59min 58s
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: DHCPv4 address 195.201.98.54/32 via 172.31.1.1
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Updating address: 195.201.98.54
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 195.201.98.54/32 (valid for 1d)
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=15 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=16 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 195.201.98.54/32, src: n/a, gw: n/a, prefsrc: 195.201.98.54, scope: host, table: local, proto: kernel, type: local
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring route: dst: 172.31.1.1/32, src: n/a, gw: n/a, prefsrc: 195.201.98.54, scope: link, table: main, proto: dhcp, type: unicast
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring route: dst: n/a, src: n/a, gw: 172.31.1.1, prefsrc: 195.201.98.54, scope: global, table: main, proto: dhcp, type: unicast
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Classless static routes received from DHCP server: ignoring router option
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Received remembered route: dst: 172.31.1.1/32, src: n/a, gw: n/a, prefsrc: 195.201.98.54, scope: link, table: main, proto: dhcp, type: unicast
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: Received remembered route: dst: n/a, src: n/a, gw: 172.31.1.1, prefsrc: 195.201.98.54, scope: global, table: main, proto: dhcp, type: unicast
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:48 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:102/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::1:101/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:102/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:101/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:101/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:102/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:102/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:103/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:103/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: fdb9:1981:930::2:17/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: fdb9:1981:930::2:17/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::141/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::141/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: fdb9:1981:930::2:2/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: fdb9:1981:930::2:2/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:103/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:103/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::14f/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::14f/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:105/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:105/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::142/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::142/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::3a21/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::3a21/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:104/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:105/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:104/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:105/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::1:106/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:105/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:106/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::1:106/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:106/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:101/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::1:106/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:101/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering foreign address: fe80::9400:ff:fe2f:4396/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Gained IPv6LL
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Discovering IPv6 routers
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: NDISC: Started IPv6 Router Solicitation client
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: fe80::9400:ff:fe2f:4396/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::3a22/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::1:106/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::3a22/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::3a2f/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::1:106/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::3a2f/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:106/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::2:104/64 is not ready.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: an address 2a01:4f8:c2c:c813::2:104/64 is not ready
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:106/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:104/64 (valid forever)
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): static routes are not configured.
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Setting routes
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:104/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Remembering route: dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: Routes set
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: link_check_ready(): dhcp4:yes dhcp6_addresses:no dhcp_routes:no dhcp_pd_addresses:no dhcp_pd_routes:no ndisc_addresses:no ndisc_routes:no
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: ens3: State changed: configuring -> configured
дек 02 09:10:49 node2.bkoty.ru systemd-networkd[222]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=17 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 09:10:50 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:10:51 node2.bkoty.ru systemd-networkd[222]: NDISC: Sent Router Solicitation, next solicitation in 4s
дек 02 09:10:53 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:10:54 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:10:55 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:10:55 node2.bkoty.ru systemd-networkd[222]: NDISC: Sent Router Solicitation, next solicitation in 8s
дек 02 09:10:56 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:10:57 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:10:59 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:11:00 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:11:00 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:11:01 node2.bkoty.ru systemd-networkd[222]: NDISC: No RA received before link confirmation timeout
дек 02 09:11:01 node2.bkoty.ru systemd-networkd[222]: NDISC: Invoking callback for 'timeout' event.
дек 02 09:11:01 node2.bkoty.ru systemd-networkd[222]: ens3: NDisc handler get timeout event
дек 02 09:11:03 node2.bkoty.ru systemd-networkd[222]: NDISC: Sent Router Solicitation, next solicitation in 16s
дек 02 09:11:19 node2.bkoty.ru systemd-networkd[222]: NDISC: Sent Router Solicitation, next solicitation in 33s
дек 02 09:11:29 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:11:45 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:11:45 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:11:53 node2.bkoty.ru systemd-networkd[222]: NDISC: Sent Router Solicitation, next solicitation in 1min 7s
дек 02 09:12:10 node2.bkoty.ru systemd-networkd[222]: Got message type=method_call sender=:1.10 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 09:12:10 node2.bkoty.ru systemd-networkd[222]: Sent message type=method_return sender=n/a destination=:1.10 path=n/a interface=n/a member=n/a cookie=18 reply_cookie=2 signature=v error-name=n/a error-message=n/a
дек 02 09:12:10 node2.bkoty.ru systemd-networkd[222]: Got message type=method_call sender=:1.10 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=3 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 09:12:10 node2.bkoty.ru systemd-networkd[222]: Sent message type=error sender=n/a destination=:1.10 path=n/a interface=n/a member=n/a cookie=19 reply_cookie=3 signature=s error-name=org.freedesktop.DBus.Error.UnknownProperty error-message=Unknown interface org.freedesktop.network1.DHCPServer or property Leases.
дек 02 09:12:15 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:12:22 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:12:22 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:12:25 node2.bkoty.ru systemd-networkd[222]: Got message type=method_call sender=:1.12 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 09:12:25 node2.bkoty.ru systemd-networkd[222]: Sent message type=method_return sender=n/a destination=:1.12 path=n/a interface=n/a member=n/a cookie=20 reply_cookie=2 signature=v error-name=n/a error-message=n/a
дек 02 09:12:25 node2.bkoty.ru systemd-networkd[222]: Got message type=method_call sender=:1.12 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=3 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 09:12:25 node2.bkoty.ru systemd-networkd[222]: Sent message type=error sender=n/a destination=:1.12 path=n/a interface=n/a member=n/a cookie=21 reply_cookie=3 signature=s error-name=org.freedesktop.DBus.Error.UnknownProperty error-message=Unknown interface org.freedesktop.network1.DHCPServer or property Leases.
дек 02 09:12:51 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:12:58 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:12:58 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
дек 02 09:13:01 node2.bkoty.ru systemd-networkd[222]: NDISC: Sent Router Solicitation, next solicitation in 2min 13s
дек 02 09:13:27 node2.bkoty.ru systemd-networkd[222]: rtnl: received non-static neighbor, ignoring.
```
</details>

Now for **247.1**,
output of `networkctl status ens3`:
```
● 2: ens3                                                                  
                     Link File: /usr/lib/systemd/network/99-default.link   
                  Network File: /etc/systemd/network/50-hetzner.network    
                          Type: ether                                      
                         State: routable (configuring)                     
             Alternative Names: enp0s3                                     
                          Path: pci-0000:00:03.0                           
                        Driver: virtio_net                                 
                        Vendor: Red Hat, Inc.                              
                         Model: Virtio network device                      
                    HW Address: 96:00:00:2f:43:96                          
                           MTU: 1500 (min: 68, max: 65535)                 
                         QDisc: fq_codel                                   
  IPv6 Address Generation Mode: eui64                                      
          Queue Length (Tx/Rx): 1/1                                        
              Auto negotiation: no                                         
                         Speed: n/a                                        
                       Address: 195.201.98.54 (DHCP4 via 172.31.1.1) 
                                ... # (IPv6 address, irrelevant, I think; besides, IPv6 are set manually and works fine)      
                       Gateway: fe80::1                                    
                           DNS: 213.133.99.99                              
                                213.133.98.98                              
                                213.133.100.100                            
               DHCP4 Client ID: IAID:0xb55e67ff/DUID                       
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab11be0add03856e57d70000

дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:105/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 195.201.98.54/32 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Setting routes
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:105/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Received remembered route: dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Routes set
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 195.201.98.54/32 is not ready.
дек 02 08:48:56 node2.bkoty.ru systemd-networkd[226]: ens3: NDisc handler get timeout event
дек 02 08:48:56 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 195.201.98.54/32 is not ready.
```
output of `systemctl status systemd-networkd.service`:
```
● systemd-networkd.service - Network Service
     Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/systemd-networkd.service.d
             └─override.conf
     Active: active (running) since Wed 2020-12-02 08:48:42 CET; 2min 25s ago
TriggeredBy: ● systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
   Main PID: 226 (systemd-network)
     Status: "Processing requests..."
      Tasks: 1 (limit: 4588)
     Memory: 2.7M
        CPU: 73ms
     CGroup: /system.slice/systemd-networkd.service
             └─226 /usr/lib/systemd/systemd-networkd

дек 02 08:50:30 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:50:30 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:50:41 node2.bkoty.ru systemd-networkd[226]: Got message type=method_call sender=:1.14 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 08:50:41 node2.bkoty.ru systemd-networkd[226]: Sent message type=method_return sender=n/a destination=:1.14 path=n/a interface=n/a member=n/a cookie=19 reply_cookie=2 signature=v error-name=n/a error-message=n/a
дек 02 08:50:41 node2.bkoty.ru systemd-networkd[226]: Got message type=method_call sender=:1.14 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=3 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 08:50:41 node2.bkoty.ru systemd-networkd[226]: Sent message type=error sender=n/a destination=:1.14 path=n/a interface=n/a member=n/a cookie=20 reply_cookie=3 signature=s error-name=org.freedesktop.DBus.Error.UnknownProperty error-message=Unknown interface org.freedesktop.network1.DHCPServer or property Leases.
дек 02 08:50:49 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:50:57 node2.bkoty.ru systemd-networkd[226]: NDISC: Sent Router Solicitation, next solicitation in 2min 15s
дек 02 08:51:03 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:51:03 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
```
output of `journalctl -b -0 -u systemd-networkd.service`
<details>

```
-- Journal begins at Sun 2020-11-29 04:20:58 CET, ends at Wed 2020-12-02 08:52:41 CET. --
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-device-monitor: Failed to stat PID1's netns: No such file or directory
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Bus bus-api-network: changing state UNSET → OPENING
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Bus bus-api-network: changing state OPENING → WATCH_BIND
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: timestamp of '/etc/systemd/network' changed
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: timestamp of '/usr/lib/systemd/network' changed
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: No virtualization found in DMI
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Virtualization found, CPUID=KVMKVMKVM
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Found VM virtualization kvm
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: /usr/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: eth0: New device has no master, continuing without
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: eth0: Flags change: +MULTICAST +BROADCAST
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: eth0: Link 2 added
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: eth0: link pending udev initialization...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: eth0: Saved original MTU: 1500
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: New device has no master, continuing without
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Failed to get driver, continuing without: Operation not supported
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Flags change: +LOOPBACK +UP +LOWER_UP +RUNNING
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Link 1 added
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: link pending udev initialization...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Saved original MTU: 65536
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Remembering foreign address: ::1/128 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: link_check_ready(): link is in pending state.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Remembering foreign address: 127.0.0.1/8 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: link_check_ready(): link is in pending state.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Remembering route: dst: ::1/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Remembering route: dst: ::1/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Remembering route: dst: 127.255.255.255/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: link, table: local, proto: kernel, type: broadcast
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Remembering route: dst: 127.0.0.1/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: host, table: local, proto: kernel, type: local
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Remembering route: dst: 127.0.0.0/8, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: host, table: local, proto: kernel, type: local
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Remembering route: dst: 127.0.0.0/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: link, table: local, proto: kernel, type: broadcast
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Remembering foreign routing policy rule: priority: 32766, ::/0 -> ::/0, iif: n/a, oif: n/a, table: 254
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Remembering foreign routing policy rule: priority: 0, ::/0 -> ::/0, iif: n/a, oif: n/a, table: 255
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: rtnl: received rule message with invalid family 129, ignoring.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: rtnl: received rule message with invalid family 128, ignoring.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Remembering foreign routing policy rule: priority: 32767, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: 253
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Remembering foreign routing policy rule: priority: 32766, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: 254
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Remembering foreign routing policy rule: priority: 0, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: 255
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Enumeration completed
дек 02 08:48:42 node2.bkoty.ru systemd[1]: Started Network Service.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got inotify event on bus bus-api-network.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got inotify event on bus bus-api-network.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got inotify event on bus bus-api-network.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got inotify event on bus bus-api-network.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got inotify event on bus bus-api-network.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got inotify event on bus bus-api-network.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got inotify event on bus bus-api-network.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run on bus bus-api-network: 2
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Added inotify watch for /run/dbus on bus bus-api-network: -1
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got inotify event on bus bus-api-network.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Bus bus-api-network: changing state WATCH_BIND → AUTHENTICATING
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: udev initialized link
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: State changed: pending -> initialized
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: Link state is up-to-date
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: lo: State changed: initialized -> unmanaged
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: eth0: Interface name change detected, eth0 has been renamed to ens3.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: eth0: State changed: pending -> linger
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: eth0: Link removed
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: New device has no master, continuing without
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Flags change: +MULTICAST +BROADCAST
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Link 2 added
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Interface is being renamed, pending initialization.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Saved original MTU: 1500
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Interface is under renaming, wait for the interface to be renamed.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: udev initialized link
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: State changed: pending -> initialized
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Link state is up-to-date
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: found matching network '/etc/systemd/network/50-hetzner.network'
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Setting '/proc/sys/net/ipv6/conf/ens3/disable_ipv6' to '0'
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Setting '/proc/sys/net/ipv6/conf/ens3/use_tempaddr' to '0'
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Setting '/proc/sys/net/ipv6/conf/ens3/accept_ra' to '0'
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Setting '/proc/sys/net/ipv6/conf/ens3/proxy_ndp' to '0'
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Setting nomaster
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Setting address genmode for link
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Failed to read sysctl property stable_secret: Input/output error
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Setting nomaster done.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Setting address genmode done.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: State changed: initialized -> configuring
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Bringing link up
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Flags change: +UP +LOWER_UP +RUNNING
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Link UP
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: LLDP: Started LLDP client
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Started LLDP.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Gained carrier
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Acquiring DHCPv4 lease
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: DHCP CLIENT (0x1739ed8): STARTED on ifindex 2
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::2
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::141
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::142
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::14f
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::3a21
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::3a22
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::3a2f
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::1:101
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::1:102
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::1:103
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::1:104
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::1:105
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::1:106
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::2:101
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::2:102
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::2:103
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::2:104
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::2:105
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: 2a01:4f8:c2c:c813::2:106
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: fdb9:1981:930::2:2
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring address: fdb9:1981:930::2:17
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Setting addresses
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: DHCP CLIENT (0x1739ed8): DISCOVER
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Bus bus-api-network: changing state AUTHENTICATING → HELLO
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: ff00::/8, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: boot, type: unicast
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RequestName cookie=2 reply_cookie=0 signature=su error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=4 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=5 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=6 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=7 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=8 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=10 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=11 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=12 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=13 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=14 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: fe80::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::141/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::142/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::14f/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::3a21/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::3a22/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::3a2f/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:101/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:102/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:103/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:104/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:105/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:106/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:101/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:102/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:103/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:104/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:105/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:106/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: fdb9:1981:930::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: fdb9:1981:930::2:2/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: fdb9:1981:930::2:17/64 (valid forever)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): static addresses are not configured.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Addresses set
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::2:102/64 is not ready
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Bus bus-api-network: changing state HELLO → RUNNING
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got message type=signal sender=org.freedesktop.DBus.Local destination=n/a path=/org/freedesktop/DBus/Local interface=org.freedesktop.DBus.Local member=Connected cookie=4294967295 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got message type=signal sender=org.freedesktop.DBus destination=:1.2 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got message type=signal sender=org.freedesktop.DBus destination=:1.2 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=2 signature=u error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Successfully acquired requested service name.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a cookie=5 reply_cookie=3 signature=n/a error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Match type='signal',sender='org.freedesktop.login1',path='/org/freedesktop/login1',interface='org.freedesktop.login1.Manager',member='PrepareForSleep' successfully installed.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: DHCP CLIENT (0x1739ed8): OFFER
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: DHCP CLIENT (0x1739ed8): REQUEST (requesting)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: DHCP CLIENT (0x1739ed8): ACK
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: DHCP CLIENT (0x1739ed8): lease expires in 23h 59min 57s
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: DHCP CLIENT (0x1739ed8): T2 expires in 20h 59min 58s
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: DHCP CLIENT (0x1739ed8): T1 expires in 12h
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: DHCPv4 address 195.201.98.54/32 via 172.31.1.1
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Updating address: 195.201.98.54
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering foreign address: 195.201.98.54/32 (valid for 1d)
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=15 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:102/64 is not ready.
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=16 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
дек 02 08:48:42 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 195.201.98.54/32, src: n/a, gw: n/a, prefsrc: 195.201.98.54, scope: host, table: local, proto: kernel, type: local
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::141/64 (valid forever)
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:102/64 is not ready.
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::2:102/64 is not ready
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::141/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:104/64 (valid forever)
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:102/64 is not ready.
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::2:102/64 is not ready
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:104/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::3a21/64 (valid forever)
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:102/64 is not ready.
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::2:102/64 is not ready
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::3a21/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::142/64 (valid forever)
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:102/64 is not ready.
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::2:102/64 is not ready
дек 02 08:48:43 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::142/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:102/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address fdb9:1981:930::2:2/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::2:102/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:102/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:102/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address fdb9:1981:930::2:2/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::1:101/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:102/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address fdb9:1981:930::2:2/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::1:101/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:103/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address fdb9:1981:930::2:2/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::1:101/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:103/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:106/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address fdb9:1981:930::2:2/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::1:101/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:106/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::14f/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address fdb9:1981:930::2:2/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::1:101/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::14f/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: fdb9:1981:930::2:2/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address fdb9:1981:930::2:17/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::1:101/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: fdb9:1981:930::2:2/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering foreign address: fe80::9400:ff:fe2f:4396/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address fdb9:1981:930::2:17/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Gained IPv6LL
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address fdb9:1981:930::2:17/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Discovering IPv6 routers
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: NDISC: Started IPv6 Router Solicitation client
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: fe80::9400:ff:fe2f:4396/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:101/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address fdb9:1981:930::2:17/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::3a2f/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:101/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:101/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address fdb9:1981:930::2:17/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::3a2f/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:101/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::2:105/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address fdb9:1981:930::2:17/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::3a2f/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::2:105/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: fdb9:1981:930::2:17/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::3a2f/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: fdb9:1981:930::2:17/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::3a22/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::3a2f/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::3a22/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:104/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:106/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::3a2f/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:104/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:106/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:105/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::3a2f/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:106/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:103/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:105/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::3a2f/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:103/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::3a2f/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 2a01:4f8:c2c:c813::1:105/64 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: an address 2a01:4f8:c2c:c813::1:105/64 is not ready
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::3a2f/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering updated address: 2a01:4f8:c2c:c813::1:105/64 (valid forever)
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 195.201.98.54/32 is not ready.
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Setting routes
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Remembering route: dst: 2a01:4f8:c2c:c813::1:105/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Received remembered route: dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: Routes set
дек 02 08:48:44 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 195.201.98.54/32 is not ready.
дек 02 08:48:45 node2.bkoty.ru systemd-networkd[226]: NDISC: Sent Router Solicitation, next solicitation in 4s
дек 02 08:48:50 node2.bkoty.ru systemd-networkd[226]: NDISC: Sent Router Solicitation, next solicitation in 8s
дек 02 08:48:56 node2.bkoty.ru systemd-networkd[226]: NDISC: No RA received before link confirmation timeout
дек 02 08:48:56 node2.bkoty.ru systemd-networkd[226]: NDISC: Invoking callback for 'timeout' event.
дек 02 08:48:56 node2.bkoty.ru systemd-networkd[226]: ens3: NDisc handler get timeout event
дек 02 08:48:56 node2.bkoty.ru systemd-networkd[226]: ens3: link_check_ready(): an address 195.201.98.54/32 is not ready.
дек 02 08:48:56 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:48:58 node2.bkoty.ru systemd-networkd[226]: NDISC: Sent Router Solicitation, next solicitation in 17s
дек 02 08:49:01 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:49:07 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:49:07 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:49:15 node2.bkoty.ru systemd-networkd[226]: NDISC: Sent Router Solicitation, next solicitation in 34s
дек 02 08:49:26 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:49:50 node2.bkoty.ru systemd-networkd[226]: NDISC: Sent Router Solicitation, next solicitation in 1min 6s
дек 02 08:49:56 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:49:56 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:50:16 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:50:20 node2.bkoty.ru systemd-networkd[226]: Got message type=method_call sender=:1.12 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 08:50:20 node2.bkoty.ru systemd-networkd[226]: Sent message type=method_return sender=n/a destination=:1.12 path=n/a interface=n/a member=n/a cookie=17 reply_cookie=2 signature=v error-name=n/a error-message=n/a
дек 02 08:50:20 node2.bkoty.ru systemd-networkd[226]: Got message type=method_call sender=:1.12 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=3 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 08:50:20 node2.bkoty.ru systemd-networkd[226]: Sent message type=error sender=n/a destination=:1.12 path=n/a interface=n/a member=n/a cookie=18 reply_cookie=3 signature=s error-name=org.freedesktop.DBus.Error.UnknownProperty error-message=Unknown interface org.freedesktop.network1.DHCPServer or property Leases.
дек 02 08:50:30 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:50:30 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:50:41 node2.bkoty.ru systemd-networkd[226]: Got message type=method_call sender=:1.14 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 08:50:41 node2.bkoty.ru systemd-networkd[226]: Sent message type=method_return sender=n/a destination=:1.14 path=n/a interface=n/a member=n/a cookie=19 reply_cookie=2 signature=v error-name=n/a error-message=n/a
дек 02 08:50:41 node2.bkoty.ru systemd-networkd[226]: Got message type=method_call sender=:1.14 destination=org.freedesktop.network1 path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=Get cookie=3 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
дек 02 08:50:41 node2.bkoty.ru systemd-networkd[226]: Sent message type=error sender=n/a destination=:1.14 path=n/a interface=n/a member=n/a cookie=20 reply_cookie=3 signature=s error-name=org.freedesktop.DBus.Error.UnknownProperty error-message=Unknown interface org.freedesktop.network1.DHCPServer or property Leases.
дек 02 08:50:49 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:50:57 node2.bkoty.ru systemd-networkd[226]: NDISC: Sent Router Solicitation, next solicitation in 2min 15s
дек 02 08:51:03 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:51:03 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:51:22 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:51:36 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:51:36 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:51:48 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:51:55 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:52:04 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:52:09 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:52:09 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
дек 02 08:52:29 node2.bkoty.ru systemd-networkd[226]: rtnl: received non-static neighbor, ignoring.
```
</details>

P.S. Date string is formatted for `ru_RU.UTF-8` locale, `дек` means `Dec`.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #17803.

@keszybz Please backport them to v247-stable branch.

### CODE REVIEW

File: src/network/networkd-dhcp4.c [hunk 1]
```diff
@@ -865,7 +865,8 @@ static int dhcp4_update_address(Link *link, bool announce) {
         addr->cinfo.ifa_prefered = lifetime;
         addr->cinfo.ifa_valid = lifetime;
         addr->prefixlen = prefixlen;
-        addr->broadcast.s_addr = address.s_addr | ~netmask.s_addr;
+        if (prefixlen <= 30)
+                addr->broadcast.s_addr = address.s_addr | ~netmask.s_addr;
```
Comment (poettering) [inline src/network/networkd-dhcp4.c:869]: i think this really could use an in-code comment explaining why 30 is the threshold

**Comment by poettering** [comment]
looks superficially OK to me, but I don't grok this in full I must admit. I think some comments in code would be good explaining the arbitrary-looking value of "30" here.

File: src/network/networkd-dhcp4.c (hunk 1 above)
Comment (yuwata) [reply src/network/networkd-dhcp4.c:869]: See https://tools.ietf.org/html/rfc3021.

**Comment by yuwata** [comment]
Updated. One more cleanup commit is added, and the link to RFC is added in the src comment. PTAL.
