### PR TITLE
networkd: bond - only set packets_per_slave on balance-rr mode

### LINKED ISSUE #90: networkd fails to setup bond when mode doesn't support packets_per_slave
systemd-networkd tries to set packets_per_slave on a bond netdev even if its mode doesn't support it.  This leads to the device not being created:

trunk (uninitialized): option packets_per_slave: mode dependency failed, not supoorted in mode 802.3ad(4)

The man page says PacketsPerSlave option "has effect only in balance-rr mode".  That's right, but in addition to that networkd must not try to set it (even to networkd's default) in other modes.

Kludgy workaround: specifying a value > 65535 in the .netdev file will skip setting the option.

### PR DESCRIPTION
**Pull request by teg**
Otherwise the creation of the bond fails.

Fixes #90

### CODE REVIEW

File: src/network/networkd-netdev-bond.c [hunk 1]
```diff
@@ -279,7 +279,8 @@ static int netdev_bond_fill_message_create(NetDev *netdev, Link *link, sd_rtnl_m
                         return log_netdev_error_errno(netdev, r, "Could not append IFLA_BOND_RESEND_IGMP attribute: %m");
         }
 
-        if (b->packets_per_slave <= PACKETS_PER_SLAVE_MAX) {
+        if (b->packets_per_slave <= PACKETS_PER_SLAVE_MAX &&
+            b->mode ==NETDEV_BOND_MODE_BALANCE_RR) {
```
Comment (poettering) [inline src/network/networkd-netdev-bond.c]: There's a space missing between the == and the NETDEV_xxx
