### PR TITLE
core: limit number of LogExtraFields

### LINKED ISSUE #40916: PID 1 crashes when trying to start a transient unit with a lot of LogExtraFields
There's a potential DoS that **requires** root privileges when creating a transient unit with a lot of `LogExtraFields`, as this eventually goes through `newa()` and `safe_alloca()` where it hits the `ALLOCA_MAX` assert:

https://github.com/systemd/systemd/blob/83b8daa032cd0adb538cfd9467e6acf2c44aa661/src/core/unit.c#L5841

Minimized reproducer:

```
python3 -c 'from pydbus import SystemBus; from gi.repository import GLib; SystemBus().get("org.freedesktop.systemd1", "/org/freedesktop/systemd1").StartTransientUnit("crash.service", "fail", [("ExecStart", GLib.Variant("a(sasb)", [("/bin/true", ["/bin/true"], False)])), ("LogExtraFields", GLib.Variant("aay", [b"F%d=x" % i for i in range(140000)]))], [])'
```

Result:
```
# python3 -c 'from pydbus import SystemBus; from gi.repository import GLib; SystemBus().get("org.freedesktop.systemd1", "/org/freedesktop/systemd1").StartTransientUnit("crash.service", "fail", [("ExecStart", GLib.Variant("a(sasb)", [("/bin/true", ["/bin/true"], False)])), ("LogExtraFields", GLib.Variant("aay", [b"F%d=x" % i for i in range(140000)]))], [])'

Broadcast message from systemd-journald@vm (Mon 2026-03-02 13:52:16 EST):

systemd[1]: Caught <ABRT>, from our own process.

Broadcast message from systemd-journald@vm (Mon 2026-03-02 13:52:16 EST):

systemd[1]: Caught <ABRT>, dumped core as pid 1228.


Broadcast message from systemd-journald@vm (Mon 2026-03-02 13:52:16 EST):

systemd[1]: Freezing execution.
```

```
# journalctl -o short-monotonic --no-hostname -b -1
...
[   41.037205] systemd[1]: Caught <ABRT>, from our own process.
[   41.036020] audit[1228]: ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 subj=system_u:system_r:init_t:s0 pid=1228 comm="systemd" exe="/usr/lib/systemd/systemd" sig=6 res=1
[   41.044644] systemd-coredump[1229]: Process 1228 (systemd) of user 0 terminated abnormally with signal 6/ABRT, processing...
[   41.044660] systemd-coredump[1229]: Due to PID 1 having crashed coredump collection will now be turned off.
[   41.184276] systemd-coredump[1229]: [🡕] Process 1228 (systemd) of user 0 dumped core.
                                       
                                       Module libcap-ng.so.0 from rpm libcap-ng-0.9.1-1.fc45.x86_64
                                       Module libaudit.so.1 from rpm audit-4.1.3-1.fc44.x86_64
                                       Module libseccomp.so.2 from rpm libseccomp-2.6.0-3.fc44.x86_64
                                       Module libblkid.so.1 from rpm util-linux-2.41.3-12.fc44.x86_64
                                       Module libmount.so.1 from rpm util-linux-2.41.3-12.fc44.x86_64
                                       Module liblzma.so.5 from rpm xz-5.8.2-2.fc44.x86_64
                                       Module libzstd.so.1 from rpm zstd-1.5.7-5.fc44.x86_64
                                       Module libkmod.so.2 from rpm kmod-34.2-4.fc44.x86_64
                                       Module libpcre2-8.so.0 from rpm pcre2-10.47-1.fc44.1.x86_64
                                       Module libselinux.so.1 from rpm libselinux-3.10-1.fc44.x86_64
                                       Module libz.so.1 from rpm zlib-ng-2.3.3-5.fc45.x86_64
                                       Module ld-linux-x86-64.so.2 from rpm glibc-2.43.9000-2.fc45.x86_64
                                       Module libcrypto.so.3 from rpm openssl-3.5.5-1.fc44.x86_64
                                       Module libm.so.6 from rpm glibc-2.43.9000-2.fc45.x86_64
                                       Module libc.so.6 from rpm glibc-2.43.9000-2.fc45.x86_64
                                       Stack trace of thread 1228:
                                       #0  0x00007fe461efa81d syscall (libc.so.6 + 0xf581d)
                                       #1  0x00007fe46200f78c missing_rt_tgsigqueueinfo (libsystemd-shared-260.so + 0xf78c)
                                       #2  0x00007fe4623461f3 propagate_signal (libsystemd-shared-260.so + 0x3461f3)
                                       #3  0x000000000041a57c crash (/usr/lib/systemd/systemd + 0x1a57c)
                                       #4  0x00007fe461e1f470 __restore_rt (libc.so.6 + 0x1a470)
                                       #5  0x00007fe461e7a9cc __pthread_kill_implementation (libc.so.6 + 0x759cc)
                                       #6  0x00007fe461e1f34e raise (libc.so.6 + 0x1a34e)
                                       #7  0x00007fe461e067b3 abort (libc.so.6 + 0x17b3)
                                       #8  0x00007fe461e07804 __libc_message_impl.cold (libc.so.6 + 0x2804)
                                       #9  0x00007fe461e17285 __assert_fail (libc.so.6 + 0x12285)
                                       #10 0x00007fe4629d95cc unit_export_log_extra_fields (libsystemd-core-260.so + 0x1d95cc)
                                       #11 0x00007fe4629dabd6 unit_export_state_files (libsystemd-core-260.so + 0x1dabd6)
                                       #12 0x00007fe4629db6c5 unit_prepare_exec (libsystemd-core-260.so + 0x1db6c5)
                                       #13 0x00007fe46294f1f4 service_spawn_internal (libsystemd-core-260.so + 0x14f1f4)
                                       #14 0x00007fe46295452b service_enter_start (libsystemd-core-260.so + 0x15452b)
                                       #15 0x00007fe462954c74 service_enter_start_pre (libsystemd-core-260.so + 0x154c74)
                                       #16 0x00007fe462954f77 service_enter_condition (libsystemd-core-260.so + 0x154f77)
                                       #17 0x00007fe462959c9f service_start (libsystemd-core-260.so + 0x159c9f)
                                       #18 0x00007fe4629c3d25 unit_start (libsystemd-core-260.so + 0x1c3d25)
                                       #19 0x00007fe4628c3907 job_perform_on_unit (libsystemd-core-260.so + 0xc3907)
                                       #20 0x00007fe4628c3b9f job_run_and_invalidate (libsystemd-core-260.so + 0xc3b9f)
                                       #21 0x00007fe4628fd1c4 manager_dispatch_run_queue (libsystemd-core-260.so + 0xfd1c4)
                                       #22 0x00007fe4623e2faa source_dispatch (libsystemd-shared-260.so + 0x3e2faa)
                                       #23 0x00007fe4623e50d7 sd_event_dispatch (libsystemd-shared-260.so + 0x3e50d7)
                                       #24 0x00007fe4623e55f4 sd_event_run (libsystemd-shared-260.so + 0x3e55f4)
                                       #25 0x00007fe4629009a8 manager_loop (libsystemd-core-260.so + 0x1009a8)
                                       #26 0x0000000000414e7f invoke_main_loop (/usr/lib/systemd/systemd + 0x14e7f)
                                       #27 0x0000000000419a04 main (/usr/lib/systemd/systemd + 0x19a04)
                                       #28 0x00007fe461e08681 __libc_start_call_main (libc.so.6 + 0x3681)
                                       #29 0x00007fe461e08798 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x3798)
                                       #30 0x00000000004085a5 _start (/usr/lib/systemd/systemd + 0x85a5)
                                       ELF object binary architecture: AMD x86-64
[   41.188628] systemd[1]: Caught <ABRT>, dumped core as pid 1228.
[   41.188657] systemd[1]: Freezing execution.
[   42.349920] systemd-oomd[900]: Failed to connect to /run/systemd/io.systemd.ManagedOOM: Connection refused
[   42.349932] systemd-oomd[900]: Failed to acquire varlink connection: Connection refused
[   42.350064] systemd-oomd[900]: Event loop failed: Connection refused
```

Relevant snippet from a symbolized stack trace:

```gdb
...
#11 __assert_fail (assertion=0x7fe462aa886c "_nn_ <= ALLOCA_MAX", file=0x7fe462aa7dbd "../src/core/unit.c", line=<optimized out>, function=<optimized out>) at assert.c:37
        linebuf = "\000\000\000\000\000\0005841"
        linestr = 0x7ffed83bd113 "5841"
#12 0x00007fe4629d95cc in unit_export_log_extra_fields (u=0x282ebf10, c=0x282ec358) at ../src/core/unit.c:5841
        _nn_ = 4480000
        _n_ = 4480000
        fd = -9
        iovec = 0x282ebf10
        p = 0x7fe4629d8e94 <unit_export_invocation_id+1066> "\211\330H\213U\330dH+\024%("
        pattern = 0x282ebf10 "\200*$("
        sizes = 0x7ffed83bd160
        n = 676030544
        r = 0
        __func__ = "unit_export_log_extra_fields"
        __PRETTY_FUNCTION__ = "unit_export_log_extra_fields"
#13 0x00007fe4629dabd6 in unit_export_state_files (u=0x282ebf10) at ../src/core/unit.c:5964
        c = 0x282ec358
        __PRETTY_FUNCTION__ = "unit_export_state_files"
#14 0x00007fe4629db6c5 in unit_prepare_exec (u=0x282ebf10) at ../src/core/unit.c:6061
        r = 0
        __PRETTY_FUNCTION__ = "unit_prepare_exec"
        crt = 0x28279d50
...
```

### PR DESCRIPTION
**Pull request by keszybz**
We have two places where those fields can be set: config and the dbus interface. Let's clamp down on the number in both places. But in principle, we could also be upgrading (through serialization/deserialization) from an older systemd which didn't enforce this limit, so also check on deserialization. A user could have a unit with lots and lots of ExtraFields, but not enough to cause the issue in #40916. To handle this gracefully, ignore the extra fields, like we do in the parser. Where the field is used, assert that we are within the expected bounds.

Fixes #40916.

Reproducer:
```console
$ python3 -c 'from pydbus import SystemBus; from gi.repository import GLib; SystemBus().get("org.freedesktop.systemd1", "/org/freedesktop/systemd1").StartTransientUnit("crash.service", "fail", [("ExecStart", GLib.Variant("a(sasb)", [("/bin/true", ["/bin/true"], False)])), ("LogExtraFields", GLib.Variant("aay", [b"F%d=x" % i for i in range(140000)]))], [])' Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from pydbus import SystemBus; from gi.repository import GLib; SystemBus().get("org.freedesktop.systemd1", "/org/freedesktop/systemd1").StartTransientUnit("crash.service", "fail", [("ExecStart", GLib.Variant("a(sasb)", [("/bin/true", ["/bin/true"], False)])), ("LogExtraFields", GLib.Variant("aay", [b"F%d=x" % i for i in range(140000)]))], [])
                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/pydbus/proxy_method.py", line 102, in __call__
    raise error
  File "/usr/lib/python3.14/site-packages/pydbus/proxy_method.py", line 97, in __call__
    result = instance._bus.con.call_sync(*call_args)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Too many extra log fields. (16)
```

### CODE REVIEW

**Comment by bluca** [comment]
Have you seen https://github.com/systemd/systemd/pull/41040 ?

**Comment by bluca** [comment]
Would be good to put the reproducer in a test to avoid regressions

**Comment by keszybz** [comment]
I don't think a test makes sense. I tested that the fix works, and how could it regress? Somebody removes the check by mistake?

**Comment by bluca** [comment]
Yeah, accidentally via one of the usual large refactors that happen occasionally

File: src/core/dbus-execute.c [hunk 1]
```diff
@@ -2806,6 +2806,9 @@ int bus_exec_context_set_transient_property(
                                 return sd_bus_error_set(reterr_error, SD_BUS_ERROR_INVALID_ARGS, "Journal field is not valid UTF-8");
 
                         if (!UNIT_WRITE_FLAGS_NOOP(flags)) {
+                                if (c->n_log_extra_fields == LOG_EXTRA_FIELDS_MAX)
```
Comment (poettering) [inline src/core/dbus-execute.c]: can we make this a >= thing?

feels safer that way, and we usually do it like that.

File: src/core/unit.h [hunk 2]
```diff
@@ -1097,6 +1098,11 @@ int unit_queue_job_check_and_mangle_type(Unit *u, JobType *type, bool reload_if_
 int parse_unit_marker(const char *marker, unsigned *settings, unsigned *mask);
 unsigned unit_normalize_markers(unsigned existing_markers, unsigned new_markers);
 
+/* Trying to log with too many fields is going to fail. We need at least also MESSAGE=,
+ * but we generally log a few extra in most cases. So let's reserve 10. Anything
+ * above a few would be very unusual, but let's not be overly strict. */
+#define LOG_EXTRA_FIELDS_MAX ENTRY_FIELD_COUNT_MAX - 10
```
Comment (poettering) [inline src/core/unit.h]: please wrap in ()
