### PR TITLE
resolve: check for overflow and underflow of size parameter

### LINKED ISSUE #7888: negative malloc based on untrusted input to dns_packet_read_rr
This doesn't appear to be a particularly exploitable bug (it doesn't appear to even crash normally), so reporting this here instead of via a private security channel.

```
==7434==WARNING: AddressSanitizer failed to allocate 0xfffffffffffffffe bytes
==7434==AddressSanitizer's allocator is terminating the process instead of returning 0
==7434==If you don't like this behavior set allocator_may_return_null=1
==7434==AddressSanitizer CHECK failed: /build/llvm-toolchain-4.0-2OlUsF/llvm-toolchain-4.0-4.0.1/projects/compiler-rt/lib/sanitizer_common/sanitizer_allocator.cc:221 "((0)) != (0)" (0x0, 0x0)
    #0 0x558211a52be5 in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/src/build/fuzz-dns-packet+0xedbe5)
    #1 0x558211a6e785 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/src/build/fuzz-dns-packet+0x109785)
    #2 0x558211a587d2 in __sanitizer::ReportAllocatorCannotReturnNull(bool) (/src/build/fuzz-dns-packet+0xf37d2)
    #3 0x55821199a8c6 in __asan::asan_malloc(unsigned long, __sanitizer::BufferedStackTrace*) (/src/build/fuzz-dns-packet+0x358c6)
    #4 0x558211a499db in __interceptor_malloc (/src/build/fuzz-dns-packet+0xe49db)
    #5 0x7f101d690e39 in memdup /src/build/../src/basic/alloc-util.c:33:15
    #6 0x558211a951c2 in dns_packet_read_memdup /src/build/../src/resolve/resolved-dns-packet.c:1258:24
    #7 0x558211a932b0 in dns_packet_read_rr /src/build/../src/resolve/resolved-dns-packet.c:1862:21
    #8 0x558211a961a3 in dns_packet_extract /src/build/../src/resolve/resolved-dns-packet.c:2166:29
    #9 0x558211a83bbe in LLVMFuzzerTestOneInput /src/build/../src/fuzz/fuzz-dns-packet.c:37:9
    #10 0x558211a84135 in main /src/build/../src/fuzz/fuzz-main.c:47:23
    #11 0x7f101bf771c0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x211c0)
    #12 0x558211994389 in _start (/src/build/fuzz-dns-packet+0x2f389)
```

To reproduce:

- Download [crash-3c8df8ed701dc81fd7b2245c4f5d08f532074f70-minimized.txt](https://github.com/systemd/systemd/files/1633409/crash-3c8df8ed701dc81fd7b2245c4f5d08f532074f70-minimized.txt)
- `git fetch origin pull/7876/head:oss-fuzz && git checkout oss-fuzz` (to get PR #7876 that includes the fuzzer)
- `CC=clang meson build -Db_lundef=false -Db_sanitize=address && ninja -C build fuzzers`
- `build/fuzz-dns-packet crash-3c8df8ed701dc81fd7b2245c4f5d08f532074f70-minimized.txt`

On Ubuntu I ran the following to get the right clang/symbolizer setup, if you're on a different distro it will be a bit different:

```
apt-get install clang-4.0
export ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-4.0/bin/llvm-symbolizer
export CC=clang-4.0
```

The problem appears to be this line, which subtracts from the untrusted `rdlength` without any checks, causing it to wrap around:

https://github.com/systemd/systemd/blob/c46bc7e2162d774f55847c1a8cb9d49085cf89bb/src/resolve/resolved-dns-packet.c#L1862-L1864

There's another similar line that probably has a similar problem:

https://github.com/systemd/systemd/blob/c46bc7e2162d774f55847c1a8cb9d49085cf89bb/src/resolve/resolved-dns-packet.c#L1840-L1842

### PR DESCRIPTION
**Pull request by shawnl**
to dns_packet_read_memdup()

Closes #7888

### CODE REVIEW

File: src/resolve/resolved-dns-packet.c [hunk 1]
```diff
@@ -1837,6 +1837,9 @@ int dns_packet_read_rr(DnsPacket *p, DnsResourceRecord **ret, bool *ret_cache_fl
                 if (r < 0)
                         return r;
 
+                if (rdlength - 4 > rdlength)
```
Comment (keszybz) [inline src/resolve/resolved-dns-packet.c]: Hmm, wouldn't it be nicer to write this as `rdlength < 4`? Shorter and more straightforward than exploiting wraparound.

File: src/resolve/resolved-dns-packet.c [hunk 2]
```diff
@@ -1859,6 +1862,9 @@ int dns_packet_read_rr(DnsPacket *p, DnsResourceRecord **ret, bool *ret_cache_fl
                 if (r < 0)
                         return r;
 
+                if (rdlength - 2 > rdlength)
```
Comment (keszybz) [inline src/resolve/resolved-dns-packet.c]: Likewise.

File: src/resolve/resolved-dns-packet.c [hunk 3]
```diff
@@ -1883,6 +1889,9 @@ int dns_packet_read_rr(DnsPacket *p, DnsResourceRecord **ret, bool *ret_cache_fl
                 if (r < 0)
                         return r;
 
+                if (rdlength - 4 > rdlength)
```
Comment (keszybz) [inline src/resolve/resolved-dns-packet.c]: Likewise.

File: src/resolve/resolved-dns-packet.c [hunk 4]
```diff
@@ -1837,6 +1837,9 @@ int dns_packet_read_rr(DnsPacket *p, DnsResourceRecord **ret, bool *ret_cache_fl
...
+                        return -EOVERFLOW;
```
Comment (poettering) [inline src/resolve/resolved-dns-packet.c]: I'd really treat this as -EBADMSG here, after all the caller just wants to have this parsed and an overflow is definitely one ind of invalid msg

File: src/resolve/resolved-dns-packet.c [hunk 5]
```diff
@@ -1927,6 +1936,10 @@ int dns_packet_read_rr(DnsPacket *p, DnsResourceRecord **ret, bool *ret_cache_fl
                 if (r < 0)
                         return r;
 
+                if ((offset + rdlength - p->rindex <          rdlength - p->rindex) ||
+                    (offset + rdlength - p->rindex > offset + rdlength))
+                        return -EOVERFLOW;
```
Comment (keszybz) [inline src/resolve/resolved-dns-packet.c]: And isn't this equivalent to `rdlength < p->rindex - rdlength`?

Comment (shawnl) [reply src/resolve/resolved-dns-packet.c]: You mean rdlength + offset < p->rindex, and that is the bug causing the tests to fail.

**Comment by shawnl** [comment]
patch updated.
