### PR TITLE
locale,firstboot: add comments to vconsole.conf

### LINKED ISSUE #29717: /etc/vconsole.conf is overwritten by localectl without any comment, in contrast to the added comment at X onfig file
### systemd version the issue has been seen with

254.5-1

### Used distribution

arch

### Linux kernel version used

6.5.7

### CPU architectures issue was seen on

None

### Component

other

### Expected behaviour you didn't see

When localectl writes X config file, possibly by [x11_write_data](https://github.com/systemd/systemd/tree/v253/src/locale/localed-util.c#L470), it bothers to add a [comment who wrote it](https://github.com/systemd/systemd/tree/v253/src/locale/localed-util.c#L494-L496). I would expect a similar comment when it writes ``/etc/vconsole.conf`` by [vconsole_write_data](https://github.com/systemd/systemd/tree/v253/src/locale/localed-util.c#L415). One reason is so an unaware user would get a clue who overwrote his data.

It would be even better if any user comments that were in the ``/etc/vconsole.conf`` before it was overwritten would be preserved. Or that there would be a command line parameter ``--no-overwrite-config``. Users who prefer it that way might over write the files manually.
Edit: Instead, or in addition to, ``--no-overwrite-config``, ``--dry-run`` can do the trick. ``localectl --dry-run ...`` would do everything as before, except actually writing the files. Instead, it will print to ``stdout``, along with the filenames, what it would otherwise write to the files. The user can then decides what to do further.

### Unexpected behaviour you saw

/etc/vconsole.conf is overwritten with no comments what did it.

### Steps to reproduce the problem

1. ```su --login```
2. ```sed -i '1i\# a comment line' /etc/vconsole.conf```
3. ```localectl set-x11-keymap cz,us pc104 ,dvorak grp:win_space_toggle```
4. ```cat /etc/vconsole.conf```
Note no comment who rewrote the file, in contrast to the comment at X config.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Closes #29717.
Replaces #29760.

### CODE REVIEW

File: src/basic/env-file.c [hunk 1]
```diff
@@ -631,3 +637,12 @@ int write_env_file_at(int dir_fd, const char *fname, char **l) {
         (void) unlinkat(dir_fd, p, 0);
         return r;
 }
+
+int write_vconsole_conf(int dir_fd, const char *fname, char **l) {
+        char **headers = STRV_MAKE(
+                "# Written by systemd-localed(8) or systemd-firstboot(1), read by systemd-localed.",
```
Comment (YHNdnzj) [inline src/basic/env-file.c]:
```suggestion
                "# Written by systemd-localed(8) or systemd-firstboot(1), read by systemd-localed and systemd-vconsole-setup.",
```

**Review by YHNdnzj — APPROVED** [review]

**Comment by yuwata** [comment]
@YHNdnzj Thank you for the review. The suggestion is applied.

File: src/basic/env-file.c [hunk 2]
```diff
@@ -637,3 +637,12 @@ int write_env_file(int dir_fd, const char *fname, char **headers, char **l) {
         (void) unlinkat(dir_fd, p, 0);
         return r;
 }
+
+int write_vconsole_conf(int dir_fd, const char *fname, char **l) {
+        char **headers = STRV_MAKE(
+                "# Written by systemd-localed(8) or systemd-firstboot(1), read by systemd-localed",
+                "# and systemd-vconsole-setup. It is probably wise not to edit this file manually.",
```
Comment (poettering) [inline src/basic/env-file.c]: i think it's totally Ok to edit this file manually. I'd remove that part.

File: src/basic/env-file.c [hunk 3]
```diff
@@ -637,3 +637,12 @@ int write_env_file(int dir_fd, const char *fname, char **headers, char **l) {
...
+                "# Use localectl(1) to instruct systemd-localed to update it.");
```
Comment (poettering) [inline src/basic/env-file.c]: I think that systemd-localed is involved is kinda an implementation detail and should not be mentioned again. I mean, you already say so in the first sentence.

File: src/basic/env-file.c (hunk 2 above)
Comment (poettering) [reply src/basic/env-file.c]: PID 1 reads this too btw.

Comment (yuwata) [reply src/basic/env-file.c]: > i think it's totally Ok to edit this file manually. I'd remove that part.

When the file is updated by localed, systemd-vconsole-setup.service is restarted. Should we mention that the service should be also restarted manually when the file is manually edited?

Comment (yuwata) [reply src/basic/env-file.c]: > PID 1 reads this too btw.

Does it? I cannot find relevant code. Maybe you confused with locale.conf ?

File: src/basic/env-file.c (hunk 3 above)
Comment (yuwata) [reply src/basic/env-file.c]: OK.
Note, the comment is copied from xorg.conf. I will also drop that part from xorg.conf.

File: src/basic/env-file.c (hunk 2 above)
Comment (poettering) [reply src/basic/env-file.c]: oops, indeed. sorry.

File: src/basic/env-file.c (hunk 3 above)
Comment (poettering) [reply src/basic/env-file.c]: yes, please

**Comment by yuwata** [comment]
@poettering Updated. PTAL.

File: src/basic/env-file.c [hunk 4]
```diff
@@ -637,3 +637,12 @@ int write_env_file(int dir_fd, const char *fname, char **headers, char **l) {
         (void) unlinkat(dir_fd, p, 0);
         return r;
 }
+
+int write_vconsole_conf(int dir_fd, const char *fname, char **l) {
+        char **headers = STRV_MAKE(
+                "# Written by systemd-localed(8) or systemd-firstboot(1), read by systemd-localed",
+                "# and systemd-vconsole-setup(8). It is probably wise not to edit this file manually."
```
Comment (poettering) [inline src/basic/env-file.c]: it' still drop the "It is probably wise not to edit this file manually". It should be fine to edit it manually, if people want. I think you can strike this and just keep the recommendation to use localectl(1). It alone conveys the suggestion that that's the primary interface to it.

File: src/basic/env-file.c [hunk 5]
```diff
@@ -637,3 +637,12 @@ int write_env_file(int dir_fd, const char *fname, char **headers, char **l) {
...
+                "# Use localectl(1) to update it.");
```
Comment (poettering) [inline src/basic/env-file.c]: "it" → "this file"

File: src/locale/localed-util.c [hunk 6]
```diff
@@ -568,7 +568,7 @@ int x11_write_data(Context *c) {
 
         fputs("# Written by systemd-localed(8), read by systemd-localed and Xorg. It's\n"
               "# probably wise not to edit this file manually. Use localectl(1) to\n"
```
Comment (poettering) [inline src/locale/localed-util.c:570]: here the comment `It's probably wise not to edit this file manually` makes a ton of sense, because we never read this file, we always overwrite it. vconsole.conf is the primary source of information after all, this xorg drop-in is only generated from it.

Hence, editing vconsole.conf manually is OK, but editing the xorg file is not, you will lose everything once localed rewrites anything.

**Comment by yuwata** [comment]
Updated. PTAL.

**Comment by poettering** [comment]
lgtm! thanks!
