### PR TITLE
core/socket: do not log failure in setting socket option with number

### LINKED ISSUE #39792: "Failed to set 16 socket option, ignoring: Operation not supported" with v258
### systemd version the issue has been seen with

258.1-2

### Used distribution

Debian forky/sid

### Linux kernel version used

6.17.0

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

[mpd.socket](https://github.com/MusicPlayerDaemon/MPD/blob/v0.24.6/systemd/system/mpd.socket.in) would start without error.

### Unexpected behaviour you saw

The following error message is logged to the journal:

    Nov 18 11:07:50 hostname systemd[1703]: mpd.socket: Failed to set 16 socket option, ignoring: Operation not supported

### Steps to reproduce the problem

1. Install [Music Player Daemon](https://www.musicpd.org/) (`apt install mpd` on Debian-based distros).
2. `systemctl start mpd.socket` (with or without `--user` - mpd ships both user and system sockets, and either will demonstrate the issue)

### Additional information

- I am able to reproduce the issue with systemd 258~rc4-1.
- I am unable to reproduce the issue with systemd 257.7-1.
- I am able to reproduce the issue on Linux 6.16.0.
- I believe socket option 16 is `SO_PASSCRED`, which makes me wonder if https://github.com/systemd/systemd/pull/37793 is related.  Any thoughts @bluca?

### PR DESCRIPTION
**Pull request by yuwata**
This also downgrade to the debug level when the option is simply not supported.

Follow-up for b81a14b91efea17631d634f5dbd69314780815ab.
Fixes #39792.

### CODE REVIEW

File: src/core/socket.c [hunk 1]
```diff
@@ -1027,9 +1027,16 @@ static void socket_close_fds(Socket *s) {
 
 DEFINE_TRIVIAL_CLEANUP_FUNC_FULL(Socket*, socket_close_fds, NULL);
 
-#define SOCKET_OPTION_WARNING_FORMAT_STR "Failed to set %s socket option, ignoring: %m"
-#define log_socket_option_warning_errno(s, error, option) \
-        log_unit_warning_errno(UNIT(s), (error), SOCKET_OPTION_WARNING_FORMAT_STR, STRINGIFY(option))
```
Comment (YHNdnzj) [inline src/core/socket.c:1032]: I guess XSTRINGIFY will do?

File: src/core/socket.c [hunk 2]
```diff
@@ -1027,9 +1027,16 @@ static void socket_close_fds(Socket *s) {
...
+#define log_socket_option_errno(s, e, option)                                          \
+        ({                                                                             \
+                int _e_ = (e);                                                         \
+                log_unit_full_errno(                                                   \
+                                UNIT(s),                                               \
+                                ERRNO_IS_NOT_SUPPORTED(_e_) ? LOG_DEBUG : LOG_WARNING, \
```
Comment (YHNdnzj) [inline src/core/socket.c:1035]: I don't think this should be applied generically. The options below our kernel baseline in particular should always be logged, as it's really weird if we get EOPTNOTSUPP

Comment (yuwata) [reply src/core/socket.c:1035]: An option may not be supported when unprivileged? At least the original issue report suggests so.

File: src/core/socket.c (hunk 1 above)
Comment (yuwata) [reply src/core/socket.c:1032]: Maybe. Not sure. I think it is better to take string for generic case, e.g. timestamping.

File: src/core/socket.c (hunk 2 above)
Comment (keszybz) [reply src/core/socket.c:1035]: Yeah, there's just too many conditions where a sockopt might fail. I'm pretty sure we don't want to keep a table with kernel versions.
