### PR TITLE
meson: bump required minimum version to 0.62.0

### LINKED ISSUE #35967: systemd fails to build on Ubuntu 22.04 with "src/udev/meson.build:281:8: ERROR: install_emptydir got unknown keyword arguments "install_tag"
### systemd version the issue has been seen with

ad7e0fdbf9714a1f1c73fa6dc0b9c3a6b6da7bb7

### Used distribution

Ubuntu 22.04.5 LTS

### Linux kernel version used

Linux version 5.15.0-130-generic

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

According to https://github.com/systemd/systemd/issues/35961 it should build.

### Unexpected behaviour you saw

```sh
$ meson --version
0.61.2

Program generate-ip-protocol-list.sh found: YES (/home/vagrant/systemd-valgrind/src/shared/generate-ip-protocol-list.sh)
Program generate-keyboard-keys-list.sh found: YES (/home/vagrant/systemd-valgrind/src/udev/generate-keyboard-keys-list.sh)
Program generate-keyboard-keys-gperf.sh found: YES (/home/vagrant/systemd-valgrind/src/udev/generate-keyboard-keys-gperf.sh)

src/udev/meson.build:281:8: ERROR: install_emptydir got unknown keyword arguments "install_tag"

A full log can be found at /home/vagrant/systemd-valgrind/build/meson-logs/meson-log.txt
```

It was introduced in https://github.com/systemd/systemd/pull/35946.

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
- bump the requred minimum version of meson to 0.62.0,
- use install_symlink(), which is supported since meson-0.61.0,
- use more features provided by newer meson with careful conditionalization.

Follow-up for 8442ac9c0264ac7beb5afd6c3bf922030a6edaf3.
Closes #35967.

### CODE REVIEW

**Comment by YHNdnzj** [comment]
I reckon we can finally sort out https://github.com/systemd/systemd/pull/28042 too?

**Comment by YHNdnzj** [comment]
hrm, any reason not going to 0.63 directly then?

**Comment by yuwata** [comment]
> I reckon we can finally sort out #28042 too?

I forgot. I will add it in this PR.

> hrm, any reason not going to 0.63 directly then?

I do not see any new interesting features in the release.
We can bump to 0.63, but not necessary right now.

File: profile.d/meson.build [hunk 1]
```diff
@@ -4,15 +4,33 @@ install_data('70-systemd-shell-extra.sh', install_dir : shellprofiledir.startswi
 install_data('80-systemd-osc-context.sh', install_dir : shellprofiledir.startswith('/usr/') ? shellprofiledir : libexecdir / 'profile.d')
 
 if conf.get('LINK_SHELL_EXTRA_DROPIN') == 1
-        install_emptydir(shellprofiledir)
+        if meson.version().version_compare('<1.3.0') # FATAL_WARNING_MARKER_REMOVE_SINGLE
```
Comment (evverx) [inline profile.d/meson.build]: I think `>=1.3.0` (with the `else` clause handling `<1.3.0`) should do the trick without markers.

Comment (yuwata) [reply profile.d/meson.build]: interesting... thank you.

File: test/meson.build [hunk 2]
```diff
@@ -1,4 +1,4 @@
-# SPDX-License-Identifier: LGPL-2.1-or-later
+1# SPDX-License-Identifier: LGPL-2.1-or-later
```
Comment (keszybz) [inline test/meson.build]: Nope.

Comment (bluca) [inline test/meson.build]: typo?

File: profile.d/meson.build [hunk 3]
```diff
@@ -4,15 +4,33 @@ install_data('70-systemd-shell-extra.sh', install_dir : shellprofiledir.startswi
...
+        else
+                install_emptydir(shellprofiledir)
 
-        meson.add_install_script(sh, '-c',
-                ln_s.format(libexecdir / 'profile.d' / '70-systemd-shell-extra.sh', shellprofiledir / '70-systemd-shell-extra.sh'))
+                meson.add_install_script(sh, '-c',
+                        ln_s.format(libexecdir / 'profile.d' / '70-systemd-shell-extra.sh',
+                                    shellprofiledir / '70-systemd-shell-extra.sh'))
+        endif
 endif
```
Comment (keszybz) [inline profile.d/meson.build:20]: Hmm, does this make sense? Maybe let's just leave this as it was until we the baseline is moved to 1.3.0?

**Review by bluca — APPROVED** [review]

File: src/ssh-generator/meson.build [hunk 4]
```diff
@@ -21,9 +21,18 @@ if conf.get('ENABLE_SSH_PROXY_CONFIG') == 1
...
+                                install_dir : sshconfdir)
+                else
+                        install_emptydir(sshconfdir)
 
-                meson.add_install_script(sh, '-c',
-                        ln_s.format(libexecdir / 'ssh_config.d' / '20-systemd-ssh-proxy.conf', sshconfdir / '20-systemd-ssh-proxy.conf'))
+                        meson.add_install_script(sh, '-c',
+                                ln_s.format(libexecdir / 'ssh_config.d' / '20-systemd-ssh-proxy.conf',
+                                            sshconfdir / '20-systemd-ssh-proxy.conf'))
+                endif
```
Comment (keszybz) [inline src/ssh-generator/meson.build:36]: Ditto.

File: test/test-network/conf/25-default.link
Comment (bluca) [inline test/test-network/conf/25-default.link:1]: given it's for a test, this doesn't need the full header that is used for shipped files. Instead, given it's a copy, please add a comment that says it is, and the path to the original, to make it a bit easier to remember

File: src/udev/meson.build [hunk 5]
```diff
@@ -269,9 +269,11 @@ executables += [
...
 ]
 
-meson.add_install_script(sh, '-c', ln_s.format(bindir / 'udevadm',
-                                               libexecdir / 'systemd-udevd'),
-                         install_tag : 'udev')
+assert(fs.parent(fs.parent(libexecdir)) / 'bin' == bindir)
+install_symlink('systemd-udevd',
+                pointing_to : '../../bin/udevadm',
+                install_dir : libexecdir,
+                install_tag : 'udev')
```
Comment (keszybz) [inline src/udev/meson.build]: That seems iffy. Not all layouts use the same structure, and we don't want to break users' setups. The existing call was more robust, so let's leave it.

File: src/userdb/meson.build [hunk 6]
```diff
@@ -34,9 +34,18 @@ if conf.get('ENABLE_SSH_USERDB_CONFIG') == 1
...
+                                install_dir : sshdconfdir)
+                else
+                        install_emptydir(sshdconfdir)
 
-                meson.add_install_script(sh, '-c',
-                        ln_s.format(libexecdir / 'sshd_config.d' / '20-systemd-userdb.conf', sshdconfdir / '20-systemd-userdb.conf'))
+                        meson.add_install_script(sh, '-c',
+                                ln_s.format(libexecdir / 'sshd_config.d' / '20-systemd-userdb.conf',
+                                            sshdconfdir / '20-systemd-userdb.conf'))
+                endif
```
Comment (keszybz) [inline src/userdb/meson.build:49]: Also here, I don't think the added verbosity is worth it.

File: units/meson.build [hunk 7]
```diff
@@ -949,10 +950,18 @@ install_data('user@0.service.d/10-login-barrier.conf',
...
+                'org.freedesktop.systemd1.service',
+                pointing_to : fs.relative_to(dbussystemservicedir / 'org.freedesktop.systemd1.service',
+                                             dbussessionservicedir),
+                install_dir : dbussessionservicedir)
+else
+        install_emptydir(dbussessionservicedir)
+        meson.add_install_script(sh, '-c',
+                ln_s.format(dbussystemservicedir / 'org.freedesktop.systemd1.service',
+                            dbussessionservicedir / 'org.freedesktop.systemd1.service'))
+endif
```
Comment (keszybz) [inline units/meson.build:962]: Ditto.

**Review by keszybz — CHANGES_REQUESTED** [review]

File: profile.d/meson.build (hunk 3 above)
Comment (bluca) [reply profile.d/meson.build:20]: If there's a perf advantage because of fewer shelling out it could be worth it, but should be measured

Comment (keszybz) [reply profile.d/meson.build:20]: I guess the more important advantage might be if we avoid noise in installation logs…

Comment (yuwata) [reply profile.d/meson.build:20]: Why not? I guess most developer uses newer meson, hence newer method can be used.
Newer method should be the way to go. But, we need to keep the old way for older meson.

File: src/udev/meson.build (hunk 5 above)
Comment (yuwata) [reply src/udev/meson.build]: We hardcode liexecdir and bindir. We do not support custom layout.

File: profile.d/meson.build (hunk 3 above)
Comment (YHNdnzj) [reply profile.d/meson.build:20]: Yeah, this also minimizes adoption work in the future. I think we should actually make more use of the pattern.

File: profile.d/meson.build (hunk 1 above)
Comment (eli-schwartz) [reply profile.d/meson.build]: This happens because meson knows how to special case the `meson.version().version_compare` function object, and when entering an if stack, it temporarily overrides the "effective" minimum version for the duration of the if stack.

So, inside of this block, it is ***as if*** you had a project `meson_version: '<1.3.0'`, which does not actually help avoid "feature too new" warnings.

In principle there's no reason we would turn down code that made this handle else blocks too. But it's not immediately apparent how to do so, since else blocks would have to understand the context of the original if, as well as elif statements, and invert the former reliably. (?) In nearly all cases you can just rewrite it using >= instead, which is simple to get correct.

File: profile.d/meson.build (hunk 3 above)
Comment (eli-schwartz) [reply profile.d/meson.build:20]: - using conditional code for newer versions of meson means that when dropping old versions in the future it is "obvious" what to do: simply drop the dead branch
- using `add_install_script` does not get tracked for `ninja uninstall`, whereas using `install_symlink` will get removed correctly

File: src/udev/meson.build (hunk 5 above)
Comment (eli-schwartz) [reply src/udev/meson.build]: If it was crucial to support non-hardcoded bindir/libexecdir then you could use `fs.relative_to()` in order to compute the relative path.

File: profile.d/meson.build (hunk 1 above)
Comment (evverx) [reply profile.d/meson.build]: > In nearly all cases you can just rewrite it using >= instead, which is simple to get correct.

I think the problem is that it isn't obvious. For example ea07a6d45daf50d948a8a904f0417cf25c97ab65 was merged with `<1.3.0` and since that part has never been covered by the workflows with warnings it wasn't noticed. I think ideally it would be great if it worked without having to remember that `>=` should be used.

Comment (eli-schwartz) [reply profile.d/meson.build]: I refer you back to

> In principle there's no reason we would turn down code that made this handle else blocks too. But it's not immediately apparent how to do so

Or as they say in the old country,

> Patches welcome :)

Comment (eli-schwartz) [reply profile.d/meson.build]: (I really do mean this quite sincerely. I tried to figure out a way and failed. I wish it worked.)
