### PR TITLE
core: Check unit start rate limiting earlier

### LINKED ISSUE #17433: PathExists in path unit when paired with ConditionPathExists in triggered service makes pid1 unresponsive
**systemd version the issue has been seen with**
246

**Used distribution**
CentOS7

**Linux kernel version used** (`uname -a`)
5.2.9

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
path unit fires upon the existence of `PathExists`, corresponding service unit runs once, systemd remains responsive

**Unexpected behaviour you saw**
path unit fired after file was touched, service unit also fired, but pid1 CPU goes to 100%, and calls via `systemctl` (both via sudo and as root) hang.

**Steps to reproduce the problem**
[root@box ~]# cat /etc/systemd/system/test123.path
[Path]
PathExists=/tmp/test123

[Install]
WantedBy=multi-user.target

[root@box ~]# cat /etc/systemd/system/test123.service
[Unit]
Description=Test 123
ConditionPathExists=!/tmp/nopenopenope

[Service]
Type=oneshot
ExecStart=/bin/touch /tmp/nopenopenope

[Install]
WantedBy=multi-user.target

[root@box ~]# systemctl daemon-reload
[root@box ~]# systemctl start test123.path
[root@box ~]# touch /tmp/test123

[root@box ~]# systemctl status test123.service
   ... hangs  

/var/log/messages has many thousands of messages about:
"systemd[1]: Condition check resulted in Test 123 being skipped."

Removing the original trigger file (`rm /tmp/test123`) restores systemd responsiveness

### PR DESCRIPTION
**Pull request by daandemeyer**
Fixes #17433. Currently, if any of the validations we do before we
check start rate limiting fail, we can still enter a busy loop as
no rate limiting gets applied. A common occurence of this scenario
is path units triggering a service that fails a condition check.

To fix the issue, we simply move up start rate limiting checks to
be the first thing we do when starting a unit. To achieve this,
we add a new method to the unit vtable and implement it for the
relevant unit types so that we can do the start rate limit checks
earlier on.

The reproduce from #17433 now correctly gets rate limited instead of triggering a busy loop in systemd.

```
[root@image ~]# systemctl status test123.service
× test123.service - Test 123
     Loaded: loaded (/etc/systemd/system/test123.service; disabled; vendor preset: disabled)
     Active: failed (Result: start-limit-hit) since Tue 2021-08-24 16:53:06 BST; 58s ago
TriggeredBy: × test123.path
  Condition: start condition failed at Tue 2021-08-24 16:53:06 BST; 58s ago
             └─ ConditionPathExists=!/tmp/nopenopenope was not met
    Process: 115 ExecStart=/bin/touch /tmp/nopenopenope (code=exited, status=0/SUCCESS)
   Main PID: 115 (code=exited, status=0/SUCCESS)
        CPU: 2ms

Aug 24 16:53:06 image systemd[1]: Starting Test 123...
Aug 24 16:53:06 image systemd[1]: test123.service: Deactivated successfully.
Aug 24 16:53:06 image systemd[1]: Finished Test 123.
Aug 24 16:53:06 image systemd[1]: Condition check resulted in Test 123 being skipped.
Aug 24 16:53:06 image systemd[1]: Condition check resulted in Test 123 being skipped.
Aug 24 16:53:06 image systemd[1]: Condition check resulted in Test 123 being skipped.
Aug 24 16:53:06 image systemd[1]: Condition check resulted in Test 123 being skipped.
Aug 24 16:53:06 image systemd[1]: test123.service: Start request repeated too quickly.
Aug 24 16:53:06 image systemd[1]: test123.service: Failed with result 'start-limit-hit'.
Aug 24 16:53:06 image systemd[1]: Failed to start Test 123.
```

### CODE REVIEW

**Comment by bluca** [comment]
Any chance for an integration test, so that we don't risk regressing?

**Comment by DaanDeMeyer** [comment]
Had to fix one existing test where the error changed because the start limit was being hit earlier than the trigger limit and added a new test based on the reproducer from #17433.

**Review by bluca — APPROVED** [review]
lgtm

File: src/core/unit.c [hunk 1]
```diff
@@ -1857,6 +1857,13 @@ int unit_start(Unit *u) {
 
         assert(u);
 
+        /* Check start rate limiting early so that failure conditions don't cause us to enter a busy loop. */
+        if (UNIT_VTABLE(u)->test_start_limit) {
+                int r = UNIT_VTABLE(u)->test_start_limit(u);
```
Comment (poettering) [inline src/core/unit.c:1862]: doesn't matter much, but as a rule, "int r" gets this special privilege to always be defined on the outermost block (i.e. on function scope), since it's our primary variable for storing function returns. for all other variables we have the rule of declaring them with minimal scope, but "int r" gets a special privilege to have maximum scope always
