### PR TITLE
rereadpt: always update kernel partition tables from userspace in an incremental fashion

### LINKED ISSUE #38672: Creating the root partition with repart fails to boot
### systemd version the issue has been seen with

257.6

### Used distribution

NixOS Unstable

### Linux kernel version used

6.12.42

### CPU architectures issue was seen on

x86_64

### Component

systemd-repart

### Expected behaviour you didn't see

It should be possible to create and format an empty root partition during initrd with systemd-repart, and boot using a pre-existing `/usr` partition.

### Unexpected behaviour you saw

The root partition is created and formatted, altering the partition table. Repart / `libfdisk` intelligently trigger an `add` event for the partition with `BLKPG_ADD_PARTITION`. However, when the file descriptor for the disk containing the partition is closed, `udev` receives an inotify event thanks to `IN_CLOSE_WRITE` and calls `synthesize_change` to redundantly trigger the kernel to reread the partition table. This causes a `remove` event to be emitted for the partition, immediately followed by an `add` event.

The emission of an `add` event causes systemd to proceed with successive units, like `systemd-fsck-root.service` or `sysroot.mount` if checking is disabled. But the immediately following `remove` event prevents such units from being started at all.

```
systemd[1]: systemd-fsck-root.service: Bound to unit dev-disk-by\x2dpartlabel-created\x2droot.device, but unit isn't active.
systemd[1]: Dependency failed for File System Check on /dev/disk/by-partlabel/created-root.
systemd[1]: Dependency failed for /sysroot.
```

Note that because the service fails to even start, `systemd-fsck` does not get a chance to open the device, so `BLKRRPART` does not return `-EBUSY`

### Steps to reproduce the problem

With `root=LABEL=created-root`, and a repart definition contained either in the initrd or in a separate `/usr` partition like this:

```
# 10-root.conf
[Partition]
Type=root
Label=created-root
Format=ext4
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by poettering**
Let's address #38672 comprehensively: let's avoid BLKRRPART as much as we can, and always do careful userspace controlled, incremental updates to the kernel partition tables.

This simply iterates through blkid's partition parsing, and turns it into a BLKPG ioctls, adding, updating, removing partitions as necessary, suppressing unnecessary changes. This has the major benefit that the call becomes truly idempotent: if nothing changed then nothing is removed/readed, like BLKRRPART is doing it.

This then ports over all code currently doing partition refreshing, specifcially: udev, repart, and homed.

Fixes: #38672

### CODE REVIEW

File: src/shared/rereadpt.h [hunk 1]
```diff
@@ -0,0 +1,12 @@
+/* SPDX-License-Identifier: LGPL-2.1-or-later */
+#pragma once
+
+#include "sd-device.h"
```
Comment (daandemeyer) [inline src/shared/rereadpt.h]: `#include shared-forward.h`

File: src/shared/rereadpt.c [hunk 2]
```diff
@@ -0,0 +1,353 @@
...
+        if (!streq_ptr(pttype, "gpt")) {
+                log_device_debug(dev, "Didn't find a GPT partition table on '%s', falling back to BLKRRPART.", p);
+                return fallback_ioctl(dev, fd);
+        }
+
+        blkid_partlist pl;
+        errno = 0;
+        pl = sym_blkid_probe_get_partitions(b);
+        if (!pl)
+                return log_device_debug_errno(dev, errno_or_else(EIO), "Unable read partition table of '%s': %m", p);
```
Comment (daandemeyer) [inline src/shared/rereadpt.c]: "Unable to"

File: src/shared/reread-partition-table.c [hunk 3]
```diff
@@ -0,0 +1,353 @@
...
+        (void) sym_blkid_probe_set_partitions_flags(b, BLKID_PARTS_ENTRY_DETAILS);
+
+        errno = 0;
+        r = sym_blkid_do_safeprobe(b);
+        if (r == _BLKID_SAFEPROBE_ERROR)
+                return log_device_debug_errno(dev, errno_or_else(EIO), "Unable to probe for partition table of '%s': %m", p);
+        if (IN_SET(r, _BLKID_SAFEPROBE_AMBIGUOUS, _BLKID_SAFEPROBE_NOT_FOUND)) {
+                log_device_debug(dev, "Didn't find partition table on block device '%s', falling back to BLKRRPART.", p);
+                return fallback_ioctl(dev, fd);
+        }
```
Comment (daandemeyer) [inline src/shared/reread-partition-table.c:310]: Does this handle different sector sizes?

File: src/shared/rereadpt.c [hunk 4]
```diff
@@ -0,0 +1,353 @@
...
+        n_partitions = sym_blkid_partlist_numof_partitions(pl);
+        if (n_partitions < 0)
+                return log_device_debug_errno(dev, errno_or_else(EIO), "Unable to acquire number of entries in partition table of '%s': %m", p);
+
+        _cleanup_(sd_device_enumerator_unrefp) sd_device_enumerator *e = NULL;
+        r = partition_enumerator_new(dev, &e);
+        if (r < 0)
+                return log_device_debug_errno(dev, r, "Failed to enumerate kernel partitions: %m");
+
+        log_debug("Updating/adding kernel partitions...");
```
Comment (daandemeyer) [inline src/shared/rereadpt.c]: Adding the device path here makes this log message a lot more useful, ditto elsewhere

File: src/shared/rereadpt.c [hunk 5]
```diff
@@ -0,0 +1,353 @@
...
+        int nr = sym_blkid_partition_get_partno(pp);
+        if (nr < 0)
+                return log_debug_errno(errno_or_else(errno), "Failed to read partition number of partition: %m");
+
+        log_debug("Processing partition %i...", nr);
+
+        errno = 0;
+        blkid_loff_t start = sym_blkid_partition_get_start(pp);
+        if (start < 0)
+                return log_debug_errno(errno_or_else(errno), "Failed to read partition start offset of partition %i: %m", nr);
```
Comment (daandemeyer) [inline src/shared/rereadpt.c]: `errno_or_else(errno)`?

File: src/shared/rereadpt.c [hunk 6]
```diff
@@ -0,0 +1,353 @@
...
+
+        if (FLAGS_SET(flags, REREADPT_FORCE_UEVENT)) {
+                /* No change? Then trigger an event manually if we were told to */
+                r = sd_device_trigger(dev, SD_DEVICE_CHANGE);
+                if (r < 0)
+                        return log_device_debug_errno(dev, r, "Failed to issue 'change' uevent on device '%s': %m", p);
+        }
+        return 0;
+#else
+        return fallback_ioctl(dev, fd);
```
Comment (daandemeyer) [inline src/shared/rereadpt.c]: Please log here that we don't have blkid

File: src/shared/reread-partition-table.c [hunk 7]
```diff
@@ -0,0 +1,353 @@
...
+        if (changed)
+                return 1;
+
+        if (FLAGS_SET(flags, REREADPT_FORCE_UEVENT)) {
+                /* No change? Then trigger an event manually if we were told to */
+                r = sd_device_trigger(dev, SD_DEVICE_CHANGE);
+                if (r < 0)
+                        return log_device_debug_errno(dev, r, "Failed to issue 'change' uevent on device '%s': %m", p);
+        }
+        return 0;
```
Comment (daandemeyer) [inline src/shared/reread-partition-table.c:370]: Newline before the return please

**Review by daandemeyer — CHANGES_REQUESTED** [review]
The unit test should really be an integration test.

Feel free to compile and install an executable that makes implementing the integration test easier, but shelling out to sfdisk, needing root and needing loop devices are all indications this should be an integration test rather than a unit test.

**Comment by poettering** [comment]
> Feel free to compile and install an executable that makes implementing the integration test easier, but shelling out to sfdisk, needing root and needing loop devices are all indications this should be an integration test rather than a unit test.

I have no idea how to take BSD locks on a loopback block device while I allocate it from the shell, and then keep it while I do my thing?

File: src/shared/reread-partition-table.c (hunk 3 above)
Comment (poettering) [reply src/shared/reread-partition-table.c:310]: blkid by default gets the sector size from the kernel. which is the right thing here, because the kernel does the same when reading its partition table, and we want this to be in sync.

File: src/test/test-rereadpt.c [hunk 8]
```diff
@@ -0,0 +1,162 @@
...
+#include "process-util.h"
+#include "rereadpt.h"
+#include "tests.h"
+#include "tmpfile-util.h"
+#include "virt.h"
+
+static void sfdisk(const char *sfdisk_path, LoopDevice *loop, const char *definition) {
+        int r;
+
+        assert(sfdisk);
```
Comment (yuwata) [inline src/test/test-rereadpt.c]: sfdisk_path

File: src/shared/blockdev-util.c [hunk 9]
```diff
@@ -414,6 +414,13 @@ int blockdev_partscan_enabled(sd_device *dev) {
 
         assert(dev);
 
+        const char *subsys;
+        r = sd_device_get_subsystem(dev, &subsys);
+        if (r < 0)
+                return r;
+        if (!streq_ptr(subsys, "block"))
```
Comment (yuwata) [inline src/shared/blockdev-util.c]: `device_in_subsystem(dev, "block")`

File: src/shared/rereadpt.c [hunk 10]
```diff
@@ -0,0 +1,355 @@
...
+#include <sys/file.h>
+#include <sys/ioctl.h>
+
+#include "sd-device.h"
+
+#include "alloc-util.h"
+#include "blkid-util.h"
+#include "blockdev-util.h"
+#include "device-util.h"
+#include "device-private.h"
```
Comment (yuwata) [inline src/shared/rereadpt.c]: Please sort.

File: src/shared/rereadpt.c [hunk 11]
```diff
@@ -0,0 +1,355 @@
...
+#if HAVE_BLKID
+static int process_partition(
+                sd_device *d,
+                int fd,
+                blkid_partition pp,
+                sd_device_enumerator *e,
+                Set **partnos,
+                RereadPartitionTableFlags flags,
+                bool *changed) {
+        int r;
```
Comment (yuwata) [inline src/shared/rereadpt.c:81]: Not a matter, but we usually insert an empty line after function arguments.

File: src/shared/rereadpt.c [hunk 12]
```diff
@@ -0,0 +1,355 @@
...
+
+        errno = 0;
+        blkid_loff_t size = sym_blkid_partition_get_size(pp);
+        if (size < 0)
+                return log_debug_errno(errno_or_else(EIO), "Failed to read partition size of partition %i: %m", nr);
+        assert((uint64_t) size < UINT64_MAX / 512U);
+
+        for (sd_device *partition = sd_device_enumerator_get_device_first(e);
+             partition;
+             partition = sd_device_enumerator_get_device_next(e)) {
```
Comment (yuwata) [inline src/shared/rereadpt.c]: FOREACH_DEVICE(e, partition)

File: src/shared/rereadpt.c [hunk 13]
```diff
@@ -0,0 +1,355 @@
...
+
+                unsigned nr_kernel;
+                r = device_get_property_uint(partition, "PARTN", &nr_kernel);
```
Comment (yuwata) [inline src/shared/rereadpt.c]: Why not to generate device node path to the partition and acquire sd_device object from that? The loop for the enumerator looks not necessary.
```
partition_node_of(node, nr, &path);
sd_device_new_from_devname(&partition, path);
```

File: src/shared/rereadpt.c [hunk 14]
```diff
@@ -0,0 +1,355 @@
...
+
+                const char *devname;
+                r = sd_device_get_devname(partition, &devname);
+                if (r < 0)
+                        return log_device_debug_errno(partition, r, "Failed to get name of partition: %m");
+
+                uint64_t start_kernel;
+                r = device_get_sysattr_u64(partition, "start", &start_kernel);
+                if (r < 0)
+                        return log_device_debug_errno(partition, r, "Failed to get start of kernel partition '%s': %m", devname);
```
Comment (yuwata) [inline src/shared/rereadpt.c]: `kernel partition` sounds slightly spurious to me...

File: src/shared/rereadpt.c [hunk 15]
```diff
@@ -0,0 +1,355 @@
...
+                r = device_get_sysattr_u64(partition, "size", &size_kernel);
+                if (r < 0)
+                        return log_device_debug_errno(partition, r, "Failed to get size of kernel partition '%s': %m", devname);
+
+                if (start_kernel == (uint64_t) start && size_kernel == (uint64_t) size) {
+                        log_device_debug(partition, "Kernel partition '%s' already matches partition table, not modifying.", devname);
+
+                        if (FLAGS_SET(flags, REREADPT_FORCE_UEVENT)) {
+                                if (!*changed) {
+                                        /* Make sure to synthesize a change even on the main device, before we issue the first one on a partition device */
```
Comment (yuwata) [inline src/shared/rereadpt.c]: Maybe `a change even on` -> `a change event on` ??

File: src/shared/rereadpt.c [hunk 16]
```diff
@@ -0,0 +1,355 @@
...
+                                        r = sd_device_trigger(d, SD_DEVICE_CHANGE);
+                                        if (r < 0)
+                                                return log_device_debug_errno(d, r, "Failed to issue 'change' uevent on device '%s': %m", node);
+
+                                        log_device_debug(partition, "Successfully issued 'change' uevent on device '%s'.", node);
```
Comment (yuwata) [inline src/shared/rereadpt.c]: `partition` -> `d`

File: src/shared/rereadpt.c [hunk 17]
```diff
@@ -0,0 +1,355 @@
...
+
+                        /* And now add it */
+                        log_device_debug(partition, "Successfully removed kernel partition '%s' in order to recreate it.", devname);
+                        break;
+                }
+
+                /* If the start offsize doesn't change we can just resize the partition */
+                log_device_debug(partition, "Resizing partition %i...", nr);
+
+                r = block_device_resize_partition(fd, nr, (uint64_t) start * 512U, (uint64_t) size * 512U);
```
Comment (yuwata) [inline src/shared/rereadpt.c]: Hmm, is this safe even when the new size invades the next partition?

File: src/shared/reread-partition-table.c [hunk 18]
```diff
@@ -0,0 +1,355 @@
...
+        }
+
+        log_device_debug(d, "Adding partition %i...", nr);
+
+        _cleanup_free_ char *subnode = NULL;
+        r = partition_node_of(node, nr, &subnode);
+        if (r < 0)
+                return log_device_debug_errno(d, r, "Failed to determine partition device: %m");
+
+        r = block_device_add_partition(fd, subnode, nr, (uint64_t) start * 512U, (uint64_t) size * 512U);
```
Comment (yuwata) [inline src/shared/reread-partition-table.c:193]: Also here. Is it safe even when the new partition does not fit the free space that the kernel currently expected?

File: src/shared/rereadpt.c [hunk 19]
```diff
@@ -0,0 +1,355 @@
...
+        assert(e);
+        assert(changed);
+
+        /* Removes all partitions of the specified device that we didn't find in the partition table (as
+         * listed in the specified Set object) */
+
+        int ret = 0;
+        for (sd_device *partition = sd_device_enumerator_get_device_first(e);
+             partition;
+             partition = sd_device_enumerator_get_device_next(e)) {
```
Comment (yuwata) [inline src/shared/rereadpt.c]: FOREACH_DEVICE()

File: src/shared/rereadpt.c [hunk 20]
```diff
@@ -0,0 +1,355 @@
...
+                unsigned nr;
+                r = device_get_property_uint(partition, "PARTN", &nr);
+                if (r < 0)
+                        return log_device_debug_errno(partition, r, "Failed to read partition number property: %m");
+                if (set_contains(partnos, UINT_TO_PTR(nr))) {
+                        log_device_debug(partition, "Found kernel partition %u in partition table, leaving around.", nr);
+                        continue;
+                }
+
+                log_device_debug(d, "Kernel knows partition %u which we didn't find, removing.", nr);
```
Comment (yuwata) [inline src/shared/rereadpt.c]: `d` -> `partition` ?

File: src/shared/rereadpt.c [hunk 21]
```diff
@@ -0,0 +1,355 @@
...
+
+                r = block_device_remove_partition(fd, devname, (int) nr);
+                if (r < 0)
+                        RET_GATHER(ret, log_device_debug_errno(d, r, "Failed to remove kernel partition '%s' that vanished from partition table: %m", devname));
+                else  {
+                        log_device_debug(d, "Removed partition %u from kernel.", nr);
```
Comment (yuwata) [inline src/shared/rereadpt.c]: Also here, `d` -> `partition` ?

File: src/udev/udev-watch.c [hunk 22]
```diff
@@ -166,29 +167,11 @@ static int synthesize_change_all(sd_device *dev) {
 
         assert(dev);
 
-        r = blockdev_reread_partition_table(dev);
+        r = rereadpt(dev, REREADPT_FORCE_UEVENT);
         if (r < 0)
-                log_device_debug_errno(dev, r, "Failed to re-read partition table, ignoring: %m");
-        bool part_table_read = r >= 0;
+                return log_device_debug_errno(dev, r, "Failed to re-read partition table, ignoring: %m");
```
Comment (yuwata) [inline src/udev/udev-watch.c]: rereadpt() logs in debug level. hence I think it is OK to remove the logging here.

Also, it is ok to drop synthesize_change_all() and call rereadpt() just after safe_fork() below.

File: src/udev/udev-watch.c [hunk 23]
```diff
@@ -166,29 +167,11 @@ static int synthesize_change_all(sd_device *dev) {
 
         assert(dev);
 
-        r = blockdev_reread_partition_table(dev);
+        r = rereadpt(dev, REREADPT_FORCE_UEVENT);
```
Comment (yuwata) [inline src/udev/udev-watch.c]: Please lock the device. This may be triggered multiple times simultaneously. I do not think this is safe when called in parallel.

**Review by yuwata — CHANGES_REQUESTED** [review]

**Comment by yuwata** [comment]
BTW, we usually not abbreviate names. I prefer `rereadpt` -> `reread_partition_table`.

File: src/shared/rereadpt.c (hunk 21 above)
Comment (poettering) [reply src/shared/rereadpt.c]: It felt weird passing a device here that has ceased to exist by then.

File: src/shared/reread-partition-table.c (hunk 18 above)
Comment (poettering) [reply src/shared/reread-partition-table.c:193]: The kernel actually doesn't care at all, partitions configured via BLPKG can overlap as much as they want.

Of course it's a bad idea to rewrite partition tables so that they contained overlapped partitions or collide with partitions currently in use, but that's not the place to enforce this, that's the repartitioning step in repart or so, and in fact it does enforce that (it never moves or shrinks partitions, only grows them, and adds them after all).

File: src/shared/rereadpt.c (hunk 17 above)
Comment (poettering) [reply src/shared/rereadpt.c]: see below

File: src/test/test-reread-partition-table.c [hunk 24]
```diff
@@ -0,0 +1,162 @@
...
+
+        ASSERT_OK_ZERO_ERRNO(access(p, F_OK));
+        ASSERT_ERROR(rereadpt_fd(loop->fd, /* flags= */ 0), EBUSY);
+        ASSERT_OK_ZERO_ERRNO(access(p, F_OK));
+
+        safe_close(pfd);
+
+        ASSERT_OK(rereadpt_fd(loop->fd, /* flags= */ 0));
+
+        pfd = open(p, O_RDONLY|O_CLOEXEC|O_NONBLOCK|O_NOCTTY);
```
[the remark this answers is not in the document]
Comment (poettering) [reply src/test/test-reread-partition-table.c:139]: this is a test

File: src/test/test-reread-partition-table.c [hunk 25]
```diff
@@ -0,0 +1,162 @@
...
+               loop,
+               "label: gpt\n"
+               "start=, size=20M, type=EBD0A0A2-B9E5-4433-87C0-68B6B72699C7\n");
+
+        ASSERT_ERROR_ERRNO(access(p, F_OK), ENOENT);
+        ASSERT_OK(rereadpt_fd(loop->fd, /* flags= */ 0));
+
+        ASSERT_OK_ZERO_ERRNO(access(p, F_OK));
+
+        _cleanup_close_ int pfd = open(p, O_RDONLY|O_CLOEXEC|O_NONBLOCK|O_NOCTTY);
```
[the remark this answers is not in the document]
Comment (poettering) [reply src/test/test-reread-partition-table.c:93]: this is a test

File: src/shared/reread-partition-table.c (hunk 18 above)
Comment (yuwata) [reply src/shared/reread-partition-table.c:193]: Interesting.

File: src/shared/rereadpt.h [hunk 26]
```diff
@@ -0,0 +1,14 @@
...
```
Comment (yuwata) [inline src/shared/rereadpt.h]: sd-device.h -> sd-forward.h

File: src/shared/reread-partition-table.c
Comment (yuwata) [inline src/shared/reread-partition-table.c:1]: I'd like to also rename the file to reread-partition-table.c or at least reread-pt.c

File: src/test/test-reread-partition-table.c
Comment (yuwata) [inline src/test/test-reread-partition-table.c:1]: Could you also add test case for overlapped partitions?

File: src/shared/rereadpt.c [hunk 27]
```diff
@@ -0,0 +1,346 @@
...
+                lock_fd = fd_reopen(fd, O_RDONLY|O_CLOEXEC|O_NOCTTY);
+                if (lock_fd < 0)
+                        return log_device_debug_errno(dev, r, "Failed top open lock fd for block device '%s': %m", p);
+
+                if (flock(lock_fd, LOCK_EX|LOCK_NB) < 0)
+                        return log_device_debug_errno(dev, errno, "Failed to take BSD lock on block device '%s': %m", p);
+        }
+
+        _cleanup_(blkid_free_probep) blkid_probe b = NULL;
+        b = sym_blkid_new_probe();
```
Comment (yuwata) [inline src/shared/rereadpt.c]: Not a matter, but merge the lines?

File: src/shared/rereadpt.c [hunk 28]
```diff
@@ -0,0 +1,346 @@
...
+        const char *pttype = NULL;
+        (void) sym_blkid_probe_lookup_value(b, "PTTYPE", &pttype, NULL);
+        if (!streq_ptr(pttype, "gpt")) {
+                log_device_debug(dev, "Didn't find a GPT partition table on '%s', falling back to BLKRRPART.", p);
+                return fallback_ioctl(dev, fd);
+        }
+
+        blkid_partlist pl;
+        errno = 0;
+        pl = sym_blkid_probe_get_partitions(b);
```
Comment (yuwata) [inline src/shared/rereadpt.c]: Also here.
```c
blkid_partlist pl = sym_blkid_probe_get_partitions(b);
```

File: src/shared/rereadpt.c [hunk 29]
```diff
@@ -0,0 +1,346 @@
...
+        if (!pl)
+                return log_device_debug_errno(dev, errno_or_else(EIO), "Unable to read partition table of '%s': %m", p);
+
+        int n_partitions;
+        errno = 0;
+        n_partitions = sym_blkid_partlist_numof_partitions(pl);
```
Comment (yuwata) [inline src/shared/rereadpt.c]: Also here.

File: src/shared/rereadpt.c [hunk 30]
```diff
@@ -0,0 +1,346 @@
...
+
+        log_device_debug(dev, "Updating/adding kernel partition devices...");
+
+        _cleanup_(set_freep) Set *found_partnos = NULL;
+        bool changed = false;
+        int ret = 0;
+        for (int i = 0; i < n_partitions; i++) {
+                blkid_partition pp;
+                errno = 0;
+                pp = sym_blkid_partlist_get_partition(pl, i);
```
Comment (yuwata) [inline src/shared/rereadpt.c]: And here.

File: src/shared/reread-partition-table.c [hunk 31]
```diff
@@ -0,0 +1,346 @@
...
+                        log_device_debug(partition, "Successfully resized kernel partition device '%s' to match partition table.", subnode);
+                        *changed = true;
+                        return 1;
+                }
+
+                /* If the start offset changed we need to remove and recreate the partition */
+                log_device_debug(partition, "Removing and recreating partition %i...", nr);
+
+                /* NB: when logging below we use the parent device now, after all the partition device ceased existing by now, most likely. */
+                partition = sd_device_unref(partition);
```
Comment (yuwata) [inline src/shared/reread-partition-table.c:181]: Thank you for the comment, but unref() here is not necessary.

**Review by yuwata — APPROVED** [review]
LGTM. Several cosmetic comments. Feel free to ignore.

**Comment by daandemeyer** [comment]
You can keep the tests as is, you're right that doing flock in bash would be a pain.

File: src/shared/reread-partition-table.c (hunk 31 above)
Comment (poettering) [reply src/shared/reread-partition-table.c:181]: but i like it, it clarifies the thinking here I think, no?

Comment (yuwata) [reply src/shared/reread-partition-table.c:181]: Not a matter. Feel free to keep it.

File: src/udev/udevadm-lock.c [hunk 32]
```diff
@@ -184,7 +184,8 @@ static int lock_device(
         struct stat st;
         int r;
 
-        fd = open(path, O_RDONLY|O_CLOEXEC|O_NONBLOCK|O_NOCTTY);
+        /* We open in O_WRONLY mode here, to trigger a rescan in udev once we are done */
+        fd = open(path, O_WRONLY|O_CLOEXEC|O_NONBLOCK|O_NOCTTY);
```
Comment (yuwata) [inline src/udev/udevadm-lock.c:188]: Hm, indeed.

**Review by yuwata — APPROVED** [review]
The last commit should be backported to stable.

**Comment by ElvishJerricco** [comment]
Is there any chance this whole thing could be backported to stable? This bug has been a thorn in our (NixOS's) side for a while now and it's one of the challenges for us switching our default initrd implementation to the systemd-based one.

**Comment by keszybz** [comment]
Backport of last commit queued for v258.2. I didn't include the whole series because it's a lot of code. Maybe we can backport it later if there are no regressions reported.

**Comment by yuwata** [comment]
If you'd like to backport the whole patches, then 
- 9011b1cfc03bf85c7e1d66a1e489ee3c71fa90a9,
- #39596,
- #39604,
- #39646,
- 84f3f30e72b10ffacab09da6336090ea9f0c049d (optional),

should be backported.

**Comment by keszybz** [comment]
Too big and too complicated to backport to v258.
