### PR TITLE
sd-journal: close journal files that were deleted by journald before we've setup inotify watch

### LINKED ISSUE #14695: Lazy setup of inotify_fd in sd-journal may cause clients to leak file descriptors
**systemd version the issue has been seen with**
* git master

**Used distribution**
 * Fedora

**Expected behaviour you didn't see**
* No deleted files referenced by the sd-journal client after calling `sd_journal_process()`

**Unexpected behaviour you saw**
* Files that were deleted by the journald server are still opened by the sd-journal client after calling `sd_journal_process()`. This is because files were opened by the client and deleted by the server before we've setup inotify monitor.

**Steps to reproduce the problem**
```python
#!/usr/bin/python3

from systemd import journal
from os import listdir,readlink
from subprocess import run

def list_fds():
    for fd in listdir("/proc/self/fd"):
        try:
            print(f"    {fd} -> {readlink('/proc/self/fd/' + fd)}")
        except FileNotFoundError as e:
            pass
devnull = open("/dev/null", "w")

print("Rotate journal 3 times")
for i in range(3):
    run(["journalctl", "--rotate"], stdout=devnull, stderr=devnull)

print("Open journal")
r = journal.Reader()

print("List fds")
list_fds()

print("Delete some journal files")
run(["journalctl", "--vacuum-files", "1"], stdout=devnull, stderr=devnull)

print("Process journal events")
r.wait(0)

print("List fds")
list_fds()
```

Example output of the reproducer script
```
Rotate journal 3 times
Open journal
List fds
    0 -> /dev/pts/0
    1 -> /dev/pts/0
    2 -> /dev/pts/0
    3 -> /dev/null
    6 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/system@3d354d8051214925b8d43f50e63d7307-000000000011eb29-00059d4928d6c3d6.journal
    7 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/system.journal
    8 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/user-1000@aaabf79080ca4edcafc88708e607b702-000000000011ebb7-00059d497ac0ed84.journal
    9 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/system@3d354d8051214925b8d43f50e63d7307-000000000011eca1-00059d49fd720acb.journal
    10 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/user-1001.journal
    11 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/system@3d354d8051214925b8d43f50e63d7307-000000000011eca2-00059d49fd728a75.journal
    12 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/user-1001@cbd42769b3e547cba69261355d9ba2f8-000000000011ec84-00059d49c900efb9.journal
    13 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/user-1000.journal
Delete some journal files
Process journal events
List fds
    0 -> /dev/pts/0
    1 -> /dev/pts/0
    2 -> /dev/pts/0
    3 -> /dev/null
    6 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/system@3d354d8051214925b8d43f50e63d7307-000000000011eb29-00059d4928d6c3d6.journal (deleted)
    7 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/system.journal
    8 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/user-1000@aaabf79080ca4edcafc88708e607b702-000000000011ebb7-00059d497ac0ed84.journal (deleted)
    9 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/system@3d354d8051214925b8d43f50e63d7307-000000000011eca1-00059d49fd720acb.journal (deleted)
    10 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/user-1001.journal
    11 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/system@3d354d8051214925b8d43f50e63d7307-000000000011eca2-00059d49fd728a75.journal (deleted)
    12 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/user-1001@cbd42769b3e547cba69261355d9ba2f8-000000000011ec84-00059d49c900efb9.journal (deleted)
    13 -> /var/log/journal/56161deef0f24959be056aa81810ce4f/user-1000.journal
```

### PR DESCRIPTION
**Pull request by msekletar**
Fixes #14695

### CODE REVIEW

File: src/journal/sd-journal.c [hunk 1]
```diff
@@ -2661,13 +2661,26 @@ _public_ int sd_journal_wait(sd_journal *j, uint64_t timeout_usec) {
...
                 r = sd_journal_get_fd(j);
                 if (r < 0)
                         return r;
 
+                /* Server might have done some vacuuming while we weren't watching.
+                   Get rid of the deleted files now so they don't stay around indefinitely. */
+                ORDERED_HASHMAP_FOREACH(f, j->files, i) {
+                        r = journal_file_fstat(f);
+                        if (r < 0)
+                                log_debug_errno(r,"Failed to fstat() journal file '%s' : %m", f->path);
```
Comment (keszybz) [inline src/journal/sd-journal.c:2678]: If the fstat failed, it seems wrong to continue and look that the stats.

Comment (msekletar) [reply src/journal/sd-journal.c:2678]: Well we did the `fstat()` when we've loaded the file initially. I think that looking at possibly outdated data (and having a minuscule risk of TOCTOU) is better than skipping the file altogether.

Comment (cdown) [reply src/journal/sd-journal.c:2678]: We shouldn't do this. The Linux VFS layer is inherently racy, and it's entirely possible nlink can become >0 again later. Probably that won't happen a *lot* later unless we hit some pathological case where we blocked in kernel space for a while, but even that is possible.

If we can't stat it, we should err on the side of caution and do nothing.

Comment (msekletar) [reply src/journal/sd-journal.c:2678]: Ok, let's just skip the file then.

**Comment by msekletar** [comment]
I've just updated my branch. PTAL

File: src/journal/sd-journal.c [hunk 2]
```diff
@@ -2661,13 +2661,28 @@ _public_ int sd_journal_wait(sd_journal *j, uint64_t timeout_usec) {
...
+                /* Server might have done some vacuuming while we weren't watching.
+                   Get rid of the deleted files now so they don't stay around indefinitely. */
+                ORDERED_HASHMAP_FOREACH(f, j->files, i) {
+                        r = journal_file_fstat(f);
+                        if (r < 0) {
+                                log_debug_errno(r,"Failed to fstat() journal file '%s' : %m", f->path);
+                                continue;
+                        }
+
+                        if (f->last_stat.st_nlink <= 0)
```
Comment (cdown) [inline src/journal/sd-journal.c:2682]: nit: nlink_t is unsigned, so it can't be less than 0.

Comment (msekletar) [reply src/journal/sd-journal.c:2682]: We have such check in one more place. I will send followup PR to fix it in both places.

Comment (msekletar) [reply src/journal/sd-journal.c:2682]: Also strictly speaking POSIX doesn't specify singleness for nlink_t.

```
nlink_t, uid_t, gid_t, and id_t shall be integer types.
```

Comment (cdown) [reply src/journal/sd-journal.c:2682]: systemd runs on Linux, which definitely does have an opinion, not an abstract POSIX operating system. :-)

Either way, it doesn't really matter.

Comment (keszybz) [reply src/journal/sd-journal.c:2682]: @poettering likes to write checks this way. The justification is that if the type is changed to signed later on, the check will still DTRT. Personally, I'd prefer == 0. But since both versions are equivalent, we should treat it as a matter of style, up to the author.

Comment (msekletar) [reply src/journal/sd-journal.c:2682]: `<=` is already used in one more place so let's just keep it then (considering that @poettering also has slight preference for this style).
