### PR TITLE
systemd.dnssd does not handle local requests

### LINKED ISSUE #32990: systemd.dnssd does not handle local requests
### systemd version the issue has been seen with

master commit a3680a4

### Used distribution

ubuntu 24.04

### Linux kernel version used

6.8.0-31-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

running ISC/bind9 dig on localhost fails but works on another host

- hpz25.local IP is 192.168.0.12

```
$ hostname
ubun4.local
$ dig -p 5353 hpz25.local @192.168.0.12

; <<>> DiG 9.18.24-0ubuntu5-Ubuntu <<>> -p 5353 hpz25.local @192.168.0.12
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55708
;; flags: qr aa; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;hpz25.local.                   IN      A

;; ANSWER SECTION:
hpz25.local.            120     IN      A       192.168.0.12

;; Query time: 0 msec
;; SERVER: 192.168.0.12#5353(192.168.0.12) (UDP)
;; WHEN: Thu May 23 12:26:53 CEST 2024
;; MSG SIZE  rcvd: 45
```

### Unexpected behaviour you saw

```
$ hostname
hpz25.local
$ dig -p 5353 hpz25.local @192.168.0.12
;; communications error to 192.168.0.12#5353: timed out
;; communications error to 192.168.0.12#5353: timed out
;; communications error to 192.168.0.12#5353: timed out

; <<>> DiG 9.18.24-0ubuntu5-Ubuntu <<>> -p 5353 hpz25.local @192.168.0.12
;; global options: +cmd
;; no servers could be reached
```

### Steps to reproduce the problem

1. enable MulticastDNS=yes on hpz25.local resolved & networkd
2. cat /etc/systemd/dnssd/ssh.dnssd 
```
[Service]
Name=%H
Type=_ssh._tcp
Port=22
```
3. sudo systemctl restart systemd-resolved.service

The same isssue appears using other mDNS client utilities on the local host:
- mquery from https://github.com/troglobit/mdnsd
- libjdns-dev/noble 2.0.3-3.1build3 ubuntu 24.04

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by agreppin**
fixes #32990

### CODE REVIEW

File: src/resolve/resolved-mdns.c [hunk 1]
```diff
@@ -386,8 +386,11 @@ static int on_mdns_packet(sd_event_source *s, int fd, uint32_t revents, void *us
         if (r <= 0)
                 return r;
 
-        if (manager_packet_from_local_address(m, p))
-                return 0;
+        if (manager_packet_from_local_address(m, p)) {
+                /* if it's not a reply, handle this request */
+                if (dns_packet_validate_reply(p) > 0)
+                        return 0;
+        }
```
Comment (poettering) [inline src/resolve/resolved-mdns.c]: so, this check is protection against accidentally answering our own packets, and getting confused by that and into possible reply loops. hence the check should really be kept in some form, but made tighter: we want to allow local stuff that is done via the classic unicast query format, but ignore it when doing mcast queries. that would allow your questions through that you were using in the reported issue.

to make such a check we just need to check the source UDP port nr, as per RFC 6762 Section 5.1:

```c
/* Refuse traffic from the local host, to avoid query loops. However, allow legacy mDNS unicast queries through anyway (we never send those ourselves, hence no risk). i.e. check for the source port nr. */
if (p->sender_port == MDNS_PORT && manager_packet_from_local_address(m, p)) 
        return 0;
```

Comment (agreppin) [reply src/resolve/resolved-mdns.c]: the proposed change only works for request coming from `dig`, but alas not from `mquery`  where the sender port is indeed 5353... I agree that `mquery` needs to be fixed.

**Review by bluca — APPROVED** [review]

File: src/resolve/resolved-mdns.c [hunk 2]
```diff
@@ -386,7 +386,10 @@ static int on_mdns_packet(sd_event_source *s, int fd, uint32_t revents, void *us
         if (r <= 0)
                 return r;
 
-        if (manager_packet_from_local_address(m, p))
+        /* Refuse traffic from the local host, to avoid query loops. However, allow legacy mDNS
+         * unicast queries through anyway (we never send those ourselves, hence no risk).
```
Comment (evverx) [inline src/resolve/resolved-mdns.c:390]: This comment is misleading because it allows sending responses and populating the cache along the way too. Now it's possible to for example send send DNAMEs pointing `local` to some weird stuff from the same machine
```sh
Jul 21 12:27:03 H systemd-resolved[205360]: Received mdns UDP packet of size 36, ifindex=3, ttl=64, fragsize=0, sender=192.168.56.4, destination=192.168.56.4
Jul 21 12:27:03 H systemd-resolved[205360]: Got mDNS reply packet
Jul 21 12:27:03 H systemd-resolved[205360]: Added positive unauthenticated non-confidential shared cache entry for local IN DNAME 120s on eth1/INET/192.168.56.4
```
and get something like
```
resolvectl query ho.local
ho.local: resolve call failed: CNAME loop detected, or CNAME resolving disabled on 'ho.local.local.local.local.local.local.local.local.local.local.local.local.local.local.local.local.local'
```
It's an interesting feature I have to say.

Comment (evverx) [reply src/resolve/resolved-mdns.c:390]: @poettering is it possible to add CODEOWNERs to prevent these sloppy reviews and merges?

File: src/resolve/resolved-mdns.c (hunk 1 above)
Comment (evverx) [reply src/resolve/resolved-mdns.c]: `mquery` supports known-answer suppression and things like that so it's not a legacy unicast querier. It needs fixing in some places like https://github.com/troglobit/mdnsd/issues/79 but the source port is correct. `resolved` should probably support mDNS queriers like this properly.

Comment (evverx) [reply src/resolve/resolved-mdns.c]: Speaking of mDNS queriers resolved can't resolve its own local services either: https://github.com/systemd/systemd/pull/22532 and it seems that it should be properly supported too.

**Comment by evverx** [comment]
It's apparently being backported to the stable branch. I'll add the "merged-but-needs-fixing" label so as not to forget about this.
