### PR TITLE
network: RADV: set default timeouts

### LINKED ISSUE #20850: systemd-networkd/resolved is not using the dns server pushed via router advertisement
Hey,

I'm not sure if I do something wrong. I'm on Arch. My router announces a DNS server in the Router Advertisement packets:

2021-09-27-112652_screenshot

But it is not used/not showing up in the `networkctl` output.

```
kmille@linbox:~ networkctl status wlp3s0   
● 3: wlp3s0                                                                    
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/wlp3s0.network
                          Type: wlan
                         State: routable (configured)
                  Online state: online                                         
                          Path: pci-0000:03:00.0
                        Driver: iwlwifi
                        Vendor: Intel Corporation
                         Model: Wireless 8260 (Dual Band Wireless-AC 8260)
                    HW Address: redacted
                           MTU: 1500 (min: 256, max: 2304)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
             WiFi access point: redacted
          Queue Length (Tx/Rx): 1/1
                       Address: 192.168.10.xx (DHCP4 via 192.168.10.1)
                                      ipv6: redacted
                       Gateway: 192.168.10.1
                                       ipv6: redacted
                           DNS: 192.168.10.1          <---------------- I miss it here
             Activation Policy: up
           Required For Online: yes
               DHCP4 Client ID: IAID:0xf8038963/DUID
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab118aa23f1d4d7ed7580000

```
I don't see errors in the log. This is my config:

```
kmille@linbox:network cat wlp3s0.network 
[Match]
Name=wlp3s0

[Network]
DHCP=yes
IPv6PrivacyExtensions=yes
IPv6AcceptRA=1

[DHCP]
RouteMetric=20
#UseMTU=true

#[IPv6AcceptRA]
#UseDNS=true
```

**systemd version the issue has been seen with**
```
kmille@linbox:~ systemctl --version                            
systemd 249 (249.4-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Linux kernel version used** (`uname -a`)
`Linux box 5.14.7-arch1-1 #1 SMP PREEMPT Wed, 22 Sep 2021 21:35:11 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
x86

### PR DESCRIPTION
**Pull request by yuwata**
Closes #20850.

~~Please review #20226 and #20778 at first.~~

### CODE REVIEW

File: src/network/networkd-radv.c [hunk 1]
```diff
@@ -678,24 +671,94 @@ int radv_add_prefix(
...
-        RoutePrefix *prefix;
+        RoutePrefix *p;
 
         assert(network);
 
-        HASHMAP_FOREACH(prefix, network->route_prefixes_by_section)
-                if (section_is_invalid(prefix->section))
-                        route_prefix_free(prefix);
+        HASHMAP_FOREACH(p, network->route_prefixes_by_section)
+                if (route_prefix_section_verify(p))
```
Comment (keszybz) [inline src/network/networkd-radv.c]: `< 0` !

Comment (yuwata) [reply src/network/networkd-radv.c]: Ouch! Fixed.

**Comment by keszybz** [comment]
focal-amd64: TEST-50-DISSECT:                    FAIL     (314 s)
mkosi/ci (opensuse) — installation failed, seems to be some fuckup with the way that the kernel is installed
build test/clang 11 — #20986

Looks all unrelated, let's merge.
