### PR TITLE
resolved: do not disable mdns/llmnr globally if it's enabled on any link

### LINKED ISSUE #36078: mDNS/LLMNR (resolver and responder) in resolved stop working after a while
### systemd version the issue has been seen with

257.2

### Used distribution

Arch

### Linux kernel version used

6.11

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

Given a bridge of veth devices with networkd configuration: 

<details>
<summary>20-lan-bridge.network</summary>

```
# /etc/systemd/network/20-lan-bridge.network
[Match]
Name=br-lan

[Link]
RequiredForOnline=no-carrier

[Network]
ConfigureWithoutCarrier=yes
IgnoreCarrierLoss=yes

[Address]
Address=10.132.143.1/24
DuplicateAddressDetection=none

[Address]
Address=fd00:be:fcf:11::1/64
DuplicateAddressDetection=none

[Network]
DHCP=no
LinkLocalAddressing=ipv6
LLDP=yes
EmitLLDP=customer-bridge
IPv6AcceptRA=no
# IPv6SendRA=yes # handled by dnsmasq
# DHCPServer=yes # handled by dnsmasq
IPv6SendRA=no
DHCPServer=no

IPv4Forwarding=yes
IPv6Forwarding=yes
IPMasquerade=both

LLMNR=yes
MulticastDNS=yes

DNS=10.132.143.1
DNS=fd00:be:fcf:11::1
Domains=~i.intelfx.name
Domains=~10.in-addr.arpa
Domains=~f.c.f.0.e.b.0.0.0.0.d.f.ip6.arpa
```
</details>

And a nspawn container on said bridge with (mostly default) networkd configuration:

<details>
<summary>80-container-host0.network</summary>

```
# /etc/systemd/network/80-container-host0.network
[Match]
Kind=veth
Name=host0
Virtualization=container

[Network]
DHCP=yes
LinkLocalAddressing=yes
LLDP=yes
EmitLLDP=customer-bridge
UseDomains=yes

MulticastDNS=yes
LLMNR=yes

[DHCP]
UseTimezone=yes
```
</details>

- mDNS and LLMNR resolution queries (`resolvectl query otherhost.` and `resolvectl query otherhost.local`) to other hosts are expected to work indefinitely after mDNS/LLMNR is enabled on an interface via networkd configuration
- mDNS and LLMNR responses to queries from other hosts (both via resolved and Avahi) are expected to work indefinitely after mDNS/LLMNR is enabled on an interface via networkd configuration

### Unexpected behavior you saw

1. Both mDNS and LLMNR resolver and responder stop working after some time, i.e.:
   ```console
   $ resolvectl query otherhost.local
   otherhost.local: resolve call failed: No appropriate name servers or networks for name found
   ```
   This happens in both directions (verified by switching one side to Avahi and retrying queries from both sides).
   The behavior persists until all instances of systemd-resolved (one or both) are restarted.

2. Even when resolution is "working" (i.e., shortly after restarting instances of systemd-resolved), sometimes it's only IPv4 resolution that works (`resolvectl query -4` succeeds and `resolvectl query -6` fails) or vice versa, randomly.

### Steps to reproduce the problem

Set up some bridges and containers as per the configuration above.

### Additional program output to the terminal or log subsystem illustrating the issue

(see above)

### LINKED ISSUE #36126: systemd-resolved and systemd-networkd fight over joining/leaving multicast groups
### systemd version the issue has been seen with

257.2-2

### Used distribution

Arch

### Linux kernel version used

6.12.10-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved, systemd-networkd

### Expected behaviour you didn't see

On boot, systemd-resolved mdns socket should be a member of the 224.0.0.251 multicast group on wlan0, and this should be observable from /proc:

```
$ cat /proc/net/igmp
Idx	Device    : Count Querier	Group    Users Timer	Reporter
1	lo        :     1      V3
				010000E0     1 0:00000000		0
3	innernet  :     2      V3
				010000E0     1 0:00000000		0
				6A0000E0     1 0:00000000		0
4	wlan0     :     2      V3
				FB0000E0     1 0:00000000		0
				010000E0     1 0:00000000		0
```

mDNS should work. This is the behavior with versions 256.9 and 257 (could not check 257.1).

<details>
<summary>mDNS configuration</summary>

```
Global
         Protocols: -LLMNR +mDNS +DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub
Current DNS Server: 9.9.9.9#dns.quad9.net
       DNS Servers: 9.9.9.9#dns.quad9.net 2620:fe::fe#dns.quad9.net
        DNS Domain: ~.

Link 3 (innernet)
    Current Scopes: none
         Protocols: -DefaultRoute -LLMNR +mDNS +DNSOverTLS DNSSEC=no/unsupported
     Default Route: no

Link 4 (wlan0)
    Current Scopes: DNS mDNS/IPv4 mDNS/IPv6
         Protocols: +DefaultRoute -LLMNR +mDNS +DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: xxx.xxx.xxx.xxx
       DNS Servers: xxx.xxx.xxx.xxx
     Default Route: yes
```

```
IDX LINK     TYPE      OPERATIONAL SETUP
  1 lo       loopback  carrier     unmanaged
  3 innernet bridge    no-carrier  configured
  4 wlan0    wlan      routable    unmanaged
```

On this computer, wlan0 is managed by NetworkManager.

Identical issue happens on a computer without NetworkManager, where wlan is managed, and configured with: 

```
[Match]
Name=wlan*

[Link]
Multicast=yes

[Network]
DHCP=yes
DNSSEC=no
MulticastDNS=yes
DNSDefaultRoute=no
```

</details>

### Unexpected behaviour you saw

On boot, systemd-resolved mdns socket is *not* a member of the multicast group (on wlan0):

```
$ cat /proc/net/igmp
Idx     Device    : Count Querier       Group    Users Timer    Reporter
1       lo        :     1      V3
                                010000E0     1 0:00000000               0
3       innernet  :     2      V3
                                010000E0     1 0:00000000               0
                                6A0000E0     1 0:00000000               0
4       wlan0     :     1      V3
                                010000E0     1 0:00000000               0
```

mDNS does not work on wlan0, since sent packets are not received.

### Steps to reproduce the problem

`systemctl restart systemd-resolved` fixes non-working mDNS (multicast membership restored). `systemctl restart systemd-networkd` breaks working mDNS (multicast membership lost).  System boots in the broken state.

(I captured `SYSTEMD_LOG_LEVEL=debug` logs of systemd-resolved, but various IP addresses are somewhat revealing and I would prefer not to post them publicly.)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a regression caused by 2976730a4d34749bfb7a88da341464f1834ab1c6.
Fixes #36078.
Fixes #36126.

Replaces #36153.
Replaces #36156.

### CODE REVIEW

**Comment by bluca** [comment]
The wrong commit is mentioned in the commit message. Does this cover a case that isn't covered by https://github.com/systemd/systemd/pull/36156 ?

File: src/resolve/resolved-llmnr.c [hunk 1]
```diff
@@ -9,9 +9,16 @@
...
+void manager_llmnr_stop(Manager *m, bool force) {
         assert(m);
 
+        if (!force) {
+                Link *l;
+                HASHMAP_FOREACH(l, m->links)
+                        if (link_get_llmnr_support(l) != RESOLVE_SUPPORT_NO)
+                                return;
+        }
+
```
Comment (poettering) [inline src/resolve/resolved-llmnr.c]: i don't like this pattern very much. I would have instead added a new fnction manager_llmnr_maybe_stop() that first does the loop and check and then chainloads to manager_llmnr_stop() (or doesn't).

it hink that's much nicer, and smaller probably too

**Comment by poettering** [comment]
beautiful!

thanks!

**Comment by yuwata** [comment]
> The wrong commit is mentioned in the commit message.

Thanks. Fixed.

> Does this cover a case that isn't covered by #36156 ?

Right. Your PR only disables mdns/llmnr on reload, but this may also disable them on any network event, i.e. sd-network, sd-netlink.

**Review by bluca — APPROVED** [review]
> Right. Your PR only disables mdns/llmnr on reload, but this may also disable them on any network event, i.e. sd-network, sd-netlink.

Ok, makes sense, I was focused on the reload case, looks good then

**Comment by yuwata** [comment]
Second commit is added, which does the same on DBus method call. PTAL.

**Comment by yuwata** [comment]
@intelfx Thank you testing the patch. Hopefully this will be backported to next v257 point release.
