### PR TITLE
networkd: bump MTU to 1280 for interfaces which have IPv6 enabled

### LINKED ISSUE #3046: networkd: Could not bring up interface when MTU < 1280
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with; Used distribution

systemd 229-3 from Arch Linux
### Expected behaviour you didn't see & Unexpected behaviour you saw

With MTU set less than 1280:
- systemd-networkd did not bring up IPIP interfaces
- systemd-networkd brought up TAP interfaces with warning
### Steps to reproduce the problem
- Create a .network profile that has nothing to do with IPv6 (the kernel does support IPv6)

```
[Match]
Name=test0
[Link]
MTUBytes=1279
[Network]
DHCP=no
LinkLocalAddressing=no
[Address]
Address=10.0.0.1/24
```
- Create a TAP interface manually: `ip tuntap add dev test0 mode tap`
- systemd-networkd brought up the interface and set the MTU to 1279, but networkd and kernel produced warning messages

```
kernel: tun: Universal TUN/TAP device driver, 1.6
kernel: tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
systemd-networkd[439]: test0: Flags change: +MULTICAST +BROADCAST
systemd-networkd[439]: test0: Link 3 added
systemd-networkd[439]: test0: link pending udev initialization...
systemd-networkd[439]: test0: Saved original MTU: 1500
systemd-udevd[459]: Could not generate persistent MAC address for test0: No such file or directory
systemd-networkd[439]: test0: udev initialized link
systemd-networkd[439]: test0: Link state is up-to-date
systemd-networkd[439]: test0: found matching network '/etc/systemd/network/test.network'
systemd-networkd[439]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=11 reply_cookie=0 error
systemd-networkd[439]: test0: Bringing link up
systemd-networkd[439]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=12 reply_cookie=0 error
systemd-networkd[439]: test0: Setting addresses
systemd-networkd[439]: test0: Flags change: +UP
systemd-networkd[439]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=13 reply_cookie=0 error
systemd-networkd[439]: test0: Could not bring up interface: Address family not supported by protocol
systemd-networkd[439]: test0: Updating address: 10.0.0.1/24 (valid forever)
systemd-networkd[439]: test0: Addresses set
systemd-networkd[439]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=14 reply_cookie=0 error
kernel: IPv6: ADDRCONF(NETDEV_UP): test0: link is not ready
kernel: A link change request failed with some changes committed already. Interface test0 may have been left with an inconsistent configuration, please check.
```
- Or, create an IPIP interface with `ip tunnel add test0 mode ipip remote <X> local <Y>`
- systemd-networkd did not bring up the interface

```
kernel: ipip: IPv4 over IPv4 tunneling driver
systemd-networkd[439]: test0: MAC address not found for new device, continuing without
systemd-networkd[439]: test0: Flags change: +NOARP
systemd-networkd[439]: test0: Link 5 added
systemd-networkd[439]: test0: link pending udev initialization...
systemd-networkd[439]: test0: udev initialized link
systemd-networkd[439]: test0: Link state is up-to-date
systemd-networkd[439]: test0: found matching network '/etc/systemd/network/test.network'
systemd-networkd[439]: test0: Cannot configure IPv6 privacy extension for interface: No such file or directory
systemd-networkd[439]: test0: Cannot disable kernel IPv6 accept_ra for interface: No such file or directory
systemd-networkd[439]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_35 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=17 reply_cookie=0 error
systemd-networkd[439]: test0: Bringing link up
systemd-networkd[439]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_35 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=18 reply_cookie=0 error
systemd-networkd[439]: test0: Setting addresses
systemd-networkd[439]: test0: Could not bring up interface: Address family not supported by protocol
systemd-networkd[439]: test0: Updating address: 10.0.0.1/24 (valid forever)
systemd-networkd[439]: test0: Addresses set
systemd-networkd[439]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_35 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=19 reply_cookie=0 error
systemd-networkd[439]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=20 reply_cookie=0 error
```

### PR DESCRIPTION
**Pull request by ssahani**
IPv6 protocol requires a minimum MTU of 1280 bytes on the interface
hence this is not getting set.
This fixes #3046.

Introduce helper link_ipv6_enabled() to figure out whether IPV6 is
enabled.
Introduce network_has_static_ipv6_addresses() to find out if any static
ipv6 address configured.
If IPv6 is not configured on any interface that is SLAAC,
DHCPv6 and static IPv6 addresses not configured, then IPv6 will be
automatically disabled for that interface that is we write
"1" to /proc/sys/net/ipv6/conf//disable_ipv6.

### CODE REVIEW

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -99,6 +99,21 @@ static bool link_ipv6ll_enabled(Link *link) {
...
 }
 
+static bool link_ipv6_enabled(Link *link) {
+        assert(link);
+
+        if (!socket_ipv6_is_supported())
+                return false;
+
+        if (link_dhcp6_enabled(link) && link_ipv6ll_enabled(link))
+                return true;
```
Comment (keszybz) [inline src/network/networkd-link.c]: You need both? It should be `||`.

File: src/network/networkd-link.c [hunk 2]
```diff
@@ -218,6 +233,31 @@ static IPv6PrivacyExtensions link_ipv6_privacy_extensions(Link *link) {
...
+        if (link->flags & IFF_LOOPBACK)
+                return 0;
+
+        disabled = !link_ipv6_enabled(link);
+
+        p = strjoina("/proc/sys/net/ipv6/conf/", link->ifname, "/disable_ipv6");
+
+        r = write_string_file(p, one_zero(disabled), WRITE_STRING_FILE_VERIFY_ON_FAILURE);
+        if (r < 0)
+                log_link_warning_errno(link, r, "Cannot set IPv6 for interface: %m");
```
Comment (keszybz) [inline src/network/networkd-link.c]: What about the message?

Comment (ssahani) [inline src/network/networkd-link.c]: It's getting failed should be as it is.

File: man/systemd.network.xml [hunk 3]
```diff
@@ -210,6 +212,15 @@
           <para>Identity Association Identifier for the interface, a 32-bit unsigned integer.</para>
         </listitem>
       </varlistentry>
+      <varlistentry>
+      <listitem>
+        <para>Note that if any interface where no static IPv6 address is configured, and
+        neither DHCPv6 nor IPv6LL is enabled, shall be considered an IPv6 less interface.
+        IPv6 will be automatically disabled for that interface by writing "1" to
+        <filename>/proc/sys/net/ipv6/conf/<replaceable>ifname</replaceable>/disable_ipv6.</filename>
```
Comment (keszybz) [inline man/systemd.network.xml:220]: "Note that an interface without any static IPv6 addresses configured, and neither DHCPv6 nor IPv6LL enabled, shall be considered to have no IPv6 support. IPv6 will be automatically disabled for that interface by writing "1" to ..."

File: src/network/networkd-link.c (hunk 1 above)
Comment (ssahani) [inline src/network/networkd-link.c]: Yes both.

File: src/network/networkd-link.c (hunk 2 above)
Comment (keszybz) [inline src/network/networkd-link.c]: Please see https://github.com/systemd/systemd/pull/3067#discussion_r60411958

**Comment by keszybz** [comment]
BTW., you can force push. Github doesn't lose the old comments like it used to.

File: src/network/networkd-link.c (hunk 1 above)
Comment (keszybz) [inline src/network/networkd-link.c]: Errr, no. If I have DHCP=ipv6 LinkLocalAddressing=ipv4 I'm pretty sure this should return true.

Comment (ssahani) [inline src/network/networkd-link.c]: Well @poettering  suggested it If I got that right 

"return false if socket_ipv6_is_supported() returns false, or when both of link_dhcp6_enabled() + link_ipv6ll_enabled() return false and if there's no static ipv6 address configured either."
https://github.com/systemd/systemd/pull/3058

Comment (keszybz) [inline src/network/networkd-link.c]: https://en.wikipedia.org/wiki/De_Morgan's_laws :)

@poettering's comment translates to:

```
 if (!socket_ipv6_is_supported())
                return false;
return link_dhcp6_enabled(link) || 
          link_ipv6ll_enabled(link) ||
          network_has_static_ipv6_addresses(link->network);
```

Comment (ssahani) [inline src/network/networkd-link.c]: silly me thanks :) I thought + as '&&'

**Comment by poettering** [comment]
lgtm, if the CI agrees too.
