### PR TITLE
sd-journal: fix generic_array_bisect()

### LINKED ISSUE #30210: Systemd 255~rc3 Journal failure ' Assertion 'left < right' failed ' when debugging enabled (sleep state changes)
### systemd version the issue has been seen with

systemd-255~rc3-1.fc40.src.rpm

### Used distribution

Fedora Rawhide (F40)

### Linux kernel version used

6.7.0amdfw-rc2+

### CPU architectures issue was seen on

x86_64

### Component

systemd, systemd-journald

### Expected behaviour you didn't see

Journal should continue to function as normal (regression from 255-rc2).

### Unexpected behaviour you saw

after upgraded package from rawhide of 255-rc3 was pushed on the 25/11/2023 several debugging scripts now fail. Appears to be related to enabling several debug outputs at once. systemd fails to return state correctly to the debug script and then keeps temporary debug output enabled and spams the journal.

### Steps to reproduce the problem

Was conducted using the following debug script which is designed to test s2idle state on amd platforms 

https://gitlab.freedesktop.org/drm/amd/-/blob/master/scripts/amd_s2idle.py

This script works fine preceding the -rc3 updates and now segfaults with the newer version of systemd. A separate bug was filled initially on the tracker here:

https://gitlab.freedesktop.org/drm/amd/-/issues/3012

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Nov 27 10:44:09 emiemi kernel: GPIO 8 is actRoot directory /var/log/journal removed.
Root directory /run/log/journal removed.
Directory /var/log/journal/0abbe6bede8c469781f868961fdc7aae removed.
mmap cache statistics: 142755 category cache hit, 8240 window list hit, 109 miss
ive: 0x18141b00
Nov 27 10:44:10 emiemi kernel: GPIO 8 is active: 0x18141b00
Nov 27 10:44:11 emiemi kernel: GPIO 5 is active: 0x10141b00
Nov 27 10:44:12 emiemi kernel: GPIO 5 is active: 0x10141b00
Nov 27 10:44:13 emiemi kernel: GPIO 5 is active: 0x10141b00
Nov 27 10:44:14 emiemi kernel: GPIO 5 is active: 0x10141b00
Nov 27 10:44:15 emiemi kernel: GPIO 5 is active: 0x10141b00
Nov 27 10:44:16 emiemi kernel: GPIO 5 is active: 0x10141b00
Nov 27 10:44:17 emiemi kernel: GPIO 5 is active: 0x10141b00
aenertia@emiemi:~/Downloads$
```

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes #30210.

### CODE REVIEW

File: src/libsystemd/sd-journal/journal-file.c [hunk 1]
```diff
@@ -2917,11 +2918,13 @@ static int generic_array_bisect_step(
                 if (i == 0)
                         return TEST_GOTO_PREVIOUS;
 
-                /* Otherwise, cutting the array short. So, here we limit the number of elements we will see
-                 * in this array, and set the right boundary to the last possibly non-corrupted object. */
+                /* Otherwise, cutting the array short, and restart the bisection. So, here we limit the
+                 * number of elements we will see in this array, and set the right boundary to the last
+                 * possibly non-corrupted object. */
                 *m = i;
+                *left = 0;
```
Comment (keszybz) [inline src/libsystemd/sd-journal/journal-file.c]: Hmm, but do we need to set this all the way to 0? If we already checked earlier that `*left` is at some value, we could just set `*left` to `MIN(*left, *right)`?

File: src/libsystemd/sd-journal/journal-file.c [hunk 2]
```diff
@@ -2879,6 +2879,7 @@ enum {
                              * should exist in an earlier position. */
         TEST_GOTO_NEXT,     /* No matching object exists in this array and earlier arrays, go to the next array. */
         TEST_GOTO_PREVIOUS, /* No matching object exists in this array and later arrays, go to the previous array. */
+        TEST_CORRUPTED,     /* Found a corrupted entry. */
```
Comment (keszybz) [inline src/libsystemd/sd-journal/journal-file.c]: There's a long comment a the beginning of `generic_array_bisect_step` that should be expanded with the documentation of this new flag.

**Comment by yuwata** [comment]
Updated. PTAL.

**Comment by bluca** [comment]
Seems unrelated, but also new, @mrc0mmand 

```
[  995.664934] testsuite-25.sh[44]: + machinectl import-tar /var/tmp/scratch.tar.gz scratch2
[  995.669356] machinectl[109]: Enqueued transfer job 8. Press C-c to continue download in background.
[  995.672955] machinectl[109]: Importing '/var/tmp/scratch.tar.gz', saving as 'scratch2'.
[  995.673609] machinectl[109]: Imported 0%.
[  995.676068] machinectl[109]: tar: ./adirectory: Cannot change mode to rwxr-xr-x: Operation not permitted
[  995.682532] machinectl[109]: tar: Exiting with failure status due to previous errors
[  995.682649] systemd-importd[53]: (transfer8) tar failed with exit status 2.
```

**Comment by mrc0mmand** [comment]
> Seems unrelated, but also new, @mrc0mmand
> 
> ```
> [  995.664934] testsuite-25.sh[44]: + machinectl import-tar /var/tmp/scratch.tar.gz scratch2
> [  995.669356] machinectl[109]: Enqueued transfer job 8. Press C-c to continue download in background.
> [  995.672955] machinectl[109]: Importing '/var/tmp/scratch.tar.gz', saving as 'scratch2'.
> [  995.673609] machinectl[109]: Imported 0%.
> [  995.676068] machinectl[109]: tar: ./adirectory: Cannot change mode to rwxr-xr-x: Operation not permitted
> [  995.682532] machinectl[109]: tar: Exiting with failure status due to previous errors
> [  995.682649] systemd-importd[53]: (transfer8) tar failed with exit status 2.
> ```

Yeah, it's new, and I've seen it in other PRs as well, but so far I haven't been able to reproduce it locally.

**Comment by yuwata** [comment]
Moved several more cleanups to #30260. This patch set should be enough to fix #30210.

File: src/libsystemd/sd-journal/journal-file.c [hunk 3]
```diff
@@ -3000,24 +3000,16 @@ static int generic_array_bisect(
         a = first;
 
         ci = ordered_hashmap_get(f->chain_cache, &first);
-        if (ci && n > ci->total && ci->begin != 0) {
-                /* Ah, we have iterated this bisection array chain previously! Let's see if we can skip ahead
-                 * in the chain, as far as the last time. But we can't jump backwards in the chain, so let's
-                 * check that first. */
+        if (ci && n > ci->total && ci->begin != 0 &&
+            test_object(f, ci->begin, needle) == TEST_LEFT) {
```
Comment (daandemeyer) [inline src/libsystemd/sd-journal/journal-file.c]: Isn't it better to just ignore the corruption errors (`EADDRNOTAVAIL`, `EBADMSG`) instead of all errors? Also, shouldn't we at least debug log about the errors we're ignoring?

File: src/libsystemd/sd-journal/journal-file.c [hunk 4]
```diff
@@ -3071,6 +3081,16 @@ static int generic_array_bisect(
...
                         for (;;) {
                                 if (left == right) {
+                                        if (m != m_original && direction == DIRECTION_DOWN) {
+                                                /* We found corrupted entries, and the final index may not be tested yet. */
+                                                r = generic_array_bisect_step(f, array, left, needle, test_object, direction, &m, &left, &right);
+                                                if (r < 0)
+                                                        return r;
+                                                if (IN_SET(r, TEST_GOTO_PREVIOUS, TEST_GOTO_NEXT))
+                                                        return 0; /* The entry does not pass the test. */
+                                                assert(left == right);
```
Comment (daandemeyer) [inline src/libsystemd/sd-journal/journal-file.c:3111]: Should we assert `r == TEST_FOUND` here?

File: src/libsystemd/sd-journal/journal-file.c [hunk 5]
```diff
@@ -3071,6 +3081,16 @@ static int generic_array_bisect(
 
                         for (;;) {
                                 if (left == right) {
+                                        if (m != m_original && direction == DIRECTION_DOWN) {
```
Comment (daandemeyer) [inline src/libsystemd/sd-journal/journal-file.c:3103]: Why only do this logic if we're going in the down direction? Doesn't this apply regardless of the direction we're going in?

File: src/libsystemd/sd-journal/journal-file.c [hunk 6]
```diff
@@ -3071,6 +3081,16 @@ static int generic_array_bisect(
...
+                                                /* We found corrupted entries, and the final index may not be tested yet. */
```
Comment (daandemeyer) [inline src/libsystemd/sd-journal/journal-file.c]: "We found one or more entries in `generic_array_bisect_step()`, which means `right` has been modified but we haven't found a matching object yet so if `left == right`, we still have to check the final object to see if it actually matches" ?

File: src/libsystemd/sd-journal/journal-file.c [hunk 7]
```diff
@@ -3083,6 +3103,8 @@ static int generic_array_bisect(
                                         return r;
                                 if (r == TEST_GOTO_PREVIOUS)
                                         goto previous;
+                                if (r == TEST_GOTO_NEXT)
+                                        return 0; /* We previously found corrupted entry, and the array was cutting short. */
```
Comment (daandemeyer) [inline src/libsystemd/sd-journal/journal-file.c]: "found a corrupt entry, and the array was cut short"

File: src/libsystemd/sd-journal/journal-file.c [hunk 8]
```diff
@@ -2913,9 +2913,19 @@ static int generic_array_bisect_step(
...
+                if (i == *left) {
+                        /* This happens on two situations:
+                         *
+                         * a) i == 0 (hence, *left == 0):
+                         *    The first entry in the array is corrupted, let's go back to the previous array.
+                         *
+                         * b) *right == *left or *left + 1, and we are going to downwards:
+                         *    In that case, the (i-1)-th object has been already tested in the previous call,
+                         *    which returned TEST_LEFT. See below. So, there is no matching entry in this
+                         *    array, and whole entry array chain. */
```
Comment (daandemeyer) [inline src/libsystemd/sd-journal/journal-file.c]: "in this array nor in the whole entry array chain"

File: src/libsystemd/sd-journal/journal-file.c (hunk 4 above)
Comment (yuwata) [reply src/libsystemd/sd-journal/journal-file.c:3111]: No, `generic_array_bisect_step()` never returns `TEST_FOUND`.

File: src/libsystemd/sd-journal/journal-file.c (hunk 5 above)
Comment (yuwata) [reply src/libsystemd/sd-journal/journal-file.c:3103]: As 'left' is always tested when we are going to upwards. I extended the comment in the code.

File: src/libsystemd/sd-journal/journal-file.c (hunk 4 above)
Comment (yuwata) [reply src/libsystemd/sd-journal/journal-file.c:3111]: Actually, `r == TEST_RIGHT`, in this case.

**Comment by yuwata** [comment]
@DaanDeMeyer Thank you for the review. All suggestions are applied, extended code comment to answer the above question, and fixed the example in the commit message. PTAL!

**Comment by keszybz** [comment]
LGTM.
