### PR TITLE
resolve: provide effective mDNS or LLMNR settings

### LINKED ISSUE #24863: global LLMNR=false/no ignored on per-link basis
### systemd version the issue has been seen with

systemd 251 (251.3-1~bpo11+1)

### Used distribution

debian bullseye 11

### Linux kernel version used

5.18.0-0.deb11.4-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

As per manual - the expected behavior as per resolved.conf manual is that LLMNR on a per-link basis should be enabled only if both per-link and global setting is enabled. But in practice per-link setting ignores global setting.

### Unexpected behaviour you saw

```
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (mv-vlan10)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (mv-vlan13)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 10.13.36.2
       DNS Servers: 10.13.36.2
        DNS Domain: touk.pl

Link 4 (mv-vlan17)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 5 (mv-vlan30)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 6 (mv-vlan31)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 7 (mv-vlan47)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 8 (mv-vlan250)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

LLMNR is enabled per-link despite being disabled globally, which conflicts with `Note that systemd-networkd.service(8) also maintains per-link LLMNR settings. LLMNR will be enabled on a link only if the per-link and the global setting is on.`

### Steps to reproduce the problem

Disable LLMNR in resolved.conf, restart relevant services.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
and warn if the global setting downgrades per-link mDNS or LLMNR settings.

Closes #24863.

### CODE REVIEW

File: src/shared/resolve-util.h [hunk 1]
```diff
@@ -25,10 +25,11 @@ typedef enum ResolveSupport ResolveSupport;
 typedef enum DnssecMode DnssecMode;
 typedef enum DnsOverTlsMode DnsOverTlsMode;
 
+/* Do not change the order. */
```
Comment (bluca) [inline src/shared/resolve-util.h]: please say why the order shouldn't be changed as well

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
Two more commits added at the beginning of this PR. So, I dropped the green label. PTAL.

**Review by bluca — APPROVED** [review]
