### PR TITLE
tests: allow for os-release quote variability in TEST-50-DISSECT

### LINKED ISSUE #19242: TEST-50-DISSECT: misleading /etc/os-release check
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > CentOS 8

During my attempts to migrate the CentOS CI's CentOS 7 job to CentOS 8 I've been battling with `TEST-50-DISSECT` which keeps failing *mysteriously*, even though everything seems to be in order. After some debugging the issue lies in this particular line:

https://github.com/systemd/systemd/blob/71d1e58309bb70bb2a014f33c5f9503dcbed020c/test/units/testsuite-50.sh#L35

This uses the `/etc/os-release` as a list of fixed-string patterns to match against the `systemd-dissect`'s output. However, `grep` happily returns 0 when at least one of the patterns match. This, combined with the `os-release`'s format, which uses quoted string in _some cases_, whereas `systemd-dissect` uses unquoted strings in all cases, makes the test fail even though it shouldn't.

CentOS 8:
```
# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

# systemd-dissect root/usr/share/minimal_0.raw 
      Name: minimal_0.raw
      Size: 2.6M

OS Release: NAME=CentOS Linux
            VERSION=8
            ID=centos
            ID_LIKE=rhel fedora
            VERSION_ID=8
            PLATFORM_ID=platform:el8
            PRETTY_NAME=CentOS Linux 8
            ANSI_COLOR=0;31
            CPE_NAME=cpe:/o:centos:centos:8
            HOME_URL=https://centos.org/
            BUG_REPORT_URL=https://bugs.centos.org/
            CENTOS_MANTISBT_PROJECT=CentOS-8
            CENTOS_MANTISBT_PROJECT_VERSION=8
            MARKER=1

RW DESIGNATOR PARTITION UUID PARTITION LABEL FSTYPE   ARCHITECTURE VERITY                           NODE PARTNO
ro root       -              -               squashfs -            external root/usr/share/minimal_0.raw -     

# systemd-dissect root/usr/share/minimal_0.raw | grep -F -f root/etc/os-release || echo "<no match>"
<no match>
```

In this case all strings in `/etc/os-release` are quoted, so there's no match with the dissected-image's output.

Fedora 33:
```
$ cat /etc/os-release 
NAME=Fedora
VERSION="33 (Thirty Three)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Thirty Three)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"

# systemd-dissect /tmp/tmp.zfwT9M/minimal_0.raw | grep -F -f /etc/os-release
 OS Release: NAME=Fedora
             ID=fedora
             VERSION_ID=33
             PRETTY_NAME=Fedora 33 (Thirty Three)
             LOGO=fedora-logo-icon
             REDHAT_BUGZILLA_PRODUCT_VERSION=33
             REDHAT_SUPPORT_PRODUCT_VERSION=33
```

In this case the grep matches the unquoted fields (and `PRETTY_NAME`, because it's matched by `NAME=Fedora`).

I suspect the image check will need to use a slightly different approach to avoid this.

/cc @bluca

### PR DESCRIPTION
**Pull request by bluca**
Quoting of values differs between distros: Fedora doesn't quote the ID_
fields, but CentOS does.
Adjust the test checks to account for this.

Fixes #19242

### CODE REVIEW

File: test/units/testsuite-50.sh [hunk 1]
```diff
@@ -32,20 +32,20 @@ os_release=$(test -e /etc/os-release && echo /etc/os-release || echo /usr/lib/os
...
+systemd-dissect ${image}.raw --root-hash=${roothash} --verity-data=${image}.fooverity | grep -q -F -f <(sed 's/"//g' $os_release)
 mv ${image}.fooverity ${image}.verity
 mv ${image}.foohash ${image}.roothash
 
 mkdir -p ${image_dir}/mount ${image_dir}/mount2
 systemd-dissect --mount ${image}.raw ${image_dir}/mount
-cat ${image_dir}/mount/usr/lib/os-release | grep -q -F -f $os_release
-cat ${image_dir}/mount/etc/os-release | grep -q -F -f $os_release
+cat ${image_dir}/mount/usr/lib/os-release | grep -q -F -f <(sed 's/"//g' $os_release)
+cat ${image_dir}/mount/etc/os-release | grep -q -F -f <(sed 's/"//g' $os_release)
```
Comment (mrc0mmand) [inline test/units/testsuite-50.sh]: I guess these two lines need to remain unchanged, since they check the `os-release` files directly.

File: test/units/testsuite-50.sh [hunk 2]
```diff
@@ -130,11 +130,11 @@ VERITY_UUID=$(systemd-id128 -u show $(tail -c 32 ${image}.roothash) -u | tail -n
...
 systemd-dissect --json=short --root-hash ${roothash} ${image}.gpt | grep -q '{"rw":"ro","designator":"root-verity","partition_uuid":"'$VERITY_UUID'","partition_label":"Verity Partition","fstype":"DM_verity_hash","architecture":"'$architecture'","verity":null,"node":'
 systemd-dissect --root-hash ${roothash} ${image}.gpt | grep -q -F "MARKER=1"
-systemd-dissect --root-hash ${roothash} ${image}.gpt | grep -q -F -f $os_release
+systemd-dissect --root-hash ${roothash} ${image}.gpt | grep -q -F -f <(sed 's/"//g' $os_release)
 
 systemd-dissect --root-hash ${roothash} --mount ${image}.gpt ${image_dir}/mount
-cat ${image_dir}/mount/usr/lib/os-release | grep -q -F -f $os_release
-cat ${image_dir}/mount/etc/os-release | grep -q -F -f $os_release
+cat ${image_dir}/mount/usr/lib/os-release | grep -q -F -f <(sed 's/"//g' $os_release)
+cat ${image_dir}/mount/etc/os-release | grep -q -F -f <(sed 's/"//g' $os_release)
```
Comment (mrc0mmand) [inline test/units/testsuite-50.sh]: ditto

**Review by mrc0mmand — CHANGES_REQUESTED** [review]
After manually fixing these two issues the test seems to pass on CentOS 8.

File: test/units/testsuite-50.sh (hunk 1 above)
Comment (bluca) [reply test/units/testsuite-50.sh]: updated

**Comment by mrc0mmand** [comment]
Thanks! Now it works as expected on CentOS 8 as well.

**Review by mrc0mmand — APPROVED** [review]
LGTM

**Comment by keszybz** [comment]
Looks OK.

I think something like https://github.com/systemd/systemd/pull/18649 would be a nicer solution in the long run.

**Comment by mrc0mmand** [comment]
No need to wait for Ubuntu CI, since the test is skipped there.
