### PR TITLE
core/namespace: introduce new mount mode READWRITE_IMPLICIT

### LINKED ISSUE #11276: ProtectSystem=strict disables ProtectHome=tmpfs
**systemd version the issue has been seen with**
240

**Used distribution**
Gentoo

**Expected behaviour you didn't see**
Unit with `ProtectSystem=strict` and `ProtectHome=tmpfs` should have a tmpfs mounted at `/home`.

**Unexpected behaviour you saw**
The unit has access to normal `/home`.

**Steps to reproduce the problem**
```
# systemd-run --pipe --property=ProtectHome=tmpfs stat -fc '%T' /home 
Running as unit: run-u286.service
tmpfs
# systemd-run --pipe --property=ProtectHome=tmpfs --property=ProtectSystem=strict stat -fc '%T' /home
Running as unit: run-u287.service
ext2/ext3
```

### PR DESCRIPTION
**Pull request by yuwata**
`ProtectSystem=strict` or `ProtectKernelTunable=yes` create implicit read-write mounts, but they are not overridable by `TemporaryFileSystem=`.
This makes such implicit read-write mounts use the new mount mode. So, they can be override by `TemproraryFileSystem=` now.
A typical usecase is that `ProtectSystem=strict` and `ProtectHome=tmpfs`.

Fixes #11276.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
CI is not happy so far:

```
exec-protecthome-tmpfs-vs-protectsystem-strict.service: Executing: /bin/sh -x -c 'test "$(stat -fc %T /home)" = "tmpfs"'
Got message type=signal sender=:1.1 destination=n/a path=/org/freedesktop/systemd1/agent interface=org.freedesktop.systemd1.Agent member=Released cookie=424 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=51 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.14 path=n/a interface=n/a member=n/a cookie=52 reply_cookie=51 signature=u error-name=n/a error-message=n/a
Got cgroup empty notification for: /system.slice/testsuite.service/13c2d86e27fb22f5/exec-privatetmp-no.service
++ stat -fc %T /home
+ test ext2/ext3 = tmpfs
Received SIGCHLD from PID 2650 (sh).
Child 2650 (sh) died (code=exited, status=1/FAILURE)
```

**Comment by yuwata** [comment]
Updated. I hope the CIs will be green.

File: src/core/namespace.c [hunk 1]
```diff
@@ -181,6 +182,24 @@ static const MountEntry protect_system_strict_table[] = {
...
+        [PRIVATE_TMP] = "private-tmp",
+        [PRIVATE_DEV] = "private-dev",
+        [BIND_DEV] = "bind-dev",
+        [EMPTY_DIR] = "empty",
+        [SYSFS] = "sysfs",
+        [PROCFS] = "procfs",
+        [READONLY] = "read-only",
+        [READWRITE] = "read-write",
+        [TMPFS] = "tmpfs",
+        [READWRITE_IMPLICIT] = "rw-implicit",
```
Comment (keszybz) [inline src/core/namespace.c]: Would be nicer to align the rvalues.

File: src/core/namespace.c [hunk 2]
```diff
@@ -516,7 +535,7 @@ static void drop_nop(MountEntry *m, size_t *n) {
 
                         /* We found it, let's see if it's the same mode, if so, we can drop this entry */
                         if (found && p->mode == f->mode) {
-                                log_debug("%s is redundant by %s", mount_entry_path(f), mount_entry_path(p));
+                                log_debug("%s (%s) is redundant by %s (%s)", mount_entry_path(f), mount_mode_to_string(f->mode), mount_entry_path(p), mount_mode_to_string(p->mode));
```
Comment (keszybz) [inline src/core/namespace.c]: "is *made* redundant"

**Comment by poettering** [comment]
Looks great. Would be great to fix the issues @keszybz pointed out, looks good to merge then. (sorry for hte late review, somehow i always missed this one...)

**Comment by yuwata** [comment]
Thank you for the review. I've force-pushed a revised version. PTAL.
