### PR TITLE
repart: respect `SOURCE_DATE_EPOCH` on `mkdir_p_root`

### LINKED ISSUE #32117: systemd-repart does not respect `SOURCE_DATE_EPOCH` when creating directories in the temporary local OS tree
### systemd version the issue has been seen with

255

### Used distribution

NixOS 24.05

### Linux kernel version used

6.8.2

### CPU architectures issue was seen on

x86_64

### Component

systemd-repart

### Expected behaviour you didn't see

systemd-repart should respect the [`SOURCE_DATE_EPOCH`](https://github.com/systemd/systemd/blob/1eeae735ad3d42d60f6513dea6d9ab0d2d858e82/docs/ENVIRONMENT.md?plain=1#L398) environment variable when [creating files / directories](https://github.com/systemd/systemd/blob/1eeae735ad3d42d60f6513dea6d9ab0d2d858e82/src/shared/copy.c#L1020) in the local OS tree through `xopenat_lock_full` with `O_CREAT`, as it happens here when [populating the local temporary tree](https://github.com/systemd/systemd/blob/1eeae735ad3d42d60f6513dea6d9ab0d2d858e82/src/partition/repart.c#L4859).

### Unexpected behaviour you saw

systemd-repart creates the directories / files in the temporary local OS tree with undeterministic timestamps (i.e. `atime` and `mtime`), causing irreproducible image builds.

### Steps to reproduce the problem

I've created a repository with a minimal reproduction example here:

https://github.com/msanft/systemd-repart-repro-bug

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by msanft**
This let's systemd-repart respect the `SOURCE_DATE_EPOCH` environment variable when creating directories in the local tree through `MakeDirectories` or `CopyFiles`.

To do this, it does two things:
- When a directory is created in `mkdir_p_root`, it set's timestamps (`mtime` and `atime`) for the directory that's being created. Additionally, it will fixup the `mtime` for the directory things are copied *into*, if `SOURCE_DATE_EPOCH` is set. Otherwise, times are left untouched (`UTIME_OMIT`). The fixup of the upper directory is necessary, as otherwise, when creating a directory in it, it's `mtime` would change.
- For the reason mentioned above, we also need to fixup the `mtime` of the upper directory if we copy a file into it.

The changes can be verified with https://github.com/msanft/systemd-repart-repro-bug.

Fixes #32117.

### CODE REVIEW

File: src/basic/mkdir.c [hunk 1]
```diff
@@ -204,7 +204,7 @@ int mkdir_p_safe(const char *prefix, const char *path, mode_t mode, uid_t uid, g
         return mkdir_p_internal(prefix, path, mode, uid, gid, flags, mkdirat_errno_wrapper);
 }
 
-int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes) {
+int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes, usec_t ts) {
```
Comment (YHNdnzj) [inline src/basic/mkdir.c]: Please introduce `mkdir_p_root_full` that takes the additional param, and make `mkdir_p_root` a static inline function which wraps the _full version, rather than plugging in `now()` everywhere

File: src/basic/mkdir.c [hunk 2]
```diff
@@ -248,13 +248,21 @@ int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m
...
-                        return -errno;
+        if (futimens(dfd, (const struct timespec[2]){ { .tv_nsec = UTIME_OMIT }, { .tv_nsec = ts } }) < 0) {
+                return -errno;
+        }
+
+        nfd = openat(dfd, bn, O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_NOFOLLOW);
+        if (nfd < 0)
+                return -errno;
 
+        if (futimens(nfd, (const struct timespec[2]){ { .tv_nsec = ts }, { .tv_nsec = ts } }) < 0) {
```
Comment (YHNdnzj) [inline src/basic/mkdir.c]: No brackets around single-line if-s

File: src/basic/mkdir.h [hunk 3]
```diff
@@ -1,6 +1,7 @@
 /* SPDX-License-Identifier: LGPL-2.1-or-later */
 #pragma once
 
+#include "time-util.h"
```
Comment (YHNdnzj) [inline src/basic/mkdir.h]: Please place our header below external ones, separated with newline

**Review by YHNdnzj — CHANGES_REQUESTED** [review]

**Comment by YHNdnzj** [comment]
Please read https://systemd.io/CODING_STYLE/ first

**Comment by msanft** [comment]
> Please read https://systemd.io/CODING_STYLE/ first

Apologies. I tried to familiarize with the guides, but let the one-line-ifs and the import slip through. Things should be in order with the style guide and contributing guidelines now.

Regarding the function signature compatability, I wasn't sure to do this, since `mkdir_p_root` wasn't used at a lot of places. But I now migrated to a compatibility wrapper.

File: src/basic/mkdir.h [hunk 4]
```diff
@@ -23,7 +26,10 @@ static inline int mkdir_parents(const char *path, mode_t mode) {
 int mkdir_parents_safe(const char *prefix, const char *path, mode_t mode, uid_t uid, gid_t gid, MkdirFlags flags);
 int mkdir_p(const char *path, mode_t mode);
 int mkdir_p_safe(const char *prefix, const char *path, mode_t mode, uid_t uid, gid_t gid, MkdirFlags flags);
-int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes);
+int mkdir_p_root_full(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes, usec_t ts);
+static inline int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes) {
+        return mkdir_p_root_full(root, p, uid, gid, m, subvolumes, now(CLOCK_REALTIME));
```
Comment (daandemeyer) [inline src/basic/mkdir.h]: Please pass USEC_INFINITY and don't call futimens in mkdir_p_root_full() if USEC_INFINITY is passed

File: src/basic/mkdir.h [hunk 5]
```diff
@@ -23,7 +26,10 @@ static inline int mkdir_parents(const char *path, mode_t mode) {
 int mkdir_parents_safe(const char *prefix, const char *path, mode_t mode, uid_t uid, gid_t gid, MkdirFlags flags);
 int mkdir_p(const char *path, mode_t mode);
 int mkdir_p_safe(const char *prefix, const char *path, mode_t mode, uid_t uid, gid_t gid, MkdirFlags flags);
-int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes);
+int mkdir_p_root_full(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes, usec_t ts);
+static inline int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes) {
```
Comment (daandemeyer) [inline src/basic/mkdir.h]: Please remove the subvolumes argument from this function as well and keep it only in the full one

File: src/basic/mkdir.h (hunk 4 above)
Comment (msanft) [reply src/basic/mkdir.h]: I think UTIME_OMIT would save the conditional and do the same here, right? What do you prefer?

Comment (daandemeyer) [reply src/basic/mkdir.h]: We use USEC_INFINITY everywhere else so I would do the same here to keep things consistent

**Comment by msanft** [comment]
Also, is there a guideline on using conditionals such as the following? I didn't find anything regarding that while skimming over the style guide

```c
if (ts != USEC_INFINITY && (futimens(dfd, (const struct timespec[2]){ { .tv_nsec = UTIME_OMIT }, { .tv_nsec = ts } }) < 0))
                return -errno;
```

File: src/basic/mkdir.c [hunk 6]
```diff
@@ -5,6 +5,7 @@
 #include <string.h>
 
 #include "alloc-util.h"
+#include "bits/time.h"
```
Comment (yuwata) [inline src/basic/mkdir.c]: Please do not include such header explicitly. This is anyway included `time-util.h` -> `time.h` -> `bits/time.h`.

File: src/basic/mkdir.c [hunk 7]
```diff
@@ -204,9 +206,10 @@ int mkdir_p_safe(const char *prefix, const char *path, mode_t mode, uid_t uid, g
         return mkdir_p_internal(prefix, path, mode, uid, gid, flags, mkdirat_errno_wrapper);
 }
 
-int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes) {
+int mkdir_p_root_full(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes, usec_t ts) {
```
Comment (yuwata) [inline src/basic/mkdir.c]: Not a big matter, but I'd like to place `ts` between `m` and `subvolumes`, as it is a basic attribute for directories.

File: src/basic/mkdir.c [hunk 8]
```diff
@@ -248,16 +251,18 @@ int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m
                 return r;
         }
 
-        if (uid_is_valid(uid) || gid_is_valid(gid)) {
-                _cleanup_close_ int nfd = -EBADF;
+        if (ts != USEC_INFINITY && (futimens(dfd, (const struct timespec[2]){ { .tv_nsec = UTIME_OMIT }, { .tv_nsec = ts } }) < 0))
```
Comment (yuwata) [inline src/basic/mkdir.c]: Hm? Setting `usec_t` into `tv_nsec` sounds spurious...

File: src/basic/mkdir.c [hunk 9]
```diff
@@ -248,16 +251,18 @@ int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m
...
+                return -errno;
 
-                nfd = openat(dfd, bn, O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_NOFOLLOW);
-                if (nfd < 0)
-                        return -errno;
+        nfd = openat(dfd, bn, O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_NOFOLLOW);
```
Comment (yuwata) [inline src/basic/mkdir.c:255]: This is not necessary when uid, gid, and ts are unspecified. Please conditionalize.

File: src/basic/mkdir.h [hunk 10]
```diff
@@ -1,9 +1,12 @@
 /* SPDX-License-Identifier: LGPL-2.1-or-later */
 #pragma once
 
+#include <bits/time.h>
```
Comment (yuwata) [inline src/basic/mkdir.h]: Please drop.

**Review by yuwata — CHANGES_REQUESTED** [review]

File: src/basic/mkdir.c [hunk 11]
```diff
@@ -204,10 +205,13 @@ int mkdir_p_safe(const char *prefix, const char *path, mode_t mode, uid_t uid, g
...
 }
 
-int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes) {
+int mkdir_p_root_full(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, usec_t ts, char **subvolumes) {
         _cleanup_free_ char *pp = NULL, *bn = NULL;
         _cleanup_close_ int dfd = -EBADF;
+        _cleanup_close_ int nfd = -EBADF;
         int r;
+        struct timespec dtime[2];
+        struct timespec nftime[2];
```
Comment (YHNdnzj) [inline src/basic/mkdir.c]: Please reduce the scope of these vars, i.e.  move these into the corresponding if blocks

File: src/basic/mkdir.c [hunk 12]
```diff
@@ -248,16 +252,28 @@ int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m
                 return r;
         }
 
-        if (uid_is_valid(uid) || gid_is_valid(gid)) {
-                _cleanup_close_ int nfd = -EBADF;
+        if (ts != USEC_INFINITY) {
+                timespec_store_nsec(dtime+0, UTIME_OMIT);
```
Comment (YHNdnzj) [inline src/basic/mkdir.c]: No need to use `timespec_store_nsec` for this?

File: src/basic/mkdir.c [hunk 13]
```diff
@@ -248,16 +252,28 @@ int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m
...
+        if (ts != USEC_INFINITY || uid_is_valid(uid) || gid_is_valid(gid)) {
                 nfd = openat(dfd, bn, O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_NOFOLLOW);
                 if (nfd < 0)
                         return -errno;
+        }
 
-                if (fchown(nfd, uid, gid) < 0)
+        if (ts != USEC_INFINITY) {
+                timespec_store_nsec(nftime+0, ts);
+                timespec_store_nsec(nftime+1, ts);
```
Comment (YHNdnzj) [inline src/basic/mkdir.c]: Just use one `struct timespec`, and pass `(const struct timespec[2]) { nftime, nftime }` below?

File: src/partition/repart.c [hunk 14]
```diff
@@ -4775,6 +4775,18 @@ static int make_subvolumes_set(
         return 0;
 }
 
+static usec_t epoch_or_utime_omit(void) {
```
Comment (YHNdnzj) [inline src/partition/repart.c]: Please make this change a separate commit.

**Review by YHNdnzj — CHANGES_REQUESTED** [review]

File: src/basic/mkdir.c [hunk 15]
```diff
@@ -204,10 +205,13 @@ int mkdir_p_safe(const char *prefix, const char *path, mode_t mode, uid_t uid, g
...
 }
 
-int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes) {
+int mkdir_p_root_full(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, usec_t ts, char **subvolumes) {
         _cleanup_free_ char *pp = NULL, *bn = NULL;
         _cleanup_close_ int dfd = -EBADF;
+        _cleanup_close_ int nfd = -EBADF;
         int r;
+        struct timespec dtime[2];
+        struct timespec nftime[2];
```
Comment (YHNdnzj) [inline src/basic/mkdir.c]: If you touch this, please add `assert(p)` here

File: src/basic/mkdir.c [hunk 16]
```diff
@@ -248,16 +252,28 @@ int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m
                 return r;
         }
```
Comment (YHNdnzj) [inline src/basic/mkdir.c:250]: Just return early here if `ts == USEC_INFINITY && !uid_is_valid(uid) && !gid_is_valid(gid)`? Then, move declaration of `nfd` below so that it's more obvious when it would be used.

File: src/partition/repart.c [hunk 17]
```diff
@@ -4775,6 +4775,18 @@ static int make_subvolumes_set(
...
+        uint64_t epoch;
+
+        if (secure_getenv_uint64("SOURCE_DATE_EPOCH", &epoch) >= 0) {
```
Comment (poettering) [inline src/partition/repart.c]: we nowadays prefer that any unexpected failures result in debug logs, hence maybe change to:

```
r = secure_getenv_uint64(…);
if (r >= 0) {
        …
} else if (r != -ENXIO) 
        log_debug_errno(r, "Failed to parse $SOURCE_DATE_EPOCH, ignoring: %m");
```

or so

File: src/partition/repart.c [hunk 18]
```diff
@@ -4775,6 +4775,18 @@ static int make_subvolumes_set(
         return 0;
 }
 
+static usec_t epoch_or_utime_omit(void) {
+        uint64_t epoch;
```
Comment (poettering) [inline src/partition/repart.c:4781]: so, this function is something that might be called a lot, and it returns the same thing each time. Hence, I think it should really have a cache, i.e. just add:

```c
static uint64_t cache = UINT64_MAX;

if (cache != UINT64_MAX)
        return cache;

…
```

and then initialize `cache` to what you return. you get the idea.

File: src/partition/repart.c [hunk 19]
```diff
@@ -4775,6 +4775,18 @@ static int make_subvolumes_set(
...
+
+        if (secure_getenv_uint64("SOURCE_DATE_EPOCH", &epoch) >= 0) {
+                if (epoch > UINT64_MAX / USEC_PER_SEC) /* Overflow check */
+                        return USEC_INFINITY;
+                return (usec_t) epoch * USEC_PER_SEC;
+        }
+
+        return (usec_t) UTIME_OMIT;
```
Comment (poettering) [inline src/partition/repart.c]: uh. UTIME_OMIT is a special value you assign to the second-granularity .tv_sec or the nano-second granularity .tv_nsec fields.
 

Here, we return a micro-second granularity usec_t. It feels a bit weird returning UTIME_OMIT here.

Maybe return USEC_INFINITY here instead, and make sure to convert that to UTIME_OMIT when converting from usec_t to timespec

File: src/basic/mkdir.c [hunk 20]
```diff
@@ -204,10 +205,12 @@ int mkdir_p_safe(const char *prefix, const char *path, mode_t mode, uid_t uid, g
         return mkdir_p_internal(prefix, path, mode, uid, gid, flags, mkdirat_errno_wrapper);
 }
 
-int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, char **subvolumes) {
+int mkdir_p_root_full(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m, usec_t ts, char **subvolumes) {
         _cleanup_free_ char *pp = NULL, *bn = NULL;
         _cleanup_close_ int dfd = -EBADF;
+        _cleanup_close_ int nfd = -EBADF;
```
Comment (YHNdnzj) [inline src/basic/mkdir.c]: Move this below `if (ts == USEC_INFINITY && !uid_is_valid(uid) && !gid_is_valid(gid))`?

File: src/partition/repart.c [hunk 21]
```diff
@@ -4775,6 +4775,18 @@ static int make_subvolumes_set(
...
+}
+
```
Comment (poettering) [inline src/partition/repart.c:4801]: this commit should really be merged with the one using this function.

We want "perfect" commits after all, i.e. that make sense of their own, and work on their own. But if this commit is merged alone then the compiler will be unhappy because it generally dislikes static functions that are not used by anything.

File: src/basic/mkdir.c [hunk 22]
```diff
@@ -204,10 +205,12 @@ int mkdir_p_safe(const char *prefix, const char *path, mode_t mode, uid_t uid, g
...
         int r;
+        struct timespec tspec;
```
Comment (YHNdnzj) [inline src/basic/mkdir.c]: Please move this into the `if (ts != USEC_INFINITY)` block

File: src/basic/mkdir.c [hunk 23]
```diff
@@ -248,16 +251,25 @@ int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m
                 return r;
         }
 
-        if (uid_is_valid(uid) || gid_is_valid(gid)) {
-                _cleanup_close_ int nfd = -EBADF;
+        if (ts == USEC_INFINITY && !uid_is_valid(uid) && !gid_is_valid(gid)) {
+                return 1;
+        }
```
Comment (YHNdnzj) [inline src/basic/mkdir.c]: no brackets here

Comment (poettering) [inline src/basic/mkdir.c]: no {} around single-line if blocks, as pwer coding style

File: src/basic/mkdir.c [hunk 24]
```diff
@@ -248,16 +251,25 @@ int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m
...
 
+        if (ts != USEC_INFINITY) {
                 nfd = openat(dfd, bn, O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_NOFOLLOW);
```
Comment (YHNdnzj) [inline src/basic/mkdir.c]: This should be moved out of the block, since it's used also below for `fchown`

File: src/basic/mkdir.c [hunk 25]
```diff
@@ -248,16 +251,25 @@ int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m
...
-                if (fchown(nfd, uid, gid) < 0)
+                timespec_store_nsec(&tspec, ts);
+                if (futimens(dfd, (const struct timespec[2]) { { .tv_nsec = UTIME_OMIT }, tspec }) < 0)
+                        return -errno;
+
+                if (futimens(nfd, (const struct timespec[2]) { tspec, tspec }) < 0)
                         return -errno;
         }
 
+        if ((uid_is_valid(uid) || gid_is_valid(gid)) && (fchown(nfd, uid, gid) < 0))
```
Comment (poettering) [inline src/basic/mkdir.c]: the () around the fchown call are unnecessary

File: src/basic/mkdir.c [hunk 26]
```diff
@@ -248,16 +251,25 @@ int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m
...
+                return -errno;
```
Comment (poettering) [inline src/basic/mkdir.c:271]: this will fall apart if uid or gid are specified but no timestamp, because nfd will not be initialized then.

File: src/basic/mkdir.c (hunk 20 above)
Comment (poettering) [inline src/basic/mkdir.c]: merge these two lines, please

File: src/basic/mkdir.c (hunk 22 above)
Comment (poettering) [inline src/basic/mkdir.c]: move to innermost scope

File: src/partition/repart.c [hunk 27]
```diff
@@ -4919,6 +4919,9 @@ static int do_copy_files(Context *context, Partition *p, const char *root) {
                         (void) copy_xattr(sfd, NULL, tfd, NULL, COPY_ALL_XATTRS);
                         (void) copy_access(sfd, tfd);
                         (void) copy_times(sfd, tfd, 0);
+
+                        if (futimens(pfd, (const struct timespec[2]) { { .tv_nsec = UTIME_OMIT }, { .tv_nsec = epoch_or_utime_omit() } }) < 0)
+                                return -errno;
```
Comment (poettering) [inline src/partition/repart.c:4940]: this call should not be done if the source epch stuff is not used.

**Comment by poettering** [comment]
lgtm

File: src/basic/mkdir.c [hunk 28]
```diff
@@ -15,6 +15,7 @@
 #include "path-util.h"
 #include "stat-util.h"
 #include "stdio-util.h"
+#include "time-util.h"
```
Comment (yuwata) [inline src/basic/mkdir.c]: Not a big matter, but this is not necessary, as time-util.h is included in mkdir.h.

File: src/basic/mkdir.c [hunk 29]
```diff
@@ -248,16 +249,27 @@ int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m
                 return r;
         }
 
-        if (uid_is_valid(uid) || gid_is_valid(gid)) {
-                _cleanup_close_ int nfd = -EBADF;
+        if (ts == USEC_INFINITY && !uid_is_valid(uid) && !gid_is_valid(gid))
```
Comment (yuwata) [inline src/basic/mkdir.c:251]: `!timestamp_is_set(ts)` ? I mean, we should also ignore `ts == 0`. Or does this intentionally accept `ts == 0`?

File: src/basic/mkdir.c [hunk 30]
```diff
@@ -248,16 +249,27 @@ int mkdir_p_root(const char *root, const char *p, uid_t uid, gid_t gid, mode_t m
...
+                return 1;
 
-                nfd = openat(dfd, bn, O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_NOFOLLOW);
-                if (nfd < 0)
+        _cleanup_close_ int nfd = -EBADF;
+        nfd = openat(dfd, bn, O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_NOFOLLOW);
+        if (nfd < 0)
+                return -errno;
+
+        if (ts != USEC_INFINITY) {
```
Comment (yuwata) [inline src/basic/mkdir.c:259]: `timestamp_is_set(ts)`

File: src/partition/repart.c [hunk 31]
```diff
@@ -4775,6 +4775,28 @@ static int make_subvolumes_set(
...
+        static bool cached = false;
+        uint64_t epoch;
+        int r;
+
+        if (cached)
+                return cache;
+
+        r = secure_getenv_uint64("SOURCE_DATE_EPOCH", &epoch);
+        if (r >= 0) {
+                if (!(epoch > UINT64_MAX / USEC_PER_SEC)) { /* Overflow check */
```
Comment (yuwata) [inline src/partition/repart.c]: `if (epoch <= UINT64_MAX / USEC_PER_SEC)` ??

File: src/partition/repart.c [hunk 32]
```diff
@@ -4907,6 +4930,9 @@ static int do_copy_files(Context *context, Partition *p, const char *root) {
                         (void) copy_xattr(sfd, NULL, tfd, NULL, COPY_ALL_XATTRS);
                         (void) copy_access(sfd, tfd);
                         (void) copy_times(sfd, tfd, 0);
+
+                        if (ts != USEC_INFINITY && futimens(pfd, (const struct timespec[2]) { { .tv_nsec = UTIME_OMIT }, { .tv_nsec = ts } }) < 0)
```
Comment (yuwata) [inline src/partition/repart.c]: Please use `timestamp_is_set()` and `timespec_store_nsec()`.

**Review by yuwata — CHANGES_REQUESTED** [review]

File: src/basic/mkdir.c (hunk 29 above)
Comment (msanft) [reply src/basic/mkdir.c:251]: [Many tools](https://github.com/search?q=SOURCE_DATE_EPOCH%3D0&type=code), namely NixOS, for which reproducible builds are especially important, set the variable to 0. The specification of `SOURCE_DATE_EPOCH` also permits setting it to 0, which is why I think it should be supported here, too, if you don't have any objections.

Comment (yuwata) [reply src/basic/mkdir.c:251]: But setting 0 timestamp sounds spurious for me... Or `futimens()` handles 0 gracefully?

Comment (msanft) [reply src/basic/mkdir.c:251]: Yes, `futimens()` handles it. It sets the timestamps to 0 like so: 

```
  File: /var/tmp/.#repartc9a185024a9ea6f2/somedir
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: fd00h/64768d	Inode: 6686698     Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 1001/      ms)   Gid: ( 1001/      ms)
Access: 1970-01-01 00:00:00.000000000 +0000
Modify: 1970-01-01 00:00:00.000000000 +0000
```

Comment (yuwata) [reply src/basic/mkdir.c:251]: OK. Still I want to filter out 0, but not a strong opinion. Feel free to ignore this.

File: src/partition/repart.c (hunk 32 above)
Comment (yuwata) [reply src/partition/repart.c]: But here, still `timespec_store_nsec()` should be used, I think, no?

File: src/partition/repart.c [hunk 33]
```diff
@@ -4907,6 +4931,12 @@ static int do_copy_files(Context *context, Partition *p, const char *root) {
                         (void) copy_xattr(sfd, NULL, tfd, NULL, COPY_ALL_XATTRS);
                         (void) copy_access(sfd, tfd);
                         (void) copy_times(sfd, tfd, 0);
+
+                        timespec_store_nsec(tspec + 0, UTIME_OMIT);
```
Comment (yuwata) [inline src/partition/repart.c]: Please do not use `timespec_store_nsec()` for storing special values like `UTIME_OMIT`.
Please do something similar in mkdir.c.

**Review by yuwata — CHANGES_REQUESTED** [review]

File: src/partition/repart.c [hunk 34]
```diff
@@ -4775,6 +4775,28 @@ static int make_subvolumes_set(
...
+
+        if (cached)
+                return cache;
+
+        r = secure_getenv_uint64("SOURCE_DATE_EPOCH", &epoch);
+        if (r >= 0) {
+                if (epoch <= UINT64_MAX / USEC_PER_SEC) { /* Overflow check */
+                        cached = true;
+                        return (cache = epoch * USEC_PER_SEC);
+                }
```
Comment (poettering) [inline src/partition/repart.c:4792]: doesn't matter much but i think we should probably debug log if the overflow condition.

a simple way would be to simply do `r = -ERANGE` here, and then change the `else if (r != -ENXIO)`  to just `if (r != -ENXIO)`

**Review by yuwata — APPROVED** [review]

**Review by bluca — APPROVED** [review]
