### PR TITLE
fix for logging deadlock

### LINKED ISSUE #7985: [bisected] fails to boot when `systemd.log_level=debug`
### Submission type

 - Bug report

### systemd version the issue has been seen with

I was convinced this was going to point to my mount logging change.  But actually the immediate cause was something more recent, PR #7968.

575b300b795b6765d66e0f351d80635c7d3addea is the first bad commit
commit 575b300b795b6765d66e0f351d80635c7d3addea
Author: Lennart Poettering <lennart@poettering.net>
Date:   Tue Jan 23 18:18:13 2018 +0100

    pid1: rework how we dispatch SIGCHLD and other signals
    
    This fundamentally makes one change: we never process more than one
    signal or more than one waitid() event per event loop. We'll never tight
    loop around waitid() or around read() on our signalfd instead, but
    always return to the main event loop after processing one event.
    
    By doing this we put the event priorization handling into full power
    again, as we'll always check for higher priority events before looking
    at the next signal or waitid() again.
    
    This introduces a new "defer" event source "sigchld_event". It's enabled
    as soon as we see SIGCHLD, and disabled as soon as waitid() reported no
    further children pending. It's running at a relatively high priority,
    one step higher than signal handling itself, but lower than
    /proc/self/mountinfo event handling, so that the latter always takes
    precedence.
    
    Since we want to process sd_notify() events at an even higher priority
    than SIGCHLD (as before) it is moved one priority step up, too.
    
    Fixes: #7932
    Possibly fixes: #7966

:040000 040000 76cf0a9a72c684eaa21fd5e3d401c76f6298845d 70427cf9941d04142d3b2014f145f8b5452a4637 M	src

### Used distribution

Fedora 27.  Selinux is disabled.

I made sure to install the same version of systemd to the initramfs (`dracut --force`).

### In case of bug report: Expected behaviour you didn't see

boot success

### In case of bug report: Unexpected behaviour you saw

System enters emergency mode.

**EDIT**: *processes on the critical path to mount /boot are blocked.  Trying to write to the journal, but systemd hasn't started it... because it's blocked trying to write to the journal.*

It looks like we're now always losing the race to start journald, before we've filled up the journald socket buffer.  (I wonder what reasons there are to open that race. Maybe we should be more robust - have journald open its own sockets.)

```
[  OK  ] Mounted Kernel Debug File System.
[   13.295230] kauditd_printk_skb: 48 callbacks suppressed
[   13.295232] audit: type=1130 audit(1516793691.603:59): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=kmod-static-nodes comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  OK  ] Mounted POSIX Message Queue File System.
[   ***] (7 of 8) A start job is running for Journal Service (20s / 1min 30s)[   24.063792] EXT4-fs (vda3): re-mounted. Opts: (null)
[  OK  ] Started udev Coldplug all Devices.
[   24.075129] audit: type=1130 audit(1516793702.384:60): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-udev-trigger comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
         Starting udev Wait for Complete Device Initialization...
[***   ] (3 of 8) A start job is running for…ce Initialization (30s / 3min 20s)[   34.275201] audit: type=1130 audit(1516793712.584:61): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-remount-fs comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  OK  ] Started Remount Root and Kernel File Systems.
         Starting Configure read-only root support...
         Starting Rebuild Hardware Database...
         Starting Create System Users...
[**    ] (4 of 10) A start job is running fo…ce Initialization (41s / 3min 20s)[   44.557244] audit: type=1130 audit(1516793722.867:62): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=fedora-readonly comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  OK  ] Started Configure read-only root support.
         Starting Load/Save Random Seed...
[  OK  [[   45.083112] audit: type=1130 audit(1516793723.392:63): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hwdb-update comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
0m] Started Rebuild Hardware Database.
[   ***] (9 of 9) A start job is running for…reate System Users (51s / 2min 1s)[   54.763187] audit: type=1130 audit(1516793733.073:64): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-random-seed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  OK  ] Started Load/Save Random Seed.
[  *** ] (3 of 8) A start job is running for…itialization (1min 10s / 3min 20s)[   73.890347] audit: type=1131 audit(1516793752.200:65): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=lvm2-lvmpolld comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ TIME ] Timed out waiting for device dev-ttyS0.device.
[DEPEND] Dependency failed for Serial Getty on ttyS0.
[ TIME ] Timed out waiting for device dev-di…75\x2d96f9\x2d4f63b9a04c83.device.
[DEPEND] Dependency failed for /boot.
[DEPEND] Dependency failed for Local File Systems.
[DEPEND] Dependency failed for Mark the need to relabel after reboot.
[DEPEND] Dependency failed for File System C…c55a0-75b1-4a75-96f9-4f63b9a04c83.
[FAILED] Failed to start Journal Service.
See 'systemctl status systemd-journald.service' for details.
[DEPEND] Dependency failed for Flush Journal to Persistent Storage.
[ TIME ] Timed out waiting for device dev-di…6b\x2dae10\x2da59eb6324f28.device.
[DEPEND] Dependency failed for /dev/disk/by-…a285c-7cdb-486b-ae10-a59eb6324f28.
[DEPEND] Dependency failed for Swap.
...
[  OK  ] Started Emergency Shell.
[  OK  ] Reached target Emergency Mode.
...
# systemctl --failed
  UNIT                     LOAD   ACTIVE SUB    DESCRIPTION                    
● systemd-sysctl.service   loaded failed failed Apply Kernel Variables         
● systemd-sysusers.service loaded failed failed Create System Users            

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

2 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```

uh, right.  Also, since `journald` didn't start, I think I'm missing useful system logs :-(.  `journalctl` only shows stuff from the initrd.

```
# systemctl list-jobs
JOB UNIT                                 TYPE  STATE  
225 systemd-update-utmp-runlevel.service start waiting
151 systemd-tmpfiles-setup.service       start running
254 machines.target                      start waiting
164 systemd-tmpfiles-setup-dev.service   start running
263 nss-lookup.target                    start waiting
414 systemd-journald.service             start running
161 local-fs-pre.target                  start waiting
241 network.target                       start waiting
255 var-lib-machines.mount               start waiting
141 systemd-udevd.service                start waiting
262 systemd-resolved.service             start waiting
265 auditd.service                       start waiting
278 systemd-networkd.service             start waiting
226 systemd-update-utmp.service          start waiting

14 jobs listed.
```

It doesn't look like we sent useful stuff to dmesg instead either...  at a guess all the useful messages are sitting in the journald socket.  Hum.

```
# dmesg |grep -i udev
[    1.667466] audit: type=1130 audit(1516793679.975:10): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=dracut-pre-udev comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   24.075129] audit: type=1130 audit(1516793702.384:60): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-udev-trigger comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  154.394602] audit: type=1130 audit(1516793832.704:83): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-udev-settle comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
# dmesg |grep -i rate
[    2.793437] systemd-journal: 29 output lines suppressed due to ratelimiting
[    2.820343] systemd: 256 output lines suppressed due to ratelimiting
```

### PR DESCRIPTION
**Pull request by poettering**
Fixes #7985

### CODE REVIEW

**Comment by poettering** [comment]
(@sourcejedi over on #7985 tested it and it work for him)

File: src/core/manager.c [hunk 1]
```diff
@@ -3482,29 +3485,52 @@ int manager_set_default_rlimits(Manager *m, struct rlimit **default_rlimit) {
         return 0;
 }
 
-void manager_recheck_journal(Manager *m) {
+static bool manager_journal_is_running(Manager *m) {
         Unit *u;
 
         assert(m);
 
+        /* If we are the user manager we can safely assume that the journal is up */
```
Comment (sourcejedi) [inline src/core/manager.c:3493]: I think this is unreachable because of the pid 1 check in the caller.

Comment (poettering) [reply src/core/manager.c:3493]: hmm, so yes, that's kinda true, but I wanted to keep this generically valid...

There's a slight different between checking MANAGER_IS_SYSTEM() and getpid() == 1. The former might hold when people call "systemd --system --test" or within "systemd-analyze verify --system" and various test cases like that. The latter only holds when we are actually live, as PID 1.

Now, I figured a function that answers whether journald.service/journald.socket are up should operate in those test modes, too correctly, because there's no reason to break it in that case. However, the call that actually switches around the logging subsystem only really makes sense when we *are* PID 1, as in those tests tools we actually want all output to go to stdout/stderr and not the journal.

hence i conditionalized the logging target switching on a PID 1 check, while the raw check whether journal is up checks whether we are in system scope. because the latter is only

Now, if the getpid() ==1 check holds, then MANAGER_IS_SYSTEM() always holds too, but not vice versa. hence logically you are right, we'll never call manager_journal_is_running()  unless MANAGER_IS_SYSTEM() is also true, however since the tests are slightly different still, and because manager_journal_is_running() might be useful in unrelated cases too one day (it could be as simple as including the result in manager_dump() output for debugging purposes) I opted to keep them in, even though strictly redundant.

Comment (sourcejedi) [reply src/core/manager.c:3493]: Sorry, I was not explicit enough.

My real concern is that manager_recheck_journal() will exit immediately if it is not a system instance.  Therefore, in the user manager case we will never get as far as `log_set_prohibit_ipc(true)`.

Comment (sourcejedi) [reply src/core/manager.c:3493]: ...and context.  Sorry, I see the initial `log_set_prohibit_ipc(false)` is guarded by the same check for PID 1.

Comment (poettering) [reply src/core/manager.c:3493]: yeah, the idea is that the manager won't ever touch the prohibit_ipc at all here unless we are PID 1... it won't even set it to true initially...

File: src/core/manager.c [hunk 2]
```diff
@@ -3482,29 +3485,52 @@ int manager_set_default_rlimits(Manager *m, struct rlimit **default_rlimit) {
...
+        /* Similar, check if the daemon itself is fully up, too */
         u = manager_get_unit(m, SPECIAL_JOURNALD_SERVICE);
-        if (u && SERVICE(u)->state != SERVICE_RUNNING) {
-                log_close_journal();
+        if (!u)
+                return false;
+        if (SERVICE(u)->state != SERVICE_RUNNING)
+                return false;
+
+        return true;
```
Comment (yuwata) [inline src/core/manager.c:3511]: The above four lines can be `return state == SERVICE_RUNNING`. Of course, the current code is consistent with the one for the socket. Just a comment, and not necessary to fix it.

**Comment by poettering** [comment]
OK, let's merge this then, as it unbreaks git, works for @sourcejedi and @yuwata likes it!

**Comment by sourcejedi** [comment]
Ok, I think I've convinced myself :).  So now the window where PID 1 will log to journald before it has processed sigchld, is hopefully pretty small.  And if we're unlucky enough to hit a full receive buffer, it's supposed to be handled by the 10ms timeout in PID 1 logging.  We should stop hitting the 10 _second_ timeout (which is used by any other PID), anywhere on the path to restart journald.

I'd love to have a guarantee that was stronger, or where the reasoning was made more explicit... maybe didn't require realizing to read log.c for magic numbers, when you read recheck_journal().  But my original reaction, about removing socket-activation of journald, would have been a rather bigger change in the visible design.  So I understand keeping the original idea, and I'm just whinging about how long it took me to understand that idea :).

**Comment by sourcejedi** [comment]
Urg.  There's another implied condition which is even more obscure.  We do meet it however.

systemd-journal.service should avoid having an ordering dependency on any unit where systemd forks a child process.   Because that process could block for 10s per log message.

Even limiting the dependencies to sockets and slices is not enough on its own.  Socket units fork if the socket type supports a BPF firewall (because it's associated with the cgroup), or if the socket needs to be chown'ed to a different user/group (to avoid blocking on user resolution).

File: src/core/manager.c [hunk 3]
```diff
@@ -3132,6 +3132,9 @@ int manager_reload(Manager *m) {
         manager_vacuum_uid_refs(m);
         manager_vacuum_gid_refs(m);
 
+        /* It might be safe to log to the journal now. */
+        manager_recheck_journal(m);
```
Comment (sourcejedi) [inline src/core/manager.c:3136]: @poettering I'm confused by this.  I'm thinking about where recheck_journal() should be called, knowing that the initrd systemd passes its state to the "real" one.  (Edit: Also `systemctl daemon-reexec`).

Don't we need to call recheck_journal() from manager_startup()?

Why do we want to call it from manager_reload()?  The state of the journald units should be the same before and after deserialization.  Surely manager_reload() doesn't somehow check for unit readiness and yet avoid calling unit_notify()?
