### PR TITLE
ptyfwd: fix OSC sequence termination handling

### LINKED ISSUE #35631: Unwanted leading '\' displayed in prompt of systemd-nspawn inside run0 session
### systemd version the issue has been seen with

257

### Used distribution

Archlinux

### Linux kernel version used

linux-6.1.120-1-lts61

### CPU architectures issue was seen on

x86_64

### Component

systemd-nspawn, systemd-run

### Expected behaviour you didn't see

The prompt is correctly displayed in the container (i.e. without leading '\')

### Unexpected behaviour you saw

The prompt is displayed with a leading '\' (with no color)

### Steps to reproduce the problem

Launch a run0 session (authenticate), and then launch a systemd-nspawn container with a prompt containing '\[' as first character

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
\root@thehost:~# echo $PS1
\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$
\root@thehost:~#
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #35631.

### CODE REVIEW

File: src/shared/ptyfwd.c [hunk 1]
```diff
@@ -515,19 +516,35 @@ static int pty_forward_ansi_process(PTYForward *f, size_t offset) {
...
-                                }
+                                r = insert_window_title_fix(f, i+1);
+                                if (r < 0)
+                                        return r;
+                                i += r;
 
+                                f->osc_sequence = mfree(f->osc_sequence);
+                                f->ansi_color_state = ANSI_COLOR_STATE_TEXT;
+                        } else if (c == '\x1b')
+                                /* See the comment above. */
```
Comment (poettering) [inline src/shared/ptyfwd.c:524]: the comment above need updating now. this part needs to be removed:

```
                                 * since we cannot look ahead to see if the Esc is followed by a "\"
                                 * we cut a corner here and assume it will be "\"e.
```
