### PR TITLE
core/cgroup: fix io.weight and blkio.weight

### LINKED ISSUE #20519: IOWeight= doesn't set io.bfq.weight
**systemd version the issue has been seen with**
 > v249.2-1.fc35

**Used distribution**
 > Fedora Rawhide

**Linux kernel version used** (`uname -a`)

 > `5.14.0-0.rc5.20210813gitf8e6dfc64f61.46.fc36.x86_64`

**CPU architecture issue was seen on**
 > x86_64

Since https://github.com/systemd/systemd/pull/13335 `IOWeight=` set also the `io.bfq.weight` cgroup property. However, in recent systemd versions this is no longer true:

```
# systemd-run -u test.service -p IOWeight=666 /bin/sleep infinity
Running as unit: test.service
# systemctl show -p IOWeight test.service
IOWeight=666
# cat /sys/fs/cgroup/system.slice/test.service/io.bfq.weight 
default 67
```

Example from Fedora 33 (v246.10-1.fc33, 5.11.9-200.fc33.x86_64):
```
# systemd-run -u test.service -p IOWeight=666 /bin/sleep infinity
Running as unit: test.service
# systemctl show -p IOWeight test.service
IOWeight=666
# cat /sys/fs/cgroup/system.slice/test.service/io.bfq.weight 
default 666
```

/cc @keszybz

### LINKED ISSUE #21187: does map blkio.bfq.weight to 1..100 meet expectations?
Hi， after commit c3ba9cb8f1b3ea0211123e1ae8e00bf7494ba233, blkio.bfq.weight is mapped to 1..100, does it meet exception. CGROUP_BLKIO_WEIGHT_MAX is defined 1000 now.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug introduced by 29eb0eefd14afc9a2424781a28b376db47c3c570.

Fixes #20519.
Fixes #21187.

### CODE REVIEW

**Comment by yuwata** [comment]
@mrc0mmand Related to #20519?

File: src/core/cgroup.c [hunk 1]
```diff
@@ -1200,12 +1200,15 @@ static int cgroup_apply_devices(Unit *u) {
         return r;
 }
 
-static void set_io_weight(Unit *u, const char *controller, uint64_t weight) {
-        char buf[8+DECIMAL_STR_MAX(uint64_t)+1];
-        const char *p;
+static void set_io_weight(Unit *u, bool is_blkio, uint64_t weight) {
+        char buf[STRLEN("default ")+DECIMAL_STR_MAX(uint64_t)+1];
```
Comment (bluca) [inline src/core/cgroup.c]: I think it was decided not to manually add the +1 for nul, and that DECIMAL_STR_MAX accounts for it?

**Comment by mrc0mmand** [comment]
> @mrc0mmand Related to #20519?

It *does* sound related, but even with the patched build the behavior remains the same:

```
# systemd-run -u test.service -p IOWeight=666 /bin/sleep infinity
Running as unit: test.service
# systemctl show -p IOWeight test.service
IOWeight=666
# cat /sys/fs/cgroup/system.slice/test.service/io.bfq.weight 
default 67

# systemctl --version
systemd 249 (v249-1.20210823143245950218.pr20522.550.gf038f3bb4c.fc36)
```

File: src/core/cgroup.c (hunk 1 above)
Comment (yuwata) [reply src/core/cgroup.c]: It is for `\n`.

Comment (bluca) [reply src/core/cgroup.c]: ah, got it

**Comment by yuwata** [comment]
@mrc0mmand Updated. The revised version should fix the issue. Could you test again?

**Comment by mrc0mmand** [comment]
> @mrc0mmand Updated. The revised version should fix the issue. Could you test again?

Nice, now it appears to be working as expected:

```
# systemd-run -u test.service -p IOWeight=666 /bin/sleep infinity
Running as unit: test.service
# systemctl show -p IOWeight test.service
IOWeight=666
# cat /sys/fs/cgroup/system.slice/test.service/io.bfq.weight 
default 666

# systemctl --version
systemd 249 (v249-1.20210823165109407537.pr20522.550.gb32239d969.fc36)
```

Thanks!

**Comment by Werkov** [comment]
Given the kernel's default BFQ weight is 100, there's an asymmetry between the minimum and maximum weights ratio to this baselien. Therefore, I think the correct formula should remap only the upper "half" of the range:
```
if (weight <= 100)
    kernel_weight = weight;
else
    kernel_weight = 100 + (weight - 100) / 11;
```
so that units with the default config would still yield the `kernel_weight` of 100. (But at the same time the kernel asymmetry seems a bit arbitrary to me, might be better fixed in BFQ.)

**Comment by yuwata** [comment]
@Werkov 
> Given the kernel's default BFQ weight is 100, there's an asymmetry between the minimum and maximum weights ratio to this baseline. Therefore, I think the correct formula should remap only the upper "half" of the range:
> 
> ```
> if (weight <= 100)
>     kernel_weight = weight;
> else
>     kernel_weight = 100 + (weight - 100) / 11;
> ```
> 
> so that units with the default config would still yield the `kernel_weight` of 100. (But at the same time the kernel asymmetry seems a bit arbitrary to me, might be better fixed in BFQ.)
> 
> EDIT: Note that the asymmetry is present both in v1 and v2 BFQ cgroup API.

Could you give me a reference for that?

**Comment by poettering** [comment]
urks, bfq. we should have never merged support for that mess. systemd should not be the place to work around kernel politics.

And it sucks we always make two writes to these files, of which one then fails.

**Comment by Werkov** [comment]
@yuwata I summed the references in [a mail](https://lore.kernel.org/linux-block/20210824105626.GA11367@blackbody.suse.cz/T/#u), plus [these](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/block/bfq-cgroup.c?h=v5.14-rc7#n1030) [two](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/block/bfq-cgroup.c?h=v5.14-rc7#n1076).

@poettering The state of things is what it is and I guess it has to be accepted [1]. I'd approach this the similar way how systemd hides v1 vs v2 cgroup API differences and do best effort conversion (to that effect, the alternative to my formula above may be simply a revert of 29eb0eefd14afc9a2424781a28b376db47c3c570).

[1] I'm now referring more to the `io.weight`/`io.bfq.weight` schism, not to the range accepted.

**Comment by yuwata** [comment]
@Werkov Thanks.

I may mis-understand the issue. Is value `{blkio,io}.bfq.weight` propagated to `{blkio,io}.weight`?? So, we should first set the value to `bfq.weight`, and then to `weight`?

**Comment by yuwata** [comment]
Updated. PTAL.

File: src/core/cgroup.c [hunk 2]
```diff
@@ -1200,21 +1200,48 @@ static int cgroup_apply_devices(Unit *u) {
...
+        assert(u);
+
+        /* FIXME: drop this when distro kernels properly support BFQ through "io.weight"
+         * See also: https://github.com/systemd/systemd/pull/13335 and
+         * https://github.com/torvalds/linux/commit/65752aef0a407e1ef17ec78a7fc31ba4e0b360f9.
+         * The range is 1..1000 apparently, and the default is 100. */
+        if (weight <= CGROUP_WEIGHT_DEFAULT)
+                bfq_weight = CGROUP_BFQ_WEIGHT_DEFAULT - (CGROUP_WEIGHT_DEFAULT - weight) * (CGROUP_BFQ_WEIGHT_DEFAULT - CGROUP_BFQ_WEIGHT_MIN) / (CGROUP_WEIGHT_DEFAULT - CGROUP_WEIGHT_MIN);
+        else
+                bfq_weight = CGROUP_BFQ_WEIGHT_DEFAULT + (weight - CGROUP_WEIGHT_DEFAULT) * (CGROUP_BFQ_WEIGHT_MAX - CGROUP_BFQ_WEIGHT_DEFAULT) / (CGROUP_WEIGHT_MAX - CGROUP_WEIGHT_DEFAULT);
```
Comment (poettering) [inline src/core/cgroup.c]: move to a helper call "convert_bfq_weight()" that takes the weight as input and outputs th converted weight?

**Comment by keszybz** [comment]
I added the helper as suggested by Lennart and a few test cases to make sure that the conversion happens as expected (it does). I force-pushed into your branch to speed things up.

**Comment by Werkov** [comment]
I was looking into the [clamping approach](https://github.com/Werkov/systemd/commit/23c61499c74a2d51a7c590c60c8994106bfdbe67), assuming that kernel will eventually accept the full range (but the clamping would IMO be better approach currently too).
Should I review my branch and post it without waiting for the [kernel change](https://lore.kernel.org/linux-block/20211015135352.57245-1-mkoutny@suse.com/)?

**Comment by keszybz** [comment]
I looked at your commit, and I don't like the loop. Why not scale it like in this PR?

**Comment by Werkov** [comment]
I think any scaling will confuse users (clamping too but its logged and in theory it's only above 1000, so less likely).
Are you displeased by the backwards goto or the repeated write in general?

**Comment by yuwata** [comment]
@Werkov https://github.com/systemd/systemd/pull/21208#issuecomment-961171813
> > It seems that the value specified to bfq.weight is propagated to (non-bfq) weight. Let's not touch bfq.weight.
> 
> :-o That surely isn't warranted. What kernel version have you seen this with?

Neither I found any code about the propagation. But, then, what is the root cause of the issues??

**Comment by yuwata** [comment]
(The "propagation" sentence is dropped from the message of the first commit.)

**Comment by Werkov** [comment]
The cause is that there are two policies for proportional IO control, systemd provides one abstraction on top of these (which is IMO good). (See also [above](https://github.com/systemd/systemd/pull/20522#issuecomment-906423513) what differs.)

**Comment by keszybz** [comment]
> Are you displeased by the backwards goto or the repeated write in general?

The repeated write. Looping is nasty, and usually causes trouble sooner or later.

I think the approach in this PR is good: we scale the value and provide a uniform API. I don't think the details of the scaling are terribly important: we provide a reasonable linear mapping and that should be good enough.

**Comment by Werkov** [comment]
O.K. Let's move forward with that.
Some [debug messages](https://github.com/systemd/systemd/pull/21728) may come handy when troubleshooting.

File: src/core/cgroup.c [hunk 3]
```diff
@@ -1200,21 +1206,46 @@ static int cgroup_apply_devices(Unit *u) {
         return r;
 }
 
-static void set_io_weight(Unit *u, const char *controller, uint64_t weight) {
-        char buf[8+DECIMAL_STR_MAX(uint64_t)+1];
-        const char *p;
+/* Convert the normal io.weight value to io.bfq.weight */
+#define BFQ_WEIGHT(weight) \
```
Comment (poettering) [inline src/core/cgroup.c:1210]: i'd really prefer if this was a function, i.e. this macro doesn't enclose argumnts in () as one should, and doesn't guard against double eval, and falls totally apart if negative values/incorrect types are passed. And the ability of being able to use compile time verification instead of test runtime doesn't really matter I think.

Comment (Werkov) [reply src/core/cgroup.c:1210]: FTR, that's been cleaned in https://github.com/systemd/systemd/pull/21728/commits/d2bd0bfa362a26a8cd6e1d68e5c485f129fbb379. But I'll take into account your remark when getting back to https://github.com/systemd/systemd/pull/21795/commits/d473255080951df2d3710e010b21896e8774e63f (dropping it).
