### PR TITLE
pcrlock: Record predictions at start of component range

### LINKED ISSUE #39946: systemd-pcrlock does not include PCR states at "start"
### systemd version the issue has been seen with

258.2

### Used distribution

Archlinux

### Linux kernel version used

6.17.9-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

When running `systemd-pcrlock predict --location [start]:[end]`, it should predict PCR values that are present at the start event. For example, in the default configuration where location is `760:940` the predictions for PCR 11 should have an allowed value that includes event `750-enter-initrd` and no later events, along with other allowed values with later events.

### Unexpected behaviour you saw

The prediction only includes PCR values that occur after more events have been recorded, or the end of the range is reached.

### Steps to reproduce the problem

This can be easily seen by running
```systemd-pcrlock predict --pcr=11 --location=760:940```
and
```systemd-pcrlock predict --pcr=11 --location=760```
on a system with the default `systemd-pcrphase` events set up.

On my system, this produces these results:
```
Results for PCR 11 (kernel-boot):
  sha256: e232ff58b6d307b332d63b4380cfa559d5e0ca23842d3c41c8294162770f1e8f
  sha256: 55b980105889af3f78345078627e5f972d7b5b2243cf02781fea2bed3a2cfa4f
  sha256: 9e0886c2ae969cb351350d365bb909703f3b5c975738ae48a3acf6152b348549
```
```
Results for PCR 11 (kernel-boot):
  sha256: 0a2c504001d198c0752a7d2ec7e6ca9ca161fc8630cc298f62b36849e74b4ab7
```
The `0a2c` value corresponds to the value of PCR 11 immediately after the `750-enter-initrd` event, while the other three values correspond to the value after `800-leave-initrd`, `850-sysinit`, and `900-ready`.

The result is that the policy generated with `--location=760:940` is actually only valid after the `800-leave-initrd` event occurs. This is contrary to the man page for systemd-pcrlock, which clearly indicates that this default range is intended to cover the system from just after the initrd is entered, and breaks this policy for unlocking disk encryption keys at boot, which seems to be the primary purpose of systemd-pcrlock.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by fergus-dall**
Currently pcrlock won't predict PCR values that would be present at the start of the requested location range (unless there are no events for that PCR in the location range). This means predictions for the default range 760:940, which is intended to start just after entering the initrd, are not actually possible to fulfill until after the initrd is exited (or possibly even later, depending on what other events are recorded).

Fix this by recording predictions immediately prior to processing components after the start point.

Fixes #39946

### CODE REVIEW

**Comment by fergus-dall** [comment]
Giving this a nudge

**Comment by fergus-dall** [comment]
Just giving this a nudge

**Comment by keszybz** [comment]
I rebased the patch to restart CI. @poettering PTAL.

File: src/pcrlock/pcrlock.c [hunk 1]
```diff
@@ -4043,8 +4042,6 @@ static int event_log_component_variant_calculate(
                 uint32_t pcr,
                 const char *path) {
```
Comment (poettering) [inline src/pcrlock/pcrlock.c]: path and component canbe dropped now iiuc.

Comment (fergus-dall) [reply src/pcrlock/pcrlock.c]: Done

**Comment by keszybz** [comment]
OK. This is a clear bugfix and pcrlock is not something that is widely used, so I think it's better to merge this than to wait.
