### PR TITLE
cryptsetup: Add dependency on loopback setup to generated units

### LINKED ISSUE #9308: systemd-cryptsetup: fails to mount LUKS volume that is a file (not a device)
**systemd version the issue has been seen with**
> systemd 238
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Debian unstable (sid)

**Expected behaviour you didn't see**
 > LUKS volume at `/path/to/luksvolume` (it's a file, not a device) should be mounted at boot

**Unexpected behaviour you saw**
 > Mounting the LUKS volume fails. I have to switch to the console and `systemctl restart systemd-cryptsetup@foo.service` manually. This succeeds and works around the issue, but has to be done at every boot.

`/etc/crypttab`:
```
foo /path/to/luksvolume /etc/luks-keys/foo nofail,discard,luks
```

Log, including the manual restart of the systemd-cryptsetup unit:
```
$ journalctl -b -1 -u systemd-cryptsetup@*
-- Logs begin at Fri 2016-04-01 10:13:18 CEST, end at Fri 2018-06-15 08:55:34 CEST. --
Jun 14 09:34:24 i10pc82 systemd-cryptsetup[375]: Set cipher aes, mode xts-plain64, key size 256 bits for device /path/to/luksvolume.
Jun 14 09:34:26 i10pc82 systemd-cryptsetup[375]: Failed to activate with key file '/etc/luks-keys/foo': Invalid argument
Jun 14 09:35:33 i10pc82 systemd[1]: systemd-cryptsetup@foo.service: Main process exited, code=killed, status=15/TERM
Jun 14 09:35:33 i10pc82 systemd[1]: systemd-cryptsetup@foo.service: Failed with result 'signal'.
Jun 14 09:35:33 i10pc82 systemd[1]: Stopped Cryptography Setup for foo.
Jun 14 09:35:33 i10pc82 systemd[1]: Starting Cryptography Setup for foo...
Jun 14 09:35:33 i10pc82 systemd-cryptsetup[1172]: Set cipher aes, mode xts-plain64, key size 256 bits for device /path/to/luksvolume.
Jun 14 09:35:35 i10pc82 systemd[1]: Started Cryptography Setup for foo.
```

**Steps to reproduce the problem**
> Happens at every boot. Haven't tried reproducing on another machine, but I would suppose that this would happen for every LUKS volume that is a file rather than a device.

### PR DESCRIPTION
**Pull request by lorenzhs**
For loopback volumes, the generated unit needs to depend on
systemd-tmpfiles-setup-dev.service to ensure that loopback
support is loaded.

Fixes #9308

### CODE REVIEW

File: src/cryptsetup/cryptsetup-generator.c [hunk 1]
```diff
@@ -152,7 +152,9 @@ static int create_disk(
                               f);
         } else
                 fprintf(f,
-                        "RequiresMountsFor=%s\n",
+                        "RequiresMountsFor=%s\n"
+                        "Requires=systemd-tmpfiles-setup-dev.service\n"
```
Comment (poettering) [inline src/cryptsetup/cryptsetup-generator.c]: hmm,  we don't need the Requires= here, do we? I mean the unit is pulled in anyway, this is merely an ordering issue.

Generally we try to minimize coupling, i.e. be as loose as possible and as strict as necessary. The Requires= dep appears to be unnecessary to me, the After= should suffice, no?

Comment (medhefgo) [reply src/cryptsetup/cryptsetup-generator.c]: It needs both, actually. It cannot work without Requires= because otherwise we don't have /dev/loop-control around.

Comment (lorenzhs) [reply src/cryptsetup/cryptsetup-generator.c]: I can test it and find out the definitive answer tomorrow when I get back to the machine exhibiting this issue :)

Comment (medhefgo) [reply src/cryptsetup/cryptsetup-generator.c]: No need for that; After= is enough. The service in question is always pulled in because it is part of low-level boot. The question is whether it should still be listed for completeness sake. I am personally on the yes side of that. A service file should always list its dependencies it really has and it would be systemd's job to ignore unnecessary ones. But also, not my call to make :D

Comment (poettering) [reply src/cryptsetup/cryptsetup-generator.c]: @medhefgo well, but whether that service is really a dependency is really debatable. I mean, i use cryptsetup, but not for loopback stuff, hence for me it really isn't. also, if creating some device node fails, this should not matter for cryptsetup usually, hence Requires= is wrong anyway...

The way to look at it I think is always to consider a user who booted into emergency mode and now piecemeal starts services, and only the one he really needs. If he decides to start cryptsetup, does that really mean he should also get the wants stuff? I am not convinced...

Comment (medhefgo) [reply src/cryptsetup/cryptsetup-generator.c]: This is for the code path for loopback devices only. /dev crypto devices don't get this dependency.

Comment (yuwata) [reply src/cryptsetup/cryptsetup-generator.c]: What happens if `systemd-tmpfiles-setup-dev.service` is masked and `modules_load=loop` is set to kernel command line as you suggested in #9308?

Comment (medhefgo) [reply src/cryptsetup/cryptsetup-generator.c]: @yuwata If people wanna shoot themselves in the foot ^^^^ customize their system, let them. It's not our job to make things easier for them.

Anyway, you did make me realize that our dependency really is /dev/loop-control. So Requires+After=dev-loop\x2dcontrol.device *should* do the trick much more correctly. @lorenzhs  Can you give this dependency a spin on your system?

Comment (lorenzhs) [reply src/cryptsetup/cryptsetup-generator.c]: Not sure if that's a Debian thing but `dev-loop\x2dcontrol.device` isn't a thing on my system:
```sh
$ systemctl status dev-loop\\x2dcontrol.device
● dev-loop\x2dcontrol.device
   Loaded: loaded
   Active: inactive (dead)
```

Comment (medhefgo) [reply src/cryptsetup/cryptsetup-generator.c]: Afaik such device units are created as/when the devices appear.

Comment (lorenzhs) [reply src/cryptsetup/cryptsetup-generator.c]: (it also doesn't help to put that in the unit file)

Comment (medhefgo) [reply src/cryptsetup/cryptsetup-generator.c]: Then it probably needs this udev rule too:
KERNEL=="loop-control", TAG+="systemd"

Comment (poettering) [reply src/cryptsetup/cryptsetup-generator.c]: > This is for the code path for loopback devices only. /dev crypto devices don't get this dependency.

That is a very good point.

Comment (poettering) [reply src/cryptsetup/cryptsetup-generator.c]: > Anyway, you did make me realize that our dependency really is /dev/loop-control. So Requires+After=dev-loop\x2dcontrol.device should do the trick much more correctly. @lorenzhs Can you give this dependency a spin on your system?

Hmm, we don't tag that device with "systemd" in the udev database, which means it never shows up as ".device" unit, and I am not convinced we should change that. So far we put the tag mostly on "real" devices, not API entrypoint stuff. i.e. /dev/null and /dev/random area also not tagged, for the same reason.

hence I think the patch as it is right now actually looks good to me.

File: src/cryptsetup/cryptsetup-generator.c [hunk 2]
```diff
@@ -152,7 +152,9 @@ static int create_disk(
...
+                        "After=systemd-tmpfiles-setup-dev.service\n",
                         u_escaped);
```
Comment (poettering) [inline src/cryptsetup/cryptsetup-generator.c:161]: hmm, so I think we should merge it like this, but could you add a brief comment before this fprintf() that explains why we need systemd-tmpfiles-setup-dev? This is not obvious after all, and the next one reading this really should get an explanation

Comment (lorenzhs) [reply src/cryptsetup/cryptsetup-generator.c:161]: done
