### PR TITLE
sd-bus: fix buffer overflow on 32bit arch

### LINKED ISSUE #23486: heap-buffer-overflow READ of size 7 in  bus_message_parse_fields (on i386)
**systemd version the issue has been seen with**
af7211541272823b1e (but is has been known for years)

According to https://github.com/systemd/systemd/blob/af7211541272823b1ef4fef8c36d10dc1027733e/README#L284-L288

i386 is supported so issues like that aren't irrelevant anymore as far as I understand.
```
printf '\x6c\x0a\x03\x01\x00\x00\x00\x00\x2a\x20\x23\x6f\x10\x00\x00\x00\x1c\x05\x6f\x6f\x62\x79\x69\x00\xfc\xff\xff\xff\xff\xff\xff\xff' >4ca2fa562e62b1e6070f903784a7cdf0903e3d82
```
```sh
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1866096144
INFO: Loaded 2 modules   (80421 inline 8-bit counters): 80399 [0xf7c62990, 0xf7c7639f), 22 [0x8203b50, 0x8203b66),
INFO: Loaded 2 PC tables (80421 PCs): 80399 [0xf7c763a0,0xf7d13418), 22 [0x81bd834,0x81bd8e4),
./build/fuzz-bus-message: Running 1 inputs 1 time(s) each.
Running: CORPUS/4ca2fa562e62b1e6070f903784a7cdf0903e3d82
=================================================================
==2596397==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf4000a50 at pc 0x080e414d bp 0xffc235c8 sp 0xffc231a0
READ of size 7 at 0xf4000a50 thread T0
    #0 0x80e414c in __interceptor_memchr.part.0 asan_interceptors.cpp.o
    #1 0xf76526ec in validate_nul /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:3308:13
    #2 0xf763fe71 in message_peek_field_string /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:4950:22
    #3 0xf76414c2 in message_skip_fields /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:5051:29
    #4 0xf75f8349 in bus_message_parse_fields /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:5460:37
    #5 0xf75f3336 in bus_message_from_malloc /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:568:13
    #6 0x81a2ced in LLVMFuzzerTestOneInput /home/vagrant/systemd/build/../src/libsystemd/sd-bus/fuzz-bus-message.c:30:13
    #7 0x808e866 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned int) (/home/vagrant/systemd/build/fuzz-bus-message+0x808e866)
    #8 0x80714be in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned int) (/home/vagrant/systemd/build/fuzz-bus-message+0x80714be)
    #9 0x80776b3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned int)) (/home/vagrant/systemd/build/fuzz-bus-message+0x80776b3)
    #10 0x8065b50 in main (/home/vagrant/systemd/build/fuzz-bus-message+0x8065b50)
    #11 0xf693ae48 in __libc_start_call_main (/lib/libc.so.6+0x24e48)
    #12 0xf693af22 in __libc_start_main@GLIBC_2.0 (/lib/libc.so.6+0x24f22)
    #13 0x8065bbb in _start (/home/vagrant/systemd/build/fuzz-bus-message+0x8065bbb)
    #13 0x8065bbb in _start (/home/vagrant/systemd/build/fuzz-bus-message+0x8065bbb)

0xf4000a50 is located 0 bytes to the right of 32-byte region [0xf4000a30,0xf4000a50)
allocated by thread T0 here:
    #0 0x816280b in malloc (/home/vagrant/systemd/build/fuzz-bus-message+0x816280b)
    #1 0xf730bef1 in memdup /home/vagrant/systemd/build/../src/basic/alloc-util.c:16:15
    #2 0x81a2b81 in LLVMFuzzerTestOneInput /home/vagrant/systemd/build/../src/libsystemd/sd-bus/fuzz-bus-message.c:28:9
    #3 0x808e866 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned int) (/home/vagrant/systemd/build/fuzz-bus-message+0x808e866)
    #4 0x80714be in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned int) (/home/vagrant/systemd/build/fuzz-bus-message+0x80714be)
    #5 0x80776b3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned int)) (/home/vagrant/systemd/build/fuzz-bus-message+0x80776b3)
    #6 0x8065b50 in main (/home/vagrant/systemd/build/fuzz-bus-message+0x8065b50)
    #7 0xf693ae48 in __libc_start_call_main (/lib/libc.so.6+0x24e48)

SUMMARY: AddressSanitizer: heap-buffer-overflow asan_interceptors.cpp.o in __interceptor_memchr.part.0
Shadow bytes around the buggy address:
  0x3e8000f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e800100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e800110: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e800120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e800130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x3e800140: fa fa fa fa fa fa 00 00 00 00[fa]fa 00 00 00 00
  0x3e800150: fa fa 00 00 00 00 fa fa 00 00 00 fa fa fa 00 00
  0x3e800160: 00 01 fa fa 00 00 00 fa fa fa 00 00 00 01 fa fa
  0x3e800170: 00 00 00 01 fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e800180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e800190: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==2596397==ABORTING
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #23486.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx

**Comment by evverx** [comment]
Looks like that particular issue is gone. Thanks! The fuzz target still crashes as soon as it starts with
```sh
=================================================================
==3393287==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf4b6431c at pc 0x080e414d bp 0xffeefe58 sp 0xffeefa30
READ of size 1 at 0xf4b6431c thread T0
    #0 0x80e414c in __interceptor_memchr.part.0 asan_interceptors.cpp.o
    #1 0xf763e2dc in validate_nul /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:3313:13
    #2 0xf7616195 in validate_string /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:3325:14
    #3 0xf7613e52 in sd_bus_message_read_basic /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:3496:38
    #4 0xf75a76b7 in sd_bus_message_dump /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-dump.c:202:21
    #5 0x81a30bf in LLVMFuzzerTestOneInput /home/vagrant/systemd/build/../src/libsystemd/sd-bus/fuzz-bus-message.c:39:9
    #6 0x808e866 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned int) (/home/vagrant/systemd/out/fuzz-bus-message+0x808e866)
    #7 0x808f591 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned int, bool, fuzzer::InputInfo*, bool, bool*) (/home/vagrant/systemd/out/fuzz-bus-message+0x808f591)
    #8 0x809213e in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/vagrant/systemd/out/fuzz-bus-message+0x809213e)
    #9 0x8092628 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/vagrant/systemd/out/fuzz-bus-message+0x8092628)
    #10 0x80774c1 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned int)) (/home/vagrant/systemd/out/fuzz-bus-message+0x80774c1)
    #11 0x8065b50 in main (/home/vagrant/systemd/out/fuzz-bus-message+0x8065b50)
    #12 0xf68ece48 in __libc_start_call_main (/lib/libc.so.6+0x24e48)
    #13 0xf68ecf22 in __libc_start_main@GLIBC_2.0 (/lib/libc.so.6+0x24f22)
    #14 0x8065bbb in _start (/home/vagrant/systemd/out/fuzz-bus-message+0x8065bbb)

0xf4b6431c is located 0 bytes to the right of 28-byte region [0xf4b64300,0xf4b6431c)
allocated by thread T0 here:
    #0 0x816280b in malloc (/home/vagrant/systemd/out/fuzz-bus-message+0x816280b)
    #1 0xf72f7ae1 in memdup /home/vagrant/systemd/build/../src/basic/alloc-util.c:16:15
    #2 0x81a2b81 in LLVMFuzzerTestOneInput /home/vagrant/systemd/build/../src/libsystemd/sd-bus/fuzz-bus-message.c:28:9
    #3 0x808e866 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned int) (/home/vagrant/systemd/out/fuzz-bus-message+0x808e866)
    #4 0x808f591 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned int, bool, fuzzer::InputInfo*, bool, bool*) (/home/vagrant/systemd/out/fuzz-bus-message+0x808f591)
    #5 0x809213e in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/vagrant/systemd/out/fuzz-bus-message+0x809213e)
    #6 0x8092628 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/vagrant/systemd/out/fuzz-bus-message+0x8092628)
    #7 0x80774c1 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned int)) (/home/vagrant/systemd/out/fuzz-bus-message+0x80774c1)
    #8 0x8065b50 in main (/home/vagrant/systemd/out/fuzz-bus-message+0x8065b50)
    #9 0xf68ece48 in __libc_start_call_main (/lib/libc.so.6+0x24e48)

SUMMARY: AddressSanitizer: heap-buffer-overflow asan_interceptors.cpp.o in __interceptor_memchr.part.0
Shadow bytes around the buggy address:
  0x3e96c810: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e96c820: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e96c830: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e96c840: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e96c850: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x3e96c860: 00 00 00[04]fa fa 00 00 00 04 fa fa 00 00 00 04
  0x3e96c870: fa fa fd fd fd fd fa fa fd fd fd fd fa fa fd fd
  0x3e96c880: fd fd fa fa 00 00 00 00 fa fa fa fa fa fa fa fa
  0x3e96c890: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e96c8a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e96c8b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3393287==ABORTING
```
but that's another issue.

FWIW I'm not sure where exactly systemd is shipped on 32-bit platforms. I opened that issue because I noticed that for some reason i386 was mentioned in the policy explicitly even though it isn't actually tested there (or at least the fuzz targets have never been run on those platforms).

**Comment by yuwata** [comment]
@evverx Updated. PTAL.

> FWIW I'm not sure where exactly systemd is shipped on 32-bit platforms. I opened that issue because I noticed that for some reason i386 was mentioned in the policy explicitly even though it isn't actually tested there (or at least the fuzz targets have never been run on those platforms).

I forgot the discussion why ubuntu i386 CI was dropped. @bluca?

**Comment by evverx** [comment]
Anyway I think the policy should just say that `systemd` is buildable on those platforms (because Packit more or less makes sure that it's buildable and the unit tests pass on i686). If/when it's actually tested there it could be updated.

**Comment by yuwata** [comment]
@evverx Updated again. If still fails, please provide the testcase.

**Comment by evverx** [comment]
```sh
printf '\x6c\x03\xff\x01\x00\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00' >CRASH
./out/fuzz-bus-message CRASH
./out/fuzz-bus-message: Running 1 inputs 1 time(s) each.
Running: CRASH
=================================================================
==3396856==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf55006e0 at pc 0xf75e255f bp 0xffc58548 sp 0xffc5853c
READ of size 1 at 0xf55006e0 thread T0
    #0 0xf75e255e in bus_message_parse_fields /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:5286:38
    #1 0xf75dff26 in bus_message_from_malloc /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:568:13
    #2 0x81a2ced in LLVMFuzzerTestOneInput /home/vagrant/systemd/build/../src/libsystemd/sd-bus/fuzz-bus-message.c:30:13
    #3 0x808e866 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned int) (/home/vagrant/systemd/out/fuzz-bus-message+0x808e866)
    #4 0x80714be in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned int) (/home/vagrant/systemd/out/fuzz-bus-message+0x80714be)
    #5 0x80776b3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned int)) (/home/vagrant/systemd/out/fuzz-bus-message+0x80776b3)
    #6 0x8065b50 in main (/home/vagrant/systemd/out/fuzz-bus-message+0x8065b50)
    #7 0xf68ede48 in __libc_start_call_main (/lib/libc.so.6+0x24e48)
    #8 0xf68edf22 in __libc_start_main@GLIBC_2.0 (/lib/libc.so.6+0x24f22)
    #9 0x8065bbb in _start (/home/vagrant/systemd/out/fuzz-bus-message+0x8065bbb)
```

**Comment by yuwata** [comment]
@evverx Thanks. One more please!

**Comment by evverx** [comment]
@yuwata given that it's just the first batch of "shallow" issues that can be triggered by that particular fuzz target on 32-bit platforms in less than a minute I don't think it's even possible to  report and fix all issues like that in a reasonable amount of time. I think it would make sense to just fix those three issues (to make sure the bus message parser can withstand 5 minutes of fuzzing or so) and be done with it. Here's the last backtrace:
```sh
printf '\x6c\x02\xdf\x01\x00\x00\x00\x00\xc9\x01\x64\x00\xfe\xff\xff\xff' >CRASH
$ ./out/fuzz-bus-message CRASH
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2787509055
INFO: Loaded 2 modules   (81497 inline 8-bit counters): 81475 [0xf7c02770, 0xf7c165b3), 22 [0x8203b50, 0x8203b66),
INFO: Loaded 2 PC tables (81497 PCs): 81475 [0xf7c165b4,0xf7cb57cc), 22 [0x81bd834,0x81bd8e4),
./out/fuzz-bus-message: Running 1 inputs 1 time(s) each.
Running: CRASH
=================================================================
==3401303==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf55006e0 at pc 0xf758d78f bp 0xffe26088 sp 0xffe2607c
READ of size 1 at 0xf55006e0 thread T0
    #0 0xf758d78e in bus_message_parse_fields /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:5286:38
    #1 0xf758b156 in bus_message_from_malloc /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:570:13
    #2 0x81a2ced in LLVMFuzzerTestOneInput /home/vagrant/systemd/build/../src/libsystemd/sd-bus/fuzz-bus-message.c:30:13
    #3 0x808e866 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned int) (/home/vagrant/systemd/out/fuzz-bus-message+0x808e866)
    #4 0x80714be in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned int) (/home/vagrant/systemd/out/fuzz-bus-message+0x80714be)
    #5 0x80776b3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned int)) (/home/vagrant/systemd/out/fuzz-bus-message+0x80776b3)
    #6 0x8065b50 in main (/home/vagrant/systemd/out/fuzz-bus-message+0x8065b50)
    #7 0xf6898e48 in __libc_start_call_main (/lib/libc.so.6+0x24e48)
    #8 0xf6898f22 in __libc_start_main@GLIBC_2.0 (/lib/libc.so.6+0x24f22)
    #9 0x8065bbb in _start (/home/vagrant/systemd/out/fuzz-bus-message+0x8065bbb)
```

File: src/libsystemd/sd-bus/bus-message.c [hunk 1]
```diff
@@ -506,7 +506,9 @@ int bus_message_from_header(
                 m->fields_size = BUS_MESSAGE_BSWAP32(m, h->dbus1.fields_size);
                 m->body_size = BUS_MESSAGE_BSWAP32(m, h->dbus1.body_size);
 
-                if (sizeof(struct bus_header) + ALIGN8(m->fields_size) + m->body_size != message_size)
+                assert(message_size >= sizeof(struct bus_header));
```
Comment (evverx) [inline src/libsystemd/sd-bus/bus-message.c:509]: I'm not sure how likely it is this assertion can be triggered but given that those messages can be controlled by senders I think it would be better to avoid it. Bogus messages should be rejected earlier somewhere without crashing code using sd-bus to parse dbus messages.

Comment (yuwata) [reply src/libsystemd/sd-bus/bus-message.c:509]: The condition is guaranteed by the other conditions at the beginning of this function. The assertion just make it clear.

**Comment by yuwata** [comment]
@evverx Are there any way to run fuzzers for 32bit system on 64bit host, except for running qemu?

**Comment by evverx** [comment]
@yuwata if you have an x86_64 machine I think the fastest way would be to "cross-compile" the fuzz targets using the ".i686" dependencies and the `-m32` flag. Another option would be to launch a 32-bit container on an x86_64 machine and build the fuzz targets there.

**Comment by yuwata** [comment]
Thanks. I will try.

**Comment by evverx** [comment]
FWIW OSS-Fuzz supports "i386" with `-m32` and 32-bit packages: https://google.github.io/oss-fuzz/getting-started/new-project-guide/#architectures but for that to work the systemd dependencies would have to be linked statically (because the runtime environment is still 64 bit and doesn't include the packages available in the build environment).

Anyway I can't reproduce those three issues anymore and the fuzz target was able to run for about 5 minutes without any crashes.

**Comment by yuwata** [comment]
> Anyway I can't reproduce those three issues anymore and the fuzz target was able to run for about 5 minutes without any crashes.

Yay! Good news! Though, I have not tested on my local machine yet. Thank you!

**Comment by yuwata** [comment]
@mrc0mmand I guess the failure in CentOS CI (CentOS Stream 8) is unrelated. But could you restart the job?

**Comment by mrc0mmand** [comment]
> @mrc0mmand I guess the failure in CentOS CI (CentOS Stream 8) is unrelated. But could you restart the job?

Interesting, that looks like we hit https://github.com/systemd/systemd/pull/17050. If this wasn't a one-off, I might need to apply https://src.fedoraproject.org/rpms/systemd/blob/rawhide/f/f58b96d3e8d1cb0dd3666bc74fa673918b586612.patch (as we do in Rawhide) in CentOS CI as well,

**Comment by michaelolbrich** [comment]
> FWIW I'm not sure where exactly systemd is shipped on 32-bit platforms. I opened that issue because I noticed that for some reason i386 was mentioned in the policy explicitly even though it isn't actually tested there (or at least the fuzz targets have never been run on those platforms).

systemd is used on a lot of 32-bit ARM devices. And while new devices are mostly 64-bit nowadays, the 32-bit devices will receive updates including new systemd versions for years to come. So fixing any 32-bit issues is certainly appreciated.

**Comment by evverx** [comment]
> systemd is used on a lot of 32-bit ARM devices

It is but I'm not sure that the policy is supposed to cover those use cases. My understanding is that it targets large distributions and more or less standard toolchains.

> So fixing any 32-bit issues is certainly appreciated.

https://github.com/google/oss-fuzz/pull/7777 landed today so if all goes well OSS-Fuzz should start fuzzing systemd compiled with `-m32` and linked with `i686` libraries soon. If https://github.com/google/oss-fuzz/pull/7779 is merged most shallow issues like that shouldn't even make it into the repository.

**Comment by keszybz** [comment]
This was already in v250.7. I'm adding it in v249-stable now too.
