### PR TITLE
sd-event: re-check new epoll events when a child event is queued

### LINKED ISSUE #18190: The program runs successfully and has output, but systemd-udevd loses program's output information and the stdout event appears to be unprocessed.
**systemd version the issue has been seen with**
 > v247

**Used distribution**
 > f33

**Linux kernel version used** (`uname -a`)
 > 5.9.16

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > Everything goes well.

**Unexpected behaviour you saw**
 > The program runs successfully and has output, but systemd-udevd loses program's output information and the stdout event appears to be unprocessed.

**Steps to reproduce the problem**
 > 
```
#!/bin/bash

function check_lvm(){
    for i in `seq 10`;do
        vgs | grep vgtest$i || exit 1
        ls /dev/vgtest$i || exit 1
        for j in `seq 10`;do
            lvs | grep lvtest${i}-${j} || exit 1
            ls /dev/vgtest${i}/lvtest${i}-${j} || exit 1
        done
    done
}

while true;do
    vgchange --refresh
    check_lvm
```
/usr/lib/udev/rules.d/11-dm-lvm.rules
```
# Use DM name and split it up into its VG/LV/layer constituents.
IMPORT{program}="/usr/sbin/dmsetup splitname --nameprefixes --noheadings --rows $env{DM_NAME}"    ####HERE, program cannot got the output ####

# DM_SUBSYSTEM_UDEV_FLAG0 is the 'NOSCAN' flag for LVM subsystem.
# This flag is used to temporarily disable selected rules to prevent any
# processing or scanning done on the LVM volume before LVM has any chance
# to zero any stale metadata found within the LV data area. Such stale
# metadata could cause false claim of the LV device, keeping it open etc.
#
# If the NOSCAN flag is present, backup selected existing flags used to
# disable rules, then set them firmly so those selected rules are surely skipped.
# Restore these flags once the NOSCAN flag is dropped (which is normally any
# uevent that follows for this LV, even an artificially generated one).
ENV{DM_SUBSYSTEM_UDEV_FLAG0}=="1", ENV{DM_NOSCAN}="1", ENV{DM_DISABLE_OTHER_RULES_FLAG_OLD}="$env{DM_UDEV_DISABLE_OTHER_RULES_FLAG}", ENV{DM_UDEV_DISABLE_OTHER_RULES_FLAG}="1"
ENV{DM_SUBSYSTEM_UDEV_FLAG0}!="1", IMPORT{db}="DM_NOSCAN", IMPORT{db}="DM_DISABLE_OTHER_RULES_FLAG_OLD"
ENV{DM_SUBSYSTEM_UDEV_FLAG0}!="1", ENV{DM_NOSCAN}=="1", ENV{DM_UDEV_DISABLE_OTHER_RULES_FLAG}="$env{DM_DISABLE_OTHER_RULES_FLAG_OLD}", \
                                   ENV{DM_DISABLE_OTHER_RULES_FLAG_OLD}="", ENV{DM_NOSCAN}=""

ENV{DM_UDEV_DISABLE_SUBSYSTEM_RULES_FLAG}=="1", GOTO="lvm_end"

# Do not create symlinks for inappropriate subdevices.
ENV{DM_LV_NAME}=="pvmove?*|?*_vorigin", GOTO="lvm_disable"
ENV{DM_LV_LAYER}=="?*", GOTO="lvm_disable"

# Create symlinks for top-level devices only.
ENV{DM_VG_NAME}=="?*", ENV{DM_LV_NAME}=="?*", SYMLINK+="$env{DM_VG_NAME}/$env{DM_LV_NAME}", GOTO="lvm_end"   ###The SYMLINK cannot be created correctly.###
```
The link cannot be created correctly because udev does not get output, but we are sure that the dmsetup has output.

### PR DESCRIPTION
**Pull request by yuwata**
Previously, when a process outputs something and exit just after
epoll_wait() but before process_child(), then the IO event is ignored
even if the IO event has higher priority. See #18190.

This can be solved by checking epoll event again after process_child().

However, there exists a possibility that another process outputs and
exits just after process_child() but before the second epoll_wait().
When the IO event has lower priority than the child event, still IO
event is processed.

So, this makes new epoll events and child events are checked in a loop
until no new event is detected. To prevent an infinite loop, the number
of maximum trial is set to 10.

Fixes #18190.

Replaces #18191, #18750, and #18799.

### CODE REVIEW

**Comment by yuwata** [comment]
See also https://github.com/systemd/systemd/pull/18750#issuecomment-785801085.

cc @hexiaowen and @gaoyi1988.

**Comment by yuwata** [comment]
The issue #18190 can be reproduced with the following. With this PR, `test-udev-event` passes even if the following`sleep()`s are inserted.
```
diff --git a/src/libsystemd/sd-event/sd-event.c b/src/libsystemd/sd-event/sd-event.c
index b83638239b..06c0fe8126 100644
--- a/src/libsystemd/sd-event/sd-event.c
+++ b/src/libsystemd/sd-event/sd-event.c
@@ -3978,6 +3978,8 @@ _public_ int sd_event_wait(sd_event *e, uint64_t timeout) {
         if (r < 0)
                 goto finish;
 
+        sleep(3);
+
         if (e->need_process_child) {
                 for (unsigned i = 0; ; ) {
                         r = process_child(e);
diff --git a/src/udev/test-udev-event.c b/src/udev/test-udev-event.c
index 584e5c27ed..42746bf8c2 100644
--- a/src/udev/test-udev-event.c
+++ b/src/udev/test-udev-event.c
@@ -1,5 +1,7 @@
 /* SPDX-License-Identifier: LGPL-2.1-or-later */
 
+#include <unistd.h>
+
 #include "path-util.h"
 #include "signal-util.h"
 #include "strv.h"
@@ -17,7 +19,7 @@ static void test_event_spawn_core(bool with_pidfd, const char *cmd, char result_
 
         assert_se(sd_device_new_from_syspath(&dev, "/sys/class/net/lo") >= 0);
         assert_se(event = udev_event_new(dev, 0, NULL, LOG_DEBUG));
-        assert_se(udev_event_spawn(event, 5 * USEC_PER_SEC, SIGKILL, false, cmd, result_buf, BUF_SIZE) == 0);
+        assert_se(udev_event_spawn(event, 5000 * USEC_PER_SEC, SIGKILL, false, cmd, result_buf, BUF_SIZE) == 0);
 
         assert_se(unsetenv("SYSTEMD_PIDFD") >= 0);
 }
@@ -60,6 +62,7 @@ static void test_event_spawn_self(const char *self, const char *arg, bool with_p
 }
 
 static void test1(void) {
+        sleep(1);
         fprintf(stdout, "aaa\nbbb");
         fprintf(stderr, "ccc\nddd");
 }
```

File: src/libsystemd/sd-event/sd-event.c [hunk 1]
```diff
@@ -3960,9 +3979,38 @@ _public_ int sd_event_wait(sd_event *e, uint64_t timeout) {
...
+                        if (r < 0)
+                                goto finish;
+
+                        if (r <= n_epoll)
+                                /* No new epoll event.*/
+                                break;
+
+                        /* New epoll events are queued. There may be a possibility that new child
+                         * events with higher priority were triggered just after the previous
+                         * process_child(). To salvage these events, let's call process_child() again. */
```
Comment (keszybz) [inline src/libsystemd/sd-event/sd-event.c]: The comment is duplicated.

File: src/libsystemd/sd-event/sd-event.c [hunk 2]
```diff
@@ -3960,9 +3979,38 @@ _public_ int sd_event_wait(sd_event *e, uint64_t timeout) {
...
+
+                        i++;
+                        if (i >= N_PROCESS_EPOLL_AND_CHILD_MAX)
+                                /* Too many trial... Give up. */
+                                break;
+
+                        n_epoll = r;
+                        e->need_process_child = true;
+                }
         }
```
Comment (keszybz) [inline src/libsystemd/sd-event/sd-event.c]: Outer {} not needed now.

File: src/libsystemd/sd-event/sd-event.c (hunk 1 above)
Comment (yuwata) [reply src/libsystemd/sd-event/sd-event.c]: It is similar, but different. Yeah, I will update the second comment to reduce redundancy.

**Comment by yuwata** [comment]
@keszybz Thank you for the comments. Updated. PTAL.

**Comment by poettering** [comment]
Did you see my comment here: https://github.com/systemd/systemd/pull/18750#issuecomment-785801085

I think our logic should be: query all event sources (i.e. epoll + waitid()) for events (order doesn't matter for this). Then, determine the highest priority event that was detected by this (and let's call the priority of it the "cutoff" priority). Then immediately check all event sources again – but this time with one restriction: only consider event sources with a priority above the cutoff priority. Of the resulting events, check again for the highest prio, make it the cutoff priority, and restart thing again, again only considering events above that new "cutoff" priority, and so on. Once one of these loops terminates with no event seen above the cutoff we are done.

This algorithm will necessarily terminate, since the number of priorities is bounded (since priorities range from INT64_MIN to INT64MAX). And it will strictly honour priorities, on every single iteration.

Does that make sense?

**Comment by yuwata** [comment]
@poettering Thank you for the suggestion. Now, priority threshold is implemented. PTAL.

File: src/libsystemd/sd-event/sd-event.c [hunk 3]
```diff
@@ -3181,10 +3186,16 @@ static int process_child(sd_event *e) {
                         r = source_set_pending(s, true);
                         if (r < 0)
                                 return r;
+                        if (r > 0) {
+                                something_new = true;
+                                if (highest_priority > s->priority)
+                                        highest_priority = s->priority;
```
Comment (keszybz) [inline src/libsystemd/sd-event/sd-event.c]: `highest_priority = MIN(highest_priority, s->priority);` ?

File: src/libsystemd/sd-event/sd-event.c [hunk 4]
```diff
@@ -3116,7 +3116,9 @@ static int process_timer(
         return 0;
 }
 
-static int process_child(sd_event *e) {
+static int process_child(sd_event *e, int64_t priority_threshold, int64_t *ret_highest_priority) {
```
Comment (keszybz) [inline src/libsystemd/sd-event/sd-event.c]: `ref_highest_priority` actually returns the lowest priority ;}. And since this is static, maybe make the parameter input/output, int64_t *priority_threshold.

File: src/libsystemd/sd-event/sd-event.c [hunk 5]
```diff
@@ -3893,6 +3894,12 @@ _public_ int sd_event_wait(sd_event *e, uint64_t timeout) {
 
                                 assert(s);
 
+                                if (s->priority > priority_threshold)
+                                        break;
+
+                                if (s->priority < highest_priority)
+                                        highest_priority = s->priority;
```
Comment (keszybz) [inline src/libsystemd/sd-event/sd-event.c]: `... MIN()`

File: src/libsystemd/sd-event/sd-event.c [hunk 6]
```diff
@@ -3931,8 +3938,66 @@ _public_ int sd_event_wait(sd_event *e, uint64_t timeout) {
...
+                        goto finish;
+                if (r == 0)
+                        /* No new child event. */
+                        break;
+
+                priority_threshold = MIN(epoll_highest_priority, child_highest_priority);
+                if (priority_threshold == INT64_MIN)
+                        break;
+
+                priority_threshold--;
```
Comment (keszybz) [inline src/libsystemd/sd-event/sd-event.c]: Maybe move the decrementation to the `for` header?

**Review by keszybz — CHANGES_REQUESTED** [review]
Looks great, but please don't use either "highest" or "lowest" when the lower numbers have higher priority. I think it's better to just say `threshold` everywhere.

File: src/libsystemd/sd-event/sd-event.c (hunk 4 above)
Comment (yuwata) [reply src/libsystemd/sd-event/sd-event.c]: > And since this is static, maybe make the parameter input/output, int64_t *priority_threshold.

`process_child()` must be called at least once with `threshold == INT64_MAX`. So, `process_epoll()` should not update `threshold`, and needs to take `threshold` and `*ret_min_threshold`. `process_child()` can directly update `threshold`, but for consistency with `process_epoll()`, I'd like to keep the current form; it takes `threshold` and `*ret_min_threshold`.

**Comment by keszybz** [comment]
LGTM. But let's wait for @poettering's ack too.

File: src/libsystemd/sd-event/sd-event.c [hunk 7]
```diff
@@ -3893,6 +3893,11 @@ _public_ int sd_event_wait(sd_event *e, uint64_t timeout) {
 
                                 assert(s);
 
+                                if (s->priority > threshold)
+                                        break;
+
+                                min_priority = MIN(min_priority, s->priority);
```
Comment (poettering) [inline src/libsystemd/sd-event/sd-event.c:3910]: this same logic needs to be added a bit further down, where inotify and signal stuff is handled. i.e. we maintain one `signal_data` structure per priority and one `inotify_data` structure per priority. If one of them is triggered we need to take that into account too when determining the minimal priority.

The change should be easy, just do the exact same stuff you do here, but do it on `struct signal_data`'s `priority` field, and the `inotify_data`'s `priority` field.

(for the timer stuff we don't need to do that, since timers are inaccurate anyway)

**Review by poettering — CHANGES_REQUESTED** [review]
Looks excellent, but one (or actually two) more things

**Comment by yuwata** [comment]
@poettering Thank you for your comment. Updated. Now, inotify events are also filtered by the threshold, and signal events update the threshold (though, they are not filtered). PTAL.

File: src/libsystemd/sd-event/sd-event.c [hunk 8]
```diff
@@ -3931,8 +3970,71 @@ _public_ int sd_event_wait(sd_event *e, uint64_t timeout) {
...
+                        break;
+
+                r = process_child(e, threshold, &child_min_priority);
+                if (r < 0)
+                        goto finish;
+                if (r == 0 && threshold < INT64_MAX)
+                        /* No new child event. */
+                        break;
+
+                r = process_inotify(e, threshold, &inotify_min_priority);
```
Comment (poettering) [inline src/libsystemd/sd-event/sd-event.c]: hmm, it seems unnecessary to move process_inotify() into the loop. I.e. we have a separate inotify queue for each priority, hence there's no need to check the contents of each queue to determine the min prioriy on it, it's entirely enough to know that there's something inside the queue. This means we don't actually need to call process_inotify() inside the loop here, but it's enough to keep track of the priority where we ar about to call event_inotify_data_read() above, because at that point we already know the priority of what is queued.

**Comment by keszybz** [comment]
CI is very unhappy.

File: src/libsystemd/sd-event/sd-event.c (hunk 8 above)
Comment (yuwata) [reply src/libsystemd/sd-event/sd-event.c]: Oh, `struct inotify_data` has own priority field. I did not know that. Thanks.

**Comment by yuwata** [comment]
@poettering Thank you for your comment. Updated again. Now, inotify events are filtered by `priority` field in `struct inotify_data`. PTAL.

**Comment by bluca** [comment]
looks like there are some udev issues, https://github.com/systemd/systemd/pull/18967 proposes a temporary revert
