### PR TITLE
network: assign new DHCP address before removing old lease address 

### LINKED ISSUE #12676: IPv4 DHCP address preliminary expired
systemd 242.19-1

arch Linux 5.0.10-arch1-1-ARCH

**Expected behaviour you didn't see**
 > IPv4 address received via DHCP should stay assigned to interface during lease renewal.

**Unexpected behaviour you saw**
 > On renewal process start address gets immediately removed from the interface. After renewal same address gets reassigned. IPv4 Communication breaks inbetween. Following log illustrates the problem:
```
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): REQUEST (renewing)
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): ACK
Mai 27 18:39:35 xenhost dbus-daemon[509]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.7425' (uid=193 pid>
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): lease expires in 59min 57s
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): T2 expires in 50min 34s
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): T1 expires in 28min 4s
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: DHCP lease lost
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing address 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: Setting transient hostname: 'n/a'
Mai 27 18:39:35 xenhost systemd-networkd[21412]: Sent message type=method_call sender=n/a destination=org.freedesktop.hostname1 path=/org/freedesktop/hostname1 interface=org.freedesktop.hostname1 m>
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: DHCPv4 address 192.168.33.5/24 via 192.168.33.2
Mai 27 18:39:35 xenhost systemd-networkd[21412]: Setting transient hostname: 'xenhost'
Mai 27 18:39:35 xenhost systemd-networkd[21412]: Sent message type=method_call sender=n/a destination=org.freedesktop.hostname1 path=/org/freedesktop/hostname1 interface=org.freedesktop.hostname1 m>
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.2/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: n/a, src: n/a, gw: 192.168.33.2, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing address: 192.168.33.5/24 (valid for 32min 8s)
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.0/24, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.255/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.0/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.5/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding address: 192.168.33.5/24 (valid for 1h)
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding route: dst: 192.168.33.5/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding route: dst: 192.168.33.255/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding route: dst: 192.168.33.0/24, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding route: dst: 192.168.33.0/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: DHCP: No routes received from DHCP server: No data available
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Configuring route: dst: 192.168.33.2/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Configuring route: dst: n/a, src: n/a, gw: 192.168.33.2, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Updating route: dst: 192.168.33.2/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Updating route: dst: n/a, src: n/a, gw: 192.168.33.2, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd[1]: Starting Hostname Service...
Mai 27 18:39:36 xenhost dbus-daemon[509]: [system] Successfully activated service 'org.freedesktop.hostname1'
Mai 27 18:39:36 xenhost systemd[1]: Started Hostname Service.
Mai 27 18:39:36 xenhost systemd-networkd[21412]: Got message type=method_return sender=:1.7441 destination=:1.7425 path=n/a interface=n/a member=n/a cookie=3 reply_cookie=57 signature=n/a error-nam>
Mai 27 18:39:36 xenhost systemd-networkd[21412]: Got message type=method_return sender=:1.7441 destination=:1.7425 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=58 signature=n/a error-nam>
Mai 27 18:39:36 xenhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res>
Mai 27 18:39:36 xenhost kernel: audit: type=1130 audit(1558975176.469:5311): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hos>
Mai 27 18:40:06 xenhost systemd[1]: systemd-hostnamed.service: Succeeded.
Mai 27 18:40:06 xenhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=>
```
**Steps to reproduce the problem**
No idea if it's matters, but I'm using a bonding device. There is an additional static IPv4 address assigned and IPv6 is active as well.
```
[root@xenhost ~]# ip a s dev lanbond
7: lanbond: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 82:28:70:ae:1a:60 brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.105/32 scope global lanbond
       valid_lft forever preferred_lft forever
    inet 192.168.33.5/24 brd 192.168.33.255 scope global dynamic lanbond
       valid_lft 2325sec preferred_lft 2325sec
    inet6 2001:16b8:2233:f6f8:8028:70ff:feae:1a60/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 3244sec preferred_lft 2902sec
    inet6 fe80::8028:70ff:feae:1a60/64 scope link
       valid_lft forever preferred_lft forever
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #12676.

### CODE REVIEW

**Comment by yuwata** [comment]
Hmm, actually, this may not release old address when acquiring process fails. @ssahani Is that your point? Anyway, we need to have better error handling. Will update.

**Comment by yuwata** [comment]
@ssahani Updated. Now, I hope, all bad cases are properly handled.

File: src/network/networkd-dhcp4.c [hunk 1]
```diff
@@ -588,9 +649,25 @@ static int dhcp_lease_acquired(sd_dhcp_client *client, Link *link) {
...
+        r = dhcp_lease_acquired(client, link);
         if (r < 0) {
-                log_link_warning_errno(link, r, "Could not update IP address: %m");
-                link_enter_failed(link);
+                /* On failure, first drop the new lease */
+                (void) dhcp_lease_lost(link);
+
+                /* Then drop the old lease. */
+                link->dhcp_lease = TAKE_PTR(link->dhcp_lease_old);
+                (void) dhcp_lease_lost(link);
```
Comment (keszybz) [inline src/network/networkd-dhcp4.c:693]: This removes the call to `link_enter_failed()`. On purpose?

When dhpc_lease_lost() is called twice, warning "DHCP lease lost" will be emitted twice, and various state changes will also happen twice. I think this needs to be refactored to avoid this.

**Comment by yuwata** [comment]
@keszybz Thank you for the comment. I've updated the failure path. Now, only lease address is dropped, and logs are not duplicated (though it may be still redundant). PTAL.

**Comment by ssahani** [comment]
Ok But keep a Note in the code that in case of network failure what happens .

**Comment by yuwata** [comment]
@ssahani and @keszybz Updated. Comments are added, and the logic on failure is simplified.

**Comment by yuwata** [comment]
> Incase of network failure we won't get into this state at all. The client is not able to communicate with the server. So how is this solving the the issue. So please update the comment not here though that client retains the IP and that could lead to two machines having the same IP.

I am afraid I may still misunderstand your point, but what do you think about stopping dhcp client in that case? Then, before stopping client, it sends release message with the old lease address.

File: src/network/networkd-dhcp4.c [hunk 2]
```diff
@@ -234,7 +288,7 @@ static int dhcp_remove_router(Link *link, struct in_addr *address) {
         if (!link->network->dhcp_use_routes)
                 return 0;
 
-        r = sd_dhcp_lease_get_router(link->dhcp_lease, &router);
+        r = sd_dhcp_lease_get_router(lease, &router);
         if (IN_SET(r, 0, -ENODATA)) {
                 log_link_debug(link, "DHCP: No gateway received from DHCP server.");
                 return 0;
```
Comment (keszybz) [inline src/network/networkd-dhcp4.c:303]: Those error messages talk about stuff "received from the DHCP server". It'll be pretty confusing if any of this is emitted when removing a route for the *old* lease. Maybe this should be updated to not log anything (even at debug level), when operating on old lease?

File: src/network/networkd-dhcp4.c [hunk 3]
```diff
@@ -216,13 +249,34 @@ static int dhcp_remove_routes(Link *link, struct in_addr *address) {
...
+                                        continue;
+                                assert_se(sd_dhcp_route_get_destination_prefix_length(new_routes[i], &l) >= 0);
+                                if (l != route->dst_prefixlen)
+                                        continue;
+                                break;
+                        }
+                        if (j != m)
+                                continue;
+                }
+
```
Comment (keszybz) [inline src/network/networkd-dhcp4.c:281]: It'd be much easier to read when split out to a separate function
(also fixes j↔i typo):
```C
static bool route_present_in_routes(const Route *route, const sd_dhcp_route **routes, unsigned n_routes) {
    assert(n == 0 || routes);
    for (unsigned j = 0; j < n_routes; j++) {
                                union in_addr_union a;
                                unsigned char l;

                                assert_se(sd_dhcp_route_get_gateway(routes[j], &a.in) >= 0);
                                if (!in_addr_equal(AF_INET, &a, &route->gw))
                                        continue;
                                assert_se(sd_dhcp_route_get_destination(new_routes[j], &a.in) >= 0);
                                if (!in_addr_equal(AF_INET, &a, &route->dst))
                                        continue;
                                assert_se(sd_dhcp_route_get_destination_prefix_length(new_routes[j], &l) >= 0);
                                if (l != route->dst_prefixlen)
                                        continue;
                                return true;
                        }
         return false;
}

...

 if (route_present_in_routes(route, new_routes, m))
          continue;
```

File: src/network/networkd-dhcp4.c (hunk 1 above)
Comment (keszybz) [reply src/network/networkd-dhcp4.c:693]: What about the call to `link_enter_failed()`, is it removed on purpose?

Comment (yuwata) [reply src/network/networkd-dhcp4.c:693]: When this fails, then dhcp_lease_acquired() already failed, and thus `link_enter_failed()` will called.

File: src/network/networkd-dhcp4.c (hunk 2 above)
Comment (yuwata) [reply src/network/networkd-dhcp4.c:303]: OK. Dropped.

File: src/network/networkd-dhcp4.c (hunk 3 above)
Comment (yuwata) [reply src/network/networkd-dhcp4.c:281]: Thanks.

> (also fixes j↔i typo):

ouch!

**Comment by yuwata** [comment]
@keszybz Thank you for your review. I've force-pushed an updated version. Now, I hope all comments by @keszybz are addressed. Though, @ssahani's request is not addressed yet... 

BTW, this PR conflicts with #12511. So, I will update this again after #12511 is merged.

**Comment by yuwata** [comment]
Rebased, and split the commit into small pieces.

I noticed that all failure in assigning address or routes leads to the interface failed state.
So, now `dhcp4_release_old_lease()` is called in `link_stop_clients()`. I hope now the all error paths are covered.

@keszybz and @ssahani Could you take another look? Thank you.

**Comment by ssahani** [comment]
Really sorry @yuwata busy with other work . I am pretty sure @keszybz will take deeper look.

**Comment by keszybz** [comment]
Looks pretty nice now.

**Comment by yuwata** [comment]
@keszybz and @ssahani Thank you!
