### PR TITLE
core: store timestamps of unit load attempts

### LINKED ISSUE #15992: TEST-48 is failing in autopkgtests
See https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/amd64/s/systemd-upstream/20200531_151344_224cd@/log.gz from  #15989:
```
[K[[0;32m  OK  [0m] Started [0;1;39msystemd-journald.service[0m.
[K         Starting [0;1;39msystemd-journal-flush.service[0m...
[[0;32m  OK  [0m] Finished [0;1;39msystemd-journal-flush.service[0m.
         Starting [0;1;39msystemd-tmpfiles-setup.service[0m...
[[0;32m  OK  [0m] Finished [0;1;39msystemd-tmpfiles-setup.service[0m.
         Starting [0;1;39msystemd-update-utmp.service[0m...
[[0;32m  OK  [0m] Finished [0;1;39msystemd-update-utmp.service[0m.
[[0;32m  OK  [0m] Started [0;1;39msystemd-udevd.service[0m.
[[0;32m  OK  [0m] Reached target [0;1;39msysinit.target[0m.
[[0;32m  OK  [0m] Started [0;1;39msystemd-tmpfiles-clean.timer[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mtimers.target[0m.
[[0;32m  OK  [0m] Listening on [0;1;39mdbus.socket[0m.
[[0;32m  OK  [0m] Reached target [0;1;39msockets.target[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mbasic.target[0m.
         Starting [0;1;39mrc-local.service[0m...
         Starting [0;1;39msystemd-logind.service[0m...
[   25.206863] rc.local[237]: /etc/rc.local: 2: /etc/rc.local: iptables: not found
         Starting [0;1;39msystemd-user-sessions.service[0m...
         Starting [0;1;39mtestsuite-48.service[0m...
[[0;32m  OK  [0m] Started [0;1;39mrc-local.service[0m.
[[0;32m  OK  [0m] Finished [0;1;39msystemd-user-sessions.service[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mtestservice-48.target[0m.
[[0;1;31mFAILED[0m] Failed to start [0;1;39mtestsuite-48.service[0m.
See 'systemctl status testsuite-48.service' for details.
[[0;32m  OK  [0m] Found device [0;1;39mdev-ttyS0.device[0m.
[[0;1;38;5;185mUNSUPP[0m] Starting of [0;1;39mproc-sys-fs-bi…_misc.automount[0m not supported.
[[0;32m  OK  [0m] Started [0;1;39mdbus.service[0m.
[[0;32m  OK  [0m] Started [0;1;39mserial-getty@ttyS0.service[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mgetty.target[0m.
[[0;32m  OK  [0m] Started [0;1;39msystemd-logind.service[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mmulti-user.target[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mtestsuite.target[0m.
         Starting [0;1;39mend.service[0m...
         Starting [0;1;39msystemd-update-utmp-runlevel.service[0m...
[[0;32m  OK  [0m] Listening on [0;1;39msystemd-rfkill.socket[0m.
[[0;32m  OK  [0m] Stopped [0;1;39mend.service[0m.
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-update-utmp-runlevel.service[0m.
[[0;32m  OK  [0m] Removed slice [0;1;39msystem-modprobe.slice[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mtestservice-48.target[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mtestsuite.target[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mmulti-user.target[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mgetty.target[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mtimers.target[0m.
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-tmpfiles-clean.timer[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mumount.target[0m.
[[0;32m  OK  [0m] Closed [0;1;39msystemd-rfkill.socket[0m.
         Stopping [0;1;39mdbus.service[0m...
         Stopping [0;1;39mserial-getty@ttyS0.service[0m...
         Stopping [0;1;39msystemd-logind.service[0m...
         Stopping [0;1;39msystemd-random-seed.service[0m...
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-logind.service[0m.
[[0;32m  OK  [0m] Stopped [0;1;39mserial-getty@ttyS0.service[0m.
[[0;32m  OK  [0m] Stopped [0;1;39mdbus.service[0m.
[[0;32m  OK  [0m] Removed slice [0;1;39msystem-serial\x2dgetty.slice[0m.
[[0;32m  OK  [0m] Stopped [0;1;39mrc-local.service[0m.
         Stopping [0;1;39msystemd-user-sessions.service[0m...
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-random-seed.service[0m.
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-user-sessions.service[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mbasic.target[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mpaths.target[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mslices.target[0m.
[[0;32m  OK  [0m] Removed slice [0;1;39muser.slice[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39msockets.target[0m.
[[0;32m  OK  [0m] Closed [0;1;39mdbus.socket[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39msysinit.target[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mcryptsetup.target[0m.
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-ask-password-console.path[0m.
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-ask-password-wall.path[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mswap.target[0m.
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-sysctl.service[0m.
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-modules-load.service[0m.
         Stopping [0;1;39msystemd-update-utmp.service[0m...
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-update-utmp.service[0m.
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-tmpfiles-setup.service[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mlocal-fs.target[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mlocal-fs-pre.target[0m.
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-tmpfiles-setup-dev.service[0m.
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-sysusers.service[0m.
[[0;32m  OK  [0m] Stopped [0;1;39msystemd-remount-fs.service[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mshutdown.target[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mfinal.target[0m.
[[0;32m  OK  [0m] Finished [0;1;39msystemd-poweroff.service[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mpoweroff.target[0m.
[   44.342311] systemd-udevd[226]: pid(185:systemd-tmpfiles-setup.service): Worker [235] did not accept message, killing the worker: Connection refused
[   44.362483] systemd-udevd[226]: pid(185:systemd-tmpfiles-setup.service): Worker [261] did not accept message, killing the worker: Connection refused
[   44.368259] systemd-udevd[226]: pid(185:systemd-tmpfiles-setup.service): Worker [236] did not accept message, killing the worker: Connection refused
[   44.373738] systemd-udevd[226]: pid(185:systemd-tmpfiles-setup.service): Worker [246] did not accept message, killing the worker: Connection refused
[   44.379058] systemd-udevd[226]: pid(185:systemd-tmpfiles-setup.service): Worker [234] did not accept message, killing the worker: Connection refused
[   44.383224] systemd-udevd[226]: pid(185:systemd-tmpfiles-setup.service): Worker [238] did not accept message, killing the worker: Connection refused
[   44.506562] reboot: Power down
Spawning getter /bin/journalctl -o export -D /var/tmp/systemd-test.zrmUZU/root/var/log/journal/bc517200c79c4b1d9c4af97fc52ec07f...
Finishing after writing 4257 entries
-rw-r----- 1 root root 8388608 May 31 15:03 /var/tmp/systemd-test.zrmUZU/system.journal
QEMU test failed
make: *** [run] Error 1
Makefile:4: recipe for target 'run' failed
make: Leaving directory '/tmp/autopkgtest.1XFm3W/build.cfR/systemd/test/TEST-48-START-STOP-NO-RELOAD'
---- /var/tmp/systemd-test.zrmUZU/system.journal ----
-- Logs begin at Sun 2020-05-31 15:03:12 UTC, end at Sun 2020-05-31 15:03:34 UTC. --
May 31 15:03:12 systemd-testsuite kernel: Spectre V2 : Spectre mitigation: LFENCE not serializing, switching to generic retpoline
May 31 15:03:12 systemd-testsuite kernel: acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
May 31 15:03:12 systemd-testsuite kernel: print_req_error: I/O error, dev fd0, sector 0
May 31 15:03:12 systemd-testsuite systemd[1]: Failed to find module 'autofs4'
May 31 15:03:22 systemd-testsuite systemd[1]: /lib/systemd/system/dbus.service:12: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process life-cycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.
May 31 15:03:27 systemd-testsuite systemd[1]: testsuite-48.service: Failed with result 'exit-code'.
May 31 15:03:27 systemd-testsuite systemd[1]: Failed to start testsuite-48.service.
May 31 15:03:29 systemd-testsuite systemd[1]: Starting of proc-sys-fs-binfmt_misc.automount not supported.

make: Entering directory '/tmp/autopkgtest.1XFm3W/build.cfR/systemd/test/TEST-48-START-STOP-NO-RELOAD'
TEST-48-START-STOP-NO-RELOAD CLEANUP AGAIN: test StartStopNoReload
make: Leaving directory '/tmp/autopkgtest.1XFm3W/build.cfR/systemd/test/TEST-48-START-STOP-NO-RELOAD'
========== END: TEST-48-START-STOP-NO-RELOAD ==========
FAILED TESTS:  TEST-48-START-STOP-NO-RELOAD
```

@bluca

### PR DESCRIPTION
**Pull request by bluca**
When the system is under heavy load, it can happen that the unit cache
is refreshed for an unrelated reason (in the test I simulate this by
attempting to start a non-existing unit). The new unit is found and
accounted for in the cache, but it's ignored since we are loading
something else.
When we actually look for it, by attempting to start it, the cache is
up to date so no refresh happens, and starting fails although we have
it loaded in the cache.

When the unit state is set to UNIT_NOT_FOUND, mark the timestamp in
u->fragment_loadtime. Then when attempting to load again we can check
both if the cache itself needs a refresh, OR if it was refreshed AFTER
the last failed attempt that resulted in the state being
UNIT_NOT_FOUND.

Update the test so that this issue reproduces more often.

Fixes #15992

### CODE REVIEW

**Comment by poettering** [comment]
The new `systemd.clock_usec=` switch might be what you want to use here...

**Comment by bluca** [comment]
> The new `systemd.clock_usec=` kernel cmdline switch might be what you want to use here...

Thanks for the suggestion - will try that after getting autopkgtest to print the complete log, so that I can see what's going on (would be really good if autopkgtest saved the test artifacts on failure, like the centos CI does...)

**Comment by bluca** [comment]
Found the issue with some more debugs. Update the PR to contain a fix, and the test to make it reproduce the issue more often.

**Comment by mrc0mmand** [comment]
I noticed and tracked down that this issue is affecting multiple tests (or at least it looks like quite similar), see https://github.com/systemd/systemd-centos-ci/issues/251#issuecomment-648180867.

**Comment by bluca** [comment]
> I noticed and tracked down that this issue is affecting multiple tests (or at least it looks like quite similar), see [systemd/systemd-centos-ci#251 (comment)](https://github.com/systemd/systemd-centos-ci/issues/251#issuecomment-648180867).

Thanks for catching that - yes they do look similar, as they add units without a reload.

File: src/core/manager.c [hunk 1]
```diff
@@ -1930,10 +1930,11 @@ unsigned manager_dispatch_load_queue(Manager *m) {
         return n;
 }
 
-static bool manager_unit_cache_needs_refresh(Manager *m) {
+static bool manager_unit_cache_needs_refresh(Manager *m, Unit *u) {
         assert(m);
 
-        return m->unit_cache_mtime > 0 && !lookup_paths_mtime_good(&m->lookup_paths, m->unit_cache_mtime);
+        return m->unit_cache_mtime > 0 &&
+                (m->unit_cache_mtime > u->fragment_loadtime || !lookup_paths_mtime_good(&m->lookup_paths, m->unit_cache_mtime));
```
Comment (keszybz) [inline src/core/manager.c:1937]: I guess we could pass just one pointer here and use `u->manager` instead. But this functions gonna be inlined anyway, so it doesn't matter.
