### PR TITLE
core/exec-invoke: gracefully handle lack of privilege for initgroups() in user mode

### LINKED ISSUE #39038: `ExecStart=|` does not work in user instances
### systemd version the issue has been seen with

258

### Used distribution

Arch Linux (CachyOS, technically)

### Linux kernel version used

6.16.8-2-cachyos

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

I expected the following unit to work when in my systemd user manager:

```
[Unit]
Description=Test

[Service]
Type=oneshot
ExecStart=|echo test
```

### Unexpected behaviour you saw

Starting the service failed and I see the following in my journal:

```
2025-09-19 14:30:22.837601 ERROR (sh)                 test.service: Failed to determine supplementary groups: Operation not permitted
2025-09-19 14:30:22.838182 ERROR (sh)                 test.service: Failed at step GROUP spawning /bin/sh: Operation not permitted
```

### Steps to reproduce the problem

Create `$XDG_CONFIG_HOME/systemd/user/test.service` with the contents:

```
[Unit]
Description=Test

[Service]
Type=oneshot
ExecStart=|echo test
```

Run `systemctl --user daemon-reload` then `systemctl --user start test.service`.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by YHNdnzj**
Fixes #39038

### CODE REVIEW

**Comment by poettering** [comment]
hmm, this feels a bit sloppy, no? i.e. shouldn't this be based on runtime_scope rather that getuid()?

also, shouldn't we make this truly idempotent, i.e. implement initgroups() ourselves so that if the target gid list is identical to the source one we skip over any failure to set things, but if it is different we fail?

**Comment by YHNdnzj** [comment]
> hmm, this feels a bit sloppy, no? i.e. shouldn't this be based on runtime_scope rather that getuid()?
> 
> also, shouldn't we make this truly idempotent, i.e. implement initgroups() ourselves so that if the target gid list is identical to the source one we skip over any failure to set things, but if it is different we fail?

So, I always disliked the fact that our internal logic mixes runtime scope checks with getpid/getuid ones without much of a justification. In this case however I think getgid() is the right check. We'd otherwise fail if the running user's group database is modified but haven't been applied to user manager through re-login. Hence the primary group condition basically signals that "the current user is logged in, do not try to touch the supplementary groups according to group db".

File: src/core/exec-invoke.c [hunk 1]
```diff
@@ -900,9 +900,14 @@ static int get_supplementary_groups(
...
         bool keep_groups = false;
         if (user && gid_is_valid(gid) && gid != 0) {
-                /* First step, initialize groups from /etc/groups */
-                if (initgroups(user, gid) < 0)
-                        return -errno;
+                /* First step, initialize groups from /etc/groups
+                 *
+                 * If our primary gid is already the one specified in Group= however (i.e. we're running
+                 * in user mode), do not attempt to re-initgroup(), which we'd lack privilege of if the user's
+                 * group database is modified but hasn't been applied to user manager through re-login. */
```
Comment (keszybz) [inline src/core/exec-invoke.c]: Dot at the end of the first sentence.

This para is hard to grok… Maybe something like this:
> If our primary gid is already the one specified in Group=,
> i.e. we're running in user mode, do not attempt to re-initgroup(). 
> We may lack privilege for this, if the user's group memberships have been modified,
> but the change hasn't been applied to the the user manager through re-login.

File: src/core/exec-invoke.c [hunk 2]
```diff
@@ -901,8 +901,14 @@ static int get_supplementary_groups(
         bool keep_groups = false;
         if (user && gid_is_valid(gid) && gid != 0) {
                 /* First step, initialize groups from /etc/groups */
-                if (initgroups(user, gid) < 0)
-                        return -errno;
+                if (initgroups(user, gid) < 0) {
+                        /* If our primary gid is already the one specified in Group= (i.e. we're running in
+                         * user mode), gracefully handle the case where we have no privilege to re-initgroups().
+                         * The user's group memberships might have been modified, but the change hasn't been
+                         * applied to the the user manager through re-login. */
```
Comment (yuwata) [inline src/core/exec-invoke.c]: doubled 'the'

File: src/core/exec-invoke.c [hunk 3]
```diff
@@ -901,8 +901,14 @@ static int get_supplementary_groups(
...
+                        if (!(ERRNO_IS_PRIVILEGE(errno) && gid == getgid()))
```
Comment (yuwata) [inline src/core/exec-invoke.c]: Not a matter but I'd like to replace `!(A && B)` with `!A || !B` to reduce parentheses.

**Comment by keszybz** [comment]
Backport queued for v258.2
