### PR TITLE
gpt-auto-generator: do not fail on missing libcryptsetup when verity is not used

### LINKED ISSUE #41749: systemd-gpt-auto-generator fails in initramfs when cryptsetup disabled due to incorrect verity error
### systemd version the issue has been seen with

259.4

### Used distribution

Gentoo

### Linux kernel version used

6.18.18-gentoo

### CPU architectures issue was seen on

x86_64

### Component

systemd-gpt-auto-generator

### Expected behaviour you didn't see

I expected `systemd-gpt-auto-generator` to generate the relevant unit files and succeed.

### Unexpected behaviour you saw

`systemd-gpt-auto-generator` prints the following message:
> Partition is Verity protected, but systemd-gpt-auto-generator was compiled without libcryptsetup support.

and then fails without generating unit files. The partition is not verity-protected at all; that statement is not true, it is just printed because (AFAICT) `add_veritysetup` is called unconditionally if `in_initrd`, regardless of whether any kind of verity protection is present, and that function fails if built without cryptsetup.

### Steps to reproduce the problem

Build Systemd without cryptsetup support. Put it in an initramfs. Create a root partition with the DPS-compliant type UUID, but *NOT* doing anything verity-related. Boot on an EFI system without a `root` option, or with `root=gpt-auto`.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by naraghavan2186**
add_veritysetup() is called unconditionally  from add_root_mount() and add_usr_mount() whenever in_initrd() is true, to generate units that only activate if verity devices appear. However, when compiled without libcryptsetup, this function returned a hard error, causing the entire generator to fail even when no verity protection is in use.

Change the #else fallback to log a warning message and return 0, matching the pattern already used by add_root_cryptsetup().

Fixes [41749](https://github.com/systemd/systemd/issues/41749)

### CODE REVIEW

**Comment by naraghavan2186** [comment]
**Before the fix without cryptsetup:**

Found container virtualization none.
Enabling partition auto-detection (respecting factory reset mode), root= is explicitly set to 'gpt-auto'.
Partition is Verity protected, but systemd-gpt-auto-generator was compiled without libcryptsetup support.
Adding /sysefi/: /dev/disk/by-designator/esp fstype=vfat
exit: 1

**After the fix without cryptsetup:**

Found container virtualization none.
Enabling partition auto-detection (respecting factory reset mode), root= is explicitly set to 'gpt-auto'.
Compiled without libcryptsetup support, skipping verity setup for 'root'.
Adding /sysroot: /dev/gpt-auto-root fstype=(any)
Loaded shared library 'libselinux.so.1' via dlopen().
Adding /sysefi/: /dev/disk/by-designator/esp fstype=vfat
exit: 0

File: src/gpt-auto-generator/gpt-auto-generator.c [hunk 1]
```diff
@@ -295,8 +295,8 @@ static int add_veritysetup(
 
         return 0;
 #else
-        return log_error_errno(SYNTHETIC_ERRNO(EOPNOTSUPP),
-                               "Partition is Verity protected, but systemd-gpt-auto-generator was compiled without libcryptsetup support.");
+        log_debug("Compiled without libcryptsetup support, skipping verity setup for '%s'.", id);
```
Comment (daandemeyer) [inline src/gpt-auto-generator/gpt-auto-generator.c]: I would at least keep this as a warning

Comment (naraghavan2186) [reply src/gpt-auto-generator/gpt-auto-generator.c]: Fixed it.
