### PR TITLE
nspawn: support passing wireless interface to container

### LINKED ISSUE #7873: nspawn should support passing wifi adapters to containers, like other environments (LXC, …) apparently can do
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemctl --version
systemd 236
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

> cat /etc/debian_version
buster/sid

### In case of bug report: Expected behaviour you didn't see

> the container should be started and the wireless network adapter should be moved to the namespace. the problem does not appear when starting the container via LXC.

### In case of bug report: Unexpected behaviour you saw

> machinectl start server037
Job for systemd-nspawn@server037.service failed because the control process exited with error code.
See "systemctl status systemd-nspawn@server037.service" and "journalctl -xe" for details.

> systemctl status systemd-nspawn@server037.service
● systemd-nspawn@server037.service - Container server037
   Loaded: loaded (/lib/systemd/system/systemd-nspawn@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-01-13 17:49:18 CET; 16s ago
     Docs: man:systemd-nspawn(1)
  Process: 23733 ExecStart=/usr/bin/systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth -U --settings=override --machine=server037 (code=exited, status=1/FAILURE)
 Main PID: 23733 (code=exited, status=1/FAILURE)
   Status: "Terminating..."

> Jan 13 17:49:18 server060 systemd[1]: Starting Container server037...
Jan 13 17:49:18 server060 systemd-nspawn[23733]: Failed to move interface wlx001c4afd2f29 to namespace: Invalid argument
Jan 13 17:49:18 server060 systemd[1]: systemd-nspawn@server037.service: Main process exited, code=exited, status=1/FAILURE
Jan 13 17:49:18 server060 systemd[1]: systemd-nspawn@server037.service: Failed with result 'exit-code'.
Jan 13 17:49:18 server060 systemd[1]: Failed to start Container server037.

> cat /etc/systemd/nspawn/server037.nspawn
[Exec]
PrivateUsers=False
[Network]
Bridge=br0
Interface=wlx001c4afd2f29

### In case of bug report: Steps to reproduce the problem

> create a container and try to start the container with the --network-interface= option using a wireless network adapter

### PR DESCRIPTION
**Pull request by yuwata**
Closes #7873.

### CODE REVIEW

**Comment by yuwata** [comment]
I have not tested this.

**Comment by poettering** [comment]
looks superficially good to me.

**Comment by yuwata** [comment]
This becomes much bigger than I initially expected. But, now renaming is also supported, and test cases are added. PTAL.

**Comment by yuwata** [comment]
@Edu4rdSHL Please test again.

**Comment by yuwata** [comment]
(BTW, this is nice article: https://www.suse.com/c/creating-virtual-wlan-interfaces/)

**Comment by Edu4rdSHL** [comment]
I have tested it and everything works as expected. I did a few tests:

- Passing the interface just to get network access: OK
- Passing the interface to do WiFi pentesting tests (which include putting the interface in monitor mode, etc): OK
- Passing the interface to create custom network configs inside the container: OK

**Review by Edu4rdSHL — APPROVED** [review]

File: src/shared/udev-util.c [hunk 1]
```diff
@@ -363,18 +364,24 @@ int udev_queue_is_empty(void) {
                 (errno == ENOENT ? true : -errno) : false;
 }
 
-bool udev_available(void) {
-        static int cache = -1;
+#define CACHED_UDEV_AVAIL_UNSET -1
+
+static int cached_udev_avail = CACHED_UDEV_AVAIL_UNSET;
```
Comment (poettering) [inline src/shared/udev-util.c]: i'd not abbreviate this, i.e. `available` is a fine word

File: src/nspawn/nspawn-network.c [hunk 2]
```diff
@@ -544,6 +547,43 @@ int move_network_interfaces(int netns_fd, char **iface_pairs) {
...
+int move_back_network_interfaces(int child_netns_fd, char **interface_pairs) {
+        _cleanup_close_ int parent_netns_fd = -EBADF;
+        int r;
+
+        assert(child_netns_fd >= 0);
+
+        if (strv_isempty(interface_pairs))
+                return 0;
+
+        r = namespace_open(getpid_cached(),
```
Comment (poettering) [inline src/nspawn/nspawn-network.c]: you can just pass 0 here as first arg

File: src/nspawn/nspawn-network.c [hunk 3]
```diff
@@ -541,6 +543,173 @@ static int needs_rename(sd_netlink **rtnl, sd_device *dev, const char *name) {
...
+        int r;
+
+        assert(rtnl);
+        assert(dev);
+        assert(name);
+        assert(ret_dev);
+
+        /* The command NL80211_CMD_SET_WIPHY_NETNS below passes phy instead of network interface,
+         * and does not take an interface name in the passed network namespace. Hence, we need to
+         * rename the interface before passing phy to the netns. */
```
Comment (poettering) [inline src/nspawn/nspawn-network.c]: so, if another interface already exists under the target name in the source namespace then the whole operation will fail, no? That would suck, no?

Maybe create a throw-away middle netns? i.e. open a new netns, migrate the iface there, then rename it in there, and then migrate it to the target ns? that way the interface will only exist under the old name in the source netns, and only under the new name in the target netns.

or am i missing something here, and this is not an issue?

Comment (yuwata) [reply src/nspawn/nspawn-network.c]: Sounds nice. I will try.

**Comment by yuwata** [comment]
@poettering Thank you for the review. Addressed all suggestions. PTAL.

@Edu4rdSHL Thank you for testing. If you'd like, please test again. Hopefully, this still works file.

File: src/nspawn/nspawn-network.c [hunk 4]
```diff
@@ -503,6 +506,58 @@ int test_network_interfaces_initialized(char **iface_pairs) {
...
+        if (r < 0)
+                return log_error_errno(r, "Failed to enter child network namespace: %m");
+
+        if (ret_original_netns_fd)
+                *ret_original_netns_fd = TAKE_FD(original_netns_fd);
+
+        return 0;
+}
+
+static int netns_fork(int netns_fd, int *ret_original_netns_fd) {
```
Comment (poettering) [inline src/nspawn/nspawn-network.c]: maybe call this fork_and_wait()? just to make clear that this is synchronous in the parent

File: src/nspawn/nspawn-network.c [hunk 5]
```diff
@@ -503,6 +506,58 @@ int test_network_interfaces_initialized(char **iface_pairs) {
         return 0;
 }
 
+static int netns_fork_child(int netns_fd, int *ret_original_netns_fd) {
```
Comment (poettering) [inline src/nspawn/nspawn-network.c]: maybe call this netns_child_begin() or so

the reason i am asking for this is because i was confused as first, because this function is after all not the full child, but just the initialization of the child, the main part of the child comes after this function returns after all. maybe a more precise name might help the next reader

**Comment by poettering** [comment]
lgtm, just some superficial comments about function names.

**Comment by yuwata** [comment]
@poettering Thank you for the review. The functions are renamed. Upgrading the green label.
