### PR TITLE
sd-lldp-rx: add VLAN ID parsing

### LINKED ISSUE #28354: networkctl lldp does not show VlanId
### systemd version the issue has been seen with

253

### Used distribution

Linux 

### Linux kernel version used

armv7l GNU/Linux

### CPU architectures issue was seen on

arm

### Component

networkctl

### Expected behaviour you didn't see

Expected VLAN id to be displayed when lldp data has vlan id information
```
networkctl lldp     
LINK CHASSIS-ID        SYSTEM-NAME                                       CAPS        PORT-ID PORT-DESCRIPTION
eth0 xx:dd:xx:xx:xx:80 dus-04x-3n2x-rack-f1x-4-5x00a.g.sgxlabs.com ..b.r...... 516     xe-0/0/4

Capability Flags:
b - Bridge; r - Router
```

### Unexpected behaviour you saw

 networkctl lldp does not display vlan-id information even though received lldp has vlan-id

### Steps to reproduce the problem

1. enable lldp 
2. check 'networkctl lldp' command  output on machine

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by lorenzo-arena**
While the `port_vlan_id` field was already present in the `sd_lldp_neighbor`, it wasn't currently parsed from the LLDP packet. I added support for that as well as a small parsing test.

Closes #28354.

### CODE REVIEW

File: src/libsystemd-network/lldp-neighbor.c [hunk 1]
```diff
@@ -315,6 +315,18 @@ int lldp_neighbor_parse(sd_lldp_neighbor *n) {
...
                                         return r;
                         }
+
+                        /* IEEE 802.1: VLAN ID*/
+                        if (memcmp(p, SD_LLDP_OUI_802_1_VLAN_ID, sizeof(SD_LLDP_OUI_802_1_VLAN_ID)) == 0) {
+                                if (length < 6)
+                                        return log_lldp_rx_errno(
+                                                n->lldp_rx, SYNTHETIC_ERRNO(EBADMSG),
+                                                "Found 802.1 VLAN ID TLV that is too short, ignoring."
+                                        );
```
Comment (yuwata) [inline src/libsystemd-network/lldp-neighbor.c]: Please follow the indentation at other places:
```c
return log_lldp_rx_errno(n->lldp_rx, SYNTHETIC_ERRNO(EBADMSG),
                         "Found 802.1 VLAN ID TLV that is too short, ignoring.");
```

File: src/libsystemd-network/lldp-neighbor.c [hunk 2]
```diff
@@ -632,6 +644,18 @@ int sd_lldp_neighbor_get_enabled_capabilities(sd_lldp_neighbor *n, uint16_t *ret
         return 0;
 }
 
+int sd_lldp_neighbor_get_port_vlan_id(sd_lldp_neighbor *n, uint16_t *ret)
+{
```
Comment (yuwata) [inline src/libsystemd-network/lldp-neighbor.c]: Please move `{` at the end of the previous line:
```c
int sd_lldp_neighbor_get_port_vlan_id(sd_lldp_neighbor *n, uint16_t *ret) {
```

File: src/libsystemd-network/lldp-neighbor.c [hunk 3]
```diff
@@ -315,6 +315,18 @@ int lldp_neighbor_parse(sd_lldp_neighbor *n) {
                                 if (r < 0)
                                         return r;
                         }
+
+                        /* IEEE 802.1: VLAN ID*/
+                        if (memcmp(p, SD_LLDP_OUI_802_1_VLAN_ID, sizeof(SD_LLDP_OUI_802_1_VLAN_ID)) == 0) {
+                                if (length < 6)
```
Comment (yuwata) [inline src/libsystemd-network/lldp-neighbor.c]: I'd like to make the condition more descriptive:
```c
if (length != sizeof(SD_LLDP_OUI_802_1_VLAN_ID) + sizeof(uint16_t))
```

File: src/libsystemd-network/test-lldp-rx.c [hunk 4]
```diff
@@ -358,6 +358,54 @@ static void test_multiple_neighbors_sorted(sd_event *e) {
...
+                0xfe, 0x09, 0x00, 0x80, 0xc2, 0x07,     /* Link aggregation: status 1, ID 0x00140012 */
+                0x01, 0x00, 0x14, 0x00, 0x12,
+                0xfe, 0x07, 0x00, 0x12, 0x0f, 0x02,     /* 802.3 Power via MDI: PSE, MDI enabled */
+                0x07, 0x01, 0x00,
+                0x00, 0x00                              /* End of LLDPDU */
+        };
+        uint16_t vlanid;
+
+        lldp_rx_handler_calls = 0;
+        assert_se(start_lldp_rx(&lldp_rx, e, lldp_rx_handler, NULL) == 0);
```
Comment (yuwata) [inline src/libsystemd-network/test-lldp-rx.c]: For new test code, please use `ASSERT_OK()`, which internally checks `>= 0`:
```c
ASSERT_OK(start_lldp_rx(&lldp_rx, e, lldp_rx_handler, NULL));
```
See shared/tests.h for more details.

File: src/libsystemd-network/test-lldp-rx.c [hunk 5]
```diff
@@ -358,6 +358,54 @@ static void test_multiple_neighbors_sorted(sd_event *e) {
...
+
+        assert_se(write(test_fd[1], frame, sizeof(frame)) == sizeof(frame));
```
Comment (yuwata) [inline src/libsystemd-network/test-lldp-rx.c]: Please use ASSERT_OK_EQ_ERRNO():
```c
ASSERT_OK_EQ_ERRNO(write(test_fd[1], frame, sizeof(frame)), sizeof(frame));
```

File: src/libsystemd-network/test-lldp-rx.c [hunk 6]
```diff
@@ -358,6 +358,54 @@ static void test_multiple_neighbors_sorted(sd_event *e) {
...
+        sd_event_run(e, 0);
```
Comment (yuwata) [inline src/libsystemd-network/test-lldp-rx.c]: ASSERT_OK(sd_event_run(e, 0));

File: src/libsystemd-network/test-lldp-rx.c [hunk 7]
```diff
@@ -358,6 +358,54 @@ static void test_multiple_neighbors_sorted(sd_event *e) {
...
+        assert_se(lldp_rx_handler_calls == 1);
```
Comment (yuwata) [inline src/libsystemd-network/test-lldp-rx.c]: ASSERT_EQ(..., 1);

File: src/libsystemd-network/test-lldp-rx.c [hunk 8]
```diff
@@ -358,6 +358,54 @@ static void test_multiple_neighbors_sorted(sd_event *e) {
...
+        assert_se(sd_lldp_rx_get_neighbors(lldp_rx, &neighbors) == 1);
```
Comment (yuwata) [inline src/libsystemd-network/test-lldp-rx.c]: ASSERT_OK_EQ(...);

File: src/libsystemd-network/test-lldp-rx.c [hunk 9]
```diff
@@ -358,6 +358,54 @@ static void test_multiple_neighbors_sorted(sd_event *e) {
...
+
+        assert_se(sd_lldp_neighbor_get_port_vlan_id(neighbors[0], &vlanid) >= 0);
```
Comment (yuwata) [inline src/libsystemd-network/test-lldp-rx.c]: ASSERT_OK()

File: src/libsystemd-network/test-lldp-rx.c [hunk 10]
```diff
@@ -358,6 +358,54 @@ static void test_multiple_neighbors_sorted(sd_event *e) {
...
+        assert_se(vlanid == 0x1234);
```
Comment (yuwata) [inline src/libsystemd-network/test-lldp-rx.c]: ASSERT_EQ()

File: src/libsystemd-network/test-lldp-rx.c [hunk 11]
```diff
@@ -358,6 +358,54 @@ static void test_multiple_neighbors_sorted(sd_event *e) {
...
+
+        sd_lldp_neighbor_unref(neighbors[0]);
+        free(neighbors);
+
+        assert_se(stop_lldp_rx(lldp_rx) == 0);
```
Comment (yuwata) [inline src/libsystemd-network/test-lldp-rx.c]: ASSERT_OK()

**Comment by yuwata** [comment]
In the commit message (and the cover letter of this PR), please include
```
Closes #28354.
```

File: src/libsystemd-network/lldp-neighbor.c (hunk 1 above)
Comment (lorenzo-arena) [reply src/libsystemd-network/lldp-neighbor.c]: Just out of curiosity: running `git clang-format HEAD~` would produce yet another result:

```c
return log_lldp_rx_errno(
        n->lldp_rx,
        SYNTHETIC_ERRNO(EBADMSG),
        "Found 802.1 VLAN ID TLV that is too short, ignoring."
);
```

I think due to the fact that the message would overflow the column limit. Would that be a preferred solution?

Comment (yuwata) [reply src/libsystemd-network/lldp-neighbor.c]: Please do not use `clang-format`.

Comment (lorenzo-arena) [reply src/libsystemd-network/lldp-neighbor.c]: Ok, I've reformatted it as requested. Thanks!

File: src/libsystemd-network/lldp-neighbor.c [hunk 12]
```diff
@@ -790,5 +814,6 @@ int lldp_neighbor_build_json(sd_lldp_neighbor *n, sd_json_variant **ret) {
                         JSON_BUILD_PAIR_STRING_NON_EMPTY("PortDescription", port_description),
                         JSON_BUILD_PAIR_STRING_NON_EMPTY("SystemName", system_name),
                         JSON_BUILD_PAIR_STRING_NON_EMPTY("SystemDescription", system_description),
-                        SD_JSON_BUILD_PAIR_CONDITION(valid_cc, "EnabledCapabilities", SD_JSON_BUILD_UNSIGNED(cc)));
+                        SD_JSON_BUILD_PAIR_CONDITION(valid_cc, "EnabledCapabilities", SD_JSON_BUILD_UNSIGNED(cc)),
+                        SD_JSON_BUILD_PAIR_CONDITION(valid_vlanid, "VlanID", SD_JSON_BUILD_UNSIGNED(valid_vlanid)));
```
Comment (qhill) [inline src/libsystemd-network/lldp-neighbor.c]: Should be SD_JSON_BUILD_UNSIGNED(vlanid)?

**Comment by lorenzo-arena** [comment]
Just another quick note: should I also add the new `VlanID` field (which I added to the JSON built by `lldp_neighbor_build_json` also to the `lldp_neighbor_dispatch_table` in *networkctl-lldp.c* and in *varlink-io.systemd.Network.c*?

**Comment by yuwata** [comment]
> Just another quick note: should I also add the new `VlanID` field (which I added to the JSON built by `lldp_neighbor_build_json` also to the `lldp_neighbor_dispatch_table` in _networkctl-lldp.c_ and in _varlink-io.systemd.Network.c_?

Ah, yes. Please.
Then, please also add a test case for the new field in test/test-network/systemd-networkd-tests.py .

File: src/libsystemd-network/lldp-neighbor.c (hunk 12 above)
Comment (yuwata) [reply src/libsystemd-network/lldp-neighbor.c:818]: I think the field should be conditionalized.

Comment (lorenzo-arena) [reply src/libsystemd-network/lldp-neighbor.c]: Yeah that's definitely wrong. I'll fix that, thanks

**Comment by lorenzo-arena** [comment]
I'm trying to set up mkosi to run integration tests on my workstation, however while I managed to get it running, all the integration tests fail due to the following error:

```
‣ Permission denied to access /dev/vhost-vsock. Not adding a VSock device to the virtual machine. (Maybe a kernel module could not be loaded?)
‣ VSock requested but cannot access /dev/vhost-vsock
Failed to open journal files: No such file or directory
```

The vsock module seems to be loaded in my host kernel

```
$ sudo lsmod | grep vsock
vhost_vsock            24576  0
vmw_vsock_virtio_transport_common    57344  1 vhost_vsock
vhost                  65536  1 vhost_vsock
vsock                  61440  2 vmw_vsock_virtio_transport_common,vhost_vsock
```

I'm working in Ubuntu 24.04 and I've temporarily turned off apparmor restrictions to get things running.

If this ends up being too complicated I can rely on the tests run by the CI but I'd be nice to be able to run them locally.

**Comment by yuwata** [comment]
networkd test can run without mkosi. See
https://github.com/systemd/systemd/blob/main/test/test-network/systemd-networkd-tests.py#L5-L16

Note, the comment lacks `--build-dir=/path/to/build`. Hence,
```
sudo ./systemd-networkd-tests.py --build-dir=/path/to/build NetworkdMTUTests.test_ipv6_mtu
```

**Comment by lorenzo-arena** [comment]
> networkd test can run without mkosi. See
> https://github.com/systemd/systemd/blob/main/test/test-network/systemd-networkd-tests.py#L5-L16

While this doesn't work on my machine (it blocks on the reload of systemd-resolved, but I'll investigate why) I've read the code for integration testing (the `NetworkdLLDPTests.test_lldp` function): if I'm understanding it correctly it works by having a "fake" interface configured to emit custom LLDP informations, which will be read by networkctl during the test. However, even with the `EmitLLDP` flag set I don't think networkd is able to send the information about the VLAN ID. Am I right?

File: src/libsystemd-network/test-lldp-rx.c [hunk 13]
```diff
@@ -358,6 +358,54 @@ static void test_multiple_neighbors_sorted(sd_event *e) {
         assert_se(stop_lldp_rx(lldp_rx) == 0);
 }
 
+static void test_receive_oui_vlanid_packet(sd_event *e) {
+        sd_lldp_rx *lldp_rx;
+        sd_lldp_neighbor **neighbors;
+        uint8_t frame[] = {
```
Comment (poettering) [inline src/libsystemd-network/test-lldp-rx.c]: static const?

File: src/network/networkctl-lldp.c [hunk 14]
```diff
@@ -53,6 +54,7 @@ static const sd_json_dispatch_field lldp_neighbor_dispatch_table[] = {
         { "SystemName",          SD_JSON_VARIANT_STRING,        sd_json_dispatch_const_string, offsetof(LLDPNeighborInfo, system_name),        0 },
         { "SystemDescription",   SD_JSON_VARIANT_STRING,        sd_json_dispatch_const_string, offsetof(LLDPNeighborInfo, system_description), 0 },
         { "EnabledCapabilities", _SD_JSON_VARIANT_TYPE_INVALID, sd_json_dispatch_uint16,       offsetof(LLDPNeighborInfo, capabilities),       0 },
+        { "VlanId",              _SD_JSON_VARIANT_TYPE_INVALID, sd_json_dispatch_uint16,       offsetof(LLDPNeighborInfo, vlan_id),            0 },
```
Comment (poettering) [inline src/network/networkctl-lldp.c]: hmm, in the .network files we spell this out as "VLANId". Maybe do that here too, to stick to a common syntax

File: src/libsystemd-network/test-lldp-rx.c (hunk 13 above)
Comment (lorenzo-arena) [reply src/libsystemd-network/test-lldp-rx.c]: Fixed; I also added another commit to set some declarations in older tests `static const` as well

File: src/network/networkctl-lldp.c (hunk 14 above)
Comment (lorenzo-arena) [reply src/network/networkctl-lldp.c]: In the same JSON other fields has uppercase "ID", like `PortID` or `ChassisID`. Maybe we could use `VLANID`?

File: src/libsystemd-network/lldp-neighbor.c [hunk 15]
```diff
@@ -315,6 +315,16 @@ int lldp_neighbor_parse(sd_lldp_neighbor *n) {
                                 if (r < 0)
                                         return r;
                         }
+
+                        /* IEEE 802.1: VLAN ID*/
```
Comment (dnicolodi) [inline src/libsystemd-network/lldp-neighbor.c]:
```suggestion
                        /* IEEE 802.1: VLAN ID */
```

File: src/network/networkctl-lldp.c (hunk 14 above)
Comment (yuwata) [reply src/network/networkctl-lldp.c]: Unfortunately, the naming in .network settings and JSON variant are mostly inconsistent.
And, as @lorenzo-arena commented, we use ID in JSON variant (and Id for .network). So, I prefer `VLANID` or `VlanID` here.

Comment (yuwata) [reply src/network/networkctl-lldp.c]: At least, this must be consistent with the name used in lldp_neighbor_build_json(). Hence, `VlanID` please.

**Comment by yuwata** [comment]
BTW, I noticed that sd-lldp-tx currently does not send VLAN ID. So, it is hard to add test in systemd-networkd-tests.py. Let's add a test case later when sd-lldp-tx supports that.

File: src/libsystemd-network/test-lldp-rx.c [hunk 16]
```diff
@@ -358,6 +358,54 @@ static void test_multiple_neighbors_sorted(sd_event *e) {
...
+
+        ASSERT_OK_EQ_ERRNO(write(test_fd[1], frame, sizeof(frame)), (ssize_t)sizeof(frame));
+        ASSERT_OK(sd_event_run(e, 0));
+        ASSERT_EQ(lldp_rx_handler_calls, 1);
+        ASSERT_OK_EQ(sd_lldp_rx_get_neighbors(lldp_rx, &neighbors), 1);
+
+        ASSERT_OK(sd_lldp_neighbor_get_port_vlan_id(neighbors[0], &vlanid));
+        ASSERT_EQ(vlanid, 0x1234);
+
+        sd_lldp_neighbor_unref(neighbors[0]);
```
Comment (yuwata) [inline src/libsystemd-network/test-lldp-rx.c:412]: Maybe better to call lldp_neighbor_build_json() here, and verify that this has "VlanID" field.

File: src/libsystemd-network/lldp-neighbor.c (hunk 15 above)
Comment (lorenzo-arena) [reply src/libsystemd-network/lldp-neighbor.c]: Thanks, solved

File: src/network/networkctl-lldp.c (hunk 14 above)
Comment (lorenzo-arena) [reply src/network/networkctl-lldp.c]: Right, I'll go with `VlanID` then

File: src/libsystemd-network/test-lldp-rx.c (hunk 16 above)
Comment (lorenzo-arena) [reply src/libsystemd-network/test-lldp-rx.c:412]: I added the test in the last rework of the commit

File: src/libsystemd-network/test-lldp-rx.c [hunk 17]
```diff
@@ -7,8 +7,10 @@
 
 #include "sd-event.h"
 #include "sd-lldp-rx.h"
+#include "lldp-neighbor.h"
```
Comment (yuwata) [inline src/libsystemd-network/test-lldp-rx.c]: We include `sd-xyz.h` headers earlier and separated with an empty line, so please move `lldp-neighbor.h` below:
```c
#include "sd-event.h"
#include "sd-lldp-rx.h"

#include "fd-util.h"
#include "json-util.h"
#include "lldp-neighbor.h"
#include "lldp-network.h"
#include "tests.h"
```

File: src/libsystemd-network/test-lldp-rx.c [hunk 18]
```diff
@@ -358,6 +360,61 @@ static void test_multiple_neighbors_sorted(sd_event *e) {
...
+        ASSERT_OK(sd_event_run(e, 0));
+        ASSERT_EQ(lldp_rx_handler_calls, 1);
+        ASSERT_OK_EQ(sd_lldp_rx_get_neighbors(lldp_rx, &neighbors), 1);
+
+        ASSERT_OK(sd_lldp_neighbor_get_port_vlan_id(neighbors[0], &vlanid));
+        ASSERT_EQ(vlanid, 0x1234);
+
+        ASSERT_OK(lldp_neighbor_build_json(neighbors[0], &neighbor_json));
+        v = sd_json_variant_by_key(neighbor_json, "VlanID");
+        ASSERT_TRUE(v && sd_json_variant_type(v) == SD_JSON_VARIANT_UNSIGNED);
```
Comment (yuwata) [inline src/libsystemd-network/test-lldp-rx.c]:
```c 
        ASSERT_NOT_NULL(v = sd_json_variant_by_key(neighbor_json, "VlanID"));
        ASSERT_EQ(sd_json_variant_type(v), SD_JSON_VARIANT_UNSIGNED);
```

File: src/libsystemd-network/test-lldp-rx.c [hunk 19]
```diff
@@ -358,6 +360,61 @@ static void test_multiple_neighbors_sorted(sd_event *e) {
...
+        ASSERT_EQ(sd_json_variant_unsigned(v), (uint64_t)0x1234);
```
Comment (yuwata) [inline src/libsystemd-network/test-lldp-rx.c]: `(uint64_t)0x1234` -> `UINT64_C(0x1234)`

**Comment by lorenzo-arena** [comment]
> LGTM, several minor requests for the test.

They should all be solved now 👍🏼
