### PR TITLE
journalctl: fix output when --lines is used with --grep

### LINKED ISSUE #25147: Journalctl: "--grep" and "--lines" do not work together
### systemd version the issue has been seen with

251.6

### Used distribution

Any linux

### Linux kernel version used

Any kernel

### CPU architectures issue was seen on

_No response_

### Component

_No response_

### Expected behaviour you didn't see

`journalctl -p 6 --grep "BTRFS"` shows the example:
```
$ journalctl --output=short-unix --dmesg -p 6 --grep "BTRFS"  
1666767634.061221 ManjaroKDE kernel: BTRFS: device label System devid 1 transid 742 /dev/sda2 scanned by systemd-udevd (179)
1666767634.061238 ManjaroKDE kernel: BTRFS info (device sda2): using crc32c (crc32c-intel) checksum algorithm
1666767634.061245 ManjaroKDE kernel: BTRFS info (device sda2): using free space tree
1666767634.061249 ManjaroKDE kernel: BTRFS info (device sda2): bdev /dev/sda2 errs: wr 0, rd 0, flush 0, corrupt 3072, gen 0
1666767634.061549 ManjaroKDE kernel: BTRFS info (device sda2: state M): using free space tree
1666767876.825905 ManjaroKDE kernel: BTRFS info (device sda2): scrub: started on devid 1
1666767885.649243 ManjaroKDE kernel: BTRFS info (device sda2): scrub: finished on devid 1 with status: 0
```

If I add the option `--lines 1`,  that means I want to get the last line of `journalctl --grep "BTRFS"`, 
```
$ journalctl --output=short-unix --dmesg -p 6  --grep "BTRFS" --lines 1
1666767885.649243 ManjaroKDE kernel: BTRFS info (device sda2): scrub: finished on devid 1 with status: 0
```

### Unexpected behaviour you saw

If I add the option `--lines 1`,  but I got the real result: "No entries":
```
$ journalctl --output=short-unix --dmesg -p 6  --grep "BTRFS" --lines 1
-- No entries --
```

Because the last line 1 does not contain "BTRFS".
```
$ journalctl --output=short-unix --dmesg -p 6  --line 1
1666771587.845724 ManjaroKDE kernel: [drm:vmw_msg_ioctl [vmwgfx]] *ERROR* Failed to open channel.
```

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by YHNdnzj**
Previously, we skip the entries before `arg_lines` unconditionally, which doesn't behave correctly when used with `--grep`.

After this commit, when a pattern is specified, we don't skip the entries early, but rely on the count of lines shown to tell us when to stop. To achieve that we would search backwards instead.

Fixes #25147

### CODE REVIEW

**Comment by YHNdnzj** [comment]
Another method is to store the matched entries in a set to be printed out later, but that would be more complex. I'm not sure if that's worth it.

File: src/journal/journalctl.c [hunk 1]
```diff
@@ -1084,6 +1084,11 @@ static int parse_argv(int argc, char *argv[]) {
                 r = pattern_compile_and_log(arg_pattern, arg_case, &arg_compiled_pattern);
                 if (r < 0)
                         return r;
+
+                /* When --grep is used along with --lines, we don't know how many lines we can print.
+                 * So we search backwards and count until enough lines have been printed or we hit the head. */
+                if (arg_lines)
```
Comment (yuwata) [inline src/journal/journalctl.c]: `arg_lines` is not a boolean, and can be negative. Maybe, `arg_lines >= 0`?

**Comment by yuwata** [comment]
I think the correct fix should be #26482.

**Review by yuwata — APPROVED** [review]
After reconsidering the PR, now LGTM.

One minor request.

**Comment by cgwalters** [comment]
The fix here broke some test code we have in rpm-ostree, which uses `--cursor` along with `-n 1` and `--grep`:
https://github.com/coreos/rpm-ostree/blob/8b1980adf1a9419a33718422efd108a0fc42ee88/tests/kolainst/destructive/cached-sigs#L33

```
[root@qemu0 ~]# journalctl -q -n 1 -u rpm-ostreed --after-cursor 's=58b57b928f404485a0f1b66e1b16c518;i=9c9;b=5a34fd9287534932818757e622df459f;m=137fa06;t=5f6a72c0de1a7;x=d61e61eb8508f5ac' '--grep=signature variant cache miss'
[root@qemu0 ~]# journalctl -q -u rpm-ostreed --after-cursor 's=58b57b928f404485a0f1b66e1b16c518;i=9c9;b=5a34fd9287534932818757e622df459f;m=137fa06;t=5f6a72c0de1a7;x=d61e61eb8508f5ac' '--grep=signature variant cache miss'
Mar 11 22:12:22 qemu0 rpm-ostree[1824]: 2023-03-11T22:12:22.663046Z DEBUG rpmostree_rust::daemon: signature variant cache miss for (fedora, 2848635589fe642e4b89e98b7cfc06eb844fd6dcb985a7673e797eaaf85aeaa1)
[root@qemu0 ~]# 
```

I think the problem here is that `--after-cursor` and `--reverse` collectively narrow the search range to nothing?

In our case, I can hack around this by dropping the `-n 1` and piping to `head -1`.
