### PR TITLE
network: add more log messages

### LINKED ISSUE #9759: If system has invalid hostname, systemd-networkd dhcpv4 does not run and obscure error message is generated
Systemd 239

If systemd-networkd is ran with an invalid hostname  an obscure error message is generated and is very difficult to debug why it is failing.
Steps to reproduce:

**An invalid hostname can either be compiled into the kernel or set from the command line:**
`# echo "Invalid hostname!"> /proc/sys/kernel/hostname `
**run systemd-networkd:**
`# SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-networkd`
**observe obscure error message**
```
ens2: found matching network '/usr/lib/systemd/network/80-dhcp.network'
sd-netlink: callback failed: Invalid argument
Got message type=signal sender=org.freedesktop.DBus.Local destination=n/a path=/org/freedesktop/DBus/Local interface=org.freedesktop.DBus.Local member=Connected cookie=4294967295 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
```
It would be nice to have an error message or handle this more gracefully.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #9759.

### CODE REVIEW

**Comment by yuwata** [comment]
Should we also mention in the man page that what is the valid hostname for DHCP clients?

File: src/network/networkd-dhcp6.c [hunk 1]
```diff
@@ -468,60 +468,58 @@ int dhcp6_configure(Link *link) {
                 return 0;
 
         r = sd_dhcp6_client_new(&client);
+        if (r == -ENOMEM)
+                return log_oom();
```
Comment (keszybz) [inline src/network/networkd-dhcp6.c:472]: I don't think this needs to be special-cased, the generic message is good enough.

**Comment by keszybz** [comment]
> Should we also mention in the man page that what is the valid hostname for DHCP clients?

We should...
