### PR TITLE
time-util: make parse_timestamp() set 0 if the input is very old date

### LINKED ISSUE #6290: Use since argument on journalctl with very old date doesn't return the logs
I am not sure if it is a bug, I tried to search documentation about date limitation, or range, but couldn't find anything.

### Submission type
 - Bug report

### systemd version the issue has been seen with

```shell
:~$ systemd --version
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
```

### Used distribution

```shell
:~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

### In case of bug report: Expected behaviour you didn't see

As you can see below, using a "newer" date it returns `650` lines, but using an older date it doesn't return anything.
```shell
:~$ sudo journalctl --no-pager -au docker --since "2000-01-01" | wc -l
650

:~$ sudo journalctl --no-pager -au docker --since "1900-01-01"
-- No entries --
```

### In case of bug report: Unexpected behaviour you saw

> See it above please

### In case of bug report: Steps to reproduce the problem

> See it above please

### PR DESCRIPTION
**Pull request by yuwata**
If the input is older than "1970-01-01 UTC", then `parse_timestamp()`
fails and returns -EINVAL. However, if the input is e.g. `-100years`,
then the function succeeds and sets `usec = 0`.
This commit makes the function also succeed for old dates and set
`usec = 0`.

Fixes #6290.

### CODE REVIEW

File: src/basic/time-util.c [hunk 1]
```diff
@@ -847,13 +847,17 @@ int parse_timestamp(const char *t, usec_t *usec) {
 
 from_tm:
         x = mktime_or_timegm(&tm, utc);
-        if (x < 0)
+        if (x == (time_t)-1)
```
Comment (keszybz) [inline src/basic/time-util.c]: I'd put a space before "-", but OK.

**Comment by keszybz** [comment]
× xenial-i386
```
3 years 3 months ago
Assertion 'parse_timestamp(p, &t) >= 0' failed at ../src/test/test-date.c:50, function test_should_parse(). Aborting.
FAIL test-date (exit status: 134)
```
PTAL.

**Comment by keszybz** [comment]
```cc
In file included from ../src/basic/macro.h:414:0,
                 from ../src/basic/alloc-util.h:27,
                 from ../src/test/test-date.c:22:
../src/test/test-date.c: In function ‘test_should_parse’:
../src/test/test-date.c:52:18: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 8 has type ‘usec_t {aka long long unsigned int}’ [-Werror=format=]
         log_info("\"%s\" → \"@%lu\"", p, t);
                  ^
../src/basic/log.h:230:76: note: in definition of macro ‘log_full_errno_realm’
                                              __FILE__, __LINE__, __func__, __VA_ARGS__) \
                                                                            ^
../src/basic/log.h:237:30: note: in expansion of macro ‘log_full_errno’
 #define log_full(level, ...) log_full_errno((level), 0, __VA_ARGS__)
                              ^
../src/basic/log.h:241:28: note: in expansion of macro ‘log_full’
 #define log_info(...)      log_full(LOG_INFO,    __VA_ARGS__)
                            ^
../src/test/test-date.c:52:9: note: in expansion of macro ‘log_info’
         log_info("\"%s\" → \"@%lu\"", p, t);
         ^
../src/test/test-date.c: In function ‘test_should_fail’:
../src/test/test-date.c:62:26: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 8 has type ‘usec_t {aka long long unsigned int}’ [-Werror=format=]
                 log_info("\"%s\" → \"@%lu\" (unexpected)", p, t);
                          ^
../src/basic/log.h:230:76: note: in definition of macro ‘log_full_errno_realm’
                                              __FILE__, __LINE__, __func__, __VA_ARGS__) \
                                                                            ^
../src/basic/log.h:237:30: note: in expansion of macro ‘log_full_errno’
 #define log_full(level, ...) log_full_errno((level), 0, __VA_ARGS__)
                              ^
../src/basic/log.h:241:28: note: in expansion of macro ‘log_full’
 #define log_info(...)      log_full(LOG_INFO,    __VA_ARGS__)
                            ^
../src/test/test-date.c:62:17: note: in expansion of macro ‘log_info’
                 log_info("\"%s\" → \"@%lu\" (unexpected)", p, t);
                 ^
cc1: some warnings being treated as errors
Makefile:16352: recipe for target 'src/test/test-date.o' failed
```

**Comment by yuwata** [comment]
@keszybz Sorry for so many broken commits. I did not have i386 build environment. Now I have both i686 and x86_64 mock environments and systemd with the commit is successfully built on them. I hope it also passes the xenial-i386 CI test.

File: src/basic/time-util.c [hunk 2]
```diff
@@ -847,19 +847,23 @@ int parse_timestamp(const char *t, usec_t *usec) {
 
 from_tm:
         x = mktime_or_timegm(&tm, utc);
-        if (x < 0)
-                return -EINVAL;
+        if (x == (time_t) -1)
+                return -EOVERFLOW;
```
Comment (poettering) [inline src/basic/time-util.c:851]: uh, i am not sure i like this. this creates an ambiguity: a negative time_t is permitted, except if it happens to be -1, in which case it is refused. (or in other words: "1969-12-31 23:59:59" will fail to parse but "1969-12-31 23:59:58" and "1970-01-01 00:00:00" will succeed)

I think we should really fail in all cases of "negative" times here. For our purposes times before 1970 make very little sense, and we should just cleanly error out on all of them.
