### PR TITLE
udev: fix issue #13976

### LINKED ISSUE #13976: v243 breaks lvremove of snapshots
**systemd version the issue has been seen with**
> v243

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
```
# lvcreate -s --size=5116M --name=mysql_snapshot /dev/SQL/mysql
  Logical volume "mysql_snapshot" created.
# lvremove -f /dev/SQL/mysql_snapshot 
  Logical volume "mysql_snapshot" successfully removed
```

**Unexpected behaviour you saw**
```
# lvcreate -s --size=5116M --name=mysql_snapshot /dev/SQL/mysql
  Logical volume "mysql_snapshot" created.
# lvremove -f /dev/SQL/mysql_snapshot
```
Here the lvremove hangs and I have to "kill -9" it. Oddly enough a second lvremove then is "successful":
```
# lvremove -f /dev/SQL/mysql_snapshot 
  WARNING: Reading VG SQL from disk because lvmetad metadata is invalid.
  Logical volume "mysql_snapshot" successfully removed
```

**Steps to reproduce the problem**
1. Create a volume group, say SQL.
2. `lvcreate -L 5G -n mysql SQL`
3. `mkfs.ext4 /dev/SQL/mysql`
4. `lvcreate -s --size=5116M --name=mysql_snapshot /dev/SQL/mysql`
5. `lvremove -f /dev/SQL/mysql_snapshot`
6. As this lvremove does not terminate, `kill -9` it.
7. `lvremove -f /dev/SQL/mysql_snapshot`
  `WARNING: Reading VG RAID from disk because lvmetad metadata is invalid.
  Logical volume "mysql_snapshot" successfully removed`

**Workaround**
Downgrade to systemd-242.

### PR DESCRIPTION
**Pull request by yuwata**
During an add or change event, the device may be disconnected.

Closes #13976.

### CODE REVIEW

File: src/udev/udev-node.c [hunk 1]
```diff
@@ -296,8 +296,11 @@ static int node_permissions_apply(sd_device *dev, bool apply_mac,
         else
                 mode |= S_IFCHR;
 
-        if (lstat(devnode, &stats) < 0)
+        if (lstat(devnode, &stats) < 0) {
+                if (errno == ENOENT)
+                        return 0; /* this is necessarily racey, so ignore missing the device */
                 return log_device_debug_errno(dev, errno, "cannot stat() node %s: %m", devnode);
+        }
```
Comment (poettering) [inline src/udev/udev-node.c:303]: looks good, but what about the operation below? shouldn't they all just fail silently on ENOENT? i.e. the chmod_and_chown() and so on?

Comment (yuwata) [reply src/udev/udev-node.c:303]: Hmm??? On ENOENT, this return with 0, so `chmod_and_chown()` is not called.

Comment (poettering) [reply src/udev/udev-node.c:303]: well, but what happens if during the lstat() the device is still there, but then during the chmod() it is gone? I mean, we never know when precisely the device disappears, could be any time, hence we should handle it on all operations?

(Alternatively we could of course operate on an open(O_PATH) fd instead, so that removal doesn't invalidate the object for us)

Comment (yuwata) [reply src/udev/udev-node.c:303]: I see. I understand. Now, ENOENT in `chmod_and_chown()` or later operations are also ignored. PTAL.

**Comment by keszybz** [comment]
LGTM.

**Comment by keszybz** [comment]
bionic-i386 timed out in tests, looks unrelated.
