### PR TITLE
journal: fix user journal corruption on rotation

### LINKED ISSUE #24150: Corrupted user journal files
### systemd version the issue has been seen with

systemd-251.3-1

### Used distribution

Arch Linux

### Linux kernel version used

5.18.14.arch1-1

### CPU architectures issue was seen on

x86_64

### Component

journalctl, systemd-journald

### Expected behaviour you didn't see

`journalctl --verify` does not show any errors.

### Unexpected behaviour you saw

`SYSTEMD_LOG_LEVEL=debug journalctl --verify` shows the following error:

```
Failed to open journal file /var/log/journal/592150cf5ad44523af127588741e363c/user-1000@c1c3d1e59afc4735b7e0ce6b9692359a-0000000000000000-0000000000000000.journal: Bad message
Journal file /var/log/journal/592150cf5ad44523af127588741e363c/user-1000@c1c3d1e59afc4735b7e0ce6b9692359a-0000000000000000-0000000000000000.journal corrupted, ignoring file.
```

**Note:**

- the underlying filesystem is BTRFS on an NVMe SSD
- the filesystem is fine (checked by `btrfs scrub`ing)
- SMART stats are perfectly fine for the disk
- the system has not been rebooted, so it's not an unclean shutdown or power loss
- the corrupted file exists and has a size of 3.6 MiB
- file permissions seem okay, other applications can read it

### Steps to reproduce the problem

None, actually, simply wait a couple of days (usually 1 or 2).

I've got the feeling it always happens when the user journal is rotated, but I'm not sure.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ SYSTEMD_LOG_LEVEL=debug journalctl --verify
Considering root directory '/run/log/journal'.
Root directory /run/log/journal added.
Considering root directory '/var/log/journal'.
Root directory /var/log/journal added.
Considering directory '/var/log/journal/592150cf5ad44523af127588741e363c'.
Directory /var/log/journal/592150cf5ad44523af127588741e363c added.
Journal effective settings seal=no keyed_hash=yes compress=yes compress_threshold_bytes=8B
File /var/log/journal/592150cf5ad44523af127588741e363c/system@541c450c00004e93bde6cc3f2d49287d-000000000001a516-0005e28ccf122b38.journal added.
(...)
File /var/log/journal/592150cf5ad44523af127588741e363c/user-1000@c1c3d1e59afc4735b7e0ce6b9692359a-0000000000032699-0005e4de62032bc5.journal added.
File /var/log/journal/592150cf5ad44523af127588741e363c/system.journal added.
File /var/log/journal/592150cf5ad44523af127588741e363c/system@541c450c00004e93bde6cc3f2d49287d-000000000003273c-0005e4e23373c762.journal added.
File /var/log/journal/592150cf5ad44523af127588741e363c/user-1000.journal added.
Failed to open journal file /var/log/journal/592150cf5ad44523af127588741e363c/user-1000@c1c3d1e59afc4735b7e0ce6b9692359a-0000000000000000-0000000000000000.journal: Bad message
Journal file /var/log/journal/592150cf5ad44523af127588741e363c/user-1000@c1c3d1e59afc4735b7e0ce6b9692359a-0000000000000000-0000000000000000.journal corrupted, ignoring file.
PASS: /var/log/journal/592150cf5ad44523af127588741e363c/system@541c450c00004e93bde6cc3f2d49287d-000000000001a516-0005e28ccf122b38.journal
(...)
PASS: /var/log/journal/592150cf5ad44523af127588741e363c/user-1000.journal
Root directory /run/log/journal removed.
Directory /var/log/journal/592150cf5ad44523af127588741e363c removed.
Root directory /var/log/journal removed.
mmap cache statistics: 83578751 context cache hit, 56628 window list hit, 641282 miss
```

### LINKED ISSUE #31222: User journal corruption on btrfs
This is something I've been seeing in my _VM farm_ for a while and never have gotten into debugging it properly until now.

I use Vagrant a lot for my test VMs - the important bits are that `vagrant ssh` will log you into the VM as a `vagrant` user and I usually follow this with `sudo su -` to get a root shell.

While reproducing some issues involving grepping journal (like https://github.com/systemd/systemd/issues/30886), I quite often noticed `journalctl` complaining about corrupted journals. After collecting some data I found out that this seems to affect only VMs that run btrfs (Arch, Fedora), it's always the user journal, and it _always_ involves the _unpriv_user_ -> _root_ "session chain". Invoking `journalctl --rotate` from the nested root session is enough to corrupt the just archived journal.

I managed to minimize it into a very simple reproducer using our test suite:
```diff
diff --git a/test/TEST-04-JOURNAL/test.sh b/test/TEST-04-JOURNAL/test.sh
index 42574ce8ea..db7b4bc6a8 100755
--- a/test/TEST-04-JOURNAL/test.sh
+++ b/test/TEST-04-JOURNAL/test.sh
@@ -27,6 +27,10 @@ test_append_files() {
         mkdir -p "$dropin_dir"
         printf '[Service]\nStandardOutput=journal+console\nStandardError=journal+console' >"$dropin_dir/99-stdout.conf"
     fi
+
+    image_install sudo
+    inst /etc/sudoers
+    inst_recursive /usr/libexec/sudo/
 }
 
 do_test "$@"
diff --git a/test/test-functions b/test/test-functions
index 80fdcd26b9..cdae1e97b0 100644
--- a/test/test-functions
+++ b/test/test-functions
@@ -2099,7 +2099,7 @@ install_testuser() {
     # create unprivileged user for user manager tests
     mkdir -p "${initdir:?}/etc/sysusers.d"
     cat >"$initdir/etc/sysusers.d/testuser.conf" <<EOF
-u testuser    4711     "Test User" /home/testuser
+u testuser    4711     "Test User" /home/testuser /bin/bash
 EOF
 
     mkdir -p "$initdir/home/testuser"
diff --git a/test/units/testsuite-04.user-corrupt.sh b/test/units/testsuite-04.user-corrupt.sh
new file mode 100755
index 0000000000..74453497f1
--- /dev/null
+++ b/test/units/testsuite-04.user-corrupt.sh
@@ -0,0 +1,31 @@
+#!/usr/bin/env bash
+# SPDX-License-Identifier: LGPL-2.1-or-later
+set -eux
+set -o pipefail
+
+mkdir -p /etc/sudoers.d/
+echo "testuser ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/testuser
+
+REPRO_SCRIPT="$(mktemp)"
+
+cat >"$REPRO_SCRIPT" <<\EOF
+#!/bin/bash
+set -eux
+set -o pipefail
+
+journalctl --rotate --vacuum-files=1
+# Nuke all archived journals, so we start with a clean slate
+rm -f /var/log/journal/$(</etc/machine-id)/system@*.journal
+rm -f /var/log/journal/$(</etc/machine-id)/user-*@*.journal
+journalctl --header | grep path
+
+for i in {0..10}; do
+    journalctl --rotate
+    journalctl --sync
+    SYSTEMD_LOG_LEVEL=debug journalctl -n1 -q
+    (! journalctl -n0 -q |& grep corrupted)
+done
+EOF
+chmod +x "$REPRO_SCRIPT"
+
+systemd-run --wait --pipe --user -M testuser@ -- sudo "$REPRO_SCRIPT"
```

```
# make -C test/TEST-04-JOURNAL/ clean setup run TEST_MATCH_SUBTEST=user-corrupt TEST_NO_QEMU=1 BUILD_DIR=$PWD/build KERNEL_APPEND=systemd.default_standard_output=journal+console FSTYPE=btrfs
...
[945170.307432] testsuite-04.sh[97]: + journalctl --header
[945170.307748] testsuite-04.sh[98]: + grep path
[945170.311593] testsuite-04.sh[98]: File path: /var/log/journal/9059aaf50f1741469b471cee9e6056be/system.journal
[945170.311593] testsuite-04.sh[98]: File path: /var/log/journal/9059aaf50f1741469b471cee9e6056be/user-4711.journal
[945170.311849] testsuite-04.sh[91]: + for i in {0..10}
[945170.311926] testsuite-04.sh[91]: + journalctl --rotate
[945170.444078] testsuite-04.sh[91]: + journalctl --sync
[945170.449523] testsuite-04.sh[91]: + SYSTEMD_LOG_LEVEL=debug
[945170.449523] testsuite-04.sh[91]: + journalctl -n1 -q
[945170.471060] testsuite-04.sh[105]: Considering root directory '/run/log/journal'.
[945170.471060] testsuite-04.sh[105]: Root directory /run/log/journal added.
[945170.471060] testsuite-04.sh[105]: Considering root directory '/var/log/journal'.
[945170.471060] testsuite-04.sh[105]: Root directory /var/log/journal added.
[945170.471060] testsuite-04.sh[105]: Considering directory '/var/log/journal/9059aaf50f1741469b471cee9e6056be'.
[945170.471060] testsuite-04.sh[105]: Directory /var/log/journal/9059aaf50f1741469b471cee9e6056be added.
[945170.471060] testsuite-04.sh[105]: Journal effective settings seal=no keyed_hash=yes compress=ZSTD compress_threshold_bytes=8B
[945170.471060] testsuite-04.sh[105]: File /var/log/journal/9059aaf50f1741469b471cee9e6056be/system.journal added.
[945170.471060] testsuite-04.sh[105]: File /var/log/journal/9059aaf50f1741469b471cee9e6056be/system@23f5950dc21b4fd4be3d5391ec94d0e1-0000000000000a8b-000610b8052a115a.journal added.
[945170.471060] testsuite-04.sh[105]: File /var/log/journal/9059aaf50f1741469b471cee9e6056be/user-4711.journal added.
[945170.471060] testsuite-04.sh[105]: Failed to open journal file /var/log/journal/9059aaf50f1741469b471cee9e6056be/user-4711@23f5950dc21b4fd4be3d5391ec94d0e1-0000000000000000-0000000000000000.journal: Bad message
[945170.471060] testsuite-04.sh[105]: Journal file /var/log/journal/9059aaf50f1741469b471cee9e6056be/user-4711@23f5950dc21b4fd4be3d5391ec94d0e1-0000000000000000-0000000000000000.journal corrupted, ignoring file.
[945170.471060] testsuite-04.sh[105]: Journal filter: none
[945170.471060] testsuite-04.sh[105]: Root directory /var/log/journal removed.
[945170.471060] testsuite-04.sh[105]: Root directory /run/log/journal removed.
[945170.471060] testsuite-04.sh[105]: Directory /var/log/journal/9059aaf50f1741469b471cee9e6056be removed.
[945170.471060] testsuite-04.sh[105]: mmap cache statistics: 234 category cache hit, 8 window list hit, 4 miss
[945170.471060] testsuite-04.sh[105]: Feb 06 16:13:27 H testsuite-04.sh[91]: + journalctl --sync
[945170.494490] testsuite-04.sh[107]: + journalctl -n0 -q
[945170.494749] (sd-pam)[77]: pam_systemd(login:session): Failed to release session: Access denied
[945170.494841] testsuite-04.sh[108]: + grep corrupted
[945170.494841] testsuite-04.sh[108]: Journal file /var/log/journal/9059aaf50f1741469b471cee9e6056be/user-4711@23f5950dc21b4fd4be3d5391ec94d0e1-0000000000000000-0000000000000000.journal corrupted, ignoring file.
[945170.495458] testsuite-04.sh[60]: Finished with result: exit-code
[945170.495458] testsuite-04.sh[60]: Main processes terminated with: code=exited/status=1
[945170.495458] testsuite-04.sh[60]: Service runtime: 439ms
[945170.495458] testsuite-04.sh[60]: CPU time consumed: 9ms
[945170.495458] testsuite-04.sh[60]: Memory peak: 2.9M (swap: 0B)
[945170.496155] testsuite-04.sh[51]: + echo 'Subtest /usr/lib/systemd/tests/testdata/units/testsuite-04.user-corrupt.sh failed'
[945170.496155] testsuite-04.sh[51]: Subtest /usr/lib/systemd/tests/testdata/units/testsuite-04.user-corrupt.sh failed
[945170.496155] testsuite-04.sh[51]: + return 1
[945170.496520] systemd[69]: run-u0.service: Failed with result 'exit-code'.
[945170.499946] dbus-broker[64]: A security policy denied :1.15 to send method call /org/freedesktop/login1:org.freedesktop.login1.Manager.ReleaseSession to org.freedesktop.login1.
[945170.500688] systemd[1]: testsuite-04.service: Failed with result 'exit-code'.
[945170.500892] systemd[1]: Failed to start testsuite-04.service.
```

Here's one example journal from Fedora Rawhide with the latest main (ATTOW): https://mrc0mmand.fedorapeople.org/user-1000-rawhide-btrfs-corrupted.journal

As mentioned above, this seems to happen only with btrfs - xfs or ext4 (cc @bluca ;)) seem to work fine.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #24150.
Fixes #31222.

### CODE REVIEW

**Comment by vcaputo** [comment]
At a glance it looks sane, though I'm unclear on the necessity of the post_change_timer leak commit - is that just hypothetical or a real leak?

**Comment by yuwata** [comment]
> At a glance it looks sane, though I'm unclear on the necessity of the post_change_timer leak commit - is that just hypothetical or a real leak?

Should be hypothetical, as we always close the file with `journal_file_offline_close()`.

**Comment by yuwata** [comment]
@mrc0mmand On Arch,
```
W: Failed to install '/etc/crypto-policies/back-ends/gnutls.config'
I: Skipping program /etc/crypto-policies/back-ends/gnutls.config as it cannot be found and is flagged to be optional
stat: cannot statx '/usr/libexec/sudo/': No such file or directory
```
Could you update the test code and force-push to this branch?

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by mrc0mmand** [comment]
> @mrc0mmand On Arch,
> 
> ```
> W: Failed to install '/etc/crypto-policies/back-ends/gnutls.config'
> I: Skipping program /etc/crypto-policies/back-ends/gnutls.config as it cannot be found and is flagged to be optional
> stat: cannot statx '/usr/libexec/sudo/': No such file or directory
> ```
> 
> Could you update the test code and force-push to this branch?

I rewrote the test case so it doesn't need sudo at all (which is very obvious in hindsight). It still reproduces the issue if I revert [49b643e](https://github.com/systemd/systemd/pull/31311/commits/49b643e25f42aee73814183c45b26c928f10aeab) and passes otherwise. Thank you!

File: src/shared/journal-file-util.c [hunk 1]
```diff
@@ -512,23 +511,19 @@ int journal_file_open_reliably(
...
-                                      file_flags, 0, compress_threshold_bytes, NULL,
-                                      mmap_cache, NULL, &old_file);
-                if (r < 0)
-                        log_debug_errno(r, "Failed to continue sequence from file %s, ignoring: %m", fname);
-                else
-                        template = old_file;
-        }
+        /* The file is corrupted. Try opening it read-only as the template before rotating to inherit its
+         * sequence number and ID. */
+        r = journal_file_open(-1, fname,
```
Comment (poettering) [inline src/shared/journal-file-util.c]: when you touch this, you could also change the first arg to `-EBADF`

File: src/libsystemd/sd-journal/journal-file.c [hunk 2]
```diff
@@ -4344,6 +4344,11 @@ int journal_file_archive(JournalFile *f, char **ret_previous_path) {
         if (!endswith(f->path, ".journal"))
                 return -EINVAL;
 
+        if (le64toh(f->header->head_entry_seqnum) == 0)
+                /* We may asynchronously copy file later e.g. on btrfs. During copying, if
+                 * journal_directory_vacuum() is called, a broken archive file may be created. */
```
Comment (poettering) [inline src/libsystemd/sd-journal/journal-file.c]: hmm, i don't grok this comment? also, it doesn't say anything about that we shouldn't archive empty journal files (which the git commit msg says, and i think this belongs in the comment too)

File: src/libsystemd/sd-journal/journal-file.c [hunk 3]
```diff
@@ -4344,6 +4344,11 @@ int journal_file_archive(JournalFile *f, char **ret_previous_path) {
         if (!endswith(f->path, ".journal"))
                 return -EINVAL;
 
+        if (le64toh(f->header->head_entry_seqnum) == 0)
```
Comment (poettering) [inline src/libsystemd/sd-journal/journal-file.c]: hmm, i think a check of `f->header->n_objects` being zero is a lot more obvious, no?

**Comment by poettering** [comment]
makes sense to me, but the comment i find confusing.

**Comment by DaanDeMeyer** [comment]
@poettering When on btrfs we copy the file as part of archiving it to make sure it gets compressed by btrfs (by enabling COW). We don't do this for other filesystems.

**Comment by poettering** [comment]
> @poettering When on btrfs we copy the file as part of archiving it to make sure it gets compressed by btrfs (by enabling COW). We don't do this for other filesystems.

But why would that copying trigger a corruption if the journal is empty?

**Comment by poettering** [comment]
(stuff like this should probably be in a comment in the code btw)

**Comment by bluca** [comment]
The CI is all green, which is something that only happens once every 3 years. Stop nitpicking and merge it before it goes red again!

**Comment by mrc0mmand** [comment]
I hate to be the _party pooper_ here, but while playing with btrfs in #31318 I came across another batch of corrupted journals even with this PR applied, this time when --vacuum-...= is involed:

```
# make -C test/TEST-04-JOURNAL/ clean setup run TEST_MATCH_SUBTEST=journal-corrupt KERNEL_APPEND=systemd.journald.forward_to_console=1 TEST_NO_NSPAWN=1 BUILD_DIR=$PWD/build FSTYPE=btrfs
...
# journalctl --file /var/tmp/systemd-tests/systemd-test.BDz1rp/system.journal -o short-monotonic --no-hostname
...
[    6.435085] systemd-journald[643]: System Journal (/var/log/journal/f56f3b5e001841b7984681d95027aaad) is 29.1M, max 76.8M, 47.6M free.
[    6.445523] systemd-journald[643]: Received client request to rotate journal, rotating.
[    6.454349] systemd-journald[643]: Deleted empty archived journal /var/log/journal/f56f3b5e001841b7984681d95027aaad/user-4711@72ff175f89a343aca99b82769be36173-0000000000001802-0006115860904198.journal (4.0K).
[    6.454382] systemd-journald[643]: Vacuuming done, freed 4.0K of archived journals from /var/log/journal/f56f3b5e001841b7984681d95027aaad.
[    6.444216] testsuite-04.sh[862]: + grep path
[    6.444216] testsuite-04.sh[862]: File path: /run/log/journal/1588e1d9d0b74acdbaada907b163b837/system.journal
[    6.444216] testsuite-04.sh[862]: File path: /var/log/journal/f56f3b5e001841b7984681d95027aaad/system.journal
[    6.444216] testsuite-04.sh[862]: File path: /var/log/journal/f56f3b5e001841b7984681d95027aaad/user-4711.journal
[    6.450194] journalctl[855]: Deleted archived journal /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-00000000000015df-000611586087d7fa.journal (308.0K).
[    6.453313] testsuite-04.sh[726]: + for _ in {0..9}
[    6.453313] testsuite-04.sh[726]: + journalctl --rotate --vacuum-files=1
[    6.455653] journalctl[855]: Deleted archived journal /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-0000000000001601-000611586088f788.journal (312.0K).
[    6.458699] journalctl[855]: Deleted archived journal /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-0000000000001625-0006115860899b83.journal (312.0K).
[    6.461600] journalctl[855]: Deleted archived journal /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-000000000000164a-00061158608a4c15.journal (292.0K).
[    6.464484] journalctl[855]: Deleted archived journal /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-0000000000001650-00061158608b49a7.journal (316.0K).
[    6.467149] testsuite-04.sh[726]: + journalctl --sync
[    6.468311] journalctl[855]: Deleted archived journal /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-000000000000167f-00061158608c1a76.journal (328.0K).
[    6.471591] journalctl[855]: Deleted archived journal /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-00000000000016bd-00061158608cec9b.journal (316.0K).
[    6.482013] systemd-journald[643]: Received client request to sync journal.
[    6.474407] journalctl[855]: Deleted archived journal /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-00000000000016e5-00061158608da274.journal (316.0K).
[    6.476895] journalctl[855]: Deleted archived journal /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-000000000000170e-00061158608e5b86.journal (508.0K).
[    6.479522] journalctl[855]: Deleted archived journal /var/log/journal/f56f3b5e001841b7984681d95027aaad/user-4711@72ff175f89a343aca99b82769be36173-0000000000001802-0006115860904198.journal (8.0M).
[    6.482125] journalctl[855]: Vacuuming done, freed 13.1M of archived journals from /var/log/journal/f56f3b5e001841b7984681d95027aaad.
[    6.483986] journalctl[855]: Vacuuming done, freed 0B of archived journals from /run/log/journal.
[    6.485483] journalctl[861]: Journal file /var/log/journal/f56f3b5e001841b7984681d95027aaad/user-4711@72ff175f89a343aca99b82769be36173-0000000000001802-0006115860904198.journal corrupted, ignoring file.
[    6.488483] journalctl[863]: Journal file /var/log/journal/f56f3b5e001841b7984681d95027aaad/user-4711@72ff175f89a343aca99b82769be36173-0000000000001802-0006115860904198.journal corrupted, ignoring file.
[    6.491461] journalctl[863]: Vacuuming done, freed 0B of archived journals from /run/log/journal.
[    6.492867] journalctl[863]: Vacuuming done, freed 0B of archived journals from /run/log/journal/1588e1d9d0b74acdbaada907b163b837.
[    6.494737] journalctl[863]: Vacuuming done, freed 0B of archived journals from /var/log/journal.
[    6.496135] journalctl[863]: Deleted archived journal /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-000000000000187d-000611586090e79d.journal (8.0M).
[    6.498661] journalctl[863]: Vacuuming done, freed 8.0M of archived journals from /var/log/journal/f56f3b5e001841b7984681d95027aaad.
[    6.501929] testsuite-04.sh[726]: + SYSTEMD_LOG_LEVEL=debug
[    6.501929] testsuite-04.sh[726]: + journalctl -n1 -q
[    6.509375] journalctl[868]: Considering root directory '/run/log/journal'.
[    6.509658] journalctl[868]: Root directory /run/log/journal added.
[    6.509721] testsuite-04.sh[868]: Feb 14 15:32:15 H testsuite-04.sh[726]: + SYSTEMD_LOG_LEVEL=debug
[    6.511623] journalctl[868]: Considering directory '/run/log/journal/1588e1d9d0b74acdbaada907b163b837'.
[    6.511689] journalctl[868]: Directory /run/log/journal/1588e1d9d0b74acdbaada907b163b837 added.
[    6.511743] journalctl[868]: Journal effective settings seal=no keyed_hash=yes compress=ZSTD compress_threshold_bytes=8B
[    6.511804] journalctl[868]: File /run/log/journal/1588e1d9d0b74acdbaada907b163b837/system.journal added.
[    6.511853] testsuite-04.sh[870]: + journalctl -n0 -q
[    6.513453] journalctl[868]: Considering root directory '/var/log/journal'.
[    6.513521] testsuite-04.sh[871]: + grep corrupted
[    6.514743] journalctl[868]: Root directory /var/log/journal added.
[    6.514805] journalctl[868]: Considering directory '/var/log/journal/f56f3b5e001841b7984681d95027aaad'.
[    6.514858] journalctl[868]: Directory /var/log/journal/f56f3b5e001841b7984681d95027aaad added.
[    6.514910] journalctl[868]: File /var/log/journal/f56f3b5e001841b7984681d95027aaad/user-4711.journal added.
[    6.514966] journalctl[868]: File /var/log/journal/f56f3b5e001841b7984681d95027aaad/system.journal added.
[    6.515025] journalctl[868]: Failed to open journal file /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-000000000000187d-000611586090e79d.journal: Bad message
[    6.515094] journalctl[868]: Journal file /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-000000000000187d-000611586090e79d.journal corrupted, ignoring file.
[    6.518330] journalctl[868]: Journal filter: none
[    6.518388] journalctl[868]: Root directory /run/log/journal removed.
[    6.518431] journalctl[868]: Root directory /var/log/journal removed.
[    6.518469] journalctl[868]: Directory /run/log/journal/1588e1d9d0b74acdbaada907b163b837 removed.
[    6.518510] journalctl[868]: Directory /var/log/journal/f56f3b5e001841b7984681d95027aaad removed.
[    6.518546] journalctl[868]: mmap cache statistics: 115 category cache hit, 7 window list hit, 4 miss
[    6.519958] testsuite-04.sh[871]: Journal file /var/log/journal/f56f3b5e001841b7984681d95027aaad/system@72ff175f89a343aca99b82769be36173-000000000000187d-000611586090e79d.journal corrupted, ignoring file.
[    6.522559] testsuite-04.sh[721]: + echo 'Subtest /usr/lib/systemd/tests/testdata/units/testsuite-04.journal-corrupt.sh failed'
```

(I pushed the updated test case and renamed it, since the corruption is not exclusive to user journals)

**Comment by bluca** [comment]
booo

**Comment by mrc0mmand** [comment]
And as with the original issue, this seems to happen only on btrfs, on ext4 the test passes without issues.

**Comment by poettering** [comment]
i wonder if this might be caused because we copy via read/write/copyfilerange, but we write the file via mmap?

File: src/basic/stat-util.c [hunk 4]
```diff
@@ -275,18 +275,21 @@ int stat_verify_regular(const struct stat *st) {
         if (!S_ISREG(st->st_mode))
                 return -EBADFD;
 
+        if (check_removed && st->st_nlink <= 0)
+                return -EIDRM;
```
Comment (poettering) [inline src/basic/stat-util.c]: hmm, instead of adding a "full" function, we could just return 0 in case of a deleted file and 1 in case of an existing file. Then, callers could handle this on their own?

(just and idea, up to you, "full" is fine too)

**Comment by poettering** [comment]
ah, i get it now!

This issue is caused by unlinkat_deallocate(), i.e. the FALLOC_FL_PUNCH_HOLE stuff it does. i.e. when we vacuum a journal file we not just delete it, we also deallocate all its contents first. we do this because people used to complain that if "journalctl -f" runs continously vacuuming would become ineffective, because that would keep the files opened, and hence pinned and hence if we only do unlink() all its disk space would remain allocated and taking up space. hence we supercharged the vacuuming by not just unlinking but also deallocating its contents first, on file systems that allow it.

But this of course conflicts if the copy takes place at the same time, because then it might copy half the deallocated (hence zero'd out) files and half the original version...

File: src/shared/copy.c [hunk 5]
```diff
@@ -798,6 +798,10 @@ static int fd_copy_regular(
         (void) futimens(fdt, (struct timespec[]) { st->st_atim, st->st_mtim });
         (void) copy_xattr(fdf, NULL, fdt, NULL, copy_flags);
 
+        r = fd_verify_regular_full(fdf, /* check_removed = */ true);
```
Comment (poettering) [inline src/shared/copy.c]: tbh i think this should be a new helper, unrelated from verify_regular, after all an inode won't change its type half-way, hence we don't really need to check the type again which however the primary purpose of fd_verify_regular() is.

maybe instead add fd_verify_linked() that just returns 0 or -EDRM, and nothing else?

File: src/shared/copy.c [hunk 6]
```diff
@@ -798,6 +798,10 @@ static int fd_copy_regular(
...
+        if (r < 0)
+                return r;
```
Comment (poettering) [inline src/shared/copy.c]: so i think this test only makes sense if used in conjunction with that FALLOC_FL_PUNCH_HOLE delete pattern we have. In the usual case I see no reason why we'd want to add this test, because usually when files are deleted they aren't weirdly destroyed like we do it for the journal vacuuming...

Hence I think this should be hidden behind a new flag, i.e. COPY_VERIFY_LINKED or so? and then only set that in the journal code.

File: src/basic/stat-util.c (hunk 4 above)
Comment (poettering) [reply src/basic/stat-util.c]: (but as dicussed below, maybe don#t add this to stat_verify_regular() at all, but instead add fd_verify_linked() instead, see discussion)

**Comment by poettering** [comment]
the approach to fix this looks very much right to me, but see my comments.

and please add a comment in journal_file_set_offline_internal() that explains the situation, i.e. why COPY_VERIFY_LINKED as flag to copy_file_atomic_full() is really important and matters.

**Comment by yuwata** [comment]
@poettering Thank you for the suggestions. I hope all suggestions are applied. PTAL!

File: src/shared/copy.h [hunk 7]
```diff
@@ -30,6 +30,7 @@ typedef enum CopyFlags {
         COPY_GRACEFUL_WARN = 1 << 15, /* Skip copying file types that aren't supported by the target filesystem */
         COPY_TRUNCATE      = 1 << 16, /* Truncate to current file offset after copying */
         COPY_LOCK_BSD      = 1 << 17, /* Return a BSD exclusively locked file descriptor referring to the copied image/directory. */
+        COPY_VERIFY_LINKED = 1 << 18, /* Check the source file is still liked after copying. */
```
Comment (daandemeyer) [inline src/shared/copy.h]: liked => linked

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by graelo** [comment]
Thanks a lot for investigating and fixing this issue!
