### PR TITLE
pid1: provide a more detailed error message when execution fails

### LINKED ISSUE #5000: Clarify CAPABILITIES exec error "Invalid argument"
### Submission type

  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

229-232

### Used distribution

Arch Linux

This is similar to https://github.com/systemd/systemd/issues/4959

Using [the service file for Caddy webserver](https://github.com/mholt/caddy/blob/466269fd10e2e9a2fb70ef80609dd379a44fbd4b/dist/init/linux-systemd/caddy.service), if I uncomment **AmbientCapabilities=CAP_NET_BIND_SERVICE** I get **Failed at step CAPABILITIES spawning /usr/bin/caddy: Invalid argument**.

Same is observed with this test service:

```
[Service]
ExecStart=/sbin/capsh --print
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_ADMIN
User=nobody
```

Would be great to have a more detailed error appear in journal.

### PR DESCRIPTION
**Pull request by keszybz**
Fixes #5000.

### CODE REVIEW

File: src/core/execute.c [hunk 1]
```diff
@@ -2422,6 +2426,7 @@ static int exec_child(
         r = reset_signal_mask();
         if (r < 0) {
                 *exit_status = EXIT_SIGNAL_MASK;
+                *error_message = strdup("Failed to reset signal mask");
```
Comment (martinpitt) [inline src/core/execute.c:2429]: None of these get checked for ENOMEM, but that should be okay -- the caller handles the case when `error_message` is `NULL`.

File: src/core/execute.c [hunk 2]
```diff
@@ -3072,17 +3118,27 @@ int exec_spawn(Unit *unit,
...
-                                                          exit_status_to_string(exit_status, EXIT_STATUS_SYSTEMD),
-                                                          command->path),
-                                         "EXECUTABLE=%s", command->path,
-                                         NULL);
+                        if (error_message)
+                                log_struct_errno(LOG_ERR, r,
+                                                 LOG_MESSAGE_ID(SD_MESSAGE_SPAWN_FAILED),
+                                                 LOG_UNIT_ID(unit),
+                                                 LOG_UNIT_MESSAGE(unit, "%s: %m",
+                                                                  command->path),
```
Comment (martinpitt) [inline src/core/execute.c]: After all this effort I think it would make sense to actually print the `error_message` :-) I'd actually keep the `%m` in addition, as `error_message` just says the "where?" while %m says the "what?".

Comment (keszybz) [reply src/core/execute.c]: Pfff. /me wanders off to hide in the woods.

(Yeah, %m was supposed to be there. I didn't test the patch, obviously, but the final messages should look like this:

Failed to reset signal mask: %m
Failed to close remaining fds: %m
Execution cancelled: %m
Failed to update environment: %m
Failed to update dynamic user credentials: %m
UID validation failed for \""UID_FMT"\": %m
GID validation failed for \""GID_FMT"\": %m
Failed to determine user credentials: %m
Failed to determine group credentials: %m
Failed to determine supplementary groups: %m
Failed to send user credentials to PID1: %m
Failed to set up stdin: %m
Failed to set up stdout: %m
Failed to set up stderr: %m
Failed to attach to cgroup %s: %m
Failed to write /proc/self/oom_score_adj: %m
Failed to drop capabilities: %m
Failed to apply ambient capabilities (before UID change): %m
Failed to change UID to UID_FMT: %m
Failed to apply ambient capabilities (after UID change): %m
Failed to set SELinux context to %s: %m
Failed to set SMACK process label: %m
Failed to set secure bits: %m
Failed to disable new privileges: %m
Failed to restrict address families: %m
Failed to disable writing to executable memory: %m
Failed to apply realtime restrictions: %m
Failed to apply namespace restrictions: %m
Failed to apply sysctl restrictions: %m
Failed to apply module loading restrictions: %m
Failed to set up private devices: %m
Failed to apply syscall filters: %m
Failed to prepare process arguments: %m
Failed to prepare AppArmor profile change to %s: %m

I think this should be clearer than the previous message in all cases. The executable path is not included, because those errors are *before* the execution, so the binary should not matter.)

File: src/core/execute.c (hunk 1 above)
Comment (keszybz) [reply src/core/execute.c:2429]: Yeah. I now added two comments to explain that.

**Comment by keszybz** [comment]
Updated.

**Comment by keszybz** [comment]
Fails in networkd-test.py. I assume that's unrelated.
