### PR TITLE
network/ndisc: fix coalescing of ndisc routes when multiple router exists

### LINKED ISSUE #33470: IPv6 Compliance RFC4861: Default Router Switch (Hosts Only) [v6LC.2.2.11] - Incorrect nexthop
### systemd version the issue has been seen with

256 and 257~devel-g6efab8c

### Used distribution

Ubuntu 24.04

### Linux kernel version used

6.8.0-35-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

#### IPv6 Conformance Test v6LC.2.2.11: Default Router Switch (Hosts Only).
**Purpose**: Verify that a host maintains at least two routers in its Default Router List and will switch routers when the router in use fails.

#### Network Configuration
```
            TN2
             |
    +--------+--------+
    |                 |
   TR1               TR2
    |                 |
    +----+-------+----+
         |       |
        TN1     HUT
```

| Step | Action | Expected Behaviour of HUT |
|--------|--------|--------|
| 1. | TR1 sends RA `Src=TR1-LLA, Prefix=TN1's Global Prefix, Reachable=10s` | |
| 2. | 5s elapse then TN2 sends Echo request to HUT.| HUT sends NS `target=TR1-LLA` (i.e. who owns `TR1-LLA`?) |
| 3. | TR1 sends NA in response to NS from HUT| |
| 4. | TR2 sends RA `Src=TR2-LLA, Prefix=TN1's Global Prefix, Reachable=10s` | |
| 5. | TN2 sends Echo request to HUT every 3s for 30s. | HUT sends Echo replies to TR1's LLA until reachable time expires. On expiry, the HUT should send 3 NS to TR1's LLA. |
| 6. | TR1 does not respond to NS from HUT. | HUT selects TR2 from its Default Router list. The HUT sends NS's to TR2's LLA. |

### Unexpected behaviour you saw

In Step 5, the HUT does not send an Echo reply via TR1, but incorrectly sends a NS for TR2.

In summary, the state of the neighbor cache entries (NCE) for TR1 and TR2 should dictate the routing decision.  At Step 5, the NCE is:

| Neighbor | State |
|----|----|
| TR1 | REACHABLE |
| TR2 | INCOMPLETE |

In an extract from [RFC4861 6.3.6](https://datatracker.ietf.org/doc/html/rfc4861#section-6.3.6):

     The policy for selecting routers from the Default Router List is as
     follows:

     1) Routers that are reachable or probably reachable (i.e., in any
        state other than INCOMPLETE) SHOULD be preferred over routers
        whose reachability is unknown or suspect (i.e., in the
        INCOMPLETE state, or for which no Neighbor Cache entry exists).
        Further implementation hints on default router selection when
        multiple equivalent routers are available are discussed in
        [[LD-SHRE](https://datatracker.ietf.org/doc/html/rfc4861#ref-LD-SHRE)].

When this test fails, the protocol summary is:

| Time (s) | Protocol Exchange |
|----|----|
| **0.0** | TR1 sends RA (reachable time=10s) |
| **5.0** | TN2 sends echo request via TR1, HUT sends NS for TR1, TR1 sends NA (a REACHABLE NCE is created for TR1), HUT sends echo reply via TR1 |
| **5.1** | TR2 sends RA (reachable time=10s) |
| **8.0** | TN2 sends echo request via TR1 (an INCOMPLETE NCE is created for TR2), HUT sends NS for INCOMPLETE TR2 (instead of replying to REACHABLE TR1) |

This violates [RFC4861 6.3.6](https://datatracker.ietf.org/doc/html/rfc4861#section-6.3.6), bullet 1.

> **NOTE**: While the routing decisions are made in the kernel, this problem does not show up when networkd is disabled and sysctl `accept_ra=2`, i.e. it succeeds when the kernel processes the RA for the default routers. I'm yet to identify the exact cause, but my suspicion is on how networkd creates the default routes.  A side-by-side comparison of watching the routing table is interesting:

Monitoring the routing table with this command and comparing kernel-processing with networkd-processing:
```
$ old="xxx"; while :; do out=$(ip -6 r show dev enp0s9); new=$(echo "$out" | sed 's/expires.*sec //'); [ "$new" != "$old" ] && date +"%F %T.%N:%n""${out}%n"; old="$new"; sleep 0.1; done
```
> NOTE: The output from this command was not displaying ECMP routes due to: [Bug in iproute2](https://bugs.launchpad.net/ubuntu/+source/iproute2/+bug/2070412) fixed by [netdev](https://marc.info/?l=linux-netdev&m=171976458316116&w=2)

The main difference is highlighted in the table below. We can see the kernel shows a route for TR2 (... :1061). <strike>Meanwhile, networkd does not show that route, despite the log indicating the route should have been created. (I'm left wondering if this is a timing issue with networkd running as a user process compared to ther kernel's near-real-time behavior). [This will be the subject of futher investigation].</strike>[The routes were not being displayed because of the bug in iproute2!]

| Native kernel (accept_ra=2) | Networkd (accept_ra=0) |
|----|----|
| 2024-06-25 13:58:14.799160751:<br>fe80::/64 proto kernel metric 256 pref medium<br><br>2024-06-25 14:00:14.146552856:<br>2001:2:0:1000::/64 proto kernel metric 256 expires 65534sec pref medium<br>fe80::/64 proto kernel metric 256 pref medium<br>default via fe80::200:10ff:fe10:1060 proto ra metric 1024 expires 44sec hoplimit 64 pref medium<br><br>2024-06-25 14:00:19.180667134:<br>2001:2:0:1000::/64 proto kernel metric 256 expires 65534sec pref medium<br>fe80::/64 proto kernel metric 256 pref medium<br>default via fe80::200:10ff:fe10:1060 proto ra metric 1024 expires 39sec hoplimit 64 pref medium<br>**default via fe80::200:10ff:fe10:1061 proto ra metric 1024 expires 44sec hoplimit 64 pref medium**<br><br>2024-06-25 14:00:46.764607577:<br>fe80::/64 proto kernel metric 256 pref medium<br> | 2024-06-25 14:05:40.236621759:<br>fe80::/64 proto kernel metric 256 pref medium<br><br>2024-06-25 14:32:59.593132559:<br>2001:2:0:1000::/64 proto ra metric 1024 expires 65534sec pref medium<br>fe80::/64 proto kernel metric 256 pref medium<br>default via fe80::200:10ff:fe10:1060 proto ra metric 1024 expires 44sec pref medium<br><br>2024-06-25 14:33:04.658694269:<br>2001:2:0:1000::/64 proto ra metric 1024 expires 65534sec pref medium<br>fe80::/64 proto kernel metric 256 pref medium<br><br>2024-06-25 14:33:12.140417989:<br>fe80::/64 proto kernel metric 256 pref medium<br> |

### Steps to reproduce the problem

[v6LC_2_2_11-Networkd-Fail.zip](https://github.com/user-attachments/files/15964978/v6LC_2_2_11-Networkd-Fail.zip)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
enp0s9: NDISC: Received Router Advertisement from fe80::200:10ff:fe10:1060: flags=0x00(none), preference=medium, lifetime=45s
enp0s9: NDISC: Invoking callback for 'router' event.
enp0s9: Requesting NDisc route (n/a): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
Setting '/proc/sys/net/ipv6/neigh/enp0s9/base_reachable_time_ms' to '10000'
No change in value '10000', suppressing write
Setting '/proc/sys/net/ipv6/neigh/enp0s9/retrans_time_ms' to '1000'
No change in value '1000', suppressing write
Setting '/proc/sys/net/ipv6/conf/enp0s9/hop_limit' to '64'
No change in value '64', suppressing write
enp0s9: Requesting NDisc route (configuring,configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Requesting NDisc address (configured): 2001:2:0:1000:a00:27ff:fe5f:f72d/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: Setting SLAAC addresses and router.
enp0s9: State changed: configured -> configuring
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=46 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: Configuring NDisc route (requesting): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Configuring NDisc route (requesting,configuring,configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Configuring NDisc address (requesting,configured): 2001:2:0:1000:a00:27ff:fe5f:f72d/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: Received new NDisc route (configured): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: ndisc_check_ready(): SLAAC addresses and routes are not set.
enp0s9: ndisc_check_ready(): SLAAC addresses and routes are not set.
enp0s9: Received updated NDisc address (configured): 2001:2:0:1000:a00:27ff:fe5f:f72d/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: SLAAC addresses and routes set.
enp0s9: link_check_ready(): IPv4LL:no DHCPv4:no DHCPv6:no DHCP-PD:no NDisc:yes
enp0s9: State changed: configuring -> configured
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=47 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
enp0s9: NDISC: Received Neighbor Advertisement from fe80::200:10ff:fe10:1060: Router=yes, Solicited=yes, Override=no
enp0s9: NDISC: Invoking callback for 'neighbor' event.
enp0s9: NDISC: Received Router Advertisement from fe80::200:10ff:fe10:1061: flags=0x00(none), preference=medium, lifetime=45s
enp0s9: NDISC: Invoking callback for 'router' event.

###########################################################################################
# Requested this 2nd default route, but it does NOT show up in the routing table. Why???  #
###########################################################################################

enp0s9: Requesting NDisc route (n/a): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1061, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a

###########################################################################################

Setting '/proc/sys/net/ipv6/neigh/enp0s9/base_reachable_time_ms' to '10000'
No change in value '10000', suppressing write
Setting '/proc/sys/net/ipv6/neigh/enp0s9/retrans_time_ms' to '1000'
No change in value '1000', suppressing write
Setting '/proc/sys/net/ipv6/conf/enp0s9/hop_limit' to '64'
No change in value '64', suppressing write
enp0s9: Requesting NDisc route (configuring,configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Requesting NDisc address (configured): 2001:2:0:1000:a00:27ff:fe5f:f72d/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: Setting SLAAC addresses and router.
enp0s9: State changed: configured -> configuring
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=48 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: Configuring NDisc route (requesting): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1061, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Configuring NDisc route (requesting,configuring,configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Configuring NDisc address (requesting,configured): 2001:2:0:1000:a00:27ff:fe5f:f72d/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: Received new NDisc route (configured): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1061, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Received remembered NDisc route (configured): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: ndisc_check_ready(): SLAAC addresses and routes are not set.
enp0s9: ndisc_check_ready(): SLAAC addresses and routes are not set.
enp0s9: Received updated NDisc address (configured): 2001:2:0:1000:a00:27ff:fe5f:f72d/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: SLAAC addresses and routes set.
enp0s9: link_check_ready(): IPv4LL:no DHCPv4:no DHCPv6:no DHCP-PD:no NDisc:yes
enp0s9: State changed: configuring -> configured
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=49 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #33470.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

File: src/network/networkd-ndisc.c [hunk 1]
```diff
@@ -149,6 +150,290 @@ static int ndisc_check_ready(Link *link) {
...
+        return log_link_debug_errno(link, SYNTHETIC_ERRNO(EBUSY), "Cannot find free nexthop ID for %s.",
+                                    IN6_ADDR_TO_STRING(&nexthop->gw.address.in6));
+}
+
+static int ndisc_nexthop_handler(sd_netlink *rtnl, sd_netlink_message *m, Request *req, Link *link, NextHop *nexthop) {
+        int r;
+
+        assert(link);
+
+        r = nexthop_configure_handler_internal(m, link, "Could not set NDisc route");
```
Comment (evverx) [inline src/network/networkd-ndisc.c:372]: Looking at
```sh
host0: Trying to reconfigure the interface.
host0: Could not set NDisc route: Connection timed out
host0: Failed
host0: The interface entered the failed state frequently, refusing to reconfigure it automatically.
```
it seems network interfaces go down here somehow.

(I don't think I have seen it before)

There is also a memory leak: https://github.com/systemd/systemd/issues/35164

Comment (evverx) [reply src/network/networkd-ndisc.c:372]: The memory leak is getting bigger:
```sh
==559==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 5248 byte(s) in 41 object(s) allocated from:
    #0 0x7f936e4d5aa3 in malloc (/usr/lib/clang/19/lib/x86_64-redhat-linux-gnu/libclang_rt.asan.so+0xd5aa3) (BuildId: 98d6f0ad935c4ea5ed3cdc909871a71680370a1>
    #1 0x55871f331d8d in malloc_multiply /work/build/../src/src/basic/alloc-util.h:119:16
    #2 0x55871f33190b in nexthop_new /work/build/../src/src/network/networkd-nexthop.c:128:19
    #3 0x55871f345902 in nexthop_add_new /work/build/../src/src/network/networkd-nexthop.c:412:13
    #4 0x55871f342c3f in manager_rtnl_process_nexthop /work/build/../src/src/network/networkd-nexthop.c:1140:21
    #5 0x7f936dc4f4f1 in process_match /work/build/../src/src/libsystemd/sd-netlink/sd-netlink.c:314:21
    #6 0x7f936dc453ce in process_running /work/build/../src/src/libsystemd/sd-netlink/sd-netlink.c:344:21
    #7 0x7f936dc44f71 in sd_netlink_process /work/build/../src/src/libsystemd/sd-netlink/sd-netlink.c:374:13
    #8 0x7f936dc4a078 in io_callback /work/build/../src/src/libsystemd/sd-netlink/sd-netlink.c:655:13
    #9 0x7f936d8a2b95 in source_dispatch /work/build/../src/src/libsystemd/sd-event/sd-event.c:4228:21
    #10 0x7f936d8a0c18 in sd_event_dispatch /work/build/../src/src/libsystemd/sd-event/sd-event.c:4849:21
    #11 0x7f936d8a6566 in sd_event_run /work/build/../src/src/libsystemd/sd-event/sd-event.c:4910:21
    #12 0x7f936d8a74ff in sd_event_loop /work/build/../src/src/libsystemd/sd-event/sd-event.c:4931:21
    #13 0x55871efc6c8d in run /work/build/../src/src/network/networkd.c:114:13
    #14 0x55871efc3d97 in main /work/build/../src/src/network/networkd.c:121:1
    #15 0x7f936c611247 in __libc_start_call_main (/lib64/libc.so.6+0x3247) (BuildId: 948d229348b56bdcf4e0a96d5ccd8fb175f617f0)
    #16 0x7f936c61130a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x330a) (BuildId: 948d229348b56bdcf4e0a96d5ccd8fb175f617f0)
    #17 0x55871efc3b44 in _start (/usr/lib/systemd/systemd-networkd+0x15fb44) (BuildId: ab2c9531981cbfe2507953d7e4a50ec991e70568)
SUMMARY: AddressSanitizer: 5248 byte(s) leaked in 41 allocation(s).
systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
```
If all goes well I'll recover RAs triggering all that.
