### PR TITLE
calendarspec: fix calculation of timespec iterations that fall onto a DST change

### LINKED ISSUE #13745: Standard time -> summer time transition breaks timer for entire day
**systemd version the issue has been seen with**

systemd v243

**Used distribution**

Fedora

**Description of problem**

The `Australia/Sydney` time zone transitioned from standard time to summer time at 02:00 on Sunday 2019-10-06. I have a timer unit set to fire every four hours:

    OnCalendar=02/4:30:00

It is expected (and for me acceptable) that this will miss activating the associated service at 02:30 on that day, since that wall-clock time does not exist. See #5595 for discussion on this behaviour.

However, systemd _also_ skipped activating the service at 06:30, 10:30, etc., until 02:30 on the following day. This means a timer that was configured to run every 4 hours actually had a gap of 27 hours between two activations.

**Steps to reproduce the problem**

    $ TZ=Australia/Sydney faketime 2019-10-06 date
    Sun Oct  6 00:00:00 AEST 2019

    $ TZ=Australia/Sydney faketime 2019-10-06 systemd-analyze calendar 2/4:30
      Original form: 2/4:30
    Normalized form: *-*-* 02/4:30:00
        Next elapse: Mon 2019-10-07 02:30:00 AEDT
           (in UTC): Sun 2019-10-06 15:30:00 UTC
           From now: 1 day 1h left

This runs `systemd-analyze` as if the current time were midnight at the start of 2019-10-06. The four-hourly timer, starting at 02:30, doesn't elapse until the _following_ day.

I would expect instead something like:

      Original form: 2/4:30
    Normalized form: *-*-* 02/4:30:00
        Next elapse: Sun 2019-10-06 06:30:00 AEDT
           (in UTC): Sat 2019-10-05 20:30:00 UTC
           From now: 5h 30min left

That is, I would expect the 02:30 activation only to be skipped.

(For reference, AEST == UTC+10, AEDT == UTC+11.)

### PR DESCRIPTION
**Pull request by keszybz**
If we tested a candidate time that would fall onto the DST change, and we
realized that it is now a valid time ('cause the given "hour" is missing),
we would jump to to beginning of the next bigger time period, i.e. the next
day.

mktime_or_timegm() already tells us what the next valid time is, so let's reuse
this, and continue the calculations at this point. This should allow us to
correctly jump over DST changes, but also leap seconds and similar.  It should
be OK even multiple days were removed from calendar, similarly to the
Gregorian-Julian transition. By reusing the information from normalization, we
don't have to make assumptions what the next valid time is.

Fixes #13745.

$ TZ=Australia/Sydney faketime '2019-10-06 01:50' build/systemd-analyze calendar 0/1:0/1 --iterations 20 | grep Iter
       Iter. #2: Sun 2019-10-06 01:52:00 AEST
       Iter. #3: Sun 2019-10-06 01:53:00 AEST
       Iter. #4: Sun 2019-10-06 01:54:00 AEST
       Iter. #5: Sun 2019-10-06 01:55:00 AEST
       Iter. #6: Sun 2019-10-06 01:56:00 AEST
       Iter. #7: Sun 2019-10-06 01:57:00 AEST
       Iter. #8: Sun 2019-10-06 01:58:00 AEST
       Iter. #9: Sun 2019-10-06 01:59:00 AEST
      Iter. #10: Sun 2019-10-06 03:00:00 AEDT
      Iter. #11: Sun 2019-10-06 03:01:00 AEDT
      Iter. #12: Sun 2019-10-06 03:02:00 AEDT
      Iter. #13: Sun 2019-10-06 03:03:00 AEDT
      Iter. #14: Sun 2019-10-06 03:04:00 AEDT
      Iter. #15: Sun 2019-10-06 03:05:00 AEDT
      Iter. #16: Sun 2019-10-06 03:06:00 AEDT
      Iter. #17: Sun 2019-10-06 03:07:00 AEDT
      Iter. #18: Sun 2019-10-06 03:08:00 AEDT
      Iter. #19: Sun 2019-10-06 03:09:00 AEDT
      Iter. #20: Sun 2019-10-06 03:10:00 AEDT

$ TZ=Australia/Sydney faketime 2019-10-06 build/systemd-analyze calendar 2/4:30 --iterations=3
  Original form: 2/4:30
Normalized form: *-*-* 02/4:30:00
    Next elapse: Sun 2019-10-06 06:30:00 AEDT
       (in UTC): Sat 2019-10-05 19:30:00 UTC
       From now: 5h 29min left
       Iter. #2: Sun 2019-10-06 10:30:00 AEDT
       (in UTC): Sat 2019-10-05 23:30:00 UTC
       From now: 9h left
       Iter. #3: Sun 2019-10-06 14:30:00 AEDT
       (in UTC): Sun 2019-10-06 03:30:00 UTC
       From now: 13h left

### CODE REVIEW

File: src/shared/calendarspec.c [hunk 1]
```diff
@@ -1146,31 +1146,32 @@ static int find_matching_component(const CalendarSpec *spec, const CalendarCompo
...
          * don't cause find_next() to loop forever. tm_year contains years
          * since 1900, so adjust it accordingly.
          */
         if (tm->tm_year + 1900 > MAX_YEAR)
-                return true;
+                return -ERANGE;
+
+        t = *tm;
+        if (mktime_or_timegm(&t, utc) < 0)
+                return -EINVAL;
```
Comment (poettering) [inline src/shared/calendarspec.c]: not that it matters much, but it's slightly ugly that we make up our own error here, even though mktime() and timegm() set errno. maybe fix this to propagate the error properly?

Comment (keszybz) [reply src/shared/calendarspec.c]: Fixed.

**Comment by keszybz** [comment]
> maybe should have a test case?

A test case wouldn't be bad. I was too lazy to add one.

> maybe beef up "systemd-analyze calendar" to take a new parameter --current-time= or so, which does what faketime does internally? Then compare the byte-by-byte output of the tool with what we expect?

Sounds good.

I now pushed a new version that propagates errno, no other changes.
