### PR TITLE
tree-wide: FORMAT_TIMESPAN() or friends must be used as a function argument

### LINKED ISSUE #20227: Possible stack-use-after-scope in systemd-networkd
**systemd version the issue has been seen with**
 > latest trunk

**Used distribution**
 > Arch Linux

Tonight's gcc+ASan/UBSan cron job went completely haywire when running the systemd-networkd testsuite:

```
systemd-networkd[129327]: lo: Failed to get driver, continuing without: Operation not supported
systemd-networkd[129327]: lo: Link 1 added
systemd-networkd[129327]: lo: Saved original MTU 65536 (min: 0, max: 4294967295)
systemd-networkd[129327]: lo: Saved hardware address: 00:00:00:00:00:00
systemd-networkd[129327]: lo: Failed to manage link by its new hardware address, ignoring: File exists
systemd-networkd[129327]: lo: Flags change: +LOOPBACK +UP +LOWER_UP +RUNNING
systemd-networkd[129327]: lo: Link UP
systemd-networkd[129327]: lo: Gained carrier
systemd-networkd[129327]: lo: udev initialized link
systemd-networkd[129327]: lo: State changed: pending -> initialized
systemd-networkd[129327]: =================================================================
systemd-networkd[129327]: ==129327==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fd9875b4280 at pc 0x7fd98d7bea61 bp 0x7ffed09c34f0 sp 0x7ffed09c2c68
systemd-networkd[129327]: READ of size 10 at 0x7fd9875b4280 thread T0
systemd-networkd[129327]:     #0 0x7fd98d7bea60 in printf_common /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors_format.inc:553
systemd-networkd[129327]:     #1 0x7fd98d7c06dd in __interceptor_vsnprintf /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1668
systemd-networkd[129327]:     #2 0x7fd98cb8e58c in log_object_internalv ../build/src/basic/log.c:805
systemd-networkd[129327]:     #3 0x7fd98cb8e862 in log_object_internal ../build/src/basic/log.c:827
systemd-networkd[129327]:     #4 0x55f88e9597a1 in log_address_debug ../build/src/network/networkd-address.c:648
systemd-networkd[129327]:     #5 0x55f88e96f01d in manager_rtnl_process_address ../build/src/network/networkd-address.c:1440
systemd-networkd[129327]:     #6 0x55f88e86e37d in manager_enumerate_internal ../build/src/network/networkd-manager.c:595
systemd-networkd[129327]:     #7 0x55f88e86e7b5 in manager_enumerate_addresses ../build/src/network/networkd-manager.c:630
systemd-networkd[129327]:     #8 0x55f88e872fa6 in manager_enumerate ../build/src/network/networkd-manager.c:702
systemd-networkd[129327]:     #9 0x55f88e86b940 in run ../build/src/network/networkd.c:92
systemd-networkd[129327]:     #10 0x55f88e86c1a2 in main ../build/src/network/networkd.c:111
systemd-networkd[129327]:     #11 0x7fd98b627b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
systemd-networkd[129327]:     #12 0x55f88e86b36d in _start (/systemd-meson-build/systemd-networkd+0x32e36d)
systemd-networkd[129327]: Address 0x7fd9875b4280 is located in stack of thread T0 at offset 128 in frame
systemd-networkd[129327]:     #0 0x55f88e958bf9 in log_address_debug ../build/src/network/networkd-address.c:623
systemd-networkd[129327]:   This frame has 5 object(s):
systemd-networkd[129327]:     [32, 40) 'addr' (line 624)
systemd-networkd[129327]:     [64, 72) 'peer' (line 624)
systemd-networkd[129327]:     [96, 104) 'flags_str' (line 624)
systemd-networkd[129327]:     [128, 192) '<unknown>' <== Memory access at offset 128 is inside this variable
systemd-networkd[129327]:     [224, 288) '<unknown>'
systemd-networkd[129327]: HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
systemd-networkd[129327]:       (longjmp and C++ exceptions *are* supported)
systemd-networkd[129327]: SUMMARY: AddressSanitizer: stack-use-after-scope /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors_format.inc:553 in printf_common
systemd-networkd[129327]: Shadow bytes around the buggy address:
systemd-networkd[129327]:   0x0ffbb0eae800: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
systemd-networkd[129327]:   0x0ffbb0eae810: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
systemd-networkd[129327]:   0x0ffbb0eae820: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
systemd-networkd[129327]:   0x0ffbb0eae830: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
systemd-networkd[129327]:   0x0ffbb0eae840: f1 f1 f1 f1 00 f2 f2 f2 00 f2 f2 f2 00 f2 f2 f2
systemd-networkd[129327]: =>0x0ffbb0eae850:[f8]f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f8 f8 f8 f8
systemd-networkd[129327]:   0x0ffbb0eae860: f8 f8 f8 f8 f3 f3 f3 f3 00 00 00 00 00 00 00 00
systemd-networkd[129327]:   0x0ffbb0eae870: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
systemd-networkd[129327]:   0x0ffbb0eae880: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
systemd-networkd[129327]:   0x0ffbb0eae890: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
systemd-networkd[129327]:   0x0ffbb0eae8a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
systemd-networkd[129327]: Shadow byte legend (one shadow byte represents 8 application bytes):
systemd-networkd[129327]:   Addressable:           00
systemd-networkd[129327]:   Partially addressable: 01 02 03 04 05 06 07
systemd-networkd[129327]:   Heap left redzone:       fa
systemd-networkd[129327]:   Freed heap region:       fd
systemd-networkd[129327]:   Stack left redzone:      f1
systemd-networkd[129327]:   Stack mid redzone:       f2
systemd-networkd[129327]:   Stack right redzone:     f3
systemd-networkd[129327]:   Stack after return:      f5
systemd-networkd[129327]:   Stack use after scope:   f8
systemd-networkd[129327]:   Global redzone:          f9
systemd-networkd[129327]:   Global init order:       f6
systemd-networkd[129327]:   Poisoned by user:        f7
systemd-networkd[129327]:   Container overflow:      fc
systemd-networkd[129327]:   Array cookie:            ac
systemd-networkd[129327]:   Intra object redzone:    bb
systemd-networkd[129327]:   ASan internal:           fe
systemd-networkd[129327]:   Left alloca redzone:     ca
systemd-networkd[129327]:   Right alloca redzone:    cb
systemd-networkd[129327]:   Shadow gap:              cc
systemd-networkd[129327]: ==129327==ABORTING
```

Job links (I re-run it once, for good measure):
 * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-cron-build/294/artifact//systemd-centos-ci/index.html
 * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-cron-build/295/artifact//systemd-centos-ci/index.html

/cc @yuwata

### PR DESCRIPTION
**Pull request by yuwata**
Follow-ups for #20109.

Fixes #20227.

cc @mrc0mmand and @keszybz.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Thank you! I'll unleash the cron job manually on this PR.

**Review by bluca — APPROVED** [review]
lgtm

**Comment by mrc0mmand** [comment]
Can confirm the issue is indeed fixed!

File: src/network/networkd-address.c [hunk 1]
```diff
@@ -637,19 +652,13 @@ static void log_address_debug(const Address *address, const char *str, const Lin
         if (has_peer)
                 (void) in_addr_to_string(address->family, &address->in_addr_peer, &peer);
 
-        if (address->cinfo.ifa_valid != CACHE_INFO_INFINITY_LIFE_TIME)
-                valid_str = FORMAT_TIMESPAN(address->cinfo.ifa_valid * USEC_PER_SEC, USEC_PER_SEC);
-
-        if (address->cinfo.ifa_prefered != CACHE_INFO_INFINITY_LIFE_TIME)
-                preferred_str = FORMAT_TIMESPAN(address->cinfo.ifa_prefered * USEC_PER_SEC, USEC_PER_SEC);
```
Comment (keszybz) [inline src/network/networkd-address.c:644]: The bug was really that `if` was used here instead of `? ... : NULL`.

File: src/network/networkd-dhcp6.c [hunk 2]
```diff
@@ -1068,11 +1063,6 @@ static void log_dhcp6_address(Link *link, const Address *address, char **ret) {
 
         (void) in6_addr_prefix_to_string(&address->in_addr.in6, address->prefixlen, &buffer);
 
-        const char *valid_str = address->cinfo.ifa_valid == CACHE_INFO_INFINITY_LIFE_TIME ? NULL :
-                FORMAT_TIMESPAN(address->cinfo.ifa_valid * USEC_PER_SEC, USEC_PER_SEC);
-        const char *preferred_str = address->cinfo.ifa_prefered == CACHE_INFO_INFINITY_LIFE_TIME ? NULL :
-                FORMAT_TIMESPAN(address->cinfo.ifa_prefered * USEC_PER_SEC, USEC_PER_SEC);
```
Comment (keszybz) [inline src/network/networkd-dhcp6.c:1074]: Strictly speaking, this part was OK (IIUC). But the new approach is much nicer!

File: src/network/networkd-address.c [hunk 3]
```diff
@@ -620,9 +621,23 @@ int manager_has_address(Manager *manager, int family, const union in_addr_union
...
+        assert(buf);
+        assert(l > 0);
+
+        if (lifetime == CACHE_INFO_INFINITY_LIFE_TIME) {
+                strscpy(buf, l, "forever");
+                return buf;
+        }
+
+        l -= strpcpy(&p, l, "for ");
+        return format_timespan(p, l, lifetime * USEC_PER_SEC, USEC_PER_SEC);
```
Comment (keszybz) [inline src/network/networkd-address.c:636]: This part is buggy. I'll make a pull request.

**Review by keszybz — COMMENTED** [review]
Thanks for taking care of this quickly. I was aware that the construct cannot be used with `if`, but I somehow forgot to fix all places. I found a buglet, so I'll follow up with a fix and a test.
