### PR TITLE
network: do not require DHCPv6 addresses when UseAddress=no

### LINKED ISSUE #19196: systemd-networkd interfaces remain configuring when UseAddress=false
**systemd version the issue has been seen with**
 > systemd 248 (248-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified               

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > Linux hostname 5.11.0-seblu #1 SMP PREEMPT Tue Feb 16 15:56:00 CET 2021 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Steps to reproduce the problem**
A very simple double interface situation where eth0 is providing the PD to a dummy interface.

#### eth0.network
```ini
[Match]
Name=eth0

[Network]
Address=1.2.3.4/24
Address=1::2/64
Gateway=1.2.3.1
DHCP=ipv6

[DHCPv4]
# Used by DHCPv6 but not allowed in DHCPv6
ClientIdentifier=duid-only
DUIDType=link-layer
DUIDRawData=xxx

[DHCPv6]
UseAddress=false
WithoutRA=solicit
```

#### dummy0.netdev
```ini
[NetDev]
Name=dummy0
Kind=dummy
```

#### dummy0.network
```ini
[Match]
Name=dummy0
[Network]
IPv6PrefixDelegation=dhcpv6
```

**Unexpected behaviour you saw**
Interface `eth0` remain configuring in networkctl 

```
# networkctl 
IDX LINK   TYPE     OPERATIONAL SETUP       
1 lo     loopback carrier     unmanaged
2 eth0   ether    routable    configuring
3 dummy0 ether    routable    configured 
```

Running in debug log level, shows `link_check_ready()` is unhappy because there is no dynamic assignment. Which is the purpose of UseAddress=false.
```
# SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-networkd
sd-device-monitor: No permission to stat PID1's netns, unable to determine if we are in host netns: Permission denied
Bus bus-api-network: changing state UNSET → OPENING
sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Bus bus-api-network: changing state OPENING → AUTHENTICATING
Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
timestamp of '/etc/systemd/network' changed
dummy0: loaded dummy
dummy0: Creating
...
eth0: Configuring route: dst: n/a, src: n/a, gw: fe80::x:x, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0
eth0: Setting NDisc routes.
eth0: Removing old NDisc information obtained from fe80::x:x.
eth0: link_check_ready(): DHCP4, DHCP6 or IPv4LL is enabled but no dynamic address is assigned yet.
eth0: NDisc routes set.
eth0: Removing old NDisc information obtained from fe80::x:x.
eth0: link_check_ready(): DHCP4, DHCP6 or IPv4LL is enabled but no dynamic address is assigned yet.
...
eth0: link_check_ready(): DHCP4, DHCP6 or IPv4LL is enabled but no dynamic address is assigned yet.
```

Despite these messages, IPv6 PD works.

**Expected behaviour you didn't see**
```
# networkctl 
IDX LINK   TYPE     OPERATIONAL SETUP       
1 lo     loopback carrier     unmanaged
2 eth0   ether    routable    configured
3 dummy0 ether    routable    configured 
```

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for 1536b7b2d00819615bf8eba194de7ccd20c3689f.

Fixes #19196.

### CODE REVIEW

File: src/network/networkd-dhcp6.c [hunk 1]
```diff
@@ -25,6 +25,13 @@
 #include "radv-internal.h"
 #include "web-util.h"
 
+bool link_dhcp6_with_address_enabled(Link *link) {
+        if (!link_dhcp6_enabled(link))
```
Comment (bluca) [inline src/network/networkd-dhcp6.c:29]: assert(link)

**Review by bluca — APPROVED** [review]
lgtm

File: src/network/networkd-dhcp6.c (hunk 1 above)
Comment (keszybz) [reply src/network/networkd-dhcp6.c:29]: link_dhcp6_enabled already does the assert… I think it's fine to leave it out.

**Review by keszybz — APPROVED** [review]
