### PR TITLE
timesync: ignore IPv6 addresses when the kernel does not support it

### LINKED ISSUE #25728: timesyncd stops cycling through server list if socket cannot be opened
### systemd version the issue has been seen with

252.2

### Used distribution

Custom

### Linux kernel version used

5.15.82

### CPU architectures issue was seen on

arm

### Component

systemd-timesync

### Expected behaviour you didn't see

On a system without IPv6 support one of the NTP server resolves to both IPv4 and IPv6 addresses. The NTP server doesn't respond over IPv4 though. systemd-timesyncd ignores the unsupported IPv6 address or logs errors for not enabling IPv6 support. It then goes on to try the next server in the list or (if at the end) waits for some time and retries the first NTP server in the list.

### Unexpected behaviour you saw

systemd-timesync rightfully complains about not being able to open an IPv6 socket.

But then, instead of skipping to the next NTP server in the list, it stops trying. Even after waiting for the poll interval given by `timedatectl timesync-status` it doesn't try contacting any of the servers again.

### Steps to reproduce the problem

While I originally spotted this in a situation where the NTP address was supplied through DNS it is reproducable by manually specifying multiple `NTP=` entries in the .network file.

1. Setup system without IPv6 support. This works best if IPv6 is disabled entirely or is built as module (which can be blacklisted). Using `ipv6.disable_ipv6=1` doesn't seem to trigger the socket error.
2. Create `.network` file with three `NTP=` entries, two IPv4 addresses and an IPv6 one in between the two. The IPv4 addresses should not point to a working NTP.
3. Reload network config and check the behaviour of systemd-timesync

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Dec 13 13:38:31 dut systemd-networkd[114]: lan0: Reconfiguring with /run/systemd/network/ntp.network.
Dec 13 13:38:31 dut systemd-timesyncd[225]: Added new link server 192.168.188.10.
Dec 13 13:38:31 dut systemd-timesyncd[225]: Added new link server fe80::9d36:27e1:4d21:39ee.
Dec 13 13:38:31 dut systemd-timesyncd[225]: Added new link server 192.168.188.20.
Dec 13 13:38:31 dut avahi-daemon[163]: Joining mDNS multicast group on interface lan0.IPv4 with address 192.168.188.19.
Dec 13 13:38:31 dut avahi-daemon[163]: New relevant interface lan0.IPv4 for mDNS.
Dec 13 13:38:31 dut avahi-daemon[163]: Registering new address record for 192.168.188.19 on lan0.IPv4.
Dec 13 13:38:31 dut systemd-timesyncd[225]: Network configuration changed, trying to establish connection.
Dec 13 13:38:31 dut systemd-timesyncd[225]: Selected server 192.168.188.10.
Dec 13 13:38:31 dut systemd-timesyncd[225]: Resolving 192.168.188.10...
Dec 13 13:38:31 dut systemd-timesyncd[225]: Resolved address 192.168.188.10:123 for 192.168.188.10.
Dec 13 13:38:31 dut systemd-timesyncd[225]: Selected address 192.168.188.10:123 of server 192.168.188.10.
Dec 13 13:38:31 dut systemd-timesyncd[225]: Connecting to time server 192.168.188.10:123 (192.168.188.10).
Dec 13 13:38:31 dut systemd-timesyncd[225]: Sent NTP request to 192.168.188.10:123 (192.168.188.10).
Dec 13 13:38:41 dut systemd-timesyncd[225]: Timed out waiting for reply from 192.168.188.10:123 (192.168.188.10).
Dec 13 13:38:41 dut systemd-timesyncd[225]: Selected server fe80::9d36:27e1:4d21:39ee.
Dec 13 13:38:41 dut systemd-timesyncd[225]: Resolving fe80::9d36:27e1:4d21:39ee...
Dec 13 13:38:41 dut systemd-timesyncd[225]: Resolved address [fe80::9d36:27e1:4d21:39ee]:123 for fe80::9d36:27e1:4d21:39ee.
Dec 13 13:38:41 dut systemd-timesyncd[225]: Selected address [fe80::9d36:27e1:4d21:39ee]:123 of server fe80::9d36:27e1:4d21:39ee.
Dec 13 13:38:41 dut systemd-timesyncd[225]: Connecting to time server [fe80::9d36:27e1:4d21:39ee]:123 (fe80::9d36:27e1:4d21:39ee).
Dec 13 13:38:41 dut systemd-timesyncd[225]: Failed to set up connection socket: Address family not supported by protocol
Dec 13 13:38:41 dut systemd-timesyncd[225]: Event source n/a (type io) returned error, disabling: Address family not supported by protocol
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #25728.

### CODE REVIEW

**Comment by yuwata** [comment]
@fxri Does this PR also work for you?

File: src/timesync/timesyncd-manager.c [hunk 1]
```diff
@@ -756,6 +756,11 @@ static int manager_resolve_handler(sd_resolve_query *q, int ret, const struct ad
                         continue;
                 }
 
+                if (ai->ai_addr->sa_family == AF_INET6 && !socket_ipv6_is_enabled()) {
+                        log_debug("Ignoring IPv6 address for %s.", m->current_server_name->string);
+                        continue;
+                }
```
Comment (poettering) [inline src/timesync/timesyncd-manager.c]: hmm, a better approach would be to change the `hints` structure that is passed into `resolve_getaddrinfo()` to set `.ai_protocol` to AF_INET4 so that the query is done for IPv4 only in the first place. i.e. a tighter query is better than filtering the answer

Comment (poettering) [reply src/timesync/timesyncd-manager.c]: (see the getaddrinfo() man page, since that's what resolve_getaddrinfo() wraps)

Comment (yuwata) [reply src/timesync/timesyncd-manager.c]: You mean .ai_family, instead of .ai_protocol?

Comment (poettering) [reply src/timesync/timesyncd-manager.c]: yeah, apparently!

File: src/timesync/timesyncd-manager.c [hunk 2]
```diff
@@ -878,6 +873,12 @@ int manager_connect(Manager *m) {
 
                 log_debug("Resolving %s...", m->current_server_name->string);
 
+                struct addrinfo hints = {
+                        .ai_flags = AI_NUMERICSERV|AI_ADDRCONFIG,
+                        .ai_socktype = SOCK_DGRAM,
+                        .ai_family = socket_ipv6_is_supported() ? AF_UNSPEC : AF_INET6,
```
Comment (fxri) [inline src/timesync/timesyncd-manager.c]: I think this needs to be `AF_INET` instead of `AF_INET6`.

Comment (poettering) [reply src/timesync/timesyncd-manager.c]: yes, true

Comment (yuwata) [reply src/timesync/timesyncd-manager.c]: Ouch!

**Comment by fxri** [comment]
Works nicely even for statically configured servers.
```
Dec 14 18:22:26 dut systemd-networkd[114]: lan0: Reconfiguring with /run/systemd/network/ntp.network.
Dec 14 18:22:26 dut systemd-timesyncd[205]: Added new link server 192.168.188.10.
Dec 14 18:22:26 dut systemd-timesyncd[205]: Added new link server fe80::9d36:27e1:4d21:39ee.
Dec 14 18:22:26 dut systemd-timesyncd[205]: Added new link server 192.168.188.20.
Dec 14 18:22:26 dut systemd-timesyncd[205]: Network configuration changed, trying to establish connection.
Dec 14 18:22:26 dut systemd-timesyncd[205]: Selected server 192.168.188.10.
Dec 14 18:22:26 dut systemd-timesyncd[205]: Resolving 192.168.188.10...
Dec 14 18:22:26 dut systemd-timesyncd[205]: Resolved address 192.168.188.10:123 for 192.168.188.10.
Dec 14 18:22:26 dut systemd-timesyncd[205]: Selected address 192.168.188.10:123 of server 192.168.188.10.
Dec 14 18:22:26 dut systemd-timesyncd[205]: Connecting to time server 192.168.188.10:123 (192.168.188.10).
Dec 14 18:22:26 dut systemd-timesyncd[205]: Sent NTP request to 192.168.188.10:123 (192.168.188.10).
Dec 14 18:22:36 dut systemd-timesyncd[205]: Timed out waiting for reply from 192.168.188.10:123 (192.168.188.10).
Dec 14 18:22:36 dut systemd-timesyncd[205]: Selected server fe80::9d36:27e1:4d21:39ee.
Dec 14 18:22:36 dut systemd-timesyncd[205]: Resolving fe80::9d36:27e1:4d21:39ee...
Dec 14 18:22:36 dut systemd-timesyncd[205]: Failed to resolve fe80::9d36:27e1:4d21:39ee: Address family for hostname not supported
Dec 14 18:22:36 dut systemd-timesyncd[205]: Selected server 192.168.188.20.
Dec 14 18:22:36 dut systemd-timesyncd[205]: Resolving 192.168.188.20...
Dec 14 18:22:36 dut systemd-timesyncd[205]: Resolved address 192.168.188.20:123 for 192.168.188.20.
Dec 14 18:22:36 dut systemd-timesyncd[205]: Selected address 192.168.188.20:123 of server 192.168.188.20.
Dec 14 18:22:36 dut systemd-timesyncd[205]: Connecting to time server 192.168.188.20:123 (192.168.188.20).
Dec 14 18:22:36 dut systemd-timesyncd[205]: Sent NTP request to 192.168.188.20:123 (192.168.188.20).
Dec 14 18:22:47 dut systemd-timesyncd[205]: Timed out waiting for reply from 192.168.188.20:123 (192.168.188.20).
Dec 14 18:22:47 dut systemd-timesyncd[205]: Waiting after exhausting servers.
Dec 14 18:23:19 dut systemd-timesyncd[205]: Selected server 192.168.188.10.
Dec 14 18:23:19 dut systemd-timesyncd[205]: Resolving 192.168.188.10...
```
If the IPv6 is injected through DNS the debug messages are slightly different, probably because the resolver doesn't include AAAA queries anymore:
```
Dec 14 18:49:47 dut systemd-timesyncd[261]: Selected server ntp46.
Dec 14 18:49:47 dut systemd-timesyncd[261]: Resolving ntp46...
Dec 14 18:49:47 dut systemd-timesyncd[261]: Resolved address 192.168.188.20:123 for ntp46.
Dec 14 18:49:47 dut systemd-timesyncd[261]: Selected address 192.168.188.20:123 of server ntp46.
Dec 14 18:49:47 dut systemd-timesyncd[261]: Connecting to time server 192.168.188.20:123 (ntp46).
Dec 14 18:49:47 dut systemd-timesyncd[261]: Sent NTP request to 192.168.188.20:123 (ntp46).
Dec 14 18:49:57 dut systemd-timesyncd[261]: Timed out waiting for reply from 192.168.188.20:123 (ntp46).
Dec 14 18:49:57 dut systemd-timesyncd[261]: Selected server ntp6only.
Dec 14 18:49:57 dut systemd-timesyncd[261]: Resolving ntp6only...
Dec 14 18:49:57 dut systemd-timesyncd[261]: Failed to resolve ntp6only: Temporary failure in name resolution

**Comment by yuwata** [comment]
@fxri Thank you for the confirmation!
