### PR TITLE
core: call dynamic_user_acquire() only when 'group' is non-null

### LINKED ISSUE #14733: ABRT in dynamic_user_acquire()
A Debian package (fwupd 1.3.7-1) installs a broken unit file, /lib/systemd/system/fwupd-refresh.service, that contains `ExecStart=@bindir@/fwupdmgr refresh --no-metadata-check`. When updating to this package version systemd crashed:

```
systemd[1]: Reloading.
systemd[1]: /lib/systemd/system/fwupd-refresh.service:17: Neither a valid executable name nor an absolute path: bindir@/fwupdmgr
systemd[1]: fwupd-refresh.service: Unit configuration has fatal error, unit will not be started.
systemd[1]: fwupd-refresh.service: Current command vanished from the unit file, execution of the command list won't be resumed.
systemd[1]: Assertion 'name' failed at src/core/dynamic-user.c:81, function dynamic_user_acquire(). Aborting.
```

I have the core file, here is the bt:

```
#0  0x00007f8dd5a3f367 in kill () at ../sysdeps/unix/syscall-template.S:78
#1  0x0000561425f2676f in crash (sig=6) at ../src/core/main.c:212
#2  <signal handler called>
#3  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#4  0x00007f8dd5a2a535 in __GI_abort () at abort.c:79
#5  0x00007f8dd5820947 in log_assert_failed_realm (realm=realm@entry=LOG_REALM_SYSTEMD, text=text@entry=0x561425f2f258 "name", file=file@entry=0x561425f33796 "src/core/dynamic-user.c", line=line@entry=81,
    func=func@entry=0x561425f55410 <__PRETTY_FUNCTION__.16857> "dynamic_user_acquire") at ../src/basic/log.c:809
#6  0x0000561425f13219 in dynamic_user_acquire (m=<optimized out>, name=0x0, ret=<optimized out>) at ../src/core/dynamic-user.c:81
#7  0x0000561425eb746e in dynamic_creds_acquire (group=0x0, user=0x0, m=0x561427b724d0, creds=<optimized out>) at ../src/core/dynamic-user.c:774
#8  unit_setup_dynamic_creds (u=<optimized out>) at ../src/core/unit.c:4915
#9  0x0000561425ee0190 in service_coldplug (u=0x561427b7ed70) at ../src/core/service.c:1201
#10 0x0000561425ebb44b in unit_coldplug (u=0x561427b7ed70) at ../src/core/unit.h:613
#11 unit_coldplug (u=0x561427b7ed70) at ../src/core/unit.c:3868
#12 0x0000561425ef44f9 in manager_coldplug (m=0x561427b724d0) at ../src/core/manager.c:1466
#13 0x0000561425f24066 in manager_reload (m=0x561427b724d0) at ../src/core/manager.c:3567
#14 invoke_main_loop (m=0x561427b724d0, saved_rlimit_nofile=<optimized out>, saved_rlimit_memlock=<optimized out>, ret_reexecute=<optimized out>, ret_retval=<optimized out>, ret_shutdown_verb=<optimized out>, ret_fds=<optimized out>,
    ret_switch_root_dir=<optimized out>, ret_switch_root_init=<optimized out>, ret_error_message=<optimized out>) at ../src/core/main.c:1753
#15 0x0000561425e78728 in main (argc=<optimized out>, argv=<optimized out>) at ../src/core/main.c:2682
```

Unfortunately I wasn't able to reproduce this, now systemd just says "Unit configuration has fatal error, unit will not be started.", even when updating the package to this version again.

systemd from Debian, 244.1-1. Initially filed at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950409

### PR DESCRIPTION
**Pull request by yuwata**
When unit is reloaded, and the reloaded unit has bad-setting, then `unit_patch_contexts()` is not called and `exec_context::user` and `group` may not be configured.

A minimum reproducer for the case is:
- step 1.
```
$ sudo systemctl edit --full hoge.service
[Service]
Type=oneshot
ExecStart=sleep 1h
```
- step 2.
```
$ sudo systemctl start hoge.service
```
- step 3.
```
$ sudo systemctl edit --full hoge.service
[Service]
Type=oneshot
ExecStart=@bindir@/sleep 1h
DynamicUser=yes
```
Then pid1 crashed.

Fixes #14733.

### CODE REVIEW

**Comment by yuwata** [comment]
Not tested. I will test this later.

File: src/core/dynamic-user.c [hunk 1]
```diff
@@ -770,7 +770,7 @@ int dynamic_creds_acquire(DynamicCreds *creds, Manager *m, const char *user, con
 
                 if (creds->user && (!group || streq_ptr(user, group)))
                         creds->group = dynamic_user_ref(creds->user);
-                else {
+                else if (group) {
```
Comment (keszybz) [inline src/core/dynamic-user.c:773]: This looks trivially correct, because dynamic_user_acquire will assert that the argument it not null. So let's merge.

**Comment by yuwata** [comment]
> The reproducer does not work for me, not sure why. But the patch looks good.

Interesting. The reproducer does not work for my another laptop. Hmm??
