### PR TITLE
core: remove path to transient unit file from unit name maps on stop

### LINKED ISSUE #35190: Getting journal notices `foo.service: Failed to open /run/systemd/transient/foo.service: No such file or directory`
### systemd version the issue has been seen with

systemd 256 (256.7-3)

### Used distribution

Debian testing

### Linux kernel version used

6.11.5-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

No strange and hard-to-reproduce journal notices after normal termination of a transient service.

### Unexpected behaviour you saw

After normal termination of a transient service, systemd reports journal messages (at notice level) like this:

```
Nov 13 23:23:06 host01 systemd[1]: webfsd@wpad.service: Failed to open /run/systemd/transient/webfsd@wpad.service: No such file or directory
```

for example, when querying

```
[~]$ systemctl is-active webfsd@wpad.service
inactive
```

There are no other adverse symptoms except these journal messages.

### Steps to reproduce the problem

It is rather hard to reproduce this problem.  The service mentioned above is started and stopped like this in a NetworkManager dispatcher script:

```bash
wfsdsn="webfsd@wpad.service"

[...]

  (up)

    systemctl --quiet stop "$wfsdsn" 1>/dev/null 2>&1 || :
    systemctl --quiet reset-failed "$wfsdsn" 1>/dev/null 2>&1 || :

    wfsdsn="webfsd@wpad.service"
    systemd-run --quiet                                                 \
                --unit "$wfsdsn"                                        \
                --description "WPAD Server"                             \
                webfsd -F -j -p 80 -R /run/wpad/root -i 127.0.0.1       \
                       -m /run/wpad/mime.types -u www-data -g www-data ;;

  (pre-down)

    systemctl --quiet stop "$wfsdsn" 1>/dev/null 2>&1 || :
    systemctl --quiet reset-failed "$wfsdsn" 1>/dev/null 2>&1 || : ;;
```

Only very rarely after stopping the transient service systemd ends up in the state described above, where it writes these ENOENT journal messages on every access to the inactive transient service.  The only method to let systemd get out of that state is to do a `daemon-reload`.

I have been able to capture the error message in the context of systemd running at debug level.  Looks like this:

```
[11114.902495] host01 systemd[1]: webfsd@wpad.service: Failed to open /run/systemd/transient/webfsd@wpad.service: No such file or directory
[11114.903550] host01 systemd[1]: webfsd@wpad.service: Failed to open /run/systemd/transient/webfsd@wpad.service: No such file or directory
[11141.914007] host01 sudo[15151]: farblos : TTY=pts/0 ; PWD=/home/farblos ; USER=root ; COMMAND=/usr/bin/systemctl log-level debug
[11141.914475] host01 sudo[15151]: pam_unix(sudo:session): session opened for user root(uid=0) by farblos(uid=1000)
[11141.925258] host01 systemd[1]: Setting log level to debug.
[11141.925285] host01 systemd[1]: Sent message type=method_return sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=n/a error-name=n/a error-message=n/a
[11141.925439] host01 systemd[1]: Bus private-bus-connection: changing state RUNNING → CLOSING
[11141.925483] host01 systemd[1]: Bus private-bus-connection: changing state CLOSING → CLOSED
[11141.925526] host01 systemd[1]: Got disconnect on private connection.
[11141.926236] host01 sudo[15151]: pam_unix(sudo:session): session closed for user root
[11149.630996] host01 systemd[1]: Got message type=method_call sender=:1.621 destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/webfsd_40wpad_2eservice interface=org.freedesktop.DBus.Properties member=Get  cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
[11149.631153] host01 systemd[1]: webfsd@wpad.service: Failed to open /run/systemd/transient/webfsd@wpad.service: No such file or directory
[11149.631169] host01 systemd[1]: webfsd@wpad.service: Failed to load configuration: No such file or directory
[11149.631275] host01 systemd[1]: Sent message type=method_return sender=n/a destination=:1.621 path=n/a interface=n/a member=n/a cookie=31602 reply_cookie=2 signature=v error-name=n/a error-message=n/a
[11149.631324] host01 systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=31603 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[11149.631337] host01 systemd[1]: webfsd@wpad.service: Collecting.
[11149.631358] host01 systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=31604 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[11149.632242] host01 systemd[1]: Got message type=method_call sender=:1.621 destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/webfsd_40wpad_2eservice interface=org.freedesktop.DBus.Properties member=Get  cookie=3 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
[11149.632398] host01 systemd[1]: webfsd@wpad.service: Failed to open /run/systemd/transient/webfsd@wpad.service: No such file or directory
[11149.632412] host01 systemd[1]: webfsd@wpad.service: Failed to load configuration: No such file or directory
[11149.632490] host01 systemd[1]: Sent message type=method_return sender=n/a destination=:1.621 path=n/a interface=n/a member=n/a cookie=31605 reply_cookie=3 signature=v error-name=n/a error-message=n/a
[11149.632536] host01 systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=31606 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[11149.632547] host01 systemd[1]: webfsd@wpad.service: Collecting.
[11149.632569] host01 systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=31607 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[11197.090524] host01 systemd[1]: bolt.service: Got notification message from PID 1947 (WATCHDOG=1)
[11197.091069] host01 systemd[1]: systemd-journald.service: Got notification message from PID 1572 (WATCHDOG=1)
[11209.365444] host01 sudo[15163]: farblos : TTY=pts/0 ; PWD=/home/farblos ; USER=root ; COMMAND=/usr/bin/systemctl daemon-reload
```

The error message in question is written by function `unit_load_fragment`:

```c
if (!f)
  return log_unit_notice_errno(u, errno, "Failed to open %s: %m", fragment);
```

as I have confirmed by instrumenting the code.

What seems strange to me is that further above the function just returns if `u->transient`.

That is about everything I can provide.  If you consider this issue interesting enough to follow up on it, I'd appreciate any hints on how to do so.  I have the sources available and can install diagnostic patches, etc.

As a starter, how would one dump the state of a unit to the journal (or some other place)?

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #35190.

### CODE REVIEW

File: src/core/load-fragment.c [hunk 1]
```diff
@@ -6246,7 +6246,12 @@ int unit_load_fragment(Unit *u) {
                  * verify this here. */
                 f = fopen(fragment, "re");
                 if (!f)
-                        return log_unit_notice_errno(u, errno, "Failed to open %s: %m", fragment);
+                        /* We do not rebuild unit_name_map and friends on transient file being stopped.
```
Comment (YHNdnzj) [inline src/core/load-fragment.c]: It appears to me that we should fix the underlying issue then?

Comment (yuwata) [reply src/core/load-fragment.c]: I thought so. But it is heavy and completely waste of time to rebuild the tables after each transient unit stopped.

Of course, it may be possible to remove the relevant entries in the tables, but not sure it is reliable. On successful path, we can do. But I am not sure for all failure paths.

Comment (yuwata) [reply src/core/load-fragment.c]: I will try tomorrow again.

Comment (YHNdnzj) [reply src/core/load-fragment.c]: Yeah, I'm aware that the unit cache logic needs more love (c.f. https://github.com/systemd/systemd/pull/35711). I'd still prefer not to tape over the problem, especially that it's just a log msg and not really new.

**Comment by yuwata** [comment]
@YHNdnzj PTAL.

**Review by YHNdnzj — APPROVED** [review]
LGTM
