### PR TITLE
bus-util: do not print (uint64_t) -1 as is

### LINKED ISSUE #4295: systemctl: show: properly print contents of more properties (instead of generic "[unprintable]" output)
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> latest git snapshot

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> fedora 24 (x86_64)

Currently, `systemctl show` outputs raw value or `[unprintable]`, e.g.,

```
# systemctl -p CPUWeight,RestrictAddressFamilies,MountFlags show systemd-udevd.service
CPUWeight=18446744073709551615
MountFlags=524288
RestrictAddressFamilies=[unprintable]
```

It is hard to understand their meaning.
So, I think `systemctl show` should outputs reader friendly values e.g.

```
# systemctl -p CPUWeight,RestrictAddressFamilies,MountFlags show systemd-udevd.service
CPUWeight=-1
MountFlags=slave
RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #4295 and #6511.

### CODE REVIEW

File: src/shared/bus-util.c [hunk 1]
```diff
@@ -746,7 +748,31 @@ int bus_print_property(const char *name, sd_bus_message *property, bool value, b
                         }
 
                         print_property(name, "%s", result);
-                } else
+
+                } else if (streq(name, "MountFlags")) {
+                        const char *result = NULL;
```
Comment (keszybz) [inline src/shared/bus-util.c:753]: This initialization is unnecessary.
