### PR TITLE
Delay running mount start jobs when we /p/s/mountinfo event source is rate limited

### LINKED ISSUE #20329: Rate limit of mount events makes starting/stopping mount units unreliable
**systemd version the issue has been seen with**
248.5 and 248.6, not 248.3

**Used distribution**
 > openSUSE Tumbleweed

**Linux kernel version used** (`uname -a`)

 > `Linux d142 5.13.4-1-default #1 SMP Thu Jul 22 15:55:06 UTC 2021 (91a0cca) x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Unexpected behaviour you saw**
 > After a batch of (un)mount events which trigger the sd-event rate limit, starting/stopping of (unrelated) `.mount` units becomes unreliable.
> Doing a `umount` followed by a `systemctl start` of the `.mount` unit is successful, but the mount didn't actually happen.
> Doing a `mount` followed by a `systemctl stop` of the `.mount` unit is successful, but the mount is still there.

**Steps to reproduce the problem**
This is a somewhat artificial test. In a real system, this is triggered by setup and teardown of a `chroot` environment, which breaks other services running shortly after it.

```
echo 'tmpfs /mnt tmpfs defaults,nofail 0 0' >> /etc/fstab
systemctl daemon-reload
mkdir -p foo
systemctl start mnt.mount

for ((i=0;i<50;++i)); do mount --bind foo foo; umount foo; done; # Trigger rate limit
umount /mnt; systemctl start mnt.mount; echo $?; mountpoint /mnt; systemctl status mnt.mount; mountpoint /mnt
```

It's expected that after `umount /mnt; systemctl start mnt.mount`, the `mnt.mount` unit is active and `/mnt` mounted. What actually happens is that the `systemctl start mnt.mount` effectively does nothing: The `mnt.mount` unit is (still) up, but `/mnt` is not mounted:

```
0
/mnt is not a mountpoint
● mnt.mount - /mnt
     Loaded: loaded (/etc/fstab; generated)
     Active: active (mounted) since Wed 2021-07-28 09:36:10 UTC; 4s ago
      Where: /mnt
       What: tmpfs
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)
      Tasks: 0 (limit: 4660)
        CPU: 5ms
     CGroup: /system.slice/mnt.mount
/mnt is not a mountpoint
```

There's a clear "happens-before" relationship of `umount` and `systemctl start`, so I would not expect any race condition.

**Additional program output to the terminal or log subsystem illustrating the issue**

Because of the rate limit, the unmount event of `/mnt` is processed after the request to `start mnt.mount`, so at that point systemd believes that the mount is still active and it doesn't actually do the mount. It looks like this in the debug log:

```text
Event source 0x561313e8ad70 (mount-monitor-dispatch) entered rate limit state.
...
mnt.mount: Trying to enqueue job mnt.mount/start/replace
mnt.mount: Installed new job mnt.mount/start as 985
mnt.mount: Enqueued job mnt.mount/start as 985
...
mnt.mount: Job 985 mnt.mount/start finished, result=done
...
Event source 0x561313e8ad70 (mount-monitor-dispatch) left rate limit state.
mnt.mount: Deactivated successfully.
mnt.mount: Changed mounted -> dead
mnt.mount: Consumed 4ms CPU time.
```

What could be done is to force processing of all mount events in the queue whenever a `.mount` unit is queried or changed. That approach should not conflict with #15464.

A workaround is to never mix `systemctl start/stop .mount` and `mount/umount`.

### PR DESCRIPTION
**Pull request by msekletar**
Fixes #20329

### CODE REVIEW

File: src/core/unit.h [hunk 1]
```diff
@@ -662,7 +662,7 @@ typedef struct UnitVTable {
 
         /* If this function is set, it's invoked first as part of starting a unit to allow start rate
          * limiting checks to occur before we do anything else. */
-        int (*test_start_limit)(Unit *u);
+        int (*test_start_inhibitors)(Unit *u);
```
Comment (poettering) [inline src/core/unit.h]: hmm, we use the term "inhibitors" in another context already.

Maybe call this "is_startable()"? or "test_startable()"?

File: src/core/unit.c [hunk 2]
```diff
@@ -1856,8 +1856,8 @@ int unit_start(Unit *u) {
         assert(u);
 
         /* Check start rate limiting early so that failure conditions don't cause us to enter a busy loop. */
-        if (UNIT_VTABLE(u)->test_start_limit) {
-                int r = UNIT_VTABLE(u)->test_start_limit(u);
+        if (UNIT_VTABLE(u)->test_start_inhibitors) {
+                int r = UNIT_VTABLE(u)->test_start_inhibitors(u);
```
Comment (poettering) [inline src/core/unit.c]: doesn't matter, but as per coding style `r` gets this special treatment to be defined at outer-most function scope always, even if only used in a local scope. Given you touch this maybe move `int r;` a few lines up. 

(but doesn't matter of course, and is unrelated to this PR)

File: src/core/mount.c [hunk 3]
```diff
@@ -2148,6 +2148,9 @@ static int mount_test_start_inhibitors(Unit *u) {
                 return r;
         }
 
+        if (sd_event_source_is_ratelimited(u->manager->mount_event_source))
+                return -EAGAIN;
```
Comment (poettering) [inline src/core/mount.c]: I think this check should be done first, and the start limit test only after that, given that the start limit check maintains state

File: src/core/mount.c [hunk 4]
```diff
@@ -1839,6 +1839,16 @@ static bool mount_is_mounted(Mount *m) {
         return UNIT(m)->perpetual || FLAGS_SET(m->proc_flags, MOUNT_PROC_IS_MOUNTED);
 }
 
+static int mount_dispatch_run_queue(sd_event_source *s, void *userdata) {
```
Comment (poettering) [inline src/core/mount.c]: I'd call this mount_on_ratelimit_expire() or so, i.e. focus on when this is called more than what it does

File: src/core/mount.c [hunk 5]
```diff
@@ -1839,6 +1839,16 @@ static bool mount_is_mounted(Mount *m) {
...
+        Manager *m = (Manager*) userdata;
```
Comment (poettering) [inline src/core/mount.c]: you can drop the cast. `void*` converts implicitly in any pointer type you like

File: src/core/mount.c [hunk 6]
```diff
@@ -1839,6 +1839,16 @@ static bool mount_is_mounted(Mount *m) {
...
+
+        assert(m);
+
+        /* By entering ratelimited state we made all mount start jobs not runnable, now rate limit is over so let's
+         * make sure we dispatch them in the next iteration. */
+        return sd_event_source_set_enabled(m->run_queue_event_source, SD_EVENT_ONESHOT);
```
Comment (poettering) [inline src/core/mount.c]: i'd not propagate errors here. Instead always return 0. but if sd_event_source_set_enabled() fails print a brief `log_debug_errno()` line, saying what happened and that we ignore it.

File: src/systemd/sd-event.h [hunk 7]
```diff
@@ -165,6 +165,7 @@ int sd_event_source_set_exit_on_failure(sd_event_source *s, int b);
 int sd_event_source_set_ratelimit(sd_event_source *s, uint64_t interval_usec, unsigned burst);
 int sd_event_source_get_ratelimit(sd_event_source *s, uint64_t *ret_interval_usec, unsigned *ret_burst);
 int sd_event_source_is_ratelimited(sd_event_source *s);
+int sd_event_source_set_ratelimit_expire_callback(sd_event_source *s, sd_event_handler_t callback);
```
Comment (poettering) [inline src/systemd/sd-event.h:169]: please also add entry to src/libsystemd/libsystemd.sym

File: src/libsystemd/sd-event/sd-event.c [hunk 8]
```diff
@@ -2873,6 +2873,13 @@ static int event_source_leave_ratelimit(sd_event_source *s) {
         ratelimit_reset(&s->rate_limit);
 
         log_debug("Event source %p (%s) left rate limit state.", s, strna(s->description));
+
+        if (s->ratelimit_expire_callback) {
+                r = s->ratelimit_expire_callback(s, s->userdata);
+                if (r < 0)
+                        log_error("Rate limit expiration callback of event source (%s) failed: %m, ignoring.", strna(s->description));
```
Comment (poettering) [inline src/libsystemd/sd-event/sd-event.c]: `log_debug_errno(r, …`

File: src/libsystemd/sd-event/sd-event.c [hunk 9]
```diff
@@ -2873,6 +2873,13 @@ static int event_source_leave_ratelimit(sd_event_source *s) {
...
+        }
```
Comment (poettering) [inline src/libsystemd/sd-event/sd-event.c:2965]: So, we need some additional checks here. i.e. we need to make sure that if people free the event source from the callback we don't fuck up. i.e. i think something like this:

```c
if (s->ratelimit_expire_callback) {
                s->dispatching = true;
                r = s->ratelimit_expire_callback(s, s->userdata);
                s->dispatching = false;

                if (r < 0) {
                        log_debug_errno(r, "Ratelimit expiry callback of event source %s (type %s) returned error, %s: %m",
                                        strna(s->description),
                                        event_source_type_to_string(s->type),
                                        s->exit_on_failure ? "exiting" : "disabling");

                        if (s->exit_on_failure)
                                (void) sd_event_exit(e, r);
                }

                if (s->n_ref == 0)
                        source_free(s);
                else if (r < 0)
                        sd_event_source_set_enabled(s, SD_EVENT_OFF);
```
(Setting `s->dispatching` ensures that the event source is not actually freed even if the last reference is dropped by the callback. We then need to catch up with the ref count below)

File: src/libsystemd/sd-event/sd-event.c [hunk 10]
```diff
@@ -2873,6 +2873,13 @@ static int event_source_leave_ratelimit(sd_event_source *s) {
...
+
         return 0;
```
Comment (poettering) [inline src/libsystemd/sd-event/sd-event.c:2967]: event_source_leave_ratelimit() is also called by sd_event_source_set_ratelimit() in some cases. I think in that case we really shouldn't invoke the callback though (rule should be: invoke callbacks only when the event loop is run, not when it is configured). i.e. add a boolean or so as parameter to the function that controls whether to call the callbacks or to skip it.

File: src/libsystemd/sd-event/sd-event.c [hunk 11]
```diff
@@ -2873,6 +2873,13 @@ static int event_source_leave_ratelimit(sd_event_source *s) {
...
```
Comment (poettering) [inline src/libsystemd/sd-event/sd-event.c:2968]: hmm, so, when process_timer() is called and as effect we might call the ratelimit expiry callback I think we should not continue with the processing but immediately go for the next event loop iteration. Specifically:

1. whenever we actually invoke such a callback,  event_source_leave_ratelimit() should return with a return code of 1.
2. whenever process_timer() sees that for any of the event sources it should also return with an exit code of 1 (but call the callback for all event sources where it is defined)
3. whenever sd_event_wait() sees that it should (after all other event sources have been process) put the event loop into INITIAL state and return 0, rather than PENDING state and return 1.

Why? because the ratelimit expiry callbacks likely reenable event sources, and if they did so we should first see if there's something pending for them before we actually dispatch a proper IO event or so. sd_event_wait() returns 1 if the caller should call sd_event_dispatch() next (i.e. there's an event source ready to be dispatched), but returns 0 if it should just be called again (i.e. there's nothing to be dispatched). Thus, if one of these expiry callbacks are called we must make sure sd_event_wait() consequently returns 0 so that we then check all IO sources properly again and take any event source that was enabled back into consideration.

File: src/libsystemd/sd-event/sd-event.c [hunk 12]
```diff
@@ -4040,9 +4067,16 @@ _public_ int sd_event_wait(sd_event *e, uint64_t timeout) {
...
                 goto finish;
 
-        r = process_inotify(e);
+        r = process_timer(e, e->timestamp.monotonic, &e->monotonic);
         if (r < 0)
                 goto finish;
+        else if (r == 1) {
+                /* Ratelimit expiry callback was called. Let's postpone processing pending sources and
+                 * put loop in the initial state in order to evaluate (in the next iteration) also sources
+                 * there were potentially re-enabled by the callback. */
```
Comment (poettering) [inline src/libsystemd/sd-event/sd-event.c]: maybe add comment: that underlines that the ratelimiting is implemented in the CLOCK_MONOTONIC clock, and thus we only do this special handling for CLOCK_MONOTONIC here.

(otherwise it might just appear too surprising that we don't do anything like this for the other process_timer() calls above)

File: src/libsystemd/sd-event/sd-event.c [hunk 13]
```diff
@@ -2841,7 +2841,7 @@ static int event_source_enter_ratelimited(sd_event_source *s) {
         return r;
 }
 
-static int event_source_leave_ratelimit(sd_event_source *s) {
+static int event_source_leave_ratelimit(sd_event_source *s, bool callback) {
```
Comment (poettering) [inline src/libsystemd/sd-event/sd-event.c]: maybe call the bool `run_callback` or so?

File: src/libsystemd/sd-event/sd-event.c [hunk 14]
```diff
@@ -3089,9 +3114,11 @@ static int process_timer(
                          * again. */
                         assert(s->ratelimited);
 
-                        r = event_source_leave_ratelimit(s);
+                        r = event_source_leave_ratelimit(s, true);
```
Comment (poettering) [inline src/libsystemd/sd-event/sd-event.c]: for boolean arguments where it's really not clear when looking at a function invocation what they might trigger we started to add inline comments, would be good to do this here too. Specifically:

```c
r = event_source_leave_ratelimit(s, /* run_callback= */ true);
```

File: src/libsystemd/sd-event/sd-event.c [hunk 15]
```diff
@@ -4411,14 +4445,21 @@ _public_ int sd_event_source_set_ratelimit(sd_event_source *s, uint64_t interval
 
         /* When ratelimiting is configured we'll always reset the rate limit state first and start fresh,
          * non-ratelimited. */
-        r = event_source_leave_ratelimit(s);
+        r = event_source_leave_ratelimit(s, false);
```
Comment (poettering) [inline src/libsystemd/sd-event/sd-event.c]: as above, maybe:

```c
r = event_source_leave_ratelimit(s, /* run_callback= */ false);
```

File: src/core/unit.c [hunk 16]
```diff
@@ -1852,12 +1852,13 @@ static bool unit_verify_deps(Unit *u) {
 int unit_start(Unit *u) {
         UnitActiveState state;
         Unit *following;
+        int r;
 
         assert(u);
 
         /* Check start rate limiting early so that failure conditions don't cause us to enter a busy loop. */
```
Comment (yuwata) [inline src/core/unit.c]: Maybe, it is better to update the comment?

**Comment by poettering** [comment]
>  Am I missing something?

Yes, you did ;-) — I had already removed the comment you are replying to less than 1min after I posted it ;-)

**Comment by poettering** [comment]
lgtm

**Comment by DaanDeMeyer** [comment]
We might need to revert https://github.com/systemd/systemd/pull/20531 which this PR builds upon so it'd be great if we could wait with merging this PR until we figure out what to do with #20531.

**Comment by poettering** [comment]
Now that #21030 has been merged, could you please rebase, @msekletar?

**Comment by msekletar** [comment]
Will do, next week though.

**Comment by msekletar** [comment]
Rebased

**Comment by poettering** [comment]
ubuntu CI times out or is not responding. Seems overloaded. Let's hope for the best. merging.
