### PR TITLE
network: do not always bump MTU with additional 4bytes

### LINKED ISSUE #12552: networkd: wrongly automatically increases MTU for a 4 bytes
**systemd version the issue has been seen with**
> systemd 242 (242.29-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Linux r1.opentech.local 5.0.13-arch1-1-ARCH #1 SMP PREEMPT Sun May 5 18:05:41 UTC 2019 x86_64 GNU/Linux

**Expected behaviour you didn't see**
 > systemd-networkd is set user-defined MTU values.

**Unexpected behaviour you saw**
 > systemd-networkd is set MTU +4 bytes for underlayer interfaces.

**Steps to reproduce the problem**

po1.netdev:
```
[NetDev]
Name=po1
Kind=bond
MTUBytes=1500

[Bond]
Mode=802.3ad
TransmitHashPolicy=layer2+3
LACPTransmitRate=fast
MIIMonitorSec=0.1
```

po1.network:
```
[Match]
Name=po1

[Network]
VLAN=vlan6
```

ten0.link:
```
[Match]
MACAddress=3c:fd:fe:aa:5e:f8

[Link]
Name=ten0
```

ten0.network:
```
[Match]
MACAddress=3c:fd:fe:aa:5e:f8

[Network]
Bond=po1
```

ten1.link:
```
[Match]
MACAddress=3c:fd:fe:aa:5e:f9

[Link]
Name=ten1
```

ten1.network:
```
[Match]
MACAddress=3c:fd:fe:aa:5e:f9

[Network]
Bond=po1
```

vlan6.netdev:
```
[NetDev]
Name=vlan6
Kind=vlan
MTUBytes=1500

[VLAN]
Id=6
```

vlan6.network:
```
[Match]
Name=vlan6

[Address]
Address=100.100.100.2/24
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #12552.

### CODE REVIEW

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -1432,6 +1432,42 @@ int link_set_mtu(Link *link, uint32_t mtu, bool force) {
...
+static uint32_t link_get_stacked_netdevs_mtu(Link *link) {
+        uint32_t mtu = 0;
+        NetDev *dev;
+        Iterator i;
+
+        HASHMAP_FOREACH(dev, link->network->stacked_netdevs, i)
+                if (dev->kind == NETDEV_KIND_VLAN && dev->mtu > 0)
+                        /* See vlan_dev_change_mtu() in kernel. */
+                        mtu = MAX(mtu, link_reduces_vlan_mtu(link) ? dev->mtu + 4 : dev->mtu);
+
```
Comment (ssahani) [inline src/network/networkd-link.c:1449]: Why we are bumping up the MTU. Should not the user responsible for this ? I think this kind of conf should be handled by the user and let kernel deicides.

Comment (yuwata) [reply src/network/networkd-link.c:1449]: Otherwise, vlan devices may not work... Of course, just warning about that may be ok. But, when we know what is a minimal requirement, then I think it may be helpful to bump MTU.

Comment (yuwata) [reply src/network/networkd-link.c:1449]: And if we do not bump MTU, then user may not find why vlan does not work. See #5972.

Comment (ssahani) [reply src/network/networkd-link.c:1449]: For that we just need to log it and should not increase.

**Comment by yuwata** [comment]
@ssahani Updated. Now, `MTUBytes=` setting is always honored, even if it is not valid. See the first commit.
And, if `MTUBytes=` is set for vlan or macvlan, but not for underlying device, and the current MTU bytes of underlying device is not sufficient, then the MTU will be increased. See the second commit.

@ssahani WDYT? Still you do not like the second commit?

**Comment by ssahani** [comment]
This makes more sense now. LGTM. Thanks.

**Comment by yuwata** [comment]
Thanks @ssahani.
