### PR TITLE
cgroup-util: kill also threads

### LINKED ISSUE #12262: "A stop job is running for User Manager for UID 1000"
I hope this is the right place to report/post/ask this.
When I want to shutdown or reboot my system (using `reboot` or `shutdown now`), the system is not shutting down immediately but rather waits 1m30s and displays the following:
```A stop job is running for User Manager for UID 1000 (1min 10s / 2min)```
I tried to find out what is causing this, creating a log according to [Debugging](https://freedesktop.org/wiki/Software/systemd/Debugging/).
Unfortunately, I can not find out myself what is causing the issue. What can I do to solve this issue?
I attached the log to the end of this report.

**systemd version the issue has 
been seen with**
> 241.67

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > System shuts down properly without a delay

**Unexpected behaviour you saw**
 > Delay when shutting down

**Steps to reproduce the problem**
Shutdown the system

[shutdown-log.txt](https://github.com/systemd/systemd/files/3060571/shutdown-log2.txt)

### PR DESCRIPTION
**Pull request by topimiettinen**
It's possible for a zombie process to have live threads. These are not listed
in /sys in "cgroup.procs" but they show up in "tasks" nodes. When killing a
cgroup, let's kill threads instead of processes, so the live threads of a
zombie get killed too.

Closes #12262.

### CODE REVIEW

**Comment by poettering** [comment]
This looks incorrect. Killing the thread group leader should bring the whole process down. We should not go and kill individual threads, that's just gonna break stuff. apps should know better how to bring their threads down if we want to kill them, hence we should only kill the thread group leader and the rest will follow automatically.

Also, this patch doesn't work on cgroupsv2. There, the "tasks" file is gone entirely, since it never made sense to expose cgroups per-thread...

And no, to my knowledge if a thread group leader dies the thread group goes away wholly. So this doesn't make semantical sense to me at all I must say

**Comment by topimiettinen** [comment]
The problem is that the thread group leader is a zombie while other threads are alive. If "tasks" will not available in the future, what would you suggest instead?

This makes a difference as the shutdown is clean again, so something must be better than before. As we're going to kill everything in the cgroup anyway, I don't think killing some threads earlier than others should break any services.

**Comment by topimiettinen** [comment]
Whoops, I looked at wrong (parent) "cgroup.procs", the process is actually listed. You're right, let's scratch this.

**Comment by topimiettinen** [comment]
Actually I was probably looking at `/sys/fs/cgroup/systemd/user.slice/user-1000.slice/user\@1000.service/dbus.service/cgroup.procs` (which includes the PID) instead of `/sys/fs/cgroup/unified/user.slice/user-1000.slice/user\@1000.service/dbus.service/cgroup.procs`, which is indeed empty. How can they be different?

**Comment by Werkov** [comment]
> It's possible for a zombie process to have live threads.
I was only able to recreate this by calling `syscall(SYS_exit, 0)` directly as recent glibc uses exit_group(2). But lets assume this somehow happens.

Signal is delivered to arbitrary thread but if it is a fatal signal all threads in the threadgroup are forcefully terminated.

Sending a signal to PID of the whole process should be thus enough. @topimiettinen What kernel version/release is this?

**Comment by topimiettinen** [comment]
@Werkov Debian Buster 4.19.0-5-amd64.

The problem is not killing the process, but noticing first that it exists. Cgroup v2 "cgroup.procs" does not list zombies.

**Comment by cdown** [comment]
Chiming in from cgroup v2 side, I agree with @poettering in saying that I'm not convinced this makes sense. If the thread group leader is AWOL and gone zombified, that's something that any init can't really hope to sensibly deal with. This may "fix" this bug, but I'm worried it will cause an indefinite slow grind of undebuggable new ones, since applications no longer control thread lifetime.

**Comment by topimiettinen** [comment]
This seems to be a bug in kernel and it may be fixed one day, so then this change for systemd would not be needed. The question for systemd is how new kernels we require and how critical we see this bug. For most participants this seems to be in heisenbug / minor annoyance category, so perhaps it's not worth changing systemd after all.

**Comment by cdown** [comment]
Yeah, if the process iterator mistakenly skips zombies with live threads, that's a kernel bug. I'm just not convinced we should try to do anything about it in systemd.

**Comment by poettering** [comment]
Hmm, patch looks OK if this is what it takes to fix things on old kernels. But at least there should be a comment about this, plus a hint when this got fixed in the kernels. Also, can we find a way to not require the "triple" killing spree on kernels that don't need it?

It should be possible to cut this down to "double" killing at least, by checking cg_unified_controller(SYSTEMD_CGROUP_CONTROLLER) first, no?

Does this bug actually apply to both cgroupv1 and cgroupv2 equally?

/cc @htejun

**Comment by topimiettinen** [comment]
The bug is only present in v2:
```
28767 pts/0    Zl     0:00 [zombie-thread2] <defunct>
$ grep 28767 /sys/fs/cgroup/unified/user.slice/user-1000.slice/session-1.scope/cgroup.procs 
$ grep 28767 /sys/fs/cgroup/systemd/user.slice/user-1000.slice/session-1.scope/cgroup.procs 
28767

cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
```
So the extra killing spree could be avoided on v1. Also, there's no need ever to use v1 "threads".  

After having killed all processes, the number of surviving zombie threads to be killed should be very low (typically there are none) and thus there should not be too much wasted effort anyway.

**Comment by Werkov** [comment]
FTR, @htejun already prepared a [fix](https://www.spinics.net/lists/cgroups/msg22387.html) in the listing of such processes.

Also, when I consider it now, I'm not convinced a process (not task/thread) with live threads is a true zombie. The current behavior is to send SIGCHILD to the parent only when the last thread of the process terminates. All in all, do we need any (temporary) fix in systemd?

**Comment by topimiettinen** [comment]
@Werkov It's something in between. Anyway, the fix for the kernel bug is in 5.2-rc5 (c03cd7738a83). With a fixed kernel (or cgroupsv1) the zombies are reported correctly. The commit adds support for older kernels with cgroupsv2. I'd expect that downstreams either fix their kernels, or use this a patch like this to avoid doing that. Alternatively systemd upstream can also include the fix and it seems @poettering is agreeable to that.

**Comment by Werkov** [comment]
> I'd expect that downstreams either fix their kernels, or use this a
> patch like this to avoid doing that.
+1

> Alternatively systemd upstream can also include the fix 
-1

File: src/basic/cgroup-util.c [hunk 1]
```diff
@@ -312,6 +317,30 @@ int cg_kill(
...
+                return r;
+
+        r = cg_unified_controller(controller);
+        if (r < 0)
+                return r;
+        if (r == 0) /* doesn't apply to legacy hierarchy */
+                return 0;
+
+        /* Kill remaining threads as a workaround for kernel bug for cgroupsv2, fixed in 5.2-rc5 (c03cd7738a83) */
+        return cg_kill_items(controller, path, sig, flags, s, log_kill, userdata, "cgroup.threads");
```
Comment (poettering) [inline src/basic/cgroup-util.c:342]: hmm, we probably can further conditionalize this, to only apply to `sig == SIGKILL`, right?

Comment (topimiettinen) [reply src/basic/cgroup-util.c:342]: It seems that the zombie reacts to other signals too and then for example `unit_kill_context()` can send a SIGHUP. I don't think we can make this optimization.

Comment (poettering) [reply src/basic/cgroup-util.c:342]: not sure i follow? i mean there are two kinds of signals in a way:

1. SIGKILL + SIGSTOP which are kernel operations on tasks pretty much, which cannot be caught, blocked or ignored. They execute a kernel operation on a task, and userspace cannot  interfere, see signal(7) about that.

2. All the others are mostly just friendly requests to the app: the app can catch them, can block them, can ignore them. The kernel only operates on them if the app doesn't handle them themselves.

This means that there's no need to deliver SIGTERM, SIGHUP and friends to all threads/zombie threads or so of a process, because they are just friendly anyway, and if a process is in such a weird state it's not going to react to friendly requests anyway. OTOH SIGKILL/SIGSTOP is something we need to rely on, because that is supposed to really make evreything go away. Hence as I understand it should matter to deliver SIGKILL (and maybe SIGSTOP) to all those weird threads, but for the other kind of signals we don't have to and probably really shouldn't.

Do I make any sense?

Comment (topimiettinen) [reply src/basic/cgroup-util.c:342]: OK, I'll make an update.
