### PR TITLE
find-esp: downgrade and ignore error on retrieving PART_ENTRY_SCHEME

### LINKED ISSUE #25332: Regression in 252: bootcl fails to probe PART_ENTRY_SCHEME on /dev/dm-0
### systemd version the issue has been seen with

252.1

### Used distribution

Arch Linux

### Linux kernel version used

6.0.6

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

After systemd update from **251.7** to **252.1** invocation of `bootctl` command fails at probing `/dev/dm-0` (encrypted LUKS partition).

In the result `bootctl` command is unusable. I guess it should just ignore encrypted LUKS devices when it does probing?

In below examples my EFI partition is mounted at `/boot/efi`.

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# /usr/bin/bootctl --path=/boot/efi --no-variables update
/dev/dm-0: Failed to probe PART_ENTRY_SCHEME: Input/output error

$ bootctl -p
/boot/efi
dm-0: Failed to query ID_PART_ENTRY_SCHEME: No such file or directory

$ bootctl -x
dm-0: Failed to query ID_PART_ENTRY_SCHEME: No such file or directory
/boot/efi
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #25332.

### CODE REVIEW

**Comment by Maryse47** [comment]
I can confirm this fixes mentioned issue.

**Comment by yuwata** [comment]
@Maryse47 Thank you for the confirmation!

File: src/shared/find-esp.c [hunk 1]
```diff
@@ -177,7 +177,8 @@ static int verify_esp_udev(
 
         r = sd_device_get_property_value(d, "ID_PART_ENTRY_SCHEME", &v);
         if (r < 0)
-                return log_error_errno(r, "Failed to get device property: %m");
+                return log_full_errno(searching && r == -ENOENT ? LOG_DEBUG : LOG_ERR, r,
```
Comment (poettering) [inline src/shared/find-esp.c]: hmm I think we should return EADDRNOTAVAIL in case `searching && r == -ENOENT` holds, instead of r. After all, if ID_PART_ENTRY_SCHEME is not set it's not the partition we are searching for.

File: src/shared/find-esp.c [hunk 2]
```diff
@@ -638,7 +640,8 @@ static int verify_xbootldr_udev(
 
         r = sd_device_get_property_value(d, "ID_PART_ENTRY_SCHEME", &type);
         if (r < 0)
-                return log_device_error_errno(d, r, "Failed to query ID_PART_ENTRY_SCHEME: %m");
+                return log_device_full_errno(d, searching && r == -ENOENT ? LOG_DEBUG : LOG_ERR, r,
+                                             "Failed to query ID_PART_ENTRY_SCHEME: %m");
```
Comment (poettering) [inline src/shared/find-esp.c:651]: as above

**Comment by yuwata** [comment]
@poettering Thank you for the review. The error code is updated. PTAL!

(Please backport at least the first commit to v252 stable.)

**Comment by Maryse47** [comment]
@poettering could you re-review and merge it? thx.
