### PR TITLE
busctl: fix introspecting DBus properties

### LINKED ISSUE #26033: busctl introspect fails to show values for properties
### systemd version the issue has been seen with

252.4

### Used distribution

Gentoo

### Linux kernel version used

5.15.85-gentoo-dist

### CPU architectures issue was seen on

x86_64

### Component

_No response_

### Expected behaviour you didn't see

busctl introspect should show values for properties

```
$ busctl introspect org.freedesktop.network1 /org/freedesktop/network1                                            
NAME                                TYPE      SIGNATURE RESULT/VALUE FLAGS
org.freedesktop.DBus.Introspectable interface -         -            -
.Introspect                         method    -         s            -
org.freedesktop.DBus.Peer           interface -         -            -
.GetMachineId                       method    -         s            -
.Ping                               method    -         -            -
org.freedesktop.DBus.Properties     interface -         -            -
.Get                                method    ss        v            -
.GetAll                             method    s         a{sv}        -
.Set                                method    ssv       -            -
.PropertiesChanged                  signal    sa{sv}as  -            -
org.freedesktop.network1.Manager    interface -         -            -
.Describe                           method    -         s            -
.DescribeLink                       method    i         s            -
.ForceRenewLink                     method    i         -            -
.GetLinkByIndex                     method    i         so           -
.GetLinkByName                      method    s         io           -
.ListLinks                          method    -         a(iso)       -
.ReconfigureLink                    method    i         -            -
.Reload                             method    -         -            -
.RenewLink                          method    i         -            -
.RevertLinkDNS                      method    i         -            -
.RevertLinkNTP                      method    i         -            -
.SetLinkDNS                         method    ia(iay)   -            -
.SetLinkDNSEx                       method    ia(iayqs) -            -
.SetLinkDNSOverTLS                  method    is        -            -
.SetLinkDNSSEC                      method    is        -            -
.SetLinkDNSSECNegativeTrustAnchors  method    ias       -            -
.SetLinkDefaultRoute                method    ib        -            -
.SetLinkDomains                     method    ia(sb)    -            -
.SetLinkLLMNR                       method    is        -            -
.SetLinkMulticastDNS                method    is        -            -
.SetLinkNTP                         method    ias       -            -
.AddressState                       property  s         "routable"   emits-change
.CarrierState                       property  s         "carrier"    emits-change
.IPv4AddressState                   property  s         "routable"   emits-change
.IPv6AddressState                   property  s         "routable"   emits-change
.NamespaceId                        property  t         4026531840   const
.OnlineState                        property  s         "online"     emits-change
.OperationalState                   property  s         "routable"   emits-change
```

### Unexpected behaviour you saw

But it seems that f2f7785d7a47ffa48ac929648794e1288509ddd8 broke something so that no property values are shown. I rebuilt the package with a patch to revert this particular commit and now property values are shown again.

```
$ busctl introspect org.freedesktop.resolve1 /org/freedesktop/resolve1
NAME                                TYPE      SIGNATURE     RESULT/VALUE           FLAGS
org.freedesktop.DBus.Introspectable interface -             -                      -
.Introspect                         method    -             s                      -
org.freedesktop.DBus.Peer           interface -             -                      -
.GetMachineId                       method    -             s                      -
.Ping                               method    -             -                      -
org.freedesktop.DBus.Properties     interface -             -                      -
.Get                                method    ss            v                      -
.GetAll                             method    s             a{sv}                  -
.Set                                method    ssv           -                      -
.PropertiesChanged                  signal    sa{sv}as      -                      -
org.freedesktop.resolve1.Manager    interface -             -                      -
.FlushCaches                        method    -             -                      -
.GetLink                            method    i             o                      -
.RegisterService                    method    sssqqqaa{say} o                      -
.ResetServerFeatures                method    -             -                      -
.ResetStatistics                    method    -             -                      -
.ResolveAddress                     method    iiayt         a(is)t                 -
.ResolveHostname                    method    isit          a(iiay)st              -
.ResolveRecord                      method    isqqt         a(iqqay)t              -
.ResolveService                     method    isssit        a(qqqsa(iiay)s)aayssst -
.RevertLink                         method    i             -                      -
.SetLinkDNS                         method    ia(iay)       -                      -
.SetLinkDNSEx                       method    ia(iayqs)     -                      -
.SetLinkDNSOverTLS                  method    is            -                      -
.SetLinkDNSSEC                      method    is            -                      -
.SetLinkDNSSECNegativeTrustAnchors  method    ias           -                      -
.SetLinkDefaultRoute                method    ib            -                      -
.SetLinkDomains                     method    ia(sb)        -                      -
.SetLinkLLMNR                       method    is            -                      -
.SetLinkMulticastDNS                method    is            -                      -
.UnregisterService                  method    o             -                      -
.CacheStatistics                    property  (ttt)         -                      -
.CurrentDNSServer                   property  (iiay)        -                      emits-change
.CurrentDNSServerEx                 property  (iiayqs)      -                      emits-change
.DNS                                property  a(iiay)       -                      emits-change
.DNSEx                              property  a(iiayqs)     -                      emits-change
.DNSOverTLS                         property  s             -                      -
.DNSSEC                             property  s             -                      -
.DNSSECNegativeTrustAnchors         property  as            -                      -
.DNSSECStatistics                   property  (tttt)        -                      -
.DNSSECSupported                    property  b             -                      -
.DNSStubListener                    property  s             -                      -
.Domains                            property  a(isb)        -                      -
.FallbackDNS                        property  a(iiay)       -                      const
.FallbackDNSEx                      property  a(iiayqs)     -                      const
.LLMNR                              property  s             -                      -
.LLMNRHostname                      property  s             -                      emits-change
.MulticastDNS                       property  s             -                      -
.ResolvConfMode                     property  s             -                      -
.TransactionStatistics              property  (tt)          -                      -
```

### Steps to reproduce the problem

Can be reproduced by introspecting any d-bus object that has properties

```
busctl introspect org.freedesktop.network1 /org/freedesktop/network1
````

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for f2f7785d7a47ffa48ac929648794e1288509ddd8.

Fixes #26033.

### CODE REVIEW

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by YHNdnzj** [comment]
@DaanDeMeyer CI errors don't seem related. Ubuntu is having some problems I guess...

**Review by bluca — APPROVED** [review]

File: src/busctl/busctl.c [hunk 1]
```diff
@@ -1043,6 +1044,21 @@ static int introspect(int argc, char **argv, void *userdata) {
...
+                        if (type == SD_BUS_TYPE_STRUCT_BEGIN)
+                                signature = strjoin(CHAR_TO_STR(SD_BUS_TYPE_STRUCT_BEGIN), contents, CHAR_TO_STR(SD_BUS_TYPE_STRUCT_END));
+                        else if (type == SD_BUS_TYPE_DICT_ENTRY_BEGIN)
+                                signature = strjoin(CHAR_TO_STR(SD_BUS_TYPE_DICT_ENTRY_BEGIN), contents, CHAR_TO_STR(SD_BUS_TYPE_DICT_ENTRY_END));
+                        else if (contents)
+                                signature = strjoin(CHAR_TO_STR(type), contents);
+                        else
+                                signature = strdup(CHAR_TO_STR(type));
+                        if (!signature)
+                                return log_oom();
```
Comment (poettering) [inline src/busctl/busctl.c:1060]: that's quite baroque.

much simpler: peek the type before you enter the `v` container, above.

i.e. don't combine what was split for you, just use the combined type ebfore

Comment (poettering) [reply src/busctl/busctl.c:1060]: → #26076
