### PR TITLE
core/cgroup: accepts MemorySwapMax=0

### LINKED ISSUE #8363: MemorySwapMax=0 shouldn't mean infinity
### Submission type

 - Bug report

### systemd version the issue has been seen with

> All versions.

### Used distribution

> centos7, systemd 234

### In case of bug report: Expected behaviour you didn't see

> Setting MemorySwapMax=0 should set cgroup knob memory.swap.max to 0.

### In case of bug report: Unexpected behaviour you saw

> systemd interprets MemorySwapMax=0 as infinity and ends up setting memory.swap.max to max.

### In case of bug report: Steps to reproduce the problem

> Set MemorySwapMax=0 in any unit and reload it.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #8363.

### CODE REVIEW

**Comment by yuwata** [comment]
@htejun Please take a look.

**Comment by htejun** [comment]
Looks good to me. Thanks a lot!

File: src/core/dbus-util.h [hunk 1]
```diff
@@ -314,7 +314,7 @@
                         return r;                                       \
                                                                         \
                 v = scale(raw, UINT32_MAX);                             \
-                if (v <= 0 || v >= UINT64_MAX)                          \
+                if (!check(v) || v >= UINT64_MAX)                       \
```
Comment (keszybz) [inline src/core/dbus-util.h]: This relies on the fact that `check(v)` returns `v` if `check` is not defined. So it is equivalent to `v > 0`, or `!v`, and the result is correct. But I think this is just too much magic. I'd just prefer to have the lower limit just passed in as a parameter to `BUS_DEFINE_SET_CGROUP_SCALE`, or maybe to always give the `check` parameter.

The code was already doing that before in BUS_DEFINE_SET_CGROUP_WEIGHT, but I think the code should be reworked to avoid this pattern.

I think it'd also make a lot of sense to move BUS_DEFINE_SET_CGROUP_* macros to the .c file. No need to have them in the header.

**Comment by yuwata** [comment]
@keszybz Thank you for the review. I've force-pushed the updated code. The main updates are
- move `BUS_DEFINE_SET_CGROUP_...` macros to dbus-cgroup.c as suggested.
- explicitly set checking functions and special strings.

However, I've dropped your proposal that lower limit should be set in SCALE macro instead of checking function. I tried to set lower limit. However, the line `v >= 0` for unsigned value appears in the defined function for swap, and then I got `warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]`. Of course, this can be suppressed by setting a pragma. But the trivial checking function was already defined for WEIGHT macro. Then, I decided to use it also in SCALE macro. What do you think?

**Comment by keszybz** [comment]
```
autopkgtest login: 
---------------------------------------------------
<VirtSubproc>: failure: Timed out on waiting for ssh connection
autopkgtest [06:20:22]: ERROR: testbed failure: cannot send to testbed: [Errno 32] Broken pipe
```
