### PR TITLE
networkd: Do not send requests to create netdevs if they exists.

### LINKED ISSUE #5448: systemd-networkd: Main Ethernet Interface fails after service restart
[dmesg.txt](https://github.com/systemd/systemd/files/800254/dmesg.txt)

### systemd version the issue has been seen with

> 232

### Used distribution

> ArchLinux, Kernel: 4.9.11-1, also seen on Kernel: 4.8.13

### Expected behaviour you didn't see

> IDX LINK             TYPE               OPERATIONAL SETUP     
>  1 lo               loopback           carrier     unmanaged 
>  2 ens3             ether              routable    configured

### Unexpected behaviour you saw

> IDX LINK             TYPE               OPERATIONAL SETUP     
>  1 lo               loopback           carrier     unmanaged 
>  2 ens3             ether              degraded   failed

ens3 config: 

>[Match]
>Name = ens3
>[Network]
>DHCP = ipv4
>Address = $IPv6-Address
>Tunnel = $Tunnel-Interface
>IPForward = ipv4
>IPMasquerade = true

After boot, network works fine, but executing "systemctl restart systemd-networkd" causes ens3 so change to "failed" state and the machine isn't reachable anymore.
Logs say:
> ens3: Could not join netdev: Invalid argument

Rebooting the whole machine, brings the network back up. 

Edit: added dmesg output

### PR DESCRIPTION
**Pull request by ssahani**
If the netdev already exists we should not send requests to
kernel to create them.

fixes #5448

### CODE REVIEW

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -2276,6 +2276,9 @@ static int link_enter_join_netdev(Link *link) {
 
         HASHMAP_FOREACH(netdev, link->network->stacked_netdevs, i) {
 
+                if (netdev->ifindex)
```
Comment (poettering) [inline src/network/networkd-link.c]: please see CODING_STYLE: do not rely on C's downgrade-to-bool feature for anything that is actually a bool, or for ptrs. i.e. for comparing numeric values, do this explicitly with != 0 or so

Comment (ssahani) [reply src/network/networkd-link.c]: OK updated.

File: src/network/networkd-link.c [hunk 2]
```diff
@@ -2276,6 +2276,9 @@ static int link_enter_join_netdev(Link *link) {
 
         HASHMAP_FOREACH(netdev, link->network->stacked_netdevs, i) {
 
+                if (netdev->ifindex > 0)
+                        return link_joined(link);
```
Comment (keszybz) [inline src/network/networkd-link.c]: I don't know this part of the code at all, but this will terminate the loop if any of the interfaces in `stacked_netdevs` exists. This looks suspicious.

Comment (ssahani) [reply src/network/networkd-link.c]: yes right updated
