### PR TITLE
shared/calendarspec: fix normalization when DST is negative

### LINKED ISSUE #32039: Timers started looping service at 2024-03-31 00:00:00 UTC
### systemd version the issue has been seen with

255

### Used distribution

Archlinux 2024-03-30

### Linux kernel version used

6.8.2-arch2-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Timers running normally after 2024-03-31 00:00:00 UTC.

### Unexpected behaviour you saw

At 2024-03-31 00:00:00 UTC, some (at least three) timers started going into a loop of restarting their services. Two physical hosts and a couple of virtual hosts in the GMT time zone were affected. One physical host in the GMT+1 time zone was unaffected despite practically identical setup.

I noticed the issue from a Zabbix warning notifying me that `shadow.service` was failing. I noticed that it was failing because of `start-limit-hit`, and that `shadow.timer` was trying to start it continuously. `shadow.service` is a very short-lived service, so the restart loop meant many starts per second.

I tried stopping the timer, starting the service manually (that worked), then re-starting the timer, but the symptoms re-occurred. I tried reboot one of the hosts completely, but the issue prevailed.

As I was going to sleep, I just shutdown one physical host and disabled the affected timers to check them the next day.  The next day, when I checked my hosts, everything was working normally again and I was able to re-start the stopped timers without any issues.

I suspect that this has to do with the DST change that happened on that day.

I also posted a thread about this on the Arch subreddit [here](https://www.reddit.com/r/archlinux/comments/1bs6361/some_systemd_timers_prominently_shadowtimer/). Up to this point, wwo other people had symptoms that seem compatible with mine ([link](https://www.reddit.com/r/archlinux/comments/1bs6361/some_systemd_timers_prominently_shadowtimer/kxevgbv/). [link](https://www.reddit.com/r/archlinux/comments/1bs6361/some_systemd_timers_prominently_shadowtimer/kxggukh/)). Note that all of these peoples are in the GMT time zone, which is in line with my observation: the only host not affected on my end was in GMT+1 to start with.

One can easily check whether my hosts were impacted or not by running:

```
journalctl --since "2024-03-31 00:00:00" --until "2024-03-31 00:05:00"
```

### Steps to reproduce the problem

Apologies as I didn't have time yet to reproduce this issue. Reproducing it seems a bit complex as I'll need to set up a VM and do the following:

* Set up a VM with the physical clock set to 2024-03-29 (well before the issue) in the GMT time zone
* Shut down the VM, fast forward to 2024-03-30 23:55
* Observe as the VM runs over to 2024-03-31 00:00:00
* Observe whether `shadow.service` goes into the aforementioned restart loop

If I get around to that in the near future, I'll report here.

### PR DESCRIPTION
**Pull request by kmeaw**
When trying to calculate the next firing of 'hourly', we'd lose the tm_isdst value on the next iteration.

On most systems in Europe/Dublin it would cause a 100% cpu hang due to timers restarting.

This happens in Europe/Dublin because Ireland defines the Irish Standard Time as UTC+1, so winter time is encoded in tzdata as negative 1 hour of daylight saving.

Before this patch:
```
$ env TZ=Europe/Dublin systemd-analyze calendar --base-time='Sat 2025-03-29 22:00:00 UTC' --iterations=5 'hourly'
  Original form: hourly
Normalized form: *-*-* *:00:00
    Next elapse: Sat 2025-03-29 23:00:00 GMT
       (in UTC): Sat 2025-03-29 23:00:00 UTC
       From now: 13h ago
   Iteration #2: Sun 2025-03-30 00:00:00 GMT
       (in UTC): Sun 2025-03-30 00:00:00 UTC
       From now: 12h ago
   Iteration #3: Sun 2025-03-30 00:00:00 GMT  <-- note every next iteration having the same firing time
       (in UTC): Sun 2025-03-30 00:00:00 UTC
       From now: 12h ago
...
```

With this patch:
```
$ env TZ=Europe/Dublin systemd-analyze calendar --base-time='Sat 2025-03-29 22:00:00 UTC' --iterations=5 'hourly'
  Original form: hourly
Normalized form: *-*-* *:00:00
    Next elapse: Sat 2025-03-29 23:00:00 GMT
       (in UTC): Sat 2025-03-29 23:00:00 UTC
       From now: 13h ago
   Iteration #2: Sun 2025-03-30 00:00:00 GMT
       (in UTC): Sun 2025-03-30 00:00:00 UTC
       From now: 12h ago
   Iteration #3: Sun 2025-03-30 02:00:00 IST  <-- the expected 1 hour jump
       (in UTC): Sun 2025-03-30 01:00:00 UTC
       From now: 11h ago
...
```

Fixes #32039.

### CODE REVIEW

File: src/shared/calendarspec.c [hunk 1]
```diff
@@ -1235,6 +1235,15 @@ static bool matches_weekday(int weekdays_bits, const struct tm *tm, bool utc) {
         return (weekdays_bits & (1 << k));
 }
 
+static int compare_tm(const struct tm *t1, const struct tm *t2) {
+        if (t1->tm_year != t2->tm_year) return t1->tm_year - t2->tm_year;
+        if (t1->tm_mon  != t2->tm_mon)  return t1->tm_mon  - t2->tm_mon;
+        if (t1->tm_mday != t2->tm_mday) return t1->tm_mday - t2->tm_mday;
+        if (t1->tm_hour != t2->tm_hour) return t1->tm_hour - t2->tm_hour;
+        if (t1->tm_min  != t2->tm_min)  return t1->tm_min  - t2->tm_min;
+        return t1->tm_sec - t2->tm_sec;
```
Comment (poettering) [inline src/shared/calendarspec.c]: please use the CMP() macro, it's guaranteed to handle overflows correctly.
also, please follow coding style, i.e. do not cram if + return in the same line

File: src/shared/calendarspec.c [hunk 2]
```diff
@@ -1243,6 +1252,7 @@ static int find_next(const CalendarSpec *spec, struct tm *tm, usec_t *usec) {
         struct tm c;
         int tm_usec;
         int r;
+        int dst;
```
Comment (poettering) [inline src/shared/calendarspec.c]: please merge these three lines

File: src/shared/calendarspec.c [hunk 3]
```diff
@@ -1345,6 +1357,14 @@ static int find_next(const CalendarSpec *spec, struct tm *tm, usec_t *usec) {
                 if (r == 0)
                         continue;
 
+                r = compare_tm(tm, &c);
+                if (r > 0 || (r == 0 && *usec - 1 >= (usec_t) tm_usec)) {
+                        /* We're stuck - advance, let mktime determine DST transition and try again. */
+                        dst = -2;
```
Comment (poettering) [inline src/shared/calendarspec.c]: i really don't like the overloading here. just add a new boolean local variable?

File: src/test/test-calendarspec.c [hunk 4]
```diff
@@ -47,8 +47,11 @@ static void _test_next(int line, const char *input, const char *new_tz, usec_t a
         if (old_tz)
                 old_tz = strdupa_safe(old_tz);
 
-        if (!isempty(new_tz))
-                new_tz = strjoina(":", new_tz);
+        if (!isempty(new_tz)) {
+                if (strchr(new_tz, ',') == NULL) {
+                        new_tz = strjoina(":", new_tz);
+                }
+        }
```
Comment (poettering) [inline src/test/test-calendarspec.c]: please follow coding style: no {} around single line if blocks. And we do not spell out `== NULL` for pointer checks

File: src/shared/calendarspec.c [hunk 5]
```diff
@@ -1251,11 +1276,13 @@ static int find_next(const CalendarSpec *spec, struct tm *tm, usec_t *usec) {
 
         c = *tm;
         tm_usec = *usec;
+        dst = spec->dst;
 
         for (unsigned iteration = 0; iteration < MAX_CALENDAR_ITERATIONS; iteration++) {
                 /* Normalize the current date */
                 (void) mktime_or_timegm_usec(&c, spec->utc, /* ret= */ NULL);
-                c.tm_isdst = spec->dst;
+                if (dst != -2)
```
Comment (poettering) [inline src/shared/calendarspec.c]: as requested before: just turn this -2 thing into a proper bool. i.e. `bool invalidate_dst = false;` or so.

File: src/shared/calendarspec.c [hunk 6]
```diff
@@ -1251,11 +1276,13 @@ static int find_next(const CalendarSpec *spec, struct tm *tm, usec_t *usec) {
...
+                        c.tm_isdst = dst;
```
Comment (poettering) [inline src/shared/calendarspec.c]: hmm we should unset the flag here again, no? i.e. `invalidate_dst = false;` here, to make sure we only revalidate the thing once after each check

Comment (kmeaw) [reply src/shared/calendarspec.c]: Sorry, I don't think I understand your idea - if we turn `dst` into a bool then we have two sources of `tm_isdst` - `spec->dst` and `c.tm_isdst` (which is set by mktime on each iteration before being overwritten). The `invalidate_dst` flag would determine which source would we use - first `spec->dst` is used but if we are stuck, we switch to mktime's `tm_isdst`.
Once the flag is flipped, we cannot update the spec's `dst` as the caller expects us to get a const pointer.

Comment (poettering) [reply src/shared/calendarspec.c]: i am not sure i follow? you only need the -2 thing locally, so you can replace that with a local variable no? that simply controls which source to use?

Comment (kmeaw) [reply src/shared/calendarspec.c]: The "make sure we only revalidate the thing once after each check" confused me.
I have replaced `-2` with a local variable as you suggested - if true then keep the value of `c.tm_isdst` that was stored by `mktime`, otherwise overwrite (as the function did before) it with the value of `spec->dst`.

File: src/shared/calendarspec.c [hunk 7]
```diff
@@ -1345,6 +1372,16 @@ static int find_next(const CalendarSpec *spec, struct tm *tm, usec_t *usec) {
                 if (r == 0)
                         continue;
 
+                r = tm_compare(tm, &c);
+                if (r == 0)
+                        r = CMP(*usec - 1, (usec_t) tm_usec);
```
Comment (poettering) [inline src/shared/calendarspec.c]: hmm, can't this underflow? i.e. if *usec is zero? 

I think it would make more sense to add 1 to tm_usec instead, since we know that that's not going to be UINT64_MAX since we treat that as USEC_INFINITY, which we don't allow.

(maybe add an `assert()` here checking for this)

Comment (kmeaw) [reply src/shared/calendarspec.c]: Thank you for catching that, adding 1 is sure a safer way. `tm_usec` isn't expected to go over `1e6`, so `(1e6)+1` won't overflow.
I don't feel comfortable doing an `assert()` in pid1. Do you think it would still be a good idea?

File: src/shared/calendarspec.c [hunk 8]
```diff
@@ -1235,14 +1235,40 @@ static bool matches_weekday(int weekdays_bits, const struct tm *tm, bool utc) {
         return (weekdays_bits & (1 << k));
 }
 
+static int tm_compare(const struct tm *t1, const struct tm *t2) {
+        int r;
+
```
Comment (bluca) [inline src/shared/calendarspec.c:1240]: assert(t1) and assert(t2)

**Review by bluca — APPROVED** [review]

File: src/shared/calendarspec.c (hunk 7 above)
Comment (bluca) [reply src/shared/calendarspec.c]: asserts to enforce against programming errors are common and used all over the place so it's ok

**Review by yuwata — APPROVED** [review]
LGTM.
