### PR TITLE
systemd-boot improvements

### LINKED ISSUE #2895: Can't it be optional to automatically add some well-known loaders found to the end of the list？
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

systemd 229-3
### Used distribution

While I was using the systemd-boot(bootctl), it automatically add **Windows Boot Manager** , **EFI Default Loader** as well as **Reboot Into Firmware Interface**.

I would like to rename the **Windows Boot Manager** , or hide this entry and make a new entry with the name I wanted.

I also want to hide the **EFI Default Loader** as well as **Reboot Into Firmware Interface** , in that before bootloader, there is a chance to choose whether get into BIOS or use which EFI APP next.

So, these three automatically added entries are not what I wanted.
But, there is no way else to deal with them, except remove line 1765~1772 from the [source code](https://github.com/systemd/systemd/blob/master/src/boot/efi/boot.c#L1766) and recompile it.

Thus, I hope it is possible to edit a config file to switch the auto-entries on/off, rather than edit the source code.

### PR DESCRIPTION
**Pull request by medhefgo**
Fixes #2895

### CODE REVIEW

File: src/boot/efi/boot.c [hunk 1]
```diff
@@ -1453,8 +1453,30 @@ static BOOLEAN config_entry_add_loader_auto(Config *config, EFI_HANDLE *device,
...
+                else {
+                        UINTN lenA;
+                        UINTN lenB;
+                        INTN equal = 1;
+                        CHAR8 *contentA = NULL;
+                        CHAR8 *contentB = NULL;
+
+                        err = file_read(root_dir, loader, 0, 0, &contentA, &lenA);
+                        if (!EFI_ERROR(err))
+                                err = file_read(root_dir, loaded_image_path, 0, 0, &contentB, &lenB);
```
Comment (poettering) [inline src/boot/efi/boot.c]: hmpf, this is potentially huuugge, no? is this really a good idea? 

what precisely are you trying to fix here?

Comment (medhefgo) [reply src/boot/efi/boot.c]: This is in the situation where we boot as "systemd/systemd-bootx64.efi" as created by bootctl for example. If the backup bootloader in "boot/bootx64.efi" is systemd-boot as well, we would end up putting ourselves to the list for no benefit.

I highly doubt anyone will ever put such a huge bootloader that it would become a performance bottleneck. In case there are errors, the code will just assume the loaders are different and continue.

Comment (poettering) [reply src/boot/efi/boot.c]: well, somebody could also have install a full kernel with initrd as bootx64.efi, no? it sounds a bit brutal to read all that in just to throw it away afterwards, no?

**Comment by medhefgo** [comment]
I pushed a new version with some changes.

- I realized I could just reuse the size parameter for file_read by making it a pointer.
- Added another press key into the dump info page, cause I noticed that some part at the start can get cut off.
- And lastly, it came to me that I could just look for the systemd-boot magic string. This way we only have to read the first 100kB of the default loader. This should hopefully make it cheap enough for you :P

File: src/boot/efi/boot.c [hunk 2]
```diff
@@ -69,6 +69,8 @@ typedef struct {
         CHAR16 *entry_oneshot;
         CHAR16 *options_edit;
         BOOLEAN no_editor;
+        BOOLEAN no_auto_entries;
+        BOOLEAN no_auto_firmware;
```
Comment (yuwata) [inline src/boot/efi/boot.c]: I think the naming of these variables `no_auto_...` should be `auto_...`, then inverted value should be stored.

Comment (medhefgo) [reply src/boot/efi/boot.c]: Normally, I'd have done so. I'm just following the old code here (no_editor).

Comment (yuwata) [reply src/boot/efi/boot.c]: It is not necessary to follow the naming `no_editor`. Also, `no_editor` should be changed to `editor` or something later. (Of course, changing that in this PR is welcome.)

**Comment by medhefgo** [comment]
I now made the config variables positive.

**Comment by yuwata** [comment]
Thanks. Looks good to me now about `no_auto_...` vs `auto_...`.

File: src/boot/efi/boot.c [hunk 3]
```diff
@@ -1142,11 +1142,11 @@ static VOID config_entry_add_from_file(Config *config, EFI_HANDLE *device, CHAR1
 static VOID config_load_defaults(Config *config, EFI_FILE *root_dir) {
         CHAR8 *content = NULL;
         UINTN sec;
-        UINTN len;
+        UINTN len = 0;
```
Comment (keszybz) [inline src/boot/efi/boot.c]: Pffff, we don't like input-output parameters like this. Please make it two separate things: one for input, one for output, and allow the output parameter to be null. Most callers don't need the length any way, so they can be simplified to not retrieve it.

File: src/boot/efi/boot.c [hunk 4]
```diff
@@ -1006,7 +1012,23 @@ static VOID config_defaults_load_from_file(Config *config, CHAR8 *content) {
...
+                                continue;
+                        config->auto_entries = on;
+                }
+
+                if (strcmpa((CHAR8 *)"auto-firmware", key) == 0) {
+                        BOOLEAN on;
+
+                        if (EFI_ERROR(parse_boolean(value, &on)))
+                                continue;
+                        config->auto_firmware = on;
```
Comment (keszybz) [inline src/boot/efi/boot.c:1031]: Analogous changes should be done in `boot_loader_load_conf` in `src/shared/bootspec.c`, and possibly the logic in `bootctl.c` should be updated.

File: src/boot/efi/boot.c [hunk 5]
```diff
@@ -1460,8 +1460,30 @@ static BOOLEAN config_entry_add_loader_auto(Config *config, EFI_HANDLE *device,
                 return FALSE;
 
         /* do not add an entry for ourselves */
-        if (loaded_image_path && StriCmp(loader, loaded_image_path) == 0)
-                return FALSE;
+        if (loaded_image_path) {
+                if (StriCmp(loader, loaded_image_path) == 0)
+                        return FALSE;
+                else {
+                        UINTN len = 100*1024;
```
Comment (keszybz) [inline src/boot/efi/boot.c]: I'm a bit confused here. Shouldn't this `else` block be independent of the check for `loaded_image_path`?

**Comment by medhefgo** [comment]
Made requested changes.

**Comment by keszybz** [comment]
Sorry for the delay on this. I finally got around to testing and reviewing this.

I found a bug in your patch: the argument to limit the read to 100k wasn't actually passed properly, because after the last changes (that I requested ;) ) the len output parameter is not used as input, so the whole file was read. I force-pushed a fixed for that.

I also found a buffer overflow, and pushed a patch to fix that.

Please take a look.

**Comment by medhefgo** [comment]
Looks good to me.

**Comment by keszybz** [comment]
OK, let's merge then. Ubuntu CI does not test sd-boot at all, so no point in waiting.
