### PR TITLE
network: fix handling of network interface renaming

### LINKED ISSUE #20657: In 249 systemd-networkd does not configure .network after systemd-udevd renames .link
**systemd version the issue has been seen with**
 > 249.2 and 249.4

**Used distribution**
 > gentoo

**Linux kernel version used** (`uname -a`)

 > `Linux deli 5.10.61-gentoo-x86_64 #1 SMP PREEMPT Tue Aug 31 14:31:27 CEST 2021 x86_64 Intel(R) Xeon(R) CPU E5-2420 0 @ 1.90GHz GenuineIntel GNU/Linux`
and `Linux asuz 5.10.61-gentoo-x86_64 #2 SMP PREEMPT Mon Aug 30 13:01:01 CEST 2021 x86_64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz GenuineIntel GNU/Linux`

**CPU architecture issue was seen on**
 > …

**Expected behaviour you didn't see**
 > Network on interface lan1 is configured

**Unexpected behaviour you saw**
 > After systemd-networkd "waiting for the interface to be renamed", it never comes back with "lan1: udev initialized link". Nothing more happens, and the interface isn't configured.

**Steps to reproduce the problem**
 > Boot system with simple .link and static .network configs.

```
# cat /etc/systemd/network/10-lan1.link
[Match]
MACAddress=90:b1:1c:10:63:bb

[Link]
Name=lan1
```

```
# cat /etc/systemd/network/30-lan1.network
[Match]
Name=lan1

[Address]
Address=192.168.1.10/24

[Route]
Gateway=192.168.1.1

[Network]
DNS=192.168.1.1
IPv6AcceptRA=no
```

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

Everything workes fine with 248.6. I've tried with different kernels: 5.10.49, 5.10.52, 5.10.61, but it makes no difference. systemd-248.6 works, systemd-249.2 fails.

I've compared the logs with debug info turned on for networkd and udevd.

The log messages from udevd are the same in both versions.

networkd in 249.2 says "eth0: Saved hardware address: 90:b1:1c:10:63:bb" which 248.6 does not.

Then networkd in 248.6 says some things that are missing in 249.2:
```
eth0: New dvice has no master, continuing without
eth0: State changed: unmanaged -> linger
eth0: Link removed
lan1: New device has no master, continuing without
lan1: Flags change: +MULTICAST +BROADCAST
lan1: Link 2 added
lan1: Interface is being renamed, pending initialization.
lan1: Saved original MTU: 1500
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #20657.

### CODE REVIEW

**Comment by yuwata** [comment]
Needs to be backported to v249.

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -1470,17 +1470,20 @@ static int link_initialized(Link *link, sd_device *device) {
...
 
-        if (link->state != LINK_STATE_PENDING)
-                return 0;
+        /* Always replace with the new sd_device object. As the sysname (and possibly other properties
+         * or sysattrs) may be outdated. */
+        sd_device_unref(link->sd_device);
+        link->sd_device = sd_device_ref(device);
 
-        if (link->sd_device)
+        /* Do no ignore unamanaged state case here. If an interface is renamed after once configured,
```
Comment (bluca) [inline src/network/networkd-link.c]: "Do not"
"renamed after being configured"

**Review by bluca — APPROVED** [review]
lgtm just some nits

**Comment by yuwata** [comment]
@bluca Thank you for your review. The comment is updated. Upgrading the green label.

File: src/network/networkd-link.c [hunk 2]
```diff
@@ -1470,17 +1470,20 @@ static int link_initialized(Link *link, sd_device *device) {
         assert(link);
         assert(device);
 
-        if (link->state != LINK_STATE_PENDING)
-                return 0;
+        /* Always replace with the new sd_device object. As the sysname (and possibly other properties
+         * or sysattrs) may be outdated. */
+        sd_device_unref(link->sd_device);
+        link->sd_device = sd_device_ref(device);
```
Comment (poettering) [inline src/network/networkd-link.c]: doesn't matter, but for replacements like this i'd alway ref first, and unref second, just in case the object passed in is actually the one already stored in there. because if you unref first then it might be destroyed already, and then you ref invalidated data...

Comment (yuwata) [reply src/network/networkd-link.c]: Interesting. Maybe, we should introduce something similar to `free_and_replace()` but with `_ref()` and `_unref()`.
