### PR TITLE
cryptsetup: retry TPM2 unseal operation if it fails with TPM2_RC_PCR_CHANGED

### LINKED ISSUE #24906: Failed to unseal HMAC key in TPM: tpm:error(2.0): PCR have changed since checked
### systemd version the issue has been seen with

systemd 251.4-1

### Used distribution

Archlinux

### Linux kernel version used

5.19.12-xanmod1-1-alderlake

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

I am using an encrypted LUKS2 root partition and enrolled an unlock key to the TPM bound to PCR-7. I expect that an intrd using systemd-cryptenroll automatically unlooks the luks partition and boots to the login prompt.

### Unexpected behaviour you saw

I experience different behavior, which leads me to the suspicion that the error is due to a race condition:
* In some cases I see the luks passphrase prompt. If I just hit enter without typing anything it boots successfully.
* In other cases I see the luks passphrase prompt. If I hit enter, I see the prompt a second time, if I hit enter again I am redirected to the emergency shell. If I hit Ctrl-D instead of entering the password, the system boots successfully.
* In a few cases the system boots successfully, without any interactions.

In cases where I get the prompt I see the following output:

```
journalctl -xb -u systemd-cryptsetup@luks
systemd-cryptsetup[338]: WARNING:esys:src/tss2-esys/api/Esys_Unseal.c:295:Esys_Unseal_Finish() Received TPM Error
systemd-cryptsetup[338]: ERROR:esys:src/tss2-esys/api/Esys_Unseal.c:98:Esys_Unseal() Esys Finish ErrorCode (0x00000128)
systemd-cryptsetup[338]: Failed to unseal HMAC key in TPM: tpm:error(2.0): PCR have changed since checked

```

### Steps to reproduce the problem

I assume it is hard to reproduce, since it seems it is tied to a race condition. 
Trying to add as much information as possible here:
* I experience the issue using dracut as well as mkinitcpio. 
* The error `Failed to unseal HMAC key in TPM` seems to be thrown in [tpm2_unseal() in tpm2_util.c](https://github.com/systemd/systemd/blob/main/src/shared/tpm2-util.c#L1685)
* The error `PCR have changed since checked` is the result received from the TPM as [TPM2_RC_PCR_CHANGED](https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-rc/tss2_rc.c#L518).
I found some explanation about the pcrUpdateCounter in the [TPM specification Page 230 - November 8, 2019 - Level 00 Revision 01.5](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part3_Commands_pub.pdf). If **any** PCR changes in the time between validating PCR7 and unsealing the HMAC key the TPM will return TPM_RC_PCR_CHANGED.
* I was able to build systemd from the current master branch and include it in the initrd with mkinitcpio. I added additional logging to print the output of the command "tpm2_pcrread" prior to calling [tpm2_load_pcr_signature() in luks2-tpm.c](https://github.com/systemd/systemd/blob/main/src/cryptsetup/cryptsetup-tokens/luks2-tpm2.c#L54) and another time after calling tpm2_unseal(). And indeed **the hash of PCR-10 changed in the meantime.**
* I am not sure whether PCR-10 is among the PCRs which cause pcrUpdateCounter to be incremented once it gets changed, but the behavior indicates it.
* I suspect IMA (Integrity Measurement Architecture) is changing this value in the meantime. At least my kconfig has CONFIG_IMA_MEASURE_PCR_IDX=10

**Idea for solution:**
I assume *arbitrary* PCR values could change anytime, so it might be nice to have some retry logic, if TPM2_RC_PCR_CHANGED is returned. Notably, according to the logs it is already trying twice. Sometimes the second attempt succeeds and sometimes both attempts fail with this error.

Probably not only the LUKS unlock is affected, but any code which calls tpm2_unseal().

**Please let me know, if you want me to provide any additional information. Thanks for helping.**

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by aafeijoo-suse**
Quoting "Trusted Platform Module Library - Part 3: Commands (Rev. 01.59)":

> "pcrUpdateCounter – this parameter is updated by TPM2_PolicyPCR(). This value may only be set once during a policy. Each time TPM2_PolicyPCR() executes, it checks to see if policySession->pcrUpdateCounter has its default state, indicating that this is the first TPM2_PolicyPCR(). If it has its default value, then policySession->pcrUpdateCounter is set to the current value of pcrUpdateCounter. If policySession->pcrUpdateCounter does not have its default value and its value is not the same as pcrUpdateCounter, the TPM shall return TPM_RC_PCR_CHANGED.
> 
> If this parameter and pcrUpdateCounter are not the same, it indicates that PCR have changed since checked by the previous TPM2_PolicyPCR(). Since they have changed, the previous PCR validation is no longer valid."

The TPM will return TPM_RC_PCR_CHANGED if any PCR value changes (no matter which) between validating the PCRs binded to the enrollment and unsealing the HMAC key, so this patch adds a retry mechanism in this case.

Fixes #24906

---

Manually tested by adding `sym_Esys_PCR_Extend` between `tpm2_make_policy_session` and
`sym_Esys_Unseal` to extend a PCR different that the one binded and force the TPM2_RC_PCR_CHANGED return code.

### CODE REVIEW

**Comment by poettering** [comment]
hmm, why bubble this up so far? why not do the loop inside of tpm2_unseal()? it appears to me we only need to loop around a minor part of that function, and do not have to reopen the device and so on, hence it looks much nice if this is hidden inside tpm2_unseal() to me

**Comment by aafeijoo-suse** [comment]
> hmm, why bubble this up so far? why not do the loop inside of tpm2_unseal()? it appears to me we only need to loop around a minor part of that function, and do not have to reopen the device and so on, hence it looks much nice if this is hidden inside tpm2_unseal() to me

Ok, that would require a call to `TPM2_PolicyRestart` inside the loop, I'll give it a try.

**Comment by aafeijoo-suse** [comment]
> Do we have to use TPM2_PolicyRestart() at all? I mean, we just can close the session and start a new one, i.e. start the looping right before the tpm2_make_policy_session() call inside ot tpm2_unseal(), no?

Yes, you're right, your suggestion works fine, no need to restart policy. Thanks!

File: src/shared/tpm2-util.c [hunk 1]
```diff
@@ -1676,44 +1676,53 @@ int tpm2_unseal(const char *device,
...
-                        pubkey, pubkey_size,
-                        pubkey_pcr_mask,
-                        signature,
-                        !!pin,
-                        &session,
-                        &policy_digest,
-                        /* ret_pcr_bank= */ NULL);
-        if (r < 0)
-                goto finish;
+        for (unsigned i = TPM2_PCRS_MAX;; i--) {
```
Comment (poettering) [inline src/shared/tpm2-util.c]: hmm, using TPM2_PCRS_MAX as max loop count sounds weird. I don't see the relationship?

add a new macro?

File: src/shared/tpm2-util.c [hunk 2]
```diff
@@ -1676,44 +1676,53 @@ int tpm2_unseal(const char *device,
...
-                goto finish;
+                rc = sym_Esys_Unseal(
+                                c.esys_context,
+                                hmac_key,
+                                session,
+                                hmac_session, /* use HMAC session to enable parameter encryption */
+                                ESYS_TR_NONE,
+                                &unsealed);
+                if (rc == TPM2_RC_PCR_CHANGED && i > 0) {
+                        log_debug("Any PCR value changed after the TPM2 policy session was created, attempting to unseal the HMAC key again.");
```
Comment (poettering) [inline src/shared/tpm2-util.c]: Any → A

after → during and then strike "was created".

Hence maybe:

"A PCR value changed during the TPM2 policy session, restarting HMAC key unsealing."

or so?

**Review by poettering — CHANGES_REQUESTED** [review]
looks pretty good

File: src/shared/tpm2-util.c (hunk 1 above)
Comment (aafeijoo-suse) [reply src/shared/tpm2-util.c]: Yes, I didn't know how many times should we retry, so I thought about 1 per PCR (24) even though it's kind of random, but a new macro makes more sense. What number do you say we should use as max?

File: src/shared/tpm2-util.c (hunk 2 above)
Comment (aafeijoo-suse) [reply src/shared/tpm2-util.c]: ok

Comment (poettering) [reply src/shared/tpm2-util.c]: oh, and maybe mention how many tries left, so that progress is visible

File: src/shared/tpm2-util.c (hunk 1 above)
Comment (poettering) [reply src/shared/tpm2-util.c]: We measure lots of stuff now, multiple things into various PCRs, hence if you manage to race against every single one of those the number you need to try might grow much larger than 24.

So I would just use something like 15 or so initially. or 30. pick something. doesn't really matter

i think in the long run, we might end up fine tuning this further anyway. i.e. start with something conservative. And if this collisions grow too frequent we might even have to add some form of sleeping between retries (exponential backoff or random or so), hence we should not have any illusions that we'll pick a perfect value right-away.

File: src/shared/tpm2-util.c (hunk 2 above)
Comment (aafeijoo-suse) [reply src/shared/tpm2-util.c]: ok, done

**Comment by poettering** [comment]
excellent! thanks for looking into this!

**Comment by keszybz** [comment]
jammy-amd64: seems to some hardware issue, `IRQ Exception at 0x000000009BC11F38`

jammy-ppc64el:
[   36.231192] systemd[1]: testsuite-67.service: Failed with result 'exit-code'.
[   36.237389] systemd[1]: Failed to start TEST-67-INTEGRITY.
[   36.253995] systemd-integritysetup[441]: Device integrity_test is not active.
[   37.275241] systemd[1]: run-credentials-systemd\x2dtmpfiles\x2dsetup.service.mount: Failed with result 'exit-code'.
TEST-67-INTEGRITY: (failed; see logs)

[   35.520481] testsuite-67.sh[433]: ++ integritysetup status integrity_test
[   35.536476] testsuite-67.sh[434]: ++ grep '^\s*device:'
[   35.540461] testsuite-67.sh[435]: ++ awk '{print $2}'
[   35.678986] testsuite-67.sh[360]: + dev_name=/dev/loop1
[   35.686071] testsuite-67.sh[436]: ++ blkid -U 01234567-ffff-eeee-eeee-0123456789ab
[   35.757133] testsuite-67.sh[360]: + '[' /dev/loop1 '!=' /dev/mapper/integrity_test ']'
[   35.758488] testsuite-67.sh[360]: + echo 'Failed to locate FS with matching UUID!'
[   35.759776] testsuite-67.sh[360]: Failed to locate FS with matching UUID!
[   35.761276] testsuite-67.sh[360]: + exit 1

@mrc0mmand I don't see an open issue for this one. Looks like another loop device race.

jammy-s390x: something failed, I have no idea what.

I assume that all those are unrelated to the patch.
