### PR TITLE
Avoid triggering assertions by nss modules when uname and/or sigprocmask are masked

### LINKED ISSUE #38582: nss-myhostname aborts in process sandboxed without sigprocmask() and uname() syscalls
### systemd version the issue has been seen with

257.7

### Used distribution

Fedora 42

### Linux kernel version used

6.15.7-200.fc42.x86_64

### CPU architectures issue was seen on

x86_64

### Component

nss-resolve

### Expected behaviour you didn't see

If a third-party service (in this case, [`malcontent-webd`](https://gitlab.freedesktop.org/pwithnall/malcontent/), for example) is sandboxed with a `SystemCallFilter=` which doesn’t include `sigprocmask rt_sigprocmask uname`, and it calls `getaddrinfo()`, then the `nss-myhostname` module which is loaded into the service process’ address space (outside of the service’s control) will abort.

This is because `nss-myhostname.c` calls `BLOCK_SIGNALS(NSS_SIGNALS_BLOCK)` (which asserts on the success of `sigprocmask()` and, later, calls `gethostname_malloc()` (which asserts on the success of `uname()`).

I think it’s normally fine for systemd processes to assert on the success of these syscalls, but given that nss-myhostname is loaded into third-party processes via NSS, it should probably gracefully return an error code if either of them fail, rather than aborting the entire process.

There may be other syscalls which it asserts the success of — these are just the two I encountered when testing my service, which otherwises uses this sandbox:
```
SystemCallFilter=@basic-io @file-system @io-event @ipc @network-io @process @sync flock
```

### Steps to reproduce the problem

Drop the following service file into `/run/systemd/system/test-filter.service` and run `sudo systemctl daemon-reload && sudo systemctl start test-filter.service`. It will succeed with the second `SystemCallFilter=` line uncommented, and fail with it commented:
```
[Unit]
Description=Example test case for https://github.com/systemd/systemd/issues/38582

[Service]
ExecStart=getent hosts duckduckgo.com
Type=oneshot

# Sandboxing
SystemCallErrorNumber=EPERM
SystemCallFilter=@basic-io @file-system @io-event @network-io
#SystemCallFilter=sigprocmask rt_sigprocmask uname
SystemCallArchitectures=native
```

### Additional program output to the terminal or log subsystem illustrating the issue

Relevant backtraces:
```
#0  0x00007f0fd3e47735 in abort () at /lib64/libc.so.6
#1  0x00007f0fbe4ff2cb in log_assert_failed
    (text=text@entry=0x7f0fbe517570 "sigprocmask_many(SIG_BLOCK, &_t, 14,26,13,17,20,29,1,10,12,27,23,28) >= 0", file=file@entry=0x7f0fbe51754b "src/nss-myhostname/nss-myhostname.c", line=line@entry=48, func=func@entry=0x7f0fbe518420 <__func__.6.lto_priv.0> "_nss_myhostname_gethostbyname4_r") at ../src/basic/log.c:996
#2  0x00007f0fbe500435 in _nss_myhostname_gethostbyname4_r
    (name=0x155de200 "v.firebog.net", pat=0x7f0fbed4de80, buffer=0x7f0fbed4df90 "", buflen=1024, errnop=0x7f0fbed4f648, h_errnop=0x7f0fbed4f698, ttlp=0x0) at ../src/nss-myhostname/nss-myhostname.c:48
#3  0x00007f0fd3f6764b in getaddrinfo () at /lib64/libc.so.6
#4  0x00007f0fd431c4ea in threaded_resolver_worker_cb () at /lib64/libgio-2.0.so.0
#5  0x00007f0fd41596d2 in g_thread_pool_thread_proxy () at /lib64/libglib-2.0.so.0
#6  0x00007f0fd41584f2 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#7  0x00007f0fd3eb71d4 in start_thread () at /lib64/libc.so.6
#8  0x00007f0fd3f39b14 in clone () at /lib64/libc.so.6
```

```
#0  0x00007f562561b735 in abort () at /lib64/libc.so.6
#1  0x00007f56144e32cb in log_assert_failed
    (text=text@entry=0x7f56144fa8a7 "uname(&u) >= 0", file=file@entry=0x7f56144fa424 "src/basic/hostname-util.c", line=line@entry=47, func=func@entry=0x7f56144fc340 <__func__.3.lto_priv.1> "gethostname_full")
    at ../src/basic/log.c:996
#2  0x00007f56144e4175 in gethostname_full
    (ret=ret@entry=0x7f5607ffdcb8, flags=(GET_HOSTNAME_ALLOW_LOCALHOST | GET_HOSTNAME_FALLBACK_DEFAULT))
    at ../src/basic/hostname-util.c:47
#3  0x00007f56144ed5da in gethostname_malloc () at ../src/basic/hostname-util.h:24
#4  _nss_myhostname_gethostbyname4_r
    (name=0x2b19f200 "v.firebog.net", pat=0x7f5607ffde80, buffer=0x7f5607ffdf90 "", buflen=1024, errnop=0x7f5607fff648, h_errnop=0x7f5607fff698, ttlp=0x0) at ../src/nss-myhostname/nss-myhostname.c:79
#5  0x00007f562573b64b in getaddrinfo () at /lib64/libc.so.6
#6  0x00007f5625af04ea in threaded_resolver_worker_cb () at /lib64/libgio-2.0.so.0
#7  0x00007f562592d6d2 in g_thread_pool_thread_proxy () at /lib64/libglib-2.0.so.0
#8  0x00007f562592c4f2 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#9  0x00007f562568b1d4 in start_thread () at /lib64/libc.so.6
#10 0x00007f562570db14 in clone () at /lib64/libc.so.6
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #38582.

### CODE REVIEW

File: src/basic/assert-util.c [hunk 1]
```diff
@@ -17,6 +18,14 @@ void log_set_assert_return_is_critical(bool b) {
         assert_return_is_critical = b;
 }
 
+void log_set_assert_return_is_critical_from_env(void) {
+        int r;
+
+        r = getenv_bool("SYSTEMD_ASSERT_RETURN_IS_CRITICAL");
```
Comment (bluca) [inline src/basic/assert-util.c]: cache the value given it may be called many times?

File: src/basic/assert-util.c [hunk 2]
```diff
@@ -17,6 +18,22 @@ void log_set_assert_return_is_critical(bool b) {
         assert_return_is_critical = b;
 }
 
+void log_set_assert_return_is_critical_from_env(void) {
+        static int cached = INT_MIN;
+        int r;
+
+        if (cached == INT_MIN) {
+                r = getenv_bool("SYSTEMD_ASSERT_RETURN_IS_CRITICAL");
```
Comment (poettering) [inline src/basic/assert-util.c]: this really should be secure_getenv_bool

Comment (yuwata) [reply src/basic/assert-util.c]: For some reasons, `secure_getenv_bool()` does not work...

**Comment by bluca** [comment]
```
Successfully forked off '(with-seccomp)' as PID 88913.
Failed to add rule for system call olduname() / -10038, ignoring: Numerical argument out of domain
Failed to add rule for system call oldolduname() / -10036, ignoring: Numerical argument out of domain
Failed to add rule for system call sigprocmask() / -10057, ignoring: Numerical argument out of domain
Failed to add rule for system call olduname() / -10038, ignoring: Numerical argument out of domain
Failed to add rule for system call oldolduname() / -10036, ignoring: Numerical argument out of domain
Failed to add rule for system call sigprocmask() / -10057, ignoring: Numerical argument out of domain
======== myhostname ========
Using libnss_myhostname.so.2
dlsym(0x0x7cc77c9e0080, _nss_myhostname_gethostbyname4_r) → 0x0x7f277d3410e0
Assertion 'sigprocmask_many(SIG_BLOCK, &_t, 14,26,13,17,20,29,1,10,12,27,23,28) >= 0' failed at src/nss-myhostname/nss-myhostname.c:48, function _nss_myhostname_gethostbyname4_r(). Aborting.
(with-seccomp) terminated by signal ABRT.
src/test/test-nss-hosts.c:492: Assertion failed: Expected "r = safe_fork("(with-seccomp)", FORK_LOG | FORK_WAIT, NULL)" to succeed, but got error: -71/EPROTO
```

**Comment by yuwata** [comment]
Apparently `get_build_exec_dir()` seems to be broken when running with sanitizers... Dropped the change, as it is unrelated to the issue. I will investigate that later in another PR.

So, hopefully now it works. Please take a look and give final approval.

**Comment by yuwata** [comment]
TEST-38-FREEZER failure in mkosi(debian) should be unrelated and fixed by https://github.com/systemd/systemd/pull/38598.
