### PR TITLE
systemctl: make is-* return EXIT_PROGRAM_OR_SERVICES_STATUS_UNKNOWN(4) when no unit file is found

### LINKED ISSUE #25680: wrong exit status with is-{active,enabled,failed} for non-existent units
### systemd version the issue has been seen with

252.2

### Used distribution

Debian sid

### Linux kernel version used

6.0.0-5-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

When using `systemctl`’s `is-active`, `is-enabled` and `is-failed` on non-existent unit names like:
```
# systemctl --quiet is-active  nonexistent.service ; echo $?
3
# systemctl --quiet is-failed  nonexistent.service ; echo $?
1
# systemctl --quiet is-enabled  nonexistent.service ; echo $?
Failed to get unit file state for nonexistent.service: No such file or directory
1
```

The used exit statuses don't seem to best fit the table from the manpage:
```
       ┌──────┬────────────────────────────────────────────────┬─────────────────────────────────────┐
       │Value │ Description in LSB                             │ Use in systemd                      │
       ├──────┼────────────────────────────────────────────────┼─────────────────────────────────────┤
       │0     │ "program is running or service is OK"          │ unit is active                      │
       ├──────┼────────────────────────────────────────────────┼─────────────────────────────────────┤
       │1     │ "program is dead and /var/run pid file exists" │ unit not failed (used by is-failed) │
       ├──────┼────────────────────────────────────────────────┼─────────────────────────────────────┤
       │2     │ "program is dead and /var/lock lock file       │ unused                              │
       │      │ exists"                                        │                                     │
       ├──────┼────────────────────────────────────────────────┼─────────────────────────────────────┤
       │3     │ "program is not running"                       │ unit is not active                  │
       ├──────┼────────────────────────────────────────────────┼─────────────────────────────────────┤
       │4     │ "program or service status is unknown"         │ no such unit                        │
       └──────┴────────────────────────────────────────────────┴─────────────────────────────────────┘
```

Wouldn’t `4` be a much better fit?

Cheers,
Chris.

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by YHNdnzj**
According to systemctl(1), we should use LSB return code 4 when the state is "no such unit" for is-{active,failed,enabled} verbs.

Fixes #25680

### CODE REVIEW

**Comment by bluca** [comment]
Isn't this a compat breakage, technically?

**Comment by YHNdnzj** [comment]
> Isn't this a compat breakage, technically?

Then a better way might be to fetch the LoadState independently, before
getting other states?

**Comment by YHNdnzj** [comment]
@bluca Re-implemented without touching the dbus interface. Should be OK now :)

**Comment by YHNdnzj** [comment]
Debian's CI has been failing continuously, and it seems to be related to sysv-generated units. Not sure how to deal with them TBH...

**Comment by YHNdnzj** [comment]
Seems to be fixed :D

File: src/systemctl/systemctl-sysv-compat.c [hunk 1]
```diff
@@ -230,6 +230,7 @@ int enable_sysv_units(const char *verb, char **args) {
                         } else {
                                 if (!arg_quiet)
                                         puts("disabled");
+                                r = ESRCH;
```
Comment (keszybz) [inline src/systemctl/systemctl-sysv-compat.c]: This looks wrong. `r = -ESRCH` ?

File: src/systemctl/systemctl-is-active.c [hunk 2]
```diff
@@ -25,21 +26,31 @@ static int check_unit_generic(int code, const UnitActiveState good_states[], int
...
 
         STRV_FOREACH(name, names) {
+                _cleanup_free_ char *load_state = NULL;
+
                 r = get_state_one_unit(bus, *name, &active_state);
+                if (r >= 0)
+                        r = unit_load_state(bus, *name, &load_state);
+
                 if (r < 0)
                         return r;
```
Comment (keszybz) [inline src/systemctl/systemctl-is-active.c]: Please don't do this "contraction". Just repeat
```C
r = some_op();
if (r < 0)
   return r;
```

File: src/systemctl/systemctl-is-active.c [hunk 3]
```diff
@@ -13,8 +13,9 @@ static int check_unit_generic(int code, const UnitActiveState good_states[], int
         _cleanup_strv_free_ char **names = NULL;
         UnitActiveState active_state;
         sd_bus *bus;
+        bool not_found = true;
+        bool ok = false;
```
Comment (keszybz) [inline src/systemctl/systemctl-is-active.c]: Please combine both declarations into one line.

File: src/systemctl/systemctl-is-enabled.c [hunk 4]
```diff
@@ -59,6 +59,7 @@ static int show_installation_targets(sd_bus *bus, const char *name) {
 int verb_is_enabled(int argc, char *argv[], void *userdata) {
         _cleanup_strv_free_ char **names = NULL;
         bool enabled;
+        bool not_found = true;
```
Comment (keszybz) [inline src/systemctl/systemctl-is-enabled.c]: Also here, just one line.

File: src/systemctl/systemctl-is-enabled.c [hunk 5]
```diff
@@ -69,16 +70,25 @@ int verb_is_enabled(int argc, char *argv[], void *userdata) {
...
-                        if (r < 0)
+                        if (r < 0 && r != -ENOENT)
                                 return log_error_errno(r, "Failed to get unit file state for %s: %m", *name);
 
+                        if (r == -ENOENT) {
+                                if (!arg_quiet)
+                                        puts("not-found");
+                                continue;
+                        } else
+                                not_found = false;
```
Comment (keszybz) [inline src/systemctl/systemctl-is-enabled.c]:
```C
if (r == -ENOENT) {
   ...
} else if (r < 0)
   return log_…;
else
   ...
```

File: src/systemctl/systemctl-is-enabled.c [hunk 6]
```diff
@@ -112,9 +122,18 @@ int verb_is_enabled(int argc, char *argv[], void *userdata) {
                         const char *s;
 
                         r = bus_call_method(bus, bus_systemd_mgr, "GetUnitFileState", &error, &reply, "s", *name);
-                        if (r < 0)
+                        if (r < 0 && r != -ENOENT)
```
Comment (keszybz) [inline src/systemctl/systemctl-is-enabled.c]: Also here, please combine all check for `r` into one `if else if else`.

**Review by keszybz — CHANGES_REQUESTED** [review]
The approach looks reasonable in general. But it really needs a test. Please find a place to add something. `test/TEST-26-SYSTEMCTL` i.e. `test/units/testsuite-26.sh` is probably the best place.

File: src/systemctl/systemctl-sysv-compat.c (hunk 1 above)
Comment (YHNdnzj) [reply src/systemctl/systemctl-sysv-compat.c]: Actually no. Previously we set `r = 1` when enabled, and `0` when disabled _and_ not found. By adding this I meant to distinguish between disabled and not found. It's not an error after all. And I chose `ESRCH` because it has a close meaning to disabled (based on the assumption that we shouldn't use some random number like 2).

Comment (keszybz) [reply src/systemctl/systemctl-sysv-compat.c]: This is "mixing metaphors" and would confuse readers since we always return negative errnos. Also, ESRCH should be treated as an opaque constant and we can't assume that it's *not* 1.

Instead, define an anonymous enum somewhere above (maybe with better naming):
```C
enum {
  ENABLE_RESULT_DISABLED = 0,
  ENABLE_RESULT_ENABLED,
  ENABLE_RESULT_NOT_FOUND,
}
```
and return one of those.

File: test/units/testsuite-26.sh [hunk 7]
```diff
@@ -79,6 +79,14 @@ systemctl list-jobs --before
 systemctl list-jobs --after --before
 systemctl list-jobs "*"
 
+# is-* verbs
+# Should return 4 for a missing unit file
+systemctl is-active not-found.service || (( $? == 4 ))
+systemctl is-failed not-found.service || (( $? == 4 ))
+systemctl is-enabled not-found.service || (( $? == 4 ))
+# return 3 when the unit exists but inactive
+systemctl is-active "$UNIT_NAME" || (( $? == 3 ))
```
Comment (keszybz) [inline test/units/testsuite-26.sh]: Hmm, this will also pass if the return value is 0. Why not use `;` instead of `||` ?

Comment (yuwata) [reply test/units/testsuite-26.sh]: Please use `assert_rc` defined in assert.sh.

**Comment by keszybz** [comment]
> Isn't this a compat breakage, technically?

If we changed the return value from zero to non-zero, it'd be more likely to cause problems. But correcting the error value I think is fine. It's essentially a bugfix.
