### PR TITLE
mount-util: make path_get_mount_info_at() also read utab

### LINKED ISSUE #35949: Unable to recognize the _netdev mount option on ext4 with an iSCSI backend
### systemd version the issue has been seen with

255.4-1ubuntu8.4

### Used distribution

Ubuntu 24.04/Oracle

### Linux kernel version used

6.8.0-1013-oracle

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

The root partition is configured with ext4 on an iSCSI backend. Despite adding the "_netdev" mount option to the fstab, the system continues to hang during poweroff. This behavior is unexpected, as the KeepConfiguration setting should be enabled to address such scenarios.

### Unexpected behaviour you saw

The path_is_network_fs_harder function calls the path_get_mount_info_at function, which filters /proc/self/mountinfo to retrieve mount options. The /proc entry invokes the show_options function hook in the kernel, specifically ext4_show_options, to collect the mount options. However, this function does not display the _netdev option, even if it has been assigned in the fstab configuration.
```
root@noble-vm:~# iscsiadm -m session -P 3 | grep "Attached SCSI devices" -B 1 -A 5
		************************
		Attached SCSI devices:
		************************
		Host Number: 6	State: running
		scsi6 Channel 00 Id 0 Lun: 0
		scsi6 Channel 00 Id 0 Lun: 1
			Attached scsi disk sda		State: running
root@noble-vm:~# cat /etc/fstab 
LABEL=cloudimg-rootfs	/	 ext4	discard,commit=30,errors=remount-ro,_netdev	0 1
LABEL=BOOT	/boot	ext4	defaults	0 2
LABEL=UEFI	/boot/efi	vfat	umask=0077	0 1
...
root@noble-vm:~# cat /proc/self/mountinfo | grep sda
31 1 8:1 / / rw,relatime shared:1 - ext4 /dev/sda1 rw,discard,errors=remount-ro,commit=30
48 31 259:0 / /boot rw,relatime shared:33 - ext4 /dev/sda16 rw
50 48 8:15 / /boot/efi rw,relatime shared:52 - vfat /dev/sda15 rw,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro
```

### Steps to reproduce the problem

1. Create a virtual machine with its root partition configured on ext4 with an iSCSI backend.
2. Add the "_netdev" mount option to the fstab configuration.
3. Test whether the virtual machine powers off without hanging.

### PR DESCRIPTION
**Pull request by yuwata**
As "_netdev" is only stored in utab.

Fixes a bug introduced by 5261c521e3a98932241f36e91cf6f7823c578aca.
Fixes #35949.

### CODE REVIEW

File: src/shared/mount-util.c [hunk 1]
```diff
@@ -1894,7 +1894,7 @@ static int path_get_mount_info_at(
         if (r < 0)
                 return log_debug_errno(r, "Failed to get mount ID: %m");
 
-        r = libmount_parse("/proc/self/mountinfo", NULL, &table, &iter);
+        r = libmount_parse(NULL, NULL, &table, &iter);
```
Comment (poettering) [inline src/shared/mount-util.c]: oh, ah.

maybe prefix the two NULL args with the usual `/* path= */` and  `/* source= */`

Comment (poettering) [reply src/shared/mount-util.c]: might be a good idea to add a comment here, that by passing NULL/NULL we make sure to get utab loaded, and thus get userspace options too

Comment (poettering) [reply src/shared/mount-util.c]: you could even be even smarter and set the first arg as before as long as ret_options is NULL, after all if we don't need the options we don't need utab.

Comment (YHNdnzj) [reply src/shared/mount-util.c]: I think we should systematically take utab into account, to avoid pitfalls like this and to avoid hardcoding /p/s/mountinfo unnecessarily.

Comment (yuwata) [reply src/shared/mount-util.c]: > I think we should systematically take utab into account, to avoid pitfalls like this and to avoid hardcoding /p/s/mountinfo unnecessarily.

Maybe adding comment is enough to avoid such pitfall ?

Comment (YHNdnzj) [reply src/shared/mount-util.c]: Probably a wrapper around libmount_parse then?

`int libmount_parse_mountinfo(bool with_utab, ...)`

Comment (yuwata) [reply src/shared/mount-util.c]: Could you elaborate more? I cannot follow, sorry.

Comment (YHNdnzj) [reply src/shared/mount-util.c]: Instead of implying this bit of info in whether /p/s/mountinfo is specified or not let's instead turn it into a proper bool?

Comment (yuwata) [reply src/shared/mount-util.c]: OK. libmount_parse_mountinfo() and libmount_parse_with_utab() are introduced. PTAL.
