### PR TITLE
network,udev: add Property= setting in [Match] section

### LINKED ISSUE #5665: RFE: newtorkd: Match based on ID_SERIAL udev attribute
### Submission type

  - [ ] Bug report
  - [ x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232-r1

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Gentoo

I want to be able to use a key in the [Match] Section of a .link file in /etc/systemd/network that matches the udev attribute ID_SERIAL and/or ID_SERIAL_SHORT.

My use case is I want to give a predictable name to a USB Ethernet network device.  In this case, it is a Samsung Galaxy S7 phone connected via USB.  When I look at the keys available in the [Match] Section Options for network.link, None of the options can actually identify the device itself.  The device shows up with a MAC address of all zeros, and the value of the ID_PATH attribute depends on which USB port I plug into.  I am currently using the following....

```
[Match]
Driver=rndis_host

[Link]
Description="RNDIS Ethernet Device"
MacAddressPolicy="random"
Name="gs7"
```

But what I really want to use is something that has the model and serial number so that I can have a network interface name associated with the specific device.  Here is an excerpt from

```
udevadm info --export-db
```

```
P: /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.3/1-1.3:1.0/net/_gs7_
E: DEVPATH=/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.3/1-1.3:1.0/net/_gs7_
E: ID_BUS=usb
E: ID_MM_CANDIDATE=1
E: ID_MODEL=SAMSUNG_Android
E: ID_MODEL_ENC=SAMSUNG_Android
E: ID_MODEL_FROM_DATABASE=GT-I9070 (network tethering, USB debugging enabled)
E: ID_MODEL_ID=6864
E: ID_NET_DRIVER=rndis_host
E: ID_NET_LINK_FILE=/etc/systemd/network/20-galaxy_s7.link
E: ID_NET_NAME="gs7"
E: ID_NET_NAME_PATH=enp0s26u1u3
E: ID_PATH=pci-0000:00:1a.0-usb-0:1.3:1.0
E: ID_PATH_TAG=pci-0000_00_1a_0-usb-0_1_3_1_0
E: ID_REVISION=0400
E: ID_SERIAL=SAMSUNG_SAMSUNG_Android_126c5003
E: ID_SERIAL_SHORT=126c5003
E: ID_TYPE=generic
E: ID_USB_DRIVER=rndis_host
E: ID_USB_INTERFACES=:e00103:0a0000:ff4201:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=SAMSUNG
E: ID_VENDOR_ENC=SAMSUNG
E: ID_VENDOR_FROM_DATABASE=Samsung Electronics Co., Ltd
E: ID_VENDOR_ID=04e8
E: IFINDEX=11
E: INTERFACE=_gs7_
E: SUBSYSTEM=net
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/_gs7_ /sys/subsystem/net/devices/_gs7_
E: TAGS=:systemd:
E: USEC_INITIALIZED=50985903220
```

Here is the resulting netdev with the .link file I have now:

```
$ ip link ls dev _gs7_
11: _gs7_: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
```

and systemd journal output:

```
mars 29 20:48:08 akita systemd[1]: Started Network Service.
mars 29 20:48:08 akita systemd-networkd[25779]: work: Configured
mars 29 20:48:08 akita systemd-networkd[25779]: netboot: Configured
mars 29 20:48:08 akita systemd-networkd[25779]: eno1: Configured
mars 29 20:48:10 akita systemd-networkd[25779]: inet: Configured
mars 29 20:53:01 akita systemd-networkd[25779]: eth0: Renamed to _gs7_
```

By the way, shouldn't the netdev name be gs7, not _gs7_?  an shouldn't it have gotten a random, locally administered, unicast MAC?

### PR DESCRIPTION
**Pull request by yuwata**
Closes #5665.

### CODE REVIEW

File: src/libsystemd-network/network-internal.c [hunk 1]
```diff
@@ -164,7 +170,7 @@ int config_parse_net_condition(const char *unit,
         return 0;
 }
 
-int config_parse_ifnames(
+int config_parse_match_strv(
```
Comment (keszybz) [inline src/libsystemd-network/network-internal.c:224]: As I wrote in #12842, it'd be great to have a test for this, but it can be added in a later PR.

File: man/systemd.link.xml [hunk 2]
```diff
@@ -115,6 +115,20 @@
...
+        <term><varname>Property=</varname></term>
+        <listitem>
+          <para>A whitespace-separated list of udev property name with its value after a equal
+          (<literal>=</literal>). If multiple properties are specified, the test results are ANDed.
+          If the list is prefixed with a "!", the test is inverted.</para>
+
+          <para>Example: if a .network file has the following:
+          <programlisting>Property=ID_MODEL_ID=6864 ID_REVISION=0400</programlisting>
+          then, the .link file matches only when an interface has both
+          <literal>ID_MODEL_ID=6864</literal> and <literal>ID_REVISION=0400</literal>.
```
Comment (keszybz) [inline man/systemd.link.xml]: What about quoting and properties with "special characters", including whitespace? Or are udev properties guaranteed to contain no whitespace?

File: man/systemd.link.xml [hunk 3]
```diff
@@ -115,6 +115,20 @@
...
         </listitem>
       </varlistentry>
+      <varlistentry>
+        <term><varname>Property=</varname></term>
+        <listitem>
+          <para>A whitespace-separated list of udev property name with its value after a equal
+          (<literal>=</literal>). If multiple properties are specified, the test results are ANDed.
+          If the list is prefixed with a "!", the test is inverted.</para>
+
+          <para>Example: if a .network file has the following:
```
Comment (keszybz) [inline man/systemd.link.xml]: .link

File: src/libsystemd-network/network-internal.c [hunk 4]
```diff
@@ -101,11 +102,51 @@ static bool net_condition_test_strv(char * const *patterns, const char *string)
...
+                            sd_device_get_property_value(device, key, &dev_val) >= 0 &&
+                            fnmatch(val, dev_val, 0) == 0)
+                                return false;
+                } else {
+                        if (!device ||
+                            sd_device_get_property_value(device, key, &dev_val) < 0 ||
+                            fnmatch(val, dev_val, 0) != 0)
+                                return false;
+                }
+        }
```
Comment (keszybz) [inline src/libsystemd-network/network-internal.c:134]: This can be written as
```C
bool v = device && sd_device_get_property_value(device, key, &dev_val) >= 0 && fnmatch(val, dev_val, 0) == 0;
if (invert ? v : !v)
    return false;
```

File: src/libsystemd-network/network-internal.c [hunk 5]
```diff
@@ -101,11 +102,51 @@ static bool net_condition_test_strv(char * const *patterns, const char *string)
...
+                if (!buf)
+                        return log_oom();
+
+                invert = *buf == '!';
+                key = buf + invert;
+                val = strchr(buf, '=');
+                if (!val)
+                        return -EINVAL;
+                *val++ = '\0';
+
```
Comment (keszybz) [inline src/libsystemd-network/network-internal.c:121]:
```C
invert = **p == '!';
val = strchr(*p + invert, '=');
if (!val)
    return -EINVAL;
key = strndup(*p + invert, val - *p - invert);
```
?

**Comment by yuwata** [comment]
@keszybz Thank you for the comments. I've force-pushed an updated version. Changes are the following.
- fix the copy-paste mistake.
- add a test for new `config_parse_match_strv()` and friend.
- mention about the special character in the man page.
- apply the suggestions of the code optimization and readablity.

PTAL.

**Comment by yuwata** [comment]
A testcase is added.

File: man/systemd.link.xml [hunk 6]
```diff
@@ -115,6 +115,21 @@
           property <varname>DEVTYPE</varname>.</para>
         </listitem>
       </varlistentry>
+      <varlistentry>
```
Comment (keszybz) [inline man/systemd.link.xml:118]: Maybe move this to the very end of the [Match] options? It's a "catch all" option, and I think we should push people towards using the other possibilities. In particular, the rvalues in the other matches are well-defined and standardized, but udev properties not as much.

File: src/libsystemd-network/network-internal.c [hunk 7]
```diff
@@ -101,11 +102,46 @@ static bool net_condition_test_strv(char * const *patterns, const char *string)
...
+        if (strv_isempty(match_property))
+                return true;
+
+        STRV_FOREACH(p, match_property) {
+                _cleanup_free_ char *key = NULL;
+                const char *val, *dev_val;
+                bool invert, v;
+
+                invert = **p == '!';
```
Comment (keszybz) [inline src/libsystemd-network/network-internal.c:116]: So "!" is present in every element in the strv? Yeah, I see that config_parse_match_property() does that.

File: src/libsystemd-network/network-internal.c [hunk 8]
```diff
@@ -101,11 +102,46 @@ static bool net_condition_test_strv(char * const *patterns, const char *string)
...
+                if (!val)
+                        return -EINVAL;
+
+                key = strndup(*p + invert, val - *p - invert);
+                if (!key)
+                        return -ENOMEM;
+
+                val++;
+
+                v = device &&
```
Comment (keszybz) [inline src/libsystemd-network/network-internal.c:128]: Hmm, if `device == NULL`, this should return false, no? I.e. maybe change to
```C
   if (strv_isempty(match_property))
         return true;
   if (!device)
         return false;
```
and remove the check on `device` here?

File: man/systemd.link.xml (hunk 6 above)
Comment (yuwata) [reply man/systemd.link.xml:118]: `Type=` or `Driver=` correspond to udev properties and, thus, properties of the network interface.
However, `Host=` or `Virtualization=` do not correspond to udev property, and are system's condition.
So, I like the current position of `Property=`, that is, the end of the settings correspond to udev properties.

File: src/libsystemd-network/network-internal.c (hunk 7 above)
Comment (yuwata) [reply src/libsystemd-network/network-internal.c:116]: Yes.

File: src/libsystemd-network/network-internal.c (hunk 8 above)
Comment (yuwata) [reply src/libsystemd-network/network-internal.c:128]: If .network or .link file has the following,
```
Property=!KEY=value
```
then I think it should applied to interface which does not have `sd_device` object.
I think it is consistent to
```
Type=!dummy
```
In this case, even if `device` is null, the file is applied to the interface.

Comment (keszybz) [reply src/libsystemd-network/network-internal.c:128]: Oh, right, I didn't take this into account. So if we have a positive match (non-inverted), and device is NULL, the result should be false. If we have a negative match (inverted), and the device is NULL, the result should be true.
So I think something like this needs to be used:
```C
v = device &&
                        sd_device_get_property_value(device, key, &dev_val) >= 0 &&
                        fnmatch(val, dev_val, 0) == 0;
if (invert ? v : !v || !device)
             return false;
```

**Comment by keszybz** [comment]
I'm setting the "needs-rework" flag because I think the condition should be changed. PTAL.

File: src/libsystemd-network/network-internal.c (hunk 8 above)
Comment (yuwata) [reply src/libsystemd-network/network-internal.c:128]: ??? `|| !device` is completely redundant, isn't it?

Comment (keszybz) [reply src/libsystemd-network/network-internal.c:128]: Oh, right. I was an idiot. So indeed, this looks ok as is.
