### PR TITLE
conf-parser: ignore trailing back-slash in comment

### LINKED ISSUE #10598: Trailing backslash in comment is parsed resulting in comment line continuation
**systemd version the issue has been seen with**
> 239
> 237

**Used distribution**
 > 239 - 239.2-1 - Arch Linux
 > 237 - 237-3ubuntu10.3 - Ubuntu Bionic

**Expected behaviour you didn't see**
 > A comment does not effect any non-comment lines after the comment

**Unexpected behaviour you saw**
 > A comment that ends with a trailing backslash results in the following line being counted as a comment.

**Steps to reproduce the problem**

```
[Unit]
Description=Comment continuation test unit

[Service]
Type=simple
# This is comment that ends in a line continuation \
ExecStart=/usr/bin/sleep 900

[Install]
WantedBy=multi-user.target
```

Attempting to start this unit results in

```
Nov 01 09:12:30 hostname systemd[1]: test-unit.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #10598.

### CODE REVIEW

File: src/shared/conf-parser.c [hunk 1]
```diff
@@ -327,6 +327,9 @@ int config_parse(const char *unit,
                         return r;
                 }
 
+                if (strchr(COMMENTS, *buf))
+                        continue;
```
Comment (poettering) [inline src/shared/conf-parser.c:331]: i figure this means the matching check in parse_line() could be dropped then?

Comment (poettering) [reply src/shared/conf-parser.c:331]: hmm, is this even right? if i do the following

```
foo \
# bar
```
Then this should be considered equivalent to this I think:

```
foo # bar
```

but with your change it would be considered equivalent to 

```
foo
```

**Comment by yuwata** [comment]
Note `bash` treats comments and continuations like following, though systemd.syntax(7) said the our syntax is based on [XDG Desktop Entry Specification](http://standards.freedesktop.org/desktop-entry-spec/latest/).
```
$ cat hoge.sh
#!/bin/bash

echo hoge \
# aaa
bbb \
ccc \

echo foo \
# aaa \
bbb \
ccc \

# comment \
echo hogehoge \
aaa \
bbb
$ bash hoge.sh
hoge
hoge.sh: line 6: bbb: command not found
foo
hoge.sh: line 11: bbb: command not found
hogehoge aaa bbb
```

File: src/shared/conf-parser.c (hunk 1 above)
Comment (yuwata) [reply src/shared/conf-parser.c:331]: I thought only `foo` in this case is natural for me... But if you do not like that or you think we should not do that, then I will update this as `foo # bar` for this case.

Comment (keszybz) [reply src/shared/conf-parser.c:331]: The decision was made to follow bash some time ago. I was against...

File: src/test/test-conf-parser.c [hunk 2]
```diff
@@ -274,6 +274,18 @@ static const char* const config_file[] = {
...
+        "#hogehoge\\\n"      /* continuation is ignored in comment */
+        "setting1=1\\\n"     /* normal continuation */
+        "2\\\n"
+        "3\n",
+
+        "[Section]\n"
+        "setting1=1\\\n"     /* normal continuation */
+        "#hogehoge\\\n"      /* commented out line in continuation is ignored */
+        "2\\\n"
+        "3\n",
```
Comment (keszybz) [inline src/test/test-conf-parser.c:287]: This is the same example as the middle case in your `hoge.sh` bash example. And this patch implements different behaviour than bash :( This is exactly what I proposed back in the day, but the choice was made to follow bash. Dunno, I guess we can decide to break from bash, but then this needs to be documented.

If we follow bash semantics, this will be interpreted as:
```
[Section]
setting1=1
2 3
```

Comment (keszybz) [reply src/test/test-conf-parser.c:287]: To clarify: I think the bash behaviour is surprising and not very useful, and I think the behaviour that the patch currently implements is nice, but if we decide to do that, it needs to be a concious and documented choice.

Comment (yuwata) [reply src/test/test-conf-parser.c:287]: Yeah, I do not like the 2nd example for bash. So, I used a different approach in this PR.

Comment (kuroneko) [reply src/test/test-conf-parser.c:287]: The bash behaviour makes perfect sense given that the bash comment syntax is specifically a comment-to-end-of-line, and not a whole line comment construct.
In bash, 
```
foo # bcd
```

The lexer consumes `# bcd` as a comment.

```
foo \
# bcd \
efg
```

The lexer sees the continuation after `foo`, starts lexing the next line, sees the `#` and the consumes until the end of the line.  The continuation is met with the empty line prior to the comment mark - no further continuation is requested (it's commented out).  `efg` is a separate statement.

Whilst I think providing continuation through a comment seems reasonable with a line oriented syntax, it is not the expected behaviour for systems professionals who are used to the fact that the shells generally allow mid-statement comments, and parse all comments as such.

**Comment by keszybz** [comment]
I pushed documentation update.

File: man/systemd.syntax.xml [hunk 3]
```diff
@@ -73,7 +73,8 @@
     backslash is replaced by a space character. This may be used to wrap long lines. The limit on
     line length is very large (currently 1 MB), but it is recommended to avoid such long lines and
     use multiple directives, variable substitution, or other mechanism as appropriate for the given
-    file type.</para>
+    file type. When a comment line or lines follow a line ending with a backslash, the comment block
+    are ignored, so the continued line is concatenated with whatever follows the comment block.</para>
```
Comment (poettering) [inline man/systemd.syntax.xml]: are ignored → is ignored

**Comment by poettering** [comment]
the added doc seems to contain a typo

**Comment by yuwata** [comment]
OK, I will update this later.

**Comment by yuwata** [comment]
@poettering Updated.
- your first comment is addressed.
- fixed typo.

PTAL.
