### PR TITLE
journalctl: make --setup-keys honor --output=json and --quiet

### LINKED ISSUE #35503: journalctl --output=json --setup-keys does not output json
### systemd version the issue has been seen with

v257-rc3)

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

journalctl

### Expected behaviour you didn't see

Output json

### Unexpected behaviour you saw

Plain text output

### Steps to reproduce the problem

```
# journalctl --output=json --setup-keys --force
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Generating seed...
Generating key pair...
Generating sealing key...

New keys have been generated for host <host_id>.

The secret sealing key has been written to the following local file.
This key file is automatically updated when the sealing key is advanced.
It should not be used on multiple hosts.

	/var/log/journal/<journal id>/fss

The sealing key is automatically changed every 15min.

Please write down the following secret verification key. It should be stored
in a safe location and should not be saved locally on disk.

	<secret_id>
```

The relevant source code here shows that output is not respected:

https://github.com/systemd/systemd/blob/59ea5e4c445f7ec80ef1800318843524cdc29a40/src/journal/journalctl-authenticate.c#L169
```

### LINKED ISSUE #35504: journalctl --setup-keys does not respect --quiet
### systemd version the issue has been seen with

256.5-2ubuntu3.1

### Used distribution

Ubuntu 22.04

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

journalctl

### Expected behaviour you didn't see

No extra output

### Unexpected behaviour you saw

```
Generating seed...
Generating key pair...
Generating sealing key...
```

### Steps to reproduce the problem

```
# journalctl --quiet --setup-keys --force
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Generating seed...
Generating key pair...
Generating sealing key...
Unable to set file attribute 0x800000 on n/a, ignoring: Operation not supported

New keys have been generated for host <host_id.

The secret sealing key has been written to the following local file.
This key file is automatically updated when the sealing key is advanced.
It should not be used on multiple hosts.

	/var/log/journal/<journal_id>/fss

The sealing key is automatically changed every 15min.

Please write down the following secret verification key. It should be stored
in a safe location and should not be saved locally on disk.

	<verification_key>
```
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #35503.
Closes #35504.

### CODE REVIEW

File: src/journal/journalctl-authenticate.c [hunk 1]
```diff
@@ -60,33 +62,35 @@ int action_setup_keys(void) {
...
         assert(arg_action == ACTION_SETUP_KEYS);
 
+        int log_level = arg_quiet ? LOG_DEBUG : LOG_ERR;
+
         r = is_dir("/var/log/journal/", /* follow = */ false);
         if (r == 0)
-                return log_error_errno(SYNTHETIC_ERRNO(ENOTDIR),
-                                       "/var/log/journal is not a directory, must be using persistent logging for FSS.");
+                return log_full_errno(log_level, SYNTHETIC_ERRNO(ENOTDIR),
+                                      "/var/log/journal is not a directory, must be using persistent logging for FSS.");
```
Comment (betelgeuse) [inline src/journal/journalctl-authenticate.c]: Error message are probably not something that --quiet should hide. The description is: `Do not show info messages and privilege warning`

**Review by bluca — APPROVED** [review]
