### PR TITLE
repart: Restore early fstab/crypttab generation

### LINKED ISSUE #40444: systemd-repart: REGRESSION, /etc/fstab will not be written to image anymore
### systemd version the issue has been seen with

260~devel+git20260123

### Used distribution

openSUSE Tumbleweed

### Linux kernel version used

6.18.5-1-default

### CPU architectures issue was seen on

x86_64

### Component

systemd-repart

### Expected behaviour you didn't see

Build images with mkosi and using mkosi.repart. With systemd git snapshot from 19.1. a `/etc/fstab` file got generated, with a git snapshot from today this file got no longer generated.
But mkosi prints:
```
Writing new partition table.
All done.
/buildroot/etc/fstab written.
```

With the some days older systemd-repart the output was:
```
‣  Generating disk image
/buildroot/etc/fstab written.
```

My impression from the logs: /etc/fstab will be generated too late now and only written to the /buildroot, when the image got already created. So it will never be copied into it.

That's why I assume this commit is not correct:
```
commit 15b1c334dff04708e2ba6ba712a1474f0128563c
Author: Vitaly Kuznetsov <vkuznets@redhat.com>
Date:   Mon Jan 12 17:05:59 2026 +0100

    repart: Generate fstab and crypttab late
    
    The immediate need for the change is to allow to capture the expected
    LUKS volume key hash and record it to the generated crypttab but it
    also seems to make sense to not generate crypttab/fstab before we know
    that partition creation succeeded as fstab/crypttab entries are bogus
    otherwise.
```

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by vittyvk**
fstab/crypttab generation were moved to the late stage to support 'fixate-volume-key' option. This, however, broke the use-case when fstab/crypttab are put to the generated partition/image. 

Fixes #40444

### CODE REVIEW

File: src/repart/repart.c [hunk 1]
```diff
@@ -10809,11 +10817,7 @@ static int run(int argc, char *argv[]) {
         if (r < 0)
                 return r;
 
-        r = context_fstab(context);
-        if (r < 0)
-                return r;
-
-        r = context_crypttab(context);
+        r = context_crypttab(context, /* late = */ true);
```
Comment (yuwata) [inline src/repart/repart.c]: Please drop space between `late` and `=` in the comment.

File: test/units/TEST-58-REPART.sh [hunk 2]
```diff
@@ -1997,6 +1997,68 @@ EOF
     losetup -d "$loop"
 }
 
+testcase_fstab_crypttab_in_repart() {
+    local defs imgs output root
```
Comment (yuwata) [inline test/units/TEST-58-REPART.sh]: `output` is unused. Please list `volume` here.

**Review by yuwata — APPROVED** [review]
LGTM. Two minor requests.

File: test/units/TEST-58-REPART.sh (hunk 2 above)
Comment (vittyvk) [reply test/units/TEST-58-REPART.sh]: Fixed.

File: src/repart/repart.c (hunk 1 above)
Comment (vittyvk) [reply src/repart/repart.c]: Dropped.
