### PR TITLE
journal: refresh cached credentials of stdout streams

### LINKED ISSUE #13708: Changing process PID causing journal logs to show old PID then logs are missing _SYSTEMD_ tags after a restart of systemd-journald
**systemd version the issue has been seen with**
systemd 243 (243.51-1-arch)

**Used distribution**
 Arch Linux

**Expected behaviour you didn't see**
 Logging for a process using [tableflip](https://github.com/cloudflare/tableflip) for graceful upgrades stays visible in `journalctl -u` with the correct PID and `_SYSTEMD_` tags stay present after a graceful upgrade of the process followed by a restart of `systemd-journald`.

**Unexpected behaviour you saw**
Logging for a process using [tableflip](https://github.com/cloudflare/tableflip) for graceful upgrades has the old PID following a graceful upgrade, logs are not visible in `journalctl -u` and `_SYSTEMD_` tags are missing after a restart of `systemd-journald`.

Our understanding of the problem is that the default `systemd` logging setup for `StandardOutput` and `StandardError` uses `SOCK_STREAM` sockets to `/run/systemd/journal/stdout`
```
[pid  6307] socket(AF_UNIX, SOCK_STREAM, 0) = 3
[pid  6307] connect(3, {sa_family=AF_UNIX, sun_path="/run/systemd/journal/stdout"}, 30) = 0
[pid  6307] shutdown(3, SHUT_RD)        = 0
[pid  6307] getsockopt(3, SOL_SOCKET, SO_SNDBUF, [212992], [4]) = 0
[pid  6307] setsockopt(3, SOL_SOCKET, SO_SNDBUF, [8388608], 4) = 0
[pid  6307] fstat(3, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
[pid  6307] lseek(3, 0, SEEK_CUR)       = -1 ESPIPE (Illegal seek)
[pid  6307] write(3, "missing-logs\n\n30\n1\n0\n0\n0\n", 25) = 25
[pid  6307] dup3(3, 1, 0)               = 1
[pid  6307] close(3)                    = 0
[pid  6307] fstat(1, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
[pid  6307] dup2(1, 2)                  = 2
```

On the other end `systemd-journald` gets the peer PID by calling `getsockopt` to get `SO_PEERCRED`
```
accept4(3, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = 101
getsockopt(101, SOL_SOCKET, SO_PEERCRED, {pid=6307, uid=1000, gid=1000}, [12]) = 0
shutdown(101, SHUT_WR)                  = 0
epoll_ctl(89, EPOLL_CTL_ADD, 101, {EPOLLIN, {u32=2065424624, u64=94194993193200}}) = 0
epoll_wait(89, [{EPOLLIN, {u32=2065424624, u64=94194993193200}}], 100, -1) = 1
read(101, "missing-logs\n\n30\n1\n0\n0\n0\n", 2055) = 25
```

Because [tableflip](https://github.com/cloudflare/tableflip) passes all file descriptors (including `STDOUT` and `STDERR`) to the new process during the graceful upgrade, the problem is twofold:

- the socket stays open and `systemd-journald` still maps incoming logs to the old PID, showing incorrectly in the output
- after getting restarted, `systemd-journald`, is unable to reconstruct metadata for the process since calling `getsockopt` on that socket to get the peer PID from `SO_PEERCRED` on start will still return the old PID for which all `/proc` references are gone.

```
read(8, "PID:6842 2019/10/02 17:11:56 Hel"..., 2055) = 36
openat(AT_FDCWD, "/proc/6307/comm", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
readlinkat(AT_FDCWD, "/proc/6307/exe", 0x564b7d588b60, 4096) = -1 ENOENT (No such file or directory)
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
openat(AT_FDCWD, "/proc/6307/cmdline", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/6307/status", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/6307/sessionid", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/6307/loginuid", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/6307/cgroup", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/log/journal/e08bf831a8034fbca67c2e3e4043443b/system.journal", O_RDWR|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

The workaround we have found so far is to log to `/run/systemd/journal/socket` with libraries using `SOCK_DGRAM` so `SCM_CREDENTIALS` are passed and the `PID` stays up-to-date.
But ideally, we'd keep logging to `STDOUT` which is more portable.

**Steps to reproduce the problem**
Build this Go program using [tableflip](https://github.com/cloudflare/tableflip):
```
$ echo 'package main

import (
        "flag"
        "fmt"
        "log"
        "os"
        "os/signal"
        "syscall"

        "github.com/cloudflare/tableflip"
)

func main() {
        var (
                pidFile = flag.String("pid-file", "", "`Path` to pid file")
        )

        flag.Parse()
        log.SetPrefix(fmt.Sprintf("PID:%d ", os.Getpid()))

        upg, err := tableflip.New(tableflip.Options{
                PIDFile: *pidFile,
        })
        if err != nil {
                panic(err)
        }
        defer upg.Stop()

        // Do an upgrade on SIGHUP
        go func() {
                sig := make(chan os.Signal, 1)
                signal.Notify(sig, syscall.SIGHUP)
                for range sig {
                        err := upg.Upgrade()
                        if err != nil {
                                log.Println("Upgrade failed:", err)
                        }
                }
        }()

        log.Printf("Hello.")

        if err := upg.Ready(); err != nil {
                panic(err)
        }
        <-upg.Exit()
}' > /tmp/missing-logs.go
$ cd /tmp
$ go build missing-logs.go
```

And create a systemd unit
```
$ echo '[Unit]
Description=missing-logs

[Service]
Type=simple
ExecStart=/tmp/missing-logs -pid-file /tmp/missing-logs.pid
ExecReload=/bin/kill -HUP $MAINPID
PIDFile=/tmp/missing-logs.pid' > ~/.config/systemd/user/missing-logs.service
$ systemctl --user daemon-reload
```

Run the unit
```
$ systemctl --user start missing-logs
```

See it is logging fine with the correct PID (5408)
```
$ systemctl --user status missing-logs
● missing-logs.service - missing-logs
   Loaded: loaded (/home/tlefebvre/.config/systemd/user/missing-logs.service; static; vendor preset: enabled)
   Active: active (running) since Wed 2019-10-02 16:36:15 PDT; 1s ago
 Main PID: 5408 (missing-logs)
   CGroup: /user.slice/user-1000.slice/user@1000.service/missing-logs.service
           └─5408 /tmp/missing-logs -pid-file /tmp/missing-logs.pid

Oct 02 16:36:15 arch-x1 systemd[770]: Started missing-logs.
Oct 02 16:36:15 arch-x1 missing-logs[5408]: PID:5408 2019/10/02 16:36:15 Hello.
```

Trigger a graceful reload
```
$ systemctl --user reload missing-logs
```

See it is still logging fine albeit the PID reported by systemd-journald being wrong (5408 instead of 5436, though correctly reported by `Main PID`)
```
$ systemctl --user status missing-logs
● missing-logs.service - missing-logs
   Loaded: loaded (/home/tlefebvre/.config/systemd/user/missing-logs.service; static; vendor preset: enabled)
   Active: active (running) since Wed 2019-10-02 16:36:15 PDT; 58s ago
  Process: 5435 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 5436 (missing-logs)
   CGroup: /user.slice/user-1000.slice/user@1000.service/missing-logs.service
           └─5436 /tmp/missing-logs -pid-file /tmp/missing-logs.pid

Oct 02 16:36:15 arch-x1 systemd[770]: Started missing-logs.
Oct 02 16:36:15 arch-x1 missing-logs[5408]: PID:5408 2019/10/02 16:36:15 Hello.
Oct 02 16:37:13 arch-x1 systemd[770]: Reloading missing-logs.
Oct 02 16:37:13 arch-x1 systemd[770]: Reloaded missing-logs.
Oct 02 16:37:13 arch-x1 missing-logs[5408]: PID:5436 2019/10/02 16:37:13 Hello.
```

Now, restart systemd-journald and trigger another reload
```
$ sudo systemctl restart systemd-journald
$ systemctl --user reload missing-logs
```

Notice we are not getting logs anymore for the unit, despite the new PID (5492) being correctly tracked in `Main PID`
```
$ systemctl --user status missing-logs
● missing-logs.service - missing-logs
   Loaded: loaded (/home/tlefebvre/.config/systemd/user/missing-logs.service; static; vendor preset: enabled)
   Active: active (running) since Wed 2019-10-02 16:36:15 PDT; 2min 39s ago
  Process: 5491 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 5492 (missing-logs)
   CGroup: /user.slice/user-1000.slice/user@1000.service/missing-logs.service
           └─5492 /tmp/missing-logs -pid-file /tmp/missing-logs.pid

Oct 02 16:36:15 arch-x1 systemd[770]: Started missing-logs.
Oct 02 16:36:15 arch-x1 missing-logs[5408]: PID:5408 2019/10/02 16:36:15 Hello.
Oct 02 16:37:13 arch-x1 systemd[770]: Reloading missing-logs.
Oct 02 16:37:13 arch-x1 systemd[770]: Reloaded missing-logs.
Oct 02 16:37:13 arch-x1 missing-logs[5408]: PID:5436 2019/10/02 16:37:13 Hello.
Oct 02 16:38:49 arch-x1 systemd[770]: Reloading missing-logs.
Oct 02 16:38:49 arch-x1 systemd[770]: Reloaded missing-logs.
```

Some logs are still available looking at the `missing-logs` tag, but are depleted of `_SYSTEMD_` tags such as `_SYSTEMD_UNIT` which causes them to stop showing up in journal for the unit.
```
$ journalctl --user -t missing-logs -o verbose
Wed 2019-10-02 16:38:49.947469 PDT [s=72e1c146a73243cb85f8350936b452e9;i=f1d0b;b=f3eab880cbef4f459070c9501988e035;m=854b7586;t=593f5f88f094d;x=b7434a687f6d0ee8]
    _TRANSPORT=stdout
    PRIORITY=6
    _UID=1000
    _GID=1000
    _MACHINE_ID=e08bf831a8034fbca67c2e3e4043443b
    _HOSTNAME=arch-x1
    _BOOT_ID=f3eab880cbef4f459070c9501988e035
    _STREAM_ID=632c7cb249bb4e0bb5c8abef8676cb7b
    SYSLOG_IDENTIFIER=missing-logs
    _PID=5408
    MESSAGE=PID:5492 2019/10/02 16:38:49 Hello.
```

Happy to give more information if needed, thanks for your help!

### PR DESCRIPTION
**Pull request by lmb**
journald assumes that getsockopt(SO_PEERCRED) correctly identifies the
process on the remote end of the socket. However, this is incorrect
according to man 7 socket:

    The returned  credentials  are  those that were in effect at the
    time of the call to connect(2) or socketpair(2).

This becomes a problem when a new process inherits the stdout stream
from a parent. First, log messages from the child process will
be attributed to the parent. Second, the struct ucred used by journald
becomes invalid as soon as the parent exits. Further sendmsg calls then
fail with ENOENT. Logs for the child process then vanish from the journal.

Fix this by using recvmsg on the stdout stream, and refreshing the cached
struct ucred if SCM_CREDENTIALS indicate a new process.

Fixes #13708

### CODE REVIEW

**Comment by lmb** [comment]
@yuwata is there something I can do to help with reviewing?

**Comment by poettering** [comment]
hmm, does this actually work? have you verified this? I am a bit surprised that this is supposed to work, I wasn't aware the SO_PASSCRED had any effect on SOCK_STREAM sockets...

**Comment by lmb** [comment]
Hi Lennart,


Yep, I tested this by generating an image via mkosi, running that and 
generating a message using systemd-cat. stracing journald shows that it 
receives SCM_CREDENTIALS.

**Comment by lmb** [comment]
I've added an integration test which checks that this works.

**Comment by lmb** [comment]
Ping @poettering and @yuwata. Not sure how to make the builders happy, it seems like they timed out? Otherwise this "works", but I'd appreciate your feedback.

**Comment by yuwata** [comment]
```
FAILED TESTS:  TEST-04-JOURNAL
autopkgtest [17:21:13]: test upstream: -----------------------]
autopkgtest [17:21:13]: test upstream:  - - - - - - - - - - results - - - - - - - - - -
upstream             FAIL non-zero exit status 1
```
The failure seems to be related to this PR.

**Comment by lmb** [comment]
@yuwata I don't think so. I just re-ran the test on my machine, and it passed:

```
$ sudo make -C test/TEST-04-JOURNAL KERNEL_APPEND="cryptopts=" clean setup run
...
[  OK  ] Reached target Power-Off.
Container nspawn-root has been shut down.
-rw-r-----+ 1 root systemd-journal 8388608 Oct 30 16:35 /var/tmp/systemd-test.8af7t2/journal/54c00a0fab604a5a98bdd29c2fd1b90d/system.journal
-rw-r-----+ 1 root systemd-journal 5607424 Oct 30 16:35 /var/tmp/systemd-test.8af7t2/journal/b22d29db53b34d78bfc1315707de1714/system.journal
TEST RUN: Journal-related tests [OK]
make: Leaving directory '/home/lorenz/dev/systemd/test/TEST-04-JOURNAL'
```

 Note also that the autopkgtest for i386 and s390x pass.

**Comment by evverx** [comment]
TEST-04 has never been flaky as far as I can remember so it looks like with this patch applied the test is less stable than usual, which most likely means that either something doesn't work as expected or the test itself is flaky. Could you force-push the code to trigger the CI once again? I think if Ubuntu CI passes, say, 5 times in a row, it will be safe to say that it's no longer flaky. I'll go ahead and add the "ci-fails" label. Could you also try running `journalctl --sync` before `journalctl -b ...` to make sure all the logs are written?

**Comment by lmb** [comment]
Thanks, I've added the `journalctl --sync` invocation. Now only 2 instead of 3 CI runs fail! I've added a commit on top which makes the test print itself to the system console. This is a hack, but I couldn't find a way to access this info via the CI UI.

**Comment by evverx** [comment]
FWIW I managed to reproduce the failure with `TEST_NO_KVM` (which slows down VMs to somewhat emulate Ubuntu CI). The test failed because `grep` couldn't find logs starting with `PID`. `journalctl --sync` fixes that but on my machine it seems to be failing to connect to `journald` via `varlink` (somewhat unpredictably). I'm not sure but maybe it has something to do with SIGKILL we send in the previous substest :-)

> This is a hack, but I couldn't find a way to access this info via the CI UI.

There's no way to look at what's going on there as far as I know (apart from downloading the artifacts from Ubuntu CI and searching for the journal files from VMs QEMU runs). In fact, at some point I think it would be great to start using `journal+console': https://github.com/systemd/systemd/pull/13719#issuecomment-540052553 :-)

**Comment by evverx** [comment]
On my machine the test keeps failing intermittently with
```
[  135.094035] test-journal.sh[417]: + sleep 3
[  135.103719] test-journal.sh[417]: + [[ ! -f /i-lose-my-logs ]]
[  135.130417] test-journal.sh[552]: ++ sed -n 2p
[  135.156334] test-journal.sh[551]: ++ journalctl --new-id128
[  135.173876] test-journal.sh[417]: + ID=cf4f06648442480fab65d63dfc7ce62b
[  135.182686] test-journal.sh[417]: + PID=554
[  135.186328] test-journal.sh[417]: + wait %%
[  135.206088] test-journal.sh[554]: + systemd-cat -t cf4f06648442480fab65d63dfc7ce62b bash -c 'echo parent; (echo child) & wait'
[  135.224238] test-journal.sh[417]: + journalctl --sync
[  135.241017] test-journal.sh[556]: Failed to connect to /run/systemd/journal/io.systemd.journal: Connection refused
```
Though I don't think it has anything to do with this PR. Maybe for the time being it would make sense to move the new subtest before the part where we make sure that journald doesn't lose data.

**Comment by lmb** [comment]
4/5 autopkgtest passed, which I'm taking as an indication that your fix works @evverx. Thanks for helping me out. I've removed the WIP commit and pushed again, hopefully this means I'll get a clean bill of health over the weekend. CI taking more than 7 hours to run is kind of insane.

File: test/TEST-04-JOURNAL/test-journal.sh [hunk 1]
```diff
@@ -74,6 +74,20 @@ cmp /expected /output
 { journalctl -ball -b  -m 2>&1 || :; } | head -1 > /output
 cmp /expected /output
 
+# https://github.com/systemd/systemd/issues/13708
+ID=$(journalctl --new-id128 | sed -n 2p)
```
Comment (keszybz) [inline test/TEST-04-JOURNAL/test-journal.sh]: Just `systemd-id128 new`.

File: test/TEST-04-JOURNAL/test-journal.sh [hunk 2]
```diff
@@ -74,6 +74,20 @@ cmp /expected /output
...
+systemd-cat -t "$ID" bash -c 'echo parent; (echo child) & wait' &
+PID=$!
+wait %%
+journalctl --sync
+journalctl -b -o export -t "$ID" --output-fields=_PID | grep '^_PID=' >/output
```
Comment (keszybz) [inline test/TEST-04-JOURNAL/test-journal.sh:85]: Hmm, this should not be handled here, but isn't this a bug in `journalctl`? It outputs fields like __CURSOR and __REALTIME which it shouldn't. @poettering opinions?

File: src/journal/journald-stream.c [hunk 3]
```diff
@@ -487,11 +487,24 @@ static int stdout_stream_scan(StdoutStream *s, bool force_flush) {
...
         ssize_t l;
         int r;
 
+        struct msghdr msghdr = {
+                .msg_iov = &iovec,
+                .msg_iovlen = 1,
+                .msg_control = buf,
+                .msg_controllen = sizeof(buf),
+                .msg_name = NULL,
+                .msg_namelen = 0,
```
Comment (keszybz) [inline src/journal/journald-stream.c]: No need to iniatialize `.msg_name` and `.msg_namelen` here.

File: src/journal/journald-stream.c [hunk 4]
```diff
@@ -511,20 +524,46 @@ static int stdout_stream_process(sd_event_source *es, int fd, uint32_t revents,
...
                 stdout_stream_scan(s, true);
                 goto terminate;
         }
 
+        CMSG_FOREACH(cmsg, &msghdr) {
+                if (cmsg->cmsg_level == SOL_SOCKET &&
+                    cmsg->cmsg_type == SCM_CREDENTIALS &&
+                    cmsg->cmsg_len == CMSG_LEN(sizeof(struct ucred)))
+                        ucred = (struct ucred *)CMSG_DATA(cmsg);
+        }
```
Comment (keszybz) [inline src/journal/journald-stream.c]: `{}` not needed.

Please add `break` after `ucred =` is assigned. There should be only one, and we can short-circuit the loop then.

File: test/TEST-04-JOURNAL/test-journal.sh (hunk 2 above)
Comment (lmb) [reply test/TEST-04-JOURNAL/test-journal.sh:85]: What do you mean when you say "this"? FWIW __CURSOR etc. have been output by the export format for a long time according to git blame.

Comment (keszybz) [reply test/TEST-04-JOURNAL/test-journal.sh:85]: >  FWIW __CURSOR etc. have been output by the export format for a long time according to git blame.

Yeah, and I think this is a bug. They are written in a separate part of the code than the other fields (because they are based on the entry header, not data), and I think this was overlooked when `--output-fields=` was being implemented. But I don't think we can just change this at this point, because of backwards compatibility concerns.

Maybe we should add `--only-fields=` that would only write the specified fields.

Comment (lmb) [reply test/TEST-04-JOURNAL/test-journal.sh:85]: If you want to create an issue I can add a comment which references it.

File: src/journal/journald-stream.c [hunk 5]
```diff
@@ -511,20 +522,47 @@ static int stdout_stream_process(sd_event_source *es, int fd, uint32_t revents,
...
+         * from a parent. In this case getpeercred returns the ucred
+         * of the parent, which can be invalid if the parent has exited
+         * in the meantime.
+         */
+        if (ucred && ucred->pid != s->ucred.pid) {
+                r = stdout_stream_scan(s, true);
+                if (r < 0)
+                        goto terminate;
+
+                memcpy(&s->ucred, ucred, sizeof(s->ucred));
```
Comment (poettering) [inline src/journal/journald-stream.c]: why not just `s->ucred = *ucred`?

File: src/journal/journald-stream.c [hunk 6]
```diff
@@ -511,20 +522,47 @@ static int stdout_stream_process(sd_event_source *es, int fd, uint32_t revents,
...
+                }
+
+        /* Invalidate the context if the pid of the sender changed.
+         * This happens when a forked process inherits stdout / stderr
+         * from a parent. In this case getpeercred returns the ucred
+         * of the parent, which can be invalid if the parent has exited
+         * in the meantime.
+         */
+        if (ucred && ucred->pid != s->ucred.pid) {
+                r = stdout_stream_scan(s, true);
```
Comment (poettering) [inline src/journal/journald-stream.c:560]: can you add a comment here? i.e.

``/* force out any previously half-written lines from a different process, before we switch to the new ucred structure for everything we just added */``

**Comment by poettering** [comment]
two minor issues. look good to merge otherwise

File: test/TEST-04-JOURNAL/test-journal.sh (hunk 2 above)
Comment (keszybz) [reply test/TEST-04-JOURNAL/test-journal.sh:85]: It seems we already have an issue: #5697.

Comment (keszybz) [reply test/TEST-04-JOURNAL/test-journal.sh:85]: Never mind, #5697 is about a different issue.
I opened #13937 now.

**Comment by keszybz** [comment]
```
[coredumpctl_collect] Gathering coredumps for '/build/build/test-journal-flush'
           PID: 2419 (test-journal-fl)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Mon 2019-11-04 18:40:55 CET (1h 2min ago)
  Command Line: /build/build/test-journal-flush
    Executable: /build/build/test-journal-flush
 Control Group: /user.slice/user-1000.slice/session-3.scope
          Unit: session-3.scope
         Slice: user-1000.slice
       Session: 3
     Owner UID: 1000 (vagrant)
       Boot ID: 55e7bd01087c4bb09dc6d35d29c71447
    Machine ID: 125938f1dabc4d79bd2b0d8e77d2fbc1
      Hostname: arch.localdomain
       Storage: /var/lib/systemd/coredump/core.test-journal-fl.0.55e7bd01087c4bb09dc6d35d29c71447.2419.1572889255000000000000.lz4
       Message: Process 2419 (test-journal-fl) of user 0 dumped core.
                
                Stack trace of thread 2419:
                #0  0x00007f52b2ddbf25 raise (libc.so.6 + 0x3bf25)
                #1  0x00007f52b2dc5897 abort (libc.so.6 + 0x25897)
                #2  0x00007f52b305cf8e log_assert_failed_realm (libsystemd-shared-243.so + 0xf4f8e)
                #3  0x00005598dc26d5d2 main (test-journal-flush + 0x15d2)
                #4  0x00007f52b2dc7153 __libc_start_main (libc.so.6 + 0x27153)
                #5  0x00005598dc26d18e _start (test-journal-flush + 0x118e)

```

**Comment by evverx** [comment]
FWIW `test-journal-flush` is flaky and has been failing sporadically since it was introduced as far as I know so I don't think it has anything to do with this PR. I would also add that it's not exactly a unit test and should probably be moved elsewhere: https://github.com/systemd/systemd/pull/13246#issuecomment-517828439.

**Comment by keszybz** [comment]
OK. Let's wait for the other checks to run though.

**Comment by keszybz** [comment]
CentOS CI (Arch in KVM) failed in test-journal-flush again.
