### PR TITLE
core: follow-ups for recent PRs

### LINKED ISSUE #34252: Some post-merge issues to fix on BindJournalSockets=
### systemd version the issue has been seen with

git main

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

See my comments here:

https://github.com/systemd/systemd/pull/32487#issuecomment-2328465309

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by YHNdnzj**
Fixes #34252

### CODE REVIEW

File: src/core/namespace.c [hunk 1]
```diff
@@ -2791,21 +2790,17 @@ int bind_mount_add(BindMount **b, size_t *n, const BindMount *item) {
...
-        if (!c)
+        if (!GREEDY_REALLOC_APPEND(*b, *n,
+                                   (&(BindMount) {
+                                           .source = TAKE_PTR(s),
+                                           .destination = TAKE_PTR(d),
+                                           .read_only = item->read_only,
+                                           .nosuid = item->nosuid,
+                                           .recursive = item->recursive,
+                                           .ignore_enoent = item->ignore_enoent,
+                                   }), 1))
```
Comment (poettering) [inline src/core/namespace.c]: hmm, this would mean in case of OOM we invalidated s and d already, and thus would leak the two allocations

File: src/core/namespace.h [hunk 2]
```diff
@@ -66,6 +66,7 @@ struct BindMount {
         char *destination;
         bool read_only;
         bool nosuid;
+        bool noexec;
```
Comment (poettering) [inline src/core/namespace.h:70]: (i guess we could add "nodev" here too one day)

File: src/core/service.c [hunk 3]
```diff
@@ -2106,13 +2090,19 @@ static void service_enter_dead(Service *s, ServiceResult f, bool allow_restart)
...
                 }
 
-                log_unit_debug(UNIT(s), "Next restart interval calculated as: %s", FORMAT_TIMESPAN(restart_usec_next, 0));
-
                 /* If the relevant option is set, and the unit doesn't already have logging level set to
                  * debug, enable it now. Make sure to overwrite the state in /run/systemd/units/ too, to
                  * ensure journald doesn't prune the messages. The previous state is saved and restored
                  * once the auto-restart flow ends. */
-                service_set_debug_invocation(s, /* enable= */ true);
+                if (s->restart_mode == SERVICE_RESTART_MODE_DEBUG) {
```
Comment (bluca) [inline src/core/service.c:2092]: https://github.com/systemd/systemd/pull/33877#discussion_r1728815318 explicitly asked to remove the conditionalization, which is being added back here

Comment (YHNdnzj) [reply src/core/service.c:2092]: I think conditionalizing this here makes more sense, also corresponding to the `RESTART_MODE_DIRECT` branch above.

File: src/core/service.c [hunk 4]
```diff
@@ -2116,7 +2106,7 @@ static void service_enter_dead(Service *s, ServiceResult f, bool allow_restart)
                  * can still introspect the counter. */
                 service_set_state(s, end_state);
 
-                service_set_debug_invocation(s, /* enable= */ false);
+                (void) unit_set_debug_invocation(UNIT(s), false);
```
Comment (yuwata) [inline src/core/service.c:2109]: `/* enable = */` is dropped.

File: src/core/service.c [hunk 5]
```diff
@@ -2101,13 +2085,19 @@ static void service_enter_dead(Service *s, ServiceResult f, bool allow_restart)
...
 
-                log_unit_debug(UNIT(s), "Next restart interval calculated as: %s", FORMAT_TIMESPAN(restart_usec_next, 0));
-
                 /* If the relevant option is set, and the unit doesn't already have logging level set to
                  * debug, enable it now. Make sure to overwrite the state in /run/systemd/units/ too, to
                  * ensure journald doesn't prune the messages. The previous state is saved and restored
                  * once the auto-restart flow ends. */
-                service_set_debug_invocation(s, /* enable= */ true);
+                if (s->restart_mode == SERVICE_RESTART_MODE_DEBUG) {
+                        r = unit_set_debug_invocation(UNIT(s), true);
```
Comment (yuwata) [inline src/core/service.c:2093]: Also here.

File: src/core/service.c (hunk 4 above)
Comment (YHNdnzj) [reply src/core/service.c:2109]: I don't think it's actually necessary? E.g. we don't add such comments for fd_cloexec, because the name already clearly encodes the meaning/action here.

Comment (poettering) [reply src/core/service.c:2109]: yeah, i'd agree with @YHNdnzj. if the function name makes clear enough what the parameter is no need to add the extra config. hence, yes, if we have a setter call then i think it's pretty clear that first arg is the object to set the thing on, and 2nd arg is the value to set that thing to.

**Comment by poettering** [comment]
(i'd be fine if people add those comments in these cases too btw. i just don't think we should require them here, and i myself probably wouldn't place them)
