### PR TITLE
network:dhcp4: request domain search list if UseDomains=yes

### LINKED ISSUE #8174: systemd-networkd DHCP search domains option
### Submission type
 - Bug report
 - Request for enhancement (RFE)

### Expected/Unexpected behaviour:

> I expected that by enabling `[DHCP]: UseDomains=true` in network configuration, the DHCP client would use DHCP provided search domains. The client only uses DHCP provided search domains if the server specifies this option as "forced"

I think that this can be broken into two parts. First, I think that the DHCP client should always get the search domains option (119). The decision about what to do (or not to do with that information) could be separated.

1. I'm using dnsmasq as the DHCP server. If I use `dhcp-option-force=option:domain-search,example.com` on the server, then `DOMAIN_SEARCH_LIST=example.com` appears in `/run/systemd/netif/leases/2` client lease info. If I use  `dhcp-option=option:domain-search,example.com`, then the lease info file does not contain a `DOMAIN_SEARCH_LIST` entry (the client did not request this option). For comparison, providing the NTP option from the server causes the corresponding entry in the client lease whether the option was "forced" or not. Again, I think the client should always get this information, even if it's not consumed by the network configuration.

2. Setting the `UseDomains=true` network configuration option adds both the domain and the domain-search values to "Search Domains" as reported by `networkctl status` and "DNS Domain" as reported by `systemd-resolve --status` and conversely no such search domains are setup when `UseDomains` is not set (or false). I think that this behavior of combining the domain and the domain-search values is acceptable but then I would expect `UseDomains` to also cause the DHCP client to request the domain-search option from the server (if it isn't always requested per the first section). Alternatively, a new option would need to be provided such as `UseSearchDomains`.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #8174.

### CODE REVIEW

File: src/network/networkd-dhcp4.c [hunk 1]
```diff
@@ -1041,6 +1041,12 @@ int dhcp4_configure(Link *link) {
                         return log_link_error_errno(link, r, "DHCP4 CLIENT: Failed to set request flag for classless static route: %m");
         }
 
+        if (link->network->dhcp_use_domains != DHCP_USE_DOMAINS_NO && !link->network->dhcp_anonymize) {
+                r = sd_dhcp_client_set_request_option(link->dhcp_client, SD_DHCP_OPTION_DOMAIN_SEARCH_LIST);
+                if (r < 0)
+                        return log_link_error_errno(link, r, "DHCP4 CLIENT: Failed to set request flag for domain search list: %m");
+        }
+
```
Comment (ssahani) [inline src/network/networkd-dhcp4.c:1049]: LGTM

Comment (yuwata) [reply src/network/networkd-dhcp4.c:1049]: Thanks. Setting the green label.
