### PR TITLE
avoid race between systemd-logind and systemd-udevd in setting ACLs

### LINKED ISSUE #24026: Keyboard not available immediately in X11 / display manager after the boot on some machine
### systemd version the issue has been seen with

251

### Used distribution

Debian/unstable

### Linux kernel version used

5.17.0-2-amd64 / 5.18.0-2-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

The keyboard should be available immediately after the boot in the display manager.

### Unexpected behaviour you saw

After the boot, when I start typing my password, the first keys are not taken into account. The journalctl and Xorg logs show an unexpected delay concerning the keyboard (about systemd-logind and udev respectively), which could explain the issue, while the keyboard is visible almost immediately by the kernel (according to journalctl). See details later.

This happens with my desktop machine at my lab, but I have no such issue with my laptop.

### Steps to reproduce the problem

On the machine in question:

1. Boot (or reboot) the machine.
2. In the grub screen, select the kernel (or wait for a few seconds for the default).
3. In the display manager (I've tried with both lightdm and xdm), start typing with the keyboard: nothing happens, and after a few seconds, keys are starting to be taken into account.

Note: This issue is visible only when `systemd-udev-trigger.service` contains
```
ExecStart=-udevadm trigger --type=all --action=add --prioritized-subsystem=block,tpmrm
```
which is new in systemd 251 (I didn't have this issue with systemd 250 and before). However, without that, there is a reproducible 6-second freeze that makes the display manager start later, thus actually hiding the issue.

### Additional information

With systemd 250.4-1, journalctl shows:
```
May 24 14:12:15 cventin kernel: microcode: microcode updated early to revision 0x49, date = 2021-08-11
May 24 14:12:15 cventin kernel: Linux version 5.17.0-2-amd64 (debian-kernel@lists.debian.org) (gcc-11 (Debian 11.3.0-1) 11.3.0, GNU ld (GNU Binutils for Debian) 2.38) #1 SMP PREEMPT Debian 5.17.6-1 (2022-05-11)
[...]
May 24 14:12:16 cventin systemd[1]: Started Network Time Synchronization.
May 24 14:12:16 cventin systemd[1]: Reached target System Time Set.
May 24 14:12:22 cventin kernel: sr 2:0:0:0: Attached scsi generic sg0 type 5
May 24 14:12:22 cventin kernel: sr 3:0:0:0: Attached scsi generic sg1 type 5
May 24 14:12:22 cventin kernel: sd 6:0:0:0: Attached scsi generic sg2 type 0
[...]
May 24 14:12:23 cventin systemd[1]: Starting User Login Management...
May 24 14:12:23 cventin systemd[1]: Starting Disk Manager...
May 24 14:12:23 cventin udisksd[662]: udisks daemon version 2.9.4 starting
May 24 14:12:23 cventin systemd-logind[661]: New seat seat0.
[...]
May 24 14:12:23 cventin systemd[1]: Started User Login Management.
[...]
May 24 14:12:23 cventin systemd-logind[661]: Watching system buttons on /dev/input/event0 (Power Button)
May 24 14:12:23 cventin systemd-logind[661]: Watching system buttons on /dev/input/event1 (Power Button)
[...]
May 24 14:12:23 cventin systemd-logind[661]: Watching system buttons on /dev/input/event2 (DELL Dell USB Entry Keyboard)
[...]
May 24 14:12:27 cventin systemd[1]: Started Session c1 of User lightdm.
```
and everything was fine (but note the 6-second delay from 14:12:16 to 14:12:22, the above lines being consecutive in the logs, and I get exactly the same behavior with systemd 251 **and** the old `systemd-udev-trigger.service` file put under `/etc/systemd/system`).

With systemd 251-2, journalctl shows:
```
May 24 14:17:47 cventin kernel: microcode: microcode updated early to revision 0x49, date = 2021-08-11
May 24 14:17:47 cventin kernel: Linux version 5.17.0-2-amd64 (debian-kernel@lists.debian.org) (gcc-11 (Debian 11.3.0-1) 11.3.0, GNU ld (GNU Binutils for Debian) 2.38) #1 SMP PREEMPT Debian 5.17.6-1 (2022-05-11)
[...]
May 24 14:17:47 cventin kernel: sr 2:0:0:0: Attached scsi generic sg0 type 5
May 24 14:17:47 cventin kernel: sr 3:0:0:0: Attached scsi generic sg1 type 5
May 24 14:17:47 cventin kernel: sd 6:0:0:0: Attached scsi generic sg2 type 0
[...]
May 24 14:17:47 cventin systemd[1]: Starting Network Time Synchronization...
May 24 14:17:47 cventin systemd[1]: Starting Record System Boot/Shutdown in UTMP...
May 24 14:17:47 cventin systemd[1]: Finished Record System Boot/Shutdown in UTMP.
May 24 14:17:47 cventin systemd[1]: Started Network Time Synchronization.
May 24 14:17:47 cventin systemd[1]: Reached target System Initialization.
May 24 14:17:47 cventin systemd[1]: Started CUPS Scheduler.
May 24 14:17:47 cventin systemd[1]: Started Daily Cleanup of Temporary Directories.
May 24 14:17:47 cventin systemd[1]: Reached target Path Units.
May 24 14:17:47 cventin systemd[1]: Reached target System Time Set.
May 24 14:17:47 cventin systemd[1]: Started Trigger anacron every hour.
[...]
May 24 14:17:48 cventin systemd[1]: Starting User Login Management...
May 24 14:17:48 cventin systemd[1]: Starting Disk Manager...
May 24 14:17:48 cventin udisksd[604]: udisks daemon version 2.9.4 starting
May 24 14:17:48 cventin systemd[1]: Started D-Bus System Message Bus.
May 24 14:17:48 cventin systemd-logind[603]: New seat seat0.
[...]
May 24 14:17:48 cventin systemd[1]: Started User Login Management.
[...]
May 24 14:17:52 cventin systemd[1]: Started Session c1 of User lightdm.
[...]
May 24 14:17:57 cventin systemd-logind[603]: Watching system buttons on /dev/input/event0 (Power Button)
May 24 14:17:57 cventin systemd-logind[603]: Watching system buttons on /dev/input/event1 (Power Button)
May 24 14:17:57 cventin systemd[1]: Listening on Load/Save RF Kill Switch Status /dev/rfkill Watch.
May 24 14:17:57 cventin systemd-logind[603]: Watching system buttons on /dev/input/event2 (DELL Dell USB Entry Keyboard)
```
and this time, the "Watching system buttons" lines appear 5 seconds after "Started Session c1 of User lightdm", and I suppose that this is related to the fact that the keyboard is useless during the first few seconds.

On the Xorg side, I could also notice an important delay after the switch to systemd 251.

2 tests with systemd 250:
```
[    14.784]
X.Org X Server 1.21.1.3
[...]
[    16.597] (II) config/udev: Adding input device DELL Dell USB Entry Keyboard (/dev/input/event2)
```
and
```
[    15.005]
X.Org X Server 1.21.1.3
[...]
[    16.818] (II) config/udev: Adding input device DELL Dell USB Entry Keyboard (/dev/input/event2)
```
(i.e. less than 2 seconds, which was fine).

2 tests with systemd 251:
```
[    11.999]
X.Org X Server 1.21.1.3
[...]
[    15.909] (II) config/udev: Adding input device DELL Dell USB Entry Keyboard (/dev/input/event2)
```
and
```
[     7.688]
X.Org X Server 1.21.1.3
[    14.644] (II) config/udev: Adding input device DELL Dell USB Entry Keyboard (/dev/input/event2)
```
(i.e. that's 4 to 7 seconds, which is too much in practice, but note that Xorg started earlier, presumably because the display manager started earlier, as mentioned above).

With a test I did on June 24 with systemd 251, journalctl shows:
```
Jun 24 17:21:16 cventin kernel: microcode: microcode updated early to revision 0x49, date = 2021-08-11
Jun 24 17:21:16 cventin kernel: Linux version 5.18.0-2-amd64 (debian-kernel@lists.debian.org) (gcc-11 (Debian 11.3.0-3) 11.3.0, GNU ld (GNU Binutils for Debian) 2.38.50.20220615) #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1 (2022-06-16)
[...]
Jun 24 17:21:16 cventin kernel: usb 2-14: New USB device found, idVendor=413c, idProduct=2107, bcdDevice= 1.04
Jun 24 17:21:16 cventin kernel: usb 2-14: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Jun 24 17:21:16 cventin kernel: usb 2-14: Product: Dell USB Entry Keyboard
Jun 24 17:21:16 cventin kernel: usb 2-14: Manufacturer: DELL
Jun 24 17:21:16 cventin kernel: hid: raw HID events driver (C) Jiri Kosina
Jun 24 17:21:16 cventin kernel: usbcore: registered new interface driver usbhid
Jun 24 17:21:16 cventin kernel: usbhid: USB HID core driver
Jun 24 17:21:16 cventin kernel: input: DELL Dell USB Entry Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-14/2-14:1.0/0003:413C:2107.0001/input/input2
Jun 24 17:21:16 cventin kernel: usb 2-8.1: new low-speed USB device number 4 using xhci_hcd
Jun 24 17:21:16 cventin kernel: hid-generic 0003:413C:2107.0001: input,hidraw0: USB HID v1.11 Keyboard [DELL Dell USB Entry Keyboard] on usb-0000:00:14.0-14/input0
[...]
Jun 24 17:21:21 cventin lightdm[827]: pam_unix(lightdm-greeter:session): session opened for user lightdm(uid=118) by (uid=0)
Jun 24 17:21:21 cventin systemd[1]: Created slice User Slice of UID 118.
Jun 24 17:21:21 cventin systemd[1]: Starting User Runtime Directory /run/user/118...
Jun 24 17:21:21 cventin systemd-logind[606]: New session c1 of user lightdm.
Jun 24 17:21:21 cventin systemd[1]: Finished User Runtime Directory /run/user/118.
Jun 24 17:21:21 cventin systemd[1]: Starting User Manager for UID 118...
Jun 24 17:21:21 cventin systemd[831]: pam_unix(systemd-user:session): session opened for user lightdm(uid=118) by (uid=0)
[...]
Jun 24 17:21:21 cventin systemd-logind[606]: New session c1 of user lightdm.
[...]
Jun 24 17:21:21 cventin systemd[1]: Started Session c1 of User lightdm.
[...]
Jun 24 17:21:26 cventin systemd-logind[606]: Watching system buttons on /dev/input/event1 (Power Button)
Jun 24 17:21:26 cventin systemd-logind[606]: Watching system buttons on /dev/input/event0 (Power Button)
Jun 24 17:21:26 cventin systemd[1]: Listening on Load/Save RF Kill Switch Status /dev/rfkill Watch.
Jun 24 17:21:26 cventin systemd-logind[606]: Watching system buttons on /dev/input/event2 (DELL Dell USB Entry Keyboard)
```
(showing that the keyboard was detected by the kernel a fraction of second after the boot, but the systemd-logind lines "Watching system buttons on" appear only 10 seconds later).

I think that the real issue is related to the fact that the systemd-logind lines "Watching system buttons on" and udev's line "Adding input device DELL Dell USB Entry Keyboard" appear too late after the boot, whether I use systemd 250 or 251 (or 251 with an older `systemd-udev-trigger.service` file).

And I'm not sure about the component since the logs show a delay with both systemd-logind (in the journalctl output) and udev (in the Xorg logs).

FYI, the bug I had reported in the Debian BTS on May 24:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1011523

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for #36408.
Hopefully fixes #24026, #28512, and/or #23547.

### CODE REVIEW

**Comment by yuwata** [comment]
Follow-up for #36408.
Not sure, but may fix #24026, #28512, and/or #23547.

File: src/login/logind-seat.c [hunk 1]
```diff
@@ -239,6 +241,21 @@ int seat_set_active(Seat *s, Session *session) {
                 return 0;
         }
 
+        /* Take a lock for the seat before updating the seat state file and applying ACLs, to avoid the
+         * following race with the uaccess builtin of systemd-udevd:
+         * 1. udevd reads the old state file,
+         * 2. logind updates the state file, and apply new ACLs,
+         * 3. udevd applies ACLs based on the old state file. */
+
+        r = mkdir_safe_label("/run/systemd/seats", 0755, 0, 0, MKDIR_WARN_MODE);
```
Comment (YHNdnzj) [inline src/login/logind-seat.c]: mkdir_parents_label(s->state_file, ...)?

**Comment by wxphaha** [comment]
If access to the stat file is locked, is it possible that udev reads the old state file first, but then sets the acl after logind?

**Comment by poettering** [comment]
hmm, i wonder if it wouldn't be nicer to just drop the acl mgmt from logind and only do it in udev, and simple trigger the devices again when the session changes? seems much nicer to me as there would be a single owner for ACLs adjustments, not two which fight.

**Comment by yuwata** [comment]
> hmm, i wonder if it wouldn't be nicer to just drop the acl mgmt from logind and only do it in udev, and simple trigger the devices again when the session changes? seems much nicer to me as there would be a single owner for ACLs adjustments, not two which fight.

Hmmmm, that potentially causes infinite loop...
1. logind triggers uevent in seat_set_active(),
2. udev processes the uevent, and broadcasts the result,
3. logind receives the result, manager_dispatch_device_udev() -> manager_process_seat_device() -> seat_start() -> seat_read_active_vt() -> seat_active_vt_changed() -> seat_set_active() OUCH!

**Comment by yuwata** [comment]
Maybe, the potential loop can be avoided by using SYNTH_UUID= property in uevent. I will try later.

File: src/libsystemd/sd-device/test-device-util.c [hunk 2]
```diff
@@ -28,6 +28,15 @@ TEST(device_in_subsystem) {
...
                 ASSERT_FALSE(device_in_subsystem(dev, NULL));
 
+                ASSERT_TRUE(device_in_subsystems(dev, STRV_MAKE("net")));
+                ASSERT_TRUE(device_in_subsystems(dev, STRV_MAKE("", "net")));
+                ASSERT_TRUE(device_in_subsystems(dev, STRV_MAKE("net", "disk")));
+                ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("disk", "subsystem")));
+                ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("disk", "")));
+                ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("")));
+                ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE(NULL)));
+                ASSERT_TRUE(!device_in_subsystems(dev, NULL));
```
Comment (keszybz) [inline src/libsystemd/sd-device/test-device-util.c]: ASSERT_FALSE?

File: src/libsystemd/sd-device/test-device-util.c [hunk 3]
```diff
@@ -38,6 +47,15 @@ TEST(device_in_subsystem) {
...
         ASSERT_FALSE(device_in_subsystem(dev, NULL));
 
+        ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("net")));
+        ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("", "net")));
+        ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("net", "disk")));
+        ASSERT_TRUE(device_in_subsystems(dev, STRV_MAKE("disk", "subsystem")));
+        ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("disk", "")));
+        ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("")));
+        ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE(NULL)));
+        ASSERT_TRUE(!device_in_subsystems(dev, NULL));
```
Comment (keszybz) [inline src/libsystemd/sd-device/test-device-util.c]: Ditto?

File: src/libsystemd/sd-device/test-device-util.c [hunk 4]
```diff
@@ -46,6 +64,15 @@ TEST(device_in_subsystem) {
         ASSERT_FALSE(device_in_subsystem(dev, "subsystem"));
         ASSERT_FALSE(device_in_subsystem(dev, ""));
         ASSERT_TRUE(device_in_subsystem(dev, NULL));
+
+        ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("net")));
+        ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("", "net")));
+        ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("net", "disk")));
+        ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("disk", "subsystem")));
+        ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("disk", "")));
+        ASSERT_TRUE(!device_in_subsystems(dev, STRV_MAKE("")));
```
Comment (keszybz) [inline src/libsystemd/sd-device/test-device-util.c]: Also here?

File: src/login/logind.c [hunk 5]
```diff
@@ -145,10 +145,7 @@ static Manager* manager_free(Manager *m) {
```
Comment (keszybz) [inline src/login/logind.c]: For the commit message:
> Previously, manager_process_seat_device() was called two times when
> received a uevent for a drm or graphics device with master-of-seat tag.
> With this commit, the function is called only once even when received a
> uevent for such a device.

This is hard to grok. Maybe like this:
> Previously, manager_process_seat_device() was called twice when logind received a uevent for a drm or graphics device with a master-of-seat tag. With this commit, the function is called only once even when logind receives two uevents for such a device.

But this commit changes the approach quite a bit. Please add a high-level over of the new approach here in the commit message.

**Review by keszybz — COMMENTED** [review]
Looks all reasonable.

**Comment by yuwata** [comment]
@keszybz Thank you for the review. All comments are addressed. PTAL.

File: src/login/logind.c [hunk 6]
```diff
@@ -852,32 +805,35 @@ static int manager_connect_console(Manager *m) {
...
+            sd_device_has_current_tag(device, "power-switch") > 0)
+                (void) manager_process_button_device(m, device);
 
-        r = sd_device_monitor_attach_event(m->device_seat_monitor, m->event);
-        if (r < 0)
-                return r;
+        /* Whenever a VCSA device is removed try to reallocate our VTs, to make sure our auto VTs never go away. */
+        const char *name;
+        if (device_in_subsystem(device, "vc") &&
+            sd_device_get_sysname(device, &name) >= 0 && startswith(name, "vcsa") &&
```
Comment (poettering) [inline src/login/logind.c]: one of those days we should probably start logging about sd_device_get_sysname() failing here...

File: src/login/logind.c [hunk 7]
```diff
@@ -895,62 +851,24 @@ static int manager_connect_udev(Manager *m) {
         if (r < 0)
                 return r;
 
-        r = sd_device_monitor_attach_event(m->device_monitor, m->event);
+        r = sd_device_monitor_filter_add_match_subsystem_devtype(m->device_monitor, "pci", NULL);
         if (r < 0)
                 return r;
```
Comment (poettering) [inline src/login/logind.c]: maybe convert these four calls into a FOREACH_STRING() situation...

Comment (poettering) [reply src/login/logind.c]: mmhmm, where does the "pci" match come from?

File: src/login/logind-seat.c [hunk 8]
```diff
@@ -207,19 +209,107 @@ int seat_preallocate_vts(Seat *s) {
...
+        if (!session || session->started)
+                seat_send_changed(s, "ActiveSession");
+}
+
+int manager_process_device_triggered_by_seat(Manager *m, sd_device *dev) {
+        assert(m);
+        assert(dev);
+
+        sd_id128_t uuid;
+        if (sd_device_get_trigger_uuid(dev, &uuid) < 0)
```
Comment (poettering) [inline src/login/logind-seat.c]: maybe debug log?

File: src/login/logind-seat.c [hunk 9]
```diff
@@ -207,19 +209,107 @@ int seat_preallocate_vts(Seat *s) {
...
+                        break;
+        if (!s)
+                return 0;
+
+        free(ASSERT_PTR(set_remove(s->uevents, &uuid)));
+        seat_triggered_uevents_done(s);
+
+        const char *id;
+        if (sd_device_get_property_value(dev, "ID_SEAT", &id) < 0 || isempty(id))
+                id = "seat0";
```
Comment (poettering) [inline src/login/logind-seat.c]: maybe add a helper device_get_seat() which does all this? we have a lot of code like this after all

File: src/login/logind-seat.c [hunk 10]
```diff
@@ -207,19 +209,107 @@ int seat_preallocate_vts(Seat *s) {
...
+                if (sd_device_has_current_tag(d, "uaccess") <= 0)
+                        continue;
 
+                /* In case people mistag devices with nodes, we need to ignore this. */
+                if (sd_device_get_devname(d, NULL) < 0)
+                        continue;
+
+                const char *id;
+                if (sd_device_get_property_value(d, "ID_SEAT", &id) < 0 || isempty(id))
+                        id = "seat0";
```
Comment (poettering) [inline src/login/logind-seat.c]: device_get_seat() would be great here too

**Comment by poettering** [comment]
looks really good, just some points

File: src/login/logind.c (hunk 7 above)
Comment (yuwata) [reply src/login/logind.c]: > mmhmm, where does the "pci" match come from?

Dropped now.

File: src/login/logind-seat.c (hunk 8 above)
Comment (yuwata) [reply src/login/logind-seat.c]: now error code is propagated to the caller and logged there.

**Comment by yuwata** [comment]
@poettering Thank you for the review. All requests are addressed. PTAL.

**Comment by bluca** [comment]
Commit 'login,udev: avoid race between systemd-logind and systemd-udevd in setting ACLs' introduced a regression, and permission checks for users owning a session no longer works. Eg: in GNOME, when already logged in clicking on suspend/reboot/poweroff in the menu asks the user for authentication, while it didn't before

**Comment by bendlas** [comment]
I've recently gotten a regression on one of my machines, which I've bisected to https://github.com/systemd/systemd/commit/c960ca2be1cfd183675df581f049a0c022c1c802

- Run `startx` on a tty
- Switch to a different tty
- Switch back
  - **REGRESSION** screen stays blank
- When trying to to switch to another tty again, chvt blocks until the startx process is killed

This only happens on one of my machines (AMD EPYC 7642, Supermicro H12SSL-i, Radeon RX 6700XT), not on any of my other AMD machines; on various 6.17 kernels.

I'd be happy to help with tracing this, if somebody tells me what to look at. For now, I'll keep using v257
