### PR TITLE
change trigger timeout defaults

### LINKED ISSUE #3167: regression: don't start services every few ms if condition fails
Again https://github.com/systemd/systemd/issues/2467

```
# cat <<EOF > /etc/systemd/system/test.socket
[Socket]
ListenStream=/run/test.ctl
EOF
# cat <<EOF > /etc/systemd/system/test.service
[Unit]
Requires=test.socket
ConditionPathExistsGlob=/tmp/nonexistent

[Service]
ExecStart=/bin/true
EOF
# systemctl daemon-reload

# systemctl start test.socket

# echo a | nc -U /run/test.ctl & # hangs

# journalctl -f -u test
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Trying to enqueue job test.service/start/replace
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Installed new job test.service/start as 192
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Enqueued job test.service/start as 192
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: ConditionPathExistsGlob=/tmp/nonexistent failed.
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Starting requested but condition failed. Not starting unit.
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Job test.service/start finished, result=done
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Trying to enqueue job test.service/start/replace
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Installed new job test.service/start as 244
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Enqueued job test.service/start as 244
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: ConditionPathExistsGlob=/tmp/nonexistent failed.
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Starting requested but condition failed. Not starting unit.
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Job test.service/start finished, result=done
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Trying to enqueue job test.service/start/replace
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Installed new job test.service/start as 296
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Enqueued job test.service/start as 296
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: ConditionPathExistsGlob=/tmp/nonexistent failed.
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Starting requested but condition failed. Not starting unit.
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Job test.service/start finished, result=done
May 01 20:50:07 systemd-testsuite systemd[1]: test.service: Trying to enqueue job test.service/start/replace
...
and so on
```

This regression was introduced by 7629ec4642b03517742

```
TEST RUN: https://github.com/systemd/systemd/issues/2467 [FAILED]
Makefile:10: recipe for target 'run' failed
make: *** [run] Error 1
7629ec4642b03517742d09b7303c204fddf82108 is the first bad commit
commit 7629ec4642b03517742d09b7303c204fddf82108
```

~~The test is coming soon.~~ See https://github.com/systemd/systemd/pull/3168

### PR DESCRIPTION
**Pull request by poettering**
Fixes #3167

### CODE REVIEW

File: src/core/socket.c [hunk 1]
```diff
@@ -100,6 +100,9 @@ static void socket_init(Unit *u) {
 
         s->control_command_id = _SOCKET_EXEC_COMMAND_INVALID;
 
+        s->trigger_limit.interval = USEC_INFINITY;
+        s->trigger_limit.burst = (unsigned) -1;
+
         RATELIMIT_INIT(s->trigger_limit, 5*USEC_PER_SEC, 2500);
```
Comment (evverx) [inline src/core/socket.c]: shouldn't we remove this?

```
bash-4.3# systemctl cat --no-pager test.socket
# /etc/systemd/system/test.socket
[Socket]
TriggerLimitIntervalSec=2s
TriggerLimitBurst=20
ListenStream=/run/test.ctl

bash-4.3# systemctl show test.socket | grep -i trigger
TriggerLimitIntervalSec=2000000
TriggerLimitBurst=20
Triggers=test.service

bash-4.3# systemctl start test.socket
bash-4.3# time echo a | nc -U /run/test.ctl

real    0m0.300s
user    0m0.012s
sys 0m0.040s
```

But

```
bash-4.3# systemctl cat --no-pager test.socket
# /etc/systemd/system/test.socket
[Socket]
ListenStream=/run/test.ctl

bash-4.3# systemctl show --no-pager test.socket | grep -i trigger
TriggerLimitIntervalSec=5000000
TriggerLimitBurst=2500
Triggers=test.service

bash-4.3# systemctl start test.socket
bash-4.3# time echo a | nc -U /run/test.ctl
...HANGS...
```

File: man/systemd.socket.xml [hunk 2]
```diff
@@ -814,13 +814,14 @@
...
         <citerefentry><refentrytitle>systemd.time</refentrytitle><manvolnum>7</manvolnum></citerefentry> for details on
-        the various time units available). The <varname>TriggerLimitBurst=</varname> setting takes an integer value and
-        specifies the numer of permitted activations per time interval, and defaults to 2500 (thus by default
-        permitting 2500 activations per 5s). Set either to 0 to disable any form of trigger rate limiting. If the limit
-        is hit, the socket unit is placed into a failure mode, and will not be connectible anymore until
-        restarted. Note that this limit is enforced before the service activation is enqueued.</para></listitem>
+        the various time units understood). The <varname>TriggerLimitBurst=</varname> setting takes a positive integer
+        value and specifies the number of permitted activations per time interval, and defaults to 200 for
+        <varname>Accept=yes</varname> sockets (thus by default permitting 200 activations per 2s), and 20 otherwise (20
+        activations per 2s). Set either to 0 to disable any form of trigger rate limiting. If the limit is hit, the
```
Comment (evverx) [inline man/systemd.socket.xml:822]: BTW

> Set either to 0 to disable any form of trigger rate limiting

What about `TriggerLimitIntervalSec=infinity` and `TriggerLimitBurst=infinity`?
I didn't check `TriggerLimitBurst=infinity` but `TriggerLimitIntervalSec=infinity` doesn't work.

https://github.com/systemd/systemd/blob/master/NEWS#L203

```
        * Most configurable timeouts in systemd now expect an argument of
          "infinity" to turn them off, instead of "0" as before. The semantics
          from now on is that a timeout of "0" means "now", and "infinity"
          means "never". To maintain backwards compatibility, "0" continues to
          turn off previously existing timeout settings.
```

File: src/core/socket.c (hunk 1 above)
Comment (poettering) [inline src/core/socket.c]: yuck! indeed! if fucked up the final commit of this stuff!

File: man/systemd.socket.xml (hunk 2 above)
Comment (poettering) [inline man/systemd.socket.xml:822]: yes, i though about this too, and this is indeed something we should do, but that's really a separate PR I think.

I'll add cleaning that up to the TODO list.

**Comment by poettering** [comment]
force pushed an updated version, with that RATELIMIT_RESET issue fixed.

File: src/core/socket.c [hunk 3]
```diff
@@ -328,6 +329,23 @@ static int socket_add_extras(Socket *s) {
 
         assert(s);
 
+        if (s->trigger_limit.interval == USEC_INFINITY && s->trigger_limit.burst == (unsigned) -1) {
```
Comment (evverx) [inline src/core/socket.c]: Shouldn't we add an `else`-branch?

``` sh
bash-4.3# systemctl cat --no-pager test.socket
# /etc/systemd/system/test.socket
[Socket]
TriggerLimitIntervalSec=5s
ListenStream=/run/test.ctl

bash-4.3# systemctl show test.socket | grep -i trigger
TriggerLimitIntervalSec=5000000
TriggerLimitBurst=4294967295 # I think should be 20
Triggers=test.service
```

Comment (poettering) [inline src/core/socket.c]: ah yuck, you are right... dang!

**Comment by poettering** [comment]
force pushed a new version now, please have a look!

(and thanks a ton for the thorough reviews! very much appreciated!)

**Comment by evverx** [comment]
LFAD :)
