### PR TITLE
 journal-gatewayd: fix handling of num_skip pointing beyond the last entry

### LINKED ISSUE #37954: journal-gatewayd always returns last entry even when it should be skipped
### systemd version the issue has been seen with

257.x

### Used distribution

Arch

### Linux kernel version used

6.15.2-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-journal-gatewayd

### Expected behaviour you didn't see

When the [`Range` header](https://www.freedesktop.org/software/systemd/man/latest/systemd-journal-gatewayd.service.html#Range%20header) is used with positive `num_skip`, it should only return records if we skip within the existing records in the journal. I.e. when we point to the last entry using the `cursor` and `num_skip` is greater than zero, the last record should not be returned.

This is particularly useful when we interrupt streaming of the logs with the `follow` flag and want to start returning new entries from the last known cursor later.

### Unexpected behaviour you saw

With positive `num_skip`, the very last record in the journal is returned even when the `cursor` points to the last record itself. E.g. if we use `__CURSOR` of the last record, `num_skip >=1` still returns the last record. Same happens if we use `__CURSOR` of older records and use `num_skip` larger than the number of records in the journal - the very last entry is always returned.

### Steps to reproduce the problem

On a system with journal that is not too busy (e.g. `mkosi vm` with debug logging disabled), the following command sequence shows the problem clearly:

```shell
# define a helper for reading the logs
getentries () { curl -s -H"Range: entries=$1:$2:$3" -H "Accept: application/json" http://localhost:19531/entries | jq -r '.__CURSOR'; }

# get last two entries of the journal
readarray -t CURSORS < <(journalctl -ojson -n2 | jq -r '.__CURSOR')
printf "%s\n" ${CURSORS[@]}
# output:
# s=7ede8bfffca84693b20262213615b346;i=2c23;b=f6249fd12dc54965ac70e9a2c478daf1;m=299aa2ad0;t=63853ee660988;x=394044360d690e41
# s=7ede8bfffca84693b20262213615b346;i=2c24;b=f6249fd12dc54965ac70e9a2c478daf1;m=299aa2b07;t=63853ee6609c0;x=d780a132ee0e0eb8

# point to last entry without skipping - 1 line should be returned
getentries "${CURSORS[1]}" 0 10
# output:
# s=7ede8bfffca84693b20262213615b346;i=2c24;b=f6249fd12dc54965ac70e9a2c478daf1;m=299aa2b07;t=63853ee6609c0;x=d780a132ee0e0eb8

# point to previous to last entry and skip 1, 1 line should be returned
getentries "${CURSORS[0]}" 1 10
# output:
# s=7ede8bfffca84693b20262213615b346;i=2c24;b=f6249fd12dc54965ac70e9a2c478daf1;m=299aa2b07;t=63853ee6609c0;x=d780a132ee0e0eb8

# point to last entry and skip 1, 0 lines should be returned
getentries "${CURSORS[1]}" 1 10
# output:
# s=7ede8bfffca84693b20262213615b346;i=2c24;b=f6249fd12dc54965ac70e9a2c478daf1;m=299aa2b07;t=63853ee6609c0;x=d780a132ee0e0eb8

# point to previous to last entry and skip 2, 0 lines should be returned
getentries "${CURSORS[0]}" 2 10
# output:
# s=7ede8bfffca84693b20262213615b346;i=2c24;b=f6249fd12dc54965ac70e9a2c478daf1;m=299aa2b07;t=63853ee6609c0;x=d780a132ee0e0eb8

# sanity check - check that the last two lines are still the same
journalctl -ojson -n2 | jq -r '.__CURSOR'
# output:
# s=7ede8bfffca84693b20262213615b346;i=2c23;b=f6249fd12dc54965ac70e9a2c478daf1;m=299aa2ad0;t=63853ee660988;x=394044360d690e41
# s=7ede8bfffca84693b20262213615b346;i=2c24;b=f6249fd12dc54965ac70e9a2c478daf1;m=299aa2b07;t=63853ee6609c0;x=d780a132ee0e0eb8
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by sairon**
When `num_skip` is supplied to the `Range` header, journal-gatewayd always returns the very last record even though it should have been skipped. This is because the `sd_journal_next_skip` always returns non-zero value on the first call, leading to one iteration of the `request_reader_entries` returning the last record.

To avoid this unexpected behavior, check that the number of lines we have skipped by is not lower than the requested skip value. If it is, then it means all entries should have been skipped without formatting the last one to the output. Break from the function with n_skip reset, or directly close the stream if follow flag is not set.

Fixes #37954

### CODE REVIEW

File: src/journal-remote/journal-gatewayd.c [hunk 1]
```diff
@@ -182,9 +182,20 @@ static ssize_t request_reader_entries(
...
-                else
+                        if (r < 0) {
+                                log_error_errno(r, "Failed to skip journal entries: %m");
+                                return MHD_CONTENT_READER_END_WITH_ERROR;
+                        }
+                        /* We skipped beyond the end, no entries should be returned here. */
+                        if (r < m->n_skip + 1) {
+                                m->n_skip = 0;
+                                if (m->follow)
+                                        return 0;
```
Comment (yuwata) [inline src/journal-remote/journal-gatewayd.c]: Maybe better to decrease `m->n_skip` with `r`, rather than setting 0, at least when `m->follow` is enabled?

Comment (sairon) [reply src/journal-remote/journal-gatewayd.c]: Good point, the original implementation can be somewhat racy and the adjustment makes the output idempotent over time as well. Adjusting the reproduction steps shown in #37954, with the request set to follow, it behaves like this now:
```bash
readarray -t CURSORS < <(journalctl -ojson -n2 | jq -r '.__CURSOR')
getentries "${CURSORS[1]}" 2 10
# nothing is output at first
# after running `systemd-cat date` three times:
# Jun 24 21:55:24 archlinux unknown[11700]: Tue Jun 24 21:55:24 CEST 2025
# Jun 24 21:55:27 archlinux unknown[11710]: Tue Jun 24 21:55:27 CEST 2025
# ^C
# on another call:
getentries "${CURSORS[1]}" 2 10
# output:
# Jun 24 21:55:24 archlinux unknown[11700]: Tue Jun 24 21:55:24 CEST 2025
# Jun 24 21:55:27 archlinux unknown[11710]: Tue Jun 24 21:55:27 CEST 2025
```

**Review by yuwata — APPROVED** [review]

**Comment by yuwata** [comment]
Is it possible to add your reproducer or something similar to TEST-04-JOURNAL ?

File: src/journal-remote/journal-gatewayd.c [hunk 2]
```diff
@@ -182,9 +182,22 @@ static ssize_t request_reader_entries(
...
+                else if (m->n_skip > 0) {
                         r = sd_journal_next_skip(m->journal, (uint64_t) m->n_skip + 1);
-                else
+                        if (r < 0) {
+                                log_error_errno(r, "Failed to skip journal entries: %m");
+                                return MHD_CONTENT_READER_END_WITH_ERROR;
+                        }
+                        /* We skipped beyond the end, make sure entries
+                         * between the cursor and n_skip offset from it
+                         * are not returned. */
```
Comment (yuwata) [inline src/journal-remote/journal-gatewayd.c]: Not a matter, but we allow ~109ch per line. So, it is not necessary to break lines so frequently.

**Comment by sairon** [comment]
Okay, fixed the formatting and added a test that covers at least the reported bug.
