### PR TITLE
sd-dhcp6-client: Implement FQDN Option

### LINKED ISSUE #4682: DHCPv6 option 39 Client FQDN not sent
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> ArchLinux ARM

### In case of bug report: Expected behaviour you didn't see

> A DHCPv6 request should contain option 39 Client FQDN

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> I have a DHCPv6 server and the Router advertisements have both the O and M flag set.
systemd-networkd correctly requests an IPv6 address from the server (and successfully receives one).
The eth0.network file contains DHCP=yes and IPv6AcceptRA=yes (but this seems irrelevant since DHCPv6 is obviously working and according to https://www.freedesktop.org/software/systemd/man/systemd.network.html I can't find something that would be explicitly needed to send the FQDN)

DHCPv6 Request from my Linux machine:
image

DHCPv6 Request from (for example) a Windows client:
image

### PR DESCRIPTION
**Pull request by agners**
Implement DHCPv6 option to exchange information about the Fully
Qualified Domain Name (FQDN) according to RFC 4704.

The RFC 4704 describes two models of operations in section 3,
currently only the second model is supported (DHCPv6 server
updates both the AAAA and the PTR RRs).

The existing DHCP Section Options SendHostname and Hostname are
sent as FQDN to the server. According to section 4.2 sending
only parts of its FQDN is allowed.

Fixes #4682.

### CODE REVIEW

File: src/libsystemd-network/sd-dhcp6-client.c [hunk 1]
```diff
@@ -59,6 +61,7 @@ struct sd_dhcp6_client {
         be16_t *req_opts;
         size_t req_opts_allocated;
         size_t req_opts_len;
+        char *fqdn;
```
Comment (poettering) [inline src/libsystemd-network/sd-dhcp6-client.c:64]: afaics this is leaked right now when sd_dhcp6_client is leaked

File: src/libsystemd-network/sd-dhcp6-client.c [hunk 2]
```diff
@@ -231,6 +234,20 @@ int sd_dhcp6_client_set_iaid(sd_dhcp6_client *client, uint32_t iaid) {
...
 
+int sd_dhcp6_client_set_fqdn(
+                sd_dhcp6_client *client,
+                const char *fqdn) {
+
+        assert_return(client, -EINVAL);
+
+        /* Refuse hostnames that neither qualify as DNS nor as Linux hostnames */
+        if (fqdn &&
+            !(hostname_is_valid(fqdn, false) && dns_name_is_valid(fqdn) > 0))
```
Comment (poettering) [inline src/libsystemd-network/sd-dhcp6-client.c]: you check here that the name must be valid as both linux and DNS hostname. That doesn't match what the comment says, and also isn't really what we want here, is it? (the comment appears right, but the code doesn't)

File: src/libsystemd-network/sd-dhcp6-client.c (hunk 1 above)
Comment (agners) [reply src/libsystemd-network/sd-dhcp6-client.c:64]: Agreed, this needs freeing.

File: src/libsystemd-network/sd-dhcp6-client.c (hunk 2 above)
Comment (agners) [reply src/libsystemd-network/sd-dhcp6-client.c]: According to discussion #7308. I agree that we should be using "or" here. If anything then dns_name_is_valid does not behave as expected.

File: src/libsystemd-network/dhcp6-option.c [hunk 3]
```diff
@@ -136,6 +136,22 @@ int dhcp6_option_append_ia(uint8_t **buf, size_t *buflen, DHCP6IA *ia) {
...
 
+int dhcp6_option_append_fqdn(uint8_t **buf, size_t *buflen, const char *fqdn) {
+        uint8_t buffer[1 + DNS_WIRE_FOMAT_HOSTNAME_MAX];
+        int r;
+
+        assert_return(buf && *buf && buflen && fqdn, -EINVAL);
+
+        buffer[0] = DHCP6_FQDN_FLAG_S; /* Request server to perform AAAA RR DNS updates */
+
+        r = dns_name_to_wire_format(fqdn, buffer + 1, sizeof(buffer) - 1,  false);
```
Comment (agners) [inline src/libsystemd-network/dhcp6-option.c]: RFC 4704 requires a terminating zero-length label only if it is a FQDN. Will use the check used in DHCPv4 client where we distinguish between hostname/fqdn using dns_name_is_single_label.

**Comment by agners** [comment]
Addressed the review and force-pushed into the same branch.

**Comment by poettering** [comment]
patch looks good, but given my recent change of mind on #7308, could you rework this PR too, to use the same check as you original proposed? Sorry for the forth and back

**Comment by agners** [comment]
Updated and force pushed as well.
