### PR TITLE
sysctl: bump pid range only on 64-bit systems

### LINKED ISSUE #12604: arm 32bit: Couldn't write '4194304' to 'kernel/pid_max': Invalid argument
**systemd version the issue has been seen with**
master @e7b621e

**Used distribution**
own OS, rpi3, 32bit armhf

**Expected behaviour you didn't see**
systemd-sysctl.service starts without errors

**Unexpected behaviour you saw**
```
 May 18 04:57:03 rpi3 systemd-sysctl[226]: Couldn't write '4194304' to 'kernel/pid_max': Invalid argument
May 18 04:57:03 rpi3 systemd[1]: systemd-sysctl.service: Main process exited, code=exited, status=1/FAILURE
May 18 04:57:03 rpi3 systemd[1]: systemd-sysctl.service: Failed with result 'exit-code'.
```

**Steps to reproduce the problem**
Boot a 32bit os with systemd

**Possible cause**
For 32bit systems pid_max maximum value is 32768,
from man 5 proc
```
 On 32-bit platforms, 32768 is the maximum value for pid_max.
```
The target OS "bitness" should be considered when generating /usr/lib/sysctl.d/50-default.conf

### PR DESCRIPTION
**Pull request by yuwata**
Closes #12604.

### CODE REVIEW

File: sysctl.d/meson.build [hunk 1]
```diff
@@ -6,6 +6,19 @@ install_data(
...
+cpu_arch = target_machine.cpu_family()
+
+if (cpu_arch == 'aarch64' or
+    cpu_arch == 'mips64' or
+    cpu_arch == 'parisc' or
+    cpu_arch == 'ppc64' or
+    cpu_arch == 'riscv64' or
+    cpu_arch == 's390x' or
+    cpu_arch == 'sparc64' or
+    cpu_arch == 'x86_64')
```
Comment (keszybz) [inline sysctl.d/meson.build]: The kernel checks the size of long:
```
#define PID_MAX_LIMIT (CONFIG_BASE_SMALL ? PAGE_SIZE * 8 : \
        (sizeof(long) > 4 ? 4 * 1024 * 1024 : PID_MAX_DEFAULT))
```
Maybe we should do the same, to avoid having the list of arches:
```
if cc.sizeof('long') > 4:
        install_data('50-pid-max.conf', install_dir : sysctldir)
endif
```
?

**Comment by yuwata** [comment]
@keszybz Thank you for the comment. Updated. PTAL.

**Comment by poettering** [comment]
i hope that's not going to confuse stuff on multiarch...
