### PR TITLE
bootctl: override is_efi_boot() check by --variables= option

### LINKED ISSUE #40392: bootctl fails in a container despite --variables=yes flag
### systemd version the issue has been seen with

259

### Used distribution

Debian Forky

### Linux kernel version used

6.17.13

### CPU architectures issue was seen on

ia64

### Component

bootctl

### Expected behaviour you didn't see

Bootctl should be able to complete its install task even in container if --variables=yes argument is given, i.e. "bootctl --variables=yes install"

### Unexpected behaviour you saw

bootctl fails with the following message:

```
root@target:~# bootctl --variables=yes install
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed" to "/boot/efi/EFI/systemd/systemd-bootx64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed" to "/boot/efi/EFI/BOOT/BOOTX64.EFI".
Random seed file /boot/efi/loader/random-seed successfully refreshed (32 bytes).
Failed to determine current boot order: Operation not supported
```

### Steps to reproduce the problem

run bootctl in a container such as systemd-nspawn with /sys/firmware/efi/efivars mounted, i.e. 

```
systemd.nspawn ... \
--bind=/sys/firmware/efi/efivars \
...
```

the bug is in the function

`int efi_get_boot_options(uint16_t **ret_options) {
`

line 487 (current) in efi-api.c

```
        if (!is_efi_boot())
                return -EOPNOTSUPP;

```

This test is not needed; if the execution gets there it's either because the computer is booted in EFI mode or --variables=yes flag is present. Prudently, a flag test can be added

```
if (!is_efi_boot() && !touch_variables())
        return -EOPNOTSUPP;

```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #40392.

### CODE REVIEW

File: src/basic/efivars.c [hunk 1]
```diff
@@ -319,20 +319,26 @@ int efi_set_variable_string(const char *variable, const char *value) {
         return efi_set_variable(variable, u16, (char16_strlen(u16) + 1) * sizeof(char16_t));
 }
 
+static int cache_efi_boot = -1;
+
+bool set_efi_boot(bool b) {
+        return (cache_efi_boot = b);
```
Comment (YHNdnzj) [inline src/basic/efivars.c:325]: Hmm, I'd prefer if we never override the efivars check, but only the auxiliary ones.

Comment (yuwata) [reply src/basic/efivars.c:325]: I initially tried that. But the check is used so many places in many binaries...
I prefer the current implementation.

**Comment by poettering** [comment]
Uh, is this really desirable? `--variables=` mostly exists so that one can set it to "no". I am not convinced that setting it to "yes" should override the container detection logic...

i mean inside of a container we typically cannot access efivarfs anyway, so this seems like half-thought out.

it might make sense to add an env var SYSTEMD_OVERRIDE_EFI= or so that overrides the efi check, but i am really not convinced this should be officially supported semantics through primary options...

**Comment by poettering** [comment]
so here's what i#d propose:

1. add an env var override for the efi check, and document it in ENVIRONMENT.md as usual
2. document for --variables= that it cannot be used to override the efi check
3. if --variable=yes is specified and the efi check fails, write a warning (and don't try to change variables)

**Comment by yuwata** [comment]
But, we have already partially support `--variables=yes`, e.g. `set-default` or `set-oneshot`.

I do not think it is better to introduce two ways `--variables=` and `$SYSTEMD_OVERRIDE_EFI` for overriding the default behavior. Both takes boolean, but `--variables=` only takes `no`. Ugly.

Even `--variables=yes` is specified, it only works when the efivarfs is explicitly mounted on the container. So, the user already takes one extra step to make it work. I do not think we should request another step to override the default behavior.

**Review by keszybz — APPROVED** [review]
LGTM.

I agree with @yuwata, that trying to split the interface into a switch + a variable would make everything complicated for very little gain.
