### PR TITLE
coredump: use unaligned_read_ne{32,64}() to parse auxv

### LINKED ISSUE #26912: Coredump undefined behavior sanitizer error in CentOS CI
### systemd version the issue has been seen with

main

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

x86_64

### Component

_No response_

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

Found in #26889 

Likely introduced in https://github.com/systemd/systemd/commit/3e4d0f6cf99f8677edd6a237382a65bfe758de03

```sh
[    8.862488] systemd[1]: Started systemd-coredump@0-458-0.service.
[    9.230698] systemd-coredump[460]: ../build/src/coredump/coredump.c:357:25: runtime error: load of misaligned address 0x613000000213 for type 'const uint64_t' (aka 'const unsigned long'), which requires 8 byte alignment
[    9.230698] systemd-coredump[460]: 0x613000000213: note: pointer points here
[    9.230698] systemd-coredump[460]:  55  58 56 3d 21 00 00 00 00  00 00 00 00 d0 fd 06 fc  7f 00 00 33 00 00 00 00  00 00 00 30 0e 00 00
[    9.230698] systemd-coredump[460]:               ^
[    9.631462] systemd-coredump[460]:     #0 0x5579365dff41 in parse_auxv64 /systemd-meson-build/../build/src/coredump/coredump.c:357:25
[    9.631462] systemd-coredump[460]:     #1 0x5579365dbb71 in grant_user_access /systemd-meson-build/../build/src/coredump/coredump.c:463:21
[    9.631462] systemd-coredump[460]:     #2 0x5579365dbb71 in save_external_coredump /systemd-meson-build/../build/src/coredump/coredump.c:607:27
[    9.631462] systemd-coredump[460]:     #3 0x5579365dbb71 in submit_coredump /systemd-meson-build/../build/src/coredump/coredump.c:944:13
[    9.631462] systemd-coredump[460]:     #4 0x5579365d37c7 in process_socket /systemd-meson-build/../build/src/coredump/coredump.c:1220:13
[    9.631462] systemd-coredump[460]:     #5 0x5579365d37c7 in run /systemd-meson-build/../build/src/coredump/coredump.c:1608:24
[    9.631462] systemd-coredump[460]:     #6 0x5579365d37c7 in main /systemd-meson-build/../build/src/coredump/coredump.c:1614:1
[    9.631462] systemd-coredump[460]:     #7 0x7f6222a3c78f  (/usr/lib/libc.so.6+0x2378f) (BuildId: 4a4bec3d95a1804443e852958fe59ed461135ce9)
[    9.631462] systemd-coredump[460]:     #8 0x7f6222a3c849 in __libc_start_main (/usr/lib/libc.so.6+0x23849) (BuildId: 4a4bec3d95a1804443e852958fe59ed461135ce9)
[    9.631462] systemd-coredump[460]:     #9 0x5579365d0af4 in _start (/usr/lib/systemd/systemd-coredump+0xeaf4) (BuildId: 43edc2d363eff09e4c80560275258651d00ac5a2)
[    9.631462] systemd-coredump[460]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/coredump/coredump.c:357:25 in
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug introduced by 3e4d0f6cf99f8677edd6a237382a65bfe758de03.
Fixes #26912.

### CODE REVIEW

File: src/coredump/coredump.c [hunk 1]
```diff
@@ -353,28 +354,34 @@ static int parse_auxv64(
 
         /* Note that we set output variables even on error. */
 
-        for (size_t i = 0; i + 1 < words; i += 2)
-                switch (auxv[i]) {
+        for (size_t i = 0; i + 1 < words; i += 2) {
```
Comment (poettering) [inline src/coredump/coredump.c]: Hmm, so by C alignment rules the auxv[] parameter isn't even allowed to be passed in here if not aligned correctly by its type. the compiler is otherwise allowed to make assumptions it shouldn't make here.

Hence, the prototype of parse_auxv64() should change to take a `const void*` rather than a `const uint64_t*` pointer, and we should never ever cast that that `const uint64_t*` if the memory is not aligned.

Comment (yuwata) [reply src/coredump/coredump.c]: Addressed. PTAL.

**Comment by keszybz** [comment]
The change looks good, but the commit message needs to explain what the issue that is being fixes is, and why we didn't see it so far.

**Review by keszybz — APPROVED** [review]

**Comment by yuwata** [comment]
@keszybz The commit message is extended. PTAL.

**Comment by keszybz** [comment]
Perfect! Thanks!

**Comment by keszybz** [comment]
The CI passed previously, so let's merge this, since the commit message shouldn't influence the result. (I know, with CI one can never be sure, but let's be optimistic ;) )
