### PR TITLE
network: do not reconfigure interface when the link gains carrier but udev not initialized it yet

### LINKED ISSUE #17929: systemd-networkd fails to set up link, "Assertion 'lldp->fd < 0' failed"
**systemd version the issue has been seen with**
 > 247

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > 5.9.12

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > `systemd-networkd` successfully configures WiFi link, obtaining an IPv4 address via DHCP and connects to the Internet.

**Unexpected behaviour you saw**
 > `systemd-networkd` fails to set up this interface. `networkctl status wlan0` shows (with `debug` in the kernel command-line):

```
● 3: wlan0
                     Link File: /usr/lib/systemd/network/80-iwd.link
                  Network File: /etc/systemd/network/50-wifi.network
                          Type: wlan
                         State: carrier (failed)
                          Path: pci-0000:02:00.0
                        Driver: iwlwifi
                        Vendor: Intel Corporation
                         Model: Dual Band Wireless-AC 3165 Plus Bluetooth (Dual Band Wireless-AC 3165)
                    HW Address: e4:70:b8:e7:fb:3f (Intel Corporate)
                           MTU: 1500 (min: 256, max: 2304)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
             WiFi access point: hypertubes (7c:39:53:d0:55:07)
          Queue Length (Tx/Rx): 1/1
                       Address: fe80::e670:b8ff:fee7:fb3f
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab1144fd3347cd965d050000

Dec 10 13:13:26 keeper systemd-networkd[482]: wlan0: Setting address genmode for link
Dec 10 13:13:26 keeper systemd-networkd[482]: wlan0: Failed to read sysctl property stable_secret: Input/output error
Dec 10 13:13:26 keeper systemd-networkd[482]: wlan0: link_check_ready(): link is in initialized state.
Dec 10 13:13:26 keeper systemd-networkd[482]: wlan0: Link state is up-to-date
Dec 10 13:13:26 keeper systemd-networkd[482]: wlan0: Setting nomaster
Dec 10 13:13:26 keeper systemd-networkd[482]: wlan0: Failed
Dec 10 13:13:26 keeper systemd-networkd[482]: wlan0: State changed: initialized -> failed
Dec 10 13:13:26 keeper systemd-networkd[482]: wlan0: Started LLDP.
Dec 10 13:13:27 keeper systemd-networkd[482]: wlan0: Remembering updated address: fe80::e670:b8ff:fee7:fb3f/64 (valid forever)
Dec 10 13:13:27 keeper systemd-networkd[482]: wlan0: Remembering route: dst: fe80::e670:b8ff:fee7:fb3f/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
```

**Steps to reproduce the problem**
 > The relevant `.network` file is simply:

```
[Match]
Name=wlan0

[Network]
DHCP=yes
```

I am using `iwd` 1.9 to set up the WiFi link.

**Relevant logs**

Relevant excerpts from the journal (with `debug` in the kernel command-line):

```
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: New device has no master, continuing without
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Flags change: +UP +LOWER_UP +RUNNING +MULTICAST +BROADCAST
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Link 3 added
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: udev initialized link
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: State changed: pending -> initialized
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: New device has no master, continuing without
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Flags change: +MULTICAST +BROADCAST
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Link 2 added
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Could not find device, waiting for device initialization: No such device
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: State changed: pending -> linger
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Link removed
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Flags change: -UP -LOWER_UP -RUNNING
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Link DOWN
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Lost carrier
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Flags change: +UP +RUNNING
[...]
hu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Link UP
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Flags change: -RUNNING
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Flags change: +LOWER_UP
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Flags change: +RUNNING
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Gained carrier
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Connected WiFi access point: [SSID redacted]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: found matching network '/etc/systemd/network/50-wifi.network'
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Re-configuring with /etc/systemd/network/50-wifi.network
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Setting nomaster
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: LLDP: Started LLDP client
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Started LLDP.
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Setting address genmode for link
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Failed to read sysctl property stable_secret: Input/output error
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: link_check_ready(): link is in initialized state.
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Link state is up-to-date
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Setting nomaster
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: Assertion 'lldp->fd < 0' failed at src/libsystemd-network/sd-lldp.c:340, function sd_lldp_set_ifindex(). Ignoring.
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: Failed
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: wlan0: State changed: initialized -> failed
[...]
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: DHCP CLIENT (0x0): STOPPED
Thu 2020-12-10 12:55:50 GMT systemd-networkd.service[486]: LLDP: Stopping LLDP client
```

**Workarounds**

The issue does not occur if I add `LLDP=no` to the `.network` file.

Alternatively, `networkctl reconfigure wlan0` also fixes the issue.

### PR DESCRIPTION
**Pull request by yuwata**
When an interface gains carrier but udev have not initialized the
interface or link_initialized_handler() has not been called yet,
then link_configure will be called twice. Thus LLDP client will be
configured twice, and triggers assertion.

Fixes #17929.

### CODE REVIEW

**Comment by yuwata** [comment]
@evverx What happens to LGTM analysis?

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -2223,8 +2222,11 @@ int link_reconfigure(Link *link, bool force) {
         _cleanup_(sd_netlink_message_unrefp) sd_netlink_message *req = NULL;
         int r;
 
-        if (IN_SET(link->state, LINK_STATE_PENDING, LINK_STATE_LINGER))
-                return 0;
+        /* When link in pending or initialized state, then link_configure() will be called. To prevent
+         * the function be called multiple times simultaneously, refuse to reconfigure the interface in
+         * these case. */
```
Comment (c4rlo) [inline src/network/networkd-link.c]:
```suggestion
        /* When link in pending or initialized state, then link_configure() will be called. To prevent
         * the function from being called multiple times simultaneously, refuse to reconfigure the
         * interface in these cases. */
```

File: src/network/networkd-link.c [hunk 2]
```diff
@@ -2223,8 +2222,11 @@ int link_reconfigure(Link *link, bool force) {
...
+        if (IN_SET(link->state, LINK_STATE_PENDING, LINK_STATE_INITIALIZED, LINK_STATE_LINGER))
+                return 0; /* o means no-op. */
```
Comment (c4rlo) [inline src/network/networkd-link.c]:
```suggestion
                return 0; /* 0 means no-op. */
```
