### PR TITLE
nspawn: don't hard fail when setting capabilities

### LINKED ISSUE #12539: systemd-nspawn unnecessarily setting capabilities that are not in the original set
https://github.com/systemd/systemd/commit/de40a3037af944f6803375f2f5269cffc4247f56 swapped `drop_capabilities()` in nspawn/nspawn.c to call `capability_quintet_enforce` instead of `capability_bounding_set_drop`. If no capability related args are passed to nspawn and the current capability set is missing one of the capabilities in nspawn's default set of `arg_caps_retain`, then nspawn will attempt to set it. However this fails and nspawn will not start. For example, in a container started without `cap_sys_boot` (which is in `arg_caps_retain`):

```
[root@image /]# capsh --print
Current: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_raw,cap_ipc_owner,cap_sys_chroot,cap_sys_ptrace,cap_sys_admin,cap_sys_nice,cap_sys_resource,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap+ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_raw,cap_ipc_owner,cap_sys_chroot,cap_sys_ptrace,cap_sys_admin,cap_sys_nice,cap_sys_resource,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=0(root)
gid=0(root)
groups=
[root@image /]# systemd-nspawn -x -- capsh --print
Spawning container image-ce38659d1e580c26 on /.#machine.e3cf534d32fd7351.
Press ^] three times within 1s to kill container.
Dropping capabilities failed: Operation not permitted
Child died too early.

```

With `cap_sys_boot` in the container this will work fine. Considering the name of the function I believe this is a bug and we should only be dropping capabilities, not setting additional ones. Can help with patches if this is not intended behavior.

### PR DESCRIPTION
**Pull request by anitazha**
The OCI changes in #9762 broke a use case in which we use nspawn from
inside a container that has dropped capabilities from the bounding set
that nspawn expected to retain. In an attempt to keep OCI compliance
and support our use case, I made hard failing on setting capabilities
not in the bounding set optional (hard fail if using OCI and log only
if using nspawn cmdline).

Fixes #12539

### CODE REVIEW

File: src/basic/capability-util.c [hunk 1]
```diff
@@ -364,13 +364,14 @@ bool ambient_capabilities_supported(void) {
         return cache;
 }
```
Comment (poettering) [inline src/basic/capability-util.c:367]: hmm, i'd prefer if we had helper call: capability_quintet_mangle() or so, that takes a CapabilityQuintet structure and masks all bits out that are not in the current bounding set, and returns > 0 if it turned any off and == 0 if not. Then we could just call this early in nspawn, and if it returns > 0 we warn loudly (or maybe as a tweak only warn loudly if any caps where configured at all).

```c
int capability_quitntet_mangle(CapabilityQuintet *q) {
        unsigned long i;
        uint64_t combined, drop = 0;
        bool changed = false;

        assert(q);

        /* Mangles the specified caps quintet taking the current bounding set into account: drops all caps from all five sets if our bounding set doesn't allow them. */

        combined = q->effective | q->bounding | q->inheritable | q->permitted | q->ambient;

        for (i = 0; i <= cap_last_cap(); i++) {
                unsigned long bit = UINT64_C(1) << i;
                if (!FLAGS_SET(combined, bit)
                        continue;

                if (prctl(PR_CAPBSET_READ, i) > 0)
                        continue;

                drop |= bit;
        }

        q->effective &= ~drop;
        q->bounding &= ~drop;
        q->inheritable &= ~drop;
        q->permitted &= ~drop;
        q->ambient &= ~drop;

        return drop != 0; /* Let the caller know we changed something */
}
```

**Comment by anitazha** [comment]
Updated with suggestions. PTAL

File: src/nspawn/nspawn.c [hunk 2]
```diff
@@ -2317,7 +2317,11 @@ static int drop_capabilities(uid_t uid) {
 
                 if (q.ambient == (uint64_t) -1 && ambient_capabilities_supported())
                         q.ambient = 0;
-        } else
+
+                if (capability_quintet_mangle(&q))
+                        return log_error_errno(EPERM, "Cannot set capabilities that are not in the bounding set.");
```
Comment (poettering) [inline src/nspawn/nspawn.c]: needs SYNTHETIC_ERRNO() around the EPERM please.

(that macro indicates that we generate the error here, instead of receiving it)

Comment (poettering) [reply src/nspawn/nspawn.c]: "bounding set" → "current bounding set" maybe?

**Comment by anitazha** [comment]
Fixed nits~
