### PR TITLE
udev/net-id: Fix check for address to keep interface names stable

### LINKED ISSUE #8446: Upgrade to systemd 238 changed predictable interface names (e.g. from wls1 to wlp2s0) for many Arch Linux users
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 238

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> Some years later my eth0 and wlan0 interfaces got renamed to wls1 and ens5 ad I fully understood that. But now the former predictable names changed to enp133s0 and wlp2s0, making them no more predictable at all. Which one of those, the former or the current is correct then?

> But more importantly it broke many networking tools, like wifi hotspot apps, internet connections, wifi connectors between devices and other stuff completely today. Not just for me, but also for the other on Arch Linux, see https://bbs.archlinux.org/viewtopic.php?id=235307.

### In case of bug report: Steps to reproduce the problem

> Upgrade from v237 to v238 on Arch Linux..

### PR DESCRIPTION
**Pull request by filbranden**
This was a bug inadvertently added by commit 73fc96c8ac0aa9. /cc @keszybz 

The intent of the strneq is to "match slot address with device by stripping the function" (as the comment above states it), for example match network device PCI address 0000:05:00.0 (including a .0 for function) to PCI slot address 0000:05:00, but changing that to a streq() call prevented the match.

I tried to test this using `udevadm test-builtin net_id`, but I can't reproduce the problem in first place... Still, I think from the comment this must be the problem.

This bug was found by @amishxda.

Fixes #8446.

Cheers!
Filipe

### CODE REVIEW

File: src/udev/udev-builtin-net_id.c [hunk 1]
```diff
@@ -297,7 +297,7 @@ static int dev_pci_slot(struct udev_device *dev, struct netnames *names) {
                 if (snprintf_ok(str, sizeof str, "%s/%s/address", slots, dent->d_name) &&
                     read_one_line_file(str, &address) >= 0)
                         /* match slot address with device by stripping the function */
-                        if (streq(address, udev_device_get_sysname(names->pcidev)))
+                        if (strneq(address, udev_device_get_sysname(names->pcidev), strlen(address)))
```
Comment (yuwata) [inline src/udev/udev-builtin-net_id.c]: I prefer `startswith(udev_device..., address)` here. See PR #8459.

Comment (filbranden) [reply src/udev/udev-builtin-net_id.c]: Oh indeed, much nicer, thanks!

That also makes the intent of this check a lot more clear.

**Comment by filbranden** [comment]
Done and pushed the update.

What's the best way to test this code? Any idea on how to introduce a check to prevent regressions in this area in the future?

**Comment by yuwata** [comment]
@amishxda Could you test this PR by the following steps?
```
$ meson build
$ ninja -C build
$ build/udevadm test-builtin net_id /sys/devices/pci0000:00/0000:00:1c.2/0000:04:00.0/net/enp4s0
```

**Comment by amishxda** [comment]
Looks like fixed.

With default udevadm (unpatched)
```
$ udevadm test-builtin net_id /sys/devices/pci0000:00/0000:00:1c.1/0000:02:00.0/net/wlan0
calling: test-builtin
Load module index
Parsed configuration file /usr/lib/systemd/network/99-default.link
Created link configuration context.
ID_NET_NAME_MAC=wlxMASKED
ID_OUI_FROM_DATABASE=Intel Corporate
ID_NET_NAME_PATH=wlp2s0
Unload module index

```

with new build (patched) - name is back to wls1

```
$ build/udevadm test-builtin net_id /sys/devices/pci0000:00/0000:00:1c.1/0000:02:00.0/net/wlan0
calling: test-builtin
Load module index
Parsed configuration file /usr/lib/systemd/network/99-default.link
Created link configuration context.
ID_NET_NAME_MAC=wlxMASKED
ID_OUI_FROM_DATABASE=Intel Corporate
ID_NET_NAME_PATH=wlp2s0
ID_NET_NAME_SLOT=wls1
Unload module index
Unloaded link configuration context.
```

Similarly tested with eth0 too - detects correct name i.e. ens5 (instead of enp133s0)

**Comment by filbranden** [comment]
Awesome thanks for testing @amishxda !

**Comment by yuwata** [comment]
@amishxda Thanks.

Let's wait CIs.

**Comment by filbranden** [comment]
> We do not have any specific tests for net_id. Let's merge this.

Any suggestions on how we could test this to prevent regressions in the future?

**Comment by michaelolbrich** [comment]
I think [umockdev](https://github.com/martinpitt/umockdev) could be used for this. It can simulate sysfs and should provide enough to test the net_id builtin, I think. @martinpitt should know more about this.

**Comment by filbranden** [comment]
Hi @amishxda,

If you don't mind... Would you please install umockdev on your machine, run the following command and send us the output?

```
$ umockdev-record /sys/devices/pci0000:00/0000:00:1c.1/0000:02:00.0/net/wlan0
```

It looks like umockdev is available as a package on Arch Linux, so you should be able to install using pacman:
https://www.archlinux.org/packages/?q=umockdev

(I don't have a device that reproduces this issue of missing the rename... Otherwise I'd do it myself... In any case, good to cover the specific case you reported!)

Thanks!
Filipe

**Comment by amishxda** [comment]
Here is the output:

Note: I have changed MAC address to 001122334455

Also I have removed following long lines from output for readability. Let me know if they are important lines and I will post them as well.

1. H: config=some really long hex digits
2. A: resource=some long hex numbers separated by spaces and line feeds (\n)

```
P: /devices/pci0000:00/0000:00:1c.1/0000:02:00.0/net/wlan0
E: DEVTYPE=wlan
E: ID_BUS=pci
E: ID_MM_CANDIDATE=1
E: ID_MODEL_FROM_DATABASE=PRO/Wireless 5100 AGN [Shiloh] Network Connection (WiFi Link 5100 AGN)
E: ID_MODEL_ID=0x4237
E: ID_NET_DRIVER=iwlwifi
E: ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
E: ID_NET_NAME=wls1
E: ID_NET_NAME_MAC=wlx001122334455
E: ID_NET_NAME_PATH=wlp2s0
E: ID_NET_NAME_SLOT=wls1
E: ID_OUI_FROM_DATABASE=Intel Corporate
E: ID_PATH=pci-0000:02:00.0
E: ID_PATH_TAG=pci-0000_02_00_0
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Network controller
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_VENDOR_ID=0x8086
E: IFINDEX=3
E: INTERFACE=wlan0
E: SUBSYSTEM=net
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/wlan0 /sys/subsystem/net/devices/wlan0
E: TAGS=:systemd:
A: addr_assign_type=0
A: addr_len=6
A: address=00:11:22:33:44:55
A: broadcast=ff:ff:ff:ff:ff:ff
A: carrier=1
A: carrier_changes=2
A: dev_id=0x0
A: dev_port=0
L: device=../../../0000:02:00.0
A: dormant=0
A: flags=0x1003
A: gro_flush_timeout=0
A: ifalias=
A: ifindex=3
A: iflink=3
A: link_mode=1
A: mtu=1500
A: name_assign_type=4
A: netdev_group=0
A: operstate=up
L: phy80211=../../ieee80211/phy0
A: power/async=disabled
A: power/control=auto
A: power/runtime_active_kids=0
A: power/runtime_active_time=0
A: power/runtime_enabled=disabled
A: power/runtime_status=unsupported
A: power/runtime_suspended_time=0
A: power/runtime_usage=0
A: proto_down=0
A: statistics/collisions=0
A: statistics/multicast=0
A: statistics/rx_bytes=15722268
A: statistics/rx_compressed=0
A: statistics/rx_crc_errors=0
A: statistics/rx_dropped=0
A: statistics/rx_errors=0
A: statistics/rx_fifo_errors=0
A: statistics/rx_frame_errors=0
A: statistics/rx_length_errors=0
A: statistics/rx_missed_errors=0
A: statistics/rx_nohandler=0
A: statistics/rx_over_errors=0
A: statistics/rx_packets=24371
A: statistics/tx_aborted_errors=0
A: statistics/tx_bytes=3943207
A: statistics/tx_carrier_errors=0
A: statistics/tx_compressed=0
A: statistics/tx_dropped=0
A: statistics/tx_errors=0
A: statistics/tx_fifo_errors=0
A: statistics/tx_heartbeat_errors=0
A: statistics/tx_packets=22861
A: statistics/tx_window_errors=0
A: tx_queue_len=1000
A: type=1

P: /devices/pci0000:00/0000:00:1c.1/0000:02:00.0
E: DRIVER=iwlwifi
E: ID_MODEL_FROM_DATABASE=PRO/Wireless 5100 AGN [Shiloh] Network Connection (WiFi Link 5100 AGN)
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Network controller
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: MODALIAS=pci:v00008086d00004237sv00008086sd00001211bc02sc80i00
E: PCI_CLASS=28000
E: PCI_ID=8086:4237
E: PCI_SLOT_NAME=0000:02:00.0
E: PCI_SUBSYS_ID=8086:1211
E: SUBSYSTEM=pci
A: broken_parity_status=0
A: class=0x028000
A: consistent_dma_mask_bits=36
A: current_link_speed=2.5 GT/s
A: current_link_width=1
A: d3cold_allowed=1
A: device=0x4237
A: devspec=
A: dma_mask_bits=36
L: driver=../../../../bus/pci/drivers/iwlwifi
A: driver_override=(null)
A: enable=1
A: irq=30
A: local_cpulist=0-1
A: local_cpus=3
A: max_link_speed=2.5 GT/s
A: max_link_width=1
A: modalias=pci:v00008086d00004237sv00008086sd00001211bc02sc80i00
A: msi_bus=1
A: msi_irqs/30=msi
A: numa_node=-1
A: power/async=enabled
A: power/control=on
A: power/runtime_active_kids=0
A: power/runtime_active_time=4592675
A: power/runtime_enabled=forbidden
A: power/runtime_status=active
A: power/runtime_suspended_time=0
A: power/runtime_usage=2
A: power/wakeup=disabled
A: power/wakeup_abort_count=
A: power/wakeup_active=
A: power/wakeup_active_count=
A: power/wakeup_count=
A: power/wakeup_expire_count=
A: power/wakeup_last_time_ms=
A: power/wakeup_max_time_ms=
A: power/wakeup_prevent_sleep_time_ms=
A: power/wakeup_total_time_ms=
A: revision=0x00
A: subsystem_device=0x1211
A: subsystem_vendor=0x8086
A: vendor=0x8086

P: /devices/pci0000:00/0000:00:1c.1
E: DRIVER=pcieport
E: ID_MODEL_FROM_DATABASE=82801I (ICH9 Family) PCI Express Port 2
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_INTERFACE_FROM_DATABASE=Normal decode
E: ID_PCI_SUBCLASS_FROM_DATABASE=PCI bridge
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: MODALIAS=pci:v00008086d00002942sv00000000sd00000000bc06sc04i00
E: PCI_CLASS=60400
E: PCI_ID=8086:2942
E: PCI_SLOT_NAME=0000:00:1c.1
E: PCI_SUBSYS_ID=0000:0000
E: SUBSYSTEM=pci
A: broken_parity_status=0
A: class=0x060400
A: consistent_dma_mask_bits=32
A: current_link_speed=2.5 GT/s
A: current_link_width=1
A: d3cold_allowed=1
A: device=0x2942
A: devspec=
A: dma_mask_bits=32
L: driver=../../../bus/pci/drivers/pcieport
A: driver_override=(null)
A: enable=1
A: irq=25
A: local_cpulist=0-1
A: local_cpus=3
A: max_link_speed=2.5 GT/s
A: max_link_width=1
A: modalias=pci:v00008086d00002942sv00000000sd00000000bc06sc04i00
A: msi_bus=1
A: msi_irqs/25=msi
A: numa_node=-1
A: power/async=enabled
A: power/control=on
A: power/runtime_active_kids=1
A: power/runtime_active_time=4592692
A: power/runtime_enabled=forbidden
A: power/runtime_status=active
A: power/runtime_suspended_time=0
A: power/runtime_usage=2
A: power/wakeup=disabled
A: power/wakeup_abort_count=
A: power/wakeup_active=
A: power/wakeup_active_count=
A: power/wakeup_count=
A: power/wakeup_expire_count=
A: power/wakeup_last_time_ms=
A: power/wakeup_max_time_ms=
A: power/wakeup_prevent_sleep_time_ms=
A: power/wakeup_total_time_ms=
A: revision=0x03
A: secondary_bus_number=2
A: subordinate_bus_number=2
A: subsystem_device=0x0000
A: subsystem_vendor=0x0000
A: vendor=0x8086
```

**Comment by filbranden** [comment]
Thank you @amishxda !

I've had some success reproducing this with umockdev (need umockdev 0.11+ for suport of openat) but unfortunately I don't really get `ID_NET_NAME_SLOT=wls1` as part of the output on my side... I guess I don't really know all the details of how this works...

Posting this here in case someone has a hint of what's missing:

```shell
$ umockdev-run -d umockdev-output.txt -- build/udevadm test-builtin net_id /sys/devices/pci0000:00/0000:00:1c.1/0000:02:00.0/net/wlan0 
calling: test-builtin
Parsed configuration file /lib/systemd/network/99-default.link
Created link configuration context.
ID_NET_NAME_MAC=wlx001122334455
ID_OUI_FROM_DATABASE=CIMSYS Inc
ID_NET_NAME_PATH=wlp2s0
Unloaded link configuration context.
```

I'll keep looking...

**Comment by amishxda** [comment]
When I try above command using MODIFIED as well as UNMODIFIED output. Even for me it does not give ID_NET_NAME_SLOT=wls1.

But I am using 238.51-1 package released by Arch linux yesterday (not build/udevadm).

Does 238.51 have the fix for this bug?

**Comment by filbranden** [comment]
So I'm guessing you have a `/sys/bus/pci/slots/1/address` which contains 0000:02:00 as its contents and that's what's making the match...

When I run it through umockdev-run, I see no /sys/bus/pci/slots so that's why I don't see it...

I'm still looking into umockdev to understand how it works...

Oh yes the fix is already in! I just want to craft a test case to prevent regressions of this in the future...

**Comment by amishxda** [comment]
Yep fix seems to be in.

Calling udevadm test-builtin directly shows wls1 but not via output of umockdev-record.

Strange.

$ udevadm test-builtin net_id /sys/devices/pci0000:00/0000:00:1c.1/0000:02:00.0/net/wlan0
```
calling: test-builtin
Load module index
Parsed configuration file /usr/lib/systemd/network/99-default.link
Created link configuration context.
ID_NET_NAME_MAC=wlxMASKED
ID_OUI_FROM_DATABASE=Intel Corporate
ID_NET_NAME_PATH=wlp2s0
ID_NET_NAME_SLOT=wls1
Unload module index
Unloaded link configuration context.
```

umockdev-run -d try2 -- udevadm test-builtin net_id /sys/devices/pci0000:00/0000:00:1c.1/0000:02:00.0/net/wlan0
```
calling: test-builtin
Load module index
Parsed configuration file /usr/lib/systemd/network/99-default.link
Created link configuration context.
ID_NET_NAME_MAC=wlxMASKED
ID_OUI_FROM_DATABASE=Intel Corporate
ID_NET_NAME_PATH=wlp2s0
Unload module index
Unloaded link configuration context.
```

**Comment by filbranden** [comment]
So I looked at the code and problem is with /sys/bus/pci/slots which isn't really mocked by umockdev:

```
$ umockdev-run -d umockdev-output.txt -- ls -l /sys/bus/pci/slots/
ls: cannot access '/sys/bus/pci/slots/': No such file or directory
```

That's what the code behind net_id uses to determine the slot.

I opened martinpitt/umockdev#78 asking to add support for it... Hopefully it's possible/easy to do so and we can add a test here to prevent regressions!
