### PR TITLE
Fix exittype test flakyness

### LINKED ISSUE #21480: TEST-56-EXIT-TYPE is flaky
**systemd version the issue has been seen with**
 > latest main

**Used distribution**
 > Arch Linux

After re-introducing TEST-56 (and the respective functionality) in https://github.com/systemd/systemd/pull/20813 I've noticed a couple of random fails in various PRs, which make the test a bit unstable:

```
[    9.646864] testsuite-56.sh[226]: + systemd-analyze log-level debug
[    9.656400] systemd[1]: Reached target Login Prompts.
[    9.727537] systemd-logind[224]: Watching system buttons on /dev/input/event0 (Power Button)
[    9.728113] systemd-logind[224]: Watching system buttons on /dev/input/event1 (AT Translated Set 2 keyboard)
[    9.728633] systemd-logind[224]: New seat seat0.
[    9.745663] systemd[1]: Started D-Bus System Message Bus.
[    9.769374] systemd[1]: Setting log level to debug.
[    9.771228] testsuite-56.sh[226]: + cat
[    9.787120] testsuite-56.sh[226]: + chmod +x /tmp/test56-exit-cgroup.sh
[    9.799320] testsuite-56.sh[226]: + systemd-run --wait --unit=one -p Type=notify -p ExitType=cgroup -p 'ExecStartPost=bash -c "systemctl stop one &"' /tmp/test56-exit-cgroup.sh
[    9.917018] systemd[1]: Started User Login Management.
[    9.924796] systemd[1]: Reached target Multi-User System.
[    9.933681] dbus-daemon[229]: [system] Successfully activated service 'org.freedesktop.systemd1'
[    9.942264] systemd[1]: Starting Record Runlevel Change in UTMP...
[    9.984707] test56-exit-cgroup.sh[234]: + disown
[    9.985737] test56-exit-cgroup.sh[235]: + sleep infinity
[    9.988313] test56-exit-cgroup.sh[234]: + systemd-notify --ready
[    9.996744] test56-exit-cgroup.sh[238]: + sleep infinity
[   10.013322] systemd[1]: Starting /tmp/test56-exit-cgroup.sh...
[   10.019846] systemd[1]: systemd-update-utmp-runlevel.service: Deactivated successfully.
[   10.036639] systemd[1]: Finished Record Runlevel Change in UTMP.
[   10.056952] test56-exit-cgroup.sh[234]: + sleep infinity
[   10.132911] testsuite-56.sh[232]: Job for one.service canceled.
[   10.138704] systemd[1]: testsuite-56.service: Main process exited, code=exited, status=1/FAILURE
[   10.138845] systemd[1]: testsuite-56.service: Failed with result 'exit-code'.
[   10.170346] systemd[1]: Failed to start TEST-56-EXIT-TYPE.
[   10.182877] systemd[1]: one.service: Control process exited, code=killed, status=15/TERM
[   10.183105] systemd[1]: one.service: Failed with result 'signal'.
```

Full journal: [system.journal.tar.gz](https://github.com/systemd/systemd/files/7587694/system.journal.tar.gz)

/cc @unusual-thoughts

### PR DESCRIPTION
**Pull request by unusual-thoughts**
The test was changed at @bluca's request (see https://github.com/systemd/systemd/pull/20813#pullrequestreview-788247911) to avoid sleeps, but this proved insufficient to avoid all races. There now appears to be a race between `ExecStartPost` finishing (and the service entering the `running state`) and the signal to stop/kill the service.

I can't find seem to find a way to reliably synchronize the kill signal without using a delay.

Closes #21480

### CODE REVIEW

File: test/units/testsuite-56.sh [hunk 1]
```diff
@@ -24,13 +24,13 @@ chmod +x /tmp/test56-exit-cgroup.sh
 
 # service should be stopped cleanly
 systemd-run --wait --unit=one -p Type=notify -p ExitType=cgroup \
-    -p ExecStartPost='bash -c "systemctl stop one &"' \
+    -p ExecStartPost='bash -c "(sleep 1; systemctl stop one) &"' \
```
Comment (bluca) [inline test/units/testsuite-56.sh]: What is this trying to do? Ensuring that the stop is sent only after the unit is running? But for that it doesn't need to be in ExecStartPost, the --wait can be removed and it can be done as a separate command. systemd-run will not return until --ready has been sent. Or am I missing something?

Comment (unusual-thoughts) [reply test/units/testsuite-56.sh]: no, it's ensuring that the stop is sent only after the ExecStartPost command itself (bash) is finished. Otherwise the service never reaches `running` state and ends up in ` stop-sigterm` instead, which causes the whole unit to fail because the control process never gets a chance to exit properly as far as systemd knows

Comment (bluca) [reply test/units/testsuite-56.sh]: Why is the ExecStartPost relevant here? If it wasn't, it would reach the running state after the sd_notify call, no?

Comment (unusual-thoughts) [reply test/units/testsuite-56.sh]: no, after the sd_notify call the service goes to the `start-post` status, and only reaches `running` after the `ExecStartPost` command finishes

Comment (bluca) [reply test/units/testsuite-56.sh]: And if there's no ExecStartPost?

Comment (unusual-thoughts) [reply test/units/testsuite-56.sh]: You mean run ` systemctl stop one` directly from the script itself? that should also work, but then for `four.service` and `five.service` it doesn't demonstrate that the main process actually already exited

Comment (bluca) [reply test/units/testsuite-56.sh]: It would most of the time, since the sd-notify is the last thing and then it exits (you can also add `--no-block`). There is a chance of a false positive, but that's better than a false negative, which is very time consuming

Comment (unusual-thoughts) [reply test/units/testsuite-56.sh]: Agreed. The new version is simpler and should be race free (at least for the false negative case). I added a sleep for the last two tests to make false positives even more unlikely.

**Review by bluca — APPROVED** [review]

**Comment by keszybz** [comment]
focal-amd64: TEST-37-RUNTIMEDIRECTORYPRESERVE:   FAIL     (1200 s)
focal-arm64: TEST-02-UNITTESTS:                  FAIL     (134 s)
```
=== Failed test log ===
--- test-journal-flush begin ---
journal_file_copy_entry failed: Invalid argument
Assertion 'r >= 0' failed at src/libsystemd/sd-journal/test-journal-flush.c:52, function main(). Aborting.
--- test-journal-flush end ---
```
@DaanDeMeyer is it one of the known issues?

focal-ppc64el: TEST-37-RUNTIMEDIRECTORYPRESERVE:   FAIL     (1201 s)
focal-s390x: TEST-37-RUNTIMEDIRECTORYPRESERVE:   FAIL     (1201 s)

**Comment by mrc0mmand** [comment]
> focal-amd64: TEST-37-RUNTIMEDIRECTORYPRESERVE: FAIL (1200 s) focal-arm64: TEST-02-UNITTESTS: FAIL (134 s)
> 
> ```
> === Failed test log ===
> --- test-journal-flush begin ---
> journal_file_copy_entry failed: Invalid argument
> Assertion 'r >= 0' failed at src/libsystemd/sd-journal/test-journal-flush.c:52, function main(). Aborting.
> --- test-journal-flush end ---
> ```
> 
> @DaanDeMeyer is it one of the known issues?
> 
Yeah, this one is known, see https://github.com/systemd/systemd/issues/17963.
