### PR TITLE
ethtool: Make sure advertise is actually set when autonegotiation is used

### LINKED ISSUE #11257: Advertise= either does not work or needs inconsistent configuration
My network card is very slow to auto negotiate the link speed down to 100baseT/Full (about 20 seconds). So I've been using this udev rule to make it only advertise that mode:
`ACTION=="add", SUBSYSTEM=="net", KERNEL=="eth*", RUN+="/usr/bin/ethtool -s $name advertise 0x008"`

With system 240, Advertise= was added, but it doesn't seem to work. If I add "Advertise=100baset-full" to the .link file, auto negotiation is still slow and ethtool reports all possible modes being advertised. The logs state "link_config: autonegotiation is unset or enabled, the speed and duplex are not writable." and in the code the advertise settings are only applied if auto negotiation is disabled.

This defeats the whole purpose of link advertise settings since it's supposed to list the modes that are used for negotiations. Note that ethtool also doesn't report advertised modes if I disable auto negotiation, because then it won't have to negotiate at all.

Here's the .link file.
```
[Match]
Driver=e1000e

[Link]
WakeOnLan=off
NamePolicy=kernel database onboard slot path
MACAddressPolicy=persistent

Advertise=100baset-full
#Duplex=full
#BitsPerSecond=100M
#AutoNegotiation=false
```

### PR DESCRIPTION
**Pull request by medhefgo**
Fixes #11257

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

@ssahani?

**Comment by ssahani** [comment]
LGTM Thanks

File: src/udev/net/ethtool-util.c [hunk 1]
```diff
@@ -615,6 +615,8 @@ int ethtool_set_glinksettings(int *fd, const char *ifname, struct link_config *l
         u->base.autoneg = link->autonegotiation;
 
         if (!eqzero(link->advertise)) {
+                if (link->autonegotiation == -1)
+                        u->base.autoneg = 1;
```
Comment (poettering) [inline src/udev/net/ethtool-util.c]: can you explain this? why is this inside the `!eqzero(link->advertise)` if block, and not before it?

Comment (medhefgo) [reply src/udev/net/ethtool-util.c]: I mainly wanted to prevent any accidental behavior changes since I am not in my comfort zone here. Setting this to 1 is necessary, because the default of -1 makes the kernel turn it off altogether. Should I make the assignment outside conditional and the one inside non-conditional? I think that would make it work like ethtool does.

Comment (poettering) [reply src/udev/net/ethtool-util.c]: well, I don't know the kernel api either there, i.e. what the autoneg field expects. before changing this we should really figure that out...

Comment (medhefgo) [reply src/udev/net/ethtool-util.c]: Afaik, it's either AUTONEG_ENABLE or AUTONEG_DISABLE. Anything else gives an EINVAL. So I guess we really should avoid assigning -1.

Comment (medhefgo) [reply src/udev/net/ethtool-util.c]: https://github.com/torvalds/linux/blob/b71acb0e372160167bf6d5500b88b30b52ccef6e/drivers/net/phy/phy.c#L273

**Comment by medhefgo** [comment]
I force pushed a version that only touches autoneg when needed.

File: src/udev/net/ethtool-util.c [hunk 2]
```diff
@@ -612,9 +612,11 @@ int ethtool_set_glinksettings(int *fd, const char *ifname, struct link_config *l
         if (link->port != _NET_DEV_PORT_INVALID)
                 u->base.port = link->port;
 
-        u->base.autoneg = link->autonegotiation;
+        if (link->autonegotiation != -1)
```
Comment (poettering) [inline src/udev/net/ethtool-util.c]: btw, instead of comparing explicitly with `!= -1` here, let's just filter out negative values, i.e. i.e. change `!= -1` to `>= 0`

**Comment by poettering** [comment]
looks pretty good now, just one more nitpick

**Comment by medhefgo** [comment]
Force pushed with >= and also using AUTONEG_ENABLE for the other assignment now.

**Comment by poettering** [comment]
excellent! thanks!
