### PR TITLE
test-seccomp: assume socket filtering is broken on powerpc too

### LINKED ISSUE #17559: RestrictAddressFamilies fails on ppc64 with libseccomp 2.5
libseccomp 2.5 added socket syscall multiplexing on ppc64(el): https://github.com/seccomp/libseccomp/pull/229

Like with i386, s390 and s390x this breaks socket argument filtering, so RestrictAddressFamilies doesn't work.

This causes the unit test to fail:

```
/* test_restrict_address_families */
Operating on architecture: ppc
Failed to install socket family rules for architecture ppc, skipping: Operation canceled
Operating on architecture: ppc64
Failed to add socket() rule for architecture ppc64, skipping: Invalid argument
Operating on architecture: ppc64-le
Failed to add socket() rule for architecture ppc64-le, skipping: Invalid argument
Assertion 'fd < 0' failed at src/test/test-seccomp.c:424, function test_restrict_address_families(). Aborting.
```

The socket filters can't be added so `socket(AF_UNIX, SOCK_DGRAM, 0);` still works, triggering the assertion.

It seems like da1921a5c396547261c8c7fcd94173346eb3b718 (the parts that re-enable ppc64) needs to be reverted.

### PR DESCRIPTION
**Pull request by keszybz**
This partially reverts da1921a5c396547261c8c7fcd94173346eb3b718. Fixes #17559.

Quoting #17559:

libseccomp 2.5 added socket syscall multiplexing on ppc64(el):
https://github.com/seccomp/libseccomp/pull/229

Like with i386, s390 and s390x this breaks socket argument filtering, so
RestrictAddressFamilies doesn't work.

This causes the unit test to fail:
/* test_restrict_address_families */
Operating on architecture: ppc
Failed to install socket family rules for architecture ppc, skipping: Operation canceled
Operating on architecture: ppc64
Failed to add socket() rule for architecture ppc64, skipping: Invalid argument
Operating on architecture: ppc64-le
Failed to add socket() rule for architecture ppc64-le, skipping: Invalid argument
Assertion 'fd < 0' failed at src/test/test-seccomp.c:424, function test_restrict_address_families(). Aborting.

The socket filters can't be added so `socket(AF_UNIX, SOCK_DGRAM, 0);` still
works, triggering the assertion.

### CODE REVIEW

File: src/test/test-seccomp.c [hunk 1]
```diff
@@ -30,7 +30,7 @@
 #include "virt.h"
 
 /* __NR_socket may be invalid due to libseccomp */
-#if !defined(__NR_socket) || __NR_socket < 0 || defined(__i386__) || defined(__s390x__) || defined(__s390__)
+#if !defined(__NR_socket) || __NR_socket < 0 || defined(__i386__) || defined(__s390x__) || defined(__s390__) || defined(__powerpc__)
 /* On these archs, socket() is implemented via the socketcall() syscall multiplexer,
  * and we can't restrict it hence via seccomp. */
```
Comment (yuwata) [inline src/test/test-seccomp.c:35]: Hmm, this comment sounds incompatible with the comment in `seccomp_restrict_address_families()`:
```
/* These we know we support (i.e. are the ones that do not use socketcall()) */
```
Is it not necessary to revert the change for `seccomp_restrict_address_families()` in da1921a5c396547261c8c7fcd94173346eb3b718?

Comment (keszybz) [reply src/test/test-seccomp.c:35]: You're right, a revert is in order. Updated in place.

Comment (keszybz) [reply src/test/test-seccomp.c:35]: This passes on ppc64 with libseccomp-2.5.0-3.fc33.ppc64le.

**Comment by poettering** [comment]
(looks superficially ok, but I am no PPC person. Merged, since tests passed)
