### PR TITLE
core/namespace: do not remount /proc for user services

### LINKED ISSUE #17860: User service failed to start with PrivateUsers=yes and ProtectControlGroups=yes
**systemd version the issue has been seen with**
 > 247.1

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > Linux arch-PC 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Service starts successfully.

**Unexpected behaviour you saw**
 > Service failed to start.
 > Logs:
 >```
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Successfully forked off '(sd-userns)' as PID 31611.
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: (sd-userns) succeeded.
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Bind-mounting / on /run/systemd/unit-root (MS_BIND|MS_REC "")...
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Applying namespace mount on /run/systemd/unit-root/dev
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Applying namespace mount on /run/systemd/unit-root/proc
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Failed to umount /run/systemd/unit-root/proc, ignoring: Invalid argument
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Failed to umount /run/systemd/unit-root/proc/sys/fs/binfmt_misc, ignoring: Invalid argument
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Mounting proc (proc) on /run/systemd/unit-root/proc (MS_NOSUID|MS_NODEV|MS_NOEXEC "")...
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Failed to mount proc (type proc) on /run/systemd/unit-root/proc (MS_NOSUID|MS_NODEV|MS_NOEXEC ""): Operation not permitted
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: ssh-agent.service: Failed to set up mount namespacing: /run/systemd/unit-root/proc: Operation not permitted
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Changed failed -> running
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=7 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Job 31 ssh-agent.service/start finished, result=done
 > Dec 05 18:49:09 arch-PC systemd[31489]: Started SSH key agent.
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/ssh_2dagent_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=8 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/ssh_2dagent_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=10 reply_cookie=0 signature=uoss error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/ssh_2dagent_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=11 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/ssh_2dagent_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=12 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31610]: Skipping PR_SET_MM, as we don't have privileges.
 > Dec 05 18:49:09 arch-PC systemd[31610]: ssh-agent.service: Failed at step NAMESPACE spawning /usr/bin/ssh-agent: Operation not permitted
 > Dec 05 18:49:09 arch-PC systemd[31489]: Received SIGCHLD from PID 31610 ((sh-agent)).
 > Dec 05 18:49:09 arch-PC systemd[31489]: Child 31610 ((sh-agent)) died (code=exited, status=226/NAMESPACE)
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Child 31610 belongs to ssh-agent.service.
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Main process exited, code=exited, status=226/NAMESPACE
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Failed with result 'exit-code'.
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Service will not restart (restart setting)
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Changed running -> failed
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=13 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Unit entered failed state.
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Consumed 1ms CPU time.
 >```

**Steps to reproduce the problem**
 > 1. Create a user service file ~/.config/systemd/user/ssh-agent.service
 >```
 >[Unit]
 >Description=SSH key agent
 >
 >[Service]
 >Type=simple
 >Environment=SSH_AUTH_SOCK=%t/ssh-agent.socket
 >ExecStart=/usr/bin/ssh-agent -D -a $SSH_AUTH_SOCK
 >
 >PrivateUsers=yes
 >ProtectControlGroups=yes
 >
 >[Install]
 >WantedBy=default.target
 >```
 >2. Run `systemctl --user daemon-reload` and `systemctl --user start ssh-agent.service`

These 2 settings works fine in systemd 246.6.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #17860.

(Not tested yet.)

### CODE REVIEW

**Comment by yuwata** [comment]
Still I have not tested this, but the original issue reporter @duament confirmed that this fixes the issue. PTAL.

File: src/core/namespace.c [hunk 1]
```diff
@@ -873,6 +873,15 @@ static int mount_procfs(const MountEntry *m, const NamespaceInfo *ns_info) {
          * mounted on /proc/ first. */
```
Comment (bluca) [inline src/core/namespace.c]: The comment above needs to be updated and moved, as it states that /proc is always remounted. For example I'd add something like this:

"In case of unprivileged user namespaces (systemd --user), mounting /proc is not allowed by the kernel."

(the manpages of user_namespaces state that it is allowed with just a mount namespace and a username namespace, but I do not believe that is true, a PID namespace is needed as well at a minimum)

**Comment by yuwata** [comment]
@bluca Thank you for the suggestion. Now the suggested comment is added. And the original comment is moved after the `if` block. I'd like to leave the man page update in a later PR, as I am not sure the exact condition now...

**Comment by bluca** [comment]
> @bluca Thank you for the suggestion. Now the suggested comment is added. And the original comment is moved after the `if` block. I'd like to leave the man page update in a later PR, as I am not sure the exact condition now...
> 
> PTAL.

Looks good thanks, setting green label.

This is a topic we should keep in mind and try to bring up with the kernel folks - it would be really great to be able to use the new "protected" proc in systemd --user instances.
To do it on our side without kernel changes, perhaps we could leverage nspawn's shim pid1 to be able to set a pid namespace when forking those services - would be a lot of refactoring though.

**Comment by bluca** [comment]
mmh TEST-13-NSPAWN-SMOKE failed in bionic-amd64, IIRC this is not one of the usual ones?

**Comment by topimiettinen** [comment]
> To do it on our side without kernel changes, perhaps we could leverage nspawn's shim pid1 to be able to set a pid namespace when forking those services - would be a lot of refactoring though.

I actually made a WIP PR for PID namespacing (#11670), but then it was decided that /proc mounting options (`hidepid=`, implemented as `ProtectProc=` and `ProcSubset=`) would be better.

**Comment by bluca** [comment]
> > To do it on our side without kernel changes, perhaps we could leverage nspawn's shim pid1 to be able to set a pid namespace when forking those services - would be a lot of refactoring though.
> 
> I actually made a WIP PR for PID namespacing (#11670), but then it was decided that /proc mounting options (`hidepid=`, implemented as `ProtectProc=` and `ProcSubset=`) would be better.

Yeah, that all makes sense. It would be up to the kernel to make that available to unpriv namespaces then.

**Comment by yuwata** [comment]
> mmh TEST-13-NSPAWN-SMOKE failed in bionic-amd64, IIRC this is not one of the usual ones?

Hmm, not sure, but I do not think it is related to this PR. Anyway, let's restart all CIs.

**Comment by bluca** [comment]
> > mmh TEST-13-NSPAWN-SMOKE failed in bionic-amd64, IIRC this is not one of the usual ones?
> 
> Hmm, not sure, but I do not think it is related to this PR. Anyway, let's restart all CIs.

Yeah, it seems unlikely that this change would affect it. And I no longer see the full journal in the artifacts.tar.gz, I'll see if I can find out why it's no longer packed.

**Comment by poettering** [comment]
Hmm, I think we should just handle EPERM when mounting /proc fails more gracefully here. i.e. it sounds like sooner or later this might be opened up in userns too, and we should then use it. Hence: let's try to mount it, but if we figure out it's not permitted just fallback the same way we fallbck on EINVAL (i.e. on old kernels)

**Comment by bluca** [comment]
> Hmm, I think we should just handle EPERM when mounting /proc fails more gracefully here. i.e. it sounds like sooner or later this might be opened up in userns too, and we should then use it. Hence: let's try to mount it, but if we figure out it's not permitted just fallback the same way we fallbck on EINVAL (i.e. on old kernels)

That sounds good to me, although I'd still differentiate the reaction to EPERM between pid1 and systemd --user: in the former case, especially when hidepid= is used, I think I'd prefer a hard failure. Unless there are foreseeable use cases where we are not allowed to remount /proc, it sounds like something that shouldn't happen, and an anomalous situation that could be used to downgrade isolation features.

**Comment by poettering** [comment]
> That sounds good to me, although I'd still differentiate the reaction to EPERM between pid1 and systemd --user: in the former case, especially when hidepid= is used, I think I'd prefer a hard failure. Unless there are foreseeable use cases where we are not allowed to remount /proc, it sounds like something that shouldn't happen, and an anomalous situation that could be used to downgrade isolation features.

We never know what happens in containers: typically stuff is forbidden there that is allowed on a regular system, and we should handle that fine. Moreover, I actually think it's OK if people have an selinux (or some other MAC) that disallows remounting procfs, and in that case we could see EPERM even on a host system.

In most cases so far we accepted that EPERM means that someone doesn't want us to do something, and we should handle it gracefully.

**Comment by bluca** [comment]
> > That sounds good to me, although I'd still differentiate the reaction to EPERM between pid1 and systemd --user: in the former case, especially when hidepid= is used, I think I'd prefer a hard failure. Unless there are foreseeable use cases where we are not allowed to remount /proc, it sounds like something that shouldn't happen, and an anomalous situation that could be used to downgrade isolation features.
> 
> We never know what happens in containers: typically stuff is forbidden there that is allowed on a regular system, and we should handle that fine. Moreover, I actually think it's OK if people have an selinux (or some other MAC) that disallows remounting procfs, and in that case we could see EPERM even on a host system.
> 
> In most cases so far we accepted that EPERM means that someone doesn't want us to do something, and we should handle it gracefully.

Ok, makes sense to me, hadn't considered the LSM route.

**Comment by yuwata** [comment]
> Hmm, I think we should just handle EPERM when mounting /proc fails more gracefully here. i.e. it sounds like sooner or later this might be opened up in userns too, and we should then use it. Hence: let's try to mount it, but if we figure out it's not permitted just fallback the same way we fallbck on EINVAL (i.e. on old kernels)

Currently, we unmount /proc and remount /proc. If mounting /proc fails, we cannot have /proc anymore...
So, handling EPERM gracefully, we need to first try to mount procfs on at somewhere. Is it what you mean?

**Comment by yuwata** [comment]
Still I have not idea how should we handle EPERM gracefully. So, I proposed another way. Now, the existing /proc is used when no mount option is requested.

**Comment by poettering** [comment]
Hmm, we have to mount a new procfs also when we opened a new userns, so that the procfs instance is owned by the userns instance, iirc. Th check would have to be extended for that I think.

That said: maybe a different approach could work too: in general if we can unmount /proc, we should also be able to mount it again. Maybe not with the mount options of our choice, but in general I think this should work. Hence maybe a workable appraoch would be to just add a fallback: if we can't mount procfs with the options of our choice, just mount things with the optoins we used to use (and log about it)

**Comment by yuwata** [comment]
@poettering Thank you for the suggestion. v3 is pushed. PTAL.

**Comment by keszybz** [comment]
LGTM, but @poettering's ack would be nice too.

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
lgtm
