### PR TITLE
sd-event: fix memleak when built without assertion

### LINKED ISSUE #34899: sd_event_set_signal_exit leaks memory when compiled without assertions
The implementation of `sd_event_set_signal_exit` contains `assert()` statements with side-effects, namely the setting of floating and non-floating mode of the SIGINT and SIGTERM event sources.

https://github.com/systemd/systemd/blob/f7078de515efd7089266815648b6e682f800649f/src/libsystemd/sd-event/sd-event.c#L5272

When compiled with assertions disabled, the event sources remain non-floating and pin the event loop itself. A comment even warns about this danger:

https://github.com/systemd/systemd/blob/f7078de515efd7089266815648b6e682f800649f/src/libsystemd/sd-event/sd-event.c#L5263-L5265

---

On another note, these assertions trigger rather than returning `-ECHILD` when disabling the signal handlers.
```c
#include <unistd.h>
#include <stdlib.h>
#include <systemd/sd-event.h>

int main(void) {
	struct sd_event *event;
	int r = 0;

	r = sd_event_new(&event);
	if (r < 0) abort();

	r = sd_event_set_signal_exit(event, 1);
	if (r < 0) abort();

	pid_t pid = fork();
	if (pid == 0) {
		r = sd_event_set_signal_exit(event, 0);
		if (r < 0) abort();
		return 0;
	}

	sd_event_unref(event);
	return 0;
}
```
```
$ gcc -g -lsystemd -fsanitize=address,undefined signal.c -o signal && ./signal
Assertion 'sd_event_source_set_floating(e->sigint_event_source, false) >= 0' failed at src/libsystemd/sd-event/sd-event.c:5254, function sd_event_set_signal_exit(). Aborting.
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug introduced by baf3fdec27f0b3a1f3d39c7def2a778824cbee51.

Fixes #34899.

### CODE REVIEW

File: src/libsystemd/sd-event/sd-event.c [hunk 1]
```diff
@@ -5269,34 +5269,34 @@ _public_ int sd_event_set_signal_exit(sd_event *e, int b) {
...
+                        assert_se(sd_event_source_set_floating(e->sigint_event_source, true) >= 0);
                         change = true;
                 }
 
                 if (!e->sigterm_event_source) {
                         r = sd_event_add_signal(e, &e->sigterm_event_source, SIGTERM | SD_EVENT_SIGNAL_PROCMASK, NULL, NULL);
                         if (r < 0) {
                                 if (change) {
-                                        assert(sd_event_source_set_floating(e->sigint_event_source, false) >= 0);
+                                        assert_se(sd_event_source_set_floating(e->sigint_event_source, false) >= 0);
```
Comment (polarina) [inline src/libsystemd/sd-event/sd-event.c:5280]: This should be `sigterm_event_source`.

File: src/libsystemd/sd-event/sd-event.c [hunk 2]
```diff
@@ -5269,34 +5269,34 @@ _public_ int sd_event_set_signal_exit(sd_event *e, int b) {
...
 
-                        assert(sd_event_source_set_floating(e->sigterm_event_source, true) >= 0);
+                        assert_se(sd_event_source_set_floating(e->sigterm_event_source, true) >= 0);
                         change = true;
                 }
 
         } else {
                 if (e->sigint_event_source) {
-                        assert(sd_event_source_set_floating(e->sigint_event_source, false) >= 0);
+                        assert_se(sd_event_source_set_floating(e->sigint_event_source, false) >= 0);
```
Comment (polarina) [inline src/libsystemd/sd-event/sd-event.c:5296]: `sd_event_source_set_floating` here may return `-ECHILD` and trigger the assertion. Perhaps add a top-level `assert_return` to `sd_event_set_signal_exit`?

Comment (yuwata) [reply src/libsystemd/sd-event/sd-event.c:5296]: Thanks. Added.
