### PR TITLE
coredump: AccessContainer= bunch of followups

### LINKED ISSUE #34130: namespace coredump stacktrace generator needs fixes.
### systemd version the issue has been seen with

git main

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

tracker bug for the post-merge issues found in #33675

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by msekletar**
Fixes #34130

### CODE REVIEW

**Comment by msekletar** [comment]
@poettering PTAL.

File: src/analyze/analyze-inspect-elf.c [hunk 1]
```diff
@@ -27,13 +28,7 @@ static int analyze_elf(char **filenames, sd_json_format_flags_t json_flags) {
...
                         return log_error_errno(r, "Could not make an absolute path out of \"%s\": %m", *filename);
 
-                path = path_join(empty_to_root(arg_root), abspath);
-                if (!path)
-                        return log_oom();
-
-                path_simplify(path);
-
-                fd = RET_NERRNO(open(path, O_RDONLY|O_CLOEXEC));
+                fd = chase_and_open(abspath, arg_root, CHASE_PREFIX_ROOT, O_RDONLY|O_CLOEXEC, NULL);
```
Comment (poettering) [inline src/analyze/analyze-inspect-elf.c]: chase_and_open() also will do path_make_absolute_cwd() for you, implicitly.

and it returns the full path of what it resolved to as last argument, if you want, which you can use for `abspath` below

Comment (poettering) [reply src/analyze/analyze-inspect-elf.c]: also, in our current coding style, if you pass NULL or 0 or something equally opaque as an argument to a function, please prefix with a parameter name as comment, to give the reader a hint what this is. i.e. the last argument here should be `/* ret_path= */ NULL`

File: src/coredump/coredump.c [hunk 2]
```diff
@@ -857,9 +860,9 @@ static int submit_coredump(
         }
 
         if (mount_tree_fd >= 0 && arg_access_container) {
-                r = setup_container_mount_tree(mount_tree_fd, &root);
+                r = attach_mount_tree(mount_tree_fd);
                 if (r < 0)
-                        log_warning_errno(r, "Failed to setup container mount tree, ignoring: %m");
+                        root = NULL;
         }
```
Comment (poettering) [inline src/coredump/coredump.c]: hmm, with this `root` will be set to the wrong root in case arg_access_container is false. this doesn't look right?

File: src/coredump/coredump.c [hunk 3]
```diff
@@ -1115,18 +1115,36 @@ static int process_socket(int fd) {
                                 /* We have all FDs we need let's take a shortcut here. */
                                 break;
                         } else {
+                                struct cmsghdr *cmsg;
+                                unsigned n_fds = 0;
+
                                 found = cmsg_find(&mh, SOL_SOCKET, SCM_RIGHTS, CMSG_LEN(sizeof(int)));
-                                if (found)
+                                if (first) {
+                                        /* This is the first message that carries file descriptors, maybe there will be
```
Comment (poettering) [inline src/coredump/coredump.c]: you are not checking whether `found` is actually true here?

File: src/coredump/coredump.c [hunk 4]
```diff
@@ -1115,18 +1115,36 @@ static int process_socket(int fd) {
...
+                                        continue;
+                                }
 
-                        break;
+                                /* This is second iteration and we didn't find array of two FDs, hence we either
+                                 * have no FDs which is OK and we can break or we have some other number of FDs
+                                 * and somebody is playing games with us. So let's check for that. */
+                                CMSG_FOREACH(cmsg, &mh)
+                                        if (cmsg->cmsg_level == SOL_SOCKET && cmsg->cmsg_type == SCM_RIGHTS)
+                                                n_fds++;
```
Comment (poettering) [inline src/coredump/coredump.c]: you can use cmsg_find() and specify the size as (socklen_t) -1

File: src/coredump/coredump.c [hunk 5]
```diff
@@ -1659,11 +1659,11 @@ static int gather_pid_mount_tree_fd(const Context *context) {
 
         /* Don't bother preparing environment if we can't pass it to libdwfl. */
 #if !HAVE_DWFL_SET_SYSROOT
-        return -EBADF;
+        return -EOPNOTSUPP;
```
Comment (poettering) [inline src/coredump/coredump.c]: this sounds ok

File: src/coredump/coredump.c [hunk 6]
```diff
@@ -1659,11 +1659,11 @@ static int gather_pid_mount_tree_fd(const Context *context) {
...
 #endif
 
         if (!arg_access_container)
-                return -EBADF;
+                return -EOPNOTSUPP;
```
Comment (poettering) [inline src/coredump/coredump.c]: but this doesn't. user configuratoin should not result in EOPNOTSUPP. Use something such as EHOSTDOWN maybe?

File: src/coredump/coredump.c (hunk 3 above)
Comment (msekletar) [reply src/coredump/coredump.c]: You are right, I must check found as well.

File: src/coredump/coredump.c (hunk 6 above)
Comment (poettering) [reply src/coredump/coredump.c]: or actually, i don't like either. in systemd we have this rule that functions should either log about all their errors, or about none (where logging means: log above LOG_DEBUG log level, because LOG_DEBUG logging is always ok). 

But these two new errors here you do not log about, though you do log about all other errors. 

hence, maybe change the gather_pid_mount_tree_fd() prototype to this:

```c
static int gather_pid_mount_tree_fd(const Context *context, int *ret_fd) {
```

And now, change these two EOPNOTSUPP/EHOSTDOWN cases to return zero (i.e. success), but then return with `*ret_fd = -EBADF;`. Thus, things are reasonably clean: we treat all errors as errors, and whether we return an fd or not on success is up to us.

File: src/coredump/coredump.c [hunk 7]
```diff
@@ -1676,7 +1676,7 @@ static int gather_pid_mount_tree_fd(const Context *context) {
                            "(sd-mount-tree)",
                            /* except_fds= */ NULL,
                            /* n_except_fds= */ 0,
-                           FORK_RESET_SIGNALS|FORK_DEATHSIG_SIGKILL|FORK_LOG,
+                           FORK_RESET_SIGNALS|FORK_DEATHSIG_SIGKILL|FORK_LOG|FORK_WAIT,
```
Comment (poettering) [inline src/coredump/coredump.c:1696]: afaics you don't need the `child` parameter anymore now. hence you can set that to NULL and get rid of the local var for it.

**Comment by msekletar** [comment]
> EnterNamespace=?

That sounds much better!

File: src/analyze/analyze-inspect-elf.c (hunk 1 above)
Comment (msekletar) [reply src/analyze/analyze-inspect-elf.c]: > and it returns the full path of what it resolved to as last argument, if you want, which you can use for `abspath` below

But when given thing doesn't exist inside root it doesn't open it and doesn't give me back absolute path but I need that for logging so I think we should keep the code as is.

Comment (poettering) [reply src/analyze/analyze-inspect-elf.c]: hmm? can't parse that? what's wrong with the path it returns as last arg?

Comment (msekletar) [reply src/analyze/analyze-inspect-elf.c]: Well the problem is on error case, I wanted resolved path even in the case the target doesn't exist, but I will just log the filename, i.e. what user gave us on commandline.

File: src/coredump/coredump.c (hunk 2 above)
Comment (msekletar) [reply src/coredump/coredump.c]: if arg_access_container is false then mount_tree_fd is invalid, i.e. we don't even send it, so I guess we could just check for fd validity.

Comment (msekletar) [reply src/coredump/coredump.c]: I guess I could just set root to "/" if attaching alternative mount tree fails, that would work as well because in parse_core we check or "/" and don't call dwfl_set_sysroot() in such case.

File: src/coredump/coredump.c (hunk 3 above)
Comment (msekletar) [reply src/coredump/coredump.c]: I think something like this might work,

```C
found = cmsg_find(&mh, SOL_SOCKET, SCM_RIGHTS, CMSG_LEN(sizeof(int)));
if (first && found) {
        /* This is the first message that carries file descriptors, maybe there will be
         * one more that actually contains array of two descriptors. */
        assert(input_fd < 0);
        input_fd = *CMSG_TYPED_DATA(found, int);
        first = false;
        continue;
} else if (first && !found) {
        /* This is the first message of zero length and it has no file descriptor,
         * this is the protocol violation so let's bail out. */
        cmsg_close_all(&mh);
        r = log_error_errno(SYNTHETIC_ERRNO(EBADMSG),
                    "Received zero length message with no file descriptor.");
        goto finish;
}
```

File: src/coredump/coredump.c (hunk 4 above)
Comment (msekletar) [reply src/coredump/coredump.c]: Hmmm, I want to count number of FDs attached to the message how does cmsg_find() helps me in that ?

**Comment by msekletar** [comment]
Updated. @poettering PTAL.

Once this is merged I will update #34300 and change AccessContainer= to EnterNamespace=.

**Comment by poettering** [comment]
hmm, either drop the "fixes" line, or add the rename commit to this PR as well.

**Comment by msekletar** [comment]
@poettering rename commit is on the branch already, now I've also added the commit with test and closed #34300.

File: test/TEST-74-AUX-UTILS/test.sh [hunk 8]
```diff
@@ -36,6 +36,7 @@ test_append_files() {
     instmods vmw_vsock_virtio_transport
     instmods vsock_loopback
     instmods vmw_vsock_vmci_transport
+    inst_binary gcc
```
Comment (bluca) [inline test/TEST-74-AUX-UTILS/test.sh:39]: As per the other PR this needs to move into a standalone test as this one runs in a container so it's not actually tested, it's skipped

Comment (msekletar) [reply test/TEST-74-AUX-UTILS/test.sh:39]: Test bails out early if it is running in container and that is true for the entire `TEST-74-AUX-UTILS.coredump.sh`. IOW, we don't test coredumpd and coredumpctl in containers and rightfully so. If we want to test coredump related components we need to run the test in a VM. I don't see how moving this new piece to a separate test case would help as I'd have to add the same condition at the beginning, i.e. if container then skip;

Comment (bluca) [reply test/TEST-74-AUX-UTILS/test.sh:39]: Yeah that's what I meant - the coredump test needs to move to TEST-86-COREDUMP or so, configured to run as a vm

Comment (msekletar) [reply test/TEST-74-AUX-UTILS/test.sh:39]: OK, I will work with @mrc0mmand and we can do that but I think that should be done in a separate PR.

File: src/coredump/coredump.c [hunk 9]
```diff
@@ -782,30 +784,32 @@ static int change_uid_gid(const Context *context) {
...
-        r = unshare(CLONE_NEWNS);
+        r = detach_mount_namespace();
         if (r < 0)
-                return log_warning_errno(errno, "Failed to unshare mount namespace: %m");
+                return log_warning_errno(r, "Failed to detach mount namespace: %m");
 
-        r = mount(NULL, "/", NULL, MS_REC|MS_PRIVATE, NULL);
-        if (r < 0)
-                return log_warning_errno(errno, "Failed to disable mount propagation: %m");
+        r = mkdir_label(MOUNT_TREE_ROOT, 0555);
```
Comment (poettering) [inline src/coredump/coredump.c]: maybe use mkdir_p_label() here, given this is three levels down, even if /run/systemd will already exist.

You can then drop EEXIST check below.

File: src/coredump/coredump.c [hunk 10]
```diff
@@ -782,30 +784,32 @@ static int change_uid_gid(const Context *context) {
...
+                                        .propagation = MS_SLAVE,
+                                }, sizeof(struct mount_attr));
         if (r < 0)
-                return log_warning_errno(r, "Failed to create temporary directory: %m");
+                return log_warning_errno(r, "Failed to change properties mount tree: %m");
 
-        r = move_mount(mount_tree_fd, "", -EBADF, root, MOVE_MOUNT_F_EMPTY_PATH);
+        r = move_mount(mount_tree_fd, "", -EBADF, MOUNT_TREE_ROOT, MOVE_MOUNT_F_EMPTY_PATH);
         if (r < 0)
                 return log_warning_errno(errno, "Failed to move mount tree: %m");
```
Comment (poettering) [inline src/coredump/coredump.c]: please update the log message. You are not really "moving" the mount here, you are attaching it. Yes, the system call is called "move_mount()", but that's because it is generic, but the operation you chose here isn't.

File: src/coredump/coredump.c [hunk 11]
```diff
@@ -819,8 +823,7 @@ static int submit_coredump(
         _cleanup_close_ int coredump_fd = -EBADF, coredump_node_fd = -EBADF;
         _cleanup_free_ char *filename = NULL, *coredump_data = NULL;
         _cleanup_free_ char *stacktrace = NULL;
-        _cleanup_free_ char *root = NULL;
-        const char *module_name;
+        const char *module_name, *root = MOUNT_TREE_ROOT;
```
Comment (poettering) [inline src/coredump/coredump.c]: this is confusing to me? now you pass this along always, even for coredumps of the host rather than any container? that cannot be right? what am i missing?

File: src/coredump/coredump.c (hunk 2 above)
Comment (poettering) [reply src/coredump/coredump.c]: but why assign "/"? why not assing NULL?

File: src/coredump/coredump.c [hunk 12]
```diff
@@ -1115,18 +1115,43 @@ static int process_socket(int fd) {
                                 /* We have all FDs we need let's take a shortcut here. */
                                 break;
                         } else {
```
Comment (poettering) [inline src/coredump/coredump.c]: get rid of the `else` here? the `if` branch does `break` anyway, hence you can get rid of one level of indentatin here by dropping the `else`.

We generally prefer shallow indentation

File: src/coredump/coredump.c [hunk 13]
```diff
@@ -1115,18 +1115,43 @@ static int process_socket(int fd) {
...
+
+                                        continue;
+                                } else if (first && !found) {
+                                        /* This is the first message of zero length and it has no file descriptor,
+                                         * this is the protocol violation so let's bail out. */
+                                        cmsg_close_all(&mh);
+                                        r = log_error_errno(SYNTHETIC_ERRNO(EBADMSG),
+                                                    "Received zero length message with no file descriptor.");
+                                        goto finish;
+                                }
```
Comment (poettering) [inline src/coredump/coredump.c]: both bracnhes here are conditioned on `first` being true? place in the same common if branch?

File: src/coredump/coredump.c [hunk 14]
```diff
@@ -1656,28 +1660,35 @@ static int forward_coredump_to_container(Context *context) {
...
+        if (!arg_access_container) {
+                r = 0;
+                goto finish;
+        }
 
-        if (socketpair(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0, pair) < 0)
-                return log_error_errno(errno, "Failed to create socket pair: %m");
+        if (socketpair(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0, pair) < 0) {
+                r = log_error_errno(errno, "Failed to create socket pair: %m");
+                goto finish;
```
Comment (poettering) [inline src/coredump/coredump.c]: we have this rule in systemd: on success always initialize return params + on failure do not touch thim. In this error path you will touch *ret_fd  however

Comment (poettering) [reply src/coredump/coredump.c]: or in other words, just drop this specific change?

File: src/coredump/coredump.c [hunk 15]
```diff
@@ -1656,28 +1660,35 @@ static int forward_coredump_to_container(Context *context) {
...
+        }
 
         r = namespace_open(context->pid, NULL, &mntns_fd, NULL, NULL, &root_fd);
-        if (r < 0)
-                return log_error_errno(r, "Failed to open mount namespace of crashing process: %m");
+        if (r < 0) {
+                log_error_errno(r, "Failed to open mount namespace of crashing process: %m");
+                goto finish;
+        }
```
Comment (poettering) [inline src/coredump/coredump.c]: ditto

File: src/coredump/coredump.c [hunk 16]
```diff
@@ -1689,9 +1700,9 @@ static int gather_pid_mount_tree_fd(const Context *context) {
                            /* netns_fd= */ -EBADF,
                            /* userns_fd= */ -EBADF,
                            root_fd,
-                           &child);
+                           NULL);
         if (r < 0)
-                return r;
+                goto finish;
```
Comment (poettering) [inline src/coredump/coredump.c]: ditto

File: src/coredump/coredump.c [hunk 17]
```diff
@@ -1712,11 +1723,17 @@ static int gather_pid_mount_tree_fd(const Context *context) {
 
         pair[1] = safe_close(pair[1]);
 
-        fd = receive_one_fd(pair[0], MSG_DONTWAIT);
-        if (fd < 0)
-                return log_error_errno(fd, "Failed to receive mount tree: %m");
+        r = receive_one_fd(pair[0], MSG_DONTWAIT);
+        if (r < 0) {
+                log_error_errno(r, "Failed to receive mount tree: %m");
+                goto finish;
```
Comment (poettering) [inline src/coredump/coredump.c]: ditto

File: src/coredump/coredump.c [hunk 18]
```diff
@@ -1712,11 +1723,17 @@ static int gather_pid_mount_tree_fd(const Context *context) {
...
+        }
 
-        return fd;
+        fd = r;
```
Comment (poettering) [inline src/coredump/coredump.c]: why not assign to `fd` right away?

File: src/coredump/coredump.c [hunk 19]
```diff
@@ -1656,28 +1660,35 @@ static int forward_coredump_to_container(Context *context) {
...
 
         assert(context);
+        assert(ret_fd);
 
         /* Don't bother preparing environment if we can't pass it to libdwfl. */
 #if !HAVE_DWFL_SET_SYSROOT
-        return -EOPNOTSUPP;
+        r = 0;
+        goto finish;
 #endif
```
Comment (poettering) [inline src/coredump/coredump.c]: the rest of the function should probably be guarded by an `#else` branch

File: src/coredump/coredump.c [hunk 20]
```diff
@@ -1656,28 +1660,35 @@ static int forward_coredump_to_container(Context *context) {
...
-        pid_t child;
 
         assert(context);
+        assert(ret_fd);
 
         /* Don't bother preparing environment if we can't pass it to libdwfl. */
 #if !HAVE_DWFL_SET_SYSROOT
-        return -EOPNOTSUPP;
+        r = 0;
+        goto finish;
```
Comment (poettering) [inline src/coredump/coredump.c]: just do: 

```
*ret_fd = -EOPNOTSUPP;
return 0;
```

File: src/coredump/coredump.c [hunk 21]
```diff
@@ -1656,28 +1660,35 @@ static int forward_coredump_to_container(Context *context) {
...
 #endif
 
-        if (!arg_access_container)
-                return -EOPNOTSUPP;
+        if (!arg_access_container) {
+                r = 0;
+                goto finish;
```
Comment (poettering) [inline src/coredump/coredump.c]: and here:

```
*ret_fd = -EHOSTDOWN;
return 0;
```

File: src/coredump/coredump.c [hunk 22]
```diff
@@ -1712,12 +1712,6 @@ static int gather_pid_mount_tree_fd(const Context *context) {
 
         pair[1] = safe_close(pair[1]);
 
-        r = wait_for_terminate_and_check("(sd-mount-tree-ns)", child, 0);
-        if (r < 0)
-                return log_error_errno(r, "Failed to wait for child: %m");
-        if (r != EXIT_SUCCESS)
-                return log_error_errno(SYNTHETIC_ERRNO(ECHILD), "Child died abnormally.");
```
Comment (poettering) [inline src/coredump/coredump.c:1681]: the removal of the local `child` variable should really be squashed into this commit (ended up in the next)

File: src/coredump/coredump.c (hunk 11 above)
Comment (msekletar) [reply src/coredump/coredump.c]: In `parse_core()` we check `root` argument with `empty_or_root()` and don't call `sym_dwfl_set_sysroot()` is such case.

**Comment by msekletar** [comment]
Updated. @poettering PTAL.

File: src/coredump/coredump.c (hunk 9 above)
Comment (yuwata) [reply src/coredump/coredump.c]: Not addressed? I think `mkdir_p_label()` is better.

File: src/coredump/coredump.c (hunk 12 above)
Comment (yuwata) [reply src/coredump/coredump.c]: Unaddressed.

File: src/coredump/coredump.c (hunk 13 above)
Comment (yuwata) [reply src/coredump/coredump.c]: Unaddressed. How about something like the following?
```c
if (first) {
        found = cmsg_find(...);
        if (!found) {
                cmsg_close_all(&mh);
                r = log_error_errno(...);
                goto finish;
        }

        assert(input_fd < 0);
        input_fd = ...;
        first = false;
        continue;
}
```

File: src/coredump/coredump.c (hunk 4 above)
Comment (yuwata) [reply src/coredump/coredump.c]: SCM_RIGHTS should not be included multiple times.

File: src/coredump/coredump.c (hunk 19 above)
Comment (yuwata) [reply src/coredump/coredump.c]: unaddressed.

File: src/coredump/coredump.c (hunk 14 above)
Comment (yuwata) [reply src/coredump/coredump.c]: Unaddressed.

File: src/coredump/coredump.c [hunk 23]
```diff
@@ -798,8 +798,8 @@ static int attach_mount_tree(int mount_tree_fd) {
         if (r < 0)
                 return log_warning_errno(r, "Failed to detach mount namespace: %m");
 
-        r = mkdir_label(MOUNT_TREE_ROOT, 0555);
-        if (r < 0 && r != -EEXIST)
+        r = mkdir_p_label(MOUNT_TREE_ROOT, 0555);
```
Comment (yuwata) [inline src/coredump/coredump.c:802]: Please move this change to the earlier commit.

File: src/coredump/coredump.c [hunk 24]
```diff
@@ -812,7 +812,7 @@ static int attach_mount_tree(int mount_tree_fd) {
 
         r = move_mount(mount_tree_fd, "", -EBADF, MOUNT_TREE_ROOT, MOVE_MOUNT_F_EMPTY_PATH);
         if (r < 0)
-                return log_warning_errno(errno, "Failed to move mount tree: %m");
+                return log_warning_errno(errno, "Failed to attach mount tree: %m");
```
Comment (yuwata) [inline src/coredump/coredump.c:816]: Also this one. Please move to the third commit.

File: src/coredump/coredump.c [hunk 25]
```diff
@@ -826,7 +826,7 @@ static int submit_coredump(
         _cleanup_(sd_json_variant_unrefp) sd_json_variant *json_metadata = NULL;
         _cleanup_close_ int coredump_fd = -EBADF, coredump_node_fd = -EBADF;
         _cleanup_free_ char *filename = NULL, *coredump_data = NULL, *stacktrace = NULL;
-        const char *module_name, *root = MOUNT_TREE_ROOT;
+        const char *module_name, *root = NULL;
```
Comment (yuwata) [inline src/coredump/coredump.c:830]: Nah, please make commits clean...

**Review by yuwata — CHANGES_REQUESTED** [review]
Please merge the last commit into earlier commits. Otherwise, it is hard to review.

File: src/coredump/coredump.c (hunk 25 above)
Comment (msekletar) [reply src/coredump/coredump.c:830]: Don't focus on commits, I made them separate so they are easier to review, maybe that was a bad idea.  I will probably just squash them.

File: src/coredump/coredump.c (hunk 4 above)
Comment (msekletar) [reply src/coredump/coredump.c]: Good point, so now I see what Lennart meant.

File: man/coredump.conf.xml [hunk 26]
```diff
@@ -110,14 +110,14 @@
       </varlistentry>
 
       <varlistentry>
-        <term><varname>AccessContainer=</varname></term>
+        <term><varname>EnterNamespace=</varname></term>
 
         <listitem><para>Controls whether <command>systemd-coredump</command> will attempt to use the mount tree of
-        a process that crashed within a container. Access to the container's filesystem might be necessary to generate
+        a process that crashed in PID namespace. Access to the namespace's mount tree might be necessary to generate
```
Comment (poettering) [inline man/coredump.conf.xml:116]: hmm, "PID namespace"?

your changes don't care about PID namespace, do they? they care about file system namespaces only afaics.

File: src/coredump/coredump.c [hunk 27]
```diff
@@ -782,30 +788,32 @@ static int change_uid_gid(const Context *context) {
...
 
-        r = mkdtemp_malloc("/tmp/systemd-coredump-root-XXXXXX", &root);
+        r = mount_setattr(mount_tree_fd, "", AT_EMPTY_PATH,
+                                &(struct mount_attr) {
+                                        .attr_set = MOUNT_ATTR_RDONLY|MOUNT_ATTR_NOSUID|MOUNT_ATTR_NODEV|MOUNT_ATTR_NOEXEC,
+                                        .propagation = MS_SLAVE,
+                                }, sizeof(struct mount_attr));
         if (r < 0)
-                return log_warning_errno(r, "Failed to create temporary directory: %m");
+                return log_warning_errno(r, "Failed to change properties mount tree: %m");
```
Comment (poettering) [inline src/coredump/coredump.c]: first arg must be `errno`, not `r`

File: src/coredump/coredump.c [hunk 28]
```diff
@@ -1056,6 +1063,8 @@ static int process_socket(int fd) {
         log_debug("Processing coredump received on stdin...");
 
         for (;;) {
+                struct cmsghdr *cmsg;
```
Comment (poettering) [inline src/coredump/coredump.c]: please move to innermost scope

File: src/coredump/coredump.c [hunk 29]
```diff
@@ -1087,40 +1096,67 @@ static int process_socket(int fd) {
...
                 }
 
-                /* The final zero-length datagram carries the file descriptor and tells us
+                /* The final zero-length datagram carries the file descriptors and tells us
                  * that we're done. */
                 if (n == 0) {
                         struct cmsghdr *found;
+                        unsigned n_fds = 0;
+
+                        found = cmsg_find(&mh, SOL_SOCKET, SCM_RIGHTS, CMSG_LEN(sizeof(int)));
```
Comment (poettering) [inline src/coredump/coredump.c]: this should be moved into the `if (first)` block below, no need to call this otherwise

File: src/coredump/coredump.c [hunk 30]
```diff
@@ -1087,40 +1096,67 @@ static int process_socket(int fd) {
...
+                                        /* This is the first message that carries file descriptors, maybe there will be
+                                         * one more that actually contains array of two descriptors. */
+                                        assert(input_fd < 0);
+
+                                        input_fd = *CMSG_TYPED_DATA(found, int);
+                                        first = false;
+
+                                        continue;
+                                } else {
+                                        /* This is zero length message but it has no file descriptor this is the protocol
```
Comment (poettering) [inline src/coredump/coredump.c]: this not entirely true, it could also have more than one fd. it has the wrong number, that's what is key here

File: src/coredump/coredump.c [hunk 31]
```diff
@@ -1087,40 +1096,67 @@ static int process_socket(int fd) {
                         goto finish;
                 }
 
-                /* The final zero-length datagram carries the file descriptor and tells us
+                /* The final zero-length datagram carries the file descriptors and tells us
                  * that we're done. */
                 if (n == 0) {
```
Comment (poettering) [inline src/coredump/coredump.c:1097]: so the logic is broken now, as you accept now that the first empty msg is received, and then some data blobs again, and then the second empty msg.

I think it would be much nicer if we would simply accept either 1 or 3 fds on a final zero length msg. That's perfectly compatible with the current logic, a natural extension, and allows no vagueness about the protocol.

File: src/coredump/coredump.c [hunk 32]
```diff
@@ -1674,17 +1724,12 @@ static int gather_pid_mount_tree_fd(const Context *context) {
...
-        r = wait_for_terminate_and_check("(sd-mount-tree-ns)", child, 0);
-        if (r < 0)
-                return log_error_errno(r, "Failed to wait for child: %m");
-        if (r != EXIT_SUCCESS)
-                return log_error_errno(SYNTHETIC_ERRNO(ECHILD), "Child died abnormally.");
-
         fd = receive_one_fd(pair[0], MSG_DONTWAIT);
         if (fd < 0)
-                return log_error_errno(fd, "Failed to receive mount tree: %m");
+                return log_error_errno(r, "Failed to receive mount tree: %m");
```
Comment (poettering) [inline src/coredump/coredump.c]: hmm, this should remain `fd`

File: src/coredump/coredump.c [hunk 33]
```diff
@@ -1736,11 +1781,9 @@ static int process_kernel(int argc, char* argv[]) {
                 if (r >= 0)
                         return 0;
 
-                r = gather_pid_mount_tree_fd(&context);
-                if (r < 0 && r != -EBADF)
+                r = gather_pid_mount_tree_fd(&context, &mount_tree_fd);
+                if (r < 0)
                         log_warning_errno(r, "Failed to access the mount tree of a container, ignoring: %m");
```
Comment (poettering) [inline src/coredump/coredump.c:1785]: you already log about all errors inside of gather_pid_mount_tree_fd(), hence this is strictly speaking duplicate logging.

i think it makes sense to keep a log message in place here however, if it tells us *new* stuff the original log messages inside of gather_pid_mount_tree_fd() didn't tell us yet. Specifically, it's the "ignoring" part which the function didn't mention. So maybe keep the log message mostly, but drop the %m (and change from log_warning_errno() to log_warning()).

that way, we will log about the error code once, and then log about the action we are taking because of it. (which is "no action")

File: src/coredump/coredump.c [hunk 34]
```diff
@@ -1628,42 +1664,56 @@ static int forward_coredump_to_container(Context *context) {
...
 #if !HAVE_DWFL_SET_SYSROOT
-        return -EBADF;
+        *ret_fd = -EOPNOTSUPP;
+        return 0;
 #endif
 
-        if (!arg_access_container)
-                return -EBADF;
+        if (!arg_enter_namespace) {
+                *ret_fd = -EHOSTDOWN;
```
Comment (poettering) [inline src/coredump/coredump.c:1675]: a debug log message would be good here btw

File: src/coredump/coredump.c [hunk 35]
```diff
@@ -1628,42 +1664,56 @@ static int forward_coredump_to_container(Context *context) {
...
-        pid_t child;
+        int r;
 
         assert(context);
+        assert(ret_fd);
 
         /* Don't bother preparing environment if we can't pass it to libdwfl. */
 #if !HAVE_DWFL_SET_SYSROOT
-        return -EBADF;
+        *ret_fd = -EOPNOTSUPP;
```
Comment (poettering) [inline src/coredump/coredump.c]: a debug log message would be good here

File: src/coredump/coredump.c [hunk 36]
```diff
@@ -1628,42 +1664,56 @@ static int forward_coredump_to_container(Context *context) {
...
+        if (!arg_enter_namespace) {
+                *ret_fd = -EHOSTDOWN;
+                return 0;
+        }
 
         if (socketpair(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0, pair) < 0)
                 return log_error_errno(errno, "Failed to create socket pair: %m");
 
-        r = namespace_open(context->pid,  NULL, &mntns_fd, NULL, NULL, &root_fd);
+        r = namespace_open(context->pid, NULL, &mntns_fd, NULL, NULL, &root_fd);
```
Comment (poettering) [inline src/coredump/coredump.c]: would be nice to prefix the `NULL` parameters with their argument names, i.e. `/* pidns_fd= */` and so on. You know the drill

File: src/coredump/coredump.c [hunk 37]
```diff
@@ -1628,42 +1664,56 @@ static int forward_coredump_to_container(Context *context) {
...
+                           /* n_except_fds= */ 0,
+                           FORK_RESET_SIGNALS|FORK_DEATHSIG_SIGKILL|FORK_LOG|FORK_WAIT,
+                           /* pidns_fd= */ -EBADF,
+                           mntns_fd,
+                           /* netns_fd= */ -EBADF,
+                           /* userns_fd= */ -EBADF,
+                           root_fd,
+                           NULL);
         if (r < 0)
                 return log_error_errno(r, "Failed to fork(): %m");
```
Comment (poettering) [inline src/coredump/coredump.c]: now that you use FORK_LOG, drop the log message here, it would be duplicative now. just do `return r` directly here

File: man/coredump.conf.xml (hunk 26 above)
Comment (msekletar) [reply man/coredump.conf.xml:116]: I mention PID namespace because this is what implementation checks for. We attempt coredump forwarding or gathering mount tree when crashed process ran in a different namespace than our own PID namespace.

https://github.com/systemd/systemd/blob/main/src/coredump/coredump.c#L1729

File: src/coredump/coredump.c (hunk 28 above)
Comment (msekletar) [reply src/coredump/coredump.c]: I am getting rid of this variable completely.

File: src/coredump/coredump.c (hunk 30 above)
Comment (msekletar) [reply src/coredump/coredump.c]: I will adjust the comment.

File: src/coredump/coredump.c (hunk 31 above)
Comment (msekletar) [reply src/coredump/coredump.c:1097]: But what we accept is one aspect, second is what we send. 

During package updates/downgrades we may run into situation when message is generated by one version (older/newer ?) and processed by another version because in the meantime systemd-coredump got replaced. To cope with this I send two messages (first with 1 fd and second with 2 fds) and when processing I allow for at most two zero-length messages but so far I didn't check whether there are no data message in between them (they shouldn't be).

**Comment by msekletar** [comment]
I've added two commits and rebase on top of today's main. @poettering PTAL. Btw, at this point I think we should just merge the PR and do any later fixups in another PR because this one is getting quite messy already.

**Comment by yuwata** [comment]
We do not accept PR that touches code in a commit and then touches again in a later commit to address requests...
Please address each request in the corresponding commit.

**Comment by poettering** [comment]
yes, please squash the fixes into the commits they are for. we want "perfect" PRs, that reflect logical steps, but not historical ones. i.e. commits should not fix up commits in the very same PR.

File: src/coredump/coredump.c [hunk 38]
```diff
@@ -856,10 +858,10 @@ static int submit_coredump(
...
         }
 
-        if (mount_tree_fd >= 0 && arg_access_container) {
-                r = setup_container_mount_tree(mount_tree_fd, &root);
-                if (r < 0)
-                        log_warning_errno(r, "Failed to setup container mount tree, ignoring: %m");
+        if (mount_tree_fd >= 0) {
+                r = attach_mount_tree(mount_tree_fd);
+                if (r >= 0)
+                        root = MOUNT_TREE_ROOT;
```
Comment (keszybz) [inline src/coredump/coredump.c]:
```
if (mount_tree_fd >= 0 &&
   attach_mount_tree(mount_tree_fd) >= 0)
      root = MOUNT_TREE_ROOT;
```
?

File: src/coredump/coredump.c [hunk 39]
```diff
@@ -782,30 +784,31 @@ static int change_uid_gid(const Context *context) {
...
 
-        r = mkdtemp_malloc("/tmp/systemd-coredump-root-XXXXXX", &root);
+        r = mount_setattr(mount_tree_fd, "", AT_EMPTY_PATH,
+                                &(struct mount_attr) {
+                                        .attr_set = MOUNT_ATTR_RDONLY|MOUNT_ATTR_NOSUID|MOUNT_ATTR_NODEV|MOUNT_ATTR_NOEXEC,
+                                        .propagation = MS_SLAVE,
+                                }, sizeof(struct mount_attr));
         if (r < 0)
-                return log_warning_errno(r, "Failed to create temporary directory: %m");
+                return log_warning_errno(r, "Failed to change properties mount tree: %m");
```
Comment (keszybz) [inline src/coredump/coredump.c]: Grammar? "Properties of"?

File: src/coredump/coredump.c [hunk 40]
```diff
@@ -1089,40 +1089,64 @@ static int process_socket(int fd) {
...
+                                        assert(input_fd < 0);
+
+                                        input_fd = *CMSG_TYPED_DATA(found, int);
+                                        first = false;
+
+                                        continue;
+                                }
+
+                                /* This is zero length message but it doesn't carry single descriptor this is the protocol
+                                 * violation so let's bail out. */
```
Comment (keszybz) [inline src/coredump/coredump.c]: I think that's two sentences pretending to be one.
Also, "a violation".

File: src/coredump/coredump.c [hunk 41]
```diff
@@ -1089,40 +1089,64 @@ static int process_socket(int fd) {
...
+                /* The final zero-length datagram carries the file descriptors and tells us
                  * that we're done. */
                 if (n == 0) {
                         struct cmsghdr *found;
 
+                        if (first) {
+                                found = cmsg_find(&mh, SOL_SOCKET, SCM_RIGHTS, CMSG_LEN(sizeof(int)));
+                                if (found) {
+                                        /* This is the first message that carries file descriptors, maybe there will be
+                                         * one more that actually contains array of two descriptors. */
```
Comment (keszybz) [inline src/coredump/coredump.c]: Also here, that's two sentences joined by a comma.

File: src/coredump/coredump.c [hunk 42]
```diff
@@ -2,11 +2,15 @@
...
 #include <errno.h>
 #include <stdio.h>
+#include <sys/mount.h>
 #include <sys/prctl.h>
 #include <sys/statvfs.h>
 #include <sys/auxv.h>
 #include <sys/xattr.h>
 #include <unistd.h>
+#if WANT_LINUX_FS_H
+#include <linux/fs.h>
```
Comment (keszybz) [inline src/coredump/coredump.c]: `#  include` please.

**Comment by Werkov** [comment]
Thanks for the cleanup/refresh @bluca; I can run cool [git-explode](https://github.com/aspiers/git-explode) on the branch now[^1] to visualize how it's structured:

```
* dbfdf12112 (topic11) coredump: fix line spacing
| * 7ebe71136e (topic12) analyze: don't use Yoda conditions
|/  
| * ad76f24a4f (topic13) analyze: modernize opening ELF binary a bit
|/  
| * 11338c997e (topic1) test: add test coverage for EnterNamespace=
|/  
| * fbf9c88916 (topic2) coredump: merge variable definitions
| | * ba72db36f7 (topic3) coredump: return correct error variable
| |/  
| * 7115274100 coredump: rework attaching container mount trees
|/  
| * 5f7b6f78f7 (topic7) coredump: use FORK_WAIT
| | * 4d88434595 (topic8) coredump: rename AccessContainer= to EnterNamespace=
| | * a1923d310b coredump: rework gather_pid_mount_tree_fd()
| | *-.   3c1f6bfe4b Merge commit '9369fffb4780bd9fef37ebd4a9fac978cfc8aec6'; commit 'cebe77b1b5c3bfe4b1c112a51042b31eba793d15' into topic8
| | |\ \  
| | |_|/  
| |/| |   
| * | | cebe77b1b5 (topic6) coredump: use FORK_LOG to get more precise logging
| * | | 7d2d5f5cad coredump: fix coding style
|/ / /  
| | * 9369fffb47 (topic5) coredump: get rid of redundant double space
| |/  
|/|   
| * 6a33660bb4 (topic4) coredump: use more appropriate return code
|/  
| * e733cc2f82 (topic9) coredump: store actual fd in appropriate variable
|/  
| * 08d028115b (topic10) coredump: check for and close unexpected FDs
|/  
*   feb9ccb56e Merge pull request #34633 from keszybz/sd-json-enum-formatting
```

Topic numbers are random (and not stable between runs), important are syntactic (in)dependencies between commits.
I'm posting it here for possibly more squashing which I attempted in [coredump-from-container-followups-squash](https://github.com/Werkov/systemd/tree/coredump-from-container-followups-squash) and easing of review. Newly, the deps decompose to:
```
* 9a4847170f (topic5) coredump: rename AccessContainer= to EnterNamespace=
* 10b48d0dfe coredump: rework gather_pid_mount_tree_fd()
*   334adc2524 Merge commit '0f1b98f1af319c67f21ee1c4c08feb46e0af9ee8' into topic5
|\  
| * 0f1b98f1af (topic4) coredump: use FORK_LOG and FORK_WAIT flags
* | cafd56d02d (topic3) coredump: use more appropriate return code
|/  
| * f6850b31a2 (topic6) coredump: store actual fd in appropriate variable
|/  
| * 9fccea8e34 (topic7) coredump: check for and close unexpected FDs
|/  
| * eeb71e4903 (topic8) coredump: rework attaching container mount trees
|/  
| * 99e1819d14 (topic9) analyze: don't use Yoda conditions
|/  
| * 7f37649b1d (topic10) analyze: modernize opening ELF binary a bit
|/  
| * e66249cdbd (topic1) coredump: fix line spacing
|/  
| * 251f7a1ffa (topic2) test: add test coverage for EnterNamespace=
|/  
*   feb9ccb56e Merge pull request #34633 from keszybz/sd-json-enum-formatting
```

The diff of endpoints (e9b019c8a39a50729aff7b9fa18396a7fc2f7fcf vs e73be6869dde1f8f581dbd784c8576005420e011) remains empty.

[^1]: The tool couldn't decompose yesterday's branch, hence the thank. (Also for possible curious users, I'm using patched version including few unmerged git-explode & git-deps PRs).

File: test/units/TEST-74-AUX-UTILS.coredump.sh [hunk 43]
```diff
@@ -225,3 +227,32 @@ systemd-run -t --property CoredumpFilter=default ls /tmp
 (! coredumpctl dump --output=/dev/null --output=/dev/null "$CORE_TEST_BIN")
 (! coredumpctl debug --debugger=/bin/false)
 (! coredumpctl debug --debugger=/bin/true --debugger-arguments='"')
+
+# Test for EnterNamespace= feature
+if pkgconf --atleast-version 0.192 libdw ; then
+    # dwfl_set_sysroot() is supported only in libdw-0.192 or newer.
+    cat > "$MAKE_STACKTRACE_DUMP" <<END
```
Comment (keszybz) [inline test/units/TEST-74-AUX-UTILS.coredump.sh]: No space after `>` please.

File: test/units/TEST-74-AUX-UTILS.coredump.sh [hunk 44]
```diff
@@ -225,3 +227,32 @@ systemd-run -t --property CoredumpFilter=default ls /tmp
...
+EOF
+$CORE_STACKTRACE_TEST_BIN
+END
+    chmod +x "$MAKE_STACKTRACE_DUMP"
+
+    mkdir -p /run/systemd/coredump.conf.d/
+    printf '[Coredump]\nEnterNamespace=no' >/run/systemd/coredump.conf.d/99-enter-namespace.conf
+
+    unshare --pid --fork --mount-proc --mount --uts --ipc --net /bin/bash -c "$MAKE_STACKTRACE_DUMP" || :
+    coredumpctl -1 info "$CORE_STACKTRACE_TEST_BIN" | grep -zvqE 'baz.*bar.*foo'
```
Comment (keszybz) [inline test/units/TEST-74-AUX-UTILS.coredump.sh]: I think this is racy. The journal might be slower in writing out the log and then this `coredumpctl` will fail. Maybe insert a sleep or check somehow?

File: test/units/TEST-74-AUX-UTILS.coredump.sh [hunk 45]
```diff
@@ -225,3 +227,32 @@ systemd-run -t --property CoredumpFilter=default ls /tmp
...
+
+    printf '[Coredump]\nEnterNamespace=yes' >/run/systemd/coredump.conf.d/99-enter-namespace.conf
+    unshare --pid --fork --mount-proc --mount --uts --ipc --net /bin/bash -c "$MAKE_STACKTRACE_DUMP" || :
```
Comment (keszybz) [inline test/units/TEST-74-AUX-UTILS.coredump.sh:254]: Here too.

**Review by keszybz — CHANGES_REQUESTED** [review]
Looks good in general. Some nitpicks.

File: src/coredump/coredump.c [hunk 46]
```diff
@@ -1086,40 +1086,65 @@ static int process_socket(int fd) {
...
+                                        first = false;
+
+                                        continue;
+                                }
+
+                                /* This is zero length message but it doesn't carry a single descriptor.
+                                 * This is a protocol violation so let's bail out. */
+                                cmsg_close_all(&mh);
+                                r = log_error_errno(SYNTHETIC_ERRNO(EBADMSG),
+                                                        "Received zero length message with no file descriptor.");
```
Comment (poettering) [inline src/coredump/coredump.c]: "no" is misleading. it might also carry more than one, in which case we'd hit this error path. maybe say "no or more than one"

File: src/coredump/coredump.c [hunk 47]
```diff
@@ -1086,40 +1086,65 @@ static int process_socket(int fd) {
...
+                        found = cmsg_find(&mh, SOL_SOCKET, SCM_RIGHTS, (socklen_t) -1);
+                        cmsg_close_all(&mh);
+
+                        if (!found)
+                                /* Hence we either have no FDs which is OK and we can break. */
+                                break;
+
+                        /* Or we have some other number of FDs and somebody is playing games with us. */
+                        r = log_error_errno(SYNTHETIC_ERRNO(EBADMSG), "Received unexpected file descriptors.");
+                        goto finish;
```
Comment (poettering) [inline src/coredump/coredump.c:1152]: I mentioned this before: but the protocol is really weird, because it allows sending data, then sending the first trailing datagram, and then more data, and then the 2nd trailing datagram.

that's really strange and should be refused. (and it's aso different from the status quo ante, where the conneciton would be closed the instant the fd msg was received).

File: src/coredump/coredump.c [hunk 48]
```diff
@@ -1086,40 +1086,65 @@ static int process_socket(int fd) {
...
```
Comment (poettering) [inline src/coredump/coredump.c:1153]: hmm, thinking about this more. If the protocol is extended here, I think it would make a ton of sense to extend it one step further at the same time, so that we do not have to go through the same dance a third time. Specifically, I think a 3rd fd should be passed along: the pidfd referencing the crashed process. note however, that old kernels do not support pidfds, hence it needs to be somewhat lenient on this, and support either 2 or 3 fds.

File: src/coredump/coredump.c (hunk 22 above)
Comment (poettering) [reply src/coredump/coredump.c:1681]: not addressed.

File: src/coredump/coredump.c [hunk 49]
```diff
@@ -1652,26 +1656,34 @@ static int forward_coredump_to_container(Context *context) {
...
-        /* Don't bother preparing environment if we can't pass it to libdwfl. */
-#if !HAVE_DWFL_SET_SYSROOT
-        return -EOPNOTSUPP;
-#endif
-
-        if (!arg_access_container)
-                return -EOPNOTSUPP;
+        if (!arg_access_container) {
+                *ret_fd = -EHOSTDOWN;
+                log_debug_errno(SYNTHETIC_ERRNO(EHOSTDOWN), "EnterNamespace=no so we won't use mount tree of the crashed process for generating backtrace.");
```
Comment (poettering) [inline src/coredump/coredump.c]: use log_debug() if you are you are making up a synthetic error code anyway.

File: src/coredump/coredump.c [hunk 50]
```diff
@@ -1652,26 +1656,34 @@ static int forward_coredump_to_container(Context *context) {
         return 0;
 }
 
-static int gather_pid_mount_tree_fd(const Context *context) {
-        _cleanup_close_ int mntns_fd = -EBADF, root_fd = -EBADF;
+static int gather_pid_mount_tree_fd(const Context *context, int *ret_fd) {
+        /* Don't bother preparing environment if we can't pass it to libdwfl. */
+#if !HAVE_DWFL_SET_SYSROOT
+        *ret_fd = -EOPNOTSUPP;
+        log_debug_errno(SYNTHETIC_ERRNO(EOPNOTSUPP), "dwfl_set_sysroot() is not supported.");
```
Comment (poettering) [inline src/coredump/coredump.c]: use plain log_debug() if you are making up an error here and are not interested in the return value of log_debug_errno()

File: src/coredump/coredump.c [hunk 51]
```diff
@@ -1685,9 +1697,10 @@ static int gather_pid_mount_tree_fd(const Context *context) {
                            /* netns_fd= */ -EBADF,
                            /* userns_fd= */ -EBADF,
                            root_fd,
-                           &child);
+                           NULL);
```
Comment (poettering) [inline src/coredump/coredump.c:1702]: this should still be merged into previous commit

File: src/coredump/coredump.c [hunk 52]
```diff
@@ -1685,9 +1697,10 @@ static int gather_pid_mount_tree_fd(const Context *context) {
...
         if (r < 0)
                 return r;
+
```
Comment (poettering) [inline src/coredump/coredump.c]: please drop this empty line

File: src/coredump/coredump.c [hunk 53]
```diff
@@ -1764,11 +1779,9 @@ static int process_kernel(int argc, char* argv[]) {
...
                         return 0;
 
-                r = gather_pid_mount_tree_fd(&context);
-                if (r < 0 && r != -EOPNOTSUPP)
-                        log_warning_errno(r, "Failed to access the mount tree of a container, ignoring: %m");
-                else
-                        mount_tree_fd = r;
+                r = gather_pid_mount_tree_fd(&context, &mount_tree_fd);
+                if (r < 0)
+                        log_warning("Failed to access the mount tree of a container, ignoring.");
```
Comment (poettering) [inline src/coredump/coredump.c]: please output the error with %m

**Review by poettering — CHANGES_REQUESTED** [review]

File: src/coredump/coredump.c (hunk 48 above)
Comment (bluca) [reply src/coredump/coredump.c:1153]: This goes beyond fixing some style and minor issues. This requires more in-depth look and I don't have the time for it. Is this something that needs to be done befor RC1 or can it wait for Michal to be back?

File: src/coredump/coredump.c (hunk 47 above)
Comment (poettering) [reply src/coredump/coredump.c:1152]: i.e. refuse any data to be passed through once the first sentinel message has been seen

File: src/coredump/coredump.c (hunk 48 above)
Comment (poettering) [reply src/coredump/coredump.c:1153]: yes, it touches the protocol, I think this should be in rc1. does not have to be in this PR though, but I think it's crucial, because we go for pidfds everywhere, and it would suck if we have to do another iteration of this messy protocol augmenting again

Comment (bluca) [reply src/coredump/coredump.c:1153]: Ok then we can keep the issue open with rc-blocker but let's get this PR merged so that the majority of other issues are solved, including the renaming. I'll link this comment in the issue.

**Comment by poettering** [comment]
i'd prefer if the issue with non-empty message after the first sentinel would be fixed right-away in this PR, but I guess i am fine if that is done in a separate PR too. it's a trivial fix though: just fail the connection when a non-zero datagram is received when "first" is already false.

**Comment by msekletar** [comment]
> i'd prefer if the issue with non-empty message after the first sentinel would be fixed right-away in this PR, but I guess i am fine if that is done in a separate PR too. it's a trivial fix though: just fail the connection when a non-zero datagram is received when "first" is already false.

I will submit it as a separate PR.

**Comment by msekletar** [comment]
> I will submit it as a separate PR.

Maybe something like this #34945 would be enough.

@poettering PTAL.

Btw, I will rebase that PR once this one is merged.
