### PR TITLE
network: increase MTU if VLAN= or MACVLAN= requests higher value

### LINKED ISSUE #5972: systemd-networkd fails to bring up netdev if an MTUBytes is specified
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 226
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Gentoo

### In case of bug report: Expected behaviour you didn't see

> VLAN is not created

### In case of bug report: Unexpected behaviour you saw

> mei 15 21:53:53 7of9 systemd[1]: Started Network Service.
mei 15 21:53:53 7of9 systemd-networkd[831]: enp3s0f1: Configured
mei 15 21:53:53 7of9 systemd-networkd[831]: enp3s0f0: enp3s0f0        : could not join netdev: Invalid argument
mei 15 21:53:53 7of9 systemd-networkd[831]: enp3s0f0: Failed

### In case of bug report: Steps to reproduce the problem

> Created the following netdev:
[NetDev]
Description=XS4all Internet VLAN 6
Name=xs4all_vlan6
Kind=vlan
MTUBytes=1508

[VLAN]
Id=6

this should create a vlan with an MTU of 1508. However the previous output already seen, it refuses to work. Removing the MTUBytes altogether brings up the device. Manually then doing ip link set vlan_6 mtu 1508 works as expected.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #5972.

### CODE REVIEW

**Comment by yuwata** [comment]
@ssahani and @oliv3r PTAL.

File: src/network/networkd-network.c [hunk 1]
```diff
@@ -97,6 +97,25 @@ void network_apply_anonymize_if_set(Network *network) {
...
+
+        HASHMAP_FOREACH(dev, network->stacked_netdevs, i) {
+                if (dev->kind == NETDEV_KIND_VLAN && dev->mtu > 0)
+                        /* See vlan_dev_change_mtu() in kernel.
+                         * Note that the additional 4bytes may not be necessary for all devices. */
+                        mtu = dev->mtu + 4;
+
+                if (dev->kind == NETDEV_KIND_MACVLAN && dev->mtu > 0)
+                        /* See macvlan_change_mtu() in kernel. */
+                        mtu = dev->mtu;
```
Comment (poettering) [inline src/network/networkd-network.c:190]: shouldn't the mtu be determined as the largest of the mtus of the stacked devices? right now the last device in the list wins...

File: src/network/networkd-network.h [hunk 2]
```diff
@@ -223,6 +223,7 @@ struct Network {
 
         struct ether_addr *mac;
         uint32_t mtu;
+        uint32_t min_mtu;
```
Comment (poettering) [inline src/network/networkd-network.h]: i wonder if "stacked_netdevs_mtu" wouldn't be a better name here?

File: src/network/networkd-link.c [hunk 3]
```diff
@@ -3081,8 +3081,9 @@ static int link_configure(Link *link) {
                         return r;
         }
 
-        if (link->network->mtu > 0) {
-                r = link_set_mtu(link, link->network->mtu);
+        if (link->network->mtu > 0 ||
+            (link->network->min_mtu > 0 && link->network->min_mtu > link->mtu)) {
```
Comment (poettering) [inline src/network/networkd-link.c]: hmm, not sure i follow, but why conditoinalize the right-hand side of `&&` only on min_mtu > 0? shouldn't it be this:

```
mtu = MAX(link->network->mtu, link->network->min_mtu);
if (mtu > link->mtu) {
        …
```

but i must admit I don't fully grok the intention here

File: src/network/networkd-network.c (hunk 1 above)
Comment (yuwata) [reply src/network/networkd-network.c:190]: Ouch!

**Comment by yuwata** [comment]
Updated. PTAL. Main changes are the following:
- `min_mtu` is renamed to `stacked_netdevs_mtu`.
- Fix invalid logic of detecting the minimum required mtu.
- Add comments to reply https://github.com/systemd/systemd/pull/11807#discussion_r259863105.

File: src/network/networkd-network.c [hunk 4]
```diff
@@ -150,10 +169,21 @@ static int network_verify(Network *network) {
         if (network->ip_masquerade)
                 network->ip_forward |= ADDRESS_FAMILY_IPV4;
 
-        if (network->mtu > 0 && network->dhcp_use_mtu) {
-                log_warning("%s: MTUBytes= in [Link] section and UseMTU= in [DHCP] section are set. "
-                            "Disabling UseMTU=.", network->filename);
-                network->dhcp_use_mtu = false;
+        network_set_stacked_netdevs_mtu(network);
```
Comment (keszybz) [inline src/network/networkd-network.c]: `stacked_netdevs_mtu` is only used internally in this function. I think it's much nicer to not make it a "global" state in the Network structure, but simply have `network_set_stacked_netdevs_mtu` return it.

File: src/network/networkd-network.c [hunk 5]
```diff
@@ -150,10 +169,21 @@ static int network_verify(Network *network) {
...
+
+        if (network->mtu > 0) {
+                if (network->dhcp_use_mtu) {
+                        log_warning("%s: MTUBytes= in [Link] section and UseMTU= in [DHCP] section are set. "
+                                    "Disabling UseMTU=.", network->filename);
+                        network->dhcp_use_mtu = false;
+                }
+
+                if (network->mtu < network->stacked_netdevs_mtu) {
```
Comment (keszybz) [inline src/network/networkd-network.c]: If we know that the stacked devices require certain MTU, shouldn't we set it, even if this Network has mtu==0 ? I.e. I think this `if` should not be moved one level up, and not be under `if (network->mtu > 0)`.

File: src/network/networkd-network.c [hunk 6]
```diff
@@ -97,6 +97,25 @@ void network_apply_anonymize_if_set(Network *network) {
...
+        NetDev *dev;
+        Iterator i;
+
+        HASHMAP_FOREACH(dev, network->stacked_netdevs, i) {
+                if (dev->kind == NETDEV_KIND_VLAN && dev->mtu > 0 && dev->mtu + 4 > mtu)
+                        /* See vlan_dev_change_mtu() in kernel.
+                         * Note that the additional 4bytes may not be necessary for all devices. */
+                        mtu = dev->mtu + 4;
+
+                if (dev->kind == NETDEV_KIND_MACVLAN && dev->mtu > mtu)
```
Comment (keszybz) [inline src/network/networkd-network.c]: `else if`

File: src/network/networkd-network.c [hunk 7]
```diff
@@ -97,6 +97,25 @@ void network_apply_anonymize_if_set(Network *network) {
...
+static void network_set_stacked_netdevs_mtu(Network *network) {
+        uint32_t mtu = 0;
+        NetDev *dev;
+        Iterator i;
+
+        HASHMAP_FOREACH(dev, network->stacked_netdevs, i) {
+                if (dev->kind == NETDEV_KIND_VLAN && dev->mtu > 0 && dev->mtu + 4 > mtu)
+                        /* See vlan_dev_change_mtu() in kernel.
+                         * Note that the additional 4bytes may not be necessary for all devices. */
+                        mtu = dev->mtu + 4;
```
Comment (keszybz) [inline src/network/networkd-network.c]: I'd drop the `&& dev->mtu + 4 > mtu` part above, and simply say `mtu = MAX(mtu, dev->mtu + 4)` here, less repeats.

File: src/network/networkd-network.c [hunk 8]
```diff
@@ -150,10 +169,21 @@ static int network_verify(Network *network) {
...
+                if (network->dhcp_use_mtu) {
+                        log_warning("%s: MTUBytes= in [Link] section and UseMTU= in [DHCP] section are set. "
+                                    "Disabling UseMTU=.", network->filename);
+                        network->dhcp_use_mtu = false;
+                }
+
+                if (network->mtu < network->stacked_netdevs_mtu) {
+                        log_notice("%s: MTUBytes= must be equal or larger than vlan's MTUBytes= plus 4bytes or macvlan's MTUBytes=, "
+                                   "increasing MTUBytes= to %"PRIu32".",
+                                   network->filename, network->stacked_netdevs_mtu);
```
Comment (keszybz) [inline src/network/networkd-network.c]: What about having `network_set_stacked_netdevs_mtu` also return the stacked netdev identifier, and here saying something like:
`%s: bumping MTUBytes= from %"PRIu32" to %"PRIu32" because of stacked device %s", ...`. Then we don't need to go into the details of the calculation, and give more info to the user why the bump happened.

File: src/network/networkd-network.h [hunk 9]
```diff
@@ -223,6 +223,7 @@ struct Network {
 
         struct ether_addr *mac;
         uint32_t mtu;
+        uint32_t stacked_netdevs_mtu;
```
Comment (keszybz) [inline src/network/networkd-network.h]: I don't think we need this.

File: src/network/networkd-network.c (hunk 5 above)
Comment (keszybz) [reply src/network/networkd-network.c]: Oh, I see this is done in a way in patch 2/3. But then this means that network->mtu is bumped in some cases, but not in others. It seems nicer to simply bump it always, so that we don't have to remember to do MAX(network->mtu, network->stacked_mtu)` everywhere.

Comment (yuwata) [reply src/network/networkd-network.c]: If `MTUBytes=` is not specified in .network file, then `network->mtu` is `0`, and in that case, `networkd` should not change mtu if device's mtu is already large enough.

Note that some drivers restart interfaces if mtu is changed. I hope `networkd` can handle that, but I think we should not change mtu if not necessary.

Without changing the current logic, how about introducing a boolean flag e.g. `network->force_change_mtu` which indicates `MTUBytes=` is specified or not? Then, we can drop `stacked_netdevs_mtu` from `Network`.

**Comment by yuwata** [comment]
@keszybz Thank you for the review. I've force-pushed an updated version. The logic is not changed, but I hope the readability of the code is now better than previous. PTAL.

**Comment by poettering** [comment]
looks good to me. but i'll leave this to @keszybz to merge, since he had more questions.
