### PR TITLE
core: delay logging the taint string until after basic.target is reached

### LINKED ISSUE #7683: system incorrectly marked as tainted with var-run-bad if /var is on a separate partition
### Submission type

 - Bug report

### systemd version the issue has been seen with

v236

### Used distribution

Debian

On a system with /var on a separate partition, the system is incorrectly marked as tainted with
```System is tainted: var-run-bad```

The unmounted /var directory is empty so I guess systemd applies this check before /var has been mounted, which contains a proper /var/run → /run symlink

### PR DESCRIPTION
**Pull request by keszybz**
This happens to be the same moment as when we send READY=1 in the user
instance, so let's piggy-back on this.

Fixes #7683.

### CODE REVIEW

File: src/core/manager.c [hunk 1]
```diff
@@ -3163,17 +3183,21 @@ void manager_check_finished(Manager *m) {
...
+                        u = manager_get_unit(m, SPECIAL_BASIC_TARGET);
+                        if (u && !u->job) {
+                                sd_notifyf(false,
+                                           "READY=1\n"
+                                           "STATUS=Reached " SPECIAL_BASIC_TARGET ".");
+                        }
+                } else
+                        log_taint_string(m);
+
+                m->ready_sent = true;
```
Comment (yuwata) [inline src/core/manager.c]: Should not set this here for system manager, that is `! MANAGER_IS_USER(m)`. If set this here, then `READY=1` notification will not be sent.

**Comment by keszybz** [comment]
Good catch, I log the logic wrong. Please see this version.

**Comment by yuwata** [comment]
Not tested, but looks good to me now. I will test this later.
