### PR TITLE
network: make prefixstable mode of IPv6Token= can be applied any received prefixes

### LINKED ISSUE #4625: Request support Semantically Opaque Interface Identifiers with IPv6 (SLAAC) RFC 7217
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd 231
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> …

#### Additional Information
RFC 4862 defines how to create an GUA (Global Unique Address) via SLAAC. But a GUA based on MAC address (EUI64) has limitations as referenced in RFC 7707, and a new unguessable method has been created via RFC 7217. iOS 10, and Mac OSX 10.12 support RFC 7217.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #4625.

cc @ssahani and @kpfleming.

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@yuwata any chance of getting this merged?

File: src/network/networkd-ndisc.c [hunk 1]
```diff
@@ -1176,29 +1176,37 @@ int config_parse_address_generation_type(
...
-        else if ((p = startswith(rvalue, "prefixstable:")))
+        if ((p = startswith(rvalue, "prefixstable"))) {
                 token->address_generation_type = IPV6_TOKEN_ADDRESS_GENERATION_PREFIXSTABLE;
-        else {
+                if (*p == ':')
+                        p++;
+                else
+                        p = NULL;
+        } else {
                 token->address_generation_type = IPV6_TOKEN_ADDRESS_GENERATION_STATIC;
```
Comment (ssahani) [inline src/network/networkd-ndisc.c:1192]: Can you give a example of the format which is we trying to parse ?

Comment (yuwata) [reply src/network/networkd-ndisc.c:1192]: Examples:
```
IPv6Token=::1a:2b:3c:4d
IPv6Token=static:::1a:2b:3c:4d   <-- this is equivalent to the first one.
IPv6Token=prefixstable           <-- this is new.
IPv6Token=prefixstable:2002:da8:1::
```

Comment (SoapGentoo) [reply src/network/networkd-ndisc.c:1192]: I'm specifically looking for `IPv6Token=prefixstable`, because I get my prefix from the router/ISP

File: src/network/networkd-ndisc.c [hunk 2]
```diff
@@ -1176,29 +1176,37 @@ int config_parse_address_generation_type(
...
+                if (token->address_generation_type == IPV6_TOKEN_ADDRESS_GENERATION_STATIC &&
+                    in_addr_is_null(AF_INET6, &buffer)) {
+                        log_syntax(unit, LOG_WARNING, filename, line, 0,
+                                   "IPv6 address in %s= cannot be the ANY address, ignoring assignment: %s",
+                                   lvalue, rvalue);
+                        return 0;
+                }
+                token->prefix = buffer.in6;
+        } else
+                token->prefix = (struct in6_addr) {};
```
Comment (ssahani) [inline src/network/networkd-ndisc.c]: Won't be this simper by this.
```
-- i/src/network/networkd-ndisc.c
+++ w/src/network/networkd-ndisc.c
@@ -1158,6 +1158,7 @@ int config_parse_address_generation_type(
 
         _cleanup_free_ IPv6Token *token = NULL;
         union in_addr_union buffer;
+        bool empty_prefix = false;
         Network *network = data;
         const char *p;
         int r;
@@ -1180,25 +1181,30 @@ int config_parse_address_generation_type(
                 token->address_generation_type = IPV6_TOKEN_ADDRESS_GENERATION_STATIC;
         else if ((p = startswith(rvalue, "prefixstable:")))
                 token->address_generation_type = IPV6_TOKEN_ADDRESS_GENERATION_PREFIXSTABLE;
-        else {
+        else if ((p = startswith(rvalue, "prefixstable"))) {
+                token->address_generation_type = IPV6_TOKEN_ADDRESS_GENERATION_PREFIXSTABLE;
+                empty_prefix = true;
+        } else {
                 token->address_generation_type = IPV6_TOKEN_ADDRESS_GENERATION_STATIC;
                 p = rvalue;
         }
 
-        r = in_addr_from_string(AF_INET6, p, &buffer);
-        if (r < 0) {
-                log_syntax(unit, LOG_WARNING, filename, line, r,
-                           "Failed to parse IPv6 %s, ignoring: %s", lvalue, rvalue);
-                return 0;
-        }
+        if (!empty_prefix) {
+                r = in_addr_from_string(AF_INET6, p, &buffer);
+                if (r < 0) {
+                        log_syntax(unit, LOG_WARNING, filename, line, r,
+                                   "Failed to parse IPv6 %s, ignoring: %s", lvalue, rvalue);
+                        return 0;
+                }
 
-        if (in_addr_is_null(AF_INET6, &buffer)) {
-                log_syntax(unit, LOG_WARNING, filename, line, 0,
-                           "IPv6 %s cannot be the ANY address, ignoring: %s", lvalue, rvalue);
-                return 0;
-        }
+                if (in_addr_is_null(AF_INET6, &buffer)) {
+                        log_syntax(unit, LOG_WARNING, filename, line, 0,
+                                   "IPv6 %s cannot be the ANY address, ignoring: %s", lvalue, rvalue);
+                        return 0;
+                }
 
 
-        token->prefix = buffer.in6;
+                token->prefix = buffer.in6;
+        } else
+                token->prefix = (struct in6_addr) {};
```

Comment (yuwata) [reply src/network/networkd-ndisc.c]: It should work. But I do not see any significant difference to the current code, though...
BTW, I notice that it is not necessary to fill `token->prefix` with zero when `IPv6Token=prefixstable`, as it is already initialized in `ipv6token_new()`. I will update that.

File: man/systemd.network.xml [hunk 3]
```diff
@@ -408,36 +408,37 @@
...
+            duplicate (in use by another node on the link), then this mode will fail to provide an
+            address for that prefix. If an IPv6 address without mode is specified, then
+            <literal>static</literal> mode is assumed.</para>
+            <para>When the mode is set to <literal>prefixstable</literal> the
+            <ulink url="https://tools.ietf.org/html/rfc7217">RFC 7217</ulink> algorithm for generating
+            interface identifiers will be used. This mode can optionally take an IPv6 address separated
+            with a colon (<literal>:</literal>). If an IPv6 address is specified, then an interface
+            identifier is generated only when a prefix received in an RA message matches the supplied
+            address.</para>
+            <para>If no address generation mode is specified (which is the default), or a receivd
```
Comment (keszybz) [inline man/systemd.network.xml]: "received"

File: man/systemd.network.xml [hunk 4]
```diff
@@ -408,36 +408,37 @@
...
-            Note that the <constant>prefixstable</constant> algorithm includes both the interface's name and
-            MAC address in the hash used to compute the interface identifier, so if either of those are changed the resulting
-            interface identifier (and address) will change, even if the prefix received in the RA message has not changed.
-
-            Note that if multiple <constant>prefixstable</constant> IPv6Token variables are supplied with addresses that
-            match a prefix received in an RA message, only the first one will be used to generate addresses.
-            </para>
+            <para>Specifies an optional address generation mode for the Stateless Address
+            Autoconfiguration (SLAAC). Supported modes are <literal>prefixstable</literal> and
+            <literal>static</literal>.</para>
```
Comment (keszybz) [inline man/systemd.network.xml:413]: Maybe add empty lines between paras...

File: man/systemd.network.xml [hunk 5]
```diff
@@ -408,36 +408,37 @@
...
+            interface identifiers will be used. This mode can optionally take an IPv6 address separated
+            with a colon (<literal>:</literal>). If an IPv6 address is specified, then an interface
+            identifier is generated only when a prefix received in an RA message matches the supplied
+            address.</para>
+            <para>If no address generation mode is specified (which is the default), or a receivd
+            prefix does not match any of the addresses provided in <literal>prefixstable</literal>
+            mode, then the EUI-64 algorithm will be used to form an interface identifier for that
+            prefix. This mode is also SLAAC, but with a potentially stable interface identifier which
+            does not directly map to the interface's hardware address.</para>
+            <para>Note that the <literal>prefixstable</literal> algorithm uses both the interface's
```
Comment (keszybz) [inline man/systemd.network.xml]: "interface's name" → "interface name"

File: man/systemd.network.xml [hunk 6]
```diff
@@ -408,36 +408,37 @@
...
+            name and MAC address in the hash used to compute the interface identifier, so if either of
```
Comment (keszybz) [inline man/systemd.network.xml]: in the hash → as input to the hash

File: src/network/networkd-ndisc.c (hunk 1 above)
Comment (keszybz) [reply src/network/networkd-ndisc.c:1192]: It's be great to add this example as `<example>` in the man page...

File: src/network/networkd-ndisc.c [hunk 7]
```diff
@@ -1176,30 +1176,37 @@ int config_parse_address_generation_type(
...
 
-        if ((p = startswith(rvalue, "static:")))
-                token->address_generation_type = IPV6_TOKEN_ADDRESS_GENERATION_STATIC;
-        else if ((p = startswith(rvalue, "prefixstable:")))
+        if ((p = startswith(rvalue, "prefixstable"))) {
                 token->address_generation_type = IPV6_TOKEN_ADDRESS_GENERATION_PREFIXSTABLE;
-        else {
+                if (*p == ':')
+                        p++;
+                else
```
Comment (keszybz) [inline src/network/networkd-ndisc.c]: Hmm, so if I specify "IPv6Token=prefixstableasdfasdfasdf" then it will be interpreted as "prefixstable". I think this needs to check that `!*p` here.

**Review by keszybz — CHANGES_REQUESTED** [review]
Looks nice, some minor comments.

File: src/network/networkd-ndisc.c (hunk 7 above)
Comment (ssahani) [reply src/network/networkd-ndisc.c]: This does not a separate. It can be added there itself. Hence it is reductant

**Comment by yuwata** [comment]
@keszybz Thank you for the review. Updated. Now all your comments are addressed. Setting the green label.

**Comment by keszybz** [comment]
LGTM.

**Comment by disich** [comment]
Trying to use sytemd-249 and setting IPv6Token=prefixstable.
However, this address is not the same as what I get by directly setting addr_gen_mode=2 and the specifying stable_secret with sysctl. Additionally 'ip addr show' does not report this address as stable-privacy. Is there a way for me to specify stable_secret while using systemd-networkd? Is there a retain the stable-privacy address as generated by the kernel.

**Comment by yuwata** [comment]
@disich I guess `IPv6LinkLocalAddressGenerationMode=stable-privacy` and `IPv6StableSecretAddress=` suffices what you want.

**Comment by disich** [comment]
@yuwata 
I am using these already but it only produces a stable-privacy link local address (fe80::) for me. The link local address using systemd-networkd is identical to what kernel generates by directly setting the parameters with sysctl.
However, for global address based on RA:
Looking into the systemd-249 code (my first attempt to understand this code), it appears /etc/machine-id is used.
Ref: networkd-ndisc.c in make_stableprivate_address.
r = sd_id128_get_machine_app_specific(NDISC_APP_ID, &secret_key);).
eventually sd_id128_get_machine reads /etc/machine-id.
Is this reading correct? Can we have an option that will generate global stable-privacy address as the kernel would.

**Comment by yuwata** [comment]
@disich Right. The `IPv6Token=prefixstable` does NOT mean the generated address is the same as the one by kernel.
The RFC allows to use arbitrary hash func to generate the address.

**Comment by disich** [comment]
@yuwata : Thanks, Agree thats its not about RFC compliance. Its about how stable my machine-id will be if we migrate to another linux distribution. We wanted to have the stable-privacy address to be constant even if we change distribution. So I was planning to hash the serial number of our embedded device (or something similar) and specify it as a stable-secret. A new ehancement in systemd-networkd which lets me specify stable secret for global ipv6 address would be awesome enhancement.
In parallel, I will check how we can keep our machine-id constant even if we migrate distributions.

**Comment by yuwata** [comment]
@disich Yeah. As you can see, the address is generated with
1. machine-ID
2. interface name
3. prefix
4. (and internal counter)

So, keeping the same machine-ID and interface name should be basically enough when changing distribution.

**Comment by disich** [comment]
@yuwata Appreciate you looking into. I think this is good for most but not for systems which deploy redundancy.
Our device is in a chassis with cards having 1:1 redundancy. Till now we only support eui64 so they get the same RA derived IP (they share same MAC but only Active brings up its network interface). However, they do not share the same machine-id. So this will cause them to get a different stable-privacy address.
Do you think the community may be willing to take up an enhancement to add a config file parameter where we can specify the stable_secret (instead of machine-id). Or provide an option where we can use this functionality from the kernel. Currently this is already allowed but only for link local address (using IPv6LinkLocalAddressGenerationMode).

**Comment by yuwata** [comment]
@disich Let's discuss on #21345.
