### PR TITLE
When mangling names, optionally emit a warning

### LINKED ISSUE #8302: systemctl: complain if unit name mangling is used
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

> archlinux, centos7

### In case of bug report: Expected behaviour you didn't see

> instance units unescape the instance name correctly when using `%I`

### In case of bug report: Unexpected behaviour you saw

> instance units replace `-` characters in the instance name with `/` when using `%I`

### In case of bug report: Steps to reproduce the problem

> Create an instance unit that uses `%I`
> Pass an instance name using a path like `foo-bar`
> `%I` will be incorrectly unescaped to `foo/bar`

[See this gist](https://gist.github.com/zfjagann/adfe79645837169fbf09fb40066b15ab)

This works, however if you run the instance name through `systemd-escape` first, which leads me to believe that instance names aren't being escaped in the same way.

### PR DESCRIPTION
**Pull request by keszybz**
The warning is not emitted for absolute paths like /dev/sda or /home, which are
converted to .device and .mount unit names without any fuss.

Most of the time it's unlikely that users use invalid unit names on purpose,
so let's warn them. Warnings are silenced when `--quiet` is used.

```console
$ build/systemctl show -p Id hello@foo-bar/baz
Invalid unit name "hello@foo-bar/baz" was escaped as "hello@foo-bar-baz" (maybe you should use systemd-escape?)
Id=hello@foo-bar-baz.service

$ build/systemd-run --user --slice foo-bar/baz --unit foo-bar/foo true
Invalid unit name "foo-bar/foo" was escaped as "foo-bar-foo" (maybe you should use systemd-escape?)
Invalid unit name "foo-bar/baz" was escaped as "foo-bar-baz" (maybe you should use systemd-escape?)
Running as unit: foo-bar-foo.service
```

Fixes #8302.

### CODE REVIEW

File: src/basic/unit-name.h [hunk 1]
```diff
@@ -68,14 +68,14 @@ int unit_name_from_path_instance(const char *prefix, const char *path, const cha
...
 
 typedef enum UnitNameMangle {
-        UNIT_NAME_NOGLOB,
-        UNIT_NAME_GLOB,
+        UNIT_NAME_MANGLE_GLOB = 1,
+        UNIT_NAME_MANGLE_WARN = 2,
 } UnitNameMangle;
 
-int unit_name_mangle_with_suffix(const char *name, UnitNameMangle allow_globs, const char *suffix, char **ret);
+int unit_name_mangle_with_suffix(const char *name, UnitNameMangle options, const char *suffix, char **ret);
```
Comment (poettering) [inline src/basic/unit-name.h]: why name this "options", rather than "flags", like we usually do?

File: src/basic/unit-name.c [hunk 2]
```diff
@@ -644,13 +649,15 @@ int unit_name_mangle_with_suffix(const char *name, UnitNameMangle allow_globs, c
         if (!s)
                 return -ENOMEM;
 
-        t = do_escape_mangle(name, allow_globs, s);
-        *t = 0;
+        mangled = do_escape_mangle(name, options & UNIT_NAME_MANGLE_GLOB, s);
+        if (mangled && (options & UNIT_NAME_MANGLE_WARN))
+                log_notice("Invalid unit name \"%s\" was escaped as \"%s\" (maybe you should use systemd-escape?)",
```
Comment (poettering) [inline src/basic/unit-name.c]: nowadays I think flags like this should just swicth between LOG_DEBUG and higher log levels, but never turn off logging entirely. i.e. I think this would be better as:

```c
log_full(options & UNIT_NAME_MANGLE_WARN ? LOG_NOTICE : LOG_DEBUG, …)
```

**Comment by keszybz** [comment]
Updated.

**Comment by poettering** [comment]
lgtm
