### PR TITLE
conf-files: fixes root directory handling, and split CONF_FILES_FILTER_MASKED into two

### LINKED ISSUE #37945: userdb only honors membership drop-ins if not empty
`.membership` drop-ins are looked up with the `CONF_FILES_FILTER_MASKED` flag, which will also ignore empty files:
https://github.com/systemd/systemd/blob/7e1647ae4e33dd8354bd311a7f7f5eb701be2391/src/shared/userdb.c#L1665-L1676

Either empty files should be special-cased for `.membership` lookups, or the documentation (which currently recommends creating `.membership` files as empty) should be adjusted to reflect this behavior.

### PR DESCRIPTION
**Pull request by yuwata**
Then, use the new CONF_FILES_FILTER_MASKED_BY_SYMLINK flag in userdb, to make .membership files correctly enumerated.

Fixes #37945.

### CODE REVIEW

File: src/shared/userdb.c [hunk 1]
```diff
@@ -1669,7 +1669,7 @@ static void discover_membership_dropins(UserDBIterator *i, UserDBFlags flags) {
                         &i->dropins,
                         ".membership",
                         NULL,
-                        CONF_FILES_REGULAR|CONF_FILES_BASENAME|CONF_FILES_FILTER_MASKED,
+                        CONF_FILES_REGULAR|CONF_FILES_BASENAME,
```
Comment (poettering) [inline src/shared/userdb.c]: hmm, it's not that simple, we check for /dev/null symlink masking before we enforce CONF_FILES_REGULAR. I think we should retain the ability to mask via such a symlink. 

Maybe we should split CONF_FILES_FILTER_MASKED into CONF_FILES_FILTER_MASKED_BY_SYMLINK and CONF_FILES_FILTER_MASKED_BY_EMPTY and then make CONF_FILES_FILTER_MASKED into an OR combination of both. Then we could use CONF_FILES_FILTER_MASKED_BY_SYMLINK here, which we want, but leave CONF_FILES_FILTER_MASKD_BY_EMPTY out.

**Comment by poettering** [comment]
Arrrgs, I am just realizing that conf_files_list() is really broken when it comes to the root dir stuff, and it's hard to fix:

files_add() follows symlinks when enumerating files. And rightfully so (it should be possible to symlink files into conf dirs). But it does so via a simple fstatat() which will not take the root dir stuff into account, but it really needs to. And we cannot fix this easily, because we have no flavour of chaseat() that allows us to pin both the root dir by fd and the inode to start from as fd...

File: src/shared/userdb.c (hunk 1 above)
Comment (yuwata) [reply src/shared/userdb.c]: If CONF_FILES_REGULAR is set, we checked if the file is regular, and `S_ISREG(st.st_mode)` refuse the symlink to /dev/null, as the device node is a character file and not a regular file, no?
From /usr/include/bits/stat.h:
```c
/* File types.  */
#define __S_IFDIR       0040000 /* Directory.  */
#define __S_IFCHR       0020000 /* Character device.  */
#define __S_IFBLK       0060000 /* Block device.  */
#define __S_IFREG       0100000 /* Regular file.  */
#define __S_IFIFO       0010000 /* FIFO.  */
#define __S_IFLNK       0120000 /* Symbolic link.  */
#define __S_IFSOCK      0140000 /* Socket.  */
```

Comment (yuwata) [reply src/shared/userdb.c]: Ah, you mean, the case that a file that have higher priority is a symlink to /dev/null, and lower priority has an empty file.

Comment (yuwata) [reply src/shared/userdb.c]: OK. I will split the MASKED flag into two.

**Comment by yuwata** [comment]
> Arrrgs, I am just realizing that conf_files_list() is really broken when it comes to the root dir stuff, and it's hard to fix:
> 
> files_add() follows symlinks when enumerating files. And rightfully so (it should be possible to symlink files into conf dirs). But it does so via a simple fstatat() which will not take the root dir stuff into account, but it really needs to. And we cannot fix this easily, because we have no flavour of chaseat() that allows us to pin both the root dir by fd and the inode to start from as fd...

Indeed. I am working on this.

**Comment by daandemeyer** [comment]
@yuwata You mean you're working on chaseat() with both a root and inode file descriptor? I tried to implement this one but it's rather complicated. I think preferably we find a way to chase everything within the root directory, pin the parent directory with `CHASE_PARENT|CHASE_EXTRACT_FILENAME` and then use `O_NOFOLLOW` all the time to prevent following symlinks like is done in firstboot.c

**Comment by yuwata** [comment]
> @yuwata You mean you're working on chaseat() with both a root and inode file descriptor? I tried to implement this one but it's rather complicated. I think preferably we find a way to chase everything within the root directory, pin the parent directory with `CHASE_PARENT|CHASE_EXTRACT_FILENAME` and then use `O_NOFOLLOW` all the time to prevent following symlinks like is done in firstboot.c

No, only on conf-files.c.

File: src/basic/stat-util.c [hunk 2]
```diff
@@ -184,19 +184,23 @@ int dir_is_empty_at(int dir_fd, const char *path, bool ignore_hidden_or_backup)
         return 1;
 }
 
-bool null_or_empty(struct stat *st) {
+bool stat_is_null(struct stat *st) {
```
Comment (YHNdnzj) [inline src/basic/stat-util.c]: So, hmm, if this gets extracted it feels a bit confusing, because previously it carried the context that this checks for some mask, and hence is not to be used as a genuine /dev/null check. But if it now becomes a standalone function like this it deserves some less confusing name. "stat_may_be_dev_null"?

File: src/basic/stat-util.c [hunk 3]
```diff
@@ -184,19 +184,23 @@ int dir_is_empty_at(int dir_fd, const char *path, bool ignore_hidden_or_backup)
...
+}
 
-        return false;
+bool stat_is_empty(struct stat *st) {
+        assert(st);
+
+        return S_ISREG(st->st_mode) && st->st_size <= 0;
+}
+
+bool null_or_empty(struct stat *st) {
```
Comment (YHNdnzj) [inline src/basic/stat-util.c]: This can be static inline

File: src/basic/conf-files.c [hunk 4]
```diff
@@ -21,97 +21,166 @@
...
-                        if (null_or_empty(&st)) {
-                                /* Mark this one as masked */
-                                r = set_put_strdup(masked, de->d_name);
-                                if (r < 0)
-                                        return r;
-
-                                log_debug("File '%s/%s' is a mask.", dirpath, de->d_name);
+                        if (r == 0) {
+                                /* If the path points to /dev/null in a image or so, then the device node may not exist. */
+                                if (path_equal(path_startswith(resolved_path, strempty(root)), "dev/null")) {
```
Comment (YHNdnzj) [inline src/basic/conf-files.c]: strempty -> empty_to_root?

File: src/basic/conf-files.c [hunk 5]
```diff
@@ -21,97 +21,166 @@
...
+                                        /* Mark this one as masked */
+                                        r = set_put_strdup(masked, de->d_name);
+                                        if (r < 0)
+                                                return log_oom_debug();
```
Comment (YHNdnzj) [inline src/basic/conf-files.c:90]: So, in library code let's still be honest about errno, and not use log_oom too aggressively. It might help to catch e.g. duplicate set items...

File: src/basic/conf-files.c [hunk 6]
```diff
@@ -21,97 +21,166 @@
...
                         }
+                }
+
+                /* Is this a masking entry? */
+                if ((FLAGS_SET(flags, CONF_FILES_FILTER_MASKED_BY_SYMLINK) && stat_is_null(&st)) ||
+                    (FLAGS_SET(flags, CONF_FILES_FILTER_MASKED_BY_EMPTY) && stat_is_empty(&st))) {
+                        /* Mark this one as masked */
+                        r = set_put_strdup(masked, de->d_name);
+                        if (r < 0)
+                                return log_oom_debug();
```
Comment (YHNdnzj) [inline src/basic/conf-files.c:136]: ditto

File: src/basic/conf-files.c [hunk 7]
```diff
@@ -21,97 +21,166 @@
...
+                } else {
+                        _cleanup_free_ char *p = path_join(resolved_dirpath, de->d_name);
                         if (!p)
-                                return -ENOMEM;
+                                return log_oom_debug();
 
                         r = hashmap_ensure_put(files, &string_hash_ops_free_free, n, p);
+                        if (r < 0)
+                                return log_oom_debug();
```
Comment (YHNdnzj) [inline src/basic/conf-files.c]: also here

**Comment by poettering** [comment]
looks pretty good to me as it is, but ig uess a new version with @YHNdnzj's points address is coming soon?

**Comment by yuwata** [comment]
Yeah, I am still working on.

**Comment by yuwata** [comment]
Sorry, I wrongly merged the PR by myself. And even the CIs are red...
I will at least fix the CI failure soon.

Please review.

Sorry.

File: src/basic/conf-files.c (hunk 5 above)
Comment (yuwata) [reply src/basic/conf-files.c:90]: set_put_strdup() only failed with -ENOMEM. So, log_oom should be enough.

File: src/basic/conf-files.c (hunk 7 above)
Comment (yuwata) [reply src/basic/conf-files.c]: In this case, at the beginning of the function, the function does not have the conflicting entry. So, it is also OK to use log_oom. I added assertion about the failure is really `-ENOMEM`.

File: src/basic/conf-files.c [hunk 8]
```diff
@@ -32,82 +34,144 @@ static int files_add(
...
+                        return log_oom_debug();
 
-                if ((flags & CONF_FILES_BASENAME))
-                        r = hashmap_ensure_put(files, &string_hash_ops_free, n, n);
-                else {
-                        p = path_join(dirpath, de->d_name);
-                        if (!p)
-                                return -ENOMEM;
+                if (FLAGS_SET(flags, CONF_FILES_CHASE_BASENAME))
+                        free_and_replace(p, resolved_path);
```
Comment (YHNdnzj) [inline src/basic/conf-files.c:168]: frankly, I'd be very wary of this. It means the callers (and hence logs and such) can no longer inform anything about the link itself, and the link target's extension might not even be the same as the symlink.

File: src/shared/pretty-print.c [hunk 9]
```diff
@@ -434,7 +439,7 @@ int conf_files_cat(const char *root, const char *name, CatFlags flags) {
         }
 
         /* Then locate the drop-ins, if any */
-        r = conf_files_list_strv(&files, extension, root, 0, (const char* const*) dirs);
+        r = conf_files_list_strv(&files, extension, root, CONF_FILES_CHASE_BASENAME, (const char* const*) dirs);
```
Comment (YHNdnzj) [inline src/shared/pretty-print.c:442]: I.e. systemctl cat on linked drop-ins (e.g. /etc/systemd/system/a.service.d/d.conf -> /opt/a/s) will now show /opt/a/s, losing all the information about actual unit name or the ordering info

File: src/libsystemd/sd-journal/catalog.c [hunk 10]
```diff
@@ -450,7 +450,9 @@ int catalog_update(const char *database, const char *root, const char* const *di
                 dirs = catalog_file_dirs;
 
         _cleanup_strv_free_ char **files = NULL;
-        r = conf_files_list_strv(&files, ".catalog", root, 0, dirs);
+        r = conf_files_list_strv(&files, ".catalog", root,
+                                 CONF_FILES_REGULAR | CONF_FILES_CHASE_BASENAME | CONF_FILES_FILTER_MASKED,
```
Comment (YHNdnzj) [inline src/libsystemd/sd-journal/catalog.c:454]: also here. catalog_import_file checks the filename for language (as well as .catalog extension). this will break a.catalog -> /path/to/zh_CN symlink

**Comment by yuwata** [comment]
> Not convinced by the way CONF_FILES_CHASE_BASENAME is implemented. Please revert the relevant changes for now and we can discuss that later on in a separate PR.

OK. Actually the CI failure is caused by the flag. Will revert, and solve the issue pointed out in the commit message in a different way.
Thank you for the review.

**Comment by yuwata** [comment]
The offending commits will be reverted by #37997.

File: src/basic/conf-files.h [hunk 11]
```diff
@@ -8,8 +8,9 @@ typedef enum ConfFilesFlags {
         CONF_FILES_REGULAR                  = 1 << 1,
         CONF_FILES_DIRECTORY                = 1 << 2,
         CONF_FILES_BASENAME                 = 1 << 3,
-        CONF_FILES_FILTER_MASKED_BY_SYMLINK = 1 << 4,
-        CONF_FILES_FILTER_MASKED_BY_EMPTY   = 1 << 5,
+        CONF_FILES_CHASE_BASENAME           = 1 << 4, /* If set, also resolve symlink files in config directories. */
```
Comment (poettering) [inline src/basic/conf-files.h:11]: a flag like might make sense, but "basename" is a bit of a misnomer, no? maybe call this _FULL_CHASE? or _RESOLVE_PATH?

Comment (yuwata) [reply src/basic/conf-files.h:11]: I am working on the issue with a different approach.
