### PR TITLE
bus-wait-for-jobs: fix failed job logging

### LINKED ISSUE #40030: systemctl doesn't print service startup failure caused by config error when Type=notify (sd_notifyf(READY=1)  sent after config parsed successfully)
### systemd version the issue has been seen with

259~rc2

### Used distribution

Fedora 44

### Linux kernel version used

6.18.0-65.fc44.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

Systemctl reports an error on f43 (systemd-258.2-1.fc43.x86_64):
```
# systemctl start kea-dhcp4
Job for kea-dhcp4.service failed because the control process exited with error code.
See "systemctl status kea-dhcp4.service" and "journalctl -xeu kea-dhcp4.service" for details.
#
```

### Unexpected behaviour you saw

Systemctl does not report an error on f44 (systemd-259~rc2-2.fc44.x86_64), but still returns 1:
```
# systemctl start kea-dhcp4
# echo $?
1
#
```
```
# systemctl status kea-dhcp4
× kea-dhcp4.service - Kea DHCPv4 Server
     Loaded: loaded (/usr/lib/systemd/system/kea-dhcp4.service; disabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Mon 2025-12-08 10:18:46 EST; 1min 57s ago
 Invocation: 01241a11c27c411f9dd6b387346eec76
       Docs: man:kea-dhcp4(8)
    Process: 4735 ExecStart=/usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4.conf (code=exited, status=1/FAILURE)
   Main PID: 4735 (code=exited, status=1/FAILURE)
   Mem peak: 6.8M
        CPU: 21ms

Dec 08 10:18:46 xxx kea-dhcp4[4735]: 2025-12-08 10:18:46.687 ERROR [kea-dhcp4.dhcp4/4735.140419047083328] DHCP4_INIT_FAIL failed to initialize Kea server: configuration error using file '/etc/kea/kea-dhcp4.conf': /etc/kea/kea-dhcp4.conf:493.1: Invalid character: l
Dec 08 10:18:46 xxx systemd[1]: kea-dhcp4.service: Child 4735 belongs to kea-dhcp4.service.
Dec 08 10:18:46 xxx systemd[1]: kea-dhcp4.service: Main process exited, code=exited, status=1/FAILURE
Dec 08 10:18:46 xxx systemd[1]: kea-dhcp4.service: Failed with result 'exit-code'.
...
```

### Steps to reproduce the problem

```
# dnf install kea
# echo lala >> /etc/kea/kea-dhcp4.conf
# systemctl start kea-dhcp4
#
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Follow-ups for 0d91a204cb78d692f23e80d3a08f9b81ecad753a.
Fixes #40030.

### CODE REVIEW

File: src/shared/bus-wait-for-jobs.c [hunk 1]
```diff
@@ -161,28 +161,31 @@ static int bus_job_get_service_result(BusWaitForJobs *d, char **ret) {
...
-                { "resources",       "of unavailable resources or another system error"                      },
-                { "protocol",        "the service did not take the steps required by its unit configuration" },
-                { "timeout",         "a timeout was exceeded"                                                },
-                { "exit-code",       "the control process exited with error code"                            },
-                { "signal",          "a fatal signal was delivered to the control process"                   },
-                { "core-dump",       "a fatal signal was delivered causing the control process to dump core" },
-                { "watchdog",        "the service failed to send watchdog ping"                              },
-                { "start-limit-hit", "start of the service was attempted too often"                          },
-                { "oom-kill",        "of an out-of-memory (OOM) siutation"                                   },
+                { "resources",       EBUSY,           "of unavailable resources or another system error"                      },
```
Comment (poettering) [inline src/shared/bus-wait-for-jobs.c]: maybe ENOEM is better for this?

File: src/shared/bus-wait-for-jobs.c [hunk 2]
```diff
@@ -161,28 +161,31 @@ static int bus_job_get_service_result(BusWaitForJobs *d, char **ret) {
...
+                { "protocol",        EPROTONOSUPPORT, "the service did not take the steps required by its unit configuration" },
```
Comment (poettering) [inline src/shared/bus-wait-for-jobs.c:176]: i think EPROTO would be better?

File: src/shared/bus-wait-for-jobs.c [hunk 3]
```diff
@@ -161,28 +161,31 @@ static int bus_job_get_service_result(BusWaitForJobs *d, char **ret) {
...
+                { "timeout",         ETIMEDOUT,       "a timeout was exceeded"                                                },
+                { "exit-code",       EPIPE,           "the control process exited with error code"                            },
```
Comment (poettering) [inline src/shared/bus-wait-for-jobs.c]: EBADE?

File: src/shared/bus-wait-for-jobs.c [hunk 4]
```diff
@@ -161,28 +161,31 @@ static int bus_job_get_service_result(BusWaitForJobs *d, char **ret) {
...
+                { "signal",          EINTR,           "a fatal signal was delivered to the control process"                   },
```
Comment (poettering) [inline src/shared/bus-wait-for-jobs.c]: i would avoid EINTR, because it's like EAGAIn one of these errors that are usually understood to be "transient", and repeating an operation could fix things. which seems like the wrong thing to communicate here.

maybe ENOTRECOVERABLE?

File: src/shared/bus-wait-for-jobs.c [hunk 5]
```diff
@@ -161,28 +161,31 @@ static int bus_job_get_service_result(BusWaitForJobs *d, char **ret) {
...
+                { "core-dump",       EFAULT,          "a fatal signal was delivered causing the control process to dump core" },
```
Comment (poettering) [inline src/shared/bus-wait-for-jobs.c]: ECONNABORTED?

File: src/shared/bus-wait-for-jobs.c (hunk 1 above)
Comment (yuwata) [reply src/shared/bus-wait-for-jobs.c]: ENOMEM is used for OOM error. I will switch to EMFILE.

File: src/shared/bus-wait-for-jobs.c (hunk 2 above)
Comment (yuwata) [reply src/shared/bus-wait-for-jobs.c:176]: EPROTO is already used for `streq(d->result, "assert")` case.
