### PR TITLE
core: delegate mountns implicitly when any of pidns/cgns/netns is in use, clean up private cgroupfs mount

### LINKED ISSUE #36952: TEST-07-PID1: test case for DelegateNamespaces= failed on Ubuntu s390x
https://autopkgtest.ubuntu.com/results/autopkgtest-noble-upstream-systemd-ci-systemd-ci/noble/s390x/s/systemd-upstream/20250402_115956_ecd0f@/log.gz
```
4536s TEST-07-PID1.sh[134]: + : '+++ testcase_cgroup BEGIN +++'
4536s TEST-07-PID1.sh[142]: + testcase_cgroup
4536s TEST-07-PID1.sh[143]: + systemd-run -p PrivateUsersEx=self -p ProtectControlGroupsEx=private --wait --pipe -- sh -c 'echo 0 >/sys/fs/cgroup/cgroup.pressure'
4536s TEST-07-PID1.sh[145]: /usr/bin/sh: 1: cannot create /sys/fs/cgroup/cgroup.pressure: Permission denied
4536s TEST-07-PID1.sh[142]: + systemd-run -p PrivateUsersEx=self -p ProtectControlGroupsEx=private -p DelegateNamespaces=cgroup --wait --pipe -- sh -c 'echo 0 >/sys/fs/cgroup/cgroup.pressure'
4536s TEST-07-PID1.sh[152]: /usr/bin/sh: 1: cannot create /sys/fs/cgroup/cgroup.pressure: Permission denied
4536s TEST-07-PID1.sh[134]: + at_exit
4536s TEST-07-PID1.sh[134]: + umount /tmp/TEST-07-PID1-delegate-namespaces-proc
4536s TEST-07-PID1.sh[134]: + rm -rf /tmp/TEST-07-PID1-delegate-namespaces-proc
4536s TEST-07-PID1.sh[84]: + echo 'Subtest /usr/lib/systemd/tests/testdata/units/TEST-07-PID1.delegate-namespaces.sh failed'
4536s TEST-07-PID1.sh[84]: Subtest /usr/lib/systemd/tests/testdata/units/TEST-07-PID1.delegate-namespaces.sh failed
4536s TEST-07-PID1.sh[84]: + return 1
4536s [FAILED] Failed to start TEST-07-PID1.service - TEST-07-PID1.
```
cc @DaanDeMeyer

### PR DESCRIPTION
**Pull request by YHNdnzj**
Fixes #36952

### CODE REVIEW

File: src/core/namespace.c [hunk 1]
```diff
@@ -207,14 +206,14 @@ static const MountEntry protect_control_groups_yes_table[] = {
...
- * flags is not set here. nsdelegate has been supported since kernels >= 4.13 so it is safe to use. */
+ * flags is not set here. */
 static const MountEntry protect_control_groups_private_table[] = {
-        { "/sys/fs/cgroup",      MOUNT_PRIVATE_CGROUP2FS, false, .read_only = false, .nosuid = true, .noexec = true, .options_const = "nsdelegate"  },
+        { "/sys/fs/cgroup",      MOUNT_PRIVATE_CGROUP2FS, false, .read_only = false },
 };
 
 /* ProtectControlGroups=strict table */
 static const MountEntry protect_control_groups_strict_table[] = {
-        { "/sys/fs/cgroup",      MOUNT_PRIVATE_CGROUP2FS, false, .read_only = true,  .nosuid = true, .noexec = true, .options_const = "nsdelegate"  },
```
Comment (poettering) [inline src/core/namespace.c:217]: why drop nosuid/noexec? those bind mount flags (i.e. not just superblock), should not be dropped?

Comment (YHNdnzj) [reply src/core/namespace.c:217]: See my comments at https://github.com/systemd/systemd/pull/36764#discussion_r1997786239

Comment (yuwata) [reply src/core/namespace.c:217]: See discussion https://github.com/systemd/systemd/pull/36764#discussion_r1997765277

**Review by yuwata — APPROVED** [review]

File: src/core/namespace.c (hunk 1 above)
Comment (poettering) [reply src/core/namespace.c:217]: ah, ok

**Review by DaanDeMeyer — APPROVED** [review]
