### PR TITLE
logind: let system-wide idle begin at system boot time

### LINKED ISSUE #35163: Logind reports the system idle since start of unix epoch instead of start of the system
### systemd version the issue has been seen with

256.7

### Used distribution

Gentoo

### Linux kernel version used

6.11.7-gentoo-dist

### CPU architectures issue was seen on

None

### Component

systemd-logind

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

On start, even before the first graphical login manager is started, logind correctly reports the system idle. However, it incorrectly reports the system idle since the start of the Unix epoch, instead of the timestamp when the system was started (which is where the idle period technically begun).

I develop a autosuspend daemon, called [sandmann](https://gitlab.com/flow/sandmann). This daemon takes action if the system becomes idle for a configurable period. At boot, when the sandmann service unit is started, it observers an system that is idle for ~54 years, i.e., idle since 1970-01-01T00:00:00Z. It therefore takes the according action, for example suspending the system.

With the logind behavior described above, the system sometimes boots, just to get suspended immediately.

I suspect a fix would involve simply changing

https://github.com/systemd/systemd/blob/893aa45886ef84b1827445dc438e410ad89fbbbf/src/login/logind-core.c#L410

from `DUAL_TIMESTAMP_NULL` to the timestamp when the system booted (or alternatively, when systemd was started).

<sup>Sandmann workaround: https://gitlab.com/flow/sandmann/-/commit/23cc0c7c0501a2ff044ea371a16e1f90fde3bd7d</sup>

### PR DESCRIPTION
**Pull request by Flowdalic**
Initialize the start of the system-wide idle time with the boot time and not with the start of the Unix epoch. This means that systemd will not report a unreasonable long idle time (around 54 years at the time of writing this), especially at in the early boot, while no login manager session may provide an more accurate start of the idle period.

Fixes #35163

### CODE REVIEW

File: src/login/logind-core.c [hunk 1]
```diff
@@ -407,10 +408,22 @@ int manager_get_user_by_pid(Manager *m, pid_t pid, User **ret) {
...
         bool idle_hint;
-        dual_timestamp ts = DUAL_TIMESTAMP_NULL;
+        dual_timestamp ts;
+        struct sysinfo info;
+        int r;
+        usec_t boot_usec;
 
         assert(m);
 
+        r = sysinfo(&info);
```
Comment (poettering) [inline src/login/logind-core.c]: urks, please, let's not use sysinfo(), it's an awful api.

is this really the uptime we want here? i mean, if we restart logind, then we'd return quite confusing values, i.e. the system might have idled/unidled before, but we'd suggest it wasn't.

I think it would make more sense to just take a timestamp when logind initializes and use that as base. any idleness info we have starts earliest at that time after all...

Comment (Flowdalic) [reply src/login/logind-core.c]: Sounds reasonable, modified according to the suggestions.

File: src/login/logind-core.c [hunk 2]
```diff
@@ -80,6 +80,8 @@ void manager_reset_config(Manager *m) {
         m->stop_idle_session_usec = USEC_INFINITY;
 
         m->maintenance_time = calendar_spec_free(m->maintenance_time);
+
+        dual_timestamp_now(&m->init_ts);
```
Comment (poettering) [inline src/login/logind-core.c]: manager_reset_config() is also issued at reload. the timestamp should only be acquired when logind initializes, not when it is reloaded I think. Hence maybe move this to manager_new()

File: src/login/logind-core.c [hunk 3]
```diff
@@ -411,6 +413,10 @@ int manager_get_idle_hint(Manager *m, dual_timestamp *t) {
 
         assert(m);
 
+        // Initialize the baseline timestamp with the time the manager got initialized to avoid reporting
+        // unreasonable large idle periods starting with the Unix epoch.
```
Comment (poettering) [inline src/login/logind-core.c]: in systemd we use `//` style comments for "fixme" issues, and `/* */` comments for explanatory stuff. This is the latter, hence please use `/* */`

Comment (poettering) [reply src/login/logind-core.c]: https://systemd.io/CODING_STYLE/#formatting

**Comment by Flowdalic** [comment]
Friendly ping of the pending review. I think it is probably even ready to get merged.

File: src/login/logind-core.c [hunk 4]
```diff
@@ -411,6 +411,10 @@ int manager_get_idle_hint(Manager *m, dual_timestamp *t) {
 
         assert(m);
 
+        /* Initialize the baseline timestamp with the time the manager got initialized to avoid reporting
+         * unreasonable large idle periods starting with the Unix epoch. */
+        ts = m->init_ts;
```
Comment (poettering) [inline src/login/logind-core.c:416]: maybe drop the DUAL_TIMESTAMP_NULL initialization further up then, given you always override this here...

**Comment by poettering** [comment]
lgtm

**Comment by bluca** [comment]
Needs a rebase

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
Hmm, what happens when logind is restarted??

**Comment by bluca** [comment]
> Hmm, what happens when logind is restarted??

That's quite broken at the moment in other more important aspects too, no?

**Comment by Flowdalic** [comment]
> Hmm, what happens when logind is restarted??

The first version of this change used the instant the system booted as starting point for the system-wide idle time. But albeit this would be more accurate, I don't foresee that the current approach of using the logind start time will cause major issues. For one, it is in many cases identical to the system boot time. Also, it will only underestimate the idle time, and not, as it was previously the case, grossly overestimate it. And if it is found to really cause issues, then we can probably switch to using the system boot time.
