### PR TITLE
several fixes for os image handling

### LINKED ISSUE #32888: TEST-13-NSPAWN (machinectl) failed in GitHub Action
https://github.com/systemd/systemd/actions/runs/9115979814/job/25063532755?pr=32871
```
gh run download 9115979814 --name ci-mkosi-9115979814-1-debian-testing-failed-test-journals -D ci/ci-mkosi-9115979814-1-debian-testing-failed-test-journals
```
```
40/93 systemd:integration-tests / TEST-13-NSPAWN                                                FAIL            100.65s   exit status 1
>>> MALLOC_PERTURB_=190 SYSTEMD_INTEGRATION_TESTS=1 /home/runner/work/systemd/systemd/test/integration-test-wrapper.py --meson-source-dir /home/runner/work/systemd/systemd --meson-build-dir /mnt/mkosi/build --name TEST-13-NSPAWN --storage volatile --firmware linux --exit-code 123 --unit TEST-13-NSPAWN.service --
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
Listing only the last 100 lines from a long log.
[   64.878494] TEST-13-NSPAWN.sh[1113]: ReadOnly=no
[   64.886885] TEST-13-NSPAWN.sh[1113]: CreationTimestamp=Thu 2024-05-16 17:43:17 UTC
[   64.897315] TEST-13-NSPAWN.sh[1113]: Usage=18446744073709551615
[   64.904411] TEST-13-NSPAWN.sh[1113]: Limit=infinity
[   64.908133] TEST-13-NSPAWN.sh[1113]: UsageExclusive=18446744073709551615
[   64.911457] TEST-13-NSPAWN.sh[1113]: LimitExclusive=infinity
[   64.913122] TEST-13-NSPAWN.sh[1113]: Name=container0
[   64.914622] TEST-13-NSPAWN.sh[1113]: Path=/var/lib/machines/container0
[   64.916354] TEST-13-NSPAWN.sh[1113]: Type=directory
[   64.917818] TEST-13-NSPAWN.sh[1113]: ReadOnly=no
[   64.919127] TEST-13-NSPAWN.sh[1113]: CreationTimestamp=Thu 2024-05-16 17:43:15 UTC
[   64.921195] TEST-13-NSPAWN.sh[1113]: Usage=18446744073709551615
[   64.922736] TEST-13-NSPAWN.sh[1113]: Limit=infinity
[   64.924115] TEST-13-NSPAWN.sh[1113]: UsageExclusive=18446744073709551615
[   64.926028] TEST-13-NSPAWN.sh[1113]: LimitExclusive=infinity
[   64.929780] TEST-13-NSPAWN.sh[1113]: Name=container1
[   64.932270] TEST-13-NSPAWN.sh[1113]: Path=/var/lib/machines/container1
[   64.937198] TEST-13-NSPAWN.sh[1113]: Type=directory
[   64.939180] TEST-13-NSPAWN.sh[1113]: ReadOnly=no
[   64.941253] TEST-13-NSPAWN.sh[1113]: CreationTimestamp=Thu 2024-05-16 17:43:17 UTC
[   64.944120] TEST-13-NSPAWN.sh[1113]: Usage=18446744073709551615
[   64.948628] TEST-13-NSPAWN.sh[1113]: Limit=infinity
[   64.952773] TEST-13-NSPAWN.sh[1113]: UsageExclusive=18446744073709551615
[   64.954895] TEST-13-NSPAWN.sh[1113]: LimitExclusive=infinity
[   64.956695] TEST-13-NSPAWN.sh[1113]: Name=container2
[   64.958277] TEST-13-NSPAWN.sh[1113]: Path=/var/lib/machines/container2
[   64.960335] TEST-13-NSPAWN.sh[1113]: Type=directory
[   64.962017] TEST-13-NSPAWN.sh[1113]: ReadOnly=no
[   64.963740] TEST-13-NSPAWN.sh[1113]: CreationTimestamp=Thu 2024-05-16 17:43:19 UTC
[   64.966431] TEST-13-NSPAWN.sh[1113]: Usage=18446744073709551615
[   64.972945] TEST-13-NSPAWN.sh[1113]: Limit=infinity
[   64.990054] TEST-13-NSPAWN.sh[1113]: UsageExclusive=18446744073709551615
[   65.000323] TEST-13-NSPAWN.sh[1113]: LimitExclusive=infinity
[   65.002593] TEST-13-NSPAWN.sh[1113]: Name=container3
[   65.004688] TEST-13-NSPAWN.sh[1113]: Path=/var/lib/machines/container3
[   65.007159] TEST-13-NSPAWN.sh[1113]: Type=directory
[   65.009314] TEST-13-NSPAWN.sh[1113]: ReadOnly=no
[   65.014598] TEST-13-NSPAWN.sh[1113]: CreationTimestamp=Thu 2024-05-16 17:43:20 UTC
[   65.017497] TEST-13-NSPAWN.sh[1113]: Usage=18446744073709551615
[   65.021623] TEST-13-NSPAWN.sh[1113]: Limit=infinity
[   65.024621] TEST-13-NSPAWN.sh[1113]: UsageExclusive=18446744073709551615
[   65.032846] TEST-13-NSPAWN.sh[1113]: LimitExclusive=infinity
[   65.035788] TEST-13-NSPAWN.sh[1113]: Name=container4
[   65.041296] TEST-13-NSPAWN.sh[1113]: Path=/var/lib/machines/container4
[   65.048934] TEST-13-NSPAWN.sh[1113]: Type=directory
[   65.053471] TEST-13-NSPAWN.sh[1113]: ReadOnly=no
[   65.058191] TEST-13-NSPAWN.sh[1113]: CreationTimestamp=Thu 2024-05-16 17:43:22 UTC
[   65.066216] TEST-13-NSPAWN.sh[1113]: Usage=18446744073709551615
[   65.069180] TEST-13-NSPAWN.sh[1113]: Limit=infinity
[   65.070656] TEST-13-NSPAWN.sh[1113]: UsageExclusive=18446744073709551615
[   65.073007] TEST-13-NSPAWN.sh[1113]: LimitExclusive=infinity
[   65.103778] TEST-13-NSPAWN.sh[568]: + machinectl clone container1 clone1
[   65.989440] TEST-13-NSPAWN.sh[568]: + machinectl show-image clone1
[   66.027592] TEST-13-NSPAWN.sh[1117]: Name=clone1
[   66.034330] TEST-13-NSPAWN.sh[1117]: Path=/var/lib/machines/clone1
[   66.042892] TEST-13-NSPAWN.sh[1117]: Type=subvolume
[   66.048925] TEST-13-NSPAWN.sh[1117]: ReadOnly=no
[   66.055071] TEST-13-NSPAWN.sh[1117]: CreationTimestamp=Thu 2024-05-16 17:44:00 UTC
[   66.062328] TEST-13-NSPAWN.sh[1117]: Usage=18446744073709551615
[   66.065121] TEST-13-NSPAWN.sh[1117]: Limit=infinity
[   66.067485] TEST-13-NSPAWN.sh[1117]: UsageExclusive=18446744073709551615
[   66.070401] TEST-13-NSPAWN.sh[1117]: LimitExclusive=infinity
[   66.102273] TEST-13-NSPAWN.sh[568]: + machinectl rename clone1 clone2
[   66.216406] TEST-13-NSPAWN.sh[1119]: + machinectl show-image clone1
[   66.434114] TEST-13-NSPAWN.sh[568]: + machinectl show-image clone2
[   66.634442] TEST-13-NSPAWN.sh[1122]: Name=clone2
[   66.635874] TEST-13-NSPAWN.sh[1122]: Path=/var/lib/machines/clone2
[   66.637970] TEST-13-NSPAWN.sh[1122]: Type=subvolume
[   66.639251] TEST-13-NSPAWN.sh[1122]: ReadOnly=no
[   66.640570] TEST-13-NSPAWN.sh[1122]: CreationTimestamp=Thu 2024-05-16 17:44:00 UTC
[   66.642616] TEST-13-NSPAWN.sh[1122]: Usage=18446744073709551615
[   66.644471] TEST-13-NSPAWN.sh[1122]: Limit=infinity
[   66.645929] TEST-13-NSPAWN.sh[1122]: UsageExclusive=18446744073709551615
[   66.647746] TEST-13-NSPAWN.sh[1122]: LimitExclusive=infinity
[   66.685861] TEST-13-NSPAWN.sh[568]: + lsattr -d /var/lib/machines
[   66.746455] TEST-13-NSPAWN.sh[1124]: ++ machinectl show-image --property=ReadOnly --value clone2
[   66.833404] TEST-13-NSPAWN.sh[568]: + [[ no == no ]]
[   66.837506] TEST-13-NSPAWN.sh[568]: + machinectl read-only clone2 yes
[   67.208582] TEST-13-NSPAWN.sh[1126]: ++ machinectl show-image --property=ReadOnly --value clone2
[   67.354985] TEST-13-NSPAWN.sh[568]: + [[ yes == yes ]]
[   67.356886] TEST-13-NSPAWN.sh[568]: + machinectl read-only clone2 no
[   67.655213] TEST-13-NSPAWN.sh[1128]: ++ machinectl show-image --property=ReadOnly --value clone2
[   67.946112] TEST-13-NSPAWN.sh[568]: + [[ yes == no ]]
[   67.947940] TEST-13-NSPAWN.sh[568]: + at_exit
[   67.953489] TEST-13-NSPAWN.sh[568]: + set +e
[   67.955203] TEST-13-NSPAWN.sh[568]: + machinectl status long-running
[   69.043397] TEST-13-NSPAWN.sh[568]: + machinectl kill --signal=KILL long-running
[   69.385074] TEST-13-NSPAWN.sh[568]: + mountpoint -q /var/lib/machines
[   69.387923] TEST-13-NSPAWN.sh[568]: + timeout 10 sh -c 'until umount /var/lib/machines; do sleep .5; done'
[   69.392923] TEST-13-NSPAWN.sh[568]: + [[ -n '' ]]
[   69.394724] TEST-13-NSPAWN.sh[568]: + rm -f '/run/systemd/nspawn/*.nspawn'
[   69.431197] TEST-13-NSPAWN.sh[506]: + echo 'Subtest /usr/lib/systemd/tests/testdata/units/TEST-13-NSPAWN.machinectl.sh failed'
[   69.441220] TEST-13-NSPAWN.sh[506]: Subtest /usr/lib/systemd/tests/testdata/units/TEST-13-NSPAWN.machinectl.sh failed
[   69.445805] TEST-13-NSPAWN.sh[506]: + return 1
[   92.723098] reboot: Power down
Finishing after writing 360010 entries
Test failed, relevant logs can be viewed with: 

gh run download 9115979814 --name ci-mkosi-9115979814-1-debian-testing-failed-test-journals -D ci/ci-mkosi-9115979814-1-debian-testing-failed-test-journals && journalctl --file ci/ci-mkosi-9115979814-1-debian-testing-failed-test-journals/test/journal/TEST-13-NSPAWN.journal --no-hostname -o short-monotonic -u TEST-13-NSPAWN.service -p info
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #32888.

### CODE REVIEW

File: src/machine/machined-dbus.c [hunk 1]
```diff
@@ -550,8 +550,8 @@ static int method_get_machine_uid_shift(sd_bus_message *message, void *userdata,
 }
 
 static int redirect_method_to_image(sd_bus_message *message, Manager *m, sd_bus_error *error, sd_bus_message_handler_t method) {
-        _cleanup_(image_unrefp) Image* i = NULL;
         const char *name;
+        Image* i;
```
Comment (YHNdnzj) [inline src/machine/machined-dbus.c]:
```suggestion
        Image *i;
```

File: src/shared/discover-image.c [hunk 2]
```diff
@@ -282,6 +282,44 @@ static int extract_image_basename(
...
+        assert(i);
+
+        if (IMAGE_IS_VENDOR(i) || IMAGE_IS_HOST(i))
+                return -EROFS;
+
+        if (i->type != IMAGE_SUBVOLUME)
+                return -EOPNOTSUPP;
+
+        if (fd < 0) {
+                fd = open(i->path, O_CLOEXEC|O_NOCTTY|O_DIRECTORY);
```
Comment (YHNdnzj) [inline src/shared/discover-image.c]: O_NOCTTY seems unnecessary when O_DIRECTORY is specified?

File: src/shared/discover-image.c [hunk 3]
```diff
@@ -282,6 +282,44 @@ static int extract_image_basename(
...
+        _cleanup_close_ int fd_close = -EBADF;
+        int r;
+
+        assert(i);
+
+        if (IMAGE_IS_VENDOR(i) || IMAGE_IS_HOST(i))
+                return -EROFS;
+
+        if (i->type != IMAGE_SUBVOLUME)
+                return -EOPNOTSUPP;
```
Comment (YHNdnzj) [inline src/shared/discover-image.c:295]: (We usually return -ENOTTY for inappropriate fstype and such?)

File: src/machine/image-dbus.c [hunk 4]
```diff
@@ -418,19 +420,48 @@ static int image_object_find(sd_bus *bus, const char *path, const char *interfac
...
 
         r = hashmap_ensure_put(&m->image_cache, &image_hash_ops, image->name, image);
-        if (r < 0) {
-                image_unref(image);
+        if (r < 0)
+                return r;
+
+        if (ret)
+                *ret = image;
+
```
Comment (YHNdnzj) [inline src/machine/image-dbus.c:429]: TAKE_PTR(image)?

File: src/shared/discover-image.c (hunk 3 above)
Comment (YHNdnzj) [reply src/shared/discover-image.c:295]: Hmm, in discover-image.c EOPNOTSUPP is used consistently, hence please ignore.

File: src/machine/image-dbus.c [hunk 5]
```diff
@@ -127,10 +127,25 @@ int bus_image_method_rename(
         if (r == 0)
                 return 1; /* Will call us back */
 
+        /* The image is cached with its name, hence it is necessary to remove from the cache before renaming. */
+        Image *removed = hashmap_remove(m->image_cache, image->name);
```
Comment (YHNdnzj) [inline src/machine/image-dbus.c]: Hmm, the memory management here is rather confusing? If image_rename fails this is leaked?

File: src/machine/image-dbus.c [hunk 6]
```diff
@@ -127,10 +127,25 @@ int bus_image_method_rename(
...
         r = image_rename(image, new_name);
         if (r < 0)
                 return r;
 
+        /* Then save the object again in the cache. */
+        if (removed) {
+                if (removed != image)
+                        image_unref(removed);
+
+                r = hashmap_put(m->image_cache, image->name, image);
```
Comment (YHNdnzj) [inline src/machine/image-dbus.c]: Also this should use hashmap_ensure_put with image_hash_ops?

File: src/shared/discover-image.c (hunk 3 above)
Comment (yuwata) [reply src/shared/discover-image.c:295]: Yeah. Let's fix that later consistently in another PR if necessary.

File: src/shared/discover-image.c (hunk 2 above)
Comment (yuwata) [reply src/shared/discover-image.c]: O_NOCTTY is actually not necessary, but also used in `image_make()`. Let's keep the flag at least now for consistency.

File: src/machine/image-dbus.c (hunk 4 above)
Comment (yuwata) [reply src/machine/image-dbus.c:429]: Ouch.

File: src/shared/discover-image.c [hunk 7]
```diff
@@ -282,6 +282,44 @@ static int extract_image_basename(
...
+
+        if (fd < 0) {
+                fd = open(i->path, O_CLOEXEC|O_NOCTTY|O_DIRECTORY);
+                if (fd < 0)
+                        return -errno;
+                fd_close = fd;
```
Comment (YHNdnzj) [inline src/shared/discover-image.c]: We usually do this in the reverse order? I.e. assign `fd_close` to `fd` at the end of the block.

File: src/machine/machined-dbus.c
Comment (YHNdnzj) [inline src/machine/machined-dbus.c:1]: > machine: cache found image when a dbus method in the main interface is called

Hmm, the commit title is a bit hard to grok. Maybe, "acquire the object from cache when available" or "do not create new image object each time dbus method is called"?

File: src/machine/image-dbus.c [hunk 8]
```diff
@@ -418,19 +413,49 @@ static int image_object_find(sd_bus *bus, const char *path, const char *interfac
...
+                return r;
+
+        if (ret)
+                *ret = image;
+
+        TAKE_PTR(image);
+        return 0;
+}
+
+static int image_object_find(sd_bus *bus, const char *path, const char *interface, void *userdata, void **found, sd_bus_error *error) {
```
Comment (YHNdnzj) [inline src/machine/image-dbus.c:434]: Hmm, if you touch this, "image_object_from_dbus_path" is more straightforward and clear.

Comment (yuwata) [reply src/machine/image-dbus.c:434]: This is a `sd_bus_object_find_t` callback, and we usually name like that, e.g. link_object_find() in networkd. If you'd like to rename it, then let's do that consistently later.

**Comment by yuwata** [comment]
@YHNdnzj Thank you for the review.
- extended commit message,
- swap assignment of FD.

Upgrading the green label.

File: test/units/TEST-13-NSPAWN.machinectl.sh [hunk 9]
```diff
@@ -132,13 +132,11 @@ machinectl show-image clone1
 machinectl rename clone1 clone2
 (! machinectl show-image clone1)
 machinectl show-image clone2
-if lsattr -d /var/lib/machines >/dev/null; then
```
Comment (bluca) [inline test/units/TEST-13-NSPAWN.machinectl.sh]: This was added explicitly to avoid this error:

https://github.com/systemd/systemd/pull/27634#issuecomment-1546366352

https://github.com/systemd/systemd/compare/1f4fe8e1131bd7fa80b9f7621147d4a255737260..bb152e764f8056d1034efeb0f19ba62999cbfcb0

So please drop this commit

Comment (yuwata) [reply test/units/TEST-13-NSPAWN.machinectl.sh]: I have no idea why calling lsattr prevents such error. But OK, the change is dropped now.

Comment (yuwata) [reply test/units/TEST-13-NSPAWN.machinectl.sh]: @mrc0mmand ?

Comment (mrc0mmand) [reply test/units/TEST-13-NSPAWN.machinectl.sh]: The test mounts `tmpfs` on `/var/log/machines` to not pollute the base image, and on older kernels you can't do `chattr()` on `tmpfs`, so `lsattr` is used here to check if it's supported:

```
# lsattr -d /tmp/foo/
lsattr: Inappropriate ioctl for device While reading flags on /tmp/foo/
```

Comment (bluca) [reply test/units/TEST-13-NSPAWN.machinectl.sh]: It would probably be good to have that as a comment in the script
