### PR TITLE
tree-wide: various terminal related fixlets

### LINKED ISSUE #38524: TEST-72-SYSUPDATE is flaky
```
[   35.792602] TEST-72-SYSUPDATE.sh[411]: + /lib/systemd/systemd-sysupdate --verify=no update
[   35.796506] TEST-72-SYSUPDATE.sh[1085]: Skipping file '/run/sysupdate.d/99-optional.transfer' with unexpected suffix.
[   35.796687] TEST-72-SYSUPDATE.sh[1085]: Skipping file '/run/sysupdate.d/05-fifth.transfer' with unexpected suffix.
[   35.796836] TEST-72-SYSUPDATE.sh[1085]: Skipping file '/run/sysupdate.d/04-fourth.transfer' with unexpected suffix.
[   35.796965] TEST-72-SYSUPDATE.sh[1085]: Skipping file '/run/sysupdate.d/03-third.transfer' with unexpected suffix.
[   35.799274] TEST-72-SYSUPDATE.sh[1085]: Skipping file '/run/sysupdate.d/02-second.transfer' with unexpected suffix.
[   35.799423] TEST-72-SYSUPDATE.sh[1085]: Skipping file '/run/sysupdate.d/01-first.transfer' with unexpected suffix.
[   35.801379] TEST-72-SYSUPDATE.sh[1085]: Skipping file '/run/sysupdate.d/optional.feature' with unexpected suffix.
[   35.817622] TEST-72-SYSUPDATE.sh[1085]: Found container virtualization none.
[   35.818739] TEST-72-SYSUPDATE.sh[1085]: Resolved $BOOT to '/var/tmp/test-72-N7uTeO/xbootldr'
[   35.819439] TEST-72-SYSUPDATE.sh[1085]: Resolved $BOOT to '/var/tmp/test-72-N7uTeO/xbootldr'
[   35.819960] TEST-72-SYSUPDATE.sh[1085]: Resolved $BOOT to '/var/tmp/test-72-N7uTeO/xbootldr'
[   35.820362] TEST-72-SYSUPDATE.sh[1085]: Discovering installed instances…
[   35.824413] TEST-72-SYSUPDATE.sh[1085]: Discovering available instances…
[   35.824662] TEST-72-SYSUPDATE.sh[1085]: Determining installed update sets…
[   35.825939] TEST-72-SYSUPDATE.sh[1085]: Determining available update sets…
[   35.828089] TEST-72-SYSUPDATE.sh[1085]: Selected update 'v5' for install.
[   35.828297] TEST-72-SYSUPDATE.sh[1085]: Making room for 1 updates…
[   35.828451] TEST-72-SYSUPDATE.sh[1085]: ~ Removing old '/proc/self/fd/3p2' (partition).
[   35.849745] TEST-72-SYSUPDATE.sh[1085]: ~ Removing old '/proc/self/fd/3p4' (partition).
[   35.906987] TEST-72-SYSUPDATE.sh[1085]: ~ Removing old '/var/tmp/test-72-N7uTeO/dirs/dir-v1' (directory).
[   35.912717] TEST-72-SYSUPDATE.sh[1085]: ~ Removing old '/var/tmp/test-72-N7uTeO/xbootldr/EFI/Linux/uki_v2+3-0.efi' (regular-file).
[   35.914426] TEST-72-SYSUPDATE.sh[1085]: ~ Removing old '/var/tmp/test-72-N7uTeO/xbootldr/EFI/Linux/uki_v2.efi.extra.d/extra.addon.efi' (regular-file).
[   35.915384] TEST-72-SYSUPDATE.sh[1085]: Removed 1 instances.
[   35.948652] TEST-72-SYSUPDATE.sh[1085]: \ Acquiring /var/tmp/test-72-N7uTeO/source/part1-v5.raw → /proc/self/fd/3p2...
[   35.952447] TEST-72-SYSUPDATE.sh[1085]: Failed to disable SO_PASSRIGHTS on notification socket, ignoring: Protocol not available
[   35.952895] TEST-72-SYSUPDATE.sh[1085]: Successfully forked off '(sd-import-raw)' as PID 1089.
[   35.959347] TEST-72-SYSUPDATE.sh[1089]: Importing '/var/tmp/test-72-N7uTeO/source/part1-v5.raw', saving at offset 9437184 in '/dev/loop0'.
[   35.959597] TEST-72-SYSUPDATE.sh[1089]: Failed to decode and write: Input/output error
[   35.959812] TEST-72-SYSUPDATE.sh[1089]: Exiting.
[   35.961333] TEST-72-SYSUPDATE.sh[1085]: Got errno from callout: 5 (Input/output error)
[   35.961646] TEST-72-SYSUPDATE.sh[1085]: (sd-import-raw) failed with exit status 1: Input/output error
```

https://github.com/systemd/systemd/actions/runs/16823206569/job/47654057819?pr=38522

[TEST-72-SYSUPDATE.journal.gz](https://github.com/user-attachments/files/21679695/TEST-72-SYSUPDATE.journal.gz)

### LINKED ISSUE #38527: pam_systemd writes osc session information to non-terminal outputs
As reported in https://github.com/coreos/fedora-coreos-tracker/issues/2003, we now write OSC stuff, even if the terminal is connected to a pipe:
```console
$ sudo build/machinectl --quiet shell dbus@ /usr/bin/true | cat -v
^[?25h^[?12l^[ 1q^[[!p^[]104^G^[[?7h^[[1G^[[0J^[[6n^[[32766;32766H^[[6n^[]3008;start=805c48fe4fee4210961da648eb4d8c60;user=root;hostname=x1c;machineid=3a9d668b4db749398a4a5e78a03bffa5;bootid=ec415154ac1845ceb370b529d355d3f1;pid=1289774;pidfdid=5482846;comm=(true);targetuser=dbus;sessionid=142;type=session^[\
```

This is caused by d8069b8add9a2290d7ed85012f8459fccfc632ed.

AFAICT, the program is really connect to a tty for stdout:
```console
$ sudo build/machinectl --quiet shell dbus@ /bin/ls -l /proc/self/fd/ | cat -v
^[?25h^[?12l^[ 1q^[[!p^[]104^G^[[?7h^[[1G^[[0J^[[6n^[[32766;32766H^[[6n^[]3008;start=1d815823b12c425fa8553359f431fab8;user=root;hostname=x1c;machineid=3a9d668b4db749398a4a5e78a03bffa5;bootid=ec415154ac1845ceb370b529d355d3f1;pid=1290181;pidfdid=5483253;comm=(ls);targetuser=dbus;sessionid=144;type=session^[\total 0^M
lrwx------ 1 dbus dbus 64 08-08 20:10 0 -> /dev/pts/11^M
lrwx------ 1 dbus dbus 64 08-08 20:10 1 -> /dev/pts/11^M
lrwx------ 1 dbus dbus 64 08-08 20:10 2 -> /dev/pts/11^M
lr-x------ 1 dbus dbus 64 08-08 20:10 3 -> /proc/1290181/fd^M
```

The man page does not make it clear whether this is a supported use case, so I'm not sure if this is really a bug. If it is, it's a fairly significant regression.

### LINKED ISSUE #38552: pid1, importctl: showing progress-bar with OSC sequence even if StandardOutput=journal+console
Hence, journal has full of `[xxxB blob data]`:
```
Aug 12 06:57:06 H TEST-13-NSPAWN.sh[663]: + importctl import-raw --class=confext /var/tmp/importtest
Aug 12 06:57:07 H (sd-transfer)[693]: Calling: /usr/lib/systemd/systemd-import raw --class confext - importtest
Aug 12 06:57:07 H TEST-13-NSPAWN.sh[692]: [83B blob data]
Aug 12 06:57:07 H systemd-importd[666]: (transfer1) Importing '/var/tmp/importtest', saving as 'importtest'.
Aug 12 06:57:07 H TEST-13-NSPAWN.sh[692]: [82B blob data]
Aug 12 06:57:07 H TEST-13-NSPAWN.sh[692]: [75B blob data]
Aug 12 06:57:07 H TEST-13-NSPAWN.sh[692]: [52B blob data]
Aug 12 06:57:07 H systemd-importd[666]: (transfer1) Operating on image directory '/var/lib/confexts'.
Aug 12 06:57:07 H TEST-13-NSPAWN.sh[692]: [36B blob data]
Aug 12 06:57:07 H TEST-13-NSPAWN.sh[692]: [59B blob data]
Aug 12 06:57:07 H TEST-13-NSPAWN.sh[692]: [34B blob data]
```

[TEST-13-NSPAWN-1.journal.gz](https://github.com/user-attachments/files/21728124/TEST-13-NSPAWN-1.journal.gz)

It seems `prepare_terminal()` in exec-invoke.c does something spurious.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #38524.
Fixes #38527.
Fixes #38552.

### CODE REVIEW

**Comment by keszybz** [comment]
fedora builds failed because of infra issues, not relevant.

mkosi/ci (opensuse, tumbledweed): `mkdir: cannot create directory ‘/mnt’: Permission denied`
That is new. Maybe something changed in the permission model? @bluca

**Comment by yuwata** [comment]
@keszybz Thank you for the review.
One more commit for PID1 is added. PTAL.

File: src/nspawn/nspawn.c [hunk 1]
```diff
@@ -3551,15 +3551,15 @@ static int inner_child(
         envp[n_env++] = strjoina("container=", arg_container_service_name);
 
         /* Propagate $TERM & Co. unless we are invoked in pipe mode and stdin/stdout/stderr don't refer to a TTY */
-        if (arg_console_mode != CONSOLE_PIPE || on_tty()) {
+        if (on_tty())
```
Comment (yuwata) [inline src/nspawn/nspawn.c]: Maybe, rather than dropping the condition, better to change `||` to `&&`. I will test later after dinner.

File: src/core/exec-invoke.c [hunk 2]
```diff
@@ -4904,7 +4904,7 @@ static void prepare_terminal(
```
Comment (keszybz) [inline src/core/exec-invoke.c]: A few lines above we have
```C
        /* We only try to reset things if we there's the chance our stdout points to a TTY */
        if (!(is_terminal_output(context->std_output) ||
              (context->std_output == EXEC_OUTPUT_INHERIT && is_terminal_input(context->std_input)) ||
              context->std_output == EXEC_OUTPUT_NAMED_FD ||
              p->stdout_fd >= 0))
                return;
```
I find that code quite surprising. If we're writing to a named fd, then it's a socket or a fifo or a file. Why would we do any of the subsequent steps in that case? This code was added like this originally and I don't understand the logic.

@poettering ?

File: src/nspawn/nspawn.c (hunk 1 above)
Comment (poettering) [inline src/nspawn/nspawn.c]: hmm, shouldn't this better be:

`if (arg_console_mode != CONSOLE_PIPE && on_tty())` 

i.e. propagate the three if we both are on a tty and and we are invoking things on a tty, otherwise set things to dumb.

might even go further and use !terminal_is_dumb() instead of on_tty() here()...

File: src/core/exec-invoke.c (hunk 2 above)
Comment (poettering) [reply src/core/exec-invoke.c]: people might very well upload ttys to the fd store, hence when it's a named fd we simply don't know a prioriy if it's a tty or not. this condition simply skips where it *definitely* is not a tty because the selected output couldn't possibly be. but named fds can be anything really, including ttys

File: src/core/exec-invoke.c [hunk 3]
```diff
@@ -4904,7 +4904,7 @@ static void prepare_terminal(
 
         (void) exec_context_apply_tty_size(context, STDIN_FILENO, STDOUT_FILENO, /* tty_path= */ NULL);
 
-        if (use_ansi)
+        if (use_ansi && !getenv_terminal_is_dumb())
```
Comment (poettering) [inline src/core/exec-invoke.c]: this should not be necessary: exec_context_shall_ansi_seq_reset() already contains a suitable check for dumb terminals.

File: src/core/execute.c [hunk 4]
```diff
@@ -180,7 +180,7 @@ void exec_context_tty_reset(const ExecContext *context, const ExecParameters *pa
         if (r < 0)
                 log_debug_errno(r, "Failed to configure TTY dimensions, ignoring: %m");
 
-        if (!sd_id128_is_null(invocation_id)) {
+        if (!sd_id128_is_null(invocation_id) && !getenv_terminal_is_dumb()) {
```
Comment (poettering) [inline src/core/execute.c]: probably should use exec_context_shall_ansi_seq_reset() too, as above

File: src/core/execute.h [hunk 5]
```diff
@@ -458,6 +458,26 @@ typedef struct ExecParameters {
                 .pidref_transport_fd    = -EBADF, \
         }
 
+static inline bool is_terminal_input(ExecInput i) {
```
Comment (poettering) [inline src/core/execute.h]: maybe rename then, i.e. exec_input_is_terminal()

File: src/core/execute.h [hunk 6]
```diff
@@ -458,6 +458,26 @@ typedef struct ExecParameters {
...
+        return IN_SET(i,
+                      EXEC_INPUT_TTY,
+                      EXEC_INPUT_TTY_FORCE,
+                      EXEC_INPUT_TTY_FAIL);
+}
+
+static inline bool is_terminal_output(ExecOutput o) {
```
Comment (poettering) [inline src/core/execute.h]: similar, and below, too

File: src/core/exec-invoke.c [hunk 7]
```diff
@@ -4860,8 +4860,7 @@ static void prepare_terminal(
         /* We only try to reset things if we there's the chance our stdout points to a TTY */
         if (!(context->std_output == EXEC_OUTPUT_TTY ||
               (context->std_output == EXEC_OUTPUT_INHERIT && is_terminal_input(context->std_input)) ||
-              context->std_output == EXEC_OUTPUT_NAMED_FD ||
-              p->stdout_fd >= 0))
+              isatty_safe(STDOUT_FILENO))) /* For the case EXEC_OUTPUT_NAMED_FD or p->stdout_fd >= 0 */
```
Comment (poettering) [inline src/core/exec-invoke.c]: i don't really like this, i think it should be otally fine to stash a tty fd in an fdstore... is there any real benefit of doing this?

**Comment by poettering** [comment]
looks pretty good, but some comments above

File: src/core/exec-invoke.c (hunk 7 above)
Comment (yuwata) [reply src/core/exec-invoke.c]: The motivation of the change is for exec_context_shall_ansi_seq_reset(), which does not check if stdout is a tty.
But actually the change is not good. I will reconsider about the issue.

File: test/units/TEST-72-SYSUPDATE.sh [hunk 8]
```diff
@@ -54,15 +54,41 @@ at_exit() {
...
+    # zstd (0x28, 0xb5, 0x2f, 0xfd)
+    [[ $(head_in_hex "$name" 4) != '28 b5 2f fd' ]]
 }
 
 new_version() {
     local sector_size="${1:?}"
     local version="${2:?}"
 
     # Create a pair of random partition payloads, and compress one
-    dd if=/dev/urandom of="$WORKDIR/source/part1-$version.raw" bs="$sector_size" count=2048
```
Comment (bluca) [inline test/units/TEST-72-SYSUPDATE.sh:65]: "infinite monkeys hitting random keys on a typewriter will eventually produce ~~Shakespeare's work~~ a compression format header"

File: test/units/TEST-72-SYSUPDATE.sh [hunk 9]
```diff
@@ -54,15 +54,41 @@ at_exit() {
...
 update_checksums() {
-	(cd "$WORKDIR/source" && sha256sum uki* part* dir-*.tar.gz >SHA256SUMS)
+    (cd "$WORKDIR/source" && sha256sum uki* part* dir-*.tar.gz >SHA256SUMS)
+}
+
+head_in_hex() {
+    local name="${1:?}"
+    local size="${2:?}"
+
+    hexdump -c --length "$size" "$name" | head -n 1 | sed -E 's/^0* *//; s/ *$//; s/ +/ /g;'
```
Comment (dnicolodi) [inline test/units/TEST-72-SYSUPDATE.sh]: I think `xxd` may be better suited to do this

File: test/units/TEST-72-SYSUPDATE.sh [hunk 10]
```diff
@@ -54,15 +54,41 @@ at_exit() {
...
 new_version() {
     local sector_size="${1:?}"
     local version="${2:?}"
 
     # Create a pair of random partition payloads, and compress one
-    dd if=/dev/urandom of="$WORKDIR/source/part1-$version.raw" bs="$sector_size" count=2048
+    while : ; do
+        dd if=/dev/urandom of="$WORKDIR/source/part1-$version.raw" bs="$sector_size" count=2048
+        avoid_compression_headers "$WORKDIR/source/part1-$version.raw" && break
+    done
```
Comment (dnicolodi) [inline test/units/TEST-72-SYSUPDATE.sh]: Isn't it simpler to set the first 4 bytes of `$WORKDIR/source/part1-$version.raw` to a known constant? It should not be too difficult to do in a shell script using `xxd`.

Comment (yuwata) [reply test/units/TEST-72-SYSUPDATE.sh]: I thought that, but currently xxd is not installed in the image. I think it is better to avoid installing the package used only single place.

Comment (bluca) [reply test/units/TEST-72-SYSUPDATE.sh]: it's a very small binary so it's ok to add it, it's useful to have anyway

File: src/core/execute.h [hunk 11]
```diff
@@ -478,6 +478,14 @@ static inline bool exec_output_is_kmsg(ExecOutput o) {
                       EXEC_OUTPUT_KMSG_AND_CONSOLE);
 }
 
+static inline bool exec_context_has_tty(const ExecContext *context) {
+        return
```
Comment (bluca) [inline src/core/execute.h:484]: assert or check context

File: test/units/TEST-72-SYSUPDATE.sh (hunk 10 above)
Comment (yuwata) [reply test/units/TEST-72-SYSUPDATE.sh]: Another approach is applied: now the first block of the image is filled with zero.

**Comment by poettering** [comment]
lgtm
