### PR TITLE
systemd-resolve: use sha256 for local-part of openpgp key

### LINKED ISSUE #4192: systemd-resolve: update OPENPGP local-part hashing algorithm
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

The `systemd-resolve --openpgp` command should hash the local-part of the OPENPGP record with SHA2-256, as it is described in [RFC 7929](https://tools.ietf.org/html/rfc7929).
### In case of bug report: Unexpected behaviour you saw

At the moment the OPENPGP local-part hashing is done as described in the old and deprecated _DANE for OpenPGP public keys_ draft in [version 2](https://tools.ietf.org/html/draft-ietf-dane-openpgpkey-02). The hashing algorithm is SHA2-224.

This can seen in the following example:

``` bash
echo -n "zbyszek" | openssl dgst -sha224 | cut -d "=" -f 2 | cut -c 1-57
d08ee310438ca124a6149ea5cc21b6313b390dce485576eff96f8722
```

The `systemd-resolve` [man page](https://github.com/systemd/systemd/blob/master/man/systemd-resolve.xml#L367) also outputs this local-part:

```
$ systemd-resolve --openpgp zbyszek@fedoraproject.org
 d08ee310438ca124a6149ea5cc21b6313b390dce485576eff96f8722._openpgpkey.fedoraproject.org. IN OPENP
GPKEY
```

But when using the  SHA2-256 algorithm (as specified in RFC 7929) the following local-part will be returned:

``` bash
echo -n "zbyszek" | openssl dgst -sha256 | cut -d "=" -f 2 | cut -c 1-57
0691f9c9710d900996ecf8ad7c394af923459f1856cec9f3487bbf20
```

@keszybz See my proposal in #4193!

### PR DESCRIPTION
**Pull request by stefan-it**
This PR uses the SHA2-256 hashing algorithm for the local-part of an OPENPGP key, as specified in [RFC 7929](https://tools.ietf.org/html/rfc7929).

Fixes #4192.

### CODE REVIEW

File: src/resolve/resolve-tool.c [hunk 1]
```diff
@@ -840,7 +840,7 @@ static int resolve_openpgp(sd_bus *bus, const char *address) {
         }
         domain++;
 
-        r = string_hashsum_sha224(address, domain - 1 - address, &hashed);
+        r = string_hashsum_sha256(address, domain - 1 - address, &hashed);
```
Comment (stefan-it) [inline src/resolve/resolve-tool.c]: `hashed` needs to be truncated to 28 octets later, see [RFC 7929](https://tools.ietf.org/html/rfc7929#section-3)!

**Comment by keszybz** [comment]
That's a lovely change in the spec ;) Peachy.

I think we should resolve both, i.e. try to sha256-format-of-the-day first, and then fall back to the old name. I suppose that most keys in the wild are still in the old format, so it'd be nice to be nice to users and support both variants for a while.

**Comment by stefan-it** [comment]
@keszybz What do you thing about the following fallback mode:

Instead of `return resolve_record(...)` (at the end of the `resolve_openpgp` function):

``` c
        r = resolve_record(bus, full,
                              arg_class ?: DNS_CLASS_IN,
                              arg_type ?: DNS_TYPE_OPENPGPKEY);

        if (r < 0) {
              hashed = NULL;
              r = string_hashsum_sha224(address, domain - 1 - address, &hashed);
              if (r < 0)
                    return log_error_errno(r, "Hashing failed: %m");

              full = strjoina(hashed, "._openpgpkey.", domain);
              log_debug("Looking up \"%s\".", full);

              return resolve_record(bus, full,
                                                      arg_class ?: DNS_CLASS_IN,
                                                      arg_type ?: DNS_TYPE_OPENPGPKEY);
        }

        return r;
```

Example output for your pgp key:

``` bash
$ systemd-resolve --openpgp zbyszek@fedoraproject.org
0691f9c9710d900996ecf8ad7c394af923459f1856cec9f3487bbf20._openpgpkey.fedoraproject.org: resolve call failed: DNSSEC validation failed: incompatible-server
d08ee310438ca124a6149ea5cc21b6313b390dce485576eff96f8722._openpgpkey.fedoraproject.org IN OPENPGPKEY 
        mQINBFBHPMsBEACeInGYJCb+7TurKfb6wGyTottCDtiSJB310i37/6ZYoeIay
# echo $?
0
```

For a non existing openpgp record for a mail address the output would look like:

``` bash
$ systemd-resolve --openpgp stefan@schweter.it
52518386cc33022de894fa0af047bd62666a63c2a6a6e86650e26955._openpgpkey.schweter.it: resolve call failed: DNSSEC validation failed: incompatible-server
fb11666ee37390f1da2a6dd64abd8396ef5d02db1c23eab03fa4995f._openpgpkey.schweter.it: resolve call failed: DNSSEC validation failed: incompatible-server
$ echo $?
1
```

I guess we should add a friendly output message after the first openpgp record retrieval with sha256, saying that we do a fallback with sha224? What do you think about my fallback logic?

**Comment by keszybz** [comment]
Fallback mode looks right. But I think it shouldn't print the error for the first lookup, if the second hash succeeds. At least if the error is "not found".

So maybe add a parameter to `resolve_record`, `bool warn_missing`, and skip printing of the line `log_error("%s: no records found", name)` when calling from resolve_openpgp. Then if resolve_openpgp gets -ESRCH from both attempts, it can print a custom error message that neither name was found.

It seems that schweter.it gives so "system error" for missing names, instead of a simple "not found", but I guess that's a special case, and in that case it's OK to print both errors.

**Comment by stefan-it** [comment]
@keszybz I added a new `warn_missing` argument to `resolve_record`. The reason why I don't check for the return code `-ESRCH`: in my setup it won't work. E.g. when I try to revolve the sha256 local-part of your domain, the error code comes from:

``` code
r = sd_bus_call(bus, req, DNS_CALL_TIMEOUT_USEC, &error, &reply);
```

So the error message `resolve call failed:` will be printed out (not identical with `-ESRCH`).

**Comment by martinpitt** [comment]
CI failure is due to not being on top of current master.  PR #4194 changed the install location of files which is unduly difficult to support in multiple variants at the same time. Can you please rebase on current master? Thanks!

**Comment by stefan-it** [comment]
Rebase is done, thanks for that hint!

File: src/resolve/resolve-tool.c [hunk 2]
```diff
@@ -430,7 +430,8 @@ static int resolve_record(sd_bus *bus, const char *name, uint16_t class, uint16_
 
         r = sd_bus_call(bus, req, DNS_CALL_TIMEOUT_USEC, &error, &reply);
         if (r < 0) {
-                log_error("%s: resolve call failed: %s", name, bus_error_message(&error, r));
+                if (warn_missing)
```
Comment (poettering) [inline src/resolve/resolve-tool.c]: wouldn't it be better to check for NXDOMAIN here explicitly? I mean, the bus call can fail for many reasons, but we should only handle the NXDOMAIN case here explicitly, no?

i.e. something like this:

`if (warn_missing || !sd_bus_error_has_name(&error, _BUS_ERROR_DNS "NXDOMAIN")) …`

File: src/resolve/resolve-tool.c [hunk 3]
```diff
@@ -840,16 +842,34 @@ static int resolve_openpgp(sd_bus *bus, const char *address) {
...
         log_debug("Looking up \"%s\".", full);
 
-        return resolve_record(bus, full,
-                              arg_class ?: DNS_CLASS_IN,
-                              arg_type ?: DNS_TYPE_OPENPGPKEY);
+        r = resolve_record(bus, full,
+                           arg_class ?: DNS_CLASS_IN,
+                           arg_type ?: DNS_TYPE_OPENPGPKEY, false);
+
+        if (r < 0) {
```
Comment (poettering) [inline src/resolve/resolve-tool.c]: similar as above, I think we should do this fallback only on NXDOMAIN, and on NODATA.

Comment (poettering) [reply src/resolve/resolve-tool.c]: With #4299 applied, doing this check would be as easy as looking for ENXIO and ESRCH here.

Comment (poettering) [reply src/resolve/resolve-tool.c]: As #4299 is applied now this line could be changed now to:

``` c
if (IN_SET(r, -ENXIO, -ESRCH)) { /* NXDOMAIN or NODATA? */ 
```

**Comment by stefan-it** [comment]
@poettering Thanks for your suggestions! I rebased onto (latest) `master` - CI looks good so far.
