### PR TITLE
service: killmode=cgroup|mixed, SendSIGKILL=no services are not multiprocess

### LINKED ISSUE #8630: services shouldn't start if there is residual processes left over (in SendSIGKILL=no case)
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemctl  --version
systemd 237
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

### Used distribution

Fedora rawhide (in Docker)

### In case of bug report: Expected behaviour you didn't see

A service in Active: deactivating (final-sigterm) (Result: timeout) should not be allowed to restart if PID(s) still exist in the control group.

```
Mar 31 07:48:31 6adbfc4b13bc systemd[1]: Started sleep.service.
Mar 31 07:48:57 6adbfc4b13bc systemd[1]: Stopping sleep.service...
Mar 31 07:50:27 6adbfc4b13bc systemd[1]: sleep.service: State 'stop-sigterm' timed out. Skipping SIGKILL.
Mar 31 07:51:57 6adbfc4b13bc systemd[1]: sleep.service: State 'stop-final-sigterm' timed out. Skipping SIGKILL. Entering failed mode.
Mar 31 07:51:57 6adbfc4b13bc systemd[1]: sleep.service: Failed with result 'timeout'.
Mar 31 07:51:57 6adbfc4b13bc systemd[1]: Stopped sleep.service.
Mar 31 07:51:57 6adbfc4b13bc systemd[1]: sleep.service: Found left-over process 122 (sleep) in control group while starting unit. Ignoring.
Mar 31 07:51:57 6adbfc4b13bc systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Mar 31 07:51:57 6adbfc4b13bc systemd[1]: Started sleep.service.
```

I expected not to see "Ignoring" and to see that as an error.

### In case of bug report: Unexpected behaviour you saw

Restarting the service created a second instance of the process in the same service
```
● sleep.service
   Loaded: loaded (/etc/systemd/system/sleep.service; static; vendor preset: disabled)
   Active: active (running) since Sat 2018-03-31 07:51:57 UTC; 4s ago
 Main PID: 204 (sleep)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/docker.service/system.slice/sleep.service
           ├─122 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600
           └─204 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600
```

### In case of bug report: Steps to reproduce the problem

```
[Service]
ExecStart=/bin/nohup /bin/sleep 3600
KillSignal=HUP
SendSIGKILL=no
```

```
[root@6adbfc4b13bc /]# systemctl start  sleep
[root@6adbfc4b13bc /]# systemctl status sleep
● sleep.service
   Loaded: loaded (/etc/systemd/system/sleep.service; static; vendor preset: dis
abled)
   Active: active (running) since Sat 2018-03-31 07:48:31 UTC; 15s ag
o
 Main PID: 122 (sleep)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/docker.service/system.slice/sleep.service
           └─122 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600
[root@6adbfc4b13bc /]# systemctl restart  sleep
```

Second window during restart - 1m30s timeout occurred as expected
```
[root@6adbfc4b13bc /]# systemctl  status sleep
● sleep.service
   Loaded: loaded (/etc/systemd/system/sleep.service; static; vendor preset: dis
abled)
   Active: deactivating (stop-sigterm) since Sat 2018-03-31 07:48:57 UTC; 1min 2
3s ago
 Main PID: 122 (sleep)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/docker.service/system.slice/sleep.service
           └─122 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600

Mar 31 07:48:31 6adbfc4b13bc systemd[1]: Started sleep.service.
Mar 31 07:48:57 6adbfc4b13bc systemd[1]: Stopping sleep.service...
[root@6adbfc4b13bc /]# systemctl  status sleep
● sleep.service
   Loaded: loaded (/etc/systemd/system/sleep.service; static; vendor preset: dis
abled)
   Active: deactivating (final-sigterm) (Result: timeout) since Sat 2018-03-31 0
7:48:57 UTC; 1min 32s ago
 Main PID: 122 (sleep)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/docker.service/system.slice/sleep.service
           └─122 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600

Mar 31 07:48:31 6adbfc4b13bc systemd[1]: Started sleep.service.
Mar 31 07:48:57 6adbfc4b13bc systemd[1]: Stopping sleep.service...
Mar 31 07:50:27 6adbfc4b13bc systemd[1]: sleep.service: 
State 'stop-sigterm' timed out. Skipping SIGKILL.
```

```
[root@6adbfc4b13bc /]# systemctl status sleep
● sleep.service
   Loaded: loaded (/etc/systemd/system/sleep.service; static; vendor preset: disabled)
   Active: active (running) since Sat 2018-03-31 07:51:57 UTC; 4s ago
 Main PID: 204 (sleep)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/docker.service/system.slice/sleep.service
           ├─122 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600
           └─204 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600
```

While a sleep service can run quite well with two instances the running of multiple database service instances on top of each other creates complicated process mess and relies on internal mechanisms to prevent corruption. Ideally the starting of the service shouldn't be allowed while a residual process is still around. It should be the admin's responsibility to take actions (SIGKILL if necessary) to restore the service to a stopped state before systemd is willing to restart the service.

### PR DESCRIPTION
**Pull request by grooverdan**
Refuse to start a service of this type as these are often database services that don't like having multiple instances trampling over their files.

closes #8630

test:
image

### CODE REVIEW

**Comment by bl33pbl0p** [comment]
What if I remove SendSIGKILL=no, daemon-reload, and then try to start it?

**Comment by grooverdan** [comment]
Then it will start a second instance. Is this a problem? systemd doesn't maintain service state after the timeout so the existence of a process in the cgroup and the current state of the service file are all that can be considered.

File: src/core/service.c [hunk 1]
```diff
@@ -1426,6 +1426,26 @@ static int service_spawn(
         if (r < 0)
                 return r;
 
+        if (IN_SET(s->kill_context.kill_mode, KILL_MIXED, KILL_CONTROL_GROUP) && !s->kill_context.send_sigkill) {
+                _cleanup_free_ char *text = NULL;
+                _cleanup_free_ char *f = NULL;
+                r = cg_get_path(SYSTEMD_CGROUP_CONTROLLER, UNIT(s)->cgroup_path, "cgroup.procs", &f);
+                if (r < 0)
+                        return r;
```
Comment (poettering) [inline src/core/service.c]: please use cg_is_empty_recursive() for this check

File: src/core/service.c [hunk 2]
```diff
@@ -1426,6 +1426,26 @@ static int service_spawn(
...
+                if (f) {
+                        r = read_one_line_file(f, &text);
+                        if (r < 0)
+                                return r;
+                        /* text not empty, process must exist */
+                        if (*text != '\0') {
+                                r = -EINVAL;
+                                log_unit_error_errno(UNIT(s), r, "Will not start SendSIGKILL=no service of type KillMode=cgroup or mixed while process %s is still active", text);
```
Comment (poettering) [inline src/core/service.c]: hmm, could you please add a comment here, explaining why the combination of these settings means it's probably safe to refuse starting in this case.

**Comment by poettering** [comment]
looks pretty ok, but please use the right helper call for this. That should simplify the patch quite a bit, and is a lot faster, in particular in cgroupsv2

**Comment by poettering** [comment]
hmm, actually, the check is not at the right place: service_spawn() is used for any process we fork off for a service, including the ExecStop= stuff, where we don#t want this.

**Comment by poettering** [comment]
this check should be placed where we currently invoke unit_warn_leftover_processes() already, i.e. in service_enter_start() and service_enter_start_pre()...

File: src/core/service.c (hunk 1 above)
Comment (grooverdan) [reply src/core/service.c]: I ended up getting `unit_warn_leftover_processes` to identify the process existing rather than separate call to `cg_is_empty_recursive`. This didn't affect the other calls to `unit_warn_leftover_processes`.

**Comment by grooverdan** [comment]
Thanks for the prompt review. Rewritten to address these comments and used the existing `unit_warn_leftover_processes` function to perform the process check.

File: src/core/service.c [hunk 3]
```diff
@@ -2017,7 +2037,9 @@ static void service_enter_start(Service *s) {
         service_unwatch_control_pid(s);
         service_unwatch_main_pid(s);
 
-        unit_warn_leftover_processes(UNIT(s));
+        if (unit_warn_leftover_processes(UNIT(s)))
+                if (service_adverse_to_leftover_processes(s))
+                        goto fail;
```
Comment (poettering) [inline src/core/service.c]: You need to initialize `r` somehow if you jump to `fail`...

File: src/core/service.c [hunk 4]
```diff
@@ -2110,7 +2132,9 @@ static void service_enter_start_pre(Service *s) {
         s->control_command = s->exec_command[SERVICE_EXEC_START_PRE];
         if (s->control_command) {
 
-                unit_warn_leftover_processes(UNIT(s));
+                if (unit_warn_leftover_processes(UNIT(s)))
+                        if (service_adverse_to_leftover_processes(s))
+                                goto fail;
```
Comment (poettering) [inline src/core/service.c]: similar here

Comment (poettering) [reply src/core/service.c]: actually, the code in both occasions your new function is called is pretty much the same, hence I figure the invocation of `unit_warn_leftover_processes()` should maybe just move into `service_adverse_to_leftover_process()`? That'd be shorter then, and I like short.

File: src/core/service.c [hunk 5]
```diff
@@ -2006,6 +2006,26 @@ static void service_kill_control_process(Service *s) {
         }
 }
 
+static bool service_adverse_to_leftover_processes(Service *s) {
```
Comment (poettering) [inline src/core/service.c]: given that when you call this you need to initialize `r` to something maybe just return an `int` here, and then return an error like `-EBUSY` when we refuse to proceed like this, and 0 otherwise?

File: src/core/unit.c [hunk 6]
```diff
@@ -5396,27 +5401,35 @@ int unit_prepare_exec(Unit *u) {
...
         (void) unit_pick_cgroup_path(u);
 
         if (!u->cgroup_path)
-                return;
+                return false;
+
+        (void) cg_kill_recursive(SYSTEMD_CGROUP_CONTROLLER, u->cgroup_path, 0, 0, NULL, log_leftover, &ur);
 
-        (void) cg_kill_recursive(SYSTEMD_CGROUP_CONTROLLER, u->cgroup_path, 0, 0, NULL, log_leftover, u);
+        return ur.result;
```
Comment (poettering) [inline src/core/unit.c]: Hmm, I think it would be nicer if the logging callback that cg_kill_recursive() takes would be slightly altered, so that it returns a boolean. And then cg_kill_recursive() should return > 0 when at least one invocation of that function returns true, and 0 otherwise. Right now cg_kill_recursive() already returns > 0 when at least one process is killed, and letting the log function decide whether to return that would be only a minor extension the way I see it, and a natural one.

With that in place you don't need the small structure to pass data between this function and the log function, which would be nicer I think.

**Comment by grooverdan** [comment]
updated. Comes out quite nicely. Even `systemctl start sleep` fails immediately.

image

File: src/core/unit.c [hunk 7]
```diff
@@ -4428,21 +4428,23 @@ int unit_make_transient(Unit *u) {
...
-                return;
+                return false;
 
         log_unit_notice(userdata,
                         "Killing process " PID_FMT " (%s) with signal SIG%s.",
                         pid,
                         strna(comm),
                         signal_to_string(sig));
+
+        return false;
```
Comment (poettering) [inline src/core/unit.c]: not that it matters at all, but in order to keep this similar to log_leftover() i think this should return true here

File: src/core/unit.c [hunk 8]
```diff
@@ -5394,29 +5396,31 @@ int unit_prepare_exec(Unit *u) {
...
         _cleanup_free_ char *comm = NULL;
 
         (void) get_process_comm(pid, &comm);
 
         if (comm && comm[0] == '(') /* Most likely our own helper process (PAM?), ignore */
-                return;
+                return false;
 
-        log_unit_warning(userdata,
+        log_unit_warning((Unit *) userdata,
```
Comment (poettering) [inline src/core/unit.c]: the explicit cast to Unit* is unnecessary, as in C "void*" casts implicitly to any type

File: src/core/unit.c [hunk 9]
```diff
@@ -5394,29 +5396,31 @@ int unit_prepare_exec(Unit *u) {
...
         assert(u);
 
         (void) unit_pick_cgroup_path(u);
 
         if (!u->cgroup_path)
-                return;
+                return false;
 
-        (void) cg_kill_recursive(SYSTEMD_CGROUP_CONTROLLER, u->cgroup_path, 0, 0, NULL, log_leftover, u);
+        return cg_kill_recursive(SYSTEMD_CGROUP_CONTROLLER, u->cgroup_path, 0, 0, NULL, log_leftover, u) == 1;
```
Comment (poettering) [inline src/core/unit.c]: i think we should propagate the return as is (i.e. change the return type of unit_warn_leftover_processes() to "int"), and let the caller eat up any errors. It's more in line with the vast majority of other functions we have, and I think more generic, if we propagate errors always and eat them up as far up the call chain as appropriate but not needlessly far down.

i.e. make this function return "int", so that it returns < 0 on error, == 0 if no offending processes were found and > 0 if there were.

File: src/basic/cgroup-util.c [hunk 10]
```diff
@@ -267,7 +267,8 @@ int cg_kill(
                                 continue;
 
                         if (log_kill)
-                                log_kill(pid, sig, userdata);
+                                if (log_kill(pid, sig, userdata))
+                                        return 1;
```
Comment (poettering) [inline src/basic/cgroup-util.c]: a few lines further down there's currently this logic:

```c
if (ret == 0)
        ret = 1
```

i.e. this sets the return value to > 0 as soon as at least one process was killed. I think this should be conditionalized depending on whether log_kill is passed. i.e. the return value is determine by log_kill if it is set, and otherwise the return value is > 0 if at least one process was killed, as before. i.e. change that code to a simple:

```c
if (!log_kill && ret == 0)
        ret = 1;
```

File: src/core/service.c [hunk 11]
```diff
@@ -2006,6 +2006,27 @@ static void service_kill_control_process(Service *s) {
...
+         *
+         * Here we take these two factors and refuse to start a service if there are existing processes
+         * within a control group. Databases, while generally having some protection against multiple
+         * instances running, lets not stress the rigor of these. Also ExecStartPre parts of the service
+         * aren't as rigoriously written to protect aganst against multiple use. */
+        if (unit_warn_leftover_processes(UNIT(s)) &&
+            IN_SET(s->kill_context.kill_mode, KILL_MIXED, KILL_CONTROL_GROUP) &&
+            !s->kill_context.send_sigkill) {
+               log_unit_error(UNIT(s), "Will not start SendSIGKILL=no service of type KillMode=cgroup or mixed while processes exist");
+               return -EBUSY;
```
Comment (poettering) [inline src/core/service.c]: we now have a new syntax in our codebase to allow merging these last two lines in one, please use it:

```c
return log_unit_error_errno(UNIT(s), SYNTHETIC_ERRNO(EBUSY), "Will not start…");
```

**Comment by poettering** [comment]
Looks pretty good, but a few more notes, see above. We are getting close.

I'd like to delay this to v242 however (i.e. not put this in the upcoming v241), since this has a chance of breaking some users and v241 is supposed to be a bugfix only release. Hope that makes sense.

**Comment by grooverdan** [comment]
Updated and rebased. At some point it was the case that 'systemctl start {service}' where there was a process existing terminated immediately. Currently it seems to wait. That would be a desirable outcome but I've lost what case achieved this. Suggestions/Feedback welcome.

**Comment by bl33pbl0p** [comment]
Thanks, I have tested your patch, it works nicely now, and doesn't seem to wait in the start job anymore (which I think is the correct behaviour in this case).

One improvement would be the description, it should read " ... KillMode=control-group ..." instead of cgroup (there is no cgroup option) which could confuse people.

Just curious though (about the usecase), why is not bumping the TimeoutStopSec= to infinity a possible option here (or better, JobRunningTimeoutSec= (we could add one for stop too)), that would mean your unit stays in "deactivating" state as long as everything doesn't clean up, and you effectively keep start jobs waiting until that is done, getting the semantics you want here, without denying requests outright, or failing them.

**Comment by grooverdan** [comment]
Thanks for testing. Glad you didn't see a wait in the starting case.

Changed KillMode=control-group as requested.

Setting absolute timeouts on database services is quite hard as there is a very variable amount of shutdown/startup time. I added `EXTEND_TIMEOUT_USEC=` as an `sd_notify` message back in v236 for such a case. Evidently the implemented case in MariaDB (at the time #8630 was written) didn't send enough messages at the right time.

As getting the right number of `EXTEND_TIMEOUT_USEC=` messages going at the right time is a more difficult problem. This PR adds a sufficient safety mechanism to not add more processes while other timeout around processes are terminating. Without this PR, processes from two different services could running, of which a sysadmin or OOMKiller could accidentally kill the wrong one(s).

**Comment by grooverdan** [comment]
Thanks @bl33pbl0p and @poettering
