### PR TITLE
ask-password: improve log message when inotify limit is reached

### LINKED ISSUE #6030: When inotify watches are used up, "No space left on device" is shown...
... which is totally expected for programmers, but not for users.

```
# systemctl start test
Failed to add /run/systemd/ask-password to directory watch: No space left on device
```

There are two problems with this error message.

1) The "No space left on device" is completely misleading for users. Programmers who know that inotify_add_watch() sets errno to ENOSPC and this errno is then translated using strerror() to that message may find it ok, but it's not.

My suggestion here would be to change the error message for this special case (when inotify_add_watch() returns < 0 and errno is set to ENOSPC) to something like "Failed to add /run/systemd/ask-password to directory watch: inotify watch limit reached", that is, not use strerrno(errno) in this case.

2) The error message looks as if it came from systemctl, but it didn't, which, for users, is even more confusing than 1). The message came from `tty-ask-password-agent`, which is forked off and exec'd by systemd. This took me a while to debug and figure out.

Here I would suggest to simply identify itself in the error message, since `tty-ask-password-agent` seems to be used a lot for a lot of operations.

#### Expected result
So, the final error message in this case would look like:

`/usr/bin/systemd-tty-ask-password-agent: Failed to add /run/systemd/ask-password to directory watch: inotify watch limit reached`

Yes, it's a bit lengthy, but it makes the error much less confusing. Also, this makes debugging a lot easier, since it's very obvious where the error is coming from.

For a complete reproducer, see https://bugzilla.redhat.com/show_bug.cgi?id=1452933#c2.

### PR DESCRIPTION
**Pull request by jsynacek**
When inotify_add_watch() fails because of the inotify limit, errno is
set to ENOSPC and then gets shown to users as "No space left on device".
That is very confusing and requires in-depth knowledge of the C library.
Therefore, show user-friendly message when inotify limit is reached.

Fixes #6030.

### CODE REVIEW

File: src/tty-ask-password-agent/tty-ask-password-agent.c [hunk 1]
```diff
@@ -525,7 +525,10 @@ static int watch_passwords(void) {
                 return log_error_errno(errno, "Failed to allocate directory watch: %m");
 
         if (inotify_add_watch(notify, "/run/systemd/ask-password", IN_CLOSE_WRITE|IN_MOVED_TO) < 0)
-                return log_error_errno(errno, "Failed to add /run/systemd/ask-password to directory watch: %m");
+                if (errno == ENOSPC)
+                        return log_error("Failed to add /run/systemd/ask-password to directory watch: inotify watch limit reached");
+                else
+                        return log_error_errno(errno, "Failed to add /run/systemd/ask-password to directory watch: %m");
```
Comment (poettering) [inline src/tty-ask-password-agent/tty-ask-password-agent.c:531]: please enclose the inner if/else in {}, otherwise it's not obvious to which `if` the `else`you added belongs. actually the compiler should have warned you about that already? it used to do that at least...

File: src/tty-ask-password-agent/tty-ask-password-agent.c [hunk 2]
```diff
@@ -525,7 +525,10 @@ static int watch_passwords(void) {
                 return log_error_errno(errno, "Failed to allocate directory watch: %m");
 
         if (inotify_add_watch(notify, "/run/systemd/ask-password", IN_CLOSE_WRITE|IN_MOVED_TO) < 0)
-                return log_error_errno(errno, "Failed to add /run/systemd/ask-password to directory watch: %m");
+                if (errno == ENOSPC)
+                        return log_error("Failed to add /run/systemd/ask-password to directory watch: inotify watch limit reached");
```
Comment (poettering) [inline src/tty-ask-password-agent/tty-ask-password-agent.c]: you are eating up the error here entirely. Please use log_error_errno() instead and pass `errno` as before. Note that passing errno has three effects: 

1. %m resolves to the error message you
2. the negative error number is returned, so that it is easy propagate with `return`.
3. if structured logging to the journal is used the error number is included in an ERRNO= field.

In this case we want 2 and 3, only 1 is not needed. Hence, please use log_error_errno() here, even if you don't make use of `%m`.

**Comment by jsynacek** [comment]
The thing is that `inotify_add_watch()` is used very inconsistently across the tree that it's not possible to write a general patch without rewriting a lot of code. Some examples:
``` 
from src/basic/terminal-util.c:
int acquire_terminal(...) {
        ...
        if ((flags & ~ACQUIRE_TERMINAL_PERMISSIVE) == ACQUIRE_TERMINAL_WAIT) {
                notify = inotify_init1(IN_CLOEXEC | (timeout != USEC_INFINITY ? IN_NONBLOCK : 0));
                if (notify < 0)
                        return -errno;

                wd = inotify_add_watch(notify, name, IN_CLOSE);
                if (wd < 0)
                        return -errno;

                if (timeout != USEC_INFINITY)
                        ts = now(CLOCK_MONOTONIC);
        }
        ...
}

from src/core/cgroup.c:
int unit_watch_cgroup(Unit *u) {
...
        u->cgroup_inotify_wd = inotify_add_watch(u->manager->cgroup_inotify_fd, events, IN_MODIFY);
        if (u->cgroup_inotify_wd < 0) {

                if (errno == ENOENT) /* If the directory is already
                                      * gone we don't need to track
                                      * it, so this is not an error */
                        return 0;

                return log_unit_error_errno(u, errno, "Failed to add inotify watch descriptor for control group %s: %m", u->cgroup_path);
        }
...
}

from src/core/path.c:
int path_spec_watch(PathSpec *s, sd_event_io_handler_t handler) {
...
                r = inotify_add_watch(s->inotify_fd, s->path, flags);
                if (r < 0) {
                        if (IN_SET(errno, EACCES, ENOENT)) {
                                if (cut)
                                        *cut = tmp;
                                break;
                        }

                        r = log_warning_errno(errno, "Failed to add watch on %s: %s", s->path, errno == ENOSPC ? "too many watches" : strerror(-r));
                        if (cut)
                                *cut = tmp;
                        goto fail;
                } else {
                ...
...
}
```
In the last snippet, the message is even already modified depending on the errno. Then, in library code, no logging should be used anyway, but code using library functions which in turn use `inotify_add_watch()` would have no idea if they should treat ENOSPC differently or not.

So my suggestion is to "fix" the message only in this particular case (I would fix the patch according to the review, of course) and not anywhere else. The reason for fixing ask-password is that the message pops up when `systemctl start <my-favourite-unit>` is run from the command line and people are confused why the error says "no space left" when they have plenty of it...

**Comment by poettering** [comment]
sure, but still, my other comments really should be addressed before this can be merged...

**Comment by poettering** [comment]
ping?

**Comment by jsynacek** [comment]
Still have this on my todo list. I will bump the priority a bit.

**Comment by jsynacek** [comment]
v2.
