### PR TITLE
 bus-util: print a friendly message when PID1 is not systemd

### LINKED ISSUE #8913: *ctl commands give unfriendly error message when run while PID 1 <> systemd
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 238.76-1

### Used distribution

> Arch Linux

My main desktop is setup as  a multi-init system  with both systemd and openrc installed.

When I boot with openrc as PID 1 many systemd commands return a vague , unfriendly error message.
example : 
```
loginctl
Failed to list sessions: Launch helper exited with unknown return code 1
```

I reported this before in https://bugzilla.freedesktop.org/show_bug.cgi?id=69962 and that was solved for systemctl in https://github.com/systemd/systemd/pull/7318 .

I overlooked that PR only solved the issue for systemctl and had no impact on other systemd *ctl commands.

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for 861f16d2679eeda79e8185057cef24653913e300.

Fixes #8913.

### CODE REVIEW

File: src/shared/bus-util.c [hunk 1]
```diff
@@ -1295,6 +1295,13 @@ int bus_connect_transport(BusTransport transport, const char *host, bool user, s
         assert_return((transport == BUS_TRANSPORT_LOCAL) == !host, -EINVAL);
         assert_return(transport == BUS_TRANSPORT_LOCAL || !user, -EOPNOTSUPP);
 
+        if (!user && sd_booted() <= 0) {
```
Comment (keszybz) [inline src/shared/bus-util.c]: Even if `host` is set, this check could be true. But I think it's not necessary to have systemd running locally for remote transport.

File: src/shared/bus-util.c [hunk 2]
```diff
@@ -1338,6 +1345,13 @@ int bus_connect_transport_systemd(BusTransport transport, const char *host, bool
...
+                /* Print a friendly message when the local system is actually not running systemd as PID 1. */
```
Comment (keszybz) [inline src/shared/bus-util.c]: Same here.

File: src/shared/bus-util.c (hunk 1 above)
Comment (yuwata) [reply src/shared/bus-util.c]: Yeah, so I've asked in telegram few days ago. @poettering said
> It requires systemd to be installed since it needs that stdio-to-dbus bridge to work

Comment (yuwata) [reply src/shared/bus-util.c]: Ah, the necessary condition is that systemd is 'installed', not 'running'. Is it true? I am not sure now. I will check it later.

Comment (yuwata) [reply src/shared/bus-util.c]: Or am I misunderstanding some points?

Comment (keszybz) [reply src/shared/bus-util.c]: `systemd-stdio-bridge` is executed on the remote side, not local. So I don't think there's any requirement locally. Remotely, systemd needs to be installed, so that `systemd-stdio-bridge` is present, and dbus needs to be running, but we cannot check this locally.

Comment (yuwata) [reply src/shared/bus-util.c]: It seems that the necessary condition is `systemd` is running on the _remote_ host. Not local.

**Comment by yuwata** [comment]
@keszybz Updated. Please take a look. Thank you.

File: src/shared/bus-util.c (hunk 1 above)
Comment (yuwata) [reply src/shared/bus-util.c]: Ah, we posted almost the same time. Thank you for the clarification. I've confirmed that.
