### PR TITLE
vpick: Fix pick_filter_image_any

### LINKED ISSUE #40083: vpick pick_filter_image_any matches too much
### systemd version the issue has been seen with

main

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

other

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

```
const PickFilter pick_filter_image_any = {
        .type_mask = (UINT32_C(1) << DT_REG) | (UINT32_C(1) << DT_BLK) | (UINT32_C(1) << DT_DIR),
        .architecture = _ARCHITECTURE_INVALID,
        .suffix = STRV_MAKE(".raw", ""),
};
```

This doesn't just match .raw image files and directory images, it also matches:
- Directory images with a .raw suffix
- Image files with any possible suffix

Every file and directory ends with the empty suffix and so every single file and directory in the .v directory will be considered. Since this is supposed to be the combo of `pick_filter_image_raw` and `pick_filter_image_dir`, I'd argue this is not the behavior we want. What we probably want is to look at every directory regardless of suffix, which matches `pick_filter_image_dir`, and to only look at image files with the .raw suffix, which matches `pick_filter_image_raw`. But currently `pick_filter_image_any` matches wayyyy more than that, which is arguably broken.

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by daandemeyer**
vpick: Fix pick_filter_image_any
Currently, pick_filter_image_any matches any image
with any suffix, which is way more than it should
be doing. It should only be matching images with
the .raw suffix.

Let's address this shortcoming by allowing to pass
multiple filters to path_pick(), and define
pick_filter_image_any as the combination of the
raw and directory image filters.

Fixes #40083

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
I don't like this, this is just too magic for me, to process things systematically different for dirs than for reg files. the .mtree dir stuff in #39621 wouldn't work with this, since the mtree suffix is really load bearing there for dirs.

i'd prefer if we just allow passing multiple filters instead.

**Comment by daandemeyer** [comment]
Always fun when you have to rewrite the entire thing to actually make it work in a somewhat sane way :/

File: src/shared/vpick.c [hunk 1]
```diff
@@ -412,89 +449,70 @@ static int make_choice(
...
+                        .path = TAKE_PTR(p),
+                        .fd = TAKE_FD(object_fd),
+                        .st = st,
+                        .version = strdup(e),
+                        .architecture = a,
+                        .tries_left = found_tries_left,
+                        .tries_done = found_tries_done,
+                };
+                if (!found.version)
+                        return -ENOMEM;
```
Comment (YHNdnzj) [inline src/shared/vpick.c]: hmm? why duplicate pin_choice here?

Comment (DaanDeMeyer) [reply src/shared/vpick.c]: Because it does too much, specifically fail if the type is wrong.

Comment (daandemeyer) [reply src/shared/vpick.c]: @YHNdnzj Good point, I only changed `pin_choice()` to return zero on wrong inode type later on. It's only after that change that it became usable here, but I forgot to refactor this to use it when I made that change.

Switched to using `pin_choice()` here now.

File: src/shared/vpick.h [hunk 2]
```diff
@@ -43,22 +43,29 @@ typedef struct PickResult {
...
 int path_uses_vpick(const char *path);
 
-extern const PickFilter pick_filter_image_raw;
-extern const PickFilter pick_filter_image_dir;
-extern const PickFilter pick_filter_image_any;
+extern const PickFilter pick_filter_image_raw[1];
+extern const PickFilter pick_filter_image_dir[1];
+
+#define pick_filter_image_any (PickFilter[]) {          \
+        *pick_filter_image_raw,                         \
```
Comment (poettering) [inline src/shared/vpick.h]: `pick_filter_image_raw[0]` seems more obvious to me, given this is really an array

File: src/shared/vpick.h [hunk 3]
```diff
@@ -43,22 +43,29 @@ typedef struct PickResult {
...
+        *pick_filter_image_dir,                         \
```
Comment (poettering) [inline src/shared/vpick.h]: ditto

File: src/shared/vpick.h [hunk 4]
```diff
@@ -43,22 +43,29 @@ typedef struct PickResult {
...
 
 int path_uses_vpick(const char *path);
 
-extern const PickFilter pick_filter_image_raw;
-extern const PickFilter pick_filter_image_dir;
-extern const PickFilter pick_filter_image_any;
+extern const PickFilter pick_filter_image_raw[1];
+extern const PickFilter pick_filter_image_dir[1];
+
+#define pick_filter_image_any (PickFilter[]) {          \
```
Comment (poettering) [inline src/shared/vpick.h]: maybe make this `(const PickFilter[])`

File: src/shared/vpick.c [hunk 5]
```diff
@@ -248,6 +295,21 @@ static int parse_tries(const char *s, unsigned *ret_tries_left, unsigned *ret_tr
         return 0;
 }
 
+static bool architecture_matches(const PickFilter *filter, Architecture a) {
```
Comment (poettering) [inline src/shared/vpick.c:298]: `assert(filter);`

File: src/shared/vpick.h [hunk 6]
```diff
@@ -43,22 +43,29 @@ typedef struct PickResult {
...
+              const char *path,
+              const PickFilter *filters,
+              size_t n_filters,
+              PickFlags flags,
+              PickResult *ret);
 
 int path_pick_update_warn(
                 char **path,
-                const PickFilter *filter,
+                const PickFilter *filters,
```
Comment (poettering) [inline src/shared/vpick.h]: doesn't matter much but for arguments that are understood to be arrays we should write filters[] rather than *filters, to communicate that to the reader, even if this is effectively the same

File: src/shared/vpick.c [hunk 7]
```diff
@@ -644,9 +650,60 @@ int path_pick(
...
+                        return r;
+                if (r == 0)
+                        continue;
+
+                if (!best.path) {
+                        best = TAKE_PICK_RESULT(result);
+                        continue;
+                }
+
+                if (pick_result_compare(&result, &best, flags) < 0) {
```
Comment (poettering) [inline src/shared/vpick.c]: i'd use `<=` here i think. shouldn't matter, but I'd still make it a conceptually a "first found wins",

**Comment by poettering** [comment]
lgtm, just coding style nits
