### PR TITLE
man: add details on disabling a top-level drop in for specific units.

### LINKED ISSUE #17602: pid1: a Wants=foo@%n.service in a service foo@.service creates too many units
**systemd version the issue has been seen with**
 246.6

**Used distribution**
 Arch Linux

**Linux kernel version used** (`uname -a`)
 5.9.3-arch1-1

**CPU architecture issue was seen on**
 x86_64

**Expected behaviour you didn't see**
Only one additional (notify) service should be created for every unit on the system.

**Unexpected behaviour you saw**

1550 services are created from the template:

```
systemctl show systemd-notify@
zsh: do you wish to see all 1200 possibilities (1550 lines)? 
```
```
...
systemd-notify@systemd-notify@systemd-notify@systemd-journal-flush.service.service.service.service
systemd-notify@systemd-notify@systemd-notify@systemd-logind.service.service.service.service
systemd-notify@systemd-notify@systemd-notify@systemd-machined.service.service.service.service
systemd-notify@systemd-notify@systemd-notify@systemd-machine-id-commit.service.service.service.service
systemd-notify@systemd-notify@systemd-notify@systemd-modules-load.service.service.service.service
...
```

"hundreds" of entries like this in the log:
```
Nov 13 20:06:18 icarus systemd[1]: /etc/systemd/system/service.d/10-override.conf:3: Failed to add dependency on systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@updatedb.service.service.service.service.service.service.service.service.service.service.service.service, ignoring: Invalid argument
Nov 13 20:06:18 icarus systemd[1]: /etc/systemd/system/service.d/10-override.conf:3: Failed to add dependency on systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-tmpfiles-clean.service.service.service.service.service.service.service.service.service.service.service, ignoring: Invalid argument
Nov 13 20:06:18 icarus systemd[1]: /etc/systemd/system/service.d/10-override.conf:3: Failed to add dependency on systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@emergency.service.service.service.service.service.service.service.service.service.service.service.service, ignoring: Invalid argument
Nov 13 20:06:18 icarus systemd[1]: /etc/systemd/system/service.d/10-override.conf:3: Failed to add dependency on systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@rescue.service.service.service.service.service.service.service.service.service.service.service.service, ignoring: Invalid argument
```

**Steps to reproduce the problem**

Create top-level drop-in with OnFailure override:
```
/etc/systemd/system/service.d/10-override.conf
[Unit]
OnFailure=systemd-notify@%n.service
```

Create template unit:
```
/etc/systemd/system/systemd-notify@.service
[Unit]
Description=Send desktop notification to user on unit failure

[Service]
Type=oneshot
ExecStart=su user -c "DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send --urgency=critical 'Systemd unit %i failed.' \
  'See \"systemctl status %i\" and \"journalctl -xe\" for details.'"
```

### PR DESCRIPTION
**Pull request by pdmorrow**
Hello,

If have a pattern like this:

```
root@machine:/run/systemd/system# cat service.d/10-all.conf
[Unit]
OnFailure=failure-handler@%n.service
root@machine:/run/systemd/system#
```

Template failure handler for all services:

```
root@machine:/run/systemd/system# cat failure-handler@.service
[Unit]
Description=Failure handler service for %I

[Service]
Type=oneshot
ExecStart=/bin/echo %I failed
root@machine:/run/systemd/system#
```

This works fine except for the template unit itself:

```
root@machine:/run/systemd/system# systemctl show --value -p OnFailure failure-handler@failing-service.service
failure-handler@failure-handler@failing-service.service.service
root@machine:/run/systemd/system#
```

As expected there is a dependency `failure-handler@failure-handler@failing-service.service.service` added for `failure-handler@failing-service.service.service`.

It's possible to never install this recursive dependency if we create a symlink like this:

```
root@machine:/run/systemd/system# mkdir failure-handler@.service.d
root@machine:/run/systemd/system# ln -s /dev/null failure-handler@.service.d/10-all.conf
```

This PR makes it clear in the unit man page that this is the best way to change something specific to a unit when top-level drop-ins are in use.

Fixes #17602

### CODE REVIEW

File: src/core/unit.c [hunk 1]
```diff
@@ -5056,6 +5056,52 @@ static void unit_update_dependency_mask(Hashmap *deps, Unit *other, UnitDependen
...
+        assert(d < _UNIT_DEPENDENCY_MAX);
+        assert(u);
+
+        /* Removes all dependencies of type d that u has on other units marked
+         * for ownership by 'mask'. */
+
+        if (mask == 0)
+                return;
+
+        do {
```
Comment (bluca) [inline src/core/unit.c]: Dependencies now are mapped via hashmap, given you have the type which is used as key, why not just using it instead of a full iteration, which sounds expensive?

Comment (pdmorrow) [reply src/core/unit.c]: Makes sense, thanks. I'll re-work.

Comment (pdmorrow) [reply src/core/unit.c]: Re-worked, we do still need to iterate on the back dependencies but we can get rid of the forward dependencies in 1 swoop. The changes make this mask agnostic, i.e. dependencies from any source are considered for removal.  PTAL!

**Review by bluca — APPROVED** [review]
lgtm - waiting for one more reviewer

File: test/units/testsuite-60.sh [hunk 2]
```diff
@@ -0,0 +1,177 @@
...
+    if [[ "$units" == *"failure-handler@failure-handler"* ]]; then
+        # We saw some recursive dependencies generated, fail the test.
+        return 1
+    fi
+
+    # We only expect to see failing-service.service and
+    # failure-handler@failing-service.service in the failed state, there
+    # shouldn't be a failure-handler@failure-handler@failing-service.service.
+    nr_failed_units="$(systemctl list-units --no-legend --no-pager | grep -c failed)"
+    if [ "${nr_failed_units}" != "2"]; then
```
Comment (bluca) [inline test/units/testsuite-60.sh]: Shellcheck is not happy: missing space before `]` (yay bash)

```
In test/units/testsuite-60.sh line 107:
    if [ "${nr_failed_units}" != "2"]; then
    ^-- SC1009: The mentioned syntax error was in this if expression.
       ^-- SC1073: Couldn't parse this test expression. Fix to allow more checks.
                                     ^-- SC1020: You need a space before the ].
                                     ^-- SC1072: Missing space before ]. Fix any mentioned problems and try again.
```

File: test/TEST-60-CLEAR-ON-FAILURE-DEPS/test.sh [hunk 3]
```diff
@@ -0,0 +1,8 @@
+#!/usr/bin/env bash
+set -e
+TEST_DESCRIPTION="Test OnFailure dependency removal via drop ins"
+TEST_NO_QEMU=1
+
+. $TEST_BASE_DIR/test-functions
+
+do_test "$@" 60
```
Comment (bluca) [inline test/TEST-60-CLEAR-ON-FAILURE-DEPS/test.sh]: you don't need to pass `60` anymore

**Comment by poettering** [comment]
Hmm, this doesn't look right to me. First of all, if you do this for OnFailure=, you should do this for OnSuccess=, too, at the very least. But people might wonder why not for the other deps too? Moreover, we might want to add implicit, automatic dep of this types one day too and then any code that removes these without taking the `UnitDependencyMask` into account isn't right.

But I wonder if we need this at all. i.e. instead of adding a drop-in whose contents undoes what another drop-in did, would it not suffice to ensure that we can safely *mask* (as in: symlink to /dev/null) a drop-in in a *specific* unit that was added as per-unit-type *global* drop-in?

i.e. i think this should already work:

```sh
mkdir -p /etc/systemd/system/service.d
cat << EOF > /etc/systemd/system/service.d/47-foo.conf
[Unit]
OnSuccess=myonsuccess@%N.service
EOF
mkdir /etc/systemd/system/myonsuccess@.service.d
ln -s /dev/null /etc/systemd/system/myonsuccess@.service.d/47-foo.conf
```

And if it doesn't, then we should make it work.

The good thing is that we don't need any conceptually new infra here, and you can use it to mask *any* setting the same way.

**Comment by poettering** [comment]
So, if that works already, I think this would be primarily a documentation bug: i.e. the documentaiton of the .d/ drop-ins should explain the issue and suggest adding the mask symlink to break the inclusion loop

**Comment by bluca** [comment]
very nice idea, hadn't thought of that - @pdmorrow could you please check if that works as expected?

**Comment by poettering** [comment]
that said, thinking about this, we could probably support undoing deps comprehensively, but if so it needs to be done by UnitDependencyMask flag (i.e. taking into account not only the dep type, but also *why* a dep was created), and that would need some more love.

Specifically, right now there is the UNIT_DEPENDENCY_FILE flags that marks a dep as being created because of one of three kinds of cases: deps generated via an explicit unit setting, deps generated via .wants/ and .requires/ symlinks, and deps created as immediate effect of another flag. We'd need to split this up so that the explicit unit setting gets a flag on its own, since setting OnFailure= in a unit file or drop-in should only unset the deps created by a unit file or drop-in, but let all deps created by other means in place.

unit_remove_dependencies() already implements deleting deps by `UnitDependencyMask` flags. It currently doesn't care about dep type, since we didn't need that so far. It would should be updated I guess to also take a UnitDependency enum as parameter that if set limits the dep types it removes.

This would solve a bigger, long-standing request people have: that you can undo any kind of dep via an empty assignment. I think that would be great to have, indeed. But it should really support any type of dep, and we need to make very clear that deps created for other reasons (implicitly or due to DefaulfDependencies=yes, and so on) cannot be undone this way.

**Comment by pdmorrow** [comment]
> very nice idea, hadn't thought of that - @pdmorrow could you please check if that works as expected?

@poettering @bluca Thanks! Lennarts suggestion works nicely.

**Comment by pdmorrow** [comment]
> that said, thinking about this, we could probably support undoing deps comprehensively, but if so it needs to be done by UnitDependencyMask flag (i.e. taking into account not only the dep type, but also _why_ a dep was created), and that would need some more love.
> 
> Specifically, right now there is the UNIT_DEPENDENCY_FILE flags that marks a dep as being created because of one of three kinds of cases: deps generated via an explicit unit setting, deps generated via .wants/ and .requires/ symlinks, and deps created as immediate effect of another flag. We'd need to split this up so that the explicit unit setting gets a flag on its own, since setting OnFailure= in a unit file or drop-in should only unset the deps created by a unit file or drop-in, but let all deps created by other means in place.
> 
> unit_remove_dependencies() already implements deleting deps by `UnitDependencyMask` flags. It currently doesn't care about dep type, since we didn't need that so far. It would should be updated I guess to also take a UnitDependency enum as parameter that if set limits the dep types it removes.
> 
> This would solve a bigger, long-standing request people have: that you can undo any kind of dep via an empty assignment. I think that would be great to have, indeed. But it should really support any type of dep, and we need to make very clear that deps created for other reasons (implicitly or due to DefaulfDependencies=yes, and so on) cannot be undone this way.

Agreed, certainly this PR is/was targeted at a very simple single use case. I'm very happy to spent some time on doing this more comprehensively. I'll close this PR in the meantime.

Cheers.

**Comment by bluca** [comment]
@pdmorrow could you please reopen this and use it to update the documentation? I figure explicitly mentioning here that symlinks to /dev/null are also possible to disable the global override should suffice: https://github.com/systemd/systemd/blob/main/man/systemd.unit.xml#L231

**Comment by pdmorrow** [comment]
> @pdmorrow could you please reopen this and use it to update the documentation? I figure explicitly mentioning here that symlinks to /dev/null are also possible to disable the global override should suffice: https://github.com/systemd/systemd/blob/main/man/systemd.unit.xml#L231

Sure, will do.

**Review by bluca — APPROVED** [review]
Thanks! LGTM

File: man/systemd.unit.xml [hunk 4]
```diff
@@ -228,7 +228,9 @@
     Configurations in <filename><replaceable>type</replaceable>.d/</filename> have the lowest precedence
     compared to settings in the name specific override directories. So the contents of
     <filename>foo-.service.d/10-override.conf</filename> would override
-    <filename>service.d/10-override.conf</filename>.</para>
+    <filename>service.d/10-override.conf</filename>. In order to disable a top-level drop-in for a specific unit
+    it suffices to create a symlink to <filename>/dev/null</filename> from the unit drop-in directory. This symlink
+    should have the same name as the top-level drop-in file.</para>
```
Comment (poettering) [inline man/systemd.unit.xml]: i think we should more explicitly mention the issue people ran into: something akin to this:

"Note that per-unit-type drop-ins generally apply to *all* units of the same type. This means that if you use such a drop-in to instantiate for each unit a secondary helper unit of the same type (e.g. consider a drop-in for service units with an `OnFailure=myfailurehandler@%N.service` line) the drop-in will also apply to that secondary helper unit, and then create another helper unit for that, and so on, until the unit name grows beyond the unit name limit. To break this recursion consider masking the per-unit-type drop-in in a drop-in specific to the secondary helper unit, by creating a /dev/null symlink with the same name as the per-unit-type drop-in."

And then maybe even give a brief exmaple?

**Comment by poettering** [comment]
(I am not a native speaker. I am pretty sure my suggestion above could be reworded to be clearer. It's a confusing topic...)

File: man/systemd.unit.xml (hunk 4 above)
Comment (keszybz) [reply man/systemd.unit.xml]: I like the proposed paragraph, but I think it should be moved to a separate section in Examples below. Here we are trying to explain basic logic, and this part is already very long. We shouldn't add a very complicated paragraph about a specific case that can be deduced from the general rules.

So instead change:
> `Configurations in <filename><replaceable>type</replaceable>.d/</filename> have the lowest precedence compared to settings in the name specific override directories`

to
> `Files in <filename><replaceable>type</replaceable>.d/</filename> have lower precedence compared to files in name-specific override directories. (The usual rules apply: multiple drop-in files with different names are applied in lexicographic order, regardless of which of the directories they reside in, so a file in <filename><replaceable>type</replaceable>.d/</filename> applies to a unit only if there are no drop-ins or masks with that name in directories with higher precedence. See Examples.)`

The old text was bad in a few ways: apart from the grammatical awkwardness, precedence is decided on the level of files not individual settings, so saying that "configuration ... have precedence" can be misleading.

Comment (pdmorrow) [reply man/systemd.unit.xml]: Thanks, I've made an attempt at this. PTAL!

Comment (bluca) [reply man/systemd.unit.xml]: Looks good, also checked the rendered version

File: man/systemd.unit.xml [hunk 5]
```diff
@@ -2188,6 +2190,61 @@ PrivateTmp=yes</programlisting>
...
+
+    <example>
+      <title>Top level drop-ins with template units</title>
+
+      <para>Top level drop-ins can be used to change some aspect of all units
+      of a particular type. For example by creating the
+      <filename index='false'>/etc/systemd/system/service.d</filename>
+      directory with a drop-in file, the contents of the drop-in file can be
+      applied to all service units. We can take this further by having the
+      top-level drop-in instantiate a secondary helper unit of the same type.
```
Comment (keszybz) [inline man/systemd.unit.xml]: "of the same type." seems unnecessary.

File: man/systemd.unit.xml [hunk 6]
```diff
@@ -2188,6 +2190,61 @@ PrivateTmp=yes</programlisting>
...
+      Consider for example the following set of units and drop-in files where
+      we install an OnFailure dependency for all service units.</para>
```
Comment (keszybz) [inline man/systemd.unit.xml]: `<varname>OnFailure=</varname>`

File: man/systemd.unit.xml [hunk 7]
```diff
@@ -2188,6 +2190,61 @@ PrivateTmp=yes</programlisting>
...
+Description=My failure handler for %i
+
+[Service]
+Type=oneshot
+# Perform some special action for when %i exits unexpectedly.
+ExecStart=/usr/sbin/myfailurehandler %i
+
+     </programlisting>
+
+    <para>We can then add an instance of the failure-handler@.service as an
```
Comment (keszybz) [inline man/systemd.unit.xml]: `<filename index='false'>failure-handler@.service</filename>`

File: man/systemd.unit.xml [hunk 8]
```diff
@@ -2188,6 +2190,61 @@ PrivateTmp=yes</programlisting>
...
+    OnFailure dependency for all service units.</para>
```
Comment (keszybz) [inline man/systemd.unit.xml]: `<varname>OnFailure=</varname>`

File: man/systemd.unit.xml [hunk 9]
```diff
@@ -2188,6 +2190,61 @@ PrivateTmp=yes</programlisting>
...
+    <para>
+    <filename index='false'>/etc/systemd/system/service.d/10-all.conf</filename>:</para>
+
+    <programlisting>[Unit]
+OnFailure=failure-handler@%n.service
+    </programlisting>
+
+    <para>Now, after running <command>systemctl daemon-reload</command> all
+    services will have acquired an OnFailure dependency on
+    failure-handler@%n.service. The template instance units will also have
```
Comment (keszybz) [inline man/systemd.unit.xml]: Similarly here.

File: man/systemd.unit.xml [hunk 10]
```diff
@@ -2188,6 +2190,61 @@ PrivateTmp=yes</programlisting>
...
+
+    <programlisting>
+<command>mkdir /etc/systemd/system/failure-handler@.service.d</command>
+<command>ln -s /dev/null /etc/systemd/system/failure-handler@.service.d/10-all.conf</command>
+<command>systemctl daemon-reload</command>
+    </programlisting>
+
+    <para>This ensures that if a failure-handler@.service instance fails it
+    will not trigger an instance named
+    failure-handler@failure-handler.service.service.</para>
```
Comment (keszybz) [inline man/systemd.unit.xml]: And in this para.

**Review by keszybz — COMMENTED** [review]
Looks good, but please add markup.

File: man/systemd.unit.xml [hunk 11]
```diff
@@ -2188,6 +2190,62 @@ PrivateTmp=yes</programlisting>
...
+      <title>Top level drop-ins with template units</title>
+
+      <para>Top level drop-ins can be used to change some aspect of all units
+      of a particular type. For example by creating the
+      <filename index='false'>/etc/systemd/system/service.d</filename>
+      directory with a drop-in file, the contents of the drop-in file can be
+      applied to all service units. We can take this further by having the
+      top-level drop-in instantiate a secondary helper unit. Consider for
+      example the following set of units and drop-in files where we install
+      an OnFailure dependency for all service units.</para>
```
Comment (poettering) [inline man/systemd.unit.xml:2204]: `OnFailure` → `<varname>OnFailure=</varname>`

File: man/systemd.unit.xml [hunk 12]
```diff
@@ -2188,6 +2190,62 @@ PrivateTmp=yes</programlisting>
       to override the entire unit.</para>
 
     </example>
+
+    <example>
+      <title>Top level drop-ins with template units</title>
+
+      <para>Top level drop-ins can be used to change some aspect of all units
+      of a particular type. For example by creating the
+      <filename index='false'>/etc/systemd/system/service.d</filename>
```
Comment (poettering) [inline man/systemd.unit.xml:2199]: please suffix dirs with `/` in docs and log message, see coding style

File: man/systemd.unit.xml [hunk 13]
```diff
@@ -2188,6 +2190,62 @@ PrivateTmp=yes</programlisting>
       to override the entire unit.</para>
 
     </example>
+
+    <example>
+      <title>Top level drop-ins with template units</title>
+
+      <para>Top level drop-ins can be used to change some aspect of all units
```
Comment (poettering) [inline man/systemd.unit.xml:2197]: I'd say `top level per-type drop-ins`

File: man/systemd.unit.xml [hunk 14]
```diff
@@ -2188,6 +2190,62 @@ PrivateTmp=yes</programlisting>
...
+      <filename index='false'>/etc/systemd/system/failure-handler@.service</filename>:</para>
+
+      <programlisting>[Unit]
+Description=My failure handler for %i
+
+[Service]
+Type=oneshot
+# Perform some special action for when %i exits unexpectedly.
+ExecStart=/usr/sbin/myfailurehandler %i
+
```
Comment (poettering) [inline man/systemd.unit.xml:2216]: spurious double newline

File: man/systemd.unit.xml [hunk 15]
```diff
@@ -2188,6 +2190,62 @@ PrivateTmp=yes</programlisting>
...
+     <para>We can then add an instance of the
+     <filename index='false'>failure-handler@.service</filename> as an
+     <varname>OnFailure=</varname> dependency for all service units.</para>
+
+    <para>
+    <filename index='false'>/etc/systemd/system/service.d/10-all.conf</filename>:</para>
+
+    <programlisting>[Unit]
+OnFailure=failure-handler@%n.service
```
Comment (poettering) [inline man/systemd.unit.xml:2227]: i think the example should better use %N. `.service.service` is really not pretty.

File: man/systemd.unit.xml [hunk 16]
```diff
@@ -2188,6 +2190,62 @@ PrivateTmp=yes</programlisting>
...
+    <filename index='false'>/dev/null</filename>:</para>
+
+    <programlisting>
+<command>mkdir /etc/systemd/system/failure-handler@.service.d</command>
+<command>ln -s /dev/null /etc/systemd/system/failure-handler@.service.d/10-all.conf</command>
+<command>systemctl daemon-reload</command>
+    </programlisting>
+
+    <para>This ensures that if a <filename index='false'>failure-handler@.service</filename> instance fails it will not trigger an instance named
+    <filename index='false'>failure-handler@failure-handler.service.service</filename>.</para>
```
Comment (poettering) [inline man/systemd.unit.xml:2245]: when chaning %n to %N above, one `.service` should be dropped here

File: man/systemd.unit.xml (hunk 12 above)
Comment (pdmorrow) [reply man/systemd.unit.xml:2199]: ack. I'll send a follow up PR to address your comments since it looks like this one got merged already
