### PR TITLE
network: fix PreferredLifetime=0

### LINKED ISSUE #13341: networkd v241: default route missing when other address has `PreferredLifetime=0`
**systemd version the issue has been seen with**
> systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

from systemd package in debian `stretch-backports` repository

**Used distribution**
 > debian stretch (with backports). Initially seen on a `debootstrap` generated image running on bare metal with real network interfaces but I can also reproduce in docker containers running stretch, buster and sid.

**Expected behaviour you didn't see**
 > Default route to be added in both cases

**Unexpected behaviour you saw**
 > Default route was missing when `PreferredLifetime=0` was added to an unrelated address on the same interface. This did not happen in v239 on the same Debian image

**Steps to reproduce the problem**
This is the minimum I could do to reproduce the issue. Note that here I am using a `bridge` but we first noticed the same behaviour on `vlan` interfaces when running on bare metal. I used Docker to demonstrate this, but it happens the same on pretty much any platform

Dockerfile: https://gist.github.com/frebib/95a3bc1c180447549257dcaa7f1ed57b/raw
Docker run: `docker run --rm -dti --name=networkd-test --privileged --security-opt seccomp=unconfined -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v $PWD/network:/etc/systemd/network frebib/systemd:sid`

`bind.network`:
```ini
[Match]
Name=eth*

[Network]
Bridge=net0
```

`net0.netdev`:
```ini
[NetDev]
Name=net0
Kind=bridge
```

`net0.network`:
```ini
[Match]
Name=net0

[Network]
# Work around https://github.com/systemd/systemd/issues/12784
LinkLocalAddressing=no

[Route]
Gateway=20.20.20.1

[Address]
Address=20.20.20.100/24

[Address]
Address=40.40.40.100/24
#PreferredLifetime=0
```

### Without `PreferredLifetime=0`
There is a default route added here as you would expect
networkd debug logs: https://gist.github.com/frebib/a7484747fe1056a8dbe6f49113b0bc75/raw
```
root@e9b1479b0efc:/# ip addr show dev net0
2: net0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 72:15:6d:d7:aa:fd brd ff:ff:ff:ff:ff:ff
    inet 20.20.20.100/24 brd 20.20.20.255 scope global net0
       valid_lft forever preferred_lft forever
    inet 40.40.40.100/24 brd 40.40.40.255 scope global net0
       valid_lft forever preferred_lft forever

root@e9b1479b0efc:/# ip ro show dev net0
default via 20.20.20.1 proto static
20.20.20.0/24 proto kernel scope link src 20.20.20.100
40.40.40.0/24 proto kernel scope link src 40.40.40.100

root@e9b1479b0efc:/# networkctl status net0
* 2: net0
       Link File: /lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/net0.network
            Type: bridge
           State: routable (configured)
          Driver: bridge
      HW Address: 72:15:6d:d7:aa:fd
         Address: 20.20.20.100
                  40.40.40.100
         Gateway: 20.20.20.1
```

### With `PreferredLifetime=0`
The default route is now missing, and networkd seems to be waiting for something, note `(configuring)` state.
networkd debug logs: https://gist.github.com/frebib/9df21b551cdb197774d51f61539d7b20/raw
```
root@c555f11f732e:/# ip addr show dev net0
2: net0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 72:15:6d:d7:aa:fd brd ff:ff:ff:ff:ff:ff
    inet 20.20.20.100/24 brd 20.20.20.255 scope global net0
       valid_lft forever preferred_lft forever
    inet 40.40.40.100/24 brd 40.40.40.255 scope global deprecated net0
       valid_lft forever preferred_lft forever

root@c555f11f732e:/# ip ro show dev net0
20.20.20.0/24 proto kernel scope link src 20.20.20.100
40.40.40.0/24 proto kernel scope link src 40.40.40.100

root@c555f11f732e:/# networkctl status net0
* 2: net0
       Link File: /lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/net0.network
            Type: bridge
           State: routable (configuring)
          Driver: bridge
      HW Address: 72:15:6d:d7:aa:fd
         Address: 20.20.20.100
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #13341.

### CODE REVIEW

File: src/network/networkd-address.c [hunk 1]
```diff
@@ -978,7 +981,7 @@ int config_parse_address_scope(const char *unit,
 bool address_is_ready(const Address *a) {
         assert(a);
 
-        if (a->family == AF_INET6)
+        if (a->family == AF_INET6 || a->preferred_lifetime_is_zero)
```
Comment (frebib) [inline src/network/networkd-address.c]: How does `preferred_lifetime_is_zero` differ from `IFA_F_DEPRECATED`? Aren't they the same thing?
Also this never changed post-v239 so what was it that introduced the bug?

Comment (yuwata) [reply src/network/networkd-address.c]: When `PreferredLifetime=0`, the address has `IFA_F_DRPRECATED`, and it is expected. So, networkd considered that the address is ready even if the flag is set.

Without this change, the address cannot be ready, and thus, no consequent setting up process does not start. This is why you get the link state is in `configuring` rather than `configured`.

Comment (yuwata) [reply src/network/networkd-address.c]: > Also this never changed post-v239 so what was it that introduced the bug?

I guess 6aa5773bfff0a92d64da70426cae833df6f84daf introduced the bug.

Comment (frebib) [reply src/network/networkd-address.c]: Apologies if I'm missing something here

> When `PreferredLifetime=0`, the address has `IFA_F_DRPRECATED`

If this is the case, can the function just be reduced to  `return !(a->flags & IFA_F_TENTATIVE);`? Or is there a case where an address is deprecated but `PreferredLifetime!=0`? I feel like the logic is duplicated

Comment (yuwata) [reply src/network/networkd-address.c]: Thank you for the comment. Updated. PTAL.

Comment (frebib) [reply src/network/networkd-address.c]: Looks good, I hope it's correct. Please don't take my word for it though, I'm not entirely sure how it is supposed to work. There was probably a reason the IFA_F_DEPRECATED check was used originally

Comment (frebib) [reply src/network/networkd-address.c]: Just tried and it seems possible to add routes to a deprecated address, so I'm not sure why it was even there in the first place :man_shrugging: 
I'll try this out tomorrow in the testing environment and let you know how it goes. Thanks very much :)

**Comment by frebib** [comment]
Just to confirm, this seems to be working as it previously did. Thanks all for the quick take-up and turn-around :)
