### PR TITLE
bootctl: fix case-sensitive comparisons in reporting bootloader entries

### LINKED ISSUE #30159: bootctl list shows spurious mismatch due to case
### systemd version the issue has been seen with

systemd-254.5-2.fc39.x86_64

### Used distribution

Fedora 39

### Linux kernel version used

6.5.11-300.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

`bootctl list` should correctly match _/boot/loader/entries_ having uppercase characters, or otherwise be case insensitive when determining new/absent entries

### Unexpected behaviour you saw

`bootctl list` has identified the following entry as `not reported/new`
```
           id: b15ac8eef3e44d67984d2034a33a47d4-6.5.11-300-nVidia-only.fc39.x86_64.conf
       source: /boot//loader/entries/b15ac8eef3e44d67984d2034a33a47d4-6.5.11-300-nVidia-only.fc39.x86_64.conf
```

and identified the following `Reported by Boot Loader` as `reported/absent`
```
           id: b15ac8eef3e44d67984d2034a33a47d4-6.5.11-300-nvidia-only.fc39.x86_64.conf
       source: /sys/firmware/efi/efivars/LoaderEntries-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
```

Note the difference in case (nVidia vs nvidia)

I am able to rectify the issue by renaming the file to match what is reported by the boot loader, though I note that the filesystem appears to behave as if it were case insensitive

```
   root]# mv b15ac8eef3e44d67984d2034a33a47d4-6.5.11-300-nVidia-only.fc39.x86_64.conf b15ac8eef3e44d67984d2034a33a47d4-6.5.11-300-nvidia-only.fc39.x86_64.conf
   mv: 'b15ac8eef3e44d67984d2034a33a47d4-6.5.11-300-nVidia-only.fc39.x86_64.conf' and 'b15ac8eef3e44d67984d2034a33a47d4-6.5.11-300-nvidia-only.fc39.x86_64.conf' are the same file
```

Renaming to an interim file and back again (without case) resolves the issue,

### Steps to reproduce the problem

Configure a boot leader entry with an uppercase character in the filename

I would expect either
1) The boot loader to report the filename with the correct case; or
2) `bootctl list` to be case insensitive when reporting new/absent

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by khayyamsaleem**
Fixes #30159

### CODE REVIEW

File: src/shared/bootspec.c [hunk 1]
```diff
@@ -1205,8 +1205,8 @@ BootEntry* boot_config_find_entry(BootConfig *config, const char *id) {
         assert(id);
 
         for (size_t j = 0; j < config->n_entries; j++)
-                if (streq_ptr(config->entries[j].id, id) ||
-                    streq_ptr(config->entries[j].id_old, id))
+                if (strcasecmp(config->entries[j].id, id) == 0 ||
```
Comment (poettering) [inline src/shared/bootspec.c]: strcaseeq_ptr() please

Comment (khayyamsaleem) [reply src/shared/bootspec.c]: ahh just found `string-util-fundamental`, thanks for the tip

**Review by bluca — APPROVED** [review]
known issue, you can ignore that
