### PR TITLE
network: set preferred source in removing route entry on address lost

### LINKED ISSUE #12490: networkd: dhcpv4 breaks routing table on IP address change
**systemd version the issue has been seen with**
237, 239

**Used distribution**
Yocto

**Expected behaviour you didn't see**
Default routing table gets properly updated when IP address changes because of DHCP renew.

**Unexpected behaviour you saw**
Duplicate entries are added, including a duplicate default route. This breaks network connectivity.

**Steps to reproduce the problem**

Enable DHCPv4 on a networkd link:

```
[Match]
Name=wan0

[Network]
DHCP=ipv4
```

Connect to a network where the DHCP server likes to change your IP address.

When the IP address changes, the routing table will look like:

```
# ip route show
default via 192.168.0.1 dev wan0 proto dhcp src 192.168.0.137 metric 1024 
default via 192.168.0.1 dev wan0 proto dhcp src 192.168.0.136 metric 1024 
192.168.0.0/24 dev wan0 proto kernel scope link src 192.168.0.136 
192.168.0.1 dev wan0 proto dhcp scope link src 192.168.0.137 metric 1024 
192.168.0.1 dev wan0 proto dhcp scope link src 192.168.0.136 metric 1024 
```

There is 2 default gateway. This breaks basic network connectivity. Even the `ping` command no longer works reliably. It will fail half the time with:

```
# ping 8.8.8.8
connect: Invalid argument
```

The ip addr on the interface is correctly removed, but the routes with the old src ip remain. Although, I believe it is the kernel that removes the IP address from the interface because it is set with an expiration time.

So far, I have found a workaround but I am not sure if it is "right". I simply removed the src address from the routes:

```
diff --git a/src/network/networkd-dhcp4.c b/src/network/networkd-dhcp4.c
index 34c1f63568..5e5315dc0f 100644
--- a/src/network/networkd-dhcp4.c
+++ b/src/network/networkd-dhcp4.c
@@ -151,7 +151,7 @@ static int link_set_dhcp_routes(Link *link) {
                 route_gw->family = AF_INET;
                 route_gw->dst.in = gateway;
                 route_gw->dst_prefixlen = 32;
-                route_gw->prefsrc.in = address;
                 route_gw->scope = RT_SCOPE_LINK;
                 route_gw->protocol = RTPROT_DHCP;
                 route_gw->priority = link->network->dhcp_route_metric;
@@ -165,7 +165,7 @@ static int link_set_dhcp_routes(Link *link) {
 
                 route->family = AF_INET;
                 route->gw.in = gateway;
-                route->prefsrc.in = address;
                 route->priority = link->network->dhcp_route_metric;
                 route->table = table;
```

This fixes the problem for me. 

Although, I've traced the reason for setting src ip in the history:

https://github.com/systemd/systemd/commit/46b0c76e2c355c0d0cc4792abb98cde07b28bc53

So, I believe the "correct" fix is to find out why the old routes are not getting cleared.

Here is a debug log of the IP address change where the routing table gets corrupted:

```
May 04 19:24:04 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0x274c8bcc): REQUEST (renewing)
May 04 19:24:04 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0x274c8bcc): ACK
May 04 19:24:04 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0x274c8bcc): lease expires in 59min 59s
May 04 19:24:04 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0x274c8bcc): T2 expires in 52min 28s
May 04 19:24:04 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0x274c8bcc): T1 expires in 29min 57s
May 04 19:24:04 sentinelc-j8t8sg systemd-networkd[291]: wan0: Updating address: 192.168.0.138/24 (valid for 1h)
May 04 19:24:04 sentinelc-j8t8sg systemd-networkd[291]: wan0: DHCP error: could not get routes: No data available
May 04 19:54:01 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0x274c8bcc): REQUEST (renewing)
May 04 20:05:16 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0x274c8bcc): REQUEST (renewing)
May 04 20:09:59 sentinelc-j8t8sg systemd-networkd[291]: NDISC: Sent Router Solicitation, next solicitation in 56min 13s
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0x274c8bcc): REQUEST (rebinding)
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0x274c8bcc): NAK: n/a
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0xf3baf004): REBOOT in 0
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0xf3baf004): DISCOVER
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0xf3baf004): OFFER
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0xf3baf004): REQUEST (requesting)
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0xf3baf004): ACK
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0xf3baf004): lease expires in 59min 58s
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0xf3baf004): T2 expires in 52min 28s
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: DHCP CLIENT (0xf3baf004): T1 expires in 29min 57s
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: wan0: DHCPv4 address 192.168.0.135/24 via 192.168.0.1
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: Setting transient hostname: 'sentinelc-j8t8sg.ettic.ca'
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: Sent message type=method_call sender=n/a destination=org.freedesktop.hostname1 path=/org/freedesktop/hostname1 interface=org.freedesk>
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: wan0: Updating address: 192.168.0.135/24 (valid for 1h)
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: wan0: DHCP error: could not get routes: No data available
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: Got message type=error sender=:1.8 destination=:1.5 path=n/a interface=n/a member=n/a cookie=5 reply_cookie=103 signature=s error-nam>
May 04 20:16:32 sentinelc-j8t8sg systemd-networkd[291]: Could not set hostname: The name org.freedesktop.PolicyKit1 was not provided by any .service files
May 04 20:24:07 sentinelc-j8t8sg systemd-networkd[291]: wan0: Removing address: 192.168.0.138/24 (valid for 0)
May 04 20:24:07 sentinelc-j8t8sg systemd-networkd[291]: wan0: Updating address: 192.168.0.135/24 (valid for 52min 25s)
```

### LINKED ISSUE #12676: IPv4 DHCP address preliminary expired
systemd 242.19-1

arch Linux 5.0.10-arch1-1-ARCH

**Expected behaviour you didn't see**
 > IPv4 address received via DHCP should stay assigned to interface during lease renewal.

**Unexpected behaviour you saw**
 > On renewal process start address gets immediately removed from the interface. After renewal same address gets reassigned. IPv4 Communication breaks inbetween. Following log illustrates the problem:
```
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): REQUEST (renewing)
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): ACK
Mai 27 18:39:35 xenhost dbus-daemon[509]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.7425' (uid=193 pid>
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): lease expires in 59min 57s
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): T2 expires in 50min 34s
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): T1 expires in 28min 4s
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: DHCP lease lost
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing address 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: Setting transient hostname: 'n/a'
Mai 27 18:39:35 xenhost systemd-networkd[21412]: Sent message type=method_call sender=n/a destination=org.freedesktop.hostname1 path=/org/freedesktop/hostname1 interface=org.freedesktop.hostname1 m>
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: DHCPv4 address 192.168.33.5/24 via 192.168.33.2
Mai 27 18:39:35 xenhost systemd-networkd[21412]: Setting transient hostname: 'xenhost'
Mai 27 18:39:35 xenhost systemd-networkd[21412]: Sent message type=method_call sender=n/a destination=org.freedesktop.hostname1 path=/org/freedesktop/hostname1 interface=org.freedesktop.hostname1 m>
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.2/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: n/a, src: n/a, gw: 192.168.33.2, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing address: 192.168.33.5/24 (valid for 32min 8s)
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.0/24, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.255/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.0/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.5/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding address: 192.168.33.5/24 (valid for 1h)
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding route: dst: 192.168.33.5/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding route: dst: 192.168.33.255/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding route: dst: 192.168.33.0/24, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding route: dst: 192.168.33.0/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: DHCP: No routes received from DHCP server: No data available
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Configuring route: dst: 192.168.33.2/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Configuring route: dst: n/a, src: n/a, gw: 192.168.33.2, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Updating route: dst: 192.168.33.2/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Updating route: dst: n/a, src: n/a, gw: 192.168.33.2, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd[1]: Starting Hostname Service...
Mai 27 18:39:36 xenhost dbus-daemon[509]: [system] Successfully activated service 'org.freedesktop.hostname1'
Mai 27 18:39:36 xenhost systemd[1]: Started Hostname Service.
Mai 27 18:39:36 xenhost systemd-networkd[21412]: Got message type=method_return sender=:1.7441 destination=:1.7425 path=n/a interface=n/a member=n/a cookie=3 reply_cookie=57 signature=n/a error-nam>
Mai 27 18:39:36 xenhost systemd-networkd[21412]: Got message type=method_return sender=:1.7441 destination=:1.7425 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=58 signature=n/a error-nam>
Mai 27 18:39:36 xenhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res>
Mai 27 18:39:36 xenhost kernel: audit: type=1130 audit(1558975176.469:5311): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hos>
Mai 27 18:40:06 xenhost systemd[1]: systemd-hostnamed.service: Succeeded.
Mai 27 18:40:06 xenhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=>
```
**Steps to reproduce the problem**
No idea if it's matters, but I'm using a bonding device. There is an additional static IPv4 address assigned and IPv6 is active as well.
```
[root@xenhost ~]# ip a s dev lanbond
7: lanbond: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 82:28:70:ae:1a:60 brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.105/32 scope global lanbond
       valid_lft forever preferred_lft forever
    inet 192.168.33.5/24 brd 192.168.33.255 scope global dynamic lanbond
       valid_lft 2325sec preferred_lft 2325sec
    inet6 2001:16b8:2233:f6f8:8028:70ff:feae:1a60/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 3244sec preferred_lft 2902sec
    inet6 fe80::8028:70ff:feae:1a60/64 scope link
       valid_lft forever preferred_lft forever
```

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes #12490. ~~And closes #12676.~~

### CODE REVIEW

**Comment by yuwata** [comment]
cc @ssahani.

**Comment by yuwata** [comment]
@ssahani Thank you for the comment. I've updated. Now, all fields are equivalent to those when configuring. PTAL.

**Comment by ssahani** [comment]
LGTM

**Comment by yuwata** [comment]
@ssahani Thanks. Let's wait for more few days @cveilleux to report this fixes the issue.

**Comment by yuwata** [comment]
On top of the fix (which was once reviewed by @ssahani), I've added many tiny cleanups. I hope the changes are almost trivial. But, please take another look. Thank you.

File: src/network/networkd-dhcp4.c [hunk 1]
```diff
@@ -426,6 +427,8 @@ static int dhcp_lease_acquired(sd_dhcp_client *client, Link *link) {
         assert(client);
         assert(link);
 
+        link->dhcp4_configured = false;
```
Comment (keszybz) [inline src/network/networkd-dhcp4.c:495]: Why is this set here?

File: test/test-network/systemd-networkd-tests.py [hunk 2]
```diff
@@ -2030,35 +2039,36 @@ def test_dhcp6_client_settings_rapidcommit_false(self):
...
-
-        self.check_link_exists('veth99')
-
+        self.start_networkd(0)
+        self.wait_online(['veth-peer:carrier'])
         self.start_dnsmasq('--dhcp-alternate-port=67,5555')
+        self.wait_online(['veth99:routable', 'veth-peer:routable'])
+
+        # link become 'routable' when at least one protocol provide an valid address.
+        self.wait_address('veth99', 'inet 192\.168\.5\.[0-9]*/24 brd 192\.168\.5\.255', ipv='-4')
```
Comment (keszybz) [inline test/test-network/systemd-networkd-tests.py]: It'd be nicer to use `r''` here since this is a regular expression. Dot does not need to be escaped, so `\.` is the same as `\\.` which is the same as `r'\.'`, but using `r''` makes it unambiguous to the reader.

File: src/network/networkd-dhcp4.c [hunk 3]
```diff
@@ -649,10 +649,23 @@ static int dhcp4_handler(sd_dhcp_client *client, int event, void *userdata) {
                                         return log_link_warning_errno(link, r, "Could not acquire IPv4 link-local address: %m");
                         }
 
+                        if (link->network->dhcp_critical) {
+                                log_link_notice(link, "DHCPv4 connection considered system critical, ignoring request to reconfigure it.");
```
Comment (keszybz) [inline src/network/networkd-dhcp4.c]: "... is considered critical, ignoring ..." (There is no "system" in the name or description of CriticalConnection=.)

File: src/network/networkd-dhcp4.c (hunk 1 above)
Comment (yuwata) [reply src/network/networkd-dhcp4.c:495]: Otherwise, even when it fails, the flag still be on.

**Comment by yuwata** [comment]
@keszybz and @ssahani Thank you for your review. I've force-pushed an updated version. PTAL.

File: src/network/networkd-dhcp4.c (hunk 1 above)
Comment (keszybz) [reply src/network/networkd-dhcp4.c:495]: OK, makes sense. <strike>But I think it should only be set when dhcp_lease is set. I'll submit a patch as separate PR.</strike>

Comment (yuwata) [reply src/network/networkd-dhcp4.c:495]: Thanks.

**Comment by ssahani** [comment]
Please drop the last patch network: assign new DHCP address before removing old lease address. We will discuss this in another fresh PR. Rest is good.

**Comment by yuwata** [comment]
OK. The last commit was moved to #12685.
