### PR TITLE
Fix dhcpv4 renew/rebind intervals to match rfc2131

### LINKED ISSUE #17909: networkd dhcpv4 client never attempts more than 2 renew and 2 rebind
**systemd version the issue has been seen with**
 > git

**Used distribution**
 > Ubuntu

**Expected behaviour you didn't see**
 > dhcpv4 client to follow RFC2131, performing more than 2 renew requests and more than 2 rebind requests

**Unexpected behaviour you saw**
 > only 2 renew requests, and only 2 rebind requests

**Steps to reproduce the problem**
 > configure an interface to use dhcpv4; acquire a dhcpv4 address, then stop the dhcpv4 server, and wait for the networkd client to perform its renewals and rebinds before expiring the lease

The current networkd dhcpv4 code appears to have a bug in its calculation of the t1 and t2 timeout, where the 'time_left' is always calculated as 1/2 of the total t1 or t2 time (respectively). However, RFC2131 specifies the 'time_left' should be 1/2 of the *remaining* time until the next phase, not 1/2 of the total time. Using 1/2 of the total time means there will only be 2 renewal requests, once at t1 and another at t1 + (t2 - t1) / 2. Then, a rebind request at t2, and one more at t2 + (expire - t2) / 2. Then the lease will expire.

### PR DESCRIPTION
**Pull request by ddstreet**
The current code calculates the renew and rebind intervals as 1/2 of t2-t1 or lifetime-t2, respectively, which is not what RFC 2131 mandates and results in networkd never attempting more than 2 renewals nor more than 2 rebinds, no matter how large the lease lifetime is.

These commits also add macros to make clear what the RFC describing the algorithms is, instead of using magic numbers.

Fixes #17909.

### CODE REVIEW

**Comment by yuwata** [comment]
It seems that this makes `SD_DHCP_CLIENT_EVENT_TRANSIENT_FAILURE` event slightly delayed than previous. I have not reviewed this in detail, so I am not sure it is expected or not. But, at least the timeout in `test_dhcp_client_with_ipv4ll_without_dhcp_server` should be increased to make all CentOS CIs green.

File: src/libsystemd-network/sd-dhcp-client.c [hunk 1]
```diff
@@ -41,6 +41,20 @@
 #define TRANSIENT_FAILURE_ATTEMPTS 3 /* Arbitrary limit: how many attempts are considered enough to report
                                       * transient failure. */
 
+/* RFC2131 section 4.1 specifies retransmission delays, starting at 4s then doubling
+ * each attempt with max of 64s, with -1 to +1 sec of random 'fuzz' added */
+#define RFC2131_FUZZ_USEC ((int32_t)(random_u32() % (2 * USEC_PER_SEC)) - (int32_t)USEC_PER_SEC)
+#define RFC2131_SEC41_NEXT_TIMEOUT_USEC(now, attempt) \
+        ((usec_t)(now + ((int32_t)((UINT64_C(1) << MIN((attempt) + 1, (uint64_t) 6)) * USEC_PER_SEC) + RFC2131_FUZZ_USEC)))
```
Comment (poettering) [inline src/libsystemd-network/sd-dhcp-client.c]: please place `now` in `()` to avoid evaluation order issues

File: src/libsystemd-network/sd-dhcp-client.c [hunk 2]
```diff
@@ -41,6 +41,20 @@
...
+
+/* RFC2131 section 4.4.5 specifies T1 (renewing) and T2 (rebinding) defaults and
+ * special reacquisition delay algorithm, different from above section 4.1,
+ * however we use the same -1 to +1 sec 'fuzz' from above */
+#define RFC2131_T1_DEFAULT(lifetime) ((lifetime) / 2)
+#define RFC2131_T2_DEFAULT(lifetime) (((lifetime) * 7) / 8)
+#define RFC2131_SEC445_NEXT_TIMEOUT_USEC(now, expire) \
+        ((usec_t)(now + (MAX((((int32_t)((expire) - (now)) / 2) + RFC2131_FUZZ_USEC), (int32_t)(60 * USEC_PER_SEC)))))
```
Comment (poettering) [inline src/libsystemd-network/sd-dhcp-client.c]: as above

Comment (poettering) [reply src/libsystemd-network/sd-dhcp-client.c]: why the downcase to 32bit btw?

Comment (ddstreet) [reply src/libsystemd-network/sd-dhcp-client.c]: i was casting to signed int to handle the situation where expire <= now, though it should have been int64_t; however in the latest push i just changed it to expire > now ?: which is probably clearer, and removed the signed casting. let me know if you prefer a different way, or if you think it might be better to move the logic into a function instead of a macro.

File: src/libsystemd-network/sd-dhcp-client.c (hunk 1 above)
Comment (ddstreet) [reply src/libsystemd-network/sd-dhcp-client.c]: sorry missed that, corrected

**Comment by ddstreet** [comment]
> It seems that this makes `SD_DHCP_CLIENT_EVENT_TRANSIENT_FAILURE` event slightly delayed than previous. I have not reviewed this in detail, so I am not sure it is expected or not. But, at least the timeout in `test_dhcp_client_with_ipv4ll_without_dhcp_server` should be increased to make all CentOS CIs green.

it does slightly delay the transient failure event - i split that change out into its own commit, and i tried to add as much detail about behavior change to both commit messages.

In particular, the section 4.1 change that slightly delays the transient failure event is essentially only skipping the first 2-second timeout that the previous behavior was using; the RFC says 'start with 4 seconds' but our current code starts with 2, and the RFC also says the 4-second start is 'for example', so I think it should be fine to keep the existing behavior of starting at 2 seconds, if you think that's better. The rfc 'example' is for a 10Mbs network, so things are *definitely* faster nowdays.

for reference, from the rfc2131:
> For example, in a 10Mb/sec Ethernet
>    internetwork, the delay before the first retransmission SHOULD be 4
>    seconds randomized by the value of a uniform random number chosen
>    from the range -1 to +1.  Clients with clocks that provide resolution
>    granularity of less than one second may choose a non-integer
>    randomization value.  The delay before the next retransmission SHOULD
>    be 8 seconds randomized by the value of a uniform number chosen from
>    the range -1 to +1.  The retransmission delay SHOULD be doubled with
>    subsequent retransmissions up to a maximum of 64 seconds.

File: src/libsystemd-network/sd-dhcp-client.c [hunk 3]
```diff
@@ -41,6 +41,20 @@
...
+#define RFC2131_SEC41_NEXT_TIMEOUT_USEC(now, attempt) \
+        ((usec_t)((now) + ((UINT64_C(1) << MIN((attempt) + 1, UINT64_C(6))) * USEC_PER_SEC) + RFC2131_FUZZ_USEC))
+
+/* RFC2131 section 4.4.5 specifies T1 (renewing) and T2 (rebinding) defaults and
+ * special reacquisition delay algorithm, different from above section 4.1,
+ * however we use the same -1 to +1 sec 'fuzz' from above */
+#define RFC2131_T1_DEFAULT(lifetime) ((lifetime) / 2)
+#define RFC2131_T2_DEFAULT(lifetime) (((lifetime) * 7) / 8)
+#define RFC2131_SEC445_NEXT_TIMEOUT_USEC(now, expire) \
+        ((usec_t)((now) + MAX((expire) > (now) ? ((expire) - (now)) / 2 : UINT64_C(0), (60 * USEC_PER_SEC)) + RFC2131_FUZZ_USEC))
```
Comment (poettering) [inline src/libsystemd-network/sd-dhcp-client.c]: btw, we have the LESS_BY() macro, that does a saturated substraction, might be good to replace the first part of the MAX() expression:

```
…  + MAX(LESS_BY(expire, now) / 2, …
```

File: src/libsystemd-network/sd-dhcp-client.c [hunk 4]
```diff
@@ -41,6 +41,20 @@
 #define TRANSIENT_FAILURE_ATTEMPTS 3 /* Arbitrary limit: how many attempts are considered enough to report
                                       * transient failure. */
 
+/* RFC2131 section 4.1 specifies retransmission delays, starting at 4s then doubling
+ * each attempt with max of 64s, with -1 to +1 sec of random 'fuzz' added */
+#define RFC2131_FUZZ_USEC ((int32_t)(random_u32() % (2 * USEC_PER_SEC)) - (int32_t)USEC_PER_SEC)
```
Comment (poettering) [inline src/libsystemd-network/sd-dhcp-client.c]: so, the type is weird here, still. I understand you want signed values here, but why 32bit? usec_t is 64bit, and USEC_PER_SEC is 64bit too, like all µs values we deal with. Thus it would appear a lot more obvious to me if you'd use int64_t here, and random_u64()... i.e. suddenly mixing in a 32bit value when our usual time operations are all 64bit is irritating at best, but smells like an error at worst

**Review by poettering — CHANGES_REQUESTED** [review]

**Comment by poettering** [comment]
(only commenting about superficials here myself, I think @yuwata's take on all of this matters most)

File: src/libsystemd-network/sd-dhcp-client.c (hunk 3 above)
Comment (ddstreet) [reply src/libsystemd-network/sd-dhcp-client.c]: ah perfect! will do, thanks

File: src/libsystemd-network/sd-dhcp-client.c (hunk 4 above)
Comment (ddstreet) [reply src/libsystemd-network/sd-dhcp-client.c]: yep you're right, it should be int64_t; i changed the fuzz to use that type, and also changed to use the usec_add(), usec_sub_unsigned(), and usec_sub_signed() functions, which nicely handle some of the underflow/overflow details, and hopefully make the macros clearer.

File: src/libsystemd-network/sd-dhcp-client.c (hunk 3 above)
Comment (ddstreet) [reply src/libsystemd-network/sd-dhcp-client.c]: i changed to use the usec_sub_unsigned() function, which seemed to make the macro clearer.

File: src/libsystemd-network/sd-dhcp-client.c [hunk 5]
```diff
@@ -1660,92 +1660,92 @@ static int client_set_lease_timeouts(sd_dhcp_client *client) {
...
-                             lifetime_timeout, 10 * USEC_PER_MSEC,
+                             client->expire_time, 10 * USEC_PER_MSEC,
                              client_timeout_expire, client,
                              client->event_priority, "dhcp4-lifetime", true);
         if (r < 0)
                 return r;
 
         log_dhcp_client(client, "lease expires in %s",
-                        format_timespan(time_string, FORMAT_TIMESPAN_MAX, lifetime_timeout - time_now, USEC_PER_SEC));
+                        format_timespan(time_string, FORMAT_TIMESPAN_MAX, client->expire_time - time_now, USEC_PER_SEC));
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-client.c]: The log should be moved to the `if` condition below, or need to be adjusted, as the time difference may be negative.

File: src/libsystemd-network/sd-dhcp-client.c [hunk 6]
```diff
@@ -1660,92 +1660,92 @@ static int client_set_lease_timeouts(sd_dhcp_client *client) {
...
-                             t2_timeout, 10 * USEC_PER_MSEC,
+                             client->t2_time, 10 * USEC_PER_MSEC,
                              client_timeout_t2, client,
                              client->event_priority, "dhcp4-t2-timeout", true);
         if (r < 0)
                 return r;
 
         log_dhcp_client(client, "T2 expires in %s",
-                        format_timespan(time_string, FORMAT_TIMESPAN_MAX, t2_timeout - time_now, USEC_PER_SEC));
+                        format_timespan(time_string, FORMAT_TIMESPAN_MAX, client->t2_time - time_now, USEC_PER_SEC));
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-client.c]: Same here.

File: src/libsystemd-network/sd-dhcp-client.c [hunk 7]
```diff
@@ -1660,92 +1660,92 @@ static int client_set_lease_timeouts(sd_dhcp_client *client) {
...
-                             t1_timeout, 10 * USEC_PER_MSEC,
+                             client->t1_time, 10 * USEC_PER_MSEC,
                              client_timeout_t1, client,
                              client->event_priority, "dhcp4-t1-timer", true);
         if (r < 0)
                 return r;
 
         log_dhcp_client(client, "T1 expires in %s",
-                        format_timespan(time_string, FORMAT_TIMESPAN_MAX, t1_timeout - time_now, USEC_PER_SEC));
+                        format_timespan(time_string, FORMAT_TIMESPAN_MAX, client->t1_time - time_now, USEC_PER_SEC));
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-client.c]: Need to be adjusted.

File: src/libsystemd-network/sd-dhcp-client.c [hunk 8]
```diff
@@ -1675,49 +1661,17 @@ static int client_set_lease_timeouts(sd_dhcp_client *client) {
...
-                client->t2_time = client_compute_timeout(client, client->lease->lifetime, 7.0 / 8.0);
-                client->lease->t2 = (client->lease->lifetime * 7) / 8;
-        }
+        /* set default t1/t2 if unset or invalid */
+        if (client->lease->t2 == 0 || client->lease->t2 >= client->lease->lifetime)
+                client->lease->t2 = RFC2131_T2_DEFAULT(client->lease->lifetime);
+        if (client->lease->t1 == 0 || client->lease->t1 >= client->lease->t2)
+                client->lease->t1 = RFC2131_T1_DEFAULT(client->lease->lifetime);
+        if (client->lease->t1 >= client->lease->t2)
+                client->lease->t2 = RFC2131_T2_DEFAULT(client->lease->lifetime);
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-client.c]: Still there exist possibilities that `t2 <= t1` or `lifetime <= t1`...

File: src/libsystemd-network/sd-dhcp-client.c [hunk 9]
```diff
@@ -41,6 +42,21 @@
 #define TRANSIENT_FAILURE_ATTEMPTS 3 /* Arbitrary limit: how many attempts are considered enough to report
                                       * transient failure. */
 
+/* RFC2131 section 4.1 specifies retransmission delays, starting at 4s then doubling
+ * each attempt with max of 64s, with -1 to +1 sec of random 'fuzz' added. */
+#define RFC2131_APPLY_FUZZ(time) \
+        usec_sub_signed((time), ((int64_t)(random_u64() % (2 * USEC_PER_SEC)) - (int64_t)USEC_PER_SEC))
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-client.c]: Not a matter, but some of `()`s are redundant.
```
usec_sub_signed(time, (int64_t) (random_u64() % (2 * USEC_PER_SEC)) - (int64_t) USEC_PER_SEC)
```

File: src/libsystemd-network/sd-dhcp-client.c [hunk 10]
```diff
@@ -41,6 +42,21 @@
...
+#define RFC2131_SEC41_NEXT_TIMEOUT(now, attempt) \
+        RFC2131_APPLY_FUZZ(usec_add((now), ((UINT64_C(1) << MIN((attempt) + 1, UINT64_C(6))) * USEC_PER_SEC)))
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-client.c]: Not a matter, but it is safe to drop `()` around `now`: `(now)` -> `now`

File: src/libsystemd-network/sd-dhcp-client.c [hunk 11]
```diff
@@ -41,6 +42,21 @@
...
+
+/* RFC2131 section 4.4.5 specifies T1 (renewing) and T2 (rebinding) defaults and
+ * special reacquisition delay algorithm, different from above section 4.1,
+ * however we use the same -1 to +1 sec 'fuzz' from above */
+#define RFC2131_T1_DEFAULT(lifetime) ((lifetime) / 2)
+#define RFC2131_T2_DEFAULT(lifetime) (((lifetime) * 7) / 8)
+#define RFC2131_SEC445_NEXT_TIMEOUT(now, expire) \
+        RFC2131_APPLY_FUZZ(usec_add((now), MAX(usec_sub_unsigned((expire), (now)) / 2, (60 * USEC_PER_SEC))))
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-client.c]: `now` is used twice.

**Review by yuwata — CHANGES_REQUESTED** [review]

File: src/libsystemd-network/sd-dhcp-client.c (hunk 5 above)
Comment (ddstreet) [reply src/libsystemd-network/sd-dhcp-client.c]: ok, i added a commit at the start of the series to fix this

File: src/libsystemd-network/sd-dhcp-client.c (hunk 11 above)
Comment (ddstreet) [reply src/libsystemd-network/sd-dhcp-client.c]: ok, i changed the macros to be functions instead; i think it's a bit clearer and avoids the double-evaluation of now.

File: src/libsystemd-network/sd-dhcp-client.c (hunk 9 above)
Comment (ddstreet) [reply src/libsystemd-network/sd-dhcp-client.c]: change from macros->functions addressed this i think

File: src/libsystemd-network/sd-dhcp-client.c (hunk 10 above)
Comment (ddstreet) [reply src/libsystemd-network/sd-dhcp-client.c]: change from macros->functions addressed this i think

File: src/libsystemd-network/sd-dhcp-client.c (hunk 6 above)
Comment (ddstreet) [reply src/libsystemd-network/sd-dhcp-client.c]: corrected this also

File: src/libsystemd-network/sd-dhcp-client.c (hunk 7 above)
Comment (ddstreet) [reply src/libsystemd-network/sd-dhcp-client.c]: corrected this also

File: src/libsystemd-network/sd-dhcp-client.c (hunk 8 above)
Comment (ddstreet) [reply src/libsystemd-network/sd-dhcp-client.c]: I may be missing something, but here is my thinking (and this assumes that T1_DEFAULT() < T2_DEFAULT() < lifetime):

```
        if (client->lease->t2 == 0 || client->lease->t2 >= client->lease->lifetime)                                                                                                                                                                                           
                client->lease->t2 = T2_DEFAULT(client->lease->lifetime);                                                                                                                                                                                                      

```
this guarantees that 0 < t2 < lifetime

```
        if (client->lease->t1 == 0 || client->lease->t1 >= client->lease->t2)                                                                                                                                                                                                 
                client->lease->t1 = T1_DEFAULT(client->lease->lifetime);                                                                                                                                                                                                      

```

since we know t2 < lifetime, this guarantees that 0 < t1 < lifetime

```
        if (client->lease->t1 >= client->lease->t2)                                                                                                                                                                                                                           
                client->lease->t2 = T2_DEFAULT(client->lease->lifetime);                                                                                                                                                                                                      

```

if this is true, and t1 >= t2, then t1 *must* be T1_DEFAULT, since the previous check could not have evaluated to false. in that case, assigning t2 to T2_DEFAULT is guaranteed to make t1 < t2.

File: src/libsystemd-network/sd-dhcp-client.c [hunk 12]
```diff
@@ -1691,49 +1677,31 @@ static int client_set_lease_timeouts(sd_dhcp_client *client) {
...
-        }
+        /* verify that 0 < t2 < lifetime */
+        if (client->lease->t2 == 0 || client->lease->t2 >= client->lease->lifetime)
+                client->lease->t2 = T2_DEFAULT(client->lease->lifetime);
+        /* verify that 0 < t1 < lifetime */
+        if (client->lease->t1 == 0 || client->lease->t1 >= client->lease->t2)
+                client->lease->t1 = T1_DEFAULT(client->lease->lifetime);
+        /* now, if t1 >= t2, t1 *must* be T1_DEFAULT, since the previous check
+         * could not evalate to false if t1 >= t2; so setting t2 to T2_DEFAULT
+         * guarantees t1 < t2. */
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-client.c:1677]: Nice. Thanks.

**Review by yuwata — APPROVED** [review]
LGTM.

**Comment by yuwata** [comment]
@mrc0mmand Could you restart the two failed CentOS CI tests?

**Comment by keszybz** [comment]
I restarted bionic-amd64.

**Comment by yuwata** [comment]
@mrc0mmand and @keszybz Thanks. All CentOS and Ubuntu CIs are green. Merging.
