### PR TITLE
sd-device-enumerator: support multiple parents

### LINKED ISSUE #6098: udevadm trigger does not trigger all specified devices
### Submission type

 - Bug report

### systemd version the issue has been seen with
master since 80877656a557 ("udevadm trigger: allow matching by device name")

### Used distribution

OpenSUSE Leap 42.2

### In case of bug report: Expected behaviour you didn't see

` # systemd/udevadm trigger --verbose /dev/input/event{0,3,9}`
/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input0/event0
/sys/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0/0003:413C:301A.001C/input/input97/event3
/sys/devices/pci0000:00/0000:00:1b.0/sound/card0/input12/event9

### In case of bug report: Unexpected behaviour you saw
only last device triggers:

` # systemd/udevadm trigger --verbose /dev/input/event{0,3,9}`
/sys/devices/pci0000:00/0000:00:1b.0/sound/card0/input12/event9
` # systemd/udevadm trigger --verbose /dev/input/event{0,3}`
/sys/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0/0003:413C:301A.001C/input/input97/event3

### PR DESCRIPTION
**Pull request by yuwata**
When `sd_device_enumerator_add_match_parent()` is called multiple times, then previously set parents are discarded.

This adds `device_enumerator_add_match_parent_incremental()` to make sd-device-enumerator scan devices under all specified parents.

Note that for backward compatibility, `sd_device_enumerator_add_match_parent()` and `udev_enumerate_add_match_parent()` still discard previous assignments.

Closes #6098.

### CODE REVIEW

File: src/libsystemd/sd-device/device-enumerator.c [hunk 1]
```diff
@@ -217,18 +217,42 @@ _public_ int sd_device_enumerator_add_match_tag(sd_device_enumerator *enumerator
...
 
-_public_ int sd_device_enumerator_add_match_parent(sd_device_enumerator *enumerator, sd_device *parent) {
+static void device_enumerator_clear_match_parent(sd_device_enumerator *enumerator) {
+        if (!enumerator)
+                return;
+
+        set_clear_free(enumerator->match_parent);
+}
+
+int device_enumerator_add_match_parent(sd_device_enumerator *enumerator, sd_device *parent) {
```
Comment (poettering) [inline src/libsystemd/sd-device/device-enumerator.c]: hmm, I think this should have a better name... the "sd_" prefix doesn't really clarify that this version doesn't flush the matches, but the sd_ version does...

maybe "add_match_parent_incremental"?

Comment (yuwata) [reply src/libsystemd/sd-device/device-enumerator.c]: OK. Renamed to `device_enumerator_add_match_parent_incremental()`.

**Comment by yuwata** [comment]
> Looks good, but maybe leave this for v242?

Yeah, I agree.

**Comment by yuwata** [comment]
I will update the man page after #11520 is merged.
