### PR TITLE
udev: fix parent token handling

### LINKED ISSUE #23288: wwan (on usb) problem on 251rc2
**systemd version the issue has been seen with**
 > 251rc2-1

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux arch 5.17.5-arch1-1 #1 SMP PREEMPT Wed, 27 Apr 2022 20:56:11 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Unexpected behaviour you saw**
 > wwan fibocom l830 stop working

**Steps to reproduce the problem**
 > upgrade systemd from 250.5-1 -> 251rc2-1

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
systemd[1]: Starting Modem Manager...
ModemManager[564]: <info>  ModemManager (version 1.18.8-1) starting in system bus...
ModemManager[564]: [qrtr] socket lookup from 1:0
ModemManager[564]: [qrtr] initial lookup finished
systemd[1]: Started Modem Manager.
ModemManager[564]: opening device...
ModemManager[564]: cannot connect to proxy: Could not connect: Connection refused
ModemManager[564]: spawning new mbim-proxy (try 1)...
ModemManager[564]: opening device...
ModemManager[564]: cannot connect to proxy: Could not connect: Connection refused
ModemManager[564]: spawning new mbim-proxy (try 1)...
ModemManager[564]: [/dev/wwan0mbim0] Couldn't find descriptors file, possibly not using cdc_mbim
ModemManager[564]: [/dev/wwan0mbim0] Fallback to default max control message size: 4096
ModemManager[564]: [/dev/cdc-wdm0] Read max control message size from descriptors file: 512
ModemManager[564]: [/dev/cdc-wdm0] unexpected port hangup!
ModemManager[564]: [/dev/cdc-wdm0] channel destroyed
ModemManager[564]: <info>  [base-manager] couldn't check support for device '/sys/devices/pci0000:00/0000:00:1f.6': not supported by any plugin
ModemManager[564]: <info>  [base-manager] couldn't check support for device '/sys/devices/pci0000:00/0000:00:1c.4/0000:09:00.0': not supported by any plugin
ModemManager[564]: <info>  [wwan0mbim0/mbim] MBIM device is not QMI capable
ModemManager[564]: [/dev/wwan0mbim0] channel destroyed
ModemManager[564]: proxy configuration failed: closed
ModemManager[564]: <info>  [device /sys/devices/pci0000:00/0000:00:14.0/usb3/3-2] creating modem with plugin 'fibocom' and '4' ports
ModemManager[564]: <warn>  [plugin/fibocom] could not grab port wwan0mbim0: unsupported subsystem: 'wwan'
ModemManager[564]: <warn>  [plugin/fibocom] could not grab port cdc-wdm0: Cannot add port 'usbmisc/cdc-wdm0', unhandled port type
ModemManager[564]: <info>  [base-manager] modem for device '/sys/devices/pci0000:00/0000:00:14.0/usb3/3-2' successfully created
ModemManager[564]: <warn>  [modem0] couldn't start initialization: Cannot initialize: MBIM port went missing
ModemManager[564]: <warn>  [modem0] couldn't initialize: 'Modem is unusable, cannot fully initialize'
```
on 250.5 see:

```text
systemd[1]: Started Modem Manager.
ModemManager[564]: opening device...
ModemManager[564]: cannot connect to proxy: Could not connect: Connection refused
ModemManager[564]: spawning new mbim-proxy (try 1)...
ModemManager[564]: [/dev/cdc-wdm0] Read max control message size from descriptors file: 512
ModemManager[564]: <info>  [cdc-wdm0/mbim] MBIM device is not QMI capable
ModemManager[564]: [/dev/cdc-wdm0] channel destroyed
ModemManager[564]: <info>  [device /sys/devices/pci0000:00/0000:00:14.0/usb3/3-2] creating modem with plugin 'fibocom' and '3' ports
ModemManager[564]: <info>  [base-manager] modem for device '/sys/devices/pci0000:00/0000:00:14.0/usb3/3-2' successfully created
ModemManager[564]: opening device...
ModemManager[564]: [/dev/cdc-wdm0] Read max control message size from descriptors file: 512
ModemManager[564]: <info>  [modem0/cdc-wdm0/mbim] MBIM device is not QMI capable
ModemManager[564]: <warn>  [modem0] couldn't load carrier config: QMI PDC not supported
ModemManager[564]: <warn>  [modem0] (shared-xmm) unexpected band value: 0-2
ModemManager[564]: <warn>  [modem0] couldn't query SIM slots: OperationNotAllowed
```

### PR DESCRIPTION
**Pull request by yuwata**
This fixes a bug introduced by 03677889f0ef42cdc534bf3b31265a054b20a354.

Fixes #23288.

### CODE REVIEW

File: src/udev/udev-rules.c [hunk 1]
```diff
@@ -2441,8 +2440,8 @@ static int udev_rule_apply_parent_token_to_event(
                         if (r == 0)
                                 break;
                 }
-                if (!line->current_token)
-                        /* All parent tokens match. But no assign tokens in the line. Hmm... */
+                if (r > 0)
```
Comment (bluca) [inline src/udev/udev-rules.c:2448]: Could `r` be uninitialized here, for example if the list is empty?

Comment (yuwata) [reply src/udev/udev-rules.c:2448]: The list is not empty. I will add an assertion soon.

**Review by bluca — APPROVED** [review]

**Comment by galibozek** [comment]
Commit: eba782d59bfc1ce82b4c41883d15fa5e705126e5 resolved my problem, thanks
