### PR TITLE
nspawn: ignore --suppress-sync=yes when seccomp is disabled

### LINKED ISSUE #21090: build error without SECCOMP support
since 4a4654e0241fbeabecb8587fd3520b6b39264b9c systemd fails to build without SECCOMP suport:

```
../src/nspawn/nspawn.c: In function ‘inner_child’:
../src/nspawn/nspawn.c:3408:21: error: implicit declaration of function ‘seccomp_suppress_sync’ [-Werror=implicit-function-declaration]
 3408 |                 r = seccomp_suppress_sync();
      |                     ^~~~~~~~~~~~~~~~~~~~~
../src/nspawn/nspawn.c:3408:21: warning: nested extern declaration of ‘seccomp_suppress_sync’ [-Wnested-externs]
```

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for 4a4654e0241fbeabecb8587fd3520b6b39264b9c.

Fixes #21090.

### CODE REVIEW

File: src/nspawn/nspawn.c [hunk 1]
```diff
@@ -3405,9 +3405,13 @@ static int inner_child(
         }
 
         if (arg_suppress_sync) {
+#if HAVE_SECCOMP
                 r = seccomp_suppress_sync();
                 if (r < 0)
                         log_debug_errno(r, "Failed to install sync() suppression seccomp filter, ignoring: %m");
+#else
+                log_debug("systemd is build without SECCOMP support. Ignoring --suppress-sync= command line option and SuppressSync= setting.")
```
Comment (bluca) [inline src/nspawn/nspawn.c]: "is built"
