### PR TITLE
cgtop: add option to show a single cgroup subtree

### LINKED ISSUE #2163: systemd-cgtop to display only a sub-tree cgroup
systemd-cgtop's output does not fit on the screen. I would like it to only display the data from `machine.slice` in order to see the data for all my containers.

But `systemd-cgtop machine.slice` does not work yet.

It should not be too complicated to implement, since `systemd-cgtop` can already filter on some slices with the `-M` option.

### PR DESCRIPTION
**Pull request by alepuccetti**
When many services are running, it was difficult to see only the interesting ones.
This patch allows to show only the subtree of interest.

Fixes #2163

### CODE REVIEW

**Comment by alban** [comment]
The tests fail on ubuntu-amd64 but I don't think it is related to this patch.

File: src/cgtop/cgtop.c [hunk 1]
```diff
@@ -835,7 +836,15 @@ static int parse_argv(int argc, char *argv[]) {
...
                 }
 
-        if (optind < argc) {
+        if (optind == argc-1) {
+                if (arg_machine) {
+                        log_error("Specify a root path together with the -M option is not allowed");
+                        return -EINVAL;
+                }
+                arg_root = argv[optind];
+
```
Comment (zonque) [inline src/cgtop/cgtop.c]: Spurious newline?

File: src/cgtop/cgtop.c [hunk 2]
```diff
@@ -835,7 +836,15 @@ static int parse_argv(int argc, char *argv[]) {
...
+        }
+        else if (optind < argc) {
```
Comment (zonque) [inline src/cgtop/cgtop.c]: While at it, please move the `else` into the `}` line.

**Comment by alepuccetti** [comment]
Patch updated

File: src/cgtop/cgtop.c [hunk 3]
```diff
@@ -672,7 +673,7 @@ static void help(void) {
                "  -n --iterations=N   Run for N iterations before exiting\n"
                "  -b --batch          Run in batch mode, accepting no input\n"
                "     --depth=DEPTH    Maximum traversal depth (default: %u)\n"
-               "  -M --machine=       Show container\n"
+               "  -M --machine=       Show container (incompatible when cgroup path is specified)\n"
```
Comment (zonque) [inline src/cgtop/cgtop.c]: Any reason why you didn't make this new feature a regular option (`-r`, `--root`)? I think that would be a better fit than stealing the extra argv.

Comment (alepuccetti) [inline src/cgtop/cgtop.c]: I did at first, but I decided to base the interface on `systemd-cgls [OPTIONS...] [CGROUP...]`. Only that in this case you can give only one cgroup and not many. This could be an expansion, but do not see the need now.

Comment (zonque) [inline src/cgtop/cgtop.c]: Well, passing more than one root does not make a whole lot of sense, so I really think a regular getopt option is a much better fit.

Comment (alepuccetti) [inline src/cgtop/cgtop.c]: It could have sense, if you want to monitor different subtrees with this patch you have to select the first common root. With multiple roots you can specify only which one you want to monitor and "cut" the branches you do not care about form the output.

example: you have the same set of services on different machines (e.g. apache and cassandra), but you do not want monitor only the resources used my all the instances of apaches across the different machines.

Also I am expecting that this features is going to be used a lot so it make sense to have it like ti is the "default" behaviour.
However, if you think that it is better with a switch, it is not a problem. I will fix it in a jiffy.

Comment (zonque) [inline src/cgtop/cgtop.c]: The code is not prepared for the scenario you are describing. You would need to add a column to to each record describing the root used to determine the values, and I doubt it would really add to the usability of this utility.

So no, I am not convinced this is a good idea, but even if you wanted to enable such a functionality later, you could still add comma separated values to the option or something like that.

Anyway, I don't want to have the final word on this. Let @poettering decide that.

Comment (poettering) [inline src/cgtop/cgtop.c]: uh, oh, I am not sure either way. I can see @zonque's point, but I also see the benefit to making this similar to cgls... That said, there's of course a discrepancy here, given that cgls handles multiple cgroup paths fine, and this tool does not... hmm, but i figure being like cgls is probably the better option, as long as there's a nice error message thrown...

Comment (poettering) [inline src/cgtop/cgtop.c]: But could you please move the comment about the incompatibility of --machine= and specification of a root directory into the man page, and remove it from --help? This looks like useful information, but --help is really supposed to be brief, while the man page should be longer...

**Comment by poettering** [comment]
looks pretty OK otherwise.

**Comment by alepuccetti** [comment]
Changed the help message and the man page. Also I added a strdup() and oom when getting the cgroup path because exiting using `q` produced seg fault.

File: src/cgtop/cgtop.c [hunk 4]
```diff
@@ -864,6 +873,11 @@ static int get_cgroup_root(char **ret) {
         const char *m;
         int r;
 
+        if (arg_root) {
+                *ret = arg_root;
```
Comment (poettering) [inline src/cgtop/cgtop.c]: You should really strdup() here, so that the caller doesn't free the static variable, and ownership of the returned string is clear.

File: src/cgtop/cgtop.c [hunk 5]
```diff
@@ -835,7 +836,15 @@ static int parse_argv(int argc, char *argv[]) {
                         assert_not_reached("Unhandled option");
                 }
 
-        if (optind < argc) {
+        if (optind == argc-1) {
+                if (arg_machine) {
+                        log_error("Specify a cgroup path together with the -M option is not allowed");
```
Comment (poettering) [inline src/cgtop/cgtop.c]: sorry for not noticing this earlier, but could you write "control group" here?

File: src/cgtop/cgtop.c [hunk 6]
```diff
@@ -835,7 +836,15 @@ static int parse_argv(int argc, char *argv[]) {
...
+                        return -EINVAL;
+                }
+                arg_root = strdup(argv[optind]);
+                if (!arg_root)
+                        return log_oom();
```
Comment (poettering) [inline src/cgtop/cgtop.c]: Hmm, I am pretty sure arg_root should point to argv[optind] directly here, as that memory is stable and stays around. However, get_cgroup_root() should really do a copy then, so that it always returns malloc()ed memory, and not sometimes global variables... (see below)

File: man/systemd-cgtop.xml [hunk 7]
```diff
@@ -252,7 +255,8 @@
 
         <listitem><para>Limit control groups shown to the part
         corresponding to the container
-        <replaceable>MACHINE</replaceable>.</para></listitem>
+        <replaceable>MACHINE</replaceable>.
+        This option may not be used when a cgroup path is specified.</para></listitem>
```
Comment (poettering) [inline man/systemd-cgtop.xml]: please spell out "control group" rather than "cgroup" here.

File: man/systemd-cgtop.xml [hunk 8]
```diff
@@ -62,7 +63,9 @@
     groups of the local Linux control group hierarchy, ordered by
     their CPU, memory, or disk I/O load. The display is refreshed in
     regular intervals (by default every 1s), similar in style to
-    <citerefentry project='man-pages'><refentrytitle>top</refentrytitle><manvolnum>1</manvolnum></citerefentry>.</para>
+    <citerefentry project='man-pages'><refentrytitle>top</refentrytitle><manvolnum>1</manvolnum></citerefentry>.
+    If a gcroup path is specified, shows only the services of
```
Comment (poettering) [inline man/systemd-cgtop.xml]: Please spell out "control group" rather than "cgroup" here.

**Comment by poettering** [comment]
ah, indeed, memory management was borked, but still not right ;-)

**Comment by alepuccetti** [comment]
Patch updated

File: src/cgtop/cgtop.c [hunk 9]
```diff
@@ -835,7 +836,13 @@ static int parse_argv(int argc, char *argv[]) {
                         assert_not_reached("Unhandled option");
                 }
 
-        if (optind < argc) {
+        if (optind == argc-1) {
+                if (arg_machine) {
+                        log_error("Specify a control group path together with the -M option is not allowed");
```
Comment (alban) [inline src/cgtop/cgtop.c]: `s/Specify/Specifying/` ?

**Comment by keszybz** [comment]
@alepuccetti: https://github.com/systemd/systemd/pull/3413#discussion_r65761117 still needs fixing.

**Comment by alepuccetti** [comment]
Patch updated

**Comment by keszybz** [comment]
autopkgtest failure is unrelated.

File: src/cgtop/cgtop.c [hunk 10]
```diff
@@ -864,6 +871,13 @@ static int get_cgroup_root(char **ret) {
         const char *m;
         int r;
 
+        if (arg_root) {
+                *ret = strdup(arg_root);
+                if (!*ret)
```
Comment (poettering) [inline src/cgtop/cgtop.c:876]: humpf, we generally avoid clobbering call-by-ref parameters on failure. See CODING_STYLE. Hence, please don't override `*ret` until your know you succeeded. Specifically, write the result into a temporary variable and only after the oom check succeeded write it into *ret...

Comment (alepuccetti) [inline src/cgtop/cgtop.c:876]: Fixed in #3443
