### PR TITLE
core/mount: if umount(8) fails but mount disappeared, assume success

### LINKED ISSUE #31337: Systemd fails to unmount credentials mount for `console@getty.service` during shutdown in an nspawn container
Noticed this in several recent CI runs:
```
# make -C test/TEST-01-BASIC/ clean setup run TEST_NO_QEMU=1 RUN_IN_UNPRIVILEGED_CONTAINER=no
...
# journalctl --file /var/tmp/systemd-tests/systemd-test.7lHGEc/system.journal -o short-monotonic --no-hostname
...
[  543.408330] systemd[1]: Stopped console-getty.service.
[  543.408373] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/console_2dgetty_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=392 reply_cookie=0 signat>
[  543.408399] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/console_2dgetty_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=393 reply_cookie=0 signat>
[  543.408423] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=394 reply_cookie=0 signature=uoss error-name=n/a error-message>
[  543.408450] systemd[1]: console-getty.service: Consumed 6ms CPU time, 2.0M memory peak.
[  543.408483] systemd[1]: Failed to lock /dev/console: Too many levels of symbolic links
[  543.408508] systemd[1]: console-getty.service: Releasing resources...
[  543.408532] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/console_2dgetty_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=395 reply_cookie=0 signat>
[  543.408559] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/console_2dgetty_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=396 reply_cookie=0 signat>
[  543.408584] systemd[1]: systemd-journald.service: Got notification message from PID 20 (FDSTORE=1)
[  543.408611] systemd[1]: systemd-journald.service: Trying to stash fd for dev=0:8/inode=77829
[  543.408638] systemd[1]: systemd-journald.service: Added fd 25 (stored) to fd store.
[  543.408663] systemd[1]: basic.target: stopping held back, waiting for: systemd-logind.service
[  543.408688] systemd[1]: shutdown.target: starting held back, waiting for: basic.target
[  543.408712] systemd[1]: sysinit.target: stopping held back, waiting for: basic.target
[  543.408752] systemd[1]: systemd-user-sessions.service: Will spawn child (service_enter_stop): /usr/lib/systemd/systemd-user-sessions
[  543.408890] systemd[1]: systemd-user-sessions.service: About to execute: /usr/lib/systemd/systemd-user-sessions stop
[  543.408923] systemd[1]: Serializing sd-executor-state to memfd.
[  543.408947] systemd[1]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
[  543.408990] umount[477]: umount: /run/credentials/console-getty.service: no mount point specified.
[  543.409109] systemd[1]: systemd-user-sessions.service: Forked /usr/lib/systemd/systemd-user-sessions as 478 (via CLONE_INTO_CGROUP)
[  543.409143] systemd[1]: Closing set fd 42 (socket:[73076])
[  543.409235] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2duser_2dsessions_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=397 reply_cooki>
[  543.409301] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2duser_2dsessions_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=398 reply_cooki>
[  543.409333] systemd[1]: systemd-user-sessions.service: Changed exited -> stop
[  543.409369] systemd[1]: Stopping systemd-user-sessions.service...
[  543.409623] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2duser_2dsessions_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=399 reply_cooki>
[  543.409669] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2duser_2dsessions_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=400 reply_cooki>
[  543.409700] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/job/186 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=401 reply_cookie=0 signature=sa{sv}as error-name>
[  543.409781] systemd[1]: Received SIGCHLD from PID 477 (umount).
[  543.409806] systemd[1]: Child 477 (umount) died (code=exited, status=32/n/a)
[  543.409840] systemd[1]: run-credentials-console\x2dgetty.service.mount: Child 477 belongs to run-credentials-console\x2dgetty.service.mount.
[  543.409867] systemd[1]: run-credentials-console\x2dgetty.service.mount: Mount process exited, code=exited, status=32/n/a
[  543.409897] systemd[1]: run-credentials-console\x2dgetty.service.mount: Failed with result 'exit-code'.
[  543.409928] systemd[1]: run-credentials-console\x2dgetty.service.mount: Changed unmounting -> failed
[  543.409965] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=402 reply_cookie=0 signature=sa{sv}as error-name=n/a err>
[  543.412505] systemd[1]: run-credentials-console\x2dgetty.service.mount: Job 257 run-credentials-console\x2dgetty.service.mount/stop finished, result=done
[  543.412577] systemd[1]: Unmounted run-credentials-console\x2dgetty.service.mount.
```

### PR DESCRIPTION
**Pull request by YHNdnzj**
Fixes #31337

cc @mrc0mmand

### CODE REVIEW

File: src/core/mount.c [hunk 1]
```diff
@@ -1638,13 +1637,18 @@ static void mount_sigchld_event(Unit *u, pid_t pid, int code, int status) {
                                 log_unit_warning(u, "Mount still present after %u attempts to unmount, giving up.", m->n_retry_umount);
                                 mount_enter_mounted(m, f);
                         }
+                } else if (f == MOUNT_FAILURE_EXIT_CODE && !m->from_proc_self_mountinfo) {
+                        /* Hmm, umount process spawned by us failed, but the mount disappeared anyway?
+                         * Maybe someone else is trying to unmount at the same time. */
+                        log_unit_notice(u, "Mount still disappeared even though umount failed, ignoring.");
```
Comment (yuwata) [inline src/core/mount.c]: 'still' sounds spurious for me. Also, if `", ignoring."`, I think it is better to downgrade the log level to LOG_DEBUG.

File: src/core/mount.c [hunk 2]
```diff
@@ -1578,7 +1578,8 @@ static void mount_sigchld_event(Unit *u, pid_t pid, int code, int status) {
 
         if (IN_SET(m->state, MOUNT_REMOUNTING, MOUNT_REMOUNTING_SIGKILL, MOUNT_REMOUNTING_SIGTERM))
                 mount_set_reload_result(m, f);
-        else if (m->result == MOUNT_SUCCESS)
+        else if (m->result == MOUNT_SUCCESS && !IN_SET(m->state, MOUNT_MOUNTING, MOUNT_UNMOUNTING))
+                /* MOUNT_MOUNTING and MOUNT_UNMOUNTING states need to be patched, see below. */
```
Comment (yuwata) [inline src/core/mount.c:1587]: Rather than patching result later, patch them here.
Otherwise, `unit_log_process_exit()` logs the failure louder.

Comment (YHNdnzj) [reply src/core/mount.c:1587]: So I thought about this, but umount(8) already logs about the failure, and it would be strange/possibly confusing if we patch the result silently. LOG_NOTICE is fine IMO?

File: src/core/mount.c (hunk 1 above)
Comment (YHNdnzj) [reply src/core/mount.c]: (LOG_NOTICE for the same reason, but I'll rephrase the message a bit)

File: src/core/mount.c (hunk 2 above)
Comment (yuwata) [reply src/core/mount.c:1587]: Indeed...

File: src/core/mount.c [hunk 3]
```diff
@@ -1643,13 +1642,18 @@ static void mount_sigchld_event(Unit *u, pid_t pid, int code, int status) {
                                 log_unit_warning(u, "Mount still present after %u attempts to unmount, giving up.", m->n_retry_umount);
                                 mount_enter_mounted(m, f);
                         }
+                } else if (f == MOUNT_FAILURE_EXIT_CODE && !m->from_proc_self_mountinfo) {
+                        /* Hmm, umount process spawned by us failed, but the mount disappeared anyway?
+                         * Maybe someone else is trying to unmount at the same time. */
+                        log_unit_notice(u, "Mount disappeared even though umount process failed, ignoring.");
```
Comment (keszybz) [inline src/core/mount.c]: I think "proceeding" or "continuing" would be better than "ignoring", because we're not "ignoring" anything, we're treating it as success.

**Review by keszybz — APPROVED** [review]

**Comment by keszybz** [comment]
I think we should do this. It is a natural extension of existing logic and shouldn't hurt.
