### PR TITLE
binfmt-util: handle ELOOP/EACCES from automount in read-only bind mounts

### LINKED ISSUE #38070: test-binfmt-util fails with -40/ELOOP in Community Build Service (CBS)
### systemd version the issue has been seen with

258

### Used distribution

CentOS

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

test-binfmt-util fails in [CBS](https://cbs.centos.org/koji/)

Build: https://cbs.centos.org/koji/taskinfo?taskID=5053886
Logs: https://cbs.centos.org/kojifiles/work/tasks/3910/5053910/build.log

```
1045/1650 systemd:test / test-binfmt-util                                          FAIL              0.31s   killed by signal 6 SIGABRT
>>> PATH=/builddir/build/BUILD/systemd-8a1d1341444aaf143108e0ca85741c779014d8b2/redhat-linux-build:/usr/share/Modules/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin MALLOC_PERTURB_=57 PROJECT_BUILD_ROOT=/builddir/build/BUILD/systemd-8a1d1341444aaf143108e0ca85741c779014d8b2/redhat-linux-build SYSTEMD_LANGUAGE_FALLBACK_MAP=/builddir/build/BUILD/systemd-8a1d1341444aaf143108e0ca85741c779014d8b2/src/locale/language-fallback-map SYSTEMD_SLOW_TESTS=1 PYTHONDONTWRITEBYTECODE=1 EFI_ADDON=/builddir/build/BUILD/systemd-8a1d1341444aaf143108e0ca85741c779014d8b2/redhat-linux-build/src/boot/addonx64.efi.stub /builddir/build/BUILD/systemd-8a1d1341444aaf143108e0ca85741c779014d8b2/redhat-linux-build/test-binfmt-util
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stderr:
/* test_binfmt_mounted */
src/test/test-binfmt-util.c:7: Assertion failed: Expected "binfmt_mounted()" to succeed, but got error: -40/ELOOP
```

It's probably a problem in CBS but the test should gracefully handle this errno: ELOOP.

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by sdainard-AL**
When /proc is bind-mounted read-only (as in mock/Koji/CBS buildroots),
  the kernel returns ELOOP when attempting to traverse the binfmt_misc
  automount point. This causes test-binfmt-util to SIGABRT and
  disable_binfmt() to log a spurious warning at shutdown.
  
  binfmt_mounted_and_writable() handles ENOENT but not ELOOP. This adds
  ELOOP and EACCES to the "not available" check.
  
  Context:
  - PR #37004 proposed reverting the test; @bluca suggested graceful handling instead
  - PR #37006 was merged and addressed ELOOP in the xstatfsat() path, but the
    open() call in binfmt_mounted_and_writable() remained unhandled
  - The bug is non-deterministic in build farms because it depends on whether the
    builder host has proc-sys-fs-binfmt_misc.automount active
  
  Root cause: mock bind-mounts host /proc with `rbind` then remounts read-only.
  If the host has binfmt_misc as an automount, the kernel returns ELOOP when
  the chroot tries to traverse it through the read-only bind mount.
  
  Tested in Amazon Linux Koji builds across multiple builder hosts — consistently
  fixes the failure on hosts where it previously reproduced.
  
  Fixes #38070

### CODE REVIEW

File: src/shared/binfmt-util.c [hunk 1]
```diff
@@ -18,6 +18,8 @@ int binfmt_mounted_and_writable(void) {
         fd = RET_NERRNO(open("/proc/sys/fs/binfmt_misc", O_CLOEXEC | O_DIRECTORY | O_PATH));
         if (fd == -ENOENT)
                 return false;
+        if (IN_SET(fd, -ELOOP, -EACCES))
```
[the remark this answers is not in the document]
Comment (sdainard-AL) [reply src/shared/binfmt-util.c]: Consolidated into a single IN_SET in d3cab87.

File: src/shared/binfmt-util.c [hunk 2]
```diff
@@ -16,7 +16,7 @@ int binfmt_mounted_and_writable(void) {
         int r;
 
         fd = RET_NERRNO(open("/proc/sys/fs/binfmt_misc", O_CLOEXEC | O_DIRECTORY | O_PATH));
-        if (fd == -ENOENT)
+        if (IN_SET(fd, -ENOENT, -ELOOP, -EACCES))
```
Comment (poettering) [inline src/shared/binfmt-util.c]: the ELOOP thing really needs a comment explaining the why...

also, we generally don't check directly against EACCES these days but use ERRNO_IS_NEG_PRIVILEGE() instead.

also, we nowadays prefer debug logging at places like this, and i think both the ELOOP and EACCESS case could really benefit from a log messag here. i.e. just use log_debug_errno()

Comment (sdainard-AL) [reply src/shared/binfmt-util.c]: Thanks for the review & insight. 
Updated: 
- added a comment explaining the ELOOP mechanism, 
- switched to `ERRNO_IS_NEG_PRIVILEGE()`, and 
- added `log_debug_errno()` for both paths.

File: src/shared/binfmt-util.c [hunk 3]
```diff
@@ -18,6 +18,12 @@ int binfmt_mounted_and_writable(void) {
         fd = RET_NERRNO(open("/proc/sys/fs/binfmt_misc", O_CLOEXEC | O_DIRECTORY | O_PATH));
         if (fd == -ENOENT)
                 return false;
+        /* ELOOP happens when binfmt_misc is an automount point under a read-only bind mount of /proc —
+         * the kernel cannot trigger the automount and returns ELOOP instead. Common in mock/Koji buildroots. */
+        if (fd == -ELOOP)
+                return log_debug_errno(fd, "Failed to open /proc/sys/fs/binfmt_misc, ignoring: %m"), false;
+        if (ERRNO_IS_NEG_PRIVILEGE(fd))
+                return log_debug_errno(fd, "Failed to open /proc/sys/fs/binfmt_misc, ignoring: %m"), false;
```
Comment (bluca) [inline src/shared/binfmt-util.c]: please don't use the comma operator, and the log is the same so the same if branch can be used

Comment (sdainard-AL) [reply src/shared/binfmt-util.c]: Thanks, corrected; appreciate the patience.

**Review by bluca — APPROVED** [review]
