### PR TITLE
nspawn: move virtual interfaces added with --network-interface back to the host

### LINKED ISSUE #13530: Stopping nspawn container destroys the veth interface defined additionally with networkd.
systemd 241 (v241-10.git511646b.fc30)
Fedora 30

When usinng a custom veth-pair added with ```--network-interface``` in an .nspawn file, attaching it to the nspawn container, then stopping the container, both veth interfaces disappear. This is a bug according to the documentation, as it states "When the container terminates, it is moved back to the host namespace."

**Expected behaviour you didn't see**
Putting back the veth interface to the host.

**Unexpected behaviour you saw**
The veth interfaces disappearing.

**Steps to reproduce the problem**

In order to attach a second interface manually to the container, I create a veth interface pair.

We have a virtual device: veth.netdev 
```
[NetDev]
Name=veth1-interface
Kind=veth

[Peer]
Name=veth2-interface
```

One side is connected to a bridge: veth1-interface.network 
```
[Match]
Name=veth1-interface

[Network]
Bridge=br-interface
```

The other side is the endpoint we need.
veth2-interface.network
``` 
[Match]
Name=veth2-interface

[Network]
DHCP=yes
```

We have a corresponding file in the container, and only in the container: veth2.network 
```
[Match]
Virtualization=container
Name=veth2-interface

[Network]
DHCP=yes
```

We have an .nspawn file that tells our container to use that interface: test.nspawn 
```
[Network]
## the primary interface
Bridge=10.250.0.x
## the additional interface in question
Interface=veth2-interface

[ ... ]
```

After restarting systemd-networkd both interfaces are up:
```
veth1-interface: Gained carrier
veth1-interface: Configured
veth2-interface: Gained carrier
veth2-interface: DHCPv4 address 10.10.0.14/24 via 10.10.0.1
```

```
br-interface		8000.e6ec11b978c8	no		vlan-interface
							veth1-interface

```

ip addr show
```
65: veth2-interface@veth1-interface: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 4e:f7:29:ad:c2:4a brd ff:ff:ff:ff:ff:ff
    inet 10.10.0.14/24 brd 10.10.0.255 scope global dynamic veth2-ellatohaz
       valid_lft 341sec preferred_lft 341sec
    inet6 fe80::4cf7:29ff:fead:c24a/64 scope link 
       valid_lft forever preferred_lft forever
66: veth1-interface@veth2-interface: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-interface state UP group default qlen 1000
    link/ether ea:d1:ee:f0:76:0d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::e8d1:eeff:fef0:760d/64 scope link 
       valid_lft forever preferred_lft forever

```

So far all good. Container starts. veth2 appears as the second interface in the container, has the right ip all good.

Then, the Container is stopped.

When tryin to start the container again:
```
systemd-nspawn[..]: Failed to resolve interface veth2-interface: No such device
```

And indeed. ip addr show displays none of the two veth interfaces, not attached to the bridge, nix nada, it disappeared.

Restarting systemd-networkd brings the interface up again, but this behavior is not documented, in fact to documentation says the interface should appear on the host namespace, hence reporting as a bug.

### PR DESCRIPTION
**Pull request by daandemeyer**
Should fix #13530. I've only tested with a physical ethernet interface and veth interfaces created with iproute2 directly. @LaKing can you test this PR as well if you get the chance?

`--network-interface` explicitly documents that interfaces added with it are moved back to the host when the container shuts down. Currently, this is only the case for physical interfaces. This PR makes sure nspawn moves back all interfaces (virtual and physical).

The implementation consists of keeping the child's network namespace alive by opening the corresponding file in proc (/proc/\<pid\>/ns/net), entering it after the container shuts down, moving back the interfaces to the parent network namespace and leaving the child network namespace.

Because the `sd_device` checks in `parse_interface` failed when moving back the interfaces to the parent with `move_network_interfaces` (probably because we still have the host's view of /sys/ which doesn't have the interfaces in the container network namespace), I moved the `sd_device` checks out of `parse_interface` into a function `check_interface` which is called when parsing the command line arguments.

### CODE REVIEW

**Comment by yuwata** [comment]
Hmm. CIs dislike this or the test needs to be updated.

**Comment by DaanDeMeyer** [comment]
Cleaned this up a lot, should be good for a review now.

One problem we can't really solve is that if the container is SIGKILLED, we don't have the opportunity to move back network interfaces so they will still be removed. Maybe it's a good idea to document this?

**Comment by DaanDeMeyer** [comment]
CI failures seem unrelated to this PR.

File: src/nspawn/nspawn-network.c [hunk 1]
```diff
@@ -395,37 +395,49 @@ int remove_bridge(const char *bridge_name) {
...
+        int ifi, r;
+        char ifi_str[2 + DECIMAL_STR_MAX(int)];
 
-                sprintf(ifi_str, "n%i", ifi);
-                r = sd_device_new_from_device_id(&d, ifi_str);
-                if (r < 0)
-                        return log_error_errno(r, "Failed to get device %s: %m", name);
+        if (path_is_read_only_fs("/sys")) {
+                return 0;
+        }
```
Comment (poettering) [inline src/nspawn/nspawn-network.c]: no {} around single-line if blocks, see:

https://systemd.io/CODING_STYLE/

File: src/nspawn/nspawn-network.c [hunk 2]
```diff
@@ -395,37 +395,49 @@ int remove_bridge(const char *bridge_name) {
...
 
-                r = device_is_renaming(d);
-                if (r < 0)
-                        return log_error_errno(r, "Failed to determine the interface %s is being renamed: %m", name);
-                if (r > 0)
-                        return log_error_errno(SYNTHETIC_ERRNO(EBUSY), "Interface %s is being renamed.", name);
+        ifi = parse_interface(name);
+        if (ifi < 0) {
+                return ifi;
         }
```
Comment (poettering) [inline src/nspawn/nspawn-network.c]: as above

File: src/nspawn/nspawn-network.c [hunk 3]
```diff
@@ -395,37 +395,49 @@ int remove_bridge(const char *bridge_name) {
...
         if (r < 0)
                 return log_error_errno(r, "Failed to resolve interface %s: %m", name);
 
-        if (path_is_read_only_fs("/sys") <= 0) {
-                char ifi_str[2 + DECIMAL_STR_MAX(int)];
+        return ifi;
+}
 
-                /* udev should be around. */
+int check_interface(const char *name) {
```
Comment (poettering) [inline src/nspawn/nspawn-network.c]: check is such a generic name. If you split this, maybe call this network_interface_test_initialized(), because that's what it actually does? Also, given you export this function now, really say "network interface" rather than just "interface", to be explicit, given that "interface" is used in many contexts on computers...

File: src/nspawn/nspawn.c [hunk 4]
```diff
@@ -848,6 +848,10 @@ static int parse_argv(int argc, char *argv[]) {
                                 return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
                                                        "Network interface name not valid: %s", optarg);
 
+                        r = check_interface(optarg);
+                        if (r < 0)
+                                return r;
+
```
Comment (poettering) [inline src/nspawn/nspawn.c:854]: so we check all those interfaces twice now? Why?

File: src/nspawn/nspawn-network.c [hunk 5]
```diff
@@ -440,40 +445,91 @@ int check_interface(const char *name) {
...
+        int fd = -1;
+
+        xsprintf(path, "/proc/" PID_FMT "/ns/net", pid);
+
+        fd = open(path, O_CLOEXEC|O_RDONLY|O_NOCTTY);
+        if (fd < 0)
+                return log_error_errno(errno, "Failed to open network namespace %s: %m", path);
+
+        return fd;
+}
```
Comment (poettering) [inline src/nspawn/nspawn-network.c]: this is pretty close to namespace_open() with a number of NULL params...

File: src/nspawn/nspawn-network.c [hunk 6]
```diff
@@ -440,40 +445,91 @@ int check_interface(const char *name) {
...
-        r = sd_netlink_open(&rtnl);
+        /* We can only move network interfaces from the current network namespace so we enter the
+         * network namespace from which we want to move interfaces. */
+
+        char current_netns_path[STRLEN("/proc//ns/net") + DECIMAL_STR_MAX(pid_t) + 1];
+        xsprintf(current_netns_path, "/proc/" PID_FMT "/ns/net", getpid());
+
+        current_netns_fd = open(current_netns_path, O_CLOEXEC|O_RDONLY|O_NOCTTY);
+        if (current_netns_fd < 0)
+                return log_error_errno(errno, "Failed to open file %s: %m", current_netns_path);
```
Comment (poettering) [inline src/nspawn/nspawn-network.c]: use namespace_open()?

File: src/nspawn/nspawn-network.c [hunk 7]
```diff
@@ -440,40 +445,91 @@ int check_interface(const char *name) {
...
+
+        r = namespace_enter(-1, -1, from, -1, -1);
```
Comment (poettering) [inline src/nspawn/nspawn-network.c]: hmm, I'd prefer if we change namespaces only in child processes forked off precisely for that purpose, and which then dies. i.e. I am very strongly of the opinion that namespace changes should not be done willy-nilly and not jumping forth and back but just done as one-way street really. Hence, please use safe_fork() to fork something off that enters the namespace, does what it needs to do and then exits, and the parent just waits for that. I don#t wnat nspawn#s main process jumping namespaces really...

File: src/nspawn/nspawn.c [hunk 8]
```diff
@@ -4415,16 +4416,30 @@ static int run_container(
...
+                current_netns_fd = open_network_namespace(getpid());
+                if (current_netns_fd < 0)
+                        return current_netns_fd;
+
+                r = move_network_interfaces(current_netns_fd, *child_netns_fd, arg_network_interfaces);
                 if (r < 0)
                         return r;
 
+                *network_interfaces_moved = true;
+
```
Comment (poettering) [inline src/nspawn/nspawn.c]: we generally try to avoid functions that clobber their return values even on failure, see coding style.

That said, I think you should move the ifaces back inside of run_container() instead of in run(), to properly deal with reboots of the container. i.e. we call run_container() in a loop as long as the contains is restarted via reboot(), and you probably want to move back the ifaces from the guest ns to the host on each cycle of that, to move them again into the new netns of the next reboot instance. But that also means you don't need to return the netns here, and hence the argument clobbering goes away too

File: src/nspawn/nspawn.c (hunk 4 above)
Comment (daandemeyer) [reply src/nspawn/nspawn.c:854]: I'm not sure what you mean here? The `ARG_NETWORK_INTERFACE` and `ARG_NETWORK_MACVLAN` cases don't seem to fall through. Doesn't that mean we have to repeat the check for all the different types of interfaces? As far as I can see we're checking each network interface once in the switch now and don't check them again after.

Comment (poettering) [reply src/nspawn/nspawn.c:854]: we check in move_network_interfaces() again, no?

Comment (daandemeyer) [reply src/nspawn/nspawn.c:854]: `move_network_interfaces` just calls `parse_interface` which doesn't do the check anymore (unless I'm missing something really obvious somewhere). The idea was to move the checking out of `parse_interface` so it could be used from inside a different network namespace without udev complaining.

File: src/nspawn/nspawn-network.c (hunk 3 above)
Comment (daandemeyer) [reply src/nspawn/nspawn-network.c]: Went with `test_network_interface_initialized`.

File: src/nspawn/nspawn.c (hunk 8 above)
Comment (daandemeyer) [reply src/nspawn/nspawn.c]: Moved everything into `run_container`.

File: src/nspawn/nspawn-network.c (hunk 7 above)
Comment (daandemeyer) [reply src/nspawn/nspawn-network.c]: I pushed a new version using `safe_fork`. Can you verify if `safe_fork` is invoked with the right flags?

**Comment by DaanDeMeyer** [comment]
Thanks for the detailed review. I pushed a simpler implementation based on your feedback. The one thing that's missing now is that the interfaces aren't moved back if an error occurs after moving the network interfaces to the child network namespace. I don't really see a way to implement that outside of putting the usual `goto finish` everywhere in `run_container` which I'd prefer to avoid. Any ideas for that?

**Comment by DaanDeMeyer** [comment]
I've been using this PR and https://github.com/systemd/systemd/pull/14420 extensively for some integration tests with rebooting containers (the `--keep-unit` kind) and so far I haven't noticed any issues.

File: src/nspawn/nspawn.c [hunk 9]
```diff
@@ -4212,6 +4212,7 @@ static int run_container(
         ssize_t l;
         sigset_t mask_chld;
         _cleanup_close_ int netns_fd = -1;
+        _cleanup_close_ int child_netns_fd = -1;
```
Comment (poettering) [inline src/nspawn/nspawn.c:4214]: hmm, these two variables both refer to the same object btw: the child's netns. One is used in the existing code when you specify --natwork-namespace-path= and the other in any case. I think we should just reuse the same variable here, it's going to be the same thing. Moreover, if netns_fd is already found initialized (because --network-namespace-path= is set) then we shouldn't open things a second time and just reuse the thing.

File: src/nspawn/nspawn.c [hunk 10]
```diff
@@ -4421,7 +4422,13 @@ static int run_container(
                                 return log_error_errno(SYNTHETIC_ERRNO(ESRCH), "Child died too early");
                 }
 
-                r = move_network_interfaces(*pid, arg_network_interfaces);
+                /* Even if the child exits, the child's network namespace namespace will stay alive
+                 * until this file descriptor is closed. */
+                r = namespace_open(*pid, NULL, NULL, &child_netns_fd, NULL, NULL);
+                if (r < 0)
+                        return log_error_errno(r, "Failed to open child network namespace: %m");
```
Comment (poettering) [inline src/nspawn/nspawn.c]: as mentioned above: do this only in netns_fd is not set already.

File: src/nspawn/nspawn.c [hunk 11]
```diff
@@ -4667,6 +4674,33 @@ static int run_container(
...
 
+        if (arg_private_network) {
+                /* Move network interfaces back to the parent network namespace. */
+                _cleanup_close_ int parent_netns_fd = -1;
+
+                r = namespace_open(getpid_cached(), NULL, NULL, &parent_netns_fd, NULL, NULL);
+                if (r < 0)
+                        return log_error_errno(r, "Failed to open parent network namespace: %m");
+
+                r = safe_fork(NULL, FORK_RESET_SIGNALS|FORK_DEATHSIG|FORK_WAIT|FORK_REOPEN_LOG, NULL);
```
Comment (poettering) [inline src/nspawn/nspawn.c]: please add FORK_LOG, so that the call logs about errors on its own. (in your current patch on failure we don't log at all here!)

Also, please drop FORK_REOPEN_LOG. There's not really a need to do that (reopening the logs makes sense if we migrate cgroups or so, i.e. our client side process props change and we want the logging service to take notice, or when we do some fd tricks and want the log fd to go away, but neither is the case here)

File: src/nspawn/nspawn.c [hunk 12]
```diff
@@ -4667,6 +4674,33 @@ static int run_container(
         /* Normally redundant, but better safe than sorry */
         (void) kill(*pid, SIGKILL);
 
+        if (arg_private_network) {
+                /* Move network interfaces back to the parent network namespace. */
+                _cleanup_close_ int parent_netns_fd = -1;
+
+                r = namespace_open(getpid_cached(), NULL, NULL, &parent_netns_fd, NULL, NULL);
+                if (r < 0)
+                        return log_error_errno(r, "Failed to open parent network namespace: %m");
```
Comment (poettering) [inline src/nspawn/nspawn.c]: why not do this in the child? i mean it doesn't really matter, but i'd keep the fd scope short if it's easy

File: src/nspawn/nspawn.c (hunk 9 above)
Comment (daandemeyer) [reply src/nspawn/nspawn.c:4214]: Done, but I renamed `netns_fd` to `child_netns_fd` for clarity.

**Comment by poettering** [comment]
thanks! lgtm!
