### PR TITLE
systemctl: exit with 1 if no unit files found

### LINKED ISSUE #15082: list-unit-files returns 0 if no unit files found
**systemd version the issue has been seen with**
> systemd 241 and 244.3-1

**Used distribution**
 > Debian testing and unstable

**Expected behaviour you didn't see**
 > Exit code is not 0.

**Unexpected behaviour you saw**
 > Exit code is 0

**Steps to reproduce the problem**
```
mdione@neomustang:~$ systemctl list-unit-files prometheus.service

0 unit files listed.
mdione@neomustang:~$ echo $?
0
```

### PR DESCRIPTION
**Pull request by GiedriusS**
Add a simple check on the number of unit files that were found: return
from the function and exit with 1 if none were found.

Verification:
```bash
root@image:~# systemctl list-unit-files dbus-nonexistant.service; echo
$?
UNIT FILE STATE VENDOR PRESET

0 unit files listed.
1
root@image:~# systemctl list-unit-files dbus.service; echo $?
UNIT FILE    STATE  VENDOR PRESET
dbus.service static enabled

1 unit files listed.
0
```

Fixes #15082.

### CODE REVIEW

File: src/systemctl/systemctl.c [hunk 1]
```diff
@@ -1658,6 +1658,9 @@ static int list_unit_files(int argc, char *argv[], void *userdata) {
                 for (unit = units; unit < units + c; unit++)
                         free(unit->path);
 
+        if (c == 0)
+            return 1;
```
Comment (anitazha) [inline src/systemctl/systemctl.c]: 8 space indent please

Comment (GiedriusS) [reply src/systemctl/systemctl.c]: Sorry, this is embarrassing. Pushed a change which makes this line use proper indentation.

File: src/systemctl/systemctl.c [hunk 2]
```diff
@@ -1658,6 +1658,9 @@ static int list_unit_files(int argc, char *argv[], void *userdata) {
                 for (unit = units; unit < units + c; unit++)
                         free(unit->path);
 
+        if (c == 0)
+                return 1;
```
Comment (anitazha) [inline src/systemctl/systemctl.c]: Sorry I really should have mentioned this in the last comment, but please return a negative error code here per the coding style guidelines (maybe `-ENOENT`?).

Comment (GiedriusS) [reply src/systemctl/systemctl.c]: Thanks, I have done that. I thought those were reserved for functions which clobber `errno`. Will know now for the future. Also, I have rebased and squashed the commits on top of `master`. Let me know if there are any other problems.

**Comment by anitazha** [comment]
Thanks!
