### PR TITLE
modprobe.d: ship drop-in to set bonding max_bonds to 0

### LINKED ISSUE #5971: networkd creates bond0, yet does not apply parameters to it
### Submission type

  - [ ] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

v229-4ubuntu17 on 4.4.0-77-generic

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

Yes, will retest with more recent stuff.

### Used distribution

Ubuntu 16.04

### In case of bug report: Expected behaviour you didn't see

```
May 15 17:38:37 xnox-iad-nr5 systemd-networkd[934]: bond0: netdev ready
May 15 17:38:37 xnox-iad-nr5 systemd-networkd[934]: Enumeration completed
May 15 17:38:37 xnox-iad-nr5 kernel: bond0 (uninitialized): Setting MII monitoring interval to 100000
May 15 17:38:37 xnox-iad-nr5 kernel: bond0 (uninitialized): Setting xmit hash policy to layer3+4 (1)
May 15 17:38:37 xnox-iad-nr5 kernel: bond0 (uninitialized): Setting resend_igmp to 1
```

### In case of bug report: Unexpected behaviour you saw

```
May 15 16:27:50 ubuntu systemd-networkd[977]: bond0: netdev ready
May 15 16:27:50 ubuntu systemd-networkd[977]: Enumeration completed
May 15 16:27:50 ubuntu systemd-networkd[977]: bond0: netdev exists, using existing without changing its parameters
```

### In case of bug report: Steps to reproduce the problem

1. Specify bond .netdev unit named bond0 with non-default Mode TransmitHashPolicy MIIMonitorSec LACPTransmitRate e.g.:
```
Mode=802.3ad
TransmitHashPolicy=layer3+4
MIIMonitorSec=1s
LACPTransmitRate=fast
```
2. Make sure bonding module is not loaded by default, e.g. it is _not_ listed in modules-load.d or similar
3. Observe that networkd auto-creates the bond0 device, yet does not set its settings

### Similar bug reports
* https://bugs.freedesktop.org/show_bug.cgi?id=82956

* This is affects cloud-init as it now can generated networkd config via nplan, which results in bond0 configs. Also i think people migrating to networkd would want to use bond0 still out of the box.

### Possible fixes
* ship [/usr]/lib/modprobe.d/ snippet to set `options bonding max_bonds=0` to prevent bond0 autocreation

* somehow check before-hand that bond0 does not exist, and when it get magically autocreated, force apply settings onto it anyway. I got lost in the networkd code a bit to figure out where all these things are happening via VTABLE callbacks =/

### PR DESCRIPTION
**Pull request by xnox**
This allows networkd to correctly manage bond0 using networkd, when requested
by the user.

Fixes #5971 #6184

### CODE REVIEW

**Comment by martinpitt** [comment]
Note: During merge (or through a force-push) the commit message should be normalized: add a "modprobe.d:" prefix and start with a lower-case letter.

File: modprobe.d/systemd.conf [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+#
+#  systemd is free software; you can redistribute it and/or modify it
+#  under the terms of the GNU Lesser General Public License as published by
+#  the Free Software Foundation; either version 2.1 of the License, or
+#  (at your option) any later version.
+#
+# When bonding module is loaded, it creates bond0 by default due to max_bonds
+# option default value 1. This interferes with the network configuration
+# management / networkd, as it is not possible to detect whether this bond0 was
+# intentially configured by the user, or should be managed by
```
Comment (keszybz) [inline modprobe.d/systemd.conf]: intentionally

**Comment by poettering** [comment]
Hmm, yeah, ideally we shouldn't do this, but given that the kernel is unlikely to fix this any time soon, the patch looks OK. However, we need to document this in NEWS, so that downstream distros know about this and can opt-out if they like.

**Comment by xnox** [comment]
@martinpitt where or how can I adjust debian packaging to account for the extra shipped file / directory?

**Comment by martinpitt** [comment]
@xnox: I'd put it into https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/udev.install ;  I think it makes more sense to ship a `modprobe.d/` snippet in udev than in the `systemd` binary package, as it's not needed in containers.

**Comment by yuwata** [comment]
The file is installed at `/usr/lib64/modprobe.d/systemd.conf`. However, at least on Fedora, it should be installed at `/usr/lib/modprobe.d/systemd.conf`.

**Comment by xnox** [comment]
@yuwata right this does seem to be wrong. I was aiming to have this to be installed into more or less `/usr/lib/systemd/system/../../modprobe.d/` such that it is correctly installed into `/lib/modprobe.d` on Debian/Ubuntu and `/usr/lib/modprobe.d`. I am not familiar with meson yet, thus I may have gotten the variable substitution wrong.

**Comment by yuwata** [comment]
@xnox I forgot to reference this PR but the fix is already merged ad6fc5bbaef13cc0faee65ab2dad963ee36b3529.
