### PR TITLE
resolve: unsupported DNSSEC algorithms are considered INSECURE

### LINKED ISSUE #19824: Unsupported DNSSEC algorithms should be considered INSECURE, not BOGUS
**systemd version the issue has been seen with**
 > systemd-248.3-1.fc35.x86_64

**Used distribution**
 > Fedora Rawhide

**Linux kernel version used** (`uname -a`)

 > `Linux pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 5.12.0-0.rc4.20210325gite138138003eb.177.fc35.x86_64 #1 SMP Thu Mar 25 16:45:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > status: NOERROR should be returned for unknown algorithms. Only ad flag should be missing in header flags.

**Unexpected behaviour you saw**
 > 
```
# dig @127.0.0.53 secure.d4a6n3.rootcanary.net

; <<>> DiG 9.16.16-RH <<>> @127.0.0.53 secure.d4a6n3.rootcanary.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 53963
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;secure.d4a6n3.rootcanary.net.	IN	A

;; ANSWER SECTION:
secure.d4a6n3.rootcanary.net. 60 IN	A	145.97.20.17

;; Query time: 366 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Jun 04 14:38:14 EDT 2021
;; MSG SIZE  rcvd: 73
```

**Steps to reproduce the problem**
 > Resolved multiple hosts from https://rootcanary.org/test.html test. Many of them returns SERVFAIL and unusually also response answer. But well behaved resolver should return NOERROR for unsupported algorithms.

- set DNSSEC=yes in /etc/systemd/resolved.conf
- systemctl restart systemd-resolved
- dig @127.0.0.53 secure.d4a6n3.rootcanary.net

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Found verdict for lookup rootcanary.net IN DS: secure
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Regular transaction 21237 for <rootcanary.net IN DS> on scope dns on eth0/* now complete with <success> from network (authent>
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Validating response from transaction 56396 (rootcanary.net IN DNSKEY).
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Looking at rootcanary.net IN DNSKEY 257 3 RSASHA256 AwEAAdDk0xPx74/+J4BFAtodd6j2yTDoX9D+paS
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:                                          jzxVl+jMQmrsrQprdBxX3fale9f62j4oo7scfU+
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:                                          wabBXl56lehbw/wds6oVqDNun9ORQisXhIq9H+u
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:                                          3a9WtTAF+OQyPoSirRLYdNR7+wWvb88L27w88+j
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:                                          L0gkFb8klGzr03EFrq6r
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         -- Flags: SEP ZONE_KEY
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         -- Key tag: 64786: validated
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Found verdict for lookup rootcanary.net IN DNSKEY: secure
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Regular transaction 56396 for <rootcanary.net IN DNSKEY> on scope dns on eth0/* now complete with <success> from network (aut>
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Validating response from transaction 23158 (d4a6n3.rootcanary.net IN DS).
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Looking at d4a6n3.rootcanary.net IN DS 55720 6 4 b599235bcba03975733a5b17a65c8ad65698ad0478d3fe5a628519d067dd381ad1a4a9b0fb38>
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Found verdict for lookup d4a6n3.rootcanary.net IN DS: secure
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Regular transaction 23158 for <d4a6n3.rootcanary.net IN DS> on scope dns on eth0/* now complete with <success> from network (>
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Validating response from transaction 55929 (d4a6n3.rootcanary.net IN DNSKEY).
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Looking at d4a6n3.rootcanary.net IN DNSKEY 257 3 DSA-NSEC3-SHA1
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         CKoJzM6LpXWxMZuzYjB60/QKvVf1xgPJfi3C6iUrrnOYcwXIZMcS7gaua4fcPgxju6eoVdg
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         CN/YyLybq3MDe+drW1pI0LWolVZSJlp2XqUX6vPe8O8GyU5oDFkGk+INU3DD+ayWoONNcfO
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         5fvrsjG1wqsVZjC4AKAyyO2TxUpyMa5FdAh5aeXz9USBrh0uHvfMMC7nO5OdoH9PlZhaaZz
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         32BfkSpkuDxjeXAt/vZ59r86PFz5Q/om2udRWAQrPprdJBxmuai4EA3rC9uEv1JZqLGdP8+
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         qVvx3H+xs27rq/9rKFC99yx0yNzkD8tx0WJVwuvNBKYDpl4hy+CM+kld3vQOzMmu+MTIVOR
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         kmTLGkD74lqJ0QAhumSpsKRu5Kl5xaC56OQihIYKfMoUI0/Fxz+5pFwRjXRH5AynWExfMep
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         V7Qn6++f+ATu8NViwsLGXm+Psor40PPTjYMv8jML9bz/CaO7t+LjPg6LrXy0sH9Vek8pK29
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         t291X+oW9HEej2WQTBhTpiAW1p529uevcMfrWje2/sO
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         -- Flags: SEP ZONE_KEY
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         -- Key tag: 55720: unsupported-algorithm
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Looking at d4a6n3.rootcanary.net IN DNSKEY 257 3 DSA-NSEC3-SHA1
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         CKoJzM6LpXWxMZuzYjB60/QKvVf1xgPJfi3C6iUrrnOYcwXIZMcS7gaua4fcPgxju6eoVdg
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         CN/YyLybq3MDe+drW1pI0LWolVZSJlp2XqUX6vPe8O8GyU5oDFkGk+INU3DD+ayWoONNcfO
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         5fvrsjG1wqsVZjC4AKAyyO2TxUpyMa5FdAh5aeXz9USBrh0uHvfMMC7nO5OdoH9PlZhaaZz
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         32BfkSpkuDxjeXAt/vZ59r86PFz5Q/om2udRWAQrPprdJBxmuai4EA3rC9uEv1JZqLGdP8+
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         qVvx3H+xs27rq/9rKFC99yx0yNzkD8tx0WJVwuvNBKYDpl4hy+CM+kld3vQOzMmu+MTIVOR
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         kmTLGkD74lqJ0QAhumSpsKRu5Kl5xaC56OQihIYKfMoUI0/Fxz+5pFwRjXRH5AynWExfMep
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         V7Qn6++f+ATu8NViwsLGXm+Psor40PPTjYMv8jML9bz/CaO7t+LjPg6LrXy0sH9Vek8pK29
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         t291X+oW9HEej2WQTBhTpiAW1p529uevcMfrWje2/sO
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         -- Flags: SEP ZONE_KEY
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]:         -- Key tag: 55720: unsupported-algorithm
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: Found verdict for lookup d4a6n3.rootcanary.net IN DNSKEY: indeterminate
Jun 04 14:38:14 pemensik-1mt-fedora-rawhide-2588999-2021-06-04-16-56 systemd-resolved[15919]: [🡕] DNSSEC validation failed for question d4a6n3.rootcanary.net IN DNSKEY: unsupported-algorithm
```

### PR DESCRIPTION
**Pull request by jacekmigacz**
For example:
```

[root@gh19824 ~]# resolvectl --cache=no query dnslabs.nl
dnslabs.nl: 2a05:1500:600:1:1c00:4aff:fe00:428 -- link: host0
```

```
[root@gh19824 ~]# resolvectl --cache=no query secure.d4a6n3.rootcanary.net
secure.d4a6n3.rootcanary.net: 145.97.20.20     -- link: host0
                              2001:610:188:408::20 -- link: host0
```

Fixes #19824.

### CODE REVIEW

File: src/resolve/resolved-dns-transaction.c [hunk 1]
```diff
@@ -3333,10 +3333,18 @@ static int dnssec_validate_records(
                         }
                 }
 
+                if (result == DNSSEC_UNSUPPORTED_ALGORITHM) {
+                        r = dns_answer_move_by_key(validated, &t->answer, rr->key, 0, NULL);
```
Comment (poettering) [inline src/resolve/resolved-dns-transaction.c:3337]: can you add a comment refefencing https://datatracker.ietf.org/doc/html/rfc6840#section-5.2 please?

Comment (bluca) [reply src/resolve/resolved-dns-transaction.c:3337]: trivial change to make, so just pushed so we can get the fix merged for the next release

**Review by bluca — APPROVED** [review]
