### PR TITLE
resolve: fix EDE handling

### LINKED ISSUE #30752: There is a memory leak in resolved caused by extended error messages
```sh
==15731==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 85 byte(s) in 85 object(s) allocated from:
    #0 0x7f61870d4e91 in __interceptor_strdup (/usr/lib64/clang/16/lib/libclang_rt.asan-x86_64.so+0xd4e91) (BuildId: 5e54448b65ce364ffd26e5e37071cc7230e8931b)
    #1 0x47480d in dns_query_accept /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:903:50
    #2 0x4650af in dns_query_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:993:9
    #3 0x461837 in dns_query_candidate_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:340:9
    #4 0x5249fc in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:461:17
    #5 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #6 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #7 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #8 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #9 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #10 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #11 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #12 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #13 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #14 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #15 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #16 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #17 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #18 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #19 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #20 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #21 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #22 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #23 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #24 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #25 0x53e3a5 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:987:17
    #26 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #27 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #28 0x53e631 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:997:17
    #29 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
Direct leak of 16 byte(s) in 16 object(s) allocated from:
    #0 0x7f61870d4e91 in __interceptor_strdup (/usr/lib64/clang/16/lib/libclang_rt.asan-x86_64.so+0xd4e91) (BuildId: 5e54448b65ce364ffd26e5e37071cc7230e8931b)
    #1 0x47480d in dns_query_accept /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:903:50
    #2 0x4650af in dns_query_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:993:9
    #3 0x461837 in dns_query_candidate_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:340:9
    #4 0x5249fc in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:461:17
    #5 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #6 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #7 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #8 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #9 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #10 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #11 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #12 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #13 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #14 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #15 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #16 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #17 0x53e3a5 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:987:17
    #18 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #19 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #20 0x53e631 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:997:17
    #21 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #22 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #23 0x53e631 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:997:17
    #24 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #25 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #26 0x53e631 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:997:17
    #27 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #28 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #29 0x53e631 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:997:17
Direct leak of 14 byte(s) in 14 object(s) allocated from:
    #0 0x7f61870d4e91 in __interceptor_strdup (/usr/lib64/clang/16/lib/libclang_rt.asan-x86_64.so+0xd4e91) (BuildId: 5e54448b65ce364ffd26e5e37071cc7230e8931b)
    #1 0x47480d in dns_query_accept /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:903:50
    #2 0x4650af in dns_query_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:993:9
    #3 0x461837 in dns_query_candidate_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:340:9
    #4 0x5249fc in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:461:17
    #5 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #6 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #7 0x52fd76 in dns_transaction_process_reply /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:1439:9
    #8 0x5695d9 in on_dns_packet /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:1492:9
    #9 0x7f618668247c in source_dispatch /home/vagrant/systemd-asan/build/../src/libsystemd/sd-event/sd-event.c:4187:21
    #10 0x7f61866804a4 in sd_event_dispatch /home/vagrant/systemd-asan/build/../src/libsystemd/sd-event/sd-event.c:4808:21
    #11 0x7f6186685f9d in sd_event_run /home/vagrant/systemd-asan/build/../src/libsystemd/sd-event/sd-event.c:4869:21
    #12 0x7f6186686f29 in sd_event_loop /home/vagrant/systemd-asan/build/../src/libsystemd/sd-event/sd-event.c:4891:21
    #13 0x66bc78 in run /home/vagrant/systemd-asan/build/../src/resolve/resolved.c:92:13
    #14 0x669cbd in main /home/vagrant/systemd-asan/build/../src/resolve/resolved.c:99:1
    #15 0x7f6184649b89 in __libc_start_call_main (/lib64/libc.so.6+0x27b89) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #16 0x7f6184649c4a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x27c4a) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #17 0x40d474 in _start (/home/vagrant/systemd-asan/build/systemd-resolved+0x40d474) (BuildId: 91f2fbabf326b3627b4b58de9be18451924d835c)
Direct leak of 9 byte(s) in 9 object(s) allocated from:
    #0 0x7f61870d4e91 in __interceptor_strdup (/usr/lib64/clang/16/lib/libclang_rt.asan-x86_64.so+0xd4e91) (BuildId: 5e54448b65ce364ffd26e5e37071cc7230e8931b)
    #1 0x47480d in dns_query_accept /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:903:50
    #2 0x4650af in dns_query_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:993:9
    #3 0x461837 in dns_query_candidate_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:340:9
    #4 0x5249fc in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:461:17
    #5 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #6 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #7 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #8 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #9 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #10 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #11 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #12 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #13 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #14 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #15 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #16 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #17 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #18 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #19 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #20 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #21 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #22 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #23 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #24 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #25 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #26 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #27 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #28 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #29 0x53e3a5 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:987:17
Direct leak of 5 byte(s) in 5 object(s) allocated from:
    #0 0x7f61870d4e91 in __interceptor_strdup (/usr/lib64/clang/16/lib/libclang_rt.asan-x86_64.so+0xd4e91) (BuildId: 5e54448b65ce364ffd26e5e37071cc7230e8931b)
    #1 0x47480d in dns_query_accept /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:903:50
    #2 0x4650af in dns_query_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:993:9
    #3 0x461837 in dns_query_candidate_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:340:9
    #4 0x5249fc in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:461:17
    #5 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #6 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #7 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #8 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #9 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #10 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #11 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #12 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #13 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #14 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #15 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #16 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #17 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #18 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #19 0x52fd76 in dns_transaction_process_reply /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:1439:9
    #20 0x5695d9 in on_dns_packet /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:1492:9
    #21 0x7f618668247c in source_dispatch /home/vagrant/systemd-asan/build/../src/libsystemd/sd-event/sd-event.c:4187:21
    #22 0x7f61866804a4 in sd_event_dispatch /home/vagrant/systemd-asan/build/../src/libsystemd/sd-event/sd-event.c:4808:21
    #23 0x7f6186685f9d in sd_event_run /home/vagrant/systemd-asan/build/../src/libsystemd/sd-event/sd-event.c:4869:21
    #24 0x7f6186686f29 in sd_event_loop /home/vagrant/systemd-asan/build/../src/libsystemd/sd-event/sd-event.c:4891:21
    #25 0x66bc78 in run /home/vagrant/systemd-asan/build/../src/resolve/resolved.c:92:13
    #26 0x669cbd in main /home/vagrant/systemd-asan/build/../src/resolve/resolved.c:99:1
    #27 0x7f6184649b89 in __libc_start_call_main (/lib64/libc.so.6+0x27b89) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #28 0x7f6184649c4a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x27c4a) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #29 0x40d474 in _start (/home/vagrant/systemd-asan/build/systemd-resolved+0x40d474) (BuildId: 91f2fbabf326b3627b4b58de9be18451924d835c)
Direct leak of 3 byte(s) in 3 object(s) allocated from:
    #0 0x7f61870d4e91 in __interceptor_strdup (/usr/lib64/clang/16/lib/libclang_rt.asan-x86_64.so+0xd4e91) (BuildId: 5e54448b65ce364ffd26e5e37071cc7230e8931b)
    #1 0x47480d in dns_query_accept /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:903:50
    #2 0x4650af in dns_query_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:993:9
    #3 0x461837 in dns_query_candidate_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:340:9
    #4 0x5249fc in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:461:17
    #5 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #6 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #7 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #8 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #9 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #10 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #11 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #12 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #13 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #14 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #15 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #16 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #17 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #18 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #19 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #20 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #21 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #22 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #23 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #24 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #25 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #26 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #27 0x52fd76 in dns_transaction_process_reply /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:1439:9
    #28 0x5695d9 in on_dns_packet /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:1492:9
    #29 0x7f618668247c in source_dispatch /home/vagrant/systemd-asan/build/../src/libsystemd/sd-event/sd-event.c:4187:21
Direct leak of 2 byte(s) in 2 object(s) allocated from:
    #0 0x7f61870d4e91 in __interceptor_strdup (/usr/lib64/clang/16/lib/libclang_rt.asan-x86_64.so+0xd4e91) (BuildId: 5e54448b65ce364ffd26e5e37071cc7230e8931b)
    #1 0x47480d in dns_query_accept /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:903:50
    #2 0x4650af in dns_query_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:993:9
    #3 0x461837 in dns_query_candidate_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-query.c:340:9
    #4 0x5249fc in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:461:17
    #5 0x55fc5b in dns_transaction_dnssec_ready /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:908:25
    #6 0x53df59 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:944:13
    #7 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #8 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #9 0x53e3a5 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:987:17
    #10 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #11 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #12 0x53e631 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:997:17
    #13 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #14 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #15 0x53e631 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:997:17
    #16 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #17 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #18 0x53e631 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:997:17
    #19 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #20 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #21 0x53e631 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:997:17
    #22 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #23 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #24 0x53e631 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:997:17
    #25 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #26 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
    #27 0x53e631 in dns_transaction_process_dnssec /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:997:17
    #28 0x5269ff in dns_transaction_notify /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:2756:17
    #29 0x525901 in dns_transaction_complete /home/vagrant/systemd-asan/build/../src/resolve/resolved-dns-transaction.c:471:17
SUMMARY: AddressSanitizer: 134 byte(s) leaked in 134 allocation(s).
```

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for #30513.

Fixes #30752, #30776, and #30779.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx @rpigott 

@mrc0mmand Is it possible to add tests for EDE code?

**Comment by rpigott** [comment]
Thanks for the fixes.

I'm not sure about the tests in this case, but probably? I see EDE is a listed feature here anyway https://www.knot-dns.cz/docs/3.2/singlehtml/, but idk how to configure it. The feature-detection bit also only cares about EDE on SERVFAIL responses, which I'm not sure how to induce from knot.

**Comment by mrc0mmand** [comment]
> cc @evverx @rpigott
> 
> @mrc0mmand Is it possible to add tests for EDE code?

This is actually harder than I expected. `knot` itself returns an EDE code only in a handful of instances - either when a zone is frozen and you request AXFR/IXFR, or when the zone itself is in some inconsistent state. The first one won't help us, because resolvectl can't so XFR. The second one took me some time, because `knot` really makes sure the zone is always in a consistent state, but I managed to come up with https://github.com/mrc0mmand/systemd/commits/dns-shenanigans/ - in this case `knot` returns `SERVFAIL` + EDE 24 (Invalid Data):

```
# journalctl --file /var/tmp/systemd-tests/systemd-test.6RWXSk/system.journal --grep "Server returned error"
Jan 07 16:27:13 ns1.unsigned.test systemd-resolved[457]: Server returned error: SERVFAIL (Invalid Data(null))
Jan 07 16:27:13 ns1.unsigned.test systemd-resolved[457]: Server returned error: SERVFAIL (Invalid Data(null))
Jan 07 16:27:13 ns1.unsigned.test systemd-resolved[457]: Server returned error: SERVFAIL (Invalid Data(null))
Jan 07 16:27:13 ns1.unsigned.test systemd-resolved[457]: Server returned error: SERVFAIL (Invalid Data(null))
Jan 07 16:27:13 ns1.unsigned.test systemd-resolved[457]: Server returned error: SERVFAIL (Invalid Data(null))
```

However, it still doesn't seem to reproduce any of the mentioned crashes...

**Comment by mrc0mmand** [comment]
One unrelated but interesting find: while playing around with the XFR stuff, I noticed that IXFR=xx doesn't play well with resolved, i.e.:

```
$ dig @127.0.0.53 IXFR=42 nix.cz
;; communications error to 127.0.0.53#53: end of file
;; communications error to 127.0.0.53#53: timed out
;; communications error to 127.0.0.53#53: timed out

; <<>> DiG 9.18.20 <<>> @127.0.0.53 IXFR=42 nix.cz
; (1 server found)
;; global options: +cmd
;; no servers could be reached
```

But when using my local DNS server explicitly, the query fails as expected:

```
$ dig @192.168.1.1 IXFR=42 nix.cz

; <<>> DiG 9.18.20 <<>> @192.168.1.1 IXFR=42 nix.cz
; (1 server found)
;; global options: +cmd
; Transfer failed.
```

No idea if that's expected, but it definitely interesting.

**Comment by yuwata** [comment]
> One unrelated but interesting find: while playing around with the XFR stuff, I noticed that IXFR=xx doesn't play well with resolved,

-> #30815.

**Comment by rpigott** [comment]
> However, it still doesn't seem to reproduce any of the mentioned crashes...

The two crashes reported I see are both related to missing the new transaction result in a switch-case hitting an "unreachable" assert. Those code paths would only be covered in the case of a recursive validating resolver reporting dnssec errors, so sadly probably not reproducible with knot.

FWIW I had been testing just by manually trying `resolvectl query dnssec-failed.org` in a container, but I guess that doesn't hit these cases with the stub resolver and varlink interface. I also didn't have sanitizers in my container, so I never discovered the message leak. I actually didn't realize the transaction object was reused, so didn't think there was anything to free...

**Comment by evverx** [comment]
> However, it still doesn't seem to reproduce any of the mentioned crashes...

I think as a stopgap it should be possible to run a "server" like
```
ncat -v --sh-exec $(pwd)/SERVER -l -k -u 127.0.0.1 53
```
where SERVER look like
```
#!/bin/bash

set -e

t=$(mktemp)
head -c+2 >"$t"
printf '\x81\x82\x00\x01\x00\x00\x00\x00\x00\x01\x07example\x03com\x00\x00\x01\x00\x01\x00\x00)\x04\xd0\x00\x00\x00\x00\x00\x06\x00\x0f\x00\x02\x00\x06' >>"$t"
cat "$t"
tail >/dev/null
rm -rf "$t"
```
once `resolved` points to `127.0.0.1` and `DNSSEC=no` both `dig @127.0.0.53 example.com` and
```sh
printf '{"method":"io.systemd.Resolve.ResolveHostname","parameters":{"name":"example.com"}}\0' | ncat -U /run/systemd/resolve/io.systemd.Resolve
```
can be used to reproduce the crashes. It's kludgy but it exercises the codepaths. With `DNSSEC=yes` `resolvectl query example.com` should trigger the memory leak.

**Comment by mrc0mmand** [comment]
> > However, it still doesn't seem to reproduce any of the mentioned crashes...
> 
> I think as a stopgap it should be possible to run a "server" like
> 
> ```
> ncat -v --sh-exec $(pwd)/SERVER -l -k -u 127.0.0.1 53
> ```
> 
> where SERVER look like
> 
> ```
> #!/bin/bash
> 
> set -e
> 
> t=$(mktemp)
> head -c+2 >"$t"
> printf '\x81\x82\x00\x01\x00\x00\x00\x00\x00\x01\x07example\x03com\x00\x00\x01\x00\x01\x00\x00)\x04\xd0\x00\x00\x00\x00\x00\x06\x00\x0f\x00\x02\x00\x06' >>"$t"
> cat "$t"
> tail >/dev/null
> rm -rf "$t"
> ```
> 
> once `resolved` points to `127.0.0.1` and `DNSSEC=no` both `dig @127.0.0.53 example.com` and
> 
> ```shell
> printf '{"method":"io.systemd.Resolve.ResolveHostname","parameters":{"name":"example.com"}}\0' | ncat -U /run/systemd/resolve/io.systemd.Resolve
> ```
> 
> can be used to reproduce the crashes. It's kludgy but it exercises the codepaths. With `DNSSEC=yes` `resolvectl query example.com` should trigger the memory leak.

Thank you for the reproducer! I think it should be possible to write a simple dummy server binary with a couple of hard-to-reproduce scenarios (like the one above) and then hide it behind Knot's `dnsproxy` module, so it automagically forwards queries for certain zones to the dummy binary. I'll try to play around with this for a bit, to see how viable it actually is.

**Comment by mrc0mmand** [comment]
@yuwata could you please rebase this? I have a test case prepared and would like to slap it on top of this PR, but it needs changes from main (and I'd like to avoid force pushing to your branch).

**Comment by yuwata** [comment]
> @yuwata could you please rebase this? I have a test case prepared and would like to slap it on top of this PR, but it needs changes from main (and I'd like to avoid force pushing to your branch).

Done. It's always OK to force-push on my branch. I have my own backup.

**Comment by mrc0mmand** [comment]
> > @yuwata could you please rebase this? I have a test case prepared and would like to slap it on top of this PR, but it needs changes from main (and I'd like to avoid force pushing to your branch).
> 
> Done. It's always OK to force-push on my branch. I have my own backup.

Thank you!

With my somewhat limited DNS knowledge (and thanks to @evverx's reproducer), implemented a _very_ simple test DNS server (it might look like a lot of code, but that's just C), which allows us to twiddle with the packet a bit more. With it I was able to trigger the mentioned memory leaks and the assertion, as well as a couple of other issues - see the FIXMEs in the test script. It's a slightly more involved than a simple shell script, but on the other hand it uses (and hence tests) our code, so I think it's a net positive.

Also, to make it a bit easier to use during tests I hid it behind Knot using the `dnsproxy` module, so it doesn't require manually pointing tools to the test server.

Feel free to tweak it further as necessary.

**Comment by yuwata** [comment]
> > > @yuwata could you please rebase this? I have a test case prepared and would like to slap it on top of this PR, but it needs changes from main (and I'd like to avoid force pushing to your branch).
> > 
> > 
> > Done. It's always OK to force-push on my branch. I have my own backup.
> 
> Thank you!
> 
> With my somewhat limited DNS knowledge (and thanks to @evverx's reproducer), implemented a _very_ simple test DNS server (it might look like a lot of code, but that's just C), which allows us to twiddle with the packet a bit more. With it I was able to trigger the mentioned memory leaks and the assertion, as well as a couple of other issues - see the FIXMEs in the test script. It's a slightly more involved than a simple shell script, but on the other hand it uses (and hence tests) our code, so I think it's a net positive.
> 
> Also, to make it a bit easier to use during tests I hid it behind Knot using the `dnsproxy` module, so it doesn't require manually pointing tools to the test server.
> 
> Feel free to tweak it further as necessary.

Wow, super nice! Thank you!
I would like to address the FIXMEs, but some of them may be in another later PR.

**Comment by mrc0mmand** [comment]
> Wow, super nice! Thank you! I would like to address the FIXMEs, but some of them may be in another later PR.

That's perfectly fine, I just noted them down somewhere so I don't forget.

**Comment by yuwata** [comment]
Fixed all FIXMEs, but added one new FIXME. I'd really like to postpone that to another PR.

**Comment by yuwata** [comment]
Hmm,,, after re-considering, we should revert 9ca133e97a0c8795b1f293ccea4965b4ad1accc4. I do not have any good reason we should distinguish the two transaction failures.

**Comment by yuwata** [comment]
- `DNS_TRANSACTION_UPSTREAM_DNSSEC_FAILURE` is dropped, 
- and introduce DNSSEC_UPSTREAM_FAILURE is introduced,
- send EDE code and message in DBus error message, varlink reply, and io.systemd.Resolve.Monitor.
- also read EDE from cached packet,
- minor modernization to the new test,
- fixed all FIXMEs in @mrc0mmand's original code.

Please review, and test again. Thank you!

File: test/units/testsuite-75.sh [hunk 1]
```diff
@@ -552,6 +580,61 @@ grep -qF "fd00:dead:beef:cafe::123" "$RUN_OUT"
...
+journalctl -u systemd-resolved.service --cursor-file="$JOURNAL_CURSOR" --grep "Server returned error: SERVFAIL \(\d+\)"
+
+# SERVFAIL + invalid EDE code + extra text
+(! run resolvectl query edns-invalid-code-with-extra-text.forwarded.test)
+grep -qE "^edns-invalid-code-with-extra-text.forwarded.test:.+: SERVFAIL \([0-9]+: Hello \[#\]\\$%~ World\)" "$RUN_OUT"
+(! run varlinkctl call /run/systemd/resolve/io.systemd.Resolve io.systemd.Resolve.ResolveHostname '{"name" : "edns-invalid-code-with-extra-text.forwarded.test"}')
+grep -qF "io.systemd.Resolve.DNSError" "$RUN_OUT"
+grep -qE '{"rcode":2,"extendedDNSErrorCode":[0-9]+,"extendedDNSErrorMessage":"Hello \[#\]\$%~ World"}' "$RUN_OUT"
+journalctl --sync
+journalctl -u systemd-resolved.service --cursor-file="$JOURNAL_CURSOR" --grep "Server returned error: SERVFAIL \(\d+: Hello \[\#\]\\$%~ World\)"
```
Comment (yuwata) [inline test/units/testsuite-75.sh]: @mrc0mmand Could you check these three grep code for `Hello...`? I am not familiar with the difference between `journalctl --grep` and `grep -E`. And I have no idea why the two `grep -E` for `Hello...` need to be different. Huh...

**Comment by rpigott** [comment]
> Hmm,,, after re-considering, now I think we should revert https://github.com/systemd/systemd/commit/9ca133e97a0c8795b1f293ccea4965b4ad1accc4. I do not have any good reason we should distinguish the two transaction failures.

In the original patch I only used the presence of EDE codes to quash the feature detection behavior and didn't bother recording or reporting the upstream message. The new transaction result was introduced just to distinguish the logging behavior [1], but in the version that was merged we always parse this part of the packet anyway, so yeah there's no longer any need for this result.

[1] https://github.com/systemd/systemd/pull/30513#discussion_r1432432619

File: test/units/testsuite-75.sh (hunk 1 above)
Comment (mrc0mmand) [reply test/units/testsuite-75.sh]: `grep -E` uses POSIX.2 ERE (extended regular expressions) and `journalctl` uses PCRE (perl compatible reg. expr.), so the syntax between the two commands is different. If you'd tell grep to use PCREs, you could use the same expression as in `journalctl`'s case (sans one backslash, not sure why):

```
$ echo '{"rcode":2,"extendedDNSErrorCode":6,"extendedDNSErrorMessage":"Hello [#]$%~ World"}' | grep -P '{"rcode":2,"extendedDNSErrorCode":\d+,"extendedDNSErrorMessage":"Hello \[\#\]\$%~ World"}'
{"rcode":2,"extendedDNSErrorCode":6,"extendedDNSErrorMessage":"Hello [#]$%~ World"}
```

Comment (mrc0mmand) [reply test/units/testsuite-75.sh]: Ah, I see, in journalctl's case we use double quotes, so we need to double-escape `$`:

```
$ echo "\$"
$
$ echo "\\$"
\$
$ echo '\$'
\$
```

**Review by mrc0mmand — APPROVED** [review]
LGTM, thank you!

**Review by bluca — APPROVED** [review]
