### PR TITLE
Ignore BOM in config files

### LINKED ISSUE #2823: Chokes on byte-order-mark, misreports as "Assignment outside of section. Ignoring."
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229, git
### In case of bug report: Expected behaviour you didn't see

When reading a service file with byte order mark, system should either skip the BOM or emit a helpful error message.
### In case of bug report: Unexpected behaviour you saw

The warning is "[file:1] Assignment outside of section. Ignoring." This is especially unfortunate because the BOM is detected correctly by most editors, and thus becomes invisible to the user (which then complain, 'what assignment?').
### In case of bug report: Steps to reproduce the problem

```
echo -e '\uFEFF\n[Service]\nExecStart=/bin/true' > test.service
./systemd-analyze --user verify test.service
```

### PR DESCRIPTION
**Pull request by keszybz**
Fixes #2823 and removes an unnecessary `feof` call.

### CODE REVIEW

File: src/basic/utf8.h [hunk 1]
```diff
@@ -28,6 +28,7 @@
 #include "missing.h"
 
 #define UTF8_REPLACEMENT_CHARACTER "\xef\xbf\xbd"
+#define UTF8_BOM "\xef\xbb\xbf"
```
Comment (zonque) [inline src/basic/utf8.h]: Such acronyms leave room for confusion. Can we call this `UTF8_BYTE_ORDER_MARK` instead?

**Comment by keszybz** [comment]
Yeah, I was on the fence myself whether to use the acronym or not. Force pushed.
