### PR TITLE
network: recreate stacked netdevs when underlying device is re-added

### LINKED ISSUE #20430: [networkd] MACVLAN et. al. are not recreated when their link(s) are "repopulated"
**systemd version the issue has been seen with**
 > 249.3

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux ideapad 5.13.9-arch1-1 #1 SMP PREEMPT Sun, 08 Aug 2021 11:25:35 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**

A (physical) network interface could be removed and added again in the system due to various reasons. For example, I bumped into the issue because I'm using `iwd` for WiFi connection. Whenever `iwd` is (re)started, my wireless NIC is removed and added again for some reason. (I can see the interface index changed. Also, udev events.)

Regardless of whether the behavior is intentional and purposeful, I expect networkd to recreate MACVLAN and/or similar of the link that was gone and now appears again, as the "sub-interfaces" have gone as well.

I'm not sure if internally networkd is / can be aware of the "repopulation" of the links it manages, or it would only see them "going down" or lost their carrier (when that was not the full picture). However, I figure it can perhaps at least check whether e.g. the interface index or the "sub-interface list" of the link (if there's such a thing) has changed when the link is up again or so?

Now I'm working around the issue by replacing the MACVLAN (re)creation in networkd (i.e. the `.netdev` and `MACVLAN=` in the corresponding `.network`) with the following systemd service:

```
[Unit]
Description=macvlan iwd hack

[Service]
Type=oneshot
ExecStart=/usr/bin/ip l add macvl0 link wlan0 type macvlan mode passthru nopromisc

[Install]
WantedBy=sys-subsystem-net-devices-wlan0.device
```

Both `macvl0`and `wlan0` are still managed (i.e. `.network`) by networkd. Everything works as desired so far.

**Unexpected behaviour you saw**

 > MACVLAN and/or similar of a link will not be recreated when the link is removed and added again in the system.

**Steps to reproduce the problem**
 
 > Use networkd to create MACVLAN or similar on a link, then do whatever that could make the link go away and comes back again. See above.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #20430.

### CODE REVIEW

File: src/network/netdev/netdev.c [hunk 1]
```diff
@@ -167,6 +167,42 @@ bool netdev_is_managed(NetDev *netdev) {
...
 
+static bool netdev_is_stacked_and_independent(NetDev *netdev) {
+        assert(netdev);
+
+        if (!IN_SET(netdev_get_create_type(netdev), NETDEV_CREATE_STACKED, NETDEV_CREATE_AFTER_CONFIGURED))
+                return false;
+
+        switch (netdev->kind) {
+        case NETDEV_KIND_ERSPAN:
+                return ERSPAN(netdev)->independent;
```
Comment (poettering) [inline src/network/netdev/netdev.c:178]: maybe move the boolean to the generic part of the netdev? might be simpler than way and is just one bit

**Review by poettering — APPROVED** [review]
lgtm (but i must admit i don't grok the full implications)

File: src/network/netdev/netdev.c (hunk 1 above)
Comment (yuwata) [reply src/network/netdev/netdev.c:178]: I would like to work on that in later PR, and keep this now.
