### PR TITLE
systemctl-enable: warn if disabled/masked unit has active triggering units

### LINKED ISSUE #311: systemctl should warn if a unit is asked to be masked but not its triggering units, the same way as we warn if a unit is asked to be stopped but not its triggering units
When booting with kdbus enabled, I see the following as errors:

Jun 21 11:54:15 krejzi systemd[1]: org.freedesktop.NetworkManager.busname: Bus service dbus-org.freedesktop.NetworkManager.service not loaded, refusing.
Jun 21 11:54:15 krejzi systemd[1]: Failed to listen on DBUS1: org.freedesktop.NetworkManager.
Jun 21 11:54:15 krejzi systemd[1]: fi.epitest.hostap.WPASupplicant.busname: Bus service wpa_supplicant.service not loaded, refusing.
Jun 21 11:54:15 krejzi systemd[1]: Failed to listen on DBUS1: fi.epitest.hostap.WPASupplicant.
Jun 21 11:54:15 krejzi systemd[1]: org.freedesktop.ModemManager1.busname: Bus service dbus-org.freedesktop.ModemManager1.service not loaded, refusing.
Jun 21 11:54:15 krejzi systemd[1]: Failed to listen on DBUS1: org.freedesktop.ModemManager1.

These services are explicitly disabled through systemctl and can't even be dbus-activated until they are enabled by systemctl enable. dbus-daemon wouldn't spawn them, but would print a warning.

My issue is that systemd prints an error instead of warning when it can't load an explicitly disabled dbus service file. It would be nice to print a warning instead, since when an error is printed at boot, systemd starts outputting to screen at boot, breaking the "quiet" kernel option.

### PR DESCRIPTION
**Pull request by YHNdnzj**
Closes #311

### CODE REVIEW

**Comment by YHNdnzj** [comment]
Please backport the first commit.

File: src/systemctl/systemctl-enable.c [hunk 1]
```diff
@@ -61,6 +61,33 @@ static int normalize_names(char **names) {
         return 0;
 }
 
+static void warn_triggering_units_for_masked(sd_bus *bus, const char *unit) {
```
Comment (bluca) [inline src/systemctl/systemctl-enable.c]: this is almost identical to `warn_triggering_units_for_stopped()`, apart from the ignore_masked bool and the first word of the warning, so maybe just merge them and add a bool parameter?

**Review by bluca — APPROVED** [review]

File: src/systemctl/systemctl-enable.c [hunk 2]
```diff
@@ -267,7 +267,7 @@ int verb_enable(int argc, char *argv[], void *userdata) {
                 /* If some of the units are disabled in user scope but still enabled in global scope,
                  * we emit a warning for that. */
 
-                _cleanup_strv_free_ char **enabled_in_global_scope = NULL;
+                _cleanup_free_ char **enabled_in_global_scope = NULL;
```
Comment (poettering) [inline src/systemctl/systemctl-enable.c]: this is a bit icky, and given this is not performance critical here i'd avoid it. But if you must then please add a big fat comment about this, because this is irregular memory management, and people might see this later and assume it is a bug, even though it is not.

File: src/systemctl/systemctl-util.c [hunk 3]
```diff
@@ -315,26 +315,39 @@ int expand_unit_names(sd_bus *bus, char **names, const char* suffix, char ***ret
...
-                return 0;
+        if (ignore_masked) {
+                _cleanup_(lookup_paths_free) LookupPaths lp = {};
+
+                r = lookup_paths_init(&lp, arg_runtime_scope, 0, arg_root);
+                if (r < 0)
+                        return r;
 
-        dbus_path = unit_dbus_path_from_name(n);
+                r = unit_is_masked(bus, &lp, name);
```
Comment (poettering) [inline src/systemctl/systemctl-util.c]: we really should fix this one day, that this half-way does client-side lookups (in ase of template unit) and half-way server side (other cases).

i.e. unit_is_masked() should use the GetUnitFileState() call when dealing with templates, and look things up server side.

File: src/systemctl/systemctl-enable.c [hunk 4]
```diff
@@ -245,6 +245,10 @@ int verb_enable(int argc, char *argv[], void *userdata) {
                         if (r < 0)
                                 return r;
                 }
+
+                if (streq(verb, "mask") && !arg_quiet && !arg_no_warn)
```
Comment (poettering) [inline src/systemctl/systemctl-enable.c]: why do this only in case of masking? sounds worthy to warn in case of disabling too I think

Comment (poettering) [reply src/systemctl/systemctl-enable.c]: instead of checking the `verb` here again I think it would be nice to instead add a local variable here called `warn_trigger` or so that is set in the if/else blocks above in the cases where we want this warning to happen, i.e. for mask + disable at least. 

could even be named `warn_trigger_message` or so and be of type `const char*`, where you just put the string `"Masking"` or `"Disabling` in that you pass as third arg to `warn_triggering_units()`

File: src/systemctl/systemctl-util.c [hunk 5]
```diff
@@ -624,25 +624,14 @@ static int unit_find_template_path(
...
-                /* A template cannot be loaded, but it can be still masked, so
-                 * we need to use a different method. */
-
-                r = unit_file_find_path(lp, name, &path);
-                if (r < 0)
-                        return r;
-                if (r == 0)
-                        return false;
-                return null_or_empty_path(path);
-        }
```
Comment (poettering) [inline src/systemctl/systemctl-util.c:643]: you cannot just drop this part without replacement. if a unit template `foo@.service` is not passed here we'd try to find a loaded Unit by that name, but that does not exist, since that's a template name, and not instantiated.

Hence special casing for templates *is* necessary. My complaint was just that instead of using a client side lookup we should use the server side lookup via GetUnitFileState() which is the call that actually is fine with templates passed in.

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
excellent! thanks!
