### PR TITLE
tests: keep SYS_PTRACE when running under ASan

### LINKED ISSUE #10692: test-capability seems to be failing under ASan in fedora rawhide docker containers
Originally it was discovered in https://github.com/systemd/systemd/pull/10678#discussion_r231864751:
```
==5649==AddressSanitizer Init done
have ambient caps: yes
Capabilities:= cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read+eip
Capabilities:= cap_dac_override,cap_net_raw+ep
==5656==Could not attach to thread 5655 (errno 1).
==5656==Failed suspending threads.
==5655==LeakSanitizer has encountered a fatal error.
==5655==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==5655==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```
I temporarily added a kludge overwriting the test with a shell script simply exiting with 77.

### PR DESCRIPTION
**Pull request by mrc0mmand**
Address Sanitizer requires `SYS_PTRACE` capability, which is being dropped during `test-execute`. Even though this patch fixes the failing test phases, the reason why it fails in the first place, only in *some* environments, is still unclear.

cc @evverx 

Fixes #10692.

### CODE REVIEW

File: src/test/test-capability.c [hunk 1]
```diff
@@ -20,8 +20,13 @@
 static uid_t test_uid = -1;
 static gid_t test_gid = -1;
 
-/* We keep CAP_DAC_OVERRIDE to avoid errors with gcov when doing test coverage */
-static uint64_t test_flags = 1ULL << CAP_DAC_OVERRIDE;
+#ifdef __SANITIZE_ADDRESS__
+        /* Keep CAP_SYS_PTRACE when running under Address Sanitizer */
+        static uint64_t test_flags = 1ULL << CAP_SYS_PTRACE;
```
Comment (poettering) [inline src/test/test-capability.c]: we usually do not add an indentation level when using `#ifdef` (except sometimes for pre-processor expressions themselves). hence, please don't indent this here...

File: src/test/test-capability.c [hunk 2]
```diff
@@ -20,8 +20,13 @@
...
+#else
+        /* We keep CAP_DAC_OVERRIDE to avoid errors with gcov when doing test coverage */
+        static uint64_t test_flags = 1ULL << CAP_DAC_OVERRIDE;
```
Comment (poettering) [inline src/test/test-capability.c]: while you are at it, could you change `1ULL` → `UINT64_C(1)`, please? While this is effectively the same, it's a bit less sloppy since uint64_t is effectively identical to unsigned long long, but not theoretically...

Comment (poettering) [reply src/test/test-capability.c]: also, could you make this `const` please? this was missing for some reason, and should really be added.

File: src/test/test-capability.c (hunk 1 above)
Comment (mrc0mmand) [reply src/test/test-capability.c]: I knew there was something off with this formatting, thanks

File: src/test/test-capability.c (hunk 2 above)
Comment (mrc0mmand) [reply src/test/test-capability.c]: sure, fixed

File: src/test/test-capability.c (hunk 1 above)
Comment (evverx) [reply src/test/test-capability.c]: To judge from this and my failed attempt to run two jobs in parallel via the `.yml` file, It seems I have been having trouble indenting text this week :-) Thank you!
