### PR TITLE
systemctl: Add --wait option to wait until started units terminate again

### LINKED ISSUE #3830: systemctl: Wait for unit to become inactive
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

This came up on converting the desktop session to use (user) systemd. The "session leader" (defined in e. g. `/usr/share/xsessions/gnome.desktop` `Exec=` line) changes from `gnome-session [...]` to `systemctl start gnome-session.target; wait-for-unit gnome-session.target` (in practice it's a little more complicated, but that's the essential bit).

We currently use a downstream script for `wait-for-unit`, but this would make sense to generalize in `systemctl`. Initial proposal is to add a `wait` verb that gets a unit name. It subscribes to unit events and exits as soon as a unit's state becomes `inactive` (→ exit code 0) or `failed` (→ exit code 1), and prints the final state to stdout (unless `--quiet`) so that the caller can check for it without having to call `systemctl state` again.

This retains the possibility to add a `--state` option later, so that callers can wait for a different state. This is uninteresting for targets as they only have two states, but services have many more, and e. g. someone might want to `systemctl wait foo.mount --state mounted`. (This would not be part of the initial proposal though).

This has some similarities with #3726 -- that asks for an (indefinitively running) monitoring while I need to wait until a given state is reached; but the subscription/event watching code would be the same.

### PR DESCRIPTION
**Pull request by martinpitt**
Fixes #3830 

This is similar to the recently added `systemd-run --wait`, but for `systemctl`, i. e. for existing units.

~~TODO: The exit code isn't non-zero if one of the units fail (I think this would be the most useful semantics)~~ (_fixed in update_). This also does not print any info messages for now -- IMHO checking for the exit status is sufficient for most cases, and if you are interested in the "why" then `systemctl status` should tell you everything.

### CODE REVIEW

File: src/systemctl/systemctl.c [hunk 1]
```diff
@@ -2679,13 +2680,81 @@ static const char *method_to_verb(const char *method) {
...
+        r = sd_bus_message_enter_container(m, SD_BUS_TYPE_ARRAY, "{sv}");
+        if (r < 0)
+                return bus_log_parse_error(r);
+
+        while ((r = sd_bus_message_enter_container(m, SD_BUS_TYPE_DICT_ENTRY, "sv")) > 0) {
+                const char *s;
+                r = sd_bus_message_read(m, "s", &s);
+                if (r < 0)
+                        return bus_log_parse_error(r);
+                if (streq(s, "ActiveState")) {
```
Comment (fsateler) [inline src/systemctl/systemctl.c:2721]: This means that invoking `--wait` on a `RemainAfterExit=yes` unit will not return until `stop` is invoked on it. I think the documentation needs to be more explicit that it relates with systemd's concept of active-ness, rather with a naive "the unit terminates".

Comment (martinpitt) [reply src/systemctl/systemctl.c:2721]: Good point, I'll add that to the documentation. I think semantically it's correct to never stop then. (You would not acually use `--wait` with such units in practice).

**Comment by martinpitt** [comment]
Pushed an update:
- Exit status of systemctl is now 1 if any `--wait`'ed unit fails.
- Point out potential infinite waiting in manpage (often due to `RemainAfterExit`)
- Rebased to current master to include the recent udev memory allocation fix
- Extend the new test in `TEST-03-JOBS` to cover successful and failing cases.

File: man/systemctl.xml [hunk 2]
```diff
@@ -363,7 +363,21 @@
...
+      <varlistentry>
+        <term><option>--wait</option></term>
+
+        <listitem>
+          <para>Synchronously wait for started units to terminate again.
+          This option may not be combined with <option>--no-block</option>.
+          Note that this will wait forever if any given unit never terminates
+          (by itself or by getting stopped explicitly); particularly services
+          which use <literal>RemainAfterExit=yes</literal>.
+          .</para>
```
Comment (martinpitt) [inline man/systemctl.xml]: There is an extra '.' here. I fixed that in my local branch, but I didn't push yet to avoid re-running the whole CI just for that. I'll wait for some more review comments, I'm sure there are other things to change :-)

File: src/systemctl/systemctl.c [hunk 3]
```diff
@@ -2679,13 +2680,86 @@ static const char *method_to_verb(const char *method) {
        return "n/a";
 }
 
+typedef struct {
+    sd_bus_slot *match;
+    sd_event *event;
+    Set *unit_paths;
+    bool any_failed;
```
Comment (keszybz) [inline src/systemctl/systemctl.c]: The indentation is wrong here and below too.

**Comment by keszybz** [comment]
Looks very reasonable, apart from a few trivial style issues.

**Comment by martinpitt** [comment]
Indendation and duplicate '.' in manpage fixed, and rebased to current master.
