### PR TITLE
hwdb: several fixes for pointing stick

### LINKED ISSUE #25698: Udev modalias changed between version, old rules do not work
### systemd version the issue has been seen with

systemd-udev.x86_64 251.8-586.fc37

### Used distribution

Fedora 37

### Linux kernel version used

6.0.11-300.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

udev rule files

### Expected behaviour you didn't see

Trackpoint rule which worked in Fedora 35 systemd-udev-249.13-6.fc35.x86_64 stopped working.

### Unexpected behaviour you saw

After upgrading from Fedora 35 to Fedora 37, my following custom rule stopped working:

```
$ cat /etc/udev/hwdb.d/71-pointingstick-local.hwdb 
# Lenovo Thinkpad
evdev:name:TPPS/2 IBM TrackPoint:dmi:bvn*:bvr*:bd*:svnLENOVO:pn*:pvrThinkPad*:*
 POINTINGSTICK_SENSITIVITY=230
```

The sensitivity got the stock 128 value.

It seems that modalias has changed. New udev version now includes physical path and ev after the name and before "dmi" in modalias.
Adding the additional * after the name and before dmi make the rule work again:

````
evdev:name:TPPS/2 IBM TrackPoint:*:dmi:bvn*:bvr*:bd*:svnLENOVO:pn*:pvrThinkPad*:*
````

However, all the rules in [official hwdb, at least for trackpoints](https://github.com/systemd/systemd/blob/main/hwdb.d/70-pointingstick.hwdb), are still written in the old way. I suppose they are not applied as well.

### Steps to reproduce the problem

1. Install Fedora 37 with sysemd-udev 251.8-586
2. Write custom trackpoint rule based on official modalias in 70-pointingstick.hwdb
3. Do systemd-hwdb update
4. See that the rule is not applied, but was applied in systemd-udev-249.13-6

### Additional program output to the terminal or log subsystem illustrating the issue

`udevadm test` now include additional phys and ev fields.

```
value '[dmi/id]modalias' is 'dmi:bvnLENOVO:bvr8DET76WW(1.46):bd06/21/2018:br1.46:efr1.24:svnLENOVO:pn4286CTO:pvrThinkPadX220:rvnLENOVO:rn4286CTO:rvrNotAvailable:cvnLENOVO:ct10:cvrNotAvailable:sku:'
event4: 2 character(s) replaced
event4: /usr/lib/udev/rules.d/60-evdev.rules:18 Importing properties from results of builtin command 'hwdb 'evdev:name:TPPS/2 IBM TrackPoint:phys:isa0060/serio1/input0:ev:7:dmi:bvnLENOVO:bvr8DET76WW_1.46_:bd06/21/2018:br1.46:efr1.24:svnLENOVO:pn4286CTO:pvrThinkPadX220:rvnLENOVO:rn4286CTO:rvrNotAvailable:cvnLENOVO:ct10:cvrNotAvailable:sku:''
```

Full output is in attachment.
[event4_trackpoint.txt](https://github.com/systemd/systemd/files/10200094/event4_trackpoint.txt)

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by yuwata** [comment]
cc @jwrdegoede

File: hwdb.d/60-keyboard.hwdb [hunk 1]
```diff
@@ -28,12 +28,6 @@
 #    <vendor> and <product> are the firmware-provided strings
 #    exported by the kernel DMI modalias, see /sys/class/dmi/id/modalias
 #
-#  - Input driver device name and DMI data match:
```
Comment (jwrdegoede) [inline hwdb.d/60-keyboard.hwdb:31]: Why are you moving this documentation block around?

I see no reason for this change, please drop it.

File: hwdb.d/70-pointingstick.hwdb [hunk 2]
```diff
@@ -17,6 +17,15 @@
 #    The vendor, product and version ID for a device node "eventX" is listed
 #    in /sys/class/input/eventX/device/id.
 #
+#  - Extended input driver device name, properties and DMI data match:
```
Comment (jwrdegoede) [inline hwdb.d/70-pointingstick.hwdb:28]: You are not adding any new matches using this new format, so why add documentation for it here?

If you want to make sure all possible match formats are covered here, maybe just remove the existing docs and instead add some text pointing the user to the matches documentation in 60-keyboard.hwdb ?

This way you remove the duplication and avoid them getting out of sync in the future again. 

You could then also add the same text pointing to the matching docs to 60-evdev.hwdb which currently lacks this.

**Review by jwrdegoede — COMMENTED** [review]
Other then the few remarks about the doc changes which I have added this looks good to me, thank you.

File: hwdb.d/70-pointingstick.hwdb [hunk 3]
```diff
@@ -96,22 +96,27 @@ evdev:name:*[tT]rack[pP]oint*:dmi:bvn*
 
 # Latitude D620
 evdev:name:*DualPoint Stick:dmi:bvn*:bvr*:bd*:svnDellInc.:pnLatitudeD620*:*
+ ID_INPUT_POINTINGSTICK=1
```
Comment (keszybz) [inline hwdb.d/70-pointingstick.hwdb]: Hmm, but is this a good change? The docs say "In case multiple records match a given lookup string, the key-value pairs from all records are combined.". So unless that stopped being true, or there is some additional consideration, I think this change should be dropped.

File: hwdb.d/70-pointingstick.hwdb [hunk 4]
```diff
@@ -87,7 +87,7 @@
 ##########################################
 # Generic
 ##########################################
-evdev:name:*[tT]rack[pP]oint*:*
+evdev:name:*[tT]rack[pP]oint*:dmi:bvn*
```
Comment (keszybz) [inline hwdb.d/70-pointingstick.hwdb]: This also matches the extended format. `*:dmi` will cover both `:phys:<phys>:ev:<ev>:dmi` in the extended match, and `:dmi` in the non-extended match.

I don't understand how this fix is supposed to work. Properties are additive. IIUC (please correct me if I got something wrong): before 57bb707d48131f4daad2b1b746eab586eb66b4f3, we query the hwdb with three patterns, and after that, we query it with four patterns. The matches returned are summed, with later additions overriding.

Please explain.

File: hwdb.d/70-pointingstick.hwdb [hunk 5]
```diff
@@ -88,6 +88,7 @@
 # Generic
 ##########################################
 evdev:name:*[tT]rack[pP]oint*:dmi:bvn*
+evdev:name:*[dD]ual[pP]oint [sS]tick*:dmi:bvn*
```
Comment (keszybz) [inline hwdb.d/70-pointingstick.hwdb]: This looks good. It also obsoletes the previous commit?

**Review by keszybz — COMMENTED** [review]
I don't quite understand the issue, nor the fix.

File: hwdb.d/70-pointingstick.hwdb (hunk 4 above)
Comment (yuwata) [reply hwdb.d/70-pointingstick.hwdb]: Urrrrgh, indeed.

Comment (keszybz) [reply hwdb.d/70-pointingstick.hwdb]: > before [57bb707](https://github.com/systemd/systemd/commit/57bb707d48131f4daad2b1b746eab586eb66b4f3), we query the hwdb with three patterns, and after that, we query it with four patterns.

Oh, this is wrong. `60-evdev.rules` has `GOTO="evdev_end"` after each match attempt. So we don't actually match it with each of the patterns, but only until the first successful match.

**Comment by keszybz** [comment]
Please see #25713. If that goes in, I think we'll still want commits 1, 2, and 5 from this one.

File: hwdb.d/70-pointingstick.hwdb (hunk 2 above)
Comment (yuwata) [reply hwdb.d/70-pointingstick.hwdb:28]: > You are not adding any new matches using this new format, so why add documentation for it here?

Neither 60-evdev.hwdb nor 60-keyboard.hwdb has entry in extended format. I add the explanation for consistency and to provide for users how to modify the hwdb.

> If you want to make sure all possible match formats are covered here, maybe just remove the existing docs and instead add some text pointing the user to the matches documentation in 60-keyboard.hwdb ?
> This way you remove the duplication and avoid them getting out of sync in the future again.

That should also work. But currently we only have three files. Hence, I decided to copy the same explanation in these files. Then, each hwdb file becomes self-consistent.

> You could then also add the same text pointing to the matching docs to 60-evdev.hwdb which currently lacks this.

Done.

**Comment by yuwata** [comment]
@jwrdegoede and @keszybz Thank you for your comments. Updated. PTAL!

**Review by jwrdegoede — APPROVED** [review]
I am still not sure that duplicating the docs on the matches in 3 places is the best thing to do.

But I don't consider this a blocker and otherwise this looks good to me.

Feel free to merge this.

**Comment by yuwata** [comment]
@jwrdegoede Thank you for the review.

> I am still not sure that duplicating the docs on the matches in 3 places is the best thing to do.

@keszybz WDYT? Future maintainability vs self-consistency. I think the comment is mostly only the document about the formats (we have no man page nor online documents about the formats). Hence, I'd like to pick the self-consistency here. But, @jwrdegoede's comment also makes sense.

File: hwdb.d/60-evdev.hwdb [hunk 6]
```diff
@@ -1,11 +1,34 @@
...
-# Match string formats:
-# evdev:<modalias>
-# evdev:name:<device name>:dmi:<dmi string>
+# Supported hardware matches are:
+#  - Generic input devices match:
+#      evdev:input:bZZZZvYYYYpXXXXeWWWW-VVVV
+#    This matches on the kernel modalias of the input-device, mainly:
+#    ZZZZ is the bus-id (see /usr/include/linux/input.h BUS_*), YYYY, XXXX and
+#    WWWW are the 4-digit hex uppercase vendor, product and version ID and VVVV
+#    is an arbitrary length input-modalias describing the device capabilities.
```
Comment (keszybz) [inline hwdb.d/60-evdev.hwdb]: "arbitrary length" → "variable-length"

File: hwdb.d/60-evdev.hwdb [hunk 7]
```diff
@@ -1,11 +1,34 @@
...
+#    The vendor, product and version ID for a device node "eventX" is listed
+#    in /sys/class/input/eventX/device/id.
+#
+#  - Input driver device name and DMI data match:
+#      evdev:name:<input device name>:dmi:bvn*:bvr*:bd*:svn<vendor>:pn*
+#    <input device name> is the name device specified by the
+#    driver, <vendor> is the firmware-provided string exported
+#    by the kernel DMI modalias, see /sys/class/dmi/id/modalias
```
Comment (keszybz) [inline hwdb.d/60-evdev.hwdb]: Dot missing.

File: hwdb.d/60-evdev.hwdb [hunk 8]
```diff
@@ -1,11 +1,34 @@
...
+#
+#  - Extended input driver device name, properties and DMI data match:
+#      evdev:name:<input device name>:phys:<phys>:ev:<ev>:dmi:bvn*:bvr*:bd*:svn<vendor>:pn*
+#    <input device name> is the name device specified by the
+#    driver, <phys> is the physical-device-path, "cat
+#    /sys/class/input/input?/phys", <ev> is the event bitmask, "cat
+#    /sys/class/input/input?/capabilities/ev" and <vendor> is the
+#    firmware-provided string exported by the kernel DMI modalias,
+#    see /sys/class/dmi/id/modalias
```
Comment (keszybz) [inline hwdb.d/60-evdev.hwdb]: Ditto.

File: hwdb.d/70-pointingstick.hwdb [hunk 9]
```diff
@@ -23,13 +25,22 @@
...
 #    see /sys/class/dmi/id/modalias
 #
+#  - Extended input driver device name, properties and DMI data match:
+#      evdev:name:<input device name>:phys:<phys>:ev:<ev>:dmi:bvn*:bvr*:bd*:svn<vendor>:pn*
+#    <input device name> is the name device specified by the
+#    driver, <phys> is the physical-device-path, "cat
+#    /sys/class/input/input?/phys", <ev> is the event bitmask, "cat
+#    /sys/class/input/input?/capabilities/ev" and <vendor> is the
+#    firmware-provided string exported by the kernel DMI modalias,
+#    see /sys/class/dmi/id/modalias
```
Comment (keszybz) [inline hwdb.d/70-pointingstick.hwdb]: Ditto.

**Review by keszybz — COMMENTED** [review]
LGTM too.

I think it's fine to duplicate the description a few times. It's easier for the user. I don't think it's much of a maintenance chore to update all three, as long as they are all in sync, so one can just trivially paste the same change in three places.

**Review by bluca — APPROVED** [review]
