### PR TITLE
dhcp-server: also append specified additional options and vendor specific option on DHCP_OFFER

### LINKED ISSUE #15780: systemd-networkd DHCP Server ignores SendOptions
**systemd version the issue has been seen with**
245 (245.4-4ubuntu3)

**Used distribution**
VERSION="20.04 LTS (Focal Fossa)"

didn't work in Ubuntu 18.04 either

**Expected behaviour you didn't see**
If I config a DHCP server with systemd-networkd I want to add additional `SendOptions` to tell the client about PXE boot servers and files.

**Unexpected behaviour you saw**
However systemd-networkd ignores all these options and sends only implicit configured options like gateway/DNS etc. but none of the explicit defined `SendOptions`

**Steps to reproduce the problem**
***config files***
```/etc/systemd/network/10-pxe.link
[Match]
MACAddress=00:11:22:33:44:55

[Link]
Name=pxe
```

```/etc/systemd/network/10-lower.network
[Match]
Name=pxe

[Network]
Description="Client installation network with DHCP server and PXE boot"
DHCP=no
DHCPServer=yes
Address=10.23.23.254/24

[DHCPServer]
PoolOffset=100
PoolSize=25
SendOption=128:ipv4address:10.23.23.10
SendOption=67:string:ipxe.efi
```

***trying dhcp***
(Re-)start systemd-networkd and for example bridge an EFI VM to it which tries network boot.
TCP Dump on the systemd-networkd machine shows the following:

```
17:06:46.297872 IP (tos 0x0, ttl 64, id 51369, offset 0, flags [none], proto UDP (17), length 375)
    0.0.0.0.68 > 255.255.255.255.67: BOOTP/DHCP, Request from 52:54:00:f8:35:bc, length 347, xid 0x4a1d1716, Flags [Broadcast]
          Client-Ethernet-Address 52:54:00:f8:35:bc
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Discover
            MSZ Option 57, length 2: 1472
            Parameter-Request Option 55, length 35:
              Subnet-Mask, Time-Zone, Default-Gateway, Time-Server
              IEN-Name-Server, Domain-Name-Server, Hostname, BS
              Domain-Name, RP, EP, RSZ
              TTL, BR, YD, YS
              NTP, Vendor-Option, Requested-IP, Lease-Time
              Server-ID, RN, RB, Vendor-Class
              TFTP, BF, GUID, Option 128
              Option 129, Option 130, Option 131, Option 132
              Option 133, Option 134, Option 135
            GUID Option 97, length 17: 0.238.188.149.198.210.123.74.66.148.204.160.14.125.242.5.148
            NDI Option 94, length 3: 1.3.1
            ARCH Option 93, length 2: 7
            Vendor-Class Option 60, length 32: "PXEClient:Arch:00007:UNDI:003001"
17:06:46.298248 IP (tos 0xc0, ttl 64, id 55807, offset 0, flags [DF], proto UDP (17), length 296)
    10.23.23.254.67 > 255.255.255.255.68: BOOTP/DHCP, Reply, length 268, xid 0x4a1d1716, Flags [Broadcast]
          Your-IP 10.23.23.123
          Client-Ethernet-Address 52:54:00:f8:35:bc
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Offer
            Lease-Time Option 51, length 4: 3600
            Subnet-Mask Option 1, length 4: 255.255.255.0
            Default-Gateway Option 3, length 4: 10.23.23.254
            Server-ID Option 54, length 4: 10.23.23.254
```

As you can see the client asks for TFTP and some other PXE related options but the answer does not contain them.
I tried different clients (hardware networkcards, machines with BIOS/UEFI, VMs) the all keep asking for a while and then give up.

I also tried other options (eg. 128-135) and they are all ignored. The same applies to SendOption values within "

Any suggestions or help appreciated :-)

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #15780.

### CODE REVIEW

File: src/libsystemd-network/sd-dhcp-server.c [hunk 1]
```diff
@@ -548,13 +478,61 @@ static int server_send_ack(
                         return r;
         }
 
-        r = dhcp_server_send_packet(server, req, packet, DHCP_ACK, offset);
+        if (!is_offer) {
```
Comment (bluca) [inline src/libsystemd-network/sd-dhcp-server.c]: The order in which the options are appended is now different - I assume it doesn't really matter?

Comment (bluca) [reply src/libsystemd-network/sd-dhcp-server.c]: (ie: lease type and timezone were before extra/vendor specific options, now they are appended afterwards)

**Review by bluca — APPROVED** [review]
lgtm, just one minor question to clarify

File: src/libsystemd-network/sd-dhcp-server.c (hunk 1 above)
Comment (keszybz) [reply src/libsystemd-network/sd-dhcp-server.c]: It *should* not matter. But it'd be nicer to keep the original order, which was more logical. It should be enough to move this block up.

File: src/libsystemd-network/sd-dhcp-server.c [hunk 2]
```diff
@@ -548,13 +478,61 @@ static int server_send_ack(
...
+                be32_t address) {
+        return server_send_offer_or_ack(server, req, address, true);
+}
+
+static int server_send_ack(
+                sd_dhcp_server *server,
+                DHCPRequest *req,
+                be32_t address) {
+        return server_send_offer_or_ack(server, req, address, false);
+}
```
Comment (keszybz) [inline src/libsystemd-network/sd-dhcp-server.c]: Since it's all `static` and each one has exactly one caller, do we really need that? I think it'd be better to just adjust the two callers.

**Review by keszybz — CHANGES_REQUESTED** [review]

**Comment by grillo-parlante** [comment]
Manually applied this patch to 246.6 and it gets PXE/BOOTP working for me.  Thanks

**Comment by yuwata** [comment]
@bluca and @keszybz Thank you for your review. Updated. The above comments are addressed. PTAL.

@grillo-parlante Thank you for testing this PR!
