### PR TITLE
journal: do not trigger assertion when journal_file_close() get NULL

### LINKED ISSUE #12400: Failed to create new runtime journal: No such file or directory
**systemd version the issue has been seen with**
> 242

`/etc/systemd/journald.conf` in our packages. We changed the configuration from `Storage=volatile` to `Storage=auto`, rebuilt systemd 242, and did the things below.

    $ systemctl daemon-reexec
    $ systemctl restart systemd-journald

On some systems, this unexpectedly fails. Persistent storage was used on some of the systems, but it also happens, when deleting `/var/log/journal/*` before the systemd-journald restart. Subsequent starts work.

```
[6046091.633474] systemd[1]: Starting Journal Service...
[6046098.794504] systemd-journald[19688]: Failed to create new runtime journal: No such file or directory
[6046105.064762] systemd-journald[19688]: Assertion 'f' failed at ../source/src/journal/journal-file.c:343, function journal_file_close(). Aborting.
[6046105.077671] systemd[1]: systemd-journald.service: Main process exited, code=dumped, status=6/ABRT
[6046105.077827] systemd[1]: systemd-journald.service: Failed with result 'core-dump'.
[6046105.078663] systemd[1]: Failed to start Journal Service.
```

Unfortunately, we do not have the debug symbols easily available, but the trace below should point to the right direction.

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ff4a95e3cb1 in __GI_abort () at abort.c:79
#2  0x00007ff4a9c6c7ba in log_assert_failed_realm () from /lib/systemd/libsystemd-shared-242.so
#3  0x00007ff4a9d0f621 in journal_file_close () from /lib/systemd/libsystemd-shared-242.so
#4  0x000000000040d9df in server_flush_to_var ()
#5  0x0000000000406731 in main ()
```

`s->runtime_journal` seems to be NULL, when `journal_file_close()` is called.

https://github.com/systemd/systemd/blob/c5b7ae0edb4e32463b5326c973443a9bc6ae10e3/src/journal/journald-server.c#L1195-L1199

### PR DESCRIPTION
**Pull request by yuwata**
Closes #12400.

### CODE REVIEW

File: src/journal/journal-file.c [hunk 1]
```diff
@@ -340,7 +340,8 @@ bool journal_file_is_offlining(JournalFile *f) {
 }
 
 JournalFile* journal_file_close(JournalFile *f) {
-        assert(f);
+        if (!f)
+                return NULL;
```
Comment (keszybz) [inline src/journal/journal-file.c:344]: This change looks good. We generally expect destructors to not complain if a NULL argument is passed.

But please change the callsites which the check before calling `journal_file_close`, e.g. here:

https://github.com/systemd/systemd/blob/3f0d8b2dbd67fdbcf36895704b64381e3aecbaa7/src/journal/journald-server.c#L2235-L2239

**Comment by yuwata** [comment]
@keszybz Thank you for your review. Now I've dropped the redundant checks. And one more plus simplification related to `journal_file_close()` was added. PTAL.
