### PR TITLE
Fn+F5 fix for MSI Bravo 15-B5DX

### LINKED ISSUE #25782: MSI Bravo 15-B5DD - additional hwdb entry for micmute
### systemd version the issue has been seen with

252.3-1

### Used distribution

Arch Linux

### Linux kernel version used

6.0.12-zen1-1-zen

### CPU architectures issue was seen on

x86_64

### Component

systemd-hwdb

### Expected behaviour you didn't see

Pressing `Fn+F5` combination mutes the microphone

### Unexpected behaviour you saw

Pressing `Fn+F5` combination doesn't mute the microphone; `dmesg` logs an error about an unknown key being presesd.

### Steps to reproduce the problem

1. Launch system on an MSI Bravo 15-B5DX laptop
2. Press `Fn+F5`
3. Observe the lack of microphone status change

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[113881.503355] atkbd serio0: Unknown key pressed (translated set 2, code 0xf1 on isa0060/serio0).
[113881.503367] atkbd serio0: Use 'setkeycodes e071 <keycode>' to make it known.
```

### PR DESCRIPTION
**Pull request by noodlejetski**
fixes #25782

### CODE REVIEW

File: hwdb.d/60-keyboard.hwdb [hunk 1]
```diff
@@ -1435,6 +1435,10 @@ evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMicro-Star*:pn*Modern*:*
 evdev:name:MSI Laptop hotkeys:dmi:bvn*:bvr*:bd*:svn*:pnM[iI][cC][rR][oO]-S[tT][aA][rR]*:*
  KEYBOARD_KEY_0213=f22
  KEYBOARD_KEY_0214=f23
+
```
Comment (yuwata) [inline hwdb.d/60-keyboard.hwdb]: Please drop the space in this empty line.

**Review by yuwata — APPROVED** [review]
LGTM.
