### PR TITLE
journal: fixes issues reported by ASan

### LINKED ISSUE #9795: ASan seems to report a stack-overflow and a negative-size-param passed to memcpy in journald
Originally, I discovered the issues with a rudimentary fuzzer I wrote the other day when I was looking at https://github.com/systemd/systemd/pull/9346.
```sh
root@a313216d8826:/src/systemd# printf ' ' >space
root@a313216d8826:/src/systemd# /out/fuzz-journald space
INFO: Seed: 386302671
INFO: Loaded 2 modules   (39025 inline 8-bit counters): 37059 [0x7f07aaa818c0, 0x7f07aaa8a983), 1966 [0x9110c8, 0x911876),
INFO: Loaded 2 PC tables (39025 PCs): 37059 [0x7f07aaa8a988,0x7f07aab1b5b8), 1966 [0x911878,0x919358),
/out/fuzz-journald: Running 1 inputs 1 time(s) each.
Running: space
=================================================================
==25==ERROR: AddressSanitizer: negative-size-param: (size=-1)
    #0 0x4ee683 in __asan_memcpy /src/llvm/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cc:23
    #1 0x5538b4 in server_process_syslog_message /work/build/../../src/systemd/src/journal/journald-syslog.c:341:17
    #2 0x534242 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-journald.c:28:2
    #3 0x59ca22 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:580:15
    #4 0x574d4a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #5 0x580415 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:715:9
    #6 0x564c6c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #7 0x7f07a919182f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #8 0x420e38 in _start (/out/fuzz-journald+0x420e38)

0x6020000000d1 is located 1 bytes inside of 2-byte region [0x6020000000d0,0x6020000000d2)
allocated by thread T0 here:
    #0 0x4efb6f in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146
    #1 0x7f07aa37f5e4 in memdup_suffix0 /work/build/../../src/systemd/src/basic/alloc-util.c:30:15
    #2 0x534172 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-journald.c:23:13
    #3 0x59ca22 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:580:15
    #4 0x574d4a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #5 0x580415 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:715:9
    #6 0x564c6c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #7 0x7f07a919182f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: negative-size-param /src/llvm/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cc:23 in __asan_memcpy
```
```sh
root@a313216d8826:/src/systemd# printf '%100000s' >a-lot-of-spaces
root@a313216d8826:/src/systemd# /out/fuzz-journald a-lot-of-spaces
INFO: Seed: 465034066
INFO: Loaded 2 modules   (39025 inline 8-bit counters): 37059 [0x7fd7a15678c0, 0x7fd7a1570983), 1966 [0x9110c8, 0x911876),
INFO: Loaded 2 PC tables (39025 PCs): 37059 [0x7fd7a1570988,0x7fd7a16015b8), 1966 [0x911878,0x919358),
/out/fuzz-journald: Running 1 inputs 1 time(s) each.
Running: a-lot-of-spaces
AddressSanitizer:DEADLYSIGNAL
=================================================================
==28==ERROR: AddressSanitizer: stack-overflow on address 0x7ffd4589fed8 (pc 0x000000553874 bp 0x7ffd45887bc0 sp 0x7ffd4589fee0 T0)
    #0 0x553873 in server_process_syslog_message /work/build/../../src/systemd/src/journal/journald-syslog.c:340:27
    #1 0x534242 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-journald.c:28:2
    #2 0x59ca22 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:580:15
    #3 0x574d4a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #4 0x580415 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:715:9
    #5 0x564c6c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #6 0x7fd79fc7782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #7 0x420e38 in _start (/out/fuzz-journald+0x420e38)

SUMMARY: AddressSanitizer: stack-overflow /work/build/../../src/systemd/src/journal/journald-syslog.c:340:27 in server_process_syslog_message
==28==ABORTING
```
Both issues can be easily triggered by sending a space and a lot of spaces to `journald` via `/run/systemd/journal/dev-log` with `nc`. The backtrace looks like
```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/lib/systemd/systemd-journald'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fc01dde3b31 in __memmove_sse2_unaligned_erms () from /lib64/libc.so.6
#1  0x000055d062955942 in server_process_syslog_message (s=0x7fffd11c4170, buf=0x55d06469a470 " ", raw_len=1, ucred=0x7fffd11c3e90, tv=0x7fffd11c3e70, label=0x0, label_len=0)
    at ../src/journal/journald-syslog.c:341
#2  0x000055d06294c524 in server_process_datagram (es=0x55d0646943a0, fd=3, revents=1, userdata=0x7fffd11c4170) at ../src/journal/journald-server.c:1153
#3  0x00007fc01e6f384b in source_dispatch (s=0x55d0646943a0) at ../src/libsystemd/sd-event/sd-event.c:3101
#4  0x00007fc01e6f50ac in sd_event_dispatch (e=0x55d064693fd0) at ../src/libsystemd/sd-event/sd-event.c:3514
#5  0x00007fc01e6f555d in sd_event_run (e=0x55d064693fd0, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:3571
#6  0x000055d062942858 in main (argc=1, argv=0x7fffd11c4568) at ../src/journal/journald.c:92
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #9795, #9820, #9829, #9738 and #9757.

Not tested. @evverx Could you check this?

### CODE REVIEW

**Comment by evverx** [comment]
@yuwata thank you! I certainly can. I could also show how to build the fuzzer to see if the issues are gone, if you like.

I'm not sure about the last commit, where `newa` is replaced by `new` everywhere. I think it's totally fine to keep almost everything except for `msg` on the stack. In fact, if I recall correctly, it was also me who was opposed to allocating memory for `msg` with `new` because I assumed it'd slow down `journald` considerably, but it was in a little bit different context and I should probably refresh my memory before saying anything :-)

**Comment by evverx** [comment]
The heap-buffer-overflow is still there:
```sh
==18==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200001cd73 at pc 0x000000485c04 bp 0x7fffdc725630 sp 0x7fffdc724de0
READ of size 1 at 0x60200001cd73 thread T0
    #0 0x485c03 in __interceptor_strlen.part.33 /src/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:356
    #1 0x55457f in server_process_syslog_message /work/build/../../src/systemd/src/journal/journald-syslog.c:421:13
    #2 0x534242 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-journald.c:28:9
    #3 0x59caf2 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:580:15
    #4 0x59a8e7 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoop.cpp:486:3
    #5 0x59e8e2 in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:717:19
    #6 0x5a1876 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:848:5
    #7 0x581246 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:766:6
    #8 0x564d3c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #9 0x7f9ffa5ae82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #10 0x420e38 in _start (/out/fuzz-journald+0x420e38)

```
The segmentation fault is gone.

**Comment by yuwata** [comment]
Updated.
- Use `strjoin()` instead of `strjoina()` for `MESSAGE=` in journald-syslog.c
- Changes on journal-send.c are dropped.

**Comment by evverx** [comment]
I've just found another issue I reported at https://github.com/systemd/systemd/issues/9829. I'm wondering if this juggling with bytes is really necessary. Wouldn't it be better to simply not touch messages received via the syslog socket? Frankly, I'm not sure that stripping leading and trailing whitespaces helps anyone. The argument I heard regarding saving space is no longer valid with `SYSLOG_RAW` implemented.

@yuwata I'll take a look in an hour or so. Thank you.

**Comment by yuwata** [comment]
Fix for #9829 is added.

File: src/journal/journald-syslog.c [hunk 1]
```diff
@@ -397,24 +406,33 @@ void server_process_syslog_message(
...
                 iovec[n++] = IOVEC_MAKE(t, hlen + syslog_ts_len);
         }
 
-        a = strjoina("MESSAGE=", msg);
+        msg_msg = strjoin("MESSAGE=", msg);
+        if (!msg_msg) {
+                log_oom();
+                return;
+        }
         iovec[n++] = IOVEC_MAKE_STRING(a);
```
Comment (evverx) [inline src/journal/journald-syslog.c]: It seems that `msg_msg` should be here instead of `a`. Otherwise, it will crash with something like
```
=================================================================
==14==ERROR: AddressSanitizer: SEGV on unknown address 0x02007f528a5d (pc 0x000000485abe bp 0x7fffd4c29450 sp 0x7fffd4c28be0 T0)
==14==The signal is caused by a READ memory access.
    #0 0x485abd in AddressIsPoisoned /src/llvm/projects/compiler-rt/lib/asan/asan_mapping.h:387
    #1 0x485abd in QuickCheckForUnpoisonedRegion /src/llvm/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.h:32
    #2 0x485abd in __interceptor_strlen.part.33 /src/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:356
    #3 0x554596 in server_process_syslog_message /work/build/../../src/systemd/src/journal/journald-syslog.c:421:22
    #4 0x534242 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-journald.c:28:9
    #5 0x59c9e2 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:580:15
    #6 0x574d0a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #7 0x5803d5 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:715:9
    #8 0x564c2c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #9 0x7f6c5661782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #10 0x420e38 in _start (/out/fuzz-journald+0x420e38)

```

Comment (yuwata) [reply src/journal/journald-syslog.c]: Ouch!

Comment (yuwata) [reply src/journal/journald-syslog.c]: Fixed.

**Comment by yuwata** [comment]
Fixes for #9735 and #9757 are also added.

File: src/core/execute.c [hunk 2]
```diff
@@ -3216,7 +3216,7 @@ static int exec_child(
                 }
 
                 fds_with_exec_fd = newa(int, n_fds + 1);
-                memcpy(fds_with_exec_fd, fds, n_fds * sizeof(int));
+                memcpy_safe(fds_with_exec_fd, fds, n_fds * sizeof(int));
```
Comment (evverx) [inline src/core/execute.c:3219]: This one seems to fix https://github.com/systemd/systemd/issues/9738, not #9735.

**Comment by evverx** [comment]
The fuzzer still crashes on receiving the string "<13>Aug  4 04:08:03 something-is-about-to-go-wrong:":
```sh
==18==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000000f6 at pc 0x000000485c04 bp 0x7ffc343048b0 sp 0x7ffc34304060
READ of size 1 at 0x6020000000f6 thread T0
    #0 0x485c03 in __interceptor_strlen.part.33 /src/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:356
    #1 0x7f4c9057219c in strjoin_real /work/build/../../src/systemd/src/basic/string-util.c:227:29
    #2 0x554556 in server_process_syslog_message /work/build/../../src/systemd/src/journal/journald-syslog.c:416:19
    #3 0x534242 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-journald.c:28:9
    #4 0x59c9d2 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:580:15
    #5 0x574cfa in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #6 0x5803c5 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:715:9
    #7 0x564c1c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #8 0x7f4c8f2b582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #9 0x420e38 in _start (/out/fuzz-journald+0x420e38)

0x6020000000f6 is located 0 bytes to the right of 6-byte region [0x6020000000f0,0x6020000000f6)
allocated by thread T0 here:
    #0 0x4efb6f in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146
    #1 0x5538f6 in server_process_syslog_message /work/build/../../src/systemd/src/journal/journald-syslog.c:344:31
    #2 0x534242 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-journald.c:28:9
    #3 0x59c9d2 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:580:15
    #4 0x574cfa in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #5 0x5803c5 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:715:9
    #6 0x564c1c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #7 0x7f4c8f2b582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

```

**Comment by yuwata** [comment]
@evverx Thank you for testing this so many times. I've added several test cases for `syslog_parse_identifier()`. PTAL.

**Comment by evverx** [comment]
@yuwata not at all. The good news is that https://github.com/systemd/systemd/issues/9820 is finally gone. The bad news is that it wasn't the last issue. We have just gone a little bit further down the rabbit hole, so to speak. Now the fuzzer crashes as soon as it gets `<>`:
```
==26==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000000d3 at pc 0x7f31152ec024 bp 0x7fff88a8e290 sp 0x7fff88a8e288
READ of size 1 at 0x6020000000d3 thread T0
    #0 0x7f31152ec023 in syslog_parse_priority /work/build/../../src/systemd/src/basic/syslog-util.c:28:20
    #1 0x5539e4 in server_process_syslog_message /work/build/../../src/systemd/src/journal/journald-syslog.c:358:9
    #2 0x534242 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-journald.c:28:9
    #3 0x59c992 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:580:15
    #4 0x574cba in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #5 0x580385 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:715:9
    #6 0x564bdc in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #7 0x7f311402582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #8 0x420e38 in _start (/out/fuzz-journald+0x420e38)

0x6020000000d3 is located 0 bytes to the right of 3-byte region [0x6020000000d0,0x6020000000d3)
allocated by thread T0 here:
    #0 0x4efb6f in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146
    #1 0x7f3115213824 in memdup_suffix0 /work/build/../../src/systemd/src/basic/alloc-util.c:30:15
    #2 0x534172 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-journald.c:23:20
    #3 0x59c992 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:580:15
    #4 0x574cba in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #5 0x580385 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:715:9
    #6 0x564bdc in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #7 0x7f311402582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
```

**Comment by yuwata** [comment]
@evverx I hope `syslog_parse_priority()` is also fixed now.

File: src/journal/journald-syslog.c [hunk 3]
```diff
@@ -218,8 +218,8 @@ size_t syslog_parse_identifier(const char **buf, char **identifier, char **pid)
         if (t)
                 *identifier = t;
 
-        if (strchr(WHITESPACE, p[e]))
-                e++;
+        e += strspn(p + e, WHITESPACE);
```
Comment (evverx) [inline src/journal/journald-syslog.c:221]: Could it be that this change causes https://github.com/systemd/systemd/issues/9839?
