### PR TITLE
core/exec-invoke: relax restriction for process name length

### LINKED ISSUE #38367: `(uetoothd)` instead of `(bluetoothd)` logged in journal
### systemd version the issue has been seen with

257.7

### Used distribution

Debian sid/unstable

### Linux kernel version used

6.16.0-rc7-00140-gec2df4364666

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

Starting `bluetoothd` should result in `(bluetoothd)` in the journal.

### Unexpected behaviour you saw

```
$ journalctl -b
[…]
Jul 27 12:30:47 abreu sudo[3489]:  pmenzel : TTY=pts/4 ; PWD=/home/pmenzel ; USER=root ; COMMAND=/usr/bin/systemctl restart bluetooth
Jul 27 12:30:47 abreu sudo[3489]: pam_unix(sudo:session): session opened for user root(uid=0) by pmenzel(uid=5272)
Jul 27 12:30:47 abreu systemd[1]: Starting bluetooth.service - Bluetooth service...
Jul 27 12:30:47 abreu (uetoothd)[3496]: bluetooth.service: ConfigurationDirectory 'bluetooth' already exists but the mode is different. (File system: 755 ConfigurationDirectoryMode: 555)
Jul 27 12:30:47 abreu bluetoothd[3496]: Bluetooth daemon 5.82
Jul 27 12:30:47 abreu systemd[1]: Started bluetooth.service - Bluetooth service.
Jul 27 12:30:47 abreu bluetoothd[3496]: Starting SDP server
[…]
```

### Steps to reproduce the problem

Run `systemctl start bluetoothd` and check the journal.

@Vudentz’s comment from https://github.com/bluez/bluez/issues/1449:

> Are you sure this is something coming from bluetoothd though? This appears to be something else truncating the string, perhaps because openlog has not been called yet so systemd is not able to determine the binary name and just use the full path which is then truncated.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Previously, we limit the length of process name by 8. This relax the restriction then at least process comm or program_invocation_name contains the untrucated process name.

Closes #38367.

### CODE REVIEW

File: src/basic/argv-util.c [hunk 1]
```diff
@@ -183,29 +183,31 @@ int rename_process(const char name[]) {
...
 
         /* First step, change the comm field. The main thread's comm is identical to the process comm. This means we
          * can use PR_SET_NAME, which sets the thread name for the calling thread. */
-        if (prctl(PR_SET_NAME, name) < 0)
+        if (prctl(PR_SET_NAME, comm) < 0)
                 log_debug_errno(errno, "PR_SET_NAME failed: %m");
         if (l >= TASK_COMM_LEN) /* Linux userspace process names can be 15 chars at max */
                 truncated = true;
 
+        l = strlen(invocation);
```
Comment (poettering) [inline src/basic/argv-util.c:208]: i guess before we touch `invocation` we should check for non-null-ness, but probably just tape over it, and initialize it from `name` if NULL.

File: src/basic/argv-util.c [hunk 2]
```diff
@@ -172,7 +172,7 @@ static int update_argv(const char name[], size_t l) {
         return 0;
 }
 
-int rename_process(const char name[]) {
+int rename_process_full(const char *comm, const char *invocation) {
         bool truncated = false;
```
Comment (poettering) [inline src/basic/argv-util.c:176]: there should be an explanation here, what `invocation` is precisely used for

File: src/core/exec-invoke.c [hunk 3]
```diff
@@ -1489,35 +1489,23 @@ static int setup_pam(
...
 
-        /* This resulting string must fit in 10 chars (i.e. the length of "/sbin/init") to look pretty in
-         * /bin/ps */
-
-        if (path_extract_filename(path, &buf) < 0) {
-                rename_process("(...)");
-                return;
-        }
+        _cleanup_free_ char *buf = NULL;
+        if (path_extract_filename(path, &buf) < 0)
```
Comment (poettering) [inline src/core/exec-invoke.c]: maybe add debug logging if you touch this?

**Comment by yuwata** [comment]
@poettering Thank you for the review. All addressed. PTAL.
