### PR TITLE
networkd: configure link even if no routes have been received by dhcp

### LINKED ISSUE #3752: systemd-networkd can't configure interface if dhcp server does not provide routers
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 216, 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> yocto
### In case of bug report: Expected behaviour you didn't see

> networkctl status -a should show "routable (configured)" even if no routes have been received by dhcp server
### In case of bug report: Unexpected behaviour you saw

> systemd-networkd waits forever in state "routable (configuring)" when dhcp server does not provide routing information ("option routers") even if the interface got an valid ip address
### In case of bug report: Steps to reproduce the problem

> 1. configure a dhcp server to not send any routers (empty option routers)
> 2. try to get network "configured" via systemd-networkd
> 3. look at 'networkctl status -a'

### PR DESCRIPTION
**Pull request by ssahani**
Fixes #3752

~~~
 networkctl 
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 eth0             ether              no-carrier  configuring 
  5 host             ether              routable    configured <==========

5 links listed.

~~~

### CODE REVIEW

File: src/network/networkd-dhcp4.c [hunk 1]
```diff
@@ -138,10 +138,13 @@ static int link_set_dhcp_routes(Link *link) {
         }
 
         n = sd_dhcp_lease_get_routes(link->dhcp_lease, &static_routes);
-        if (n == -ENODATA)
-                return 0;
         if (n < 0)
-                return log_link_warning_errno(link, n, "DHCP error: could not get routes: %m");
+                log_link_warning_errno(link, n, "DHCP error: could not get routes: %m");
```
Comment (sitsofe) [inline src/network/networkd-dhcp4.c]: It's not really an error for DHCP not to send a route. It could be just interface is unroutable to the outside....

Comment (ssahani) [reply src/network/networkd-dhcp4.c]: This pr is about dhcp not sending any routes. So what I am missing here. It's waring message.

**Comment by ssahani** [comment]
I can't follow you sorry

**Comment by flo-wer** [comment]
He is referring to the title, it is meant to be "configure link", not "linke" or "linker".

File: src/network/networkd-dhcp4.c (hunk 1 above)
Comment (flo-wer) [reply src/network/networkd-dhcp4.c]: If sd_dhcp_lease_get_routes returns -ENODATA, this will still print an error. You have to exclude this case like above:
`if (n < 0 && n != -ENODATA)`

Comment (ssahani) [reply src/network/networkd-dhcp4.c]: I think we should log the warning message .

**Comment by ssahani** [comment]
Ohh fixed thanks :)

File: src/network/networkd-dhcp4.c (hunk 1 above)
Comment (andir) [reply src/network/networkd-dhcp4.c]: This comment is about this change and the one in line 90.

If I got the intend of this PR right this is about DHCP responses that do not carry a `ROUTER` attribute aka a default gateway.

IMHO logging this situation is definitely required. I am just unsure if `warning` is the right level here. `warning` causes me to think that there might be something wrong within `networkd` but it was able to continue vs this is a (valid) edge case that networkd did handle, but you might be wondering why there is no default route.

Wouldn't `log_link_info_errno` be better suited in that case? In any case the logged message could probably made more descriptive.

For the first message in Line 90 logging beased on one of the two return codes (-EINVAL, -ENODATA) could probably be something like
```C
switch (n) {
 case -ENODATA: log_info(…, "DHCP {nfo: No routes received from DHCP server: %m"); break ;
 case -EINVAL:
 default:
   log_{warrning,error}(…, "DHCP {warning|error}: could not get routes: %m"); break ;
}
```

I have had many frustrating hours with software that just logged errors like `Subsystem: error: ${errno}` where I had to start reading the source code to actually get why or what is going wrong. Getting this right in networkd would be awesome :-)

Comment (ssahani) [reply src/network/networkd-dhcp4.c]: I get your point . We should be more more informative about what actually going wrong . will update and please feel free to comment on these issues which help us debugging more user friendly. Thank you.

File: src/network/networkd-dhcp4.c [hunk 2]
```diff
@@ -94,8 +94,10 @@ static int link_set_dhcp_routes(Link *link) {
                 return log_link_warning_errno(link, r, "DHCP error: could not get address: %m");
 
         r = sd_dhcp_lease_get_router(link->dhcp_lease, &gateway);
-        if (r < 0 && r != -ENODATA)
-                return log_link_warning_errno(link, r, "DHCP error: could not get gateway: %m");
+        if (r == -ENODATA)
+                log_link_info(link, "DHCP: No routes received from DHCP server: %m");
+        else
```
Comment (yuwata) [inline src/network/networkd-dhcp4.c]: Should be `else if (r < 0)` here? With this PR, I got
```
wlp2s0: DHCP error: could not get gateway: Success
```

Comment (ssahani) [reply src/network/networkd-dhcp4.c]: Yes right . updated. thanks !

Comment (yuwata) [reply src/network/networkd-dhcp4.c]: Updated commit fixes my point. Thanks.

File: src/network/networkd-dhcp4.c (hunk 1 above)
Comment (yuwata) [reply src/network/networkd-dhcp4.c]: Yeah, if the function returns `-ENODATA`, we should show messages at most in info level, I think. What do you think about applying the logic similar to one for `sd_dhcp_lease_get_router()`?

Comment (ssahani) [reply src/network/networkd-dhcp4.c]: No this not a normal case we don't know the routes. That means it is not routble. Info is just a information we can ignore. I don't think we can ignore this.

Comment (yuwata) [reply src/network/networkd-dhcp4.c]: Hmm, I may misunderstand the code or what the routes here are. But on my laptop, I got
```
wlp2s0: DHCP error: could not get routes: No data available
```
however I can connect internet. I thought that even if we do not get routes from DHCP, getting default gateway is sufficient to connect outside. Is it correct, or not?

Comment (ssahani) [reply src/network/networkd-dhcp4.c]: Yes that is correct. But we can't really keep the log in info level.

Comment (sitsofe) [reply src/network/networkd-dhcp4.c]: Perhaps "DHCP server did not provide any additional routes" would be a nicer message...

Comment (yuwata) [reply src/network/networkd-dhcp4.c]: @ssahani Then, I still do not understand why you stick to warn here. I think we should warn if DHCP server do not provide either default gateway or additional routes. What do you think about the following?
```
if (n == -ENODATA)
    log_link_info(link, "DHCP: No routes received from DHCP server: %m");
else if (n < 0)
    log_link_warning_errno(link, n, "DHCP error: could not get routes: %m");
if (r < 0 && n < 0)
    log_link_warning(link, "DHCP error: No routes received from DHCP server: %m");
```

Comment (ssahani) [reply src/network/networkd-dhcp4.c]: Agree this is more informative. When the asset fails for get_router we should warn.

**Comment by yuwata** [comment]
Thanks. lgtm.

File: src/network/networkd-dhcp4.c [hunk 3]
```diff
@@ -147,9 +149,17 @@ static int link_set_dhcp_routes(Link *link) {
...
         n = sd_dhcp_lease_get_routes(link->dhcp_lease, &static_routes);
         if (n == -ENODATA)
-                return 0;
-        if (n < 0)
-                return log_link_warning_errno(link, n, "DHCP error: could not get routes: %m");
+                log_link_info(link, "DHCP: No routes received from DHCP server: %m");
+        else if (n < 0)
+                log_link_warning_errno(link, n, "DHCP error: could not get routes: %m");
+
+        if (n < 0 && r < 0) {
```
Comment (poettering) [inline src/network/networkd-dhcp4.c]: hmm, i really don't like that you check r here, after all it has possibly been updated in the mean time with lots of other values since it was set to -ENODATA because no routes were discovered.

Why not just use the the test "link->dhcp4_messages == 0" here instead? that's a much more correct and explicit test under the same conditions, or am I wrong?

File: src/network/networkd-dhcp4.c [hunk 4]
```diff
@@ -147,9 +149,17 @@ static int link_set_dhcp_routes(Link *link) {
...
+
+                log_link_warning(link, "DHCP error: No routes received from DHCP server: %m");
+
+                link->dhcp4_configured = true;
+                link_check_ready(link);
+        }
```
Comment (poettering) [inline src/network/networkd-dhcp4.c]: so, even though it's not strictly necessary either you should do "return 0" here i figure, or just move the whole block to the end of the function... otherwise it's weird, if you still go through the loop even though you already decided its unnecessary...

or am i missing something here?

Comment (ssahani) [reply src/network/networkd-dhcp4.c]: Ok done

File: src/network/networkd-dhcp4.c (hunk 3 above)
Comment (ssahani) [reply src/network/networkd-dhcp4.c]: yes that is much cleaner. thanks !

**Comment by ssahani** [comment]
updated
