### PR TITLE
test-env-util: fix typo leading to memleak

### LINKED ISSUE #5405: test-env-util, test-fileio: LeakSanitizer: detected memory leaks
https://github.com/systemd/systemd/pull/5131#issuecomment-281314198
```
FAIL: test-env-util
===================


=================================================================
==17489==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fd06fa1de60 in malloc (/lib64/libasan.so.3+0xc6e60)
    #1 0x7fd06ef1c5ec in malloc_multiply src/basic/alloc-util.h:70
    #2 0x7fd06ef1dc76 in strnappend src/basic/string-util.c:206
    #3 0x7fd06ef7efb0 in replace_env_n src/basic/env-util.c:694
    #4 0x55a386b954a7 in replace_env src/basic/env-util.h:42
    #5 0x55a386b978ba in test_replace_env src/test/test-env-util.c:160
    #6 0x55a386b99b24 in main src/test/test-env-util.c:324
    #7 0x7fd06d7e5400 in __libc_start_main (/lib64/libc.so.6+0x20400)

Direct leak of 9 byte(s) in 1 object(s) allocated from:
    #0 0x7fd06fa1de60 in malloc (/lib64/libasan.so.3+0xc6e60)
    #1 0x7fd06ef1c5ec in malloc_multiply src/basic/alloc-util.h:70
    #2 0x7fd06ef1dc76 in strnappend src/basic/string-util.c:206
    #3 0x7fd06ef7efb0 in replace_env_n src/basic/env-util.c:694
    #4 0x55a386b954a7 in replace_env src/basic/env-util.h:42
    #5 0x55a386b978ba in test_replace_env src/test/test-env-util.c:160
    #6 0x55a386b99b2e in main src/test/test-env-util.c:325
    #7 0x7fd06d7e5400 in __libc_start_main (/lib64/libc.so.6+0x20400)

SUMMARY: AddressSanitizer: 25 byte(s) leaked in 2 allocation(s).
FAIL test-env-util (exit status: 1)
FAIL: test-fileio
=================
...
==18689==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f181a73e210 in realloc (/lib64/libasan.so.3+0xc7210)
    #1 0x7f1819d20c23 in greedy_realloc src/basic/alloc-util.c:57
    #2 0x7f1819cd7431 in parse_env_file_internal src/basic/fileio.c:415
    #3 0x7f1819cd93ae in merge_env_file src/basic/fileio.c:807
    #4 0x5634db7dc370 in test_merge_env_file_invalid src/test/test-fileio.c:308
    #5 0x5634db7e0af8 in main src/test/test-fileio.c:674
    #6 0x7f1818505400 in __libc_start_main (/lib64/libc.so.6+0x20400)

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).
FAIL test-fileio (exit status: 1)
```

### PR DESCRIPTION
**Pull request by keszybz**
Fixes #5405.

### CODE REVIEW

**Comment by keszybz** [comment]
It does fix one leak. I'll dig further ;)

**Comment by evverx** [comment]
@keszybz , sure.
Actually, I mean LGTM (except `Fixes #5405`)

**Comment by keszybz** [comment]
I think it's good now.

File: src/basic/fileio.c [hunk 1]
```diff
@@ -780,6 +781,7 @@ static int merge_env_file_push(
 
         if (!env_name_is_valid(key)) {
                 log_error("%s:%u: invalid variable name \"%s\", ignoring.", strna(filename), line, key);
+                free(value);
```
Comment (evverx) [inline src/basic/fileio.c:784]: The leak has gone. But it's hard to track `value`. Shouldn't we `free(value)` in `parse_env_file_internal`?

Comment (keszybz) [reply src/basic/fileio.c:784]: This function "consumes" value on success. Skipping the value is a success. To handle it specially would require passing the information back to parse_env_file_internal that it's not really a success, so it could free `value`. This would be more core and more brittleness. Current cure *is* quite simple, I just forgot to take care of `value` in this one case.

Comment (evverx) [reply src/basic/fileio.c:784]: @keszybz , ok

Unrelated to this PR. I've added BOM
```diff
diff --git a/src/test/test-fileio.c b/src/test/test-fileio.c
index b1d688c..e8a2410 100644
--- a/src/test/test-fileio.c
+++ b/src/test/test-fileio.c
@@ -55,7 +55,7 @@ static void test_parse_env_file(void) {
         f = fdopen(fd, "w");
         assert_se(f);

-        fputs("one=BAR   \n"
+        fputs("\xef\xbb\xbfone=BAR   \n"
               "# comment\n"
               " # comment \n"
               " ; comment \n"
```
And test fails with
```
Assertion 'streq_ptr(a[0], "one=BAR")' failed at src/test/test-fileio.c:87, function test_parse_env_file(). Aborting.
```
Does it matter?

Comment (evverx) [reply src/basic/fileio.c:784]: Actually, I didn't read https://github.com/systemd/systemd/pull/5131 So, I don't fully understand what does this code do :-)

Comment (keszybz) [reply src/basic/fileio.c:784]: We have no support for skipping BOMs afaik, and parse_env_file does not validate variable name validity, so you end up with an entry called "<BOM>one". We probably should detect this better, but that's unrelated to my PR.

Comment (poettering) [reply src/basic/fileio.c:784]: BOMs are a gruesome concept I must say, I am not sure we should really care too much about them...

Comment (evverx) [reply src/basic/fileio.c:784]: Well, we ignore BOM sometimes: https://github.com/systemd/systemd/pull/2883
