### PR TITLE
cryptsetup: Treat key file errors as a failed password attempt

### LINKED ISSUE #11723: v241 has issues with /home encrypted
**systemd version the issue has been seen with**
> v241

**Used distribution**
 > Manjaro Linux KDE 18.0.3-pre2

**Expected behaviour you didn't see**
 > unencrypted `/home` partition

**Unexpected behaviour you saw**
 > manjaro-kde systemd-cryptsetup[269]: Failed to open key file.
manjaro-kde systemd-cryptsetup[269]: Failed to activate with the key file '/crypto_keyfile.bin' : Invalid argument
manjaro-kde systemd[1]: Failed to start Cryptography Setup for luks-[UUID]

**Steps to reproduce the problem**

Installed a KDE VM system using [latest development ISO](https://osdn.net/projects/manjaro/storage/kde/18.0.3-pre2/), manually partitioned with efi boot partition, root partition and separate encrypted home partition.

Reported on Manjaro forum:

https://forum.manjaro.org/t/75655/26
https://forum.manjaro.org/t/75711

Issue is most likely introduced via [23th Jan changes](https://github.com/systemd/systemd/compare/v241-rc1...v241-rc2) to cryptsetup.

### PR DESCRIPTION
**Pull request by refi64**
6f177c7dc092eb68762b4533d41b14244adb2a73 caused key file errors to immediately fail, which would make it hard to correct an issue due to e.g. a crypttab typo or a damaged key file.

Closes #11723.

### CODE REVIEW

File: src/cryptsetup/cryptsetup.c [hunk 1]
```diff
@@ -710,7 +710,8 @@ static int run(int argc, char *argv[]) {
                                                          flags);
                         if (r >= 0)
                                 break;
-                        if (r != -EAGAIN)
+                        /* Avoid immediately failing due to key file issues */
+                        if (r != -EAGAIN && !key_file)
```
Comment (poettering) [inline src/cryptsetup/cryptsetup.c]: Hmm, I think it would be better to change attach_luks_or_plain() instead. It has the `crypt_activate_by_keyfile_offset()` in the middle, that is used when a key_file path is supplied. When it returns we turn EPERM into EAGAIN right now with a friendly log msg. I think it we should add another if check right there, that turns EINVAL into EAGAIN too with a different, appropriate error msg. EINVAL is after all the (awfully generic) error libcryptsetup returns if the keyfile doesn't exist. 

Or in other words: I think we should handle this error as early as possible, with a friendly log msgs, instead of doing so after it already propagated further through our stack losing its context.

The error msg should probably suggest what the context of all of is this i.e. `Failed to activate with key file '%s'. (Key file missing?)` or so. (since EINVAL is so generic we can only guess, hence the question in the end.

**Comment by kirbyfan64** [comment]
@poettering Done.

**Comment by poettering** [comment]
lgtm! thanks!

**Comment by blackjackshellac** [comment]
This was driving me nuts in Fedora 30.  As a workaround, you can change the /etc filesystem luks password to "none" in /etc/crypttab (assuming luks-key files are under /etc).  Something like,

```
luks-abcde UUID=abcde none luks
```
