### PR TITLE
process-util: handle double NUL as the end of command line

### LINKED ISSUE #21186: systemctl status interprets null terminators in cmdline as arguments
**systemd version the issue has been seen with**

```
$ systemd --version
systemd 249 (249.4-1-cloudflare-2021.9.0)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP -LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

**Used distribution**

Debian Buster

**Linux kernel version used** (`uname -a`)

```
$ uname -a
Linux 131m1 5.10.75-cloudflare-kasan-2021.10.5 #1 SMP Mon Sep 27 00:00:00 UTC 2010 x86_64 GNU/Linux
````

**CPU architecture issue was seen on**

x86_64

**Expected behaviour you didn't see**

The output of `systemctl status` matches arguments / intended cmdline

**Unexpected behaviour you saw**

The output has extra empty quoted arguments

**Steps to reproduce the problem**

Running nginx with a bunch of workers seems to do it.

**Additional program output to the terminal or log subsystem illustrating the issue**

The issue seem to have started after the following PR, which landed in v249:

* https://github.com/systemd/systemd/pull/18863

Example `systemctl status` output for an nginx on my system:

```
             ├─476904 "nginx: master process /usr/local/nginx-fl/sbin/nginx-fl"
             ├─476955 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─476956 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─476957 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─476958 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─476959 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─476961 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─476970 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─476975 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─476984 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─476992 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─476994 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─476999 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─477004 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─477014 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─477019 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─477024 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─477028 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─477034 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─477038 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
             └─477044 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" ""
```

In the parent process:

```
$ cat /proc/476904/cmdline | hexdump -C
00000000  6e 67 69 6e 78 3a 20 6d  61 73 74 65 72 20 70 72  |nginx: master pr|
00000010  6f 63 65 73 73 20 2f 75  73 72 2f 6c 6f 63 61 6c  |ocess /usr/local|
00000020  2f 6e 67 69 6e 78 2d 66  6c 2f 73 62 69 6e 2f 6e  |/nginx-fl/sbin/n|
00000030  67 69 6e 78 2d 66 6c 00                           |ginx-fl.|
00000038
```

In a child:

```
ivan@131m1:~$ cat /proc/476957/cmdline | hexdump -C
00000000  6e 67 69 6e 78 3a 20 77  6f 72 6b 65 72 20 70 72  |nginx: worker pr|
00000010  6f 63 65 73 73 00 00 00  00 00 00 00 00 00 00 00  |ocess...........|
00000020  00 00                                             |..|
00000022
```

From https://man7.org/linux/man-pages/man5/proc.5.html it sounds like the correct way of interpreting double null bytes is as a string terminator, so systemd needs to be fixed.

```
       /proc/[pid]/cmdline
              This read-only file holds the complete command line for
              the process, unless the process is a zombie.  In the
              latter case, there is nothing in this file: that is, a
              read on this file will return 0 characters.  The command-
              line arguments appear in this file as a set of strings
              separated by null bytes ('\0'), with a further null byte
              after the last string.
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #21186.

### CODE REVIEW

**Comment by bobrik** [comment]
I tested on my system and both services that had issues before look good now.

File: src/basic/process-util.c [hunk 1]
```diff
@@ -140,14 +139,10 @@ static int get_process_cmdline_nulstr(
...
-         * data.
-         *
-         * Returns an error, 0 if output was read but is truncated, 1 otherwise.
-         */
+         * data. */
 
         p = procfs_file_alloca(pid, "cmdline");
-        r = read_virtual_file(p, max_size, &t, &k); /* Let's assume that each input byte results in >= 1
-                                                     * columns of output. We ignore zero-width codepoints. */
+        r = read_virtual_file(p, SIZE_MAX, &t, &k);
```
Comment (keszybz) [inline src/basic/process-util.c]: I don't think this is a good idea. This effectively disables the size limit, which means that we can read (and parse) megabytes of data here. If the data is full of short sequences, this will lead to a fairly significant "allocation amplification" when we split this in individual strings. This function is called in places that lists processes, also for untrusted processes, so I think it should be more careful.

File: src/basic/process-util.c [hunk 2]
```diff
@@ -161,30 +156,36 @@ static int get_process_cmdline_nulstr(
...
 
-                k = strlen(t);
-                r = k <= max_size;
-                if (r == 0) /* truncation */
-                        t[max_size] = '\0';
+                t[0] = '[';
+                memcpy(t + 1, comm, len);
+                t[len + 1] = ']';
+                t[len + 2] = '\0';
+                t[len + 3] = '\0';
```
Comment (poettering) [inline src/basic/process-util.c]: idea:

```c
memcpy(t + 1 + len, (const char[]) { ']', 0, 0 }), 3);
```

**Comment by poettering** [comment]
I think there's an ambiguity here: if you invoke a command line like this:

```
/bin/echo "" "" "" ""
```

Then you can't distinguish it from a command line like this:

```
/bin/echo
```

if one reads the man page as the reporter (@bobrik) of #21186 reads it. i.e. this blurb:

> The  command-line arguments appear in this file as a set of strings separated by null bytes ('\0'), with a further null byte after the last string.

@bobrik reads it as if the only case when two NUL bytes appear in the buffer it means end of the string, but I think it doesn't actually mean that, it just literally means: "whatever, there's an extra NUL byte at the end", i.e. that there can be any number of sequential NUL bytes, but the last one is extra, and shoul dnot be shown.

Now, the way we currently show command lines with trailing NUL bytes is indeed confusing and weird. We probably shouldn#t do this. The problem is caused by various daemons (including some of our own) which change their cmdline after start-up to show some basic status info in "ps". Since they can't change the size of the cmdline buffer they fill it with a lot of zeroes at the end, which the only *correct* way to interpret is that they have a lot of empty string arguments at the end, which we currently do. But "correct" and "reality" sometimes are in conflict hence I think we should accept that daemons do what they do and hence simply drop all trailing empty strings from the argument lists we read from /proc/$PID/cmdline. This then means any invocation of `/bin/echo ""` will be shown as `/bin/echo`, but I think I can live with that, we mostly do this for presentation purposes anyway.

(In an ideal world everyone would use PR_SET_MM_ARG_END to adjust the array length, but given that is a privileged call I think it's unrealistic to expect)

**Comment by poettering** [comment]
Uh, for forgot to make the point I was trying to make though: which is that there should be an appropriate comment in the code that explains that we knowingly misinterpret `/bin/echo ""` as `/bin/echo`, because of the daemons which rename their processes.

**Comment by keszybz** [comment]
> This then means any invocation of `/bin/echo ""` will be shown as `/bin/echo`

Is it?  I think we have two conflicting cases: a daemon which shortened it's cmdline, and processes with empty arguments. *Because* we opt to show the second one correctly, we show the first one incorrectly.

E.g. I see this:
```console
$ bash -c 'sleep 100 && echo OK' -c '' &
$ systemctl status $$ | grep bash
             ├─26723 bash -c "sleep 100 && echo OK" -c ""
```

**Comment by poettering** [comment]
That's exactly what I wanted to say. So far we opted to show all trailing empty elements.  This patch suppresses them. There are good arguments for both cases, but I am leaning towards what "ps" does, i.e. suppress them.

**Comment by poettering** [comment]
another idea: make it controllable by a flag. i figure we'd pass that flag in all current invocations, so one might consider it redundant, but I don't think it would be, because it's formalized documenttion if you so will, i.e.

```c
r = get_process_cmdline(…, PROCESS_CMDLINE_SUPPRESS_TRAILING_EMPTY);
```

I think makes very clear that we are doing some suppressing of information here.

Given we have a flags parameter anyway to me this appears to be the way to do.

**Comment by keszybz** [comment]
I think the flag would make sense if it was controllable by the user, e.g. through a command-line option. But I don't think we want to expose this… And adding a flag (and two implementations!) just a means of documenting this internally doesn't seem like the right approach.

**Comment by poettering** [comment]
> I think the flag would make sense if it was controllable by the user, e.g. through a command-line option. But I don't think we want to expose this… And adding a flag (and two implementations!) just a means of documenting this internally doesn't seem like the right approach.

two implementations?

I mean, it's one conditionalizing some extra processing after we are done, that's all. i.e. the loops that drop the "empty suffix".

**Comment by yuwata** [comment]
@keszybz and @poettering Sorry for late response. Updated. Addresses @keszybz's request, and truncation is applied again.
The new flag `PROCESS_CMDLINE_SUPPRESS_TRAILING_EMPTY`, which is suggested by @poettering, is not added in this PR, and the empty strings are always dropped from the result. As I could not find any places we should disable that feature.
Let's add that flag later when we find a place we should keep the trailing empty strings.

PTAL.

**Comment by keszybz** [comment]
LGTM.
