### PR TITLE
wait-online: fix handling of unmanaged state

### LINKED ISSUE #22246: [systemd-networkd] RequiredFamilyForOnline does not appear to be working
**systemd version the issue has been seen with**
 > systemd 250 (250.3-1-manjaro)

**Used distribution**
 > Manjaro

**Linux kernel version used** (`uname -a`)
 > Linux AIO 5.15.16-1-ACS-MANJARO #1 SMP PREEMPT Mon Jan 24 23:05:33 CST 2022 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > The RequiredFamilyForOnline parameter works

**Unexpected behaviour you saw**
 > RequiredFamilyForOnline does not seem to work.

**Steps to reproduce the problem**
```
cat /etc/systemd/network/10-sr-iov.link
[Match]
OriginalName=enp7s0f2

[SR-IOV]
VirtualFunction=2
```
```
cat /etc/systemd/network/br0_bind.network
[Match]
Name=enp*s0

[Link]
MTUBytes=9000

[Network]
Bridge=br0
```
```
cat /etc/systemd/network/br0.netdev
[NetDev]
Name=br0
Kind=bridge
```
```
cat /etc/systemd/network/br0.network
[Match]
Name=br0

[Network]
DHCP=yes
MulticastDNS=true
IPv6Token=prefixstable
IPv6PrivacyExtensions=prefer-public

[Link]
RequiredForOnline=yes
RequiredFamilyForOnline=ipv4
```
```
cat /usr/lib/systemd/system/test.service 
[Unit]
Description=nettest
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/bin/sh -c 'networkctl status br0 > /var/log/test.log'
KillMode=process

[Install]
WantedBy=multi-user.target
```
```
cat /var/log/test.log                   
● 3: br0                        
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/br0.network
                          Type: bridge
                         State: routable (configured)
                  Online state: offline
                        Driver: bridge
              Hardware Address: 12:53:9f:19:83:29
                           MTU: 9000 (min: 68, max: 65535)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
                 Forward Delay: 14.990s
                    Hello Time: 1.990s
                       Max Age: 19.990s
                   Ageing Time: 4min 59.990s
                      Priority: 32768
                           STP: no
        Multicast IGMP Version: 2
                          Cost: 1999
                    Port State: disabled
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: 2Gbps
                       Address: fd3c:731a:706b::5c4
                                fd3c:731a:706b:0:3501:5ede:8f26:4c08
                                fd3c:731a:706b:0:bbe6:9919:c88a:287b
                                fe80::1053:9fff:fe19:8329
                           DNS: fd3c:731a:706b::1
             Activation Policy: up
           Required For Online: yes
             DHCP6 Client IAID: 0xe2890d07
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab111b3f9218eb97b87a0000

1月 26 02:25:14 AIO systemd-networkd[424]: br0: netdev ready
1月 26 02:25:14 AIO systemd-networkd[424]: br0: Link UP
1月 26 02:25:15 AIO systemd-networkd[424]: br0: Gained carrier
1月 26 02:25:16 AIO systemd-networkd[424]: br0: Lost carrier
1月 26 02:25:17 AIO systemd-networkd[424]: br0: DHCPv6 lease lost
1月 26 02:25:17 AIO systemd-networkd[424]: br0: Gained IPv6LL
1月 26 02:25:19 AIO systemd-networkd[424]: br0: Gained carrier
1月 26 02:25:45 AIO systemd-networkd[424]: br0: DHCPv6 address fd3c:731a:706b::5c4/128 (valid for 11h 59min 59s, preferred for 11h 59min 59s)
1月 26 02:25:45 AIO systemd-networkd[424]: br0: DHCP: received delegated prefix fd3c:731a:706b:4::/62
```

**Additional program output to the terminal or log subsystem illustrating the issue**

https://gist.github.com/daiaji/faaddfb7bba63a4bc2ed17a3c4d1f7ee

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #22246.

### CODE REVIEW

File: src/network/wait-online/link.c [hunk 1]
```diff
@@ -107,72 +107,77 @@ int link_update_monitor(Link *l) {
         r = sd_network_link_get_required_for_online(l->ifindex);
         if (r < 0)
                 ret = log_link_debug_errno(l, r, "Failed to determine whether the link is required for online or not, "
-                                           "ignoring: %m");
-        else
-                l->required_for_online = r > 0;
+                                           "assuming yes: %m");
+        l->required_for_online = r != 0;
```
Comment (bluca) [inline src/network/wait-online/link.c]: Shouldn't all these be initialized when the structure is initialized, and then shouldn't the parsing not touch them in case there's a failure? That's the usual pattern we use, no?

Comment (yuwata) [reply src/network/wait-online/link.c]: Yeah,,, you are right. The commit is now dropped.

What I thought previously is the following; If the link is unmanaged, then its link file does not contain `REQUIRED_FOR_ONLINE=` line. That's correct. Then, I thought that the parser failed in that case. But that is not correct. The parser correctly handles the missing line. So, it is not necessary to do like that.

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
The last commit is also fixed. I mistakenly tested with wrong binary on the local system. I hope now it works fine. PTAL.
