### PR TITLE
analyze: correctly draw the plot for user instances.

### LINKED ISSUE #740: `systemd-analyze --user plot` works incorrectly, producing arbitrarily wide SVGs.
Start-up timestamp of a user instance (userspace_time in struct boot_times) actually may be arbitrarily big. This, because all timestamps are offset by that value, leads to creation of arbitrarily wide SVGs which almost completely consist of blank space.

One may reproduce this locally by restarting the user instance (on a machine with moderate uptime) and running `systemd-analyze --user plot > foo.svg`. I won't link an example SVG here as it may cause an OOM for somebody.

### PR DESCRIPTION
**Pull request by intelfx**
Start-up timestamp of a user instance (userspace_time in struct boot_times)
actually may be arbitrarily big. This, because all timestamps are offset by
that value, leads to creation of arbitrarily wide SVGs which almost completely
consist of blank space.

Fix this by inverse-offsetting all timestamps by that value if user instance
operation is requested.

Fixes #740.

### CODE REVIEW

File: src/analyze/analyze.c [hunk 1]
```diff
@@ -188,14 +200,32 @@ static void free_unit_times(struct unit_times *t, unsigned n) {
...
 }
 
+static void subtract_timestamp(usec_t *a, usec_t b) {
+        if (*a > 0) {
+                assert(*a >= b);
+                if (*a < b) {
+                        log_warning("subtract_timestamp: cannot subtract %llu - %llu", (unsigned long long)*a, (unsigned long long)b);
+                        *a = 0;
+                } else
+                        *a -= b;
```
Comment (zonque) [inline src/analyze/analyze.c]: I'm confused. If you assert that `a >= b`, the subsequent condition `a < b` will always be true and the actual subtraction will never take place. What am I missing?

Comment (intelfx) [inline src/analyze/analyze.c]: Ah, this is a debug leftover. Thanks for spotting. Pushing updated patch...

(In fact, if I assert `a >= b`, then `a < b` will _never_ be true, so the subtraction will _always_ take place. Nevertheless, one of branches is still dead code.)

File: src/analyze/analyze.c [hunk 2]
```diff
@@ -450,10 +501,7 @@ static int pretty_boot_time(sd_bus *bus, char **_buf) {
                 size = strpcpyf(&ptr, size, "%s (initrd) + ", format_timespan(ts, sizeof(ts), t->userspace_time - t->initrd_time, USEC_PER_MSEC));
 
         size = strpcpyf(&ptr, size, "%s (userspace) ", format_timespan(ts, sizeof(ts), t->finish_time - t->userspace_time, USEC_PER_MSEC));
-        if (t->kernel_time > 0)
-                strpcpyf(&ptr, size, "= %s", format_timespan(ts, sizeof(ts), t->firmware_time + t->finish_time, USEC_PER_MSEC));
-        else
-                strpcpyf(&ptr, size, "= %s", format_timespan(ts, sizeof(ts), t->finish_time - t->userspace_time, USEC_PER_MSEC));
+        strpcpyf(&ptr, size, "= %s", format_timespan(ts, sizeof(ts), t->firmware_time + t->finish_time, USEC_PER_MSEC));
```
Comment (zonque) [inline src/analyze/analyze.c:504]: Why this hunk?

Comment (intelfx) [inline src/analyze/analyze.c:504]: Because the subtraction `t->finish_time - t->userspace_time` is essentially a localized, incomplete version of subject of this patch. It is now done in `acquire_boot_times()` in line 397.

At the same time, `t->firmware_time` is now forced to 0 if we analyze a user instance (in the same place, in line 396).

File: src/analyze/analyze.c [hunk 3]
```diff
@@ -188,14 +200,28 @@ static void free_unit_times(struct unit_times *t, unsigned n) {
         free(t);
 }
 
+static void subtract_timestamp(usec_t *a, usec_t b) {
```
Comment (zonque) [inline src/analyze/analyze.c:203]: An `assert(a)` can't harm here, I'd say, but that's a nit.

File: src/analyze/analyze.c [hunk 4]
```diff
@@ -188,14 +200,28 @@ static void free_unit_times(struct unit_times *t, unsigned n) {
...
+        if (*a > 0) {
+                assert(*a >= b);
+                *a -= b;
+        }
+}
+
+static int acquire_boot_times(sd_bus *bus, struct boot_times **bt);
```
Comment (zonque) [inline src/analyze/analyze.c]: Static forward decls are ugly, IMO. As `acquire_boot_times()` doesn't call into `acquire_time_data()`, could you move the entire function up, probably even in an extra patch?

File: src/analyze/analyze.c (hunk 2 above)
Comment (zonque) [inline src/analyze/analyze.c:504]: Ok, thanks!

File: src/analyze/analyze.c (hunk 4 above)
Comment (intelfx) [inline src/analyze/analyze.c]: Done.

File: src/analyze/analyze.c (hunk 3 above)
Comment (intelfx) [inline src/analyze/analyze.c:203]: Done.

BTW, is it correct to `assert(*a >= b)` here? Input does not come from the user, but it comes over the bus from a different daemon.
