### PR TITLE
socket-util: introduce CMSG_FIND_AND_COPY_DATA()

### LINKED ISSUE #27241: timesyncd fails with assertion on 32bit system with 64bit time_t e.g. RISCV32
### systemd version the issue has been seen with

253.3

### Used distribution

Yocto Project (tip of trunk)

### Linux kernel version used

6.1.20-yocto-standard

### CPU architectures issue was seen on

other

### Component

systemd-timesync

### Expected behaviour you didn't see

Normal run.

### Unexpected behaviour you saw

aborts with assertion error

```
Assertion '((uintptr_t) _p) % __alignof__(struct timespec) == 0' failed at src/timesync/timesyncd-manager.c:448, function manager_receive_response(). Aborting.

Thread 1 "systemd-timesyn" received signal SIGABRT, Aborted.
```

GDB backtrace

```
0x94838a9a in __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44      pthread_kill.c: No such file or directory.
(gdb) bt
#0  0x94838a9a in __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x94838acc in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x948023f2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x947f2842 in __GI_abort () at abort.c:79
#4  0x94acb84c in log_assert_failed (text=0x369 <error: Cannot access memory at address 0x369>, file=0x6 <error: Cannot access memory at address 0x6>, line=-1802442724,
    func=0x1 <error: Cannot access memory at address 0x1>) at ../git/src/basic/log.c:889
#5  0x68806284 in manager_receive_response (source=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=0x6880d310) at ../git/src/timesync/timesyncd-manager.c:448
#6  0x94b6d96a in source_dispatch (s=0x688121e0) at ../git/src/libsystemd/sd-event/sd-event.c:3676
#7  0x94b6d61c in sd_event_dispatch (e=0x6880d510) at ../git/src/libsystemd/sd-event/sd-event.c:4252
#8  0x94b6e220 in sd_event_run (e=0x6880d510, timeout=18446744073709551615) at ../git/src/libsystemd/sd-event/sd-event.c:4313
#9  0x94b6e432 in sd_event_loop (e=0x6880d510) at ../git/src/libsystemd/sd-event/sd-event.c:4334
#10 0x68802e4e in run (argc=<optimized out>, argv=<optimized out>) at ../git/src/timesync/timesyncd.c:217
#11 main (argc=<optimized out>, argv=<optimized out>) at ../git/src/timesync/timesyncd.c:231
```

The issue is due to alignment of `struct timespec` being 8 on rv32 because time_t is 64bit by default on this architecture.
and uintptr_t is 4

see the call sequence below

https://github.com/systemd/systemd/blob/main/src/timesync/timesyncd-manager.c#L449
https://github.com/systemd/systemd/blob/main/src/basic/socket-util.h#L178
https://github.com/systemd/systemd/blob/main/src/basic/socket-util.h#L187
https://github.com/systemd/systemd/blob/main/src/fundamental/macro-fundamental.h#L363

### Steps to reproduce the problem

```
git clone git://git.yoctoproject.org/poky
. ./oe-init-build-env
echo 'DISTRO="poky-altcfg"' >> conf/local.conf
echo 'MACHINE="qemuriscv32"' >> conf/local.conf
echo 'IMAGE_FEATURES:append = " dbg-pkgs tools-debug"' >> conf/local.conf
bitbake core-image-minimal
runqemu
```

Once qemu boots run it under gdb

```
gdb /lib/systemd/systemd-timesyncd
```

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #27241.

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, what? struct timeval is not properly aligned when included in cmsg on riscv32? That sounds completely broken and a toolchain/libc bug.

**Comment by yuwata** [comment]
Looking at the `CMSG_XYZ()` macros in glibc, the alignment of data is only for `size_t` (I guess that's equivalent to `uintptr_t`). So, I am not sure this is a bug in glibc, but, at least `CMSG_XYZ` macros do not guarantee that the timespec is aligned with its `__alignof__()`.

**Comment by poettering** [comment]
what a bad interface of the kernel there! meh!

i guess this triggered only on riscv32 so far because there you have 32bit pointers but 64bit time_t, which no other arch appears to have

**Comment by poettering** [comment]
we should probably be copying out struct ucred too, just to be safe...

there's another place we deal with cmsg/SO_TIMESTAMP: server_process_datagram() in journal/journald-server.c.

**Comment by poettering** [comment]
> we should probably be copying out struct ucred too, just to be safe...

hmm, let's not do that, instead check the alignment at compile time. will prep patch for that part.

**Comment by poettering** [comment]
I prepped #27254 now which extends the alignment checks in CMSG_TYPED_DATA() to be done at build-time already. THis should catch the original issue during building already on riscv32 instead of runtime.

**Comment by poettering** [comment]
PR looks conceptually good to me, just needs to cover this other struct timeval/struct timespec cases too, as mentioned.

**Comment by yuwata** [comment]
Updated. PTAL.
Now this is on top of #27254. Please merge #27254 first.

File: src/basic/socket-util.c [hunk 1]
```diff
@@ -1171,6 +1171,18 @@ struct cmsghdr* cmsg_find(struct msghdr *mh, int level, int type, socklen_t leng
...
+void* cmsg_find_and_copy_data(struct msghdr *mh, int level, int type, void *buf, size_t buf_len) {
+        struct cmsghdr *cmsg;
+
+        assert(mh);
+
+        cmsg = cmsg_find(mh, level, type, buf_len == SIZE_MAX ? (socklen_t) -1 : CMSG_LEN(buf_len));
+        if (!cmsg)
+                return NULL;
+
+        return memcpy_safe(buf, CMSG_DATA(cmsg), buf_len == SIZE_MAX ? cmsg->cmsg_len : buf_len);
```
Comment (bluca) [inline src/basic/socket-util.c]: please add a comment here explaining why this is necessary - quoting the manpage is enough

File: src/libsystemd-network/sd-dhcp-server.c [hunk 2]
```diff
@@ -407,7 +407,7 @@ static int dhcp_server_send_udp(sd_dhcp_server *server, be32_t destination,
                    rather than binding the socket. This will be mostly useful
                    when we gain support for arbitrary number of server addresses
                  */
-                pktinfo = (struct in_pktinfo*) CMSG_DATA(cmsg);
+                pktinfo = CMSG_TYPED_DATA(cmsg, struct in_pktinfo);
```
Comment (poettering) [inline src/libsystemd-network/sd-dhcp-server.c:410]: CMSG_TYPED_DATA() doesn't really work if you put together cmsg data. it only works when reading it. That's because it validates the size values in the cmsg header, but those are not initialized here.

**Comment by poettering** [comment]
looks good but the last patch doesn't work

File: src/libsystemd-network/sd-dhcp-server.c (hunk 2 above)
Comment (yuwata) [reply src/libsystemd-network/sd-dhcp-server.c:410]: Hm? I cannot follow. 

`CMSG_TYPED_DATA()` is mostly a typesafe version of `CMSG_DATA()` with alignment check. And no extra values are read from the cmsg header other than `CMSG_DATA()` reads. If it does not work, then I think `CMSG_DATA()` here cannot work.

> That's because it validates the size values in the cmsg header, but those are not initialized here.

Here "the size values" mean `cmsg->cmsg_len` ? It _is_ already initialized before `CMSG_TYPED_DATA()` (or `CMSG_DATA()`) is called.

**Comment by yuwata** [comment]
Rebased, addressed @medhefgo's comment in the previous PR, extended commit message.

I hope all comments except for the @poettering's comment about the last commit.

PTAL.

File: src/basic/socket-util.h [hunk 3]
```diff
@@ -189,11 +189,16 @@ int flush_accept(int fd);
...
 
 struct cmsghdr* cmsg_find(struct msghdr *mh, int level, int type, socklen_t length);
+void* cmsg_find_and_copy_data(struct msghdr *mh, int level, int type, void *buf, size_t buf_len);
 
 /* Type-safe, dereferencing version of cmsg_find() */
 #define CMSG_FIND_DATA(mh, level, type, ctype)                          \
         CMSG_TYPED_DATA(cmsg_find(mh, level, type, CMSG_LEN(sizeof(ctype))), ctype)
 
+/* Type-safe version of cmsg_find_and_copy_data() */
+#define CMSG_FIND_AND_COPY_DATA(mh, level, cmsg_type, type)             \
```
Comment (dtardon) [inline src/basic/socket-util.h]: Nitpick: It would be nice if `CMSG_FIND_DATA` and `CMSG_FIND_AND_COPY_DATA` used same names for the type parameters.

File: src/libsystemd-network/sd-dhcp-server.c (hunk 2 above)
Comment (poettering) [reply src/libsystemd-network/sd-dhcp-server.c:410]: you are right. ignore me

**Comment by kraj** [comment]
I tested this along with 27254 on 253 release and can confirm that issue is fixed on qemu riscv32

```
root@qemuriscv32:~# /usr/lib/systemd/systemd-timesyncd
Contacted time server 216.239.35.0:123 (time1.google.com).

```

File: src/basic/socket-util.c (hunk 1 above)
Comment (bluca) [reply src/basic/socket-util.c]: still unaddressed?

Comment (yuwata) [reply src/basic/socket-util.c]: Do you think so? What kind of message do you want ?

Comment (bluca) [reply src/basic/socket-util.c]: I meant to add it as a code comment, as it's obscure enough so it's bound to look puzzling in the future when one has to look here, not just as a commit message. A short version of the commit message would be more than enough.

Comment (yuwata) [reply src/basic/socket-util.c]: OK. I will do.

**Comment by yuwata** [comment]
Also commented in source code. Upgrading the green label.

**Comment by bluca** [comment]
This is a bit too invasive for a stable backport
