### PR TITLE
core: do not propagate polkit error to caller

### LINKED ISSUE #13865: patch dbus error msg "The name org.freedesktop.PolicyKit1 was not provided by any .service files" when talking to polkit with something more helpful
When restarting apache2 with `systemctl restart apache2` forgetting to `sudo` the following misleading message returns:

```
Failed to restart apache2.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
```

### PR DESCRIPTION
**Pull request by keszybz**
If we fail to start polkit, we get a message like
"org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer.",
which has no meaning for the caller of our StartUnit method. Let's just
return a normal SD_BUS_ERROR_ACCESS_DENIED error.

$ systemctl start apache
Failed to start apache.service: Could not activate remote peer. (before)
Failed to start apache.service: Access denied                   (after)

Fixes #13865.

### CODE REVIEW

File: src/core/dbus-unit.c [hunk 1]
```diff
@@ -393,16 +393,21 @@ int bus_unit_method_start_generic(
...
                         polkit_message_for_job[job_type],
                         true,
                         message,
-                        error);
-        if (r < 0)
-                return r;
+                        &e);
+        if (r < 0) {
+                log_debug_errno(r, "Polkit authorization failed: %s", bus_error_message(&e, r));
+                return sd_bus_error_set(error, SD_BUS_ERROR_ACCESS_DENIED, "Permission denied");
```
Comment (poettering) [inline src/core/dbus-unit.c]: i am pretty sure this should be placed in the polkit code, i.e. in bus_verify_polkit_async(). In fact there's already some code in place to eat up certain polkit errors and turning them into plain EACCES, it just needs to cover more, most importanltly the "interactive authentication needed one".

The patch becomes a three-liner then I guess.

Comment (keszybz) [reply src/core/dbus-unit.c]: Duh, for some reason I didn't think of this. Updated.

**Comment by keszybz** [comment]
bionic-ppc64el: FAILED TESTS:  TEST-09-ISSUE-2691:
Nov 14 19:52:00 systemd-testsuite systemd[1]: testsuite.service: Control process exited, code=dumped, status=11/SEGV
Hmm.
