### PR TITLE
run: ignore bus connection error in acquiring invocation ID

### LINKED ISSUE #37675: TEST-74-AUX-UTILS.run is flaky
```
5572s TEST-74-AUX-UTILS.sh[1408]: + [[ -e /etc/pam.d/systemd-run0 ]]
5572s TEST-74-AUX-UTILS.sh[1408]: + assert_rc 37 timeout 300 systemd-run --unit=disconnecttest --wait --pipe --user -M testuser@.host bash -ec 'systemctl --user daemon-reexec; sleep 3; exit 37'
5572s TEST-74-AUX-UTILS.sh[1793]: + set +ex
5572s TEST-74-AUX-UTILS.sh[1795]: Failed to request invocation ID for unit: Remote peer disconnected
5572s [FAILED] Failed to start TEST-74-AUX-UTILS.service - TEST-74-AUX-UTILS.
5572s TEST-74-AUX-UTILS.sh[1820]: FAIL: expected: '37' actual: '1'
5572s TEST-74-AUX-UTILS.sh[109]: + echo 'Subtest /usr/lib/systemd/tests/testdata/units/TEST-74-AUX-UTILS.run.sh failed'
```

https://autopkgtest.ubuntu.com/results/autopkgtest-noble-upstream-systemd-ci-systemd-ci/noble/s390x/s/systemd-upstream/20250531_072622_61231@/log.gz

[TEST-74-AUX-UTILS.journal.gz](https://github.com/user-attachments/files/20533107/TEST-74-AUX-UTILS.journal.gz)

### PR DESCRIPTION
**Pull request by yuwata**
This introduce bus_error_is_connection(), and use it where applicable.
Then, this makes connection errors in acquiring invocation ID by systemd-run handled gracefully, like we already do other places.

Fixes #37675.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

File: src/run/run.c [hunk 1]
```diff
@@ -2075,8 +2075,24 @@ static int acquire_invocation_id(sd_bus *bus, const char *unit, sd_id128_t *ret)
                                 &error,
                                 &reply,
                                 "ay");
-        if (r < 0)
+        if (r < 0) {
+               /* Let's ignore connection errors. This might be caused by that the service manager is being
+                * restarted. Handle handle this gracefully. */
```
Comment (YHNdnzj) [inline src/run/run.c]:
```suggestion
                * restarted. Handle this gracefully. */
```

File: src/run/run.c [hunk 2]
```diff
@@ -2075,8 +2075,24 @@ static int acquire_invocation_id(sd_bus *bus, const char *unit, sd_id128_t *ret)
...
+                if (sd_bus_error_has_names(
```
Comment (YHNdnzj) [inline src/run/run.c]: There're now three checks for this, so seems worth a small helper. bus_error_is_connection?

**Comment by yuwata** [comment]
Introduced bus_error_is_connection() as suggested. Please take a look again. Hopefully the change since the previous push should be trivial. But, please.

File: src/run/run.c [hunk 3]
```diff
@@ -2075,8 +2063,24 @@ static int acquire_invocation_id(sd_bus *bus, const char *unit, sd_id128_t *ret)
...
+        if (r < 0) {
+               /* Let's ignore connection errors. This might be caused by that the service manager is being
+                * restarted. Handle this gracefully. */
+                if (bus_error_is_connection(&error)) {
+                        log_debug_errno(r, "Bus call failed due to connection problems. ignoring: %s", bus_error_message(&error, r));
+                        *ret = SD_ID128_NULL;
+                        return 0;
+                }
+
+                /* Maybe the service is already stopped and cleared? */
```
Comment (YHNdnzj) [inline src/run/run.c]: This actually can't happen because we add reference on the unit. Just log generically about connection error?

File: src/run/run.c [hunk 4]
```diff
@@ -2075,8 +2063,24 @@ static int acquire_invocation_id(sd_bus *bus, const char *unit, sd_id128_t *ret)
                                 &error,
                                 &reply,
                                 "ay");
-        if (r < 0)
+        if (r < 0) {
+               /* Let's ignore connection errors. This might be caused by that the service manager is being
+                * restarted. Handle this gracefully. */
+                if (bus_error_is_connection(&error)) {
+                        log_debug_errno(r, "Bus call failed due to connection problems. ignoring: %s", bus_error_message(&error, r));
```
Comment (YHNdnzj) [inline src/run/run.c]:
```suggestion
                        log_debug_errno(r, "Invocation ID request failed due to bus connection problems, ignoring.");
```

File: src/run/run.c (hunk 3 above)
Comment (yuwata) [reply src/run/run.c]: `AddRef` is set only when the connection is bus client. See `transient_unit_set_properties()`.

But, for simplicity, I merged two logs.
