### PR TITLE
pid1: several fixlets for device handling

### LINKED ISSUE #12953: Devices transition plugged -> dead -> plugged is still not completely fixed
This happened on Tumbleweed which ships systemd v242.

For the complete debug logs, please consult https://bugzilla.suse.com/show_bug.cgi?id=1137373.

Except from the logs:

> [   25.202778] fyrfos systemd[1]: Switching root.
> [   36.627399] fyrfos systemd[1]: Starting udev Coldplug all Devices...
> [   36.714237] fyrfos systemd[1]: Started udev Coldplug all Devices.
> [   48.182070] fyrfos systemd[1]: Reloading.
> [   48.433421] fyrfos systemd[1]: Invoking unit coldplug() handlers…
> [   48.457773] fyrfos systemd[1]: dev-sdb5.device: Changed dead -> plugged
> [   48.466512] fyrfos systemd[1]: Invoking unit catchup() handlers…
> [   48.471053] fyrfos systemd[1]: dev-sdb5.device: Changed plugged -> dead
> [   48.741803] fyrfos systemd[1]: dev-sdb5.device: Changed dead -> plugged
> [   49.005134] fyrfos systemd[1]: local.mount: local.mount lost dependency BindsTo=dev-sdb5.device
> 

This was already reported in https://github.com/systemd/systemd/issues/11997 but the fix was incorrect, see https://github.com/systemd/systemd/pull/12013#issuecomment-479038739

### LINKED ISSUE #23208: Boot to emergency mode if devices are switched to SYSTEMD_READY=0 (multipath scenario)
**systemd version the issue has been seen with**

All versions since (at least) 246

**Used distribution**

openSUSE Tumbleweed, openSUSE Leap

**Linux kernel version used** (`uname -a`)
 
`5.14`, `5.17` (any)

**CPU architecture issue was seen on**

`x86_64`, `s390x` (any)

**Expected behaviour you didn't see**
 
System should boot cleanly

**Unexpected behaviour you saw**

System ends up in emergency mode with messages like
 
    [    5.741385] m8315021 systemd-fsck[744]: /dev/sdd1 is in use.
    [    5.743787] m8315021 mount[745]: mount: /mnt: /dev/sdd1 already mounted or mount point busy.

**Steps to reproduce the problem**

Prerequisites:

 - system with multipath hardware or (at least) `multipathd.service` enabled / started
 - system boots from normal (non-multipath) disk
 - `multipath` module not included in initial ramdisk
 - low-level (SCSI) driver for multipathed disks are included in initial ramdisk (a common situation, because the "hostonly" mode in recent dracut versions defaults to including all SCSI modules that were loaded when dracut built the initrd).

With this prerequisites, the problem is still timing-dependent, but not difficult to reproduce.

**Additional program output to the terminal or log subsystem illustrating the issue**

In the case at hand, we look at a SCSI multipath device. The device to be mounted is `/dev/disk/by-uuid/56c5fcd8-35ad-48f3-8b9c-8fc7a89c5459`, which is a multipath is on a device-mapper multipath device. The low-level SCSI devices with this UUID are `/dev/sdd1` and `/dev/sdh1`. The desired mount point is `/mnt`. The following is a journalctl excerpt.

During initramfs processing, udev sees the SCSI devices and systemd considers them "plugged". Note that `multipathd.service` is disabled in the initramfs, thus `SYSTEMD_READY=0` is not set on these devices.

    [    3.332761] m8315021 systemd-udevd[300]: sdd1: Creating symlink '/dev/disk/by-uuid/56c5fcd8-35ad-48f3-8b9c-8fc7a89c5459' to '../../sdd1'
    [    3.338510] m8315021 systemd[1]: dev-disk-by\x2duuid-56c5fcd8\x2d35ad\x2d48f3\x2d8b9c\x2d8fc7a89c5459.device: Changed dead -> plugged
    [    3.376903] m8315021 systemd-udevd[306]: sdh1: Atomically replace '/dev/disk/by-uuid/56c5fcd8-35ad-48f3-8b9c-8fc7a89c5459'
    [    3.380014] m8315021 systemd[1]: dev-disk-by\x2duuid-56c5fcd8\x2d35ad\x2d48f3\x2d8b9c\x2d8fc7a89c5459.device: Device dev-disk-by\x2duuid-56c5fcd8\x2d35ad\x2d48f3\x2d8b9c\x2d8fc7a89c5459.device appeared twice with different sysfs paths /sys/devices/css0/0.0.0004/0.0.1915/host1/rport-1:0-0/target1:0:0/1:0:0:1076052021/block/sdd/sdd1 and /sys/devices/css0/0.0.0005/0.0.1955/host0/rport-0:0-0/target0:0:0/0:0:0:1076052021/block/sdh/sdh1, ignoring the latter.

**Side note:** the above shows an inconsistency between udev's and systemd's handling of the two different devices having the same alias. While udev replaces the `by-uuid` symlink which now points to `sdh1` rather than `sdd1`, systemd keeps the previous mapping to `sdd1` and emits a warning. *This is not the problem cause but worth mentioning*.

    [    3.690821] m8315021 systemd[1]: Switching root.

systemd reads the deserialized state and found attributes for this device, which are "plugged" and `DEVICE_FOUND_UDEV`, respectively. Device enumeration doesn't find the device in the udev db, which has been cleared. It's also not mounted, so it isn't found from a mount point, either.

After switching root `multipathd.service` is active, and thus the SCSI devices now get `SYSTEMD_READY=0` set, as indicated by the messages below. Note that the partitions `sdd1` and `sdh1` inherit the `DM_MULTIPATH_DEVICE_PATH=1` property from `sdd` and `sdh`, respectively, and that `DM_MULTIPATH_DEVICE_PATH=1` implies `SYSTEMD_READY=0`.

    [    5.063229] m8315021 systemd-udevd[526]: sdh: '/sbin/multipath -u sdh'(out) 'DM_MULTIPATH_DEVICE_PATH="1"'
    [    5.083264] m8315021 systemd-udevd[532]: sdd: '/sbin/multipath -u sdd'(out) 'DM_MULTIPATH_DEVICE_PATH="1"'

However `device_dispatch_io()` does nothing for ADD events with devices that aren't ready. In particular, the `plugged` state, which had been deserialized, is not reset. Hence, as soon as `local-fs-pre.target` is reached, systemd tries to fsck and mount the device. But in the meantime, `multipathd` had seen the devices too, and created a multipath map from them, causing the fsck and mount to fail:

    [    5.626369] m8315021 multipathd[707]: 3600507630bffc3200000000000003523: addmap [0 41943040 multipath 1 queue_if_no_path 1 alua 1 1 service-time 0 2 1 8:48 1 8:112 1]
    [    5.728621] m8315021 systemd[740]: systemd-fsck@dev-disk-by\x2duuid-56c5fcd8\x2d35ad\x2d48f3\x2d8b9c\x2d8fc7a89c5459.service: Executing: /usr/lib/systemd/systemd-fsck /dev/disk/by-uuid/56c5fcd8-35ad-48f3-8b9c-8fc7a89c5459
    [    5.741385] m8315021 systemd-fsck[744]: /dev/sdd1 is in use.
    [    5.741385] m8315021 systemd-fsck[744]: e2fsck: Cannot continue, aborting.
    [    5.742124] m8315021 systemd-fsck[740]: fsck failed with exit status 8.
    [    5.742195] m8315021 systemd-fsck[740]: Ignoring error.
    [    5.742379] m8315021 systemd[1]: systemd-fsck@dev-disk-by\x2duuid-56c5fcd8\x2d35ad\x2d48f3\x2d8b9c\x2d8fc7a89c5459.service: Job 164 systemd-fsck@dev-disk-by\x2duuid-56c5fcd8\x2d35ad\x2d48f3\x2d8b9c\x2d8fc7a89c5459.service/start finished, result=done
    [    5.743046] m8315021 systemd[745]: mnt.mount: Executing: /usr/bin/mount /dev/disk/by-uuid/56c5fcd8-35ad-48f3-8b9c-8fc7a89c5459 /mnt -t ext2 -o acl,user_xattr,noatime
    [    5.743787] m8315021 mount[745]: mount: /mnt: /dev/sdd1 already mounted or mount point busy.
    [    5.744679] m8315021 systemd[1]: mnt.mount: Mount process exited, code=exited, status=32/n/a
    [    5.746814] m8315021 systemd[1]: mnt.mount: Unit entered failed state.

Thus emergency mode is entered. Shortly later, the uevent that re-creates the `by-uuid` device (pointing to the correct device-mapper device now) arrives, but this has no effect on systemd, because it had considered this `by-uuid` device "plugged" before already.

    [    5.763330] m8315021 systemd-udevd[544]: dm-4: Atomically replace '/dev/disk/by-uuid/56c5fcd8-35ad-48f3-8b9c-8fc7a89c5459'
    [    5.803581] m8315021 systemd[1]: dev-disk-by\x2did-dm\x2duuid\x2dpart1\x2dmpath\x2d3600507630bffc3200000000000003523.device: Changed dead -> plugged
    [    5.803658] m8315021 systemd[1]: dev-disk-by\x2did-dm\x2dname\x2d3600507630bffc3200000000000003523\x2dpart1.device: Changed dead -> plugged
    [    5.803888] m8315021 systemd[1]: dev-dm\x2d4.device: Changed dead -> plugged

(note that various device aliases reach "plugged" state here, but the `by-uuid` alias is not mentioned).

### Suggested solution (tentative)

This problem is loosely related to #12953, even though it looks like the opposite problem (while in #12953 we want to keep the "plugged" state, we want to drop it / replace it with "dead" here). The difference is that #12953 occured after a "simple" reload operation, whereas this occurs while switching root.

When we switch root, we know that **udev** will re-run all uevents during udev coldplug (`systemd-udev-trigger.service`). They have to be re-run because rules and thus device properties may have changed. In the problem case, even the crucial `SYSTEMD_READY` property changes. We know from the discussion in #12953 and its predecessors (#8675, #8832, #11997) that switching a "plugged" device back to "dead" is potentially dangerous, especially if the device in question might be already mounted or otherwise used. A possible solution has to avoid this. My proposed solution goes on top of the fix I proposed in https://github.com/systemd/systemd/issues/12953#issuecomment-1111048603.

The idea is that if we serialize/deserialize device `state` and `found` flags while switching root, we shouldn't set "plugged" and `DEVICE_FOUND_UDEV` states. The udev db entries are gone when systemd reexecutes. Unused devices can just be "forgotten", they'll be rediscovered by udev. Devices that are mounted should keep their `DEVICE_FOUND_MOUNT` or `DEVICE_FOUND_SWAP` flags, but the state should be reset from `DEVICE_PLUGGED` to `DEVICE_TENTATIVE` (the same state that systemd uses in other similar situations when a device is encountered that seems to be in use, but not in the udev db). `DEVICE_TENTATIVE` has the effect that systemd will wait for these devices to switch to `DEVICE_PLUGGED` before attempting to mount them. The switch to `DEVICE_PLUGGED` will happen when the dm device created by multipathd is first seen by systemd. In order to detect "switching root" state, I use the already existing `honor_device_enumeration` flag, which is cleared during deserialization if and only if systemd executes a switch root operation.

The code can be [inspected on my issue23208 branch](https://github.com/mwilck/systemd/commit/ca778f3f5efd6684bf815074d00e2b330b2a182b).

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #12953.
Fixes #23208.
Replaces #23215.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @mwilck, @fbuihuu and @hreinecke.

**Comment by yuwata** [comment]
I hope most commits, except for the last two, are trivial.

**Comment by yuwata** [comment]
From https://github.com/yuwata/systemd/commit/c7fd2d5c00b62e6ca53aab052c5e8f6ec6b7c3f8#commitcomment-72476156
> Thanks for looking into this! Note that my comment in [systemd#23208](https://github.com/systemd/systemd/issues/23208) was a bit misleading perhaps. In the case I quoted, udev had indeed taken over the symlink. But that's not necessarily the case if you look at the udev code. A worker may or may not take over the symlink. In particular, systemd has no concept of udev's link priority.
> 
> IMO the only safe way for systemd to derive the current state of symlinks is to read the symlink from the filesystem, at least after each ADD/CHANGE/REMOVE uevent.

@mwilck Thank you for the comment. But, sorry, I cannot follow the comment. Could you elaborate more?

**Comment by mwilck** [comment]
Can you explain how this relates to my #23215 ?

**Comment by mwilck** [comment]
> The last commit is mostly equivalent to your PR, no?

Right ... I didn't realize this looking over the commit messages. Why didn't you just use my patch?

**Comment by mwilck** [comment]
> Right ... I didn't realize this looking over the commit messages. Why didn't you just use my patch?

I see you moved the flag modification from `device_deserialize_item()` to `device_coldplug()`. I suppose that's ok, but I'd prefer fixing the flags as soon as possible, thereby avoiding any risk to use the "wrong" flags in case the ordering of function calls in this part of the code changes in the future. Could you explain why you think doing it in `device_coldplug()` is better?

**Comment by fbuihuu** [comment]
> > The last commit is mostly equivalent to your PR, no?
> 
> Right ... I didn't realize this looking over the commit messages. Why didn't you just use my patch?

@yuwata that doesn't sound really fair actually. As you can guess, Martin spent a lot o time investigating, analyzing and fixing the issues (introduced roughly 4 years ago by https://github.com/systemd/systemd/commit/66f3fdbb073d8263b34bd65982a7e59d09086b23 that no one could fix since then). So at minimum it would be nice to give him credit of the detailed analyzis although I'm not sure to understand why you didn't provide feedback on his PR in the first place, that's what we usually do.

**Comment by yuwata** [comment]
> The code in [link_update()](https://github.com/systemd/systemd/blob/2d14ec9b8a2a7232b1a0b9229c4de4423790b5b3/src/udev/udev-node.c#L449) tries to set the symlink to the device with the highest link priority. If priorities are equal, it prefers itself (the device for which it's executing).

Right.

> We know that this may result in races between different devices claiming the same symlink.

The race should be solved by #23043. If you'd like, please take a look.

> If one device has higher link priority than all others, it will win. Regardless of which device "wins", all possible candidates will have the symlink listed in their `DEVLINKS` property.

Right.

> Thus if systemd processes an uevent with a certain devlink set, it can't be sure that the device it's currently processing actually owns this symlink.

It CAN, by using `sd_device_new_from_devname()`.

> In the case of multipath, `SYSTEMD_READY="0"` will be set for all devices except the winning device mapper device, which also has the highest priority. The same holds for MD RAID. IIUC this **should** cause the symlink to be set correctly in systemd. There's nothing that would enforce this behavior (setting `SYSTEMD_READY="0"` for all but the highest prio candidate) in udev rules, though.

Right. I forgot that in the previous version. Now, `device_is_ready()`, which checks `SYSTEMD_READY=`, is called after `sd_device_new_from_devname()`.

> In order to be certain to have the "right" device mapped to any symlink pseudo-device, systemd would need to read the symlinks that udev creates. The udev db itself doesn't contain this information, unless there's exactly one device with higher link prio than all others.

Right. So, `sd_device_new_from_devname()` reads the symlink.

> Alternatively, one might argue that if several devices claim the same symlink with the same prio, it doesn't really matter which one wins, and except for very rare situations it wouldn't really hurt that systemd and udev are in inconsistent state (if it did hurt, we'd see a lot more errors in this area than we actually do). If we accept this argument, it'd be sufficient if systemd read the link priority and mapped symlinks to the device with the highest prio, without having to actually read the symlinks.

I am not sure. May be true, but may not.

**Comment by mwilck** [comment]
> The race should be solved by https://github.com/systemd/systemd/pull/23043. If you'd like, please take a look.

Interesting that you did it this way now... the basic idea looks similar to my ancient PRs #8667 and #9551, which have later been superseded by the "lockless" solution #17431. Back then, I had scaling issues with a very large number of symlink contenders (1000 and more) for a symlink. This was mostly due to bad scaling in the kernel, solved by fd7732e033e3 ("fs/locks: create a tree of dependent requests.") in kernel v5.0.

> Right. So, sd_device_new_from_devname() reads the symlink.

Alright. Good to know. Your patch set here is pretty big, I still have to dig deeper into it. Next week, probably.

**Comment by mwilck** [comment]
> > Thus if systemd processes an uevent with a certain devlink set, it can't be sure that the device it's currently processing actually owns this symlink.
> 
> It CAN, by using `sd_device_new_from_devname()`.

I see. But now it can happen that when systemd processes an event for device A and reads the devlinks, the links point to device B. Different devlinks can even point to different devices C, D, … Not saying this is a problem, we just need to be aware of the possibility.

**Comment by yuwata** [comment]
Hm...
From https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/11428/
```
Apr 30 06:52:17 H systemd-journald[286]: Failed to send WATCHDOG=1 notification message: Connection refused
Apr 30 06:53:57 H systemd-journald[286]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
Apr 30 06:55:17 H systemd-journald[286]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
Apr 30 06:56:57 H systemd-journald[286]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
Apr 30 06:58:17 H systemd-journald[286]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
```

File: src/core/device.c [hunk 1]
```diff
@@ -158,19 +158,65 @@ static void device_set_state(Device *d, DeviceState state) {
...
+         * - On reload or reexecute, we can trust enumerated_found, deserialized_found, and deserialized_state.
+         *   Of course, deserialized parameters may be outdated, but the unit state can be adjusted later by
+         *   device_catchup() or uevents. */
+
+        if (!m->honor_device_enumeration && !MANAGER_IS_USER(m)) {
+                f &= ~DEVICE_FOUND_UDEV; /* ignore DEVICE_FOUND_UDEV bit */
+                if (s == DEVICE_PLUGGED)
+                        s = DEVICE_TENTATIVE; /* downgrade state */
+                if (f == DEVICE_NOT_FOUND)
+                        s = DEVICE_DEAD; /* If nobody sees the device, downgrade more */
```
Comment (mwilck) [inline src/core/device.c]: I assume that `deserialized_found == DEVICE_NOT_FOUND` implies `deserialized_state == DEVICE_DEAD`. In that case the clause would be redundant. But if this implication does **not** hold for whatever reason, we'd better understand how that comes to pass before we reset the state to "dead", which is dangerous.

**Comment by mwilck** [comment]
@yuwata, AFAICS commit https://github.com/systemd/systemd/pull/23215/commits/57910e581ecd85de524c21a8eac213dd9c54732c (my proposed fix for #12953) is not included in your set. Could you explain please?

File: src/core/device.c [hunk 2]
```diff
@@ -639,13 +685,9 @@ static void device_found_changed(Device *d, DeviceFound previous, DeviceFound no
...
 
 static void device_update_found_one(Device *d, DeviceFound found, DeviceFound mask) {
-        Manager *m;
-
         assert(d);
 
-        m = UNIT(d)->manager;
-
-        if (MANAGER_IS_RUNNING(m) && (m->honor_device_enumeration || MANAGER_IS_USER(m))) {
+        if (MANAGER_IS_RUNNING(UNIT(d)->manager)) {
```
Comment (mwilck) [inline src/core/device.c:692]: This drops the condition `m->honor_device_enumeration`. If the udev db is not initialized, `d->enumerated_found` will be `DEVICE_NOT_FOUND`. Thus `manager_startup() → manager_ready() → unit_catchup() → device_catchup() → device_update_found_one()` will see `MANAGER_OK`, and will reset `d->found` to `d->enumerated_found == DEVICE_FOUND_NONE`, with possibly fatal consequences. What am I missing here?

**Review by mwilck — CHANGES_REQUESTED** [review]

File: src/core/device.c (hunk 2 above)
Comment (mwilck) [reply src/core/device.c:692]: IOW, I think the test for `m->honor_device_enumeration` must be kept here.

File: src/core/device.c [hunk 3]
```diff
@@ -705,9 +698,111 @@ static bool device_is_ready(sd_device *dev) {
...
+                if (PATH_STARTSWITH_SET(devlink, "/dev/block/", "/dev/char/"))
+                        continue;
+
+                if (device_setup_devlink_unit_one(m, devlink, &assigned) <= 0)
+                        continue;
+
+                if (sd_device_get_syspath(assigned, &s) < 0)
+                        continue;
+
+                if (path_equal(s, syspath))
```
Comment (mwilck) [inline src/core/device.c]: Should this be `!path_equal()` ?

**Comment by mwilck** [comment]
> @yuwata, AFAICS commit [57910e5](https://github.com/systemd/systemd/commit/57910e581ecd85de524c21a8eac213dd9c54732c) (my proposed fix for #12953) is not included in your set. Could you explain please?

See https://github.com/systemd/systemd/pull/23234#issuecomment-1114704517

File: src/core/device.c [hunk 4]
```diff
@@ -705,9 +698,111 @@ static bool device_is_ready(sd_device *dev) {
...
+                if (!path_startswith(d->path, "/dev/"))
+                        continue;
+
+                if (device_setup_devlink_unit_one(m, d->path, &assigned) <= 0)
+                        continue;
+
+                if (sd_device_get_syspath(assigned, &s) < 0)
+                        continue;
+
+                if (path_equal(s, syspath))
```
Comment (mwilck) [inline src/core/device.c]: Again, `!path_equal()`?

File: src/core/device.c (hunk 1 above)
Comment (yuwata) [reply src/core/device.c]: The condition holds if `deserialized_found == DEVICE_FOUND_UDEV`.
In that case, `f == DEVICE_NOT_FOUND` and the device was neither mounted nor used as a swap.
Hence, I think it is safe to go to `DEVICE_DEAD`.

In other words, entering the state `DEVICE_TENTATIVE` with `DEVICE_NOT_FOUND` sounds quite strange.

File: src/core/device.c (hunk 3 above)
Comment (yuwata) [reply src/core/device.c]: No, I intend to exclude this to make `ready_devlinks` only contain links not assigned to the device currently processing.

The .device units which corresponds to the syspath that is currently processing will be handled by `device_update_found_by_sysfs()`. However, .device units that get involved in this function whose syspath is different from the syspath currently processed must be handled by `device_update_found_by_name()`. So, we need to create the list of the involved devices here.

File: src/core/device.c (hunk 4 above)
Comment (yuwata) [reply src/core/device.c]: This is also intended.

File: src/core/device.c (hunk 1 above)
Comment (mwilck) [reply src/core/device.c]: It would be strange to find this combination (`found == DEVICE_NOT_FOUND` and `state != DEVICE_DEAD`) in the serialized state, yes. Maybe we should emit a warning if we hit this case.

File: src/core/device.c (hunk 3 above)
Comment (mwilck) [reply src/core/device.c]: ok, thanks for the clarification.

**Comment by yuwata** [comment]
Reply for https://github.com/systemd/systemd/pull/23234#issuecomment-1114704517
> @yuwata, you're confusing me. Why do we have a separate PR for this now, which is also included in #23218?

Sorry, previously one of the commit in this PR had a memleak, and CI were unhappy, to investigate the reason, I split the PR. Now, the memleak is fixed. I will close #23234.

> > @mwilck I do not think the first commit of #23215 is necessary. Moreover, it makes devices removed during reload or reexec processes not handled correctly.
> 
> The commit is necessary for systemd reload operations that take place before the udev DB is fully initialized, e.g. during boot, as explained int the commit message ([57910e5](https://github.com/systemd/systemd/commit/57910e581ecd85de524c21a8eac213dd9c54732c)). In this case, the `DEVICE_FOUND_UDEV` bit would be clear in `d->enumerated_found`, and we'd reset `d->found` in `device_catchup()`, causing the `plugged→dead→plugged` transition (#11997, #12953). If systemd is reloading, the only reason to reset `DEVICE_FOUND_UDEV` would be the arrival of a REMOVE uevent. If this actually happens during a reload, the uevent will be handled after the reload, and the device state will be correct again, even if we haven't reset it in `device_catchup()`.
> 
> You're right that this does not hold for `systemctl daemon-reexec`, because `reexec` closes systemd's device monitor socket, creating a time window in which uevents might get lost. That's no problem for the switching-root case, where udev coldplug will fix device states. `systemctl daemon-reexec` without switching root might indeed miss uevents. The "risk" that my patch introduces is only that _a device is removed while systemd is re-executing_, and systemd misses the REMOVE uevent. This is quite unlikely, and easily fixed by running `systemctl restart systemd-udev-trigger.service`. IMO this risk is rather unimportant compared to the frequent issues with systemd _reload_ operations during boot leading to "plugged→dead→plugged" transitions.
> 
> The only way to "fix" the reexec problem would be to distinguish between "reload" and "reexec" in `device_catchup()`, and apply my patch only in the "reload" case. But even if we did that, `daemon-reexec` triggered during the boot procedure would be at risk to falsely consider devices "dead" if it calls `device_enumerate` before udev coldplugging has finished. We know from past discussions about `udev settle` that determining when udev is **done** processing devices is basically impossible. IMHO the best way to avoid this would be to generally block or postpone "reexecute" operations (except for switching root) until `default.target` (or at least `local-fs.target`) has been reached. But that goes far beyond the scope of my PR.

With the second commit in #23215, or the second commit in this PR, all device units will not have `DEVICE_FOUND_UDEV` bit in `d->found`, and the state is `DEVICE_TENTATIVE` (or DEVICE_DEAD with my commit) after `device_coldplug()`. Hence, the devices with the tentative state will never enter the dead state in `device_catchup()` (unless the device is not mounted or used for swapping anymore). 
If PID1 is reloaded or reexecuted soon after switching root, the `deserialized_found` does not have `DEVICE_FOUND_UDEV` bit and `deserialized_state == DEVICE_TENTATIVE`, and these are simply copied to the main parameters. Hence the tentative devices will never enter the dead state in `device_catchup()` called in the reload or reexecute process (again, unless the device is not mounted or used for swapping anymore).

**Comment by yuwata** [comment]
@mrc0mmand I noticed that if PID1 has a memleak, then several tests in CentOS CI (Arch Linux + sanitizers) fail. But, unfortunately, the logs do not contain anything about why the tests failed. E.g. https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/11428/
Is this expected? Is it possible to improve the report like e.g. when networkd has memleak?

**Comment by mwilck** [comment]
> With the second commit in #23215, or the second commit in this PR, all device units will not have `DEVICE_FOUND_UDEV` bit in `d->found`, and the state is `DEVICE_TENTATIVE` (or DEVICE_DEAD with my commit) after `device_coldplug()`. 

Hm, you're right. I didn't realize this because I'd tackled the "plugged→dead→plugged" before I looked at the multipath issue.

**Comment by mrc0mmand** [comment]
> @mrc0mmand I noticed that if PID1 has a memleak, then several tests in CentOS CI (Arch Linux + sanitizers) fail. But, unfortunately, the logs do not contain anything about why the tests failed. E.g. https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/11428/ Is this expected? Is it possible to improve the report like e.g. when networkd has memleak?

I've stumbled across this as well when debugging stuff in RHEL. The issue here, imo, is that the memleak happens when a logging facility is not available (e.g. before/after journald is started/stopped), so the log goes to /dev/null. I guess it would make sense to use `log_path=` for ASan/UBSan logs for PID as well (as we already do for journald), so they don't get accidentally lost. I'll put this on my TODO list to look at it later.

File: src/core/device.c (hunk 2 above)
Comment (mwilck) [reply src/core/device.c:692]: `m->honor_device_enumeration` matters only if switching root. Following a similar argument as https://github.com/systemd/systemd/pull/23218#issuecomment-1114901938, the device would have been reset to `DEVICE_TENTATIVE` beforehand. If the device had been mounted before switching root, `device_enumerate()` should have seen it and `enumerated_found` should be `DEVICE_FOUND_MOUNTED`.
So I *suppose* this change does no harm. It's the kind of thing that scares me a bit though, because of past experience with the subtleties of the device handling code.

As `m->honor_device_enumeration` now doesn't affect any more whether device enumeration is honored, this change is definitely an argument for changing the field name from `m->honor_device_enumeration` to `m->honor_serialized_device_state` or perhaps simply `m->switching_root`.

**Comment by mwilck** [comment]
@yuwata, I would appreciate if we could isolate the switching root / device activation fixes from the code that modifies the symlink handling. The former is required to fix actual bugs we are seeing. The latter, while highly worthwhile, is not known to cause any real-world issues.

You are probably aware that the issues we're working on here are outside the realm of CI. Only testing on a variety of diversely configured real systems by real people reveals possible issues. Most of these users don't test with upstream systemd, and won't be easily persuaded to do so.

My patches from #23215 have been verified by users on SUSE releases of systemd, based on systemd 249 and 246, respectively. I'll provide backports of  b5f9f2b7 to these users for testing, but I will not include the rest of your changes because they are too intrusive for us. I hope you can understand that.

**Comment by fbuihuu** [comment]
@yuwata a slightly different approach can be found at https://github.com/systemd/systemd/compare/main...fbuihuu:device-fix-plug-dead-plug-again, see the first three commits. It basically always forces to forget all devices that is no more present in udev DB (done by `device_coldplug()`) and let `device_catchup()` decide for the final state (in case the device is referenced by a mount/swap unit). This is more or less what the old code did. It also introduces `MANAGER_IS_SWITCHING_ROOT()` which makes the code slightly easier to parse.

The fourth commit is more interesting because it drops `device_coldplug()` entirely. Since this function was basically used to restore the serialized device properties, which is supposed to be done be `device_deserialize_items()`. Hence it let `device_catchup()` decides for the final state of the device and generate the state transition event when needed.

**Comment by yuwata** [comment]
Sorry for late reply. I will update this and reply the comments later today.

**Comment by yuwata** [comment]
Dropped the commits about symlink update. Will reply the comments one-by-one.

File: src/core/device.c (hunk 2 above)
Comment (yuwata) [reply src/core/device.c:692]: > `m->honor_device_enumeration` matters only if switching root. Following a similar argument as [#23218 (comment)](https://github.com/systemd/systemd/pull/23218#issuecomment-1114901938), the device would have been reset to `DEVICE_TENTATIVE` beforehand. If the device had been mounted before switching root, `device_enumerate()` should have seen it and `enumerated_found` should be `DEVICE_FOUND_MOUNTED`. So I _suppose_ this change does no harm. It's the kind of thing that scares me a bit though, because of past experience with the subtleties of the device handling code.

`device_enumerate()` sets `DEVICE_FOUND_UDEV` bit if the device is already processed by systemd-udevd, instead of `DEVICE_FOUND_MOUNT`.
As I commented in the code, on switching root, `device_enumerate()` lists almost no devices, as udev database is cleared. Hence, `device_catchup()` does not set `DEVICE_FOUND_UDEV` flag for devices, and `device->state` is kept as `DEVICE_TENTATIVE`.

> As `m->honor_device_enumeration` now doesn't affect any more whether device enumeration is honored, this change is definitely an argument for changing the field name from `m->honor_device_enumeration` to `m->honor_serialized_device_state` or perhaps simply `m->switching_root`.

Yeah, I agree. But let's do that later.

**Comment by yuwata** [comment]
> I have run the first two patches from this PR ([5cfb16a](https://github.com/systemd/systemd/commit/5cfb16af539ded421328e44ce0f51785778cda75) and [b5f9f2b](https://github.com/systemd/systemd/commit/b5f9f2b79731aaa5fc332bada88bdc52870f6a6a)) through extensive reboot tests, both on systems that would used to exhibit boot failures without these patches and on others (to watch out for regressions). Two customers, who could reproduce multipath booting issues on their systems easily before, have verified the same fix in similar extensive reboot tests. All tests were done with SUSE systemd packages with the mentioned two patches cherry-picked.
> 
> **I consider these two commits validated by real-world testing.**

Yay!! Thank you!

File: src/core/device.c (hunk 2 above)
Comment (mwilck) [reply src/core/device.c:692]: My concern here was that `device_coldplug()` now calls `device_set_state()` even if `honor_device_enumeration` is false. But as I said previously, I believe it's ok, and my testing yielded favourable results. This conversation can be considered resolved.

>  As I commented in the code, on switching root, `device_enumerate()` lists almost no devices, as udev database is cleared. 

FTR: true,  but `manager_enumerate()` also calls `mount_enumerate()`, which may set `DEVICE_FOUND_MOUNT`.

**Comment by yuwata** [comment]
I guess all concerns are solved now? At least I think all questions are answered.
PTAL!

File: src/core/device.c (hunk 1 above)
Comment (yuwata) [reply src/core/device.c]: OK. Let's add the warning later.

File: src/core/device.c [hunk 5]
```diff
@@ -158,19 +158,65 @@ static void device_set_state(Device *d, DeviceState state) {
...
         assert(d);
         assert(d->state == DEVICE_DEAD);
 
         /* First, let's put the deserialized state and found mask into effect, if we have it. */
+        if (d->deserialized_state < 0)
+                return 0;
+
+        m = u->manager;
+        f = d->deserialized_found;
+        s = d->deserialized_state;
```
Comment (keszybz) [inline src/core/device.c]: Why not write this as 
```C
Manager *m = u->manager;
DeviceFound found = d->deserialized_found;
DeviceState state = d->deserialized_state;
```
Much easier to read…

File: src/core/device.c [hunk 6]
```diff
@@ -158,19 +158,65 @@ static void device_set_state(Device *d, DeviceState state) {
...
+
+        /* On initial boot, switch-root, reload, reexecute, the following happen:
+         * 1. MANAGER_IS_RUNNING() == false
+         * 2. enumerate devices: manager_enumerate() -> device_enumerate()
+         *    Device::enumerated_found is set.
```
Comment (keszybz) [inline src/core/device.c]: `::` is C++. Maybe just `Device.enumerated_found` ?

File: src/core/device.c [hunk 7]
```diff
@@ -158,19 +158,65 @@ static void device_set_state(Device *d, DeviceState state) {
...
+         * 3. deserialize devices: manager_deserialize() -> device_deserialize()
+         *    Device::deserialize_state and Device::deserialized_found are set.
+         * 4. coldplug devices: manager_coldplug() -> device_coldplug()
+         *    deserialized properties are copied to the main properties.
+         * 5. MANAGER_IS_RUNNING() == true: manager_ready()
+         * 6. catchup devices: manager_catchup() -> device_catchup()
+         *    Device::enumerated_found is applied to Device::found, and state is updated based on that.
+         *
+         * Notes:
+         * - On initial boot, no udev database exist. Hence, no devices are enumerated in the step 2.
```
Comment (keszybz) [inline src/core/device.c]: exist → exists

File: src/core/device.c [hunk 8]
```diff
@@ -158,19 +158,65 @@ static void device_set_state(Device *d, DeviceState state) {
...
+         *   Also, there is no deserialized device. Device units are (a) generated based on dependencies of
+         *   other units, or (b) generated when uevents are received.
+         *
+         * - On switch-root, no udev databse exist, except for devices with sticky bit, i.e. OPTIONS="db_persist".
```
Comment (keszybz) [inline src/core/device.c]: databse exist → database exists

Note that this description is only true for "traditional initramfs". We (I) stopped doing the db wipe on switch root now. Maybe change "no udev database exists" to "the udev database may be removed" ?

**Review by keszybz — COMMENTED** [review]
This looks reasonable, but the logic is so complicated that I don't feel confident saying it's correct. Let's merge this and release -rc3 to give people a few days to test this.

**Comment by keszybz** [comment]
mkosi / ci (fedora, 35): test-acl: sh: line 1: getfacl: command not found

**Comment by mrc0mmand** [comment]
> mkosi / ci (fedora, 35): test-acl: sh: line 1: getfacl: command not found

That's being resolved in https://github.com/systemd/systemd/pull/23365.

**Comment by yuwata** [comment]
> mkosi / ci (fedora, 35): test-acl: sh: line 1: getfacl: command not found

#23365.

**Comment by fbuihuu** [comment]
> The macro `MANAGER_IS_SWITCHING_ROOT()` is true only when the _previous_ process in the shutting down stage. Hence, it is always false in `device_coldplug()` or `device_catchup()`.

@yuwata I don't think so, otherwise this code would have never been able to pass my basic testing. See the call to `manager_set_switching_root(m, arg_switched_root);` in `main()`.

> 
> > The fourth commit is more interesting because it drops `device_coldplug()` entirely. Since this function was basically used to restore the serialized device properties, which is supposed to be done be `device_deserialize_items()`. Hence it let `device_catchup()` decides for the final state of the device and generate the state transition event when needed.
> 
> If the (deserialized) found and the `enumerated_found` are equivalent, then it does not call `device_set_state()`...

Well that's the whole point of the patch: "forget" all devices after switching root that are no more referenced by udev nor by systemd (mount/swap) units.

I think you should reread it more carefully. This version seems to be simpler, which is rather a good argument since the logic is already complicated.

Thanks.

**Comment by yuwata** [comment]
@fbuihuu Could you open a PR? Then we can easily review and discuss about the code there.

**Comment by fbuihuu** [comment]
> @fbuihuu Could you open a PR? Then we can easily review and discuss about the code there.

OK I will.

**Comment by mwilck** [comment]
> It's not clear to me whether it will cause issue in practice (maybe @mwilck knows ?) but this `dead->plugged` transition for devices with `db_persist` doen't look correct and wasn't present before. And udev man page seems to indicate that this transition should not occur.

Why would this even be mentioned in an the udev man page? It's genuine systemd functionality.

I have observed these transitions (I see them all the time actually because I work with multipath-tools, but I didn't bother about it), but definitely no negative impact. 

I have a test case here where root FS (btrfs) is on top of LVM on top of MD RAID on top of multipath. Thus the multipath devices (which have `db_persist` set) are in use once root is mounted, but from the PoV of systemd, they have neither `DEVICE_FOUND_MOUNT` nor `DEVICE_FOUND_SWAP` set. Thus they start out "dead" after switching root, just like in @fbuihuu's example. I can see these dead→plugged transitions with loglevel debug, but everything works just fine during boot.

**Comment by mwilck** [comment]
@yuwata. recall [this discussion](https://github.com/systemd/systemd/pull/23218#discussion_r862654712) we had previously? If we removed the lines 
```
+                if (found == DEVICE_NOT_FOUND)
+                        state = DEVICE_DEAD; /* If nobody sees the device, downgrade more */
```
from 75d7b59, we'd still see transition messages but only "tentative→plugged", not the confusing "dead→plugged". I don't think this can be completely avoided. We apply the result from enumeration after the result from deserialization on purpose.

**Comment by mwilck** [comment]
Ah, and my example above shows that it can actually happen that `deserialized_state == DEVICE_PLUGGED` and `(deserialized_found & ~DEVICE_FOUND_UDEV) == DEVICE_NOT_FOUND`. (https://github.com/systemd/systemd/pull/23218#discussion_r862841031).

**Comment by yuwata** [comment]
https://github.com/systemd/systemd/issues/13775#issuecomment-1211271191 requests to backport 75d7b5989f99125e52d5c0e5656fa1cd0fae2405. Setting the backport label.

**Comment by keszybz** [comment]
@yuwata I know this and #23517 have been requested for backports, but I don't feel confident enough to do it myself. Could you open a PR against v250-stable?

**Comment by yuwata** [comment]
Sure, I will.

**Comment by keszybz** [comment]
@yuwata ping

**Comment by nikita-dodia** [comment]
Hi All,
We have an issue where all devices change to dead state during systemd daemon-reload. The issue is seen on systemd-stable v-253.6.
The systemd daemon-reload is performed during startup. We found the pull request [#23215](https://github.com/systemd/systemd/pull/23215) on github that seems to address this issue.
We tracked that #23215 got superseeded by this pull request,but this pull request does not include
the change [57910e5](https://github.com/systemd/systemd/pull/23215/commits/57910e581ecd85de524c21a8eac213dd9c54732c)  that we need for our issue
Is there a specific reason why this change from #23215 got dropped when "replacing" it with the new pull request?

**Comment by yuwata** [comment]
@nikita-dodia Could you open a new issue about your issue, if it can be reproducible with a recent release of systemd? Otherwise we can easily forget your comment on an already closed PR.

**Comment by nikita-dodia** [comment]
We can only test it on latest release of v253-stable which is v253.29. Would you accept a new issue based on reproduction on this 253.29 version?

**Comment by mwilck** [comment]
It's almost 3y ago and a really complicated matter.

I can just say that back then, after lengthy discussions with @yuwata and others, we concluded that #23218 was correct. And since then I haven't observed the kind of device failures during boot that were the topic of this PR. I have no clue about the state of the backports.

**Comment by yuwata** [comment]
@nikita-dodia Sorry, v253 is too old here. Please reproduce with a recent release.

**Comment by nikita-dodia** [comment]
> It's almost 3y ago and a really complicated matter.
> 
> I can just say that back then, after lengthy discussions with @yuwata and others, we concluded that #23218 was correct. And since then I haven't observed the kind of device failures during boot that were the topic of this PR. I have no clue about the state of the backports.

I have two questions regarding the fix:

1. Did your startup scenario change so that you are not concerned about doing systemctl daemon-reload during startup any more?
2. In the original fix #23215 you mentioned in the first point of the conversation that the issue is seen during systemctl reload. Was it systemctl reload for a service or daemon-reload for the complete manager?

**Comment by nikita-dodia** [comment]
> @nikita-dodia BTW, maybe related to #9751 ?

Our current understanding is that the conditions are different (i.e we do not trigger udevadm trigger in parallel to systemctl daemon-reload) so its not related to #9751.

The issue that we see is occasional.
