### PR TITLE
mmap-cache: enforce an unused windows minimum

### LINKED ISSUE #34516: journalctl --verify fails to utilize mmap cache effectively
### systemd version the issue has been seen with

255

### Used distribution

gentoo

### Linux kernel version used

6.10.6-gentoo

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

journalctl completes efficiently without unmapping recently accessed file ranges. it should have low sys%, low page fault rate and utilize the mmap cache efficiently.

### Unexpected behaviour you saw

journalctl --verify (and likely other forms of journal access) spend tons of time calling mmap/munmap when there's multiple journal files that exceed some TBD count/size. it incurs high page fault rates and high sys% cpu.

if the data set is smaller (say after --vacuum or on single journal files), the bad behavior won't occur.

a screenshot showing high kernel time spent in memory mapping, high fault rates, repeated mmap/munmap, high sys%

2024-09-20-182824_1920x1200_scrot

### Steps to reproduce the problem

have a large enough journal data set and run journalctl --verify, and wonder why it takes so long. check perf, strace -e %memory for repeated mmap/munmap calls, pidstat -r for page fault rate and pidstat -u for sys%.

i can reproduce this with systemd 249 on ubuntu, 255 on gentoo, and 256 on debian.

i can provide an exemplary data set if needed.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by vcaputo**
With many fds the global windows count generally exceeds the
minimum.   This results in always reusing the unused entry if
there is one, which becomes a sort of degenerate case where we're
just constantly unmapping->mapping.

Instead let's try always have at least several unused windows on the
unused list before we resort to churning through it.

Fixes #34516

### CODE REVIEW

**Comment by vcaputo** [comment]
@mischief thanks for the testing

File: src/libsystemd/sd-journal/mmap-cache.c [hunk 1]
```diff
@@ -64,11 +64,13 @@ struct MMapCache {
 
         LIST_HEAD(Window, unused);
         Window *last_unused;
+        unsigned n_unused;
 
         Window *windows_by_category[_MMAP_CACHE_CATEGORY_MAX];
 };
 
 #define WINDOWS_MIN 64
+#define UNUSED_MIN 8
```
Comment (vcaputo) [inline src/libsystemd/sd-journal/mmap-cache.c]: Picking the right value here is up for grabs.

@mischief provided these timings for UNUSED_MIN=8:
```
mmap cache statistics: 3432317041 category cache hit, 469645869 window list hit, 1879691 miss
real    3m14.098s
user    2m8.897s
sys     1m4.725s
```
Which while much better than not having this PR at all, could use some improvement.

@mischief if you're up for doing a similar set of timings like you did for the FD_WINDOWS_MIN in the closed PR, it could help inform what's the best bang for buck here... TIA

**Comment by mischief** [comment]
```
$ for f in 4 8 16 32; do echo $f; time SYSTEMD_LOG_LEVEL=debug ./build/journalctl-${f} --quiet --verify --directory=/tmp/var/log/journal/a232bb0e623b4953950b2c2906b2c219/ |& grep miss; done
4
mmap cache statistics: 3458384934 category cache hit, 445456491 window list hit, 1176 miss

real    2m4.467s
user    2m3.702s
sys     0m0.741s
8
mmap cache statistics: 3458384934 category cache hit, 445456491 window list hit, 1176 miss

real    2m6.019s
user    2m5.317s
sys     0m0.671s
16
mmap cache statistics: 3458384934 category cache hit, 445456491 window list hit, 1176 miss

real    2m2.979s
user    2m2.275s
sys     0m0.684s
32
mmap cache statistics: 3458384934 category cache hit, 445456491 window list hit, 1176 miss

real    2m6.153s
user    2m5.511s
sys     0m0.608s
```

1 and 2 exhibit similar symptoms to #34516.

**Comment by mischief** [comment]
with updated patch with extra stats:
```
$ for f in 4 8 16 32; do time SYSTEMD_LOG_LEVEL=debug ./build/journalctl-${f} --quiet --verify --directory=/tmp/var/log/journal/a232bb0e623b4953950b2c2906b2c219/ |& grep miss; done
mmap cache statistics: 3458384934 category cache hit, 445456491 window list hit, 1176 miss, 100 files, 129 windows, 29 unused

real    2m5.265s
user    2m4.614s
sys     0m0.639s
mmap cache statistics: 3458384934 category cache hit, 445456491 window list hit, 1176 miss, 100 files, 129 windows, 29 unused

real    2m5.061s
user    2m4.241s
sys     0m0.816s
mmap cache statistics: 3458384934 category cache hit, 445456491 window list hit, 1176 miss, 100 files, 129 windows, 29 unused

real    2m5.367s
user    2m4.714s
sys     0m0.648s
mmap cache statistics: 3458384934 category cache hit, 445456491 window list hit, 1176 miss, 100 files, 129 windows, 29 unused

real    2m5.237s
user    2m4.553s
sys     0m0.671s
```

**Comment by vcaputo** [comment]
Ok, I've changed it to 4 for now.  Let's see what the team thinks about this approach...

**Comment by vcaputo** [comment]
ping @yuwata @DaanDeMeyer any thoughts here?  I find it compelling that enforcing a minimum of just 4 unused windows in the unused list prevents the degenerate behavior @mischief observed.  That's not a major amt of headroom to go for, esp. considering it's a per-mmap-cache and not per-mmap-cache-fd allocation.

**Comment by yuwata** [comment]
Sorry for late review. Looks nice. I will test this later.

**Review by poettering — APPROVED** [review]

**Comment by poettering** [comment]
(will leave the merge to @yuwata, since he wanted to test this)

**Review by yuwata — APPROVED** [review]
Sorry for late.
Really nice.

**Comment by yuwata** [comment]
> Thanks for the timely reviews guys

Sorry for late, really.

> If there's a way to credit @mischief (Nick Owens) in the release notes as a contributor I'd like to advocate for it. We collaborated on this in person and without his nerd sniping me into action by describing and showing me the poor performance and obviously dysfunctional mmap/munmap behavior he saw in strace, neither this PR or its related issue would have been created. But I don't think the release contributors list generator automatically includes anyone beyond merged commit authors, does it?

I think it is OK to add a `Special thanks:` section with a short sentence just above `Contributors:` of the next release in NEWS. Please open a PR.

We added GNOME Foundation to the contributors list, see 18d264123629a284b0923201735f057ed12b348c, but it is hard to maintain, as you said the list is automatically generated. So, using another section is better, I think.
