### PR TITLE
Fixes for socket buffer size

### LINKED ISSUE #14417: network: Many interfaces lead to "kernel receive buffer overrun"
**systemd version the issue has been seen with**
241, but the relevant code has not changed since.

**Used distribution**
 Debian 10

**Expected behaviour you didn't see**
`systemd-networkd.service` should start successfully.

**Unexpected behaviour you saw**
With about 200 interfaces (100 VLANs and a bridge on each of them), when starting `systemd-networkd` I get the following error in the journal:
```
systemd-networkd[1831]: Could not enumerate addresses: No buffer space available
```
Running `sudo SYSTEMD_LOG_LEVEL=debug /lib/systemd/systemd-networkd` gives a bit more insight:
```
rtnl: kernel receive buffer overrun
Could not enumerate addresses: No buffer space available
```
The buffer that is overrun is probably [this one](https://github.com/systemd/systemd/blob/4171837be6b8c92886727a04616c4d2b6d123e22/src/network/networkd-manager.c#L42) somewhere inside [this function](https://github.com/systemd/systemd/blob/4171837be6b8c92886727a04616c4d2b6d123e22/src/network/networkd-manager.c#L1925).

**Steps to reproduce the problem**
* Add 100 VLAN interfaces to one of your interfaces/bridges.
* Add a bridge to each of those interfaces
* `sudo systemctl restart systemd-networkd`

### LINKED ISSUE #16865: several vlans stuck in pending
**systemd version the issue has been seen with**

> systemd 245 (245.4-4ubuntu3.2)
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**

> Ubuntu 20.04 LTS

**Expected behaviour you didn't see**

> Configured vlans

**Steps to reproduce the problem**

> Use the provided netplan. `systemctl enable systemd-networkd.socket`

**netplan**

[01-netcfg.txt](https://github.com/systemd/systemd/files/5134516/01-netcfg.txt)

**journalctl -b with debug on**

[debug.log](https://github.com/systemd/systemd/files/5134620/debug.log)

**networkctl status -a**

[network.log](https://github.com/systemd/systemd/files/5134643/network.log)

> The bug appiers at Line 19189, every interface before is configured

**dmesg**

[dmesg.log](https://github.com/systemd/systemd/files/5134674/dmesg.log)

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes #14417.
Hopefully fixes #16865.

### CODE REVIEW

File: src/basic/socket-util.c [hunk 1]
```diff
@@ -628,13 +628,19 @@ int fd_inc_sndbuf(int fd, size_t n) {
...
+        /* First, try to set the buffer size with SO_SNDBUF. */
+        r = setsockopt_int(fd, SOL_SOCKET, SO_SNDBUF, n);
+        if (r < 0)
+                return r;
 
-        if (setsockopt_int(fd, SOL_SOCKET, SO_SNDBUF, n) < 0) {
-                r = setsockopt_int(fd, SOL_SOCKET, SO_SNDBUFFORCE, n);
-                if (r < 0)
-                        return r;
-        }
```
Comment (poettering) [inline src/basic/socket-util.c:634]: maybe add a comment here, why we now check again

File: src/basic/socket-util.c [hunk 2]
```diff
@@ -650,13 +656,19 @@ int fd_inc_rcvbuf(int fd, size_t n) {
...
+        /* First, try to set the buffer size with SO_RCVBUF. */
+        r = setsockopt_int(fd, SOL_SOCKET, SO_RCVBUF, n);
+        if (r < 0)
+                return r;
 
-        if (setsockopt_int(fd, SOL_SOCKET, SO_RCVBUF, n) < 0) {
-                r = setsockopt_int(fd, SOL_SOCKET, SO_RCVBUFFORCE, n);
-                if (r < 0)
-                        return r;
-        }
```
Comment (poettering) [inline src/basic/socket-util.c:653]: ditto

File: src/libsystemd/sd-device/device-monitor.c [hunk 3]
```diff
@@ -91,18 +91,9 @@ int device_monitor_allow_unicast_sender(sd_device_monitor *m, sd_device_monitor
...
-        assert_return((size_t) n == size, -EINVAL);
-
-        if (setsockopt_int(m->sock, SOL_SOCKET, SO_RCVBUFFORCE, n) < 0) {
-                r = setsockopt_int(m->sock, SOL_SOCKET, SO_RCVBUF, n);
-                if (r < 0)
-                        return r;
-        }
 
-        return 0;
+        return fd_inc_rcvbuf(m->sock, size);
```
Comment (poettering) [inline src/libsystemd/sd-device/device-monitor.c]: so, hmm, is this right? fd_inc_recvbuf() only *increases* the socket buffer, while the pre-existing code might also lower it if the caller asks for it. Is this an intentional change? I guess in most cases this is called to increase the buffer, but do we want to encode that it can only be used for that?

File: src/core/socket.c [hunk 4]
```diff
@@ -1058,20 +1058,15 @@ static void socket_apply_socket_options(Socket *s, int fd) {
...
         if (s->receive_buffer > 0) {
-                /* We first try with SO_RCVBUFFORCE, in case we have the perms for that */
-                if (setsockopt_int(fd, SOL_SOCKET, SO_RCVBUFFORCE, s->receive_buffer) < 0) {
-                        r = setsockopt_int(fd, SOL_SOCKET, SO_RCVBUF, s->receive_buffer);
-                        if (r < 0)
-                                log_unit_warning_errno(UNIT(s), r, "SO_RCVBUF failed: %m");
-                }
+                r = fd_inc_rcvbuf(fd, s->receive_buffer);
+                if (r < 0)
+                        log_unit_warning_errno(UNIT(s), r, "SO_RCVBUF/SO_RCVBUFFORCE failed: %m");
```
Comment (poettering) [inline src/core/socket.c:1063]: same as above, previous code could also lower buffer size, new code only increases.

**Comment by yuwata** [comment]
@poettering Thank you for your review. Updated. I hope all comments are addressed. PTAL.

@keszybz I think it is worth to backport this to some stable branches.

**Comment by andir** [comment]
Is there a chance this could be included in a stable systemd release or do you think this is too big of a change for the current stable version?

**Comment by keszybz** [comment]
This will be included in systemd-246.5.
