### PR TITLE
udev-builtin-net_id: ignore firmware_node/sun == 0

### LINKED ISSUE #34082: Naming conflict when booting with multiple virtio-net NICs
### systemd version the issue has been seen with

256

### Used distribution

CentOS Stream 10

### Linux kernel version used

6.10.0-rc4

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

Multiple virtio-net NICs should use udev's stable network interface names and no naming conflicts should occur.

### Unexpected behaviour you saw

However, as soon as I add second virtio-net NIC I am running into naming conflict (because both interfaces try to claim ens0 name) and one interface ends up with eth0 name. This is most likely caused by recent change https://github.com/systemd/systemd/commit/0a4ecc54cb9f2d3418b970c51bfadb69c34ae9eb. 

### Steps to reproduce the problem

1. Boot latest CentOS Stream 10 with systemd-256-12
2. Verify that single virtio NIC has ens0 interface name
3. Shutdown the VM
4. Add another virtio-net NIC
5. Boot

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by champtar**
Since ID_NET_NAME_SLOT was introduced we ignore slot == 0 https://github.com/systemd/systemd/blob/0035597a30d120f70df2dd7da3d6128fb8ba6051/src/udev/udev-builtin-net_id.c#L139

Qemu sets _SUN to PCI_SLOT() for all NICs, so _SUN is not unique. https://gitlab.com/qemu-project/qemu/-/issues/2530

In my tests with libvirt I can only set 'slot="0x00"' in interface definition, so all NICs end up with _SUN == 0, and this commit is enough to avoid the issue.

Fixes 0a4ecc54cb9f2d3418b970c51bfadb69c34ae9eb

Fixes #34082

### CODE REVIEW

File: src/udev/udev-builtin-net_id.c [hunk 1]
```diff
@@ -581,6 +581,9 @@ static int get_device_firmware_node_sun(sd_device *dev, uint32_t *ret) {
         if (r < 0)
                 return log_device_warning_errno(dev, r, "Failed to parse firmware_node/sun '%s', ignoring: %m", attr);
 
+        if (*ret == 0)
```
Comment (yuwata) [inline src/udev/udev-builtin-net_id.c]: Please update `ret` only when the function succeeds.
```c
uin32_t sun;
r = safe_atou32(attr, &sun);
if (r < 0)
        return log_device_debug_errno(...);
if (sun == 0)
        return log_device_debug_errno(...);

*ret = sun;
return 0;
```

**Review by yuwata — CHANGES_REQUESTED** [review]

File: src/udev/udev-builtin-net_id.c (hunk 1 above)
Comment (champtar) [reply src/udev/udev-builtin-net_id.c]: Done

**Review by yuwata — APPROVED** [review]
