### PR TITLE
Don't tag i2c mice as pointing sticks

### LINKED ISSUE #36677: udev: mice on i2c keyboards are labelled as pointing stick
### systemd version the issue has been seen with

257.x

### Used distribution

Fedora 41

### Linux kernel version used

6.13.5-200.nobara.fc41.x86_64

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

Seen in [libinput#1103](https://gitlab.freedesktop.org/libinput/libinput/-/issues/1103).

User has a i2c HID keyboard that results in two devices, a keyboard and a mouse. The latter is labelled `ID_INPUT_POINTINGSTICK` because of 3d7ac1c655ec40f3829543072494dcdfb92dbc6b. We'll need some heuristics to differ between real pointing sticks and mice (aside from the kernel prop which isn't always set, apparently).

Doesn't really matter since those devices never send events but it's a bug nonetheless.

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by whot**
There are no real i2c mice but there are i2c `FooBar Mouse` devices that are an artifact of how the HID kernel drivers split up event nodes. These nodes will be seen for some i2c keyboards and touchpads, depending on the HID report descriptor.

Let's not tag those as pointing sticks.

Closes #36677

### CODE REVIEW

**Comment by keszybz** [comment]
I pushed a commit to update `parse_hwdb.py`. The test should now pass.

File: hwdb.d/parse_hwdb.py [hunk 1]
```diff
@@ -75,7 +75,7 @@
 TYPES = {'mouse':    ('usb', 'bluetooth', 'ps2', '*'),
          'evdev':    ('name', 'atkbd', 'input'),
          'fb':       ('pci', 'vmbus'),
-         'id-input': ('modalias'),
+         'id-input': ('modalias', 'i2c'),
```
Comment (yuwata) [inline hwdb.d/parse_hwdb.py]: Maybe better to add `usb` and `bluetooth`?

**Review by yuwata — APPROVED** [review]

File: hwdb.d/parse_hwdb.py (hunk 1 above)
Comment (whot) [reply hwdb.d/parse_hwdb.py]: Done now and @keszybz I squashed your commit (with this change) into the first commit so the change and test change are in the same commit. sorry for the breakage

**Comment by whot** [comment]
Failure of the `TEST-70-TPM2` in the mkosi test appears unrelated.

**Review by yuwata — APPROVED** [review]
