### PR TITLE
timer: Adjust calendar timers based on monotonic timer instead of realtime

### LINKED ISSUE #16347: Timer using OnCalendar= has next elapse stuck on MANAGER_TIMESTAMP_USERSPACE
master (a68da222571789414b86d6bfa67aa7d38c63b19a)

We have some newly provisioned hosts that may boot with the wrong time (in this case, very far into the future). During boot the clock syncs. By the end of system start up, the time will be correct.

However, timers configured with `OnCalendar=` will have a next elapse/trigger time set to very far into the future (in the range of the time at boot). It seems to be caused by this code: https://github.com/systemd/systemd/blob/master/src/core/timer.c#L390-L395. Even though `v->next_elapse` is correct relative to what the time is now, `UNIT(t)->manager->timestamps[MANAGER_TIMESTAMP_USERSPACE].realtime` is in the future so next elapse gets stuck to this value.

Besides the comment in the code being incorrect (it's intended for persistent timers but affects non-persistent ones), I'm not sure checking against a stored realtime is a good idea when the clock could change at any time. But then I'm not sure what the right logic would be to fix the original problem and my current problem.

**Steps to reproduce the problem**
Not an exact repro, but close enough to see the effect:
```
# set clock forward on the host
sudo date -s "Jul 2 22:45:10 PDT 2023"

# boot a container for the test
systemd-nspawn -bi image.raw

# set clock back on the host
sudo date -s "Jul 2 22:45:10 PDT 2020"

# create and observe the timer in the container
systemd-run --unit test --on-calendar '*:0/15:0' touch /tmp/testfile
systemctl show test.timer -p NextElapseUSecRealtime # shows a time around 2023
systemd-analyze dump | grep userspace # shows the exact same time as above
```

### PR DESCRIPTION
**Pull request by filbranden**
When the RTC time at boot is off in the future by a few days, `OnCalendar=` timers will be scheduled based on the time at boot. But if the time has been adjusted since boot, the timers will end up scheduled way in the future, which may cause them not to fire as shortly or often as expected.

Update the logic so that the time will be adjusted based on monotonic time. We do that by calculating the adjusted manager startup realtime from the monotonic time stored at that time, by comparing that time with the realtime and monotonic time of the current time.

Added a test case to validate this works as expected. The test case creates a QEMU virtual machine with the clock 3 days in the future. Then we adjust the clock back 3 days, and test creating a timer with an `OnCalendar=` for every 15
minutes.

Test output without the corresponding code changes that fix the issue:

```
  Timer elapse outside of the expected 20 minute window.
    next_elapsed=1594686119
    now=1594426921
    time_delta=259198
```

With the code changes in, the test passes as expected.

Fixes #16347. cc @anitazha.

### CODE REVIEW

File: src/core/timer.c [hunk 1]
```diff
@@ -391,8 +392,9 @@ static void timer_enter_waiting(Timer *t, bool time_change) {
                          * if the scheduled time has already passed, set the time when systemd
                          * first started as the scheduled time.
                          * Also, we don't have to check t->persistent since the logic implicitly express true. */
```
Comment (anitazha) [inline src/core/timer.c]: Maybe remove this comment about `t->persistent` since this also applies to non-persistent timers?

**Comment by anitazha** [comment]
bionic "boot-and-services" are not doing so hot. Any clue if it's this PR or more widespread?

File: src/core/timer.c (hunk 1 above)
Comment (filbranden) [reply src/core/timer.c]: Done!

**Comment by filbranden** [comment]
So I decided to make this PR smaller, by only fixing the issue with the OnCalendar= timers, but not touching the manager startup timestamp.

My logic here is that if the realtime clock for some reason fluctuates and starts becoming unreliable, then the manager startup time might start to drift, which might just look odd... So I think we might need more discussion on that one before merging.

This one to me is a clear fix, since scheduling timers based on monotonic time just makes sense.

Yeah not sure why the bionic tests failed, I looked at the logs and didn't look related to my changes at all... Let's see how they do on this second run.

Done removing the comment line you mentioned. Thanks for the review!

**Comment by poettering** [comment]
I dont get this. Why is this necessary? we watch wallclock time changes, and should reschedule everything in that case. Using the monotonic clock looks like a hack to me, we should schedule wallclock events by wallclock time, and watch wallclock time changes to deal with time jumps.

There might be a bug with rescheduling things on time jumps, but I am pretty sure that should not be fixed like this...

**Comment by poettering** [comment]
hmm, look at this again, i think I grok why you want this, i.e. it's not actually about rescheduling things when time changes but it's only about figuring out the timestamps for the initial elapsing, i.e. when cross connecting the boot time timestamps to the timer scheduler. I think this is more acceptable then. So ignore my comment above.

I must say I am not too fond of the idea that we fill in a dual_timestamp here though, even though we just care about the realtime value...

**Comment by poettering** [comment]
I prepped a fix for the dual_timestamp mapping stuff I complained about, please have a look at #16536
