### PR TITLE
various service watchdog fixes

### LINKED ISSUE #9467: Watchdog timeout not honored
**systemd version the issue has been seen with**
237

**Used distribution**
 > Ubuntu 18.04

**Expected behaviour you didn't see**
 > WatchdogSec not honored

**Unexpected behaviour you saw**
 > Watchdog timeout triggered right upon running systemctl daemon-reload

**Steps to reproduce the problem**

1) Create a service with:
```
[Service]
NotifyAccess=all
ExecStart=/bin/sleep 120
```
2) Then run it with systemctl start test
3) Edit test.service and add: (in a real case it is done with a drop-in)
```
Type=notify
WatchdogSec=30s
```
4) Load the new config with systemctl daemon-reload

Actual result: watchdog timeout is triggered less than 1 second after running systemctl daemon-reload

Expected resukt: watchdog timeout should happen after 30s, i.e. the configured timeout.

### PR DESCRIPTION
**Pull request by poettering**
Fixes #9467

### CODE REVIEW

File: src/core/service.c [hunk 1]
```diff
@@ -236,48 +236,48 @@ static void service_start_watchdog(Service *s) {
...
 
-                if (IN_SET(extend_timeout_usec, 0, USEC_INFINITY))
-                        return;
+        if (!source)
+                return;
 
-                extended = usec_add(now(CLOCK_MONOTONIC), extend_timeout_usec);
+        r = sd_event_source_get_time(s->timer_event_source, &current);
+        if (r < 0) {
+                log_unit_warning_errno(UNIT(s), r, "Failed to retrieve timeout time, ignoring: %m");
```
Comment (keszybz) [inline src/core/service.c]:
```C
const char *desc;
(void) sd_event_source_get_description(s->timer_event_source, &desc);
"... for source %s", strna(desc));
```

**Comment by keszybz** [comment]
I can confirm that this fixes the reproducer in  #9467.

**Comment by poettering** [comment]
force pushed a new version. only changes are the suggested log message tweak, and the rebase on current git (which is pretty much renaming a functional call and dropping its first argument). Taking libertity to set green label given the trivial fixes.
