### PR TITLE
UnitFreezer: several cleanups

### LINKED ISSUE #31115: No PropertiesChanged signal emitted when freezing/thawing unit
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22.04.3

### Linux kernel version used

6.5.0-14-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

`PropertiesChanged` signal with the updated `FreezerState` property is emitted on
**service**: org.freedesktop.systemd1
**path**: /org/freedesktop/systemd1/unit/<masked-unit-name> (e.g. cow_2eservice)
**interface**: org.freedesktop.DBus.Properties

### Unexpected behaviour you saw

No `PropertiesChanged` signal is emitted on `org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/<masked-unit-name> org.freedesktop.DBus.Properties`

### Steps to reproduce the problem

Using the gist here: https://gist.github.com/engelmi/a1ed5af612dbecb51a27b28b83d1a33e

1. Copy the `cow.service` from gist (could be any other service, the unit name is just hardcoded in `watch.py`)
2. Copy and run python script `watch.py` from gist to watch for property changed signals on D-Bus
3. In other terminal run
   1. `systemctl start cow.service` (signals are received)
   2. `systemctl freeze cow.service` (no signal is received)
   3. `systemctl thaw cow.service` (also no signal received)
   4. `systemctl stop cow.service` (signals are received again, with Freezerstate)

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by YHNdnzj**
Fixes #31115
Related: #33083 #33269

### CODE REVIEW

**Comment by bluca** [comment]
Could you please split the last commit in a separate PR? It's a lot of changes for a bugfix

File: src/core/cgroup.c [hunk 1]
```diff
@@ -5106,7 +5106,7 @@ static int unit_cgroup_freezer_kernel_state(Unit *u, FreezerState *ret) {
 
 int unit_cgroup_freezer_action(Unit *u, FreezerAction action) {
         _cleanup_free_ char *path = NULL;
-        FreezerState target, current, next;
+        FreezerState current, next, objective;
```
Comment (bluca) [inline src/core/cgroup.c:5105]: shouldn't this change be in the "core/unit: rename freezer "target" to "objective"" commit rather than the "core/cgroup: skip freezer action wholly if current == objective" commit?

**Review by bluca — APPROVED** [review]

File: src/core/unit.c [hunk 2]
```diff
@@ -6156,26 +6156,26 @@ bool unit_can_isolate_refuse_manual(Unit *u) {
         return unit_can_isolate(u) && !u->refuse_manual_start;
 }
 
-void unit_next_freezer_state(Unit *u, FreezerAction action, FreezerState *ret, FreezerState *ret_target) {
-        Unit *slice;
-        FreezerState curr, parent, next, tgt;
+void unit_next_freezer_state(Unit *u, FreezerAction action, FreezerState *ret, FreezerState *ret_objective) {
+        FreezerState curr, parent, next, objective;
```
Comment (poettering) [inline src/core/unit.c]: maybe rename "curr" to "current" a the same time?

File: src/core/unit.c [hunk 3]
```diff
@@ -6251,6 +6251,22 @@ bool unit_can_freeze(const Unit *u) {
...
 
+void unit_set_freezer_state(Unit *u, FreezerState state) {
+        assert(u);
+        assert(state >= 0);
+        assert(state < _FREEZER_STATE_MAX);
+
+        if (u->freezer_state == state)
+                return;
+
+        log_unit_debug(u, "Freezer state changed %s -> %s",
```
Comment (poettering) [inline src/core/unit.c:6262]: very very very important: `special_glyph(SPECIAL_GLYPH_ARROW_RIGHT)`

File: src/libsystemd/sd-bus/bus-common-errors.c [hunk 4]
```diff
@@ -34,6 +34,7 @@ BUS_ERROR_MAP_ELF_REGISTER const sd_bus_error_map bus_common_errors[] = {
         SD_BUS_ERROR_MAP(BUS_ERROR_DISK_FULL,                    ENOSPC),
         SD_BUS_ERROR_MAP(BUS_ERROR_FILE_DESCRIPTOR_STORE_DISABLED,
                                                                  EHOSTDOWN),
+        SD_BUS_ERROR_MAP(BUS_ERROR_FROZEN_BY_PARENT,             ECHILD),
```
Comment (poettering) [inline src/libsystemd/sd-bus/bus-common-errors.c]: maybe EDEADLK? 

(but doesn't matter)

**Comment by poettering** [comment]
lgtm, too.

File: src/core/unit.c (hunk 3 above)
Comment (YHNdnzj) [reply src/core/unit.c:6262]: (I'd prefer not to use special glyphs in basic state change messages. None of the existing unit state change logs use this, and I think these should be readable even in the most limited environments)
