### PR TITLE
systemd: Support OOMPolicy in scope units

### LINKED ISSUE #25376: systemd built-in OOM killer (*not* systemd-oomd) kills all processes in user session/scope unit upon kernel OOM and doesn't respect OOMPolicy=
### systemd version the issue has been seen with

252.1-1-arch

### Used distribution

Arch Linux

### Linux kernel version used

6.0.7-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Normal kernel OOM killer behavior, because the kernel is able to do the job perfectly well on its own.

### Unexpected behaviour you saw

systemd will kill an entire user slice's scope unit when a process under the scope is OOM killed by the kernel, wrecking *everything* the user was doing instead of limiting the damage to a single offending process. (As a bonus, explicitly disabling this "feature" also doesn't work.)

systemd also lies to you that this will work, even with the reproduction steps below:

```
arch-vm[788]:~% systemctl --user -p DefaultOOMPolicy show
DefaultOOMPolicy=continue
```

### Steps to reproduce the problem

1) Add the following to `/etc/systemd/user.conf.d/resources.conf`:

```
[Manager]
DefaultOOMPolicy=continue
```

Alternatively, edit `/etc/systemd/user.conf` and stick `DefaultOOMPolicy=continue` there; it means the same thing.

2) Run something that eventually triggers the **kernel** OOM killer (this report has **nothing to do with** `systemd-oomd`):

```sh
#!/usr/bin/env sh

exec tail /dev/zero
```

3) After a few seconds, watch as everything you were doing disappears!

### More stuff that doesn't work

* In `/etc/systemd/system.conf`:

  ```
  [Manager]
  DefaultOOMPolicy=continue
  ```

  This will theoretically disable the idiocy for stuff under the system slice, but has no effect on the user slice.

* In `/etc/systemd/system/user-.slice.d/resources.conf` (a "drop-in" which will affect all user slice):

  ```
  [Slice]
  OOMPolicy=continue
  ```

  The `OOMPolicy` key is not recognized under `[Slice]`, while `[Scope]` and `[Service]` are completely unrecognized:

  ```
  Nov 14 15:25:27 arch-vm systemd[1]: /etc/systemd/system/user-.slice.d/resources.conf:2: Unknown key name 'OOMPolicy' in section 'Slice', ignoring.
  ```

* In `/etc/systemd/system/user@.service.d/resources.conf`:
  ```
  [Service]
  OOMPolicy=continue
  ```

  Does nothing.

* In `/etc/systemd/system/session-.scope.d/resources.conf`:

  ```
  [Scope]
  OOMPolicy=continue
  ```

  The `OOMPolicy` key is not recognized under `[Scope]`:

  ```
  Nov 14 15:22:04 arch-vm systemd[1]: /etc/systemd/system/session-.scope.d/resources.conf:2: Unknown key name 'OOMPolicy' in section 'Scope', ignoring.
  ```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Nov 14 11:53:50 arch-vm sshd[8404]: Accepted publickey for mdl from 192.168.204.1 port 54143 ssh2: RSA SHA256:LLfd0TPd0DL8Abh1c/g+Jb8nTV8i1D6BPGM/7VU6wRo
Nov 14 11:53:50 arch-vm sshd[8404]: pam_unix(sshd:session): session opened for user mdl(uid=1000) by (uid=0)
Nov 14 11:53:50 arch-vm systemd-logind[396]: New session 3 of user mdl.
Nov 14 11:53:50 arch-vm systemd[1]: Started Session 3 of User mdl.
...
Nov 14 12:34:17 arch-vm kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-3.scope,task=tail,pid=8656,uid=1000
Nov 14 12:34:17 arch-vm kernel: Out of memory: Killed process 8656 (tail) total-vm:25725656kB, anon-rss:25720108kB, file-rss:4kB, shmem-rss:0kB, UID:1000 pgtables:50388kB oom_score_adj:0
Nov 14 12:34:17 arch-vm systemd[1]: session-3.scope: A process of this unit has been killed by the OOM killer.
Nov 14 12:34:17 arch-vm systemd[1]: session-3.scope: Killing process 8404 (sshd) with signal SIGKILL.
Nov 14 12:34:17 arch-vm systemd[1]: session-3.scope: Killing process 8409 (sshd) with signal SIGKILL.
Nov 14 12:34:17 arch-vm systemd[1]: session-3.scope: Killing process 8411 (zsh) with signal SIGKILL.
Nov 14 12:34:17 arch-vm systemd[1]: session-3.scope: Killing process 8656 (tail) with signal SIGKILL.
Nov 14 12:34:17 arch-vm systemd-logind[396]: Session 3 logged out. Waiting for processes to exit.
Nov 14 12:34:18 arch-vm systemd[1]: session-3.scope: Failed with result 'oom-kill'.
Nov 14 12:34:18 arch-vm systemd[1]: session-3.scope: Consumed 16.369s CPU time.
Nov 14 12:34:18 arch-vm systemd-logind[396]: Removed session 3.
```

### PR DESCRIPTION
**Pull request by drvink**
Closes #25376.

### CODE REVIEW

**Comment by poettering** [comment]
this adds the property, but doesn't hook it up in any way? what's the point of that?

File: src/core/scope.c [hunk 1]
```diff
@@ -194,6 +195,9 @@ static int scope_add_extras(Scope *s) {
         if (r < 0)
                 return r;
 
+        if (s->oom_policy < 0)
+                s->oom_policy = s->cgroup_context.delegate ? OOM_CONTINUE : UNIT(s)->manager->default_oom_policy;
```
Comment (poettering) [inline src/core/scope.c:199]: you need propagate this into `s->cgroup_context.memory_oom_group` too. The way service.c does it

File: src/core/scope.c [hunk 2]
```diff
@@ -635,7 +641,9 @@ static void scope_notify_cgroup_oom_event(Unit *u, bool managed_oom) {
         else
                 log_unit_debug(u, "Process of control group was killed by the OOM killer.");
 
-        /* This will probably need to be modified when scope units get an oom-policy */
+        if (s->oom_policy == OOM_CONTINUE)
+                return;
+
```
Comment (poettering) [inline src/core/scope.c:648]: what about OOM_STOP?

Comment (drvink) [reply src/core/scope.c:648]: If the policy is OOM_STOP, then the unit will be terminated, just like before. (As I said in the issue thread, I don't think this is a good default or even a useful behavior, but unless you want to change it, this edit does not change the old behavior, so the code is fine.)

Comment (poettering) [reply src/core/scope.c:648]: well, what I am saying is that if OOM_STOP is set we should not enter SCOPE_STOP_SIGKILL right-away as the code will do now, but SCOPE_STOP_SIGTERM instead.

Comment (drvink) [reply src/core/scope.c:648]: ah, yes. I'll fix this and the group_context issue in a bit. Thanks.

**Comment by poettering** [comment]
(and I'd be fine if the login session scopes are switched over to use OOMPolicy=continue, if you want to add a second commit to this PR. Just add another sd_bus_message() line to manager_start_scope() in src/login/logind-dbus.c)

**Comment by drvink** [comment]
> I'd be fine if the login session scopes are switched over to use OOMPolicy=continue

Cool. I'll add it. This is definitely the right thing to do--I could imagine scenarios where someone might want the rest of a scope terminated if one process in it gets OOM killed, but definitely not for their login sessions!

Also, if you can give me a hint for what needs to be done in order to make `systemd-run --scope -p OOMPolicy=foo` work, it probably makes sense to do it as part of this PR.

**Comment by drvink** [comment]
I made the requested changes. Now all `OOMPolicy` modes work as expected (continue, stop, kill), and the policy can also be selected for a transient scope or service when using `systemd-run`.

File: src/shared/bus-unit-util.c [hunk 3]
```diff
@@ -2142,6 +2142,10 @@ static int bus_append_scope_property(sd_bus_message *m, const char *field, const
         if (STR_IN_SET(field, "User", "Group"))
                 return bus_append_string(m, field, eq);
 
+        if (streq(field, "OOMPolicy")) {
```
Comment (anitazha) [inline src/shared/bus-unit-util.c]: nit: you can add `OOMPolicy` to the end of the STR_IN_SET macro above since they return the same thing

File: src/shared/bus-unit-util.c [hunk 4]
```diff
@@ -2142,6 +2142,10 @@ static int bus_append_scope_property(sd_bus_message *m, const char *field, const
...
+                return bus_append_string(m, field, eq);
+        }
```
Comment (daandemeyer) [inline src/shared/bus-unit-util.c]: Coding style issue: No braces around single line if statements

**Review by anitazha — COMMENTED** [review]
Overall lgtm. Thanks for working on this

File: src/shared/bus-unit-util.c (hunk 3 above)
Comment (drvink) [reply src/shared/bus-unit-util.c]: Do you really want to? [These lines above](https://github.com/systemd/systemd/pull/25385/files/3c83984e3f366ef8d604a6ad09ad82112f08663c#diff-67cfddb9602e31232220c4c28dcc990d00fe78d33ae49be3c9fb7baefff8ce03R2131-R2138) could use STR_IN_SET too, but they aren't.

Comment (anitazha) [reply src/shared/bus-unit-util.c]: Yea I noticed that and was going to update it outside of this PR. I think it would make it more stylistically consistent with the other parts of this file. You're welcome to update both parts to STR_IN_SET if you're inclined

Comment (drvink) [reply src/shared/bus-unit-util.c]: If you plan to clean it up in a style commit I'll just leave it as it is here, for clarity.

**Comment by poettering** [comment]
thanks! lgtm!

**Comment by poettering** [comment]
CI failure appears unrelated. Merging.

**Comment by drvink** [comment]
@keszybz Ah shit, sorry. I did find the gperf input and manpage-related scripts while trying to cover all the separate places that need to be touched in the code and docs with regard to unit directives, but ended up forgetting those two before having decided my patch, as the author of a famous mail filtering tool once remarked in a comment at the top of a file he had just written, "seems to be bug-free". ;)
