### PR TITLE
locale: re-read configuration files if necessary

### LINKED ISSUE #8491: localectl doesn’t rewrite keymap files when config doesn’t change, even if files were deleted in the meantime
### Submission type

 - Bug report

### systemd version the issue has been seen with

238

### Used distribution

Arch Linux

### Actual behaviour

If `localectl set-x11-keymap` or `localectl set-keymap` is called two times with the same arguments and that `/etc/X11/xorg.conf.d/00-keyboard.conf` or `/etc/vconsole.conf` is deleted between the two calls, the files are not recreated by localed, leaving the system without keymap configuration.

### Steps to reproduce the problem

```
❯ localectl set-x11-keymap fr
❯ cat /etc/X11/xorg.conf.d/00-keyboard.conf 
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# instruct systemd-localed to update it.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "fr"
EndSection
❯ cat /etc/vconsole.conf 
KEYMAP=fr
❯ rm /etc/X11/xorg.conf.d/00-keyboard.conf
❯ rm /etc/vconsole.conf
❯ localectl set-x11-keymap fr
❯ env LANG=C cat /etc/X11/xorg.conf.d/00-keyboard.conf 
cat: /etc/X11/xorg.conf.d/00-keyboard.conf: No such file or directory
```

The `set-keymap` command has the same problem.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #8491 and #6070.

### CODE REVIEW

File: src/locale/localed.c [hunk 1]
```diff
@@ -33,6 +33,42 @@
 
 static Hashmap *polkit_registry = NULL;
 
+static int locale_read_data_once(Context *c, sd_bus_message *m) {
+        static sd_bus_message *_m = NULL;
+
```
Comment (keszybz) [inline src/locale/localed.c]: Hmm, this works, true. But maybe it would be better to store this in Context instead, i.e. add a `sd_bus_message *_last_read_for_message`? Context is only used in localed and one test file, so it seems OK to modify the data structure. Then this check could be moved to `locale_read_data`, simplifying the whole thing.

**Comment by yuwata** [comment]
@keszybz Thank you for the comments and suggestions. I have some questions.
> we store the mtime of the file on disk whenever it is read or written by us, and when asked to write the config that is not changed we compare the mtime to our cached timestamp.

Sounds better. I will update this to check mtime.

> changing how localed handles config files that change underneath it.

Yeah, does it cause something harmful?

> To reload the changed data from disk, user would have to call reload explicitly.

Why we need to request to user such task?

**Comment by keszybz** [comment]
The documented way to adjust configuration at runtime is to call the dbus apis. localed is special in this regard that it doesn't use the information for anything on it's own. So in this particular case, we could say that we'll re-read the configuration automatically wherever queried. This would work, as long as we ignore the possibility of the file being written by something else, with partial contents at the time of reading. But still, this would make localed different than other daemons and less predictable, for no particular benefit that I can see.

**Comment by yuwata** [comment]
> the possibility of the file being written by something else, with partial contents at the time of reading

Yeah, but I think such a race can be occur everywhere we load any configuration...

> no particular benefit

If localed reads config files when necessary, then, e.g. if we perform the following operation,
```
$ localectl status
$ sudo echo 'LANG=en_US.UTF-8' > /etc/locale.conf
$ localectl status
```
the second output can show the correct locale setting. This is a similar situation reported in #1329. So, I think we should always check the current settings, by using mtime in this case.

**Comment by yuwata** [comment]
@keszybz Updated.
- Use mtime instead of cached sd_bus_message.
- Now the configuration files are re-read only if they are modified directly. So, if no one touch the configuration files, then they are read only once.

PTAL. Thank you.

File: src/locale/localed.c [hunk 2]
```diff
@@ -193,6 +205,58 @@ static int property_get_locale(
...
+        Context *c = userdata;
+        int r;
+
+        r = vconsole_read_data(c);
+        if (r < 0)
+                return r;
+
+        if (streq(property, "VConsoleKeymap"))
+                return sd_bus_message_append_basic(reply, 's', c->vc_keymap);
+        else if (streq(property, "VConsoleKeymapToggle"))
```
Comment (keszybz) [inline src/locale/localed.c:226]: I don't get this part. It's quite a lot of code to implement lazy loading of a very-very small config file. With the changed code, it's possible for localed to suddenly fail in the middle of operations, if it fails to read one of the files. I think it was cleaner and simpler to read the data when starting.

**Comment by yuwata** [comment]
Updated. Now the cache using sd_bus_message comes again. So, `stat()` for each config file is called once per bus transaction.

File: src/locale/localed.c (hunk 2 above)
Comment (yuwata) [reply src/locale/localed.c:226]: Now each `*_read_data()` is effectively called once per bus transaction.

**Comment by yuwata** [comment]
Updated.
- Make `locale_write_data()` not read the configuration file before writing data.
- Cleanup `method_set_locale()`. Now it writes data only when it is necessary.
- Add a fallback logic to fix #6070.

**Comment by yuwata** [comment]
Also, man page is updated.

File: src/locale/keymap-util.c [hunk 3]
```diff
@@ -314,15 +375,24 @@ int vconsole_write_data(Context *c) {
...
                 return 0;
         }
 
-        return write_env_file_label("/etc/vconsole.conf", l);
+        r = write_env_file_label("/etc/vconsole.conf", l);
+        if (r < 0)
+                return r;
+
+        if (stat("/etc/vconsole.conf", &st) >= 0)
+                c->vc_mtime = timespec_load(&st.st_mtim);
```
Comment (poettering) [inline src/locale/keymap-util.c:387]: hmm, i'd prefer if we'd actually read the mtime from the file we just wrote as last step before closing its fd, otherwise this has such a "racy" feeling to it... I figure doing that would not be trivial, hence maybe it is OK this way, but it sure would be prettier if we somehow made this work one day (for example, have write_env_file_label() and friends optionally return the final mtime after it completed writing)

**Comment by poettering** [comment]
regarding the philosophical question of "reload configration files automatically or not". I think it's important to notice that localed's only purpose is to read and write configuration files, it's very different hence from let's say journald which reads its config file and consumes it. I think this distinction should not be underetimated, and yes i think making localed honour modified /etc/vconsole.conf makes a ton of sense. Or to say it differently: if we had some other daemon which purely consumes /etc/vconsole.conf then it really shouldn't do any auto-reload magic, but localed is not like that...

hence I think this should go in...
