### PR TITLE
resolved: fix strange function recursion

### LINKED ISSUE #19651: resolvectl dns reset is not effective
With recent git tip:

```console
$ sudo resolvectl dns hub0 1.1.1.1 1.0.0.1
$ resolvectl dns
Global:
Link 2 (hub0): 1.1.1.1 1.0.0.1
Link 3 (enp0s31f6):
Link 4 (wwp0s20f0u2i12):
Link 5 (wlp4s0): 8.8.4.4 8.8.8.8
Link 6 (virbr0):
$ sudo busctl call org.freedesktop.resolve1 /org/freedesktop/resolve1/link/_32 org.freedesktop.resolve1.Link SetDNS "a(iay)" 0
$ resolvectl dns
Global:
Link 2 (hub0): 1.0.0.1
Link 3 (enp0s31f6):
Link 4 (wwp0s20f0u2i12):
Link 5 (wlp4s0): 8.8.4.4 8.8.8.8
Link 6 (virbr0):
```

In the logs:
```
May 18 19:59:59 krowka systemd-resolved[2477]: hub0: Bus client set DNS server list to: 1.1.1.1, 1.0.0.1
May 18 20:00:06 krowka systemd-resolved[2477]: hub0: Bus client reset DNS server list.
```

https://bugzilla.redhat.com/show_bug.cgi?id=1840790

### PR DESCRIPTION
**Pull request by keszybz**
In dns_server_unlink_marked() and dns_server_mark_all() we done recursively.
People might have dozens of servers defined, and it's better to avoid recursion
when a simple loop suffices.

dns_server_unlink_marked() would only unmark the first marked server.

Fixes #19651.

### CODE REVIEW

File: src/resolve/resolved-dns-server.c [hunk 1]
```diff
@@ -805,30 +805,30 @@ void dns_server_unlink_all(DnsServer *first) {
...
-void dns_server_mark_all(DnsServer *first) {
-        if (!first)
-                return;
+        return changed;
+}
 
-        first->marked = true;
-        dns_server_mark_all(first->servers_next);
+void dns_server_mark_all(DnsServer *server) {
+        while (server) {
```
Comment (bluca) [inline src/resolve/resolved-dns-server.c:828]: `for (; server; server = server->servers_next)` to save a whopping whole line and two brackets? But just bikeshedding, doesn't matter much

**Review by bluca — APPROVED** [review]
LGTM
