### PR TITLE
process-util: update the end pointer of the process name on rename

### LINKED ISSUE #6492: process-util: memory corruption in process renaming
### Submission type

 - Bug report

### systemd version the issue has been seen with

> at least 233 and 234

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> The process responsible for PAM management is renamed to "(sd-pam)".

### In case of bug report: Unexpected behaviour you saw

> The process name is corrupted to "(sd-pam)TERM=linux" or variations such as "(sd-pamTERM=linux)").

### In case of bug report: Steps to reproduce the problem

    [Unit]
    Description=Testcase for PAM
    
    [Service]
    ExecStart=/bin/sleep infinity
    User=nobody
    PAMName=login

```
$ systemd-cgls
Control group /:
-.slice
├─user.slice
│ ├─user-99.slice
│ │ ├─user@99.service
│ │ │ └─init.scope
│ │ │   ├─1167 /usr/lib/systemd/systemd --user
│ │ │   └─1168 (sd-pam)
│ │ └─session-c6.scope
│ │   ├─1166 /bin/sleep infinity
│ │   └─1173 (sd-pam)TERM=linux
…
```

### PR DESCRIPTION
**Pull request by joukewitteveen**
This fixes #6492

As observed by @poettering, we only updated the end pointer on the first call to `rename_process`.

### CODE REVIEW

File: src/basic/process-util.c [hunk 1]
```diff
@@ -351,9 +351,14 @@ int rename_process(const char name[]) {
 
                 mm = nn;
                 mm_size = nn_size;
-        } else
+        } else {
                 strncpy(mm, name, mm_size);
 
+                /* Update the end pointer, continuing regardless of any failure. */
+                if (prctl(PR_SET_MM, PR_SET_MM_ARG_END, (unsigned long) mm + l + 1, 0, 0) < 0)
+                        log_debug_errno(errno, "PR_SET_MM_ARG_END failed, proceeding without: %m");
```
Comment (evverx) [inline src/basic/process-util.c:358]: @joukewitteveen, thank you for fixing this. Is there any chance you could add a test calling `rename_process` two times in a row to `test-process-util`?

Comment (evverx) [reply src/basic/process-util.c:358]: I'm not sure `strncpy` and `prctl` should be called when a process doesn't have enough privileges. I've just added a simple test that does something like this:
```sh
rename_process("abc")
fork()
....
setresuid(99, 99, 99)
rename_process("abcde")
```
. I see the following:
```sh
cmdline = <abc>
PR_SET_MM_ARG_END failed, proceeding without: Operation not permitted
cmdline = <abcdHOSTNAME=localhost.localdomain>
```
and I don't think that this is correct. The `if` branch checks that the result of `getuid` is equal to `0` before calling `strncpy` and `prctl`.

**Comment by joukewitteveen** [comment]
Thanks! I fixed the `euid` check and added some tests.

File: src/basic/process-util.c [hunk 2]
```diff
@@ -312,19 +312,18 @@ int rename_process(const char name[]) {
...
-        if (mm_size < l+1) {
+
+        /* Let's not bother with this if we don't have euid == 0. Strictly speaking if people do weird stuff with
+         * capabilities this could work even for euid != 0, but our own code generally doesn't do that, hence let's
+         * use this as quick bypass check, to avoid calling mmap() if PR_SET_MM_ARG_{START,END} fails with EPERM later
+         * on anyway. After all geteuid() is dead cheap to call, but mmap() is not. */
+        if (geteuid() != 0) {
+                log_debug("Skipping PR_SET_MM, as we don't have privileges.");
+
+        } else if (mm_size < l+1) {
```
Comment (evverx) [inline src/basic/process-util.c]: The braces and the empty line don't seem to be needed here.

File: src/test/test-process-util.c [hunk 3]
```diff
@@ -355,50 +355,80 @@ static void test_get_process_cmdline_harder(void) {
...
-        log_info("cmdline = <%s>", cmdline);
-        assert_se(strneq(p, cmdline, strlen("test-process-util")));
-        assert_se(startswith(p, cmdline));
+        /* we cannot expect cmdline to be renamed properly without privileges */
+        if (geteuid() == 0) {
+                log_info("cmdline = <%s>", cmdline);
+                assert_se(strneq(p, cmdline, strlen("test-process-util")));
+                assert_se(startswith(p, cmdline));
+        } else
+                log_info("cmdline = <%s> (not verified)", cmdline);
```
Comment (evverx) [inline src/test/test-process-util.c:387]: It would probably make sense to check that `rename_process` doesn't really change the command line when it is run as an unprivileged user. Not that it matters, though.

File: src/basic/process-util.c [hunk 4]
```diff
@@ -312,19 +312,18 @@ int rename_process(const char name[]) {
         /* Third step, completely replace the argv[] array the kernel maintains for us. This requires privileges, but
          * has the advantage that the argv[] array is exactly what we want it to be, and not filled up with zeros at
          * the end. This is the best option for changing /proc/self/cmdline. */
-        if (mm_size < l+1) {
+
+        /* Let's not bother with this if we don't have euid == 0. Strictly speaking if people do weird stuff with
+         * capabilities this could work even for euid != 0, but our own code generally doesn't do that, hence let's
+         * use this as quick bypass check, to avoid calling mmap() if PR_SET_MM_ARG_{START,END} fails with EPERM later
+         * on anyway. After all geteuid() is dead cheap to call, but mmap() is not. */
+        if (geteuid() != 0) {
```
Comment (evverx) [inline src/basic/process-util.c]: This check doesn't seem to be sufficient. A command line still can be corrupted if the process calling `rename_process` doesn't have the `CAP_SYS_RESOURCE` capability. The following patch can be used to trigger the corruption:
```diff
diff --git a/src/test/test-process-util.c b/src/test/test-process-util.c
index e7c9766..6319808 100644
--- a/src/test/test-process-util.c
+++ b/src/test/test-process-util.c
@@ -32,6 +32,7 @@

 #include "alloc-util.h"
 #include "architecture.h"
+#include "capability-util.h"
 #include "fd-util.h"
 #include "log.h"
 #include "macro.h"
@@ -423,6 +424,7 @@ static void test_rename_process_multi(void) {

         /* child */
         test_rename_process_now("one", 1);
+        drop_capability(CAP_SYS_RESOURCE);
         test_rename_process_now("more", 0); /* longer than "one", hence truncated */
         setresuid(99, 99, 99);
         test_rename_process_now("time!", 0);
```
I'm not sure what to do about it. The function might check that the process has the `CAP_SYS_RESOURCE` capability. Unfortunately, that won't work inside a user namespace.

Comment (evverx) [reply src/basic/process-util.c]: Anyway, the PR fixes the real life issue, so I think it can be merged as is after removing the braces and the empty line.

Comment (evverx) [reply src/basic/process-util.c]: Alternatively, `PR_SET_MM` can be removed altogether because long strings have never been passed to `rename_process` yet :-)

Comment (joukewitteveen) [reply src/basic/process-util.c]: I have updated the comment reflecting your remark.
Agreed, the fix is far from perfect, but it is a real improvement.

File: src/test/test-process-util.c (hunk 3 above)
Comment (joukewitteveen) [reply src/test/test-process-util.c:387]: Oddly enough, when I run the test as an ordinary user, I get
```
Skipping PR_SET_MM, as we don't have privileges.
comm = <one>
cmdline = <one> (not verified)
Skipping PR_SET_MM, as we don't have privileges.
comm = <more>
cmdline = <mor> (not verified)
Skipping PR_SET_MM, as we don't have privileges.
comm = <time!>
cmdline = <tim> (not verified)
Skipping PR_SET_MM, as we don't have privileges.
comm = <0>
cmdline = <0> (not verified)
```
while running as root gives
```
comm = <one>
cmdline = <one>
comm = <more>
cmdline = <more>
Skipping PR_SET_MM, as we don't have privileges.
comm = <time!>
cmdline = <more> (not verified)
Skipping PR_SET_MM, as we don't have privileges.
comm = <0>
cmdline = <more> (not verified)
```
At least the test now succeeds both ways.

Comment (evverx) [reply src/test/test-process-util.c:387]: That is true that the test succeeds, but it would also succeed if I removed `geteuid() != 0` from `rename_process`. In other words, `test-process-util` calls `setresuid` and `rename_process` to reproduce the memory corruption which had been possible before `geteuid` was placed at the top of the `if`, but `test-process-util` doesn't test that `rename_process` doesn't corrupt memory after calling `setresuid`.

**Comment by evverx** [comment]
@joukewitteveen, thank you.
