### PR TITLE
in-addr: improve log message for e.g. [DHCPv4] AllowList=

### LINKED ISSUE #30107: AllowList= option from [DHCPv4] section in a .network file doesn't work
### systemd version the issue has been seen with

252.5

### Used distribution

Ubuntu 23.04

### Linux kernel version used

6.2.0

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

I have a running DHCP server in my LAN.
I've configured a AllowList= option below a [DHCPv4] section in a .network file from a client machine with another,  **inexistent** DHCP Server IP address
What I expected was Systemd-networkd would warn me about the impossibility of getting any valid network data (maybe at Journal, maybe though an console error...) because that bad DHCP server, but, instead, it gets network data from my other running DHCP server without any problem.

### Steps to reproduce the problem

Add for instance this line into your .network file ...

```
[Match]
Name=yourinterfacename
[Network]
DHCP=yes
AllowList=whatevernonexistantIP
```

... and restart Systemd-networkd. If you have a valid DHCP server, you'll continue to get valid network data from it, instead of blocking it.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Closes #30107.

### CODE REVIEW

File: src/shared/in-addr-prefix-util.c [hunk 1]
```diff
@@ -312,7 +312,8 @@ int config_parse_in_addr_prefixes(
                         }
                         if (r < 0) {
                                 log_syntax(unit, LOG_WARNING, filename, line, r,
-                                           "Address prefix is invalid, ignoring assignment: %s", word);
+                                           "Invalid address prefix is specified to [%s] %s=, ignoring assignment: %s",
```
Comment (bluca) [inline src/shared/in-addr-prefix-util.c]: "specified in"

**Review by bluca — APPROVED** [review]
