### PR TITLE
hostnamed: expose FirmwareDate as uint64 in dbus

### LINKED ISSUE #25679: hostnamed firmware date property needs love before release
### systemd version the issue has been seen with

main

### Used distribution

fedora

### Linux kernel version used

yeah

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

The firmware date field should be returned as UNIX time.

### Unexpected behaviour you saw

it's literally the DMI time the kernel formats.

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by jelly**
Offer the firmware date as an epoch instead of the literal DMI string.

Closes #25679

### CODE REVIEW

File: src/hostname/hostnamed.c [hunk 1]
```diff
@@ -250,8 +250,27 @@ static int get_firmware_vendor(char **ret) {
...
+static int get_firmware_date(uint64_t *ret) {
+         const char *k;
+         struct tm tm;
+         time_t v;
+         _cleanup_free_ char *bios_date = NULL;
+         int r;
+
+         r = get_hardware_firmware_data("bios_date", &bios_date);
+         if (r <= 0)
+                 return r;
```
Comment (yuwata) [inline src/hostname/hostnamed.c]: Please set 'a default' value on `r == 0`:
```c
r = get_hardware_firmware_data(...);
if (r < 0)
        return r;
if (r == 0) {
        *ret = USEC_INFINITY;
        return 0;
}
```

File: src/hostname/hostnamed.c [hunk 2]
```diff
@@ -250,8 +250,27 @@ static int get_firmware_vendor(char **ret) {
...
+
+         k = strptime(bios_date, "%m/%d/%Y", &tm);
```
Comment (yuwata) [inline src/hostname/hostnamed.c]: I think it is better to use `parse_timestamp()`, though it does not support `/` as a separator. So, how about to first replace `/` with `-`, and use `parse_timestamp()`?

File: src/hostname/hostnamed.c [hunk 3]
```diff
@@ -250,8 +250,27 @@ static int get_firmware_vendor(char **ret) {
          return get_hardware_firmware_data("bios_vendor", ret);
 }
 
-static int get_firmware_date(char **ret) {
-         return get_hardware_firmware_data("bios_date", ret);
+static int get_firmware_date(uint64_t *ret) {
```
Comment (yuwata) [inline src/hostname/hostnamed.c]: Please use `usec_t` instead of `uint64_t`, even though these are equivalent.

File: src/hostname/hostnamed.c [hunk 4]
```diff
@@ -661,11 +680,11 @@ static int property_get_firmware_date(
                 void *userdata,
                 sd_bus_error *error) {
 
-        _cleanup_free_ char *firmware_date = NULL;
+        uint64_t firmware_date = 0;
```
Comment (yuwata) [inline src/hostname/hostnamed.c]: Please use `usec_t`. Also, I'd like to make the default value `USEC_INFINITY`, instead of `0`.

File: src/hostname/hostnamed.c [hunk 5]
```diff
@@ -1189,7 +1208,8 @@ static int method_get_hardware_serial(sd_bus_message *m, void *userdata, sd_bus_
 static int method_describe(sd_bus_message *m, void *userdata, sd_bus_error *error) {
         _cleanup_free_ char *hn = NULL, *dhn = NULL, *in = NULL, *text = NULL,
                 *chassis = NULL, *vendor = NULL, *model = NULL, *serial = NULL, *firmware_version = NULL,
-                *firmware_vendor = NULL, *firmware_date = NULL;
+                *firmware_vendor = NULL;
+        uint64_t firmware_date = 0;
```
Comment (yuwata) [inline src/hostname/hostnamed.c]: `usec_t` and `USEC_INFINITY`

File: src/hostname/hostnamed.c [hunk 6]
```diff
@@ -1277,7 +1297,7 @@ static int method_describe(sd_bus_message *m, void *userdata, sd_bus_error *erro
                                        JSON_BUILD_PAIR("HardwareSerial", JSON_BUILD_STRING(serial)),
                                        JSON_BUILD_PAIR("FirmwareVersion", JSON_BUILD_STRING(firmware_version)),
                                        JSON_BUILD_PAIR("FirmwareVendor", JSON_BUILD_STRING(firmware_vendor)),
-                                       JSON_BUILD_PAIR("FirmwareDate", JSON_BUILD_STRING(firmware_date)),
+                                       JSON_BUILD_PAIR("FirmwareDate", JSON_BUILD_UNSIGNED(firmware_date)),
```
Comment (yuwata) [inline src/hostname/hostnamed.c]: Please use `JSON_BUILD_PAIR_FINITE_USEC()`.

**Review by yuwata — CHANGES_REQUESTED** [review]

**Comment by yuwata** [comment]
Could you also add a brief test for the feature at tests/units/testsuite-71.sh?

File: src/hostname/hostnamed.c [hunk 7]
```diff
@@ -250,8 +250,27 @@ static int get_firmware_vendor(char **ret) {
...
+         _cleanup_free_ char *bios_date = NULL;
+         int r;
+
+         r = get_hardware_firmware_data("bios_date", &bios_date);
+         if (r <= 0)
+                 return r;
+
+         k = strptime(bios_date, "%m/%d/%Y", &tm);
+         if (!k || *k)
+                 return r;
```
Comment (poettering) [inline src/hostname/hostnamed.c]: honestly, I'd just write a manual parser, i.e.:

```c
const char *p = bios_date;
r = extract_many_words(&p, "/", EXTRACT_DONT_COALESCE_SEPARATORS, &month, &day, &year);
if (r < 0)
        return r;
if (r != 3) /* less than three args read? */
        return -EINVAL;
if (!isempty(p)) /* more left in the string? */
        return -EINVAL;
 
unsigned m, d, y;
r = safe_atou(month, &m);
if (r < 0) 
        return r;
if (m < 1 || m > 12)
        return -EINVAL;

r = safe_atou(day, &d);
if (r < 0)
        return r;
if (d < 1 || d > 31)
        return -EINVAL;

r = safe_atou(year, &y);
if (r < 0)
        return r;
if (y < 1970 || y > (usigned) INT_MAX)
        return -EINVAL;  

tm = (struct tm) {
        .tm_mday = d,
        .tm_mon = m,
        .tm_year = y,
};
v = timegm(&tm);
if (v == (time_t) -1))
        return -errno;
if (tm.tm_mday != (int) d || tm.tm_mon != (int m) || tm.tm_year != (int) y)
        return -EINVAL; /* date was not normalized? (e.g. "30th of feb") */

File: src/hostname/hostnamed.c [hunk 8]
```diff
@@ -250,8 +250,27 @@ static int get_firmware_vendor(char **ret) {
...
+
+        v = timegm(&tm);
+        if (v == (time_t) -1)
+                return r;
```
Comment (poettering) [inline src/hostname/hostnamed.c:279]: `return -errno` here as timegm() returns the error in that.

File: src/hostname/hostnamed.c [hunk 9]
```diff
@@ -250,8 +250,27 @@ static int get_firmware_vendor(char **ret) {
...
+
+        *ret = (uint64_t) v * USEC_PER_SEC;
```
Comment (poettering) [inline src/hostname/hostnamed.c]: maybe add extra safety overflow check here first:

```c
if (v > UINT64_MAX / USEC_PER_SEC) /* overflow check */
        return -EINVAL;
```

just in case somebody specifies some ridiculously large year there.

File: src/hostname/hostnamed.c (hunk 2 above)
Comment (jelly) [reply src/hostname/hostnamed.c]: Sounds good! But I'd have to make it support "%m-%d-%Y", which I did, probably should also do that for other variants I suppose?

File: src/hostname/hostnamed.c [hunk 10]
```diff
@@ -250,8 +250,27 @@ static int get_firmware_vendor(char **ret) {
...
+                 return r;
+
+         k = strptime(bios_date, "%m/%d/%Y", &tm);
+         if (!k || *k)
+                 return r;
+
+        v = timegm(&tm);
+        if (v == (time_t) -1)
+                return r;
+
```
Comment (poettering) [inline src/hostname/hostnamed.c:309]: timegm() and friends will silently mangle the data in the `struct tm` if not normalized (i.e. "feb 30" is specified or garbage like that). I think we should check for that, i.e. compare if the values we care about still match what we passed in. if we not then the input was apparently garbage, and we should return an error

File: src/hostname/hostnamed.c (hunk 7 above)
Comment (jelly) [reply src/hostname/hostnamed.c]: I could, locally just started using `parse_timestamp` and extended it to support `12-31-2021`. That seems to me better then writing another parser? If @yuwata agrees with the code above I'm happy to update the PR.

**Comment by jelly** [comment]
> Could you also add a brief test for the feature at tests/units/testsuite-71.sh?

I guess it makes sense to expose it then in hostnamectl? As alternative I can just use `jq` with `hostnamectl --json=short`, but I am not 100% sure if I understand if `test/units/testsiute-71.sh` runs as root in a container. This is required to set a predictable `bios_date` in `/sys/class/dmi/id`.

I noticed the unit tests fail with  `org.freedesktop.hostname1.xml:   24/30 OUTDATED`, so I assume I need to update `man/org.freedesktop.hostname1.xml`.

File: src/hostname/hostnamed.c (hunk 7 above)
Comment (poettering) [reply src/hostname/hostnamed.c]: parse_timestamp() can parse a lot of stuff. I think we should be more restrictive here, and just parse exactly what we can expect.

parse_timestamp() will happily parse timezones and µs and whatnot, none of which we should accept here I think.

this data is ultimately from a low-quality source: the firmware, hence I think we should be careful here, and better suppress garbage data than to parse it incorrectly.

Comment (yuwata) [reply src/hostname/hostnamed.c]: I do not have strong opinion over that. But if you provide a restrictive parser, then please add tests for it.

**Comment by bluca** [comment]
> > Could you also add a brief test for the feature at tests/units/testsuite-71.sh?
> 
> I guess it makes sense to expose it then in hostnamectl? As alternative I can just use `jq` with `hostnamectl --json=short`, but I am not 100% sure if I understand if `test/units/testsiute-71.sh` runs as root in a container. This is required to set a predictable `bios_date` in `/sys/class/dmi/id`.
> 
> I noticed the unit tests fail with `org.freedesktop.hostname1.xml: 24/30 OUTDATED`, so I assume I need to update `man/org.freedesktop.hostname1.xml`.

Having a test that exercises the code paths, even without validating the output, is already good as it allows sanitizers to detect crashes/leaks/etc. So even if you can't have a reliable date to parse, it's still worth adding test coverage

File: src/hostname/hostnamectl.c [hunk 11]
```diff
@@ -304,6 +314,7 @@ static int show_all_names(sd_bus *bus) {
                 { "HardwareVendor",            "s", NULL, offsetof(StatusInfo, hardware_vendor)  },
                 { "HardwareModel",             "s", NULL, offsetof(StatusInfo, hardware_model)   },
                 { "FirmwareVersion",           "s", NULL, offsetof(StatusInfo, firmware_version) },
+                { "FirmwareDate",              "t", NULL, offsetof(StatusInfo, firmware_date) },
```
Comment (poettering) [inline src/hostname/hostnamectl.c]: doesn't matter, but please align `}` at the end

File: src/hostname/hostnamed.c [hunk 12]
```diff
@@ -250,8 +250,30 @@ static int get_firmware_vendor(char **ret) {
...
+                 *ret = USEC_INFINITY;
+                 return 0;
+         }
+
+         for (size_t i = 0; i <= strlen(bios_date); i++) {
+                 if (bios_date[i] == '/')
+                         bios_date[i] = '-';
+         }
+
+        r = parse_timestamp(bios_date, ret);
```
Comment (poettering) [inline src/hostname/hostnamed.c]: please don't use parse_timestamp(), we should be strict here, and only accept a strict format, with the expected syntax.

in particular as parse_timestamp expects the format `YYYY-MM-DD` while the sysfs property outputs `MM/DD/YYYY` no matter of converting `/` to `-` is going to rearrange the numbers for you...

Comment (jelly) [reply src/hostname/hostnamed.c]: Applied the parsing suggestion, still an issue left with `hostnamectl` although the timestamp returned via DBUS looks correct.

File: src/hostname/hostnamectl.c [hunk 13]
```diff
@@ -52,6 +53,7 @@ typedef struct StatusInfo {
         const char *hardware_vendor;
         const char *hardware_model;
         const char *firmware_version;
+        const usec_t firmware_date;
```
Comment (poettering) [inline src/hostname/hostnamectl.c]: drop the "const" btw. that only is relevant for pointers, and useless otherwise.

File: src/hostname/hostnamed.c (hunk 1 above)
Comment (poettering) [reply src/hostname/hostnamed.c]: not addressed yet

Comment (poettering) [reply src/hostname/hostnamed.c]: ah, it is addressed, but you forgot to replace the `<=` with `<` here

File: src/hostname/hostnamed.c [hunk 14]
```diff
@@ -250,8 +250,62 @@ static int get_firmware_vendor(char **ret) {
...
+                return -EINVAL;
+
+        r = safe_atou(year, &y);
+        if (r < 0)
+                return r;
+        if (y < 1970 || y > (unsigned) INT_MAX)
+                return -EINVAL;
+        y -= 1900;
+
+        struct tm tm = (struct tm) {
```
Comment (poettering) [inline src/hostname/hostnamed.c]: you can drop the `(struct tm)`, it's not needed

File: test/units/testsuite-71.sh [hunk 15]
```diff
@@ -89,10 +89,25 @@ test_chassis() {
     fi
 }
 
+
```
Comment (poettering) [inline test/units/testsuite-71.sh]: spurious double empty line

File: test/units/testsuite-71.sh [hunk 16]
```diff
@@ -89,10 +89,25 @@ test_chassis() {
...
+restore_sysfs_dmi() {
+    umount /sys/class/dmi/id
+}
+
+
```
Comment (poettering) [inline test/units/testsuite-71.sh]: ditto

File: test/units/testsuite-71.sh [hunk 17]
```diff
@@ -89,10 +89,25 @@ test_chassis() {
...
+test_firmware_date() {
+    trap restore_machine_info RETURN
+
+    mount -t tmpfs none /sys/class/dmi/id
+    echo '12/31/2022' > /sys/class/dmi/id/bios_date
+    assert_in '2022-12-31' "$(hostnamectl)"
```
Comment (poettering) [inline test/units/testsuite-71.sh]: hostnamed might cache the info. hence issue `systemctl restart systemd-hostnamed` before, so that the cache is flushed and the date re-read again

File: src/hostname/hostnamed.c (hunk 12 above)
Comment (poettering) [reply src/hostname/hostnamed.c]: "an issue"?

Comment (jelly) [reply src/hostname/hostnamed.c]:
```
[root@image ~]# hostnamectl
     Firmware Date: Tue 1970-01-20 00:48:28 CET
[root@image ~]# hostnamectl --json=short
"FirmwareDate":1640908800000
```

So the JSON looks correct to me, and `TABLE_TIMESTAMP` should take a `usec_t`

File: src/hostname/hostnamed.c [hunk 18]
```diff
@@ -250,8 +250,62 @@ static int get_firmware_vendor(char **ret) {
...
+                .tm_mon = m,
+                .tm_year = y,
+        };
+        time_t v = timegm(&tm);
+        if (v == (time_t) -1)
+                return -errno;
+        if (tm.tm_mday != (int) d || tm.tm_mon != (int) m || tm.tm_year != (int) y)
+                return -EINVAL; /* date was not normalized? (e.g. "30th of feb") */
+
+        *ret = (usec_t) v * USEC_PER_MSEC;
```
Comment (poettering) [inline src/hostname/hostnamed.c]: USEC_PER_SEC!

time_t is seconds, and usec_t is µs

File: src/hostname/hostnamed.c (hunk 12 above)
Comment (poettering) [reply src/hostname/hostnamed.c]: for some reason you are using USEC_PER_MSEC as a multiplier, but should use USEC_PER_SEC. Hence the resulting µs value will be by a factor 1000 off. which results in the weird translation

File: src/hostname/hostnamed.c (hunk 18 above)
Comment (jelly) [reply src/hostname/hostnamed.c]: Sorry, fixed locally!

File: src/hostname/hostnamed.c [hunk 19]
```diff
@@ -250,8 +250,62 @@ static int get_firmware_vendor(char **ret) {
          return get_hardware_firmware_data("bios_vendor", ret);
 }
 
-static int get_firmware_date(char **ret) {
-         return get_hardware_firmware_data("bios_date", ret);
+static int get_firmware_date(usec_t *ret) {
+         _cleanup_free_ char *bios_date = NULL, *month = NULL, *day = NULL, *year = NULL;
+         int r;
+
```
Comment (bluca) [inline src/hostname/hostnamed.c:256]: assert(ret)

File: src/hostname/hostnamectl.c [hunk 20]
```diff
@@ -5,6 +5,7 @@
 #include <stdbool.h>
 #include <stdlib.h>
 #include <string.h>
+#include <stdint.h>
```
Comment (bluca) [inline src/hostname/hostnamectl.c]: sort alphabetically

File: test/units/testsuite-71.sh [hunk 21]
```diff
@@ -89,10 +89,45 @@ test_chassis() {
...
+    rm -rf /etc/systemd/system/systemd-hostnamed.service.d
+    systemctl daemon-reload
+    systemctl restart systemd-hostnamed
+}
+
+test_firmware_date() {
+    trap restore_sysfs_dmi RETURN
+
+    # Ignore /sys being mounted as tmpfs
+    mkdir /etc/systemd/system/systemd-hostnamed.service.d/
```
Comment (bluca) [inline test/units/testsuite-71.sh]: do this in /run given it's ephemeral

File: src/hostname/hostnamectl.c (hunk 20 above)
Comment (poettering) [reply src/hostname/hostnamectl.c]: actually, i don't think this line is needed at all

File: src/hostname/hostnamed.c [hunk 22]
```diff
@@ -250,8 +250,62 @@ static int get_firmware_vendor(char **ret) {
...
+         r = get_hardware_firmware_data("bios_date", &bios_date);
+         if (r < 0)
+                 return r;
+         if (r == 0) {
+                 *ret = USEC_INFINITY;
+                 return 0;
+         }
+
+        const char *p = bios_date;
```
Comment (poettering) [inline src/hostname/hostnamed.c]: something is off with indentation here. should all be 8 spaces

**Comment by poettering** [comment]
btw, this is close to be ready. please drop the "draft" status

**Comment by poettering** [comment]
lgtm! thanks!

File: src/hostname/hostnamed.c (hunk 19 above)
Comment (bluca) [reply src/hostname/hostnamed.c:256]: still not addressed

Comment (jelly) [reply src/hostname/hostnamed.c:256]: Sorry, fixed! Thanks for the review!

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
The test fails on s390x:

`Jan 18 19:17:25 H testsuite-71.sh[151]: mount: /sys/class/dmi/id: mount point does not exist.`

you should probably do mkdir -p just in case

**Comment by bluca** [comment]
still unhappy:

`Jan 18 23:26:33 H testsuite-71.sh[151]: mkdir: cannot create directory ‘/sys/class/dmi’: Read-only file system`

Mount the tmpfs one level up?

File: src/hostname/hostnamectl.c [hunk 23]
```diff
@@ -239,6 +241,14 @@ static int print_status_info(StatusInfo *i) {
                         return table_log_add_error(r);
         }
 
+        if (i->firmware_date != 0 && i->firmware_date != USEC_INFINITY) {
```
Comment (yuwata) [inline src/hostname/hostnamectl.c]: `timestamp_is_set(i->firmware_date)`

File: test/units/testsuite-71.sh [hunk 24]
```diff
@@ -89,10 +89,47 @@ test_chassis() {
...
+    rm -rf /run/systemd/system/systemd-hostnamed.service.d
+    systemctl daemon-reload
+    systemctl restart systemd-hostnamed
+}
+
+test_firmware_date() {
+    trap restore_sysfs_dmi RETURN
+
+    # Ignore /sys being mounted as tmpfs
+    mkdir /run/systemd/system/systemd-hostnamed.service.d/
```
Comment (yuwata) [inline test/units/testsuite-71.sh]: Please use `mkdir -p` for safety.

File: test/units/testsuite-71.sh [hunk 25]
```diff
@@ -89,10 +89,47 @@ test_chassis() {
...
+    cat > /run/systemd/system/systemd-hostnamed.service.d/override.conf <<- EOF
```
Comment (yuwata) [inline test/units/testsuite-71.sh]: We usually do not insert space between `>` and filename, (also maybe between `<<` and `EOF`, though I do not know why you set `-` after `<<`):
```
    cat >/run/systemd/system/systemd-hostnamed.service.d/override.conf <<EOF
```

File: test/units/testsuite-71.sh [hunk 26]
```diff
@@ -89,10 +89,47 @@ test_chassis() {
...
+[Service]
+Environment="SYSTEMD_DEVICE_VERIFY_SYSFS=0"
+EOF
+    systemctl daemon-reload
+
+    # mkdir for s390x
+    mkdir -p /sys/class/dmi/id
```
Comment (yuwata) [inline test/units/testsuite-71.sh]: How about to simply skip the test when the system does not have /sys/class/dmi/id ?
```sh
if [[ ! -d /sys/class/dmi/id ]]; then
    echo "/sys/class/dmi/id not found, skipping firmware date tests."
    return 0;
fi
```

File: test/units/testsuite-71.sh [hunk 27]
```diff
@@ -89,10 +89,47 @@ test_chassis() {
     fi
 }
 
+restore_sysfs_dmi() {
+    umount /sys/class/dmi/id
+    rm -rf /run/systemd/system/systemd-hostnamed.service.d
+    systemctl daemon-reload
+    systemctl restart systemd-hostnamed
```
Comment (yuwata) [inline test/units/testsuite-71.sh]: Not a matter, but stopping hostnamed is sufficient.

File: test/units/testsuite-71.sh [hunk 28]
```diff
@@ -89,10 +89,47 @@ test_chassis() {
...
+EOF
+    systemctl daemon-reload
+
+    # mkdir for s390x
+    mkdir -p /sys/class/dmi/id
+    mount -t tmpfs none /sys/class/dmi/id
+    echo '1' > /sys/class/dmi/id/uevent
+
+    echo '01/01/2000' > /sys/class/dmi/id/bios_date
+    systemctl restart systemd-hostnamed
```
Comment (yuwata) [inline test/units/testsuite-71.sh]: Also here. stopping hostnamed is enough, as `hostnamectl` below will start hostnamed.

**Review by yuwata — CHANGES_REQUESTED** [review]

File: test/units/testsuite-71.sh (hunk 26 above)
Comment (jelly) [reply test/units/testsuite-71.sh]: Makes sense, s390x has no DMI nor does powerpc.

File: test/units/testsuite-71.sh [hunk 29]
```diff
@@ -89,10 +89,50 @@ test_chassis() {
...
+    cat >/run/systemd/system/systemd-hostnamed.service.d/override.conf <<EOF
+[Service]
+Environment="SYSTEMD_DEVICE_VERIFY_SYSFS=0"
+EOF
+    systemctl daemon-reload
+
+    # No DMI on s390x or ppc
+    if [[ ! -d /sys/class/dmi/id ]]; then
+        echo "/sys/class/dmi/id not found, skipping firmware date tests."
+        return 0;
```
Comment (yuwata) [inline test/units/testsuite-71.sh]: It works, but `;` at the end is not necessary :-)

File: test/units/testsuite-71.sh [hunk 30]
```diff
@@ -89,10 +89,50 @@ test_chassis() {
...
+    # Ignore /sys being mounted as tmpfs
+    mkdir -p /run/systemd/system/systemd-hostnamed.service.d/
+    cat >/run/systemd/system/systemd-hostnamed.service.d/override.conf <<EOF
+[Service]
+Environment="SYSTEMD_DEVICE_VERIFY_SYSFS=0"
+EOF
+    systemctl daemon-reload
+
+    # No DMI on s390x or ppc
+    if [[ ! -d /sys/class/dmi/id ]]; then
```
Comment (yuwata) [inline test/units/testsuite-71.sh]: Not a big matter, but the check should be done earlier than creating drop-in config and `systemctl daemon-reload`. Then, testing on s390 or ppc slightly become faster.

**Review by yuwata — APPROVED** [review]
LGTM. Two minor comments. Thank you for your work!

**Review by yuwata — APPROVED** [review]
