### PR TITLE
core: only activate transaction that contain useful jobs

### LINKED ISSUE #9751: race condition between "systemctl daemon-reload" and "udevadm trigger"
**systemd version the issue has been seen with**
> v239

**Used distribution**
 > embedded system (but also reproduced with Debian and systemd v239)

**Expected behavior you didn't see**
 > serialized/deserialized device jobs don't hang forever after "daemon-reload"

**Unexpected behavior you saw**
 > serialized/deserialized device jobs hang forever after "daemon-reload"

**Steps to reproduce the problem**

To be executed in two different shells, a couple of iterations are enough. With proper timing this issue can be also reproduced with just one "udevadm trigger" & "systemctl daemon-reload" call in parallel if the latter is delayed a bit.
```
$ while true; do systemctl daemon-reload; done
$ while true; do udevadm trigger; done
```

----

If running device jobs get intercepted by "systemctl daemon-reload" (and in turn get serialized/deserialized), these will hang forever after "daemon-reload" returned. These device jobs hang in state "nop waiting" forever as can be seen afterwards with "systemctl list-jobs".

**I've bisected this behavior down to the following commit:**
```
f332611abee97247e40311d99492d53697152a1a is the first bad commit
commit f332611abee97247e40311d99492d53697152a1a
Author: Boucman <jeremy.rosen@enst-bretagne.fr>
Date: Fri Nov 10 17:00:32 2017 +0100

device : reload when udev generates a "changed" event (#6850)
```

This commit isn't the root cause of the problem but the one which caused to reproduce the issue easily with the above mentioned procedure. In general it seems that either all device jobs or "nop waiting" jobs which get serialized/deserialized hang forever after "daemon-reload" returns.

This issue can easily be reproduced, are further debug logs needed?

### PR DESCRIPTION
**Pull request by msekletar**
If no real jobs were added to the transaction, do not activate it. The JOB_NOP anchor does not perform any useful work and activating such transaction only wastes resources.

Fixes #9751

### CODE REVIEW

File: src/core/manager.c [hunk 1]
```diff
@@ -2278,6 +2278,11 @@ int manager_propagate_reload(Manager *m, Unit *unit, JobMode mode, sd_bus_error
                         tr->anchor_job,
                         mode == JOB_IGNORE_DEPENDENCIES ? TRANSACTION_IGNORE_ORDER : 0);
 
+        /* Only activate the transaction if it contains jobs other than NOP anchor.
+         * Short-circuiting here avoids unnecessary processing, such as emitting D-Bus signals. */
+        if (hashmap_size(tr->jobs) == 1)
```
Comment (YHNdnzj) [inline src/core/manager.c]: we prefer <= checks

Comment (msekletar) [reply src/core/manager.c]: Hmmm...Isn't that confusing? I mean we want early return in exactly one case so why check interval. On top of that, we put anchor job to the transaction explicitly.

**Comment by msekletar** [comment]
> Code itself makes sense to me, but I don't entirely understand the connection to the linked issue. The way I read things this only suppresses jobs from being installed if there's nothing load-bearing, but doesn't address the underlying issue?

AFAICT, the issue as described is not reproducible any more with current systemd version. I was able to reproduce 50%, i.e. NOP jobs are present after reload but eventually they are cleared because run_queue is correctly triggered after coldpluging stuff after deserialization. So the second part, i.e. these NOP jobs are stuck forever is no longer the case.

File: src/core/manager.c (hunk 1 above)
Comment (YHNdnzj) [reply src/core/manager.c]: Yeah I know == 0 is in reality not reachable, but we tend to encode the intention in these comparisons, and 0 is conceptually something we should skip too

**Comment by msekletar** [comment]
@YHNdnzj updated. PTAL.

**Review by yuwata — APPROVED** [review]
LGTM.
Could you add a test case for the issue?
I think it is better to add a sub test in TEST-17-UDEV.

**Comment by YHNdnzj** [comment]
OK, merging this as-is now. As explained above this is just an optimization, hence doesn't strictly speaking need a test. Test cases are still nice to have, but I see no reason to block the PR for that.
