### PR TITLE
sd-netlink: add destroy_callback to sd_netlink_call_async() and fix memleaks in networkd

### LINKED ISSUE #10196: There seems to be a memory leak in test-network
It turns out that the tests from https://github.com/systemd/systemd/pull/10147 don't clear up after themselves leaving several devices on the machine where they are run, which, in turn, triggers the following memory leak in `test-network`:
```sh
==14606== Memcheck, a memory error detector
==14606== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==14606== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==14606== Command: ./build/test-network
==14606==
==14606==
==14606== HEAP SUMMARY:
==14606==     in use at exit: 27,387 bytes in 371 blocks
==14606==   total heap usage: 1,575 allocs, 1,204 frees, 646,949 bytes allocated
==14606==
==14606== 9,685 (3,784 direct, 5,901 indirect) bytes in 11 blocks are definitely lost in loss record 41 of 41
==14606==    at 0x4C2EA1E: calloc (vg_replace_malloc.c:711)
==14606==    by 0x11DF60: link_new (networkd-link.c:450)
==14606==    by 0x12D20A: link_add (networkd-link.c:3326)
==14606==    by 0x135CC9: manager_rtnl_process_link (networkd-manager.c:679)
==14606==    by 0x139345: manager_rtnl_enumerate_links (networkd-manager.c:1557)
==14606==    by 0x1179DE: main (test-network.c:248)
==14606==
==14606== LEAK SUMMARY:
==14606==    definitely lost: 3,784 bytes in 11 blocks
==14606==    indirectly lost: 5,901 bytes in 100 blocks
==14606==      possibly lost: 0 bytes in 0 blocks
==14606==    still reachable: 17,702 bytes in 260 blocks
==14606==         suppressed: 0 bytes in 0 blocks
```
```
$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 52:54:00:b9:b5:61 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:bc:08:8d brd ff:ff:ff:ff:ff:ff
4: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 22:a3:26:51:1b:08 brd ff:ff:ff:ff:ff:ff
7: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 9e:2e:0d:cc:66:05 brd ff:ff:ff:ff:ff:ff
11: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
12: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
13: erspan0@NONE: <BROADCAST,MULTICAST> mtu 1446 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
18: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd ::
19: ip6gre0@NONE: <NOARP> mtu 1448 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/gre6 :: brd ::
24: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
33: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
44: ip6_vti0@NONE: <NOARP> mtu 1332 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd ::
47: ip_vti0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #10196 and #10320.

### CODE REVIEW

**Comment by yuwata** [comment]
@evverx Please take a look!

**Comment by evverx** [comment]
@yuwata thank you. I can confirm that the leak is gone.

File: src/network/networkd-manager.c [hunk 1]
```diff
@@ -1446,7 +1450,7 @@ void manager_free(Manager *m) {
 
                 hashmap_remove(m->links, INT_TO_PTR(link->ifindex));
 
-                link_unref(link);
+                link_free(link);
```
Comment (keszybz) [inline src/network/networkd-manager.c]: I don't think we want to do this this way. Forcibly freeing an object if it still has some other references remaining is generally bad. (The exception is where there are known circular references between objects. But that mostly applies to objects of the same type in a graph, like the unit graph, and here we have a hierarchy of objects so this should not be needed). The callbacks are all referenced from `manager->rtnl->reply_callbacks` and `manager->rtnl->reply_callbacks_prioq`. We call `sd_netlink_unref(m->rtnl)` below, and this should get rid of all the callbacks. If it doesn't that seems like an error to be fixed there to me.

Comment (yuwata) [reply src/network/networkd-manager.c]: > Forcibly freeing an object if it still has some other references remaining is generally bad.

Yes. I agree with you. But, if I understand correctly, now we do not have any way to unref a object which is set to callback userdata.
So, should we introduce `sd_netlink_set_destroy_callback()` similar to `sd_bus_slot_set_destroy_callback()`? I will try later.

Comment (keszybz) [reply src/network/networkd-manager.c]: Yes, it sounds like the right solution. I know this is going to be quite a lot of additional code, but I don't think we have much choice if we want to fix this properly.

**Comment by yuwata** [comment]
@keszybz I noticed `sd_netlink` is not public. So, I added destroy_callback argument to sd_netlink_call_async(). PTAL.

**Comment by yuwata** [comment]
Added a commit for fixing #10320 and small trivial cleanups.

File: src/libsystemd/sd-netlink/sd-netlink.c [hunk 2]
```diff
@@ -542,7 +542,7 @@ int sd_netlink_call_async(sd_netlink *nl,
 
         if (c->timeout != 0) {
                 r = prioq_put(nl->reply_callbacks_prioq, c, &c->prioq_idx);
-                if (r > 0) {
+                if (r < 0) {
```
Comment (poettering) [inline src/libsystemd/sd-netlink/sd-netlink.c:559]: ouch!

File: src/libsystemd/sd-netlink/sd-netlink.c [hunk 3]
```diff
@@ -494,13 +506,15 @@ static int timeout_compare(const void *a, const void *b) {
...
-                       sd_netlink_message_handler_t callback,
-                       void *userdata,
-                       uint64_t usec,
-                       uint32_t *serial) {
-        struct reply_callback *c;
+int sd_netlink_call_async(
+                sd_netlink *nl,
+                sd_netlink_message *m,
+                sd_netlink_message_handler_t callback,
+                sd_netlink_destroy_t destroy_callback,
```
Comment (poettering) [inline src/libsystemd/sd-netlink/sd-netlink.c:513]: hmm, i think sooner or later we should really rework this to have a sd_netlink_slot object similar to sd_bus_slot, and return that here instead of the serial or so, and then the destroy ptr could be set on the slot object, similar to how we do it in sd-bus...

but i figure that's a major rework, hence maybe that should be left for another time

**Comment by poettering** [comment]
so i think we should add sd_netlink_slot eventually, but this works too. Merging.
