### PR TITLE
network-generator: make ip=dhcp works with container manager

### LINKED ISSUE #28626: systemd-networkd default "unmanaged" for docker*, br-*, veth*
### systemd version the issue has been seen with

253.7-1

### Used distribution

Arch

### Linux kernel version used

6.4.6-hardened

### CPU architectures issue was seen on

x86_64

### Component

_No response_

### Expected behaviour you didn't see

Docker containers cannot connect to unternet,

networkctl shows "configuring" for docker0 and br-* devices.

### Unexpected behaviour you saw

systemd-networkd applying default route to docker network interfaces, thereby blocking docker containers from reaching internet.

This issue has cost me countless hours. I dont know why systemd-networkd decides to ship some "clever" defaults in /usr/lib/systemd/network but doesn't have a default for docker.

### Steps to reproduce the problem

Install systemd-networkd, install docker, start container: `docker run busybox ping -c 1 1.1.1.1` -> timeout

networkctl will show that systemd-networkd is busy "configuring" docker0 and all other docker virtual interfaces

Fix:

create /etc/systemd/network/{20-veth.network,21-docker.network,22-docker-br.network}
with contents:

```
[Match]
Name=veth*
[Link]
Unmanaged=true
```

```
[Match]
Name=docker*
[Link]
Unmanaged=true
```

```
[Match]
Name=br*
[Link]
Unmanaged=true
```

I assume this issue has been reported here hundreds of times. I really dont know why it is still default behavior.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Aug 01 18:36:55 hub systemd-networkd[97962]: docker0: Configuring with /run/systemd/network/91-default.network.
Aug 01 18:36:55 hub systemd-networkd[97962]: br-8297310e8a61: Configuring with /run/systemd/network/91-default.network.
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #28626.

### CODE REVIEW

File: src/network/generator/network-generator.c [hunk 1]
```diff
@@ -1108,10 +1108,15 @@ void network_dump(Network *network, FILE *f) {
...
         assert(f);
 
-        fprintf(f,
-                "[Match]\n"
-                "Name=%s\n",
-                isempty(network->ifname) ? "*" : network->ifname);
+        fputs("[Match]\n", f);
+
+        if (isempty(network->ifname))
+                /* If the interface name is not specified, then let's make the .network file matches the all
```
Comment (bluca) [inline src/network/generator/network-generator.c]: "match all physical interfaces"

**Review by bluca — APPROVED** [review]
