### PR TITLE
Fix a few test failures when building in mock

### LINKED ISSUE #3358: test/udev-test.pl fails when building inside mock
When building a systemd RPM in mock, the test/udev-test.pl test fails with several errors, likely because of the chroot environment that mock sets up. This test should probably be skipped or reworked when building inside a chroot.
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 230, though I remember seeing this in previous releases as well

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> CentOS 7
### In case of bug report: Expected behaviour you didn't see

> build succeeds
### In case of bug report: Unexpected behaviour you saw

> build fails
### In case of bug report: Steps to reproduce the problem

> attempt to build systemd in mock
> the test/udev-test.pl will fail

Full output of the failure:

```
 /usr/bin/install -c -m 644 man/sd_is_special.3 man/sd_journal.3 man/sd_journal_add_conjunction.3 man/sd_journal_add_disjunction.3 man/sd_journal_close.3 man/sd_journal_enumerate_data.3 man/sd_journal_enumerate_unique.3 man/sd_journal_flush_matches.3 man/sd_journal_get_catalog_for_message_id.3 man/sd_journal_get_cutoff_monotonic_usec.3 man/sd_journal_get_data_threshold.3 man/sd_journal_get_events.3 man/sd_journal_get_monotonic_usec.3 man/sd_journal_get_timeout.3 man/sd_journal_has_persistent_files.3 man/sd_journal_next_skip.3 man/sd_journal_open_directory.3 man/sd_journal_open_directory_fd.3 man/sd_journal_open_files.3 man/sd_journal_open_files_fd.3 man/sd_journal_perror.3 man/sd_journal_previous.3 man/sd_journal_previous_skip.3 man/sd_journal_printv.3 man/sd_journal_process.3 man/sd_journal_reliable_fd.3 man/sd_journal_restart_data.3 man/sd_journal_restart_fields.3 man/sd_journal_restart_unique.3 man/sd_journal_seek_cursor.3 man/sd_journal_seek_monotonic_usec.3 man/sd_journal_seek_realtime_usec.3 man/sd_journal_seek_tail.3 man/sd_journal_send.3 man/sd_journal_sendv.3 man/sd_journal_set_data_threshold.3 man/sd_journal_test_cursor.3 man/sd_journal_wait.3 man/sd_listen_fds_with_names.3 man/sd_machine_get_ifindices.3 '/builddir/build/BUILDROOT/systemd-230-1.fb1.x86_64/usr/share/man/man3'
libtool: install: warning: remember to run `libtool --finish /usr/lib64/security'
PASS: test-bus-error
FAIL: test/udev-test.pl
# XFAIL: 0
# FAIL:  1
# ERROR: 0
Failed to read ACPI FPDT: No such file or directory
Failed to read EFI loader data: No such file or directory
Failed to read variables: No such file or directory
Failed to connect to user bus: No such file or directory
Failed to connect to bus, skipping tests.
Failed to connect to bus, skipping tests.
FAIL: test/udev-test.pl
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
remove:      error as expected
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error as expected
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
414 errors occurred
# XFAIL: 0
# FAIL:  1
# ERROR: 0
# XFAIL: 0
# FAIL:  1
# ERROR: 0
Failed to read ACPI FPDT: No such file or directory
Failed to read EFI loader data: No such file or directory
Failed to read variables: No such file or directory
Failed to connect to user bus: No such file or directory
Failed to connect to bus, skipping tests.
Failed to connect to bus, skipping tests.
FAIL: test/udev-test.pl
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
remove:      error as expected
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error as expected
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
failed to mount / as private: Invalid argument
./test-udev add failed with code 256
add:         error
failed to mount / as private: Invalid argument
./test-udev remove failed with code 256
414 errors occurred
RPM build errors:
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check] Error 2
```

### PR DESCRIPTION
**Pull request by davide125**
This PR fixes a number of tests failures when building systemd in mock. I have verified that master now builds successfully both with and without `use_nspawn` enabled in mock. This closes #3358.

### CODE REVIEW

**Comment by keszybz** [comment]
> The condition tests for hostname will fail if hostname looks like an id128.

That sounds like some kind of error... Skipping the test does not seem to be the solution.

File: src/test/test-execute.c [hunk 1]
```diff
@@ -76,6 +76,11 @@ static void test(Manager *m, const char *unit_name, int status_expected, int cod
         check(m, unit, status_expected, code_expected);
 }
 
+static int in_container(void) {
+        char *container = getenv("container");
+        return container != NULL && strcmp(container, "systemd-nspawn") == 0;
```
Comment (keszybz) [inline src/test/test-execute.c]: We have a helper function for that: `streq_ptr`. So you could write:

```
   return streq_ptr(getenv("container"), "systemd-nspawn");
```

Nevertheless the condition that is tested doesn't match the function name. I don't think the test needs to be so specific, why not just use `!strempty(getenv("container"))`.

File: src/test/test-execute.c [hunk 2]
```diff
@@ -111,6 +116,10 @@ static void test_exec_privatetmp(Manager *m) {
 }
 
 static void test_exec_privatedevices(Manager *m) {
+        if (in_container()) {
+                printf("testing in container, skipping private device tests\n");
```
Comment (keszybz) [inline src/test/test-execute.c]: Other places in the same file use `log` when skipping tests. So

```
  log_notice("Running in container, skipping private device tests");
```

**Comment by keszybz** [comment]
Ah, OK, so test_condition_test_host() checks that the host name is not the same as the machine id. That's stupid of us, since that's a perfectly legal setup. Can you please instead fix the test instead? (E.g. to skip that one assert if the hostname turns out to be equal the the machine id.)

File: test/udev-test.pl [hunk 3]
```diff
@@ -1535,6 +1535,13 @@ sub run_test {
         exit($EXIT_TEST_SKIP);
 }
 
+# skip the test when running in a chroot
+system("systemd-detect-virt", "-r", "-q");
+if ($? >> 8 == 0) {
+  print "Running in a chroot, skipping the test.\n";
+  exit($EXIT_TEST_SKIP);
```
Comment (poettering) [inline test/udev-test.pl]: please follow the usual indentation style of the rest of this perl script!

File: src/test/test-condition.c [hunk 4]
```diff
@@ -142,6 +142,11 @@ static void test_condition_test_host(void) {
         hostname = gethostname_malloc();
         assert_se(hostname);
 
+        /* if hostname looks like an id128 then skip testing it */
+        if (sd_id128_from_string(hostname, &id) >= 0) {
```
Comment (poettering) [inline src/test/test-condition.c]: not that it matters too much, but please use id128_is_valid() for this check

File: src/test/test-execute.c (hunk 1 above)
Comment (poettering) [inline src/test/test-execute.c]: instead of defining a new function for this, please just use "detect_container(NULL) > 0", it's defined in virt.h

**Comment by davide125** [comment]
Force pushed to address comments. @keszybz I thought about comparing hostname with machine id before the assert, but that seems pointless as it's essentially what the CONDITION_HOST test would do internally. I'm open to suggestions for better ways to do this.

File: test/udev-test.pl [hunk 5]
```diff
@@ -1535,6 +1535,13 @@ sub run_test {
         exit($EXIT_TEST_SKIP);
 }
 
+# skip the test when running in a chroot
+system("systemd-detect-virt", "-r", "-q");
+if ($? >> 8 == 0) {
+    print "Running in a chroot, skipping the test.\n";
+    exit($EXIT_TEST_SKIP);
```
Comment (keszybz) [inline test/udev-test.pl:1542]: 8 space indent please.

**Comment by keszybz** [comment]
Minor formatting issues fixed in merge.
