### PR TITLE
pid1: do not reset subtree_control on already-existing units with delegation

### LINKED ISSUE #8364: Reloading a delegated unit shouldn't reset its cgroup.subtree_control
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> centos7

### In case of bug report: Expected behaviour you didn't see

> When a delegated unit is reloaded (via direct reload or daemon-reload), the delegatee's cgroup.subtree_control shouldn't be modified by systemd.

### In case of bug report: Unexpected behaviour you saw

> systemd on daemon-reload tries to disable all controllers in a delegated cgroup.

### In case of bug report: Steps to reproduce the problem

> Create a unit with Delegate=yes, enable controllers in it and do systemctl daemon-reload.

### PR DESCRIPTION
**Pull request by keszybz**
Fixes #8364.

Reproducer:
```console
$ sudo systemd-run -t -p Delegate=yes bash
# mkdir /sys/fs/cgroup/system.slice/run-u6958.service/supervisor
# echo $$ > /sys/fs/cgroup/system.slice/run-u6958.service/supervisor/cgroup.procs
# echo +memory > /sys/fs/cgroup/system.slice/run-u6958.service/cgroup.subtree_control
# cat /sys/fs/cgroup/system.slice/run-u6958.service/cgroup.subtree_control
memory
# systemctl daemon-reload
# cat /sys/fs/cgroup/system.slice/run-u6958.service/cgroup.subtree_control
(empty)
```
With patch, the last command shows 'memory'.

### CODE REVIEW

**Comment by keszybz** [comment]
`TEST RUN: EXTEND_TIMEOUT_USEC=usec start/runtime/stop tests [FAILED]`

File: src/basic/cgroup-util.c [hunk 1]
```diff
@@ -2104,23 +2107,29 @@ int cg_get_keyed_attribute(
 
 int cg_create_everywhere(CGroupMask supported, CGroupMask mask, const char *path) {
         CGroupController c;
+        bool new;
```
Comment (poettering) [inline src/basic/cgroup-util.c]: we have a macro called new(), we should probably stay away from that name. This only works here because it isn't followed by a `(`, and that sounds a bit too fragile to me...

File: src/core/cgroup.c [hunk 2]
```diff
@@ -1453,6 +1453,7 @@ static int unit_create_cgroup(
 
         CGroupContext *c;
         int r;
+        bool new;
```
Comment (poettering) [inline src/core/cgroup.c]: as above

**Comment by keszybz** [comment]
Updated.

**Comment by hxysayhi** [comment]
In the systemd v250 environment, when I restart the service, the subtree_control is reset. Is this reasonable?


If I modify the value of subtree_control, then when I restart the service, systemd will try to overwrite the value of subtree_control. For example, if I add a `cpu` controller to subtree_control, systemd will remove it from subtree_control when the service is restarted. If I create a subdirectory at this time, and there are still processes in the subgroup when restarting, the startup will fail. The error is as follows:   
```
Control process exited, code=exited, status=219/CGROUP
...
Unit process 543222  (xxx) remains running after unit stoped.
....
```
Which seems to be a failure when rewriting the subtree_control. 

I want to manage subtree_control by myself when delegation is turned on, I hope systemd doesn't modify it.

**Comment by yuwata** [comment]
@hxysayhi Please open a new issue. Otherwise, we easily forget your comment.

**Comment by yuwata** [comment]
Oops. You already opened a new issue. Sorry.
