### PR TITLE
resolve: allow whitespaces in the digest

### LINKED ISSUE #3682: [dnssec-trust-anchors.d] systemd-resolved fail on "Trailing garbage", but RFC 4034 say whitespace allowed
### Submission type
- [X] Bug report
### systemd version the issue has been seen with

systemd 230
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
### Used distribution

Archlinux
### Expected behaviour you didn't see

```
% cat /etc/dnssec-trust-anchors.d/craoc.fr.positive
craoc.fr.               IN DS 9138 7 1 9C42814A  315   86FEB   B1D6E 27380DF669   D6A790372
% sudo systemctl restart systemd-resolved
% journalctl -u systemd-resolved
everything is fine
```
### Unexpected behaviour you saw

```
% cat /etc/dnssec-trust-anchors.d/craoc.fr.positive
craoc.fr.               IN DS 9138 7 1 9C42814A  315   86FEB   B1D6E 27380DF669   D6A790372
% sudo systemctl restart systemd-resolved
% journalctl -u systemd-resolved --no-hostname
…
juil. 07 20:55:10 systemd-resolved[2278]: Trailing garbage on line /etc/dnssec-trust-anchors.d/craoc.fr.positive:1, ignoring line.
…
```
### Steps to reproduce the problem

Just introduce whitespace in a dnssec-trust-anchors.d file.
### Remarks

Everything is good without whitespace:

```
craoc.fr.               IN DS 9138 7 1 9C42814A31586FEBB1D6E27380DF669D6A790372
```

man dnssec-trust-anchors.d indicate the file format respect the RFC 4034 section 5.
extract from section [5.3](https://tools.ietf.org/html/rfc4034#section-5.3):

> Whitespace is allowed within the hexadecimal text

Either say explicitly whitespace aren't allowed in the man or patch systemd-resolved to support whitespace (I personalty think the second is better :) )

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #3682.

### CODE REVIEW

File: src/resolve/resolved-dns-trust-anchor.c [hunk 1]
```diff
@@ -274,6 +275,14 @@ static int dns_trust_anchor_load_positive(DnsTrustAnchor *d, const char *path, u
                         return -EINVAL;
                 }
 
+                if (isempty(p)) {
+                        log_warning("Missing DS parametes on line %s:%u", path, line);
```
Comment (keszybz) [inline src/resolve/resolved-dns-trust-anchor.c]: Typo.

File: src/resolve/resolved-dns-trust-anchor.c [hunk 2]
```diff
@@ -274,6 +275,14 @@ static int dns_trust_anchor_load_positive(DnsTrustAnchor *d, const char *path, u
...
+                        return -EINVAL;
+                }
+
+                digest = strdupa(p);
+                digest = delete_chars(digest, WHITESPACE);
```
Comment (keszybz) [inline src/resolve/resolved-dns-trust-anchor.c]: Hmm, I wonder if it wouldn't be better to tweak `unhexmem` instead to ignore whitespace. Possibly as a flag, in case there are places where we want to preserve it. It just seems that in majority of cases we don't care about whitespace at all.

Comment (keszybz) [reply src/resolve/resolved-dns-trust-anchor.c]: `root_hash_load` in `src/shared/dissect-image.c` would imho benefit from this too: it seems unnecessarily strict to forbid trailing whitespace in `.roothash`.

Comment (yuwata) [reply src/resolve/resolved-dns-trust-anchor.c]: OK. I will update this.

**Comment by yuwata** [comment]
@keszybz Updated. As `unbase64mem()` already ignores whitespaces, then I made `unhexmem()` also do so.

File: src/basic/hexdecoct.c [hunk 3]
```diff
@@ -89,6 +89,9 @@ int unhexmem(const char *p, size_t l, void **mem, size_t *len) {
         if (l == (size_t) -1)
                 l = strlen(p);
 
+        p = delete_chars(strndupa(p, l), WHITESPACE);
```
Comment (keszybz) [inline src/basic/hexdecoct.c]: Hmm, that's not going to work. First, `strndupa` (`alloca` in general) cannot be used in arguments of another function, it must be a separate statement. But a bigger problem is that `p` has unknown length. In practice most uses are probably bounded somehow, but since `unhexmem` is used both on files read from disk and packets received from the network, I think we need to be careful, and avoid stack allocations of unknown size.

I think a better solution would be to simply use `strlen` here on the original string, possibly allocating larger space then necessary, and in the loop below, skipping any whitespace chars. As a result, if there is whitespace, we might overallocate a bit. But in all non-pathological cases this overallocation will be very small, and in pathological cases we'll just be a bit less efficient.

I'm not sure if we should allow whitespace everywhere or just at the beginning and end.

File: src/basic/hexdecoct.c [hunk 4]
```diff
@@ -89,6 +89,9 @@ int unhexmem(const char *p, size_t l, void **mem, size_t *len) {
...
+        l = strlen(p);
```
Comment (poettering) [inline src/basic/hexdecoct.c]: I figure this works too, but this means we'll go through the string twice, once for removing whitespace, and wants for translating to binary... I figure eventually it might make sense to optimize that so that we skip whitespace automatically within the translation loop

File: src/basic/hexdecoct.c (hunk 3 above)
Comment (poettering) [reply src/basic/hexdecoct.c]: how did i miss that? I claim that my jetlag is at fault here (hi from san francisco, btw ;-))

**Comment by yuwata** [comment]
@keszybz and @poettering Thank you for the comments. I will try to optimize this and drop `alloca()`.

File: src/basic/hexdecoct.c (hunk 3 above)
Comment (keszybz) [reply src/basic/hexdecoct.c]: Welcome to the night shift!

**Comment by yuwata** [comment]
@keszybz and @poettering Updated. Please take a look.
- `unhexmem()` do not call `alloca()`.
- input text is parsed only twice: `strlen()` and decoding.
- several cosmetic changes.

File: src/test/test-hexdecoct.c [hunk 5]
```diff
@@ -76,20 +76,37 @@ static void test_undecchar(void) {
...
-        assert_se(unhexmem(hex, strlen(hex) + 1, &mem, &len) == -EINVAL);
-        assert_se(unhexmem(hex, strlen(hex) - 1, &mem, &len) == -EINVAL);
-        assert_se(unhexmem(hex, strlen(hex), &mem, &len) == 0);
+        assert_se(unhexmem(s, l, &mem, &len) == retval);
+        if (retval == 0) {
+                if (l == (size_t) - 1)
+                        l = strlen(s);
+
+                assert_se((hex = hexmem(mem, len)));
+                assert_se(streq(delete_chars(strndupa(s, l), WHITESPACE), hex));
```
Comment (keszybz) [inline src/test/test-hexdecoct.c]: No strndupa in args please.

File: src/libsystemd-network/network-internal.c [hunk 6]
```diff
@@ -658,12 +658,15 @@ int serialize_dhcp_option(FILE *f, const char *key, const void *data, size_t siz
...
 int deserialize_dhcp_option(void **data, size_t *data_len, const char *string) {
+        size_t l;
+
         assert(data);
         assert(data_len);
         assert(string);
 
-        if (strlen(string) % 2)
+        l = strlen(string);
+        if (l % 2)
```
Comment (keszybz) [inline src/libsystemd-network/network-internal.c]: Does this check make sense anymore?

**Comment by yuwata** [comment]
@keszybz Updated.
- do not call `alloca()` inside the list of argument of a function call.
- drop `deserialize_dhcp_option()`.
