### PR TITLE
network: use sysctl to set IPv6LL address generation mode when the interface is already up

### LINKED ISSUE #22424: networkd: fails to restore IPv6LL address generation
**systemd version the issue has been seen with**
`systemd 250 (250.3-2-arch)`

**Used distribution**
Arch Linux 2022.02.01 (installation iso)

**Linux kernel version used** (`uname -a`)
`Linux archiso 5.16.4-arch1-1 #1 SMP PREEMPT Sat, 29 Jan 2022 19:08:13 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
`x86_64`

**Unexpected behaviour you saw**
If a network interface has kernel IPv6LL address generation disabled when networkd is started, networkd re-enables address generation but the interface nevers obtains an IPv6LL address, resulting in the interface being stuck in the `configuring` state.

**Steps to reproduce the problem**
1. Boot Arch iso
`qemu-system-x86_64 -enable-kvm -cdrom archlinux-2022.02.01-x86_64.iso -m 4G`

2. Disable IPv6LL

```
# sysctl -w net.ipv6.conf.ens3.addr_gen_mode=1
net.ipv6.conf.ens3.addr_gen_mode = 1
```

Note:
```
0: generate address based on EUI64 (default)
1: do no generate a link-local address, use EUI64 for addresses generated from autoconf
```

3. Clear v6 interface addresses
```
# ip link set ens3 down; ip link set ens3 up

# ip address show ens3
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    inet 10.0.2.15/24 metric 100 brd 10.0.2.255 scope global dynamic ens3
       valid_lft 86358sec preferred_lft 86358sec

```

4. Restart networkd
```
# systemctl restart systemd-networkd
```

5. Networkd has restored kernel IPv6LL defaults
```
# sysctl net.ipv6.conf.ens3.addr_gen_mode
net.ipv6.conf.ens3.addr_gen_mode = 0
```
... but it's stuck waiting for an address

```
# networkctl status ens3            
● 2: ens3                                                                      >
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/20-ethernet.network
                          Type: ether
                         State: routable (configuring)
                  Online state: online                                         >
             Alternative Names: enp0s3
                          Path: pci-0000:00:03.0
                        Driver: e1000
                        Vendor: Intel Corporation
                         Model: 82540EM Gigabit Ethernet Controller (QEMU Virtu>
              Hardware Address: 52:54:00:12:34:56
                           MTU: 1500 (min: 46, max: 16110)
                         QDisc: fq_codel
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: yes
                         Speed: 1Gbps
                        Duplex: full
                          Port: tp
                       Address: 10.0.2.15 (DHCP4 via 10.0.2.2)
                       Gateway: 10.0.2.2
                           DNS: 10.0.2.3
```

Note that if you now toggle (!) `addr_gen_mode` manually it _does_ assign an IPv6LL address..

```
# sysctl -w net.ipv6.conf.ens3.addr_gen_mode=1
# sysctl -w net.ipv6.conf.ens3.addr_gen_mode=0
```

**Additional program output to the terminal or log subsystem illustrating the issue**

Some interesting bits from systemd-networkd logs:

```
Feb 04 18:27:42 archiso systemd-networkd[931]: ens3: Setting IPv6LL address generation mode
...
Feb 04 18:27:42 archiso systemd-networkd[931]: ens3: IPv6LL address generation mode set.
Feb 04 18:27:42 archiso systemd-networkd[931]: ens3: master interface set.
Feb 04 18:27:42 archiso systemd-networkd[931]: ens3: link_check_ready(): link is not activated.
Feb 04 18:27:42 archiso systemd-networkd[931]: ens3: Bringing link up
Feb 04 18:27:42 archiso systemd-networkd[931]: ens3: link_check_ready(): IPv6LL is not configured yet.
```

Full networkd debug log: [networkd.log](https://gist.githubusercontent.com/ius/ce2a016678b351fe9dc7522e2d466fb5/raw/60c0caf93ba023a5bd2aaaddaf40ceb1dd9f54a0/networkd.log)

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #22424.
Replaces #22433.

### CODE REVIEW

File: src/network/networkd-ipv6ll.c [hunk 1]
```diff
@@ -74,6 +74,48 @@ bool link_may_have_ipv6ll(Link *link) {
         return false;
 }
 
+IPv6LinkLocalAddressGenMode link_get_ipv6ll_addrgen_mode(Link *link) {
+        if (!link_ipv6ll_enabled(link))
+                return IPV6_LINK_LOCAL_ADDRESSS_GEN_MODE_NONE;
+
+        if (link->network->ipv6ll_address_gen_mode >= 0)
```
Comment (bluca) [inline src/network/networkd-ipv6ll.c:84]: assert/check link and link->network?

File: src/network/networkd-ipv6ll.c [hunk 2]
```diff
@@ -116,6 +116,65 @@ int ipv6ll_addrgen_mode_fill_message(sd_netlink_message *message, IPv6LinkLocalA
...
+        int family, r;
+
+        assert(link);
+        assert(message);
+
+        r = sd_rtnl_message_get_family(message, &family);
+        if (r < 0)
+                return r;
+
+        if (family != AF_UNSPEC)
```
Comment (bluca) [inline src/network/networkd-ipv6ll.c:133]: Is this intended to be AF_UNSPEC instead of AF_INET6?

File: src/network/networkd-setlink.c [hunk 3]
```diff
@@ -688,6 +688,19 @@ int link_request_to_set_addrgen_mode(Link *link) {
         if (mode == link->ipv6ll_address_gen_mode)
                 return 0;
 
+        /* If the link is already up, then changing the mode by netlink does take no effect until the
```
Comment (bluca) [inline src/network/networkd-setlink.c]: `does not take effect`

File: src/network/networkd-setlink.c [hunk 4]
```diff
@@ -688,6 +688,19 @@ int link_request_to_set_addrgen_mode(Link *link) {
...
+         * link becomes down. Hence, we need to reset the interface. However, setting the mode by
```
Comment (bluca) [inline src/network/networkd-setlink.c]: `link goes down`

**Review by bluca — APPROVED** [review]
lgtm, just some nits and a question

File: src/network/networkd-ipv6ll.c (hunk 1 above)
Comment (yuwata) [reply src/network/networkd-ipv6ll.c:84]: `link->network` is handled `link_ipv6ll_enabled()`. Added `assert(link);`.

File: src/network/networkd-ipv6ll.c (hunk 2 above)
Comment (yuwata) [reply src/network/networkd-ipv6ll.c:133]: `AF_UNSPEC` here is correct. Here, `family` may be `AF_BRIDGE` in some message. This intends to avoid such case.

**Comment by yuwata** [comment]
@bluca Thank you for the review. Addressed the above points. Upgrading the green label.
