### PR TITLE
logind: Restore chvt as non-root user without polkit

### LINKED ISSUE #17473: Cannot activate VT without CAP_SYS_ADMIN when polkit is disabled (prevents running weston as non-root user)
**systemd version the issue has been seen with**
 > 245 and later (also reproduced on latest master)

**Used distribution**
 > Custom Embedded Distribution on Raspberry Pi 4

**Linux kernel version used** (`uname -a`)
 > 5.4.72

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > Since 4acf0cfd2f92edb94ad48d04f1ce6c9ab4e19d55, it is no longer possible for a process without `CAP_SYS_ADMIN` to activate a virtual terminal when polkit support is disabled.

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
 > Build without polkit support and attempt to activate launch weston as  non-root user. See: https://gitlab.freedesktop.org/wayland/weston/-/issues/428

### PR DESCRIPTION
**Pull request by JPEWdev**
4acf0cfd2f ("logind: check PolicyKit before allowing VT switch") broke
the ability to write user sessions that run graphical sessions (e.g.
weston/X11). This was partially amended in 19bb87fbfa ("login: allow
non-console sessions to change vt") by changing the default PolicyKit
policy so that non-root users are again allowed to switch the VT. This
makes the policy when PolKit is not enabled (as on many embedded
systems) match the default PolKit policy and allows launching graphical
sessions as a non-root user.

Closes #17473

### CODE REVIEW

**Comment by mikkorapeli** [comment]
The patch looks good to me. There is no need to have polkit with its mozjs as hard dependency from systemd. mozjs has a huge impact on both rootfs file system size and boot time for any services like weston which would depend on it.

**Comment by poettering** [comment]
hmm, the policykit policy is different from what you claim: only users with a session are allow to issue chvt. users without are not. Thus the commit msg is misleading.

But I think the patch is OK in general. I just would prefer if the comit msg and comment would be updated to say that the policykit enforced default policy is similar but not identical to this.

File: src/login/logind-polkit.h [hunk 1]
```diff
@@ -0,0 +1,10 @@
+/* SPDX-License-Identifier: LGPL-2.1+ */
+#pragma once
+
+#include "sd-bus.h"
+
+#include "bus-object.h"
+#include "logind.h"
+
+int check_polkit_chvt(sd_bus_message *message, Manager *manager, sd_bus_error *error);
+
```
Comment (yuwata) [inline src/login/logind-polkit.h]: Please drop the unnecessary blank line at the end of file.

File: src/login/meson.build [hunk 2]
```diff
@@ -26,6 +26,7 @@ liblogind_core_sources = files('''
         logind-device.h
         logind-inhibit.c
         logind-inhibit.h
+        logind-polkit.c
```
Comment (yuwata) [inline src/login/meson.build:28]: Please also add `logind-polkit.h`.

**Review by yuwata — CHANGES_REQUESTED** [review]

File: src/login/logind-polkit.h (hunk 1 above)
Comment (JPEWdev) [reply src/login/logind-polkit.h]: Done

File: src/login/meson.build (hunk 2 above)
Comment (JPEWdev) [reply src/login/meson.build:28]: done

**Comment by poettering** [comment]
lgtm
