### PR TITLE
network/route: check if existing route can be updated

### LINKED ISSUE #28426: RA Default Preference not observed
### systemd version the issue has been seen with

252.5-2ubuntu3

### Used distribution

Ubuntu Lunar

### Linux kernel version used

6.2.0-24-generic

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

I have two routers - a primary one that connects to the internet and a secondary that connects to a VPN. The primary is configured with 'default router preference high' and the secondary has 'default router preference medium' (but it advertises specific routes).

I expect the primary router to always be used as the default gateway when both routers are available. The secondary should only be used as a default gateway when the primary is not advertising itself.

### Unexpected behaviour you saw

I have observed that my workstation starts using the secondary (default router preference medium) if that one is restarted, even though the primary (default router preference high) is available/advertising itself.

### Steps to reproduce the problem

I have created a github repo that can reproduce the problem here: https://github.com/lagweasel/router-pref-issue

The setup includes 3 VirtualBox VMs. One of them is the main workstations (called 'main') and the other two are acting as the two routers (using bird2 to send router advertisements). All 3 are attached to an isolated virtualbox network.

The steps are:

1. Start VMs
    `vagrant up`
    Expected result: All 3 VMs are started, but sending of IPv6 router advertisements is initially disabled

2. Verify there is no IPv6 default gateway yet on 'main' VM (RA hasn't been enabled yet) 
    `./test-ping.sh`
    Expected result: ping: connect: Network is unreachable

3. Enable Router Advertisements on 'high' preference default gateway (address ends with :1)
    `./enable-h.sh`
    Expected result: radv_h: enabled

4. Verify 'high' preference default gateway (address ends with :1) is used for IPv6 pings from main VM
    `./test-ping.sh`
    Expected result: From fd00:a:b:c::1 icmp_seq=1 Destination unreachable: No route
    (Note this response is from ":1" router.)

5. Enable Router Advertisements on 'medium' preference default gateway (address ends with :2)
    `./enable-m.sh`
    Expected result: radv_m: enabled

6. Run test to see whether 'high' or 'medium' preference default gateway is used for IPv6 pings from main VM
    `./test-ping.sh`
    Expected result: From fd00:a:b:c::1 icmp_seq=1 Destination unreachable: No route
    Actual result:   From fd00:a:b:c::2 icmp_seq=1 Destination unreachable: No route

(See the main readme file in the repo for prerequisites and additional details/scripts.)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Jul 17 11:34:53 main systemd-networkd[1916]: enp0s3: link_check_ready(): IPv4LL:no DHCPv4:yes DHCPv6:no DHCP-PD:no NDisc:no
Jul 17 11:34:53 main systemd-networkd[1916]: enp0s3: State changed: configuring -> configured
Jul 17 11:34:53 main systemd-networkd[1916]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=49 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 17 11:34:53 main systemd-networkd[1916]: enp0s3: NDISC: Sent Router Solicitation, next solicitation in 3s
Jul 17 11:34:54 main systemd-networkd[1916]: enp0s8: Received new foreign address (configured): fe80::a00:27ff:fee3:f60b/64 (valid forever, preferred forever), flags: permanent, scope: link
Jul 17 11:34:54 main systemd-networkd[1916]: enp0s8: Gained IPv6LL
Jul 17 11:34:54 main systemd-networkd[1916]: enp0s8: Discovering IPv6 routers
Jul 17 11:34:54 main systemd-networkd[1916]: enp0s8: NDISC: Started IPv6 Router Solicitation client
Jul 17 11:34:54 main systemd-networkd[1916]: enp0s8: link_check_ready(): dynamic addresses or routes are not configured.
Jul 17 11:34:54 main systemd-networkd[1916]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=50 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 17 11:34:54 main systemd-networkd[1916]: enp0s8: link_check_ready(): dynamic addresses or routes are not configured.
Jul 17 11:34:54 main systemd-networkd[1916]: enp0s8: Received new foreign route (configured): dst: fe80::a00:27ff:fee3:f60b/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local(255), proto: kernel, type: local, nexthop: 0, priority: 0, flags: n/a
Jul 17 11:34:54 main systemd-networkd[1916]: enp0s8: NDISC: Sent Router Solicitation, next solicitation in 4s
Jul 17 11:34:57 main systemd-networkd[1916]: enp0s3: NDISC: Sent Router Solicitation, next solicitation in 7s
Jul 17 11:34:59 main systemd-networkd[1916]: enp0s8: NDISC: Sent Router Solicitation, next solicitation in 7s
Jul 17 11:35:05 main systemd-networkd[1916]: enp0s3: NDISC: Sent Router Solicitation, next solicitation in 14s
Jul 17 11:35:05 main systemd-networkd[1916]: enp0s3: NDISC: No RA received before link confirmation timeout
Jul 17 11:35:05 main systemd-networkd[1916]: enp0s3: NDISC: Invoking callback for 'timeout' event.
Jul 17 11:35:05 main systemd-networkd[1916]: enp0s3: NDisc handler get timeout event
Jul 17 11:35:06 main systemd-networkd[1916]: enp0s8: NDISC: No RA received before link confirmation timeout
Jul 17 11:35:06 main systemd-networkd[1916]: enp0s8: NDISC: Invoking callback for 'timeout' event.
Jul 17 11:35:06 main systemd-networkd[1916]: enp0s8: NDisc handler get timeout event
Jul 17 11:35:06 main systemd-networkd[1916]: enp0s8: link_check_ready(): IPv4LL:no DHCPv4:no DHCPv6:no DHCP-PD:no NDisc:yes
Jul 17 11:35:06 main systemd-networkd[1916]: enp0s8: State changed: configuring -> configured
Jul 17 11:35:06 main systemd-networkd[1916]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=51 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 17 11:35:08 main systemd-networkd[1916]: enp0s8: NDISC: Sent Router Solicitation, next solicitation in 15s
Jul 17 11:35:20 main systemd-networkd[1916]: enp0s3: NDISC: Sent Router Solicitation, next solicitation in 27s
Jul 17 11:35:23 main systemd-networkd[1916]: enp0s8: NDISC: Sent Router Solicitation, next solicitation in 29s
Jul 17 11:35:48 main systemd-networkd[1916]: enp0s3: NDISC: Sent Router Solicitation, next solicitation in 57s
Jul 17 11:35:53 main systemd-networkd[1916]: enp0s8: NDISC: Sent Router Solicitation, next solicitation in 1min 2s
Jul 17 11:36:46 main systemd-networkd[1916]: enp0s3: NDISC: Sent Router Solicitation, next solicitation in 1min 57s
Jul 17 11:36:55 main systemd-networkd[1916]: enp0s8: NDISC: Sent Router Solicitation, next solicitation in 2min 5s
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: NDISC: Received Router Advertisement: flags none preference high lifetime 1800 sec
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: NDISC: Invoking callback for 'router' event.
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: Requesting NDisc route (n/a): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: Requesting NDisc route (n/a): dst: fd00:a:b:c::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: Requesting NDisc address (n/a): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 59s, preferred for 3h 59min 59s), flags: tentative,manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: Setting SLAAC addresses and router.
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: State changed: configured -> configuring
Jul 17 11:37:23 main systemd-networkd[1916]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=52 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: link_check_ready(): address fd00:a:b:c:a00:27ff:fee3:f60b/64 is not ready.
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: Configuring NDisc route (requesting): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: Configuring NDisc route (requesting): dst: fd00:a:b:c::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: Configuring NDisc address (requesting): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 59s, preferred for 3h 59min 59s), flags: tentative,manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: Received remembered NDisc route (configured): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: Received remembered NDisc route (configured): dst: fd00:a:b:c::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: Received updated NDisc address (configured): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 59s, preferred for 3h 59min 59s), flags: tentative,manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: link_check_ready(): address fd00:a:b:c:a00:27ff:fee3:f60b/64 is not ready.
Jul 17 11:37:23 main systemd-networkd[1916]: enp0s8: ndisc_check_ready(): no SLAAC address is ready.
Jul 17 11:37:25 main systemd-networkd[1916]: enp0s8: Received updated NDisc address (configured): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 58s, preferred for 3h 59min 58s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:25 main systemd-networkd[1916]: enp0s8: SLAAC addresses and routes set.
Jul 17 11:37:25 main systemd-networkd[1916]: enp0s8: link_check_ready(): IPv4LL:no DHCPv4:no DHCPv6:no DHCP-PD:no NDisc:yes
Jul 17 11:37:25 main systemd-networkd[1916]: enp0s8: State changed: configuring -> configured
Jul 17 11:37:25 main systemd-networkd[1916]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=53 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 17 11:37:25 main systemd-networkd[1916]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=54 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 17 11:37:25 main systemd-networkd[1916]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=55 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 17 11:37:25 main systemd-networkd[1916]: enp0s8: Received new foreign route (configured): dst: fd00:a:b:c:a00:27ff:fee3:f60b/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local(255), proto: kernel, type: local, nexthop: 0, priority: 0, flags: n/a
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: NDISC: Received Router Advertisement: flags none preference medium lifetime 1800 sec
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: NDISC: Invoking callback for 'router' event.
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: Requesting NDisc route (n/a): dst: n/a, src: n/a, gw: fe80::2, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: Requesting NDisc route (configured): dst: fd00:a:b:c::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: Requesting NDisc address (configured): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 59s, preferred for 3h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: Setting SLAAC addresses and router.
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: State changed: configured -> configuring
Jul 17 11:37:34 main systemd-networkd[1916]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=56 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: link_check_ready(): dynamic addresses or routes are not configured.
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: Configuring NDisc route (requesting): dst: n/a, src: n/a, gw: fe80::2, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: Configuring NDisc route (requesting,configured): dst: fd00:a:b:c::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: Configuring NDisc address (requesting,configured): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 59s, preferred for 3h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: Received remembered NDisc route (configured): dst: n/a, src: n/a, gw: fe80::2, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: Received remembered NDisc route (configured): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: Received updated NDisc address (configured): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 59s, preferred for 3h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: link_check_ready(): dynamic addresses or routes are not configured.
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: SLAAC addresses and routes set.
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: link_check_ready(): IPv4LL:no DHCPv4:no DHCPv6:no DHCP-PD:no NDisc:yes
Jul 17 11:37:34 main systemd-networkd[1916]: enp0s8: State changed: configuring -> configured
Jul 17 11:37:34 main systemd-networkd[1916]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=57 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: NDISC: Received Router Advertisement: flags none preference high lifetime 1800 sec
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: NDISC: Invoking callback for 'router' event.
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: Requesting NDisc route (configured): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: Requesting NDisc route (configuring,configured): dst: fd00:a:b:c::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: Requesting NDisc address (configured): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 59s, preferred for 3h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: Setting SLAAC addresses and router.
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: Configuring NDisc route (requesting,configured): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: Configuring NDisc route (requesting,configuring,configured): dst: fd00:a:b:c::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: Configuring NDisc address (requesting,configured): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 59s, preferred for 3h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: Received updated NDisc address (configured): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 59s, preferred for 3h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:39 main systemd-networkd[1916]: enp0s8: SLAAC addresses and routes set.
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: NDISC: Received Router Advertisement: flags none preference medium lifetime 1800 sec
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: NDISC: Invoking callback for 'router' event.
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: Requesting NDisc route (configured): dst: n/a, src: n/a, gw: fe80::2, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: Requesting NDisc route (configuring,configured): dst: fd00:a:b:c::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: Requesting NDisc address (configured): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 59s, preferred for 3h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: Setting SLAAC addresses and router.
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: Configuring NDisc route (requesting,configured): dst: n/a, src: n/a, gw: fe80::2, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: Configuring NDisc route (requesting,configuring,configured): dst: fd00:a:b:c::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: Configuring NDisc address (requesting,configured): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 59s, preferred for 3h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: Received updated NDisc address (configured): fd00:a:b:c:a00:27ff:fee3:f60b/64 (valid for 23h 59min 59s, preferred for 3h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 17 11:37:50 main systemd-networkd[1916]: enp0s8: SLAAC addresses and routes set.
```

### LINKED ISSUE #28437: IPv6 Compliance RFC4861: Router Advertisement Processing, Cur Hop Limit [v6LC.2.2.13 Part B]
### systemd version the issue has been seen with

250

### Used distribution

Embedded Linux - Debian-based

### Linux kernel version used

5.15.71-rt51+gc36e774d0d9a

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

### Expected behaviour you didn't see

**Purpose**: Verify that a node properly processes the Cur Hop Limit field of a Router Advertisement.

#### Reference
[RFC4861](https://www.rfc-editor.org/rfc/rfc4861.txt) Neighbor Discovery – Sections 4.2 and 6.3.4

From section 4.2. Router Advertisement Message Format:
```
Cur Hop Limit        8-bit unsigned integer.  The default value that
                     should be placed in the Hop Count field of the IP
                     header for outgoing IP packets.  A value of zero
                     means unspecified (by this router).
```

From section 6.3.4. Processing Received Router Advertisements:
```
If the received Cur Hop Limit value is non-zero, the host SHOULD set
its CurHopLimit variable to the received value.
```

### Unexpected behaviour you saw

networkd ignores the RA's CurHopLimit parameter.

For comparison, stopping `networkd` and configuring the interface via `/etc/network/interfaces` results in a successful protocol exchange.

### Steps to reproduce the problem

The attached zip file has a `legacy` folder, where the network was configured via `/etc/network/interfaces` and a `networkd` folder, where the network was managed by `networkd`. The PCAP in the `legacy` folder demonstrates the expected protocol exchange, whereas the PCAP in the `networkd` folder demonstrates the failure.

Specifically, in the file `v6LC_2_2_13b-Net0-20230707042202-filtered.pcapng`, packet 11 shows the RA setting `Cur hop limit: 100`. The ping reply in packet 13 shows networkd has not used the `Cur hop limit` from the RA and instead uses the value 64.

[2_2_13b - Router Advertisement Processing, Cur Hop Limit.zip](https://github.com/systemd/systemd/files/12075238/2_2_13b.-.Router.Advertisement.Processing.Cur.Hop.Limit.zip)

### Additional program output to the terminal or log subsystem illustrating the issue

Reference: [IPv6 Core Conformance Specification](https://www.ipv6ready.org/docs/Core_Conformance.pdf), Test v6LC.2.2.13, part B.

### LINKED ISSUE #28439: IPv6 Compliance RFC4191: Processing Router Advertisements with Router Preference (Host Only) [v6LC.2.2.22]
### systemd version the issue has been seen with

250

### Used distribution

Embedded Linux - Debian-based

### Linux kernel version used

5.15.71-rt51+gc36e774d0d9a

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

### Expected behaviour you didn't see

**Purpose**: Verify that the HUT uses a Default Router List with preference values for Type B Host.

When there are two routers on the network and Router1 sends an RA with `Reserved Route Preference`, meanwhile Router2 sends an RA with `Low Preference` route.  Later, Router2 changes from `Reserved` to `High` route preference. This change in preference route ought to result in the host sending to Router2 as the default route.  Instead, it continues to use Router1 as the default router.

From [RFC4191](https://www.rfc-editor.org/rfc/rfc4191.txt):

Section 2.1:
```
   Preference values are encoded as a two-bit signed integer, as
   follows:

      01      High
      00      Medium (default)
      11      Low
      10      Reserved - MUST NOT be sent
```

Section 2.2:
```
Prf (Route Preference)
    If the Reserved (10) value is received, the receiver MUST treat
    the value as if it were (00).
```

Section 3.1:

```
   Type B hosts use a Default Router List augmented with preference
   values, but ignore all Route Information Options.  They use the
   Default Router Preference value in the Router Advertisement header.
   They ignore Route Information Options.
```

### Unexpected behaviour you saw

The router with `Reserved Preference` was used instead of the `High Preference` router.

### Steps to reproduce the problem

Please find attached a zip file containing two PCAP files, `legacy` and `networkd`.  The `legacy` PCAP shows the correct behavior.  It was recorded when our host was configured using Debian's legacy `/etc/network/interfaces` file and `networkd` was disabled and stopped.  The `networkd` PCAP shows incorrect behavior. It was recorded after configuring `networkd` to manage the interface.

Under the `networkd` folder, the PCAP file `v6LC_2_2_22c-Net0-20230707043553-filtered.pcapng` shows the incorrect behaviour. 

Packet 1: Router1 sends an RA with a `Default Router Preference` equal `Reserved`.
Packet 2: Router2 sends an RA with a `Default Router Preference` equal to `Low`.
Packet 6: Router2 sends an RA with a `Default Router Preference` equal to `High`.
Packet 8: Ping reply is sent via Router1, when it should have been sent via Router2.

Compare that with the PCAP showing the correct behaviour in the `legacy` folder, `v6LC_2_2_22c-Net0-20230705084630.pcapng`.

Packet 1: Router1 sends an RA with a `Default Router Preference` equal `Reserved`.
Packet 2: Router2 sends an RA with a `Default Router Preference` equal to `Low`.
Packet 5: Router2 sends an RA with a `Default Router Preference` equal to `High`.
Packet 7: Ping reply is sent via Router2

[2_2_22c - Processing Router Advertisements with Router Preference.zip](https://github.com/systemd/systemd/files/12076148/2_2_22c.-.Processing.Router.Advertisements.with.Router.Preference.zip)

#### Changing Router Preference High to Low
I have second variation where the router preference for Router1 was changed from High to Low, meanwhile Router2 had a preference of Medium.  The host continues to choose Router1 as the default router, when it should be choosing Router2.  This suggests `networkd` is not updating the router preference.  See PCAP files in attached zip.

[2_2_22d - Processing Router Advertisements with Router Preference.zip](https://github.com/systemd/systemd/files/12076417/2_2_22d.-.Processing.Router.Advertisements.with.Router.Preference.zip)

#### Changing Router Low to High
A third variation has Router1 changing from Low to High, meanwhile Router 2 had a preference of Medium.  The host continues to choose Router2 when it should be choosing Router1.

[2_2_22e - Processing Router Advertisements with Router Preference.zip](https://github.com/systemd/systemd/files/12076622/2_2_22e.-.Processing.Router.Advertisements.with.Router.Preference.zip)

### LINKED ISSUE #28853: networkd: TCPCongestionControlAlgorithm change not applied on reload
### systemd version the issue has been seen with

254.1-1-arch

### Used distribution

ArchLinux

### Linux kernel version used

6.1.45-1-lts

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

On a `systemctl reload systemd-networkd` the live config should either match configfiles or an error message/non-zero return code should appear somewhere. 

In this particular case I'd like congestion control to get changed as described in the config file, route `metric` parameter should get dropped as specified in the updated config.

### Unexpected behaviour you saw

On removing `metric` parameter or when TCP changing congestion control algorithm is changed `networkd` silently ignores these changes. I suppose this happens for many other settings.

### Steps to reproduce the problem

1. Start with a network config like that:
```
[Match]
Name=wifi

[Link]
RequiredForOnline=yes
MTUBytes=1500

[Network]
DHCP=yes
DNSDefaultRoute=yes

DNS=9.9.9.9 149.112.112.112 2620:fe::fe 2620:fe::9
DNSOverTLS=no
DNSSEC=allow-downgrade
Domains=~.

[DHCPv4]
UseDNS=no
[DHCPv6]
UseDNS=no

[Route]
Gateway=172.31.3.1
Protocol=static
GatewayOnLink=yes
Scope=global
Metric=10
TCPCongestionControlAlgorithm=bbr
```

2. issue `systemctl reload systemd-networkd`
3. observe `networkd` add a new route with the required parameters
4. Drop the "metric" field from config, change `bbr` to `cubic`
5. issue `systemctl reload systemd-networkd`
6. Observe the `metric` field in the config still present, `bbr` still being the selected tcp congestion control algorithm, no mention of cubic
7. No errors in logs

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# ip r
default via 172.31.3.1 dev wifi proto dhcp src 172.31.3.180 metric 1024 
172.31.3.0/24 dev wifi proto kernel scope link src 172.31.3.180 metric 1024 
172.31.3.1 dev wifi proto dhcp scope link src 172.31.3.180 metric 1024 

root@ZGROZA:~
# systemctl reload systemd-networkd

root@ZGROZA:~
# ip r
default via 172.31.3.1 dev wifi proto static metric 10 onlink congctl bbr # good, expected
default via 172.31.3.1 dev wifi proto dhcp src 172.31.3.180 metric 1024 
172.31.3.0/24 dev wifi proto kernel scope link src 172.31.3.180 metric 1024 
172.31.3.1 dev wifi proto dhcp scope link src 172.31.3.180 metric 1024 

root@ZGROZA:~
# systemctl reload systemd-networkd

root@ZGROZA:~
# ip r
default via 172.31.3.1 dev wifi proto static metric 10 onlink congctl bbr # bad, expected congctl cubic
default via 172.31.3.1 dev wifi proto dhcp src 172.31.3.180 metric 1024 
172.31.3.0/24 dev wifi proto kernel scope link src 172.31.3.180 metric 1024 
172.31.3.1 dev wifi proto dhcp scope link src 172.31.3.180 metric 1024 

root@ZGROZA:~
# systemctl reload systemd-networkd

root@ZGROZA:~
# ip r
default via 172.31.3.1 dev wifi proto static metric 10 onlink congctl bbr # bad, expected cubic, no metric parameter 
default via 172.31.3.1 dev wifi proto dhcp src 172.31.3.180 metric 1024 
172.31.3.0/24 dev wifi proto kernel scope link src 172.31.3.180 metric 1024 
172.31.3.1 dev wifi proto dhcp scope link src 172.31.3.180 metric 1024 



sie 16 10:10:42 ZGROZA systemd[1]: Reloading Network Configuration...
sie 16 10:10:42 ZGROZA systemd[1]: Reloaded Network Configuration.
sie 16 10:10:42 ZGROZA systemd-networkd[2834]: wifi: Reconfiguring with /etc/systemd/network/wifi-general.network.
sie 16 10:10:42 ZGROZA systemd-networkd[2834]: wifi: DHCP lease lost
sie 16 10:10:42 ZGROZA systemd-networkd[2834]: wifi: DHCPv6 lease lost
sie 16 10:10:42 ZGROZA systemd-networkd[2834]: wifi: DHCPv4 address 172.31.3.180/24, gateway 172.31.3.1 acquired from 172.31.3.1

sie 16 10:10:59 ZGROZA systemd[1]: Reloading Network Configuration...
sie 16 10:10:59 ZGROZA systemd[1]: Reloaded Network Configuration.
sie 16 10:10:59 ZGROZA systemd-networkd[2834]: wifi: Reconfiguring with /etc/systemd/network/wifi-general.network.
sie 16 10:10:59 ZGROZA systemd-networkd[2834]: wifi: DHCP lease lost
sie 16 10:10:59 ZGROZA systemd-networkd[2834]: wifi: DHCPv6 lease lost
sie 16 10:10:59 ZGROZA systemd-networkd[2834]: wifi: DHCPv4 address 172.31.3.180/24, gateway 172.31.3.1 acquired from 172.31.3.1
sie 16 10:11:53 ZGROZA systemd[1]: Reloading Network Configuration...
sie 16 10:11:53 ZGROZA systemd[1]: Reloaded Network Configuration.
sie 16 10:11:53 ZGROZA systemd-networkd[2834]: wifi: Reconfiguring with /etc/systemd/network/wifi-general.network.
sie 16 10:11:53 ZGROZA systemd-networkd[2834]: wifi: DHCP lease lost
sie 16 10:11:53 ZGROZA systemd-networkd[2834]: wifi: DHCPv6 lease lost
sie 16 10:11:53 ZGROZA systemd-networkd[2834]: wifi: DHCPv4 address 172.31.3.180/24, gateway 172.31.3.1 acquired from 172.31.3.1
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #28426.
Fixes #28437.
Fixes #28439.
Fixes #28853.

### CODE REVIEW

File: src/network/networkd-ndisc.c [hunk 1]
```diff
@@ -441,6 +441,41 @@ static int ndisc_router_process_retransmission_time(Link *link, sd_ndisc_router
...
+        /* 0 is the unspecified value and must not be set (see RFC4861, 6.3.4):
+         *
+         * A Router Advertisement field (e.g., Cur Hop Limit, Reachable Time, and Retrans Timer) may contain
+         * a value denoting that it is unspecified. In such cases, the parameter should be ignored and the
+         * host should continue using whatever value it is already using. In particular, a host MUST NOT
+         * interpret the unspecified value as meaning change back to the default value that was in use before
+         * the first Router Advertisement was received.
+         *
+         * If the received Cur Hop Limit value is non-zero, the host SHOULD set
+         * its CurHopLimit variable to the received value.*/
```
Comment (LiveFreeAndRoam) [inline src/network/networkd-ndisc.c:511]: I really appreciate these explanatory comments. 👍

**Review by LiveFreeAndRoam — APPROVED** [review]
Looks good!

File: src/network/networkd-ndisc.c [hunk 2]
```diff
@@ -430,6 +441,41 @@ static int ndisc_router_process_retransmission_time(Link *link, sd_ndisc_router
...
+        if (hop_limit <= 0)
```
Comment (LiveFreeAndRoam) [inline src/network/networkd-ndisc.c:512]: BTW, I see this pattern of checking for negative values of unsigned variables in other functions.  Why check for negative values when it can never be negative?

File: src/network/networkd-ndisc.c (hunk 1 above)
Comment (yuwata) [reply src/network/networkd-ndisc.c:511]: I just copied RFC 🤪

File: src/network/networkd-ndisc.c (hunk 2 above)
Comment (yuwata) [reply src/network/networkd-ndisc.c:512]: Just for readability that we will never pass negative values to sysctl.

**Comment by yuwata** [comment]
(I will add test cases)

**Comment by poettering** [comment]
lgtm. if you add a testcase feel free to add green label?

**Comment by yuwata** [comment]
@LiveFreeAndRoam Please test again. Thank you.

**Comment by poettering** [comment]
lgtm

**Comment by LiveFreeAndRoam** [comment]
> @LiveFreeAndRoam Please test again. Thank you.

Will do. I'll be able to verify it by Tuesday, at the latest.

**Comment by bluca** [comment]
needs rebase to pick up test fixes

**Comment by yuwata** [comment]
@LiveFreeAndRoam Ping? (There's no need to rush, but for reminder.)

**Comment by LiveFreeAndRoam** [comment]
Apologies for the delay.

I have verified #28437 still passes.

I cloned your [repo ](https://github.com/yuwata/systemd) and checked out your [yuwata:network-route-check-conflict](https://github.com/yuwata/systemd/tree/network-route-check-conflict) branch and built from it. I then reran the IPv6 Logo test v6LC_2_2_13b and it passed.

Thank you for the fix @yuwata.

**Comment by yuwata** [comment]
@LiveFreeAndRoam Thank you!
