### PR TITLE
network: fix log message and man page for HopLimit=

### LINKED ISSUE #28899: network: per-route hop limit PR needs follow-ups
### systemd version the issue has been seen with

HEAD

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

See post-merge review https://github.com/systemd/systemd/pull/28871

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for 88c0642358398240a54d242e812439fcd0564b05.
Closes #28899.

### CODE REVIEW

File: src/network/networkd-route.c [hunk 1]
```diff
@@ -2573,17 +2573,17 @@ int config_parse_route_hop_limit(
         r = safe_atou32(rvalue, &k);
         if (r < 0) {
                 log_syntax(unit, LOG_WARNING, filename, line, r,
-                           "Could not parse route hop limit %s \"%s\", ignoring assignment: %m", lvalue, rvalue);
+                           "Could not parse per route hop limit, ignoring assignment: %s", rvalue);
```
Comment (keszybz) [inline src/network/networkd-route.c:2576]: I think that we have a general anti-pattern here: we should just say "Could not parse %s.%s …", section, lvalue". This is both easier for us (because we don't have to craft a custom error message), *and* easier for the user, because they don't have to try to guess what setting we were trying to describe.

I think we should rework most error messages like this. But we should probably do that in one big pull request. So let's merge this, since it fixes other issues too.

Comment (yuwata) [reply src/network/networkd-route.c:2576]: I agree. I will do that later.
