### PR TITLE
core: assign TTY to PAM context when TTYPath= is specified

### LINKED ISSUE #38486: core: custom graphical service no longer works
### systemd version the issue has been seen with

258-rc1

### Used distribution

Arch Linux

### Linux kernel version used

6.16.0

### CPU architectures issue was seen on

x86_64

### Component

systemd, systemd-logind

### Expected behaviour you didn't see

Starting a graphical service should work.

### Unexpected behaviour you saw

Starting a graphical service does not work.

I suspect latest changes in `systemd-logind` PAM sessions, but not sure.
Tried to apply patches from #38405, but that does not help.

### Steps to reproduce the problem

Here is an example of such service to start KDE Plasma:

```service
[Unit]
Description=KDE Plasma session for user %I
After=graphical.target systemd-user-sessions.service modprobe@drm.service
Conflicts=getty@tty1.service

[Service]
User=%i
WorkingDirectory=~

PAMName=login
TTYPath=/dev/tty1
UnsetEnvironment=TERM

StandardOutput=journal
ExecStart=/usr/bin/startplasma-wayland

[Install]
WantedBy=graphical.target
```

It worked fine in 257.7, but in 258-rc1 it does not work anymore. Judging by the logs, I assume apps basically can not find the display maybe?

```
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: wayland-egl, wayland, eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, xcb.
```

I tired some shenanigans with environment variables etc., but nothing helped. Maybe I'm just missing something?
Running `startplasma-wayland` manually from a tty works just fine.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #38486 again, which was fixed by 1405d46bf998b5a4b6f572a14ac88890828a405d, but regressed again by f875a8026ec2dfa6026da3ee216782e9f7c04a43.

Follow-up for f875a8026ec2dfa6026da3ee216782e9f7c04a43.

### CODE REVIEW

**Comment by yuwata** [comment]
The offending commit f875a8026ec2dfa6026da3ee216782e9f7c04a43 is unfortunately backported to v258.2, so please backport this to v258-stable repository.

**Comment by bluca** [comment]
This really needs a test as it keeps breaking

**Comment by yuwata** [comment]
> This really needs a test as it keeps breaking

Yeah, but I have no idea how to test it. Could you give me an idea?

**Comment by bluca** [comment]
I don't know either, I am really not familiar with all this TTY malarky

**Comment by HanabishiRecca** [comment]
I confirm that it fixes the issue. Thank you.

File: src/core/exec-invoke.c [hunk 1]
```diff
@@ -1237,7 +1237,11 @@ static int exec_context_get_tty_for_pam(const ExecContext *context, char **ret)
                 return 1;
         }
 
-        if (!IN_SET(context->std_input, EXEC_INPUT_TTY, EXEC_INPUT_TTY_FAIL, EXEC_INPUT_TTY_FORCE)) {
+        /* Do not implicitly configure TTY unless TTYPath= or StandardInput=tty is specified. See issue
+         * #39334. Note, exec_context_tty_path() returns "/dev/console" when TTYPath= is unspecified, hence
+         * explicitly check context->tty_path here. */
+        if (!context->tty_path &&
+            !IN_SET(context->std_input, EXEC_INPUT_TTY, EXEC_INPUT_TTY_FAIL, EXEC_INPUT_TTY_FORCE)) {
```
Comment (YHNdnzj) [inline src/core/exec-invoke.c]: while at it, use exec_input_is_terminal?
