### PR TITLE
vmspawn: Use host_device driver for --extra-drive block devices

### LINKED ISSUE #37986: vmspawn: Block devices don't work with --extra-drive=
### systemd version the issue has been seen with

main

### Used distribution

Arch

### Linux kernel version used

6.15.2-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-vmspawn

### Expected behaviour you didn't see

Per the documentation, `vmspawn`'s `--extra-drive=` option "Takes a disk image or block device on the host and supplies it to the virtual machine as another drive."

### Unexpected behaviour you saw

But QEMU fails with the following error message when I pass `--extra-drive=` a block device:

```
> systemd-vmspawn -i image.raw --extra-drive=/dev/loop1
qemu-system-x86_64: -blockdev driver=raw,cache.direct=off,cache.no-flush=on,file.driver=file,file.filename=/dev/loop1,node-name=vmspawn_extra_0: 'file' driver requires '/dev/loop1' to be a regular file
```

It seems like the raw driver doesn't support block devices, at least with the QEMU I'm running:

```
> qemu-system-x86_64 --version
QEMU emulator version 10.0.0
Copyright (c) 2003-2025 Fabrice Bellard and the QEMU Project developers
```

The [docs](https://www.qemu.org/docs/master/about/removed-features.html#drive-file-json-driver-file-removed-in-6-0) I found mention that the appropriate driver for block devices is `host_device`, and testing has confirmed that it works.

I've got a [PR](https://github.com/systemd/systemd/pull/37987) ready that sets the file/host_device driver based on regular/block, resp., and that solves the issue for me.

I'm hoping someone could try to reproduce this issue, maybe I've got something configured wrong.

### Steps to reproduce the problem

```
reprodir=$(mktemp -d)
cd $reprodir
mkosi --include=mkosi-vm
fallocate -l 64M extra.raw

# Works with a file:
systemd-vmspawn -i image.raw --extra-drive=extra.raw

loop=$(losetup -Pf --show extra.raw)
# Fails with a block device:
systemd-vmspawn -i image.raw --extra-drive="$loop"
# => qemu-system-x86_64: -blockdev driver=raw,cache.direct=off,cache.no-flush=on,file.driver=file,file.filename=/dev/loop1,node-name=vmspawn_extra_0: 'file' driver requires '/dev/loop1' to be a regular file
# Using the branch in the PR boots with the extra drive attached as expected

# Cleanup:
#losetup -d "$loop"
#rm -rf "$reprodir"
```

### PR DESCRIPTION
**Pull request by labichn**
Extra drives attached to VMs use the file driver for regular files and the host_device driver for block devices.

Fixes #37986

### CODE REVIEW

**Comment by labichn** [comment]
I went back and forth on whether `cache.no-flush=on` is appropriate for block devices. Let me know if I should change that value (or others) for block devices.

File: src/vmspawn/vmspawn.c [hunk 1]
```diff
@@ -2013,6 +2013,9 @@ static int run_virtual_machine(int kvm_device_fd, int vhost_device_fd) {
         size_t i = 0;
         STRV_FOREACH(drive, arg_extra_drives) {
                 _cleanup_free_ char *escaped_drive = NULL;
+                _cleanup_free_ char *driver = NULL;
```
Comment (poettering) [inline src/vmspawn/vmspawn.c]: please merge with previous line

File: src/vmspawn/vmspawn.c [hunk 2]
```diff
@@ -2022,7 +2025,21 @@ static int run_virtual_machine(int kvm_device_fd, int vhost_device_fd) {
                 if (!escaped_drive)
                         return log_oom();
 
-                r = strv_extendf(&cmdline, "driver=raw,cache.direct=off,cache.no-flush=on,file.driver=file,file.filename=%s,node-name=vmspawn_extra_%zu", escaped_drive, i);
+                fd = open(*drive, O_RDONLY | O_CLOEXEC);
```
Comment (poettering) [inline src/vmspawn/vmspawn.c]: any reason you are actually opening this here?

i mean, I am a big fan of pinning inodes via fds to avoid races. But you are not really doing this here: you open the inode, and the only op you do is fstat()... You might as well have used plain stat() instead of fstat() hence?

I mean, if we could pass an fd to the device to qemu (instead of a path), that'd be great, but i think we cannot actually do that. or can we? if we could then it would be great if we open the thing once, then do our check via it, and then pass it to qemu as open fd.

File: src/vmspawn/vmspawn.c [hunk 3]
```diff
@@ -2022,7 +2025,21 @@ static int run_virtual_machine(int kvm_device_fd, int vhost_device_fd) {
...
+                if (fd < 0)
+                        return log_error_errno(errno, "Failed to open '%s': %m", *drive);
+
+                if (fstat(fd, &st) < 0)
+                        return log_error_errno(errno, "Failed to stat '%s': %m", *drive);
+
+                if (S_ISREG(st.st_mode))
+                        driver = strdup("file");
+                else if (S_ISBLK(st.st_mode))
+                        driver = strdup("host_device");
```
Comment (poettering) [inline src/vmspawn/vmspawn.c]: why allocate a buffer for these? just make `driver` a `const char*` variable, and let it reference the literal strings instead of copies...

(also: if you use strdup() you must do an OOM check afterwards)

File: src/vmspawn/vmspawn.c (hunk 2 above)
Comment (labichn) [reply src/vmspawn/vmspawn.c]: No good reason, replaced with `stat` in 67d0fc1656e291edf98884518e457b2db1341b24 as sugggested, thanks.

File: src/vmspawn/vmspawn.c (hunk 3 above)
Comment (labichn) [reply src/vmspawn/vmspawn.c]: Addressed in 67d0fc1656e291edf98884518e457b2db1341b24.

File: src/vmspawn/vmspawn.c (hunk 1 above)
Comment (labichn) [reply src/vmspawn/vmspawn.c]: Changed `driver` to `const` in 67d0fc1656e291edf98884518e457b2db1341b24.
