### PR TITLE
network: fix several issues in config parser

### LINKED ISSUE #10615: There seems to be a memory leak in config_parse_hwaddr
I duplicated each line in the configs used by `systemd-networkd-tests.py` with
```
find ./conf/ -type f  | xargs perl -i -alpe 'print if !/^\[/'
```
and then I ran the test. `ASan` (which is having trouble unwinding the stack today for some unknown reason) reported a memory leak:
```sh
==6976==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 12 byte(s) in 2 object(s) allocated from:
    #0 0x7fb358d0ce50 in calloc (/lib64/libasan.so.5+0xeee50)
    #1 0x5600d8f8023f in config_parse_hwaddr ../src/libsystemd-network/network-internal.c:287
    #2 0x7fb357b33acc  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x720acc)
    #3 0x7fb357b34e77  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x721e77)
    #4 0x7fb357b35d89  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x722d89)
    #5 0x5600d8e5bd46 in netdev_load_one ../src/network/netdev/netdev.c:662
    #6 0x5600d8e5dc72 in netdev_load ../src/network/netdev/netdev.c:765
    #7 0x5600d8e13871 in manager_load_config ../src/network/networkd-manager.c:1497
    #8 0x5600d8dfe394 in main ../src/network/networkd.c:90
    #9 0x7fb35613711a in __libc_start_main (/lib64/libc.so.6+0x2311a)
Direct leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x7fb358d0ce50 in calloc (/lib64/libasan.so.5+0xeee50)
    #1 0x5600d8f8023f in config_parse_hwaddr ../src/libsystemd-network/network-internal.c:287
    #2 0x7fb357b33acc  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x720acc)
    #3 0x7fb357b34e77  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x721e77)
    #4 0x7fb357b35d89  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x722d89)
    #5 0x7fb357b36289  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x723289)
    #6 0x7fb357b36d73  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x723d73)
    #7 0x5600d8e5a858 in netdev_load_one ../src/network/netdev/netdev.c:621
    #8 0x5600d8e5dc72 in netdev_load ../src/network/netdev/netdev.c:765
    #9 0x5600d8e13871 in manager_load_config ../src/network/networkd-manager.c:1497
    #10 0x5600d8dfe394 in main ../src/network/networkd.c:90
    #11 0x7fb35613711a in __libc_start_main (/lib64/libc.so.6+0x2311a)
SUMMARY: AddressSanitizer: 18 byte(s) leaked in 3 allocation(s).
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #10615.

### CODE REVIEW

**Comment by yuwata** [comment]
The CI failure is unrelated: TEST-17-UDEV-WANT timeouts.

@evverx Could you also review this?

File: src/network/networkd-network.c [hunk 1]
```diff
@@ -607,14 +607,17 @@ int config_parse_netdev(const char *unit,
 
         switch (kind) {
         case NETDEV_KIND_BRIDGE:
+                network->bridge = netdev_unref(network->bridge);
```
Comment (evverx) [inline src/network/networkd-network.c:610]: It's more of a question :-) I'm wondering if it's possible to trigger the leak in practice. I can't seem to find a way to do it easily. The commit message says that the leak is possible but how possible is it?

**Comment by evverx** [comment]
@yuwata thank you! I'll take a closer look tomorrow. I'm far from my laptop right now.

File: src/network/networkd-network.c (hunk 1 above)
Comment (yuwata) [reply src/network/networkd-network.c:610]: Yeah, fortunately, missing `netdev_unref()` here does not cause memleak, as `manager_free()` uses
```
        while ((netdev = hashmap_first(m->netdevs)))
                netdev_unref(netdev);
```
instead of 
```
        while ((netdev = hashmap_steal_first(m->netdevs)))
                netdev_unref(netdev);
```
But, without this fix, actually the reference counter of the netdev increases with the number of `Bridge=` lines.

File: src/network/networkd-radv.c [hunk 2]
```diff
@@ -27,29 +40,22 @@ int config_parse_router_prefix_delegation(
...
         assert(lvalue);
         assert(rvalue);
         assert(data);
 
-        if (streq(rvalue, "static"))
-                network->router_prefix_delegation = RADV_PREFIX_DELEGATION_STATIC;
-        else if (streq(rvalue, "dhcpv6"))
-                network->router_prefix_delegation = RADV_PREFIX_DELEGATION_DHCP6;
-        else {
-                d = parse_boolean(rvalue);
```
Comment (evverx) [inline src/network/networkd-radv.c:43]: I don't think we can just replace this with "yes" and "no" without breaking backwards compatibility. `parse_boolean` also takes `1`, `y`, `true`, `0`, `n`, `false` and so on. In theory, it's possible to update `radv_prefix_delegation_table`, but it would be hard to keep up with `parse_boolean` should anyone decide to extend it in the future. I'd leave it as is.

File: test/test-network/conf/dhcp-client-timezone-router.network [hunk 3]
```diff
@@ -4,5 +4,7 @@ Name=veth99
 [Network]
 IPv6AcceptRA=false
 DHCP=ipv4
+
+[DHCP]
```
Comment (evverx) [inline test/test-network/conf/dhcp-client-timezone-router.network:8]: I find it weird that the test passes with or without this line :-) It seems to me that this section isn't covered by the test at all.

File: src/network/networkd-radv.c (hunk 2 above)
Comment (yuwata) [reply src/network/networkd-radv.c:43]: I thought that `DEFINE_STRING_TABLE_LOOKUP_WITH_BOOLEAN` treats such words correctly... But I have not tested that on this setting. I will test them.

Comment (evverx) [reply src/network/networkd-radv.c:43]: I'm sorry. I totally missed the `WITH_BOOLEAN` part.

File: test/test-network/conf/dhcp-client-timezone-router.network (hunk 3 above)
Comment (yuwata) [reply test/test-network/conf/dhcp-client-timezone-router.network:8]: Is it? Without this, at least on fedora 28, the tests using this conf file logs something in the journal.

Comment (evverx) [reply test/test-network/conf/dhcp-client-timezone-router.network:8]: But none of the tests fails as far as know. Nobody looks at the journal if nothing fails :-)

Comment (evverx) [reply test/test-network/conf/dhcp-client-timezone-router.network:8]: I guess the same goes for the issue fixed in https://github.com/systemd/systemd/pull/10618/commits/f7601e3a4fb4a611b60d4fe997ab1162941ccc8f. It's true that `networkd` complains loudly:
```sh
/run/systemd/network/25-geneve.netdev:10: Unknown lvalue 'UDP6ZeroChecksumTx' in section 'GENEVE'
/run/systemd/network/25-geneve.netdev:11: Unknown lvalue 'UDP6ZeroChecksumRx' in section 'GENEVE'
/run/systemd/network/25-geneve.netdev:10: Unknown lvalue 'UDP6ZeroChecksumTx' in section 'GENEVE'
/run/systemd/network/25-geneve.netdev:11: Unknown lvalue 'UDP6ZeroChecksumRx' in section 'GENEVE'
```
but the test passes no matter what is used in the config.

Comment (evverx) [reply test/test-network/conf/dhcp-client-timezone-router.network:8]: Anyway, strictly speaking, that has nothing to do with the PR and can be safely ignored :-)

File: src/libsystemd-network/network-internal.c [hunk 4]
```diff
@@ -255,11 +255,10 @@ int config_parse_ifalias(const char *unit,
...
         }
 
-        free(*s);
-        if (*n)
-                *s = TAKE_PTR(n);
+        if (isempty(n))
+                *s = mfree(*s);
         else
-                *s = NULL;
+                free_and_replace(*s, n);
```
Comment (evverx) [inline src/libsystemd-network/network-internal.c:261]: This block looks strange because `free_and_replace` is used everywhere else. Is there something special about `ifalias` or is the handling of an empty string not correct in the other places?

Comment (evverx) [reply src/libsystemd-network/network-internal.c:261]: Then again, the comment above, technically, has nothing to do with the PR. The `if` block has always been here.

**Comment by yuwata** [comment]
@evverx I've added commits that address recent your issues. PTAL.

File: src/network/netdev/wireguard.c [hunk 5]
```diff
@@ -249,8 +250,7 @@ static int wireguard_resolve_handler(sd_resolve_query *q,
 
         if (ret != 0) {
                 log_netdev_error(netdev, "Failed to resolve host '%s:%s': %s", e->host, e->port, gai_strerror(ret));
-                LIST_PREPEND(endpoints, w->failed_endpoints, e);
-                e = NULL;
+                LIST_PREPEND(endpoints, w->failed_endpoints, TAKE_PTR(e));
```
Comment (Mic92) [inline src/network/netdev/wireguard.c]: ok.

File: src/network/netdev/wireguard.c [hunk 6]
```diff
@@ -613,8 +613,7 @@ int config_parse_wireguard_endpoint(const char *unit,
         endpoint->host = TAKE_PTR(host);
         endpoint->port = TAKE_PTR(port);
         endpoint->netdev = netdev_ref(data);
-        LIST_PREPEND(endpoints, w->unresolved_endpoints, endpoint);
-        endpoint = NULL;
+        LIST_PREPEND(endpoints, w->unresolved_endpoints, TAKE_PTR(endpoint));
```
Comment (Mic92) [inline src/network/netdev/wireguard.c]: ok.

File: src/network/netdev/wireguard.c [hunk 7]
```diff
@@ -687,6 +688,16 @@ static void wireguard_done(NetDev *netdev) {
                 }
                 free(peer);
         }
+
+        while ((e = w->unresolved_endpoints)) {
```
Comment (Mic92) [inline src/network/netdev/wireguard.c]: For this to work, it must be ensured that the timer that resolves endpoints no longer tries to access the data here. I have to recheck if that is the case when `sd_event_source_unref` is applied on it.

File: src/network/netdev/wireguard.c [hunk 8]
```diff
@@ -213,6 +213,7 @@ static int on_resolve_retry(sd_event_source *s, usec_t usec, void *userdata) {
 
         w->resolve_retry_event_source = sd_event_source_unref(w->resolve_retry_event_source);
 
+        assert(!w->unresolved_endpoints);
```
Comment (Mic92) [inline src/network/netdev/wireguard.c]: I double checked but did not found a case where this could happen, since `on_resolve_retry` is only scheduled when all previous endpoints have been resolved. It is still a good idea though to have this here.

File: src/network/netdev/wireguard.c (hunk 5 above)
Comment (Mic92) [inline src/network/netdev/wireguard.c]: ok

File: src/network/netdev/wireguard.c (hunk 6 above)
Comment (Mic92) [inline src/network/netdev/wireguard.c]: ok.

File: src/network/netdev/wireguard.c [hunk 9]
```diff
@@ -673,10 +672,12 @@ static void wireguard_done(NetDev *netdev) {
         Wireguard *w;
         WireguardPeer *peer;
         WireguardIPmask *mask;
+        WireguardEndpoint *e;
 
         assert(netdev);
         w = WIREGUARD(netdev);
-        assert(!w->unresolved_endpoints);
+        assert(w);
```
Comment (Mic92) [inline src/network/netdev/wireguard.c]: ok.

File: src/network/netdev/wireguard.c (hunk 7 above)
Comment (Mic92) [reply src/network/netdev/wireguard.c]: From `sd_event_source_unref(3)`:

      Note that event source objects stay alive and may be dispatched as long
       as they have a reference counter greater than zero. In order to drop a
       reference of an event source and make sure the associated event source
       handler function is not called anymore it is recommended to combine a
       call of sd_event_source_unref() with a prior call to
       sd_event_source_set_enabled() with SD_EVENT_OFF.

Can you also call `sd_event_source_set_enabled` in this case?

**Comment by Mic92** [comment]
Might be for you interest: cc @zx2c4

File: src/network/netdev/wireguard.c (hunk 7 above)
Comment (yuwata) [reply src/network/netdev/wireguard.c]: In general, if we want to disable an event, actually `sd_event_source_set_enabled()` needs to be called. But, in this case, the `sd_event_source` object is referenced only by `Wireguard`. So, it is not necessary to call the function, that is, `sd_event_source_unref()` is enough here.

We usually do not call `sd_event_source_set_enabled()` in the similar cases.

**Comment by yuwata** [comment]
@Mic92 Thank you for the review. I noticed that `resolve_query` is not unreffed. I've added a tiny commit for that.

File: src/network/netdev/wireguard.c [hunk 10]
```diff
@@ -282,37 +282,42 @@ static int wireguard_resolve_handler(sd_resolve_query *q,
...
                                            endpoint->host,
                                            endpoint->port,
                                            &hints,
                                            wireguard_resolve_handler,
                                            endpoint);
 
-                if (r == -ENOBUFS)
-                        break;
+                if (k == -ENOBUFS)
+                        return k;
```
Comment (Mic92) [inline src/network/netdev/wireguard.c]: There is a limit of concurrent allowed queries. The break is needed if an endpoint exceed this limit (i.e. an endpoint can have 10000 of peers). Therefore please revert this last commit.

Comment (yuwata) [reply src/network/netdev/wireguard.c]: Ah, I see. Thanks. Dropped.

**Comment by evverx** [comment]
@Mic92 I've just added a basic test for wireguard in https://github.com/systemd/systemd/pull/10631. It'd be great to extend it a bit in the future so that it would make a little bit more sense. For now, it helps to trigger a memory leak when `wireguard` is available (I'm not sure whether it is fixed here):
```sh
==23779==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fc77b1f7e50 in calloc (/lib64/libasan.so.5+0xeee50)
    #1 0x55b8e3b4f80a in config_parse_wireguard_endpoint ../src/network/netdev/wireguard.c:575
    #2 0x7fc77a01eacc  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x720acc)
    #3 0x7fc77a01fe77  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x721e77)
    #4 0x7fc77a020d89  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x722d89)
    #5 0x55b8e3b2c5a4 in netdev_load_one ../src/network/netdev/netdev.c:662
    #6 0x55b8e3b2e4d0 in netdev_load ../src/network/netdev/netdev.c:765
    #7 0x55b8e3ae4131 in manager_load_config ../src/network/networkd-manager.c:1497
    #8 0x55b8e3acec54 in main ../src/network/networkd.c:90
    #9 0x7fc77862211a in __libc_start_main (/lib64/libc.so.6+0x2311a)
Indirect leak of 22 byte(s) in 1 object(s) allocated from:
    #0 0x7fc77b1f7c48 in malloc (/lib64/libasan.so.5+0xeec48)
    #1 0x7fc77b1b68bc  (/lib64/libasan.so.5+0xad8bc)
    #2 0x55b8e3b4fe65 in config_parse_wireguard_endpoint ../src/network/netdev/wireguard.c:604
    #3 0x7fc77a01eacc  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x720acc)
    #4 0x7fc77a01fe77  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x721e77)
    #5 0x7fc77a020d89  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x722d89)
    #6 0x55b8e3b2c5a4 in netdev_load_one ../src/network/netdev/netdev.c:662
    #7 0x55b8e3b2e4d0 in netdev_load ../src/network/netdev/netdev.c:765
    #8 0x55b8e3ae4131 in manager_load_config ../src/network/networkd-manager.c:1497
    #9 0x55b8e3acec54 in main ../src/network/networkd.c:90
    #10 0x7fc77862211a in __libc_start_main (/lib64/libc.so.6+0x2311a)
Indirect leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x7fc77b144320 in strdup (/lib64/libasan.so.5+0x3b320)
    #1 0x55b8e3b4fee9 in config_parse_wireguard_endpoint ../src/network/netdev/wireguard.c:608
    #2 0x7fc77a01eacc  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x720acc)
    #3 0x7fc77a01fe77  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x721e77)
    #4 0x7fc77a020d89  (/home/vagrant/systemd/build/src/shared/libsystemd-shared-239.so+0x722d89)
    #5 0x55b8e3b2c5a4 in netdev_load_one ../src/network/netdev/netdev.c:662
    #6 0x55b8e3b2e4d0 in netdev_load ../src/network/netdev/netdev.c:765
    #7 0x55b8e3ae4131 in manager_load_config ../src/network/networkd-manager.c:1497
    #8 0x55b8e3acec54 in main ../src/network/networkd.c:90
    #9 0x7fc77862211a in __libc_start_main (/lib64/libc.so.6+0x2311a)
SUMMARY: AddressSanitizer: 76 byte(s) leaked in 3 allocation(s).
SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-networkd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by evverx** [comment]
@Mic92 and thank you for taking a look!

**Comment by evverx** [comment]
@Mic92 the test runs a fully functional instance of `systemd-networkd` on a machine so it's more or less "real" environment. Here's what the test itself prints:
```sh
test_wireguard (__main__.NetworkdNetDevTests) ... interface: wg99
  public key: clei1xcOL9V1BVgBlS8UN4ehzqq0ShJ92i543AGh2hU=
  private key: (hidden)
  listening port: 51820

peer: RDf+LSpeEre7YEIKaxg+wbpsNV7du+ktR99uBEtIiCA=
  allowed ips: 192.168.26.0/24, fd31:bf08:57cb::/48
ok

----------------------------------------------------------------------
Ran 1 test in 5.191s
```
And the following is the output of `systemd-networkd`:
```sh
wg99: netdev ready
eth1: Gained IPv6LL
eth0: Gained IPv6LL
Enumeration completed
Started Network Service.
SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-networkd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
wg99: Failed to resolve host 'wireguard.example.com:51820': Name or service not known
pam_unix(sudo:session): session closed for user root
USER_END pid=23906 uid=0 auid=1000 ses=4 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix a>
CRED_DISP pid=23906 uid=0 auid=1000 ses=4 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_env,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? termin>
wg99: Failed to resolve host 'wireguard.example.com:51820': Name or service not known
Selected source 217.70.19.12
Source 188.93.104.2 replaced with 78.140.251.2
```

> Can we get the wireguard related changes into a different pull request?

I think it's a good idea!

**Comment by Mic92** [comment]
ok. The error then makes sense to me, because the endpoint is not resolved it will stuck the in retry queue
and wireguard_endpoint is not freed on termination. In this pull request the loop that frees unresolved_endpoints will also call `wireguard_endpoint_free` so this should issue should be solved as well.

**Comment by evverx** [comment]
> The error then makes sense to me, because the endpoint is not resolved it will stuck the in retry queue and wireguard_endpoint is not freed on termination

That's basically why I think that the test needs a bit tweaking to be more useful :-) I just copy-pasted the config from the documentation.

**Comment by yuwata** [comment]
Ugh, my fix about wireguard causes segfault... I will try to update them.

**Comment by evverx** [comment]
@yuwata segfaults are more predictable than assertions that can be compiled out so I'd say the stability has been improved :-)

**Comment by yuwata** [comment]
Hmm, I think the wireguard issue needs much work than I initially expected. @Mic92 I will split them to another PR later.

**Comment by yuwata** [comment]
The last 3 commits for wireguard are now moved to #10632.

**Comment by evverx** [comment]
By the way, @yuwata I've just opened https://github.com/systemd/systemd/pull/10640 where you can find the fuzzers I was talking about.

**Comment by yuwata** [comment]
@evverx Do you think it is good to merge?
