### PR TITLE
udev-builtin-kmod: support to run without arguments

### LINKED ISSUE #24715: udev does not load module if modalias contains a single quote '\''
### systemd version the issue has been seen with

251.4

### Used distribution

Fedora 37

### Linux kernel version used

5.19.? and 6.0.0-rc?

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

msi-laptop module does not get autoloaded when it should.

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

On a MSI S270 laptop the dmi modalias is:

 ```
# cat /sys/class/dmi/id/modalias
dmi:bvnAmericanMegatrendsInc.:bvrA1013AMSV4.30:bd01/09/2006:svnMICRO-STARINT'LCO.,LTD:pnMS-1013:pvr0131:cvnMICRO-STARINT'LCO.,LTD:ct10:cvrN/A:
```

And one of the module aliases for the msi-laptop kernel module is:

```
dmi*:svn*MICRO-STARINT'LCO.,LTD*:pn*MS-1013*:pvr*0131*:cvn*MICRO-STARINT'LCO.,LTD*:
```

Yet the module does not autoload, while:

```
modprobe `cat /sys/class/dmi/id/modalias`
```

does cause it to autoload.

On a hunch I dropped the `'LCO.,LTD` part of the DMI strings in the kernel module, so that the module modalias now is:

```
dmi*:svn*MICRO-STARINT*:pn*MS-1013*:pvr*0131*:cvn*MICRO-STARINT*:
```

And that works around this issue.

I have the feeling that udevd is doing something wrong with escaping the `'` char, perhaps passing something like:
```
dmi:bvnAmericanMegatrendsInc.:bvrA1013AMSV4.30:bd01/09/2006:svnMICRO-STARINT\'LCO.,LTD:pnMS-1013:pvr0131:cvnMICRO-STARINT\'LCO.,LTD:ct10:cvrN/A:
```

to the modprobe command. Notice the backslashes there which should not be there. These extra backslashes are causing the msi-laptop alias to not match the modalias (as passed to modprobe). By changing the msi-laptop alias to instead of `'LCO.,LTD` accepting a wildcard (`*`) in that part of the alias the extra escaping does not matter and the module does auto-load correctly.

Note this addition of extra blackslashes to escape the `'` is only a theory I have not confirmed this is actually happening in any way.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
If no module name is provided, then try to load modules based on the device modealias.

Previously, MODALIAS property is passed as an argument, but it may contain quotation. Hence, unfortunately the modalias may be modified and cannot load expected modules.

Fixes #24715.

### CODE REVIEW

**Comment by jwrdegoede** [comment]
Good idea to avoid the quotes being stripped fro the modalias by making the kmod builtin load it itself.

Thank you for working on this.

File: src/udev/udev-builtin-kmod.c [hunk 1]
```diff
@@ -21,15 +23,29 @@ _printf_(6,0) static void udev_kmod_log(void *data, int priority, const char *fi
...
+        if (strv_isempty(modules)) {
+                const char *modalias;
+
+                r = sd_device_get_property_value(dev, "MODALIAS", &modalias);
+                if (r < 0)
+                        return log_device_warning_errno(dev, r, "Failed to read property \"MODALIAS\".");
 
-        for (int i = 2; argv[i]; i++)
-                (void) module_load_and_warn(ctx, argv[i], false);
+                (void) module_load_and_warn(ctx, modalias, false);
```
Comment (bluca) [inline src/udev/udev-builtin-kmod.c]: can modalias list more than one module here?

Comment (yuwata) [reply src/udev/udev-builtin-kmod.c]: modalias is not a module list, but string something like the following:
```
MODALIAS=dmi:bvnAmericanMegatrendsInc.:bvrA1013AMSV4.30:bd01/09/2006:svnMICRO-STARINT'LCO.,LTD:pnMS-1013:pvr0131:cvnMICRO-STARINT'LCO.,LTD:ct10:cvrN/A:
```

**Review by bluca — APPROVED** [review]

File: src/udev/udev-builtin-kmod.c [hunk 2]
```diff
@@ -21,15 +23,29 @@ _printf_(6,0) static void udev_kmod_log(void *data, int priority, const char *fi
...
+
+        assert(dev);
+
         if (!ctx)
                 return 0;
 
-        if (argc < 3 || !streq(argv[1], "load"))
-                return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
-                                       "%s: expected: load <module>…", argv[0]);
+        if (!streq(argv[1], "load"))
```
Comment (poettering) [inline src/udev/udev-builtin-kmod.c]: what happened to the argc check?

File: src/udev/udev-builtin-kmod.c (hunk 1 above)
Comment (poettering) [inline src/udev/udev-builtin-kmod.c]: if you touch this, maybe add `/* verbose= */` before the last argument

**Comment by yuwata** [comment]
Addressed the comments by @poettering. PTAL.

**Comment by poettering** [comment]
lgtm, thanks!
