### PR TITLE
network/tuntap: verify User=/Group= earlier and refuse non-system users/groups

### LINKED ISSUE #37279: systemd-networkd ignores systemd-homed users
### systemd version the issue has been seen with

252

### Used distribution

Debian 12

### Linux kernel version used

6.6.72-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

User= and Group= directives work for all users.

### Unexpected behaviour you saw

`systemd-networkd[470]: vpn0: Cannot resolve user name test: No such process`

### Steps to reproduce the problem

Create tunnel device for VPN with user & group directives using user from systemd-homed instead of regular system user:
```
[NetDev]
Name=vpn0
Kind=tun

[Tun]
User=test
Group=test
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
homectl create test

```

### PR DESCRIPTION
**Pull request by yuwata**
Similar to #36123.
Closes #37279.

### CODE REVIEW

File: src/network/netdev/tuntap.c [hunk 1]
```diff
@@ -241,6 +227,28 @@ static int tuntap_verify(NetDev *netdev, const char *filename) {
                                    "Please set it in the corresponding .network file.",
                                    netdev_kind_to_string(netdev->kind), filename);
 
+        if (t->user_name) {
+                const char *user = t->user_name;
+                uid_t uid;
+
+                r = get_user_creds(&user, &uid, NULL, NULL, NULL, USER_CREDS_ALLOW_MISSING);
```
Comment (poettering) [inline src/network/netdev/tuntap.c]: maybe prefix the 3rd, 4th, 5th parameter with `/* ret_gid= */` style comments, as usual, if you touch this?

File: src/network/netdev/tuntap.c [hunk 2]
```diff
@@ -234,6 +236,8 @@ static int tuntap_verify(NetDev *netdev, const char *filename) {
                 r = get_user_creds(&user, &uid, NULL, NULL, NULL, USER_CREDS_ALLOW_MISSING);
                 if (r < 0)
                         log_netdev_warning_errno(netdev, r, "Cannot resolve user name %s, ignoring: %m", t->user_name);
+                else if (!uid_is_system(uid))
+                        log_netdev_warning(netdev, "User '%s' is not a system user (UID="UID_FMT"), ignoring.", t->user_name, uid);
```
Comment (poettering) [inline src/network/netdev/tuntap.c]: this looks fine, but I figure sooner or later we should probably switch more things over to doing userdb_by_name() and then using user_record_disposition() to determine if the user is a system user. This has the benefit that user database provides can tightly control on their own how they want a user categorized.

Comment (yuwata) [reply src/network/netdev/tuntap.c]: OK. I will try.

**Comment by yuwata** [comment]
@poettering Now usedb_by_name()/groupdb_by_name() are used. PTAL.

File: src/network/netdev/tuntap.c [hunk 3]
```diff
@@ -228,19 +228,29 @@ static int tuntap_verify(NetDev *netdev, const char *filename) {
 
         if (t->user_name) {
                 UserRecord *ur;
+                UserDBMatch match = USERDB_MATCH_NULL;
 
-                r = userdb_by_name(t->user_name, /* match = */ NULL, USERDB_PARSE_NUMERIC, &ur);
-                if (r < 0)
+                match.disposition_mask = UINT64_C(1) << USER_SYSTEM;
```
Comment (poettering) [inline src/network/netdev/tuntap.c]: ah, nice use of the UserDBMatch stuff, i didn't even think of that.
