### PR TITLE
fstab-generator: use correct targets when /sysroot is specificied in fstab only

### LINKED ISSUE #3551: RFE: when fstab-generator is run in initrd, accept fstab entry for /sysroot as equivalent to root= kernel cmdline param
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)
### systemd version the issue has been seen with

230
### distribution

arch linux
### proposal

1) currently `add_sysroot_mount()`:
https://github.com/systemd/systemd/blob/master/src/fstab-generator/fstab-generator.c#L489
will only be invoked when kernel `root=` parameter is present, 
which is not a required kernel parameter when using `systemd` as `/init`:
http://unix.stackexchange.com/questions/289672/kernel-init-without-root-parameter

2) we propose to allow extra configuration sources for the `root=`, 
for example, use special entry `/sysroot` in the `/etc/fstab`
https://github.com/random-archer/mkinitcpio-systemd-tool/blob/master/fstab

```
#  <file system>        <dir>      <type>    <option>         <dump> <pass>
 /dev/mapper/root     /sysroot    ext4      defaults,ro        0     1
```

### PR DESCRIPTION
**Pull request by lilyinstarlight**
See #3551 for context, but basically this treats the `/sysroot` entry (and `/sysroot/usr`) in the initrd fstab equivalently to `root=` (and `mount.usr=`) on the kernel cmdline

I additionally adjusted the existing fstab-generator tests to support testing an fstab file in addition to the existing support for testing kernel cmdline parameters (and added a test to ensure this /sysroot behavior). If I need to adjust the convention for that or add a new test script instead of expanding the existing one, then I can make that change

I had to add an environment variable for fstab-generator tests (`SYSTEMD_SYSFS_CHECK`) to ensure it parses all entries, including /dev ones, even when it is detected as being inside of a container (such as the environment mkosi runs the tests in)

It would be nice if fstab and kernel cmdline processing shared more of their code-paths so we wouldn't have to duplicate behavior like this, but this PR is at least a short-term fix to the problem (and I am *definitely* not confident enough in my skill to make any major changes/refactors to systemd 😅)

Fixes #3551

### CODE REVIEW

**Comment by YHNdnzj** [comment]
Such usage could use some documentation?

And maybe also add a check for `root=fstab` similar to `root=gpt-auto` to allow using fstab in initrd explicitly?

File: src/fstab-generator/fstab-generator.c [hunk 1]
```diff
@@ -744,11 +749,22 @@ static int parse_fstab(bool initrd) {
                         flags |= rw_only * MOUNT_RW_ONLY |
                                  automount * MOUNT_AUTOMOUNT;
 
+                        is_sysroot = path_equal(where, "/sysroot");
+                        is_sysroot_usr = path_equal(where, "/sysroot/usr");
+
                         const char *target_unit =
                                 initrd ?               SPECIAL_INITRD_FS_TARGET :
+                                is_sysroot ?           SPECIAL_INITRD_ROOT_FS_TARGET :
+                                is_sysroot_usr ?       SPECIAL_INITRD_USR_FS_TARGET :
```
Comment (YHNdnzj) [inline src/fstab-generator/fstab-generator.c:796]: It seems that the split `usr` fs has a special handling:
https://github.com/systemd/systemd/blob/c41fff1e0897df5731881225d831febaebf70413/src/fstab-generator/fstab-generator.c#L979-L984

Comment (lilyinstarlight) [reply src/fstab-generator/fstab-generator.c:796]: Ah, so it does! I looked less closely at that one (since I was mostly interested in just root fs). I'll make an update that can equivalently cover that case as well sometime in the next day or so

**Comment by lilyinstarlight** [comment]
> Such usage could use some documentation?

Documentation like in the systemd-fstab-generator(8) manual page that /sysroot is treated equivalently, or somewhere else?

> And maybe also add a check for `root=fstab` similar to `root=gpt-auto` to allow using the fstab in initrd explicitly?

I can possibly do that if that is preferred. Would that mean it wouldn't use `initrd-root-fs.target`/`initrd-root-device.target` for the `/sysroot` entry in fstab unless `root=fstab` is specified on kernel command line?

**Comment by YHNdnzj** [comment]
> I can possibly do that if that is preferred. Would that mean it wouldn't use initrd-root-fs.target/initrd-root-device.target for the /sysroot entry in fstab unless root=fstab is specified on kernel command line?

Nope, `gpt-auto` automatically handles rootfs mount even if `root=gpt-auto` isn't set too. Just allow those interested to use it as a hint, in order to make this more obvious in their setups :)

> Documentation like in the systemd-fstab-generator(8) manual page that /sysroot is treated equivalently, or somewhere else?

https://github.com/systemd/systemd/blob/b66a6e1a5838b874b789820c090dd6850cf10513/man/systemd-fstab-generator.xml#L82-L88

I guess a short comment like the `gpt-auto` one will do, i.e. mention that `root=fstab` uses the `/sysroot` entry in the initrd fstab.

File: src/fstab-generator/fstab-generator.c (hunk 1 above)
Comment (lilyinstarlight) [reply src/fstab-generator/fstab-generator.c:796]: Should be fixed now

**Comment by lilyinstarlight** [comment]
I've implemented the above `root=fstab` and documentation suggestions, and I fixed the `/sysroot/usr` semantics

Thank you for the feedback!

File: src/fstab-generator/fstab-generator.c [hunk 2]
```diff
@@ -838,6 +874,11 @@ static int add_sysroot_mount(void) {
                 log_debug("Skipping root directory handling, as gpt-auto was requested.");
                 return 0;
         }
+        else if (streq(arg_root_what, "fstab")) {
```
Comment (YHNdnzj) [inline src/fstab-generator/fstab-generator.c]: systemd's coding style requires the `else` to be on the same line as `}`, i.e.

```suggestion
        } else if (streq(arg_root_what, "fstab")) {
```

See also: https://systemd.io/CODING_STYLE/

File: src/fstab-generator/fstab-generator.c [hunk 3]
```diff
@@ -958,6 +999,12 @@ static int add_sysroot_usr_mount(void) {
                 return 1; /* systemd-gpt-auto-generator will generate a unit for this, hence report that a
                            * unit file is being created for the host /usr/ mount. */
         }
+        else if (streq(arg_usr_what, "fstab")) {
```
Comment (YHNdnzj) [inline src/fstab-generator/fstab-generator.c]: Same :)

**Review by YHNdnzj — COMMENTED** [review]
Let's wait for reviews from systemd members now :p

File: src/fstab-generator/fstab-generator.c (hunk 2 above)
Comment (lilyinstarlight) [reply src/fstab-generator/fstab-generator.c]: Oops I even read that document, but I guess habit still took over. Thank you for the catch!

**Comment by lilyinstarlight** [comment]
I rebased to resolve a minor conflict in `src/fstab-generator/fstab-generator.c`

File: src/fstab-generator/fstab-generator.c [hunk 4]
```diff
@@ -763,21 +763,52 @@ static int parse_fstab(bool initrd) {
...
                                       flags,
                                       target_unit);
+
+                        if (is_sysroot_usr && k >= 0) {
+                                log_debug("Synthesizing fstab entry what=/sysusr/usr where=/sysroot/usr opts=bind");
+
+                                r = add_mount(fstab,
+                                              arg_dest,
+                                              "/sysusr/usr",
+                                              canonical_where?: where,
```
Comment (keszybz) [inline src/fstab-generator/fstab-generator.c]: Missing space before '?'.

File: src/fstab-generator/fstab-generator.c [hunk 5]
```diff
@@ -856,6 +887,10 @@ static int add_sysroot_mount(void) {
                 /* This is handled by gpt-auto-generator */
                 log_debug("Skipping root directory handling, as gpt-auto was requested.");
                 return 0;
+        } else if (streq(arg_root_what, "fstab")) {
+                /* This is handled by parse_fstab */
+                log_debug("Using fstab for root directory handling as requested.");
```
Comment (keszybz) [inline src/fstab-generator/fstab-generator.c]: Maybe "initrd's fstab" for clarity?
"Using initrd's fstab for /sysroot/ configuration" ?

File: src/fstab-generator/fstab-generator.c [hunk 6]
```diff
@@ -976,6 +1011,11 @@ static int add_sysroot_usr_mount(void) {
                 log_debug("Skipping /usr/ directory handling, as gpt-auto was requested.");
                 return 1; /* systemd-gpt-auto-generator will generate a unit for this, hence report that a
                            * unit file is being created for the host /usr/ mount. */
+        } else if (streq(arg_usr_what, "fstab")) {
+                /* This is handled by parse_fstab */
+                log_debug("Using fstab for /usr/ directory handling as requested.");
```
Comment (keszybz) [inline src/fstab-generator/fstab-generator.c]: "Using initrd's fstab for /sysroot/usr/ configuration" ?

File: docs/ENVIRONMENT.md [hunk 7]
```diff
@@ -54,6 +54,10 @@ All tools:
 * `$SYSTEMD_SYSROOT_FSTAB` — if set, use this path instead of
   `/sysroot/etc/fstab`. Only useful for debugging `systemd-fstab-generator`.
 
+* `$SYSTEMD_FORCE_FSTAB` — takes a boolean. If set, overrides container
+  detection that ignores /dev entries in fstab. Only useful for debugging
```
Comment (keszybz) [inline docs/ENVIRONMENT.md]: `<filename>/dev/</filename>`

**Review by keszybz — COMMENTED** [review]
LGTM. Some minor stylistic issues.

**Comment by lilyinstarlight** [comment]
All of the stylistic nits should be fixed now. Thank you @keszybz!

File: docs/ENVIRONMENT.md (hunk 7 above)
Comment (lilyinstarlight) [reply docs/ENVIRONMENT.md]: I think that's a docbook tag and this file is markdown. I've changed it to <code>&grave;/dev/&grave;</code> instead

File: docs/ENVIRONMENT.md [hunk 8]
```diff
@@ -54,6 +54,10 @@ All tools:
 * `$SYSTEMD_SYSROOT_FSTAB` — if set, use this path instead of
   `/sysroot/etc/fstab`. Only useful for debugging `systemd-fstab-generator`.
 
+* `$SYSTEMD_FORCE_FSTAB` — takes a boolean. If set, overrides container
+  detection that ignores `/dev` entries in fstab. Only useful for debugging
```
Comment (YHNdnzj) [inline docs/ENVIRONMENT.md]: We always add the trailing slash to directories.

**Review by YHNdnzj — APPROVED** [review]
Only one minor thing left :)

File: docs/ENVIRONMENT.md (hunk 8 above)
Comment (lilyinstarlight) [reply docs/ENVIRONMENT.md]: Done!

File: src/fstab-generator/fstab-generator.c [hunk 9]
```diff
@@ -763,21 +763,52 @@ static int parse_fstab(bool initrd) {
...
                                       target_unit);
+
+                        if (is_sysroot_usr && k >= 0) {
+                                log_debug("Synthesizing fstab entry what=/sysusr/usr where=/sysroot/usr opts=bind");
+
+                                r = add_mount(fstab,
+                                              arg_dest,
+                                              "/sysusr/usr",
+                                              canonical_where ?: where,
+                                              canonical_where ? where: NULL,
```
Comment (poettering) [inline src/fstab-generator/fstab-generator.c]: why use canonical_where/where here?

for the sake of readability, we already established that where is "/sysroot/usr" here, hence I think it would be wise to spell that out, just like we do belo in add_sysroot_usr_mount

Comment (poettering) [reply src/fstab-generator/fstab-generator.c]: in fact, I think it would be good if we'd unify this call to add_mount() here and down below, i.e. add a helper add_sysusr_sysroot_usr_bind_mount() or so, that adds the bind mount, and is called from both places. After all, afaics they only differ in a single argument: the source.

File: src/fstab-generator/fstab-generator.c [hunk 10]
```diff
@@ -763,21 +763,52 @@ static int parse_fstab(bool initrd) {
...
+                                              NULL,
+                                              "bind",
+                                              0,
+                                              0,
+                                              SPECIAL_INITRD_FS_TARGET);
+                                if (r != 0)
+                                        k = r;
```
Comment (poettering) [inline src/fstab-generator/fstab-generator.c:815]: so, the /sysusr/usr/ indirection is kinda a hack by systemd to allow us to access /usr/ before we even format the root fs. I am not sure its wise to let that leak into fstab. so why not generate this automatically anyway?

File: src/fstab-generator/fstab-generator.c [hunk 11]
```diff
@@ -763,21 +763,52 @@ static int parse_fstab(bool initrd) {
                         flags |= rw_only * MOUNT_RW_ONLY |
                                  automount * MOUNT_AUTOMOUNT;
 
+                        is_sysroot = path_equal(where, "/sysroot");
+                        /* See comment from add_sysroot_usr_mount about the need for extra indirection
+                         * in case /usr needs to be mounted in order for the root fs to be synthesized
+                         * based on configuration included in /usr/, e.g. systemd-repart. */
+                        is_sysroot_usr = path_equal(where, "/sysroot/usr");
```
Comment (poettering) [inline src/fstab-generator/fstab-generator.c]: I think this should be conditionalized on `in_initrd()` (i.e. the function by that name, not the function parameter `initrd` we receive here). i.e. on the host /sysroot/ should really not be a thing

File: src/fstab-generator/fstab-generator.c [hunk 12]
```diff
@@ -763,21 +763,52 @@ static int parse_fstab(bool initrd) {
...
+                                r = generator_write_initrd_root_device_deps(arg_dest, what);
+                                if (r < 0)
+                                        return r;
+                        }
+
                         k = add_mount(fstab,
                                       arg_dest,
                                       what,
-                                      canonical_where ?: where,
+                                      canonical_where ?: is_sysroot_usr ? "/sysusr/usr" : where,
```
Comment (poettering) [inline src/fstab-generator/fstab-generator.c]: this looks wrong, no? the `is_sysroot_usr` check should come first, take precedence

File: src/fstab-generator/fstab-generator.c [hunk 13]
```diff
@@ -692,7 +693,11 @@ static int parse_fstab(bool initrd) {
                                 continue;
                         }
 
-                        if (is_device_path(what)) {
+                        e = getenv_bool_secure("SYSTEMD_FORCE_FSTAB");
```
Comment (poettering) [inline src/fstab-generator/fstab-generator.c]: searching for env vars is kinda slow. please move outside of the loop, so it is only done once. or even better, maybe do it lazily the first time we need it. i.e.

```
int force_fstab = -1;

if (force_fstab < 0) {
        r = getenv_bool_secure("SYSTEMD_FORCE_FSTAB");
        if (r < 0 && r != -ENXIO)
                log_debug_errno(r, …");
        force_fstab = e > 0;
}
```

i.e. use -1 as indicator you never parsed this ebfore

File: src/fstab-generator/fstab-generator.c [hunk 14]
```diff
@@ -692,7 +693,11 @@ static int parse_fstab(bool initrd) {
...
+                        if (e < 0 && e != -ENXIO)
+                                log_debug_errno(r, "Failed to parse $SYSTEMD_FORCE_FSTAB, ignoring: %m");
+
+                        if (e <= 0 && is_device_path(what)) {
                                 log_info("/sys/ is read-only (running in a container?), ignoring fstab device entry for %s.", what);
                                 continue;
                         }
```
Comment (poettering) [inline src/fstab-generator/fstab-generator.c:719]: hmm, I think it would be better to just explicitly override the sysfs read-only check altogether. i.e. call the env var SYSTEMD_SYSFS_CHECK=0/1 or so.

File: src/fstab-generator/fstab-generator.c (hunk 9 above)
Comment (lilyinstarlight) [reply src/fstab-generator/fstab-generator.c]: I originally had that but you're right it would be clearer to just spell it out. I've also factored it out to a helper function like you suggested. Thank you!

File: src/fstab-generator/fstab-generator.c (hunk 12 above)
Comment (lilyinstarlight) [reply src/fstab-generator/fstab-generator.c]: You're right, I did have it backwards. I also added a `!is_sysroot_usr` condition to the next line to make sure it always uses `NULL` for `original_where` in that case instead of checking `conditional_where`, for consistency (but I guess that should never be a situation that comes up)

File: src/fstab-generator/fstab-generator.c (hunk 13 above)
Comment (lilyinstarlight) [reply src/fstab-generator/fstab-generator.c]: I've implemented essentially what you had in that snippet, but adjusted for renaming the var per the following review comment and flipping the logic

File: src/fstab-generator/fstab-generator.c (hunk 14 above)
Comment (lilyinstarlight) [reply src/fstab-generator/fstab-generator.c:719]: Done, I've renamed it and flipped what it does to follow the new name. I didn't update the description in `docs/ENVIRONMENT.md` much, so let me know if I need to adjust any of that

**Comment by keszybz** [comment]
LGTM.
