### PR TITLE
sd-journal: verify journal file header in more detail

### LINKED ISSUE #27635: systemd-journald segfaults when appending to a corrupted journal
### systemd version the issue has been seen with

latest main

### Used distribution

Fedora 37, Fedora Rawhide

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

systemd-journald

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

I spent some time with @DaanDeMeyer's great idea of appending stuff to corrupted journals and wrote a little [test](https://github.com/systemd/systemd/compare/main...mrc0mmand:systemd:append-to-corrupted-journals) that attempts to do exactly that. And in under a minute it managed to trigger a segmentation fault:

```
$ build-san/test-journal-append --start-offset 69
Opening journal /tmp/journal-append-gzK0q6/system.journal
Reserving 333 entries in field hash table.                                                                             
Reserving 2047 entries in data hash table.
Journal effective settings seal=no keyed_hash=yes compress=ZSTD compress_threshold_bytes=512B                          
Start offset: 69                                    
AddressSanitizer:DEADLYSIGNAL                   
=================================================================                                                      
==1772452==ERROR: AddressSanitizer: SEGV on unknown address 0x7fda3666c980 (pc 0x7fa9abc2b087 bp 0x7ffe4961b040 sp 0x7ffe4961aef0 T0)                                                                                                          
==1772452==The signal is caused by a READ memory access.
    #0 0x7fa9abc2b087 in journal_file_find_field_object_with_hash ../src/libsystemd/sd-journal/journal-file.c:1421     
    #1 0x7fa9abc2d23b in journal_file_append_field ../src/libsystemd/sd-journal/journal-file.c:1638                    
    #2 0x7fa9abc2e29b in journal_file_append_data ../src/libsystemd/sd-journal/journal-file.c:1767                     
    #3 0x7fa9abc3764d in journal_file_append_entry ../src/libsystemd/sd-journal/journal-file.c:2453                    
    #4 0x403052 in journal_append_message ../src/journal/test-journal-append.c:35                                      
    #5 0x403f47 in journal_corrupt_and_append ../src/journal/test-journal-append.c:118                                 
    #6 0x40474b in main ../src/journal/test-journal-append.c:185                                                       
    #7 0x7fa9aa04a50f in __libc_start_call_main (/lib64/libc.so.6+0x2750f)                                             
    #8 0x7fa9aa04a5c8 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x275c8)
    #9 0x402574 in _start (/home/fsumsal/repos/@systemd/systemd/build-san/test-journal-append+0x402574)                
                                                           
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/libsystemd/sd-journal/journal-file.c:1421 in journal_file_find_field_object_with_hash
==1772452==ABORTING
Aborted (core dumped)
```

When I take the journal it left behind and copy it over to `/var/log/journal/.../system.journal`, restarting `systemd-journald` triggers the same issue:

```
[10931.988967] kernel: systemd-journal[552]: segfault at 7fda8df83530 ip 00007f495f58f243 sp 00007ffcf5e93810 error 4 in libsystemd-shared-253.so[7f495f32c000+353000]
[10931.988977] kernel: Code: 00 00 48 89 c1 48 c1 e9 04 48 83 f8 0f 0f 86 de 00 00 00 4c 89 e8 ba 00 00 00 00 48 f7 f1 48 c1 e2 04 49 03 94 24 e0 00 00 00 <48> 8b 02 48 89 45 b0 eb 69 48 8b 45 a8 48 39 43 08 0f 85 8b 00 00
[10932.047292] systemd-coredump[71876]: Process 552 (systemd-journal) of user 0 dumped core.
[10932.047323] systemd-coredump[71876]: Coredump diverted to /var/lib/systemd/coredump/core.systemd-journal.0.3157fc8b280547a185a4648609995286.552.1683992277000000.zst
[10932.047347] systemd-coredump[71876]: Stack trace of thread 552:
[10932.047356] systemd-coredump[71876]: #0  0x00007f495f58f243 journal_file_find_field_object_with_hash (libsystemd-shared-253.so + 0x263243)
[10932.047373] systemd-coredump[71876]: #1  0x00007f495f58fdf7 journal_file_append_field (libsystemd-shared-253.so + 0x263df7)
[10932.047387] systemd-coredump[71876]: #2  0x00007f495f590109 journal_file_append_data (libsystemd-shared-253.so + 0x264109)
[10932.047401] systemd-coredump[71876]: #3  0x00007f495f591493 journal_file_append_entry (libsystemd-shared-253.so + 0x265493)
[10932.047435] systemd-coredump[71876]: #4  0x000000000040ffec server_write_to_journal (systemd-journald + 0xffec)
[10932.047458] systemd-coredump[71876]: #5  0x0000000000412a3b server_dispatch_message_real (systemd-journald + 0x12a3b)
[10932.047472] systemd-coredump[71876]: #6  0x0000000000413b70 server_dispatch_message (systemd-journald + 0x13b70)
[10932.047486] systemd-coredump[71876]: #7  0x0000000000422e1f server_process_entry (systemd-journald + 0x22e1f)
[10932.047501] systemd-coredump[71876]: #8  0x00000000004235c8 server_process_native_message (systemd-journald + 0x235c8)
[10932.047516] systemd-coredump[71876]: #9  0x00000000004147a2 server_process_datagram (systemd-journald + 0x147a2)
[10932.047531] systemd-coredump[71876]: #10 0x00007f495f5b9ab2 source_dispatch (libsystemd-shared-253.so + 0x28dab2)
[10932.047544] systemd-coredump[71876]: #11 0x00007f495f5ba0a5 sd_event_dispatch (libsystemd-shared-253.so + 0x28e0a5)
[10932.047558] systemd-coredump[71876]: #12 0x00007f495f5ba2fc sd_event_run (libsystemd-shared-253.so + 0x28e2fc)
[10932.047571] systemd-coredump[71876]: #13 0x00000000004074c1 main (systemd-journald + 0x74c1)
[10932.047582] systemd-coredump[71876]: #14 0x00007f495eb56d85 __libc_start_main (libc.so.6 + 0x3ad85)
[10932.047594] systemd-coredump[71876]: #15 0x00000000004070ce _start (systemd-journald + 0x70ce)
[10932.047605] systemd-coredump[71876]: ELF object binary architecture: AMD x86-64
```

Journal: [system.journal.tar.gz](https://github.com/systemd/systemd/files/11470036/system.journal.tar.gz)

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug introduced by 206f0f397edf1144c63a158fb30f496c3e89f256.
Fixes #27635.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Looks nice! I've been hammering this overnight and so far no crash or any other issue.

File: src/libsystemd/sd-journal/journal-file.c [hunk 1]
```diff
@@ -552,18 +552,103 @@ static int journal_file_verify_header(JournalFile *f) {
...
+                if (_h != 0) {                                          \
+                        if (_h < offsetof(Object, hash_table.items))    \
+                                return -ENODATA;                        \
+                        _h -= offsetof(Object, hash_table.items);       \
+                        check_offset(_h);                               \
+                        assert(_h <= header_size + arena_size);         \
+                        if (_sz > header_size + arena_size - _h)        \
+                                return -ENODATA;                        \
+                }                                                       \
+        }
```
Comment (poettering) [inline src/libsystemd/sd-journal/journal-file.c]: do we really need to make these macros? i.e. the fact that they access local variables directly is particularly ugly.

why not just make them regular static functions, and pass the few variables in as parameters? and then make it return a regular error code?

yes, it would be a bit longer, but a lot less special.

**Comment by poettering** [comment]
tests look all good to me. just not fan of the macro usage with such heavy "side-effects" here, i.e. that access local variables by name

**Comment by poettering** [comment]
first commit looks uncontroversial, cherry picked that one

**Comment by yuwata** [comment]
@poettering Thank you for the review. Replaced with normal functions. PTAL.

File: src/libsystemd/sd-journal/journal-file.c [hunk 2]
```diff
@@ -512,6 +512,34 @@ static bool warn_wrong_flags(const JournalFile *f, bool compatible) {
...
+        if (!VALID64(offset))
+                return false;
+        if (offset < header_size)
+                return false;
+        if (offset > tail_object_offset)
+                return false;
+        return true;
+}
+
+static bool hash_is_valid(uint64_t offset, uint64_t size, uint64_t header_size, uint64_t arena_size, uint64_t tail_object_offset) {
```
Comment (poettering) [inline src/libsystemd/sd-journal/journal-file.c]: maybe call this `hash_table_is_valid()` to be more accurate, and not misleading the casual reviewer that this was validting a hash value or so.

File: src/libsystemd/sd-journal/journal-file.c [hunk 3]
```diff
@@ -552,18 +580,77 @@ static int journal_file_verify_header(JournalFile *f) {
...
+        }
+
+        if (JOURNAL_HEADER_CONTAINS(f->header, tail_entry_offset)) {
+                if (!offset_is_valid(le64toh(f->header->tail_entry_offset), header_size, tail_object_offset))
+                        return -ENODATA;
+        }
+
+        /* Verify number of objects */
+        uint64_t n_objects = le64toh(f->header->n_objects);
+        if (n_objects * sizeof(ObjectHeader) > arena_size)
```
Comment (poettering) [inline src/libsystemd/sd-journal/journal-file.c]: overflow check before multiplying these?

File: src/libsystemd/sd-journal/journal-file.c [hunk 4]
```diff
@@ -552,18 +580,77 @@ static int journal_file_verify_header(JournalFile *f) {
...
+                if (!offset_is_valid(offset, header_size, tail_object_offset))
+                        return -ENODATA;
+                if (entry_array_offset > offset)
+                        return -ENODATA;
+                if (entry_array_offset == 0 && offset != 0)
+                        return -ENODATA;
+                if ((offset == 0) != (n == 0))
+                        return -ENODATA;
+                assert(offset <= header_size + arena_size);
+                if (n * journal_file_entry_array_item_size(f) > header_size + arena_size - offset)
```
Comment (poettering) [inline src/libsystemd/sd-journal/journal-file.c]: please cast `n` explicitly to `uint64_t` here, so that we know the multiplication cannot overrun.

(i.e. on 32bit systems, both factors are 32bit and thus might overrun)

File: src/libsystemd/sd-journal/journal-file.c [hunk 5]
```diff
@@ -552,18 +580,77 @@ static int journal_file_verify_header(JournalFile *f) {
...
+                        return -ENODATA;
+        }
+
+        if (JOURNAL_HEADER_CONTAINS(f->header, tail_entry_offset)) {
+                if (!offset_is_valid(le64toh(f->header->tail_entry_offset), header_size, tail_object_offset))
+                        return -ENODATA;
+        }
```
Comment (poettering) [inline src/libsystemd/sd-journal/journal-file.c]: drop the extra {}?

**Review by poettering — CHANGES_REQUESTED** [review]

File: src/libsystemd/sd-journal/journal-file.c (hunk 3 above)
Comment (keszybz) [reply src/libsystemd/sd-journal/journal-file.c]: I'll change that to `n_objects > arena_size / sizeof(ObjectHeader)`.

**Comment by keszybz** [comment]
To move things along, I update the patch following Lennart's comments.

**Comment by keszybz** [comment]
Build test / build (clang, 15, lld, openssl): apt timeout
jammy-ppc64el: 9096s TEST-70-TPM2:                       FAIL     (109 s)

**Comment by yuwata** [comment]
@keszybz Thank you!
