### PR TITLE
journalctl: make --until work again with --after-cursor and --lines

### LINKED ISSUE #31776: journalctl --until is ignored when --after-cursor and --lines are both specified
### systemd version the issue has been seen with

systemd-254.10-1.fc39.x86_64

### Used distribution

Fedora 39

### Linux kernel version used

6.6.13-200.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

When `--after-cursor`, `--until`, and `--lines` are specified, the output should not contain any messages from after the `--until` timestamp. In particular, if `--after-cursor` comes from a time after the `--until` timestamp, the output should be empty.

```
$ sudo journalctl --after-cursor='s=f8b30a9d1e664c7d8e29a1194ee14a60;i=18bee8c;b=920817753cd14eb2b5a1efa648ddd95e;m=2aabbe63dbe;t=6139a47fa1895;x=d700d213de4d236d' --until '2024-03-14 01:00' --lines 5
-- No entries --
```

### Unexpected behaviour you saw

When `--after-cursor`, `--until`, and `--lines` are specified, `--until` is ignored. Lines from after the `--until` timestamp are shown.

```
$ sudo journalctl --after-cursor='s=f8b30a9d1e664c7d8e29a1194ee14a60;i=18bee8c;b=920817753cd14eb2b5a1efa648ddd95e;m=2aabbe63dbe;t=6139a47fa1895;x=d700d213de4d236d' --until '2024-03-14 01:00' --lines 5
Mar 14 01:01:01 laptop CROND[1549786]: (root) CMD (run-parts /etc/cron.hourly)
Mar 14 01:01:01 laptop run-parts[1549789]: (/etc/cron.hourly) starting 0anacron
Mar 14 01:01:01 laptop anacron[1549802]: Anacron started on 2024-03-14
Mar 14 01:01:01 laptop anacron[1549802]: Normal exit (0 jobs run)
Mar 14 01:01:01 laptop run-parts[1549804]: (/etc/cron.hourly) finished 0anacron
```

This is a regression.
Known working version: systemd-252-18.el9.x86_64 (RHEL 9.3)

### Steps to reproduce the problem

1. Find the cursor for some timestamp X. In this example, I use `'2024-03-14 01:01'`.
```
$ sudo journalctl --until '2024-03-14 01:01' --lines 0 --show-cursor
-- cursor: s=f8b30a9d1e664c7d8e29a1194ee14a60;i=18bee8c;b=920817753cd14eb2b5a1efa648ddd95e;m=2aabbe63dbe;t=6139a47fa1895;x=d700d213de4d236d
```

2. Query the logs for messages after the cursor and until (X - 1min) -- here, `'2024-03-14 01:00'`. Also set the `--lines` argument to some value (here, `5`).
```
$ sudo journalctl --after-cursor='s=f8b30a9d1e664c7d8e29a1194ee14a60;i=18bee8c;b=920817753cd14eb2b5a1efa648ddd95e;m=2aabbe63dbe;t=6139a47fa1895;x=d700d213de4d236d' --until '2024-03-14 01:00' --lines 5
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Additional info:

It works correctly when --lines is omitted (no output, because the --after-cursor comes after the --until timestamp):

$ sudo journalctl --after-cursor='s=f8b30a9d1e664c7d8e29a1194ee14a60;i=18bee8c;b=920817753cd14eb2b5a1efa648ddd95e;m=2aabbe63dbe;t=6139a47fa1895;x=d700d213de4d236d' --until '2024-03-14 01:00'
-- No entries --


It also works correctly when --after-cursor is omitted (most recent 5 lines before --until):

$ sudo journalctl --until '2024-03-14 01:00' --lines 5
Mar 14 00:59:03 laptop slack.desktop[4178081]: [03/14/24, 00:59:03:685] info: [DND_V2] (E030G10V24F) Will check for changes in DND status again in 5 minutes
Mar 14 00:59:40 laptop slack.desktop[4178081]: [03/14/24, 00:59:40:629] info: [RTM] Setting a timeout of 53 ms to process more rtm events
Mar 14 00:59:40 laptop slack.desktop[4178081]: [03/14/24, 00:59:40:682] info: [RTM] Waited 53 ms, processing more rtm events now
Mar 14 00:59:52 laptop slack.desktop[4178081]: [03/14/24, 00:59:52:464] info: [RTM] Setting a timeout of 78 ms to process more rtm events
Mar 14 00:59:52 laptop slack.desktop[4178081]: [03/14/24, 00:59:52:543] info: [RTM] Waited 78 ms, processing more rtm events now


Or when --until is omitted (first 5 lines after the --after-cursor). This is the same as the buggy behavior when --until is specified, but it's correct in this context:

$ sudo journalctl --after-cursor='s=f8b30a9d1e664c7d8e29a1194ee14a60;i=18bee8c;b=920817753cd14eb2b5a1efa648ddd95e;m=2aabbe63dbe;t=6139a47fa1895;x=d700d213de4d236d' --lines 5
Mar 14 01:01:01 laptop CROND[1549786]: (root) CMD (run-parts /etc/cron.hourly)
Mar 14 01:01:01 laptop run-parts[1549789]: (/etc/cron.hourly) starting 0anacron
Mar 14 01:01:01 laptop anacron[1549802]: Anacron started on 2024-03-14
Mar 14 01:01:01 laptop anacron[1549802]: Normal exit (0 jobs run)
Mar 14 01:01:01 laptop run-parts[1549804]: (/etc/cron.hourly) finished 0anacron
```

### PR DESCRIPTION
**Pull request by yuwata**
plus two tiny cleanups.

Fixes #31776.

### CODE REVIEW

**Comment by yuwata** [comment]
Please backport the first two commits to stable.

**Comment by YHNdnzj** [comment]
Hmm, not introduced by this PR, but if --after-cursor is used in conjunction with --lines=N, it would show the first N lines instead of the last?

I think the current implementation of cursor is very flawed and we probably will need a bigger rework than this (see also https://github.com/systemd/systemd/issues/26764)

File: src/journal/journalctl.c [hunk 1]
```diff
@@ -2079,6 +2080,64 @@ typedef struct Context {
...
+        /* Only --since is specified, and we know that the current position is in the range. */
+        if (!arg_until_set && arg_since_set && c->since_seeked && !arg_reverse)
+                return 1;
+
+        r = sd_journal_get_realtime_usec(j, &usec);
+        if (r < 0)
+                return log_error_errno(r, "Failed to determine realtime timestamp: %m");
+
+        if (arg_until_set && usec > arg_until) {
+                if (c->until_seeked)
```
Comment (YHNdnzj) [inline src/journal/journalctl.c]: So this variable is kinda redundant and unnecessary? Essentially this can still be derived from arg_reverse. With this condition, things actually get more complex: if the current seek is after arg_until, we actually first seek to arg_until, and in the next loop return -EDOM?

File: src/journal/journalctl.c [hunk 2]
```diff
@@ -2099,44 +2166,13 @@ static int show(Context *c) {
                                 break;
                 }
 
-                if (arg_until_set && !arg_reverse && (arg_lines < 0 || arg_since_set)) {
```
Comment (YHNdnzj) [inline src/journal/journalctl.c:2102]: As mentioned in https://github.com/systemd/systemd/issues/31776#issuecomment-1997010061, relaxing this check should fix the problem? Maybe, replace since_seeked with a generic `seek_need_recheck` field, that's set to true if cursor is used or --until is used with --lines. In all other cases it's guaranteed that the initial seek is at right place.

File: src/journal/journalctl.c (hunk 1 above)
Comment (yuwata) [reply src/journal/journalctl.c]: Maybe, the new verifier is redundant or less optimal. But the current logic is already too complicated, and I'd like to make that simpler and easily understood.
And the possibility you mentioned is not performance sensitive, I think.
At least, the logic by this PR should be much simpler and symmetric, this hopefully easily understood.

File: src/journal/journalctl.c (hunk 2 above)
Comment (yuwata) [reply src/journal/journalctl.c:2102]: Maybe, but not sure. The condition has been extended, and is now already complicated. I think it is better to simplify the logic, rather than extend it further.

Comment (YHNdnzj) [reply src/journal/journalctl.c:2102]: It actually gave me a hard time trying to understand the implications :/

File: src/journal/journalctl.c (hunk 1 above)
Comment (YHNdnzj) [reply src/journal/journalctl.c]: The newly-introduced implications actually gave me a hard time reading the PR :/ Should probably add a comment here that this is "intentional"

**Comment by yuwata** [comment]
OK. After reading the code and #26764, there are many potential issues in --since, --until, --cursor, --lines, and so on, and the previous version does not fully cover them. Let's now tape over the code now to fix issue #31776 to make the fix easily backported to stable branch, and rework later (I am already working on that).

@YHNdnzj PTAL.

**Review by YHNdnzj — APPROVED** [review]
