### PR TITLE
tmpfiles: Make C still copy if the destination directory is empty

### LINKED ISSUE #11287: tmpfiles.d: allow "C" lines to copy stuff into pre-existing empty destination dirs
Hello!

I'm trying to support factory resetting on my distro, which entails the ability to boot with an empty `/var` and `/etc`. I use OSTree, so I cannot delete the folders completely without messing things up, but I can make them empty.

The only type in tmpfiles.d I've been able to find that actually copies content is `C`, but it doesn't copy anything if the destination exists. Something like `C /etc - - - /usr/etc` would not work because `/etc` exists, even though it is empty. 

Could there be a new type that recursively copies content, just like `C`, but will do so even if the destination exists (as long as it is empty)? Is there some better solution to doing this?

Thank you!

### PR DESCRIPTION
**Pull request by refi64**
Fixes #11287.

### CODE REVIEW

File: src/basic/copy.c [hunk 1]
```diff
@@ -522,6 +522,12 @@ static int fd_copy_directory(
                 return -errno;
         fdf = -1;
 
+        if (copy_flags & COPY_MERGE_EMPTY) {
+                r = unlinkat(dt, to, AT_REMOVEDIR);
+                if (r < 0 && errno != ENOENT)
+                        return -errno;
+        }
```
Comment (poettering) [inline src/basic/copy.c:533]: I don't think we should remove the target first, but reuse it, which is what i'd assume a "merge" copy would do. i.e. please add a dir_is_empty() check here... (which should probably gain a related call dir_is_empty_at() for this purpose)

**Comment by poettering** [comment]
(looks good otherwise)

**Comment by kirbyfan64** [comment]
So I've tried recreating/rebasing/cherry-picking/force-pushing to this remote branch several times, and even though local Git is showing that the commit to add dir_is_empty_at is *first*, GitHub's UI is still showing it as *last*. I'm not sure if this is a bug or if it'll affect a merge in any way.

**Comment by poettering** [comment]
> So I've tried recreating/rebasing/cherry-picking/force-pushing to this remote branch several times, and even though local Git is showing that the commit to add dir_is_empty_at is _first_, GitHub's UI is still showing it as _last_. I'm not sure if this is a bug or if it'll affect a merge in any way.

github is stupid there. it strictly orders by time, not by parent/child relationship. This means you#d have to patch the timestamps to get the right order in github's view. 

quite frankly, don't bother, we are by now used to that, and it's something github really should fix...

File: src/basic/stat-util.c [hunk 2]
```diff
@@ -67,20 +67,33 @@ int is_device_node(const char *path) {
         return !!(S_ISBLK(info.st_mode) || S_ISCHR(info.st_mode));
 }
 
-int dir_is_empty(const char *path) {
-        _cleanup_closedir_ DIR *d;
+int dir_is_empty_at(int dirfd, const char *path) {
```
Comment (poettering) [inline src/basic/stat-util.c]: please don't call the parameter dirfd(), after all that's a symbol exposed by glibc, and we should try to avoid such name clashes even if in this case you get away with it. maybe dir_fd or so...

File: src/basic/stat-util.c [hunk 3]
```diff
@@ -67,20 +67,33 @@ int is_device_node(const char *path) {
...
+        _cleanup_close_ int fd = -1;
+        _cleanup_closedir_ DIR *d = NULL;
         struct dirent *de;
 
-        d = opendir(path);
+        if (path)
+                fd = openat(dirfd, path, O_RDONLY|O_DIRECTORY|O_CLOEXEC|O_NOCTTY);
```
Comment (poettering) [inline src/basic/stat-util.c]: hmm, let's maybe drop O_NOCTTY off this. you already specify O_DIRECTORY and a directory cannot be a tty, hence this is redundant, and might confuse readers.

File: src/basic/stat-util.c [hunk 4]
```diff
@@ -67,20 +67,33 @@ int is_device_node(const char *path) {
...
 
         FOREACH_DIRENT(de, d, return -errno)
                 return 0;
 
         return 1;
 }
 
+int dir_is_empty(const char *path) {
+        return dir_is_empty_at(AT_FDCWD, path);
+}
```
Comment (poettering) [inline src/basic/stat-util.c]: maybe move this to the header and make it static inline. We do that for many of such "stub aliases" and I think this would be a good candidate for that too.

File: src/basic/copy.c [hunk 5]
```diff
@@ -525,7 +526,8 @@ static int fd_copy_directory(
         r = mkdirat(dt, to, st->st_mode & 07777);
         if (r >= 0)
                 created = true;
-        else if (errno == EEXIST && (copy_flags & COPY_MERGE))
+        else if (errno == EEXIST &&
+                 (copy_flags & COPY_MERGE || (copy_flags & COPY_MERGE_EMPTY && dir_is_empty_at(dt, to))))
```
Comment (poettering) [inline src/basic/copy.c]: this would misunderstand a failure in "dir_is_empty_at()" as "yes it's an empty dir"... please add proper error handling and propagation to the dir_is_empty_at()...

Comment (poettering) [reply src/basic/copy.c]: hmm, also: please do the dir_is_empty_at() thing first if the new bit is set, and only if that returns ENOENT continue with the mkdirat(). Why? creating a directory might fail with EROFS or EPERM or so even if it already exists, if for some reason the caller has no privs to create a directory (think selinux, read-only file systems, overlayfs, …). Let's hence sidestep the issue and use dir_is_empty_at() first (which is more likely to succeed in such a case), and then use mkdirat() only if we detected the dir doesn't exist yet.

**Comment by kirbyfan64** [comment]
@poettering Done. (FWIW the dirfd and O_DIRECTORY w/ O_NOCTTY parts were based on other parts of the source code, the latter being from copy.c and the former being found in fileio.h among other places.)

**Comment by AdrianVovk** [comment]
Any reason that changes are still requested or can this be merged?

**Comment by keszybz** [comment]
LGTM.
