### PR TITLE
test-resolved-stream: Use a random port number

### LINKED ISSUE #28393: test-resolved-stream failure on CentOS Stream 9 Hyperscale
### systemd version the issue has been seen with

main

### Used distribution

CentOS Stream 9

### Linux kernel version used

CentOS Stream 9 kernel

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

```
 539/1208 systemd:resolve / test-resolved-stream                           FAIL              5.29s   killed by signal 6 SIGABRT
>>> PATH=/builddir/build/BUILD/systemd-hsfb-254.999/redhat-linux-build:/usr/share/Modules/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin PROJECT_BUILD_ROOT=/builddir/build/BUILD/systemd-hsfb-254.999/redhat-linux-build MALLOC_PERTURB_=149 SYSTEMD_LANGUAGE_FALLBACK_MAP=/builddir/build/BUILD/systemd-hsfb-254.999/src/locale/language-fallback-map EFI_ADDON=/builddir/build/BUILD/systemd-hsfb-254.999/redhat-linux-build/src/boot/efi/addonaa64.efi.stub /builddir/build/BUILD/systemd-hsfb-254.999/redhat-linux-build/test-resolved-stream
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stdout:
E04086A4FFFF0000:error:80000062:system library:BIO_bind:Address already in use:crypto/bio/bio_sock2.c:176:calling bind()
E04086A4FFFF0000:error:10000075:BIO routines:BIO_bind:unable to bind socket:crypto/bio/bio_sock2.c:178:
stderr:
Successfully forked off '(usernstest)' as PID 503128.
Skipping PR_SET_MM, as we don't have privileges.
test-resolved-stream: Can't create user and network ns, running on host: Operation not permitted
(usernstest) failed with exit status 1.
test-resolved-stream: Started TCP test
test-resolved-stream: A record
test-resolved-stream: AAAA record
test-resolved-stream: A + AAAA record
test-resolved-stream: Finished TCP test
test-resolved-stream: Started TLS test
Successfully forked off '(test-resolved-stream-tls-openssl)' as PID 503143.
Skipping PR_SET_MM, as we don't have privileges.
test-resolved-stream: A record
Failed to invoke SSL_do_handshake: SSL_get_error()=5
Assertion 'sd_event_run(event, EVENT_TIMEOUT_USEC) >= 1' failed at src/resolve/test-resolved-stream.c:281, function test_dns_stream(). Aborting.
```

### Steps to reproduce the problem

This is running inside of `mock` on Community Build System (CBS) in a chroot of the Hyperscale SIG for CentOS 9.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
https://cbs.centos.org/kojifiles/work/tasks/1783/3491783/build.log
```

### PR DESCRIPTION
**Pull request by daandemeyer**
Hopefully fixes #28393

### CODE REVIEW

File: src/resolve/test-resolved-stream.c [hunk 1]
```diff
@@ -374,7 +375,7 @@ static void try_isolate_network(void) {
 int main(int argc, char **argv) {
         server_address = (union sockaddr_union) {
                 .in.sin_family = AF_INET,
-                .in.sin_port = htobe16(12345),
+                .in.sin_port = htobe16(random_u64()),
```
Comment (yuwata) [inline src/resolve/test-resolved-stream.c]: I guess, if this provides a small value, the test will fail.

File: src/resolve/test-resolved-stream.c [hunk 2]
```diff
@@ -371,10 +372,19 @@ static void try_isolate_network(void) {
         assert_se(ioctl(socket_fd, SIOCSIFFLAGS, &req) >= 0);
 }
 
+static in_port_t random_port(void) {
+        in_port_t port;
+
+        while ((port = random_u64()) <= 1024)
```
Comment (yuwata) [inline src/resolve/test-resolved-stream.c]: And, should not be larger than UINT16_MAX...
Why not to simply use `random_u64_range(UINT16_MAX - 1024) + 1024` ?

**Comment by DaanDeMeyer** [comment]
Updated to use the suggested approach, setting the green label

**Review by bluca — APPROVED** [review]
