### PR TITLE
repart: mkfs.btrfs --subvol option format change

### LINKED ISSUE #37074: repart: mkfs.btrfs --subvol option format change
### systemd version the issue has been seen with

main

### Used distribution

Arch

### Linux kernel version used

6.13.8-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-repart

### Expected behaviour you didn't see

A rework of the mkfs.btrfs `--subvol` option value has broken the ro and default subvolume functionality in repart.

The repart invocation below should create a disk image with four generic partitions containing the subvolume /live.

1. /live is RW
2. /live is RO
3. /live is RW and default
4. /live is RO and default

With the latest development version of repart and btrfs-progs 6.12+ the repart invocation below leads to the mkfs.btrfs invocation

```
Executing mkfs command: mkfs.btrfs -L linux-generic-2 -U 8017fe16-c4d5-454a-9aae-f870f451dfa7 -r /var/tmp/.#repartb8ac4545d7174ade --sectorsize=4096 /var/tmp/repart-IrQgi0 --subvol /live:ro
```

which fails with the error `ERROR: could not get canonical path: /live:ro`. The mkfs commands for the third and fourth partitions also fail with variants of the same error if the previous partitions configurations are removed.

This is due to the following change to the subvol option in btrfs-progs: https://github.com/kdave/btrfs-progs/commit/8ba72e45c8a6da1275b448ad4912d96e0a2c54b5. (NOTE: The commit message has an error in it: It should say `s/ro-default/default-ro/`, per the source code.)

This PR (#37075) fixes the subvol option value that's built by repart to match the new structure.

### Steps to reproduce the problem

Run the following commands in an empty directory on a BTRFS partition to reproduce the issue (and test the fixed version).

```bash
mkdir -p repart.d skel/live
cat <<'EOF' > repart.d/10-rw.conf
[Partition]
Type=linux-generic
Format=btrfs
SizeMinBytes=16M
SizeMaxBytes=16M
CopyFiles=/:/
Subvolumes=/live
EOF
cat <<'EOF' > repart.d/20-ro.conf
[Partition]
Type=linux-generic
Format=btrfs
SizeMinBytes=16M
SizeMaxBytes=16M
CopyFiles=/:/
Subvolumes=/live:ro
EOF
cat <<'EOF' > repart.d/30-rw-default.conf
[Partition]
Type=linux-generic
Format=btrfs
SizeMinBytes=16M
SizeMaxBytes=16M
CopyFiles=/:/
Subvolumes=/live
DefaultSubvolume=/live
EOF
cat <<'EOF' > repart.d/40-ro-default.conf
[Partition]
Type=linux-generic
Format=btrfs
SizeMinBytes=16M
SizeMaxBytes=16M
CopyFiles=/:/
Subvolumes=/live:ro
DefaultSubvolume=/live
EOF
SYSTEMD_LOG_LEVEL=debug systemd-repart --copy-source=skel --definitions=repart.d --empty=create --size=auto default.raw
# Latest main fails with:
# ...
# ERROR: could not get canonical path: /live:ro
#
# Patched version outputs:
# ...
# Executing mkfs command: mkfs.btrfs -L linux-generic -U faf08da8-a17c-4782-a30f-ef21013961df -r /var/tmp/.#repart230922d83a4e8b90 --sectorsize=4096 /var/tmp/repart-ykXVeT --subvol /live
# ...
# Executing mkfs command: mkfs.btrfs -L linux-generic-2 -U 8017fe16-c4d5-454a-9aae-f870f451dfa7 -r /var/tmp/.#repartd06250062bf1370f --sectorsize=4096 /var/tmp/repart-0LRIak --subvol ro:/live
# ...
# Executing mkfs command: mkfs.btrfs -L linux-generic-3 -U 79eca9b0-d432-4b4c-8cf9-404299dbbd84 -r /var/tmp/.#repart81496e27c001d2d3 --sectorsize=4096 /var/tmp/repart-KdZBeW --subvol default:/live
# ...
# Executing mkfs command: mkfs.btrfs -L linux-generic-4 -U 39820576-1b43-4684-835a-06874d78f5e6 -r /var/tmp/.#repart8cb998942ea8b335 --sectorsize=4096 /var/tmp/repart-ZCAy1z --subvol default-ro:/live
# ...

# Check that the subvolumes were created correctly:
mkdir -p mnt
sudo losetup -Pf default.raw
sudo mount /dev/loop0p1 ./mnt
sudo btrfs sub show ./mnt/live
# => live ... Flags: - ...
sudo umount ./mnt
sudo mount /dev/loop0p2 ./mnt
sudo btrfs sub show ./mnt/live
# => live ... Flags: readonly ...
sudo umount ./mnt
sudo mount /dev/loop0p3 ./mnt
sudo btrfs sub show ./mnt
# => live ... Flags: - ...
sudo umount ./mnt
sudo mount /dev/loop0p4 ./mnt
sudo btrfs sub show ./mnt
# => live ... Flags: readonly ...
sudo umount ./mnt
sudo losetup -D
```

### PR DESCRIPTION
**Pull request by labichn**
Adapt repart mkfs.btrfs invocation to match the latest format: (btrfs-progs@8ba72e45c8a6da1275b448ad4912d96e0a2c54b5)

Fixes #37074

### CODE REVIEW

File: src/repart/repart.c [hunk 1]
```diff
@@ -6041,21 +6041,23 @@ static int append_btrfs_subvols(char ***l, OrderedHashmap *subvolumes, const cha
...
                 f = subvolume_flags_to_string(subvolume->flags);
                 if (!f)
                         return log_oom();
 
-                if (streq_ptr(subvolume->path, default_subvolume) &&
-                    !strextend_with_separator(&f, ",", "default"))
+                if (streq_ptr(subvolume->path, default_subvolume) && !strextend(&s, "default"))
+                        return log_oom();
+
+                if (!isempty(f) && !strextend_with_separator(&s, "-", f))
```
Comment (yuwata) [inline src/repart/repart.c]: Currently, only ro or default-ro will be set, so this should work.
But, in general the logic is incorrect, as subvolume_flags_to_string() uses strv_join() and potentially concat multiple options with comma, but btrfs command taks only one option.

So, please also update subvolume_flags_to_string().

**Review by yuwata — CHANGES_REQUESTED** [review]

File: src/repart/repart.c [hunk 2]
```diff
@@ -6041,21 +6041,23 @@ static int append_btrfs_subvols(char ***l, OrderedHashmap *subvolumes, const cha
         assert(l);
 
         ORDERED_HASHMAP_FOREACH(subvolume, subvolumes) {
-                _cleanup_free_ char *s = NULL, *f = NULL;
+                _cleanup_free_ char *s = NULL, *f = NULL, *p = NULL;
 
-                s = strdup(subvolume->path);
-                if (!s)
+                p = strdup(subvolume->path);
```
Comment (yuwata) [inline src/repart/repart.c]: It is not necessary to duplicate the path. Just pass it to strextend below.

File: src/repart/repart.c (hunk 1 above)
Comment (labichn) [reply src/repart/repart.c]: I'm tempted to remove `subvolume_flags_to_string` (as in latest push). Inlining the RO test is simple, and the new API doesn't look like it will be extended in that way. This is the only use of the function.

@DaanDeMeyer, do you expect we'll need this helper for future changes in btrfs-progs, or are you happy with us dropping `subvolume_flags_to_string`?

Comment (daandemeyer) [reply src/repart/repart.c]: Please drop it

**Review by yuwata — APPROVED** [review]
LGTM. Thank you!
