### PR TITLE
network: fixlets for manager state file

### LINKED ISSUE #28566: systemd-networkd: Unable to acquire IPv6 DNS server address
### systemd version the issue has been seen with

252.5-2ubuntu3

### Used distribution

Ubuntu 23.04

### Linux kernel version used

6.2.0-20-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

The output of resolvectl should contain IPv6 DNS server address.

### Unexpected behaviour you saw

When using `NetworkManager`, the output of `resolvectl` contains both IPv4 and IPv6 DNS server addresses. But when using `networkd`, there is only IPv4 DNS server  address.

Both `NetworkManager` and `networkd` can acquire IPv6 addresses. The problem does not occur on Ubuntu 20.04 (systemd 245.4), but it also occurs on Ubuntu 22.04 (systemd 249.11).

The configuration file and output are as follows.

 # `NetworkManager`
/etc/netplan/00-installer-config.yaml:
```
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    ens35:
      dhcp4: true
      dhcp6: true
```
resolvectl output:
```
root@ubuntu-23-01:~# resolvectl 
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (ens35)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: fe80::x:x:x:f6f6
       DNS Servers: 192.168.1.1 fe80::x:x:x:f6f6
        DNS Domain: Home lan
```

# `networkd`
/etc/netplan/00-installer-config.yaml:
```
network:
  version: 2
  renderer: networkd
  ethernets:
    ens35:
      dhcp4: true
      dhcp6: true
```
`netplan auto-generated` /run/systemd/network/10-netplan-ens35.network:
```
[Match]
Name=ens35

[Network]
DHCP=yes
LinkLocalAddressing=ipv6

[DHCP]
RouteMetric=100
UseMTU=true
```
resolvectl output:
```
root@ubuntu-23-01:~# resolvectl 
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (ens35)
Current Scopes: DNS
     Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
   DNS Servers: 192.168.1.1
    DNS Domain: Home
```
journalctl -b -u systemd-networkd > log.txt:
```
Jul 29 12:35:57 ubuntu-23-01 systemd[1]: Starting systemd-networkd.service - Network Configuration...
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: SELinux enabled state cached to: disabled
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Bus bus-api-network: changing state UNSET → OPENING
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Added inotify watch for /run on bus bus-api-network: 2
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Added inotify watch for /run/dbus on bus bus-api-network: 3
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Added inotify watch for /run/dbus/system_bus_socket on bus bus-api-network: -1
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Bus bus-api-network: changing state OPENING → WATCH_BIND
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Registering bus object implementation for path=/org/freedesktop/network1 iface=org.freedesktop.network1.Manager
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Registering bus object implementation for path=/org/freedesktop/network1/link iface=org.freedesktop.network1.DHCPServer
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Registering bus object implementation for path=/org/freedesktop/network1/link iface=org.freedesktop.network1.Link
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Registering bus object implementation for path=/org/freedesktop/network1/network iface=org.freedesktop.network1.Network
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: sd-device-monitor(n/a): Failed to stat PID1's netns, ignoring: No such file or directory
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Virtualization VMware Virtual Platform found in DMI (/sys/class/dmi/id/product_name)
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: UML virtualization not found in /proc/cpuinfo.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Virtualization XEN not found, /proc/xen does not exist
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Virtualization found, CPUID=VMwareVMware
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Found VM virtualization vmware
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: /usr/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Saved new link: ifindex=2, iftype=ETHER(1), kind=n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Saved original MTU 1500 (min: 46, max: 16110)
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Saved hardware address: 00:0c:29:ce:fe:91
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Saved IPv6 link-local address generation mode: eui64
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Flags change: +MULTICAST +BROADCAST
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:11.0/0000:02:03.0/physfn".
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: udev initialized link
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: State changed: pending -> initialized
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Saved new link: ifindex=1, iftype=LOOPBACK(772), kind=n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Saved original MTU 65536 (min: 0, max: 4294967295)
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Saved hardware address: 00:00:00:00:00:00
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Saved IPv6 link-local address generation mode: eui64
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Flags change: +LOOPBACK +UP +LOWER_UP +RUNNING
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Link UP
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Gained carrier
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: udev initialized link
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: State changed: pending -> initialized
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Received new foreign QDisc (configured): handle=0:0, parent=ffff:ffff, kind=noqueue
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Received new foreign address (configured): ::1/128 (valid forever, preferred forever), flags: permanent, scope: host
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: link_check_ready(): link is in initialized state.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Received new foreign address (configured): 127.0.0.1/8 (valid forever, preferred forever), flags: permanent, scope: host
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: link_check_ready(): link is in initialized state.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: rtnl: received non-static neighbor, ignoring.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Received new foreign route (configured): dst: ::1/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local(255), proto: kernel, type: local, nexthop: 0, priority: 0, flags: n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Received new foreign route (configured): dst: ::1/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: kernel, type: unicast, nexthop: 0, priority: 256, flags: n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Received new foreign route (configured): dst: 127.255.255.255/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: link, table: local(255), proto: kernel, type: broadcast, nexthop: 0, priority: 0, flags: n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Received new foreign route (configured): dst: 127.0.0.1/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: host, table: local(255), proto: kernel, type: local, nexthop: 0, priority: 0, flags: n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Received new foreign route (configured): dst: 127.0.0.0/8, src: n/a, gw: n/a, prefsrc: 127.0.0.1, scope: host, table: local(255), proto: kernel, type: local, nexthop: 0, priority: 0, flags: n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Remembering foreign routing policy rule (configured): priority: 32766, ::/0 -> ::/0, iif: n/a, oif: n/a, table: main(254)
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Remembering foreign routing policy rule (configured): priority: 0, ::/0 -> ::/0, iif: n/a, oif: n/a, table: local(255)
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: rtnl: received rule message with invalid family 129, ignoring.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: rtnl: received rule message with invalid family 128, ignoring.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Remembering foreign routing policy rule (configured): priority: 32767, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: default(253)
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Remembering foreign routing policy rule (configured): priority: 32766, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: main(254)
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Remembering foreign routing policy rule (configured): priority: 0, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: local(255)
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Enumeration completed
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Got inotify event on bus bus-api-network.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Bus bus-api-network: changing state WATCH_BIND → AUTHENTICATING
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Found driver: e1000
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Saved permanent hardware address: 00:0c:29:ce:fe:91
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Link state is up-to-date
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: found matching network '/run/systemd/network/10-netplan-ens35.network'.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring with /run/systemd/network/10-netplan-ens35.network.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: State changed: initialized -> configuring
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): link is not activated.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): link is not activated.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Setting '/proc/sys/net/ipv6/conf/ens35/disable_ipv6' to '0'
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: No change in value '0', suppressing write
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Setting '/proc/sys/net/ipv6/conf/ens35/use_tempaddr' to '0'
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: No change in value '0', suppressing write
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Setting '/proc/sys/net/ipv6/conf/ens35/accept_ra' to '0'
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Setting '/proc/sys/net/ipv6/conf/ens35/proxy_ndp' to '0'
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: No change in value '0', suppressing write
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Setting '/proc/sys/net/ipv4/conf/ens35/promote_secondaries' to '1'
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): link is not activated.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Requested to activate link
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Requested configuring of the DHCPv4 client.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Requested configuring of the DHCPv6 client.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Requested configuring of the IPv6 Router Discovery.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): link is not activated.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): link is not activated.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): link is not activated.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): link is not activated.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): link is not activated.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): link is not activated.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): link is not activated.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): link is not activated.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): link is not activated.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Bringing link up
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Failed to get driver, continuing without: Operation not supported
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Saved permanent hardware address: 00:00:00:00:00:00
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Link state is up-to-date
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: Unmanaging interface.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: lo: State changed: initialized -> unmanaged
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Flags change: +UP
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Link UP
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv6LL is not configured yet.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Received new foreign route (configured): dst: ff00::/8, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local(255), proto: kernel, type: multicast, nexthop: 0, priority: 256, flags: n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Received new foreign route (configured): dst: fe80::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: kernel, type: unicast, nexthop: 0, priority: 256, flags: n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Flags change: +LOWER_UP +RUNNING
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: Gained carrier
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: found matching network '/run/systemd/network/10-netplan-ens35.network'.
Jul 29 12:35:57 ubuntu-23-01 systemd[1]: Started systemd-networkd.service - Network Configuration.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: LLDP Rx: Started LLDP client
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv6LL is not configured yet.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv6LL is not configured yet.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv6LL is not configured yet.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv6LL is not configured yet.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv6LL is not configured yet.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv6LL is not configured yet.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv6LL is not configured yet.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv6LL is not configured yet.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv6LL is not configured yet.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 client: STARTED on ifindex 2
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 client is configured, acquiring DHCPv4 lease.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: IPv6 link-local address is not set, delaying to start DHCPv6 client.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv6 client is configured.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: IPv6 Router Discovery is configured.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Bus bus-api-network: changing state AUTHENTICATING → HELLO
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 client: DISCOVER
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RequestName cookie=2 reply_cookie=0 signature=su error-name=n/a error-message=n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.3 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Bus bus-api-network: changing state HELLO → RUNNING
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Got message type=signal sender=org.freedesktop.DBus.Local destination=n/a path=/org/freedesktop/DBus/Local interface=org.freedesktop.DBus.Local member=Connected cookie=4294967295 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Got message type=signal sender=org.freedesktop.DBus destination=:1.3 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Got message type=signal sender=org.freedesktop.DBus destination=:1.3 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.3 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=2 signature=u error-name=n/a error-message=n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Successfully acquired requested service name.
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.3 path=n/a interface=n/a member=n/a cookie=5 reply_cookie=3 signature=n/a error-name=n/a error-message=n/a
Jul 29 12:35:57 ubuntu-23-01 systemd-networkd[631]: Match type='signal',sender='org.freedesktop.login1',path='/org/freedesktop/login1',interface='org.freedesktop.login1.Manager',member='PrepareForSleep' successfully installed.
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 client: Received message from RAW socket, processing.
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: Ignoring DHCP option 125 while parsing.
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 client: OFFER
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 client: REQUEST (requesting)
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 client: Received message from RAW socket, processing.
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: Ignoring DHCP option 125 while parsing.
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 client: ACK
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 client: lease expires in 59min 59s
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 client: T2 expires in 52min 30s
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 client: T1 expires in 29min 59s
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 address 192.168.1.37/24, gateway 192.168.1.1 acquired from 192.168.1.1
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting DHCPv4 address (n/a): 192.168.1.37/24 (valid for 59min 59s, preferred for 59min 59s), flags: tentative, scope: global
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: DHCP: No static routes received from DHCP server.
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting DHCPv4 route (n/a): dst: 192.168.1.1/32, src: n/a, gw: n/a, prefsrc: 192.168.1.37, scope: link, table: main(254), proto: dhcp, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting DHCPv4 route (n/a): dst: n/a, src: n/a, gw: 192.168.1.1, prefsrc: 192.168.1.37, scope: global, table: main(254), proto: dhcp, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: DHCP: requested route destination 192.168.1.1/32 is in the assigned network 192.168.1.0/24, ignoring gateway address 192.168.1.1
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting DHCPv4 route (requesting): dst: 192.168.1.1/32, src: n/a, gw: n/a, prefsrc: 192.168.1.37, scope: link, table: main(254), proto: dhcp, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): address 192.168.1.37/24 is not ready.
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring DHCPv4 address (requesting): 192.168.1.37/24 (valid for 59min 59s, preferred for 59min 59s), flags: tentative, scope: global
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring DHCPv4 route (requesting): dst: 192.168.1.1/32, src: n/a, gw: n/a, prefsrc: 192.168.1.37, scope: link, table: main(254), proto: dhcp, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring DHCPv4 route (requesting): dst: n/a, src: n/a, gw: 192.168.1.1, prefsrc: 192.168.1.37, scope: global, table: main(254), proto: dhcp, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Received updated DHCPv4 address (configured): 192.168.1.37/24 (valid for 59min 59s, preferred for 59min 59s), flags: n/a, scope: global
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=4 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv6LL is not configured yet.
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=5 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Received new foreign route (configured): dst: 192.168.1.37/32, src: n/a, gw: n/a, prefsrc: 192.168.1.37, scope: host, table: local(255), proto: kernel, type: local, nexthop: 0, priority: 0, flags: n/a
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Received new foreign route (configured): dst: 192.168.1.255/32, src: n/a, gw: n/a, prefsrc: 192.168.1.37, scope: link, table: local(255), proto: kernel, type: broadcast, nexthop: 0, priority: 0, flags: n/a
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Received new foreign route (configured): dst: 192.168.1.0/24, src: n/a, gw: n/a, prefsrc: 192.168.1.37, scope: link, table: main(254), proto: kernel, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: dhcp4_check_ready(): DHCPv4 address and routes are not set.
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Received remembered DHCPv4 route (configured): dst: 192.168.1.1/32, src: n/a, gw: n/a, prefsrc: 192.168.1.37, scope: link, table: main(254), proto: dhcp, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: dhcp4_check_ready(): DHCPv4 address and routes are not set.
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: Received remembered DHCPv4 route (configured): dst: n/a, src: n/a, gw: 192.168.1.1, prefsrc: 192.168.1.37, scope: global, table: main(254), proto: dhcp, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv4 address and routes set.
Jul 29 12:36:00 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv6LL is not configured yet.
Jul 29 12:36:01 ubuntu-23-01 systemd-networkd[631]: ens35: Received new foreign address (configured): fe80::x:x:x:fe91/64 (valid forever, preferred forever), flags: permanent, scope: link
Jul 29 12:36:01 ubuntu-23-01 systemd-networkd[631]: ens35: Gained IPv6LL
Jul 29 12:36:01 ubuntu-23-01 systemd-networkd[631]: ens35: Discovering IPv6 routers
Jul 29 12:36:01 ubuntu-23-01 systemd-networkd[631]: ens35: NDISC: Started IPv6 Router Solicitation client
Jul 29 12:36:01 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv4LL:no DHCPv4:yes DHCPv6:no DHCP-PD:no NDisc:no
Jul 29 12:36:01 ubuntu-23-01 systemd-networkd[631]: ens35: State changed: configuring -> configured
Jul 29 12:36:01 ubuntu-23-01 systemd-networkd[631]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=6 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 29 12:36:01 ubuntu-23-01 systemd-networkd[631]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=7 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 29 12:36:01 ubuntu-23-01 systemd-networkd[631]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=8 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 29 12:36:01 ubuntu-23-01 systemd-networkd[631]: ens35: Received new foreign route (configured): dst: fe80::x:x:x:fe91/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local(255), proto: kernel, type: local, nexthop: 0, priority: 0, flags: n/a
Jul 29 12:36:02 ubuntu-23-01 systemd-networkd[631]: ens35: NDISC: Sent Router Solicitation, next solicitation in 4s
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: NDISC: Received Router Advertisement: flags OTHER preference low lifetime 1800 sec
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: NDISC: Invoking callback for 'router' event.
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv6 client: Starting in Information request mode
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv6 client: State changed: stopped -> information-request
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Acquiring DHCPv6 lease on NDisc request
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting NDisc route (n/a): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting NDisc route (n/a): dst: 2500:x:x:x::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting NDisc address (n/a): 2500:x:x:x:x:x:x:fe91/64 (valid for 2d 23h 59min 59s, preferred for 1d 23h 59min 59s), flags: tentative,manage-temporary-address,no-prefixroute, scope: global
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting NDisc route (n/a): dst: 2500:x:x:x::/64, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Setting SLAAC addresses and router.
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: State changed: configured -> configuring
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): address 2500:x:x:x:x:x:x:fe91/64 is not ready.
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring NDisc route (requesting): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring NDisc route (requesting): dst: 2500:x:x:x::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring NDisc address (requesting): 2500:x:x:x:x:x:x:fe91/64 (valid for 2d 23h 59min 59s, preferred for 1d 23h 59min 59s), flags: tentative,manage-temporary-address,no-prefixroute, scope: global
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring NDisc route (requesting): dst: 2500:x:x:x::/64, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv6 client: Sent Information Request
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv6 client: Next retransmission in 943ms
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Received remembered NDisc route (configured): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Received remembered NDisc route (configured): dst: 2500:x:x:x::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Received updated NDisc address (configured): 2500:x:x:x:x:x:x:fe91/64 (valid for 2d 23h 59min 59s, preferred for 1d 23h 59min 59s), flags: tentative,manage-temporary-address,no-prefixroute, scope: global
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): address 2500:x:x:x:x:x:x:fe91/64 is not ready.
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: Received remembered NDisc route (configured): dst: 2500:x:x:x::/64, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: ndisc_check_ready(): no SLAAC address is ready.
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv6 client: New information request will be refused in 6h.
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv6 client: Processed Reply message
Jul 29 12:36:04 ubuntu-23-01 systemd-networkd[631]: ens35: DHCPv6 client: State changed: information-request -> stopped
Jul 29 12:36:05 ubuntu-23-01 systemd-networkd[631]: ens35: Received updated NDisc address (configured): 2500:x:x:x:x:x:x:fe91/64 (valid for 2d 23h 59min 58s, preferred for 1d 23h 59min 58s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 29 12:36:05 ubuntu-23-01 systemd-networkd[631]: ens35: SLAAC addresses and routes set.
Jul 29 12:36:05 ubuntu-23-01 systemd-networkd[631]: ens35: link_check_ready(): IPv4LL:no DHCPv4:yes DHCPv6:no DHCP-PD:no NDisc:yes
Jul 29 12:36:05 ubuntu-23-01 systemd-networkd[631]: ens35: State changed: configuring -> configured
Jul 29 12:36:05 ubuntu-23-01 systemd-networkd[631]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=10 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 29 12:36:05 ubuntu-23-01 systemd-networkd[631]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=11 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 29 12:36:05 ubuntu-23-01 systemd-networkd[631]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=12 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jul 29 12:36:05 ubuntu-23-01 systemd-networkd[631]: ens35: Received new foreign route (configured): dst: 2500:x:x:x:x:x:x:fe91/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local(255), proto: kernel, type: local, nexthop: 0, priority: 0, flags: n/a
Jul 29 12:36:13 ubuntu-23-01 systemd-networkd[631]: ens35: NDISC: No RA received before link confirmation timeout
Jul 29 12:36:13 ubuntu-23-01 systemd-networkd[631]: ens35: NDISC: Invoking callback for 'timeout' event.
Jul 29 12:36:13 ubuntu-23-01 systemd-networkd[631]: ens35: NDisc handler get timeout event
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: NDISC: Received Router Advertisement: flags OTHER preference low lifetime 1800 sec
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: NDISC: Invoking callback for 'router' event.
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: Acquiring DHCPv6 lease on NDisc request
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting NDisc route (configured): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting NDisc route (configured): dst: 2500:x:x:x::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting NDisc address (configured): 2500:x:x:x:x:x:x:fe91/64 (valid for 2d 23h 59min 59s, preferred for 1d 23h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting NDisc route (configured): dst: 2500:x:x:x::/64, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: Setting SLAAC addresses and router.
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring NDisc route (requesting,configured): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring NDisc route (requesting,configured): dst: 2500:x:x:x::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring NDisc address (requesting,configured): 2500:x:x:x:x:x:x:fe91/64 (valid for 2d 23h 59min 59s, preferred for 1d 23h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring NDisc route (requesting,configured): dst: 2500:x:x:x::/64, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: Received updated NDisc address (configured): 2500:x:x:x:x:x:x:fe91/64 (valid for 2d 23h 59min 59s, preferred for 1d 23h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 29 12:36:20 ubuntu-23-01 systemd-networkd[631]: ens35: SLAAC addresses and routes set.
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: NDISC: Received Router Advertisement: flags OTHER preference low lifetime 1800 sec
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: NDISC: Invoking callback for 'router' event.
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: Acquiring DHCPv6 lease on NDisc request
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting NDisc route (configuring,configured): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting NDisc route (configuring,configured): dst: 2500:x:x:x::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting NDisc address (configured): 2500:x:x:x:x:x:x:fe91/64 (valid for 2d 23h 59min 59s, preferred for 1d 23h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: Requesting NDisc route (configuring,configured): dst: 2500:x:x:x::/64, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: Setting SLAAC addresses and router.
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring NDisc route (requesting,configuring,configured): dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring NDisc route (requesting,configuring,configured): dst: 2500:x:x:x::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring NDisc address (requesting,configured): 2500:x:x:x:x:x:x:fe91/64 (valid for 2d 23h 59min 59s, preferred for 1d 23h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: Configuring NDisc route (requesting,configuring,configured): dst: 2500:x:x:x::/64, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: Received updated NDisc address (configured): 2500:x:x:x:x:x:x:fe91/64 (valid for 2d 23h 59min 59s, preferred for 1d 23h 59min 59s), flags: manage-temporary-address,no-prefixroute, scope: global
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: ndisc_check_ready(): SLAAC addresses and routes are not set.
Jul 29 12:36:34 ubuntu-23-01 systemd-networkd[631]: ens35: SLAAC addresses and routes set.
```

### Steps to reproduce the problem

1. Set up radvd and DHCPv6 service
2. Freshly installed Ubuntu 23.04
3. Modify the netplan configuration file as:
```
network:
  version: 2
  renderer: networkd
  ethernets:
    ens35:
      dhcp4: true
      dhcp6: true
```
4. Run `netplan apply` 
5. Run `resolvectl` and check the output

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### LINKED ISSUE #29148: timesyncd ignores DHCPv6-configured NTP server
### systemd version the issue has been seen with

253.6

### Used distribution

NixOS 23.05

### Linux kernel version used

6.1.47

### CPU architectures issue was seen on

x86_64

### Component

systemd-timesync

### Expected behaviour you didn't see

`systemd-timesyncd` uses DHCPv6-configured NTP Server

### Unexpected behaviour you saw

`systemd-timesyncd` ignores DHCPv6-configured NTP Server

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ cat /etc/systemd/network/30-wan_hgw.network
[Match]
Name=wan_hgw

[Link]
RequiredForOnline=routable

[Network]
DHCP=yes
DHCPPrefixDelegation=true
IPForward=true
IPv6AcceptRA=true

[DHCPv4]
UseDNS=false
UseHostname=false
UseRoutes=false

[DHCPv6]
UseNTP=true
WithoutRA=solicit

[DHCPPrefixDelegation]
Announce=false
Assign=false
UplinkInterface=:self

[IPv6AcceptRA]
Token=::f21

$ cat /etc/systemd/networkd.conf
[Network]

$ cat /etc/systemd/timesyncd.conf
[Time]
NTP=

$ systemctl cat systemd-networkd
(snip)
Environment=SYSTEMD_LOG_LEVEL=debug

$ systemctl cat systemd-timesyncd
(snip)
Environment=SYSTEMD_LOG_LEVEL=debug

$ systemctl restart systemd-networkd
$ systemctl restart systemd-timesyncd

$ networkctl status wan_hgw
● 6: wan_hgw                                                                          
                     Link File: /etc/systemd/network/10-wan_hgw.link
                  Network File: /etc/systemd/network/30-wan_hgw.network
                         State: routable (configured)
                  Online state: online                                                
                          Type: ether
                          Path: pci-0000:01:00.3
                        Driver: igb
                        Vendor: Intel Corporation
                         Model: I350 Gigabit Network Connection
              Hardware Address: 2c:53:4a:07:f9:03 (Shenzhen Winyao Electronic Limited)
                           MTU: 1500 (min: 68, max: 9216)
                         QDisc: mq
  IPv6 Address Generation Mode: eui64
      Number of Queues (Tx/Rx): 8/8
              Auto negotiation: yes
                         Speed: 1Gbps
                        Duplex: full
                          Port: tp
                       Address: 192.168.18.41 (DHCP4 via 192.168.18.1)
                                2400:4051:c520:1e00::f21
                                fe80::2e53:4aff:fe07:f903
                       Gateway: fe80::2eff:65ff:fe38:7fc6
                           DNS: 2400:4051:c520:1e00:2eff:65ff:fe38:7fc6
                           NTP: 2404:1a8:1102::b         <- DHCPv6 issues NTP server addresses
                                2404:1a8:1102::a
                           SIP: 192.168.18.1
             Activation Policy: up
           Required For Online: yes
               DHCP4 Client ID: IAID:0x4fabaa6f/DUID
             DHCP6 Client IAID: 0x4fabaa6f
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab111c741a944e2150b30000

$ timedatectl show-timesync --all
LinkNTPServers=                         <- No DHCP-configured NTP servers
SystemNTPServers=
RuntimeNTPServers=
FallbackNTPServers=0.nixos.pool.ntp.org 1.nixos.pool.ntp.org 2.nixos.pool.ntp.org 3.nixos.pool.ntp.org
ServerName=0.nixos.pool.ntp.org         <- DHCP-configured NTP servers are not used
ServerAddress=160.16.113.133
RootDistanceMaxUSec=5s
PollIntervalMinUSec=32s
PollIntervalMaxUSec=34min 8s
PollIntervalUSec=2min 8s
NTPMessage={ Leap=0, Version=4, Mode=4, Stratum=3, Precision=-25, RootDelay=2.334ms, RootDispersion=167us, Reference=761B6B93, OriginateTimestamp=Sun 2023-09-10 19:59:30 JST, ReceiveTimestamp=Sun 2023-09-10 19:59:30 JST, TransmitTimestamp=Sun 2023-09-10 19:59:30 JST, DestinationTimestamp=Sun 2023-09-10 19:59:30 JST, Ignored=no, PacketCount=2, Jitter=607us }
Frequency=2448872

$ journalctl -u systemd-networkd -u systemd-timesyncd -S "20:08:11"
```
https://gist.github.com/ngkz/5525dd8a2919b7f9debb30d16c3a4920

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #29148.
Fixes #28566.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

File: src/network/networkd-state-file.c [hunk 1]
```diff
@@ -21,88 +21,250 @@
...
+                r = sd_dhcp6_lease_get_ntp_addrs(link->dhcp6_lease, &addresses);
+                if (r >= 0) {
+                        r = ordered_set_put_in6_addrv(s, addresses, r);
+                        if (r < 0)
+                                return r;
+                }
+
+                r = sd_dhcp6_lease_get_ntp_fqdn(link->dhcp6_lease, &fqdn);
+                if (r >= 0) {
+                        r = ordered_set_put_strdupv(s, fqdn);
```
Comment (evverx) [inline src/network/networkd-state-file.c:177]: It's apparently possible to stuff all sorts of binary data here:
```sh
-bash-5.2# networkctl status host0 --json=short | jq '.NTP[].Server'
"\\000\\000a"
"\\001\\002\\003"
"a\\010a"

-bash-5.2# grep NTP /run/systemd/netif/state 
NTP=\000\000a \001\002\003 a\010a
```
Looks like `dns_name_is_valid` is missing somewhere. (It's not necessarily related to this PR but I haven't seen this before).
