### PR TITLE
repart: fix assertion failure

### LINKED ISSUE #37178: repart: Assertion failed when resizing with version 257.5
### systemd version the issue has been seen with

257.5

### Used distribution

_No response_

### Linux kernel version used

6.14.2-300.fc42.aarch64

### CPU architectures issue was seen on

aarch64

### Component

systemd-repart

### Expected behaviour you didn't see

The root partition is resized to take the whole disk

### Unexpected behaviour you saw

```
[root@03f57e8d82ac /]# fdisk -lx /dev/mmcblk0 
GPT PMBR size mismatch (4194303 != 499744767) will be corrected by write.
The backup GPT table is not on the end of the device.
Disk /dev/mmcblk0: 238.3 GiB, 255869321216 bytes, 499744768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 6C2CC038-D12D-4BC7-AA37-8C441A5F17BF
First usable LBA: 34
Last usable LBA: 4194270
Alternative LBA: 4194303
Partition entries starting LBA: 2
Allocated partition entries: 128
Partition entries ending LBA: 33

Device           Start     End Sectors Type-UUID                            UUID                                 Name Attrs
/dev/mmcblk0p1      34 1048609 1048576 C12A7328-F81F-11D2-BA4B-00A0C93EC93B 2A465EFC-229A-40E1-A187-C13E6AA33092 esp  RequiredPartition LegacyBIOSBootable
/dev/mmcblk0p2 1048610 4194270 3145661 B921B045-1DF0-41C3-AF44-4C6F280D3FAE 24E4BD60-69B2-4C47-8502-973741637FC0 root GUID:59
[root@03f57e8d82ac /]# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
mmcblk0     179:0    0 238.3G  0 disk 
├─mmcblk0p1 179:1    0   512M  0 part 
└─mmcblk0p2 179:2    0   1.5G  0 part /
[root@03f57e8d82ac /]# cat /usr/local/lib/repart.d/50-root.conf
[Partition]
Type=root
# systemd-repart --dry-run=no
Assertion 'required % context->grain_size == 0' failed at src/repart/repart.c:1076, function context_allocate_partitions(). Aborting.
Aborted (core dumped)
```

### Steps to reproduce the problem

Boot Fedora 42 on a RaspberryPi, add the root partition definition, start `systemd-repart`.  

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Apr 18 14:02:59 03f57e8d82ac systemd[1]: Starting systemd-repart.service - Repartition Root Disk...
Apr 18 14:02:59 03f57e8d82ac systemd-repart[720]: Assertion 'required % context->grain_size == 0' failed at src/rep
art/repart.c:1076, function context_allocate_partitions(). Aborting.
Apr 18 14:03:00 03f57e8d82ac systemd-coredump[722]: [🡕] Process 720 (systemd-repart) of user 0
 dumped core.
                                                    
                                                    Module /usr/bin/systemd-repart from rpm systemd-257.5-2.fc42.aarch64
                                                    Module libudev.so.1 from rpm systemd-257.5-2.fc42.aarch64
                                                    Module libjson-c.so.5 from rpm json-c-0.18-2.fc42.aarch64
                                                    Module libdevmapper.so.1.02 from rpm lvm2-2.03.30-3.fc42.aarch64
                                                    Module libcryptsetup.so.12 from rpm cryptsetup-2.7.5-2.fc42.aarch64
                                                    Module libcap-ng.so.0 from rpm libcap-ng-0.8.5-4.fc42.aarch64
                                                    Module libpcre2-8.so.0 from rpm pcre2-10.45-1.fc42.aarch64
                                                    Module libeconf.so.0 from rpm libeconf-0.7.6-1.fc42.aarch64
                                                    Module libaudit.so.1 from rpm audit-4.0.3-2.fc42.aarch64
                                                    Module libattr.so.1 from rpm attr-2.5.2-5.fc42.aarch64
                                                    Module libz.so.1 from rpm zlib-ng-2.2.4-3.fc42.aarch64
                                                    Module libuuid.so.1 from rpm util-linux-2.40.4-7.fc42.aarch64
                                                    Module libselinux.so.1 from rpm libselinux-3.8-1.fc42.aarch64
                                                    Module libseccomp.so.2 from rpm libseccomp-2.5.5-2.fc41.aarch64
                                                    Module libpam.so.0 from rpm pam-1.7.0-4.fc42.aarch64
                                                    Module libmount.so.1 from rpm util-linux-2.40.4-7.fc42.aarch64
                                                    Module libcrypt.so.2 from rpm libxcrypt-4.4.38-7.fc42.aarch64
                                                    Module libcap.so.2 from rpm libcap-2.73-2.fc42.aarch64
                                                    Module libacl.so.1 from rpm acl-2.3.2-3.fc42.aarch64
                                                    Module libcrypto.so.3 from rpm openssl-3.2.4-3.fc42.aarch64
                                                    Module libfdisk.so.1 from rpm util-linux-2.40.4-7.fc42.aarch64
                                                    Module libblkid.so.1 from rpm util-linux-2.40.4-7.fc42.aarch64
                                                    Module libsystemd-shared-257.5-2.fc42.so from rpm systemd-257.5-2.fc42.aarch64

                                                    Stack trace of thread 720:
                                                    #0  0x0000ffff8377f27c __pthread_kill_implementation (libc.so.6 + 0x8f27c)
                                                    #1  0x0000ffff8372b4fc raise (libc.so.6 + 0x3b4fc)
                                                    #2  0x0000ffff83715a48 abort (libc.so.6 + 0x25a48)
                                                    #3  0x0000ffff83fe2e48 log_assert_failed (libsystemd-shared-257.5-2.fc42.so + 0
x212e48)
                                                    #4  0x0000aaaadd7a5274 context_allocate_partitions.part.0.lto_priv.0 (/usr/bin/
systemd-repart + 0x25274)
                                                    #5  0x0000aaaadd7a8740 run (/usr/bin/systemd-repart + 0x28740)
                                                    #6  0x0000aaaadd7892ec main (/usr/bin/systemd-repart + 0x92ec)
                                                    #7  0x0000ffff8371625c __libc_start_call_main (libc.so.6 + 0x2625c)
                                                    #8  0x0000ffff8371633c __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2633c)
                                                    #9  0x0000aaaadd7894b0 _start (/usr/bin/systemd-repart + 0x94b0)
                                                    ELF object binary architecture: AARCH64
Apr 18 14:03:00 03f57e8d82ac systemd[1]: systemd-repart.service: Main process exited, code=dumped, stat
us=6/ABRT
Apr 18 14:03:00 03f57e8d82ac systemd[1]: systemd-repart.service: Failed with result 'core-dump'.
Apr 18 14:03:00 03f57e8d82ac systemd[1]: Failed to start systemd-repart.service - Repartition Root Disk.
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #37178.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
@AdrianVovk Can you review the first commit?

**Comment by AdrianVovk** [comment]
Sorry for the delay 

I'm struggling to wrap my head around why the padding settings shouldn't be merged in this case. Could you explain more?

If I configure the ESP to have 800 MB of space + 200MB of padding. Then I configure XBOOTLDR to have 1GB of space + 500MB of padding. Finally, I make XBOOTLDR supplement for the ESP. Let's say there's plenty of free space. I'm expecting the end result to be a 1 GB esp + 500 MB of padding + no XBOOTLDR partition

(Looking at this again, actually, the logic that propagates sizes is probably off. We propagate ranges appropriately, but if Min=Max I don't think we do the right thing. I should take another look at that)

File: man/repart.d.xml [hunk 1]
```diff
@@ -919,10 +919,9 @@
         for the merged partition for some other reason.</para>
 
         <para>The following fields are merged into the target definition in the specified ways:
-        <varname>Weight=</varname> and <varname>PaddingWeight=</varname> are simply overwritten;
-        <varname>SizeMinBytes=</varname> and <varname>PaddingMinBytes=</varname> use the larger of the two
-        values; <varname>SizeMaxBytes=</varname> and <varname>PaddingMaxBytes=</varname> use the smaller
-        value; and <varname>CopyFiles=</varname>, <varname>ExcludeFiles=</varname>,
+        <varname>Weight=</varname>is simply overwritten; <varname>SizeMinBytes=</varname> uses the larger of
+        the two values; <varname>SizeMaxBytes=</varname> uses the smaller value; and
+        <varname>CopyFiles=</varname>, <varname>ExcludeFiles=</varname>,
```
Comment (keszybz) [inline man/repart.d.xml]: Hmm, I don't find the premise in the commit message at all obvious. Let's say I want to create either ESP + large XBOOTLDR, or just a larger ESP if possible. And the padding after the large partition is supposed to be as specified in the second config, i.e. the supplement. The original design in 2cb9c68c3a898954a99a915006ea82822450e2c9 allows this, which is nice and consistent. With your change, we suddenly ignore the padding, which I don't see a good justification for.

**Review by keszybz — COMMENTED** [review]
Dunno, it seems that the assert wasn't taking some conditions into account properly. But I'm not convinced about the logic change in the first commit.

**Comment by keszybz** [comment]
Heh, we essentially wrote the same thing concurrently.

**Comment by yuwata** [comment]
@AdrianVovk @keszybz Sorry for late response.
Now the first commit about padding for supplement partition is dropped.
This should be fine. PTAL. cc also @DaanDeMeyer .

**Comment by keszybz** [comment]
Looks reasonable. This now only removes an assertion failure, so there's no chance for the CI to fail, so I'll merge it without further ado.
