### PR TITLE
Fix #20933

### LINKED ISSUE #20933: Malformed dbus call crashes systemd
**systemd version the issue has been seen with**
 > v249 (should work with much older versions)

**Used distribution**
 > arch linux

**Linux kernel version used** (`uname -a`)
 > `5.14.8`

**CPU architecture issue was seen on**
 > `x86_64`

**Expected behaviour you didn't see**
 > The dbus call should fail with a validation error (the dbus call is asking for an empty argv)

**Unexpected behaviour you saw**
 > The service manager crashed with SIGABRT upon hitting [this assert](https://github.com/systemd/systemd/blob/v249/src/core/execute.c#L5964) (which moved to [here](https://github.com/systemd/systemd/blob/main/src/basic/escape.c#L550) in `main`): 

**Steps to reproduce the problem**
 ```
busctl call \
   org.freedesktop.systemd1 \
   /org/freedesktop/systemd1 \
   org.freedesktop.systemd1.Manager \
   StartTransientUnit \
   "ssa(sv)a(sa(sv))"  \
   test.service \
   replace \
   1 ExecStart "a(sasb)" 1 /usr/bin/sleep 0 true 0
```
(works with both PID 1 and user systemd)

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
systemd[1]: Caught <ABRT>, dumped core as pid 83069.
systemd[1]: Freezing execution.
```

backtrace:
```gdb
#0  0x00007f57c445f01b in kill () from /usr/lib/libc.so.6
#1  0x000055e508aa8667 in crash (sig=6) at ../systemd/src/core/main.c:257
#2  <signal handler called>
#3  0x00007f57c445ed22 in raise () from /usr/lib/libc.so.6
#4  0x00007f57c4448862 in abort () from /usr/lib/libc.so.6
#5  0x00007f57c477e068 in log_assert_failed (text=<optimized out>, text@entry=0x55e508b7da04 "argv", file=<optimized out>, file@entry=0x55e508b89ad6 "src/core/execute.c", line=<optimized out>, line@entry=5964, func=<optimized out>, func@entry=0x55e508b8e150 <__PRETTY_FUNCTION__.128> "exec_command_line")
    at ../systemd/src/basic/log.c:862
#6  0x000055e508acb810 in exec_command_line (argv=<optimized out>)
    at ../systemd/src/core/execute.c:5964
#7  0x000055e508acbc95 in exec_spawn (unit=<optimized out>, command=0x55e50a4fb2b0, context=<optimized out>, params=<optimized out>, runtime=0x0, dcreds=0x55e50a54e350, ret=0x7ffd4e539790)
    at ../systemd/src/core/execute.c:4744
#8  0x000055e508b01d92 in service_spawn (s=s@entry=0x55e50a54d8b0, c=<optimized out>, timeout=<optimized out>, flags=<optimized out>, flags@entry=(EXEC_APPLY_SANDBOXING | EXEC_APPLY_CHROOT | EXEC_APPLY_TTY_STDIN | EXEC_WRITE_CREDENTIALS | EXEC_PASS_FDS | EXEC_SET_WATCHDOG), ret_pid=ret_pid@entry=0x7ffd4e539934)
    at ../systemd/src/core/service.c:1568
#9  0x000055e508b0700e in service_enter_start (s=0x55e50a54d8b0)
    at ../systemd/src/core/service.c:2129
#10 0x000055e508b076e6 in service_enter_condition (s=0x55e50a54d8b0)
    at ../systemd/src/core/service.c:2233
#11 service_start (u=0x55e50a54d8b0)
    at ../systemd/src/core/service.c:2480
#12 0x000055e508acf673 in unit_start (u=0x55e50a54d8b0)
    at ../systemd/src/core/unit.c:1911
#13 job_perform_on_unit (j=0x7ffd4e539a60)
    at ../systemd/src/core/job.c:769
#14 0x000055e508ae785a in job_run_and_invalidate (j=<optimized out>)
    at ../systemd/src/core/job.c:836
#15 manager_dispatch_run_queue (source=<optimized out>, userdata=<optimized out>)
    at ../systemd/src/core/manager.c:2196
#16 manager_dispatch_run_queue (source=<optimized out>, userdata=0x55e50a40f5c0)
    at ../systemd/src/core/manager.c:2185
#17 0x00007f57c4919795 in source_dispatch (s=s@entry=0x55e50a40e7e0)
    at ../systemd/src/libsystemd/sd-event/sd-event.c:3544
#18 0x00007f57c4919cee in dispatch_exit (e=<optimized out>)
    at ../systemd/src/libsystemd/sd-event/sd-event.c:3654
#19 sd_event_dispatch (e=e@entry=0x55e50a410db0)
    at ../systemd/src/libsystemd/sd-event/sd-event.c:4071
#20 0x00007f57c491b319 in sd_event_run (e=0x55e50a410db0, timeout=18446744073709551615)
    at ../systemd/src/libsystemd/sd-event/sd-event.c:4139
#21 0x000055e508aec451 in manager_loop (m=0x55e50a40f5c0)
    at ../systemd/src/core/manager.c:2993
#22 0x000055e508aa6fb8 in invoke_main_loop (ret_error_message=0x7ffd4e539e60, ret_switch_root_init=<synthetic pointer>, ret_switch_root_dir=<synthetic pointer>, ret_fds=0x7ffd4e539e50, ret_shutdown_verb=<synthetic pointer>, ret_retval=<synthetic pointer>, ret_reexecute=<synthetic pointer>, saved_rlimit_memlock=0x7ffd4e539e70, saved_rlimit_nofile=0x7ffd4e539e80, m=0x55e50a40f5c0)
    at ../systemd/src/core/main.c:1873
#23 main (argc=1, argv=0x7ffd4e53a0e8)
    at ../systemd/src/core/main.c:288
```

### PR DESCRIPTION
**Pull request by unusual-thoughts**
Closes https://github.com/systemd/systemd/issues/20933

This verifies that the `argv` part of any `exec_command` parameters that are sent through dbus is not empty at deserialization time.

Possibly an additional check should be made in `service.c service_verify()` that would again check if all `exec_command`s are correctly populated, after the service has been deserialized, either through dbus or otherwise ?

### CODE REVIEW

File: src/core/dbus-execute.c [hunk 1]
```diff
@@ -1423,6 +1423,10 @@ int bus_set_transient_exec_command(
                 if (r < 0)
                         return r;
 
+                if (!argv)
+                        return sd_bus_error_setf(error, SD_BUS_ERROR_INVALID_ARGS,
+                                                 "\"%s\" argv cannot be empty", name);
+
```
Comment (yuwata) [inline src/core/dbus-execute.c]: I think we should accept an empty argv here. The empty argv means resetting exec command.

**Review by yuwata — CHANGES_REQUESTED** [review]

File: src/core/dbus-execute.c (hunk 1 above)
Comment (unusual-thoughts) [reply src/core/dbus-execute.c]: Are you sure ? The signature is typically `a(sasb)`:


> ExecStartPre, ExecStart, ExecStartPost, ExecReload, ExecStop, and ExecStop are arrays of structures where each struct contains: the binary path to execute; an array with all arguments to pass to the executed command, starting with argument 0; a boolean whether it should be considered a failure if the process exits uncleanly; two pairs of CLOCK_REALTIME/CLOCK_MONOTONIC microsecond timestamps when the process began and finished running the last time, or 0 if it never ran or never finished running; the PID of the process, or 0 if it has not run yet; the exit code and status of the last run. This field hence maps more or less to the corresponding setting in the service unit file but is augmented with runtime data.



Did you mean that the `a(sasb)` array itself can be empty ? this is looking at the inner `as` array.

Comment (unusual-thoughts) [reply src/core/dbus-execute.c]: Also of course this change does fix the crash described in https://github.com/systemd/systemd/issues/20933

```
busctl call \
  org.freedesktop.systemd1 /org/freedesktop/systemd1 \
  org.freedesktop.systemd1.Manager StartTransientUnit \
  "ssa(sv)a(sa(sv))" test.service replace \
  1 ExecStart "a(sasb)" 1 /usr/bin/sleep 0 true 0
```
now fails with a dbus error instead of crashing, while e.g.
```
busctl call \
  org.freedesktop.systemd1 /org/freedesktop/systemd1 \
  org.freedesktop.systemd1.Manager StartTransientUnit \
  "ssa(sv)a(sa(sv))" test.service replace \
  1 ExecStart "a(sasb)" 1 /usr/bin/sleep 2 /usr/bin/sleep infinity true 0
```
still works

Comment (yuwata) [reply src/core/dbus-execute.c]: Ah, the dbus method accepts `path` and `argv` separately. Hm, then this may be good. Sorry for the noise.

**Comment by yuwata** [comment]
Could you also add a testcase for the issue in test/TEST-XX-YYYY ?

**Comment by yuwata** [comment]
> Possibly an additional check should be made in `service.c service_verify()` that would again check if all `exec_command`s are correctly populated, after the service has been deserialized, either through dbus or otherwise ?

I like this idea.

**Comment by unusual-thoughts** [comment]
> > Possibly an additional check should be made in `service.c service_verify()` that would again check if all `exec_command`s are correctly populated, after the service has been deserialized, either through dbus or otherwise ?
> 
> I like this idea.

added here https://github.com/systemd/systemd/pull/20935/files#diff-88a01402a6feb6c8a13f32a718325c7fdbdd4ca47de52b147ff75eaace8e1903R569

**Comment by unusual-thoughts** [comment]
> Could you also add a testcase for the issue in test/TEST-XX-YYYY ?

done

File: src/core/service.c [hunk 2]
```diff
@@ -563,6 +563,13 @@ static int service_arm_timer(Service *s, usec_t usec) {
 static int service_verify(Service *s) {
         assert(s);
         assert(UNIT(s)->load_state == UNIT_LOADED);
+        ServiceExecCommand c;
+        ExecCommand *command;
+
+        for (c = 0; c < _SERVICE_EXEC_COMMAND_MAX; c++)
```
Comment (bluca) [inline src/core/service.c]: `for (ServiceExecCommand c = 0; ...`

and move ExecCommand declaration inside the for

File: src/core/service.c [hunk 3]
```diff
@@ -563,6 +563,13 @@ static int service_arm_timer(Service *s, usec_t usec) {
 static int service_verify(Service *s) {
         assert(s);
         assert(UNIT(s)->load_state == UNIT_LOADED);
+        ServiceExecCommand c;
+        ExecCommand *command;
```
Comment (yuwata) [inline src/core/service.c]: Please move them to the loop below:
```
for (ServiceExecCommand c = 0; c < _SERVICE_EXEC_COMMAND_MAX; c++) {
        ExecCommand *command;

        LIST_FOREACH(command, command, s->exec_command[c])
```

File: test/units/testsuite-66.sh [hunk 4]
```diff
@@ -0,0 +1,25 @@
+#!/usr/bin/env bash
+set -eux
+
```
Comment (bluca) [inline test/units/testsuite-66.sh]: set -o pipefail

File: src/core/dbus-execute.c [hunk 5]
```diff
@@ -1423,6 +1423,10 @@ int bus_set_transient_exec_command(
                 if (r < 0)
                         return r;
 
+                if (!argv)
```
Comment (bluca) [inline src/core/dbus-execute.c]: `strv_isempty(argv)`

**Review by yuwata — CHANGES_REQUESTED** [review]
Mostly good. But one nit.

Also, please explain and mention the issue in each commit.

**Comment by yuwata** [comment]
BTW, maybe better to merge the new tests with TEST-23-TYPE-EXEC or so, to slightly speed up CIs.

**Comment by yuwata** [comment]
I merged the new test with TEST-23, and several minor modification on your commits. @unusual-thoughts Could you pick the commits from https://github.com/yuwata/systemd/commits/fix-empty-argv, or change the permission to allow systemd maintainers push on your repository?

**Comment by yuwata** [comment]
Please pick the commits one by one... Adding new TEST-XX makes CIs slower. So, I'd like to merge the test cases you added into an existing one.

**Comment by unusual-thoughts** [comment]
> Please pick the commits one by one... Adding new TEST-XX makes CIs slower. So, I'd like to merge the test cases you added into an existing one.

Sorry about that. I have both commits now. BTW during transient unit dbus deserialization the path is checked not only for empty values but also for invalid paths:  https://github.com/systemd/systemd/blob/f5d40373b0250b100a3eb61f8f16620e21d12634/src/core/dbus-execute.c#L1417

**Comment by yuwata** [comment]
Indeed. Nice catch! Could you update the second commit? It is ok to replace the author of the commit with yours. Or, simply drop the second commit entirely.

**Comment by unusual-thoughts** [comment]
> Indeed. Nice catch! Could you update the second commit? It is ok to replace the author of the commit with yours. Or, simply drop the second commit entirely.

done

**Comment by msekletar** [comment]
I am reviewing backport of this PR to CentOS stream/RHEL and it makes me wonder whether the commit from @yuwata is actually needed (idea is sound but it seems to me it is actually a dead code ATM).

`service_verify()` is called only once in `service_load()`, however, incorrect value of Exec command is already refused in `config_parse_exec()`. We have the same check in `dbus-execute.c` which covers "over-the-bus" case. Thus the only remaining is deserialisation, however, `service_verify()` is *not* called after deserialisation. Should we add virtual function e.g. `unit_verify()` that would be called after deserialisation?
