### PR TITLE
journal-remote: improve man page and error message

### LINKED ISSUE #6675: RFE: journal-remote: determine output filename based on the hostname in the journal entries
### Submission type

 - Bug report

### systemd version the issue has been seen with
systemd-233, but the issue is still present in upstream git

### Used distribution

Fedora 26

### In case of bug report: Expected behaviour you didn't see

    cat foo | systemd-journal-remote --output . -

should work correctly

### In case of bug report: Unexpected behaviour you saw

It does not:

    For SplitMode=none, output must be a file.

### Cause of the problem

* arg_split_mode defaults to JOURNAL_WRITE_SPLIT_HOST. So far so good.
* "-" is placed into arg_files, for later use as stdin (https://github.com/systemd/systemd/blob/master/src/journal-remote/journal-remote.c#L1476). So far so good.
* This leads to type_a being set, as arg_files is no longer empty. Hmm... https://github.com/systemd/systemd/blob/master/src/journal-remote/journal-remote.c#L1479
* Which then (confusingly, and unconditionally) overwrites arg_split_mode with JOURNAL_SPLIT_MODE_NONE: https://github.com/systemd/systemd/blob/master/src/journal-remote/journal-remote.c#L1495. Ah, that's not good...

This is probably not what we wanted, and this actually breaks one of the manpage's provided examples:

    journalctl -o export | systemd-journal-remote -o /tmp/dir -

### PR DESCRIPTION
**Pull request by yuwata**
C.f. #6675.

### CODE REVIEW

File: src/journal-remote/journal-remote.c [hunk 1]
```diff
@@ -1495,10 +1495,15 @@ static int parse_argv(int argc, char *argv[]) {
                 arg_split_mode = JOURNAL_WRITE_SPLIT_NONE;
         }
 
-        if (arg_split_mode == JOURNAL_WRITE_SPLIT_NONE
-            && arg_output && is_dir(arg_output, true) > 0) {
-                log_error("For SplitMode=none, output must be a file.");
-                return -EINVAL;
+        if (arg_split_mode == JOURNAL_WRITE_SPLIT_NONE && arg_output) {
```
Comment (rburchell) [inline src/journal-remote/journal-remote.c:1498]: Sorry for the late comment, I thought I had submitted this, but apparently not.

Perhaps additionally the above overwrite of arg_split_mode deserves some kind of info-level notification like "SplitMode cannot be used for active sources, forcing SplitMode=none"?

**Comment by poettering** [comment]
CI failure appears unrelated
