### PR TITLE
core: do not free stack-allocated strings

### LINKED ISSUE #8387: Segfault mounting cgroups on ZEN kernel
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v238

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> Boots fine

### In case of bug report: Unexpected behaviour you saw

> Segfaults in libc after mounting cpuset cgroup

### In case of bug report: Steps to reproduce the problem

Linux ZEN is built with MuQSS (which has a `cpu` cgroup controller but no `cpuacct` one).
--> systemd in initramfs segfaults.

Booting with `systemd.unified_cgroup_hierarchy` avoids the problem.
**Reverting commit 56c8d7444ac212c48443a0d30e42ea279140f96d fixes the problem.**

It appears the issue is that the code at https://github.com/systemd/systemd/blob/56c8d7444ac212c48443a0d30e42ea279140f96d/src/core/mount-setup.c#L256-L267 now creates an array of arrays of string literals, but the code at https://github.com/systemd/systemd/blob/56c8d7444ac212c48443a0d30e42ea279140f96d/src/core/mount-setup.c#L292-L311 expects to manipulate heap-allocated strings.

Downstream bug: https://bugs.archlinux.org/task/57741

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #8387.

### CODE REVIEW

**Comment by keszybz** [comment]
Thanks.

File: src/core/mount-setup.c [hunk 1]
```diff
@@ -300,7 +301,8 @@ int mount_cgroup_controllers(char ***join_controllers) {
 
                                         t = set_remove(controllers, *i);
                                         if (!t) {
-                                                free(*i);
+                                                if (has_argument)
+                                                        free(*i);
```
Comment (evverx) [inline src/core/mount-setup.c:305]: `i` seems to be memory allocated from the heap by `malloc`, so I would say that the commit message is a little misleading.

**Comment by evverx** [comment]
On the whole, I think the code removed in https://github.com/systemd/systemd/commit/56c8d7444ac212c48443a0d30e42ea279140f96d is easier to understand and is more likely to be correct. Frankly, I'm still trying to figure out why `systemd` won't crash on `reexec`, for example.

File: src/core/mount-setup.c (hunk 1 above)
Comment (keszybz) [reply src/core/mount-setup.c:305]: Yeah, it should say "stack-allocated".

Comment (yuwata) [reply src/core/mount-setup.c:305]: Yeah, sorry. I copied the text from the issue. Please fix the commit message on merge.

**Comment by keszybz** [comment]
```
Ubuntu 17.10 autopkgtest ttyS0

autopkgtest login: 
---------------------------------------------------
<VirtSubproc>: failure: Timed out on waiting for ssh connection
autopkgtest [09:20:04]: ERROR: testbed failure: cannot send to testbed: [Errno 32] Broken pipe
```

File: src/core/mount-setup.c (hunk 1 above)
Comment (poettering) [reply src/core/mount-setup.c:305]: actually, "stack-allocated" isn't right either... These are literal strings (i.e. constants), hence they'll be placed in the data segment of the executable, which is neither stack nor heap... (yeah it's confusing, since we process an actually stack-allocated strv here, but the entries it points to are in the data segment...)

Comment (poettering) [reply src/core/mount-setup.c:305]: (and sorry for being a smart-ass about this ;-))
