### PR TITLE
test-execute: check capabilities before runnig tests

### LINKED ISSUE #8193: test-execute failing in test_exec_capabilityambientset
`test-execute` is failing in a Fedora rawhide nspawn container:
```
exec-capabilityambientset.service: Failed to set pids.max: No such file or directory
BPF firewalling not supported on this manager, proceeding without.
exec-capabilityambientset.service: Passing 0 fds to service
exec-capabilityambientset.service: About to execute: /bin/sh -x -c 'c=$$(grep "CapAmb:" /proc/self/status); test "$$c" = "CapAmb:	0000000000003000"'
exec-capabilityambientset.service: Forked /bin/sh as 23477
exec-capabilityambientset.service: Changed dead -> start
exec-capabilityambientset.service
	UMask: 0022
	WorkingDirectory: /root
	RootDirectory: /
	NonBlocking: no
	PrivateTmp: no
	PrivateDevices: no
	ProtectKernelTunables: no
	ProtectKernelModules: no
	ProtectControlGroups: no
	PrivateNetwork: no
	PrivateUsers: no
	ProtectHome: no
	ProtectSystem: no
	MountAPIVFS: no
	IgnoreSIGPIPE: yes
	MemoryDenyWriteExecute: no
	RestrictRealtime: no
	KeyringMode: inherit
	RuntimeDirectoryPreserve: no
	RuntimeDirectoryMode: 0755
	StateDirectoryMode: 0755
	CacheDirectoryMode: 0755
	LogsDirectoryMode: 0755
	ConfigurationDirectoryMode: 0755
	StandardInput: null
	StandardOutput: inherit
	StandardError: inherit
	AmbientCapabilities: cap_net_admin cap_net_raw
	User: nobody
	DynamicUser: no
	LockPersonality: no
exec-capabilityambientset.service: User lookup succeeded: uid=65534 gid=65534
exec-capabilityambientset.service: Failed to apply ambient capabilities (before UID change): Operation not permitted
exec-capabilityambientset.service: Failed at step CAPABILITIES spawning /bin/sh: Operation not permitted
Received SIGCHLD from PID 23477 ((sh)).
Child 23477 ((sh)) died (code=exited, status=218/CAPABILITIES)
exec-capabilityambientset.service: Child 23477 belongs to exec-capabilityambientset.service.
exec-capabilityambientset.service: Main process exited, code=exited, status=218/CAPABILITIES
exec-capabilityambientset.service: Failed with result 'exit-code'.
exec-capabilityambientset.service: Changed start -> failed
exec-capabilityambientset.service: Unit entered failed state.
	PID: 23477
	Start Timestamp: Thu 2018-02-15 23:11:37 CET
	Exit Timestamp: Thu 2018-02-15 23:11:37 CET
	Exit Code: exited
	Exit Status: 218
Assertion 'service->main_exec_status.status == status_expected' failed at ../src/test/test-execute.c:74, function check(). Aborting.
```
I think this is new. This is with  kernel-core-4.14.16-300.fc27.x86_64.  #4610 might be related or might not.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #8193.

### CODE REVIEW

File: src/test/test-execute.c [hunk 1]
```diff
@@ -551,8 +559,14 @@ static void test_exec_capabilityambientset(Manager *m) {
                 return;
         }
 
-        test(m, "exec-capabilityambientset.service", 0, CLD_EXITED);
-        test(m, "exec-capabilityambientset-merge.service", 0, CLD_EXITED);
+        if (have_effective_cap(CAP_NET_ADMIN) <= 0 ||
+            have_effective_cap(CAP_NET_RAW) <= 0) {
```
Comment (evverx) [inline src/test/test-execute.c]: I think these checks are the right thing to do, but would it also make sense to replace `CAP_NET_ADMIN` and `CAP_NET_RAW` with other capabilities that are less likely to be dropped by container runtimes to minimize the probability of the test being skipped?

File: src/test/test-execute.c [hunk 2]
```diff
@@ -551,8 +559,14 @@ static void test_exec_capabilityambientset(Manager *m) {
...
+                log_error("Skipping %s, this process does not have enough capabilities", __func__);
```
Comment (evverx) [inline src/test/test-execute.c]: I'm not sure about `log_error`. In other places in `test-execute`, `log_notice` is used to indicate events of this type.

File: src/test/test-execute.c (hunk 1 above)
Comment (yuwata) [reply src/test/test-execute.c]: OK. Do you have any proposal?

File: src/test/test-execute.c (hunk 2 above)
Comment (yuwata) [reply src/test/test-execute.c]: OK.

File: src/test/test-execute.c (hunk 1 above)
Comment (evverx) [reply src/test/test-execute.c]: I've skimmed over the following configs:
* https://github.com/systemd/systemd/blob/6cc7e918ffe2f6a08be2b3ea221b8dbb79e41a97/src/nspawn/nspawn.c#L153-L179
* https://github.com/moby/moby/blob/954e55b3745fe764df54e8fc19039b49bcd2f1a3/oci/defaults.go#L14-L29
* https://github.com/lxc/lxc/blob/19462d43e8e9744f08f127bfb5d5a9f08c1aafa9/src/lxc/conf.c#L209-L260
* https://github.com/rkt/rkt/blob/b429dc42790a31a2c4169d56838e1fbe671ce895/stage1/init/common/pod.go#L642-L656

and `CAP_NET_RAW` seems to be safe to use. Another one I would probably pick is `CAP_SETUID`.

File: src/test/test-execute.c [hunk 3]
```diff
@@ -551,8 +559,14 @@ static void test_exec_capabilityambientset(Manager *m) {
...
+                return;
+        }
+
+        test(m, "exec-ambientcapabilities.service", 0, CLD_EXITED);
```
Comment (evverx) [inline src/test/test-execute.c]: When I first read the code, I didn't notice the unit files had been renamed. I think it would be great if the commit message contained a more detailed explanation of the change :-)

Comment (evverx) [reply src/test/test-execute.c]: Basically, I can't seem to understand why it was necessary to rename the unit files. The names of all the other unit files related to capabilities begin with `exec-capability`.

**Comment by yuwata** [comment]
Updated. Changes are below.
- Use log_notice() instead of log_error()
- Add explanation in commit message why I want to rename test units
- Use CAP_CHOWN instead of CAP_NET_ADMIN, as suggested.

Please take a look.

**Comment by evverx** [comment]
@yuwata, thank you. Yesterday I wrote that the checks were the right thing to do, but now that `CAP_CHOWN` is used along with the other very common capabilities and given that it is impossible to check everything (for example, the test will fail without `CAP_SETPCAP`), I think that they are unnecessary and could be dropped.

Anyway, the PR looks good to me and I think it could be merged as is.

**Comment by keszybz** [comment]
I can confirm that this fixes #8193 for me.

**Comment by keszybz** [comment]
```

Ubuntu 17.10 autopkgtest ttyS0

autopkgtest login: 
---------------------------------------------------
<VirtSubproc>: failure: Timed out on waiting for ssh connection
autopkgtest [17:53:10]: ERROR: testbed failure: cannot send to testbed: [Errno 32] Broken pipe
```
