### PR TITLE
logind-dbus: avoid assertion on HandlePowerKey=factory-reset

### LINKED ISSUE #39385: HandlePowerKey=factory-reset causes assertion error
### systemd version the issue has been seen with

257.8-1~deb13u2

### Used distribution

Debian trixie

### Linux kernel version used

6.12.48+deb13-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

factory-reset.target being triggered

### Unexpected behaviour you saw

    Assertion 'IN_SET(a->inhibit_what, INHIBIT_SHUTDOWN, INHIBIT_SLEEP)' failed at src/login/logind-dbus.c:1824, function send_prepare_for(). Aborting.

### Steps to reproduce the problem

Note that I originally got this issue with yocto and systemd v257.6 and then tried to reproduce it with mkosi and qemu. The config can probably be reduced quite a bit:

mkosi.conf:

```conf
[Distribution]
Distribution=debian
Release=trixie
RepositoryKeyFetch=true

[Output]
Format=disk
OutputDirectory=out

[Include]
Include=mkosi-vm

[Content]
Bootable=yes
Packages=openssh-client
         vim
         systemd
         systemd-sysv
         dbus
RootPassword=password

[Validation]
Checksum=yes

[Runtime]
KVM=yes
```

mkosi.postinst.chroot:

```bash
#!/bin/bash

mkdir -p /etc/systemd/logind.conf.d
cat > /etc/systemd/logind.conf.d/99-factory-reset-bug.conf <<'EOF'
[Login]
# This will cause an assertion failure when power button is pressed
HandlePowerKey=factory-reset
EOF
```

    mkosi build

    sudo mkosi qemu

    journalctl -u systemd-logind -f

Then I presss `C-a c` and run `system_powerdown`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
(qemu) system_powerdown 
(qemu) Oct 20 10:41:41 localhost systemd-logind[525]: Power key pressed short.
Oct 20 10:41:41 localhost systemd-logind[525]: Performing factory reset...
Oct 20 10:41:41 localhost systemd-logind[525]: Assertion 'IN_SET(a->inhibit_what, INHIBIT_SHUTDOWN, INHIBIT_SLEEP)' failed at src/login/logind-dbus.c:1824, function send_prepare_for(). Aborting.
Oct 20 10:41:42 localhost systemd-coredump[575]: [🡕] Process 525 (systemd-logind) of user 0 dumped core.
Oct 20 10:41:42 localhost systemd[1]: systemd-logind.service: Main process exited, code=dumped, status=6/ABRT
Oct 20 10:41:42 localhost systemd[1]: systemd-logind.service: Failed with result 'core-dump'.
```

### PR DESCRIPTION
**Pull request by dtardon**
The factory-reset action is handled together with the various sleep/shutdown actions, but its not either one.

Fixes #39385

### CODE REVIEW

File: src/login/logind-dbus.c [hunk 1]
```diff
@@ -1946,7 +1946,11 @@ static int send_prepare_for(Manager *m, const HandleActionData *a, bool _active)
 
         assert(m);
         assert(a);
-        assert(IN_SET(a->inhibit_what, INHIBIT_SHUTDOWN, INHIBIT_SLEEP));
+        assert(IN_SET(a->inhibit_what, INHIBIT_SHUTDOWN, INHIBIT_SLEEP, _INHIBIT_WHAT_INVALID));
```
Comment (poettering) [inline src/login/logind-dbus.c]: maybe move this line down, after the if check. that way you don't have to extend the list.

**Comment by ecksun** [comment]
If I apply this patch to my yocto system using systemd v257.6 I now get this error instead:

    systemd-logind[270]: Assertion 'w > 0' failed at c/debug/systemd/257.6/src/login/logind-inhibit.c:414, function manager_is_inhibited(). Aborting.

I'm not sure how relevant it is to this particular PR but I thought it noteworthy nontheless

**Comment by dtardon** [comment]
> If I apply this patch to my yocto system using systemd v257.6 I now get this error instead:
> 
> ```
> systemd-logind[270]: Assertion 'w > 0' failed at c/debug/systemd/257.6/src/login/logind-inhibit.c:414, function manager_is_inhibited(). Aborting.
> ```
> 
> I'm not sure how relevant it is to this particular PR but I thought it noteworthy nontheless

It is. My first attempt just allowed to go a bit further... I've added `a->inhibit_what > 0` to the condition to call `manager_is_inhibited()`, but it might make sense to allow invalid `InhibitWhat` parameter in that function and just return `false` in that case.

File: src/login/logind-dbus.c [hunk 2]
```diff
@@ -2163,6 +2168,7 @@ int bus_manager_shutdown_or_sleep_now_or_later(
 
         delayed =
                 m->inhibit_delay_max > 0 &&
+                a->inhibit_what >= 0 &&
```
Comment (yuwata) [inline src/login/logind-dbus.c:2171]: When you touch the code, please move the two conditions into `manager_is_inhibit()`.

**Review by yuwata — CHANGES_REQUESTED** [review]

File: src/login/logind-dbus.c (hunk 2 above)
Comment (yuwata) [reply src/login/logind-dbus.c:2171]: Reconsidering about this. The current form is better. Sorry for the noise and blocking merge.
