### PR TITLE
network: IPv4LL and ACD fixes

### LINKED ISSUE #12145: systemd-networkd IPV4LL addr assingment and drop in loop
**systemd version the issue has been seen with**
> systemd 239

**Used distribution**
 > Custom, built with Yocto Project master branch

**Expected behaviour you didn't see**
 > DHCP IPv4 and IPV4LL addresses assigned and not removed.

**Unexpected behaviour you saw**
 > The systemd-networkd removes and adds IPV4LL addr in a loop.

**Steps to reproduce the problem**

**/lib/systemd/network/10-net.network:**
```
[Network]
LinkLocalAddressing=yes
DHCP=ipv4
```

Plugged a USB cellular module (Quectel EC25) which is presented in the system as usb1 and uses the cdc_ether driver.

The systemd-networkd removes and adds the IPV4LL in a loop. I couldn't reproduce this behavior in the native ethernet interface.

systemd-networkd log with `Environment=SYSTEMD_LOG_LEVEL=debug`:
```
Mar 29 14:01:35 localhost systemd-networkd[29786]: IPV4ACD: Probing 169.254.192.231
Mar 29 14:01:36 localhost systemd-networkd[29786]: IPV4ACD: Probing 169.254.192.231
Mar 29 14:01:38 localhost systemd-networkd[29786]: IPV4ACD: Probing 169.254.192.231
Mar 29 14:01:41 localhost systemd-networkd[29786]: IPV4ACD: ANNOUNCE
Mar 29 14:01:41 localhost systemd-networkd[29786]: usb1: IPv4 link-local claim 169.254.192.231
Mar 29 14:01:41 localhost systemd-networkd[29786]: usb1: Updating address: 169.254.192.231/16 (valid forever)
Mar 29 14:01:41 localhost systemd-networkd[29786]: IPV4ACD: DEFEND
Mar 29 14:01:42 localhost systemd-networkd[29786]: IPV4ACD: Conflict on 169.254.192.231 (1)
Mar 29 14:01:42 localhost systemd-networkd[29786]: usb1: IPv4 link-local release 169.254.192.231
Mar 29 14:01:42 localhost systemd-networkd[29786]: IPV4LL: Picked new IP address 169.254.192.231.
Mar 29 14:01:42 localhost systemd-networkd[29786]: usb1: Removing address: 169.254.192.231/16 (valid forever)
Mar 29 14:01:42 localhost systemd-networkd[29786]: IPV4ACD: Probing 169.254.192.231
Mar 29 14:01:44 localhost systemd-networkd[29786]: IPV4ACD: Probing 169.254.192.231
Mar 29 14:01:45 localhost systemd-networkd[29786]: IPV4ACD: Probing 169.254.192.231
Mar 29 14:01:48 localhost systemd-networkd[29786]: IPV4ACD: ANNOUNCE
Mar 29 14:01:48 localhost systemd-networkd[29786]: usb1: IPv4 link-local claim 169.254.192.231
Mar 29 14:01:48 localhost systemd-networkd[29786]: usb1: Updating address: 169.254.192.231/16 (valid forever)
Mar 29 14:01:48 localhost systemd-networkd[29786]: IPV4ACD: DEFEND
Mar 29 14:01:49 localhost systemd-networkd[29786]: IPV4ACD: Conflict on 169.254.192.231 (1)
Mar 29 14:01:49 localhost systemd-networkd[29786]: usb1: IPv4 link-local release 169.254.192.231
Mar 29 14:01:49 localhost systemd-networkd[29786]: IPV4LL: Picked new IP address 169.254.192.231.
Mar 29 14:01:49 localhost systemd-networkd[29786]: usb1: Removing address: 169.254.192.231/16 (valid forever)
Mar 29 14:01:49 localhost systemd-networkd[29786]: IPV4ACD: Probing 169.254.192.231
Mar 29 14:01:51 localhost systemd-networkd[29786]: IPV4ACD: Probing 169.254.192.231
Mar 29 14:01:53 localhost systemd-networkd[29786]: IPV4ACD: Probing 169.254.192.231
```

### LINKED ISSUE #17235: SendDecline side effect with multiple interface on the same network
**systemd version the issue has been seen with**
> systemd 246 (246)
> +PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL -XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Gentroo

**Linux kernel version used** (`uname -a`)
 > Linux lady-voodoo.local 5.4.67-longterm #1 SMP PREEMPT 2020-10-01T23:33:09+01:00 x86_64 Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz GenuineIntel GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

When a system has 2 network interfaces (here Ethernet and WiFi) connected into the same L2 network, both configured with `[DHCPv4] SendDecline=true`, systemd-networkd identifies both IP as DAD. This issue can also be observed when only one of the 2 interface has `SendDecline` enabled, I will use this here to simplify the bug report.

```
Oct 02 16:58:40 lady-voodoo.local systemd-networkd[14730]: eth0: DHCPv4 address 10.134.1.141/25 via 10.134.1.129
Oct 02 16:58:40 lady-voodoo.local systemd-networkd[14730]: eth0: DAD conflict. Dropping DHCP4 address 10.134.1.141
Oct 02 16:58:40 lady-voodoo.local systemd-networkd[14730]: eth0: DHCP lease lost
```

Looking a bit more into details about this, I can see the following is observed from a network capture:

* Interface L2 info:

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP mode DEFAULT group default qlen 1000
    link/ether 24:f5:aa:c7:86:a6 brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DORMANT group default qlen 1000
    link/ether 28:b2:bd:c0:42:e8 brd ff:ff:ff:ff:ff:ff
```

* Traffic on interface #1 (eth0)
```
$ sudo tcpdump -i eth0 -nn -vv -s 0 -e arp and not host 10.134.1.129 --direction=out
..
16:57:48.783829 24:f5:aa:c7:86:a6 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 10.134.1.141 tell 0.0.0.0, length 28
16:57:48.993494 24:f5:aa:c7:86:a6 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 10.134.1.141 tell 0.0.0.0, length 28
..
```
```
$ sudo tcpdump -i eth0 -nn -vv -s 0 -e arp and not host 10.134.1.129 --direction=in
<empty>
```

* Traffic on interface #2 (wlan0)

```
$ sudo tcpdump -i wlan0 -nn -vv -s 0 -e arp and not host 10.134.1.129 --direction=out
<empty>
```
```
$ sudo tcpdump -i wlan0 -nn -vv -s 0 -e arp and not host 10.134.1.129 --direction=in
..
16:57:48.861772 24:f5:aa:c7:86:a6 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 60: Ethernet (len 6), IPv4 (len 4), Request who-has 10.134.1.141 tell 0.0.0.0, length 46
16:57:49.065638 24:f5:aa:c7:86:a6 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 60: Ethernet (len 6), IPv4 (len 4), Request who-has 10.134.1.141 tell 0.0.0.0, length 46
..
```

What is happening here is the following:
* An ARP request is broadcasted on `eth0` to identify a duplicate (this is expected)
* The ARP request is reaching all devices on the L2 network where `eth0` is connected (this is expected)
* Which means, the second interface (wlan0) is also receiving the ARP request with eth0 MAC address as the source (this is expected)
* systemd-networkd identifies this ARP packet as a DAD, this is not expected since the source MAC of the incoming packet is the MAC address of the initial interface sending the packet out

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #12145.
Fixes #17235.

### CODE REVIEW

**Comment by yuwata** [comment]
I added this to v249 milestone. If this is too late to be included in v249, feel free to drop it. But this is slightly large, and maybe hard to backport this after v249.

File: src/libsystemd-network/sd-ipv4acd.c [hunk 1]
```diff
@@ -432,12 +432,24 @@ const char *sd_ipv4acd_get_ifname(sd_ipv4acd *acd) {
...
         assert_return(addr, -EINVAL);
-        assert_return(acd->state == IPV4ACD_STATE_INIT, -EBUSY);
+        assert_return(!ether_addr_is_null(addr), -EINVAL);
 
         acd->mac_addr = *addr;
 
+        if (!sd_ipv4acd_is_running(acd))
+                return 0;
+
+        assert(acd->fd);
```
Comment (poettering) [inline src/libsystemd-network/sd-ipv4acd.c]: `assert(acd->fd >= 0)`

File: src/libsystemd-network/sd-ipv4acd.c [hunk 2]
```diff
@@ -490,14 +490,35 @@ int sd_ipv4acd_set_callback(sd_ipv4acd *acd, sd_ipv4acd_callback_t cb, void *use
...
+
+        if (in4_addr_equal(&acd->address, address))
+                return 0;
 
         acd->address = *address;
 
+        if (!sd_ipv4acd_is_running(acd))
+                return 0;
+
+        assert(acd->fd);
```
Comment (poettering) [inline src/libsystemd-network/sd-ipv4acd.c]: `>= 0`

File: src/libsystemd-network/sd-ipv4acd.c [hunk 3]
```diff
@@ -316,6 +305,41 @@ static int ipv4acd_on_timeout(sd_event_source *s, uint64_t usec, void *userdata)
...
+         * interfaces, then the host SHOULD similarly treat this as an address conflict" */
+        if (arp->ea_hdr.ar_op != htobe16(ARPOP_REQUEST))
+                return false; /* not ARP Request, ignoring. */
+        if (memeqzero(arp->arp_spa, sizeof(struct in_addr)) == 0)
+                return false; /* not ARP Probe, ignoring. */
+        if (memcmp(arp->arp_tpa, &acd->address, sizeof(struct in_addr)) != 0)
+                return false; /* target IP address does not match, BPF code is broken? */
+
+        SET_FOREACH(a, acd->other_mac_addrs)
+                if (memcmp(arp->arp_sha, a, ETH_ALEN) == 0)
```
Comment (poettering) [inline src/libsystemd-network/sd-ipv4acd.c]: ether_addr_equal()?

Comment (poettering) [reply src/libsystemd-network/sd-ipv4acd.c]: ah, i see, arp_sha is not of type struct ether_addr. ignore hence

File: src/libsystemd-network/sd-ipv4acd.c [hunk 4]
```diff
@@ -453,6 +455,28 @@ int sd_ipv4acd_set_mac(sd_ipv4acd *acd, const struct ether_addr *addr) {
...
+        return set_ensure_consume(&acd->other_mac_addrs, &ether_addr_hash_ops_free, a);
+}
+
+int sd_ipv4acd_remove_other_mac(sd_ipv4acd *acd, const struct ether_addr *addr) {
+        assert_return(acd, -EINVAL);
+        assert_return(addr, -EINVAL);
+
+        free(set_remove(acd->other_mac_addrs, addr));
+        return 0;
+}
```
Comment (poettering) [inline src/libsystemd-network/sd-ipv4acd.c]: i wonder if this shouldn't be done with a callback instead. I.e. instead of propagating the MAC addresses of the whole system continously into all sd_ipv4acd objects, do it the other way round: allow configuring a callback function that is called whenver a MAC address should be checked if local. And then maintain a single global hashmap inside of networkd where we keep track of all local MAC addreses and the interfaces they belong to.

This could even be useful to detect MAC address collisions when automatically assigning a MAC address or so.

Or in other words:

1. Extend the `Manager` object to gain a new field `links_by_mac_address`. It's keyed by the mac address and points to the interface with that MAC address, as is kept track of the same way as `links_by_name` is. (if we want to support that the same MAC address may be set for multiple local interfaces, then I guess we need to make sure that links with the same one are linked up in a linked list, and the `links_by_mac_address` hashmap points only to the first of them.

2. Add sd_ipv4acd_set_other_mac_callback() that takes an `sd_ipv4acd_other_mac_callback_t` parameter which is a function that returns 0, 1 or error, and gets a `const struct ether_addr` as parameter.

3. Add glue code to networkd to implement sd_ipv4acd_other_mac_callback_t once, and make it check the `links_by_mac_address` hashmap.

I think this would be more robust, less duplication and use less resources.

(Btw, I think it would be nice to rename the `links` field in `Manager` to `links_by_ifindex`, so that we then nicely have `links_by_ifindex`, `links_by_ifname` and `links_by_mac`)

**Comment by yuwata** [comment]
@poettering Thank you for your review. Now, the callback mechanisms which checks the sender hardware address is introduced to sd-ipv4acd and sd-ipv4ll. PTAL.

File: src/network/networkd-link.c [hunk 5]
```diff
@@ -1984,18 +2002,34 @@ static int link_update_hardware_address(Link *link, sd_netlink_message *message)
...
-                return log_link_warning_errno(link, r, "rtnl: failed to read hardware address: %m");
+                return log_link_debug_errno(link, r, "rtnl: failed to read hardware address: %m");
 
-        if (hw_addr_equal(&link->hw_addr, &hw_addr))
+        if (hw_addr_equal(&link->hw_addr, &old))
                 return 0;
 
-        link->hw_addr = hw_addr;
+        if (hw_addr_is_null(&old))
+                log_link_debug(link, "Saved hardware address: %s", HW_ADDR_TO_STR(&link->hw_addr));
```
Comment (keszybz) [inline src/network/networkd-link.c:2022]: I wasn't aware of `HW_ADDR_TO_STR()`. The trick with a temporary buffer is neat. I wasn't sure if it is valid, but it seems so. At least for C++ it seems that this is well defined: https://stackoverflow.com/questions/37946437/when-exactly-does-the-destruction-of-a-temporary-object-happen-in-a-function-cal says
>  the temporary is destroyed after the end of the full-expression containing it

And the "full-expression" is the function call (http://eel.is/c++draft/intro.execution#5, the outermost function call in case of nested calls due to 5.6).

I hope C follows the same rules.

Anyway, it's not directly related to this PR.

File: src/network/networkd-ipv4ll.c [hunk 6]
```diff
@@ -184,31 +184,16 @@ int ipv4ll_configure(Link *link) {
...
-                return r;
-
-        if (restart) {
-                r = sd_ipv4ll_start(link->ipv4ll);
-                if (r < 0)
-                        return r;
-        }
-
-        return 0;
+        return sd_ipv4ll_set_mac(link->ipv4ll, &link->hw_addr.ether);
```
Comment (keszybz) [inline src/network/networkd-ipv4ll.c:211]: Nice.

File: src/network/networkd-address.c [hunk 7]
```diff
@@ -1153,6 +1153,22 @@ int link_request_address(
...
+
+        assert(link);
+        assert(address);
+
+        r = link_request_address(link, address, consume, &link->static_address_messages,
+                                 static_address_handler, &req);
+        if (r < 0)
+                return r;
+
+        req->after_configure = static_address_after_configure;
```
Comment (keszybz) [inline src/network/networkd-address.c:1148]: Before, the callback was only set when `link_request_address()` returned 1. Now, it is always set. Can you comment on this?

File: src/network/networkd-ipv4acd.c [hunk 8]
```diff
@@ -0,0 +1,234 @@
...
+                if (address_get(link, address, NULL) < 0)
+                        return;
+
+                r = address_remove(address, link);
+                if (r < 0) {
+                        log_link_warning_errno(link, r, "Failed to remove address "IPV4_ADDRESS_FMT_STR": %m",
+                                               IPV4_ADDRESS_FMT_VAL(address->in_addr.in));
+                        link_enter_failed(link);
+                }
+                break;
```
Comment (keszybz) [inline src/network/networkd-ipv4acd.c]: Hmm, so we remove the address if the acd client is stopped… Or in other words, we effectively add an address by creating the acd client for it, and remove it by stopping the acd client… I wonder if we should then rename things, to emphasize the "address" part and de-emphesize the "conflict detection" part. But I don't have any good suggestions.

**Review by keszybz — COMMENTED** [review]
LGTM. I'd be inclined to merge this for 249.

File: src/network/networkd-address.c (hunk 7 above)
Comment (keszybz) [reply src/network/networkd-address.c:1148]: @yuwata ^

Comment (yuwata) [reply src/network/networkd-address.c:1148]: Thank you for catching this. This is an error. Fixed.

File: src/network/networkd-ipv4acd.c (hunk 8 above)
Comment (yuwata) [reply src/network/networkd-ipv4acd.c]: You mean about the log messages? The messages in the callback function is updated. PTAL.

**Comment by yuwata** [comment]
@keszybz Thank you for your review. Force-pushed a revised version. In addition to the above points you commented, the following changes are applied.
- in dhcp_lease_lost(), now the pending request is also dropped.
- in on_acd(), DHCPv4 address is not removed in the function, but dhcp_lease_lost() drop it.
- split on_acd() into several small functions.

File: src/network/networkd-ipv4acd.c [hunk 9]
```diff
@@ -0,0 +1,271 @@
...
+
+        r = sd_dhcp_client_send_decline(link->dhcp_client);
+        if (r < 0)
+                log_link_warning_errno(link, r, "Failed to send DHCP DECLINE, ignoring: %m");
+
+        if (!link->dhcp_lease)
+                /* Unlikely, but during probing the address, the lease may be lost. */
+                return 0;
+
+        log_link_warning(link, "Dropping DHCPv4 lease, as an address conflict is detected.");
```
Comment (keszybz) [inline src/network/networkd-ipv4acd.c:69]: "is" → "was"

**Review by keszybz — COMMENTED** [review]
s390x: "boot-and-services": `test_service (__main__.NspawnTest) ... Failed to dump process list for 'systemd-nspawn@c1.service', ignoring: Unit systemd-nspawn@c1.service not loaded.`
Looks unrelated.

LGTM, let's get this merged.
