### PR TITLE
sd-device-monitor: dynamically allocate receive buffer

### LINKED ISSUE #24987: device_monitor_receive_device buffer size not sufficient for some entries
### systemd version the issue has been seen with

252-rc1+

### Used distribution

Ubuntu 22.04

### Linux kernel version used

5.15.0-43-generic

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

device_monitor_receive_device to adapt to (be having an optional argument to call for that behavior) entries that exceed the currently static allocation of the 8192 byte buffer.

### Unexpected behaviour you saw

Calling [device_monitor_receive_device](https://github.com/systemd/systemd/blob/main/src/libsystemd/sd-device/device-monitor.c#L483)  on some systems which deliver more than the 8192 bytes that are expected [break on](https://github.com/systemd/systemd/blob/main/src/libsystemd/sd-device/device-monitor.c#L519) as it sees smsg.msg_flags & MSG_TRUNC and then reports back an EINVAL.

That has affected libvirtd and we were wondering if it is a systemd bug (no one was aware of e.g. a standard that limits the size to 8192) which due to the unexpected EINVAL did end up [broken here](https://gitlab.com/libvirt/libvirt/-/issues/245).

If there is a standard that defines this size to max 8192 I'm happy to learn, we can consider this closed and a problem of the firmware. But otherwise systemd should consider adapting the buffer size in some way to be able to handle those entries as well.

I simplified this from libvirt to a small test program and then used systemd from git to ensure it wasn't recently fixed.

### Steps to reproduce the problem

We found this when reacting to the dmi data on a "HP ProLiant DL360 Gen9".
Other systems might expose something similar, but we do not know about such so far.

On the mentioned system we read via device_monitor_receive_device from libvirtd (but any other user of device_monitor_receive_device should see the same) fail. Therefore

1. run code that spins on `device_monitor_receive_device`
2. re-emit dmi events with:
  $ sudo udevadm trigger --action=add --subsystem-match dmi
3. That will make it return EINVAL as outlined above.

I've found [udev_test.c](https://gist.github.com/syohex/6446167) which almost does what I need to show it.
Changing the filter to "dmi",NULL and reporting the errno gave me [this small program](https://paste.ubuntu.com/p/qFMnsQ8xDt/).

Which as expected on retriggering the dmi event gives me:
```
$ gcc -Wall udev_test.c -o udev_test -ludev && sudo ./udev_test 
@@ receive device is not found(check2) => Invalid argument
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# Stracing the readmsg that libudev does for libvirt showing the raw content

$ sudo strace -e recvmsg -s 8192 -r -tt -ff -p $(pidof libvirtd)
strace: Process 2243029 attached with 19 threads
[pid 2243029] 10:40:47.119923 (+     0.000000) recvmsg(13, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000001}, msg_namelen=12, msg_iov=[{iov_base="add@/devices/virtual/dmi/id\0ACTION=add\0DEVPATH=/devices/virtual/dmi/id\0SUBSYSTEM=dmi\0SYNTH_UUID=0\0MODALIAS=dmi:bvnHP:bvrP89:bd01/22/2018:br2.56:efr2.60:svnHP:pnProLiantDL360Gen9:pvr:rvnHP:rnProLiantDL360Gen9:rvr:cvnHP:ct23:cvr:sku780018-S01:\0SEQNUM=1682063\0", iov_len=16384}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_PEEK|MSG_TRUNC) = 257
[pid 2243029] 10:40:47.120347 (+     0.000358) recvmsg(13, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000001}, msg_namelen=12, msg_iov=[{iov_base="add@/devices/virtual/dmi/id\0ACTION=add\0DEVPATH=/devices/virtual/dmi/id\0SUBSYSTEM=dmi\0SYNTH_UUID=0\0MODALIAS=dmi:bvnHP:bvrP89:bd01/22/2018:br2.56:efr2.60:svnHP:pnProLiantDL360Gen9:pvr:rvnHP:rnProLiantDL360Gen9:rvr:cvnHP:ct23:cvr:sku780018-S01:\0SEQNUM=1682063\0", iov_len=16384}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 257
[pid 2243096] 10:40:47.128458 (+     0.008117) recvmsg(24, {msg_name={sa_family=AF_NETLINK, nl_pid=1269060, nl_groups=0x000002}, msg_namelen=128 => 12, msg_iov=[{iov_base=[{prefix="libudev", magic=htonl(0xfeedcafe), header_size=40, properties_off=40, properties_len=12371, filter_subsystem_hash=htonl(0x9d224c86), filter_devtype_hash=htonl(0), filter_tag_bloom_hi=htonl(0), filter_tag_bloom_lo=htonl(0)}, "ACTION=add\0DEVPATH=/devices/virtual/dmi/id\0SUBSYSTEM=dmi\0SYNTH_UUID=0\0MODALIAS=dmi:bvnHP:bvrP89:bd01/22/2018:br2.56:efr2.60:svnHP:pnProLiantDL360Gen9:pvr:rvnHP:rnProLiantDL360Gen9:rvr:cvnHP:ct23:cvr:sku780018-S01:\0SEQNUM=1682063\0USEC_INITIALIZED=3193195\0ID_VENDOR=HP\0ID_MODEL=ProLiant DL360 Gen9\0MEMORY_ARRAY_LOCATION=System Board Or Motherboard\0MEMORY_ARRAY_EC_TYPE=Multi-bit ECC\0MEMORY_ARRAY_MAX_CAPACITY=1649267441664\0MEMORY_DEVICE_0_TOTAL_WIDTH=72\0MEMORY_DEVICE_0_DATA_WIDTH=64\0MEMORY_DEVICE_0_SIZE=17179869184\0MEMORY_DEVICE_0_FORM_FACTOR=DIMM\0MEMORY_DEVICE_0_LOCATOR=PROC 1 DIMM 1\0MEMORY_DEVICE_0_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_0_TYPE=DDR4\0MEMORY_DEVICE_0_TYPE_DETAIL=Synchronous Registered (Buffered)\0MEMORY_DEVICE_0_SPEED_MTS=2133\0MEMORY_DEVICE_0_MANUFACTURER=HP\0MEMORY_DEVICE_0_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_0_ASSET_TAG=Not Specified\0MEMORY_DEVICE_0_PART_NUMBER=752369-081\0MEMORY_DEVICE_0_RANK=2\0MEMORY_DEVICE_0_CONFIGURED_SPEED_MTS=1866\0MEMORY_DEVICE_0_MINIMUM_VOLTAGE=1\0MEMORY_DEVICE_0_MAXIMUM_VOLTAGE=1\0MEMORY_DEVICE_0_CONFIGURED_VOLTAGE=1\0MEMORY_DEVICE_1_TOTAL_WIDTH=72\0MEMORY_DEVICE_1_DATA_WIDTH=64\0MEMORY_DEVICE_1_PRESENT=0\0MEMORY_DEVICE_1_FORM_FACTOR=DIMM\0MEMORY_DEVICE_1_SET=1\0MEMORY_DEVICE_1_LOCATOR=PROC 1 DIMM 2\0MEMORY_DEVICE_1_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_1_TYPE=DDR4\0MEMORY_DEVICE_1_TYPE_DETAIL=Synchronous\0MEMORY_DEVICE_1_MANUFACTURER=UNKNOWN\0MEMORY_DEVICE_1_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_1_ASSET_TAG=Not Specified\0MEMORY_DEVICE_1_PART_NUMBER=NOT AVAILABLE\0MEMORY_DEVICE_2_TOTAL_WIDTH=72\0MEMORY_DEVICE_2_DATA_WIDTH=64\0MEMORY_DEVICE_2_PRESENT=0\0MEMORY_DEVICE_2_FORM_FACTOR=DIMM\0MEMORY_DEVICE_2_SET=2\0MEMORY_DEVICE_2_LOCATOR=PROC 1 DIMM 3\0MEMORY_DEVICE_2_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_2_TYPE=DDR4\0MEMORY_DEVICE_2_TYPE_DETAIL=Synchronous\0MEMORY_DEVICE_2_MANUFACTURER=UNKNOWN\0MEMORY_DEVICE_2_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_2_ASSET_TAG=Not Specified\0MEMORY_DEVICE_2_PART_NUMBER=NOT AVAILABLE\0MEMORY_DEVICE_3_TOTAL_WIDTH=72\0MEMORY_DEVICE_3_DATA_WIDTH=64\0MEMORY_DEVICE_3_SIZE=17179869184\0MEMORY_DEVICE_3_FORM_FACTOR=DIMM\0MEMORY_DEVICE_3_SET=3\0MEMORY_DEVICE_3_LOCATOR=PROC 1 DIMM 4\0MEMORY_DEVICE_3_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_3_TYPE=DDR4\0MEMORY_DEVICE_3_TYPE_DETAIL=Synchronous Registered (Buffered)\0MEMORY_DEVICE_3_SPEED_MTS=2133\0MEMORY_DEVICE_3_MANUFACTURER=HP\0MEMORY_DEVICE_3_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_3_ASSET_TAG=Not Specified\0MEMORY_DEVICE_3_PART_NUMBER=752369-081\0MEMORY_DEVICE_3_RANK=2\0MEMORY_DEVICE_3_CONFIGURED_SPEED_MTS=1866\0MEMORY_DEVICE_3_MINIMUM_VOLTAGE=1\0MEMORY_DEVICE_3_MAXIMUM_VOLTAGE=1\0MEMORY_DEVICE_3_CONFIGURED_VOLTAGE=1\0MEMORY_DEVICE_4_TOTAL_WIDTH=72\0MEMORY_DEVICE_4_DATA_WIDTH=64\0MEMORY_DEVICE_4_PRESENT=0\0MEMORY_DEVICE_4_FORM_FACTOR=DIMM\0MEMORY_DEVICE_4_SET=4\0MEMORY_DEVICE_4_LOCATOR=PROC 1 DIMM 5\0MEMORY_DEVICE_4_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_4_TYPE=DDR4\0MEMORY_DEVICE_4_TYPE_DETAIL=Synchronous\0MEMORY_DEVICE_4_MANUFACTURER=UNKNOWN\0MEMORY_DEVICE_4_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_4_ASSET_TAG=Not Specified\0MEMORY_DEVICE_4_PART_NUMBER=NOT AVAILABLE\0MEMORY_DEVICE_5_TOTAL_WIDTH=72\0MEMORY_DEVICE_5_DATA_WIDTH=64\0MEMORY_DEVICE_5_PRESENT=0\0MEMORY_DEVICE_5_FORM_FACTOR=DIMM\0MEMORY_DEVICE_5_SET=5\0MEMORY_DEVICE_5_LOCATOR=PROC 1 DIMM 6\0MEMORY_DEVICE_5_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_5_TYPE=DDR4\0MEMORY_DEVICE_5_TYPE_DETAIL=Synchronous\0MEMORY_DEVICE_5_MANUFACTURER=UNKNOWN\0MEMORY_DEVICE_5_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_5_ASSET_TAG=Not Specified\0MEMORY_DEVICE_5_PART_NUMBER=NOT AVAILABLE\0MEMORY_DEVICE_6_TOTAL_WIDTH=72\0MEMORY_DEVICE_6_DATA_WIDTH=64\0MEMORY_DEVICE_6_PRESENT=0\0MEMORY_DEVICE_6_FORM_FACTOR=DIMM\0MEMORY_DEVICE_6_SET=6\0MEMORY_DEVICE_6_LOCATOR=PROC 1 DIMM 7\0MEMORY_DEVICE_6_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_6_TYPE=DDR4\0MEMORY_DEVICE_6_TYPE_DETAIL=Synchronous\0MEMORY_DEVICE_6_MANUFACTURER=UNKNOWN\0MEMORY_DEVICE_6_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_6_ASSET_TAG=Not Specified\0MEMORY_DEVICE_6_PART_NUMBER=NOT AVAILABLE\0MEMORY_DEVICE_7_TOTAL_WIDTH=72\0MEMORY_DEVICE_7_DATA_WIDTH=64\0MEMORY_DEVICE_7_PRESENT=0\0MEMORY_DEVICE_7_FORM_FACTOR=DIMM\0MEMORY_DEVICE_7_SET=7\0MEMORY_DEVICE_7_LOCATOR=PROC 1 DIMM 8\0MEMORY_DEVICE_7_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_7_TYPE=DDR4\0MEMORY_DEVICE_7_TYPE_DETAIL=Synchronous\0MEMORY_DEVICE_7_MANUFACTURER=UNKNOWN\0MEMORY_DEVICE_7_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_7_ASSET_TAG=Not Specified\0MEMORY_DEVICE_7_PART_NUMBER=NOT AVAILABLE\0MEMORY_DEVICE_8_TOTAL_WIDTH=72\0MEMORY_DEVICE_8_DATA_WIDTH=64\0MEMORY_DEVICE_8_SIZE=17179869184\0MEMORY_DEVICE_8_FORM_FACTOR=DIMM\0MEMORY_DEVICE_8_SET=8\0MEMORY_DEVICE_8_LOCATOR=PROC 1 DIMM 9\0MEMORY_DEVICE_8_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_8_TYPE=DDR4\0MEMORY_DEVICE_8_TYPE_DETAIL=Synchronous Registered (Buffered)\0MEMORY_DEVICE_8_SPEED_MTS=2133\0MEMORY_DEVICE_8_MANUFACTURER=HP\0MEMORY_DEVICE_8_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_8_ASSET_TAG=Not Specified\0MEMORY_DEVICE_8_PART_NUMBER=752369-081\0MEMORY_DEVICE_8_RANK=2\0MEMORY_DEVICE_8_CONFIGURED_SPEED_MTS=1866\0MEMORY_DEVICE_8_MINIMUM_VOLTAGE=1\0MEMORY_DEVICE_8_MAXIMUM_VOLTAGE=1\0MEMORY_DEVICE_8_CONFIGURED_VOLTAGE=1\0MEMORY_DEVICE_9_TOTAL_WIDTH=72\0MEMORY_DEVICE_9_DATA_WIDTH=64\0MEMORY_DEVICE_9_PRESENT=0\0MEMORY_DEVICE_9_FORM_FACTOR=DIMM\0MEMORY_DEVICE_9_SET=9\0MEMORY_DEVICE_9_LOCATOR=PROC 1 DIMM 10\0MEMORY_DEVICE_9_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_9_TYPE=DDR4\0MEMORY_DEVICE_9_TYPE_DETAIL=Synchronous\0MEMORY_DEVICE_9_MANUFACTURER=UNKNOWN\0MEMORY_DEVICE_9_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_9_ASSET_TAG=Not Specified\0MEMORY_DEVICE_9_PART_NUMBER=NOT AVAILABLE\0MEMORY_DEVICE_10_TOTAL_WIDTH=72\0MEMORY_DEVICE_10_DATA_WIDTH=64\0MEMORY_DEVICE_10_PRESENT=0\0MEMORY_DEVICE_10_FORM_FACTOR=DIMM\0MEMORY_DEVICE_10_SET=10\0MEMORY_DEVICE_10_LOCATOR=PROC 1 DIMM 11\0MEMORY_DEVICE_10_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_10_TYPE=DDR4\0MEMORY_DEVICE_10_TYPE_DETAIL=Synchronous\0MEMORY_DEVICE_10_MANUFACTURER=UNKNOWN\0MEMORY_DEVICE_10_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_10_ASSET_TAG=Not Specified\0MEMORY_DEVICE_10_PART_NUMBER=NOT AVAILABLE\0MEMORY_DEVICE_11_TOTAL_WIDTH=72\0MEMORY_DEVICE_11_DATA_WIDTH=64\0MEMORY_DEVICE_11_SIZE=17179869184\0MEMORY_DEVICE_11_FORM_FACTOR=DIMM\0MEMORY_DEVICE_11_SET=11\0MEMORY_DEVICE_11_LOCATOR=PROC 1 DIMM 12\0MEMORY_DEVICE_11_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_11_TYPE=DDR4\0MEMORY_DEVICE_11_TYPE_DETAIL=Synchronous Registered (Buffered)\0MEMORY_DEVICE_11_SPEED_MTS=2133\0MEMORY_DEVICE_11_MANUFACTURER=HP\0MEMORY_DEVICE_11_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_11_ASSET_TAG=Not Specified\0MEMORY_DEVICE_11_PART_NUMBER=752369-081\0MEMORY_DEVICE_11_RANK=2\0MEMORY_DEVICE_11_CONFIGURED_SPEED_MTS=1866\0MEMORY_DEVICE_11_MINIMUM_VOLTAGE=1\0MEMORY_DEVICE_11_MAXIMUM_VOLTAGE=1\0MEMORY_DEVICE_11_CONFIGURED_VOLTAGE=1\0MEMORY_DEVICE_12_TOTAL_WIDTH=72\0MEMORY_DEVICE_12_DATA_WIDTH=64\0MEMORY_DEVICE_12_PRESENT=0\0MEMORY_DEVICE_12_FORM_FACTOR=DIMM\0MEMORY_DEVICE_12_SET=12\0MEMORY_DEVICE_12_LOCATOR=PROC 2 DIMM 1\0MEMORY_DEVICE_12_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_12_TYPE=DDR4\0MEMORY_DEVICE_12_TYPE_DETAIL=Synchronous\0MEMORY_DEVICE_12_MANUFACTURER=UNKNOWN\0MEMORY_DEVICE_12_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_12_ASSET_TAG=Not Specified\0MEMORY_DEVICE_12_PART_NUMBER=NOT AVAILABLE\0MEMORY_DEVICE_13_TOTAL_WIDTH=72\0MEMORY_DEVICE_13_DATA_WIDTH=64\0MEMORY_DEVICE_13_PRESENT=0\0MEMORY_DEVICE_13_FORM_FACTOR=DIMM\0MEMORY_DEVICE_13_SET=13\0MEMORY_DEVICE_13_LOCATOR=PROC 2 DIMM 2\0MEMORY_DEVICE_13_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_13_TYPE=DDR4\0MEMORY_DEVICE_13_TYPE_DETAIL=Synchronous\0MEMORY_DEVICE_13_MANUFACTURER=UNKNOWN\0MEMORY_DEVICE_13_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_13_ASSET_TAG=Not Specified\0MEMORY_DEVICE_13_PART_NUMBER=NOT AVAILABLE\0MEMORY_DEVICE_14_TOTAL_WIDTH=72\0MEMORY_DEVICE_14_DATA_WIDTH=64\0MEMORY_DEVICE_14_PRESENT=0\0MEMORY_DEVICE_14_FORM_FACTOR=DIMM\0MEMORY_DEVICE_14_SET=14\0MEMORY_DEVICE_14_LOCATOR=PROC 2 DIMM 3\0MEMORY_DEVICE_14_BANK_LOCATOR=Not Specified\0MEMORY_DEVICE_14_TYPE=DDR4\0MEMORY_DEVICE_14_TYPE_DETAIL=Synchronous\0MEMORY_DEVICE_14_MANUFACTURER=UNKNOWN\0MEMORY_DEVICE_14_SERIAL_NUMBER=Not Specified\0MEMORY_DEVICE_14_ASSET_TAG=Not Specified\0MEMORY_DEVICE_14_PART_NUMBER=NOT AVAILABLE\0MEMORY"], iov_len=8192}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, cmsg_data={pid=2243123, uid=0, gid=0}}], msg_controllen=32, msg_flags=MSG_TRUNC}, 0) = 8192
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #24987.

Also, follow-ups for #24982.

### CODE REVIEW

File: src/basic/alloc-util.h [hunk 1]
```diff
@@ -44,6 +44,19 @@ typedef void* (*mfree_func_t)(void *p);
                 (t*) alloca0((sizeof(t)*_n_));                          \
         })
 
+/* Be careful! The lifetime of the allocated buffer depends on the requested size. */
```
Comment (vcaputo) [inline src/basic/alloc-util.h]: 1. wouldn't it be more appropriate to just note that despite potentially being heap-allocated memory, the caller must treat this as on the stack and not hand the pointer out?
2. isn't this naming just leaking implementation detail the caller shouldn't need to be aware of at all?  We don't want the caller to be changing its behavior based on if ALLOCA_MAX was exceeded or not, just hide that detail or this helper isn't particularly helping.
3. shouldn't this really just be replacing newa() altogether?  There isn't any scenario where you want newa() exceeding ALLOCA_MAX, can't this transparently DTRT with a heap allocation safely via the cleanup_free magic?  Why not just rename newa() to _newa() or newa_internal() and make this the public newa() everyone uses?

What am I missing?

Comment (yuwata) [reply src/basic/alloc-util.h]: > 1. wouldn't it be more appropriate to just note that despite potentially being heap-allocated memory, the caller must treat this as on the stack and not hand the pointer out?

If the naming `new_or_newa()` is accepted, then it suggests that the buffer may be heap-allocated. Should I rephrase all common pitfalls about heap-allocated memory??

> 2. isn't this naming just leaking implementation detail the caller shouldn't need to be aware of at all?  We don't want the caller to be changing its behavior based on if ALLOCA_MAX was exceeded or not, just hide that detail or this helper isn't particularly helping.

Suggestion?

> 3. shouldn't this really just be replacing newa() altogether?  There isn't any scenario where you want newa() exceeding ALLOCA_MAX, can't this transparently DTRT with a heap allocation safely via the cleanup_free magic?  Why not just rename newa() to _newa() or newa_internal() and make this the public newa() everyone uses?

One downside of this macro is that the valid scope of the allocated buffer is also depends on the size. So,
```c
void func(void) {
    char *buf;

    if (...) {
        n = ...;
        buf = newa(char, n);
    } else {
        n = ...;
        buf = newa(char, n);
    }

    /* buf is still valid */
}
```
However, this does not work for `new_or_newa()` with a large size. So, replacing `newa()` with the newly introduced one is questionable.

Comment (vcaputo) [reply src/basic/alloc-util.h]: Considering this newa()-misusing code was recently written it seems likely to recur again and again so why not change the calling convention of systemd's newa() helper such that it always accommodates for heap-allocated scenario needs, update all the newa() callers appropriately, and get rid of the existing insufficient newa() public interface?

It just seems silly to me that we have this newa() helper that's only creating potential situations where the allocation is too large for on-stack.  If the author reached for newa() it's implied that the allocation is expected to *usually* be small enough for stack allocation.  But that also implies it's totally acceptable for it to go a little slower in the implicitly exceptional situation that the allocation was large, so change the interface to accommodate heap-allocations should they be necessary.

The only argument I can come up with against this is not wanting to have to check for OOM everywhere newa() is used.

Edit:  It seems silly to me that we have a deliberately fatal *runtime* error in the form of an assert in newa() should the allocation exceed ALLOCA_MAX, when the vast majority of the time the too-large allocation could have been performed successfully on the heap if the code were simply robust enough to do so.  Arguably every time that assert fires in production we probably crashed something unnecessarily.  That code existing at all makes me want to cry.  It should only be acceptable as a static assert in a newa() variant that only accepts compile-time known sizes.  This thing should be able to try use the heap instead of shit the bed IMHO.

Comment (vcaputo) [reply src/basic/alloc-util.h]: Wouldn't something like this be preferable?

https://github.com/systemd/systemd/compare/main...vcaputo:systemd:newa-safe?expand=1

Comment (yuwata) [reply src/basic/alloc-util.h]: Seems not bad. But that is out of scope of this PR. I'd like to do such a change in another (later?) PR.
Could you open a PR? Let's discuss there about the new allocator.

**Comment by cpaelzer** [comment]
Hi @yuwata and thank you for the quick response.
I've checked out your branch, built and ran it against the system/test outlined in #24987
I didn't have the time this morning to go much deeper but hope this helps to make progress on this.

To be on the safe side in my test program I gave it a bigger buffer via `udev_monitor_set_receive_buffer_size(udev_monitor,65536)` but i still found it breaking with -EINVAL on 8192:
```
cmsg_data={pid=2404966, uid=0, gid=0}}], msg_controllen=32, msg_flags=MSG_TRUNC}, 0) = 8192
```

I debugged `device_monitor_receive_device` and no matter if I set it via `udev_monitor_set_receive_buffer_size` or not I'm seeing it to use 12411 there. But then that can't be the reason anyway because for the sake of brute forcing it I've not only set `udev_monitor_set_receive_buffer_size` but also in `device_monitor_receive_device` thrown in `if (n<65536) n=65536;` to no change :-/

I was double checking on the iov used, but that looks sane as well...
Overall:
```
Breakpoint 1, device_monitor_receive_device (m=0x5555555592c0, ret=0x7fffffffe140) at ../src/libsystemd/sd-device/device-monitor.c:483
483	int device_monitor_receive_device(sd_device_monitor *m, sd_device **ret) {
(gdb) n
484	        _cleanup_(sd_device_unrefp) sd_device *device = NULL;
(gdb) 
493	        struct msghdr smsg = {
(gdb) 
505	        bool is_initialized = false;
(gdb) 
508	        assert(m);
(gdb) 
509	        assert(ret);
(gdb) 
511	        n = next_datagram_size_fd(m->sock);
(gdb) 
512	        if (n < 0) {
(gdb) p n
$1 = 12411
(gdb) n
517		if (n<65536) n=65536;
(gdb) n
519	        new_or_newa(message.buf, n);
(gdb) p n
$2 = 65536
(gdb) n
520	        if (!message.buf)
(gdb) n
523	        iov = IOVEC_MAKE(message.buf, n);
(gdb) n
525	        n = recvmsg(m->sock, &smsg, 0);
(gdb) p iov
$3 = {iov_base = 0x7ffffffede70, iov_len = 65536}
```

As I said I didn't have the time to go deeper this morning, but maybe you already see the critical part.
Also is there another place you'd me expect the test program to be changed to manage to get a confirmed good run with your change on the affected system?

File: src/basic/alloc-util.h [hunk 2]
```diff
@@ -44,6 +44,19 @@ typedef void* (*mfree_func_t)(void *p);
...
+#define _new_or_newa(ret, n, buf_free)                                  \
+        _cleanup_free_ typeof(ret) buf_free = NULL;                     \
+        ({                                                              \
+                size_t __n__ = (n);                                     \
+                if (__n__ < ALLOCA_MAX / sizeof(ret[0]) / 2)            \
+                        ret = newa(typeof(ret[0]), __n__);              \
+                else                                                    \
+                        ret = buf_free = new(typeof(ret[0]), __n__);    \
+        })
```
Comment (poettering) [inline src/basic/alloc-util.h]: what about a mechanism that works like this: implement a macro that allows allocating memory for a type x and always allocates an additional alignof(x) bytes extra, and returns the allocated pointer incremented alignof(x) bytes. Then, in the byte immediately before the returned pointer we store whether this is an alloca() or a malloc() allocation. and provide a generic destructor function that either calls malloc() or it does not.

(And that byte could later be used for marking allocated memory for erasing on destruction, or for marking that memory for munmap() to cover for unswappable memory).

This would mean extra memory use will be minimal: if you allocate a string we just allocated a single byte more. and in the worst case if we waste 8 bytes...

Comment (yuwata) [reply src/basic/alloc-util.h]: It sounds something like the suggestion by @vcaputo in the above for me, right?

**Comment by yuwata** [comment]
@cpaelzer I cannot reproduce that.
With the following additional log:
```
git diff
diff --git a/src/libsystemd/sd-device/device-monitor.c b/src/libsystemd/sd-device/device-monitor.c
index ba49afcfd8..e04244f0c2 100644
--- a/src/libsystemd/sd-device/device-monitor.c
+++ b/src/libsystemd/sd-device/device-monitor.c
@@ -514,6 +514,7 @@ int device_monitor_receive_device(sd_device_monitor *m, sd_device **ret) {
                         log_monitor_errno(m, n, "Failed to get the received message size: %m");
                 return n;
         }
+        log_monitor(m, "expected message size: %zi", n);
 
         new_or_newa(message.buf, n);
         if (!message.buf)
@@ -527,6 +528,7 @@ int device_monitor_receive_device(sd_device_monitor *m, sd_device **ret) {
                         log_monitor_errno(m, errno, "Failed to receive message: %m");
                 return -errno;
         }
+        log_monitor(m, "received message size: %zi", n);
 
         if (smsg.msg_flags & MSG_TRUNC)
                 return log_monitor_errno(m, SYNTHETIC_ERRNO(EINVAL), "Received truncated message, ignoring message.");
```
Then, a device with huge number of properties,
```
$ SYSTEMD_LOG_LEVEL=debug build/udevadm monitor
SELinux enabled state cached to: disabled
monitor will print the received events for:
sd-device-monitor(n/a): Unable to get network namespace of udev netlink socket, unable to determine if we are in host netns, ignoring: Operation not permitted
UDEV - the event which udev sends out after rule processing
sd-device-monitor(n/a): Unable to get network namespace of udev netlink socket, unable to determine if we are in host netns, ignoring: Operation not permitted
KERNEL - the kernel uevent

sd-device-monitor(n/a): expected message size: 127
sd-device-monitor(n/a): received message size: 127
KERNEL[409889.000367] add      /devices/virtual/net/hoge (net)
sd-device-monitor(n/a): expected message size: 128
sd-device-monitor(n/a): received message size: 128
KERNEL[409889.000438] add      /devices/virtual/net/hoge/queues/rx-0 (queues)
sd-device-monitor(n/a): expected message size: 128
sd-device-monitor(n/a): received message size: 128
KERNEL[409889.000487] add      /devices/virtual/net/hoge/queues/tx-0 (queues)
sd-device-monitor(n/a): expected message size: 11210
sd-device-monitor(n/a): received message size: 11210
UDEV  [409889.347699] add      /devices/virtual/net/hoge (net)
sd-device-monitor(n/a): expected message size: 180
sd-device-monitor(n/a): received message size: 180
UDEV  [409889.403388] add      /devices/virtual/net/hoge/queues/rx-0 (queues)
sd-device-monitor(n/a): expected message size: 180
sd-device-monitor(n/a): received message size: 180
UDEV  [409889.473623] add      /devices/virtual/net/hoge/queues/tx-0 (queues)
```

**Comment by yuwata** [comment]
@cpaelzer BTW, setting the receive buffer size 65536 sounds too small. We usually set 128M or so.

File: src/basic/alloc-util.h (hunk 1 above)
Comment (vcaputo) [reply src/basic/alloc-util.h]: Feel free to make use of the idea or any of the commits.  I'm currently helping family with urgent home repairs before November arrives, and don't really have enough time/energy to participate here more than sporadically.

I just felt guilty ranting about newa() without showing a reasonable implementation, and it happened to be a bad weather day here.

Also I see @poettering already suggested a more compact implementation, so I'm sure there'd be a bit of iteration from where my proof-of-concept branch is, in terms of both naming things and the technical details.

The only other thing I'd like to mention is in a world where newa() transparently falls back on the heap if over ALLOCA_MAX, ALLOCA_MAX can be substantially smaller than the current 4MiB because you're no longer dodging an assert().  The existing assert() doesn't even account for cumulative newa()s in the same stack frame.  The sd-journal function my branch changed to use newa_safe() is one such example of cumulative newa() use.  Making ALLOCA_MAX much smaller seems like a good idea to me.

**Comment by cpaelzer** [comment]
> Then, a device with huge number of properties,
> 
> ```
> $ SYSTEMD_LOG_LEVEL=debug build/udevadm monitor
> ```

I agree that I can see similar behavior with udevadm monitor from the build systemd:

```
$ sudo SYSTEMD_LOG_LEVEL=debug systemd/build/udevadm monitor
SELinux enabled state cached to: disabled
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

sd-device-monitor(n/a): expected message size: 257
sd-device-monitor(n/a): received message size: 257
KERNEL[6380295.401601] add      /devices/virtual/dmi/id (dmi)
sd-device-monitor(n/a): expected message size: 12411
sd-device-monitor(n/a): received message size: 12411
UDEV  [6380295.411915] add      /devices/virtual/dmi/id (dmi)
```

But udev_monitor_receive_device as used in the test program still gets an EINVAL (even asking for a 128M buffer). But that might be caused by not using the new code all the way. It does link against the new built libudev but I do not have a full system which uses the rebuilt systemd. Hence chances are the test might use old code in some place.

@yuwata  have you run the test program I provided in the bug report?
Did it - for you - return EINVAL before and no more after the fix?

**Comment by yuwata** [comment]
> I now managed to get my test program to really use the new code and can confirm that it works.

Thank you for the confirmation!

Now, I added a test case in our testsuite.

The commits for `new_or_newa()` is dropped tentatively, and will be submitted that in another PR.

PTAL!

**Comment by cpaelzer** [comment]
> Now, I added a test case in our testsuite.
> 
> The commits for `new_or_newa()` is dropped tentatively, and will be submitted that in another PR.

Yep I see the local `buf_alloc` being used for now.

> PTAL!

Fully built the most recent branch head (69363f13) again.
The test program on affected HW works fine with this - the read completes and delivers content.

Thanks @yuwata

**Comment by keszybz** [comment]
LGTM.

jammy-amd64: TEST-29-PORTABLE:                   FAIL     (302 s). Should be unrelated.
