### PR TITLE
kmod-setup: fix loading virtio modules, and load other vsock transport modules

### LINKED ISSUE #40161: systemd-ssh-generator: IOCTL_VM_SOCKETS_GET_LOCAL_CID returned special value (1), ignoring
### systemd version the issue has been seen with

259-1

### Used distribution

Arch Linux

### Linux kernel version used

6.18.1-arch1-2

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

On my Hyper-V machine, AF\_VSOCK CID is `1` which seems to have been ignored since 492ae9ec4eb7fdfe090fba2e59175072bfabf2f5. This socket works fine on systemd 258.2, therefore should not be ignored. Possibly related: #40096

### Unexpected behaviour you saw

systemd-ssh-generator ignores AF\_VSOCK CID `1`.

### Steps to reproduce the problem

Boot a Hyper-V virtual machine with systemd 258.3-1 and 259. On systemd 258.2-2, systemd-ssh-generator works fine and allows me to ssh via the socket from Hyper-V:

```
Try contacting this VM's SSH server via 'ssh vsock%1' from host.
```

Now it no longer shows the output above and does not listen to the vsock at all.

### Additional program output to the terminal or log subsystem illustrating the issue

```console
$ dir=$(mktemp -d)
$ SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/system-generators/systemd-ssh-generator "$dir" "$dir" "$dir"
Found container virtualization none.
Virtualization Hyper-V UEFI Release v4.1 found in DMI (/sys/class/dmi/id/product_version)
UML virtualization not found in /proc/cpuinfo.
Virtualization XEN not found, /proc/xen does not exist
Virtualization found, CPUID=Microsoft Hv
Found VM virtualization microsoft
Local AF_VSOCK CID: 1
IOCTL_VM_SOCKETS_GET_LOCAL_CID returned special value (1), ignoring.
Binding SSH to AF_UNIX socket /run/ssh-unix-local/socket.
→ connect via 'ssh .host' locally
Not running in container, not listening on /run/host/unix-export/ssh
```

### LINKED ISSUE #40503: systemd-ssh-generator does not create the sshd-vsock.socket and service during boot on Fedora 43 VMs
### systemd version the issue has been seen with

systemd-258.3-2.fc43.x86_64

### Used distribution

Fedora 43

### Linux kernel version used

6.18.6-200.fc43.x86_64

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

If I run `systemctl daemon-reload` after the  VM boots the sshd-vsock.socket and service are generated. If I then start the service I can connect to the VM with `ssh vsock/3`.

### Unexpected behaviour you saw

systemd-ssh-generator does not create the sshd-vsock.socket and service during boot on Fedora 43 VMs

### Steps to reproduce the problem

Install a Fedora 43 VM on a Fedora 43 using libvirt / virt-manager, making sure to include a virtio vsock device.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #40161.
Fixes #40503.

### CODE REVIEW

File: src/core/kmod-setup.c [hunk 1]
```diff
@@ -93,6 +89,18 @@ static bool has_virtio_pci(void) {
 static bool in_qemu(void) {
         return IN_SET(detect_vm(), VIRTUALIZATION_KVM, VIRTUALIZATION_QEMU);
 }
+
+static bool may_have_virtio_vsock(void) {
+        return VIRTUALIZATION_IS_VM(detect_vm());
```
Comment (YHNdnzj) [inline src/core/kmod-setup.c]: VIRTUALIZATION_IS_VM seems unnecessary? Plain != _NONE. should do.

Comment (poettering) [reply src/core/kmod-setup.c]: also detect_vm() can return an error in theory. hence, i would do:

```c
return detect_vm() > 0;
```

returning on the fact that NONE is 0

**Comment by yuwata** [comment]
BTW, `has_virtio_console()` and `has_virtiofs()` seem to have the same issue.
Let's also fix them later if this works.

File: src/core/kmod-setup.c [hunk 2]
```diff
@@ -74,25 +74,18 @@ static bool has_virtio_rng(void) {
...
-static bool has_virtiofs(void) {
-        return has_virtio_feature("virtiofs", STRV_MAKE("virtio:d0000001Av"));
-}
-
 static bool has_virtio_pci(void) {
         return has_virtio_feature("virtio-pci", STRV_MAKE("pci:v00001AF4d"));
 }
 
+static bool may_have_virtio(void) {
+        return detect_vm() > 0;
```
Comment (poettering) [inline src/core/kmod-setup.c]: that's such a generic check...

Comment (poettering) [reply src/core/kmod-setup.c]: and does this even fix things? i mean, if the virtio bus doesn't show up early enough, then the kmods for it might not be able to attach to it either that early, so is this actually fixing the issue?

Comment (yuwata) [reply src/core/kmod-setup.c]: Not sure, but force-pushed with a narrower check.

File: src/core/kmod-setup.c [hunk 3]
```diff
@@ -74,22 +74,15 @@ static bool has_virtio_rng(void) {
...
-}
-
 static bool has_virtio_pci(void) {
         return has_virtio_feature("virtio-pci", STRV_MAKE("pci:v00001AF4d"));
 }
 
+static bool may_have_virtio(void) {
+        /* FIXME: strictly speaking, other virtio features, e.g. vsock, are independent of the virtio PCI device. */
+        return has_virtio_pci();
+}
```
Comment (keszybz) [inline src/core/kmod-setup.c:84]: I don't like the idea of merging a solution with a FIXME. Because it seems likely that the issue will not be fixed for some users, e.g. if they try to build a VM without PCI.

Can we just use `detect_vm() != VIRTUALIZATION_NONE` as the condition for all virtio modules? The cost of a failed lookup is negligible, and the cost of loading an unnecessary module is also not that big.

Comment (yuwata) [reply src/core/kmod-setup.c:84]: At least `detect_vm() != VIRTUALIZATION_NONE` disturbs hyperv systems, as loading multiple vsock transport driver causes a conflict.

Comment (yuwata) [reply src/core/kmod-setup.c:84]: See https://github.com/systemd/systemd/issues/40161#issuecomment-3851004460, which is the report tested with the exactly the same condition you suggest.

**Comment by poettering** [comment]
my question still stands:

> and does this even fix things? i mean, if the virtio bus doesn't show up early enough, then the kmods for it might not be able to attach to it either that early, so is this actually fixing the issue?

i am not sure this fixes things properly, it might just shorten the window.

if virtio bus probing is async, then we'll always have a problem, we need to wait for that stuff to complete.

**Comment by poettering** [comment]
hmm, i wonder if those pci devices show up in smbios tables, if so we could look there for detection

File: src/core/kmod-setup.c [hunk 4]
```diff
@@ -117,18 +110,18 @@ int kmod_setup(void) {
...
 
                 /* We can't wait for specific virtiofs tags to show up as device nodes so we have to load the
                  * virtiofs and virtio_pci modules early to make sure the virtiofs tags are found when
                  * sysroot.mount is started.
                  *
                  * TODO: Remove these again once https://gitlab.com/virtio-fs/virtiofsd/-/issues/128 is
                  * resolved and the kernel fix is widely available. */
-                { "virtiofs",                   "/sys/module/virtiofs",      false, false, has_virtiofs       },
+                { "virtiofs",                   "/sys/module/virtiofs",      false, false, may_have_virtio    },
                 { "virtio_pci",                 "/sys/module/virtio_pci",    false, false, has_virtio_pci     },
```
Comment (poettering) [inline src/core/kmod-setup.c:135]: i wonder if we should switch order here, to ensure virtio_pci is loaded first?

File: src/core/kmod-setup.c (hunk 3 above)
Comment (keszybz) [reply src/core/kmod-setup.c:84]: OK.

File: src/core/kmod-setup.c (hunk 4 above)
Comment (keszybz) [reply src/core/kmod-setup.c:135]: This shouldn't matter. `may_have_virtio` and `has_virtio_pci` are effectively the exact same check.

**Comment by keszybz** [comment]
> hmm, i wonder if those pci devices show up in smbios tables, if so we could look there for detection

I checked with `dmidecode` on a VM with a vsock enabled, and dmidecode doesn't say anything about it.
