### PR TITLE
hashmap: make hashmap_put_strdup() take hash_ops

### LINKED ISSUE #17259: regression in enumerator match_property OR semantic
`udevadm trigger` manpage mentions that specifying multiple property matches results in an OR semantic.
> -p, --property-match=PROPERTY=VALUE
> ... When this option is specified more than once, then each matching result is ORed

Although not explicitly documented in the manpages the same was true for eg `udev_enumerate_add_match_property`.

systemd 245 and earlier allowed specifying the same property name multiple times with different values. 

This no longer works with systemd 246, specifying the same property name more than once results in an error (EEXIST).

**systemd version the issue has been seen with**
 >systemd 246

also current master 1b97c5cba58fdd1138e7622d7edef9a48309b0e2 shows that issue

**Used distribution**
 > LibreELEC

**Linux kernel version used** (`uname -a`)
 >5.9.0-rc7

**CPU architecture issue was seen on**
 > ARM

**Expected behaviour you didn't see**

Property matching should provide OR semantic, eg when using the following command to match both disks and partitions with systemd 245:
```
# udevadm trigger -v -n -y 'sd*' -p DEVTYPE=disk -p DEVTYPE=partition
/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/host0/target0:0:0/0:0:0:/block/sda
/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/host0/target0:0:0/0:0:0:/block/sda/sda1
```

**Unexpected behaviour you saw**
Property matching fails if the same property name is specified more than once
```
# udevadm trigger -v -n -y 'sd*' -p DEVTYPE=disk -p DEVTYPE=partition
Failed to add property match 'DEVTYPE=partition': File exists
```

**Steps to reproduce the problem**
Either use the udevadm trigger command as above (a simple `udevadm trigger -p FOO=bar -p FOO=baz` will do) or call `udev_enumerate_add_match_property` or `sd_device_enumerator_add_match_property` another time with the same property name.

**Further information**
git bisect led to commit eb1c1dc029c91750e6255c3fd844b4f4bf238fab as the first bad commit which was added via #15635

### PR DESCRIPTION
**Pull request by yuwata**
This fixes the issue caused by eb1c1dc029c91750e6255c3fd844b4f4bf238fab.

Fixes #17259.

### CODE REVIEW

**Comment by keszybz** [comment]
Thanks for the quick patch. But I can't say I like the approach. For me, if we use `_put_strdup` to insert items in the hashmap, we should treat the hashmap as a black box that does allocation and freeing on our behalf. Thus explicitly specifying `hashmap_ops_free_free` as an argument is a step backwards. Instead, the one place which wants to do freeing on its own should be adjusted to follow the common pattern and not do any explicit freeing.

**Comment by yuwata** [comment]
@keszybz Thank you for you comment. Force-pushed v2. How about this one? PTAL.

**Comment by HiassofT** [comment]
@yuwata thanks a lot for looking into this! I did a few tests with v1 and then v2 and it looks good so far

File: src/basic/hashmap.c [hunk 1]
```diff
@@ -1794,10 +1794,10 @@ int set_consume(Set *s, void *value) {
         return r;
 }
 
-int _hashmap_put_strdup(Hashmap **h, const char *k, const char *v  HASHMAP_DEBUG_PARAMS) {
+int _hashmap_put_strdup_full(Hashmap **h, bool use_string_hash, const char *k, const char *v  HASHMAP_DEBUG_PARAMS) {
         int r;
 
-        r = _hashmap_ensure_allocated(h, &string_hash_ops_free_free  HASHMAP_DEBUG_PASS_ARGS);
+        r = _hashmap_ensure_allocated(h, use_string_hash ? &string_hash_ops_free_free : &trivial_hash_ops_free_free  HASHMAP_DEBUG_PASS_ARGS);
```
Comment (poettering) [inline src/basic/hashmap.c]: hmm, instead of taking a bool argument here and converting that in one of two hash ops structs, maybe just take a hash opt ptr right-away as argument?

That way it woud be more generic I figure, and probably even more descriptive since a standalone "false" or "true" as one of many params in a function call is always a bit opaque, but a parameter such as `&trivial_hash_ops_free_free` quite a bit more explanatory

File: src/libsystemd/sd-device/device-enumerator.c [hunk 2]
```diff
@@ -118,7 +118,7 @@ _public_ int sd_device_enumerator_add_match_sysattr(sd_device_enumerator *enumer
         else
                 hashmap = &enumerator->nomatch_sysattr;
 
-        r = hashmap_put_strdup(hashmap, sysattr, value);
+        r = hashmap_put_strdup_full(hashmap, false, sysattr, value);
```
Comment (keszybz) [inline src/libsystemd/sd-device/device-enumerator.c]: I don't get this: what is so special about this call site that we don't want to hash the strings?

File: src/basic/hashmap.c (hunk 1 above)
Comment (yuwata) [reply src/basic/hashmap.c]: Thank you for the advice. Updated.

File: src/libsystemd/sd-device/device-enumerator.c (hunk 2 above)
Comment (yuwata) [reply src/libsystemd/sd-device/device-enumerator.c]: Before the offending commit, multiple sysattr or property values can be specified as we used `trivial_hash_ops`. With `string_hash_ops` we cannot set multiple values for the same key.

Now the commit message also mentions that.

**Comment by yuwata** [comment]
@poettering and @keszybz Thank you for the comments. I force-pushed a revised version. PTAL.

**Comment by HiassofT** [comment]
thanks again, quick tests with v3 look good, too!
