### PR TITLE
networkd: DHCPv6 client allow to configure Rapid Commit

### LINKED ISSUE #5845: [RFE] Option to enable/disable rapid-commit for systemd-networkd's DHCPv6 client
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 233

### Used distribution

> coreos 1395.0.0

### Feature: Expected behaviour

> Add an option to enable/disable rapid-commit for systemd-networkd's DHCPv6 client

### Reason
I tried IPv6 support in Amazon EC2 VPC. Amazon EC2 VPC uses RA and DHCPv6 for IPv6 addressing.
On boot, EC2 instance receives an RA message with manged flag, then it sends a DHCPv6 solicit message to ff02::1:2. DHCPv6 server in VPC is expected to respond to solicit massages.

In case of dhclient 4.3.5, everything works well. But in case of systemd-networkd (and dhcpcd 6.11.5), it seems that DHCPv6 server ignores solicit messages from hosts (that is, no DHCPv6 advertise message appears in packets captured by tcpdump)

DHCPv6 solicit messages sent by systemd-networkd and dhcpcd have `rapid-commit` option. On the other hand, those sent by dhclient have no rapid-commit option. The presence of that option is the most notable difference I've found in the solicit messages from dhclient and the others.

According to https://tools.ietf.org/html/rfc3315#section-17.2.1, I guess DHCPv6 server in VPC is not RFC compliant. I posted this issue to AWS forum (https://forums.aws.amazon.com/thread.jspa?messageID=772808&tstart=0) though, but no reply.

Yes, this is amazon's issue. But, I want to ask systemd-networkd to have an option to enable/disable `rapid-commit`.

### PR DESCRIPTION
**Pull request by ssahani**
The DHCPv6 client can obtain configuration parameters
from a DHCPv6 server through a rapid two-message exchange
(solicit and reply). When the rapid commit option is
enabled by both the DHCPv6 client and the DHCPv6 server,
the two-message exchange is used, rather than the default
four-method exchange (solicit, advertise, request, and reply).
The two-message exchange provides faster client configuration
and is beneficial in environments in which networks are under a heavy load.

Closes #5845

### CODE REVIEW

**Comment by fsateler** [comment]
Is there any drawback to enabling this option? If so, I think this should be mentioned in the manpage. If not, maybe it should be enabled by default?

File: src/network/networkd-dhcp6.c [hunk 1]
```diff
@@ -251,6 +252,12 @@ int dhcp6_configure(Link *link) {
         if (r < 0)
                 goto error;
 
+        if (link->network->rapid_commit) {
+                r = sd_dhcp6_client_set_request_option(client, SD_DHCP6_OPTION_RAPID_COMMIT);
+                if (r < 0)
+                        goto error;
+        }
```
Comment (poettering) [inline src/network/networkd-dhcp6.c:521]: hmm, is it really sufficient to just request this option? I mean, why don't we have to make changes to the state engine of the dhcp client, too?

I didn't read up on dhcp rapid commit, but it appears to be something that requires more client side changes than just requesting it.

File: man/systemd.network.xml [hunk 2]
```diff
@@ -1234,6 +1234,18 @@
...
         </varlistentry>
+
+        <varlistentry>
+          <term><varname>RapidCommit=</varname></term>
+          <listitem>
+            <para>A boolean. The DHCPv6 client can obtain configuration parameters from a DHCPv6 server through a
+            rapid two-message exchange (solicit and reply). When the rapid commit option is enabled by both the
+            DHCPv6 client and the DHCPv6 server, the two-message exchange is used, rather than the default four-method
+            exchange (solicit, advertise, request, and reply). The two-message exchange provides faster client configuration
+            and is beneficial in environments in which networks are under a heavy load. Defaults to false.</para>
```
Comment (poettering) [inline man/systemd.network.xml]: could you add a reference to RFC 4039?

Comment (ssahani) [reply man/systemd.network.xml]: OK

File: src/network/networkd-dhcp6.c (hunk 1 above)
Comment (ssahani) [reply src/network/networkd-dhcp6.c:521]: I think the client part is handled as per https://tools.ietf.org/html/rfc3315#section-17.1.1  `DHCP6_STATE_SOLICITATION` in client_receive_advertise.

Comment (poettering) [reply src/network/networkd-dhcp6.c:521]: so, what are you saying? we already implement that part correctly?

Comment (ssahani) [reply src/network/networkd-dhcp6.c:521]: Well I think so. Since enabling this in the request we can see the change in packet exchange.
I have attached the screenshorts.


screenshot from 2017-11-27 17-51-19

with rapid commit.

Comment (ssahani) [reply src/network/networkd-dhcp6.c:521]: screenshot from 2017-11-27 17-48-46
Without rapid commit.

**Comment by yuwata** [comment]
lgtm.

**Comment by yuwata** [comment]
@ssahani What do you think about @fsateler 's point?

**Comment by ssahani** [comment]
yes we can make that default to be true. Updated.
