### PR TITLE
resolved: make link-local addresses relevant in unicast

### LINKED ISSUE #37777: systemd-resolved refuses to use ipv6 link-local resolver
### systemd version the issue has been seen with

257.6-1

### Used distribution

Arch Linux

### Linux kernel version used

6.14.10-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

resolvectl

### Expected behaviour you didn't see

I've configured a site-to-site wireguard tunnel and I'm using ipv6 link-local addresses for communication on it. I tried to set up DNS with systemd-resolved using those same addresses, but it insists that `Current Scopes: none`.

Inb4: Yes, I've included the interface index and `dig @fe80::2ef2:607b:e530:a943%wg example.com` works properly.

### Unexpected behaviour you saw

I expected to see `Current Scopes: DNS`, since I configured DNS. But systemd-resolved refuses to use it for some reason.

### Steps to reproduce the problem

- Write a `/etc/systemd/networkd/90-wg.netdev` file to create the wireguard tunnel.
- Configure the created interface:
```ini
# /etc/systemd/networkd/90-wg.network
[Match]
Name=wg

[Network]
Address=fe80::233d:efbb:e6b3:3e15/64
DNS=fe80::2ef2:607b:e530:a943%wg
Domains=example.com
```
- Run `networkctl reload`
- Check `Current Scopes`:
```sh
$ resolvectl status wg
Link 4 (wg)
    Current Scopes: none # Why is this none???
         Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
       DNS Servers: fe80::2ef2:607b:e530:a943
        DNS Domain: example.com
     Default Route: no
```

The interface index is not displayed in status for some reason, but it seems systemd-resolved is aware of it:
```sh
$ resolvectl show-server-state
# ...
Server: fe80::2ef2:607b:e530:a943%4
                              Type: link
                         Interface: wg
                   Interface Index: 4
            Verified feature level: n/a
            Possible feature level: TLS+EDNS0+DO
                       DNSSEC Mode: no
                  DNSSEC Supported: yes
Maximum UDP fragment size received: 512
               Failed UDP attempts: 0
               Failed TCP attempts: 0
             Seen truncated packet: no
          Seen OPT RR getting lost: no
             Seen RRSIG RR missing: no
               Seen invalid packet: no
            Server dropped DO flag: no
```

### PR DESCRIPTION
**Pull request by gtsiam**
This comes up in ptp links where we don't really want or need to assign routable ips to each of the routers if they're doing dns. Or in other words: Link local addresses are valid source addresses too.

---

This is an MVP fix, factoring compatibility concerns in.

IMO, everything to do with "link address relevant" should be nuked; it is trying to be too smart for its own good. Even with this change, it is trivially easy to break.

The linux routing table is a complex beast. Even pretending nftables, ip rules and bpf don't exist. The most we should be doing is trying and seeing what works, looking at link state up/down and maybe multicast/broadcast support for mdns/llmnr. Anything more, and the chances of getting it wrong increase exponentially.

Fixes #37777.

### CODE REVIEW

**Comment by gtsiam** [comment]
None of the test failures look to have anything to do with this PR. Maybe ubuntu/debian changed something?

**Comment by poettering** [comment]
I am not sure how i feel about this one. The goal here is to reduce the number of interfaces resolved deals with. 

I find it a pretty exotic case to want to talk to link-local DNS servers. And it's not going to be pain just here but for the synthesized resolv.conf files we provide too (because they'd need to carry an ifindex/scope).

I might be to OK make this a somewhat "hidden" and opt-in feature. i.e. check some boolean env var for this. env vars is how we make certain features available we don't want to fully advertise because we consider them problematic. For example SYSTEMD_RESOLVED_SYNTHESIZE_HOSTNAME exists like this. They are documented in docs/ENVIRONMENT.md to keep them out of sight in the usual docs.

**Comment by poettering** [comment]
or in other words, introduce a check against some new env var, i.e. `secure_getenv_bool("SYSTEMD_RESOLVED_RELAX_RELEVANT_NETIF")` or so, and we can merge this.

**Comment by gtsiam** [comment]
Hmmm... I really don't like the idea of adding a hidden option here. What I'm trying to do _should_ work. If I define a `DNS=...` entry, I expect it to be used, not silently ignored. A hidden environment variable that tells resolved to not be broken isn't really helping here.

I consider these checks a huge mistake, which is why I was trying to relax them. Maybe they're not completely pointless for mDNS/LLMNR, but for unicast dns they make absolutely no sense. But if you insist on keeping them...

The other way I was going to implement this was to consider ipv6 link-local relevant on interfaces with configured link-local dns going out of the same interface. I dropped this as it wouldn't support link-local dns across interfaces, which again _should_ work. But at least this approach would fix the part of the bug I care about.

Would you be willing to merge an implementation of that?

Otherwise, a global option in `/etc/systemd/resolved.conf` that turns off these checks, at least for unicast dns would be even better.

**Comment by poettering** [comment]
> Hmmm... I really don't like the idea of adding a hidden option here. What I'm trying to do _should_ work. If I define a `DNS=...` entry, I expect it to be used, not silently ignored. A hidden environment variable that tells resolved to not be broken isn't really helping here.

So hmm, is your DNS server actually a link-local one too? It is, right? If so, what about this: if we see that at least one link-local DNS server is configured for an interface, we'll consider the interface already relevant if it just has a link-local IP address assigned? That should make things just work for you, no?

**Comment by gtsiam** [comment]
> So hmm, is your DNS server actually a link-local one too?

It's on a ptp wireguard link. I'm using ospf to exchange routes, so I have to configure a link-local address anyway. Being able to just do link-local dns makes configuration easier on my end.

> If so, what about this: [...]

Yeah, pretty much what I was trying to describe above. It will have to do, so I'll get to it.

File: src/resolve/resolved-link.c [hunk 1]
```diff
@@ -700,13 +709,30 @@ bool link_relevant(Link *l, int family, bool local_multicast) {
...
         LIST_FOREACH(addresses, a, l->addresses)
-                if ((family == AF_UNSPEC || a->family == family) && link_address_relevant(a, local_multicast))
+                if ((family == AF_UNSPEC || a->family == family) &&
+                    link_address_relevant(a, allow_link_local))
                         return true;
 
         return false;
 }
 
+bool link_local_dns(Link *l, int family) {
```
Comment (poettering) [inline src/resolve/resolved-link.c]: maybe rename `link_has_link_local_dns()`?

File: src/resolve/resolved-link.c [hunk 2]
```diff
@@ -700,13 +709,30 @@ bool link_relevant(Link *l, int family, bool local_multicast) {
...
+
+        /* Check if the link has a link-local dns server for the specified family */
+
+        LIST_FOREACH(servers, s, l->dns_servers) {
+                if ((family == AF_UNSPEC || s->family == family) &&
+                    in_addr_is_link_local(s->family, &s->address)) {
+                        return true;
+                }
+        }
```
Comment (poettering) [inline src/resolve/resolved-link.c]: drop the {}, we generally don't place them if we don't have to.

File: src/resolve/resolved-link.c (hunk 1 above)
Comment (gtsiam) [reply src/resolve/resolved-link.c]: yeah, why not

File: src/resolve/resolved-link.c (hunk 2 above)
Comment (gtsiam) [reply src/resolve/resolved-link.c]: Oh, gotcha

**Comment by poettering** [comment]
looks good, just some coding style nitpicks. if you fix that looks ok to merge. but please drop the draft state, so that CI fully can pass.

**Comment by gtsiam** [comment]
Thanks - I'll fix them in a bit.

Though there's a bug where the DNS scope doesn't seem to come up on boot. `networkctl reload` after boot brings it up, so something to do with load order. I'm investigating now, that's why I marked it as draft.

**Comment by poettering** [comment]
ah right, if dns is configured after the interface shows up first, we need to recheck relevance now, since it now depends on the DNS server data too, not just on rtnetlink. i.e. bus_link_method_set_dns_servers_internal() needs to call link_allocate_scopes() too now.

**Comment by gtsiam** [comment]
Oh - figured it out: It can't parse named ifindex in the .network file because technically the interface doesn't exist. I can just not put an ifindex there anyway. If I understand the code, I think it pretty much always ignores the ifindex anyway.

**Comment by gtsiam** [comment]
> bus_link_method_set_dns_servers_internal() needs to call link_allocate_scopes() too now.

~~That does sound right though. Something seems to trigger it anyway, but I'll add the call to be sure.~~

It calls it already, it was just ifindex parsing then. This is just a minor inconvenience though, so I'm happy to just live with it for now. ifindex is effectively ignored anyway.

File: src/resolve/resolved-link.c [hunk 3]
```diff
@@ -700,9 +709,25 @@ bool link_relevant(Link *l, int family, bool local_multicast) {
...
         LIST_FOREACH(addresses, a, l->addresses)
-                if ((family == AF_UNSPEC || a->family == family) && link_address_relevant(a, local_multicast))
+                if ((family == AF_UNSPEC || a->family == family) &&
+                    link_address_relevant(a, allow_link_local))
+                        return true;
+
+        return false;
+}
+
+bool link_has_link_local_dns(Link *l, int family) {
```
Comment (yuwata) [inline src/resolve/resolved-link.c]: This is only used in this source file. Please move this above `link_relevant()` and make it `static`.

File: src/resolve/resolved-link.c [hunk 4]
```diff
@@ -700,9 +709,25 @@ bool link_relevant(Link *l, int family, bool local_multicast) {
...
+
+        /* Check if the link has a link-local dns server for the specified family */
+
+        LIST_FOREACH(servers, s, l->dns_servers) {
```
Comment (yuwata) [inline src/resolve/resolved-link.c]: Unnecessary `{}`

File: src/resolve/resolved-link.c [hunk 5]
```diff
@@ -700,9 +709,25 @@ bool link_relevant(Link *l, int family, bool local_multicast) {
...
+                if ((family == AF_UNSPEC || s->family == family) &&
+                    in_addr_is_link_local(s->family, &s->address))
```
Comment (yuwata) [inline src/resolve/resolved-link.c]: Not a matter, but we allow ~109ch per line. Maybe not necessary to break the line?

File: src/resolve/resolved-link.c [hunk 6]
```diff
@@ -700,9 +709,25 @@ bool link_relevant(Link *l, int family, bool local_multicast) {
             !IN_SET(l->networkd_operstate, LINK_OPERSTATE_DEGRADED_CARRIER, LINK_OPERSTATE_DEGRADED, LINK_OPERSTATE_ROUTABLE))
                 return false;
 
+        allow_link_local = local_multicast || link_has_link_local_dns(l, family);
+
         LIST_FOREACH(addresses, a, l->addresses)
-                if ((family == AF_UNSPEC || a->family == family) && link_address_relevant(a, local_multicast))
+                if ((family == AF_UNSPEC || a->family == family) &&
+                    link_address_relevant(a, allow_link_local))
```
Comment (yuwata) [inline src/resolve/resolved-link.c:728]: Also here. I do not think it is necessary to break line. Though, that's really not a matter.

File: src/resolve/resolved-link.c (hunk 5 above)
Comment (gtsiam) [reply src/resolve/resolved-link.c]: Didn't know you went up to 109 (weird limit)?
Still, it goes to 115 if I don't break, so I'll leave it.

File: src/resolve/resolved-link.c (hunk 6 above)
Comment (gtsiam) [reply src/resolve/resolved-link.c:728]: This goes to 112 if I don't break.

File: src/resolve/resolved-link.c (hunk 4 above)
Comment (gtsiam) [reply src/resolve/resolved-link.c]: Removed, pushing in a bit. So many CI minutes.

File: src/resolve/resolved-link.c (hunk 3 above)
Comment (gtsiam) [reply src/resolve/resolved-link.c]: done.

File: src/resolve/resolved-link.c (hunk 5 above)
Comment (yuwata) [reply src/resolve/resolved-link.c]: I do not know where the weird number came from. But docs/CODING_STYLE.md says so.
It is totally OK to leave that.

**Review by yuwata — APPROVED** [review]
LGTM.

File: src/resolve/resolved-link.c [hunk 7]
```diff
@@ -674,14 +674,35 @@ int link_update(Link *l) {
         return 0;
 }
 
+static bool link_has_link_local_dns(Link *l, int family) {
+
+        /* Check if the link has a link-local dns server for the specified family */
+
+        LIST_FOREACH(servers, s, l->dns_servers)
```
Comment (yuwata) [inline src/resolve/resolved-link.c:681]: Hmm, bit late, but how about the global dns servers with interface specifier?

Comment (gtsiam) [reply src/resolve/resolved-link.c:681]: I don't think this is worth supporting with the address checks.

I've seen ipv6 link-local dns on a regular basis from consumer routers (which often advertise it through RAs). Not sure were global link-local dns would come into play.

If someone tries to use link-local dns in resolv.conf, it would probably race with interface creation, making addresses hard to parse (since we can't convert the interface name to an index on startup)

We would also have to check interface indices. Here we can get away with not doing it since ifindex is effectively ignored on link dns, etc etc. But with global dns it becomes too complicated for no real benefit, fast.

The only viable way to do this, in my view, is to drop the pointless address checks and delay link-local address interface resolution, but that's both quite a bit of work and not up to me.

**Comment by poettering** [comment]
> Oh - figured it out: It can't parse named ifindex in the .network file because technically the interface doesn't exist. I can just not put an ifindex there anyway. If I understand the code, I think it pretty much always ignores the ifindex anyway.

So, the ifindex is kinda redundant in this case anyway: it's pretty much a broken config to configure a link-local DNS server with ifindex X on an interface Y, unless X == Y... Hence, if a link-local server is specified, we can simply imply the ifindex to be the one of the interface this is associated with.

File: src/resolve/resolved-link.c (hunk 7 above)
Comment (poettering) [reply src/resolve/resolved-link.c:681]: yeah, i'd ignore global dns servers with scope. probably ignore it for good, but definitely for now.

**Comment by poettering** [comment]
BTW, if you work with link-local DNS, maybe you want to address prep a fix for #37214, too?

should be kinda simple: just fix resolvectl to suffix all DNS server addresses from the link-local IP range with the ifname they are configured on.

**Comment by gtsiam** [comment]
> if a link-local server is specified, we can simply imply the ifindex to be the one of the interface

This is effectively already what's happening. In fact, even if you specify a different ifindex on link dns, resolved [just ignores](https://github.com/systemd/systemd/blob/aeac400d1b6d7b922c379cb390419ea4c82e9417/src/resolve/resolved-dns-server.c#L699-L701) it and uses the interface's ifindex anyway.

> maybe you want to address prep a fix for https://github.com/systemd/systemd/issues/37214, too?

Yeah, I'll take a look in a second pr, why not.
