### PR TITLE
nspawn: replace strextend_with_separator() -> strextendf_with_separator()

### LINKED ISSUE #15822: systemd-nspawn incorrectly parsed mountpoints when SELinux options -L or -Z containing commas
**systemd version the issue has been seen with**
> systemd 245 (v245.4-1.fc32)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

**Used distribution**
 > Fedora 32 x86_64

**Expected behaviour you didn't see**
 > systemd-nspawn handles SELinux labels with commas

**Unexpected behaviour you saw**
 > The comma seems to be parsed as a separate mountpoint option rather than one string to be set as something like `"mode=1777,uid=277413888,gid=277413888,context="system_u:object_r:systemd_nspawn_file_t:s0:c77,c78""`

> SYSTEMD_LOG_LEVEL=debug /usr/bin/systemd-nspawn --boot --link-journal=try-guest --settings=override --machine=fedora -L system_u:object_r:systemd_nspawn_file_t:s0:c77,c78 -Z system_u:system_r:systemd_nspawn_t:s0:c77,c78
Setting RLIMIT_CPU to infinity.
Setting RLIMIT_FSIZE to infinity.
Setting RLIMIT_DATA to infinity.
Setting RLIMIT_STACK to 8388608:infinity.
Setting RLIMIT_CORE to 0:infinity.
Setting RLIMIT_RSS to infinity.
Setting RLIMIT_NPROC to 127864.
Setting RLIMIT_NOFILE to 1024:4096.
Setting RLIMIT_MEMLOCK to 65536.
Setting RLIMIT_AS to infinity.
Setting RLIMIT_LOCKS to infinity.
Setting RLIMIT_SIGPENDING to 127864.
Setting RLIMIT_MSGQUEUE to 819200.
Setting RLIMIT_NICE to 0.
Setting RLIMIT_RTPRIO to 0.
Setting RLIMIT_RTTIME to infinity.
Settings are trusted: yes
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Spawning container fedora on /var/lib/machines/fedora.
Press ^] three times within 1s to kill container.
Outer child is initializing.
Mounting / (MS_REC|MS_SLAVE "")...
Selected user namespace base 277413888 and range 65536.
Bind-mounting /var/lib/machines/fedora on /var/lib/machines/fedora (MS_BIND|MS_REC "")...
Found libsystemd shared at "/var/lib/machines/fedora/lib/systemd/libsystemd-shared-245.so", version 245 (OK).
Using unified hierarchy for container.
Mounting /var/lib/machines/fedora (MS_REC|MS_SHARED "")...
Root directory of image is already owned by the right UID/GID range, skipping recursive chown operation.
Mounting tmpfs on /var/lib/machines/fedora/tmp (MS_NOSUID|MS_NODEV|MS_STRICTATIME "mode=1777,uid=277413888,gid=277413888,context=system_u:object_r:systemd_nspawn_file_t:s0:c77,c78")...
Failed to mount tmpfs (type tmpfs) on /var/lib/machines/fedora/tmp (MS_NOSUID|MS_NODEV|MS_STRICTATIME "mode=1777,uid=277413888,gid=277413888,context=system_u:object_r:systemd_nspawn_file_t:s0:c77,c78"): Invalid argument
(sd-namespace) failed with exit status 1.

**Steps to reproduce the problem**
```
SYSTEMD_LOG_LEVEL=debug /usr/bin/systemd-nspawn --boot --link-journal=try-guest --settings=override --machine=fedora -L system_u:object_r:systemd_nspawn_file_t:s0:c77,c78 -Z system_u:system_r:systemd_nspawn_t:s0:c77,c78
```

The same occurs when using these options in a systemd-nspawn@.service unit.  Replacing the `,` with `.` works, but creates inclusive SELinux category ranges, rather than groups, reducing the number of SELinux separated containers that can be run.

It should also be noted that using `.` in the command line or nspawn template unit file results in the following (mounted with commas) in the machine:
```
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,context="system_u:object_r:systemd_nspawn_file_t:s0:c77,c78",uid=277413888,gid=277413888)
```

### LINKED ISSUE #19976: systemd-nspawn failed to mount tmpfs
**systemd version the issue has been seen with**
 > 249 rc1

**Used distribution**
 > Fedora Rawhide

**Linux kernel version used** (`uname -a`)

 > 5.12.12-300.fc34.x86_64

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > a running nspawn container

**Unexpected behaviour you saw**
 > 
```
Jun 20 10:31:01 brutus systemd[1]: Failed to start Container mycontainer.
Jun 20 10:31:01 brutus systemd[1]: systemd-nspawn@mycontainer.service: Failed with result 'exit-code'.
Jun 20 10:31:01 brutus systemd[1]: systemd-nspawn@mycontainer.service: Main process exited, code=exited, status=1/FAILURE
Jun 20 10:31:01 brutus systemd-nspawn[3786]: Failed to mount tmpfs (type tmpfs) on /var/lib/machines/mycontainer/tmp (2|4|(1<<24) "mode=1777,size=10%,nr_inodes=400k,uid=496107520,gid=496107520,context=,sys.id:sys.role:systemd.nspawn.container.fs:s0,"): Invalid argument
Jun 20 10:31:01 brutus systemd[1]: Starting Container mycontainer..
```
**Steps to reproduce the problem**
 > The "unexpected behavior i saw above" say's enough

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug introduced by cfea7618f28562c053a1ee194108feaa502081ff.

Before this commit:
mode=1777,size=10%,nr_inodes=400k,uid=496107520,gid=496107520,context=,sys.id:sys.role:systemd.nspawn.container.fs:s0,
After this commit:
mode=1777,size=10%,nr_inodes=400k,uid=496107520,gid=496107520,context=sys.id:sys.role:systemd.nspawn.container.fs:s0

Fixes #19976.
Also fixes #15822.

### CODE REVIEW

**Review by bluca — APPROVED** [review]
LGTM

**Comment by mrc0mmand** [comment]
While trying to reproduce this, I noticed that the mount flags are now printed in a "weird" way:

```
21:16:35 Failed to mount tmpfs (type tmpfs) on /var/tmp/systemd-test-TEST-01-BASIC/root/tmp (2|4|(1<<24) "mode=1777,size=10%,nr_inodes=400k,uid=0,gid=0,context=system_u:object_r:svirt_sandbox_file_t:s0:c0,c1"): Invalid argument
```

Shouldn't the `2|4|(1<<24) ` be `MS_NOSUID|MS_NODEV|MS_STRICTATIME` instead?

This is not caused by this PR, it's been happening for a while according to various CI logs, e.g.:

```
Mounting /dev (16384|(1<<19) "")...
Mounting ramfs (ramfs) on /dev/shm (2|4|8 "mode=0700")...
Couldn't read inherited credential 'passwd.hashed-password.root', skipping: No such file or directory
Couldn't read inherited credential 'passwd.plaintext-password.root', skipping: No such file or directory
Couldn't read inherited credential 'passwd.shell.root', skipping: No such file or directory
Remounting /dev/shm (1|2|4|8|32|4096 "")...
```

**Comment by yuwata** [comment]
@mrc0mmand One more commit is added to show mount flag names.

File: src/shared/mount-util.c [hunk 1]
```diff
@@ -530,71 +531,50 @@ int mode_to_inaccessible_node(
...
+                { .flag = MS_I_VERSION,   .name = "MS_I_VERSION",   },
+                { .flag = MS_STRICTATIME, .name = "MS_STRICTATIME", },
+                { .flag = MS_LAZYTIME,    .name = "MS_LAZYTIME",    },
+        };
+        _cleanup_free_ char *str = NULL;
+
+        for (size_t i = 0; i < ELEMENTSOF(map); i++)
+                if (flags & map[i].flag)
+                        if (!strextend_with_separator(&str, "|", map[i].name))
+                                return -ENOMEM;
```
Comment (poettering) [inline src/shared/mount-util.c:570]: i think it would be nice to keep track of the flags we resolved, and then show the ones we couldn't map.

i.e. do this here:
```c
flags &= ~map[i].flag;
```

and then below:

```c
if (!str || flags != 0) {
        r = strextendf_with_separator(&str, "|", "%lx", flags);
        if (r < 0)
                return r;
```

And then we can nicely handle all flags, the ones we know and the ones we don't...

Comment (yuwata) [reply src/shared/mount-util.c:570]: Done. PTAL.

**Comment by poettering** [comment]
excellent! thanks!

**Comment by doverride** [comment]
> While trying to reproduce this, I noticed that the mount flags are now printed in a "weird" way:
> 
> ```
> 21:16:35 Failed to mount tmpfs (type tmpfs) on /var/tmp/systemd-test-TEST-01-BASIC/root/tmp (2|4|(1<<24) "mode=1777,size=10%,nr_inodes=400k,uid=0,gid=0,context=system_u:object_r:svirt_sandbox_file_t:s0:c0,c1"): Invalid argument
> ```

I wonder why this is failing with invalid argument, looks like a valid `context=` to me...

**Comment by mrc0mmand** [comment]
> > While trying to reproduce this, I noticed that the mount flags are now printed in a "weird" way:
> > ```
> > 21:16:35 Failed to mount tmpfs (type tmpfs) on /var/tmp/systemd-test-TEST-01-BASIC/root/tmp (2|4|(1<<24) "mode=1777,size=10%,nr_inodes=400k,uid=0,gid=0,context=system_u:object_r:svirt_sandbox_file_t:s0:c0,c1"): Invalid argument
> > ```
> 
> I wonder why this is failing with invalid argument, looks like a valid `context=` to me...

Not sure why (my SELinux knowledge is almost non-existing), but without the "c0,c1" stuff it works:

```
[root@fedora ~]# mount -v -t tmpfs -o mode=1777,size=10%,nr_inodes=400k,uid=0,gid=0,context=system_u:object_r:container_file_t:s0:c0,c1 tmpfs test
mount: /root/test: wrong fs type, bad option, bad superblock on tmpfs, missing codepage or helper program, or other error.

[root@fedora ~]# mount -v -t tmpfs -o mode=1777,size=10%,nr_inodes=400k,uid=0,gid=0,context=system_u:object_r:container_file_t:s0 tmpfs test
mount: tmpfs mounted on /root/test.
```

:shrug:

**Comment by doverride** [comment]
Yes seems the proper way to do it is:

```
[root@brutus ~]# mount -v -t tmpfs -o mode=1777,size=10%,nr_inodes=400k,uid=0,gid=0,context=\"sys.id:sys.role:systemd.nspawn.container.fs:s0:c1,c2\" tmpfs test
mount: tmpfs mounted on /root/test
```
It works fine without the `\"` as long as it does not have a `,` separator in there...

**Comment by doverride** [comment]
@mrc0mmand can you confirm that? and @yuwata if so could you please adjust the code to make it look like `context=\"...\"` instead?

**Comment by mrc0mmand** [comment]
> @mrc0mmand can you confirm that? and @yuwata if so could you please adjust the code to make it look like `context=\"...\"` instead?

Quite indeed!

```
[root@fedora ~]# mount -v -t tmpfs -o mode=1777,size=10%,nr_inodes=400k,uid=0,gid=0,context=system_u:object_r:container_file_t:s0:c0,c1 tmpfs test
mount: /root/test: wrong fs type, bad option, bad superblock on tmpfs, missing codepage or helper program, or other error.

[root@fedora ~]# mount -v -t tmpfs -o mode=1777,size=10%,nr_inodes=400k,uid=0,gid=0,context=\"system_u:object_r:container_file_t:s0:c0,c1\" tmpfs test
mount: tmpfs mounted on /root/test.
```

**Comment by mrc0mmand** [comment]
Apart from the issue @doverride mentioned above, the flags seem to be finally displayed correctly:

```
Mounting ramfs (ramfs) on /dev/shm (MS_NOSUID|MS_NODEV|MS_NOEXEC "mode=0700")...
Couldn't read inherited credential 'passwd.hashed-password.root', skipping: No such file or directory
Couldn't read inherited credential 'passwd.plaintext-password.root', skipping: No such file or directory
Couldn't read inherited credential 'passwd.shell.root', skipping: No such file or directory
Remounting /dev/shm (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Moving mount /dev/shm â†’ /run/credentials/systemd-sysusers.service (MS_MOVE "")...
```

**Comment by yuwata** [comment]
> @mrc0mmand can you confirm that? and @yuwata if so could you please adjust the code to make it look like `context=\"...\"` instead?

Sure, now I am working on that. Thank you.

**Comment by yuwata** [comment]
@doverride, @mrc0mmand, @poettering and @bluca This PR becomes larger than I initially expected. But, now I hope mount options are handled correctly. PTAL.

**Comment by mrc0mmand** [comment]
> @doverride, @mrc0mmand, @poettering and @bluca This PR becomes larger than I initially expected. But, now I hope mount options are handled correctly. PTAL.

Thanks, I'll give it a spin!

File: src/test/test-mount-util.c [hunk 2]
```diff
@@ -69,6 +69,12 @@ static void test_mount_option_mangle(void) {
         opts = mfree(opts);
 
         assert_se(mount_option_mangle("rw,relatime,fmask=0022,dmask=0022,\"hogehoge", MS_RDONLY, &f, &opts) < 0);
+
+        assert_se(mount_option_mangle("mode=1777,size=10%,nr_inodes=400k,uid=496107520,gid=496107520,context=\"sys.id:sys.role:systemd.nspawn.container.fs:s0,s1\"", 0, &f, &opts) == 0);
+        assert_se(f == 0);
+        log_info("%s", opts);
+        assert_se(streq(opts, "mode=1777,size=10%,nr_inodes=400k,uid=496107520,gid=496107520,context=\"sys.id:sys.role:systemd.nspawn.container.fs:s0,s1\""));
+        opts = mfree(opts);
 }
```
Comment (ghost) [inline src/test/test-mount-util.c:77]: Probably best to use `\"system_u:object_r:svirt_sandbox_file_t:s0:c0,c1\"` here if this test runs on Fedora?

Comment (yuwata) [reply src/test/test-mount-util.c:77]: haha, this is just a test for option string handling, so the actual content is not important. But yeah, will fix. Thanks.

Comment (yuwata) [reply src/test/test-mount-util.c:77]: Updated.

**Comment by mrc0mmand** [comment]
Looks like everything works as it should:

```
# ...  /systemd-meson-build/systemd-nspawn --register=no ...  --selinux-apifs-context=system_u:object_r:container_file_t:s0:c0,c1 --selinux-context=system_u:system_r:container_t:s0:c0,c1 /usr/lib/systemd/systemd ... selinux=1
...
Spawning container TEST-01-BASIC on /var/tmp/systemd-test-TEST-01-BASIC/root.
Press ^] three times within 1s to kill container.
systemd 249-rc1-32-gdd24615 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.
Detected initialized system, this is not the first boot.

Welcome to Fedora 35 (Cloud Edition Prerelease)!
...
[  OK  ] Started User Login Management.
[  OK  ] Reached target Multi-User System.
         Starting Update UTMP about System Runlevel Changes...
         Starting TEST-01-BASIC...
[  OK  ] Finished Update UTMP about System Runlevel Changes.
[  OK  ] Finished TEST-01-BASIC.
[  OK  ] Reached target Testsuite target.
         Starting End the test...
[  OK  ] Stopped End the test.
...
Successfully forked off '(sd-executor)' as PID 58.
(sd-executor) succeeded.
Powering off.
Container TEST-01-BASIC has been shut down.
```

**Comment by cgzones** [comment]
This patch-set might now also fix #15822.

**Comment by keszybz** [comment]
LGTM.
I'll push a follow-up to add a smoke test for mount_flags_to_string().
