### PR TITLE
tmpfiles: skip redundant label writes to avoid unnecessary timestamp

### LINKED ISSUE #41507: systemd-tmpfiles: File modification time always changes with `z`
### systemd version the issue has been seen with

258.5

### Used distribution

ALT Atomic Onyx Nightly 04.04.2026

### Linux kernel version used

6.18.21-6.18-alt1

### CPU architectures issue was seen on

x86_64

### Component

systemd-tmpfiles

### Expected behaviour you didn't see

File modification time doesn't changed with `z` when mode and owner and group same as entry

### Unexpected behaviour you saw

File modification time will not changes with `z` when mode and owner and group same as entry

### Steps to reproduce the problem

Create tmpfiles with `z` entry. When triggering tmpfiles with `--create` time modification will changes even if nothing to change. With `d` all works fine

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by naraghavan2186**
When systemd-tmpfiles processes a 'z' (relabel) entry, fd_set_perms() unconditionally calls label_fix_full() even when mode, owner, and group already match. This causes setfilecon_raw() (SELinux) or xsetxattr() (SMACK) to write the security label even if it is already correct, which on some kernels updates the file's timestamps unnecessarily.

Fix this by comparing the current label with the desired label before writing, and skipping the write when they already match. This is consistent with how fd_set_perms() already skips chmod/chown when the values are unchanged.

Fixes [41507](https://github.com/systemd/systemd/issues/41507)

### CODE REVIEW

**Comment by naraghavan2186** [comment]
root@localhost:~# f=/tmp/ztst; rm -f "$f"; touch "$f"; chmod 0644 "$f"; sleep 3; stat -c "mtime=%Y ctime=%Z" "$f"; echo "z $f 0644 root root - -" | SYSTEMD_LOG_LEVEL=debug systemd-tmpfiles --create - 2>&1; stat -c "mtime=%Y ctime=%Z" "$f"
mtime=1775543207 ctime=1775543207
;245mLooking for configuration files in (higher priority first): 
;245m  /etc/tmpfiles.d 
;245m  /run/tmpfiles.d 
;245m  /usr/local/lib/tmpfiles.d 
;245m  /usr/lib/tmpfiles.d 
;245mSuccessfully loaded SELinux database in 5.729ms, size on heap is 1136K. 
;245mReading config from stdin... 
;245mRunning create action for entry z /tmp/ztst 
**;245mRelabelling "/tmp/ztst"**   -->  the relabeling code path is being entered even though mode, owner, and group already match.
mtime=1775543207 ctime=1775543207

**Comment by keszybz** [comment]
The comment from Claude seems to be valid.

File: src/shared/selinux-util.c [hunk 1]
```diff
@@ -389,6 +389,12 @@ static int selinux_fix_fd(
                 return log_selinux_enforcing_errno(errno, "Unable to lookup intended SELinux security context of %s: %m", label_path);
         }
 
+        /* Skip the write if the label is already correct, to avoid unnecessary
+         * timestamp changes on the file */
+        _cleanup_freecon_ char *oldcon = NULL;
+        if (sym_fgetfilecon_raw(fd, &oldcon) >= 0 && streq_ptr(fcon, oldcon))
```
[the remark this answers is not in the document]
Comment (naraghavan2186) [reply src/shared/selinux-util.c]: Fixed it. switched to getfilecon_raw(FORMAT_PROC_FD_PATH(fd), ...) to handle O_PATH fds, consistent with the rest of the function.

**Comment by naraghavan2186** [comment]
> The comment from Claude seems to be valid.

 Fixed it. switched to getfilecon_raw(FORMAT_PROC_FD_PATH(fd), ...) to handle O_PATH fds, consistent with the rest of the function.

File: src/shared/selinux-util.c [hunk 2]
```diff
@@ -400,8 +406,8 @@ static int selinux_fix_fd(
                         return 0;
 
                 /* If the old label is identical to the new one, suppress any kind of error */
-                _cleanup_freecon_ char *oldcon = NULL;
-                if (sym_getfilecon_raw(FORMAT_PROC_FD_PATH(fd), &oldcon) >= 0 && streq_ptr(fcon, oldcon))
+                _cleanup_freecon_ char *curcon = NULL;
+                if (sym_getfilecon_raw(FORMAT_PROC_FD_PATH(fd), &curcon) >= 0 && streq_ptr(fcon, curcon))
```
Comment (poettering) [inline src/shared/selinux-util.c]: hmm, i think we'll have the same code at at least 3 places in selinux-util.c, no?

please add a helper hence that does is called fgetfilecon_idempotent() or so which does this all in one, and can be used at all places:

1. it suppresses no-change relabels
2. it goes via FORMAT_PROT_FD_PATH() so that O_PATH fds can work

File: src/shared/smack-util.c [hunk 3]
```diff
@@ -142,6 +142,13 @@ static int smack_fix_fd(
         else
                 return 0;
 
+        /* Skip the write if the label is already correct, to avoid unnecessary
+         * timestamp changes on the file */
+        _cleanup_free_ char *old_label = NULL;
+        if (fgetxattr_malloc(fd, "security.SMACK64", &old_label, /* ret_size= */ NULL) >= 0 &&
+            streq(old_label, label))
+                return 0;
```
Comment (poettering) [inline src/shared/smack-util.c]: maybe just make xsetxattr() do this by default. it seems like this is always a good idea

File: src/shared/smack-util.c [hunk 4]
```diff
@@ -151,10 +158,10 @@ static int smack_fix_fd(
                 return 0;
         if (r < 0) {
                 /* If the old label is identical to the new one, suppress any kind of error */
-                _cleanup_free_ char *old_label = NULL;
+                _cleanup_free_ char *cur_label = NULL;
 
-                if (fgetxattr_malloc(fd, "security.SMACK64", &old_label, /* ret_size= */ NULL) >= 0 &&
-                    streq(old_label, label))
+                if (fgetxattr_malloc(fd, "security.SMACK64", &cur_label, /* ret_size= */ NULL) >= 0 &&
+                    streq(cur_label, label))
```
Comment (poettering) [inline src/shared/smack-util.c]: hmm, this a-posterio check is kinda pointless now, no?

File: src/shared/selinux-util.c (hunk 2 above)
Comment (naraghavan2186) [reply src/shared/selinux-util.c]: Added setfilecon_idempotent() helper (named after sethostname_idempotent() since it's setting, not getting). It reads the current context via FORMAT_PROC_FD_PATH() for O_PATH support, compares, and only writes if different. Used it in both selinux_fix_fd() and mac_selinux_apply_fd(). Left mac_selinux_apply() unchanged since it's path-based, not fd-based.

File: src/shared/smack-util.c (hunk 3 above)
Comment (naraghavan2186) [reply src/shared/smack-util.c]: added the check directly inside xsetxattr_full(). It reads the current value via getxattr_at_malloc() and compares with memcmp before writing.

File: src/shared/smack-util.c (hunk 4 above)
Comment (naraghavan2186) [reply src/shared/smack-util.c]: Removed the redundant error-path check

File: src/shared/selinux-util.c [hunk 5]
```diff
@@ -389,25 +402,19 @@ static int selinux_fix_fd(
...
-                _cleanup_freecon_ char *oldcon = NULL;
-                if (sym_getfilecon_raw(FORMAT_PROC_FD_PATH(fd), &oldcon) >= 0 && streq_ptr(fcon, oldcon))
-                        return 0;
+        /* If the FS doesn't support labels, then exit without warning */
+        if (ERRNO_IS_NOT_SUPPORTED(r))
+                return 0;
 
-                return log_selinux_enforcing_errno(r, "Unable to fix SELinux security context of %s: %m", label_path);
-        }
+        /* It the FS is read-only and we were told to ignore failures caused by that, suppress error */
```
[the remark this answers is not in the document]
Comment (naraghavan2186) [reply src/shared/selinux-util.c]: Fixed

File: src/basic/xattr-util.c [hunk 6]
```diff
@@ -301,6 +301,16 @@ int xsetxattr_full(
...
 
+        /* Skip the write if the xattr already has the correct value, to avoid
+         * unnecessary timestamp changes on the file */
+        _cleanup_free_ char *old_value = NULL;
+        size_t old_size;
+
+        if (getxattr_at_malloc(fd, path, name, at_flags, &old_value, &old_size) >= 0 &&
+            old_size == size &&
+            memcmp(old_value, value, size) == 0)
+                return 0;
```
[the remark this answers is not in the document]
Comment (naraghavan2186) [reply src/basic/xattr-util.c:314]: Fixed

File: src/basic/xattr-util.c [hunk 7]
```diff
@@ -301,6 +301,19 @@ int xsetxattr_full(
...
+         * unnecessary timestamp changes on the file. Only do this for plain
+         * replace mode (xattr_flags == 0) — XATTR_CREATE callers expect
+         * -EEXIST when the xattr already exists. */
+        _cleanup_free_ char *old_value = NULL;
+        size_t old_size;
+
+        if (xattr_flags == 0 &&
+            getxattr_at_malloc(fd, path, name, at_flags, &old_value, &old_size) >= 0 &&
+            old_size == size &&
+            memcmp(old_value, value, size) == 0)
```
Comment (poettering) [inline src/basic/xattr-util.c]: the two latter checks can be replaced by using `memcmp_nn(old_value, old_size, value, size) == 0`

Comment (naraghavan2186) [reply src/basic/xattr-util.c]: Understood and fixed it.
