### PR TITLE
ask-password: refuse empty password strv

### LINKED ISSUE #34270: `homectl` Segmentation fault
### systemd version the issue has been seen with

256.5-1-arch

### Used distribution

Arch Linux

### Linux kernel version used

6.10.8-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

homectl

### Expected behaviour you didn't see

`homectl create user` ask for the password then create a new home, on TTY.
 

### Unexpected behaviour you saw

1. `homectl create user` did not do null pointer check right and got Segfault. Here is the stack trace:

    ```
    #0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
    No locals.
    #1  0x00007b46f70bacd3 in __GI___strdup (s=0x0) at strdup.c:41
            len = <optimized out>
            new = <optimized out>
    #2  0x0000579caf7f06fe in acquire_new_password (user_name=0x579ce9d5c2e0 "test1", hr=hr@entry=0x579ce9d5ec40, suggest=suggest@entry=true, ret=ret@entry=0x7fff818d4160)
        at ../systemd/src/home/homectl.c:1264
            copy = 0x0
            _pvar_ = <optimized out>
            _var_ = <optimized out>
            _nullvalue_ = <optimized out>
            second = 0x579ce9d5f300
            question = 0x579ce9d5f0c0 "Please enter new password for user test1 (repeat):"
            _e = <optimized out>
            first = 0x579ce9d5f2e0
            req = {message = 0x579ce9d5f0c0 "Please enter new password for user test1 (repeat):", keyring = 0x579caf8030d2 "home-password", icon = 0x579caf8030e0 "user-home", id = 0x0, 
              credential = 0x579caf8031a9 "home.new-password"}
            _level = <optimized out>
            envpw = 0x0
            i = <optimized out>
            r = <optimized out>
            __func__ = "acquire_new_password"
    #3  0x0000579caf7f56d2 in create_home_common (input=<optimized out>) at ../systemd/src/home/homectl.c:1433
            new_password = 0x0
            bus = 0x579ce9d5c4a0
            hr = 0x579ce9d5ec40
            blobs = 0x0
            r = 0
            __func__ = "create_home_common"
    #4  0x0000579caf7ed69a in run (argc=4, argv=0x7fff818d4718) at ../systemd/src/home/homectl.c:4592
            r = 1
            verbs = <optimized out>
            r = <optimized out>
    #5  main (argc=4, argv=0x7fff818d4718) at ../systemd/src/home/homectl.c:4595
            r = <optimized out>
            __func__ = "main"
    
    ```

2. Note that the problem was not `strdup`ping a null pointer. It was, instead, why `ask_password_auto` skip printing the prompt and reading the password. 
3. This issue was only seen when a normal user logged onto the TTY and run this command without `sudo` or `run0` or equivalent things. The user may have sufficient permission to create a new home, via polkit.

### Steps to reproduce the problem

1. Fresh install Arch Linux (and update all things to the latest version).
2. After boot, log in with `root` on TTY. Then create a new home:

    ```
    homectl create --member-of=wheel foo
    ```

3. Log `root` out, then log `foot` in.
4. Run:

    ```
    homectl create bar
    ```

    and got "segmentation fault"

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → AUTHENTICATING
Successfully forked off '(polkit-agent)' as PID 2763.
Skipping PR_SET_MM, as we don't have privileges.
{
	"userName" : "bar",
	"disposition" : "regular",
	"lastChangeUSec" : 1725558427150711,
	"lastPasswordChangeUSec" : 1725558427150711
}
libpwquality.so.1 is not installed: libpwquality.so.1: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #34270.

### CODE REVIEW

File: src/shared/ask-password-api.c [hunk 1]
```diff
@@ -168,7 +168,16 @@ static int ask_password_keyring(const AskPasswordRequest *req, AskPasswordFlags
...
                 return r;
 
-        return retrieve_key(serial, ret);
+        _cleanup_strv_free_erase_ char **l = NULL;
+        r = retrieve_key(serial, &l);
+        if (r < 0)
+                return r;
+
+        if (strv_isempty(l))
+                return log_debug_errno(SYNTHETIC_ERRNO(ENOKEY), "Found an empty password from keyring.");
```
Comment (poettering) [inline src/shared/ask-password-api.c:177]: i thnk a similar check is still missing in ask_password_plymouth(). Hopefully plymouth won't send us an empty password list, but better check that too.

Comment (yuwata) [reply src/shared/ask-password-api.c:177]: I noticed that, but it is currently used by only tty-ask-password.c, and the caller checks if the strv is empty. So, I did not touch that part.

Now, for consistency, `_plymouth()` also checks the strv, and dropped the check in tty-ask-password.

**Comment by yuwata** [comment]
@poettering Thank you for the review. The request is applied. PTAL.
