### PR TITLE
pretty-print: fix handling of line continuation in cat_file()

### LINKED ISSUE #35878: Wrong syntax highligting with `systemctl cat` for multiline value
### systemd version the issue has been seen with

256.9-2.fc41

### Used distribution

Fedora 41

### Linux kernel version used

6.12.4-200.fc41

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

`systemctl cat` should correctly syntax highlight service files

### Unexpected behaviour you saw

Multiline values which contain an equal sign are colored green up to the equal sign even though they are just part of a larger string.

image

### Steps to reproduce the problem

Create a service containing the below content and run `systemctl cat` on in.

```ini
Environment="ARGS= \
    --collector.cpu.info \
    --collector.drm \
    --collector.ethtool \
    --collector.systemd \
    --collector.systemd.unit-include=(ds-player-backend|kiosksession@tty1)\\.service \
    --collector.systemd.enable-restarts-metrics \
    --collector.systemd.enable-start-time-metrics \
"
```

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #35878.

### CODE REVIEW

File: src/shared/pretty-print.c [hunk 1]
```diff
@@ -219,6 +203,7 @@ static int cat_file(const char *filename, bool newline, CatFlags flags) {
                ansi_normal());
         fflush(stdout);
 
+        bool continued = false;
```
Comment (YHNdnzj) [inline src/shared/pretty-print.c]: Can be placed directly in for()?

File: src/shared/pretty-print.c [hunk 2]
```diff
@@ -228,58 +213,78 @@ static int cat_file(const char *filename, bool newline, CatFlags flags) {
...
+                }
+
+                /* Check if the line ends with a backslash. */
+                bool escaped = false;
+                char *e;
+                for (e = line; *e != '\0'; e++) {
+                        if (escaped)
+                                escaped = false;
+                        else if (*e == '\\')
+                                escaped = true;
```
Comment (YHNdnzj) [inline src/shared/pretty-print.c:258]: Hmm? Why not strrchr and check if the next char is NUL?

Comment (yuwata) [reply src/shared/pretty-print.c:258]: `"\\\\"` (two backslashes) at the end means one backslash.

File: src/shared/pretty-print.c [hunk 3]
```diff
@@ -222,11 +222,11 @@ static int cat_file(const char *filename, bool newline, CatFlags flags) {
                 }
 
                 /* empty line */
-                if (isempty(l) && FLAGS_SET(flags, CAT_TLDR))
+                if (isempty(l) && FLAGS_SET(flags, CAT_TLDR) && !continued)
```
Comment (poettering) [inline src/shared/pretty-print.c]: what about comments, shouldn't they also be skipped after continuation lines? (just wondering, no idea what our conf file parser actually does there)

**Comment by poettering** [comment]
would be good having a test for this that just checks that --tldr output of some complex file with comments and continuation lines is what we expect it to be. This parsing stuff is otherwise quite hard to follow, I#d say.

**Comment by poettering** [comment]
i do wonder if it wouldn't be better to somehow to merge the cat/tldr logic into regular config_parse(), so that we definitely have the same parser in place.

**Comment by yuwata** [comment]
> i do wonder if it wouldn't be better to somehow to merge the cat/tldr logic into regular config_parse(), so that we definitely have the same parser in place.

I thought so, but it is also used for parsing non-ini style files, e.g. tmpfiles, binfmt, sysusers, and so on.

**Comment by yuwata** [comment]
> would be good having a test for this that just checks that --tldr output of some complex file with comments and continuation lines is what we expect it to be. This parsing stuff is otherwise quite hard to follow, I#d say.

test case is added. PTAL.

**Review by bluca — APPROVED** [review]
