### PR TITLE
core/device: inactivate removed device on switching root

### LINKED ISSUE #25106: some network units created not properly after renamed network interface
### systemd version the issue has been seen with

251.5-607.fc37

### Used distribution

Fedora 37

### Linux kernel version used

5.19.14-300.fc37.aarch64

### CPU architectures issue was seen on

aarch64

### Component

udev rule files

### Expected behaviour you didn't see

I have configured `/etc/udev/rules.d/80-ifname.rules` with content
```
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="bcmgenet", NAME="lan"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="brcmfmac", NAME="wlan"
```
This file renames the network interface at udev level. All work expected. systemd-networkd applies 'network' files to the renamed network interface. I have access to the server via a network.
Except autogenerated system unit file with name `sys-devices-platform-scb-fd580000.ethernet-net-eth0.device`.
```
[root@wc-1 ~]# systemctl status sys-devices-platform-scb-fd580000.ethernet-net-eth0.device
● sys-devices-platform-scb-fd580000.ethernet-net-eth0.device - /sys/devices/platform/scb/fd580000.ethernet/net/eth0
     Loaded: loaded
     Active: activating (tentative) since Sat 2022-10-01 00:00:04 UTC; 55min ago
```
I have checked content of `/sys/devices/platform/scb/fd580000.ethernet/net`  content
```
[root@wc-1 ~]# ls -l /sys/devices/platform/scb/fd580000.ethernet/net
total 0
drwxr-xr-x. 5 root root 0 Oct  1 00:00 lan
[root@wc-1 ~]# ls -l /sys/devices/platform/scb/fd580000.ethernet/net/*
total 0
-r--r--r--. 1 root root 4096 Oct  1 00:00 addr_assign_type
-r--r--r--. 1 root root 4096 Oct  1 00:38 addr_len
-r--r--r--. 1 root root 4096 Oct  1 00:00 address
-r--r--r--. 1 root root 4096 Oct  1 00:38 broadcast
-rw-r--r--. 1 root root 4096 Oct  1 00:38 carrier
-r--r--r--. 1 root root 4096 Oct  1 00:38 carrier_changes
-r--r--r--. 1 root root 4096 Oct  1 00:38 carrier_down_count
-r--r--r--. 1 root root 4096 Oct  1 00:38 carrier_up_count
-r--r--r--. 1 root root 4096 Oct  1 00:38 dev_id
-r--r--r--. 1 root root 4096 Oct  1 00:38 dev_port
lrwxrwxrwx. 1 root root    0 Oct  1 00:38 device -> ../../../fd580000.ethernet
-r--r--r--. 1 root root 4096 Oct  1 00:38 dormant
-r--r--r--. 1 root root 4096 Oct  1 00:10 duplex
-rw-r--r--. 1 root root 4096 Oct  1 00:38 flags
-rw-r--r--. 1 root root 4096 Oct  1 00:38 gro_flush_timeout
-rw-r--r--. 1 root root 4096 Oct  1 00:38 ifalias
-r--r--r--. 1 root root 4096 Oct  1 00:38 ifindex
-r--r--r--. 1 root root 4096 Oct  1 00:38 iflink
-r--r--r--. 1 root root 4096 Oct  1 00:38 link_mode
-rw-r--r--. 1 root root 4096 Oct  1 00:38 mtu
-r--r--r--. 1 root root 4096 Oct  1 00:00 name_assign_type
-rw-r--r--. 1 root root 4096 Oct  1 00:38 napi_defer_hard_irqs
-rw-r--r--. 1 root root 4096 Oct  1 00:38 netdev_group
-r--r--r--. 1 root root 4096 Oct  1 00:38 operstate
lrwxrwxrwx. 1 root root    0 Oct  1 00:38 phydev -> ../../unimac-mdio.-19/mdio_bus/unimac-mdio--19/unimac-mdio--19:00
-r--r--r--. 1 root root 4096 Oct  1 00:38 phys_port_id
-r--r--r--. 1 root root 4096 Oct  1 00:38 phys_port_name
-r--r--r--. 1 root root 4096 Oct  1 00:38 phys_switch_id
drwxr-xr-x. 2 root root    0 Oct  1 00:38 power
-rw-r--r--. 1 root root 4096 Oct  1 00:38 proto_down
drwxr-xr-x. 8 root root    0 Oct  1 00:00 queues
-r--r--r--. 1 root root 4096 Oct  1 00:10 speed
drwxr-xr-x. 2 root root    0 Oct  1 00:38 statistics
lrwxrwxrwx. 1 root root    0 Oct  1 00:00 subsystem -> ../../../../../../class/net
-r--r--r--. 1 root root 4096 Oct  1 00:38 testing
-rw-r--r--. 1 root root 4096 Oct  1 00:38 threaded
-rw-r--r--. 1 root root 4096 Oct  1 00:38 tx_queue_len
-r--r--r--. 1 root root 4096 Oct  1 00:38 type
-rw-r--r--. 1 root root 4096 Oct  1 00:00 uevent
```
For me, systemd does not see the network devices being renamed and generates a unit file for a device that does not exist now.

### Unexpected behaviour you saw

systemd generate unit files to the actual device name after it is renamed at udev rule level.

### Steps to reproduce the problem

Create file `/etc/udev/rules.d/80-ifname.rules` with content like
```
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="bcmgenet", NAME="lan"
```

Restart server.
Check which systemd units have status `activating`
```
systemctl -a | grep activating
```
Now, this unit points to the non-existent network device.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #25106.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @mwilck and @fbuihuu.

**Comment by mwilck** [comment]
Half a year ago, I guess I would be able to tell whether or not this is correct, as I understood the logic. AFAICS, this patch shouldn't break anything.

But I don't understand why this fixes #25106. `device_coldplug()`  is executed way before udev has any chance to rename the device (after switching root). If the device had been renamed before switching root, why did systemd (in initramfs) consider it plugged with the old, wrong, name?

File: src/core/device.c [hunk 1]
```diff
@@ -305,6 +305,19 @@ static int device_coldplug(Unit *u) {
                 found &= ~DEVICE_FOUND_UDEV;
                 if (state == DEVICE_PLUGGED)
                         state = DEVICE_TENTATIVE;
+
+                /* Also check the existence of the device syspath. Otherwise, if the device has been removed
+                 * during the switching root, it will never go to inactive state, as both Device.found and
+                 * Device.enumerated_found do not have the DEVICE_FOUND_UDEV flag, so device_catchup() in
+                 * device_update_found_one() does nothing in most cases. See issue #25106. Note, the syspath
+                 * field only serialized and deserialized when the device was previously processed by udevd,
+                 * and switched from the root filesystem with newer systemd. */
```
Comment (keszybz) [inline src/core/device.c]:
```
                /* Also check the validity of the device syspath. Without this check, if the device was removed
                 * while switching root, it would never go to inactive state, as both Device.found and
                 * Device.enumerated_found do not have the DEVICE_FOUND_UDEV flag, so device_catchup() in
                 * device_update_found_one() does nothing in most cases. See issue #25106. Note that the syspath
                 * field is only serialized when systemd is sufficiently new and the device has been already processed
                 * by udevd. */
```

**Comment by yuwata** [comment]
> Half a year ago, I guess I would be able to tell whether or not this is correct, as I understood the logic. Today, I feel less certain about it. Anyway, AFAICS, this patch shouldn't break anything.

IIRC, we have discussed about that the dropping `DEVICE_FOUND_UDEV` flag causes devices removed while switching root never go to inactive state. So, I added
```
                if (found == DEVICE_NOT_FOUND)
                        state = DEVICE_DEAD; /* If nobody sees the device, downgrade more */
```
But, `found == DEVICE_NOT_FOUND` actually does NOT means the device is removed, but the device is not interested by any other units. And the code causes #23429, which is fixed by cf1ac0cfe44997747b0f857a1d0b67cea1298272.

So, at the time, the removal of devices while during switching root was not correctly handled.

> But I don't understand why this fixes #25106. `device_coldplug()` is executed way before udev has any chance to rename the device (after switching root). Otoh, if the device had been renamed **before** switching root, why did systemd (in initramfs) consider it plugged with the old, wrong, name?

The issue should be caused the following steps:
1. in initrd, the device (network interface) is renamed by udevd or any external tools,
2. _before_ PID1 in initrd receives the 'move' uevent, PID1 starts the serialization process. Hence, the device with old syspath is serialized,
3. device_coldplug(): PID1 in main system setup the removed device with the deserialized state. As it is not enumerated, hence the device is in `DEVICE_TENTATIVE` state (that is, activating state) without `DEVICE_FOUND_UDEV` flag. Note, `Device.found` is now `DEVICE_NOT_FOUND`, as network interface is not mounted or cannot be used as swap.
4. device_catchup(): as `enumerated_found` is also `DEVICE_NOT_FOUND`, it does nothing. Hence, the device is still in activating.

**Comment by mwilck** [comment]
> before PID1 in initrd receives the 'move' uevent, PID1 starts the serialization process. Hence, the device with old syspath is serialized,

Ah. I didn't know this was possible. This seems to be the core of the issue IMO. But I realize that it's hard to avoid.
What you're saying makes sense.

I still wonder if the reporter of #25106 has a correctly configured system (I already posted there, as you may have seen).

**Review by mwilck — APPROVED** [review]
To the best of my knowledge, this should be fine. If the syspath, which represents the "real" device, doesn't exist, the device is gone.

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by keszybz** [comment]
Queued up for v252.3.

**Comment by yuwata** [comment]
Setting the backport tag again to backport older release (with other PRs). (@keszybz Sorry for the late action in another PR).

**Comment by keszybz** [comment]
Queued up for v251.9.
