### PR TITLE
systemctl: enable: overwrite broken alias symlinks

### LINKED ISSUE #23694: systemctl enable/preset should take over broken alias symlinks
In Debian, when we remove a package, we are not disabling the service provided by that package, the "enablement state" of the service is kept along with the configuration files so that if you reinstall the package, you end up in the same state.

The downside to this is that when you have a service unit with an "Alias" directive, the symlink created for the aliased name also stays and becomes a broken symlink (because the underlying .service file has been removed from /usr/lib/systemd/).

This symlink is then causing issue when the same aliased name is reused by another service unit. For instance, when I try to switch from wireplumber to pipewire-media-session (or the opposite), I will get an error like this:

```
$ sudo systemctl enable --global pipewire-media-session.service 
Failed to enable unit, file "/etc/systemd/user/pipewire-session-manager.service" already exists and is a symlink to "/usr/lib/systemd/user/wireplumber.service".
```

I would like systemd to recognize that this symlink is broken and behave as if it didn't exist precisely because it's broken. I don't think that you would break backwards compatibility in any meaningful way with this change.

### PR DESCRIPTION
**Pull request by YHNdnzj**
When switching to an alternative alias provider, the previous one might have been uninstalled or so. It should be fine for us to overwrite them directly.

Fixes #23694

### CODE REVIEW

File: src/shared/install.c [hunk 1]
```diff
@@ -1912,6 +1912,16 @@ static int install_info_symlink_alias(
...
                         return -ENOMEM;
 
+                if (!force) {
+                        q = chase_symlinks(alias_path, lp->root_dir, CHASE_NONEXISTENT, NULL, NULL);
+                        if (q < 0 && q != -ENOENT) {
+                                r = r < 0 ? r : q;
+                                continue;
+                        }
+                        if (q == 0)
+                                force = true;
```
Comment (poettering) [inline src/shared/install.c]: so if the file doesn't exist then you enable force mode? i don#t grok that logic? care to explain?

**Comment by YHNdnzj** [comment]
If the source file doesn’t exist, it’s a broken symlink, and thus it’s OK
to force overwrite it.

**Comment by poettering** [comment]
well, but you are turning it on for *all* aliases, this is called in a loop after all

**Comment by YHNdnzj** [comment]
Oops. Sorry.

File: src/shared/install.c [hunk 2]
```diff
@@ -1912,7 +1913,15 @@ static int install_info_symlink_alias(
...
                         return -ENOMEM;
 
-                q = create_symlink(lp, info->path, alias_path, force, changes, n_changes);
+                q = chase_symlinks(alias_path, lp->root_dir, CHASE_NONEXISTENT, NULL, NULL);
+                if (q < 0 && q != -ENOENT) {
+                        r = r < 0 ? r : q;
+                        continue;
+                }
+                if (q == 0)
+                        broken = true;
```
Comment (poettering) [inline src/shared/install.c]: maybe just:

```c
broken = q == 0; /* symlink target does not exist? */
```

File: src/shared/install.c [hunk 3]
```diff
@@ -1892,6 +1892,7 @@ static int install_info_symlink_alias(
 
         STRV_FOREACH(s, info->aliases) {
                 _cleanup_free_ char *alias_path = NULL, *dst = NULL, *dst_updated = NULL;
+                bool broken = false;
```
Comment (poettering) [inline src/shared/install.c]: this initialization can go away now.
