### PR TITLE
fix handling of templates instantiated in /usr/lib 

### LINKED ISSUE #5136: systemd reports "bad" unit file state for instantiated unit file alias names
### Submission type
  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with
current master

### Used distribution
Fedora Rawhide (nspawn container)

### In case of bug report: Expected behaviour you didn't see
Output of ```systemctl list-unit-files``` shouldn't list unit files being in "bad" state unless there is really something wrong with them.

### In case of bug report: Unexpected behaviour you saw
$subject 

### In case of bug report: Steps to reproduce the problem
Have following unit files present, 

```
$ systemctl list-unit-files getty*
UNIT FILE      STATE  
getty@.service enabled
getty.target   static 

2 unit files listed.
```

Then create following symlink and reload systemd,

```
$ ln -s /usr/lib/systemd/system/getty@.service /usr/lib/systemd/system/getty@tty9.service
$ systemctl daemon-reload
```

Observe that systemd claims that ```getty@tty9.service``` unit file is in a "bad" state. However that unit file is perfectly fine, since it is an alias to ```getty@.service``` and we didn't do anything with ```getty@.service``` template.

```
$ systemctl list-unit-files getty*
UNIT FILE          STATE  
getty@.service     enabled
getty@tty9.service bad              <--- BUG
getty.target       static 
```

### PR DESCRIPTION
**Pull request by poettering**
All work to fix #5136.

### CODE REVIEW

File: src/shared/install.c [hunk 1]
```diff
@@ -1439,6 +1440,18 @@ static int install_info_traverse(
...
                                         return r;
 
+                                if (streq(buffer, i->name)) {
+
+                                        /* We filled in the instance, and the target stayed the same? If so, then let's
+                                         * honour the link as it is. */
+
+                                        r = install_info_follow(c, i, paths->root_dir, flags, true);
+                                        if (r < 0)
+                                                return r;
```
Comment (keszybz) [inline src/shared/install.c:1493]: It is normally an error to have a symlink to itself, but not in the systemd enable-by-symlink syntax. Indeed, we allow symlinks that point to nothing, we might just as well allow symlinks which loop.

**Comment by keszybz** [comment]
```
:: [  BEGIN   ] :: Running 'userdel -r systemdtester'
userdel: user systemdtester is currently used by process 4245
:: [   FAIL   ] :: Command 'userdel -r systemdtester' (Expected 0, got 8)
```
I've seen this before, seems unrelated.

**Comment by keszybz** [comment]
Damn github, I reloaded the page and it kept the merge text but reset the merge type.
