### PR TITLE
journal: fix dropping first record during upload to remote journal

### LINKED ISSUE #13576: journal-upload/journal-remote is dropping the first record during a transaction
**systemd version the issue has been seen with**
> systemd-243-1.fc32

**Used distribution**
 > Fedora Rawhide

Either systemd-journal-upload or systemd-journal-remote seems to drop the first record during a transaction:

Reproducer:
```bash
#!/bin/bash

TEST_SRC_JOURNAL="$(mktemp src-journalXXX.journal)"
TEST_DST_JOURNAL="$(mktemp dst-journalXXX.journal)"
TEST_TAG="journaluploadtest$RANDOM"

rpm -q systemd-journal-remote || exit 1

# Create a test source journal
logger -t $TEST_TAG 'Testing journal-upload #1'
logger -t $TEST_TAG 'Testing journal-upload #2'
logger -t $TEST_TAG 'Testing journal-upload #3'
journalctl -o export -t $TEST_TAG | /usr/lib/systemd/systemd-journal-remote --split-mode=none --output=$TEST_SRC_JOURNAL -
echo "--- INPUT JOURNAL BEGIN ---"
journalctl --file=$TEST_SRC_JOURNAL
echo "--- INPUT END BEGIN ---"

# Start a systemd-journal-remote listener
/usr/lib/systemd/systemd-journal-remote --split-mode=none --output=$TEST_DST_JOURNAL --listen-http=127.0.0.1:19532 &
JOURNAL_REMOTE_PID=$!
sleep 1

if kill -0 $JOURNAL_REMOTE_PID; then
    /usr/lib/systemd/systemd-journal-upload --file=$TEST_SRC_JOURNAL --follow=no --url=http://localhost:19532
    sleep 1
    kill $JOURNAL_REMOTE_PID
    echo "--- OUTPUT JOURNAL BEGIN ---"
    journalctl --file=$TEST_DST_JOURNAL -t $TEST_TAG
    echo "--- OUTPUT JOURNAL END---"
else
    echo >&2 "[ERROR] Failed to start a systemd-journal-remote listener"
fi

rm -fv $TEST_SRC_JOURNAL $TEST_DST_JOURNAL
```

Output:
```
# ./repro.sh 
systemd-journal-remote-243-1.fc32.x86_64
Finishing after writing 3 entries
--- INPUT JOURNAL BEGIN ---
-- Logs begin at Tue 2019-09-17 07:12:13 EDT, end at Tue 2019-09-17 07:12:13 EDT. --
Sep 17 07:12:13 host-10-0-137-186 journaluploadtest19061[2551]: Testing journal-upload #1
Sep 17 07:12:13 host-10-0-137-186 journaluploadtest19061[2552]: Testing journal-upload #2
Sep 17 07:12:13 host-10-0-137-186 journaluploadtest19061[2553]: Testing journal-upload #3
--- INPUT END BEGIN ---
No more entries, closing journal.
--- OUTPUT JOURNAL BEGIN ---
Finishing after writing 2 entries
-- Logs begin at Tue 2019-09-17 07:12:13 EDT, end at Tue 2019-09-17 07:12:13 EDT. --
Sep 17 07:12:13 host-10-0-137-186 journaluploadtest19061[2552]: Testing journal-upload #2
Sep 17 07:12:13 host-10-0-137-186 journaluploadtest19061[2553]: Testing journal-upload #3
--- OUTPUT JOURNAL END---
removed 'src-journalmEM.journal'
removed 'dst-journalr6e.journal'
```

### PR DESCRIPTION
**Pull request by vtronko**
fix #13576

### CODE REVIEW

File: src/journal-remote/journal-upload-journal.c [hunk 1]
```diff
@@ -410,5 +410,5 @@ int open_journal_for_upload(Uploader *u,
                                                cursor);
         }
 
-        return process_journal_input(u, 1 + !!after_cursor);
+        return process_journal_input(u, 0 + !!after_cursor);
```
Comment (keszybz) [inline src/journal-remote/journal-upload-journal.c]: Yep, this looks OK. But please drop `0 + !!`, no need to keep it.

**Comment by keszybz** [comment]
`!!` is also pointless, but OK.

**Comment by keszybz** [comment]
centos ci (arch in kvm) failed with TEST-43-PRIVATEUSER-UNPRIV, which I assume is unrelated.
