### PR TITLE
journal: Log a better message when we're rotating because a file is full

### LINKED ISSUE #22007: systemd-journald: Failed to write entry (20 items, 658 bytes), rotating before retrying: Argument list too long
**systemd version the issue has been seen with**
 > 2.50 (regression since 249.7)

**Used distribution**
 > LibreELEC:master
Dev tree in use: https://github.com/heitbaum/LibreELEC.tv/commits/dev

**Linux kernel version used** (`uname -a`)

 > `Linux nuc11 5.15.13-rc1 #1 SMP Tue Jan 4 07:47:49 UTC 2022 x86_64 GNU/Linux` `Linux version 5.15.13-rc1 (docker@31f49c1bcfb8) (x86_64-libreelec-linux-gnu-gcc-10.3.0 (GCC) 10.3.0, GNU ld (GNU Binutils) 2.37) #1 SMP Tue Jan 4 07:47:49 UTC 2022`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > systemd-journald[365]: Failed to write entry (20 items, 849 bytes), rotating before retrying: Argument list too long

**Steps to reproduce the problem**
 > use 250 instead of 249.7, unsure where these log messages are actually coming from in dmesg/kmsg 

https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/sysutils/systemd
https://github.com/heitbaum/LibreELEC.tv/commit/d2263ea5c338831a5c522ea71780683bab361edb
https://github.com/heitbaum/LibreELEC.tv/commit/785f227163202aa75e08658fbd7d43fa10017906

**Additional program output to the terminal or log subsystem illustrating the issue**.7

```
dmesg | grep systemd
[    3.383568] systemd[1]: systemd 250 running in system mode (-PAM -AUDIT -SELINUX -APPARMOR -IMA -SMACK -SECCOMP -GCRYPT -GNUTLS -OPENSSL -ACL +BLKID -CURL -ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP -LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -BZIP2 -LZ4 -XZ -ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=hybrid)
[    3.401375] systemd[1]: Detected architecture x86-64.
[    3.487469] systemd[1]: Queued start job for default target Kodi Mediacenter Interface.
[    3.489989] systemd[1]: Created slice Slice /system/modprobe.
[    3.490088] systemd[1]: Created slice User and Session Slice.
[    3.490111] systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
[    3.490127] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    3.490146] systemd[1]: Reached target Path Units.
[    3.490156] systemd[1]: Reached target Slice Units.
[    3.491494] systemd[1]: Listening on RPCbind Server Activation Socket.
[    3.491509] systemd[1]: Reached target RPC Port Mapper.
[    3.491536] systemd[1]: Listening on initctl Compatibility Named Pipe.
[    3.492056] systemd[1]: Journal Audit Socket was skipped because of a failed condition check (ConditionSecurity=audit).
[    3.492221] systemd[1]: Listening on Journal Socket (/dev/log).
[    3.492255] systemd[1]: Listening on Journal Socket.
[    3.492498] systemd[1]: Listening on udev Control Socket.
[    3.492525] systemd[1]: Listening on udev Kernel Socket.
[    3.492558] systemd[1]: Huge Pages File System was skipped because of a failed condition check (ConditionPathExists=/sys/kernel/mm/hugepages).
[    3.492767] systemd[1]: Mounting POSIX Message Queue File System...
[    3.492999] systemd[1]: Mounting Kernel Debug File System...
[    3.493248] systemd[1]: Mounting Kernel Trace File System...
[    3.493536] systemd[1]: Mounting Variable Directory...
[    3.493845] systemd[1]: Starting Create List of Static Device Nodes...
[    3.494102] systemd[1]: Starting Load Kernel Module configfs...
[    3.494376] systemd[1]: Starting Load Kernel Module drm...
[    3.494641] systemd[1]: Starting Load Kernel Module fuse...
[    3.494983] systemd[1]: Starting Show Version...
[    3.495237] systemd[1]: Starting Create Persistent Log Directory on /storage and rotate large logs...
[    3.495488] systemd[1]: Starting Mounting swapfile...
[    3.497638] systemd[1]: Starting Rebuild Hardware Database...
[    3.499201] systemd[1]: Starting Load Kernel Modules...
[    3.499454] systemd[1]: Starting Setup NTP servers for timesyncd...
[    3.499794] systemd[1]: Starting Coldplug All udev Devices...
[    3.500101] systemd[1]: Starting Wait for Kernel Time Synchronisation...
[    3.500837] systemd[1]: Mounted POSIX Message Queue File System.
[    3.500872] systemd[1]: Mounted Kernel Debug File System.
[    3.500896] systemd[1]: Mounted Kernel Trace File System.
[    3.500919] systemd[1]: Mounted Variable Directory.
[    3.501006] systemd[1]: Finished Create List of Static Device Nodes.
[    3.501076] systemd[1]: modprobe@configfs.service: Deactivated successfully.
[    3.501143] systemd[1]: Finished Load Kernel Module configfs.
[    3.501218] systemd[1]: modprobe@drm.service: Deactivated successfully.
[    3.501273] systemd[1]: Finished Load Kernel Module drm.
[    3.501340] systemd[1]: modprobe@fuse.service: Deactivated successfully.
[    3.501392] systemd[1]: Finished Load Kernel Module fuse.
[    3.501474] systemd[1]: Finished Show Version.
[    3.501983] systemd[1]: Mounting FUSE Control File System...
[    3.502269] systemd[1]: Mounting Kernel Configuration File System...
[    3.502457] systemd[1]: Finished Create Persistent Log Directory on /storage and rotate large logs.
[    3.503209] systemd[1]: Persistent Log Storage was skipped because all trigger condition checks failed.
[    3.503312] systemd[1]: Finished Setup NTP servers for timesyncd.
[    3.504740] systemd[1]: Mounted FUSE Control File System.
[    3.504779] systemd[1]: Mounted Kernel Configuration File System.
[    3.509918] systemd[1]: Finished Load Kernel Modules.
[    3.510437] systemd[1]: Starting Apply Kernel Variables...
[    3.515608] systemd[1]: Finished Apply Kernel Variables.
[    3.539025] systemd[1]: Finished Coldplug All udev Devices.
[    3.547274] systemd[1]: Finished Mounting swapfile.
[    3.547325] systemd[1]: Reached target Swaps.
[    3.547831] systemd[1]: Mounting Temporary Directory /tmp...
[    3.549413] systemd[1]: Mounted Temporary Directory /tmp.
[    3.549446] systemd[1]: Reached target Local File Systems.
[    3.549793] systemd[1]: Starting Setup machine-id...
[    3.558307] systemd[1]: Finished Setup machine-id.
[    3.558806] systemd[1]: Starting Journal Service...
[    3.559056] systemd[1]: Starting Create Static Device Nodes in /dev...
[    3.562434] systemd[1]: Finished Create Static Device Nodes in /dev.
[    3.573182] systemd-journald[365]: Data hash table of /run/log/journal/98626b9930184724b0e20606f52cf421/system.journal has a fill level at 75.0 (1536 of 2047 items, 524288 file size, 341 bytes per hash table item), suggesting rotation.
[    3.573185] systemd-journald[365]: /run/log/journal/98626b9930184724b0e20606f52cf421/system.journal: Journal header limits reached or header out-of-date, rotating.
[    3.579087] systemd[1]: Started Journal Service.
[    3.582451] systemd-journald[365]: Received client request to flush runtime journal.
[    4.108024] systemd-journald[365]: Data hash table of /run/log/journal/98626b9930184724b0e20606f52cf421/system.journal has a fill level at 75.1 (1538 of 2047 items, 524288 file size, 340 bytes per hash table item), suggesting rotation.
[    4.108028] systemd-journald[365]: /run/log/journal/98626b9930184724b0e20606f52cf421/system.journal: Journal header limits reached or header out-of-date, rotating.
[   15.253613] systemd-journald[365]: Failed to write entry (20 items, 631 bytes), rotating before retrying: Argument list too long
[   15.594383] systemd-journald[365]: Failed to write entry (20 items, 627 bytes), rotating before retrying: Argument list too long
[   16.052220] systemd-journald[365]: Failed to write entry (20 items, 662 bytes), rotating before retrying: Argument list too long
[   16.357800] systemd-journald[365]: Failed to write entry (20 items, 607 bytes), rotating before retrying: Argument list too long
[   16.660732] systemd-journald[365]: Failed to write entry (20 items, 868 bytes), rotating before retrying: Argument list too long
[   26.597820] systemd-journald[365]: Failed to write entry (20 items, 626 bytes), rotating before retrying: Argument list too long
[   26.602164] systemd-journald[365]: Failed to write entry (20 items, 658 bytes), rotating before retrying: Argument list too long
[   26.607063] systemd-journald[365]: Failed to write entry (20 items, 644 bytes), rotating before retrying: Argument list too long
[   26.611182] systemd-journald[365]: Failed to write entry (20 items, 615 bytes), rotating before retrying: Argument list too long
[   35.539711] systemd-journald[365]: Failed to write entry (29 items, 700 bytes), rotating before retrying: Argument list too long
[   36.847395] systemd-journald[365]: Failed to write entry (20 items, 681 bytes), rotating before retrying: Argument list too long
[   36.852076] systemd-journald[365]: Failed to write entry (20 items, 615 bytes), rotating before retrying: Argument list too long
[   36.856307] systemd-journald[365]: Failed to write entry (20 items, 610 bytes), rotating before retrying: Argument list too long
[   36.860612] systemd-journald[365]: Failed to write entry (20 items, 606 bytes), rotating before retrying: Argument list too long
[ 3964.226965] systemd-journald[365]: Failed to write entry (23 items, 744 bytes), rotating before retrying: Argument list too long
[17932.975067] systemd-journald[365]: Failed to write entry (23 items, 726 bytes), rotating before retrying: Argument list too long
[29253.557421] systemd-journald[365]: Failed to write entry (20 items, 884 bytes), rotating before retrying: Argument list too long
[38320.572867] systemd-journald[365]: Failed to write entry (22 items, 738 bytes), rotating before retrying: Argument list too long
[46825.097917] systemd-journald[365]: Failed to write entry (20 items, 849 bytes), rotating before retrying: Argument list too long
```

- further info in https://github.com/LibreELEC/LibreELEC.tv/issues/6029

### PR DESCRIPTION
**Pull request by daandemeyer**
The previous message was confusing errors. When we're rotating because
we've reached the file size limit, let's log a better message.

Fixes #22007.

### CODE REVIEW

File: src/journal/journald-server.c [hunk 1]
```diff
@@ -853,7 +853,10 @@ static void write_to_journal(Server *s, uid_t uid, struct iovec *iovec, size_t n
                 return;
         }
 
-        log_info_errno(r, "Failed to write entry (%zu items, %zu bytes), rotating before retrying: %m", n, IOVEC_TOTAL_SIZE(iovec, n));
+        if (r == -E2BIG)
+                log_info("Journal file %s is full, rotating to a new file", f->file->path);
+        else
+                log_info_errno(r, "Failed to write entry (%zu items, %zu bytes), rotating before retrying: %m", n, IOVEC_TOTAL_SIZE(iovec, n));
```
Comment (yuwata) [inline src/journal/journald-server.c]: Maybe, it is better to mention the filename here?

**Review by yuwata — APPROVED** [review]
LGTM. One minor suggestion.

File: src/journal/journald-server.c [hunk 2]
```diff
@@ -853,7 +853,10 @@ static void write_to_journal(Server *s, uid_t uid, struct iovec *iovec, size_t n
                 return;
         }
 
-        log_info_errno(r, "Failed to write entry (%zu items, %zu bytes), rotating before retrying: %m", n, IOVEC_TOTAL_SIZE(iovec, n));
+        if (r == -E2BIG)
+                log_info("Journal file %s is full, rotating to a new file", f->file->path);
```
Comment (yuwata) [inline src/journal/journald-server.c]: Maybe, `log_debug()` is enough in this case?

Comment (daandemeyer) [reply src/journal/journald-server.c]: Having a log message when a file was rotated is quite useful. Unless an extreme amount of data is being logged, this message shouldn't trigger all that often so I don't think it hurts to keep it at info.

Comment (daandemeyer) [reply src/journal/journald-server.c]: Nvm, this could actually be triggered very often depending on what file size limits are configured. Downgraded to log_debug()

**Comment by keszybz** [comment]
LGTM too.
