### PR TITLE
vmspawn: use indexed loop

### LINKED ISSUE #40380: build failure on (32bit) s390, [-Werror=format=]
### systemd version the issue has been seen with

259

### Used distribution

Gentoo

### Linux kernel version used

6.8.9-gentoo

### CPU architectures issue was seen on

other

### Component

systemd-vmspawn

### Expected behaviour you didn't see

systemd builds

### Unexpected behaviour you saw

```
FAILED: [code=1] systemd-vmspawn.p/src_vmspawn_vmspawn.c.o 
s390-ibm-linux-gnu-gcc -Isystemd-vmspawn.p -Isrc/basic -I../systemd-259/src/basic -Isrc/fundamental -I../systemd-259/src/fundamental -Isrc/systemd -I../systemd-259/src/systemd -Isrc/version -I../systemd-259/src/version -I../systemd-259/src/libsystemd/sd-bus -I../systemd-259/src/libsystemd/sd-common -I../systemd-259/src/libsystemd/sd-device -I../systemd-259/src/libsystemd/sd-event -I../systemd-259/src/libsystemd/sd-hwdb -I../systemd-259/src/libsystemd/sd-id128 -Isrc/libsystemd/sd-journal -I../systemd-259/src/libsystemd/sd-journal -I../systemd-259/src/libsystemd/sd-json -I../systemd-259/src/libsystemd/sd-netlink -I../systemd-259/src/libsystemd/sd-network -I../systemd-259/src/libsystemd/sd-path -I../systemd-259/src/libsystemd/sd-resolve -I../systemd-259/src/libsystemd/sd-varlink -Isrc/shared -I../systemd-259/src/shared -Isrc/vmspawn -I../systemd-259/src/vmspawn -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu17 -Wno-missing-field-initializers -Wno-unused-parameter -Wno-nonnull-compare -Warray-bounds -Warray-bounds=2 -Wdate-time -Wendif-labels -Werror=bool-compare -Werror=discarded-qualifiers -Werror=flex-array-member-not-at-end -Werror=format=2 -Werror=format-signedness -Werror=implicit-function-declaration -Werror=implicit-int -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=missing-declarations -Werror=missing-parameter-name -Werror=missing-prototypes -Werror=overflow -Werror=override-init -Werror=pointer-sign -Werror=return-type -Werror=sequence-point -Werror=shift-count-overflow -Werror=shift-overflow=2 -Werror=strict-flex-arrays -Werror=undef -Wfloat-equal -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-aliasing=2 -Wstrict-prototypes -Wsuggest-attribute=noreturn -Wunterminated-string-initialization -Wunused-function -Wwrite-strings -Wzero-as-null-pointer-constant -Wzero-length-bounds -fdiagnostics-show-option -fno-common -fstack-protector -fstack-protector-strong -fstrict-flex-arrays=3 --param=ssp-buffer-size=4 -Wno-maybe-uninitialized -Wno-unused-result -ftrivial-auto-var-init=zero -Werror=shadow -O2 -pipe -fno-strict-aliasing -fstrict-flex-arrays=1 -fvisibility=hidden -include config.h -isystem../systemd-259/src/include/override -isystemsrc/include/override -isystem../systemd-259/src/include/uapi -MD -MQ systemd-vmspawn.p/src_vmspawn_vmspawn.c.o -MF systemd-vmspawn.p/src_vmspawn_vmspawn.c.o.d -o systemd-vmspawn.p/src_vmspawn_vmspawn.c.o -c ../systemd-259/src/vmspawn/vmspawn.c
../systemd-259/src/vmspawn/vmspawn.c: In function ‘run_virtual_machine’:
../systemd-259/src/vmspawn/vmspawn.c:2438:41: error: format ‘%zi’ expects argument of type ‘signed size_t’, but argument 3 has type ‘int’ [-Werror=format=]
 2438 |                 if (asprintf(&id, "mnt%zi", mount - arg_runtime_mounts.mounts) < 0)
      |                                       ~~^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         |         |
      |                                         long int  int
      |                                       %i
cc1: some warnings being treated as errors
```

### Steps to reproduce the problem

Try to build systemd-259 in a 32bit s390 environment 
(In this case, the Gentoo installation stage builder, which effectively uses a 32bit chroot on a 64bit s390x machine.)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #40380.

### CODE REVIEW

File: src/vmspawn/vmspawn.c [hunk 1]
```diff
@@ -2444,7 +2444,7 @@ static int run_virtual_machine(int kvm_device_fd, int vhost_device_fd) {
                         return log_oom();
 
                 _cleanup_free_ char *id = NULL;
-                if (asprintf(&id, "mnt%zi", mount - arg_runtime_mounts.mounts) < 0)
+                if (asprintf(&id, "mnt%ti", mount - arg_runtime_mounts.mounts) < 0)
```
Comment (YHNdnzj) [inline src/vmspawn/vmspawn.c]: hmm, sounds like we should use the index of the mount rather than pointer offset?

Comment (yuwata) [reply src/vmspawn/vmspawn.c]: OK. Let's do so.

File: src/vmspawn/vmspawn.c [hunk 2]
```diff
@@ -2408,18 +2408,20 @@ static int run_virtual_machine(int kvm_device_fd, int vhost_device_fd) {
         if (r < 0)
                 return log_oom();
 
-        FOREACH_ARRAY(mount, arg_runtime_mounts.mounts, arg_runtime_mounts.n_mounts) {
+        for (size_t j = 0; j < arg_runtime_mounts.n_mounts; j++) {
                 _cleanup_free_ char *listen_address = NULL;
                 _cleanup_(fork_notify_terminate) PidRef child = PIDREF_NULL;
 
+                RuntimeMount *m = arg_runtime_mounts.mounts + j;
```
Comment (YHNdnzj) [inline src/vmspawn/vmspawn.c]: I'd just place this at the very beginning of the loop body, i.e. above listen_address

**Comment by yuwata** [comment]
BTW, maybe better to introduce FOREACH_ARRAY_WITH_INDEX() or so later.

**Comment by poettering** [comment]
lgtm
