### PR TITLE
boot: Strip boot counter from entry id

### LINKED ISSUE #38813: systemd-boot uses wrong id for boot entries when boot counting is enabled
### systemd version the issue has been seen with

257.7

### Used distribution

openSUSE MicroOS

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

Expected behavior: systemd-boot removes the boot counting from the id when handling boot entries. I.e. boot entry `/boot/efi//loader/entries/opensuse-microos-6.16.3-1-default-4+3.conf` should have `opensuse-microos-6.16.3-1-default-4.conf` as `id` (as shown by `bootctl list`) instead of `opensuse-microos-6.16.3-1-default-4+3.conf`). This issue invalidates the reported boot entries (in EFI var `LoaderEntries`); in addition, the default entry and the selected entry don't work as intended, as bootctl and systemd-boot ids differs.

The id is generated [here](https://github.com/systemd/systemd/blob/67573e8b8ba2ef7df8640553c16beb8b60684c1d/src/boot/boot.c#L1398), where the file is used as is and the boot counting is not removed.

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

- Enable Automatic Boot Assessment: `echo "3" > /etc/kernel/tries`
- Create a new entry with the boot count enabled
- Reboot to enter systemd-boot
- Boot into a different entry to keep the boot counting enabled

In addition, set the default entry (`bootctl set-default`) to the id shown by `bootctl list`, i.e. without the boot count in it, then reboot into systemd-boot, where there won't be any default.

If needed I can give detailed steps to reproduce it on MicroOS.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# bootctl list
         type: Boot Loader Specification Type #1 (.conf)
        title: openSUSE MicroOS 20250901 (4@6.16.3-1-default) (default) (not reported/new)
           id: opensuse-microos-6.16.3-1-default-4.conf
       source: /boot/efi//loader/entries/opensuse-microos-6.16.3-1-default-4+3.conf (on the EFI System Partition)
        tries: 3 left
     sort-key: opensuse-microos
      version: 4@6.16.3-1-default
        linux: /boot/efi//opensuse-microos/6.16.3-1-default/linux-69aad88811b8e5f86cfd942dd2209d5f0f5a831d
       initrd: /boot/efi//opensuse-microos/6.16.3-1-default/initrd-4c420909fedb54d346d458bde5d17ea8e4c7b252
      options: quiet systemd.show_status=yes console=ttyS0,115200 console=tty0 ignition.platform.id=qemu security=selinux sel>

         type: Reported by Boot Loader
        title: opensuse-microos-6.16.3-1-default-4+3.conf (reported/absent)
           id: opensuse-microos-6.16.3-1-default-4+3.conf
       source: /sys/firmware/efi/efivars/LoaderEntries-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f (on the EFI System Partition)
## Content of /sys/firmware/efi/efivars/LoaderEntries-*
opensuse-microos-6.16.3-1-default-5.conf
opensuse-microos-6.16.3-1-default-4+3.conf
opensuse-microos-6.16.3-1-default-3.conf
opensuse-microos-6.16.3-1-default-2.conf
opensuse-microos-6.16.3-1-default-1.conf
auto-efi-default
auto-reboot-to-firmware-setup
```

### PR DESCRIPTION
**Pull request by danyspin97**
When boot counter is found in the boot entry filename, strip it from the id to match bootctl id.

Fixes #38813.

### CODE REVIEW

File: src/boot/boot.c [hunk 1]
```diff
@@ -1395,13 +1399,16 @@ static void boot_entry_add_type1(
...
-        strtolower16(entry->id);
-
-        config_add_entry(config, entry);
 
         if (path)
                 boot_entry_parse_tries(entry, path, file, u".conf");
+
+        if (!entry->id) {
+                entry->id = xstrdup16(file);
+        }
```
Comment (poettering) [inline src/boot/boot.c]: in our codebase we do not use {} for single line if blocks, see coding style.

**Comment by poettering** [comment]
lgtm, just this coding style nitpick

**Comment by keszybz** [comment]
Please update.

File: src/boot/boot.c (hunk 1 above)
Comment (danyspin97) [reply src/boot/boot.c]: Fixed.

**Review by keszybz — APPROVED** [review]
LGTM.

**Comment by keszybz** [comment]
Backport queued for v258.1
