### PR TITLE
Working version of `telinit 0` - fixes #6482

### LINKED ISSUE #6482: systemctl's fallback function talk_initctl() doesn't work for runlevel 0 (shutdown)
### Submission type

 - Bug report

### systemd version the issue has been seen with

v234+git-9fcaa574

https://github.com/systemd/systemd/blob/9fcaa574f07c3159281584643b573a80b5c1a843/src/systemctl/systemctl.c#L8156

### Used distribution

Fedora 26

### In case of bug report: Steps to reproduce the problem

I saw two weird things about this code.

1. Actions omitted from the table in `action_to_runlevel()` will default to runlevel 0 (system shutdown).  Both ACTION_DEFAULT and ACTION_EMERGENCY can be directed to this function, and are not in the table.
2. When `action_to_runlevel()` returns runlevel 0 (system shutdown), `talk_initctl()` treats this as a failure.  

The result of the current code is that `talk_initctl()` can send requests for reboot, single user, multi-user or graphical runlevels, but not the runlevel for shutdown.

Replacing the table with a switch/case statement with a `default` would work, but might be a bit verbose.  Another way to write the table would be as a list of (action, runlevel) pairs, which you can iterate through.

### PR DESCRIPTION
**Pull request by sourcejedi**
Tested by commenting out the first half of `start_with_fallback()`.

### CODE REVIEW

File: src/systemctl/systemctl.c [hunk 1]
```diff
@@ -8574,8 +8574,6 @@ int main(int argc, char*argv[]) {
         case ACTION_RUNLEVEL4:
         case ACTION_RUNLEVEL5:
         case ACTION_RESCUE:
-        case ACTION_EMERGENCY:
-        case ACTION_DEFAULT:
```
Comment (poettering) [inline src/systemctl/systemctl.c:8578]: instead of dropping this without replacement, I think it would be good, adding it in a comment to some later location in this switch statement, and adding to that comment why we don#t care for these actions here. Otherwise the next time somebody looks at this statement he might think we forgot something there..

**Comment by poettering** [comment]
@sourcejedi hmm, given you closed #6482 now, should we also close #6638, or is there something in it you'd like us to merge?

File: src/systemctl/systemctl.c (hunk 1 above)
Comment (sourcejedi) [reply src/systemctl/systemctl.c:8578]: So `start_with_fallback()` works correctly even for actions without a fallback.  In that sense it's fine to have these 2 cases.  But still, they're never used.

There are... several different subsets of possible actions, depending where it's used.  It definitely confused me :).  Used here, it already implicitly excludes four actions:

        ACTION_EXIT,
        ACTION_SUSPEND,
        ACTION_HIBERNATE,
        ACTION_HYBRID_SLEEP,

It is easier to understand if the unused actions are dropped, so the switch correctly reflects `systemctl` v.s. all the legacy commands.

You might have a point about this needing to be more explicit though.  I might have stared at this too long by now, to consider what it looks like to a new reader :).  I'm sending a more verbose version, as you suggest.
