### PR TITLE
sd-device: fix crash if a device has many tags

### LINKED ISSUE #2954: udevd crash with lots of tags
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

229 and current master
### Used distribution

Ubuntu, upstream master build (Downstream report: https://launchpad.net/bugs/1564976)
### Steps to reproduce the problem

A colleague of mine did some performance measurements for using udev device tags, as they'd like to use them for a language to describe access control. During that we noticed that udevd crashes if you try to add a large number of tags:

```
for i in `seq 10000`; do printf 'KERNEL=="kmsg", TAG+="test%i"\n' $i; done > /run/udev/rules.d/70-manytags.rules
udevadm trigger --sysname-match=kmsg --verbose
```

Then udevd crashes with

```
worker [13738] terminated by signal 11 (Segmentation fault)
#0  0x00005555555f0fed in device_properties_prepare (device=0x555555683600) at src/libsystemd/sd-device/sd-device.c:1486
        _appendees_ = {
          0x7fffff801d80 ":test7679:test4364:test1143:test5855:test7318:test5305:test7786:test4511:test5674:test4140:test845:test2656:test1697:test3090:test4065:test2086:test8131:test4315:test5852:test1207:test81:test1387:test"..., 0x55555562642c ":", 
          0x555555674ab0 "test3837"}
        _len_ = 12166
        _i_ = 0
        _d_ = 0x7fffff7fede0 <error: Cannot access memory at address 0x7fffff7fede0>
        _p_ = 0x7fffff7fede0 <error: Cannot access memory at address 0x7fffff7fede0>
        tags = 0x7fffff801d80 ":test7679:test4364:test1143:test5855:test7318:test5305:test7786:test4511:test5674:test4140:test845:test2656:test1697:test3090:test4065:test2086:test8131:test4315:test5852:test1207:test81:test1387:test"...
        tag = 0x555555674ab0 "test3837"
        r = 0
        __PRETTY_FUNCTION__ = "device_properties_prepare"
```

This crashes in src/libsystemd/sd-device/sd-device.c, device_properties_prepare():

```
                char *tags = NULL;
                while ((tag = sd_device_get_tag_next(device)))
                        tags = strjoina(tags, ":", tag);
```

strjoina() (which essentially is alloca() with some automatic size determination) is very efficient with a few tags, but it has an undefined upper bound and undefined behaviour on stack overflow, i. e. there is no way to find out when it failed. In most cases of where systemd uses `strjoina()` the number of items is known exactly and small, but I don't think it's a good idea to use `strjoina()` in an unbounded loop like this as there's no safe way to determine overflows.

### PR DESCRIPTION
**Pull request by martinpitt**
`strjoina()` is unsafe to be used in an unbounded loop as `alloca()` has no error reporting. Thus devices with a large number of tags trigger a segfault in device_properties_prepare() due to overflowing the stack.

Rewrite the building of the "tags" string using `greedy_realloc()` and `strpcpy()` to work with arbitrary many tags. This also avoids re-copying the entire string in each loop iteration.

Before this commit we always appended one ":". Change this to start with an iniital ":" and for each tag append instead of prepend a ":". This unifies what happens for the first and all subsequent tags so that we can use a for loop.

Fixes #2954

### CODE REVIEW

**Comment by ronnychevalier** [comment]
Shouldn't this fix be also applied for devlinks just above (line [1468](https://github.com/martinpitt/systemd/blob/master/src/libsystemd/sd-device/sd-device.c#L1468))?

File: src/libsystemd/sd-device/sd-device.c [hunk 1]
```diff
@@ -1475,17 +1475,20 @@ static int device_properties_prepare(sd_device *device) {
...
-
-                while ((tag = sd_device_get_tag_next(device)))
-                        tags = strjoina(tags, ":", tag);
+                if (!greedy_realloc((void**) &tags, &tags_allocated, 2, 1))
+                        return -ENOMEM;
+                tags_end = stpcpy(tags, ":");
 
-                tags = strjoina(tags, ":");
+                for (tag = sd_device_get_tag_first(device); tag; tag = sd_device_get_tag_next(device)) {
+                        if (!greedy_realloc((void**) &tags, &tags_allocated, (tags_end - tags) + strlen(tag) + 1, 1))
```
Comment (poettering) [inline src/libsystemd/sd-device/sd-device.c]: greedy_realloc() is kinda an internal function. The GREEDY_REALLOC() macro (that wraps it) should really be called instead. Is there are reason you caller the fucntion instead of the macro?

**Comment by poettering** [comment]
looks ok otherwise

**Comment by martinpitt** [comment]
> Shouldn't this fix be also applied for devlinks just above (line 1468)?

Yes, I think it should. I'll add another commit which does that.

> Is there are reason you caller the fucntion instead of the macro?

Nothing except my ignorance; I'll change it to use the macro, thanks for reviewing!

**Comment by martinpitt** [comment]
I now changed the corresponding code for `DEVLINKS`, and also fixed a bug: We mustn't permanently keep `char* <string>_end` pointers as the realloc might change the initial pointer and thus the end pointer becomes invalid. So this keeps track of the actual length instead.

Is there a better pattern than

```
char *e;
e = stpcpy(tags, ...);
tags_len = e - tags;
```

? Of course it could be written on one line like

```
tags_len = stpcpy(tags, ...) - tags;
```

but IMHO this is harder to read and understand.

**Comment by filbranden** [comment]
Instead of building a string... Why not build a strv array and use strv_join() to concatenate all of them in the end? That takes away most of the pointer arithmetic. It can also be potentially more efficient (in terms of copies) since strv_join will calculate the whole length and allocate the buffer only once. (Though probably not the case here since you'll likely end up strdup'ing all strings as well, but still...)

Would you like to give that a try?

File: src/libsystemd/sd-device/sd-device.c [hunk 2]
```diff
@@ -1457,15 +1457,25 @@ static int device_properties_prepare(sd_device *device) {
...
+                                return -ENOMEM;
+                        e = stpcpy(devlinks, devlink);
+                        devlinks_len = e - devlinks;
+
+                        while ((devlink = sd_device_get_devlink_next(device))) {
+                                if (!GREEDY_REALLOC(devlinks, devlinks_allocated, devlinks_len + strlen(devlink) + 2))
+                                        return -ENOMEM;
+                                e = stpcpy(stpcpy(devlinks + devlinks_len, " "), devlink);
+                                devlinks_len = e - devlinks;
+                        }
```
Comment (keszybz) [inline src/libsystemd/sd-device/sd-device.c]: It seems wasteful to repeat the whole logic... What about:

```
for (devlink = sd_device_get_devlink_first(device);
      devlink; 
      devlink = sd_device_get_devlink_next(device)) {
   if (!GREEDY_REALLOC(devlinks, devlinks_allocated, devlinks_len + strlen(devlink) + 2))
         return -ENOMEM;
   if (devlinks_len > 0)
        e = stpcpy(devlinks + devlinks_len++, " ");
   e = stpcpy(devlinks + devlinks_len, devlink);
```

?

File: src/libsystemd/sd-device/sd-device.c [hunk 3]
```diff
@@ -1475,17 +1485,22 @@ static int device_properties_prepare(sd_device *device) {
...
+                e = stpcpy(tags, ":");
+                tags_len = e - tags;
 
-                tags = strjoina(tags, ":");
+                for (tag = sd_device_get_tag_first(device); tag; tag = sd_device_get_tag_next(device)) {
+                        if (!GREEDY_REALLOC(tags, tags_allocated, tags_len + strlen(tag) + 1))
+                                return -ENOMEM;
+                        e = stpcpy(stpcpy(tags + tags_len, tag), ":");
+                        tags_len = e - tags;
+                }
```
Comment (keszybz) [inline src/libsystemd/sd-device/sd-device.c:1499]: And similarly here?

**Comment by keszybz** [comment]
I don't think allocating many small strings will be more efficient. Current version should actually be quite fast, with O(1) allocations and than a bunch of string copies.

File: src/libsystemd/sd-device/sd-device.c (hunk 2 above)
Comment (martinpitt) [inline src/libsystemd/sd-device/sd-device.c]: Seems fine, this would make it similar to the `tags` below, except with the special-casing of not prepending a space with the first entry. I'll change it accordingly tomorrow morning.

File: src/libsystemd/sd-device/sd-device.c (hunk 3 above)
Comment (martinpitt) [inline src/libsystemd/sd-device/sd-device.c:1499]: I don't understand what you want me to change here. For `tags` it already uses an "unified" for loop instead of first/others special cases?

Comment (keszybz) [inline src/libsystemd/sd-device/sd-device.c:1499]: You can move lines 1493-1496 into the loop.

File: src/libsystemd/sd-device/sd-device.c (hunk 2 above)
Comment (keszybz) [inline src/libsystemd/sd-device/sd-device.c]: I'm not sure I understand the comment. The first entry has to be special cased, and that's what my proposed version does.

File: src/libsystemd/sd-device/sd-device.c (hunk 3 above)
Comment (martinpitt) [inline src/libsystemd/sd-device/sd-device.c:1499]: Not without making the code significantly more complicated -- note that the loop might run zero times, but even then we _still_ want `tags` to be ":"

**Comment by martinpitt** [comment]
Force-pushed new commit with @keszybz' suggestion. This is indeed simpler now, thanks!
