### PR TITLE
Network: update acquired dhcp6 prefix routes

### LINKED ISSUE #16356: systemd-networkd does not appear to reset the valid/preferred lifetime of delegated IPv6 prefixes when doing a DHCPv6 RENEW, leading to loss of IPv6 connectivity
**systemd version the issue has been seen with**
> git HEAD

**Used distribution**
 > Ubuntu

**Expected behaviour you didn't see**
 > Valid and preferred lifetimes for IPv6 delegated prefixes as announced in RAs should be reset after a DHCPv6 RENEW renews the lease.

**Unexpected behaviour you saw**
 > The lifetimes continue decrementing towards 0, causing loss of IPv6 connectivity for devices behind the router when 0 is reached.

**Steps to reproduce the problem**
1. Set up systemd-networkd to do DHCPv6 PD and delegate the prefixes to one or more interfaces.
2. Watch as the valid and preferred lifetimes for the delegated prefixes as shown by "rdisc6" continue to decrement toward 0 even after the DHCPv6 client renews the lease.
3. Watch as IPv6 connectivity stops working when the lifetimes reach 0.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #16356.

cc @andir.

### CODE REVIEW

File: src/network/networkd-dhcp6.c [hunk 1]
```diff
@@ -112,28 +112,24 @@ static int dhcp6_get_preferred_delegated_prefix(
                 log_link_debug(link, "The requested prefix %s is available. Using it.",
                                strnull(assigned_buf));
                 return 0;
```
Comment (keszybz) [inline src/network/networkd-dhcp6.c:113]: Right, there's `return 0` so dropping the `else` makes no functional difference.
