### PR TITLE
bootctl: do not fail when the same file is updated multiple times

### LINKED ISSUE #33392: bootctl recognizes the file it just updated as already up-to-date and fails
### systemd version the issue has been seen with

256

### Used distribution

Archlinux

### Linux kernel version used

6.9.4-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

On upgrading to systemd 256 and running `bootctl update --no-variables` the command failed with following output:
```
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed" to "/efi/EFI/systemd/systemd-bootx64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed" to "/efi/EFI/BOOT/BOOTX64.EFI".
Skipping "/efi/EFI/BOOT/BOOTX64.EFI", same boot loader version in place already.
```

### Steps to reproduce the problem

1. Install systemd-boot in `/EFI/BOOT/BOOTX64.EFI` on the EFI partition
2. Run `bootctl update`

This occurs because as of #30418 systemd-boot will first update `/EFI/BOOT/BOOTX64.EFI` and then update every copy of itself in `/EFI/BOOT`, including the file that was just updated, and considers finding a file with the same version as the update target to be an error.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a regression caused by 929f41c6528fb630753d4e2f588a8eb6c2f6a609.
Fixes #33392.

### CODE REVIEW

File: src/boot/bootctl-install.c [hunk 1]
```diff
@@ -191,14 +191,14 @@ static int version_check(int fd_from, const char *from, int fd_to, const char *t
         if (r == -ESRCH)
                 return log_notice_errno(r, "Source file \"%s\" does not carry version information!", from);
         if (r < 0)
-                return r;
+                return log_error_errno(r, "Failed to get version information of source file \"%s\": %m", from);
```
Comment (poettering) [inline src/boot/bootctl-install.c]: hmm, get_file_version() itself is all over the place with log messages, some error codes are logged at LOG_DEBUG level, others above it.

So I guess this fix doesn't make things really worse, but it also doesn't clean up things properly, as it means: before we had some errors we wouldn't log about at all, and now we have some errors we'll log about twice...

File: src/boot/bootctl-install.c [hunk 2]
```diff
@@ -334,6 +337,9 @@ static int update_efi_boot_binaries(const char *esp_path, const char *source_pat
                 _cleanup_close_ int fd = -EBADF;
                 _cleanup_free_ char *v = NULL;
 
+                if (de->d_type != DT_REG)
```
Comment (poettering) [inline src/boot/bootctl-install.c]: we can't expct d_type to always be initialized, not all file systems support that. Hence, please change to `if (!IN_SET(de->d_type, DT_REG, DT_UNKNOWN))`…

File: src/boot/bootctl-install.c [hunk 3]
```diff
@@ -334,6 +337,9 @@ static int update_efi_boot_binaries(const char *esp_path, const char *source_pat
...
+                        continue;
+
                 if (!endswith_no_case(de->d_name, ".efi"))
                         continue;
```
Comment (poettering) [inline src/boot/bootctl-install.c]: actually, we should be probably more careful with weird inode types here, i.e. at least open the files below with O_NONBLOCK|O_NOCTTY|O_NOFOLLOW in case we hit some weird stuff such as tty device nodes, where we really shouldn't block.

**Comment by poettering** [comment]
hmm, there are some other issues i think need addressing in that original PR, to keep track of that i filed #33413

File: src/boot/bootctl-install.c (hunk 2 above)
Comment (poettering) [reply src/boot/bootctl-install.c]: (note that get_file_version() contains a verify_regular_file() check actually, but weirdly turns it into ESRCH, something weird is going on there)

File: src/boot/bootctl-install.c [hunk 4]
```diff
@@ -423,7 +428,7 @@ static int copy_one_file(const char *esp_path, const char *name, bool force) {
                 /* If we were installed under any other name in /EFI/BOOT, make sure we update those binaries
                  * as well. */
                 if (!force)
-                        RET_GATHER(ret, update_efi_boot_binaries(esp_path, source_path));
+                        RET_GATHER(ret, update_efi_boot_binaries(esp_path, source_path, default_dest_path));
```
Comment (poettering) [inline src/boot/bootctl-install.c]: hmm, i find it weird to pass the full path here, and then throwing it away in the calleee. I think it would make more sense to pass in only he file name.

File: src/boot/bootctl-install.c [hunk 5]
```diff
@@ -319,13 +319,14 @@ static int create_subdirs(const char *root, const char * const *subdirs) {
         return 0;
 }
 
-static int update_efi_boot_binaries(const char *esp_path, const char *source_path) {
+static int update_efi_boot_binaries(const char *esp_path, const char *source_path, const char *exclude_path) {
```
Comment (YHNdnzj) [inline src/boot/bootctl-install.c]: BTW, I think we should actually handle up-to-date binaries gracefully here. These aren't canonical paths that `bootctl install` would operate on after all, and if users copy other versions of sd-boot here for testing/other purposes we shouldn't error out.

**Comment by arianvp** [comment]
The linked commit in the description links to a documentation fix. Wrong commit?

**Comment by ElvishJerricco** [comment]
NixOS has been shipping a revert of f8b02a56febf14adf2474875a1b6625f1f346a6f for a couple of months now due to #33392. We tried to ship this PR as a fix, but it led to [this issue](https://github.com/NixOS/nixpkgs/issues/331170), so we instead reverted. We rely on `bootctl` to exit when something goes wrong, so we can't use `--graceful` as a workaround. I'm not entirely sure why shipping this PR led to that issue; we didn't spend much time investigating since it wasn't merged upstream. But if there's anything I can do to help this PR along and resolve the issue we had with it, I would love to have this merged so we can remove our revert patch.

**Comment by ElvishJerricco** [comment]
What can we do to progress this? NixOS has been reverting f8b02a56febf14adf2474875a1b6625f1f346a6f since we shipped 257 because of this bug, and the fix in this PR led to more problems that I linked above. But now reverting f8b02a56febf14adf2474875a1b6625f1f346a6f doesn't cleanly apply so it's going to take some work to revert. Would much prefer to have a fix.

File: src/boot/bootctl-install.c [hunk 6]
```diff
@@ -334,9 +338,16 @@ static int update_efi_boot_binaries(const char *esp_path, const char *source_pat
...
                 _cleanup_free_ char *v = NULL;
 
+                if (de->d_type != DT_REG)
+                        continue;
+
                 if (!endswith_no_case(de->d_name, ".efi"))
                         continue;
 
+                /* Skip the file that is already updated. */
+                if (path_equal_filename(de->d_name, exclude_path))
```
Comment (ElvishJerricco) [inline src/boot/bootctl-install.c]: This doesn't account for the case insensitivity of the file system. That's what caused [the NixOS bug](https://github.com/NixOS/nixpkgs/issues/331170) that forced us not to use this PR.

```suggestion
                if (inode_same_at(dirfd(d), de->d_name, 0, exclude_path, 0))
```

This seems to work, and we may be start shipping this in NixOS soon so we no longer have to revert f8b02a56febf14adf2474875a1b6625f1f346a6f

**Comment by yuwata** [comment]
Sorry for late response, and thank you for the review and suggestions.
I took @YHNdnzj's suggestion. PTAL.

**Comment by bluca** [comment]
```
../src/bootctl/bootctl-install.c:354:38: error: unused variable 'v' [-Werror,-Wunused-variable]
                _cleanup_free_ char *v = NULL;
```

**Review by bluca — APPROVED** [review]

**Comment by arianvp** [comment]
Thanks for the collab on this! always great to be dropping patches and moving a bit closer to upstream.
