### PR TITLE
resolve: fix memleak and use-after-free, and several cleanups

### LINKED ISSUE #22427: systemd-resolved crash
**systemd version the issue has been seen with**
 > 249.9-1.fc35-x86_64

**Used distribution**
 > Fedora Silverblue 35

**Linux kernel version used** (`uname -a`)

 > Linux rocinante 5.15.18-200.fc35.x86_64 #1 SMP Sat Jan 29 13:54:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > less crashes

**Unexpected behaviour you saw**
 > lots of crashes

**Steps to reproduce the problem**
 > no idea, but I'm getting A LOT of crashes.
coredumpctl list
```
Fri 2022-02-04 22:49:10 EST     888  990  989 SIGABRT inaccessible /usr/lib/systemd/systemd-resolved                      >
Fri 2022-02-04 23:04:10 EST   30897  990  989 SIGSEGV inaccessible /usr/lib/systemd/systemd-resolved                      >
Fri 2022-02-04 23:19:11 EST   31736  990  989 SIGABRT inaccessible /usr/lib/systemd/systemd-resolved      
```
(previously I had crashes 4 times / hour but I'm not sure it's the same version, I did reboot)

**Additional program output to the terminal or log subsystem illustrating the issue**

The SIGABRT
```
coredumpctl dump
           PID: 31736 (systemd-resolve)
           UID: 990 (systemd-resolve)
           GID: 989 (systemd-resolve)
        Signal: 6 (ABRT)
     Timestamp: Fri 2022-02-04 23:19:10 EST (3min 53s ago)
  Command Line: /usr/lib/systemd/systemd-resolved
    Executable: /usr/lib/systemd/systemd-resolved
 Control Group: /system.slice/systemd-resolved.service
          Unit: systemd-resolved.service
         Slice: system.slice
       Boot ID: c18b56418c4b4a1fab091b8791a5fc99
    Machine ID: 5c2fa807ae304688bd20aee5ed0c1487
      Hostname: rocinante
       Storage: /var/lib/systemd/coredump/core.systemd-resolve.990.c18b56418c4b4a1fab091b8791a5fc99.31736.1644034750000000.zst (inaccessible)
       Message: Process 31736 (systemd-resolve) of user 990 dumped core.
                
                Found module linux-vdso.so.1 with build-id: dd9f72d7bd194bdaf5264b45aa11ecb7d35396d6
                Found module libopensc.so.8 with build-id: 44d3807ac7d8c7d65741cc0662c945ac27e9aa85
                Found module opensc-pkcs11.so with build-id: b59a39986e9a89dc398ad4c0af93e30435a10ae6
                Found module p11-kit-trust.so with build-id: c7bfa625cbb60c5db93408bbff8541b7d7206f75
                Found module libnss_altfiles.so.2 with build-id: fe5989dc31e3eb80f0a1d33b816ac9ab6a408222
                Found module libnss_systemd.so.2 with build-id: babba3904ec3983f952d1a2e49984c3d375448d8
                Found module libnss_sss.so.2 with build-id: f507413541bb0cb10590bccb2ead1bed2599c74b
                Found module libnl-3.so.200 with build-id: 9ec8cd67a8293913423a6e854ed3c21bb97ecf9e
                Found module libnl-route-3.so.200 with build-id: 25ac144713fd4d7ed0d9394a7d36c424b185fdf1
                Found module libcap-ng.so.0 with build-id: 1c7599981a7ae118996a9dfaf161e25d430bf14a
                Found module libibverbs.so.1 with build-id: ad646a9247a907209a0e0bd0c28f05d965bc976b
                Found module libpcre2-8.so.0 with build-id: 67d78ee981939e51fee33d8885ff8000552e7a3d
                Found module libeconf.so.0 with build-id: a9479b45047dac4e8b6fabfe99a01d9f4518fe55
                Found module libaudit.so.1 with build-id: ee46c59ab334973f1508e2f5e367eb53b2f5e672
                Found module libffi.so.6 with build-id: 0129f72b58e11d59546f7f207d2c90af7ebd9a5e
                Found module libz.so.1 with build-id: 5903f5c355c264403e4e7cdc66779584425ca3b8
                Found module libpcap.so.1 with build-id: d2259e63bc0fc951f7cc4d07c02d3b01a16ff76b
                Found module libattr.so.1 with build-id: 38932d6d81e2a95598ccc83ab14016fa87378891
                Found module libgmp.so.10 with build-id: 14dbc5e93375ccb760dc47c5aaecc0cdfc45a06a
                Found module libhogweed.so.6 with build-id: 288da1bb6ffaf6600c2f8a126bec247f2e9a4628
                Found module libnettle.so.8 with build-id: 62dba2572638edf8336bd4de5017fc70eaf0a567
                Found module libtasn1.so.6 with build-id: be32a4fab2585b6114471e83bf582b3df020b594
                Found module libunistring.so.2 with build-id: edcae9db236efd11e61995054ddf27a89ec6dc40
                Found module libidn2.so.0 with build-id: f3ad1b0687f5b426beed2d3d3d18aa301932f7a3
                Found module ld-linux-x86-64.so.2 with build-id: 4e2c368b1240116994daff7f0f248a01f6e53198
                Found module liblzma.so.5 with build-id: 7fec53ce7cba9489f130c99cfd3ace82e9dde0ee
                Found module libzstd.so.1 with build-id: 7984add4b0ab24869c30e19cfba3637ca295dd7b
                Found module libselinux.so.1 with build-id: f805394f993c704b949315b56c344d22dfad801f
                Found module libseccomp.so.2 with build-id: d9e37e30e12bcd8de6d550fda9c874c8870067d9
                Found module libpam.so.0 with build-id: 8ab37bc9d948cd5b1a39cad3d739942991def3c9
                Found module libp11-kit.so.0 with build-id: a7a93824ebf14980eeb37fe23c9d86dd201f947f
                Found module libcrypto.so.1.1 with build-id: 3ead607210606611d5f3398ee7e65198bd519de9
                Found module libmount.so.1 with build-id: 7f7bccf74cb835b64429e61ea0ec03cd0cb95b8b
                Found module liblz4.so.1 with build-id: fd02c4542a1ce1ad6c503b958447be1c37a4afee
                Found module libkmod.so.2 with build-id: 05f61a23314c52c5af47b36809ecf59ee9f000ef
                Found module libip4tc.so.2 with build-id: 87e7e634dae72aabee3832ecf6f2d01515e2dc7b
                Found module libcrypt.so.2 with build-id: 52fd1fd3dc3c8c13f94214c6f2d6fda0832db3d5
                Found module libcap.so.2 with build-id: 0214aa9cc6a8646eb9ec27ab7dda6a2219da6500
                Found module libblkid.so.1 with build-id: 96be27216d8d6d7ba3694ca503cd1b07f60fa539
                Found module libacl.so.1 with build-id: 24b2ced347e35fc1fbc66dfd90c65930ebce8628
                Found module libc.so.6 with build-id: f2837f792a83ba96d761c1b715570411dc0ef584
                Found module libgcc_s.so.1 with build-id: 88564abce789aa42536da1247a57ff6062d61dcb
                Found module libgcrypt.so.20 with build-id: 711d41580c5a8649a79a8430a985dac3e25b5ba2
                Found module libgnutls.so.30 with build-id: 725a333b137bd282d588279e04f20d99a3ea24c1
                Found module libm.so.6 with build-id: 47343f97c29c4e91c841e2bfd344329a264075ad
                Found module libgpg-error.so.0 with build-id: 081975d0a3416374b4883b2f1639fd3c9df42390
                Found module libsystemd-shared-249.so with build-id: ca199d8953af98d699deb587260a38d50b83fb28
                Found module systemd-resolved with build-id: 41c739bd84e8a04b62fdf6e4489d98d8e3b73e4b
                Stack trace of thread 31736:
                #0  0x00007f909b7d788c __pthread_kill_implementation (libc.so.6 + 0x8f88c)
                #1  0x00007f909b78a6a6 raise (libc.so.6 + 0x426a6)
                #2  0x00007f909b7747d3 abort (libc.so.6 + 0x2c7d3)
                #3  0x00007f909be43f0a log_assert_failed.cold (libsystemd-shared-249.so + 0x7bf0a)
                #4  0x0000565319db3aea on_query_timeout (systemd-resolved + 0x13aea)
                #5  0x00007f909bff05b8 source_dispatch (libsystemd-shared-249.so + 0x2285b8)
                #6  0x00007f909bff08ed sd_event_dispatch (libsystemd-shared-249.so + 0x2288ed)
                #7  0x00007f909bff1f48 sd_event_run (libsystemd-shared-249.so + 0x229f48)
                #8  0x00007f909bff211f sd_event_loop (libsystemd-shared-249.so + 0x22a11f)
                #9  0x0000565319dee35c run (systemd-resolved + 0x4e35c)
                #10 0x0000565319db007a main (systemd-resolved + 0x1007a)
                #11 0x00007f909b775560 __libc_start_call_main (libc.so.6 + 0x2d560)
                #12 0x00007f909b77560c __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d60c)
                #13 0x0000565319db0115 _start (systemd-resolved + 0x10115)
File "/var/lib/systemd/coredump/core.systemd-resolve.990.c18b56418c4b4a1fab091b8791a5fc99.31736.1644034750000000.zst" is not readable: Permission denied
```

The SIGSEGV
```
          PID: 30897 (systemd-resolve)
           UID: 990 (systemd-resolve)
           GID: 989 (systemd-resolve)
        Signal: 11 (SEGV)
     Timestamp: Fri 2022-02-04 23:04:10 EST (20min ago)
  Command Line: /usr/lib/systemd/systemd-resolved
    Executable: /usr/lib/systemd/systemd-resolved
 Control Group: /system.slice/systemd-resolved.service
          Unit: systemd-resolved.service
         Slice: system.slice
       Boot ID: c18b56418c4b4a1fab091b8791a5fc99
    Machine ID: 5c2fa807ae304688bd20aee5ed0c1487
      Hostname: rocinante
       Storage: /var/lib/systemd/coredump/core.systemd-resolve.990.c18b56418c4b4a1fab091b8791a5fc99.30897.1644033850000000.zst (inaccessible)
       Message: Process 30897 (systemd-resolve) of user 990 dumped core.
                
                Found module linux-vdso.so.1 with build-id: dd9f72d7bd194bdaf5264b45aa11ecb7d35396d6
                Found module libopensc.so.8 with build-id: 44d3807ac7d8c7d65741cc0662c945ac27e9aa85
                Found module opensc-pkcs11.so with build-id: b59a39986e9a89dc398ad4c0af93e30435a10ae6
                Found module p11-kit-trust.so with build-id: c7bfa625cbb60c5db93408bbff8541b7d7206f75
                Found module libnss_altfiles.so.2 with build-id: fe5989dc31e3eb80f0a1d33b816ac9ab6a408222
                Found module libnss_systemd.so.2 with build-id: babba3904ec3983f952d1a2e49984c3d375448d8
                Found module libnss_sss.so.2 with build-id: f507413541bb0cb10590bccb2ead1bed2599c74b
                Found module libnl-3.so.200 with build-id: 9ec8cd67a8293913423a6e854ed3c21bb97ecf9e
                Found module libnl-route-3.so.200 with build-id: 25ac144713fd4d7ed0d9394a7d36c424b185fdf1
                Found module libcap-ng.so.0 with build-id: 1c7599981a7ae118996a9dfaf161e25d430bf14a
                Found module libibverbs.so.1 with build-id: ad646a9247a907209a0e0bd0c28f05d965bc976b
                Found module libpcre2-8.so.0 with build-id: 67d78ee981939e51fee33d8885ff8000552e7a3d
                Found module libeconf.so.0 with build-id: a9479b45047dac4e8b6fabfe99a01d9f4518fe55
                Found module libaudit.so.1 with build-id: ee46c59ab334973f1508e2f5e367eb53b2f5e672
                Found module libffi.so.6 with build-id: 0129f72b58e11d59546f7f207d2c90af7ebd9a5e
                Found module libz.so.1 with build-id: 5903f5c355c264403e4e7cdc66779584425ca3b8
                Found module libpcap.so.1 with build-id: d2259e63bc0fc951f7cc4d07c02d3b01a16ff76b
                Found module libattr.so.1 with build-id: 38932d6d81e2a95598ccc83ab14016fa87378891
                Found module libgmp.so.10 with build-id: 14dbc5e93375ccb760dc47c5aaecc0cdfc45a06a
                Found module libhogweed.so.6 with build-id: 288da1bb6ffaf6600c2f8a126bec247f2e9a4628
                Found module libnettle.so.8 with build-id: 62dba2572638edf8336bd4de5017fc70eaf0a567
                Found module libtasn1.so.6 with build-id: be32a4fab2585b6114471e83bf582b3df020b594
                Found module libunistring.so.2 with build-id: edcae9db236efd11e61995054ddf27a89ec6dc40
                Found module libidn2.so.0 with build-id: f3ad1b0687f5b426beed2d3d3d18aa301932f7a3
                Found module ld-linux-x86-64.so.2 with build-id: 4e2c368b1240116994daff7f0f248a01f6e53198
                Found module liblzma.so.5 with build-id: 7fec53ce7cba9489f130c99cfd3ace82e9dde0ee
                Found module libzstd.so.1 with build-id: 7984add4b0ab24869c30e19cfba3637ca295dd7b
                Found module libselinux.so.1 with build-id: f805394f993c704b949315b56c344d22dfad801f
                Found module libseccomp.so.2 with build-id: d9e37e30e12bcd8de6d550fda9c874c8870067d9
                Found module libpam.so.0 with build-id: 8ab37bc9d948cd5b1a39cad3d739942991def3c9
                Found module libp11-kit.so.0 with build-id: a7a93824ebf14980eeb37fe23c9d86dd201f947f
                Found module libcrypto.so.1.1 with build-id: 3ead607210606611d5f3398ee7e65198bd519de9
                Found module libmount.so.1 with build-id: 7f7bccf74cb835b64429e61ea0ec03cd0cb95b8b
                Found module liblz4.so.1 with build-id: fd02c4542a1ce1ad6c503b958447be1c37a4afee
                Found module libkmod.so.2 with build-id: 05f61a23314c52c5af47b36809ecf59ee9f000ef
                Found module libip4tc.so.2 with build-id: 87e7e634dae72aabee3832ecf6f2d01515e2dc7b
                Found module libcrypt.so.2 with build-id: 52fd1fd3dc3c8c13f94214c6f2d6fda0832db3d5
                Found module libcap.so.2 with build-id: 0214aa9cc6a8646eb9ec27ab7dda6a2219da6500
                Found module libblkid.so.1 with build-id: 96be27216d8d6d7ba3694ca503cd1b07f60fa539
                Found module libacl.so.1 with build-id: 24b2ced347e35fc1fbc66dfd90c65930ebce8628
                Found module libc.so.6 with build-id: f2837f792a83ba96d761c1b715570411dc0ef584
                Found module libgcc_s.so.1 with build-id: 88564abce789aa42536da1247a57ff6062d61dcb
                Found module libgcrypt.so.20 with build-id: 711d41580c5a8649a79a8430a985dac3e25b5ba2
                Found module libgnutls.so.30 with build-id: 725a333b137bd282d588279e04f20d99a3ea24c1
                Found module libm.so.6 with build-id: 47343f97c29c4e91c841e2bfd344329a264075ad
                Found module libgpg-error.so.0 with build-id: 081975d0a3416374b4883b2f1639fd3c9df42390
                Found module libsystemd-shared-249.so with build-id: ca199d8953af98d699deb587260a38d50b83fb28
                Found module systemd-resolved with build-id: 41c739bd84e8a04b62fdf6e4489d98d8e3b73e4b
                Stack trace of thread 30897:
                #0  0x00007ff6ba0e7a6c _hashmap_first_key_and_value (libsystemd-shared-249.so + 0x168a6c)
                #1  0x0000560fa4298896 dns_query_candidate_stop (systemd-resolved + 0x13896)
                #2  0x0000560fa4298a78 dns_query_stop (systemd-resolved + 0x13a78)
                #3  0x0000560fa4298b02 on_query_timeout (systemd-resolved + 0x13b02)
                #4  0x00007ff6ba1a75b8 source_dispatch (libsystemd-shared-249.so + 0x2285b8)
                #5  0x00007ff6ba1a78ed sd_event_dispatch (libsystemd-shared-249.so + 0x2288ed)
                #6  0x00007ff6ba1a8f48 sd_event_run (libsystemd-shared-249.so + 0x229f48)
                #7  0x00007ff6ba1a911f sd_event_loop (libsystemd-shared-249.so + 0x22a11f)
                #8  0x0000560fa42d335c run (systemd-resolved + 0x4e35c)
                #9  0x0000560fa429507a main (systemd-resolved + 0x1007a)
                #10 0x00007ff6b992c560 __libc_start_call_main (libc.so.6 + 0x2d560)
                #11 0x00007ff6b992c60c __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d60c)
                #12 0x0000560fa4295115 _start (systemd-resolved + 0x10115)
File "/var/lib/systemd/coredump/core.systemd-resolve.990.c18b56418c4b4a1fab091b8791a5fc99.30897.1644033850000000.zst" is not readable: Permission denied
```

```text
…
```

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes #22427.

### CODE REVIEW

File: src/resolve/resolved-dns-query.c [hunk 1]
```diff
@@ -381,6 +381,8 @@ DnsQuery *dns_query_free(DnsQuery *q) {
         if (!q)
                 return NULL;
 
+        sd_event_source_disable_unref(q->timeout_event_source);
```
Comment (poettering) [inline src/resolve/resolved-dns-query.c]: i'd probably write this as:

```c
q->timeout_event_source = sd_event_source_disable_unref(q->timeout_event_source);
```

i.e. we call into dns_query_free(), and all kinds of other stuff, which might refer back to us and might be tripped up because we field is left pointing to freed data. i mean, i am not saying there's a bug *now*, I am just saying that after some later refactoring where dns_query_free() does more stuff it might become one and we should avoid that right away.

i.e. i think we can get away with leaving bad pointers around during destruction of some object, when we know we are really the only ones referencing the object. But here it's not that clear I think... the aux queries might still have a pointer back to us...

File: src/resolve/resolved-dns-query.c [hunk 2]
```diff
@@ -348,7 +349,7 @@ static void dns_query_stop(DnsQuery *q) {
 
         assert(q);
 
-        q->timeout_event_source = sd_event_source_disable_unref(q->timeout_event_source);
+        event_source_disable(q->timeout_event_source);
```
Comment (poettering) [inline src/resolve/resolved-dns-query.c:352]: hmm, does this fix an issue? or is it just an optimization?

i mean, when we restart the query, then we previously just allocated a new timeout event source, so it should work all good, but maybe not as efficient as it could be...

**Comment by poettering** [comment]
lgtm, just wondering about the last commit: did that fix a real bug, or is it just an optimization? see comment above

File: src/resolve/resolved-dns-query.c (hunk 2 above)
Comment (yuwata) [reply src/resolve/resolved-dns-query.c:352]: This is just an optimization. I will update the commit message.

File: src/resolve/resolved-dns-query.c (hunk 1 above)
Comment (yuwata) [reply src/resolve/resolved-dns-query.c]: OK. Actually `DnsQuery` is a complicated object.

**Comment by yuwata** [comment]
@poettering Thank you for the review. The above two points are addressed. Upgrading the green label.

**Review by bluca — APPROVED** [review]

**Comment by DemiMarie** [comment]
Is this an exploitable security hole?
