### PR TITLE
Always rename an interface to its name specified in config

### LINKED ISSUE #9006: udev: interface name in link file not applied
**systemd version the issue has been seen with**
v237

**Used distribution**
Ubuntu 18.04

**Expected behaviour you didn't see**
I have a link file with the following contents:

```
[Match]
MACAddress=52:54:00:69:1d:5b

[Link]
Name=myif3
WakeOnLan=off
```

I expect to see that when I boot, the interface is renamed to `myif3`.

**Unexpected behaviour you saw**

The interface is not renamed, it stays as `ens3`.

This usually **breaks networking** because other parts of the system assume the interface was renamed.

**Steps to reproduce the problem**

 - Create a virtual machine. (I use `uvtool`, but it doesn't really matter.)
 - If using Ubuntu 18.04, the simplest way to demonstrate this is to change `/etc/netplan/50-cloud-init.yaml` and change the `set-name:` yaml key to `myif3`. Then reboot.
 - If not using Ubuntu 18.04, create a link file that sets the Name of a Link, and reboot.
 - The interface is not renamed (as a result, network connectivity is probably broken.)

**Further Information**

I've done further analysis on this.

The interface will be renamed if the link file is in the initrd, but not if the file is absent from the initrd.

Firstly, systemd-udevd renames the interface when running out of initrd.  If the link file is in the initrd, it will be read and applied at that time. If the link file is *not* in the initrd, systemd-udevd will rename the device anyway according to NamePolicy. This will usually be a PCI slot id - here `ens3`. 

Once we leave initrd and get to the normal root file system, the systemd-udevd daemon will be started. This will also consider the link file, but because the interface has been renamed, the `name_assign_type` will be `NET_NAME_RENAMED` (4), so [`should_rename`](https://github.com/systemd/systemd/blob/v237/src/udev/net/link-config.c#L312) will return false and the device won't be renamed again. This is the cause of the unexpected behaviour.

I think `should_rename` should allow `NET_NAME_RENAMED` to be overridden; at least when there's a specific name given in the link file.

### PR DESCRIPTION
**Pull request by cyphermox**
For when no NamePolicy= is specified...

This is intended to fix #9006.

### CODE REVIEW

**Comment by xnox** [comment]
Imho explicit user configuration of custom interface names should be honoured.
Imho declarative specification of a custom interface name, should trump a non-declarative one.
Thus explicit names specified in the declarative .link files should be always applied.

+1 from me

File: src/udev/net/link-config.c [hunk 1]
```diff
@@ -295,37 +295,6 @@ static bool mac_is_random(struct udev_device *device) {
...
-
-        switch (type) {
-        case NET_NAME_USER:
-        case NET_NAME_RENAMED:
-                /* these were already named by userspace, do not touch again */
-                return false;
-        case NET_NAME_PREDICTABLE:
-                /* the kernel claims to have given a predictable name */
-                if (respect_predictable)
-                        return false;
```
Comment (keszybz) [inline src/udev/net/link-config.c]: This part should stay. I.e. if `type == NET_NAME_PREDICATABLE` and `NAMEPOLICY_KERNEL` was specified, the kernel name should be kept.

**Comment by xnox** [comment]
should_rename is now still used.
name_predictable hunk is now back in.
@keszybz @fsateler is this good to go in now? It looks like the requested changes were done.
