### PR TITLE
test: skip instead of fail if crypto kmods are not available

### LINKED ISSUE #5524: khash does not work on Linux 3.16
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 233

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Debian experimental

Building systemd 233 in experimental [failed pretty much everywhere](https://buildd.debian.org/status/package.php?p=systemd&suite=experimental), due to the new khash API:
```
FAIL: test-id128
================
Assertion 'sd_id128_get_machine_app_specific(SD_ID128_MAKE(f0,3d,aa,eb,1c,33,4b,43,a7,32,17,29,44,bf,77,2e), &id) >= 0' failed at ../src/test/test-id128.c:157, function main(). Aborting.
random: aba6b71d549e4f2bba390a748ef437b3
waldi: 0102030405060708090a0b0c0d0e0f10
waldi2: 0102030405060708090a0b0c0d0e0f10
waldi3: 01020304-0506-0708-090a-0b0c0d0e0f10
waldi4: 01020304-0506-0708-090a-0b0c0d0e0f10
FAIL test-id128 (exit status: 134)

FAIL: test-hash
===============
Assertion 'khash_new(&h, "foobar") == -EOPNOTSUPP' failed at ../src/test/test-hash.c:33, function main(). Aborting.
FAIL test-hash (exit status: 134)
```

The new "application specific ID" API in id128 uses khash, that's why that fails as well.

Debian's buildds run Debian 8 (latest stable) with Linux 3.16. Our README says:
```
REQUIREMENTS:
        Linux kernel >= 3.12
        Linux kernel >= 4.2 for unified cgroup hierarchy support
```
So supposedly we should bump that?

Right now it seems that `sd_id128_get_machine_app_specific()` isn't actually being used anywhere right now. We won't get 233 into Debian 9, so I'm not too worried about upgrade failures (i. e. upgrading Debian 8 to Debian 9 and thus upgrading to systemd > 233 while still running on 3.16), but not every distribution might be so lucky.

But we should still do something about the tests. Would it be okay to skip these two on `ENOTSUPP`? Or should we patch that downstream?

### PR DESCRIPTION
**Pull request by martinpitt**
Package build machines may have module loading disabled, thus AF_ALG
sockets are not available. Skip the tests that cover those (khash and
id128) instead of failing them in this case.
    
Fixes #5524

### CODE REVIEW

**Comment by mbiebl** [comment]
Small nit: I bumped the min version a bit (to 3.13) in #5519

**Comment by evverx** [comment]
> khash (more precisely, AF_ALG sockets) are not yet available on Linux
3.12

What are the values of the `CONFIG_CRYPTO_USER_API_HASH`, `CONFIG_CRYPTO_HMAC` and `CONFIG_CRYPTO_SHA256`?

**Comment by evverx** [comment]
@mbiebl has already found [the root cause](https://github.com/systemd/systemd/issues/5524#issuecomment-283841947)
> As module loading is disabled, af_alg, algif_hash, sha256_* and hmac are not autoloaded.

and
> Just built on a Debian 3.16 kernel where module loading is not disabled: The test-suite passed without problems.

I think we shouldn't skip the tests.

**Comment by poettering** [comment]
> I think we shouldn't skip the tests.

Well, I think it makes sense to test this if we can, but if we can't it's no total loss if we cannot, given that this isn't at the core of what systemd does.

**Comment by poettering** [comment]
@martinpitt the patch looks great, but any chance you could update the commit msg? it currently says the kernel version number would be a discriminator, but that's not precisely true, it's the kernel module loading that was turned off that is causing this...

**Comment by martinpitt** [comment]
@poettering: sure! done

**Comment by evverx** [comment]
> if we can't it's no total loss if we cannot, given that this isn't at the core of what systemd does.

Shouldn't we remove the `CONFIG_CRYPTO_*` from the "REQUIREMENTS"-section?

**Comment by floppym** [comment]
The commit message from 0fe5f3c5d743a7e4c63580a67066935f9e23a2f4 seems to indicate that systemd will rely more heavily on the kernel crypto support in the future.

Also, failing tests are a pretty good way to detect a mis-configured system. That's how the README update occurred in the first place; otherwise I would have been clueless.

**Comment by floppym** [comment]
I see Martin's latest changeset outputs a warning message when skipping the tests. That seems like a reasonable compromise.

File: src/test/test-hash.c [hunk 1]
```diff
@@ -25,12 +27,18 @@
...
 
         log_set_max_level(LOG_DEBUG);
 
         assert_se(khash_new(&h, NULL) == -EINVAL);
         assert_se(khash_new(&h, "") == -EINVAL);
-        assert_se(khash_new(&h, "foobar") == -EOPNOTSUPP);
+        r = khash_new(&h, "foobar");
+        if (r == -EAFNOSUPPORT) {
+                puts("khash not supported on this kernel, skipping");
+                return 0;
```
Comment (evverx) [inline src/test/test-hash.c]: `return EXIT_TEST_SKIP`?

File: src/test/test-id128.c [hunk 2]
```diff
@@ -154,11 +154,16 @@ int main(int argc, char *argv[]) {
...
         assert_se(sd_id128_equal(id, id2));
 
-        assert_se(sd_id128_get_machine_app_specific(SD_ID128_MAKE(f0,3d,aa,eb,1c,33,4b,43,a7,32,17,29,44,bf,77,2e), &id) >= 0);
-        assert_se(sd_id128_get_machine_app_specific(SD_ID128_MAKE(f0,3d,aa,eb,1c,33,4b,43,a7,32,17,29,44,bf,77,2e), &id2) >= 0);
-        assert_se(sd_id128_equal(id, id2));
-        assert_se(sd_id128_get_machine_app_specific(SD_ID128_MAKE(51,df,0b,4b,c3,b0,4c,97,80,e2,99,b9,8c,a3,73,b8), &id2) >= 0);
-        assert_se(!sd_id128_equal(id, id2));
+        r = sd_id128_get_machine_app_specific(SD_ID128_MAKE(f0,3d,aa,eb,1c,33,4b,43,a7,32,17,29,44,bf,77,2e), &id);
+        if (r == -EAFNOSUPPORT) {
+                puts("khash not supported on this kernel, skipping");
```
Comment (evverx) [inline src/test/test-id128.c]: Why not `log_info` or so?

File: src/test/test-hash.c (hunk 1 above)
Comment (martinpitt) [reply src/test/test-hash.c]: Yes, good point, will change.

File: src/test/test-id128.c (hunk 2 above)
Comment (martinpitt) [reply src/test/test-id128.c]: Sounds like bikeshedding; a lot of the tests use `printf()`, but I'm fine with using `log_info()`. In fact that was my first version, then I realized that `printf()` was more common in our tests. I'll change it back.

**Comment by martinpitt** [comment]
Pushed with changes discussed above.

BTW, I just pushed a quickfix for the "test-udev" failure in root-unittests. I'll clean this up more properly later on, but this should work for now.

**Comment by martinpitt** [comment]
@evverx, do you want me to change anything else? If not, would you mind reviewing/landing? Thanks!

**Comment by tixxdz** [comment]
we return skipped, lgtm

**Comment by evverx** [comment]
@martinpitt , sorry, I forgot to press the "merge"-button.

LGTM, thanks!
