### PR TITLE
resolved: don't treat conn reset as packet loss

### LINKED ISSUE #33719: High CPU usage for resolved after queries being rejected
### systemd version the issue has been seen with

256.2

### Used distribution

Arch

### Linux kernel version used

6.9.8-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

No persistent high CPU usage (or even spikes) for resolved no matter what

### Unexpected behaviour you saw

Persistent high CPU usage (one core 100%) for resolved after TCP queries being rejected with ICMP port unreachable from the host itself.

While the process can be terminated in a blink with e.g. `systemctl stop` or `restart` (i.e., no SIGKILL needed; no zombie whatsoever), `resolvectl` could have problem (i.e., it stalls) contacting the daemon (even when the command is just `resolvectl`, no `query` or anything) when the CPU usage is high (but it can be terminated with `Ctrl-C` in a blink as well.)

CPU is Intel Core i5-1235U, for the record.

### Steps to reproduce the problem

It can be easily reproduced by having two reject rules in an nftable:

```
table inet filter {
        chain output {
                type filter hook output priority filter; policy accept;
                oifname "lo" accept # irrelevant if the stub listener is not used
                udp dport 53 ip daddr != x.x.x.x reject
                tcp dport 53 ip daddr != x.x.x.x reject
        }
}
```

where x.x.x.x is a link DNS server configured on one of my interfaces (say a wireguard interface), while another interface (say a wireless NIC) also have some link DNS server(s) configured. (So basically a DNS "killswitch".)

(P.S. I do not use `DNS=` in my `wg-quick` conf. I use `resolvectl dns` in a `PostUp=` instead.)

*(Note that the report is about the high CPU usage, which should not occur even if rejecting TCP with ICMP could be considered "a wrong thing to do". I *am* aware that there is `reject with tcp reset`, which is probably the "proper way", and that one can also use `resolvectl dns some_interface ""` to temporarily clear the link DNS server configured on certain interfaces instead.)*

The rule for the UDP queries is to make sure that resolved will send TCP queries. The problem does NOT occur if the TCP queries are simply dropped or rejected with tcp reset. It also *seems* that if the ICMP port unreachable were sent from another host (e.g. a Linux gateway with similar rules in a *forward* chain), the problem does not occur either. (I mean, throughout the tests there seemed to be spikes in that case. In other words, it is "inconclusive" whether the problem exists for that case. Maybe it does not. Maybe it's just somehow less "severe".)

**The problem does NOT occur for UDP queries either.** There's one other thing I did notice though, that is, UDP queries sent to link DNS server(s) are always sent out via the link/interface on which the server(s) are configured. In other words, route(s) and route policies do not seem to matter in the UDP case, whereas the TCP case depends on route decision. *(I have no idea whether the behavior in either case is wrong or unexpected.)*

### Additional program output to the terminal or log subsystem illustrating the issue

```
$ readlink /etc/resolv.conf 
../run/systemd/resolve/stub-resolv.conf
```

```
$ grep -v '^\(#\|$\)' /etc/resolv.conf 
nameserver 127.0.0.53
options edns0 trust-ad
search .
```

### PR DESCRIPTION
**Pull request by rpigott**
tcp reset / icmp port-unreachable are markedly different conditions than packet loss. It doesn't make much sense to retry in this case. It's actually not clear if there is any benefit at all retrying tcp connections, which were presumably already retried as necessary by the tcp stack.

I'm not 100% this is the right solution, but it fixes #33719 afaict.

### CODE REVIEW

File: src/resolve/resolved-dns-stream.c [hunk 1]
```diff
@@ -322,6 +322,13 @@ static int on_stream_io(sd_event_source *es, int fd, uint32_t revents, void *use
                         return dns_stream_complete(s, -r);
         }
 
+        if (revents & EPOLLERR) {
+                socklen_t errlen = sizeof(r);
+                if (getsockopt(s->fd, SOL_SOCKET, SO_ERROR, &r, &errlen) == 0) {
+                        return dns_stream_complete(s, r);
+                }
```
Comment (daandemeyer) [inline src/resolve/resolved-dns-stream.c]: No braces for single line ifs

**Review by yuwata — APPROVED** [review]

**Comment by CScallops** [comment]
Sorry to bother, but I'm trying to determine if this PR got released in any stable release, but I can't find if. Probably skill issue. Has this been released yet? Thanks!
