### PR TITLE
core/namespace: check if we have enough privilege

### LINKED ISSUE #29526: Services configured with `PrivateNetwork=yes` fail to start in containers
### systemd version the issue has been seen with

git main

### Used distribution

Ubuntu 23.10

### Linux kernel version used

6.5.0-5-generic

### CPU architectures issue was seen on

aarch64

### Component

systemd

### Expected behaviour you didn't see

Services configured with `PrivateNetwork=yes` should be able to start inside containers.

### Unexpected behaviour you saw

Services configured with `PrivateNetwork=yes` fail to start within containers. Specifically, services configured this way fail when pid1 is attempting to mount a private sysfs for mount namespacing:

```
root@six:~# systemd-detect-virt 
systemd-nspawn
root@six:~# systemd-run -p PrivateNetwork=yes --wait /bin/true
Running as unit: run-u9.service
Finished with result: exit-code
Main processes terminated with: code=exited/status=226
Service runtime: 14ms
CPU time consumed: 14ms
root@six:~# systemctl status run-u9.service
× run-u9.service - /bin/true
     Loaded: loaded (/run/systemd/transient/run-u9.service; transient)
  Transient: yes
     Active: failed (Result: exit-code) since Tue 2023-10-10 17:33:23 EDT; 7s ago
   Duration: 14ms
    Process: 144 ExecStart=/bin/true (code=exited, status=226/NAMESPACE)
   Main PID: 144 (code=exited, status=226/NAMESPACE)
        CPU: 14ms

Oct 10 17:33:23 six (true)[144]: run-u9.service: Failed to set up mount namespacing: /sys: Operation not permitted
Oct 10 17:33:23 six (true)[144]: run-u9.service: Failed at step NAMESPACE spawning /bin/true: Operation not permitted
Oct 10 17:33:23 six systemd[1]: run-u9.service: Child 144 belongs to run-u9.service.
Oct 10 17:33:23 six systemd[1]: run-u9.service: Main process exited, code=exited, status=226/NAMESPACE
Oct 10 17:33:23 six systemd[1]: run-u9.service: Failed with result 'exit-code'.
Oct 10 17:33:23 six systemd[1]: run-u9.service: Service will not restart (restart setting)
Oct 10 17:33:23 six systemd[1]: run-u9.service: Changed running -> failed
Oct 10 17:33:23 six systemd[1]: run-u9.service: Unit entered failed state.
Oct 10 17:33:23 six systemd[1]: run-u9.service: Consumed 14ms CPU time.
Oct 10 17:33:23 six systemd[1]: run-u9.service: Releasing resources...
```

### Steps to reproduce the problem

1. Create a container for use with systemd-nspawn. I did this on Ubuntu 23.10 using debootstrap to create an Ubuntu 23.10 container, but I don't think it really matters how the container is created.

```bash
sudo debootstrap mantic /var/lib/machines/mantic
sudo machinectl start mantic
sudo machinectl shell mantic
```

2. In the container, follow [the instructions](https://systemd.io/HACKING/) to build systemd from source, and then install it inside the container with `ninja -C build install`.
3. Reboot the container.
4. Enter the container again with `machinectl shell mantic`, and attempt to start any service with `PrivateNetwork=yes`, such as `systemd-localed.service` or `systemd-hostnamed.service`. Or, run a transient service:

```bash
systemd-run --wait -p PrivateNetwork=yes /bin/true
``` 

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
root@six:~# journalctl -u run-u9.service --no-pager -b
Oct 10 17:33:23 six systemd[1]: run-u9.service: Failed to load configuration: No such file or directory
Oct 10 17:33:23 six systemd[1]: run-u9.service: Trying to enqueue job run-u9.service/start/fail
Oct 10 17:33:23 six systemd[1]: run-u9.service: Installed new job run-u9.service/start as 624
Oct 10 17:33:23 six systemd[1]: run-u9.service: Enqueued job run-u9.service/start as 624
Oct 10 17:33:23 six systemd[1]: run-u9.service: Will spawn child (service_enter_start): /bin/true
Oct 10 17:33:23 six systemd[1]: run-u9.service: Failed to set 'trusted.invocation_id' xattr on control group /system.slice/run-u9.service, ignoring: Operation not permitted
Oct 10 17:33:23 six systemd[1]: run-u9.service: Failed to remove 'trusted.delegate' xattr flag on control group /system.slice/run-u9.service, ignoring: Operation not permitted
Oct 10 17:33:23 six systemd[1]: run-u9.service: Failed to remove 'trusted.survive_final_kill_signal' xattr flag on control group /system.slice/run-u9.service, ignoring: Operation not permitted
Oct 10 17:33:23 six systemd[1]: run-u9.service: Passing 0 fds to service
Oct 10 17:33:23 six systemd[1]: run-u9.service: About to execute: /bin/true
Oct 10 17:33:23 six systemd[1]: run-u9.service: Forked /bin/true as 144
Oct 10 17:33:23 six (true)[144]: PR_SET_MM_ARG_START failed: Operation not permitted
Oct 10 17:33:23 six (true)[144]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Oct 10 17:33:23 six (true)[144]: run-u9.service: Kernel keyring access prohibited, ignoring.
Oct 10 17:33:23 six systemd[1]: run-u9.service: Changed dead -> running
Oct 10 17:33:23 six systemd[1]: run-u9.service: Job 624 run-u9.service/start finished, result=done
Oct 10 17:33:23 six systemd[1]: Started run-u9.service.
Oct 10 17:33:23 six (true)[144]: Successfully added address 127.0.0.1 to loopback interface
Oct 10 17:33:23 six (true)[144]: Successfully added address ::1 to loopback interface
Oct 10 17:33:23 six (true)[144]: Successfully brought loopback interface up
Oct 10 17:33:23 six (true)[144]: Bind-mounting / on /run/systemd/mount-rootfs (MS_BIND|MS_REC "")...
Oct 10 17:33:23 six (true)[144]: Applying namespace mount on /run/systemd/mount-rootfs/run/credentials
Oct 10 17:33:23 six (true)[144]: Bind-mounting /run/systemd/inaccessible/dir on /run/systemd/mount-rootfs/run/credentials (MS_BIND|MS_REC "")...
Oct 10 17:33:23 six (true)[144]: Successfully mounted /run/systemd/inaccessible/dir to /run/systemd/mount-rootfs/run/credentials
Oct 10 17:33:23 six (true)[144]: Applying namespace mount on /run/systemd/mount-rootfs/run/systemd/incoming
Oct 10 17:33:23 six (true)[144]: Followed source symlinks /run/systemd/propagate/run-u9.service → /run/systemd/propagate/run-u9.service.
Oct 10 17:33:23 six (true)[144]: Bind-mounting /run/systemd/propagate/run-u9.service on /run/systemd/mount-rootfs/run/systemd/incoming (MS_BIND "")...
Oct 10 17:33:23 six (true)[144]: Successfully mounted /run/systemd/propagate/run-u9.service to /run/systemd/mount-rootfs/run/systemd/incoming
Oct 10 17:33:23 six (true)[144]: Applying namespace mount on /run/systemd/mount-rootfs/sys
Oct 10 17:33:23 six (true)[144]: Failed to umount /run/systemd/mount-rootfs/sys, ignoring: Invalid argument
Oct 10 17:33:23 six (true)[144]: Failed to umount /run/systemd/mount-rootfs/sys, ignoring: Invalid argument
Oct 10 17:33:23 six (true)[144]: Failed to umount /run/systemd/mount-rootfs/sys, ignoring: Invalid argument
Oct 10 17:33:23 six (true)[144]: Failed to umount /run/systemd/mount-rootfs/sys, ignoring: Invalid argument
Oct 10 17:33:23 six (true)[144]: Failed to umount /run/systemd/mount-rootfs/sys, ignoring: Invalid argument
Oct 10 17:33:23 six (true)[144]: Failed to umount /run/systemd/mount-rootfs/sys, ignoring: Invalid argument
Oct 10 17:33:23 six (true)[144]: Failed to umount /run/systemd/mount-rootfs/sys, ignoring: Invalid argument
Oct 10 17:33:23 six (true)[144]: Failed to umount /run/systemd/mount-rootfs/sys, ignoring: Invalid argument
Oct 10 17:33:23 six (true)[144]: Mounting sysfs (sysfs) on /run/systemd/mount-rootfs/sys (MS_NOSUID|MS_NODEV|MS_NOEXEC "")...
Oct 10 17:33:23 six (true)[144]: Failed to mount sysfs (type sysfs) on /run/systemd/mount-rootfs/sys (MS_NOSUID|MS_NODEV|MS_NOEXEC ""): Operation not permitted
Oct 10 17:33:23 six (true)[144]: run-u9.service: Failed to set up mount namespacing: /sys: Operation not permitted
Oct 10 17:33:23 six (true)[144]: run-u9.service: Failed at step NAMESPACE spawning /bin/true: Operation not permitted
Oct 10 17:33:23 six systemd[1]: run-u9.service: Child 144 belongs to run-u9.service.
Oct 10 17:33:23 six systemd[1]: run-u9.service: Main process exited, code=exited, status=226/NAMESPACE
Oct 10 17:33:23 six systemd[1]: run-u9.service: Failed with result 'exit-code'.
Oct 10 17:33:23 six systemd[1]: run-u9.service: Service will not restart (restart setting)
Oct 10 17:33:23 six systemd[1]: run-u9.service: Changed running -> failed
Oct 10 17:33:23 six systemd[1]: run-u9.service: Unit entered failed state.
Oct 10 17:33:23 six systemd[1]: run-u9.service: Consumed 14ms CPU time.
Oct 10 17:33:23 six systemd[1]: run-u9.service: Releasing resources...
```

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes #29526.

### CODE REVIEW

**Comment by yuwata** [comment]
Hmm,,, mounting another sysfs instance on an existing sysfs instance failed...

**Comment by yuwata** [comment]
Yay, now all green. @enr0n Please test this PR.

**Comment by enr0n** [comment]
> Yay, now all green. @enr0n Please test this PR.

@yuwata I tested this locally and it works for me. Thanks!

File: src/core/namespace.c [hunk 1]
```diff
@@ -1111,56 +1111,80 @@ static int mount_private_apivfs(
...
                         return r;
 
-                r = path_is_mount_point(entry_path, NULL, 0);
+                r = mount_nofollow_verbose(LOG_DEBUG, fstype, temporary_mount, fstype, MS_NOSUID|MS_NOEXEC|MS_NODEV, opts);
+                if (r == -EINVAL && opts) {
+                        /* If this failed with EINVAL then this likely means the textual hidepid= stuff for
+                         * proc is not supported by the kernel, and thus the per-instance hidepid= neither,
+                         * which means we really don't want to use it, since it would affect our host's /proc
+                         * mount. Hence let's gracefully fallback to a classic, unrestricted version. */
+                        opts = NULL;
```
Comment (YHNdnzj) [inline src/core/namespace.c]: Hmm, is this necessary? It's not used again below.

File: src/core/namespace.c [hunk 2]
```diff
@@ -1111,56 +1111,80 @@ static int mount_private_apivfs(
...
-                /* We lack permissions to mount a new instance, and it is not already mounted. But we can
-                 * access the host's, so as a final fallback bind-mount it to the destination, as most likely
-                 * we are inside a user manager in an unprivileged user namespace. */
-                return mount_nofollow_verbose(LOG_DEBUG, bind_source, entry_path, NULL, MS_BIND|MS_REC, NULL);
+                /* Then, move the new mount instance. */
+                r = mount_nofollow_verbose(LOG_DEBUG, temporary_mount, entry_path, NULL, MS_MOVE, NULL);
+                if (r < 0)
+                        return r;
+
+                (void) rmdir(temporary_mount);
```
Comment (YHNdnzj) [inline src/core/namespace.c]: Maybe use `rmdir_and_freep`?

File: src/core/namespace.c [hunk 3]
```diff
@@ -1107,37 +1107,64 @@ static int mount_bind_sysfs(const MountEntry *m) {
...
+        assert(fstype);
+        assert(entry_path);
+        assert(bind_source);
 
+        (void) mkdir_p_label(entry_path, 0755);
         n = umount_recursive(entry_path, 0);
 
-        r = mount_nofollow_verbose(LOG_DEBUG, "sysfs", entry_path, "sysfs", MS_NOSUID|MS_NOEXEC|MS_NODEV, NULL);
+        r = mount_nofollow_verbose(LOG_DEBUG, fstype, entry_path, fstype, MS_NOSUID|MS_NOEXEC|MS_NODEV, opts);
+        if (r == -EINVAL && opts)
```
Comment (poettering) [inline src/core/namespace.c:1186]: this only applies to procfs afaics, hence add `streq(fstype, "proc")` to the conditions here?

Comment (poettering) [reply src/core/namespace.c:1186]: or alternatively add another boolean param `try_without_options` or so that is only set for the procfs case?

File: src/core/namespace.c [hunk 4]
```diff
@@ -1152,15 +1155,26 @@ static int mount_private_apivfs(
         } else if (r < 0)
                 return r;
 
+        /* OK. We have a new mount instance. Let's clear an exisitng mount and its submounts. */
```
Comment (poettering) [inline src/core/namespace.c]: typo

File: src/core/namespace.c (hunk 3 above)
Comment (yuwata) [reply src/core/namespace.c:1186]: For sysfs, `opts` is always `NULL`. So, I do not think it is necessary.

File: src/core/namespace.c [hunk 5]
```diff
@@ -1160,37 +1160,64 @@ static int mount_bind_sysfs(const MountEntry *m) {
...
-        (void) bind_mount_submounts("/sys", entry_path);
+        /* We mounted a new instance now. Let's bind mount the children over now. This matters for nspawn
+         * where a bunch of files are overmounted, in particular the boot id. */
+        (void) bind_mount_submounts(bind_source, entry_path);
         return 0;
 }
 
+static int mount_private_sysfs(const MountEntry *m) {
+        assert(m);
+        return mount_private_apivfs("sysfs", mount_entry_path(m), "/sys", NULL);
```
Comment (bluca) [inline src/core/namespace.c]: `/* opts= */ NULL`

File: src/core/namespace.c [hunk 6]
```diff
@@ -1160,37 +1160,64 @@ static int mount_bind_sysfs(const MountEntry *m) {
...
+                 * existing mount. */
 
                 if (n > 0)
-                        /* /sys or some of sub-mounts are umounted in the above. Refuse incomplete tree.
+                        /* The mount or some of sub-mounts are umounted in the above. Refuse incomplete tree.
                          * Propagate the original error code returned by mount() in the above. */
                         return r;
 
-                return mount_bind_sysfs(m);
+                r = path_is_mount_point(entry_path, NULL, 0);
```
Comment (bluca) [inline src/core/namespace.c]: `/* root= */ NULL`

File: src/core/namespace.c [hunk 7]
```diff
@@ -1160,37 +1160,64 @@ static int mount_bind_sysfs(const MountEntry *m) {
...
+                if (r < 0)
+                        return log_debug_errno(r, "Unable to determine whether '%s' is already mounted: %m", entry_path);
+                if (r > 0)
+                        return 0; /* Use the current mount as is. */
+
+                /* We lack permissions to mount a new instance, and it is not already mounted. But we can
+                 * access the host's, so as a final fallback bind-mount it to the destination, as most likely
+                 * we are inside a user manager in an unprivileged user namespace. */
+                return mount_nofollow_verbose(LOG_DEBUG, bind_source, entry_path, NULL, MS_BIND|MS_REC, NULL);
```
Comment (bluca) [inline src/core/namespace.c]: `/* type= */ NULL, MS_BIND|MS_REC, /* options= */ NULL`

File: src/core/namespace.c [hunk 8]
```diff
@@ -1160,37 +1160,64 @@ static int mount_bind_sysfs(const MountEntry *m) {
...
         n = umount_recursive(entry_path, 0);
 
-        r = mount_nofollow_verbose(LOG_DEBUG, "sysfs", entry_path, "sysfs", MS_NOSUID|MS_NOEXEC|MS_NODEV, NULL);
+        r = mount_nofollow_verbose(LOG_DEBUG, fstype, entry_path, fstype, MS_NOSUID|MS_NOEXEC|MS_NODEV, opts);
+        if (r == -EINVAL && opts)
+                /* If this failed with EINVAL then this likely means the textual hidepid= stuff for procfs is
+                 * not supported by the kernel, and thus the per-instance hidepid= neither, which means we
+                 * really don't want to use it, since it would affect our host's /proc mount. Hence let's
+                 * gracefully fallback to a classic, unrestricted version. */
+                r = mount_nofollow_verbose(LOG_DEBUG, fstype, entry_path, fstype, MS_NOSUID|MS_NOEXEC|MS_NODEV, NULL);
```
Comment (bluca) [inline src/core/namespace.c]: `/* options= */ NULL`

**Review by bluca — APPROVED** [review]
