### PR TITLE
ac-power: check battery existence and status

### LINKED ISSUE #25316: Lenovo P14s Gen2 (AMD) reports ConditionACPower false while on AC Power via USB-C
### systemd version the issue has been seen with

systemd/testing,now 252-2

### Used distribution

Debian Bookworm

### Linux kernel version used

6.0.0-2-amd64

### CPU architectures issue was seen on

_No response_

### Component

_No response_

### Expected behaviour you didn't see

A unit with ConditionACPower=true runs when I manually start it while on AC Power using the stock USB-C power supply.

### Unexpected behaviour you saw

The unit did not start 

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Nov 09 13:01:37 leo systemd[1]: backup.service: Installed new job backup.service/start as 31081
Nov 09 13:01:37 leo systemd[1]: backup.service: Enqueued job backup.service/start as 31081
Nov 09 13:01:37 leo systemd[1]: BAT0: The power supply is battery.
Nov 09 13:01:37 leo systemd[1]: hidpp_battery_6: The power supply is a device battery, ignoring device.
Nov 09 13:01:37 leo systemd[1]: Found battery and no online power sources, assuming system is running from battery.
Nov 09 13:01:37 leo systemd[1]: backup.service: ConditionACPower=true failed.
Nov 09 13:01:37 leo systemd[1]: backup.service: Starting requested but condition failed. Not starting unit.
Nov 09 13:01:37 leo systemd[1]: backup.service: Job 31081 backup.service/start finished, result=done
Nov 09 13:01:37 leo systemd[1]: Create system backups was skipped because of an unmet condition check (ConditionACPower=true).
```

### PR DESCRIPTION
**Pull request by yuwata**
If a battery is not present or its status is not discharging, then the battery should not be used as a power source.
Let's count batteries currently discharging.

Fixes #25316.

### CODE REVIEW

**Comment by yuwata** [comment]
@mrc0mmand What happens to packit??

**Comment by mrc0mmand** [comment]
> @mrc0mmand What happens to packit??

Interesting, looks like Packit is FUBAR - definitely not related to this PR, but I'll ping the Packit folks.

**Comment by yuwata** [comment]
@TomasTomecek Thank you!

File: src/shared/udev-util.c [hunk 1]
```diff
@@ -642,9 +642,46 @@ static int device_is_power_sink(sd_device *device) {
...
+                if (r != -ENOENT)
+                        log_device_debug_errno(d, r, "Failed to read 'scope' sysfs attribute, ignoring: %m");
+        } else if (streq(val, "Device")) {
+                log_device_debug(d, "The power supply is a device battery, ignoring device.");
+                return false;
+        }
+
+        r = device_get_sysattr_bool(d, "present");
+        if (r < 0)
+                log_device_debug_errno(d, r, "Failed to read 'present' sysfs attribute, assuming the battery presents: %m");
```
Comment (poettering) [inline src/shared/udev-util.c]: presents → is present

**Comment by poettering** [comment]
lgtm (one nitpick)

**Comment by yuwata** [comment]
> lgtm (one nitpick)

@poettering I guess you forgot to submit your review?

**Review by poettering — APPROVED** [review]
