### PR TITLE
coverity: Add custom assertion macros for Coverity

### LINKED ISSUE #9183: Coverity poor match for ASSERT_SIDE_EFFECT (on assert_se)
I think most of the Coverity false positives are `ASSERT_SIDE_EFFECT` whenever `assert_se` is used.

Latest report had 3 of them, for example:

```c
*** CID 1391439:  Incorrect expression  (ASSERT_SIDE_EFFECT)
/src/fuzz/fuzz-journal-remote.c: 59 in LLVMFuzzerTestOneInput()
53             /* Out */
54     
55             r = sd_journal_open_files(&j, (const char**) STRV_MAKE(name), 0);
56             assert_se(r >= 0);
57     
58             if (getenv_bool("SYSTEMD_FUZZ_OUTPUT") <= 0)
>>>     CID 1391439:  Incorrect expression  (ASSERT_SIDE_EFFECT)
>>>     Assignment "dev_null = fopen("/dev/null", "we")" has a side effect.  This code will work differently in a non-debug build.
59                     assert_se(dev_null = fopen("/dev/null", "we"));
60     
61             for (mode = 0; mode < _OUTPUT_MODE_MAX; mode++) {
62                     if (!dev_null)
63                             log_info("/* %s */", output_mode_to_string(mode));
64                     r = show_journal(dev_null ?: stdout, j, mode, 0, 0, -1, 0, NULL);
```

Can we _teach_ Coverity that `assert_se` doesn't ignore side effects? It seems that whenever they match a `/assert/i` in regular expression, they assume it has a problem with side effects...

I wish it would at least be able to *look* inside the definition of `assert_se` and notice that it's not a problem with it.

One alternative would be to rename `assert_se` to something else that doesn't include `assert` in its name... But I think teaching Coverity to do the right thing would be better.

I didn't find many docs for Coverity online... So wondering if anyone else in the project knows more about it or knows how best to get some support on it to try to fix this one?

Cheers,
Filipe

### PR DESCRIPTION
**Pull request by filbranden**
This seems to solve the ASSERT_SIDE_EFFECT assertions we have for calls of `assert_se()` and `assert_return()`.

This technique has been described and recommended in:
https://community.synopsys.com/s/question/0D534000046Yuzb/suppressing-assertsideeffect-for-functions-that-allow-for-sideeffects

Tested by triggering a run of Coverity from a local build, in which the complaints about `assert_se()` and `assert_return()` were gone...

Fixes #9183

### CODE REVIEW

**Comment by evverx** [comment]
@filbranden thank you. A lot of warnings are gone, but I can also see a number of "missing parentheses" warnings. I'm wondering if you submitted something that is not included in this PR yet?

**Comment by filbranden** [comment]
@evverx Yes I was trying to push a fix for `assert_return()` and I ended up making a mistake in my macros, using `!expr` instead of `!(expr)`, duh :-)

We ran out of quota in Coverity, we can only push 3 analysis per day.

I actually reworked it once again (pushed it here now), I think this solution is cleaner and I believe it should be able to handle both `assert_se()` and `assert_return()`. Tomorrow late afternoon I'll push this one manually to Coverity to test it and, depending on results, we can go ahead and merge it.

Perhaps take a look and see what you think of the code... If you'd like to do an initial review, that would be nice. Since we can only test this twice a day, let's make sure our first attempt will count, so we can use the second one to just fix any minor details that need it :-)

Cheers,
Filipe

File: src/basic/macro.h [hunk 1]
```diff
@@ -247,12 +247,45 @@ static inline unsigned long ALIGN_POWER2(unsigned long u) {
...
+ * for uses of assert_se() and assert_return().
+ *
+ * These definitions make expression go through a (trivial) function
+ * call to ensure they are not discarded. Also use ! or !! to ensure
+ * the boolean expressions are seen as such.
+ */
+
+extern void __coverity_panic__(void);
+
+static inline int __coverity_check__(int condition) {
```
Comment (poettering) [inline src/basic/macro.h:266]: wouldn't bool be better for both types here, than int?

File: src/basic/macro.h [hunk 2]
```diff
@@ -247,12 +247,45 @@ static inline unsigned long ALIGN_POWER2(unsigned long u) {
...
                 if (_unlikely_(!(expr)))                                \
                         log_assert_failed(message, __FILE__, __LINE__, __PRETTY_FUNCTION__); \
         } while (false)
 
+#endif  /* __COVERITY__ */
+
+#define assert_log(expr, message) ((_likely_(expr))                     \
+        ? (true)                                                        \
+        : (log_assert_failed_return(message, __FILE__, __LINE__, __PRETTY_FUNCTION__), false))
+
```
Comment (poettering) [inline src/basic/macro.h]: you define assert_log() twice in case __COVERITY__ is set, no?

**Comment by evverx** [comment]
I'd just add a link to https://community.synopsys.com/s/question/0D534000046Yuzb/suppressing-assertsideeffect-for-functions-that-allow-for-sideeffects to the comment, so that it'd be a little bit easier to understand where it all comes from when the git history isn't available. Everything else looks good to me. Not that I'm particularly good at expanding macros in my head, though :-)

Also, the "don't merge" label might scare potential reviewers, so I'd drop it as well.

Just out of curiosity, is there any reason you didn't use Travis to send data to Coverity? I though it should be more convenient than uploading analysis results manually.

File: src/basic/macro.h (hunk 2 above)
Comment (filbranden) [reply src/basic/macro.h]: Great catch! I moved it up, but clearly not enough... Will fix.

File: src/basic/macro.h (hunk 1 above)
Comment (filbranden) [reply src/basic/macro.h:266]: In principle, yes. But there seems to be a lot of magic in Coverity, so I'm not sure whether using a bool here would make it warn... So I'm trying to stick as close as possible to the suggestion I got in that thread (even though I had to adapt it a bit to work on assert_return() as well.)

**Comment by filbranden** [comment]
> I'd just add a link to ... to the comment, so that it'd be a little bit easier to understand where it all comes from when the git history isn't available.

Good point! Will do.

> Also, the "don't merge" label might scare potential reviewers, so I'd drop it as well.

Yes agreed. I mostly didn't because I haven't really tested it...

> Just out of curiosity, is there any reason you didn't use Travis to send data to Coverity? I though it should be more convenient than uploading analysis results manually.

Believe me, I tried!!!

It's no longer watching PRs and there doesn't seem to be any manual trigger for that...

I enabled watching branches and even temporarily pushed a new `coverity` branch to systemd/systemd (feel so dirty about it!) but Travis still didn't seem to find it, probably because .travis.yml doesn't list it and it has a whitelist for branches...

So this actually took me on a tangent looking into this whole Travis -> Docker -> Coverity plumbing and I have some ideas on how to improve it:
* Move the Dockerfile to a new `docker-builder` subdirectory, since it shouldn't be Travis-specific.
* Don't include the sources in it (instead, mount them as a volume), only include the build dependencies. If Coverity is available, include that in the container as well.
* In particular, this means you would be able to cache this container and use it more than once, no need to build it every time...
* Include a `systemd-builder` script inside it and make it the Docker container entry-point. This would take commands such as `build`, `build --test`, `cov-build`, etc.

After this is done, one would be able to run the Coverity build inside a container locally, and even upload it, with something similar to:

```sh
$ docker build -t systemd-builder docker-builder/
$ mkdir cov-build cov-int
$ docker run --mount type=bind,src=.,dst=/systemd,readonly --mount type=bind,src=cov-build/,dst=/cov-build --mount type=bind,src=cov-int/,dst=/cov-int systemd-builder cov-build
$ docker-builder/coverity.sh upload cov-int/
```

(There are a few more details, but that's the general idea... I'm far from getting something usable, but making progress. I'll open a PR when I have something that can be experimented with.)

Cheers!
Filipe

**Comment by filbranden** [comment]
Ok, I just tested this with a manual upload to Coverity and it seems to work... Merge at will! :smiley:

**Comment by keszybz** [comment]
> We ran out of quota in Coverity

Oh, that's why I was constantly getting e-mail from coverity about new defects ;)

**Comment by keszybz** [comment]
s390x fails with `boot-and-services    FAIL stderr: Failed to dump process list for 'systemd-nspawn@c1.service', ignoring: Unit systemd-nspawn@c1.service not loaded.`, unrelated.
