### PR TITLE
repart: use real disk start/end for bar production

### LINKED ISSUE #21817: repart: assertion failed when resizing root partition on 249.7-2 under ArchLinux
**systemd version the issue has been seen with**

```
# pacman -Q systemd
systemd 249.7-2
```

**Used distribution**
ArchLinux

**Linux kernel version used** (`uname -a`)
Linux backup51.[redacted] 5.10.87-1-lts #1 SMP Fri, 17 Dec 2021 10:43:27 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
Qemu 6.2.0 virtual machine, x86_64

**Unexpected behaviour you saw**
```
# /usr/bin/systemd-repart
TYPE                                 LABEL       UUID                                 FILE         NODE          SIZE PADDING
root-x86-64                          root-x86-64 5f5770b4-f87f-ee43-be43-18f3baec322d 50-root.conf /dev/sda2     3.9G      0B
21686148-6449-6e6f-744e-656564454649 -           a22d6cb3-9910-ca40-be45-0cf148792a43 -            /dev/sda1     1.0M      0B
                                                                                                             Σ = 3.9G  Σ = 0B
Assertion 'to <= context->end' failed at src/partition/repart.c:2114, function context_bar_char_process_partition(). Aborting.
[1]    1474 abort (core dumped)  /usr/bin/systemd-repart
```

**Steps to reproduce the problem**
```
# cat /etc/repart.d/50-root.conf
[Partition]
Type=root
# /usr/bin/systemd-repart
```

**Additional program output to the terminal or log subsystem illustrating the issue**

```
 # /usr/bin/systemd-repart
TYPE                                 LABEL       UUID                                 FILE         NODE          SIZE PADDING
root-x86-64                          root-x86-64 5f5770b4-f87f-ee43-be43-18f3baec322d 50-root.conf /dev/sda2     3.9G      0B
21686148-6449-6e6f-744e-656564454649 -           a22d6cb3-9910-ca40-be45-0cf148792a43 -            /dev/sda1     1.0M      0B
                                                                                                             Σ = 3.9G  Σ = 0B
Assertion 'to <= context->end' failed at src/partition/repart.c:2114, function context_bar_char_process_partition(). Aborting.
[1]    1474 abort (core dumped)  /usr/bin/systemd-repart
```

Here is the output of lsblk...
```
# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda      8:0    0   25G  0 disk
├─sda1   8:1    0    1M  0 part
└─sda2   8:2    0    4G  0 part /
sdb      8:16   0   10T  0 disk
```

I can pull the core dump if required.

### PR DESCRIPTION
**Pull request by tomty89**
Partitions are not always within our aligned scope. Bar printing involves foreign partitions as well.

Fixes #21817.

### CODE REVIEW

File: src/partition/repart.c [hunk 1]
```diff
@@ -2080,16 +2080,14 @@ static void context_bar_char_process_partition(
...
-        assert(context->end >= context->start);
-        total = context->end - context->start;
+        assert(context->total > 0);
+        total = context->total;
 
-        assert(from >= context->start);
-        assert(from <= context->end);
-        x = (from - context->start) * n / total;
+        assert(from <= total);
+        x = (from - 0) * n / total;
```
Comment (bluca) [inline src/partition/repart.c]: `- 0`?

Comment (tomty89) [reply src/partition/repart.c:2087]: The very beginning of a disk (?)

**Comment by tomty89** [comment]
We may also consider the unaligned first / last lba returned by `fdisk_get_first_lba()` / `fdisk_get_last_lba()`, although personally I don't find that better. (I prefer the gaps at the beginning and the end being printed as well.)

File: src/partition/repart.c (hunk 1 above)
Comment (tomty89) [reply src/partition/repart.c:2087]: Note that this is purely about the bar printing, so we shouldn't need to check whether partition start / end are actually "valid" (e.g. before the partition table end) here, regardless of whether the partition is foreign.

**Comment by keszybz** [comment]
LGTM.
