### PR TITLE
xorg/50-systemd-user: import XAUTHORITY only if set

### LINKED ISSUE #40745: Unwanted "environment variable not set" warning in xsession-errors log
### systemd version the issue has been seen with

259.1

### Used distribution

Arch Linux

### Component

other

### Expected behaviour you didn't see

No errors/warnings if XAUTHORITY variable is not exported by display manager.

`XAUTHORITY` variable is optional. Not all display managers export it. However, `systemctl --user import-environment` run from `/etc/X11/xinit/xinitrc.d/50-systemd-user.sh` tries to import this variable, which leads to the warning message. Moreover, systemctl tries to colorize output despite stderr is not a tty (deserves to be reported as another bug), so the line in xsession-errors looks confusing.

### Unexpected behaviour you saw

```
[0;1;39mEnvironment variable $XAUTHORITY not set, ignoring.[0m
```

### PR DESCRIPTION
**Pull request by dimich-dmb**
The warning will still be reported if XAUTHORITY is set but not exported. However, such scenario is unlikely for xinitrc.d scripts environment.

Fixes #40745

### CODE REVIEW

File: xorg/50-systemd-user.sh [hunk 1]
```diff
@@ -8,7 +8,7 @@
 #  the Free Software Foundation; either version 2.1 of the License, or
 #  (at your option) any later version.
 
-systemctl --user import-environment DISPLAY XAUTHORITY
+systemctl --user import-environment DISPLAY ${XAUTHORITY+XAUTHORITY}
```
Comment (poettering) [inline xorg/50-systemd-user.sh:11]: is that syntax a bash extension? or is it posix?

Comment (poettering) [reply xorg/50-systemd-user.sh:11]: seems to be posix. fine then.

https://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html
