### PR TITLE
cryptsetup: use uint64_t for keyfile-offset=

### LINKED ISSUE #7677: systemd-cryptsetup: "Numerical result out of range" on parsing keyfile-offset option
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 236

### Used distribution

> Gentoo

### In case of bug report: Expected behaviour you didn't see

> systemd-cryptsetup successfully opening LUKS volume according to /etc/crypttab:
```
home	PARTUUID=...	/dev/disk/by-id/...		luks,discard,keyfile-offset=15664672768,keyfile-size=2048
```

Manually checking such config with cryptsetup without systemd wrapper succeeds:
```
cryptsetup -v luksOpen --test-passphrase --key-file=/dev/disk/by-id/... --keyfile-offset=15664672768 --keyfile-size=2048 /dev/disk/by-partuuid/...
```
(I store key in unallocated space after partition. That's why I point to keyfile as /dev/disk/by-id/... and supply a large keyfile-offset.)

### In case of bug report: Unexpected behaviour you saw

> Error message from systemd-cryptsetup and LUKS volume not opened:
```
systemd[1]: Starting Cryptography Setup for home...
systemd-cryptsetup[261]: Failed to parse keyfile-offset=15664672768, ignoring: Numerical result out of range
systemd-cryptsetup[261]: Failed to activate with key file '/dev/disk/by-id/...': Operation not permitted
```

### In case of bug report: Steps to reproduce the problem

> Supply a large keyfile-offset (not fitting in unsigned int) in /etc/crypttab

### PR DESCRIPTION
**Pull request by keszybz**
A warning is added, but not made fatal, on the presumption that there might be
people out there who used a large offset and it was truncated and the key is
actually placed at this "wrong" location. If they key is at the untruncated
location higher than 2**32, then crypt_activate_by_keyfile_offset() will fail
anyway.

Fixes #7677.

Once https://gitlab.com/cryptsetup/cryptsetup/issues/359 is resolved, we should
switch to the new api, whatever it is.

### CODE REVIEW

File: src/cryptsetup/cryptsetup.c [hunk 1]
```diff
@@ -132,12 +132,16 @@ static int parse_one_option(const char *option) {
...
-                r = safe_atou(val, &arg_keyfile_offset);
+                r = safe_atou64(val, &arg_keyfile_offset);
                 if (r < 0) {
                         log_error_errno(r, "Failed to parse %s, ignoring: %m", option);
                         return 0;
                 }
 
+                if ((size_t) arg_keyfile_offset != arg_keyfile_offset)
+                        /* https://gitlab.com/cryptsetup/cryptsetup/issues/359 */
+                        log_warning("keyfile-offset= value truncated to %zu", (size_t) arg_keyfile_offset);
```
Comment (poettering) [inline src/cryptsetup/cryptsetup.c]: hmm, we never permitted the truncated version, did we? safe_atou() after all just refused to parse this, hence we failed entirely? I think we should just fail if the user specifies a value >32bit on a 32bit arch, instead of warn and truncate

Comment (keszybz) [reply src/cryptsetup/cryptsetup.c]: I meant that somebody might have created the key at the wrong offset using some other tool. But that's overthinking the problem. I'll adjust to refuse.

**Comment by keszybz** [comment]
Updated.

**Comment by poettering** [comment]
lgtm.

(one might argue we should actually fail entirely when we fail to parse this, but i guess this is OK too)

File: src/cryptsetup/cryptsetup.c [hunk 2]
```diff
@@ -131,13 +131,22 @@ static int parse_one_option(const char *option) {
...
+                uint64_t off;
 
-                r = safe_atou(val, &arg_keyfile_offset);
+                r = safe_atou64(val, &off);
                 if (r < 0) {
                         log_error_errno(r, "Failed to parse %s, ignoring: %m", option);
                         return 0;
                 }
 
+                if ((size_t) off != off) {
```
Comment (yuwata) [inline src/cryptsetup/cryptsetup.c:142]: Is it not necessary to re-cast the value like `(uint64_t) (size_t) off != off`?

Comment (keszybz) [reply src/cryptsetup/cryptsetup.c:142]: ints are promoted to the longer type, so it's fine as is.

Comment (yuwata) [reply src/cryptsetup/cryptsetup.c:142]: Thanks.
