### PR TITLE
Print "Shutdown.." or "Reboot scheduled for Thu 2020-06-11 06:00:00 CEST, use 'shutdown -c' to cancel." depending on what'll happen

### LINKED ISSUE #16129: misleading message on scheduled reboot: "Shutdown scheduled for Thu 2020-06-11 06:00:00 CEST, use 'shutdown -c' to cancel."
**systemd version the issue has been seen with**
> 215-17+deb8u13

However I see [here](https://github.com/systemd/systemd/blob/161bc1b62777b3f32ce645a8e128007a654a2300/src/systemctl/systemctl.c#L9092) that the behavior is still present in today's git repo.
 
**Used distribution**
 > Debian

**Expected behaviour you didn't see**
 > It should say misleading "Reboot scheduled for Thu 2020-06-11 06:00:00 CEST, use 'shutdown -c' to cancel." instead

**Unexpected behaviour you saw**
 > It said ""Shutdown scheduled for Thu 2020-06-11 06:00:00 CEST, use 'shutdown -c' to cancel."

**Steps to reproduce the problem**

shutdown -r +1

### PR DESCRIPTION
**Pull request by tpo**
I'd be glad if you could pull this fix. Mind you I have **not** tested it, it is however trivial.

Depending on if the system has been scheduled for shutdown or for reboot pring the corresponding message (and not only "Shutdown"). Prtinting the "wrong" message when rebooting will mislead and panic people. I get these messages via cron from remote servers and it would be bad if those systems actually *did* shut down, as the email from cron is telling me. Those messages cause an adrenalin spike in our team, which wouldn't happen, if the message was "correct"

This fixes #16129

### CODE REVIEW

File: src/systemctl/systemctl.c [hunk 1]
```diff
@@ -9089,7 +9089,9 @@ static int logind_schedule_shutdown(void) {
                 return log_warning_errno(r, "Failed to call ScheduleShutdown in logind, proceeding with immediate shutdown: %s", bus_error_message(&error, r));
 
         if (!arg_quiet)
-                log_info("Shutdown scheduled for %s, use 'shutdown -c' to cancel.", format_timestamp(date, sizeof(date), arg_when));
+                log_info("%s scheduled for %s, use 'shutdown -c' to cancel.",
+                         (arg_action == ACTION_REBOOT ? "Reboot" : "Shutdown"),
```
Comment (keszybz) [inline src/systemctl/systemctl.c]: This *does* fix the immediate issue reported in #16129, but not the other cases. If you look at the `switch` statement above, it is clear that the message is inappropriate in other cases too, e.g. for kexec it'll still say "Shutdown". So maybe extend the `switch` statement to also specify a human-readable action name for this message:
```C
case ACTION_HALT:
    action = "halt";
    human = "Halt";
    break;
...
case ACTION_KEXEC:
   action = "kexec";
   human = "Reboot via kexec";
   ...
```

Also, coding style: the parentheses in the added line are not needed. But that'll be resolved if the code is reworked as suggested anyway.

Comment (tpo) [reply src/systemctl/systemctl.c]: Thanks @keszybz 

* I am assuming that the "halt" and "poweroff" actions will both shut the system down, correct?
* What does "exit" do? Also shut the system down?
* And kexec replaces the running kernel with a new one without shutdown or reboot, right?

Comment (poettering) [reply src/systemctl/systemctl.c]: "exit" is only supported when systemd runs as PID in a container, and means that systemd just exits with some configurable error code.

To your other questions the answer is "yes"

Comment (tpo) [reply src/systemctl/systemctl.c]: @keszybz, I think I have resolved the raised points in 5ad42057f65d23d2b51b0aba8cdd38b1daae1196. If you want I can squash my two commits.

**Comment by tpo** [comment]
Btw. @keszybz - to be strict this represents an API/interface change. Do you want me to add a note to some changelog or release notes?

**Comment by DaanDeMeyer** [comment]
We generally like to merge "perfect" PRs, i.e. PRs which are split into commits that each are logical steps, not historical ones. or in other words: please make sure that your PR doesn't contain commits that fixes up other commits in the same PR. Also see CODING_STYLE...

(specifically: please rebase and squash the later commits into the first one)

(I don't think this is a big enough change to mention in the release notes.)

**Comment by keszybz** [comment]
> We generally like to merge "perfect" PRs, i.e. PRs which are split into commits that each are logical steps, not historical ones. or in other words: please make sure that your PR doesn't contain commits that fixes up other commits in the same PR. Also see CODING_STYLE...

In general this is correct, but in this case we can do a squash-and-merge operation since there's just one logical change.

> (I don't think this is a big enough change to mention in the release notes.)

Yeah, this is not an API change. User interface strings are not part of the API and no stability promises are made for them.

File: src/systemctl/systemctl.c [hunk 2]
```diff
@@ -9063,19 +9064,24 @@ static int logind_schedule_shutdown(void) {
...
                 action = "halt";
+                log_action = "Shutdown";
                 break;
         case ACTION_POWEROFF:
                 action = "poweroff";
+                log_action = "Shutdown";
                 break;
         case ACTION_KEXEC:
                 action = "kexec";
+                log_action = "Kernel replacement";
```
Comment (keszybz) [inline src/systemctl/systemctl.c]: Please change this to "Reboot via kexec". "Kernel replacement" is confusing.

Comment (tpo) [reply src/systemctl/systemctl.c]: @keszybz isn't that *even more* confusing? Because as far as I understand *no reboot* will happen, it's only the kernel that will be replaced.

I can replace it with "Kernel replacement via kexec" (...scheduled for Thu 2020-06-11 06:00:00 CEST, use 'shutdown -c' to cancel."). Or the shorter, much less explicit and IMHO much less clear "Kexec" (...scheduled for Thu 2020-06-11 06:00:00 CEST, use 'shutdown -c' to cancel.").

?

Comment (keszybz) [reply src/systemctl/systemctl.c]: From a users pov, it is a new boot. The difference is that the system doesn't go through POST or similar and the hardware isn't physically reset. But depending on how the machine is set up, this might not even make any visual difference. The system starts from the beginning.

I'm pretty sure that "boot"/"reboot" and "kexec" should appear somewhere in this string.
Maybe "Boot into new kernel with kexec" ?

Comment (tpo) [reply src/systemctl/systemctl.c]: Ah, I see. So it was a misunderstanding on my side. Will change accordingly. Thanks!

**Comment by tpo** [comment]
Thanks @keszybz !
