### PR TITLE
networkd: don't stop the dhcp server if it's not configured.

### LINKED ISSUE #7047: Assertion failed in sd-dhcp-server.c
### Submission type

Bug report

### systemd version the issue has been seen with

v234

### Used distribution

debian buster

### Unexpected behaviour you saw

With systemd-networkd debug logging enabled, when the ethernet link goes down I'm seeing:

```
Oct 10 13:41:07 nena systemd-networkd[126]: eth0: Lost carrier
Oct 10 13:41:07 nena systemd-networkd[126]: DHCP CLIENT (0x560f2dc5): STOPPED
Oct 10 13:41:07 nena systemd-networkd[126]: eth0: DHCP lease lost
Oct 10 13:41:07 nena systemd-networkd[126]: NDISC: Stopping IPv6 Router Solicitation client
Oct 10 13:41:07 nena systemd-networkd[126]: Assertion 'server' failed at ../src/libsystemd-network/sd-dhcp-server.c:256, function sd_dhcp_server_stop(). Ignoring.
```

I don't know if it might be related, but on subsequent link up I'm also experiencing "NDISC: Error sending Router Solicitation: Network is unreachable", which does not resolve on restarting networkd (see issue #2365), resulting in loss of IPv6 connectivity.

### Steps to reproduce the problem

My config:
```
[Match]
Name=eth0

[Network]
DHCP=ipv4
IPv6PrivacyExtensions=no
IPv6DuplicateAddressDetection=0
LLMNR=on

[DHCP]
UseDomains=yes
```

The error occurs on link down.

### PR DESCRIPTION
**Pull request by ssahani**
we call sd_dhcp_server_stop even if it's not configured when link is
down resulting unwanted logs.
```
Oct 10 13:41:07 nena systemd-networkd[126]: eth0: Lost carrier
Oct 10 13:41:07 nena systemd-networkd[126]: DHCP CLIENT (0x560f2dc5): STOPPED
Oct 10 13:41:07 nena systemd-networkd[126]: eth0: DHCP lease lost
Oct 10 13:41:07 nena systemd-networkd[126]: NDISC: Stopping IPv6 Router Solicitation client
Oct 10 13:41:07 nena systemd-networkd[126]: Assertion 'server' failed at ../src/libsystemd-network/sd-dhcp-server.c:256, function sd_dhcp_server_stop(). Ignoring.
```

fixes #7047

### CODE REVIEW

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -3082,7 +3082,8 @@ static int link_carrier_lost(Link *link) {
                 return r;
         }
 
-        (void) sd_dhcp_server_stop(link->dhcp_server);
+        if (link_dhcp4_server_enabled(link))
+            (void) sd_dhcp_server_stop(link->dhcp_server);
```
Comment (keszybz) [inline src/network/networkd-link.c]: Indentation.

Comment (ssahani) [reply src/network/networkd-link.c]: fixed.
