### PR TITLE
test-process-util: Handle unprivileged setrlimit success

### LINKED ISSUE #22896: Test error in 549/978 test-process-util - fails with current Clang-15-git and GCC-12-git
**systemd version the issue has been seen with**
 > `250.r1651.gf777e745a7`

**Used distribution**
 > `EndevourOS (Arch)`

**Linux kernel version used** (`uname -a`)
 > `5.17.1`

**CPU architecture issue was seen on**
 > `Haswell-EP`

**Expected behaviour you didn't see**
 > `Pass`

**Unexpected behaviour you saw**
 > `Fail`

**Steps to reproduce the problem**
 > Compile with: `clang version 15.0.0 (/home/marcus/Downloads/llvm-git/llvm-project de30408b3b0a012f902b8565fa0b7625c1d5fec6)`

and the following compiler options: 

```
export CC=clang
export CXX=clang++
export CC_LD=lld
export CXX_LD=lld
export LD=lld
export AR=llvm-ar
export NM=llvm-nm
export STRIP=llvm-strip
export OBJCOPY=llvm-objcopy
export OBJDUMP=llvm-objdump
export READELF=llvm-readelf
export RANLIB=llvm-ranlib
export HOSTCC=clang
export HOSTCXX=clang++
export HOSTAR=llvm-ar
export CFLAGS="-O3 -march=native -mtune=native -mllvm -polly -mllvm -polly-parallel -fopenmp -mllvm -polly-vectorizer=stripmine -mllvm -polly-omp-backend=LLVM -mllvm -polly-num-threads=36 -mllvm -polly-scheduling=dynamic -mllvm -polly-scheduling-chunksize=1 -mllvm -polly-ast-use-context -mllvm -polly-invariant-load-hoisting -mllvm -polly-loopfusion-greedy -mllvm -polly-run-inliner -mllvm -polly-run-dce -fno-math-errno -fno-trapping-math -falign-functions=32 -fno-semantic-interposition -fcf-protection=none -flto"
export CXXFLAGS="${CFLAGS}"
export LDFLAGS="-Wl,--lto-O3,-Bsymbolic-functions,--as-needed -flto -fuse-ld=lld"
export ASFLAGS="-D__AVX__=1 -D__AVX2__=1 -D__FMA__=1"
```

**Additional program output to the terminal or log subsystem illustrating the issue**

[meson-log.txt](https://github.com/systemd/systemd/files/8370904/meson-log.txt)
[testlog.txt](https://github.com/systemd/systemd/files/8370906/testlog.txt)
```

549/978 test-process-util                                                           FAIL             0.34s   killed by signal 6 SIGABRT
>>> MALLOC_PERTURB_=149 PATH=/home/marcus/Downloads/systemd-git/src/build:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl SYSTEMD_LANGUAGE_FALLBACK_MAP=/home/marcus/Downloads/systemd-git/src/systemd/src/locale/language-fallback-map /home/marcus/Downloads/systemd-git/src/build/test-process-util
```

…
```

### PR DESCRIPTION
**Pull request by dbnicholson**
Currently test_setpriority_closest assumes that setting RLIMIT_NICE to 30 will fail if the process is unprivileged. If it succeeds, it assumes that the process is privileged and setresuid and setresgid will succeed.

However, if RLIMIT_NICE is already >= 30, then setrlimit will succeed even if the process is unprivileged. Guard against that by checking for permission errors in setresuid and setresgid and skipping the full test if so.

Fixes #22896.

### CODE REVIEW

File: src/test/test-process-util.c [hunk 1]
```diff
@@ -716,9 +716,17 @@ TEST(setpriority_closest) {
...
-                        full_test = true;
+                        /* However, if the hard limit was above 30, setrlimit would succeed unprivileged, so
+                         * check if the UID/GID can be changed before enabling the full test. */
+                        if (setresgid(GID_NOBODY, GID_NOBODY, GID_NOBODY) < 0) {
+                                assert_se(ERRNO_IS_PRIVILEGE(errno));
+                                full_test = false;
+                        } else if (setresuid(UID_NOBODY, UID_NOBODY, UID_NOBODY) < 0) {
+                                assert_se(ERRNO_IS_PRIVILEGE(errno));
+                                full_test = false;
+                        } else {
```
Comment (bluca) [inline src/test/test-process-util.c]: no brackets around single-line ifs

**Review by yuwata — APPROVED** [review]
