### PR TITLE
boot: load device tree even if no original config exists

### LINKED ISSUE #24059: Boot Loader Entry Key `devicetree` Unsupported
### systemd version the issue has been seen with

251.3

### Used distribution

Arch Linux

### Linux kernel version used

5.19 (rc1)

### CPU architectures issue was seen on

aarch64

### Component

systemd-boot

### Expected behaviour you didn't see

Should be jumping to the kernel.

### Unexpected behaviour you saw

image

### Steps to reproduce the problem

Create an aarch64 archiso for the Lenovo ThinkPad X13s, like done here: https://github.com/ironrobin/archiso-x13s
Flash the ISO to a USB drive.
Boot into the USB drive.
Select an entry that looks something like this:
```
title   Arch Linux install medium (aarch64, UEFI)
linux      /arch/boot/aarch64/Image
devicetree /arch/boot/aarch64/sc8280xp-thinkpad.dtb
initrd     /arch/boot/aarch64/initramfs-linux.img
options archisobasedir=arch archisolabel=ARCH_AARCH64_202207 efi=novamap clk_ignore_unused console=tty0
```
Note: Things work if you use the `dtb=` kernel option in the options list. Yet if you use `devicetree` Entry Key it is showing as Unsupported. 

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by craftyguy**
Firmware may not have loaded a devicetree, for example if the device
shipped with windows and exclusively supports ACPI.
We should always load the specified devicetree regardless of firmware
state to enable booting on platforms where Linux only supports DT.

Fixes #24059

cc @daniel-thompson, since you wrote this and I just rebased / tested.

### CODE REVIEW

File: src/boot/efi/devicetree.c [hunk 1]
```diff
@@ -133,7 +129,7 @@ EFI_STATUS devicetree_install_from_memory(
 void devicetree_cleanup(struct devicetree_state *state) {
         EFI_STATUS err;
 
-        if (!state->pages)
+        if (!state->pages || !state->orig)
```
Comment (bluca) [inline src/boot/efi/devicetree.c]: Shouldn't the configuration table be cleared anyway in this case? As that's the 'original' state that is being restored

File: src/boot/efi/devicetree.c [hunk 2]
```diff
@@ -72,8 +72,6 @@ EFI_STATUS devicetree_install(struct devicetree_state *state, EFI_FILE *root_dir
         assert(name);
 
         state->orig = find_configuration_table(MAKE_GUID_PTR(EFI_DTB_TABLE));
-        if (!state->orig)
```
Comment (bluca) [inline src/boot/efi/devicetree.c:75]: This check should stay, and a debug level log be written, instead of returning (same below)

File: src/boot/efi/devicetree.c (hunk 1 above)
Comment (bluca) [reply src/boot/efi/devicetree.c]: @kukrimate any suggestion on the appropriate thing to do here? Not many DTB experts around here

File: src/boot/efi/devicetree.c (hunk 2 above)
Comment (poettering) [reply src/boot/efi/devicetree.c:75]: we have no debug logging currentl in EFI mode. log_trace probably comes closest

File: src/boot/efi/devicetree.c (hunk 1 above)
Comment (daniel-thompson) [reply src/boot/efi/devicetree.c]: This line comes from my original PoC and it is not related to being devicetree-correct. I had already spent more time than I should have reviewing a code base I'd never seen before (systemd-boot) and writing a PoC. I suspect I was no longer in the mood to go an double check that that InstallConfigurationTable() could tolerate a NULL pointer (given I was asking someone else to test it, I probably figured that loading the wrong config table would be easier to debug remotely than a crash in systemd-boot)!

However I just checked both EDK2 implementation and the UEFI spec. Passing a NULL to InstallConfigurationTable is just fine and does the right thing. Therefore removing this line is "the right thing to do".

File: src/boot/efi/devicetree.c (hunk 2 above)
Comment (daniel-thompson) [reply src/boot/efi/devicetree.c:75]: If there can't be a debug message here then maybe no message is best.

We were told to install a devicetree and we installed one. I'm not sure there is a need for more "drama" if we install a devicetree on a system without a DT than a system with an existing DT.

Comment (kcxt) [reply src/boot/efi/devicetree.c:75]: +1 for this, installing a DT should not implicitly depend on whatever environment the EFI firmware provides, it's intentional - and if not then usually a pretty obvious thing to spot.

File: src/boot/efi/devicetree.c (hunk 1 above)
Comment (craftyguy) [reply src/boot/efi/devicetree.c]: I dropped this change in the latest revision, and added a note in the commit message that calling `InstallConfigurationTable` is fine.

**Review by bluca — APPROVED** [review]
Please add a comment explaining why the result is not checked next to both calls - this is unusual in our codebase, so it will be confusing otherwise

File: src/boot/efi/devicetree.c [hunk 3]
```diff
@@ -71,9 +71,10 @@ EFI_STATUS devicetree_install(struct devicetree_state *state, EFI_FILE *root_dir
         assert(root_dir);
         assert(name);
 
+        /* Note: The return value of this function is intentionally not checked. In cases where the system fw
+         * has no devicetree, we still want to load a given devicetree, so a NULL value from this function is
+         * fine. */
         state->orig = find_configuration_table(MAKE_GUID_PTR(EFI_DTB_TABLE));
```
Comment (daniel-thompson) [inline src/boot/efi/devicetree.c:77]: Nitpicking but this comment is justifying why we deleted the (broken) error path rather than what the code is actually doing. How about something more like the following (which, among other things, hints that we did check how the InstallConfigurationTable() in devicetree_cleanup() actually works):

Capture the original value for the devicetree table. NULL is not an error in this case so we don't need to check the return value. NULL simply means the system fw had no devicetree initially (and is the correct value to use to return to the initial state if needed).

Comment (craftyguy) [reply src/boot/efi/devicetree.c:77]: sure whatever, I've already spend far too much time on a simple patch that someone else wrote to fix sd-boot on these platforms 😓

**Comment by bluca** [comment]
it will
