### PR TITLE
network: fix several DHCP6 PD issues, and cleanup DHCP4 and NDISC

### LINKED ISSUE #13218: systemd-networkd stops adding temporary IPs after a few days with IPv6PrivacyExtensions=yes
**systemd version the issue has been seen with**
> systemd 242 (242.32-3-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > About every 24 hours when a temporary IPv6 address gets to status deprecated, a new temporary IP address should be added to the interface

**Unexpected behaviour you saw**
 > For the first few days, a new address was added as expected, but after 6 days the old IPv6 address got deprecated without a adding a new one. Instead of using a temporary address for the outgoing traffic, the MAC-address based IPv6 is used which I want to avoid for privacy reasons or the IPv6PrivacyExtensions setting would not make sense.

**Steps to reproduce the problem**
Configure network interface with the following settings and wait for a few days. The value for Name may have to be adjusted according to the name of the network interface
```
[Match]
Name=en*

[Network]
DHCP=yes
IPv6AcceptRA=yes
IPv6PrivacyExtensions=yes
```

**Debug logging**
For debugging purposes, I had to use a VM, but I experienced the same behaviour on a physical machine before. I configured **Environment=SYSTEMD_LOG_LEVEL=debug** in a drop-in file and found the following entries with journalctl - partly anonymized:

```
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Configuring route: dst: 2003:c5:xxxx:xxxx::/64, src: n/a, gw: n/a, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Configuring route: dst: 2003:c5:xxxx:xxxx::/56, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Sent INFORMATION-REQUEST
Jul 01 19:54:25 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Next retransmission in 991ms
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Updating route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Updating route: dst: 2003:c5:xxxx:xxxx::/64, src: n/a, gw: n/a, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:5054:ff:fe00:4063/64 (valid for 2h)
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx::/56, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Recv REPLY
Jul 01 19:54:27 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:5054:ff:fe00:4063/64 (valid for 1h 59min 59s)
Jul 01 19:54:27 server-arch systemd-networkd[289]: ens3: Configured
Jul 01 19:54:27 server-arch systemd-networkd[289]: ens3: State changed: configuring -> configured
Jul 01 19:54:27 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:5054:ff:fe00:4063/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 01 19:54:27 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/64 (valid for 1h 59min 59s)
Jul 01 19:54:27 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/128, src: n/a, gw: n/a, prefsrc: n/a
```
every few minutes I have entries like the following one:
```
Jul 01 19:56:44 server-arch systemd-networkd[289]: NDISC: Received Router Advertisement: flags OTHER preference medium lifetime 1800 sec
Jul 01 19:56:44 server-arch systemd-networkd[289]: NDISC: Invoking callback for 'router' event.
Jul 01 19:56:44 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Started in Information request mode
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Acquiring DHCPv6 lease on NDisc request
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Configuring route: dst: 2003:c5:xxxx:xxxx::/64, src: n/a, gw: n/a, prefsrc: n/a
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Configuring route: dst: 2003:c5:xxxx:xxxx::/56, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:56:44 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Sent INFORMATION-REQUEST
Jul 01 19:56:44 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Next retransmission in 996ms
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:5054:ff:fe00:4063/64 (valid for 2h)
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/64 (valid for 2h)
Jul 01 19:56:45 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Recv REPLY
```
...
after first 24 hours
```
Jul 02 19:50:31 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:60fc:ab46:9c7d:da37/64 (valid for 1h 51min 14s)
Jul 02 19:50:31 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:60fc:ab46:9c7d:da37/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 02 19:50:32 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/64 (valid for 1h 51min 13s)
```
...
```
Jul 03 19:46:35 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:35e7:270e:2684:e591/64 (valid for 1h 56min 23s)
Jul 03 19:46:35 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:35e7:270e:2684:e591/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 03 19:46:36 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:60fc:ab46:9c7d:da37/64 (valid for 1h 56min 22s)
```
...
```
Jul 04 19:42:40 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:40df:4dac:e9cb:7d9e/64 (valid for 1h 59min 6s)
Jul 04 19:42:40 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:40df:4dac:e9cb:7d9e/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 04 19:42:41 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:35e7:270e:2684:e591/64 (valid for 1h 59min 5s)
```
...
```
Jul 05 19:38:45 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:fd2b:a818:e29d:2a0e/64 (valid for 1h 56min 15s)
Jul 05 19:38:45 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:fd2b:a818:e29d:2a0e/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 05 19:38:46 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:40df:4dac:e9cb:7d9e/64 (valid for 1h 56min 14s)
```
...
```
Jul 06 19:34:48 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/64 (valid for 1h 59min 55s)
Jul 06 19:34:48 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 06 19:34:49 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:fd2b:a818:e29d:2a0e/64 (valid for 1h 59min 54s)
```
...
after 6 days only
```
Jul 07 19:30:57 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/64 (valid for 1h 55min 50s)
```
24 hours later no more related entries.
systemd-networkd only shows that it's deprecating the temporary address which was added 24 hours ago but no _Adding address_ / _Adding route_ entries. This does not always seem to happen after exactly 6 days, can also be a few days more or less.

Output of **ip a** at that time:
```
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:00:40:63 brd ff:ff:ff:ff:ff:ff
    inet 192.168.x.y/24 brd 192.168.x.255 scope global dynamic ens3
       valid_lft 773602sec preferred_lft 773602sec
    inet6 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/64 scope global temporary deprecated dynamic 
       valid_lft 6946sec preferred_lft 0sec
    inet6 2003:c5:xxxx:xxxx:fd2b:a818:e29d:2a0e/64 scope global temporary deprecated dynamic 
       valid_lft 6946sec preferred_lft 0sec
    inet6 2003:c5:xxxx:xxxx:40df:4dac:e9cb:7d9e/64 scope global temporary deprecated dynamic 
       valid_lft 6946sec preferred_lft 0sec
    inet6 2003:c5:xxxx:xxxx:35e7:270e:2684:e591/64 scope global temporary deprecated dynamic 
       valid_lft 6946sec preferred_lft 0sec
    inet6 2003:c5:xxxx:xxxx:60fc:ab46:9c7d:da37/64 scope global temporary deprecated dynamic 
       valid_lft 6946sec preferred_lft 0sec
    inet6 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/64 scope global temporary deprecated dynamic 
       valid_lft 6946sec preferred_lft 0sec
    inet6 2003:c5:xxxx:xxxx:5054:ff:fe00:4063/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 6946sec preferred_lft 1546sec
    inet6 fe80::5054:ff:fe00:4063/64 scope link 
       valid_lft forever preferred_lft forever
```

All temporary IPv6 addresses are now deprecated. After their lifetime has expired, the old addresses get removed
```
Jul 08 19:54:35 server-arch systemd-networkd[289]: ens3: Removing address: 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/64 (valid for 0)
Jul 08 19:54:35 server-arch systemd-networkd[289]: ens3: Removing route: dst: 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/128, src: n/a, gw: n/a, prefsrc: n/a

Jul 09 19:50:31 server-arch systemd-networkd[289]: ens3: Removing address: 2003:c5:xxxx:xxxx:60fc:ab46:9c7d:da37/64 (valid for 0)
Jul 09 19:50:31 server-arch systemd-networkd[289]: ens3: Removing route: dst: 2003:c5:xxxx:xxxx:60fc:ab46:9c7d:da37/128, src: n/a, gw: n/a, prefsrc: n/a

Jul 10 19:46:35 server-arch systemd-networkd[289]: ens3: Removing address: 2003:c5:xxxx:xxxx:35e7:270e:2684:e591/64 (valid for 0)
Jul 10 19:46:35 server-arch systemd-networkd[289]: ens3: Removing route: dst: 2003:c5:xxxx:xxxx:35e7:270e:2684:e591/128, src: n/a, gw: n/a, prefsrc: n/a

Jul 11 19:42:40 server-arch systemd-networkd[289]: ens3: Removing address: 2003:c5:xxxx:xxxx:40df:4dac:e9cb:7d9e/64 (valid for 0)
Jul 11 19:42:40 server-arch systemd-networkd[289]: ens3: Removing route: dst: 2003:c5:xxxx:xxxx:40df:4dac:e9cb:7d9e/128, src: n/a, gw: n/a, prefsrc: n/a

Jul 12 19:38:44 server-arch systemd-networkd[289]: ens3: Removing address: 2003:c5:xxxx:xxxx:fd2b:a818:e29d:2a0e/64 (valid for 0)
Jul 12 19:38:44 server-arch systemd-networkd[289]: ens3: Removing route: dst: 2003:c5:xxxx:xxxx:fd2b:a818:e29d:2a0e/128, src: n/a, gw: n/a, prefsrc: n/a
```
When the last IPv6 address is to be removed, I find the following log entries
```
Jul 13 19:34:47 server-arch systemd-networkd[289]: ens3: Removing address: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/64 (valid for 0)
Jul 13 19:34:47 server-arch systemd-networkd[289]: ens3: Removing route: dst: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 13 19:35:08 server-arch systemd-networkd[289]: NDISC: Received Router Advertisement: flags OTHER preference medium lifetime 1800 sec
Jul 13 19:35:08 server-arch systemd-networkd[289]: NDISC: Invoking callback for 'router' event.
Jul 13 19:35:08 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Started in Information request mode
Jul 13 19:35:08 server-arch systemd-networkd[289]: ens3: Acquiring DHCPv6 lease on NDisc request
Jul 13 19:35:08 server-arch systemd-networkd[289]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 13 19:35:08 server-arch systemd-networkd[289]: ens3: Configuring route: dst: 2003:c5:xxxx:xxxx::/64, src: n/a, gw: n/a, prefsrc: n/a
Jul 13 19:35:08 server-arch systemd-networkd[289]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 13 19:35:08 server-arch systemd-networkd[289]: ens3: Configuring route: dst: 2003:c5:xxxx:xxxx::/56, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 13 19:35:08 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Sent INFORMATION-REQUEST
Jul 13 19:35:08 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Next retransmission in 960ms
Jul 13 19:35:08 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:5054:ff:fe00:4063/64 (valid for 2h)
Jul 13 19:35:08 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Recv REPLY
Jul 13 19:35:10 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/64 (valid for 1h 59min 58s)
Jul 13 19:35:10 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/128, src: n/a, gw: n/a, prefsrc: n/a
```
and the last deprecated address gets active again and the procedure starts again with adding new addresses for a few days...

When my router or the ISP disconnects my WAN connection and receives a new prefix, this also resulted in a new temporary IPv6 address until the renewal stalls again.

### LINKED ISSUE #13564: systemd-networkd does not clean up old IPv6 prefix delegation routes from downstream interfaces
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > debian 10 (buster)

**Expected behaviour you didn't see**
 > When I get a new prefix via IA_PD from the router, the old routes should be deleted

**Unexpected behaviour you saw**
 > Routes don't get cleaned up.

**Steps to reproduce the problem**
I get a new IPv6 pool every day from my ISP. I use prefix delegation to provide IPv6 in the network. After 5 days, I saw 5 IPv6 prefixes on the internal interface. The old ones do not get cleaned up. I will try to get a PCAP from the router at the time of address change.

But even if there is no kind of "de-announcement" from the router for the old prefix, the prefix delegation has a valid lifetime of 2 hours. At least this should be honored and the route should be deleted after it is invalid.

Restarting systemd-networkd cleans up all IPv6 routes

### LINKED ISSUE #15455: networkd: IPv6 prefix delegation not updated correctly when prefix changes
**systemd version the issue has been seen with**
> 244.3 (from Debian buster backports) and git master at commit ac24e418d9bc988ecf114c464701b35934948178

**Used distribution**
 > Debian stable (Buster)

**Expected behaviour you didn't see**
 > I have an internet connection via a router provided by my ISP (called "CPE" from here on) and use a Linux box as a router in between the CPE and my internal network. Thus, my internal network needs its own IPv6 prefix. The CPE supports IPv6 prefix delegation via DHCPv6. My internet connection does not have stable IPv6 prefixes, so each time the connection is reset, the delegated prefixes become invalid. (Unfortunately, the CPE does not send a Reconfigure message.)

> Using tcpdump I found: When systemd-networkd wants to renew the prefixes, it sends a DHCPv6 Renew message and gets a NoBinding response if the prefix is no longer valid. My reading of RFC 8415 (Sec. 18.2.10.1) is that in this case the DHCPv6 client should request a new prefix. Instead, systemd-networkd continuously retries renewing the expired prefix without success. After some time, it switches to Rebind messages, with the same effect. IPv6 connectivity is lost. I would expect that systemd-networkd would switch to trying to obtain a new prefix.

**Unexpected behaviour you saw**
 > I also encounter #13564, i.e., systemd-networkd never cleans up routes for delegated prefixes that are no longer valid. These prefixes are no longer advertised downstream by networkd, so that part seems to work, but the routes remain, leading to possible problems since they no longer "belong" to me.

**Steps to reproduce the problem**
Config files:
```
#/etc/systemd/network/10-enp3s0.network <- the "external" interface

[Match]
Name=enp3s0

[Network]
Address=<some RFC1918 IPv4 address>
Gateway=<IPv4 gateway>
Address=fdxx:xxxx:xxxx:xxxx::1/64
IPv6AcceptRA=yes
DHCP=ipv6
IPv6PrivacyExtensions=true

[DHCPv6]
# Note: usually, the CPE is configured to only set the "Other
# Configuration" flag. I also tried changing it to set the "Managed"
# flag in router advertisements, but with the setting below, there
# is no difference in the behavior of networkd. In git master I hit
# issue #15375 instead without the "Managed" flag.
ForceDHCPv6PDOtherInformation=yes


#/etc/systemd/network/20-br0.network <- the "internal" interface

[Match]
Name=br0

[Network]
Address=<some RFC1918 IPv4 address>
Address=fdxx:xxxx:xxxx:yyyy::1/64
IPv6PrefixDelegation=yes

[IPv6PrefixDelegation]
Managed=yes
OtherInformation=yes
RouterLifetimeSec=7200
EmitDNS=yes
DNS=fdxx:xxxx:xxxx:yyyy::1
DNSLifetimeSec=7200

[IPv6Prefix]
Prefix=fdxx:xxxx:xxxx:yyyy::/64
ValidLifetimeSec=7200
PreferredLifetimeSec=3600
```

To "fix" this, running `networkctl reconfigure enp3s0` helps, but does not remove old routes.

### LINKED ISSUE #16546: systemd-networkd asserts on loss and regain of carrier when doing DHCPv6-PD with AssignAcquiredDelegatedPrefixAddress=yes
**systemd version the issue has been seen with**
> 246-rc1

**Used distribution**
 > Ubuntu

**Expected behaviour you didn't see**
 > systemd-networkd does not crash if carrier is lost and regained

**Unexpected behaviour you saw**
 > systemd-networkd crashes if carrier is lost and regained

**Steps to reproduce the problem**
1. My configuration has an Ethernet adapter with 5 VLANs, each of which is configured to receive a prefix with DHCPv6-PD done on another interface.  I haven't tried to reproduce the problem without the VLANs.
2. Unplug the Ethernet cable.
3. Plug the Ethernet cable.
4. Crash

As mentioned in the title, this only happens with AssignAcquiredDelegatedPrefixAddress=yes.  Setting the value to no for all interfaces works around the crash.  It also doesn't matter whether ConfigureWithoutCarrier is true or false; the crash happens both ways.

Log output from reproducing:
```
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb18260: Gained carrier
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb18260: Discovering IPv6 routers
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb18260: State changed: configured -> configuring
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_311 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=68 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb18260: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb18260: link_check_ready(): dhcp4:no dhcp6_addresses:no dhcp_routes:no dhcp_pd_addresses:no dhcp_pd_routes:no ndisc_addresses:yes ndisc_routes:yes                                                       
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb18260: State changed: configuring -> configured
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_311 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=69 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb18260: link_check_ready(): static addresses are configured. Configuring static routes.                                                                                                                  
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Flags change: +LOWER_UP +RUNNING
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_314 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=70 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Gained carrier
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Starting IPv6 Router Advertisements
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Started IPv6 Router Advertisement daemon
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Requesting DHCPv6 prefixes to be delegated for new link
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Requesting re-assignment of delegated prefixes after adding new link                                                                                                                             
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Configuring route: dst: 2001:db8:0:f00::/56, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unreachable                                                            
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Configuring unreachable route for 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Assigning up to 256 prefixes from 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: The requested prefix 2001:db8:0:f03:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f03::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: State changed: configured -> configuring
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_312 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=71 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Configuring route: dst: 2001:db8:0:f03::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Adding prefix route 2001:db8:0:f03::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Assigned prefix 2001:db8:0:f03::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: The requested prefix 2001:db8:0:f01:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f01::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: State changed: configured -> configuring
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_314 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=72 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Configuring route: dst: 2001:db8:0:f01::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Adding prefix route 2001:db8:0:f01::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Assigned prefix 2001:db8:0:f01::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: The requested prefix 2001:db8:0:f05:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f05::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: State changed: configured -> configuring
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_315 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=73 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Configuring route: dst: 2001:db8:0:f05::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Adding prefix route 2001:db8:0:f05::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Assigned prefix 2001:db8:0:f05::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: The requested prefix 2001:db8:0:f04:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f04::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: State changed: configured -> configuring
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_316 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=74 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Configuring route: dst: 2001:db8:0:f04::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Adding prefix route 2001:db8:0:f04::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Assigned prefix 2001:db8:0:f04::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: The requested prefix 2001:db8:0:f02:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f02::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: State changed: configured -> configuring
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_313 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=75 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Configuring route: dst: 2001:db8:0:f02::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Adding prefix route 2001:db8:0:f02::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Assigned prefix 2001:db8:0:f02::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Assigning up to 256 prefixes from 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Setting unreachable routes for DHCPv6 delegated subnets
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: State changed: configured -> configuring
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=76 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                            
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Setting addresses
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Next Router Advertisement in 6s
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Flags change: +LOWER_UP +RUNNING
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_313 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=77 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Gained carrier
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Starting IPv6 Router Advertisements
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Started IPv6 Router Advertisement daemon
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Requesting DHCPv6 prefixes to be delegated for new link
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Requesting re-assignment of delegated prefixes after adding new link                                                                                                                             
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Configuring route: dst: 2001:db8:0:f00::/56, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unreachable                                                            
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Configuring unreachable route for 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Assigning up to 256 prefixes from 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: The requested prefix 2001:db8:0:f03:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f03::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Configuring route: dst: 2001:db8:0:f03::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Adding prefix route 2001:db8:0:f03::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Assigned prefix 2001:db8:0:f03::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: The requested prefix 2001:db8:0:f01:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f01::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Configuring route: dst: 2001:db8:0:f01::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Adding prefix route 2001:db8:0:f01::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Assigned prefix 2001:db8:0:f01::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: The requested prefix 2001:db8:0:f05:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f05::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Configuring route: dst: 2001:db8:0:f05::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Adding prefix route 2001:db8:0:f05::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Assigned prefix 2001:db8:0:f05::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: The requested prefix 2001:db8:0:f04:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f04::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Configuring route: dst: 2001:db8:0:f04::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Adding prefix route 2001:db8:0:f04::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Assigned prefix 2001:db8:0:f04::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: The requested prefix 2001:db8:0:f02:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f02::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Configuring route: dst: 2001:db8:0:f02::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Adding prefix route 2001:db8:0:f02::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Assigned prefix 2001:db8:0:f02::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Assigning up to 256 prefixes from 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Setting unreachable routes for DHCPv6 delegated subnets
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Setting addresses
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Next Router Advertisement in 11s
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Flags change: +LOWER_UP +RUNNING
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_312 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=78 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Gained carrier
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Starting IPv6 Router Advertisements
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Started IPv6 Router Advertisement daemon
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Requesting DHCPv6 prefixes to be delegated for new link
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Requesting re-assignment of delegated prefixes after adding new link                                                                                                                             
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Configuring route: dst: 2001:db8:0:f00::/56, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unreachable                                                            
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Configuring unreachable route for 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Assigning up to 256 prefixes from 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: The requested prefix 2001:db8:0:f03:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f03::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Configuring route: dst: 2001:db8:0:f03::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Adding prefix route 2001:db8:0:f03::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Assigned prefix 2001:db8:0:f03::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: The requested prefix 2001:db8:0:f01:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f01::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Configuring route: dst: 2001:db8:0:f01::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Adding prefix route 2001:db8:0:f01::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Assigned prefix 2001:db8:0:f01::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: The requested prefix 2001:db8:0:f05:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f05::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Configuring route: dst: 2001:db8:0:f05::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Adding prefix route 2001:db8:0:f05::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Assigned prefix 2001:db8:0:f05::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: The requested prefix 2001:db8:0:f04:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f04::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Configuring route: dst: 2001:db8:0:f04::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Adding prefix route 2001:db8:0:f04::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Assigned prefix 2001:db8:0:f04::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: The requested prefix 2001:db8:0:f02:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f02::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Configuring route: dst: 2001:db8:0:f02::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Adding prefix route 2001:db8:0:f02::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Assigned prefix 2001:db8:0:f02::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Assigning up to 256 prefixes from 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Setting unreachable routes for DHCPv6 delegated subnets
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Setting addresses
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Next Router Advertisement in 15s
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Flags change: +LOWER_UP +RUNNING
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_316 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=79 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Gained carrier
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Starting IPv6 Router Advertisements
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Started IPv6 Router Advertisement daemon
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Requesting DHCPv6 prefixes to be delegated for new link
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Requesting re-assignment of delegated prefixes after adding new link                                                                                                                             
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Configuring route: dst: 2001:db8:0:f00::/56, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unreachable                                                            
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Configuring unreachable route for 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Assigning up to 256 prefixes from 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: The requested prefix 2001:db8:0:f03:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f03::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Configuring route: dst: 2001:db8:0:f03::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Adding prefix route 2001:db8:0:f03::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Assigned prefix 2001:db8:0:f03::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: The requested prefix 2001:db8:0:f01:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f01::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Configuring route: dst: 2001:db8:0:f01::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Adding prefix route 2001:db8:0:f01::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Assigned prefix 2001:db8:0:f01::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: The requested prefix 2001:db8:0:f05:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f05::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Configuring route: dst: 2001:db8:0:f05::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Adding prefix route 2001:db8:0:f05::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Assigned prefix 2001:db8:0:f05::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: The requested prefix 2001:db8:0:f04:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f04::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Configuring route: dst: 2001:db8:0:f04::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Adding prefix route 2001:db8:0:f04::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Assigned prefix 2001:db8:0:f04::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: The requested prefix 2001:db8:0:f02:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f02::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Configuring route: dst: 2001:db8:0:f02::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Adding prefix route 2001:db8:0:f02::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Assigned prefix 2001:db8:0:f02::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Assigning up to 256 prefixes from 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Setting unreachable routes for DHCPv6 delegated subnets
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Setting addresses
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Next Router Advertisement in 9s
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Flags change: +LOWER_UP +RUNNING
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_315 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=80 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Gained carrier
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Starting IPv6 Router Advertisements
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Started IPv6 Router Advertisement daemon
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Requesting DHCPv6 prefixes to be delegated for new link
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Requesting re-assignment of delegated prefixes after adding new link                                                                                                                             
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Configuring route: dst: 2001:db8:0:f00::/56, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unreachable                                                            
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Configuring unreachable route for 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Assigning up to 256 prefixes from 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: The requested prefix 2001:db8:0:f03:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f03::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Configuring route: dst: 2001:db8:0:f03::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Adding prefix route 2001:db8:0:f03::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Assigned prefix 2001:db8:0:f03::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: The requested prefix 2001:db8:0:f01:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f01::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Configuring route: dst: 2001:db8:0:f01::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Adding prefix route 2001:db8:0:f01::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Assigned prefix 2001:db8:0:f01::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: The requested prefix 2001:db8:0:f05:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f05::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Configuring route: dst: 2001:db8:0:f05::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Adding prefix route 2001:db8:0:f05::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Assigned prefix 2001:db8:0:f05::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: The requested prefix 2001:db8:0:f04:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f04::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Configuring route: dst: 2001:db8:0:f04::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Adding prefix route 2001:db8:0:f04::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Assigned prefix 2001:db8:0:f04::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: The requested prefix 2001:db8:0:f02:: is available. Using it.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Updated prefix 2001:db8:0:f02::/64 preferred 3min 20s valid 5min
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Configuring route: dst: 2001:db8:0:f02::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unicast                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Adding prefix route 2001:db8:0:f02::/64
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Assigned prefix 2001:db8:0:f02::/64 from 2001:db8:0:f00::/56 to link                                                                                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Assigning up to 256 prefixes from 2001:db8:0:f00::/56
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Setting unreachable routes for DHCPv6 delegated subnets
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Setting addresses
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: RADV: Next Router Advertisement in 5s
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Remembering route: dst: 2001:db8:0:f03::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: boot, type: unicast                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Remembering route: dst: 2001:db8:0:f03::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast                                                                 
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Remembering updated address: 2001:db8:0:f03:205:1bff:feb1:8260/64 (valid for 5min)                                                                                                                     
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Remembering route: dst: 2001:db8:0:f01::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: boot, type: unicast                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Remembering route: dst: 2001:db8:0:f01::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast                                                                 
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Remembering updated address: 2001:db8:0:f01:205:1bff:feb1:8260/64 (valid for 5min)                                                                                                                     
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Remembering route: dst: 2001:db8:0:f05::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: boot, type: unicast                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Remembering route: dst: 2001:db8:0:f05::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast                                                                 
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: Remembering updated address: 2001:db8:0:f05:205:1bff:feb1:8260/64 (valid for 5min)                                                                                                                     
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Remembering route: dst: 2001:db8:0:f04::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: boot, type: unicast                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Remembering route: dst: 2001:db8:0:f04::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast                                                                 
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Remembering updated address: 2001:db8:0:f04:205:1bff:feb1:8260/64 (valid for 5min)                                                                                                                     
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Remembering route: dst: 2001:db8:0:f02::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: boot, type: unicast                                                                   
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Remembering route: dst: 2001:db8:0:f02::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast                                                                 
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Remembering updated address: 2001:db8:0:f02:205:1bff:feb1:8260/64 (valid for 5min)                                                                                                                     
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Remembering updated address: 192.168.1.1/24 (valid forever)
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_314 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=81 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Remembering route: dst: 192.168.1.1/32, src: n/a, gw: n/a, prefsrc: 192.168.1.1, scope: host, table: local, proto: kernel, type: local                                                                 
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Remembering route: dst: 192.168.1.255/32, src: n/a, gw: n/a, prefsrc: 192.168.1.1, scope: link, table: local, proto: kernel, type: broadcast                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Remembering route: dst: 192.168.1.0/24, src: n/a, gw: n/a, prefsrc: 192.168.1.1, scope: link, table: main, proto: kernel, type: unicast                                                                
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Remembering route: dst: 192.168.1.0/32, src: n/a, gw: n/a, prefsrc: 192.168.1.1, scope: link, table: local, proto: kernel, type: broadcast                                                             
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Remembering route: dst: fdda:5f29:421c:1::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast                                                               
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Remembering updated address: fdda:5f29:421c:1::1/64 (valid forever)                                                                                                                                    
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: Addresses set
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: link_check_ready(): an address 2001:db8:0:f01:205:1bff:feb1:8260/64 is not ready.                                                                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Remembering updated address: 192.168.2.1/24 (valid forever)
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_313 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=82 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Remembering route: dst: 192.168.2.1/32, src: n/a, gw: n/a, prefsrc: 192.168.2.1, scope: host, table: local, proto: kernel, type: local                                                                 
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Remembering route: dst: 192.168.2.255/32, src: n/a, gw: n/a, prefsrc: 192.168.2.1, scope: link, table: local, proto: kernel, type: broadcast                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Remembering route: dst: 192.168.2.0/24, src: n/a, gw: n/a, prefsrc: 192.168.2.1, scope: link, table: main, proto: kernel, type: unicast                                                                
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Remembering route: dst: 192.168.2.0/32, src: n/a, gw: n/a, prefsrc: 192.168.2.1, scope: link, table: local, proto: kernel, type: broadcast                                                             
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Remembering route: dst: fdda:5f29:421c:2::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast                                                               
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Remembering updated address: fdda:5f29:421c:2::1/64 (valid forever)                                                                                                                                    
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: Addresses set
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget2: link_check_ready(): an address fdda:5f29:421c:2::1/64 is not ready.                                                                                                                                    
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Remembering updated address: 192.168.3.1/24 (valid forever)
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_312 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=83 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Remembering route: dst: 192.168.3.1/32, src: n/a, gw: n/a, prefsrc: 192.168.3.1, scope: host, table: local, proto: kernel, type: local                                                                 
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Remembering route: dst: 192.168.3.255/32, src: n/a, gw: n/a, prefsrc: 192.168.3.1, scope: link, table: local, proto: kernel, type: broadcast                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Remembering route: dst: 192.168.3.0/24, src: n/a, gw: n/a, prefsrc: 192.168.3.1, scope: link, table: main, proto: kernel, type: unicast                                                                
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Remembering route: dst: 192.168.3.0/32, src: n/a, gw: n/a, prefsrc: 192.168.3.1, scope: link, table: local, proto: kernel, type: broadcast                                                             
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Remembering route: dst: fdda:5f29:421c:3::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast                                                               
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Remembering updated address: fdda:5f29:421c:3::1/64 (valid forever)                                                                                                                                    
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: Addresses set
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: link_check_ready(): an address 2001:db8:0:f03:205:1bff:feb1:8260/64 is not ready.                                                                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Remembering updated address: 192.168.4.1/24 (valid forever)
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_316 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=84 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Remembering route: dst: 192.168.4.1/32, src: n/a, gw: n/a, prefsrc: 192.168.4.1, scope: host, table: local, proto: kernel, type: local                                                                 
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Remembering route: dst: 192.168.4.255/32, src: n/a, gw: n/a, prefsrc: 192.168.4.1, scope: link, table: local, proto: kernel, type: broadcast                                                           
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Remembering route: dst: 192.168.4.0/24, src: n/a, gw: n/a, prefsrc: 192.168.4.1, scope: link, table: main, proto: kernel, type: unicast                                                                
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Remembering route: dst: 192.168.4.0/32, src: n/a, gw: n/a, prefsrc: 192.168.4.1, scope: link, table: local, proto: kernel, type: broadcast                                                             
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Remembering route: dst: fdda:5f29:421c:4::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast                                                               
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Remembering updated address: fdda:5f29:421c:4::1/64 (valid forever)                                                                                                                                    
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: Addresses set
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget4: link_check_ready(): an address fdda:5f29:421c:4::1/64 is not ready.                                                                                                                                    
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: Unreachable routes for DHCPv6 delegated subnets set
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: link_check_ready(): dhcp4:no dhcp6_addresses:yes dhcp_routes:yes dhcp_pd_addresses:no dhcp_pd_routes:no ndisc_addresses:yes ndisc_routes:yes                                                     
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: enx00051bb03daa: State changed: configuring -> configured
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=85 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a                                                                                                            
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: DHCPv6 prefix delegation routes set
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: link_check_ready(): an address 2001:db8:0:f03:205:1bff:feb1:8260/64 is not ready.                                                                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: DHCPv6 delegated prefix addresses set
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget3: link_check_ready(): an address 2001:db8:0:f03:205:1bff:feb1:8260/64 is not ready.                                                                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: DHCPv6 prefix delegation routes set
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: link_check_ready(): an address 2001:db8:0:f01:205:1bff:feb1:8260/64 is not ready.                                                                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: DHCPv6 delegated prefix addresses set
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget1: link_check_ready(): an address 2001:db8:0:f01:205:1bff:feb1:8260/64 is not ready.                                                                                                                      
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: DHCPv6 prefix delegation routes set
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: link_check_ready(): static addresses are not configured.
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: pdtarget5: DHCPv6 delegated prefix addresses set
Jul 22 23:59:01 mamarley-laptop systemd-networkd[3545]: Assertion 'link->addresses_configured' failed at src/network/networkd-link.c:1037, function link_request_set_routes(). Aborting.
```

### LINKED ISSUE #16602: network: rename settings about DHCPv6 prefix delegation
Currently, we have three settings to configure DHCPv6 prefix delegation.
```
[Network]
IPv6PDSubnetId=
[DHCPv6]
AssignAcquiredDelegatedPrefixAddress=
AssignAcquiredDelegatedPrefixToken=
```
I think we should introduce a new section and rename the settings like follows:
```
[DHCPv6PrefixDelegation]
SubnetID=
Assign=
Token=
```
@poettering, @keszybz, @ssahani, @andir and @mamarley. WDYT?

Note that all the above settings are introduced after v245. So, if they should be renamed, that should be done before v246 release.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #16602.
Fixes #16546.
Fixes #15455.
Fixes #13564.
Hopefully fixes #13218.

### CODE REVIEW

**Comment by yuwata** [comment]
@keszybz and @poettering PTAL. @mamarley already tested this and it works fine now, yah!

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -1183,8 +1183,11 @@ void link_check_ready(Link *link) {
                         return;
                 }
 
-                if ((link_dhcp4_enabled(link) || link_dhcp6_enabled(link)) && set_isempty(link->addresses)) {
-                        log_link_debug(link, "%s(): DHCP4 or DHCP6 is enabled but no address is assigned yet.", __func__);
+                if ((link_dhcp4_enabled(link) || link_dhcp6_enabled(link) || link_dhcp6_pd_is_enabled(link)) &&
+                    !link->dhcp_address && !set_isempty(link->dhcp6_addresses) &&
```
Comment (keszybz) [inline src/network/networkd-link.c]: Isn't the condition inverted here? I'd expect `!link->dhcp_address && set_isempty(link->dhcp6_addresses) && ...`

Comment (yuwata) [reply src/network/networkd-link.c]: Ouch! Fixed.

File: src/network/networkd-address.c [hunk 2]
```diff
@@ -359,15 +359,21 @@ int address_update(
...
+                        if (r < 0)
+                                return r;
+                }
 
-                r = link_ipv6ll_gained(address->link, &address->in_addr.in6);
-                if (r < 0)
-                        return r;
+                if (address->family == AF_INET6 &&
+                    in_addr_is_link_local(AF_INET6, &address->in_addr) > 0 &&
+                    in_addr_is_null(AF_INET6, (const union in_addr_union*) &address->link->ipv6ll_address) > 0) {
```
Comment (poettering) [inline src/network/networkd-address.c]: `IN6_IS_ADDR_UNSPECIFIED(&address->link->ipv6ll_address)`

File: src/network/networkd-link.c [hunk 3]
```diff
@@ -1272,23 +1308,48 @@ static int address_handler(sd_netlink *rtnl, sd_netlink_message *m, Link *link)
...
+                a = set_first(link->static_addresses);
+                if (!a) {
+                        log_link_warning(link, "No static address is stored.");
+                        link_enter_failed(link);
+                }
+                if (!a->callback) {
+                        log_link_warning(link, "Address ready callback is not set.");
+                        link_enter_failed(link);
+                }
+                r = a->callback(a);
```
Comment (poettering) [inline src/network/networkd-link.c:1328]: this will segfault if a->callback is actually NULL. You forgot a return further up...

Comment (yuwata) [reply src/network/networkd-link.c:1328]: Oh, thanks. Updated.

**Comment by yuwata** [comment]
Two more commits are added for #16602.

**Comment by mamarley** [comment]
I wonder if it might be a good idea to have the new configuration section name more explicitly reflect that it handles the receiving end of prefix delegation (versus the existing [IPv6PrefixDelegation] section that handles the "sending" end).

Also, I may be out of my depth with this, but it seems to me that a separate PR for the renaming might be a better way to organize things.

**Comment by poettering** [comment]
the settings moved to the new sections need a NEWS update too, because they are mentioned there too

**Comment by mamarley** [comment]
Now that this is merged, when I try the new configuration options, I keep getting `Unknown section 'DHCPv6PrefixDelegation'. Ignoring.` for every time the section appears.  I'm not sure if I'm just doing something dumb or if something is broken, but I'm not seeing anything wrong with my configuration.

**Comment by mamarley** [comment]
Yep, it looks like declaring the new section was missed in networkd-network.c.  https://github.com/systemd/systemd/pull/16616 opened.
