### PR TITLE
sd-journal: reset saved direction on seek

### LINKED ISSUE #29216: Journal seeking broken in v254
### systemd version the issue has been seen with

254.3-1

### Used distribution

Arch Linux

### Linux kernel version used

6.5.3-zen1-1-zen

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Assuming the journal is not empty, stepping to the previous entry after seek_tail always works.

### Unexpected behaviour you saw

`seek_tail` > `previous` > `seek_tail` > `previous` encounters an EOF, see reproducer.

### Steps to reproduce the problem

```c
#include <systemd/sd-journal.h>
#include <stdio.h>

#define dbg(x) do { int ret = (x); printf(#x " returned %d\n", ret); } while (0)

int main (void) {
    sd_journal *j;
    dbg(sd_journal_open(&j, 0));
    dbg(sd_journal_seek_tail(j));
    dbg(sd_journal_previous(j));
    dbg(sd_journal_seek_tail(j));
    dbg(sd_journal_previous(j));
    return 0;
}
```

outputs:

```
sd_journal_open(&j, 0) returned 0
sd_journal_seek_tail(j) returned 0
sd_journal_previous(j) returned 1
sd_journal_seek_tail(j) returned 0
sd_journal_previous(j) returned 0
```

The second `sd_journal_previous` did not manage to move the cursor.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #29216.

### CODE REVIEW

File: src/journal/test-journal-interleaving.c [hunk 1]
```diff
@@ -185,6 +185,15 @@ static void test_skip_one(void (*setup)(void)) {
         test_check_numbers_down(j, 9);
         sd_journal_close(j);
 
+        /* Seek to head twice, iterate down. */
+        assert_ret(sd_journal_open_directory(&j, t, 0));
+        assert_ret(sd_journal_seek_head(j));
+        assert_se(sd_journal_next(j) == 1);     /* pointing the first entry */
+        assert_ret(sd_journal_seek_head(j));
+        assert_se(sd_journal_next(j) == 1);     /* pointing the first entry */
```
Comment (keszybz) [inline src/journal/test-journal-interleaving.c]: A preexisting condition, but "point the first entry" is not a valid sentence. "Pointing to the first entry" or "pointing at the first entry" or "before" or "after".

**Review by keszybz — APPROVED** [review]

File: src/journal/test-journal-interleaving.c (hunk 1 above)
Comment (yuwata) [reply src/journal/test-journal-interleaving.c]: Thanks. `to` is inserted.

**Review by bluca — APPROVED** [review]
