### PR TITLE
 core: fix EBUSY on restart of delegated services

### LINKED ISSUE #41278: Sporadic unit failures due to cgroup reuse and failure to cleanup
An educated guess is that this might have been caused by https://github.com/systemd/systemd/pull/36815/commits/f8f67eab70737549325a718d66c589847043516a

pidfd_spawn fails with EBUSY:

`systemd[1]: systemd-nspawn@long-running.service: Failed to spawn executor: Device or resource busy`

```
EBUSY (clone3() only)
       CLONE_INTO_CGROUP was specified in cl_args.flags, but the file descriptor specified  in  cl_args.cgroup
       refers to a version 2 cgroup in which a domain controller is enabled.
```

The guess is that cleaning up the cgroup fails, so when trying to reuse it for the stop-post it already has controllers enabled and fails.

https://github.com/systemd/systemd/actions/runs/23415844622/job/68166700340?pr=41242

[TEST-13-NSPAWN-1.journal.gz](https://github.com/user-attachments/files/26182053/TEST-13-NSPAWN-1.journal.gz)

### PR DESCRIPTION
**Pull request by naraghavan2186**
When a service is configured with Delegate=yes and DelegateSubgroup=sub, the delegated container may write domain controllers (e.g. "pids") into the service cgroup's cgroup.subtree_control via its cgroupns root. On container exit the stale controllers remain, and on service restart clone3() with  CLONE_INTO_CGROUP fails with EBUSY because placing a process into a cgroup  that has domain controllers in subtree_control violates the no-internal-processes rule.

Fix by calling cg_enable(mask=0) in unit_prune_cgroup() right after cg_trim(). This clears any stale controllers from subtree_control as part of  normal service cgroup cleanup, restoring a clean state for the next start. If cg_trim() fails (e.g. sub-cgroups still have live processes), the cg_enable() will also fail and is silently ignored — the next start will
fail with EBUSY, which is the correct visible outcome.

Fixes [41278](https://github.com/systemd/systemd/issues/41278)

### CODE REVIEW

File: src/core/execute.c [hunk 1]
```diff
@@ -520,6 +520,17 @@ int exec_spawn(
...
 
+        /* For delegated units with a delegate_subgroup, a previous run of the service may have enabled
+         * domain controllers (e.g. "pids") in the service cgroup's cgroup.subtree_control via a cgroup
+         * namespace root write. When the process exits the sub-cgroup stays and the stale controllers
+         * remain. On restart, clone3(CLONE_INTO_CGROUP) targeting the service cgroup then fails with
+         * EBUSY because the cgroup would become an "internal" node with a domain controller enabled.
+         * Proactively clear all controllers from subtree_control before spawning the main process.
+         * Only do this for the main process spawn (not control process spawns), because control processes
+         * are already placed into a fresh subcgroup. */
+        if (cgtarget && FLAGS_SET(params->flags, EXEC_CGROUP_DELEGATE) && !exec_params_needs_control_subcgroup(params))
```
Comment (YHNdnzj) [inline src/core/execute.c]: this doesn't look right. It means all controllers are disabled again before each ExecStartPre=, no? Instead, maybe disable all controllers if cg_trim() fails in unit_prune_cgroup()?

File: src/basic/process-util.c [hunk 2]
```diff
@@ -2079,6 +2079,18 @@ int posix_spawn_wrapper(
         if (ERRNO_IS_NOT_SUPPORTED(r) && FLAGS_SET(flags, POSIX_SPAWN_SETCGROUP) && cg_is_threaded(cgroup) > 0)
                 return -EUCLEAN; /* clone3() could also return EOPNOTSUPP if the target cgroup is in threaded mode,
                                     turn that into something recognizable */
+        if (r == -EBUSY && FLAGS_SET(flags, POSIX_SPAWN_SETCGROUP)) {
+                /* clone3(CLONE_INTO_CGROUP) failed because the target cgroup has domain controllers enabled
+                 * in cgroup.subtree_control, violating the no-internal-processes rule. This is a transient
+                 * per-cgroup condition (stale state from a delegated container's previous run), unlike the
+                 * permanent EOPNOTSUPP/privilege cases. Do NOT permanently disable CLONE_INTO_CGROUP;
+                 * fall back for this spawn only and let the caller move the child via cg_attach(). */
```
Comment (YHNdnzj) [inline src/basic/process-util.c]: hmm? why? if the clone3() fails, any attempt to migrate the process later would also fail? this just shifts the timing a bit? I'm pretty sure we should not hide the error here...

Comment (naraghavan2186) [reply src/basic/process-util.c]: If cg_enable(mask=0) in exec_spawn succeeds -> clone3() succeeds -> no EBUSY at all
If cg_enable(mask=0) fails (stale sub/ cgroup still holds the controllers) -> clone3() returns EBUSY -> the fallback spawns without CLONE_INTO_CGROUP -> caller does cg_attach() -> also EBUSY for identical reason -> process runs in wrong cgroup, error silently.
As you mentioned fallback just delays the failure. The right behaviour is to propagate EBUSY back to exec_spawn so the service fails loudly with a clear error and not quietly. The posix_spawn_wrapper is also a generic utility that should not be encoding cgroup-specific workaround logic.

File: src/core/execute.c (hunk 1 above)
Comment (naraghavan2186) [reply src/core/execute.c]: My original intent was a to have guard close to the clone3() call and clear stale state immediately before the spawn that would fail, so the fix is self-contained regardless of whether cleanup ran correctly at stop time. The flaw is that !exec_params_needs_control_subcgroup() is also true for ExecStartPre=, so it ran on every pre-start spawn including a clean first start.
Moved to unit_prune_cgroup() after cg_trim() — the right place since stale subtree_control entries are a cleanup concern, and unit_cgroup_delegate(u) scopes it correctly.

**Review by daandemeyer — APPROVED** [review]

**Comment by daandemeyer** [comment]
@naraghavan-msft Actually I don't see the point of running this on success of cg_trim() unless it's the root slice that will remove the top level node of the cgroup, and there won't be any subtree_control file left to write, shouldn't we only run this on failure of cg_trim() like @YHNdnzj suggested?

**Comment by YHNdnzj** [comment]
hmm, thinking more about this, maybe we should defer this until the next cycle of service actually gets invoked? i.e. service_start() - right above where we set crt->reset_accounting? This way the leftover processes do not have the resource control lifted immediately?

**Comment by naraghavan2186** [comment]
> @naraghavan-msft Actually I don't see the point of running this on success of cg_trim() unless it's the root slice that will remove the top level node of the cgroup, and there won't be any subtree_control file left to write, shouldn't we only run this on failure of cg_trim() like @YHNdnzj suggested?

@daandemeyer  

The unconditional call is intentional and safe in all three cases:

cg_trim() succeeds, non-root slice - the cgroup directory is rmdir, so cg_enable() gets ENOENT and fails silently. It is harmless
cg_trim() fails -  the cgroup survives (live processes in sub-cgroups); clearing subtree_control here is exactly the point.
Root slice - cg_trim() is called with delete_root=false, so the root cgroup directory always remains. Clearing stale controllers on the root slice needs to happen even on cg_trim() success, so putting this exclusively in the failure branch would silently miss this case.
Moving the call into the failure branch alone would handle case 2 but break case 3. The unconditional placement with (void) is simpler and covers all cases correctly.
Kindly let me know if you think otherwise

**Comment by naraghavan2186** [comment]
> hmm, thinking more about this, maybe we should defer this until the next cycle of service actually gets invoked? i.e. service_start() - right above where we set crt->reset_accounting? This way the leftover processes do not have the resource control lifted immediately?

Deferring to service_start() would only cover services, not scopes/slices. Also, crt->cgroup_path may still be stale at that point - unit_realize_cgroup() hasn't run yet. Cleanup belongs in unit_prune_cgroup() where the cgroup lifetime is being managed.

**Comment by YHNdnzj** [comment]
> Deferring to service_start() would only cover services, not scopes/slices.

scopes won't suffer from this problem as it is not restartable. And slices cannot contain processes, it is the cgroup subtree primitive after all and is fully managed.

> Also, crt->cgroup_path may still be stale at that point - unit_realize_cgroup() hasn't run yet.

Not really? unit_maybe_release_cgroup() would refuse to clear cgroup_path if the cg is not empty. So exactly when we see a "stale" cgroup_path we need to go out of the way to disable potentially dangling controllers.

> Cleanup belongs in unit_prune_cgroup() where the cgroup lifetime is being managed.

Yeah, that's why I initially proposed that. But by deferring the cleanup, we ensure the controllers are kept active as long as processes from previous invocation haven't exited. If restart is _not_ requested, we'd have the chance to do comprehensive cleanup later once we see the cgroup empty event. I think this is generally more preferable, but I'd not block the PR if you insist on the current approach.

**Comment by naraghavan2186** [comment]
> > Deferring to service_start() would only cover services, not scopes/slices.
> 
> scopes won't suffer from this problem as it is not restartable. And slices cannot contain processes, it is the cgroup subtree primitive after all and is fully managed.
> 
> > Also, crt->cgroup_path may still be stale at that point - unit_realize_cgroup() hasn't run yet.
> 
> Not really? unit_maybe_release_cgroup() would refuse to clear cgroup_path if the cg is not empty. So exactly when we see a "stale" cgroup_path we need to go out of the way to disable potentially dangling controllers.
> 
> > Cleanup belongs in unit_prune_cgroup() where the cgroup lifetime is being managed.
> 
> Yeah, that's why I initially proposed that. But by deferring the cleanup, we ensure the controllers are kept active as long as processes from previous invocation haven't exited. If restart is _not_ requested, we'd have the chance to do comprehensive cleanup later once we see the cgroup empty event. I think this is generally more preferable, but I'd not block the PR if you insist on the current approach.

@YHNdnzj  Thank you for the suggestion. I have now moved the cg_enable(mask=0) from unit_prune_cgroup() to service_start(), right above crt->reset_accounting as you suggested. This way resource control stays intact for lingering processes until the next start cycle actually begins.

**Comment by poettering** [comment]
claude is right, that needs fixing

**Comment by poettering** [comment]
hmm, given this would then touch the cgroup runtime object I'd feel more comfortable if the code would move to src/core/cgroup.c. 

i.e. add a new helper unit_cgroup_disable_all_controllers() that takes a unit, and hides the logic, and that is simply called from service_start().

**Comment by keszybz** [comment]
FWIW, this failure is observed in CI in `test/units/TEST-74-AUX-UTILS.capsule.sh`: `systemctl clean capsule@foobar.service --what=all` fails with -EBUSY when trying to join the cgroup:
```
systemd[1]: Successfully forked off '(sd-rmrf)' as PID 582.
systemd[1]: capsule@foobar.service: Changed dead -> cleaning
systemd[1]: Found unit capsule@foobar.service at /usr/lib/systemd/system/capsule@.service (regular file)
(sd-rmrf)[582]: capsule@foobar.service: Failed to join unit cgroup /capsule.slice/capsule@foobar.service: Device or resource busy
systemd[1]: Received SIGCHLD.
systemd[1]: Child 582 ((sd-rmrf)) died (code=exited, status=219/CGROUP)
systemd[1]: capsule@foobar.service: Control process exited, code=exited, status=219/CGROUP
```
That -EBUSY comes from `cg_attach`.

**Review by keszybz — COMMENTED** [review]
I think this latest approach looks very reasonable. Please implement the two things mentioned by Lennart.

**Comment by naraghavan2186** [comment]
> hmm, given this would then touch the cgroup runtime object I'd feel more comfortable if the code would move to src/core/cgroup.c.
> 
> i.e. add a new helper unit_cgroup_disable_all_controllers() that takes a unit, and hides the logic, and that is simply called from service_start().

i have fixed this by adding the logic into a new unit_cgroup_disable_all_controllers() helper in src/core/cgroup.c that takes a Unit*, clears stale controllers via cg_enable(mask=0), logs at debug level on failure, and updates crt->cgroup_enabled_mask only on success. service_start() now just calls the helper.

**Comment by naraghavan2186** [comment]
> I think this latest approach looks very reasonable. Please implement the two things mentioned by Lennart.

Thanks for pointing out the systemctl clean path. I have added a unit_cgroup_disable_all_controllers(u) call in service_clean() as well, right before unit_fork_and_watch_rm_rf(), so the stale controllers are cleared before theworker tries to cg_attach(). Same helper and same guard checks , so this should fix the EBUSY seen in the CI.

File: src/core/cgroup.c [hunk 3]
```diff
@@ -4002,6 +4002,33 @@ bool unit_cgroup_delegate(Unit *u) {
...
+        if (!unit_cgroup_delegate(u))
+                return;
+
+        /* For delegated units, the previous payload may have enabled controllers (e.g. "pids") in
+         * cgroup.subtree_control. These persist after the service stops and turn the cgroup into an
+         * "internal node", causing clone3(CLONE_INTO_CGROUP) to fail with EBUSY. Clear them now, right
+         * before the new start, so that resource control is preserved for lingering processes as long as
+         * possible. Ignore errors — if sub-cgroups still have live processes the write will fail, but so
+         * will the upcoming spawn. */
+        r = cg_enable(u->manager->cgroup_supported, /* mask= */ 0, crt->cgroup_path, /* ret_result_mask= */ NULL);
```
[the remark this answers is not in the document]
Comment (naraghavan2186) [reply src/core/cgroup.c]: Fixed it

File: src/core/cgroup.c [hunk 4]
```diff
@@ -4002,6 +4002,33 @@ bool unit_cgroup_delegate(Unit *u) {
         return c->delegate;
 }
 
+void unit_cgroup_disable_all_controllers(Unit *u) {
```
[the remark this answers is not in the document]
Comment (naraghavan2186) [reply src/core/cgroup.c:4005]: followed the suggestion from Lennart.. Ignoring this for now.

**Review by bluca — APPROVED** [review]

**Review by keszybz — COMMENTED** [review]
Nice, thanks.
