### PR TITLE
bootspec: choose correct default entry

### LINKED ISSUE #7727: bootctl list command marks incorrect entry as "(default)"
### systemd version the issue has been seen with
236.0-2

$ bootctl --version
systemd 236
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution
Arch Linux (x86_64)

### In case of bug report: Expected behaviour you didn't see
```
# bootctl list
...
title: Arch Linux speedboot (default)
...
```

### In case of bug report: Unexpected behaviour you saw
```
# bootctl list
...
title: Arch Linux (default)
…
```

### In case of bug report: Steps to reproduce the problem
```
# efibootmgr
No BootOrder is set; firmware will attempt recovery
$ ls -l /boot/loader/entries/
total 16
-rwxr-xr-x 1 root root 218 Mar 20  2017 arch-fallback-break.conf
-rwxr-xr-x 1 root root 171 Mar 20  2017 arch-fallback.conf
-rwxr-xr-x 1 root root 204 Nov 25 22:47 arch-tiny.conf
-rwxr-xr-x 1 root root 153 Mar 17  2017 arch.conf
$ cat /boot/loader/loader.conf
timeout 1
default arch-tiny
editor 1
$ grep title /boot/loader/entries/arch-tiny.conf
title Arch Linux speedboot
$ grep title /boot/loader/entries/arch.conf
title Arch Linux
$ grep initrd /boot/loader/entries/arch-tiny.conf
initrd /intel-ucode.img
initrd /initramfs-linux-tiny.img
$ grep initrd /boot/loader/entries/arch.conf
initrd /intel-ucode.img
initrd /initramfs-linux.img
# reboot
$ cat /proc/cmdline
initrd=\intel-ucode.img initrd=\initramfs-linux-tiny.img root=PARTUUID=c...3 rw fbcon=scrollback:128k iomem=relaxed
```

### PR DESCRIPTION
**Pull request by yuwata**
The boot loader `systemd-boot` removes ".conf" from file name of entry configs, and determine which entry is the default entry. However, bootspec, which is used by `systemctl` and `bootctl` did not remove ".conf", then sometimes `bootctl` marks wrong entry as default.
This Fixes the logic to choose the default entry in bootspec, to match the logic used in `systemd-boot` boot loader.

Fixes #7727.

### CODE REVIEW

File: src/shared/bootspec.c [hunk 1]
```diff
@@ -52,22 +52,28 @@ void boot_entry_free(BootEntry *entry) {
...
 
         assert(path);
         assert(entry);
 
-        f = fopen(path, "re");
-        if (!f)
-                return log_error_errno(errno, "Failed to open \"%s\": %m", path);
+        c = endswith_no_case(path, ".conf");
+        if (!c)
+                return log_error("Invalid loader entry filename: %s", path);
```
Comment (poettering) [inline src/shared/bootspec.c]: log_error() returns "0". That's not intended here, is it? Should probably be `{ log_error(…); return -EINVAL; }` or so

Comment (yuwata) [reply src/shared/bootspec.c]: Thank you. Fixed.

**Comment by yuwata** [comment]
I've force-pushed an updated version, which fixes the wrong return value. PTAL.
