### PR TITLE
sd-bus/bus-track: use install_callback in sd_bus_track_add_name()

### LINKED ISSUE #32381: systemd unexpectedly(?) terminates units with `Unexpected error response from GetNameOwner(): Connection terminated` during a "mount storm"
We have an internal customer that started experiencing unexpected restarts of certain units on their OpenShift clusters. After analyzing logs the symptoms looked very similar to [this issue](https://github.com/systemd/systemd/issues/15316), since the affected units reported `Unexpected error response from GetNameOwner(): Connection terminated` just before getting restarted. However, we already have patches for that in RHEL.

Another candidate was https://github.com/systemd/systemd/issues/30573, but I failed to reproduce that issue on multiple machines with several reproducers I could come up with. However, after putting these reproducers together with a couple of other hints from customer's logs, I was able to _conjure_ a slightly different (and _spiced up_) reproducer, that appears to reproduce the issue the customer is facing not only on RHELs, but also on Fedora Rawhide, and the latest systemd upstream (af46138f39acb55f1faefcb48ebc3316efac87b4 ATTOW, also on Rawhide). In all cases `dbus-broker` was used as the dbus... broker.

Reproducer:
```bash
#/bin/bash
set -eux
set -o pipefail

NMOUNTS=800
MPOINT="$(findmnt --mountpoint / --noheading -o SOURCE)"
TS="$(date +"%s.%N")"

systemctl mask --now --runtime systemd-oomd.{socket,service}
id testuser || useradd testuser
systemctl stop "tmp-mnt*.mount" || :
systemctl log-level debug

for i in {0..100}; do
        echo "=== $i ==="
        for i in $(seq 0 $NMOUNTS); do
                mkdir -p "/tmp/mnt$i"
                systemd-mount "$MPOINT" "/tmp/mnt$i" &
        done
        wait
        for i in $(seq 0 $NMOUNTS); do
                systemd-umount "/tmp/mnt$i" &
        done
        wait

        busctl status --user --machine=testuser@ --no-pager
        systemctl stop user@4711.service
        (! journalctl --since="@$TS" --grep "Connection terminated")
done
```

With this reproducer I get following output in a couple of iterations (really depends on the machine you run this on and your luck):
```
# systemctl --version
systemd 256~devel (256~devel-gaf46138)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT -LIBARCHIVE
# ./repro.sh
...
++ systemctl stop user@4711.service
++ journalctl --since=@1713626172.951606857 --grep 'Connection terminated'
-- No entries --
++ for i in {0..100}
++ echo '=== 1 ==='
=== 1 ===
+++ seq 0 800
...
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
Failed to stop automount unit: Connection timed out
++ busctl status --user --machine=testuser@ --no-pager
BusAddress=unixexec:path=systemd-run,argv1=-M.host,argv2=-PGq,argv3=--wait,argv4=-pUser%3dtestuser,argv5=-pPAMName%3dlogin,argv6=systemd-stdio-bridge,argv7=-punix:path%3d%24%7bXDG_RUNTIME_DIR%7d/bus
BusID=db15434bb5619733c1ee88f5c4c006b1
PID=8351
PIDFD=yes
EUID=0
EGID=0
SupplementaryGIDs=0
Label=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
++ systemctl stop user@4711.service
++ journalctl --since=@1713626172.951606857 --grep 'Connection terminated'
Apr 20 11:25:30 xxx systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 20 11:25:30 xxx systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminat>
Apr 20 11:25:30 xxx systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 20 11:25:30 xxx systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 20 11:25:30 xxx systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 20 11:25:30 xxx systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 20 11:25:30 xxx systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 20 11:25:30 xxx systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
...
```

More details from the journal:
```
...
[  747.889938] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/tmp_2dmnt199_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=8 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[  747.889987] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/tmp_2dmnt199_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[  747.890050] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/tmp_2dmnt199_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=470 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[  747.890101] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/tmp_2dmnt199_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=471 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[  747.890152] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/tmp_2dmnt199_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=314 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[  747.890199] systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/tmp_2dmnt199_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=315 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[  764.600613] systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.687538] systemd[1]: systemd-homed.service: Deactivated successfully.
[  764.687805] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-homed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  764.736119] systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.736517] audit: BPF prog-id=49 op=UNLOAD
[  764.737643] systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.738216] systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.738638] NetworkManager[768]: <info>  [1713626730.6956] caught SIGTERM, shutting down normally.
[  764.739340] NetworkManager[768]: <info>  [1713626730.6963] dhcp4 (eth0): canceled DHCP transaction
[  764.739428] NetworkManager[768]: <info>  [1713626730.6963] dhcp4 (eth0): activation: beginning transaction (timeout in 45 seconds)
[  764.739488] NetworkManager[768]: <info>  [1713626730.6963] dhcp4 (eth0): state changed no lease
[  764.739568] NetworkManager[768]: <info>  [1713626730.6965] manager: NetworkManager state is now CONNECTED_SITE
[  764.741702] NetworkManager[768]: <info>  [1713626730.6988] exiting (success)
[  764.785825] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  764.785993] systemd[1]: NetworkManager.service: Deactivated successfully.
[  764.834007] systemd[1]: avahi-daemon.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.834605] avahi-daemon[744]: Got SIGTERM, quitting.
[  764.835133] avahi-daemon[744]: Leaving mDNS multicast group on interface eth0.IPv6 with address 2620:52:0:bb:f816:3eff:fe67:3519.
[  764.835201] avahi-daemon[744]: Leaving mDNS multicast group on interface eth0.IPv4 with address 10.0.187.174.
[  764.835251] avahi-daemon[744]: Leaving mDNS multicast group on interface lo.IPv6 with address ::1.
[  764.835321] avahi-daemon[744]: Leaving mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
[  764.835399] avahi-daemon[744]: avahi-daemon 0.8 exiting.
[  764.881474] systemd[1]: avahi-daemon.service: Deactivated successfully.
[  764.881747] audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=avahi-daemon comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  764.968329] systemd[1]: systemd-resolved.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.969842] systemd[1]: systemd-networkd.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.970411] systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
[  764.970969] systemd[1]: systemd-timesyncd.service: Unexpected error response from GetNameOwner(): Connection terminated
...
```

The most problematic part is the unexpected NetworkManager restart (as that's how the customer noticed the issue in the first place). However, the system itself seems to be fine after this _incident_:

```
# systemctl status
● xxx
    State: running
    Units: 397 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
    Since: Sat 2024-04-20 11:12:47 EDT; 18min ago
  systemd: 256~devel-gaf46138
   CGroup: /
...
```

And now for the big questions - is this our issue or somebody else's (dbus-broker?)? And can we do anything about it?

/cc @msekletar @rmetrich

### PR DESCRIPTION
**Pull request by msekletar**
Previously we didn't provide any install_callback to sd_bus_add_match_async() so in case AddMatch() method call timed out we destroyed the bus connection. This seems overly aggressive and simply updating the sd_bus_track object accordingly should be enough.

Follow-up for 37ce3fd2b7dd8f81f6f4bca2003961a92b2963dc.

Fixes #32381

### CODE REVIEW

File: src/libsystemd/sd-bus/bus-track.c [hunk 1]
```diff
@@ -166,17 +167,36 @@ static sd_bus_track* track_free(sd_bus_track *track) {
...
+
+        assert(message);
+        assert(item->track);
+        assert(item->name);
+
+        e = sd_bus_message_get_error(message);
+        if (!e)
+                return 0;
+
+        log_debug_errno(sd_bus_error_get_errno(e), "Failed to install match for tracking name '%s': %s", item->name, e->message);
```
Comment (yuwata) [inline src/libsystemd/sd-bus/bus-track.c]: Maybe better to include error message from `bus_error_message()`?

**Review by yuwata — APPROVED** [review]

**Comment by msekletar** [comment]
@mrc0mmand I am running the reproducer from https://github.com/systemd/systemd/issues/32381 but it would be great if you could also test it.

**Comment by msekletar** [comment]
Updated. @yuwata PTAL.

File: src/libsystemd/sd-bus/bus-track.c [hunk 2]
```diff
@@ -4,6 +4,7 @@
 
 #include "alloc-util.h"
 #include "bus-internal.h"
+#include "bus-error.h"
```
Comment (yuwata) [inline src/libsystemd/sd-bus/bus-track.c:6]: Please sort.

**Review by yuwata — APPROVED** [review]
One more nitpick.

**Comment by mrc0mmand** [comment]
> @mrc0mmand I am running the reproducer from #32381 but it would be great if you could also test it.

I've been running some tests on multiple machines and so far it looks good, thanks!
