### PR TITLE
udev: manipulate device nodes with O_PATH

### LINKED ISSUE #16858: test-repart fails sporadically with 'Failed to make loopback device of future partition 6: Resource temporarily unavailable'
**systemd version the issue has been seen with**
> latest master

**Used distribution**
 > Arch Linux

During yesterday & today I've noticed several runs where the `test-repart` failed with:

```
244/788 test-repart                                                                                 FAIL           1.17s (exit status 1)

--- command ---
18:32:23 /build/src/partition/test-repart.sh /systemd-meson-build/systemd-repart
--- Listing only the last 100 lines from a long log. ---
+ /systemd-meson-build/systemd-repart /tmp/tmp.pi5HXXYq3n/zzz --empty=create --size=1G --seed=e2a40bf9-73f1-4278-9160-49c031e7aef8
Sized '/tmp/tmp.pi5HXXYq3n/zzz' to 1.0G.
Applying changes.
Wiped block device.
Discarded entire block device.
Writing new partition table.
All done.
+ sfdisk -d /tmp/tmp.pi5HXXYq3n/zzz
+ grep -v -e sector-size -e '^$'
+ cmp /tmp/tmp.pi5HXXYq3n/empty -
+ echo '### Testing with root, root2, home, & swap ###'
+ cat
+ ln -s root.conf /tmp/tmp.pi5HXXYq3n/definitions/root2.conf
+ cat
+ cat
+ /systemd-meson-build/systemd-repart /tmp/tmp.pi5HXXYq3n/zzz --dry-run=no --seed=e2a40bf9-73f1-4278-9160-49c031e7aef8 --definitions=/tmp/tmp.pi5HXXYq3n/definitions
[0;1;38;5;185m/tmp/tmp.pi5HXXYq3n/definitions/home.conf:4: Partition label too long for GPT table, ignoring: "home-always-too-long-xxxxxxxxxxxxxx-5.7.12-arch1-1" (from "home-always-too-long-xxxxxxxxxxxxxx-%v")[0m
Applying changes.
Successfully wiped file system signatures from future partition 0.
Successfully discarded data from future partition 0.
Successfully wiped file system signatures from future partition 1.
Successfully discarded data from future partition 1.
Successfully wiped file system signatures from future partition 2.
Successfully discarded data from future partition 2.
Successfully wiped file system signatures from future partition 3.
Successfully discarded data from future partition 3.
Successfully discarded gap after partition 3.
Adding new partition 0 to partition table.
Adding new partition 1 to partition table.
Adding new partition 2 to partition table.
Adding new partition 3 to partition table.
Writing new partition table.
All done.
+ sfdisk -d /tmp/tmp.pi5HXXYq3n/zzz
+ grep -v -e sector-size -e '^$'
+ cmp /tmp/tmp.pi5HXXYq3n/populated -
+ echo '### Testing with root, root2, home, swap, & another partition ###'
+ cat
+ cat
+ echo Label=ignored_label
+ echo UUID=b0b1b2b3b4b5b6b7b8b9babbbcbdbebf
+ /systemd-meson-build/systemd-repart /tmp/tmp.pi5HXXYq3n/zzz --dry-run=no --seed=e2a40bf9-73f1-4278-9160-49c031e7aef8 --definitions=/tmp/tmp.pi5HXXYq3n/definitions
[0;1;38;5;185m/tmp/tmp.pi5HXXYq3n/definitions/home.conf:4: Partition label too long for GPT table, ignoring: "home-always-too-long-xxxxxxxxxxxxxx-5.7.12-arch1-1" (from "home-always-too-long-xxxxxxxxxxxxxx-%v")[0m
Applying changes.
Successfully wiped file system signatures from future partition 4.
Successfully discarded data from future partition 4.
Adding new partition 4 to partition table.
Writing new partition table.
All done.
+ sfdisk -d /tmp/tmp.pi5HXXYq3n/zzz
+ grep -v -e sector-size -e '^$'
+ cmp /tmp/tmp.pi5HXXYq3n/populated2 -
+ echo '### Resizing to 2G ###'
+ /systemd-meson-build/systemd-repart /tmp/tmp.pi5HXXYq3n/zzz --size=2G --dry-run=no --seed=e2a40bf9-73f1-4278-9160-49c031e7aef8 --definitions=/tmp/tmp.pi5HXXYq3n/definitions
[0;1;38;5;185m/tmp/tmp.pi5HXXYq3n/definitions/home.conf:4: Partition label too long for GPT table, ignoring: "home-always-too-long-xxxxxxxxxxxxxx-5.7.12-arch1-1" (from "home-always-too-long-xxxxxxxxxxxxxx-%v")[0m
File '/tmp/tmp.pi5HXXYq3n/zzz' grown from 1.0G to 2.0G by truncation.
Applying changes.
Growing existing partition 4.
Writing new partition table.
All done.
+ sfdisk -d /tmp/tmp.pi5HXXYq3n/zzz
+ grep -v -e sector-size -e '^$'
+ cmp /tmp/tmp.pi5HXXYq3n/populated3 -
+ dd if=/dev/urandom of=/tmp/tmp.pi5HXXYq3n/block-copy bs=4096 count=10240
10240+0 records in
10240+0 records out
41943040 bytes (42 MB, 40 MiB) copied, 0.436799 s, 96.0 MB/s
+ echo '### Testing with root, root2, home, swap, another partition, & partition copy ###'
+ cat
+ /systemd-meson-build/systemd-repart /tmp/tmp.pi5HXXYq3n/zzz --size=3G --dry-run=no --seed=e2a40bf9-73f1-4278-9160-49c031e7aef8 --definitions=/tmp/tmp.pi5HXXYq3n/definitions
[0;1;38;5;185m/tmp/tmp.pi5HXXYq3n/definitions/home.conf:4: Partition label too long for GPT table, ignoring: "home-always-too-long-xxxxxxxxxxxxxx-5.7.12-arch1-1" (from "home-always-too-long-xxxxxxxxxxxxxx-%v")[0m
File '/tmp/tmp.pi5HXXYq3n/zzz' grown from 2.0G to 3.0G by truncation.
Applying changes.
Successfully wiped file system signatures from future partition 5.
Successfully discarded data from future partition 5.
Copying in '/tmp/tmp.pi5HXXYq3n/block-copy' (40.0M) on block level into future partition 5.
Copying in of '/tmp/tmp.pi5HXXYq3n/block-copy' on block level completed.
Adding new partition 5 to partition table.
Writing new partition table.
All done.
+ grep -v -e sector-size -e '^$'
+ sfdisk -d /tmp/tmp.pi5HXXYq3n/zzz
+ cmp /tmp/tmp.pi5HXXYq3n/populated4 -
+ cmp --bytes=41943040 --ignore-initial=0:2147463168 /tmp/tmp.pi5HXXYq3n/block-copy /tmp/tmp.pi5HXXYq3n/zzz
++ id -u
+ '[' 0 == 0 ']'
+ type -P cryptsetup diff losetup
+ echo '### Testing Format=/Encrypt=/CopyFiles='
+ cat
+ /systemd-meson-build/systemd-repart /tmp/tmp.pi5HXXYq3n/zzz --size=auto --dry-run=no --seed=e2a40bf9-73f1-4278-9160-49c031e7aef8 --definitions=/tmp/tmp.pi5HXXYq3n/definitions
[0;1;38;5;185m/tmp/tmp.pi5HXXYq3n/definitions/home.conf:4: Partition label too long for GPT table, ignoring: "home-always-too-long-xxxxxxxxxxxxxx-5.7.12-arch1-1" (from "home-always-too-long-xxxxxxxxxxxxxx-%v")[0m
Automatically determined minimal disk image size as 3.0G.
File '/tmp/tmp.pi5HXXYq3n/zzz' grown from 3.0G to 3.0G by truncation.
Applying changes.
Successfully wiped file system signatures from future partition 6.
Successfully discarded data from future partition 6.
[0;1;31mFailed to make loopback device of future partition 6: Resource temporarily unavailable[0m
+ rm -rf /tmp/tmp.pi5HXXYq3n
```

The Arch image wasn't updated for a while (due to another kernel bug), so it appears to be caused by a code change.

### PR DESCRIPTION
**Pull request by poettering**
This is one of bunch of fixes that hopefully will eventually fix #16858. It's just one small part of a whole though, and a proper fix requires more work.

The main goal with this is to minimize a race where the kernel creates a device node in devtmpfs for us, and we then adjust its ownership/access mode/ACLs/timestamps but in the middle of it the kernel replaces the device node with a new one, and we apply half of it.

This doesn't fix the race fully (we can't, after all the kernel doesn't hand us a ready O_PATH fd to the device node), but it does two things:

1. we'll adjust the node in full now or not at all. we'll not apply partial settings to device nodes (which is problematic security-wise)

2. this removes an error condition where the handler would return EEXIST if the node is replaced in the middle, thus failing the rule application. We now operate systematically: either we apply the rules or we don't because the node went away, but we'll never fail because of it. 

Or to summarize: it's atomic and graceful now, in all conditions: either it's applied or not applied, and if something vanishes in the middle this neither causes an error nor results in partially applied props.

### CODE REVIEW

File: src/udev/udev-node.c [hunk 1]
```diff
@@ -296,16 +297,25 @@ static int node_permissions_apply(sd_device *dev, bool apply_mac,
...
-                        return 0; /* this is necessarily racey, so ignore missing the device */
-                return log_device_debug_errno(dev, errno, "cannot stat() node %s: %m", devnode);
+        node_fd = open(devnode, O_PATH|O_NOFOLLOW|O_CLOEXEC);
+        if (node_fd < 0) {
+                if (errno == ENOENT) {
+                        log_device_debug_errno(dev, errno, "Device node %s is missing, skipping handling.", devnode);
+                        return 0; /* This is necessarily racey, so ignore missing the device */
+                }
+
+                return log_device_debug_errno(dev, errno, "Cannot open node %s: %m", devnode);
```
Comment (keszybz) [inline src/udev/udev-node.c:307]: Preexisting condition, but shouldn't this be higher than debug?

**Review by keszybz — COMMENTED** [review]
bionic-i386 timed out in "upstream", should be unrelated.
