### PR TITLE
core: Prevent corrupting units from stale alias state on daemon-reload

### LINKED ISSUE #37482: Type=notify services sometimes have left-over processes
### systemd version the issue has been seen with

257.5

### Used distribution

Centos 9

### Linux kernel version used

6.11.1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Meta has several daemons running with the following architecture:
1. watchdog@meta-daemon.service starts and sends READY=1 for itself via sd_notify
2. meta-daemon.service starts and is activating
3. watchdog@meta-daemon.service does a healthcheck for meta-daemon.service using sd_pid_notify and sends READY=1. meta-daemon.service is now started
4. Watchdog sends WATCHDOG=1 periodically using sd_pid_notify

With KillMode=control-group, we expect that when meta-daemon.service is started, there are no left-over processes in its control group.

### Unexpected behaviour you saw

We occasionally get the following error with the following symptoms:
```
# 1 - rsyslog goes from starting -> started
May  8 06:47:27 systemd[1]: Started meta-daemon.service

# 2 - Chef runs `systemctl daemon-reload`
May  8 06:47:27 systemd[1]: Reload requested from client PID 1410762 ('systemctl') (unit chef.service)...

# 3 - systemd PID1 sees left-over process
May  8 06:47:28 systemd[1]: meta-daemon.service: Found left-over process 1409036 (meta-daemon) in control group while starting unit. Ignoring.
May  8 06:47:28 systemd[1]: meta-daemon.service: This usually indicates unclean termination of a previous run, or service implementation deficiencies.

# 4 - After reload, systemd PID1 believes rsyslog is not started and starts it again
May  8 06:47:28 systemd[1]: Starting metalos.wds.falcon_proxy.service
```

Luckily, most of our processes are well-behaving and will try to grab their standard port and fail. Systemd then kills all processes in the control group (including the leftover one), restarts the unit and we're in a good state again. But...one of our daemons is not well-behaving and had two instances running in parallel for awhile!

We have never seen this with Type=simple services.

### Steps to reproduce the problem

I have yet to get a reliable repro with debug logs since it happens infrequently and we don't have debug logs by default on our fleet.

I have verified:
1. No misbehaving ExecStartPre= commands are leaving around left-over processes.
2. The watchdog service is using the right PID for pid_notify
3. Naively running a systemd-notify service in a loop with systemctl daemon-reload doesn't reproduce this easily

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### LINKED ISSUE #38817: Overriding a unit with an alias to a different unit causes misbehavior on daemon-reload
### systemd version the issue has been seen with

257.7

### Used distribution

N/A

### Linux kernel version used

N/A

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

Currently, if we have two running units a.service and b.service, and
we make b.service an alias to a.service and do a daemon-reload, then
when b.service is deserialized, its fields will override the fields
of the a.service Unit object.

### Steps to reproduce the problem

The issue is reproduced by the test case in https://github.com/systemd/systemd/pull/38800

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by cdown**
During daemon-reload (or daemon-reexec), when a unit becomes an alias to another unit, deserialising the alias's stale serialised state can corrupt the canonical unit's live runtime state.

Consider this scenario:

1. Before reload:
   - a.service is running
   - b.service was stopped earlier and is dead
   - Both exist as independent units

2. User creates an alias to migrate from b -> a:

   - `ln -s /run/systemd/system/a.service /etc/systemd/system/b.service`

3. daemon-reload triggers serialisation. State file contains both units:
   - a.service -> state=running, cgroup=/system.slice/a.service, PID=1234, ...
   - b.service -> state=dead, cgroup=(empty), no PIDs, ...

4. During deserialisation:
   - Processes a.service: loads Unit A, deserialises -> state=RUNNING
   - Processes b.service: manager_load_unit() detects symlink, returns Unit A
   - unit_deserialize_state(Unit A, ...) overwrites with b's dead state

5. The result is that:
   - Unit A incorrectly shows state=dead despite PID 1234 still running
   - If a.service has Upholds= dependents, catch-up logic sees a.service should be running but is dead
   - systemd starts a.service again -> PID 5678
   - Two instances run: PID 1234 (left-over) and PID 5678 (new)

This bug is deterministic when serialisation orders a.service before b.service.

The root cause is that manager_deserialize_one_unit() calls manager_load_unit(name, &u) which resolves aliases via unit_follow_merge(), returning the canonical Unit object. However, the code doesn't distinguish between two cases when u->id differs from the requested name from the state file. In the corruption case, we're deserialising an alias entry and unit_deserialize_state() blindly overwrites the canonical unit's fields with stale data from the old, independent unit. The serialised b.service then overwrites Unit A's correct live state.

This commit first scans the serialised unit names, then adds a check after manager_load_unit():

    if (!streq(u->id, name) && set_contains(serialized_units, u->id))
        ...

This detects when the loaded unit's canonical ID (u->id) differs from the serialised name, indicating the name is now an alias for a different unit and the canonical unit also has its own serialised state entry.

If the canonical unit does not have its own serialised state entry, we keep the state entry. That handles cases where the old name is really just a rename, and thus the old name is the only serialised state for the unit. In that case there is no bug, because there is no separate canonical state entry for the stale alias entry to overwrite.

Skipping is safe because:

1. The canonical unit's own state entry will be correctly deserialised regardless of order. This fix only prevents other stale alias entries from corrupting it.
2. unit_merge() has already transferred the necessary data. When b.service became an alias during unit loading, unit_merge() already migrated dependencies and references to the canonical unit.
3. After merging, the alias doesn't have its own runtime state. The serialised data represents b.service when it was independent, which is now obsolete once the canonical unit also has its own serialised entry.
4. All fields are stale. unit_deserialize_state() would overwrite state, timestamps, cgroup paths, pids, etc. There's no scenario where we want this data applied on top of the canonical unit's own serialised state.

This fix also correctly handles unit precedence. For example, imagine this scenario:

1. `b.service` is a valid, running unit defined in `/run`.
2. The sysadmin creates `ln -s .../a.service /etc/.../b.service`.
3. On reload, the new symlink in `/etc` overrides the unit in `/run`.

The new perspective from the manager side is that `b.service` is now an alias for `a.service`.

In this case, systemd correctly abandons the old b.service unit, because that's the intended general semantics of unit file precedence. We also do that in other cases, like when a unit file in /etc/systemd/system/ masks a vendor-supplied unit file in /lib/systemd/system/, or when an admin uses systemctl mask to explicitly disable a unit.

In all these scenarios, the configuration with the highest precedence (in /etc/) is treated as the new source of truth. The old unit's definition is discarded, and its running processes are (correctly) abandoned. In that respect we are not doing anything new here.

Some may ask why we shouldn't just ignore the symlink if we think this case will come up. I think there are multiple very strong reasons not to do so:

1. It violates unit precedence. The unit design is built on a strict precedence list. When an admin puts any file in /etc, they are intentionally overriding everything else. If manager_load_unit were to "ignore" this file based on runtime state, it would break this fundamental precedent.
2. It makes daemon-reload stateful. daemon-reload is supposed to be a simple, stateless operation, basically to read the files on disk and apply the new configuration. But doing this would make daemon-reload stateful, because we'd have to read the files on disk, but cross-reference the current runtime state, and...  maybe ignore some files. This is complex and unpredictable.
3. It also completely ignores the user intent. The admin clearly has tried to replace the old service with an alias. Ignoring their instruction is the opposite of what they want.

Fixes: https://github.com/systemd/systemd/issues/38817
Fixes: https://github.com/systemd/systemd/issues/37482

### CODE REVIEW

File: src/core/unit-serialize.c [hunk 1]
```diff
@@ -405,6 +406,98 @@ int unit_deserialize_state_skip(FILE *f) {
...
+                        return 1;
+
+                val = line;
+                r = extract_first_word(&val, &key, "=", EXTRACT_DONT_COALESCE_SEPARATORS);
+                if (r < 0)
+                        return log_error_errno(r, "Failed to extract key from serialization line: %m");
+                if (r == 0 || !key)
+                        continue;
+
+                if (STR_IN_SET(key,
```
Comment (cdown) [inline src/core/unit-serialize.c]: Having a list of these here is not ideal obviously. I'm happy to do some refactor but given these are spread all over the place I think it's probably not realistic. Let me know what you think.

File: src/core/manager-serialize.c [hunk 2]
```diff
@@ -202,6 +202,37 @@ static int manager_deserialize_one_unit(Manager *m, const char *name, FILE *f, F
...
+                 *
+                 * The serialised data represents the old, independent unit. Deserialising this stale state
+                 * would corrupt the canonical unit's live state, so we must discard it.
+                 *
+                 * Take as an example, a.service is running. Someone created symlink b.service -> a.service.
+                 * On first reload, the state file still has b.service as an independent dead unit (from
+                 * before the symlink existed), but b.service now resolves to a.service. We must discard
+                 * b.service's stale dead state to preserve a.service's running state.
+                 */
+                log_warning("Unit file for '%s' was overridden by a symlink to '%s'. Skipping stale state of old unit. Any processes from the overridden unit are now abandoned!",
```
Comment (cdown) [inline src/core/manager-serialize.c]: Open to other suggestions. Usually we are relatively benign with the messages, but I think we should make it clear that something quite bad has happened here.

**Comment by daandemeyer** [comment]
Please cherry pick the commits from https://github.com/systemd/systemd/pull/38800 in here as well so we have test coverage for the fix

**Comment by ikruglov** [comment]
@cdown, thanks for detailed explanation.

A thought: should you deserialize into a dummy unit (outside `m->units`) instead of parsing via `unit_deserialize_state_discard()`? You can later disregard entire unit object, and, perhaps, even gracefully stop it.

**Comment by cdown** [comment]
@DaanDeMeyer I have an integration test that doesn't require fixed ordering patch coming up, once that's done I will move this out of draft :-)

**Comment by cdown** [comment]
@ikruglov That was my first thought as well (to avoid duplicating the parsing logic), but I backed away from it because of side effects. Unit objects are pretty tightly coupled to the manager. If we create a dummy unit, state deserialisation might trigger logic that we really don't want for a stale object like updating global counters, touching cgroups, or attempting to resolve dependencies and altering the dependency graph of other units.

Since we are dealing with corrupted/stale state, it feels much safer to treat this like toxic waste and parse and discard the FDs explicitly without letting the data touch any logic or object lifecycles. It’s a bit more boilerplate, but it guarantees no interaction with the rest of the system

**Comment by cdown** [comment]
Integration test that fails before this patch and passes afterwards is now included.

**Comment by cdown** [comment]
Also to capture some of my thoughts on the discussions elsewhere I've had with @ikruglov and @DaanDeMeyer, I wanted to summarise my feelings on the design decisions made in this patch, and go over alternatives considered and why I think they are the wrong paths to go down.

- Why not ignore the new alias and keep tracking the running process? Because ignoring the alias would break the declarative configuration model. When an administrator places a symlink in /etc/systemd/system/, they are explicitly using systemd's override mechanics to say that this file takes precedence over the one in /run or /usr/lib. If daemon-reload were to look at that symlink and say, "yes, I see you configured an alias, but I'm going to ignore it because a process happens to be running", it would break the fundamental contract that configuration on disk is the source of truth and generally go against the operating model we have.
- Why not make daemon-reload fail in this scenario? Because this would both be inconsistent, and a breaking change that hurts configuration management. First, daemon-reload is a global operation. If we fail the entire reload because of one conflicted unit, we block configuration updates for every other service on the system. This would be disastrous for configuration management tooling which rightly expects daemon-reload to be an idempotent to reconcile disk and memory. Second, systemd already allows this abandonment behavior elsewhere: if you `rm /etc/systemd/system/foo.service` while it is running and reload, pid1 successfully reloads and orphans the process. That's what the user asked for after all. If the user wants different behaviour, they have to _ask_ for different behaviour. This patch ensures consistency with that existing behavior, it's not something new.
- Why not terminate the old process instead of abandoning it? Because daemon-reload must remain a safe, non-destructive operation. While having an unmanaged process is messy, automatically killing it is extremely dangerous. daemon-reload should update configuration, it is not and should not become its job to manage lifecycles. If we changed this, a simple syntax error or a symlink mistake during a deployment could cause daemon-reload to SIGKILL (for example) a running database. That would be much worse than the current situation and is asking for trouble.

It is, ultimately, the user's job to ask us to do the right things, and the best we can do is execute what they asked for in a safe way. If the user fails to do that, systemd's job is still to process their instructions in a safe way. It is not to ignore them, or take proactive actions to "fix" what the user said (like killing processes). Doing so would be even more dangerous, because it involves the service manager guessing the administrator's intent and taking irreversible, destructive action based on that guess.

File: src/core/manager-serialize.c [hunk 3]
```diff
@@ -202,6 +202,37 @@ static int manager_deserialize_one_unit(Manager *m, const char *name, FILE *f, F
...
+                            name,
+                            u->id);
+
+                r = unit_deserialize_state_discard(f, fds);
```
Comment (yuwata) [inline src/core/manager-serialize.c]: Simply, 
```c
return unit_deserialize_state_discard(...);
```

File: src/core/unit-serialize.c [hunk 4]
```diff
@@ -405,6 +406,98 @@ int unit_deserialize_state_skip(FILE *f) {
...
+                               "netns-socket-1",
+                               "ipv4-socket-bind-bpf-link-fd",
+                               "ipv6-socket-bind-bpf-link-fd",
+                               "restrict-ifaces-bpf-fd")) {
+                        /* Value is just the FD number */
+                        int fd;
+
+                        fd = deserialize_fd(fds, val);
+                        if (fd >= 0)
+                                safe_close(fd);
```
Comment (yuwata) [inline src/core/unit-serialize.c]: safe_close() gracefully handle negative errno:
```c
safe_close(deserialize_fd(fds, val));
```

File: src/core/unit-serialize.c [hunk 5]
```diff
@@ -405,6 +406,98 @@ int unit_deserialize_state_skip(FILE *f) {
...
+                                      "ip-bpf-egress-installed",           /* cgroup: <fd> <attach_type> <path> */
+                                      "bpf-device-control-installed",      /* cgroup: <fd> <attach_type> <path> */
+                                      "ip-bpf-custom-ingress-installed",   /* cgroup: <fd> <attach_type> <path> */
+                                      "ip-bpf-custom-egress-installed")) { /* cgroup: <fd> <attach_type> <path> */
+                        /* Single FD keys where fd is first word, followed by additional data */
+                        _cleanup_free_ char *fdv = NULL;
+                        int fd;
+
+                        r = extract_first_word(&val, &fdv, NULL, 0);
+                        if (r > 0) {
```
Comment (yuwata) [inline src/core/unit-serialize.c]: Not necessary to store error code:
```c
if (extract_first_word(...) > 0)
        safe_close(deserialize_fd(...));
```

File: src/core/unit-serialize.c [hunk 6]
```diff
@@ -405,6 +406,98 @@ int unit_deserialize_state_skip(FILE *f) {
...
+                        /* These are PidRef keys: may contain pidfd (format: @<fd>:<pid> or @<fd> or just <pid>) */
+                        const char *e;
+
+                        e = startswith(val, "@");
+                        if (e) {
+                                _cleanup_free_ char *fdstr = NULL;
+                                int fd;
+
+                                r = extract_first_word(&e, &fdstr, ":", 0);
+                                if (r > 0) {
```
Comment (yuwata) [inline src/core/unit-serialize.c]: Also here.

File: src/core/unit-serialize.c [hunk 7]
```diff
@@ -405,6 +406,98 @@ int unit_deserialize_state_skip(FILE *f) {
...
+                const char *val;
+
+                r = read_stripped_line(f, LONG_LINE_MAX, &line);
+                if (r < 0)
+                        return log_error_errno(r, "Failed to read serialization line: %m");
+                if (r == 0)
+                        return 0;
+
+                if (isempty(line))
+                        return 1;
```
Comment (yuwata) [inline src/core/unit-serialize.c]: Seems to not necessary to return `1`. The caller only checks if it is negative or not. Please use `0`.

File: src/core/manager-serialize.c (hunk 2 above)
Comment (yuwata) [inline src/core/manager-serialize.c]: Please mention that the log message is checked in TEST-07-PID1.alias-corruption.sh, so the test case may need to be adjusted when the log message is updated.

File: test/units/TEST-07-PID1.alias-corruption.sh [hunk 8]
```diff
@@ -0,0 +1,142 @@
...
+[Service]
+Type=simple
+ExecStart=/bin/sleep infinity
+EOF
+            done
+
+            systemctl daemon-reload
+
+            # Ensure they are running again (they might have been
+            # abandoned/killed during the transition)
```
Comment (yuwata) [inline test/units/TEST-07-PID1.alias-corruption.sh:200]: When a unit is overridden, the serialization is discarded and the service process is killed, maybe better to check that?

How about to save (not only legit one but also) all sus service PIDs before daemon-reload, and check the consistency between journal entries of 'Skipping stale state...' and killed processes ?

File: test/units/TEST-07-PID1.alias-corruption.sh [hunk 9]
```diff
@@ -0,0 +1,142 @@
...
+    done
+    rm -f /run/systemd/system/legit.service
+    systemctl daemon-reload
+}
+
+trap cleanup_test_units EXIT
+
+setup_test_units
+trigger_bug
+verify_result
```
Comment (yuwata) [inline test/units/TEST-07-PID1.alias-corruption.sh]: I do not think it is necessary to split the test into three sequential functions.
Please merge them.

Also, maybe better to test with `daemon-reexec`?

File: src/core/unit-serialize.c (hunk 1 above)
Comment (yuwata) [reply src/core/unit-serialize.c]: Maybe better to add debugging logs about remaining fds in the fdset after manager_deserialize(), and check it in the integration test? We already log about serialized fds at the beginning of manager_deserialize(). Something similar?

**Review by yuwata — COMMENTED** [review]
I guess this works fine. Several suggestions.

File: src/core/unit-serialize.c (hunk 1 above)
Comment (cdown) [reply src/core/unit-serialize.c]: It looks like some FDs are expected to remain after manager_deserialize(), I think bus FDs, for example, are one of those.

So even with logs, how should this be tested? I'm concerned about fragility. The number of remaining FDs seems not expected to be zero in all cases. Over time we may also have different expected counts. What's your suggested approach?

Comment (cdown) [reply src/core/unit-serialize.c]: @yuwata Any updated thoughts on this? :-)

**Comment by bluca** [comment]
Needs a review from Lennart, might postpone to the next release if it doesn't get finished on time

File: src/core/unit-serialize.c (hunk 1 above)
Comment (yuwata) [reply src/core/unit-serialize.c]: Sorry for late response.

> It looks like some FDs are expected to remain after manager_deserialize(), I think bus FDs, for example, are one of those.
>
> So even with logs, how should this be tested? I'm concerned about fragility. The number of remaining FDs seems not expected to be zero in all cases. Over time we may also have different expected counts. What's your suggested approach?

I thought all FDs should be consumed by deserialization. Not sure what 'bus FDs' means here. Have you checked how many FDs are still in the FDSet after deserialization? What kind of FDs are still there?

BTW, at least on daemon-reload, remaining FDs are anyway closed. And, even daemon-reexec, remaining FDs are closed after manager_distribute_fds(). Hence, even if the list here is incomplete or becomes outdated in a future, that should not be a big problem, I guess.

**Review by yuwata — APPROVED** [review]
LGTM.

File: test/units/TEST-07-PID1.alias-corruption.sh [hunk 10]
```diff
@@ -0,0 +1,177 @@
...
+# 6. We detect this PID change as proof of corruption.
+
+run_test() {
+    local reload_cmd="${1:-daemon-reload}"
+    echo ""
+    echo "========================================="
+    echo "Testing with: systemctl $reload_cmd"
+    echo "========================================="
+
+    cat > /run/systemd/system/legit.service <<'EOF'
```
Comment (keszybz) [inline test/units/TEST-07-PID1.alias-corruption.sh]: Please drop the space after a redirection operator. Below too.

**Review by keszybz — CHANGES_REQUESTED** [review]

File: src/core/manager-serialize.c [hunk 11]
```diff
@@ -204,6 +204,36 @@ static int manager_deserialize_one_unit(Manager *m, const char *name, FILE *f, F
...
+                 * b.service's stale dead state to preserve a.service's running state.
+                 *
+                 * Note: This log message is checked in TEST-07-PID1.alias-corruption.sh, so the test case
+                 * may need adjustment if the message is changed.
+                 */
+                log_warning("Unit file for '%s' was overridden by a symlink to '%s'. Skipping stale state of old unit. Any processes from the overridden unit are now abandoned!",
+                            name,
+                            u->id);
+
+                return unit_deserialize_state_discard(f, fds);
```
Comment (keszybz) [inline src/core/manager-serialize.c]: `manager_deserialize_units` calls `manager_deserialize_one_unit` and then `unit_deserialize_state_skip`. This patch introduces `unit_deserialize_state_discard` which also skips data for a unit, except that it doesn't make any attempt to close fds. I think the attempt to add the fd closing here is going to create bugs in the future, because we'll almost certainly forget to update this side list. So for maintainability, we should just handle this in a generic way.

We need to handle left-over fds somehow anyway, and as @yuwata said, we are supposed to be doing that. For example, we might deserialize data from a *newer* systemd, with fields that this copy does not even know about, so we must gracefully support the case where extraneous fds are provided.

That said, I think it'd make sense to set a flag like `boo_stale_aliased_units_have_skipped_in_deserialization = true`, and use that to emit a better message where we warn about unused fds. (Not sure if we do that anywhere.)

EDIT: I guess this wasn't clear what I mean here. Please kill  `unit_deserialize_state_discard` and let `unit_deserialize_state_skip` do the job.

File: src/core/unit-serialize.c (hunk 1 above)
Comment (keszybz) [reply src/core/unit-serialize.c]: Right, so we close the fds here:
https://github.com/systemd/systemd/blob/13a74f350e0629bedb9e3dbcb53cbcff365af699/src/core/main.c#L3428
So I think we should add a message there. Maybe even at warning level. It's iffy if there are any fds left-over.

**Review by keszybz — CHANGES_REQUESTED** [review]
Overall, I think the behaviour after this patch is better than status quo. Corrupting the state of an unrelated unit by merging with state of an unrelated unit is obviously terrible.

OTOH, leaving behind the processes without supervision seems very wrong too. Maybe we could create a temporary unit that'd take over the cgroup so that we at least keep track? And immediately schedule this unit to be killed? I don't know how to do this, and I don't think this should be considered a blocker for merging. Emitting the warning is good enough and better than status quo.

File: src/core/main.c [hunk 12]
```diff
@@ -2137,6 +2137,8 @@ static int do_reexecute(
          * but let's hope that doesn't matter.) */
 
         arg_serialization = safe_fclose(arg_serialization);
+        if (fds && !fdset_isempty(fds))
```
Comment (yuwata) [inline src/core/main.c]: `fdset_isempty()` can take `NULL`. Please drop the first condition `fds`.

File: src/core/manager-serialize.c [hunk 13]
```diff
@@ -203,6 +203,36 @@ static int manager_deserialize_one_unit(Manager *m, const char *name, FILE *f, F
         if (r < 0)
                 return log_notice_errno(r, "Failed to load unit \"%s\", skipping deserialization: %m", name);
 
+        if (!streq(u->id, name)) {
+                /*
+                 * The unit from the state file (name) resolved to a different canonical unit (u->id). This
+                 * means the unit in the state file is now an alias that wasn't an alias when the state was
+                 * serialised.
```
Comment (yuwata) [inline src/core/manager-serialize.c]: Typo: serialized

File: src/core/main.c [hunk 14]
```diff
@@ -2137,6 +2137,8 @@ static int do_reexecute(
...
+                log_warning("%u unused deserialisation file descriptors passed, closing.", fdset_size(fds));
```
Comment (yuwata) [inline src/core/main.c]: deserialization

File: src/core/manager-serialize.c [hunk 15]
```diff
@@ -203,6 +203,36 @@ static int manager_deserialize_one_unit(Manager *m, const char *name, FILE *f, F
...
+                 *
+                 * It is very important to note that this only affects STALE aliases, that is, units that
+                 * were independent when the state file was written, but are now aliases (either because a
+                 * reload created the symlink, or the symlink existed but this is the first reload). Normal
+                 * aliases that were already aliases during the most recent serialisation are filtered out in
+                 * in manager_serialise_units(), so they never appear in the state file.
```
Comment (yuwata) [inline src/core/manager-serialize.c]: manager_serialize_units()

File: src/core/manager-serialize.c [hunk 16]
```diff
@@ -203,6 +203,36 @@ static int manager_deserialize_one_unit(Manager *m, const char *name, FILE *f, F
...
+                 *
+                 * The serialised data represents the old, independent unit. Deserialising this stale state
```
Comment (yuwata) [inline src/core/manager-serialize.c]: serialized
Deserializing

File: test/units/TEST-07-PID1.alias-corruption.sh [hunk 17]
```diff
@@ -0,0 +1,177 @@
...
+
+    cat >/run/systemd/system/legit.service <<'EOF'
+[Service]
+Type=simple
+ExecStart=/bin/sleep infinity
+EOF
+
+    # Create 20 sus units. They must be Type=simple/running so systemd
+    # CANNOT garbage collect them. If they are dead/stopped, systemd can remove
+    # them from memory before serialisation
```
Comment (yuwata) [inline test/units/TEST-07-PID1.alias-corruption.sh]: Also here: serialization

**Review by yuwata — APPROVED** [review]
LGTM.

Please convert all serialise -> serialize, including commit message.

File: src/core/main.c (hunk 14 above)
Comment (YHNdnzj) [inline src/core/main.c]: note that this is very much expected, e.g. we don't consume the serialized varlink socket fds on daemon-reload. Kinda tempted to drop this...

**Review by YHNdnzj — CHANGES_REQUESTED** [review]
frankly, I'm a bit skeptical about this approach, considering this might break legitimate use cases. Let's say if a distro packages a.service, and the upstream of "a" got renamed to "b" and the canonical unit of that package is now b.service with an alias a.service, and we'd lose all the states across daemon-reload?

I can see how the simplicity of the approach taken here appeals, but OTOH it feels too naive...

File: src/core/main.c (hunk 14 above)
Comment (yuwata) [reply src/core/main.c]: Maybe better to downgrade to LOG_DEBUG ?

Comment (cdown) [reply src/core/main.c]: That's what I meant above by saying not all file descriptors are even intended to be consumed. I don't have a strong preference here, I don't think it's necessarily very useful.

**Comment by cdown** [comment]
@YHNdnzj  I mean, in the case you describe where the distro renames `a.service` to `b.service` with `a.service` becoming an alias, the state loss is inkeeping with our other behaviour.

First, the configuration has change fundamentally because the distro has changed which unit is canonical. From our perspective post-reload, `b.service` is now the canonical unit (with no prior state), and `a.service` is just an alias pointing to `b.service`. The old `a.service` state belongs to a different unit entirely. Applying it to `b.service` would be just wrong.

Second, this already happens in other scenarios. For example, if you `rm /etc/systemd/system/foo.service` while it's running and reload, systemd abandons the process. If you replace a unit file entirely, we don't try to preserve old state. Aliasing is just another form of configuration change.

I feel like there is a more fundamental tension here. The question is, should daemon-reload try to be "smart" about configuration changes and preserve state that contradicts the new config? I strongly believe this is a direction we should avoid going, we will end up with all kinds of insane kludges if we start down this path. daemon-reload is and must remain a simple and stateless operation: read the config from disk, and apply it. The alternative reality where we cross reference runtime state to decide whether to ignore parts of the configuration is the first step to making daemon-reload unpredictable and stateful. That way leads complete madness.

At the end of the day this fixes a state corruption. That's far worse than state loss in an edge case. If we want to keep the old units around like @keszybz suggested, that should be done in future, and is a whole heap of work by itself. But for now, let's just fix the bug.

**Comment by YHNdnzj** [comment]
> First, the configuration has change fundamentally because the distro has changed which unit is canonical. From our perspective post-reload, b.service is now the canonical unit (with no prior state), and a.service is just an alias pointing to b.service. The old a.service state belongs to a different unit entirely. Applying it to b.service would be just wrong.

If the other unit existed and wasn't an alias, sure. But if I swap two names of the same unit or change the canonical name of a unit while keeping a link via alias I don't see why this is suddenly deemed unsupported. In fact, I remember doing this myself for a Unit shipped by Arch. coturn.service is an alias of turnserver.service in packaging, but I did my local full override of the units in /etc/ and at the same time made coturn.service the canonical one.

> Second, this already happens in other scenarios. For example, if you rm /etc/systemd/system/foo.service while it's running and reload, systemd abandons the process.

That's really not the case. The states are preserved with load state set to not-found. It's one of the essential designs to make sure we can still stop removed units somewhat cleanly.

**Comment by cdown** [comment]
I stand corrected! I apparently have held that misconception for a quite long time, thank you.

Then I suggest a slightly different way to approach this. In your rename case, there's one serialised entry, and applying it is correct. In the corruption case there are two serialised entries and the stale one is overwriting the good one. As such they can be distinguished because in the corruption case, the canonical unit has its own serialised entry, but in the rename case it does not. So what we can do is scan the serialised unit names up front and only discard alias state when the canonical unit also has a serialised entry.

Let me know if that sounds good to you.

**Comment by YHNdnzj** [comment]
> I stand corrected! I apparently have held that misconception for a quite long time, thank you.

Np ;) I think it's very common to be confused that manager_load_unit() does not fail on non-existent unit.

The proposed approach sounds nice, and doesn't involve additional moving parts. Happy to review the revised version

**Comment by yuwata** [comment]
@cdown What the state of this? I think it is better to merge this before RC1, as this touches the very core part of systemd.

**Comment by cdown** [comment]
@yuwata Let's skip it this release, there's probably some more back and forth to be had yet. Thanks!

**Comment by ikruglov** [comment]
@cdown, ideally, I'd like to get this merged because next release. It think it's quite close to a merge

File: src/core/main.c (hunk 14 above)
Comment (YHNdnzj) [reply src/core/main.c]: fdset_close debug logs internally already, hence let's not duplicate it.

**Comment by yuwata** [comment]
Feel free to move back to v260 milestone if it is ready before the v260 merge window is closed.

File: src/core/manager-serialize.c [hunk 18]
```diff
@@ -207,6 +250,45 @@ static int manager_deserialize_one_unit(Manager *m, const char *name, FILE *f, F
...
                 return log_notice_errno(r, "Failed to load unit \"%s\", skipping deserialization: %m", name);
 
+        if (!streq(u->id, name) &&
+            serialized_units &&
+            set_contains(serialized_units, u->id)) {
+                /*
+                 * The unit from the state file (name) resolved to a different canonical unit (u->id), and
+                 * the canonical unit also has its own state entry.
+                 *
+                 * This means the unit in the state file is now a stale alias that wasn't an alias when the
```
Comment (keszybz) [inline src/core/manager-serialize.c]: WDYM by "stale alias"? It *wasn't* an alias before, and *is* an alias now. So it's not "stale", IIUC?

**Review by keszybz — COMMENTED** [review]
LGTM, but I'm confused by the "stale alias" phrasing.

File: src/core/manager-serialize.c (hunk 18 above)
Comment (cdown) [reply src/core/manager-serialize.c]: It's a fair question, by this I meant the serialised state entry is stale rather than the alias, in that it was written when it was still an independent unit, but now it resolves an alias to `u->id`. I'll rephrase it overall to:

> This means the state entry for the unit name is stale. That is, when the state was serialized, the name referred to an independent unit, but it now resolves as an alias to the canonical unit.

File: src/core/manager-serialize.c [hunk 19]
```diff
@@ -197,7 +198,49 @@ int manager_serialize(
...
+        for (;;) {
+                _cleanup_free_ char *line = NULL;
+
+                r = read_stripped_line(f, LONG_LINE_MAX, &line);
+                if (r < 0)
+                        return log_error_errno(r, "Failed to read serialization line: %m");
+                if (r == 0)
+                        break;
+
+                r = set_put_strdup(&serialized_units, line);
```
Comment (YHNdnzj) [inline src/core/manager-serialize.c]: Why strdup? Just pass ownership over?

File: src/core/manager-serialize.c [hunk 20]
```diff
@@ -197,7 +198,49 @@ int manager_serialize(
         return 0;
 }
 
-static int manager_deserialize_one_unit(Manager *m, const char *name, FILE *f, FDSet *fds) {
+static int manager_collect_serialized_unit_names(FILE *f, Set **ret_serialized_units) {
```
Comment (YHNdnzj) [inline src/core/manager-serialize.c]: Calling it ret would be fine. The function name already entails the info

File: src/core/manager-serialize.c [hunk 21]
```diff
@@ -207,6 +250,46 @@ static int manager_deserialize_one_unit(Manager *m, const char *name, FILE *f, F
         if (r < 0)
                 return log_notice_errno(r, "Failed to load unit \"%s\", skipping deserialization: %m", name);
 
+        if (!streq(u->id, name) &&
+            serialized_units &&
```
Comment (YHNdnzj) [inline src/core/manager-serialize.c]: set_contains handles NULL set gracefully, hence this is unnecessary

File: src/core/manager-serialize.c [hunk 22]
```diff
@@ -197,7 +198,49 @@ int manager_serialize(
...
+
+        assert(f);
+        assert(ret);
+
+        offset = ftello(f);
+        if (offset < 0)
+                return log_error_errno(errno, "Failed to determine serialization offset: %m");
+
+        for (;;) {
+                char *line = NULL;
```
Comment (YHNdnzj) [inline src/core/manager-serialize.c]: initialization is unnecessary

File: src/core/manager-serialize.c [hunk 23]
```diff
@@ -197,7 +198,49 @@ int manager_serialize(
...
+
+                r = read_stripped_line(f, LONG_LINE_MAX, &line);
+                if (r < 0)
+                        return log_error_errno(r, "Failed to read serialization line: %m");
+                if (r == 0)
+                        break;
+
+                r = set_ensure_consume(&serialized_units, &string_hash_ops_free, line);
+                if (r < 0)
+                        return r;
```
Comment (YHNdnzj) [inline src/core/manager-serialize.c]: log_oom?

File: src/core/manager-serialize.c [hunk 24]
```diff
@@ -197,7 +198,49 @@ int manager_serialize(
...
+        *ret = TAKE_PTR(serialized_units);
+        return 0;
+}
+
+static int manager_deserialize_one_unit(
+                Manager *m,
+                const char *name,
+                FILE *f,
+                FDSet *fds,
+                const Set *serialized_units) {
```
Comment (YHNdnzj) [inline src/core/manager-serialize.c]: Please insert a newline, as per our coding style

File: src/core/manager-serialize.c [hunk 25]
```diff
@@ -216,7 +298,11 @@ static int manager_deserialize_one_unit(Manager *m, const char *name, FILE *f, F
         return 0;
 }
 
-static int manager_deserialize_units(Manager *m, FILE *f, FDSet *fds) {
+static int manager_deserialize_units(
+                Manager *m,
+                FILE *f,
+                FDSet *fds,
+                const Set *serialized_units) {
```
Comment (YHNdnzj) [inline src/core/manager-serialize.c]: ditto

File: src/core/manager-serialize.c [hunk 26]
```diff
@@ -207,6 +250,45 @@ static int manager_deserialize_one_unit(Manager *m, const char *name, FILE *f, F
         if (r < 0)
                 return log_notice_errno(r, "Failed to load unit \"%s\", skipping deserialization: %m", name);
 
+        if (!streq(u->id, name) &&
+            set_contains(serialized_units, u->id)) {
```
Comment (YHNdnzj) [inline src/core/manager-serialize.c:255]: Hmm, this misses the (even more unlikely) case where the new canonical unit id was not present, but _multiple_ individual units got turned into aliases of it? I figure we should insert the canonical unit id to the set unconditionally after deserialization to ensure we skip further attempts to deserialize to the unit object

File: src/core/manager-serialize.c [hunk 27]
```diff
@@ -555,5 +642,9 @@ int manager_deserialize(Manager *m, FILE *f, FDSet *fds) {
                 }
         }
 
-        return manager_deserialize_units(m, f, fds);
+        r = manager_collect_serialized_unit_names(f, &serialized_units);
```
Comment (YHNdnzj) [inline src/core/manager-serialize.c]: Hmm, why not fold this into _deserialize_units?

**Review by YHNdnzj — APPROVED** [review]
Mostly LGTM, thanks!

**Comment by ikruglov** [comment]
Can we please merge this PR. There are two approval.

File: src/core/manager-serialize.c [hunk 28]
```diff
@@ -197,7 +198,50 @@ int manager_serialize(
...
+
+        assert(f);
+        assert(ret);
+
+        offset = ftello(f);
+        if (offset < 0)
+                return log_error_errno(errno, "Failed to determine serialization offset: %m");
+
+        for (;;) {
+                char *line;
```
Comment (ikruglov) [inline src/core/manager-serialize.c]: should be `_cleanup_free_ char *line = NULL;`

**Review by ikruglov — CHANGES_REQUESTED** [review]
ah, there is a memleak. @cdown please have a look

File: src/core/manager-serialize.c (hunk 28 above)
Comment (cdown) [reply src/core/manager-serialize.c]: Good catch! The fix will have to be a little more complicated than just changing it to `_cleanup_free_ char *line = NULL;` , since we also need to TAKE_PTR(line) into set_ensure_consume(). I'll update that now.

File: test/units/TEST-07-PID1.alias-corruption.sh [hunk 29]
```diff
@@ -0,0 +1,178 @@
...
+                echo "ERROR: $unit is still tracking PID $pid (not abandoned)!"
+                return 1
+            fi
+            echo "$unit process (PID $pid) was correctly abandoned (still running, no longer tracked)"
+        done
+
+        # Check consistency between journal warnings and abandoned processes
+        echo "Checking journal for stale state warnings..."
+        journal_warnings=$(journalctl --since "$reload_start" --no-pager | grep "Skipping stale state" || true)
+        warning_count=$(echo "$journal_warnings" | grep -c "Skipping stale state" || true)
```
[the remark this answers is not in the document]
Comment (cdown) [reply test/units/TEST-07-PID1.alias-corruption.sh:168]: Because we don't want false failures and this is probabilistic, this is actually what we want. So I don't think we should change this.

File: src/core/manager-serialize.c [hunk 30]
```diff
@@ -197,7 +198,50 @@ int manager_serialize(
...
+                if (r < 0)
+                        return log_oom();
+
+                r = unit_deserialize_state_skip(f);
+                if (r < 0)
+                        return r;
+        }
+
+        if (fseeko(f, offset, SEEK_SET) < 0)
+                return log_error_errno(errno, "Failed to reset serialization offset: %m");
```
Comment (poettering) [inline src/core/manager-serialize.c:232]: urks, i cannot say i find an approach that parses forwards and returns to the beginning particularly sexy...

**Comment by poettering** [comment]
So I really don't like this (i.e. the parser that goes forward and then backwards) but I really have no better idea either. it's an ugly problem, and ugly problems typically don't have beautiful solutions, hence I guess fine by me.
