### PR TITLE
Fix Positivo-vaio Pro PW key toggle touchpad

### LINKED ISSUE #25668: Fix Positivo-vaio Pro PW key toggle touchpad
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22.04.1

### Linux kernel version used

5.15.0-43-generic

### CPU architectures issue was seen on

x86_64

### Component

_No response_

### Expected behaviour you didn't see

Fn+F1 in my device was to be able to toggle (on-off) touchpad

### Unexpected behaviour you saw

The pressing of the keys wasn't responding

### Steps to reproduce the problem

Press Fn+F1

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by drosdeck**
Resolve #25668

### CODE REVIEW

**Review by bluca — APPROVED** [review]

File: hwdb.d/60-keyboard.hwdb [hunk 1]
```diff
@@ -2011,8 +2011,8 @@ evdev:atkbd:dmi:bvn*:bvr*:bd*:svnViewSonic:pnVPAD10:*
 ###########################################################
 # Positivo-Vaio
 ###########################################################
-# Vaio FE14 (VJFE41F11X, VJE42F11X, VJFE44F11X, VJFE54F11X)
-evdev:name:AT Translated Set 2 keyboard:dmi:bvn*:bvr*:bd*:svnPositivoBahia-VAIO:pnVJFE*:pvr*:*
+# Vaio FE14 (VJFE41F11X, VJE42F11X, VJFE44F11X, VJFE54F11X, VJPW11F11)
+evdev:name:AT Translated Set 2 keyboard:dmi:bvn*:bvr*:bd*:svnPositivoBahia-VAIO:pnVJ[FP][EW]*:pvr*:*
```
Comment (yuwata) [inline hwdb.d/60-keyboard.hwdb]: Now this also accept `FW`  and `PE`. Please add only what you really want.

**Review by yuwata — CHANGES_REQUESTED** [review]
