### PR TITLE
analyze: also find template unit when an instance is specified

### LINKED ISSUE #30357: analyze: systemd-analyze verify does not take unit files in the current working directory
### systemd version the issue has been seen with

255

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

https://github.com/systemd/systemd/pull/30172#issuecomment-1844699620
> This PR triggers a failure in Git's test suite (which has some support for setting up repository maintenance via systemd). It has unit files for several timers (`git-maintenance@hourly.timer`, `git-maintenance@daily.timer`, etc) along with a template service file (`git-maintenance@.service`) and expects to be able to verify per-timer services (e.g. `git-maintenance@hourly.service`) even though no specific unit file exists.
> 
> As a more minimal example, this used to work:
> 
> ```shell
> cat >foo@.service <<-\EOF
> [Service]
> ExecStart=ls
> EOF
> systemd-analyze verify foo@bar.service
> ```
> 
> and would use the `foo@.service` file. But as of [2f6181a](https://github.com/systemd/systemd/commit/2f6181ad4d6c126e3ebf6880ba30b3b0059c6fc8), it yields:
> 
> ```
> Unit foo@bar.service not found.
> ```
> 
> presumably because we break out of `verify_set_unit_path()` after seeing that the literal unit filename does not exist (and then whatever code later resolved the template name does not see that unit path at all).

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a regression caused by 2f6181ad4d6c126e3ebf6880ba30b3b0059c6fc8.

Fixes #30357.

### CODE REVIEW

**Comment by yuwata** [comment]
I will add a test case later.

File: src/analyze/analyze-verify-util.c [hunk 1]
```diff
@@ -72,6 +72,43 @@ int verify_prepare_filename(const char *filename, char **ret) {
...
+                return r;
+
+        r = RET_NERRNO(access(a, F_OK));
+        if (r >= 0) {
+                *ret = TAKE_PTR(a);
+                return 0;
+        }
+
+        if (!unit_name_is_valid(p, UNIT_NAME_INSTANCE))
+                return r; /* return the original error code given by the above access(). */
```
Comment (peff) [inline src/analyze/analyze-verify-util.c]: This passes my stripped-down test for `foo@bar.service`, but still causes a failure in Git's test suite. The difference there is that the command is actually `systemd-analyze verify systemd/user/git-maintenance@hourly.service`. And it looks like `unit_name_is_valid()` doesn't like the slashes in the filename.

Looking at `verify_prepare_filename()` above, you probably need to extract the basename, operate on that, then paste it back onto the directory. Something like peff/systemd@e883729e9fec15ed5c273b8700af475697810a0b, which seems to work for me.

(I wondered at first why we could not simply use `verify_prepare_filename()`, but I think it is going the _other_ way, filling in a template with a parameter).

File: test/units/testsuite-65.sh [hunk 2]
```diff
@@ -296,6 +296,25 @@ EOF
...
+EOF
+
+cat <<EOF >/tmp/hoge@test.service
+[Service]
+ExecStart=ls
+EOF
+
+# issue #30357
+pushd /tmp
+systemd-analyze verify foo@bar.service
```
Comment (peff) [inline test/units/testsuite-65.sh:311]: Based on my comment above, we'd probably want a `subdir/foo@bar.service` test, as well.

File: src/analyze/analyze-verify-util.c [hunk 3]
```diff
@@ -72,26 +72,69 @@ int verify_prepare_filename(const char *filename, char **ret) {
...
+        if (r < 0)
+                return r;
+
+        a = mfree(a);
+        a = path_join(d, t);
+        if (!a)
+                return -ENOMEM;
+
+        if (access(a, F_OK) < 0)
+                return -errno;
```
Comment (peff) [inline src/analyze/analyze-verify-util.c:117]: Above you used `RET_NERRNO`, but we don't here. This could be:
```suggestion
        r = RET_NERRNO(access(a, F_OK));
        if (r < 0)
                return r;
```

for consistency. Alternatively, I think just `return negative_errno()` works, too. I don't know how important it is to use these wrappers or not (the comment in `negative_errno()` talks about helping the compiler realize that `errno` won't ever be `0` here).

**Review by peff — APPROVED** [review]
This looks good to me and fixes the original failure I saw in Git's test suite. I did notice one inconsistency below.

Bear in mind also that this is the first time I've ever looked at systemd code, so you may take my review with a very large grain of salt. :sweat_smile:

File: src/analyze/analyze-verify-util.c (hunk 3 above)
Comment (yuwata) [reply src/analyze/analyze-verify-util.c:117]: RET_NERRNO is not necessary here (and also above). I dropped the first RET_NERRNO.

**Comment by yuwata** [comment]
CentOS CI failures are unrelated.

**Comment by bluca** [comment]
```
521s ../src/analyze/analyze-verify-util.c: In function ‘verify_set_unit_path’:
521s ../src/basic/strv.h:73:16: error: ‘t’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
521s    73 |         return strv_consume_with_size(l, NULL, value);
521s       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
521s ../src/analyze/analyze-verify-util.c:130:23: note: ‘t’ was declared here
521s   130 |                 char *t;
521s       |                       ^

```

**Comment by yuwata** [comment]
> ```
> 521s ../src/analyze/analyze-verify-util.c: In function ‘verify_set_unit_path’:
> 521s ../src/basic/strv.h:73:16: error: ‘t’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
> 521s    73 |         return strv_consume_with_size(l, NULL, value);
> 521s       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 521s ../src/analyze/analyze-verify-util.c:130:23: note: ‘t’ was declared here
> 521s   130 |                 char *t;
> 521s       |                       ^
> ```

That should be false-positive. I added `_cleanup_free_` attribute. Hopefully now it works.

**Review by bluca — APPROVED** [review]
