### PR TITLE
util: introduce strverscmp_improved()

### LINKED ISSUE #18403: str_verscmp() or strverscmp() do not work with RC version
I had sd-boot with from `247~rc2`. When I tried to upgrade sd-boot with `247.2-2`, it cannot, as `strverscmp()` in `bootctl` wrongly detects that newer version is already installed.
Replacing with `str_verscmp()` does not help. See tests added in #18402.

Should we improve `str_verscmp()` to make it handle RC version gracefully?

### PR DESCRIPTION
**Pull request by yuwata**
Unfortunately, strverscmp() from libc or str_verscmp() do not correctly handle pre-release version, e.g. 247 vs 247~rc1.

This implement a new comparison function, which is based on the RPM's `rpmvercmp()`.

Fixes #18403.

### CODE REVIEW

**Comment by yuwata** [comment]
sd-boot still uses `str_verscmp()`. If once this is reviewed and accepted, then I will port `strverscmp_improved()` to sd-boot.

**Comment by yuwata** [comment]
BTW, how should I share such a long function between libbasic and sd-boot, instead of simply copying it?

**Comment by yuwata** [comment]
`strverscmp_improved()` is ported to sd-boot. PTAL.

File: src/basic/strverscmp.c [hunk 1]
```diff
@@ -1,20 +1,75 @@
 /* SPDX-License-Identifier: LGPL-2.1-or-later */
```
Comment (poettering) [inline src/basic/strverscmp.c]: oh, yikes, sharing code between the uefi codebase and the rest. so far we didn't dare and just copied stuff...

I figure doing this sooner or later is unavoidable, but i wonder if maybe we should try to isolate this code in a separate dir, so that we don't have src/basic/ where some stuff is userspace-only, other stuff also works in uefi.

i.e. maybe add a new dir maybe called `src/compatible/` or `śrc/extricable/` or `src/common-firmware/` or `src/firmware-shared/` or so? other ideas? slight preference for `src/firmware/common` from my side

The idea would be that everything in `src/boot/efi/` would be pure efi code, everything in `src/basic/` would be pure userspace code, and the stuff in `src/firmware-common/` would be the common code that works in both environments?

Most likely a bunch of stuff from src/boot/efi/util.h could be moved there too

File: src/basic/strverscmp.c [hunk 2]
```diff
@@ -1,20 +1,75 @@
...
+#if !defined SD_BOOT
 #include <ctype.h>
 
 #include "string-util.h"
-#include "strverscmp.h"
 
-static bool is_alpha(char a) {
+typedef bool sd_bool;
+#define sd_strcmp(a, b)     strcmp((a), (b))
+#define sd_strncmp(a, b, n) strncmp((a), (b), (n))
```
Comment (poettering) [inline src/basic/strverscmp.c]: hmm, can't we instead just define strcmp to StrCmp() on efi? i.e. use the regular C names for these instead of prefixing them?

I'd probably try to do that for most stuff, i.e. consider the uefi naming the anomaly and always map the uefi names back to the regular C stuff, where that is reasonable

File: src/basic/strverscmp.c [hunk 3]
```diff
@@ -1,20 +1,75 @@
...
+
+#include <efi.h>
+#include <efilib.h>
+
+typedef BOOLEAN sd_bool;
+#define sd_strcmp(a, b)     StrCmp((a), (b))
+#define sd_strncmp(a, b, n) StrnCmp((a), (b), (n))
+
+#define XCONCATENATE(x, y) x ## y
+#define CONCATENATE(x, y) XCONCATENATE(x, y)
```
Comment (poettering) [inline src/basic/strverscmp.c]: move to src/boot/efi/util.h (or src/firmware-common/macro.h) or so?

**Review by poettering — COMMENTED** [review]
hmm, the new version compariso logic comes from RPM, but I wonder how that relates to the same logic from .deb? i.e. will this break stuff that previously worked with dpkg? any idea?

**Comment by yuwata** [comment]
@poettering Thank you for the suggestions. Now, shared codes are moved to src/firmware-common. PTAL.

**Comment by yuwata** [comment]
> hmm, the new version compariso logic comes from RPM, but I wonder how that relates to the same logic from .deb? i.e. will this break stuff that previously worked with dpkg? any idea?

Will check. Maybe https://www.debian.org/doc/debian-policy/ch-controlfields.html#version explains well.

**Comment by keszybz** [comment]
>  the new version compariso logic comes from RPM, but I wonder how that relates to the same logic from .deb? 

I don't expect any issues. The rules for rpm were explicitly modelled after those in deb.

File: src/firmware-common/string-util-common.c [hunk 4]
```diff
@@ -74,3 +76,159 @@ sd_char* endswith_no_case(const sd_char *s, const sd_char *postfix) {
...
 }
+
+#ifdef SD_BOOT
+static sd_bool isdigit(sd_char a) {
+        return a >= '0' && a <= '9';
+}
+#endif
+
+static sd_bool is_alpha(sd_char a) {
+        /* Loocale independent version of isalpha(). */
```
Comment (keszybz) [inline src/firmware-common/string-util-common.c]: typo

File: meson.build [hunk 5]
```diff
@@ -1611,6 +1611,7 @@ fuzzers = []
 
 basic_includes = include_directories(
         'src/basic',
+        'src/firmware-common',
```
Comment (keszybz) [inline meson.build]: A bit of a bikeshed comment, but maybe we could call this something different? I think even `src/common` would be nicer. Or `src/generic`.  `firmware-common` is lengthy and `sd-boot` isn't actually firmware. (EFI is "firmware *interface*. I always thought we're on the non-firmware side of that boundary.)

Comment (poettering) [reply meson.build]: maybe all the dir "fundamental"? would that work for you, @keszybz?

File: src/basic/macro.h [hunk 6]
```diff
@@ -9,6 +9,8 @@
 #include <sys/sysmacros.h>
 #include <sys/types.h>
 
+#include "macro-common.h"
```
Comment (poettering) [inline src/basic/macro.h]: if we go for the "fundamental" moniker for the dir, this should probably be called "macro-fundamental.h" or so, i guess

**Comment by poettering** [comment]
so i like the general approach (and i like the "fundamental" moniker, which i hope @keszybz finds ok too)

I wonder about the string stuff though. In our userspace C code we actually have multiple character types, too: "char" for most stuff and char16_t, and char32_t in special cases (mostly in utf8.c but also the EFI userspace apis). I guess we should try to focus on unifying on that naming, given that this is how C11 calls stuff.

hence, make sure that char16_t and CHAR16 can be used interchangably, and then maybe define the apis where we need it in multiple versions, maybe generating them generically for the type via macros.

i.e. i have the suspicion that while we mostly want to use 16bit chars in the efi codebase, and mostly 8bit chars in the regular userspace codebase, there are cases on both sides where we want to use the other size, too (or size*s*) hence, it's better to support them always in parallel, and hence define the 16bit apis also in userspace (even if mostly unused) and the 8bit apis in the efi code (even if mostly unused)

I think ultimately things will be nicer then, since the code doesn't change meaning as much depending where it is compiled into and the types are as safe as they can be. does that make sense?

File: meson.build (hunk 5 above)
Comment (keszybz) [reply meson.build]: I'd prefer "generic" or "common". But "fundamental" works too.

**Comment by keszybz** [comment]
> hence, make sure that char16_t and CHAR16 can be used interchangably, and then maybe define the apis where we need it in multiple versions, maybe generating them generically for the type via macros.

Is that really worth it? I think we should merge this PR with the current scope of removing obvious duplications. If/when the need arises to rework the code, we can slowly convert them to macros if appropriate. I think doing that conversion right now would be quite a lot of work (and potential for errors), without any obvious gain.

**Comment by yuwata** [comment]
@poettering and @keszybz Thank you for comments. The new directory is renamed `firmware-common` -> `fundamental`. Upgrading the green label.

**Comment by yuwata** [comment]
> so i like the general approach (and i like the "fundamental" moniker, which i hope @keszybz finds ok too)
> 
> I wonder about the string stuff though. In our userspace C code we actually have multiple character types, too: "char" for most stuff and char16_t, and char32_t in special cases (mostly in utf8.c but also the EFI userspace apis). I guess we should try to focus on unifying on that naming, given that this is how C11 calls stuff.
> 
> hence, make sure that char16_t and CHAR16 can be used interchangably, and then maybe define the apis where we need it in multiple versions, maybe generating them generically for the type via macros.
> 
> i.e. i have the suspicion that while we mostly want to use 16bit chars in the efi codebase, and mostly 8bit chars in the regular userspace codebase, there are cases on both sides where we want to use the other size, too (or size_s_) hence, it's better to support them always in parallel, and hence define the 16bit apis also in userspace (even if mostly unused) and the 8bit apis in the efi code (even if mostly unused)
> 
> I think ultimately things will be nicer then, since the code doesn't change meaning as much depending where it is compiled into and the types are as safe as they can be. does that make sense?

@poettering Let's do that later when we want such codes.

**Comment by keszybz** [comment]
centosci:  TEST-50-DISSECT
bionic-amd64: general crash
ci/semaphoreci/pr: Debian autopkgtest (LXC): there's so much javascript it can't load the result
