### PR TITLE
homed: fix dbus node enumerator

### LINKED ISSUE #24114: There is a memory leak in homed
### systemd version the issue has been seen with

main

### Component

systemd-homed

### Steps to reproduce the problem

As far as I can tell `dfuzzer` triggered it by calling the "GetManagedObjects" method after a bunch of users were created with `homectl create`.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[253405.607604] systemd-homed[136]: =================================================================
[253405.608555] systemd-homed[136]: ==136==ERROR: LeakSanitizer: detected memory leaks
[253405.609355] systemd-homed[136]: Direct leak of 565440 byte(s) in 8835 object(s) allocated from:
[253405.609993] systemd-homed[136]:     #0 0x7fc5a5aaec98 in __interceptor_realloc (/lib64/libasan.so.6+0xaec98)
[253405.610665] systemd-homed[136]:     #1 0x7fc5a484f7b0 in path_extend_internal ../src/basic/path-util.c:536
[253405.611253] systemd-homed[136]:     #2 0x7fc5a4a0a45e in sd_bus_path_encode ../src/libsystemd/sd-bus/sd-bus.c:3954
[253405.611767] systemd-homed[136]:     #3 0x4114b4 in bus_home_path ../src/home/homed-home-bus.c:719
[253405.612482] systemd-homed[136]:     #4 0x411bc2 in bus_home_node_enumerator ../src/home/homed-home-bus.c:771
[253405.613239] systemd-homed[136]:     #5 0x7fc5a49915e4 in add_enumerated_to_set ../src/libsystemd/sd-bus/bus-objects.c:121
[253405.613768] systemd-homed[136]:     #6 0x7fc5a4991e79 in add_subtree_to_set ../src/libsystemd/sd-bus/bus-objects.c:182
[253405.614402] systemd-homed[136]:     #7 0x7fc5a4992554 in get_child_nodes ../src/libsystemd/sd-bus/bus-objects.c:235
[253405.614743] systemd-homed[136]:     #8 0x7fc5a499b398 in introspect_path ../src/libsystemd/sd-bus/bus-objects.c:940
[253405.615209] systemd-homed[136]:     #9 0x7fc5a499c1fc in process_introspect ../src/libsystemd/sd-bus/bus-objects.c:1019
[253405.615515] systemd-homed[136]:     #10 0x7fc5a499f280 in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1366
[253405.615810] systemd-homed[136]:     #11 0x7fc5a49a0334 in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1440
[253405.616182] systemd-homed[136]:     #12 0x7fc5a49ff424 in process_message ../src/libsystemd/sd-bus/sd-bus.c:2962
[253405.616468] systemd-homed[136]:     #13 0x7fc5a49ff93b in process_running ../src/libsystemd/sd-bus/sd-bus.c:3004
[253405.616735] systemd-homed[136]:     #14 0x7fc5a4a0279c in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3224
[253405.616998] systemd-homed[136]:     #15 0x7fc5a4a02936 in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3251
[253405.617367] systemd-homed[136]:     #16 0x7fc5a4a06037 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3602
[253405.617644] systemd-homed[136]:     #17 0x7fc5a4bc0d28 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3602
[253405.618739] systemd-homed[136]:     #18 0x7fc5a4bc95bf in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4186
[253405.619346] systemd-homed[136]:     #19 0x7fc5a4bca723 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4247
[253405.619942] systemd-homed[136]:     #20 0x7fc5a4bcaaa4 in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4268
[253405.620611] systemd-homed[136]:     #21 0x469411 in run ../src/home/homed.c:44
[253405.621229] systemd-homed[136]:     #22 0x469691 in main ../src/home/homed.c:51
[253405.621758] systemd-homed[136]:     #23 0x7fc5a284043f in __libc_start_call_main (/lib64/libc.so.6+0x4043f)
[253405.622331] systemd-homed[136]: Direct leak of 565440 byte(s) in 8835 object(s) allocated from:
[253405.623032] systemd-homed[136]:     #0 0x7fc5a5aaec98 in __interceptor_realloc (/lib64/libasan.so.6+0xaec98)
[253405.623520] systemd-homed[136]:     #1 0x7fc5a484f7b0 in path_extend_internal ../src/basic/path-util.c:536
[253405.623809] systemd-homed[136]:     #2 0x7fc5a4a0a45e in sd_bus_path_encode ../src/libsystemd/sd-bus/sd-bus.c:3954
[253405.624181] systemd-homed[136]:     #3 0x4114b4 in bus_home_path ../src/home/homed-home-bus.c:719
[253405.624484] systemd-homed[136]:     #4 0x411bc2 in bus_home_node_enumerator ../src/home/homed-home-bus.c:771
[253405.624755] systemd-homed[136]:     #5 0x7fc5a49915e4 in add_enumerated_to_set ../src/libsystemd/sd-bus/bus-objects.c:121
[253405.625020] systemd-homed[136]:     #6 0x7fc5a4991e79 in add_subtree_to_set ../src/libsystemd/sd-bus/bus-objects.c:182
[253405.625372] systemd-homed[136]:     #7 0x7fc5a4992554 in get_child_nodes ../src/libsystemd/sd-bus/bus-objects.c:235
[253405.625642] systemd-homed[136]:     #8 0x7fc5a499b398 in introspect_path ../src/libsystemd/sd-bus/bus-objects.c:940
[253405.626045] systemd-homed[136]:     #9 0x7fc5a499c1fc in process_introspect ../src/libsystemd/sd-bus/bus-objects.c:1019
[253405.626447] systemd-homed[136]:     #10 0x7fc5a499f280 in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1366
[253405.626728] systemd-homed[136]:     #11 0x7fc5a49a00ac in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1430
[253405.627225] systemd-homed[136]:     #12 0x7fc5a49ff424 in process_message ../src/libsystemd/sd-bus/sd-bus.c:2962
[253405.627894] systemd-homed[136]:     #13 0x7fc5a49ff93b in process_running ../src/libsystemd/sd-bus/sd-bus.c:3004
[253405.628499] systemd-homed[136]:     #14 0x7fc5a4a0279c in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3224
[253405.629810] systemd-homed[136]:     #15 0x7fc5a4a02936 in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3251
[253405.630698] systemd-homed[136]:     #16 0x7fc5a4a06037 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3602
[253405.631533] systemd-homed[136]:     #17 0x7fc5a4bc0d28 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3602
[253405.632304] systemd-homed[136]:     #18 0x7fc5a4bc95bf in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4186
[253405.632917] systemd-homed[136]:     #19 0x7fc5a4bca723 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4247
[253405.633587] systemd-homed[136]:     #20 0x7fc5a4bcaaa4 in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4268
[253405.634330] systemd-homed[136]:     #21 0x469411 in run ../src/home/homed.c:44
[253405.635295] systemd-homed[136]:     #22 0x469691 in main ../src/home/homed.c:51
[253405.635661] systemd-homed[136]:     #23 0x7fc5a284043f in __libc_start_call_main (/lib64/libc.so.6+0x4043f)
[253405.635956] systemd-homed[136]: Direct leak of 433600 byte(s) in 6775 object(s) allocated from:
[253405.636377] systemd-homed[136]:     #0 0x7fc5a5aaec98 in __interceptor_realloc (/lib64/libasan.so.6+0xaec98)
[253405.636750] systemd-homed[136]:     #1 0x7fc5a484f7b0 in path_extend_internal ../src/basic/path-util.c:536
[253405.637047] systemd-homed[136]:     #2 0x7fc5a4a0a45e in sd_bus_path_encode ../src/libsystemd/sd-bus/sd-bus.c:3954
[253405.637461] systemd-homed[136]:     #3 0x4114b4 in bus_home_path ../src/home/homed-home-bus.c:719
[253405.637745] systemd-homed[136]:     #4 0x411bc2 in bus_home_node_enumerator ../src/home/homed-home-bus.c:771
[253405.638014] systemd-homed[136]:     #5 0x7fc5a49915e4 in add_enumerated_to_set ../src/libsystemd/sd-bus/bus-objects.c:121
[253405.638381] systemd-homed[136]:     #6 0x7fc5a4991e79 in add_subtree_to_set ../src/libsystemd/sd-bus/bus-objects.c:182
[253405.638826] systemd-homed[136]:     #7 0x7fc5a4992554 in get_child_nodes ../src/libsystemd/sd-bus/bus-objects.c:235
[253405.639465] systemd-homed[136]:     #8 0x7fc5a499dd04 in process_get_managed_objects ../src/libsystemd/sd-bus/bus-objects.c:1239
[253405.639887] systemd-homed[136]:     #9 0x7fc5a499f345 in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1375
[253405.640282] systemd-homed[136]:     #10 0x7fc5a49a00ac in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1430
[253405.640610] systemd-homed[136]:     #11 0x7fc5a49ff424 in process_message ../src/libsystemd/sd-bus/sd-bus.c:2962
[253405.640888] systemd-homed[136]:     #12 0x7fc5a49ff93b in process_running ../src/libsystemd/sd-bus/sd-bus.c:3004
[253405.641271] systemd-homed[136]:     #13 0x7fc5a4a0279c in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3224
[253405.641596] systemd-homed[136]:     #14 0x7fc5a4a02936 in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3251
[253405.641898] systemd-homed[136]:     #15 0x7fc5a4a06037 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3602
[253405.642388] systemd-homed[136]:     #16 0x7fc5a4bc0d28 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3602
[253405.643895] systemd-homed[136]:     #17 0x7fc5a4bc95bf in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4186
[253405.646011] systemd-homed[136]:     #18 0x7fc5a4bca723 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4247
[253405.646787] systemd-homed[136]:     #19 0x7fc5a4bcaaa4 in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4268
[253405.647528] systemd-homed[136]:     #20 0x469411 in run ../src/home/homed.c:44
[253405.648154] systemd-homed[136]:     #21 0x469691 in main ../src/home/homed.c:51
[253405.648503] systemd-homed[136]:     #22 0x7fc5a284043f in __libc_start_call_main (/lib64/libc.so.6+0x4043f)
[253405.648818] systemd-homed[136]: SUMMARY: AddressSanitizer: 1564480 byte(s) leaked in 24445 allocation(s).
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #24114.

### CODE REVIEW

**Review by evverx — APPROVED** [review]
The memory leak is gone. Thanks! Other than that, `GetManagedObjects` and `busctl tree org.freedesktop.home1` can now show all home directories instead of just one.

It would be great if it was possible to add a test to TEST-46-HOMED running `homectl create` twice and making sure that the size of the array returned by `GetManagedObjects` is larger than 1.

File: src/home/homed-home-bus.c [hunk 1]
```diff
@@ -771,6 +771,8 @@ static int bus_home_node_enumerator(
                 r = bus_home_path(h, l + k);
                 if (r < 0)
                         return r;
+
+                k++;
```
Comment (poettering) [inline src/home/homed-home-bus.c:775]: ouch ouch ouch!

**Comment by yuwata** [comment]
@evverx I will add a test case in a later PR. Merging.
