### PR TITLE
mount-util: introduce path_is_network_fs_harder() and use it in networkd

### LINKED ISSUE #32426: networkd: imply KeepConfiguration= for network devices if root fs has _netdev set
### systemd version the issue has been seen with

255.4-2-arch

### Used distribution

ArchLinux

### Linux kernel version used

6.8.7-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

system does not hang during shutdown when the root file system is on an iscsi device.

### Unexpected behaviour you saw

system hang due to network has been stopped before root file system.

### Steps to reproduce the problem

1. root file system is a "local" file system (e.g ext4/btrfs)
2. reboot

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
```
### Additional
This is very similar to #22383 #21967 

But due to #22383 is using `path_is_network_fs`, if the root fs is a "local file system" on a network device, the changes to the value `KeepConfiguration=` will not be applied for this situation.

So I think systemd should use the "_netdev" options in `fstab` to detect whether if network is required by the root filesystem.
A filesystem name whitelist is insufficient and incorrect.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #32426.

### CODE REVIEW

File: src/shared/mount-util.c [hunk 1]
```diff
@@ -1820,3 +1821,70 @@ char* umount_and_unlink_and_free(char *p) {
...
+        struct libmnt_fs *fs;
+        int r;
+
+        assert(path);
+
+        table = mnt_new_table();
+        if (!table)
+                return -ENOMEM;
+
+        r = mnt_table_parse_file(table, "/proc/self/mountinfo");
```
Comment (YHNdnzj) [inline src/shared/mount-util.c]: mnt_table_parse_mtab?
