### PR TITLE
Several fixlets for PTY forwarder and systemd-run

### LINKED ISSUE #38237: TEST-74-AUX-UTILS.run is flaky
```
TEST-74-AUX-UTILS.sh[2651]: ++ run0 --pty echo -n foo
TEST-74-AUX-UTILS.sh[1490]: + assert_eq '' foo
TEST-74-AUX-UTILS.sh[2658]: + set +ex
TEST-74-AUX-UTILS.sh[2658]: FAIL: expected: 'foo' actual: ''
TEST-74-AUX-UTILS.sh[114]: + echo 'Subtest /usr/lib/systemd/tests/testdata/units/TEST-74-AUX-UTILS.run.sh failed'
TEST-74-AUX-UTILS.sh[114]: Subtest /usr/lib/systemd/tests/testdata/units/TEST-74-AUX-UTILS.run.sh failed
```

https://artifacts.dev.testing-farm.io/9098096e-6d69-46ec-ab6a-8208a82a738b/

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes #38237.

### CODE REVIEW

File: src/shared/ptyfwd.c [hunk 1]
```diff
@@ -1083,26 +1110,29 @@ PTYForward* pty_forward_free(PTYForward *f) {
...
-
-        SET_FLAG(f->flags, PTY_FORWARD_IGNORE_VHANGUP, b);
+        if (FLAGS_SET(f->flags, PTY_FORWARD_IGNORE_VHANGUP) != b) {
+                SET_FLAG(f->flags, PTY_FORWARD_IGNORE_VHANGUP, b);
+                changed = true;
+        }
 
-        if (!ignore_vhangup(f)) {
+        /* When false, also unset the initial one. */
+        if (!b && FLAGS_SET(f->flags, PTY_FORWARD_IGNORE_INITIAL_VHANGUP)) {
```
Comment (YHNdnzj) [inline src/shared/ptyfwd.c]: Hmm, not sure I follow? It's perfectly reasonable to only ignore the initial one while resetting the generic one to false?

File: src/shared/ptyfwd.h [hunk 2]
```diff
@@ -12,7 +12,7 @@ typedef enum PTYForwardFlags {
         /* Continue reading after hangup? */
         PTY_FORWARD_IGNORE_VHANGUP         = 1 << 1,
 
-        /* Continue reading after hangup but only if we never read anything else? */
+        /* Continue reading after the initial hangup but only if we never read anything else? */
```
Comment (YHNdnzj) [inline src/shared/ptyfwd.h]: Why does this matter? Can you elaborate? Ideally we'd make hangups idempotent if we haven't read anything anyways, and this changes that without sufficient reasoning?

Comment (yuwata) [reply src/shared/ptyfwd.h]: Hmm, I was confused by the naming, and thought 'initial' means 'the first'.
Except for that, the change has no reason. Will drop.

File: src/shared/ptyfwd.c (hunk 1 above)
Comment (yuwata) [reply src/shared/ptyfwd.c]: To make it usable in systemd-run, which uses PTY_FORWARD_IGNORE_INITIAL_VHANGUP.

Alternatively, I think it is OK to introduce, e.g. pty_forward_set_ignore_initial_vhangup() or pty_forward_set_flags().

**Comment by yuwata** [comment]
@YHNdnzj Thank you for the comments. Updated. PTAL.

File: src/shared/ptyfwd.c (hunk 1 above)
Comment (YHNdnzj) [reply src/shared/ptyfwd.c]: in that case I'd prefer if we just introduce a pty_forward_honor_vhangup or so that unsets both. I doubt we'll ever disable vhangup after establishing pty forwarding.

Comment (yuwata) [reply src/shared/ptyfwd.c]: That sounds better!

File: src/shared/ptyfwd.c [hunk 3]
```diff
@@ -1087,33 +1087,23 @@ PTYForward* pty_forward_free(PTYForward *f) {
...
+        return shovel(f);
 }
 
-bool pty_forward_get_ignore_vhangup(PTYForward *f) {
+bool pty_forward_vhangup_honored(PTYForward *f) {
         assert(f);
 
-        return FLAGS_SET(f->flags, PTY_FORWARD_IGNORE_VHANGUP);
+        return !ignore_vhangup(f);
 }
```
Comment (keszybz) [inline src/shared/ptyfwd.c]: This wrapper is now useless. Please merge `ignore_vhangup` into this function.

Maybe also constify `PTYForward*` while at it.
