### PR TITLE
network: fix KeepConfiguration=yes

### LINKED ISSUE #36411: The default route of a pppoe interface is removed after restarting systemd-networkd
### systemd version the issue has been seen with

systemd 257.2-2

### Used distribution

Arch Linux

### Linux kernel version used

6.12.10-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

networkctl, systemd-networkd

### Expected behaviour you didn't see

The default route of the ppp interface remains unchanged

### Unexpected behaviour you saw

The default route of the ppp interface is removed

### Steps to reproduce the problem

1. wait for pppd and systemd-networkd to finish configuring the ppp0 interface
2. run `systemctl restart systemd-networkd`
3. `ip -r` shows the default route is removed

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
log generated by `journalctl -b -u systemd-networkd --since='2025-02-17 18:13:00' | grep ppp0`

some ipv6 related rows are removed

Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Saved new link: ifindex=20, iftype=PPP(512), kind=ppp
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Saved original MTU 1492 (min: 0, max: 4294967295)
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Saved IPv6 link-local address generation mode: eui64
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Flags change: +UP +LOWER_UP +RUNNING +MULTICAST +POINTOPOINT +NOARP
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Link UP
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Gained carrier
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Remembering foreign QDisc (configured): handle=0:0, parent=ffff:ffff, kind=fq
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Received new foreign address (configured): 1.1.1.1 peer 1.1.1.1/32 (valid forever, preferred forever), flags: permanent, scope: global, label: n/a
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is in pending state.

Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is in pending state.

Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is in pending state.

Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Gained IPv6LL
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is in pending state.

Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Received new foreign route (configured): dst: n/a, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 0, proto: boot, scope: link, type: unicast, flags: n/a
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Received new foreign route (configured): dst: 1.1.1.1/32, src: n/a, gw: n/a, prefsrc: 1.1.1.1, table: main(254), priority: 0, proto: kernel, scope: link, type: unicast, flags: n/a
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Received new foreign route (configured): dst: 1.1.1.1/32, src: n/a, gw: n/a, prefsrc: 1.1.1.1, table: local(255), priority: 0, proto: kernel, scope: host, type: local, flags: n/a





Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Received new foreign route (configured): dst: n/a, src: n/a, nexthop: 286179004, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a






Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Deserialized NDisc route (configured): dst: n/a, src: n/a, nexthop: 286179004, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a

Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: udev initialized link
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Found driver: ppp
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Link state is up-to-date
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: State changed: pending -> initialized
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Found matching .network file: /etc/systemd/network/ppp.network
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Configuring with /etc/systemd/network/ppp.network.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: State changed: initialized -> configuring
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Removing foreign route (configured,marked): dst: n/a, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 0, proto: boot, scope: link, type: unicast, flags: n/a
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is not activated.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is not activated.
Feb 17 18:13:19 belfast systemd-networkd[791992]: Setting '/proc/sys/net/ipv6/conf/ppp0/disable_ipv6' to '0'
Feb 17 18:13:19 belfast systemd-networkd[791992]: Setting '/proc/sys/net/ipv6/conf/ppp0/use_tempaddr' to '0'
Feb 17 18:13:19 belfast systemd-networkd[791992]: Setting '/proc/sys/net/ipv6/conf/ppp0/accept_ra' to '0'
Feb 17 18:13:19 belfast systemd-networkd[791992]: Setting '/proc/sys/net/ipv6/conf/ppp0/proxy_ndp' to '0'
Feb 17 18:13:19 belfast systemd-networkd[791992]: Setting '/proc/sys/net/ipv4/conf/ppp0/promote_secondaries' to '1'
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is not activated.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Requested to activate link
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Requested configuring of the DHCPv6 client.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Requested configuring of the IPv6 Router Discovery.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is not activated.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is not activated.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is not activated.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is not activated.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is not activated.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is not activated.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is not activated.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is not activated.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: link_check_ready(): link is not activated.
Feb 17 18:13:19 belfast systemd-networkd[791992]: ppp0: Bringing link up
Feb 17 18:13:20 belfast systemd-networkd[791992]: ppp0: Forgetting removed foreign route (n/a): dst: n/a, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 0, proto: boot, scope: link, type: unicast, flags: n/a
Feb 17 18:13:20 belfast systemd-networkd[791992]: ppp0: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
Feb 17 18:13:20 belfast systemd-networkd[791992]: ppp0: DHCPv6 client is configured.
Feb 17 18:13:20 belfast systemd-networkd[791992]: ppp0: Discovering IPv6 routers
Feb 17 18:13:20 belfast systemd-networkd[791992]: ppp0: NDISC: Started IPv6 Router Solicitation client
Feb 17 18:13:20 belfast systemd-networkd[791992]: ppp0: IPv6 Router Discovery is configured and started.
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: NDISC: Sent Router Solicitation, next solicitation in 4s

Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: NDISC: Invoking callback for 'router' event.
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: Starting in Solicit mode
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: State changed: stopped -> solicitation
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: Acquiring DHCPv6 lease on NDisc request
Feb 17 18:13:21 belfast systemd-networkd[791992]: Setting '/proc/sys/net/ipv6/conf/ppp0/mtu' to '1492'

Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: Requesting NDisc route (configured): dst: n/a, src: n/a, nexthop: 286179004, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a


Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: Setting SLAAC addresses and router.
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: Configuring NDisc route (requesting,configured): dst: n/a, src: n/a, nexthop: 286179004, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a


Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: Sent Solicit
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: Next retransmission in 1s
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: ndisc_check_ready(): SLAAC addresses and routes are not set.
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: ndisc_check_ready(): SLAAC addresses and routes are not set.

Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: SLAAC addresses and routes set.
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: link_check_ready(): IPv4LL:no DHCPv4:no DHCPv6:no DHCP-PD:no NDisc:yes
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: State changed: configuring -> configured
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: Received an IA option with non-zero status: NoAddrsAvail: No addresses available
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: Failed to parse IA_NA option, ignoring: Invalid argument
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: Processed Advertise message
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: State changed: solicitation -> request
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: Sent Request
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: Next retransmission in 980ms
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: Received an IA option with non-zero status: NoAddrsAvail: No addresses available
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: Failed to parse IA_NA option, ignoring: Invalid argument
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: Processed Reply message
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: T1 expires in 21h 38min 7s
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: T2 expires in 22h 29min 42s
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: Valid lifetime expires in 3d
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 client: State changed: request -> bound

Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: Setting DHCPv6 addresses and routes
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: State changed: configured -> configuring
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: link_check_ready(): IPv4LL:no DHCPv4:no DHCPv6:no DHCP-PD:no NDisc:yes
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: State changed: configuring -> configured
Feb 17 18:13:21 belfast systemd-networkd[791992]: ppp0: DHCPv6 addresses and routes set.

I found a similar issue but it got closed.
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a regression in dd6d53a8dc58c5e6e310b09ba7f7a22600a87ba9 (v257).
Fixes #36411.

### CODE REVIEW

**Comment by yuwata** [comment]
Please backport the first two commits to v257-stable.

**Review by bluca — APPROVED** [review]

File: src/network/networkd-util.c [hunk 1]
```diff
@@ -113,6 +114,42 @@ DEFINE_STRING_TABLE_LOOKUP_FROM_STRING(dhcp_deprecated_address_family, AddressFa
...
+        if (source == NETWORK_CONFIG_SOURCE_STATIC)
+                return true;
+
+        /* Ignore dynamically assigned configs. */
+        if (source != NETWORK_CONFIG_SOURCE_FOREIGN)
+                return false;
+
+        /* When 'only_static' is true, do not mark foreign configs. */
+        if (only_static)
+                return false;
```
Comment (daandemeyer) [inline src/network/networkd-util.c]: Shouldn't this check be done before the second check?

Comment (yuwata) [reply src/network/networkd-util.c]: There is no particular order for the second and third checks. But, maybe swapping the check makes the code easy to understand. So, swapped.

File: src/network/networkd-nexthop.c [hunk 2]
```diff
@@ -924,17 +924,8 @@ int link_drop_nexthops(Link *link, bool only_static) {
...
-                        if (only_static)
-                                continue;
-
-                        /* Do not mark foreign nexthop when KeepConfiguration= is enabled. */
-                        if (link->network &&
-                            FLAGS_SET(link->network->keep_configuration, KEEP_CONFIGURATION_STATIC))
-                                continue;
-
-                } else if (nexthop->source != NETWORK_CONFIG_SOURCE_STATIC)
-                        continue; /* Ignore dynamically configurad nexthops. */
```
Comment (daandemeyer) [inline src/network/networkd-nexthop.c:937]: Previously this didn't look at `nexthop->protocol` at all, now it does. Is protocol always `RTPROT_STATIC` here? Otherwise this is a behavior change, while the commit message says it's not supposed to be a behavior change.

Comment (yuwata) [reply src/network/networkd-nexthop.c:937]: The nexthops statically configured by networkd has RTPROT_STATIC with NETWORK_CONFIG_SOURCE_STATIC.
When configured dynamically, it has RTPROT_RA or so with NETWORK_CONFIG_SOURCE_NDISC.
Currently, the kernel does not configure any nexthops implicitly.
So, the behavior may be changed only when a user manually configures nexthops.

Comment (yuwata) [reply src/network/networkd-nexthop.c:937]: Similar for routing policy rules.

Comment (yuwata) [reply src/network/networkd-nexthop.c:937]: For neighbor entries, currently we do not set/get/manage protocol field, and the behavior is unchanged.

Comment (yuwata) [reply src/network/networkd-nexthop.c:937]: I will extend the commit message.

Comment (yuwata) [reply src/network/networkd-nexthop.c:937]: Mentioned the behavior change. PTAL.

**Review by DaanDeMeyer — APPROVED** [review]
