### PR TITLE
hostnamectl: respect SYSTEMD_COLORS

### LINKED ISSUE #35521: hostnamectl does not respect 16 color palette environment variable
### systemd version the issue has been seen with

systemd 256 (256.9-1-arch) +PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT +LIBARCHIVE

### Used distribution

Arch Linux

### Linux kernel version used

6.12.3-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

hostnamectl

### Expected behaviour you didn't see

`Firmware Age` (Older than 2 years) table entry is colored in 16 color palette `33` - a sane and legible orange I set in my terminal theme colors

### Unexpected behaviour you saw

`Firmware Age` (Older than 2 years) table entry is colored in 216 color palette `5:185` - a bright unhealthy looking unlegible  greenish yellow

### Steps to reproduce the problem

```
SYSTEMD_COLORS=16 hostnamectl
```

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by sgross-emlix**
Instead of the wrapper functions the color defines where used directly. This was especially a problem for ANSI_HIGHLIGHT_YELLOW which is not legible at all for light themes such as solarized. The 16 color palette fallback can be set to a sane yellow or orange on that matter but it was not used though `SYSTEMD_COLORS=16` was set.

Use the proper wrapper functions and let the right color be selected the way other components do it already.

Closes #35521

### CODE REVIEW

**Review by yuwata — APPROVED** [review]

File: src/hostname/hostnamectl.c [hunk 1]
```diff
@@ -313,7 +313,7 @@ static int print_status_info(StatusInfo *i) {
                         r = table_add_many(table,
                                            TABLE_FIELD, "Firmware Age",
                                            TABLE_TIMESPAN_DAY, n - i->firmware_date,
-                                           TABLE_SET_COLOR, n - i->firmware_date > USEC_PER_YEAR*2 ? ANSI_HIGHLIGHT_YELLOW : NULL);
+                                           TABLE_SET_COLOR, n - i->firmware_date > USEC_PER_YEAR*2 ? ansi_highlight_yellow() : NULL);
```
Comment (yuwata) [inline src/hostname/hostnamectl.c:316]: Note, this is not necessary, as whether color is enabled is checked when displaying tables. But OK.

Comment (sgross-emlix) [reply src/hostname/hostnamectl.c:316]: But it is. Please see the corresponding issue.  
When calling `ANSI_HIGHLIGHT_YELLOW` directly the SYSTEMD_COLORS=16 is ignored.

Comment (yuwata) [reply src/hostname/hostnamectl.c:316]: Yeah, I was confused, and you are right.
