### PR TITLE
id128: several cleanups

### LINKED ISSUE #11649: systemd-id128 invocation-id always returns the user manager invocation id
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Debian

**Expected behaviour you didn't see**
 
```
% systemd-run --user --pipe systemd-id128 invocation-id
Running as unit: run-u132649.service
e9fd300dbcbe4fc59541d72d53ecbc04
% systemd-run --user --pipe systemd-id128 invocation-id
Running as unit: run-u132651.service
95130fcaf9664d969b01ce32e6b2f3a0
% journalctl INVOCATION_ID=95130fcaf9664d969b01ce32e6b2f3a0
-- Logs begin at Wed 2018-08-15 22:53:55 -03, end at Mon 2019-02-04 15:05:05 -03. --
Feb 04 15:03:44 felipedell systemd[1]: Started /usr/bin/systemd-id128 invocation-id.
Feb 04 15:03:45 felipedell systemd[1]: run-u132651.service: Succeeded.
```

**Unexpected behaviour you saw**

```
% systemd-run --user --pipe systemd-id128 invocation-id     
Running as unit: run-u371.service
05159fb4a25046f885c00cdd8207cfc7
% systemd-run --user --pipe systemd-id128 invocation-id
Running as unit: run-u372.service
05159fb4a25046f885c00cdd8207cfc7
% journalctl INVOCATION_ID=05159fb4a25046f885c00cdd8207cfc7
-- Logs begin at Wed 2018-08-15 22:53:55 -03, end at Mon 2019-02-04 15:04:58 -03. --
Jan 31 18:07:34 felipedell systemd[1]: Starting User Manager for UID 1000...
Jan 31 18:07:34 felipedell systemd[1]: Started User Manager for UID 1000.
```

### PR DESCRIPTION
**Pull request by yuwata**
~~Closes #11649.~~

### CODE REVIEW

File: src/id128/id128.c [hunk 1]
```diff
@@ -55,7 +64,24 @@ static int verb_invocation_id(int argc, char **argv, void *userdata) {
...
+
+        case INVOCATION_SYSTEM:
+                r = get_invocation_from_keyring(&id);
+                if (r == 0) /* get_invocation_from_keyring() returns 0 when keyring does not contain invocation ID. */
+                        r = -ENXIO;
+                break;
+
+        case INVOCATION_USER:
+                r = get_invocation_from_environment(&id);
+                break;
```
Comment (keszybz) [inline src/id128/id128.c]: Your patch looks like a reasonable change to current code, but I'm not sure if the *current* code is correct. b3415f5daef49642be3d5f417b8880c078420ff7 described the three ways that the invocation id is passed. Later d3070fbdf6077d7da9dbafa198fff8dea712d2ff added `/run/systemd/unit/` in addition to xattrs, for use by journald. So I'd  expect that we'd still rely on the environment variable in containers. But this doesn't seem to work, because we unconditionally error out without ever getting to `secure_getenv()`.

As root in a container, without your patch:
```console
$ strace systemd-id128 invocation-id
...
request_key("user", "invocation_id", NULL, 0) = -1 EPERM (Operation not permitted)
writev(2, [{iov_base="Failed to get invocation-ID: Ope"..., iov_len=52}, {iov_base="\n", iov_len=1}], 2Failed to get invocation-ID: Operation not permitted
) = 53
...
exit_group(1)
$ echo $INVOCATION_ID
b6f814efd4154598a17da7ec626b0035
```

Maybe @poettering can confirm what the expected behaviour is in this case: my expectation is that `sd_id128_get_invocation` would return stuff from the environment variable.

**Comment by poettering** [comment]
hmm, so currently we don't really distuingish the invocation ids much. the service manager picks one for each unit it starts, and that's all, there's no clear concept of scope existing right now.

When invoking processes the service manager tries to set the invocation ID as env var + in the keyring + in /run. Not all of these modes work in both scopes. And hence is not done where it doesn#t work.

I am not convinced it really makes sense to allow user sessions to know the service manager's invocation ID. Hence I think the right approach to solving this issue here, is to carefully make sure the invocation ID the system service manager picks for the user service manager never leaks into the user services. The env vars are sufficiently cleaned up for that already, see sanitize_environment() in src/core/manager.c. They keyring needs some love though. I figure we might need to reconfigure user@.service to not send the key at all, given that it is not deletable from unpriv code and thus leaks into user services.

Or in other words: instead of teach systemd-id128 two different invocation IDs I'd rather remove the system one entirely from user services, and thus simplify things.

**Comment by fsateler** [comment]
> Or in other words: instead of teach systemd-id128 two different invocation IDs I'd rather remove the system one entirely from user services, and thus simplify things.

Agreed. Having different invocation ids is confusing. Anything that sets an invocation id should make sure to clear the invocation id it received itself before launching tasks.

**Comment by keszybz** [comment]
I assume #11991 will resolve the original issue, so commit 4/5 will not be necessary. But the other ones  are still useful. @yuwata can you resubmit with the `--systemd/--user` part removed?

**Comment by yuwata** [comment]
Ok, I will do that tomorrow.

**Comment by yuwata** [comment]
@keszybz Done. PTAL.

**Comment by keszybz** [comment]
Thanks. LGTM. Travis-CI passed, so let's merge.
