### PR TITLE
login: allow to cancel delayed action by CancelScheduledShutdown()

### LINKED ISSUE #34554: CancelScheduledShutdown() reports a shutdown was cancelled that was not cancelled
### systemd version the issue has been seen with

256.6-1-arch

### Used distribution

Arch Linux

### Linux kernel version used

6.10.10-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

logind has a dbus method "CancelScheduledShutdown()" which I expect to cancel a shutdown.

### Unexpected behaviour you saw

When I call this method while holding a shutdown delay inhibitor lock, I get cancelled=true, but shutdown happens anyway.

### Steps to reproduce the problem

```
$ systemd-inhibit --what=shutdown --mode=delay --why=debugging sleep infinity &
$ reboot # doesn't immediately reboot b/c of above
$ busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager CancelScheduledShutdown
b true # appears to have cancelled shutdown

<wall message that shutdown was cancelled>
<reboots when max delay sec is reached>
```
```
$ journalctl -b -1 -u systemd-logind
[...]
Sep 25 17:34:58 rdtw systemd-logind[761]: The system will reboot now!
Sep 25 17:34:58 rdtw systemd-logind[761]: System shutdown has been cancelled
Sep 25 17:35:01 rdtw systemd-logind[761]: System is rebooting.
[...]
```

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #34554.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @rpigott

File: src/login/logind-dbus.c [hunk 1]
```diff
@@ -1980,6 +1980,21 @@ static int delay_shutdown_or_sleep(
         return 0;
 }
 
+static void cancel_delayed_action(Manager *m) {
+        assert(m);
+
+        (void) sd_event_source_set_enabled(m->inhibit_timeout_source, SD_EVENT_OFF);
+
+        if (m->action_job)
+                /* When m->action_job is non-NULL, the delayed action has been already triggeed, and now we
```
Comment (bluca) [inline src/login/logind-dbus.c]: triggeed -> triggered

File: src/login/logind-dbus.c [hunk 2]
```diff
@@ -1980,6 +1980,21 @@ static int delay_shutdown_or_sleep(
...
+                 * are waiting for the job being finished. See match_job_removed(). */
+                ;
```
Comment (bluca) [inline src/login/logind-dbus.c]: this looks a bit strange on the eyes, maybe just have a single if block and this comment before/after?

File: src/login/logind-dbus.c [hunk 3]
```diff
@@ -412,10 +412,23 @@ static int property_get_scheduled_shutdown(
...
-        r = sd_bus_message_append(
-                        reply, "st",
-                        handle_action_to_string(m->scheduled_shutdown_action),
-                        m->scheduled_shutdown_timeout);
+        if (m->delayed_action) {
+                usec_t t = 0;
+
+                if (m->inhibit_timeout_source) {
+                        r = sd_event_source_get_time(m->inhibit_timeout_source, &t);
+                        if (r < 0)
```
Comment (bluca) [inline src/login/logind-dbus.c:420]: Should this maybe fallback to m->scheduled_shutdown_timeout so that the info is not lost to the caller? Otherwise this would be a regression in case it fails

File: src/login/logind-dbus.c [hunk 4]
```diff
@@ -1980,6 +1980,21 @@ static int delay_shutdown_or_sleep(
         return 0;
 }
 
+static void cancel_delayed_action(Manager *m) {
+        assert(m);
+
+        (void) sd_event_source_set_enabled(m->inhibit_timeout_source, SD_EVENT_OFF);
```
Comment (poettering) [inline src/login/logind-dbus.c:1992]: hmm the time source can be NULL, no? if so this would generate a debug log msg

Comment (poettering) [reply src/login/logind-dbus.c:1992]: ah, not true, we allow turning off NULL event sources silently. so ignore this.

**Comment by poettering** [comment]
lgtm

**Comment by yuwata** [comment]
@bluca and @poettering Thank you for the review. All comments are addressed.
