### PR TITLE
systemctl: also ignore ENOENT in checking inhibitors

### LINKED ISSUE #35757: Unable to reboot or poweroff from initrd emergency shell
### systemd version the issue has been seen with

257.1

### Used distribution

Debian testing

### Linux kernel version used

6.12.6-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

System goes into reboot or poweroff when using appropriate command

### Unexpected behaviour you saw

Invocation of reboot/poweroff ends up with error and nothing happens.

FYI: when using pre-257 systemd versions: the error message is shown anyway, nonetheless reboot/poweroff is performed

### Steps to reproduce the problem

1) Build initrd image using dracut and reboot
2) Boot into emergency shell using either `rd.emergency` or `rd.break` kernel command line parameter
3) Run `reboot` or `poweroff`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Generating "/run/initramfs/rdsosreport.txt"


Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.


Press Enter for maintenance
(or press Control-D to continue): 
:/root# reboot
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → CLOSED
Failed to connect to system scope bus via local transport: No such file or directory
:/root# systemctl --version
systemd 257 (257.1-4)
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug caused by 804874d26ac73e0af07c4c5d7165c95372f03f6d.
Follow-up for a1417e5563acb73a0accdc12b3af91e4ec1c7f46.
Fixes #35757.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

File: src/systemctl/systemctl-logind.c [hunk 1]
```diff
@@ -152,9 +152,9 @@ int logind_check_inhibitors(enum action a) {
                 return 0;
 
         r = acquire_bus_full(BUS_FULL, /* graceful = */ true, &bus);
-        if (r == -ECONNREFUSED && geteuid() == 0)
-                return 0; /* When D-Bus is not running, allow root to force a shutdown. E.g. when running at
-                           * the emergency console. */
+        if (ERRNO_IS_NEG_DISCONNECT(r) && geteuid() == 0)
+                return 0; /* When D-Bus is not running (ECONNREFUSED) or D-Bus socket is not created (ENOENT),
+                           * allow root to force a shutdown. E.g. when running at the emergency console. */
```
Comment (poettering) [inline src/systemctl/systemctl-logind.c:157]: hmm, ENOENT is not included in ERRNO_IS_NEG_DISCONNECT()... hence not grokking this?

Comment (yuwata) [reply src/systemctl/systemctl-logind.c:157]: Interestingly, it _does_ include ENOENT.

Comment (bluca) [reply src/systemctl/systemctl-logind.c:157]: eheh it's `ENONET` that is included, not `ENOENT` - and yes I misread it too when I reviewed it

Comment (yuwata) [reply src/systemctl/systemctl-logind.c:157]: Oh......

Comment (yuwata) [reply src/systemctl/systemctl-logind.c:157]: -> #35808.
