### PR TITLE
tar-util: allow to build without acl support

### LINKED ISSUE #39928: Build of tar-until when -Dacl=disabled fails
### systemd version the issue has been seen with

259-rc1 and 259-rc2

### Used distribution

LibreELEC 13

### Linux kernel version used

6.18.0-rc7

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Does not build

### Unexpected behaviour you saw

Na

### Steps to reproduce the problem

Build without libacl1-dev or sys/acl.h on the build host.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[742/1238] Compiling C object src/shared/libsystemd-shared-259.a.p/tar-util.c.o
FAILED: [code=1] src/shared/libsystemd-shared-259.a.p/tar-util.c.o 
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc -Isrc/shared/libsystemd-shared-259.a.p -Isrc/basic -I../src/basic -Isrc/fundamental -I../src/fundamental -Isrc/systemd -I../src/systemd -Isrc/version -I../src/version -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-common -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -Isrc/libsystemd/sd-journal -I../src/libsystemd/sd-journal -I../src/libsystemd/sd-json -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-path -I../src/libsystemd/sd-resolve -I../src/libsystemd/sd-varlink -Isrc/shared -I../src/shared -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/blkid -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/libmount -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu17 -Wno-missing-field-initializers -Wno-unused-parameter -Wno-nonnull-compare -Warray-bounds -Warray-bounds=2 -Wdate-time -Wendif-labels -Werror=bool-compare -Werror=discarded-qualifiers -Werror=flex-array-member-not-at-end -Werror=format=2 -Werror=format-signedness -Werror=implicit-function-declaration -Werror=implicit-int -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=missing-declarations -Werror=missing-parameter-name -Werror=missing-prototypes -Werror=overflow -Werror=override-init -Werror=pointer-sign -Werror=return-type -Werror=sequence-point -Werror=shift-count-overflow -Werror=shift-overflow=2 -Werror=strict-flex-arrays -Werror=undef -Wfloat-equal -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-aliasing=2 -Wstrict-prototypes -Wsuggest-attribute=noreturn -Wunterminated-string-initialization -Wunused-function -Wwrite-strings -Wzero-as-null-pointer-constant -Wzero-length-bounds -fdiagnostics-show-option -fno-common -fstack-protector -fstack-protector-strong -fstrict-flex-arrays=3 --param=ssp-buffer-size=4 -Wno-maybe-uninitialized -Wno-unused-result -Werror=shadow -march=x86-64-v3 -Wall -pipe -O2 -fomit-frame-pointer -DNDEBUG -fno-schedule-insns -fno-schedule-insns2 -Wno-format-truncation -fPIC -fno-strict-aliasing -fstrict-flex-arrays=1 -fvisibility=hidden -fno-omit-frame-pointer -include config.h -pthread -isystem../src/include/override -isystemsrc/include/override -isystem../src/include/uapi -fvisibility=default -MD -MQ src/shared/libsystemd-shared-259.a.p/tar-util.c.o -MF src/shared/libsystemd-shared-259.a.p/tar-util.c.o.d -o src/shared/libsystemd-shared-259.a.p/tar-util.c.o -c ../src/shared/tar-util.c
../src/shared/tar-util.c:62:9: error: unknown type name 'acl_t'
   62 |         acl_t acl_access, acl_default;
      |         ^~~~~
../src/shared/tar-util.c: In function 'open_inode_done':
../src/shared/tar-util.c:92:17: error: implicit declaration of function 'sym_acl_free' [-Wimplicit-function-declaration]
   92 |                 sym_acl_free(of->acl_access);
      |                 ^~~~~~~~~~~~
../src/shared/tar-util.c:92:17: warning: nested extern declaration of 'sym_acl_free' [-Wnested-externs]
../src/shared/tar-util.c: In function 'open_inode_apply_acl':
../src/shared/tar-util.c:116:21: error: implicit declaration of function 'sym_acl_set_fd' [-Wimplicit-function-declaration]
  116 |                 if (sym_acl_set_fd(of->fd, of->acl_access) < 0)
      |                     ^~~~~~~~~~~~~~
../src/shared/tar-util.c:116:21: warning: nested extern declaration of 'sym_acl_set_fd' [-Wnested-externs]
../src/shared/tar-util.c:122:21: error: implicit declaration of function 'sym_acl_set_file' [-Wimplicit-function-declaration]
  122 |                 if (sym_acl_set_file(FORMAT_PROC_FD_PATH(of->fd), ACL_TYPE_DEFAULT, of->acl_default) < 0)
      |                     ^~~~~~~~~~~~~~~~
../src/shared/tar-util.c:122:21: warning: nested extern declaration of 'sym_acl_set_file' [-Wnested-externs]
../src/shared/tar-util.c:122:67: error: 'ACL_TYPE_DEFAULT' undeclared (first use in this function)
  122 |                 if (sym_acl_set_file(FORMAT_PROC_FD_PATH(of->fd), ACL_TYPE_DEFAULT, of->acl_default) < 0)
      |                                                                   ^~~~~~~~~~~~~~~~
../src/shared/tar-util.c:122:67: note: each undeclared identifier is reported only once for each function it appears in
../src/shared/tar-util.c: At top level:
../src/shared/tar-util.c:425:17: error: unknown type name 'acl_type_t'
  425 |                 acl_type_t ntype,
      |                 ^~~~~~~~~~
../src/shared/tar-util.c:426:17: error: unknown type name 'acl_t'
  426 |                 acl_t *acl,
      |                 ^~~~~
../src/shared/tar-util.c:570:17: error: unknown type name 'acl_t'
  570 |                 acl_t *acl_access,
      |                 ^~~~~
../src/shared/tar-util.c:571:17: error: unknown type name 'acl_t'
  571 |                 acl_t *acl_default,
      |                 ^~~~~
../src/shared/tar-util.c: In function 'tar_x':
../src/shared/tar-util.c:725:29: error: implicit declaration of function 'archive_entry_read_stat'; did you mean 'archive_entry_copy_stat'? [-Wimplicit-function-declaration]
  725 |                         r = archive_entry_read_stat(
      |                             ^~~~~~~~~~~~~~~~~~~~~~~
      |                             archive_entry_copy_stat
../src/shared/tar-util.c:725:29: warning: nested extern declaration of 'archive_entry_read_stat' [-Wnested-externs]
../src/shared/tar-util.c:806:46: error: unknown type name 'acl_t'
  806 |                         _cleanup_(acl_freep) acl_t acl_access = NULL, acl_default = NULL;
      |                                              ^~~~~
../src/shared/tar-util.c:806:25: error: cleanup argument not a function
  806 |                         _cleanup_(acl_freep) acl_t acl_access = NULL, acl_default = NULL;
      |                         ^~~~~~~~~
../src/shared/tar-util.c:806:65: error: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  806 |                         _cleanup_(acl_freep) acl_t acl_access = NULL, acl_default = NULL;
      |                                                                 ^~~~
../src/shared/tar-util.c:806:25: error: cleanup argument not a function
  806 |                         _cleanup_(acl_freep) acl_t acl_access = NULL, acl_default = NULL;
      |                         ^~~~~~~~~
../src/shared/tar-util.c:806:85: error: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  806 |                         _cleanup_(acl_freep) acl_t acl_access = NULL, acl_default = NULL;
      |                                                                                     ^~~~
../src/shared/tar-util.c:943:47: error: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  943 |                                 .acl_access = TAKE_PTR(acl_access),
      |                                               ^~~~~~~~
../src/shared/tar-util.c:943:47: note: (near initialization for '(anonymous)')
../src/shared/tar-util.c:944:48: error: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  944 |                                 .acl_default = TAKE_PTR(acl_default),
      |                                                ^~~~~~~~
../src/shared/tar-util.c:944:48: note: (near initialization for '(anonymous)')
../src/shared/tar-util.c: At top level:
../src/shared/tar-util.c:1124:17: error: unknown type name 'acl_type_t'
 1124 |                 acl_type_t ntype,
      |                 ^~~~~~~~~~
../src/shared/tar-util.c:1125:17: error: unknown type name 'acl_t'
 1125 |                 acl_t acl,
      |                 ^~~~~
../src/shared/tar-util.c: In function 'archive_item':
../src/shared/tar-util.c:1302:29: error: implicit declaration of function 'sym_acl_extended_file' [-Wimplicit-function-declaration]
 1302 |                         r = sym_acl_extended_file(FORMAT_PROC_FD_PATH(inode_fd));
      |                             ^~~~~~~~~~~~~~~~~~~~~
../src/shared/tar-util.c:1302:29: warning: nested extern declaration of 'sym_acl_extended_file' [-Wnested-externs]
../src/shared/tar-util.c:1306:54: error: unknown type name 'acl_t'
 1306 |                                 _cleanup_(acl_freep) acl_t acl = NULL;
      |                                                      ^~~~~
../src/shared/tar-util.c:1306:33: error: cleanup argument not a function
 1306 |                                 _cleanup_(acl_freep) acl_t acl = NULL;
      |                                 ^~~~~~~~~
../src/shared/tar-util.c:1306:66: error: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
 1306 |                                 _cleanup_(acl_freep) acl_t acl = NULL;
      |                                                                  ^~~~
../src/shared/tar-util.c:1307:39: error: implicit declaration of function 'sym_acl_get_file' [-Wimplicit-function-declaration]
 1307 |                                 acl = sym_acl_get_file(FORMAT_PROC_FD_PATH(inode_fd), ACL_TYPE_ACCESS);
      |                                       ^~~~~~~~~~~~~~~~
../src/shared/tar-util.c:1307:39: warning: nested extern declaration of 'sym_acl_get_file' [-Wnested-externs]
../src/shared/tar-util.c:1307:87: error: 'ACL_TYPE_ACCESS' undeclared (first use in this function)
 1307 |                                 acl = sym_acl_get_file(FORMAT_PROC_FD_PATH(inode_fd), ACL_TYPE_ACCESS);
      |                                                                                       ^~~~~~~~~~~~~~~
../src/shared/tar-util.c:1311:33: error: implicit declaration of function 'archive_write_acl'; did you mean 'archive_write_fail'? [-Wimplicit-function-declaration]
 1311 |                                 archive_write_acl(entry, ACL_TYPE_ACCESS, acl, d->flags);
      |                                 ^~~~~~~~~~~~~~~~~
      |                                 archive_write_fail
../src/shared/tar-util.c:1311:33: warning: nested extern declaration of 'archive_write_acl' [-Wnested-externs]
../src/shared/tar-util.c:1316:95: error: 'ACL_TYPE_DEFAULT' undeclared (first use in this function)
 1316 |                                         acl = sym_acl_get_file(FORMAT_PROC_FD_PATH(inode_fd), ACL_TYPE_DEFAULT);
      |                                                                                               ^~~~~~~~~~~~~~~~
[757/1238] Compiling C object systemd-journald.p/src_journal_journald-manager.c.o
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by yuwata**
This adds minimal definitions provided by libacl to make tar-util built without libacl support.
Fixes the following compile error:
```
../src/shared/tar-util.c:62:9: error: unknown type name 'acl_t'
   62 |         acl_t acl_access, acl_default;
      |         ^~~~~
```

Follow-up for 4ded7f7a434c59534f65a0f9d391c55961eb110d.
Fixes #39928.
Replaces #39954.

### CODE REVIEW

File: src/shared/tar-util.c [hunk 1]
```diff
@@ -124,6 +125,9 @@ static int open_inode_apply_acl(OpenInode *of) {
         }
```
Comment (keszybz) [inline src/shared/tar-util.c:134]: If ACLs are supported, we return an error if they could not be applied succesfully. If a build is made without acl support, I think we should at least warn if any ACLs would have been applied.

**Comment by poettering** [comment]
I am fine either way. I can follow @keszybz' rationale, but I personally don't care too much.

At the very least we should do some debug logging though if a tarball is unpacked that has ACLs but which we do not generate

**Comment by yuwata** [comment]
@keszybz @poettering Thank you for review and suggestions. I will try to add warning or debugging logs.

**Comment by yuwata** [comment]
Updated. Now logged when an archive entry has ACLs but ACL support is disabled. PTAL.

File: src/shared/tar-util.c [hunk 2]
```diff
@@ -113,14 +115,22 @@ static int open_inode_apply_acl(OpenInode *of) {
                 return 0;
 
         if (of->acl_access) {
+#if HAVE_ACL
                 if (sym_acl_set_fd(of->fd, of->acl_access) < 0)
                         RET_GATHER(r, log_error_errno(errno, "Failed to adjust ACLs of '%s': %m", of->path));
+#else
+                log_debug("The archive entry '%s' has ACLs, but ACL support is disabled.", of->path);
```
Comment (poettering) [inline src/shared/tar-util.c:122]: i'd prefer if this would say that we ignore the ACL data. i.e. just end this in ", not applying ACL."

File: src/shared/tar-util.c [hunk 3]
```diff
@@ -113,14 +115,22 @@ static int open_inode_apply_acl(OpenInode *of) {
...
+#endif
         }
 
         if (of->filetype == S_IFDIR && of->acl_default) {
+#if HAVE_ACL
                 /* There's no API to set default ACLs by fd, hence go by /proc/self/fd/ path */
                 if (sym_acl_set_file(FORMAT_PROC_FD_PATH(of->fd), ACL_TYPE_DEFAULT, of->acl_default) < 0)
                         RET_GATHER(r, log_error_errno(errno, "Failed to adjust default ACLs of '%s': %m", of->path));
+#else
+                log_debug("The archive entry '%s' has default ACLs, but ACL support is disabled.", of->path);
```
Comment (poettering) [inline src/shared/tar-util.c:132]: ditto

File: src/shared/tar-util.c (hunk 2 above)
Comment (keszybz) [reply src/shared/tar-util.c:122]: But this would be confusing no? "Archive entry has ACLs, not applying ALCs"? I think the current form is better.

**Review by keszybz — APPROVED** [review]

File: src/shared/tar-util.c (hunk 2 above)
Comment (yuwata) [reply src/shared/tar-util.c:122]: "Archive entry '%s' has ACLs, but ACL support is disabled, not applying ACL."
should be fine?

Comment (keszybz) [reply src/shared/tar-util.c:122]: I'll merge this with the current wording so that we get the rc done. The wording can always be adjusted later.

Comment (yuwata) [reply src/shared/tar-util.c:122]: Yeah. Thank you!
