### PR TITLE
core: also remove private directories by systemctl clean

### LINKED ISSUE #13355: systemctl clean does not clean private directories but it does clean symlinks to them
**systemd version the issue has been seen with**
> ... 243rc1

**Used distribution**
 > …Fedora Rawhide

**Expected behaviour you didn't see**
 > …no cleaning of /var/lib/private/myapp

**Unexpected behaviour you saw**
 > …cleaning of /var/lib/myapp (symlink)

**Steps to reproduce the problem**
systemd-run -p DymanicUser=yes -p User=joe -p CacheDirectory=joe /usr/bin/bash -c 'echo joe > /var/cache//joe/joe'
systemctl clean
ls /var/cache/joe /var/cache/private/joe

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #13355.

### CODE REVIEW

File: src/core/execute.c [hunk 1]
```diff
@@ -4822,6 +4822,16 @@ int exec_context_get_clean_directories(
...
+
+                        if (exec_directory_is_private(c, t)) {
+                                j = path_join(prefix[t], "private", *i);
+                                if (!j)
+                                        return -ENOMEM;
+
+                                r = strv_consume(&l, j);
+                                if (r < 0)
+                                        return r;
+                        }
```
Comment (poettering) [inline src/core/execute.c:4840]: hmm, an alternative might be two unconditionally delete both the regular and the private dir. Sounds like it would be more robust during updates?

**Comment by poettering** [comment]
lgtm

(whether or not to unconditionally remove the private subdir is something we can think about later)

File: src/core/execute.c (hunk 1 above)
Comment (yuwata) [reply src/core/execute.c:4840]: OK. I agree with you.

**Comment by yuwata** [comment]
@poettering Thank you for the review. Updated.

**Comment by keszybz** [comment]
Hmm, this is rather complex and I don't feel comfortable merging it just before the release. Let's postpone this to the next release. If we merge it right after, it should be easy enough to backport.

**Comment by yuwata** [comment]
@keszybz I think the first four commits should be included in v243, as they fix the issue and change the dbus API. I will split this PR into two.

**Comment by yuwata** [comment]
The commits that extends `systemctl clean` for non-service units are moved to #13439.

**Comment by keszybz** [comment]
LGTM.
