### PR TITLE
network/ndisc: revert bogus treatment of RA router lifetimes

### LINKED ISSUE #33357: networkd: DHCPv6 does not work alongside SLAAC starting with v256
### systemd version the issue has been seen with

256

### Used distribution

Arch

### Linux kernel version used

6.9.4-arch1pf5-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

DHCPv6 lease acquired alongside a SLAAC address

### Unexpected behaviour you saw

DHCPv6 lease not acquired without any error indication

### Steps to reproduce the problem

- use an OpenWrt installation as a router, enable SLAAC + DHCPv6 (enable M+O for IPv6 RAs)
- configure a .network with `DHCP=yes`
- connect, observe `networkctl status <ifname>`

#### networkd configs

<details>
<summary>/etc/systemd/network/80-container-host0.network</summary>

```conf
# File: /etc/systemd/network/80-container-host0.network

[Match]
Virtualization=container
Name=host0

[Network]
DHCP=yes
LLMNR=yes
MulticastDNS=yes
LinkLocalAddressing=yes
LLDP=yes
EmitLLDP=customer-bridge
IPForward=yes
IPv6AcceptRA=yes
#IgnoreCarrierLoss=true
#KeepConfiguration=dhcp

[DHCP]
UseTimezone=yes
UseDomains=yes
```
</details>

#### `networkctl status host0` output

<details>
<summary>Good (v255.7) networkctl status</summary>

```console
$ networkctl status host0
● 2: host0
                   Link File: /usr/lib/systemd/network/99-default.link
                Network File: /etc/systemd/network/80-container-host0.network
                       State: routable (configured)
                Online state: online
                        Type: ether
                        Kind: veth
                      Driver: veth
            Hardware Address: b2:19:09:b0:72:11
                         MTU: 1500 (min: 68, max: 65535)
                       QDisc: noqueue
IPv6 Address Generation Mode: eui64
    Number of Queues (Tx/Rx): 32/32
            Auto negotiation: no
                       Speed: 10Gbps
                      Duplex: full
                        Port: tp
                     Address: 10.196.254.2 (DHCP4 via 10.196.254.1)
                              fd00:be:fcf:1::2
                              fd00:be:fcf:1:b019:9ff:feb0:7211
                              fe80::b019:9ff:feb0:7211
                     Gateway: 10.196.254.1
                         DNS: 10.196.254.1
                              fd00:be:fcf:1::1
              Search Domains: nexus.i.intelfx.name
           Activation Policy: up
         Required For Online: yes
             DHCP4 Client ID: IAID:0xaadbcf43/DUID
           DHCP6 Client IAID: 0xaadbcf43
           DHCP6 Client DUID: DUID-EN/Vendor:0000ab11dfe0ba986f0bcae1
                Connected To: anystation.nexus.i.intelfx.name on port vb-stratofoTlQF

Jun 16 07:08:26 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: Gained carrier
Jun 16 07:08:26 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: Gained IPv6LL
Jun 16 07:08:26 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: Configuring with /etc/systemd/network/80-container-host0.network.
Jun 16 07:08:26 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: DHCPv4 address 10.196.254.2/24, gateway 10.196.254.1 acquired from 10.196.254.1
Jun 16 07:08:27 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: DHCPv6 address fd00:be:fcf:1::2/128 (valid for 59min 59s, preferred for 59min 59s)
Jun 16 07:08:31 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: Configuring with /etc/systemd/network/80-container-host0.network.
Jun 16 07:08:31 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: DHCP lease lost
Jun 16 07:08:31 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: DHCPv6 lease lost
Jun 16 07:08:31 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: DHCPv4 address 10.196.254.2/24, gateway 10.196.254.1 acquired from 10.196.254.1
Jun 16 07:08:31 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: DHCPv6 address fd00:be:fcf:1::2/128 (valid for 59min 59s, preferred for 59min 59s)
```
</details>

<details>
<summary>Bad (v256) networkctl status</summary>

```console
$ networkctl status host0
● 2: host0
                   Link File: /usr/lib/systemd/network/99-default.link
                Network File: /etc/systemd/network/80-container-host0.network
                       State: routable (configured)
                Online state: online
                        Type: ether
                        Kind: veth
                      Driver: veth
            Hardware Address: b2:19:09:b0:72:11
                         MTU: 1500 (min: 68, max: 65535)
                       QDisc: noqueue
IPv6 Address Generation Mode: eui64
    Number of Queues (Tx/Rx): 32/32
            Auto negotiation: no
                       Speed: 10Gbps
                      Duplex: full
                        Port: tp
                     Address: 10.196.254.2 (DHCPv4 via 10.196.254.1)
                              fd00:be:fcf:1:b019:9ff:feb0:7211
                              fe80::b019:9ff:feb0:7211
                     Gateway: 10.196.254.1
                         DNS: 10.196.254.1
                              fd00:be:fcf:1::1
              Search Domains: nexus.i.intelfx.name
           Activation Policy: up
         Required For Online: yes
            DHCPv4 Client ID: IAID:0xaadbcf43/DUID
          DHCPv6 Client DUID: DUID-EN/Vendor:0000ab11dfe0ba986f0bcae1

Jun 16 07:08:31 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: DHCP lease lost
Jun 16 07:08:31 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: DHCPv6 lease lost
Jun 16 07:08:31 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: DHCPv4 address 10.196.254.2/24, gateway 10.196.254.1 acquired from 10.196.254.1
Jun 16 07:08:31 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: DHCPv6 address fd00:be:fcf:1::2/128 (valid for 59min 59s, preferred for 59min 59s)
Jun 16 07:11:50 stratofortress.nexus.i.intelfx.name systemd-networkd[3655314]: host0: DHCPv6 lease lost
Jun 16 07:11:50 stratofortress.nexus.i.intelfx.name systemd-networkd[3734860]: host0: Link UP
Jun 16 07:11:50 stratofortress.nexus.i.intelfx.name systemd-networkd[3734860]: host0: Gained carrier
Jun 16 07:11:50 stratofortress.nexus.i.intelfx.name systemd-networkd[3734860]: host0: Gained IPv6LL
Jun 16 07:11:50 stratofortress.nexus.i.intelfx.name systemd-networkd[3734860]: host0: Configuring with /etc/systemd/network/80-container-host0.network.
Jun 16 07:11:50 stratofortress.nexus.i.intelfx.name systemd-networkd[3734860]: host0: DHCPv4 address 10.196.254.2/24, gateway 10.196.254.1 acquired from 10.196.254.1
```
</details>

#### `SYSTEMD_LOG_LEVEL=debug systemd-networkd` logs

- [networkd-bad.log](https://github.com/user-attachments/files/15856163/networkd-bad.log)
- [networkd-good.log](https://github.com/user-attachments/files/15856164/networkd-good.log)

#### `git bisect` run

```sh
# bad: [5c79cdec10a547a866764a66e1e14898112a00cd] Finalize NEWS and version for v256
# good: [e4817103d0f32a3492608f14da6628d5c9b83197] executor: check for all permission related errnos when setting up IPC namespace
git bisect start 'v256' 'v255.7'
# good: [db11bab38ccf1ed257f310d29070843d4c58ea01] NEWS: finalize for v255
git bisect good db11bab38ccf1ed257f310d29070843d4c58ea01
# bad: [ec596fe34e731fa8c1772b8c1e3a7762be0f4665] Merge pull request #30480 from keszybz/kernel-install-more-paths
git bisect bad ec596fe34e731fa8c1772b8c1e3a7762be0f4665
# good: [73a994cff0306642b84bac81f847fc8d0cace124] Merge pull request #30990 from poettering/more-mime
git bisect good 73a994cff0306642b84bac81f847fc8d0cace124
# good: [76995e7dc4196adaafe010711229281bd1e13a5d] Merge pull request #31286 from poettering/bootctl-varlink
git bisect good 76995e7dc4196adaafe010711229281bd1e13a5d
# bad: [e5191faf44bfcb709b1452890ef3fec9a7428055] Merge pull request #31000 from flatcar-hub/krnowak/mutable-overlays
git bisect bad e5191faf44bfcb709b1452890ef3fec9a7428055
# good: [b2ac9280889ce5915e9b8437ee2aff134142ace9] cryptsetup: drop "headless" bool, make it a flag in AskPasswordFlags instead
git bisect good b2ac9280889ce5915e9b8437ee2aff134142ace9
# bad: [1212c80c71a9c608ed182d2808273f7c93442121] test: Initial systemd-sysext tests
git bisect bad 1212c80c71a9c608ed182d2808273f7c93442121
# bad: [46be11208215f7cf2d2868e3f59603e51cb062cf] Merge pull request #31403 from yuwata/pam-sd-bus-session
git bisect bad 46be11208215f7cf2d2868e3f59603e51cb062cf
# bad: [de53c661bcb88bea5ab1f005060bb07bdfd6deac] logind-dbus: clean up manager_{start,stop,kill}_unit
git bisect bad de53c661bcb88bea5ab1f005060bb07bdfd6deac
# good: [e404ca3eb77fe6b10d49b5c36afb41d8e2710ca8] Merge pull request #31419 from AdrianVovk/fixup-largefile-define
git bisect good e404ca3eb77fe6b10d49b5c36afb41d8e2710ca8
# bad: [ffef01acddcac27caaef02f7f28bff03d7799e5e] network/ndisc: ignore most fields of RA header when lifetime is zero
git bisect bad ffef01acddcac27caaef02f7f28bff03d7799e5e
# good: [787e71e432abf6134257875ba3bee55b1c747a29] sd-ndisc: introduce sd_ndisc_is_running()
git bisect good 787e71e432abf6134257875ba3bee55b1c747a29
# good: [479d3e1994a2e4ff7070dc2a0cb1615af7120b0c] network/ndisc: drop configurations when received RA with zero lifetime
git bisect good 479d3e1994a2e4ff7070dc2a0cb1615af7120b0c
# first bad commit: [ffef01acddcac27caaef02f7f28bff03d7799e5e] network/ndisc: ignore most fields of RA header when lifetime is zero
```

```
ffef01acddcac27caaef02f7f28bff03d7799e5e is the first bad commit
commit ffef01acddcac27caaef02f7f28bff03d7799e5e
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Mon Feb 19 10:37:23 2024 +0900

    network/ndisc: ignore most fields of RA header when lifetime is zero

 src/network/networkd-ndisc.c | 24 ++++++++++++++++++++++--
 1 file changed, 22 insertions(+), 2 deletions(-)
```

### PR DESCRIPTION
**Pull request by intelfx**
This reverts commit ffef01acddcac27caaef02f7f28bff03d7799e5e.

Similar to 2d393b1b6d8 ("network: IPv6 Compliance: Router Advertisement Processing, Reachable Time [v6LC.2.2.15]"),

Extract from: https://www.ietf.org/rfc/rfc4861.html#section-4.2, p.21, first paragraph:

    The Router Lifetime applies only to
    the router's usefulness as a default router; it
    does not apply to information contained in other
    message fields or options.

So it does not make sense to prevent DHCPv6 when Router Lifetime is 0.

Fixes #33357.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
@intelfx @yuwata should hopefully be back next week. I'd like to wait for him as he's most familiar with the ipv6 stuff in networkd.

File: src/network/networkd-ndisc.c [hunk 1]
```diff
@@ -2081,11 +2081,6 @@ static int ndisc_start_dhcp6_client(Link *link, sd_ndisc_router *rt) {
         assert(link);
         assert(link->network);
 
-        /* Do not start DHCPv6 client if the router lifetime is zero, as the message sent as a signal of
-         * that the router is e.g. shutting down, revoked, etc,. */
-        r = sd_ndisc_router_get_lifetime(rt, NULL);
-        if (r <= 0)
-                return r;
```
Comment (yuwata) [inline src/network/networkd-ndisc.c]: Please drop the doubled empty line here.

**Review by yuwata — APPROVED** [review]
LGTM. Sorry for late response. One minor comment.

**Review by bluca — APPROVED** [review]
