### PR TITLE
network: fix address flag handling

### LINKED ISSUE #13218: systemd-networkd stops adding temporary IPs after a few days with IPv6PrivacyExtensions=yes
**systemd version the issue has been seen with**
> systemd 242 (242.32-3-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > About every 24 hours when a temporary IPv6 address gets to status deprecated, a new temporary IP address should be added to the interface

**Unexpected behaviour you saw**
 > For the first few days, a new address was added as expected, but after 6 days the old IPv6 address got deprecated without a adding a new one. Instead of using a temporary address for the outgoing traffic, the MAC-address based IPv6 is used which I want to avoid for privacy reasons or the IPv6PrivacyExtensions setting would not make sense.

**Steps to reproduce the problem**
Configure network interface with the following settings and wait for a few days. The value for Name may have to be adjusted according to the name of the network interface
```
[Match]
Name=en*

[Network]
DHCP=yes
IPv6AcceptRA=yes
IPv6PrivacyExtensions=yes
```

**Debug logging**
For debugging purposes, I had to use a VM, but I experienced the same behaviour on a physical machine before. I configured **Environment=SYSTEMD_LOG_LEVEL=debug** in a drop-in file and found the following entries with journalctl - partly anonymized:

```
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Configuring route: dst: 2003:c5:xxxx:xxxx::/64, src: n/a, gw: n/a, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Configuring route: dst: 2003:c5:xxxx:xxxx::/56, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Sent INFORMATION-REQUEST
Jul 01 19:54:25 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Next retransmission in 991ms
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Updating route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Updating route: dst: 2003:c5:xxxx:xxxx::/64, src: n/a, gw: n/a, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:5054:ff:fe00:4063/64 (valid for 2h)
Jul 01 19:54:25 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx::/56, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:54:25 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Recv REPLY
Jul 01 19:54:27 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:5054:ff:fe00:4063/64 (valid for 1h 59min 59s)
Jul 01 19:54:27 server-arch systemd-networkd[289]: ens3: Configured
Jul 01 19:54:27 server-arch systemd-networkd[289]: ens3: State changed: configuring -> configured
Jul 01 19:54:27 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:5054:ff:fe00:4063/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 01 19:54:27 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/64 (valid for 1h 59min 59s)
Jul 01 19:54:27 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/128, src: n/a, gw: n/a, prefsrc: n/a
```
every few minutes I have entries like the following one:
```
Jul 01 19:56:44 server-arch systemd-networkd[289]: NDISC: Received Router Advertisement: flags OTHER preference medium lifetime 1800 sec
Jul 01 19:56:44 server-arch systemd-networkd[289]: NDISC: Invoking callback for 'router' event.
Jul 01 19:56:44 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Started in Information request mode
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Acquiring DHCPv6 lease on NDisc request
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Configuring route: dst: 2003:c5:xxxx:xxxx::/64, src: n/a, gw: n/a, prefsrc: n/a
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Configuring route: dst: 2003:c5:xxxx:xxxx::/56, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 01 19:56:44 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Sent INFORMATION-REQUEST
Jul 01 19:56:44 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Next retransmission in 996ms
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:5054:ff:fe00:4063/64 (valid for 2h)
Jul 01 19:56:44 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/64 (valid for 2h)
Jul 01 19:56:45 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Recv REPLY
```
...
after first 24 hours
```
Jul 02 19:50:31 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:60fc:ab46:9c7d:da37/64 (valid for 1h 51min 14s)
Jul 02 19:50:31 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:60fc:ab46:9c7d:da37/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 02 19:50:32 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/64 (valid for 1h 51min 13s)
```
...
```
Jul 03 19:46:35 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:35e7:270e:2684:e591/64 (valid for 1h 56min 23s)
Jul 03 19:46:35 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:35e7:270e:2684:e591/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 03 19:46:36 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:60fc:ab46:9c7d:da37/64 (valid for 1h 56min 22s)
```
...
```
Jul 04 19:42:40 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:40df:4dac:e9cb:7d9e/64 (valid for 1h 59min 6s)
Jul 04 19:42:40 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:40df:4dac:e9cb:7d9e/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 04 19:42:41 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:35e7:270e:2684:e591/64 (valid for 1h 59min 5s)
```
...
```
Jul 05 19:38:45 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:fd2b:a818:e29d:2a0e/64 (valid for 1h 56min 15s)
Jul 05 19:38:45 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:fd2b:a818:e29d:2a0e/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 05 19:38:46 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:40df:4dac:e9cb:7d9e/64 (valid for 1h 56min 14s)
```
...
```
Jul 06 19:34:48 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/64 (valid for 1h 59min 55s)
Jul 06 19:34:48 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 06 19:34:49 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:fd2b:a818:e29d:2a0e/64 (valid for 1h 59min 54s)
```
...
after 6 days only
```
Jul 07 19:30:57 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/64 (valid for 1h 55min 50s)
```
24 hours later no more related entries.
systemd-networkd only shows that it's deprecating the temporary address which was added 24 hours ago but no _Adding address_ / _Adding route_ entries. This does not always seem to happen after exactly 6 days, can also be a few days more or less.

Output of **ip a** at that time:
```
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:00:40:63 brd ff:ff:ff:ff:ff:ff
    inet 192.168.x.y/24 brd 192.168.x.255 scope global dynamic ens3
       valid_lft 773602sec preferred_lft 773602sec
    inet6 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/64 scope global temporary deprecated dynamic 
       valid_lft 6946sec preferred_lft 0sec
    inet6 2003:c5:xxxx:xxxx:fd2b:a818:e29d:2a0e/64 scope global temporary deprecated dynamic 
       valid_lft 6946sec preferred_lft 0sec
    inet6 2003:c5:xxxx:xxxx:40df:4dac:e9cb:7d9e/64 scope global temporary deprecated dynamic 
       valid_lft 6946sec preferred_lft 0sec
    inet6 2003:c5:xxxx:xxxx:35e7:270e:2684:e591/64 scope global temporary deprecated dynamic 
       valid_lft 6946sec preferred_lft 0sec
    inet6 2003:c5:xxxx:xxxx:60fc:ab46:9c7d:da37/64 scope global temporary deprecated dynamic 
       valid_lft 6946sec preferred_lft 0sec
    inet6 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/64 scope global temporary deprecated dynamic 
       valid_lft 6946sec preferred_lft 0sec
    inet6 2003:c5:xxxx:xxxx:5054:ff:fe00:4063/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 6946sec preferred_lft 1546sec
    inet6 fe80::5054:ff:fe00:4063/64 scope link 
       valid_lft forever preferred_lft forever
```

All temporary IPv6 addresses are now deprecated. After their lifetime has expired, the old addresses get removed
```
Jul 08 19:54:35 server-arch systemd-networkd[289]: ens3: Removing address: 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/64 (valid for 0)
Jul 08 19:54:35 server-arch systemd-networkd[289]: ens3: Removing route: dst: 2003:c5:xxxx:xxxx:e977:6e2a:85d0:b911/128, src: n/a, gw: n/a, prefsrc: n/a

Jul 09 19:50:31 server-arch systemd-networkd[289]: ens3: Removing address: 2003:c5:xxxx:xxxx:60fc:ab46:9c7d:da37/64 (valid for 0)
Jul 09 19:50:31 server-arch systemd-networkd[289]: ens3: Removing route: dst: 2003:c5:xxxx:xxxx:60fc:ab46:9c7d:da37/128, src: n/a, gw: n/a, prefsrc: n/a

Jul 10 19:46:35 server-arch systemd-networkd[289]: ens3: Removing address: 2003:c5:xxxx:xxxx:35e7:270e:2684:e591/64 (valid for 0)
Jul 10 19:46:35 server-arch systemd-networkd[289]: ens3: Removing route: dst: 2003:c5:xxxx:xxxx:35e7:270e:2684:e591/128, src: n/a, gw: n/a, prefsrc: n/a

Jul 11 19:42:40 server-arch systemd-networkd[289]: ens3: Removing address: 2003:c5:xxxx:xxxx:40df:4dac:e9cb:7d9e/64 (valid for 0)
Jul 11 19:42:40 server-arch systemd-networkd[289]: ens3: Removing route: dst: 2003:c5:xxxx:xxxx:40df:4dac:e9cb:7d9e/128, src: n/a, gw: n/a, prefsrc: n/a

Jul 12 19:38:44 server-arch systemd-networkd[289]: ens3: Removing address: 2003:c5:xxxx:xxxx:fd2b:a818:e29d:2a0e/64 (valid for 0)
Jul 12 19:38:44 server-arch systemd-networkd[289]: ens3: Removing route: dst: 2003:c5:xxxx:xxxx:fd2b:a818:e29d:2a0e/128, src: n/a, gw: n/a, prefsrc: n/a
```
When the last IPv6 address is to be removed, I find the following log entries
```
Jul 13 19:34:47 server-arch systemd-networkd[289]: ens3: Removing address: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/64 (valid for 0)
Jul 13 19:34:47 server-arch systemd-networkd[289]: ens3: Removing route: dst: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/128, src: n/a, gw: n/a, prefsrc: n/a
Jul 13 19:35:08 server-arch systemd-networkd[289]: NDISC: Received Router Advertisement: flags OTHER preference medium lifetime 1800 sec
Jul 13 19:35:08 server-arch systemd-networkd[289]: NDISC: Invoking callback for 'router' event.
Jul 13 19:35:08 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Started in Information request mode
Jul 13 19:35:08 server-arch systemd-networkd[289]: ens3: Acquiring DHCPv6 lease on NDisc request
Jul 13 19:35:08 server-arch systemd-networkd[289]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 13 19:35:08 server-arch systemd-networkd[289]: ens3: Configuring route: dst: 2003:c5:xxxx:xxxx::/64, src: n/a, gw: n/a, prefsrc: n/a
Jul 13 19:35:08 server-arch systemd-networkd[289]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 13 19:35:08 server-arch systemd-networkd[289]: ens3: Configuring route: dst: 2003:c5:xxxx:xxxx::/56, src: n/a, gw: fe80::a96:d7ff:fexx:xxxx, prefsrc: n/a
Jul 13 19:35:08 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Sent INFORMATION-REQUEST
Jul 13 19:35:08 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Next retransmission in 960ms
Jul 13 19:35:08 server-arch systemd-networkd[289]: ens3: Updating address: 2003:c5:xxxx:xxxx:5054:ff:fe00:4063/64 (valid for 2h)
Jul 13 19:35:08 server-arch systemd-networkd[289]: DHCPv6 CLIENT: Recv REPLY
Jul 13 19:35:10 server-arch systemd-networkd[289]: ens3: Adding address: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/64 (valid for 1h 59min 58s)
Jul 13 19:35:10 server-arch systemd-networkd[289]: ens3: Adding route: dst: 2003:c5:xxxx:xxxx:ec8e:e858:7774:f0f6/128, src: n/a, gw: n/a, prefsrc: n/a
```
and the last deprecated address gets active again and the procedure starts again with adding new addresses for a few days...

When my router or the ISP disconnects my WAN connection and receives a new prefix, this also resulted in a new temporary IPv6 address until the renewal stalls again.

### LINKED ISSUE #19838: After an undefined amount of time, IPv6PrivacyExtensions=yes is no longer honored
**systemd version the issue has been seen with**
 > systemd 248 (248.3-2-arch)
> +PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
 > archlinux

**Linux kernel version used** (`uname -a`)

 > `Linux toxoplasmosis 5.12.4-2-ck-skylake #1 SMP PREEMPT Sun, 16 May 2021 02:40:56 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > `IPv6PrivacyExtensions=yes` is permanently honored. The SLAAC IPv6 is *never* the IP that the system uses to reach the internet; `curl -6 icanhazip.com` *never* returns the `scope global dynamic mngtmpaddr noprefixroute` IP.

**Unexpected behaviour you saw**
 > `curl -6 icanhazip.com` returns my SLAAC IPv6 address, which does not honor `IPv6PrivacyExtensions=yes`

**Steps to reproduce the problem**
* `IPv6PrivacyExtensions=yes` in the adequate systemd.network(5) file.
* Wait a long time (21 days in my case; previous times was about 24 hours)
* `curl -6 icanhazip.com`

**Additional program output to the terminal or log subsystem illustrating the issue**

```
% networkctl 
IDX LINK      TYPE      OPERATIONAL SETUP
[...]
  2 wlp3s0    wlan      routable    configured
[...]
```
```
% ip addr show wlp3s0 
2: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 11:22:33:44:55:66 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.11/24 brd 192.168.1.255 scope global dynamic wlp3s0
       valid_lft 79566sec preferred_lft 79566sec
    inet6 home:prefix:b287:b87d:c905:6312/64 scope global temporary deprecated dynamic 
       valid_lft 1770sec preferred_lft 0sec
    inet6 home:prefix:ab82:f20c:d84f:b6d/64 scope global temporary deprecated dynamic 
       valid_lft 1770sec preferred_lft 0sec
    inet6 home:prefix:1122:33ff:fe44:5566/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 1770sec preferred_lft 570sec
    inet6 fe80::1122:33ff:fe44:5566/64 scope link 
       valid_lft forever preferred_lft forever
```
```
% sysctl net.ipv6.conf.wlp3s0
net.ipv6.conf.wlp3s0.accept_dad = 1
net.ipv6.conf.wlp3s0.accept_ra = 0
net.ipv6.conf.wlp3s0.accept_ra_defrtr = 1
net.ipv6.conf.wlp3s0.accept_ra_from_local = 0
net.ipv6.conf.wlp3s0.accept_ra_min_hop_limit = 1
net.ipv6.conf.wlp3s0.accept_ra_mtu = 1
net.ipv6.conf.wlp3s0.accept_ra_pinfo = 1
net.ipv6.conf.wlp3s0.accept_ra_rt_info_max_plen = 0
net.ipv6.conf.wlp3s0.accept_ra_rt_info_min_plen = 0
net.ipv6.conf.wlp3s0.accept_ra_rtr_pref = 1
net.ipv6.conf.wlp3s0.accept_redirects = 1
net.ipv6.conf.wlp3s0.accept_source_route = 0
net.ipv6.conf.wlp3s0.addr_gen_mode = 0
net.ipv6.conf.wlp3s0.autoconf = 1
net.ipv6.conf.wlp3s0.dad_transmits = 1
net.ipv6.conf.wlp3s0.disable_ipv6 = 0
net.ipv6.conf.wlp3s0.disable_policy = 0
net.ipv6.conf.wlp3s0.drop_unicast_in_l2_multicast = 0
net.ipv6.conf.wlp3s0.drop_unsolicited_na = 0
net.ipv6.conf.wlp3s0.enhanced_dad = 1
net.ipv6.conf.wlp3s0.force_mld_version = 0
net.ipv6.conf.wlp3s0.force_tllao = 0
net.ipv6.conf.wlp3s0.forwarding = 0
net.ipv6.conf.wlp3s0.hop_limit = 64
net.ipv6.conf.wlp3s0.ignore_routes_with_linkdown = 0
net.ipv6.conf.wlp3s0.keep_addr_on_down = 0
net.ipv6.conf.wlp3s0.max_addresses = 16
net.ipv6.conf.wlp3s0.max_desync_factor = 600
net.ipv6.conf.wlp3s0.mc_forwarding = 0
net.ipv6.conf.wlp3s0.mldv1_unsolicited_report_interval = 10000
net.ipv6.conf.wlp3s0.mldv2_unsolicited_report_interval = 1000
net.ipv6.conf.wlp3s0.mtu = 1500
net.ipv6.conf.wlp3s0.ndisc_notify = 0
net.ipv6.conf.wlp3s0.ndisc_tclass = 0
net.ipv6.conf.wlp3s0.optimistic_dad = 0
net.ipv6.conf.wlp3s0.proxy_ndp = 0
net.ipv6.conf.wlp3s0.ra_defrtr_metric = 1024
net.ipv6.conf.wlp3s0.regen_max_retry = 3
net.ipv6.conf.wlp3s0.router_probe_interval = 60
net.ipv6.conf.wlp3s0.router_solicitation_delay = 1
net.ipv6.conf.wlp3s0.router_solicitation_interval = 4
net.ipv6.conf.wlp3s0.router_solicitation_max_interval = 3600
net.ipv6.conf.wlp3s0.router_solicitations = -1
net.ipv6.conf.wlp3s0.rpl_seg_enabled = 0
net.ipv6.conf.wlp3s0.seg6_enabled = 0
net.ipv6.conf.wlp3s0.seg6_require_hmac = 0
sysctl: permission denied on key 'net.ipv6.conf.wlp3s0.stable_secret'
net.ipv6.conf.wlp3s0.suppress_frag_ndisc = 1
net.ipv6.conf.wlp3s0.temp_prefered_lft = 86400
net.ipv6.conf.wlp3s0.temp_valid_lft = 604800
net.ipv6.conf.wlp3s0.use_oif_addrs_only = 0
net.ipv6.conf.wlp3s0.use_optimistic = 0
net.ipv6.conf.wlp3s0.use_tempaddr = 2 # <----- Most important
```
```INI
/etc/systemd/network/20-wireless.network
[Match]
MACAddress=11:22:33:44:55:66

[Network]
DHCP=yes
IPv6PrivacyExtensions=yes
```

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for a8481354f0cd2c0855472193d0f57c7a77674969.
Fixes #13218.
Fixes #19838.

### CODE REVIEW

File: src/network/networkd-address.c [hunk 1]
```diff
@@ -19,6 +19,45 @@
...
+
+        for (size_t i = 0; i < ELEMENTSOF(map); i++) {
+                if (!FLAGS_SET(flags, map[i].flag))
+                        continue;
+                if (map[i].flag == IFA_F_SECONDARY && family == AF_INET6) {
+                        if (!strextend_with_separator(&str, ",", "temporary"))
+                                return -ENOMEM;
+                } else {
+                        if (!strextend_with_separator(&str, ",", map[i].name))
+                                return -ENOMEM;
```
Comment (poettering) [inline src/network/networkd-address.c]: doesn't matter, but I'd probably have shortened this to:

```c
if (!strextend_with_separator(
                &str, ",", 
                map[i].flag == IFA_F_SECONDARY && family == AF_INET6 ? "temporary" : map[i].name))
        return -ENOMEM;
```

**Comment by yuwata** [comment]
@poettering Thank you for the review. The above suggestion is applied. Upgrading the green label.
