### PR TITLE
timedate: refuse setting time when unit is in 'activating' or friends

### LINKED ISSUE #11420: Failure to set time during a short while after NTP is disabled
**systemd version the issue has been seen with**
systemd 239 (Also applies to 240 and master as well)

**Used distribution**
[OpenBMC 2.6.0-rc1][https://github.com/openbmc/openbmc/tree/2.6.0-rc1]

**Expected behaviour you didn't see**
* When NTP is disabled, user shall be able to set time manually;
* When NTP is enabled, user shall be unable to set time manually;

**Unexpected behaviour you saw**
* During a short while (e.g. 5~8 seconds) after NTP is disabled, user fails to set time;
* During a short while after NTP is enabled, user is still able to set time.

**Steps to reproduce the problem**
Run below commands:
```bash
timedatectl set-ntp 1
sleep 10  # Wait for a while for NTP service to start
timedatectl set-ntp 0
timedatectl set-time "2019-01-12" # This is expected to work, but it fails
echo $?
timedatectl set-ntp 1
timedatectl set-time "2019-01-12" # This is expected to fail, but it works.
echo $?

```

We got below output, which indicates that it fails to set time after ntp is disabled, and it successfully set the time after ntp is enabled.

```
Failed to set time: Automatic time synchronization is enabled
1
0
```

### PR DESCRIPTION
**Pull request by yuwata**
This makes `timedated` refuse requests by `timedatectl set-time` during unit is in activating or inactivating state.

Fixes #11420.

### CODE REVIEW

**Comment by mine260309** [comment]
This fix "improves" the behavior by making the time window shorter, but the issue remains.

If you run below test, the set time after NTP disable still fails.
```
timedatectl set-ntp 1
sleep 10
timedatectl set-ntp 0
timedatectl set-time "2019-01-12"
echo $?
timedatectl set-ntp 1
timedatectl set-time "2019-01-12"
echo $?
```

**Comment by mine260309** [comment]
Well, when mentions that it "improves" the behavior by making the time window shorter, I mean for both cases.
In above test, if you run it for multiple times, we may get `1,1`, or `1,0`, or `0, 1`, I did not get `0,0` for now.
* Most times we got `1, 1`, which is your expected;
* Sometimes we got `1, 0`, which means the bug is not fixed;
* Sometimes we got `0, 1`, which is my expectation.

Anyway, the behavior is not stable, so I do not think this pull request actually fixes the bug.

---

And about your comment:
> just after disabling NTP, I think we should reject until the NTP clients are certainly stopped for safety

May I ask why? Is it because the concern that the manually set time may get invalidated during NTP service exiting?

**Comment by mine260309** [comment]
Not really in `timedatectl`.
If we are going to add something like "--wait", it shall be done by the interface `method_set_ntp`, so that not only `timedatectl` could ask for `--wait`, but any service that makes DBus call to `SetNTP` could ask for `wait`.
However, that will break the existing interface, so I do not think it is good solution.

I am not requesting a new feature, but wonder if we could fix the issue #11420

**Comment by yuwata** [comment]
> Sometimes we got 1, 0, which means the bug is not fixed

Hmm... I will try to rework.

**Comment by mine260309** [comment]
A second thought: `SetNTP`'s implementation **shall** wait for NTP service to start/stop by default.
Otherwise, what happens if:
1. SetNTP returns OK, NTP property is already changed;
2. The NTP services fail to start/stop.

If the above happens, the system is left with a state where NTP property and the NTP services status are not consistent.

What do you think?

**Comment by yuwata** [comment]
Updated. I hope the situation
> Sometimes we got 1, 0, which means the bug is not fixed;

is fixed. @mine260309 Could you test this?

**Comment by mine260309** [comment]
@yuwata From the code, I believe that your concern is fixed, e.g. you expect failure to set time right after NTP is enabled.

But from my perspective, it is not good enough, because it makes the user get an error while he expects OK, in the case that user disabled NTP and set a time.

What do you think about my previous concern:

> Otherwise, what happens if:
> 1. SetNTP returns OK, NTP property is already changed;
> 2. The NTP services fail to start/stop.
>
> If the above happens, the system is left with a state where NTP property and the NTP services status are not consistent.

**Comment by mine260309** [comment]
> Do you mean that the case e.g. ExecStartPre=bash -c 'sleep 5s; false' or something is added to systemd-timesyncd.service?

Yeah, you can use that to **simulate** the failure of starting/stopping NTP service.

**Comment by yuwata** [comment]
I've not tested the 'simulator', but I guess the inconsistency is, at most, tentative. `timedated` always checks service states when `NTP` property is requested.
Or, have you already find any persistent inconsistency?

**Comment by rahulmah** [comment]
@mine260309 @yuwata yuwata: I think it's perfectly fine with the fix - “Reject Set time until the NTP is fully disabled”.  Just add a proper message in the REST error response so that customer will come to know that set time request has failed here because NTP disable in progress.

File: src/timedate/timedated.c [hunk 1]
```diff
@@ -735,6 +743,9 @@ static int method_set_time(sd_bus_message *m, void *userdata, sd_bus_error *erro
         assert(m);
         assert(c);
 
+        if (c->slot_job_removed)
+                return sd_bus_error_set(error, BUS_ERROR_AUTOMATIC_TIME_SYNC_ENABLED, "Previous request is not finished, refusing.");
```
Comment (yuwata) [inline src/timedate/timedated.c:747]: > “Reject Set time until the NTP is fully disabled”.

@rahulmah Thank you for the suggestion. But, the previous request may be `set-ntp true`, that is, enabling...
The condition hits only when `set-ntp` and `set-time` (or equivalent bus APIs) are called sequentially. Of course, there exists a possibility that the callers are different, but it is really rare, I guess. So, the meaning of 'Previous request' is clear. WDYT?
