### PR TITLE
path-util: introduce path_simplify()

### LINKED ISSUE #9107: WorkingDirectory ending in "/." leads to "Operation not permitted" error on load
**systemd version the issue has been seen with**
> 237

**Used distribution**
 > ubuntu 18.04
> Linux web 4.15.0-12-generic #13-Ubuntu SMP Thu Mar 8 06:24:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Expected behaviour you didn't see**
 > unit file should load

**Unexpected behaviour you saw**
 > unit file fails to load 

**Steps to reproduce the problem**

- create simple unit file  `/etc/systemd/system/bugdemo.service`

 > [Unit]
 > Description=demonstrate possible bug
 >
 > [Service]
 > ExecStart=/bin/cat
 > WorkingDirectory=/etc

- reload, check status
   
 > $ systemctl daemon-reload
 > $ systemctl status bugdemo.service
 >   ● bugdemo.service - demonstrate possible bug
 >    Loaded: loaded (/etc/systemd/system/bugdemo.service; static; vendor preset: enabled)

- add `/.` to WorkingDirectory

 > [Unit]
 > Description=demonstrate possible bug
 >
 > [Service]
 > ExecStart=/bin/cat
 > WorkingDirectory=/etc/.

- reload, check status

 > $ systemctl daemon-reload
 > $ systemctl status bugdemo.service
 >   ● bugdemo.service - demonstrate possible bug
 >    Loaded: error (Reason: Operation not permitted)

Even if that's intended behaviour, the error message is not very helpful.

Background: I'm creating the unit-file with ansible and there's an optional extra part to the working directory. That part default's to `.`, so I can combine the base path with the optional extra bit, even if the extra part is not used. I can work around this with a conditional, but it seems odd to me that systemd refuses to load the unit-file with the extra `/.`.

### PR DESCRIPTION
**Pull request by yuwata**
This slightly relaxes the restriction for specifying paths in unit files. Previously, we do not allow path which starts with `./`, ends with `/.`, or has `/./`. But these are redundant but safe. So, this introduces the function `path_kill_slashes_and_dot()` which cleanups such redundant path specifications.

Fixes #9107.

@poettering You tagged #9107 'needs-better-log-message'. But I think `/./` or trailing `/.` are safe. What do you think about this?

### CODE REVIEW

**Comment by yuwata** [comment]
@keszybz I noticed right now that you self-assigned the issue. I do not want to disturb your work, but if you are interested in this, please give me a comment. Thank you.

**Comment by keszybz** [comment]
I wanted to work on it, but I started doing something else in the mean time. I'll reassign it to you.

**Comment by yuwata** [comment]
Updated. PTAL.

File: src/test/test-path-util.c [hunk 1]
```diff
@@ -69,15 +78,28 @@ static void test_path(void) {
...
-                char p3[] = "/./";
-
-                assert_se(path_equal(path_kill_slashes(p1), "aaa/bbb/ccc"));
-                assert_se(path_equal(path_kill_slashes(p2), "/aaa/./ccc"));
-                assert_se(path_equal(path_kill_slashes(p3), "/./"));
-        }
+        test_path_kill_slashes_one("aaa/bbb////ccc", "aaa/bbb/ccc", "aaa/bbb/ccc");
+        test_path_kill_slashes_one("//aaa/.////ccc", "/aaa/./ccc", "/aaa/ccc");
+        test_path_kill_slashes_one("///", "/", "/");
+        test_path_kill_slashes_one("///.//", "/.", "/");
```
Comment (keszybz) [inline src/test/test-path-util.c]: Hmm, this removes a trailing slash, and a trailing slash is significant in some contexts. I'm not sure if this matters here.

File: src/basic/path-util.c [hunk 2]
```diff
@@ -992,3 +993,52 @@ bool empty_or_root(const char *root) {
...
+        assert((flag & (PATH_CHECK_ABSOLUTE | PATH_CHECK_RELATIVE)) != (PATH_CHECK_ABSOLUTE | PATH_CHECK_RELATIVE));
+
+        fatal = flag & PATH_CHECK_FATAL;
+
+        if (flag & (PATH_CHECK_ABSOLUTE | PATH_CHECK_RELATIVE)) {
+                absolute = path_is_absolute(path);
+
+                if (!absolute && (flag & PATH_CHECK_ABSOLUTE)) {
+                        log_syntax(unit, LOG_ERR, filename, line, 0,
+                                   "%s= path is not an absolute%s: %s",
```
Comment (keszybz) [inline src/basic/path-util.c]: "is not absolute"

File: src/basic/path-util.c [hunk 3]
```diff
@@ -992,3 +993,52 @@ bool empty_or_root(const char *root) {
...
+                                   fatal ? "" : ", ignoring", lvalue, path);
+                        return -EINVAL;
+                }
+
+                if (absolute && (flag & PATH_CHECK_RELATIVE)) {
+                        log_syntax(unit, LOG_ERR, filename, line, 0,
+                                   "%s= path is an absolute%s: %s",
```
Comment (keszybz) [inline src/basic/path-util.c]: "is absolute"

File: src/basic/path-util.c [hunk 4]
```diff
@@ -992,3 +993,52 @@ bool empty_or_root(const char *root) {
...
+        path_kill_slashes_and_dot(path, true);
+
+        if (!path_is_normalized(path)) {
+                log_syntax(unit, LOG_ERR, filename, line, 0,
+                           "%s= path is not normalized%s: %s",
+                           fatal ? "" : ", ignoring", lvalue, path);
+                return -EINVAL;
+        }
+
+        if (!utf8_is_valid(path)) {
```
Comment (keszybz) [inline src/basic/path-util.c]: So this check must be first, because otherwise we can print non-utf8 in the messages above.

File: src/core/load-fragment.c [hunk 5]
```diff
@@ -2599,17 +2572,16 @@ int config_parse_unit_requires_mounts_for(
...
                 r = unit_full_printf(u, word, &resolved);
                 if (r < 0) {
                         log_syntax(unit, LOG_ERR, filename, line, r, "Failed to resolve unit specifiers in '%s', ignoring: %m", word);
                         continue;
                 }
 
+                r = path_simplify_and_warn(resolved, PATH_CHECK_ABSOLUTE, unit, filename, line, lvalue);
+                if (r < 0)
+                        continue;
+
```
Comment (keszybz) [inline src/core/load-fragment.c:2583]: The check for utf8-validity needs to be before `unit_full_printf` and its error message. I don't think you can remove the utf8 check.

**Comment by poettering** [comment]
Hmm, I haven't liked the name "path_kill_slashes()" since a longer time, I was always attempted to rename it to path_normalize(), to match path_is_normalized(), but then again the latter doesn't permit embedded "..", which we can't really remove in this function as doing that requires hitting the disk... 

That said, maybe a more suitable name would be "path_transform()" or "path_tidy()" or so? @keszybz ideas?

File: src/test/test-path-util.c [hunk 6]
```diff
@@ -26,6 +26,15 @@
...
         }
 
+#define test_path_kill_slashes_one(in, out, out_dot) {                  \
+                char *p;                                                \
+                                                                        \
+                p = strdupa(in);                                        \
+                assert_se(streq(path_kill_slashes_and_dot(p, false), out)); \
+                p = strdupa(in);                                        \
+                assert_se(streq(path_kill_slashes_and_dot(p, true), out_dot)); \
+        }
```
Comment (poettering) [inline src/test/test-path-util.c]: why make this a macro? why not a regular function? (some test cases use macros like this for no real reason i can see, but we should not add more...)

**Comment by poettering** [comment]
So, i guess accepting/normalizing inner dots for WorkingDirectory= is OK, given that the field usually references foreign, externally defined paths, hence conceptually the PR looks mostly good. I am wondering howerver if we really should do that for RuntimeDirectory() too.. I mean, the runtime directory is not really a path, it's a part of the of the path, and we build the actual path from it. Hence I think we should be stricter there, and not allow non-normalized stuff... That said I am not feeling too strongly about this, I'd be fine with this PR either way...

**Comment by poettering** [comment]
(But I'd still like to see path_kill_slashes_and_dot()/path_kill_slashes() to be renamed to path_simplify() a part of this PR)

**Comment by poettering** [comment]
Hmm, the original bug report complained that "systemctl status" for an offending service looks like this:

```
systemctl status bugdemo.service
● bugdemo.service - demonstrate possible bug
Loaded: error (Reason: Operation not permitted)
```

This PR doesn't really change that, if the path contains "..", right? My original plan was to simply make sure that the error we report there is a bit more useful, though not entirely sure how much work that would actually be... property_get_load_error() generates that error string server side, so we could fix this without the client needing changes, but I am not sure how best to fill it with indication that WorkingDirectory= is at fault here... 

Maybe a workable way out is to just generically say that configuration settings are at fault, which should be actionable enough and the logs should then show details.

Lemme cook up a patch for that part. I think it would be orthogonal to your work however, and both should go in

File: src/core/load-fragment.c (hunk 5 above)
Comment (yuwata) [reply src/core/load-fragment.c:2583]: I see... Are there any possibility that `unit_{full,name}_printf()` generate utf8 invalid strings? I mean, that should we check utf8-validity before _and_ after `unit_{full,name}_printf()`?

**Comment by yuwata** [comment]
Updated. But not addressed all comments. Still wip.

File: src/core/load-fragment.c (hunk 5 above)
Comment (yuwata) [reply src/core/load-fragment.c:2583]: I added utf8-validity check in `parse_line()`. So, conf parsers do not need to call `utf8_is_valid()` now.

File: src/basic/path-util.c (hunk 4 above)
Comment (yuwata) [reply src/basic/path-util.c]: OK. it is moved to the beginning of the function.

File: src/test/test-path-util.c (hunk 1 above)
Comment (yuwata) [reply src/test/test-path-util.c]: trailing slash? I think I do not change anything about slashes.

File: src/test/test-path-util.c (hunk 6 above)
Comment (yuwata) [reply src/test/test-path-util.c]: Now I use function instead of macro.

**Comment by yuwata** [comment]
Updated. PTAL.

@poettering 
> I am wondering howerver if we really should do that for RuntimeDirectory() too.. I mean, the runtime directory is not really a path, it's a part of the of the path, and we build the actual path from it.

Yes, so I added the flag `PATH_CHECK_RELATIVE`.

> Hence I think we should be stricter there, and not allow non-normalized stuff...

Hmm, sorry, I cannot understand why...

File: src/core/load-fragment.c (hunk 5 above)
Comment (keszybz) [reply src/core/load-fragment.c:2583]: That's a great solution.
