### PR TITLE
dissect-image: open dissected and decrypted partitions

### LINKED ISSUE #24617: pid1: simultaneously starting multiple services with same image may trigger conflict
### systemd version the issue has been seen with

HEAD

### Used distribution

Ubuntu focal

### Linux kernel version used

5.4.0-125-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

TEST-29-PORTABLE succeeds.

### Unexpected behaviour you saw

TEST-29-PORTABLE fails:
https://autopkgtest.ubuntu.com/results/autopkgtest-focal-upstream-systemd-ci-systemd-ci/focal/amd64/s/systemd-upstream/20220908_232004_2ec87@/log.gz
See [TEST-29-PORTABLE.journal.tar.gz](https://github.com/systemd/systemd/files/9535214/TEST-29-PORTABLE.journal.tar.gz).

### Steps to reproduce the problem

Run the test.

### Additional program output to the terminal or log subsystem illustrating the issue

```
Sep 09 07:33:18 systemd[452]: Opened '/usr/share/minimal_1.raw' in O_RDONLY access mode, with O_DIRECT enabled.
Sep 09 07:33:18 systemd[452]: Successfully acquired /dev/loop0, devno=7:0, nr=0, diskseq=0
Sep 09 07:33:18 systemd[452]: Allocating context for crypt device /usr/share/minimal_1.verity.
Sep 09 07:33:18 systemd[452]: Trying to open and read device /usr/share/minimal_1.verity with direct-io.
Sep 09 07:33:18 systemd[452]: Crypto backend (OpenSSL 1.1.1f  31 Mar 2020) initialized in cryptsetup library version 2.2.2.
Sep 09 07:33:18 systemd[452]: Detected kernel Linux 5.4.0-125-generic x86_64.
Sep 09 07:33:18 systemd[452]: Reading VERITY header of size 512 on device /usr/share/minimal_1.verity, offset 0.
Sep 09 07:33:18 systemd[454]: Opened '/usr/share/minimal_1.raw' in O_RDONLY access mode, with O_DIRECT enabled.
Sep 09 07:33:18 systemd[452]: Setting ciphertext data device to /dev/loop0.
Sep 09 07:33:18 systemd[452]: Trying to open and read device /dev/loop0 with direct-io.
Sep 09 07:33:18 systemd[452]: Activating volume dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity by volume key.
Sep 09 07:33:18 systemd[452]: Trying to activate VERITY device dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity using hash sha256.
Sep 09 07:33:18 systemd[452]: Allocating a free loop device.
Sep 09 07:33:18 systemd[454]: Successfully acquired /dev/loop1, devno=7:1, nr=1, diskseq=0
Sep 09 07:33:18 systemd[452]: Trying to open and read device /dev/loop5 with direct-io.
Sep 09 07:33:18 systemd[454]: Allocating context for crypt device /usr/share/minimal_1.verity.
Sep 09 07:33:18 systemd[454]: Trying to open and read device /usr/share/minimal_1.verity with direct-io.
Sep 09 07:33:18 systemd[454]: Trying to load VERITY crypt type from device /usr/share/minimal_1.verity.
Sep 09 07:33:18 systemd[454]: Reading VERITY header of size 512 on device /usr/share/minimal_1.verity, offset 0.
Sep 09 07:33:18 systemd[454]: Setting ciphertext data device to /dev/loop1.
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop1 with direct-io.
Sep 09 07:33:18 systemd[454]: Activating volume dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity by volume key.
Sep 09 07:33:18 systemd[454]: Device dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity already exists. <-- in LOG_ERR
Sep 09 07:33:18 systemd[454]: Allocating crypt device context by device dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity.
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop0 with direct-io. <-- What??
Sep 09 07:33:18 systemd[454]: Allocating context for crypt device /dev/loop0. <-- Hm??
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop0 with direct-io. <-- Huh??
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop0 with direct-io. <-- again??
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop5 with direct-io.
Sep 09 07:33:18 systemd[454]: Error opening verity device, crypt_volume_key_get failed: Invalid argument
Sep 09 07:33:18 systemd[454]: Releasing crypt device /dev/loop5 context.
Sep 09 07:33:18 systemd[454]: Allocating context for crypt device /usr/share/minimal_1.verity.
Sep 09 07:33:18 systemd[454]: Trying to open and read device /usr/share/minimal_1.verity with direct-io.
Sep 09 07:33:18 systemd[454]: Trying to load VERITY crypt type from device /usr/share/minimal_1.verity.
Sep 09 07:33:18 systemd[454]: Reading VERITY header of size 512 on device /usr/share/minimal_1.verity, offset 0.
Sep 09 07:33:18 systemd[454]: Setting ciphertext data device to /dev/loop1.
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop1 with direct-io.
Sep 09 07:33:18 systemd[454]: Activating volume loop1-verity by volume key.
Sep 09 07:33:18 systemd[454]: Trying to activate VERITY device loop1-verity using hash sha256.
Sep 09 07:33:18 systemd[454]: Allocating a free loop device.
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop6 with direct-io.
Sep 09 07:33:18 systemd[454]: Calculated device size is 5928 sectors (RO), offset 0.
(udev processing many events)
Sep 09 07:33:21 kernel: /dev/mapper/dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity: Can't open blockdev <-- LOG_ERR
(snip)
Sep 09 07:33:21 systemd[452]: Udev cookie 0xd4dedbd (semid 10) destroyed
Sep 09 07:33:21 systemd[452]: Verity volume dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity status is V.
Sep 09 07:33:21 systemd[454]: Udev cookie 0xd4d0212 (semid 11) destroyed
Sep 09 07:33:21 systemd[454]: Verity volume loop1-verity status is V.
Sep 09 07:33:21 systemd[454]: Deactivating volume dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity. <-- ??
Sep 09 07:33:21 systemd[454]: Allocating crypt device context by device dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity.
Sep 09 07:33:21 systemd[452]: Probed fstype 'squashfs' on partition /dev/mapper/dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity.
Sep 09 07:33:21 systemd[454]: Trying to open and read device /dev/loop0 with direct-io. <-- Oh, again??
Sep 09 07:33:21 systemd[454]: Allocating context for crypt device /dev/loop0.
Sep 09 07:33:21 systemd[454]: Trying to open and read device /dev/loop0 with direct-io.
Sep 09 07:33:21 systemd[454]: Trying to open and read device /dev/loop0 with direct-io.
Sep 09 07:33:21 systemd[454]: Trying to open and read device /dev/loop5 with direct-io.
Sep 09 07:33:21 systemd[454]: Trying to open and read device /dev/loop0 with direct-io.
Sep 09 07:33:21 systemd[454]: Verity volume dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity status is V.
Sep 09 07:33:21 systemd[454]: dm remove dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity  [ opencount flush retryremove deferredremove ]   [16384] (*1) <-- Wait, wait, it is still used by PID=452...
Sep 09 07:33:21 systemd[452]: Mounting /dev/mapper/dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity (squashfs) on /run/systemd/unit-root (MS_RDONLY|MS_NODEV "")...
Sep 09 07:33:21 systemd-udevd[281]: dm-0: Device is queued (SEQNUM=3921, ACTION=remove)
Sep 09 07:33:21 systemd[452]: Failed to mount /dev/mapper/dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity (type squashfs) on /run/systemd/unit-root (MS_RDONLY|MS_NODEV ""): No such file or directory
Sep 09 07:33:21 systemd[452]: Failed to mount root image: No such file or directory
Sep 09 07:33:21 systemd[452]: Deactivating volume dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity.
Sep 09 07:33:21 systemd[452]: Device dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity is not active.
Sep 09 07:33:21 systemd[452]: Failed to deactivate encrypted partition dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity <-- yeah, it is already removed by PID=454...
Sep 09 07:33:21 systemd[452]: Releasing crypt device /usr/share/minimal_1.verity context.
Sep 09 07:33:21 systemd[452]: Releasing device-mapper backend.
Sep 09 07:33:21 systemd[452]: Closing read only fd for /usr/share/minimal_1.verity.
Sep 09 07:33:21 systemd[452]: Closed loop /dev/loop5 (/usr/share/minimal_1.verity).
Sep 09 07:33:21 systemd[452]: minimal-app0-bar.service: Failed to set up mount namespacing: No such file or directory
Sep 09 07:33:21 systemd[452]: minimal-app0-bar.service: Failed at step NAMESPACE spawning cat: No such file or directory
Sep 09 07:33:21 systemd[1]: Received SIGCHLD from PID 452 ((cat)).
Sep 09 07:33:21 systemd[1]: Child 452 ((cat)) died (code=exited, status=226/NAMESPACE)
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Child 452 belongs to minimal-app0-bar.service.
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Control process exited, code=exited, status=226/NAMESPACE
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Got final SIGCHLD for state start-pre.
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Failed with result 'exit-code'.
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Service will not restart (restart setting)
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Changed start-pre -> failed
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Job 486 minimal-app0-bar.service/start finished, result=failed
Sep 09 07:33:21 systemd[1]: Failed to start minimal-app0-bar.service.
```

### PR DESCRIPTION
**Pull request by yuwata**
If multiple services with the same encrypted image are simultaneously
starting, one may deactivate the dm device while others using it.
To prevent such the situation, let's open the dm device
for the decrypted volume.

Fixes #24617.

### CODE REVIEW

File: src/shared/dissect-image.c [hunk 1]
```diff
@@ -2061,6 +2070,33 @@ static int verity_partition(
...
+
+        if (!p->decrypted_node)
+                return 0;
+
+        if (p->decrypted_node_fd >= 0)
+                return p->decrypted_node_fd;
+
+        rw = p->rw && !(flags & DISSECT_IMAGE_MOUNT_READ_ONLY);
+
+        fd = open(p->decrypted_node, O_NONBLOCK | O_CLOEXEC | O_NOCTTY | (rw ? O_RDWR : O_RDONLY));
```
Comment (poettering) [inline src/shared/dissect-image.c]: we can always open this in O_RDONLY mode. We just want to pin, not use for writes. And if we mount via /proc/self/fd/ then the kernel will only look at the inode we pin, and not what kind of fd we have...

File: src/shared/dissect-image.h [hunk 2]
```diff
@@ -26,6 +26,7 @@ struct DissectedPartition {
         char *fstype;
         char *node;
         char *label;
+        int decrypted_node_fd;
```
Comment (poettering) [inline src/shared/dissect-image.h]: hmm, instead of doing this only if decryption is in place, I'd always pin the device here once we know which one to mount. i.e. call this `mount_node_fd` or so, then always open the block device one we figured it out both if encrypted or if not, and then always mount through /proc/self/fd/.

It think that's much prettier since it adds less special casing to the encryption code path

File: src/shared/dissect-image.c (hunk 1 above)
Comment (yuwata) [reply src/shared/dissect-image.c]: Is it possible to use O_PATH?

Comment (poettering) [reply src/shared/dissect-image.c]: I dont think so. I am pretty sure if you use O_PATH the bsd locks would end up being unaffected by the bsd locks on the non-O_PATH fds...

Comment (yuwata) [reply src/shared/dissect-image.c]: OK. Thanks.

File: src/shared/dissect-image.c [hunk 3]
```diff
@@ -228,6 +229,31 @@ static int make_partition_devname(
...
 #endif
 
+#if HAVE_BLKID || HAVE_LIBCRYPTSETUP
+static int dissected_partition_open(DissectedPartition *p) {
+        _cleanup_close_ int fd = -1;
+        const char *node;
+
+        assert(p);
+
+        if (!p->decrypted_node && p->mount_node_fd >= 0)
```
Comment (poettering) [inline src/shared/dissect-image.c]: why the `!p->decrypted_node` check?

File: src/shared/dissect-image.c [hunk 4]
```diff
@@ -1268,12 +1314,13 @@ static int mount_partition(
         assert(m);
         assert(where);
 
+        if (!m->found || m->mount_node_fd < 0)
```
Comment (poettering) [inline src/shared/dissect-image.c]: the left-hand check is redundant, no? the right-hand check already should be enough?

File: src/shared/dissect-image.c [hunk 5]
```diff
@@ -228,6 +229,31 @@ static int make_partition_devname(
...
+        fd = open(node, O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_NOCTTY);
+        if (fd < 0)
+                return -errno;
+
+        log_debug("Opened %s (fd=%i).", node, fd);
+
+        safe_close(p->mount_node_fd);
+        p->mount_node_fd = TAKE_FD(fd);
+
+        return 0;
```
Comment (poettering) [inline src/shared/dissect-image.c]: i think it would make sense to to compare the BLKGETDISKSEQ value of these partition devices with the one of the "whole" device here, to ensure we don't end up with wrong devices.

And beforehand we should check that what we just opened is actually a block device. 

And this call should probably not even try to open() if the "whole" node is not actually a block device itself.

File: src/shared/dissect-image.c (hunk 3 above)
Comment (yuwata) [reply src/shared/dissect-image.c]: First, `dissect_image()` opens all partitions and store their fd into `p->mount_node_fd`.
Then, `dissected_image_decrypt()` opens all decrypted partitions and replaces existing fds.
Hence, `p->mount_node_fd` may be for `p->node`, instead of `p->decrypted_node`.

File: src/shared/dissect-image.c (hunk 5 above)
Comment (yuwata) [reply src/shared/dissect-image.c]: OK.
(But, you said in my other PRs, `dissect_image()` should work for non device fd...)

**Comment by yuwata** [comment]
@poettering and @bluca Rebased on top of my recent cleanup commits. PTAL!

File: src/shared/dissect-image.c [hunk 6]
```diff
@@ -2068,59 +2068,68 @@ static int verity_partition(
...
-                        goto success;
 
-                /* Device is being opened by another process, but it has not finished yet, yield for 2ms */
+                if (existing_cd)
+                        crypt_free_and_replace(cd, existing_cd);
+
+                goto success;
+
+        try_again:
+                /* Device is being removed by another process. Let's wati for a while. */
```
Comment (bluca) [inline src/shared/dissect-image.c]: /wati/wait/

File: src/shared/dissect-image.c [hunk 7]
```diff
@@ -2069,7 +2069,16 @@ static int verity_partition(
          * retry a few times before giving up. */
         for (unsigned i = 0; i < N_DEVICE_NODE_LIST_ATTEMPTS; i++) {
                 _cleanup_(sym_crypt_freep) struct crypt_device *existing_cd = NULL;
+                _cleanup_close_ int fd = -1;
 
+                /* First, check the device is already exist. */
```
Comment (bluca) [inline src/shared/dissect-image.c]: "check if the device already exists"

**Review by bluca — COMMENTED** [review]
commit message mentions a lock is taken, but where does that happen?

**Comment by yuwata** [comment]
> commit message mentions a lock is taken, but where does that happen?

Sorry, I forgot to update the commit message. Now about the lock is dropped from the commit message.

At least in this PR, the partitions are opened but not locked, as udevd locks only whole (native, i.e., non-DM) block devices. So, I cannot find any reasons we need to lock dissected partitions. Also, the whole block device to be dissected may be already locked through `loop_device_open()` or `loop_device_make()`. It may be better to call `loop_device_flock()` in `dissect_loop_device()`. But, I'd like to do that in another PR if necessary.

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
@bluca Thank you for reviewing this PR.
@poettering Could you re-review this if you'd like?

File: src/shared/dissect-image.c [hunk 8]
```diff
@@ -264,6 +265,47 @@ static int make_partition_devname(
         return asprintf(ret, "%s%s%i", whole_devname, need_p ? "p" : "", nr);
 }
 
+static int open_partition(const char *node, bool is_partition, LoopDevice *loop) {
```
Comment (keszybz) [inline src/shared/dissect-image.c]: I think the signature should be:
```C
static int open_partition(const LoopDevice *loop, const char *node, bool is_partition)
```

File: src/shared/dissect-image.c [hunk 9]
```diff
@@ -264,6 +265,47 @@ static int make_partition_devname(
...
+
+                r = fd_get_diskseq(fd, &diskseq);
+                if (r < 0)
+                        return r;
+
+                if (loop->diskseq != diskseq)
+                        return -ENXIO;
+        }
+
+        log_debug("Opened %s (fd=%i).", node, fd);
```
Comment (keszybz) [inline src/shared/dissect-image.c]: Maybe also log diskseq here if non-zero?

File: src/shared/dissect-image.c [hunk 10]
```diff
@@ -2090,14 +2090,16 @@ static int verity_partition(
                 if (!restore_deferred_remove){
                         /* To avoid races, disable automatic removal on umount while setting up the new device. Restore it on failure. */
                         r = dm_deferred_remove_cancel(name);
-                        /* If activation returns EBUSY there might be no deferred removal to cancel, that's fine */
-                        if (r < 0 && r != -ENXIO)
+                        /* -EBUSY and -ENXIO: the device is already removed or being removed. We cannot use the device, try to open again.
```
Comment (keszybz) [inline src/shared/dissect-image.c]: A general comment about tense, here and in other places: "is already removed" → "has already been removed". But I guess you can leave it as-is. The sentence is understandable, even if the grammar is a bit off.

File: src/shared/dissect-image.c (hunk 8 above)
Comment (yuwata) [reply src/shared/dissect-image.c]: The main target is `node`. And `loop` is used for checking the opened file descriptor. I will add the `const` qualifier for `loop`.

**Comment by yuwata** [comment]
@keszybz Thank you for your review. Addressed the above comments, except for the one for the order of the arguments in `open_partition()`. Hopefully, that should not be a big matter. Upgrading the green label.
