### PR TITLE
networkd: limit the number of routes to the kernel limit

### LINKED ISSUE #3922: systemd-networkd: failed with "Argument list too long"
### systemd version the issue has been seen with

```
$ systemctl --version
systemd 231
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```
### Used distribution

Latest ArchLinux with:

```
$ uname -a
Linux ancient 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
```
### In case of bug report: Unexpected behaviour you saw

After recent update of systemd, systemd-networkd failed with:

```
...
Aug 08 10:00:15 ancient systemd[1]: Starting Network Service...
Aug 08 10:00:15 ancient systemd-networkd[429]: Failed to parse file '/etc/systemd/network/ol.network': Argument list too long
Aug 08 10:00:15 ancient systemd-networkd[429]: Could not load configuration files: Argument list too long
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
Aug 08 10:00:15 ancient systemd[1]: Failed to start Network Service.
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Unit entered failed state.
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Service has no hold-off time, scheduling restart.
Aug 08 10:00:15 ancient systemd[1]: Stopped Network Service.
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Start request repeated too quickly.
Aug 08 10:00:15 ancient systemd[1]: Failed to start Network Service.
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Unit entered failed state.
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Failed with result 'start-limit-hit'.
...
```
### In case of bug report: Steps to reproduce the problem

In fact, I have a very long `ol.network` with 1346 routes configured with following format:

```
[Route]
Gateway=10.233.0.5
Destination=223.248.0.0/14

[Route]
Gateway=10.233.0.5
Destination=223.252.128.0/17
...
```

This configuration used to work with last version of systemd.

### PR DESCRIPTION
**Pull request by keszybz**
Fixes #3922.

### CODE REVIEW

**Comment by arvidjaar** [comment]
I apologize for confusion but it appears that `net.ipv4.route.max_size` is leftover that is unused now in kernel. It was removed in 2012 by 89aef8921bfbac22f00e04f8450f6e447db13e42.

Author: David S. Miller davem@davemloft.net
Date:   Tue Jul 17 11:00:09 2012 -0700

```
ipv4: Delete routing cache
```

IPv6 continues to be used though.

File: src/network/networkd-route.c [hunk 1]
```diff
@@ -26,10 +26,37 @@
...
+        _cleanup_free_ char *s4 = NULL, *s6 = NULL;
+        unsigned val4 = ROUTES_DEFAULT_MAX_PER_FAMILY, val6 = ROUTES_DEFAULT_MAX_PER_FAMILY;
+
+        if (cached > 0)
+                return cached;
+
+        if (sysctl_read("net/ipv4/route/max_size", &s4) >= 0) {
+                truncate_nl(s4);
+                if (safe_atou(s4, &val4) >= 0 &&
+                    val4 == 2147483647U)
```
Comment (poettering) [inline src/network/networkd-route.c:46]: maybe write this as val4 >= UINT32_MAX-1?

**Comment by keszybz** [comment]
Damn, I forgot about that the route cache was removed. I guess the way that the code is currently is not harmful currently. But this also means that the kernel (at least for ipv4) uses a different limit. So this requires some more investigation.
