### PR TITLE
sd-device: keep escaped strings in DEVLINK= property

### LINKED ISSUE #17772: Timeout waiting for device who's name contains a space
**systemd version the issue has been seen with**
247

**Used distribution**
Arch Linux

**Linux kernel version used** (`uname -a`)
`Linux archvm1 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
Device which is specified with a space gets successfully mounted and doesn't interrupt booting.

**Unexpected behaviour you saw**
There was a time out waiting for a device which was specifying with a space: `root="PARTLABEL=Arch Linux"` in kernel command line (when using systemd based initramfs):

```
systemd[1]: dev-disk-by\x2dpartlabel-Arch\x5cx20Linux.device: Job dev-disk-by\x2dpartlabel-Arch\x5cx20Linux.device/start timed out.
systemd[1]: Timed out waiting for device /dev/disk/by-partlabel/Arch\x20Linux.
systemd[1]: Dependency failed for Initrd Root Device.
systemd[1]: initrd-root-device.target: Job initrd-root-device.target/start failed with result 'dependency'.
systemd[1]: initrd-root-device.target: Triggering OnFailure= dependencies.
systemd[1]: Dependency failed for /sysroot.
kernel: audit: type=1130 audit(1606647217.833:8): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=emergency comm="systemd" exe="/init" hostname=? addr=? terminal=? res=success'
systemd[1]: Dependency failed for Initrd Root File System.
systemd[1]: Dependency failed for Reload Configuration from the Real Root.
systemd[1]: initrd-parse-etc.service: Job initrd-parse-etc.service/start failed with result 'dependency'.
systemd[1]: initrd-parse-etc.service: Triggering OnFailure= dependencies.
systemd[1]: initrd-root-fs.target: Job initrd-root-fs.target/start failed with result 'dependency'.
systemd[1]: initrd-root-fs.target: Triggering OnFailure= dependencies.
systemd[1]: sysroot.mount: Job sysroot.mount/start failed with result 'dependency'.
systemd[1]: Dependency failed for File System Check on /dev/disk/by-partlabel/Arch\x20Linux.
systemd[1]: systemd-fsck-root.service: Job systemd-fsck-root.service/start failed with result 'dependency'.
systemd[1]: dev-disk-by\x2dpartlabel-Arch\x5cx20Linux.device: Job dev-disk-by\x2dpartlabel-Arch\x5cx20Linux.device/start failed with result 'timeout'.
```

The same can be observed when adding an fstab entry with an escaped space `PARTLABEL=data\040disk`:

```
systemd[1]: dev-disk-by\x2dpartlabel-data\x5cx20disk.device: Job dev-disk-by\x2dpartlabel-data\x5cx20disk.device/start timed out.
systemd[1]: Timed out waiting for device /dev/disk/by-partlabel/data\x20disk.
systemd[1]: Dependency failed for File System Check on /dev/disk/by-partlabel/data\x20disk.
systemd[1]: Dependency failed for /data.
systemd[1]: Dependency failed for Local File Systems.
systemd[1]: local-fs.target: Job local-fs.target/start failed with result 'dependency'.
systemd[1]: local-fs.target: Triggering OnFailure= dependencies.
systemd[1]: data.mount: Job data.mount/start failed with result 'dependency'.
systemd[1]: systemd-fsck@dev-disk-by\x2dpartlabel-data\x5cx20disk.service: Job systemd-fsck@dev-disk-by\x2dpartlabel-data\x5cx20disk.service/start failed with result 'dependency'.
systemd[1]: dev-disk-by\x2dpartlabel-data\x5cx20disk.device: Job dev-disk-by\x2dpartlabel-data\x5cx20disk.device/start failed with result 'timeout'.
```

After the unit times out, in both instances booting could be resumed by pressing the prompted key (`Enter` in the first case or `^D` in the second).

This issue did not occur with systemd 246.6.

**Steps to reproduce the problem**
Using a using systemd-based initramfs, in the kernel command line specify the `root` parameter with a quoted space. E.g.:
```
root="PARTLABEL=Arch Linux"
```

Alternatively specify a device with an escaped space (`\040`) in fstab. E.g.:
```
PARTLABEL=data\040disk /data xfs rw,relatime,nodev,nosuid,attr2,inode64,noquota 0 2
```

Downstream bug report: https://bugs.archlinux.org/task/68785 .

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #17772.

### CODE REVIEW

File: src/basic/hashmap.c [hunk 1]
```diff
@@ -1976,3 +1976,36 @@ IteratedCache* iterated_cache_free(IteratedCache *cache) {
 
         return mfree(cache);
 }
+
+int set_strjoin(Set *s, const char *separator, char **ret) {
+        size_t separator_len, allocated = 0, len = 0;
```
Comment (keszybz) [inline src/basic/hashmap.c:1981]: It doesn't matter too much, but right now the end position is accounted twice: once in `len` and once in `e`. I think it'd be cleaner to just use one variable:
```
        SET_FOREACH(value, s) {
                size_t l = strlen_ptr(value);

                if (l == 0)
                          continue;

                if (!GREEDY_REALLOC(str, allocated, len + l + (first ? 0 : separator_len) + 1))
                        return -ENOMEM;

                if (separator_len > 0 && !first)
                        memcpy(str + len, separator, separator_len);
                memcpy(str + len + first ? 0 : separator_len, value, l);
                len += (first ? 0 : separator_len) + l;
                first = false;
        }
        str[len] = '\0';
```

This has the advantage that we use the slightly faster memcpy instead of strcpy too.

File: src/libsystemd/sd-device/device-private.c [hunk 2]
```diff
@@ -319,7 +319,7 @@ static int device_amend(sd_device *device, const char *key, const char *value) {
                 for (const char *p = value;;) {
                         _cleanup_free_ char *word = NULL;
 
-                        r = extract_first_word(&p, &word, NULL, 0);
+                        r = extract_first_word(&p, &word, NULL, EXTRACT_RETAIN_ESCAPE);
```
Comment (keszybz) [inline src/libsystemd/sd-device/device-private.c:325]: I don't think this is the right approach. If we retain the escapes in the string here, than we would have to make sure that the escapes are removed whereever the string is actually used. In particular, getting a string with escapes from `sd_device_get_devlink_next` would be totally unexpected. Instead of playing games like this, I think the only way to structure the handling of strings is to do full verification and unescaping when originally the data enters the program, and to always operate on "real" values internally, and finally always escape special values when exporting data, as appropriate for the given export format. Thus, when "exporting" the data through `sd_device_get_devlink_next`, no escaping needs to be done. When "exporting" the data through the stringified DEVLINK property, re-escape special characters.

**Review by keszybz — CHANGES_REQUESTED** [review]

**Comment by mbiebl** [comment]
Whatever the final solution, this appears to be something which should be cherry-picked in systemd-stable

**Comment by cdown** [comment]
87a4d41 also breaks cases with slashes, see #17888.

File: src/libsystemd/sd-device/device-private.c (hunk 2 above)
Comment (yuwata) [reply src/libsystemd/sd-device/device-private.c:325]: Besides how we should handle the string, 87a4d416e5126b6fb2528ae192a6a6a8033539ce breaks backward compatibility. Previously, `sd_device_get_devlink_first/next()` provided escaped strings. But now they do not. 

udev rules set escaped string, and sd-device itself did nothing to the input strings.
For backward compatibility, we need to keep the behavior.

**Comment by yuwata** [comment]
Updated.
- slightly optimize `set_strjoin()` as suggested by @keszybz.
- Add a short comment why we need to retain escaped strings.

PTAL.

File: src/libsystemd/sd-device/device-private.c (hunk 2 above)
Comment (keszybz) [reply src/libsystemd/sd-device/device-private.c:325]: Thankfully sd_device_get_devlink_first is strictly undocumented. I guess it'll be up to the person writing the docs whenever that happens to deal with that ;)

**Review by keszybz — COMMENTED** [review]
OK, let's merge this. But I think we should have some plan to create a non-hacky API later on.

**Comment by poettering** [comment]
uh oh, this is problematic. Dropping the ":" from the prefix and suffix of the TAGS= property is problematic. We usually add those in udev so that people can match for tags with shell globs, so that they can just write `*:foo:*` to match for a tag "foo". This works because every tag has a ":" before *and* after. This is done in most modalias strings we generate the same way. Yes, it looks weird to always prefix and suffix with ":", but it makes pattern matching sooo much either.

These properties need to be reverted to the old behaviour!

**Comment by poettering** [comment]
I posted #17930 now, to keep track of this
