### PR TITLE
network: rework IPv6 address generation mode

### LINKED ISSUE #20149: networkd: [IPv6Prefix] Assign= option does not respect [Network] IPv6Token= option
**systemd version the issue has been seen with**
 > 247

**Used distribution**
 > Debian 

**Linux kernel version used** (`uname -a`)

 > `Linux host 5.10.0-0.bpo.7-amd64 #1 SMP Debian 5.10.40-1~bpo10+1 (2021-06-04) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > After settings `IPv6Token=` in `[Network]` section of `.network` file, and `Assign=true` in `[IPv6Prefix]`, the autoconfigured address from the given prefix on the interface should contain interface identifier as specified by `IPv6Token`.

**Unexpected behaviour you saw**
 > The autoconfigured address always uses EUI-64 interface identifier.

Additionally, `[DHCPv6PrefixDelegation]` has its own `Token=` option which acts similarly to `IPv6Token=` in `[Network]` section. I propose if `Token=` is unset, we should follow `IPv6Token=` as well.

Also, `Assign=` should default to the same truth value in both `[IPv6Prefix]` and `[DHCPv6PrefixDelegation]`. Right now the former defaults to false but the latter defaults to true which is confusing. Both defaulting to true is likely the intended behavior.

**Steps to reproduce the problem**
 > `test.network` config

```ini
[Network]
IPv6Token=::1
#IPv6Token=prefixstable # does not work either
IPv6SendRA=yes
...

[IPv6Prefix]
Prefix=fd00:dead:beef:feed::/64
Assign=true # should assign fd00:dead:beef:feed::1/64 to the interface
# but it always assigns fd00:dead:beef:feed:[EUI-64-iid]/64, ignoring IPv6Token option above

...
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #20149.

~~Please review #20226 at first.~~

### CODE REVIEW

File: src/network/networkd-radv.c [hunk 1]
```diff
@@ -19,6 +19,44 @@
 #include "string-table.h"
 #include "strv.h"
 
+void network_adjust_radv(Network *network) {
```
Comment (poettering) [inline src/network/networkd-radv.c:23]: what is this commit precisely doing? i.e. te diff is too hard to read, and your commit just says "move functions"? so are oyu saying this commit just reorders the functions?

Comment (yuwata) [reply src/network/networkd-radv.c:23]: Right. I will update the commit message later.

File: src/network/networkd-address-generation.c [hunk 2]
```diff
@@ -0,0 +1,371 @@
...
+#include "networkd-link.h"
+#include "networkd-network.h"
+#include "string-util.h"
+
+#define DAD_CONFLICTS_IDGEN_RETRIES_RFC7217 3
+
+/* https://tools.ietf.org/html/rfc5453 */
+/* https://www.iana.org/assignments/ipv6-interface-ids/ipv6-interface-ids.xml */
+
+#define SUBNET_ROUTER_ANYCAST_ADDRESS_RFC4291               ((struct in6_addr) { .s6_addr = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 } })
```
Comment (poettering) [inline src/network/networkd-address-generation.c]: should be const, so that the compiler/link can place this in the `.rodata` section and merge it with something else

File: src/network/networkd-address-generation.c [hunk 3]
```diff
@@ -0,0 +1,371 @@
...
+#define SUBNET_ROUTER_ANYCAST_PREFIXLEN                     8
+#define RESERVED_IPV6_INTERFACE_IDENTIFIERS_ADDRESS_RFC4291 ((struct in6_addr) { .s6_addr = { 0x02, 0x00, 0x5E, 0xFF, 0xFE } })
+#define RESERVED_IPV6_INTERFACE_IDENTIFIERS_PREFIXLEN       5
+#define RESERVED_SUBNET_ANYCAST_ADDRESSES_RFC4291           ((struct in6_addr) { .s6_addr = { 0xFD, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF } })
```
Comment (poettering) [inline src/network/networkd-address-generation.c]: here too

File: src/network/meson.build [hunk 4]
```diff
@@ -51,6 +51,8 @@ sources = files('''
         netdev/macsec.h
```
Comment (poettering) [inline src/network/meson.build:51]: so, does this commit just move things? or also change the code? if the latter, any chance this could be spit in two, to make it easier to review? i.e. if this just moves things around I trust everything is in order, i just want to review the actual code changes afte rthat

Comment (yuwata) [reply src/network/meson.build:51]: OK. I will split it into two (or more) commits.

**Comment by yuwata** [comment]
Updated. I split the commits into small parts, and add more commit messages. PTAL.

File: src/network/networkd-radv.c [hunk 5]
```diff
@@ -215,6 +215,9 @@ int link_request_radv_addresses(Link *link) {
                 if (r < 0)
                         return r;
 
+                if (prefixlen > 64)
```
Comment (keszybz) [inline src/network/networkd-radv.c]: Maybe add a comment explaining this? It's not obvious.

File: src/network/networkd-ndisc.c [hunk 6]
```diff
@@ -396,9 +396,20 @@ static int ndisc_router_process_autonomous_prefix(Link *link, sd_ndisc_router *r
...
+                return log_link_error_errno(link, r, "Failed to get prefix address: %m");
+
         r = sd_ndisc_router_prefix_get_prefixlen(rt, &prefixlen);
         if (r < 0)
                 return log_link_error_errno(link, r, "Failed to get prefix length: %m");
+        if (prefixlen > 64) {
+                _cleanup_free_ char *buf = NULL;
+
+                (void) in6_addr_prefix_to_string(&prefix, prefixlen, &buf);
+                log_link_debug(link, "Prefix length is larger than 64, ignoring autonomous prefix %s.", buf);
```
Comment (keszybz) [inline src/network/networkd-ndisc.c]: "Prefix is longer than 64, …"

File: man/systemd.network.xml [hunk 7]
```diff
@@ -2158,11 +2158,9 @@ Table=1234</programlisting></para>
         <term><varname>Token=</varname></term>
         <listitem>
           <para>Specifies an optional address generation mode for assigning an address in each
-          delegated prefix. Takes an IPv6 address. When set, the lower bits of the supplied address is
-          combined with the upper bits of each delegatad prefix received from the WAN interface by the
-          DHCPv6 Prefix Delegation to form a complete address. When <varname>Assign=</varname> is
-          disabled, this setting is ignored. When unset, the EUI-64 algorithm will be used to form
-          addresses. Defaults to unset.</para>
+          delegated prefix. This accepts the same syntax of <varname>Token=</varname> in [IPv6AcceptRA]
+          section. If <varname>Assign=</varname> is disabled, then this setting will be ignored.
```
Comment (keszybz) [inline man/systemd.network.xml]: "is disabled" → "is set to disabled" or "is set to false".

File: man/systemd.network.xml [hunk 8]
```diff
@@ -2158,11 +2158,9 @@ Table=1234</programlisting></para>
...
+          Defaults to unset, and EUI-64 algorithm will be used.</para>
```
Comment (keszybz) [inline man/systemd.network.xml]: "and EUI-64 algorithm will be used" → "which means the EUI-64 algorithm will be used"

File: man/systemd.network.xml [hunk 9]
```diff
@@ -2729,6 +2729,16 @@ Token=prefixstable:2002:da8:1::</programlisting></para>
         </para></listitem>
       </varlistentry>
 
+      <varlistentry>
+        <term><varname>Token=</varname></term>
+        <listitem>
+          <para>Specifies an optional address generation mode for assigning an address in each
+          prefix. This accepts the same syntax of <varname>Token=</varname> in [IPv6AcceptRA] section.
```
Comment (keszybz) [inline man/systemd.network.xml]: "of" → "as"

"*the* [IPv6AcceptRA] section"

File: man/systemd.network.xml [hunk 10]
```diff
@@ -2729,6 +2729,16 @@ Token=prefixstable:2002:da8:1::</programlisting></para>
...
+          If <varname>Assign=</varname> is disabled, then this setting will be ignored. Defaults to
```
Comment (keszybz) [inline man/systemd.network.xml]: "is set to false"

File: man/systemd.network.xml [hunk 11]
```diff
@@ -2729,6 +2729,16 @@ Token=prefixstable:2002:da8:1::</programlisting></para>
...
+          unset, and EUI-64 algorithm will be used.</para>
```
Comment (keszybz) [inline man/systemd.network.xml]: "which means that the EUI-64 algorithm will be used"

**Review by keszybz — COMMENTED** [review]
Looks all reasonable. I can't say I followed all the code logic changes in detail, but I read through them, and didn't see anything suspicious.
