### PR TITLE
core/mount: adjust deserialized state based on if the corresponding mountinfo entry exists or not

### LINKED ISSUE #23796: systemd: mount units fail with "Mount process finished, but there is no mount."
**systemd version the issue has been seen with**
 > [root@fedora ~]# systemctl --version
systemd 250 (v250.3-8.fc36)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS 
+FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

**Used distribution**
 > Fedora release 36 (Thirty Six)

**Linux kernel version used** (`uname -a`)

 > [root@fedora ~]# uname -a
Linux fedora 5.17.5-300.fc36.x86_64 #1 SMP PREEMPT Thu Apr 28 15:51:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > mounts work

**Unexpected behaviour you saw**
 > 
 Mounting units fail with "Mount process finished, but there is no mount.". 
It's hard to reproduce with 'systemctl daemon-reload' after https://github.com/systemd/systemd/issues/10872 , but it's easy to reproduce with 'systemctl daemon-reexec'.
```
× root-test.mount - mount unit for test
     Loaded: loaded (/proc/self/mountinfo; static)
     Active: failed (Result: protocol) since Tue 2022-06-21 08:38:28 EDT; 4s ago
      Where: /root/test
       What: /dev/loop0
        CPU: 3ms

Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Child 3065 belongs to root-test.mount.
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Mount process exited, code=exited, status=0/SUCCESS (success)
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Mount process finished, but there is no mount.
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Failed with result 'protocol'.
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Changed mounting -> failed
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Failed to delete cgroup entry from LSM BPF map: No such file or directory
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Job 2039 root-test.mount/start finished, result=failed
Jun 21 08:38:28 fedora systemd[1]: Failed to mount root-test.mount - mount unit for test.
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Unit entered failed state.
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Consumed 3ms CPU time.
```

**Steps to reproduce the problem**
 > 
1. dd if=/dev/zero of=device_file.img bs=1024 count=20000
2. mkfs.ext4 device_file.img;mkdir -p /root/test
3. add test.sh and root-test.mount 
4. systemd-analyze set-log-level debug
5. run test.sh
```
[root@fedora ~]# cat test.sh 
#!/bin/bash
random_sleep() {
    local long
    long="${1-2}"
    sleep $(bc <<< "scale=4; $long*$RANDOM/327670")
    #    echo $(bc <<< "scale=4; $long*$RANDOM/327670")
}

while true
do
    systemctl start root-test.mount & random_sleep
    systemctl daemon-reexec
    sleep 5
    systemctl status root-test.mount >> /root/mount.log
    grep "but there is no mount" /root/mount.log
    if [ $? -eq 0 ]; then
           break
    fi
    systemctl stop root-test.mount
    sleep 2
done
[root@fedora ~]#
[root@fedora ~]# cat /etc/systemd/system/root-test.mount 
[Unit]
Description=mount unit for test
[Mount]
What=/root/device_file.img
Where=/root/test
Type=ext4
Options=nodev
[root@fedora ~]#
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #23796.
Replaces #23803 and #23851.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @Geass-LL and @jcg190701.

File: src/core/manager.c [hunk 1]
```diff
@@ -1757,6 +1757,10 @@ static void manager_ready(Manager *m) {
                         UID_INVALID, GID_INVALID, 0444);
 
         m->honor_device_enumeration = true;
+
+        /* Re-read /proc/self/mountinfo when the first SIGCHLD event for mount unit is received. As, the
+         * mount states set by mount_enumerate() may be overwritten by the outdated deserialized states. */
```
Comment (lclgo) [inline src/core/manager.c]: I think it's better to also mention that `mount_enumerate may failed to catch the change event`.

Comment (yuwata) [reply src/core/manager.c]: What is "the change event"??

Comment (lclgo) [reply src/core/manager.c]: I mean the change of `/proc/self/mountinfo`.
Emm... tought twice, I was wrong. The mount states set by `mount_enumerate()` should always be up-to-date, even if the libmount monitor is closed when systemd reexcutes.
The comment dosn't need any modify.

**Review by jcg190701 — APPROVED** [review]

File: test/units/testsuite-60.sh [hunk 2]
```diff
@@ -53,6 +53,51 @@ EOF
...
+EOF
+    chmod +x "$MOUNT_MYTMPFS"
+
+    mkdir -p /run/systemd/system
+    cat >/run/systemd/system/tmp-hoge.mount <<EOF
+[Mount]
+What=mytmpfs
+Where=/tmp/hoge
+Type=mytmpfs
+EOF
```
Comment (mrc0mmand) [inline test/units/testsuite-60.sh]: This is going to break on systems where `mount` is already in `/sbin`, like Arch:

```
# command -v mount
/usr/sbin/mount
# MOUNT=$(command -v mount 2>/dev/null)
# echo "$(echo "$MOUNT" | sed -e 's|bin|sbin|')".mytmpfs
/usr/ssbin/mount.mytmpfs
```

What about something like this:

```suggestion
    local mount_path mount_mytmpfs

    mount_path="$(command -v mount 2>/dev/null)"
    mount_mytmpfs="${mount_path/\/bin/\/sbin}.mytmpfs"

    cat >"$mount_mytmpfs" <<EOF
#!/bin/bash

sleep ".\$RANDOM"
exec -- $mount_path -t tmpfs tmpfs "\$2"
EOF
    chmod +x "$mount_mytmpfs"

    mkdir -p /run/systemd/system
    cat >/run/systemd/system/tmp-hoge.mount <<EOF
[Mount]
What=mytmpfs
Where=/tmp/hoge
Type=mytmpfs
EOF

    # shellcheck disable=SC2064
    trap "rm -f /run/systemd/system/tmp-hoge.mount '$mount_mytmpfs" RETURN
```

File: src/core/mount.c [hunk 3]
```diff
@@ -1801,6 +1801,7 @@ static int mount_load_proc_self_mountinfo(Manager *m, bool set_flags) {
                 (void) mount_setup_unit(m, device, path, options, fstype, set_flags);
         }
 
+        m->mountinfo_uptodate = true;
```
Comment (daandemeyer) [inline src/core/mount.c]: Maybe name this `mountinfo_dirty` instead? (and invert all the conditions/assignments)

File: test/units/testsuite-60.sh (hunk 2 above)
Comment (yuwata) [reply test/units/testsuite-60.sh]: Thank you!

File: src/core/mount.c (hunk 3 above)
Comment (yuwata) [reply src/core/mount.c]: Not strong opinion, but I prefer `mountinfo_uptodate`, as if `mountinfo_dirty` or something inverted is used, then we need to set the flag on initialization:
```
*m = (Manager) {
        ...,
        .mountinfo_dirty = true,
};
```

File: test/units/testsuite-60.sh [hunk 4]
```diff
@@ -53,6 +53,53 @@ EOF
     }
 }
 
+cleanup_23796() {(
```
Comment (mrc0mmand) [inline test/units/testsuite-60.sh]: You can drop this function now.

Comment (yuwata) [reply test/units/testsuite-60.sh]: Ouch. Indeed.

File: test/units/testsuite-60.sh [hunk 5]
```diff
@@ -53,6 +53,44 @@ EOF
...
+    mkdir -p /run/systemd/system
+    cat >/run/systemd/system/tmp-hoge.mount <<EOF
+[Mount]
+What=mytmpfs
+Where=/tmp/hoge
+Type=mytmpfs
+EOF
+
+    # shellcheck disable=SC2064
+    trap "rm -f /run/systemd/system/tmp-hoge.mount '$mount_mytmpfs" RETURN
```
Comment (mrc0mmand) [inline test/units/testsuite-60.sh]: Whoops, I missed `'` in my previous comment, sorry about that:

```suggestion
    trap "rm -f /run/systemd/system/tmp-hoge.mount '$mount_mytmpfs'" RETURN
```

Also, I had to add a sleep between `systemctl start` and `systemctl daemon-reexec` below, to reproduce the issue reliably after reverting the first commit from this PR, i.e. the final patch to make it all work is

```diff
diff --git a/test/units/testsuite-60.sh b/test/units/testsuite-60.sh
index c282e9ac68..ebb9ae9936 100755
--- a/test/units/testsuite-60.sh
+++ b/test/units/testsuite-60.sh
@@ -74,10 +74,11 @@ Type=mytmpfs
 EOF
 
     # shellcheck disable=SC2064
-    trap "rm -f /run/systemd/system/tmp-hoge.mount '$mount_mytmpfs" RETURN
+    trap "rm -f /run/systemd/system/tmp-hoge.mount '$mount_mytmpfs'" RETURN
 
     for ((i = 0; i < 10; i++)); do
         systemctl --no-block start tmp-hoge.mount
+        sleep ".$RANDOM"
         systemctl daemon-reexec
 
         sleep 1
```

File: src/core/manager.c [hunk 6]
```diff
@@ -1757,6 +1757,10 @@ static void manager_ready(Manager *m) {
...
+        m->mountinfo_uptodate = false;
```
Comment (poettering) [inline src/core/manager.c]: hmm, I am confused. This is not hooked to SIGCHLD at all? Is the comment outdated?

**Comment by yuwata** [comment]
(The failures in mkosi CIs should not be related.)

**Comment by Geass-LL** [comment]
ping. Now CI is green, could you please review and merge this PR?

File: src/core/mount.c [hunk 7]
```diff
@@ -761,8 +761,31 @@ static int mount_coldplug(Unit *u) {
...
+                        break;
+                case MOUNT_MOUNTING:
+                        new_state = MOUNT_MOUNTING_DONE;
+                        break;
+                default:
+                        break;
+                }
+        else
+                switch (new_state) {
+                case MOUNT_MOUNTING_DONE:
```
Comment (msekletar) [inline src/core/mount.c]: Maybe we should add an assertion here that we have to have control_pid or at least warn when we don't have it.

File: src/core/mount.c [hunk 8]
```diff
@@ -761,8 +761,31 @@ static int mount_coldplug(Unit *u) {
...
+                        new_state = MOUNT_MOUNTING;
+                        break;
+                case MOUNT_UNMOUNTING:
+                        new_state = MOUNT_DEAD;
```
Comment (msekletar) [inline src/core/mount.c]: Because of this we will not really coldplug units that were previously unmounting. Do you know how we make sure that control_pid is rewatched and mount is not marked as dead as prematurely? I mean umounting can take some time specifically for NFS and other network FS types.

**Comment by yuwata** [comment]
@jcg190701 Which variant?

**Comment by jcg190701** [comment]
> @jcg190701 Which variant?

variant_0

**Comment by yuwata** [comment]
@jcg190701 Sorry for late response.
During running your test, do you see `(mount-monitor-dispatch) entered rate limit` or `(mount-monitor-dispatch) left rate limit` in journal?

**Comment by yangmingtai** [comment]
@yuwata Some checks were not successful:  focal-s390x — autopkgtest finished (failure)
Please solve it when you are free. Thanks

**Comment by keszybz** [comment]
LGTM.

I restarted s390x/focal now, let's merge if the tests pass.

**Review by bluca — APPROVED** [review]

**Comment by keszybz** [comment]
I'm adding this to v251.5.
