### PR TITLE
coredumpctl: print a hint if any coredumps are in flight

### LINKED ISSUE #4685: `coredumpctl list` should indicate when a coredump is being processed
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

229

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Debian derivative

### In case of bug report: Expected behaviour you didn't see

If I run `coredumpctl list` while `systemd-coredumpd` is being run to process a new crash, there is no indication in the list output that a new crash has happened but is not ready to view in `coredumpctl` yet. This is especially pronounced on slow hardware, where it can take several minutes to process a new core dump — and during those minutes I could be trying to debug the problem, and could be mislead by `coredumpctl list` not listing any crashes.

### PR DESCRIPTION
**Pull request by keszybz**
Fixes #4685.

### CODE REVIEW

File: src/coredump/coredumpctl.c [hunk 1]
```diff
@@ -871,9 +874,64 @@ static int run_gdb(sd_journal *j) {
...
+
+        r = sd_bus_message_enter_container(reply, SD_BUS_TYPE_ARRAY, "(ssssssouso)");
+        if (r < 0)
+                return bus_log_parse_error(r);
+
+        while ((r = sd_bus_message_read(
+                                reply, "(ssssssouso)",
+                                NULL,  NULL,  NULL,  &state,  NULL,
+                                NULL,  NULL,  NULL,  NULL,  NULL) > 0))
+                if (!STR_IN_SET(state, "dead", "failed"))
```
Comment (martinpitt) [inline src/coredump/coredumpctl.c:920]: Is this really complete? What about "exited" or the various "stop*"? When looking at the various possible states, it almost seems like a whitelist (start, start-post, running) seems easier?

File: src/coredump/coredumpctl.c [hunk 2]
```diff
@@ -933,6 +995,11 @@ int main(int argc, char *argv[]) {
                 assert_not_reached("Shouldn't be here");
         }
 
+        if (units_active > 0)
+                printf("%s-- Warning: %d systemd-coredump@.service %s, output may be incomplete.%s\n",
```
Comment (poettering) [inline src/coredump/coredumpctl.c]: "Warning" appears a bit strong wording. I mean, warning are about something non-critical that is wrong, but there's nothing wrong about coredumps being processed, hence I am not sure "Warning" is the right wording. (also, I figure it makese sense to highlight this, but probably just with normal highlighting, and not necessarily with red highlighting)

File: src/coredump/coredumpctl.c [hunk 3]
```diff
@@ -913,6 +971,10 @@ int main(int argc, char *argv[]) {
                 log_debug("Journal filter: %s", filter);
         }
 
+        units_active = check_units_active();
+        if (units_active < 0)
+                log_warning("Failed to check if any systemd-coredump@.service units are running.");
```
Comment (poettering) [inline src/coredump/coredumpctl.c]: hmm, this would mean we log twice about any error. I think it would be better to move this message string into the check_units_active() call, when checken for the errors of sd_bus_call()

File: src/coredump/coredumpctl.c (hunk 1 above)
Comment (poettering) [reply src/coredump/coredumpctl.c:920]: well, systemd-coredump@.service is defined by us, and we know it doesn't define ExecStop= nor has RemainAfterExit= set, hence I think it's fine to only check for "dead" and "failed" here. In fact I think it's nicer this way, as these are the only two active states where the unit is fully down.

File: src/coredump/coredumpctl.c (hunk 3 above)
Comment (keszybz) [reply src/coredump/coredumpctl.c]: Indeed. check_units_active already logs on all errors, so I removed this and just tweaked the message in check_units_active a bit.

File: src/coredump/coredumpctl.c (hunk 2 above)
Comment (keszybz) [reply src/coredump/coredumpctl.c]: Changed to "Notice". I still keep it red because otherwise it's too easy to miss. It's very likely to want to look at the last coredump, so we really want to point out if any are still being processed.

**Comment by keszybz** [comment]
Updated.
