### PR TITLE
journal: several timestamp cleanups and improvements

### LINKED ISSUE #32492: Journalctl shows wrong timestamp on some hibernation-related log messages after waking from hibernation
### systemd version the issue has been seen with

systemd 255.4-2

### Used distribution

Arch Linux

### Linux kernel version used

6.8.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

journalctl, systemd-journald

### Expected behaviour you didn't see

Some log messages about preparing for hibernation like `Freezing user space processes` should be before I wake up the system at the next day

### Unexpected behaviour you saw

Some of the messages described above are after the time I press power button at next day

see logs below

### Steps to reproduce the problem

1. press power button to show logoff screen of KDE 6
2. click Hibernate
3. press power button at next day
4. view log using `journalctl -b -e`

### Additional program output to the terminal or log subsystem illustrating the issue

The issue is observed on KDE 6 wayland session for this time, but I noticed the same behavior before on KDE 5 X11.

logs
https://fars.ee/Evb9

### PR DESCRIPTION
**Pull request by yuwata**
Closes #32492.

### CODE REVIEW

File: src/shared/logs-show.c [hunk 1]
```diff
@@ -446,37 +446,76 @@ static int output_timestamp_realtime(
...
+static void parse_display_realtime(
+                sd_journal *j,
+                const char *source_realtime,
+                const char *source_monotonic,
+                usec_t *ret) {
+
+        usec_t t, s, u;
+
+        assert(j);
+
```
Comment (bluca) [inline src/shared/logs-show.c:452]: assert(ret)

**Review by bluca — APPROVED** [review]

File: src/journal/journald-audit.c [hunk 2]
```diff
@@ -336,9 +336,8 @@ void process_audit_string(Server *s, int type, const char *data, size_t size) {
         uint64_t seconds, msec, id;
         const char *p, *type_name;
         char id_field[sizeof("_AUDIT_ID=") + DECIMAL_STR_MAX(uint64_t)],
-             type_field[sizeof("_AUDIT_TYPE=") + DECIMAL_STR_MAX(int)],
-             source_time_field[sizeof("_SOURCE_REALTIME_TIMESTAMP=") + DECIMAL_STR_MAX(usec_t)];
-        struct iovec iovec[N_IOVEC_META_FIELDS + 8 + N_IOVEC_AUDIT_FIELDS];
+                type_field[sizeof("_AUDIT_TYPE=") + DECIMAL_STR_MAX(int)];
```
Comment (YHNdnzj) [inline src/journal/journald-audit.c]: switch to `STRLEN` while at it?

File: src/shared/logs-show.c [hunk 3]
```diff
@@ -446,37 +446,77 @@ static int output_timestamp_realtime(
...
-                const char *monotonic,
+                const char *source_realtime,
+                const char *source_monotonic,
                 dual_timestamp *ret_display_ts,
                 sd_id128_t *ret_boot_id) {
 
-        bool realtime_good = false, monotonic_good = false, boot_id_good = false;
+        dual_timestamp
+                header_ts = { USEC_INFINITY, USEC_INFINITY },
+                source_ts = { USEC_INFINITY, USEC_INFINITY };
```
Comment (YHNdnzj) [inline src/shared/logs-show.c]: I think we should introduce `DUAL_TIMESTAMP_INFINITY` or sth.

File: src/shared/logs-show.c [hunk 4]
```diff
@@ -425,19 +423,17 @@ static int output_timestamp_realtime(
...
+                                return log_error_errno(SYNTHETIC_ERRNO(EINVAL), "Failed to format syslog time.");
 
                         if (mode == OUTPUT_SHORT_PRECISE) {
                                 size_t k;
 
                                 assert(sizeof(buf) > strlen(buf));
                                 k = sizeof(buf) - strlen(buf);
 
-                                r = snprintf(buf + strlen(buf), k, ".%06"PRIu64, display_ts->realtime % USEC_PER_SEC);
+                                r = snprintf(buf + strlen(buf), k, ".%06"PRIu64, usec % USEC_PER_SEC);
```
Comment (YHNdnzj) [inline src/shared/logs-show.c]: snprintf_ok?

**Review by YHNdnzj — APPROVED** [review]

File: src/shared/logs-show.c [hunk 5]
```diff
@@ -425,19 +423,16 @@ static int output_timestamp_realtime(
...
                                      localtime_or_gmtime_r(&t, &tm, flags & OUTPUT_UTC)) <= 0)
-                                return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
-                                                       "Failed to format syslog time");
+                                return log_error_errno(SYNTHETIC_ERRNO(EINVAL), "Failed to format syslog time.");
 
                         if (mode == OUTPUT_SHORT_PRECISE) {
                                 size_t k;
 
                                 assert(sizeof(buf) > strlen(buf));
                                 k = sizeof(buf) - strlen(buf);
```
Comment (YHNdnzj) [inline src/shared/logs-show.c]: Just pass this directly to `snprintf_ok`?

File: src/shared/logs-show.c [hunk 6]
```diff
@@ -364,53 +364,51 @@ static int output_timestamp_realtime(
...
                         if (tail == 0)
-                                return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
-                                                       "Failed to format ISO time");
+                                return log_error_errno(SYNTHETIC_ERRNO(EINVAL), "Failed to format ISO time.");
 
                         /* No usec in strftime, need to append */
                         if (mode == OUTPUT_SHORT_ISO_PRECISE) {
                                 assert(ELEMENTSOF(buf) - tail >= 7);
-                                snprintf(buf + tail, ELEMENTSOF(buf) - tail, ".%06"PRI_USEC, display_ts->realtime % USEC_PER_SEC);
+                                if (!snprintf(buf + tail, ELEMENTSOF(buf) - tail, ".%06"PRI_USEC, usec % USEC_PER_SEC))
```
Comment (YHNdnzj) [inline src/shared/logs-show.c]: Hmm, no need to change this? Or, `assert_se(snprintf_ok(...))`?

At least, `_ok`?

Comment (yuwata) [reply src/shared/logs-show.c]: Ouch.

File: src/shared/logs-show.c [hunk 7]
```diff
@@ -439,37 +439,75 @@ static int output_timestamp_realtime(
...
-        if (!monotonic_good || !VALID_MONOTONIC(ret_display_ts->monotonic))
-                monotonic_good = boot_id_good = sd_journal_get_monotonic_usec(j, &ret_display_ts->monotonic, ret_boot_id) >= 0;
-        if (!monotonic_good)
-                ret_display_ts->monotonic = USEC_INFINITY;
-
-        if (!boot_id_good)
-                boot_id_good = sd_journal_get_monotonic_usec(j, NULL, ret_boot_id) >= 0;
-        if (!boot_id_good)
-                *ret_boot_id = SD_ID128_NULL;
+        if (source_realtime && safe_atou64(source_realtime, &t) >= 0 && VALID_REALTIME(t))
```
Comment (poettering) [inline src/shared/logs-show.c:491]: i think it might make sense to introduce parse_realtime_usec() and parse_monotonic_usec() which combine safe_atou64 and VALID_REALTIME/VALID_MONOTONIC
