### PR TITLE
core/transaction: fix issue in dropping unmergeable jobs

### LINKED ISSUE #38765: systemd-tmpfiles-setup started state persists through initrd->root transition
### systemd version the issue has been seen with

dd28a11d5737fc038cb17fa3aab3ab5230ed6f15

### Used distribution

Fedora 42, rawhide (from systemd's mkosi config), Rocky 9

### Linux kernel version used

6.17.0-0.rc3.250826gfab1beda7597.32.fc44.x86_64 (among others)

### CPU architectures issue was seen on

x86_64

### Component

_No response_

### Expected behaviour you didn't see

`systemd-tmpfiles-setup.service` doesn't always run in the real root.

### Unexpected behaviour you saw

`systemd-tmpfiles-setup.service` (sometimes) only runs once inside the initrd, but not again after transitioning:

```
[root@fedora ~]# journalctl --unit systemd-tmpfiles-setup --unit initrd-switch-root
Aug 29 20:22:41 fedora systemd[1]: Starting systemd-tmpfiles-setup.service - Create System Files and Directories...
Aug 29 20:22:41 fedora systemd[1]: Finished systemd-tmpfiles-setup.service - Create System Files and Directories.
Aug 29 20:22:42 fedora systemd[1]: Starting initrd-switch-root.service - Switch Root...
[root@fedora ~]#
```

### Steps to reproduce the problem

I haven't made a ton of progress at narrowing down the cause but I started seeing this once in a while after working through https://github.com/systemd/mkosi/issues/3836. I haven't been able to reproduce this with a raw `mkosi vm`, but I can hit it by booting a pair of RAIDed disks in QEMU with the `mkosi` image produced by this repository, with a couple tiny tweaks.

1. Apply:
```$ git diff
diff --git a/mkosi/mkosi.conf b/mkosi/mkosi.conf
index c8e20bc6b1..4146db8d4c 100644
--- a/mkosi/mkosi.conf
+++ b/mkosi/mkosi.conf
@@ -28,6 +28,8 @@ PassEnvironment=
 [Output]
 RepartDirectories=mkosi.repart
 OutputDirectory=../build/mkosi.output
+Format=disk
+SplitArtifacts=kernel,initrd,partitions

 [Build]
 History=yes
@@ -58,6 +60,8 @@ ExtraTrees=
 Initrds=%O/initrd
 KernelInitrdModules=default

+RootPassword=root
+
 # Disable relabeling by default as it only matters for TEST-06-SELINUX, takes a non-trivial amount of time
 # and results in lots of errors when building images as a regular user.
 SELinuxRelabel=no
@@ -153,3 +157,6 @@ KVM=yes
 [Include]
 Include=%D/mkosi/mkosi.sanitizers
         %D/mkosi/mkosi.coverage
+
+[Config]
+Profiles=lvm,raid
```
2. `mkosi -f box -- meson setup build`
3. `mkosi -f box -- meson compile -C build mkosi
4. Boot the image in QEMU (script attached)

[boot_raid_image.sh](https://github.com/user-attachments/files/22054587/boot_raid_image.sh)

### Additional program output to the terminal or log subsystem illustrating the issue

Full debug log is at https://gist.github.com/pbjhelmert/7d99062790ab37741ff78bf605323efd.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #38765.

### CODE REVIEW

**Comment by yuwata** [comment]
It seems the issue exists at least since 1ffba6fe82d65f2a87b53a21c7927bca8176038c (earlier than v1 !!!), and it seems the situation seems to be worse before the commit. So, I guess the issue exists from the very beginning. Interesting.

**Comment by bluca** [comment]
Is this a regression in v258?

**Comment by yuwata** [comment]
> Is this a regression in v258?

I guess no. But not sure yet. As commented in the above, the very root cause exists since v1. But the issue may be revealed by introducing the 'lenient' job type in v258 and making it used in initrd-switch-root. The report of the original issue is unclear about that.

**Comment by pbjhelmert** [comment]
Definitely not a (recent) regression, the primary environment in which I've been bitten by this is Rocky 9, all the way back at `systemd 252 (252-46.el9_5.2.0.1)`.

**Comment by yuwata** [comment]
Even this is not a regression, the issue is terrible and the fix is not so big, so I'd like this to be in v258, and backport to older releases.
I already confirmed that such spurious removal of jobs not happens with this commit.

**Comment by pbjhelmert** [comment]
Indeed, I've just tested booting a bunch with the setup described in the issue and found that the VM boots healthy consistently with this patch, but without it it hits the error case ~50% of boots.

File: src/core/transaction.c [hunk 1]
```diff
@@ -216,19 +216,20 @@ static int delete_one_unmergeable_job(Transaction *tr, Job *job) {
         return -EINVAL;
 }
 
-static int transaction_merge_jobs(Transaction *tr, sd_bus_error *e) {
+static int transaction_ensure_mergable(Transaction *tr, bool matters_to_anchor, sd_bus_error *e) {
```
Comment (YHNdnzj) [inline src/core/transaction.c]: mergable -> mergeable

File: src/core/transaction.c [hunk 2]
```diff
@@ -216,19 +216,20 @@ static int delete_one_unmergeable_job(Transaction *tr, Job *job) {
...
         assert(tr);
 
-        /* First step, check whether any of the jobs for one specific
-         * task conflict. If so, try to drop one of them. */
         HASHMAP_FOREACH(j, tr->jobs) {
                 JobType t;
 
                 t = j->type;
                 LIST_FOREACH(transaction, k, j->transaction_next) {
+                        if (j->matters_to_anchor || k->matters_to_anchor != matters_to_anchor)
```
Comment (YHNdnzj) [inline src/core/transaction.c]: Hmm? This means all units that matter to anchor are exempted from validation/deletion, which might trigger the assertion on job_type_merge_and_collapse() when actually merging below, no?

File: src/core/transaction.c [hunk 3]
```diff
@@ -216,19 +216,20 @@ static int delete_one_unmergeable_job(Transaction *tr, Job *job) {
...
         int r;
 
         assert(tr);
 
-        /* First step, check whether any of the jobs for one specific
-         * task conflict. If so, try to drop one of them. */
         HASHMAP_FOREACH(j, tr->jobs) {
                 JobType t;
 
                 t = j->type;
```
Comment (YHNdnzj) [inline src/core/transaction.c:233]: please instead check if `job_matters_to_anchor(j) == matters_to_anchor` here

File: src/core/transaction.c [hunk 4]
```diff
@@ -253,7 +254,26 @@ static int transaction_merge_jobs(Transaction *tr, sd_bus_error *e) {
...
+        return 0;
+}
+
+static int transaction_merge_jobs(Transaction *tr, sd_bus_error *e) {
+        Job *j;
+        int r;
+
+        assert(tr);
+
+        /* First step, try to drop unmergable jobs for anchor jobs. */
```
Comment (YHNdnzj) [inline src/core/transaction.c]: anchor jobs -> jobs that matter to anchor

File: src/core/transaction.c (hunk 1 above)
Comment (yuwata) [reply src/core/transaction.c]: Ouch.

File: src/core/transaction.c (hunk 3 above)
Comment (yuwata) [reply src/core/transaction.c:233]: No that does not work. I initially tried that. It is because that some jobs that matter to anchor may exist outside of the hashmap `tr->jobs` but exist in the list `j->transaction_next` of non-anchor job.

File: src/core/transaction.c (hunk 2 above)
Comment (yuwata) [reply src/core/transaction.c]: No, we anyway check all pairs of jobs. Hence the assertion does not triggered. This just changes the order of the check.

File: src/core/transaction.c (hunk 4 above)
Comment (yuwata) [reply src/core/transaction.c]: Thanks. Will update.

**Comment by yuwata** [comment]
@YHNdnzj Thank you for the review. Force pushed an updated version, which fixes the function name and comments. But logic is unchanged. See for the above comments.

File: src/core/transaction.c (hunk 2 above)
Comment (YHNdnzj) [reply src/core/transaction.c]: How? Transaction.jobs is a map between Unit and a _list_ of jobs. Individual jobs for a unit have no associations with each other. But you're checking `j` as the prominent job...

File: src/core/transaction.c (hunk 3 above)
Comment (YHNdnzj) [reply src/core/transaction.c:233]: The function iterates through the list, no?

File: src/core/transaction.c (hunk 2 above)
Comment (yuwata) [reply src/core/transaction.c]: Ah, I forgot `()` in the condition...

File: src/core/transaction.c (hunk 3 above)
Comment (yuwata) [reply src/core/transaction.c:233]: Ah, I misunderstood your point. You suggested `job_matters_to_anchor(j)` but I thought `j->matters_to_anchor`. Yeah, sounds better.

**Comment by yuwata** [comment]
Now I understand @YHNdnzj's point, and fully addressed requests. Also, a test case is added.
PTAL.

**Review by YHNdnzj — APPROVED** [review]
LGTM

**Comment by keszybz** [comment]
Backport queued for v257.10

**Comment by pbjhelmert** [comment]
Is there any chance of a backport for 252 (RHEL-family 9)?

**Comment by daandemeyer** [comment]
> Is there any chance of a backport for 252 (RHEL-family 9)?

This is something you should take up with your distribution. They're supposed to provide support for the version they ship in their official releases. We only support recent versions.
