### PR TITLE
compress: do not call lzma_end_wrapper() when fail to open liblzma

### LINKED ISSUE #40277: [libsystemd] usage of uninitalized function pointer due to failure to lazy load liblzma causes a SEGFAULT
### systemd version the issue has been seen with

259

### Used distribution

Amazon linux

### Linux kernel version used

6.12.58-82.121.amzn2023.x86_64

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

SEGFAULT

### Steps to reproduce the problem

1. Build systemd in an environment with the xz pacakge present.
2. Try to decompress journal files that are compressed with XZ using libsystemd in an environment without liblzma (a part of the xz package)

RCA:
See, for example:
https://github.com/systemd/systemd/blob/e67ad3e586179c03c969a334a3e2b7d742bd1a94/src/basic/compress.c#L536

In the beginning of the function, a call to lzma_end_wrapper is deferred.
dlopen_lzma may fail so the lzma function is never loaded to sym_lzma_end function pointer and it is called anyway in lzma_end_wrapper causing a SEGFAULT.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug in 3fc72d54132151c131301fc7954e0b44cdd3c860 (v256).
Fixes #40277.

### CODE REVIEW

**Review by daandemeyer — APPROVED** [review]

File: src/basic/compress.c [hunk 1]
```diff
@@ -355,20 +355,18 @@ int decompress_blob_xz(
         assert(dst_size);
 
 #if HAVE_XZ
-        _cleanup_(lzma_end_wrapper) lzma_stream s = LZMA_STREAM_INIT;
```
Comment (YHNdnzj) [inline src/basic/compress.c:358]: all functions need similar treatment? i.e. other (de-)compress_*_xz and zstd ones that call ZSTD_freeCCtx

Comment (yuwata) [reply src/basic/compress.c:358]: Indeed. Fixed.

Note, ZSTD_freeDCtxp and friends are not necessary to do like that, as it does nothing when `NULL`.
