### PR TITLE
core/transaction: restart dependency loop when a new dependency is added

### LINKED ISSUE #36031: Assertion 'e->key == i->next_key' failed at src/basic/hashmap.c:670, function hashmap_iterate_in_internal_order().
### systemd version the issue has been seen with

257.2

### Used distribution

Debian Bookworm 

### Linux kernel version used

6.6.69-cloudflare-2025.1.1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

We expected that on a system service restart, that the service restarts.

### Unexpected behaviour you saw

```Jan 10 19:17:54 693dm4 systemd[1]: Assertion 'e->key == i->next_key' failed at src/basic/hashmap.c:670, function hashmap_iterate_in_internal_order(). Aborting.
Jan 10 19:17:54 693dm4 systemd[1]: Caught <ABRT>, from our own process.
Jan 10 19:17:55 693dm4 systemd-coredump[144981]: Process 144980 (systemd) of user 0 dumped core.

                                                 Module /usr/lib/systemd/systemd from deb systemd-257.2-1-cloudflare-2025.1.1.amd64
                                                 Module libsystemd-shared-257.so from deb systemd-257.2-1-cloudflare-2025.1.1.amd64
                                                 Module libsystemd-core-257.so from deb systemd-257.2-1-cloudflare-2025.1.1.amd64
                                                 Stack trace of thread 144980:
                                                 #0  0x00007f6ccd920799 syscall (libc.so.6 + 0x101799)
                                                 #1  0x00007f6ccdc14b91 propagate_signal (libsystemd-shared-257.so + 0x214b91)
                                                 #2  0x00005640ec482d8e n/a (/usr/lib/systemd/systemd + 0x12d8e)
                                                 #3  0x00007f6ccd85b050 __restore_rt (libc.so.6 + 0x3c050)
                                                 #4  0x00007f6ccd8a9ebc __pthread_kill_implementation (libc.so.6 + 0x8aebc)
                                                 #5  0x00007f6ccd85afb2 __GI_raise (libc.so.6 + 0x3bfb2)
                                                 #6  0x00007f6ccd845472 __GI_abort (libc.so.6 + 0x26472)
                                                 #7  0x00007f6ccda96c12 n/a (libsystemd-shared-257.so + 0x96c12)
                                                 #8  0x00007f6ccdbe65c6 n/a (libsystemd-shared-257.so + 0x1e65c6)
                                                 #9  0x00007f6ccdbedb72 _hashmap_iterate (libsystemd-shared-257.so + 0x1edb72)
                                                 #10 0x00007f6cce1421cf transaction_add_job_and_dependencies (libsystemd-core-257.so + 0x1421cf)
                                                 #11 0x00007f6cce0eb7e7 manager_add_job_full (libsystemd-core-257.so + 0xeb7e7)
                                                 #12 0x00007f6cce116df7 n/a (libsystemd-core-257.so + 0x116df7)
                                                 #13 0x00007f6cce117bb3 n/a (libsystemd-core-257.so + 0x117bb3)
                                                 #14 0x00007f6ccdc6e734 n/a (libsystemd-shared-257.so + 0x26e734)
                                                 #15 0x00007f6ccdc6ea8d sd_event_dispatch (libsystemd-shared-257.so + 0x26ea8d)
                                                 #16 0x00007f6ccdc70408 sd_event_run (libsystemd-shared-257.so + 0x270408)
                                                 #17 0x00007f6cce0f3fe4 manager_loop (libsystemd-core-257.so + 0xf3fe4)
                                                 #18 0x00005640ec478e94 n/a (/usr/lib/systemd/systemd + 0x8e94)
                                                 #19 0x00007f6ccd84624a __libc_start_call_main (libc.so.6 + 0x2724a)
                                                 #20 0x00007f6ccd846305 __libc_start_main_impl (libc.so.6 + 0x27305)
                                                 #21 0x00005640ec47b3d1 n/a (/usr/lib/systemd/systemd + 0xb3d1)
                                                 ELF object binary architecture: AMD x86-64
Jan 10 19:17:55 693dm4 systemd[1]: Caught <ABRT>, dumped core as pid 144980.
Jan 10 19:17:55 693dm4 systemd[1]: Freezing execution.
```

### Steps to reproduce the problem

The problem inconsistently reproduces on our production node during a configuration management update.

### Additional program output to the terminal or log subsystem illustrating the issue

gdb backtrace: https://gist.github.com/fredlawl/fc0e5eeeb7023ec0f9405b8f3d12434a

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #36031.

### CODE REVIEW

**Comment by poettering** [comment]
Oh. wow! Excellent work on tracking this one down!

**Review by YHNdnzj — COMMENTED** [review]
It's not really clear to me why this applies to stop and reload jobs but not others. Can you extend the commit message?

**Comment by yuwata** [comment]
> It's not really clear to me why this applies to stop and reload jobs but not others. Can you extend the commit message?

We do not have e.g. WantedBy= or RequiredBy= settings, hence start dependency cannot be added by other units. But, we stop_ignored dependency is added by other units through Conflicts=.
Also, we have both PropagateReloadFrom= and PropagateReloadTo=. Hence, propagate_reload dependency can be also added by other units. Similar for PropagateRestartFrom=/To=.
I will extend commit message.

**Comment by yuwata** [comment]
I noticed that the generation counter does not consider type of dependency, hence even start dependency is not added by other units, we may need to restart the loop when another unit updates one of the dependency type.

**Comment by yuwata** [comment]
The reporter says this introduces infinite loop...

**Comment by yuwata** [comment]
Two more commits are added. Also, sets the restart limit of the loop.
Please review again.

File: src/core/unit.c [hunk 1]
```diff
@@ -636,12 +636,14 @@ static void unit_clear_dependencies(Unit *u) {
                                 hashmap_remove(other_deps, u);
 
                         unit_add_to_gc_queue(other);
+                        other->dependency_generation++;
```
Comment (fredlawl) [inline src/core/unit.c:634]: I may be mistaken, but is this over accounting? `unit_free()` calls `unit_clear_dependencies()` Wouldn't `u` and `other` update twice for the same unit? (other could be a dependency of another, and once unit_free, is now `u` in the next function call)

Comment (yuwata) [reply src/core/unit.c:634]: Sorry, I cannot follow.
Even if it is over counted, there should be no problem.

File: src/core/unit.h [hunk 2]
```diff
@@ -1157,22 +1158,40 @@ typedef struct UnitForEachDependencyData {
...
  * smart: if the atom is unique, we'll directly go to right entry. Otherwise we'll iterate through the
  * per-dependency type hashmap and match all dep that have the right atom set. */
-#define _UNIT_FOREACH_DEPENDENCY(other, u, ma, data)                    \
+#define _UNIT_FOREACH_DEPENDENCY(other, u, ma, restart, data)           \
         for (UnitForEachDependencyData data = {                         \
                         .match_atom = (ma),                             \
                         .by_type = (u)->dependencies,                   \
                         .by_type_iterator = ITERATOR_FIRST,             \
                         .current_unit = &(other),                       \
+                        .restart_on_generation_change = restart,        \
```
Comment (YHNdnzj) [inline src/core/unit.h]: is it necessary to stash `restart` in UnitForEachDependencyData? You already deliberately access `u` below, so `restart` can be used directly too?

Comment (yuwata) [reply src/core/unit.h]: Made all arguments (both `u` and `restart`) stored in `data`.

**Comment by yuwata** [comment]
The reporter confirmed this works. Final review please.

File: src/core/unit.c [hunk 3]
```diff
@@ -3106,6 +3111,9 @@ static int unit_add_dependency_impl(
                 flags |= NOTIFY_DEPENDENCY_UPDATE_TO;
         }
 
+        u->dependency_generation++;
+        other->dependency_generation++;
+
```
Comment (YHNdnzj) [inline src/core/unit.c]: there's no need to bump generation if dependency is unchanged? Should be placed in the two if blocks accordingly?
