### PR TITLE
core/cgroup: cache IO accounting data when pruning a cgroup

### LINKED ISSUE #26988: `systemd-run --wait` only reports non-zero "IO bytes" if `systemctl status` has been called on the transient unit
### systemd version the issue has been seen with

253.1-3-arch

### Used distribution

Arch Linux

### Linux kernel version used

6.2.8+arch1+pf5

### CPU architectures issue was seen on

x86_64

### Component

systemd-run

### Expected behaviour you didn't see

`systemd-run --wait` is supposed to show IO stats at the end of the run:

```
# du -hs --apparent-size "$HOME/tmp/big/test/testcase1"
51G     /home/intelfx/tmp/big/test/testcase1

# systemd-run --wait sh -c "tar -c $HOME/tmp/big/test/testcase1 | cat >/dev/null"
Running as unit: run-u637.service
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 44.625s
CPU time consumed: 44.043s
IP traffic received: 0B
IP traffic sent: 0B
IO bytes read: 100.2G
IO bytes written: 0B
```

(please ignore the ×2, this is due to LUKS encryption causing both the dm and actual disk bdi to appear in io.stat)

### Unexpected behaviour you saw

`systemd-run --wait` displays almost-zero IO stats at the end of the run, UNLESS `systemctl status` is also called on the transient unit::
```
# du -hs --apparent-size "$HOME/tmp/big/test/testcase1"
51G     /home/intelfx/tmp/big/test/testcase1

# systemd-run --wait sh -c "tar -c $HOME/tmp/big/test/testcase1 | cat >/dev/null"
Running as unit: run-u1266.service
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 45.491s
CPU time consumed: 45.155s
IP traffic received: 0B
IP traffic sent: 0B
IO bytes read: 200.0K
IO bytes written: 0B
```

Additionally, when `systemctl status` _is_ run on the transient unit, `systemd-run` output will reflect the IO values reported on the last systemctl invocation:

```
(terminal 1) # systemd-run --wait sh -c "tar -c $HOME/tmp/big/test/testcase1 | cat >/dev/null"
Running as unit: run-u1277.service
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 44.179s
CPU time consumed: 43.584s
IP traffic received: 0B
IP traffic sent: 0B
IO bytes read: 50.0G
IO bytes written: 0B

(terminal 2) # systemctl status run-u1277 -n0
● run-u1277.service - /usr/bin/sh -c tar -c /home/intelfx/tmp/big/test/testcase1 | cat >/dev/null
     Loaded: loaded (/run/systemd/transient/run-u1277.service; transient)
  Transient: yes
     Active: active (running) since Sun 2023-03-26 06:10:35 +04; 22s ago
   Main PID: 1291252 (sh)
         IP: 0B in, 0B out
         IO: 50.0G read, 0B written
      Tasks: 3 (limit: 19032)
     Memory: 6.1G
        CPU: 22.065s
     CGroup: /system.slice/run-u1277.service
             ├─1291252 /usr/bin/sh -c "tar -c /home/intelfx/tmp/big/test/testcase1 | cat >/dev/null"
             ├─1291253 tar -c /home/intelfx/tmp/big/test/testcase1
             └─1291254 cat
```

### Steps to reproduce the problem

Case 1:

1. create a big enough temporary file
2. `systemd-run --wait sh -c "cat /path/to/file >/dev/null"`
3. observe almost zero reported IO

Case 2:
1. create a big enough temporary file
2. `systemd-run --wait sh -c "cat /path/to/file >/dev/null"`
3. while (2) is running, perform a `systemctl status <transient unit>`
4. observe reported IO in (2) matches reported IO in (3)

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by intelfx**
When removing a cgroup in `unit_prune_cgroup()`, read IO metrics to cache them similar to the existing treatment of the CPU and memory usage data.

Note that we do not do this for the IP metrics as the firewall objects are only destroyed in `unit_free()` and thus stay alive long enough to be read out directly by all interested parties.

Fixes #26988.

---

I'm not entirely clear on why we are keeping the BPF objects alive until `unit_free()` (rather than freeing them alongside cgroups), but I guess there is a good reason for that? If not, we should just implement similar caching for the counters and free the BPF objects together with cgroups.

### CODE REVIEW

File: src/core/unit.c [hunk 1]
```diff
@@ -2385,7 +2385,7 @@ static int unit_log_resources(Unit *u) {
 
                 assert(io_fields[k].journal_field);
 
-                (void) unit_get_io_accounting(u, k, k > 0, &value);
+                (void) unit_get_io_accounting(u, k, true, &value);
```
Comment (YHNdnzj) [inline src/core/unit.c]:
```suggestion
                (void) unit_get_io_accounting(u, k, /* allow_cache = */ true, &value);
```

Also this is not really obvious, hence worth a comment.

Comment (intelfx) [reply src/core/unit.c]: Yup, forgot that. I'll update this as soon as I get back home :)

File: src/core/cgroup.c [hunk 2]
```diff
@@ -3571,12 +3571,17 @@ void unit_prune_cgroup(Unit *u) {
...
 
-        /* Cache the last CPU and memory usage values before we destroy the cgroup */
+        /* Cache the last resource usage values before we destroy the cgroup */
         (void) unit_get_cpu_usage(u, /* ret = */ NULL);
 
         for (CGroupMemoryAccountingMetric metric = 0; metric <= _CGROUP_MEMORY_ACCOUNTING_METRIC_CACHED_LAST; metric++)
                 (void) unit_get_memory_accounting(u, metric, /* ret = */ NULL);
 
+        /* All IO metrics are read at once from the underlying cgroup, so issue just a single call */
+        (void) unit_get_io_accounting(u, /* metric = */ 0, /* allow_cache = */ false, /* ret = */ NULL);
```
Comment (YHNdnzj) [inline src/core/cgroup.c]: Ugh, I find the `allow_cache` name rather confusing BTW, as if the cgroup has been destroyed we'd read from cache regardless. Could you rename it to `prefer_cache` or `shortcut_cache`? Otherwise I'll submit a PR later.

**Review by YHNdnzj — APPROVED** [review]

File: src/core/cgroup.c (hunk 2 above)
Comment (intelfx) [reply src/core/cgroup.c]: `skip_update`?

Comment (intelfx) [reply src/core/cgroup.c]: Ah, nevermind, I forgot that it will still go through the cgroup if the cache is invalid.

Comment (intelfx) [reply src/core/cgroup.c]: Actually, given we're bikeshedding the name... I think I don't like `prefer_cache` after all, because it does not properly reflect the fact that we can and will get stale values. Other ideas? :sweat_smile:

Comment (YHNdnzj) [reply src/core/cgroup.c]: Hmm, looking at it a bit closer, I think it's OK to just remove it? `unit_get_cpu_usage` and `_memory_accounting` both don't carry such a param. Effectively this only saves one `unit_get_io_accounting_raw` call which immediately returns `-ENODATA` if `!crt->cgroup_path` anyway.

**Review by yuwata — APPROVED** [review]

File: src/core/cgroup.c (hunk 2 above)
Comment (intelfx) [reply src/core/cgroup.c]: It's one call per IO metric, but overall yep, you're right. The regular DBus unit property path does not make use of `allow_cache` anyway, which means the complexity is already `O(n^2)` most of the time (but with n=4 I don't think it's worth optimizing).

**Comment by intelfx** [comment]
Anyone has any words about the BPF objects used for IP accounting? Why are we keeping them until `unit_free()`?

File: src/core/cgroup.c [hunk 3]
```diff
@@ -3571,12 +3571,17 @@ void unit_prune_cgroup(Unit *u) {
...
 
-        /* Cache the last CPU and memory usage values before we destroy the cgroup */
+        /* Cache the last resource usage values before we destroy the cgroup */
         (void) unit_get_cpu_usage(u, /* ret = */ NULL);
 
         for (CGroupMemoryAccountingMetric metric = 0; metric <= _CGROUP_MEMORY_ACCOUNTING_METRIC_CACHED_LAST; metric++)
                 (void) unit_get_memory_accounting(u, metric, /* ret = */ NULL);
 
+        /* All IO metrics are read at once from the underlying cgroup, so issue just a single call */
+        (void) unit_get_io_accounting(u, /* metric = */ 0, /* ret = */ NULL);
```
Comment (poettering) [inline src/core/cgroup.c]: hmm i find it weird to pass 0 here, because that is just a weird way to write `CGROUP_IO_READ_BYTES`, and that's really misleading here.

I think it would be nice to explicitly specify _CGROUP_IO_ACCOUNTING_METRIC_INVALID here, and make sure that unit_get_io_accounting() is fine with that, as long as `ret` is specified as NULL, and in that case just reads stuff and doesn't return anything.

**Comment by poettering** [comment]
> Anyone has any words about the BPF objects used for IP accounting? Why are we keeping them until `unit_free()`?

Hmm, i guess we could clean that up at the same time as the cgroup. i see no reason to keep it any longer.

File: src/core/cgroup.c (hunk 3 above)
Comment (intelfx) [reply src/core/cgroup.c]: Fair enough, done.

**Comment by intelfx** [comment]
> > Anyone has any words about the BPF objects used for IP accounting? Why are we keeping them until `unit_free()`?
> 
> Hmm, i guess we could clean that up at the same time as the cgroup. i see no reason to keep it any longer.

OK, I'll see what I can do. I'd rather make it another PR though? I'd prefer to get this one backported because it fixes a user-facing issue.

File: src/core/cgroup.c [hunk 4]
```diff
@@ -4858,12 +4863,14 @@ static int unit_get_io_accounting_raw(
...
                 Unit *u,
                 CGroupIOAccountingMetric metric,
-                bool allow_cache,
                 uint64_t *ret) {
 
         uint64_t raw[_CGROUP_IO_ACCOUNTING_METRIC_MAX];
         int r;
 
+        assert(metric < _CGROUP_IO_ACCOUNTING_METRIC_MAX
+               || (ret == NULL && metric == _CGROUP_IO_ACCOUNTING_METRIC_INVALID));
```
Comment (YHNdnzj) [inline src/core/cgroup.c]: Hmm, the `< _CGROUP_IO_...MAX` part would always be true, no? Maybe:

```c
/* We specialize the case where _..._INVALID is specified as metric, and no retval is expected, which means the caller wants to refresh the cached values */
assert(metric >= 0 || (metric == _..._INVALID && !ret));
assert(metric < _..._MAX);
```

File: src/core/cgroup.c [hunk 5]
```diff
@@ -4873,11 +4880,9 @@ int unit_get_io_accounting(
         if (!crt)
                 return -ENODATA;
 
-        if (allow_cache && crt->io_accounting_last[metric] != UINT64_MAX)
-                goto done;
-
         r = unit_get_io_accounting_raw(u, crt, raw);
-        if (r == -ENODATA && crt->io_accounting_last[metric] != UINT64_MAX)
+        if (r == -ENODATA
+            && metric < _CGROUP_IO_ACCOUNTING_METRIC_MAX && crt->io_accounting_last[metric] != UINT64_MAX)
```
Comment (YHNdnzj) [inline src/core/cgroup.c]: This should be metric >= 0 too

**Review by YHNdnzj — CHANGES_REQUESTED** [review]

File: src/core/cgroup.c (hunk 4 above)
Comment (intelfx) [reply src/core/cgroup.c]: Oops, that's a thinko — I somehow ended up convincing myself that _INVALID is > _MAX rather than being -EINVAL. Fixed.

Comment (YHNdnzj) [reply src/core/cgroup.c]: Please include a comment like this. When doing null ptr checks we rely on them degrading to bool BTW, no need for == NULL

Comment (intelfx) [reply src/core/cgroup.c]: OK. The coding style said that I "may" use downgrade-to-bool for NULL checks, so I went with my own preference, but if it's actually a requirement, fine.

**Review by YHNdnzj — APPROVED** [review]
