### PR TITLE
make "bootctl random-seed" handle two kinds of failures more gracefully

### LINKED ISSUE #13603: Failed to start Store a SystemToken in an EFI Variable
**systemd version the issue has been seen with**
> 243.0

**Used distribution**
 > Archlinux

**Expected behaviour you didn't see**
 > With random seed successfully already set in EFI variable through `#bootctl random-seed`, systemd-boot-system-token.service should not fire.

**Unexpected behaviour you saw**
 > Unit started and failed with error:
`Failed to start Store a System Token in an EFI Variable`

**Steps to reproduce the problem**
> Start systemd-boot-system-token.service with default
`ConditionPathExists=|!/sys/firmware/efi/efivars/LoaderRandomSeed-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f`
No such file exists even with EFI variable already set through `#bootctl random-seed`.
Suspect the EFI variable's name changed?  No error when unit file amended to:
`ConditionPathExists=|!/sys/firmware/efi/efivars/LoaderSystemToken-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f`

### PR DESCRIPTION
**Pull request by poettering**
Fixes #13603

### CODE REVIEW

File: src/boot/bootctl.c [hunk 1]
```diff
@@ -1458,11 +1458,15 @@ static int install_random_seed(const char *esp) {
          * state. */
         RUN_WITH_UMASK(0077) {
                 r = efi_set_variable(EFI_VENDOR_LOADER, "LoaderSystemToken", buffer, sz);
-                if (r < 0)
+                if (r == -EINVAL) /* Some firmwares don't allow us to write arbitrary variables, let's ignore
+                                   * this error, and accept our fate. */
+                        log_notice("Firmware refused writing of 'LoaderSystemToken', skipping operation.");
```
Comment (keszybz) [inline src/boot/bootctl.c]: I don't think this should say "Firmware", since you never know. Might be SELinux or the kernel or some other thing.

File: src/boot/bootctl.c [hunk 2]
```diff
@@ -1708,7 +1708,11 @@ static int verb_set_default(int argc, char *argv[], void *userdata) {
 static int verb_random_seed(int argc, char *argv[], void *userdata) {
         int r;
 
-        r = acquire_esp(false, NULL, NULL, NULL, NULL);
+        r = find_esp_and_warn(arg_esp_path, false, &arg_esp_path, NULL, NULL, NULL, NULL);
+        if (r == -ENOKEY) {
+                log_notice("No ESP found, not initializing random seed.");
+                return 0;
+        }
```
Comment (keszybz) [inline src/boot/bootctl.c:1731]: That seems wrong. If I call `bootctl random-seed` I really expect something to happen and we shouldn't suppress errors. If the service that uses that command is called in wrong conditions, then the conditionalization of the service needs to be fixed.

File: src/boot/bootctl.c (hunk 1 above)
Comment (poettering) [reply src/boot/bootctl.c]: EINVAL is not an error SELinux causes, but you are right, there might be other reasons than the firmware

File: src/boot/bootctl.c (hunk 2 above)
Comment (poettering) [reply src/boot/bootctl.c:1731]: The conditionalization is really hard, since the ESP might be mounted at a variety of places really. we actively search for it. Note that you will still see a log msg if we skip operation, so it's not that it's entirely silent and invisible...

Comment (keszybz) [reply src/boot/bootctl.c:1731]: Then I think we need to check if we are running as part of the service, and only change behaviour in that case. I think making this explicit would be best: add a command line option `--skip-if-no-efi`, and call `bootctl random-seed --skip-if-no-efi` in the unit.

**Comment by poettering** [comment]
Force pushed a new version that adds `--graceful` along the lines suggested by @keszybz (covering both cases)

File: man/bootctl.xml [hunk 3]
```diff
@@ -183,6 +183,12 @@
         <listitem><para>Do not touch the firmware's boot loader list stored in EFI variables.</para></listitem>
       </varlistentry>
 
+      <varlistentry>
+        <term><option>--graceful</option></term>
```
Comment (keszybz) [inline man/bootctl.xml:187]: Hmm, maybe `--permissive` or `--sloppy` rather than `--graceful`? I understand where you're coming from, but if one doesn't think about "graceful failure", then this is name is very unclear.

Comment (keszybz) [reply man/bootctl.xml:187]: I think we can still change the name before the final release. Let's merge this as is now.
