### PR TITLE
Don't assume /run/systemd exists when creating unit-root

### LINKED ISSUE #17842: test_exec_basic fails in mkosi after updating to systemd v247
**systemd version the issue has been seen with**
 > master branch

**Used distribution**
 > Arch

**Linux kernel version used** (`uname -a`)
 > 5.9.11

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Tests pass

**Unexpected behaviour you saw**
 > test_exec_basic fails

**Steps to reproduce the problem**
 > sudo mkosi --default .mkosi/mkosi.fedora (or any distro of your choice)

Encountered this one while trying to fix #17828. Didn't encounter it yesterday and happened to update to v247 inbetween yesterday and today so I'm suspecting it's got something to do with the changes introduced in v247.

```
292/417 test-execute                              FAIL           0.12s (killed by signal 6 SIGABRT)

--- command ---
18:07:13 SYSTEMD_LANGUAGE_FALLBACK_MAP='/root/src/src/locale/language-fallback-map' PATH='/root/build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' SYSTEMD_KBD_MODEL_MAP='/root/src/src/locale/kbd-model-map' /root/build/test-execute
--- Listing only the last 100 lines from a long log. ---
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-environment-no-substitute.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-systemcallfilter-failing2.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-passenvironment-repeated.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-standardinput-data.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-systemcallfilter-with-errno-number.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-dynamicuser-fixeduser-games.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-capabilityboundingset-merge.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-umask-default.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-privatedevices-yes-capability-mknod.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-readwritepaths-mount-propagation.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-runtimedirectory-owner-nfsnobody.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-protectkernellogs-no-capabilities.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-privatedevices-no.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-privatedevices-no-capability-mknod.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-protectkernelmodules-yes-capabilities.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-dynamicuser-fixeduser-adm.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-supplementarygroups-multiple-groups-default-group-user.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-systemcallfilter-not-failing.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-protectkernelmodules-yes-mount-propagation.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-supplementarygroups-multiple-groups-withgid.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-privatedevices-disabled-by-prefix.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-ambientcapabilities-merge.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-readonlypaths-mount-propagation.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-user-nfsnobody.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-personality-ppc64le.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-environment.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-systemcallfilter-not-failing2.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-supplementarygroups-single-group-user.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-protecthome-tmpfs-vs-protectsystem-strict.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-environment-empty.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-privatedevices-yes-capability-sys-rawio.service
unit_file_build_name_map: normal unit file: /root/src/test/test-execute/exec-restrictnamespaces-mnt.service
proc.mount: Failed to load configuration: No such file or directory
proc-sys.mount: Failed to load configuration: No such file or directory
proc-sys-kernel.mount: Failed to load configuration: No such file or directory
proc-sys-kernel-random.mount: Failed to load configuration: No such file or directory
sys.mount: Failed to load configuration: No such file or directory
dev.mount: Failed to load configuration: No such file or directory
var.mount: Failed to load configuration: No such file or directory
root.mount: Failed to load configuration: No such file or directory
run.mount: Failed to load configuration: No such file or directory
SELinux enabled state cached to: disabled
Successfully created private D-Bus server.
Bus bus-system: changing state UNSET → OPENING
Bus bus-system: changing state OPENING → CLOSED
Failed to connect to system bus: No such file or directory
Invoking unit coldplug() handlers…
-.slice changed dead -> active
efi.mount: Changed dead -> mounted
root-dest.mount: Changed dead -> mounted
sys-devices.mount: Changed dead -> mounted
proc-fs.mount: Changed dead -> mounted
proc-bus.mount: Changed dead -> mounted
sys-kernel.mount: Changed dead -> mounted
root-build.mount: Changed dead -> mounted
proc-acpi.mount: Changed dead -> mounted
proc-sys-net.mount: Changed dead -> mounted
run-host.mount: Changed dead -> mounted
-.mount: Changed dead -> mounted
sys-dev.mount: Changed dead -> mounted
dev-mqueue.mount: Changed dead -> mounted
init.scope changed dead -> running
run-host-os\x2drelease.mount: Changed dead -> mounted
proc-asound.mount: Changed dead -> mounted
var-tmp.mount: Changed dead -> mounted
proc-sys-kernel-random-boot_id.mount: Changed dead -> mounted
sys-class.mount: Changed dead -> mounted
tmp.mount: Changed dead -> mounted
sys-block.mount: Changed dead -> mounted
proc-scsi.mount: Changed dead -> mounted
sys-bus.mount: Changed dead -> mounted
run-host-incoming.mount: Changed dead -> mounted
proc-irq.mount: Changed dead -> mounted
Invoking unit catchup() handlers…
shutdown.target: Failed to load configuration: No such file or directory
basic.target: Failed to load configuration: No such file or directory
exec-basic.service: ConditionKernelVersion=" >= 2.0" " * " "*.*" succeeded.
exec-basic.service: ConditionKernelVersion=" >= 2.0" " <= 60 " "!= 1.4" succeeded.
exec-basic.service: ConditionKernelVersion=">=2.0" "<=60" "!=1.4" succeeded.
exec-basic.service: ConditionKernelVersion=">=3.0" succeeded.
exec-basic.service: Failed to set 'memory.limit_in_bytes' attribute on '/8f23b4c65cdebd7/exec-basic.service' to '-1': No such file or directory
exec-basic.service: Failed to set 'pids.max' attribute on '/8f23b4c65cdebd7/exec-basic.service' to 'max': No such file or directory
exec-basic.service: Passing 0 fds to service
exec-basic.service: About to execute: /usr/bin/touch /tmp/a
exec-basic.service: Forked /usr/bin/touch as 6196
exec-basic.service: Changed dead -> start
Received SIGCHLD from PID 6196 ((touch)).
Child 6196 ((touch)) died (code=exited, status=226/NAMESPACE)
exec-basic.service: Failed to read oom_kill field of memory.events cgroup attribute: No such file or directory
exec-basic.service: Child 6196 belongs to exec-basic.service.
exec-basic.service: Main process exited, code=exited, status=226/NAMESPACE
exec-basic.service: Failed with result 'exit-code'.
exec-basic.service: Service will not restart (restart setting)
exec-basic.service: Changed start -> failed
exec-basic.service: Unit entered failed state.
Spawning thread to nuke /tmp/systemd-private-b2d70b4916b64f00b671ddd76882c67d-exec-basic.service-DZkrir
Spawning thread to nuke /var/tmp/systemd-private-b2d70b4916b64f00b671ddd76882c67d-exec-basic.service-vBuyIr
test_exec_basic: exec-basic.service: exit status 226, expected 0
-------

Full log written to /root/build/meson-logs/testlog.txt
FAILED: meson-test 
/usr/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
‣ Error: Build script returned non-zero exit code 1.
```

### PR DESCRIPTION
**Pull request by daandemeyer**
Fixes #17842.

Pretty sure this isn't the right place to fix this but hopefully this gets some discussion going about where this should be fixed. 

9fac502920a648d82e21b207989bfc3c00fbdebc changed something that causes /run/systemd to not exist when a mount namespace is created for a unit inside a container. This causes tests that need a mount namespace to fail when running in an nspawn container. Finding this error took me quite long because by the time the error is logged from the child process, stderr has already been overwritten by the stderr fd from the process we're going to invoke.

I'm guessing a better fix would be to create /run/systemd at the correct place but I'm unsure what the correct place is.

Test plan:

- Without this change, `mkosi --default .mkosi/mkosi.fedora` will fail when running test_exec_basic
- With this change, `mkosi --default .mkosi/mkosi.fedora` will fail when running test_exec_dynamicuser (which is another bug I'm trying to solve before I encountered this one by upgrading to v247)

(All these test failures I'm encountering now with mkosi are a good argument for merging #17787 so we catch these errors immediately instead of much later when someone runs the tests in mkosi)

### CODE REVIEW

File: src/core/namespace.c [hunk 1]
```diff
@@ -1548,7 +1548,7 @@ int setup_namespace(
                  * in their own namespaces after all, and hence won't see each other. */
 
                 root = "/run/systemd/unit-root";
-                (void) mkdir_label(root, 0700);
+                (void) mkdir_p_label(root, 0700);
```
Comment (yuwata) [inline src/core/namespace.c]: /run/systemd should be 0755.

**Review by yuwata — COMMENTED** [review]
By looking at https://github.com/systemd/systemd/commit/9fac502920a648d82e21b207989bfc3c00fbdebc, I think `outer_child()` in nspawn.c should create the directory...

**Comment by poettering** [comment]
hmm, /run/systemd is created already in mount_setup() in src/core/mount-setup.c, i.e. very early during PID 1 set up. Are you saying you booted up a container with systemd where /run/systemd/ didn't exist? That cannot happen, PID 1 should not be able to run if it cannot create /run/systemd. Not grokking this

**Comment by poettering** [comment]
or is this a container without systemd running as pid1? i.e. an npsawn container withouth `--boot`?

**Comment by DaanDeMeyer** [comment]
It's mkosi running the build script so there's no systemd running as pid1 in the container. I'm guessing the test manager that is started by test-execute might not create /run/systemd?

**Comment by yuwata** [comment]
When nspawn without `--boot`, /run/systemd seems to be not created now, because of 9fac502920a648d82e21b207989bfc3c00fbdeb. The existence of `/run/systemd` is almost API we assume, no? Again, I think `outer_child()` should create the directory.

**Comment by poettering** [comment]
ok, place to fix this looks right then, but please use the right access mode (i.e. create the dir with a separate mkdir_p_label() call), as @yuwata  said.

Also, please accompany that line with a brief comment, maybe `/* /run/systemd should have been created by PID 1 early on already, but let's create it here if missing anyway, to make testing without booted PID 1 easy */` 

or something lke that.

**Comment by yuwata** [comment]
(BTW, now ubuntu CIs seem to work again!)

**Comment by DaanDeMeyer** [comment]
Updated to use separate mkdir_p_label with correct mode. @yuwata's idea of this being practically public API makes sense though. On the other hand, this seems like an edge case. The /run/systemd directory is only for use by systemd right? If so, this fix should be fine.

**Review by bluca — APPROVED** [review]
Looks good and requested changes have been applied, setting green label. Semaphore error seems unrelated:

> Assertion 'manager_get_unit_by_pid(m, 4711) == NULL' failed at src/test/test-watch-pid.c:45, function main(). Aborting.

**Comment by DaanDeMeyer** [comment]
Bionic-i386 timed out again
