### PR TITLE
cryptsetup-fido2: Try all FIDO2 key slots when opening LUKS volume

### LINKED ISSUE #19208: RFE: cryptsetup: support automatic LUKS header FIDO2 param discovery even if multiple FIDO2 tokens are enrolled
**systemd version the issue has been seen with**
 > v248

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > `Linux unicorn 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > I'm able to unlock my root volume with one of my fido2 keys

**Unexpected behaviour you saw**
 > I was unable to unlock, with either `fido2-device=auto` or `fido2-device=/dev/hidraw1` passed as `rd.luks.options=`

**Steps to reproduce the problem**
 > Enrolled 2 keys using `systemd-cryptenroll --fido2-device=auto /dev/nvme0n1p4` each time (with only one key plugged in each time)

**Additional program output to the terminal or log subsystem illustrating the issue**
When booting with `fido2-device=auto`:

```
Apr 05 01:35:12 archlinux kernel: Command line: rd.luks.options=fido2-device=auto rd.luks.uuid=c399df9f-f0db-4b5d-8743-27ebfe445161 rd.luks.name=c399df9f-f0db-4b5d-8743-27ebfe445161=unicorn root=/dev/mapper/unicorn debug
...
Apr 05 01:35:12 archlinux systemd-cryptsetup[209]: Multiple FIDO2 tokens enrolled, cannot automatically determine token.
Apr 05 01:35:12 archlinux systemd-cryptsetup[209]: Automatic FIDO2 metadata discovery was not possible because missing or not unique, falling back to traditional unlocking.
```

When booting with `fido2-device=/dev/hidraw1`
```
Apr 05 02:40:07 archlinux kernel: Command line: rd.luks.options=fido2-device=/dev/hidraw1 rd.luks.uuid=c399df9f-f0db-4b5d-8743-27ebfe445161 rd.luks.name=c399df9f-f0db-4b5d-8743-27ebfe445161=unicorn root=/dev/mapper/unicorn debug
...
Apr 05 02:40:07 archlinux systemd-cryptsetup[203]: Multiple FIDO2 tokens enrolled, cannot automatically determine token.
Apr 05 02:40:07 archlinux systemd-cryptsetup[203]: Automatic FIDO2 metadata discovery was not possible because missing or not unique, falling back to traditional unlocking.
```

```
# systemd-cryptenroll --fido2-device=list
PATH         MANUFACTURER PRODUCT              
/dev/hidraw1 Yubico       YubiKey OTP+FIDO+CCID

# systemd-cryptenroll --fido2-device=list
PATH         MANUFACTURER PRODUCT   
/dev/hidraw0 SoloKeys     Solo 2.3.0
```

### PR DESCRIPTION
**Pull request by PeterCxy**
After #25268, it is now possible to check whether a credential is present on a FIDO2 token without actually attempting to retrieve said credential. However, when cryptsetup plugins are not enabled, the fallback unlock routines are not able to make multiple attempts with multiple different FIDO2 key slots.

Instead of looking for one FIDO2 key slot when trying to unlock, we now attempt to use all key slots applicable.

Fixes #19208.

### CODE REVIEW

File: src/cryptsetup/cryptsetup-fido2.c [hunk 1]
```diff
@@ -121,42 +135,42 @@ int acquire_fido2_key(
...
                 _cleanup_(json_variant_unrefp) JsonVariant *v = NULL;
                 JsonVariant *w;
+                _cleanup_free_ void *salt = NULL;
+                _cleanup_free_ char *rp = NULL;
+                size_t salt_size = 0;
                 int ks;
 
-                r = cryptsetup_get_token_as_json(cd, token, "systemd-fido2", &v);
-                if (IN_SET(r, -ENOENT, -EINVAL, -EMEDIUMTYPE))
+                int res_json = cryptsetup_get_token_as_json(cd, token, "systemd-fido2", &v);
```
Comment (bluca) [inline src/cryptsetup/cryptsetup-fido2.c]: why is a new variable used instead of `r`?

File: src/cryptsetup/cryptsetup-fido2.c [hunk 2]
```diff
@@ -121,42 +135,42 @@ int acquire_fido2_key(
...
+                void **ret_decrypted_key,
+                size_t *ret_decrypted_key_size,
+                AskPasswordFlags ask_password_flags) {
+
+        _cleanup_free_ void *cid = NULL;
+        size_t cid_size = 0;
+        int r = -ENOENT;
         Fido2EnrollFlags required = 0;
 
         assert(cd);
```
Comment (bluca) [inline src/cryptsetup/cryptsetup-fido2.c:149]: sprinkle a few asserts here for the new parameters

File: src/cryptsetup/cryptsetup-fido2.c [hunk 3]
```diff
@@ -243,20 +250,36 @@ int find_fido2_auto_data(
...
+                                cid, cid_size,
+                                key_file, key_file_size, key_file_offset,
+                                salt, salt_size,
+                                until,
+                                headless,
+                                required,
+                                ret_decrypted_key, ret_decrypted_key_size,
+                                ask_password_flags);
+
+                if (!r)
```
Comment (bluca) [inline src/cryptsetup/cryptsetup-fido2.c]: `r == 0`

File: src/cryptsetup/cryptsetup-fido2.c (hunk 1 above)
Comment (PeterCxy) [reply src/cryptsetup/cryptsetup-fido2.c]: Because we want to preserve the error codes of previous calls to `acquire_fido2_key` even if later calls to `cryptsetup_get_token_as_json` fail. This loop will only terminate if `acquire_fido2_key` succeeds or we exhaust all LUKS key slots, in which case `cryptsetup_get_token_as_json` fails with one of the error codes checked below. When that happens, we still want this function to return the error code of the last actual call to `acquire_fido2_key`.

**Review by bluca — APPROVED** [review]

File: src/cryptsetup/cryptsetup-fido2.c [hunk 4]
```diff
@@ -112,6 +94,31 @@ int acquire_fido2_key(
                         device_exists = true;  /* now we know for sure, a device exists, no need to ask again */
                 }
 
+                /* Always make an attempt at using the current key slot before asking for PIN.
```
Comment (poettering) [inline src/cryptsetup/cryptsetup-fido2.c]: current key slot?

File: src/cryptsetup/cryptsetup-fido2.c [hunk 5]
```diff
@@ -112,6 +94,31 @@ int acquire_fido2_key(
...
+                 * fido2_use_hmac_hash will perform a pre-flight check for whether the credential for
```
Comment (poettering) [inline src/cryptsetup/cryptsetup-fido2.c]: we generally suffix function names with () in documentation and comments

File: src/cryptsetup/cryptsetup-fido2.c (hunk 1 above)
Comment (poettering) [reply src/cryptsetup/cryptsetup-fido2.c]: please do this the other way round, i.e. use "r" for the local errors, and collect the final error in some variable "ret" or "rr" or so. That'd be more in line how we usually do things.

i.e. `r` should always be good to use for every use, and if you want to keep the error for longer, than that's the special case that should get its own variable.

File: src/cryptsetup/cryptsetup-fido2.c [hunk 6]
```diff
@@ -243,20 +246,36 @@ int find_fido2_auto_data(
...
 
         if (!cid)
                 return log_error_errno(SYNTHETIC_ERRNO(ENXIO),
                                        "No valid FIDO2 token data found.");
 
-        log_info("Automatically discovered security FIDO2 token unlocks volume.");
+        if (r < 0) {
+                if (r == -EAGAIN) /* fido2 device does not exist, or UV is blocked (reinsertion needed) */
+                        return log_error_errno(r,
+                                               "FIDO2 token not available");
```
Comment (poettering) [inline src/cryptsetup/cryptsetup-fido2.c]: should not be an error? i.e. not log_error_errno()...

i'd write this like this:

```c
if (r == -EAGAIN)
        …
if (r < 0)
        …
```

in the interest of keeping indentation level low/reduce nesting

Comment (poettering) [inline src/cryptsetup/cryptsetup-fido2.c]: the comment and the log message say two different things btw?

File: src/cryptsetup/cryptsetup-fido2.c [hunk 7]
```diff
@@ -243,20 +246,36 @@ int find_fido2_auto_data(
...
+                                rp,
+                                cid, cid_size,
+                                key_file, key_file_size, key_file_offset,
+                                salt, salt_size,
+                                until,
+                                headless,
+                                required,
+                                ret_decrypted_key, ret_decrypted_key_size,
+                                ask_password_flags);
+
```
Comment (poettering) [inline src/cryptsetup/cryptsetup-fido2.c]: please remove this empty line. we typically want to keep function calls and their immediate error handling/return code handling together.
