### PR TITLE
systemctl: skip checking inhibitors when dbus.service is not running

### LINKED ISSUE #35416: Regression: when dbus is not around, it's no more possible to restart or shutdown the system
### systemd version the issue has been seen with

257-rc3

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

The sequence:

```
systemctl rescue
systemctl poweroff
```

used to shutdown the system in rescue mode until v256

### Unexpected behaviour you saw

With v257-rc3:

```
$ systemctl rescue
$ systemctl poweroff
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → CLOSED
Failed to connect to system scope bus via local transport: No such file or directory
```

### Steps to reproduce the problem

See above.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug introduced by 804874d26ac73e0af07c4c5d7165c95372f03f6d.

Fixes #35416.

### CODE REVIEW

File: src/systemctl/systemctl-logind.c [hunk 1]
```diff
@@ -151,7 +151,9 @@ int logind_check_inhibitors(enum action a) {
         if (arg_transport != BUS_TRANSPORT_LOCAL)
                 return 0;
 
-        r = acquire_bus(BUS_FULL, &bus);
+        r = acquire_bus_full(BUS_FULL, /* graceful = */ true, &bus);
+        if (r == -ECONNREFUSED)
```
Comment (bluca) [inline src/systemctl/systemctl-logind.c]: This should also check uid == 0 to keep parity with the 256 behaviour. Also given we are past RC3, I'd much prefer if the fix for 257 was just the error check here, and the refactor was in a separate PR for 258

Comment (yuwata) [reply src/systemctl/systemctl-logind.c]: OK. Done. PTAL!

File: src/systemctl/systemctl-logind.c [hunk 2]
```diff
@@ -152,6 +152,8 @@ int logind_check_inhibitors(enum action a) {
                 return 0;
 
         r = acquire_bus(BUS_FULL, &bus);
+        if (r == -ECONNREFUSED && geteuid() == 0)
+                return 0; /* dbus.service seems not running. */
```
Comment (bluca) [inline src/systemctl/systemctl-logind.c]: Maybe a more explicit comment such as: `When D-Bus is not running, allow root to force a shutdown. E.g.: when running at the emergency console."

**Review by bluca — APPROVED** [review]
