### PR TITLE
journalctl: expunge verification key from argv

### LINKED ISSUE #4135: FSS private part leak when ran using sudo
### Submission type
- [ ] Bug report
- [x ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Archlinux
### In case of bug report: Expected behaviour you didn't see

> NA
### In case of bug report: Unexpected behaviour you saw

> NA
### In case of bug report: Steps to reproduce the problem

> NA

When the verification command is run using sudo, a log entry like below is generated by default leaking the private key.
Sep 13 14:25:05 HOST_HERE sudo[28510]:    hi117 : TTY=pts/1 ; PWD=/home/hi117 ; USER=root ; COMMAND=/usr/bin/journalctl --verify --verify-key PRIVATE_KEY_HERE
This log entry cannot be removed because FSS is in place, preventing modification of the logs. A documentation entry should be added noting this and a new flag allowing for interactive input of the private key part should be added to prevent this issue.

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
After parsing the `--verify-key` argument, overwrite it with null bytes. This minimizes (but does not completely eliminate) the time frame within which another process on the system can extract the verification key from the `journalctl` command line.

---

Note that this does not fix #4135 (nor the problem of accidentally recording the verification key in the shell history file, which I would guess to also happen occasionally), and the new flag requested in that issue is still called for IMO.

I *think* this is safe to do. ISO C11 ([ISO/IEC 9899:201x](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf)) says in 5.1.2.2.1, number 2, last dash, that “the strings pointed to by the `argv` array shall be modifiable by the program”, and `getopt(3)` says that the function “places a pointer to the following text in the same `argv`-element, or the text of the following `argv`-element, in optarg”, so the `optarg` pointer ought to be modifiable without segfault. Nevertheless, review by someone better versed in C than me would be a good idea.

The `strdup` introduces a small memory leak. Do you think it’s significant? Should I try to fix it? (I haven’t yet looked at where `arg_verify_key` is used, if it would be easy to `free` or not.)

Also, the *length* of the verification key is still leaked, but I don’t think there’s any information in there that is not already known. As far as I can tell from `setup_keys`, the verification key seems to consist of:

- the seed – length already known as compile-time constant;
- `n`, the setup wall time divided by interval – value already known since setup wall time (`n * arg_interval`) is stored in FSS header; and
- the interval – value already known, stored in FSS header.

### CODE REVIEW

File: src/journal/journalctl.c [hunk 1]
```diff
@@ -683,8 +683,9 @@ static int parse_argv(int argc, char *argv[]) {
 
                 case ARG_VERIFY_KEY:
                         arg_action = ACTION_VERIFY;
-                        arg_verify_key = optarg;
+                        arg_verify_key = strdup(optarg);
                         arg_merge = false;
+                        memset(optarg, 0, strlen(arg_verify_key));
```
Comment (keszybz) [inline src/journal/journalctl.c]: Please use `string_erase` instead.

File: src/journal/journalctl.c [hunk 2]
```diff
@@ -683,8 +683,9 @@ static int parse_argv(int argc, char *argv[]) {
 
                 case ARG_VERIFY_KEY:
                         arg_action = ACTION_VERIFY;
-                        arg_verify_key = optarg;
+                        arg_verify_key = strdup(optarg);
```
Comment (keszybz) [inline src/journal/journalctl.c:686]: oom check is necessary.

Please also put
  `free(arg_verify_key)`
at end of `main`.

Comment (lucaswerkmeister) [reply src/journal/journalctl.c:686]: > oom check is necessary.

And in case of OOM, die or just use `optarg` as `arg_verify_key` without expunging it? As you say, it’s snake oil, we *could* just proceed…

File: src/journal/journalctl.c (hunk 1 above)
Comment (lucaswerkmeister) [reply src/journal/journalctl.c]: Nice, I didn’t know about that function.

File: src/journal/journalctl.c (hunk 2 above)
Comment (keszybz) [reply src/journal/journalctl.c:686]: Fail. It doesn't matter really, and that's what we do elsewhere in the codebase.

**Comment by lucaswerkmeister** [comment]
Updated. I’ve also removed the `const` modifier from `arg_verify_key`’s declaration, since it seems to be incorrect now. (My understanding of `const` is fuzzy, but with it there was a compiler warning on `free`.)

EDIT: Damn, completely forgot about OOM, please hang on for a second

**Comment by lucaswerkmeister** [comment]
Okay, added OOM, sorry again.

**Comment by keszybz** [comment]
> I’ve also removed the const modifier from arg_verify_key’s declaration, since it seems to be incorrect now. (My understanding of const is fuzzy, but with it there was a compiler warning on free.)

`const` type means that the memory area cannot be modified. Both overwriting the memory or freeing it are such modifications.

File: src/journal/journalctl.c (hunk 1 above)
Comment (lucaswerkmeister) [reply src/journal/journalctl.c]: Grr, I just noticed that the commit message (“overwrite it with null bytes”) no longer applies with this change… too late to change it now
