### PR TITLE
sd-dhcp6-client: ignore IAs which do not match IAID

### LINKED ISSUE #20803: DHCPv6 too strict when the response is missing IAID for some sections
**systemd version the issue has been seen with**
 > systemd 248 (248.3-1ubuntu3)

**Used distribution**
 > Ubuntu 21.10 (Impish Indri)

**Linux kernel version used** (`uname -a`)
 > `Linux ip-172-31-211-65 5.11.0-1015-aws #16+21.10.1-Ubuntu SMP Mon Jul 26 13:47:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > IPv6 address acquired

**Unexpected behaviour you saw**
 > IPv6 address was not acquired due to issues parsing the DHCPv6 Advertise message:
```
systemd-networkd[19265]: DHCPv6 CLIENT: Sent SOLICIT
systemd-networkd[19265]: DHCPv6 CLIENT: Next retransmission in 29s
systemd-networkd[19265]: DHCPv6 CLIENT: ADVERTISE has wrong IAID for IA PD
systemd-networkd[19265]: DHCPv6 CLIENT: Recv ADVERTISE
```
> The DHCPv6 message is expected to have the same IAID in all the sections:
https://github.com/systemd/systemd/blob/8d71f2b3a6c9ef26a3a39fcaa4281776e9420976/src/libsystemd-network/sd-dhcp6-client.c#L1247-L1251

**Steps to reproduce the problem**
> To reproduce this problem, an AWS setup with IPv6 enabled is required.
> Create a VPC and assign an IPv6 CIDR. Assign IPv6 CIDR to a subnet and start an instance with an IPv6 address assigned.
> Once the instance is up and running, assign and IPv6 Prefix to the network interface.
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-prefix-eni.html
> The instance will fail or acquire or renew the lease for the IPv6 address.
>
> As you can see below, the main issue is the missing IAID for the IAPD section.
> I could not find any reference in the RFC about the possibility of not setting the IAID in all sections of the message, so seems to be something that AWS should fix at some point.
> That being said, the parsing of the message is also too strict. The sections with valid IAID, like the IANA should be processed and the DHCPv6 lease acquired or renewed.

**Additional program output to the terminal or log subsystem illustrating the issue**

> The DHCPv6 Advertise message as parsed with tshark:
```
> sudo tshark -V -i ens5 -d "udp.port==546:2,dhcpv6" -f "udp port 546 or udp port 547"

DHCPv6
    Message type: Advertise (2)
    Transaction ID: 0x88b74a
    Client Identifier
        Option: Client Identifier (1)
        Length: 14
        DUID: 00020000ab115b2000709a2178c4
        DUID Type: assigned by vendor based on Enterprise number (2)
        Enterprise ID: Tom Gundersen (systemd) (43793)
        Identifier: 5b2000709a2178c4
    Server Identifier
        Option: Server Identifier (2)
        Length: 10
        DUID: 000300010265476d3310
        DUID Type: link-layer address (3)
        Hardware type: Ethernet (1)
        Link-layer address: 02:65:47:6d:33:10
    Preference
        Option: Preference (7)
        Length: 1
        Pref-value: 255
    Identity Association for Non-temporary Address
        Option: Identity Association for Non-temporary Address (3)
        Length: 40
        IAID: ed10bdb8
        T1: 70
        T2: 112
        IA Address
            Option: IA Address (5)
            Length: 24
            IPv6 address: 2a05:d014:aa7:911:dfeb:bd5a:5115:7bef
            Preferred lifetime: 140
            Valid lifetime: 450
    Identity Association for Prefix Delegation
        Option: Identity Association for Prefix Delegation (25)
        Length: 41
        IAID: 00000000
        T1: 70
        T2: 112
        IA Prefix
            Option: IA Prefix (26)
            Length: 25
            Preferred lifetime: 140
            Valid lifetime: 450
            Prefix length: 80
            Prefix address: 2a05:d014:aa7:911:4393::
```

### PR DESCRIPTION
**Pull request by yuwata**
But do not refuse whole message.

Fixes #20803.

### CODE REVIEW

File: src/libsystemd-network/dhcp6-option.c [hunk 1]
```diff
@@ -529,6 +529,9 @@ int dhcp6_option_parse_ia(sd_dhcp6_client *client, DHCP6Option *iaoption, DHCP6I
                 if (len < DHCP6_OPTION_IA_NA_LEN)
                         return -ENOBUFS;
 
+                if (((const struct ia_na*) iaoption->data)->id != iaid)
```
Comment (bluca) [inline src/libsystemd-network/dhcp6-option.c:540]: It would be nice to add a comment here mentioning RFC8415 I think, for future readers

**Review by bluca — APPROVED** [review]
Just one minor request, LGTM

**Comment by yuwata** [comment]
@bluca Thank you for your review. A brief comment for the fix is added. Upgrading the green label.

File: src/libsystemd-network/dhcp6-option.c [hunk 2]
```diff
@@ -564,13 +580,18 @@ int dhcp6_option_parse_ia(sd_dhcp6_client *client, DHCP6Option *iaoption, DHCP6I
                 if (len < DHCP6_OPTION_IA_TA_LEN)
                         return -ENOBUFS;
 
+                /* According to RFC8415, IAs which do not match the client's IAID should be ignored,
+                 * but not necessary to ignore or refuse the whole message. */
+                if (((const struct ia_ta*) iaoption->data)->id != iaid)
+                        return -ENOMSG; /* Indicate the option should be ignored. */
```
Comment (hakman) [inline src/libsystemd-network/dhcp6-option.c]: Maybe this deserves a debug message also, so that people with misconfigured environments get some feedback like before.

Comment (yuwata) [reply src/libsystemd-network/dhcp6-option.c]: Thank you for the suggestion. A debug message is added.

File: src/libsystemd-network/dhcp6-option.c [hunk 3]
```diff
@@ -529,6 +535,14 @@ int dhcp6_option_parse_ia(sd_dhcp6_client *client, DHCP6Option *iaoption, DHCP6I
                 if (len < DHCP6_OPTION_IA_NA_LEN)
                         return -ENOBUFS;
 
+                /* According to RFC8415, IAs which do not match the client's IAID should be ignored,
+                 * but not necessary to ignore or refuse the whole message. */
+                if (((const struct ia_na*) iaoption->data)->id != iaid)
+                        /* ENOANO indicates the option should be ignored. */
+                        return log_dhcp6_client_errno(client, SYNTHETIC_ERRNO(ENOANO),
+                                                      "Received IA_NA option whose IAID is different "
+                                                      "from the one choosed by the client, ignoring.");
```
Comment (bluca) [inline src/libsystemd-network/dhcp6-option.c]: "Received an IA_NA option with a different IAID "

/choosed/chosen/

File: src/libsystemd-network/dhcp6-option.c (hunk 2 above)
Comment (hakman) [reply src/libsystemd-network/dhcp6-option.c]: Thanks :)

File: src/libsystemd-network/dhcp6-option.c (hunk 3 above)
Comment (yuwata) [reply src/libsystemd-network/dhcp6-option.c]: Ouch. Fixed. Thank you!
