### PR TITLE
network: try to bring down interface before setting MAC address

### LINKED ISSUE #6696: RFE: networkd: possibly down interface when networkd is restarted and .network configures a different MAC address than is previously set, so that the MAC address can actually be changed
### Submission type

 - Bug report

### systemd version the issue has been seen with
232

### In case of bug report: Expected behaviour you didn't see

Here is the configuration of the network file
====================================
cat /etc/systemd/network/00-xyz-eth0.network
[Match]
Name=eth0
[Link]
MACAddress=70:E2:84:14:20:45 
[Network]
Address=10.10.10.4/24
Gateway=10.10.10.1

Configuration of link file
====================
cat /etc/systemd/network/00-xyz-eth0.link
[Match]
MACAddress=60:E2:84:14:20:45

[Link]
MACAddress=70:E2:84:14:20:45

Before systemd-networkd  restart
==========================
ip link show
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 60:e2:84:14:20:45 brd ff:ff:ff:ff:ff:ff 

After Systemd-networkd restart
systemctl restart systemd-networkd.service

ip link show
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 60:e2:84:14:20:45 brd ff:ff:ff:ff:ff:ff 

### In case of bug report: Unexpected behaviour you saw

The mac address is not changed,expected output I thought it should be 70:E2:84:14:20:45

### In case of bug report: Steps to reproduce the problem

Given above.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #6696.

### CODE REVIEW

File: src/network/networkd-setlink.c [hunk 1]
```diff
@@ -680,6 +680,15 @@ int link_request_to_set_mac(Link *link) {
         if (!link->network->mac)
                 return 0;
 
+        if (link->hw_addr.length != sizeof(struct ether_addr)) {
+                log_link_debug(link, "Size of hardware address (%zu) does not match the size of MAC address (%zu), ignoring.",
+                               link->hw_addr.length, sizeof(struct ether_addr));
+                return 0;
+        }
```
Comment (poettering) [inline src/network/networkd-setlink.c:732]: hmm, so this means the code will only ever set the hw address of ethernet? isn't this a useful feature for other transports, too? infiniband and such, which have longer hw addresses?

File: src/network/networkd-setlink.c [hunk 2]
```diff
@@ -483,6 +515,15 @@ static bool link_is_ready_to_call_set_link(Request *req) {
                         }
                 }
                 break;
+        case SET_LINK_MAC:
+                if (PTR_TO_INT(req->userdata)) {
```
Comment (poettering) [inline src/network/networkd-setlink.c]: maybe add a comment here, what this is about. The variable name doesn't tell us anything after all...

File: src/network/networkd-setlink.c [hunk 3]
```diff
@@ -689,7 +733,15 @@ int link_request_to_set_mac(Link *link) {
...
 
-        return link_request_set_link(link, SET_LINK_MAC, link_set_mac_handler, NULL);
+        r = link_request_set_link(link, SET_LINK_MAC,
+                                  allow_retry ? link_set_mac_allow_retry_handler : link_set_mac_handler,
+                                  &req);
+        if (r < 0)
+                return r;
+
+        /* This indicates whether we should bring down the interface or not before setting MAC address. */
+        req->userdata = INT_TO_PTR(!allow_retry);
```
Comment (poettering) [inline src/network/networkd-setlink.c]: hmm, do you actually need to set the userdata here? You could also just compare the handler installed for this `Request` with the pointers to link_set_mac_allow_retry_handler(), right?

i think that would be a bit nicer maybe, since userdata is so opaque

File: src/network/networkd-setlink.c (hunk 1 above)
Comment (yuwata) [reply src/network/networkd-setlink.c:732]: I do not have and am not familiar with infiniband or device with longer hw addreses. But, at least, the current logic does not support such devices. Maybe, we should rename `MACAddress=` -> `HardwareAddress=` and support address with an arbitrary length.

Let's do that when people request to support such hw.

**Comment by yuwata** [comment]
@poettering Thank you for the comments. Now, the assignment to `req->userdata` is dropped, and also added a brief comment around `link_down()`. PTAL.

File: src/network/networkd-setlink.c (hunk 1 above)
Comment (poettering) [reply src/network/networkd-setlink.c:732]: ok. but maybe add a comment explaining this. i.e. a `/* Note that for now we only support changing hardware addresses on Ethernet. */` or so would probably suffice, next to the check

File: src/network/networkd-setlink.c [hunk 4]
```diff
@@ -483,6 +515,17 @@ static bool link_is_ready_to_call_set_link(Request *req) {
                         }
                 }
                 break;
+        case SET_LINK_MAC:
+                if (req->netlink_handler == link_set_mac_handler) {
+                        /* This is the second trial to set MTU. Maybe, the first trial failed as the
+                         * interface was up. */
```
Comment (poettering) [inline src/network/networkd-setlink.c]: maybe explicitly say here `On the first attempt req->netlink_handler points to link_set_mac_allow_retry_handler()`, just to make clear why this check works

**Comment by poettering** [comment]
lgtm, but the two comments I suggested would be great to have

**Comment by yuwata** [comment]
@poettering Thanks. The suggested comments are added. Upgrading the green label.
