### PR TITLE
Fix printing of circular dependencies

### LINKED ISSUE #26052: systemctl: list-dependencies: tree structure with `--all` is in disorder if it hits loop dependencies
### systemd version the issue has been seen with

Current HEAD (d59ce37c280bb1bcd8787c2b77b54d8fe69bf8d2)

### Used distribution

Arch Linux

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

systemctl

### Expected behaviour you didn't see

The tree structure is complete.

### Unexpected behaviour you saw

screenshot

### Steps to reproduce the problem

Use `systemctl list-dependencies --all` on a unit that has dependency loops.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ systemctl list-dependencies --all dbus.service

dbus.service
● ├─-.mount
● │ └─-.slice
● ├─dbus.socket
● │ ├─-.mount
● │ │ └─-.slice
● │ ├─system.slice
● │ │ └─-.slice
● │ └─sysinit.target
● │   ├─dev-hugepages.mount
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ └─-.slice
● │   ├─dev-mqueue.mount
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ └─-.slice
● │   ├─kmod-static-nodes.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─ldconfig.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─lvm2-lvmpolld.socket
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ └─system.slice
● │   │   └─-.slice
○ │   ├─lvm2-monitor.service
● │   ├─proc-sys-fs-binfmt_misc.automount
● │   │ └─-.mount
● │   │   └─-.slice
● │   ├─sys-fs-fuse-connections.mount
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ ├─-.slice
○ │   │ └─modprobe@fuse.service
● │   │   └─system-modprobe.slice
● │   │     └─system.slice
● │   │       └─-.slice
● │   ├─sys-kernel-config.mount
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ ├─-.slice
○ │   │ └─modprobe@configfs.service
● │   │   └─system-modprobe.slice
● │   │     └─system.slice
● │   │       └─-.slice
● │   ├─sys-kernel-debug.mount
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ └─-.slice
● │   ├─sys-kernel-tracing.mount
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ └─-.slice
● │   ├─systemd-ask-password-console.path
● │   │ └─-.mount
● │   │   └─-.slice
○ │   ├─systemd-binfmt.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─systemd-boot-system-token.service
● │   │ └─system.slice
● │   │   └─-.slice
○ │   ├─systemd-firstboot.service
● │   │ ├─system.slice
● │   │ │ └─-.slice
○ │   │ └─first-boot-complete.target
○ │   ├─systemd-hwdb-update.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─systemd-journal-catalog-update.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─systemd-journal-flush.service
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ ├─system.slice
● │   │ │ └─-.slice
● │   │ └─systemd-journald.service
● │   │   ├─-.mount
● │   │   │ └─-.slice
● │   │   ├─system.slice
● │   │   │ └─-.slice
● │   │   ├─systemd-journald-audit.socket
● │   │   │ └─system.slice
● │   │   │   └─-.slice
● │   │   ├─systemd-journald-dev-log.socket
● │   │   │ ├─-.mount
● │   │   │ │ └─-.slice
● │   │   │ └─system.slice
● │   │   │   └─-.slice
● │   │   └─systemd-journald.socket
● │   │     ├─-.mount
● │   │     │ └─-.slice
● │   │     └─system.slice
● │   │       └─-.slice
● │   ├─systemd-journald.service
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ ├─system.slice
● │   │ │ └─-.slice
● │   │ ├─systemd-journald-audit.socket
● │   │ │ └─system.slice
● │   │ │   └─-.slice
● │   │ ├─systemd-journald-dev-log.socket
● │   │ │ ├─-.mount
● │   │ │ │ └─-.slice
● │   │ │ └─system.slice
● │   │ │   └─-.slice
● │   │ └─systemd-journald.socket
● │   │   ├─-.mount
● │   │   │ └─-.slice
● │   │   └─system.slice
● │   │     └─-.slice
○ │   ├─systemd-machine-id-commit.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─systemd-modules-load.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─systemd-network-generator.service
● │   │ ├─system.slice
● │   │ │ └─-.slice
● │   │ └─network-pre.target
● │   ├─systemd-pcrphase-sysinit.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─systemd-pcrphase.service
● │   │ ├─system.slice
● │   │ │ └─-.slice
  │   │   └─...
● │   ├─systemd-random-seed.service
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ ├─system.slice
● │   │ │ └─-.slice
○ │   │ └─first-boot-complete.target
○ │   ├─systemd-repart.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─systemd-sysctl.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─systemd-sysusers.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─systemd-timesyncd.service
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ ├─system.slice
● │   │ │ └─-.slice
● │   │ ├─tmp.mount
● │   │ │ ├─-.mount
● │   │ │ │ └─-.slice
● │   │ │ └─system.slice
● │   │ │   └─-.slice
● │   │ └─time-set.target
● │   ├─systemd-tmpfiles-setup-dev.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─systemd-tmpfiles-setup.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─systemd-udev-trigger.service
● │   │ ├─system.slice
● │   │ │ └─-.slice
● │   │ └─systemd-udevd.service
● │   │   ├─system.slice
● │   │   │ └─-.slice
● │   │   ├─systemd-udevd-control.socket
● │   │   │ ├─-.mount
● │   │   │ │ └─-.slice
● │   │   │ └─system.slice
● │   │   │   └─-.slice
● │   │   └─systemd-udevd-kernel.socket
● │   │     └─system.slice
● │   │       └─-.slice
● │   ├─systemd-udevd.service
● │   │ ├─system.slice
● │   │ │ └─-.slice
● │   │ ├─systemd-udevd-control.socket
● │   │ │ ├─-.mount
● │   │ │ │ └─-.slice
● │   │ │ └─system.slice
● │   │ │   └─-.slice
● │   │ └─systemd-udevd-kernel.socket
● │   │   └─system.slice
● │   │     └─-.slice
● │   ├─systemd-update-done.service
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─systemd-update-utmp.service
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ └─system.slice
● │   │   └─-.slice
● │   ├─cryptsetup.target
● │   ├─integritysetup.target
● │   ├─local-fs.target
● │   │ ├─-.mount
● │   │ │ └─-.slice
● │   │ ├─efi.mount
● │   │ │ ├─-.mount
● │   │ │ │ └─-.slice
● │   │ │ ├─dev-nvme0n1p1.device
● │   │ │ ├─system.slice
● │   │ │ │ └─-.slice
● │   │ │ └─systemd-fsck@dev-disk-by\x2duuid-0156\x2dCC11.service
● │   │ │   ├─dev-disk-by\x2duuid-0156\x2dCC11.device
● │   │ │   └─system-systemd\x2dfsck.slice
● │   │ │     └─system.slice
● │   │ │       └─-.slice
● │   │ ├─home-yhndnzj-Downloads.mount
● │   │ │ ├─-.mount
● │   │ │ │ └─-.slice
● │   │ │ └─system.slice
● │   │ │   └─-.slice
● │   │ ├─systemd-fsck-root.service
● │   │ │ └─system.slice
● │   │ │   └─-.slice
● │   │ ├─systemd-remount-fs.service
● │   │ │ ├─system.slice
● │   │ │ │ └─-.slice
● │   │ │ └─local-fs-pre.target
● │   │ └─tmp.mount
● │   │   ├─-.mount
● │   │   │ └─-.slice
● │   │   └─system.slice
● │   │     └─-.slice
● │   ├─swap.target
● │   │ └─swapfile.swap
● │   │   ├─-.mount
● │   │   │ └─-.slice
● │   │   └─system.slice
● │   │     └─-.slice
● │   └─veritysetup.target
● ├─system.slice
● │ └─-.slice
● └─tmp.mount
●   ├─-.mount
●   │ └─-.slice
●   └─system.slice
●     └─-.slice
```

### PR DESCRIPTION
**Pull request by dtardon**
Fixes #26052.

### CODE REVIEW

File: src/systemctl/systemctl-list-dependencies.c [hunk 1]
```diff
@@ -146,7 +146,7 @@ static int list_dependencies_one(
 
         if (circular && !arg_plain) {
                 printf("  ");
-                r = list_dependencies_print("...", level, branches, /* last = */ true);
+                r = list_dependencies_print("...", _UNIT_ACTIVE_STATE_INVALID, level, branches, /* last = */ true);
```
Comment (keszybz) [inline src/systemctl/systemctl-list-dependencies.c:148]: This will now be printed in red. On purpose?

Comment (dtardon) [reply src/systemctl/systemctl-list-dependencies.c:148]: It won't. This is covered by
```c
if (arg_plain || state == _UNIT_ACTIVE_STATE_INVALID)
        printf("  ");
```
in `list_dependencies_print`.

Comment (keszybz) [reply src/systemctl/systemctl-list-dependencies.c:148]: Ah, OK.
