### PR TITLE
network: reconfigure interface when renamed

### LINKED ISSUE #24975: networkd waits for interface to be renamed forever
### systemd version the issue has been seen with

251.3-1~bpo11+1

### Used distribution

Debian Bullseye

### Linux kernel version used

5.10.0-13

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

A renamed network interface is configured by networkd.

Output of `networkctl`:
```sh
IDX LINK     TYPE     OPERATIONAL SETUP
...
  3 kli      ether    routable    configured
```

### Unexpected behaviour you saw

A renamed network interface is **not** configured by networkd.

Output of `networkctl`:
```sh
IDX LINK     TYPE     OPERATIONAL SETUP
...
  3 kli      ether    off         unmanaged
...
```

### Steps to reproduce the problem

```service
# /etc/systemd/network/02_customboard_kli.link
[Match]
OriginalName=enp4s0
KernelCommandLine=systemd.setenv=BOARD_NAME=CustomBoard

[Link]
Name=kli
WakeOnLan=magic
```

```service
# /etc/systemd/network/kli.network
[Match]
Name=kli

[Network]
VLAN=kli_it
DHCP=ipv4

LinkLocalAddressing=no
IPv6AcceptRA=no

[DHCPv4]
ClientIdentifier=mac
```

Restart as long as the network interface is not configured anymore as expected

### Additional program output to the terminal or log subsystem illustrating the issue

https://gist.github.com/d4nuu8/0bcbaa2dbadcc44838fb70807d983709

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #24975.

(~~I will add testcases later.~~ Done.)

### CODE REVIEW

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -2064,33 +2066,57 @@ static int link_update_driver(Link *link, sd_netlink_message *message) {
...
                 return 0;
 
         /* When udevd is running, read the permanent hardware address after the interface is
          * initialized by udevd. Otherwise, ethtool may not work correctly. See issue #22538.
          * When udevd is not running, read the value when the interface is detected. */
-        if (link->state != (udev_available() ? LINK_STATE_INITIALIZED : LINK_STATE_PENDING))
+        if (udev_available() && !link->dev)
+                return 0;
+
+        /* If the interface does not have a hardware address, then neither for permanent address. */
```
Comment (bluca) [inline src/network/networkd-link.c]: did you mean "then it will not have a permanent address either"?

**Review by bluca — APPROVED** [review]
