### PR TITLE
analyze: introduce --instance= option to control instance name for template units

### LINKED ISSUE #33681: `systemd-analyze verify` doesn't handle template units properly
### systemd version the issue has been seen with

256.1

### Used distribution

NixOS 24.11pre

### Linux kernel version used

6.6.36

### CPU architectures issue was seen on

aarch64

### Component

systemd-analyze

### Expected behaviour you didn't see

`systemd-analyze verify` shouldn't fail verifying `systemd-growfs@.service`

### Unexpected behaviour you saw

```
$ systemd-analyze verify  /usr/lib/systemd/system/systemd-growfs@.service 
systemd-growfs@i.service: Failed to create systemd-growfs@i.service/start: Unit i.mount not found.
```

Note that it does work if you fill in the template:

```
$ systemd-analyze verify  /etc/systemd/system/systemd-growfs@-.service
```

### Steps to reproduce the problem

```
#  SPDX-License-Identifier: LGPL-2.1-or-later
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Grow File System on %f
Documentation=man:systemd-growfs@.service(8)

DefaultDependencies=no
BindsTo=%i.mount
After=systemd-repart.service %i.mount
Conflicts=shutdown.target
```

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Closes #33681.

### CODE REVIEW

File: src/analyze/analyze-verify-util.c [hunk 1]
```diff
@@ -55,7 +56,7 @@ int verify_prepare_filename(const char *filename, char **ret) {
                 return -EINVAL;
 
         if (unit_name_is_valid(name, UNIT_NAME_TEMPLATE)) {
-                r = unit_name_replace_instance(name, "i", &with_instance);
+                r = unit_name_replace_instance(name, arg_instance, &with_instance);
```
Comment (YHNdnzj) [inline src/analyze/analyze-verify-util.c:59]: Hmm, I don't grok this? Why not just specify instance in unit id? I think the solution is to give a hint that some units might have restrictions on instance name, but no more?

Comment (yuwata) [reply src/analyze/analyze-verify-util.c:59]: Of course, `systemd-analyze verify systemd-growfs@.service --instance=tmp` and `systemd-analyze verify systemd-growfs@tmp.service` are equivalent.

But, `--instance` may be useful for passing multiple units in a directory. E.g.
```
systemd-analyze verify /usr/lib/systemd/system/*.service --instance=hoge
```
Otherwise, users need to append instance name to each service name.

Comment (YHNdnzj) [reply src/analyze/analyze-verify-util.c:59]: Probably. Though I doubt that people really want to inspect so many units at once.

But apart from that, this means that the PR doesn't (intend to) resolve #33681, no?

Comment (yuwata) [reply src/analyze/analyze-verify-util.c:59]: > Probably. Though I doubt that people really want to inspect so many units at once.

Not necessary so many, just multiple.

> But apart from that, this means that the PR doesn't (intend to) resolve #33681, no?

Maybe Closes -> Inspired by or Prompted by.

Comment (YHNdnzj) [reply src/analyze/analyze-verify-util.c:59]: Hmm, rethinking about this, maybe `test_instance` can serve as the hint well enough.

File: src/analyze/analyze.c [hunk 2]
```diff
@@ -272,6 +273,7 @@ static int help(int argc, char *argv[], void *userdata) {
                "     --man[=BOOL]            Do [not] check for existence of man pages\n"
                "     --generators[=BOOL]     Do [not] run unit generators\n"
                "                             (requires privileges)\n"
+               "     --instance=NAME         Specifies instance name for template units\n"
```
Comment (YHNdnzj) [inline src/analyze/analyze.c]:
```suggestion
               "     --instance=NAME         Specify fallback instance name for template units\n"
```

**Review by YHNdnzj — APPROVED** [review]

File: src/analyze/analyze-verify-util.c (hunk 1 above)
Comment (yuwata) [reply src/analyze/analyze-verify-util.c:59]: Commit message and man page are extended.

File: src/analyze/analyze.c [hunk 3]
```diff
@@ -102,6 +102,7 @@ RuntimeScope arg_runtime_scope = RUNTIME_SCOPE_SYSTEM;
 RecursiveErrors arg_recursive_errors = _RECURSIVE_ERRORS_INVALID;
 bool arg_man = true;
 bool arg_generators = false;
+const char *arg_instance = "test_instance";
```
Comment (poettering) [inline src/analyze/analyze.c:105]: btw, for new code i'd always use strdup() memory for such arg_xyz strings, rather than point directly into argv[]. That's because we nowadays change argv[] in rename_process() at so many places, for example in safe_fork(), which unexpectedly then changes these strings. Hence, given we only duplicate a very small number of strings when parsing command lines, i#d always strdup() this, just to avoid confusion later on (because it is *very* confusing, if various arg_* strings become invalid after safe_fork())

Comment (yuwata) [reply src/analyze/analyze.c:105]: OK. Maybe better to update CODING_STYLE?
