### PR TITLE
resolved: fix use-after-free with queries hitting the cache

### LINKED ISSUE #16168: resolved is randomly crashing (hashmap_iterate_entry())
Hello,

On debian unstable, with systemd 245.6-1, resolved crashed multiple times with the following trace:

```
           PID: 338706 (systemd-resolve)
           UID: 102 (systemd-resolve)
           GID: 104 (systemd-resolve)
        Signal: 11 (SEGV)
     Timestamp: Sat 2020-06-13 08:07:53 CEST (20min ago)
  Command Line: /lib/systemd/systemd-resolved
    Executable: /usr/lib/systemd/systemd-resolved
 Control Group: /system.slice/systemd-resolved.service
          Unit: systemd-resolved.service
         Slice: system.slice
       Boot ID: 73d56b833b174db5814a013cf44aaf57
    Machine ID: eb71526a9be548c2806ab24bb024fb1f
      Hostname: edoras
       Storage: /var/lib/systemd/coredump/core.systemd-resolve.102.73d56b833b174db5814a013cf44aaf57.338706.1592028473000000000000.lz4
       Message: Process 338706 (systemd-resolve) of user 102 dumped core.
                
                Stack trace of thread 338706:
                #0  0x00007fdd53305b2a hashmap_iterate_entry (libsystemd-shared-245.so + 0x110b2a)
                #1  0x00007fdd53307a52 internal_hashmap_iterate (libsystemd-shared-245.so + 0x112a52)
                #2  0x000055c391b33b17 dns_query_candidate_go (systemd-resolved + 0x32b17)
                #3  0x000055c391b3312c dns_query_candidate_notify (systemd-resolved + 0x3212c)
                #4  0x000055c391b33388 dns_transaction_complete (systemd-resolved + 0x32388)
                #5  0x000055c391b2bccd dns_transaction_process_dnssec (systemd-resolved + 0x2accd)
                #6  0x000055c391b2cb2d dns_transaction_process_reply (systemd-resolved + 0x2bb2d)
                #7  0x000055c391b2d41b on_dns_packet (systemd-resolved + 0x2c41b)
                #8  0x00007fdd53279ac7 source_dispatch (libsystemd-shared-245.so + 0x84ac7)
                #9  0x00007fdd53279d61 sd_event_dispatch (libsystemd-shared-245.so + 0x84d61)
                #10 0x00007fdd5327b798 sd_event_run (libsystemd-shared-245.so + 0x86798)
                #11 0x00007fdd5327b9b7 sd_event_loop (libsystemd-shared-245.so + 0x869b7)
                #12 0x000055c391b0cb7a run (systemd-resolved + 0xbb7a)
                #13 0x00007fdd5347ee0b __libc_start_main (libc.so.6 + 0x26e0b)
                #14 0x000055c391b0d4ca _start (systemd-resolved + 0xc4ca)
```

In dmesg, I can see: `[605459.479558] traps: systemd-resolve[338706] general protection fault ip:7fdd53305b2a sp:7fff14895a10 error:0 in libsystemd-shared-245.so[7fdd53245000+170000]`

### PR DESCRIPTION
**Pull request by keszybz**
When dns_transaction_complete() manages to resolve a query, it invalidates the
query candidate object. It shall not be accessed afterwards.

We have the following chain of calls:
dns_query_candidate_go → dns_transaction_go → dns_transaction_prepare → dns_cache_lookup (success: 1)
                                                                      → dns_transaction_complete
After returning back to dns_query_candidate_go(), we'd attempt to continue
iteration over the list of transactions attached to the query candidate,
accessing already freed (and overwritten) memory:

(gdb) bt
0  0x00007f637297cf47 in hashmap_iterate_entry (i=0x7ffe7e15cc90, h=0x706f746b73656465) at ../src/basic/hashmap.c:703
1  _hashmap_iterate (h=0x706f746b73656465, i=i@entry=0x7ffe7e15cc90, value=value@entry=0x7ffe7e15cc88,
    key=key@entry=0x0) at ../src/basic/hashmap.c:712
2  0x00007f637297d01b in set_iterate (s=<optimized out>, i=i@entry=0x7ffe7e15cc90, value=value@entry=0x7ffe7e15cc88)
    at ../src/basic/hashmap.c:733
hence we crash

3  0x0000557bc99eb80f in dns_query_candidate_go (c=c@entry=0x557bcaf86890) at ../src/resolve/resolved-dns-query.c:139
...but c is not valid here in the second iteration of the loop

4  0x0000557bc99eb720 in dns_query_candidate_notify (c=0x557bcaf86890) at ../src/resolve/resolved-dns-query.c:271
c was valid here at entry...

5  0x0000557bc99efe28 in dns_transaction_complete (t=0x557bcac072f0, state=<optimized out>)
    at ../src/resolve/resolved-dns-transaction.c:350
t is a valid transaction (11481 in the backtrace below)

6  0x0000557bc99f1efb in dns_transaction_process_reply (t=0x557bcac072f0, p=<optimized out>)
    at ../src/resolve/resolved-dns-transaction.c:1171
7  0x0000557bc99f2d41 in on_dns_packet (s=<optimized out>, fd=<optimized out>, revents=<optimized out>,
    userdata=0x557bcac072f0) at ../src/resolve/resolved-dns-transaction.c:1223
8  0x00007f6372a25217 in source_dispatch (s=s@entry=0x557bcb162c50) at ../src/libsystemd/sd-event/sd-event.c:3181
9  0x00007f6372a254fd in sd_event_dispatch (e=0x557bcb15b050) at ../src/libsystemd/sd-event/sd-event.c:3620
10 0x00007f6372a267c8 in sd_event_run (e=e@entry=0x557bcb15b050, timeout=timeout@entry=18446744073709551615)
    at ../src/libsystemd/sd-event/sd-event.c:3678
11 0x00007f6372a269ef in sd_event_loop (e=0x557bcb15b050) at ../src/libsystemd/sd-event/sd-event.c:3700
12 0x0000557bc99ddc14 in run (argc=<optimized out>, argv=<optimized out>) at ../src/resolve/resolved.c:92
13 0x0000557bc99d260a in main (argc=<optimized out>, argv=<optimized out>) at ../src/resolve/resolved.c:99

silver.batkin.net systemd-resolved[31705]: Got message type=method_call sender=:1.3644 destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveHostname cookie=2 reply_cookie=0 signature=isit error-name=n/a error-message=n/a
silver.batkin.net systemd-resolved[31705]: idn2_lookup_u8: silver → silver
silver.batkin.net systemd-resolved[31705]: Looking up RR for silver IN A.
silver.batkin.net systemd-resolved[31705]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=1102 reply_cookie=0 signature=s error-name=n/a error-message=n/a
silver.batkin.net systemd-resolved[31705]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=1103 reply_cookie=0 signature=s error-name=n/a error-message=n/a
silver.batkin.net systemd-resolved[31705]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.3324 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=1103 signature=s error-name=n/a error-message=n/a
silver.batkin.net systemd-resolved[31705]: Cache miss for silver.batkin.net IN A
silver.batkin.net systemd-resolved[31705]: Transaction 11481 for <silver.batkin.net IN A> scope dns on enp42s0/*.
silver.batkin.net systemd-resolved[31705]: Using feature level UDP for transaction 11481.
silver.batkin.net systemd-resolved[31705]: Using DNS server 192.168.1.1 for transaction 11481.
silver.batkin.net systemd-resolved[31705]: Sending query packet with id 11481 of size 35.
silver.batkin.net systemd-resolved[31705]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.3324 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=1102 signature= error-name=n/a error-message=n/a
silver.batkin.net systemd-resolved[31705]: Match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.3644' successfully installed.
silver.batkin.net systemd-resolved[31705]: Processing incoming packet on transaction 11481 (rcode=NXDOMAIN).
silver.batkin.net systemd-resolved[31705]: Not caching negative entry without a SOA record: silver.batkin.net IN A
silver.batkin.net systemd-resolved[31705]: Transaction 11481 for <silver.batkin.net IN A> on scope dns on enp42s0/* now complete with <rcode-failure> from network (unsigned).
silver.batkin.net systemd-resolved[31705]: Positive cache hit for silver.lan IN A
silver.batkin.net systemd-resolved[31705]: Transaction 64364 for <silver.lan IN A> on scope dns on enp42s0/* now complete with <success> from cache (unsigned).
silver.batkin.net systemd-resolved[31705]: Sent message type=method_return sender=n/a destination=:1.3644 path=n/a interface=n/a member=n/a cookie=1104 reply_cookie=2 signature=a(iiay)st error-name=n/a error-message=n/a
silver.batkin.net systemd-resolved[31705]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=1105 reply_cookie=0 signature=s error-name=n/a error-message=n/a
silver.batkin.net systemd-resolved[31705]: Freeing transaction 64364.
silver.batkin.net systemd[1]: systemd-resolved.service: Main process exited, code=dumped, status=11/SEGV
silver.batkin.net systemd[1]: systemd-resolved.service: Failed with result 'core-dump'.

Fixes #16168, https://bugzilla.redhat.com/show_bug.cgi?id=1895937.

### CODE REVIEW

**Comment by ssahani** [comment]
Certainly complex bug to fix.

**Comment by keszybz** [comment]
@abatkin second version. Hopefully this one will be better. At least in my testing it doesn't "hang".

**Comment by abatkin** [comment]
[firefox-log.txt](https://github.com/systemd/systemd/files/5832128/firefox-log.txt)

Even stranger behavior:
* curl works
* I can't even launch firefox

Attached is `journalctl -f` after I flushed the resolved cache and ran "firefox" - the gap is where I was waiting (nothing happened, a window didn't even open) at which point I pressed `Ctrl+C` and those final lines appeared. I rebooted and tried again with the same result. After reinstalling the stock Fedora systemd I'm running again.

Note that I had to manually apply the patch, because the version I was basing on from Fedora was slightly different than systemd's master (where the PR is branched from) so the patch wouldn't apply cleanly. I guess this one of the challenges of a monolithic systemd with resolved being part of the systemd codebase - I'd be willing to compile/run resolved from master if that was possible, but not all of systemd, given how core it is to the whole OS.

File: src/resolve/resolved-dns-transaction.c [hunk 1]
```diff
@@ -1687,7 +1691,7 @@ int dns_transaction_go(DnsTransaction *t) {
                 t->state = DNS_TRANSACTION_PENDING;
 
                 log_debug("Delaying %s transaction for " USEC_FMT "us.", dns_protocol_to_string(t->scope->protocol), jitter);
-                return 0;
+                return 1;
```
Comment (poettering) [inline src/resolve/resolved-dns-transaction.c:1694]: yikes

**Comment by poettering** [comment]
Oh, man, thanks so much for tracking this down. And there even was the ready protection counter already in place, but not used wherever necessary!

Looks excellent, thanks!

**Comment by abatkin** [comment]
Wait, this was just merged? I'd love to be able to test systemd master on my system since I applied this to Fedora's SRPM of 246.7-2. But if the behavior of this PR on master vs applying this patch against Fedora's 246.7-2 is the same, then it results in an unusable system for me. Obviously there's some other issue going on and use-after-free is is bad, but at least today I have a system where 99% of my DNS lookups work and resolved only crashes occasionally with very little noticeable user impact.

**Comment by keszybz** [comment]
@abatkin @poettering only saw your comment after merging it. We're working on a fix for the fix ;)

(It shouldn't matter if this is for the v246 or master branch. The code didn't change significantly.)

**Comment by poettering** [comment]
yeah, sorry, i didn't see your commit. when you finish reviewing some PR in github it puts you at the review comment you just added, and thus I didn't see your comment because it was further up. I noticed quickly after merging though. sorry!

**Comment by keszybz** [comment]
```
Jan 18 14:34:18 silver.batkin.net systemd-resolved[829]: Transaction 45619 for <silver.batkin.net IN A> on scope dns on enp42s0/* now complete with <rcode-failure> from network (unsigned).
Jan 18 14:34:18 silver.batkin.net systemd-resolved[829]: Positive cache hit for silver.lan IN A
Jan 18 14:34:18 silver.batkin.net systemd-resolved[829]: Transaction 20073 for <silver.lan IN A> on scope dns on enp42s0/* now complete with <success> from cache (unsigned).
Jan 18 14:34:18 silver.batkin.net systemd-resolved[829]: Freeing transaction 45619.
-- ctrl+c
```
So the second transaction does not get finalized. It seems most likely that the part that does dns_query_candidate_notify() is somehow borked. I'll try to figure this out tomorrow ;)
