### PR TITLE
sd-bus: Return detailed (sd-buscntr) error from bus_container_connect_socket().

### LINKED ISSUE #17620: systemd-run fails with "Protocol error" when invoked with -M on a container that doesn't have dbus up yet
**systemd version the issue has been seen with**
 > 246

**Used distribution**
 > Arch

**Linux kernel version used** (`uname -a`)
 > Linux ARCH 5.9.8-arch1-1 #1 SMP PREEMPT Tue, 10 Nov 2020 22:44:11 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > To run `systemd-run` without error

**Unexpected behaviour you saw**
 > `systemd-run` fails with 
```
Failed to create bus connection: Protocol error
```

**Steps to reproduce the problem**
 > It is not always reproducable

I am running a machine with `systemd-nspawn` and wait for the machine polling with `machinectl`. When the machine is up, I want to run some commands with 
```
systemd-run --machine "$MACHINE_NAME" --pipe --wait /bin/bash <<-EOT
...
EOT
```

```
Wait for container target8559
Container up!
Failed to create bus connection: Protocol error
```

The `Protocol error` comes from the `systemd-run` command. This happens **sometimes** ... don't know who to dig into ... is this a `D-Bus` problem?

### PR DESCRIPTION
**Pull request by daandemeyer**
I think this fixes #17620

### CODE REVIEW

File: src/libsystemd/sd-bus/bus-container.c [hunk 1]
```diff
@@ -75,8 +75,6 @@ int bus_container_connect_socket(sd_bus *b) {
         r = wait_for_terminate_and_check("(sd-buscntrns)", child, 0);
         if (r < 0)
                 return r;
-        if (r != EXIT_SUCCESS)
```
Comment (poettering) [inline src/libsystemd/sd-bus/bus-container.c:78]: hmm, so previously it happened way too often that people inserted other uses of `r` (since that's auch catchall error variable) between setting and using the variable like you do here, if the setting and the user is so long apart.

hence, please add a temporay bool here:

```c
bool nonzero_exit_status = r != EXIT_SUCCESS;
```

And then when you want to check things below, do a:

```c
if (nonzero_exit_status)
        return -EPROTO;
```

that way if people start to use `r` for somethingelse in between it doesn't matter.

**Comment by poettering** [comment]
looks good, but one more tweak please

**Comment by DaanDeMeyer** [comment]
Addressed comment, setting the green label

**Comment by poettering** [comment]
lgtm
