### PR TITLE
network/ndisc: add support for Redirect message

### LINKED ISSUE #31438: IPv6 Compliance RFC4861: Redirected On-link: Valid (Hosts Only) [v6LC.2.3.1]
### systemd version the issue has been seen with

255

### Used distribution

Ubuntu 23

### Linux kernel version used

6.5.0-17-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

#### Test v6LC.2.3.1: Redirected On-link: Valid (Hosts Only)
**Purpose**: Verify that a host properly processes valid Redirect messages when redirected on-link.
**Reference**: RFC 4861, Section 4.6.1, 4.6.3, and 8.3

#### Network Configuration
```
       TR1
        |
    +---+---+
    |       |
   TN1     HUT
```

#### Procedure
| Step | Action | Expected Behavior of HUT<sup>(1)</sup> |
|--------|--------|--------|
| 1 | TR1 forwards `Echo request Src="TN1 Offlink GA"` to HUT GA<sup>(2)</sup>. | HUT sends `Echo reply` to TR1 as first hop. |
| 2 | TR1 sends `Redirect Dst="TN1 GA" Target="TN1 GA"` to HUT. | |
| 3 | TR1 forwards `Echo request Src="TN1 Offlink GA"` to HUT GA. | HUT sends `NS` for TN1's GA and `Echo reply` to TN1 on-link. |
* **(1)** - Host Under Test
* **(2)** - Global Address

The procedure is repeated with the Redirect options changing for each run.

| Run | TLLA | Redirected Packet Option |
|--------|--------|--------|
| A | No | No |
| B | No | Yes |
| C | Yes | No |
| D | Yes | Yes | 

### Unexpected behaviour you saw

`networkd` ignores the `Redirect` message.  In Step 3, `networkd` issues its `Ping reply` with first-hop being TR1.

### Steps to reproduce the problem

[v6LC_2_3_01a.zip](https://github.com/systemd/systemd/files/14366217/v6LC_2_3_01a.zip)

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Closes #31438.

split-out of #30569.
This also includes a test case for #31373.

This is already tested by @LiveFreeAndRoam.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

File: src/libsystemd-network/sd-ndisc-redirect.c [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+        return 0;
+}
+
+int sd_ndisc_redirect_get_target_mac(sd_ndisc_redirect *rd, struct ether_addr *ret) {
+        assert_return(rd, -EINVAL);
+
+        return ndisc_option_get_mac(rd->options, SD_NDISC_OPTION_TARGET_LL_ADDRESS, ret);
+}
+
+int sd_ndisc_redirect_get_redirected_header(sd_ndisc_redirect *rd, struct ip6_hdr *ret) {
```
Comment (evverx) [inline src/libsystemd-network/sd-ndisc-redirect.c:113]: I wonder why `sd_ndisc_redirect_get_redirected_header`, `sd_ndisc_redirect_get_target_mac` and some other functions were added? As far as I can tell they aren't used anywhere. They don't seem to be included in the "network-next" branch either.

"Redirected Header" options were added to the parser in https://github.com/systemd/systemd/pull/31584 (and already triggered a memory leak as far as I can remember) but they are parsed and then thrown away.

Comment (yuwata) [reply src/libsystemd-network/sd-ndisc-redirect.c:113]: These are currently not used, may be used in a future, but not sure.

Comment (evverx) [reply src/libsystemd-network/sd-ndisc-redirect.c:113]: Dunno. Now that all the options are parsed unconditionally I'm not sure options like that should be there. It's true the parser is fuzzed but the fuzz target is pretty dumb in the sense that it isn't structure-aware and it can take longer than usual for it to discover even shallow issues especially given that lengths are in units of 8 octets there.
