### PR TITLE
pid1: fix cleanup of stale implicit deps based on /proc/self/mountinfo

### LINKED ISSUE #11342: systemd-240 fails to mount squashfs again, waiting for loop0 till timeout
**systemd version the issue has been seen with**
> 240 (this is a regression compared to 239)

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
 > I have the following in fstab:
 > ```
 > /home/mgorny/repos.ro.sqfs      /var/db/repos   squashfs        comment=systemd.automount       0 0
 > ```
 > 
 > The filesystem is mounted on boot. After unmounting it, both auto-mounting and `systemctl start var-db-repos.mount` used to mount it again.

**Unexpected behaviour you saw**
> After unmounting the filesystem once:
```
$ systemctl start var-db-repos.mount                                                                                        
A dependency job for var-db-repos.mount failed. See 'journalctl -xe' for details.
$ journalctl -xe
[...]
sty 06 10:10:11 pomiocik systemd[1]: dev-loop0.device: Job dev-loop0.device/start timed out.
sty 06 10:10:11 pomiocik systemd[1]: Timed out waiting for device /dev/loop0.
-- Subject: Unit dev-loop0.device has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit dev-loop0.device has failed.
-- 
-- The result is RESULT.
sty 06 10:10:11 pomiocik systemd[1]: Dependency failed for /var/db/repos.
-- Subject: Unit var-db-repos.mount has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit var-db-repos.mount has failed.
-- 
-- The result is RESULT.
sty 06 10:10:11 pomiocik systemd[1]: var-db-repos.mount: Job var-db-repos.mount/start failed with result 'dependency'.
sty 06 10:10:11 pomiocik systemd[1]: dev-loop0.device: Job dev-loop0.device/start failed with result 'timeout'.
```

**Steps to reproduce the problem**

1. Get or make a squashfs.
2. Add it to fstab as pasted above (with either automount or regular mount).
3. Reboot.
4. `umount /my/squashfs`
5. `systemctl start my-squashfs.mount`

### PR DESCRIPTION
**Pull request by keszybz**
The problem was introduced in a37422045fbb68ad68f734e5dc00e0a5b1759773:
we have a unit which has a fragment, and when we'd update it based on
/proc/self/mountinfo, we'd say that e.g. What=/dev/loop8 has origin-fragment.
This commit changes two things:
- origin-fragment is changed to origin-mountinfo-implicit
- when we stop a unit, mountinfo information is flushed and all deps based
  on it are dropped.

The second step is important, because when we restart the unit, we want to
notice that we have "fresh" mountinfo information. We could keep the old info
around and solve this in a different way, but keeping stale information seems
inelegant.

Fixes #11342.

### CODE REVIEW

File: src/core/mount.c [hunk 1]
```diff
@@ -352,7 +352,10 @@ static int mount_add_device_dependencies(Mount *m) {
          * automatically stopped when the device disappears suddenly. */
         dep = mount_is_bound_to_device(m) ? UNIT_BINDS_TO : UNIT_REQUIRES;
 
-        mask = m->from_fragment ? UNIT_DEPENDENCY_FILE : UNIT_DEPENDENCY_MOUNTINFO_IMPLICIT;
+        /* We update 'what' based on /proc/self/mountinfo, so let's say
+         * the dependency is based on that, even if we have a fragment. */
+        mask = m->from_fragment && !m->from_proc_self_mountinfo ? UNIT_DEPENDENCY_FILE
+                                                                : UNIT_DEPENDENCY_MOUNTINFO_IMPLICIT;
```
Comment (poettering) [inline src/core/mount.c]: hmm, actually i think the check should be this:

```c
mask = m->from_proc_self_mountinfo ? UNIT_DEPENDENCY_MOUNTINFO_IMPLICIT : UNIT_DEPENDENCY_FILE;
```

Why? because this is then in sync with the origin of `p`, see definition of get_mount_parameters()....

or in other words, I don't think we should test m->from_fragment here at all..

File: src/core/mount.c [hunk 2]
```diff
@@ -823,6 +826,10 @@ static void mount_enter_dead(Mount *m, MountResult f) {
         unit_unref_uid_gid(UNIT(m), true);
 
         dynamic_creds_destroy(&m->dynamic_creds);
+
+        /* Any information and dependencies based on /proc/self/mountinfo are now stale */
+        assert_se(update_parameters_proc_self_mount_info(m, NULL, NULL, NULL) >= 0);
+        unit_remove_dependencies(UNIT(m), UNIT_DEPENDENCY_MOUNTINFO_IMPLICIT);
```
Comment (poettering) [inline src/core/mount.c:855]: i don't grok this part. why is this necessary? we read /proc/self/mountinfo anyway very soon after, which should drop the data too, no? what's the reason for pulling that into this call, ahead of time?

**Comment by poettering** [comment]
not liked by CI

File: src/core/mount.c (hunk 1 above)
Comment (keszybz) [reply src/core/mount.c]: Yes, that's much better.

**Comment by keszybz** [comment]
bionic-i386 failed with `E: Malformed entry 1 in list file /etc/apt/sources.list.d/autopkgtest.list (URI parse)`. Looks unrelated.

File: src/core/mount.c (hunk 2 above)
Comment (keszybz) [reply src/core/mount.c:855]: I assume you are talking about the call to `update_parameters_...`. I tried to explain this in the commit message, but I know I wasn't very clear. The calls to `unit_remove_dependnecies` removes the references to the loopback device from the mount unit. This fixes the original bug reported in #11342. But an opposite issue starts occuring: after a sequence of start, stop, start of the mount unit, the mount doesn't have the automatic dependencies on the loopback device. The call to `update_parameters_...` fixes this new issue. Without it, after mounting again, if the same loopback device is used, we notice that the mountinfo parameters didn't change and don't trigger the update of automatic dependencies. This is not the only way this could be fixed. But I think it is actually pretty nice — I don't think we should "cache" stale information from mountinfo to save a few small allocs. In normal use the remount might never happen, or the loopback device might be different, etc. With this call, we stop the mount and destroy the volatile information, even if it is possible that it might be reused if we remount in the same place and with the same options.

**Comment by keszybz** [comment]
Updated for `mask` calculation.

File: src/core/mount.c (hunk 2 above)
Comment (poettering) [reply src/core/mount.c:855]: i still don#t get this though. I mean, we should enter mount_enter_dead() *because* the mount disappeared from /proc/self/mountinfo, i.e. the removal of the entry from that file should happen first, and because of it we then change the unit state. Now from the state change function you flush out the data acquired from /proc/self/mountinfo, as if it could still be there, but it should already have vanished, otherwise we couldn't reach where we are now...

What am I missing?

Comment (keszybz) [reply src/core/mount.c:855]: In my tests, the mountinfo data survived until the next start job. I'll try to figure out why it's not flushed.

**Comment by keszybz** [comment]
I moved the resetting of stale mount info to an earlier point. I hope you like this version better.

**Comment by keszybz** [comment]
I removed this PR from the milestone because the bug is already in it so we count things twice.
