### PR TITLE
udev: do not propagate error in executing PROGRAM

### LINKED ISSUE #14027: Keyboard and mouse not working in X.org with udev 243-5
**systemd version the issue has been seen with**
> 243-5

**Used distribution**
 > Debian bullseye/sid

**Expected behaviour you didn't see**
 >  when X comes up, keyboard and mouse responding to clicks and tips and all.

**Unexpected behaviour you saw**
 >  when X comes up, keyboard and mouse (console mode works just fine),

**Steps to reproduce the problem**
Either lightdm comes up and kills keyboard and mouse or issuing "startx" with same result.

-----
-- Package-specific info:

-- System Information:
Debian Release: bullseye/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'stable')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 5.2.0-3-amd64 (SMP w/2 CPU cores)
Locale: LANG=pt_BR.UTF-8, LC_CTYPE=pt_BR.UTF-8 (charmap=UTF-8) (ignored: LC_ALL set to pt_BR.UTF-8), LANGUAGE=pt_BR (charmap=UTF-8) (ignored: LC_ALL set to pt_BR.UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages udev depends on:
ii  adduser       3.118
ii  dpkg          1.19.7
ii  libacl1       2.2.53-5
ii  libblkid1     2.34-0.1
ii  libc6         2.29-3
ii  libkmod2      26-3
ii  libselinux1   2.9-2+b2
ii  libudev1      243-5
ii  systemd-sysv  243-5
ii  util-linux    2.34-0.1

udev recommends no packages.

udev suggests no packages.

Versions of packages udev is related to:
ii  systemd  243-5

-- debconf information:
  udev/title/upgrade:
  udev/new_kernel_needed: false
  udev/sysfs_deprecated_incompatibility:
  udev/reboot_needed:
[udev-database.txt (text/plain, attachment)]

-*-*-*-*-
P: /devices/LNXSYSTM:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:LNXSYSTM:
E: USEC_INITIALIZED=15547303
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXCPU:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXCPU:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:LNXCPU:
E: USEC_INITIALIZED=15548482
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXCPU:01
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXCPU:01
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:LNXCPU:
E: USEC_INITIALIZED=15549728
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXCPU:02
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXCPU:02
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:LNXCPU:
E: USEC_INITIALIZED=15548667
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXCPU:03
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXCPU:03
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:LNXCPU:
E: USEC_INITIALIZED=15549879
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXCPU:04
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXCPU:04
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:LNXCPU:
E: USEC_INITIALIZED=15551098
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXCPU:05
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXCPU:05
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:LNXCPU:
E: USEC_INITIALIZED=15551112
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXCPU:06
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXCPU:06
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:LNXCPU:
E: USEC_INITIALIZED=15552357
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXCPU:07
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXCPU:07
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:LNXCPU:
E: USEC_INITIALIZED=15553571
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXPWRBN:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXPWRBN:00
E: SUBSYSTEM=acpi
E: DRIVER=button
E: MODALIAS=acpi:LNXPWRBN:
E: USEC_INITIALIZED=15553593
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXPWRBN:00/input/input10
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXPWRBN:00/input/input10
E: SUBSYSTEM=input
E: PRODUCT=19/0/1/0
E: NAME="Power Button"
E: PHYS="LNXPWRBN/button/input0"
E: PROP=0
E: EV=3
E: KEY=10000000000000 0
E: MODALIAS=input:b0019v0000p0001e0000-e0,1,k74,ramlsfw
E: USEC_INITIALIZED=3672221
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_PATH=acpi-LNXPWRBN:00
E: ID_PATH_TAG=acpi-LNXPWRBN_00
E: ID_FOR_SEAT=input-acpi-LNXPWRBN_00
E: TAGS=:seat:

P: /devices/LNXSYSTM:00/LNXPWRBN:00/input/input10/event4
N: input/event4
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXPWRBN:00/input/input10/event4
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event4
E: MAJOR=13
E: MINOR=68

P: /devices/LNXSYSTM:00/LNXSYBUS:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:LNXSYBUS:
E: USEC_INITIALIZED=15554798
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00
E: SUBSYSTEM=acpi
E: DRIVER=ac
E: MODALIAS=acpi:ACPI0003:
E: USEC_INITIALIZED=15592786
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00/power_supply/ADP0
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00/power_supply/ADP0
E: SUBSYSTEM=power_supply
E: POWER_SUPPLY_NAME=ADP0
E: POWER_SUPPLY_ONLINE=1

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0A03:
E: USEC_INITIALIZED=15659749
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:31
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:31
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0A08:PNP0A03:
E: USEC_INITIALIZED=15678108
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00
E: SUBSYSTEM=acpi
E: DRIVER=video
E: MODALIAS=acpi:LNXVIDEO:
E: USEC_INITIALIZED=15681784
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/device:02
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/device:02
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/device:03
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/device:03
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/device:04
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/device:04
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input13
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input13
E: SUBSYSTEM=input
E: PRODUCT=19/0/6/0
E: NAME="Video Bus"
E: PHYS="LNXVIDEO/video/input0"
E: PROP=0
E: EV=3
E: KEY=3e000b00000000 0 0 0
E: MODALIAS=input:b0019v0000p0006e0000-e0,1,kE0,E1,E3,F1,F2,F3,F4,F5,ramlsfw
E: USEC_INITIALIZED=4241566
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_PATH=acpi-LNXVIDEO:00
E: ID_PATH_TAG=acpi-LNXVIDEO_00
E: ID_FOR_SEAT=input-acpi-LNXVIDEO_00
E: TAGS=:seat:

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input13/event5
N: input/event5
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input13/event5
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event5
E: MAJOR=13
E: MINOR=69

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/PNP0C02:01
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/PNP0C02:01
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0C02:
E: USEC_INITIALIZED=15732532
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/device:01
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/device:01
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:05
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:05
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/INT0800:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/INT0800:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:INT0800:
E: USEC_INITIALIZED=15791565
E: ID_VENDOR_FROM_DATABASE=Interphase Corporation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0000:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0000:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0000:
E: USEC_INITIALIZED=15784843
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0100:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0100:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0100:
E: USEC_INITIALIZED=15787886
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0103:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0103:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0103:
E: USEC_INITIALIZED=15792249
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0200:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0200:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0200:
E: USEC_INITIALIZED=15781117
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0303:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0303:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0303:
E: USEC_INITIALIZED=15773007
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0B00:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0B00:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0B00:
E: USEC_INITIALIZED=15789416
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0C02:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0C02:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0C02:
E: USEC_INITIALIZED=15782770
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0C04:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0C04:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0C04:
E: USEC_INITIALIZED=15791079
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0C09:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0C09:00
E: SUBSYSTEM=acpi
E: DRIVER=ec
E: MODALIAS=acpi:PNP0C09:
E: USEC_INITIALIZED=15779398
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0F13:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/PNP0F13:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0F13:
E: USEC_INITIALIZED=15805993
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/STLC063:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/STLC063:00
E: SUBSYSTEM=acpi
E: MODALIAS=

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:07
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:07
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:07/device:08
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:07/device:08
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:07/device:08/device:09
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:07/device:08/device:09
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0a
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0a
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0b
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0b
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0c
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0c
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0d
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0d
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0e
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0e
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0e/device:0f
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0e/device:0f
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0e/device:0f/device:10
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0e/device:0f/device:10
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:11
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:11
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:12
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:12
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:13
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:13
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:14
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:14
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:15
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:15
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:15/device:16
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:15/device:16
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:17
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:17
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:17/device:18
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:17/device:18
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:19
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:19
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:19/device:1a
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:19/device:1a
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1b
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1b
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1b/device:1c
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1b/device:1c
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1b/device:1d
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1b/device:1d
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1b/device:1e
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1b/device:1e
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1f
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1f
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1f/device:20
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1f/device:20
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:21
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:21
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:21/device:22
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:21/device:22
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:23
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:23
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:23/device:24
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:23/device:24
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:25
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:25
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:26
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:26
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:27
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:27
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:28
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:28
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:29
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:29
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2a
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2a
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2b
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2b
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2c
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2c
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2d
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2d
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2e
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2e
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2f
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2f
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:30
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:30
E: SUBSYSTEM=acpi

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00
E: SUBSYSTEM=acpi
E: DRIVER=battery
E: MODALIAS=acpi:PNP0C0A:
E: USEC_INITIALIZED=15822978
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0
E: SUBSYSTEM=power_supply
E: POWER_SUPPLY_NAME=BAT0
E: POWER_SUPPLY_STATUS=Full
E: POWER_SUPPLY_PRESENT=1
E: POWER_SUPPLY_TECHNOLOGY=Li-ion
E: POWER_SUPPLY_CYCLE_COUNT=0
E: POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11100000
E: POWER_SUPPLY_VOLTAGE_NOW=14800000
E: POWER_SUPPLY_CHARGE_FULL_DESIGN=4400000
E: POWER_SUPPLY_CHARGE_FULL=2738000
E: POWER_SUPPLY_CHARGE_NOW=2738000
E: POWER_SUPPLY_CAPACITY=100
E: POWER_SUPPLY_CAPACITY_LEVEL=Full
E: POWER_SUPPLY_MODEL_NAME=760
E: POWER_SUPPLY_MANUFACTURER=Clevo CO.
E: POWER_SUPPLY_SERIAL_NUMBER= 

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00
E: SUBSYSTEM=acpi
E: DRIVER=button
E: MODALIAS=acpi:PNP0C0C:
E: USEC_INITIALIZED=15834017
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input8
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input8
E: SUBSYSTEM=input
E: PRODUCT=19/0/1/0
E: NAME="Power Button"
E: PHYS="PNP0C0C/button/input0"
E: PROP=0
E: EV=3
E: KEY=10000000000000 0
E: MODALIAS=input:b0019v0000p0001e0000-e0,1,k74,ramlsfw
E: USEC_INITIALIZED=3671111
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_PATH=acpi-PNP0C0C:00
E: ID_PATH_TAG=acpi-PNP0C0C_00
E: ID_FOR_SEAT=input-acpi-PNP0C0C_00
E: TAGS=:seat:

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input8/event2
N: input/event2
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input8/event2
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event2
E: MAJOR=13
E: MINOR=66

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00
E: SUBSYSTEM=acpi
E: DRIVER=button
E: MODALIAS=acpi:PNP0C0D:
E: USEC_INITIALIZED=15828973
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input6
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input6
E: SUBSYSTEM=input
E: PRODUCT=19/0/5/0
E: NAME="Lid Switch"
E: PHYS="PNP0C0D/button/input0"
E: PROP=0
E: EV=21
E: SW=1
E: MODALIAS=input:b0019v0000p0005e0000-e0,5,kramlsfw0,
E: USEC_INITIALIZED=3649459
E: ID_INPUT=1
E: ID_INPUT_SWITCH=1
E: ID_PATH=acpi-PNP0C0D:00
E: ID_PATH_TAG=acpi-PNP0C0D_00
E: ID_FOR_SEAT=input-acpi-PNP0C0D_00
E: TAGS=:seat:

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input6/event1
N: input/event1
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input6/event1
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event1
E: MAJOR=13
E: MINOR=65

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00
E: SUBSYSTEM=acpi
E: DRIVER=button
E: MODALIAS=acpi:PNP0C0E:
E: USEC_INITIALIZED=15827679
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input9
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input9
E: SUBSYSTEM=input
E: PRODUCT=19/0/3/0
E: NAME="Sleep Button"
E: PHYS="PNP0C0E/button/input0"
E: PROP=0
E: EV=3
E: KEY=4000 0 0
E: MODALIAS=input:b0019v0000p0003e0000-e0,1,k8E,ramlsfw
E: USEC_INITIALIZED=3671488
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_PATH=acpi-PNP0C0E:00
E: ID_PATH_TAG=acpi-PNP0C0E_00
E: ID_FOR_SEAT=input-acpi-PNP0C0E_00
E: TAGS=:seat:

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input9/event3
N: input/event3
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input9/event3
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event3
E: MAJOR=13
E: MINOR=67

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0C0F:
E: USEC_INITIALIZED=15830394
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:01
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:01
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0C0F:
E: USEC_INITIALIZED=15831592
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:02
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:02
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0C0F:
E: USEC_INITIALIZED=15832800
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:03
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:03
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0C0F:
E: USEC_INITIALIZED=15835268
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:04
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:04
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0C0F:
E: USEC_INITIALIZED=15839832
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:05
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:05
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0C0F:
E: USEC_INITIALIZED=15838647
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:06
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:06
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0C0F:
E: USEC_INITIALIZED=15843213
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:07
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:07
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0C0F:
E: USEC_INITIALIZED=15846563
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C14:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C14:00
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:PNP0C14:
E: USEC_INITIALIZED=15853729
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C31:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C31:00
E: SUBSYSTEM=acpi
E: MODALIAS=

P: /devices/LNXSYSTM:00/LNXSYBUS:01
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:01
E: SUBSYSTEM=acpi
E: MODALIAS=acpi:LNXSYBUS:
E: USEC_INITIALIZED=15848996
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/LNXSYSTM:00/LNXSYBUS:01/LNXTHERM:00
L: 0
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:01/LNXTHERM:00
E: SUBSYSTEM=acpi
E: DRIVER=thermal
E: MODALIAS=acpi:LNXTHERM:
E: USEC_INITIALIZED=15854999
E: ID_VENDOR_FROM_DATABASE=The Linux Foundation

P: /devices/breakpoint
L: 0
E: DEVPATH=/devices/breakpoint
E: SUBSYSTEM=event_source

P: /devices/cpu
L: 0
E: DEVPATH=/devices/cpu
E: SUBSYSTEM=event_source

P: /devices/cstate_core
L: 0
E: DEVPATH=/devices/cstate_core
E: SUBSYSTEM=event_source

P: /devices/cstate_pkg
L: 0
E: DEVPATH=/devices/cstate_pkg
E: SUBSYSTEM=event_source

P: /devices/i915
L: 0
E: DEVPATH=/devices/i915
E: SUBSYSTEM=event_source

P: /devices/kprobe
L: 0
E: DEVPATH=/devices/kprobe
E: SUBSYSTEM=event_source

P: /devices/msr
L: 0
E: DEVPATH=/devices/msr
E: SUBSYSTEM=event_source

P: /devices/pci0000:00/0000:00:00.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:00.0
E: SUBSYSTEM=pci
E: PCI_CLASS=60000
E: PCI_ID=8086:0044
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:00.0
E: MODALIAS=pci:v00008086d00000044sv00001558sd00005125bc06sc00i00
E: USEC_INITIALIZED=15680718
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=Host bridge
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=Core Processor DRAM Controller

P: /devices/pci0000:00/0000:00:02.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0
E: SUBSYSTEM=pci
E: DRIVER=i915
E: PCI_CLASS=30000
E: PCI_ID=8086:0046
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:02.0
E: MODALIAS=pci:v00008086d00000046sv00001558sd00005125bc03sc00i00
E: USEC_INITIALIZED=15672129
E: ID_PCI_CLASS_FROM_DATABASE=Display controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=VGA compatible controller
E: ID_PCI_INTERFACE_FROM_DATABASE=VGA controller
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=Core Processor Integrated Graphics Controller

P: /devices/pci0000:00/0000:00:02.0/backlight/acpi_video0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/backlight/acpi_video0
E: SUBSYSTEM=backlight
E: USEC_INITIALIZED=15847929
E: ID_PATH=pci-0000:00:02.0
E: ID_PATH_TAG=pci-0000_00_02_0
E: ID_FOR_SEAT=backlight-pci-0000_00_02_0
E: SYSTEMD_WANTS=systemd-backlight@backlight:acpi_video0.service
E: TAGS=:seat:systemd:

P: /devices/pci0000:00/0000:00:02.0/drm/card0
N: dri/card0
L: 0
S: dri/by-path/pci-0000:00:02.0-card
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/drm/card0
E: SUBSYSTEM=drm
E: DEVNAME=/dev/dri/card0
E: DEVTYPE=drm_minor
E: MAJOR=226
E: MINOR=0
E: USEC_INITIALIZED=4875244
E: ID_PATH=pci-0000:00:02.0
E: ID_PATH_TAG=pci-0000_00_02_0
E: ID_FOR_SEAT=drm-pci-0000_00_02_0
E: DEVLINKS=/dev/dri/by-path/pci-0000:00:02.0-card
E: TAGS=:master-of-seat:seat:uaccess:

P: /devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1
E: SUBSYSTEM=drm
E: USEC_INITIALIZED=4882696
E: ID_PATH=pci-0000:00:02.0
E: ID_PATH_TAG=pci-0000_00_02_0
E: ID_FOR_SEAT=drm-pci-0000_00_02_0
E: TAGS=:master-of-seat:seat:

P: /devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1/drm_dp_aux0
N: drm_dp_aux0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1/drm_dp_aux0
E: SUBSYSTEM=drm_dp_aux_dev
E: DEVNAME=/dev/drm_dp_aux0
E: MAJOR=249
E: MINOR=0

P: /devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1/i2c-7
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1/i2c-7
E: SUBSYSTEM=i2c

P: /devices/pci0000:00/0000:00:02.0/drm/card0/card0-HDMI-A-1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/drm/card0/card0-HDMI-A-1
E: SUBSYSTEM=drm
E: USEC_INITIALIZED=4881838
E: ID_PATH=pci-0000:00:02.0
E: ID_PATH_TAG=pci-0000_00_02_0
E: ID_FOR_SEAT=drm-pci-0000_00_02_0
E: TAGS=:master-of-seat:seat:

P: /devices/pci0000:00/0000:00:02.0/drm/card0/card0-LVDS-1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/drm/card0/card0-LVDS-1
E: SUBSYSTEM=drm
E: USEC_INITIALIZED=4875737
E: ID_PATH=pci-0000:00:02.0
E: ID_PATH_TAG=pci-0000_00_02_0
E: ID_FOR_SEAT=drm-pci-0000_00_02_0
E: TAGS=:master-of-seat:seat:

P: /devices/pci0000:00/0000:00:02.0/drm/card0/card0-VGA-1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/drm/card0/card0-VGA-1
E: SUBSYSTEM=drm
E: USEC_INITIALIZED=4880411
E: ID_PATH=pci-0000:00:02.0
E: ID_PATH_TAG=pci-0000_00_02_0
E: ID_FOR_SEAT=drm-pci-0000_00_02_0
E: TAGS=:master-of-seat:seat:

P: /devices/pci0000:00/0000:00:02.0/drm/renderD128
N: dri/renderD128
L: 0
S: dri/by-path/pci-0000:00:02.0-render
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/drm/renderD128
E: SUBSYSTEM=drm
E: DEVNAME=/dev/dri/renderD128
E: DEVTYPE=drm_minor
E: MAJOR=226
E: MINOR=128
E: USEC_INITIALIZED=15858391
E: ID_PATH=pci-0000:00:02.0
E: ID_PATH_TAG=pci-0000_00_02_0
E: ID_FOR_SEAT=drm-pci-0000_00_02_0
E: DEVLINKS=/dev/dri/by-path/pci-0000:00:02.0-render
E: TAGS=:seat:uaccess:

P: /devices/pci0000:00/0000:00:02.0/graphics/fb0
N: fb0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/graphics/fb0
E: SUBSYSTEM=graphics
E: DEVNAME=/dev/fb0
E: MAJOR=29
E: MINOR=0
E: USEC_INITIALIZED=4884855
E: ID_PATH=pci-0000:00:02.0
E: ID_PATH_TAG=pci-0000_00_02_0
E: ID_FOR_SEAT=graphics-pci-0000_00_02_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:02.0/i2c-1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/i2c-1
E: SUBSYSTEM=i2c

P: /devices/pci0000:00/0000:00:02.0/i2c-2
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/i2c-2
E: SUBSYSTEM=i2c

P: /devices/pci0000:00/0000:00:02.0/i2c-3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/i2c-3
E: SUBSYSTEM=i2c

P: /devices/pci0000:00/0000:00:02.0/i2c-4
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/i2c-4
E: SUBSYSTEM=i2c

P: /devices/pci0000:00/0000:00:02.0/i2c-5
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/i2c-5
E: SUBSYSTEM=i2c

P: /devices/pci0000:00/0000:00:02.0/i2c-6
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/i2c-6
E: SUBSYSTEM=i2c

P: /devices/pci0000:00/0000:00:16.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:16.0
E: SUBSYSTEM=pci
E: DRIVER=mei_me
E: PCI_CLASS=78000
E: PCI_ID=8086:3B64
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:16.0
E: MODALIAS=pci:v00008086d00003B64sv00001558sd00005125bc07sc80i00
E: USEC_INITIALIZED=15749445
E: ID_PCI_CLASS_FROM_DATABASE=Communication controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Communication controller
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset HECI Controller

P: /devices/pci0000:00/0000:00:16.0/mei/mei0
N: mei0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:16.0/mei/mei0
E: SUBSYSTEM=mei
E: DEVNAME=/dev/mei0
E: MAJOR=247
E: MINOR=0

P: /devices/pci0000:00/0000:00:16.0/mei::309dcde8-ccb1-4062-8f78-600115a34327:01
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:16.0/mei::309dcde8-ccb1-4062-8f78-600115a34327:01
E: SUBSYSTEM=mei
E: MEI_CL_VERSION=1
E: MEI_CL_UUID=309dcde8-ccb1-4062-8f78-600115a34327
E: MEI_CL_NAME=
E: MODALIAS=mei::309dcde8-ccb1-4062-8f78-600115a34327:01:

P: /devices/pci0000:00/0000:00:16.0/mei::3c4852d6-d47b-4f46-b05e-b5edc1aa430a:01
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:16.0/mei::3c4852d6-d47b-4f46-b05e-b5edc1aa430a:01
E: SUBSYSTEM=mei
E: MEI_CL_VERSION=1
E: MEI_CL_UUID=3c4852d6-d47b-4f46-b05e-b5edc1aa430a
E: MEI_CL_NAME=
E: MODALIAS=mei::3c4852d6-d47b-4f46-b05e-b5edc1aa430a:01:

P: /devices/pci0000:00/0000:00:16.0/mei::42b3ce2f-bd9f-485a-96ae-26406230b1ff:01
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:16.0/mei::42b3ce2f-bd9f-485a-96ae-26406230b1ff:01
E: SUBSYSTEM=mei
E: MEI_CL_VERSION=1
E: MEI_CL_UUID=42b3ce2f-bd9f-485a-96ae-26406230b1ff
E: MEI_CL_NAME=
E: MODALIAS=mei::42b3ce2f-bd9f-485a-96ae-26406230b1ff:01:

P: /devices/pci0000:00/0000:00:16.0/mei::55213584-9a29-4916-badf-0fb7ed682aeb:01
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:16.0/mei::55213584-9a29-4916-badf-0fb7ed682aeb:01
E: SUBSYSTEM=mei
E: MEI_CL_VERSION=1
E: MEI_CL_UUID=55213584-9a29-4916-badf-0fb7ed682aeb
E: MEI_CL_NAME=
E: MODALIAS=mei::55213584-9a29-4916-badf-0fb7ed682aeb:01:

P: /devices/pci0000:00/0000:00:16.0/mei::9b27fd6d-ef72-4967-bcc2-471a32679620:01
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:16.0/mei::9b27fd6d-ef72-4967-bcc2-471a32679620:01
E: SUBSYSTEM=mei
E: MEI_CL_VERSION=1
E: MEI_CL_UUID=9b27fd6d-ef72-4967-bcc2-471a32679620
E: MEI_CL_NAME=
E: MODALIAS=mei::9b27fd6d-ef72-4967-bcc2-471a32679620:01:

P: /devices/pci0000:00/0000:00:16.0/mei::d2ea63bc-5f04-4997-9454-8cadf4e3ef8a:01
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:16.0/mei::d2ea63bc-5f04-4997-9454-8cadf4e3ef8a:01
E: SUBSYSTEM=mei
E: MEI_CL_VERSION=1
E: MEI_CL_UUID=d2ea63bc-5f04-4997-9454-8cadf4e3ef8a
E: MEI_CL_NAME=
E: MODALIAS=mei::d2ea63bc-5f04-4997-9454-8cadf4e3ef8a:01:

P: /devices/pci0000:00/0000:00:16.0/mei::f908627d-13bf-4a04-b91f-a64e9245323d:01
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:16.0/mei::f908627d-13bf-4a04-b91f-a64e9245323d:01
E: SUBSYSTEM=mei
E: MEI_CL_VERSION=1
E: MEI_CL_UUID=f908627d-13bf-4a04-b91f-a64e9245323d
E: MEI_CL_NAME=
E: MODALIAS=mei::f908627d-13bf-4a04-b91f-a64e9245323d:01:

P: /devices/pci0000:00/0000:00:16.0/mei::fa8f55e8-ab22-42dd-b916-7dce39002574:01
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:16.0/mei::fa8f55e8-ab22-42dd-b916-7dce39002574:01
E: SUBSYSTEM=mei
E: MEI_CL_VERSION=1
E: MEI_CL_UUID=fa8f55e8-ab22-42dd-b916-7dce39002574
E: MEI_CL_NAME=
E: MODALIAS=mei::fa8f55e8-ab22-42dd-b916-7dce39002574:01:

P: /devices/pci0000:00/0000:00:1a.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1a.0
E: SUBSYSTEM=pci
E: DRIVER=ehci-pci
E: PCI_CLASS=C0320
E: PCI_ID=8086:3B3C
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:1a.0
E: MODALIAS=pci:v00008086d00003B3Csv00001558sd00005125bc0Csc03i20
E: USEC_INITIALIZED=15743508
E: ID_PCI_CLASS_FROM_DATABASE=Serial bus controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=USB controller
E: ID_PCI_INTERFACE_FROM_DATABASE=EHCI
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset USB2 Enhanced Host Controller

P: /devices/pci0000:00/0000:00:1a.0/usb1
N: bus/usb/001/001
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1a.0/usb1
E: SUBSYSTEM=usb
E: DEVNAME=/dev/bus/usb/001/001
E: DEVTYPE=usb_device
E: DRIVER=usb
E: PRODUCT=1d6b/2/502
E: TYPE=9/0/0
E: BUSNUM=001
E: DEVNUM=001
E: MAJOR=189
E: MINOR=0
E: USEC_INITIALIZED=3702639
E: ID_VENDOR=Linux_5.2.0-3-amd64_ehci_hcd
E: ID_VENDOR_ENC=Linux\x205.2.0-3-amd64\x20ehci_hcd
E: ID_VENDOR_ID=1d6b
E: ID_MODEL=EHCI_Host_Controller
E: ID_MODEL_ENC=EHCI\x20Host\x20Controller
E: ID_MODEL_ID=0002
E: ID_REVISION=0502
E: ID_SERIAL=Linux_5.2.0-3-amd64_ehci_hcd_EHCI_Host_Controller_0000:00:1a.0
E: ID_SERIAL_SHORT=0000:00:1a.0
E: ID_BUS=usb
E: ID_USB_INTERFACES=:090000:
E: ID_VENDOR_FROM_DATABASE=Linux Foundation
E: ID_MODEL_FROM_DATABASE=2.0 root hub
E: ID_PATH=pci-0000:00:1a.0
E: ID_PATH_TAG=pci-0000_00_1a_0
E: ID_FOR_SEAT=usb-pci-0000_00_1a_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1a.0/usb1/1-0:1.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1a.0/usb1/1-0:1.0
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=hub
E: PRODUCT=1d6b/2/502
E: TYPE=9/0/0
E: INTERFACE=9/0/0
E: MODALIAS=usb:v1D6Bp0002d0502dc09dsc00dp00ic09isc00ip00in00
E: USEC_INITIALIZED=16625546
E: ID_USB_CLASS_FROM_DATABASE=Hub
E: ID_USB_PROTOCOL_FROM_DATABASE=Full speed (or root) hub
E: ID_VENDOR_FROM_DATABASE=Linux Foundation
E: ID_MODEL_FROM_DATABASE=2.0 root hub
E: ID_PATH=pci-0000:00:1a.0-usb-0:0:1.0
E: ID_PATH_TAG=pci-0000_00_1a_0-usb-0_0_1_0

P: /devices/pci0000:00/0000:00:1a.0/usb1/1-1
N: bus/usb/001/002
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1a.0/usb1/1-1
E: SUBSYSTEM=usb
E: DEVNAME=/dev/bus/usb/001/002
E: DEVTYPE=usb_device
E: DRIVER=usb
E: PRODUCT=8087/20/0
E: TYPE=9/0/1
E: BUSNUM=001
E: DEVNUM=002
E: MAJOR=189
E: MINOR=1
E: USEC_INITIALIZED=4388961
E: ID_VENDOR=8087
E: ID_VENDOR_ENC=8087
E: ID_VENDOR_ID=8087
E: ID_MODEL=0020
E: ID_MODEL_ENC=0020
E: ID_MODEL_ID=0020
E: ID_REVISION=0000
E: ID_SERIAL=8087_0020
E: ID_BUS=usb
E: ID_USB_INTERFACES=:090000:
E: ID_VENDOR_FROM_DATABASE=Intel Corp.
E: ID_MODEL_FROM_DATABASE=Integrated Rate Matching Hub
E: ID_PATH=pci-0000:00:1a.0-usb-0:1
E: ID_PATH_TAG=pci-0000_00_1a_0-usb-0_1
E: ID_FOR_SEAT=usb-pci-0000_00_1a_0-usb-0_1
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1:1.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1:1.0
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=hub
E: PRODUCT=8087/20/0
E: TYPE=9/0/1
E: INTERFACE=9/0/0
E: MODALIAS=usb:v8087p0020d0000dc09dsc00dp01ic09isc00ip00in00
E: USEC_INITIALIZED=16668068
E: ID_USB_CLASS_FROM_DATABASE=Hub
E: ID_USB_PROTOCOL_FROM_DATABASE=Single TT
E: ID_VENDOR_FROM_DATABASE=Intel Corp.
E: ID_MODEL_FROM_DATABASE=Integrated Rate Matching Hub
E: ID_PATH=pci-0000:00:1a.0-usb-0:1:1.0
E: ID_PATH_TAG=pci-0000_00_1a_0-usb-0_1_1_0

P: /devices/pci0000:00/0000:00:1b.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0
E: SUBSYSTEM=pci
E: DRIVER=snd_hda_intel
E: PCI_CLASS=40300
E: PCI_ID=8086:3B56
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:1b.0
E: MODALIAS=pci:v00008086d00003B56sv00001558sd00005125bc04sc03i00
E: USEC_INITIALIZED=15748465
E: ID_PCI_CLASS_FROM_DATABASE=Multimedia controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Audio device
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset High Definition Audio

P: /devices/pci0000:00/0000:00:1b.0/hdaudioC0D0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/hdaudioC0D0
E: SUBSYSTEM=hdaudio
E: DRIVER=snd_hda_codec_realtek
E: MODALIAS=hdaudio:v10EC0272r00100001a01

P: /devices/pci0000:00/0000:00:1b.0/hdaudioC0D3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/hdaudioC0D3
E: SUBSYSTEM=hdaudio
E: DRIVER=snd_hda_codec_hdmi
E: MODALIAS=hdaudio:v80862804r00100000a01

P: /devices/pci0000:00/0000:00:1b.0/sound/card0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0
E: SUBSYSTEM=sound
E: USEC_INITIALIZED=17261584
E: ID_PATH=pci-0000:00:1b.0
E: ID_PATH_TAG=pci-0000_00_1b_0
E: ID_FOR_SEAT=sound-pci-0000_00_1b_0
E: SOUND_INITIALIZED=1
E: ID_PCI_CLASS_FROM_DATABASE=Multimedia controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Audio device
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset High Definition Audio
E: ID_BUS=pci
E: ID_VENDOR_ID=0x8086
E: ID_MODEL_ID=0x3b56
E: SOUND_FORM_FACTOR=internal
E: SYSTEMD_WANTS=sound.target
E: SYSTEMD_USER_WANTS=sound.target
E: TAGS=:seat:systemd:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/hwC0D0
N: snd/hwC0D0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/hwC0D0
E: SUBSYSTEM=sound
E: DEVNAME=/dev/snd/hwC0D0
E: MAJOR=116
E: MINOR=7
E: USEC_INITIALIZED=17268915
E: TAGS=:uaccess:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/hwC0D3
N: snd/hwC0D3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/hwC0D3
E: SUBSYSTEM=sound
E: DEVNAME=/dev/snd/hwC0D3
E: MAJOR=116
E: MINOR=8
E: USEC_INITIALIZED=17268720
E: TAGS=:uaccess:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input22
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input22
E: SUBSYSTEM=input
E: PRODUCT=1/10ec/272/1
E: NAME="HDA Digital PCBeep"
E: PHYS="card0/codec#0/beep0"
E: PROP=0
E: EV=40001
E: SND=6
E: MODALIAS=input:b0001v10ECp0272e0001-e0,12,kramls1,2,fw
E: USEC_INITIALIZED=17270529
E: ID_INPUT=1
E: ID_PATH=pci-0000:00:1b.0
E: ID_PATH_TAG=pci-0000_00_1b_0
E: ID_FOR_SEAT=input-pci-0000_00_1b_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input22/event13
N: input/event13
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input22/event13
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event13
E: MAJOR=13
E: MINOR=77

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input23
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input23
E: SUBSYSTEM=input
E: PRODUCT=0/0/0/0
E: NAME="HDA Intel MID Mic"
E: PHYS="ALSA"
E: PROP=0
E: EV=21
E: SW=10
E: MODALIAS=input:b0000v0000p0000e0000-e0,5,kramlsfw4,
E: USEC_INITIALIZED=17271040
E: ID_INPUT=1
E: ID_INPUT_SWITCH=1
E: ID_PATH=pci-0000:00:1b.0
E: ID_PATH_TAG=pci-0000_00_1b_0
E: ID_FOR_SEAT=input-pci-0000_00_1b_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input23/event14
N: input/event14
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input23/event14
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event14
E: MAJOR=13
E: MINOR=78

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input24
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input24
E: SUBSYSTEM=input
E: PRODUCT=0/0/0/0
E: NAME="HDA Intel MID Headphone"
E: PHYS="ALSA"
E: PROP=0
E: EV=21
E: SW=4
E: MODALIAS=input:b0000v0000p0000e0000-e0,5,kramlsfw2,
E: USEC_INITIALIZED=17272475
E: ID_INPUT=1
E: ID_INPUT_SWITCH=1
E: ID_PATH=pci-0000:00:1b.0
E: ID_PATH_TAG=pci-0000_00_1b_0
E: ID_FOR_SEAT=input-pci-0000_00_1b_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input24/event15
N: input/event15
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input24/event15
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event15
E: MAJOR=13
E: MINOR=79

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input25
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input25
E: SUBSYSTEM=input
E: PRODUCT=0/0/0/0
E: NAME="HDA Intel MID HDMI/DP,pcm=3"
E: PHYS="ALSA"
E: PROP=0
E: EV=21
E: SW=140
E: MODALIAS=input:b0000v0000p0000e0000-e0,5,kramlsfw6,8,
E: USEC_INITIALIZED=17304744
E: ID_INPUT=1
E: ID_INPUT_SWITCH=1
E: ID_PATH=pci-0000:00:1b.0
E: ID_PATH_TAG=pci-0000_00_1b_0
E: ID_FOR_SEAT=input-pci-0000_00_1b_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input25/event16
N: input/event16
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input25/event16
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event16
E: MAJOR=13
E: MINOR=80

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input26
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input26
E: SUBSYSTEM=input
E: PRODUCT=0/0/0/0
E: NAME="HDA Intel MID HDMI/DP,pcm=7"
E: PHYS="ALSA"
E: PROP=0
E: EV=21
E: SW=140
E: MODALIAS=input:b0000v0000p0000e0000-e0,5,kramlsfw6,8,
E: USEC_INITIALIZED=17306412
E: ID_INPUT=1
E: ID_INPUT_SWITCH=1
E: ID_PATH=pci-0000:00:1b.0
E: ID_PATH_TAG=pci-0000_00_1b_0
E: ID_FOR_SEAT=input-pci-0000_00_1b_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input26/event17
N: input/event17
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input26/event17
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event17
E: MAJOR=13
E: MINOR=81

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input27
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input27
E: SUBSYSTEM=input
E: PRODUCT=0/0/0/0
E: NAME="HDA Intel MID HDMI/DP,pcm=8"
E: PHYS="ALSA"
E: PROP=0
E: EV=21
E: SW=140
E: MODALIAS=input:b0000v0000p0000e0000-e0,5,kramlsfw6,8,
E: USEC_INITIALIZED=17314336
E: ID_INPUT=1
E: ID_INPUT_SWITCH=1
E: ID_PATH=pci-0000:00:1b.0
E: ID_PATH_TAG=pci-0000_00_1b_0
E: ID_FOR_SEAT=input-pci-0000_00_1b_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input27/event18
N: input/event18
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input27/event18
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event18
E: MAJOR=13
E: MINOR=82

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/pcmC0D0c
N: snd/pcmC0D0c
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/pcmC0D0c
E: SUBSYSTEM=sound
E: DEVNAME=/dev/snd/pcmC0D0c
E: DEVTYPE=pcm
E: MAJOR=116
E: MINOR=3
E: USEC_INITIALIZED=17264675
E: TAGS=:uaccess:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/pcmC0D0p
N: snd/pcmC0D0p
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/pcmC0D0p
E: SUBSYSTEM=sound
E: DEVNAME=/dev/snd/pcmC0D0p
E: DEVTYPE=pcm
E: MAJOR=116
E: MINOR=2
E: USEC_INITIALIZED=17263162
E: TAGS=:uaccess:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/pcmC0D3p
N: snd/pcmC0D3p
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/pcmC0D3p
E: SUBSYSTEM=sound
E: DEVNAME=/dev/snd/pcmC0D3p
E: DEVTYPE=pcm
E: MAJOR=116
E: MINOR=4
E: USEC_INITIALIZED=17265232
E: TAGS=:uaccess:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/pcmC0D7p
N: snd/pcmC0D7p
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/pcmC0D7p
E: SUBSYSTEM=sound
E: DEVNAME=/dev/snd/pcmC0D7p
E: DEVTYPE=pcm
E: MAJOR=116
E: MINOR=5
E: USEC_INITIALIZED=17267273
E: TAGS=:uaccess:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/pcmC0D8p
N: snd/pcmC0D8p
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/pcmC0D8p
E: SUBSYSTEM=sound
E: DEVNAME=/dev/snd/pcmC0D8p
E: DEVTYPE=pcm
E: MAJOR=116
E: MINOR=6
E: USEC_INITIALIZED=17266736
E: TAGS=:uaccess:

P: /devices/pci0000:00/0000:00:1b.0/sound/card0/controlC0
N: snd/controlC0
L: 0
S: snd/by-path/pci-0000:00:1b.0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/controlC0
E: SUBSYSTEM=sound
E: DEVNAME=/dev/snd/controlC0
E: MAJOR=116
E: MINOR=9
E: USEC_INITIALIZED=17471489
E: ID_PATH=pci-0000:00:1b.0
E: ID_PATH_TAG=pci-0000_00_1b_0
E: DEVLINKS=/dev/snd/by-path/pci-0000:00:1b.0
E: TAGS=:uaccess:

P: /devices/pci0000:00/0000:00:1c.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.0
E: SUBSYSTEM=pci
E: DRIVER=pcieport
E: PCI_CLASS=60400
E: PCI_ID=8086:3B42
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:1c.0
E: MODALIAS=pci:v00008086d00003B42sv00001558sd00005125bc06sc04i00
E: USEC_INITIALIZED=15746102
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=PCI bridge
E: ID_PCI_INTERFACE_FROM_DATABASE=Normal decode
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset PCI Express Root Port 1

P: /devices/pci0000:00/0000:00:1c.0/0000:00:1c.0:pcie010
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.0/0000:00:1c.0:pcie010
E: SUBSYSTEM=pci_express

P: /devices/pci0000:00/0000:00:1c.0/pci_bus/0000:02
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.0/pci_bus/0000:02
E: SUBSYSTEM=pci_bus

P: /devices/pci0000:00/0000:00:1c.1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.1
E: SUBSYSTEM=pci
E: DRIVER=pcieport
E: PCI_CLASS=60400
E: PCI_ID=8086:3B44
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:1c.1
E: MODALIAS=pci:v00008086d00003B44sv00001558sd00005125bc06sc04i00
E: USEC_INITIALIZED=15744482
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=PCI bridge
E: ID_PCI_INTERFACE_FROM_DATABASE=Normal decode
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset PCI Express Root Port 2

P: /devices/pci0000:00/0000:00:1c.1/0000:00:1c.1:pcie010
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.1/0000:00:1c.1:pcie010
E: SUBSYSTEM=pci_express

P: /devices/pci0000:00/0000:00:1c.1/pci_bus/0000:03
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.1/pci_bus/0000:03
E: SUBSYSTEM=pci_bus

P: /devices/pci0000:00/0000:00:1c.2
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.2
E: SUBSYSTEM=pci
E: DRIVER=pcieport
E: PCI_CLASS=60400
E: PCI_ID=8086:3B46
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:1c.2
E: MODALIAS=pci:v00008086d00003B46sv00001558sd00005125bc06sc04i00
E: USEC_INITIALIZED=15746885
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=PCI bridge
E: ID_PCI_INTERFACE_FROM_DATABASE=Normal decode
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset PCI Express Root Port 3

P: /devices/pci0000:00/0000:00:1c.2/0000:00:1c.2:pcie010
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.2/0000:00:1c.2:pcie010
E: SUBSYSTEM=pci_express

P: /devices/pci0000:00/0000:00:1c.2/0000:05:00.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.2/0000:05:00.0
E: SUBSYSTEM=pci
E: DRIVER=rtl8192ce
E: PCI_CLASS=28000
E: PCI_ID=10EC:8176
E: PCI_SUBSYS_ID=10EC:9196
E: PCI_SLOT_NAME=0000:05:00.0
E: MODALIAS=pci:v000010ECd00008176sv000010ECsd00009196bc02sc80i00
E: USEC_INITIALIZED=16076415
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Network controller
E: ID_VENDOR_FROM_DATABASE=Realtek Semiconductor Co., Ltd.
E: ID_MODEL_FROM_DATABASE=RTL8188CE 802.11b/g/n WiFi Adapter

P: /devices/pci0000:00/0000:00:1c.2/0000:05:00.0/ieee80211/phy0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.2/0000:05:00.0/ieee80211/phy0
E: SUBSYSTEM=ieee80211

P: /devices/pci0000:00/0000:00:1c.2/0000:05:00.0/ieee80211/phy0/rfkill0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.2/0000:05:00.0/ieee80211/phy0/rfkill0
E: SUBSYSTEM=rfkill
E: RFKILL_NAME=phy0
E: RFKILL_TYPE=wlan
E: RFKILL_STATE=2
E: USEC_INITIALIZED=18114982
E: SYSTEMD_RFKILL=1
E: ID_PATH=pci-0000:05:00.0
E: ID_PATH_TAG=pci-0000_05_00_0

P: /devices/pci0000:00/0000:00:1c.2/0000:05:00.0/net/wlan0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.2/0000:05:00.0/net/wlan0
E: SUBSYSTEM=net
E: DEVTYPE=wlan
E: INTERFACE=wlan0
E: IFINDEX=3
E: USEC_INITIALIZED=18182596
E: ID_NET_NAMING_SCHEME=v243
E: ID_NET_NAME_MAC=wlx001c7b9d123c
E: ID_OUI_FROM_DATABASE=Castlenet Technology Inc.
E: ID_NET_NAME_PATH=wlp5s0
E: ID_BUS=pci
E: ID_VENDOR_ID=0x10ec
E: ID_MODEL_ID=0x8176
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Network controller
E: ID_VENDOR_FROM_DATABASE=Realtek Semiconductor Co., Ltd.
E: ID_MODEL_FROM_DATABASE=RTL8188CE 802.11b/g/n WiFi Adapter
E: ID_MM_CANDIDATE=1
E: ID_PATH=pci-0000:05:00.0
E: ID_PATH_TAG=pci-0000_05_00_0
E: ID_NET_DRIVER=rtl8192ce
E: ID_NET_LINK_FILE=/lib/systemd/network/99-default.link
E: ID_NET_NAME=wlp5s0
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/wlan0
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1c.2/pci_bus/0000:05
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.2/pci_bus/0000:05
E: SUBSYSTEM=pci_bus

P: /devices/pci0000:00/0000:00:1c.3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.3
E: SUBSYSTEM=pci
E: DRIVER=pcieport
E: PCI_CLASS=60400
E: PCI_ID=8086:3B48
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:1c.3
E: MODALIAS=pci:v00008086d00003B48sv00001558sd00005125bc06sc04i00
E: USEC_INITIALIZED=15747666
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=PCI bridge
E: ID_PCI_INTERFACE_FROM_DATABASE=Normal decode
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset PCI Express Root Port 4

P: /devices/pci0000:00/0000:00:1c.3/0000:00:1c.3:pcie010
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.3/0000:00:1c.3:pcie010
E: SUBSYSTEM=pci_express

P: /devices/pci0000:00/0000:00:1c.3/0000:06:00.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.3/0000:06:00.0
E: SUBSYSTEM=pci
E: DRIVER=jme
E: PCI_CLASS=20000
E: PCI_ID=197B:0250
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:06:00.0
E: MODALIAS=pci:v0000197Bd00000250sv00001558sd00005125bc02sc00i00
E: USEC_INITIALIZED=16087749
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=JMicron Technology Corp.
E: ID_MODEL_FROM_DATABASE=JMC250 PCI Express Gigabit Ethernet Controller

P: /devices/pci0000:00/0000:00:1c.3/0000:06:00.0/net/eth0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.3/0000:06:00.0/net/eth0
E: SUBSYSTEM=net
E: INTERFACE=eth0
E: IFINDEX=2
E: USEC_INITIALIZED=3675343
E: ID_NET_NAMING_SCHEME=v243
E: ID_NET_NAME_MAC=enx0040a7214fea
E: ID_OUI_FROM_DATABASE=ITAUTEC PHILCO S.A.
E: ID_NET_NAME_PATH=enp6s0f0
E: ID_BUS=pci
E: ID_VENDOR_ID=0x197b
E: ID_MODEL_ID=0x0250
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=JMicron Technology Corp.
E: ID_MODEL_FROM_DATABASE=JMC250 PCI Express Gigabit Ethernet Controller
E: ID_MM_CANDIDATE=1
E: ID_PATH=pci-0000:06:00.0
E: ID_PATH_TAG=pci-0000_06_00_0
E: ID_NET_DRIVER=jme
E: ID_NET_LINK_FILE=/lib/systemd/network/99-default.link
E: ID_NET_NAME=enp6s0f0
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/eth0
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1c.3/0000:06:00.1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.3/0000:06:00.1
E: SUBSYSTEM=pci
E: DRIVER=sdhci-pci
E: PCI_CLASS=88000
E: PCI_ID=197B:2392
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:06:00.1
E: MODALIAS=pci:v0000197Bd00002392sv00001558sd00005125bc08sc80i00
E: USEC_INITIALIZED=16087741
E: ID_PCI_CLASS_FROM_DATABASE=Generic system peripheral
E: ID_PCI_SUBCLASS_FROM_DATABASE=System peripheral
E: ID_VENDOR_FROM_DATABASE=JMicron Technology Corp.
E: ID_MODEL_FROM_DATABASE=SD/MMC Host Controller

P: /devices/pci0000:00/0000:00:1c.3/0000:06:00.1/leds/mmc0::
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.3/0000:06:00.1/leds/mmc0::
E: SUBSYSTEM=leds
E: USEC_INITIALIZED=16093024
E: ID_PATH=pci-0000:06:00.1
E: ID_PATH_TAG=pci-0000_06_00_1
E: ID_FOR_SEAT=leds-pci-0000_06_00_1
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1c.3/0000:06:00.1/mmc_host/mmc0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.3/0000:06:00.1/mmc_host/mmc0
E: SUBSYSTEM=mmc_host

P: /devices/pci0000:00/0000:00:1c.3/0000:06:00.2
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.3/0000:06:00.2
E: SUBSYSTEM=pci
E: PCI_CLASS=80501
E: PCI_ID=197B:2391
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:06:00.2
E: MODALIAS=pci:v0000197Bd00002391sv00001558sd00005125bc08sc05i01
E: USEC_INITIALIZED=16071370
E: ID_PCI_CLASS_FROM_DATABASE=Generic system peripheral
E: ID_PCI_SUBCLASS_FROM_DATABASE=SD Host controller
E: ID_VENDOR_FROM_DATABASE=JMicron Technology Corp.
E: ID_MODEL_FROM_DATABASE=Standard SD Host Controller

P: /devices/pci0000:00/0000:00:1c.3/0000:06:00.3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.3/0000:06:00.3
E: SUBSYSTEM=pci
E: DRIVER=jmb38x_ms
E: PCI_CLASS=88000
E: PCI_ID=197B:2393
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:06:00.3
E: MODALIAS=pci:v0000197Bd00002393sv00001558sd00005125bc08sc80i00
E: USEC_INITIALIZED=16070292
E: ID_PCI_CLASS_FROM_DATABASE=Generic system peripheral
E: ID_PCI_SUBCLASS_FROM_DATABASE=System peripheral
E: ID_VENDOR_FROM_DATABASE=JMicron Technology Corp.
E: ID_MODEL_FROM_DATABASE=MS Host Controller

P: /devices/pci0000:00/0000:00:1c.3/0000:06:00.3/memstick_host/memstick0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.3/0000:06:00.3/memstick_host/memstick0
E: SUBSYSTEM=memstick_host

P: /devices/pci0000:00/0000:00:1c.3/pci_bus/0000:06
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.3/pci_bus/0000:06
E: SUBSYSTEM=pci_bus

P: /devices/pci0000:00/0000:00:1d.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0
E: SUBSYSTEM=pci
E: DRIVER=ehci-pci
E: PCI_CLASS=C0320
E: PCI_ID=8086:3B34
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:1d.0
E: MODALIAS=pci:v00008086d00003B34sv00001558sd00005125bc0Csc03i20
E: USEC_INITIALIZED=15745281
E: ID_PCI_CLASS_FROM_DATABASE=Serial bus controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=USB controller
E: ID_PCI_INTERFACE_FROM_DATABASE=EHCI
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset USB2 Enhanced Host Controller

P: /devices/pci0000:00/0000:00:1d.0/usb2
N: bus/usb/002/001
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2
E: SUBSYSTEM=usb
E: DEVNAME=/dev/bus/usb/002/001
E: DEVTYPE=usb_device
E: DRIVER=usb
E: PRODUCT=1d6b/2/502
E: TYPE=9/0/0
E: BUSNUM=002
E: DEVNUM=001
E: MAJOR=189
E: MINOR=128
E: USEC_INITIALIZED=3701829
E: ID_VENDOR=Linux_5.2.0-3-amd64_ehci_hcd
E: ID_VENDOR_ENC=Linux\x205.2.0-3-amd64\x20ehci_hcd
E: ID_VENDOR_ID=1d6b
E: ID_MODEL=EHCI_Host_Controller
E: ID_MODEL_ENC=EHCI\x20Host\x20Controller
E: ID_MODEL_ID=0002
E: ID_REVISION=0502
E: ID_SERIAL=Linux_5.2.0-3-amd64_ehci_hcd_EHCI_Host_Controller_0000:00:1d.0
E: ID_SERIAL_SHORT=0000:00:1d.0
E: ID_BUS=usb
E: ID_USB_INTERFACES=:090000:
E: ID_VENDOR_FROM_DATABASE=Linux Foundation
E: ID_MODEL_FROM_DATABASE=2.0 root hub
E: ID_PATH=pci-0000:00:1d.0
E: ID_PATH_TAG=pci-0000_00_1d_0
E: ID_FOR_SEAT=usb-pci-0000_00_1d_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-0:1.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-0:1.0
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=hub
E: PRODUCT=1d6b/2/502
E: TYPE=9/0/0
E: INTERFACE=9/0/0
E: MODALIAS=usb:v1D6Bp0002d0502dc09dsc00dp00ic09isc00ip00in00
E: USEC_INITIALIZED=16627844
E: ID_USB_CLASS_FROM_DATABASE=Hub
E: ID_USB_PROTOCOL_FROM_DATABASE=Full speed (or root) hub
E: ID_VENDOR_FROM_DATABASE=Linux Foundation
E: ID_MODEL_FROM_DATABASE=2.0 root hub
E: ID_PATH=pci-0000:00:1d.0-usb-0:0:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_0_1_0

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1
N: bus/usb/002/002
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1
E: SUBSYSTEM=usb
E: DEVNAME=/dev/bus/usb/002/002
E: DEVTYPE=usb_device
E: DRIVER=usb
E: PRODUCT=8087/20/0
E: TYPE=9/0/1
E: BUSNUM=002
E: DEVNUM=002
E: MAJOR=189
E: MINOR=129
E: USEC_INITIALIZED=4504945
E: ID_VENDOR=8087
E: ID_VENDOR_ENC=8087
E: ID_VENDOR_ID=8087
E: ID_MODEL=0020
E: ID_MODEL_ENC=0020
E: ID_MODEL_ID=0020
E: ID_REVISION=0000
E: ID_SERIAL=8087_0020
E: ID_BUS=usb
E: ID_USB_INTERFACES=:090000:
E: ID_VENDOR_FROM_DATABASE=Intel Corp.
E: ID_MODEL_FROM_DATABASE=Integrated Rate Matching Hub
E: ID_PATH=pci-0000:00:1d.0-usb-0:1
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1
E: ID_FOR_SEAT=usb-pci-0000_00_1d_0-usb-0_1
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1
N: bus/usb/002/003
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1
E: SUBSYSTEM=usb
E: DEVNAME=/dev/bus/usb/002/003
E: DEVTYPE=usb_device
E: DRIVER=usb
E: PRODUCT=5e3/604/305
E: TYPE=9/0/0
E: BUSNUM=002
E: DEVNUM=003
E: MAJOR=189
E: MINOR=130
E: USEC_INITIALIZED=4951261
E: ID_VENDOR=05e3
E: ID_VENDOR_ENC=05e3
E: ID_VENDOR_ID=05e3
E: ID_MODEL=USB_Hub
E: ID_MODEL_ENC=USB\x20Hub
E: ID_MODEL_ID=0604
E: ID_REVISION=0305
E: ID_SERIAL=05e3_USB_Hub
E: ID_BUS=usb
E: ID_USB_INTERFACES=:090000:
E: ID_VENDOR_FROM_DATABASE=Genesys Logic, Inc.
E: ID_MODEL_FROM_DATABASE=USB 1.1 Hub
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1
E: ID_FOR_SEAT=usb-pci-0000_00_1d_0-usb-0_1_1
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1
N: bus/usb/002/005
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1
E: SUBSYSTEM=usb
E: DEVNAME=/dev/bus/usb/002/005
E: DEVTYPE=usb_device
E: DRIVER=usb
E: PRODUCT=1a2c/c23/110
E: TYPE=0/0/0
E: BUSNUM=002
E: DEVNUM=005
E: MAJOR=189
E: MINOR=132
E: USEC_INITIALIZED=5367132
E: ID_VENDOR=USB
E: ID_VENDOR_ENC=USB
E: ID_VENDOR_ID=1a2c
E: ID_MODEL=USB_Keyboard
E: ID_MODEL_ENC=USB\x20Keyboard
E: ID_MODEL_ID=0c23
E: ID_REVISION=0110
E: ID_SERIAL=USB_USB_Keyboard
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030101:030000:
E: ID_VENDOR_FROM_DATABASE=China Resource Semico Co., Ltd
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.1
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_1

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=usbhid
E: PRODUCT=1a2c/c23/110
E: TYPE=0/0/0
E: INTERFACE=3/1/1
E: MODALIAS=usb:v1A2Cp0C23d0110dc00dsc00dp00ic03isc01ip01in00
E: USEC_INITIALIZED=17607223
E: ID_VENDOR_FROM_DATABASE=China Resource Semico Co., Ltd
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.1:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_1_1_0

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001
E: SUBSYSTEM=hid
E: DRIVER=hid-generic
E: HID_ID=0003:00001A2C:00000C23
E: HID_NAME=USB USB Keyboard
E: HID_PHYS=usb-0000:00:1d.0-1.1.1/input0
E: HID_UNIQ=
E: MODALIAS=hid:b0003g0001v00001A2Cp00000C23

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001/hidraw/hidraw0
N: hidraw0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001/hidraw/hidraw0
E: SUBSYSTEM=hidraw
E: DEVNAME=/dev/hidraw0
E: MAJOR=248
E: MINOR=0

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001/input/input16
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001/input/input16
E: SUBSYSTEM=input
E: PRODUCT=3/1a2c/c23/110
E: NAME="USB USB Keyboard"
E: PHYS="usb-0000:00:1d.0-1.1.1/input0"
E: UNIQ=""
E: PROP=0
E: EV=120013
E: KEY=1000000000007 ff800000000007ff febeffdff3cfffff fffffffffffffffe
E: MSC=10
E: LED=7
E: MODALIAS=input:b0003v1A2Cp0C23e0110-e0,1,4,11,14,k71,72,73,74,75,77,79,7A,7B,7C,7D,7E,7F,80,81,82,83,84,85,86,87,88,89,8A,B7,B8,B9,BA,BB,BC,BD,BE,BF,C0,C1,C2,F0,ram4,l0,1,2,sfw
E: USEC_INITIALIZED=5505297
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_VENDOR=USB
E: ID_VENDOR_ENC=USB
E: ID_VENDOR_ID=1a2c
E: ID_MODEL=USB_Keyboard
E: ID_MODEL_ENC=USB\x20Keyboard
E: ID_MODEL_ID=0c23
E: ID_REVISION=0110
E: ID_SERIAL=USB_USB_Keyboard
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030101:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.1:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_1_1_0
E: ID_FOR_SEAT=input-pci-0000_00_1d_0-usb-0_1_1_1_1_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001/input/input16/event7
N: input/event7
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001/input/input16/event7
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event7
E: MAJOR=13
E: MINOR=71

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001/input/input16/input16::capslock
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001/input/input16/input16::capslock
E: SUBSYSTEM=leds
E: USEC_INITIALIZED=17653351
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.1:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_1_1_0
E: ID_FOR_SEAT=leds-pci-0000_00_1d_0-usb-0_1_1_1_1_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001/input/input16/input16::numlock
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001/input/input16/input16::numlock
E: SUBSYSTEM=leds
E: USEC_INITIALIZED=17656400
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.1:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_1_1_0
E: ID_FOR_SEAT=leds-pci-0000_00_1d_0-usb-0_1_1_1_1_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001/input/input16/input16::scrolllock
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.0/0003:1A2C:0C23.0001/input/input16/input16::scrolllock
E: SUBSYSTEM=leds
E: USEC_INITIALIZED=17657806
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.1:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_1_1_0
E: ID_FOR_SEAT=leds-pci-0000_00_1d_0-usb-0_1_1_1_1_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=usbhid
E: PRODUCT=1a2c/c23/110
E: TYPE=0/0/0
E: INTERFACE=3/0/0
E: MODALIAS=usb:v1A2Cp0C23d0110dc00dsc00dp00ic03isc00ip00in01
E: USEC_INITIALIZED=17614138
E: ID_VENDOR_FROM_DATABASE=China Resource Semico Co., Ltd
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.1:1.1
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_1_1_1

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1/0003:1A2C:0C23.0002
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1/0003:1A2C:0C23.0002
E: SUBSYSTEM=hid
E: DRIVER=hid-generic
E: HID_ID=0003:00001A2C:00000C23
E: HID_NAME=USB USB Keyboard
E: HID_PHYS=usb-0000:00:1d.0-1.1.1/input1
E: HID_UNIQ=
E: MODALIAS=hid:b0003g0001v00001A2Cp00000C23

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1/0003:1A2C:0C23.0002/hidraw/hidraw1
N: hidraw1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1/0003:1A2C:0C23.0002/hidraw/hidraw1
E: SUBSYSTEM=hidraw
E: DEVNAME=/dev/hidraw1
E: MAJOR=248
E: MINOR=1

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1/0003:1A2C:0C23.0002/input/input17
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1/0003:1A2C:0C23.0002/input/input17
E: SUBSYSTEM=input
E: PRODUCT=3/1a2c/c23/110
E: NAME="USB USB Keyboard Consumer Control"
E: PHYS="usb-0000:00:1d.0-1.1.1/input1"
E: UNIQ=""
E: PROP=0
E: EV=1f
E: KEY=300ff 0 0 483ffff17aff32d bfd4444600000000 1 130c730b17c000 267bfad9415fed 9e168000004400 10000002
E: REL=1040
E: ABS=100000000
E: MSC=10
E: MODALIAS=input:b0003v1A2Cp0C23e0110-e0,1,2,3,4,k71,72,73,74,77,80,82,83,85,86,87,88,89,8A,8B,8C,8E,90,96,98,9B,9C,9E,9F,A1,A3,A4,A5,A6,A7,A8,A9,AB,AC,AD,AE,B1,B2,B5,CE,CF,D0,D1,D2,D4,D8,D9,DB,E0,E1,E4,E5,E6,EA,EB,F0,F1,F4,100,161,162,166,16A,16E,172,174,176,177,178,179,17A,17B,17C,17D,17F,180,182,183,185,188,189,18C,18D,18E,18F,190,191,192,193,195,197,198,199,19A,19C,1A0,1A1,1A2,1A3,1A4,1A5,1A6,1A7,1A8,1A9,1AA,1AB,1AC,1AD,1AE,1AF,1B0,1B1,1B7,1BA,240,241,242,243,244,245,246,247,250,251,r6,C,a20,m4,lsfw
E: USEC_INITIALIZED=5506042
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_VENDOR=USB
E: ID_VENDOR_ENC=USB
E: ID_VENDOR_ID=1a2c
E: ID_MODEL=USB_Keyboard
E: ID_MODEL_ENC=USB\x20Keyboard
E: ID_MODEL_ID=0c23
E: ID_REVISION=0110
E: ID_SERIAL=USB_USB_Keyboard
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030101:030000:
E: ID_USB_INTERFACE_NUM=01
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.1:1.1
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_1_1_1
E: ID_FOR_SEAT=input-pci-0000_00_1d_0-usb-0_1_1_1_1_1
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1/0003:1A2C:0C23.0002/input/input17/event8
N: input/event8
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1/0003:1A2C:0C23.0002/input/input17/event8
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event8
E: MAJOR=13
E: MINOR=72

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1/0003:1A2C:0C23.0002/input/input18
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1/0003:1A2C:0C23.0002/input/input18
E: SUBSYSTEM=input
E: PRODUCT=3/1a2c/c23/110
E: NAME="USB USB Keyboard System Control"
E: PHYS="usb-0000:00:1d.0-1.1.1/input1"
E: UNIQ=""
E: PROP=0
E: EV=13
E: KEY=c000 10000000000000 0
E: MSC=10
E: MODALIAS=input:b0003v1A2Cp0C23e0110-e0,1,4,k74,8E,8F,ram4,lsfw
E: USEC_INITIALIZED=5505518
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_VENDOR=USB
E: ID_VENDOR_ENC=USB
E: ID_VENDOR_ID=1a2c
E: ID_MODEL=USB_Keyboard
E: ID_MODEL_ENC=USB\x20Keyboard
E: ID_MODEL_ID=0c23
E: ID_REVISION=0110
E: ID_SERIAL=USB_USB_Keyboard
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030101:030000:
E: ID_USB_INTERFACE_NUM=01
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.1:1.1
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_1_1_1
E: ID_FOR_SEAT=input-pci-0000_00_1d_0-usb-0_1_1_1_1_1
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1/0003:1A2C:0C23.0002/input/input18/event9
N: input/event9
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.1/2-1.1.1:1.1/0003:1A2C:0C23.0002/input/input18/event9
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event9
E: MAJOR=13
E: MINOR=73

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2
N: bus/usb/002/006
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2
E: SUBSYSTEM=usb
E: DEVNAME=/dev/bus/usb/002/006
E: DEVTYPE=usb_device
E: DRIVER=usb
E: PRODUCT=8bb/2704/100
E: TYPE=0/0/0
E: BUSNUM=002
E: DEVNUM=006
E: MAJOR=189
E: MINOR=133
E: USEC_INITIALIZED=5616661
E: ID_VENDOR=Burr-Brown_from_TI
E: ID_VENDOR_ENC=Burr-Brown\x20from\x20TI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_VENDOR_ID=08bb
E: ID_MODEL=USB_Audio_DAC
E: ID_MODEL_ENC=USB\x20Audio\x20DAC\x20\x20\x20
E: ID_MODEL_ID=2704
E: ID_REVISION=0100
E: ID_SERIAL=Burr-Brown_from_TI_USB_Audio_DAC
E: ID_BUS=usb
E: ID_USB_INTERFACES=:010100:010200:030000:
E: ID_VENDOR_FROM_DATABASE=Texas Instruments
E: ID_MODEL_FROM_DATABASE=PCM2704 16-bit stereo audio DAC
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.2
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_2

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.0
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=snd-usb-audio
E: PRODUCT=8bb/2704/100
E: TYPE=0/0/0
E: INTERFACE=1/1/0
E: MODALIAS=usb:v08BBp2704d0100dc00dsc00dp00ic01isc01ip00in00
E: USEC_INITIALIZED=17609618
E: ID_VENDOR_FROM_DATABASE=Texas Instruments
E: ID_MODEL_FROM_DATABASE=PCM2704 16-bit stereo audio DAC
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.2:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_2_1_0

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.0/sound/card1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.0/sound/card1
E: SUBSYSTEM=sound
E: USEC_INITIALIZED=18338196
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.2:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_2_1_0
E: ID_FOR_SEAT=sound-pci-0000_00_1d_0-usb-0_1_1_2_1_0
E: SOUND_INITIALIZED=1
E: ID_VENDOR_FROM_DATABASE=Texas Instruments
E: ID_MODEL_FROM_DATABASE=PCM2704 16-bit stereo audio DAC
E: ID_VENDOR=Burr-Brown_from_TI
E: ID_VENDOR_ENC=Burr-Brown\x20from\x20TI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_VENDOR_ID=08bb
E: ID_MODEL=USB_Audio_DAC
E: ID_MODEL_ENC=USB\x20Audio\x20DAC\x20\x20\x20
E: ID_MODEL_ID=2704
E: ID_REVISION=0100
E: ID_SERIAL=Burr-Brown_from_TI_USB_Audio_DAC
E: ID_TYPE=audio
E: ID_BUS=usb
E: ID_USB_INTERFACES=:010100:010200:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=snd-usb-audio
E: ID_ID=usb-Burr-Brown_from_TI_USB_Audio_DAC-00
E: SYSTEMD_WANTS=sound.target
E: SYSTEMD_USER_WANTS=sound.target
E: TAGS=:seat:systemd:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.0/sound/card1/pcmC1D0p
N: snd/pcmC1D0p
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.0/sound/card1/pcmC1D0p
E: SUBSYSTEM=sound
E: DEVNAME=/dev/snd/pcmC1D0p
E: DEVTYPE=pcm
E: MAJOR=116
E: MINOR=10
E: USEC_INITIALIZED=18346377
E: TAGS=:uaccess:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.0/sound/card1/controlC1
N: snd/controlC1
L: 0
S: snd/by-id/usb-Burr-Brown_from_TI_USB_Audio_DAC-00
S: snd/by-path/pci-0000:00:1d.0-usb-0:1.1.2:1.0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.0/sound/card1/controlC1
E: SUBSYSTEM=sound
E: DEVNAME=/dev/snd/controlC1
E: MAJOR=116
E: MINOR=11
E: USEC_INITIALIZED=18347669
E: ID_VENDOR=Burr-Brown_from_TI
E: ID_VENDOR_ENC=Burr-Brown\x20from\x20TI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_VENDOR_ID=08bb
E: ID_MODEL=USB_Audio_DAC
E: ID_MODEL_ENC=USB\x20Audio\x20DAC\x20\x20\x20
E: ID_MODEL_ID=2704
E: ID_REVISION=0100
E: ID_SERIAL=Burr-Brown_from_TI_USB_Audio_DAC
E: ID_TYPE=audio
E: ID_BUS=usb
E: ID_USB_INTERFACES=:010100:010200:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=snd-usb-audio
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.2:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_2_1_0
E: DEVLINKS=/dev/snd/by-id/usb-Burr-Brown_from_TI_USB_Audio_DAC-00 /dev/snd/by-path/pci-0000:00:1d.0-usb-0:1.1.2:1.0
E: TAGS=:uaccess:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.1
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=snd-usb-audio
E: PRODUCT=8bb/2704/100
E: TYPE=0/0/0
E: INTERFACE=1/2/0
E: MODALIAS=usb:v08BBp2704d0100dc00dsc00dp00ic01isc02ip00in01
E: USEC_INITIALIZED=17618224
E: ID_VENDOR_FROM_DATABASE=Texas Instruments
E: ID_MODEL_FROM_DATABASE=PCM2704 16-bit stereo audio DAC
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.2:1.1
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_2_1_1

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.2
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.2
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=usbhid
E: PRODUCT=8bb/2704/100
E: TYPE=0/0/0
E: INTERFACE=3/0/0
E: MODALIAS=usb:v08BBp2704d0100dc00dsc00dp00ic03isc00ip00in02
E: USEC_INITIALIZED=17618402
E: ID_VENDOR_FROM_DATABASE=Texas Instruments
E: ID_MODEL_FROM_DATABASE=PCM2704 16-bit stereo audio DAC
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.2:1.2
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_2_1_2

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.2/0003:08BB:2704.0003
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.2/0003:08BB:2704.0003
E: SUBSYSTEM=hid
E: DRIVER=hid-generic
E: HID_ID=0003:000008BB:00002704
E: HID_NAME=Burr-Brown from TI               USB Audio DAC   
E: HID_PHYS=usb-0000:00:1d.0-1.1.2/input2
E: HID_UNIQ=
E: MODALIAS=hid:b0003g0001v000008BBp00002704

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.2/0003:08BB:2704.0003/hidraw/hidraw2
N: hidraw2
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.2/0003:08BB:2704.0003/hidraw/hidraw2
E: SUBSYSTEM=hidraw
E: DEVNAME=/dev/hidraw2
E: MAJOR=248
E: MINOR=2

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.2/0003:08BB:2704.0003/input/input19
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.2/0003:08BB:2704.0003/input/input19
E: SUBSYSTEM=input
E: PRODUCT=3/8bb/2704/100
E: NAME="Burr-Brown from TI               USB Audio DAC   "
E: PHYS="usb-0000:00:1d.0-1.1.2/input2"
E: UNIQ=""
E: PROP=0
E: EV=13
E: KEY=8 0 0 0 7800000000 e000000000000 0
E: MSC=10
E: MODALIAS=input:b0003v08BBp2704e0100-e0,1,4,k71,72,73,A3,A4,A5,A6,183,ram4,lsfw
E: USEC_INITIALIZED=5618815
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_VENDOR=Burr-Brown_from_TI
E: ID_VENDOR_ENC=Burr-Brown\x20from\x20TI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_VENDOR_ID=08bb
E: ID_MODEL=USB_Audio_DAC
E: ID_MODEL_ENC=USB\x20Audio\x20DAC\x20\x20\x20
E: ID_MODEL_ID=2704
E: ID_REVISION=0100
E: ID_SERIAL=Burr-Brown_from_TI_USB_Audio_DAC
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:010100:010200:030000:
E: ID_USB_INTERFACE_NUM=02
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.2:1.2
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_2_1_2
E: ID_FOR_SEAT=input-pci-0000_00_1d_0-usb-0_1_1_2_1_2
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.2/0003:08BB:2704.0003/input/input19/event10
N: input/event10
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.2/2-1.1.2:1.2/0003:08BB:2704.0003/input/input19/event10
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event10
E: MAJOR=13
E: MINOR=74

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3
N: bus/usb/002/007
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3
E: SUBSYSTEM=usb
E: DEVNAME=/dev/bus/usb/002/007
E: DEVTYPE=usb_device
E: DRIVER=usb
E: PRODUCT=275d/ba6/100
E: TYPE=0/0/0
E: BUSNUM=002
E: DEVNUM=007
E: MAJOR=189
E: MINOR=134
E: USEC_INITIALIZED=5811108
E: ID_VENDOR=275d
E: ID_VENDOR_ENC=275d
E: ID_VENDOR_ID=275d
E: ID_MODEL=USB_OPTICAL_MOUSE
E: ID_MODEL_ENC=USB\x20OPTICAL\x20MOUSE\x20
E: ID_MODEL_ID=0ba6
E: ID_REVISION=0100
E: ID_SERIAL=275d_USB_OPTICAL_MOUSE
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030102:
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.3
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_3

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3/2-1.1.3:1.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3/2-1.1.3:1.0
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=usbhid
E: PRODUCT=275d/ba6/100
E: TYPE=0/0/0
E: INTERFACE=3/1/2
E: MODALIAS=usb:v275Dp0BA6d0100dc00dsc00dp00ic03isc01ip02in00
E: USEC_INITIALIZED=17608060
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.3:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_3_1_0

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3/2-1.1.3:1.0/0003:275D:0BA6.0004
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3/2-1.1.3:1.0/0003:275D:0BA6.0004
E: SUBSYSTEM=hid
E: DRIVER=hid-generic
E: HID_ID=0003:0000275D:00000BA6
E: HID_NAME=USB OPTICAL MOUSE 
E: HID_PHYS=usb-0000:00:1d.0-1.1.3/input0
E: HID_UNIQ=
E: MODALIAS=hid:b0003g0001v0000275Dp00000BA6

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3/2-1.1.3:1.0/0003:275D:0BA6.0004/hidraw/hidraw3
N: hidraw3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3/2-1.1.3:1.0/0003:275D:0BA6.0004/hidraw/hidraw3
E: SUBSYSTEM=hidraw
E: DEVNAME=/dev/hidraw3
E: MAJOR=248
E: MINOR=3

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3/2-1.1.3:1.0/0003:275D:0BA6.0004/input/input20
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3/2-1.1.3:1.0/0003:275D:0BA6.0004/input/input20
E: SUBSYSTEM=input
E: PRODUCT=3/275d/ba6/111
E: NAME="USB OPTICAL MOUSE "
E: PHYS="usb-0000:00:1d.0-1.1.3/input0"
E: UNIQ=""
E: PROP=0
E: EV=17
E: KEY=70000 0 0 0 0
E: REL=903
E: MSC=10
E: MODALIAS=input:b0003v275Dp0BA6e0111-e0,1,2,4,k110,111,112,r0,1,8,B,am4,lsfw
E: USEC_INITIALIZED=5813508
E: ID_INPUT=1
E: ID_INPUT_MOUSE=1
E: ID_VENDOR=275d
E: ID_VENDOR_ENC=275d
E: ID_VENDOR_ID=275d
E: ID_MODEL=USB_OPTICAL_MOUSE
E: ID_MODEL_ENC=USB\x20OPTICAL\x20MOUSE\x20
E: ID_MODEL_ID=0ba6
E: ID_REVISION=0100
E: ID_SERIAL=275d_USB_OPTICAL_MOUSE
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030102:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.3:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_3_1_0
E: ID_FOR_SEAT=input-pci-0000_00_1d_0-usb-0_1_1_3_1_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3/2-1.1.3:1.0/0003:275D:0BA6.0004/input/input20/event11
N: input/event11
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3/2-1.1.3:1.0/0003:275D:0BA6.0004/input/input20/event11
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event11
E: MAJOR=13
E: MINOR=75

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3/2-1.1.3:1.0/0003:275D:0BA6.0004/input/input20/mouse1
N: input/mouse1
L: 0
S: input/by-id/usb-275d_USB_OPTICAL_MOUSE-mouse
S: input/by-path/pci-0000:00:1d.0-usb-0:1.1.3:1.0-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1.3/2-1.1.3:1.0/0003:275D:0BA6.0004/input/input20/mouse1
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/mouse1
E: MAJOR=13
E: MINOR=33
E: USEC_INITIALIZED=17631173
E: ID_INPUT=1
E: ID_INPUT_MOUSE=1
E: ID_VENDOR=275d
E: ID_VENDOR_ENC=275d
E: ID_VENDOR_ID=275d
E: ID_MODEL=USB_OPTICAL_MOUSE
E: ID_MODEL_ENC=USB\x20OPTICAL\x20MOUSE\x20
E: ID_MODEL_ID=0ba6
E: ID_REVISION=0100
E: ID_SERIAL=275d_USB_OPTICAL_MOUSE
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030102:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1.3:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_3_1_0
E: DEVLINKS=/dev/input/by-id/usb-275d_USB_OPTICAL_MOUSE-mouse /dev/input/by-path/pci-0000:00:1d.0-usb-0:1.1.3:1.0-mouse

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1:1.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1:1.0
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=hub
E: PRODUCT=5e3/604/305
E: TYPE=9/0/0
E: INTERFACE=9/0/0
E: MODALIAS=usb:v05E3p0604d0305dc09dsc00dp00ic09isc00ip00in00
E: USEC_INITIALIZED=16908202
E: ID_USB_CLASS_FROM_DATABASE=Hub
E: ID_USB_PROTOCOL_FROM_DATABASE=Full speed (or root) hub
E: ID_VENDOR_FROM_DATABASE=Genesys Logic, Inc.
E: ID_MODEL_FROM_DATABASE=USB 1.1 Hub
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.1:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_1_0

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6
N: bus/usb/002/004
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6
E: SUBSYSTEM=usb
E: DEVNAME=/dev/bus/usb/002/004
E: DEVTYPE=usb_device
E: DRIVER=usb
E: PRODUCT=5986/241/602
E: TYPE=239/2/1
E: BUSNUM=002
E: DEVNUM=004
E: MAJOR=189
E: MINOR=131
E: USEC_INITIALIZED=5349518
E: ID_VENDOR=BISON_Corporation
E: ID_VENDOR_ENC=BISON\x20Corporation
E: ID_VENDOR_ID=5986
E: ID_MODEL=BisonCam__NB_Pro
E: ID_MODEL_ENC=BisonCam\x2c\x20NB\x20Pro
E: ID_MODEL_ID=0241
E: ID_REVISION=0602
E: ID_SERIAL=BISON_Corporation_BisonCam__NB_Pro
E: ID_BUS=usb
E: ID_USB_INTERFACES=:0e0100:0e0200:
E: ID_VENDOR_FROM_DATABASE=Acer, Inc
E: ID_MODEL_FROM_DATABASE=BisonCam, NB Pro
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.6
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_6

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=uvcvideo
E: PRODUCT=5986/241/602
E: TYPE=239/2/1
E: INTERFACE=14/1/0
E: MODALIAS=usb:v5986p0241d0602dcEFdsc02dp01ic0Eisc01ip00in00
E: USEC_INITIALIZED=17629209
E: ID_USB_CLASS_FROM_DATABASE=Miscellaneous Device
E: ID_USB_PROTOCOL_FROM_DATABASE=Interface Association
E: ID_VENDOR_FROM_DATABASE=Acer, Inc
E: ID_MODEL_FROM_DATABASE=BisonCam, NB Pro
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.6:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_6_1_0

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/input/input28
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/input/input28
E: SUBSYSTEM=input
E: PRODUCT=3/5986/241/602
E: NAME="BisonCam, NB Pro: BisonCam, NB "
E: PHYS="usb-0000:00:1d.0-1.6/button"
E: PROP=0
E: EV=3
E: KEY=100000 0 0 0
E: MODALIAS=input:b0003v5986p0241e0602-e0,1,kD4,ramlsfw
E: USEC_INITIALIZED=18300535
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_VENDOR=BISON_Corporation
E: ID_VENDOR_ENC=BISON\x20Corporation
E: ID_VENDOR_ID=5986
E: ID_MODEL=BisonCam__NB_Pro
E: ID_MODEL_ENC=BisonCam\x2c\x20NB\x20Pro
E: ID_MODEL_ID=0241
E: ID_REVISION=0602
E: ID_SERIAL=BISON_Corporation_BisonCam__NB_Pro
E: ID_TYPE=video
E: ID_BUS=usb
E: ID_USB_INTERFACES=:0e0100:0e0200:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=uvcvideo
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.6:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_6_1_0
E: ID_FOR_SEAT=input-pci-0000_00_1d_0-usb-0_1_6_1_0
E: TAGS=:seat:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/input/input28/event19
N: input/event19
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/input/input28/event19
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event19
E: MAJOR=13
E: MINOR=83

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/media0
N: media0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/media0
E: SUBSYSTEM=media
E: DEVNAME=/dev/media0
E: MAJOR=245
E: MINOR=0

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/video4linux/video0
N: video0
L: 0
S: v4l/by-id/usb-BISON_Corporation_BisonCam__NB_Pro-video-index0
S: v4l/by-path/pci-0000:00:1d.0-usb-0:1.6:1.0-video-index0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/video4linux/video0
E: SUBSYSTEM=video4linux
E: DEVNAME=/dev/video0
E: MAJOR=81
E: MINOR=0
E: USEC_INITIALIZED=18389569
E: ID_V4L_VERSION=2
E: ID_V4L_PRODUCT=BisonCam, NB Pro: BisonCam, NB
E: ID_V4L_CAPABILITIES=:capture:
E: ID_VENDOR=BISON_Corporation
E: ID_VENDOR_ENC=BISON\x20Corporation
E: ID_VENDOR_ID=5986
E: ID_MODEL=BisonCam__NB_Pro
E: ID_MODEL_ENC=BisonCam\x2c\x20NB\x20Pro
E: ID_MODEL_ID=0241
E: ID_REVISION=0602
E: ID_SERIAL=BISON_Corporation_BisonCam__NB_Pro
E: ID_TYPE=video
E: ID_BUS=usb
E: ID_USB_INTERFACES=:0e0100:0e0200:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=uvcvideo
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.6:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_6_1_0
E: ID_FOR_SEAT=video4linux-pci-0000_00_1d_0-usb-0_1_6_1_0
E: COLORD_DEVICE=1
E: COLORD_KIND=camera
E: DEVLINKS=/dev/v4l/by-id/usb-BISON_Corporation_BisonCam__NB_Pro-video-index0 /dev/v4l/by-path/pci-0000:00:1d.0-usb-0:1.6:1.0-video-index0
E: TAGS=:seat:uaccess:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/video4linux/video1
N: video1
L: 0
S: v4l/by-path/pci-0000:00:1d.0-usb-0:1.6:1.0-video-index1
S: v4l/by-id/usb-BISON_Corporation_BisonCam__NB_Pro-video-index1
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/video4linux/video1
E: SUBSYSTEM=video4linux
E: DEVNAME=/dev/video1
E: MAJOR=81
E: MINOR=1
E: USEC_INITIALIZED=18387479
E: ID_V4L_VERSION=2
E: ID_V4L_PRODUCT=BisonCam, NB Pro: BisonCam, NB
E: ID_V4L_CAPABILITIES=:
E: ID_VENDOR=BISON_Corporation
E: ID_VENDOR_ENC=BISON\x20Corporation
E: ID_VENDOR_ID=5986
E: ID_MODEL=BisonCam__NB_Pro
E: ID_MODEL_ENC=BisonCam\x2c\x20NB\x20Pro
E: ID_MODEL_ID=0241
E: ID_REVISION=0602
E: ID_SERIAL=BISON_Corporation_BisonCam__NB_Pro
E: ID_TYPE=video
E: ID_BUS=usb
E: ID_USB_INTERFACES=:0e0100:0e0200:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=uvcvideo
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.6:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_6_1_0
E: ID_FOR_SEAT=video4linux-pci-0000_00_1d_0-usb-0_1_6_1_0
E: COLORD_DEVICE=1
E: COLORD_KIND=camera
E: DEVLINKS=/dev/v4l/by-path/pci-0000:00:1d.0-usb-0:1.6:1.0-video-index1 /dev/v4l/by-id/usb-BISON_Corporation_BisonCam__NB_Pro-video-index1
E: TAGS=:seat:uaccess:

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.1
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=uvcvideo
E: PRODUCT=5986/241/602
E: TYPE=239/2/1
E: INTERFACE=14/2/0
E: MODALIAS=usb:v5986p0241d0602dcEFdsc02dp01ic0Eisc02ip00in01
E: USEC_INITIALIZED=17636171
E: ID_USB_CLASS_FROM_DATABASE=Miscellaneous Device
E: ID_USB_PROTOCOL_FROM_DATABASE=Interface Association
E: ID_VENDOR_FROM_DATABASE=Acer, Inc
E: ID_MODEL_FROM_DATABASE=BisonCam, NB Pro
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.6:1.1
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_6_1_1

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1:1.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1:1.0
E: SUBSYSTEM=usb
E: DEVTYPE=usb_interface
E: DRIVER=hub
E: PRODUCT=8087/20/0
E: TYPE=9/0/1
E: INTERFACE=9/0/0
E: MODALIAS=usb:v8087p0020d0000dc09dsc00dp01ic09isc00ip00in00
E: USEC_INITIALIZED=16700419
E: ID_USB_CLASS_FROM_DATABASE=Hub
E: ID_USB_PROTOCOL_FROM_DATABASE=Single TT
E: ID_VENDOR_FROM_DATABASE=Intel Corp.
E: ID_MODEL_FROM_DATABASE=Integrated Rate Matching Hub
E: ID_PATH=pci-0000:00:1d.0-usb-0:1:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_1_0

P: /devices/pci0000:00/0000:00:1e.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1e.0
E: SUBSYSTEM=pci
E: PCI_CLASS=60401
E: PCI_ID=8086:2448
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:1e.0
E: MODALIAS=pci:v00008086d00002448sv00001558sd00005125bc06sc04i01
E: USEC_INITIALIZED=16239533
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=PCI bridge
E: ID_PCI_INTERFACE_FROM_DATABASE=Subtractive decode
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=82801 Mobile PCI Bridge

P: /devices/pci0000:00/0000:00:1e.0/pci_bus/0000:07
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1e.0/pci_bus/0000:07
E: SUBSYSTEM=pci_bus

P: /devices/pci0000:00/0000:00:1f.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.0
E: SUBSYSTEM=pci
E: DRIVER=lpc_ich
E: PCI_CLASS=60100
E: PCI_ID=8086:3B09
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:1f.0
E: MODALIAS=pci:v00008086d00003B09sv00001558sd00005125bc06sc01i00
E: USEC_INITIALIZED=15893494
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=ISA bridge
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=HM55 Chipset LPC Interface Controller

P: /devices/pci0000:00/0000:00:1f.0/INT0800:00
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.0/INT0800:00
E: SUBSYSTEM=platform
E: MODALIAS=acpi:INT0800:
E: USEC_INITIALIZED=15903520
E: ID_VENDOR_FROM_DATABASE=Interphase Corporation
E: ID_PATH=pci-0000:00:1f.0-platform-INT0800:00
E: ID_PATH_TAG=pci-0000_00_1f_0-platform-INT0800_00

P: /devices/pci0000:00/0000:00:1f.0/PNP0103:00
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.0/PNP0103:00
E: SUBSYSTEM=platform
E: MODALIAS=acpi:PNP0103:
E: USEC_INITIALIZED=15903502
E: ID_PATH=pci-0000:00:1f.0-platform-PNP0103:00
E: ID_PATH_TAG=pci-0000_00_1f_0-platform-PNP0103_00

P: /devices/pci0000:00/0000:00:1f.0/PNP0C04:00
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.0/PNP0C04:00
E: SUBSYSTEM=platform
E: MODALIAS=acpi:PNP0C04:
E: USEC_INITIALIZED=15904853
E: ID_PATH=pci-0000:00:1f.0-platform-PNP0C04:00
E: ID_PATH_TAG=pci-0000_00_1f_0-platform-PNP0C04_00

P: /devices/pci0000:00/0000:00:1f.0/PNP0C09:00
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.0/PNP0C09:00
E: SUBSYSTEM=platform
E: MODALIAS=acpi:PNP0C09:
E: USEC_INITIALIZED=15904834
E: ID_PATH=pci-0000:00:1f.0-platform-PNP0C09:00
E: ID_PATH_TAG=pci-0000_00_1f_0-platform-PNP0C09_00

P: /devices/pci0000:00/0000:00:1f.0/iTCO_wdt.0.auto
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.0/iTCO_wdt.0.auto
E: SUBSYSTEM=platform
E: DEVTYPE=mfd_device
E: DRIVER=iTCO_wdt
E: MODALIAS=platform:iTCO_wdt
E: USEC_INITIALIZED=15906123
E: ID_PATH=pci-0000:00:1f.0-platform-iTCO_wdt.0.auto
E: ID_PATH_TAG=pci-0000_00_1f_0-platform-iTCO_wdt_0_auto

P: /devices/pci0000:00/0000:00:1f.0/iTCO_wdt.0.auto/misc/watchdog
N: watchdog
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.0/iTCO_wdt.0.auto/misc/watchdog
E: SUBSYSTEM=misc
E: DEVNAME=/dev/watchdog
E: MAJOR=10
E: MINOR=130

P: /devices/pci0000:00/0000:00:1f.0/iTCO_wdt.0.auto/watchdog/watchdog0
N: watchdog0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.0/iTCO_wdt.0.auto/watchdog/watchdog0
E: SUBSYSTEM=watchdog
E: DEVNAME=/dev/watchdog0
E: MAJOR=246
E: MINOR=0

P: /devices/pci0000:00/0000:00:1f.2
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2
E: SUBSYSTEM=pci
E: DRIVER=ahci
E: PCI_CLASS=10601
E: PCI_ID=8086:3B29
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:1f.2
E: MODALIAS=pci:v00008086d00003B29sv00001558sd00005125bc01sc06i01
E: USEC_INITIALIZED=15894707
E: ID_PCI_CLASS_FROM_DATABASE=Mass storage controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=SATA controller
E: ID_PCI_INTERFACE_FROM_DATABASE=AHCI 1.0
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset 4 port SATA AHCI Controller

P: /devices/pci0000:00/0000:00:1f.2/ata1/ata_port/ata1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/ata_port/ata1
E: SUBSYSTEM=ata_port

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0
E: SUBSYSTEM=scsi
E: DEVTYPE=scsi_host

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/scsi_host/host0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/scsi_host/host0
E: SUBSYSTEM=scsi_host

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0
E: SUBSYSTEM=scsi
E: DEVTYPE=scsi_target

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0
E: SUBSYSTEM=scsi
E: DEVTYPE=scsi_device
E: DRIVER=sd
E: MODALIAS=scsi:t-0x00

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
N: sda
L: 0
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745
S: disk/by-id/wwn-0x50024e9400bbadf8
S: disk/by-path/pci-0000:00:1f.2-ata-1
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda
E: DEVTYPE=disk
E: MAJOR=8
E: MINOR=0
E: USEC_INITIALIZED=5156370
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION_TABLE=1
E: UDISKS_PARTITION_TABLE_SCHEME=mbr
E: UDISKS_PARTITION_TABLE_COUNT=12
E: UDISKS_ATA_SMART_IS_AVAILABLE=1
E: DEVLINKS=/dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745 /dev/disk/by-id/wwn-0x50024e9400bbadf8 /dev/disk/by-path/pci-0000:00:1f.2-ata-1
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda1
N: sda1
L: 0
S: disk/by-id/wwn-0x50024e9400bbadf8-part1
S: disk/by-partuuid/8dad9926-01
S: disk/by-label/SYSTEM_BOOT
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part1
S: disk/by-uuid/6CC6502FC64FF7BA
S: disk/by-path/pci-0000:00:1f.2-ata-1-part1
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda1
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda1
E: DEVTYPE=partition
E: PARTN=1
E: MAJOR=8
E: MINOR=1
E: USEC_INITIALIZED=6536655
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: ID_FS_LABEL=SYSTEM_BOOT
E: ID_FS_LABEL_ENC=SYSTEM_BOOT
E: ID_FS_UUID=6CC6502FC64FF7BA
E: ID_FS_UUID_ENC=6CC6502FC64FF7BA
E: ID_FS_TYPE=ntfs
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=8dad9926-01
E: ID_PART_ENTRY_TYPE=0x7
E: ID_PART_ENTRY_FLAGS=0x80
E: ID_PART_ENTRY_NUMBER=1
E: ID_PART_ENTRY_OFFSET=2048
E: ID_PART_ENTRY_SIZE=204800
E: ID_PART_ENTRY_DISK=8:0
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION=1
E: UDISKS_PARTITION_SCHEME=mbr
E: UDISKS_PARTITION_NUMBER=1
E: UDISKS_PARTITION_TYPE=0x07
E: UDISKS_PARTITION_SIZE=104857600
E: UDISKS_PARTITION_FLAGS=boot
E: UDISKS_PARTITION_SLAVE=/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: UDISKS_PARTITION_OFFSET=1048576
E: UDISKS_PARTITION_ALIGNMENT_OFFSET=0
E: DEVLINKS=/dev/disk/by-id/wwn-0x50024e9400bbadf8-part1 /dev/disk/by-partuuid/8dad9926-01 /dev/disk/by-label/SYSTEM_BOOT /dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part1 /dev/disk/by-uuid/6CC6502FC64FF7BA /dev/disk/by-path/pci-0000:00:1f.2-ata-1-part1
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda10
N: sda10
L: 0
S: disk/by-path/pci-0000:00:1f.2-ata-1-part10
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part10
S: disk/by-uuid/6b490167-be9b-4dc3-868c-67e23ecf50d9
S: disk/by-id/wwn-0x50024e9400bbadf8-part10
S: disk/by-partuuid/8dad9926-0a
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda10
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda10
E: DEVTYPE=partition
E: PARTN=10
E: MAJOR=8
E: MINOR=10
E: USEC_INITIALIZED=6903809
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: ID_FS_UUID=6b490167-be9b-4dc3-868c-67e23ecf50d9
E: ID_FS_UUID_ENC=6b490167-be9b-4dc3-868c-67e23ecf50d9
E: ID_FS_VERSION=1.0
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=8dad9926-0a
E: ID_PART_ENTRY_TYPE=0x83
E: ID_PART_ENTRY_NUMBER=10
E: ID_PART_ENTRY_OFFSET=561733632
E: ID_PART_ENTRY_SIZE=63408128
E: ID_PART_ENTRY_DISK=8:0
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION=1
E: UDISKS_PARTITION_SCHEME=mbr
E: UDISKS_PARTITION_NUMBER=10
E: UDISKS_PARTITION_TYPE=0x83
E: UDISKS_PARTITION_SIZE=32464961536
E: UDISKS_PARTITION_SLAVE=/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: UDISKS_PARTITION_OFFSET=287607619584
E: UDISKS_PARTITION_ALIGNMENT_OFFSET=0
E: DEVLINKS=/dev/disk/by-path/pci-0000:00:1f.2-ata-1-part10 /dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part10 /dev/disk/by-uuid/6b490167-be9b-4dc3-868c-67e23ecf50d9 /dev/disk/by-id/wwn-0x50024e9400bbadf8-part10 /dev/disk/by-partuuid/8dad9926-0a
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda11
N: sda11
L: 0
S: disk/by-path/pci-0000:00:1f.2-ata-1-part11
S: disk/by-partuuid/8dad9926-0b
S: disk/by-uuid/71eee594-5230-4176-bea1-f9b1d7837ea7
S: disk/by-id/wwn-0x50024e9400bbadf8-part11
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part11
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda11
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda11
E: DEVTYPE=partition
E: PARTN=11
E: MAJOR=8
E: MINOR=11
E: USEC_INITIALIZED=7186298
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: ID_FS_UUID=71eee594-5230-4176-bea1-f9b1d7837ea7
E: ID_FS_UUID_ENC=71eee594-5230-4176-bea1-f9b1d7837ea7
E: ID_FS_VERSION=1.0
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=8dad9926-0b
E: ID_PART_ENTRY_TYPE=0x83
E: ID_PART_ENTRY_NUMBER=11
E: ID_PART_ENTRY_OFFSET=197050368
E: ID_PART_ENTRY_SIZE=293625856
E: ID_PART_ENTRY_DISK=8:0
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION=1
E: UDISKS_PARTITION_SCHEME=mbr
E: UDISKS_PARTITION_NUMBER=11
E: UDISKS_PARTITION_TYPE=0x83
E: UDISKS_PARTITION_SIZE=150336438272
E: UDISKS_PARTITION_SLAVE=/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: UDISKS_PARTITION_OFFSET=100889788416
E: UDISKS_PARTITION_ALIGNMENT_OFFSET=0
E: DEVLINKS=/dev/disk/by-path/pci-0000:00:1f.2-ata-1-part11 /dev/disk/by-partuuid/8dad9926-0b /dev/disk/by-uuid/71eee594-5230-4176-bea1-f9b1d7837ea7 /dev/disk/by-id/wwn-0x50024e9400bbadf8-part11 /dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part11
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda12
N: sda12
L: 0
S: disk/by-partuuid/8dad9926-0c
S: disk/by-id/wwn-0x50024e9400bbadf8-part12
S: disk/by-uuid/5a6a7b15-7679-4416-8932-880cc728916c
S: disk/by-path/pci-0000:00:1f.2-ata-1-part12
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part12
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda12
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda12
E: DEVTYPE=partition
E: PARTN=12
E: MAJOR=8
E: MINOR=12
E: USEC_INITIALIZED=6118287
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: ID_FS_UUID=5a6a7b15-7679-4416-8932-880cc728916c
E: ID_FS_UUID_ENC=5a6a7b15-7679-4416-8932-880cc728916c
E: ID_FS_VERSION=1.0
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=8dad9926-0c
E: ID_PART_ENTRY_TYPE=0x83
E: ID_PART_ENTRY_NUMBER=12
E: ID_PART_ENTRY_OFFSET=490678272
E: ID_PART_ENTRY_SIZE=16381952
E: ID_PART_ENTRY_DISK=8:0
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION=1
E: UDISKS_PARTITION_SCHEME=mbr
E: UDISKS_PARTITION_NUMBER=12
E: UDISKS_PARTITION_TYPE=0x83
E: UDISKS_PARTITION_SIZE=8387559424
E: UDISKS_PARTITION_SLAVE=/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: UDISKS_PARTITION_OFFSET=251227275264
E: UDISKS_PARTITION_ALIGNMENT_OFFSET=0
E: DEVLINKS=/dev/disk/by-partuuid/8dad9926-0c /dev/disk/by-id/wwn-0x50024e9400bbadf8-part12 /dev/disk/by-uuid/5a6a7b15-7679-4416-8932-880cc728916c /dev/disk/by-path/pci-0000:00:1f.2-ata-1-part12 /dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part12
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda2
N: sda2
L: 0
S: disk/by-path/pci-0000:00:1f.2-ata-1-part2
S: disk/by-uuid/20D051F0D051CCA2
S: disk/by-id/wwn-0x50024e9400bbadf8-part2
S: disk/by-label/SYSTEM_OS
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part2
S: disk/by-partuuid/8dad9926-02
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda2
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda2
E: DEVTYPE=partition
E: PARTN=2
E: MAJOR=8
E: MINOR=2
E: USEC_INITIALIZED=6559717
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: ID_FS_LABEL=SYSTEM_OS
E: ID_FS_LABEL_ENC=SYSTEM_OS
E: ID_FS_UUID=20D051F0D051CCA2
E: ID_FS_UUID_ENC=20D051F0D051CCA2
E: ID_FS_TYPE=ntfs
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=8dad9926-02
E: ID_PART_ENTRY_TYPE=0x7
E: ID_PART_ENTRY_NUMBER=2
E: ID_PART_ENTRY_OFFSET=206848
E: ID_PART_ENTRY_SIZE=195919872
E: ID_PART_ENTRY_DISK=8:0
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION=1
E: UDISKS_PARTITION_SCHEME=mbr
E: UDISKS_PARTITION_NUMBER=2
E: UDISKS_PARTITION_TYPE=0x07
E: UDISKS_PARTITION_SIZE=100310974464
E: UDISKS_PARTITION_SLAVE=/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: UDISKS_PARTITION_OFFSET=105906176
E: UDISKS_PARTITION_ALIGNMENT_OFFSET=0
E: DEVLINKS=/dev/disk/by-path/pci-0000:00:1f.2-ata-1-part2 /dev/disk/by-uuid/20D051F0D051CCA2 /dev/disk/by-id/wwn-0x50024e9400bbadf8-part2 /dev/disk/by-label/SYSTEM_OS /dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part2 /dev/disk/by-partuuid/8dad9926-02
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda3
N: sda3
L: 0
S: disk/by-path/pci-0000:00:1f.2-ata-1-part3
S: disk/by-partuuid/8dad9926-03
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part3
S: disk/by-id/wwn-0x50024e9400bbadf8-part3
S: disk/by-uuid/1680B51480B4FAF7
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda3
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda3
E: DEVTYPE=partition
E: PARTN=3
E: MAJOR=8
E: MINOR=3
E: USEC_INITIALIZED=7023911
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: ID_FS_UUID=1680B51480B4FAF7
E: ID_FS_UUID_ENC=1680B51480B4FAF7
E: ID_FS_TYPE=ntfs
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=8dad9926-03
E: ID_PART_ENTRY_TYPE=0x27
E: ID_PART_ENTRY_NUMBER=3
E: ID_PART_ENTRY_OFFSET=196126720
E: ID_PART_ENTRY_SIZE=921600
E: ID_PART_ENTRY_DISK=8:0
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION=1
E: UDISKS_PARTITION_SCHEME=mbr
E: UDISKS_PARTITION_NUMBER=3
E: UDISKS_PARTITION_TYPE=0x27
E: UDISKS_PARTITION_SIZE=471859200
E: UDISKS_PARTITION_SLAVE=/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: UDISKS_PARTITION_OFFSET=100416880640
E: UDISKS_PARTITION_ALIGNMENT_OFFSET=0
E: UDISKS_PRESENTATION_HIDE=1
E: UDISKS_IGNORE=1
E: DEVLINKS=/dev/disk/by-path/pci-0000:00:1f.2-ata-1-part3 /dev/disk/by-partuuid/8dad9926-03 /dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part3 /dev/disk/by-id/wwn-0x50024e9400bbadf8-part3 /dev/disk/by-uuid/1680B51480B4FAF7
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda4
N: sda4
L: 0
S: disk/by-path/pci-0000:00:1f.2-ata-1-part4
S: disk/by-id/wwn-0x50024e9400bbadf8-part4
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part4
S: disk/by-partuuid/8dad9926-04
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda4
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda4
E: DEVTYPE=partition
E: PARTN=4
E: MAJOR=8
E: MINOR=4
E: USEC_INITIALIZED=5236747
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=8dad9926-04
E: ID_PART_ENTRY_TYPE=0x5
E: ID_PART_ENTRY_NUMBER=4
E: ID_PART_ENTRY_OFFSET=197048320
E: ID_PART_ENTRY_SIZE=428093440
E: ID_PART_ENTRY_DISK=8:0
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION=1
E: UDISKS_PARTITION_SCHEME=mbr
E: UDISKS_PARTITION_NUMBER=4
E: UDISKS_PARTITION_TYPE=0x05
E: UDISKS_PARTITION_SIZE=219183841280
E: UDISKS_PARTITION_SLAVE=/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: UDISKS_PARTITION_OFFSET=100888739840
E: UDISKS_PARTITION_ALIGNMENT_OFFSET=0
E: DEVLINKS=/dev/disk/by-path/pci-0000:00:1f.2-ata-1-part4 /dev/disk/by-id/wwn-0x50024e9400bbadf8-part4 /dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part4 /dev/disk/by-partuuid/8dad9926-04
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda5
N: sda5
L: 0
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part5
S: disk/by-partuuid/8dad9926-05
S: disk/by-id/wwn-0x50024e9400bbadf8-part5
S: disk/by-uuid/5c30267b-70fd-4f2d-98cb-8503c8aa64fd
S: disk/by-path/pci-0000:00:1f.2-ata-1-part5
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda5
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda5
E: DEVTYPE=partition
E: PARTN=5
E: MAJOR=8
E: MINOR=5
E: USEC_INITIALIZED=6773599
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: ID_FS_UUID=5c30267b-70fd-4f2d-98cb-8503c8aa64fd
E: ID_FS_UUID_ENC=5c30267b-70fd-4f2d-98cb-8503c8aa64fd
E: ID_FS_VERSION=1.0
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=8dad9926-05
E: ID_PART_ENTRY_TYPE=0x83
E: ID_PART_ENTRY_NUMBER=5
E: ID_PART_ENTRY_OFFSET=507062272
E: ID_PART_ENTRY_SIZE=12064768
E: ID_PART_ENTRY_DISK=8:0
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION=1
E: UDISKS_PARTITION_SCHEME=mbr
E: UDISKS_PARTITION_NUMBER=5
E: UDISKS_PARTITION_TYPE=0x83
E: UDISKS_PARTITION_SIZE=6177161216
E: UDISKS_PARTITION_SLAVE=/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: UDISKS_PARTITION_OFFSET=259615883264
E: UDISKS_PARTITION_ALIGNMENT_OFFSET=0
E: DEVLINKS=/dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part5 /dev/disk/by-partuuid/8dad9926-05 /dev/disk/by-id/wwn-0x50024e9400bbadf8-part5 /dev/disk/by-uuid/5c30267b-70fd-4f2d-98cb-8503c8aa64fd /dev/disk/by-path/pci-0000:00:1f.2-ata-1-part5
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda6
N: sda6
L: 0
S: disk/by-uuid/2b328fb4-2ba8-4700-9679-34efd2253604
S: disk/by-path/pci-0000:00:1f.2-ata-1-part6
S: disk/by-id/wwn-0x50024e9400bbadf8-part6
S: disk/by-partuuid/8dad9926-06
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part6
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda6
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda6
E: DEVTYPE=partition
E: PARTN=6
E: MAJOR=8
E: MINOR=6
E: USEC_INITIALIZED=7104795
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: ID_FS_UUID=2b328fb4-2ba8-4700-9679-34efd2253604
E: ID_FS_UUID_ENC=2b328fb4-2ba8-4700-9679-34efd2253604
E: ID_FS_VERSION=1.0
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=8dad9926-06
E: ID_PART_ENTRY_TYPE=0x83
E: ID_PART_ENTRY_NUMBER=6
E: ID_PART_ENTRY_OFFSET=519129088
E: ID_PART_ENTRY_SIZE=28186624
E: ID_PART_ENTRY_DISK=8:0
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION=1
E: UDISKS_PARTITION_SCHEME=mbr
E: UDISKS_PARTITION_NUMBER=6
E: UDISKS_PARTITION_TYPE=0x83
E: UDISKS_PARTITION_SIZE=14431551488
E: UDISKS_PARTITION_SLAVE=/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: UDISKS_PARTITION_OFFSET=265794093056
E: UDISKS_PARTITION_ALIGNMENT_OFFSET=0
E: DEVLINKS=/dev/disk/by-uuid/2b328fb4-2ba8-4700-9679-34efd2253604 /dev/disk/by-path/pci-0000:00:1f.2-ata-1-part6 /dev/disk/by-id/wwn-0x50024e9400bbadf8-part6 /dev/disk/by-partuuid/8dad9926-06 /dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part6
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda7
N: sda7
L: 0
S: disk/by-id/wwn-0x50024e9400bbadf8-part7
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part7
S: disk/by-partuuid/8dad9926-07
S: disk/by-uuid/5352d2db-2f2d-4816-8150-cdc19e276f17
S: disk/by-path/pci-0000:00:1f.2-ata-1-part7
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda7
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda7
E: DEVTYPE=partition
E: PARTN=7
E: MAJOR=8
E: MINOR=7
E: USEC_INITIALIZED=6642678
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: ID_FS_UUID=5352d2db-2f2d-4816-8150-cdc19e276f17
E: ID_FS_UUID_ENC=5352d2db-2f2d-4816-8150-cdc19e276f17
E: ID_FS_VERSION=1.0
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=8dad9926-07
E: ID_PART_ENTRY_TYPE=0x83
E: ID_PART_ENTRY_NUMBER=7
E: ID_PART_ENTRY_OFFSET=547317760
E: ID_PART_ENTRY_SIZE=5038080
E: ID_PART_ENTRY_DISK=8:0
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION=1
E: UDISKS_PARTITION_SCHEME=mbr
E: UDISKS_PARTITION_NUMBER=7
E: UDISKS_PARTITION_TYPE=0x83
E: UDISKS_PARTITION_SIZE=2579496960
E: UDISKS_PARTITION_SLAVE=/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: UDISKS_PARTITION_OFFSET=280226693120
E: UDISKS_PARTITION_ALIGNMENT_OFFSET=0
E: DEVLINKS=/dev/disk/by-id/wwn-0x50024e9400bbadf8-part7 /dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part7 /dev/disk/by-partuuid/8dad9926-07 /dev/disk/by-uuid/5352d2db-2f2d-4816-8150-cdc19e276f17 /dev/disk/by-path/pci-0000:00:1f.2-ata-1-part7
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda8
N: sda8
L: 0
S: disk/by-path/pci-0000:00:1f.2-ata-1-part8
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part8
S: disk/by-id/wwn-0x50024e9400bbadf8-part8
S: disk/by-uuid/9f2a6911-7ad8-4af7-be5e-763b7e141e6b
S: disk/by-partuuid/8dad9926-08
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda8
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda8
E: DEVTYPE=partition
E: PARTN=8
E: MAJOR=8
E: MINOR=8
E: USEC_INITIALIZED=6832139
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: ID_FS_UUID=9f2a6911-7ad8-4af7-be5e-763b7e141e6b
E: ID_FS_UUID_ENC=9f2a6911-7ad8-4af7-be5e-763b7e141e6b
E: ID_FS_VERSION=1
E: ID_FS_TYPE=swap
E: ID_FS_USAGE=other
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=8dad9926-08
E: ID_PART_ENTRY_TYPE=0x82
E: ID_PART_ENTRY_NUMBER=8
E: ID_PART_ENTRY_OFFSET=552357888
E: ID_PART_ENTRY_SIZE=7811072
E: ID_PART_ENTRY_DISK=8:0
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION=1
E: UDISKS_PARTITION_SCHEME=mbr
E: UDISKS_PARTITION_NUMBER=8
E: UDISKS_PARTITION_TYPE=0x82
E: UDISKS_PARTITION_SIZE=3999268864
E: UDISKS_PARTITION_SLAVE=/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: UDISKS_PARTITION_OFFSET=282807238656
E: UDISKS_PARTITION_ALIGNMENT_OFFSET=0
E: DEVLINKS=/dev/disk/by-path/pci-0000:00:1f.2-ata-1-part8 /dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part8 /dev/disk/by-id/wwn-0x50024e9400bbadf8-part8 /dev/disk/by-uuid/9f2a6911-7ad8-4af7-be5e-763b7e141e6b /dev/disk/by-partuuid/8dad9926-08
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda9
N: sda9
L: 0
S: disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part9
S: disk/by-uuid/8aab9ec3-977b-400e-a011-71aa6e25e0d7
S: disk/by-partuuid/8dad9926-09
S: disk/by-path/pci-0000:00:1f.2-ata-1-part9
S: disk/by-id/wwn-0x50024e9400bbadf8-part9
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda9
E: SUBSYSTEM=block
E: DEVNAME=/dev/sda9
E: DEVTYPE=partition
E: PARTN=9
E: MAJOR=8
E: MINOR=9
E: USEC_INITIALIZED=6045234
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=SAMSUNG_HM321HI
E: ID_MODEL_ENC=SAMSUNG\x20HM321HI\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=2AJ10001
E: ID_SERIAL=SAMSUNG_HM321HI_S2K5J56B705745
E: ID_SERIAL_SHORT=S2K5J56B705745
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=80
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=254
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=0
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=1
E: ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=254
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5400
E: ID_WWN=0x50024e9400bbadf8
E: ID_WWN_WITH_EXTENSION=0x50024e9400bbadf8
E: ID_PATH=pci-0000:00:1f.2-ata-1
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-1
E: ID_PART_TABLE_UUID=8dad9926
E: ID_PART_TABLE_TYPE=dos
E: ID_FS_UUID=8aab9ec3-977b-400e-a011-71aa6e25e0d7
E: ID_FS_UUID_ENC=8aab9ec3-977b-400e-a011-71aa6e25e0d7
E: ID_FS_VERSION=1.0
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=8dad9926-09
E: ID_PART_ENTRY_TYPE=0x83
E: ID_PART_ENTRY_NUMBER=9
E: ID_PART_ENTRY_OFFSET=560171008
E: ID_PART_ENTRY_SIZE=1560576
E: ID_PART_ENTRY_DISK=8:0
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION=1
E: UDISKS_PARTITION_SCHEME=mbr
E: UDISKS_PARTITION_NUMBER=9
E: UDISKS_PARTITION_TYPE=0x83
E: UDISKS_PARTITION_SIZE=799014912
E: UDISKS_PARTITION_SLAVE=/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: UDISKS_PARTITION_OFFSET=286807556096
E: UDISKS_PARTITION_ALIGNMENT_OFFSET=0
E: DEVLINKS=/dev/disk/by-id/ata-SAMSUNG_HM321HI_S2K5J56B705745-part9 /dev/disk/by-uuid/8aab9ec3-977b-400e-a011-71aa6e25e0d7 /dev/disk/by-partuuid/8dad9926-09 /dev/disk/by-path/pci-0000:00:1f.2-ata-1-part9 /dev/disk/by-id/wwn-0x50024e9400bbadf8-part9
E: TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/bsg/0:0:0:0
N: bsg/0:0:0:0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/bsg/0:0:0:0
E: SUBSYSTEM=bsg
E: DEVNAME=/dev/bsg/0:0:0:0
E: MAJOR=250
E: MINOR=0

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/scsi_device/0:0:0:0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/scsi_device/0:0:0:0
E: SUBSYSTEM=scsi_device

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/scsi_disk/0:0:0:0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/scsi_disk/0:0:0:0
E: SUBSYSTEM=scsi_disk

P: /devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/scsi_generic/sg0
N: sg0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/scsi_generic/sg0
E: SUBSYSTEM=scsi_generic
E: DEVNAME=/dev/sg0
E: MAJOR=21
E: MINOR=0

P: /devices/pci0000:00/0000:00:1f.2/ata1/link1/ata_link/link1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/link1/ata_link/link1
E: SUBSYSTEM=ata_link

P: /devices/pci0000:00/0000:00:1f.2/ata1/link1/dev1.0/ata_device/dev1.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata1/link1/dev1.0/ata_device/dev1.0
E: SUBSYSTEM=ata_device

P: /devices/pci0000:00/0000:00:1f.2/ata2/ata_port/ata2
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/ata_port/ata2
E: SUBSYSTEM=ata_port

P: /devices/pci0000:00/0000:00:1f.2/ata2/host1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/host1
E: SUBSYSTEM=scsi
E: DEVTYPE=scsi_host

P: /devices/pci0000:00/0000:00:1f.2/ata2/host1/scsi_host/host1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/host1/scsi_host/host1
E: SUBSYSTEM=scsi_host

P: /devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0
E: SUBSYSTEM=scsi
E: DEVTYPE=scsi_target

P: /devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0
E: SUBSYSTEM=scsi
E: DEVTYPE=scsi_device
E: DRIVER=sr
E: MODALIAS=scsi:t-0x05

P: /devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/block/sr0
N: sr0
L: -100
S: disk/by-path/pci-0000:00:1f.2-ata-2
S: disk/by-id/ata-TSSTcorp_CDDVDW_TS-L633F_R8356GIB403495
S: dvdrw
S: cdrw
S: cdrom
S: dvd
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/block/sr0
E: SUBSYSTEM=block
E: DEVNAME=/dev/sr0
E: DEVTYPE=disk
E: MAJOR=11
E: MINOR=0
E: USEC_INITIALIZED=5017125
E: ID_CDROM=1
E: SYSTEMD_MOUNT_DEVICE_BOUND=1
E: ID_CDROM_CD=1
E: ID_CDROM_CD_R=1
E: ID_CDROM_CD_RW=1
E: ID_CDROM_DVD=1
E: ID_CDROM_DVD_R=1
E: ID_CDROM_DVD_RW=1
E: ID_CDROM_DVD_RAM=1
E: ID_CDROM_DVD_PLUS_R=1
E: ID_CDROM_DVD_PLUS_RW=1
E: ID_CDROM_DVD_PLUS_R_DL=1
E: ID_CDROM_MRW=1
E: ID_CDROM_MRW_W=1
E: ID_ATA=1
E: ID_TYPE=cd
E: ID_BUS=ata
E: ID_MODEL=TSSTcorp_CDDVDW_TS-L633F
E: ID_MODEL_ENC=TSSTcorp\x20CDDVDW\x20TS-L633F\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=TM00
E: ID_SERIAL=TSSTcorp_CDDVDW_TS-L633F_R8356GIB403495
E: ID_SERIAL_SHORT=R8356GIB403495
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_PATH=pci-0000:00:1f.2-ata-2
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-2
E: ID_FOR_SEAT=block-pci-0000_00_1f_2-ata-2
E: UDISKS_PRESENTATION_NOPOLICY=0
E: DEVLINKS=/dev/disk/by-path/pci-0000:00:1f.2-ata-2 /dev/disk/by-id/ata-TSSTcorp_CDDVDW_TS-L633F_R8356GIB403495 /dev/dvdrw /dev/cdrw /dev/cdrom /dev/dvd
E: TAGS=:uaccess:seat:systemd:

P: /devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/bsg/1:0:0:0
N: bsg/1:0:0:0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/bsg/1:0:0:0
E: SUBSYSTEM=bsg
E: DEVNAME=/dev/bsg/1:0:0:0
E: MAJOR=250
E: MINOR=1

P: /devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/scsi_device/1:0:0:0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/scsi_device/1:0:0:0
E: SUBSYSTEM=scsi_device

P: /devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/scsi_generic/sg1
N: sg1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/scsi_generic/sg1
E: SUBSYSTEM=scsi_generic
E: DEVNAME=/dev/sg1
E: MAJOR=21
E: MINOR=1
E: USEC_INITIALIZED=17051952
E: ID_PATH=pci-0000:00:1f.2-ata-2
E: ID_PATH_TAG=pci-0000_00_1f_2-ata-2
E: ID_FOR_SEAT=scsi_generic-pci-0000_00_1f_2-ata-2
E: TAGS=:seat:uaccess:

P: /devices/pci0000:00/0000:00:1f.2/ata2/link2/ata_link/link2
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/link2/ata_link/link2
E: SUBSYSTEM=ata_link

P: /devices/pci0000:00/0000:00:1f.2/ata2/link2/dev2.0/ata_device/dev2.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/link2/dev2.0/ata_device/dev2.0
E: SUBSYSTEM=ata_device

P: /devices/pci0000:00/0000:00:1f.2/ata3/ata_port/ata3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata3/ata_port/ata3
E: SUBSYSTEM=ata_port

P: /devices/pci0000:00/0000:00:1f.2/ata3/host2
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata3/host2
E: SUBSYSTEM=scsi
E: DEVTYPE=scsi_host

P: /devices/pci0000:00/0000:00:1f.2/ata3/host2/scsi_host/host2
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata3/host2/scsi_host/host2
E: SUBSYSTEM=scsi_host

P: /devices/pci0000:00/0000:00:1f.2/ata3/link3/ata_link/link3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata3/link3/ata_link/link3
E: SUBSYSTEM=ata_link

P: /devices/pci0000:00/0000:00:1f.2/ata3/link3/dev3.0/ata_device/dev3.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata3/link3/dev3.0/ata_device/dev3.0
E: SUBSYSTEM=ata_device

P: /devices/pci0000:00/0000:00:1f.2/ata4/ata_port/ata4
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata4/ata_port/ata4
E: SUBSYSTEM=ata_port

P: /devices/pci0000:00/0000:00:1f.2/ata4/host3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata4/host3
E: SUBSYSTEM=scsi
E: DEVTYPE=scsi_host

P: /devices/pci0000:00/0000:00:1f.2/ata4/host3/scsi_host/host3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata4/host3/scsi_host/host3
E: SUBSYSTEM=scsi_host

P: /devices/pci0000:00/0000:00:1f.2/ata4/link4/ata_link/link4
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata4/link4/ata_link/link4
E: SUBSYSTEM=ata_link

P: /devices/pci0000:00/0000:00:1f.2/ata4/link4/dev4.0/ata_device/dev4.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata4/link4/dev4.0/ata_device/dev4.0
E: SUBSYSTEM=ata_device

P: /devices/pci0000:00/0000:00:1f.2/ata5/ata_port/ata5
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata5/ata_port/ata5
E: SUBSYSTEM=ata_port

P: /devices/pci0000:00/0000:00:1f.2/ata5/host4
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata5/host4
E: SUBSYSTEM=scsi
E: DEVTYPE=scsi_host

P: /devices/pci0000:00/0000:00:1f.2/ata5/host4/scsi_host/host4
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata5/host4/scsi_host/host4
E: SUBSYSTEM=scsi_host

P: /devices/pci0000:00/0000:00:1f.2/ata5/link5/ata_link/link5
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata5/link5/ata_link/link5
E: SUBSYSTEM=ata_link

P: /devices/pci0000:00/0000:00:1f.2/ata5/link5/dev5.0/ata_device/dev5.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata5/link5/dev5.0/ata_device/dev5.0
E: SUBSYSTEM=ata_device

P: /devices/pci0000:00/0000:00:1f.3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.3
E: SUBSYSTEM=pci
E: DRIVER=i801_smbus
E: PCI_CLASS=C0500
E: PCI_ID=8086:3B30
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:1f.3
E: MODALIAS=pci:v00008086d00003B30sv00001558sd00005125bc0Csc05i00
E: USEC_INITIALIZED=15895900
E: ID_PCI_CLASS_FROM_DATABASE=Serial bus controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=SMBus
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset SMBus Controller

P: /devices/pci0000:00/0000:00:1f.3/i2c-0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.3/i2c-0
E: SUBSYSTEM=i2c

P: /devices/pci0000:00/0000:00:1f.6
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1f.6
E: SUBSYSTEM=pci
E: PCI_CLASS=118000
E: PCI_ID=8086:3B32
E: PCI_SUBSYS_ID=1558:5125
E: PCI_SLOT_NAME=0000:00:1f.6
E: MODALIAS=pci:v00008086d00003B32sv00001558sd00005125bc11sc80i00
E: USEC_INITIALIZED=15894846
E: ID_PCI_CLASS_FROM_DATABASE=Signal processing controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Signal processing controller
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=5 Series/3400 Series Chipset Thermal Subsystem

P: /devices/pci0000:00/pci_bus/0000:00
L: 0
E: DEVPATH=/devices/pci0000:00/pci_bus/0000:00
E: SUBSYSTEM=pci_bus

P: /devices/pci0000:ff/0000:ff:00.0
L: 0
E: DEVPATH=/devices/pci0000:ff/0000:ff:00.0
E: SUBSYSTEM=pci
E: PCI_CLASS=60000
E: PCI_ID=8086:2C62
E: PCI_SUBSYS_ID=8086:8086
E: PCI_SLOT_NAME=0000:ff:00.0
E: MODALIAS=pci:v00008086d00002C62sv00008086sd00008086bc06sc00i00
E: USEC_INITIALIZED=15937063
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=Host bridge
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=Core Processor QuickPath Architecture Generic Non-core Registers

P: /devices/pci0000:ff/0000:ff:00.1
L: 0
E: DEVPATH=/devices/pci0000:ff/0000:ff:00.1
E: SUBSYSTEM=pci
E: PCI_CLASS=60000
E: PCI_ID=8086:2D01
E: PCI_SUBSYS_ID=8086:8086
E: PCI_SLOT_NAME=0000:ff:00.1
E: MODALIAS=pci:v00008086d00002D01sv00008086sd00008086bc06sc00i00
E: USEC_INITIALIZED=15961426
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=Host bridge
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=Core Processor QuickPath Architecture System Address Decoder

P: /devices/pci0000:ff/0000:ff:02.0
L: 0
E: DEVPATH=/devices/pci0000:ff/0000:ff:02.0
E: SUBSYSTEM=pci
E: PCI_CLASS=60000
E: PCI_ID=8086:2D10
E: PCI_SUBSYS_ID=8086:8086
E: PCI_SLOT_NAME=0000:ff:02.0
E: MODALIAS=pci:v00008086d00002D10sv00008086sd00008086bc06sc00i00
E: USEC_INITIALIZED=15965645
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=Host bridge
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=Core Processor QPI Link 0

P: /devices/pci0000:ff/0000:ff:02.1
L: 0
E: DEVPATH=/devices/pci0000:ff/0000:ff:02.1
E: SUBSYSTEM=pci
E: PCI_CLASS=60000
E: PCI_ID=8086:2D11
E: PCI_SUBSYS_ID=8086:8086
E: PCI_SLOT_NAME=0000:ff:02.1
E: MODALIAS=pci:v00008086d00002D11sv00008086sd00008086bc06sc00i00
E: USEC_INITIALIZED=15962579
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=Host bridge
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=1st Generation Core i3/5/7 Processor QPI Physical 0

P: /devices/pci0000:ff/0000:ff:02.2
L: 0
E: DEVPATH=/devices/pci0000:ff/0000:ff:02.2
E: SUBSYSTEM=pci
E: PCI_CLASS=60000
E: PCI_ID=8086:2D12
E: PCI_SUBSYS_ID=8086:8086
E: PCI_SLOT_NAME=0000:ff:02.2
E: MODALIAS=pci:v00008086d00002D12sv00008086sd00008086bc06sc00i00
E: USEC_INITIALIZED=15962648
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=Host bridge
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=1st Generation Core i3/5/7 Processor Reserved

P: /devices/pci0000:ff/0000:ff:02.3
L: 0
E: DEVPATH=/devices/pci0000:ff/0000:ff:02.3
E: SUBSYSTEM=pci
E: PCI_CLASS=60000
E: PCI_ID=8086:2D13
E: PCI_SUBSYS_ID=8086:8086
E: PCI_SLOT_NAME=0000:ff:02.3
E: MODALIAS=pci:v00008086d00002D13sv00008086sd00008086bc06sc00i00
E: USEC_INITIALIZED=15964239
E: ID_PCI_CLASS_FROM_DATABASE=Bridge
E: ID_PCI_SUBCLASS_FROM_DATABASE=Host bridge
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=1st Generation Core i3/5/7 Processor Reserved

P: /devices/pci0000:ff/pci_bus/0000:ff
L: 0
E: DEVPATH=/devices/pci0000:ff/pci_bus/0000:ff
E: SUBSYSTEM=pci_bus

P: /devices/platform/ACPI0003:00
L: 0
E: DEVPATH=/devices/platform/ACPI0003:00
E: SUBSYSTEM=platform
E: MODALIAS=acpi:ACPI0003:
E: USEC_INITIALIZED=15969873
E: ID_PATH=platform-ACPI0003:00
E: ID_PATH_TAG=platform-ACPI0003_00

P: /devices/platform/PNP0C0A:00
L: 0
E: DEVPATH=/devices/platform/PNP0C0A:00
E: SUBSYSTEM=platform
E: MODALIAS=acpi:PNP0C0A:
E: USEC_INITIALIZED=15970763
E: ID_PATH=platform-PNP0C0A:00
E: ID_PATH_TAG=platform-PNP0C0A_00

P: /devices/platform/PNP0C0C:00
L: 0
E: DEVPATH=/devices/platform/PNP0C0C:00
E: SUBSYSTEM=platform
E: MODALIAS=acpi:PNP0C0C:
E: USEC_INITIALIZED=15971774
E: ID_PATH=platform-PNP0C0C:00
E: ID_PATH_TAG=platform-PNP0C0C_00

P: /devices/platform/PNP0C0D:00
L: 0
E: DEVPATH=/devices/platform/PNP0C0D:00
E: SUBSYSTEM=platform
E: MODALIAS=acpi:PNP0C0D:
E: USEC_INITIALIZED=15973419
E: ID_PATH=platform-PNP0C0D:00
E: ID_PATH_TAG=platform-PNP0C0D_00

P: /devices/platform/PNP0C0E:00
L: 0
E: DEVPATH=/devices/platform/PNP0C0E:00
E: SUBSYSTEM=platform
E: MODALIAS=acpi:PNP0C0E:
E: USEC_INITIALIZED=15974494
E: ID_PATH=platform-PNP0C0E:00
E: ID_PATH_TAG=platform-PNP0C0E_00

P: /devices/platform/PNP0C14:00
L: 0
E: DEVPATH=/devices/platform/PNP0C14:00
E: SUBSYSTEM=platform
E: DRIVER=acpi-wmi
E: MODALIAS=acpi:PNP0C14:
E: USEC_INITIALIZED=15978621
E: ID_PATH=platform-PNP0C14:00
E: ID_PATH_TAG=platform-PNP0C14_00

P: /devices/platform/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00
L: 0
E: DEVPATH=/devices/platform/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00
E: SUBSYSTEM=wmi_bus

P: /devices/platform/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/ABBC0F6B-8EA1-11D1-00A0-C90629100000
L: 0
E: DEVPATH=/devices/platform/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/ABBC0F6B-8EA1-11D1-00A0-C90629100000
E: SUBSYSTEM=wmi
E: DEVTYPE=event
E: MODALIAS=wmi:ABBC0F6B-8EA1-11D1-00A0-C90629100000
E: WMI_GUID=ABBC0F6B-8EA1-11D1-00A0-C90629100000

P: /devices/platform/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/ABBC0F6C-8EA1-11D1-00A0-C90629100000
L: 0
E: DEVPATH=/devices/platform/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/ABBC0F6C-8EA1-11D1-00A0-C90629100000
E: SUBSYSTEM=wmi
E: DEVTYPE=event
E: MODALIAS=wmi:ABBC0F6C-8EA1-11D1-00A0-C90629100000
E: WMI_GUID=ABBC0F6C-8EA1-11D1-00A0-C90629100000

P: /devices/platform/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/ABBC0F6D-8EA1-11D1-00A0-C90629100000
L: 0
E: DEVPATH=/devices/platform/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/ABBC0F6D-8EA1-11D1-00A0-C90629100000
E: SUBSYSTEM=wmi
E: DEVTYPE=method
E: MODALIAS=wmi:ABBC0F6D-8EA1-11D1-00A0-C90629100000
E: WMI_GUID=ABBC0F6D-8EA1-11D1-00A0-C90629100000

P: /devices/platform/alarmtimer
L: 0
E: DEVPATH=/devices/platform/alarmtimer
E: SUBSYSTEM=platform
E: DRIVER=alarmtimer
E: MODALIAS=platform:alarmtimer
E: USEC_INITIALIZED=15978614
E: ID_PATH=platform-alarmtimer
E: ID_PATH_TAG=platform-alarmtimer

P: /devices/platform/coretemp.0
L: 0
E: DEVPATH=/devices/platform/coretemp.0
E: SUBSYSTEM=platform
E: DRIVER=coretemp
E: MODALIAS=platform:coretemp
E: USEC_INITIALIZED=17095776
E: ID_PATH=platform-coretemp.0
E: ID_PATH_TAG=platform-coretemp_0

P: /devices/platform/coretemp.0/hwmon/hwmon1
L: 0
E: DEVPATH=/devices/platform/coretemp.0/hwmon/hwmon1
E: SUBSYSTEM=hwmon

P: /devices/platform/i8042
L: 0
E: DEVPATH=/devices/platform/i8042
E: SUBSYSTEM=platform
E: DRIVER=i8042
E: MODALIAS=platform:i8042
E: USEC_INITIALIZED=15979627
E: ID_PATH=platform-i8042
E: ID_PATH_TAG=platform-i8042

P: /devices/platform/i8042/serio0
L: 0
E: DEVPATH=/devices/platform/i8042/serio0
E: SUBSYSTEM=serio
E: DRIVER=atkbd
E: SERIO_TYPE=06
E: SERIO_PROTO=00
E: SERIO_ID=00
E: SERIO_EXTRA=00
E: MODALIAS=serio:ty06pr00id00ex00
E: SERIO_FIRMWARE_ID=PNP: PNP0303

P: /devices/platform/i8042/serio0/input/input0
L: 0
E: DEVPATH=/devices/platform/i8042/serio0/input/input0
E: SUBSYSTEM=input
E: PRODUCT=11/1/1/ab83
E: NAME="AT Translated Set 2 keyboard"
E: PHYS="isa0060/serio0/input0"
E: PROP=0
E: EV=120013
E: KEY=402000000 3803078f800d001 feffffdfffefffff fffffffffffffffe
E: MSC=10
E: LED=7
E: MODALIAS=input:b0011v0001p0001eAB83-e0,1,4,11,14,k71,72,73,74,75,76,77,79,7A,7B,7C,7D,7E,7F,80,8C,8E,8F,9B,9C,9D,9E,9F,A3,A4,A5,A6,AC,AD,B7,B8,B9,D9,E2,ram4,l0,1,2,sfw
E: USEC_INITIALIZED=3599273
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_BUS=i8042
E: ID_SERIAL=noserial
E: ID_PATH=platform-i8042-serio-0
E: ID_PATH_TAG=platform-i8042-serio-0
E: ID_FOR_SEAT=input-platform-i8042-serio-0
E: TAGS=:seat:

P: /devices/platform/i8042/serio0/input/input0/event0
N: input/event0
L: 0
E: DEVPATH=/devices/platform/i8042/serio0/input/input0/event0
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event0
E: MAJOR=13
E: MINOR=64

P: /devices/platform/i8042/serio0/input/input0/input0::capslock
L: 0
E: DEVPATH=/devices/platform/i8042/serio0/input/input0/input0::capslock
E: SUBSYSTEM=leds
E: USEC_INITIALIZED=16153646
E: ID_PATH=platform-i8042-serio-0
E: ID_PATH_TAG=platform-i8042-serio-0
E: ID_FOR_SEAT=leds-platform-i8042-serio-0
E: TAGS=:seat:

P: /devices/platform/i8042/serio0/input/input0/input0::numlock
L: 0
E: DEVPATH=/devices/platform/i8042/serio0/input/input0/input0::numlock
E: SUBSYSTEM=leds
E: USEC_INITIALIZED=16151905
E: ID_PATH=platform-i8042-serio-0
E: ID_PATH_TAG=platform-i8042-serio-0
E: ID_FOR_SEAT=leds-platform-i8042-serio-0
E: TAGS=:seat:

P: /devices/platform/i8042/serio0/input/input0/input0::scrolllock
L: 0
E: DEVPATH=/devices/platform/i8042/serio0/input/input0/input0::scrolllock
E: SUBSYSTEM=leds
E: USEC_INITIALIZED=16151114
E: ID_PATH=platform-i8042-serio-0
E: ID_PATH_TAG=platform-i8042-serio-0
E: ID_FOR_SEAT=leds-platform-i8042-serio-0
E: TAGS=:seat:

P: /devices/platform/i8042/serio1
L: 0
E: DEVPATH=/devices/platform/i8042/serio1
E: SUBSYSTEM=serio
E: SERIO_TYPE=01
E: SERIO_PROTO=00
E: SERIO_ID=00
E: SERIO_EXTRA=00
E: MODALIAS=serio:ty01pr00id00ex00
E: SERIO_FIRMWARE_ID=PNP: PNP0f13

P: /devices/platform/i8042/serio2
L: 0
E: DEVPATH=/devices/platform/i8042/serio2
E: SUBSYSTEM=serio
E: DRIVER=psmouse
E: SERIO_TYPE=01
E: SERIO_PROTO=00
E: SERIO_ID=00
E: SERIO_EXTRA=00
E: MODALIAS=serio:ty01pr00id00ex00
E: SERIO_FIRMWARE_ID=PNP: PNP0f13

P: /devices/platform/i8042/serio2/input/input12
L: 0
E: DEVPATH=/devices/platform/i8042/serio2/input/input12
E: SUBSYSTEM=input
E: PRODUCT=11/2/7/1b1
E: NAME="SynPS/2 Synaptics TouchPad"
E: PHYS="isa0060/serio2/input0"
E: PROP=9
E: EV=b
E: KEY=6420 30000 0 0 0 0
E: ABS=260800011000003
E: MODALIAS=input:b0011v0002p0007e01B1-e0,1,3,k110,111,145,14A,14D,14E,ra0,1,18,1C,2F,35,36,39,mlsfw
E: USEC_INITIALIZED=4953513
E: ID_INPUT=1
E: ID_INPUT_TOUCHPAD=1
E: ID_BUS=i8042
E: ID_SERIAL=noserial
E: ID_PATH=platform-i8042-serio-2
E: ID_PATH_TAG=platform-i8042-serio-2
E: ID_FOR_SEAT=input-platform-i8042-serio-2
E: TAGS=:seat:

P: /devices/platform/i8042/serio2/input/input12/event6
N: input/event6
L: 0
E: DEVPATH=/devices/platform/i8042/serio2/input/input12/event6
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event6
E: MAJOR=13
E: MINOR=70

P: /devices/platform/i8042/serio2/input/input12/mouse0
N: input/mouse0
L: 0
S: input/by-path/platform-i8042-serio-2-mouse
E: DEVPATH=/devices/platform/i8042/serio2/input/input12/mouse0
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/mouse0
E: MAJOR=13
E: MINOR=32
E: USEC_INITIALIZED=16234379
E: ID_INPUT=1
E: ID_INPUT_TOUCHPAD=1
E: ID_BUS=i8042
E: ID_SERIAL=noserial
E: ID_PATH=platform-i8042-serio-2
E: ID_PATH_TAG=platform-i8042-serio-2
E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-2-mouse

P: /devices/platform/i8042/serio3
L: 0
E: DEVPATH=/devices/platform/i8042/serio3
E: SUBSYSTEM=serio
E: SERIO_TYPE=01
E: SERIO_PROTO=00
E: SERIO_ID=00
E: SERIO_EXTRA=00
E: MODALIAS=serio:ty01pr00id00ex00
E: SERIO_FIRMWARE_ID=PNP: PNP0f13

P: /devices/platform/i8042/serio4
L: 0
E: DEVPATH=/devices/platform/i8042/serio4
E: SUBSYSTEM=serio
E: SERIO_TYPE=01
E: SERIO_PROTO=00
E: SERIO_ID=00
E: SERIO_EXTRA=00
E: MODALIAS=serio:ty01pr00id00ex00
E: SERIO_FIRMWARE_ID=PNP: PNP0f13

P: /devices/platform/microcode
L: 0
E: DEVPATH=/devices/platform/microcode
E: SUBSYSTEM=platform
E: MODALIAS=platform:microcode
E: USEC_INITIALIZED=15979601
E: ID_PATH=platform-microcode
E: ID_PATH_TAG=platform-microcode

P: /devices/platform/pcspkr
L: 0
E: DEVPATH=/devices/platform/pcspkr
E: SUBSYSTEM=platform
E: DRIVER=pcspkr
E: MODALIAS=platform:pcspkr
E: USEC_INITIALIZED=15982098
E: ID_PATH=platform-pcspkr
E: ID_PATH_TAG=platform-pcspkr

P: /devices/platform/pcspkr/input/input21
L: 0
E: DEVPATH=/devices/platform/pcspkr/input/input21
E: SUBSYSTEM=input
E: PRODUCT=10/1f/1/100
E: NAME="PC Speaker"
E: PHYS="isa0061/input0"
E: PROP=0
E: EV=40001
E: SND=6
E: MODALIAS=input:b0010v001Fp0001e0100-e0,12,kramls1,2,fw
E: USEC_INITIALIZED=17067315
E: ID_INPUT=1
E: ID_SERIAL=noserial
E: ID_PATH=platform-pcspkr
E: ID_PATH_TAG=platform-pcspkr
E: ID_FOR_SEAT=input-platform-pcspkr
E: TAGS=:seat:

P: /devices/platform/pcspkr/input/input21/event12
N: input/event12
L: 0
E: DEVPATH=/devices/platform/pcspkr/input/input21/event12
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event12
E: MAJOR=13
E: MINOR=76

P: /devices/platform/platform-framebuffer.0
L: 0
E: DEVPATH=/devices/platform/platform-framebuffer.0
E: SUBSYSTEM=platform
E: MODALIAS=platform:platform-framebuffer
E: USEC_INITIALIZED=16008570
E: ID_PATH=platform-platform-framebuffer.0
E: ID_PATH_TAG=platform-platform-framebuffer_0

P: /devices/platform/reg-dummy
L: 0
E: DEVPATH=/devices/platform/reg-dummy
E: SUBSYSTEM=platform
E: DRIVER=reg-dummy
E: MODALIAS=platform:reg-dummy
E: USEC_INITIALIZED=16014071
E: ID_PATH=platform-reg-dummy
E: ID_PATH_TAG=platform-reg-dummy

P: /devices/platform/reg-dummy/regulator/regulator.0
L: 0
E: DEVPATH=/devices/platform/reg-dummy/regulator/regulator.0
E: SUBSYSTEM=regulator

P: /devices/platform/regulatory.0
L: 0
E: DEVPATH=/devices/platform/regulatory.0
E: SUBSYSTEM=platform
E: MODALIAS=platform:regulatory
E: USEC_INITIALIZED=17100653
E: ID_PATH=platform-regulatory.0
E: ID_PATH_TAG=platform-regulatory_0

P: /devices/platform/serial8250
L: 0
E: DEVPATH=/devices/platform/serial8250
E: SUBSYSTEM=platform
E: DRIVER=serial8250
E: MODALIAS=platform:serial8250
E: USEC_INITIALIZED=16072446
E: ID_PATH=platform-serial8250
E: ID_PATH_TAG=platform-serial8250

P: /devices/platform/serial8250/tty/ttyS0
N: ttyS0
L: 0
E: DEVPATH=/devices/platform/serial8250/tty/ttyS0
E: SUBSYSTEM=tty
E: DEVNAME=/dev/ttyS0
E: MAJOR=4
E: MINOR=64
E: USEC_INITIALIZED=16078957
E: ID_MM_CANDIDATE=1
E: TAGS=:systemd:

P: /devices/platform/serial8250/tty/ttyS1
N: ttyS1
L: 0
E: DEVPATH=/devices/platform/serial8250/tty/ttyS1
E: SUBSYSTEM=tty
E: DEVNAME=/dev/ttyS1
E: MAJOR=4
E: MINOR=65
E: USEC_INITIALIZED=16080300
E: ID_MM_CANDIDATE=1
E: TAGS=:systemd:

P: /devices/platform/serial8250/tty/ttyS2
N: ttyS2
L: 0
E: DEVPATH=/devices/platform/serial8250/tty/ttyS2
E: SUBSYSTEM=tty
E: DEVNAME=/dev/ttyS2
E: MAJOR=4
E: MINOR=66
E: USEC_INITIALIZED=16085372
E: ID_MM_CANDIDATE=1
E: TAGS=:systemd:

P: /devices/platform/serial8250/tty/ttyS3
N: ttyS3
L: 0
E: DEVPATH=/devices/platform/serial8250/tty/ttyS3
E: SUBSYSTEM=tty
E: DEVNAME=/dev/ttyS3
E: MAJOR=4
E: MINOR=67
E: USEC_INITIALIZED=16086603
E: ID_MM_CANDIDATE=1
E: TAGS=:systemd:

P: /devices/pnp0/00:00
L: 0
E: DEVPATH=/devices/pnp0/00:00
E: SUBSYSTEM=pnp
E: DRIVER=system

P: /devices/pnp0/00:01
L: 0
E: DEVPATH=/devices/pnp0/00:01
E: SUBSYSTEM=pnp
E: DRIVER=rtc_cmos

P: /devices/pnp0/00:01/cmos_nvram0
L: 0
E: DEVPATH=/devices/pnp0/00:01/cmos_nvram0
E: SUBSYSTEM=nvmem

P: /devices/pnp0/00:01/rtc/rtc0
N: rtc0
L: -100
S: rtc
E: DEVPATH=/devices/pnp0/00:01/rtc/rtc0
E: SUBSYSTEM=rtc
E: DEVNAME=/dev/rtc0
E: MAJOR=252
E: MINOR=0
E: USEC_INITIALIZED=3610037
E: DEVLINKS=/dev/rtc

P: /devices/pnp0/00:02
L: 0
E: DEVPATH=/devices/pnp0/00:02
E: SUBSYSTEM=pnp
E: DRIVER=i8042 kbd

P: /devices/pnp0/00:03
L: 0
E: DEVPATH=/devices/pnp0/00:03
E: SUBSYSTEM=pnp
E: DRIVER=i8042 aux

P: /devices/pnp0/00:04
L: 0
E: DEVPATH=/devices/pnp0/00:04
E: SUBSYSTEM=pnp
E: DRIVER=system

P: /devices/software
L: 0
E: DEVPATH=/devices/software
E: SUBSYSTEM=event_source

P: /devices/system/clockevents/broadcast
L: 0
E: DEVPATH=/devices/system/clockevents/broadcast
E: SUBSYSTEM=clockevents

P: /devices/system/clockevents/clockevent0
L: 0
E: DEVPATH=/devices/system/clockevents/clockevent0
E: SUBSYSTEM=clockevents

P: /devices/system/clockevents/clockevent1
L: 0
E: DEVPATH=/devices/system/clockevents/clockevent1
E: SUBSYSTEM=clockevents

P: /devices/system/clocksource/clocksource0
L: 0
E: DEVPATH=/devices/system/clocksource/clocksource0
E: SUBSYSTEM=clocksource

P: /devices/system/cpu/cpu0
L: 0
E: DEVPATH=/devices/system/cpu/cpu0
E: SUBSYSTEM=cpu
E: DRIVER=processor
E: MODALIAS=cpu:type:x86,ven0000fam0006mod0025:feature:,0000,0001,0002,0003,0004,0005,0006,0007,0008,0009,000B,000C,000D,000E,000F,0010,0011,0013,0015,0016,0017,0018,0019,001A,001B,001C,001D,001F,002B,0034,003B,003D,0068,006B,006C,006D,006F,0070,0072,0074,0075,0076,0078,0079,007C,0080,0082,0083,0084,0087,0088,0089,008D,008E,008F,0091,0097,00C0,00EB,00EC,00F0,00F1,00F3,00F5,00F6,00F9,00FA,00FB,00FD,0165,01C0,01C2,025A,025B,025C,025F

P: /devices/system/cpu/cpu1
L: 0
E: DEVPATH=/devices/system/cpu/cpu1
E: SUBSYSTEM=cpu
E: DRIVER=processor
E: MODALIAS=cpu:type:x86,ven0000fam0006mod0025:feature:,0000,0001,0002,0003,0004,0005,0006,0007,0008,0009,000B,000C,000D,000E,000F,0010,0011,0013,0015,0016,0017,0018,0019,001A,001B,001C,001D,001F,002B,0034,003B,003D,0068,006B,006C,006D,006F,0070,0072,0074,0075,0076,0078,0079,007C,0080,0082,0083,0084,0087,0088,0089,008D,008E,008F,0091,0097,00C0,00EB,00EC,00F0,00F1,00F3,00F5,00F6,00F9,00FA,00FB,00FD,0165,01C0,01C2,025A,025B,025C,025F

P: /devices/system/edac/mc
L: 0
E: DEVPATH=/devices/system/edac/mc
E: SUBSYSTEM=edac

P: /devices/system/machinecheck/machinecheck0
L: 0
E: DEVPATH=/devices/system/machinecheck/machinecheck0
E: SUBSYSTEM=machinecheck

P: /devices/system/machinecheck/machinecheck1
L: 0
E: DEVPATH=/devices/system/machinecheck/machinecheck1
E: SUBSYSTEM=machinecheck

P: /devices/system/memory/memory0
L: 0
E: DEVPATH=/devices/system/memory/memory0
E: SUBSYSTEM=memory

P: /devices/system/memory/memory1
L: 0
E: DEVPATH=/devices/system/memory/memory1
E: SUBSYSTEM=memory

P: /devices/system/memory/memory10
L: 0
E: DEVPATH=/devices/system/memory/memory10
E: SUBSYSTEM=memory

P: /devices/system/memory/memory11
L: 0
E: DEVPATH=/devices/system/memory/memory11
E: SUBSYSTEM=memory

P: /devices/system/memory/memory12
L: 0
E: DEVPATH=/devices/system/memory/memory12
E: SUBSYSTEM=memory

P: /devices/system/memory/memory13
L: 0
E: DEVPATH=/devices/system/memory/memory13
E: SUBSYSTEM=memory

P: /devices/system/memory/memory14
L: 0
E: DEVPATH=/devices/system/memory/memory14
E: SUBSYSTEM=memory

P: /devices/system/memory/memory15
L: 0
E: DEVPATH=/devices/system/memory/memory15
E: SUBSYSTEM=memory

P: /devices/system/memory/memory16
L: 0
E: DEVPATH=/devices/system/memory/memory16
E: SUBSYSTEM=memory

P: /devices/system/memory/memory17
L: 0
E: DEVPATH=/devices/system/memory/memory17
E: SUBSYSTEM=memory

P: /devices/system/memory/memory18
L: 0
E: DEVPATH=/devices/system/memory/memory18
E: SUBSYSTEM=memory

P: /devices/system/memory/memory19
L: 0
E: DEVPATH=/devices/system/memory/memory19
E: SUBSYSTEM=memory

P: /devices/system/memory/memory2
L: 0
E: DEVPATH=/devices/system/memory/memory2
E: SUBSYSTEM=memory

P: /devices/system/memory/memory20
L: 0
E: DEVPATH=/devices/system/memory/memory20
E: SUBSYSTEM=memory

P: /devices/system/memory/memory21
L: 0
E: DEVPATH=/devices/system/memory/memory21
E: SUBSYSTEM=memory

P: /devices/system/memory/memory22
L: 0
E: DEVPATH=/devices/system/memory/memory22
E: SUBSYSTEM=memory

P: /devices/system/memory/memory23
L: 0
E: DEVPATH=/devices/system/memory/memory23
E: SUBSYSTEM=memory

P: /devices/system/memory/memory3
L: 0
E: DEVPATH=/devices/system/memory/memory3
E: SUBSYSTEM=memory

P: /devices/system/memory/memory32
L: 0
E: DEVPATH=/devices/system/memory/memory32
E: SUBSYSTEM=memory

P: /devices/system/memory/memory33
L: 0
E: DEVPATH=/devices/system/memory/memory33
E: SUBSYSTEM=memory

P: /devices/system/memory/memory34
L: 0
E: DEVPATH=/devices/system/memory/memory34
E: SUBSYSTEM=memory

P: /devices/system/memory/memory35
L: 0
E: DEVPATH=/devices/system/memory/memory35
E: SUBSYSTEM=memory

P: /devices/system/memory/memory36
L: 0
E: DEVPATH=/devices/system/memory/memory36
E: SUBSYSTEM=memory

P: /devices/system/memory/memory37
L: 0
E: DEVPATH=/devices/system/memory/memory37
E: SUBSYSTEM=memory

P: /devices/system/memory/memory38
L: 0
E: DEVPATH=/devices/system/memory/memory38
E: SUBSYSTEM=memory

P: /devices/system/memory/memory4
L: 0
E: DEVPATH=/devices/system/memory/memory4
E: SUBSYSTEM=memory

P: /devices/system/memory/memory5
L: 0
E: DEVPATH=/devices/system/memory/memory5
E: SUBSYSTEM=memory

P: /devices/system/memory/memory6
L: 0
E: DEVPATH=/devices/system/memory/memory6
E: SUBSYSTEM=memory

P: /devices/system/memory/memory7
L: 0
E: DEVPATH=/devices/system/memory/memory7
E: SUBSYSTEM=memory

P: /devices/system/memory/memory8
L: 0
E: DEVPATH=/devices/system/memory/memory8
E: SUBSYSTEM=memory

P: /devices/system/memory/memory9
L: 0
E: DEVPATH=/devices/system/memory/memory9
E: SUBSYSTEM=memory

P: /devices/system/node/node0
L: 0
E: DEVPATH=/devices/system/node/node0
E: SUBSYSTEM=node

P: /devices/tracepoint
L: 0
E: DEVPATH=/devices/tracepoint
E: SUBSYSTEM=event_source

P: /devices/uncore
L: 0
E: DEVPATH=/devices/uncore
E: SUBSYSTEM=event_source

P: /devices/uprobe
L: 0
E: DEVPATH=/devices/uprobe
E: SUBSYSTEM=event_source

P: /devices/virtual/bdi/11:0
L: 0
E: DEVPATH=/devices/virtual/bdi/11:0
E: SUBSYSTEM=bdi

P: /devices/virtual/bdi/7:0
L: 0
E: DEVPATH=/devices/virtual/bdi/7:0
E: SUBSYSTEM=bdi

P: /devices/virtual/bdi/7:1
L: 0
E: DEVPATH=/devices/virtual/bdi/7:1
E: SUBSYSTEM=bdi

P: /devices/virtual/bdi/7:2
L: 0
E: DEVPATH=/devices/virtual/bdi/7:2
E: SUBSYSTEM=bdi

P: /devices/virtual/bdi/7:3
L: 0
E: DEVPATH=/devices/virtual/bdi/7:3
E: SUBSYSTEM=bdi

P: /devices/virtual/bdi/7:4
L: 0
E: DEVPATH=/devices/virtual/bdi/7:4
E: SUBSYSTEM=bdi

P: /devices/virtual/bdi/7:5
L: 0
E: DEVPATH=/devices/virtual/bdi/7:5
E: SUBSYSTEM=bdi

P: /devices/virtual/bdi/7:6
L: 0
E: DEVPATH=/devices/virtual/bdi/7:6
E: SUBSYSTEM=bdi

P: /devices/virtual/bdi/7:7
L: 0
E: DEVPATH=/devices/virtual/bdi/7:7
E: SUBSYSTEM=bdi

P: /devices/virtual/bdi/8:0
L: 0
E: DEVPATH=/devices/virtual/bdi/8:0
E: SUBSYSTEM=bdi

P: /devices/virtual/block/loop0
N: loop0
L: 0
E: DEVPATH=/devices/virtual/block/loop0
E: SUBSYSTEM=block
E: DEVNAME=/dev/loop0
E: DEVTYPE=disk
E: MAJOR=7
E: MINOR=0
E: USEC_INITIALIZED=18029286
E: UDISKS_PRESENTATION_NOPOLICY=1
E: SYSTEMD_READY=0
E: TAGS=:systemd:

P: /devices/virtual/block/loop1
N: loop1
L: 0
E: DEVPATH=/devices/virtual/block/loop1
E: SUBSYSTEM=block
E: DEVNAME=/dev/loop1
E: DEVTYPE=disk
E: MAJOR=7
E: MINOR=1
E: USEC_INITIALIZED=18028736
E: UDISKS_PRESENTATION_NOPOLICY=1
E: SYSTEMD_READY=0
E: TAGS=:systemd:

P: /devices/virtual/block/loop2
N: loop2
L: 0
E: DEVPATH=/devices/virtual/block/loop2
E: SUBSYSTEM=block
E: DEVNAME=/dev/loop2
E: DEVTYPE=disk
E: MAJOR=7
E: MINOR=2
E: USEC_INITIALIZED=18027248
E: UDISKS_PRESENTATION_NOPOLICY=1
E: SYSTEMD_READY=0
E: TAGS=:systemd:

P: /devices/virtual/block/loop3
N: loop3
L: 0
E: DEVPATH=/devices/virtual/block/loop3
E: SUBSYSTEM=block
E: DEVNAME=/dev/loop3
E: DEVTYPE=disk
E: MAJOR=7
E: MINOR=3
E: USEC_INITIALIZED=18028596
E: UDISKS_PRESENTATION_NOPOLICY=1
E: SYSTEMD_READY=0
E: TAGS=:systemd:

P: /devices/virtual/block/loop4
N: loop4
L: 0
E: DEVPATH=/devices/virtual/block/loop4
E: SUBSYSTEM=block
E: DEVNAME=/dev/loop4
E: DEVTYPE=disk
E: MAJOR=7
E: MINOR=4
E: USEC_INITIALIZED=18026348
E: UDISKS_PRESENTATION_NOPOLICY=1
E: SYSTEMD_READY=0
E: TAGS=:systemd:

P: /devices/virtual/block/loop5
N: loop5
L: 0
E: DEVPATH=/devices/virtual/block/loop5
E: SUBSYSTEM=block
E: DEVNAME=/dev/loop5
E: DEVTYPE=disk
E: MAJOR=7
E: MINOR=5
E: USEC_INITIALIZED=18027594
E: UDISKS_PRESENTATION_NOPOLICY=1
E: SYSTEMD_READY=0
E: TAGS=:systemd:

P: /devices/virtual/block/loop6
N: loop6
L: 0
E: DEVPATH=/devices/virtual/block/loop6
E: SUBSYSTEM=block
E: DEVNAME=/dev/loop6
E: DEVTYPE=disk
E: MAJOR=7
E: MINOR=6
E: USEC_INITIALIZED=18026611
E: UDISKS_PRESENTATION_NOPOLICY=1
E: SYSTEMD_READY=0
E: TAGS=:systemd:

P: /devices/virtual/block/loop7
N: loop7
L: 0
E: DEVPATH=/devices/virtual/block/loop7
E: SUBSYSTEM=block
E: DEVNAME=/dev/loop7
E: DEVTYPE=disk
E: MAJOR=7
E: MINOR=7
E: USEC_INITIALIZED=18030279
E: UDISKS_PRESENTATION_NOPOLICY=1
E: SYSTEMD_READY=0
E: TAGS=:systemd:

P: /devices/virtual/dmi/id
L: 0
E: DEVPATH=/devices/virtual/dmi/id
E: SUBSYSTEM=dmi
E: MODALIAS=dmi:bvninfowayNoteW7425:bvr1.01.05IT-SL2.1:bd01/17/2011:svnItautecS.A.:pnInfoway:pvrInft:rvnItautecS.A:rnW7425:rvrNotApplicable:cvnItautec:ct9:cvrN/A:

P: /devices/virtual/graphics/fbcon
L: 0
E: DEVPATH=/devices/virtual/graphics/fbcon
E: SUBSYSTEM=graphics

P: /devices/virtual/input/mice
N: input/mice
L: 0
E: DEVPATH=/devices/virtual/input/mice
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/mice
E: MAJOR=13
E: MINOR=63

P: /devices/virtual/mem/full
N: full
L: 0
E: DEVPATH=/devices/virtual/mem/full
E: SUBSYSTEM=mem
E: DEVNAME=/dev/full
E: DEVMODE=0666
E: MAJOR=1
E: MINOR=7

P: /devices/virtual/mem/kmsg
N: kmsg
L: 0
E: DEVPATH=/devices/virtual/mem/kmsg
E: SUBSYSTEM=mem
E: DEVNAME=/dev/kmsg
E: DEVMODE=0644
E: MAJOR=1
E: MINOR=11

P: /devices/virtual/mem/mem
N: mem
L: 0
E: DEVPATH=/devices/virtual/mem/mem
E: SUBSYSTEM=mem
E: DEVNAME=/dev/mem
E: MAJOR=1
E: MINOR=1

P: /devices/virtual/mem/null
N: null
L: 0
E: DEVPATH=/devices/virtual/mem/null
E: SUBSYSTEM=mem
E: DEVNAME=/dev/null
E: DEVMODE=0666
E: MAJOR=1
E: MINOR=3

P: /devices/virtual/mem/port
N: port
L: 0
E: DEVPATH=/devices/virtual/mem/port
E: SUBSYSTEM=mem
E: DEVNAME=/dev/port
E: MAJOR=1
E: MINOR=4

P: /devices/virtual/mem/random
N: random
L: 0
E: DEVPATH=/devices/virtual/mem/random
E: SUBSYSTEM=mem
E: DEVNAME=/dev/random
E: DEVMODE=0666
E: MAJOR=1
E: MINOR=8

P: /devices/virtual/mem/urandom
N: urandom
L: 0
E: DEVPATH=/devices/virtual/mem/urandom
E: SUBSYSTEM=mem
E: DEVNAME=/dev/urandom
E: DEVMODE=0666
E: MAJOR=1
E: MINOR=9

P: /devices/virtual/mem/zero
N: zero
L: 0
E: DEVPATH=/devices/virtual/mem/zero
E: SUBSYSTEM=mem
E: DEVNAME=/dev/zero
E: DEVMODE=0666
E: MAJOR=1
E: MINOR=5

P: /devices/virtual/misc/autofs
N: autofs
L: 0
E: DEVPATH=/devices/virtual/misc/autofs
E: SUBSYSTEM=misc
E: DEVNAME=/dev/autofs
E: DEVMODE=0644
E: MAJOR=10
E: MINOR=235

P: /devices/virtual/misc/cpu_dma_latency
N: cpu_dma_latency
L: 0
E: DEVPATH=/devices/virtual/misc/cpu_dma_latency
E: SUBSYSTEM=misc
E: DEVNAME=/dev/cpu_dma_latency
E: MAJOR=10
E: MINOR=62

P: /devices/virtual/misc/fuse
N: fuse
L: 0
E: DEVPATH=/devices/virtual/misc/fuse
E: SUBSYSTEM=misc
E: DEVNAME=/dev/fuse
E: MAJOR=10
E: MINOR=229

P: /devices/virtual/misc/hpet
N: hpet
L: 0
E: DEVPATH=/devices/virtual/misc/hpet
E: SUBSYSTEM=misc
E: DEVNAME=/dev/hpet
E: MAJOR=10
E: MINOR=228

P: /devices/virtual/misc/loop-control
N: loop-control
L: 0
E: DEVPATH=/devices/virtual/misc/loop-control
E: SUBSYSTEM=misc
E: DEVNAME=/dev/loop-control
E: MAJOR=10
E: MINOR=237

P: /devices/virtual/misc/memory_bandwidth
N: memory_bandwidth
L: 0
E: DEVPATH=/devices/virtual/misc/memory_bandwidth
E: SUBSYSTEM=misc
E: DEVNAME=/dev/memory_bandwidth
E: MAJOR=10
E: MINOR=59

P: /devices/virtual/misc/network_latency
N: network_latency
L: 0
E: DEVPATH=/devices/virtual/misc/network_latency
E: SUBSYSTEM=misc
E: DEVNAME=/dev/network_latency
E: MAJOR=10
E: MINOR=61

P: /devices/virtual/misc/network_throughput
N: network_throughput
L: 0
E: DEVPATH=/devices/virtual/misc/network_throughput
E: SUBSYSTEM=misc
E: DEVNAME=/dev/network_throughput
E: MAJOR=10
E: MINOR=60

P: /devices/virtual/misc/psaux
N: psaux
L: 0
E: DEVPATH=/devices/virtual/misc/psaux
E: SUBSYSTEM=misc
E: DEVNAME=/dev/psaux
E: MAJOR=10
E: MINOR=1

P: /devices/virtual/misc/rfkill
N: rfkill
L: 0
E: DEVPATH=/devices/virtual/misc/rfkill
E: SUBSYSTEM=misc
E: DEVNAME=/dev/rfkill
E: MAJOR=10
E: MINOR=58
E: USEC_INITIALIZED=17096843
E: SYSTEMD_WANTS=systemd-rfkill.socket
E: TAGS=:uaccess:seat:systemd:

P: /devices/virtual/misc/snapshot
N: snapshot
L: 0
E: DEVPATH=/devices/virtual/misc/snapshot
E: SUBSYSTEM=misc
E: DEVNAME=/dev/snapshot
E: MAJOR=10
E: MINOR=231

P: /devices/virtual/misc/uinput
N: uinput
L: 0
E: DEVPATH=/devices/virtual/misc/uinput
E: SUBSYSTEM=misc
E: DEVNAME=/dev/uinput
E: MAJOR=10
E: MINOR=223

P: /devices/virtual/misc/vga_arbiter
N: vga_arbiter
L: 0
E: DEVPATH=/devices/virtual/misc/vga_arbiter
E: SUBSYSTEM=misc
E: DEVNAME=/dev/vga_arbiter
E: MAJOR=10
E: MINOR=63

P: /devices/virtual/net/lo
L: 0
E: DEVPATH=/devices/virtual/net/lo
E: SUBSYSTEM=net
E: INTERFACE=lo
E: IFINDEX=1
E: USEC_INITIALIZED=3637528
E: ID_MM_CANDIDATE=1
E: ID_NET_LINK_FILE=/lib/systemd/network/99-default.link

P: /devices/virtual/sound/timer
N: snd/timer
L: 0
E: DEVPATH=/devices/virtual/sound/timer
E: SUBSYSTEM=sound
E: DEVNAME=/dev/snd/timer
E: MAJOR=116
E: MINOR=33
E: USEC_INITIALIZED=17054688
E: TAGS=:uaccess:

P: /devices/virtual/thermal/cooling_device0
L: 0
E: DEVPATH=/devices/virtual/thermal/cooling_device0
E: SUBSYSTEM=thermal

P: /devices/virtual/thermal/cooling_device1
L: 0
E: DEVPATH=/devices/virtual/thermal/cooling_device1
E: SUBSYSTEM=thermal

P: /devices/virtual/thermal/cooling_device2
L: 0
E: DEVPATH=/devices/virtual/thermal/cooling_device2
E: SUBSYSTEM=thermal

P: /devices/virtual/thermal/cooling_device3
L: 0
E: DEVPATH=/devices/virtual/thermal/cooling_device3
E: SUBSYSTEM=thermal

P: /devices/virtual/thermal/thermal_zone0
L: 0
E: DEVPATH=/devices/virtual/thermal/thermal_zone0
E: SUBSYSTEM=thermal

P: /devices/virtual/thermal/thermal_zone0/hwmon0
L: 0
E: DEVPATH=/devices/virtual/thermal/thermal_zone0/hwmon0
E: SUBSYSTEM=hwmon

P: /devices/virtual/tty/console
N: console
L: 0
E: DEVPATH=/devices/virtual/tty/console
E: SUBSYSTEM=tty
E: DEVNAME=/dev/console
E: MAJOR=5
E: MINOR=1
E: USEC_INITIALIZED=16267369
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/ptmx
N: ptmx
L: 0
E: DEVPATH=/devices/virtual/tty/ptmx
E: SUBSYSTEM=tty
E: DEVNAME=/dev/ptmx
E: DEVMODE=0666
E: MAJOR=5
E: MINOR=2
E: USEC_INITIALIZED=16271193
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty
N: tty
L: 0
E: DEVPATH=/devices/virtual/tty/tty
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty
E: DEVMODE=0666
E: MAJOR=5
E: MINOR=0
E: USEC_INITIALIZED=16274243
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty0
N: tty0
L: 0
E: DEVPATH=/devices/virtual/tty/tty0
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty0
E: MAJOR=4
E: MINOR=0
E: USEC_INITIALIZED=16275158
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty1
N: tty1
L: 0
E: DEVPATH=/devices/virtual/tty/tty1
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty1
E: MAJOR=4
E: MINOR=1
E: USEC_INITIALIZED=16276154
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty10
N: tty10
L: 0
E: DEVPATH=/devices/virtual/tty/tty10
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty10
E: MAJOR=4
E: MINOR=10
E: USEC_INITIALIZED=16278131
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty11
N: tty11
L: 0
E: DEVPATH=/devices/virtual/tty/tty11
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty11
E: MAJOR=4
E: MINOR=11
E: USEC_INITIALIZED=16279838
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty12
N: tty12
L: 0
E: DEVPATH=/devices/virtual/tty/tty12
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty12
E: MAJOR=4
E: MINOR=12
E: USEC_INITIALIZED=16281886
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty13
N: tty13
L: 0
E: DEVPATH=/devices/virtual/tty/tty13
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty13
E: MAJOR=4
E: MINOR=13
E: USEC_INITIALIZED=16284251
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty14
N: tty14
L: 0
E: DEVPATH=/devices/virtual/tty/tty14
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty14
E: MAJOR=4
E: MINOR=14
E: USEC_INITIALIZED=16286221
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty15
N: tty15
L: 0
E: DEVPATH=/devices/virtual/tty/tty15
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty15
E: MAJOR=4
E: MINOR=15
E: USEC_INITIALIZED=16291753
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty16
N: tty16
L: 0
E: DEVPATH=/devices/virtual/tty/tty16
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty16
E: MAJOR=4
E: MINOR=16
E: USEC_INITIALIZED=16294795
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty17
N: tty17
L: 0
E: DEVPATH=/devices/virtual/tty/tty17
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty17
E: MAJOR=4
E: MINOR=17
E: USEC_INITIALIZED=16297831
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty18
N: tty18
L: 0
E: DEVPATH=/devices/virtual/tty/tty18
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty18
E: MAJOR=4
E: MINOR=18
E: USEC_INITIALIZED=16301331
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty19
N: tty19
L: 0
E: DEVPATH=/devices/virtual/tty/tty19
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty19
E: MAJOR=4
E: MINOR=19
E: USEC_INITIALIZED=16305378
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty2
N: tty2
L: 0
E: DEVPATH=/devices/virtual/tty/tty2
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty2
E: MAJOR=4
E: MINOR=2
E: USEC_INITIALIZED=16308822
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty20
N: tty20
L: 0
E: DEVPATH=/devices/virtual/tty/tty20
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty20
E: MAJOR=4
E: MINOR=20
E: USEC_INITIALIZED=16312321
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty21
N: tty21
L: 0
E: DEVPATH=/devices/virtual/tty/tty21
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty21
E: MAJOR=4
E: MINOR=21
E: USEC_INITIALIZED=16315812
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty22
N: tty22
L: 0
E: DEVPATH=/devices/virtual/tty/tty22
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty22
E: MAJOR=4
E: MINOR=22
E: USEC_INITIALIZED=16319330
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty23
N: tty23
L: 0
E: DEVPATH=/devices/virtual/tty/tty23
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty23
E: MAJOR=4
E: MINOR=23
E: USEC_INITIALIZED=16322814
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty24
N: tty24
L: 0
E: DEVPATH=/devices/virtual/tty/tty24
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty24
E: MAJOR=4
E: MINOR=24
E: USEC_INITIALIZED=16326316
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty25
N: tty25
L: 0
E: DEVPATH=/devices/virtual/tty/tty25
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty25
E: MAJOR=4
E: MINOR=25
E: USEC_INITIALIZED=16330127
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty26
N: tty26
L: 0
E: DEVPATH=/devices/virtual/tty/tty26
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty26
E: MAJOR=4
E: MINOR=26
E: USEC_INITIALIZED=16331062
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty27
N: tty27
L: 0
E: DEVPATH=/devices/virtual/tty/tty27
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty27
E: MAJOR=4
E: MINOR=27
E: USEC_INITIALIZED=16333966
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty28
N: tty28
L: 0
E: DEVPATH=/devices/virtual/tty/tty28
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty28
E: MAJOR=4
E: MINOR=28
E: USEC_INITIALIZED=16336762
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty29
N: tty29
L: 0
E: DEVPATH=/devices/virtual/tty/tty29
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty29
E: MAJOR=4
E: MINOR=29
E: USEC_INITIALIZED=16340194
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty3
N: tty3
L: 0
E: DEVPATH=/devices/virtual/tty/tty3
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty3
E: MAJOR=4
E: MINOR=3
E: USEC_INITIALIZED=16343584
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty30
N: tty30
L: 0
E: DEVPATH=/devices/virtual/tty/tty30
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty30
E: MAJOR=4
E: MINOR=30
E: USEC_INITIALIZED=16346787
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty31
N: tty31
L: 0
E: DEVPATH=/devices/virtual/tty/tty31
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty31
E: MAJOR=4
E: MINOR=31
E: USEC_INITIALIZED=16351853
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty32
N: tty32
L: 0
E: DEVPATH=/devices/virtual/tty/tty32
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty32
E: MAJOR=4
E: MINOR=32
E: USEC_INITIALIZED=16353519
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty33
N: tty33
L: 0
E: DEVPATH=/devices/virtual/tty/tty33
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty33
E: MAJOR=4
E: MINOR=33
E: USEC_INITIALIZED=16356850
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty34
N: tty34
L: 0
E: DEVPATH=/devices/virtual/tty/tty34
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty34
E: MAJOR=4
E: MINOR=34
E: USEC_INITIALIZED=16360148
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty35
N: tty35
L: 0
E: DEVPATH=/devices/virtual/tty/tty35
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty35
E: MAJOR=4
E: MINOR=35
E: USEC_INITIALIZED=16363522
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty36
N: tty36
L: 0
E: DEVPATH=/devices/virtual/tty/tty36
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty36
E: MAJOR=4
E: MINOR=36
E: USEC_INITIALIZED=16366778
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty37
N: tty37
L: 0
E: DEVPATH=/devices/virtual/tty/tty37
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty37
E: MAJOR=4
E: MINOR=37
E: USEC_INITIALIZED=16371137
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty38
N: tty38
L: 0
E: DEVPATH=/devices/virtual/tty/tty38
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty38
E: MAJOR=4
E: MINOR=38
E: USEC_INITIALIZED=16374471
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty39
N: tty39
L: 0
E: DEVPATH=/devices/virtual/tty/tty39
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty39
E: MAJOR=4
E: MINOR=39
E: USEC_INITIALIZED=16373625
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty4
N: tty4
L: 0
E: DEVPATH=/devices/virtual/tty/tty4
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty4
E: MAJOR=4
E: MINOR=4
E: USEC_INITIALIZED=16377596
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty40
N: tty40
L: 0
E: DEVPATH=/devices/virtual/tty/tty40
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty40
E: MAJOR=4
E: MINOR=40
E: USEC_INITIALIZED=16376763
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty41
N: tty41
L: 0
E: DEVPATH=/devices/virtual/tty/tty41
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty41
E: MAJOR=4
E: MINOR=41
E: USEC_INITIALIZED=16380722
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty42
N: tty42
L: 0
E: DEVPATH=/devices/virtual/tty/tty42
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty42
E: MAJOR=4
E: MINOR=42
E: USEC_INITIALIZED=16379853
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty43
N: tty43
L: 0
E: DEVPATH=/devices/virtual/tty/tty43
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty43
E: MAJOR=4
E: MINOR=43
E: USEC_INITIALIZED=16383685
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty44
N: tty44
L: 0
E: DEVPATH=/devices/virtual/tty/tty44
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty44
E: MAJOR=4
E: MINOR=44
E: USEC_INITIALIZED=16382845
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty45
N: tty45
L: 0
E: DEVPATH=/devices/virtual/tty/tty45
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty45
E: MAJOR=4
E: MINOR=45
E: USEC_INITIALIZED=16386559
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty46
N: tty46
L: 0
E: DEVPATH=/devices/virtual/tty/tty46
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty46
E: MAJOR=4
E: MINOR=46
E: USEC_INITIALIZED=16385726
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty47
N: tty47
L: 0
E: DEVPATH=/devices/virtual/tty/tty47
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty47
E: MAJOR=4
E: MINOR=47
E: USEC_INITIALIZED=16389588
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty48
N: tty48
L: 0
E: DEVPATH=/devices/virtual/tty/tty48
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty48
E: MAJOR=4
E: MINOR=48
E: USEC_INITIALIZED=16388728
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty49
N: tty49
L: 0
E: DEVPATH=/devices/virtual/tty/tty49
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty49
E: MAJOR=4
E: MINOR=49
E: USEC_INITIALIZED=16391959
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty5
N: tty5
L: 0
E: DEVPATH=/devices/virtual/tty/tty5
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty5
E: MAJOR=4
E: MINOR=5
E: USEC_INITIALIZED=16391121
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty50
N: tty50
L: 0
E: DEVPATH=/devices/virtual/tty/tty50
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty50
E: MAJOR=4
E: MINOR=50
E: USEC_INITIALIZED=16394462
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty51
N: tty51
L: 0
E: DEVPATH=/devices/virtual/tty/tty51
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty51
E: MAJOR=4
E: MINOR=51
E: USEC_INITIALIZED=16393626
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty52
N: tty52
L: 0
E: DEVPATH=/devices/virtual/tty/tty52
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty52
E: MAJOR=4
E: MINOR=52
E: USEC_INITIALIZED=16400183
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty53
N: tty53
L: 0
E: DEVPATH=/devices/virtual/tty/tty53
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty53
E: MAJOR=4
E: MINOR=53
E: USEC_INITIALIZED=16398272
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty54
N: tty54
L: 0
E: DEVPATH=/devices/virtual/tty/tty54
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty54
E: MAJOR=4
E: MINOR=54
E: USEC_INITIALIZED=16399426
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty55
N: tty55
L: 0
E: DEVPATH=/devices/virtual/tty/tty55
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty55
E: MAJOR=4
E: MINOR=55
E: USEC_INITIALIZED=16402596
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty56
N: tty56
L: 0
E: DEVPATH=/devices/virtual/tty/tty56
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty56
E: MAJOR=4
E: MINOR=56
E: USEC_INITIALIZED=16401754
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty57
N: tty57
L: 0
E: DEVPATH=/devices/virtual/tty/tty57
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty57
E: MAJOR=4
E: MINOR=57
E: USEC_INITIALIZED=16404858
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty58
N: tty58
L: 0
E: DEVPATH=/devices/virtual/tty/tty58
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty58
E: MAJOR=4
E: MINOR=58
E: USEC_INITIALIZED=16404022
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty59
N: tty59
L: 0
E: DEVPATH=/devices/virtual/tty/tty59
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty59
E: MAJOR=4
E: MINOR=59
E: USEC_INITIALIZED=16407030
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty6
N: tty6
L: 0
E: DEVPATH=/devices/virtual/tty/tty6
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty6
E: MAJOR=4
E: MINOR=6
E: USEC_INITIALIZED=16406202
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty60
N: tty60
L: 0
E: DEVPATH=/devices/virtual/tty/tty60
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty60
E: MAJOR=4
E: MINOR=60
E: USEC_INITIALIZED=16409248
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty61
N: tty61
L: 0
E: DEVPATH=/devices/virtual/tty/tty61
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty61
E: MAJOR=4
E: MINOR=61
E: USEC_INITIALIZED=16408413
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty62
N: tty62
L: 0
E: DEVPATH=/devices/virtual/tty/tty62
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty62
E: MAJOR=4
E: MINOR=62
E: USEC_INITIALIZED=16420159
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty63
N: tty63
L: 0
E: DEVPATH=/devices/virtual/tty/tty63
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty63
E: MAJOR=4
E: MINOR=63
E: USEC_INITIALIZED=16410443
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty7
N: tty7
L: 0
E: DEVPATH=/devices/virtual/tty/tty7
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty7
E: MAJOR=4
E: MINOR=7
E: USEC_INITIALIZED=16417447
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty8
N: tty8
L: 0
E: DEVPATH=/devices/virtual/tty/tty8
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty8
E: MAJOR=4
E: MINOR=8
E: USEC_INITIALIZED=16419890
E: ID_MM_CANDIDATE=1

P: /devices/virtual/tty/tty9
N: tty9
L: 0
E: DEVPATH=/devices/virtual/tty/tty9
E: SUBSYSTEM=tty
E: DEVNAME=/dev/tty9
E: MAJOR=4
E: MINOR=9
E: USEC_INITIALIZED=16421368
E: ID_MM_CANDIDATE=1

P: /devices/virtual/vc/vcs
N: vcs
L: 0
E: DEVPATH=/devices/virtual/vc/vcs
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcs
E: MAJOR=7
E: MINOR=0

P: /devices/virtual/vc/vcs1
N: vcs1
L: 0
E: DEVPATH=/devices/virtual/vc/vcs1
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcs1
E: MAJOR=7
E: MINOR=1

P: /devices/virtual/vc/vcs2
N: vcs2
L: 0
E: DEVPATH=/devices/virtual/vc/vcs2
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcs2
E: MAJOR=7
E: MINOR=2

P: /devices/virtual/vc/vcs3
N: vcs3
L: 0
E: DEVPATH=/devices/virtual/vc/vcs3
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcs3
E: MAJOR=7
E: MINOR=3

P: /devices/virtual/vc/vcs4
N: vcs4
L: 0
E: DEVPATH=/devices/virtual/vc/vcs4
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcs4
E: MAJOR=7
E: MINOR=4

P: /devices/virtual/vc/vcs5
N: vcs5
L: 0
E: DEVPATH=/devices/virtual/vc/vcs5
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcs5
E: MAJOR=7
E: MINOR=5

P: /devices/virtual/vc/vcs6
N: vcs6
L: 0
E: DEVPATH=/devices/virtual/vc/vcs6
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcs6
E: MAJOR=7
E: MINOR=6

P: /devices/virtual/vc/vcs7
N: vcs7
L: 0
E: DEVPATH=/devices/virtual/vc/vcs7
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcs7
E: MAJOR=7
E: MINOR=7

P: /devices/virtual/vc/vcs9
N: vcs9
L: 0
E: DEVPATH=/devices/virtual/vc/vcs9
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcs9
E: MAJOR=7
E: MINOR=9

P: /devices/virtual/vc/vcsa
N: vcsa
L: 0
E: DEVPATH=/devices/virtual/vc/vcsa
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsa
E: MAJOR=7
E: MINOR=128

P: /devices/virtual/vc/vcsa1
N: vcsa1
L: 0
E: DEVPATH=/devices/virtual/vc/vcsa1
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsa1
E: MAJOR=7
E: MINOR=129

P: /devices/virtual/vc/vcsa2
N: vcsa2
L: 0
E: DEVPATH=/devices/virtual/vc/vcsa2
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsa2
E: MAJOR=7
E: MINOR=130

P: /devices/virtual/vc/vcsa3
N: vcsa3
L: 0
E: DEVPATH=/devices/virtual/vc/vcsa3
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsa3
E: MAJOR=7
E: MINOR=131

P: /devices/virtual/vc/vcsa4
N: vcsa4
L: 0
E: DEVPATH=/devices/virtual/vc/vcsa4
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsa4
E: MAJOR=7
E: MINOR=132

P: /devices/virtual/vc/vcsa5
N: vcsa5
L: 0
E: DEVPATH=/devices/virtual/vc/vcsa5
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsa5
E: MAJOR=7
E: MINOR=133

P: /devices/virtual/vc/vcsa6
N: vcsa6
L: 0
E: DEVPATH=/devices/virtual/vc/vcsa6
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsa6
E: MAJOR=7
E: MINOR=134

P: /devices/virtual/vc/vcsa7
N: vcsa7
L: 0
E: DEVPATH=/devices/virtual/vc/vcsa7
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsa7
E: MAJOR=7
E: MINOR=135

P: /devices/virtual/vc/vcsa9
N: vcsa9
L: 0
E: DEVPATH=/devices/virtual/vc/vcsa9
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsa9
E: MAJOR=7
E: MINOR=137

P: /devices/virtual/vc/vcsu
N: vcsu
L: 0
E: DEVPATH=/devices/virtual/vc/vcsu
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsu
E: MAJOR=7
E: MINOR=64

P: /devices/virtual/vc/vcsu1
N: vcsu1
L: 0
E: DEVPATH=/devices/virtual/vc/vcsu1
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsu1
E: MAJOR=7
E: MINOR=65

P: /devices/virtual/vc/vcsu2
N: vcsu2
L: 0
E: DEVPATH=/devices/virtual/vc/vcsu2
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsu2
E: MAJOR=7
E: MINOR=66

P: /devices/virtual/vc/vcsu3
N: vcsu3
L: 0
E: DEVPATH=/devices/virtual/vc/vcsu3
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsu3
E: MAJOR=7
E: MINOR=67

P: /devices/virtual/vc/vcsu4
N: vcsu4
L: 0
E: DEVPATH=/devices/virtual/vc/vcsu4
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsu4
E: MAJOR=7
E: MINOR=68

P: /devices/virtual/vc/vcsu5
N: vcsu5
L: 0
E: DEVPATH=/devices/virtual/vc/vcsu5
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsu5
E: MAJOR=7
E: MINOR=69

P: /devices/virtual/vc/vcsu6
N: vcsu6
L: 0
E: DEVPATH=/devices/virtual/vc/vcsu6
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsu6
E: MAJOR=7
E: MINOR=70

P: /devices/virtual/vc/vcsu7
N: vcsu7
L: 0
E: DEVPATH=/devices/virtual/vc/vcsu7
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsu7
E: MAJOR=7
E: MINOR=71

P: /devices/virtual/vc/vcsu9
N: vcsu9
L: 0
E: DEVPATH=/devices/virtual/vc/vcsu9
E: SUBSYSTEM=vc
E: DEVNAME=/dev/vcsu9
E: MAJOR=7
E: MINOR=73

P: /devices/virtual/vtconsole/vtcon0
L: 0
E: DEVPATH=/devices/virtual/vtconsole/vtcon0
E: SUBSYSTEM=vtconsole

P: /devices/virtual/vtconsole/vtcon1
L: 0
E: DEVPATH=/devices/virtual/vtconsole/vtcon1
E: SUBSYSTEM=vtconsole

P: /devices/virtual/workqueue/writeback
L: 0
E: DEVPATH=/devices/virtual/workqueue/writeback
E: SUBSYSTEM=workqueue

-*-*-*-*-
Thanks,

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #14027.

### CODE REVIEW

**Comment by mbiebl** [comment]
First of, thanks for working on this @yuwata !

So this only partially changes the behaviour fo `PROGRAM`?
But there are other mechanisms like `RUN` or `IMPORT` which run internal/external tools and can fail for various reasons. I think in general we should not fail early while processing udev rules.

**Comment by keszybz** [comment]
Yep, we want this change. Let's make the behaviour the same for PROGRAM/IMPORT/RUN though.

File: src/udev/udev-rules.c [hunk 1]
```diff
@@ -1671,10 +1671,11 @@ static int udev_rule_apply_token_to_event(
...
 
                 r = udev_event_spawn(event, timeout_usec, true, buf, result, sizeof(result));
-                if (r < 0)
-                        return log_rule_error_errno(dev, rules, r, "Failed to execute '%s': %m", buf);
-                if (r > 0)
+                if (r != 0) {
+                        if (r < 0)
+                                log_rule_warning_errno(dev, rules, r, "Failed to execute '%s', ignoring: %m", buf);
                         return token->op == OP_NOMATCH;
+                }
```
Comment (keszybz) [inline src/udev/udev-rules.c:1680]: Maybe write this as
```C
if (r < 0)
        log_rule_warning_errno(dev, rules, r, "Failed to execute '%s', ignoring: %m", buf);
if (r != 0)
         return token->op == OP_NOMATCH;
```

**Comment by yuwata** [comment]
Updated. PTAL.

**Comment by yuwata** [comment]
Wow, all ubuntu CIs are red...

**Comment by mbiebl** [comment]
@yuwata apologies, this was my fault. I reorganised the branch names to follow DEP-14 [1].
The new `master` branch is now called `debian/master`.
To unbreak CI I added the `master` branch back.
@ddstreet, @martinpitt, @evverx : what are the places that would need to be changed to use `debian/master`? Would be great if you can make that switch.
Once that is done, I'd turn of the old `master` branch



[1] https://dep-team.pages.debian.net/deps/dep14/

**Comment by keszybz** [comment]
LGTM.

**Comment by martinpitt** [comment]
@mbiebl: Just in the GitHub webhook URLs, I changed them to run branch "debian/master" now. @keszybz , @evverx , please let me know if something goes wrong there. If that survived a PR run or two, then @mbiebl can retire the old master branch.

**Comment by mbiebl** [comment]
thanks @martinpitt, @yuwata
