### PR TITLE
sd-ndisc: handle invalid DNSSL option gracefully

### LINKED ISSUE #31168: networkd: "State changed: configured -> failed" on receiving malformed DNSSL RA options
```sh
eived Router Advertisement: flags none preference medium lifetime 30min
host0: NDISC: Invoking callback for 'router' event.
host0: Requesting NDisc route (configuring,configured): dst: n/a, src: n/a, gw: fe80::741a:afff:fe88:1910, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
host0: Failed to get DNSSL addresses: Invalid argument
host0: Failed
host0: State changed: configured -> failed
Sent message type
```
The DNSSL option was
```python
>>> p[ICMPv6NDOptDNSSL].show()
###[ ICMPv6 Neighbor Discovery Option - DNS Search List Option ]###
  type      = 31
  len       = 14
  res       = 61032
  lifetime  = 2968794681
  searchlist= ['\\xbc\x0b\\xbc\\xa9\\x97q7\\xad\\x86\\x80\x14.X\\xaa\\x8a\\x.7\\xa1\\xbe\\x91Y\x00\\xc4\\xe8\\xdd\\xd8m\\xe5JzqBtE\\x9e.\\xfd\\x9dq\x1d\\xd0\\xc0T\x0cM\x1f\\xbf\\x90\\xd9yX\\xc0\x1d\\xa39ϸ\\xec.xd2\\xe4Ͷ\x13/\\xc0F\\xe8\x07?\\xaa(\\xa5#\\xf1\\xf0\\xca\\xd3\x19?\\xfal|\\xec\x1b\\xcfq\\xeb\\xbah\x1b\\x8e}\\x93~\x0b\\x9f\\x.b\x12\\x9cu"_\x12\x00.']
```
```python
>>> hexdump(p[ICMPv6NDOptDNSSL])
0000  1F 0E EE 68 B0 F4 36 39 2C BC 0B BC A9 97 71 37  ...h..69,.....q7
0010  AD 86 80 14 2E 58 AA 8A B7 A1 BE 91 59 00 C4 E8  .....X......Y...
0020  DD D8 6D E5 4A 7A 71 42 74 45 9E 2E FD 9D 71 1D  ..m.JzqBtE....q.
0030  D0 C0 54 0C 4D 1F BF 90 D9 79 58 C0 1D A3 39 CF  ..T.M....yX...9.
0040  B8 EC D2 E4 CD B6 13 2F C0 46 E8 07 3F AA 28 A5  ......./.F..?.(.
0050  23 F1 F0 CA D3 19 3F FA 6C 7C EC 1B CF 71 EB BA  #.....?.l|...q..
0060  68 1B 8E 7D 93 7E 0B 9F DB 12 9C 75 22 5F 12 00  h..}.~.....u"_..
```
Currently I have to restart networkd every 10 seconds to keep the fuzzer going.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #31168.

### CODE REVIEW

File: src/libsystemd-network/ndisc-router.c [hunk 1]
```diff
@@ -717,7 +717,7 @@ int sd_ndisc_router_dnssl_get_domains(sd_ndisc_router *rt, char ***ret) {
                                 e[n] = 0;
                                 r = dns_name_normalize(e, 0, &normalized);
                                 if (r < 0)
-                                        return r;
+                                        return r == -ENOMEM ? -ENOMEM : -EBADMSG;
```
Comment (evverx) [inline src/libsystemd-network/ndisc-router.c:724]: Looks reasonable. It seems something like that should be added to https://github.com/systemd/systemd/pull/30952.

As far as I can tell the issue is gone. networkd also withstood a gazillion nonsensical DNSSL options I sent. If anything else pops up it's unlikely to be related to that issue. LGTM. Thanks!

Comment (poettering) [inline src/libsystemd-network/ndisc-router.c:724]: maybe add debug logging here, logging the original error code here first?

File: src/libsystemd-network/ndisc-router.c [hunk 2]
```diff
@@ -754,7 +754,7 @@ int sd_ndisc_router_dnssl_get_domains(sd_ndisc_router *rt, char ***ret) {
 
                 r = dns_label_escape((char*) p+1, *p, e + n, DNS_LABEL_ESCAPED_MAX);
                 if (r < 0)
-                        return r;
+                        return r == -ENOMEM ? -ENOMEM : -EBADMSG;
```
Comment (poettering) [inline src/libsystemd-network/ndisc-router.c:765]: ditto

File: src/libsystemd-network/ndisc-router.c (hunk 1 above)
Comment (poettering) [reply src/libsystemd-network/ndisc-router.c:724]: i mean, it might be nice so that the original error code is surfaced before we convert it into a more generic one.
