### PR TITLE
networkd/dhcp: shorten overlong hostname

### LINKED ISSUE #7563: when receiving overly long DHCP fqdns for the local system, truncate at first dot, to make them single label, until they fit in the Linux hostname length limit
### Submission type

 - Bug report

### systemd version the issue has been seen with

```
$ sudo init --version
systemd 234
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN default-hierarchy=legacy
```

### Used distribution

> Container Linux (CoreOS) 1520.8.0

More information at https://github.com/coreos/bugs/issues/2273

### In case of bug report: Expected behaviour you didn't see

systemd networkd fails to set hostname on GCE instances with sufficiently long instance name, leaving hostname as `localhost`

### In case of bug report: Steps to reproduce the problem

1. Launch container linux instance in GCE with a "long" instance name and / or instance group name, causing the FQDN to exceed 64 bytes.
1. Look at the journalctl -b logs for a hostname setting error
1. Notice that the hostname is set to localhost and not the instance name.

COS (Google's internal one powering GKE) seems to set it correctly, even if the instance name is long.

### PR DESCRIPTION
**Pull request by lucab**
This commit updates networkd behavior to check if the hostname option
received via DHCP is too long for Linux limit, and in case shorten it.
An overlong hostname will be truncated to the first dot or to
`HOST_MAX_LEN`, whatever comes earlier.

Fixes #7563

### CODE REVIEW

File: src/basic/hostname-util.c [hunk 1]
```diff
@@ -221,6 +221,39 @@ int sethostname_idempotent(const char *s) {
...
+                *ret = h;
+                return 0;
+        }
+
+        for (p = h; *p; p++) {
+                if (*p == '.') {
+                        *p = 0;
+                        break;
+                }
+        }
```
Comment (poettering) [inline src/basic/hostname-util.c]:
```
p = strchr(h, '.');
if (!p)
        return -EDOM;
*p = 0;
`` `

File: src/basic/hostname-util.c [hunk 2]
```diff
@@ -221,6 +221,39 @@ int sethostname_idempotent(const char *s) {
...
+
+        strshorten(h, HOST_NAME_MAX);
```
Comment (poettering) [inline src/basic/hostname-util.c]: hmm, this should not be necessary, the first label should not be longer than 64 chars anyway...

File: src/basic/hostname-util.c [hunk 3]
```diff
@@ -221,6 +221,39 @@ int sethostname_idempotent(const char *s) {
...
+
+        if (strlen(h) == 0)
```
Comment (poettering) [inline src/basic/hostname-util.c]: strlen() is O(n). If all you want to check is whether the string is empty, is "isempty()" instead...

That said, i think it would be better to instead just call hostname_is_valid(…, false) here

File: src/basic/hostname-util.c [hunk 4]
```diff
@@ -221,6 +221,39 @@ int sethostname_idempotent(const char *s) {
...
+                return -EFAULT;
```
Comment (poettering) [inline src/basic/hostname-util.c]: uh, EFAULT is a strange choice i think, it's has a very clear meaning regarding memory issues which might potentially happen here too. Pick any other error, for example -EDOM or so...

Comment (poettering) [reply src/basic/hostname-util.c]: also, `h` is leaked here

File: src/basic/hostname-util.c [hunk 5]
```diff
@@ -221,6 +221,39 @@ int sethostname_idempotent(const char *s) {
...
+
+        *ret = h;
+        return 0;
```
Comment (poettering) [inline src/basic/hostname-util.c]: consider returning `0` when the name was Ok anyway, and `1` if we shortened it, so that the caller knows about that.

File: src/network/networkd-dhcp4.c [hunk 6]
```diff
@@ -462,12 +462,19 @@ static int dhcp_lease_acquired(sd_dhcp_client *client, Link *link) {
...
-                        hostname = link->network->dhcp_hostname;
+                        dhcpname = link->network->dhcp_hostname;
                 else
-                        (void) sd_dhcp_lease_get_hostname(lease, &hostname);
+                        (void) sd_dhcp_lease_get_hostname(lease, &dhcpname);
+
+                if (dhcpname) {
+                        r = shorten_overlong(dhcpname, &hostname);
+                        if (r < 0)
+                                log_link_error_errno(link, r, "Failed to shorten DHCP hostname '%s': %m", dhcpname);
```
Comment (poettering) [inline src/network/networkd-dhcp4.c]: i think we should log here about the shortening. if you make shorten_overlong() return == 0 and > 0 as suggested above we could add a notice message here saying "DHCP supplied hostname too long for Linux, shortened from %s to %s" or so...

Also, the error case should be downgraded to warning really, as we proceed otherwise, the issue isn't fatal. And we should indicate that, maybe by suffixing the error message with "Unable to shorten DHCP supplied hostname '%s', ignoring: %m"

File: src/basic/hostname-util.c (hunk 4 above)
Comment (lucab) [reply src/basic/hostname-util.c]: `EFAULT` was to mimic `sethostname(2)`, but I just realized I completely misread its meaning. I'll go for -EDOM.

File: src/basic/hostname-util.c (hunk 2 above)
Comment (lucab) [reply src/basic/hostname-util.c]: Not sure I got your point, input could still be a single overlong label like at https://github.com/systemd/systemd/pull/7616/files#diff-cedcecfd5de09ead4c57bf267ed1e705R223.

Comment (poettering) [reply src/basic/hostname-util.c]: are you sure it could be? iirc dhcp encodes the fqdn in DNS-style binary encoding, and that doesn't cover labels longer than 64 chars, i.e. the encoding already makes that impossible...

Comment (poettering) [reply src/basic/hostname-util.c]: (but anyway, i don't really care about this one, i just don't hink it will ever have any effect)

Comment (lucab) [reply src/basic/hostname-util.c]: Now I see. No, I think that this specific DHCP option is just a single-byte length plus a sequence of characters: https://tools.ietf.org/html/rfc2132#section-3.17

Comment (poettering) [reply src/basic/hostname-util.c]: ah, ok, then that makes sense.

**Comment by lucab** [comment]
Rebased, I should have addressed all previous comments. Changed in this revision:
 * s/EFAULT/EDOM/
 * using strchr instead of hand-made loop
 * changed strlen checks to hostname_is_valid
 * freeing h on error (is there a more idiomatic way instead of this free-before-return?)
 * changed error log to a warning one
 * added a r=1 return code and a corresponding notice log
