### PR TITLE
core/manager: falling back to execute generators without sandboxing

### LINKED ISSUE #26474: systemd 253: cannot start container with init: "Failed to fork: Operation not permitted"
### systemd version the issue has been seen with

253 (253-1-arch)

### Used distribution

Arch Linux

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Init starts up in container (output of `podman run --rm -it archlinux:latest /usr/sbin/init`, which right now uses systemd 252):
```
systemd 252.5-1-arch running in system mode (+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified)
Detected virtualization podman.
Detected architecture x86-64.
Detected first boot.

Welcome to Arch Linux!

Initializing machine ID from container UUID.
Failed to mount /run/machine-id (type n/a) on /etc/machine-id (MS_BIND ""): Operation not permitted
bpf-lsm: BPF LSM hook not enabled in the kernel, BPF LSM not supported
Populated /etc with preset unit settings.
Queued start job for default target Graphical Interface.
[  OK  ] Created slice Slice /system/getty.
...
```

### Unexpected behaviour you saw

```
systemd 253-1-arch running in system mode (+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified)
Detected virtualization podman.
Detected architecture x86-64.
Detected first boot.

Welcome to Arch Linux!

Initializing machine ID from container UUID.
Failed to mount /run/machine-id (type n/a) on /etc/machine-id (MS_BIND ""): Operation not permitted
bpf-lsm: BPF LSM hook not enabled in the kernel, BPF LSM not supported
Failed to fork: Operation not permitted
[!!!!!!] Failed to start up manager.
Exiting PID 1...
```

### Steps to reproduce the problem

Create an image with the latest systemd (253) in it.

Dockerfile:
```
FROM archlinux:latest
RUN pacman -Syu --noconfirm # so you actually get systemd 253
CMD /usr/sbin/init
```
Build and run with podman:
```sh
podman build -t archlinux-253 .
podman run --rm -it archlinux-253
```
Alternatively, build and run with docker:
```
docker build -t archlinux-253 .
docker run --tmpfs /tmp:exec --tmpfs /run:exec -t archlinux-253 sh -c 'mount -o remount,rw /sys/fs/cgroup/ ; exec /usr/sbin/init'
```
Both produce the same result.

The same seems to happen with Fedora rawhide according to https://bugzilla.redhat.com/show_bug.cgi?id=2165004 (has apparently been using systemd-253~rc1-1.fc38 and systemd-253~rc2-3.fc38). I guess this is a problem with systemd itself and not something specific to Arch Linux or Fedora rawhide, but I couldn't find an issue here, so here we go...

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Output of `podman run --env SYSTEMD_LOG_LEVEL=debug --rm -it archlinux-253`:

systemd 253-1-arch running in system mode (+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified)
Detected virtualization podman.
Detected architecture x86-64.
Detected first boot.
Kernel version 6.1.12-arch1-1, our baseline is 4.15

Welcome to Arch Linux!

Hostname was already set to <09b6cf300ea9>.
Initializing machine ID from container UUID.
Bind-mounting /run/machine-id on /etc/machine-id (MS_BIND "")...
Failed to mount /run/machine-id (type n/a) on /etc/machine-id (MS_BIND ""): Operation not permitted
Failed to add address 127.0.0.1 to loopback interface: Operation not permitted
Failed to add address ::1 to loopback interface: Operation not permitted
Failed to bring loopback interface up: Operation not permitted
Setting '/proc/sys/net/unix/max_dgram_qlen' to '512'
Failed to bump AF_UNIX datagram queue length, ignoring: Permission denied
Setting '/proc/sys/fs/file-max' to '9223372036854775807'
Setting '/proc/sys/fs/nr_open' to '2147483640'
Failed to bump fs.nr_open, ignoring: Permission denied
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Unified cgroup hierarchy is located at /sys/fs/cgroup.
bpf-firewall: Can't load kernel CGROUP SKB BPF program, BPF firewalling is not supported: Operation not permitted
Can't load kernel CGROUP DEVICE BPF program, BPF device control is not supported: Operation not permitted
bpf-socket-bind: BPF program type cgroup_sock_addr is not supported
restrict-interfaces: BPF program type cgroup_skb is not supported
Controller 'cpu' supported: yes
Controller 'cpuacct' supported: no
Controller 'cpuset' supported: no
Controller 'io' supported: no
Controller 'blkio' supported: no
Controller 'memory' supported: yes
Controller 'devices' supported: no
Controller 'pids' supported: yes
Controller 'bpf-firewall' supported: no
Controller 'bpf-devices' supported: no
Controller 'bpf-foreign' supported: yes
Controller 'bpf-socket-bind' supported: no
Controller 'bpf-restrict-network-interfaces' supported: no
Set up TFD_TIMER_CANCEL_ON_SET timerfd.
Failed to stat /etc/localtime, ignoring: No such file or directory
/etc/localtime doesn't exist yet, watching /etc instead.
bpf-lsm: BPF LSM hook not enabled in the kernel, BPF LSM not supported
Enabling (yes) showing of status (commandline).
Serializing system-environment-generators to memfd.
Successfully forked off '(sd-executor)' as PID 2.
Skipping PR_SET_MM, as we don't have privileges.
Serializing 10-arch to memfd.
Successfully forked off '(direxec)' as PID 3.
/usr/lib/systemd/system-environment-generators/10-arch succeeded.
(sd-executor) succeeded.
Failed to fork: Operation not permitted
[!!!!!!] Failed to start up manager.
Exiting PID 1...
```
```

### PR DESCRIPTION
**Pull request by yuwata**
When running in a container, like docker or so, creating new mount namespace may be disabled.

Fixes #26474.
Fixes RHBZ#2165004 (https://bugzilla.redhat.com/show_bug.cgi?id=2165004).

### CODE REVIEW

File: src/core/manager.c [hunk 1]
```diff
@@ -3834,6 +3834,14 @@ static int manager_run_generators(Manager *m) {
         if (r == 0) {
                 r = manager_execute_generators(m, paths, /* remount_ro= */ true);
                 _exit(r >= 0 ? EXIT_SUCCESS : EXIT_FAILURE);
+
+        } else if (r == -EPERM) {
```
Comment (poettering) [inline src/core/manager.c]: maybe use ERRNO_IS_PRIVILEGE()?

Comment (poettering) [reply src/core/manager.c]: hmm, we use FORK_LOG in the safe_fork() invocation, so there will already be a loud message about lack of privs being printed here if we lacked the privs.

Maybe move this into safe_fork() instead, i.e. add a new flag `FORK_MOUNTNS_GRACEFUL` which will implicitly cancel the effect of `FORK_NEW_MOUNTNS` and `FORK_PRIVATE_TMP` flag if it can't acquire a new namespace in the child. It would still fork off the child, and it would print a debug message only in case it does the fallback thing.

Comment (keszybz) [reply src/core/manager.c]: As I wrote on an earlier version of the patch, I think the message should be at debug level. We support running without namespaces, so we shouldn't warn too loudly.

**Comment by yuwata** [comment]
@poettering and @keszybz Thank you for the comments.
- ERRNO_IS_PRIVILEGE() is now used,
- log message is downgraded,

PTAL.

> Maybe move this into safe_fork() instead, i.e. add a new flag `FORK_MOUNTNS_GRACEFUL` which will implicitly cancel the effect of `FORK_NEW_MOUNTNS` and `FORK_PRIVATE_TMP` flag if it can't acquire a new namespace in the child. It would still fork off the child, and it would print a debug message only in case it does the fallback thing.

It may be useful, but unfortunately cannot be applied here, as we need to change the `remount_ro` flag in `manager_execute_generators()`.

**Comment by keszybz** [comment]
jammy-ppc64el: TEST-50-DISSECT:                    FAIL     (1210 s). Looks like the usual timeout, not related to the patch at hand.

LGTM.

@yuwata, thanks!
