### PR TITLE
core: apply WorkingDirectory after enforce_user

### LINKED ISSUE #10568: exec: chdir to WorkingDirectory fails on NFS with root squash
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Debian Unstable

**Expected behaviour you didn't see**
 > A template service that has `User=%i` and `WorkingDirectory=/home/%i` with the working directory being on an NFS share with root squash enabled and Permissions `700` starts properly

**Unexpected behaviour you saw**
 > A template service that has `User=%i` and `WorkingDirectory=/home/%i` with the working directory being on an NFS share with root squash enabled doesn't start unless the permissions on the home directory are `701`

**Steps to reproduce the problem**

This service reproduces the problem
```
# /etc/systemd/system/chdirdebug@.service
[Unit]
Description=Test service to debug chdir

[Service]
Type=oneshot
User=%i
ExecStart=/bin/bash -c "echo $(pwd)"
WorkingDirectory=/home/%i
```

For a user with permissions 755 it runs perfectly and for a user with home permissions 700
```
-- Logs begin at Sat 2018-03-24 09:34:45 CET, end at Mon 2018-10-29 18:36:42 CET. --
Oct 29 18:36:42 host systemd[1]: Starting Test service to debug chdir...
Oct 29 18:36:42 host systemd[96667]: chdirdebug@user.service: Changing to the requested working directory failed: Permission denied
Oct 29 18:36:42 host systemd[96667]: chdirdebug@user.service: Failed at step CHDIR spawning /bin/bash: Permission denied
Oct 29 18:36:42 host systemd[1]: chdirdebug@user.service: Main process exited, code=exited, status=200/CHDIR
Oct 29 18:36:42 host systemd[1]: chdirdebug@user.service: Failed with result 'exit-code'.
Oct 29 18:36:42 host systemd[1]: Failed to start Test service to debug chdir.
```

After helpful discussion with @grawity in #systemd the assumption is, that the move of `apply_working_directory` in 50b3dfb9d64872025450aa63765206720be471d6 to the earliest possible position is too early, since in the context of network filesystems root might not be allowed to change the directory.

If I were to hazard a guess moving `apply_working_directory` from its current [position](https://github.com/systemd/systemd/blob/master/src/core/execute.c#L3200) to somewhere after [this block](https://github.com/systemd/systemd/blob/master/src/core/execute.c#L3348) that calls `ensure_user`, might be a solution.

And yes, the user does have permission to read their own home. ;) 

Thanks a lot in advance!

### PR DESCRIPTION
**Pull request by behrmann**
If WorkingDirectory is on NFS, root might only have the privileges of
nobody and the chdir to the WorkingDirectory might fail, even if the
user running the service would have the proper privileges to chdir to
that directory.

Fixes #10568

### CODE REVIEW

File: src/core/execute.c [hunk 1]
```diff
@@ -3375,6 +3370,12 @@ static int exec_child(
                 }
         }
 
+        /* Apply working directory here, because the working directory might be on NFS and only the user running
+         * this service might have the correct privilege to change to the working directory */
+        r = apply_working_directory(context, params, home, needs_mount_namespace, exit_status);
+        if (r < 0)
+                return log_unit_error_errno(unit, r, "Changing to the requested working directory failed: %m");
```
Comment (poettering) [inline src/core/execute.c:3377]: this really sounds like a game of whack-a-mole to me... So far our policy was to do security restrictions last, under the assumption that we can only lose privs, not gain them. The NFS messiness corrupts that logic though, suddenly doing security first enables us to do other stuff we weren't allowed to do before. Now, this really smells to me as if sooner or later different stuff people want to do would require different orderings, and that ultimately in a way that cannot be solved properly due to cyclic ordering reqs...

But anyway, let's see where this goes. The above is just  a bad feeling I have about this, maybe in reality it's not going to be that bad...

Comment (grawity) [reply src/core/execute.c:3377]: For what it's worth, the requirement is not NFS-specific – it can apply equally well to any network filesystem, as local root _isn't_ automatically remote root in most of them. (CIFS? Accounts, kerberos tickets. AFS? Tokens. FUSE? allow_root/allow_other is off by default.)

**Comment by behrmann** [comment]
On Wed, Oct 31, 2018 at 04:07:18AM -0700, Lennart Poettering wrote:
> this really sounds like a game of whack-a-mole to me... So far our policy was to do security restrictions last, under the assumption that we can only lose privs, not gain them. The NFS messiness corrupts that logic though, suddenly doing security first enables us to do other stuff we weren't allowed to do before. Now, this really smells to me as if sooner or later different stuff people want to do would require different orderings, and that ultimately in a way that cannot be solved properly due to cyclic ordering reqs...
> 

> this really sounds like a game of whack-a-mole to me... So far our policy was
> to do security restrictions last, under the assumption that we can only lose
> privs, not gain them. The NFS messiness corrupts that logic though, suddenly
> doing security first enables us to do other stuff we weren't allowed to do
> before. Now, this really smells to me as if sooner or later different stuff
> people want to do would require different orderings, and that ultimately in a
> way that cannot be solved properly due to cyclic ordering reqs...

Terribly sorry for this mess, but maybe duplicating this logic would in this case be worthwhile?

One could test, whether the working directory is on a local fs and change the directory in the same place as before and if not, then do after changing the UID. After @grawity's comment I'm a bit queasy though, whether anything later then this solution could be needed.
