### PR TITLE
json: decrease DEPTH_MAX to 4k

### LINKED ISSUE #10738: test: test-json built by clang fails
```
264/623 test-json                               FAIL     0.21 s (killed by signal 11 SIGSEGV)

--- command ---
PATH='/var/build-clang:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/watanabe/bin:/usr/local/texlive/2016/bin/x86_64-linux' SYSTEMD_KBD_MODEL_MAP='/home/watanabe/git/systemd/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/home/watanabe/git/systemd/src/locale/language-fallback-map' /var/build-clang/test-json
--- Listing only the last 100 lines from a long log. ---


{
"foo" : "bar", 
"qüüx" : [ 1, 2, 3,
4,
5 ],
"miep" : { "hallo" : 1 },

"zzzzzz" 
:
[ true, 
false, 7.5, {} ]
}
--- original end ---
--- non-pretty begin ---
{"foo":"bar","qüüx":[1,2,3,4,5],"miep":{"hallo":1},"zzzzzz":[true,false,7.500000000000000000000e+00,{}]}
--- non-pretty end ---
--- pretty begin ---
[waldo: 3: 1] {
[waldo: 4: 1] 	"foo" : "bar",
[waldo: 5: 1] 	"qüüx" : [
[waldo: 5:12] 		1,
[waldo: 5:15] 		2,
[waldo: 5:18] 		3,
[waldo: 6: 1] 		4,
[waldo: 7: 1] 		5
              	],
[waldo: 8: 1] 	"miep" : {
[waldo: 8:12] 		"hallo" : 1
              	},
[waldo:10: 1] 	"zzzzzz" : [
[waldo:12: 3] 		true,
[waldo:13: 1] 		false,
[waldo:13: 8] 		7.500000000000000000000e+00,
[waldo:13:13] 		{}
              	]
              }
--- pretty end ---
[{"key":[{"key":[{"key":[{"key":[{"key":[{"key":[{"key":[{"key":[{"key":[{"key":[{"key":[{"key":
(snip)
--- stderr ---
Failed to read $container of PID 1, ignoring: Permission denied
Found container virtualization none.
formatted normally: {"k":"v","foo":[1,2,3],"bar":{"zap":null}}
formatted prettily:
{
	"k" : "v",
	"foo" : [
		1,
		2,
		3
	],
	"bar" : {
		"zap" : null
	}
}
formatted normally: {"mutant":[1,null,"1",{"1":[1,"1"]}],"thisisaverylongproperty":1.269999999999999999983e+00}
formatted prettily:
{
	"mutant" : [
		1,
		null,
		"1",
		{
			"1" : [
				1,
				"1"
			]
		}
	],
	"thisisaverylongproperty" : 1.269999999999999999983e+00
}
formatted normally: {"foo":"􏿿\"򏿿FFF\"􏿿\"򏿿􏿿F􏿿􏿿􏿿􏿿\"򏿿FF\"􏿿\"򏿿􏿿"}
formatted prettily:
{
	"foo" : "􏿿\"򏿿FFF\"􏿿\"򏿿􏿿F􏿿􏿿􏿿􏿿\"򏿿FF\"􏿿\"򏿿􏿿"
}
formatted normally: [0,0,0.000000000000000000000e+00,0.000000000000000000000e+00,0.000000000000000000000e+00,0.000000000000000000000e+00,0.000000000000000000000e+00,0.000000000000000000000e+00,0.000000000000000000000e+00,0.000000000000000000000e+00,0.000000000000000000000e+00,0.000000000000000000000e+00,0.000000000000000000000e+00]
formatted prettily:
[
	0,
	0,
	0.000000000000000000000e+00,
	0.000000000000000000000e+00,
	0.000000000000000000000e+00,
	0.000000000000000000000e+00,
	0.000000000000000000000e+00,
	0.000000000000000000000e+00,
	0.000000000000000000000e+00,
	0.000000000000000000000e+00,
	0.000000000000000000000e+00,
	0.000000000000000000000e+00,
	0.000000000000000000000e+00
]
GOT: [{"x":true,"y":{"this":null}},null,null,null,null,77,["foobar","zzz"],["one","two","three","four"]]
GOT: 3.141592653589793238513e+00
GOT: 3.141592653589793238513e+00
max depth at 16384
-------
```

### PR DESCRIPTION
**Pull request by yuwata**
This makes DEPTH_MAX lower value, as test-json fails with stack overflow.

Note that the test can pass with 8k, but for safety, here set to 4k.

Fixes #10738.

### CODE REVIEW

File: src/basic/json.c [hunk 1]
```diff
@@ -24,10 +24,10 @@
 #include "terminal-util.h"
 #include "utf8.h"
 
-/* Refuse putting together variants with a larger depth than 16K by default (as a protection against overflowing stacks
+/* Refuse putting together variants with a larger depth than 4K by default (as a protection against overflowing stacks
  * if code processes JSON objects recursively. Note that we store the depth in an uint16_t, hence make sure this
  * remains under 2^16. */
```
Comment (poettering) [inline src/basic/json.c]: could you add a comment here saying that 16K was discovered to be too high on llvm/x86-64?

Comment (yuwata) [reply src/basic/json.c]: OK. Done.

**Comment by poettering** [comment]
excellent! thanks!
