### PR TITLE
udev: several inotify watch fixups

### LINKED ISSUE #18525: udev: watch handle may be deleted by other devices
**systemd version the issue has been seen with**
 > 247

**Expected behaviour you didn't see**
 > Each disk or lvm device has a watch handle symlink in /run/udev/watch

**Unexpected behaviour you saw**
 > Some devices have no watch handle

**Steps to reproduce the problem**
 > The follow scripts can reproduce the problem
```
watch_org=$(ls -l /run/udev/watch | wc -l)

while true
do
        systemctl restart systemd-udevd
        sleep 3

        udevadm trigger
        udevadm settle
        watch_current=$(ls -l /run/udev/watch | wc -l)
        if [ $watch_org != $watch_current ]; then
                break
        fi
done
```

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes #18525.

Replaces #18524 and #18526.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @gaoyi1988

File: src/udev/udev-watch.c [hunk 1]
```diff
@@ -90,12 +91,22 @@ int udev_watch_begin(int inotify_fd, sd_device *dev) {
...
                 return log_device_error_errno(dev, r, "Failed to create parent directory of '%s': %m", filename);
-        (void) unlink(filename);
 
         r = device_get_id_filename(dev, &id);
         if (r < 0)
                 return log_device_error_errno(dev, r, "Failed to get device id-filename: %m");
 
+        r = readlink_malloc(filename, &old_id);
+        if (r >= 0) {
+                if (streq(id, old_id))
```
Comment (bluca) [inline src/udev/udev-watch.c]: if I understand correctly these are paths, so path_equal() ?

Comment (yuwata) [reply src/udev/udev-watch.c]: `path_equal()` handles slashes gracefully. But in this case, the device id must be unique, hence should be handled strictly. Moreover, in most cases, the ids saved in symlinks do not look like paths:
```
$ ls -l /run/udev/watch
total 0
lrwxrwxrwx 1 root root 4 Mar  5 08:50 1 -> b8:0
lrwxrwxrwx 1 root root 6 Mar  5 08:49 2 -> b259:2
lrwxrwxrwx 1 root root 6 Mar  5 08:49 3 -> b259:1
lrwxrwxrwx 1 root root 6 Mar  5 08:49 4 -> b259:0
lrwxrwxrwx 1 root root 4 Mar  5 18:41 666 -> b7:0
lrwxrwxrwx 1 root root 4 Mar  5 10:43 70 -> b7:1
```

Comment (bluca) [reply src/udev/udev-watch.c]: I see, makes sense

**Review by bluca — APPROVED** [review]
Changes themselves look good to me, but not that familiar with this area, so waiting for more eyes, and maybe a test run from the reporter

**Comment by yuwata** [comment]
Ah, this is completely broken. Will rework...

File: src/udev/udev-watch.c [hunk 2]
```diff
@@ -90,12 +91,22 @@ int udev_watch_begin(int inotify_fd, sd_device *dev) {
...
+                        return 0;
+
+                log_device_warning(dev, "'%s' is a symbolic link to a differnt device '%s', ignoring.", filename, old_id);
```
Comment (keszybz) [inline src/udev/udev-watch.c]: different

**Comment by yuwata** [comment]
bionic-i386 fails in portabled test. I hope it is not related. PTAL.

**Comment by bluca** [comment]
It doesn't seem unrelated:

```
Mar 08 00:02:30 systemd-testsuite systemd-portabled[406]: Failed to wait for device to be initialized: Connection timed out
Mar 08 00:02:35 systemd-testsuite systemd-portabled[406]: Failed to wait for device to be initialized: Connection timed out
Mar 08 00:02:35 systemd-testsuite systemd-udevd[250]: loop0: Failed to update device symlinks: Too many levels of symbolic links
Mar 08 00:02:36 systemd-testsuite systemd-udevd[247]: loop8: Failed to update device symlinks: Too many levels of symbolic links
```

(as explained in the readme you can download the tarball with the test artifacts, including the journal file, from the linked URL - eg for this case ```wget https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/i386/s/systemd-upstream/20210308_002553_0c359@/artifacts.tar.gz```)

**Comment by gaoyi1988** [comment]
@yuwata 
I just backport commit https://github.com/systemd/systemd/pull/18904/commits/70e2dac3362dc88400d63ab6ed403558de41223f and https://github.com/systemd/systemd/pull/18904/commits/647a6321bf85a44611babbeb69879f7fcd365233. And run the test. 

There are some problems:
1. Thers is one device has no symlink path_wd and path_id. so far, it's only happened once.
2. Thers is one device has no symlink path_id. 
```
[root@localhost watch]# ll | grep 49
lrwxrwxrwx. 1 root root 5 Mar  8 17:56 38 -> b8:49
lrwxrwxrwx. 1 root root 5 Mar  8 17:56 49 -> b8:36
lrwxrwxrwx. 1 root root 2 Mar  8 17:56 b8:49 -> 38
```

Are there any other commits I have to backport?

**Comment by yuwata** [comment]
Updated. Though, I cannot find the root cause of the previous portable test issue...

@gaoyi1988 Thank you for testing this PR. Could you test again?

**Comment by bluca** [comment]
> Updated. Though, I cannot find the root cause of the previous portable test issue...

It will be from the dissect-image logic, ie waiting for the device to appear?

**Comment by gaoyi1988** [comment]
@yuwata 
I have backport https://github.com/systemd/systemd/pull/18904/commits/9c86b95281edd2f3ae05affd6e15797369e2a9b1, https://github.com/systemd/systemd/pull/18904/commits/fb153661705a7bfaf0b6d20ddd0a541e33241ae8 and https://github.com/systemd/systemd/pull/18904/commits/e087790811e0c6a9a8861f188e70cc20b34541f0. But it seems that there are possibilities that some devices have no symlink path_id.
```
[root@localhost watch]# ll | grep 47
lrwxrwxrwx. 1 root root 5 Mar  9 20:58 47 -> b8:65
```

**Comment by gaoyi1988** [comment]
@yuwata 
Accordding to the logs, no path_id is happened because of change event and inotify event with IN_IGNORED are both happened, and symlink path_id is deleted by inotify event which created by change event.
```
Mar 10 11:32:00 localhost.localdomain systemd-udevd[79335]: dm-2: Processing device (SEQNUM=398878, ACTION=change)
Mar 10 11:32:00 localhost.localdomain systemd-udevd[79335]: dm-2: Removing watch
Mar 10 11:32:00 localhost.localdomain **systemd-udevd[79288]: dm-2: Inotify event: 8000 for /dev/dm-2**
Mar 10 11:32:00 localhost.localdomain systemd-udevd[79335]: dm-2: Delete watch handle 12, b253:2
...
Mar 10 11:32:00 localhost.localdomain systemd-udevd[79335]: dm-2: Adding watch on '/dev/dm-2'
Mar 10 11:32:00 localhost.localdomain systemd-udevd[79335]: dm-2: Delete watch handle -2, b253:2
Mar 10 11:32:00 localhost.localdomain systemd-udevd[79335]: **dm-2: Create watch handle /run/udev/watch/65 /run/udev/watch/b253:2**
Mar 10 11:32:00 localhost.localdomain systemd-udevd[79335]: dm-2: sd-device: Created db file '/run/udev/data/b253:2' for '/devices/virtual/block/dm-2'
Mar 10 11:32:00 localhost.localdomain systemd-udevd[79335]: dm-2: Device (SEQNUM=398878, ACTION=change) processed
Mar 10 11:32:00 localhost.localdomain systemd-udevd[79335]: dm-2: sd-device-monitor: Passed 889 byte to netlink monitor
Mar 10 11:32:00 localhost.localdomain **systemd-udevd[79288]: dm-2: Delete watch handle -2, b253:2**
```

**Comment by yuwata** [comment]
@gaoyi1988 Updated. Could you test again?

**Comment by yuwata** [comment]
> dm-2: Delete watch handle -2, b253:2

Where does this come from?

**Comment by gaoyi1988** [comment]
> > dm-2: Delete watch handle -2, b253:2
> 
> Where does this come from?

"Create watch handle..." and "Delete watch handle..." is added by me for debug. 
In the end of device_remove_watch_handle, add:
```
log_device_debug(device, "Delete watch handle %d, %s", wd, id); 
```
In device_set_watch_handle before call symlink, add:
```
log_device_debug(device, "Create watch handle %s %s", path_wd, path_id);
```
In that logs, PID 79288 is main process and handles inotify event, PID 79335 handles change event.

**Comment by gaoyi1988** [comment]
@yuwata 
I think the real problem is in function device_remove_watch_handle. If we delete path_wd, we must delete path_id at the same time. But if we can't find path_wd, path_id may be updated by other event, so we can't delete.

I think your commit cf457241e3bba83f5804f0f38d415587c593168c didn't fix this problem.

**Comment by yuwata** [comment]
Updated.

@gaoyi1988 
> In that logs, PID 79288 is main process and handles inotify event, PID 79335 handles change event.

Yeah, calling `udev_watch_end()` from the main process may cause race condition. I dropped it. Now, `udev_watch_begin/end()` are only called from udev worker processs. Hence, there should be no race anymore. Please test again. Thank you for your help!

**Comment by yuwata** [comment]
@gaoyi1988 BTW, how do you test this PR? I included your original reproducer reported in #18525 in our test. If you find any issues in the current PR, then please provide the reproducer.

**Comment by yuwata** [comment]
Wow! Finally, all CIs are green!

**Comment by gaoyi1988** [comment]
@yuwata 
Delete udev_watch_end in on_inotify can fix the problem. And my testcase is in https://github.com/systemd/systemd/issues/18525

**Comment by yuwata** [comment]
Thank you!

**Comment by gaoyi1988** [comment]
@yuwata 
Are there still any problems? Why this is not merged?

**Comment by yuwata** [comment]
Because no one has reviewed this yet, and we are slightly busy for v248 release process. I hope this will be merged soon after v248 is released.

File: src/udev/udevd.c [hunk 3]
```diff
@@ -1713,12 +1721,11 @@ static int main_loop(Manager *manager) {
         if (r < 0)
                 return log_error_errno(r, "Failed to enable SO_PASSCRED: %m");
 
-        r = udev_watch_init();
-        if (r < 0)
-                return log_error_errno(r, "Failed to create inotify descriptor: %m");
-        manager->fd_inotify = r;
+        manager->inotify_fd = inotify_init1(IN_CLOEXEC);
+        if (manager->inotify_fd < 0)
+                log_error_errno(errno, "Failed to create inotify descriptor: %m");
```
Comment (poettering) [inline src/udev/udevd.c]: not fatal anymore?

File: src/udev/udev-event.c [hunk 4]
```diff
@@ -993,10 +995,8 @@ int udev_event_execute_rules(
         if (r < 0)
                 return log_device_error_errno(dev, r, "Failed to get ACTION: %m");
 
-        if (action == SD_DEVICE_REMOVE) {
-                event_execute_rules_on_remove(event, inotify_fd, timeout_usec, timeout_signal, properties_list, rules);
-                return 0;
```
Comment (poettering) [inline src/udev/udev-event.c:999]: hmm, this has quite some potential of surfacing issues that noone noticed before because we ignore the results of remove rules, no?

File: src/libsystemd/sd-device/sd-device.c [hunk 5]
```diff
@@ -654,15 +654,14 @@ _public_ int sd_device_new_from_device_id(sd_device **ret, const char *id) {
         }
 
         case '+': {
-                char subsys[PATH_MAX];
-                char *sysname;
+                char subsys[NAME_MAX];
```
Comment (poettering) [inline src/libsystemd/sd-device/sd-device.c]: NAME_MAX does not include space for trailing NUL, hence should be NAME_MAX+1 here (PATH_MAX *does* include it)

File: src/libsystemd/sd-device/sd-device.c [hunk 6]
```diff
@@ -775,60 +792,45 @@ static int device_set_drivers_subsystem(sd_device *device, const char *_subsyste
...
+                        return r;
+
                 /* read 'subsystem' link */
                 path = strjoina(syspath, "/subsystem");
                 r = readlink_value(path, &subsystem);
+                if (r < 0 && r != -ENOENT)
+                        return log_device_debug_errno(device, r,
+                                                      "sd-device: Failed to read subsystem for %s: %m",
+                                                      device->devpath);
                 if (r >= 0)
```
Comment (poettering) [inline src/libsystemd/sd-device/sd-device.c]: maybe change this to `if (subsystem)` to make this more readable? doesn't matter though

File: src/libsystemd/sd-device/device-private.h [hunk 7]
```diff
@@ -12,18 +12,22 @@
...
-int device_get_watch_handle(sd_device *device, int *handle);
+int device_get_watch_handle(sd_device *device);
 int device_get_devnode_mode(sd_device *device, mode_t *mode);
 int device_get_devnode_uid(sd_device *device, uid_t *uid);
 int device_get_devnode_gid(sd_device *device, gid_t *gid);
 
 void device_seal(sd_device *device);
 void device_set_is_initialized(sd_device *device);
-void device_set_watch_handle(sd_device *device, int fd);
+int device_set_watch_handle(sd_device *device, int handle);
```
Comment (poettering) [inline src/libsystemd/sd-device/device-private.h]: we usually call these "wd"

File: src/libsystemd/sd-device/sd-device.c [hunk 8]
```diff
@@ -1239,10 +1239,7 @@ static int handle_db_line(sd_device *device, char key, const char *value) {
 
                 break;
         case 'W':
-                r = safe_atoi(value, &device->watch_handle);
-                if (r < 0)
-                        return r;
-
+                /* Deprecated. */
```
Comment (poettering) [inline src/libsystemd/sd-device/sd-device.c]: what happens during upgrade from old udev?

File: src/udev/udevd.c [hunk 9]
```diff
@@ -1293,17 +1293,18 @@ static int on_inotify(sd_event_source *s, int fd, uint32_t revents, void *userda
...
                         continue;
+                }
 
                 if (sd_device_get_devname(dev, &devnode) < 0)
                         continue;
 
                 log_device_debug(dev, "Inotify event: %x for %s", e->mask, devnode);
                 if (e->mask & IN_CLOSE_WRITE)
-                        synthesize_change(dev);
-                else if (e->mask & IN_IGNORED)
```
Comment (poettering) [inline src/udev/udevd.c:1311]: hmm, why is the IN_IGNORED handling dropped?

**Review by poettering — COMMENTED** [review]
looks good, a few comments

File: src/udev/udevd.c (hunk 9 above)
Comment (gaoyi1988) [reply src/udev/udevd.c:1311]: @yuwata 
This is also my question. 

Actually, before verified this solution, I have verified that delete path_id and path_wd both, or delete anything can solve the problem. And I think this is the real problem. As follow:
```
static void device_remove_watch_handle(sd_device *device) {
        const char *id;
        int wd;

        assert(device);

        /* First, remove the symlink from handle to device id. */
        wd = device_get_watch_handle(device);
        if (wd >= 0) {
                char path_wd[STRLEN("/run/udev/watch/") + DECIMAL_STR_MAX(int)];

                xsprintf(path_wd, "/run/udev/watch/%d", wd);
                if (access(path_wd, F_OK) < 0)
                        return;
                
                (void) unlink(path_wd);
        } else 
                return;

        /* Next, remove the symlink from device id to handle. */
        if (device_get_id_filename(device, &id) >= 0) {
                const char *path_id;

                path_id = strjoina("/run/udev/watch/", id);
                (void) unlink(path_id);
        }

        device->watch_handle = -1;
}
```

File: src/udev/udev-event.c (hunk 4 above)
Comment (yuwata) [reply src/udev/udev-event.c:999]: When, some remove rules are failed, then this commit changes only two things: warn the failure, and skip `udev_event_execute_run()`. Skipping `udev_event_execute_run()` on some failure should be safer, as the execution list may be different from expected.

File: src/libsystemd/sd-device/sd-device.c (hunk 8 above)
Comment (yuwata) [reply src/libsystemd/sd-device/sd-device.c]: Watch handle is always read from /run/udev/watch now. New udevd simply ignores the handle saved in udev databse.

File: src/udev/udevd.c (hunk 9 above)
Comment (yuwata) [reply src/udev/udevd.c:1311]: When `IN_IGNORED` is triggered, the corresponding 'remove' uevent for the device will be triggered, and during the process of the uevent, `udev_watch_end()` is called. So, it is not necessary to handle the flag here. Moreover, when both `udev_watch_end()` is called by both the main and worker process, then `device_remove_watch_handle()` in `udev_watch_end()` may cause some race. With this commit, `udev_watch_begin()` and `udev_watch_end()` are only called by workers. So, there should be no race.

I added short comment about that in the code.

**Comment by yuwata** [comment]
@poettering Thank you for your review. Updated. PTAL.

File: src/libsystemd/sd-device/sd-device.c [hunk 10]
```diff
@@ -751,15 +751,32 @@ int device_set_subsystem(sd_device *device, const char *_subsystem) {
...
+                return -EINVAL;
+
+        for (p = drivers - 1; p >= syspath; p--)
+                if (*p == '/')
+                        break;
+
+        if (p <= syspath)
+                return -EINVAL;
+        p++;
+        if (p >= drivers)
```
Comment (poettering) [inline src/libsystemd/sd-device/sd-device.c:777]: maybe add comment here: `/* refuse duplicate slashes */` or so? because that's what this is supposed to do, no?

File: src/libsystemd/sd-device/device-private.c [hunk 11]
```diff
@@ -568,28 +569,132 @@ int device_get_devlink_priority(sd_device *device, int *priority) {
...
+                xsprintf(path_wd, "/run/udev/watch/%d", wd);
+                (void) unlink(path_wd);
+        }
+
+        /* Next, remove the symlink from device id to handle. */
+        if (device_get_device_id(device, &id) >= 0) {
+                const char *path_id;
+
+                path_id = strjoina("/run/udev/watch/", id);
+                (void) unlink(path_id);
```
Comment (poettering) [inline src/libsystemd/sd-device/device-private.c]: doesn't matter, but maybe debug log if this fails with errors != ENOENT? 

doens't matter at all though

File: src/libsystemd/sd-device/device-private.c [hunk 12]
```diff
@@ -568,28 +569,132 @@ int device_get_devlink_priority(sd_device *device, int *priority) {
...
-        assert(device);
+int device_new_from_watch_handle_at(sd_device **ret, int dirfd, int wd) {
+        char path_wd[STRLEN("/run/udev/watch/") + DECIMAL_STR_MAX(int)];
+        _cleanup_free_ char *id = NULL;
+        int r;
+
+        assert(ret);
+
+        if (wd < 0)
+                return -EINVAL;
```
Comment (poettering) [inline src/libsystemd/sd-device/device-private.c]: EBADF? (i mean, that's the error you return further up when the wd db on disk is borked)

**Review by poettering — APPROVED** [review]
looks all great to me. only found nitpicks

**Comment by yuwata** [comment]
@poettering Thank you for review. All the above comments are addressed. Upgrading the green label.
