### PR TITLE
efi: Cache contents of EFI variable SystemdOptions

### LINKED ISSUE #16097: Running systemctl reads from EFI variables when launched by a monitoring agent
**systemd version the issue has been seen with**
> v245-1586-gb11e98037c

**Used distribution**
 > Fedora 32

**Expected behaviour you didn't see**
 > systemctl shouldn't read EFI variables, at all.

**Unexpected behaviour you saw**
 > systemctl (and other tools, systemd-analyze, etc.) read EFI variables if they're called by a daemon, such as Chef agent, which runs them without a controlling tty.

**Steps to reproduce the problem**

This works fine:

```
$ strace -e openat ./build/systemctl 2>&1 | grep /sys/firmware
(empty)
```

But this doesn't:

```
$ strace -e openat setsid ./build/systemctl 2>&1 | grep /sys/firmware
openat(AT_FDCWD, "/sys/firmware/efi/efivars/SecureBoot-XXX-YYY-ZZZ", O_RDONLY|O_NOCTTY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/sys/firmware/efi/efivars/SystemdOptions-XXX-YYY-ZZZ", O_RDONLY|O_NOCTTY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

Ooops!

Looking at the source, I can see that `log_parse_environment()` tries to detect whether it's being run from a daemon by [checking whether there's a controlling tty](https://github.com/systemd/systemd/blob/v245/src/basic/log.c#L1112-L1116) when deciding to parse `/proc/cmdline`.

And recently commit https://github.com/systemd/systemd/commit/c7d26acce6dcb0e72be6160873fac758e9b7c440 (which was first released in v245) will read EFI variables when parsing `/proc/cmdline`, so this code got a lot more expensive, enough to be noticeable.

cc @anitazha @arianvp

### PR DESCRIPTION
**Pull request by filbranden**
Cache it early in startup of the system manager, right after `/run/systemd` is created, so that further access to it can be done without accessing the EFI filesystem at all.

Fixes #16097.

cc @poettering @keszybz @arianvp 

NOTE: I didn't have time to fully test this yet, but opening a PR already to check whether this approach is what you also had in mind and to get some initial code reviews before I come back to it tomorrow. (Labeling it "dont-merge" for this reason.)

### CODE REVIEW

File: src/basic/efivars.c [hunk 1]
```diff
@@ -365,10 +352,42 @@ int systemd_efi_options_variable(char **line) {
...
                 return -ENODATA;
+        if (r < 0)
+                return r;
 
+        r = mkdir_safe_label("/run/systemd/efivars", 0700, 0, 0, MKDIR_WARN_MODE);
+        if (r < 0)
+                return r;
+
+        return write_string_file("/run/systemd/efivars/SystemdOptions", line,
+                        WRITE_STRING_FILE_ATOMIC|WRITE_STRING_FILE_CREATE|WRITE_STRING_FILE_MODE_0600|WRITE_STRING_FILE_SYNC);
```
Comment (poettering) [inline src/basic/efivars.c]: i would suggest the file is made public, i.e. no 0600 mode. It's like /proc/cmdline, and that too is readable by everyone.

File: src/basic/efivars.c [hunk 2]
```diff
@@ -365,10 +352,42 @@ int systemd_efi_options_variable(char **line) {
...
         }
 
-        r = efi_get_variable_string(EFI_VENDOR_SYSTEMD, "SystemdOptions", line);
+        r = efi_get_variable_string(EFI_VENDOR_SYSTEMD, "SystemdOptions", &line);
         if (r == -ENOENT)
                 return -ENODATA;
+        if (r < 0)
+                return r;
 
+        r = mkdir_safe_label("/run/systemd/efivars", 0700, 0, 0, MKDIR_WARN_MODE);
```
Comment (poettering) [inline src/basic/efivars.c]: I'd just use 0755 here, if we add more stuff there and it shall be inaccessible it should be the individual files that protect access I think

File: src/basic/efivars.c [hunk 3]
```diff
@@ -365,10 +352,42 @@ int systemd_efi_options_variable(char **line) {
...
+        if (r < 0)
+                return r;
+
+        return write_string_file("/run/systemd/efivars/SystemdOptions", line,
```
Comment (poettering) [inline src/basic/efivars.c]: bikeshedding: if we end up caching other variables here the name here should probably contain the namespace uuid, i.e. incorporate EFI_VENDOR_SYSTEMD like /sys/firmware/efivars  would list it

File: src/core/main.c [hunk 4]
```diff
@@ -2630,6 +2631,9 @@ int main(int argc, char *argv[]) {
 
                 /* The efivarfs is now mounted, let's read the random seed off it */
                 (void) efi_take_random_seed();
+
+                /* Cache command-line options passed from EFI variables */
+                (void) cache_efi_options_variable();
```
Comment (poettering) [inline src/core/main.c]: should be done only under the `!skip_setup` condition, otherwise we'll redo this needlessly on each daemon reexec.

(Note that the `efi_take_random_seed()` invocation got that wrong, it should be guarded the same way. I fix that in #16142)

File: src/basic/efivars.c (hunk 1 above)
Comment (filbranden) [reply src/basic/efivars.c]: Done!

File: src/basic/efivars.c (hunk 2 above)
Comment (filbranden) [reply src/basic/efivars.c]: Done (actually asking `write_string_file()` to create the directory now.)

File: src/basic/efivars.c (hunk 3 above)
Comment (filbranden) [reply src/basic/efivars.c]: Done.

File: src/core/main.c (hunk 4 above)
Comment (filbranden) [reply src/core/main.c]: Done. (I guess.)

**Comment by filbranden** [comment]
What's the best way to test this?

I can use `mkosi qemu` to create an image with this version and boot it on QEMU using UEFI, but how do I set the SystemdOptions EFI variable there? (I'm still looking into how to do that, but I thought it would make sense to ask that here too, in case someone knows it off the top of their head...)

**Comment by filbranden** [comment]
I just tested this on QEMU using `efivar` and it seems to work as expected.

Pushed a UTF-16 formatted file using `efivar -n <uuid>-SystemdOptions -f <inputfile> -w` and after booting the system I confirmed it was decoded into `/run/systemd/efivars/SystemdOptions-<uuid>`.

Also included `systemd.log_level=debug` into that EFI variable and confirmed that `systemctl log-level` reported `debug`. So this is working as expected.

Cheers!
Filipe

**Comment by poettering** [comment]
bootctl has a verb for that: "systemd-efi-options"

**Comment by poettering** [comment]
Hmm, btw, thinking about "bootctl  systemd-efi-options" got me wondering if we should do more cache mgmt here, i.e. somehow mark the file as out-of-date when we change th EFI variable, and somehow refresh the file or bypass it in that case. But after thinking a bit more about that I think it's probably a bad idea, and the way you already implemented it has better semantics: it's a *good* thing if (just like /proc/cmdline) the cmdline when updated applies only to *future* boots, but not to current boots. Hence I think this is good to merge.
