### PR TITLE
ReFix #11128

### LINKED ISSUE #11128: CacheDirectory and LogsDirectory permissions not changed if the directory exists
**systemd version**
> 239

**Used distribution**
 > Debian Sid (LXC container running on Proxmox 5.2, Linux 4.15.18)

**Expected behaviour**
 > {State,Cache,Logs}Directory should be chmod/chown-ed based on the User/Group and *DirectoryMode options specified in the service file.

**Unexpected behaviour**
 > The permissions are not changed when the service starts if the directories already exist.

**Steps to reproduce the problem**

Considering this service file:
    
    [Unit]
    Description=Test Service
    After=network.target
    
    [Service]
    Type=simple
    ExecStart=echo "Test"
    
    SyslogIdentifier=test
    
    User=foo
    Group=bar
    PrivateTmp=yes
    LogsDirectory=test
    LogsDirectoryMode=750
    CacheDirectory=test
    CacheDirectoryMode=750
    
    [Install]
    WantedBy=multi-user.target

If the `/var/log/test/` directory doesn't exist, systemd creates it and sets the permissions as expected when the service is started:

    ebourg@icare:~$ ll -lhd /var/log/test
    ls: cannot access '/var/log/test': No such file or directory
    ebourg@icare:~$ sudo systemctl start test
    ebourg@icare:~$ ll -lhd /var/log/test
    drwxr-x--- 2 foo bar 4.0K Dec 12 12:46 /var/log/test

but if the directory already exists, neither the ownership nor the permissions are modified:

    ebourg@icare:~$ sudo rm -Rf /var/log/test
    ebourg@icare:~$ sudo mkdir /var/log/test/
    ebourg@icare:~$ sudo systemctl start test
    ebourg@icare:~$ ll -lhd /var/log/test
    drwxr-xr-x 2 root root 4.0K Dec 12 12:46 /var/log/test

I expected systemd to change the permissions as stated by the documentation:

> If the specified directories already exist and their owning user or group do not match the configured ones, all files and directories below the specified directories as well as the directories themselves will have their file ownership recursively changed to match what is configured.

### PR DESCRIPTION
**Pull request by taro-yamada**
I sent #11518 to fix #11128, and thankfully it was merged.
But it broke 30c81ce because I did not understand its intent well.

This PR changes to just output a warning about a difference of permissions without executing chmod().
I hope this change follows the intent of 30c81ce.

I'm so sorry for bothering you.

### CODE REVIEW

File: src/core/execute.c [hunk 1]
```diff
@@ -2161,10 +2161,18 @@ static int setup_exec_directory(
                         if (r < 0 && r != -EEXIST)
                                 goto fail;
                         if (r == -EEXIST) {
-                                if (chmod(p, context->directories[type].mode) < 0) {
+                                struct stat st;
+                                mode_t mask = 07777;
+                                r = stat(p, &st);
+                                if (r < 0) {
```
Comment (poettering) [inline src/core/execute.c]: maybe shorten these two lines to:

```c
```
if (stat(p, &st) < 0) {
…
```

After all, we don't really care about the actual return value of stat() after we checked for the failure

File: src/core/execute.c [hunk 2]
```diff
@@ -2161,10 +2161,18 @@ static int setup_exec_directory(
...
                                         r = -errno;
                                         goto fail;
                                 }
+                                if ((st.st_mode & mask) != context->directories[type].mode) {
```
Comment (poettering) [inline src/core/execute.c]: not that it matters, but i think it would be nicer to also mask the right-hand side of the comparison with 07777. I mean, the mode stored there shouldn't have any other bits set, but I think it would be more readable. i.e. maybe rewrite this check as:

```c
if ((st.st_mode ^ contrext->directories[type].mode) & 07777 != 0))
…
```

File: src/core/execute.c [hunk 3]
```diff
@@ -2161,10 +2161,18 @@ static int setup_exec_directory(
...
+                                        log_warning( "%s \'%s\' already exists but the mode is different.\n"
+                                                "filesystem: %o\t%sMode: %o\n",
+                                                exec_directory_type_to_string(type), *rt, st.st_mode & mask, exec_directory_type_to_string(type), context->directories[type].mode & mask);
```
Comment (poettering) [inline src/core/execute.c]: we usually use a slightly different indenting: we'd indent the two continuation lines above to the opening bracket of the function call they continue

File: src/core/execute.c [hunk 4]
```diff
@@ -2161,10 +2161,18 @@ static int setup_exec_directory(
                         if (r < 0 && r != -EEXIST)
                                 goto fail;
                         if (r == -EEXIST) {
-                                if (chmod(p, context->directories[type].mode) < 0) {
+                                struct stat st;
+                                mode_t mask = 07777;
+                                r = stat(p, &st);
```
Comment (yuwata) [inline src/core/execute.c]: Please add one empty line between the variable definition and `stat()`.

**Comment by yuwata** [comment]
@taro-yamada This contains two things, reverting your previous commit, and adding a warning. So, I think it is better to split the commit in that way: first revert the previous commit, and add the warning in the second commit.

**Comment by taro-yamada** [comment]
@poettering  @yuwata Thank you for mentering me.
I fixed the points pointed out.

File: src/core/execute.c [hunk 5]
```diff
@@ -2161,10 +2161,18 @@ static int setup_exec_directory(
                         if (r < 0 && r != -EEXIST)
                                 goto fail;
                         if (r == -EEXIST) {
-                                if (chmod(p, context->directories[type].mode) < 0) {
+                                struct stat st;
+                                mode_t mask = 07777;
```
Comment (yuwata) [inline src/core/execute.c]: It is not a strong opinion, but I prefer to drop the variable `mask`.

File: src/core/execute.c [hunk 6]
```diff
@@ -2161,10 +2161,18 @@ static int setup_exec_directory(
...
+
+                                if (stat(p, &st) < 0) {
                                         r = -errno;
                                         goto fail;
                                 }
+                                if (((st.st_mode ^ context->directories[type].mode) & mask ) != 0) {
```
Comment (yuwata) [inline src/core/execute.c]: Please drop a whitespace between `mask` and `)`.
Also, please drop unnecessary `{}`.

File: src/core/execute.c [hunk 7]
```diff
@@ -2161,10 +2161,18 @@ static int setup_exec_directory(
...
+                                        log_warning("%s \'%s\' already exists but the mode is different.\n"
+                                                    "filesystem: %o\t%sMode: %o\n",
+                                                    exec_directory_type_to_string(type), *rt, st.st_mode & mask, exec_directory_type_to_string(type), context->directories[type].mode & mask);
```
Comment (yuwata) [inline src/core/execute.c]: Please drop `\n` and `\t` from the log message.
Also, the argument line is too long... Please wrap the line at somewhere.

File: src/core/execute.c (hunk 5 above)
Comment (taro-yamada) [reply src/core/execute.c]: Is it OK to write "07777" directly in three places instead of "mask"?

**Comment by taro-yamada** [comment]
Thank you @yuwata,  so I wrote one question in requested changes.

File: src/core/execute.c (hunk 5 above)
Comment (poettering) [reply src/core/execute.c]: yes!

Comment (poettering) [reply src/core/execute.c]: (well, i mean, three places? you need it only once, no?)

Comment (yuwata) [reply src/core/execute.c]: Yeah, `mask` is used at three places.

Comment (poettering) [reply src/core/execute.c]: ah, true, seeing that now. but yeah, specifying htis literally thrice is OK, and I think more readable even...

**Comment by taro-yamada** [comment]
@poettering @yuwata I understand!
The change was applied.

**Comment by taro-yamada** [comment]
Thank you for merging!
