### PR TITLE
nspawn: fix copy/reflink fallback when directory already exists

### LINKED ISSUE #8780: systemd-nspawn --template Couldn't create snapshot on ext4
### Submission type

 - Bug report

### systemd version the issue has been seen with

238.76-1 (https://github.com/systemd/systemd-stable/commit/f398c546c6fc43121131f41acec56b5a851bd35e)

### Used distribution

ArchLinux

### In case of bug report: Expected behaviour you didn't see

When starting a container with the --template flag on an ext4 filesystem where the container's root directory already exists, it should start the container without any extra action. The systemd-nspawn man page says:

```
If this is specified and the container's root directory 
(as configured by --directory=) does not yet exist it
 is created as "btrfs" snapshot (if supported) or 
plain directory (otherwise) and populated from this 
template tree. 
```

### In case of bug report: Unexpected behaviour you saw

systemd-nspawn fails to create the container because it tries to create a snapshot even though the root already exists and the filesystem is not even a btrfs:

```
root@pbb2 ~# /usr/bin/systemd-nspawn --boot --machine=postgresql --template=/var/lib/machines/base
Couldn't create snapshot /var/lib/machines/postgresql from /var/lib/machines/base: Inappropriate ioctl for device
root@pbb2 ~#
```

### In case of bug report: Steps to reproduce the problem

Start a container with the --template option on an ext4 filesystem, stop it and start it again.

### PR DESCRIPTION
**Pull request by ghost**
fixes #8780

### CODE REVIEW

File: src/basic/btrfs-util.c [hunk 1]
```diff
@@ -1689,8 +1689,7 @@ int btrfs_subvol_snapshot_fd(int old_fd, const char *new_path, BtrfsSnapshotFlag
                 r = btrfs_subvol_make(new_path);
                 if (r == -ENOTTY && (flags & BTRFS_SNAPSHOT_FALLBACK_DIRECTORY)) {
                         /* If the destination doesn't support subvolumes, then use a plain directory, if that's requested. */
-                        if (mkdir(new_path, 0755) < 0)
-                                return r;
+                        (void) mkdir(new_path, 0755);
```
Comment (yuwata) [inline src/basic/btrfs-util.c]: ~~Ignoring all error here seems not good. I think only `EEXIST` should be ignored, if I correctly understand the issue #8780. I propose the following:~~
```
if (mkdir(new_path, 0755) < 0 && errno != EEXIST)
        return -errno;
```

File: src/basic/btrfs-util.c [hunk 2]
```diff
@@ -1689,8 +1689,7 @@ int btrfs_subvol_snapshot_fd(int old_fd, const char *new_path, BtrfsSnapshotFlag
                 r = btrfs_subvol_make(new_path);
                 if (r == -ENOTTY && (flags & BTRFS_SNAPSHOT_FALLBACK_DIRECTORY)) {
                         /* If the destination doesn't support subvolumes, then use a plain directory, if that's requested. */
-                        if (mkdir(new_path, 0755) < 0)
-                                return r;
```
Comment (poettering) [inline src/basic/btrfs-util.c]: so the existing code returns the original error ENOTTY if the fallback failed. This is what trips up the logic here. As the caller of this API expects to get EEXIST if the destination already exists, and not ENOTTY. Hence, the right fix should be as easy as changing `return r` → `return -errno`, so that the error of the `mkdir()` is propagated, and not the original btrfs ioctl error.

**Comment by petabyteboy** [comment]
I've implemented your suggestion and tested it.
Thanks for the great explanation.

**Comment by yuwata** [comment]
Ah, the caller already treats `-EEXIST`. Yeah, changing the return value seems sufficient.
Looks good to me now.
