### PR TITLE
journalctl: do not fail on SIGTERM/SIGINT or STDOUT disconnect when running with --follow

### LINKED ISSUE #38114: Closing stdout on journalctl --follow causes it to exit with non-zero exit code
### systemd version the issue has been seen with

257.5

### Used distribution

NixOS unstable

### Linux kernel version used

6.12.32

### CPU architectures issue was seen on

None

### Component

journalctl

### Expected behaviour you didn't see

When running `journalctl --follow | head -1`, `journalctl` exits with exit code 0

### Unexpected behaviour you saw

journalctl exits with exit code 1

### Steps to reproduce the problem

`journalctl --follow | head -1`

-----

I assumed that given #9374 it shouldn't error out when stdout closes or is piped around and closes. This is problematic for situations where pipefail is set in bash for example.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #38114.

### CODE REVIEW

File: src/shared/main-func.c [hunk 1]
```diff
@@ -32,25 +32,6 @@ void main_finalize(int r, int exit_status) {
...
 
-int raise_or_exit_status(int ret) {
-        if (ret < 0)
-                return EXIT_FAILURE;
-        if (ret == 0)
-                return EXIT_SUCCESS;
-        if (!SIGNAL_VALID(ret))
-                return EXIT_FAILURE;
-
-#if HAVE_VALGRIND_VALGRIND_H
```
Comment (YHNdnzj) [inline src/shared/main-func.c:43]: Inclusion of valgrind.h can be dropped?

Comment (YHNdnzj) [reply src/shared/main-func.c:43]: Plus signal-util.h and hashmap.h?

**Comment by yuwata** [comment]
@YHNdnzj @poettering Thank you for the review. Addressed the requests. Upgrading the green label.
