### PR TITLE
pe-binary: .initrd section is optional for UKI

### LINKED ISSUE #32774: ukify-generated efi file not recognized by bootctl and kernel-install
### systemd version the issue has been seen with

255.4

### Used distribution

Gentoo

### Linux kernel version used

6.6.30-gentoo

### CPU architectures issue was seen on

x86_64

### Component

bootctl, kernel-install, systemd-boot

### Expected behaviour you didn't see

My ukify-generated efi files are not recognized by `bootctl` and `kernel-install`. Namely

- `bootctl list` shows details about them
- `bootctl unlink` works
- `kernel-install remove` works

### Unexpected behaviour you saw

- Most invocations of `bootctl` and `kernel-install` show an error/warning in yellow for each of my ukis, which looks as follows:
      
      Parsed PE file '/boot/EFI/Linux/<uki filename>.efi' is not a UKI.

- The output of `bootctl list` for my ukis is listed as `(reported/absent)`:

        type: Reported by Boot Loader
       title: <uki filename>.efi (reported/absent)
          id: <uki filename>.efi
      source: /sys/firmware/efi/efivars/LoaderEntries-<some uuid>

- `bootctl unlink` does not work, i.e., the selected uki is not unlinked/removed (autocompletion of kernels works, no error message shown)
- `kernel-install remove` does not work, i.e., no uki can be selected using autocomplete

### Steps to reproduce the problem

- configure kernel (particularities: no initrd, kernel command line options embedded in-kernel)
- `make`
- `make modules_install && make install`
- reboot into new kernel (no problem, systemd-boot works as expected)
- do any of the actions involving `bootctl` or `kernel-install` mentioned above

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
.osrel is also optional, but sd-boot and bootctl requires it. So, let's keep .osrel section at least now.

Fixes #32774.

### CODE REVIEW

File: src/shared/pe-binary.c [hunk 1]
```diff
@@ -236,6 +236,5 @@ bool pe_is_uki(const PeHeader *pe_header, const IMAGE_SECTION_HEADER *sections)
 
         return
                 pe_header_find_section(pe_header, sections, ".osrel") &&
-                pe_header_find_section(pe_header, sections, ".linux") &&
-                pe_header_find_section(pe_header, sections, ".initrd");
+                pe_header_find_section(pe_header, sections, ".linux");
```
Comment (poettering) [inline src/shared/pe-binary.c:241]: I think we should add a comment here, something along the lines of `/* Note that the UKI spec only requires .linux, but we are stricter here, and require .osrel too, since for sd-boot it just doesn't make sense to not have that.*/`

Comment (yuwata) [reply src/shared/pe-binary.c:241]: Okay, added.

**Review by keszybz — APPROVED** [review]
