### PR TITLE
journalctl: call all cleanup functions before raise()

### LINKED ISSUE #30995: `journalctl --follow` does not free memory on exit
### systemd version the issue has been seen with

255-1269-g2d1e7d1

### Used distribution

openSUSE Tumbleweed

### Linux kernel version used

6.6.9-1-default

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

`journalctl --follow` frees memory on exit.

### Unexpected behaviour you saw

`journalctl --follow` does not free memory on exit.

### Steps to reproduce the problem

This was a design choice in #27519, instead of returning cleanly from the main process, the signal is re-sent to exit with the signal's exit code.

https://github.com/systemd/systemd/blob/ee8f3e489e200c05e23bb3d7c6c75804df58e752/src/journal/journalctl.c#L2690-L2693

But, the common way to exit `--follow` is with `Ctrl+c`, so maybe at least SIGINT should not be propagated and return 0 in this case.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Closes #30995.

### CODE REVIEW

File: src/shared/main-func.h [hunk 1]
```diff
@@ -40,3 +41,18 @@
  * Note: "true" means failure! */
 #define DEFINE_MAIN_FUNCTION_WITH_POSITIVE_FAILURE(impl)                \
         _DEFINE_MAIN_FUNCTION(,impl(argc, argv), r < 0 ? EXIT_FAILURE : r)
+
+static inline int raise_or_exit(int ret) {
+        if (ret < 0)
+                return EXIT_FAILURE;
+        if (ret == 0)
+                return EXIT_SUCCESS;
+        if (SIGNAL_VALID(ret))
```
Comment (YHNdnzj) [inline src/shared/main-func.h]:
```suggestion
        if (!SIGNAL_VALID(ret))
```

File: src/shared/main-func.h [hunk 2]
```diff
@@ -6,13 +6,15 @@
...
+#include "hashmap.h"
 #include "pager.h"
 #include "selinux-util.h"
+#include "signal-util.h"
 #include "spawn-ask-password-agent.h"
 #include "spawn-polkit-agent.h"
 #include "static-destruct.h"
 
-#define _DEFINE_MAIN_FUNCTION(intro, impl, ret)                         \
+#define _DEFINE_MAIN_FUNCTION(intro, impl, result_to_exit_status, result_to_return_value) \
```
Comment (YHNdnzj) [inline src/shared/main-func.h:17]: Hmm, why use different values for EXIT_STATUS= notification and real exit code? And pid1 doesn't really make use of EXIT_STATUS= anyway 🤔

**Review by YHNdnzj — APPROVED** [review]

**Comment by poettering** [comment]
hmm, why bother with raising the original signal anyway? I'd just exit cleanly on SIGINT/SIGTERM quite frnakly.

**Comment by yuwata** [comment]
> hmm, why bother with raising the original signal anyway? I'd just exit cleanly on SIGINT/SIGTERM quite frnakly.

I did so, but @keszybz requested to pass the original signal:
https://github.com/systemd/systemd/pull/27519#discussion_r1205281175.

**Review by keszybz — CHANGES_REQUESTED** [review]
Hmm, we already have a static destructor `cleanup_pools()` which only does anything when on valgrind. And apparently, it was not called when interrupted, but only on normal exit.

With your patch, the hashmap destructors will be called twice on normal exit:
```console
$ SYSTEMD_LOG_LEVEL=debug valgrind build/journalctl -n 0 --no-pager
...
Trimmed 3.9K from memory pool 0x4dc0d40. (0B left)
Trimmed 11.8K from memory pool 0x4dc0d60. (0B left)
Trimmed 0B from memory pool 0x4dc0d40. (0B left)
Trimmed 0B from memory pool 0x4dc0d60. (0B left)
```

Something strange is going on. Your first patch adds a call to `hashmap_trim_pools()` right after `static_destruct()`. In case of a normal exit, we clearly call `hashmap_trim_pools()` twice, as expected with that patch. But when interrupted, we only get one call.

I think that `static_destruct()` is somehow borked. If we fix that, then we don't need the duplicate call to `hashmap_trim_pools()`.

**Comment by yuwata** [comment]
> Oh, stupid me. The thing in hashmap.c is a real "destructor", the only place where we use `__attribute__((__destructor__))`. So this doesn't get called because it's not using our bespoke STATIC_DESTRUCTOR machinery.
> 
> I'm not sure what to do here, but anyway, I think the end effect should be that: a) the hashmap cleanup is only called once, and b) we should keep the conditionalization on valgrind. Freeing the mempools is a waste of time if the kernel is going to immediately destroy all memory anyway.

valgrind is only used for debugging or so. Calling twice is not bad in debugging code, as running binary on valgrind is already slow in general. Also, I expect the second call of `hashmap_trim_pools()` should not be so heavy. I do not think we should optimize such situation.

File: src/shared/main-func.h [hunk 3]
```diff
@@ -21,22 +23,49 @@
...
+}
 
 /* Zero is mapped to EXIT_SUCCESS, negative values are mapped to EXIT_FAILURE,
  * and positive values are propagated.
  * Note: "true" means failure! */
 #define DEFINE_MAIN_FUNCTION_WITH_POSITIVE_FAILURE(impl)                \
-        _DEFINE_MAIN_FUNCTION(,impl(argc, argv), r < 0 ? EXIT_FAILURE : r)
+        _DEFINE_MAIN_FUNCTION(,impl(argc, argv), fail_on_nonzero, fail_on_nonzero)
+
+static inline int raise_or_exit(int ret) {
```
Comment (poettering) [inline src/shared/main-func.h]: this doesn't exit() like the name suggests.

maybe call this raise_or_exit_status() or so?

File: src/shared/main-func.h [hunk 4]
```diff
@@ -21,22 +23,49 @@
...
+        if (ret < 0)
+                return EXIT_FAILURE;
+        if (ret == 0)
+                return EXIT_SUCCESS;
+        if (!SIGNAL_VALID(ret))
+                return EXIT_FAILURE;
+        if (raise(ret) < 0)
```
Comment (poettering) [inline src/shared/main-func.h]: i think it would be safer to just do return EXIT_FAILURE here in case raise() doesn't immediately abort the program. After all signals can be masked, and I think in that case we better should exit with a failure than just raise a signal again (which assert_not_reached()) after all does.

**Comment by poettering** [comment]
Frankly, I am not sure there's any problem here in the first place. I think there are two reasonable ways to react to SIGTERM + SIGINT: clean up and exit cleanly. Or don't clean up and let the OS process cleanup logic take care of everything. I find this mixture of raising the signal but cleaning up things a bit weird, tbh.

File: src/shared/main-func.h [hunk 5]
```diff
@@ -27,6 +28,7 @@
                 pager_close();                                          \
                 mac_selinux_finish();                                   \
                 static_destruct();                                      \
+                hashmap_trim_pools();                                   \
```
Comment (poettering) [inline src/shared/main-func.h]: hmm, do we really want this? it's useless busywork. It makes sense in valgrind, but otherwise I am not sure it's worth the effort.

so far the cleanup destructor conditioned this on valgrind. Why drop that conditioning?

File: src/shared/tests.h [hunk 6]
```diff
@@ -187,6 +187,7 @@ static inline int run_test_table(void) {
                         _r = run_test_table();            \
                 _q = _outro ? _outro() : EXIT_SUCCESS;    \
                 static_destruct();                        \
+                hashmap_trim_pools();                     \
```
Comment (poettering) [inline src/shared/tests.h]: i think in the tests it makes a lot of sense to do this always, hence this addition does make a ton of sense to me.

File: src/shared/main-func.h [hunk 7]
```diff
@@ -22,23 +22,32 @@
...
                 polkit_agent_close();                                   \
                 pager_close();                                          \
                 mac_selinux_finish();                                   \
                 static_destruct();                                      \
                 hashmap_trim_pools();                                   \
-                return ret;                                             \
+                return result_to_exit_status(r);                        \
         }
 
+static inline int fail_on_negative(int result) {
```
Comment (poettering) [inline src/shared/main-func.h]: maybe call exit_failure_if_negative()?

File: src/shared/main-func.h [hunk 8]
```diff
@@ -22,23 +22,32 @@
...
+        return result < 0 ? EXIT_FAILURE : EXIT_SUCCESS;
+}
+
 /* Negative return values from impl are mapped to EXIT_FAILURE, and
  * everything else means success! */
 #define DEFINE_MAIN_FUNCTION(impl)                                      \
-        _DEFINE_MAIN_FUNCTION(,impl(argc, argv), r < 0 ? EXIT_FAILURE : EXIT_SUCCESS)
+        _DEFINE_MAIN_FUNCTION(,impl(argc, argv), fail_on_negative)
+
+static inline int fail_on_nonzero(int result) {
```
Comment (poettering) [inline src/shared/main-func.h]: exit_failure_if_nonzero?

**Comment by poettering** [comment]
so, i find the goal here a bit weird, i.e. trying to clean up memory in abnormal termination conditions (which term-by-signals qualifies as I'd say). @keszybz wanted this, as I understand. I don't care too much, hence, if there's interest I think the general approach can work and is fine. But some comments above.

File: src/shared/tests.h (hunk 6 above)
Comment (yuwata) [reply src/shared/tests.h]: Maybe. But tentatively dropped, now this change is unrelated to this PR.

**Comment by yuwata** [comment]
I re-read comments about by @keszybz and @poettering hashmap mempool cleanups. And now I changed my mind.
In the revised version, `hashmap_trim_pools()` is only called when running on valgrind and `raise()` will be called.
PTAL.

**Review by YHNdnzj — APPROVED** [review]
