### PR TITLE
sysusers: do not create duplicated groups when create users 

### LINKED ISSUE #8315: sysusers creating duplicate group entries
### Submission type

 - Bug report

### systemd version the issue has been seen with

>237 specifically 7909254c7a8ee09d91b8b21fd779320b3e2fe716 of systemd-stable

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

>systemd-sysusers generate /etc/groups free from duplicate entries

### In case of bug report: Unexpected behaviour you saw

>systemd-sysusers generate /etc/groups with multiple duplicate entries

### In case of bug report: Steps to reproduce the problem

>execute systemd-sysusers with the following config present
```
# default arch groups
# groups first, because we have user/group id mismatch on ftp and mail
g sys 3 - -
g mem 8 - -
g ftp 11 - -
g mail 12 - -
g log 19 - -
g smmsp 25 - -
g proc 26 - -
g games 50 - -
g lock 54 - -
g network 90 - -
g floppy 94 - -
g scanner 96 - -
g power 98 - -

# default arch users
u bin 1 - -
u daemon 2 - -
u mail 8 - /var/spool/mail
u ftp 14 - /srv/ftp
u http 33 - /srv/http

# default membership
m bin daemon
m bin sys
m daemon adm
m daemon bin
```
before executing the command the only entry in passwd and group files is for root
https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/filesystem&id=bc695be763be4b553a31cf899dc5badfb6f1a0aa
Other entries /usr/lib/sysusers.d/
systemd-remote.conf basic.conf systemd.conf as supplied by systemd
dbus.conf with contents
```
# sysusers.d snippet for creating the D-Bus system user automatically
# at boot on systemd-based systems that ship with an unpopulated
# /etc. See sysusers.d(5) for details.

u dbus 81 "System Message Bus"
```
util-linux.conf with contents
```
u uuidd 68
g rfkill - - -
```
```
# SYSTEMD_LOG_LEVEL=debug systemd-sysusers
Adding implicit group 'daemon' due to m line
Adding implicit group 'bin' due to m line
Creating group sys with gid 3.
Creating group mem with gid 8.
Creating group ftp with gid 11.
Creating group mail with gid 12.
Creating group log with gid 19.
Creating group smmsp with gid 25.
Creating group proc with gid 26.
Creating group games with gid 50.
Creating group lock with gid 54.
Creating group network with gid 90.
Creating group floppy with gid 94.
Creating group scanner with gid 96.
Creating group power with gid 98.
Creating group adm with gid 999.
Creating group wheel with gid 998.
Creating group kmem with gid 997.
Creating group tty with gid 5.
Creating group utmp with gid 996.
Creating group audio with gid 995.
Creating group optical with gid 994.
Creating group uucp with gid 993.
Creating group disk with gid 992.
Creating group input with gid 991.
Creating group kvm with gid 990.
Creating group lp with gid 989.
Creating group render with gid 988.
Creating group storage with gid 987.
Creating group video with gid 986.
Creating group users with gid 985.
Creating group systemd-journal with gid 984.
Creating group rfkill with gid 983.
Creating group daemon with gid 982.
Creating group bin with gid 981.
Creating group bin with gid 1.
Creating user bin (n/a) with uid 1 and gid 1.
Creating group daemon with gid 2.
Creating user daemon (n/a) with uid 2 and gid 2.
Creating group mail with gid 980.
Suggested user ID 8 for mail already used.
Creating user mail (n/a) with uid 980 and gid 980.
Creating group ftp with gid 14.
Creating user ftp (n/a) with uid 14 and gid 14.
Creating group http with gid 33.
Creating user http (n/a) with uid 33 and gid 33.
Group root already exists.
User root already exists.
Creating group nobody with gid 65534.
Creating user nobody (Nobody) with uid 65534 and gid 65534.
Creating group dbus with gid 81.
Creating user dbus (System Message Bus) with uid 81 and gid 81.
Creating group systemd-journal-remote with gid 979.
Creating user systemd-journal-remote (systemd Journal Remote) with uid 979 and gid 979.
Creating group systemd-network with gid 978.
Creating user systemd-network (systemd Network Management) with uid 978 and gid 978.
Creating group systemd-resolve with gid 977.
Creating user systemd-resolve (systemd Resolver) with uid 977 and gid 977.
Creating group systemd-coredump with gid 976.
Creating user systemd-coredump (systemd Core Dumper) with uid 976 and gid 976.
Creating group uuidd with gid 68.
Creating user uuidd (n/a) with uid 68 and gid 68.
```
Generated /etc/group
```
root:x:0:root
sys:x:3:bin
mem:x:8:
ftp:x:11:
mail:x:12:
log:x:19:
smmsp:x:25:
proc:x:26:
games:x:50:
lock:x:54:
network:x:90:
floppy:x:94:
scanner:x:96:
power:x:98:
adm:x:999:daemon
wheel:x:998:
kmem:x:997:
tty:x:5:
utmp:x:996:
audio:x:995:
optical:x:994:
uucp:x:993:
disk:x:992:
input:x:991:
kvm:x:990:
lp:x:989:
render:x:988:
storage:x:987:
video:x:986:
users:x:985:
systemd-journal:x:984:
rfkill:x:983:
daemon:x:982:bin
bin:x:981:daemon
bin:x:1:daemon
daemon:x:2:bin
mail:x:980:
ftp:x:14:
http:x:33:
nobody:x:65534:
dbus:x:81:
systemd-journal-remote:x:979:
systemd-network:x:978:
systemd-resolve:x:977:
systemd-coredump:x:976:
uuidd:x:68:
```
Generated /etc/passwd
```
$ cat target/etc/passwd
root:x:0:0::/root:/bin/bash
bin:x:1:1::/:/sbin/nologin
daemon:x:2:2::/:/sbin/nologin
mail:x:980:980::/var/spool/mail:/sbin/nologin
ftp:x:14:14::/srv/ftp:/sbin/nologin
http:x:33:33::/srv/http:/sbin/nologin
nobody:x:65534:65534:Nobody:/:/sbin/nologin
dbus:x:81:81:System Message Bus:/:/sbin/nologin
systemd-journal-remote:x:979:979:systemd Journal Remote:/:/sbin/nologin
systemd-network:x:978:978:systemd Network Management:/:/sbin/nologin
systemd-resolve:x:977:977:systemd Resolver:/:/sbin/nologin
systemd-coredump:x:976:976:systemd Core Dumper:/:/sbin/nologin
uuidd:x:68:68::/:/sbin/nologin
```
Output from grpchk
```
grpck -r
duplicate group entry
delete line 'ftp:x:11:'? No
duplicate group entry
delete line 'mail:x:12:'? No
duplicate group entry
delete line 'daemon:x:982:bin'? No
duplicate group entry
delete line 'bin:x:981:daemon'? No
duplicate group entry
delete line 'bin:x:1:daemon'? No
duplicate group entry
delete line 'daemon:x:2:bin'? No
duplicate group entry
delete line 'mail:x:980:'? No
duplicate group entry
delete line 'ftp:x:14:'? No
duplicate shadow group entry
delete line 'ftp:!!::'? No
duplicate shadow group entry
delete line 'mail:!!::'? No
duplicate shadow group entry
delete line 'daemon:!!::bin'? No
duplicate shadow group entry
delete line 'bin:!!::daemon'? No
duplicate shadow group entry
delete line 'bin:!!::daemon'? No
duplicate shadow group entry
delete line 'daemon:!!::bin'? No
duplicate shadow group entry
delete line 'mail:!!::'? No
duplicate shadow group entry
delete line 'ftp:!!::'? No
grpck: no changes
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #8315.

### CODE REVIEW

**Comment by yuwata** [comment]
Hmm.
```
========== TEST-21-SYSUSERS ==========
make: Entering directory '/tmp/autopkgtest.gYJtXK/build.RIu/debian/test/TEST-21-SYSUSERS'
TEST CLEANUP: Sysuser-related tests
TEST SETUP: Sysuser-related tests
TEST RUN: Sysuser-related tests
*** Running test-1.input
*** Running test-2.input
*** Running test-3.input
*** Running test-4.input
*** Running test-5.input
*** Running test-6.input
*** Running test-7.input
--- /var/tmp/systemd-test.UakIQ3/etc/passwd	2018-03-01 06:44:22.518889250 +0000
+++ /dev/fd/61	2018-03-01 06:44:22.518889250 +0000
@@ -1,5 +1,5 @@
 bin:x:1:1::/:/sbin/nologin
 daemon:x:2:2::/:/sbin/nologin
-mail:x:999:0::/var/spool/mail:/sbin/nologin
-ftp:x:14:0::/srv/ftp:/sbin/nologin
+mail:x:8:12::/var/spool/mail:/sbin/nologin
+ftp:x:14:11::/srv/ftp:/sbin/nologin
 http:x:33:33::/srv/http:/sbin/nologin
**** Unexpected output for test-7.input
make: *** [run] Error 1
Makefile:4: recipe for target 'run' failed
make: Leaving directory '/tmp/autopkgtest.gYJtXK/build.RIu/debian/test/TEST-21-SYSUSERS'
```

**Comment by yuwata** [comment]
```
*** Running test-7.input --- /var/tmp/systemd-test.2vMmBN/etc/passwd 2018-03-01 09:49:44.234267749 +0000 +++ /dev/fd/61 2018-03-01 09:49:44.234267749 +0000 @@ -1,5 +1,5 @@ bin:x:1:1::/:/sbin/nologin daemon:x:2:2::/:/sbin/nologin -mail:x:12:12::/var/spool/mail:/sbin/nologin +mail:x:8:12::/var/spool/mail:/sbin/nologin ftp:x:14:11::/srv/ftp:/sbin/nologin http:x:33:33::/srv/http:/sbin/nologin **** Unexpected output for test-7.input make: *** [run] Error 1 Makefile:4: recipe for target 'run' failed
```

File: src/sysusers/sysusers.c [hunk 1]
```diff
@@ -1209,12 +1209,23 @@ static int process_item(Item *i) {
...
-                if (r < 0)
-                        return r;
+        case ADD_USER: {
+                Item *j;
+
+                j = ordered_hashmap_get(groups, i->name);
+                if (j && j->todo_group) {
+                        /* The group with the same name is already in queue.
+                         * So, let's use the information about the group. */
+                        i->gid_set = j->gid_set;
```
Comment (mvo5) [inline src/sysusers/sysusers.c]: This is still failing because "add_user()" will do a uid_is_ok()" check which will prevent different uid/groupid. This means that user "mail" gets 12:12 because the code will reuse the group id. I think this is expected behaviour and consistent with what systemd-sysusers was doing before we added the extended "uid:gid" syntax. So I think this PR just needs a test update to `mail:x:12:12..:`.

To get 8:12 it would be possible to set `i->id_set_strict = true` here. I tested this locally and with that all existing tests pass. However this also will cause unwanted side effects (i.e. if the uid is already taken it will create wrong entries now). So we would need a way to specify that we only want the gid to be fixed.

Comment (mvo5) [reply src/sysusers/sysusers.c]: Please let me know if I can help in any way, happy to take your PR and tweak the test (but given how trivial that is it is probably not worth it).

Comment (yuwata) [reply src/sysusers/sysusers.c]: > To get 8:12 it would be possible to set i->id_set_strict = true here. 

Good catch! Thanks.

**Comment by yuwata** [comment]
Updated.

File: src/sysusers/sysusers.c (hunk 1 above)
Comment (yuwata) [reply src/sysusers/sysusers.c]: > However this also will cause unwanted side effects (i.e. if the uid is already taken it will create wrong entries now).

Hmm? Could you give me an example for this?

Comment (mvo5) [reply src/sysusers/sysusers.c]: You are right, I think this is actually ok - I was misrembering what id_set_strict checks - but it only checks for group id clashes so that is fine and we can add it. I also think its the right thing to do and in line what the users expect. But AFAICT it's a behaviour change from the old code (even from the code from before uid:gid) because that code would detect the uid/gid name match and also match the uid/gid. However I think its ok to argue this is a bugfix. So from my POV adding i->id_set_strict = true is fine. We might release note it (that something changed in this particular corner case).

**Comment by yuwata** [comment]
@mvo5 Thank you for the comments.
Now, at least one Ubuntu CI passes. So, I removed 'WIP' from the title of this PR and 'dont-merge' tag.

**Comment by yuwata** [comment]
Updated. Added one more commit to fix the behavior of 'm' line.

**Comment by yuwata** [comment]
Fedora and artful-i386 failure are not related to this.

**Comment by keszybz** [comment]
```
autopkgtest login: 
---------------------------------------------------
<VirtSubproc>: failure: Timed out on waiting for ssh connection
autopkgtest [01:32:17]: ERROR: testbed failure: cannot send to testbed: [Errno 32] Broken pipe
```
