### PR TITLE
conf-parse: make config_parse_many() optionally save 'struct stat' for each file

### LINKED ISSUE #21113: networkd not reloading / reconfiguring new addresses on interface
**systemd version the issue has been seen with**
 > 249.5

**Used distribution**
 > yocto

**Linux kernel version used** (`uname -a`)

 > 4.10.62

**CPU architecture issue was seen on**
 > arm

**Expected behaviour you didn't see**
 > Addresses that were added to the network file were not added to the interface

**Unexpected behaviour you saw**

**Steps to reproduce the problem**
 > Configure the interface without addresses on a running networkd such as (/etc/systemd/network/00-bmc-eth0.network)
```
[Match]
Name=eth0
[Link]
MACAddress=3c:28:6d:4d:c8:2e
[Network]
LinkLocalAddressing=ipv6
IPv6AcceptRA=false
DHCP=false
```
> Write a new configuration with some addresses
```
[Match]
Name=eth0
[Link]
MACAddress=3c:28:6d:4d:c8:2e
[Network]
LinkLocalAddressing=ipv6
IPv6AcceptRA=false
DHCP=false
[Address]
Address=2002:a05:6661:396::/128
[Route]
Gateway=fe80::1
[Neighbor]
Address=fe80::1
MACAddress=2:32:0:0:0:0
```
> Execute a reload and reconfigure
```
networkctl reload
networkctl reconfigure eth0
```

**Additional program output to the terminal or log subsystem illustrating the issue**
```
Got message type=method_call sender=:1.36 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.network1.Manager member=Reload cookie=125 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=35 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.87 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=35 signature=u error-name=n/a error-message=n/a
/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
Sent message type=method_return sender=n/a destination=:1.36 path=n/a interface=n/a member=n/a cookie=36 reply_cookie=125 signature=n/a error-name=n/a error-message=n/a
eth1: found matching network '/etc/systemd/network/00-bmc-eth1.network'.
eth0: found matching network '/etc/systemd/network/00-bmc-eth0.network'.
Got message type=method_call sender=:1.36 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.network1.Manager member=Reload cookie=130 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=37 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.87 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=37 signature=u error-name=n/a error-message=n/a
/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
Sent message type=method_return sender=n/a destination=:1.36 path=n/a interface=n/a member=n/a cookie=38 reply_cookie=130 signature=n/a error-name=n/a error-message=n/a
eth1: found matching network '/etc/systemd/network/00-bmc-eth1.network'.
eth0: found matching network '/etc/systemd/network/00-bmc-eth0.network'.
Got message type=method_call sender=:1.36 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.network1.Manager member=Reload cookie=134 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=39 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.87 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=39 signature=u error-name=n/a error-message=n/a
/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
Sent message type=method_return sender=n/a destination=:1.36 path=n/a interface=n/a member=n/a cookie=40 reply_cookie=134 signature=n/a error-name=n/a error-message=n/a
eth1: found matching network '/etc/systemd/network/00-bmc-eth1.network'.
eth0: found matching network '/etc/systemd/network/00-bmc-eth0.network'.
Got message type=method_call sender=:1.36 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.network1.Manager member=Reload cookie=139 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=41 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.87 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=41 signature=u error-name=n/a error-message=n/a
/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
Sent message type=method_return sender=n/a destination=:1.36 path=n/a interface=n/a member=n/a cookie=42 reply_cookie=139 signature=n/a error-name=n/a error-message=n/a
eth1: found matching network '/etc/systemd/network/00-bmc-eth1.network'.
eth0: found matching network '/etc/systemd/network/00-bmc-eth0.network'.
Got message type=method_call sender=:1.36 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.network1.Manager member=Reload cookie=147 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=43 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.87 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=43 signature=u error-name=n/a error-message=n/a
/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
Sent message type=method_return sender=n/a destination=:1.36 path=n/a interface=n/a member=n/a cookie=44 reply_cookie=147 signature=n/a error-name=n/a error-message=n/a
eth1: found matching network '/etc/systemd/network/00-bmc-eth1.network'.
eth0: found matching network '/etc/systemd/network/00-bmc-eth0.network'.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
rtnl: received non-static neighbor, ignoring.
Got message type=method_call sender=:1.136 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=Get cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
Failed to stat network namespace, ignoring: No such file or directory
Sent message type=method_return sender=n/a destination=:1.136 path=n/a interface=n/a member=n/a cookie=45 reply_cookie=2 signature=v error-name=n/a error-message=n/a
Got message type=method_call sender=:1.137 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=Get cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
Failed to stat network namespace, ignoring: No such file or directory
Sent message type=method_return sender=n/a destination=:1.137 path=n/a interface=n/a member=n/a cookie=46 reply_cookie=2 signature=v error-name=n/a error-message=n/a
Got message type=method_call sender=:1.138 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.network1.Manager member=Reload cookie=2 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=47 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.87 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=47 signature=u error-name=n/a error-message=n/a
/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
Sent message type=method_return sender=n/a destination=:1.138 path=n/a interface=n/a member=n/a cookie=48 reply_cookie=2 signature=n/a error-name=n/a error-message=n/a
eth1: found matching network '/etc/systemd/network/00-bmc-eth1.network'.
eth0: found matching network '/etc/systemd/network/00-bmc-eth0.network'.
Got message type=method_call sender=:1.139 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=Get cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
Failed to stat network namespace, ignoring: No such file or directory
Sent message type=method_return sender=n/a destination=:1.139 path=n/a interface=n/a member=n/a cookie=49 reply_cookie=2 signature=v error-name=n/a error-message=n/a
Got message type=method_call sender=:1.140 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=Get cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
Failed to stat network namespace, ignoring: No such file or directory
Sent message type=method_return sender=n/a destination=:1.140 path=n/a interface=n/a member=n/a cookie=50 reply_cookie=2 signature=v error-name=n/a error-message=n/a
Got message type=method_call sender=:1.141 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.network1.Manager member=ReconfigureLink cookie=2 reply_cookie=0 signature=i error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=51 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.87 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=51 signature=u error-name=n/a error-message=n/a
eth0: State changed: configured -> initialized
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=52 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=method_return sender=n/a destination=:1.141 path=n/a interface=n/a member=n/a cookie=53 reply_cookie=2 signature=n/a error-name=n/a error-message=n/a
eth0: found matching network '/etc/systemd/network/00-bmc-eth0.network'.
eth0: Re-configuring with /etc/systemd/network/00-bmc-eth0.network
eth0: LLDP: Stopping LLDP client
eth0: State changed: initialized -> configuring
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=54 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Setting '/proc/sys/net/ipv6/conf/eth0/disable_ipv6' to '0'
Setting '/proc/sys/net/ipv6/conf/eth0/use_tempaddr' to '0'
Setting '/proc/sys/net/ipv6/conf/eth0/accept_ra' to '0'
Setting '/proc/sys/net/ipv6/conf/eth0/proxy_ndp' to '0'
Setting '/proc/sys/net/ipv4/conf/eth0/promote_secondaries' to '1'
eth0: Requested to set IPv6LL address generation mode
eth0: Requested to set master interface
eth0: Requested to activate link
eth0: LLDP: Started LLDP client
eth0: Started LLDP.
eth0: link_check_ready(): link layer is configuring.
eth0: link_check_ready(): link layer is configuring.
eth0: link_check_ready(): link layer is configuring.
eth0: link_check_ready(): link layer is configuring.
eth0: link_check_ready(): link layer is configuring.
eth0: link_check_ready(): link layer is configuring.
eth0: link_check_ready(): link layer is configuring.
eth0: link_check_ready(): link layer is configuring.
eth0: link_check_ready(): link layer is configuring.
eth0: Setting IPv6LL address generation mode
eth0: Setting master interface
eth0: IPv6LL address generation mode set.
eth0: master interface set.
eth0: link_check_ready(): link is not activated.
eth0: Bringing link up
eth0: State changed: configuring -> configured
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=55 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #21113.

### CODE REVIEW

File: src/network/networkd-network.c [hunk 1]
```diff
@@ -580,6 +580,28 @@ int network_load(Manager *manager, OrderedHashmap **networks) {
         return 0;
 }
 
+static bool stats_by_path_equal(Hashmap *a, Hashmap *b) {
```
Comment (poettering) [inline src/network/networkd-network.c:583]: is "equal" really the right name for this? maybe "_unmodified"?

Comment (yuwata) [reply src/network/networkd-network.c:583]: For me, "equal" sounds suitable for "stats", and "unmodified" sounds suitable for "file" (or "path").
So, I prefer "equal" here. But not strong opinion. If you or others prefer "unmodified", then I will rename it.
