### PR TITLE
systemctl: format many entries in 'show' command

### LINKED ISSUE #11869: RestartPreventExitStatus= missing from "systemctl show" output
Having a service like this

```
# /lib/systemd/system/ssh.service
[Unit]
Description=OpenBSD Secure Shell server
Documentation=man:sshd(8) man:sshd_config(5)
After=network.target auditd.service
ConditionPathExists=!/etc/ssh/sshd_not_to_be_run

[Service]
EnvironmentFile=-/etc/default/ssh
ExecStartPre=/usr/sbin/sshd -t
ExecStart=/usr/sbin/sshd -D $SSHD_OPTS
ExecReload=/usr/sbin/sshd -t
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=notify
RuntimeDirectory=sshd
RuntimeDirectoryMode=0755

[Install]
WantedBy=multi-user.target
```
It would be nice if "systemctl show ssh.service" would list the value of `RestartPreventExitStatus=255`

```
Type=notify
Restart=on-failure
NotifyAccess=main
RestartUSec=100ms
TimeoutStartUSec=1min 30s
TimeoutStopUSec=1min 30s
RuntimeMaxUSec=infinity
WatchdogUSec=0
WatchdogTimestampMonotonic=0
RootDirectoryStartOnly=no
RemainAfterExit=no
GuessMainPID=yes
MainPID=0
ControlPID=0
FileDescriptorStoreMax=0
NFileDescriptorStore=0
StatusErrno=0
Result=exit-code
UID=[not set]
GID=[not set]
NRestarts=5
ExecMainStartTimestampMonotonic=0
ExecMainExitTimestampMonotonic=0
ExecMainPID=0
ExecMainCode=0
ExecMainStatus=0
ExecStartPre={ path=/usr/sbin/sshd ; argv[]=/usr/sbin/sshd -t ; ignore_errors=no ; start_time=[Sat 2019-03-02 14:23:35 CET] ; stop_time=[Sat 2019-03-02 14:23:35 CET] ; pid=14514 ; code=exited ; status=255 }
ExecStart={ path=/usr/sbin/sshd ; argv[]=/usr/sbin/sshd -D $SSHD_OPTS ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecReload={ path=/usr/sbin/sshd ; argv[]=/usr/sbin/sshd -t ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecReload={ path=/bin/kill ; argv[]=/bin/kill -HUP $MAINPID ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
Slice=system.slice
MemoryCurrent=[not set]
CPUUsageNSec=[not set]
TasksCurrent=[not set]
IPIngressBytes=18446744073709551615
IPIngressPackets=18446744073709551615
IPEgressBytes=18446744073709551615
IPEgressPackets=18446744073709551615
Delegate=no
CPUAccounting=no
CPUWeight=[not set]
StartupCPUWeight=[not set]
CPUShares=[not set]
StartupCPUShares=[not set]
CPUQuotaPerSecUSec=infinity
IOAccounting=no
IOWeight=[not set]
StartupIOWeight=[not set]
BlockIOAccounting=no
BlockIOWeight=[not set]
StartupBlockIOWeight=[not set]
MemoryAccounting=yes
MemoryMin=0
MemoryLow=0
MemoryHigh=infinity
MemoryMax=infinity
MemorySwapMax=infinity
MemoryLimit=infinity
DevicePolicy=auto
TasksAccounting=yes
TasksMax=4915
IPAccounting=no
EnvironmentFiles=/etc/default/ssh (ignore_errors=yes)
UMask=0022
LimitCPU=infinity
LimitCPUSoft=infinity
LimitFSIZE=infinity
LimitFSIZESoft=infinity
LimitDATA=infinity
LimitDATASoft=infinity
LimitSTACK=infinity
LimitSTACKSoft=8388608
LimitCORE=infinity
LimitCORESoft=0
LimitRSS=infinity
LimitRSSSoft=infinity
LimitNOFILE=524288
LimitNOFILESoft=1024
LimitAS=infinity
LimitASSoft=infinity
LimitNPROC=63254
LimitNPROCSoft=63254
LimitMEMLOCK=65536
LimitMEMLOCKSoft=65536
LimitLOCKS=infinity
LimitLOCKSSoft=infinity
LimitSIGPENDING=63254
LimitSIGPENDINGSoft=63254
LimitMSGQUEUE=819200
LimitMSGQUEUESoft=819200
LimitNICE=0
LimitNICESoft=0
LimitRTPRIO=0
LimitRTPRIOSoft=0
LimitRTTIME=infinity
LimitRTTIMESoft=infinity
OOMScoreAdjust=0
Nice=0
IOSchedulingClass=0
IOSchedulingPriority=0
CPUSchedulingPolicy=0
CPUSchedulingPriority=0
TimerSlackNSec=50000
CPUSchedulingResetOnFork=no
NonBlocking=no
StandardInput=null
StandardInputData=
StandardOutput=journal
StandardError=inherit
TTYReset=no
TTYVHangup=no
TTYVTDisallocate=no
SyslogPriority=30
SyslogLevelPrefix=yes
SyslogLevel=6
SyslogFacility=3
LogLevelMax=-1
LogRateLimitIntervalUSec=0
LogRateLimitBurst=0
SecureBits=0
CapabilityBoundingSet=cap_chown cap_dac_override cap_dac_read_search cap_fowner cap_fsetid cap_kill cap_setgid cap_setuid cap_setpcap cap_linux_immutable cap_net_bind_service cap_net_broadcast cap_net_admin cap_net_raw cap_ipc_lock cap_ipc_owner cap_sys_module cap_sys_rawio cap_sys_chroot cap_sys_ptrace cap_sys_pacct cap_sys_admin cap_sys_boot cap_sys_nice cap_sys_resource cap_sys_time cap_sys_tty_config cap_mknod cap_lease cap_audit_write cap_audit_control cap_setfcap cap_mac_override cap_mac_admin cap_syslog cap_wake_alarm cap_block_suspend
AmbientCapabilities=
DynamicUser=no
RemoveIPC=no
MountFlags=
PrivateTmp=no
PrivateDevices=no
ProtectKernelTunables=no
ProtectKernelModules=no
ProtectControlGroups=no
PrivateNetwork=no
PrivateUsers=no
PrivateMounts=no
ProtectHome=no
ProtectSystem=no
SameProcessGroup=no
UtmpMode=init
IgnoreSIGPIPE=yes
NoNewPrivileges=no
SystemCallErrorNumber=0
LockPersonality=no
RuntimeDirectoryPreserve=no
RuntimeDirectoryMode=0755
RuntimeDirectory=sshd
StateDirectoryMode=0755
CacheDirectoryMode=0755
LogsDirectoryMode=0755
ConfigurationDirectoryMode=0755
MemoryDenyWriteExecute=no
RestrictRealtime=no
RestrictNamespaces=no
MountAPIVFS=no
KeyringMode=private
KillMode=process
KillSignal=15
FinalKillSignal=9
SendSIGKILL=yes
SendSIGHUP=no
WatchdogSignal=6
Id=ssh.service
Names=ssh.service
Requires=-.mount sysinit.target system.slice
Conflicts=shutdown.target
Before=shutdown.target
After=-.mount system.slice systemd-journald.socket network.target basic.target auditd.service sysinit.target
RequiresMountsFor=/run/sshd
Documentation=man:sshd(8) man:sshd_config(5)
Description=OpenBSD Secure Shell server
LoadState=loaded
ActiveState=failed
SubState=failed
FragmentPath=/lib/systemd/system/ssh.service
UnitFileState=disabled
UnitFilePreset=enabled
StateChangeTimestamp=Sat 2019-03-02 14:23:36 CET
StateChangeTimestampMonotonic=252092638270
InactiveExitTimestamp=Sat 2019-03-02 14:23:35 CET
InactiveExitTimestampMonotonic=252092401156
ActiveEnterTimestampMonotonic=0
ActiveExitTimestampMonotonic=0
InactiveEnterTimestamp=Sat 2019-03-02 14:23:36 CET
InactiveEnterTimestampMonotonic=252092637629
CanStart=yes
CanStop=yes
CanReload=yes
CanIsolate=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
JobTimeoutUSec=infinity
JobRunningTimeoutUSec=infinity
JobTimeoutAction=none
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Sat 2019-03-02 14:23:36 CET
ConditionTimestampMonotonic=252092637839
AssertTimestamp=Sat 2019-03-02 14:23:36 CET
AssertTimestampMonotonic=252092637858
Transient=no
Perpetual=no
StartLimitIntervalUSec=10s
StartLimitBurst=5
StartLimitAction=none
FailureAction=none
FailureActionExitStatus=-1
SuccessAction=none
SuccessActionExitStatus=-1
InvocationID=879e00a14040443586f5f4b93d266c67
CollectMode=inactive
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #11869.

### CODE REVIEW

File: src/systemctl/systemctl.c [hunk 1]
```diff
@@ -4769,6 +4769,68 @@ static int print_property(const char *name, const char *expected_value, sd_bus_m
                         }
 
                         return 1;
+
+                } else if (endswith(name, "ExitStatus") && streq(contents, "aiai")) {
+                        const int *status, *signal;
```
Comment (poettering) [inline src/systemctl/systemctl.c]: dbus type "i" means int32_t, not "int". While on all archs we care about these types are the same, let's be accurate here...

File: src/systemctl/systemctl.c [hunk 2]
```diff
@@ -4769,6 +4769,68 @@ static int print_property(const char *name, const char *expected_value, sd_bus_m
...
+                        r = sd_bus_message_read_array(m, 'i', (const void **) &signal, &sz_signal);
+                        if (r < 0)
+                                return bus_log_parse_error(r);
+
+                        r = sd_bus_message_exit_container(m);
+                        if (r < 0)
+                                return bus_log_parse_error(r);
+
+                        sz_status /= sizeof(int);
+                        sz_signal /= sizeof(int);
```
Comment (poettering) [inline src/systemctl/systemctl.c]: /= sizeof(int32_t) ...

File: src/core/dbus-service.c [hunk 3]
```diff
@@ -171,6 +171,9 @@ static int bus_set_transient_exit_status(
         if (r < 0)
                 return r;
 
+        sz_status /= sizeof(int);
+        sz_signal /= sizeof(int);
```
Comment (poettering) [inline src/core/dbus-service.c]: needs to be int32_t (the current version of this function is borked, see earlier comment)

File: src/basic/in-addr-util.c [hunk 4]
```diff
@@ -241,6 +242,40 @@ int in_addr_to_string(int family, const union in_addr_union *u, char **ret) {
...
+        char *p;
+        size_t l;
+
+        assert(u);
+        assert(ret);
+
+        if (family == AF_INET)
+                l = INET_ADDRSTRLEN + 3;
+        else if (family == AF_INET6)
+                l = INET6_ADDRSTRLEN + 4;
```
Comment (poettering) [inline src/basic/in-addr-util.c:334]: should be `+ 5`, no? i.e. the longest suffix we attach is `/128\0` and that's 5 chars, because of the trailing NUL

File: src/basic/in-addr-util.c [hunk 5]
```diff
@@ -241,6 +242,40 @@ int in_addr_to_string(int family, const union in_addr_union *u, char **ret) {
...
+int in_addr_prefix_to_string(int family, const union in_addr_union *u, unsigned prefixlen, char **ret) {
+        _cleanup_free_ char *x = NULL;
+        char *p;
+        size_t l;
+
+        assert(u);
+        assert(ret);
+
+        if (family == AF_INET)
+                l = INET_ADDRSTRLEN + 3;
```
Comment (poettering) [inline src/basic/in-addr-util.c:332]: +4, trailing NUL needs to be included, no?

File: src/basic/in-addr-util.c [hunk 6]
```diff
@@ -241,6 +242,40 @@ int in_addr_to_string(int family, const union in_addr_union *u, char **ret) {
...
+        if (!inet_ntop(family, u, x, l))
+                return errno > 0 ? -errno : -EINVAL;
+
+        p = x + strlen(x);
+        l -= strlen(x);
+        (void) strpcpyf(&p, l, "/%u", prefixlen);
+
+        *ret = TAKE_PTR(x);
+        return 0;
+}
```
Comment (poettering) [inline src/basic/in-addr-util.c:355]: maybe add test case for this, that also makes sure we can parse this again?

**Comment by poettering** [comment]
Also needs a rebase

File: src/basic/in-addr-util.c (hunk 5 above)
Comment (yuwata) [reply src/basic/in-addr-util.c:332]: `INET_ADDRSTRLEN` is 16, thus it already includes trailing NUL. So, +3 is fine.

**Comment by yuwata** [comment]
@poettering Thank you for the review. I've force-pushed an updated version.
- Several tests for in_addr_prefix_to_string() are added.
- `int` -> `int32_t`, but only for `xxxExitStatus`.

**Comment by yuwata** [comment]
Re-rebased, then drop the commit for `SELinuxContext=` or friends.

File: src/core/dbus-service.c [hunk 7]
```diff
@@ -55,7 +55,7 @@ static int property_get_exit_status_set(
                 return r;
 
         SET_FOREACH(id, status_set->status, i) {
-                int val = PTR_TO_INT(id);
+                int32_t val = PTR_TO_INT32(id);
```
Comment (poettering) [inline src/core/dbus-service.c]: hmm, the `status_set->status` `Set` object actually *does* contain `int` values, hence this should be:

```c
int32_t val = PTR_TO_INT(id);
``` 

i think, as we first need to extract and convert the int value from the Set, and then convert it here to in32_t so that we can use it for dbus marshalling.

File: src/core/dbus-service.c [hunk 8]
```diff
@@ -74,10 +74,10 @@ static int property_get_exit_status_set(
                 return r;
 
         SET_FOREACH(id, status_set->signal, i) {
-                int val = PTR_TO_INT(id);
+                int32_t val = PTR_TO_INT32(id);
```
Comment (poettering) [inline src/core/dbus-service.c]: as above

File: src/core/dbus-service.c [hunk 9]
```diff
@@ -179,34 +182,34 @@ static int bus_set_transient_exit_status(
...
-                        return sd_bus_error_setf(error, SD_BUS_ERROR_INVALID_ARGS, "Invalid status code in %s: %i", name, status[i]);
+                        return sd_bus_error_setf(error, SD_BUS_ERROR_INVALID_ARGS, "Invalid status code in %s: %"PRIi32, name, status[i]);
 
                 if (!UNIT_WRITE_FLAGS_NOOP(flags)) {
                         r = set_ensure_allocated(&status_set->status, NULL);
                         if (r < 0)
                                 return r;
 
-                        r = set_put(status_set->status, INT_TO_PTR(status[i]));
+                        r = set_put(status_set->status, INT32_TO_PTR(status[i]));
```
Comment (poettering) [inline src/core/dbus-service.c]: INT_TO_PTR) was right here, since the `Set` object should contains ints...

File: src/core/dbus-service.c [hunk 10]
```diff
@@ -179,34 +182,34 @@ static int bus_set_transient_exit_status(
...
-                        return sd_bus_error_setf(error, SD_BUS_ERROR_INVALID_ARGS, "Invalid signal in %s: %i", name, signal[i]);
+                        return sd_bus_error_setf(error, SD_BUS_ERROR_INVALID_ARGS, "Invalid signal in %s: %"PRIi32, name, signal[i]);
 
                 if (!UNIT_WRITE_FLAGS_NOOP(flags)) {
                         r = set_ensure_allocated(&status_set->signal, NULL);
                         if (r < 0)
                                 return r;
 
-                        r = set_put(status_set->signal, INT_TO_PTR(signal[i]));
+                        r = set_put(status_set->signal, INT32_TO_PTR(signal[i]));
```
Comment (poettering) [inline src/core/dbus-service.c]: as above

File: src/core/dbus-service.c (hunk 7 above)
Comment (yuwata) [reply src/core/dbus-service.c]: Indeed. I was so foolish...

**Comment by yuwata** [comment]
Updated. PTAL.
