### PR TITLE
Fixes several recent CI issues

### LINKED ISSUE #36678: TEST-70-TPM2 failed when running with sanitizers
For example:
https://github.com/systemd/systemd/actions/runs/13753149354/job/38456642329?pr=36622
```
[  168.032694] TEST-70-TPM2.sh[3053]: ++ systemd-dissect --attach /tmp/dditest.raw
[  168.094395] TEST-70-TPM2.sh[2662]: + DEVICE=/dev/loop0
[  168.094735] TEST-70-TPM2.sh[2662]: + udevadm wait --settle --timeout=10 /dev/loop0p1
[  178.289772] TEST-70-TPM2.sh[2662]: + at_exit
[  178.290178] TEST-70-TPM2.sh[2662]: + [[ -n 0x81000000 ]]
[  178.292279] TEST-70-TPM2.sh[2662]: + tpm2_evictcontrol -c 0x81000000
[  178.371417] TEST-70-TPM2.sh[3058]: persistent-handle: 0x81000000
[  178.371860] TEST-70-TPM2.sh[3058]: action: evicted
[  178.387383] TEST-70-TPM2.sh[698]: + echo 'Subtest /usr/lib/systemd/tests/testdata/units/TEST-70-TPM2.cryptsetup.sh failed'
[  178.387677] TEST-70-TPM2.sh[698]: Subtest /usr/lib/systemd/tests/testdata/units/TEST-70-TPM2.cryptsetup.sh failed
[  178.388139] TEST-70-TPM2.sh[698]: + return 1
[FAILED] Failed to start TEST-70-TPM2.service - TEST-70-TPM2.
```
```
No coredumps found.
[  168.064578] systemd-udevd[2889]: ==2889==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7fff8cd3f960 at pc 0x564b3288022b bp 0x7fff8cd3f5b0 sp 0x7fff8cd3f5a8
[  168.064578] systemd-udevd[2889]: READ of size 8 at 0x7fff8cd3f960 thread T0 ((udev-worker))
Found 1 sanitizer issues (0 internal, 0 asan, 0 ubsan, 0 msan).
```
Unfortunately, the sanitizer does not provide enough information.

@evverx Do you have any idea how we can get more information?

### LINKED ISSUE #36679: TEST-74-AUX-UTILS: disconnecttest failed
https://github.com/systemd/systemd/actions/runs/13753149354/job/38456642537?pr=36622
```
TEST-74-AUX-UTILS.sh[1418]: + assert_rc 37 systemd-run --unit=disconnecttest --wait --pipe --user -M testuser@.host bash -ec 'systemctl --user daemon-reexec; sleep 3; exit 37'
TEST-74-AUX-UTILS.sh[1791]: + set +ex
Trying to halt container. Send SIGTERM again to trigger immediate termination.
Finishing after writing 83733 entries
]3008;end=868aff8560824dbfa5633b9109dd294c\]3008;end=0ea012664abd42a3812c39c99f468edb\Trying to halt container. Send SIGTERM again to trigger immediate termination.
Sending SIGTERM to remaining processes...
Sending SIGKILL to remaining processes...
All filesystems, swaps, loop devices, MD devices and DM devices detached.
Halting system.
```
Unfortunately, no journal is saved.

### PR DESCRIPTION
**Pull request by yuwata**
- Fixes a race in systemd-run caused by b7ba8d55b8e413ff326abc4814b92d42b8d3c3c3, which causes issue #36679.
- Skip verifying masked units in TEST-23.
- Avoid false-positive ASan warning by switching sanitizer run from Fedora rawhide to Fedora 41, caused by recent update from llvm-19.1.7-11.fc43 to llvm-20.1.0-1.fc43. Hopefully issue #36678 should be fixed.

Closes #36678.
Closes #36679.

### CODE REVIEW

File: src/run/run.c [hunk 1]
```diff
@@ -1810,6 +1810,7 @@ static void run_context_detach_bus(RunContext *c) {
         c->match_properties_changed = sd_bus_slot_unref(c->match_properties_changed);
         c->match_disconnected = sd_bus_slot_unref(c->match_disconnected);
         c->match_job_removed = sd_bus_slot_unref(c->match_job_removed);
+        c->start_job = mfree(c->start_job);
```
Comment (YHNdnzj) [inline src/run/run.c]: hmm, is this really the right approach? It means we'd potentially never set up pty forwarder and such if we miss JobRemoved signal.

My thinking now is to maybe turn this around: store the start job id and unit's current job id in RunContext, and move the main logic of match_job_removed into run_context_check_started(). And then call that for each run_context_update() invocation. I.e.:

```c
static void run_context_check_started(RunContext *c) {
        if (c->start_job == 0 || c->unit_job == c->start_job) /* job start has been processed or it's still running */
                return;

        /* job just completed */

        sd_notify(...);
        run_context_setup_ptyfwd(...);

        c->start_job = 0;
}

static int run_context_update(RunContext *c) {

        static const struct bus_properties_map = {
                ...,
                { "Job", "(uo)", bus_map_job_id, offsetof(RunContext, unit_job) },
        };

        bus_map_all_properties(...);

        run_context_check_started(c);
        run_context_check_done(c);
}
```

With this we can rely purely on PropertiesChanged signal match + run_context_update() to catch job completion, which handles disconnection properly.

Comment (YHNdnzj) [reply src/run/run.c]: Plus a nice side effect I just noticed: for a oneshot service, no matter whether we get JobRemoved or PropertiesChanged + active_state -> inactive first, the sd_notify(...) is properly sent.

Oh, another thing I realized while writing this: we should probably refuse --pty-late with oneshot services. They're simply useless...

Comment (yuwata) [reply src/run/run.c]: Thank you for the suggestion.

> Oh, another thing I realized while writing this: we should probably refuse --pty-late with oneshot services. They're simply useless...

This is not addressed at least in this PR.
Even if it is useless, it 'works' without any issue, IIUC, no?
I am not sure we should refuse such combination.

File: src/run/run.c [hunk 2]
```diff
@@ -2056,18 +2095,9 @@ static int match_job_removed(sd_bus_message *m, void *userdata, sd_bus_error *er
...
                 return 0;
 
-        /* Notify our caller that the service is now running, just in case. */
-        (void) sd_notifyf(/* unset_environment= */ false,
-                          "READY=1\n"
-                          "RUN_UNIT=%s",
-                          c->unit);
-
-        r = run_context_setup_ptyfwd(c);
+        r = run_context_check_started(c, /* current_job = */ NULL);
```
Comment (YHNdnzj) [inline src/run/run.c]: (I think the match for JobRemoved can be removed wholesale. Now that active_state is checked in _started() we might be looking at outdated data here)

File: src/run/run.c [hunk 3]
```diff
@@ -1660,12 +1662,44 @@ static int run_context_reconnect(RunContext *c) {
...
+                return 0; /* The start job is still active. */
+
+        /* The start job is finished. */
+        c->start_job = mfree(c->start_job);
+        c->match_job_removed = sd_bus_slot_unref(c->match_job_removed);
+
+        /* Setup ptyfwd now if --pty-late is specified. */
+        r = run_context_setup_ptyfwd(c);
+        if (r < 0)
+                return sd_event_exit(c->event, r);
```
Comment (YHNdnzj) [inline src/run/run.c]: Not your fault, but we probably should not use r as exit status. Exit with EXIT_FAILURE and propagate r?
