### PR TITLE
sd-bus: allow receiving messages with MSG_CTRUNC set

### LINKED ISSUE #34688: if selinux denies an fd delivered via SCM_RIGHTS/AF_UNIX the fd will be dropped, we get MSG_CTRUNC
While debugging a different issue (hence all the `disown` shenanigans below) I hit a strange behavior where some systemd operations start timing out when PID 1 hits an AVC. I can't currently even say what's the actual issue, hopefully demonstration will give some insight into it:

```
## This is from latest Fedora Rawhide
# rpm -q systemd
systemd-256.5-1.fc42.x86_64
# ausearch -m avc
<no matches>

# (systemd-run --user --machine=adm@ --wait true) & disown
[1] 937
Running as unit: run-u0.service; invocation ID: 2deba724222749549bc1a336301a91d5
Finished with result: success
Main processes terminated with: code=exited, status=0/SUCCESS
Service runtime: 9ms
CPU time consumed: 3ms
Memory peak: 1M (swap: 0B)
# ausearch -m avc
<no matches>
```

So far so good. But if I redirect the output of the subshell into a file under `/tmp`, this triggers an AVC and things start getting wonky:
```
# (systemd-run --user --machine=adm@ --wait true) &>/tmp/out.log & disown
[1] 972
# cat /tmp/out.log 
Failed to start transient service unit: Remote peer disconnected
Failed to start transient service unit: Transport endpoint is not connected
# ausearch -m avc
----
time->Wed Oct  9 08:30:27 2024
type=AVC msg=audit(1728477027.046:202): avc:  denied  { write } for  pid=1 comm="systemd" path="/tmp/out.log" dev="tmpfs" ino=21 scontext=system_u:system_r:init_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file permissive=0
# journactl -o short-monotonic --no-hostname -e
...
[  831.769504] systemd[1]: Processing of bus failed, closing down: Exchange full
[  831.769690] systemd[1]: Bus bus-api-system: changing state RUNNING → CLOSING
[  831.769714] systemd[1]: Bus bus-api-system: changing state CLOSING → CLOSED
```

Now even the original command (without redirect) stops working:
```
# (systemd-run --user --machine=adm@ --wait true) & disown
[1] 978
Failed to start transient service unit: Transport endpoint is not connected
```

But other (and more _common_) `systemd-run` invocations suffer the same fate as well:
```
# systemd-run --wait --pipe echo hello
Failed to start transient service unit: Connection timed out
```

This issue seems to persist for a while until there's some other activity (like service start in cron, manual `systemctl start`, etc.).

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
In the event that we can't receive all of the fds from the message
(which can happen for a number of reasons including LSM denials or
hitting the fd limit of the process) the kernel will set the MSG_CTRUNC
flag.  Through our use of recvmsg_safe() we've been treating this as a
fatal error, which will result in dropping the connection.

Let's dial that back a bit: we can receive the message, but when the
user attempts to access the missing fds via sd_bus_message_read_basic()
we can return the (existing) error code of -EBADMSG to indicate that the
fd is missing.

We can do this by using recvmsg() directly, and relaxing some of the
checks on message creation: when (and only when) we have received
MSG_CTRUNC we allow a smaller than expected (per the header) number of
fds to be present.  The error check in sd_bus_message_read_basic() was
already there so we don't need to do anything about that.

This puts the receiver of the message into a difficult situation: you
can call sd_bus_message_read_basic() as often as you want but as long as
it keeps returning -EBADMSG it won't progress through the message and
you won't be able to close whatever container you're in.  That means
that the user will probably need to abandon processing the message
anyway.  So why not just drop the message up front?  This approach is
more likely to yield a useful error message, which will be invaluable
for people trying to track down problems caused by LSM denials.

Fixes #34688

### CODE REVIEW

File: src/libsystemd/sd-bus/bus-internal.h [hunk 1]
```diff
@@ -256,6 +256,7 @@ typedef struct sd_bus {
 
         int *fds;
         size_t n_fds;
+        bool fds_might_be_truncated; /* MSG_CTRUNC was seen during recvmsg() */
```
Comment (noxiouz) [inline src/libsystemd/sd-bus/bus-internal.h]: this comment is not fully true
For example, bus_socket_read_auth does not set that to true (because we do not expect fds to be sent/received, but still)

**Comment by allisonkarlitskaya** [comment]
@keszybz maybe you can help me with developing a proper integration test for Fedora/selinux here which tests an LSM denial on an fd send?  Or is there another mechanism we can use to fake this?

File: src/libsystemd/sd-bus/bus-internal.h (hunk 1 above)
Comment (keszybz) [reply src/libsystemd/sd-bus/bus-internal.h]: Having this as a "global" on the bus object seems bad. Is it possible to move this to the individual message?

File: src/libsystemd/sd-bus/bus-socket.c [hunk 2]
```diff
@@ -590,6 +590,15 @@ static int bus_process_cmsg(sd_bus *bus, struct msghdr *mh, bool allow_fds) {
                 return 0;
         }
 
+        if (n_fds > 0 && bus->fds_might_be_truncated)
+                /* We previously received fds with MSG_CTRUNC set, indicating the fd array was truncated
+                 * (e.g., by an LSM blocking some fds). When the kernel truncates the fd array, it drops
+                 * all fds from the blocked one onwards - we have no way to know how many were lost or
+                 * which indexes are affected. Any fds we receive now would be appended at the wrong
+                 * indexes, corrupting the message's fd table. We must silently drop them to avoid a
+                 * worse mess. The message will still fail later if it tries to access a truncated fd. */
```
Comment (keszybz) [inline src/libsystemd/sd-bus/bus-socket.c]: "The message will fail": this sentence is strange. The message is a passive object.

Also, based on earlier discussion, I think "we have no way to know how many were lost or which indexes are affected" is not true. Since the kernel drops all fds after the failed one, we could keep track of that and match them to indices…

File: src/libsystemd/sd-bus/fuzz-bus-message.c [hunk 3]
```diff
@@ -23,7 +23,7 @@ int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
 
         assert_se(buffer = memdup(data, size));
 
-        r = bus_message_from_malloc(bus, buffer, size, NULL, 0, NULL, &m);
+        r = bus_message_from_malloc(bus, buffer, size, NULL, 0, /* fds_might_be_truncated = */ false, NULL, &m);
```
Comment (keszybz) [inline src/libsystemd/sd-bus/fuzz-bus-message.c]: This needs to be exactly `/* fds_might_be_truncated= */` or Yu will be very unhappy.

File: src/libsystemd/sd-bus/test-bus-marshal.c [hunk 4]
```diff
@@ -243,7 +243,7 @@ int main(int argc, char *argv[]) {
 
         m = sd_bus_message_unref(m);
 
-        r = bus_message_from_malloc(bus, buffer, sz, NULL, 0, NULL, &m);
+        r = bus_message_from_malloc(bus, buffer, sz, NULL, 0, /* fds_might_be_truncated = */ false, NULL, &m);
```
Comment (keszybz) [inline src/libsystemd/sd-bus/test-bus-marshal.c]: Ditto.

File: src/libsystemd/sd-bus/bus-message.c [hunk 5]
```diff
@@ -4197,8 +4198,20 @@ static int message_parse_fields(sd_bus_message *m) {
...
+         * may have truncated the fd array (e.g., due to LSM denials blocking fd passing). In that case, we
+         * accept fewer fds than declared. Any attempt to actually use a truncated fd will fail later when
+         * sd_bus_message_read_basic() finds the fd index out of range. */
+        if (fds_might_be_truncated) {
+                if (m->n_fds > n_unix_fds_declared)
+                        return -EBADMSG;
+        } else {
+                if (m->n_fds != n_unix_fds_declared)
+                        return -EBADMSG;
+        }
```
Comment (keszybz) [inline src/libsystemd/sd-bus/bus-message.c]: Does this need to be so verbose?
Maybe
```C
if (m->n_fds > n_unix_fds_declared || (m->n_fds < n_unix_fds_declared && !fds_might_be_truncated))
     return -EBADMSG;
```
or
```C
if (fds_might_be_truncated ? m->n_fds > n_unix_fds_declared : m->n_fds != n_unix_fds_declared)
     return -EBADMSG;
```

File: src/libsystemd/sd-bus/bus-internal.h (hunk 1 above)
Comment (keszybz) [reply src/libsystemd/sd-bus/bus-internal.h]: `bus_socket_read_auth` **does** set it to true, at least in the second version of the patch.

Comment (keszybz) [reply src/libsystemd/sd-bus/bus-internal.h]: Hmm, maybe move this along with the other `bool`s above? It is kind of nice to have them all together.

File: src/libsystemd/sd-bus/test-bus-marshal.c [hunk 6]
```diff
@@ -99,6 +103,140 @@ static void test_bus_label_escape_one(const char *a, const char *b) {
...
+        assert_se(fds);
+        fds[0] = fcntl(memfd0, F_DUPFD_CLOEXEC, 3);
+        fds[1] = fcntl(memfd1, F_DUPFD_CLOEXEC, 3);
+        assert_se(fds[0] >= 0 && fds[1] >= 0);
+
+        /* Test 1: Parse with correct fd count, no truncation - should succeed */
+        log_info("Test 1: Exact fd count match, fds_might_be_truncated=false");
+        void *blob_copy = memdup(blob, blob_size);
+        assert_se(blob_copy);
+        r = bus_message_from_malloc(bus, blob_copy, blob_size, fds, 2, /* fds_might_be_truncated = */ false, NULL, &m);
```
Comment (keszybz) [inline src/libsystemd/sd-bus/test-bus-marshal.c]: Also here, the space before `=` is not wanted.

File: src/libsystemd/sd-bus/test-bus-chat.c [hunk 7]
```diff
@@ -493,6 +497,147 @@ static void* client2(void *p) {
...
+TEST(ctrunc) {
+        _cleanup_(sd_bus_flush_close_unrefp) sd_bus *bus = NULL;
+        _cleanup_(sd_bus_message_unrefp) sd_bus_message *recvd = NULL, *sent = NULL, *junk = NULL;
+        struct rlimit orig_rl, new_rl;
+        const char *unique;
+        const int n_fds_to_send = 64;
+        ino_t memfd_st_ino[n_fds_to_send];
+        int r;
+
+        log_info("Testing MSG_CTRUNC handling via session bus...");
```
Comment (keszybz) [inline src/libsystemd/sd-bus/test-bus-chat.c]: TEST() already logs, so please drop this and the "MSG_CTRUNC test passed" message at the bottom.

File: src/libsystemd/sd-bus/test-bus-chat.c [hunk 8]
```diff
@@ -493,6 +497,147 @@ static void* client2(void *p) {
...
+                int fd; /* weakly owned: the fd belongs to the message */
+                r = sd_bus_message_read_basic(recvd, 'h', &fd);
+                if (r != -EBADMSG)
+                        return (void) log_error_errno(r, "Failed to (not) read fd from message");
+        }
+        r = sd_bus_message_exit_container(recvd);
+        if (r != -EBUSY)
+                return (void) log_error_errno(r, "Failed to fail to exit array");
+
+        log_info("MSG_CTRUNC test passed");
```
Comment (keszybz) [inline src/libsystemd/sd-bus/test-bus-chat.c:619]: I think we should check that the next message can be received… Without that, the test feels incomplete. Something like this seems to pass here:
```C
        /* Send the message again */
        ASSERT_OK(sd_bus_send(bus, sent, NULL));
        ASSERT_OK(get_one_message(bus, &r2));
        ASSERT_TRUE(sd_bus_message_is_method_call(r2, "org.freedesktop.systemd.test", "SendFds"));
 
        /* Read all the fds. */
        ASSERT_EQ(sd_bus_message_enter_container(r2, SD_BUS_TYPE_ARRAY, "h"), 1);
        for (i = 0; i < n_fds_to_send; i++) {
                int fd; /* weakly owned: the fd belongs to the message */
                ASSERT_OK(sd_bus_message_read_basic(r2, 'h', &fd));
                ASSERT_EQ(get_inode(fd), memfd_st_ino[i]);
        }
        ASSERT_OK(sd_bus_message_exit_container(r2));
```

File: src/libsystemd/sd-bus/test-bus-chat.c [hunk 9]
```diff
@@ -493,6 +497,147 @@ static void* client2(void *p) {
...
+
+        /* At this point we're stuck.  We can call sd_bus_message_read_basic() as often as we want, but we
+         * won't be able to make progress and won't be able to close the array or read anything else in the
+         * message.
+         */
+        for (i = 0; i < 2 * n_fds_to_send; i++) {
+                int fd; /* weakly owned: the fd belongs to the message */
+                r = sd_bus_message_read_basic(recvd, 'h', &fd);
+                if (r != -EBADMSG)
+                        return (void) log_error_errno(r, "Failed to (not) read fd from message");
```
Comment (keszybz) [inline src/libsystemd/sd-bus/test-bus-chat.c]: This needs to be an assert for the test to test. Some errors in the first part can cause the test to be skipped, those can be handled like this. But most of the checks need to use ASSERT. Probably everything starting at `sd_bus_message_new_method_call`.

File: src/libsystemd/sd-bus/test-bus-chat.c [hunk 10]
```diff
@@ -493,6 +497,147 @@ static void* client2(void *p) {
...
+
+        /* Make sure at least one fd failed */
+        ASSERT_LT(i, n_fds_to_send);
+        log_info("fds truncated at %i", i);
+
+        /* At this point we're stuck.  We can call sd_bus_message_read_basic() as often as we want, but we
+         * won't be able to make progress and won't be able to close the array or read anything else in the
+         * message.
+         */
+        for (i = 0; i < 2 * n_fds_to_send; i++) {
```
Comment (keszybz) [inline src/libsystemd/sd-bus/test-bus-chat.c:598]: Just `i < n_fds_to_send`, no?

File: src/libsystemd/sd-bus/test-bus-chat.c [hunk 11]
```diff
@@ -493,6 +497,147 @@ static void* client2(void *p) {
...
+                int fd; /* weakly owned: the fd belongs to the message */
+                r = sd_bus_message_read_basic(recvd, 'h', &fd);
+                if (r == -EBADMSG)
+                        /* Good!  We were expecting this! */
+                        break;
+                if (r < 0)
+                        return (void) log_error_errno(r, "Failed to read fd from message");
+                /* Make sure it stayed in the same order as we sent it */
+                ASSERT_EQ(get_inode(fd), memfd_st_ino[i]);
+        }
```
Comment (keszybz) [inline src/libsystemd/sd-bus/test-bus-chat.c:587]: I think this is trying to do too much. If we hit truncation, all fds are discarded, so we always get 0 fds, IIUC. So this could be simplified to drop the logic for partial success.

**Review by keszybz — CHANGES_REQUESTED** [review]
I think this approach is reasonable, but some details need tweaking.

**Comment by keszybz** [comment]
> @keszybz maybe you can help me with developing a proper integration test for Fedora/selinux here which tests an LSM denial on an fd send? Or is there another mechanism we can use to fake this?

I think the two tests added in the second patch are enough. The generic mechanism is fairly simple. If you can test that the patch work in the initial reproducer with SELinux, that is good enough. To test this in CI we'd need to build something very fragile and nobody wants to maintain such fragile tests.

File: src/libsystemd/sd-bus/bus-socket.c [hunk 12]
```diff
@@ -646,13 +655,15 @@ static int bus_socket_read_auth(sd_bus *b) {
                         .msg_controllen = sizeof(control),
                 };
 
-                k = recvmsg_safe(b->input_fd, &mh, MSG_DONTWAIT|MSG_CMSG_CLOEXEC);
-                if (k == -ENOTSOCK) {
+                k = recvmsg(b->input_fd, &mh, MSG_DONTWAIT|MSG_CMSG_CLOEXEC);
```
Comment (poettering) [inline src/libsystemd/sd-bus/bus-socket.c]: maybe use RET_NERRNO() macro

File: src/libsystemd/sd-bus/bus-internal.h (hunk 1 above)
Comment (poettering) [inline src/libsystemd/sd-bus/bus-internal.h]: i wuld really prefer if this would just be called got_ctrunc or so, i.e. say what actually happened.

**Comment by poettering** [comment]
hmm, what MSG_CTRUNC doesn't really tell us *what* precisely got truncated: could be the fd array, or could be some other aux data. it's too generic a flag for us to know exactly what happened. This sucks, but of course cannot be changed without kernel fixes. But I think we should try to make the best of the shitty situation, and hence:

1. if we see MSG_CTRUNC but have the right number of fds, then something else got truncated. if that happened we should consider the msg corrupted, as before. please add such a check
2. we should discuss the vagueness of MSG_CTRUNC in a comment a bit, briefly. i.e. saying we are doing guesswork here.
3. i'd really prefer if sd_bus_message_read_basic() would return some recognizable error if an fd went missing, rather than the very generic EBADMSG. Maybe just return EBADSLT?

**Comment by allisonkarlitskaya** [comment]
> i'd really prefer if sd_bus_message_read_basic() would return some recognizable error if an fd went missing, rather than the very generic EBADMSG. Maybe just return EBADSLT?

Do we want, in that case, to allow the message to continue to be processed? (ie: does the iterator advance)

**Comment by poettering** [comment]
> Do we want, in that case, to allow the message to continue to be processed? (ie: does the iterator advance)

i don't see why we would want that. 

if you wanted to support that i think the right approach would be to return success but initialize the fd that is returned to -EBADF or so. But frankly, that would be a compat break, and I am really not sure what the usecase for that headache is. I think it's totally fine that incomplete messages parse incompletely.

i mean, what's the goal you are having with this? do you *actually* want to process dbus messages that are incomplete? or isn't the behaviour you are looking for just that broken messages shouldn't result in broken connections? i find the usecase for the former very weak, and for the latter I am not enthusiastic but i can see why you want that, so we can make this work...

**Comment by allisonkarlitskaya** [comment]
> i mean, what's the goal you are having with this? do you actually want to process dbus messages that are incomplete? or isn't the behaviour you are looking for just that broken messages shouldn't result in broken connections? i find the usecase for the former very weak, and for the latter I am not enthusiastic but i can see why you want that, so we can make this work...

So, broken messages should *never* result in broken connections is kinda the entire point of this PR.  So yes, definitely.

As for if we want to try to make the message readable to the end, it was meant as a straight-up question.  I think I actually agree with you that once we've discovered that the message has been damaged in transit, the only sensible thing to do is to discard it.  I have a hard time thinking about a usecase where anything else would make sense...

File: src/libsystemd/sd-bus/bus-message.c (hunk 5 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-message.c]: I actually plan to make it a bit more verbose in the next iteration of the patch.  I want this to be very very explicit.  I rewrote it from a `?:` operator as I was working on it...

File: src/libsystemd/sd-bus/bus-internal.h (hunk 1 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-internal.h]: Kinda disagree with that.  It's absolutely related to fds/n_fds.  I'd put all three of them together into a higher-level data type if it was reasonably possible...

File: src/libsystemd/sd-bus/test-bus-chat.c (hunk 8 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/test-bus-chat.c:619]: Thanks for the suggestion.  I agree: the entire point is that the connection continues to be usable after the failed message.

File: src/libsystemd/sd-bus/test-bus-chat.c (hunk 10 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/test-bus-chat.c:598]: I wanted to make sure that "no matter how hard you try..." is really hard :)

File: src/libsystemd/sd-bus/test-bus-chat.c (hunk 11 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/test-bus-chat.c:587]: Ya, that's what I observed during testing and it wasn't my original intent.  I think I messed up in the patch somewhere.  It's important to me that the first failing fd is the one that actually got truncated by the LSM so that we have a hope for better log messages.

On that note, I think I'm also going to add a warning if we see MSG_CTRUNC in the first place.

File: src/libsystemd/sd-bus/bus-internal.h (hunk 1 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-internal.h]: I went back and forth on the naming of this for a while and settled on this because, at least in testing, there's no "ctrunc" received at all.  Happy to change it though.

Comment (poettering) [reply src/libsystemd/sd-bus/bus-internal.h]: oh, i misunderstood then. are you saying if selinux eats up fds it will *not* set MSG_CTRUNC?

File: src/libsystemd/sd-bus/bus-socket.c (hunk 2 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-socket.c]: So this code is where we merge together additional received fds after we've already received the first batch.  I'm not even sure if this is possible in the first place (since I think all fds should be sent in a single cmsg with the first byte of data), but the code exists to do it...

So let's assume we're in a case where the fds got split across multiple recvmsg() calls for some reason (which is what the merging code is attempting to deal with).  We don't know what the split would have been.  It's true that (later, when we parse the header) we'll know the total number of fds, but let's say a message with 10 fds gets split up into being sent like (5, 2, 3).  And then let's say in the first one we have the second fd dropped (ie: so of the 5 we only receive 1).  How do we know that there was 5 fds in that first message?  If we were to start appending fds again after this we'd have to skip 4 spots (the number of fds that got dropped) but we have no way to know that 4 fds disappeared: only that some truncation occurred at some point...

I basically think once we get into the truncated state we need to keep truncating.  Also: it's pretty academic anyway since once we hit the truncated fd when trying to decode the message body we won't be able to proceed further anyway...

File: src/libsystemd/sd-bus/fuzz-bus-message.c (hunk 3 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/fuzz-bus-message.c]: Fixed.

File: src/libsystemd/sd-bus/test-bus-chat.c (hunk 11 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/test-bus-chat.c:587]: I found the issue: I originally intended to set the `got_ctrunc` flag on the bus struct *after* handling the fds in the first round, but it got set before, which means that all fds got truncated.  That's not at all what I wanted, so I fixed it so the first error we get when decoding a message ought to be specifically about the fd that got truncated.

File: src/libsystemd/sd-bus/bus-internal.h (hunk 1 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-internal.h]: With "in testing" I meant "from the test case".  If selinux eats fds MSG_CTRUNC is indeed always set.  I renamed it.

File: src/libsystemd/sd-bus/test-bus-chat.c (hunk 11 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/test-bus-chat.c:587]: I kept this and added a check that we receive at least one fd.

File: src/libsystemd/sd-bus/bus-socket.c (hunk 12 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-socket.c]: Thanks for the hint.

File: src/libsystemd/sd-bus/test-bus-chat.c (hunk 9 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/test-bus-chat.c]: I changed all of these...

**Comment by allisonkarlitskaya** [comment]
> EBADSLT

I didn't do this one.  It feels very weird and is probably going to result in some very confusing error messages.

I wonder if we could reuse ECHRNG here or something else more appropriate?  Honestly, if we consider that the LSM has "damaged" the message in-flight (which I think is a reasonable view) I think that BADMSG is the best error...

File: src/libsystemd/sd-bus/bus-message.c [hunk 13]
```diff
@@ -4197,8 +4198,29 @@ static int message_parse_fields(sd_bus_message *m) {
...
-        if (m->n_fds != unix_fds)
-                return -EBADMSG;
+        /* Validate that the number of fds we actually received via SCM_RIGHTS matches (or is compatible
+         * with) the number declared in the message header.
+         *
+         * Normally these must match exactly. However, when MSG_CTRUNC was set during recvmsg(), the kernel
+         * should have truncated the fd array (e.g., due to LSM denials blocking fd passing). In that case,
+         * we accept strictly fewer fds than declared. Any attempt to actually use a truncated fd will fail
+         * later when sd_bus_message_read_basic() finds the fd index out of range. */
+        if (got_ctrunc) {
```
Comment (bluca) [inline src/libsystemd/sd-bus/bus-message.c]: This is going to be extremely hard to debug, please try to add as much information as possible in the log messages below. Ideally with details of the bus interface/method/property involved.

File: src/libsystemd/sd-bus/bus-message.c [hunk 14]
```diff
@@ -4197,8 +4198,29 @@ static int message_parse_fields(sd_bus_message *m) {
...
+                /* MSG_CTRUNC?  We need to see strictly fewer fds than the header declares. */
+                if (m->n_fds >= n_unix_fds_declared) {
+                        log_error("Received a bus message with MSG_CTRUNC with %u fds received vs. %u declared", m->n_fds, n_unix_fds_declared);
+                        return -EBADMSG;
+                }
+
+                /* Log a message even in the "expected" case: it'll help people track down LSM weirdness */
+                log_warning("Received a bus message with truncated fds: %u received vs. %u sent", m->n_fds, n_unix_fds_declared);
```
Comment (bluca) [inline src/libsystemd/sd-bus/bus-message.c]: When this happens it's really bad, and things will break, so it really should be log_error too

Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-message.c]: The logic here is that in the "warning" case we still produce a message but in the "error" cases we shutdown the connection...

Of course I don't really care if the warnings are also a bit louder...

File: src/libsystemd/sd-bus/bus-message.c (hunk 13 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-message.c]: Ok.

File: src/libsystemd/sd-bus/bus-message.c (hunk 14 above)
Comment (bluca) [reply src/libsystemd/sd-bus/bus-message.c]: The message will likely be unusable - eg, any of the methods that require a PIDFD - so it should be really loud here too. This is ultimately a situation where the system set up is broken and needs to be fixed, so the loudest, the better

File: src/libsystemd/sd-bus/bus-message.c [hunk 15]
```diff
@@ -4197,8 +4198,29 @@ static int message_parse_fields(sd_bus_message *m) {
...
+         *
+         * Normally these must match exactly. However, when MSG_CTRUNC was set during recvmsg(), the kernel
+         * should have truncated the fd array (e.g., due to LSM denials blocking fd passing). In that case,
+         * we accept strictly fewer fds than declared. Any attempt to actually use a truncated fd will fail
+         * later when sd_bus_message_read_basic() finds the fd index out of range. */
+        if (got_ctrunc) {
+                /* MSG_CTRUNC?  We need to see strictly fewer fds than the header declares. */
+                if (m->n_fds >= n_unix_fds_declared) {
+                        log_error("Received a bus message with MSG_CTRUNC with %u fds received vs. %u declared", m->n_fds, n_unix_fds_declared);
+                        return -EBADMSG;
```
Comment (keszybz) [inline src/libsystemd/sd-bus/bus-message.c]: `return log_error_errno(SYNTHETHIC_ERRNO(EBADMSG), "…");`, drop `{}`.

File: src/libsystemd/sd-bus/bus-message.c [hunk 16]
```diff
@@ -4197,8 +4198,29 @@ static int message_parse_fields(sd_bus_message *m) {
...
+                }
+
+                /* Log a message even in the "expected" case: it'll help people track down LSM weirdness */
+                log_warning("Received a bus message with truncated fds: %u received vs. %u sent", m->n_fds, n_unix_fds_declared);
+        } else {
+                /* No CTRUNC?  Needs to be an exact match. */
+                if (m->n_fds != n_unix_fds_declared) {
+                        log_error("Received a bus message without MSG_CTRUNC with %u fds received vs %u declared", m->n_fds, n_unix_fds_declared);
+                        return -EBADMSG;
```
Comment (keszybz) [inline src/libsystemd/sd-bus/bus-message.c]: Also here, SYNTHETIC_ERRNO please.

File: src/libsystemd/sd-bus/bus-socket.c [hunk 17]
```diff
@@ -646,13 +657,15 @@ static int bus_socket_read_auth(sd_bus *b) {
                         .msg_controllen = sizeof(control),
                 };
 
-                k = recvmsg_safe(b->input_fd, &mh, MSG_DONTWAIT|MSG_CMSG_CLOEXEC);
-                if (k == -ENOTSOCK) {
+                k = RET_NERRNO(recvmsg(b->input_fd, &mh, MSG_DONTWAIT|MSG_CMSG_CLOEXEC));
+                if (errno == -ENOTSOCK) {
```
Comment (keszybz) [inline src/libsystemd/sd-bus/bus-socket.c]: No! With RET_NERRNO, `k` contains the negative error value on error. `errno` itself is never negative.

File: src/libsystemd/sd-bus/bus-socket.c [hunk 18]
```diff
@@ -646,13 +657,15 @@ static int bus_socket_read_auth(sd_bus *b) {
...
                         b->prefer_readv = true;
                         k = readv(b->input_fd, &iov, 1);
                         if (k < 0)
                                 k = -errno;
-                } else
+                } else if (k < 0)
+                        k = -errno;
```
Comment (keszybz) [inline src/libsystemd/sd-bus/bus-socket.c]: This part is not needed.

File: src/libsystemd/sd-bus/bus-socket.c [hunk 19]
```diff
@@ -1418,13 +1433,15 @@ int bus_socket_read_message(sd_bus *bus) {
...
-                k = recvmsg_safe(bus->input_fd, &mh, MSG_DONTWAIT|MSG_CMSG_CLOEXEC);
+                k = RET_NERRNO(recvmsg(bus->input_fd, &mh, MSG_DONTWAIT|MSG_CMSG_CLOEXEC));
                 if (k == -ENOTSOCK) {
                         bus->prefer_readv = true;
                         k = readv(bus->input_fd, &iov, 1);
                         if (k < 0)
                                 k = -errno;
-                } else
+                } else if (k < 0)
+                        k = -errno;
```
Comment (keszybz) [inline src/libsystemd/sd-bus/bus-socket.c]: Ditto.

File: src/libsystemd/sd-bus/test-bus-marshal.c (hunk 4 above)
Comment (keszybz) [reply src/libsystemd/sd-bus/test-bus-marshal.c]: Stale comment.

File: src/libsystemd/sd-bus/test-bus-marshal.c [hunk 20]
```diff
@@ -99,6 +103,140 @@ static void test_bus_label_escape_one(const char *a, const char *b) {
...
+        _cleanup_(sd_bus_message_unrefp) sd_bus_message *m = NULL;
+        _cleanup_close_ int memfd0 = -EBADF, memfd1 = -EBADF;
+        _cleanup_free_ void *blob = NULL;
+        _cleanup_free_ int *fds = NULL;
+        ino_t ino0, ino1;
+        size_t blob_size;
+        int fd, r;
+
+        /* Create two memfds and record their inodes for later verification */
+        memfd0 = memfd_create_wrapper("test-fd-0", 0);
```
Comment (keszybz) [inline src/libsystemd/sd-bus/test-bus-marshal.c]: Here and below, please don't introduce new test code which does not use the test macros. This should be `ASSERT_OK(memfd_create_wrapper(…));` etc.

File: src/libsystemd/sd-bus/test-bus-marshal.c [hunk 21]
```diff
@@ -243,7 +381,7 @@ int main(int argc, char *argv[]) {
 
         m = sd_bus_message_unref(m);
 
-        r = bus_message_from_malloc(bus, buffer, sz, NULL, 0, /* fds_might_be_truncated = */ false, NULL, &m);
+        r = bus_message_from_malloc(bus, buffer, sz, NULL, 0, /* got_ctrunc= */ false, NULL, &m);
```
Comment (keszybz) [inline src/libsystemd/sd-bus/test-bus-marshal.c]: Misplaced chunk.

File: src/libsystemd/sd-bus/bus-message.c (hunk 14 above)
Comment (poettering) [inline src/libsystemd/sd-bus/bus-message.c]: please output uint32_t with `"%" PRIu32` not with `%u`

File: src/libsystemd/sd-bus/bus-message.c [hunk 22]
```diff
@@ -4197,8 +4198,29 @@ static int message_parse_fields(sd_bus_message *m) {
...
+                        log_error("Received a bus message with MSG_CTRUNC with %u fds received vs. %u declared", m->n_fds, n_unix_fds_declared);
+                        return -EBADMSG;
+                }
+
+                /* Log a message even in the "expected" case: it'll help people track down LSM weirdness */
+                log_warning("Received a bus message with truncated fds: %u received vs. %u sent", m->n_fds, n_unix_fds_declared);
+        } else {
+                /* No CTRUNC?  Needs to be an exact match. */
+                if (m->n_fds != n_unix_fds_declared) {
+                        log_error("Received a bus message without MSG_CTRUNC with %u fds received vs %u declared", m->n_fds, n_unix_fds_declared);
```
Comment (poettering) [inline src/libsystemd/sd-bus/bus-message.c]: ditto

File: src/libsystemd/sd-bus/test-bus-chat.c [hunk 23]
```diff
@@ -493,6 +497,128 @@ static void* client2(void *p) {
...
+        assert_se(fstat(fd, &st) >= 0);
+        return st.st_ino;
+}
+
+static int get_one_message(sd_bus *bus, sd_bus_message **m) {
+        int r;
+
+        assert (m);
+
+        while (*m == NULL) {
```
Comment (poettering) [inline src/libsystemd/sd-bus/test-bus-chat.c]: in our codebase we rely on C's downgrade-to-bool feature for pointer nullness checks, hence: `while (!*m)`

File: src/libsystemd/sd-bus/test-bus-chat.c [hunk 24]
```diff
@@ -493,6 +497,128 @@ static void* client2(void *p) {
...
+                r = sd_bus_wait(bus, 100 * USEC_PER_MSEC);
```
Comment (poettering) [inline src/libsystemd/sd-bus/test-bus-chat.c]: why specify a timeout?

File: src/libsystemd/sd-bus/bus-socket.c (hunk 17 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-socket.c]: Thanks for the catch.  This was a mistake during a refactor from a previous review round...

File: src/libsystemd/sd-bus/test-bus-chat.c (hunk 24 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/test-bus-chat.c]: does the test framework impose a higher-level timeout? mostly to make sure it doesn't stall...

File: src/libsystemd/sd-bus/test-bus-marshal.c (hunk 21 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/test-bus-marshal.c]: Ooops.  I did all the test changes in the second commit without remembering that the first commit also adjusted the tests...

File: src/libsystemd/sd-bus/test-bus-marshal.c (hunk 20 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/test-bus-marshal.c]: I think I got it right, but the style here is pretty inconsistent even within this file.  Please take another look and let me know if you like it...

File: src/libsystemd/sd-bus/bus-message.c [hunk 25]
```diff
@@ -4197,8 +4198,25 @@ static int message_parse_fields(sd_bus_message *m) {
...
+                /* MSG_CTRUNC?  We need to see strictly fewer fds than the header declares. */
+                if (m->n_fds >= n_unix_fds_declared)
+                        return log_error_errno(SYNTHETIC_ERRNO(EBADMSG), "Received a bus message with MSG_CTRUNC with %" PRIu32 " fds received vs. %" PRIu32 " declared", m->n_fds, n_unix_fds_declared);
+
+                /* Log a message even in the "expected" case: it'll help people track down LSM weirdness */
+                log_error("Received a bus message with truncated fds: %" PRIu32 " received vs. %" PRIu32 " sent", m->n_fds, n_unix_fds_declared);
+        } else {
+                /* No CTRUNC?  Needs to be an exact match. */
+                if (m->n_fds != n_unix_fds_declared)
+                        return log_error_errno(SYNTHETIC_ERRNO(EBADMSG), "Received a bus message without MSG_CTRUNC with %" PRIu32 " fds received vs %" PRIu32 " declared", m->n_fds, n_unix_fds_declared);
```
Comment (YHNdnzj) [inline src/libsystemd/sd-bus/bus-message.c]: please do not log from library functions, as long as the error is somewhat expected (originates from normal communication). In this case it's a client protocol violation, and a simple return is enough.

File: src/libsystemd/sd-bus/test-bus-marshal.c (hunk 20 above)
Comment (keszybz) [reply src/libsystemd/sd-bus/test-bus-marshal.c]: Yeah. We added the macros but there was not tree-wide conversion to the new style. We do conversions one file a  time… But when new code is added, we want to use the new style.

File: src/libsystemd/sd-bus/bus-message.c (hunk 25 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-message.c]: you and @bluca need to fight this one out: he said the exact opposite 😅

Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-message.c]: you and @bluca need to fight this one out: he said the exact opposite 😅

Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-message.c]: you and @bluca need to fight this one out: he said the exact opposite 😅

File: src/libsystemd/sd-bus/bus-message.c [hunk 26]
```diff
@@ -4197,8 +4198,25 @@ static int message_parse_fields(sd_bus_message *m) {
                         return r;
         }
 
-        if (m->n_fds != unix_fds)
-                return -EBADMSG;
+        /* Validate that the number of fds we actually received via SCM_RIGHTS matches (or is compatible
+         * with) the number declared in the message header.
+         *
+         * Normally these must match exactly. However, when MSG_CTRUNC was set during recvmsg(), the kernel
+         * should have truncated the fd array (e.g., due to LSM denials blocking fd passing). In that case,
```
Comment (keszybz) [inline src/libsystemd/sd-bus/bus-message.c]: For the commit message: para 4 starts with "This puts the receiver of the message into a difficult situation" but para 3 talks about changes being done. I assume that wasn't intended to say that the introduced changes inconvenience the receiver . Please adjust the commit message.

Here: "should have" → "might have" ? Also below, the comment seems to have been written with the assumption that MSG_TRUNC indicates that the fd array was truncated. But as discussed later, there are other reasons for MSG_TRUNC to be set. So the number of fds might not be affected, even if MSG_TRUNC is set.

Oh, and the code treats `got_trunc && m->n_fds == n_unix_fds_declared` as a hard error and returns immediately. This seems unnecessary.

I think the code would be easier if the indents were reduced by one, into a flat conditional list, even if the boolean is "evaluated" twice:
```C
if (m->n_fds > n_unix_fds_declared)
     return log_debug_errno(SYNTHETIC_ERRNO(EBADMSG),
                            "Too many fds…");
if (m->n_fds < n_unix_fds_declared && !got_ctrunc)
     return log_debug_errno(SYNTHETIC_ERRNO(EBADMSG),
                            "Not enough many fds…");
if (m->n_fds < n_unix_fds_declared && got_ctrunc)
    log_debug("Received message with truncated fd array, attempts to access those fds will fail later, continuing.");
...
```

File: src/libsystemd/sd-bus/bus-message.c (hunk 25 above)
Comment (bluca) [reply src/libsystemd/sd-bus/bus-message.c]: This is going to be extremely hard to debug, so it seems well worth an exception to the convention

File: src/libsystemd/sd-bus/bus-message.c [hunk 27]
```diff
@@ -4197,8 +4198,25 @@ static int message_parse_fields(sd_bus_message *m) {
...
+         * we accept strictly fewer fds than declared. Any attempt to actually use a truncated fd will fail
+         * later when sd_bus_message_read_basic() finds the fd index out of range. */
+        if (got_ctrunc) {
+                /* MSG_CTRUNC?  We need to see strictly fewer fds than the header declares. */
+                if (m->n_fds >= n_unix_fds_declared)
+                        return log_error_errno(SYNTHETIC_ERRNO(EBADMSG), "Received a bus message with MSG_CTRUNC with %" PRIu32 " fds received vs. %" PRIu32 " declared", m->n_fds, n_unix_fds_declared);
```
Comment (keszybz) [inline src/libsystemd/sd-bus/bus-message.c]: This line is very long. Please apply some linebreaks.

File: src/libsystemd/sd-bus/bus-message.c (hunk 25 above)
Comment (keszybz) [reply src/libsystemd/sd-bus/bus-message.c]: Yeah. This needs to be `debug` level here. It'd be nice to emit the warning here, but we have the general rule that library code must not log non-debug.

File: src/libsystemd/sd-bus/test-bus-chat.c (hunk 24 above)
Comment (keszybz) [reply src/libsystemd/sd-bus/test-bus-chat.c]: It does. Meson has a timeout. There are also timeouts at higher levels. So we don't want to have a timeout here if the test is intended to function without it.

**Comment by keszybz** [comment]
On Mon, Jan 19, 2026 at 04:59:47AM -0800, Luca Boccassi wrote:
> @bluca commented on this pull request.
> 
> 
> 
> > +                /* No CTRUNC?  Needs to be an exact match. */
> +                if (m->n_fds != n_unix_fds_declared)
> +                        return log_error_errno(SYNTHETIC_ERRNO(EBADMSG), "Received a bus message without MSG_CTRUNC with %" PRIu32 " fds received vs %" PRIu32 " declared", m->n_fds, n_unix_fds_declared);
> 
> This is going to be extremely hard to debug, so it seems well worth an exception to the convention

OK, so let's leave it at non-debug level for now. I think we'll end up with changing that, but let's get the patch merged, we can figure out the details of logging later.

File: src/libsystemd/sd-bus/bus-message.c (hunk 25 above)
Comment (YHNdnzj) [reply src/libsystemd/sd-bus/bus-message.c]: I'm referring to the else branch only, which didn't log anything

File: src/libsystemd/sd-bus/bus-message.c (hunk 26 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-message.c]: Here: "should have" → "might have" ? 

I'm not sure about that.  If we got CTRUNC then I really assume that we got our array of fds truncated.  If we get the expected number of fds even with CTRUNC set then that truly is something unexpected.  I'm not stuck on this point, though, so I'm happy to simplify the checks a bit.

Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-message.c]: I followed your suggested approach but changed it to log an error if got_ctrunc, regardless of the number of fds involved.  I thought about lifting it to the calling function but having the expected/declared number of fds in the error message is useful, and we need to decode the header to get that, so it stays here.

File: src/libsystemd/sd-bus/bus-message.c (hunk 27 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-message.c]: Broke all of these up.

File: src/libsystemd/sd-bus/bus-message.c (hunk 25 above)
Comment (allisonkarlitskaya) [reply src/libsystemd/sd-bus/bus-message.c]: Discussed further below: we'll keep these as errors for now.

**Comment by keszybz** [comment]
DNS fails in the noble/* runs.

File: src/libsystemd/sd-bus/bus-message.c [hunk 28]
```diff
@@ -4197,8 +4198,26 @@ static int message_parse_fields(sd_bus_message *m) {
...
+                                       "Received a bus message with too many fds: %" PRIu32 " received vs. %" PRIu32 " declared",
+                                       m->n_fds, n_unix_fds_declared);
+
+        if (m->n_fds < n_unix_fds_declared && !got_ctrunc)
+                return log_error_errno(SYNTHETIC_ERRNO(EBADMSG),
+                                       "Received a bus message with too few fds: %" PRIu32 " received vs. %" PRIu32 " declared",
+                                       m->n_fds, n_unix_fds_declared);
+
+        if (got_ctrunc)
+                log_error("Received a bus message with MSG_CTRUNC set with %" PRIu32 " fds received vs %" PRIu32 " declared",
```
Comment (yuwata) [inline src/libsystemd/sd-bus/bus-message.c:4219]: I do not think we should log in LOG_ERR level from library.

Comment (yuwata) [reply src/libsystemd/sd-bus/bus-message.c:4219]: Ah, you already discussed about that.
Hm, but still I'd like to make them in LOG_DEBUG.

Comment (yuwata) [reply src/libsystemd/sd-bus/bus-message.c:4219]: -> #40487.
