### PR TITLE
core: mark units as need daemon-reload if unit file operations are performed

### LINKED ISSUE #29341: Invalid Alias parameter, causing the service status to be inconsistent.
### systemd version the issue has been seen with

253

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

When `A.service` is running, configure a valid `Alias`and an invalid `Alias`, and `systemctl enable A`. `A.service` is `enabled`.

### Unexpected behaviour you saw

When `A.service` is running, configure a valid `Alias`and an invalid `Alias`, and `systemctl enable A`. `systemctl status A.service` finds `A.serivce` is `disabled`, but `systemctl is-enabled A.serivce` return enabled. After `systemctl stop A; systemctl start A`, `A.service` is `enabled`.

### Steps to reproduce the problem

\# cat << EOF > /usr/lib/systemd/system/A.service
[Unit]
Description="serivce A"
[Service]
ExecStart=/usr/bin/sleep 100
[Install]
Alias=B.service
Alias=C
EOF

\# systemctl daemon-reload

\# systemctl start A

\# systemctl status A
● A.service - "serivce A"
     Loaded: loaded (/usr/lib/systemd/system/A.service; disabled; preset: disabled)
     Active: active (running) since Wed 2023-09-27 11:27:06 CST; 3s ago
   Main PID: 7145 (sleep)
      Tasks: 1 (limit: 21479)
     Memory: 200.0K
     CGroup: /system.slice/A.service
             └─7145 /usr/bin/sleep 100

\# systemctl enable A
Failed to enable unit: Cannot alias A.service as C.

\# systemctl status A
● A.service - "serivce A"
     Loaded: loaded (/usr/lib/systemd/system/A.service; disabled; preset: disabled)
     Active: active (running) since Wed 2023-09-27 11:27:50 CST; 47s ago
   Main PID: 7154 (sleep)
      Tasks: 1 (limit: 21479)
     Memory: 196.0K
     CGroup: /system.slice/A.service
             └─7154 /usr/bin/sleep 100

\# systemctl is-enabled A
enabled

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by YHNdnzj**
'systemctl enable/disable' would issue daemon-reload after the operation succeeds. However, enabling and disabling are not atomic, meaning that the unit file state could still change even if the operation generally fails, and the unit_file_state cached by manager becomes outdated.

Fixes #29341

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
so here's another idea, very pragmatic, and I think I like it: maintain a simple boolean for the whole manager object: whenever we make the first change of a unit file enablement/disablement, we set it. and on daemon-reload it gets reset again. And we simply OR that into any per-unit NeedsReload.

This would fix the issue nicely I think, and would be a good idea anyway, as it means any "forgotten" unit file operation will still be reported as needs daemon reload until the reload takes place...

File: src/core/dbus-manager.c [hunk 1]
```diff
@@ -2543,6 +2543,8 @@ static int method_enable_unit_files_generic(
                 return 1; /* No authorization for now, but the async polkit stuff will call us again when it has it */
 
         r = call(m->runtime_scope, flags, NULL, l, &changes, &n_changes);
+        if (n_changes > 0)
+                m->unit_file_state_outdated = true; /* See comments for this variable in manager.h */
```
Comment (poettering) [inline src/core/dbus-manager.c]: could also do:

```c
m->unit_file_state_outdated = m->unit_file_state_outdated || n_changes > 0;
```
