### PR TITLE
let's make "systemd-run --scope --user" work again on cgroupsv2

### LINKED ISSUE #3388: systemd-run --user --scope ... doesn't work with unified cgroup hierarchy
### Submission type
- [ x ] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

`230 and 230+84 commits`
### Used distribution

`Arch Linux (testing)`
### In case of bug report: Expected behaviour you didn't see

`systemd-run --user --scope bash -c "sleep 100"` should start a new scope and service in the user systemd instance.
### In case of bug report: Unexpected behaviour you saw

systemd-run fails and the journal has `run-r9c9b0f8d4fd14753bd9d4446b7a4c1ef.scope: Failed to add PIDs to scope's control group: Permission denied`

The system was booted with `systemd.unified_cgroup_hierarchy=1`. Removing that option (and rebooting) makes systemd-run --scope work again.

### PR DESCRIPTION
**Pull request by poettering**
lots of fixes in order to finally close #3388.

### CODE REVIEW

**Comment by evverx** [comment]
`systemd` seems to be crashing on `xenial`, which could be because `cgroup2` is not supported there. Here are the logs that I was able to get from a `xenial` host:
```sh
Feb 07 23:13:46 systemd[1]: Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
...
Feb 07 23:14:05 systemd[1]: session-1.scope: Failed to attach PID 224 to realized cgroup /user.slice/user-0.slice/session-1.scope in controller cpu, ignoring: No such file or directory
Feb 07 23:14:05 systemd[1]: Assertion 'path' failed at ../src/basic/cgroup-util.c:823, function cg_attach(). Aborting.
Feb 07 23:14:05 systemd-coredump[235]: Due to PID 1 having crashed coredump collection will now be turned off.
Feb 07 23:14:05 systemd[1]: Caught <ABRT>, dumped core as pid 234.
Feb 07 23:14:05 systemd[1]: Freezing execution.
Feb 07 23:14:11 systemd-coredump[235]: Failed to generate stack trace: Unwinding not supported for this architecture
Feb 07 23:14:11 systemd-coredump[235]: Process 234 (systemd) of user 0 dumped core.
Feb 07 23:14:30 login[224]: pam_systemd(login:session): Failed to create session: Connection timed out
```
and the backtrace:
```sh
#0  0x00007f15cf2fb767     kill - libc.so.6
#1  0x00005606c3a0a05c - 1 crash - /lib/systemd/systemd
    ../src/core/main.c:196
#2  0x00007f15cf6a1390     __restore_rt - libpthread.so.0
#3  0x00007f15cf2fb428     raise - libc.so.6
#4  0x00007f15cf2fd02a - 1 abort - libc.so.6
#5  0x00007f15d1122e48 - 1 log_assert_failed_realm - libsystemd-shared-237.so
    ../src/basic/log.c:820
#6  0x00007f15d10fa789 - 1 cg_attach - libsystemd-shared-237.so
    ../src/basic/cgroup-util.c:823
#7  0x00005606c3aca9d5 - 1 unit_attach_pids_to_cgroup - /lib/systemd/systemd
    ../src/core/cgroup.c:1636
#8  0x00005606c3af647b - 1 scope_start - /lib/systemd/systemd
    ../src/core/scope.c:346
#9  0x00005606c3aab540 - 1 unit_start - /lib/systemd/systemd
    ../src/core/unit.c:1861
#10 0x00005606c3a429c4 - 1 job_perform_on_unit - /lib/systemd/systemd
    ../src/core/job.c:529
#11 0x00005606c3a42d39 - 1 job_run_and_invalidate - /lib/systemd/systemd
    ../src/core/job.c:594
#12 0x00005606c3a655d5 - 1 manager_dispatch_run_queue - /lib/systemd/systemd
    ../src/core/manager.c:1861
#13 0x00007f15d11bab86 - 1 source_dispatch - libsystemd-shared-237.so
    ../src/libsystemd/sd-event/sd-event.c:2333
#14 0x00007f15d11bbeb1 - 1 sd_event_dispatch - libsystemd-shared-237.so
    ../src/libsystemd/sd-event/sd-event.c:2663
#15 0x00007f15d11bc349 - 1 sd_event_run - libsystemd-shared-237.so
    ../src/libsystemd/sd-event/sd-event.c:2723
#16 0x00005606c3a685cb - 1 manager_loop - /lib/systemd/systemd
    ../src/core/manager.c:2573
#17 0x00005606c3a10b7b - 1 invoke_main_loop - /lib/systemd/systemd
    ../src/core/main.c:1778
#18 0x00005606c3a138e6 - 1 main - /lib/systemd/systemd
    ../src/core/main.c:2563
#19 0x00007f15cf2e6830 - 1 __libc_start_main - libc.so.6
#20 0x00005606c3a093a9 - 1 _start - /lib/systemd/systemd
```

**Comment by evverx** [comment]
I seem to have been wrong to say that the crash has anything to do with whether `cgroup2` is supported or not. I can reproduce it on a machine where the hybrid hierarchy is being used. Passing `systemd.unified_cgroup_hierarchy=yes` appears to be enough to make everything work.

File: src/core/manager.c [hunk 1]
```diff
@@ -2296,17 +2321,18 @@ static int manager_dispatch_signal_fd(sd_event_source *source, int fd, uint32_t
                 break;
 
         case SIGUSR1: {
-                Unit *u;
+                bool b;
 
-                u = manager_get_unit(m, SPECIAL_DBUS_SERVICE);
-
-                if (!u || UNIT_IS_ACTIVE_OR_RELOADING(unit_active_state(u))) {
+                b = manager_dbus_is_running(m, false);
```
Comment (keszybz) [inline src/core/manager.c]: Would be nicer to get rid of `b` and put the condition directly in the conditional.

File: src/core/manager.c [hunk 2]
```diff
@@ -3519,6 +3546,30 @@ int manager_set_default_rlimits(Manager *m, struct rlimit **default_rlimit) {
...
+        bool b;
+
+        assert(m);
+
+        /* Connects to the bus if the dbus service and socket are running. If we are running in user mode this is all
+         * it does. In system mode we'll also connect to the system bus (which will most likely just reuse the
+         * connection of the API bus). That's because the system bus after all runs as service of the system instance,
+         * while in the user instance we can assume it's already there. */
+
+        b = manager_dbus_is_running(m, false);
```
Comment (keszybz) [inline src/core/manager.c]: The same here.

File: src/core/manager.c [hunk 3]
```diff
@@ -3185,8 +3186,7 @@ int manager_reload(Manager *m) {
         manager_recheck_dbus(m);
 
         /* Sync current state of bus names with our set of listening units */
-        if (m->api_bus)
-                manager_sync_bus_names(m, m->api_bus);
+        manager_enqueue_sync_bus_names(m);
```
Comment (keszybz) [inline src/core/manager.c]:
```C
q = ...
if (q < 0 && r >= 0)
    r = q;
```
?

File: src/core/cgroup.c [hunk 4]
```diff
@@ -1503,19 +1507,140 @@ static int unit_create_cgroup(
...
+
+        /* Determine this unit's cgroup path relative to our cgroup root */
+        pp = path_startswith(u->cgroup_path, u->manager->cgroup_root);
+        if (!pp)
+                return -EINVAL;
+
+        if (!isempty(suffix_path))
+                pp = strjoina("/", pp, suffix_path);
+        else
+                pp = strjoina("/", pp);
```
Comment (keszybz) [inline src/core/cgroup.c]: That `if` is not necessary, the "true" branch works for both cases.

File: src/core/cgroup.c [hunk 5]
```diff
@@ -1503,19 +1507,140 @@ static int unit_create_cgroup(
...
+                /* First, attach the PID to the main cgroup hierarchy */
+                q = cg_attach(SYSTEMD_CGROUP_CONTROLLER, p, pid);
+                if (IN_SET(q, -EPERM, -EACCES) && MANAGER_IS_USER(u->manager)) {
+                        /* If we are in a user instance, and we can't moe the process ourselves, let's ask the system
+                         * instance about it instead. Since it's more privileged it might be able to move the process
+                         * across the leaves of a subtree who's top node is not owned by us. */
+
+                        q = unit_attach_pid_to_cgroup_via_bus(u, pid, suffix_path);
+                        if (q < 0)
+                                log_unit_debug_errno(u, q, "Going via the bus didn't work either, ignoring: %m");
```
Comment (keszybz) [inline src/core/cgroup.c]: This log line will is hard to understand without context. I think it'd be nicer to exchange the order here, so that both errors (with errnos) are logged. This will make things clearer when debugging. Also, I don't like the artificial setting of the errno (EACCESS → EPERM).
```C
 q = cg_attach(SYSTEMD_CGROUP_CONTROLLER, p, pid);
 if (q < 0) {
            log_unit_debug_errno(...);
            if (MANAGER_IS_SYSTEM(u->manager) || !IN_SET(q, -EPERM, -EACCES))
                  continue;
 q = unit_attach_pid_to_cgroup_via_bus(...);
 if (q < 0)
            log_unit_debug_errno(u, q, "Couldn't move process " PID_FMT " to requested cgroup %s via bus: %m", pid, p);
```

**Comment by poettering** [comment]
@evverx thanks a lot for finding this! just force pushed a new version that should fix the issue!

File: src/core/cgroup.c [hunk 6]
```diff
@@ -1503,19 +1507,140 @@ static int unit_create_cgroup(
...
+
+        r = 0;
+        SET_FOREACH(pidp, pids, i) {
+                pid_t pid = PTR_TO_PID(pidp);
+                CGroupController c;
+
+                /* First, attach the PID to the main cgroup hierarchy */
+                q = cg_attach(SYSTEMD_CGROUP_CONTROLLER, p, pid);
+                if (IN_SET(q, -EPERM, -EACCES) && MANAGER_IS_USER(u->manager)) {
+                        /* If we are in a user instance, and we can't moe the process ourselves, let's ask the system
```
Comment (keszybz) [inline src/core/cgroup.c]: mo*v*e

File: src/core/unit.c [hunk 7]
```diff
@@ -5362,6 +5362,34 @@ const char *unit_label_path(Unit *u) {
...
+        /* Some extra safety check */
+        if (pid == 1 || pid == getpid_cached())
+                return sd_bus_error_setf(error, SD_BUS_ERROR_INVALID_ARGS, "Process " PID_FMT " is manager processs, refusing.", pid);
+
+        /* Don't even begin to bother with kernel threads */
+        r = is_kernel_thread(pid);
+        if (r == -ESRCH)
+                return sd_bus_error_setf(error, SD_BUS_ERROR_UNIX_PROCESS_ID_UNKNOWN, "Process with ID " PID_FMT " does not exist.", pid);
+        if (r < 0)
+                return sd_bus_error_set_errnof(error, r, "Failed to determine whether process " PID_FMT " is kernel thread: %m", pid);
```
Comment (keszybz) [inline src/core/unit.c]: is *a*

File: src/core/unit.c [hunk 8]
```diff
@@ -5362,6 +5362,34 @@ const char *unit_label_path(Unit *u) {
...
+        if (r > 0)
+                return sd_bus_error_setf(error, SD_BUS_ERROR_INVALID_ARGS, "Process " PID_FMT " is kernel thread, refusing.", pid);
```
Comment (keszybz) [inline src/core/unit.c]: is *a*

**Comment by poettering** [comment]
I force pushed a new version, adressing the issues @keszybz found, too! PTAL!

File: src/core/dbus-unit.c [hunk 9]
```diff
@@ -1127,6 +1127,118 @@ static int property_get_ip_counter(
...
+        int r;
+
+        assert(message);
+
+        /* This migrates the processes with the specified PIDs into the cgroup of this unit, optionally below a
+         * specified cgroup path. Obviously this only works for units that actually maintain a cgroup
+         * representation. If a process is already in the cgroup no operation is executed – in this case the specified
+         * subcgroup path has no effect! */
+
+        r = mac_selinux_unit_access_check(u, message, "start", error);
```
Comment (keszybz) [inline src/core/dbus-unit.c:1145]: IIUC, if we wanted something different than "start", if would be necessary to amend selinux policy. Might be worth it. Maybe we should reach out to selinux maintainers for comments?

File: src/core/unit.c [hunk 10]
```diff
@@ -2463,12 +2461,6 @@ void unit_notify(Unit *u, UnitActiveState os, UnitActiveState ns, bool reload_su
         /* Some names are special */
```
Comment (sourcejedi) [inline src/core/unit.c:2461]: This comment can be removed.  The `if/else` block doesn't have any special names in it anymore.

Comment (keszybz) [reply src/core/unit.c:2461]: → #8199.
