### PR TITLE
network: state-file: ignore dynamic entries when specified by DBus method

### LINKED ISSUE #21515: systemd-resolved unable to overwrite DHCP DNS servers
<details>
<summary>Versions (systemd 249, linux 5.15)</summary>

```
$ systemctl --version
systemd 249 (249.7-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

$ uname -a
Linux host 5.15.4-arch1-1 #1 SMP PREEMPT Sun, 21 Nov 2021 21:34:33 +0000 x86_64 GNU/Linux
```

</details>

Using a `systemd-networkd`-managed interface using DHCP, `systemd-resolved` gets properly configured with the network's DHCP-advertised DNS servers.

However, `resolvectl dns $IFACE` is not able to remove those servers from the list, either by using `""` (an empty argument, as pointed out by the man page to clear the DNS servers) or trying to replace with another one (e.g. `1.1.1.1`).

- `resolvectl dns $IFACE ""` is more or less a no-op (i.e. dhcp-supplied DNS servers remain configured on that interface)
- `resolvectl dns $IFACE 1.1.1.1` adds the server to the list, does not remove DHCP-supplied servers, and does not change the `Current DNS Server` field shown in `resolvectl status $IFACE`, resulting in the system still using the "wrong" one.

Disabling DNS support on the `.network` file for DHCP and DHCPv6 (with or without setting DNS servers there) makes resolved able to configure that interface as expected.

<details><summary>Drop-in .network file</summary>

```ini
[Match]
Name=$IFACE

[Network]
DHCP=true
DNS=1.1.1.1

[DHCPv4]
UseDNS=false

[DHCPv6]
UseDNS=false

[IPv6AcceptRA]
UseDNS=false
```

</details>

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #21515.

### CODE REVIEW

File: src/network/networkd-state-file.c [hunk 1]
```diff
@@ -418,6 +423,44 @@ static void serialize_addresses(
...
+        assert(link);
+        assert(f);
+
+        ORDERED_SET_FOREACH(p, static_domains)
+                fputs_with_space(f, p, NULL, &space);
+
+        if (use_domains == DHCP_USE_DOMAINS_NO)
+                return;
+
+        if (link->dhcp_lease && link->network->dhcp_use_domains == use_domains) {
```
Comment (bluca) [inline src/network/networkd-state-file.c:440]: check or assert `link->network`

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
@bluca Thank you! Upgrading the green label.
