### PR TITLE
core: gracefully ignore PrivateBPF=yes if the kernel does not support it

### LINKED ISSUE #38225: TEST-07-PID1.private-bpf fails on arm64/ppc64el
```
7414s TEST-07-PID1.sh[4054]: + systemd-run --wait -p PrivateUsers=yes -p PrivateMounts=yes -p DelegateNamespaces=mnt -p ProtectKernelTunables=yes -p PrivateBPF=no grep -q '/sys/fs/bpf .* ro,' /proc/mounts
7414s TEST-07-PID1.sh[4055]: Running as unit: run-ra9c30e61b1a14f8888037cc330fa7f65.service; invocation ID: a401e36111e64c8b804f4912bb8e314c
7414s TEST-07-PID1.sh[4055]:           Finished with result: success
7414s TEST-07-PID1.sh[4055]: Main processes terminated with: code=exited, status=0/SUCCESS
7414s TEST-07-PID1.sh[4055]:                Service runtime: 27ms
7414s TEST-07-PID1.sh[4055]:              CPU time consumed: 22ms
7414s TEST-07-PID1.sh[4055]:                    Memory peak: 1.9M (swap: 0B)
7414s TEST-07-PID1.sh[4054]: + systemd-run --wait -p PrivateUsers=yes -p PrivateMounts=yes -p DelegateNamespaces=mnt -p PrivateBPF=yes grep -q '^none /sys/fs/bpf bpf rw' /proc/mounts
7414s TEST-07-PID1.sh[4059]: Running as unit: run-r82485d5cd7b84174972f6f7a3fe21ca6.service; invocation ID: 7636f268621d42238f1b918970da7a0c
7414s TEST-07-PID1.sh[4059]:           Finished with result: exit-code
7414s TEST-07-PID1.sh[4059]: Main processes terminated with: code=exited, status=226/NAMESPACE
7414s TEST-07-PID1.sh[4059]:                Service runtime: 22ms
7414s TEST-07-PID1.sh[4059]:              CPU time consumed: 9ms
7414s TEST-07-PID1.sh[4059]:                    Memory peak: 1.9M (swap: 0B)
7414s TEST-07-PID1.sh[113]: + echo 'Subtest /usr/lib/systemd/tests/testdata/units/TEST-07-PID1.private-bpf.sh failed'
7414s TEST-07-PID1.sh[113]: Subtest /usr/lib/systemd/tests/testdata/units/TEST-07-PID1.private-bpf.sh failed
```

```
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Successfully forked off '(sd-bpffs)' as PID 4061.
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Successfully forked off '(sd-userns)' as PID 4062.
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: (sd-userns) succeeded.
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Set up privileged user namespace
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Bind-mounting / on /run/systemd/mount-rootfs (MS_BIND|MS_REC "")...
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Applying namespace mount on /run/systemd/mount-rootfs/dev
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Applying namespace mount on /run/systemd/mount-rootfs/proc
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Mounting proc (proc) on /run/systemd/namespace-ALyb7A (MS_NOSUID|MS_NODEV|MS_NOEXEC "")...
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Failed to mount proc (type proc) on /run/systemd/namespace-ALyb7A (MS_NOSUID|MS_NODEV|MS_NOEXEC ""): Operation not permitted
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Applying namespace mount on /run/systemd/mount-rootfs/run
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Applying namespace mount on /run/systemd/mount-rootfs/run/credentials
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Failed to umount /run/systemd/mount-rootfs/run/credentials/systemd-journald.service, ignoring: Invalid argument
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Failed to umount /run/systemd/mount-rootfs/run/credentials/systemd-resolved.service, ignoring: Invalid argument
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Failed to umount /run/systemd/mount-rootfs/run/credentials/systemd-networkd.service, ignoring: Invalid argument
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Failed to umount /run/systemd/mount-rootfs/run/credentials/console-getty.service, ignoring: Invalid argument
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Bind-mounting /run/systemd/inaccessible/dir on /run/systemd/mount-rootfs/run/credentials (MS_BIND|MS_REC "")...
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Successfully mounted /run/systemd/inaccessible/dir to /run/systemd/mount-rootfs/run/credentials
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Applying namespace mount on /run/systemd/mount-rootfs/run/systemd/incoming
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Followed source symlinks /run/systemd/propagate/run-r82485d5cd7b84174972f6f7a3fe21ca6.service → /run/systemd/propagate/run-r82485d5cd7b84174972f6f7a3fe21ca6.service.
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Bind-mounting /run/systemd/propagate/run-r82485d5cd7b84174972f6f7a3fe21ca6.service on /run/systemd/mount-rootfs/run/systemd/incoming (MS_BIND "")...
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Successfully mounted /run/systemd/propagate/run-r82485d5cd7b84174972f6f7a3fe21ca6.service to /run/systemd/mount-rootfs/run/systemd/incoming
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Applying namespace mount on /run/systemd/mount-rootfs/sys
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Applying namespace mount on /run/systemd/mount-rootfs/sys/fs/bpf
Jul 15 04:30:55 H (sd-bp[4061]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Failed to create bpffs superblock: Operation not permitted
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Failed to fsmount bpffs: Invalid argument
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Failed to set up mount namespacing: /sys/fs/bpf: Invalid argument
Jul 15 04:30:55 H (grep)[4060]: run-r82485d5cd7b84174972f6f7a3fe21ca6.service: Failed at step NAMESPACE spawning /usr/bin/grep: Invalid argument
```

https://autopkgtest.ubuntu.com/results/autopkgtest-noble-upstream-systemd-ci-systemd-ci/noble/arm64/s/systemd-upstream/20250715_034635_a69b1@/log.gz
https://autopkgtest.ubuntu.com/results/autopkgtest-noble-upstream-systemd-ci-systemd-ci/noble/arm64/s/systemd-upstream/20250715_034635_a69b1@/artifacts.tar.gz

Introduced by https://github.com/systemd/systemd/pull/36134

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #38225.

### CODE REVIEW

**Comment by teknoraver** [comment]
@yuwata the changes are ok, but they are unrelated to the failure.
In Ubuntu with a 6.8 kernel the error can be reproduces without even calling the helper:
```
root@H:~# uname -a
Linux H 6.8.0-63-generic #66-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 13 20:09:49 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

root@H:~# systemd-run --wait -p PrivateUsers=yes -p PrivateMounts=yes -p DelegateNamespaces=mnt -p PrivateBPF=yes true
Running as unit: run-r28cb45a5d2b2445796424307a8aa822b.service; invocation ID: beae8781e23343ce90dc128ee70e8c35
          Finished with result: exit-code
Main processes terminated with: code=exited, status=226/NAMESPACE
               Service runtime: 14ms
             CPU time consumed: 6ms
                   Memory peak: 2.4M (swap: 0B)
```

**Comment by bluca** [comment]
```
TEST-07-PID1.sh[3971]: + /usr/lib/systemd/tests/unit-tests/manual/test-bpf-token
TEST-07-PID1.sh[4003]: Failed to create bpf token: Invalid argument
TEST-07-PID1.sh[3971]: + '[' 1 -eq 77 ']'
TEST-07-PID1.sh[3971]: + set -e
TEST-07-PID1.sh[3971]: + systemd-run --wait -p PrivateUsers=yes -p PrivateMounts=yes -p DelegateNamespaces=mnt -p PrivateBPF=yes -p BPFDelegateCommands=BPFProgLoad /usr/lib/systemd/tests/unit-tests/manual/test-bpf-token
TEST-07-PID1.sh[4004]: Running as unit: run-p4004-i136480.service; invocation ID: 4f0acad7c9f040b18f81bc6ca33edad6
TEST-07-PID1.sh[4004]:           Finished with result: exit-code
TEST-07-PID1.sh[4004]: Main processes terminated with: code=exited, status=77/NOPERM
TEST-07-PID1.sh[4004]:                Service runtime: 58ms
TEST-07-PID1.sh[4004]:              CPU time consumed: 29ms
TEST-07-PID1.sh[4004]:                    Memory peak: 2.2M (swap: 0B)
```

**Comment by yuwata** [comment]
@bluca @teknoraver Could you re-review and re-test again?

**Comment by bluca** [comment]
```
../src/test/test-bpf-token.c: In function ‘intro’:
../src/test/test-bpf-token.c:31:48: error: missing binary operator before token ‘(’
   31 | #if HAVE_LIBBPF && __LIBBPF_CURRENT_VERSION_GEQ(1, 5)
```

**Comment by yuwata** [comment]
@bluca @teknoraver Another version is pushed. Please test. Thank you.

File: src/core/unit.c [hunk 1]
```diff
@@ -4442,6 +4442,12 @@ int unit_patch_contexts(Unit *u) {
 
                 FOREACH_ARRAY(d, ec->directories, _EXEC_DIRECTORY_TYPE_MAX)
                         exec_directory_sort(d);
+
+                if (ec->private_bpf != PRIVATE_BPF_NO && !fsconfig_bpffs_supported()) {
+                        log_unit_debug(u, "PrivateBPF=%s is not supported by the kernel, disabling the feature.",
```
Comment (bluca) [inline src/core/unit.c]: maybe log_once at info level, to make sure it's visible?

Comment (yuwata) [reply src/core/unit.c]: Yeah. Will do on next push.

File: src/core/unit.c [hunk 2]
```diff
@@ -4442,6 +4442,12 @@ int unit_patch_contexts(Unit *u) {
...
+                                       private_bpf_to_string(ec->private_bpf));
+                        ec->private_bpf = PRIVATE_BPF_NO;
```
Comment (YHNdnzj) [inline src/core/unit.c]: I'd prefer if this is done in executor and not in pid1. pid1 can have quite different process context after all, and all other fallback logic we currently carry is invoked in executor.

Comment (yuwata) [reply src/core/unit.c]: This is the kernel feature check. So, checking here should be efficient.
Of course, theoretically, even if this is passed, the executor may fail to setup bpffs. But, what's the real issue in checking here?

Comment (YHNdnzj) [reply src/core/unit.c]: We usually try to preserve what's set in unit file (or implied by other settings) and export that via IPC. The fallback logic is logged separately. Now suddenly the actual support for the feature also impacts that, which kinda irks me.

Comment (yuwata) [reply src/core/unit.c]: OK. Moved to the executor.

**Comment by yuwata** [comment]
@bluca @teknoraver @YHNdnzj Force-pushed new version. Please take a look. Thank you!

**Comment by teknoraver** [comment]
Oddly this behave differently than systemd:
```
root@H:~# /usr/lib/systemd/tests/testdata/units/TEST-07-PID1.private-bpf.sh
+ set -o pipefail
+ systemd-run --wait -p PrivateUsers=yes -p PrivateMounts=yes -p DelegateNamespaces=mnt -p ProtectKernelTunables=yes -p PrivateBPF=no grep -q '/sys/fs/bpf .* ro,' /proc/mounts
Running as unit: run-r0f36e645f1744e1687f2d9235f80c4f3.service; invocation ID: 7edb8f4855384bcbad5c606028d49c75
          Finished with result: success
Main processes terminated with: code=exited, status=0/SUCCESS
               Service runtime: 22ms
             CPU time consumed: 15ms
                   Memory peak: 1.9M (swap: 0B)
+ set +e
+ /usr/lib/systemd/tests/unit-tests/manual/test-bpffs
+ RET_TEST_BPFFS=0
+ set -e
+ ((  RET_TEST_BPFFS != 0  ))
+ systemd-run --wait -p PrivateUsers=yes -p PrivateMounts=yes -p DelegateNamespaces=mnt -p PrivateBPF=yes grep -q '^none /sys/fs/bpf bpf rw' /proc/mounts
Running as unit: run-r7d3adbfa92ef4de0afe77c45ed1d7a30.service; invocation ID: fac324f2d3d44ebe90f3a00ec3c8f2cb
          Finished with result: exit-code
Main processes terminated with: code=exited, status=226/NAMESPACE
               Service runtime: 19ms
             CPU time consumed: 6ms
                   Memory peak: 2.4M (swap: 0B)
root@H:~#
```
strace says:
```
root@H:~# strace -e fsopen,fsconfig /usr/lib/systemd/tests/unit-tests/manual/test-bpffs
fsopen("bpf", FSOPEN_CLOEXEC)           = 3
fsconfig(3, FSCONFIG_SET_STRING, "delegate_cmds", "0xffffffffffffffff", 0) = 0
fsconfig(3, FSCONFIG_SET_STRING, "delegate_maps", "0xffffffffffffffff", 0) = 0
fsconfig(3, FSCONFIG_SET_STRING, "delegate_progs", "0xffffffffffffffff", 0) = 0
fsconfig(3, FSCONFIG_SET_STRING, "delegate_attachs", "0xffffffffffffffff", 0) = 0
fsconfig(3, FSCONFIG_CMD_CREATE, NULL, NULL, 0) = 0
+++ exited with 0 +++
```

I think that the problem lies behind the two unshare() that systemd does before fsconfig.
Let me try this.

File: src/basic/mountpoint-util.c [hunk 3]
```diff
@@ -807,6 +807,33 @@ int mount_option_supported(const char *fstype, const char *key, const char *valu
         return true; /* works! */
 }
 
+bool fsconfig_bpffs_supported(void) {
```
Comment (YHNdnzj) [inline src/basic/mountpoint-util.c]: Then, this can be a static function in core/namespace.c

File: src/core/execute.h [hunk 4]
```diff
@@ -525,6 +525,7 @@ char** exec_context_get_address_families(const ExecContext *c);
 char** exec_context_get_restrict_filesystems(const ExecContext *c);
 bool exec_context_restrict_namespaces_set(const ExecContext *c);
 bool exec_context_restrict_filesystems_set(const ExecContext *c);
+PrivateBPF exec_context_get_private_bpf(const ExecContext *c);
```
Comment (YHNdnzj) [inline src/core/execute.h]: I'd group this with exec_context_get_protect_control_groups

**Review by YHNdnzj — APPROVED** [review]
LGTM

**Comment by teknoraver** [comment]
@yuwata this still doesn't work.
This is the sample I was using to develop the bpf feature:
https://gist.github.com/teknoraver/92f27cbc456e4ab4a508943eb93958b8
This one works with kernel 6.11 and doesn with 6.8:

```
root@H:~# uname -a
Linux H 6.8.0-63-generic #66-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 13 20:09:49 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

root@H:~# strace -fe fsconfig /work/src/bpf_token
strace: Process 4376 attached
[pid  4376] fsconfig(5, FSCONFIG_SET_STRING, "delegate_cmds", "any", 0) = 0
[pid  4376] fsconfig(5, FSCONFIG_SET_STRING, "delegate_maps", "any", 0) = 0
[pid  4376] fsconfig(5, FSCONFIG_SET_STRING, "delegate_progs", "any", 0) = 0
[pid  4376] fsconfig(5, FSCONFIG_SET_STRING, "delegate_attachs", "any", 0) = 0
[pid  4376] fsconfig(5, FSCONFIG_CMD_CREATE, NULL, NULL, 0) = -1 EPERM (Operation not permitted)
fsconfig: Operation not permitted
```

**Comment by teknoraver** [comment]
@yuwata same sample but smaller, no BPF code, just filesystem API:

https://gist.github.com/teknoraver/d92edf01a5ffbcabc6db3b640aa9666a

File: src/basic/mountpoint-util.c (hunk 3 above)
Comment (yuwata) [reply src/basic/mountpoint-util.c]: Moved to core/namespace.c, but it is also used in test. So, cannot be static.

**Comment by yuwata** [comment]
@YHNdnzj Thank you for the review.
@teknoraver Thank you for the sample code.
Force pushed another version. PTAL.

**Comment by teknoraver** [comment]
With kernel 6.8 it still exits with status=226/NAMESPACE.
Shouldn't see the unsupported message on first usage with `journalctl -p 0..6 |grep PrivateBPF`?

**Comment by teknoraver** [comment]
I added the two unshares and now I have the error messages:
```
root@H:~# journalctl |grep -i -e BPFFS -e FSCONFIG
Jul 16 20:31:56 H (grep)[2931]: run-rca91df63117645758f9ba21bf8cef780.service: Successfully forked off '(sd-bpffs-check)' as PID 2935.
Jul 16 20:31:56 H (sd-bp[2935]: run-rca91df63117645758f9ba21bf8cef780.service: Failed to FSCONFIG_CMD_CREATE for bpffs: Operation not permitted
Jul 16 20:31:56 H (grep)[2931]: run-rca91df63117645758f9ba21bf8cef780.service: (sd-bpffs-check) failed with exit status 1.
Jul 16 20:31:56 H (grep)[2931]: run-rca91df63117645758f9ba21bf8cef780.service: bpffs helper exited with error: Operation not permitted
```

**Comment by teknoraver** [comment]
Also, the check is done every time instead of just once:
```
root@H:~# journalctl |grep -i -e BPFFS -e FSCONFIG
Jul 16 20:33:50 H (grep)[444]: run-red70a32abea545c19861e3bfce059a31.service: Successfully forked off '(sd-bpffs-check)' as PID 445.
Jul 16 20:33:50 H (sd-bp[445]: run-red70a32abea545c19861e3bfce059a31.service: Failed to FSCONFIG_CMD_CREATE for bpffs: Operation not permitted
Jul 16 20:33:50 H (grep)[444]: run-red70a32abea545c19861e3bfce059a31.service: (sd-bpffs-check) failed with exit status 1.
Jul 16 20:33:50 H (grep)[444]: run-red70a32abea545c19861e3bfce059a31.service: bpffs helper exited with error: Operation not permitted
Jul 16 20:34:00 H (true)[1339]: run-ra532721e00094449bff51f6d80c723e6.service: Successfully forked off '(sd-bpffs-check)' as PID 1340.
Jul 16 20:34:00 H (sd-bp[1340]: run-ra532721e00094449bff51f6d80c723e6.service: Failed to FSCONFIG_CMD_CREATE for bpffs: Operation not permitted
Jul 16 20:34:00 H (true)[1339]: run-ra532721e00094449bff51f6d80c723e6.service: (sd-bpffs-check) failed with exit status 1.
Jul 16 20:34:00 H (true)[1339]: run-ra532721e00094449bff51f6d80c723e6.service: bpffs helper exited with error: Operation not permitted
Jul 16 20:34:14 H (true)[1648]: run-r5eec4a39698e4942924c77b6aaa1aa4b.service: Successfully forked off '(sd-bpffs-check)' as PID 1649.
Jul 16 20:34:14 H (sd-bp[1649]: run-r5eec4a39698e4942924c77b6aaa1aa4b.service: Failed to FSCONFIG_CMD_CREATE for bpffs: Operation not permitted
Jul 16 20:34:14 H (true)[1648]: run-r5eec4a39698e4942924c77b6aaa1aa4b.service: (sd-bpffs-check) failed with exit status 1.
Jul 16 20:34:14 H (true)[1648]: run-r5eec4a39698e4942924c77b6aaa1aa4b.service: bpffs helper exited with error: Operation not permitted
Jul 16 20:34:20 H (true)[1832]: run-r625a77d93db94028895ccaf492556b53.service: Successfully forked off '(sd-bpffs-check)' as PID 1843.
Jul 16 20:34:20 H (sd-bp[1843]: run-r625a77d93db94028895ccaf492556b53.service: Failed to FSCONFIG_CMD_CREATE for bpffs: Operation not permitted
Jul 16 20:34:20 H (true)[1832]: run-r625a77d93db94028895ccaf492556b53.service: (sd-bpffs-check) failed with exit status 1.
Jul 16 20:34:20 H (true)[1832]: run-r625a77d93db94028895ccaf492556b53.service: bpffs helper exited with error: Operation not permitted
Jul 16 20:34:55 H (grep)[4373]: run-rb334b68b15d645abb29fbf62fde99928.service: Successfully forked off '(sd-bpffs-check)' as PID 4374.
Jul 16 20:34:55 H (sd-bp[4374]: run-rb334b68b15d645abb29fbf62fde99928.service: Failed to FSCONFIG_CMD_CREATE for bpffs: Operation not permitted
Jul 16 20:34:55 H (grep)[4373]: run-rb334b68b15d645abb29fbf62fde99928.service: (sd-bpffs-check) failed with exit status 1.
Jul 16 20:34:55 H (grep)[4373]: run-rb334b68b15d645abb29fbf62fde99928.service: bpffs helper exited with error: Operation not permitted
```

**Comment by teknoraver** [comment]
Same sample code works fine with Debian and a 6.8  vanilla kernel
```
root@debian64:~# uname -a
Linux debian64 6.8.0-kvm #8 SMP Thu Jul 17 12:59:54 CEST 2025 x86_64 GNU/Linux

root@debian64:~# strace -f -e fsopen,fsconfig,fspick,fsmount,move_mount,unshare ./bpffs
strace: Process 375 attached
[pid   374] unshare(CLONE_NEWUSER)      = 0
[pid   374] unshare(CLONE_NEWNS)        = 0
[pid   374] fsopen("bpf", FSOPEN_CLOEXEC) = 5
[pid   375] fsconfig(5, FSCONFIG_SET_STRING, "delegate_cmds", "any", 0) = 0
[pid   375] fsconfig(5, FSCONFIG_SET_STRING, "delegate_maps", "any", 0) = 0
[pid   375] fsconfig(5, FSCONFIG_SET_STRING, "delegate_progs", "any", 0) = 0
[pid   375] fsconfig(5, FSCONFIG_SET_STRING, "delegate_attachs", "any", 0) = 0
[pid   375] fsconfig(5, FSCONFIG_CMD_CREATE, NULL, NULL, 0) = 0
[pid   374] fsmount(5, 0, 0)            = 6
[pid   375] +++ exited with 0 +++
```
Probably it's something specific to the Ubuntu kernel or in the distro setup?

**Comment by bluca** [comment]
Double check apparmor and similar, it might be getting in the way

**Comment by teknoraver** [comment]
Nope, that Ubuntu kernel gives that error even on a minimal Debian setup.
I bisected the Ubuntu kernel and this is the commit which introduced the error:

https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/noble/commit/?id=010c10bb7f585a58d8f5d963a688cd297e9d0a57

**Comment by yuwata** [comment]
Hmm, so is the issue is a ubuntu kernel specific? Then, there is mostly nothing we should do?
Maybe, to gracefully downgrade the setting for the old kernel, it is sufficient to call fsopen() and fsconfig() without sending bpffs fd (and even without clone)?

What is the minimal kernel version for PrivateBPF= and related delegation options?

**Comment by bluca** [comment]
The issue appears on Ubuntu for some reason, but that kernel commit is in mainline and was merged in v6.11

**Comment by yuwata** [comment]
> The issue appears on Ubuntu for some reason, but that kernel commit is in mainline and was merged in v6.11

Then, maybe the issue is already fixed in the mainline after that? Not sure, just my guess.

**Comment by teknoraver** [comment]
I can't find any commit with a fixtag referencing that one.
That commit is a backport from kernel 6.11 (https://github.com/torvalds/linux/commit/e1c5ae59c0f22f7fe5c07fb5513a29e4aad868c9), but all vanilla kernels from 6.8 to 6.11 work fine.
It could be an Ubuntu bug or a bad backport.
I'm investigating it.

**Comment by bluca** [comment]
it doesn't, still fails

**Comment by yuwata** [comment]
> I can't find any commit with a fixtag referencing that one. That commit is a backport from kernel 6.11 ([torvalds/linux@e1c5ae5](https://github.com/torvalds/linux/commit/e1c5ae59c0f22f7fe5c07fb5513a29e4aad868c9)), but all vanilla kernels from 6.8 to 6.11 work fine. It could be an Ubuntu bug or a bad backport. I'm investigating it.

Yeah, bad backport is plausible.

**Comment by yuwata** [comment]
MEMO for me:
BPF token delegation: https://github.com/torvalds/linux/commit/40bba140c60fbb3ee8df6203c82fbd3de9f19d95 (v6.8)

**Comment by yuwata** [comment]
> it doesn't, still fails

But that sounds a bug in the ubuntu kernel? I have not checked, but at least @teknoraver says so.

**Comment by yuwata** [comment]
@teknoraver BTW, currently, even if no bpf token delegation option is specified, we always set delegation, and that requires kernel v6.8 or newer. Is it a right approach? Maybe we should support PrivateBPF=yes without delegation for older kernels? Is it meaningless? WDYT?

**Comment by bluca** [comment]
Sure, but it's still triggered by a new code change, we can't just ignore it

**Comment by yuwata** [comment]
> Sure, but it's still triggered by a new code change, we can't just ignore it

I do not think we should merge it soon, but if the issue is really caused by a bad backport, there is nothing we should do about the issue.

**Comment by bluca** [comment]
But this can be detected that it doesn't work, and the feature skipped gracefully, instead of hard failing

**Comment by yuwata** [comment]
Hmm, I will re-consider...

**Comment by keszybz** [comment]
Please see https://github.com/systemd/systemd/pull/38255. It rearranges the code a bit.

**Comment by yuwata** [comment]
Pushed another approach. I've not tested yet.

**Comment by teknoraver** [comment]
I debugged the error and digged throug the Ubuntu repo, this is what I found:

BPF Tokens were merged in 6.8 https://github.com/torvalds/linux/commit/40bba140c60fbb3ee8df6203c82fbd3de9f19d95
But still in the 6.8 merge window they were reverted in https://github.com/torvalds/linux/commit/d17aff807f845cf93926c28705216639c7279110

The reason why the test code succeeds on a vanilla 6.8 kernel is because unknown mount options set via fsconfig() are just ignored:
```
[pid   482] fsconfig(5, FSCONFIG_SET_STRING, "delegate_cmds", "any", 0) = 0
[pid   482] fsconfig(5, FSCONFIG_SET_STRING, "delegate_maps", "any", 0) = 0
[pid   482] fsconfig(5, FSCONFIG_SET_STRING, "delegate_progs", "any", 0) = 0
[pid   482] fsconfig(5, FSCONFIG_SET_STRING, "delegate_attachs", "any", 0) = 0
[pid   482] fsconfig(5, FSCONFIG_SET_STRING, "unknown_option", "random_value", 0) = 0
[pid   482] fsconfig(5, FSCONFIG_SET_STRING, "qwerty", "123456", 0) = 0
[pid   482] fsconfig(5, FSCONFIG_CMD_CREATE, NULL, NULL, 0) = 0
```

To make things again more confusing, Ubuntu backported in its 6.8 tree https://github.com/torvalds/linux/commit/e1c5ae59c0f22f7fe5c07fb5513a29e4aad868c9 which disallowed some fsconfig() calls from an user namespace.
This red herring disguised me.

Then, BPF tokens were merged back again in 6.9 https://github.com/torvalds/linux/commit/6fe01d3cbb924a72493eb3f4722dfcfd1c194234 with a chunk which allows bpffs to be mounted from an user namespace:
```patch
 static struct file_system_type bpf_fs_type = {
        .owner          = THIS_MODULE,
        .name           = "bpf",
        .init_fs_context = bpf_init_fs_context,
        .parameters     = bpf_fs_parameters,
-       .kill_sb        = kill_litter_super,
+       .kill_sb        = bpf_kill_super,
+       .fs_flags       = FS_USERNS_MOUNT,
 };
```

So, we can safely assume that BPF tokens are supported by kernel 6.9 and later.

**Comment by teknoraver** [comment]
@yuwata it works now with your latest push

File: src/core/exec-invoke.c [hunk 5]
```diff
@@ -2270,20 +2270,55 @@ static int setup_private_users_child(int unshare_ready_fd, const char *uid_map,
         return 0;
 }
 
+static int bpffs_helper(const ExecContext *c, int socket_fd) {
+        char number[STRLEN("0x") + sizeof(c->bpf_delegate_commands) * 2 + 1];
+
+        assert(c);
```
Comment (bluca) [inline src/core/exec-invoke.c:2274]: assert needs to go before the definition above

File: src/core/namespace.c [hunk 6]
```diff
@@ -1832,6 +1833,22 @@ static int apply_one_mount(
...
         log_debug("Applying namespace mount on %s", mount_entry_path(m));
 
+        if (m->mode == MOUNT_BPFFS) {
+                r = mount_bpffs(m, p->bpffs_pidref, p->bpffs_socket_fd, p->bpffs_errno_pipe);
+                if (r >= 0 ||
+                    (!ERRNO_IS_NEG_NOT_SUPPORTED(r) && /* old kernel? */
+                     !ERRNO_IS_NEG_PRIVILEGE(r)))      /* ubuntu kernel bug? See issue #38225 */
+                        return r;
+
+                if (!m->ignore) {
```
Comment (bluca) [inline src/core/namespace.c]: did you mean `if (m->ignore)` ?

File: src/core/exec-invoke.c (hunk 5 above)
Comment (keszybz) [reply src/core/exec-invoke.c:2274]: I don't think it does. `sizeof` operates on the type, at compilation time, not on the specific pointer at runtime.

Comment (keszybz) [reply src/core/exec-invoke.c:2274]: Yeah, looking at the assembly, without optimization, gcc just creates space on the stack. So I think this is fine.

**Review by keszybz — APPROVED** [review]
LGTM, apart from the one issue that Luca noticed.

File: src/core/exec-invoke.c (hunk 5 above)
Comment (bluca) [reply src/core/exec-invoke.c:2274]: ok, interesting

File: src/core/namespace.c (hunk 6 above)
Comment (yuwata) [reply src/core/namespace.c]: This is hackish, but correct.
- `m->ignore` is true: we have ProtectKernelTunables=yes, so we need to fallback.
- `m->ignore` is false: we do not have ProtectKernelTunables=yes, so we should skip the mount.

I will comment that in the code later.

File: src/core/exec-invoke.c (hunk 5 above)
Comment (yuwata) [reply src/core/exec-invoke.c:2274]: Interesting, but will move the assertion at the beginning of the function.

File: src/core/namespace.c (hunk 6 above)
Comment (yuwata) [reply src/core/namespace.c]: Reconsidering about that, the condition is swapped in the revised version. See
https://github.com/systemd/systemd/compare/78071eb9a40431f98c6e73e5bcd9b0b93b109337..a6738260036b0e88b0776490d3f8ab6c3bc7bbac

**Comment by yuwata** [comment]
@bluca @keszybz Thank you for review. Upgrading the green label.

@teknoraver Thank you for investigating the root cause of the issue!

**Comment by teknoraver** [comment]
And I confirm that it still works with latest kernel
```
[root@localhost ~]# systemd-run --wait -p PrivateUsers=yes -p PrivateMounts=yes -p DelegateNamespaces=mnt -p PrivateBPF=yes -S
Running as unit: run-p718-i1018.service
Press ^] three times within 1s to disconnect TTY.

bash-5.2# mount |grep bpf
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
none on /sys/fs/bpf type bpf (rw,relatime)
```

**Review by bluca — APPROVED** [review]
Nice stuff, the tests are passing now
