### PR TITLE
namespace-util: handle -ENOSPC by userns_acquire() gracefully in is_idmapping_supported()

### LINKED ISSUE #35311: "Failed to set up special execution directory: No space left on device" w/user namespaces disabled
### systemd version the issue has been seen with

257~rc2-3

### Used distribution

Debian testing

### Linux kernel version used

6.11.7-amd64 (or 6.11.9-amd64)

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Services with `RuntimeDirectory`, `StateDirectory`, etc. settings starting properly with user namespaces disabled.

### Unexpected behaviour you saw

With user namespaces disabled, services with `RuntimeDirectory`, `StateDirectory`, etc. settings failed to start with error messages like
```
systemd-logind.service: Failed to set up special execution directory in /run: No space left on device
systemd-logind.service: Failed at step RUNTIME_DIRECTORY spawning /usr/lib/systemd/systemd-logind: No space left on device
```
despite having ample space in `/run` and `/var`.

### Steps to reproduce the problem

Attempt to run an affected `systemd` version with user namespaces disabled, as with Debian's `hardening-runtime` package installed -- it ships a `sysctl` configuration file reading in part
```python
# Disable User Namespaces, as it opens up a large attack surface to unprivileged users.
# On Debian kernel.unprivileged_userns_clone is set to 0 by default as well
user.max_user_namespaces = 0
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemd[1]: gssproxy.service: Will spawn child (service_enter_start): /usr/sbin/gssproxy
systemd[1]: gssproxy.service: Passing 0 fds to service
systemd[1]: gssproxy.service: About to execute: /usr/sbin/gssproxy -D
systemd[1]: Serializing sd-executor-state to memfd.
systemd[1]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
systemd[1]: gssproxy.service: Forked /usr/sbin/gssproxy as 881778 (via CLONE_INTO_CGROUP)
systemd[1]: Closing set fd 154 (socket:[11489])
systemd[1]: Closing set fd 204 (socket:[1244032])
systemd[1]: Closing set fd 207 (socket:[11487])
systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/gssproxy_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=19059 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/gssproxy_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=19060 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
systemd[1]: gssproxy.service: Changed failed -> start
systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=19061 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
systemd[1]: Starting gssproxy.service - GSSAPI Proxy Daemon...
systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/gssproxy_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=19062 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/gssproxy_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=19063 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/job/84662 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=19064 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
systemd[1]: Got message type=method_call sender=:1.360 destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=GetUnit  cookie=4 reply_cookie=0 signature=s error-name=n/a error-message=n/a
systemd[1]: Sent message type=method_return sender=n/a destination=:1.360 path=n/a interface=n/a member=n/a cookie=19065 reply_cookie=4 signature=o error-name=n/a error-message=n/a
systemd[1]: Got message type=method_call sender=:1.360 destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/gssproxy_2eservice interface=org.freedesktop.DBus.Properties member=Get  cookie=5 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
systemd[1]: Sent message type=method_return sender=n/a destination=:1.360 path=n/a interface=n/a member=n/a cookie=19066 reply_cookie=5 signature=v error-name=n/a error-message=n/a
(gssproxy)[881778]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
(gssproxy)[881778]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
(gssproxy)[881778]: Failed to fork off '(sd-mkuserns)': No space left on device
(gssproxy)[881778]: Failed to fork process (sd-mkuserns): No space left on device
(gssproxy)[881778]: ID-mapping supported namespace acquire failed for '/var/lib/gssproxy/clients' : No space left on device
(gssproxy)[881778]: Unable to determine if ID mapping is supported on mount '/var/lib/gssproxy/clients': No space left on device
(gssproxy)[881778]: gssproxy.service: Failed to set up special execution directory in /var/lib: No space left on device
(gssproxy)[881778]: gssproxy.service: Failed at step STATE_DIRECTORY spawning /usr/sbin/gssproxy: No space left on device
```

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for edae62120f13b24d51812d1d7c0ab24acb420305.
Fixes #35311.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

File: src/basic/namespace-util.c [hunk 1]
```diff
@@ -529,7 +529,9 @@ int is_idmapping_supported(const char *path) {
                 return r;
 
         userns_fd = userns_acquire(uid_map, gid_map);
-        if (ERRNO_IS_NEG_NOT_SUPPORTED(userns_fd) || ERRNO_IS_NEG_PRIVILEGE(userns_fd))
+        if (ERRNO_IS_NEG_NOT_SUPPORTED(userns_fd) ||
+            ERRNO_IS_NEG_PRIVILEGE(userns_fd) ||
+            userns_fd == -ENOSPC) /* ENOSPC means user.max_user_namespaces is reached */
```
Comment (poettering) [inline src/basic/namespace-util.c]: hmm, it's kinda ugly to just treat ENOSPC the same as not supported, after all it might just be that some other code took all userns away that were available and hence userns are supported, just none available right now.

however, i don#t really see a better strategy here. hence maybe it's ok to fix this like this. however: please add an explicit log message for this case, so that this is reasonable to debug. i.e. some message on ENOSPC that explicitly suggests `user.max_user_namespaces` being exhausted or maybe even zero

Comment (yuwata) [reply src/basic/namespace-util.c]: Yeah, exactly. The check is quite racy about ENOSPC error. But I neither find a better way.
I will add a debugging log.
