### PR TITLE
systemctl: fix memleak

### LINKED ISSUE #36178: There is a memory leak in systemctl
### systemd version the issue has been seen with

systemd 258~devel

### Used distribution

Fedora 42

### Linux kernel version used

6.13.0-0.rc7.20250114gitc45323b7560e.56.fc42.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

There should not be a memory leak.

### Unexpected behaviour you saw

Memory leak in the systemctl component.

### Steps to reproduce the problem

While executing one of the integration tests in the pipeline (PR stage), a memory leak was observed in systemctl.
[22532](https://github.com/systemd/systemd/pull/22532).

[Testlink](https://github.com/systemd/systemd/actions/runs/12965789993/job/36165890082?pr=22532)

Logs:
```
[   51.232708] TEST-88-RESOLVED-MDNS.sh[1269]: ==144==ERROR: LeakSanitizer: detected memory leaks
[   51.232708] TEST-88-RESOLVED-MDNS.sh[1269]: Direct leak of 9 byte(s) in 1 object(s) allocated from:
[   51.248708] TEST-88-RESOLVED-MDNS.sh[1269]:     #0 0x7f3df30bc7ee in strdup (/usr/lib/clang/19/lib/x86_64-redhat-linux-gnu/libclang_rt.asan.so+0xbc7ee) (BuildId: 1afad417992f0eb55159b853d8ca03bff039a365)
[   51.248708] TEST-88-RESOLVED-MDNS.sh[1269]:     #1 0x7f3df29c3be1 in sd_bus_get_property_string /usr/src/debug/systemd/src/libsystemd/sd-bus/bus-convenience.c:518:13
[   51.248708] TEST-88-RESOLVED-MDNS.sh[1269]:     #2 0x7f3df236fbf5 in bus_get_property_string /usr/src/debug/systemd/src/shared/bus-locator.c:167:16
[   51.248708] TEST-88-RESOLVED-MDNS.sh[1269]:     #3 0x56322152de8d in verb_is_system_running /usr/src/debug/systemd/src/systemctl/systemctl-is-system-running.c:59:13
[   51.248708] TEST-88-RESOLVED-MDNS.sh[1269]:     #4 0x7f3df26d8ebc in dispatch_verb /usr/src/debug/systemd/src/shared/verbs.c:126:16
[   51.248708] TEST-88-RESOLVED-MDNS.sh[1269]:     #5 0x56322158ef98 in run /usr/src/debug/systemd/src/systemctl/systemctl.c:1314:21
[   51.248708] TEST-88-RESOLVED-MDNS.sh[1269]:     #6 0x56322158ef98 in main /usr/src/debug/systemd/src/systemctl/systemctl.c:1376:1
[   51.248708] TEST-88-RESOLVED-MDNS.sh[1269]:     #7 0x7f3df1e105f4 in __libc_start_call_main (/lib64/libc.so.6+0x35f4) (BuildId: be08f175fb99297415ecc80c9ee7a33b56cbd355)
[   51.248708] TEST-88-RESOLVED-MDNS.sh[1269]:     #8 0x7f3df1e106a7 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x36a7) (BuildId: be08f175fb99297415ecc80c9ee7a33b56cbd355)
[   51.248708] TEST-88-RESOLVED-MDNS.sh[1269]:     #9 0x56322151aba4  (/usr/bin/systemctl+0x37ba4) (BuildId: f51dccae0424aafdad031c7dc[414](https://github.com/systemd/systemd/actions/runs/12965789993/job/36165890082?pr=22532#step:12:415)de649bd530be)
[   51.248708] TEST-88-RESOLVED-MDNS.sh[1269]: SUMMARY: AddressSanitizer: 9 byte(s) leaked in 1 allocation(s).

Found 1 sanitizer issues (0 internal, 1 asan, 0 ubsan, 0 msan).
```
### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug introduced by adb6cd9be2b7e9e614d2b5835c7b70cf8eacc852.

Fixes #36178.

### CODE REVIEW

File: src/systemctl/systemctl-is-system-running.c [hunk 1]
```diff
@@ -66,13 +66,19 @@ int verb_is_system_running(int argc, char *argv[], void *userdata) {
         }
 
         if (arg_wait && STR_IN_SET(state, "initializing", "starting")) {
+                /* The signal handler will allocate memory and assign to 'state', hence need to free previous
+                 * one before enterling the event loop. */
```
Comment (vcaputo) [inline src/systemctl/systemctl-is-system-running.c]: nit: entering

Comment (yuwata) [reply src/systemctl/systemctl-is-system-running.c]: Ouch. Fixed.

**Review by bluca — APPROVED** [review]
