### PR TITLE
sd-device-monitor: introduce sd_device_monitor_get_events() and _get_timeout()

### LINKED ISSUE #34094: sd_device_monitor should get trivial get_events() + get_timeout() functions too
### systemd version the issue has been seen with

git main

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

See my comments on: https://github.com/systemd/systemd/pull/33032#issuecomment-2305217592

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Follow-ups for #33032.
Closes #34094.

### CODE REVIEW

File: src/libsystemd/sd-device/test-sd-device-monitor.c [hunk 1]
```diff
@@ -377,8 +378,13 @@ TEST(sd_device_monitor_receive) {
         ASSERT_OK(device_monitor_send(monitor_server, &sa, device));
 
         ASSERT_OK(fd = sd_device_monitor_get_fd(monitor_client));
+        ASSERT_OK(event = sd_device_monitor_get_events(monitor_client));
+        ASSERT_EQ(event, (int) EPOLLIN);
+        ASSERT_OK(sd_device_monitor_get_timeout(monitor_client, &timeout));
+        ASSERT_EQ(timeout, USEC_INFINITY);
```
Comment (poettering) [inline src/libsystemd/sd-device/test-sd-device-monitor.c]: please move these two calls into the loop.

**Comment by poettering** [comment]
thanks, lgtm. just one minor fix.

File: src/libsystemd/sd-device/test-sd-device-monitor.c [hunk 2]
```diff
@@ -377,20 +378,25 @@ TEST(sd_device_monitor_receive) {
...
+
         for (;;) {
-                r = fd_wait_for_event(fd, POLLIN, 10 * USEC_PER_SEC);
+                r = fd_wait_for_event(fd, event, 10 * USEC_PER_SEC);
```
Comment (poettering) [inline src/libsystemd/sd-device/test-sd-device-monitor.c]: maybe change last arg to `MAX(10 * USEC_PER_SEC, timeout)`? it doesn't change behaviour, but looks more correct...
