### PR TITLE
udev: gracefully handle ENODEV or friends in opening device node

### LINKED ISSUE #38033: (udev-worker): sr0: Failed to open device node: Read-only file system
### systemd version the issue has been seen with

git main

### Used distribution

openSUSE Tumbleweed

### Linux kernel version used

6.14.1-1-default

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

qemu/kvm with sata cdrom, no `Failed to open device node` errors on the journal.

### Unexpected behaviour you saw

cdrom with iso attached to `/dev/sr0`:

```
[    3.168020] localhost kernel: sr 1:0:0:0: [sr0] scsi3-mmc drive: 4x/4x cd/rw xa/form2 tray
[    3.186227] localhost kernel: cdrom: Uniform CD-ROM driver Revision: 3.20
[    3.186247] localhost kernel: usb 1-4: new full-speed USB device number 3 using xhci_hcd
[    3.186299] localhost kernel: sr 1:0:0:0: Attached scsi CD-ROM sr0
[    3.274076] localhost (udev-worker)[393]: sr0: Failed to open device node: Read-only file system
```

### Steps to reproduce the problem

Bisected to 1abb592f2f886913492e4967cc96816c167177a9
CC @yuwata 

Since 1abb592f2f886913492e4967cc96816c167177a9, the uaccess builtin opens devices using `sd_device_open()` with `O_RDWR`, and that should not be necessary just to set ACLs (in fact, it should not be necessary to open the device at all just to set xattr).

The problem is that some devices cannot be opened r/w, so the uaccess builtin fails. E.g., `/dev/srX`, the cdrom driver returns `EROFS` in this case (https://github.com/torvalds/linux/blob/66701750d5565c574af42bef0b789ce0203e3071/drivers/cdrom/cdrom.c#L1167-L1168):

```
[    5.505182] localhost (udev-worker)[716]: sr0: Running built-in command "uaccess"
[    5.538707] localhost (udev-worker)[716]: sr0: Failed to open device node: Read-only file system
[    5.538880] localhost (udev-worker)[716]: sr0: Failed to run built-in command "uaccess", ignoring: Read-only file system
```

But, after replacing `O_RDWR` with `O_RDONLY`, it can also happen that the uaccess builtin runs before the cdrom module is loaded, returning `ENXIO` in that case, although it runs successfully later after the module is already loaded.

```
[   59.232289] localhost (udev-worker)[2100]: sr0: Running built-in command "uaccess"
[   59.232482] localhost (udev-worker)[2100]: sr0: Failed to open device node: No such device or address
[   59.232495] localhost (udev-worker)[2100]: sr0: Failed to run built-in command "uaccess", ignoring: No such device or address
...
[   59.275427] localhost (udev-worker)[2100]: sr0: Running built-in command "uaccess"
[   59.275722] localhost (udev-worker)[2100]: sr0: Running command "/usr/sbin/pktsetup -i -d 11:0"
```

Also, after handling this case, I found errors with `/dev/dri/card0` returning `ENODEV`:

```
[    2.685476] localhost (udev-worker)[397]: card0: Running built-in command "uaccess"
[    2.685802] localhost (udev-worker)[397]: card0: Failed to open device node: No such device
[    2.685806] localhost (udev-worker)[397]: card0: Failed to run built-in command "uaccess", ignoring: No such device
```

And after handling this case, now `ENOENT`:

```
[    2.944910] localhost (udev-worker)[382]: card0: Running built-in command "uaccess"
[    2.945619] localhost (udev-worker)[382]: card0: Failed to open device node: No such file or directory
[    2.946019] localhost (udev-worker)[382]: card0: Failed to run built-in command "uaccess", ignoring: No such file or directory
```

So far so good, but I don't know if other special cases should be handled, or if this part should be rewritten without `sd_device_open()`.

```patch
diff --git a/src/udev/udev-builtin-uaccess.c b/src/udev/udev-builtin-uaccess.c
index 9a9ba43b1c..65d9652a5b 100644
--- a/src/udev/udev-builtin-uaccess.c
+++ b/src/udev/udev-builtin-uaccess.c
@@ -120,9 +120,12 @@ static int builtin_uaccess(UdevEvent *event, int argc, char *argv[]) {
         if (!logind_running())
                 return 0;
 
-        _cleanup_close_ int fd = sd_device_open(dev, O_CLOEXEC|O_RDWR);
+        _cleanup_close_ int fd = sd_device_open(dev, O_CLOEXEC|O_RDONLY);
         if (fd < 0)
-                return log_device_error_errno(dev, fd, "Failed to open device node: %m");
+                return log_device_full_errno(dev,
+                                             IN_SET(errno, ENOENT, ENXIO, ENODEV) ? LOG_DEBUG : LOG_ERR,
+                                             fd,
+                                             "Failed to open device node: %m");
 
         const char *seat;
         r = device_get_seat(dev, &seat);
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #38033.

### CODE REVIEW

File: src/udev/cdrom_id/cdrom_id.c [hunk 1]
```diff
@@ -966,8 +967,10 @@ static int run(int argc, char *argv[]) {
                 return r;
 
         r = open_drive(&c);
+        if (ERRNO_IS_NEG_DEVICE_ABSENT(r))
+                return 0;
```
Comment (poettering) [inline src/udev/cdrom_id/cdrom_id.c:971]: i think debug logging would always be advisable?

Comment (poettering) [reply src/udev/cdrom_id/cdrom_id.c:971]: ah, ignor me, i see open_drive() already does that.

File: src/udev/udev-node.c [hunk 2]
```diff
@@ -735,7 +735,7 @@ int static_node_apply_permissions(
 
         node_fd = open(devnode, O_PATH|O_CLOEXEC);
         if (node_fd < 0) {
-                if (errno != ENOENT)
+                if (!ERRNO_IS_DEVICE_ABSENT(errno))
                         return log_error_errno(errno, "Failed to open %s: %m", devnode);
                 return 0;
```
Comment (poettering) [inline src/udev/udev-node.c]: maybe add debug logging here?

**Comment by yuwata** [comment]
@poettering Thank you for the review. Addressed the request. Upgrading the green label.
