### PR TITLE
tree-wide: allow building with -Wgnu-variable-sized-type-not-at-end option for clang

### LINKED ISSUE #37497: Subclasses of struct ObjectHeader does not comply with Wflex-array-member-not-at-end
### systemd version the issue has been seen with

latest version on main branch

### Used distribution

irrelevant (static checker report)

### Linux kernel version used

irrelevant (static checker report)

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

Encouraged by commit c1b0e39ffd76ca14960d3253286d9590c36f00f2, I deside to manually reopen #35929

As illustrated in #35929, flexible array members are used in the middle of several structs in file src/libsystemd/sd-journal/journal-def.h.

Due to commit c1b0e39ffd76ca14960d3253286d9590c36f00f2 adds `-Werror=flex-array-member-not-at-end`, usages reported in #35929 will no longer build. Fortunately, no error message is generated currently due to a bug of GCC. When a typedef of a flexible array struct is declared before the struct definition being aliased, and used later in the middle of another struct, GCC will not report it.
(An [example comparison](https://godbolt.org/z/P1aYbY1j3) between GCC and Clang for this bug in GCC)

In this case, a type alias is declared on line 19
https://github.com/systemd/systemd/blob/a31edb4e71517e580ec2b2444ee0b6d8a9ba5274/src/libsystemd/sd-journal/journal-def.h#L19
The flexible array struct is defined later on line 55
https://github.com/systemd/systemd/blob/a31edb4e71517e580ec2b2444ee0b6d8a9ba5274/src/libsystemd/sd-journal/journal-def.h#L55-L61
And used in the middle of multiple subclasses, such as `DataObject` on line 64
https://github.com/systemd/systemd/blob/a31edb4e71517e580ec2b2444ee0b6d8a9ba5274/src/libsystemd/sd-journal/journal-def.h#L64

You can verify this issue by moving the typedef on line 19 below the definition of ObjectHeader. Besides, no matter the typedef is declared before or after the struct definition, Clang will always report this issue correctly, as shown in my GCC/Clang comparison.
The reason that Clang does not report currently is that it is manually disabled.
https://github.com/systemd/systemd/blob/a31edb4e71517e580ec2b2444ee0b6d8a9ba5274/meson.build#L483
I think this checker in Clang should be configured consistently with the one in GCC.

For the entire report of all usages in this file, please refer to #35929. 

### Unexpected behaviour you saw

In https://github.com/systemd/systemd/issues/35929#issuecomment-2578186279, @vcaputo considers that it is not a problem and I am wasting your time.

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for #36993.
Closes #37497.

### CODE REVIEW

File: src/libsystemd/sd-journal/journal-def.h [hunk 1]
```diff
@@ -57,7 +57,6 @@ struct ObjectHeader {
         uint8_t flags;
         uint8_t reserved[6];
         le64_t size;
-        uint8_t payload[];
```
Comment (keszybz) [inline src/libsystemd/sd-journal/journal-def.h:58]: The preceding fields have size that is a multiple of 8 bytes, so the end of `.size` is aligned, so offsetof(ObjectHeader, payload) == sizeof(ObjectHeader)`, good.

File: src/libsystemd/sd-journal/journal-def.h [hunk 2]
```diff
@@ -104,18 +104,12 @@ assert_cc(sizeof(struct FieldObject) == sizeof(struct FieldObject__packed));
...
+                        le64_t hash;                   \
+                } regular[0];                          \
                 struct {                               \
-                        dummy_t __empty_compact;       \
-                        struct {                       \
-                                le32_t object_offset;  \
-                        } compact[];                   \
-                };                                     \
+                        le32_t object_offset;          \
+                } compact[0];                          \
```
Comment (keszybz) [inline src/libsystemd/sd-journal/journal-def.h:113]: Hmm, this just just drop `dummy_t`, it also changes a flexible array member to a zero-length array member. If this is intentional, please mention it in the commit message.

File: src/libsystemd-network/dhcp-duid-internal.h [hunk 3]
```diff
@@ -37,17 +37,17 @@ struct duid {
                         /* DUID_TYPE_LLT */
                         be16_t htype;
                         be32_t time;
-                        uint8_t haddr[];
+                        uint8_t haddr[0]; /* struct duid is embedded in many structs, let's not use flex array. */
```
Comment (keszybz) [inline src/libsystemd-network/dhcp-duid-internal.h]: Hmm, flex arrays cannot be embedded in the middle of other structs because this is very error prone. By doing those changes here, we're defeating those protections that the compiler affords us. This make the code more error prone and seems like a step in the wrong direction.

Comment (keszybz) [reply src/libsystemd-network/dhcp-duid-internal.h]: So… if I drop that commit, I get the following:
```
../src/libsystemd-network/dhcp6-internal.h:67:22: warning: field 'duid' with variable sized type 'sd_dhcp_duid' (aka 'struct sd_dhcp_duid') not at the end of a struct or class is a GNU extension [-Wgnu-variable-sized-type-not-at-end]
   67 |         sd_dhcp_duid duid;
      |                      ^
```
and it comes from here:
```
struct sd_dhcp6_client {
        unsigned n_ref;

        int ifindex;
        char *ifname;

        struct in6_addr local_address;
        struct hw_addr_data hw_addr;
        uint16_t arp_type;

        sd_event *event;
        sd_event_source *receive_message;
        sd_event_source *timeout_resend;
        sd_event_source *timeout_expire;
        sd_event_source *timeout_t1;
        sd_event_source *timeout_t2;
        int event_priority;
        int fd;

        sd_device *dev;

        DHCP6State state;
        bool information_request;
        usec_t information_request_time_usec;
        usec_t information_refresh_time_usec;
        be32_t transaction_id;
        usec_t transaction_start;
        usec_t retransmit_time;
        uint8_t retransmit_count;

        bool iaid_set;
        DHCP6IA ia_na;
        DHCP6IA ia_pd;
        DHCP6RequestIA request_ia;
        sd_dhcp_duid duid;
        be16_t *req_opts;
        size_t n_req_opts;
        char *fqdn;
        char *mudurl;
        char **user_class;
        char **vendor_class;
        OrderedHashmap *extra_options;
        OrderedSet *vendor_options;
        bool rapid_commit;

        struct sd_dhcp6_lease *lease;

        sd_dhcp6_client_callback_t callback;
        void *userdata;
        sd_dhcp6_client_callback_t state_callback;
        void *state_userdata;
        bool send_release;
};
```
Maybe I'm missing something, but isn't this variable-length struct in the middle of the structure just asking for trouble?

Comment (keszybz) [reply src/libsystemd-network/dhcp-duid-internal.h]:
```
  263 |         r = sd_dhcp_duid_set(&client->duid, duid_type, duid, duid_len);
      |                               ~~~~~~  ^
```
??

File: src/libsystemd/sd-journal/journal-def.h (hunk 1 above)
Comment (YHNdnzj) [inline src/libsystemd/sd-journal/journal-def.h:58]: Hmm, this one seems a bit moot and the GNU extension actually makes sense IMO, since it clearly indicates where the data lies.

Comment (yuwata) [reply src/libsystemd/sd-journal/journal-def.h:58]: Thanks. Mentioned in the commit message.

Comment (yuwata) [reply src/libsystemd/sd-journal/journal-def.h:58]: But, that's mostly unused.

File: src/libsystemd/sd-journal/journal-def.h (hunk 2 above)
Comment (yuwata) [reply src/libsystemd/sd-journal/journal-def.h:113]: OK. Done.

File: src/libsystemd-network/dhcp-duid-internal.h (hunk 3 above)
Comment (yuwata) [reply src/libsystemd-network/dhcp-duid-internal.h]: I was lazy about moving all sd_dhcp_duid and sd_dhcp_client_id to end of each struct that contains them.
Now, they are moved to end of structs.

**Comment by yuwata** [comment]
@keszybz @YHNdnzj PTAL.

File: src/libsystemd-network/dhcp-duid-internal.h (hunk 3 above)
Comment (keszybz) [reply src/libsystemd-network/dhcp-duid-internal.h]: Hmm, after looking at this for a while, I think this is the wrong way to handle this. The essential problem that we have is that we have a "flexible length structure" which we use as a fixed-length structure. For example, we allocate the structures calling `new`, which uses `sizeof`. Either the size of the structure is declared large enough to cover all use cases, or it's not and we'll do a buffer overrun later. So it's conceptually incompatible to use flex arrays and allocations based on sizeof. 

In fact, I think the problem is not that sd_dhcp_duid is in the middle, but that it is declared using a flex array. In `dhcp-duid-internal.h` we have:
```C
struct duid {
        be16_t type;
        union {
                struct {
                        /* DUID_TYPE_LLT */
                        be16_t htype;
                        be32_t time;
                        uint8_t haddr[];
                } _packed_ llt;
                struct {
                        /* DUID_TYPE_EN */
                        be32_t pen;
                        uint8_t id[];
                } _packed_ en;
                struct {
                        /* DUID_TYPE_LL */
                        be16_t htype;
                        uint8_t haddr[];
                } _packed_ ll;
                struct {
                        /* DUID_TYPE_UUID */
                        sd_id128_t uuid;
                } _packed_ uuid;
                uint8_t data[MAX_DUID_DATA_LEN];
        };
} _packed_;
```
I think we should put fixed sized in each of those flex arrays. E.g. `harrd[CONST_MAX(ETH_ALEN, INFINIBAND_ALEN)]`.

Then we stop pretending that this is a struct with an arbitrary size and it can be embedded anywhere.

File: src/libsystemd/sd-journal/journal-authenticate.c [hunk 4]
```diff
@@ -284,7 +284,7 @@ int journal_file_hmac_put_object(JournalFile *f, ObjectType type, Object *o, uin
         } else if (type > OBJECT_UNUSED && o->object.type != type)
                 return -EBADMSG;
 
-        sym_gcry_md_write(f->hmac, o, offsetof(ObjectHeader, payload));
+        sym_gcry_md_write(f->hmac, o, sizeof(ObjectHeader));
```
Comment (poettering) [inline src/libsystemd/sd-journal/journal-authenticate.c]: i really dislike this btw, because it suggests the size of the prefix would matter instead of the offset of the suffix. yes, of course we are careful, and don't risk the alignment issues, but i think conceptually this is a step back, as we emphasize the wrong thing here in the code.

File: src/libsystemd/sd-journal/journal-def.h (hunk 1 above)
Comment (poettering) [reply src/libsystemd/sd-journal/journal-def.h:58]: why not just keep this with [0] at least? it would alleviate our concerns but also address the issue at hand?

File: src/libsystemd/sd-journal/journal-def.h [hunk 5]
```diff
@@ -102,18 +102,12 @@ assert_cc(sizeof(struct FieldObject) == sizeof(struct FieldObject__packed));
...
         } items;                                       \
```
Comment (poettering) [inline src/libsystemd/sd-journal/journal-def.h:114]: so here you went for the [0] approach, which suggests the payload[0] in the previous commit should also be fine, no?

Comment (poettering) [reply src/libsystemd/sd-journal/journal-def.h:114]: kinda would prefer if there was a comment here, that explains briefly what the point of the [0] is. i.e. something like `/* this is an array; since we are not allowed to place a variable sized array in a union, we just zero-size it, even if it is generally longer */`

File: src/libsystemd/sd-event/event-source.h [hunk 6]
```diff
@@ -237,4 +233,9 @@ struct inotify_data {
         /* A linked list of all inotify objects with data already read, that still need processing. We keep this list
          * to make it efficient to figure out what inotify objects to process data on next. */
         LIST_FIELDS(struct inotify_data, buffered);
+
+        /* The buffer we read inotify events into */
+        size_t buffer_filled; /* fill level of the buffer */
+        union inotify_event_buffer buffer; /* struct inotify_event in union inotify_event_buffer has flex
+                                            * array. Hence, this must be at the end. */
```
Comment (poettering) [inline src/libsystemd/sd-event/event-source.h:240]: hmpf

File: src/libsystemd-network/dhcp-lease-internal.h [hunk 7]
```diff
@@ -84,6 +82,8 @@ struct sd_dhcp_lease {
         size_t sixrd_n_br_addresses;
 
         LIST_HEAD(struct sd_dhcp_raw_option, private_options);
+
+        sd_dhcp_client_id client_id; /* This contains flex array, hence must be at the end. */
```
Comment (poettering) [inline src/libsystemd-network/dhcp-lease-internal.h]: it doesn't include a flex array though? it includes a zero-sized one, but that's something quite different, no?

File: src/libsystemd-network/dhcp-duid-internal.h (hunk 3 above)
Comment (keszybz) [reply src/libsystemd-network/dhcp-duid-internal.h]: @poettering did you see this comment?

Comment (poettering) [reply src/libsystemd-network/dhcp-duid-internal.h]: yeah, and i agree with it.
