### PR TITLE
network: bridge vlan without PVID

### LINKED ISSUE #5716: systemd-networkd: bridge vlan: does not remove vlan 1
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

### Used distribution

Debian stretch

### In case of bug report: Expected behaviour you didn't see

    # bridge vlan show dev test
    port    vlan ids
    test     2 PVID Egress Untagged

### In case of bug report: Unexpected behaviour you saw

    # bridge vlan show dev test
    port    vlan ids
    test     1 Egress Untagged
             2 PVID Egress Untagged

### In case of bug report: Steps to reproduce the problem

/etc/systemd/network/00-test.network:

    [Match]
    Name=test
    
    [Link]
    ARP=false
    
    [Network]
    Bridge=br
    
    [BridgeVLAN]
    VLAN=2
    EgressUntagged=2
    PVID=2

/etc/systemd/network/00-br.netdev:

    [NetDev]
    Kind=bridge
    Name=br
    
    [Bridge]
    VLANFiltering=true
    STP=false

/etc/systemd/network/00-br.network:

    [Match]
    Name=br
    
    [Link]
    ARP=false
    
    [Network]
    IPv6AcceptRA=false

then add some link named `test`:

    # ip link add type veth peer name test

### PR DESCRIPTION
**Pull request by toanju**
this patch makes it possible to configure a vlan aware bridge without the
PVID. To configure no PVID set DefaultPVID=none in the [BridgeVLAN] section.

fixes #5716

### CODE REVIEW

File: src/shared/vlan-util.c [hunk 1]
```diff
@@ -61,6 +62,10 @@ int config_parse_vlanid(
                 return 0;
         }
         if (r < 0) {
+                if (streq(lvalue, "DefaultPVID") && streq(rvalue, "none")) {
```
Comment (poettering) [inline src/shared/vlan-util.c]: uh oh, i really don#t like this special-casing here...

Please introduce a new function config_parse_default_vlanid(), that is primarily a wrapper around config_parse_vlanid(), but before handing things off will check for "none" and handle that directly. Then, use that new function in the netdev-gperf.gperf file for DefaultPVID=, but leave the original function for [VLAN]'s ID=, and things should be much prettier.

File: src/shared/vlan-util.c [hunk 2]
```diff
@@ -61,6 +62,10 @@ int config_parse_vlanid(
...
+                        *id = -1;
```
Comment (poettering) [inline src/shared/vlan-util.c]: id is of type `*uint16_t`. It's not OK to assign -1 to it (didn't your compiler complain about this?)

Please define a new macro VLANID_DEFAULT or so, mapping to `((uint16_t) -1)` or so and use that at the reevant places.

File: src/shared/vlan-util.c [hunk 3]
```diff
@@ -17,9 +17,10 @@
   along with systemd; If not, see <http://www.gnu.org/licenses/>.
 ***/
 
-#include "vlan-util.h"
-#include "parse-util.h"
+#include "basic/string-util.h"
```
Comment (poettering) [inline src/shared/vlan-util.c]: "basic" is part of the search path anyway, for everything we build from our search tree. Please drop this prefix

Comment (toanju) [reply src/shared/vlan-util.c]: thanks, will drop

File: src/shared/vlan-util.c (hunk 1 above)
Comment (toanju) [reply src/shared/vlan-util.c]: ack, will do

File: src/shared/vlan-util.c (hunk 2 above)
Comment (toanju) [reply src/shared/vlan-util.c]: right, gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1) doesn't complain. can do so.

**Comment by toanju** [comment]
Actually the added function `config_parse_default_port_vlanid` could be dropped since the pvid could be configured now as `DefaultPVID=0`. `DefaultPVID=none` is a little more verbose though. Both can be used right now. I have no strong opinion on this, hence feedback is welcome.

**Comment by poettering** [comment]
we usually try to be strict when parsing stuff, and not permit implicit "magic" values, but rather only have explicit ones, if you follow what I mean. i.e. if there's no sensible VLAN id "0", but "0" only stands for a "disabled", "off", "none" or a similar concept, than we should really expose it as such

Hmm, so this is messy, I wonder if the other users of VLAN id parsing (i.e VLAN.Id and the brvlan and fdb code actually really should be accepting vlan ID 0... I am not much of a VLAN guru, @ssahani, @toanju I figure both of you have more of a clue about that? Does it really make sense that parse_vlanid() accepts 0 as valid VLAN id? Does that really make sense for all users of it? I have the suspicion this is all pretty broken right now in networkd...

File: man/systemd.netdev.xml [hunk 4]
```diff
@@ -344,7 +344,8 @@
         <varlistentry>
           <term><varname>DefaultPVID=</varname></term>
           <listitem>
-            <para>This specifies the default port VLAN ID of a newly attached bridge port.</para>
+            <para>This specifies the default port VLAN ID of a newly attached bridge port.
+            Set this to <literal>none</literal> or <literal>0</literal> to disable the PVID.</para>
```
Comment (keszybz) [inline man/systemd.netdev.xml]: I don't see the point of allowing both. IIUC, "none" is translated to 0, so "0" should not be allowed as an option here.

`vlanid_is_valid` allows 0 and has a comment about explicitly allowing 0. Looks like this should be changed.

File: src/network/netdev/bridge.c [hunk 5]
```diff
@@ -102,7 +102,7 @@ static int netdev_bridge_post_create(NetDev *netdev, Link *link, sd_netlink_mess
                         return log_netdev_error_errno(netdev, r, "Could not append IFLA_BR_PRIORITY attribute: %m");
         }
 
-        if (b->default_pvid > 0) {
+        if (b->default_pvid != UINT16_MAX) {
```
Comment (keszybz) [inline src/network/netdev/bridge.c]: I'd prefer `VLANID_INVALID` here.

File: src/network/netdev/bridge.c [hunk 6]
```diff
@@ -160,6 +160,7 @@ static void bridge_init(NetDev *n) {
         b->mcast_snooping = -1;
         b->vlan_filtering = -1;
         b->stp = -1;
+        b->default_pvid = UINT16_MAX;
```
Comment (keszybz) [inline src/network/netdev/bridge.c]: And here too.

**Comment by toanju** [comment]
imho the current situation in the kernel is a bit fuzzy. Using a vid 0 on an interface works fine:

```
-bash-4.4# ip l a type dummy
-bash-4.4# ip l a link dummy0 type vlan id 0
```
I am not sure if anybody uses the explicit vid 0 on a interface though. 

But having a bridge dev with vid 0 isn't allowed:
```
-bash-4.4# ip l a type bridge
-bash-4.4# ip l a type dummy
-bash-4.4# ip l s bridge0 type bridge vlan_filtering 1
-bash-4.4# ip l s dummy0 master bridge0
-bash-4.4# bridge vlan add vid 0 dev dummy0
RTNETLINK answers: Invalid argument
```
To switch untagged packets you have to set the pvid using a vid in the range of 1-4094.

In general the vid 0 means no VLAN and the packets sent do not set the VLAN header. afaik the vid 0 is used on switches in case you want to apply a certain priority.

File: src/network/netdev/bridge.c (hunk 5 above)
Comment (toanju) [reply src/network/netdev/bridge.c]: fine with me

File: src/network/netdev/bridge.c (hunk 6 above)
Comment (toanju) [reply src/network/netdev/bridge.c]: same

File: man/systemd.netdev.xml (hunk 4 above)
Comment (toanju) [reply man/systemd.netdev.xml]: fine with me

Comment (toanju) [reply man/systemd.netdev.xml]: I will add a check for vid==0 depending on vid 0 is shall be allowed or not

**Comment by ssahani** [comment]
Indeed @poettering . `0` is allowed

```
$ sudo  ip link add link enp0s25 name enp0s25.100 type vlan id 0
[sus@maximus build]$ ip -d link show enp0s25.100
9: enp0s25.100@enp0s25: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 28:d2:44:b0:6a:32 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    vlan protocol 802.1Q id 0 <REORDER_HDR> addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
```

Also networkd does accepts `0`

File: src/network/netdev/bridge.c [hunk 7]
```diff
@@ -102,7 +103,7 @@ static int netdev_bridge_post_create(NetDev *netdev, Link *link, sd_netlink_mess
                         return log_netdev_error_errno(netdev, r, "Could not append IFLA_BR_PRIORITY attribute: %m");
         }
 
-        if (b->default_pvid > 0) {
+        if (b->default_pvid != VLANID_INVALID) {
```
Comment (ssahani) [inline src/network/netdev/bridge.c:106]:
```
index 9fdcb5537..0ac703fb7 100644
--- i/src/network/netdev/bridge.c
+++ w/src/network/netdev/bridge.c
@@ -102,7 +102,7 @@ static int netdev_bridge_post_create(NetDev *netdev, Link *link, sd_netlink_mess
                         return log_netdev_error_errno(netdev, r, "Could not append IFLA_BR_PRIORITY attribute: %m");
         }
 
-        if (b->default_pvid > 0) {
+        if (b->default_pvid >= 0) {
                 r = sd_netlink_message_append_u16(req, IFLA_BR_VLAN_DEFAULT_PVID, b->default_pvid);
                 if (r < 0)
                         return log_netdev_error_errno(netdev, r, "Could not append IFLA_BR_VLAN_DEFAULT_PVID attribute: %m");
```
With conf 

```
                                                                                                                                                                                               
[NetDev]                                                                                                                                                                                       
Kind=bridge                                                                                                                                                                                    
Name=br                                                                                                                                                                                        
                                                                                                                                                                                               
[Bridge]                                                                                                                                                                                       
VLANFiltering=true                                                                                                                                                                             
DefaultPVID=0                                                                                                                                                                                  
```
So this works
```
$ ip -d link show  br | grep pvid
    bridge forward_delay 1500 hello_time 200 max_age 2000 ageing_time 30000 stp_state 0 priority 32768 vlan_filtering 1 vlan_protocol 802.1Q bridge_id 8000.e2:f:4b:c0:a3:4c designated_root 8000.e2:f:4b:c0:a3:4c root_port 0 root_path_cost 0 topology_change 0 topology_change_detected 0 hello_timer    0.00 tcn_timer    0.00 topology_change_timer    0.00 gc_timer  274.79 vlan_default_pvid 0 group_fwd_mask 0 group_address 01:80:c2:00:00:00 mcast_snooping 1 mcast_router 1 mcast_query_use_ifaddr 0 mcast_querier 0 mcast_hash_elasticity 4 mcast_hash_max 512 mcast_last_member_count 2 mcast_startup_query_count 2 mcast_last_member_interval 100 mcast_membership_interval 26000 mcast_querier_interval 25500 mcast_query_interval 12500 mcast_query_response_interval 1000 mcast_startup_query_interval 3125 nf_call_iptables 0 nf_call_ip6tables 0 nf_call_arptables 0 addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
```

Comment (toanju) [reply src/network/netdev/bridge.c:106]: That was actually discussed above that DefaultPVID=0 would work. The preference from the discussion above is that "none" is preferable. The result in the end is the same since "none" sets the vid to 0.

Comment (ssahani) [reply src/network/netdev/bridge.c:106]: What I think is "none" is like disabled but here pvid/vlanid `0` is perfectly valid. Hence that makes sense here.

Comment (toanju) [reply src/network/netdev/bridge.c:106]: None is equivalent to 0 and hence disabled. It's rather a matter of taste if networkd shall accept both for configuration to disable the pvid. If the vid 0 would be valid on a bridge the above shown 'bridge vlan add vid 0 dev dummy0' would be accepted as well. That's what I tried to express in the comment above, sorry if it was confusing. 

The kernel disables the pvid 0 here http://elixir.free-electrons.com/linux/latest/source/net/bridge/br_vlan.c#L823.

**Comment by toanju** [comment]
Any updates on this?

**Comment by poettering** [comment]
patch looks OK, but I think we should still fix parse_vlanid() sooner or later and explicitly disallow vlan id "0". As I understand there's no such concept as a VLAN 0, but it is used as special marker in different ways in different subsystems. And such a marker is a low-level internal concept that should not spill into our configuration. Instead we should refuse parsing "0" as a valid VLAN id, and as appropriate define a special value, ike this patch does it for all cases. 

But I figure that can happen in a later patch, hence merging this now.
