### PR TITLE
udev: do not kill "udevadm control" processes in the same cgroup

### LINKED ISSUE #16867: udevd killing udevadm reload command when SELinux is enabled
**systemd version the issue has been seen with**
> systemd 246 (246.2-1)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
   

**Used distribution**
 > Debian sid

**Expected behaviour you didn't see**
 > Normal udevd reload, like on a SELinux disabled system:

```
Aug 27 10:04:59 debianHome systemd[1]: Reloading Rule-based Manager for Device Events and Files.
Aug 27 10:04:59 debianHome udevadm[57886]: SELinux enabled state cached to: disabled
Aug 27 10:04:59 debianHome systemd-udevd[57881]: Received udev control message (RELOAD)
Aug 27 10:04:59 debianHome systemd-udevd[57881]: Unload module index
Aug 27 10:04:59 debianHome systemd-udevd[57881]: Unloaded link configuration context.
Aug 27 10:04:59 debianHome systemd[1]: Reloaded Rule-based Manager for Device Events and Files.
```
**Unexpected behaviour you saw**
 > udevd killing (or trying to kill) the udevadm process, called by the ExecReload= command:

> Enforcing mode, i.e. SIGKILL denied
```
Aug 27 10:07:14 rpi3 systemd[1]: Reloading Rule-based Manager for Device Events and Files.
Aug 27 10:07:14 rpi3 udevadm[26973]: SELinux enabled state cached to: enabled
Aug 27 10:07:14 rpi3 udevadm[26973]: Successfully loaded SELinux database in 12.371ms, size on heap is 2355K.
Aug 27 10:07:14 rpi3 audit[26970]: AVC avc:  denied  { sigkill } for  pid=26970 comm="systemd-udevd" scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_
u:system_r:udev_t:s0-s0:c0.c1023 tclass=process permissive=0
Aug 27 10:07:14 rpi3 audit[26970]: SYSCALL arch=c00000b7 syscall=129 success=no exit=-13 a0=695d a1=9 a2=695d a3=aaaacc2fa510 items=0 ppid=1 pid=26970 auid=4294967295
 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-udevd" exe="/usr/bin/udevadm" subj=system_u:system_r:udev_t:s0-s0:c0.c1023 key=(n
ull)
Aug 27 10:07:14 rpi3 audit: OBJ_PID opid=26973 oauid=-1 ouid=0 oses=-1 obj=system_u:system_r:udev_t:s0-s0:c0.c1023 ocomm="udevadm"
Aug 27 10:07:14 rpi3 audit: PROCTITLE proctitle="/lib/systemd/systemd-udevd"
Aug 27 10:07:14 rpi3 systemd-udevd[26970]: Received udev control message (RELOAD)
Aug 27 10:07:14 rpi3 audit[26970]: AVC avc:  denied  { sigkill } for  pid=26970 comm="systemd-udevd" scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_
u:system_r:udev_t:s0-s0:c0.c1023 tclass=process permissive=0
Aug 27 10:07:14 rpi3 audit[26970]: SYSCALL arch=c00000b7 syscall=129 success=no exit=-13 a0=695d a1=9 a2=695d a3=aaaacc2fa510 items=0 ppid=1 pid=26970 auid=4294967295
 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-udevd" exe="/usr/bin/udevadm" subj=system_u:system_r:udev_t:s0-s0:c0.c1023 key=(n
ull)
Aug 27 10:07:14 rpi3 audit: OBJ_PID opid=26973 oauid=-1 ouid=0 oses=-1 obj=system_u:system_r:udev_t:s0-s0:c0.c1023 ocomm="udevadm"
Aug 27 10:07:14 rpi3 audit: PROCTITLE proctitle="/lib/systemd/systemd-udevd"
Aug 27 10:07:14 rpi3 audit[26970]: AVC avc:  denied  { sigkill } for  pid=26970 comm="systemd-udevd" scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_
u:system_r:udev_t:s0-s0:c0.c1023 tclass=process permissive=0
Aug 27 10:07:14 rpi3 audit[26970]: SYSCALL arch=c00000b7 syscall=129 success=no exit=-13 a0=695d a1=9 a2=695d a3=aaaacc2fa510 items=0 ppid=1 pid=26970 auid=4294967295
 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-udevd" exe="/usr/bin/udevadm" subj=system_u:system_r:udev_t:s0-s0:c0.c1023 key=(n
ull)
Aug 27 10:07:14 rpi3 audit: OBJ_PID opid=26973 oauid=-1 ouid=0 oses=-1 obj=system_u:system_r:udev_t:s0-s0:c0.c1023 ocomm="udevadm"
Aug 27 10:07:14 rpi3 audit: PROCTITLE proctitle="/lib/systemd/systemd-udevd"
Aug 27 10:07:14 rpi3 systemd-udevd[26970]: Unload module index
Aug 27 10:07:14 rpi3 systemd-udevd[26970]: Unloaded link configuration context.
Aug 27 10:07:14 rpi3 systemd[1]: Reloaded Rule-based Manager for Device Events and Files.
```

> Permissive mode, i.e. SIGKILL allowed
```
Aug 27 10:07:46 rpi3 audit[26979]: SYSCALL arch=c00000b7 syscall=64 success=yes exit=1 a0=3 a1=ffffeaff79b0 a2=1 a3=ffff7fa43670 items=0 ppid=26291 pid=26979 auid=0 u
id=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts1 ses=9 comm="setenforce" exe="/usr/sbin/setenforce" subj=root:sysadm_r:sysadm_t:s0-s0:c0.c1023 key=(null)
Aug 27 10:07:46 rpi3 audit: PROCTITLE proctitle=736574656E666F7263650030
Aug 27 10:07:49 rpi3 systemd[1]: Reloading Rule-based Manager for Device Events and Files.
Aug 27 10:07:49 rpi3 udevadm[26982]: SELinux enabled state cached to: enabled
Aug 27 10:07:49 rpi3 udevadm[26982]: Successfully loaded SELinux database in 12.344ms, size on heap is 2355K.
Aug 27 10:07:49 rpi3 audit[26970]: AVC avc:  denied  { sigkill } for  pid=26970 comm="systemd-udevd" scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_
u:system_r:udev_t:s0-s0:c0.c1023 tclass=process permissive=1
Aug 27 10:07:49 rpi3 audit[26970]: SYSCALL arch=c00000b7 syscall=129 success=yes exit=0 a0=6966 a1=9 a2=6966 a3=aaaacc2fa510 items=0 ppid=1 pid=26970 auid=4294967295 
uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-udevd" exe="/usr/bin/udevadm" subj=system_u:system_r:udev_t:s0-s0:c0.c1023 key=(nu
ll)
Aug 27 10:07:49 rpi3 audit: OBJ_PID opid=26982 oauid=-1 ouid=0 oses=-1 obj=system_u:system_r:udev_t:s0-s0:c0.c1023 ocomm="udevadm"
Aug 27 10:07:49 rpi3 audit: PROCTITLE proctitle="/lib/systemd/systemd-udevd"
Aug 27 10:07:49 rpi3 systemd-udevd[26970]: Received udev control message (RELOAD)
Aug 27 10:07:49 rpi3 systemd[1]: systemd-udevd.service: Control process exited, code=killed, status=9/KILL
Aug 27 10:07:49 rpi3 systemd[1]: Reload failed for Rule-based Manager for Device Events and Files.
```

Now systemd (pid1) reports the reload as failed, because the ExecReload= process got killed.

**Steps to reproduce the problem**

```
systemctl reload systemd-udevd
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #16867.

### CODE REVIEW

**Comment by yuwata** [comment]
Note that the original issue looks something related to selinux, but can be reproducible with selinux disabled, by slowing down udevadm, e.g:
```
# /etc/systemd/system/systemd-udevd.service.d/override.conf
[Service]
ExecReload=
ExecReload=valgrind --leak-check=full /path/to/build/udevadm control --reload --timeout 0
```

File: src/udev/udevd.c [hunk 1]
```diff
@@ -1490,10 +1498,12 @@ static int on_post(sd_event_source *s, void *userdata) {
         if (manager->exit)
                 return sd_event_exit(manager->event, 0);
 
-        if (manager->cgroup)
+        if (manager->cgroup && !manager->ctrl_is_connected)
```
Comment (bluca) [inline src/udev/udevd.c]: won't this risk leaving something behind if it happens to be running at the same time as udevadm?

File: src/udev/udev-ctrl.c [hunk 2]
```diff
@@ -205,12 +205,12 @@ static int udev_ctrl_connection_event_handler(sd_event_source *s, int fd, uint32
                 return 0;
         }
 
-        if (msg_wire.type == _UDEV_CTRL_END_MESSAGES)
-                return 0;
-
         if (uctrl->callback)
                 (void) uctrl->callback(uctrl, msg_wire.type, &msg_wire.value, uctrl->userdata);
 
+        if (msg_wire.type == _UDEV_CTRL_END_MESSAGES)
```
Comment (bluca) [inline src/udev/udev-ctrl.c]: it is not clear to me how shuffling around these and the additional callback help with the problem, could you please add more details to the commit message?

File: src/udev/udevd.c (hunk 1 above)
Comment (yuwata) [reply src/udev/udevd.c]: Potentially yes. But `on_post()` is frequently called. So hopefully they are killed later soon.

**Comment by yuwata** [comment]
Logic to protect udevadm is changed. Also, how the new logic work is briefly commented in the code. PTAL.

**Review by bluca — APPROVED** [review]

File: src/udev/udevd.c [hunk 3]
```diff
@@ -1490,9 +1496,26 @@ static int on_post(sd_event_source *s, void *userdata) {
         if (manager->exit)
                 return sd_event_exit(manager->event, 0);
 
-        if (manager->cgroup)
-                /* cleanup possible left-over processes in our cgroup */
-                (void) cg_kill(SYSTEMD_CGROUP_CONTROLLER, manager->cgroup, SIGKILL, CGROUP_IGNORE_SELF, NULL, NULL, NULL);
+        if (manager->cgroup && udev_ctrl_is_connected(manager->ctrl) <= 0) {
```
Comment (bluca) [inline src/udev/udevd.c]: doesn't this mean if a user is calling udevadm, it will also skip the cleanup? is it still necessary after the pid matching logic was introduced?

**Comment by yuwata** [comment]
Now, "udevadm control" always send its PID. Also, the comments in the code are extended. I hope all questions and concerns by @bluca are addressed.

**Review by bluca — APPROVED** [review]
Nice! Maybe safer to wait for 251 though?

**Comment by yuwata** [comment]
> Nice! Maybe safer to wait for 251 though?

Yeah.
