### PR TITLE
dissect: support to unmount image without root partition

### LINKED ISSUE #25480: systemd-dissect --umount does not handle usr only images mounted with systemd-dissect --mount
### systemd version the issue has been seen with

main

### Used distribution

Fedora 37

### Linux kernel version used

6.0.8-300.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

```
➜  mkosi git:(repart) ✗ sudo systemd-dissect mkosi.output/fedora~37/image.raw -M abc
➜  mkosi git:(repart) ✗ ls abc
efi/  usr/
➜  mkosi git:(repart) ✗ sudo ../systemd/build/systemd-dissect -U abc
Failed to find backing block device for 'abc': Block device required
```

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
➜  mkosi git:(repart) ✗ sudo ../systemd/build/systemd-dissect mkosi.output/fedora~37/image.raw
      Name: image.raw
      Size: 562.5M

Image UUID: a8dbca6f-77a6-485c-8c67-b653758a8928
OS Release: NAME=Fedora Linux
            VERSION=37 (Thirty Seven)
            ID=fedora
            VERSION_ID=37
            VERSION_CODENAME=
            PLATFORM_ID=platform:f37
            PRETTY_NAME=Fedora Linux 37 (Thirty Seven)
            ANSI_COLOR=0;38;2;60;110;180
            LOGO=fedora-logo-icon
            CPE_NAME=cpe:/o:fedoraproject:fedora:37
            DEFAULT_HOSTNAME=fedora
            HOME_URL=https://fedoraproject.org/
            DOCUMENTATION_URL=https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/
            SUPPORT_URL=https://ask.fedoraproject.org/
            BUG_REPORT_URL=https://bugzilla.redhat.com/
            REDHAT_BUGZILLA_PRODUCT=Fedora
            REDHAT_BUGZILLA_PRODUCT_VERSION=37
            REDHAT_SUPPORT_PRODUCT=Fedora
            REDHAT_SUPPORT_PRODUCT_VERSION=37

    Use As: ✓ bootable system for UEFI
            ✓ bootable system for container
            ✗ portable service
            ✗ initrd
            ✗ extension for system
            ✗ extension for initrd
            ✗ extension for portable service

RW DESIGNATOR PARTITION UUID                       PARTITION LABEL FSTYPE ARCHITECTURE VERITY GROWFS NODE         PARTNO
rw usr        807857ae-2c79-4538-9271-ebbfaa657f11 usr-x86-64      ext4   x86-64       no        yes /dev/loop0p2 2
rw esp        da584991-3b7c-4868-a2f6-f82b79dc70db esp             vfat   -            -          no /dev/loop0p1 1
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #25480.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Don't we have to unmount the tmpfs as well? Also @poettering was thinking about implementing a policy for systemd-dissect to tell it what partitions to mount so any number of partitions from a disk image could be mounted and ideally --umount would be able to deal with all of them.

**Comment by yuwata** [comment]
Ah, nice catch. Will fix later. Thanks.

**Comment by DaanDeMeyer** [comment]
I made my own attempt to fix this in #25572, PTAL!

File: src/dissect/dissect.c [hunk 1]
```diff
@@ -1191,6 +1191,25 @@ static int action_umount(const char *path) {
...
+                if (!usr_path)
+                        return log_oom();
+
+                free_and_replace(canonical, usr_path);
+                close_and_replace(fd, usr_fd);
+        }
+
         r = fd_get_whole_disk(fd, /*backing=*/ true, &devno);
         if (r < 0)
                 return log_error_errno(r, "Failed to find backing block device for '%s': %m", canonical);
```
Comment (poettering) [inline src/dissect/dissect.c:1211]: I think this would be simpler if we'd just try fd_get_whole_disk() and if it doesn't work, try it on the usr subdir.

i.e.:

```
r = fd_get_whole_disk(fd, /* backing=*/ true, &devno);
if (r == -ENOTBLK) {
        _cleanup_close_ int usrfd = -1;

        usrfd = openat(fd, "/usr/", O_CLOEXEC|O_DIRECTORY_O_NOFOLLOW);
        if (usrfd < 0)
                …

        r = fd_get_while_disk(usrfd, /* backing=* / true, &devno);
}
if (r < 0)
        …

File: src/dissect/dissect.c [hunk 2]
```diff
@@ -1191,6 +1191,25 @@ static int action_umount(const char *path) {
...
+
+                usr_fd = openat(fd, "usr", O_CLOEXEC | O_DIRECTORY | O_NOFOLLOW);
+                if (usr_fd < 0)
+                        return log_error_errno(errno, "Failed to open '%s/usr': %m", canonical);
+
+                usr_path = path_join(canonical, "usr");
+                if (!usr_path)
+                        return log_oom();
+
+                free_and_replace(canonical, usr_path);
```
Comment (poettering) [inline src/dissect/dissect.c]: this looks wrong? if a DDI has an ESP then it would be mounted into /efi/ below the root of the image. Thus, by changing `canonical` here, it would no longer be unmounted via the unmounting below. 

This line should just go

File: src/dissect/dissect.c [hunk 3]
```diff
@@ -1191,6 +1191,25 @@ static int action_umount(const char *path) {
...
+                close_and_replace(fd, usr_fd);
```
Comment (poettering) [inline src/dissect/dissect.c]: this appears unnecessary, too

**Review by poettering — CHANGES_REQUESTED** [review]

**Comment by yuwata** [comment]
@DaanDeMeyer and @poettering Thank you for your review. Updated. PTAL!

**Review by DaanDeMeyer — APPROVED** [review]
