### PR TITLE
DHCP: when adding static routes set scopes properly

### LINKED ISSUE #5979: When adding routes systemd can be more intelligent about route scopes
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 233

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Container Linux

### In case of bug report: Expected behaviour you didn't see

> When static routes are configured via DHCP, the server doesn't have a way to tell the client what scope to use (no DHCP option for route scope). So it's important that the client assumes good defaults. I think systemd can do something similar as the `ip route add` command. Quoting https://linux.die.net/man/8/ip

> scope SCOPE_VAL
   the scope of the destinations covered by the route prefix. SCOPE_VAL may be a number or a string from the file /etc/iproute2/rt_scopes. If this parameter is omitted, ip assumes scope global for all gatewayed unicast routes, scope link for direct unicast and broadcast routes and scope host for local routes.

### In case of bug report: Unexpected behaviour you saw

> systemd adds static routes from DHCP with scope `RT_SCOPE_UNIVERSE` aka `global`. Despite that the server sends two routes (one direct route to the gateway and the other to the LAN the gateway and my host are both on), the kernel rejects the second route because it doesn't know how to reach the gateway as the route was not _link local_.

> Normally if the DHCP server sends a non-32 bit netmask, the kernel will automatically add a route to the network with link local. In my case, the server sends a netmask of 255.255.255.255 so I am not getting that.

### In case of bug report: Steps to reproduce the problem

> 
 * Configure an interface, e.g., `eth0`, with DHCP, assuming the network is 192.168.0.0/24
* Server sends two routes in response:
  ```
  # cat /run/systemd/netif/leases/3
  ...
  ADDRESS=192.168.0.2
  NETMASK=255.255.255.255
  ROUTES=192.168.0.1/32,0.0.0.0 192.168.0.0/24,192.168.0.1
  ...
  ```
* systemd-networkd fails to configure `eth0`:
  ```
  # systemctl status systemd-networkd
  ...
  systemd-networkd[26821]: eth0: Could not set DHCPv4 route: Network is unreachable
  systemd-networkd[26821]: eth0: Failed
  ```

### PR DESCRIPTION
**Pull request by wonderfly**
DHCP responses could include static routes, but unfortunately not an
option to tell what scope to use. So it's important that the client sets
it properly.

This mimics what the `ip route add` command does when adding a static
route without an explicit scope:

* If the destination IP is on the local host, use scope `host`
* Otherwise if the gateway IP is null (direct route), use scope `link`
* If anything else, use the current default `global`.

Fixes #5979

@poettering @keszybz Can you take a look?

### CODE REVIEW

**Comment by poettering** [comment]
patch looks good, but please also update systemd.network(5) explaining this behaviour. It currently still claims the scope would default to "global" without any conditions

File: src/network/networkd-dhcp4.c [hunk 1]
```diff
@@ -142,6 +141,14 @@ static int link_set_dhcp_routes(Link *link) {
...
                 route->table = link->network->dhcp_route_table;
 
+                /* Set route scope based on its dst and gw. */
+                if (in_addr_is_localhost(AF_INET, &route->dst) || (address.s_addr && route->dst.in.s_addr == address.s_addr))
+                        route->scope = RT_SCOPE_HOST;
+                else if (in4_addr_is_null(&route->gw.in))
+                        route->scope = RT_SCOPE_LINK;
+                else
+                        route->scope = RT_SCOPE_UNIVERSE;
+
```
Comment (keszybz) [inline src/network/networkd-dhcp4.c]: Also, could you split this out into a static helper function? E.g. `route_scope_from_address`…

**Comment by wonderfly** [comment]
> patch looks good, but please also update systemd.network(5) explaining this behaviour. It currently still claims the scope would default to "global" without any conditions

Thanks for the reminder for updating docs. But I assume you were referring to the [Route] section? That remains unchanged - routes statically configured through .network files will still default to "global", and that can be changed through the "Scope=" option as one likes.

This patches affects only the logic for routes added through DHCP - where the server doesn't have such an option to tell the client what scope to use. I think it's worth documenting too. Let me add something to the "UseRoutes=" option in the [DHCP] section?

**Comment by keszybz** [comment]
That sounds good.

File: src/network/networkd-dhcp4.c (hunk 1 above)
Comment (wonderfly) [reply src/network/networkd-dhcp4.c]: Done, but I missed your suggestion for the function name... Let me know if you like mine. :P

**Comment by wonderfly** [comment]
Explained the logic in systemd.network.xml. PTAL. Feel free to suggest any change to the wording. Documentation isn't my strength...

**Comment by keszybz** [comment]
I mangled your commit a bit. The documentation part is fine, but I didn't like the fact that `dhcp4_route_set_scope` introduced failure handling to be introduced, even though it couldn't really fail. I changed that to have a dumb `route_scope_from_address` and remove the error handling.

**Comment by wonderfly** [comment]
It looks great. Thanks
