### PR TITLE
varlink ref fix

### LINKED ISSUE #18025: systemd-resolved broken since commit "nss-resolve: varlink_call() set error_id only when r >= 0"
**systemd version the issue has been seen with**
 247.2

**Used distribution**
 Arch Linux / EndeavourOS

**Linux kernel version used** (`uname -a`)
 5.4.84-1-lts

**CPU architecture issue was seen on**
 x86_64

**Expected behaviour you didn't see**
 Could resolve hostname

**Unexpected behaviour you saw**
 Couldn't resolve hostname

**Steps to reproduce the problem**
 Trying use DNS resolution

**Additional information:**
Happens since https://github.com/systemd/systemd/commit/3c229a9afb670025a3c1792bf5ac233b5a566ec5

[resolved.conf.txt](https://github.com/systemd/systemd/files/5719903/resolved.conf.txt)
[nsswitch.conf.txt](https://github.com/systemd/systemd/files/5719904/nsswitch.conf.txt)
[systemd-resolved.logs.txt](https://github.com/systemd/systemd/files/5719905/systemd-resolved.logs.txt)

### PR DESCRIPTION
**Pull request by poettering**
My proposal to fix #18025. Not much tested, and it's late, but it appears to me this is actually the right fix.

i.e. the general rule is that doing:

```c
p = foo_unref(p);
```

is only safe as long as `foo_unref()` never ends up calling callbacks that might deref `p` via some other code path. If that's the case we always need to write:

```c
q = TAKE_PTR(p);
foo_unref(q);
```

So that `p` is reset before we destroy the object it pointed to.

I briefly checked the other callers of varlink_close_unref() and I think they don't suffer by this issue.

I wonder if we should learn some lesson from this though, i.e. maybe not have varlink_close_unref() to avoid this pitfall. i.e. an alternative patch to this one could be:

```c
m->managed_oom_varlink_request = varlink_close_unref(m->managed_oom_varlink_request);
```

becomes:

```c
if (m->managed_oom_varlink_request) {
        varlink_close(m->managed_oom_varlink_request);
        m->managed_oom_varlink_request = varlink_unref(m->managed_oom_varlink_request);
}
```

With this fix the varlink_close() would call vl_disconnect() which would already reset m->managed_oom_varlink_request to NULL and thus make this unref a NOP. In fact, this also means a sufficient patch would also be to replace like this:

```c
m->managed_oom_varlink_request = varlink_close_unref(m->managed_oom_varlink_request);
```

becomes:

```c
if (m->managed_oom_varlink_request)
        varlink_close(m->managed_oom_varlink_request);
```

The vl_disconnect() handler would already unref the the pointer for us...

But quite frankly, I of these three solutions I like the one I proposed best.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Arch (mkosi) is not happy:

```
[516/1655] Generating console.c.o with a custom command
FAILED: src/boot/efi/console.c.o 
cc -c ../src/src/boot/efi/console.c -o src/boot/efi/console.c.o -Wall -Wextra -std=gnu99 -nostdlib -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -I /root/src/src/fundamental -DSD_BOOT -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI -ggdb -O0
../src/src/boot/efi/console.c:27:3: error: conflicting types for ‘EFI_KEY_STATE’
   27 | } EFI_KEY_STATE;
      |   ^~~~~~~~~~~~~
In file included from /usr/include/efi/efi.h:63,
                 from ../src/src/boot/efi/console.c:3:
/usr/include/efi/eficonex.h:32:3: note: previous declaration of ‘EFI_KEY_STATE’ was here
   32 | } EFI_KEY_STATE;
      |   ^~~~~~~~~~~~~
../src/src/boot/efi/console.c:32:3: error: conflicting types for ‘EFI_KEY_DATA’
   32 | } EFI_KEY_DATA;
      |   ^~~~~~~~~~~~
In file included from /usr/include/efi/efi.h:63,
                 from ../src/src/boot/efi/console.c:3:
/usr/include/efi/eficonex.h:37:3: note: previous declaration of ‘EFI_KEY_DATA’ was here
   37 | } EFI_KEY_DATA;
      |   ^~~~~~~~~~~~
../src/src/boot/efi/console.c:34:29: error: conflicting types for ‘EFI_INPUT_READ_KEY_EX’
   34 | typedef EFI_STATUS (EFIAPI *EFI_INPUT_READ_KEY_EX)(
      |                             ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/efi/efi.h:63,
                 from ../src/src/boot/efi/console.c:3:
/usr/include/efi/eficonex.h:68:10: note: previous declaration of ‘EFI_INPUT_READ_KEY_EX’ was here
   68 | (EFIAPI *EFI_INPUT_READ_KEY_EX) (
      |          ^~~~~~~~~~~~~~~~~~~~~
../src/src/boot/efi/console.c:44:29: error: conflicting types for ‘EFI_KEY_NOTIFY_FUNCTION’
   44 | typedef EFI_STATUS (EFIAPI *EFI_KEY_NOTIFY_FUNCTION)(
      |                             ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/efi/efi.h:63,
                 from ../src/src/boot/efi/console.c:3:
/usr/include/efi/eficonex.h:82:10: note: previous declaration of ‘EFI_KEY_NOTIFY_FUNCTION’ was here
   82 | (EFIAPI *EFI_KEY_NOTIFY_FUNCTION) (
      |          ^~~~~~~~~~~~~~~~~~~~~~~
../src/src/boot/efi/console.c:48:29: error: conflicting types for ‘EFI_REGISTER_KEYSTROKE_NOTIFY’
   48 | typedef EFI_STATUS (EFIAPI *EFI_REGISTER_KEYSTROKE_NOTIFY)(
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/efi/efi.h:63,
                 from ../src/src/boot/efi/console.c:3:
/usr/include/efi/eficonex.h:88:10: note: previous declaration of ‘EFI_REGISTER_KEYSTROKE_NOTIFY’ was here
   88 | (EFIAPI *EFI_REGISTER_KEYSTROKE_NOTIFY) (
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/src/boot/efi/console.c:60:16: error: redefinition of ‘struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL’
   60 | typedef struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL {
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/efi/efi.h:63,
                 from ../src/src/boot/efi/console.c:3:
/usr/include/efi/eficonex.h:102:16: note: originally defined here
  102 | typedef struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL{
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/src/boot/efi/console.c:67:3: error: conflicting types for ‘EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL’
   67 | } EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/efi/efi.h:63,
                 from ../src/src/boot/efi/console.c:3:
/usr/include/efi/eficonex.h:109:3: note: previous declaration of ‘EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL’ was here
  109 | } EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/efi/efi.h:42,
                 from ../src/src/boot/efi/console.c:3:
../src/src/boot/efi/console.c: In function ‘console_key_read’:
../src/src/boot/efi/console.c:92:74: warning: passing argument 1 of ‘TextInputEx->ReadKeyStrokeEx’ from incompatible pointer type [-Wincompatible-pointer-types]
   92 |                 err = uefi_call_wrapper(TextInputEx->ReadKeyStrokeEx, 2, TextInputEx, &keydata);
      |                                                                          ^~~~~~~~~~~
      |                                                                          |
      |                                                                          EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL * {aka struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *}
../src/src/boot/efi/console.c:92:74: note: expected ‘struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *’ but argument is of type ‘EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *’ {aka ‘struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *’}
[517/1655] Generating util.c.o with a custom command
[518/1655] Generating boot.c.o with a custom command
ninja: build stopped: subcommand failed.
```

**Comment by DaanDeMeyer** [comment]
gnu-efi got updated today, I'm guessing a lot of the stuff we've defined manually until now got added to the gnu-efi headers. Let me try and add that stuff to missing_efi.h with appropriate guards.

**Comment by mrc0mmand** [comment]
> gnu-efi got updated today, I'm guessing a lot of the stuff we've defined manually until now got added to the gnu-efi headers. Let me try and add that stuff to missing_efi.h with appropriate guards.

Ah, I see, it indeed happens even with the systemd master & latest gnu-efi. Thanks for the heads-up!

**Comment by DaanDeMeyer** [comment]
Fix in #18987

**Comment by keszybz** [comment]
This certainly fixes the problem. Nevertheless, I don't think this is as nice as is it should be.

With status quo ante (before either my match or this pull request), we had this ugly property that calling `sd_varlink_close(x)` was OK, calling `x = sd_varlink_unref(x)` was OK, calling `x = sd_varlink_close_unref(x)` crashed. This violates a very basic principle that I think must be satisfied if users of this library are not to go crazy: when operating internally on a reference, the code ensures that it'll hold at least one reference. If doing callbacks, it means that it might need to temporarily bump the reference count. And in fact, this is what happens in various places, in sd-event, and also in the varlink code. This isn't very pretty, but this is what makes the library much easier to use and robust.

In the proposed patch, the issue is certainly avoided by nullifying the global reference before doing the call. But I think this is a work-around, not a solution, and just a trap waiting for us to fall into again.

**Comment by poettering** [comment]
Well, the simple fact is that in the status quo ante the ref count is decreased twice by the caller, by accident, even though it only retained one reference. With your fix this was taped over by allowing this to happen, but I think that's super ugly.

Maybe the way out is to replace `sd_varlink_close_unref()` by `sd_varlink_close_unrefp()` (which we define anyway for the gcc attribute stuff, and then only use that. i.e. this:

```c
p = sd_varlink_close_unref(p);
```

would become this:

```s
sd_varlink_close_unrefp(&p);
```

which would be shorter, fully safe and maybe even less redundant.

File: src/core/core-varlink.c [hunk 1]
```diff
@@ -473,10 +473,15 @@ int manager_varlink_init(Manager *m) {
...
         assert(m);
 
-        /* Send the final message if we still have a subscribe request open. */
-        m->managed_oom_varlink_request = varlink_close_unref(m->managed_oom_varlink_request);
+        /* Explicitly close the varlink connection to oomd. Note we first take the varlink connection out of
+         * the manager, and only then disconnect it — in two steps – so that we don't end up accidentally
+         * unreffing it twice. After all, closing the connection might cause the disconnect handler we
+         * installed (vl_disconnect() above) to be called, where we will unref it too. */
+        vl = TAKE_PTR(m->managed_oom_varlink_request);
+        varlink_close_unref(vl);
```
Comment (keszybz) [inline src/core/core-varlink.c]: The variable doesn't seem necessary
```C
varlink_close_unref(TAKE_PTR(m->managed_oom_varlink_request));
```

File: src/shared/varlink.c [hunk 2]
```diff
@@ -1221,33 +1220,17 @@ Varlink* varlink_close_unref(Varlink *v) {
...
 Varlink* varlink_flush_close_unref(Varlink *v) {
-        if (v)
-                varlink_flush(v);
+        if (!v)
+                return NULL;
 
-        return varlink_close_unref(v);
+        (void) varlink_flush(v);
+        (void) varlink_close(v);
+        return varlink_unref(v);
```
Comment (keszybz) [inline src/shared/varlink.c]: This chunk should stay.

**Review by keszybz — COMMENTED** [review]
This patch takes exactly the route with TAKE_PTR that in my comment I wrote that is not desirable. But It's true that it's just one extra `TAKE_PTR()`, which in practice doesn't look bad. So OK, let's do this.

**Comment by poettering** [comment]
rebased, and made the two suggested changes. ptal!

**Comment by keszybz** [comment]
LGTM.
