### PR TITLE
network: fix NDisc behavior when multiple routers exist

### LINKED ISSUE #16719: systemd 246 looses IPv6 address in a flappy way
**systemd version the issue has been seen with**
> 246

**Used distribution**
 > Archlinux

**Expected behaviour you didn't see**
 > stable IPv6 connection

**Unexpected behaviour you saw**
 > IPv6 address is lost from time to time for minutes, is back for some minutes and gone again and back and...

**Steps to reproduce the problem**

I did downgrade to 245 and the problem doesn't appear, when I upgrade to 246 the flappy IPv6 is back. My interface config is rather short:

```
 /etc/systemd/network/20-wired.network                              
[Match]               
Name=enp4s0

[Network]
DHCP=yes
```

And this is how it should look like and does with 245:
```
3: enp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:1b:21:22:46:10 brd ff:ff:ff:ff:ff:ff
    inet 10.23.0.150/24 brd 10.23.0.255 scope global dynamic enp4s0
       valid_lft 5390sec preferred_lft 5390sec
    inet6 fde8:1689:74ac::6b9/128 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fde8:1689:74ac:0:21b:21ff:fe22:4610/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 2003:a:XXXX:XXXX:21b:21ff:fe22:4610/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 86309sec preferred_lft 14309sec
    inet6 fe80::21b:21ff:fe22:4610/64 scope link 
       valid_lft forever preferred_lft forever
```

With 246 in the faulty state:
```
3: enp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:1b:21:22:46:10 brd ff:ff:ff:ff:ff:ff
    inet 10.23.0.150/24 brd 10.23.0.255 scope global dynamic enp4s0
       valid_lft 5390sec preferred_lft 3490sec
    inet6 fde8:1689:74ac::6b9/128 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fde8:1689:74ac:0:21b:21ff:fe22:4610/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::21b:21ff:fe22:4610/64 scope link 
       valid_lft forever preferred_lft forever
```

In the flappy case only the IPv4 and the link local v6 addresses are available.

I tried to see anything in the logs via journalctl or dmesg but nothing to see there at those timeslots where flapping starts.

Since it's narrowed down to the diff between systemd 245 and 246 I guess a change is the root cause for that behavior.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #16719.

### CODE REVIEW

**Comment by yuwata** [comment]
@keszybz and @poettering Could you review this? This needs to be backported to v246-stable.

File: src/network/networkd-address.c [hunk 1]
```diff
@@ -134,8 +137,10 @@ void address_free(Address *address) {
                 set_remove(address->link->dhcp6_addresses_old, address);
                 set_remove(address->link->dhcp6_pd_addresses, address);
                 set_remove(address->link->dhcp6_pd_addresses_old, address);
-                set_remove(address->link->ndisc_addresses, address);
-                set_remove(address->link->ndisc_addresses_old, address);
+                HASHMAP_FOREACH(addresses, address->link->ndisc_addresses_by_router, i)
+                        set_remove(addresses, address);
+                HASHMAP_FOREACH(addresses, address->link->ndisc_addresses_old_by_router, i)
+                        set_remove(addresses, address);
```
Comment (keszybz) [inline src/network/networkd-address.c]: Hmm... maybe instead of building two parallel hashmap structures, it would be easier to mark the items in those structures with a boolean flag `is_old`? This would require extending the item type, but would otherwise make the code a lot simpler.

**Comment by yuwata** [comment]
@keszybz Thank you for the comment, and sorry for late response. I force-pushed a revised version. I hope it addresses your suggestion. PTAL.

**Comment by colmbuckley** [comment]
I attached some comments to #16719 - I think that this issue has not yet been completely addressed.

**Review by ssahani — COMMENTED** [review]
Which commit introduced this bug.

**Comment by yuwata** [comment]
> Which commit introduced this bug.

By 69203fba700ea8d7b0c4f4e3d1e1f809ac4644a1 and b0b97766564b9a2b7f78a77bba00c0a577b39712.

**Comment by keszybz** [comment]
centos ci failed with, looks relevant:
```
05:16:06 ======================================================================
05:16:06 ERROR: test_ipv6_prefix_delegation (__main__.NetworkdRATests)
05:16:06 ----------------------------------------------------------------------
05:16:06 Traceback (most recent call last):
05:16:06   File "test/test-network/systemd-networkd-tests.py", line 3108, in test_ipv6_prefix_delegation
05:16:06     self.wait_online(['veth99:routable', 'veth-peer:degraded'])
05:16:06   File "test/test-network/systemd-networkd-tests.py", line 546, in wait_online
05:16:06     check_output(*args, env=env)
05:16:06   File "test/test-network/systemd-networkd-tests.py", line 49, in check_output
05:16:06     return subprocess.check_output(command, universal_newlines=True, **kwargs).rstrip()
05:16:06   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
05:16:06     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
05:16:06   File "/usr/lib/python3.8/subprocess.py", line 512, in run
05:16:06     raise CalledProcessError(retcode, process.args,
05:16:06 subprocess.CalledProcessError: Command '['/systemd-meson-build/systemd-networkd-wait-online', '--timeout=20s', '--interface=veth99:routable', '--interface=veth-peer:degraded']' returned non-zero exit status 1.
05:16:06 
05:16:06 ======================================================================
05:16:06 FAIL: test_ipv6_token_prefixstable (__main__.NetworkdRATests)
05:16:06 ----------------------------------------------------------------------
05:16:06 Traceback (most recent call last):
05:16:06   File "test/test-network/systemd-networkd-tests.py", line 3150, in test_ipv6_token_prefixstable
05:16:06     self.wait_online(['veth99:routable', 'veth-peer:degraded'])
05:16:06   File "test/test-network/systemd-networkd-tests.py", line 554, in wait_online
05:16:06     self.wait_operstate(link.split(':')[0], None, setup_state, setup_timeout)
05:16:06   File "test/test-network/systemd-networkd-tests.py", line 519, in wait_operstate
05:16:06     self.fail(f'Timed out waiting for {link} to reach state {operstate}/{setup_state}')
05:16:06 AssertionError: Timed out waiting for veth-peer to reach state \S+/configured
05:16:06 
05:16:06 ======================================================================
05:16:06 FAIL: test_ipv6_token_static (__main__.NetworkdRATests)
05:16:06 ----------------------------------------------------------------------
05:16:06 Traceback (most recent call last):
05:16:06   File "test/test-network/systemd-networkd-tests.py", line 3122, in test_ipv6_token_static
05:16:06     self.wait_online(['veth99:routable', 'veth-peer:degraded'])
05:16:06   File "test/test-network/systemd-networkd-tests.py", line 554, in wait_online
05:16:06     self.wait_operstate(link.split(':')[0], None, setup_state, setup_timeout)
05:16:06   File "test/test-network/systemd-networkd-tests.py", line 519, in wait_operstate
05:16:06     self.fail(f'Timed out waiting for {link} to reach state {operstate}/{setup_state}')
05:16:06 AssertionError: Timed out waiting for veth-peer to reach state \S+/configured
05:16:06 
05:16:06 ======================================================================
05:16:06 FAIL: test_ipv6_token_static_explicit (__main__.NetworkdRATests)
05:16:06 ----------------------------------------------------------------------
05:16:06 Traceback (most recent call last):
05:16:06   File "test/test-network/systemd-networkd-tests.py", line 3131, in test_ipv6_token_static_explicit
05:16:06     self.wait_online(['veth99:routable', 'veth-peer:degraded'])
05:16:06   File "test/test-network/systemd-networkd-tests.py", line 554, in wait_online
05:16:06     self.wait_operstate(link.split(':')[0], None, setup_state, setup_timeout)
05:16:06   File "test/test-network/systemd-networkd-tests.py", line 519, in wait_operstate
05:16:06     self.fail(f'Timed out waiting for {link} to reach state {operstate}/{setup_state}')
05:16:06 AssertionError: Timed out waiting for veth-peer to reach state \S+/configured
05:16:06 
05:16:06 ----------------------------------------------------------------------
05:16:06 Ran 141 tests in 2036.804s
05:16:06 
05:16:06 FAILED (failures=3, errors=1, skipped=1, expected failures=2)
05:16:06 [TASK END] Fri 04 Sep 2020 05:16:05 AM CEST
05:16:06 [RESULT] systemd-networkd_sanitizers - FAIL (EC: 1) (log file: /build/vagrant-arch-sanitizers-clang-testsuite.yAM/systemd-networkd_sanitizers_FAIL.log)
```

```
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #0 0x5585ccd52e4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #1 0x5585ccd4f8a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #2 0x5585cce081b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #3 0x5585cce07cf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #4 0x5585cce06810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #5 0x7ffa1f6a3f9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #6 0x7ffa1f6a2f79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #7 0x7ffa1f6a59ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #8 0x7ffa1f6a640d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #9 0x5585ccb9faac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #10 0x5585ccb9f254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #11 0x7ffa1eb5f001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]:     #12 0x5585ccb9f16d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 04:53:07 arch.localdomain systemd-networkd[160511]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
05:16:10 
05:16:10 
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #0 0x5559d3c63e4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #1 0x5559d3c608a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #2 0x5559d3d191b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #3 0x5559d3d18cf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #4 0x5559d3d17810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #5 0x7f8edc333f9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #6 0x7f8edc332f79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #7 0x7f8edc3359ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #8 0x7f8edc33640d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #9 0x5559d3ab0aac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #10 0x5559d3ab0254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #11 0x7f8edb7ef001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]:     #12 0x5559d3ab016d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 04:53:15 arch.localdomain systemd-networkd[160543]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
05:16:10 
05:16:10 
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #0 0x55e15d759e4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #1 0x55e15d7568a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #2 0x55e15d80f1b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #3 0x55e15d80ecf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #4 0x55e15d80d810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #5 0x7f622821bf9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #6 0x7f622821af79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #7 0x7f622821d9ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #8 0x7f622821e40d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #9 0x55e15d5a6aac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #10 0x55e15d5a6254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #11 0x7f62276d7001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]:     #12 0x55e15d5a616d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 04:53:30 arch.localdomain systemd-networkd[160560]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
05:16:10 
05:16:10 
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #0 0x560ba8057e4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #1 0x560ba80548a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #2 0x560ba810d1b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #3 0x560ba810ccf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #4 0x560ba810b810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #5 0x7fe504fabf9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #6 0x7fe504faaf79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #7 0x7fe504fad9ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #8 0x7fe504fae40d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #9 0x560ba7ea4aac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #10 0x560ba7ea4254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #11 0x7fe504467001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]:     #12 0x560ba7ea416d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 04:53:36 arch.localdomain systemd-networkd[160569]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
05:16:10 
05:16:10 
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #0 0x5587d43cae4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #1 0x5587d43c78a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #2 0x5587d44801b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #3 0x5587d447fcf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #4 0x5587d447e810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #5 0x7fb68e46bf9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #6 0x7fb68e46af79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #7 0x7fb68e46d9ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #8 0x7fb68e46e40d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #9 0x5587d4217aac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #10 0x5587d4217254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #11 0x7fb68d927001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]:     #12 0x5587d421716d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 04:53:46 arch.localdomain systemd-networkd[160581]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
05:16:10 
05:16:10 
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #0 0x5584cd79fe4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #1 0x5584cd79c8a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #2 0x5584cd8551b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #3 0x5584cd854cf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #4 0x5584cd853810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #5 0x7f8fb4933f9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #6 0x7f8fb4932f79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #7 0x7f8fb49359ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #8 0x7f8fb493640d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #9 0x5584cd5ecaac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #10 0x5584cd5ec254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #11 0x7f8fb3def001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]:     #12 0x5584cd5ec16d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 04:53:56 arch.localdomain systemd-networkd[160599]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
05:16:10 
05:16:10 
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]: NDISC: Invoking callback for 'router' event.
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-resolved[157871]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/resolve1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1338 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #0 0x5572d8af3e4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #1 0x5572d8af08a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #2 0x5572d8ba91b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #3 0x5572d8ba8cf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #4 0x5572d8ba7810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #5 0x7f435e94bf9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #6 0x7f435e94af79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #7 0x7f435e94d9ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #8 0x7f435e94e40d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #9 0x5572d8940aac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #10 0x5572d8940254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #11 0x7f435de07001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]:     #12 0x5572d894016d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 04:54:01 arch.localdomain systemd-networkd[160614]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
05:16:10 
05:16:10 
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #0 0x55859483ae4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #1 0x5585948378a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #2 0x5585948f01b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #3 0x5585948efcf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #4 0x5585948ee810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #5 0x7f961e65bf9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #6 0x7f961e65af79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #7 0x7f961e65d9ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #8 0x7f961e65e40d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #9 0x558594687aac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #10 0x558594687254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #11 0x7f961db17001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]:     #12 0x55859468716d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 04:54:09 arch.localdomain systemd-networkd[160617]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
05:16:10 
05:16:10 
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #0 0x56212cecae4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #1 0x56212cec78a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #2 0x56212cf801b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #3 0x56212cf7fcf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #4 0x56212cf7e810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #5 0x7fbdf99c3f9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #6 0x7fbdf99c2f79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #7 0x7fbdf99c59ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #8 0x7fbdf99c640d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #9 0x56212cd17aac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #10 0x56212cd17254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #11 0x7fbdf8e7f001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]:     #12 0x56212cd1716d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 04:58:10 arch.localdomain systemd-networkd[161073]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
05:16:10 
05:16:10 
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]: NDISC: Received Router Advertisement: flags none preference medium lifetime 0 sec
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]: NDISC: Invoking callback for 'router' event.
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #0 0x55db3465ae4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #1 0x55db346578a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #2 0x55db347101b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #3 0x55db3470fcf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #4 0x55db3470e810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #5 0x7f4c074cbf9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #6 0x7f4c074caf79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #7 0x7f4c074cd9ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #8 0x7f4c074ce40d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #9 0x55db344a7aac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #10 0x55db344a7254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #11 0x7f4c06987001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]:     #12 0x55db344a716d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 05:14:33 arch.localdomain systemd-networkd[166075]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
05:16:10 
05:16:10 
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]: NDISC: Invoking callback for 'router' event.
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #0 0x557c8847ce4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #1 0x557c884798a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #2 0x557c885321b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #3 0x557c88531cf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #4 0x557c88530810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #5 0x7f752788bf9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #6 0x7f752788af79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #7 0x7f752788d9ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #8 0x7f752788e40d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #9 0x557c882c9aac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #10 0x557c882c9254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #11 0x7f7526d47001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]:     #12 0x557c882c916d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 05:14:51 arch.localdomain systemd-networkd[166129]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
05:16:10 
05:16:10 
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]: NDISC: Received Router Advertisement: flags none preference medium lifetime 0 sec
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]: NDISC: Invoking callback for 'router' event.
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #0 0x55b1eee62e4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #1 0x55b1eee5f8a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #2 0x55b1eef181b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #3 0x55b1eef17cf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #4 0x55b1eef16810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #5 0x7f78de03bf9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #6 0x7f78de03af79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #7 0x7f78de03d9ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #8 0x7f78de03e40d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #9 0x55b1eecafaac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #10 0x55b1eecaf254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #11 0x7f78dd4f7001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]:     #12 0x55b1eecaf16d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 05:15:11 arch.localdomain systemd-networkd[166182]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
05:16:10 
05:16:10 
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]: ../build/src/network/networkd-ndisc.c:1113:29: runtime error: member access within null pointer of type 'NDiscAddress' (aka 'struct NDiscAddress')
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]: rtnl: received non-static neighbor, ignoring.
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]: NDISC: Received Router Advertisement: flags none preference medium lifetime 0 sec
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]: NDISC: Invoking callback for 'router' event.
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #0 0x563f1c203e4b in ndisc_router_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1113:29
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #1 0x563f1c2008a7 in ndisc_handler /systemd-meson-build/../build/src/network/networkd-ndisc.c:1180:21
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #2 0x563f1c2b91b7 in ndisc_callback /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:43:9
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #3 0x563f1c2b8cf6 in ndisc_handle_datagram /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:201:9
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #4 0x563f1c2b7810 in ndisc_recv /systemd-meson-build/../build/src/libsystemd-network/sd-ndisc.c:254:16
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #5 0x7f12efaebf9f in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3232:21
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #6 0x7f12efaeaf79 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3673:21
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #7 0x7f12efaed9ac in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3731:21
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #8 0x7f12efaee40d in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3753:21
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #9 0x563f1c050aac in run /systemd-meson-build/../build/src/network/networkd.c:123:13
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #10 0x563f1c050254 in main /systemd-meson-build/../build/src/network/networkd.c:130:1
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #11 0x7f12eefa7001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]:     #12 0x563f1c05016d in _start (/systemd-meson-build/systemd-networkd+0x23a16d)
05:16:10 Sep 04 05:15:33 arch.localdomain systemd-networkd[166245]: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../build/src/network/networkd-ndisc.c:1113:29 in
```

**Comment by yuwata** [comment]
The failures may be the same as the segfault reported by @colmbuckley in #16719. I hope they are fixed now.

**Comment by keszybz** [comment]
Great, thanks. The code looks good to me, though I don't feel like I understand all the details. But if the CI passes, I think we can merge this.

**Comment by ssahani** [comment]
@yuwata can you please explain why this issue happend and how we fixing this.

**Comment by yuwata** [comment]
@ssahani My previous commits make old information (addresses, routes, DNS servers and domain) is cleaned when a new packet is received. It is desired if there exists only one RA server in the network. Otherwise, if the config of the RA server is updated, then the old information is not cleaned and the new information is just appended.

However, if there exists multiple RA servers in a network, then `networkd` typically receives different information from each server, thus information received by a RA server is cleaned when a packet received from another RA server. So, the network config of the machine becomes unstable.

To solve the issue, this patch makes each information labeled by the address of the router. Then, `networkd` can correctly handle that whether information is really changed or received from another RA server.

**Comment by colmbuckley** [comment]
@yuwata Finally figured out why I was seeing multiple RA servers; there are some Google Nest thermostats on this network, and they send out RAs to advertise their own internal mesh networks - [see here](https://forum.archive.openwrt.org/viewtopic.php?id=54161). Their design seems to be sound, and it **normally** wouldn't interfere with the operation of a regular SLAAC network, but the logic in your patch triggers this pathology.

**Comment by keszybz** [comment]
CentOS CI (Arch in KVM) failed in TEST-50-DISSECT, unrelated. I'll restart it.

**Comment by keszybz** [comment]
semaphore failed in packet download, I'll restart it too.
