### PR TITLE
systemctl: always pass &changes and &n_changes

### LINKED ISSUE #3339: `systemctl set-default` crashes
```
-bash-4.3# systemctl set-default multi-user.target
Segmentation fault (core dumped)
```

```
(gdb) thread apply all bt

Thread 1 (Thread 0x7fcd71c0f880 (LWP 286)):
#0  0x00005637ed326ce4 in bus_deserialize_and_dump_unit_file_changes (m=0x5637ed87e390, quiet=false, changes=0x0, n_changes=0x0) at src/shared/bus-unit-util.c:893
#1  0x00005637ed2f2ad4 in set_default (argc=2, argv=0x7ffea3b11230, userdata=0x0) at src/systemctl/systemctl.c:2101
#2  0x00005637ed396dbe in dispatch_verb (argc=3, argv=0x7ffea3b11228, verbs=0x5637ed43f4a0 <verbs>, userdata=0x0) at src/basic/verbs.c:92
#3  0x00005637ed305a38 in systemctl_main (argc=3, argv=0x7ffea3b11228) at src/systemctl/systemctl.c:7468
#4  0x00005637ed3069c2 in main (argc=3, argv=0x7ffea3b11228) at src/systemctl/systemctl.c:7737
```

This regression was introduced by af3d811352094f3f

### PR DESCRIPTION
**Pull request by eworm-de**
We have to pass addresses of changes and n_changes to
bus_deserialize_and_dump_unit_file_changes(). Otherwise we are hit by
missing information (subsequent calls to unit_file_changes_add() to
not add anything) and null pointer dereference later.

Fixes #3339

### CODE REVIEW

File: src/systemctl/systemctl.c [hunk 1]
```diff
@@ -2098,7 +2097,7 @@ static int set_default(int argc, char *argv[], void *userdata) {
                 if (r < 0)
                         return log_error_errno(r, "Failed to set default target: %s", bus_error_message(&error, r));
 
-                r = bus_deserialize_and_dump_unit_file_changes(reply, arg_quiet, NULL, NULL);
+                r = bus_deserialize_and_dump_unit_file_changes(reply, arg_quiet, &changes, &n_changes);
```
Comment (evverx) [inline src/systemctl/systemctl.c:2098]: There is a memory leak. Try:

```
-bash-4.3# systemctl set-default graphical.target

-bash-4.3# valgrind --leak-check=full systemctl set-default multi-user.target
==53== Memcheck, a memory error detector
==53== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==53== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==53== Command: systemctl set-default multi-user.target
==53==
Removed /etc/systemd/system/default.target.
Created symlink /etc/systemd/system/default.target → /lib/systemd/system/multi-user.target.
==53==
==53== HEAP SUMMARY:
==53==     in use at exit: 157 bytes in 5 blocks
==53==   total heap usage: 1,360 allocs, 1,355 frees, 391,609 bytes allocated
==53==
==53== 157 (48 direct, 109 indirect) bytes in 1 blocks are definitely lost in loss record 3 of 3
==53==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==53==    by 0x13683F: unit_file_changes_add (install.c:291)
==53==    by 0x152C84: bus_deserialize_and_dump_unit_file_changes (bus-unit-util.c:885)
==53==    by 0x11EA84: set_default (systemctl.c:2100)
==53==    by 0x1C2398: dispatch_verb (verbs.c:92)
==53==    by 0x1319F6: systemctl_main (systemctl.c:7465)
==53==    by 0x132980: main (systemctl.c:7734)
==53==
==53== LEAK SUMMARY:
==53==    definitely lost: 48 bytes in 1 blocks
==53==    indirectly lost: 109 bytes in 4 blocks
==53==      possibly lost: 0 bytes in 0 blocks
==53==    still reachable: 0 bytes in 0 blocks
==53==         suppressed: 0 bytes in 0 blocks
==53==
==53== For counts of detected and suppressed errors, rerun with: -v
==53== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

Comment (eworm-de) [inline src/systemctl/systemctl.c:2098]: Looks like we need some

```
unit_file_changes_free(changes, n_changes);
```

I will take a look tomorrow when I am back at physical keyboard.

Comment (eworm-de) [inline src/systemctl/systemctl.c:2098]: Added commit 6407767, which should fix the leaks.

File: src/shared/bus-unit-util.c [hunk 2]
```diff
@@ -865,6 +865,9 @@ int bus_deserialize_and_dump_unit_file_changes(sd_bus_message *m, bool quiet, Un
         const char *type, *path, *source;
         int r;
 
+        assert(changes);
+        assert(n_changes);
```
Comment (poettering) [inline src/shared/bus-unit-util.c:871]: why is this necessary? neither unit_file_dump_changes() nor unit_file_changes_add() really insist on the changes ptr to be non-NULL. They both have shortcuts to become NOPs in this case, in case you don't care about the precise changes generated... Hence adding an assert() here appears wrong.

File: src/systemctl/systemctl.c [hunk 3]
```diff
@@ -5723,12 +5721,11 @@ static int add_dependency(int argc, char *argv[], void *userdata) {
...
+        unsigned n_changes = 0;
         int r;
 
         if (install_client_side()) {
-                UnitFileChange *changes = NULL;
-                unsigned n_changes = 0;
-
                 r = unit_file_preset_all(arg_scope, arg_runtime, arg_root, arg_preset_mode, arg_force, &changes, &n_changes);
                 unit_file_dump_changes(r, "preset", changes, n_changes, arg_quiet);
                 unit_file_changes_free(changes, n_changes);
```
Comment (poettering) [inline src/systemctl/systemctl.c]: You have to move the unit_file_changes_free() call outside of this block too, if you move the declaration out of it. Otherwise you leak memory.

File: src/machine/machinectl.c [hunk 4]
```diff
@@ -1662,7 +1664,7 @@ static int enable_machine(int argc, char *argv[], void *userdata) {
                         return bus_log_parse_error(r);
         }
 
-        r = bus_deserialize_and_dump_unit_file_changes(reply, arg_quiet, NULL, NULL);
+        r = bus_deserialize_and_dump_unit_file_changes(reply, arg_quiet, &changes, &n_changes);
         if (r < 0)
```
Comment (poettering) [inline src/machine/machinectl.c:1668]: memory leak...

File: src/systemctl/systemctl.c [hunk 5]
```diff
@@ -2068,9 +2070,6 @@ static int set_default(int argc, char *argv[], void *userdata) {
                 return log_error_errno(r, "Failed to mangle unit name: %m");
 
         if (install_client_side()) {
-                UnitFileChange *changes = NULL;
-                unsigned n_changes = 0;
-
                 r = unit_file_set_default(arg_scope, arg_root, unit, true, &changes, &n_changes);
                 unit_file_dump_changes(r, "set default", changes, n_changes, arg_quiet);
                 unit_file_changes_free(changes, n_changes);
```
Comment (poettering) [inline src/systemctl/systemctl.c]: this _free() call must be moved into the outer block too, otherwise mem leak

File: src/systemctl/systemctl.c (hunk 1 above)
Comment (poettering) [inline src/systemctl/systemctl.c:2098]: @eworm-de please merge these commits, so that there's not intermediary state of the repo with the mem leak in place...

File: src/machine/machinectl.c [hunk 6]
```diff
@@ -1668,6 +1668,8 @@ static int enable_machine(int argc, char *argv[], void *userdata) {
...
                 return r;
 
+        unit_file_changes_free(changes, n_changes);
+
```
Comment (poettering) [inline src/machine/machinectl.c:1670]: This doesn't look right... the changes array needs to be freed in case of failure too. i figure that means you have to add a "fail:" section to the end, and make sure all error paths jump to it instead of returning directly.

Comment (poettering) [inline src/machine/machinectl.c:1670]: similar for the other cases too.

File: src/shared/bus-unit-util.c (hunk 2 above)
Comment (eworm-de) [inline src/shared/bus-unit-util.c:871]: `unit_file_dump_changes()` and `unit_file_changes_add()` are fine, but later we call

```
unit_file_dump_changes(0, NULL, *changes, *n_changes, false);
```

which dereferences `changes` with `*changes`. So yes, this is necessary.

Comment (poettering) [inline src/shared/bus-unit-util.c:871]: ah, right, make sense then, sorry for the confusoin.

**Comment by eworm-de** [comment]
Updated. Does that look better?
I hope I got all the code paths right.
