### PR TITLE
strv: drop strv_join_quoted() 

### LINKED ISSUE #8056: systemd-run can crash pid 1
Since this requires privileges to be set up correctly in order to be run, I don't really consider it a DoS.

Using the following command crashes pid 1:
```
# systemd-run /usr/bin/echo привет
```
That's because a failed assertion gets triggered in `strv_join_quoted` in `src/basic/strv.c:419`. That function doesn't really make much sense to me, including the assertion, so I leave this to someone more knowledgeable to fix correctly. The following patch might help you with testing this:
```
diff --git a/src/test/test-strv.c b/src/test/test-strv.c
index aec00eb81..cf409fd3b 100644
--- a/src/test/test-strv.c
+++ b/src/test/test-strv.c
@@ -726,7 +726,18 @@ static void test_strv_fnmatch(void) {
         assert_se(strv_fnmatch(v, "\\", FNM_NOESCAPE));
 }
 
+static void test_utf8(void) {
+        _cleanup_strv_free_ char **v = NULL;
+        _cleanup_free_ char *s = NULL;
+
+        v = strv_new("/usr/bin/echo ", "привет", NULL);
+        assert_se(v);
+        s = strv_join_quoted(v);
+        assert_se(s);
+}
+
 int main(int argc, char *argv[]) {
+        test_utf8();
         test_specifier_printf();
         test_str_in_set();
         test_strptr_in_set();
```
I've tried fixing this by removing the assertion and making the algorithm allocate more space, but even then, when trying to `streq` the result with what I expected, it didn't work.

As a side note, there are probably more assumptions throughout the code base that simply assume that a character is one byte long, which don't hold.

### PR DESCRIPTION
**Pull request by yuwata**
The function `strv_join_quoted()` is now not used, and has a bug in the buffer size calculation when the strings needs to escaped, as reported in #8056.
So, let's remove the function.

Closes #8056.

### CODE REVIEW

**Comment by evverx** [comment]
@yuwata, I can't keep up with you :-)

`strv_join_quoted` is no longer used anywhere apart from `test-strv`. Would it be better to get rid of it instead of trying to fix it?

File: src/test/test-strv.c [hunk 1]
```diff
@@ -726,6 +726,16 @@ static void test_strv_fnmatch(void) {
...
 
+static void test_strv_join_quoted_utf8(void) {
+        _cleanup_strv_free_ char **v = NULL;
+        _cleanup_free_ char *s = NULL;
+
+        /* test for issue #8056 */
+
+        assert_se(v = strv_new("/usr/bin/echo ", "привет", NULL));
+        assert_se(s = strv_join_quoted(v));
+}
```
Comment (jsynacek) [inline src/test/test-strv.c]: Initially, my solution looked like this as well. But I figured there should also be an assert that uses `streq` to check if you really got what you wanted from `strv_join_quoted`.

**Comment by yuwata** [comment]
@evverx I've added a commit that moves the function to test-strv.c. So, it may be not necessary `test_strv_join_quoted_utf8()` as it is a test for tests...

File: src/test/test-strv.c (hunk 1 above)
Comment (yuwata) [reply src/test/test-strv.c]: Yeah. But, now `strv_join_quoted()` is just a function for tests in test-strv.c. Of course, more tests is better than fewer. But it may not be necessary here.

**Comment by evverx** [comment]
@yuwata, thank you.

To be honest, I'm a bit confused about what `test_strv_quote_unquote` is testing now. The idea seems to have been to check whether something quoted by `strv_join_quoted` could be successfully unquoted and that made sense. Now that `strv_join_quoted` isn't used any more, the test is kind of artificial. Though, I'm not sure what to do about it.

Also I don't think that the commit message should contain the string "fixes #8056", because the crash mentioned in #8056 was fixed in 2e59b241ca86b8338c706a7a704d301fde908581.

**Comment by poettering** [comment]
Hmm, patch looks good, but I figure it's better to just remove the function if it's unused outside of tests...

**Comment by yuwata** [comment]
Yeah, indeed. I will update. Thank you.

**Comment by yuwata** [comment]
@evverx @poettering Updated. Now this completely removes the function as suggested.
