### PR TITLE
execute: Fix migration from DynamicUser=yes to no

### LINKED ISSUE #12131: RFE: migrate StateDirectory= and friends back from DynamicUser=1 subdir to regular one if needed
**systemd version the issue has been seen with**
> 241.1023-1

**Used distribution**
 > Manjaro

From Journalctl I get:

```
manjaro systemd[694]: systemd-timesyncd.service: Failed at step STATE_DIRECTORY spawning /usr/lib/systemd/systemd-timesyncd: Not a directory
manjaro systemd[694]: systemd-timesyncd.service: Failed to set up special execution directory in /var/lib: Not a directory
manjaro systemd[1]: Failed to start Network Time Synchronization.
manjaro systemd[691]: systemd-timesyncd.service: Failed at step STATE_DIRECTORY spawning /usr/lib/systemd/systemd-timesyncd: Not a directory
manjaro systemd[691]: systemd-timesyncd.service: Failed to set up special execution directory in /var/lib: Not a directory
manjaro systemd[1]: Failed to start Network Time Synchronization.
manjaro systemd[688]: systemd-timesyncd.service: Failed at step STATE_DIRECTORY spawning /usr/lib/systemd/systemd-timesyncd: Not a directory
manjaro systemd[688]: systemd-timesyncd.service: Failed to set up special execution directory in /var/lib: Not a directory
manjaro systemd[1]: Failed to start Network Time Synchronization.
manjaro systemd[685]: systemd-timesyncd.service: Failed at step STATE_DIRECTORY spawning /usr/lib/systemd/systemd-timesyncd: Not a directory
manjaro systemd[685]: systemd-timesyncd.service: Failed to set up special execution directory in /var/lib: Not a directory
manjaro systemd[1]: Failed to start Network Time Synchronization.
manjaro systemd[681]: systemd-timesyncd.service: Failed at step STATE_DIRECTORY spawning /usr/lib/systemd/systemd-timesyncd: Not a directory
manjaro systemd[681]: systemd-timesyncd.service: Failed to set up special execution directory in /var/lib: Not a directory
manjaro systemd-fsck[651]: fsck failed with exit status 16.
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #12131.

### CODE REVIEW

**Comment by mbiebl** [comment]
Works great. Thanks for fixing this so quickly, @yuwata

**Comment by mbiebl** [comment]
good idea, adding a test case for this, btw.

File: src/core/execute.c [hunk 1]
```diff
@@ -2256,13 +2256,17 @@ static int setup_exec_directory(
                                  * since they all support the private/ symlink logic at least in some
                                  * configurations, see above. */
 
+                                r = chase_symlinks(target, NULL, 0, &resolved, NULL);
```
Comment (yuwata) [inline src/core/execute.c]: I noticed that maybe this should be `path_simplify()`, otherwise, if e.g., /var/lib is a simlink to somewhere, the issue is still not fixed.

Comment (yuwata) [reply src/core/execute.c]: Oh, `path_simplify()` does not kill two dots...

**Comment by yuwata** [comment]
Updated.

**Comment by keszybz** [comment]
Oh, I missed this one. It'll have to go in post-release.

**Comment by keszybz** [comment]
Looks very nice.
