### PR TITLE
journalctl: track more closely whether we're within --until= range

### LINKED ISSUE #38121: journalctl --until --lines having error output when --until has no entries
### systemd version the issue has been seen with

257

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

journalctl

### Expected behaviour you didn't see

journalctl --until today --lines 5
```
-- No entries --
```

### Unexpected behaviour you saw

journalctl --until today --lines 5
[root@localhost ~]# journalctl --until today -n 5
Jul 08 14:45:11 localhost.localdomain kernel: xxxx
Jul 08 14:45:11 localhost.localdomain kernel: xxxx
Jul 08 14:45:11 localhost.localdomain kernel: xxxx
Jul 08 14:45:11 localhost.localdomain kernel: xxxx
Jul 08 14:45:11 localhost.localdomain kernel: xxxx

### Steps to reproduce the problem

1. sudo journalctl --vacuum-time=1s --rotate
2. journalctl --until today : `-- No entries --`
3. journalctl --until today --lines 5

### Additional program output to the terminal or log subsystem illustrating the issue

### PR DESCRIPTION
**Pull request by YHNdnzj**
Follow-up for 81fb5375b3b3bfc22d023d7908ad9eee4b3c1ffb

The offending commit fails to account for the case where we have fewer lines before --until= than what's specified in --lines=. Aside from that, if --grep= + --lines=+N are used, we might also seek forward in the middle of the loop, breaking the --until= boundary.

Let's turn the logic around then. Context.until_safe will be set iff we're certain that there's enough to output, and it gets reset whenever we seek forward.

Fixes #38121
Replaces #38122
Closes #38122

### CODE REVIEW

File: src/journal/journalctl-show.c [hunk 1]
```diff
@@ -117,10 +118,15 @@ static int seek_journal(Context *c) {
                                 return log_error_errno(r, "Failed to seek to tail: %m");
                 }
 
-                if (arg_reverse)
+                if (arg_reverse) {
                         r = sd_journal_previous(j);
-                else /* arg_lines_needs_seek_end */
+                        c->until_safe = true; /* can't possibly go beyond --until= if --reverse */
+
+                } else { /* arg_lines_needs_seek_end */
```
Comment (yuwata) [inline src/journal/journalctl-show.c]: This is not a fault in the commit. But could you suffix the function name with `()`?

**Review by yuwata — APPROVED** [review]
LGTM. One minor nitpick.
