### PR TITLE
core: increment start limit counter only when we can start the unit

### LINKED ISSUE #39247: D-Bus activated service can trip over StartLimitBurst earlier than expected
### systemd version the issue has been seen with

systemd-258-1.fc44.x86_64

### Used distribution

Fedora Rawhide

### Linux kernel version used

6.17.0-63.fc44.x86_64

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

One of our very old internal systemd tests has been occasionally failing on some ppc64le machines. The test, for some archaic reasons, restarts polkit by calling `killall polkitd` - since polkit is D-Bus activated, touching its D-Bus interface brings the unit back up again. The test does this 3 times in a row in a short timespan and sometimes the third restart fails due to a rate limit. However, systemd there defaults to `StartLimitBurst=5` so 3 restarts in a row shouldn't be an issue.

While tracking this down I minimized the reproducer to this:

```bash
#!/bin/bash

set -eux

systemctl show polkit | grep StartLimit

systemctl reset-failed polkit || :
systemctl status --no-pager polkit || :

for i in {1..5}; do
    echo "Start #$i"
    killall polkitd || :
    if ! pkexec echo hello; then
        journalctl -o short-monotonic --no-hostname --no-pager -u polkit -n 15
        exit 1
    fi
done
```

And the result from an _affected_ ppc64le machine looks like this:
```
# ./repro.sh 
+ systemctl show polkit
+ grep StartLimit
StartLimitIntervalUSec=10s
StartLimitBurst=5
StartLimitAction=none
+ systemctl reset-failed polkit
+ systemctl status --no-pager polkit
● polkit.service - Authorization Manager
     Loaded: loaded (/usr/lib/systemd/system/polkit.service; static)
     Active: active (running) since Tue 2025-09-16 11:57:24 UTC; 799ms ago
 Invocation: 2a6583d96acf4325aa4183aaf01f8641
       Docs: man:polkit(8)
   Main PID: 10182 (polkitd)
      Tasks: 5 (limit: 21696)
     Memory: 5.2M (peak: 20.1M)
        CPU: 83ms
     CGroup: /system.slice/polkit.service
             └─10182 /usr/lib/polkit-1/polkitd --no-debug --log-level=err

Sep 16 11:57:24 xxx (polkitd)[10182]: Failed to install filter set for architecture ppc, skipping...nceled
Sep 16 11:57:24 xxx (polkitd)[10182]: Failed to install filter set for architecture ppc64, skippi...nceled
Sep 16 11:57:24 xxx (polkitd)[10182]: Failed to install filter set for architecture ppc, skipping...nceled
Sep 16 11:57:24 xxx (polkitd)[10182]: Failed to install filter set for architecture ppc64, skippi...nceled
Sep 16 11:57:24 xxx (polkitd)[10182]: polkit.service: Executing: /usr/lib/polkit-1/polkitd --no-d...el=err
Sep 16 11:57:24 xxx polkitd[10182]: Started polkitd version 125
Sep 16 11:57:24 xxx systemd[1]: polkit.service: D-Bus name org.freedesktop.PolicyKit1 now owned ... :1.154
Sep 16 11:57:24 xxx systemd[1]: polkit.service: Changed start -> running
Sep 16 11:57:24 xxx systemd[1]: polkit.service: Job 5120 polkit.service/start finished, result=done
Sep 16 11:57:24 xxx systemd[1]: Started polkit.service - Authorization Manager.
Hint: Some lines were ellipsized, use -l to show in full.
+ for i in {1..5}
+ echo 'Start #1'
Start #1
+ killall polkitd
+ pkexec echo hello
hello
+ for i in {1..5}
+ echo 'Start #2'
Start #2
+ killall polkitd
+ pkexec echo hello
hello
+ for i in {1..5}
+ echo 'Start #3'
Start #3
+ killall polkitd
+ pkexec echo hello

** (process:10227): WARNING **: 11:57:26.071: Error enumerating actions: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.freedesktop.PolicyKit1': startup job failed
Error checking for authorization org.freedesktop.policykit.exec: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.freedesktop.PolicyKit1': startup job failed
+ journalctl -o short-monotonic --no-hostname --no-pager -u polkit -n 15
[ 5218.386483] systemd[1]: polkit.service: Start request repeated too quickly.
[ 5218.386496] systemd[1]: polkit.service: Failed with result 'start-limit-hit'.
[ 5218.386528] systemd[1]: polkit.service: Service restart not allowed.
[ 5218.386570] systemd[1]: polkit.service: Job 5412 polkit.service/start finished, result=failed
[ 5218.386582] systemd[1]: Failed to start polkit.service - Authorization Manager.
[ 5218.386884] systemd[1]: polkit.service: Releasing resources...
[ 5218.388943] systemd[1]: polkit.service: Trying to enqueue job polkit.service/start/replace
[ 5218.389288] systemd[1]: polkit.service: Installed new job polkit.service/start as 5485
[ 5218.389310] systemd[1]: polkit.service: Enqueued job polkit.service/start as 5485
[ 5218.389726] systemd[1]: polkit.service: Start request repeated too quickly.
[ 5218.389739] systemd[1]: polkit.service: Failed with result 'start-limit-hit'.
[ 5218.389770] systemd[1]: polkit.service: Service restart not allowed.
[ 5218.389812] systemd[1]: polkit.service: Job 5485 polkit.service/start finished, result=failed
[ 5218.389825] systemd[1]: Failed to start polkit.service - Authorization Manager.
[ 5218.390157] systemd[1]: polkit.service: Releasing resources...
+ exit 1
```

It was very strange that the issue was reproducible only on ppc64le (and even there, only on some machines) - turns out that the reason behind this is that the _affected_ ppc64le machines are really slow, which means that the `polkit.service` remains in the "stopping/cleaning" state for longer - and it's long enough for the reproducer to get to the `pkexec` part when we try to bring the polkit service back up (while it's still stopping).

Code-wise this means we go through `service_can_start()` and `unit_test_start_limit()` [0], which calls `ratelimit_below()` that increments the ratelimit counter. However, later in `service_start()` we realize that the service is still in `SERVICE_STOP/SERVICE_STOP_SIGTERM/SERVICE_CLEANING` state and return `-EAGAIN` [1], which moves the job back to `JOB_WAITING` so we can try again later, yet we already consumed one ratelimit slot.

With this the reproducer can be made more deterministic by artificially delaying the polkit service stop, i.e.:

```bash
#!/usr/bin/bash

set -eu

mkdir -p /run/systemd/system/polkit.service.d/
cat >/run/systemd/system/polkit.service.d/99-ExecStopPost.conf <<EOF
[Service]
ExecStopPost=sleep 1
EOF
systemctl daemon-reload
trap 'rm -f /run/systemd/system/polkit.service.d/99-ExecStopPost.conf; systemctl daemon-reload' EXIT

systemctl restart polkit
systemctl reset-failed polkit
systemctl status --no-pager polkit
systemctl show polkit | grep StartLimit

for i in {1..5}; do
        echo "Start #$i"

        systemctl stop --no-block polkit
        if ! pkexec echo hello; then
                journalctl -o short-monotonic --no-hostname --no-pager -u polkit -n 15
                exit 1
        fi
done
```

Which results in:

```
# ./repro.sh 
● polkit.service - Authorization Manager
     Loaded: loaded (/usr/lib/systemd/system/polkit.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
             /run/systemd/system/polkit.service.d
             └─99-ExecStopPost.conf
     Active: active (running) since Wed 2025-10-08 07:47:27 EDT; 32ms ago
 Invocation: 8f074734720c466b8bee3b5bf970abac
       Docs: man:polkit(8)
   Main PID: 1957 (polkitd)
     Status: "Processing requests..."
      Tasks: 5 (limit: 2282)
     Memory: 2M (peak: 3.6M)
        CPU: 61ms
     CGroup: /system.slice/polkit.service
             └─1957 /usr/lib/polkit-1/polkitd --no-debug --log-level=notice

Oct 08 07:47:27 xxx systemd[1]: Starting polkit.service - Authorization Manager...
Oct 08 07:47:27 xxx polkitd[1957]: Started polkitd version 126
Oct 08 07:47:27 xxx systemd[1]: Started polkit.service - Authorization Manager.
StartLimitIntervalUSec=10s
StartLimitBurst=5
StartLimitAction=none
Start #1
hello
Start #2
hello
Start #3

** (process:2020): WARNING **: 07:47:30.748: Error enumerating actions: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.freedesktop.PolicyKit1': startup job failed
Error checking for authorization org.freedesktop.policykit.exec: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.freedesktop.PolicyKit1': startup job failed
[  136.526420] systemd[1]: polkit.service: Deactivated successfully.
[  136.536313] systemd[1]: Starting polkit.service - Authorization Manager...
[  136.601900] polkitd[2006]: Started polkitd version 126
[  136.606293] systemd[1]: Started polkit.service - Authorization Manager.
[  136.643473] systemd[1]: Stopping polkit.service - Authorization Manager...
[  137.712710] systemd[1]: polkit.service: Deactivated successfully.
[  137.717530] systemd[1]: polkit.service: Start request repeated too quickly.
[  137.717647] systemd[1]: polkit.service: Failed with result 'start-limit-hit'.
[  137.718151] systemd[1]: Failed to start polkit.service - Authorization Manager.
[  137.724244] systemd[1]: polkit.service: Start request repeated too quickly.
[  137.724254] systemd[1]: polkit.service: Failed with result 'start-limit-hit'.
[  137.724284] systemd[1]: Failed to start polkit.service - Authorization Manager.
[  137.730176] systemd[1]: polkit.service: Start request repeated too quickly.
[  137.730187] systemd[1]: polkit.service: Failed with result 'start-limit-hit'.
[  137.730215] systemd[1]: Failed to start polkit.service - Authorization Manager.
```

This is quite a corner case so the question is - is this behavior expected?

[0] https://github.com/systemd/systemd/blob/1353564b9d7bd11888b7ca068ffce771ce6d8e7e/src/core/service.c#L5561
[1] https://github.com/systemd/systemd/blob/1353564b9d7bd11888b7ca068ffce771ce6d8e7e/src/core/service.c#L2959

### Unexpected behaviour you saw

The service should not fail when the number of restarts is < `StartLimitBurst`.

### Steps to reproduce the problem

See above.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Otherwise, e.g. requesting to start a unit that is under stopping may enter the failed state.

This makes
- refuse earlier to start units that are in the deactivating or refreshing states, so several redundant conditions in .start() are dropped,
- allow .can_start() return boolean and refuse to start units when it returns zero,
- move checks for unit states mapped to UNIT_ACTIVATING from .start() to .can_start().

Fixes #39247.

### CODE REVIEW

**Comment by YHNdnzj** [comment]
I'm pretty sure semantically "already on it" should not be treated as not be able to start...

**Comment by YHNdnzj** [comment]
And please do not return -AGAIN prematurely from unit_start. The checks below are very much relevant as a loaded unit can be stopped but not started again, hence ought to be dropped from the run queue immediately.

**Comment by YHNdnzj** [comment]
I mean, can start should only set to false if the job cannot be scheduled at all. If it's going to be delayed internally then I doubt it qualifies...

**Comment by yuwata** [comment]
> And please do not return -AGAIN prematurely from unit_start. The checks below are very much relevant as a loaded unit can be stopped but not started again, hence ought to be dropped from the run queue immediately.
> I mean, can start should only set to false if the job cannot be scheduled at all. If it's going to be delayed internally then I doubt it qualifies...

@YHNdnzj Sorry, I cannot follow. Could you elaborate more?
I thought I only make the start limit counter not incremented when we cannot schedule start job of a unit. Do you find any drawback of this PR? Or do I need to touch more places?

**Comment by YHNdnzj** [comment]
(I'm not home right now so cannot do complete review. Will check back this evening)

File: src/core/unit.c [hunk 1]
```diff
@@ -1936,7 +1936,7 @@ int unit_start(Unit *u, ActivationDetails *details) {
         state = unit_active_state(u);
         if (UNIT_IS_ACTIVE_OR_RELOADING(state))
                 return -EALREADY;
-        if (state == UNIT_MAINTENANCE)
+        if (IN_SET(state, UNIT_DEACTIVATING, UNIT_MAINTENANCE, UNIT_REFRESHING))
```
Comment (YHNdnzj) [inline src/core/unit.c]: UNIT_REFRESHING is handled by UNIT_IS_ACTIVE_OR_RELOADING already

File: src/core/unit.c [hunk 2]
```diff
@@ -1986,7 +1986,7 @@ int unit_start(Unit *u, ActivationDetails *details) {
         /* Check our ability to start early so that failure conditions don't cause us to enter a busy loop. */
         if (UNIT_VTABLE(u)->can_start) {
                 r = UNIT_VTABLE(u)->can_start(u);
-                if (r < 0)
+                if (r <= 0)
```
Comment (YHNdnzj) [inline src/core/unit.c:1990]: So, hmm, with your changes the can_start() naming becomes inaccurate, because it also checks whether we _should call into start()_. Hence maybe rename it to start_check() or sth.

Comment (YHNdnzj) [reply src/core/unit.c:1990]: Please also update the comment above and in unit.h

File: src/core/mount.c [hunk 3]
```diff
@@ -2386,6 +2373,10 @@ static int mount_can_start(Unit *u) {
         Mount *m = ASSERT_PTR(MOUNT(u));
         int r;
 
+        /* Already on it! */
```
Comment (YHNdnzj) [inline src/core/mount.c]: This is a bit hard to grok outside of the context. Say "being started already"?

File: src/core/service.c [hunk 4]
```diff
@@ -5562,6 +5551,13 @@ static int service_can_start(Unit *u) {
         Service *s = ASSERT_PTR(SERVICE(u));
         int r;
 
+        /* First check the state, and do not increment start limit counter if the service cannot start due to
+         * that e.g. it is already being started. Note, the service state mapped to UNIT_ACTIVE,
+         * UNIT_RELOADING, UNIT_DEACTIVATING, UNIT_MAINTENANCE, and UNIT_REFRESHING are already filtered in
+         * unit_start(). Hence, here we only need to check the state mapped to UNIT_ACTIVATING. */
+        if (IN_SET(s->state, SERVICE_CONDITION, SERVICE_START_PRE, SERVICE_START, SERVICE_START_POST))
+                return false;
```
Comment (YHNdnzj) [inline src/core/service.c:5559]: Please be consistent on retval style (0/1 vs false/true)

**Review by YHNdnzj — CHANGES_REQUESTED** [review]
Sorry for the noise above. I wasn't aware that can_start function in vtable is unrelated to unit_can_start and CanStart property (so it really should be renamed IMO)

**Comment by yuwata** [comment]
@YHNdnzj Thank you for the review. All comments and requests are addressed. PTAL.

**Review by YHNdnzj — APPROVED** [review]
LGTM

**Comment by bluca** [comment]
The new test added here appears to be flaky:

```
5148s TEST-07-PID1.sh[5632]: + systemctl show systemd-resolved.service
5148s TEST-07-PID1.sh[5633]: + grep StartLimit
5148s TEST-07-PID1.sh[5633]: StartLimitIntervalUSec=30s
5148s TEST-07-PID1.sh[5633]: StartLimitBurst=5
5148s TEST-07-PID1.sh[5633]: StartLimitAction=none
5148s TEST-07-PID1.sh[5579]: + for i in {1..5}
5148s TEST-07-PID1.sh[5579]: + echo 'Start #1'
5148s TEST-07-PID1.sh[5579]: Start #1
5148s TEST-07-PID1.sh[5579]: + systemctl stop --no-block systemd-resolved.service
5148s TEST-07-PID1.sh[5579]: + resolvectl
5148s TEST-07-PID1.sh[5635]: Failed to get global data: Remote peer disconnected
5148s TEST-07-PID1.sh[5579]: + journalctl -o short-monotonic --no-hostname --no-pager -u systemd-resolved.service -n 15
5148s TEST-07-PID1.sh[5636]: [  715.578014] systemd-resolved[5627]: Got message type=signal sender=org.freedesktop.DBus destination=:1.1147 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired  cookie=4294967295 reply_cookie=0 signature=s error-name=n/a error-message=n/a
5148s TEST-07-PID1.sh[5636]: [  715.578032] systemd-resolved[5627]: Got message type=signal sender=org.freedesktop.DBus destination=:1.1147 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired  cookie=4294967295 reply_cookie=0 signature=s error-name=n/a error-message=n/a
5148s TEST-07-PID1.sh[5636]: [  715.578050] systemd-resolved[5627]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.1147 path=n/a interface=n/a member=n/a  cookie=4294967295 reply_cookie=2 signature=u error-name=n/a error-message=n/a
5148s TEST-07-PID1.sh[5636]: [  715.578057] systemd-resolved[5627]: Successfully acquired requested service name.
5148s TEST-07-PID1.sh[5636]: [  715.578073] systemd-resolved[5627]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.1147 path=n/a interface=n/a member=n/a  cookie=4294967295 reply_cookie=3 signature= error-name=n/a error-message=n/a
5148s TEST-07-PID1.sh[5636]: [  715.578079] systemd-resolved[5627]: Match type='signal',sender='org.freedesktop.login1',path='/org/freedesktop/login1',interface='org.freedesktop.login1.Manager',member='PrepareForSleep' successfully installed.
5148s TEST-07-PID1.sh[5636]: [  715.615275] systemd[1]: systemd-resolved.service: Trying to enqueue job systemd-resolved.service/stop/replace
5148s TEST-07-PID1.sh[5636]: [  715.615299] systemd[1]: systemd-resolved.service: Installed new job systemd-resolved.service/stop as 17742
5148s TEST-07-PID1.sh[5636]: [  715.615308] systemd[1]: systemd-resolved.service: Enqueued job systemd-resolved.service/stop as 17742
5148s TEST-07-PID1.sh[5636]: [  715.615738] systemd[1]: systemd-resolved.service: Changed running -> stop-sigterm
5148s TEST-07-PID1.sh[5636]: [  715.615752] systemd[1]: Stopping systemd-resolved.service - Network Name Resolution...
5148s TEST-07-PID1.sh[5636]: [  715.624037] systemd-resolved[5627]: Bus bus-api-resolve: changing state RUNNING → CLOSED
5148s TEST-07-PID1.sh[5636]: [  715.624088] systemd-resolved[5627]: Removing scope on link *, protocol dns, family *, origin global, delegate n/a
5148s TEST-07-PID1.sh[5636]: [  715.624214] systemd[1]: systemd-resolved.service: Got notification message from PID 5627: STOPPING=1, STATUS=Shutting down...
5148s TEST-07-PID1.sh[5636]: [  715.624348] systemd[1]: systemd-resolved.service: D-Bus name org.freedesktop.resolve1 now not owned by anyone.
5148s TEST-07-PID1.sh[5579]: + exit 1
```

https://autopkgtest.ubuntu.com/results/autopkgtest-noble-upstream-systemd-ci-systemd-ci/noble/ppc64el/s/systemd-upstream/20251023_201527_c330c@/log.gz
