### PR TITLE
 sd-device: support the case that /sys is a symlink

### LINKED ISSUE #7676: The assert at src/libsystemd/sd-device/sd-device.c#L681 fails if /sys is a symlink
### Submission type
 - Bug report

### systemd version the issue has been seen with
Still exists in the current master...

### Used distribution

Arch Linux ARM in a custom userspace container that
has /sys symlinked to /oldroot/sys - ok, i didnt
ask anyone to support this but crashing seems wrong.

### In case of bug report: Expected behaviour you didn't see
Not crashing.

### In case of bug report: Unexpected behaviour you saw
Crashing.

### In case of bug report: Steps to reproduce the problem
Launch spacefm with /sys a symlink to something that
doesnt start with /sys (i suppose).

### PR DESCRIPTION
**Pull request by yuwata**
When /sys is a symlink to the sysfs mountpoint, e.g. /path/to/sysfs. Then, `device->syspath` was set to like /path/to/sysfs/devices/foo/baz. This converts the path to /sys/devices/foo/baz.

Fixes #7676.

### CODE REVIEW

File: src/libsystemd/sd-device/sd-device.c [hunk 1]
```diff
@@ -172,14 +172,12 @@ int device_set_syspath(sd_device *device, const char *_syspath, bool verify) {
...
                         /* not a symlink */
-                        syspath = canonicalize_file_name(_syspath);
-                        if (!syspath) {
-                                if (errno == ENOENT)
-                                        /* the device does not exist (any more?) */
-                                        return -ENODEV;
-
-                                return log_debug_errno(errno, "sd-device: could not canonicalize '%s': %m", _syspath);
-                        }
+                        r = chase_symlinks(_syspath, NULL, 0, &syspath);
```
Comment (poettering) [inline src/libsystemd/sd-device/sd-device.c]: Hmm I don't really grok the old btw, I think we should just call chase_symlinks() right-away instead of resolving the first step with readlink_and_canonicalize() and then the rest with chase_symlinks(). This appears unnecessarily complex still

File: src/libsystemd/sd-device/sd-device.c [hunk 2]
```diff
@@ -183,6 +183,33 @@ int device_set_syspath(sd_device *device, const char *_syspath, bool verify) {
...
+                        r = readlink_and_canonicalize("/sys", NULL, &real_sys);
+                        if (r < 0)
+                                return log_debug_errno(r, "sd-device: could not read symlink /sys: %m");
+
+                        if (!path_startswith(syspath, real_sys)) {
+                                log_debug("sd-device: canonicalized path '%s' does not starts with '%s'. Something strange...", syspath, real_sys);
+                                return -ENODEV;
+                        }
+
+                        r = path_make_relative(real_sys, syspath, &relpath);
```
Comment (poettering) [inline src/libsystemd/sd-device/sd-device.c]: as above, i'd just use chase_symlinks directly on /sys, and then chop off that from the new path here. i.e. now manual invocation of readlink_and_canonicalize or so so, but just always use chase_symlinks(), to determine the real meaning of both the specified syspath and of /sys

**Comment by yuwata** [comment]
@poettering Thank you for your comments. I've force-pushed a new version. Please take a look.
