### PR TITLE
network: add basic support of neighbor advertisement

### LINKED ISSUE #28421: IPv6 Compliance RFC4861: Neighbor Advertisement Processing, R-bit Change (Hosts Only) [v6LC.2.1.21a]
### systemd version the issue has been seen with

250

### Used distribution

Embedded Linux - Debian-based

### Linux kernel version used

5.15.71-rt51+gc36e774d0d9a

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

### Expected behaviour you didn't see

[RFC 4861 Neighbor Discovery in IPv6, page 66](https://www.rfc-editor.org/rfc/rfc4861#section-6.3.4:~:text=%2D%20The%20IsRouter%20flag,as%20a%20host.), Extract:

       - The IsRouter flag in the cache entry MUST be set based on the
         Router flag in the received advertisement.  In those cases
         where the IsRouter flag changes from TRUE to FALSE as a result
         of this update, the node MUST remove that router from the
         Default Router List and update the Destination Cache entries
         for all destinations using that neighbor as a router as
         specified in Section 7.3.3.  This is needed to detect when a
         node that is used as a router stops forwarding packets due to
         being configured as a host.

### Unexpected behaviour you saw

Networkd is not honoring this behaviour.  Instead, it continues to preserve the route entry, ignoring the change of the NA's `IsRouter` flag. 

### Steps to reproduce the problem

Reproducing this requires a protocol exchange. If you need help setting something up, please ask, FWIW, I find `tcpreplay` a useful tool).  Otherwise, I'll assume you have the tools necessary to duplicate this in your own environment.

Please find attached a zip file containing two PCAP files, `legacy` and `networkd`.  The `legacy` PCAP shows the correct behavior.  It was recorded when our host was configured using Debian's legacy `/etc/network/interfaces` file and `networkd` was disabled and stopped.  The `networkd` PCAP shows incorrect behavior. It was recorded after configuring `networkd` to manage the interface.

There are associated log files that provide additional information.  If you need more, please ask.

[2_1_21a - Neighbor Advertisement Processing, R-bit Change.zip](https://github.com/systemd/systemd/files/12066187/2_1_21a.-.Neighbor.Advertisement.Processing.R-bit.Change.zip)

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Closes #28421.

### CODE REVIEW

**Comment by yuwata** [comment]
@LiveFreeAndRoam Please test this PR. Thank you!

**Comment by LiveFreeAndRoam** [comment]
Will do. I should have the results late afternoon on Monday.

**Comment by bluca** [comment]
@mrc0mmand looks new:

```
18:58:52 [   58.835810] systemd-journald[317]: Failed to create new system journal: No space left on device
18:58:52 [   58.871275] kernel: Buffer I/O error on dev loop0, logical block 188, lost async page write
18:58:52 [   59.002224] systemd-journald[317]: Failed to open system journal: No space left on device
18:58:52 [   59.092183] systemd-journald[317]: Failed to open system journal: No space left on device
18:58:52 [   59.165246] systemd-journald[317]: Failed to open system journal: No space left on device
18:58:52 [   60.383763] testsuite-58.sh[8600]: Creating journal (262144 blocks): done
18:58:52 [   61.063267] testsuite-58.sh[8600]: Writing superblocks and filesystem accounting information:    0/8192         mkfs.ext4: Input/output error while writing out and closing file system
18:58:52 [   61.063733] testsuite-58.sh[8598]: (mkfs) failed with exit status 1.
18:58:52 [   61.063733] testsuite-58.sh[8598]: Failed to sync loop block device, ignoring: Input/output error
```

**Comment by LiveFreeAndRoam** [comment]
Hi @yuwata.  I was about to start an IPv6 Conformance test cycle.  It looks like you've begun pushing changes to systemd/systemd.  What branch would you like me to test? Your `network-neighbor-advertisement` branch or some other?

**Comment by yuwata** [comment]
> Hi @yuwata. I was about to start an IPv6 Conformance test cycle. It looks like you've begun pushing changes to systemd/systemd. What branch would you like me to test? Your `network-neighbor-advertisement` branch or some other?

Yes, `network-neighbor-advertisement` please. Thank you! This should not be still perfect. But I hope the situation should be better than previous when you open several issues.

**Comment by LiveFreeAndRoam** [comment]
I'm seeing failures at the moment. I'll have to dig in deeper to see what's tripping up one of the tests. I'll need some time to track this down.

**Comment by yuwata** [comment]
Which test(s)? Please provide the list of failed tests. I will also take a look.

**Comment by LiveFreeAndRoam** [comment]
Sorry for the delay, I had to run some errands.  I'm back looking at it now. The failed test is the same described in #28421.  I'm guessing the default route is not being deleted upon receipt of the NA with isRouter=false.

**Comment by LiveFreeAndRoam** [comment]
To get the tests to pass, I had to comment out your checks for `sd_ndisc_neighbor_is_solicited` and `sd_ndisc_neighbor_is_override`.  The diff is:

```
diff --git a/src/network/networkd-ndisc.c b/src/network/networkd-ndisc.c
index 672e07438d..3b738e9178 100644
--- a/src/network/networkd-ndisc.c
+++ b/src/network/networkd-ndisc.c
@@ -1819,15 +1819,15 @@ static int ndisc_neighbor_handler(Link *link, sd_ndisc_neighbor *na) {
         assert(link);
         assert(na);
 
-        /* Currently, we do not send neighbor solicitation. Hence, ignore solicited neighbor advertisement. */
-        r = sd_ndisc_neighbor_is_solicited(na);
-        if (r != 0)
-                return r;
+        // /* Currently, we do not send neighbor solicitation. Hence, ignore solicited neighbor advertisement. */
+        // r = sd_ndisc_neighbor_is_solicited(na);
+        // if (r != 0)
+        //         return r;
 
         /* It is not necessary to update anything if the override flag is not set. */
-        r = sd_ndisc_neighbor_is_override(na);
-        if (r <= 0)
-                return r;
+        // r = sd_ndisc_neighbor_is_override(na);
+        // if (r <= 0)
+        //         return r;
 
         r = sd_ndisc_neighbor_is_router(na);
         if (r < 0)
```

**Comment by LiveFreeAndRoam** [comment]
Probably a better way to look at this is that the processing for `IsRouter` flag ought to trump checks for `solicited` and `override` flags.  In which case, a more appropriate patch would be to move the `IsRouter` processing above other checks.  E.g.:

```
diff --git a/src/network/networkd-ndisc.c b/src/network/networkd-ndisc.c
index 672e07438d..58794ed18e 100644
--- a/src/network/networkd-ndisc.c
+++ b/src/network/networkd-ndisc.c
@@ -1819,16 +1819,6 @@ static int ndisc_neighbor_handler(Link *link, sd_ndisc_neighbor *na) {
         assert(link);
         assert(na);
 
-        /* Currently, we do not send neighbor solicitation. Hence, ignore solicited neighbor advertisement. */
-        r = sd_ndisc_neighbor_is_solicited(na);
-        if (r != 0)
-                return r;
-
-        /* It is not necessary to update anything if the override flag is not set. */
-        r = sd_ndisc_neighbor_is_override(na);
-        if (r <= 0)
-                return r;
-
         r = sd_ndisc_neighbor_is_router(na);
         if (r < 0)
                 return r;
@@ -1839,6 +1829,16 @@ static int ndisc_neighbor_handler(Link *link, sd_ndisc_neighbor *na) {
         if (r < 0)
                 return r;
 
+        /* Currently, we do not send neighbor solicitation. Hence, ignore solicited neighbor advertisement. */
+        r = sd_ndisc_neighbor_is_solicited(na);
+        if (r != 0)
+                return r;
+
+        /* It is not necessary to update anything if the override flag is not set. */
+        r = sd_ndisc_neighbor_is_override(na);
+        if (r <= 0)
+                return r;
+
         return 0;
 }
```

File: src/libsystemd-network/sd-ndisc-neighbor.c [hunk 1]
```diff
@@ -0,0 +1,172 @@
...
+         * address has changed. The Target Address MUST NOT be a multicast address.
+         *
+         * Here, we only check if the target address is a link-layer address (or a null address, for safety)
+         * when the message is an unsolicited neighbor advertisement. */
+        if (!FLAGS_SET(na->flags, ND_NA_FLAG_SOLICITED)) {
+                if (!in6_addr_is_link_local(&na->target_address) && !in6_addr_is_null(&na->target_address))
+                        return log_ndisc_errno(nd, SYNTHETIC_ERRNO(EBADMSG),
+                                               "Received ND packet with wrond NA target address (%s), ignoring.",
+                                               IN6_ADDR_TO_STRING(&na->target_address));
+        }
```
Comment (poettering) [inline src/libsystemd-network/sd-ndisc-neighbor.c]: the {} is redudnant.

File: src/network/networkd-ndisc.c [hunk 2]
```diff
@@ -1297,7 +1297,7 @@ static int ndisc_router_process_options(Link *link, sd_ndisc_router *rt) {
         }
 }
 
-static int ndisc_drop_outdated(Link *link, usec_t timestamp_usec) {
+static int ndisc_drop_outdated(Link *link, struct in6_addr *router, usec_t timestamp_usec) {
```
Comment (poettering) [inline src/network/networkd-ndisc.c]: const?

File: src/libsystemd-network/sd-radv.c [hunk 3]
```diff
@@ -127,6 +127,44 @@ static bool router_lifetime_is_valid(usec_t lifetime_usec) {
                  lifetime_usec <= RADV_MAX_ROUTER_LIFETIME_USEC);
 }
 
+static int radv_send_router_on_stop(sd_radv *ra) {
+        assert(ra);
+
+        struct sockaddr_in6 dst_addr = {
+                .sin6_family = AF_INET6,
+                .sin6_addr = IN6ADDR_ALL_NODES_MULTICAST_INIT,
+        };
```
Comment (poettering) [inline src/libsystemd-network/sd-radv.c]: this is not modified, hence make it static const?

File: src/libsystemd-network/sd-radv.c [hunk 4]
```diff
@@ -127,6 +127,44 @@ static bool router_lifetime_is_valid(usec_t lifetime_usec) {
...
+        struct nd_router_advert adv = {
+                .nd_ra_type = ND_ROUTER_ADVERT,
+        };
```
Comment (poettering) [inline src/libsystemd-network/sd-radv.c]: ditto

File: src/libsystemd-network/sd-radv.c [hunk 5]
```diff
@@ -398,6 +400,115 @@ static int radv_timeout(sd_event_source *s, uint64_t usec, void *userdata) {
...
+                sd_radv *ra,
+                const struct in6_addr *dst,
+                uint32_t flags) {
+
+        assert(ra);
+
+        struct sockaddr_in6 dst_addr = {
+                .sin6_family = AF_INET6,
+                .sin6_addr = IN6ADDR_ALL_NODES_MULTICAST_INIT,
+        };
```
Comment (poettering) [inline src/libsystemd-network/sd-radv.c]: static const?

File: src/libsystemd-network/sd-radv.c [hunk 6]
```diff
@@ -398,6 +400,115 @@ static int radv_timeout(sd_event_source *s, uint64_t usec, void *userdata) {
...
+
+        ssize_t buflen = next_datagram_size_fd(fd);
+        if (ERRNO_IS_NEG_TRANSIENT(buflen) || ERRNO_IS_NEG_DISCONNECT(buflen))
+                return 0;
+        if (buflen < 0) {
+                log_radv_errno(ra, buflen, "Failed to determine datagram size to read, ignoring: %m");
+                return 0;
+        }
+
+        _cleanup_free_ uint8_t *buf = new0(uint8_t, buflen);
```
Comment (poettering) [inline src/libsystemd-network/sd-radv.c]: why new0() rather than new()?

**Comment by LiveFreeAndRoam** [comment]
I want to add a little more context... (for future reference)

Even though networkd is not yet sending NS packets, the kernel does.

The neighbor responds to an NS with an NA (`solicited`).  In that same NA it could also flip the (`IsRouter`) flag.  So, regardless of the NA `solicited` flag, we still need to process the `IsRouter` flag for routes that networkd created.

**Comment by LiveFreeAndRoam** [comment]
_Question_: Currently, networkd intercepts the RA packets and prevents the kernel from processing them by setting the sysctl variable `accept_ra=0`.  With NA packets, it looks like both networkd and the kernel will process them, since there doesn't appear to be a way to tell the kernel to ignore them. For NA packets, I think this is ok (and necessary) because the kernel will need to resolve a neighbor's address with an NS/NA exchange. Though, it leaves me wondering if there are cases where having both _networkd_ and the _kernel_ process the same NA might cause problems.

Thoughts?

**Comment by LiveFreeAndRoam** [comment]
FYI, I'm running the IPv6 Conformance _Base_ tests,  using my patch (described above).  The tests will be complete in about 3 hours.  I'll need another hour to collate the results and report my findings.  Keep in mind, these are just the _Base_ tests (a collection of **333** protocol tests). There are another set of tests (_PMTU, DAD, Ping_ - **81** tests in total) that take quite a bit longer to run, so those results will come at a later point in time.

**Comment by LiveFreeAndRoam** [comment]
Today's results are in... there has been a big improvement since we first started looking at these issues.

In summary:

| Version | v254<sup>(1)</sup> | v255<sup>(2)</sup> | v255+patches to-current-date<sup>(1)</sup> |
|--------|--------|--------|--------|
| **Passing** | 31 | 36 | 53 |
| **Failing** | 42 | 67 | 22 |
| **TBD** | 28 | 0 | 28 |

* **(1)** Only base tests were run. There are 28 more tests that have failed in the past that I am yet to run.
* **(2)** All tests were run

I'll write up the next batch of cases that would be good to address.

File: src/libsystemd-network/sd-radv.c (hunk 3 above)
Comment (yuwata) [reply src/libsystemd-network/sd-radv.c]: It can be, but if we make it static const, we need to cast it when setting `msg.msg_name`.

File: src/libsystemd-network/sd-radv.c (hunk 5 above)
Comment (yuwata) [reply src/libsystemd-network/sd-radv.c]: The same as the above.

**Review by LiveFreeAndRoam — CHANGES_REQUESTED** [review]
I still need the changes referenced in my [comment ](https://github.com/systemd/systemd/pull/31373#issuecomment-1951939104) to be applied.  The IPv6 Compliance test won't pass without those changes.

I also consulted with the owners of the test program, and they confirmed the R flag must be processed independently of the O or S flags.

**Review by LiveFreeAndRoam — APPROVED** [review]
Getting in with an early approval.  Tests pass and code looks good to me.

**Comment by yuwata** [comment]
Will push an updated version after #31423 is merged.

**Comment by LiveFreeAndRoam** [comment]
Sorry to say, but these tests are failing again.  I'm build with SHA ba8017c0d3.

I won't get a chance to investigate until I get back from 1 week away.

**Comment by yuwata** [comment]
@LiveFreeAndRoam Sorry for late. Could you try with this branch again?

**Comment by yuwata** [comment]
Yay, CentOS CIs are green again. @LiveFreeAndRoam Could you test again?

**Comment by LiveFreeAndRoam** [comment]
The tests from the 2.1.21 suite are still failing.  I will investigate further a little later today.  Let me know if there is something specific you'd like me to look for.

I rebuilt using:

```
$ git log -n 1
commit 59b72d6f47160c74a1d7f44bc3e2373b4e14dd58 (HEAD -> network-next, origin/network-next)
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Sat Mar 16 02:32:50 2024 +0900
```

**Comment by yuwata** [comment]
Hm, debugging logs of networkd please.

**Comment by LiveFreeAndRoam** [comment]
@yuwata, here is the debug log after running _2.1.21a_.


```
enp0s9: NDISC: Received Router Advertisement: flags none preference medium lifetime 20s
enp0s9: NDISC: Invoking callback for 'router' event.
enp0s9: Requesting NDisc route (n/a): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
Setting '/proc/sys/net/ipv6/neigh/enp0s9/base_reachable_time_ms' to '100000'
No change in value '100000', suppressing write
Setting '/proc/sys/net/ipv6/neigh/enp0s9/retrans_time_ms' to '1000'
No change in value '1000', suppressing write
Setting '/proc/sys/net/ipv6/conf/enp0s9/hop_limit' to '64'
No change in value '64', suppressing write
enp0s9: Requesting NDisc route (n/a): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Requesting NDisc address (n/a): 2001:2:0:1000:f1c5:7f81:2ff6:19fd/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: Setting SLAAC addresses and router.
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: Configuring NDisc route (requesting): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Configuring NDisc route (requesting): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Configuring NDisc address (requesting): 2001:2:0:1000:f1c5:7f81:2ff6:19fd/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: Received new NDisc route (configured): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: ndisc_check_ready(): SLAAC addresses and routes are not set.
enp0s9: Received new NDisc route (configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: ndisc_check_ready(): SLAAC addresses and routes are not set.
enp0s9: Received new NDisc address (configured): 2001:2:0:1000:f1c5:7f81:2ff6:19fd/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: tentative,manage-temporary-address,no-prefixroute, scope: global
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: ndisc_check_ready(): no SLAAC address is ready.
enp0s9: Received updated NDisc address (configured): 2001:2:0:1000:f1c5:7f81:2ff6:19fd/64 (valid for 18h 12min 13s, preferred for 18h 12min 13s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: SLAAC addresses and routes set.
enp0s9: link_check_ready(): IPv4LL:no DHCPv4:no DHCPv6:no DHCP-PD:no NDisc:yes
enp0s9: State changed: configuring -> configured
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=21 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=22 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=23 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
enp0s9: Received new foreign route (configured): dst: 2001:2:0:1000:f1c5:7f81:2ff6:19fd/128, src: n/a, gw: n/a, prefsrc: n/a, table: local(255), priority: 0, proto: kernel, scope: global, type: local, flags: n/a
enp0s9: NDISC: Received Router Advertisement: flags none preference medium lifetime 0
enp0s9: NDISC: Invoking callback for 'router' event.
enp0s9: Removing NDisc route (configured): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Found an existing route that conflicts with new route based on a received RA, removing.
enp0s9: Removing NDisc route (configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Requesting NDisc route (configured,removing): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Setting SLAAC addresses and router.
enp0s9: Refuse to configure NDisc route with zero lifetime.
enp0s9: Forgetting removed NDisc route (n/a): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Forgetting removed NDisc route (n/a): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
```

**Comment by LiveFreeAndRoam** [comment]
I corrected the config file (disabling the stable-privacy that I needed for other tests to pass). I reran the tests and they are passing.  

This issue can be closed.

@yuwata, Apologies for the misdirect; my dud results were a quick test between other tasks and I had forgotten about the stable-privacy changes to make other tests pass.

**Comment by yuwata** [comment]
@LiveFreeAndRoam Thank you for testing! I am happy to hear that this now works fine.

@bluca @YHNdnzj @keszybz This is now ready for review. Could you review this?

**Comment by yuwata** [comment]
Note, our own test case will be added later, already waiting in #30569.

File: src/libsystemd-network/sd-ndisc.c [hunk 7]
```diff
@@ -225,6 +227,31 @@ static int ndisc_handle_router(sd_ndisc *nd, ICMP6Packet *packet) {
...
+        na = ndisc_neighbor_new(packet);
+        if (!na)
+                return -ENOMEM;
+
+        r = ndisc_neighbor_parse(nd, na);
+        if (r < 0)
+                return r;
+
+        log_ndisc(nd, "Received Neighbor Advertisement from %s: Router=%s, Solicited=%s, Override=%s",
+                  IN6_ADDR_TO_STRING(&na->packet->sender_address),
```
Comment (bluca) [inline src/libsystemd-network/sd-ndisc.c]: ASSERT_PTR or check na->packet

File: src/network/networkd-ndisc.c [hunk 8]
```diff
@@ -1679,6 +1697,131 @@ static int ndisc_router_handler(Link *link, sd_ndisc_router *rt) {
...
 }
 
+static int ndisc_neighbor_handle_non_router_message(Link *link, sd_ndisc_neighbor *na) {
+        struct in6_addr address;
+        int r;
+
+        assert(link);
+        assert(na);
+
+        /* Received Neighbor Advertisement message without Router flag. The node might be a router, and now
```
Comment (bluca) [inline src/network/networkd-ndisc.c]: "might have been a router"

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
@bluca Thank you for the review. The above comments are addressed. Upgrading the green label.
