### PR TITLE
network: also check ID_NET_MANAGED_BY property on reconfigure

### LINKED ISSUE #36997: unmanaged interfaces (as marked by udev rule) unexpectedly configured in small percent of boots
### systemd version the issue has been seen with

257.4-3.fc43

### Used distribution

Fedora Rawhide

### Linux kernel version used

6.15.0-0.rc0.20250401git08733088b566.8.fc43.aarch64

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

### Expected behaviour you didn't see

Enslaved SRIOV mlx interface is marked as unmanaged by udev.  networkd initially honors the unmagaed state but something appears to trip it into initializing and attempting to configure it.  Restarting networkd fixes the isue.

[journal.txt](https://github.com/user-attachments/files/19592670/journal.txt)

### Unexpected behaviour you saw

Some small percentage of the time, networkd suddenly disregards the unmanaged state and starts managing the interface incorrectly.  A restart of systemd-networkd.service will restore the link as unmanaged.

### Steps to reproduce the problem

Create, or reboot Azure VM with accelerated networking (may take hundreds of reboots to reproduce).

This is reproduced on a number of different distros and versions of systemd on a variety on amd64 and aarch64.  Some scenario combinations cause higher rates of failure (e.g. Azure v6 arm64 vm sizes).  This focuses on a Fedora rawhide failure on arm64 v5 vm size.

```
[cpatterson@temp-vm-cpatterson-selftest-3dd98c31 ~]$ cat /etc/systemd/network/10-dhcp.network
[Match]
Name=e*

[Network]
DHCP=ipv4
LinkLocalAddressing=ipv6

[DHCP]
RouteMetric=100
UseMTU=true

[cpatterson@temp-vm-cpatterson-selftest-3dd98c31 ~]$ cat /usr/lib/udev/rules.d/10-azure-unmanaged-sriov.rules
# Azure VMs with accelerated networking may have MANA, mlx4, or mlx5 SR-IOV devices which are transparently bonded to a synthetic
# hv_netvsc device.  Mark devices with the IFF_SLAVE bit set as unmanaged devices:
#   AZURE_UNMANAGED_SRIOV=1 for 10-azure-unmanaged-sriov.network
#   ID_NET_MANAGED_BY=unmanaged for systemd-networkd >= 255
#   NM_UNMANAGED=1 for NetworkManager
#
# ATTR{flags}=="0x?[89ABCDEF]??" checks the IFF_SLAVE bit (0x800).
#
# NOTE: this is changed from upstream to add logger debugs.
#
SUBSYSTEM=="net", DRIVERS=="hv_netvsc|mana|mlx4_core|mlx5_core", RUN+="/bin/sh -c 'logger -t azure-unmanaged-sriov-udev \"checking action=$env{ACTION} device=$env{INTERFACE} driver=$attr{driver} flags=$attr{flags}\"'"
SUBSYSTEM=="net", ACTION!="remove", DRIVERS=="mana|mlx4_core|mlx5_core", ATTR{flags}=="0x?[89ABCDEF]??", ENV{AZURE_UNMANAGED_SRIOV}="1", ENV{ID_NET_MANAGED_BY}="unmanaged", ENV{NM_UNMANAGED}="1", RUN+="/bin/sh -c 'logger -t azure-unmanaged-sriov-udev \"marked device unmanaged for action=$env{ACTION} device=$env{INTERFACE} driver=$attr{driver} flags=$attr{flags}\"'"


[cpatterson@temp-vm-cpatterson-selftest-3dd98c31 ~]$ cat /usr/lib/systemd/network/10-azure-unmanaged-sriov.network
# Azure VMs with accelerated networking may have MANA, mlx4, or mlx5 SR-IOV
# devices which are transparently bonded to a synthetic hv_netvsc device.
# 10-azure-unmanaged-sriov.rules will mark these devices with
# AZURE_UNMANAGED_SRIOV=1 so this can configure the devices as unmanaged.

[Match]
Property=AZURE_UNMANAGED_SRIOV=1

[Link]
Unmanaged=yes
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[    9.061471] temp-vm-cpatterson-selftest-3dd98c31 azure-unmanaged-sriov-udev[968]: marked device unmanaged for action=add device=eth1 driver=mlx5_core flags=0x1802
[    9.325565] temp-vm-cpatterson-selftest-3dd98c31 azure-unmanaged-sriov-udev[972]: checking action=move device=enP25476s1 driver=mlx5_core flags=0x1802
[    9.328239] temp-vm-cpatterson-selftest-3dd98c31 azure-unmanaged-sriov-udev[973]: marked device unmanaged for action=move device=enP25476s1 driver=mlx5_core flags=0x1802
...
[    9.497770] temp-vm-cpatterson-selftest-3dd98c31 kernel: mlx5_core 6384:00:02.0 enP25476s1: Link up
[    9.498258] temp-vm-cpatterson-selftest-3dd98c31 kernel: hv_netvsc 6045bdb5-b81f-6045-bdb5-b81f6045bdb5 eth0: Data path switched to VF: enP25476s1
[    9.147817] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[736]: enP25476s1: Starting '/usr/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/enP25476s1 --prefix=/net/ipv4/neigh/enP25476s1 --prefix=/net/ipv6/conf/enP25476s1 --prefix=/net/ipv6/neigh/enP25476s1'
[    9.147894] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: /usr/lib/systemd/network/10-azure-unmanaged-sriov.network: Successfully loaded.
[    9.152329] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Saved new link: ifindex=3, iftype=ETHER(1), kind=n/a
[    9.152375] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Saved original MTU 1500 (min: 68, max: 9978)
[    9.152426] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Saved permanent hardware address: 60:45:bd:b5:b8:1f
[    9.152467] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Saved hardware address: 60:45:bd:b5:b8:1f
[    9.152517] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Failed to manage link by its new hardware address, ignoring: File exists
[    9.152560] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Attached to master interface: 2
[    9.152602] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Saved IPv6 link-local address generation mode: eui64
[    9.152638] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Flags change: +SLAVE +MULTICAST +BROADCAST
[    9.204705] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[736]: enP25476s1: Process '/usr/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/enP25476s1 --prefix=/net/ipv4/neigh/enP25476s1 --prefix=/net/ipv6/conf/enP25476s1 --prefix=/net/ipv6/neigh/enP25476s1' succeeded.
[    9.205111] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[736]: enP25476s1: sd-device: Created database file '/run/udev/data/n3' for '/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/MSFT1000:00/7bca5ee7-6384-409d-8345-90de60690756/pci6384:00/6384:00:02.0/net/enP25476s1'.
[    9.205216] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[736]: enP25476s1: Device processed (SEQNUM=3851, ACTION=add)
[    9.205355] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[736]: enP25476s1: sd-device-monitor(worker): Passed 1088 byte to netlink monitor.
[    9.210330] temp-vm-cpatterson-selftest-3dd98c31 systemd-udevd[708]: enP25476s1: SEQNUM=3884 blocked by SEQNUM=3852
[    9.210529] temp-vm-cpatterson-selftest-3dd98c31 systemd-udevd[708]: enP25476s1: SEQNUM=3884 blocked by SEQNUM=3864
[    9.210760] temp-vm-cpatterson-selftest-3dd98c31 systemd-udevd[708]: enP25476s1: SEQNUM=3884 blocked by SEQNUM=3865
[    9.210833] temp-vm-cpatterson-selftest-3dd98c31 systemd-udevd[708]: enP25476s1: SEQNUM=3884 blocked by SEQNUM=3867
[    9.211029] temp-vm-cpatterson-selftest-3dd98c31 systemd-udevd[708]: enP25476s1: SEQNUM=3884 blocked by SEQNUM=3871
[    9.314777] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Interface is being renamed, pending initialization.
[    9.314908] temp-vm-cpatterson-selftest-3dd98c31 systemd-udevd[708]: enP25476s1: Device ready for processing (SEQNUM=3884, ACTION=move)
[    9.314935] temp-vm-cpatterson-selftest-3dd98c31 systemd-udevd[708]: enP25476s1: sd-device-monitor(manager): Passed 438 byte to netlink monitor.
[    9.315293] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: Processing device (SEQNUM=3884, ACTION=move)
[    9.315540] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: sd-device: Created database file '/run/udev/data/n3' for '/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/MSFT1000:00/7bca5ee7-6384-409d-8345-90de60690756/pci6384:00/6384:00:02.0/net/enP25476s1'.
[    9.315983] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: /usr/lib/udev/rules.d/10-azure-unmanaged-sriov.rules:8 RUN '/bin/sh -c 'logger -t azure-unmanaged-sriov-udev "checking action=$env{ACTION} device=$env{INTERFACE} driver=$attr{driver} flags=$attr{flags}"''
[    9.316136] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: /usr/lib/udev/rules.d/10-azure-unmanaged-sriov.rules:9 RUN '/bin/sh -c 'logger -t azure-unmanaged-sriov-udev "marked device unmanaged for action=$env{ACTION} device=$env{INTERFACE} driver=$attr{driver} flags=$attr{flags}"''
[    9.316184] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: /usr/lib/udev/rules.d/50-udev-default.rules:31 Importing properties from results of builtin command 'net_driver'
[    9.316318] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Device is renaming, waiting for the interface to be renamed.
[    9.316932] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: /usr/lib/udev/rules.d/75-net-description.rules:6 Importing properties from results of builtin command 'hwdb 'net:naming:drmlx5_core:''
[    9.316943] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: No entry found from hwdb.
[    9.316949] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: /usr/lib/udev/rules.d/75-net-description.rules:6 Failed to run builtin 'hwdb 'net:naming:drmlx5_core:'': No data available
[    9.316954] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: /usr/lib/udev/rules.d/75-net-description.rules:8 Importing properties from results of builtin command 'net_id'
[    9.317189] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: MAC address identifier: hw_addr=60:45:bd:b5:b8:1f → x6045bdb5b81f
[    9.317386] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: sd-device: Failed to chase symlinks in "/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/MSFT1000:00/7bca5ee7-6384-409d-8345-90de60690756/pci6384:00/6384:00:02.0/net/enP25476s1/of_node".
[    9.317528] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: Failed to get device of_node, ignoring: No such device
[    9.317714] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: New interface name 'eth1' received from the kernel does not correspond with the name currently configured on the actual interface 'enP25476s1'. Ignoring.
[    9.317751] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: New interface name 'eth1' received from the kernel does not correspond with the name currently configured on the actual interface 'enP25476s1'. Ignoring.
[    9.317788] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: New interface name 'eth1' received from the kernel does not correspond with the name currently configured on the actual interface 'enP25476s1'. Ignoring.
[    9.318867] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: PCI path identifier: domain=P25476 bus_and_slot=p0s2 func=n/a port=n/a → enP25476p0s2
[    9.319347] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: PCI slot identifier: domain=P25476 slot=1 func=n/a port=n/a → enP25476s1
[    9.319385] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: Could not find USB parent device: No such file or directory
[    9.319470] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: Could not get BCMA parent device: No such file or directory
[    9.319552] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: /usr/lib/udev/rules.d/75-net-description.rules:14 Importing properties from results of builtin command 'hwdb --subsystem=pci'
[    9.319632] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: hwdb modalias key: "pci:v000015B3d00001018sv000015B3sd00000080bc02sc00i00"
[    9.319921] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: /usr/lib/udev/rules.d/80-net-setup-link.rules:5 Importing properties from results of builtin command 'path_id'
[    9.320016] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: /usr/lib/udev/rules.d/80-net-setup-link.rules:9 Importing properties from results of builtin command 'net_setup_link'
[    9.320106] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: Device has name_assign_type=4
[    9.320213] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: Device has addr_assign_type=0
[    9.321639] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: Config file /usr/lib/systemd/network/99-default.link is applied
[    9.321733] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: MAC address on the device already matches policy "persistent".
[    9.321820] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: Not applying Name= and NamePolicy= on 'move' uevent.
[    9.321903] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: Not applying AlternativeNames= and AlternativeNamesPolicy= on 'move' uevent.
[    9.321997] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: /usr/lib/udev/rules.d/80-net-setup-link.rules:11 NAME 'enP25476s1'
[    9.322159] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: sd-device: Created database file '/run/udev/data/n3' for '/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/MSFT1000:00/7bca5ee7-6384-409d-8345-90de60690756/pci6384:00/6384:00:02.0/net/enP25476s1'.
[    9.328506] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: sd-device: Created database file '/run/udev/data/n3' for '/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/MSFT1000:00/7bca5ee7-6384-409d-8345-90de60690756/pci6384:00/6384:00:02.0/net/enP25476s1'.
[    9.328514] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: Device processed (SEQNUM=3884, ACTION=move)
[    9.328591] temp-vm-cpatterson-selftest-3dd98c31 (udev-worker)[713]: enP25476s1: sd-device-monitor(worker): Passed 1195 byte to netlink monitor.
[    9.498348] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Interface is requested to be managed by 'unmanaged', not managing the interface.
[    9.498354] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: State changed: pending -> unmanaged
[    9.498615] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Flags change: +UP +LOWER_UP
[    9.498651] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Link UP
[    9.513420] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Flags change: +RUNNING
[    9.513474] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Gained carrier
[    9.513481] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Found matching .network file: /etc/systemd/network/10-dhcp.network
[    9.513485] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: Configuring with /etc/systemd/network/10-dhcp.network.
[    9.513513] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: State changed: unmanaged -> initialized
[    9.513534] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: State changed: initialized -> configuring
[    9.513558] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: link_check_ready(): link is not activated.
[    9.513562] temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: link_check_ready(): link is not activated.


[cpatterson@temp-vm-cpatterson-selftest-3dd98c31 ~]$ uname -a
Linux temp-vm-cpatterson-selftest-3dd98c31 6.15.0-0.rc0.20250401git08733088b566.8.fc43.aarch64 #1 SMP PREEMPT_DYNAMIC Tue Apr  1 20:39:13 UTC 2025 aarch64 GNU/Linux

[cpatterson@temp-vm-cpatterson-selftest-3dd98c31 ~]$ systemctl --version
systemd 257 (257.4-3.fc43)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +IPE +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +BTF +XKBCOMMON +UTMP +SYSVINIT +LIBARCHIVE

[cpatterson@temp-vm-cpatterson-selftest-3dd98c31 ~]$ networkctl
IDX LINK       TYPE     OPERATIONAL SETUP
  1 lo         loopback carrier     unmanaged
  2 eth0       ether    routable    configured
  3 enP25476s1 ether    routable    configuring

3 links listed.

[cpatterson@temp-vm-cpatterson-selftest-3dd98c31 ~]$ networkctl status enP25476s1
● 3: enP25476s1
                   Link File: /usr/lib/systemd/network/99-default.link
                Network File: /etc/systemd/network/10-dhcp.network
                       State: routable (configuring)
                Online state: online
                        Type: ether
                        Path: acpi-MSFT1000:00-pci-6384:00:02.0
                      Driver: mlx5_core
                      Vendor: Mellanox Technologies
                       Model: MT27800 Family [ConnectX-5 Virtual Function]
           Alternative Names: enP25476p0s2
            Hardware Address: 60:45:bd:b5:b8:1f (Microsoft)
                         MTU: 1500 (min: 68, max: 9978)
                       QDisc: mq
                      Master: eth0
IPv6 Address Generation Mode: eui64
    Number of Queues (Tx/Rx): 64/8
            Auto negotiation: yes
                       Speed: 100Gbps
                      Duplex: full
                     Address: 10.0.0.78 (DHCPv4 via 168.63.129.16)
                              fe80::6245:bdff:feb5:b81f
                         DNS: 168.63.129.16
           Activation Policy: up
         Required For Online: yes
            DHCPv4 Client ID: IAID:0xb7f2c20e/DUID
          DHCPv6 Client DUID: DUID-EN/Vendor:0000ab11fbe17c1798c7ca5c

Apr 03 16:43:36 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
Apr 03 16:43:37 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: NDISC: Sent Router Solicitation, next solicitation in 15s
Apr 03 16:43:52 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: NDISC: Sent Router Solicitation, next solicitation in 29s
Apr 03 16:44:21 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: NDISC: Sent Router Solicitation, next solicitation in 1min
Apr 03 16:45:22 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: NDISC: Sent Router Solicitation, next solicitation in 2min
Apr 03 16:47:23 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: NDISC: Sent Router Solicitation, next solicitation in 4min 10s
Apr 03 16:51:33 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: NDISC: Sent Router Solicitation, next solicitation in 8min 18s
Apr 03 16:59:51 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: NDISC: Sent Router Solicitation, next solicitation in 17min 7s
Apr 03 17:16:58 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: NDISC: Sent Router Solicitation, next solicitation in 34min 54s
Apr 03 17:51:53 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[957]: enP25476s1: NDISC: Sent Router Solicitation, next solicitation in 1h 3min 31s


[cpatterson@temp-vm-cpatterson-selftest-3dd98c31 ~]$ sudo systemctl restart systemd-networkd.service
[cpatterson@temp-vm-cpatterson-selftest-3dd98c31 ~]$ networkctl
IDX LINK       TYPE     OPERATIONAL SETUP
  1 lo         loopback carrier     unmanaged
  2 eth0       ether    routable    configured
  3 enP25476s1 ether    routable    unmanaged

3 links listed.
[cpatterson@temp-vm-cpatterson-selftest-3dd98c31 ~]$ networkctl status enP25476s1
● 3: enP25476s1
                   Link File: /usr/lib/systemd/network/99-default.link
                Network File: n/a
                       State: routable (unmanaged)
                Online state: unknown
                        Type: ether
                        Path: acpi-MSFT1000:00-pci-6384:00:02.0
                      Driver: mlx5_core
                      Vendor: Mellanox Technologies
                       Model: MT27800 Family [ConnectX-5 Virtual Function]
           Alternative Names: enP25476p0s2
            Hardware Address: 60:45:bd:b5:b8:1f (Microsoft)
                         MTU: 1500 (min: 68, max: 9978)
                       QDisc: mq
                      Master: eth0
IPv6 Address Generation Mode: eui64
    Number of Queues (Tx/Rx): 64/8
            Auto negotiation: yes
                       Speed: 100Gbps
                      Duplex: full
                     Address: 10.0.0.78
                              fe80::6245:bdff:feb5:b81f

Apr 03 18:07:41 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[2554]: enP25476s1: Received new foreign route (configured): dst: fe80::6245:bdff:feb5:b81f/128, src: n/a, gw: n/a, prefsrc: n/a, table: local(255), priority: 0, proto: kernel, scope>
Apr 03 18:07:41 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[2554]: enP25476s1: Received remembered foreign route (configured): dst: fe80::6245:bdff:feb5:b81f/128, src: n/a, gw: n/a, prefsrc: n/a, table: local(255), priority: 0, proto: kernel>
Apr 03 18:07:41 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[2554]: enP25476s1: Deserialized DHCPv4 address (configured): 10.0.0.78/24 broadcast 10.0.0.255 (valid forever, preferred forever), flags: permanent, scope: global, label: n/a
Apr 03 18:07:41 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[2554]: enP25476s1: udev initialized link
Apr 03 18:07:41 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[2554]: enP25476s1: Found driver: mlx5_core
Apr 03 18:07:41 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[2554]: enP25476s1: Link state is up-to-date
Apr 03 18:07:41 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[2554]: enP25476s1: State changed: pending -> initialized
Apr 03 18:07:41 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[2554]: enP25476s1: Found matching .network file: /usr/lib/systemd/network/10-azure-unmanaged-sriov.network
Apr 03 18:07:41 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[2554]: enP25476s1: Unmanaging interface.
Apr 03 18:07:41 temp-vm-cpatterson-selftest-3dd98c31 systemd-networkd[2554]: enP25476s1: State changed: initialized -> unmanaged
```

### PR DESCRIPTION
**Pull request by yuwata**
Previously, the property was checked only when an uevent is received, so even if an interface has ID_NET_MANAGED_BY property, the interface will be configured by networkd when reconfiguration is triggered e.g. when interface state is changed.

Follow-up for ba87a61d05d637be9f0b21707f7fe3b0a74c5a05.
Fixes #36997.

### CODE REVIEW

**Comment by cjp256** [comment]
Thank you @yuwata @bluca !

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -1369,6 +1369,32 @@ static void link_enter_unmanaged(Link *link) {
...
+        if (r == -ENOENT)
+                return true;
+        if (r < 0)
+                return log_link_warning_errno(link, r, "Failed to get ID_NET_MANAGED_BY udev property: %m");
+
+        if (streq(s, "io.systemd.Network"))
+                return true;
+
+        if (link->state == LINK_STATE_UNMANAGED)
+                return false; /* Already in unmanaged state */
```
Comment (jepio) [inline src/network/networkd-link.c:1391]: shouldn't this check be earlier in the function?

Comment (yuwata) [reply src/network/networkd-link.c:1391]: Hm? I don't think so? Do you find any issues?
