### PR TITLE
network: directly compare with in_addr element for IPv4 case

### LINKED ISSUE #17304: network: No static address is stored
**systemd version the issue has been seen with**
 > 246.6-1-arch

**Used distribution**
 > Arch Linux

**Unexpected behaviour you saw**
 > dummy0: No static address is stored.
 > dummy0: Failed

**Steps to reproduce the problem**
1. prepare configuration files
   ```
   # /etc/systemd/network/dummy0.netdev
   [NetDev]
   Name=dummy0
   Kind=dummy
   ```
   ```
   # /etc/systemd/network/dummy0.network
   [Match]
   Name=dummy0

   [Address]
   Address=100.64.0.1/32
   Peer=100.64.0.2/32
   ```
2. `networkctl reload`. The `dummy0` interface is shown as `routable` and `configured` after IPv6 DAD.
3. `systemctl restart systemd-networkd`. The `dummy0` interface is shown as `routable` and `failed`.

This issue is somehow related to prefix length, and only affect point-to-point address.

### PR DESCRIPTION
**Pull request by yuwata**
When peer address is set, address_compare() (or address_equal()) mostly
does not work in link_is_static_address_configured(), as an Address object
stored in a Link does not contain peer addresses. So, we need to also
compare with in_addr element for IPv4 case.

Fixes #17304.

### CODE REVIEW

File: src/network/networkd-address.c [hunk 1]
```diff
@@ -551,6 +551,9 @@ static bool link_is_static_address_configured(Link *link, Address *address) {
                 else if (address->family == AF_INET6 && net_address->family == AF_INET6 &&
                          in_addr_equal(AF_INET6, &address->in_addr, &net_address->in_addr_peer) > 0)
                         return true;
+                else if (address->family == AF_INET && net_address->family == AF_INET &&
+                         in_addr_equal(AF_INET, &address->in_addr, &net_address->in_addr) > 0)
```
Comment (keszybz) [inline src/network/networkd-address.c]: I don't understand this comparison. We check in_addr_peer for AF_INET6 and in_addr for AF_INET... So I think this at least needs a comment in the code why `address_equal()` doesn't suffice and why we are comparing different fields for different protocols.

Comment (yuwata) [reply src/network/networkd-address.c]: I added a comment.

**Comment by yuwata** [comment]
@keszybz Thank you for the comment. I added why `address_equal()` does not work in the code. As the first commit is a kind of workaround, I added a commit that fixes the issue comprehensively. Also a test is added. PTAL.

File: src/network/networkd-address.c [hunk 2]
```diff
@@ -1854,6 +1853,25 @@ static int address_section_verify(Address *address) {
                                          address->section->filename, address->section->line);
         }
 
+        if (address->family == AF_INET && in_addr_is_null(address->family, &address->in_addr_peer) &&
+            address->broadcast.s_addr == 0 && address->prefixlen <= 30)
+                address->broadcast.s_addr = address->in_addr.in.s_addr | htobe32(0xfffffffflu >> address->prefixlen);
+        else if (address->broadcast.s_addr != 0) {
+                log_warning("%s: broadcast address is set for IPv6 address or IPv4 address with prefixlength larger than 30. "
+                            "Ignoring Broadcast= setting in the [Addres] section from line %u.",
```
Comment (zhangyoufu) [inline src/network/networkd-address.c]: typo

Comment (yuwata) [reply src/network/networkd-address.c]: Ouch. Thanks.

File: test/test-network/systemd-networkd-tests.py [hunk 3]
```diff
@@ -1886,6 +1887,21 @@ def test_address_dad(self):
...
+        for trial in range(2):
+            if trial == 0:
+                start_networkd()
+            else:
+                restart_networkd()
+
+            self.wait_online(['dummy98:routable'])
+
+            output = check_output('ip -4 address show dev dummy98')
+            self.assertRegex(output, 'inet 100.64.0.1 peer 100.64.0.2/32 scope global')
```
Comment (zhangyoufu) [inline test/test-network/systemd-networkd-tests.py]: Dots are not escaped for regex pattern. I would prefer `assertIn` rather than `assertRegex`.

File: src/network/networkd-address.c (hunk 1 above)
Comment (keszybz) [reply src/network/networkd-address.c]: Thanks. This helps a lot. I still don't understand the second `else if` though:
you say that "Address stored in Link does not [contain the peer address]", so I don't understand why we're comparing the two.
`address_equal()` calls `address_compare_func()` which does `memcmp(&a1->in_addr, &a2->in_addr)`. Is this supposed to return a different result than `in_addr_equal()`?

**Comment by j0k4rX** [comment]
hello @zhangyoufu, i checked your Fixedsys repository & got a question for you -> how can i change the font size according to my own will ? what process should i follow ?
Thanks. waitin' for your feedback.

File: src/network/networkd-address.c (hunk 1 above)
Comment (yuwata) [reply src/network/networkd-address.c]: Not only `in_addr` element, but `address_compare_func()` also compares prefix generated by `address_prefix()` it may return different value if a peer address is set.

The comment in the code is revised.

File: test/test-network/systemd-networkd-tests.py (hunk 3 above)
Comment (yuwata) [reply test/test-network/systemd-networkd-tests.py]: Thanks. Now `assertIn()` is used in this test. I will convert remaining `assertRegex()` in other tests in another PR.

**Comment by yuwata** [comment]
@keszybz and @zhangyoufu I force-pushed new version.
- The comment in the code is updated.
- `assertRegex()` -> `assertIn()`

PTAL.

**Comment by keszybz** [comment]
LGTM. I don't understand all the address manipulation bits in detail, but looks OK.
