### PR TITLE
test: exclude "bdi" subsystem

### LINKED ISSUE #22970: Spurious fails in `test-sd-device/sd_device_new_from_syspath()`
**systemd version the issue has been seen with**
 > latest main

**Used distribution**
 > Arch Linux/CentOS Stream 8

In a couple of recent jobs I noticed a fail in `test-sd-device`:

```
382/984 test-sd-device                                                     FAIL              1.43s   killed by signal 6 SIGABRT
>>> MALLOC_PERTURB_=43 SYSTEMD_LANGUAGE_FALLBACK_MAP=/build/src/locale/language-fallback-map PATH=/systemd-meson-build:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl /systemd-meson-build/test-sd-device
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
Listing only the last 100 lines from a long log.
syspath:/sys/devices/software subsystem:event_source id:+event_source:software initialized:yes
syspath:/sys/devices/system/clockevents/broadcast subsystem:clockevents id:+clockevents:broadcast initialized:yes
syspath:/sys/devices/system/clockevents/clockevent0 subsystem:clockevents id:+clockevents:clockevent0 initialized:yes
syspath:/sys/devices/system/clockevents/clockevent1 subsystem:clockevents id:+clockevents:clockevent1 initialized:yes
syspath:/sys/devices/system/clockevents/clockevent2 subsystem:clockevents id:+clockevents:clockevent2 initialized:yes
syspath:/sys/devices/system/clockevents/clockevent3 subsystem:clockevents id:+clockevents:clockevent3 initialized:yes
syspath:/sys/devices/system/clockevents/clockevent4 subsystem:clockevents id:+clockevents:clockevent4 initialized:yes
syspath:/sys/devices/system/clockevents/clockevent5 subsystem:clockevents id:+clockevents:clockevent5 initialized:yes
syspath:/sys/devices/system/clockevents/clockevent6 subsystem:clockevents id:+clockevents:clockevent6 initialized:yes
syspath:/sys/devices/system/clockevents/clockevent7 subsystem:clockevents id:+clockevents:clockevent7 initialized:yes
syspath:/sys/devices/system/clocksource/clocksource0 subsystem:clocksource id:+clocksource:clocksource0 initialized:yes
syspath:/sys/devices/system/container/PNP0A06:00 subsystem:container id:+container:PNP0A06:00 initialized:yes
syspath:/sys/devices/system/container/PNP0A06:01 subsystem:container id:+container:PNP0A06:01 initialized:yes
syspath:/sys/devices/system/container/PNP0A06:02 subsystem:container id:+container:PNP0A06:02 initialized:yes
syspath:/sys/devices/system/cpu/cpu0 subsystem:cpu id:+cpu:cpu0 initialized:yes
syspath:/sys/devices/system/cpu/cpu1 subsystem:cpu id:+cpu:cpu1 initialized:yes
syspath:/sys/devices/system/cpu/cpu2 subsystem:cpu id:+cpu:cpu2 initialized:yes
syspath:/sys/devices/system/cpu/cpu3 subsystem:cpu id:+cpu:cpu3 initialized:yes
syspath:/sys/devices/system/cpu/cpu4 subsystem:cpu id:+cpu:cpu4 initialized:yes
syspath:/sys/devices/system/cpu/cpu5 subsystem:cpu id:+cpu:cpu5 initialized:yes
syspath:/sys/devices/system/cpu/cpu6 subsystem:cpu id:+cpu:cpu6 initialized:yes
syspath:/sys/devices/system/cpu/cpu7 subsystem:cpu id:+cpu:cpu7 initialized:yes
syspath:/sys/devices/system/edac/mc subsystem:edac id:+edac:mc initialized:yes
syspath:/sys/devices/system/machinecheck/machinecheck0 subsystem:machinecheck id:+machinecheck:machinecheck0 initialized:yes
syspath:/sys/devices/system/machinecheck/machinecheck1 subsystem:machinecheck id:+machinecheck:machinecheck1 initialized:yes
syspath:/sys/devices/system/machinecheck/machinecheck2 subsystem:machinecheck id:+machinecheck:machinecheck2 initialized:yes
syspath:/sys/devices/system/machinecheck/machinecheck3 subsystem:machinecheck id:+machinecheck:machinecheck3 initialized:yes
syspath:/sys/devices/system/machinecheck/machinecheck4 subsystem:machinecheck id:+machinecheck:machinecheck4 initialized:yes
syspath:/sys/devices/system/machinecheck/machinecheck5 subsystem:machinecheck id:+machinecheck:machinecheck5 initialized:yes
syspath:/sys/devices/system/machinecheck/machinecheck6 subsystem:machinecheck id:+machinecheck:machinecheck6 initialized:yes
syspath:/sys/devices/system/machinecheck/machinecheck7 subsystem:machinecheck id:+machinecheck:machinecheck7 initialized:no
syspath:/sys/devices/system/memory/memory0 subsystem:memory id:+memory:memory0 initialized:no
syspath:/sys/devices/system/memory/memory1 subsystem:memory id:+memory:memory1 initialized:no
syspath:/sys/devices/system/memory/memory10 subsystem:memory id:+memory:memory10 initialized:no
syspath:/sys/devices/system/memory/memory11 subsystem:memory id:+memory:memory11 initialized:no
syspath:/sys/devices/system/memory/memory12 subsystem:memory id:+memory:memory12 initialized:no
syspath:/sys/devices/system/memory/memory13 subsystem:memory id:+memory:memory13 initialized:yes
syspath:/sys/devices/system/memory/memory14 subsystem:memory id:+memory:memory14 initialized:yes
syspath:/sys/devices/system/memory/memory15 subsystem:memory id:+memory:memory15 initialized:yes
syspath:/sys/devices/system/memory/memory16 subsystem:memory id:+memory:memory16 initialized:yes
syspath:/sys/devices/system/memory/memory17 subsystem:memory id:+memory:memory17 initialized:no
syspath:/sys/devices/system/memory/memory18 subsystem:memory id:+memory:memory18 initialized:no
syspath:/sys/devices/system/memory/memory19 subsystem:memory id:+memory:memory19 initialized:no
syspath:/sys/devices/system/memory/memory2 subsystem:memory id:+memory:memory2 initialized:yes
syspath:/sys/devices/system/memory/memory20 subsystem:memory id:+memory:memory20 initialized:yes
syspath:/sys/devices/system/memory/memory21 subsystem:memory id:+memory:memory21 initialized:yes
syspath:/sys/devices/system/memory/memory22 subsystem:memory id:+memory:memory22 initialized:yes
syspath:/sys/devices/system/memory/memory23 subsystem:memory id:+memory:memory23 initialized:yes
syspath:/sys/devices/system/memory/memory3 subsystem:memory id:+memory:memory3 initialized:yes
syspath:/sys/devices/system/memory/memory32 subsystem:memory id:+memory:memory32 initialized:yes
syspath:/sys/devices/system/memory/memory33 subsystem:memory id:+memory:memory33 initialized:yes
syspath:/sys/devices/system/memory/memory34 subsystem:memory id:+memory:memory34 initialized:yes
syspath:/sys/devices/system/memory/memory35 subsystem:memory id:+memory:memory35 initialized:yes
syspath:/sys/devices/system/memory/memory36 subsystem:memory id:+memory:memory36 initialized:yes
syspath:/sys/devices/system/memory/memory37 subsystem:memory id:+memory:memory37 initialized:yes
syspath:/sys/devices/system/memory/memory38 subsystem:memory id:+memory:memory38 initialized:no
syspath:/sys/devices/system/memory/memory39 subsystem:memory id:+memory:memory39 initialized:no
syspath:/sys/devices/system/memory/memory4 subsystem:memory id:+memory:memory4 initialized:no
syspath:/sys/devices/system/memory/memory40 subsystem:memory id:+memory:memory40 initialized:no
syspath:/sys/devices/system/memory/memory41 subsystem:memory id:+memory:memory41 initialized:no
syspath:/sys/devices/system/memory/memory42 subsystem:memory id:+memory:memory42 initialized:no
syspath:/sys/devices/system/memory/memory43 subsystem:memory id:+memory:memory43 initialized:no
syspath:/sys/devices/system/memory/memory44 subsystem:memory id:+memory:memory44 initialized:no
syspath:/sys/devices/system/memory/memory45 subsystem:memory id:+memory:memory45 initialized:no
syspath:/sys/devices/system/memory/memory46 subsystem:memory id:+memory:memory46 initialized:no
syspath:/sys/devices/system/memory/memory47 subsystem:memory id:+memory:memory47 initialized:no
syspath:/sys/devices/system/memory/memory48 subsystem:memory id:+memory:memory48 initialized:no
syspath:/sys/devices/system/memory/memory49 subsystem:memory id:+memory:memory49 initialized:no
syspath:/sys/devices/system/memory/memory5 subsystem:memory id:+memory:memory5 initialized:yes
syspath:/sys/devices/system/memory/memory50 subsystem:memory id:+memory:memory50 initialized:no
syspath:/sys/devices/system/memory/memory51 subsystem:memory id:+memory:memory51 initialized:no
syspath:/sys/devices/system/memory/memory52 subsystem:memory id:+memory:memory52 initialized:no
syspath:/sys/devices/system/memory/memory53 subsystem:memory id:+memory:memory53 initialized:no
syspath:/sys/devices/system/memory/memory54 subsystem:memory id:+memory:memory54 initialized:no
syspath:/sys/devices/system/memory/memory55 subsystem:memory id:+memory:memory55 initialized:yes
syspath:/sys/devices/system/memory/memory56 subsystem:memory id:+memory:memory56 initialized:no
syspath:/sys/devices/system/memory/memory57 subsystem:memory id:+memory:memory57 initialized:no
syspath:/sys/devices/system/memory/memory58 subsystem:memory id:+memory:memory58 initialized:no
syspath:/sys/devices/system/memory/memory59 subsystem:memory id:+memory:memory59 initialized:no
syspath:/sys/devices/system/memory/memory6 subsystem:memory id:+memory:memory6 initialized:no
syspath:/sys/devices/system/memory/memory60 subsystem:memory id:+memory:memory60 initialized:no
syspath:/sys/devices/system/memory/memory61 subsystem:memory id:+memory:memory61 initialized:no
syspath:/sys/devices/system/memory/memory62 subsystem:memory id:+memory:memory62 initialized:no
syspath:/sys/devices/system/memory/memory63 subsystem:memory id:+memory:memory63 initialized:no
syspath:/sys/devices/system/memory/memory64 subsystem:memory id:+memory:memory64 initialized:no
syspath:/sys/devices/system/memory/memory65 subsystem:memory id:+memory:memory65 initialized:no
syspath:/sys/devices/system/memory/memory66 subsystem:memory id:+memory:memory66 initialized:no
syspath:/sys/devices/system/memory/memory67 subsystem:memory id:+memory:memory67 initialized:no
syspath:/sys/devices/system/memory/memory68 subsystem:memory id:+memory:memory68 initialized:no
syspath:/sys/devices/system/memory/memory69 subsystem:memory id:+memory:memory69 initialized:no
syspath:/sys/devices/system/memory/memory7 subsystem:memory id:+memory:memory7 initialized:no
syspath:/sys/devices/system/memory/memory70 subsystem:memory id:+memory:memory70 initialized:no
syspath:/sys/devices/system/memory/memory71 subsystem:memory id:+memory:memory71 initialized:no
syspath:/sys/devices/system/memory/memory8 subsystem:memory id:+memory:memory8 initialized:no
syspath:/sys/devices/system/memory/memory9 subsystem:memory id:+memory:memory9 initialized:no
syspath:/sys/devices/system/node/node0 subsystem:node id:+node:node0 initialized:no
syspath:/sys/devices/tracepoint subsystem:event_source id:+event_source:tracepoint initialized:yes
syspath:/sys/devices/uprobe subsystem:event_source id:+event_source:uprobe initialized:no
syspath:/sys/devices/virtual/bdi/0:49 subsystem:bdi id:+bdi:0:49 initialized:no
Assertion 'sd_device_new_from_syspath(&dev, syspath) >= 0' failed at src/libsystemd/sd-device/test-sd-device.c:28, function test_sd_device_one(). Aborting.
```

 * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-cron-build/570/artifact//systemd-centos-ci/artifacts_all/artifacts_io3852y3/vagrant-logs.06X/vagrant-arch-sanitizers-gcc-testsuite.zA9/ninja-test_sanitizers_FAIL.log
 * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/7270/artifact//systemd-centos-ci/artifacts_mhiz4out/testsuite-logs-upstream.X63/ninja-test_FAIL.log
 * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/7262/artifact//systemd-centos-ci/artifacts__7nn0peb/testsuite-logs-upstream.yiF/ninja-test_FAIL.log
 * ...

### PR DESCRIPTION
**Pull request by yuwata**
On several CI environments, it seems that bdi devices sometimes removed
during the test is running. Let's exclude them.

Fixes #22970.

### CODE REVIEW

**Review by mrc0mmand — APPROVED** [review]
Thanks, LGTM!

File: src/libsystemd/sd-device/test-sd-device.c [hunk 1]
```diff
@@ -182,6 +182,7 @@ TEST(sd_device_enumerator_devices) {
 
         assert_se(sd_device_enumerator_new(&e) >= 0);
         assert_se(sd_device_enumerator_allow_uninitialized(e) >= 0);
+        assert_se(sd_device_enumerator_add_match_subsystem(e, "bdi", false) >= 0);
```
Comment (poettering) [inline src/libsystemd/sd-device/test-sd-device.c:187]: maybe add a comment here, explaining this magic line?

**Comment by poettering** [comment]
now if i only knew what "bdi" devices actually are? anyone grokked the info available via google? i only understand that they are about "backing devices", but not sure what that is specifically supposed to mean...

File: src/libsystemd/sd-device/test-sd-device.c (hunk 1 above)
Comment (yuwata) [reply src/libsystemd/sd-device/test-sd-device.c:187]: Added.

**Comment by yuwata** [comment]
Nah, still failed...

**Comment by yuwata** [comment]
@mrc0mmand and @poettering PTAL.

**Comment by mrc0mmand** [comment]
TEST-58-REPART failed in focal-ppc64el, but it seems unrelated:

```
[  122.722379] kernel: loop_set_block_size: loop3 () has still dirty pages (nrpages=1)
[  123.228153] kernel: audit: type=1130 audit(1650863887.568:21): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=testsuite-58 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? r>
[  123.021442] audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=testsuite-58 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
[  123.076004] testsuite-58.sh[291]: + cat
[  123.076004] testsuite-58.sh[291]: + cat
[  123.076004] testsuite-58.sh[291]: + cat
[  123.076004] testsuite-58.sh[291]: + truncate -s 100m /tmp/testsuite-58-sector-4096.img
[  123.107079] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/sys_2ddevices_2dvirtual_2dblock_2dloop3_2edevice interface=org.freedesktop.DBus.Properties me>
[  123.109773] testsuite-58.sh[415]: ++ losetup -b 4096 -P --show -f /tmp/testsuite-58-sector-4096.img
[  123.109773] testsuite-58.sh[415]: losetup: /tmp/testsuite-58-sector-4096.img: failed to set up loop device: Resource temporarily unavailable
[  123.124482] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=612 reply_cookie=0 signature=>
[  123.125008] testsuite-58.sh[291]: + LOOP=
```

TEST-70-TPM2 failed on focal-amd64 due to timeout, which also looks unrelated:
```
[   62.453968] kernel: tpm tpm0: Operation Timed out
```

so LGTM, at least from the test point of view, thanks!

File: src/basic/hashmap.c [hunk 2]
```diff
@@ -2070,3 +2071,27 @@ bool set_equal(Set *a, Set *b) {
...
+        assert(s);
+
+        SET_FOREACH(p, patterns)
+                if (fnmatch(p, s, 0) == 0)
+                        return true;
+
+        return false;
+}
+
+bool set_fnmatch2(Set *match_patterns, Set *nomatch_patterns, const char *s) {
```
Comment (keszybz) [inline src/basic/hashmap.c]: ~~I'm not crazy about the name, but I don't have any great suggestions.~~

Maybe call the parameters "include" and "exclude"? "nomatch" doesn't convey that this is an exclude list.
Also a comment explaining the match-on-empty semantics would be nice.

```
bool set_fnmatch(const char *needle, const Set *include_patterns, const Set *exclude_patterns) {
      if (exclude_patterns && set_fnmatch(needle, exclude_patterns, NULL))
            return false;

      const char *p;
      SET_FOREACH(p, include_patterns)
                 if (fnmatch(p, needle, 0) == 0)
                        return true;
      return set_isempty(include_patterns);
}
```
?

I think it'd be useful to have the `needle` param first. I expect we'll want to add fnmatch flags sooner or later, and then it'd nicer to have the patterns and flags as later arguments.

File: src/libsystemd/sd-device/device-enumerator.c [hunk 3]
```diff
@@ -198,6 +200,10 @@ _public_ int sd_device_enumerator_add_match_sysname(sd_device_enumerator *enumer
         return 1;
 }
 
+_public_ int sd_device_enumerator_add_match_sysname(sd_device_enumerator *enumerator, const char *sysname) {
+        return device_enumerator_add_match_sysname(enumerator, sysname, true);
+}
```
Comment (keszybz) [inline src/libsystemd/sd-device/device-enumerator.c:205]: I think it'd make sense to also export the new functionality. If *we* need it, it seems likely that other users of sd-device will also need it.

**Review by keszybz — COMMENTED** [review]
Looks good in general.

File: src/basic/hashmap.c (hunk 2 above)
Comment (yuwata) [reply src/basic/hashmap.c]: Arguments are renamed, but their order are not changed, as I'd like to make the order similar to the `fnmatch()` or our `strv_fnmatch()`.

Also, renamed the function `set_fnmatch2()` -> `set_fnmatch()` as suggested. And made the original `set_fnmatch()` static and renamed to `set_fnmatch_one()`. I kept the original two function implementation, as it is simpler to read, I think.

**Comment by yuwata** [comment]
@keszybz Thank you for the comments. Now `sd_device_enumerator_add_nomatch_sysname()` is exported. PTAL.

**Comment by keszybz** [comment]
LGTM. I think we should merge this to get the CI functional.

> @keszybz Thank you for the comments. Now `sd_device_enumerator_add_nomatch_sysname()` is exported. PTAL.

Looking at the last commit, we have `sd_device_enumerator_add_match_sysname` and `sd_device_enumerator_add_nomatch_sysname`, but `sd_device_enumerator_add_match_subsystem` and `sd_device_enumerator_add_match_sysattr` take a `match` boolean. Shouldn't we instead add `sd_device_enumerator_add_match_sysname2` which also accepts the `match` boolean?

**Comment by keszybz** [comment]
rpm-build in copr failed with `!! Copr timeout => sending INT`.
