### PR TITLE
analyze: resolve executable path if it is relative

### LINKED ISSUE #18252: systemd-analyze  verify failed
**systemd version the issue has been seen with**
 >  systemd-247.2

**Used distribution**
 > A customised embedded linux based on yocto 

**Linux kernel version used** (`uname -a`)
 > 5.4.87

**CPU architecture issue was seen on**
 > …

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 >  \# systemd-analyze --man=false verify /lib/systemd/system/initrd-cleanup.service
initrd-cleanup.service: Command systemctl is not executable: No such file or directory
  \# cat /lib/systemd/system/initrd-cleanup.service
 \#  SPDX-License-Identifier: LGPL-2.1-or-later
 \#
 \#  This file is part of systemd.
 \#
 \#  systemd is free software; you can redistribute it and/or modify it
 \#  under the terms of the GNU Lesser General Public License as published by
 \#  the Free Software Foundation; either version 2.1 of the License, or
 \#  (at your option) any later version.

[Unit]
Description=Cleaning Up and Shutting Down Daemons
DefaultDependencies=no
AssertPathExists=/etc/initrd-release
OnFailure=emergency.target
OnFailureJobMode=replace-irreversibly
After=initrd-root-fs.target initrd-fs.target initrd.target

[Service]
Type=oneshot
ExecStart=systemctl --no-block isolate initrd-switch-root.target

**Steps to reproduce the problem**
 > …

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #18252.

### CODE REVIEW

**Review by bluca — APPROVED** [review]
lgtm - if it works in the unit, it should work in systemd-analyze too

File: src/analyze/analyze-verify.c [hunk 1]
```diff
@@ -115,13 +115,20 @@ static int verify_socket(Unit *u) {
...
 
         if (exec->flags & EXEC_COMMAND_IGNORE_FAILURE)
                 return 0;
 
-        if (access(exec->path, X_OK) < 0)
+        r = find_executable_full(exec->path, false, &exec_path, NULL);
+        if (r < 0)
+                return log_unit_error_errno(u, r, "Command %s not found: %m", exec->path);
+
+        if (access(exec_path, X_OK) < 0)
```
Comment (poettering) [inline src/analyze/analyze-verify.c]: this is done implicitly by find_executable_full() anyway, no need to do that again

**Review by poettering — CHANGES_REQUESTED** [review]

**Comment by yuwata** [comment]
Updated. Addressed @poettering's comment. Also fixes `find_executable()` when path is absolute to a directory.

**Comment by keszybz** [comment]
LGTM.

File: src/basic/path-util.c [hunk 2]
```diff
@@ -599,14 +600,24 @@ static int check_x_access(const char *path, int *ret_fd) {
...
                         return r;
-
-                *ret_fd = TAKE_FD(fd);
         } else {
                 /* Let's optimize things a bit by not opening the file if we don't need the fd. */
                 if (access(path, X_OK) < 0)
                         return -errno;
         }
 
+        with_dash = strjoina(path, "/");
```
Comment (poettering) [inline src/basic/path-util.c:609]: hmm, this appends the dash even if the provided path already had one, in which case it basically does the same access() check twice

File: src/basic/path-util.c [hunk 3]
```diff
@@ -599,14 +600,24 @@ static int check_x_access(const char *path, int *ret_fd) {
...
+
+        /* If this passes, it must be a directory. */
+        if (access(with_dash, X_OK) >= 0)
+                return -EISDIR;
```
Comment (poettering) [inline src/basic/path-util.c:613]: hmm, if we have the fd open anyway I think a better check would be using the fd, i.e. do fstat() here

File: src/basic/path-util.c [hunk 4]
```diff
@@ -599,14 +600,24 @@ static int check_x_access(const char *path, int *ret_fd) {
...
+
+        if (errno != ENOTDIR)
+                return -errno;
+
+        if (ret_fd)
+                *ret_fd = TAKE_FD(fd);
+
```
Comment (poettering) [inline src/basic/path-util.c:620]: hmm, so this now does two access() calls for the case where the fd is not requested, and opens things up for races (theoretically, …). now, the access() code path was in place for optimization, but if an optimization is less sexy than the original (and i think it is less sexy, since more than one syscall, and non-atomic), i think we shouldn't do the optimization.

maybe we should just always use open(O_PATH) now, and then fstat() it to check if regular file, and then access_fd() it for checking if its executable.

```c
fd = open(path, O_CLOEXEC|O_PATH);
if (fd < 0)
        return -errno;

r = fd_verify_regular(fd);
if (r < 0)
        return r;

r = access_fd(fd, X_OK);
if (r < 0)
       return r;

if (ret_fd)
        *ret_fd = TAKE_FD(fd);
```

This would then mean 3 syscalls for cases where the caller wants the fd, and 4 where they don't. which is ok, i guess.

**Comment by yuwata** [comment]
@poettering Thank you for the comments. I will create a follow-up PR.
