### PR TITLE
core/cgroup: fix TasksMaxScale percentage serialization

### LINKED ISSUE #41009: bus_cgroup_set_tasks_max_scale: TasksMax percentage serialized 5-10x too low due to units mismatch
### systemd version the issue has been seen with

259

### Used distribution

N/A (bug is in upstream source, confirmed on custom build from v259)

### Linux kernel version used

6.9.0

### CPU architectures issue was seen on

x86_64

### Component

_No response_

### Expected behaviour you didn't see

`systemctl set-property --runtime user.slice TasksMax=40%` should persist `TasksMax=40.00%` in the runtime drop-in file, and `daemon-reload` should re-read the same 40% value.

### Unexpected behaviour you saw

The drop-in file is written as <code>TasksMax=4.0%</code> instead of <code>TasksMax=40.00%</code> — 5-10x too low (exactly 10x for inputs ≥ 5%). On the next <code>daemon-reload</code>, <code>daemon-reexec</code>, or reboot, the effective TasksMax limit drops without any warning in the journal.</p>
<p>The bug is in <code>bus_cgroup_set_tasks_max_scale()</code> (<code>src/core/dbus-cgroup.c</code>, ~line 1011). The function computes <code>scaled = DIV_ROUND_UP(v * 100, UINT32_MAX)</code>, producing a <strong>whole-percent</strong> value (e.g., 40 for 40%). But the format string <code>scaled/10 . scaled%10 %%</code> treats <code>scaled</code> as <strong>tenths of percent</strong>, outputting <code>4.0%</code> instead of <code>40.0%</code>.</p>
<p>The adjacent memory property handlers (<code>MemoryMax</code>, <code>MemoryHigh</code>, <code>MemoryLow</code>) use <code>UINT32_SCALE_TO_PERMYRIAD</code> + <code>PERMYRIAD_AS_PERCENT_FORMAT_STR</code> and produce correct output. Both paths are in the same file, writing to the same drop-in directory:</p>
<pre><code>$ cat /run/systemd/system.control/user.slice.d/50-MemoryLowScale.conf
[Slice]
MemoryLow=15.00%    ← CORRECT (uses PERMYRIAD macros)

$ cat /run/systemd/system.control/user.slice.d/50-TasksMaxScale.conf
[Slice]
TasksMax=4.0%       ← WRONG (hand-rolled formula)
</code></pre>
<p><strong>Buggy code</strong> (<code>src/core/dbus-cgroup.c</code>, ~line 1011):</p>
<pre><code class="language-c">uint32_t scaled = DIV_ROUND_UP((uint64_t) v * 100U, (uint64_t) UINT32_MAX);
unit_write_settingf(u, flags, name, "%s=%" PRIu32 ".%" PRIu32 "%%", "TasksMax",
                    scaled / 10, scaled % 10);
</code></pre>
<p><strong>Correct code</strong> (other scaled property handlers, ~line 904, via <code>BUS_DEFINE_SET_CGROUP_LIMIT</code>):</p>
<pre><code class="language-c">int scaled = UINT32_SCALE_TO_PERMYRIAD(raw);
unit_write_settingf(u, flags, name, "%.*s=" PERMYRIAD_AS_PERCENT_FORMAT_STR,
                    (int)(strlen(name) - strlen("Scale")), name,
                    PERMYRIAD_AS_PERCENT_FORMAT_VAL(scaled));
</code></pre>
<p><strong>Error table:</strong></p>

Intended | Written (buggy) | Read back as | Effective reduction
-- | -- | -- | --
1% | 0.2% | 0.20% | 5x
5% | 0.5% | 0.50% | 10x
10% | 1.0% | 1.00% | 10x
40% | 4.0% | 4.00% | 10x
100% | 10.0% | 10.00% | 10x

<p>This bug affects runtime property changes via <code>systemctl set-property</code> (and <code>systemd-run</code>), not static unit file configurations — those go through <code>config_parse_tasks_max()</code> which uses a different (correct) code path.</p>
<p><strong>Impact</strong>: The effective TasksMax is silently reduced by ~10x after daemon-reload. On systems where the actual thread count exceeds the reduced limit, this causes fork rejections across all processes in the affected slice  (<code>cgroup: fork rejected by pids controller in /user.slice/.../scope</code>). The in-memory value is correct immediately after <code>set-property</code>, masking the file error until the next <code>daemon-reload</code>.</p>
<p><strong>Suggested fix</strong>: Replace the hand-rolled formula with the existing <code>PERMYRIAD</code> macros, consistent with the other scaled property handlers:</p>
<pre><code class="language-c">int scaled = UINT32_SCALE_TO_PERMYRIAD(v);
assert_se(endswith(name, "Scale"));
unit_write_settingf(u, flags, name, "%.*s=" PERMYRIAD_AS_PERCENT_FORMAT_STR,
                    (int)(strlen(name) - strlen("Scale")), name,
                    PERMYRIAD_AS_PERCENT_FORMAT_VAL(scaled));
</code></pre>
<p><strong>Workaround</strong>: Use absolute values instead of percentages:</p>
<pre><code class="language-bash">THREADS_MAX=$(cat /proc/sys/kernel/threads-max)
sudo systemctl set-property --runtime user.slice "TasksMax=$((THREADS_MAX * 40 / 100))"
</code></pre>

### Steps to reproduce the problem

```bash
# Set TasksMax to 40%
sudo systemctl set-property --runtime user.slice TasksMax=40%

# In-memory value is correct
systemctl show user.slice -p TasksMax
# TasksMax=352909  (40% of threads-max on this machine)

# Drop-in file is wrong
cat /run/systemd/system.control/user.slice.d/50-TasksMaxScale.conf
# TasksMax=4.0%   (should be 40.00%)

# Compare with memory property (correct)
cat /run/systemd/system.control/user.slice.d/50-MemoryLowScale.conf
# MemoryLow=15.00%   (correct — uses PERMYRIAD macros)

# After daemon-reload, limit drops to 4%
sudo systemctl daemon-reload
systemctl show user.slice -p TasksMax
# TasksMax=35290   (4% of threads-max — 10x reduction)
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# Before daemon-reload (correct in-memory value):
$ systemctl show user.slice -p TasksMax
TasksMax=352909

# The buggy drop-in file:
$ cat /run/systemd/system.control/user.slice.d/50-TasksMaxScale.conf
[Slice]
TasksMax=4.0%

# After daemon-reload (wrong — 10x reduction):
$ systemctl show user.slice -p TasksMax
TasksMax=35290

# The correct memory property drop-in for comparison:
$ cat /run/systemd/system.control/user.slice.d/50-MemoryLowScale.conf
[Slice]
MemoryLow=15.00%
```

### PR DESCRIPTION
**Pull request by Cyrus-Xi**
`bus_cgroup_set_tasks_max_scale()` uses a hand-rolled percentage format that produces values ~10x too
small (e.g., `TasksMax=4.0%` instead of `TasksMax=40.00%`).

The function computes whole-percent values (`scaled = v * 100 / UINT32_MAX`) but the format string
treats them as tenths-of-percent (`scaled/10 . scaled%10`). On daemon-reload, the incorrect value is
re-read, silently reducing the effective TasksMax by ~5-10x.

Fix by replacing with `UINT32_SCALE_TO_PERMYRIAD()` + `PERMYRIAD_AS_PERCENT_FORMAT_STR`, matching
`BUS_DEFINE_SET_CGROUP_LIMIT`.

Fixes #41009

(Note: This PR was developed with AI assistance (Claude Code).)

### CODE REVIEW

**Comment by daandemeyer** [comment]
@claude review

**Review by daandemeyer — APPROVED** [review]

**Comment by daandemeyer** [comment]
@Cyrus-Xi please add a test to  `test/units/TEST-19-CGROUP.sh`

**Comment by ikruglov** [comment]
@Cyrus-Xi please squash all commits into one.

**Comment by Cyrus-Xi** [comment]
added test and squashed commits into 1

edit: made executable to fix failing CI

File: src/core/dbus-cgroup.c [hunk 1]
```diff
@@ -1010,9 +1010,13 @@ static int bus_cgroup_set_tasks_max_scale(
                 *p = (CGroupTasksMax) { v, UINT32_MAX }; /* .scale is not 0, so this is interpreted as v/UINT32_MAX. */
                 unit_invalidate_cgroup(u, CGROUP_MASK_PIDS);
 
-                uint32_t scaled = DIV_ROUND_UP((uint64_t) v * 100U, (uint64_t) UINT32_MAX);
-                unit_write_settingf(u, flags, name, "%s=%" PRIu32 ".%" PRIu32 "%%", "TasksMax",
-                                    scaled / 10, scaled % 10);
+                /* Prepare to chop off suffix */
+                assert_se(endswith(name, "Scale"));
```
Comment (yuwata) [inline src/core/dbus-cgroup.c]: Please drop this. It is not necessary. Please directly use `"TasksMax"` in unit_write_settingf() below:
```c
unit_write_settingf(u, flags, name, "TasksMax=" PERMYRIAD_AS_PERCENT_FORMAT_STR,
                    PERMYRIAD_AS_PERCENT_FORMAT_VAL(scaled));
```

File: test/units/TEST-19-CGROUP.tasks-max-scale.sh [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+testcase_tasks_max_scale_serialize() {
+    # Regression test for https://github.com/systemd/systemd/issues/41009
+    # TasksMaxScale was serialized as 4.0% instead of 40.00%, causing 10x reduction on daemon-reload
+
+    local unit="test-tasks-max.slice"
+    local unit_file="/run/systemd/system/${unit}"
+    local dropin_dir="/run/systemd/system.control/${unit}.d"
+
+    # shellcheck disable=SC2329
+    cleanup() {
```
Comment (yuwata) [inline test/units/TEST-19-CGROUP.tasks-max-scale.sh]: Please use `()` rather than `{}` the use `set +e`:
```sh
cleanup() (
    set +e
    rm -rf ...
    rm -f ...
    systemctl daemon-reload
)
```
then drop `2>/dev/null || true`. This is test code, it is not necessary to make it silent.

File: test/units/TEST-19-CGROUP.tasks-max-scale.sh [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+    # Capture value before daemon-reload
+    local tasks_max_before
+    tasks_max_before=$(systemctl show -P TasksMax "${unit}")
+
+    # Reload and verify value is preserved (the actual bug: value dropped 10x here)
+    systemctl daemon-reload
+
+    local tasks_max_after
+    tasks_max_after=$(systemctl show -P TasksMax "${unit}")
+    [[ "${tasks_max_before}" == "${tasks_max_after}" ]] || {
```
Comment (yuwata) [inline test/units/TEST-19-CGROUP.tasks-max-scale.sh]: Please use `assert_eq "${tasks_max_before}" "${tasks_max_after}"`.

File: test/units/TEST-19-CGROUP.tasks-max-scale.sh [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+# SPDX-License-Identifier: LGPL-2.1-or-later
+set -ex
+set -o pipefail
+
+# shellcheck source=test/units/test-control.sh
+. "$(dirname "$0")"/test-control.sh
+# shellcheck source=test/units/util.sh
+. "$(dirname "$0")"/util.sh
+
+if [[ "$(get_cgroup_hierarchy)" != unified ]]; then
```
Comment (yuwata) [inline test/units/TEST-19-CGROUP.tasks-max-scale.sh]: Now we only support unified one. Please drop the check.

File: src/core/dbus-cgroup.c (hunk 1 above)
Comment (Cyrus-Xi) [reply src/core/dbus-cgroup.c]: fixed for all, thanks for the review

**Comment by yuwata** [comment]
Hmm, the commit message has spurious indent. Let's fix it on merge (by using squash merge).
