### PR TITLE
core: don't hit an assert when printing status messages about units with overly long descriptions

### LINKED ISSUE #4534: systemd crashes when systemd-run generates very large error message
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

debian testing

### In case of bug report: Unexpected behaviour you saw

When receiving a particularly large error message, systemd[1] crashes in xsprintf, leaving the system in a state that even rebooting cleanly is impossible.

### In case of bug report: Steps to reproduce the problem

call systemd-run with a command that will generate a particularly large error message, in my particulary case saltstack calls systemd-run with apt-get to install packages, one of those packages doesn't exist and apt returns an error message longer than MAX_LINE.

### Journal
This is the message in journald.

```txt
Nov 01 15:37:37 computer systemd[1]: Assertion 'xsprintf: buf[] must be big enough' failed at ../src/core/job.c:771, function job_log_status_message(). Aborting.
Nov 01 15:37:37 computer systemd[1]: Caught <ABRT>, dumped core as pid 3316.
Nov 01 15:37:37 computer systemd[1]: Freezing execution.
Nov 01 15:37:37 computer salt-minion[619]: [ERROR   ] Command '['systemd-run', '--scope', 'apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'insta [truncated]
Nov 01 15:37:37 computer salt-minion[619]: :i386', 'sudo', 'openjdk-8-jre', 'libwayland-egl1-mesa', 'libgcrypt20:i386', 'libxcb-dri2-0-dev:i386', 'libxcb-dri3-dev', 'libegl1-mesa', 'libxcb-glx0-dev', ' [truncated]
```

### PR DESCRIPTION
**Pull request by poettering**
Fixes #4534

### CODE REVIEW

File: src/core/job.c [hunk 1]
```diff
@@ -767,8 +767,9 @@ static void job_log_status_message(Unit *u, JobType t, JobResult result) {
         if (!format)
                 return;
 
+        /* The description might be longer than the buffer, but that's OK, we'll just truncate it here */
         DISABLE_WARNING_FORMAT_NONLITERAL;
-        xsprintf(buf, format, unit_description(u));
+        snprintf(buf, sizeof(buf), format, unit_description(u));
```
Comment (evverx) [inline src/core/job.c:772]: This fixes #4534, of course.
But what about other places?

This PR is the second quick fix. 79c954405fd77e36c5

Comment (evverx) [reply src/core/job.c:772]:
```
-bash-4.3# systemd-run --service-type=notify --description="$(printf "a%10000s" "a")" sleep 10000
Warning! D-Bus connection terminated.
Broadcast message from systemd-journald@systemd-testsuite (Wed 2016-11-02 10:33:52 UTC):

systemd[1]: Caught <ABRT>, dumped core as pid 188.


Failed to wait for response: Connection reset by peer

Broadcast message from systemd-journald@systemd-testsuite (Wed 2016-11-02 10:33:52 UTC):

systemd[1]: Freezing execution.

-bash-4.3# journalctl | grep Assert
systemd-testsuite systemd[1]: Assertion 'xsprintf: buf[] must be big enough' failed at src/core/unit.c:1453, function unit_status_log_starting_stopping_reloading(). Aborting.
```

File: src/core/job.c [hunk 2]
```diff
@@ -690,16 +690,16 @@ _pure_ static const char *job_get_status_message_format(Unit *u, JobType t, JobR
 }
 
 static void job_print_status_message(Unit *u, JobType t, JobResult result) {
-        static struct {
+        static const struct {
                 const char *color, *word;
         } const statuses[_JOB_RESULT_MAX] = {
```
Comment (keszybz) [inline src/core/job.c:695]: I think this second `const` is redundant...

Comment (poettering) [reply src/core/job.c:695]: oh! i missed that, so the patch was actually redundant as a whole... 

But then again I think it's easier to see this if the const is specified next to the "static", so that the next one doesn't make the same mistake as I just did...
