### PR TITLE
fstab-generator: ignore sysfs entry in container

### LINKED ISSUE #21744: Writable /sys in containers can brick networkd
* systemd version the issue has been seen with: 249
* Used distribution: openSUSE Tumbleweed
* Linux kernel version used: 5.15.6
* CPU architecture issue was seen on: x86_64

Reproducer:

1. Prepare some small-scale container image of choice. Should contain systemd and should have systemd-networkd enabled for boot.
2. Add the line `sysfs /sys sysfs noauto 0 0` into the container's `/etc/fstab`.
3. Launch container, e.g. `systemd-nspawn -b -n`
4. The effect of the fstab line is that /sys is writable.
5. **Observed behavior**: networkd now believes that udevd is in charge of the host0 network interface; the interface never leaves the "pending" status:

```
01:27 testcont:/ # networkctl 
IDX LINK  TYPE     OPERATIONAL SETUP  
  1 lo    loopback carrier     pending
  2 host0 ether    off         pending

2 links listed.
```

**Expected behavior:** configure the interface.

Background:

There used to be a time when Linux systems might have a line for /sys in /etc/fstab, because some distro-specific boot scripts during the sysvinit time used fstab even for essential filesystems. I had such a system; and it was migrated through the times. When systemd came onto the scene, the rogue /sys entry in fstab did no harm. /sys was still sysfs.

Later, the host was converted to an nspawn container, i.e. retaining the /sys entry in fstab, without noticable ill effect. (I found that such fstab entry would cause /sys to be readwritable.) The last version of systemd inside the container that showed expected behavior was v234. That nspawn container was upgraded to the next distro release, featuring v246, where networkd was found to stop working when with that /sys entry. Reproduction of this behavior was then attempted with a newer systemd for the bugreport.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #21744.

### CODE REVIEW

**Comment by poettering** [comment]
No. Dont. /sys/ being writable is the way to indicate that udev is used ifnependently of containers or not. See container interface docs.

**Comment by jengelh** [comment]
Having only 3d67535 (do not remount /sys in containers) should be sufficient, right? No need for 145fc43.

**Comment by yuwata** [comment]
> No. Dont. /sys/ being writable is the way to indicate that udev is used ifnependently of containers or not. See container interface docs.

@poettering Right. So, this intends to ignore sysfs entry in fstab. Or, do I misunderstand your point?

File: src/fstab-generator/fstab-generator.c [hunk 1]
```diff
@@ -112,7 +111,7 @@ static int add_swap(
                 return 0;
         }
 
-        if (detect_container() > 0) {
+        if (path_is_read_only_fs("/sys") > 0) {
```
Comment (keszybz) [inline src/fstab-generator/fstab-generator.c]: Please describe the motivation of such changes in the commit message…

Is this for speed? I think it'd be more reasonable to do `if (path_is_read_only_fs("/sys") > 0 || detect_container() > 0) …`. As the change is done now, effectively fstab-generator could execute where it didn't before, in case of containers that are set up with /sys writeable. It might be an error in the set up, or just a different way to do things, and I don't think we want to open ourselves to regressions here.

**Comment by keszybz** [comment]
I think the change is reasonable: belt-and-suspenders approach to software engineering ;)

File: src/fstab-generator/fstab-generator.c (hunk 1 above)
Comment (yuwata) [reply src/fstab-generator/fstab-generator.c]: We replaced `detect_container()` -> `path_is_read_only_fs("/sys")` in networkd. So, I thought that we should always use `path_is_read_only_fs("/sys")` everywhere. But after reconsidering about that, maybe we should use it only when checking udevd is running or not. In this case, swap is not related to udevd. So, I will drop the change.

**Comment by yuwata** [comment]
The change in`add_swap()` is dropped. PTAL.

**Comment by keszybz** [comment]
Thanks, this looks very straightforward now.
