### PR TITLE
chase: add explicit root_fd parameter to chaseat() and drop CHASE_AT_RESOLVE_IN_ROOT

### LINKED ISSUE #41630: Enumerating devices with libudev requires read permission on "/" (can't use Landlock)
### systemd version the issue has been seen with

260.1

### Used distribution

Arch Linux

### Linux kernel version used

6.19.10-hardened1-1-hardened

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

I have a program that uses **libudev** to enumerate usb devices. This program is also using **Landlock** to restrict itself, it can only read files under **"/sys/{bus,class,devices}"**.

Since systemd v260, this program fails with a permission denied error.

relevant syscalls trace with systemd v259:
```
openat(AT_FDCWD, "/sys/bus", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
getdents64(3, 0x67b54eba20 /* 53 entries */, 32768) = 1496
openat(AT_FDCWD, "/sys/bus/usb/devices/", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 4
fstat(4, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
getdents64(4, 0x67b54f3a60 /* 54 entries */, 32768) = 1624
openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECTORY) = 5

```

same with systemd v260:
```
openat(AT_FDCWD, "/sys/bus", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
getdents64(3, 0xad9292b31c0 /* 53 entries */, 32768) = 1496
openat(AT_FDCWD, "/sys/bus/usb/devices/", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 4
fstat(4, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
getdents64(4, 0xad9292bb200 /* 54 entries */, 32768) = 1624
openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = -1 EACCES (Permission denied)
```

The **O_PATH** flag is missing in the **openat "/"** system call in systemd v260.

This is annoying because the solution would be to give read permission on "/" but kinda defeat the purpose of using Landlock.

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

Here is a basic rust program to reproduce the issue:

**src/main.rs**:
```rust
use landlock::{
    path_beneath_rules, Access, AccessFs, CompatLevel, Compatible, Ruleset, RulesetAttr,
    RulesetCreatedAttr,
};
use udev::Enumerator;

fn main() -> Result<(), Box<dyn std::error::Error>> {

    let ruleset = Ruleset::default().set_compatibility(CompatLevel::BestEffort);
    let mut ruleset = ruleset
        .handle_access(AccessFs::from_all(landlock::ABI::V2))?
        .create()?;
    ruleset = ruleset.add_rules(path_beneath_rules(
        ["/sys/bus", "/sys/class", "/sys/devices"],
        AccessFs::from_read(landlock::ABI::V2),
    ))?;
    let _ = ruleset.restrict_self()?;

    let mut enumerator = Enumerator::new()?;
    enumerator.match_subsystem("usb")?;
    for dev in enumerator.scan_devices()? {
        println!("{dev:?}");
    }

    Ok(())
}
```

Cargo.toml:
```toml
[package]
name = "dbg-systemd"
version = "0.1.0"
edition = "2024"

[dependencies]
udev = "0.9"
landlock = "0.4"
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by daandemeyer**
Split the single directory fd that chaseat() used to take into two separate
fds: a root_fd that sets the chroot boundary (symlinks may not escape it,
absolute symlinks resolve relative to it), and a dir_fd that path resolution
starts from. This makes the chroot semantics of chaseat() explicit at every
call site instead of encoding them in the CHASE_AT_RESOLVE_IN_ROOT flag,
which is removed. It also decouples the starting directory from the root
boundary, so callers can descend from any inode inside the tree without
having to reopen the root separately.

XAT_FDROOT passed as root_fd means "no containment" (host root); as dir_fd
it means "start at root_fd". For a smoother transition, AT_FDCWD is also
accepted as root_fd and treated as XAT_FDROOT. When root_fd points to a
directory that is actually the host root, it is normalized to XAT_FDROOT
up front so the existing shortcut path can kick in.

Absolute paths returned by chaseat() are now relative to root_fd, and
relative paths are relative to dir_fd. The result is absolute only when
there is no chroot boundary (root_fd is XAT_FDROOT), or when an absolute
symlink made resolution jump out of the dir_fd subtree; otherwise callers
get a relative path they can feed straight back into an openat()-style
call against dir_fd. Specifically, when dir_fd == root_fd and we're not
operating on the host's root directory, we return a relative path even if
we received an absolute path or resolved an absolute symlink to allow
passing the path directly to openat() style functions. We do this to not
have to go modify every caller of chaseat() to make sure they deal properly
with any absolute paths they might receive. Only when root_fd != dir_fd do
we have to return an absolute path to indicate that the path is relative to
root_fd and not dir_fd.

The shortcut that skips the per-component walk is reworked around a new
chase_xopenat() helper that funnels CHASE_NOFOLLOW, CHASE_MUST_BE_* and
CHASE_TRIGGER_AUTOFS through xopenat_full()'s O_NOFOLLOW, O_DIRECTORY,
XO_REGULAR, XO_SOCKET and XO_TRIGGER_AUTOMOUNT flags. As a result these
flags no longer force us off the shortcut and can be dropped from
CHASE_NO_SHORTCUT_MASK, and the old openat_opath_with_automount() helper
goes away. A CHASE_MUST_BE_ANY alias is introduced for shortcut callers
(stat/access paths) that don't go through xopenat_full() and still need
to bail on those flags locally.

All *_and_* helpers built on top of chaseat() (chase_and_openat,
chase_and_opendirat, chase_and_statat, chase_and_accessat,
chase_and_fopenat_unlocked, chase_and_unlinkat, chase_and_open_parent_at)
gain the same root_fd parameter, and every call site in the tree is
ported to the new signature.

### CODE REVIEW

File: src/basic/chase.c [hunk 1]
```diff
@@ -239,90 +208,93 @@ int chaseat(int dir_fd, const char *path, ChaseFlags flags, char **ret_path, int
...
+                r = dir_fd_is_root(root_fd);
+                if (r < 0)
+                        return r;
+                if (r > 0)
+                        root_fd = XAT_FDROOT;
+        }
+
+        /* If dir_fd points to the host's root directory and there is no chroot boundary, normalize it
+         * to XAT_FDROOT so the shortcut path can kick in. */
         r = dir_fd_is_root(dir_fd);
```
[the remark this answers is not in the document]
Comment (daandemeyer) [reply src/basic/chase.c:236]: I wouldn't say it's uncommon at all, let's keep it

File: src/basic/fs-util.c [hunk 2]
```diff
@@ -1217,9 +1278,11 @@ int xopenat_full(int dir_fd, const char *path, int open_flags, XOpenFlags xopen_
                  * first */
 
                 if (FLAGS_SET(open_flags, O_PATH)) {
-                        fd = openat(dir_fd, path, open_flags, mode);
+                        fd = FLAGS_SET(xopen_flags, XO_TRIGGER_AUTOMOUNT) ?
+                                openat_with_automount(dir_fd, path, open_flags, mode) :
+                                RET_NERRNO(openat(dir_fd, path, open_flags, mode));
```
Comment (brauner) [inline src/basic/fs-util.c:1283]: Please don't use `?:` for two function calls. Make it a proper `if ()`.

File: src/basic/chase.h [hunk 3]
```diff
@@ -15,21 +15,19 @@ typedef enum ChaseFlags {
                                              * right-most component refers to symlink, return O_PATH fd of the symlink. */
         CHASE_WARN               = 1 << 8,  /* Emit an appropriate warning when an error is encountered.
                                              * Note: this may do an NSS lookup, hence this flag cannot be used in PID 1. */
-        CHASE_AT_RESOLVE_IN_ROOT = 1 << 9,  /* Same as openat2()'s RESOLVE_IN_ROOT flag, symlinks are resolved
-                                             * relative to the given directory fd instead of root. */
```
Comment (brauner) [inline src/basic/chase.h:19]: I think the chase() machinery should be taught about `openat2()` and if it's available (non-`ENOSYS` because not available on the kernel or because seccomp filter blocks it) it should be used. That doesn't have to be done in this change but should be a follow-up change.

I didn't realize until know that we're not using `openat2()` at all which is really really sad. I think doing this all in userspace will never be on a par with what `openat2()` does in the kernel. I kinda sense that we should put a moratorium on any new `openat2()` features until one of the main consumers here moves forward with this.

**Review by brauner — APPROVED** [review]
I didn't go over the coding style - I trust the bots to fix this. It looks reasonable to me. I do dislike that we effectively embeddd a bad version of `openat2()` in here - seccomp or not.

The other thing is that returning a path here and then commenting that a resolved path may be directly passed to `openat()` with a dir_fd if relative is just straightup dangerous imho. `dir_fd` might have been moved around `N` times while you're performing your lookup. IOW, by the time the path is returned `dir_fd` may have been moved outside of `root_fd` already. So path can really really really only be a cosmetic thing. If you want to use it with `dir_fd` you must go through a variant of chase() again.

Maybe that is the long-term invariant to go after as well: It's forbidden to use plain glibc wrappers to reopen or open fds/paths/inoderefs.

**Comment by daandemeyer** [comment]
> Maybe that is the long-term invariant to go after as well: It's forbidden to use plain glibc wrappers to reopen or open fds/paths/inoderefs.

This is what I'm going for with InodeRef

File: src/basic/fs-util.c [hunk 4]
```diff
@@ -1130,15 +1131,65 @@ int openat_report_new(int dirfd, const char *pathname, int flags, mode_t mode, b
         }
 }
 
+static int openat_with_automount(int dir_fd, const char *path, int open_flags, mode_t mode) {
```
Comment (poettering) [inline src/basic/fs-util.c:1134]: hmm, this only works with O_PATH? this is neither directly mentioned in a comment, nor is there an assert_se() check that verifies `open_flags` has O_PATH set.

it's simply wrong to use open_tree() for anyting else than O_PATH acquisition after all

File: src/basic/fs-util.c [hunk 5]
```diff
@@ -1130,15 +1131,65 @@ int openat_report_new(int dirfd, const char *pathname, int flags, mode_t mode, b
...
+         * mount namespace anyway. */
+
+        static bool can_open_tree = true;
+        int r;
+
+        assert(dir_fd >= 0 || dir_fd == AT_FDCWD);
+        assert(path);
+
+        if (can_open_tree) {
+                r = RET_NERRNO(open_tree(dir_fd, path,
```
Comment (poettering) [inline src/basic/fs-util.c:1148]: I'd always store the result of syscalls that track resources in a real variable, not in `r`... it's weird that `r` is now more than just an exit status...

File: src/basic/fs-util.c [hunk 6]
```diff
@@ -1130,15 +1131,65 @@ int openat_report_new(int dirfd, const char *pathname, int flags, mode_t mode, b
...
         bool made_dir = false, made_file = false;
         int r;
 
         assert(dir_fd >= 0 || IN_SET(dir_fd, AT_FDCWD, XAT_FDROOT));
 
-        /* An inode cannot be both a directory and a regular file at the same time. */
+        /* An inode can only be one of a directory, a regular file or a socket at the same time. */
         assert(!(FLAGS_SET(open_flags, O_DIRECTORY) && FLAGS_SET(xopen_flags, XO_REGULAR)));
+        assert(!(FLAGS_SET(xopen_flags, XO_REGULAR) && FLAGS_SET(xopen_flags, XO_SOCKET)));
+        assert(!(FLAGS_SET(open_flags, O_DIRECTORY) && FLAGS_SET(xopen_flags, XO_SOCKET)));
```
Comment (poettering) [inline src/basic/fs-util.c:1183]: i'd have checked this as:

```c
asser(FLAGS_SET(open_flags, O_DIRECTORY) + FLAGS_SET(xopen_flags, XO_REGULAR) + FLAGS_SET(xopen_flags, XO_SOCKET) <= 1);
```

File: src/basic/fs-util.c [hunk 7]
```diff
@@ -1266,14 +1329,28 @@ int xopenat_full(int dir_fd, const char *path, int open_flags, XOpenFlags xopen_
                                 }
                         }
                 }
+        } else if (FLAGS_SET(xopen_flags, XO_TRIGGER_AUTOMOUNT)) {
+                fd = openat_with_automount(dir_fd, path, open_flags, mode);
```
Comment (poettering) [inline src/basic/fs-util.c:1333]: this seems wrong? this is an O_PATH codepath, but you call openat_with_automount() here, which seems to be O_PATH only

File: src/test/test-fs-util.c [hunk 8]
```diff
@@ -740,6 +741,65 @@ TEST(xopenat_regular) {
...
+
+        /* We can't easily set up an autofs mount in a test, but we can verify that
+         * XO_TRIGGER_AUTOMOUNT works on a regular path and produces the same inode as a
+         * plain O_PATH open. */
+        fd = xopenat_full(AT_FDCWD, "/usr", O_PATH|O_CLOEXEC|O_DIRECTORY, XO_TRIGGER_AUTOMOUNT, 0);
+        ASSERT_OK(fd);
+
+        _cleanup_close_ int fd2 = xopenat_full(AT_FDCWD, "/usr", O_PATH|O_CLOEXEC|O_DIRECTORY, 0, 0);
+        ASSERT_OK(fd2);
+        ASSERT_OK_POSITIVE(fd_inode_same(fd, fd2));
```
Comment (poettering) [inline src/test/test-fs-util.c:800]: this should really test what happens if XO_TRIGGER_AUTOMOUNT is combined with non-O_PATH

File: src/basic/chase.c [hunk 9]
```diff
@@ -239,127 +219,116 @@ int chaseat(int dir_fd, const char *path, ChaseFlags flags, char **ret_path, int
          *    the mount point is emitted. CHASE_WARN cannot be used in PID 1.
          */
 
-        _cleanup_close_ int _dir_fd = -EBADF;
+        /* We treat AT_FDCWD as XAT_FDROOT for a more seamless migration for all callers of chaseat() before
+         * it was reworked to support separate root_fd and dir_fd arguments. */
+        if (root_fd == AT_FDCWD)
+                root_fd = XAT_FDROOT;
```
Comment (poettering) [inline src/basic/chase.c:225]: we should really fix that across the tree

**Comment by poettering** [comment]
hmm, next time, please split up such complex commits more. i.e. the xopenat() wrapper than the chase code uses could have been a separate commit. It's extremely hard to follow the complexity of the 3rd patch this way...

File: src/basic/fs-util.c (hunk 7 above)
Comment (brauner) [reply src/basic/fs-util.c:1333]: I think you meant "non-O_PATH codepath"?. The idea is that `XO_TRIGGER_AUTOMOUNT` implies `O_PATH`.

Comment (daandemeyer) [reply src/basic/fs-util.c:1333]: It doesn't even imply it, we assert `O_PATH` is set when `XO_TRIGGER_AUTOMOUNT` is set at the top so this is safe?

File: src/test/test-fs-util.c (hunk 8 above)
Comment (daandemeyer) [reply src/test/test-fs-util.c:800]: It will crash as we assert in xopenat_full() that XO_TRIGGER_AUTOMOUNT is used with O_PATH
