### PR TITLE
Prefer logging to console unless JOURNAL_STREAM is set

### LINKED ISSUE #15902: CLI tools do not log to the console when executed as a child process
**systemd version the issue has been seen with**
> v245

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > systemd-tmpfiles logs to the console when executed as a child process

**Unexpected behaviour you saw**
 > systemd-tmpfiles logs to the journal when executed as a child process

**Steps to reproduce the problem**

Run systemd-tmpfiles as a child process (e.g. via Python's `subprocess.run`)

I spent (wasted?) a lot of time debugging a pacman hook failure that was failing with not logging output because systemd-tmpfiles decides to log directly to the journal if the stderr fd is not a tty. systemd-tmpfiles calls `log_setup_service` which sets the log target to `AUTO`. Subsequently, when `log_open` is called, the `isatty` check fails and systemd-tmpfiles prefers all the other logging options above logging to the console. 

I think this behaviour is perfectly acceptable for actual services but for stuff that is also meant to be run as a CLI tool, maybe we should prefer logging to the console even if it isn't a tty to avoid weird behaviour when running these command line tools as child processes of another process for example a package manager such as pacman.

### PR DESCRIPTION
**Pull request by daandemeyer**
Fixes #15902.

I tried adding a `log_setup_cli` function first in a similar vein to `log_setup_service` but there seem to be quite some discrepancies between all the tools (some set LC_ALL to "", some enable colors, etc). I'm not sure if we could align all those tools to use the exact same setup so I left that out for now.

### CODE REVIEW

File: src/binfmt/binfmt.c [hunk 1]
```diff
@@ -191,7 +191,8 @@ static int run(int argc, char *argv[]) {
         if (r <= 0)
                 return r < 0 ? EXIT_FAILURE : EXIT_SUCCESS;
 
-        log_setup_service();
+        log_parse_environment();
+        log_open();
```
Comment (keszybz) [inline src/binfmt/binfmt.c]: That's fairly ugly... What about going in the other direction: making log_setup_service have a parameter like log_to_console and putting `true` or `false` in the callers?

**Comment by DaanDeMeyer** [comment]
There might be more offenders. I took the tools used in Arch pacman systemd hook and systemd-firstboot as those are the tools I've been impacted by the problem.

**Comment by keszybz** [comment]
> but there seem to be quite some discrepancies between all the tools (some set LC_ALL to "", some enable colors, etc). 

The history here is that adding color output in logging requires some work when there was manual coloring added to messages. It is necessary to remove/adjust/verify that this coloring does not interact badly with the log coloring. That is why it's not turned on everywhere.

File: src/basic/log.c [hunk 2]
```diff
@@ -1396,12 +1396,12 @@ int log_dup_console(void) {
...
 }
 
-void log_setup_service(void) {
+void log_setup_service(bool log_to_console) {
         /* Sets up logging the way it is most appropriate for running a program as a service. Note that using this
          * doesn't make the binary unsuitable for invocation on the command line, as log output will still go to the
          * terminal if invoked interactively. */
 
-        log_set_target(LOG_TARGET_AUTO);
+        log_set_target(log_to_console ? LOG_TARGET_CONSOLE : LOG_TARGET_AUTO);
```
Comment (keszybz) [inline src/basic/log.c]: Hmm, maybe we should combine this with an explicit setting in the units where the binaries that set log_to_console=true are used? We still want to log to the journal from systemd-tmpfiles.service, systemd-sysusers.service, etc.

Comment (daandemeyer) [reply src/basic/log.c]: Is there a big difference between logging directly to the journal and having output pass via the console? It ends up in the journal regardless no?

EDIT: nvm, syslog log level isn't possible via the console. I'll add the necessary environment variable to the unit files.

Comment (daandemeyer) [reply src/basic/log.c]: Setting the SYSTEMD_LOG_TARGET environment variable in the relevant units works but is a little bit ugly. Maybe there's a way to detect whether we're running as a service and switch between console and journal based on that?

Comment (keszybz) [reply src/basic/log.c]: Yes, there's a difference: when going via the console, all metadata is stripped (or rather, it is never attached in the first place). I agree that setting of a variable is ugly. Indeed, maybe it'd be better to look at $JOURNAL_STREAM? @poettering, opinions?

**Comment by poettering** [comment]
i like @keszybz' idea with the JOURNAL_STREAM stuff. i.e. automatically upgrade to structured journal logging if stdout/stderr is actually connected to a journal stream anyway. It's precisely what $JOURNAL_STREAM was invented for. And this could easily be hidden inside log_setup_service() so that it magically works for all services

**Comment by DaanDeMeyer** [comment]
We now prefer console unless `JOURNAL_STREAM` is set. This works but does make console preferred over kmsg by default. I'm not sure what the best way is to deal with that. Maybe its fine to prefer console over kmsg unless kmsg is explicitly configured?

File: src/basic/log.c [hunk 3]
```diff
@@ -1131,6 +1131,10 @@ void log_parse_environment_realm(LogRealm realm) {
                  * closed the console yet. */
                 (void) proc_cmdline_parse(parse_proc_cmdline_item, NULL, PROC_CMDLINE_STRIP_RD_PREFIX);
 
+        e = getenv("JOURNAL_STREAM");
```
Comment (poettering) [inline src/basic/log.c]: so we set the env var to the st_dev and st_ino fields of the fd stderr is connected to. The idea is that this allows us to protect us from cases where we are forked off some service that itself had stderr connected to the journal but connects our stderr to a pipe it allocated itself, but didn#t clean up $JOURNAL_STREAM.

We should thus compare the contents with the data from fstat(STDERR_FILENO). i.e. add a new helper call or so:

```c
bool stderr_is_journal(void) {
        _cleanup_free_ char *w = NULL;
        const char *e;
        uint64_t dev, ino;

        e = getenv("JOURNAL_STREAM");
        if (!e)
                return false;

        if (extract_first_word(&e, &w, ":",  EXTRACT_DONT_COALESCE_SEPARATORS) <= 0)
                return false;

         if (safe_atou64(w, &dev) < 0)
                return false;
         if (safe_atou64(e, &ino) < 0)
                return false;        

        if (fstat(STDERR_FILENO, &st) < 0)
                return false;

        return st.st_dev == dev & st.st_ino == ino;
}
```

Comment (poettering) [reply src/basic/log.c]: i wonder if we should do this unconditionally in log_open() if LOG_TARGET_AUTO is chosen — entirely replacing the isatty() check

Comment (daandemeyer) [reply src/basic/log.c]: I replaced the `isatty` check by the `stderr_is_journal` check. I think that's a net improvement over the `isatty` check.

Also, is `extract_many_words` supposed to succeed if it can't read the requested amount of words? That gave me a pretty nasty segfault.

File: src/basic/log.c [hunk 4]
```diff
@@ -219,6 +220,30 @@ static int log_open_journal(void) {
...
+        _cleanup_free_ char *f = NULL, *s = NULL;
+        const char *e;
+        uint64_t dev, ino;
+        struct stat st;
+
+        e = getenv("JOURNAL_STREAM");
+        if (!e)
+                return false;
+
+        if (extract_many_words(&e, ":", EXTRACT_DONT_COALESCE_SEPARATORS, &f, &s, NULL) < 2)
```
Comment (poettering) [inline src/basic/log.c]: hmm, to fully validate the input string you'd have to check `isempty(e)` after calling extract_many_words() to check that there's no trailing rubbish (think: a string line `47:11:8:15` is passed...)

I'd probably just use extract_first_word() to extract the first word, and then parse that to an integer and parse whatever remains as another integer (as my original code snippet suggested)

**Comment by poettering** [comment]
I like this a lot I must say. This is a lot nicer than the old isatty() check.

**Comment by poettering** [comment]
CI is unhappy?

**Comment by mrc0mmand** [comment]
For some reason this breaks `TEST-21-SYSUSERS` in all CIs:

[CentOS CI - Arch](https://ci.centos.org/job/systemd-pr-build-vagrant/8026/artifact//systemd-centos-ci/artifacts_RQwWbQ/vagrant-logs.0WR/vagrant-arch-testsuite.YdZ/TEST-21-SYSUSERS_FAIL.log)
```
*** Running test unhappy-1.input
--- /var/tmp/systemd-test-TEST-21-SYSUSERS/tmp/err	2020-06-10 18:58:25.007480639 +0000
+++ unhappy-1.expected-err	2020-06-10 18:34:44.460643387 +0000
@@ -1 +1 @@
-Creating group tape with gid 968.
+Failed to parse UID: '9999999999': Numerical result out of range
**** Unexpected error output for unhappy-1.input
Creating group tape with gid 968.
make: *** [Makefile:4: run] Error 1
make: Leaving directory '/build/test/TEST-21-SYSUSERS'
```

[CentOS CI - CentOS 7](https://ci.centos.org/job/systemd-pr-build/12426/artifact//systemd-centos-ci/artifacts_XK4_t6/testsuite-logs-upstream.Ug4/TEST-21-SYSUSERS_FAIL.log)
```
*** Running test unhappy-1.input
--- /var/tmp/systemd-test-TEST-21-SYSUSERS/tmp/err	2020-06-10 19:38:21.061806943 +0100
+++ unhappy-1.expected-err	2020-06-10 19:25:33.560142414 +0100
@@ -1 +1 @@
-Creating user systemd-coredump (systemd Core Dumper) with uid 988 and gid 988.
+Failed to parse UID: '9999999999': Numerical result out of range
**** Unexpected error output for unhappy-1.input
Creating user systemd-coredump (systemd Core Dumper) with uid 988 and gid 988.
make: *** [run] Error 1
make: Leaving directory `/root/systemd/test/TEST-21-SYSUSERS'
```

Ubuntu CI - amd64
```
*** Running test unhappy-1.input
--- /var/tmp/systemd-test.6yW0xs/tmp/err	2020-06-11 04:03:06.964521988 +0000
+++ unhappy-1.expected-err	2020-06-11 02:18:14.000000000 +0000
@@ -0,0 +1 @@
+Failed to parse UID: '9999999999': Numerical result out of range
**** Unexpected error output for unhappy-1.input
make: *** [run] Error 1
Makefile:4: recipe for target 'run' failed
make: Leaving directory '/tmp/autopkgtest.c4GiLG/build.icl/systemd/test/TEST-21-SYSUSERS'
```

etc.

**Comment by DaanDeMeyer** [comment]
Fixed, the tests relied on the output being logged to journald instead of the console. That gives us a good indication that the change is working. I fixed the tests to read the output from the console instead and they seem to be passing now.
