### PR TITLE
make "machinectl clean" asynchronous, and open it up via PolicyKit

### LINKED ISSUE #3585: RFE: `machinectl clean` is missing polkit support
### Submission type
- Request for enhancement (RFE)
### systemd version the issue has been seen with

> 230 eee0a1e4
### Used distribution

> Gentoo (Kernel 4.5.0)
### In case of bug report: Expected behaviour you didn't see

> Executing `machinectl clean` as non-root user should ask for elevated privileges through polkit, but doesn't
### In case of bug report: Unexpected behaviour you saw

> Executing `machinectl clean` as non-root user simply returns `Could not clean pool: Access denied`
### In case of bug report: Steps to reproduce the problem

> Execute `machinectl clean` as non-root user
## TODO

Add polkit support to `machinectl clean` to be consistent with other `machinectl` commands such as `clone`, `start`, `remove`, etc.

### PR DESCRIPTION
**Pull request by poettering**
Fixes #3585.

### CODE REVIEW

File: src/basic/fileio.c [hunk 1]
```diff
@@ -1354,3 +1354,44 @@ int link_tmpfile(int fd, const char *path, const char *target) {
...
+
+        assert(f);
+        assert(ret);
+
+        /* Reads a NUL-terminated string from the specified file. */
+
+        for (;;) {
+                int c;
+
+                if (!GREEDY_REALLOC(x, allocated, n+2))
```
Comment (martinpitt) [inline src/basic/fileio.c]: This is a function call for every single byte that gets read. The whole function looks a bit cumbersome: Wouldn't it be easier to stop on NUL when writing the file, by just writing `strlen(buffer)` bytes? Then reading it could just slurp in entire blocks until EOF, i. e. this could re-use `read_full_file()`.

Comment (martinpitt) [inline src/basic/fileio.c]: Nevermind, sorry. There is further data after the 0 bytes in the file.

**Comment by martinpitt** [comment]
I previously had a (bogus) comment/question about `read_nul_str()`, but this got clarified after I went through the whole patch. Looks sensible by the looks of it.
