### PR TITLE
timesync: fix parsing FallbackNTP=

### LINKED ISSUE #40621: timesyncd: falls back to "compiled in" NTP Servers even when `FallbackNTP=` is empty [Manpage Update?]
### systemd version the issue has been seen with

241

### Used distribution

Debian

### Linux kernel version used

4.19.0-16

### CPU architectures issue was seen on

x86_64

### Component

systemd-timesync

### Expected behaviour you didn't see

When config `FallbackNTP=` is empty, do not contact NTP Servers

### Unexpected behaviour you saw

Per https://github.com/systemd/systemd/blob/e4dcf0cbce7f3fc76e14ae946df8ae5c08a6c401/man/timesyncd.conf.xml#L72 

> When the empty string is assigned, the list of NTP servers is reset, and all prior assignments will have no effect. 

But this is not the case, it falls back to compiled in NTP Servers.

**You could update the manpage to make that clear.**

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ timedatectl show-timesync
FallbackNTPServers=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org
ServerName=0.debian.pool.ntp.org
ServerAddress=139.144.71.56
[...]
$ systemd-analyze cat-config systemd/timesyncd.conf
# /etc/systemd/timesyncd.conf
[...]#
# See timesyncd.conf(5) for details.

[Time]
#NTP=
#FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org 192.168.3.253
#RootDistanceMaxSec=5
#PollIntervalMinSec=32
#PollIntervalMaxSec=2048

# /etc/systemd/timesyncd.conf.d/disable.conf

[Time]
NTP=
FallbackNTP=
```

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for 3745770ae4dcf262707882a38f6c5ba2684329a3.
Fixes #40621.

### CODE REVIEW

File: src/timesync/timesyncd-conf.c [hunk 1]
```diff
@@ -84,15 +84,21 @@ int config_parse_servers(
...
-                r = manager_parse_server_string(m, ltype, rvalue);
-                if (r < 0) {
-                        log_syntax(unit, LOG_WARNING, filename, line, r,
-                                   "Failed to parse NTP server string '%s', ignoring: %m", rvalue);
-                        return 0;
-                }
+
+                /* FallbackNTP= with an empty string disables the built-in fallback servers. */
+                if (ltype == SERVER_FALLBACK)
+                        m->have_fallbacks = true;
```
Comment (YHNdnzj) [inline src/timesync/timesyncd-conf.c]: maybe rename the field to "fallback_set" or "_parsed"? have_fallbacks is kinda ambiguous and I was confused for a moment
