### PR TITLE
resolve: fix use after free in DnsAnswer

### LINKED ISSUE #18132: Potential heap-use-after-free in systemd-resolved
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > Arch Linux

I noticed that several of the recent CentOS CI runs reported ABRTs in `systemd-resolved`. One of them happened in the sanitizer run, which yielded a possibly helpful trace:

```
systemd-resolved[112830]: ==112830==ERROR: AddressSanitizer: heap-use-after-free on address 0x6040000248f8 at pc 0x564d06c61a51 bp 0x7ffe3b0ec4b0 sp 0x7ffe3b0ec4a8
systemd-resolved[112830]:                             gVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+
systemd-resolved[112830]: READ of size 4 at 0x6040000248f8 thread T0
systemd-resolved[112830]:                             sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXx
systemd-resolved[112830]:                             uOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555
systemd-resolved[112830]:                             KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU=
systemd-resolved[112830]:         -- Flags: SEP ZONE_KEY
systemd-resolved[112830]:         -- Key tag: 20326: validated
systemd-resolved[112830]:     #0 0x564d06c61a50 in dns_answer_item_compare_func /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:26:13
systemd-resolved[112830]:     #1 0x7ff165e42af3 in base_bucket_scan /systemd-meson-build/../build/src/basic/hashmap.c:1209:29
systemd-resolved[112830]:     #2 0x7ff165e43f83 in _hashmap_get /systemd-meson-build/../build/src/basic/hashmap.c:1341:15
systemd-resolved[112830]:     #3 0x564d06c54ad8 in set_get /systemd-meson-build/../build/src/basic/set.h:38:16
systemd-resolved[112830]:     #4 0x564d06c5445a in dns_answer_add /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:143:17
systemd-resolved[112830]:     #5 0x564d06c5eb3f in dns_answer_copy_by_key /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:602:21
systemd-resolved[112830]:     #6 0x564d06c5f547 in dns_answer_move_by_key /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:617:13
systemd-resolved[112830]:     #7 0x564d06b8a318 in dnssec_validate_records /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:2847:29
systemd-resolved[112830]:     #8 0x564d06b84e28 in dns_transaction_validate_dnssec /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:3098:21
systemd-resolved[112830]:     #9 0x564d06b7e234 in dns_transaction_process_dnssec /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:793:13
systemd-resolved[112830]:     #10 0x564d06b75e10 in dns_transaction_process_reply /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:1159:9
systemd-resolved[112830]:     #11 0x564d06b8f39c in dns_transaction_on_stream_packet /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:495:9
systemd-resolved[112830]:     #12 0x564d06b8edca in on_stream_packet /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:545:24
systemd-resolved[112830]:     #13 0x564d06b5a663 in on_stream_io /systemd-meson-build/../build/src/resolve/resolved-dns-stream.c:419:45
systemd-resolved[112830]:     #14 0x7ff1660bb257 in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3498:21
systemd-resolved[112830]:     #15 0x7ff1660ba230 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3950:21
systemd-resolved[112830]:     #16 0x7ff1660bce7c in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:4011:21
systemd-resolved[112830]:     #17 0x7ff1660bd94e in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:4032:21
systemd-resolved[112830]:     #18 0x564d06bfd6e2 in run /systemd-meson-build/../build/src/resolve/resolved.c:92:13
systemd-resolved[112830]:     #19 0x564d06bfd06a in main /systemd-meson-build/../build/src/resolve/resolved.c:99:1
systemd-resolved[112830]:     #20 0x7ff165099151 in __libc_start_main (/usr/lib/libc.so.6+0x28151)
systemd-resolved[112830]:     #21 0x564d06af5c1d in _start (/systemd-meson-build/systemd-resolved+0x12cc1d)
systemd-resolved[112830]: 0x6040000248f8 is located 40 bytes inside of 48-byte region [0x6040000248d0,0x604000024900)
systemd-resolved[112830]: freed by thread T0 here:
systemd-resolved[112830]:     #0 0x7ff16672b392 in realloc (/usr/lib/clang/11.0.0/lib/linux/libclang_rt.asan-x86_64.so+0xf2392)
systemd-resolved[112830]:     #1 0x564d06c60766 in dns_answer_reserve /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:683:21
systemd-resolved[112830]:     #2 0x564d06c5522c in dns_answer_reserve_or_clone /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:710:13
systemd-resolved[112830]:     #3 0x564d06c5eb05 in dns_answer_copy_by_key /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:598:21
systemd-resolved[112830]:     #4 0x564d06c5f547 in dns_answer_move_by_key /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:617:13
systemd-resolved[112830]:     #5 0x564d06b8a318 in dnssec_validate_records /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:2847:29
systemd-resolved[112830]:     #6 0x564d06b84e28 in dns_transaction_validate_dnssec /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:3098:21
systemd-resolved[112830]:     #7 0x564d06b7e234 in dns_transaction_process_dnssec /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:793:13
systemd-resolved[112830]:     #8 0x564d06b75e10 in dns_transaction_process_reply /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:1159:9
systemd-resolved[112830]:     #9 0x564d06b8f39c in dns_transaction_on_stream_packet /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:495:9
systemd-resolved[112830]:     #10 0x564d06b8edca in on_stream_packet /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:545:24
systemd-resolved[112830]:     #11 0x564d06b5a663 in on_stream_io /systemd-meson-build/../build/src/resolve/resolved-dns-stream.c:419:45
systemd-resolved[112830]:     #12 0x7ff1660bb257 in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3498:21
systemd-resolved[112830]:     #13 0x7ff1660ba230 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3950:21
systemd-resolved[112830]:     #14 0x7ff1660bce7c in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:4011:21
systemd-resolved[112830]:     #15 0x7ff1660bd94e in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:4032:21
systemd-resolved[112830]:     #16 0x564d06bfd6e2 in run /systemd-meson-build/../build/src/resolve/resolved.c:92:13
systemd-resolved[112830]:     #17 0x564d06bfd06a in main /systemd-meson-build/../build/src/resolve/resolved.c:99:1
systemd-resolved[112830]:     #18 0x7ff165099151 in __libc_start_main (/usr/lib/libc.so.6+0x28151)
systemd-resolved[112830]: previously allocated by thread T0 here:
systemd-resolved[112830]:     #0 0x7ff16672b1c1 in calloc (/usr/lib/clang/11.0.0/lib/linux/libclang_rt.asan-x86_64.so+0xf21c1)
systemd-resolved[112830]:     #1 0x564d06c53c8a in dns_answer_new /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:51:13
systemd-resolved[112830]:     #2 0x564d06c60653 in dns_answer_reserve /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:689:21
systemd-resolved[112830]:     #3 0x564d06c5522c in dns_answer_reserve_or_clone /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:710:13
systemd-resolved[112830]:     #4 0x564d06c5eb05 in dns_answer_copy_by_key /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:598:21
systemd-resolved[112830]:     #5 0x564d06c5f547 in dns_answer_move_by_key /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:617:13
systemd-resolved[112830]:     #6 0x564d06b8a318 in dnssec_validate_records /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:2847:29
systemd-resolved[112830]:     #7 0x564d06b84e28 in dns_transaction_validate_dnssec /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:3098:21
systemd-resolved[112830]:     #8 0x564d06b7e234 in dns_transaction_process_dnssec /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:793:13
systemd-resolved[112830]:     #9 0x564d06b75e10 in dns_transaction_process_reply /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:1159:9
systemd-resolved[112830]:     #10 0x564d06b8f39c in dns_transaction_on_stream_packet /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:495:9
systemd-resolved[112830]:     #11 0x564d06b8edca in on_stream_packet /systemd-meson-build/../build/src/resolve/resolved-dns-transaction.c:545:24
systemd-resolved[112830]:     #12 0x564d06b5a663 in on_stream_io /systemd-meson-build/../build/src/resolve/resolved-dns-stream.c:419:45
systemd-resolved[112830]:     #13 0x7ff1660bb257 in source_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3498:21
systemd-resolved[112830]:     #14 0x7ff1660ba230 in sd_event_dispatch /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:3950:21
systemd-resolved[112830]:     #15 0x7ff1660bce7c in sd_event_run /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:4011:21
systemd-resolved[112830]:     #16 0x7ff1660bd94e in sd_event_loop /systemd-meson-build/../build/src/libsystemd/sd-event/sd-event.c:4032:21
systemd-resolved[112830]:     #17 0x564d06bfd6e2 in run /systemd-meson-build/../build/src/resolve/resolved.c:92:13
systemd-resolved[112830]:     #18 0x564d06bfd06a in main /systemd-meson-build/../build/src/resolve/resolved.c:99:1
systemd-resolved[112830]:     #19 0x7ff165099151 in __libc_start_main (/usr/lib/libc.so.6+0x28151)
systemd-resolved[112830]: SUMMARY: AddressSanitizer: heap-use-after-free /systemd-meson-build/../build/src/resolve/resolved-dns-answer.c:26:13 in dns_answer_item_compare_func
``` 

/cc @yuwata @keszybz

### PR DESCRIPTION
**Pull request by yuwata**
This fixes a bug introduced by ae45e1a3832fbb6c96707687e42f0b4aaab52c9b.

Fixes #18132.

### CODE REVIEW

File: src/resolve/resolved-dns-answer.c [hunk 1]
```diff
@@ -656,6 +656,7 @@ void dns_answer_order_by_scope(DnsAnswer *a, bool prefer_link_local) {
 
 int dns_answer_reserve(DnsAnswer **a, size_t n_free) {
         DnsAnswer *n;
+        int r;
```
Comment (bluca) [inline src/resolve/resolved-dns-answer.c]: nit: move declaration inside the ```if (*a)``` block

File: src/resolve/resolved-dns-answer.c [hunk 2]
```diff
@@ -685,6 +686,19 @@ int dns_answer_reserve(DnsAnswer **a, size_t n_free) {
                         return -ENOMEM;
 
                 n->n_allocated = ns;
+
+                set_clear(n->set_items);
```
Comment (bluca) [inline src/resolve/resolved-dns-answer.c:698]: any particular reason to clear and repopulate, rather than just increasing the size as needed?

**Comment by bluca** [comment]
@mrc0mmand if you have a reliable reproducer, could you please check this patch, if you have time?

**Comment by mrc0mmand** [comment]
> @mrc0mmand if you have a reliable reproducer, could you please check this patch, if you have time?

Unfortunately I don't, this issue happened quite randomly across several runs in the past couple of days.

File: src/resolve/resolved-dns-answer.c (hunk 2 above)
Comment (topimiettinen) [reply src/resolve/resolved-dns-answer.c:698]: @bluca I think the set contains pointers into array `items` at the end of DnsAnswer structure. Once the structure is realloc()ated, the pointers still refer to old area, so the set has to be refreshed with new pointers to items. So increasing the size would not work.

File: src/resolve/resolved-dns-answer.c [hunk 3]
```diff
@@ -685,6 +686,19 @@ int dns_answer_reserve(DnsAnswer **a, size_t n_free) {
...
+                if (r < 0)
+                        return r;
+
+                for (size_t i = 0; i < n->n_rrs; i++) {
+                        r = set_put(n->set_items, &n->items[i]);
+                        if (r < 0)
+                                return r;
+                        if (r == 0)
+                                return -EEXIST;
+                }
```
Comment (poettering) [inline src/resolve/resolved-dns-answer.c]: so, previously the function had the nice property that it either succeeded or it failed entirely leaving the object the way it was. With this rework, if the realloc() worked, but the set_reserve fails, then we'll have an invalid object.

If you move the set_reserve() before the realloc() then we should be good, as in that case the set_put() calls are guaranteed to succeed.

hence, please do set_reserve() first, then the realloc(), then the set_clear(), and then the set_put() loop. The latter should be enclosed in `assert_se()`, since the earlier set_reserve() should have given us the guarantee that the set_put() will work (and given that the elements previously fit in the same set, hence they should still be good to fit, without conflicts, without EEXIST).

**Review by poettering — CHANGES_REQUESTED** [review]

File: src/resolve/resolved-dns-answer.c (hunk 1 above)
Comment (poettering) [reply src/resolve/resolved-dns-answer.c]: "int r" is special, since it is the variable we store the error code of function calls in in 99% of the cases. it hence gets this special exception to always be placed in the outermost scope, at the top of the function, since it's not just any variable, but one that is an artifact how we do error handling everywhere after all... (if this makes any sense)

hence, I'd leave it like in @yuwata's existing version

File: src/resolve/resolved-dns-answer.c (hunk 2 above)
Comment (poettering) [reply src/resolve/resolved-dns-answer.c:698]: correct

File: src/resolve/resolved-dns-answer.c (hunk 3 above)
Comment (poettering) [reply src/resolve/resolved-dns-answer.c]: and of course add a brief comment next to the assert_se() explaining why we get the guarantee that the set_put() will succeed, since assert_se()'ing around something that can theoretically fail will look like a bug at first sight.

File: src/resolve/resolved-dns-answer.c (hunk 1 above)
Comment (bluca) [reply src/resolve/resolved-dns-answer.c]: I see, that makes sense

File: src/resolve/resolved-dns-answer.c (hunk 2 above)
Comment (bluca) [reply src/resolve/resolved-dns-answer.c:698]: Thanks! Missed that detail

**Comment by yuwata** [comment]
@poettering and @bluca Thank you for the review. Force-pushed a new version. PTAL.

File: src/resolve/resolved-dns-answer.c [hunk 4]
```diff
@@ -680,11 +681,23 @@ int dns_answer_reserve(DnsAnswer **a, size_t n_free) {
...
+                        return r;
+
                 n = realloc(*a, offsetof(DnsAnswer, items) + sizeof(DnsAnswerItem) * ns);
                 if (!n)
                         return -ENOMEM;
 
                 n->n_allocated = ns;
+
+                /* Previously all items are stored in the set, and the enough memory area is allocated
+                 * in the above. So set_put() in the below should not fail. */
```
Comment (poettering) [inline src/resolve/resolved-dns-answer.c]: i'd use stronger language: "cannot" instead of "should not"

**Comment by yuwata** [comment]
@poettering Thank you for your comment. The comment is updated. Setting the green label.
