### PR TITLE
udev: warn string truncation

### LINKED ISSUE #21078: udev_event_apply_format (often silently) truncates its output without returning an error
udev_event_apply_format does not let the caller determine if an error or other truncation has occurred: Unlike the strpcpy family of functions, it always returns a positive value (assuming the [assert](https://github.com/systemd/systemd/blob/v249/src/udev/udev-event.c#L489) is correct). In most cases, it also does not log a warning.

This is especially problematic for rules that use [`PROGRAM="..."`](https://github.com/systemd/systemd/blob/v249/src/udev/udev-rules.c#L1696)/[`RUN="..."`](https://github.com/systemd/systemd/blob/v249/src/udev/udev-rules.c#L2202-L2205)/etc where the command is silently truncated if it exceeds 1023 characters (UDEV_PATH_SIZE-1), which causes the wrong command to be executed; the silent truncation makes this particularly hard to debug (e.g. https://github.com/raspberrypi/linux/issues/3779#issuecomment-758029604).

Curiously, the return value of `udev_event_apply_format` appears to be ignored everywhere it is called (it's cast to `void`).

There are four main cases of truncation:
* The two error cases (["Invalid format string"](https://github.com/systemd/systemd/blob/v249/src/udev/udev-event.c#L461), ["Failed to substitute variable ... or apply format"](https://github.com/systemd/systemd/blob/v249/src/udev/udev-event.c#L473-L475)) break out of the loop (and ignore the rest of the format string). As these are already special-cased, returning an error here would be easy.
* When the [character-by-character copy](https://github.com/systemd/systemd/blob/v249/src/udev/udev-event.c#L464-L465) runs out of space, it also simply breaks out of the loop. Again, since this is already special-cased, it could easily return an error.
* [udev_event_subst_format](https://github.com/systemd/systemd/blob/v249/src/udev/udev-event.c#L234) ignores the return value from any of its calls to `strpcpy(&s, l, ...)` or similar (which return 0 to indicate truncation). It looks like this could be changed to take `char **dest` and simply return the result of strpcpy in most cases (which would allow truncation to be detected), with minor modifications to the handling of [FORMAT_SUBST_LINKS](https://github.com/systemd/systemd/blob/v249/src/udev/udev-event.c#L406-L413) (which calls strpcpy/strpcpyl multiple times) and [replace_whitespace](https://github.com/systemd/systemd/blob/v249/src/udev/udev-event.c#L480-L483).

`udev_event_subst_format` also substitutes many error cases (mainly `-ENOENT`) with the empty string (`goto null_terminate;`). While this might be reasonable if the format string is a single substitution, this is less likely to be the desired behaviour otherwise. For example, `$devnode`/`%N` is substituted with the empty string on ENOENT, which doesn't make sense in its typical uses cases, e.g. Debian udev 232-25+deb9u13 seems to use it entirely within command lines:
```
> grep -rE '\$devnode|%N' /lib/udev /etc/udev/
Binary file /lib/udev/hwdb.bin matches
/lib/udev/rules.d/75-probe_mtd.rules:KERNEL=="mtd*ro", IMPORT{program}="mtd_probe $devnode"
/lib/udev/rules.d/64-btrfs.rules:IMPORT{builtin}="btrfs ready $devnode"
/lib/udev/rules.d/60-persistent-storage.rules:KERNEL=="sd*[!0-9]|sr*", ENV{ID_SERIAL}!="?*", SUBSYSTEMS=="scsi", ATTRS{vendor}=="ATA", IMPORT{program}="ata_id --export $devnode"
/lib/udev/rules.d/60-persistent-storage.rules:KERNEL=="sd*[!0-9]|sr*", ENV{ID_SERIAL}!="?*", SUBSYSTEMS=="scsi", ATTRS{type}=="5", ATTRS{scsi_level}=="[6-9]*", IMPORT{program}="ata_id --export $devnode"
/lib/udev/rules.d/60-persistent-storage.rules:KERNEL=="sd*[!0-9]|sr*", ENV{ID_SERIAL}!="?*", ATTR{removable}=="0", SUBSYSTEMS=="usb", IMPORT{program}="ata_id --export $devnode"
/lib/udev/rules.d/60-persistent-storage.rules:KERNEL=="sd*[!0-9]|sr*", ENV{ID_SERIAL}!="?*", IMPORT{program}="scsi_id --export --whitelisted -d $devnode", ENV{ID_BUS}="scsi"
/lib/udev/rules.d/60-persistent-storage.rules:KERNEL=="cciss*", ENV{DEVTYPE}=="disk", ENV{ID_SERIAL}!="?*", IMPORT{program}="scsi_id --export --whitelisted -d $devnode", ENV{ID_BUS}="cciss"
/lib/udev/rules.d/60-persistent-v4l.rules:IMPORT{program}="v4l_id $devnode"
/lib/udev/rules.d/60-persistent-storage-tape.rules:SUBSYSTEM=="scsi_generic", SUBSYSTEMS=="scsi", ATTRS{type}=="8", IMPORT{program}="scsi_id --sg-version=3 --export --whitelisted -d $devnode", \
/lib/udev/rules.d/60-cdrom_id.rules:ENV{DISK_EJECT_REQUEST}=="?*", RUN+="cdrom_id --eject-media $devnode", GOTO="cdrom_end"
/lib/udev/rules.d/60-cdrom_id.rules:IMPORT{program}="cdrom_id --lock-media $devnode"
```

There's also potential truncation in the handling of FORMAT_SUBST_ATTR (within [udev_resolve_subsys_kernel](https://github.com/systemd/systemd/blob/af55491028a0722088a16ff6e20de2d6f1507640/src/shared/udev-util.c#L550-L559), and in the [strscpy of the value from device_get_sysattr_value_maybe_from_netlink or device_get_sysattr_value_maybe_from_netlink](https://github.com/systemd/systemd/blob/main/src/udev/udev-event.c#L366)), but it is perhaps reasonable to assume that the length of these attributes do not exceed UDEV_NAME_SIZE.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #21078.

### CODE REVIEW

File: src/basic/strxcpyx.c [hunk 1]
```diff
@@ -15,89 +15,116 @@
 #include <stdio.h>
 #include <string.h>
 
+#include "string-util.h"
 #include "strxcpyx.h"
 
-size_t strnpcpy(char **dest, size_t size, const char *src, size_t len) {
+size_t strnpcpy_full(char **dest, size_t size, const char *src, size_t len, bool *ret_truncated) {
+        bool truncated = false;
```
Comment (keszybz) [inline src/basic/strxcpyx.c:22]: Please add some tests for all the new functions. Those things are usually tricky to get right in all corner cases.

File: src/udev/udev-event.c [hunk 2]
```diff
@@ -382,42 +387,46 @@ static ssize_t udev_event_subst_format(
...
+                FOREACH_DEVICE_DEVLINK(dev, val) {
+                        bool t;
+
                         if (s == dest)
-                                strpcpy(&s, l, val + STRLEN("/dev/"));
+                                strpcpy_full(&s, l, val + STRLEN("/dev/"), &t);
                         else
-                                strpcpyl(&s, l, " ", val + STRLEN("/dev/"), NULL);
+                                strpcpyl_full(&s, l, &t, " ", val + STRLEN("/dev/"), NULL);
+                        truncated = truncated || t;
```
Comment (keszybz) [inline src/udev/udev-event.c]: Hmm, at least here, if truncation occurs, we just shouldn't follow the link.

File: src/udev/udev-rules.c [hunk 3]
```diff
@@ -1876,8 +1904,12 @@ static int udev_rule_apply_token_to_event(
         }
         case TK_M_IMPORT_PARENT: {
                 char buf[UDEV_PATH_SIZE];
+                bool truncated;
+
+                (void) udev_event_apply_format(event, token->value, buf, sizeof(buf), false, &truncated);
+                if (truncated)
+                        log_rule_warning(dev, rules, "Result of substitution into %s is truncated.", token->value);
```
Comment (keszybz) [inline src/udev/udev-rules.c]: The message is also misleading. Because it's the name of the thing to import that is truncated, not the thing itself.

And importing the wrong thing because the name got truncated seems very iffy…

**Review by keszybz — COMMENTED** [review]
I'm not convinced that this is the right approach. In the cases where program *output* is truncated, OK, I guess it would make sense to warn and continue. But in most cases, e.g. when truncation occurs in the attribute value to set or a program to call, I think we should cause that part of the rule to fail. The truncated value should not be used to take any action.

**Comment by yuwata** [comment]
Updated.
- tests for `strxcyx_full()` are added.
- refuse to process token when truncation is detected.
- drop the last line of the program result when importing property from the result.

PTAL.

File: src/basic/strxcpyx.c [hunk 4]
```diff
@@ -15,89 +15,110 @@
...
+
+        if (ret_truncated)
+                *ret_truncated = truncated;
+
         return size;
 }
 
-size_t strpcpyl(char **dest, size_t size, const char *src, ...) {
+size_t strpcpyl_full(char **dest, size_t size, bool *ret_truncated, const char *src, ...) {
+        bool truncated = false, t;
```
Comment (bluca) [inline src/basic/strxcpyx.c]: reduce scope of `t` by moving inside do-while?

File: src/basic/strxcpyx.c [hunk 5]
```diff
@@ -15,89 +15,110 @@
...
         assert(dest);
         assert(src);
 
-        return strnscpy(dest, size, src, strlen(src));
+        return strnscpy_full(dest, size, src, strlen(src), ret_truncated);
 }
 
-size_t strscpyl(char *dest, size_t size, const char *src, ...) {
+size_t strscpyl_full(char *dest, size_t size, bool *ret_truncated, const char *src, ...) {
+        bool truncated = false, t;
```
Comment (bluca) [inline src/basic/strxcpyx.c]: ditto

File: src/udev/udev-rules.c [hunk 6]
```diff
@@ -1520,7 +1534,10 @@ static int attr_subst_subdir(char attr[static UDEV_PATH_SIZE]) {
                 if (dent->d_name[0] == '.')
                         continue;
 
-                strscpyl(p, size, dent->d_name, tail, NULL);
+                strscpyl_full(p, size, &truncated, dent->d_name, tail, NULL);
```
Comment (bluca) [inline src/udev/udev-rules.c]: shouldn't this pass `&truncated` instead of NULL to strscpyl_full?

Comment (bluca) [reply src/udev/udev-rules.c]: oh wait I got confused with the other, it's not the last parameter here, nvm

File: src/udev/udev-rules.c [hunk 7]
```diff
@@ -1849,9 +1849,11 @@ static int udev_rule_apply_token_to_event(
                 }
 
                 r = strv_split_newlines_full(&lines, result, EXTRACT_RETAIN_ESCAPE);
-                if (r < 0)
+                if (r < 0) {
```
Comment (bluca) [inline src/udev/udev-rules.c:1853]: this could also return EINVAL, no? Shouldn't it check explicitly for ENOMEM before returning?

**Comment by yuwata** [comment]
@bluca Thanks. The above points are addressed. PTAL.

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
Rebased.
