### PR TITLE
pstore: several minor follow-ups

### LINKED ISSUE #13122: systemd-pstore seems to crash under ASan when it processes empty files
```
-bash-4.4# /lib/systemd/systemd-pstore
=================================================================
==104==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000275 at pc 0x7f105cfc3add bp 0x7ffc59562930 sp 0x7ffc595620d8
WRITE of size 6 at 0x602000000275 thread T0
    #0 0x7f105cfc3adc  (/usr/lib64/libasan.so.5+0x40adc)
    #1 0x404bde in move_file ../src/pstore/pstore.c:148
    #2 0x406679 in process_dmesg_files ../src/pstore/pstore.c:285
    #3 0x408683 in run ../src/pstore/pstore.c:384
    #4 0x4087ee in main ../src/pstore/pstore.c:393
    #5 0x7f105a8af412 in __libc_start_main (/usr/lib64/libc.so.6+0x24412)
    #6 0x4024ed in _start (/usr/lib/systemd/systemd-pstore+0x4024ed)

0x602000000275 is located 0 bytes to the right of 5-byte region [0x602000000270,0x602000000275)
allocated by thread T0 here:
    #0 0x7f105d072c08 in __interceptor_malloc (/usr/lib64/libasan.so.5+0xefc08)
    #1 0x4049f6 in move_file ../src/pstore/pstore.c:145
    #2 0x406679 in process_dmesg_files ../src/pstore/pstore.c:285
    #3 0x408683 in run ../src/pstore/pstore.c:384
    #4 0x4087ee in main ../src/pstore/pstore.c:393
    #5 0x7f105a8af412 in __libc_start_main (/usr/lib64/libc.so.6+0x24412)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib64/libasan.so.5+0x40adc)
Shadow bytes around the buggy address:
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff8000: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fd
  0x0c047fff8010: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fd
  0x0c047fff8020: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff8030: fa fa fd fa fa fa fd fd fa fa fd fd fa fa fd fd
=>0x0c047fff8040: fa fa fd fa fa fa fd fa fa fa 00 02 fa fa[05]fa
  0x0c047fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==104==ABORTING
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #13122.

cc @evverx and @edevolder.

### CODE REVIEW

File: src/pstore/pstore.c [hunk 1]
```diff
@@ -141,12 +139,14 @@ static int move_file(PStoreEntry *pe, const char *subdir) {
         field = strjoina("MESSAGE=PStore ", pe->dirent.d_name, suffix);
         iovec[n_iovec++] = IOVEC_MAKE_STRING(field);
 
-        field_size = strlen("FILE=") + pe->content_size;
-        field = malloc(field_size);
```
Comment (evverx) [inline src/pstore/pstore.c:145]: Currently the code seems to be based on the assumption that `malloc` is always called here. If it isn't the memory allocated via `strjoina` `field` points to is freed because of `_cleanup_free_` causing `systemd-pstore` to crash with:
```
==8432==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x7ffc6ff9de60 in thread T0
    #0 0x7fe77d3f0840 in __interceptor_free (/lib64/libasan.so.5+0xef840)
    #1 0x404235 in freep ../src/basic/alloc-util.h:83
    #2 0x404235 in move_file ../src/pstore/pstore.c:120
    #3 0x406554 in run ../src/pstore/pstore.c:385
    #4 0x406554 in main ../src/pstore/pstore.c:390
    #5 0x7fe77b29e412 in __libc_start_main (/lib64/libc.so.6+0x24412)
    #6 0x4024ad in _start (/home/vagrant/systemd/build/systemd-pstore+0x4024ad)

Address 0x7ffc6ff9de60 is located in stack of thread T0
SUMMARY: AddressSanitizer: bad-free (/lib64/libasan.so.5+0xef840) in __interceptor_free
==8432==ABORTING
```

I think it would be better to fix https://github.com/systemd/systemd/issues/13122 by replacing `stpcpy` (which tries to write a null byte `field` doesn't have room for) with `memcpy`. I'd also avoid `strjoina` there in general or add another variable declared without `_cleanup_free_`.

Comment (yuwata) [reply src/pstore/pstore.c:145]: Ouch. Will fix that.

**Comment by yuwata** [comment]
@evverx Thanks. Updated.

File: src/pstore/pstore.c [hunk 2]
```diff
@@ -170,8 +170,8 @@ static int move_file(PStoreEntry *pe, const char *subdir) {
 }
 
 static int write_dmesg(const char *dmesg, size_t size, const char *id) {
-        _cleanup_(unlink_and_freep) char *ofd_path = NULL;
-        _cleanup_free_ char *tmp_path = NULL;
+        _cleanup_(unlink_and_freep) char *tmp_path = NULL;
+        _cleanup_free_ char *ofd_path = NULL;
```
Comment (poettering) [inline src/pstore/pstore.c:177]: the `ofd_path = mfree(ofd_path)` line at the end of this function also needs updating

**Comment by poettering** [comment]
btw, I think it would also be good to add a line like `ConditionDirectoryNotEmpty=/sys/fs/pstore` or so, to only run the service if there are actually files to process. That way people don't have to pay the penalty for it if there's nothing to do

**Comment by poettering** [comment]
/cc @mattiasb who commented about the first fix:

https://github.com/systemd/systemd/commit/9b4abc69b201e5d7295e1b0762883659f053e747#r34386152

File: src/pstore/pstore.c (hunk 2 above)
Comment (poettering) [reply src/pstore/pstore.c:177]: (it should be changed to `tmp_path = mfree(tmp_path)` to "disarm" the unlink destructor, since at that point the file is already gone on disk

**Comment by yuwata** [comment]
Updated.
- @mattiasb is mentioned in the first commit.
- ConditionDirectoryNotEmpty= is added.

File: src/pstore/pstore.c (hunk 2 above)
Comment (yuwata) [reply src/pstore/pstore.c:177]: I see. Fixed.

**Comment by keszybz** [comment]
LGTM.
