### PR TITLE
core: fix stack-use-after-scope

### LINKED ISSUE #18753: Possible stack-use-after-scope in config_parse_many()
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > Arch Linux

The nightly gcc+ASan job started failing tonight with:

```
==1==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f9478e38090 at pc 0x7f947e0ca7ed bp 0x7ffc9e849240 sp 0x7ffc9e849230
READ of size 8 at 0x7f9478e38090 thread T0 (systemd)
    #0 0x7f947e0ca7ec in strv_extend_strv_concat ../build/src/basic/strv.c:226
    #1 0x7f947de2a173 in config_parse_many ../build/src/shared/conf-parser.c:506
    #2 0x55e24dc988e9 in parse_config_file ../build/src/core/main.c:721
    #3 0x55e24dc9911c in parse_configuration ../build/src/core/main.c:2392
    #4 0x55e24dc9bcb2 in main ../build/src/core/main.c:2763
    #5 0x7f947ca0fb24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
    #6 0x55e24dc8991d in _start (/usr/lib/systemd/systemd+0x47191d)

Address 0x7f9478e38090 is located in stack of thread T0 (systemd) at offset 144 in frame
    #0 0x55e24dc95c86 in parse_config_file ../build/src/core/main.c:634

  This frame has 5 object(s):
    [48, 56) '_free_files' (line 703)
    [80, 88) '_free_dirs' (line 703)
    [112, 128) '<unknown>'
    [144, 184) '<unknown>' <== Memory access at offset 144 is inside this variable
    [224, 2744) 'items' (line 635)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope ../build/src/basic/strv.c:226 in strv_extend_strv_concat
Shadow bytes around the buggy address:
  0x0ff30f1befc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff30f1befd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff30f1befe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff30f1beff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff30f1bf000: f1 f1 f1 f1 00 00 00 f2 00 00 00 f2 f2 f2 f8 f8
=>0x0ff30f1bf010: f2 f2[f8]f8 f8 f8 f8 f2 f2 f2 f2 f2 00 00 00 00
  0x0ff30f1bf020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff30f1bf030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff30f1bf040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff30f1bf050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff30f1bf060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==1==ABORTING
```

/cc @keszybz

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug introduced by f70e6fb471a4eeed8e2a4a7c608beabbb0aba8be.

Fixes #18753.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @mrc0mmand

File: src/core/main.c [hunk 1]
```diff
@@ -700,26 +700,24 @@ static int parse_config_file(void) {
...
                         return log_error_errno(r, "Failed to determine config file paths: %m");
-                files = (const char* const*) _free_files;
-                dirs = (const char* const*) _free_dirs;
+
                 suffix = "user.conf.d";
         }
 
         (void) config_parse_many(
-                        files, dirs, suffix,
+                        (const char* const*) (files ?: STRV_MAKE(PKGSYSCONFDIR "/system.conf")),
```
Comment (bluca) [inline src/core/main.c:718]: iirc we don't want to use these macros that create data storage on the stack inlined in function calls either - so perhaps just unconditionally define these above in separate variables, inline with the declarations, and use them if files/dirs are empty?

Comment (yuwata) [reply src/core/main.c:718]: > iirc we don't want to use these macros that create data storage on the stack inlined in function calls either

I cannot remember we have such coding rule.
Maybe, you are confused with the limitation about `alloca()`?

Comment (keszybz) [reply src/core/main.c:718]: This patch is OK. The STRV_MAKEd object lives until the function returns, which is enough.
The original bug was that the object was declared in a scope created by the conditional. I think this is nicer code than what I wrote anyway, so let's merge it.

Comment (bluca) [reply src/core/main.c:718]: mmh I have the distinct memory of a review where I'd been asked not to use STR_MAKE inline - might be misremembering though. Good to know that it's fine
