### PR TITLE
libudev: rescan devices when filter is updated

### LINKED ISSUE #12776: libudev does not refresh device list
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Updating the matches of an `udev_enumerate` instance, calling `udev_enumerate_scan_devices` and then iterating the list retrieved using `udev_enumerate_get_list_entry` should provide different different `udev_list_entry`s if the set of devices arising from the updated match differs from the the original match. 

**Unexpected behaviour you saw**
 > The resulting list does not differ.

**Steps to reproduce the problem**
Given the following program:
```c++
#include <libudev.h>
#include <iostream>

int main()
  {
  udev * ctx = udev_new();
  udev_enumerate * enumerate = udev_enumerate_new(ctx);

  udev_enumerate_add_match_subsystem(enumerate, "leds");
  udev_enumerate_scan_devices(enumerate);

  for(udev_list_entry * entry = udev_enumerate_get_list_entry(enumerate); entry; entry = udev_list_entry_get_next(entry))
    {
    std::cout << "entry: " << udev_list_entry_get_name(entry) << '\n';
    }

  udev_enumerate_add_match_subsystem(enumerate, "block");
  udev_enumerate_scan_devices(enumerate);

  std::cout << " ===== \n";

  for(udev_list_entry * entry = udev_enumerate_get_list_entry(enumerate); entry; entry = udev_list_entry_get_next(entry))
    {
    std::cout << "entry: " << udev_list_entry_get_name(entry) << '\n';
    }

  udev_enumerate_unref(enumerate);
  udev_unref(ctx);
  }
```
One would expect that the second loop also prints the syspaths of the devices in the `block` subsystem.

It seems that the issue lies in the way the `udev_enumerate_add_match_`... functions work. Considering the definition of `udev_enumerate` in [libudev-enumerate.c](https://github.com/systemd/systemd/blob/master/src/libudev/libudev-enumerate.c):

```c
struct udev_enumerate {
        struct udev *udev;
        unsigned n_ref;
        struct udev_list devices_list;
        bool devices_uptodate:1;

        sd_device_enumerator *enumerator;
};
```
a valid expection would be for the matching functions to set the non-static member variable `devices_uptodate` to `false`, similar to how the underlying implementation does (see [device-enumerator.c](https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-device/device-enumerator.c))

The documentation is silent about whether or not it is valid to adjust the matches of an enumerator after initial iteration of the original device list.

### PR DESCRIPTION
**Pull request by yuwata**
And this also contains several cleanups.

Fixes #12776.

### CODE REVIEW

File: src/libudev/libudev-device-internal.h [hunk 1]
```diff
@@ -23,16 +23,16 @@ struct udev_device {
...
+        struct udev_list *tags;
         uint64_t tags_generation;
-        struct udev_list devlinks;
+        struct udev_list *devlinks;
         uint64_t devlinks_generation;
         bool properties_read:1;
         bool tags_read:1;
         bool devlinks_read:1;
-        struct udev_list sysattrs;
+        struct udev_list *sysattrs;
```
Comment (keszybz) [inline src/libudev/libudev-device-internal.h]: <strike>Hmm, can you provide the justification for this change? `struct udev_device` is already "hidden", so by making those separate we're not "hiding" anything. And this increases the allocation cost quite a bit, because more memory is used (for the pointers), and a lot of small additional allocations are done. And this is a "hot path" in the sense that we have can thousands of such objects, so the efficiency of this data structure matters.</strike>

OK, so this is done ini preparation for the reimplementation using hashmaps. I think it'd be nice to say something in the commit message explaining this.

File: src/libudev/libudev-list.c [hunk 2]
```diff
@@ -87,174 +64,121 @@ struct udev_list *udev_list_new(bool unique) {
...
-        list->entries_max = 0;
-        udev_list_entry_foreach_safe(entry_loop, entry_tmp, udev_list_get_entry(list))
-                udev_list_entry_delete(entry_loop);
+        if (!list)
+                return;
+
+        if (list->unique) {
+                hashmap_clear_with_destructor(list->unique_entries, udev_list_entry_free);
+                list->uptodate = false;
+                LIST_HEAD_INIT(list->entries);
```
Comment (keszybz) [inline src/libudev/libudev-list.c]: Why call LIST_HEAD_INIT here? It should not be necessary, if `udev_list_entry_free` works properly.

**Comment by yuwata** [comment]
@keszybz Thank you for the comments. I've updated commit message and drop unnecessary cleanup. PTAL.

**Comment by keszybz** [comment]
LGTM.
