### PR TITLE
file-io: Fix copying sparse files

### LINKED ISSUE #28781: src/shrared/copy.c copy_bytes_full can copy beyond max_bytes when using COPY_HOLE
### systemd version the issue has been seen with

commit ac8db36cbc26694ee94beecc8dca208ec4b5fd45

### Used distribution

Ubuntu 22.10

### Linux kernel version used

6.2.0-26-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-repart

### Expected behaviour you didn't see

All partitions copied out using the split option are the same size and contents as they are in the disk image.

### Unexpected behaviour you saw

The last partition copied out when using the split option was larger than the specified partition size using MaxSizeBytes. When I checked the extra data it includes the backup GPT.

### Steps to reproduce the problem

The final partition must have a hole at the end. The easiest way to do this is to create a verity hash partition that is larger than required for the data partition.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by mcassaniti**
This change makes sure a data copy using `copy_bytes()` does not exceed the `max_bytes` value when using `COPY_HOLES` and `max_bytes` stops before the next data section.

Fixes #28781

### CODE REVIEW

File: src/shared/copy.c [hunk 1]
```diff
@@ -275,9 +275,17 @@ int copy_bytes_full(
...
+                                n = MIN(max_bytes, (size_t) e - c);
+                                r = create_hole(fdt, n);
                                 if (r < 0)
                                         return r;
+
+                                if (max_bytes <= (uint64_t) n)
+                                        break;
+
+                                /* Note how many bytes were transferred as required */
+                                max_bytes -= max_bytes == UINT64_MAX ? 0 : n;
```
Comment (daandemeyer) [inline src/shared/copy.c]: How about this instead:

```c
if (e > c) {
        /* Make sure our new hole doesn't go over the maximum size we're allowed to
         * copy. */
        n = MIN(max_bytes, (uint64_t) e - c);

        r = create_hole(fdt, n);
        if (r < 0)
                return r;

        /* Make sure holes are taken into account in the maximum size we're supposed
         * to copy. */
        max_bytes -= n;
        if (max_bytes <= 0)
                break;

        /* Update the size we're supposed to copy in this iteration if needed. */
        if (m > max_bytes)
                 m = max_bytes;
}
```

File: src/test/test-copy.c [hunk 2]
```diff
@@ -436,6 +436,72 @@ TEST_RET(copy_holes) {
...
+         * sure that the holes are aligned to the block size.
+         */
+
+        r = RET_NERRNO(fallocate(fd, FALLOC_FL_PUNCH_HOLE | FALLOC_FL_KEEP_SIZE, 0, blksz));
+        if (ERRNO_IS_NOT_SUPPORTED(r))
+                return log_tests_skipped("Filesystem doesn't support hole punching");
+        assert_se(r >= 0);
+        assert_se(lseek(fd, blksz, SEEK_CUR) >= 0);
+        for (i = 0; i < blksz / sizeof(data); i++)
+                assert_se(write(fd, data, sizeof(data)) >= 0);
```
Comment (daandemeyer) [inline src/test/test-copy.c]: We probably want to assert that we wrote as much data as we passed in here? Might be better to use `loop_write()` here and then `assert >= 0` will be sufficient

File: src/test/test-copy.c [hunk 3]
```diff
@@ -436,6 +436,72 @@ TEST_RET(copy_holes) {
...
+        assert_se(fallocate(fd, FALLOC_FL_PUNCH_HOLE | FALLOC_FL_KEEP_SIZE, 2 * blksz, 2 * blksz) >= 0);
+        assert_se(lseek(fd, 2 * blksz, SEEK_CUR) >= 0);
+        for (i = 0; i < blksz / sizeof(data); i++)
+                assert_se(write(fd, data, sizeof(data)) >= 0);
```
Comment (daandemeyer) [inline src/test/test-copy.c]: Ditto for `loop_write()`

File: src/test/test-copy.c [hunk 4]
```diff
@@ -436,6 +436,72 @@ TEST_RET(copy_holes) {
         return 0;
 }
 
+TEST_RET(copy_holes_with_gaps) {
+        _cleanup_(unlink_tempfilep) char fn[] = "/var/tmp/test-copy-hole-with-gaps-fd-src-XXXXXX";
+        _cleanup_(unlink_tempfilep) char fn_copy[] = "/var/tmp/test-copy-hole-with-gaps-fd-tgt-XXXXXX";
```
Comment (daandemeyer) [inline src/test/test-copy.c]: Please replace this with something like:

```c
_cleanup_(rm_rf_physical_and_freep) char *t = NULL;
_cleanup_close_ int fd = -EBADF, fd_copy = -EBADF;

assert_se((tfd = mkdtemp_open(NULL, 0, &t)) >= 0);
assert_se((fd = openat(tfd, "src", ...) >= 0);
assert_se((fd_copy = openat(tfd, "dst", ...) >= 0);
```

**Review by DaanDeMeyer — CHANGES_REQUESTED** [review]
Looks great, thanks for proposing a fix, a few comments

File: src/shared/copy.c (hunk 1 above)
Comment (mcassaniti) [reply src/shared/copy.c]: The first part certainly helps, especially for 32-bit, but the second is (I think) incorrect. max_bytes should stay as UINT64_MAX (i.e.: not defined) if the called does not specify a value. That is why the ternary operator is there. I only wanted to change max_bytes at the last moment.

I'm more than open to suggestions as long as the tests pass. I think the mkosi test is possibly unrelated.

Comment (daandemeyer) [reply src/shared/copy.c]: Right, good point, this should solve that issue

```c
if (e > c) {
        /* Make sure our new hole doesn't go over the maximum size we're allowed to
         * copy. */
        n = MIN(max_bytes, (uint64_t) e - c);

        r = create_hole(fdt, n);
        if (r < 0)
                return r;

        /* Make sure holes are taken into account in the maximum size we're supposed
         * to copy. */
        if (max_bytes != UINT64_MAX) {
                max_bytes -= n;
                if (max_bytes <= 0)
                        break;
        )

        /* Update the size we're supposed to copy in this iteration if needed. */
        if (m > max_bytes)
                 m = max_bytes;
}
```

File: src/test/test-copy.c (hunk 4 above)
Comment (mcassaniti) [reply src/test/test-copy.c]: I copied these from the test above. If that is no good then I'm happy to apply your suggestions.

Comment (daandemeyer) [reply src/test/test-copy.c]: What I suggested is how we try to do things for new tests. The test you copied from just hasn't been migrated to that pattern yet.

File: src/shared/copy.c (hunk 1 above)
Comment (mcassaniti) [reply src/shared/copy.c]: Done

File: src/test/test-copy.c (hunk 2 above)
Comment (mcassaniti) [reply src/test/test-copy.c]: Done

File: src/test/test-copy.c (hunk 3 above)
Comment (mcassaniti) [reply src/test/test-copy.c]: Done

File: src/test/test-copy.c (hunk 4 above)
Comment (mcassaniti) [reply src/test/test-copy.c]: Done

**Review by DaanDeMeyer — APPROVED** [review]

File: src/test/test-copy.c [hunk 5]
```diff
@@ -436,6 +437,77 @@ TEST_RET(copy_holes) {
...
+        _cleanup_close_ int tfd = -EBADF, fd = -EBADF, fd_copy = -EBADF;
+
+        int r;
+        struct stat stat;
+        off_t blksz;
+        char data[16] = "0123456789ABCDEF";
+
+        assert_se((tfd = mkdtemp_open(NULL, 0, &t)) >= 0);
+        assert_se((fd = openat(tfd, "src", O_CREAT | O_RDWR)) >= 0);
+        assert_se((fd_copy = openat(tfd, "dst", O_CREAT | O_WRONLY)) >= 0);
```
Comment (daandemeyer) [inline src/test/test-copy.c]: These need a mode as well. 0600 should be fine here

**Comment by bluca** [comment]
```
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:126:11: error: call to ‘__openat_missing_mode’ declared with attribute error: openat with O_CREAT or O_TMPFILE in third argument needs 4 arguments
  126 |           __openat_missing_mode ();
      |           ^~~~~~~~~~~~~~~~~~~~~~~~
In function ‘openat’,
    inlined from ‘test_copy_holes_with_gaps’ at ../src/test/test-copy.c:451:9:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:126:11: error: call to ‘__openat_missing_mode’ declared with attribute error: openat with O_CREAT or O_TMPFILE in third argument needs 4 arguments
  126 |           __openat_missing_mode ();
```

File: src/test/test-copy.c (hunk 5 above)
Comment (mcassaniti) [reply src/test/test-copy.c]: Hopefully fixed.

**Review by DaanDeMeyer — APPROVED** [review]

**Review by bluca — APPROVED** [review]

**Comment by mcassaniti** [comment]
Not bad for a Python programmer.

**Comment by bluca** [comment]
> Not bad for a Python programmer.

you jinxed it!

```
stderr:
/* test_copy_file */
/* test_copy_tree_replace_file */
/* test_copy_tree_replace_dirs */
/* test_copy_file_fd */
/* test_copy_tree */
ignore/file is in the denylist, ignoring
/* test_copy_bytes */
/* test_copy_bytes_regular_file */
test_copy_bytes_regular_file_one try_reflink=no max_bytes=18446744073709551615
test_copy_bytes_regular_file_one try_reflink=yes max_bytes=18446744073709551615
test_copy_bytes_regular_file_one try_reflink=no max_bytes=1000
test_copy_bytes_regular_file_one try_reflink=yes max_bytes=1000
test_copy_bytes_regular_file_one try_reflink=no max_bytes=32000
test_copy_bytes_regular_file_one try_reflink=yes max_bytes=32000
/* test_copy_atomic */
/* test_copy_proc */
/* test_copy_holes */
/* test_copy_holes_with_gaps */
Assertion 'loop_write(fd, data, blksz, 0) >= 0' failed at src/test/test-copy.c:472, function test_copy_holes_with_gaps(). Aborting.
```

**Comment by mcassaniti** [comment]
> Assertion 'loop_write(fd, data, blksz, 0) >= 0' failed at src/test/test-copy.c:472, function test_copy_holes_with_gaps().

Ummm, help?

**Comment by bluca** [comment]
Try to add some debug to print the return code? Otherwise it's difficult to say

**Comment by mcassaniti** [comment]
> Try to add some debug to print the return code? Otherwise it's difficult to say

I got "Bad address" as the error. When I take a look at the implementation of loop_write this makes sense.

@DaanDeMeyer it seems loop_write does not copy the same buffer value over and over but instead writes bytes from the input buffer to the file with some potential polling. I'd be better using the loop I had before which I'll revert to.

**Comment by DaanDeMeyer** [comment]
@mcassaniti My idea was actually to use loop_write() in combination with the loop you were using first instead of a raw write()

**Comment by DaanDeMeyer** [comment]
@mcassaniti I pushed an update to your PR to use loop_write() and a few other cleanups.

**Comment by mcassaniti** [comment]
I don't think those CI failures were me.
