### PR TITLE
machinectl: do not format size if freed disk space is "-1"

### LINKED ISSUE #11941: machinectl clean: Total freed exclusive disk space (null)
**systemd version the issue has been seen with**
> systemd 241 (241.7-2-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > `machinectl clean` should specify the size of the freed disk space.

**Unexpected behaviour you saw**
 > `machinectl clean` sets `(null)` for the freed disk space:
```
Removed image '.tar-https:\x2f\x2fnspawn\x2eorg\x2fstorage\x2fdebian\x2fstretch\x2ftar\x2fstretch\x2etar\x2exz.\x225c82e563-2f75538\x22'. Freed exclusive disk space: (null)
Removed 1 images in total. Total freed exclusive disk space (null).
```

**Steps to reproduce the problem**

`machinectl clean`

### PR DESCRIPTION
**Pull request by yuwata**
Closes #11941.

### CODE REVIEW

File: src/machine/machinectl.c [hunk 1]
```diff
@@ -2666,18 +2666,22 @@ static int clean_images(int argc, char *argv[], void *userdata) {
...
+                }
                 c++;
         }
 
         r = sd_bus_message_exit_container(reply);
         if (r < 0)
                 return bus_log_parse_error(r);
 
-        log_info("Removed %u images in total. Total freed exclusive disk space %s.",
+        log_info("Removed %u images in total. Total freed exclusive disk space: %s.",
```
Comment (poettering) [inline src/machine/machinectl.c]: Hmm, I think we should tweak this a bit: if we don't know how much disk space was removed in total, we shouldn't mention this either. Hence, I think `total` should be initialized to UINT64_MAX initially, and then in the loop we should have this:

```c
if (total == UINT64_MAX)
        total = usage;
else
        total += usage;
```

that way, if total is UINT64_MAX at the end of the loop we don't know how much we cleaned up, and it if itsn't we know that at least this much was cleared.

**Comment by yuwata** [comment]
@poettering Thank you for the review. Updated. Though, the updated version may be different from you expected. I hope I understand your comment correctly...

**Comment by poettering** [comment]
This is not what I meant, but this works too, and maybe even better. Thanks!
