### PR TITLE
missing_syscall: when adding syscall replacements, use different names

### LINKED ISSUE #8099: glibc-2.27 memfd_create not being detected correctly with kernels 3.10.y/3.14.y
### Submission type

- Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

>LibreELEC 9.0

### In case of bug report: Expected behaviour you didn't see

>Successful systemd build with glibc-2.27 and kernels that do not implement `memfd_create`.

### In case of bug report: Unexpected behaviour you saw

>systemd build failure with glibc-2.27 and kernels that do not implement `memfd_create`.

> systemd builds successfully with glibc-2.27 and kernel 4.14.16.

### In case of bug report: Steps to reproduce the problem

> Build systemd-237 with glibc-2.27 and kernels 3.10.108 or 3.14.29 (most likely any other kernel prior to 3.17.0 when the `memfd_create` syscall is introduced to the kernel).

I've encountered a problem building systemd-237 and glibc-2.27 with kernels that do not implement the `memfd_create` syscall (ie. any kernel before 3.17.0).

For example, when building 3.10.108, glibc-2.27 and systemd-237:
```
[66/985] Compiling C object 'src/basic/basic@sta/barrier.c.o'.
[67/985] Compiling C object 'src/basic/basic@sta/calendarspec.c.o'.
FAILED: src/basic/basic@sta/calendarspec.c.o
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Hub.arm-9.0-devel-next/toolchain/bin/armv8a-libreelec-linux-gnueabi-gcc -march=armv8-a+crc -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=cortex-a53 -mfloat-abi=hard -mfpu=neon-fp-armv8 -fomit-frame-pointer -Wall -pipe -Os -flto -ffat-lto-objects -Isrc/basic/basic@sta -Isrc/basic -I../src/basic -I. -I../ -Isrc/libsystemd-network -I../src/libsystemd-network -I../src/libsystemd/sd-network -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-device -I../src/libsystemd/sd-bus -Isrc/core -I../src/core -Isrc/libudev -I../src/libudev -Isrc/udev -I../src/udev -Isrc/login -I../src/login -Isrc/timesync -I../src/timesync -Isrc/resolve -I../src/resolve -Isrc/journal -I../src/journal -Isrc/systemd -I../src/systemd -Isrc/shared -I../src/shared -I/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Hub.arm-9.0-devel-next/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include -I/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Hub.arm-9.0-devel-next/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/blkid -I/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Hub.arm-9.0-devel-next/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/uuid -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=gnu99 -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Wdate-time -Wnested-externs -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -fPIE -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Werror=shadow -ffunction-sections -fdata-sections -include config.h -fPIC -pthread -fvisibility=default -MMD -MQ 'src/basic/basic@sta/calendarspec.c.o' -MF 'src/basic/basic@sta/calendarspec.c.o.d' -o 'src/basic/basic@sta/calendarspec.c.o' -c ../src/basic/calendarspec.c
In file included from ../src/basic/missing.h:1358:0,
                 from ../src/basic/util.h:47,
                 from ../src/basic/calendarspec.h:29,
                 from ../src/basic/calendarspec.c:34:
../src/basic/missing_syscall.h:65:19: error: static declaration of 'memfd_create' follows non-static declaration
 static inline int memfd_create(const char *name, unsigned int flags) {
                   ^~~~~~~~~~~~
In file included from /home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Hub.arm-9.0-devel-next/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/bits/mman-linux.h:115:0,
                 from /home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Hub.arm-9.0-devel-next/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/bits/mman.h:40,
                 from /home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Hub.arm-9.0-devel-next/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/sys/mman.h:41,
                 from ../src/basic/calendarspec.c:30:
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Hub.arm-9.0-devel-next/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/bits/mman-shared.h:46:5: note: previous declaration of 'memfd_create' was here
 int memfd_create (const char *__name, unsigned int __flags) __THROW;
     ^~~~~~~~~~~~
[68/985] Compiling C object 'src/basic/basic@sta/cap-list.c.o'.
[69/985] Compiling C object 'src/basic/basic@sta/capability-util.c.o'.
[70/985] Compiling C object 'src/basic/basic@sta/clock-util.c.o'.
[71/985] Compiling C object 'src/basic/basic@sta/exit-status.c.o'.
[72/985] Compiling C object 'src/basic/basic@sta/ether-addr-util.c.o'.
[73/985] Compiling C object 'src/basic/basic@sta/copy.c.o'.
[74/985] Compiling C object 'src/basic/basic@sta/btrfs-util.c.o'.
[75/985] Compiling C object 'src/basic/basic@sta/extract-word.c.o'.
[76/985] Compiling C object 'src/basic/basic@sta/cgroup-util.c.o'.
../src/basic/cgroup-util.c: In function 'cg_pid_get_path':
../src/basic/cgroup-util.c:1066:48: warning: 'controller_str' may be used uninitialized in this function [-Wmaybe-uninitialized]
                                 if (k == cs && memcmp(word, controller_str, cs) == 0) {
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

The `HAVE_MEMFD_CREATE` detection in `meson.build` is failing to determine that `memfd_create` is now implemented by glibc-2.27, however it appears to fail only when the kernel does not also implement this syscall. If the kernel does implement `memfd_create`, ie. 4.14.16, then the meson detection works as expected and the build succeeds.

system-237 sets the following `#define`s when building with glibc-2.27 and the stated kernels:

kernel 3.10.108:
```
config.h:#define HAVE_LINUX_MEMFD_H 0
config.h:#define HAVE_MEMFD_CREATE 0
```

kernel 3.14.29:
```
config.h:#define HAVE_LINUX_MEMFD_H 0
config.h:#define HAVE_MEMFD_CREATE 0
```

kernel 4.14.16:
```
config.h:#define HAVE_LINUX_MEMFD_H 1
config.h:#define HAVE_MEMFD_CREATE 1
```

Consequently systemd-237 fails to build with glibc-2.27 and kernels 3.10.108 and 3.14.29 (see build error, above), but builds successfully with 4.14.16.

Since LibreELEC will only be building with `glibc-2.27` (which implements `memfd_create`) as a workaround I'm using [this patch](https://github.com/MilhouseVH/LibreELEC.tv/blob/4579822797b1575fd064d87bcf33131511f9e471/packages/sysutils/systemd/patches/systemd-0100-fix-glibc-2.27-build.patch) to force enable `HAVE_MEMFD_CREATE` in `meson.build` and I'm able to  successfully build systemd-237 with all kernels.

The patch confirms that systemd-237 is building with the glibc-2.27 implementation of `memfd_create` because if we use the patch and build systemd-237 with glibc-2.26 (and not glibc-2.27) then systemd will fail to build as `memfd_create` is no longer declared. For example:
```
FAILED: src/basic/basic@sta/fileio.c.o
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Hub.arm-9.0-devel-next/toolchain/bin/armv8a-libreelec-linux-gnueabi-gcc -march=armv8-a+crc -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=cortex-a53 -mfloat-abi=hard -mfpu=neon-fp-armv8 -fomit-frame-pointer -Wall -pipe -Os -flto -ffat-lto-objects -Isrc/basic/basic@sta -Isrc/basic -I../src/basic -I. -I../ -Isrc/libsystemd-network -I../src/libsystemd-network -I../src/libsystemd/sd-network -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-device -I../src/libsystemd/sd-bus -Isrc/core -I../src/core -Isrc/libudev -I../src/libudev -Isrc/udev -I../src/udev -Isrc/login -I../src/login -Isrc/timesync -I../src/timesync -Isrc/resolve -I../src/resolve -Isrc/journal -I../src/journal -Isrc/systemd -I../src/systemd -Isrc/shared -I../src/shared -I/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Hub.arm-9.0-devel-next/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include -I/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Hub.arm-9.0-devel-next/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/blkid -I/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-WeTek_Hub.arm-9.0-devel-next/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/uuid -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=gnu99 -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Wdate-time -Wnested-externs -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -fPIE -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Werror=shadow -ffunction-sections -fdata-sections -include config.h -fPIC -pthread -fvisibility=default -MMD -MQ 'src/basic/basic@sta/fileio.c.o' -MF 'src/basic/basic@sta/fileio.c.o.d' -o 'src/basic/basic@sta/fileio.c.o' -c ../src/basic/fileio.c
../src/basic/fileio.c: In function 'open_serialization_fd':
../src/basic/fileio.c:1460:14: error: implicit declaration of function 'memfd_create'; did you mean 'timer_create'? [-Werror=implicit-function-declaration]
         fd = memfd_create(ident, MFD_CLOEXEC);
              ^~~~~~~~~~~~
              timer_create
../src/basic/fileio.c:1460:14: warning: nested extern declaration of 'memfd_create' [-Wnested-externs]
cc1: some warnings being treated as errors
```

However this patch, while it works, is not ideal as we'd rather not patch against upstream. And it's just a hack.

Does anyone have any idea why `HAVE_MEMFD_CREATE` is not being determined correctly by `meson.build` when the kernel does not implement `memfd_create` but `glibc` does?

### PR DESCRIPTION
**Pull request by keszybz**
In meson.build we check that functions are available using:
    meson.get_compiler('c').has_function('foo')
which checks the following:
if __stub_foo or __stub___foo are defined, return false
if foo is declared (a pointer to the function can be taken), return true
otherwise check for __builtin_memfd_create

_stub is documented by glibc as
   It defines a symbol '__stub_FUNCTION' for each function
   in the C library which is a stub, meaning it will fail
   every time called, usually setting errno to ENOSYS.

So if __stub is defined, we know we don't want to use the glibc version, but
this doesn't tell us if the name itself is defined or not. If it _is_ defined,
and we define our replacement as an inline static function, we get an error:
```
In file included from ../src/basic/missing.h:1358:0,
                 from ../src/basic/util.h:47,
                 from ../src/basic/calendarspec.h:29,
                 from ../src/basic/calendarspec.c:34:
../src/basic/missing_syscall.h:65:19: error: static declaration of 'memfd_create' follows non-static declaration
 static inline int memfd_create(const char *name, unsigned int flags) {
                   ^~~~~~~~~~~~
.../usr/include/bits/mman-shared.h:46:5: note: previous declaration of 'memfd_create' was here
 int memfd_create (const char *__name, unsigned int __flags) __THROW;
     ^~~~~~~~~~~~
```
To avoid this problem, call our inline functions different than glibc,
and use a #define to map the official name to our replacement.

Fixes #8099.

@MilhouseVH I'd appreciate if you tested that this actually fixes your issue.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Many thanks - my build system is tied up for the next few hours but I'll kick off clean 3.10.y, 3.14.y and 4.14.y builds to test this and let you know how it goes - should have results later tonight/tomorrow (I'm in the UK).

File: src/basic/missing_syscall.h [hunk 1]
```diff
@@ -26,9 +26,11 @@
 #include <sys/types.h>
 
 #if !HAVE_PIVOT_ROOT
-static inline int pivot_root(const char *new_root, const char *put_old) {
+static inline int _pivot_root(const char *new_root, const char *put_old) {
```
Comment (poettering) [inline src/basic/missing_syscall.h]: hmm, I think we should stay away from the "_" prefix if it's easy to, and this is an excercise in namespace hygiene after all. To quote GNU:

> In addition to the names documented in this manual, reserved names include all external identifiers (global functions and variables) that begin with an underscore (‘_’) and all identifiers regardless of use that begin with either two underscores or an underscore followed by a capital letter are reserved names. This is so that the library and header files can define functions, variables, and macros for internal purposes without risk of conflict with names in user programs.

hence, why not pick any other prefix, maybe `private_`, `missing_`, `xxx_` or `local_` or so?

**Comment by keszybz** [comment]
I like "missing_" because it matches the name of the file. Updated.

**Comment by poettering** [comment]
looks good, but I figure this should be rebased on top of git, and updated for statx?

**Comment by poettering** [comment]
hmm, I figure we should add an explanation for this to missing-syscall.h, so that people adding stuff there will see it

**Comment by MilhouseVH** [comment]
Sorry for the delay, I've been running build tests which take a while in order to be thorough.

I've been using the original version of this PR (http://ix.io/Nqp) on top of systemd-237, as the current version no longer applies on systemd-237.

| Linux | A | B | C |
|----|:----:|----|----|
|3.10.y | FAIL | SUCCESS | SUCCESS |
|3.14.y | FAIL | SUCCESS | SUCCESS |
|4.14.y | SUCCESS | SUCCESS | SUCCESS |

A) systemd-237 + glibc-2.27
B) systemd-237 + PR8229 + glibc-2.27
C) systemd-237 + PR8229 + glibc-2.26

The two failures with 3.10.y and 3.14.y were expected.

With this PR I don't see any change in `config.h` - the 3.10.y/3.14.y kernels both have:
```
#define HAVE_LINUX_MEMFD_H 0
#define HAVE_MEMFD_CREATE 0
```
Is this expected? I assume it is, as the builds are successful. This is the meson-log.txt from the 3.10.108 build: http://ix.io/Nsq

So with this PR, systemd-237 now builds successfully with 3.10.y/3.14.y/4.14.y kernels, with or without glibc-2.27. Many thanks!
