### PR TITLE
core/device: use LIST_FOREACH_AFTER() or friend

### LINKED ISSUE #10681: UBSan seems to be complaining about "member access within null pointer of type 'struct Device'"
In https://github.com/systemd/systemd/pull/10678 I started to build `systemd` with `ASan` and `UBsan` and, more importantly, run the unit tests under them. Here's another issue uncovered there:
```
emergency.target: Failed to load configuration: No such file or directory
emergency.service: Failed to load configuration: No such file or directory
../src/core/device.c:737:16: runtime error: member access within null pointer of type 'struct Device'
    #0 0x560581a8e63f in device_following ../src/core/device.c:737
    #1 0x5605819e1753 in unit_following ../src/core/unit.c:3817
    #2 0x5605819b4a3c in unit_dump ../src/core/unit.c:1186
    #3 0x560581966a93 in manager_dump_units ../src/core/manager.c:2069
    #4 0x560581946b13 in main ../src/test/test-engine.c:40
    #5 0x7f40fedaf412 in __libc_start_main (/build/build/../../lib64/libc.so.6+0x24412)
    #6 0x560581945e0d in _start (/build/build/test-engine+0x484e0d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/core/device.c:737:16 in 
-------
```
The full log can be found at https://api.travis-ci.org/v3/job/452166133/log.txt

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

File: src/core/swap.c [hunk 1]
```diff
@@ -1237,7 +1237,7 @@ static Unit *swap_following(Unit *u) {
         }
 
         /* Fall back to the first on the list */
-        return UNIT(first);
+        return first ? UNIT(first) : NULL;
```
Comment (keszybz) [inline src/core/swap.c]: Let's fix `UNIT` definition instead and avoid the member access if the argument is NULL.

**Comment by poettering** [comment]
ah, eh, just this instant I pushed #10686 which does exactly what @keszybz asked for in an alternative patch...

@yuwata any chance you can drop that part of this PR, and then we merge #10686 and that part?

**Comment by yuwata** [comment]
The first commit was dropped.
