### PR TITLE
udevadm-trigger: extend receive buffer size

### LINKED ISSUE #29863: Possible race condition(?) when calling `udevadm trigger --settle`
Thanks to a regression introduced in https://github.com/systemd/systemd/pull/29847 CI started hitting a strange race condition where `udevadm trigger --settle` sometimes gets stuck indefinitely even when the uevent queue is empty.

One of the regressions from https://github.com/systemd/systemd/pull/29847 was that we always set the log level to 0, which makes the race condition more likely (for whatever reason):

```
# udevadm control -l 0; while SYSTEMD_LOG_LEVEL=debug timeout -v 10 udevadm trigger -w; do :; done
...
blkcg_punt_bio: Triggered device with action 'change'.
scsi_tmf_0: Triggered device with action 'change'.
scsi_tmf_1: Triggered device with action 'change'.
scsi_tmf_2: Triggered device with action 'change'.
scsi_tmf_3: Triggered device with action 'change'.
scsi_tmf_4: Triggered device with action 'change'.
scsi_tmf_5: Triggered device with action 'change'.
writeback: Triggered device with action 'change'.
sd-device-monitor(n/a): Failed to get the received message size: No buffer space available
timeout: sending signal TERM to command ‘udevadm’
```

I had little luck reproducing this locally, but a beefy CI machine (with 72 cores) can hit this on the first or second iteration.

/cc @yuwata

### PR DESCRIPTION
**Pull request by yuwata**
We may trigger huge number of devices and will receive many events. Let's extend the buffer size, otherwise the buffer may be filled.

Fixes #29863.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @mrc0mmand

File: src/udev/udevadm-trigger.c [hunk 1]
```diff
@@ -526,6 +526,8 @@ int trigger_main(int argc, char *argv[], void *userdata) {
                 if (r < 0)
                         return log_error_errno(r, "Failed to create device monitor object: %m");
 
+                (void) sd_device_monitor_set_receive_buffer_size(m, 128*1024*1024);
```
Comment (poettering) [inline src/udev/udevadm-trigger.c]: we actually set this in most of our code now. Should we maybe just set this internally in sd-device, so that the problem goes away?

i mean, socket memory is these days accounted to the process that owns a socket, hence we shouldn't be too concerned that this might waste memory.

**Comment by mrc0mmand** [comment]
Thanks! Could you also add a test case for this? Something like:

```diff
diff --git a/test/units/testsuite-17.10.sh b/test/units/testsuite-17.10.sh
index b4724653f3..f9708319b0 100755
--- a/test/units/testsuite-17.10.sh
+++ b/test/units/testsuite-17.10.sh
@@ -219,6 +219,15 @@ udevadm settle -t 300
 udevadm trigger --wait-daemon=5
 udevadm trigger -h
 
+# https://github.com/systemd/systemd/issues/29863
+if [[ "$(systemd-detect-virt -v)" != "qemu" ]]; then
+    udevadm control --log-level=0
+    for _ in {0..9}; do
+        timeout 30 udevadm trigger --settle
+    done
+    udevadm control --log-level=debug
+fi
+
 udevadm wait /dev/null
 udevadm wait /sys/class/net/$netdev
 udevadm wait -t 5 /sys/class/net/$netdev
```

should suffice.

**Comment by yuwata** [comment]
@poettering @mrc0mmand Thank you for the comments. Applied both suggestions. PTAL.

**Review by mrc0mmand — APPROVED** [review]
LGTM, thank you!
