### PR TITLE
calendarspec: day of month also needs to be reset when year is changed

### LINKED ISSUE #40260: Timer with repetition value doesn't trigger on the 1st of January
### systemd version the issue has been seen with

258.3-2.fc43

### Used distribution

Fedora 43

### Linux kernel version used

6.17.12-300.fc43.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-analyze

### Expected behaviour you didn't see

> Values may be suffixed with "/" and a repetition value, which indicates that the **value itself** and the value plus all multiples of the repetition value are matched.

 ` '*-*-1/11 23:00:00'`

I expected this calendar event to trigger on `2026-01-01 23:00` but it didn't. 

### Unexpected behaviour you saw

Timer didn't fire.  Confirmed with `systemd-analyze calendar` that the 1st of January is missing from iterations with some repetition values for other years as well, not just 2026. 

### Steps to reproduce the problem

```
systemd-analyze calendar --iterations=10  '*-*-1/11 23:00:00' --base-time='2025-11-01' | grep "Iteration"
   Iteration #2: Wed 2025-11-12 23:00:00 CET
   Iteration #3: Sun 2025-11-23 23:00:00 CET
   Iteration #4: Mon 2025-12-01 23:00:00 CET
   Iteration #5: Fri 2025-12-12 23:00:00 CET
   Iteration #6: Tue 2025-12-23 23:00:00 CET
 [[note the missing iteration here]]
   Iteration #7: Mon 2026-01-12 23:00:00 CET
   Iteration #8: Fri 2026-01-23 23:00:00 CET
   Iteration #9: Sun 2026-02-01 23:00:00 CET
  Iteration #10: Thu 2026-02-12 23:00:00 CET
```

2026-01-01 does show up for some repetition values, 1-3 works I think 4 is the lowest repetition that skips the January 1st.  

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #40260.

### CODE REVIEW

File: src/shared/calendarspec.c [hunk 1]
```diff
@@ -1194,9 +1194,10 @@ static int tm_within_bounds(struct tm *tm, bool utc) {
          * other sub time units are already reset in find_next().
          */
         int cmp;
-        if ((cmp = CMP(t.tm_year, tm->tm_year)) != 0)
+        if ((cmp = CMP(t.tm_year, tm->tm_year)) != 0) {
                 t.tm_mon = 0;
-        else if ((cmp = CMP(t.tm_mon, tm->tm_mon)) != 0)
+                t.tm_mday = 1;
```
Comment (YHNdnzj) [inline src/shared/calendarspec.c:1199]: hmm, I wonder if the initial mktime_or_timegm_usec in find_next() should be switched to tm_within_bound instead?

Comment (poettering) [reply src/shared/calendarspec.c:1199]: hmm, but the initial invocation of mktime_or_timegm_usec() should actually do normalization, hence seems wrong to replace it with tm_within_bound()?

Comment (yuwata) [reply src/shared/calendarspec.c:1199]: Yeah, the initial one is for normalization.
