### PR TITLE
udev/path_id: fix skip_subsystem()

### LINKED ISSUE #21617: disk by-path question/suggestion for usb storage devices
Hi, 

I was developing an application and noticed the following issue:

When a usb storage device is plugged in running ```udevadm info /dev/sdm``` generates following output:
```
P: /devices/pci0000:00/0000:00:1c.6/0000:14:00.0/usb6/6-1/6-1:1.0/host15/target15:0:0/15:0:0:0/block/sdm
N: sdm
L: 0
S: disk/by-path/pci-0000:14:00.0-usb-0:1:1.0-scsi-0:0:0:0
S: disk/by-id/usb-WD_Elements_25A3_564348564239414E-0:0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.6/0000:14:00.0/usb6/6-1/6-1:1.0/host15/target15:0:0/15:0:0:0/block/sdm
E: DEVNAME=/dev/sdm
E: DEVTYPE=disk
E: MAJOR=8
E: MINOR=192
E: SUBSYSTEM=block
E: USEC_INITIALIZED=33762001
E: ID_VENDOR=WD
E: ID_VENDOR_ENC=WD\x20\x20\x20\x20\x20\x20
E: ID_VENDOR_ID=1058
E: ID_MODEL=Elements_25A3
E: ID_MODEL_ENC=Elements\x2025A3\x20\x20\x20
E: ID_MODEL_ID=25a3
E: ID_REVISION=1031
E: ID_SERIAL=WD_Elements_25A3_XXXXXXXXXX-0:0
E: ID_SERIAL_SHORT=XXXXXXXXXX
E: ID_TYPE=disk
E: ID_INSTANCE=0:0
E: ID_BUS=usb
E: ID_USB_INTERFACES=:080650:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usb-storage
E: ID_PATH=pci-0000:14:00.0-usb-0:1:1.0-scsi-0:0:0:0
E: ID_PATH_TAG=pci-0000_14_00_0-usb-0_1_1_0-scsi-0_0_0_0
E: ID_PART_TABLE_UUID=bca046c6-1b56-4fa7-a04c-196631b4a867
E: ID_PART_TABLE_TYPE=gpt
E: DEVLINKS=/dev/disk/by-path/pci-0000:14:00.0-usb-0:1:1.0-scsi-0:0:0:0 /dev/disk/by-id/usb-WD_Elements_25A3_XXXXXXXXXX-0:0
E: TAGS=:systemd:
```
In ```DEVLINKS```, generated by-path value is ```/dev/disk/by-path/pci-0000:14:00.0-usb-0:1:1.0-scsi-0:0:0:0```. I checked the source code and in file ```systemd/src/udev/udev-builtin-path_id.c``` at line: ```496``` and saw that usb part has a fixed value of ```0```. 

```path_prepend(path, "usb-0:%s", port);```

Is there any particular reason why ```usb-0``` is a fixed value, but not bus id? Why its not ```usb-6``` or ```usb6``` according the output above. E.g ```/dev/disk/by-path/pci-0000:14:00.0-usb-6-1:1.0-scsi-0:0:0:0```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #21617.

### CODE REVIEW

File: src/udev/udev-builtin-path_id.c [hunk 1]
```diff
@@ -494,9 +494,10 @@ static sd_device *handle_usb(sd_device *parent, char **path) {
         port = strchr(str, '-');
         if (!port)
                 return parent;
+        bus = strndupa_safe(str, port - str);
```
Comment (bluca) [inline src/udev/udev-builtin-path_id.c]: I know we have the ALLOCA_MAX stuff now so even though this depends on external input it should be safe, but given it's a format string, maybe you can avoid that at all with something like `"usb-%.*s:%s", str, port - str, port`?

**Comment by yuwata** [comment]
@bluca Thank you for the suggestion. Applied. PTAL.

**Review by bluca — APPROVED** [review]

File: src/udev/udev-builtin-path_id.c [hunk 2]
```diff
@@ -488,12 +498,12 @@ static sd_device *handle_usb(sd_device *parent, char **path) {
...
-        port = strchr(str, '-');
-        if (!port)
+
+        hyphen = strchr(str, '-');
+        if (!hyphen)
                 return parent;
-        port++;
 
-        path_prepend(path, "usb-0:%s", port);
+        path_prepend(path, "usb-%.*s:%s", (int)(hyphen - str), str, hyphen + 1);
```
Comment (arvidjaar) [inline src/udev/udev-builtin-path_id.c]: This defeats the very purpose of stable device path. USB host number may change across reboots (and probably even without reboot). The part after USB host number is determined by device topology and so does not change.

The actual USB host number here is irrelevant, because we build stable path to the parent which uniquely identifies USB host. In hindsight it had been better to not include it at all.

What exact problem this change solves?

Comment (yuwata) [reply src/udev/udev-builtin-path_id.c]: Thank you for the explanation. I completely misunderstand the motivation of using '0' here. I added a comment about that based on your comment.

**Comment by yuwata** [comment]
I added this to v250 milestone, as the first commit fixes a regression.

File: src/udev/udev-builtin-path_id.c [hunk 3]
```diff
@@ -80,19 +80,29 @@ static int format_lun_number(sd_device *dev, char **path) {
...
         assert(dev);
         assert(subsys);
 
-        for (;;) {
+        /* Unlike the function name, this drops multiple parent devices EXCEPT FOR THE LAST ONE.
+         * The last one will be dropped at the end of the loop in builtin_path_id().
+         * E.g.
+         * Input:  /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0
+         * Output: /sys/devices/pci0000:00/0000:00:14.0/usb1
+         */
```
Comment (keszybz) [inline src/udev/udev-builtin-path_id.c:93]: Eh, one day we'll add some unit tests for this.

**Review by keszybz — APPROVED** [review]
```console
$ git diff d340bdd~ src/udev/udev-builtin-path_id.c
diff --git src/udev/udev-builtin-path_id.c src/udev/udev-builtin-path_id.c
index effc36f36a..6fdd3eceea 100644
--- src/udev/udev-builtin-path_id.c
+++ src/udev/udev-builtin-path_id.c
@@ -85,6 +85,13 @@ static sd_device *skip_subsystem(sd_device *dev, const char *subsys) {
         assert(dev);
         assert(subsys);
 
+        /* Unlike the function name, this drops multiple parent devices EXCEPT FOR THE LAST ONE.
+         * The last one will be dropped at the end of the loop in builtin_path_id().
+         * E.g.
+         * Input:  /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0
+         * Output: /sys/devices/pci0000:00/0000:00:14.0/usb1
+         */
+
         for (parent = dev; ; ) {
                 const char *subsystem;
 
@@ -340,7 +347,7 @@ static sd_device *handle_scsi_default(sd_device *parent, char **path) {
         if (!pos)
                 return NULL;
 
-        base = strndupa(base, pos - base);
+        base = strndupa_safe(base, pos - base);
         dir = opendir(base);
         if (!dir)
                 return NULL;
@@ -496,6 +503,10 @@ static sd_device *handle_usb(sd_device *parent, char **path) {
                 return parent;
         port++;
 
+        /* USB host number may change across reboots (and probably even without reboot). The part after
+         * USB host number is determined by device topology and so does not change. Hence, drop the
+         * host number and always use '0' instead. */
+
         path_prepend(path, "usb-0:%s", port);
         return skip_subsystem(parent, "usb");
 }
@@ -533,7 +544,7 @@ static sd_device *handle_ap(sd_device *parent, char **path) {
         return skip_subsystem(parent, "ap");
 }
 
-static int builtin_path_id(sd_device *dev, int argc, char *argv[], bool test) {
+static int builtin_path_id(sd_device *dev, sd_netlink **rtnl, int argc, char *argv[], bool test) {
         sd_device *parent;
         _cleanup_free_ char *path = NULL;
         _cleanup_free_ char *compat_path = NULL;
```
Apart from comment changes and other irrelevant stuff, the only thing is the strndupa refactoring. So this effectively a revert to pre-d340bdd. d340bdd was supposed to be just a cleanup, so it seems fine to revert if it causes a behavioural change.

**Comment by keszybz** [comment]
mkosi / ci (arch): Failed to dissect image '/home/runner/work/systemd/systemd/image.raw': Connection timed out
