### PR TITLE
network,udev: several fixlets for setting up SR-IOV VFs

### LINKED ISSUE #37257: Failed to set up SR-IOV vf with systemd 257.5 on Debian 13
### systemd version the issue has been seen with

257.5 (Debian package version 257.5-2)

### Used distribution

Debian Trixie (13)

### Linux kernel version used

6.12.22-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

An SR-IOV virtual function is configured on the network device

### Unexpected behaviour you saw

SR-IOV VF configuration fails - no virtual functions are created, network device is put into 'failed' state in systemd-networkd

### Steps to reproduce the problem

Dell Optiplex 7040, with Intel i350 dual port card installed.

`10-enp3s0f0.network`

```
[Match]
Name=enp3s0f0

[Link]
RequiredForOnline=no

[Network]
DHCP=true

[SR-IOV]
VirtualFunction=0
```

The card is capable of SR-IOV operation, and can be configured manually like this:this:

```
# cat /sys/devices/pci0000\:00/0000\:00\:1d.0/0000\:03\:00.0/sriov_numvfs 
0
# ip link show enp3s0f0
2: enp3s0f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether b4:96:91:3e:61:34 brd ff:ff:ff:ff:ff:ff
    altname enxb496913e6134
# echo 1 > /sys/devices/pci0000\:00/0000\:00\:1d.0/0000\:03\:00.0/sriov_numvfs
# cat /sys/devices/pci0000\:00/0000\:00\:1d.0/0000\:03\:00.0/sriov_numvfs 
1
# ip link show enp3s0f0
2: enp3s0f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether b4:96:91:3e:61:34 brd ff:ff:ff:ff:ff:ff
    vf 0     link/ether 9a:26:89:fc:6b:fb brd ff:ff:ff:ff:ff:ff, spoof checking on, link-state auto, trust off
    altname enxb496913e6134

```

# cat /sys/devices/pci0000\:00/0000\:00\:1d.0/0000\:03\:00.0/sriov_numvfs
0
`echo 1 > /sys/devices/pci0000\:00/0000\:00\:1d.0/0000\:03\:00.0/sriov_numvfs`

... `ip link show enp3s0f0` give the following outpu:
```
2: enp3s0f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether b4:96:91:3e:61:34 brd ff:ff:ff:ff:ff:ff
    vf 0     link/ether 9a:26:89:fc:6b:fb brd ff:ff:ff:ff:ff:ff, spoof checking on, link-state auto, trust off
    altname enxb496913e6134
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Apr 26 13:09:29 systemd[1]: Starting systemd-udevd.service - Rule-based Manager for Device Events and Files...
Apr 26 13:09:29 systemd-udevd[375]: Using default interface naming scheme 'v257'.
Apr 26 13:09:29 systemd[1]: Started systemd-udevd.service - Rule-based Manager for Device Events and Files.
Apr 26 13:09:29 systemd[1]: Starting systemd-networkd.service - Network Configuration...
Apr 26 13:09:29 lvm[438]: PV /dev/nvme0n1p4 online, VG coldean is complete.
Apr 26 13:09:29 lvm[438]: VG coldean finished
Apr 26 13:09:29 systemd-networkd[397]: Bus bus-api-network: changing state UNSET → OPENING
Apr 26 13:09:29 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:29 systemd-networkd[397]: Added inotify watch for /run on bus bus-api-network: 2
Apr 26 13:09:29 systemd-networkd[397]: Added inotify watch for /run/dbus on bus bus-api-network: -1
Apr 26 13:09:29 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:29 systemd-networkd[397]: Bus bus-api-network: changing state OPENING → WATCH_BIND
Apr 26 13:09:29 systemd-networkd[397]: Registering bus object implementation for path=/org/freedesktop/network1 iface=org.freedesktop.network1.Manager
Apr 26 13:09:29 systemd-networkd[397]: Registering bus object implementation for path=/org/freedesktop/network1/link iface=org.freedesktop.network1.Link
Apr 26 13:09:29 systemd-networkd[397]: Registering bus object implementation for path=/org/freedesktop/network1/link iface=org.freedesktop.network1.DHCPServer
Apr 26 13:09:29 systemd-networkd[397]: Registering bus object implementation for path=/org/freedesktop/network1/link iface=org.freedesktop.network1.DHCPv4Client
Apr 26 13:09:29 systemd-networkd[397]: Registering bus object implementation for path=/org/freedesktop/network1/link iface=org.freedesktop.network1.DHCPv6Client
Apr 26 13:09:29 systemd-networkd[397]: Registering bus object implementation for path=/org/freedesktop/network1/network iface=org.freedesktop.network1.Network
Apr 26 13:09:29 systemd-networkd[397]: Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
Apr 26 13:09:29 systemd-networkd[397]: sd-device-monitor(n/a): Failed to stat PID1's netns, ignoring: No such file or directory
Apr 26 13:09:29 systemd-networkd[397]: Loading...
Apr 26 13:09:29 systemd-networkd[397]: /etc/systemd/network/10-enp3s0f0.network: Successfully loaded.
Apr 26 13:09:29 systemd-networkd[397]: /usr/lib/systemd/network/80-6rd-tunnel.network: Successfully loaded.
Apr 26 13:09:29 systemd-networkd[397]: No virtualization found in DMI vendor table.
Apr 26 13:09:29 systemd-networkd[397]: Unable to read /sys/firmware/dmi/entries/0-0/raw, using the virtualization information found in DMI vendor table, ignoring: Permission denied
Apr 26 13:09:29 systemd-networkd[397]: UML virtualization not found in /proc/cpuinfo.
Apr 26 13:09:29 systemd-networkd[397]: Virtualization XEN not found, /proc/xen does not exist
Apr 26 13:09:29 systemd-networkd[397]: No virtualization found in CPUID
Apr 26 13:09:29 systemd-networkd[397]: This platform does not support /proc/device-tree
Apr 26 13:09:29 systemd-networkd[397]: This platform does not support /proc/sysinfo
Apr 26 13:09:29 systemd-networkd[397]: Found VM virtualization none
Apr 26 13:09:29 systemd-networkd[397]: /usr/lib/systemd/network/80-container-host0-tun.network: Conditions in the file do not match the system environment, skipping.
Apr 26 13:09:29 systemd-networkd[397]: /usr/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
Apr 26 13:09:29 systemd-networkd[397]: /usr/lib/systemd/network/80-container-vb.network: Successfully loaded.
Apr 26 13:09:29 systemd-networkd[397]: /usr/lib/systemd/network/80-container-ve.network: Successfully loaded.
Apr 26 13:09:29 systemd-networkd[397]: /usr/lib/systemd/network/80-container-vz.network: Successfully loaded.
Apr 26 13:09:29 systemd-networkd[397]: /usr/lib/systemd/network/80-namespace-ns.network: Successfully loaded.
Apr 26 13:09:29 systemd-networkd[397]: /usr/lib/systemd/network/80-vm-vt.network: Successfully loaded.
Apr 26 13:09:29 systemd-networkd[397]: /usr/lib/systemd/network/80-wifi-adhoc.network: Successfully loaded.
Apr 26 13:09:29 systemd-networkd[397]: Loaded.
Apr 26 13:09:29 systemd-networkd[397]: Enumerating...
Apr 26 13:09:29 systemd-networkd[397]: lo: Saved new link: ifindex=1, iftype=LOOPBACK(772), kind=n/a
Apr 26 13:09:29 systemd-networkd[397]: lo: Saved original MTU 65536 (min: 0, max: 4294967295)
Apr 26 13:09:29 systemd-networkd[397]: lo: Saved hardware address: 00:00:00:00:00:00
Apr 26 13:09:29 systemd-networkd[397]: lo: Saved IPv6 link-local address generation mode: eui64
Apr 26 13:09:29 systemd-networkd[397]: lo: Flags change: +LOOPBACK +UP +LOWER_UP +RUNNING
Apr 26 13:09:29 systemd-networkd[397]: lo: Link UP
Apr 26 13:09:29 systemd-networkd[397]: lo: Gained carrier
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Saved new link: ifindex=2, iftype=ETHER(1), kind=n/a
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Saved original MTU 1500 (min: 68, max: 9216)
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Saved permanent hardware address: b4:96:91:3e:61:34
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Saved hardware address: b4:96:91:3e:61:34
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Saved IPv6 link-local address generation mode: eui64
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Flags change: +MULTICAST +BROADCAST
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: Saved new link: ifindex=3, iftype=ETHER(1), kind=n/a
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: Saved original MTU 1500 (min: 68, max: 9216)
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: Saved permanent hardware address: 00:0f:53:08:98:d8
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: Saved hardware address: 00:0f:53:08:98:d8
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: Saved IPv6 link-local address generation mode: eui64
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: Flags change: +MULTICAST +BROADCAST
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: Saved new link: ifindex=4, iftype=ETHER(1), kind=n/a
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: Saved original MTU 1500 (min: 68, max: 9216)
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: Saved permanent hardware address: b4:96:91:3e:61:35
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: Saved hardware address: b4:96:91:3e:61:35
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: Saved IPv6 link-local address generation mode: eui64
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: Flags change: +MULTICAST +BROADCAST
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: Saved new link: ifindex=5, iftype=ETHER(1), kind=n/a
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: Saved original MTU 1500 (min: 68, max: 9216)
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: Saved permanent hardware address: 00:0f:53:08:98:d9
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: Saved hardware address: 00:0f:53:08:98:d9
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: Saved IPv6 link-local address generation mode: eui64
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: Flags change: +MULTICAST +BROADCAST
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: Saved new link: ifindex=6, iftype=ETHER(1), kind=n/a
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: Saved original MTU 1500 (min: 68, max: 9000)
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: Saved permanent hardware address: 48:4d:7e:e5:b4:2b
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: Saved hardware address: 48:4d:7e:e5:b4:2b
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: Saved IPv6 link-local address generation mode: eui64
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: Flags change: +MULTICAST +BROADCAST
Apr 26 13:09:29 systemd-networkd[397]: lo: Remembering foreign QDisc (configured): handle=0:0, parent=ffff:ffff, kind=noqueue
Apr 26 13:09:29 systemd-networkd[397]: lo: Received new foreign address (configured): 127.0.0.1/8 (valid forever, preferred forever), flags: permanent, scope: host, label: n/a
Apr 26 13:09:29 systemd-networkd[397]: lo: link_check_ready(): link is in pending state.
Apr 26 13:09:29 systemd-networkd[397]: lo: Received new foreign address (configured): ::1/128 (valid forever, preferred forever), flags: permanent,no-prefixroute, scope: host
Apr 26 13:09:29 systemd-networkd[397]: lo: link_check_ready(): link is in pending state.
Apr 26 13:09:29 systemd-networkd[397]: lo: Received new foreign route (configured): dst: 127.0.0.0/8, src: n/a, gw: n/a, prefsrc: 127.0.0.1, table: local(255), priority: 0, proto: kernel, scope: host, type: local, flags: n/a
Apr 26 13:09:29 systemd-networkd[397]: lo: Received new foreign route (configured): dst: 127.0.0.1/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, table: local(255), priority: 0, proto: kernel, scope: host, type: local, flags: n/a
Apr 26 13:09:29 systemd-networkd[397]: lo: Received new foreign route (configured): dst: 127.255.255.255/32, src: n/a, gw: n/a, prefsrc: 127.0.0.1, table: local(255), priority: 0, proto: kernel, scope: link, type: broadcast, flags: n/a
Apr 26 13:09:29 systemd-networkd[397]: lo: Received new foreign route (configured): dst: ::1/128, src: n/a, gw: n/a, prefsrc: n/a, table: local(255), priority: 0, proto: kernel, scope: global, type: local, flags: n/a
Apr 26 13:09:29 systemd-networkd[397]: Remembering foreign routing policy rule (configured): priority: 0, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: local(255)
Apr 26 13:09:29 systemd-networkd[397]: Remembering foreign routing policy rule (configured): priority: 32766, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: main(254)
Apr 26 13:09:29 systemd-networkd[397]: Remembering foreign routing policy rule (configured): priority: 32767, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: default(253)
Apr 26 13:09:29 systemd-networkd[397]: rtnl: received rule message with invalid family 128, ignoring.
Apr 26 13:09:29 systemd-networkd[397]: rtnl: received rule message with invalid family 129, ignoring.
Apr 26 13:09:29 systemd-networkd[397]: Remembering foreign routing policy rule (configured): priority: 0, ::/0 -> ::/0, iif: n/a, oif: n/a, table: local(255)
Apr 26 13:09:29 systemd-networkd[397]: Remembering foreign routing policy rule (configured): priority: 32766, ::/0 -> ::/0, iif: n/a, oif: n/a, table: main(254)
Apr 26 13:09:29 systemd-networkd[397]: Enumeration completed.
Apr 26 13:09:29 systemd-networkd[397]: Starting...
Apr 26 13:09:29 systemd-networkd[397]: Loaded 'libbpf.so.1' via dlopen()
Apr 26 13:09:29 systemd-networkd[397]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Apr 26 13:09:29 systemd-networkd[397]: lo: udev initialized link
Apr 26 13:09:29 systemd-networkd[397]: sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/physfn".
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: udev initialized link
Apr 26 13:09:29 systemd-networkd[397]: sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/physfn".
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: udev initialized link
Apr 26 13:09:29 systemd-networkd[397]: sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:1d.0/0000:03:00.1/physfn".
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: udev initialized link
Apr 26 13:09:29 systemd-networkd[397]: sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:1d.0/0000:03:00.0/physfn".
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: udev initialized link
Apr 26 13:09:29 systemd-networkd[397]: sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:1f.6/physfn".
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: udev initialized link
Apr 26 13:09:29 systemd-networkd[397]: Started.
Apr 26 13:09:29 systemd-networkd[397]: memory105: sd-device-monitor(n/a): Received device does not pass filter, ignoring.
Apr 26 13:09:29 systemd-networkd[397]: lo: Failed to get driver, continuing without: Operation not supported
Apr 26 13:09:29 systemd[1]: Started systemd-networkd.service - Network Configuration.
Apr 26 13:09:29 systemd-networkd[397]: lo: Saved permanent hardware address: 00:00:00:00:00:00
Apr 26 13:09:29 systemd-networkd[397]: lo: Link state is up-to-date
Apr 26 13:09:29 systemd-networkd[397]: lo: State changed: pending -> initialized
Apr 26 13:09:29 systemd-networkd[397]: lo: No matching .network found.
Apr 26 13:09:29 systemd-networkd[397]: lo: Unmanaging interface.
Apr 26 13:09:29 systemd-networkd[397]: lo: State changed: initialized -> unmanaged
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: Found driver: sfc_siena
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: Link state is up-to-date
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: State changed: pending -> initialized
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: No matching .network found.
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: Unmanaging interface.
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f0np0: State changed: initialized -> unmanaged
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: Found driver: sfc_siena
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: Link state is up-to-date
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: State changed: pending -> initialized
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: No matching .network found.
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: Unmanaging interface.
Apr 26 13:09:29 systemd-networkd[397]: enp1s0f1np1: State changed: initialized -> unmanaged
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: Found driver: igb
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: Link state is up-to-date
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: State changed: pending -> initialized
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: No matching .network found.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: Unmanaging interface.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f1: State changed: initialized -> unmanaged
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Found driver: igb
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Link state is up-to-date
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: pending -> initialized
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Found matching .network file: /etc/systemd/network/10-enp3s0f0.network
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Configuring with /etc/systemd/network/10-enp3s0f0.network.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: initialized -> configuring
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Configuring SR-IOV
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/disable_ipv6' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/use_tempaddr' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/accept_ra' to '0'
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/proxy_ndp' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv4/conf/enp3s0f0/promote_secondaries' to '1'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '1', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested to activate link
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the DHCPv4 client.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the DHCPv6 client.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the IPv6 Router Discovery.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Setting SR-IOV virtual function 0.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Bringing link up
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: Found driver: e1000e
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: Link state is up-to-date
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: State changed: pending -> initialized
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: No matching .network found.
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: Unmanaging interface.
Apr 26 13:09:29 systemd-networkd[397]: enp0s31f6: State changed: initialized -> unmanaged
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Could not set up SR-IOV: Invalid argument
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Failed
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: configuring -> failed
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Trying to reconfigure the interface.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: failed -> initialized
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Flags change: +UP
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Link UP
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is in initialized state.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Found matching .network file: /etc/systemd/network/10-enp3s0f0.network
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Reconfiguring with /etc/systemd/network/10-enp3s0f0.network.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: initialized -> configuring
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Configuring SR-IOV
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/disable_ipv6' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/use_tempaddr' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/accept_ra' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/proxy_ndp' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv4/conf/enp3s0f0/promote_secondaries' to '1'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '1', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested to activate link
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the DHCPv4 client.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the DHCPv6 client.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the IPv6 Router Discovery.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Setting SR-IOV virtual function 0.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Bringing link up
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Could not set up SR-IOV: Invalid argument
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Failed
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: configuring -> failed
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Trying to reconfigure the interface.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: failed -> initialized
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is in initialized state.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Found matching .network file: /etc/systemd/network/10-enp3s0f0.network
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Reconfiguring with /etc/systemd/network/10-enp3s0f0.network.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: initialized -> configuring
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Configuring SR-IOV
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/disable_ipv6' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/use_tempaddr' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/accept_ra' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/proxy_ndp' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv4/conf/enp3s0f0/promote_secondaries' to '1'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '1', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested to activate link
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the DHCPv4 client.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the DHCPv6 client.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the IPv6 Router Discovery.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Setting SR-IOV virtual function 0.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Bringing link up
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Could not set up SR-IOV: Invalid argument
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Failed
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: configuring -> failed
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Trying to reconfigure the interface.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: failed -> initialized
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is in initialized state.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Found matching .network file: /etc/systemd/network/10-enp3s0f0.network
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Reconfiguring with /etc/systemd/network/10-enp3s0f0.network.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: initialized -> configuring
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Configuring SR-IOV
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/disable_ipv6' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/use_tempaddr' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/accept_ra' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/proxy_ndp' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv4/conf/enp3s0f0/promote_secondaries' to '1'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '1', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested to activate link
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the DHCPv4 client.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the DHCPv6 client.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the IPv6 Router Discovery.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Setting SR-IOV virtual function 0.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Bringing link up
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Could not set up SR-IOV: Invalid argument
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Failed
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: configuring -> failed
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Trying to reconfigure the interface.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: failed -> initialized
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is in initialized state.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Found matching .network file: /etc/systemd/network/10-enp3s0f0.network
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Reconfiguring with /etc/systemd/network/10-enp3s0f0.network.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: initialized -> configuring
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Configuring SR-IOV
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/disable_ipv6' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/use_tempaddr' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/accept_ra' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/proxy_ndp' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv4/conf/enp3s0f0/promote_secondaries' to '1'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '1', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested to activate link
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the DHCPv4 client.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the DHCPv6 client.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the IPv6 Router Discovery.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Setting SR-IOV virtual function 0.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Bringing link up
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Could not set up SR-IOV: Invalid argument
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Failed
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: configuring -> failed
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Trying to reconfigure the interface.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: failed -> initialized
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is in initialized state.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Found matching .network file: /etc/systemd/network/10-enp3s0f0.network
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Reconfiguring with /etc/systemd/network/10-enp3s0f0.network.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: initialized -> configuring
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Configuring SR-IOV
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/disable_ipv6' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/use_tempaddr' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/accept_ra' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv6/conf/enp3s0f0/proxy_ndp' to '0'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '0', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: Setting '/proc/sys/net/ipv4/conf/enp3s0f0/promote_secondaries' to '1'
Apr 26 13:09:29 systemd-networkd[397]: No change in value '1', suppressing write
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested to activate link
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the DHCPv4 client.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the DHCPv6 client.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Requested configuring of the IPv6 Router Discovery.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: link_check_ready(): link is not activated.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Setting SR-IOV virtual function 0.
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Bringing link up
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Could not set up SR-IOV: Invalid argument
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: Failed
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: State changed: configuring -> failed
Apr 26 13:09:29 systemd-networkd[397]: enp3s0f0: The interface entered the failed state frequently, refusing to reconfigure it automatically.
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network: New incoming connection.
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network: Connections of user 998: 0 (of 576 max)
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Setting state idle-server
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Received message: {"method":"io.systemd.Network.GetNamespaceId","parameters":{}}
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Changing state idle-server → processing-method
Apr 26 13:09:29 systemd-networkd[397]: Failed to query network nsid, ignoring: No data available
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Sending message: {"parameters":{"NamespaceId":4026531840,"NamespaceNSID":null}}
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Changing state processing-method → processed-method
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Changing state processed-method → idle-server
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Received message: {"method":"io.systemd.Network.SetPersistentStorage","parameters":{"Ready":true}}
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Changing state idle-server → processing-method
Apr 26 13:09:29 systemd-networkd[397]: Trying to acquire polkit authentication for 'org.freedesktop.network1.set-persistent-storage'.
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Sending message: {"parameters":{}}
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Changing state processing-method → processed-method
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Changing state processed-method → idle-server
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Changing state idle-server → pending-disconnect
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Changing state pending-disconnect → processing-disconnect
Apr 26 13:09:29 systemd-networkd[397]: varlink-api-network-27-27: Changing state processing-disconnect → disconnected
Apr 26 13:09:30 systemd-networkd[397]: Got inotify event on bus bus-api-network.
Apr 26 13:09:30 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:30 systemd-networkd[397]: Added inotify watch for /run on bus bus-api-network: 2
Apr 26 13:09:30 systemd-networkd[397]: Added inotify watch for /run/dbus on bus bus-api-network: -1
Apr 26 13:09:30 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:30 systemd-networkd[397]: Got inotify event on bus bus-api-network.
Apr 26 13:09:30 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:30 systemd-networkd[397]: Added inotify watch for /run on bus bus-api-network: 2
Apr 26 13:09:30 systemd-networkd[397]: Added inotify watch for /run/dbus on bus bus-api-network: -1
Apr 26 13:09:30 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:30 systemd-networkd[397]: Got inotify event on bus bus-api-network.
Apr 26 13:09:30 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:30 systemd-networkd[397]: Added inotify watch for /run on bus bus-api-network: 2
Apr 26 13:09:30 systemd-networkd[397]: Added inotify watch for /run/dbus on bus bus-api-network: -1
Apr 26 13:09:30 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:30 systemd-networkd[397]: Got inotify event on bus bus-api-network.
Apr 26 13:09:30 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:30 systemd-networkd[397]: Added inotify watch for /run on bus bus-api-network: 2
Apr 26 13:09:30 systemd-networkd[397]: Added inotify watch for /run/dbus on bus bus-api-network: -1
Apr 26 13:09:30 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:30 systemd-networkd[397]: Got inotify event on bus bus-api-network.
Apr 26 13:09:30 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:30 systemd-networkd[397]: Added inotify watch for /run on bus bus-api-network: 2
Apr 26 13:09:30 systemd-networkd[397]: Added inotify watch for /run/dbus on bus bus-api-network: -1
Apr 26 13:09:30 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:30 systemd-networkd[397]: Got inotify event on bus bus-api-network.
Apr 26 13:09:30 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:30 systemd-networkd[397]: Added inotify watch for /run on bus bus-api-network: 2
Apr 26 13:09:30 systemd-networkd[397]: Added inotify watch for /run/dbus on bus bus-api-network: -1
Apr 26 13:09:30 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:31 systemd-networkd[397]: Got inotify event on bus bus-api-network.
Apr 26 13:09:31 systemd-networkd[397]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Apr 26 13:09:31 systemd-networkd[397]: Bus bus-api-network: changing state WATCH_BIND → AUTHENTICATING
Apr 26 13:09:31 systemd-networkd[397]: Bus bus-api-network: changing state AUTHENTICATING → HELLO
Apr 26 13:09:31 systemd-networkd[397]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Apr 26 13:09:31 systemd-networkd[397]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RequestName cookie=2 reply_cookie=0 signature=su error-name=n/a error-message=n/a
Apr 26 13:09:31 systemd-networkd[397]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Apr 26 13:09:31 systemd-networkd[397]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.0 path=n/a interface=n/a member=n/a  cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Apr 26 13:09:31 systemd-networkd[397]: Bus bus-api-network: changing state HELLO → RUNNING
Apr 26 13:09:31 systemd-networkd[397]: Got message type=signal sender=org.freedesktop.DBus.Local destination=n/a path=/org/freedesktop/DBus/Local interface=org.freedesktop.DBus.Local member=Connected  cookie=4294967295 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Apr 26 13:09:31 systemd-networkd[397]: Got message type=signal sender=org.freedesktop.DBus destination=:1.0 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired  cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Apr 26 13:09:31 systemd-networkd[397]: Got message type=signal sender=org.freedesktop.DBus destination=:1.0 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired  cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Apr 26 13:09:31 systemd-networkd[397]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.0 path=n/a interface=n/a member=n/a  cookie=4 reply_cookie=2 signature=u error-name=n/a error-message=n/a
Apr 26 13:09:31 systemd-networkd[397]: Successfully acquired requested service name.
Apr 26 13:09:31 systemd-networkd[397]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.0 path=n/a interface=n/a member=n/a  cookie=5 reply_cookie=3 signature=n/a error-name=n/a error-message=n/a
Apr 26 13:09:31 systemd-networkd[397]: Match type='signal',sender='org.freedesktop.login1',path='/org/freedesktop/login1',interface='org.freedesktop.login1.Manager',member='PrepareForSleep' successfully installed.
Apr 26 13:09:31 systemd-networkd[397]: enp0s31f6: Flags change: +UP
Apr 26 13:09:31 systemd-networkd[397]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_36 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=4 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Apr 26 13:09:31 systemd-networkd[397]: enp0s31f6: Link UP
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #37257 and #37275.

### CODE REVIEW

File: src/network/networkd-sriov.c [hunk 1]
```diff
@@ -16,11 +16,8 @@ static int sr_iov_handler(sd_netlink *rtnl, sd_netlink_message *m, Request *req,
         assert(link);
 
         r = sd_netlink_message_get_errno(m);
-        if (r < 0 && r != -EEXIST) {
-                log_link_message_error_errno(link, m, r, "Could not set up SR-IOV");
-                link_enter_failed(link);
-                return 1;
-        }
+        if (r < 0)
+                log_link_message_warning_errno(link, m, r, "Failed to set up SR-IOV virtual function, ignoring");
```
Comment (poettering) [inline src/network/networkd-sriov.c:20]: suffix with `: %m`?

Comment (yuwata) [reply src/network/networkd-sriov.c:20]: log_link_message_warning_errno() append error message from sd_netlink_message.
Hence, `%m` should not.
