### PR TITLE
core: use write() instead of send()

### LINKED ISSUE #33299: systemd 256 fails seccomp on service startup due to sendto() usage
### systemd version the issue has been seen with

256

### Used distribution

Debian Bookworm

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

On systemd v255 we were able to start a unit without `sendto` allowed.

### Unexpected behaviour you saw

On systemd v256 the service fails to start:

```
Jun 12 22:01:22 131m33 systemd[1]: tracefwdr.service: Main process exited, code=exited, status=203/EXEC
```

We have the list of allowed syscalls in `SystemCallFilter=` and `SystemCallErrorNumber=EPERM` for this unit.

If I comment out `SystemCallErrorNumber=`, I can see a seccomp violation:

```
Jun 13 00:16:29 131m33 audisp-syslog[15587]: type=SECCOMP msg=audit(1718237789.318:96110): auid=4294967295 uid=2144 gid=2144 ses=4294967295 pid=1612773 comm="(racefwdr)" exe="/usr/lib/systemd/systemd-executor" sig=31 arch=c000003e syscall=44 compat=0 ip=0x7f8f1f529a39 code=0x80000000 AUID="unset" UID="tracefwdr" GID="tracefwdr" ARCH=x86_64 SYSCALL=unknown-syscall(-1)
```

Here 44 is `sendto`:

```
$ ausyscall 44
sendto
```

After some painful tracing due to `(` replacing the first character of the binary, one can find that `sendto()` is coming from inside the house:

```
(racefwdr) 1615623 [036] 15948.313137: probe:audit_log_format: (ffffffffa9c22180)
        ffffffffa9c22181 audit_log_format+0x1 ([kernel.kallsyms])
        ffffffffa9c2285d audit_log_start+0x49d ([kernel.kallsyms])
        ffffffffa9c43b77 audit_seccomp+0x57 ([kernel.kallsyms])
        ffffffffa9c6153e __seccomp_filter+0x99e ([kernel.kallsyms])
        ffffffffa9b4d390 syscall_trace_enter.isra.0+0x90 ([kernel.kallsyms])
        ffffffffabf441a5 do_syscall_64+0x15 ([kernel.kallsyms])
        ffffffffac000118 entry_SYSCALL_64_after_hwframe+0x60 ([kernel.kallsyms])
            7fcbe1329a39 __libc_send+0x19 (inlined)
            559571c7e9ae run+0x4de (/usr/lib/systemd/systemd-executor)
            559571c70396 main+0x36 (/usr/lib/systemd/systemd-executor)
            7fcbe1246249 __libc_start_call_main+0x79 (/usr/lib/x86_64-linux-gnu/libc.so.6)
```

It seems that there are some inlined frames that are missing, so I cannot pinpoint where exactly in the executor code the `sendto()` syscalls happens.

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a regression caused by 12001b1bf067339db089d52e08fd0b4c6a9945df.
Fixes #33299.

### CODE REVIEW

**Comment by yuwata** [comment]
Please backport to v256-stable.

**Comment by bluca** [comment]
```
08:16:04 [   14.163569] (test-execute-unprivileged)[857]: Child 2886 ((true)) died (code=dumped, status=31/SYS)
08:16:04 [   14.163611] (test-execute-unprivileged)[857]: exec-systemcallfilter-without-network-io.service: Child 2886 belongs to exec-systemcallfilter-without-network-io.service.
08:16:04 [   14.163635] (test-execute-unprivileged)[857]: exec-systemcallfilter-without-network-io.service: Main process exited, code=dumped, status=31/SYS
08:16:04 [   14.163788] (test-execute-unprivileged)[857]: exec-systemcallfilter-without-network-io.service: Failed with result 'core-dump'.
08:16:04 [   14.163816] (test-execute-unprivileged)[857]: exec-systemcallfilter-without-network-io.service: Service will not restart (restart setting)
08:16:04 [   14.163822] (test-execute-unprivileged)[857]: exec-systemcallfilter-without-network-io.service: Changed start -> failed
08:16:04 [   14.171149] (test-execute-unprivileged)[857]: src/test/test-execute.c:835:test_exec_systemcallfilter exec-systemcallfilter-without-network-io.service: can_unshare=no: exit code 3, expected 1
```

File: src/core/exec-invoke.c [hunk 1]
```diff
@@ -4012,7 +4012,7 @@ static int send_handoff_timestamp(
         dual_timestamp dt;
         dual_timestamp_now(&dt);
 
-        if (send(p->handoff_timestamp_fd, (const usec_t[2]) { dt.realtime, dt.monotonic }, sizeof(usec_t) * 2, 0) < 0) {
+        if (write(p->handoff_timestamp_fd, (const usec_t[2]) { dt.realtime, dt.monotonic }, sizeof(usec_t) * 2) < 0) {
```
Comment (YHNdnzj) [inline src/core/exec-invoke.c:4023]: Hmm, this would not really solve the problem? While `network-io` is no longer required, it still makes masking `basic-io` impossible...

**Comment by poettering** [comment]
So i think this does make a ton of sense, and we should merge this, but this is not a complete fix. We should still automatically add `write` to the syscall filter set if the handoff code path will be used.

File: src/core/exec-invoke.c (hunk 1 above)
Comment (yuwata) [reply src/core/exec-invoke.c:4023]: The dependency to `@basic-io` or `write` is not new, but since 5686391b006ee82d8a4559067ad9818e3e631247.

**Comment by yuwata** [comment]
I have no idea why the test failed on CentOS CI (Arch)...

**Comment by yuwata** [comment]
The seccomp filter in the test is relaxed. Let's see if it works.

File: src/core/exec-invoke.c (hunk 1 above)
Comment (YHNdnzj) [reply src/core/exec-invoke.c:4023]: Well, if people choose `Type=exec` + filter out `write`, we can claim that it's a user config problem. Yet here we always send out handoff timestamp, hence IMO these are two sufficiently different cases.

**Comment by yuwata** [comment]
> We should still automatically add `write` to the syscall filter set if the handoff code path will be used.

This is also supported now. PTAL.

**Review by bluca — APPROVED** [review]
