### PR TITLE
systemctl: edit: write override files as text files, instead of stripping the newline off the final would-be line

### LINKED ISSUE #25303: systemctl edit results in final missing final newline
### systemd version the issue has been seen with

247.3-7+deb11u1, 251.6-1

### Used distribution

Debian bullseye, sid

### Linux kernel version used

5.10.0-19-amd64, 6.0.0-2-amd64

### CPU architectures issue was seen on

amd64, x32

### Component

systemctl

### Expected behaviour you didn't see

/e/s/s/*svc*.s.d/o.c to be a text file.

### Unexpected behaviour you saw

It isn't.

### Steps to reproduce the problem

`systemctl edit systemd-networkd-wait-online`, put in some stuff, `cat /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf`, behold

I guess they don't *need* to be text files for systemd to accept them, but it's damn annoying, and means you can't process them in the usual ways.

### Additional program output to the terminal or log subsystem illustrating the issue

I can confirm from some older overrides that they *used* to be text files, so idk.

### PR DESCRIPTION
**Pull request by nabijaczleweli**
I think this is the only time this is abused:
```
$ git grep WRITE_STRING_FILE_AVOID_NEWLINE | grep -v test
src/basic/fileio.c:        needs_nl = !(flags & WRITE_STRING_FILE_AVOID_NEWLINE) && !endswith(line, "\n");
src/basic/fileio.c:        q = verify_file(fn, line, !(flags & WRITE_STRING_FILE_AVOID_NEWLINE) || (flags & WRITE_STRING_FILE_VERIFY_IGNORE_NEWLINE));
src/basic/fileio.h:        WRITE_STRING_FILE_AVOID_NEWLINE              = 1 << 3,
src/udev/udev-rules.c:                                      WRITE_STRING_FILE_AVOID_NEWLINE |
```
The udev-rules.c writes to An attribute, which I assume lives somewhere in sysfs.

Closes #25303

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
CI failure appears unrelated

**Comment by mrc0mmand** [comment]
This now creates an empty `override.conf` if you close the editor after `systemctl edit` without any changes.

Before:
```
# rm -f /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
# EDITOR=cat systemctl edit systemd-networkd-wait-online </dev/null
...
Editing "/etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf" canceled: temporary file is empty.
# wc -l /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
wc: /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf: No such file or directory
```

With this patch:
```
# rm -f /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
# EDITOR=cat build/systemctl edit systemd-networkd-wait-online </dev/null
...
# wc -l /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
1 /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
# hexdump -c /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
0000000  \n                                                            
0000001
```

File: src/systemctl/systemctl-edit.c [hunk 1]
```diff
@@ -486,7 +486,7 @@ static int trim_edit_markers(const char *path) {
 
         /* Write new contents if the trimming actually changed anything */
         if (strlen(contents) != size) {
-                r = write_string_file(path, contents_start, WRITE_STRING_FILE_CREATE | WRITE_STRING_FILE_TRUNCATE | WRITE_STRING_FILE_AVOID_NEWLINE);
+                r = write_string_file(path, contents_start, WRITE_STRING_FILE_CREATE | WRITE_STRING_FILE_TRUNCATE | (*contents_start ? 0 : WRITE_STRING_FILE_AVOID_NEWLINE));
```
Comment (poettering) [inline src/systemctl/systemctl-edit.c]: this doesn't look ideal. the strlen() check above should probably cover the trailing newline too

**Comment by nabijaczleweli** [comment]
Updated to manually re-introduce the trailing newline into the buffer after the strip.

File: src/systemctl/systemctl-edit.c [hunk 2]
```diff
@@ -460,7 +460,7 @@ static int find_paths_to_edit(sd_bus *bus, char **names, char ***paths) {
 
 static int trim_edit_markers(const char *path) {
         _cleanup_free_ char *contents = NULL;
-        char *contents_start = NULL;
+        char *contents_start = NULL, *tmp;
```
Comment (bluca) [inline src/systemctl/systemctl-edit.c]: tmp can be declared inside the new if

File: src/systemctl/systemctl-edit.c [hunk 3]
```diff
@@ -483,6 +483,18 @@ static int trim_edit_markers(const char *path) {
                 strshorten(contents_start, contents_end - contents_start);
 
         contents_start = strstrip(contents_start);
+        if (*contents_start && !endswith(contents_start, "\n")) {
+                if (MALLOC_SIZEOF_SAFE(contents) - (contents_start - contents) - strlen(contents_start) < 2) {
+                        tmp = realloc(contents, size + 1);
+                        if (!tmp)
+                                goto nofix;
```
Comment (bluca) [inline src/systemctl/systemctl-edit.c]: this goto is a bit ugly - just invert the condition check, and add another below

**Comment by nabijaczleweli** [comment]
Both applied

**Review by bluca — APPROVED** [review]

File: src/systemctl/systemctl-edit.c [hunk 4]
```diff
@@ -483,6 +483,18 @@ static int trim_edit_markers(const char *path) {
                 strshorten(contents_start, contents_end - contents_start);
 
         contents_start = strstrip(contents_start);
+        if (*contents_start && !endswith(contents_start, "\n")) {
+                char *tmp = contents_start;
+                if (MALLOC_SIZEOF_SAFE(contents) - (contents_start - contents) - strlen(contents_start) < 2) {
+                        if ((tmp = realloc(contents, size + 1))) {
```
Comment (yuwata) [inline src/systemctl/systemctl-edit.c:489]: Sorry for late review, but why not to use `GREEDY_REALLOC()`??

File: src/systemctl/systemctl-edit.c [hunk 5]
```diff
@@ -483,6 +483,18 @@ static int trim_edit_markers(const char *path) {
                 strshorten(contents_start, contents_end - contents_start);
 
         contents_start = strstrip(contents_start);
+        if (*contents_start && !endswith(contents_start, "\n")) {
```
Comment (yuwata) [inline src/systemctl/systemctl-edit.c:486]: `*contents_start` is `char`, please do not use implicit cast to boolean. Maybe, better to use `isempty()`.

**Comment by yuwata** [comment]
Also, please add testcases for the issue and fix.

File: src/systemctl/systemctl-edit.c (hunk 5 above)
Comment (poettering) [inline src/systemctl/systemctl-edit.c:486]: according to our coding style, we don't want to use C's downgrade-to-bool feature unless the type of the variable is actually boolean or boolean-like – or is a pointer. but *contents_start here is a char, i.e. neither boolean nor pointer. Hence please write:

```c
if (contents_start[0] != 0 && … 
```

Comment (poettering) [reply src/systemctl/systemctl-edit.c:486]: so the second part of the expression is redundant. strstrip() removes trailing whitespace anyway, which means newlines are removed.

File: src/systemctl/systemctl-edit.c [hunk 6]
```diff
@@ -483,6 +483,18 @@ static int trim_edit_markers(const char *path) {
...
+                char *tmp = contents_start;
+                if (MALLOC_SIZEOF_SAFE(contents) - (contents_start - contents) - strlen(contents_start) < 2) {
+                        if ((tmp = realloc(contents, size + 1))) {
+                                contents_start = tmp + (contents_start - contents);
+                                contents = tmp;
+                        }
+                }
+
+                if (tmp)
+                        strcat(contents_start, "\n");
```
Comment (poettering) [inline src/systemctl/systemctl-edit.c:496]: we do not allow strcat() in our codebase. codeql should have refused that.

**Review by poettering — COMMENTED** [review]
I think this should be reworked more substantially...

File: src/systemctl/systemctl-edit.c (hunk 6 above)
Comment (nabijaczleweli) [reply src/systemctl/systemctl-edit.c:496]: Yes you do:
```
nabijaczleweli@tarta:~/store/code/systemd$ git grep -w strcat
.github/codeql-custom.qls:      - cpp/unsafe-strcat
src/basic/unit-name.c:                strcat(s, suffix);
src/systemctl/systemctl-edit.c:                        strcat(contents_start, "\n");
```

And no it shouldn't've, [the buffer size is checked](https://codeql.github.com/codeql-query-help/cpp/cpp-unsafe-strcat/#example).

I could replace the strcat with inline strcat-but-worse. Nothing is gained, semantics are lost.

**Comment by poettering** [comment]
I prepped #25487 now that should simplify this a lot, and addresses all my concerns
