### PR TITLE
core: get rid of unused Service.will_auto_restart logic

### LINKED ISSUE #27594: OnFailure/OnSuccess= fires between service auto-restarts
### systemd version the issue has been seen with

latest main

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

`OnFailure=` fires only after start limit is hit, as per our documentation ([systemd.unit(5)](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#OnFailure=)):

> A space-separated list of one or more units that are activated when this unit enters the "failed" state. A service unit using Restart= enters the failed state only after the start limits are reached.

### Unexpected behaviour you saw

`OnFailure=` fires between auto-restarts. This is originally mentioned in https://github.com/systemd/systemd/pull/26751#issuecomment-1483339684.

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by YHNdnzj**
This essentially reverts 2ad2e41.

The announced new behavior for `OnFailure=` never worked properly, and we've fixed the document instead in #27675.
Therefore, let's get rid of the unused logic completely. More at #27594.

The to-be-added `RestartMode=` option should cover the use case hopefully.

Closes #27594

### CODE REVIEW

**Comment by yuwata** [comment]
> Closes #27594

This is your previous PR. Wrong number? Or, you mean, "Follow-up for #27594"?

**Review by yuwata — COMMENTED** [review]
Hmm, for readability of the change, could you 
1. first drop `Service.will_auto_restart`,
2. then drop `UNIT_NOTIFY_WILL_AUTO_RESTART` ?

I'd like to keep UnitNotifyFlags at least now.

File: src/core/service.c [hunk 1]
```diff
@@ -1941,8 +1941,6 @@ static bool service_will_restart(Unit *u) {
```
Comment (yuwata) [inline src/core/service.c:1944]: The commit message of the first commit is bit outdated?
I guess "This essentially reverts 2ad2e41a72ec19159c0746a78e15ff880fe32a63." should be moved to the second commit??

**Review by yuwata — APPROVED** [review]
LGTM.

File: src/core/service.c (hunk 1 above)
Comment (YHNdnzj) [reply src/core/service.c:1944]: Hmm, I was referring to the `UNIT_NOTIFY_WILL_AUTO_RESTART` logic 🤔, which technically belongs to the first commit.

Comment (yuwata) [reply src/core/service.c:1944]: IIUC, the first commit does not change any behavior, and simply drops an unnecessary flag.

Or, in other words, the referenced commit has been already reverted effectively, and this PR is just a cleanup.

Comment (YHNdnzj) [reply src/core/service.c:1944]: That makes sense. Updated.

**Comment by yuwata** [comment]
@mrc0mmand Could you restart the failed test?

**Comment by mrc0mmand** [comment]
> @mrc0mmand Could you restart the failed test?

Heh, I actually can't. I have no idea why, but Jenkins throws an exception (which has 224 lines, thanks, Java) whenever I try that for this particular job. But given the current results, it's just the usual timeouts when the AWS region is oversaturated, so I wouldn't worry too much about it.
