### PR TITLE
core: do not fail at step SECCOMP if there is no kernel support

### LINKED ISSUE #3882: Systemd should not fail to execute when seccomp is disabled in the kernel
### Submission type
- Bug report
### systemd version the issue has been seen with

> 231
### Used distribution

> Debian
### In case of bug report: Expected behaviour you didn't see

Successful boot on a systemd built with seccomp support but without kernel support (ie, CONFIG_SECCOMP unset).
### In case of bug report: Unexpected behaviour you saw

Failure to boot as several services had SystemCallFilters applied in 231.

This was reported [downstream](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832713). The debian kernels on arm\* do not have SECCOMP enabled (not sure why), and this failure to boot as logind and journald fail to execute.

I think the fix would be to have an equivalent to `mac_selinux_use` for seccomp, and skip the setup in case it is not available.

### PR DESCRIPTION
**Pull request by fsateler**
Fixes #3882

### CODE REVIEW

File: src/shared/seccomp-util.c [hunk 1]
```diff
@@ -89,6 +91,14 @@ int seccomp_add_secondary_archs(scmp_filter_ctx *c) {
 
 }
 
+bool is_seccomp_enabled(void) {
+        _cleanup_free_ char* field = NULL;
+        static int cached_enabled = -1;
+        if (cached_enabled < 0)
+                cached_enabled = get_proc_field("/proc/self/status", "Seccomp", "\n", &field) == 0;
```
Comment (keszybz) [inline src/shared/seccomp-util.c:98]: It would seem cleaner to change get_proc_field to accept NULL argument, and assign the value only if is non-null.

File: src/core/main.c [hunk 2]
```diff
@@ -1186,6 +1189,10 @@ static int enforce_syscall_archs(Set *archs) {
         void *id;
         int r;
 
+        if (!is_seccomp_enabled()) {
+                return 0;
+        }
```
Comment (keszybz) [inline src/core/main.c]: No braces for single statements please.

File: src/core/execute.c [hunk 3]
```diff
@@ -1083,6 +1083,13 @@ static int apply_seccomp(const ExecContext *c) {
 
         assert(c);
 
+        if (!is_seccomp_enabled()) {
+                log_open();
+                log_debug("SECCOMP not detected in the kernel, skipping syscall filtering");
+                log_close();
+                return 0;
+        }
```
Comment (keszybz) [inline src/core/execute.c]: You should define a helper function for this:

```
if (skip_seccomp_disabled("syscall filtering"))
       return 0;
```

File: src/shared/seccomp-util.c [hunk 4]
```diff
@@ -89,6 +91,14 @@ int seccomp_add_secondary_archs(scmp_filter_ctx *c) {
 
 }
 
+bool is_seccomp_enabled(void) {
```
Comment (poettering) [inline src/shared/seccomp-util.c]: hmm, i think "enabled" is a misnomer here, as this suggest that you could disable/enabled seccomp system-wide via some runtime setting, like you can do it for selinux.

I'd probably rename it to is_seccomp_available().

**Comment by fsateler** [comment]
Force pushed with all comments addressed.

File: src/core/execute.c [hunk 5]
```diff
@@ -1074,6 +1074,16 @@ static void rename_process_from_path(const char *path) {
 
 #ifdef HAVE_SECCOMP
 
+static bool skip_seccomp_unavailable(const char* msg) {
+        if (!is_seccomp_available()) {
+                log_open();
+                log_debug("SECCOMP not detected in the kernel, skipping %s", msg);
```
Comment (evverx) [inline src/core/execute.c]: Why not `log_unit_debug`?
I think

```
Aug 21 21:50:58 systemd[968]: systemd-journald.service: SECCOMP not detected in the kernel, skipping MemoryDenyWriteExecute
```

is better than

```
Aug 21 21:50:58 systemd[968]: SECCOMP not detected in the kernel, skipping MemoryDenyWriteExecute
```

File: src/core/main.c [hunk 6]
```diff
@@ -72,6 +72,9 @@
 #include "process-util.h"
 #include "raw-clone.h"
 #include "rlimit-util.h"
+#ifdef HAVE_SECCOMP
```
Comment (evverx) [inline src/core/main.c:75]: Why do we need this `ifdef`?

Comment (fsateler) [inline src/core/main.c:75]: Because seccom-util.h is not part of the dist if HAVE_SECCOMP is not defined (https://github.com/systemd/systemd/blob/v231/Makefile.am#L1065). I think this would break distcheck?

Comment (evverx) [inline src/core/main.c:75]: Well, the `test-execute` doesn't contain that `ifdef`. I've checked:

``` sh
$ sudo dnf remove libseccomp-devel
$ git clean -dxf
$ ./autogen.sh c
$ make
...
In file included from src/test/test-execute.c:33:0:
./src/shared/seccomp-util.h:22:21: fatal error: seccomp.h: No such file or directory
compilation terminated.
```

Comment (keszybz) [inline src/core/main.c:75]: Sounds like a bug in test-execute ;)

File: src/core/execute.c [hunk 7]
```diff
@@ -1130,6 +1143,9 @@ static int apply_address_families(const ExecContext *c) {
 
         assert(c);
 
+        if (skip_seccomp_unavailable("RestrictAddressFamilies"))
```
Comment (poettering) [inline src/core/execute.c]: nitpick: in the docs we usually suffix unit file settings with "=", to indicate that they are unit file settings... I think we should stick to that in log messages too.

**Comment by poettering** [comment]
looks pretty OK overall, only the two minor things left: log_unit_debug() would indeed be nicer to use, and please add the "=" to the options logged. Otherwise looks fine.

(the test-execute issue may be fixed separately, it's after all unrelated to your work)

**Comment by evverx** [comment]
> the test-execute issue may be fixed separately, it's after all unrelated to your work

https://github.com/systemd/systemd/pull/4004/files#diff-cbcbc0f7e2e04ddc0a50f2ef7cdf4c03R33

Should be:

``` c
#ifdef HAVE_SECCOMP
#include "seccomp-util.h"
#endif
```

Am I missing something? :)

**Comment by fsateler** [comment]
Force pushed will all comments addressed (and added the `#ifdef` guard to test-execute.c)

**Comment by poettering** [comment]
lgtm

**Comment by evverx** [comment]
@fsateler , many thanks!
Works fine:

``` sh
-bash-4.3# grep -i seccomp /proc/self/status # CONFIG_SECCOMP is not set

-bash-4.3# journalctl -b --no-hostname | grep -i seccomp
Aug 22 04:13:03 systemd[1]: systemd 231 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Aug 22 04:13:07 systemd[969]: systemd-journald.service: SECCOMP not detected in the kernel, skipping MemoryDenyWriteExecute=
Aug 22 04:13:07 systemd[969]: systemd-journald.service: SECCOMP not detected in the kernel, skipping syscall filtering
Aug 22 04:13:20 systemd[1472]: systemd-timesyncd.service: SECCOMP not detected in the kernel, skipping MemoryDenyWriteExecute=
Aug 22 04:13:20 systemd[1472]: systemd-timesyncd.service: SECCOMP not detected in the kernel, skipping syscall filtering
Aug 22 04:13:22 systemd[1477]: systemd-logind.service: SECCOMP not detected in the kernel, skipping MemoryDenyWriteExecute=
Aug 22 04:13:22 systemd[1477]: systemd-logind.service: SECCOMP not detected in the kernel, skipping syscall filtering
```

But

```
  CC       src/core/libcore_la-load-fragment.lo
In file included from src/core/execute.h:252:0,
                 from src/core/execute.c:68:
src/core/execute.c: In function ‘skip_seccomp_unavailable’:
src/core/unit.h:642:28: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
                 Unit *_u = (unit);                                      \
                            ^
src/core/unit.h:647:37: note: in expansion of macro ‘log_unit_full’
 #define log_unit_debug(unit, ...)   log_unit_full(unit, LOG_DEBUG, 0, ##__VA_ARGS__)
                                     ^
src/core/execute.c:1080:17: note: in expansion of macro ‘log_unit_debug’
                 log_unit_debug(u, "SECCOMP not detected in the kernel, skipping %s", msg);
                 ^
```

I guess we should change `Unit *_u` to `const Unit *_u`

**Comment by fsateler** [comment]
@evverx yes I noticed, I'm prepping a separate PR to fix that :)

In general, there is very little const correctness (eg, `sd_bus_get_*` do not take a `const sd_bus*`). Is this something worth pursuing? At least for the public API.

**Comment by keszybz** [comment]
Unfortunately sd_bus_get_\* are not fixable (public API). We discussed that a while ago. Maybe when we bump the so version.

**Comment by poettering** [comment]
I really don't think sd_bus_get_xyz() should take const bus objects. We want the liberty that we cache whatever they return, and we really shouldn't encode in the API whether some calls might internally cache something (and thus alter the object) or not. Caching is internal, and callers should not be bothered with such logic.

**Comment by fsateler** [comment]
@keszybz I can't find a reference to the old discussion either in the issue tracker or on the mailing lists, do you have a pointer to that? 

Adding a const qualifier should be backwards-compatible both API and ABI-wise: http://stackoverflow.com/a/5083976/1117815 refers to the C99 standard, I can't find a C90 standard copy online, but I think the result should be the same.

Moreover, the `const`ness of a parameter has already been changed at least once: https://github.com/systemd/systemd/pull/529

@poettering do you mean that currently, sd_bus_get_xyz can block if some value is not already cached?

**Comment by poettering** [comment]
@fsateler changing const of function parameters breaks API as pointers taken of that function will change their type.

PR #529 was before we actually declared the sd-bus API stable, hence it was fine to go in.

@fsateler This is not about blocking or not. It's simply about making guarantees about the future. Right now, some sd_bus_get_xyz() calls might not read write access, but let's say one of these options becomes obsolete one day, and replaced by a related, but different API. The old calls are mapped internally to the new ones, to maintain compat. Since the mapping isn't free we might choose to cache what we return, to speed things up when something is called multiple times.

Or think of a different case: we have a couple of cases where we cache stuff in process, things like "what is the current cgroup root?", "what is the current log level?" or "what does $SYSTEMD_COLORS evaluate to?". Maybe one of those days we want to make some caches like that per-bus-object, instead of per-process. Right now, that's totally possible, we can hide that neatly. However, if we make the guarantee through const-ness that these initialize-once variables are never ever part of sd_bus, then we limit our liberties to change internals quite drastically. 

It's really a general question: if you make the object argument "const" then this means, you can _never_ write to it, ever, from that function, not even for cache variables, or statistics, or debugging, or anyting. And that's just a very weird bet to take for the future...

I am very sure that "const" has no place on the "object" argument of functions. It's fine for "non-object" arguments, but not otherwise.

**Comment by fsateler** [comment]
OK, makes sense. I won't work on the const thing then.

**Comment by evverx** [comment]
BTW
@martinpitt , @fsateler 

https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=39ccf2b0a0d5899898452efec7bcb6b04100a871

> Revert "units: add a basic SystemCallFilter
> ...
> This can be reactivated once https://github.com/systemd/systemd/issues/3882 is fixed.

Please note https://github.com/systemd/systemd/issues/3962
This affects Debian/Ubuntu too
Fix: https://anonscm.debian.org/git/selinux/libselinux.git/commit/?id=f8713974c7e925bc82506a090eade13193f57783

**Comment by martinpitt** [comment]
@evverx : Thanks for pointing out! Debian's and Ubuntu's development series already have that fix in libselinux. In systemd packaging git the reversion of system call filters now got dropped and replaced by a cherry-pick of this upstream patch.

Thanks @fsateler for fixing!
