### PR TITLE
sleep: check if we're on AC power before checking battery capacity

### LINKED ISSUE #26492: sleep: suspend-then-hibernate skips suspend when no batteries are present
### systemd version the issue has been seen with

253

### Used distribution

Arch

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

The system (a desktop - no batteries) should be suspended for the period specified by the HibernateDelaySec setting. It should then wake and hibernate. This behavior was expected to be restored with the release of 253.

### Unexpected behaviour you saw

The system does not suspend at all, instead it hibernates immediately.

### Steps to reproduce the problem

On a system without batteries:

1. Set `HibernateDelaySec=` to a small value for testing.
2. Run `systemctl suspend-then-hibernate`.

Observe that the system hibernates immediately.

Having looked at the code, it is the battery_is_low() function (shared/sleep-config.c) causing the issue. Contrary to the comment in the code, the function returns 1 (true) when no battery is present, not zero. This causes custom_timer_suspend() to immediately return 1, resulting in hibernation.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by YHNdnzj**
Fixes #26492

### CODE REVIEW

File: src/shared/sleep-config.c [hunk 1]
```diff
@@ -210,11 +211,13 @@ int battery_is_low(void) {
         if (r < 0)
                 return log_debug_errno(r, "Failed to initialize battery enumerator: %m");
```
Comment (bluca) [inline src/shared/sleep-config.c]: just check if there's any devices with `sd_device_enumerator_get_device_first` here

File: src/shared/sleep-config.c [hunk 2]
```diff
@@ -200,6 +200,7 @@ static int read_battery_capacity_percentage(sd_device *dev) {
 int battery_is_low(void) {
```
Comment (bluca) [inline src/shared/sleep-config.c]: rename to battery_is_present_and_low, or something along those lines

**Comment by poettering** [comment]
hmm, the correct logic is unfortunately a lot more complex. It probably would be wise to just invoke int on_ac_power() first, and shortcut things. It implements the full logic, and it was hard enough to get this somewhat right.

File: src/shared/sleep-config.c (hunk 1 above)
Comment (YHNdnzj) [reply src/shared/sleep-config.c]: I was thinking it might not be worth it as `FOREACH_DEVICE` calls it anyway, and the condition would shortcut things for us 🤔

File: src/shared/sleep-config.c [hunk 3]
```diff
@@ -196,25 +197,31 @@ static int read_battery_capacity_percentage(sd_device *dev) {
...
         _cleanup_(sd_device_enumerator_unrefp) sd_device_enumerator *e = NULL;
         sd_device *dev;
+        bool has_battery = false;
         int r;
 
          /* We have not used battery capacity_level since value is set to full
          * or Normal in case ACPI is not working properly. In case of no battery
          * 0 will be returned and system will be suspended for 1st cycle then hibernated */
 
+        if (on_ac_power())
```
Comment (poettering) [inline src/shared/sleep-config.c]: on_ac_power() might return error. right now you are treating an error like false. Which is OK I think, but we usually want this to be don explicitly, i.e. if we fold the error case into either true or false, then please make this visible by doing a literal check like `!= 0`, and maybe adding a comment.

(and maybe even doing log_debug_errno() in case of the error)

**Comment by poettering** [comment]
looks good, just see my comment about log message/comment/explicit error folding

File: src/shared/sleep-config.c [hunk 4]
```diff
@@ -196,25 +197,31 @@ static int read_battery_capacity_percentage(sd_device *dev) {
         return battery_capacity;
 }
 
-/* If battery percentage capacity is <= 5%, return success */
-int battery_is_low(void) {
+/* If a battery whose percentage capacity is <= 5% exists, and we're not on AC power, return success */
+int battery_is_present_and_low(void) {
         _cleanup_(sd_device_enumerator_unrefp) sd_device_enumerator *e = NULL;
         sd_device *dev;
+        bool has_battery = false;
```
Comment (bluca) [inline src/shared/sleep-config.c]: remove this, no longer needed

**Comment by YHNdnzj** [comment]
> on_ac_power() might return error. right now you are treating an error like false. Which is OK I think, but we usually want this to be don explicitly, i.e. if we fold the error case into either true or false, then please make this visible by doing a literal check like != 0, and maybe adding a comment.

Actually I think if it returns an error we can't just return false directly, and should proceed to check the capacity?

File: src/shared/sleep-config.c [hunk 5]
```diff
@@ -206,6 +207,12 @@ int battery_is_low(void) {
          * or Normal in case ACPI is not working properly. In case of no battery
          * 0 will be returned and system will be suspended for 1st cycle then hibernated */
 
+        r = on_ac_power();
+        if (r < 0)
+                log_debug_errno(r, "Failed to check if the system is running on AC, ignoring: %m");
```
Comment (poettering) [inline src/shared/sleep-config.c]: maybe include ", assuming is not", to indicate clearly how this cases is treated now.

Comment (poettering) [reply src/shared/sleep-config.c]: or maybe say "assuming it might not be"

**Review by bluca — APPROVED** [review]

File: src/sleep/sleep.c [hunk 6]
```diff
@@ -274,7 +274,7 @@ static int custom_timer_suspend(const SleepConfig *sleep_config) {
 
         hibernate_timestamp = usec_add(now(CLOCK_BOOTTIME), sleep_config->hibernate_delay_usec);
 
-        while (battery_is_low() == 0) {
+        while (!battery_is_present_and_low()) {
```
Comment (keszybz) [inline src/sleep/sleep.c]: Please don't use `!` on a value which may be < 0. The previous version with `== 0` was better.

File: src/shared/sleep-config.c [hunk 7]
```diff
@@ -196,8 +197,8 @@ static int read_battery_capacity_percentage(sd_device *dev) {
         return battery_capacity;
 }
 
-/* If battery percentage capacity is <= 5%, return success */
-int battery_is_low(void) {
+/* If a battery whose percentage capacity is <= 5% exists, and we're not on AC power, return success */
+int battery_is_present_and_low(void) {
```
Comment (keszybz) [inline src/shared/sleep-config.c]: Hmm, but this new name doesn't reflect the new semantics. It is more precise, so one would expect that this extra precision describes the logic, but that's not the case. The old name was better…

File: src/shared/sleep-config.c [hunk 8]
```diff
@@ -206,6 +207,12 @@ int battery_is_low(void) {
          * or Normal in case ACPI is not working properly. In case of no battery
          * 0 will be returned and system will be suspended for 1st cycle then hibernated */
 
+        r = on_ac_power();
+        if (r < 0)
+                log_debug_errno(r, "Failed to check if the system is running on AC, assuming it might not be: %m");
```
Comment (keszybz) [inline src/shared/sleep-config.c]: "assuming it is not" ?

**Review by keszybz — CHANGES_REQUESTED** [review]

File: src/shared/sleep-config.c (hunk 7 above)
Comment (bluca) [reply src/shared/sleep-config.c]: how so? it returns true if the battery is low, false otherwise

Comment (YHNdnzj) [reply src/shared/sleep-config.c]: Maybe something like `battery_is_discharging_and_low` then?
