### PR TITLE
stat-util: Make sure we trigger automounts when looking for ESP/XBOOTLDR

### LINKED ISSUE #25417: launching kexec.target fails because efi partition is unmounted already
### systemd version the issue has been seen with

251

### Used distribution

Kubuntu 22.10

### Linux kernel version used

5.19.0-23

### CPU architectures issue was seen on

x86_64

### Component

systemd, systemd-boot

### Expected behaviour you didn't see

I would expect that the following three commands will result in kexec:

    systemctl kexec
    systemctl start kexec.target --job-mode=replace-irreversibly
    qdbus --system org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.StartUnit kexec.target replace-irreversibly

I am using systemd-boot, so my system follows the Boot Loader Specification.

### Unexpected behaviour you saw

     systemctl start kexec.target --job-mode=replace-irreversibly
     qdbus --system org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.StartUnit kexec.target replace-irreversibly

did not result in kexec, I got the following error message:

    nov 16 10:39:04 GreenOne systemctl[2041]: No kexec kernel loaded and autodetection failed.
    nov 16 10:39:04 GreenOne systemctl[2041]: Cannot automatically load kernel: ESP mount point not found.
    nov 16 10:39:04 GreenOne systemctl[2041]: Failed to load kexec kernel, continuing without.

As per https://lists.freedesktop.org/archives/systemd-devel/2022-August/048235.html, it is because

> systemctl attempts to autodetect kernel
> for kexec and it needs ESP; final call to "systemctl --force kexec"
> happens late, when ESP (/boot/efi in your case) is already unmounted.

Putting the following to `/etc/systemd/system/boot-efi.mount.d/nodef.conf`:

    [Unit]
    DefaultDependencies=false

and the following to `/etc/systemd/system/systemd-fsck@dev-disk-by\\x2duuid-893B\\x2d91D8.service.d/exit.conf`

    [Service]
    RemainAfterExit=false

(replace `893B` and `91D8` with the first and second part of the UUID of your `/boot/efi`.)

makes the above commands work.

### Steps to reproduce the problem

Run either of the following on Kubuntu 22.10 (fresh install with systemd-boot turned on, I used this guide to set it up: https://blobfolio.com/2018/replace-grub2-with-systemd-boot-on-ubuntu-18-04/ – - not sure if this is distro specific, or even hardware specific. I tried this on Thinkpad X1 Extreme gen 2 and Thinkpad x1 Nano gen 1).

    systemctl start kexec.target --job-mode=replace-irreversibly
    qdbus --system org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.StartUnit kexec.target replace-irreversibly

Reported as instructed on the mailing list (I was waiting for my distro's systemd to catch up with one recent enough to be allowed to report a bug): https://lists.freedesktop.org/archives/systemd-devel/2022-August/048237.html

I was also confused by the documentation here: https://github.com/systemd/systemd/issues/24588

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by daandemeyer**
Fixes #25417

### CODE REVIEW

File: src/basic/stat-util.c [hunk 1]
```diff
@@ -451,11 +451,19 @@ int statx_fallback(int dfd, const char *path, int flags, unsigned mask, struct s
...
 
         assert(dir_fd >= 0 || dir_fd == AT_FDCWD);
         assert(ret);
 
+        nested = path_join(path, "a");
+        if (!nested)
+                return -ENOMEM;
+
+        /* Make sure we trigger any automounts by trying to access a file inside the given path. */
+        (void) faccessat(dir_fd, nested, F_OK, 0);
```
Comment (yuwata) [inline src/basic/stat-util.c]: Why not to do that in caller side? I don't think we should unconditionally do like that...

Comment (daandemeyer) [reply src/basic/stat-util.c]: We can make it configurable if needed but it seems good to do this by default. It's very hard to consider when writing code that a directory might be automounted and I think that usually we want to check something of the automounted directory instead of the mountpoint.

A good example is that we broke `bootctl status` and `systemctl kexec` by not doing this.

Comment (yuwata) [reply src/basic/stat-util.c]: Hm, it is used in `is_fs_type_at()` hence in `path_is_fs_type()` and `fd_is_fs_type()`... Also, it is used in `rm_rf()`.

I am not sure we can change all calls to trigger automount...

**Comment by DaanDeMeyer** [comment]
We only trigger automounts in find-esp now, PTAL!

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
lgtm
