### PR TITLE
network: ndisc: ignore route prefix if the destination is ::/0 and UseGateway=no

### LINKED ISSUE #21912: UseGateway=no does not work on IPv6AcceptRA
**systemd version the issue has been seen with**
[root@localhost ~]# systemctl --version
systemd 250 (250-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
Arch Linux

**Linux kernel version used** (`uname -a`)
[root@localhost ~]# uname -a
Linux localhost 5.15.11-arch2-1 #1 SMP PREEMPT Wed, 22 Dec 2021 09:23:54 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
x86-64

**Expected behaviour you didn't see**
When setting UseGateway=no on IPv6AcceptRA, default route advertised by IPv6 RA should be ignored.

**Unexpected behaviour you saw**
Default route is still inserted with UseGateway=no on IPv6AcceptRA section.

**Steps to reproduce the problem**
Set UseGateway=no on IPv6 network with default route advertised by RA.
Default route should not be inserted for the specified interface.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
[root@localhost ~]# cat /etc/systemd/network/ens160.network
[Match]
Name=ens160

[Link]
MTUBytes=1500

[Network]
DHCP=yes
IPv6LinkLocalAddressGenerationMode=eui64

[DHCPv4]
UseGateway=yes

[root@localhost ~]# cat /etc/systemd/network/ens192.network
[Match]
Name=ens192

[Link]
MTUBytes=9000

[Network]
DHCP=yes
IPv6LinkLocalAddressGenerationMode=eui64

[DHCPv4]
UseGateway=no

[IPv6AcceptRA]
UseGateway=no

[root@localhost ~]# ip -6 r
::1 dev lo proto kernel metric 256 pref medium
2001:aaaa:aaaa:aaaa::/64 dev ens160 proto ra metric 1024 expires 2591944sec pref medium
2a01:bbbb:bbbb:bbbb::/64 dev ens192 proto ra metric 1024 expires 86388sec pref medium
fe80::/64 dev ens160 proto kernel metric 256 pref medium
fe80::/64 dev ens192 proto kernel metric 256 pref medium
default proto ra metric 1024 expires 1744sec mtu 1500 pref medium
        nexthop via fe80::aaaa dev ens160 weight 1
        nexthop via fe80::bbbb dev ens192 weight 1
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #21912.

### CODE REVIEW

**Comment by yuwata** [comment]
This needs to be backported to v250-stable.

**Review by bluca — APPROVED** [review]

File: src/network/networkd-ndisc.c [hunk 1]
```diff
@@ -612,6 +612,11 @@ static int ndisc_router_process_route(Link *link, sd_ndisc_router *rt) {
         if (r < 0)
                 return log_link_error_errno(link, r, "Failed to get route prefix length: %m");
 
+        if (!link->network->ipv6_accept_ra_use_gateway &&
```
Comment (tomty89) [inline src/network/networkd-ndisc.c]: Hmm, in `ndisc_router_process_default()`:

https://github.com/systemd/systemd/blob/a420d71793bcbc1539a63be60f83cdc14373ea4a/src/network/networkd-ndisc.c#L346-L363

Do we even need `!link->network->ipv6_accept_ra_use_gateway &&` here? Or are they actually for different stuff?

Comment (yuwata) [reply src/network/networkd-ndisc.c]: When networkd receives an RA, then networkd creates the default gateway via the router address. Also, networkd creates routes defined in route prefixes. If an RA contains a route prefix whose destination is ::/0, then the created route becomes the default gateway. Hence, if `UseGateway=no` is set, we also need to check route prefixes contained in RA.

Comment (tomty89) [reply src/network/networkd-ndisc.c]: > If an RA contains a route prefix whose destination is ::/0, then the created route becomes the default gateway.

And the nexthop/via of that will always also be the router address? If that's the case, `ndisc_router_process_route()` can return (0) whenever `in6_addr_is_null(&dst) && prefixlen == 0`, regardless of whether `link->network->ipv6_accept_ra_use_gateway` is false? (Because `ndisc_router_process_default()` will do the same thing regardless of whether the RA contains such route prefix?)

Comment (yuwata) [reply src/network/networkd-ndisc.c]: Indeed. Updated.

**Comment by millnet-maho** [comment]
Wouldn't it be a good idea to distinguish between automatically using the router as the default gateway and accepting an explicit ::/0 route? I'd like to turn off the former but still have networkd process explicit default routes (route info option (24) of ::/0). (Specifically, if you have two or more routers on the same network but only one advertises ::/0.)

**Comment by yuwata** [comment]
@millnet-maho Please file as a new request. Otherwise we can easily forget your request.
