### PR TITLE
process-util: handle pidfd_spawn() returning E2BIG

### LINKED ISSUE #33613: Update systemd 255.7-1 to 256.1-1 => attempt restart Linux  =>  segfault and kernel panic
### systemd version the issue has been seen with

256.1-1-x86_64

### Used distribution

Manjaro 24.0.3

### Linux kernel version used

5.4.278-1-MANJARO (LTS)

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Linux Manjaro 24.0.3. kernel 5.4.278 (LTS), systemd 255.7-1.
Installed in Virtualbox, works successfully.

### Unexpected behaviour you saw

After update systemd 255.7-1 to 256.1-1:
1) restart system failed - segfault in libsystemd-shared-256.1-1.so, kernel panic, system stopped.
2) after reset - system loadind failed.
Segfault

### Steps to reproduce the problem

Problem after full update:

`# pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (4) lib32-systemd-256.1-1  systemd-256.1-1  systemd-libs-256.1-1  systemd-sysvcompat-256.1-1

Total Download Size:   10.28 MiB
Total Installed Size:  37.15 MiB
Net Upgrade Size:       1.61 MiB

:: Proceed with installation? [Y/n] y
`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[VM-Test4 test_user]# pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (4) lib32-systemd-256.1-1  systemd-256.1-1  systemd-libs-256.1-1  systemd-sysvcompat-256.1-1

Total Download Size:   10.28 MiB
Total Installed Size:  37.15 MiB
Net Upgrade Size:       1.61 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 systemd-256.1-1-x86_64                               8.5 MiB  1678 KiB/s 00:05 [#############################################] 100%
 systemd-libs-256.1-1-x86_64                       1129.9 KiB  1385 KiB/s 00:01 [#############################################] 100%
 lib32-systemd-256.1-1-x86_64                       731.6 KiB  1025 KiB/s 00:01 [#############################################] 100%
 systemd-sysvcompat-256.1-1-x86_64                    6.1 KiB  73.4 KiB/s 00:00 [#############################################] 100%
 Total (4/4)                                         10.3 MiB  1484 KiB/s 00:07 [#############################################] 100%
(4/4) checking keys in keyring                                                  [#############################################] 100%
(4/4) checking package integrity                                                [#############################################] 100%
(4/4) loading package files                                                     [#############################################] 100%
(4/4) checking for file conflicts                                               [#############################################] 100%
(4/4) checking available disk space                                             [#############################################] 100%
:: Processing package changes...
(1/4) upgrading systemd-libs                                                    [#############################################] 100%
(2/4) upgrading lib32-systemd                                                   [#############################################] 100%
(3/4) upgrading systemd                                                         [#############################################] 100%
:: This is a systemd feature update. You may want to have a look at
   NEWS for what changed, or if you observe unexpected behavior:
     /usr/share/doc/systemd/NEWS
(4/4) upgrading systemd-sysvcompat                                              [#############################################] 100%
:: Running post-transaction hooks...
( 1/12) Creating system user accounts...
( 2/12) Updating journal message catalog...
( 3/12) Reloading system manager configuration...
( 4/12) Reloading user manager configuration...
( 5/12) Updating udev hardware database...
( 6/12) Applying kernel sysctl settings...
( 7/12) Creating temporary files...
( 8/12) Reloading device manager configuration...
( 9/12) Arming ConditionNeedsUpdate...
(10/12) Updating the MIME type database...
(11/12) Updating linux initcpios...
==> Building image from preset: /etc/mkinitcpio.d/linux54.preset: 'default'
==> Using configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-5.4-x86_64 -c /etc/mkinitcpio.conf -g /boot/initramfs-5.4-x86_64.img
==> Starting build: '5.4.278-1-MANJARO'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [kms]
==> WARNING: No module containing the symbol 'drm_privacy_screen_register' found in: 'drivers/platform'
  -> Running build hook: [block]
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [filesystems]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: '/boot/initramfs-5.4-x86_64.img'
  -> Early uncompressed CPIO image generation successful
==> Initcpio image generation successful
==> Building image from preset: /etc/mkinitcpio.d/linux54.preset: 'fallback'
==> Using configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-5.4-x86_64 -c /etc/mkinitcpio.conf -g /boot/initramfs-5.4-x86_64-fallback.img -S autodetect
==> Starting build: '5.4.278-1-MANJARO'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [modconf]
  -> Running build hook: [kms]
==> WARNING: Possibly missing firmware for module: 'ast'
==> WARNING: No module containing the symbol 'drm_privacy_screen_register' found in: 'drivers/platform'
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: 'qed'
==> WARNING: Possibly missing firmware for module: 'bfa'
==> WARNING: Possibly missing firmware for module: 'qla1280'
==> WARNING: Possibly missing firmware for module: 'qla2xxx'
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [filesystems]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: '/boot/initramfs-5.4-x86_64-fallback.img'
  -> Early uncompressed CPIO image generation successful
==> Initcpio image generation successful
(12/12) Reloading system bus configuration...
Job for dbus-broker.service failed.
See "systemctl status dbus-broker.service" and "journalctl -xeu dbus-broker.service" for details.
error: command failed to execute correctly







[VM-Test4 test_user]# systemctl status dbus-broker.service
● dbus-broker.service - D-Bus System Message Bus
     Loaded: loaded (/usr/lib/systemd/system/dbus-broker.service; disabled; preset: disabled)
     Active: active (running) since Thu 2024-07-04 12:40:34 +06; 31min ago
 Invocation: 88a7395d66fa447182aa9a9c3a6b9037
TriggeredBy: ● dbus.socket
       Docs: man:dbus-broker-launch(1)
   Main PID: 685 (dbus-broker-lau)
      Tasks: 2 (limit: 9524)
     Memory: 7.9M
        CPU: 380ms
     CGroup: /system.slice/dbus-broker.service
             ├─685 /usr/bin/dbus-broker-launch --scope system --audit
             └─686 dbus-broker --log 4 --controller 9 --machine-id 321fc68d579f4a9fa7c5027fe9e52fe8 --max-bytes 536870912 --max-fds 4096 --max-matches 131072>

Jul 04 13:09:52 VM-Test4 dbus-broker-launch[685]: Looking up NSS user entry for 'pulse'...
Jul 04 13:09:52 VM-Test4 dbus-broker-launch[685]: NSS returned no entry for 'pulse'
Jul 04 13:09:52 VM-Test4 dbus-broker-launch[685]: Invalid user-name in /usr/share/dbus-1/system.d/pulseaudio-system.conf +27: user="pulse"
Jul 04 13:09:52 VM-Test4 dbus-broker-launch[685]: Noticed file-system modification, trigger reload.
Jul 04 13:09:52 VM-Test4 dbus-broker-launch[685]: Looking up NSS user entry for 'pulse'...
Jul 04 13:09:52 VM-Test4 dbus-broker-launch[685]: NSS returned no entry for 'pulse'
Jul 04 13:09:52 VM-Test4 dbus-broker-launch[685]: Invalid user-name in /usr/share/dbus-1/system.d/pulseaudio-system.conf +27: user="pulse"
Jul 04 13:11:12 VM-Test4 systemd[1]: dbus-broker.service: Failed to spawn executor: Argument list too long
Jul 04 13:11:12 VM-Test4 systemd[1]: dbus-broker.service: Failed to spawn 'reload' task: Argument list too long
Jul 04 13:11:12 VM-Test4 systemd[1]: Reload failed for D-Bus System Message Bus.

[VM-Test4 test_user]#
```

### PR DESCRIPTION
**Pull request by kkourt**
process-util: handle pidfd_spawn() returning E2BIG

In some kernels (specifically, 5.4) even though the clone3 syscall is
supported, setting CLONE_INTO_CGROUP is not. The error message returned
in this case is E2BIG.

If posix_spawn_wrapper encounters this error, it does not retry, and
cannot spawn any programs in said kernels.

This commit adds a check for the E2BIG error and retries pidfd_spawn()
without the POSIX_SPAWN_SETCGROUP flag.

Originally, this issue was reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1077204.

Fixes #33613

### CODE REVIEW

**Comment by kkourt** [comment]
CC: @bluca who introduced pidfd_spawn in 2e106312e2e8e8f88516039446abcf7d9afdaff2

File: src/basic/process-util.c [hunk 1]
```diff
@@ -2107,7 +2107,7 @@ int posix_spawn_wrapper(
 
                 return FLAGS_SET(flags, POSIX_SPAWN_SETCGROUP);
         }
-        if (ERRNO_IS_NOT_SUPPORTED(r)) {
+        if (ERRNO_IS_NOT_SUPPORTED(r) || r == E2BIG) {
```
Comment (bluca) [inline src/basic/process-util.c]: If this is only an issue due to POSIX_SPAWN_SETCGROUP, then instead of falling back to posix_spawn, please add another branch just above the r == 0 that retries removes POSIX_SPAWN_SETCGROUP from flags and retries pidfd_spawn

**Comment by YHNdnzj** [comment]
> In some kernels (specifically, 5.4) even though the clone3 syscall is supported, setting CLONE_INTO_CGROUP is not. The error message returned in this case is E2BIG.

Hmm, but this is neither documented nor sane behavior, no? Has this been raised to kernel/glibc folks first?

**Comment by YHNdnzj** [comment]
Hmm, https://lore.kernel.org/lkml/20240808-clone3-shadow-stack-v8-8-0acf37caf14c@kernel.org/ suggests that this is indeed considered valid for clone3(). I wonder glibc should document this properly or convert the errno to e.g. EINVAL. But this patch makes sense nonetheless then.

File: src/basic/process-util.c (hunk 1 above)
Comment (yuwata) [inline src/basic/process-util.c]: Please add a short comment what `E2BIG` means here. Not only in the commit message.

**Comment by K900** [comment]
I'm pretty sure this is actually a glibc bug - it's failing because it's setting `clone_args.cgroup` unconditionally even on kernels where it's not available, instead of taking the fallback.

**Comment by poettering** [comment]
I think kernel/glibc behaviour does make some sense, and yes, we should handle this gracefully, i.e. try to disable the POSIX_SPAWN_SETCGROUP flag, then try again, and if it works now, cache this fact.

File: src/basic/process-util.c (hunk 1 above)
Comment (kkourt) [reply src/basic/process-util.c]: Thanks, pushed a new version with this change.

Comment (kkourt) [reply src/basic/process-util.c]: Thanks, pushed a new version that includes a comment as well.

File: src/basic/process-util.c [hunk 2]
```diff
@@ -2100,6 +2100,15 @@ int posix_spawn_wrapper(
         _cleanup_close_ int pidfd = -EBADF;
 
         r = pidfd_spawn(&pidfd, path, NULL, &attr, argv, envp);
+        if (r == E2BIG) {
```
Comment (poettering) [inline src/basic/process-util.c]: please also check if POSIX_SPAWN_SETCGROUP was actually set here. otherwise E2BIG might mean something unrelated after all.

**Review by poettering — CHANGES_REQUESTED** [review]

File: src/basic/process-util.c [hunk 3]
```diff
@@ -2100,6 +2100,15 @@ int posix_spawn_wrapper(
...
+                /* Some kernels (e.g., 5.4) support clone3 but they do not support CLONE_INTO_CGROUP.
+                 * Retry pidfd_spawn() after removing the flag. */
+                flags &= ~POSIX_SPAWN_SETCGROUP;
+                r = posix_spawnattr_setflags(&attr, flags);
+                if (r != 0)
+                        return -r;
+                r = pidfd_spawn(&pidfd, path, NULL, &attr, argv, envp);
+        }
```
Comment (poettering) [inline src/basic/process-util.c:2116]: and please, as suggested earlier, cache the result, i.e. add "static bool setcgroup_supported = true;" somewhere as a local static variable here, and then set it to false if we realize it doesn't actually work. Then, always check this field before we try to do anything.

File: src/basic/process-util.c [hunk 4]
```diff
@@ -2117,11 +2126,14 @@ int posix_spawn_wrapper(
...
 
         /* Compiled on a newer host, or seccomp&friends blocking clone3()? Fallback, but need to change the
-         * flags to remove the cgroup one, which is what redirects to clone3() */
-        flags &= ~POSIX_SPAWN_SETCGROUP;
-        r = posix_spawnattr_setflags(&attr, flags);
-        if (r != 0)
-                return -r;
+         * flags to remove the cgroup one, which is what redirects to clone3().
+         * Clear POSIX_SPAWN_SETCGROUP if it was not already done. */
+        if (flags & POSIX_SPAWN_SETCGROUP) {
```
Comment (YHNdnzj) [inline src/basic/process-util.c]: FLAGS_SET

File: src/basic/process-util.c (hunk 3 above)
Comment (kkourt) [reply src/basic/process-util.c:2116]: OK, did so in a second patch. I only update the static variable if we were successful because otherwise, there might be something else going wrong.

File: src/basic/process-util.c [hunk 5]
```diff
@@ -2098,6 +2098,15 @@ int posix_spawn_wrapper(
...
         _cleanup_close_ int pidfd = -EBADF;
+        static bool setcgroup_supported = true;
+
+        /* If we have observed that SPAWN_CGROUP is not supported, remove the flag */
+        if (!setcgroup_supported && FLAGS_SET(flags, POSIX_SPAWN_SETCGROUP)) {
+                flags &= ~POSIX_SPAWN_SETCGROUP;
+                r = posix_spawnattr_setflags(&attr, flags);
+                if (r != 0)
+                        return -r;
+        }
```
Comment (yuwata) [inline src/basic/process-util.c]: This should be moved slightly earlier place.
```c
        static bool setcgroup_supported = true;
        _cleanup_close_ int cgroup_fd = -EBADF;

        if (cgroup && setcgroup_supported) {
                ......
```

**Review by yuwata — CHANGES_REQUESTED** [review]

**Comment by yuwata** [comment]
@kkourt Could you squash the two commits? I do not think the change should be split into two.

**Comment by kkourt** [comment]
> @kkourt Could you squash the two commits? I do not think the change should be split into two.

Sounds good. Squashed the commits and moved the declaration of the boolean up requested.

File: src/basic/process-util.c [hunk 6]
```diff
@@ -2099,7 +2100,28 @@ int posix_spawn_wrapper(
 #if HAVE_PIDFD_SPAWN
         _cleanup_close_ int pidfd = -EBADF;
 
+        /* If we have observed that SPAWN_CGROUP is not supported, remove the flag */
+        if (!setcgroup_supported && FLAGS_SET(flags, POSIX_SPAWN_SETCGROUP)) {
```
Comment (YHNdnzj) [inline src/basic/process-util.c]: Please just skip the opening of cgroup altogether if we know in advance it would be ignored anyway.

**Review by YHNdnzj — CHANGES_REQUESTED** [review]

File: src/basic/process-util.c (hunk 6 above)
Comment (yuwata) [reply src/basic/process-util.c]: Yeah, please see the above code in my comment.

Comment (poettering) [reply src/basic/process-util.c]: yes, the opening of the cgorup is what is slow, and if it doesn't work we really shouldn't bother.

File: src/basic/process-util.c [hunk 7]
```diff
@@ -2099,7 +2100,28 @@ int posix_spawn_wrapper(
...
         r = pidfd_spawn(&pidfd, path, NULL, &attr, argv, envp);
+        if (r == E2BIG && FLAGS_SET(flags, POSIX_SPAWN_SETCGROUP)) {
+                /* Some kernels (e.g., 5.4) support clone3 but they do not support CLONE_INTO_CGROUP.
+                 * Retry pidfd_spawn() after removing the flag. */
+                flags &= ~POSIX_SPAWN_SETCGROUP;
+                r = posix_spawnattr_setflags(&attr, flags);
+                if (r != 0)
+                        return -r;
+                r = pidfd_spawn(&pidfd, path, NULL, &attr, argv, envp);
+                /* if pidfd_spawn was succesfull after removing SPAWN_CGROUP,
```
Comment (poettering) [inline src/basic/process-util.c]: successfull → successful

**Comment by kkourt** [comment]
Thanks for the reviews, I believe all comments were addressed in the latest push.

File: src/basic/process-util.c [hunk 8]
```diff
@@ -2099,7 +2100,28 @@ int posix_spawn_wrapper(
 #if HAVE_PIDFD_SPAWN
         _cleanup_close_ int pidfd = -EBADF;
 
+        /* If we have observed that SPAWN_CGROUP is not supported, remove the flag */
+        if (!setcgroup_supported && FLAGS_SET(flags, POSIX_SPAWN_SETCGROUP)) {
+                flags &= ~POSIX_SPAWN_SETCGROUP;
+                r = posix_spawnattr_setflags(&attr, flags);
+                if (r != 0)
+                        return -r;
+        }
```
Comment (poettering) [inline src/basic/process-util.c]: you can drop this whole block now

Comment (kkourt) [reply src/basic/process-util.c]: ah yes, indeed.

I left the check in:
```
+        if (FLAGS_SET(flags, POSIX_SPAWN_SETCGROUP)) {
+                flags &= ~POSIX_SPAWN_SETCGROUP;
+                r = posix_spawnattr_setflags(&attr, flags);
+                if (r != 0)
+                        return -r;
+        }
```

But maybe it can be removed as well?

**Review by bluca — APPROVED** [review]

File: src/basic/process-util.c (hunk 8 above)
Comment (yuwata) [reply src/basic/process-util.c]: The change should be OK. Let's keep it.

**Review by yuwata — APPROVED** [review]
LGTM.
