### PR TITLE
network/sr-iov: ignore EINVAL in reading dev_port sysfs attribute

### LINKED ISSUE #27369: Failed to manage SR-IOV PF and VF ports, ignoring: Invalid argument
### systemd version the issue has been seen with

252

### Used distribution

Ubuntu 23.04

### Linux kernel version used

5.19.0-40-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

No errors

### Unexpected behaviour you saw

My log gets spammed by:

`systemd-networkd[554]: vethe8f1694: Failed to manage SR-IOV PF and VF ports, ignoring: Invalid argument`

I think the `vethe8f1694` interface is from Docker, but this issue started appearing when updating Ubuntu 22.10 to 23.04 so I suspect its more likely that its related to systemd than with docker.

### Steps to reproduce the problem

Honestly I have no idea. I have another system with exactly the same kernel/hardware/docker version, where I don't see this error, so I'm not sure what is causing this.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemd-networkd[554]: veth9634225: Failed to manage SR-IOV PF and VF ports, ignoring: Invalid argument
```

### PR DESCRIPTION
**Pull request by yuwata**
This also adds several debugging logs.

Fixes #27369.

### CODE REVIEW

**Comment by yuwata** [comment]
Please backport the first commit to stable.

File: src/network/networkd-sriov.c [hunk 1]
```diff
@@ -209,7 +209,11 @@ static int link_set_sr_iov_phys_port(Link *link) {
         if (!link->dev)
                 return -ENODEV;
 
+        /* This may return -EINVAL or -ENODEV, instead of -ENOENT, if the device has been removed or is under
```
Comment (bluca) [inline src/network/networkd-sriov.c]: "is being removed"

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
lgtm
