### PR TITLE
tmpfiles: try to set file attributes one by one

### LINKED ISSUE #17690: systemd-tmpfiles prints weird errors when setting file attributes that conflict
**systemd version the issue has been seen with**
 > Arch Linux's  246.6-1

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > 5.9.9-arch1-1

**CPU architecture issue was seen on**
 > x86-64

**Expected behaviour you didn't see**
 > systemd-tmpfiles not printing any errors

**Unexpected behaviour you saw**
 > systemd-tempfiles prints the following errors:
```
(2/3) Creating temporary files...
Cannot set file attribute for '/var/log/journal', value=0x00800000, mask=0x00800000, ignoring: Invalid argument
Cannot set file attribute for '/var/log/journal/1cd5XXXXXXXXXXXXXXXX32420fa', value=0x00800000, mask=0x00800000, ignoring: Invalid argument
Cannot set file attribute for '/var/log/journal/remote', value=0x00800000, mask=0x00800000, ignoring: Invalid argument
```

My investigation showed that these errors are only printed when compression was enabled on the directories systemd-tmpfiles tries to set the `+C` attribute on. Running `chattr -c` on the directories listed in the error messages fixed the errors.
It seems to me that **compression** and **no CoW** cannot be enabled together on **btrfs**.

Maybe this can be fixed by also disabling compression in [master/tmpfiles.d/journal-nocow.conf](https://github.com/systemd/systemd/blob/master/tmpfiles.d/journal-nocow.conf), if thats possible, sensible and does not hurt on other filesystems?

The other issue here is, maybe the error messages could be improved? It took me some googling to get to the root of the issue...

**Steps to reproduce the problem**
 > Enable compression on a btrfs filesystem before systemd-tmpfiles creates `/var/log/journal`

EDIT: It seems this only happens if the attributes are used via `chattr +c` or `btrfs property set ./dir compression lzo`, but not when using the mount option `compress=`.
Sounds like there could be a btrfs bug at play here, too, but I dont think thats the case since `btrfs(5)` states for the `nodatacow` mount option: ` Nodatacow implies nodatasum, and disables compression.`

also, showing that `+c` and `+C` seem to conflict:
```console
% mkdir dir                                             
% lsattr                                                
-------------------- ./dir
% chattr +C dir                                         
% lsattr                                                
---------------C---- ./dir
% chattr +c dir                                         
chattr: Invalid argument while setting flags on dir
% lsattr                                                
---------------C---- ./dir
% chattr -C dir                                         
% chattr +c dir                                         
% lsattr                                                
--------c----------- ./dir
% chattr +C dir                                         
chattr: Invalid argument while setting flags on dir
% lsattr                                                
--------c----------- ./dir
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #17690.

### CODE REVIEW

**Comment by poettering** [comment]
I wonder if we can't find a more generic solution. i.e. if we get EINVAL when setting the whole set of attributes at once, we instead try to turn them on one by one. And log about the ones we cannot turn on in some brief manner. That sounds more future proof I guess.

**Comment by yuwata** [comment]
> if we get EINVAL when setting the whole set of attributes at once, we instead try to turn them on one by one.

I initially had that idea. But in what order should we set attributes? E.g., if `+cC` is specified for a file or directory on btrfs (assume that none of them are already added), then which attribute should be added?

**Comment by poettering** [comment]
Well, it's not clear which of the two attributes is more relevant. I mean, is nocow or encryption more relevant? I really couldn't say. Hence i'd just start with the value with the lowest value, and go from there, to define some order. And then log about the flags we couldn't enable. Ultimately the user has to do something about this anyway and adjust the rules, we couldn't possibly know what is the right approach to fixing the issue.

I'd thus add chattr_fd_verbose() that is a chatty wrapper around chattr_fd() and falls back to sending all specified flags one by one, if we can't apply them at once.

**Comment by yuwata** [comment]
OK, I will implement that later instead of the current patch.

**Comment by yuwata** [comment]
@poettering Updated. Now if `ioctl()` fails with `EINVAL`, then the requested file attributes are set one by one. PTAL.

File: src/tmpfiles/tmpfiles.c [hunk 1]
```diff
@@ -1308,11 +1308,15 @@ static int fd_set_attribute(Item *item, int fd, const char *path, const struct s
...
-                               r,
-                               "Cannot set file attribute for '%s', value=0x%08x, mask=0x%08x, ignoring: %m",
+        unsigned previous, current;
+        r = chattr_full(NULL, procfs_fd, f, item->attribute_mask, &previous, &current, true);
+        if (r == -ENOANO)
+                log_warning("Cannot set file attributes for '%s', maybe due to incompatiblity in specified attributes, "
+                            "previous=0x%08x, current=0x%08x, expected=0x%08x, ignoring.",
+                            path, previous, current, (previous & ~item->attribute_mask) | (f & item->attribute_mask));
+        else if (r < 0)
+                log_full_errno(IN_SET(r, -ENOTTY, -EOPNOTSUPP) ? LOG_DEBUG : LOG_WARNING, r,
```
Comment (poettering) [inline src/tmpfiles/tmpfiles.c]: ERRNO_IS_NOT_SUPPORTED(r), maybe?

File: src/basic/chattr-util.c [hunk 2]
```diff
@@ -10,59 +10,81 @@
...
 
-        assert(p);
+                new_one = UPDATE_FLAG(current_attr, mask_one, FLAGS_SET(value, mask_one));
+                if (new_one == current_attr)
+                        continue;
 
-        if (mask == 0)
-                return 0;
+                if (ioctl(fd, FS_IOC_SETFLAGS, &new_one) >= 0)
+                        current_attr = new_one;
```
Comment (poettering) [inline src/basic/chattr-util.c]: maybe even safer would be to read the new flags mask back via FS_IOC_GETFLAGS again instead of assuming it was applied 1:1, maybe some weird fs does some internal mangling, we might never know.

**Review by poettering — APPROVED** [review]
looks great, two more ideas

**Comment by yuwata** [comment]
@poettering Thank you for your review. The above suggestions are addressed. Setting the green label.
