### PR TITLE
conf-files: several cleanups and fixlets

### LINKED ISSUE #40285: Systemd fails to issue error on when drop-in directories are unreadable
### systemd version the issue has been seen with

255.4

### Used distribution

Ubuntu

### Linux kernel version used

6.8.0-90-generic

### CPU architectures issue was seen on

ia64

### Component

journalctl, resolvectl

### Expected behaviour you didn't see

Inaccessible drop-in configuration directories (e.g. /etc/systemd/resolved.conf.d) should produce an error message in the log

### Unexpected behaviour you saw

Inaccesible drop-in configuration directories resulted in the configuration files within those directories silently ignored.

### Steps to reproduce the problem

1. On a test system, create /etc/systemd/resolved.conf.d if it isn't already present. 
2. Set the permissions for /etc/systemd/resolved.conf.d to 644 (no "x" permissions). 
3. Create a file /etc/systemd/resolved.conf.d/10-domains.conf containing:
```
[Resolve]
Domains=example.com
```
4. Run "systemctl reload-config" (not necessary, but eliminates some potential questions)
5. Run "systemctl restart systemd-resolved"
6. Observe the system log and note that no errors are reported.
7. Run "systemd-analyze cat-config /etc/systemd/resolved.conf" and note that the contents of 10-domains.conf are reported correctly.
8. Run "resolvectl status" and note that the contents of 10-domains.conf are not present. This file has not been loaded, although no errors have been reported.
9. Change the permissions for /etc/systemd/resolved.conf.d to 755. Repeat steps 4 through 8 and note that step 8 shows that the contents of 10-domains.conf are present.
  
### Further description

If optional drop-in directories, like /etc/systemd/journald.conf.d or /etc/systemd/resolved.conf.d, exist but are unreadable due to permission or other issues, systemd ignores the contents but fails to issue an error. Configuration issues become unnecessarily difficult to resolve as a result. A drop-in directory that exists but is unreadable, means that intended configurations are not being applied, and I believe failing to apply intended configuration files should be flagged as an error. Adding a log message to signal this error condition will same some of us a lot of time out in the field.

Note: Originally opened as Ubuntu bug [2137143](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2137143), where it was referred upstream.
```

### LINKED ISSUE #40313: `systemctl cat` fails on a conf file pointing to /dev/null
### systemd version the issue has been seen with

258.3

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

We experience a difference in behavior between v258.3 and v257.

Setup:
A conf file pointing to a /dev/null

```
$ ls -la /etc/systemd/system/service.d/10-timeout-abort.conf
lrwxrwxrwx 1 root root 9 Jan  9 09:06 /etc/systemd/system/service.d/10-timeout-abort.conf -> /dev/null
```

for 257 this is not a problem. Note a successful exit code:
```
$ systemctl --version
systemd 257 (257.9-1~deb13u1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +IPE +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +BTF -XKBCOMMON -UTMP +SYSVINIT +LIBARCHIVE

$ systemctl cat systemd-networkd --no-pager
# /usr/lib/systemd/system/systemd-networkd.service
... 
# /etc/systemd/system/service.d/10-timeout-abort.conf

$ echo $?
0
```

### Unexpected behaviour you saw

but 258 fails:

```
$ systemctl --version
systemd 258 (258.3-1.5.hs+fb.el9_z)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +IPE +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +BTF +XKBCOMMON +UTMP +SYSVINIT +LIBARCHIVE

$ systemctl cat systemd-networkd --no-pager
# /usr/lib/systemd/system/systemd-networkd.service
...
Failed to chase '/etc/systemd/system/service.d/10-timeout-abort.conf': File descriptor in bad state
...

$ echo $?
1
```

### Steps to reproduce the problem

```sh
Create a symlink `/etc/systemd/system/service.d/10-timeout-abort.conf` pointing to /dev/null.
```

### Additional program output to the terminal or log subsystem illustrating the issue

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #40313.
Closes #40285.

### CODE REVIEW

File: src/shared/pretty-print.c [hunk 1]
```diff
@@ -324,7 +324,20 @@ static int cat_file_by_path(const char *p, bool *newline, CatFlags flags) {
...
-        r = conf_file_new(p, /* root= */ NULL, CONF_FILES_REGULAR, &c);
+        r = conf_file_new(p, /* root= */ NULL, CONF_FILES_REGULAR | CONF_FILES_FILTER_MASKED, &c);
+        if (r == -ERFKILL) { /* masked */
+                if (newline) {
+                        if (*newline)
+                                putc('\n', stdout);
+                        *newline = true;
+                }
+
+                printf("%s# %s is masked%s\n",
```
Comment (keszybz) [inline src/shared/pretty-print.c]: This message is a bit wrong. `/etc/systemd/system/service.d/10-timeout-abort.conf is masked` is misleading, since it's `/usr/lib/systemd/system/service.d/10-timeout-abort.conf` that is masked. The file in `/etc` is the mask. This should say "… is a mask".

File: src/udev/udevadm-util.c [hunk 2]
```diff
@@ -248,7 +248,11 @@ static int search_rules_file_in_conf_dirs(const char *s, const char *root, ConfF
                         return log_oom();
 
                 _cleanup_(conf_file_freep) ConfFile *c = NULL;
-                r = conf_file_new(path, root, CONF_FILES_REGULAR, &c);
+                r = conf_file_new(path, root, CONF_FILES_REGULAR | CONF_FILES_FILTER_MASKED, &c);
+                if (r == -ERFKILL) {
+                        log_warning_errno(r, "File '%s%s' is a mask, ignoring.", empty_to_root(root), skip_leading_slash(path));
```
Comment (keszybz) [inline src/udev/udevadm-util.c:253]: … right. Esp. that here you say "is a mask".

File: src/basic/conf-files.c [hunk 3]
```diff
@@ -112,6 +112,147 @@ static int conf_file_prefix_root(ConfFile *c, const char *root) {
...
+
+        root = empty_to_root(root);
+
+        r = chaseat(rfd, path, conf_files_chase_flags(flags), &resolved_path, &fd);
+        if (r < 0)
+                return log_debug_errno(r, "Failed to chase '%s%s': %m",
+                                       root, skip_leading_slash(original_path));
+        if (r == 0) {
+                if (FLAGS_SET(flags, CONF_FILES_FILTER_MASKED_BY_SYMLINK)) {
+
```
Comment (ikruglov) [inline src/basic/conf-files.c]: spurious empty line

File: src/basic/conf-files.c [hunk 4]
```diff
@@ -261,100 +402,22 @@ static int files_add(
...
+                                de->d_name,
+                                masked,
+                                flags,
+                                &resolved_path,
+                                &fd,
+                                &st);
+                if (r == -ENOMEM)
+                        return r;
+                if (r < 0)
                         continue;
```
Comment (ikruglov) [inline src/basic/conf-files.c:436]: should you log_debug with ", ignoring" here?

**Review by ikruglov — COMMENTED** [review]
minor nits

**Review by keszybz — CHANGES_REQUESTED** [review]
LGTM.

One semi-related issue I noticed is that `systemd-analyze cat-config` is not covered by this change. I created a mask file and I see:
```console
$ SYSTEMD_LOG_LEVEL=debug build/systemd-analyze cat-config udev/rules.d
...
File '/etc/udev/rules.d/10-dm.rules' is a mask (symlink to /dev/null).
File '/usr/lib/udev/rules.d/10-dm.rules' is masked by previous entry.
Skipping file '/usr/lib/udev/rules.d/README', suffix is not '.rules'.
# /usr/lib/udev/rules.d/01-md-raid-creating.rules
...
```
At normal log level, there is no indication about the masked files. It'd be nice if we handled this the same way and printed a `# foo is masked` message at the appropriate place. But I guess this must be a completely separate code path, so we don't have to handle this here.

File: src/basic/conf-files.c (hunk 4 above)
Comment (yuwata) [reply src/basic/conf-files.c:436]: All negative errno (except for -ENOMEM) are not critical, and already logged in `conf_file_chase_and_verify()`. So, I intentionally drop logging here.

**Comment by yuwata** [comment]
> One semi-related issue I noticed is that `systemd-analyze cat-config` is not covered by this change. I created a mask file and I see:
> 
> ```
> $ SYSTEMD_LOG_LEVEL=debug build/systemd-analyze cat-config udev/rules.d
> ...
> File '/etc/udev/rules.d/10-dm.rules' is a mask (symlink to /dev/null).
> File '/usr/lib/udev/rules.d/10-dm.rules' is masked by previous entry.
> Skipping file '/usr/lib/udev/rules.d/README', suffix is not '.rules'.
> # /usr/lib/udev/rules.d/01-md-raid-creating.rules
> ...
> ```
> 
> At normal log level, there is no indication about the masked files. It'd be nice if we handled this the same way and printed a `# foo is masked` message at the appropriate place. But I guess this must be a completely separate code path, so we don't have to handle this here.

I am lazy about addressing the 'issue' now. Let's do that later.

**Comment by yuwata** [comment]
@ikruglov @keszybz Thank you for the review. Most comments are addressed. Upgrading the green label.
@gvenugo3 Thank you for the prototype of the fix. I picked your commits.

**Comment by yuwata** [comment]
I think it is better to backport the first 5 commits.
