### PR TITLE
networkd: Drop IPv6LL address when link is down.

### LINKED ISSUE #3264: systemd-networkd fails to bind to DHCPv6 client address after link up
I have a wireless link with DHCP=both enabled. (I have a DHCPv4 server, but no DHCPv6 server, but I don't think this is relevant.) When systemd-networkd starts, it successfully starts the DHCPv6 client. If I issue
`ip l set wlp3s0 down; ip l set wlp3s0 up`
I observe the following error:

```
May 15 10:57:53 laptop systemd-networkd[22129]: wlp3s0: Acquiring DHCPv6 lease
May 15 10:57:53 laptop systemd-networkd[22129]: DHCPv6 CLIENT: Failed to bind to UDP socket at address fe80::226:c6ff:fe85:a3c2: Cannot assign requested address
May 15 10:57:53 laptop systemd-networkd[22129]: wlp3s0: Could not acquire DHCPv6 lease: Cannot assign requested address
May 15 10:57:53 laptop systemd-networkd[22129]: wlp3s0: Failed
```

(The debug messages are added in #3258.)

Under strace:

```
socket(PF_INET6, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_UDP) = 15
setsockopt(15, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0
setsockopt(15, SOL_IPV6, IPV6_MULTICAST_LOOP, [0], 4) = 0
setsockopt(15, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(15, {sa_family=AF_INET6, sin6_port=htons(546),
      inet_pton(AF_INET6, "fe80::226:c6ff:fe85:a3c2", &sin6_addr),
      sin6_flowinfo=0,
      sin6_scope_id=if_nametoindex("wlp3s0")}, 28) = -1 EADDRNOTAVAIL (Cannot assign requested address)
```

This appears to be a race of some kind. If I insert `sleep(2)` before the `bind`, in `dhcp6_network_bind_udp_socket()`, the error disappears. `sleep(1)` is not enough, and the error is still present. It seems that the kernel thinks that the address is not available for a while, and indeed, the message that the address has been added is emitted about 1s after "Gained carrier":

```
[116758.557859] wpa_supplicant[24867]: wlp3s0: WPA: Key negotiation completed with 20:64:32:d7:2b:0f [PTK=CCMP GTK=TKIP]
[116758.559782] wpa_supplicant[24867]: wlp3s0: CTRL-EVENT-CONNECTED - Connection to 20:64:32:d7:2b:0f completed [id=0 id_str=]
[116758.560542] systemd-networkd[6385]: wlp3s0: Flags change: +RUNNING
[116758.562724] systemd-networkd[6385]: wlp3s0: Gained carrier
[116758.563639] systemd-networkd[6385]: wlp3s0: Acquiring IPv4 link-local address
[116758.564528] systemd-networkd[6385]: wlp3s0: Acquiring DHCPv4 lease
[116758.565370] systemd-networkd[6385]: DHCP CLIENT (0xe7cb9917): STARTED on ifindex 3
[116758.566178] systemd-networkd[6385]: wlp3s0: Acquiring DHCPv6 lease
[116758.566934] systemd-networkd[6385]: DHCPv6 CLIENT: Failed to bind to UDP socket at address fe80::226:c6ff:fe85:a3c2: Cannot assign requested address
[116758.568596] systemd-networkd[6385]: wlp3s0: Could not acquire DHCPv6 lease: Cannot assign requested address
[116758.569595] systemd-networkd[6385]: wlp3s0: Failed
[116758.571380] systemd-networkd[6385]: DHCP CLIENT (0xe7cb9917): STOPPED
[116758.572222] systemd-networkd[6385]: ACD: STOPPED
[116758.573037] systemd-networkd[6385]: NDisc CLIENT: Stop NDisc
[116759.566074] systemd-networkd[6385]: wlp3s0: Adding address: fe80::226:c6ff:fe85:a3c2/64 (valid forever)
```

So it seems we are trying to start the client to early, and we should wait for the address to appear.
@ssahani @teg

### PR DESCRIPTION
**Pull request by ssahani**
Now we are not dropping the IPv6LL address when link is down.
So next time when link is up and before kernel acquired this address
we are using the old address.

When the link is down kernel tells us that this address is no longer
valid . Let's remove this address and again when kernel tells us
that the address is added let's use it.

fixes #3264

### CODE REVIEW

File: src/network/networkd-address.c [hunk 1]
```diff
@@ -98,6 +98,9 @@ void address_free(Address *address) {
         if (address->link) {
                 set_remove(address->link->addresses, address);
                 set_remove(address->link->addresses_foreign, address);
+
+                if (in_addr_is_link_local(AF_INET6, &address->in_addr))
+                        memzero(&address->link->ipv6ll_address, sizeof(struct in6_addr));
```
Comment (keszybz) [inline src/network/networkd-address.c:103]: Yep, I can confirm that this fixes the issue in #3264.
But I don't think that `ipv6ll_address` should be nuked after any link local address is lost. For example I can do the following:

```
$ sudo ip a a dev wlp3s0 fe80::226:c6ff:fe85:a3c3/64
$ sudo ip a d dev wlp3s0 fe80::226:c6ff:fe85:a3c3/64
```

With you patch, `ipv6ll_address` will be zeroed. I think the check should use `in_addr_equal` to compare the address being removed with `ipv6ll_address` directly.

**Comment by ssahani** [comment]
Yes true. Now it's only one ipv6ll_address we are storing generated by kernel. We are not storing multiple LL address. Do you think it  should be a set and we store multiple LL address ?

**Comment by teg** [comment]
Looks good. Thanks!
