### PR TITLE
sysupdate: Support volatile-root for finding the root partition

### LINKED ISSUE #25241: systemd-sysupdate can't find root device when systemd.volatile=overlay is used
### systemd version the issue has been seen with

252

### Used distribution

Ubuntu 22.02

### Linux kernel version used

5.15.0-52-generic

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

When the root filesystem is an overlay `systemd-sysupdate list` doesn't get far enough to query the remote transfer sources. It instead fails with this error:

```
# /lib/systemd/systemd-sysupdate list --verify=no
Failed to find whole disk device for partition backing file system: No such device
```

Looking at older issues, it appears that `systemd-repart` previously had the same challenge (reference: #20610). It would appear that a similar change as #20612 could be made to `systemd-sysupdate` to check for the existence of `/run/systemd/volatile-root`.

### Steps to reproduce the problem

I ran the following from my systemd repo clone to build an Ubuntu bootable image with latest systemd, serve the image via http, and then boot the image in qemu-kvm:

```
sudo mkosi --output-split-root=yes --bootable=yes --kernel-command-line "systemd.volatile=overlay" --image-version 2 --password=root --autologin=yes --qemu-headless=yes build
sudo mkosi --image-version 2 serve &
sudo mkosi --image-version 2 --qemu-kvm=yes --qemu-headless=yes qemu
```

I next added a simple transfer conf under `/usr/lib/sysupdate.d`, enough to see the error reported above. I made a code change to sysupdate-resource.c as suggested above, re-ran the steps, and saw that was enough to get past the error.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by reubeno**
The existing logic can't find the root device in scenarios where the root has been replaced with an overlay. This adds logic to look at `/run/systemd/volatile-root` to find the original root. This is similar to what `systemd-repart` and `gpt-auto-generator` already do (references: #20612, #20578).

I tested this change by using `mkosi` to build an Ubuntu 22.04 image booted with `systemd.volatile=overlay`. Without this change, `systemd-sysupdate` can't find the root device; with this change, it gets through the logic to find the root device and proceeds to query the transfer source.

Fixes #25241 

---

_NOTE: My biggest question is whether it makes sense to minimally duplicate this logic as the PR presently does vs. extract out the `volatile-root`-checking logic in a utility function. I opted to go with the former as the logic in sysupdate intentionally looks at `/usr` and *not* `/` (_unlike `systemd-repart`_, which does) and it seemed prudent to preserve that behavior._

### CODE REVIEW

File: src/sysupdate/sysupdate-resource.c [hunk 1]
```diff
@@ -546,7 +550,19 @@ int resource_resolve_path(
...
 
-                r = get_block_device_harder("/usr/", &d);
+                r = readlink_malloc("/run/systemd/volatile-root", &orig_root);
+                if (r == -ENOENT) { /* volatile-root not found */
+                        r = get_block_device_harder("/usr/", &d);
+                } else if (r < 0)
+                        return log_error_errno(r, "Failed to read symlink /run/systemd/volatile-root: %m");
+                else {
+                        mode_t m;
+                        r = device_path_parse_major_minor(orig_root, &m, &d);
```
Comment (poettering) [inline src/sysupdate/sysupdate-resource.c]: hmm, so gpt-auto-generator uses device_path_parse_major_minor() because it runs before udev does, and thus cannot rely that the `/dev/block/x:y` symlinks are in place yet. But sysupdate doesn't run that early, hence it should not do this dance, and instead just use the path as is. i.e. use a simple `stat(orig_roog, &st)` here, that follows the symlink. And then validate that it indeed checks out to be a block device.

or in other words: I think the fact that /run/systemd/volatile-root only contains a major/minor based symlink path is not something we should rely on except where we really really have to. Whenever we can, we should just assume it's a path to a device node (or a symlink to it)

**Comment by poettering** [comment]
looks conceptually OK. but please rework to just stat() the path stored in that file, to derive major/minor, see comments.

**Comment by poettering** [comment]
> NOTE: My biggest question is whether it makes sense to minimally duplicate this logic as the PR presently does vs. extract out the `volatile-root`-checking logic in a utility function. I opted to go with the former as the logic in sysupdate intentionally looks at `/usr` and _not_ `/` (_unlike `systemd-repart`_, which does) and it seemed prudent to preserve that behavior.

I guess that is obsolete: just use stat(), and then the codepaths will look totally different anyway.

File: src/sysupdate/sysupdate-resource.c (hunk 1 above)
Comment (reubeno) [reply src/sysupdate/sysupdate-resource.c]: Thanks for the feedback -- this was very helpful. I've pushed an update that aims to address your concerns.
