### PR TITLE
networkd: Add back static routes after DHCPv4 lease expires.

### LINKED ISSUE #12426: UseRoutes=false still leads to dropped routes on dhcp renew
**systemd version the issue has been seen with**
> systemd 242 (242.0-3-arch)

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > If UseRoutes=false static routes should be stable on dhcp ip refresh

**Unexpected behaviour you saw**
 > The static route is working but as soon as the dhcp lease expires and a new lease is acquired the static route is dropped

**Steps to reproduce the problem**
> Set a static route on a dhcp managed interface, set useroutes=false, wait for dhcp renew

**My config on the interface**
The host has 1 nic, a vlan vnic (with the default gateway on it) and a bridge for kvm as well as other local network stuff. The first route is to have a route to the private network, the second is to get announcements of a upnp streaming server to the correct interface.
This config used to work until arch updated from systemd 241.67-1 to 242.0-3. 

> [Match]
> Name=br0
> 
> [Network]
> DHCP=ipv4
> Domains=my.domain
> LinkLocalAddressing=no
> IPv6AcceptRA=no
> BindCarrier=eno1
> 
> [DHCP]
> UseRoutes=false
> SendHostname=true
> Hostname=my-hostname
> ClientIdentifier=mac
> 
> [Route]
> Destination=192.168.1.0/24
> Scope=link
> 
> [Route]
> Destination=239.255.255.250
> Scope=link

### PR DESCRIPTION
**Pull request by ssahani**
1. When the DHCPv4 lease expires kernel removes the route. So add it back
when we gain lease again.

Closes #12426

2. When UseRoutes=false do not remove router

### CODE REVIEW

File: src/network/networkd-address.c [hunk 1]
```diff
@@ -479,7 +479,7 @@ int address_remove(
                 return log_link_error_errno(link, r, "Could not append IFA_LOCAL attribute: %m");
 
         r = netlink_call_async(link->manager->rtnl, NULL, req,
-                               callback ?: address_remove_handler,
+                               callback ? callback: address_remove_handler,
```
Comment (yuwata) [inline src/network/networkd-address.c]: The change is completely equivalent, and we use the shorter version. So, please drop this.

**Comment by ssahani** [comment]
updated thanks.
