### PR TITLE
networkd: Fix Link up

### LINKED ISSUE #12504: networkd: throwing invalid argument while bringing up the interface
There seems to be a bug introduced. first time networkd not able to bring the interface and second time it's able to 

**Steps to reproduce the problem**
````
dummy-test: Adding route: dst: fe80::cc89:aeff:fe07:bf/128, src: n/a, gw: n/a, prefsrc: n/a
dummy-test: Could not bring up interface: Invalid argument <====================
vxlan-test: Link state is up-to-date
```

dmesg
```
[25310.931434] A link change request failed with some changes committed already. Interface dummy-test may have been left with an inconsistent configuration, please check.
[25310.943688] A link change request failed with some changes committed already. Interface vxlan-test may have been left with an inconsistent configuration, please check.
[25359.056725] A link change request failed with some changes committed already. Interface dummy-test may have been left with an inconsistent configuration, please check.
[25359.069276] A link change request failed with some changes committed already. Interface vxlan-test may have been left with an inconsistent configuration, please check.
[25414.723874] A link change request failed with some changes committed already. Interface dummy-test may have been left with an inconsistent configuration, please check.
[25414.735969] A link change request failed with some changes committed already. Interface vxlan-test may have been left with an inconsistent configuration, please check.
[25583.428566] A link change request failed with some changes committed already. Interface dummy-test may have been left with an inconsistent configuration, please check.
[25583.442321] A link change request failed with some changes committed already. Interface vxlan-test may have been left with an inconsistent configuration, please check.
[25631.842157] A link change request failed with some changes committed already. Interface dummy-test may have been left with an inconsistent configuration, please check.
[25631.852183] A link change request failed with some changes committed already. Interface vxlan-test may have been left with an inconsistent configuration, please check.
[25662.570760] A link change request failed with some changes committed already. Interface dummy-test may have been left with an inconsistent configuration, please check.
[25662.572175] A link change request failed with some changes committed already. Interface vxlan-test may have been left with an inconsistent configuration, please check.
[25681.015688] A link change request failed with some changes committed already. Interface dummy-test may have been left with an inconsistent configuration, please check.
[25681.028508] A link change request failed with some changes committed already. Interface vxlan-test may have been left with an inconsistent configuration, please check.
[25740.659475] A link change request failed with some changes committed already. Interface dummy-test may have been left with an inconsistent configuration, please check.
[25740.669263] A link change request failed with some changes committed already. Interface vxlan-test may have been left with an inconsistent configuration, please check.
```

### PR DESCRIPTION
**Pull request by ssahani**
Fill up IFLA_INET6_ADDR_GEN_MODE while we do link_up.

```
dummy-test: Adding route: dst: fe80::cc89:aeff:fe07:bf/128, src: n/a, gw: n/a, prefsrc: n/a
dummy-test: Could not bring up interface: Invalid argument <====================
vxlan-test: Link state is up-to-date
```

After reading the kernel code when we do a link up
```
net/core/rtnetlink.c
IFLA_AF_SPEC
 af_ops->set_link_af(dev, af);
  inet6_set_link_af
   if (tb[IFLA_INET6_ADDR_GEN_MODE])
             Here it looks for IFLA_INET6_ADDR_GEN_MODE
```

Since link up we don't filling up that it's failing.

Closes #12504 and possible same issue as per #10881

it seems ```link_configure_addrgen_mode``` reductant now.

### CODE REVIEW

**Comment by ssahani** [comment]
@yuwata @keszybz PTAL

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -2047,6 +2048,15 @@ static int link_up(Link *link) {
                                 return log_link_error_errno(link, r, "Could not append IFLA_INET6_TOKEN: %m");
                 }
 
+                if (sysctl_read_ip_property(AF_INET6, link->ifname, "stable_secret", NULL) < 0)
+                        ipv6ll_mode = IN6_ADDR_GEN_MODE_EUI64;
```
Comment (yuwata) [inline src/network/networkd-link.c:2056]: Please import the comment from `link_configure_addrgen_mode()`.

File: src/network/networkd-link.c [hunk 2]
```diff
@@ -2001,6 +2001,7 @@ static int link_up_handler(sd_netlink *rtnl, sd_netlink_message *m, Link *link)
 
 static int link_up(Link *link) {
         _cleanup_(sd_netlink_message_unrefp) sd_netlink_message *req = NULL;
+        uint8_t ipv6ll_mode;
```
Comment (yuwata) [inline src/network/networkd-link.c]: Not a matter, but I'd like to move the variable definition just after the line `if (link_ipv6_enabled(link)) {`.

**Comment by ssahani** [comment]
updated PTAL @yuwata . Thanks for review.

**Comment by yuwata** [comment]
Hmm, test_link_local_addressing fails...

**Comment by yuwata** [comment]
Looks nice. Still `link_configure_addrgen_mode()` is necessary?

**Comment by ssahani** [comment]
yes seems to be . It bit to handle kernel.  when ```socket_ipv6_is_supported``` is there we disabling the LL address with the kernel but in later when LinkLocal=no we not getting into the if part because of  ```link_ipv6_enabled``` is coming as false. But it would be nice we should unify the common code in the later PR

**Comment by ssahani** [comment]
CI failure seems unrelated 
```
build-login          PASS
boot-and-services    FAIL non-zero exit status 1
udev                 PASS
root-unittests       PASS
```

**Comment by yuwata** [comment]
(BTW, I think this is a bug of `inet6_set_link_af()`. It does not accept an empty `IFLA_AF_SPEC/AF_INET6` container. E.g., `inet_set_link_af()` accepts an empty container.)

**Comment by ssahani** [comment]
I think the  In the code of ```IFF_UP``` --->```IFLA_INET6_ADDR_GEN_MODE``` added or something changed. Previously we were doing that and it was working . We can actually make this configurable 

```
enum in6_addr_gen_mode {
        IN6_ADDR_GEN_MODE_EUI64,
        IN6_ADDR_GEN_MODE_NONE,
        IN6_ADDR_GEN_MODE_STABLE_PRIVACY,
        IN6_ADDR_GEN_MODE_RANDOM,
};
```

If you interested or I will add it.

**Comment by yuwata** [comment]
I noticed 0e2fdb83bb5e22047e0c7cc058b415d0e93f02cf did that. This PR partially revert the commit :-p

**Comment by yuwata** [comment]
> We can actually make this configurable

I am not sure the usecase... Let's do that when someone requests.
