### PR TITLE
network: skip .network files earlier when conditions do not match system environment

### LINKED ISSUE #4211: systemd-networkd: attempts to configure bridge despite non-[Match] in container
### Submission type
- Bug report
### systemd version the issue has been seen with

> 231
### Used distribution

> _Host:_ Debian 8.5, systemd-215, Kernel 4.1.15 (Hetzner Rescue System)
> _Guest:_ Gentoo, systemd-231 (systemd-nspawn container)
### In case of bug report: Expected behaviour you didn't see

> Running a systemd-nspawn container to bootstrap a server's OS.
> While running as container for bootstrapping purposes, a different network configuration should be used as the "productive" one, which should be achieved by corresponding `[Match]` criteria in `systemd-networkd`'s configuration
> Content in `/etc/systemd/network/00-vmbridge.network`:
> 
> ``` INI
> [Match]
> Virtualization=!systemd-nspawn
> Name=public
> 
> [Network]
> Description=A bridge providing connectivity for the VMs
> Bridge=vmbridge
> ```
> 
> I'd expect this configuration to be completely ignored, as in my container there's nether an interface named `public` nor does the `Virtualization=` condition produce a `true` result.
> 
> Despite this, `systemd-nspawn` logs this error on startup:
> 
> ```
> [/etc/systemd/network/00-vmbridge.network:8] Bridge could not be found, ignoring assignment: vmbridge
> ```
### In case of bug report: Unexpected behaviour you saw

> `systemd-nspawn` ignoring the `[Match]` criteria of a `*.network` file and trying to apply a `Bridge=` configuration nonetheless.
### In case of bug report: Steps to reproduce the problem

> - Create the file `/etc/systemd/network/00-vmbridge.network`:
>   
>   ``` INI
>   [Match]
>   Virtualization=!systemd-nspawn
>   Name=public
>   
>   [Network]
>   Description=A bridge providing connectivity for the VMs
>   Bridge=vmbridge
>   ```
> - Execute `systemctl restart systemd-networkd`
> - Execute `systemctl status systemd-networkd` or manually check it's journal
> - The error (red highlighted) `[/etc/systemd/network/00-vmbridge.network:8] Bridge could not be found, ignoring assignment: vmbridge` is logged

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #4211.

### CODE REVIEW

File: src/network/networkd-network.c [hunk 1]
```diff
@@ -204,6 +204,28 @@ int network_load_one(Manager *manager, const char *filename) {
...
 
+        network = new0(Network, 1);
+        if (!network)
+                return log_oom();
+
+        r = config_parse_many(filename, NETWORK_DIRS, dropin_dirname,
+                              "Match\0",
+                              config_item_perf_lookup, network_network_gperf_lookup,
+                              CONFIG_PARSE_WARN | CONFIG_PARSE_RELAXED, network);
+        if (r < 0)
```
Comment (poettering) [inline src/network/networkd-network.c]: hmm, what's the goal here. this means we'll parse all configuration files twice, opening them twice for that. I don't grok why this would really be desirable?

Reading everything twice sounds less than ideal to me...

Is this just done to avoid slightly confusing log msgs?

**Comment by yuwata** [comment]
OK. Another approach is used now. PTAL.

**Comment by keszybz** [comment]
```
autopkgtest [01:41:55]: test hostnamed: [-----------------------
original hostname: autopkgtest
FAIL: expected: '' actual: 'Could not set property: Access denied'
autopkgtest [01:41:56]: test hostnamed: -----------------------]
```
No idea what is going on here. I'll restart the CI.

This looks very reasonable. I'll set the flag, but let's wait for @poettering's review too.

**Comment by yuwata** [comment]
I think the CI failure is already fixed by #11792.

File: src/network/networkd-network-gperf.gperf [hunk 2]
```diff
@@ -38,15 +38,15 @@ Link.AllMulticast,                      config_parse_tristate,
...
-Network.VLAN,                           config_parse_netdev,                            0,                             0
-Network.MACVLAN,                        config_parse_netdev,                            0,                             0
-Network.MACVTAP,                        config_parse_netdev,                            0,                             0
-Network.IPVLAN,                         config_parse_netdev,                            0,                             0
-Network.VXLAN,                          config_parse_netdev,                            0,                             0
-Network.Tunnel,                         config_parse_tunnel,                            0,                             0
-Network.VRF,                            config_parse_netdev,                            0,                             0
+Network.Bridge,                         config_parse_string,                            0,                             offsetof(Network, bridge_name)
+Network.Bond,                           config_parse_string,                            0,                             offsetof(Network, bond_name)
```
Comment (poettering) [inline src/network/networkd-network-gperf.gperf]: these two should use config_parse_ifname(), no?

File: src/network/networkd-network-gperf.gperf [hunk 3]
```diff
@@ -38,15 +38,15 @@ Link.AllMulticast,                      config_parse_tristate,
...
+Network.VLAN,                           config_parse_stacked_netdev,                    0,                             offsetof(Network, stacked_netdev_names)
+Network.MACVLAN,                        config_parse_stacked_netdev,                    0,                             offsetof(Network, stacked_netdev_names)
+Network.MACVTAP,                        config_parse_stacked_netdev,                    0,                             offsetof(Network, stacked_netdev_names)
+Network.IPVLAN,                         config_parse_stacked_netdev,                    0,                             offsetof(Network, stacked_netdev_names)
+Network.VXLAN,                          config_parse_stacked_netdev,                    0,                             offsetof(Network, stacked_netdev_names)
+Network.Tunnel,                         config_parse_stacked_netdev,                    _NETDEV_KIND_TUNNEL,           offsetof(Network, stacked_netdev_names)
+Network.VRF,                            config_parse_string,                            0,                             offsetof(Network, vrf_name)
```
Comment (poettering) [inline src/network/networkd-network-gperf.gperf]: dito

File: src/network/networkd-network.c [hunk 4]
```diff
@@ -97,13 +97,108 @@ void network_apply_anonymize_if_set(Network *network) {
...
+        (void) network_resolve_netdev_one(network, network->bond_name, NETDEV_KIND_BOND, &network->bond);
+        (void) network_resolve_netdev_one(network, network->bridge_name, NETDEV_KIND_BRIDGE, &network->bridge);
+        (void) network_resolve_netdev_one(network, network->vrf_name, NETDEV_KIND_VRF, &network->vrf);
+        (void) network_resolve_stacked_netdevs(network);
+
+        /* Free unnecessary entries. */
+        network->bond_name = mfree(network->bond_name);
+        network->bridge_name = mfree(network->bridge_name);
+        network->vrf_name = mfree(network->vrf_name);
+        network->stacked_netdev_names = hashmap_free_free_key(network->stacked_netdev_names);
```
Comment (poettering) [inline src/network/networkd-network.c:201]: i probably wouldn#t bother freeing these, but ok...

File: src/network/networkd-network.c [hunk 5]
```diff
@@ -583,84 +681,51 @@ int config_parse_netdev(const char *unit,
...
-        case NETDEV_KIND_VLAN:
-        case NETDEV_KIND_MACVLAN:
-        case NETDEV_KIND_MACVTAP:
-        case NETDEV_KIND_IPVLAN:
-        case NETDEV_KIND_VXLAN:
-        case NETDEV_KIND_VCAN:
-                r = hashmap_ensure_allocated(&network->stacked_netdevs, &string_hash_ops);
-                if (r < 0)
-                        return log_oom();
+        name = strdup(rvalue);
```
Comment (poettering) [inline src/network/networkd-network.c:720]: check for validity with ifname_is_valid() first?

**Comment by poettering** [comment]
Looks great to me, but I'd like to see some early ifname string validation in place, see above.

**Comment by yuwata** [comment]
Updated.
- `config_parse_string()` -> `config_parse_ifname()`
- add `ifname_valid()` in `config_parse_tunnel()`.

BTW, `ifname_valid()` should be renamed to `ifname_is_valid()`, I think.

**Comment by keszybz** [comment]
Both bionic-i386 and bionic-s390x fail with boot-smoke ("Failed to resolve group 'render'").

**Comment by poettering** [comment]
> BTW, `ifname_valid()` should be renamed to `ifname_is_valid()`, I think.

yeah, we don't follow a strict naming regime there, but probably should indeed.
