### PR TITLE
systemctl: edit: rephrase edit markers to avoid misunderstanding

### LINKED ISSUE #25856: Clarify `systemctl edit` override message
### systemd version the issue has been seen with

systemd 252.4-2

### Used distribution

Arch Linux

### Linux kernel version used

6.1.1-arch1-1

### CPU architectures issue was seen on

aarch64

### Component

systemctl

### Expected behaviour you didn't see

The `.#override...` file should state, when not using `systemctl edit --force` where this is actually true, that (roughly):

"Any changed options between here and the comment below will change those options in the resulting file"

### Unexpected behaviour you saw

The `.#override...` file created by `systemctl edit` states:

"Anything between here and the comment below will become the new contents of the file" as well as "Lines below this comment will be discarded".

I read this to mean that any options I don't specify in the override will be missing in the resulting unit, but this isn't the case, and instead you only need to specify the options you want to change.

### Steps to reproduce the problem

Run `systemctl edit` on any unit and see the default override message.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by YHNdnzj**
Closes #25856

### CODE REVIEW

**Comment by poettering** [comment]
The suggested change doesn't look right to me. "systemctl edit" creates a drop-in file only, and the stuff between the two markers indeed will become the full new file contents -- for that drop-in. With your rewording you appear to suggest that the drop-in will contain more text, but it really won't, it's all there's going to be.

I am pretty sure we can word this better, i.e. somehow emphasize that this is about the *drop-in* file only, and we'll replace that one as whole, but that the original unit file will remain intact.

**Comment by poettering** [comment]
that sounds like OK wording to me

File: src/systemctl/systemctl-edit.c [hunk 1]
```diff
@@ -19,8 +19,8 @@
 #include "terminal-util.h"
 #include "tmpfile-util.h"
 
-#define EDIT_MARKER_START "### Anything between here and the comment below will become the new contents of the file"
-#define EDIT_MARKER_END "### Lines below this comment will be discarded"
+#define EDIT_MARKER_START "### Anything between here and the comment below will become the content of the drop-in file"
```
Comment (poettering) [inline src/systemctl/systemctl-edit.c]: content → contents

**Comment by poettering** [comment]
thanks
