### PR TITLE
pass service env vars to PAM session hooks when using PAMName=

### LINKED ISSUE #3050: pass service env vars to PAM session hooks when using PAMName=
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229, but probably present for a few years already

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> Some PAM modules, notably pam_systemd, are sensitive to environment variables. I would expect variables specified using Environment= in units that use PAMName=/User= to be available to the PAM module being loaded.
### In case of bug report: Unexpected behaviour you saw

> Currently, systemd does not set the variables specified in Environment= before calling pam_start in src/core/execute.c:setup_pam. As a result it is not possible to influence the behavior of PAM modules through environment variables.
### In case of bug report: Steps to reproduce the problem

> I considered adding `Environment=XDG_SESSION_TYPE=x11` to [xlogin](https://github.com/joukewitteveen/xlogin/blob/master/xlogin%40.service.in) so that `logind` would get to know the proper session type. However, `loginctl` shows the default session type ("tty").

### PR DESCRIPTION
**Pull request by joukewitteveen**
This fixes #3050.

### CODE REVIEW

File: src/core/execute.c [hunk 1]
```diff
@@ -861,6 +867,9 @@ static int setup_pam(
                 pam_code = PAM_BUF_ERR;
                 goto fail;
         }
+        strv_free(*env);
+        *env = e;
+        e = NULL;
```
Comment (poettering) [inline src/core/execute.c]: what's the rationale for moving this up? we generally try to avoid clobbering call-by-ref parameters on failure. Also see CODING_STYLE. Changing the passed in parameter like you are doing here doesn't look right hence.

**Comment by poettering** [comment]
found one nit, rest looks good.

**Comment by joukewitteveen** [comment]
Sorry. Corrected.

File: src/core/execute.c [hunk 2]
```diff
@@ -846,6 +846,12 @@ static int setup_pam(
                         goto fail;
         }
 
+        STRV_FOREACH(e, *env) {
+                pam_code = pam_putenv(handle, *e);
+                if (pam_code != PAM_SUCCESS)
+                        goto fail;
```
Comment (evverx) [inline src/core/execute.c:852]: Hm, why do you use `e` here?
`if (pam_code != PAM_SUCCESS)` we try to [`strv_free(e)`](https://github.com/systemd/systemd/blob/daf3aaeebfc991a337af0372206257dc204b25de/src/core/execute.c#L994). And

```
                #1  0x00007fe46ab70a5a abort (libc.so.6)
                #2  0x00007fe46abafdc0 __libc_message (libc.so.6)
                #3  0x00007fe46abb856a _int_free (libc.so.6)
                #4  0x00007fe46abbbacc __libc_free (libc.so.6)
                #5  0x00007fe46c0851f4 strv_clear (libsystemd-shared-230.so)
                #6  0x00007fe46c08522d strv_free (libsystemd-shared-230.so)
                #7  0x000055cc83b9db5a strv_freep (systemd)
                #8  0x000055cc83ba3adb exec_child (systemd)
                #9  0x000055cc83ba40b2 exec_spawn (systemd)
                #10 0x000055cc83b838d2 service_spawn (systemd)
                #11 0x000055cc83b84e89 service_enter_start (systemd)
                #12 0x000055cc83b85170 service_enter_start_pre (systemd)
                #13 0x000055cc83b85f73 service_start (systemd)
                #14 0x000055cc83be1544 unit_start (systemd)
                #15 0x000055cc83bec8ab job_perform_on_unit (systemd)
                #16 0x000055cc83becbec job_run_and_invalidate (systemd)
                #17 0x000055cc83b625b1 manager_dispatch_run_queue (systemd)
                #18 0x00007fe46c14a784 source_dispatch (libsystemd-shared-230.so)
                #19 0x00007fe46c14b95e sd_event_dispatch (libsystemd-shared-230.so)
                #20 0x00007fe46c14bd93 sd_event_run (libsystemd-shared-230.so)
                #21 0x000055cc83b65116 manager_loop (systemd)
                #22 0x000055cc83b5baab main (systemd)
                #23 0x00007fe46ab5a731 __libc_start_main (libc.so.6)
                #24 0x000055cc83b53a19 _start (systemd)
```

Comment (evverx) [inline src/core/execute.c:852]: Another backtrace https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/i386/s/systemd-upstream/20160706_172520@/log.gz

```
Jul 06 17:24:49 adt systemd[1648]: PAM _pam_load_conf_file: unable to open /etc/pam.d/system-auth
Jul 06 17:24:49 adt systemd[1648]: *** Error in `(systemd)': free(): invalid pointer: 0x8158a75c ***
Jul 06 17:24:49 adt systemd[1648]: ======= Backtrace: =========
Jul 06 17:24:49 adt systemd[1648]: /lib/i386-linux-gnu/libc.so.6(+0x67257)[0xb7281257]
Jul 06 17:24:49 adt systemd[1648]: /lib/i386-linux-gnu/libc.so.6(+0x6d577)[0xb7287577]
Jul 06 17:24:49 adt systemd[1648]: /lib/i386-linux-gnu/libc.so.6(+0x6dd31)[0xb7287d31]
Jul 06 17:24:49 adt systemd[1648]: /lib/systemd/libsystemd-shared-230.so(strv_free+0x2b)[0xb754f31b]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x599be)[0x800c19be]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x5bf11)[0x800c3f11]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x5d34f)[0x800c534f]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x3f8bc)[0x800a78bc]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x40d4e)[0x800a8d4e]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x40fef)[0x800a8fef]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x41cb5)[0x800a9cb5]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x95659)[0x800fd659]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x9fc0a)[0x80107c0a]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x9ff0e)[0x80107f0e]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x222fe)[0x8008a2fe]
Jul 06 17:24:49 adt systemd[1648]: /lib/systemd/libsystemd-shared-230.so(+0x104f97)[0xb760af97]
Jul 06 17:24:49 adt systemd[1648]: /lib/systemd/libsystemd-shared-230.so(sd_event_dispatch+0x1b2)[0xb760c158]
Jul 06 17:24:49 adt systemd[1648]: /lib/systemd/libsystemd-shared-230.so(sd_event_run+0x2dd)[0xb760c599]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x249c2)[0x8008c9c2]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x1bfe8)[0x80083fe8]
Jul 06 17:24:49 adt systemd[1648]: /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf7)[0xb7232637]
Jul 06 17:24:49 adt systemd[1648]: (systemd)(+0x14f40)[0x8007cf40]
```

Comment (joukewitteveen) [inline src/core/execute.c:852]: You are right, using `e` is problematic, as it is assumed in the `fail:` block that `e` is `NULL`-terminated, which it is not in our case. Shall I just introduce a new variable and submit a pull request?
Alternatively (and easier) we can set `e = NULL` before jumping to fail. #3680

Edit: on closer inspection, our `e` is `NULL`-terminated (it is a pointer into a vector returned by strv_env_merge) and should not be able to cause this bug.

Comment (joukewitteveen) [inline src/core/execute.c:852]: Is there any way to find out what `*e` (`var=value`) caused `pam_putenv` to fail?

Comment (evverx) [inline src/core/execute.c:852]: > Edit: on closer inspection, our e is NULL-terminated (it is a pointer into a vector returned by strv_env_merge) and should not be able to cause this bug.

Well, we `strv_free(accum_env)` twice:
- https://github.com/joukewitteveen/systemd/blob/daf3aaeebfc991a337af0372206257dc204b25de/src/core/execute.c#L994
- https://github.com/joukewitteveen/systemd/blob/daf3aaeebfc991a337af0372206257dc204b25de/src/core/execute.c#L1787 (note `_cleanup_strv_free_` [there](https://github.com/joukewitteveen/systemd/blob/daf3aaeebfc991a337af0372206257dc204b25de/src/core/execute.c#L1473))

> #3680 

Thanks! I'll take a look.
