### PR TITLE
networkctl: status command also shows logs of networkd

### LINKED ISSUE #14050: make "networkctl status" show logs related to the specified iface
**systemd version the issue has been seen with**
> systemd 243

**Used distribution**
 > NixOS 19.09 and NixOS master

**Expected behaviour you didn't see**
 > systemd-networkd should listen on `67/udp`.

**Unexpected behaviour you saw**
 > systemd-networkd did not listen on `67/udp`

With hindsight, this systemd-networkd warning is relevant:
> systemd-networkd[489]: Failed to determine timezone: No such file or directory

**Steps to reproduce the problem**
```
[Match]
Name=eth0

[Network]
DHCPServer=true
Address=10.0.0.1/24

[DHCPServer]
DNS=10.0.0.1
PoolOffset=100
```

https://github.com/NixOS/nixpkgs/pull/73505 has an automated test to reproduce this, executable via https://nixos.org/nixos/manual/index.html#sec-running-nixos-tests-interactively .

**Mechanism**

In systemd 242, `systemd` would create `/etc/localtime` and `systemd-networkd` would grab timezone info from `/etc/localtime` as part of being a DHCP server. Everything is good so far.

systemd 243 introduced https://github.com/systemd/systemd/commit/09bef967d9cacb95bafab0882606cc3a57ac324e, which removed the creation of `/etc/localtime`, and thus `systemd-networkd` [fails to get timezone data](https://github.com/systemd/systemd/blob/efb536d0cbe2e58f80e501d19999928c75e08f6a/src/basic/time-util.c#L1393-L1395), and thus [fails to start a DHCP server](https://github.com/systemd/systemd/blob/efb536d0cbe2e58f80e501d19999928c75e08f6a/src/network/networkd-dhcp-server.c#L223-L225). In particular, not listening on `67/udp`.

https://github.com/systemd/systemd/commit/bc9ecd484f1ebfe0de8b567c90f6cd867fbd5894 will fix this by falling back to UTC if `/etc/localtime` does not exist.

**Workaround**
Set `EmitTimezone=false` under `[DHCPServer]`.

**Context**

Tracked in NixOS at https://github.com/NixOS/nixpkgs/issues/73504 .

### PR DESCRIPTION
**Pull request by yuwata**
Closes #14050.

### CODE REVIEW

File: src/network/networkctl.c [hunk 1]
```diff
@@ -1067,7 +1071,95 @@ static int dump_statistics(Table *table, const LinkInfo *info) {
...
+                        return log_error_errno(r, "Failed to add link matches: %m");
+        } else {
+                r = add_matches_for_unit(j, "systemd-networkd.service");
+                if (r < 0)
+                        return log_error_errno(r, "Failed to add unit matches: %m");
+        }
+
+
+
+        return show_journal(
```
Comment (poettering) [inline src/network/networkctl.c:1126]: spurious newlines

Comment (yuwata) [reply src/network/networkctl.c:1126]: Thanks. Dropped.

File: src/network/networkctl.c [hunk 2]
```diff
@@ -1067,7 +1071,93 @@ static int dump_statistics(Table *table, const LinkInfo *info) {
...
+                       (r = sd_journal_add_match(j, "_SYSTEMD_UNIT=systemd-networkd.service", 0)) ||
+                       (r = sd_journal_add_match(j, m, 0))
+                );
+                if (r < 0)
+                        return log_error_errno(r, "Failed to add link matches: %m");
+        } else {
+                r = add_matches_for_unit(j, "systemd-networkd.service");
+                if (r < 0)
+                        return log_error_errno(r, "Failed to add unit matches: %m");
+        }
```
Comment (poettering) [inline src/network/networkctl.c:1124]: hmm, I think we should simplify this, and just log everything matching, without limiting things to networkd or so...

i.e. networkctl should show *everything* about the interfcae, regardless who logs that. For example, if openvpn or openvswitch or so manage an iface together with networkd we should show the output of all of them, interleaved with networkd's output (well, only if they are willing to augment their logs with journald metadata). i.e. let's be comphrensive here: if people specify INTERFACE=, then that's what counts, regardless who does it... 

(Admittedly INTERFACE is a bit generically named, a property of NETIF= or so IFNAME= or so might be better, maybe we can still get away with changing that?)

(and we probably should also show logs of `_KERNEL_DEVICE=n4711` when called for an interface with ifindex 4711, so that the kernel output tagged properly shows up too)

**Comment by yuwata** [comment]
@poettering Thank you for the comment. I've force-pushed the revised commits. PTAL.

File: src/network/netdev/netdev.h [hunk 3]
```diff
@@ -222,7 +222,7 @@ const struct ConfigPerfItem* network_netdev_gperf_lookup(const char *key, GPERF_
 #define log_netdev_full(netdev, level, error, ...)                      \
         ({                                                              \
                 const NetDev *_n = (netdev);                            \
-                _n ? log_object_internal(level, error, PROJECT_FILE, __LINE__, __func__, "INTERFACE=", _n->ifname, NULL, NULL, ##__VA_ARGS__) : \
+                _n ? log_object_internal(level, error, PROJECT_FILE, __LINE__, __func__, "NETIF=", _n->ifname, NULL, NULL, ##__VA_ARGS__) : \
```
Comment (keszybz) [inline src/network/netdev/netdev.h]: INTERFACE= is the name used by the kernel, so I'm not sure if we should change it.

I'm not too happy about the backwards compat break here. 
The attribute has been set for many years (since f2341e0a87cab1558c84c933956e9181d5fb6c52?), and I think we should try to provide better transition if the name is changed:
1. set both attributes, and warn in NEWS that INTERFACE= is deprecated and will be removed in a few releases.
2. look for both INTERFACE= and IFNAME= when matching messages.

But looking at https://codesearch.debian.net/search?q=\bINTERFACE%3D&literal=0, INTERFACE= is used in so many places with this particular meaning that my preference would be not to change it at all. If we were starting from scratch, we'd probably use a better name, but changing causes more problems than the small clarification we get.

File: src/network/networkd-routing-policy-rule.c [hunk 4]
```diff
@@ -461,102 +461,103 @@ int routing_policy_rule_configure(RoutingPolicyRule *rule, Link *link, link_netl
                 (void) in_addr_to_string(rule->family, &rule->from, &from);
                 (void) in_addr_to_string(rule->family, &rule->to, &to);
 
-                log_debug("Configuring routing policy rule: %s/%u -> %s/%u, iif: %s, oif: %s, table: %u",
+                log_link_debug(link,
+                               "Configuring routing policy rule: %s/%u -> %s/%u, iif: %s, oif: %s, table: %u",
                           from, rule->from_prefixlen, to, rule->to_prefixlen, strna(rule->iif), strna(rule->oif), rule->table);
```
Comment (keszybz) [inline src/network/networkd-routing-policy-rule.c]: Indentation.

File: src/network/netdev/netdev.h (hunk 3 above)
Comment (poettering) [reply src/network/netdev/netdev.h]: ok, then let's stick to INTERFACE=

Comment (yuwata) [reply src/network/netdev/netdev.h]: OK. Renaming part is dropped.

File: src/network/networkd-routing-policy-rule.c (hunk 4 above)
Comment (yuwata) [reply src/network/networkd-routing-policy-rule.c]: Thanks. Fixed.

**Comment by keszybz** [comment]
Looks great now, thanks!
