### PR TITLE
network: disable kernel creating prefix route when RouteTable= is set

### LINKED ISSUE #8726: systemd-networkd DHCP client RouteTable ignored
### Submission type
 - Bug report

### systemd version the issue has been seen with

238

### Used distribution

Fedora

### In case of bug report: Expected behaviour you didn't see

[root@gw1 ~]# ip route show table main
default via 192.168.22.1 dev elf0 proto dhcp src 192.168.22.63 metric 1024 
192.168.22.0/24 dev elf0 proto kernel scope link src 192.168.22.63 
192.168.22.1 dev elf0 proto dhcp scope link src 192.168.22.63 metric 1024 
192.168.42.0/24 dev lan0 proto kernel scope link src 192.168.42.1 
[root@gw1 ~]# ip route show table 211
default via 192.168.22.1 dev elf1 proto dhcp src 192.168.22.84 metric 1024 
**192.168.22.0/24 dev elf1 proto kernel scope link src 192.168.22.84** 
192.168.22.1 dev elf1 proto dhcp scope link src 192.168.22.84 metric 1024 
192.168.42.0/24 dev lan0 proto kernel scope link src 192.168.42.1 

### In case of bug report: Unexpected behaviour you saw

[root@gw1 ~]# ip route show table main
default via 192.168.22.1 dev elf0 proto dhcp src 192.168.22.63 metric 1024 
192.168.22.0/24 dev elf0 proto kernel scope link src 192.168.22.63 
**192.168.22.0/24 dev elf1 proto kernel scope link src 192.168.22.84** 
192.168.22.1 dev elf0 proto dhcp scope link src 192.168.22.63 metric 1024 
192.168.42.0/24 dev lan0 proto kernel scope link src 192.168.42.1 
[root@gw1 ~]# ip route show table 211
default via 192.168.22.1 dev elf1 proto dhcp src 192.168.22.84 metric 1024 
192.168.22.1 dev elf1 proto dhcp scope link src 192.168.22.84 metric 1024 
192.168.42.0/24 dev lan0 proto kernel scope link src 192.168.42.1 

### In case of bug report: Steps to reproduce the problem

With multiple interfaces receiving IP from DHCP server

#### First interface .network
[Match]
Name=elf0

[Network]
DHCP=yes

#### Second interface .network
[Match]
Name=elf1

[Network]
DHCP=ipv4
IPForward=true
IPv6AcceptRA=false

[DHCP]
RouteTable=211

### PR DESCRIPTION
**Pull request by yuwata**
Closes #8726.

cc @ssahani.

### CODE REVIEW

**Comment by ssahani** [comment]
Hmm if it's wrong why kernel even allowing this?

**Comment by yuwata** [comment]
@ssahani When configuring address, kernel does not know whether `RouteTable=` is specified or not. So, when `RouteTable=` is specified, we need to set `noprefixroute` flag and configure the route with correct route table.

**Comment by ssahani** [comment]
I posted a alternative fix. https://github.com/systemd/systemd/pull/12831
@yuwata could you verify this fixes it.

**Comment by ssahani** [comment]
I looked at the kernel code. When we add the addresses this route gets added. And while adding this route it try to figure out from the config which table to use .

precisely here https://elixir.bootlin.com/linux/latest/source/net/ipv4/fib_frontend.c#L1030 . I now testing this PR.

**Comment by yuwata** [comment]
@ssahani Thanks. BTW, I have no idea why the CentOS CI dislike this PR...

**Comment by yuwata** [comment]
@ssahani I may understand why the CI fails with the previous version. The prefix route must be configured earlier than other routes.

**Comment by poettering** [comment]
Patch looks good to me, But I am not sure I fully grok this all. Good to merge by me, but maybe @ssahani has to say something about this? Also, maybe repush to retrigger CI?

**Comment by yuwata** [comment]
Hmm... Still CentOS CI fails.
```
veth99: Remembering route: dst: 192.168.5.181/32, src: n/a, gw: n/a, prefsrc: 192.168.5.181, scope: host, table: local, proto: kernel, type: local
veth99: Remembering route: dst: 192.168.5.255/32, src: n/a, gw: n/a, prefsrc: 192.168.5.181, scope: link, table: local, proto: kernel, type: broadcast
veth99: Remembering route: dst: 192.168.5.0/32, src: n/a, gw: n/a, prefsrc: 192.168.5.181, scope: link, table: local, proto: kernel, type: broadcast
veth99: Configuring route: dst: 192.168.5.0/24, src: n/a, gw: n/a, prefsrc: 192.168.5.181, scope: link, table: 211, proto: 16, type: unicast
veth99: Updating remembered route: dst: 192.168.5.0/24, src: n/a, gw: n/a, prefsrc: 192.168.5.181, scope: link, table: 211, proto: 16, type: unicast
veth99: Configuring route: dst: 192.168.5.0/24, src: n/a, gw: 192.168.5.5, prefsrc: 192.168.5.181, scope: global, table: 211, proto: 16, type: unicast
veth99: Configuring route: dst: 192.168.5.1/32, src: n/a, gw: n/a, prefsrc: 192.168.5.181, scope: link, table: 211, proto: 16, type: unicast
veth99: Configuring route: dst: n/a, src: n/a, gw: 192.168.5.1, prefsrc: 192.168.5.181, scope: global, table: 211, proto: 16, type: unicast
veth99: Could not set DHCPv4 route: Network is unreachable```

**Comment by ssahani** [comment]
> Patch looks good to me, But I am not sure I fully grok this all. Good to merge by me, but maybe @ssahani has to say something about this? 

just setting ```IFA_F_NOPREFIXROUTE``` in the address flag would fix this.

**Comment by yuwata** [comment]
> > Patch looks good to me, But I am not sure I fully grok this all. Good to merge by me, but maybe @ssahani has to say something about this?
> 
> just setting `IFA_F_NOPREFIXROUTE` in the address flag would fix this.

@ssahani As you can see in your PR, just setting the flag does not pass the CentOS CIs.

Maybe, there exist a bug in older kernel. If setting the flag, even if we create the relevant prefix route, some route cannot be set and kernel returns `ENETUNREACH`. So, now in this PR, first try to set the flag, and if it fails, revert the configurations and try without the flag. That means #8726 cannot be fixed with old kernels. I hope the reporter of #8726 uses newer kernels :-)

**Comment by ssahani** [comment]
We already have this configuration ```IFA_F_NOPREFIXROUTE``` as configurable and not passing CI will fix this. I am going to change as ```DHCPNoprefixRoute=``` that would make more sense.

**Comment by yuwata** [comment]
> We already have this configuration `IFA_F_NOPREFIXROUTE` as configurable and not passing CI will fix this.

- Simply setting `IFA_F_NOPREFIXROUTE` does not work. Some routes cannot be configured.
- Setting `IFA_F_NOPREFIXROUTE` and configuring prefix route does not work. Some routes still cannot be configured with old kernels.

> I am going to change as `DHCPNoprefixRoute=` that would make more sense.

Adding that option itself maybe OK. Though, no one requests that yet...
But the option does not fix issue #8726.

**Comment by ssahani** [comment]
>Adding that option itself maybe OK. Though, no one requests that yet...
But the option does not fix issue #8726.

Now I am wondering what is the issue ?

**Comment by yuwata** [comment]
> > Adding that option itself maybe OK. Though, no one requests that yet...
> > But the option does not fix issue #8726.
> 
> Now I am wondering what is the issue ?

Original issue (or RFE) #8726 is that the prefix route does not in specified route table. So, just adding the option cannot solve the issue. We need to create the prefix route with specified table.

> > Simply setting IFA_F_NOPREFIXROUTE does not work. Some routes cannot be configured.
> 
> umm why this option is at all ?

I've also tested with RTNH_F_ONLINK flag, but still some routes cannot be configured...
Are there any suggestions?

> > Setting IFA_F_NOPREFIXROUTE and configuring prefix route does not work. Some routes still cannot be configured with old kernels.
> 
> what old kernel ?

Not sure, but CentOS provided 3.11 does not work. But Arch provided 5.x works fine.

**Comment by ssahani** [comment]
>Original issue (or RFE) #8726 is that the prefix route does not in specified route table. So, just adding the option cannot solve the issue. We need to create the prefix route with specified table.

For what if the user does not want ? Please post a patch to kernel.


> I've also tested with RTNH_F_ONLINK flag, but still some routes cannot be configured...
Are there any suggestions?

Will try to figure out.

**Comment by yuwata** [comment]
> > Original issue (or RFE) #8726 is that the prefix route does not in specified route table. So, just adding the option cannot solve the issue. We need to create the prefix route with specified table.
> 
> For what if the user does not want ? Please post a patch to kernel.

Even if I or someone write a kernel patch for #8726, it should be a new feature for the kernel, not a bug fix. So, we cannot use it. So, the practical solution to the issue #8726 is disabling kernel to create the prefix route, and then `networkd` create it with the specified table.

**Comment by ssahani** [comment]
>Even if I or someone write a kernel patch for #8726, it should be a new feature for the kernel, not a bug fix. 

Why this a bug ? In this use case user does not want in MAIN table . And I seen the kernel intact checks the what route table number. I  figure out how this can be done on-shot.

**Comment by yuwata** [comment]
I noticed `IFA_F_NOPREFIXROUTE` flag is supported since 3.14. See https://github.com/torvalds/linux/commit/761aac737eb11901c382a3f021dead59a26983fc. I guess CentOS backports this into 3.11. So, we also need to introduce fallback logic if we use the flag.

**Comment by ssahani** [comment]
Does even 3.1 had prefix route properties ?

**Comment by yuwata** [comment]
3.1? What property? Sorry, could you elaborate more?

**Comment by ssahani** [comment]
prefix routes ?

**Comment by yuwata** [comment]
Ah, you commented about the following my comment. Yes, please forget that. Sorry for the noise.

> I noticed `IFA_F_NOPREFIXROUTE` flag is supported since 3.14. See [torvalds/linux@761aac7](https://github.com/torvalds/linux/commit/761aac737eb11901c382a3f021dead59a26983fc). I guess CentOS backports this into 3.11. ~So, we also need to introduce fallback logic if we use the flag.~ No, if kernel does not support the flag, the flag is just ignored.

**Comment by poettering** [comment]
hmm, what's the state on this one? are we good to merge this?

**Comment by yuwata** [comment]
I believe now the logic of this PR is clear, so it is ready to merge. @ssahani Do you have any objection about this? Or, have you found another way to fix #8726?

**Comment by ssahani** [comment]
This is fix not this right way to fix it. I will still say no. I am wondering kernel has already has provided a flag for this and we already have this is Address section. Why using wrong fixes? User already have a workaround for this. This can be moved to 244. I will take a look then.

**Comment by yuwata** [comment]
> This is fix not this right way to fix it. I will still say no. 

OK. Let's postpone the PR to v244. But, still I cannot catch your point. Sorry.

> I am wondering kernel has already has provided a flag for this and we already have this is Address section.

Which flag provide the right fix for the issue?

> User already have a workaround for this.

Really? Sorry. I maybe missed that. Please let me know again.

> I think this is the patch. https://www.mail-archive.com/netdev@vger.kernel.org/msg83548.html.

This just add `NOPREFIXROUTE` flag for ipv4. But the story is more complicated I think. Because, for older kernels, if the address is assigned with the flag, adding several routes fails.

> It seems if route table not main this is does say it's not the criteria for measuring that user does not want prefix route.

Not sure. I think it is safer to add a new option to drop prefix route in `[DHCPv4]` section.

**Comment by ssahani** [comment]
What is a prefix route and why we need this @yuwata?

**Comment by fpletz** [comment]
@ssahani The prefix route is need so that the local host can access other hosts on the same subnet on that interface. It would always go through the gateway if it has a device explicitely specified in its route and the gateway would even allow that without sending redirects.

In short, the kernel mechanism to add prefix routes automatically always adds them to the main table which is not what users are probably expecting when they set a routing table for DHCP.

I agree that a new option to drop prefix routes in `[DHCPv4]` would make sense. Would it make sense to enable it by default and let networkd also add the prefix routes in the default (main routing table) case?

**Comment by fpletz** [comment]
Also, if this is done by default, we can also apply metrics and possibly other options to prefix routes which would fix #928. Note that this should also be applied for `[DHCPv6]` and possibly `[IPv6AcceptRA]`. Or even better a route metric setting on an interface basis as suggested in mentioned issue.

Also see https://github.com/systemd/systemd/issues/928#issuecomment-332860963 which notes that neworkd will also need to take care of removing/adding prefix routes on carrier changes. Since we do DHCP again in that case we might get away with this though.

I've currently implemented this functionality with a networkd config by enslaving the interface to a VRF. In this case the kernel will take care of adding the prefix routes to the routing table configured for the VRF.

File: src/network/networkd-dhcp4.c [hunk 1]
```diff
@@ -193,6 +198,31 @@ static int link_set_dhcp_routes(Link *link) {
...
+                if (r < 0)
+                        return log_link_error_errno(link, r,  "Could not allocate route: %m");
+
+                prefix_route->family = AF_INET;
+                prefix_route->dst.in.s_addr = address.s_addr & netmask.s_addr;
+                prefix_route->dst_prefixlen = in4_addr_netmask_to_prefixlen(&netmask);
+                prefix_route->prefsrc.in = address;
+                prefix_route->scope = RT_SCOPE_LINK;
+                prefix_route->protocol = RTPROT_DHCP;
+                prefix_route->table = table;
```
Comment (keszybz) [inline src/network/networkd-dhcp4.c:244]: This block...

File: src/network/networkd-dhcp4.c [hunk 2]
```diff
@@ -443,6 +473,30 @@ static int dhcp_remove_dns_routes(Link *link, sd_dhcp_lease *lease, const struct
...
+                        return log_link_error_errno(link, r, "DHCP error: No netmask: %m");
+
+                prefix_route->family = AF_INET;
+                prefix_route->dst.in.s_addr = address->s_addr & netmask.s_addr;
+                prefix_route->dst_prefixlen = in4_addr_netmask_to_prefixlen(&netmask);
+                prefix_route->prefsrc.in = *address;
+                prefix_route->scope = RT_SCOPE_LINK;
+                prefix_route->protocol = RTPROT_DHCP;
+                prefix_route->table = table;
+
```
Comment (keszybz) [inline src/network/networkd-dhcp4.c:520]: .. and this block are almost identical. So this could be split out in a separate function.

Though @ssahani says that the route gets deleteted automatically. But I don't understand the exact conditions when this happens. I guess it is safer to delete the route. If it turns out that this is never needed, we can drop the removal.

**Comment by keszybz** [comment]
There are two relevant kernel patches:
- https://github.com/torvalds/linux/commit/761aac737eb11901c382a3f021dead59a26983fc (kernel 3.14) which is for IPv6
- https://github.com/torvalds/linux/commit/7b1311807f3d3eb8bef3ccc53127838b3bea3771 (kernel 4.4) which is for IPv4

4.4 is fairly recent. Right now we advertise support for 3.13. 4.4 is from January 2016, so almost 4 years. But still, it would be nice not to bump the required kernel version.

File: src/network/networkd-dhcp4.c (hunk 2 above)
Comment (ssahani) [reply src/network/networkd-dhcp4.c:520]: No need to delete I will follow up a patch that it won't create itself.
