### PR TITLE
resolved: always return the validated answers when validating

### LINKED ISSUE #24827: systemd-resolved includes response in SERVFAIL answer in case of dnssec bogus
### systemd version the issue has been seen with

251.4

### Used distribution

Fedora 37

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

My upstream VM dnsmasq:

```
; <<>> DiG 9.18.5 <<>> dnssec-failed.org @192.168.122.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 46881
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 6 (DNSSEC Bogus)
;; QUESTION SECTION:
;dnssec-failed.org.		IN	A

;; Query time: 0 msec
;; SERVER: 192.168.122.1#53(192.168.122.1) (UDP)
;; WHEN: Mon Sep 26 17:41:02 EDT 2022
;; MSG SIZE  rcvd: 52
```

### Unexpected behaviour you saw

- systemd-resolved creates hybrid response with answer AND status: SERVFAIL at the same time

```
; <<>> DiG 9.18.5 <<>> dnssec-failed.org @127.0.0.53
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 3675
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;dnssec-failed.org.		IN	A

;; ANSWER SECTION:
dnssec-failed.org.	281	IN	A	96.99.227.255

;; Query time: 2 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Mon Sep 26 17:36:11 EDT 2022
;; MSG SIZE  rcvd: 62
```

- I think it violates https://www.rfc-editor.org/rfc/rfc4035.html#section-5.5
- Also https://www.rfc-editor.org/rfc/rfc4035.html#section-4.7

### Steps to reproduce the problem

- Enabled ``DNSSEC=yes`` in resolved.conf
- systemctl restart systemd-resolved
- dig @127.0.0.53 dnssec-failed.org

I think

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by rpigott**
We normally expect sd-resolved only to return the validated subset of a validated response. In some cases we give up on validating, because we have enough information already to conclude the answer is bogus.

Let's be sure to always reply with only the validated subset in these cases too, so that we don't return bogus answers and confuse primitive clients that won't see the SERVFAIL rcode.

---
Fixes: #24827 #32238

### CODE REVIEW

**Review by bluca — APPROVED** [review]

File: src/resolve/resolved-dns-transaction.c [hunk 1]
```diff
@@ -917,6 +917,10 @@ static int dns_transaction_dnssec_ready(DnsTransaction *t) {
                         if (r < 0)
                                 log_oom_debug();
 
+                        /* The answer would normally be replaced by the validated subset, but at this point
+                         * we aren't going to bother validating the rest, so just drop it. */
+                        DNS_ANSWER_REPLACE(t->answer, dns_answer_new(0));
```
Comment (yuwata) [inline src/resolve/resolved-dns-transaction.c]: Missing oom check?

**Comment by yuwata** [comment]
Is it possible to add a test case for this? Or already tested? cc @mrc0mmand

File: src/resolve/resolved-dns-answer.h [hunk 2]
```diff
@@ -54,6 +54,7 @@ DnsAnswer *dns_answer_unref(DnsAnswer *a);
                 *_a = _b;                       \
         } while(0)
 
+
```
Comment (yuwata) [inline src/resolve/resolved-dns-answer.h]: Hm? Please drop this empty line.

Comment (rpigott) [reply src/resolve/resolved-dns-answer.h]: Oops.

**Comment by rpigott** [comment]
> Is it possible to add a test case for this?

I don't think there is a test atm. The domains I used to test this are `nosig.go.dnscheck.tools` and `badsig.go.dnscheck.tools`, which hit the new bits in dnssec_ready and validate_dnssec respectively, if it helps. IIUC something in the untrusted.test zone from teh testsuite can probably hit the same bit as nosig.go.dnscheck.tools, if you try to query the stub with dnssec=yes.

File: src/resolve/resolved-dns-transaction.c [hunk 3]
```diff
@@ -917,8 +919,16 @@ static int dns_transaction_dnssec_ready(DnsTransaction *t) {
                         if (r < 0)
                                 log_oom_debug();
 
+                        /* The answer would normally be replaced by the validated subset, but at this point
+                         * we aren't going to bother validating the rest, so just drop it. */
+                        empty = dns_answer_new(0);
+                        if (!empty)
+                                return -ENOMEM;
+                        DNS_ANSWER_REPLACE(t->answer, empty);
```
Comment (poettering) [inline src/resolve/resolved-dns-transaction.c:927]: hmm, this is unnecessarily complex. Quite widely in the systemd tree we consider NULL collections equivalent to empty collections. DnsAnswer is the same. Hence, the above four lines can be replaced by:

```c
t->answer = dns_answer_unref(t->answer);
```

**Comment by poettering** [comment]
Hmm, I wonder if it wouldn#t be better to simply clear the answer structure in dns_transaction_complete() for all result codes that aren't a success. Seems cleaner to me, as it would cover all result codes.
