### PR TITLE
core: propagate stop too if restart is issued

### LINKED ISSUE #24068: PropagatesStopTo= does not propagate on restart
### systemd version the issue has been seen with

250.3-8.fc36

### Used distribution

Fedora 36

### Linux kernel version used

5.17.5-300.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl, systemd, other

### Expected behaviour you didn't see

When a unit with `PropagatesStopTo=` is restarted (i.e. via `systemctl restart`), the service that is supposed to receive the stop propagation is not stopped. The "stop" portion of the restart request is not propagated as expected.

### Unexpected behaviour you saw

The unit that is the target of the stop propagation is unaffected.

### Steps to reproduce the problem

1. Create two units:
    * foo.service
        ```systemd
        [Unit]
        Wants=bar.service
        After=bar.service
        PropagatesStopTo=bar.service

        [Service]
        ExecStartPre=echo start foo
        ExecStart=sleep infinity
        ExecStopPost=echo stopped foo
        ```
    * bar.service
        ```systemd
        [Service]
        ExecStartPre=echo start bar
        ExecStart=sleep infinity
        ExecStopPost=echo stopped bar
        ```
1. Start both services: `systemctl start foo.service`
2. Restart foo: `systemctl restart foo.service`
3. Notice that the logs for foo show it was stopped, but bar continues running and does not stop. The expectation is that foo stopping would cause bar to stop, and then foo starting would cause bar to start due to the `Wants=` dependency, meaning a restart of foo should result in a restart of bar.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[zeffron@fedora ~]$ journalctl -u foo.service --since -1m
Jul 20 17:06:15 fedora systemd[1]: Starting foo.service...
Jul 20 17:06:15 fedora echo[1620]: start foo
Jul 20 17:06:15 fedora systemd[1]: Started foo.service.
Jul 20 17:06:19 fedora systemd[1]: Stopping foo.service...
Jul 20 17:06:19 fedora echo[1627]: stopped foo
Jul 20 17:06:19 fedora systemd[1]: foo.service: Deactivated successfully.
Jul 20 17:06:19 fedora systemd[1]: Stopped foo.service.
Jul 20 17:06:19 fedora echo[1628]: start foo
Jul 20 17:06:19 fedora systemd[1]: Starting foo.service...
Jul 20 17:06:19 fedora systemd[1]: Started foo.service.

[zeffron@fedora ~]$ journalctl -u bar.service --since -1m
Jul 20 17:06:15 fedora systemd[1]: Starting bar.service...
Jul 20 17:06:15 fedora echo[1622]: start bar
Jul 20 17:06:15 fedora systemd[1]: Started bar.service.
```

### PR DESCRIPTION
**Pull request by YHNdnzj**
The restart of a unit should also be considered as that a stop job happens, and thus gets propagated to units specified using `PropagatesStopTo=`.

Fixes #24068

### CODE REVIEW

**Review by AdamHinojosa09 — APPROVED** [review]

**Review by AdamHinojosa09 — APPROVED** [review]

File: src/core/transaction.c [hunk 1]
```diff
@@ -902,6 +902,7 @@ int transaction_add_job_and_dependencies(
                 bool ignore_order,
                 sd_bus_error *e) {
 
+        _cleanup_strv_free_ char **propagated_restart = NULL;
```
Comment (poettering) [inline src/core/transaction.c]: string arrays suck for this. Please use a `Set` object, and just insert the `Unit` object pointer into it.

This will bring down rutime behaviour for checking if we already marked something for restarts from O(n) to effectively O(1)

File: src/core/transaction.c [hunk 2]
```diff
@@ -1050,27 +1051,36 @@ int transaction_add_job_and_dependencies(
...
-                                atom = UNIT_ATOM_PROPAGATE_RESTART;
-                                ptype = JOB_TRY_RESTART;
-                        } else {
-                                ptype = JOB_STOP;
-                                atom = UNIT_ATOM_PROPAGATE_STOP;
-                        }
 
-                        UNIT_FOREACH_DEPENDENCY(dep, ret->unit, atom) {
-                                JobType nt;
+                        if (type == JOB_RESTART)
```
Comment (poettering) [inline src/core/transaction.c:1054]: please add an explanatory comment here that explains why this makes sense.

File: src/core/transaction.c (hunk 1 above)
Comment (poettering) [reply src/core/transaction.c]: also, a global field for this sounds like a strange option to me. this should be moved into the loop immediately before the two dep loops.

**Review by poettering — CHANGES_REQUESTED** [review]
makes sense i guess, but some comments.

File: src/core/transaction.c (hunk 1 above)
Comment (YHNdnzj) [reply src/core/transaction.c]: > also, a global field for this sounds like a strange option to me. this should be moved into the loop immediately before the two dep loops.

Hmm, I didn't seem to find such a loop 🤔

Comment (YHNdnzj) [reply src/core/transaction.c]: Does declaring variables in `if` blocks meet the latest code style? It seems that this piece of code hasn't been touched for ages.

File: src/core/transaction.c [hunk 3]
```diff
@@ -1047,27 +1047,42 @@ int transaction_add_job_and_dependencies(
...
-                                JobType nt;
+                        propagated_restart = set_new(NULL);
+                        if (!propagated_restart)
+                                return -ENOMEM;
+
+                        if (type == JOB_RESTART)
+                                UNIT_FOREACH_DEPENDENCY(dep, ret->unit, UNIT_ATOM_PROPAGATE_RESTART) {
+                                        JobType nt;
+
+                                        r = set_put(propagated_restart, dep);
```
Comment (poettering) [inline src/core/transaction.c]: please use `set_ensure_put()` here. and drop the the set_new() call above. THis will mean we'll allocate the set lazily once we need it. shortens the code a bit.

all our code treats NULL sets as empty sets, hence this is pretty effective

File: src/core/transaction.c [hunk 4]
```diff
@@ -976,7 +976,7 @@ int transaction_add_job_and_dependencies(
         }
 
         if (is_new && !ignore_requirements && type != JOB_NOP) {
-                _cleanup_set_free_ Set *following = NULL;
+                _cleanup_set_free_ Set *following = NULL, *propagated_restart = NULL;
```
Comment (bluca) [inline src/core/transaction.c]: `propagated_restart` is only used inside the `if (IN_SET(type, JOB_STOP, JOB_RESTART))` block, so you can move it further down

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
lgtm, too
