### PR TITLE
core,test: services in reloading state should exit without waiting TimeoutStartSec

### LINKED ISSUE #19300: Restart=always|on-failure|etc does not restart a crashed service, if RELOADING=1 was sent immediately before
**systemd version the issue has been seen with**
 > v247, v241

**Used distribution**
 > Yocto derivative, Debian stable

**Linux kernel version used** (`uname -a`)
 > `5.10.19`

**CPU architecture issue was seen on**
 > arm64, amd64

**Expected behaviour you didn't see**
 > A service is restarted when it crashes and it has `Restart=on-failure`

**Unexpected behaviour you saw**
 > The service was not restarted, as it's stuck in `reloading` state

**Steps to reproduce the problem**
 > …
```
# systemctl cat test.service
[Service]
Type=notify
ExecStart=/bin/bash -c "systemd-notify --ready; systemd-notify RELOADING=1; sleep 5; exit 1"
Restart=on-failure
```

```
# systemctl status -l test
* test.service
     Loaded: loaded (/run/systemd/system/test.service; static)
     Active: reloading (reload) (Result: exit-code) since Mon 2021-04-12 16:42:21 UTC; 19s ago
    Process: 585 ExecStart=/bin/bash -c systemd-notify --ready; systemd-notify RELOADING=1; sleep 1; exit 1 (code=exited, status=1/FAILURE)
   Main PID: 585 (code=exited, status=1/FAILURE)
         IO: 48.0K read, 0B written
      Tasks: 0 (limit: 1184)
     Memory: 56.0K
        CPU: 341ms
     CGroup: /system.slice/test.service

Apr 12 16:42:21 localhost systemd[1]: Starting test.service...
Apr 12 16:42:21 localhost systemd[1]: Started test.service.
Apr 12 16:42:27 localhost systemd[1]: test.service: Main process exited, code=exited, status=1/FAILURE
```

(note the `19s ago` in the status, as it was not restarted)

If `RELOADING=1` is not sent, the service is restarted immediately as expected.

### PR DESCRIPTION
**Pull request by pdmorrow**
Fixes #19300

If a service is in reloading state and exits before entering ready state then it should not need to wait for TimeoutStartSec secs before finally exiting, this is since there is no chance of it ever transitioning to ready state. This allows services who end up in this state with Restart=on-failure|on-abort|etc to be restarted immediately when they exit rather than needing to wait the extra TimeoutStartSec (default 4m) time before being restarted.

For example:

```
peter@p52s:~$ systemctl cat test-reload.service --no-pager
# /run/systemd/system/test-reload.service
[Unit]
Description=Stuck in reloading

[Service]
Type=notify
ExecStart=/bin/bash -c "systemd-notify --ready; systemd-notify RELOADING=1; sleep 2; exit 1"
Restart=on-failure
peter@p52s:~$ 
```

```
peter@p52s:~$ systemctl status test-reload.service --no-pager -l
● test-reload.service - Stuck in reloading
   Loaded: loaded (/run/systemd/system/test-reload.service; static; vendor preset: enabled)
   Active: reloading (reload) (Result: exit-code) since Fri 2021-04-16 11:06:15 BST; 32s ago
  Process: 22988 ExecStart=/bin/bash -c systemd-notify --ready; systemd-notify RELOADING=1; sleep 2; exit 1 (code=exited, status=1/FAILURE)
 Main PID: 22988 (code=exited, status=1/FAILURE)
    Tasks: 0 (limit: 4915)
   Memory: 4.0K
   CGroup: /system.slice/test-reload.service

Apr 16 11:06:15 p52s systemd[1]: Starting Stuck in reloading...
Apr 16 11:06:15 p52s systemd[1]: Started Stuck in reloading.
Apr 16 11:06:17 p52s systemd[1]: test-reload.service: Main process exited, code=exited, status=1/FAILURE
peter@p52s:~$ 
```

Note 32s ago, the service was not restarted as expected.

### CODE REVIEW

File: test/units/testsuite-57.sh [hunk 1]
```diff
@@ -0,0 +1,64 @@
+#!/usr/bin/env bash
+set -ex
```
Comment (bluca) [inline test/units/testsuite-57.sh]: eux

File: test/units/testsuite-57.sh [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+
+systemctl daemon-reload
+
+# This service will sleep for 1s then exit with a non-zero exit code, it
+# should not stay in reloading state. Rather, it should be restarted
+# and finally end up in "failed" state after StartLimitBurst has been exceeded.
+systemctl start testservice-fail-57.service
+# Sleep for 4s to allow the service to start, exit, start, exit.
+sleep 4
+state=$(systemctl show testservice-fail-57.service --property=ActiveState --value)
```
Comment (bluca) [inline test/units/testsuite-57.sh]: shellcheck this please (there's another PR doing shellcheck on the rest, don't want to add new warnings)

File: test/units/testsuite-57.sh [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+if [ "$state" = "reloading" ]; then
+    fail
+fi
+
+# This service will sleep for 3s to allow us to send it a SIGABRT.
+systemctl start testservice-abort-57.service
+pid=$(systemctl show testservice-abort-57.service --property=ExecMainPID --value)
+kill -6 "$pid"
```
Comment (bluca) [inline test/units/testsuite-57.sh]: @mrc0mmand there's an intentional abrt() and consequent core file here, what was the trick to make the CentOS CI expect this and not fail?

File: test/units/testsuite-57.sh [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+# Sleep long enough to allow the restart to complete and for the 2nd sleep to finish.
+sleep 8
```
Comment (bluca) [inline test/units/testsuite-57.sh]: rather than arbitrary sleeps that will be flaky on nested vms, would be better just to loop and check for state changes directly

File: test/units/testsuite-57.sh (hunk 3 above)
Comment (mrc0mmand) [reply test/units/testsuite-57.sh]: Should be fixed by https://github.com/systemd/systemd-centos-ci/commit/5a4105876f291b0e8364735982d2dd2b75d82217.

Comment (bluca) [reply test/units/testsuite-57.sh]: thanks!

File: test/units/testsuite-57.sh (hunk 1 above)
Comment (pdmorrow) [reply test/units/testsuite-57.sh]: Fixed.

File: test/units/testsuite-57.sh (hunk 2 above)
Comment (pdmorrow) [reply test/units/testsuite-57.sh]: Sure, shellcheck looks clean here with the next round of diffs.

```
peter@p52s:~/git/systemd-pdmorrow$ shellcheck test/units/testsuite-57.sh 
peter@p52s:~/git/systemd-pdmorrow$ echo $?
0
peter@p52s:~/git/systemd-pdmorrow$ 
```

File: test/units/testsuite-57.sh (hunk 4 above)
Comment (pdmorrow) [reply test/units/testsuite-57.sh]: I've had another go at this, though there is still a timeout in use (albeit much larger). Very welcome to hear any other suggestions on how to make this better.

File: test/units/testsuite-57.sh [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+# state and does not linger in reloading state.
+systemctl start testservice-fail-restart-57.service
+wait_on_state_or_fail "testservice-fail-restart-57.service" "failed" "30"
+
+# This service sends a RELOADING=1 message then exits before it sends a
+# READY=1. It should automatically restart on abort. It will sleep for 5s
+# to allow us to send it a SIGABRT. Ensure the service enters the failed state
+# and does not linger in reloading state.
+systemctl start testservice-abort-restart-57.service
+pid=$(systemctl show testservice-abort-restart-57.service --property=ExecMainPID --value)
```
Comment (bluca) [inline test/units/testsuite-57.sh]: `systemctl --signal=SIGABORT kill testservice-abort-restart-57.service`

**Review by bluca — APPROVED** [review]
LGTM - but would much prefer @poettering to double check the pid1 service FSM change

File: test/units/testsuite-57.sh (hunk 5 above)
Comment (pdmorrow) [reply test/units/testsuite-57.sh]: Updated.

**Comment by mrc0mmand** [comment]
@bluca looks like both `sleep` and `bash` coredumps need to be filtered out:

```
        Signal: 6 (ABRT)
     Timestamp: Mon 2021-04-19 15:20:57 CEST (48min ago)
  Command Line: /bin/bash -c systemd-notify --ready; systemd-notify RELOADING=1; sleep 5; exit 1
    Executable: /usr/bin/bash
```

I'll patch it shortly and then restart the CI.

**Comment by pdmorrow** [comment]
> @bluca looks like both `sleep` and `bash` coredumps need to be filtered out:
> 
> ```
>         Signal: 6 (ABRT)
>      Timestamp: Mon 2021-04-19 15:20:57 CEST (48min ago)
>   Command Line: /bin/bash -c systemd-notify --ready; systemd-notify RELOADING=1; sleep 5; exit 1
>     Executable: /usr/bin/bash
> ```
> 
> I'll patch it shortly and then restart the CI.

Thank you!

File: src/core/service.c [hunk 6]
```diff
@@ -3472,8 +3472,18 @@ static void service_sigchld_event(Unit *u, pid_t pid, int code, int status) {
...
                         case SERVICE_RELOAD:
+                            /* The service has exited but it's still in
+                             * reloading state, we can't expect the reload
+                             * to complete so end the control process.
+                             */
+                            s->timer_event_source = sd_event_source_unref(s->timer_event_source);
+                            service_kill_control_process(s);
+                            s->reload_result = f;
+                            service_enter_running(s, f);
+                            break;
```
Comment (poettering) [inline src/core/service.c]: indent to multiples of 8 spaces please

**Comment by poettering** [comment]
hmm, so the reload command you configured, why doesn't it fail once the service went away?

is this supposed to be a way to "fail quicker" in case the ExecReload= program is a bit unreliable, and doesn't realize when the daemon died while it was doing its thing?

i am trying to get my head around this.

I mean the error condition is eventually noticed in the current code, too, right? Once the ExecReload timeout is reached, no? So this doesn't really fix a bug, but just speeds the failure up a bit under some condition? Did i get this right?

File: src/core/service.c (hunk 6 above)
Comment (pdmorrow) [reply src/core/service.c]: Oops, fixed.

**Comment by pdmorrow** [comment]
> hmm, so the reload command you configured, why doesn't it fail once the service went away?

In my tests and in the case where we saw this happen we didn't have an ExecReload command.


> 
> is this supposed to be a way to "fail quicker" in case the ExecReload= program is a bit unreliable, and doesn't realize when the daemon died while it was doing its thing?
> 

Yes, pretty much.

> i am trying to get my head around this.
> 
> I mean the error condition is eventually noticed in the current code, too, right? Once the ExecReload timeout is reached, no? So this doesn't really fix a bug, but just speeds the failure up a bit under some condition? Did i get this right?

Yep you got it right but I guess there is an argument for this being a bug or expected behaviour. Looking at the docs I read this:

```
RELOADING=1
Tells the service manager that the service is reloading its configuration. This is useful to allow the service manager to track the service's internal state, and present it to the user. Note that a service that sends this notification must also send a "READY=1" notification when it completed reloading its configuration. Reloads are propagated in the same way as they are when initiated by the user.
```

If a service sent RELOADING=1 to the manager but then crashed/exited before it could send the READY=1 message. Then it needs to wait TimeoutStartSec + RestartSec before restarting instead of just RestartSec. In a specific case I had I had configured a RestartSec of 1s but had not configured a TimeoutStartSec, thus we ended up waiting 4m 1s for the service to be restarted.

Yes the service should not crash/exit between RELOADING=1 and READY=1 but since systemd knows the service has exited I think this could be considered a bug since there is a failure to recognise the service will never send a corresponding READY=1. systemd is waiting for an event that will never come, so this PR detects this case and ends the control process and stops the timer which will fire after TimeoutStartSec expires.

Hopefully that makes sense?

File: src/core/service.c [hunk 7]
```diff
@@ -3472,8 +3472,18 @@ static void service_sigchld_event(Unit *u, pid_t pid, int code, int status) {
 
                         switch (s->state) {
 
-                        case SERVICE_START_POST:
                         case SERVICE_RELOAD:
+                                /* The service has exited but it's still in
+                                 * reloading state, we can't expect the reload
+                                 * to complete so end the control process.
+                                 */
```
Comment (poettering) [inline src/core/service.c]: so i figure you want to check here if the control pid is still valid, and if so, immediately enter the stop phase.

```c
case SERVICE_START_POST:
case SERVICE_RELOAD:

        if (control_pid_good(s) <= 0) /* If from here on neither a main nor a control process remain running, then the current state can never exit cleanly, hence immediately terminate the service */
                service_enter_stop(s, SERVICE_SUCCESS);

        /* Otherwise we need to wait until the operation is complete. */
         break;
```

Comment (pdmorrow) [reply src/core/service.c]: Thanks, pushed new changes. I've propagated the original ServiceResult "f" here though instead of passing SERVICE_SUCCESS since this seems to more accurately capture what the state was at the time of the service exiting.

File: src/core/service.c [hunk 8]
```diff
@@ -3473,7 +3473,17 @@ static void service_sigchld_event(Unit *u, pid_t pid, int code, int status) {
                         switch (s->state) {
 
                         case SERVICE_START_POST:
+                                _fallthrough_;
```
Comment (bluca) [inline src/core/service.c]: this shouldn't be necessary? the compiler shouldn't complain about stacked cases iirc

Comment (pdmorrow) [reply src/core/service.c]: You are right, sorry for the noise.  Pushed changes.

File: src/core/service.c [hunk 9]
```diff
@@ -3474,6 +3474,15 @@ static void service_sigchld_event(Unit *u, pid_t pid, int code, int status) {
 
                         case SERVICE_START_POST:
                         case SERVICE_RELOAD:
+                                /* If neither main nor control processes are running then
+                                 * the current state can never exit cleanly, hence immediately
+                                 * terminate the service. */
+                                if (control_pid_good(s) <= 0)
+                                    service_enter_stop(s, f);
```
Comment (poettering) [inline src/core/service.c]: indentation: multiples of 8 spaces please

File: test/TEST-57-RELOADING-RESTART/Makefile [hunk 10]
```diff
@@ -0,0 +1 @@
+../TEST-01-BASIC/Makefile
```
Comment (poettering) [inline test/TEST-57-RELOADING-RESTART/Makefile]: hmm, TEST-57 is already taken by #19322

**Comment by poettering** [comment]
looks (almost) perfect. See comments.

File: src/core/service.c (hunk 9 above)
Comment (pdmorrow) [reply src/core/service.c]: Hopefully that's the last time I do that. Fix in the next iteration.

File: test/TEST-57-RELOADING-RESTART/Makefile (hunk 10 above)
Comment (pdmorrow) [reply test/TEST-57-RELOADING-RESTART/Makefile]: I've renamed to TEST-59, seems TEST-58 has been taken in the interim.

**Comment by pdmorrow** [comment]
> looks (almost) perfect. See comments.

Thank you for the review!
