### PR TITLE
dissect-image: extend timeout for waiting devlink

### LINKED ISSUE #24490: TEST-29-PORTABLE flakiness without HW accel
### systemd version the issue has been seen with

latest main

### Used distribution

CentOS Stream 8

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

_No response_

### Component

systemd-portabled, tests

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

I noticed that TEST-29 became suspiciously unstable - not sure if this is caused directly by running the test without HW accel in the C8S job, or there's something else related to the recent udev changes:

```
[   90.624713] H systemd[1]: minimal-app0-bar.service: Changed dead -> start-pre
[   90.627929] H systemd[1]: Starting minimal-app0-bar.service...
[   90.629688] H systemd[1]: minimal-app0.service: Will spawn child (service_enter_start_pre): cat
[   90.630900] H systemd[1]: bpf_devices_allow_list_device: /dev/null rwm
...
[   90.788840] H systemd[1]: minimal-app0-bar.service: User lookup succeeded: uid=62418 gid=62418
[   90.792416] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/minimal_2dapp0_2dbar_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1746 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   90.793742] H systemd[658]: Opened '/usr/share/minimal_1.raw' in O_RDONLY access mode, with O_DIRECT enabled.
[   90.796457] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/minimal_2dapp0_2dbar_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1747 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   90.799401] H systemd[1]: systemd-journald.service: Got notification message from PID 499 (FDSTORE=1)
[   90.800525] H systemd[1]: systemd-journald.service: Added fd 46 (n/a) to fd store.
[   90.803510] H systemd[658]: sd-device: the uevent file "/sys/devices/virtual/block/loop0/power/uevent" does not exist.
[   90.805004] H systemd[659]: Failed to connect to nscd socket: No such file or directory
[   90.810564] H systemd[1]: loop0: Device busy: SYSTEMD_READY property from device is false
[   90.813674] H systemd[658]: sd-device: the uevent file "/sys/devices/virtual/block/loop0/holders/uevent" does not exist.
[   90.814984] H systemd[659]: Failed to connect to nscd socket: No such file or directory
[   90.817034] H systemd[658]: sd-device: the uevent file "/sys/devices/virtual/block/loop0/mq/uevent" does not exist.
[   90.819621] H systemd[658]: sd-device: the uevent file "/sys/devices/virtual/block/loop0/mq/0/uevent" does not exist.
[   90.820744] H systemd[658]: sd-device: the uevent file "/sys/devices/virtual/block/loop0/mq/0/cpu1/uevent" does not exist.
[   90.823606] H systemd[658]: sd-device: the uevent file "/sys/devices/virtual/block/loop0/mq/0/cpu0/uevent" does not exist.
[   90.825708] H systemd[658]: sd-device: the uevent file "/sys/devices/virtual/block/loop0/queue/uevent" does not exist.
[   90.827940] H systemd[658]: sd-device: the uevent file "/sys/devices/virtual/block/loop0/queue/iosched/uevent" does not exist.
[   90.829364] H systemd[658]: sd-device: the uevent file "/sys/devices/virtual/block/loop0/integrity/uevent" does not exist.
[   90.832944] H systemd[658]: sd-device: the uevent file "/sys/devices/virtual/block/loop0/trace/uevent" does not exist.
[   90.834214] H systemd[658]: sd-device: the uevent file "/sys/devices/virtual/block/loop0/slaves/uevent" does not exist.
[   90.837688] H systemd[658]: Successfully acquired /dev/loop0, devno=7:0, nr=0, diskseq=0
[   90.840236] H systemd[1]: minimal-app0.service: User lookup succeeded: uid=64256 gid=64256
[   90.843582] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/minimal_2dapp0_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1748 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   90.844874] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/minimal_2dapp0_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1749 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   90.848610] H systemd[659]: Opened '/usr/share/minimal_1.raw' in O_RDONLY access mode, with O_DIRECT enabled.
[   90.851015] H systemd[1]: loop0: Processing udev action (SEQNUM=1901, ACTION=change)
[   90.852495] H systemd[1]: dev-loop0.device: Changed dead -> plugged
[   90.854533] H systemd[1]: sys-devices-virtual-block-loop0.device: Changed dead -> plugged
[   90.857989] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=1750 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[   90.859678] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=1751 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[   90.863266] H systemd[1]: systemd-journald.service: Got notification message from PID 499 (FDSTORE=1)
[   90.865968] H systemd[1]: systemd-journald.service: Added fd 47 (n/a) to fd store.
[   90.867444] H systemd[659]: sd-device: the uevent file "/sys/devices/virtual/block/loop1/power/uevent" does not exist.
[   90.870700] H systemd[659]: sd-device: the uevent file "/sys/devices/virtual/block/loop1/holders/uevent" does not exist.
[   90.873613] H systemd[659]: sd-device: the uevent file "/sys/devices/virtual/block/loop1/mq/uevent" does not exist.
[   90.875305] H systemd[659]: sd-device: the uevent file "/sys/devices/virtual/block/loop1/mq/0/uevent" does not exist.
[   90.877883] H systemd[659]: sd-device: the uevent file "/sys/devices/virtual/block/loop1/mq/0/cpu1/uevent" does not exist.
[   90.879616] H systemd[659]: sd-device: the uevent file "/sys/devices/virtual/block/loop1/mq/0/cpu0/uevent" does not exist.
[   90.882632] H systemd[659]: sd-device: the uevent file "/sys/devices/virtual/block/loop1/queue/uevent" does not exist.
[   90.883764] H systemd[659]: sd-device: the uevent file "/sys/devices/virtual/block/loop1/queue/iosched/uevent" does not exist.
[   90.886771] H systemd[659]: sd-device: the uevent file "/sys/devices/virtual/block/loop1/integrity/uevent" does not exist.
[   90.887890] H systemd[659]: sd-device: the uevent file "/sys/devices/virtual/block/loop1/trace/uevent" does not exist.
[   90.889154] H systemd[659]: sd-device: the uevent file "/sys/devices/virtual/block/loop1/slaves/uevent" does not exist.
[   90.891819] H systemd[658]: Allocating context for crypt device /usr/share/minimal_1.verity.
[   90.895180] H systemd[658]: Trying to open and read device /usr/share/minimal_1.verity with direct-io.
[   90.897028] H systemd[658]: Initialising device-mapper backend library.
[   90.899722] H systemd[659]: Successfully acquired /dev/loop1, devno=7:1, nr=1, diskseq=0
[   90.901367] H systemd[658]: Trying to load VERITY crypt type from device /usr/share/minimal_1.verity.
[   90.903858] H systemd[658]: Crypto backend (OpenSSL 1.1.1k  FIPS 25 Mar 2021) initialized in cryptsetup library version 2.3.7.
[   90.906482] H systemd[658]: Detected kernel Linux 4.18.0-408.el8.x86_64 x86_64.
[   90.907691] H systemd[658]: Reading VERITY header of size 512 on device /usr/share/minimal_1.verity, offset 0.
[   90.909914] H systemd[658]: Setting ciphertext data device to /dev/loop0.
[   90.911820] H systemd[658]: Trying to open and read device /dev/loop0 with direct-io.
[   90.912794] H systemd[658]: Activating volume 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity by volume key.
[   90.913684] H systemd[658]: dm version   [ opencount flush ]   [16384] (*1)
[   90.915884] H systemd[658]: dm versions   [ opencount flush ]   [16384] (*1)
[   90.916860] H systemd[658]: Detected dm-ioctl version 4.46.0.
[   90.918958] H systemd[1]: sys-devices-virtual-block-dm\x2d0.device: Job 683 sys-devices-virtual-block-dm\x2d0.device/nop finished, result=done
[   90.922024] H systemd[658]: Detected dm-verity version 1.8.0.
[   90.923520] H systemd[658]: Device-mapper backend running with UDEV support enabled.
[   90.925810] H systemd[658]: dm status 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity  [ opencount noflush ]   [16384] (*1)
[   90.926926] H systemd[658]: Activating volume 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity by key.
[   90.929573] H systemd[658]: dm versions   [ opencount flush ]   [16384] (*1)
[   90.932083] H systemd[658]: dm status 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity  [ opencount noflush ]   [16384] (*1)
[   90.933669] H systemd[658]: Trying to activate VERITY device 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity using hash sha256.
[   90.936334] H systemd[658]: Allocating a free loop device.
[   90.937557] H systemd[658]: Trying to open and read device /dev/loop2 with direct-io.
[   90.939979] H systemd[658]: Calculated device size is 5792 sectors (RO), offset 0.
[   90.941414] H systemd[658]: DM-UUID is CRYPT-VERITY-1eb7c2fb23f14d678af62b6f5498bcab-71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity
[   90.943328] H systemd[658]: Udev cookie 0xd4de3f4 (semid 8) created
[   90.946168] H systemd[658]: Udev cookie 0xd4de3f4 (semid 8) incremented to 1
[   90.947204] H systemd[658]: Udev cookie 0xd4de3f4 (semid 8) incremented to 2
[   90.949824] H systemd[658]: Udev cookie 0xd4de3f4 (semid 8) assigned to CREATE task(0) with flags DISABLE_LIBRARY_FALLBACK         (0x20)
[   90.951259] H systemd[658]: dm create 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity CRYPT-VERITY-1eb7c2fb23f14d678af62b6f5498bcab-71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity [ opencount flush ]   [16384] (*1)
[   90.953496] H systemd[659]: Allocating context for crypt device /usr/share/minimal_1.verity.
[   90.955407] H systemd[659]: Trying to open and read device /usr/share/minimal_1.verity with direct-io.
[   90.957573] H systemd[659]: Initialising device-mapper backend library.
[   90.959575] H systemd[659]: Trying to load VERITY crypt type from device /usr/share/minimal_1.verity.
[   90.960758] H systemd[659]: Crypto backend (OpenSSL 1.1.1k  FIPS 25 Mar 2021) initialized in cryptsetup library version 2.3.7.
[   90.963269] H systemd[659]: Detected kernel Linux 4.18.0-408.el8.x86_64 x86_64.
[   90.965014] H systemd[659]: Reading VERITY header of size 512 on device /usr/share/minimal_1.verity, offset 0.
[   90.966550] H systemd[658]: dm reload   (253:0) [ opencount flush readonly securedata ]   [16384] (*1)
[   90.968625] H systemd[659]: Setting ciphertext data device to /dev/loop1.
[   90.970877] H systemd[659]: Trying to open and read device /dev/loop1 with direct-io.
[   90.972823] H systemd[1]: loop1: Processing udev action (SEQNUM=1902, ACTION=change)
[   90.975914] H systemd[658]: dm resume 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity  [ opencount flush readonly securedata ]   [16384] (*1)
[   90.977759] H systemd[659]: Activating volume 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity by volume key.
[   90.980978] H systemd[658]: 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity: Stacking NODE_ADD (253,0) 0:6 0660 [trust_udev]
[   90.982021] H systemd[658]: 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity: Stacking NODE_READ_AHEAD 256 (flags=1)
[   90.983320] H systemd[658]: Udev cookie 0xd4de3f4 (semid 8) decremented to 1
[   90.984211] H systemd[658]: Udev cookie 0xd4de3f4 (semid 8) waiting for zero
[   90.985078] H systemd[659]: dm version   [ opencount flush ]   [16384] (*1)
[   90.986112] H systemd[659]: dm versions   [ opencount flush ]   [16384] (*1)
[   90.987191] H systemd[659]: Detected dm-ioctl version 4.46.0.
[   90.988290] H systemd[659]: Detected dm-verity version 1.8.0.
[   90.990680] H systemd[659]: Device-mapper backend running with UDEV support enabled.
[   90.993677] H systemd[659]: dm status 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity  [ opencount noflush ]   [16384] (*1)
[   90.996492] H systemd[659]: Device 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity already exists.
[   90.997658] H systemd[659]: Allocating crypt device context by device 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity.
[   90.989797] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2ddm_5cx2d0_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1888 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   91.000886] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2dloop2_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1893 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   91.005579] H systemd[659]: dm versions   [ opencount flush ]   [16384] (*1)
[   91.007049] H systemd[659]: dm status 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity  [ opencount noflush ]   [16384] (*1)
[   91.009494] H systemd[659]: dm versions   [ opencount flush ]   [16384] (*1)
[   91.010616] H systemd[659]: dm table 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity  [ opencount flush securedata ]   [16384] (*1)
[   91.013167] H systemd[1]: dev-loop1.device: Changed dead -> plugged
[   91.014925] H systemd[659]: Trying to open and read device /dev/loop0 with direct-io.
[   91.018508] H systemd[1]: sys-devices-virtual-block-loop1.device: Changed dead -> plugged
[   91.020855] H systemd[659]: dm status 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity  [ opencount noflush ]   [16384] (*1)
[   91.023490] H systemd[659]: Verity volume 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity status is V.
[   91.025049] H systemd[659]: Allocating context for crypt device /dev/loop0.
[   91.028254] H systemd[659]: Trying to open and read device /dev/loop0 with direct-io.
[   91.029696] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=1752 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[   91.030975] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=1753 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[   91.032425] H systemd[659]: dm versions   [ opencount flush ]   [16384] (*1)
[   91.037411] H systemd[659]: dm table 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity  [ opencount flush securedata ]   [16384] (*1)
[   91.039385] H systemd[659]: Trying to open and read device /dev/loop0 with direct-io.
[   91.040631] H systemd[659]: Trying to open and read device /dev/loop2 with direct-io.
[   91.041683] H systemd[659]: dm status 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity  [ opencount noflush ]   [16384] (*1)
[   91.042712] H systemd[659]: Verity volume 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity status is V.
[   91.043735] H systemd[659]: Failed to stat() /dev/mapper/71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity: No such file or directory
[   91.044900] H systemd[659]: Failed to stat() /dev/mapper/71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity: No such file or directory
[   91.046250] H systemd[1]: loop2: Processing udev action (SEQNUM=1903, ACTION=change)
[   91.047334] H systemd[1]: dev-disk-by\x2duuid-1eb7c2fb\x2d23f1\x2d4d67\x2d8af6\x2d2b6f5498bcab.device: Changed dead -> plugged
[   91.048415] H systemd[1]: dev-loop2.device: Changed dead -> plugged
[   91.049515] H systemd[1]: sys-devices-virtual-block-loop2.device: Changed dead -> plugged
[   91.052533] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=1754 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[   91.056060] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=1755 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[   91.060979] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=1756 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[   91.062862] H systemd[1]: loop1: Processing udev action (SEQNUM=1904, ACTION=change)
[   91.066598] H systemd[1]: Added job dev-loop1.device/nop to transaction.
[   91.070713] H systemd[1]: dev-loop1.device: Installed new job dev-loop1.device/nop as 668
[   91.072477] H systemd[1]: Added job sys-devices-virtual-block-loop1.device/nop to transaction.
[   91.075972] H systemd[1]: sys-devices-virtual-block-loop1.device: Installed new job sys-devices-virtual-block-loop1.device/nop as 669
[   91.077619] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/sys_2ddevices_2dvirtual_2dblock_2dloop1_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1757 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   91.080498] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/sys_2ddevices_2dvirtual_2dblock_2dloop1_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1758 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   91.081823] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2dloop1_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1759 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   91.083066] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2dloop1_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1760 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   91.084400] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobNew cookie=1761 reply_cookie=0 signature=uos error-name=n/a error-message=n/a
[   91.085578] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobNew cookie=1762 reply_cookie=0 signature=uos error-name=n/a error-message=n/a
[   91.087003] H systemd[1]: dm-0: Processing udev action (SEQNUM=1906, ACTION=add)
[   91.088481] H systemd[1]: dm-0: Device busy: SYSTEMD_READY property from device is false
[   91.089668] H systemd[1]: dm-0: Processing udev action (SEQNUM=1907, ACTION=change)
[   91.090870] H systemd[1]: dev-dm\x2d0.device: Changed dead -> plugged
[   91.092399] H systemd[1]: sys-devices-virtual-block-dm\x2d0.device: Changed dead -> plugged
[   91.093984] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=1763 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[   91.095469] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=1764 reply_cookie=0 signature=so error-name=n/a error-message=n/a
[   91.096735] H systemd[1]: dev-loop1.device: Job 668 dev-loop1.device/nop finished, result=done
[   91.098337] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=1765 reply_cookie=0 signature=uoss error-name=n/a error-message=n/a
[   91.099665] H systemd[1]: sys-devices-virtual-block-loop1.device: Job 669 sys-devices-virtual-block-loop1.device/nop finished, result=done
[   91.101375] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=1766 reply_cookie=0 signature=uoss error-name=n/a error-message=n/a
[   91.102651] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/sys_2ddevices_2dvirtual_2dblock_2dloop1_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1767 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   91.103860] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/sys_2ddevices_2dvirtual_2dblock_2dloop1_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1768 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   91.105304] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2dloop1_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1769 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   91.106574] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2dloop1_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1770 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
[   91.108159] H systemd[659]: Failed to wait for device to be initialized: Connection timed out
...
[   91.415844] H systemd[658]: Device 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity is not active.
[   91.417513] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=1834 reply_cookie=0 signature=so error-name=n/a error-message>
[   91.418833] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/sys_2ddevices_2dvirtual_2dblock_2ddm_5cx2d1_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged c>
[   91.420150] H systemd[658]: Failed to deactivate encrypted partition 71209f8191fb04d7073cbadf9a557a3064fab0e130bc7a0fe391897a060a2b98-verity
[   91.421750] H systemd[658]: Releasing crypt device /usr/share/minimal_1.verity context.
[   91.423286] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/sys_2ddevices_2dvirtual_2dblock_2ddm_5cx2d1_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged c>
[   91.424800] H systemd[658]: Releasing device-mapper backend.
[   91.425903] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2ddm_5cx2d1_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1837 reply_cookie=0 si>
[   91.427293] H systemd[658]: Closing read only fd for /usr/share/minimal_1.verity.
[   91.428436] H systemd[659]: Deactivating volume loop1-verity.
[   91.429784] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2ddm_5cx2d1_2edevice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=1838 reply_cookie=0 si>
[   91.431727] H systemd[659]: Allocating crypt device context by device loop1-verity.
[   91.433047] H systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobNew cookie=1839 reply_cookie=0 signature=uos error-name=n/a error-message>
[   91.434108] H systemd[658]: Closed loop /dev/loop2 (/usr/share/minimal_1.verity).
[   91.435032] H systemd[659]: dm versions   [ opencount flush ]   [16384] (*1)
[   91.436123] H systemd[659]: dm status loop1-verity  [ opencount noflush ]   [16384] (*1)
[   91.437361] H systemd[1]: dm-0: Processing udev action (SEQNUM=1908, ACTION=change)
[   91.438689] H systemd[1]: Added job dev-dm\x2d0.device/nop to transaction.
[   91.439926] H systemd[1]: dev-dm\x2d0.device: Installed new job dev-dm\x2d0.device/nop as 682
[   91.441050] H systemd[1]: Added job sys-devices-virtual-block-dm\x2d0.device/nop to transaction.
[   91.442085] H systemd[658]: minimal-app0-bar.service: Failed to set up mount namespacing: No such file or directory
[   91.443481] H systemd[658]: minimal-app0-bar.service: Failed at step NAMESPACE spawning cat: No such file or directory
```

Affected jobs:
  * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/10344/artifact//systemd-centos-ci/index.html
  * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/10345/artifact//systemd-centos-ci/index.html
  * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/10342/artifact//systemd-centos-ci/index.html
  * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/10337/artifact//systemd-centos-ci/index.html

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #24490.

### CODE REVIEW

File: src/shared/dissect-image.c [hunk 1]
```diff
@@ -2057,7 +2057,7 @@ static int verity_partition(
                         if (r == 0) {
                                 /* devmapper might say that the device exists, but the devlink might not yet have been
                                  * created. Check and wait for the udev event in that case. */
-                                r = device_wait_for_devlink(node, "block", 100 * USEC_PER_MSEC, NULL);
+                                r = device_wait_for_devlink(node, "block", 30 * USEC_PER_SEC, NULL);
```
Comment (bluca) [inline src/shared/dissect-image.c]: Uh this is way way too long for my use case, fast fallback is very important and 100ms was already quite high - note that this happens all the time because the kernel device-mapper is just bad

Comment (yuwata) [reply src/shared/dissect-image.c]: So, WDYT about using a environment variable?

Comment (bluca) [reply src/shared/dissect-image.c]: that would work, but can I set it for pid1?

Comment (bluca) [reply src/shared/dissect-image.c]: or what about, leave default as is, and set the env var in the test?

Comment (yuwata) [reply src/shared/dissect-image.c]: Yes, that's mostly for tests.

File: test/units/testsuite-29.sh [hunk 2]
```diff
@@ -5,6 +5,8 @@
 set -eux
 set -o pipefail
 
+export SYSTEMD_DISSECT_VERITY_TIMEOUT_SEC=30
```
Comment (bluca) [inline test/units/testsuite-29.sh:17]: this will only affect the local commands, no? but it's needed for PID1 too?

File: src/shared/dissect-image.c [hunk 3]
```diff
@@ -2055,9 +2055,28 @@ static int verity_partition(
                         if (!IN_SET(r, 0, -ENODEV, -ENOENT, -EBUSY))
                                 return log_debug_errno(r, "Checking whether existing verity device %s can be reused failed: %m", node);
                         if (r == 0) {
+                                usec_t timeout_usec = 100 * USEC_PER_MSEC;
+                                const char *e;
+
+                                /* On slower machines, like non-KVM vm, setting up device may take much time.
```
Comment (bluca) [inline src/shared/dissect-image.c]: "take a long time"

File: test/units/testsuite-29.sh (hunk 2 above)
Comment (yuwata) [reply test/units/testsuite-29.sh:17]: Ah,,, indeed...

Comment (bluca) [reply test/units/testsuite-29.sh:17]: and also for systemd-portabled.service

**Comment by yuwata** [comment]
@bluca Thank you for the review. Now the env var is also set for PID1. PTAL.

**Review by bluca — APPROVED** [review]

**Review by mrc0mmand — APPROVED** [review]
