### PR TITLE
udev: cleanups for creating/removing device node symlinks

### LINKED ISSUE #20212: [udev] identically named partitions trigger pathological performance in link_update() & link_find_prioritized()
**systemd version the issue has been seen with**
> 248.3

**Used distribution**
> Fedora 34

**Linux kernel version used** (`uname -a`)
 > `Linux n5550.penurio.us 5.12.14-300.fc34.x86_64 #1 SMP Wed Jun 30 18:30:21 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Successful boot in a reasonable amount of time

**Unexpected behaviour you saw**
 > udev race condition(?) caused very long boot times and/or device timeouts when "large numbers" of block devices are attached.

**Steps to reproduce the problem**
 > Attempt to boot NAS with 5 data disks, each with 16 partitions installed.  (NAS boots fine when data disks are not installed.)

This is basically an upstream clone of an issue that was fixed in Red Hat Enterprise Linux 8.  Unfortunately, the Red Hat Bugzilla is not public, but you can see the pull request at https://github.com/redhat-plumbers/systemd-rhel8/pull/175.

From what I can tell, the problematic upstream commits are:
* https://github.com/systemd/systemd/commit/30f6dce62cb3a738b20253f2192270607c31b55b
* https://github.com/systemd/systemd/commit/996c83903da5bf8b371314b4207ff97afeef65a4

This is borne out by the fact that a test RPM built from https://github.com/systemd/systemd-stable/commit/a59b0a9f768f6e27b25f4f1bab6de08842e78d74 boots in the expected amount of time, and an RPM built from https://github.com/systemd/systemd-stable/commit/30f6dce62cb3a738b20253f2192270607c31b55b does not.

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes #20212, #19946, https://bugzilla.redhat.com/show_bug.cgi?id=1973857, and https://bugzilla.redhat.com/show_bug.cgi?id=1977994.

### CODE REVIEW

File: src/udev/udev-node.c [hunk 1]
```diff
@@ -232,6 +261,67 @@ size_t udev_node_escape_path(const char *src, char *dest, size_t size) {
...
+
+                if (symlink(data, filename) >= 0)
+                        return 0;
+
+                r = -errno;
+                if (r != -ENOENT)
+                        break;
+        }
+
+        return log_device_debug_errno(dev, errno, "Failed to create symbolic link %s: %m", filename);
```
Comment (poettering) [inline src/udev/udev-node.c]: errno → r

File: src/udev/udev-node.c [hunk 2]
```diff
@@ -278,10 +280,51 @@ static int update_stack_dir(sd_device *dev, const char *dirname, bool add) {
...
+                                log_device_debug_errno(dev, errno, "Failed to remove %s, ignoring: %m", filename);
+                }
+
+                if (rmdir(dirname) >= 0 || errno == ENOENT)
+                        return 0;
+
+                if (unlink_failed)
+                        return 0;
+
+                if ((st1.st_mode & S_IFMT) == 0)
```
Comment (poettering) [inline src/udev/udev-node.c]: maybe add comment here: `/* stat() failed */

File: src/udev/udev-node.c [hunk 3]
```diff
@@ -278,10 +280,51 @@ static int update_stack_dir(sd_device *dev, const char *dirname, bool add) {
...
+                                return 0;
+                        }
+
+                        if (!stat_inode_unmodified(&st1, &st2))
+                                return 0;
+
+                        log_device_debug(dev, "Symlink %s is removed, but timestamp of %s is not changed, updating timestamp after 10ms.",
+                                         filename, dirname);
+                        (void) usleep(10 * USEC_PER_MSEC);
+                        if (utimensat(AT_FDCWD, dirname, NULL, 0) < 0) {
```
Comment (poettering) [inline src/udev/udev-node.c]: hmm, why is this necssary? we operate on tmpfs here, we know that mtimes are properly updated there, why do this explicitly here?

File: src/udev/udev-node.c [hunk 4]
```diff
@@ -311,15 +354,37 @@ static int update_stack_dir(sd_device *dev, const char *dirname, bool add) {
...
+                        if (stat(dirname, &st2) < 0)
+                                return log_device_debug_errno(dev, errno, "Failed to stat %s, ignoring: %m", dirname);
+
+                        if (!stat_inode_unmodified(&st1, &st2))
+                                return 0;
+
+                        log_device_debug(dev, "Symlink %s is created, but timestamp of %s is not changed, updating timestamp after 10ms.",
+                                         filename, dirname);
+                        (void) usleep(10 * USEC_PER_MSEC);
+                        if (utimensat(AT_FDCWD, dirname, NULL, 0) < 0)
```
Comment (poettering) [inline src/udev/udev-node.c]: here too, why would the explicit mtime change be good here?

File: src/udev/udev-node.c [hunk 5]
```diff
@@ -481,45 +481,116 @@ static int link_update(sd_device *dev, const char *slink_in, bool add) {
...
+                if (device_has_devlink(dev, devlink))
                         continue;
 
                 log_device_debug(dev,
-                                 "Updating old device symlink '%s', which is no longer belonging to this device.",
-                                 name);
+                                 "Removing/updating old device symlink '%s', which is no longer belonging to this device.",
+                                 devlink);
+
+                r = link_update(dev, devlink, false);
```
Comment (poettering) [inline src/udev/udev-node.c]: maybe insert comment before third arg: `/* add= */`

File: src/udev/udev-node.c [hunk 6]
```diff
@@ -481,45 +481,116 @@ static int link_update(sd_device *dev, const char *slink_in, bool add) {
...
+                if (r < 0)
+                        log_device_warning_errno(dev, r,
+                                                 "Failed to remove/update device symlink '%s', ignoring: %m",
+                                                 devlink);
+        }
+
+        /* create/update symlinks, add symlinks to name index */
+        FOREACH_DEVICE_DEVLINK(dev, devlink) {
+                r = link_update(dev, devlink, true);
```
Comment (poettering) [inline src/udev/udev-node.c]: ditto

File: src/udev/udev-node.c [hunk 7]
```diff
@@ -481,45 +481,116 @@ static int link_update(sd_device *dev, const char *slink_in, bool add) {
         return -ELOOP;
 }
 
-int udev_node_update_old_links(sd_device *dev, sd_device *dev_old) {
-        const char *name;
+static int xsprintf_dev_num_path_from_sd_device(sd_device *dev, char **ret) {
```
Comment (poettering) [inline src/udev/udev-node.c]: maybe call this `device_get_devpath_by_devnum()`?

i.e. this is in many ways like device_get_depth(), but returns the major/minor path, instead of the primary device node path.

**Review by poettering — CHANGES_REQUESTED** [review]

File: src/udev/udev-node.c (hunk 3 above)
Comment (yuwata) [reply src/udev/udev-node.c]: Please read the comments in the revised code.

**Comment by yuwata** [comment]
@poettering Thank you for the review. All suggestions are applied. Also, comments which replies the question about `utimensat()` is added in the code. PTAL.

Note @ipilcher tested the previous version, and the performance looks great. See https://github.com/systemd/systemd/issues/20212#issuecomment-910431835.

File: src/udev/udev-node.c [hunk 8]
```diff
@@ -447,6 +451,14 @@ static int link_update(sd_device *dev, const char *slink_in, bool add) {
                 _cleanup_free_ char *target = NULL;
                 struct stat st1 = {}, st2 = {};
 
+                if (i > 0) {
+                        usec_t delay = MIN_RANDOM_DELAY + random_u64_range(MAX_RANDOM_DELAY - MIN_RANDOM_DELAY);
```
Comment (poettering) [inline src/udev/udev-node.c:451]: as discussed in that other bug, maybe do:

```
usec_t delay = MIN_RANDOM_DELAY + random_u64_range((1 << MIN(10,  i)) * (MAX_RANDOM_DELAY - MIN_RANDOM_DELAY));
```

i.e. grow the max delay exponentially on each invocation.

(I topped this out at factor 1024, not sure what the right value to pick there is)

**Comment by poettering** [comment]
lgtm. i think this could be merged as is. but if @ipilcher is interested the delay loop could be tweaked further, with exponentially increasing sleeps, as proposed, to maybe address the issues he still saw for very large number of devices.

**Comment by yuwata** [comment]
OK. I will prep a patch for the exponentially increasing sleeps.

**Comment by ipilcher** [comment]
> OK. I will prep a patch for the exponentially increasing sleeps.

@yuwata 

Trying to determine if the "upward curve" if anything more than a theoretical concern ...

I created a VM with 1,024 identically named partitions (8 disks x 128 partitions).  The CPU usage "blip" shown by `virt-manager` is definitely larger when I load the `virtio_scsi` module, but it doesn't peg the 4 VCPUs in the VM, and there's no noticeable delay in processing the new devices.

My additional logging indicates that `link_find_prioritized()` was called 4,324 times, and it looped 702,804 times.  Elapsed time from loading the module until the last udev worker exited was 7 seconds.

It's your call whether it's worthwhile to spend additional time to further improve the situation.

**Comment by yuwata** [comment]
@ipilcher Thank you for the test result.

**Comment by yuwata** [comment]
@bsdnet If you'd like, please prepare a PR on systemd-stable repository. Thank you.

**Comment by bsdnet** [comment]
See the PR https://github.com/systemd/systemd-stable/pull/200
