### PR TITLE
systemctl: check triggering units only for stopped units

### LINKED ISSUE #11088: systemctl reports wrong status after denied polkit action
**systemd version the issue has been seen with**

v239

**Used distribution**

Debian sid

This is related to https://gitlab.freedesktop.org/polkit/polkit/issues/74
After applying the fix for policykit-1 and trying to start a service as a user with ```uid=4000000000```, I get the following output:
```
test@debian:~$ id
uid=4000000000(test) gid=4000000000(test) Gruppen=4000000000(test)
test@debian:~$ systemctl stop rsyslog
**
ERROR:pkttyagent.c:156:main: assertion failed: (polkit_unix_process_get_uid (POLKIT_UNIX_PROCESS (subject)) >= 0)
Failed to stop rsyslog.service: Interactive authentication required.
See system logs and 'systemctl status rsyslog.service' for details.
Warning: Stopping rsyslog.service, but it can still be activated by:
  syslog.socket
```
The warning ```Warning: Stopping rsyslog.service, but it can still be activated by:
  syslog.socket``` is misleading, as rsyslog was not actually stopped

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #11088.

### CODE REVIEW

File: src/systemctl/systemctl.c [hunk 1]
```diff
@@ -3180,12 +3184,18 @@ static int start_unit(int argc, char *argv[], void *userdata) {
                         return log_error_errno(r, "Failed to attach bus to event loop: %m");
         }
 
+        if (method_is_stop)
+                names_stopped = newa0(char*, strv_length(names) + 1);
```
Comment (poettering) [inline src/systemctl/systemctl.c]: i am pretty sure this will trip up static checkers sooner or laters, because they are unlikely to understand that names_stopped not being initialized doesn't matter if "method_is_stop" is not true

**Comment by yuwata** [comment]
@poettering Thank you for the comment. I think now the code is safer than previous. PTAL.
