### PR TITLE
core: rewrite IPAddressAllow/Deny= parser

### LINKED ISSUE #20608: timesyncd tries to set time forever when it can't set the system's time
I think in this situation, `timesyncd` should stop retrying:

```
09:38 $ /lib/systemd/systemd-timesyncd 
Directory "/var/lib/systemd/timesync" already exists, but is owned by 100:102 (1001:1001 was requested), refusing.
Failed to call clock_adjtime(): Operation not permitted
Initial synchronization to time server 91.189.91.157:123 (ntp.ubuntu.com).
Failed to call clock_adjtime(): Operation not permitted
[...]
```

and it just keeps on going forever (or at least once per minute for more than 30m :).

### LINKED ISSUE #20680: systemd freezes for minutes with around 4000 IpAddressAllow lines on a unit file
**systemd version the issue has been seen with**
 > 248.7

**Used distribution**
 > Fedora 34

**Linux kernel version used** (`uname -a`)

 > `5.13.13`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > It should perform fast on boot

**Unexpected behaviour you saw**
 >  It hangs for several minutes, doing timeouts when running multiple systemctl commands and PID 1 consuming 100% CPU.

**Steps to reproduce the problem**
 > `systemctl edit sshd`
Add:
```
[Service]
IPAccounting=yes
IPAddressDeny=any
```

Then get some IPv4/IPv6 block lists, e.g. from ipverse.net and prepend lines with `IpAddressAllow=` and append them. Save and quit. It will timeout when applying the systemctl daemon-reload. In case of a reboot it freezes for a while in the switching root step.

Tested with 280 lines, systemd-analyze blame took less than 1 second for `initrd-switch-root.service`. Tested with around 4000 lines, systemd-analyze took over 7 minutes to boot.

### PR DESCRIPTION
**Pull request by yuwata**
Previously, if a unit file contains `n` `IPAddressAllow/Deny=` lines, then the computational order of parsing the file was `O(n^3)`. This PR makes it `O(n log n)`.

Fixes #20680.

### CODE REVIEW

File: src/shared/in-addr-prefix-util.c [hunk 1]
```diff
@@ -0,0 +1,252 @@
...
+
+int in_addr_prefixes_reduce(Set *prefixes) {
+        _cleanup_set_free_ Set *ipv4_prefixlens = NULL, *ipv6_prefixlens = NULL;
+        struct in_addr_prefix *p;
+        int r;
+
+        SET_FOREACH(p, prefixes) {
+                Set **prefixlens = p->family == AF_INET ? &ipv4_prefixlens : &ipv6_prefixlens;
+
+                r = set_ensure_put(prefixlens, NULL, UINT8_TO_PTR(p->prefixlen + 1));
```
Comment (bluca) [inline src/shared/in-addr-prefix-util.c]: what's the +1 here for?

File: src/shared/in-addr-prefix-util.c [hunk 2]
```diff
@@ -0,0 +1,252 @@
...
+                                        return log_oom();
+                        }
+
+                } else if (is_localhost(word)) {
+                        /* "localhost" is a shortcut for 127.0.0.0/8 and ::1/128 */
+
+                        if (ltype != AF_INET6) {
+                                r = in_addr_prefix_add(prefixes, &(struct in_addr_prefix) {
+                                                .family = AF_INET,
+                                                .address.in.s_addr = htobe32(0x7f000000),
```
Comment (bluca) [inline src/shared/in-addr-prefix-util.c]: `#define` for this magic number? For readability

File: src/shared/in-addr-prefix-util.c [hunk 3]
```diff
@@ -0,0 +1,252 @@
...
+                                                .address.in.s_addr = htobe32((UINT32_C(169) << 24) | (UINT32_C(254) << 16)),
+                                                .prefixlen = 16 });
+                                if (r < 0)
+                                        return log_oom();
+                        }
+
+                        if (ltype != AF_INET) {
+                                r = in_addr_prefix_add(prefixes, &(struct in_addr_prefix) {
+                                                .family = AF_INET6,
+                                                .address.in6.s6_addr32[0] = htobe32(0xfe800000),
```
Comment (bluca) [inline src/shared/in-addr-prefix-util.c]: same, `#define`

**Comment by bluca** [comment]
Can you add more details to the commit message explaining how it went from n^3 to nlogn?

File: src/shared/in-addr-prefix-util.c (hunk 1 above)
Comment (poettering) [reply src/shared/in-addr-prefix-util.c]: because prefixlen == 0 happens IRL and for Set/Hashmap it should be something different than NULL, but the plain cast would be

File: src/shared/in-addr-prefix-util.c [hunk 4]
```diff
@@ -0,0 +1,252 @@
...
+        copy = newdup(struct in_addr_prefix, prefix, 1);
+        if (!copy)
+                return -ENOMEM;
+
+        (void) in_addr_mask(copy->family, &copy->address, copy->prefixlen);
+        return set_ensure_consume(prefixes, &in_addr_prefix_hash_ops_free, copy);
+}
+
+int in_addr_prefixes_reduce(Set *prefixes) {
+        _cleanup_set_free_ Set *ipv4_prefixlens = NULL, *ipv6_prefixlens = NULL;
```
Comment (poettering) [inline src/shared/in-addr-prefix-util.c]: this these bit masks would only contain 32 resp. 128 entries at max, no?

wouldn't it be better to just do a packet bit array? i.e. `uint64_t prefixlen_max[128 / sizeof(uint64_t)]` and then set a bit for each prefixlen known?

of course this would mean iterating through the defined prefixlens would then take 128 iterations, but that sounds much simpler/quicker than all the memory allocation the Set requires, no?

and before entering the other loop below you could even convert this bitmask into an array of sorted prefixlens, then it would be densely packed and ridiculously fast to iterate through the defined prefixlens.

File: src/shared/in-addr-prefix-util.c [hunk 5]
```diff
@@ -0,0 +1,252 @@
...
+                        return 0;
+                }
+                if (r == 0)
+                        return 0;
+
+                if (streq(word, "any")) {
+                        /* "any" is a shortcut for 0.0.0.0/0 and ::/0 */
+
+                        if (ltype != AF_INET6) {
+                                r = in_addr_prefix_add(prefixes, &(struct in_addr_prefix) { .family = AF_INET });
```
Comment (poettering) [inline src/shared/in-addr-prefix-util.c]: given this compound literal is used twice, maybe add a `#define` for it?

File: src/shared/in-addr-prefix-util.c [hunk 6]
```diff
@@ -0,0 +1,252 @@
...
+                                if (r < 0)
+                                        return log_oom();
+                        }
+
+                        if (ltype != AF_INET) {
+                                r = in_addr_prefix_add(prefixes, &(struct in_addr_prefix) { .family = AF_INET6 });
```
Comment (poettering) [inline src/shared/in-addr-prefix-util.c]: ditto?

File: src/core/cgroup.h [hunk 7]
```diff
@@ -153,8 +152,11 @@ struct CGroupContext {
         bool memory_min_set;
         bool memory_low_set;
 
-        LIST_HEAD(IPAddressAccessItem, ip_address_allow);
-        LIST_HEAD(IPAddressAccessItem, ip_address_deny);
+        Set *ip_address_allow;
+        Set *ip_address_deny;
+        /* in_addr_prefixes_reduce() is called. */
+        bool ip_address_allow_reduced;
+        bool ip_address_deny_reduced;
```
Comment (poettering) [inline src/core/cgroup.h:160]: `:1` on bot?

File: src/core/cgroup.h [hunk 8]
```diff
@@ -153,8 +152,11 @@ struct CGroupContext {
         bool memory_min_set;
         bool memory_low_set;
 
-        LIST_HEAD(IPAddressAccessItem, ip_address_allow);
-        LIST_HEAD(IPAddressAccessItem, ip_address_deny);
+        Set *ip_address_allow;
+        Set *ip_address_deny;
+        /* in_addr_prefixes_reduce() is called. */
```
Comment (poettering) [inline src/core/cgroup.h]: is → has been

or maybe

```
/* These two flags indicate that redundant entries have been removed from ip_address_allow/ip_address_deny, i.e. in_addr_prefixes_reduce() has already been called. */
```

**Review by poettering — CHANGES_REQUESTED** [review]
Looks great to me. Just wondering if using a `Set` for the prefixlens is the best choice, given that it has at max 128 entries (see above), but maybe I am overthinking this.

File: src/core/cgroup.h (hunk 7 above)
Comment (yuwata) [reply src/core/cgroup.h:160]: Unfortunately, it cannot. In bpf-firewall.c, pointers to them are used.

**Comment by yuwata** [comment]
@bluca and @poettering Thank you for your review. All suggestions, except for adding `:1`, are applied. Also, tests for the new `in_addr_prefix` related functions are added, and two trivial commits are added. PTAL.

File: src/shared/in-addr-prefix-util.c [hunk 9]
```diff
@@ -0,0 +1,324 @@
...
+        copy = newdup(struct in_addr_prefix, prefix, 1);
+        if (!copy)
+                return -ENOMEM;
+
+        (void) in_addr_mask(copy->family, &copy->address, copy->prefixlen);
+        return set_ensure_consume(prefixes, &in_addr_prefix_hash_ops_free, copy);
+}
+
+int in_addr_prefixes_reduce(Set *prefixes) {
+        uint64_t ipv4_prefixlen_bits = 0, ipv6_prefixlen_bits[128 / sizeof(uint64_t)] = {};
```
Comment (poettering) [inline src/shared/in-addr-prefix-util.c]: i guess uint64_t for ipv4_prefixlent_bits works, but it's still a surprising choice given you need exactly 32bits here. So maybe use uint32_t here, simply to be less surprising?

File: src/shared/in-addr-prefix-util.c [hunk 10]
```diff
@@ -0,0 +1,324 @@
...
+                        else
+                                ipv4_prefixlen_bits |= UINT64_C(1) << (p->prefixlen - 1);
+                        break;
+                case AF_INET6:
+                        assert(p->prefixlen <= 128);
+                        if (p->prefixlen == 0)
+                                ipv6_has_any = true;
+                        else
+                                ipv6_prefixlen_bits[(p->prefixlen - 1) / sizeof(uint64_t)] |=
+                                        UINT64_C(1) << ((p->prefixlen - 1) % sizeof(uint64_t));
```
Comment (poettering) [inline src/shared/in-addr-prefix-util.c:125]: hmm, don't we have a macro for this somewhere? if not we should

Comment (yuwata) [reply src/shared/in-addr-prefix-util.c:125]: Yeah, but I'd like to leave that to another PR.

**Comment by yuwata** [comment]
@poettering Thank you for the suggestions. Upgrading the green label.

**Review by bluca — APPROVED** [review]
lgtm
