### PR TITLE
networkd: DHCP client do not get into a loop while setting MTU

### LINKED ISSUE #6593: networkd: UseMTU causes networkd to crash and not set MTU
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> Container Linux

### In case of bug report: Expected behaviour you didn't see

> The network interface is configured with the MTU from the DHCP lease

### In case of bug report: Unexpected behaviour you saw

> The network interface is configured with the new MTU. It goes down to configure itself. networkd then handles the link going down and sets the MTU back to the original MTU. The link comes back up and networkd crashes.

### In case of bug report: Steps to reproduce the problem

> 

1.  Have a network card that goes down and comes back up when the mtu changes (e1000 will do this)
2.  Set UseMTU to true in the [DHCP] section of a network file.
3.  Have a DHCP server which changes the mtu to 9000
4.  Start networkd
5.  Networkd will crash when the interface comes up from reconfiguring

I think what's happening is when networkd gets the lease with the MTU option it sends a rtnl message to configure the iface to the new mtu asynchonously, then sends the message to configure the iface's address, also asynchonously, with the callback `dhcp4_address_handler`. The iface then goes down to reconfigure. networkd notices this, and tears down all of the state (including the lease structure) associated with that link. The interface then comes up, and the kernel replies to the message to configure the address, triggering the `dhcp4_address_handler` callback. This then calls `link_set_dhcp_routes` which asserts the lease structure is non-NULL and crashes.

I have a [fix](https://github.com/systemd/systemd/pull/6594) that prevents crashing by returning if the lease or network is NULL instead of asserting it, but networkd will still fail to ever set the MTU if the interface goes down to reconfigure.

To actually fix the problem, we could set a timeout when the mtu changes. The link will then go down, come back up, and get a new lease which will not set the MTU (since it will be the same). When the timer expires, if the interface hasn't gotten a new lease, reset the MTU to the old one. The interface will go down, but come back up with the correct MTU, but then the second time it gets a lease, it will already have the correct MTU and not go down again. Does that seem reasonable?

See also: 
 * https://github.com/coreos/bugs/issues/1827 (has detailed repro steps)
 * https://github.com/coreos/bugs/issues/2031

### PR DESCRIPTION
**Pull request by ssahani**
Some devices get reset itself while setting the MTU. we get into a LOOP .
Once the MTU changed then the DHCP client talking with DHCP server never stops.
networkd gets into a loop and generates endless DHCP requests.

fixes #6593

### CODE REVIEW

**Comment by yuwata** [comment]
I hope that #7380 is also fixed by this PR.

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -3097,6 +3104,9 @@ static int link_carrier_lost(Link *link) {
 
         assert(link);
 
+        if (link->setting_mtu == true)
```
Comment (keszybz) [inline src/network/networkd-link.c]: Drop " == true" everywhere, we don't compare booleans like that.

Comment (ssahani) [reply src/network/networkd-link.c]: updated

**Comment by keszybz** [comment]
```
190/250 test-resolve                            TIMEOUT 30.01 s
```

**Comment by keszybz** [comment]
@ssahani any chance you could look into Fedora CI failures? All recent PRs fail the same way.

File: src/network/networkd-link.c [hunk 2]
```diff
@@ -1660,6 +1662,11 @@ static int link_acquire_conf(Link *link) {
 
         assert(link);
 
+        if (link->setting_mtu) {
+                link->setting_mtu = false;
```
Comment (poettering) [inline src/network/networkd-link.c:1666]: it would be really good, to have a comment here that explains what this is about!

**Comment by ssahani** [comment]
Sure will add
