### PR TITLE
properly acquire os-release file from containers

### LINKED ISSUE #10549: machinectl list does not show os name and version
**systemd version the issue has been seen with**

v239

**Used distribution**
 
Debian sid

This is from the downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911231

```
root@pluto:~# systemctl --version
systemd 239
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
root@pluto:~# debootstrap sid /var/lib/machines/sid
...
I: Base system installed successfully.
root@pluto:~# machinectl list
No machines.
root@pluto:~# machinectl start sid
root@pluto:~# machinectl list
MACHINE CLASS     SERVICE        OS VERSION ADDRESSES
sid     container systemd-nspawn -  -       -        

1 machines listed.
```
With v232, os version and name are shown.

### PR DESCRIPTION
**Pull request by poettering**
Since d58ad743f98b3a88de961462fb7adedbf30f727d we are using chase_symlinks() to find the os-release file of a container image. For this to work we must be able to convert an O_PATH fd to a regular fd by opening /proc/self/fd/. That works correctly only if we are a proper member of the destination pidns. Previously we didn't do this correctly, as we didn't fork a second time after doing setns() on the pidns. With this we correct that.

Fixes #10549

### CODE REVIEW

**Comment by keszybz** [comment]
Pfff, another "fun" review. Why can't all this be nice and simple?

File: src/basic/process-util.c [hunk 1]
```diff
@@ -1409,6 +1409,60 @@ int safe_fork_full(
...
+                int mntns_fd,
+                int netns_fd,
+                int userns_fd,
+                int root_fd,
+                pid_t *ret_pid) {
+
+        int r;
+
+        /* This is much like safe_fork(), but forks twice, and joins the specified namespaces in the middle
+         * process. This ensures that we are fully a member of the destination namespace, with pidns an all, so that
```
Comment (keszybz) [inline src/basic/process-util.c:1428]: and
