### PR TITLE
systemctl: update 'show' command formats

### LINKED ISSUE #8064: "systemctl show --property=ListenStream systemd-journald" fails (so does ListenDatagram)
### Submission type
 - Bug report

### systemd version the issue has been seen with
237-1

### Used distribution

debian unstable

i can extract all the properties of a `.socket` unit file listed in `systemctl show` using the `--proprerty=` argument *except* for two:

 * `ListenStream`
 * `ListenDatagram`

here's an example loop showing that those two values are present in the initial `show` output, but empty when requested directly as `--property`: 

```
systemctl show systemd-journald.socket | grep ^Listen
for x in $(systemctl show systemd-journald.socket | cut -f1 -d=); do
   out=$(systemctl show "--property=$x" systemd-journald.socket)
   if [ -z "$out" ]; then
      echo "$x"
   fi
done
```

I would have expected `systemctl show --property=ListenStream systemd-journald` to emit `/run/systemd/journal/stdout`

### PR DESCRIPTION
**Pull request by yuwata**
In the `systemctl show` command, we usually use the dbus field names. So, let's use it also for `Paths=`, `Listen=`, `Timers{Monotonic,Calendar}=`, and `EnvironmentFiles=`.

Fixes #8064.

### CODE REVIEW

**Comment by yuwata** [comment]
(Ouch! I made a mistake in the last commit. I will fix it.)

**Comment by yuwata** [comment]
Updated.

File: src/systemctl/systemctl.c [hunk 1]
```diff
@@ -4944,6 +4944,29 @@ static int print_property(const char *name, sd_bus_message *m, const char *conte
...
+
+                        r = sd_bus_message_enter_container(m, SD_BUS_TYPE_ARRAY, "(sst)");
+                        if (r < 0)
+                                return bus_log_parse_error(r);
+
+                        while ((r = sd_bus_message_read(m, "(sst)", &base, &spec, &next_elapse)) > 0) {
+                                char timespan[FORMAT_TIMESPAN_MAX];
+
+                                print_prop(name, "{ %s=%s ; next_elapse=%s }", base, spec,
+                                           format_timespan(timespan, sizeof(timespan), next_elapse, 0));
```
Comment (keszybz) [inline src/systemctl/systemctl.c]: Hmm, I get nonsensical values in output:
```console
$ systemctl list-timers unbound*
NEXT                         LEFT    LAST                         PASSED  UNIT                 ACTIVATES
Sat 2018-02-03 00:00:00 CET  8h left Fri 2018-02-02 00:00:22 CET  15h ago unbound-anchor.timer unbound-anchor.service

1 timers listed.
$  build/systemctl show -p TimersCalendar unbound-anchor.timer
TimersCalendar={ OnCalendar=*-*-* 00:00:00 ; next_elapse=48y 1month 2d 12h 30min }
$ build/busctl introspect org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/unbound_2danchor_2etimer |grep TimersCalendar
.TimersCalendar                     property  a(sst)    1 "OnCalendar" "*-*-* 00:00:00" 15176…00 emits-invalidation
```

File: src/systemctl/systemctl.c [hunk 2]
```diff
@@ -4907,10 +4907,7 @@ static int print_property(const char *name, sd_bus_message *m, const char *conte
                                 return bus_log_parse_error(r);
 
                         while ((r = sd_bus_message_read(m, "(ss)", &type, &path)) > 0)
-                                if (arg_value)
-                                        puts(path);
-                                else
-                                        printf("Listen%s=%s\n", type, path);
+                                print_prop(name, "%s (%s)", path, type);
```
Comment (keszybz) [inline src/systemctl/systemctl.c:4910]: Hmm, I don't think this is an improvement... This output is much harder to use in scripts, grep, etc. Why not go the other way, and fix the query code so that `systemctl show -p ListenStream` does the expected thing?

File: src/systemctl/systemctl.c [hunk 3]
```diff
@@ -4889,7 +4889,7 @@ static int print_property(const char *name, sd_bus_message *m, const char *conte
                                 return bus_log_parse_error(r);
 
                         while ((r = sd_bus_message_read(m, "(ss)", &type, &path)) > 0)
-                                print_prop(type, "%s", path);
+                                print_prop(name, "%s (%s)", path, type);
```
Comment (keszybz) [inline src/systemctl/systemctl.c:4892]: Same here.

File: src/systemctl/systemctl.c (hunk 2 above)
Comment (yuwata) [reply src/systemctl/systemctl.c:4910]: Hmm... `systemctl show -p` does not take unit settings, but takes dbus properties. E.g., it supports `*USec` instead of `*Sec`:
```
$ systemctl show -p RestartUSec systemd-journal.service
RestartUSec=100ms
$ systemctl show -p RestartSec systemd-journal.service
```
So, I think making `-p` support to map from a unit settings to the relevant dbus property may be a good idea, but it is not a scope of this PR.

File: src/systemctl/systemctl.c (hunk 1 above)
Comment (yuwata) [reply src/systemctl/systemctl.c]: Ouch! The value is not timespan but timestamp. I've updated.

**Comment by yuwata** [comment]
Updated. Now, the 'nonsensical values' in TimersCalendar is fixed. I want to move the other point by @keszybz to other PRs. I think the current objective of `systemctl show` command is just show the dbus properties (in human or script readable format).

File: src/systemctl/systemctl.c (hunk 2 above)
Comment (keszybz) [reply src/systemctl/systemctl.c:4910]: Makes sense.
