### PR TITLE
journal-gatewayd: fix segfault with certain request

### LINKED ISSUE #3873: systemd-journal-gatewayd crashes if request has `follow` and unmatched `KEY=match` parameter
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

systemd 231
### Used distribution

Arch Linux
### In case of bug report: Expected behaviour you didn't see

systemd-journal-gatewayd doesn't crash
### In case of bug report: Unexpected behaviour you saw

systemd-journal-gatewayd crashes as follows:

```
$ curl http://localhost:19531/entries\?follow\&FOO\=bar
curl: (18) transfer closed with outstanding read data remaining
$ sudo systemctl status systemd-journal-gatewayd
● systemd-journal-gatewayd.service - Journal Gateway Service
   Loaded: loaded (/usr/lib/systemd/system/systemd-journal-gatewayd.service; indirect; vendor preset: disabled)
   Active: failed (Result: signal) since 수 2016-08-03 16:47:03 KST; 3s ago
     Docs: man:systemd-journal-gatewayd(8)
  Process: 6790 ExecStart=/usr/lib/systemd/systemd-journal-gatewayd (code=killed, signal=SEGV)
 Main PID: 6790 (code=killed, signal=SEGV)

 8월 03 13:03:41 naomint systemd[1]: Started Journal Gateway Service.
 8월 03 16:47:03 naomint systemd[1]: systemd-journal-gatewayd.service: Main process exited, code=killed, status=11/SEGV
 8월 03 16:47:03 naomint systemd[1]: systemd-journal-gatewayd.service: Unit entered failed state.
 8월 03 16:47:03 naomint systemd[1]: systemd-journal-gatewayd.service: Failed with result 'signal'.
```
### In case of bug report: Steps to reproduce the problem
1. Start systemd-journald-gatewayd
   
   `sudo systemctl start systemd-journal-gatewayd`
2. Request logs with `follow` and `KEY=match` parameter that doesn't match any log entry.
   
   `curl http://localhost:19531/entries?follow&FOO=bar`

### PR DESCRIPTION
**Pull request by eungjun-yi**
When client requests to get logs with `follow` and `KEY=match` that doesn't
match any log entry, journal-gatewayd segfaulted.

This fixes #3873.

### CODE REVIEW

**Comment by keszybz** [comment]
This fixes the segfault, but I don't think that the correct solution. The failure only happens when follow is specified. With your patch an error would be returned, but what should happen instead is that we should return nothing and wait for matching entries to appear. (E.g. if the match is the MESSAGE_ID=fc2e22bc6ee647b6b90729ab34a250b1 and we are waiting for a coredump, we cannot assume that at least one will be available when we start. It's OK to get no entries initially with follow.)

**Comment by eungjun-yi** [comment]
@keszybz Okay, I'll retry it.

File: src/journal-remote/journal-gatewayd.c [hunk 1]
```diff
@@ -239,6 +239,10 @@ static ssize_t request_reader_entries(
                 m->size = (uint64_t) sz;
         }
 
+        if (m->tmp == NULL && m->follow) {
+                return (ssize_t) 0;
+        }
```
Comment (keszybz) [inline src/journal-remote/journal-gatewayd.c]: Please don't use {} around a single statement (see CODING_STYLE).

The cast is not needed, 0 is already a signed integer, and the compiler will do the size promotion automatically if necessary.

Comment (keszybz) [inline src/journal-remote/journal-gatewayd.c]: Please add 'Fixes #3873' to the commit description so that github will close the issue automaticallly.

Comment (eungjun-yi) [inline src/journal-remote/journal-gatewayd.c]: Thanks for review. I've updated it.

**Comment by keszybz** [comment]
Thanks!
