### PR TITLE
logind: remember our idle state and use it to detect idle level transitions

### LINKED ISSUE #16391: systemd: logind parameters "IdleAction=Lock" is not working
**systemd version the issue has been seen with**
> Version: 241-7

**Used distribution**
 >Debian 10.4 Desktop

**Expected behaviour you didn't see**
> In logind.conf `IdleAction=Lock` should send `Lock` event when system is Idle

**Unexpected behaviour you saw**
 >Not received any `Lock` event After the above configuration and restart of system, 

**Steps to reproduce the problem**
* Disable other Auto Lock features in desktop environment.
* Set 'Blank screen' timeout to 5min
* Configured the logind for recieving the `Lock` event action after reaching system Idle.
logind.conf
```
[Login]
IdleAction=lock
IdleActionSec=1min
```
* Restart the system and waited using a sample application which is registered for dbus event "Lock"
* waited for more than 10min after system lid is off, not received any "Lock" event, and when i saw the status logs the idle action was initiating but no dbus event generated
```
========================================================================================
● systemd-logind.service - Login Service
   Loaded: loaded (/lib/systemd/system/systemd-logind.service; static; vendor
preset: enabled)
   Active: active (running) since Tue 2020-06-16 19:48:42 IST; 2 days ago
     Docs: man:systemd-logind.service(8)
           man:logind.conf(5)
           https://www.freedesktop.org/wiki/Software/systemd/logind
           https://www.freedesktop.org/wiki/Software/systemd/multiseat
 Main PID: 634 (systemd-logind)
   Status: "Processing requests..."
    Tasks: 1 (limit: 4915)
   Memory: 2.6M
   CGroup: /system.slice/systemd-logind.service
           └─634 /lib/systemd/systemd-logind

Jun 19 18:09:08 debian systemd-logind[634]: System idle. Taking action.
Jun 19 18:10:38 debian systemd-logind[634]: System idle. Taking action.
Jun 19 18:12:08 debian systemd-logind[634]: System idle. Taking action.
Jun 19 18:13:38 debian systemd-logind[634]: System idle. Taking action.
Jun 19 18:15:08 debian systemd-logind[634]: System idle. Taking action.
========================================================================================
```
With curiosity i have checked the source code and after applying the below change i could see the `Lock` event is generating and  my sample application could recieve it.

```diff
diff --git a/src/login/logind.c b/src/login/logind.c
index 95ec0a57c6..ea505ceed8 100644
--- a/src/login/logind.c
+++ b/src/login/logind.c
@@ -1019,7 +1019,7 @@ static int manager_dispatch_idle_action(sd_event_source
*s, uint64_t t, void *us
                     (m->idle_action_not_before_usec <= 0 || n >=
m->idle_action_not_before_usec + m->idle_action_usec)) {
                         log_info("System idle. Taking action.");

-                        manager_handle_action(m, 0, m->idle_action, false,
false);
+                        manager_handle_action(m, 0, m->idle_action, false,
true);
                         m->idle_action_not_before_usec = n;
                 }
```
Is there any specific reason blocking the "Lock" action in the [source code](https://github.com/systemd/systemd/blob/d7b34e384108ff431401d942ec0daaf156ec27c1/src/login/logind-action.c#L94)?

can we apply the above change to the master branch?

Thanks,
venkata.

### PR DESCRIPTION
**Pull request by msekletar**
Fixes #16391

### CODE REVIEW

File: src/login/logind.c [hunk 1]
```diff
@@ -963,19 +963,35 @@ static int manager_dispatch_idle_action(sd_event_source *s, uint64_t t, void *us
...
+
+                        if (m->idle_action == HANDLE_LOCK && !is_edge)
+                                /* We are idle and we were before so we are actually not taking any action. */
+                                log_debug("System idle.");
+                        else
+                                log_info("System idle. Doing %s operation.", handle_action_to_string(m->idle_action));
+
+                        manager_handle_action(m, 0, m->idle_action, false, is_edge);
                         m->idle_action_not_before_usec = n;
+
```
Comment (keszybz) [inline src/login/logind.c]: Please drop this empty line.

File: src/login/logind.c [hunk 2]
```diff
@@ -963,19 +963,35 @@ static int manager_dispatch_idle_action(sd_event_source *s, uint64_t t, void *us
...
 
                 if (n >= since.monotonic + m->idle_action_usec &&
                     (m->idle_action_not_before_usec <= 0 || n >= m->idle_action_not_before_usec + m->idle_action_usec)) {
-                        log_info("System idle. Doing %s operation.", handle_action_to_string(m->idle_action));
+                        bool is_edge = false;
 
-                        manager_handle_action(m, 0, m->idle_action, false, false);
+                        /* We weren't idle previously or some activity happened while we were sleeping, and now we are
+                         * idle. Let's remember that for the next time and make this an edge transition. */
+                        if (!m->was_idle || since.monotonic > m->idle_action_not_before_usec) {
```
Comment (keszybz) [inline src/login/logind.c]: `>` → `>=`. We use `>=` everywhere.

**Review by keszybz — COMMENTED** [review]
This looks reasonable, but it's hard to have confidence. I was wondering if there are some other place where `was_idle` should be reset.

It'd be nice to get confirmation that this fixes the OP's issue.

**Comment by msekletar** [comment]
Updated. @keszybz PTAL.

Btw, regarding testing, so far I tested this manually. In my other PR that I have now opened (#23569) I am adding new integration test for logind so I will add test case for this once we merge both PR.

**Comment by yuwata** [comment]
Please add a test.

**Comment by keszybz** [comment]
Yeah. With some form of a test this would be much easier.

File: test/units/testsuite-35.sh [hunk 3]
```diff
@@ -360,6 +360,89 @@ EOF
...
+    if loginctl --no-legend | awk '{ print $3; }' | sort -u | grep -q testuser ; then
+        echo >&2 "Session of the \'testuser\' is already present."
+        return 1
+    fi
+
+    # IdleActionSec is set 1s but the accuracy of associated timer is 30s so we
+    # need to sleep in worst case for 31s to make sure timer elapsed. We sleep
+    # here for 35s to accomodate for any possible scheudling delays.
+    cat > /tmp/test.exp <<EOF
+spawn systemd-run -G -t -p PAMName=login -p User=testuser bash
```
Comment (yuwata) [inline test/units/testsuite-35.sh:402]: Not sure, but why not to simply run a script with `systemd-run`??

File: test/units/testsuite-35.sh [hunk 4]
```diff
@@ -360,6 +360,89 @@ EOF
...
+[Login]
+IdleAction=lock
+IdleActionSec=1s
+EOF
+    systemctl restart systemd-logind.service
+    systemctl service-log-level systemd-logind.service debug
+}
+
+teardown_idle_action_lock() {
+    set +e
```
Comment (yuwata) [inline test/units/testsuite-35.sh]: Please use subshell:
```
teardown_idle_action_lock() {(
    set +ex
    ...
)}
```

File: test/TEST-35-LOGIN/test.sh [hunk 5]
```diff
@@ -7,4 +7,14 @@ TEST_DESCRIPTION="LOGIN"
 # shellcheck source=test/test-functions
 . "${TEST_BASE_DIR:?}/test-functions"
 
+test_append_files() {
+    if command -v expect >/dev/null && command -v tclsh >/dev/null ; then
```
Comment (yuwata) [inline test/TEST-35-LOGIN/test.sh]: Please move this in `install_basic_tools()` in test-functions. The testing image is shared with other tests, hence these will not be included when multiple tests are executed, like our CIs do.

**Review by yuwata — CHANGES_REQUESTED** [review]

File: test/units/testsuite-35.sh (hunk 3 above)
Comment (msekletar) [reply test/units/testsuite-35.sh:402]: I am using expect because I want tty allocated and AFAICT you can't do systemd-run --pty from context where you don't have any tty.

File: test/test-functions [hunk 6]
```diff
@@ -1736,6 +1736,13 @@ install_basic_tools() {
     image_install -o ldconfig.real
     # for TEST-35-LOGIN
     image_install -o evemu-device evemu-event
+    if command -v expect >/dev/null && command -v tclsh >/dev/null ; then
+        # shellcheck disable=SC2016
+        version="$(tclsh <<< 'puts $tcl_version')"
+
+        image_install expect
+        inst_recursive /usr/lib64/tcl"$version" /usr/share/tcl"$version"
```
Comment (bluca) [inline test/test-functions:1744]: I missed this, right now the dependencies happen not to be installed in the ubuntu/debian tests, but if they were (intentionally or pulled in accidentally by something else), this would break, as the path is specific to 64bit rpm distros

Comment (bluca) [reply test/test-functions:1744]: on debian/ubuntu, `/usr/bin/tclsh` is a symlink to `/usr/bin/tclsh<version>`

Comment (bluca) [reply test/test-functions:1744]: there's also both `/usr/lib/tcl<version>` and multi-arch `/usr/lib/x86_64-linux-gnu/tcl<version>`, but no `/usr/share/tcl<version>`

Comment (yuwata) [reply test/test-functions:1744]: Ouch. Will address them.

Comment (yuwata) [reply test/test-functions:1744]: #23930.
