### PR TITLE
journal: do not remove spaces after identifier in syslog message

### LINKED ISSUE #9839: journald has started to strip leading spaces from messages received via the syslog socket
A long time ago ec5ff4445cca6a1d was merged, which made processing of syslog messages consistent with the "native" and "stream" protocols, where leading spaces aren't stripped to preserve indents (presumably so that backtraces look aesthetic :-)). This has effectively been changed in https://github.com/systemd/systemd/pull/9827 and it would be great to bring it back.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #9839 introduced by a6aadf4ae0bae185dc4c414d492a4a781c80ffe5 (#9827).

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx.

File: src/journal/test-journal-syslog.c [hunk 1]
```diff
@@ -31,15 +32,18 @@ static void test_syslog_parse_priority(const char *str, int priority, int ret) {
...
-        test_syslog_parse_identifier("pidu:  xxx", "pidu", NULL, 7);
-        test_syslog_parse_identifier("pidu xxx", NULL, NULL, 0);
-        test_syslog_parse_identifier(":", "", NULL, 1);
-        test_syslog_parse_identifier(":  ", "", NULL, 3);
-        test_syslog_parse_identifier("pidu:", "pidu", NULL, 5);
-        test_syslog_parse_identifier("pidu: ", "pidu", NULL, 6);
-        test_syslog_parse_identifier("pidu : ", NULL, NULL, 0);
+        test_syslog_parse_identifier("pidu[111]: xxx", "pidu", "111", "xxx", 11);
+        test_syslog_parse_identifier("pidu: xxx", "pidu", NULL, "xxx", 6);
+        test_syslog_parse_identifier("pidu:  xxx", "pidu", NULL, " xxx", 6);
```
Comment (evverx) [inline src/journal/test-journal-syslog.c:37]: I'd also add a comment with a link to https://github.com/systemd/systemd/pull/156#issuecomment-111172243 to make it a little bit easier to understand why only the first space is dropped. Looks great otherwise. Thank you!

**Comment by yuwata** [comment]
@evverx Thank you for the reference. I've added a comment in the source, and modified the commit message.
