### PR TITLE
util-lib: follow shell syntax for escape in quotes

### LINKED ISSUE #10659: EnvironmentFile= honours backward slashes (unexpectedly)
It is unexpected that when a file is fed to `EnvironmentFile=` variables' values containing backward slashes are processed as special.  The documentation does not mention such a behaviour and it just seems wrong. 

The expected behaviour would be if `systemd` parses the environment files as close to the way shell does as possible, i.e.:

    VAR1=\value
    VAR2="\value"
    VAR3='\value'

For `VAR1` the value should be `value` (since `\v` is in a bare string and is just `v`), but `VAR2` and `VAR3` should have values of `\value`.

Right now, `systemd` is resolving escapes unconditionally and it makes life very hard since you cannot source the same environment file from scripts (if there are backward slashes).

### PR DESCRIPTION
**Pull request by kragniz**
Fixes #10659.

### CODE REVIEW

File: src/basic/env-file.c [hunk 1]
```diff
@@ -225,10 +211,13 @@ static int parse_env_file_internal(
                 case DOUBLE_QUOTE_VALUE_ESCAPE:
                         state = DOUBLE_QUOTE_VALUE;
 
-                        if (!strchr(NEWLINE, c)) {
+                        if (c == '\"')
+                                value[n_value++] = c;
```
Comment (filbranden) [inline src/basic/env-file.c]: You need to do the GREEDY_REALLOC in this case as well.

I recommend something like:

```c
if (c == '\"' || !strchr(NEWLINE, c)) {
    if (!GREEDY_REALLOC(value, value_alloc, n_value+3))
        return -ENOMEM;
    if (c != '\"')
        value[n_value++] = '\\';
    value[n_value++] = c;
}
```

(Untested, might be incorrect...)

File: src/basic/env-file.c [hunk 2]
```diff
@@ -225,10 +211,13 @@ static int parse_env_file_internal(
...
+                        else if (!strchr(NEWLINE, c)) {
                                 if (!GREEDY_REALLOC(value, value_alloc, n_value+2))
```
Comment (filbranden) [inline src/basic/env-file.c:215]: So I think you need `n_value+3` here, since `n_value+2` was right for a single character and now you have two characters here...

File: src/basic/env-file.c [hunk 3]
```diff
@@ -225,10 +211,13 @@ static int parse_env_file_internal(
                 case DOUBLE_QUOTE_VALUE_ESCAPE:
                         state = DOUBLE_QUOTE_VALUE;
 
-                        if (!strchr(NEWLINE, c)) {
+                        if (c == '\"')
```
Comment (keszybz) [inline src/basic/env-file.c]: Please remove the backslash here, it's just confusing: `'"'`.

File: src/basic/env-file.c (hunk 1 above)
Comment (keszybz) [reply src/basic/env-file.c]: A GREEDY_REALLOC is needed, but I don't think the proposed code is good.
Maybe just
```C 
if (c == '"') {
        if (!GREEDY_REALLOC(value, value_alloc, n_value+2))
                return -ENOMEM;
        value[n_value++] = '"';
} else if (!strchr(NEWLINE, c)) {
       if (!GREEDY_REALLOC(value, value_alloc, n_value+3))
                 return -ENOMEM;
       value[n_value++] = '\\';
       value[n_value++] = c;
}

Comment (kragniz) [reply src/basic/env-file.c]: Good point, I'll make this change.

File: src/basic/env-file.c (hunk 3 above)
Comment (kragniz) [reply src/basic/env-file.c]: I agree that it's confusing, but it's what's done in the rest of this file. Should I change it everywhere?

Comment (keszybz) [reply src/basic/env-file.c]: Yes. As a separate commit though.

**Comment by kragniz** [comment]
I've added the GREEDY_REALLOC part and added a commit to remove all instances of `'\"'`.

@filbranden I like the idea of that test, I'll look at adding it as a follow-up PR

**Comment by poettering** [comment]
could you add a proper commit msg explaining what you are actually changing here?

**Comment by poettering** [comment]
looks ok to me, but i'd really like a longer commit msg explaining the effective changes this means. (and we need a NEWS entry for this too, but @keszybz volunteered to add that)

**Comment by poettering** [comment]
(actually both commits could use a etter commit msg, explaining what and why)

**Comment by kragniz** [comment]
@poettering I've updated the commit messages, please take a look

**Comment by poettering** [comment]
lgtm
