### PR TITLE
Networkd vs interface renaming

### LINKED ISSUE #7293: Race condition: interface renaming, udev vs. networkd
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 235

### Used distribution

> Debian, but irrelevant AFAICT

### In case of bug report: Expected behaviour you didn't see

> I can rename an interface with a udev rule or a .link file

### In case of bug report: Unexpected behaviour you saw

> networkd is faster and enables the interface before udev gets around to renaming it.
> Unfortunately, an interface that's up cannot be renamed

### In case of bug report: Steps to reproduce the problem

```
# cat /etc/systemd/network/10-en0.link:
[Match]
MACAddress=aa:bb:cc:dd:ee:ff

[Link]
MACAddressPolicy=none
Name=en0
```
Reboot a couple of times. Sometimes the interface is renamed correctly. Sometimes it is not.

Workaround:
```
# cat systemd-networkd.service.d/after-udev.conf 
[Service]
ExecStartPre=/sbin/udevadm settle
```

### PR DESCRIPTION
**Pull request by yuwata**
Previously, `networkd` does not synthesize 'move' uevent, and if an interface is passed through uevent or netlink and with valid udev database, the interface is assumed to be initialized.
But, if the interface renaming is requested, it induces move uevent. So, some racy situations between `networkd` and `udev` may exist.

This adds `ID_NET_RENAMING_TO` property to udev database when an interface renaming is requested, and the property will be dropped when the corresponding `move` uevent is processed. And this makes `networkd` check whether the property exists or not before configuring interfaces.

I am not sure, but this may fix #7293.

### CODE REVIEW

File: src/udev/udev-event.c [hunk 1]
```diff
@@ -732,6 +732,13 @@ static int rename_netif(UdevEvent *event) {
                                                 "but could not update sd_device object: %m",
                                                 ifindex, oldname, event->name);
 
+        /* Save new name in ID_NET_RENAMING_TO and drop that in the later move uevent. */
+        r = device_add_property(dev, "ID_NET_RENAMING_TO", event->name);
+        if (r < 0)
+                return log_device_warning_errno(dev, r, "Network interface %i is renamed from '%s' to '%s', "
+                                                "but failed to save the new name in udev database: %m",
+                                                ifindex, oldname, event->name);
```
Comment (poettering) [inline src/udev/udev-event.c]: shouldn't this device_add_property() be done before the device_rename() above?

File: src/udev/udev-event.c [hunk 2]
```diff
@@ -817,6 +824,46 @@ static void event_execute_rules_on_remove(
...
+        r = device_copy_properties(dev, event->dev_db_clone);
+        if (r < 0)
+                return log_device_debug_errno(dev, r, "Failed to copy properties from cloned device, ignoring: %m");
+
+        /* Drop previously added property */
+        r = sd_device_get_property_value(dev, "ID_NET_RENAMING_TO", &rename_to);
+        if (r < 0 && r != -ENOENT)
+                return log_device_debug_errno(dev, r, "Failed to get property 'ID_NET_RENAMING_TO', ignoring: %m");
+        if (r == -ENOENT)
+                return 0;
```
Comment (poettering) [inline src/udev/udev-event.c]: if you check against -ENOENT first, you can remove the r != -ENOENT check in the other if check...

**Comment by poettering** [comment]
I think this is quite an important fix btw, not just for networkd, but any consumer. I figure the NM folks should take notice of this too, and ignore ifaces that have the prop set. @lkundrak ping

**Comment by yuwata** [comment]
@poettering Updated. The above two comments are addressed in the updated version. PTAL.

**Comment by yuwata** [comment]
> I wonder if it wouldn't be better to keep the property name entirely generic. There might be other subsystems that implement the "move" action, and trigger it from "add" by renaming the device (or otherwise doing something to it). And I think it would make sense to allow the property to be used for those things too.

Actually renaming itself may not limited to network interfaces, but currently `udevd`, at least explicitly, supports only network interface renaming.

> hence maybe rename ID_NET_RENAMING_TO to ID_RENAMING= and make it a boolean? (i mean, we don't need the actual iface name we are renaming to as a prop, do we? a boolean would suffix too, no?)

If boolean is enough, meybe we should use a tag?

**Comment by poettering** [comment]
> Actually renaming itself may not limited to network interfaces, but currently `udevd`, at least explicitly, supports only network interface renaming.

Well, but other components might do it too, for example from some program they ship that is run from "add". And I think it would make a ton of sense, to allow them to follow the same semantics them, and use the same property for this.

I mean, I figure in PID 1 and such we should also check this new prop, and probably for all devices, so that devices don't show up under their old temporary name at all when they are renamed anyway. And for that having a generic name would be great since PID 1 of course synthesizes .device units for all kinds of device types, not just net ifs

**Comment by poettering** [comment]
> If boolean is enough, meybe we should use a tag?

tags come at a price. the more oyu have the "fuller" the per-udev-msg bloom filter becomes, and that destroys the filtering caps. Hence, people shouldn't use tags unless they actively want to use it for matching devices. i.e. if somebody asks the question "please tell me all devices that are currently being renamed", then a tag would be right, but if nobody asks questions like that it should be a regular prop. (and yes, i don't think anyone would ask that question, wouldn#t you agree?)

**Comment by yuwata** [comment]
Thank you for the explanation. I will update this tomorrow or later.

**Comment by yuwata** [comment]
@poettering Updated.
- Rename `ID_NET_RENAMING_TO` -> `ID_RENAMING`
- Always drop `ID_RENAMING` property on 'move' uevent.
