### PR TITLE
ask-password: fix assertion

### LINKED ISSUE #11295: (sd-passwd)[602]: Assertion 'keyname' failed at ../src/shared/ask-password-api.c:164, function ask_password_keyring().
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Fedora Rawhide

**Expected behaviour you didn't see**
 > Success

**Unexpected behaviour you saw**
 > Dumps core

**Steps to reproduce the problem**
Set up a system to use Clevis-luks

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #11295.

### CODE REVIEW

File: src/shared/ask-password-api.c [hunk 1]
```diff
@@ -341,7 +341,7 @@ int ask_password_tty(
                         goto finish;
                 }
 
-                if (notify >= 0 && pollfd[POLL_INOTIFY].revents != 0) {
+                if (notify >= 0 && pollfd[POLL_INOTIFY].revents != 0 && keyname) {
```
Comment (keszybz) [inline src/shared/ask-password-api.c:344]: Below we have
```C
if (keyname)
     (void) add_to_keyring_and_log(...);
```
So checking for 'keyname` is symmetrical here.
