### PR TITLE
journalctl: do not add io event source for stdout if it is a file

### LINKED ISSUE #28636: journalctl -f output cannot be redirected to a file
### systemd version the issue has been seen with

254

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

journalctl

### Expected behaviour you didn't see

```sh
$ journalctl -u cups -f > log
^C
$ file --mime log
log: text/plain; charset=us-ascii
```

### Unexpected behaviour you saw

https://bugzilla.redhat.com/show_bug.cgi?id=2228089

Redirection to a file from 'journalctl -f' does not work
```
$ journactl -f > log
Failed to add io event source for stdout: Operation not permitted

$ file --mime log
log: inode/x-empty; charset=binary
```

systemd-253.5-6.fc39.x86_64 was working.

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug introduced by 713342d9b09d717e9942ed08bd620c9159a98fb8.

Fixes #28636.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2228089.

### CODE REVIEW

File: src/journal/journalctl.c [hunk 1]
```diff
@@ -2328,10 +2329,15 @@ static int setup_event(Context *c, int fd, sd_event **ret) {
         if (r < 0)
                 return log_error_errno(r, "Failed to add io event source for journal: %m");
 
-        /* Also keeps an eye on STDOUT, and exits as soon as we see a POLLHUP on that, i.e. when it is closed. */
-        r = sd_event_add_io(e, NULL, STDOUT_FILENO, EPOLLHUP|EPOLLERR, NULL, INT_TO_PTR(-ECANCELED));
-        if (r < 0)
-                return log_error_errno(r, "Failed to add io event source for stdout: %m");
+        if (fstat(STDOUT_FILENO, &st) < 0)
+                return log_error_errno(r, "Faield to stat stdout: %m");
```
Comment (mrc0mmand) [inline src/journal/journalctl.c]:
```suggestion
                return log_error_errno(r, "Failed to stat stdout: %m");
```

**Comment by keszybz** [comment]
Please note that this needs a fixup from #28680.
