### PR TITLE
networkd: link_enter_configured remove assert

### LINKED ISSUE #4746: sometimes networkd fails an assert at link_enter_configured()
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> arch linux

### In case of bug report: Expected behaviour you didn't see

> systemd-networkd runs happy and assert-free.

### In case of bug report: Unexpected behaviour you saw

> systemd-networkd sometimes triggers an assert on `link_enter_configured` and crashes. Here is a piece of log on a case where it crashed. The interface that triggers it is `br-virt` (a bridge for my virtual machines). It does not always crash though.

    26 Nov 12:51:01 galois systemd-networkd: ve-ada: Gained carrier
    26 Nov 12:51:01 galois systemd-networkd: ve-ada: Configured
    26 Nov 12:51:01 galois systemd-timesyncd: Network configuration changed, trying to establish connection.
    26 Nov 12:51:01 galois kernel: br-virt: port 1(ve-ada) entered blocking state
    26 Nov 12:51:01 galois kernel: br-virt: port 1(ve-ada) entered forwarding state
    26 Nov 12:51:01 galois dnsmasq: reading /run/systemd/resolve/resolv.conf
    26 Nov 12:51:01 galois systemd-networkd: br-virt: Gained carrier
    26 Nov 12:51:01 galois dnsmasq: using local addresses only for domain virt.local
    26 Nov 12:51:01 galois systemd-networkd: Assertion 'link->state == LINK_STATE_SETTING_ROUTES' failed at src/network/networkd-link.c:692, function link_enter_configured(). Aborting.

### In case of bug report: Steps to reproduce the problem

> Not sure yet... That bridge `br-virt` is created by networkd and has a statically configured address. I also have dnsmasq listening on that interface working as dhcp and dns server for my virtual machines. Could it be a race with dnsmasq somehow?

> Also, since `link_check_ready` happily returns in case expectations are not met, probably [this line](https://github.com/systemd/systemd/blob/master/src/network/networkd-link.c#L742) should just check for `== LINK_STATE_SETTING_ROUTES`, and never trigger an assert here. This does not explain why this expectation is sometimes not met though...

### PR DESCRIPTION
**Pull request by ssahani**
When we are in link_enter_configured we assume that the

link->state should be LINK_STATE_SETTING_ROUTES but in some
situation it's LINK_STATlE_SETTING_ADDRESSES.

Just ignore the wrong state.

Also since the return value not used any where
make link_enter_configured return type void.

Fixes: #4746

### CODE REVIEW

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -689,7 +689,9 @@ static Address* link_find_dhcp_server_address(Link *link) {
 static int link_enter_configured(Link *link) {
         assert(link);
         assert(link->network);
-        assert(link->state == LINK_STATE_SETTING_ROUTES);
+
+        if (link->state != LINK_STATE_SETTING_ROUTES)
+                return 1;
```
Comment (keszybz) [inline src/network/networkd-link.c]: Why `1`? It's not used for anything, right?

Comment (ssahani) [reply src/network/networkd-link.c]: @keszybz  what we should use then ?

Comment (keszybz) [reply src/network/networkd-link.c]: 0.

**Comment by poettering** [comment]
Also, as mentioned before. Please add a line following the following syntax to your PRs/commits:

> Fixes: #4746 

When github sees that it will automatically close the issue when the PR is merged! You came pretty close to that with your:

> This closed #4746

But that's not quite the syntax github expects... 

Thanks!

**Comment by ssahani** [comment]
@poettering  I was following the the link I should be writing closes.

https://help.github.com/articles/closing-issues-via-commit-messages/

```

close
closes
closed
fix
fixes
fixed
resolve
resolves
resolved
```

File: src/network/networkd-link.c (hunk 1 above)
Comment (ssahani) [reply src/network/networkd-link.c]: why 0

**Comment by keszybz** [comment]
We generally don't use past tense in commit messages (We say "Fix the segfault when …" and not "Fixed the segfault when …"). In fact, in your commit message you use present tense ("ignore and bail out"), so adding a sentence at the end with past tense is inconsequent. So even if paste tense works, please just use the standard form with present tense.

File: src/network/networkd-link.c (hunk 1 above)
Comment (keszybz) [reply src/network/networkd-link.c]: Couple of reasons:
- 0 is the standard value that means "success"
- sometimes we return 0 and 1 to mean, respectively, "success, no action taken" and "success, action taken". This can be useful when the caller needs to distinguish those two cases. For this function, the only caller does not care about the result at all, so there's no point in making this distinction. Also, the convention is reverse (1 is never used for the case of "nothing needs to be done").

**Comment by ssahani** [comment]
yes should be closes what you say ?

**Comment by keszybz** [comment]
"Closes" or "Fixes".

File: src/network/networkd-link.c (hunk 1 above)
Comment (ssahani) [reply src/network/networkd-link.c]: Thanks ! But we already using this same syntax other places

```
link_down_handler
    if (IN_SET(link->state, LINK_STATE_FAILED, LINK_STATE_LINGER))
                return 1;
```

Should we all change that too.

**Comment by ssahani** [comment]
I realised that mistake After @poettering  mentioned .

File: src/network/networkd-link.c (hunk 1 above)
Comment (keszybz) [reply src/network/networkd-link.c]: `link_down_handler` is a callback, and for callbacks `1` means break look, and `0` means continue loop. That's a different case.

You could actually make `link_enter_configured` return `void`.

Comment (ssahani) [reply src/network/networkd-link.c]: Actually we have diffrent places with same behaviour I chose the  wrong example.

`link_initialized_and_synced`

```
    if (link->state != LINK_STATE_PENDING)
                return 1

```

But yes we can make `link_enter_configured` void

Comment (keszybz) [reply src/network/networkd-link.c]: link_initialized_and_synced is also used as a callback.

Comment (ssahani) [reply src/network/networkd-link.c]: not really 
```
                     goto failed;
        } else {
                /* we are calling a callback directly, so must take a ref */
                link_ref(link);

                r = link_initialized_and_synced(m->rtnl, NULL, link);
                if (r < 0)
                        goto failed;
        }

        return 0;
```

Comment (keszybz) [reply src/network/networkd-link.c]: "not really" what?

Comment (ssahani) [reply src/network/networkd-link.c]: it's been called directly and `address_update` also not a call back too.

**Comment by ssahani** [comment]
updated.

File: src/network/networkd-link.c (hunk 1 above)
Comment (keszybz) [reply src/network/networkd-link.c]: It is *also* used as a callback. The return convention is determined by this use.
