### PR TITLE
Use "systemctl --user --force exit" to kill the user manager

### LINKED ISSUE #8621: hardcoded signal number in systemd-exit.service.in is not portable
### Submission type

 - Bug report

### systemd version the issue has been seen with

v238, master

### Summary

Value of `SIGRTMIN+24` can only be determined at runtime, but systemd assumes the value is `58` statically,.

### Code
Relevant code is here: https://github.com/systemd/systemd/blob/a7df2d1e4349a8c90223d8b7ae339dbad05da503/units/user/systemd-exit.service.in#L19

### Impact and Background

Breaks systemd on platforms / environments that have different values for `SIGRTMIN+24`.  Man page for signal suggests this might not be portable across glibc versions either[1].  Same man page suggests this value should never be hard-coded:

       The Linux kernel supports a range of 33 different real-time signals,
       numbered 32 to 64.  However, the glibc POSIX threads implementation
       internally uses two (for NPTL) or three (for LinuxThreads) real-time
       signals (see pthreads(7)), and adjusts the value of SIGRTMIN suitably
       (to 34 or 35).  Because the range of available real-time signals
       varies according to the glibc threading implementation (and this
       variation can occur at run time according to the available kernel and
       glibc), and indeed the range of real-time signals varies across UNIX
       systems, programs should never refer to real-time signals using hard-
       coded numbers, but instead should always refer to real-time signals
       using the notation SIGRTMIN+n, and include suitable (run-time) checks
       that SIGRTMIN+n does not exceed SIGRTMAX.

Getting this wrong causes failure to cleanly exit user sessions.

### Proposed Fixes

1) Require `kill` supports notation for expressing the signal relative to `SIGRTMIN`.  The commit introducing this context mentions utillinux, but this appears to no longer be the case.  A quick check shows support was added in 2011: https://github.com/karelzak/util-linux/commit/ae63d823abc33554ee1d3906a876734277293557

2) Generate the constant using compile-time check (print result with a small program or so).  While technically this value can only be determined at runtime, for  practical purposes this value is really a per-libc constant and would likely be sufficient to address portability concerns.  If it's not safe to assume it is constant then many things would break in worse ways :).

[1] http://man7.org/linux/man-pages/man7/signal.7.html

### PR DESCRIPTION
**Pull request by filbranden**
Using `systemctl --user --force exit` will send SIGRTMIN+24 to the user manager. Use that to implement user service systemd-exit.service.

This removes our dependence on an external `kill` binary and the concerns about whether they recognize SIGRTMIN+n by name or what their interpretation of SIGRTMIN is.

Tested: `systemctl --user start systemd-exit.service` kills the `systemd --user` instance for my user.

Fixes #8621

(Command syntax suggested in https://github.com/systemd/systemd/issues/8621#issuecomment-378184399.)

**NOTE:** This relies on getting $MANAGERPID from the environment, which happens when the command is called from ExecStart= in a user unit, but not when it's called explicitly in the command line... Is there a better way to find the manager pid that doesn't depend on the environment?

### CODE REVIEW

File: src/systemctl/systemctl.c [hunk 1]
```diff
@@ -3548,6 +3548,22 @@ static int load_kexec_kernel(void) {
         return 0;
 }
 
+static int kill_user_manager(void) {
+        int r;
+        char *pid_env;
+        pid_t pid;
+
+        pid_env = getenv("MANAGERPID");
```
Comment (filbranden) [inline src/systemctl/systemctl.c]: Is there a better way that doesn't depend on $MANAGERPID being present?

File: src/systemctl/systemctl.c [hunk 2]
```diff
@@ -3548,6 +3548,22 @@ static int load_kexec_kernel(void) {
...
+        if (!pid_env || !*pid_env)
```
Comment (yuwata) [inline src/systemctl/systemctl.c]: `isempty(pid_env)`?

File: src/systemctl/systemctl.c [hunk 3]
```diff
@@ -3548,6 +3548,22 @@ static int load_kexec_kernel(void) {
...
+                return -EINVAL;
+        r = parse_pid(pid_env, &pid);
+        if (r < 0)
+                return r;
```
Comment (yuwata) [inline src/systemctl/systemctl.c]: I think we should log something in this case.

File: src/systemctl/systemctl.c (hunk 2 above)
Comment (filbranden) [reply src/systemctl/systemctl.c]: Good catch! Done.

File: src/systemctl/systemctl.c (hunk 3 above)
Comment (filbranden) [reply src/systemctl/systemctl.c]: Done.

File: src/systemctl/systemctl.c (hunk 1 above)
Comment (filbranden) [reply src/systemctl/systemctl.c]: Doesn't really look like this pid is available anywhere else that's easily obtainable... One thing that occurred me was, when the environment variable is set, also set a property of the user manager such as ManagerPid= or Pid= and then query it later... But perhaps using $MANAGERPID from the environment is good enough? Thoughts?

**Comment by poettering** [comment]
So, I think we should use the bus instead of unix signals to do this. This avoids the need to figure out the PID altogether. Looking at the code though I think systemctl already can do this anyway, it's hidden in the trivial_method() function, which just calls Exit() on systemd's --user bus service. And all that appears to be hooked up alright already...

Hence, I think what's left to do is to just adjust the exit unit file to use this, changes to systemctl might not be necessary at all...

**Comment by filbranden** [comment]
Done. Very simple! :-)

I noticed the bus interface was there, but I thought the plan was to keep using the signal...

Anyways, please take another look.

Cheers,
Filipe

**Comment by keszybz** [comment]
Nice!

**Comment by dtzWill** [comment]
Hooray! Thank you!

**Comment by yuwata** [comment]
#9386.
