### PR TITLE
oss-fuzz: install libcrypt-dev in i386 image

### LINKED ISSUE #39395: 32-bit systemd builds fail on Ubuntu 24.04 (on OSS-Fuzz)
As mentioned in https://github.com/systemd/systemd/pull/39371 with Ubuntu 24.04 32-bit systemd builds fail with the OSS-Fuzz toolchain. Here's what it looks like:
```sh
clang  -o src/shared/libsystemd-shared-259.so  -L/usr/lib/clang/22.0.0git/lib/linux -Wl,--as-needed -Wl,--allow-shlib-undefined -shared -fPIC -Wl,-soname,libsystemd-shared-259.so -Wl,--whole-archive -Wl,--start-group src/libc/libc-wrapper.a src/shared/libsystemd-shared-259.a src/basic/libbasic.a src/libsystemd/libsystemd_static.a -Wl,--no-whole-archive -fstack-protector -m32 -O1 -fno-omit-frame-pointer -gline-tables-only -Wno-error=incompatible-function-pointer-types -Wno-error=int-conversion -Wno-error=deprecated-declarations -Wno-error=implicit-function-declaration -Wno-error=implicit-int -Wno-error=unknown-warning-option -Wno-error=vla-cxx-extension -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -Wl,-rpath,/usr/lib/x86_64-linux-gnu -shared -Wl,--version-script=/src/systemd/src/shared/libshared.sym -pthread /usr/lib/i386-linux-gnu/libcap.so /usr/lib/x86_64-linux-gnu/libcrypt.so -ldl -lrt -Wl,--fatal-warnings -Wl,-z,now -Wl,-z,relro -Wl,--gc-sections -Wl,--fatal-warnings -Wl,-z,now -Wl,-z,relro -Wl,--gc-sections -Wl,--fatal-warnings -Wl,-z,now -Wl,-z,relro -Wl,--gc-sections -lm -Wl,--end-group -Wl,--fatal-warnings -Wl,-z,now -Wl,-z,relro -Wl,--gc-sections -Wl,--fatal-warnings -Wl,-z,now -Wl,-z,relro -Wl,--gc-sections^M
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libcrypt.so: error adding symbols: file in wrong format^M
clang: error: linker command failed with exit code 1 (use -v to see invocation)^M
```
It can either be turned off by removing `i386` from https://github.com/google/oss-fuzz/blob/d249026fd1335e240b1845eb1e61ba490e069fb1/projects/systemd/project.yaml#L29 or it can be addressed with something like
```diff
diff --git a/tools/oss-fuzz.sh b/tools/oss-fuzz.sh
index 6df95af..2481fa0 100755
--- a/tools/oss-fuzz.sh
+++ b/tools/oss-fuzz.sh
@@ -46,7 +46,8 @@ else
         pkg-config wget python3-jinja2 zipmerge zstd
 
     if [[ "$ARCHITECTURE" == i386 ]]; then
-        apt-get install -y pkg-config:i386 libcap-dev:i386 libmount-dev:i386
+        apt-get install -y pkg-config:i386 libcap-dev:i386 libcrypt-dev:i386 libmount-dev:i386
+        export PKG_CONFIG=i386-linux-gnu-pkgconf
     fi
 
     pip3 install -r .github/workflows/requirements.txt --require-hashes
```

### PR DESCRIPTION
**Pull request by yuwata**
This is preparation for bumping base image of oss-fuzz to Ubuntu 24.04.

Closes #39395.

### CODE REVIEW

**Comment by yuwata** [comment]
c.f. https://github.com/google/oss-fuzz/pull/14264

**Comment by yuwata** [comment]
cc @evverx

File: tools/oss-fuzz.sh [hunk 1]
```diff
@@ -46,7 +46,8 @@ else
         pkg-config wget python3-jinja2 zipmerge zstd
 
     if [[ "$ARCHITECTURE" == i386 ]]; then
-        apt-get install -y pkg-config:i386 libmount-dev:i386
+        apt-get install -y pkg-config:i386 libcrypt-dev:i386 libmount-dev:i386
+        export PKG_CONFIG=i386-linux-gnu-pkgconf
```
Comment (evverx) [inline tools/oss-fuzz.sh]: Looks like it doesn't work on Ubuntu 20.04. Could you try `i686-linux-gnu-pkg-config` instead? In the meantime I'll pull the images locally to see what's available there.

Comment (evverx) [reply tools/oss-fuzz.sh]: `i686-linux-gnu-pkg-config` works on both Ubuntu 20.04 and Ubuntu 24.04. On Ubuntu 24.04 it's a compat link pointing to `pkgconf`.

With `i686-linux-gnu-pkg-config` I built the fuzz targets using the OSS-Fuzz toolchain on both Ubuntu 20.04 and Ubuntu 24.04 successfully.

Comment (yuwata) [reply tools/oss-fuzz.sh]: It seems that Ubuntu 20.04 neither has i386-linux-gnu-pkgconf nor i686-linux-gnu-pkgconf.
The new version seems to work. At least build succeeds.

Comment (yuwata) [reply tools/oss-fuzz.sh]: > `i686-linux-gnu-pkg-config` works on both Ubuntu 20.04 and Ubuntu 24.04. On Ubuntu 24.04 it's a compat link pointing to `pkgconf`.
> 
> With `i686-linux-gnu-pkg-config` I built the fuzz targets using the OSS-Fuzz toolchain on both Ubuntu 20.04 and Ubuntu 24.04 successfully.

Hm? They exist?

Which do you want? i386- with condition (current version) or i686- without condition?

Comment (evverx) [reply tools/oss-fuzz.sh]: > Hm? They exist?

I installed `pkg-config:i386` and got `i686-linux-gnu-pkg-config` there:
```sh
root@a8b576d27019:/src/systemd# ls -l /usr/bin/i686-linux-gnu-pkg-config 
lrwxrwxrwx. 1 root root 34 Nov 10 00:45 /usr/bin/i686-linux-gnu-pkg-config -> /usr/share/pkg-config-crosswrapper
```

> Which do you want? i386- with condition (current version) or i686- without condition?

I think `i686` would be better because it sets `PKG_CONFIG` explicitly even on Ubuntu 20.04 instead of relying on `pkg-config:i386` conflicting with `pkg-config` on Ubuntu 20.04. This sort of thing is partly why it broke on Ubuntu 24.04. Though I'm guessing both options should work so I'll leave it to you to decide.

Comment (yuwata) [reply tools/oss-fuzz.sh]: OK. Then, one less condition should be better. I will switch to i686-. Thanks.

Comment (yuwata) [reply tools/oss-fuzz.sh]: Hmm, unfortunately, i686- does not work.
https://github.com/systemd/systemd/actions/runs/19217288055/job/54928745217?pr=39658

Comment (evverx) [reply tools/oss-fuzz.sh]: It should be `i686-linux-gnu-pkg-config`

Comment (yuwata) [reply tools/oss-fuzz.sh]: Indeed. It works. Thanks.

**Comment by yuwata** [comment]
This does not touch any main source files. Merging without any other reviewers approvals.
