### PR TITLE
resolvconf-compat: first try to use the specified interface name as is

### LINKED ISSUE #25032: resolvconf (resolvectl) wrongly splits arguments
### systemd version the issue has been seen with

251.6

### Used distribution

Arch Linux

### Linux kernel version used

6.0.2-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

resolvectl

### Expected behaviour you didn't see

I use StrongSwan to connect to VPN. During connection it sets up DNS using `resolveconf` which is a symlink to `resolvectl` on my system.
The relevant log from failed attempt to set DNS servers looks like this:
```
installing DNS server 192.168.35.2 via resolvconf
resolvconf: Failed to resolve interface "xf.inet.ipsec.192.168.35": No such device
removing DNS server 192.168.35.2 via resolvconf
resolvconf: Failed to resolve interface "xf.inet.ipsec.192.168.35": No such device
adding DNS server failed
```

xf is the name of XFRM interface that I use for this connection.
The problem is quite new. I don't use this connection very often so I'm not sure when this started to happen exactly but I'm quite confident that everything was working properly on `systemd` 250 (and older).

### Unexpected behaviour you saw

DNS is not set by `resolvconf` invoked by `StrongSwan`.

### Steps to reproduce the problem

Configure XFRM interface for IPSec connection. Configure StrongSwan's resolve plugin like this:
```
    resolvconf {
        iface_prefix = xf.inet.ipsec.
    }
```

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #25032.

### CODE REVIEW

File: src/resolve/resolvectl.c [hunk 1]
```diff
@@ -108,51 +108,58 @@ static int interface_info_compare(const InterfaceInfo *a, const InterfaceInfo *b
...
+        _cleanup_free_ char *buf = NULL;
         int ifi;
 
         assert(s);
 
-        iface = strdup(s);
-        if (!iface)
-                return log_oom();
+        ifi = rtnl_resolve_interface(NULL, s);
+        if (ifi < 0 && drop_protocol_specifier) {
```
Comment (poettering) [inline src/resolve/resolvectl.c]: `ERRNO_IS_DEVICE_ABSENT(ifi)`?

File: src/resolve/resolvectl.c [hunk 2]
```diff
@@ -108,51 +108,58 @@ static int interface_info_compare(const InterfaceInfo *a, const InterfaceInfo *b
...
+                /* When invoked as resolvconf, drop the protocol specifier(s) at the end. */
```
Comment (poettering) [inline src/resolve/resolvectl.c:122]: i think the code would become a lot simpler if we'd just add a `buf = strdup(s);` here before the loop, instead of trying to be too smart here. This is not a performance sensitive codepath, hence one potentially unnecessary extra allocation here shouldn't matter.

File: src/resolve/resolvectl.c [hunk 3]
```diff
@@ -108,51 +108,58 @@ static int interface_info_compare(const InterfaceInfo *a, const InterfaceInfo *b
...
-                        return 0; /* done */
+                        log_debug("Ignoring protocol specifier '%s'.", dot + 1);
+                        ifi = rtnl_resolve_interface(NULL, buf);
+                        if (ifi >= 0)
+                                break;
                 }
+        }
 
-                return log_error_errno(ifi, "Failed to resolve interface \"%s\": %m", iface);
+        if (ifi == -ENODEV && arg_ifindex_permissive) {
```
Comment (poettering) [inline src/resolve/resolvectl.c]: ERRNO_IS_DEVICE_ABSENT()?

File: src/resolve/resolvectl.c [hunk 4]
```diff
@@ -108,51 +108,58 @@ static int interface_info_compare(const InterfaceInfo *a, const InterfaceInfo *b
...
-                log_debug("Ignoring protocol specifier '%s'.", dot + 1);
-                iface = strndup(s, dot - s);
-                if (!iface)
-                        return log_oom();
-                return ifname_mangle(iface);
-        } else
-                return ifname_mangle(s);
+        free_and_replace(arg_ifname, buf);
+        return 1; /* found */
 }
```
Comment (poettering) [inline src/resolve/resolvectl.c:179]: so i really dislike the ambiguity this introduces, i.e. you never know what "foo.bar" means: interface "foo" with protocol "bar", or interface "foo.bar" with no protocol?

While I think your patch generally makes sense I think we should at the very least warn about this ambiguity, and in selected cases even refuse. Specifically:

1. If there's practical ambiguity (and not just theoretical ambiguity) we should refuse. i.e. if the user passes "foo.bar" as interface name and there is both an interface "foo.bar" *and* one called "foo" existing, then we really don't know what to make of this, hence fail with a loud error.

2. if the user passes in an interface name containing a dot and it exists we should use it, but warn.

(conversely, we should not warn for interfaces that have no dot in them, because then things are clear. And we should not warn about interfaces that have a dot in them, and there's none by that full name, but once we chop off one dot it does exist).

**Comment by poettering** [comment]
I prepped #25064 now, documenting that people better avoid using "." in interface names.

**Comment by yuwata** [comment]
@poettering Thank you for the suggestion. In the revised version, though the logic is not changed from the previous version, but shows more information. PTAL.

**Comment by keszybz** [comment]
Yup, I think this strikes the right ballance. It should still work in all cases that worked before (backwards compat) and resolves the reported issue and the user will get warnings if there's some ambiguity involved.

**Comment by yuwata** [comment]
Hmm? Ubuntu CI does not install resolvconf ?? cc @bluca 
```
testsuite-75.sh[72]: ++ command -v resolvconf
testsuite-75.sh[34]: + RESOLVCONF=
testsuite-75.sh[34]: + RESOLVCONF=/sbin/resolvconf
testsuite-75.sh[34]: + [[ -x /sbin/resolvconf ]]
testsuite-75.sh[34]: + echo 'WARNING: command resolvconf not found. Skipping tests for resolvconf'
testsuite-75.sh[34]: WARNING: command resolvconf not found. Skipping tests for resolvconf
```

**Comment by yuwata** [comment]
Oh,
```
# remove resolvconf compat symlink
rm -f debian/tmp/sbin/resolvconf
# remove obsolete compat symlink
rm -f debian/tmp/usr/bin/systemd-resolve
```

**Comment by bluca** [comment]
we re-added it later, but it's not there in jammy

**Comment by keszybz** [comment]
mkosi / ci (opensuse, tumbleweed):
````
 'libbpf0' not found in package names. Trying capabilities.
No provider of 'libbpf0' found.
```
That's not related.
