### PR TITLE
tree-wide: allow building with -Werror=flex-array-member-not-at-end

### LINKED ISSUE #36988: efi fundamental structs need rework to fix Wflex-array-member-not-at-end
### systemd version the issue has been seen with

master

### Used distribution

irrelevant

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

efi-fundamental.h has this

```
typedef struct {
        uint32_t dwLength;
        uint16_t wRevision;
        uint16_t wCertificateType;
        uint8_t bCertificate[];
} WIN_CERTIFICATE;

typedef struct {
        WIN_CERTIFICATE Hdr;
        EFI_GUID CertType;
        uint8_t CertData[];
} WIN_CERTIFICATE_UEFI_GUID;
```

Unfortunately it is undefined what this does. An struct can only contain *one* flexible array and that must be the last member. currently GCC tolerates this code as an undocumented extension. 
This now fails with -Werror=flex-array-member-not-at-end.

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #36988.

### CODE REVIEW

File: src/shared/ethtool-util.c [hunk 1]
```diff
@@ -429,33 +429,28 @@ int ethtool_set_nic_buffer_size(int *ethtool_fd, const char *ifname, const netde
...
 static int get_stringset(int ethtool_fd, const char *ifname, enum ethtool_stringset stringset_id, struct ethtool_gstrings **ret) {
         _cleanup_free_ struct ethtool_gstrings *strings = NULL;
-        struct {
-                struct ethtool_sset_info info;
-                uint32_t space;
-        } buffer = {
-                .info.cmd = ETHTOOL_GSSET_INFO,
-                .info.sset_mask = UINT64_C(1) << stringset_id,
-        };
+        uint8_t buffer [offsetof(struct ethtool_sset_info, data) + sizeof(uint32_t)] = {};
```
Comment (YHNdnzj) [inline src/shared/ethtool-util.c]:
```suggestion
        uint8_t buffer[offsetof(struct ethtool_sset_info, data) + sizeof(uint32_t)] = {};
```

File: src/shared/ethtool-util.h [hunk 2]
```diff
@@ -107,10 +107,11 @@ typedef enum NetDevPort {
 #define ETHTOOL_LINK_MODE_MASK_MAX_KERNEL_NBYTES  (4 * ETHTOOL_LINK_MODE_MASK_MAX_KERNEL_NU32)
 
 /* layout of the struct passed from/to userland */
-struct ethtool_link_usettings {
+union ethtool_link_usettings {
         struct ethtool_link_settings base;
 
         struct {
+                uint8_t  header[offsetof(struct ethtool_link_settings, link_mode_masks)];
```
Comment (YHNdnzj) [inline src/shared/ethtool-util.h]:
```suggestion
                uint8_t header[offsetof(struct ethtool_link_settings, link_mode_masks)];
```

**Review by bluca — APPROVED** [review]
