### PR TITLE
logind-dbus: set gc_mode to USER_GC_BY_PIN when disable linger

### LINKED ISSUE #33488: user does not get terminated after linger is disabled
### systemd version the issue has been seen with

256.1

### Used distribution

Arch

### Linux kernel version used

6.9.6-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

loginctl, systemd-logind

### Expected behaviour you didn't see

user gets terminated after linger is disabled; `loginctl user-status $some_user` would give:
```
Failed to get user: User ID xxxx is not logged in or lingering
```

### Unexpected behaviour you saw

user does not get terminated after linger is disabled; the state is closing but it is never closed; `terminate-user` would stop the user manager and the slice, but apparently it's still not exactly "cleaned up".

note that if the user does not have linger enabled, and logged in on e.g. tty after a fresh (re)boot, logging out (i.e., stopping the last / only session left) will get the user terminated (and "cleaned up").

### Steps to reproduce the problem

```
$ sudo loginctl user-status temp
Failed to get user: User ID 1001 is not logged in or lingering

$ sudo loginctl enable-linger temp

$ sudo loginctl user-status temp
temp (1001)
   Since: Wed 2024-06-26 16:47:36 HKT; 1s ago
   State: lingering
Sessions: 5
  Linger: yes
    Unit: user-1001.slice
          └─user@1001.service
            └─init.scope
              ├─971 /usr/lib/systemd/systemd --user
              └─973 "(sd-pam)"

Jun 26 16:47:36 ideapad systemd[971]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Jun 26 16:47:36 ideapad systemd[971]: Listening on GnuPG cryptographic agent and passphrase cache.
Jun 26 16:47:36 ideapad systemd[971]: Listening on GnuPG public key management service.
Jun 26 16:47:36 ideapad systemd[971]: Listening on p11-kit server.
Jun 26 16:47:36 ideapad systemd[971]: Listening on Sound System.
Jun 26 16:47:36 ideapad systemd[971]: Listening on D-Bus User Message Bus Socket.
Jun 26 16:47:36 ideapad systemd[971]: Reached target Sockets.
Jun 26 16:47:36 ideapad systemd[971]: Reached target Basic System.
Jun 26 16:47:36 ideapad systemd[971]: Reached target Main User Target.
Jun 26 16:47:36 ideapad systemd[971]: Startup finished in 103ms.

$ sudo loginctl disable-linger temp

$ sleep 15

$ sudo loginctl user-status temp
temp (1001)
   Since: Wed 2024-06-26 16:47:36 HKT; 32s ago
   State: closing
Sessions: 5
  Linger: no
    Unit: user-1001.slice
          └─user@1001.service
            └─init.scope
              ├─971 /usr/lib/systemd/systemd --user
              └─973 "(sd-pam)"

Jun 26 16:47:36 ideapad systemd[971]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Jun 26 16:47:36 ideapad systemd[971]: Listening on GnuPG cryptographic agent and passphrase cache.
Jun 26 16:47:36 ideapad systemd[971]: Listening on GnuPG public key management service.
Jun 26 16:47:36 ideapad systemd[971]: Listening on p11-kit server.
Jun 26 16:47:36 ideapad systemd[971]: Listening on Sound System.
Jun 26 16:47:36 ideapad systemd[971]: Listening on D-Bus User Message Bus Socket.
Jun 26 16:47:36 ideapad systemd[971]: Reached target Sockets.
Jun 26 16:47:36 ideapad systemd[971]: Reached target Basic System.
Jun 26 16:47:36 ideapad systemd[971]: Reached target Main User Target.
Jun 26 16:47:36 ideapad systemd[971]: Startup finished in 103ms.

$ sudo loginctl terminate-user temp

$ sudo loginctl user-status temp
temp (1001)
   Since: Wed 2024-06-26 16:47:36 HKT; 45s ago
   State: closing
Sessions: 5
  Linger: no
    Unit: user-1001.slice

Jun 26 16:48:18 ideapad systemd[971]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Jun 26 16:48:18 ideapad systemd[971]: Closed GnuPG cryptographic agent and passphrase cache.
Jun 26 16:48:18 ideapad systemd[971]: Closed GnuPG public key management service.
Jun 26 16:48:18 ideapad systemd[971]: Closed p11-kit server.
Jun 26 16:48:18 ideapad systemd[971]: Closed Sound System.
Jun 26 16:48:18 ideapad systemd[971]: Removed slice User Application Slice.
Jun 26 16:48:18 ideapad systemd[971]: Reached target Shutdown.
Jun 26 16:48:18 ideapad systemd[971]: Finished Exit the Session.
Jun 26 16:48:18 ideapad systemd[971]: Reached target Exit the Session.
Jun 26 16:48:18 ideapad systemd[1]: Removed slice User Slice of UID 1001.

$ systemctl status user@1001
○ user@1001.service - User Manager for UID 1001
     Loaded: loaded (/usr/lib/systemd/system/user@.service; static)
    Drop-In: /usr/lib/systemd/system/user@.service.d
             └─10-login-barrier.conf
             /etc/systemd/system/user@1001.service.d
             └─override.conf
     Active: inactive (dead)
       Docs: man:user@.service(5)

Jun 26 16:48:18 ideapad systemd[971]: Closed GnuPG cryptographic agent and passphrase cache.
Jun 26 16:48:18 ideapad systemd[971]: Closed GnuPG public key management service.
Jun 26 16:48:18 ideapad systemd[971]: Closed p11-kit server.
Jun 26 16:48:18 ideapad systemd[971]: Closed Sound System.
Jun 26 16:48:18 ideapad systemd[971]: Removed slice User Application Slice.
Jun 26 16:48:18 ideapad systemd[971]: Reached target Shutdown.
Jun 26 16:48:18 ideapad systemd[971]: Finished Exit the Session.
Jun 26 16:48:18 ideapad systemd[971]: Reached target Exit the Session.
Jun 26 16:48:18 ideapad systemd[1]: user@1001.service: Deactivated successfully.
Jun 26 16:48:18 ideapad systemd[1]: Stopped User Manager for UID 1001.

$ systemctl status user-1001.slice
○ user-1001.slice - User Slice of UID 1001
     Loaded: loaded
    Drop-In: /usr/lib/systemd/system/user-.slice.d
             └─10-defaults.conf
     Active: inactive (dead)
       Docs: man:user@.service(5)

Jun 26 16:48:18 ideapad systemd[971]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Jun 26 16:48:18 ideapad systemd[971]: Closed GnuPG cryptographic agent and passphrase cache.
Jun 26 16:48:18 ideapad systemd[971]: Closed GnuPG public key management service.
Jun 26 16:48:18 ideapad systemd[971]: Closed p11-kit server.
Jun 26 16:48:18 ideapad systemd[971]: Closed Sound System.
Jun 26 16:48:18 ideapad systemd[971]: Removed slice User Application Slice.
Jun 26 16:48:18 ideapad systemd[971]: Reached target Shutdown.
Jun 26 16:48:18 ideapad systemd[971]: Finished Exit the Session.
Jun 26 16:48:18 ideapad systemd[971]: Reached target Exit the Session.
Jun 26 16:48:18 ideapad systemd[1]: Removed slice User Slice of UID 1001.

$ sudo loginctl kill-user temp
Could not kill user: No such file or directory

$ sudo loginctl user-status temp
temp (1001)
   Since: Wed 2024-06-26 16:47:36 HKT; 4min 17s ago
   State: closing
Sessions: 5
  Linger: no
    Unit: user-1001.slice

Jun 26 16:48:18 ideapad systemd[971]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Jun 26 16:48:18 ideapad systemd[971]: Closed GnuPG cryptographic agent and passphrase cache.
Jun 26 16:48:18 ideapad systemd[971]: Closed GnuPG public key management service.
Jun 26 16:48:18 ideapad systemd[971]: Closed p11-kit server.
Jun 26 16:48:18 ideapad systemd[971]: Closed Sound System.
Jun 26 16:48:18 ideapad systemd[971]: Removed slice User Application Slice.
Jun 26 16:48:18 ideapad systemd[971]: Reached target Shutdown.
Jun 26 16:48:18 ideapad systemd[971]: Finished Exit the Session.
Jun 26 16:48:18 ideapad systemd[971]: Reached target Exit the Session.
Jun 26 16:48:18 ideapad systemd[1]: Removed slice User Slice of UID 1001.
```

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by tomty89**
The mode switch from any to pin is currently done in create_session(). However, if no (pinning) session is created before (or after) linger is disabled, the user will not be gc'd after that. Therefore, also perform the mode switch when linger is being disabled.

Fixes #33488.

### CODE REVIEW

**Review by YHNdnzj — APPROVED** [review]
LGTM

File: src/login/logind-dbus.c [hunk 1]
```diff
@@ -1509,8 +1509,10 @@ static int method_set_user_linger(sd_bus_message *message, void *userdata, sd_bu
                         return -errno;
 
                 u = hashmap_get(m->users, UID_TO_PTR(uid));
-                if (u)
+                if (u) {
+                        u->gc_mode = USER_GC_BY_PIN;
```
Comment (poettering) [inline src/login/logind-dbus.c:1514]: can you add a comment here, maybe something like: `/* Make sure that disabling lingering will terminate the user tracking if no sessions pin it. */`  or so?
