### PR TITLE
sd-device,udev: refuse unsafe path in SYMLINK= and TAG=

### LINKED ISSUE #27155: NVMe by-id/ symlink changed when device serial has leading whitespace starting from v249
### systemd version the issue has been seen with

v253

### Used distribution

Fedora 37+, RHEL 9.2

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

systemd-udevd

### Expected behaviour you didn't see

[This commit](https://github.com/systemd/systemd/commit/5118e8e71dda211d20e34ec8d3012186ba27d3d3) changed how the `by-id/` symlink is created for NVMe devices where the device serial has leading whitespace. E.g. with a serial of `      foobar`, it changed from

```
nvme-QEMU_NVMe_Ctrl__foobar -> ../../nvme0n1
```

to

```
nvme-QEMU_NVMe_Ctrl_______foobar -> ../../nvme0n1
```

This is noticeable when upgrading from RHEL 8.6 to RHEL 9.2, but I don't think there's anything RHEL-specific about the change.

Changes in symlinks in turn break userspace programs that rely on them not changing across updates.

Should a backcompat rule be added back for this? Or is the upstream stance that stable symlinks are best effort but not guaranteed?

We don't want to re-introduce https://github.com/systemd/systemd/issues/19309 though, which is what the commit fixes, so this would require tweaking it further.

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #27155.
Replaces #27164.

### CODE REVIEW

File: src/udev/udev-rules.c [hunk 1]
```diff
@@ -2582,6 +2582,11 @@ static int udev_rule_apply_token_to_event(
                                 next = skip_leading_chars(next, NULL);
                         }
 
+                        if (path_is_safe(p)) {
```
Comment (daandemeyer) [inline src/udev/udev-rules.c]: Missing negation?

**Review by DaanDeMeyer — CHANGES_REQUESTED** [review]
LGTM, except for one thing

File: src/udev/udev-rules.c (hunk 1 above)
Comment (yuwata) [reply src/udev/udev-rules.c]: Ouch! Fixed.

**Comment by DaanDeMeyer** [comment]
This does bump the udev path size from 1024 to 4096. Does that matter at all or is it OK?

**Comment by yuwata** [comment]
> This does bump the udev path size from 1024 to 4096 (because path_is_safe() uses PATH_MAX). Does that matter at all or is it OK?

This mostly (except for 5 chars for the prefix "/dev/") not change the limit about the length, as `udev_event_apply_format()` called earlier with UDEV_PATH_MAX.

**Comment by yuwata** [comment]
Now, the validity checks are moved to sd-device. PTAL.

**Comment by keszybz** [comment]
CI is very unhappy :(

**Comment by keszybz** [comment]
```
In file included from ../src/udev/udev-rules.c:11:
../src/udev/udev-rules.c: In function â€˜udev_rule_apply_token_to_eventâ€™:
../src/udev/udev-rules.c:207:51: error: â€˜%sâ€™ directive argument is null [-Werror=format-overflow=]
  207 |                                 _dev, _lv, error, "%s:%u " fmt,         \
      |                                                   ^~~~~~~~
../src/udev/udev-rules.c:207:51: error: â€˜%sâ€™ directive argument is null [-Werror=format-overflow=]
  207 |                                 _dev, _lv, error, "%s:%u " fmt,         \
      |                                                   ^~~~~~~~
../src/udev/udev-rules.c:207:51: error: â€˜%sâ€™ directive argument is null [-Werror=format-overflow=]
  207 |                                 _dev, _lv, error, "%s:%u " fmt,         \
      |                                                   ^~~~~~~~
../src/udev/udev-rules.c:207:51: error: â€˜%sâ€™ directive argument is null [-Werror=format-overflow=]
  207 |                                 _dev, _lv, error, "%s:%u " fmt,         \
      |                                                   ^~~~~~~~
```

**Comment by yuwata** [comment]
> CI is very unhappy :(

Oops. I hope now it works fine. PTAL.

File: test/test-functions [hunk 2]
```diff
@@ -512,6 +512,9 @@ run_qemu() {
         read -ra user_qemu_options <<< "$QEMU_OPTIONS"
         qemu_options+=("${user_qemu_options[@]}")
     fi
+    if [[ -n "${QEMU_OPTIONS_ARRAY+x}" ]]; then
+        qemu_options+=("${QEMU_OPTIONS_ARRAY[@]}")
+    fi
```
Comment (yuwata) [inline test/test-functions]: @mrc0mmand Do you think that this is a good way to add options with space?

**Review by DaanDeMeyer — APPROVED** [review]

File: test/test-functions (hunk 2 above)
Comment (YHNdnzj) [reply test/test-functions]: I think there is no need to check if the array is empty. `"${QEMU_OPTIONS_ARRAY[@]}"` expands to nothing if it's empty, and the `+=` becomes a no-op.

Comment (YHNdnzj) [reply test/test-functions]: (And this is the correct way I think, as this is expanded per-element.)

Comment (yuwata) [reply test/test-functions]: Problem here is that `QEMU_OPTIONS_ARRAY` may not be declared, and if not, `"${QEMU_OPTIONS_ARRAY[@]}"` triggers error, as we usually call `set -u`. Hence, we need to check if it is declared.

Not familiar, but `[[ -v QEMU_OPTIONS_ARRAY ]]` may be better to check that. WDYT?

Comment (YHNdnzj) [reply test/test-functions]: Oh, right.

Then `-v` would be the way to go :)

Comment (mrc0mmand) [reply test/test-functions]: It's unfortunate we have to do this dance, but I guess it will do. I thought about teaching `run_qemu()` to check if `$QEMU_OPTIONS` is an array, and if so skip the intermediate conversion, but that introduces crapload of other issues.

But to make this simpler, you can use just

```suggestion
    qemu_options+=(${QEMU_OPTIONS_ARRAY:+"${QEMU_OPTIONS_ARRAY[@]}"})
```

Comment (mrc0mmand) [reply test/test-functions]: (With newer bash versions you can do just `qemu_options+=("${QEMU_OPTIONS_ARRAY[@]}")` and it will do the right thing even with `set -u`, but versions like 4.4 and lower treat expansion even of a defined, but empty array as an unbound variable, so it's better to stay on the safe side)

Comment (yuwata) [reply test/test-functions]: @mrc0mmand Oh, that's much simpler. Thanks.

File: src/libsystemd/sd-device/sd-device.c [hunk 3]
```diff
@@ -1473,34 +1473,58 @@ int device_add_tag(sd_device *device, const char *tag, bool both) {
...
 
-        r = set_put_strdup(&device->devlinks, devlink);
+        if (!path_is_safe(devlink))
+                return -EINVAL;
+
+        p = prefix_dev(devlink);
+        if (!p)
+                return -ENOMEM;
+
+        path_simplify(p);
```
Comment (keszybz) [inline src/libsystemd/sd-device/sd-device.c:1499]: `path_is_safe()` rejects `..`, but otherwise accepts everything except empty strings and paths exceeding length limits. And `prefix_dev()` accepts any string, incl. absolute paths. This seems iffy: we shouldn't take an absolute path and silently make it a path under `/dev/`. We should reject those instead.

Also, adding the `/dev/` prefix everywhere seems wasteful: all paths in the hashmap will have `/dev/`. And in fact all rules on my machine use relative paths in SYMLINK. So we'd be reallocating and lenghtening all strings for no good reason.

File: test/udev-test.pl [hunk 4]
```diff
@@ -212,13 +212,37 @@ sub expect_for_some {
...
+                rules           => <<EOF
+SUBSYSTEMS=="scsi", ATTRS{vendor}=="ATA", ATTRS{model}=="ST910021AS", SYMLINK+="removed"
+SUBSYSTEMS=="scsi", ATTRS{vendor}=="ATA", ATTRS{model}=="ST910021AS", SYMLINK-="removed"
+SUBSYSTEMS=="scsi", ATTRS{vendor}=="ATA", ATTRS{model}=="ST910021AS", SYMLINK+="unsafe/../../path"
+SUBSYSTEMS=="scsi", ATTRS{vendor}=="ATA", ATTRS{model}=="ST910021AS", SYMLINK+="link1 link2/foo link3/aaa/bbb"
+SUBSYSTEMS=="scsi", ATTRS{vendor}=="ATA", ATTRS{model}=="ST910021AS", SYMLINK+="default?;;replace%%test/foo'aaa"
+SUBSYSTEMS=="scsi", ATTRS{vendor}=="ATA", ATTRS{model}=="ST910021AS", OPTIONS="string_escape=replace", SYMLINK+="string_escape   replace/foo%%bbb"
+SUBSYSTEMS=="scsi", ATTRS{vendor}=="ATA", ATTRS{model}=="ST910021AS", ENV{.HOGE}="env    with    space", SYMLINK+="%E{.HOGE}"
+SUBSYSTEMS=="scsi", ATTRS{vendor}=="ATA", ATTRS{model}=="ST910021AS", ENV{.HOGE}="default/replace/mode?foo;;hoge", SYMLINK+="%E{.HOGE}"
+SUBSYSTEMS=="scsi", ATTRS{vendor}=="ATA", ATTRS{model}=="ST910021AS", OPTIONS="string_escape=replace", ENV{.HOGE}="replace/env/harder?foo;;hoge", SYMLINK+="%E{.HOGE}"
```
Comment (keszybz) [inline test/udev-test.pl:245]: Please add a test with SYMLINK with `/dev/` and an absolute pat outside of `/dev/`.

File: test/units/testsuite-64.sh [hunk 5]
```diff
@@ -174,8 +174,54 @@ testcase_megasas2_basic() {
...
+        )
+    done
+    for (( i = 15; i < 20; i++ )); do
+        expected_symlinks+=(
+            # old replace mode does not provide devlink, as serial contains "/"
+            # newer replace mode
+            /dev/disk/by-id/nvme-QEMU_NVMe_Ctrl_dead_.._.._beef_"$i"
+            # with nsid
+            /dev/disk/by-id/nvme-QEMU_NVMe_Ctrl_dead_.._.._beef_"$i"_1
+        )
```
Comment (keszybz) [inline test/units/testsuite-64.sh:214]: This is a great test. Thanks!

**Review by keszybz — COMMENTED** [review]
LGTM, except for the part about symlink creation. After reading the full diff I realize that the code was already like that, and that the logic is just being moved around. So I guess it's fine to merge as is. We can maybe adjust how absolute paths are dealt with later.

File: src/libsystemd/sd-device/sd-device.c (hunk 3 above)
Comment (keszybz) [reply src/libsystemd/sd-device/sd-device.c:1499]: Yep. This was a pre-existing issue, so it's probably better to merge this PR now, because it fixes a real problem. We can do cleanups later.
