### PR TITLE
seccomp: fix #9939 and allow specifying multiple errnos for syscall

### LINKED ISSUE #9939: ENOMEM when trying to filter different system call sets with different error numbers
**systemd version the issue has been seen with**
v239, v237

**Used distribution**
 Arch, Debian

**Expected behaviour you didn't see**
I was trying to debug a `SystemCallFilter` and thought assigning different error numbers to the different system call sets in the filter would be a good way to discover which system call was actually tripping up my service (hoping that it would log the returned errno to the journal).

**Unexpected behaviour you saw**
Bizarrely, systemd reported an error “cannot allocate memory” when restarting the service, and this error remains visible in the `systemctl status` output as well (the service seems to be running, but the “loaded” status is “error (Reason: Cannot allocate memory)”). Both of the systems I’ve reproduced this on have plenty of free memory.

**Steps to reproduce the problem**
```sh
sudo systemd-run -p 'SystemCallFilter=~@cpu-emulation:EPERM @debug:ENOENT' true
sudo systemd-run -p 'SystemCallFilter=~@clock:EPERM @privileged:ENOENT' true
```
The particular error numbers don’t matter (`EPERM` and `ENOENT` are 1 and 2, but you can also use 42 and 1337 if you feel like it), but assigning the same error number to both sets makes the error go away. This also doesn’t seem to be tied to any particular system call set, but some combinations will produce the same error and other won’t.

I tried to debug this, but didn’t get very far. Even at `systemd-analyze log-level debug`, these two log messages are directly consecutive:

```
systemd[1]: run-raf052eefe10b4d00b21b5803452ffa08.service: Failed to load configuration: No such file or directory
systemd[1]: Sent message type=error sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=org.freedesktop.DBus.Error.NoMemory error-message=Cannot allocate memory
```

The first is normal for `systemd-run` services as far as I can tell, and the second already signals the error. `strace`ing PID1 also doesn’t turn up anything interesting. The only conclusion I can draw from that is that the error *probably* doesn’t happen when actually applying the seccomp filter, because that’s the very very last step in `exec_child`, and if we actually got that far I would expect to see a lot more debug log messages. So I assume this error happens when *parsing* the directive. Probably.

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
See #9939 and the individual commit messages. (This is v2 of the pull request – v1 ignored two particular pseudo syscall numbers instead.)

TODO:
- tests, I suppose
- does the second commit need to be mentioned in `NEWS` and/or `systemd.exec(5)`?

### CODE REVIEW

File: src/shared/seccomp-util.c [hunk 1]
```diff
@@ -1051,6 +1051,16 @@ int seccomp_parse_syscall_filter_full(
                                    "Failed to parse system call, ignoring: %s", name);
                         return 0;
                 }
+                if (id == -10189 || id == -10191) {
```
Comment (keszybz) [inline src/shared/seccomp-util.c]: I can't say I like this. I'd rather just drop all syscalls that are mapped negative, and just emit a debug message here. If the syscall maps to negative, it is not available, and we don't care about it.

File: src/shared/seccomp-util.c [hunk 2]
```diff
@@ -1067,7 +1067,17 @@ int seccomp_parse_syscall_filter_full(
...
                         if (r < 0)
-                                return flags & SECCOMP_PARSE_LOG ? log_oom() : -ENOMEM;
+                                switch (r) {
+                                case -ENOMEM:
+                                        return flags & SECCOMP_PARSE_LOG ? log_oom() : -ENOMEM;
+                                case -EEXIST:
+                                        if (flags & SECCOMP_PARSE_LOG)
+                                                log_warning("System call %s already blocked with different errno: %d",
+                                                            name, PTR_TO_INT(hashmap_get(filter, INT_TO_PTR(id + 1))));
+                                        return -EINVAL;
```
Comment (keszybz) [inline src/shared/seccomp-util.c]: Shouldn't we just let this pass? This seems like a config error, but if the syscall is blocked anyway, this should be enough.

Comment (lucaswerkmeister) [reply src/shared/seccomp-util.c]: I wouldn’t object to that, but that’s a behavioral change that I feel should be made in a separate commit/PR.

File: src/shared/seccomp-util.c (hunk 1 above)
Comment (lucaswerkmeister) [reply src/shared/seccomp-util.c]: I don’t like it either, but for now I like the alternative even less :/ dropping pseudo syscall numbers completely hides those syscalls from `systemctl show`, and I feel like that’s too invasive to do at parse time. (I wouldn’t object if this only happened by the time we apply the filter.)

Comment (keszybz) [reply src/shared/seccomp-util.c]: But those numbers look like an implementation details of seccomp. We don't want to bake this into our code.

And I have to say that with that patch things are even more confusing: some syscalls are still hidden from `systemctl show`, but the rules *which* functions are hidden are pretty obscure.

I don't see why we should care about syscalls which are undefined on a given architecture. But if you think it's important to show them, then let's do this properly and adjust the data structures so that it's possible to store those syscalls which don't map to a valid syscall numbers.

**Comment by keszybz** [comment]
Yeah, even when looking at this after two days, I don't like the approach of hardcoding the numbers like that. Let's look for some different solution.

File: src/shared/seccomp-util.c (hunk 1 above)
Comment (lucaswerkmeister) [reply src/shared/seccomp-util.c]: > But if you think it's important to show them, then let's do this properly and adjust the data structures so that it's possible to store those syscalls which don't map to a valid syscall numbers.

Well – if I understand correctly, that’s exactly the purpose of libseccomp’s pseudo syscall numbers: we can pretend that each syscall corresponds to an integer, and just always pass these integers around, and translate them back to syscall names for display and everything, without having to care which syscalls actually exist and which don’t. It’s just that libseccomp slipped up a bit :(

**Comment by lucaswerkmeister** [comment]
Updated, PTAL!

**Comment by lucaswerkmeister** [comment]
Does this still need rework from my side?

File: src/shared/seccomp-util.c [hunk 3]
```diff
@@ -1061,10 +1061,9 @@ int seccomp_parse_syscall_filter_full(
                                 case -ENOMEM:
                                         return flags & SECCOMP_PARSE_LOG ? log_oom() : -ENOMEM;
                                 case -EEXIST:
-                                        if (flags & SECCOMP_PARSE_LOG)
-                                                log_warning("System call %s already blocked with different errno: %d",
-                                                            name, PTR_TO_INT(hashmap_get(filter, INT_TO_PTR(id + 1))));
-                                        return -EINVAL;
+                                        assert_se(hashmap_update(filter, INT_TO_PTR(id + 1), INT_TO_PTR(errno_num)) == 0);
+                                        r = 0;
```
Comment (keszybz) [inline src/shared/seccomp-util.c]: This assignment is not needed.

Comment (lucaswerkmeister) [reply src/shared/seccomp-util.c]: I thought it would be cleaner to ensure a stale `r` “error” isn’t left behind, in case the function’s control flow changes later or something, but I’ll remove it :)

**Comment by lucaswerkmeister** [comment]
Thanks, updated. (I removed the assignment and kept the `break;`, but I guess that could also be changed to a `return 0;` – not sure which I prefer.)
