### PR TITLE
logind efi boot-into-firmware fixes

### LINKED ISSUE #7424: busctl introspect called on /org/freedesktop/login1 returns ENOENT
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 235

### Used distribution

> Arch Linux

The command:
`busctl introspect org.freedesktop.login1 /org/freedesktop/login1`
returns `No such file or directory`.
Invocation on other objects like `/org/freedesktop` or `/org/freedesktop/login1/session` works.
The `gdbus` command which invokes the same method works. 
I can reproduce it even booting the live ARCH_201711 iso on the same machine (but only booting in UEFI mode, BIOS mode works).

### Requirements to reproduce

After a discussion in the IRC channel, we came to the conculsion that a system booted with UEFI where `/sys/firmware/efi/efivars/OsIndicationsSupported-*` is missing is likely to be the cause.

### PR DESCRIPTION
**Pull request by poettering**
Fixes #7424.

### CODE REVIEW

File: src/shared/efivars.c [hunk 1]
```diff
@@ -152,9 +153,10 @@ static int get_os_indications(uint64_t *os_indication) {
                  * efi_reboot_to_firmware_supported() above. */
                 *os_indication = 0;
                 return 0;
-        } else if (r < 0)
+        }
```
Comment (keszybz) [inline src/shared/efivars.c]: I don't see how that is an improvement. It is longer, and if anything it makes the code more brittle, because if the `return` is removed later on, this part needs to be updated too to undo this change. When the blocks are single-line, this doesn't matter so much, but with a longer block this change reduces legibility.

Comment (poettering) [reply src/shared/efivars.c]: force pushed a new version now where i dropped that... I am a fan of an "exit early and forget it" strategy when dealing with errors, and hence would always replace "else if" by "if" if the earlier branch all ended in a "return", simply so that as little "structural context" is carried on down to the rest of the function as possible, and we can forget everything we can forget about what came before...

But dunno, I don't care too much about this, hence dropped the hunk now, and force pushed again. PTAL.

**Comment by poettering** [comment]
CI failure is caused by #7445. Everything else passed. Merging.
