### PR TITLE
networkd: fallback to chaddr for static lease lookup when not found

### LINKED ISSUE #21368: dhcp-server: also read sender MAC address from packet header
**systemd version the issue has been seen with**
 
> ```
> systemd 249 (249.4)
> +PAM +AUDIT -SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL > -ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB -ZSTD -XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
> ```

**Used distribution**
> NixOS - Unstable

**Linux kernel version used** (`uname -a`)
> `Linux central 5.10.78 #1-NixOS SMP Sat Nov 6 13:10:10 UTC 2021 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
> x86_64

**Expected behaviour you didn't see**
 > IPs assigned via `DHCPServerStaticLease` were not handed out to clients.

**Unexpected behaviour you saw**
 > Random IPs were assigned to clients instead. 

**Steps to reproduce the problem**

When using a network configuration like so:

```
[root@central:/etc/nixos]# cat /etc/systemd/network/br_internal.network

[Match]
Name=br_internal

[Network]
Address=192.168.0.1/24
ConfigureWithoutCarrier=yes
DHCPServer=yes
DHCPv6PrefixDelegation=yes
IPv6SendRA=yes

[DHCPServer]
DNS=192.168.0.1
EmitDNS=true
PoolOffset=100
PoolSize=99

[DHCPServerStaticLease]
MACAddress=04:d4:c4:52:8e:ce
Address=192.168.0.101
```

I would expect a client with MAC `04:d4:c4:52:8e:ce` to be assigned the IP `192.168.0.101`. However, the client is instead assigned a random IP from the DHCP pool: 

image

Things I've tried that didn't work:

- Using a Linux client instead (still assigned random pool IP)
- Upper / lower casing `04:d4:c4:52:8e:ce`
- Specifying `Address=192.168.0.101/24` instead (which I've seen somewhere, but gave warning in journal)
- Rebooting all machines 
- Omitting `PoolOffset` and `PoolSize`

**Additional program output to the terminal or log subsystem illustrating the issue**

Journal output around a random time I applied that config.

```
Nov 14 23:11:47 central nixos[95798]: switching to system configuration /nix/store/cf6356pngbvi0w255mn1s0pivvy01q5j-nixos-system-central-21.11pre329879.c5ed8beb478
Nov 14 23:11:47 central systemd[1]: Stopped target Local File Systems.
Nov 14 23:11:47 central systemd[1]: Stopped target All Network Interfaces (deprecated).
Nov 14 23:11:47 central systemd[1]: Stopped target Remote File Systems.
Nov 14 23:11:47 central systemd[1]: systemd-networkd-wait-online.service: Deactivated successfully.
Nov 14 23:11:47 central systemd[1]: Stopped Wait for Network to be Configured.
Nov 14 23:11:47 central systemd[1]: Stopping Network Configuration...
Nov 14 23:11:47 central systemd-networkd[94579]: enp4s0: DHCP lease lost
Nov 14 23:11:47 central systemd-networkd[94579]: enp4s0: DHCPv6 lease lost
Nov 14 23:11:47 central systemd-networkd[94579]: br_internal: DHCPv6 lease lost
Nov 14 23:11:47 central systemd-resolved[1894]: enp2s0f2: Failed to read DNSSEC negative trust anchors for the interface, ignoring: No data available
Nov 14 23:11:47 central systemd[1]: systemd-networkd.service: Deactivated successfully.
Nov 14 23:11:47 central systemd[1]: Stopped Network Configuration.
Nov 14 23:11:47 central systemd[1]: systemd-networkd.service: Consumed 47ms CPU time, received 1.4K IP traffic, sent 1.6K IP traffic.
Nov 14 23:11:47 central systemd[1]: Starting Network Configuration...
Nov 14 23:11:47 central systemd-networkd[98487]: tap_drone: TUNSETIFF failed on tun dev: Device or resource busy
Nov 14 23:11:47 central systemd-networkd[98487]: Failed to load /etc/systemd/network/tap_drone.netdev, ignoring: Device or resource busy
Nov 14 23:11:47 central systemd-networkd[98487]: tap_drone: Link UP
Nov 14 23:11:47 central systemd-networkd[98487]: tap_drone: Gained carrier
Nov 14 23:11:47 central systemd-networkd[98487]: br_internal: netdev ready
Nov 14 23:11:47 central systemd-networkd[98487]: br_internal: Link UP
Nov 14 23:11:47 central systemd-networkd[98487]: br_internal: Gained carrier
Nov 14 23:11:47 central systemd-networkd[98487]: enp2s0f3: Link UP
Nov 14 23:11:47 central systemd-networkd[98487]: enp2s0f2: Link UP
Nov 14 23:11:47 central systemd-networkd[98487]: enp2s0f1: Link UP
Nov 14 23:11:47 central systemd-networkd[98487]: enp2s0f1: Gained carrier
Nov 14 23:11:47 central systemd-networkd[98487]: enp2s0f0: Link UP
Nov 14 23:11:47 central systemd-networkd[98487]: enp2s0f0: Gained carrier
Nov 14 23:11:47 central systemd-networkd[98487]: enp4s0: Link UP
Nov 14 23:11:47 central systemd-networkd[98487]: enp4s0: Gained carrier
Nov 14 23:11:47 central systemd-networkd[98487]: lo: Link UP
Nov 14 23:11:47 central systemd-networkd[98487]: lo: Gained carrier
Nov 14 23:11:47 central systemd-networkd[98487]: br_internal: Gained IPv6LL
Nov 14 23:11:47 central systemd-networkd[98487]: enp4s0: Gained IPv6LL
Nov 14 23:11:47 central systemd-networkd[98487]: Enumeration completed
Nov 14 23:11:47 central systemd[1]: Started Network Configuration.
Nov 14 23:11:47 central systemd-networkd[98487]: br_internal: netdev exists, using existing without changing its parameters
```

Actual bridge configuration for `br_internal`:

```
[root@central:/etc/nixos]# cat /etc/systemd/network/br_internal.netdev

[NetDev]
Kind=bridge
Name=br_internal
```

```
[root@central:/etc/nixos]# cat /etc/systemd/network/internal.network

[Match]
Name=enp2s0f* tap_drone

[Network]
Bridge=br_internal
```

### PR DESCRIPTION
**Pull request by RobertMe**
DHCP static leases are looked up by the client identifier as send by the client, while configured based on MAC. As RFC 2131 states the client identifier is an opaque key and must not be interpreted by the server this means that DHCP clients can (/will) also use a client identifier which is not a MAC address. One of these clients actually is systemd-networkd which uses an RFC 4361 by default to generate the client identifier. For these kind of DHCP clients static leases thus don't work because of this mismatch between configuring a MAC address but the server matching based on client identifier. This adds a fallback to try to look up a configured static lease based on the "chaddr" of the DHCP message as this will always contain the MAC address of the client.

Fixes #21368

### CODE REVIEW

**Comment by RobertMe** [comment]
This is my first PR, and I'm a C noob, so please bear with me :)

Some remarks:
1. Code is "reused" from existing code where the configuration is converted into a client id: https://github.com/systemd/systemd/blob/360c9cdc65dc44a9d263e9f7433e7a6fbff15c9d/src/network/networkd-dhcp-server-static-lease.c#L197-L203
2. I couldn't find that there are any unit tests covering the DHCP server so I couldn't / didn't add any for this change. If there are unit tests covering this, than please point me to where these are
3. I've looked into "rewriting" the current implementation to drop "client id" fully and replacing it with just mac address as personally I believe that, in it's current form, it doesn't really make sense (no other DHCP server seems to work based on client id; And the configuration calling it MACAddress but actual implementation using it the "client identifier" and not the "chaddr"). But this seems to involve some shared libraries / headers which I believe would require rewiring the current methods to a "dumbed down" version which would be odd and unfamiliar to me. Furthermore later on there might still be the possibility to extend the configuration with a `ClientIdentifier=` based match (so either on MACAddress / chaddr or on client identifier).
4. I thought about adding some "logic" to the condition (`if (!static_lease)`) but as the spec says that the client id is an opaque value I believe that adding some checks like "only do this fallback lookup if the received client id doesn't look like a MAC address" would "violate" that rule as it wouldn't apply the fallback logic when the client id happens to be 7 bytes long and start with 0x01.

File: src/libsystemd-network/sd-dhcp-server.c [hunk 1]
```diff
@@ -1094,6 +1094,24 @@ int dhcp_server_handle_message(sd_dhcp_server *server, DHCPMessage *message, siz
...
+        /* when no lease is found based on the client id fall back to chaddr */
+        if (!static_lease) {
+                DHCPClientId c;
+
+                c = (DHCPClientId) {
+                        .length = ETH_ALEN + 1,
+                        .data = new(uint8_t, ETH_ALEN + 1),
+                };
+                if (!c.data)
+                        return log_oom();
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-server.c]: Please do not log the failure in higher level. Please use `return -ENOMEM;` or `return log_oom_debug();`.

File: src/libsystemd-network/sd-dhcp-server.c [hunk 2]
```diff
@@ -1094,6 +1094,24 @@ int dhcp_server_handle_message(sd_dhcp_server *server, DHCPMessage *message, siz
...
+
+                /* set client id type to 1: Ethernet Link-Layer (RFC 2132) */
+                c.data[0] = 0x01;
+                memcpy(c.data + 1, req->message->chaddr, ETH_ALEN);
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-server.c]: Please check `req->message->hlen == ETH_ALEN`, or use `req->message->hlen` instead of `ETH_ALEN`.

File: src/libsystemd-network/sd-dhcp-server.c [hunk 3]
```diff
@@ -1094,6 +1094,24 @@ int dhcp_server_handle_message(sd_dhcp_server *server, DHCPMessage *message, siz
         existing_lease = hashmap_get(server->bound_leases_by_client_id, &req->client_id);
         static_lease = hashmap_get(server->static_leases_by_client_id, &req->client_id);
 
+        /* when no lease is found based on the client id fall back to chaddr */
+        if (!static_lease) {
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-server.c]: The function is already long. Please split-out the logic as a function, e.g. something like the following:
```c
static DHCPLease* server_get_static_lease(sd_dhcp_server *server, const DHCPRequest *req) {
        ...

        static_lease = hashmap_get(...);
        if (static_lease)
                return static_lease;

        c = (DHCPClientId) {
                ...,
        };

        return hashmap_get(...);
}
```

**Review by yuwata — CHANGES_REQUESTED** [review]
Thank you! The basic logic sounds good to me. Several minor requests.

**Comment by RobertMe** [comment]
Thanks for the review @yuwata, despite my apparent failure to run the tests locally and all failing. I will try to fix your remarks in today or in the next couple of days.

Could you confirm that the CI error is due to a missing `free(c.data)` (after using `c` for the hashmap lookup)? And might you also be able to direct me to where these tests are actually located so I can add some? As I'm failing miserably to find anything based on the error. I do obviously find the `LLVMFuzzerTestOneInput ../src/libsystemd-network/fuzz-dhcp-server.c:76`, but missing on what this list of errors is based:
>  453/1183 systemd:libsystemd-network / test-dhcp-server                        FAIL              0.54s   exit status 1
 808/1183 systemd:fuzzers / fuzz-dhcp-server_buffer-overflow-2                 FAIL              0.08s   exit status 1
 809/1183 systemd:fuzzers / fuzz-dhcp-server_discover-existing                 FAIL              0.08s   exit status 1
 810/1183 systemd:fuzzers / fuzz-dhcp-server_discover-new                      FAIL              0.09s   exit status 1
 811/1183 systemd:fuzzers / fuzz-dhcp-server_duplicate-input-data              FAIL              0.08s   exit status 1
 812/1183 systemd:fuzzers / fuzz-dhcp-server_release                           FAIL              0.08s   exit status 1
 813/1183 systemd:fuzzers / fuzz-dhcp-server_request-existing                  FAIL              0.08s   exit status 1
 814/1183 systemd:fuzzers / fuzz-dhcp-server_request-new                       FAIL              0.09s   exit status 1
 815/1183 systemd:fuzzers / fuzz-dhcp-server_request-reboot                    FAIL              0.09s   exit status 1
 816/1183 systemd:fuzzers / fuzz-dhcp-server_request-renew                     FAIL              0.09s   exit status 1

So the "buffer-overflow-2", "discover-existing", .... Are these tests? Or like data sets and `LLVMFuzzerTestOneInput` being the only test method (being executed multiple times)?
And a pointer in how I can run the tests locally would be appreciated as well :) I earlier quickly copied what I believed to be the (shell) commands from the CI run but still wasn't getting those errors as reported by the CI.

File: src/libsystemd-network/sd-dhcp-server.c (hunk 1 above)
Comment (RobertMe) [reply src/libsystemd-network/sd-dhcp-server.c]: Updated to `-ENOMEM`

File: src/libsystemd-network/sd-dhcp-server.c (hunk 2 above)
Comment (RobertMe) [reply src/libsystemd-network/sd-dhcp-server.c]: Used `req->message->hlen` for all three occurences (so also for `size` and the allocation size). This so the full address will always fit.

File: src/libsystemd-network/sd-dhcp-server.c (hunk 3 above)
Comment (RobertMe) [reply src/libsystemd-network/sd-dhcp-server.c]: Extracted. Moved `DHCPLease*` from return value to return argument to be able to return the `-ENOMEM` / accomodate for failure. Hope I have done it correctly with all the pointer magic ("reused" `TAKE_PTR` from elsewhere)

File: src/libsystemd-network/sd-dhcp-server.c [hunk 4]
```diff
@@ -1061,6 +1061,39 @@ static bool address_available(sd_dhcp_server *server, be32_t address) {
         return true;
 }
 
+static int server_get_static_lease(sd_dhcp_server *server, const DHCPRequest *req, DHCPLease **ret) {
+        DHCPLease *static_lease;
+        _cleanup_free_ uint8_t *data = NULL;
+
+        static_lease = hashmap_get(server->static_leases_by_client_id, &req->client_id);
+        if (static_lease) {
+                *ret = TAKE_PTR(static_lease);
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-server.c]: `static_lease` here in this function does not have `_cleanup_` attribute, then `TAKE_PTR()` is not necessary.

File: src/libsystemd-network/sd-dhcp-server.c [hunk 5]
```diff
@@ -1061,6 +1061,39 @@ static bool address_available(sd_dhcp_server *server, be32_t address) {
...
+        DHCPClientId c;
+
+        c = (DHCPClientId) {
+                .length = req->message->hlen + 1,
+                .data = data,
+        };
+
+        static_lease = hashmap_get(server->static_leases_by_client_id, &c);
+
+        *ret = TAKE_PTR(static_lease);
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-server.c]: Here also.

File: src/libsystemd-network/sd-dhcp-server.c [hunk 6]
```diff
@@ -1061,6 +1061,39 @@ static bool address_available(sd_dhcp_server *server, be32_t address) {
         return true;
 }
 
+static int server_get_static_lease(sd_dhcp_server *server, const DHCPRequest *req, DHCPLease **ret) {
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-server.c:1064]: Please add assertions for the arguments.

File: src/libsystemd-network/sd-dhcp-server.c [hunk 7]
```diff
@@ -1061,6 +1061,39 @@ static bool address_available(sd_dhcp_server *server, be32_t address) {
...
+        memcpy(data + 1, req->message->chaddr, req->message->hlen);
+
+        DHCPClientId c;
+
+        c = (DHCPClientId) {
+                .length = req->message->hlen + 1,
+                .data = data,
+        };
+
+        static_lease = hashmap_get(server->static_leases_by_client_id, &c);
```
Comment (yuwata) [inline src/libsystemd-network/sd-dhcp-server.c]:
```c
        static_lease = hashmap_get(server->static_leases_by_client_id,
                                   &(DHCPClientId) {
                                           .length = req->message->hlen + 1,
                                           .data = data,
                                   });
```

**Review by yuwata — CHANGES_REQUESTED** [review]
Looks mostly OK. Several minor comments.

File: src/libsystemd-network/sd-dhcp-server.c (hunk 6 above)
Comment (RobertMe) [reply src/libsystemd-network/sd-dhcp-server.c:1064]: Added `assert()`. Was unsure if it should be `assert(...)` or `assert_return(..., -EINVAL)`. Looking at other functions it seemed to be a mix and couldn't spot any logic in it. So hope `assert()` is correct.

File: src/libsystemd-network/sd-dhcp-server.c (hunk 7 above)
Comment (RobertMe) [reply src/libsystemd-network/sd-dhcp-server.c]: Updated, hope the indentation is correct (aligned with the first character after the `(` and then indenting with the default of 8 spaces?)

**Comment by yuwata** [comment]
@RobertMe I cannot see the revised commit. Maybe you pushed an older version?

**Comment by RobertMe** [comment]
@yuwata whoops, that was stupid. Did a `commit --amend` without `-a` / staging the changes. So it's committed & pushed now.

File: src/libsystemd-network/sd-dhcp-server.c (hunk 6 above)
Comment (yuwata) [reply src/libsystemd-network/sd-dhcp-server.c:1064]: In this case, assert() is correct. Thanks.
assert_return() is used only in exposed library functions.

**Review by yuwata — APPROVED** [review]
LGTM. Thank you!

**Comment by mbiebl** [comment]
@yuwata we had a downstream bug report against v252 in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1050098

Do you think it would be feasible/reasonable to backport this patch to v252-stable?

**Comment by yuwata** [comment]
> @yuwata we had a downstream bug report against v252 in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1050098
> 
> Do you think it would be feasible/reasonable to backport this patch to v252-stable?

Yeah, not sure we can cleanly backport it (that is, `git cherry-pick -x` work or not), but this PR should fix the issue.

**Comment by RobertMe** [comment]
That would be awesome. As I actually discovered this issue while running Debian (Bookworm) myself. So if it could be backported I don't have to wait ~2 years to actually use my own bugfix 😃

And if I can be of any help please let me know.

**Comment by mbiebl** [comment]
`git cherry-pick -x` works cleanly.
@RobertMe could you test/verify if the patch applied on top of v252-stable fixes your issue?
