### PR TITLE
core/unit: re-find dropin paths of a unit after writting settings

### LINKED ISSUE #35710: Every unit created by runc need daemon reload since systemd v230
### systemd version the issue has been seen with

255.4-1ubuntu8.4

### Used distribution

Ubuntu 24.04

### Linux kernel version used

6.8.0-51-generic

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

The  unit should not need daemon reload. 

### Unexpected behaviour you saw

$ systemctl status docker-xxx.scope 
Warning: The unit file, source configuration file or drop-ins of docker-xxx.scope changed on disk. Run 'systemctl daemon-reload' to reload units.

### Steps to reproduce the problem

$ sudo systemd-run -u sleep-infinity.scope --scope sleep infinity
$ sudo systemctl set-property sleep-infinity.scope DevicePolicy=strict DeviceAllow="char-* m"

$ sudo systemctl show -P NeedDaemonReload sleep-infinity.scope
yes

Expected output:
no

Stop the unit.
$ sudo systemctl stop sleep-infinity.scope

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by HeRaNO**
Fixes: ab932a622d57 ("core: simplify unit_need_daemon_reload() a bit")
Fixes #35710
Carry and replace #35711 
Close: #35711

### CODE REVIEW

File: src/core/unit.c [hunk 1]
```diff
@@ -4748,12 +4749,12 @@ int unit_write_setting(Unit *u, UnitWriteFlags flags, const char *name, const ch
         if (r < 0)
                 return r;
 
-        r = strv_push(&u->dropin_paths, q);
-        if (r < 0)
-                return r;
         q = NULL;
```
Comment (yuwata) [inline src/core/unit.c]: Please also drop this. Otherwise `q` is leaked.

File: src/core/unit.c [hunk 2]
```diff
@@ -4679,6 +4679,7 @@ char* unit_concat_strv(char **l, UnitWriteFlags flags) {
 
 int unit_write_setting(Unit *u, UnitWriteFlags flags, const char *name, const char *data) {
         _cleanup_free_ char *p = NULL, *q = NULL, *escaped = NULL;
+        _cleanup_strv_free_ char **dropins = NULL;
```
Comment (yuwata) [inline src/core/unit.c]: For newer code, please declare the variable where really necessary. That is, please move the declaration of `dropins` just before `unit_find_dropin_paths()`.

**Review by yuwata — CHANGES_REQUESTED** [review]

File: src/core/unit.c (hunk 1 above)
Comment (HeRaNO) [reply src/core/unit.c]: done.

File: src/core/unit.c (hunk 2 above)
Comment (HeRaNO) [reply src/core/unit.c]: done.

File: src/core/unit.c [hunk 3]
```diff
@@ -4748,12 +4748,11 @@ int unit_write_setting(Unit *u, UnitWriteFlags flags, const char *name, const ch
         if (r < 0)
                 return r;
 
-        r = strv_push(&u->dropin_paths, q);
+        _cleanup_strv_free_ char **dropins = NULL;
+        r = unit_find_dropin_paths(u, /* use_unit_path_cache= */ false, &dropins);
```
Comment (YHNdnzj) [inline src/core/unit.c]: It should be fine to use the cache here? We just inserted the new dropin there above after all
