### PR TITLE
core: introduce UNIT_ATOM_PROPAGATE_STOP_GRACEFUL for PropagatesStopTo=

### LINKED ISSUE #26839: Regression introduced in v253 that prevents some units to be restarted
### systemd version the issue has been seen with

253

### Used distribution

openSUSE Factory

### Linux kernel version used

irrelevant

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

Be able to restart `auditd.service` properly.

### Unexpected behaviour you saw

```
 # systemctl restart auditd.service 
Failed to restart auditd.service: Transaction contains conflicting jobs 'stop' and 'start' for augenrules.service. Probably contradicting requirement dependencies configured.
See system logs and 'systemctl status auditd.service' for details.

```

### Steps to reproduce the problem

```
# systemctl cat foo.service 
# /etc/systemd/system/foo.service
[Unit]
Requires=bar.service
After=bar.service
PropagatesStopTo=bar.service

[Service]
ExecStartPre=echo start foo
ExecStart=sleep infinity
ExecStopPost=echo stopped foo
```
```
# systemctl cat bar.service 
# /etc/systemd/system/bar.service
[Service]
ExecStartPre=echo start bar
ExecStart=sleep infinity
ExecStopPost=echo stopped bar
```
```
# systemctl restart foo.service 
Failed to restart foo.service: Transaction contains conflicting jobs 'stop' and 'restart' for foo.service. Probably contradicting requirement dependencies configured.
See system logs and 'systemctl status foo.service' for details.
```

Note that this test case has been taken from https://github.com/systemd/systemd/issues/24068 except that `Wants=bar.service` was changed into `Requires=bar.service`.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by YHNdnzj**
Follow-up for 017a7ba

Before this commit, when a unit that is restarting propagates stop
to other units, it can also depend on them, which results in
job type conflict and thus failure to pull in the dependencies.

So, let's introduce a new dependency atom `UNIT_ATOM_PROPAGATE_STOP_GRACEFUL`,
and use it for `PropagatesStopTo=`. It will enqueue a restart job if
there's already a start job, which meets the ultimate goal and avoids
job type conflict.

Fixes #26839
Closes #26938

### CODE REVIEW

**Comment by YHNdnzj** [comment]
cc @fbuihuu 

I shall probably add some tests for this, but I'm really sleepy now. Will come back tomorrow :)

**Comment by YHNdnzj** [comment]
@poettering I'd like this to be reviewed before we tag the next backport version.

While this solution is not very clean, I can't come up with a better one at the moment unfortunately :(

File: src/core/transaction.c [hunk 1]
```diff
@@ -1102,13 +1124,13 @@ int transaction_add_job_and_dependencies(
         }
 
         return 0;
```
Comment (poettering) [inline src/core/transaction.c:1128]: hmm, i think it would be nicer if we'd simply collect all PropagatesStopTo= units in a new set during the entire transaction, and then once we are done with compiling the transaction we go through that set and enqueue a stop job for that unit, but gracefully, i.e. that if there's already a job for the same unit applied in the transaction we'll simply skip it.

Comment (poettering) [reply src/core/transaction.c:1128]: this would require splitting the atom UNIT_ATOM_PROPAGATE_STOP I guess. i.e. add  UNIT_ATOM_PROPAGATE_STOP_GRACEFUL as a separate atom, that is used by UNIT_PROPAGATES_STOP_TO, and results in this behaviour.

This way we can clearly say that the propagates-stop-to thing is a "second-class citizen", i.e. that it only has effect on a transaction if there's nothing else already having an effect on the same unit in the transaction.

does that make sense?

Comment (YHNdnzj) [reply src/core/transaction.c:1128]: > i.e. that if there's already a job for the same unit applied in the transaction we'll simply skip it.

But IIUC that defeats the purpose of the original commit, which allows `restart` jobs to be propagated as stop to other units through `PropagatesStopTo=`? If the anchor unit A has `Requires + PropagatesStopTo` on another unit B, a start job will be enqueued for B, and with your suggestion we just ignore B when processing `PropagatesStopTo=`.

**Comment by bluca** [comment]
@YHNdnzj any update on this?

**Comment by YHNdnzj** [comment]
> @YHNdnzj any update on this?

@poettering Would like some clarification on your previous review comments 🤔

**Comment by YHNdnzj** [comment]
Addressed @poettering's comment, but the approach is slightly different. PTAL.

File: man/systemctl.xml [hunk 2]
```diff
@@ -2003,6 +2003,11 @@ Jan 12 10:46:45 example.com bluetoothd[8900]: gatt-time-server: Input/output err
         <varname>Triggers=</varname> in <citerefentry><refentrytitle>systemd.unit</refentrytitle><manvolnum>5</manvolnum></citerefentry>
         for more information about triggering units.</para>
 
+        <para><literal>restart-dependencies</literal> may only be used with
+        <command>systemctl start</command>. In this mode, dependencies of
+        the specified unit will receive restart propagation, as if a restart
+        job had been enqueued for the unit.</para>
```
Comment (poettering) [inline man/systemctl.xml:2009]: so i actually didn't document this on purpose, because it sounded too specialist to me, i wanted to keep this as an undocumented half-internal feature. But actually, thinking about it it might be ok, there might be other uses for this. hnece commit looks ok.
