### PR TITLE
login: use parse_uid() when unmounting user runtime directory

### LINKED ISSUE #9541: user-runtime-dir@XXX.service fails with 'No such user XXX'
systemd 239

It seems that it's possible that the user is deleted before stopping user-runtime-dir@xxx.service.

The commands are executed via ssh by script.
useradd test1
su -c id test1
su -c 'rpm -qa' test1
userdel test1

And checking `systemctl --failed', the following unit fails.
● user-runtime-dir@1000.service loaded failed failed /run/user/1000 mount wrapper

Related logs are as below.
Jul 09 02:45:38 qemux86-64 systemd-logind[119]: New session c2 of user test1.
Jul 09 02:45:39 qemux86-64 systemd[349]: Startup finished in 1.072s.
Jul 09 02:45:40 qemux86-64 systemd-logind[119]: Removed session c2.
Jul 09 02:45:41 qemux86-64 systemd-timesyncd[103]: Timed out waiting for reply from 216.239.35.12:123 (time4.google.com).
Jul 09 02:45:43 qemux86-64 systemd-logind[119]: New session c3 of user test1.
Jul 09 02:45:45 qemux86-64 systemd[362]: Startup finished in 1.066s.
Jul 09 02:45:47 qemux86-64 systemd-logind[119]: Removed session c3.
Jul 09 02:45:50 qemux86-64 systemd-user-runtime-dir[373]: No such user "1000"

Below is a simple script to reproduce the problem. (Assume target ip is 192.168.7.16.)

#!/bin/sh

ssh -o StrictHostKeyChecking=no root@192.168.7.16 'export PATH=/usr/sbin:/sbin:/usr/bin:/bin; useradd test1'
ssh -o StrictHostKeyChecking=no root@192.168.7.16 'export PATH=/usr/sbin:/sbin:/usr/bin:/bin; su -c id test1'
ssh -o StrictHostKeyChecking=no root@192.168.7.16 'export PATH=/usr/sbin:/sbin:/usr/bin:/bin; su -c "rpm -qa" test1'
ssh -o StrictHostKeyChecking=no root@192.168.7.16 'export PATH=/usr/sbin:/sbin:/usr/bin:/bin; userdel test1'

### PR DESCRIPTION
**Pull request by yuwata**
If a UID is specified to the argument of `systemd-user-runtime-dir` and the UID does not exist anymore, then it is safe to remove the runtime directory. So, this makes `systemd-user-runtime-dir` also try to parse the uid as a fallback in such case.

Fixes #9541.

### CODE REVIEW

**Comment by yuwata** [comment]
I am not sure this is a right fix for #9541, as I cannot reproduce the issue...

**Comment by yuwata** [comment]
In #9541, the reporter @ChenQi1989 confirms that this PR fixes the issue.

File: src/login/user-runtime-dir.c [hunk 1]
```diff
@@ -148,6 +148,11 @@ int main(int argc, char *argv[]) {
 
         user = argv[2];
         r = get_user_creds(&user, &uid, &gid, NULL, NULL);
+        if (r == -ESRCH && streq(argv[1], "stop")) {
+                /* The user may be already removed. Fallback to parse_uid() if the requested operation is 'stop'. */
+                if (parse_uid(user, &uid) >= 0)
+                        r = 0;
+        }
```
Comment (poettering) [inline src/login/user-runtime-dir.c]: Hmm, I think this should work differently: in the stop case we should not consult the password database at first, i.e. directly go for parse_uid(), and use a fallback on get_user_creds() if that doesn't work...  Which means I think this code should actually be moved inside of the if branches below, and the start branch should use get_user_creds() as before, but  the stop branch should use parse_uid() first, with a fallback to get_user_creds(). This way the gid field doesn't have to be requested at all, which is pretty nice, too

It's generally a

**Comment by yuwata** [comment]
Updated. Now it uses `parse_uid()` first, as @poettering suggests. PTAL.

**Comment by poettering** [comment]
lgtm failure appears to be caused by network, and rawhide issue by statx() glibc issue, both unrelated. merging.
