### PR TITLE
udev: fix performance regression in resolving event dependencies

### LINKED ISSUE #39583: udevadm settle reports "Failed to issue io.systemd.service.Ping() varlink call: Timer expired" which lead blktests block/001 failed
### systemd version the issue has been seen with

systemd-258~rc2-1.fc43.x86_64 and higher version systemd-258.1-2.fc44 

### Used distribution

Fedora release 44 (Rawhide)

### Linux kernel version used

6.18.0-0.rc3.251030ge53642b87a4f4.33.fc44.x86_64

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

The blktests block/001 pass

### Unexpected behaviour you saw

The test case failed and `udevadm settle` reported error msg:
```
# ./check block/001
block/001 (stress device hotplugging)                        [failed]
    runtime    ...  154.490s
    --- tests/block/001.out	2025-11-03 02:09:32.125072082 -0500
    +++ /root/blktests/results/nodev/block/001.out.bad	2025-11-03 02:13:37.590569533 -0500
    @@ -1,4 +1,5 @@
     Running block/001
     Stressing sd
     Stressing sr
    +Failed to issue io.systemd.service.Ping() varlink call: Timer expired

# cat /root/blktests/results/nodev/block/001.out.bad
Running block/001
Stressing sd
Stressing sr
Failed to issue io.systemd.service.Ping() varlink call: Timer expired
Test complete
```

### Steps to reproduce the problem

Running blktests block/001

### Additional program output to the terminal or log subsystem illustrating the issue

I've tried downgrading systemd to systemd-257.10-1.fc42.x86_64 and cannot reproduce the issue. 
You can find more log from https://github.com/linux-blktests/blktests/issues/208

### LINKED ISSUE #39817: systemd-udevd stuck at 100% CPU usage in resize_buckets
### systemd version the issue has been seen with

258

### Used distribution

Fedora 43

### Linux kernel version used

6.17.7-300.fc43.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

CPU usage should not be excessive, in absence of an even storm of any kind.

### Unexpected behaviour you saw

I noticed that my system was using a lot of CPU on `systemd-udev` so I've attached gdb to the process and collected a backtrace:

```
(gdb) bt
#0  0x00007f28203cf092 in base_bucket_scan (h=h@entry=0x7f281de99df0, idx=idx@entry=38132, key=key@entry=0x5559eba98770) at ../src/basic/hashmap.c:1226
#1  0x00007f28203d9122 in set_put (s=0x7f281de99df0, key=key@entry=0x5559eba98770) at ../src/basic/hashmap.c:1274
#2  0x00007f28203da8c9 in set_ensure_put (s=<optimized out>, hash_ops=<optimized out>, key=0x5559eba98770) at ../src/basic/hashmap.c:1290
#3  0x00005559d53954b8 in event_build_dependencies (event=0x5559eba98770) at ../src/udev/udev-manager.c:672
#4  event_queue_start (manager=<optimized out>) at ../src/udev/udev-manager.c:740
#5  on_post (s=<optimized out>, userdata=<optimized out>) at ../src/udev/udev-manager.c:1312
#6  0x00007f282046b09e in source_dispatch (s=s@entry=0x5559e295a5e0) at ../src/libsystemd/sd-event/sd-event.c:4201
#7  0x00007f282046b5e2 in sd_event_dispatch (e=<optimized out>, e@entry=0x5559e293cc50) at ../src/libsystemd/sd-event/sd-event.c:4782
#8  0x00007f282046d940 in sd_event_run (e=<optimized out>, e@entry=0x5559e293cc50, timeout=timeout@entry=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:4843
#9  0x00007f282046db1f in sd_event_loop (e=<optimized out>) at ../src/libsystemd/sd-event/sd-event.c:4864
#10 0x00005559d535f5c0 in manager_main (manager=0x5559e2931c10) at ../src/udev/udev-manager.c:1511
#11 run_udevd (argc=<optimized out>, argv=<optimized out>) at ../src/udev/udevd.c:78
#12 run (argc=<optimized out>, argv=<optimized out>) at ../src/udev/udevadm.c:128
#13 main (argc=<optimized out>, argv=<optimized out>) at ../src/udev/udevadm.c:144
```

This issue is persistent and I see the same resize function being called over and over.

### Steps to reproduce the problem

No idea, this just happens to happen on my Framework 13 / Core Ultra 125H system running Fedora 43 as of 20th Nov 2025.

### Additional program output to the terminal or log subsystem illustrating the issue

Apparently udev uses 18GB of RSS, so perhaps that's resizing one _very_ large table somewhere?

```sh
$ top -n 1
Tasks: 631 total,   2 running, 626 sleeping,   2 stopped,   1 zombie
%Cpu(s):  7,4 us,  1,4 sy,  0,0 ni, 90,8 id,  0,0 wa,  0,0 hi,  0,5 si,  0,0 st 
MiB Mem :  96003,0 total,  28553,0 free,  39038,3 used,  41007,1 buff/cache     
MiB Swap:   8192,0 total,   8191,1 free,      0,9 used.  56964,6 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                
1891695 root      20   0   17,4g  17,4g   8848 R  91,7  18,6   8:33.40 systemd-udevd                                                                                                                                                                          
```

The system has been up for about a day, so nothing too drastic.

```sh
udevadm info -t -q all | wc -l
26834
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #39583.
Fixes #39817.

### CODE REVIEW

**Comment by yuwata** [comment]
If you think the performance regression reported at #39583 and #39817 is critical, please backport this to v258 and v259.

File: src/udev/udev-manager.c [hunk 1]
```diff
@@ -947,8 +940,8 @@ static int event_queue_insert(Manager *manager, sd_device *dev) {
                                                         "The event (SEQNUM=%"PRIu64") has been already queued.",
                                                         event->seqnum);
 
-                /* Inserting an event in an earlier place may change dependency tree. Let's rebuild it later. */
-                event_clear_dependencies(e);
+                /* The inserted event may be a blocker of a later event. Let's find blocker again later. */
```
Comment (keszybz) [inline src/udev/udev-manager.c]: I don't grok this. We insert the new event *after* `e`. So the new event cannot be a blocker of `e`, but could be a blocker of later events after `e`?

Comment (keszybz) [reply src/udev/udev-manager.c]: An explanation is provided in the commit message, but it is a description of a static state, and doesn't directly describe what happens when new events are inserted. Please extend it.

Comment (yuwata) [reply src/udev/udev-manager.c]: > I don't grok this. We insert the new event _after_ `e`. So the new event cannot be a blocker of `e`, but could be a blocker of later events after `e`?

No, here, we receive an event with smaller SEQNUM after `e` (with larger SEQNUM) is received. This is a bug in the kernel.

If e.g. these two events are for the same device, then the newly inserted event (with smaller SEQNUM) should block the existing event `e`. Hence, we need to clear the already found blocker for `e` here.

Comment (yuwata) [reply src/udev/udev-manager.c]: See 6a04c1e518008bb81b41a94f56b015801fd399b2 for more details.

**Comment by yuwata** [comment]
@keszybz Added/updated comments. PTAL.

**Comment by bluca** [comment]
This doesn't backport cleanly and the merge conflict is non-trivial, so I'll leave it for now
