### PR TITLE
core: namespace fixes

### LINKED ISSUE #9844: local DoS: unpriv users can break starting services which have DynamicUser=1 (and rely on StateDirectory=)
**systemd version the issue has been seen with**

238

**Used distribution**
Fedora Workstation 28, with `setenforce 0`.

**Expected behaviour you didn't see**
unprivileged users cannot cause system services to fail with "Permission denied" errors.

**Unexpected behaviour you saw**
unprivileged user with access to FUSE can cause system services to fail with "Permission denied" errors when they are (re)started.

**Steps to reproduce the problem**

1. mkdir -p ~/mnt/mnt
2. bindfs --no-allow-other ~/mnt/mnt ~/mnt/mnt
3. bindfs --no-allow-other ~/mnt ~/mnt
4. systemctl start test.service

```
# /etc/systemd/system/test.service
[Service]

DynamicUser=yes
User=test-service
StateDirectory=test-service

ProtectSystem=strict

Type=oneshot

#ExecStart=/bin/ls -l /proc/self/ns
#ExecStart=/bin/cat /proc/self/mountinfo
#ExecStart=/bin/ls -ld /var/lib/test-service

ExecStart=/bin/touch /var/lib/test-service
```

**Additional information**

This is adapted from @siebenmann's problem(s).

https://github.com/systemd/systemd/issues/9835#issuecomment-411529873

> the trace we see is:
> 
> ````
> [....]
> 26787 openat(AT_FDCWD, "/run/systemd/unit-root/h/281/ckstst", O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECTORY) = 4
> 26787 name_to_handle_at(4, "thinclient_drives", {handle_bytes=128}, 0x7ffe1eca7454, 0) = -1 EACCES (Permission denied)
> 26787 openat(4, "thinclient_drives", O_RDONLY|O_CLOEXEC|O_PATH) = -1 EACCES (Permission denied)
> 26787 newfstatat(4, "thinclient_drives", 0x7ffe1eca7560, AT_SYMLINK_NOFOLLOW) = -1 EACCES (Permission denied)
> 26787 close(4)                          = 0
> 26787 close(3)                          = 0
> 26787 chdir("/")                        = 0
> 26787 setresgid(62583, 62583, 62583)    = 0
> [...]
> ````
> 
> On Ubuntu 18.04's version of systemd (based on version 237), the issue happens any time we have a FUSE mount (active or inactive) in a NFS mounted home directory that is not world-accessible (and thus not accessible to UID 0 on the NFS client). This happens with eg sshfs.
> 

---

> @siebenmann Sounds like it could be something along the lines of ProtectHome=read-only -> bind_remount_recursive_with_mountinfo() -> path_is_mount_point(). Ouch. Thanks for the specific details of your case.

He [mentioned on Twitter](https://twitter.com/thatcks/status/1027180345681240064) that changing some directory mode to `0755` allowed root to start accessing his problem mount, at least enough for root to be able to unmount it.  At first I didn't understand why systemd would be blocked by mode `0000`, when I think it runs as root with CAP_DAC_READ_SEARCH.  I think the implication was that CAP_DAC_READ_SEARCH has no effect on NFS, which sounds very plausible.

But we can start looking at this with FUSE as above, if NFS is harder to set up for testing.

Simply creating one `--no-allow-other` mount didn't seem to cause a problem.  Perhaps one of the fallbacks systemd uses has the ability to avoid touching inside the specific mount point which it is querying. (A similar ability is required for umount, when you need to unmount an unresponsive NFS filesystem).

It seems that you can't nest no-root-allowed mounts.  The mount program is usually going to be running as (set-uid) root.  But, I was at least able to trick systemd into trying to access inside a no-root-allowed mount.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #9844.

### CODE REVIEW

File: src/basic/mount-util.c [hunk 1]
```diff
@@ -543,6 +543,11 @@ int bind_remount_recursive_with_mountinfo(const char *prefix, bool ro, char **bl
                         r = path_is_mount_point(x, NULL, 0);
                         if (IN_SET(r, 0, -ENOENT))
                                 continue;
+                        if (IN_SET(r, -EACCES, -EPERM)) {
+                                /* Even if root user invoke this, FUSE or NFS mount points may not be acceessed. */
```
Comment (sourcejedi) [inline src/basic/mount-util.c:547]: If we go with this code, I would comment it: /* Even if root user invokes this, paths inside FUSE or NFS may be inaccessible. */

It's a nitpick. But I didn't seem to get `path_is_mount_point()` to fail when passed a FUSE mount point (mounted with --no-allow-other).  I had to trick systemd into passing a *sub*directory inside my FUSE mount point.

I think this would explain why the first report we noticed is from siebenmann with NFS *and* FUSE.  It seems it doesn't trigger from a single FUSE mount like `sshfs`, if you're not also using NFS.

It's also a grammar nitpick. I read "may not" as meaning "is never allowed".  We want to say "might not be allowed".

## Implications of this fix

So this means we could leave some mounts writable, and you have to rely on the directory permissions. Do you think this is acceptable in most practical cases? [*]

I also wonder if we will want to mention that some less common cases will not benefit from this protection, e.g. in a revision of the doc for ProtectSystem=.

I suppose concerns with user-triggered mounts are not specific to this change.  Any mount the user creates after the service starts (including by `automount`?), will be propagated into the service namespace as read-write.

I suppose the options like `BindReadOnlyPath=` (`ProtectSystem=yes`, `ProtectHome=read-only`) are relatively fragile when compared to `InaccessiblePaths=` (`ProtectHome=yes`).

`ProtectHome=read-only` can be seen as inferior anyway.  It's mostly `ProtectSystem=strict` that I worry might be promising more than it achieves.  "ensures that any modification of the ... local mounts is prohibited for the service."

---

[*] I'm not sure what "most practical cases" look like.  I'm stuck on how exactly siebenmanns problem happened in the first place. It seems as if mount() had been run successfully - which normally requires root? - inside a directory which root cannot access. Maybe this was using an executable which has file capabilities, so it wasn't running as UID 0?  I looked into my test with `bindfs`: I was using a set-uid root executable (`fusermount`).

**Comment by poettering** [comment]
Patch looks OK to me. 

That said, I wonder if we should make this behaviour optional, as some users of bind_remount_recursive() might not want such silent fallback on the fuse mounts (and instead should just fail)

Also, I think it would make sense to overmount these file nodes with inaccessible ones if we can't remount them read-only. Hence maybe introduce a new flags parameter to the function, with a new flags BIND_REMOUNT_FALLBACK_INACCESSIBLE, which would simply overmount all files/dirs we can't remount read-only with the files/dirs from mode_to_inaccessible_node(). We'd use this new flag in namespace.c to make sure that anything that we can't make read-only is made entirely unavailable. If both fail we should return fatally however, and simply fail the service to start.

**Comment by poettering** [comment]
I have posted #9852 now, which also addresses the reported two issues. However, I think this PR should also be merged, as it makes sure we can handle these NFS/FUSE cases without failing ourselves. (see my earlier comments)

**Comment by sourcejedi** [comment]
@poettering 

> I think it would make sense to overmount these file nodes with inaccessible ones if we can't remount them read-only.

In my reproducer, `~/mnt` is inaccessible by UID 0.  But UID 0 can still remount `~/mnt`.  The problem is that it can't remount `~/mnt/mnt`.  It would be equally unable to create an inaccessible mount on `~/mnt/mnt`.  :-(.

File: src/basic/mount-util.c (hunk 1 above)
Comment (keszybz) [reply src/basic/mount-util.c:547]: Yeah, we should probably reword the comment. But since @poettering already submitted a follow-up PR, let's first merge this, than that, and then work on any cleanups to avoid conflicts.

**Comment by poettering** [comment]
> In my reproducer, ~/mnt is inaccessible by UID 0. But UID 0 can still remount ~/mnt. The problem is that it can't remount ~/mnt/mnt. It would be equally unable to create an inaccessible mount on ~/mnt/mnt. :-(.

then maybe go up the tree until we find a mount point to overmount...

**Comment by yuwata** [comment]
@sourcejedi In #9856, I've tried to improve the comment. Please take a look.

About your concerns.
I do not have any examples that service units can access some directories even if ProtectSystem= or friends are set. I guess that if pid1 cannot access some mount points, then also service units cannot access them, except the permission of them are explicitly chosen for `User=` of units can access them. Or am I missing something?

**Comment by sourcejedi** [comment]
@yuwata one of my concerns is not related to this PR or to siebenmanns problem. I have split it into a separate issue, with a reproducer: #9857.

**Comment by yuwata** [comment]
@sourcejedi Yeah, my previous expectation was not true. And it seems may be critical for the settings like ProtectHome=.

**Comment by yuwata** [comment]
BTW, your concerns are independent of this PR :-)

**Comment by yuwata** [comment]
So, let's discuss that in your recent issue.
