### PR TITLE
networkd: if the DHCP server returns both a Classless Static Routes

### LINKED ISSUE #7792: Default route from DHCP no longer set after upgrade 235.38 -> 236.0
### Submission type

 - Bug report

### systemd version the issue has been seen with

236.0

### Used distribution

Arch Linux

#### 235.38

```
> ip route
default via 192.168.165.1 dev enp3s0 proto dhcp src 192.168.165.5 metric 1024
192.168.165.0/24 dev enp3s0 proto kernel scope link src 192.168.165.5
192.168.165.1 dev enp3s0 proto dhcp scope link src 192.168.165.5 metric 1024
```

#### 236.0

```
> ip route
192.168.165.0/24 dev enp3s0 proto kernel scope link src 192.168.165.5
```

even though the route is apparently correctly received:

```
> journalctl -b -o cat -u systemd-networkd
Starting Network Service...
Enumeration completed
Started Network Service.
eth0: Interface name change detected, eth0 has been renamed to enp3s0.
enp3s0: IPv6 successfully enabled
enp3s0: Gained carrier
enp3s0: Gained IPv6LL
enp3s0: DHCPv4 address 192.168.165.5/24 via 192.168.165.1
enp3s0: Configured
```
 
### In case of bug report: Steps to reproduce the problem

```
> cat /etc/systemd/network/eth0.network
[Match]
Name=enp3s0

[Network]
DHCP=yes

[DHCP]
UseDomains=true
```

### PR DESCRIPTION
**Pull request by ssahani**
option and a Static Routes option, the DHCP client MUST ignore the
   Static Routes option.

Closes #7792

### CODE REVIEW

File: src/network/networkd-dhcp4.c [hunk 1]
```diff
@@ -101,9 +102,19 @@ static int link_set_dhcp_routes(Link *link) {
         if (n < 0)
                 log_link_debug_errno(link, n, "DHCP error: could not get routes: %m");
 
+        for (i = 0; i < n; i++) {
```
Comment (yuwata) [inline src/network/networkd-dhcp4.c:105]: Small coding style issue: unnecessary `{`.

**Comment by ssahani** [comment]
updated

File: src/network/networkd-dhcp4.c [hunk 2]
```diff
@@ -132,7 +142,11 @@ static int link_set_dhcp_routes(Link *link) {
 
         /* According to RFC 3442: If the DHCP server returns both a Classless Static Routes option and
            a Router option, the DHCP client MUST ignore the Router option. */
-        if (r >= 0 && link->dhcp4_messages <= 0) {
+
+        if (classless_route)
+                log_link_warning(link, "Classless static routes received from DHCP server: ignoring static-route option and router option");
```
Comment (yuwata) [inline src/network/networkd-dhcp4.c]: I think we should warn this only when both classless static and static routes are recieved.

Comment (ssahani) [reply src/network/networkd-dhcp4.c]: Ok

**Comment by yuwata** [comment]
lgtm.
