### PR TITLE
WIP: test: debug TEST-41 failure on Ubuntu CI

### LINKED ISSUE #13794: TEST-41 sleep duration too short
**systemd version the issue has been seen with**
> git

<!-- **NOTE:** Do not submit bug reports about anything but the two most recently released systemd versions upstream! -->
<!-- For older version please use distribution trackers (see https://github.com/systemd/systemd/blob/master/docs/CONTRIBUTING.md#filing-issues). -->

**Used distribution**
 > Ubuntu CI

**Expected behaviour you didn't see**
 > TEST-41 pass

**Unexpected behaviour you saw**
 > TEST-41 fail

**Steps to reproduce the problem**

TEST-41 gives auto-restart services only 5 seconds to run and auto-restart several times, e.g.:

```
! systemd-run --unit=two -p StartLimitBurst=3 -p Type=oneshot -p Restart=on-failure -p ExecStart="/bin/bash -c \"printf a >>  $TMP_FILE\"" /bin/bash -c "exit 1"                                                                                                              
                                                                                                                                                                                                                                                                              
sleep 5                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                              
if [[ $(cat $TMP_FILE) != "aaa" ]]; then                                                                                                                                                                                                                                      
  exit 1                                                                                                                                                                                                                                                                      
fi                                                                                                                                                                                                                                                                            

```

However the Ubuntu CI runs on a single-cpu VM instance, and this test runs under non-accelerated qemu on that instance, so that 5 seconds isn't always enough time for the service to be auto-restarted the expected 3 times, e.g.:

the 3rd start of two.service begins:

> two.service: Forked /bin/bash as 280
> two.service: Executing: /bin/bash -c 'printf a >>  /test-41-oneshot-restart-test'
> two.service: Changed dead -> start
> 

then the testsuite `sleep 5` times out and checks the `/test-41-oneshot-restart-test` file, but finds only 'aa' and fails the test:

> Received SIGCHLD from PID 244 (testsuite.sh).
> Child 244 (testsuite.sh) died (code=exited, status=1/FAILURE)
> testsuite.service: Child 244 belongs to testsuite.service.
> testsuite.service: Main process exited, code=exited, status=1/FAILURE
> testsuite.service: Failed with result 'exit-code'.
> testsuite.service: Changed start -> failed
> testsuite.service: Job 68 testsuite.service/start finished, result=failed
> testsuite.service: Unit entered failed state.
> testsuite.service: Consumed 1.030s CPU time.
> 

then two.service actually writes the final 'a' to the file and exits, but it's too late:

> Child 280 (bash) died (code=exited, status=0/SUCCESS)
> two.service: Child 280 belongs to two.service.
> two.service: Main process exited, code=exited, status=0/SUCCESS
>

### PR DESCRIPTION
**Pull request by ddstreet**
TEST-41 gives auto-restart services only 5 seconds to run and
auto-restart several times, but on slow systems - such as
Ubuntu CI, which runs on a single-cpu VM instance, and this
test runs under non-accelerated qemu on that instance - the 5
seconds is not always enough time.

Hopefully doubling it to 10 seconds will be enough even for slow systems.

Fixes #13794.

### CODE REVIEW

**Comment by ddstreet** [comment]
Interesting, the longer sleep duration didn't appear to help.  I opened #13797 to blacklist this test in Ubuntu CI, as this might take longer to debug the failure.

**Comment by keszybz** [comment]
Hmm, maybe make it 30 s to see if that helps?

**Comment by ddstreet** [comment]
Hmm, seems I assumed incorrectly that this is a slow testbed problem; it looks like the restart limit is not being honored correctly, as two.service is started with `StartLimitBurst=3 `but is getting restarted more times than that:

> two.service: Installed new job two.service/restart as 725
> two.service: Enqueued job two.service/restart as 725
> two.service: Scheduled restart job, restart counter is at 5.

> Oct 17 13:03:29 systemd-testsuite testsuite.sh[244]: ++ cat /test-41-oneshot-restart-test
> Oct 17 13:03:29 systemd-testsuite testsuite.sh[244]: + [[ aaaaa != \a\a\a ]]
> Oct 17 13:03:29 systemd-testsuite testsuite.sh[244]: + exit 1

**Comment by anitazha** [comment]
How about `StartLimitIntervalSec=` to 30s and lower the sleeps back to 5? Seems like `StartLimitIntervalSec=10s` (or whatever `DefaultStartLimitIntervalSec=` is in the CI) is racing with the check.

**Comment by ddstreet** [comment]
I think I figured it out.

The test uses StartLimitBurst=3, but that only will enforce the limit if it's restarted 3 times within the default start limit interval, which is 10 seconds.  If the system is so slow that 3 restarts takes more than 10 seconds, it won't rate limit the restarts.

So in this test I think there are 2 problems:

1. the assumption that all 3 restarts for two.service will happen in less than 5 seconds is too short
2. the assumption that the 10 second DefaultStartLimitIntervalSec is long enough for all 3 restarts to fall inside it is also too short

I'll try updating the test and re-run it here to see if my reading of the failure is correct :)

**Comment by ddstreet** [comment]
@anitazha yep, exactly what you said - I posted my last comment without seeing yours.

I set the StartLimitIntervalSec to 120 secs and put the result checks in for loops so we don't have to rely on a specific sleep time.  I did keep a 10 second sleep to verify there aren't any additional restarts after the expected 3, though.

File: test/TEST-41-ONESHOT-RESTART/testsuite.sh [hunk 1]
```diff
@@ -18,10 +23,20 @@ TMP_FILE="/test-41-oneshot-restart-test"
 
 touch $TMP_FILE
 
-! systemd-run --unit=two -p StartLimitBurst=3 -p Type=oneshot -p Restart=on-failure -p ExecStart="/bin/bash -c \"printf a >>  $TMP_FILE\"" /bin/bash -c "exit 1"
+# test two: make sure StartLimitBurst correctly limits the number of restarts
```
Comment (anitazha) [inline test/TEST-41-ONESHOT-RESTART/testsuite.sh:26]: Maybe also include "and restarts execution of the unit from the first ExecStart=" since it is showing that multiple `ExecStart=` properties would not restart from the point that it failed.

Comment (ddstreet) [reply test/TEST-41-ONESHOT-RESTART/testsuite.sh:26]: done!
