### PR TITLE
tmpfiles: do not require `STATX_ATIME`

### LINKED ISSUE #41227: tmpfiles: bogus error condition when `STATX_ATIME` is not set
### systemd version the issue has been seen with

260

### Used distribution

Arch

### Linux kernel version used

6.18.x

### CPU architectures issue was seen on

x86_64

### Component

systemd-tmpfiles

### Expected behaviour you didn't see

systemd-tmpfiles must not rely on `STATX_ATIME` being always set if the kernel "new enough", as this flag is masked off when the filesystem is mounted with `noatime`.

https://github.com/torvalds/linux/blob/05f7e89ab9731565d8a62e3b5d1ec206485eeb0b/fs/stat.c#L191-L195:

```c
	/* allow the fs to override these if it really wants to */
	/* SB_NOATIME means filesystem supplies dummy atime value */
	if (inode->i_sb->s_flags & SB_NOATIME)
		stat->result_mask &= ~STATX_ATIME;
```

### Unexpected behaviour you saw

systemd-tmpfiles uses `STATX_ATIME` as a "mandatory" flag, expecting it to be always set in a well-formed environment, and emitting an error if it is not set suggesting that the environment is broken when it in fact isn't:

https://github.com/systemd/systemd/blob/3e52279684a53ebf84d1d73d528bf400c5fb3497/src/tmpfiles/tmpfiles.c#L589-L598

leading to

https://github.com/systemd/systemd/blob/3e52279684a53ebf84d1d73d528bf400c5fb3497/src/basic/stat-util.c#L377-L385

### Steps to reproduce the problem

- set up a rootfs on a filesystem with `noatime`
- boot using systemd
- observe `systemd-tmpfiles-clean.service` failing

### Additional program output to the terminal or log subsystem illustrating the issue

```console
# SYSTEMD_LOG_LEVEL=debug systemd-tmpfiles --clean
<...>
Running clean action for entry X /var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-*/tmp
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-prometheus-smartctl-exporter.service-GKguQK/tmp) failed: Protocol driver not attached
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-systemd-logind.service-k8j52T/tmp) failed: Protocol driver not attached
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-irqbalance.service-7RJkev/tmp) failed: Protocol driver not attached
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-chronyd.service-8hkO5G/tmp) failed: Protocol driver not attached
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-dbus-broker.service-6P6LVl/tmp) failed: Protocol driver not attached
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-nginx.service-B5HX8B/tmp) failed: Protocol driver not attached
Running clean action for entry x /var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-*
Running clean action for entry q /var/tmp
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp) failed: Protocol driver not attached
<...>
```

### PR DESCRIPTION
**Pull request by intelfx**
Timestamps are not guaranteed to be set by `statx()`, and their presence
should not be asserted as a proxy to judge the kernel version. In
particular, `STATX_ATIME` is omitted from the return when querying a
file on a `noatime` superblock, causing spurious errors from tmpfiles:

```console
# SYSTEMD_LOG_LEVEL=debug systemd-tmpfiles --clean
<...>
Running clean action for entry X /var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-*/tmp
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-prometheus-smartctl-exporter.service-GKguQK/tmp) failed: Protocol driver not attached
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-systemd-logind.service-k8j52T/tmp) failed: Protocol driver not attached
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-irqbalance.service-7RJkev/tmp) failed: Protocol driver not attached
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-chronyd.service-8hkO5G/tmp) failed: Protocol driver not attached
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-dbus-broker.service-6P6LVl/tmp) failed: Protocol driver not attached
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-nginx.service-B5HX8B/tmp) failed: Protocol driver not attached
Running clean action for entry x /var/tmp/systemd-private-94cc8a77688e497f96d5b9019e66ed6f-*
Running clean action for entry q /var/tmp
statx() does not support 'STATX_ATIME' mask (running on an old kernel?)
statx(/var/tmp) failed: Protocol driver not attached
<...>
```

Additionally, refactor `dir_cleanup()` slightly for self-consistency to make
it evident that the `NSEC_INFINITY` transformation is correct.

Fixes #41227.

### CODE REVIEW

File: src/tmpfiles/tmpfiles.c [hunk 1]
```diff
@@ -710,10 +710,10 @@ static int dir_cleanup(
                         continue;
```
Comment (keszybz) [inline src/tmpfiles/tmpfiles.c:710]: For the commit message: it doesn't matter *greatly*, but git logs are not in markdown, so  backticks and such make it hard to read.

File: src/tmpfiles/tmpfiles.c [hunk 2]
```diff
@@ -3145,8 +3149,8 @@ static int clean_item_instance(
         }
 
         return dir_cleanup(c, i, instance, d,
-                           statx_timestamp_load_nsec(&sx.stx_atime),
-                           statx_timestamp_load_nsec(&sx.stx_mtime),
+                           atime_nsec,
+                           mtime_nsec,
```
Comment (keszybz) [inline src/tmpfiles/tmpfiles.c:3161]: `dir_cleanup` only uses those two timestamps. If we can't get the timestamps, not restoring them is entirely reasonable.

**Review by keszybz — APPROVED** [review]
LGTM.

File: src/tmpfiles/tmpfiles.c (hunk 1 above)
Comment (intelfx) [reply src/tmpfiles/tmpfiles.c:710]: Oh, alright. I tend to use tooling that _does_ treat them as Markdown, so I guess it was my cavalier assumption that everyone does too.

File: src/tmpfiles/tmpfiles.c (hunk 2 above)
Comment (intelfx) [reply src/tmpfiles/tmpfiles.c:3161]: I'm sorry, I don't quite understand what is the point here — I thought that's exactly what the new logic does, as explained in the commit messages? :sweat_smile:

File: src/tmpfiles/tmpfiles.c [hunk 3]
```diff
@@ -3126,6 +3127,9 @@ static int clean_item_instance(
         if (r <= 0)
                 return r;
 
+        atime_nsec = FLAGS_SET(sx.stx_mask, STATX_ATIME) ? statx_timestamp_load_nsec(&sx.stx_atime) : NSEC_INFINITY;
```
[the remark this answers is not in the document]
Comment (poettering) [reply src/tmpfiles/tmpfiles.c:3138]: yeah, claude is right. if you pass in NSEC_INFINITY here as meaning "no known", and atime and mtime can have that separately, then dir_cleanup() needs tweaks to map that properly to TIMESPEC_OMIT individually.

Moreover the log before that also needs some love regarding handling this niche value

File: src/tmpfiles/tmpfiles.c (hunk 2 above)
Comment (keszybz) [reply src/tmpfiles/tmpfiles.c:3161]: "entirely reasonable" was about your patch. I was just saying it looks OK.

File: src/tmpfiles/tmpfiles.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (intelfx) [reply src/tmpfiles/tmpfiles.c:3138]: Yes, sounds legit, I missed that, will fix

**Review by keszybz — APPROVED** [review]
LGTM too.

**Comment by PaulGrandperrin** [comment]
Hi, could this be backported to the 260 branch?
