### PR TITLE
network: introduce BPF to reject netlink messages about non-static neighbor

### LINKED ISSUE #21031: Excessive CPU use by systemd-networkd during arp storm in network
**systemd version the issue has been seen with**
 > 245

**Used distribution**
 > Ubuntu 20.04

**Linux kernel version used** (`uname -a`)
 > `Linux foobar 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Low CPU usage

**Unexpected behaviour you saw**
 > 100% CPU usage by systemd-networkd

**Steps to reproduce the problem**
 1. Create L2 loop between two (or more) vxlan interfaces with enabled arp on both vxlan interfaces.
 2. wait until BUM reaches ~ 50-100 Mbps
 3. Check CPU usage by systemd-networkd.

**Additional program output to the terminal or log subsystem illustrating the issue**
I found that systemd-networkd is listening on AF_NETLINK (which is fine) but recieves huge amount of RTM_NEWNEIGH messages. I'm not sure that systemd-networkd should be interested in updates in arp tables. If there are too much of updates, systemd-networkd unexpectedly start to become high-volume application.

This is snippet from strace for systemd-networkd under moderate arp storm:

```
gettid()                                = 947
epoll_wait(4, [{EPOLLIN, {u32=3090839696, u64=94178838739088}}], 24, 0) = 1
gettid()                                = 947
epoll_wait(4, [{EPOLLIN, {u32=3090839696, u64=94178838739088}}], 24, 0) = 1
recvmsg(7, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000004}, msg_namelen=128->12, msg_iov=[{iov_base=NULL, iov_len=0}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_NETLINK, cmsg_type=0x3}], msg_controllen=24, msg_flags=MSG_TRUNC}, MSG_PEEK|MSG_TRUNC) = 68
recvmsg(7, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000004}, msg_namelen=128->12, msg_iov=[{iov_base={{len=68, type=RTM_NEWNEIGH, flags=0, seq=0, pid=0}, {ndm_family=AF_BRIDGE, ndm_ifindex=if_nametoindex("vx_o_101"), ndm_state=NUD_REACHABLE, ndm_flags=0, ndm_type=RTN_UNSPEC}, [{{nla_len=10, nla_type=NDA_LLADDR}, 02:e0:52:10:9c:ef}, {{nla_len=8, nla_type=NDA_MASTER}, if_nametoindex("br_out_101")}, {{nla_len=20, nla_type=NDA_CACHEINFO}, {ndm_confirmed=0, ndm_used=1310925, ndm_updated=0, ndm_refcnt=0}}]}, iov_len=3080}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_NETLINK, cmsg_type=0x3}], msg_controllen=24, msg_flags=0}, MSG_TRUNC) = 68
gettid()                                = 947
epoll_wait(4, [{EPOLLIN, {u32=3090839696, u64=94178838739088}}], 24, 0) = 1
gettid()                                = 947
epoll_wait(4, [{EPOLLIN, {u32=3090839696, u64=94178838739088}}], 24, 0) = 1
recvmsg(7, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000004}, msg_namelen=128->12, msg_iov=[{iov_base=NULL, iov_len=0}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_NETLINK, cmsg_type=0x3}], msg_controllen=24, msg_flags=MSG_TRUNC}, MSG_PEEK|MSG_TRUNC) = 68
recvmsg(7, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000004}, msg_namelen=128->12, msg_iov=[{iov_base={{len=68, type=RTM_NEWNEIGH, flags=0, seq=0, pid=0}, {ndm_family=AF_BRIDGE, ndm_ifindex=if_nametoindex("fw0.102"), ndm_state=NUD_REACHABLE, ndm_flags=0, ndm_type=RTN_UNSPEC}, [{{nla_len=10, nla_type=NDA_LLADDR}, b4:2d:56:ff:97:5f}, {{nla_len=8, nla_type=NDA_MASTER}, if_nametoindex("br_in_102")}, {{nla_len=20, nla_type=NDA_CACHEINFO}, {ndm_confirmed=0, ndm_used=1230214, ndm_updated=0, ndm_refcnt=0}}]}, iov_len=3080}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_NETLINK, cmsg_type=0x3}], msg_controllen=24, msg_flags=0}, MSG_TRUNC) = 68
gettid()                                = 947
epoll_wait(4, [{EPOLLIN, {u32=3090839696, u64=94178838739088}}], 24, 0) = 1
gettid()                                = 947
epoll_wait(4, [{EPOLLIN, {u32=3090839696, u64=94178838739088}}], 24, 0) = 1
recvmsg(7, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000004}, msg_namelen=128->12, msg_iov=[{iov_base=NULL, iov_len=0}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_NETLINK, cmsg_type=0x3}], msg_controllen=24, msg_flags=MSG_TRUNC}, MSG_PEEK|MSG_TRUNC) = 68
recvmsg(7, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000004}, msg_namelen=128->12, msg_iov=[{iov_base={{len=68, type=RTM_NEWNEIGH, flags=0, seq=0, pid=0}, {ndm_family=AF_BRIDGE, ndm_ifindex=if_nametoindex("fw0.102"), ndm_state=NUD_REACHABLE, ndm_flags=0, ndm_type=RTN_UNSPEC}, [{{nla_len=10, nla_type=NDA_LLADDR}, b4:2d:56:ff:44:bb}, {{nla_len=8, nla_type=NDA_MASTER}, if_nametoindex("br_in_102")}, {{nla_len=20, nla_type=NDA_CACHEINFO}, {ndm_confirmed=0, ndm_used=1230215, ndm_updated=0, ndm_refcnt=0}}]}, iov_len=3080}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_NETLINK, cmsg_type=0x3}], msg_controllen=24, msg_flags=0}, MSG_TRUNC) = 68
gettid()                                = 947
epoll_wait(4, [{EPOLLIN, {u32=3090839696, u64=94178838739088}}], 24, 0) = 1
gettid()                                = 947
epoll_wait(4, [{EPOLLIN, {u32=3090839696, u64=94178838739088}}], 24, 0) = 1
recvmsg(7, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000004}, msg_namelen=128->12, msg_iov=[{iov_base=NULL, iov_len=0}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_NETLINK, cmsg_type=0x3}], msg_controllen=24, msg_flags=MSG_TRUNC}, MSG_PEEK|MSG_TRUNC) = 68
recvmsg(7, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000004}, msg_namelen=128->12, msg_iov=[{iov_base={{len=68, type=RTM_NEWNEIGH, flags=0, seq=0, pid=0}, {ndm_family=AF_BRIDGE, ndm_ifindex=if_nametoindex("vx_i_102"), ndm_state=NUD_REACHABLE, ndm_flags=0, ndm_type=RTN_UNSPEC}, [{{nla_len=10, nla_type=NDA_LLADDR}, 02:e0:52:10:9c:ef}, {{nla_len=8, nla_type=NDA_MASTER}, if_nametoindex("br_in_102")}, {{nla_len=20, nla_type=NDA_CACHEINFO}, {ndm_confirmed=0, ndm_used=1230110, ndm_updated=0, ndm_refcnt=0}}]}, iov_len=3080}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_NETLINK, cmsg_type=0x3}], msg_controllen=24, msg_flags=0}, MSG_TRUNC) = 68
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #21031.

### CODE REVIEW

File: src/libsystemd/sd-netlink/sd-netlink.c [hunk 1]
```diff
@@ -1023,3 +1023,18 @@ int sd_netlink_add_match(
...
+        struct sock_fprog prog = {
+                .len = len,
+                .filter = filter,
+        };
+
+        assert_return(nl, -EINVAL);
+        assert_return(len == 0 || filter, -EINVAL);
+
+        if (setsockopt(nl->fd, SOL_SOCKET, len == 0 ? SO_DETACH_FILTER : SO_ATTACH_FILTER, &prog, sizeof(prog)) < 0)
+                return -errno;
```
Comment (poettering) [inline src/libsystemd/sd-netlink/sd-netlink.c:1037]: nit: SO_DETACH_FILTER ignores the passed parameter, thus maybe strange to specify that?

```c
if (len == 0)
        r = setsockopt(nl->fd, SOL_SOCKET, SO_DETACH_FILTER, NULL, 0);
else
        r = setsockopt(nl->fd, SOL_SOCKET, SO_ATTACH_FILTER,
                &(struct sock_fprog) {
                        .len = len,
                        .filter = filter,
                }, sizeof(struct sock_fprog));
if (r < 0)
        return -errno;
```

or so?

**Comment by bluca** [comment]
Looks related:

```
 364/1234 test-sd-device-monitor                  FAIL     0.52 s (killed by signal 6 SIGABRT)

--- command ---
11:02:07 SYSTEMD_LANGUAGE_FALLBACK_MAP='/home/runner/work/systemd/systemd/src/locale/language-fallback-map' PATH='/home/runner/work/systemd/systemd/build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin' SYSTEMD_KBD_MODEL_MAP='/home/runner/work/systemd/systemd/src/locale/kbd-model-map' /home/runner/work/systemd/systemd/build/test-sd-device-monitor
--- stderr ---
/* test_receive_device_fail */
lo: /* test_send_receive_one(subsystem_filter=false, tag_filter=false, use_bpf=false) */
lo: /* test_send_receive_one(subsystem_filter=true, tag_filter=false, use_bpf=false) */
lo: /* test_send_receive_one(subsystem_filter=false, tag_filter=true, use_bpf=false) */
lo: /* test_send_receive_one(subsystem_filter=true, tag_filter=true, use_bpf=false) */
lo: /* test_send_receive_one(subsystem_filter=true, tag_filter=false, use_bpf=true) */
lo: /* test_send_receive_one(subsystem_filter=false, tag_filter=true, use_bpf=true) */
lo: /* test_send_receive_one(subsystem_filter=true, tag_filter=true, use_bpf=true) */
lo: /* test_subsystem_filter */
lo: Sending device subsystem:net syspath:/sys/devices/virtual/net/lo
lo: /* test_tag_filter */
lo: Sending device syspath:/sys/devices/virtual/net/lo
lo: /* test_sysattr_filter(ifindex) */
lo: Sending device syspath:/sys/devices/virtual/net/lo
lo: /* test_sd_device_monitor_filter_remove */
Assertion 'sd_device_monitor_filter_remove(monitor_client) >= 0' failed at src/libsystemd/sd-device/test-sd-device-monitor.c:278, function test_sd_device_monitor_filter_remove(). Aborting.
```
