### PR TITLE
test: make test-55-oomd less flaky

### LINKED ISSUE #21146: TEST-55-OOMD occasionally fails
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > Arch Linux

Looks like there's a synchronization problem between the `runas` and `oomctl | grep -E` sections:
https://github.com/systemd/systemd/blob/cfee6b955154c30be31ffcf0e3b7b89374a52fff/test/units/testsuite-55.sh#L70-L76

```
[   32.676407] systemd[229]: Created slice Slice /testsuite.
[   32.677026] systemd[229]: Created slice Slice /testsuite/55.
[   32.677733] systemd[229]: Created slice Test slice for memory pressure kills.
[   32.680791] systemd[229]: Started No memory pressure.
[   32.683993] su[285]: pam_unix(su:session): session closed for user testuser
[   32.686188] testsuite-55.sh[237]: + runas testuser systemctl start --user testsuite-55-testbloat.service
[   32.686188] testsuite-55.sh[237]: + declare userid=testuser
[   32.686188] testsuite-55.sh[237]: + shift
[   32.686188] testsuite-55.sh[237]: + su testuser -s /bin/sh -c 'XDG_RUNTIME_DIR=/run/user/$UID exec "$@"' -- sh systemctl start --user testsuite-55-testbloat.service
[   32.691295] su[288]: (to testuser) root on none
[   32.703781] su[288]: pam_unix(su:session): session opened for user testuser(uid=4711) by (uid=0)
[   32.717058] systemd[229]: Started Create a lot of memory pressure.
[   32.720404] su[288]: pam_unix(su:session): session closed for user testuser
[   32.722123] testsuite-55.sh[292]: + grep -E '/user.slice.*/testsuite-55-workload.slice'
[   32.723919] testsuite-55.sh[291]: + oomctl
[   32.746796] testsuite-55-slowgrowth.sh[290]: target 107831296
[   32.746796] testsuite-55-slowgrowth.sh[290]: mem usage 2973696
[   32.785733] systemd-oomd[260]: oomd: New incoming message: {"parameters":{"cgroups":[{"mode":"auto","path":"/testsuite.slice/testsuite-55.slice/testsuite-55-workload.slice/testsuite-55-testbloat.service","property":"ManagedOOMSwap"},{">
[   32.785924] systemd-oomd[260]: oomd: Changing state awaiting-reply-more → processing-reply
[   32.785999] systemd-oomd[260]: oomd: Changing state processing-reply → awaiting-reply-more
[   32.786062] systemd-oomd[260]: Got message type=method_call sender=:1.9 destination=org.freedesktop.oom1 path=/org/freedesktop/oom1 interface=org.freedesktop.oom1.Manager member=DumpByFileDescriptor cookie=2 reply_cookie=0 signature=n/>
[   32.786192] systemd-oomd[260]: Sent message type=method_return sender=n/a destination=:1.9 path=n/a interface=n/a member=n/a cookie=6 reply_cookie=2 signature=h error-name=n/a error-message=n/a
[   32.786272] systemd-oomd[260]: varlink: New incoming connection.
[   32.786370] systemd-oomd[260]: varlink: Connections of user 4711: 0 (of 576 max)
[   32.786433] systemd-oomd[260]: varlink-11: Setting state idle-server
[   32.786523] systemd-oomd[260]: varlink-11: New incoming message: {"method":"io.systemd.oom.ReportManagedOOMCGroups","parameters":{"cgroups":[]},"oneway":true}
[   32.786591] systemd-oomd[260]: varlink-11: Changing state idle-server → processing-method-oneway
[   32.786751] systemd-oomd[260]: varlink-11: Changing state processing-method-oneway → idle-server
[   32.786826] systemd-oomd[260]: varlink-11: New incoming message: {"method":"io.systemd.oom.ReportManagedOOMCGroups","parameters":{"cgroups":[{"mode":"auto","path":"/user.slice/user-4711.slice/user@4711.service/testsuite.slice","propert>
[   32.786898] systemd-oomd[260]: varlink-11: Changing state idle-server → processing-method-oneway
[   32.786979] systemd-oomd[260]: varlink-11: Changing state processing-method-oneway → idle-server
[   32.787037] systemd-oomd[260]: varlink-11: New incoming message: {"method":"io.systemd.oom.ReportManagedOOMCGroups","parameters":{"cgroups":[{"mode":"auto","path":"/user.slice/user-4711.slice/user@4711.service/testsuite.slice/testsuite>
[   32.787107] systemd-oomd[260]: varlink-11: Changing state idle-server → processing-method-oneway
[   32.787164] systemd-oomd[260]: varlink-11: Changing state processing-method-oneway → idle-server
[   32.787216] systemd-oomd[260]: varlink-11: New incoming message: {"method":"io.systemd.oom.ReportManagedOOMCGroups","parameters":{"cgroups":[{"mode":"auto","path":"/user.slice/user-4711.slice/user@4711.service/testsuite.slice/testsuite>
[   32.787280] systemd-oomd[260]: varlink-11: Changing state idle-server → processing-method-oneway
[   32.787347] systemd-oomd[260]: varlink-11: Changing state processing-method-oneway → idle-server
[   32.787402] systemd-oomd[260]: varlink-11: New incoming message: {"method":"io.systemd.oom.ReportManagedOOMCGroups","parameters":{"cgroups":[{"mode":"auto","path":"/user.slice/user-4711.slice/user@4711.service/testsuite.slice/testsuite>
[   32.793258] systemd-oomd[260]: varlink-11: Changing state idle-server → processing-method-oneway
[   32.793442] systemd-oomd[260]: varlink-11: Changing state processing-method-oneway → idle-server
[   32.793645] systemd-oomd[260]: varlink-11: New incoming message: {"method":"io.systemd.oom.ReportManagedOOMCGroups","parameters":{"cgroups":[{"mode":"auto","path":"/user.slice/user-4711.slice/user@4711.service/testsuite.slice/testsuite>
[   32.793782] systemd-oomd[260]: varlink-11: Changing state idle-server → processing-method-oneway
[   32.793861] systemd-oomd[260]: varlink-11: Changing state processing-method-oneway → idle-server
[   32.893103] audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=testsuite-55 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
[   32.922309] sh[296]: + systemctl poweroff --no-block
[   33.156247] systemd-logind[222]: System is powering down.
[   37.144959] systemd-oomd[260]: oomd: New incoming message: {"parameters":{"cgroups":[{"mode":"auto","path":"/system.slice/testsuite-55.service","property":"ManagedOOMSwap"},{"mode":"auto","path":"/system.slice/testsuite-55.service","pr>
[   37.145414] systemd-oomd[260]: oomd: Changing state awaiting-reply-more → processing-reply
[   37.145505] systemd-oomd[260]: oomd: Changing state processing-reply → awaiting-reply-more
```

(the `grep -E` call returns 1 in this case)

Logs:
  * [system.journal.tar.gz](https://github.com/systemd/systemd/files/7424695/system.journal.tar.gz)
  * [TEST-55-OOMD_FAIL.log](https://github.com/systemd/systemd/files/7424697/TEST-55-OOMD_FAIL.log)

The same seems to be true for the "system" part of the test:
https://github.com/systemd/systemd/blob/cfee6b955154c30be31ffcf0e3b7b89374a52fff/test/units/testsuite-55.sh#L37-L43

```
[   22.077309] testsuite-55.sh[241]: + systemctl start testsuite-55-testchill.service
[   27.038475] systemd-oomd[265]: Bus bus-api-oom: changing state UNSET → OPENING
[   27.039030] systemd-oomd[265]: sd-bus: starting bus bus-api-oom by connecting to /run/dbus/system_bus_socket...
[   27.039149] systemd-oomd[265]: Bus bus-api-oom: changing state OPENING → AUTHENTICATING
[   27.047128] systemd-oomd[265]: Registering bus object implementation for path=/org/freedesktop/oom1 iface=org.freedesktop.oom1.Manager
[   27.047297] systemd-oomd[265]: Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
[   27.047425] systemd-oomd[265]: varlink: Setting state idle-client
[   27.047553] systemd-oomd[265]: oomd: Sending message: {"method":"io.systemd.ManagedOOM.SubscribeManagedOOMCGroups","parameters":{},"more":true}
[   27.047661] systemd-oomd[265]: oomd: Changing state idle-client → awaiting-reply-more
[   27.047763] systemd-oomd[265]: Initialized systemd-oomd varlink server
[   27.047887] systemd-oomd[265]: systemd-oomd started.
[   27.583469] testsuite-55.sh[241]: + systemctl start testsuite-55-testbloat.service
[   30.635314] testsuite-55.sh[270]: + oomctl
[   30.635719] testsuite-55.sh[271]: + grep /testsuite-55-workload.slice
[   30.655389] testsuite-55-slowgrowth.sh[268]: target 107970560
[   30.655389] testsuite-55-slowgrowth.sh[268]: mem usage 3112960
[   30.710030] dbus-daemon[230]: [system] Activating via systemd: service name='org.freedesktop.oom1' unit='dbus-org.freedesktop.oom1.service' requested by ':1.5' (uid=0 pid=270 comm="oomctl ")
[   31.190865] systemd-oomd[265]: Bus bus-api-oom: changing state AUTHENTICATING → HELLO
[   31.191293] systemd-oomd[265]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error->
[   31.191379] systemd-oomd[265]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RequestName cookie=2 reply_cookie=0 signature=su error-name=n/a e>
[   31.191460] dbus-daemon[230]: [system] Successfully activated service 'org.freedesktop.oom1'
[   31.191578] systemd-oomd[265]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.6 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
[   31.191686] systemd-oomd[265]: Bus bus-api-oom: changing state HELLO → RUNNING
[   31.191789] systemd-oomd[265]: Got message type=signal sender=org.freedesktop.DBus.Local destination=n/a path=/org/freedesktop/DBus/Local interface=org.freedesktop.DBus.Local member=Connected cookie=4294967295 reply_cookie=0 signature=>
[   31.191896] systemd-oomd[265]: Got message type=signal sender=org.freedesktop.DBus destination=:1.6 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=2 reply_cookie=0 signature=s error-name=n/a error->
[   31.192001] systemd-oomd[265]: Got message type=signal sender=org.freedesktop.DBus destination=:1.6 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=3 reply_cookie=0 signature=s error-name=n/a error->
[   31.192146] systemd-oomd[265]: Got message type=method_call sender=:1.5 destination=org.freedesktop.oom1 path=/org/freedesktop/oom1 interface=org.freedesktop.oom1.Manager member=DumpByFileDescriptor cookie=2 reply_cookie=0 signature=n/>
[   31.192257] systemd-oomd[265]: Sent message type=method_return sender=n/a destination=:1.5 path=n/a interface=n/a member=n/a cookie=3 reply_cookie=2 signature=h error-name=n/a error-message=n/a
[   31.192373] systemd-oomd[265]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.6 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=2 signature=u error-name=n/a error-message=n/a
[   31.192455] systemd-oomd[265]: Successfully acquired requested service name.
[   31.290059] sh[274]: + systemctl poweroff --no-block
[   31.510423] systemd-logind[225]: System is powering down.
[   31.734149] systemd-oomd[265]: oomd: New incoming message: {"parameters":{"cgroups":[{"mode":"kill","path":"/testsuite.slice/testsuite-55.slice/testsuite-55-workload.slice","property":"ManagedOOMMemoryPressure","limit":858993459}]},"co>
[   31.734346] systemd-oomd[265]: oomd: Changing state awaiting-reply-more → processing-reply
[   31.734429] systemd-oomd[265]: oomd: Changing state processing-reply → awaiting-reply-more
[   35.769844] systemd-oomd[265]: Memory pressure for /testsuite.slice/testsuite-55.slice/testsuite-55-workload.slice is 34.80% > 20.00% for > 2s with reclaim activity
[   35.770609] systemd-oomd[265]: oomd attempting to kill 268 with KILL
[   35.770773] systemd-oomd[265]: oomd attempting to kill 273 with KILL
```

Logs:
  * [system.journal.tar.gz](https://github.com/systemd/systemd/files/7424718/system.journal.tar.gz)
  * [TEST-55-OOMD_FAIL.log](https://github.com/systemd/systemd/files/7424721/TEST-55-OOMD_FAIL.log)

/cc @anitazha

### PR DESCRIPTION
**Pull request by anitazha**
Make oomctl a bit less likely to race with systemd-oomd receiving the
managed oom cgroup info by checking oomctl output in a loop with
timeout.

Fixes #21146

### CODE REVIEW

File: test/units/testsuite-55.sh [hunk 1]
```diff
@@ -38,9 +38,20 @@ systemctl start testsuite-55-testchill.service
 systemctl start testsuite-55-testbloat.service
 
 # Verify systemd-oomd is monitoring the expected units
-oomctl | grep "/testsuite-55-workload.slice"
-oomctl | grep "20.00%"
-oomctl | grep "Default Memory Pressure Duration: 2s"
+# Try to avoid racing the oomctl output check by checking in a loop with a timeout
+oomctl_output=$(oomctl)
+timeout="$(date -ud "1 minutes" +%s)"
```
Comment (bluca) [inline test/units/testsuite-55.sh:43]: Make it 5? Some of those CIs are _really_ congested

Comment (keszybz) [reply test/units/testsuite-55.sh:43]: Well, we went from a timeout of 0 s to 60 s here. Maybe this will be enough.

Comment (bluca) [reply test/units/testsuite-55.sh:43]: ok, let's merge this and if needed bump it again

**Review by bluca — APPROVED** [review]

**Comment by keszybz** [comment]
I'll merge this, @bluca's comment notwithstanding. Maybe this will be enough to avoid the flakes.

centos ci(arch linux), focal-ppc64el, focal-s390x all failed with unrelated timeouts.
