### PR TITLE
systemd-run: ensure error logs suggest to use '--user' when appropriate

### LINKED ISSUE #21933: Missing "--user" in the error message: "systemctl status run-re0d0bf6d3c994fd58fb9b35c67291e7b.service"
**systemd version the issue has been seen with**
 > 249.7

**Used distribution**
 > Fedora 35

**Linux kernel version used** (`uname -a`)

 > `Linux laptop 5.15.11-200.fc35.x86_64 #1 SMP Wed Dec 22 15:41:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > ```See "systemctl --user status run-re0d0bf6d3c994fd58fb9b35c67291e7b.service"```

**Unexpected behaviour you saw**
 > ```See "systemctl status run-re0d0bf6d3c994fd58fb9b35c67291e7b.service"```

**Steps to reproduce the problem**
 

```
[testuser@laptop ~]$ systemd-run --user --service-type=notify /bin/false
Job for run-re0d0bf6d3c994fd58fb9b35c67291e7b.service failed because the control process exited with error code.
See "systemctl status run-re0d0bf6d3c994fd58fb9b35c67291e7b.service" and "journalctl -xeu run-re0d0bf6d3c994fd58fb9b35c67291e7b.service" for details.
[testuser@laptop ~]$
[testuser@laptop ~]$ systemctl status run-re0d0bf6d3c994fd58fb9b35c67291e7b.service
Unit run-re0d0bf6d3c994fd58fb9b35c67291e7b.service could not be found.
[testuser@laptop ~]$ systemctl --user status run-re0d0bf6d3c994fd58fb9b35c67291e7b.service
× run-re0d0bf6d3c994fd58fb9b35c67291e7b.service - /bin/false
     Loaded: loaded (/run/user/1014/systemd/transient/run-re0d0bf6d3c994fd58fb9b35c67291e7b.service; transient)
  Transient: yes
     Active: failed (Result: exit-code) since Wed 2021-12-29 22:51:01 CET; 39s ago
    Process: 250475 ExecStart=/bin/false (code=exited, status=1/FAILURE)
   Main PID: 250475 (code=exited, status=1/FAILURE)
        CPU: 1ms

Dec 29 22:51:01 laptop systemd[250387]: Starting /bin/false...
Dec 29 22:51:01 laptop systemd[250387]: run-re0d0bf6d3c994fd58fb9b35c67291e7b.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 22:51:01 laptop systemd[250387]: run-re0d0bf6d3c994fd58fb9b35c67291e7b.service: Failed with result 'exit-code'.
Dec 29 22:51:01 laptop systemd[250387]: Failed to start /bin/false.
[testuser@laptop ~]$
```

The error message suggested the command `systemctl status run-re0d0bf6d3c994fd58fb9b35c67291e7b.service`
but that command failed. When adding the command-line flag `--user` the command started to work.

**Additional program output to the terminal or log subsystem illustrating the issue**

The same thing but running in debug mode

```text
[testuser@laptop ~]$ export SYSTEMD_LOG_LEVEL=debug
[testuser@laptop ~]$ systemd-run --user --service-type=notify /bin/false
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/user/1014/systemd/private...
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=StartTransientUnit cookie=1 reply_cookie=0 signature=ssa(sv)a(sa(sv)) error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a cookie=3 reply_cookie=1 signature=o error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=1 reply_cookie=0 signature=so error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobNew cookie=2 reply_cookie=0 signature=uos error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/run_2dr8e300f71b2f246fabf1ba4d7a3578d89_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=4 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/run_2dr8e300f71b2f246fabf1ba4d7a3578d89_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=5 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/run_2dr8e300f71b2f246fabf1ba4d7a3578d89_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=6 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/run_2dr8e300f71b2f246fabf1ba4d7a3578d89_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=7 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/job/22 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=8 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/run_2dr8e300f71b2f246fabf1ba4d7a3578d89_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=10 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/run_2dr8e300f71b2f246fabf1ba4d7a3578d89_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=11 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=12 reply_cookie=0 signature=uoss error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/run_2dr8e300f71b2f246fabf1ba4d7a3578d89_2eservice interface=org.freedesktop.DBus.Properties member=Get cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a cookie=15 reply_cookie=2 signature=v error-name=n/a error-message=n/a
Job for run-r8e300f71b2f246fabf1ba4d7a3578d89.service failed because the control process exited with error code.
See "systemctl status run-r8e300f71b2f246fabf1ba4d7a3578d89.service" and "journalctl -xeu run-r8e300f71b2f246fabf1ba4d7a3578d89.service" for details.
Unexpected job result, assuming server side newer than us: failed
Got result failed/Input/output error for job run-r8e300f71b2f246fabf1ba4d7a3578d89.service
Bus n/a: changing state RUNNING → CLOSED
[testuser@laptop ~]$ 
[testuser@laptop ~]$ systemctl status run-r8e300f71b2f246fabf1ba4d7a3578d89.service
running_in_chroot(): Permission denied
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → AUTHENTICATING
Successfully forked off '(pager)' as PID 251100.
Skipping PR_SET_MM, as we don't have privileges.
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Failed to execute 'pager', using next fallback pager: No such file or directory
Pager executable is "less", options "FRSXMK", quit_on_interrupt: yes
Showing one /org/freedesktop/systemd1/unit/run_2dr8e300f71b2f246fabf1ba4d7a3578d89_2eservice
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.780 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/run_2dr8e300f71b2f246fabf1ba4d7a3578d89_2eservice interface=org.freedesktop.DBus.Properties member=GetAll cookie=2 reply_co>
Got message type=method_return sender=:1.15 destination=:1.780 path=n/a interface=n/a member=n/a cookie=9291 reply_cookie=2 signature=a{sv} error-name=n/a error-message=n/a
Unit run-r8e300f71b2f246fabf1ba4d7a3578d89.service could not be found.
Bus n/a: changing state RUNNING → CLOSED
[testuser@laptop ~]$ 
[testuser@laptop ~]$ 
[testuser@laptop ~]$ systemctl --user status run-r8e300f71b2f246fabf1ba4d7a3578d89.service
running_in_chroot(): Permission denied
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/user/1014/systemd/private...
Bus n/a: changing state OPENING → AUTHENTICATING
Successfully forked off '(pager)' as PID 251102.
Skipping PR_SET_MM, as we don't have privileges.
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Failed to execute 'pager', using next fallback pager: No such file or directory
Pager executable is "less", options "FRSXMK", quit_on_interrupt: yes
Showing one /org/freedesktop/systemd1/unit/run_2dr8e300f71b2f246fabf1ba4d7a3578d89_2eservice
Bus n/a: changing state AUTHENTICATING → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/run_2dr8e300f71b2f246fabf1ba4d7a3578d89_2eservice interface=org.freedesktop.DBus.Properties member=GetAll cookie=1 reply_co>
Got message type=method_return sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=a{sv} error-name=n/a error-message=n/a
Considering root directory '/run/log/journal'.
Root directory /run/log/journal added.
Considering root directory '/var/log/journal'.
Root directory /var/log/journal added.
Considering directory '/var/log/journal/c341780e88a04800982a41eea47639d3'.
Directory /var/log/journal/c341780e88a04800982a41eea47639d3 added.
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1007.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1011.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1013.journal: Permission denied
Journal effective settings seal=no keyed_hash=yes compress=no compress_threshold_bytes=8B
File /var/log/journal/c341780e88a04800982a41eea47639d3/user-1014.journal added.
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@368844d1cbf840faa5004552998c14b8-00000000000008c3-0005abec29928e34.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1010.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@eef5206cd0db4a2995a43ee1ce788bc1-0000000000000b9c-0005abec30841cc7.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@368844d1cbf840faa5004552998c14b8-0000000000000ba3-0005abec32e36230.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@eef5206cd0db4a2995a43ee1ce788bc1-000000000000ba90-0005afc569ebfbef.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005bffdc16e6c76-35389814a0007d7d.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@eef5206cd0db4a2995a43ee1ce788bc1-000000000000beaa-0005afc56a68eeca.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1012.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@975e0d5f2e194af399e14baf4f2af583-000000000000bf20-0005afc56d9a50cd.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1008.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@eef5206cd0db4a2995a43ee1ce788bc1-0000000000012d47-0005b13f17887e60.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@975e0d5f2e194af399e14baf4f2af583-0000000000012d78-0005b13f1b439c18.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005b29280edb06f-686e4fb5a87e48e2.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005b29a54d743a9-60a8f6f91943a327.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@51fa78dcdf604f3e957c86cfde9bbec0-0000000000000001-0005b29280bfd9ff.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@fce36038f9a146f2ae8e964cde464eab-0000000000000a1b-0005b29a54d73d7a.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@51fa78dcdf604f3e957c86cfde9bbec0-00000000000069b7-0005b2ad33a5733d.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@6130fa3416ef443dbfa83aa572ac0e9c-0000000000006e69-0005b2ad3b2e64ad.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@51fa78dcdf604f3e957c86cfde9bbec0-000000000001ce2d-0005b5830d9f58b5.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@3dddb0ab836b4729ab9c711cd8b0de7f-000000000001d438-0005b5830f2fedd0.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005b89c05f9c155-cb6b7db423efe2d9.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@bafa1c6dae59449eb4ed26b09d006579-0000000000000001-0005b89c05d20fba.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@00fcce8bdb7545b6a4809c08efbfb23c-000000000001fd9a-0005b5dbee4161a0.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005ba063aab2c12-4df24deeb5b5a54a.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@9349e094c5f34314a1dbe22316ad398f-0000000000000001-0005ba063a8057be.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005ba063aa424cf-69a5ba01b80e7990.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005ba8ac46ffac5-71ae106455cf9c05.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005ba8ac57bb041-55970feebbc4feb3.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005bbe93c32e140-2b423acf36d06a7a.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005bbe93d5f8fd8-8dfb70f9acd49745.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@30447c0f0e5f440cb8eb8b56e21e5ac2-0000000000000001-0005bbe93c09ca3c.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@46066eb54c7543dd986f2199fd3c5aae-0000000000000af1-0005bbe93d5f8a71.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005bf47b75c2ccf-24d57413683b4fbd.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005bffdc07a8289-928c2363455e4ff6.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005c12b10441f1b-7d3dfaa07632b222.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005c12b112f33f3-f3c8e35902736fa5.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005c1d1df305eab-5f328ddc18dc215c.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005c1d1eaed85d8-d8e9276a99a9cef6.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005c3dc596c788d-44b004ec1512175e.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005c3dc5a681379-4f1a28b89b74f3f8.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005c42b712baf7f-e00f8e4067c7298b.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005c4340979a9c0-b9246162ef7c258c.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@f5354b70557347058b9f548681dab43c-0000000000000001-0005c42b710a5bc1.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@1822f183d94242b8bf43ed32afb7be17-0000000000000cd6-0005c4340979a206.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005c60e26996957-135b5c8054738f51.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005c60e27a8a96c-5d7ad7aa58a3ea28.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005c88dc4404c29-76528e7099eb5cd6.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@8e004093283d469283b8804f9fad2199-0000000000000001-0005c88dc42a0bc2.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005c88dc4fd6122-90d5eb6bc117c00b.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005c8f1ee0e5d3a-d380cdee767f0261.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005c8f1efb43cc7-64f45e1b73c06edf.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005cb38f7ca49fc-a19c244cc5ff180b.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005cb38f8d64852-2e86bf31fbdc354e.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005cba31207a832-c9d19864da4fc293.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005cba312fcc157-4090d07419bed74a.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005cba45d4f6b8f-0c81172ac3aa404e.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005cba45e5d918e-e3db32e30d339059.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005cd08f9deff1a-b7539643868c5e2a.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005cd08faf79fed-eaa71b9d6c311335.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@41e9f6937490423fb8b2a5394c62c5ac-0000000000000001-0005cd08f9c79681.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@d0cb8ca011904e2d8d4e2a33faf6397e-000000000000090d-0005cd08faf79755.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1002@bce5807dad2745d19bc2824b07ace015-00000000000023cc-0005cb6716f716d9.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1003@53d07811216247a7838ada42cf28c5c9-000000000001c82d-0005cc7af0f00802.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1001@9c1e2184574d4a0d80d51f1bb319f78b-0000000000002126-0005cb66efca54df.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005ce39a987c4ce-aa6baf66e3692ae6.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005ce39aa8b0d88-753efc404e745e0f.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005ce88455f557d-cf7b307d2e648a88.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005ce884666803e-5cfec367aa51f6d4.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005ceb72ba6955d-dcbd452c69f81e53.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005ceb72cc8fead-ab93d07ad9de6d43.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@aedf705ff65d497f86fb2bf3d2cb2c59-0000000000000001-0005ceb72b8db35d.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@3c0f78df80084cb99d0d8d74baef483f-0000000000000900-0005ceb72cc8f5ba.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1006@d11cbcd73978436fa81ace115e183eea-000000000002b56b-0005cf2a4067f229.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1004@8182560d86694602815cfc044f4c76cd-0000000000021575-0005ce007faaef8d.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1007@8ca2164f9b10438d8643c5577de0ddb4-000000000003466f-0005cfa290d05c1b.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1002@bce5807dad2745d19bc2824b07ace015-000000000001e939-0005cdd8a774610a.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1001@61952d195889463da9f733791c1d4ac2-0000000000021b12-0005ce01942c2ab0.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1003@1c24a46a35d74a6b8d2a95e57bc1a36a-000000000002139e-0005cdffe6563343.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1005@66db7d8fa97f415eb98bd969b738c494-000000000002b4d2-0005cf2a3ab1fd30.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005d01d19a3ddf4-f391ca57bca06a49.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005d01d1ae384e9-2385472f45e955b6.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1008@0005d01f680c6cc1-b6f3348c7a431321.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005d15198923194-49d177d55463d4c6.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005d26338373ea4-52add977359c0c35.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005d2633972ba4c-904d7b1e37b94c19.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@cd0b29a21c664eef92313712bde29c2e-0000000000000001-0005d263381d0a14.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@2765d2c7d2034adb8a1074b410070a47-00000000000008ff-0005d26339728f69.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1008@a43425d78ffa41f6b3b2e3d811ce0565-0000000000000c83-0005d01f680c6109.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1007@8ca2164f9b10438d8643c5577de0ddb4-00000000000389fb-0005cfbbb5f42ab8.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1009@9787b4c214b34fd3bb20bfdb3b0a741d-0000000000042617-0005d0ec27480e91.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1006@d11cbcd73978436fa81ace115e183eea-0000000000038e73-0005cfbe6b819571.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1004@8182560d86694602815cfc044f4c76cd-0000000000038d2d-0005cfbca52c4636.journal: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005d3434178456c-df701710c10a29e2.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005d34342818dbb-83825ce3fe1941f1.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/system@0005d3e5d1f9ad78-9e7ee7c4c857af72.journal~: Permission denied
Failed to open journal file /var/log/journal/c341780e88a04800982a41eea47639d3/user-1000@0005d3e5d2f0030d-3a64a109d951f468.journal~: Permission denied
Journal filter: (_BOOT_ID=de7611d2bb1b4621bfa6e65a7379cf17 AND (((_UID=0 OR _UID=1014) AND OBJECT_SYSTEMD_USER_UNIT=run-r8e300f71b2f246fabf1ba4d7a3578d89.service) OR ((_UID=0 OR _UID=1014) AND COREDUMP_USER_UNIT=run-r8e300f71b2f246fabf1b>
Directory /var/log/journal/c341780e88a04800982a41eea47639d3 removed.
Root directory /var/log/journal removed.
Root directory /run/log/journal removed.
mmap cache statistics: 3535 context cache hit, 4 window list hit, 1 miss
Bus n/a: changing state RUNNING → CLOSED
× run-r8e300f71b2f246fabf1ba4d7a3578d89.service - /bin/false
     Loaded: loaded (/run/user/1014/systemd/transient/run-r8e300f71b2f246fabf1ba4d7a3578d89.service; transient)
  Transient: yes
     Active: failed (Result: exit-code) since Wed 2021-12-29 23:05:56 CET; 2min 55s ago
    Process: 251034 ExecStart=/bin/false (code=exited, status=1/FAILURE)
   Main PID: 251034 (code=exited, status=1/FAILURE)
        CPU: 1ms

Dec 29 23:05:56 laptop systemd[250939]: Starting /bin/false...
Dec 29 23:05:56 laptop systemd[250939]: run-r8e300f71b2f246fabf1ba4d7a3578d89.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 23:05:56 laptop systemd[250939]: run-r8e300f71b2f246fabf1ba4d7a3578d89.service: Failed with result 'exit-code'.
Dec 29 23:05:56 laptop systemd[250939]: Failed to start /bin/false.
```

### PR DESCRIPTION
**Pull request by bluca**
Before:

```
$ systemd-run --service-type=notify --user false
Job for run-rc3fe52ee6ddd4a6eaaf1a20e0a949cdf.service failed because the control process exited with error code.
See "systemctl status run-rc3fe52ee6ddd4a6eaaf1a20e0a949cdf.service" and "journalctl -xeu run-rc3fe52ee6ddd4a6eaaf1a20e0a949cdf.service" for details.
```

After:

```
$ systemd-run --service-type=notify --user false
Job for run-r7791e380a7b6400ea01d6a0e5a458b23.service failed because the control process exited with error code.
See "systemctl --user status run-r7791e380a7b6400ea01d6a0e5a458b23.service" and "journalctl --user -xeu run-r7791e380a7b6400ea01d6a0e5a458b23.service" for details.
```

Fixes #21933

### CODE REVIEW

File: src/run/run.c [hunk 1]
```diff
@@ -1229,7 +1229,7 @@ static int start_transient_service(
                 if (r < 0)
                         return bus_log_parse_error(r);
 
-                r = bus_wait_for_jobs_one(w, object, arg_quiet, NULL);
+                r = bus_wait_for_jobs_one(w, object, arg_quiet, arg_user ? (const char* []) {"--user", NULL} : NULL);
```
Comment (yuwata) [inline src/run/run.c]: `STRV_MAKE_CONST()`?

**Review by yuwata — APPROVED** [review]
LGTM. One minor suggestion.

File: src/run/run.c (hunk 1 above)
Comment (bluca) [reply src/run/run.c]: yes indeed, forgot about that

**Comment by yuwata** [comment]
(Ouch. I mistakenly merged this with 'Rebase and Merge' button.)
