### PR TITLE
pcrlock: support measurement of big files

### LINKED ISSUE #31883: pcrlock lock-raw and lock-kernel-initrd fails with long files (>64MB)
### systemd version the issue has been seen with

256

### Used distribution

all

### Linux kernel version used

all

### CPU architectures issue was seen on

x86_64

### Component

systemd-pcrlock

### Unexpected behaviour you saw

```sh
$ systemd-pcrlock lock-raw --pcr=9 /boot/efi/opensuse-microos/6.7.9-1-default/initrd

Failed to read data from stdin: Argument list too long
```

### PR DESCRIPTION
**Pull request by aplanas**
Introduces a new read flag in fileio to read large files, and pcrlock uses it for locking raw files and initrd.

Fixes #31883

### CODE REVIEW

**Comment by bluca** [comment]
Completely foregoing the size check seems a bit too much, how about adding a version of the helper that takes in a custom max size? And then specify something like 1G that should be enough in normal cases?

**Comment by aplanas** [comment]
> Completely foregoing the size check seems a bit too much, how about adding a version of the helper that takes in a custom max size? And then specify something like 1G that should be enough in normal cases?

Yes, this makes more sense.

On one side I can simply change  `READ_FULL_BYTES_MAX` into something line  `(1U * U64_GB - UINT64_C(1))` and that will be all. This will change the global limit for every `read_full_xxx` family calls. Is this OK?

The other alternative is still add a new flag, something line `READ_FULL_FILE_LARGE_FILE` that will change the limit of 64MB to 1GB if the flag is set, and enable this flag in the pcrlock verbs. This will not change the default limit of 64MB, except when the flag is set.

What option does makes more sense for you?

**Comment by bluca** [comment]
Second one please, as we want the existing limit for other cases

**Comment by aplanas** [comment]
> Second one please, as we want the existing limit for other cases

Yes, of course. Should be done

**Review by bluca — APPROVED** [review]

File: src/pcrlock/pcrlock.c [hunk 1]
```diff
@@ -3808,8 +3808,8 @@ static int verb_lock_kernel_initrd(int argc, char *argv[], void *userdata) {
                         return log_error_errno(errno, "Failed to open '%s': %m", argv[1]);
         }
 
-        r = read_full_stream(f ?: stdin, (char**) &data, &size);
-        if (r < 0)
+        r = read_full_stream_full(f ?: stdin, NULL, UINT64_MAX, SIZE_MAX, READ_FULL_FILE_LARGE_FILE, (char**) &data, &size);
+         if (r < 0)
```
Comment (YHNdnzj) [inline src/pcrlock/pcrlock.c]: extra space?

File: src/basic/fileio.c [hunk 2]
```diff
@@ -706,12 +711,21 @@ int read_full_stream_full(
                         goto finalize;
                 }
 
-                if (n >= READ_FULL_BYTES_MAX) {
+                if (n >= READ_FULL_BYTES_MAX && !FLAGS_SET(flags, READ_FULL_FILE_LARGE_FILE)) {
+                        r = -E2BIG;
+                        goto finalize;
+                }
+
+                if (n >= READ_FULL_LARGE_BYTES_MAX) {
```
Comment (YHNdnzj) [inline src/basic/fileio.c]: The two if blocks can be merged?

```c
if (n >= (FLAGS_SET(flags, READ_FULL_FILE_LARGE_FILE) ? READ_FULL_LARGE_BYTES_MAX : READ_FULL_BYTES_MAX))
        ...
```

File: src/basic/fileio.c [hunk 3]
```diff
@@ -706,12 +711,21 @@ int read_full_stream_full(
...
                         r = -E2BIG;
                         goto finalize;
                 }
 
-                n_next = MIN(n * 2, READ_FULL_BYTES_MAX);
+                n_next = n * 2;
+                if (!FLAGS_SET(flags, READ_FULL_FILE_LARGE_FILE))
+                        n_next = MIN(n_next, READ_FULL_BYTES_MAX);
+                else
+                        n_next = MIN(n_next, READ_FULL_LARGE_BYTES_MAX);
```
Comment (YHNdnzj) [inline src/basic/fileio.c]: also here, ternary operator might be more straightforward?

**Review by YHNdnzj — APPROVED** [review]

File: src/pcrlock/pcrlock.c (hunk 1 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: fixed

File: src/basic/fileio.c (hunk 2 above)
Comment (aplanas) [reply src/basic/fileio.c]: Done

File: src/basic/fileio.c (hunk 3 above)
Comment (aplanas) [reply src/basic/fileio.c]: Yes. Done.

File: src/basic/fileio.c [hunk 4]
```diff
@@ -645,9 +647,12 @@ int read_full_stream_full(
                 n_next = size != SIZE_MAX && !FLAGS_SET(flags, READ_FULL_FILE_FAIL_WHEN_LARGER) ? size : LINE_MAX;
 
         /* Never read more than we need to determine that our own limit is hit */
-        if (n_next > READ_FULL_BYTES_MAX)
+        if (n_next > READ_FULL_BYTES_MAX && !FLAGS_SET(flags, READ_FULL_FILE_LARGE_FILE))
                 n_next = READ_FULL_BYTES_MAX + 1;
 
+        if (n_next > READ_FULL_LARGE_BYTES_MAX)
+                n_next = READ_FULL_LARGE_BYTES_MAX + 1;
```
Comment (keszybz) [inline src/basic/fileio.c]: That is ugly. Maybe:
```C

const size_t limit = FLAGS_SET(flags, READ_FULL_FILE_LARGE_FILE) ? READ_FULL_LARGE_BYTES_MAX :  READ_FULL_BYTES_MAX);

n_next = MIN(n_next, limit + 1);
```

and then limit can also be reused later on, instead of repeating the same condition.

File: src/basic/fileio.c [hunk 5]
```diff
@@ -657,7 +662,7 @@ int read_full_stream_full(
                 size_t k;
 
                 /* If we shall fail when reading overly large data, then read exactly one byte more than the
-                 * specified size at max, since that'll tell us if there's anymore data beyond the limit*/
+                 * specified size at max, since that'll tell us if there's anymore data beyond the limit */
```
Comment (keszybz) [inline src/basic/fileio.c]: Add ".".

File: src/basic/fileio.c [hunk 6]
```diff
@@ -706,12 +711,12 @@ int read_full_stream_full(
                         goto finalize;
                 }
 
-                if (n >= READ_FULL_BYTES_MAX) {
+                if (n >= (FLAGS_SET(flags, READ_FULL_FILE_LARGE_FILE) ? READ_FULL_LARGE_BYTES_MAX : READ_FULL_BYTES_MAX)) {
```
Comment (keszybz) [inline src/basic/fileio.c]: `... n >= limit ...`

File: src/basic/fileio.c [hunk 7]
```diff
@@ -33,6 +33,8 @@
 
 /* The maximum size of the file we'll read in one go in read_full_file() (64M). */
 #define READ_FULL_BYTES_MAX (64U * U64_MB - UINT64_C(1))
+/* The maximum size of large files that we'll read in one go in read_full_file() (1G). */
+#define READ_FULL_LARGE_BYTES_MAX (1U * U64_GB - UINT64_C(1))
```
Comment (keszybz) [inline src/basic/fileio.c]: This seems iffy. There are many systems where reading of 1GB of file into memory is not going to work.

File: src/pcrlock/pcrlock.c [hunk 8]
```diff
@@ -2769,7 +2769,7 @@ static int verb_lock_raw(int argc, char *argv[], void *userdata) {
                         return log_error_errno(errno, "Failed to open '%s': %m", argv[1]);
         }
 
-        r = read_full_stream(f ?: stdin, &data, &size);
+        r = read_full_stream_full(f ?: stdin, NULL, UINT64_MAX, SIZE_MAX, READ_FULL_FILE_LARGE_FILE, &data, &size);
```
Comment (keszybz) [inline src/pcrlock/pcrlock.c]: I very much don't like this solution. Reading a 64MB file into memory is a bit sloppy but OK on most systems. But reading 1GB files into memory is not right. And the 1GB limit is arbitrary too, I'm sure that there'll be people who'll want it raised because they embed nvidia firmware and whatnot. The internals should be reworked to use a streaming API to hash the file.

**Review by keszybz — CHANGES_REQUESTED** [review]

**Comment by Vogtinator** [comment]
The file doesn't need to be loaded into memory at once. IMO the correct solution is to have `make_pcrlock_record` accept a stream and use `EVP_DigestInit` + `EVP_DigestUpdate` + `EVP_DigestFinal` on the data stream.

File: src/basic/fileio.c (hunk 4 above)
Comment (aplanas) [reply src/basic/fileio.c]: yes, done

File: src/pcrlock/pcrlock.c (hunk 8 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: > The internals should be reworked to use a streaming API to hash the file.

I was thinking on creating a `make_pcrlock_record` variant that will accept a fd and use it only in those two verbs. Would that be accepted?

**Comment by aplanas** [comment]
> The file doesn't need to be loaded into memory at once. IMO the correct solution is to have `make_pcrlock_record` accept a stream and use `EVP_DigestInit` + `EVP_DigestUpdate` + `EVP_DigestFinal` on the data stream.

That is what is suggested here: https://github.com/systemd/systemd/pull/31889#discussion_r1536617197

But make_pcrlock_record cannot be replaced, there is use case where the parameter needs to be a place in memory. I proposed to create a variant of it that accept a fd. If this is accepted I will go for it.

**Comment by Vogtinator** [comment]
> > The file doesn't need to be loaded into memory at once. IMO the correct solution is to have `make_pcrlock_record` accept a stream and use `EVP_DigestInit` + `EVP_DigestUpdate` + `EVP_DigestFinal` on the data stream.
> 
> That is what is suggested here: [#31889 (comment)](https://github.com/systemd/systemd/pull/31889#discussion_r1536617197)
> 
> But make_pcrlock_record cannot be replaced, there is use case where the parameter needs to be a place in memory. I proposed to create a variant of it that accept a fd. If this is accepted I will go for it.

Could be abstracted using `fmemopen` / `open_memstream` as well

File: src/pcrlock/pcrlock.c (hunk 8 above)
Comment (bluca) [reply src/pcrlock/pcrlock.c]: that sounds fine

File: src/pcrlock/pcrlock.c [hunk 9]
```diff
@@ -2771,7 +2771,7 @@ static int verb_lock_raw(int argc, char *argv[], void *userdata) {
 
         r = read_full_stream(f ?: stdin, &data, &size);
         if (r < 0)
-                return log_error_errno(r, "Failed to read data from stdin: %m");
+                return log_error_errno(r, "Failed to read data from %s: %m", f ? argv[1] : "stdin");
```
Comment (poettering) [inline src/pcrlock/pcrlock.c]: I'd prefer if we'd normalize this up top, i.e. change the `if (argc >= 2)` block above to something like this:

```c
const char *fname;
…
if (argc >= 2) {
        fname = argv[1];
        f = fopen(fname, "re");
        if (!f)
                return …
} else 
        fname = "<stdin>";
```

and then use `fname` systematically in the code below. I think that's much nicer since it only does the conditioning once, and makes it easier to not fuck this up again, if we add more log messages later.

**Comment by aplanas** [comment]
@keszybz  I changed the implementation, reading now 64k blocks to calculate the hash.

File: src/basic/fileio.c (hunk 7 above)
Comment (aplanas) [reply src/basic/fileio.c]: Should be done

File: src/pcrlock/pcrlock.c [hunk 10]
```diff
@@ -2691,6 +2691,103 @@ static int make_pcrlock_record(
...
+
+        *md = mfree(*md);
+}
+
+static int make_pcrlock_record_from_stream(
+                uint32_t pcr,
+                FILE *f,
+                JsonVariant **ret_record) {
+        _cleanup_(json_variant_unrefp) JsonVariant *digests = NULL;
+        _cleanup_(evp_md_ctx_free_all) EVP_MD_CTX **mdctx = NULL;
```
Comment (Vogtinator) [inline src/pcrlock/pcrlock.c]: Could be stored on the stack + `static void evp_md_ctx_free_all(EVP_MD_CTX *(*md)[TPM2_N_HASH_ALGORITHMS])`

Comment (aplanas) [reply src/pcrlock/pcrlock.c]: In that case the size would not be known, and inside the `evp_md_ctx_free_all` I would need to iter until `TPM2_N_HASH_ALGORITHMS`.  I was not able to use `sizeof()` because array size is lost in C function arguments.  Somehow I found this ugly.

Comment (Vogtinator) [reply src/pcrlock/pcrlock.c]: > In that case the size would not be known

If you use `static void evp_md_ctx_free_all(EVP_MD_CTX *(*md)[TPM2_N_HASH_ALGORITHMS])`, it is known and you can do the usual `sizeof(*md)/sizeof(**md)` dance. The compiler will also warn resp. error out if the array in the function parameter has the wrong size.

Comment (aplanas) [reply src/pcrlock/pcrlock.c]: Very cool. Done!

File: src/pcrlock/pcrlock.c [hunk 11]
```diff
@@ -2691,6 +2691,93 @@ static int make_pcrlock_record(
...
+static void evp_md_ctx_free_all(EVP_MD_CTX *(*md)[TPM2_N_HASH_ALGORITHMS]) {
+        for (size_t i = 0; i < sizeof(*md) / sizeof(**md); i++)
+                if ((*md)[i])
+                        EVP_MD_CTX_free((*md)[i]);
+}
+
+static int make_pcrlock_record_from_stream(
+                uint32_t pcr,
+                FILE *f,
+                JsonVariant **ret_record) {
```
Comment (bluca) [inline src/pcrlock/pcrlock.c]: empty line after open bracket when parameters are broken out

File: src/pcrlock/pcrlock.c [hunk 12]
```diff
@@ -2691,6 +2691,93 @@ static int make_pcrlock_record(
         return 0;
 }
 
+static void evp_md_ctx_free_all(EVP_MD_CTX *(*md)[TPM2_N_HASH_ALGORITHMS]) {
+        for (size_t i = 0; i < sizeof(*md) / sizeof(**md); i++)
```
Comment (bluca) [inline src/pcrlock/pcrlock.c]: assert(md)

File: src/pcrlock/pcrlock.c [hunk 13]
```diff
@@ -2691,6 +2691,93 @@ static int make_pcrlock_record(
...
+
+        for (size_t i = 0; i < TPM2_N_HASH_ALGORITHMS; i++) {
+                _cleanup_free_ unsigned char *hash = NULL;
+                const char *a;
+                int hash_ssize;
+                unsigned hash_usize;
+
+                assert_se(a = tpm2_hash_alg_to_string(tpm2_hash_algorithms[i]));
+                hash_ssize = EVP_MD_CTX_size(mdctx[i]);
+                assert_se(hash_ssize > 0);
```
Comment (bluca) [inline src/pcrlock/pcrlock.c]: this doesn't have side effects, so only assert(0

File: src/pcrlock/pcrlock.c (hunk 11 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: done

File: src/pcrlock/pcrlock.c (hunk 12 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: yes, done

File: src/pcrlock/pcrlock.c (hunk 13 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: I changed he one from `make_pcrlock_record()` too.

File: src/pcrlock/pcrlock.c [hunk 14]
```diff
@@ -2691,6 +2691,95 @@ static int make_pcrlock_record(
...
+                        EVP_MD_CTX_free((*md)[i]);
+}
+
+static int make_pcrlock_record_from_stream(
+                uint32_t pcr,
+                FILE *f,
+                JsonVariant **ret_record) {
+
+        _cleanup_(json_variant_unrefp) JsonVariant *digests = NULL;
+        _cleanup_(evp_md_ctx_free_all) EVP_MD_CTX *mdctx[TPM2_N_HASH_ALGORITHMS] = { NULL };
```
Comment (poettering) [inline src/pcrlock/pcrlock.c]: drop the `NULL`. In our codebase you can just write `{}` here. It's a GNU extension we happily use.

File: src/pcrlock/pcrlock.c [hunk 15]
```diff
@@ -2691,6 +2691,95 @@ static int make_pcrlock_record(
...
+                n = fread(buffer, 1, sizeof(buffer), f);
+                if (ferror(f))
+                        return log_error_errno(SYNTHETIC_ERRNO(ENOTRECOVERABLE), "Failed to read file: %m");
+                if (n == 0 && feof(f))
+                        break;
+
+                for (size_t i = 0; i < TPM2_N_HASH_ALGORITHMS; i++) {
+                        if (EVP_DigestUpdate(mdctx[i], buffer, n) != 1)
+                                return log_error_errno(SYNTHETIC_ERRNO(ENOTRECOVERABLE), "Unable to hash data.");
+                }
```
Comment (poettering) [inline src/pcrlock/pcrlock.c]: drop the {}, they are unnecessary.

**Comment by poettering** [comment]
lgtm, just two minor tweaks

File: src/pcrlock/pcrlock.c (hunk 14 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: I see. Done!

File: src/pcrlock/pcrlock.c (hunk 15 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: Done

File: src/pcrlock/pcrlock.c [hunk 16]
```diff
@@ -2769,17 +2855,13 @@ static int verb_lock_raw(int argc, char *argv[], void *userdata) {
...
-                return log_error_errno(r, "Failed to read data from stdin: %m");
-
         for (uint32_t i = 0; i < TPM2_PCRS_MAX; i++) {
                 _cleanup_(json_variant_unrefp) JsonVariant *record = NULL;
 
                 if (!FLAGS_SET(arg_pcr_mask, UINT32_C(1) << i))
                         continue;
 
-                r = make_pcrlock_record(i, data, size, &record);
+                r = make_pcrlock_record_from_stream(i, f ?: stdin, &record);
```
Comment (qhill) [inline src/pcrlock/pcrlock.c]: Can this really be done in a loop? Surely the stream needs to be rewound (not going to work for stdin) if multiple PCRs are specified or this need to enforce that only a single PCR is specified.

Comment (aplanas) [reply src/pcrlock/pcrlock.c]: the code read a buffer and update the different digests with the content of the buffer: this avoid re-reading the same content for every hash, and doing a seek(0) (that as you say cannot be applied for stdin)

Comment (qhill) [reply src/pcrlock/pcrlock.c]: But isn't the digest re-calculated from the stream for each PCR?  Or the PCR loop should be moved to make_pcrlock_record_from_stream (returning the record array rather than a single record)? The initrd case is obviously fine as there is only a single PCR involved.

Comment (qhill) [reply src/pcrlock/pcrlock.c]: Or alternatively return the digest rather than the record and then take this call outside the loop and build the record in the caller.

Comment (aplanas) [reply src/pcrlock/pcrlock.c]: I am not sure that I follow you.

The loop is about hashes algorithms, not PCRs.  The output should be the hash of the asset (file) for each algorithm.

If there are multiple PCRs, those will share the same digest and the JSON output will contain something like this:

```json
{
  "records": [
    {"pcr": 1, "digests": [ <HASHES> ]},
    {"pcr": 2, "digests": [ <SAME HASHES> ]}
  ]
}
```

What it is stored is the value of the hash that will be used to extend this PCR, not the extended value.

Comment (poettering) [reply src/pcrlock/pcrlock.c]: @qhill is right: there *is* a loop around PCRs.

Comment (poettering) [reply src/pcrlock/pcrlock.c]: in verb_lock_raw() we iterate through arg_pcr_mask...

in verb_lock_kernel_initrd() we only do this for a single PCR, hence there we are fine.

Comment (poettering) [reply src/pcrlock/pcrlock.c]: hence, please change make_pcrlock_record_from_stream() to take a pcr mask, not a single pcr index, and things should be good.

Comment (aplanas) [reply src/pcrlock/pcrlock.c]: oh I think that I get it now, is the 2776 loop!

Comment (poettering) [reply src/pcrlock/pcrlock.c]: (and please don't try to rewind the stream. that'd suck, since the tool wouldn#t work on pipes anymore, and would mean we do the same work over and over again)

Comment (aplanas) [reply src/pcrlock/pcrlock.c]: @qhill sorry for the delay. I think that I addressed the iteration over the PCRs issue.  As recommended by @poettering I used a `pcr_mask` parameter.

@qhill thanks a lot for pointing this bug! Can you check if this change makes sense?

Comment (qhill) [reply src/pcrlock/pcrlock.c]: No problem.  This looks correct now.

File: src/pcrlock/pcrlock.c [hunk 17]
```diff
@@ -2708,6 +2708,105 @@ static int make_pcrlock_record(
...
+                        return log_oom();
+
+                if (EVP_DigestInit_ex(mdctx[i], md, NULL) != 1)
+                        return log_error_errno(SYNTHETIC_ERRNO(ENOTRECOVERABLE),
+                                               "Failed to allocate message digest for %s.", a);
+        }
+
+        for (;;) {
+                uint8_t buffer[64*1024];
+                size_t n = 0;
```
Comment (keszybz) [inline src/pcrlock/pcrlock.c]: Unnecessary initialization.

File: src/pcrlock/pcrlock.c [hunk 18]
```diff
@@ -2708,6 +2708,105 @@ static int make_pcrlock_record(
...
+
+        for (size_t i = 0; i < TPM2_N_HASH_ALGORITHMS; i++) {
+                _cleanup_free_ unsigned char *hash = NULL;
+                const char *a;
+                int hash_ssize;
+                unsigned hash_usize;
+
+                assert_se(a = tpm2_hash_alg_to_string(tpm2_hash_algorithms[i]));
+                hash_ssize = EVP_MD_CTX_size(mdctx[i]);
+                assert(hash_ssize > 0);
```
Comment (keszybz) [inline src/pcrlock/pcrlock.c]: Maybe `assert(hash_ssize > 0 && hash_size <= EVP_MAX_MD_SIZE)`?

File: src/pcrlock/pcrlock.c [hunk 19]
```diff
@@ -2708,6 +2708,105 @@ static int make_pcrlock_record(
...
+                hash_usize = hash_ssize;
+
+                hash = malloc(hash_usize);
```
Comment (keszybz) [inline src/pcrlock/pcrlock.c]: Hmm, it seems a bit silly to allocate the 64kb buffer on the stack, and then the 8 byte buffer here via malloc. Why not just have
```C
unsigned char hash[hash_size];
```
?

File: src/pcrlock/pcrlock.c [hunk 20]
```diff
@@ -2708,6 +2708,105 @@ static int make_pcrlock_record(
         return 0;
 }
 
+static void evp_md_ctx_free_all(EVP_MD_CTX *(*md)[TPM2_N_HASH_ALGORITHMS]) {
+        assert(md);
+        for (size_t i = 0; i < sizeof(*md) / sizeof(**md); i++)
+                if ((*md)[i])
+                        EVP_MD_CTX_free((*md)[i]);
```
Comment (keszybz) [inline src/pcrlock/pcrlock.c]: What about
```C
        FOREACH_ARRAY(alg, *md, TPM2_N_HASH_ALGORITHMS)
                if (*alg)
                        EVP_MD_CTX_free(*alg);
```
?

File: src/pcrlock/pcrlock.c [hunk 21]
```diff
@@ -2708,6 +2708,105 @@ static int make_pcrlock_record(
...
+                assert_se(a = tpm2_hash_alg_to_string(tpm2_hash_algorithms[i]));
+                assert_se(md = EVP_get_digestbyname(a));
+
+                mdctx[i] = EVP_MD_CTX_new();
+                if (!mdctx[i])
+                        return log_oom();
+
+                if (EVP_DigestInit_ex(mdctx[i], md, NULL) != 1)
+                        return log_error_errno(SYNTHETIC_ERRNO(ENOTRECOVERABLE),
+                                               "Failed to allocate message digest for %s.", a);
```
Comment (keszybz) [inline src/pcrlock/pcrlock.c]: allocate → initialize

**Review by keszybz — CHANGES_REQUESTED** [review]
Looks almost ready. Some tweaks needed.

File: src/pcrlock/pcrlock.c (hunk 19 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: should be `unsigned char hash[EVP_MAX_MD_SIZE]`, or can C allocate in the stack a variable amount depending on the iteration?

Comment (keszybz) [reply src/pcrlock/pcrlock.c]: Yes, it can.

File: src/pcrlock/pcrlock.c (hunk 17 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: Done

File: src/pcrlock/pcrlock.c (hunk 18 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: Done

File: src/pcrlock/pcrlock.c (hunk 19 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: Done, but using the EVP_MAX_MD_SIZE, will change if advisable

File: src/pcrlock/pcrlock.c (hunk 20 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: Ah yes. Done.

File: src/pcrlock/pcrlock.c (hunk 21 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: changed

**Comment by keszybz** [comment]
LGTM.

File: src/pcrlock/pcrlock.c (hunk 19 above)
Comment (aplanas) [reply src/pcrlock/pcrlock.c]: Done.
