### PR TITLE
cryptsetup: fall back to traditional unlocking if any TPM2 operation fails

### LINKED ISSUE #22870: systemd-cryptsetup does not ask for password if any TPM2 operation fails with ENOTRECOVERABLE
**systemd version the issue has been seen with**
 > v250

**Used distribution**
 > openSUSE Tumbleweed

**Linux kernel version used** (`uname -a`)

 > `Linux localhost.localdomain 5.16.15-1-default #1 SMP PREEMPT Wed Mar 16 23:33:05 UTC 2022 (d8f0e40) x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Be able to boot the system by entering a text password if the TPM is cleared.

**Unexpected behaviour you saw**
 > Unable to boot.

**Steps to reproduce the problem**
 > 1. Example FS Layout (`cryptsetup luksFormat -y -v --type luks2 /dev/vda3`). 
```
dev@localhost:~> lsblk
NAME          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
sr0            11:0    1 912.9M  0 rom   
vda           253:0    0    20G  0 disk  
├─vda1        253:1    0   512M  0 part  /boot/efi
├─vda2        253:2    0     2G  0 part  /boot
└─vda3        253:3    0  17.5G  0 part  
  └─cr-auto-1 254:0    0  17.5G  0 crypt /var
                                         /srv
                                         /root
                                         /home
                                         /opt
                                         /usr/local
                                         /
```
 > 2. `systemd-cryptenroll --tpm2-device=auto /dev/vda3`
 > 3. Add `tpm2-device=auto` to cr-auto-1 in /etc/crypttab
 > 4. Clear TPM SRK (run `tpm2_clear`)
 > 5. Reboot.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
sh-4.4# systemctl status "systemd-cryptsetup@cr\x2dauto\x2d1.service"
× systemd-cryptsetup@cr\x2dauto\x2d1.service - Cryptography Setup for cr-auto-1
     Loaded: loaded (/etc/crypttab; generated)
     Active: failed (Result: exit-code) since Thu 2022-03-24 08:01:35 UTC; 46min ago
       Docs: man:crypttab(5)
             man:systemd-cryptsetup-generator(8)
             man:systemd-cryptsetup@.service(8)
    Process: 404 ExecStart=/usr/lib/systemd/systemd-cryptsetup attach cr-auto-1 /dev/disk/by-uuid/7bb5cda8-0a95-42ef-b763-7386c5c72e49 none x-initrd.attach,tpm2-device=auto (code=exited, status=1/FAILURE)
   Main PID: 404 (code=exited, status=1/FAILURE)

Mar 24 08:01:35 localhost systemd[1]: Starting Cryptography Setup for cr-auto-1...
Mar 24 08:01:35 localhost systemd-cryptsetup[404]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/7bb5cda8-0a95-42ef-b763-7386c5c72e49.
Mar 24 08:01:35 localhost systemd-cryptsetup[404]: Automatically discovered security TPM2 token unlocks volume.
Mar 24 08:01:35 localhost systemd-cryptsetup[404]: WARNING:esys:src/tss2-esys/api/Esys_Load.c:324:Esys_Load_Finish() Received TPM Error
Mar 24 08:01:35 localhost systemd-cryptsetup[404]: ERROR:esys:src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x00000921)
Mar 24 08:01:35 localhost systemd-cryptsetup[404]: Failed to load HMAC key in TPM: tpm:warn(2.0): authorizations for objects subject to DA protection are not allowed at this time because the TPM is in DA lockout mode
Mar 24 08:01:35 localhost systemd[1]: systemd-cryptsetup@cr\x2dauto\x2d1.service: Main process exited, code=exited, status=1/FAILURE
Mar 24 08:01:35 localhost systemd[1]: systemd-cryptsetup@cr\x2dauto\x2d1.service: Failed with result 'exit-code'.
Mar 24 08:01:35 localhost systemd[1]: Failed to start Cryptography Setup for cr-auto-1.
```

This happens in the `tpm2_unseal` method:

https://github.com/systemd/systemd/blob/e5531be27b034a7f4c517a0f76cbcbabe63c960e/src/shared/tpm2-util.c#L1132-L1135

Which is called from:

https://github.com/systemd/systemd/blob/e5531be27b034a7f4c517a0f76cbcbabe63c960e/src/cryptsetup/cryptsetup.c#L1328-L1338

Then ends here:

https://github.com/systemd/systemd/blob/e5531be27b034a7f4c517a0f76cbcbabe63c960e/src/cryptsetup/cryptsetup.c#L1906-L1909

Is the expected behavior not to continue with the boot process (and not prompt for password) if any of the TPM2 operations return ENOTRECOVERABLE?

### PR DESCRIPTION
**Pull request by aafeijoo-suse**
If any TPM2 operation fails, the boot process should continue and
prompt for a text password (if configured to do so).

Fixes #22870

### CODE REVIEW

File: src/cryptsetup/cryptsetup.c [hunk 1]
```diff
@@ -1322,8 +1322,11 @@ static int attach_luks_or_plain_or_bitlk_by_tpm2(
                                 return log_error_errno(SYNTHETIC_ERRNO(EAGAIN), "TPM2 PIN unlock failed, falling back to traditional unlocking.");
                         if (ERRNO_IS_NOT_SUPPORTED(r)) /* TPM2 support not compiled in? */
                                 return log_debug_errno(SYNTHETIC_ERRNO(EAGAIN), "TPM2 support not available, falling back to traditional unlocking.");
-                        if (r != -EAGAIN) /* EAGAIN means: no tpm2 chip found */
-                                return r;
+                        /* EAGAIN means: no tpm2 chip found */
+                        if (r != -EAGAIN) {
```
Comment (bluca) [inline src/cryptsetup/cryptsetup.c:1326]: no braces around single-line if statements

File: src/cryptsetup/cryptsetup.c [hunk 2]
```diff
@@ -1322,8 +1322,11 @@ static int attach_luks_or_plain_or_bitlk_by_tpm2(
...
+                                return log_debug_errno(SYNTHETIC_ERRNO(EAGAIN),
+                                                       "TPM2 operation failed, falling back to traditional unlocking.");
```
Comment (poettering) [inline src/cryptsetup/cryptsetup.c]: so this should definitely log the original error code here, and there should be an explicit comment that we mangle error codes here. i.e. something like this:

```c
log_debug_errno(r, TPM2 operation failed, falling back to traditional unlocking: %m");
return -EAGAIN; /* Mangle error code: lLet's make any form of TPM2 failure non-fatal. */
```

File: src/cryptsetup/cryptsetup.c (hunk 1 above)
Comment (aafeijoo-suse) [reply src/cryptsetup/cryptsetup.c:1326]: ok, sorry

File: src/cryptsetup/cryptsetup.c (hunk 2 above)
Comment (aafeijoo-suse) [reply src/cryptsetup/cryptsetup.c]: ok

**Comment by aafeijoo-suse** [comment]
Yes, the log looks different. Every time I follow the steps described in the issue (rebooting after just calling `tpm2_clear`) I always get `0x1df`. I don't have an answer why now I always get this, but when I opened the issue I was running more tpm2 commands to test what was going on. I've just created a new vm and I keep getting the same error code.

```
localhost:/home/dev # systemctl status "systemd-cryptsetup@cr\x2dauto\x2d1.service"
● systemd-cryptsetup@cr\x2dauto\x2d1.service - Cryptography Setup for cr-auto-1
     Loaded: loaded (/etc/crypttab; generated)
     Active: active (exited) since Wed 2022-03-30 12:30:34 CEST; 1min 6s ago
       Docs: man:crypttab(5)
             man:systemd-cryptsetup-generator(8)
             man:systemd-cryptsetup@.service(8)
   Main PID: 495 (code=exited, status=0/SUCCESS)
        CPU: 3.580s

Mar 30 12:30:27 localhost systemd[1]: Starting Cryptography Setup for cr-auto-1...
Mar 30 12:30:27 localhost systemd-cryptsetup[495]: WARNING:esys:src/tss2-esys/api/Esys_Load.c:324:Esys_Load_Finish() Received TPM Error
Mar 30 12:30:27 localhost systemd-cryptsetup[495]: ERROR:esys:src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x000001df)
Mar 30 12:30:27 localhost systemd-cryptsetup[495]: gotcha 0x1DF
Mar 30 12:30:27 localhost systemd-cryptsetup[495]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/274d583a->
Mar 30 12:30:27 localhost systemd-cryptsetup[495]: WARNING:esys:src/tss2-esys/api/Esys_Load.c:324:Esys_Load_Finish() Received TPM Error
Mar 30 12:30:27 localhost systemd-cryptsetup[495]: ERROR:esys:src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x000001df)
Mar 30 12:30:27 localhost systemd-cryptsetup[495]: gotcha 0x1DF
Mar 30 12:30:32 localhost systemd-cryptsetup[495]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/274d583a->
Mar 30 12:30:34 localhost systemd[1]: Finished Cryptography Setup for cr-auto-1.
```

That the TPM2_RC_LOCKOUT code was not handled in the issue report was my fault, the commit that added it was merged 15 days ago, so sorry for that.

File: src/cryptsetup/cryptsetup.c [hunk 3]
```diff
@@ -1322,8 +1322,11 @@ static int attach_luks_or_plain_or_bitlk_by_tpm2(
                                 return log_error_errno(SYNTHETIC_ERRNO(EAGAIN), "TPM2 PIN unlock failed, falling back to traditional unlocking.");
                         if (ERRNO_IS_NOT_SUPPORTED(r)) /* TPM2 support not compiled in? */
                                 return log_debug_errno(SYNTHETIC_ERRNO(EAGAIN), "TPM2 support not available, falling back to traditional unlocking.");
-                        if (r != -EAGAIN) /* EAGAIN means: no tpm2 chip found */
-                                return r;
+                        /* EAGAIN means: no tpm2 chip found */
+                        if (r != -EAGAIN) {
+                                log_debug_errno(r, "TPM2 operation failed, falling back to traditional unlocking: %m");
```
Comment (poettering) [inline src/cryptsetup/cryptsetup.c]: hmm, so I think we should upgrade this to `log_notice_errno()`. This log line carries information that the error logging done by acquire_tpm2_key() is not giving users, i.e. that we now fall back to traditional unlocking. Thus I think this should be above LOG_DEBUG log level, so that users can actually see this

File: src/cryptsetup/cryptsetup.c [hunk 4]
```diff
@@ -1334,8 +1337,10 @@ static int attach_luks_or_plain_or_bitlk_by_tpm2(
                         if (r == -ENOENT)
                                 return log_debug_errno(SYNTHETIC_ERRNO(EAGAIN),
                                                        "No TPM2 metadata enrolled in LUKS2 header or TPM2 support not available, falling back to traditional unlocking.");
-                        if (!IN_SET(r, -EOPNOTSUPP, -EAGAIN))
-                                return r;
+                        if (!IN_SET(r, -EOPNOTSUPP, -EAGAIN)) {
+                                log_debug_errno(r, "TPM2 operation failed, falling back to traditional unlocking: %m");
+                                return -EAGAIN; /* Mangle error code: let's make any form of TPM2 failure non-fatal. */
```
Comment (poettering) [inline src/cryptsetup/cryptsetup.c:1342]: same here

**Comment by poettering** [comment]
DA lockout happens if you try to unlock via TPM too frequently. means "dictionary attack lockout". Thus, my guess is that the actual error you saw was that integrity failure thing, but then you tried this a couple of times, at which time you tried it too frequently and got the DA lockout error instead, until some time passed when you soo the original integrity failure thing.

so this all looks as something one can expect.

So the patch looks good too, just some nitpicking about log level, see above.

File: src/cryptsetup/cryptsetup.c (hunk 3 above)
Comment (aafeijoo-suse) [reply src/cryptsetup/cryptsetup.c]: ok, done

File: src/cryptsetup/cryptsetup.c (hunk 4 above)
Comment (aafeijoo-suse) [reply src/cryptsetup/cryptsetup.c:1342]: ok
