### PR TITLE
mount-util: make path_is_network_fs_harder() gracefully handle errors

### LINKED ISSUE #35075: test_path_is_network_fs_harder fails in build environments
```
/* test_path_is_network_fs_harder */
src/test/test-mount-util.c:541: Assertion failed: expected "path_is_network_fs_harder("/dev")" to succeed but got the following error: Invalid argument
```

the test makes assumption about the running environment, but they are out of its control. There are no guarantees about any of the external directories or mount points or anything else in a build environment. This needs to be dropped or changed to work everywhere, under any condition.

https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=amd64&ver=257%7Erc1-2&stamp=1730977643&raw=0

Regression introduced by https://github.com/systemd/systemd/commit/d49d95df0a260aaca9a3fdd1e6ce535592a53bca

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for d49d95df0a260aaca9a3fdd1e6ce535592a53bca.
Replaces 9a032ec55a9820a0424309670fe551c99203e5f1.
Fixes #35075.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @bluca

File: src/shared/mount-util.c [hunk 1]
```diff
@@ -1856,13 +1856,20 @@ int path_is_network_fs_harder(const char *path) {
         _cleanup_free_ char *fstype = NULL, *options = NULL;
         int r, ret;
 
-        assert(path);
+        if (!path || !path_is_absolute(path))
```
Comment (YHNdnzj) [inline src/shared/mount-util.c]: Hmm? Why? Unexpected paths as input should really be caught as programming errors.

File: src/test/test-mount-util.c [hunk 2]
```diff
@@ -538,9 +538,44 @@ TEST(bind_mount_submounts) {
...
 TEST(path_is_network_fs_harder) {
-        ASSERT_OK_ZERO(path_is_network_fs_harder("/dev"));
-        ASSERT_OK_ZERO(path_is_network_fs_harder("/sys"));
-        ASSERT_OK_ZERO(path_is_network_fs_harder("/run"));
+        int r;
+
+        ASSERT_OK(path_is_network_fs_harder("/"));
+        ASSERT_OK(path_is_network_fs_harder("/dev"));
+        ASSERT_OK(path_is_network_fs_harder("/sys"));
+        ASSERT_OK(path_is_network_fs_harder("/run"));
```
Comment (bluca) [inline src/test/test-mount-util.c]: Please remove these assertions, access might be blocked in a myriad of ways or they might be something completely different and unexpected

File: src/test/test-mount-util.c [hunk 3]
```diff
@@ -538,9 +538,44 @@ TEST(bind_mount_submounts) {
...
+                      FORK_WAIT |
+                      FORK_REOPEN_LOG |
+                      FORK_LOG |
+                      FORK_NEW_MOUNTNS |
+                      FORK_MOUNTNS_SLAVE,
+                      NULL);
+        ASSERT_OK(r);
+
+        if (r == 0) {
+                ASSERT_OK(mount_nofollow_verbose(LOG_INFO, "tmpfs", t, "tmpfs", 0, NULL));
```
Comment (bluca) [inline src/test/test-mount-util.c:578]: check for permission errors and skip instead

Comment (yuwata) [reply src/test/test-mount-util.c:578]: In this case, we know the path is a temporary directory, and we have a capability to do that.

Comment (bluca) [reply src/test/test-mount-util.c:578]: Not necessarily, mounting could be blocked, for example via seccomp, or selinux, or many other ways. This is a unit test, it cannot assert on permissions, it needs to detect and gracefully skip on denials.

**Comment by yuwata** [comment]
@bluca @YHNdnzj Thank you for the review. PTAL.

File: src/test/test-mount-util.c (hunk 3 above)
Comment (bluca) [reply src/test/test-mount-util.c:578]: still unaddressed

Comment (yuwata) [reply src/test/test-mount-util.c:578]: Theoretically true, but if that happens, many test cases in this test will fail, not only here.
Let's address such theoretical concern all places if we really want to run the unit test on such spurious or too strict system.

File: src/shared/mount-util.c [hunk 4]
```diff
@@ -1858,11 +1858,20 @@ int path_is_network_fs_harder(const char *path) {
...
+
         ret = path_is_network_fs(path);
+        if (ret == -ENOENT)
+                return ret;
         if (ret > 0)
                 return true;
 
         r = path_get_mount_info(path, &fstype, &options);
+        if (r == -EINVAL) {
+                log_debug_errno(r, "Failed to find mount point '%s', maybe not a mount point, assuming not a network filesystem: %m", path);
```
Comment (poettering) [inline src/shared/mount-util.c]: so i think we should tweak path_get_mount_info():

1. it should get the mount id from the path via path_get_mnt_id()
2. then search through /proc/self/mountinfo via the mount id. libmount currently doesn't provide a direct api for this (i asked for it in https://githuhttps://github.com/util-linux/util-linux/issues/3275b.com/util-linux/util-linux/issues/3275), but we can just iterate through the table ourselves until we find an entry where mnt_fs_get_id() checks out. (a new api in libmount for this wouldn't algorithmically do anything better anyway, at least for now.)

benefit of this: this code would work on any inode, not just mount point inodes. any we can drop the restriction on absolute paths

**Comment by yuwata** [comment]
@poettering Thank you for the suggestion. Implemented. PTAL.

**Comment by poettering** [comment]
hmm, this could be tweaked further: i.e. open the path once and operate on that instead of opening it twice, once for path_is_network_fs() and once for path_get_mount_info()

**Comment by yuwata** [comment]
> hmm, this could be tweaked further: i.e. open the path once and operate on that instead of opening it twice, once for path_is_network_fs() and once for path_get_mount_info()

Done. The change is not small. Dropping the green label, PTAL.

File: src/shared/mount-util.c [hunk 5]
```diff
@@ -1808,63 +1808,81 @@ char* umount_and_unlink_and_free(char *p) {
...
+        _cleanup_close_ int fd = -EBADF;
+        int r;
 
-        assert(path);
+        assert(dir_fd >= 0 || dir_fd == AT_FDCWD);
 
-        ret = path_is_network_fs(path);
-        if (ret > 0)
-                return true;
+        fd = RET_NERRNO(xopenat(dir_fd, path, O_PATH | O_CLOEXEC | O_NOFOLLOW));
```
Comment (poettering) [inline src/shared/mount-util.c]: xopenat() is our call, hence does error handling our way. Hence please drop RET_NERRNO()

**Comment by poettering** [comment]
This is really nice now! Love it!

**Review by YHNdnzj — APPROVED** [review]
