### PR TITLE
hostname: fix off-by-one issue in gethostname()

### LINKED ISSUE #20309: hostname-setup maybe shouldn't leave the terminator byte alone
**systemd version the issue has been seen with**
 > all

**Used distribution**
 > NA

**Linux kernel version used** (`uname -a`)
 > NA

**CPU architecture issue was seen on**
 > ALL

**Expected behaviour you didn't see**
 > I think there maybe a problem in commit https://github.com/systemd/systemd/pull/17859/commits/39ede7cc377dcb057411c80509e5fde8901f20fb.
As i tested the gethostname syscall with the test.c listed as below.
```
testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest:~ # ./test
testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest:~ # echo $?
220
testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest:~ # cat test.c
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>

int main()
{
        char buf[65] = {};
        if (gethostname(buf, sizeof(buf) -1) < 0)
                return -errno;
        printf("The hostname is %s,the len of buf is %d", buf, sizeof(buf));
}
```
When i set the hostname to a 64 7-bit ASCII lower-case alphanumeric characters like:
```
testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
```
The test.c couldn't get the hostname.
And when i used gethostname(buf, sizeof(buf)) instead of gethostname(buf, sizeof(buf) -1). I can get the hostname.
Maybe we should revert the commit https://github.com/systemd/systemd/pull/17859/commits/39ede7cc377dcb057411c80509e5fde8901f20fb?

**Unexpected behaviour you saw**
 > The test.c couldn't get the hostname.

**Steps to reproduce the problem**
 > 1. Set the hostname to a 64 7-bit ASCII lower-case alphanumeric characters
     2. run the test.c.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

### LINKED ISSUE #20417: Unexpected `hostnamectl` behavior with a long transient hostname
**systemd version the issue has been seen with**
 > v249~rc2-1.fc35

**Used distribution**
 > Fedora Rawhide

**Linux kernel version used** (`uname -a`)

 > `5.13.0-0.rc7.20210625git44db63d1ad8d.55.fc35.x86_64`

`hostnamectl` can't change the transient hostname back once it has been set to a 64-character long one.

Initial state:
```
# hostnamectl
   Static hostname: n/a                                                      
Transient hostname: fedora
         Icon name: computer-vm
           Chassis: vm
        Machine ID: b294558f15804e699e066463ce33ec8b
           Boot ID: 724c2a5f24c04e28a0297e23b85bfa9f
    Virtualization: kvm
  Operating System: Fedora 35 (Rawhide Prerelease)                           
       CPE OS Name: cpe:/o:fedoraproject:fedora:35
            Kernel: Linux 5.13.0-0.rc7.20210625git44db63d1ad8d.55.fc35.x86_64
      Architecture: x86-64
   Hardware Vendor: Red Hat
    Hardware Model: OpenStack Compute
```

Set a 64-character long hostname:
```
# hostnamectl hostname xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.x
Could not set transient hostname: Failed to set hostname: File name too long
# hostnamectl
 Static hostname: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.x
       Icon name: computer-vm
         Chassis: vm
      Machine ID: b294558f15804e699e066463ce33ec8b
         Boot ID: 724c2a5f24c04e28a0297e23b85bfa9f
  Virtualization: kvm
Operating System: Fedora 35 (Rawhide Prerelease)                                  
     CPE OS Name: cpe:/o:fedoraproject:fedora:35
          Kernel: Linux 5.13.0-0.rc7.20210625git44db63d1ad8d.55.fc35.x86_64
    Architecture: x86-64
 Hardware Vendor: Red Hat
  Hardware Model: OpenStack Compute
```

Try to change it back to something shorter:
```
# hostnamectl hostname localhost
Could not set static hostname: Failed to set hostname: File name too long
# hostnamectl
   Static hostname: localhost
Transient hostname: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.x
         Icon name: computer-vm
           Chassis: vm
        Machine ID: b294558f15804e699e066463ce33ec8b
           Boot ID: 724c2a5f24c04e28a0297e23b85bfa9f
    Virtualization: kvm
  Operating System: Fedora 35 (Rawhide Prerelease)                                  
       CPE OS Name: cpe:/o:fedoraproject:fedora:35
            Kernel: Linux 5.13.0-0.rc7.20210625git44db63d1ad8d.55.fc35.x86_64
      Architecture: x86-64
   Hardware Vendor: Red Hat
    Hardware Model: OpenStack Compute
```

### PR DESCRIPTION
**Pull request by yuwata**
gethostname() returns null-terminated hostname.

Fixes #20309.
Fixes #20417.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @mrc0mmand.

File: src/shared/hostname-setup.c [hunk 1]
```diff
@@ -24,7 +24,7 @@ static int sethostname_idempotent_full(const char *s, bool really) {
```
Comment (keszybz) [inline src/shared/hostname-setup.c:25]: The initialization in the preceding line is not useful then…

**Review by keszybz — COMMENTED** [review]
Hmm, but did you see the comment on the commit that added this:
    
    gethostname(3) says it's unspecified whether the string is properly terminated
    when the hostname is too long. We created a buffer with one extra byte, and it
    seems the intent was to let that byte serve as terminator even if we get an
    unterminated string from gethostname().

The new behaviour needs an explanation.

**Comment by mrc0mmand** [comment]
I can confirm the patch works, thanks! I'll skip setting the green flag given the comments from others, though.

**Comment by floppym** [comment]
If gethostname() could possibly fail to null-terminate the string, maybe buf should actually be `HOST_NAME_MAX + 2` bytes long, and you should pass `HOST_NAME_MAX + 1` as the length parameter.

**Comment by poettering** [comment]
well uname() sizes the array as 65 (i.e. HOST_NAME_MAX+1) so we should be good on that front.

And in fact, maybe we should never use gethostname() and always use uname() (like we do elsewhere), since it avoids these pitfalls...

**Comment by poettering** [comment]
note that according to the gethostname() man page the glibc call will intrenally call uname() anyway. So we might just go for that right away and avoid the fuss

File: src/shared/hostname-setup.c [hunk 2]
```diff
@@ -46,7 +46,7 @@ bool get_hostname_filtered(char ret[static HOST_NAME_MAX + 1]) {
 
         /* Returns true if we got a good hostname, false otherwise. */
 
-        if (gethostname(buf, sizeof(buf) - 1) < 0)
```
Comment (poettering) [inline src/shared/hostname-setup.c:49]: i wonder why we have get_hostname_filtered() at all, if we have gethostname_strict() already? @keszybz?

**Comment by yuwata** [comment]
Thank you for comments. I will update soon.

**Comment by yuwata** [comment]
Updated. PTAL.

**Comment by bluca** [comment]
looks related:

```
 475/1232 test-hostname-setup                     FAIL     0.32 s (exit status 1)

--- command ---
19:05:25 PATH='/home/runner/work/systemd/systemd/build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin' SYSTEMD_KBD_MODEL_MAP='/home/runner/work/systemd/systemd/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/home/runner/work/systemd/systemd/src/locale/language-fallback-map' /home/runner/work/systemd/systemd/build/test-hostname-setup
--- stderr ---
Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
Found container virtualization none.
Hostname was already set to <fv-az269-277>.

=================================================================
==26023==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 13 byte(s) in 1 object(s) allocated from:
    #0 0x47f6c4 in strdup (/home/runner/work/systemd/systemd/build/test-hostname-setup+0x47f6c4)
    #1 0x7f2242331a0b in gethostname_full /home/runner/work/systemd/systemd/build/../src/basic/hostname-util.c:67:23
    #2 0x7f224215de9c in sethostname_idempotent_full /home/runner/work/systemd/systemd/build/../src/shared/hostname-setup.c:28:13
    #3 0x7f224215efe9 in hostname_setup /home/runner/work/systemd/systemd/build/../src/shared/hostname-setup.c:213:13
    #4 0x4bcc1a in test_hostname_setup /home/runner/work/systemd/systemd/build/../src/test/test-hostname-setup.c:62:9
    #5 0x4bc1f7 in main /home/runner/work/systemd/systemd/build/../src/test/test-hostname-setup.c:69:9
    #6 0x7f22417ad0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: 13 byte(s) leaked in 1 allocation(s).
```

File: src/shared/hostname-setup.c (hunk 2 above)
Comment (yuwata) [reply src/shared/hostname-setup.c:49]: It allows "localhost" or friends. Now `get_hostname_filtered()` is replaced with `gethostname_full()`.

**Review by mrc0mmand — APPROVED** [review]
Tested the latest build locally and it still seems to DTRT.

File: src/basic/hostname-util.c [hunk 3]
```diff
@@ -36,67 +36,62 @@ char* get_default_hostname(void) {
...
 
-        k = strdup(u.nodename);
-        if (!k)
-                return -ENOMEM;
+        return s;
+}
 
-        *ret = k;
-        return 0;
+int gethostname_strict(char **ret) {
```
Comment (poettering) [inline src/basic/hostname-util.c]: make static inline?

File: src/basic/hostname-util.c [hunk 4]
```diff
@@ -36,67 +36,62 @@ char* get_default_hostname(void) {
...
 
-int gethostname_strict(char **ret) {
-        struct utsname u;
-        char *k;
+        *ret = TAKE_PTR(buf);
+        return 0;
+}
 
-        /* This call will rather fail than make up a name. It will not return "localhost" either. */
+char* gethostname_malloc(void) {
```
Comment (poettering) [inline src/basic/hostname-util.c]: move to header and make static inline?

File: src/basic/hostname-util.c [hunk 5]
```diff
@@ -36,67 +36,62 @@ char* get_default_hostname(void) {
...
+                return NULL;
 
-        if (isempty(u.nodename))
-                return -ENXIO;
+        return s;
+}
 
-        if (streq(u.nodename, "(none)"))
-                return -ENXIO;
+char* gethostname_short_malloc(void) {
```
Comment (poettering) [inline src/basic/hostname-util.c]: ditto

**Comment by poettering** [comment]
lgtm

**Comment by yuwata** [comment]
@mrc0mmand Thank you for testing, and @poettering thank you for the comment. Now, the three variants of `gethostname()` are made inline. Upgrading the green label.
