### PR TITLE
user-sessions: do not remove /etc/nologin

### LINKED ISSUE #26965: systemd-user-sessions deletes /etc/nologin
### systemd version the issue has been seen with

252

### Used distribution

Debian

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

We use pam_nologin to deny user access to systems whilst we work on them. Recently, whilst doing maintenance on a server, I put a helpful message into /etc/nologin. After a reboot, I was surprised to discover that this file had been deleted by something which led to users gaining access before we were ready.

Using the Linux auditd I tracked down the file deletion to systemd-user-sessions.service. Reading the man page for that service, it only mentions using the /run/nologin file.  Checking the source code for src/user-sessions/user-sessions.c though I see in the start method:

                r = unlink_or_warn("/run/nologin");
                k = unlink_or_warn("/etc/nologin");

There doesn't seem to be any good reason given for this service to also delete the file in /etc.  This leaves me with no easy way to set my own nologin file that will be preserved over a reboot. I realise that I could just remove the service completely but this doesn't seem like appropriate behaviour, I'm sure it will surprise other sysadmins who expect to be able to rely on pam_nologin to keep systems secure.

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by keszybz**
pam_nologin looks for /etc/nologin and /run/nologin. user-sessions creates (and removes) /run/nologin, but also removes /etc/nologin. (This behaviour is unchanged since the introduction of the binary in e92787416c691c3f34f47349e5eae3fa68eae856.)

/etc/nologin can be used by administrator to disable user logins, e.g. for extended maintanance. There is no good reason for us to remove it. The goal of user-sessions is not to allow users to log in at any cost, but just to prohibit logins during shutdown and startup. Let's leave /etc/nologin for the administrator.

The makes the code match the man page.

Fixes #26965.

### CODE REVIEW

File: src/user-sessions/user-sessions.c [hunk 1]
```diff
@@ -31,10 +31,8 @@ static int run(int argc, char *argv[]) {
 
         if (streq(argv[1], "start")) {
                 r = unlink_or_warn("/run/nologin");
-                k = unlink_or_warn("/etc/nologin");
                 if (r < 0)
                         return r;
-                return k;
```
Comment (YHNdnzj) [inline src/user-sessions/user-sessions.c:37]: We should return here, else it runs along and returns -EINVAL below.

```c
if (streq(...))
    return unlink_or_warn(...);
```

Comment (keszybz) [reply src/user-sessions/user-sessions.c:37]: Yikes.

**Comment by bluca** [comment]
This is technically a compat break, no? In theory someone could be relying on this behavior, eg create the file, so some stuff and then just reboot knowing it will be gone. Sounds be fine to do, but should be mentioned at the top of the news? (Can be done separately)

**Comment by keszybz** [comment]
Yes, I expect this to be mentioned in NEWS.

**Comment by poettering** [comment]
See my comments on:

https://github.com/systemd/systemd/issues/26965#issuecomment-1483809333

**Comment by poettering** [comment]
the "needs-discussion" I just added because I only did some initial research, and i don't wanted this to be hurried in before we now all the facts.

i mean, as it stands now the original issue should probably be addressed by just using /etc/nologin.txt, no?

**Comment by keszybz** [comment]
> i mean, as it stands now the original issue should probably be addressed by just using /etc/nologin.txt, no?

No, `/etc/nologin.txt` used by `/sbin/nologin`. It has no relevance for `pam_nologin`, right now. And as I wrote in https://github.com/systemd/systemd/issues/26965#issuecomment-1484760390, I don't think it should.

File: src/user-sessions/user-sessions.c [hunk 2]
```diff
@@ -29,14 +29,9 @@ static int run(int argc, char *argv[]) {
...
-        if (streq(argv[1], "start")) {
-                r = unlink_or_warn("/run/nologin");
-                k = unlink_or_warn("/etc/nologin");
-                if (r < 0)
-                        return r;
-                return k;
-
-        } else if (streq(argv[1], "stop"))
+        if (streq(argv[1], "start"))
+                return unlink_or_warn("/run/nologin");
```
Comment (poettering) [inline src/user-sessions/user-sessions.c:35]: Can you add a comment here, explaining this:

```
/* Traditionally, there was only /etc/nologin, and we managed that. Then, in PAM
$SOMEVERSION support for /run/nologin was added as alternative. 10y later we stopped 
managing /etc/nologin, leaving it for the administrator to manage. */
```

Also, please update the requirements list in README with the minimal PAM version we require now. Even if it's a super old one.

**Comment by poettering** [comment]
hmm, glibc's /usr/include/paths.h  defines _PATH_NOLOGIN pointing to /etc/nologin btw.

We might want add a brief comment about the fact we ignore that too somewhere. I think that macro is mostly a historical BSD thing. Deserves to be ignored, but a brief comment should be added nonetheless.

**Comment by poettering** [comment]
urks. shadow defines the /etc/nologin too, via NOLOGINS_FILE in login.defs. No idea what for. I hope we won#t lose compat with that.

**Comment by poettering** [comment]
so shadow apparently supports non-PAM builds where it checks that file itself. I guess we don't have to support that. so let's ignore that cruft.

File: src/user-sessions/user-sessions.c (hunk 2 above)
Comment (keszybz) [reply src/user-sessions/user-sessions.c:35]: I added a comment to create_shutdown_run_nologin_or_warn(), since that's where we create the file. And README already said PAM >= 1.1.2, which covers this. I amended the commit message.

**Review by YHNdnzj — APPROVED** [review]

**Comment by poettering** [comment]
looks good. but would prefer if such things that (even if only remotely) look like compat breakages would be committed along with their NEWS entry already.

**Comment by keszybz** [comment]
I'll write the NEWS entry when the time comes. I want to look over the commit list anyway, and it's just less work to write everything at once.
