### PR TITLE
Fixes & improvments for using homed-luks on 4k disks

### LINKED ISSUE #30393: Cannot login with user created using `--luks-sector-size=4096`
### systemd version the issue has been seen with

255-1

### Used distribution

Arch Linux

### Linux kernel version used

6.6.4-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-homed

### Expected behaviour you didn't see

Successful login from getty.

### Unexpected behaviour you saw

When logging it from getty, password was asked four times, but home was still not unlocked.

Full boot log with `systemd.log_level=debug`: [vm3.log](https://github.com/systemd/systemd/files/13623659/vm3.log)

### Steps to reproduce the problem

Create user with:
```
# homectl create test1 --storage=luks --luks-sector-size=4096
```

And then try to log in as `test1`.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Dec 09 09:33:31 archtestvm3 systemd-homed[350]: Sending to worker: {"luksSectorSize":4096,"userName":"test1","perMachine":[{"storage":"luks","matchMachineId":"418c71588d254bd99e170598e657c240"}],"disposition":"regular","lastChangeUSec":1702114399414059,"lastPasswordChangeUSec":1702114399414059,"privileged":{"hashedPassword":["$y$j9T$6ZVl2lxZz6RtRK7HV5U2H1$2wX6PZEoNYhTd26NYh4FYwwFpYDcDpUDKuYOB8/hWJA"]},"signature":[{"data":"2x07M1tGS0//vnaUmv7sBeDLsVARLIi4SCYXCeU7/4xm5sBc/Y3mfuXJ+GLN3vhYpjddI9i2tjRv9UHVSO+SBw==","key":"-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA7zKL9UrI6RWJYaQ4aw9AbuaivMVs2COEn3smZVP/z2s=\n-----END PUBLIC KEY-----\n"}],"binding":{"418c71588d254bd99e170598e657c240":{"imagePath":"/home/test1.home","partitionUuid":"8c118879-0164-4f49-b7ab-6b146d13bba2","luksUuid":"f18e4697-db98-4ce8-876e-2e3ce6b67c1a","fileSystemUuid":"bba71fbd-f086-4655-a0fb-2e580e82d0c9","luksCipher":"aes","luksCipherMode":"xts-plain64","luksVolumeKeySize":32,"fileSystemType":"btrfs","uid":60510,"gid":60510,"storage":"luks"}},"status":{"418c71588d254bd99e170598e657c240":{"rateLimitBeginUSec":1702114411845443,"rateLimitCount":1}},"secret":{}}
Dec 09 09:33:31 archtestvm3 systemd-homed[350]: Successfully forked off '(sd-homework)' as PID 515.
Dec 09 09:33:31 archtestvm3 systemd-homed[350]: test1: changing state inactive → activating-for-acquire
Dec 09 09:33:31 archtestvm3 systemd-journald[227]: Compressed data object 1101 -> 727 using ZSTD
Dec 09 09:33:31 archtestvm3 systemd-homework[515]: User record has no recovery keys, plaintext passwords not tested against it.
Dec 09 09:33:31 archtestvm3 systemd-homework[515]: None of the supplied plaintext passwords unlock the user record's hashed passwords.
Dec 09 09:33:31 archtestvm3 systemd-homed[350]: Got notify message lacking both ERRNO= and SYSTEMD_LUKS_LOCK_FD= field, ignoring.
Dec 09 09:33:31 archtestvm3 systemd-homed[350]: Worker reported error code ENOKEY.
Dec 09 09:33:31 archtestvm3 systemd-homed[350]: Activation failed: Required key not available
Dec 09 09:33:31 archtestvm3 systemd-homed[350]: Sent message type=error sender=n/a destination=:1.9 path=n/a interface=n/a member=n/a cookie=26 reply_cookie=3 signature=s error-name=org.freedesktop.home1.BadPassword error-message=Password for home test1 is incorrect or not sufficient for authentication.
Dec 09 09:33:31 archtestvm3 systemd-homed[350]: test1: changing state activating-for-acquire → inactive
```

### LINKED ISSUE #30394: `homectl create --image-path=` does not work on 4Kn drives
### systemd version the issue has been seen with

255-1

### Used distribution

Arch Linux

### Linux kernel version used

6.6.4-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-homed

### Expected behaviour you didn't see

A successfully created user in "inactive" state.

### Unexpected behaviour you saw

The created user is "absent".

```
# homectl                                          
NAME  UID   GID   STATE  REALNAME HOME        SHELL        
test1 60510 60510 absent test1    /home/test1 /usr/bin/bash

1 home areas listed.
```

### Steps to reproduce the problem

Have a drive with logical sector size of 4096 (in my case, it's [virtual disk in libvirt/qemu](https://wiki.archlinux.org/title/Libvirt#Advanced_Format_4K_native_disk)):
```
# lsblk -pt /dev/sdc
NAME     ALIGNMENT MIN-IO OPT-IO PHY-SEC LOG-SEC ROTA SCHED RQ-SIZE  RA WSAME
/dev/sdc         0   4096      0    4096    4096    1 none      256 128    0B
```

Create a user:
```
# homectl create test1 --storage=luks --image-path=/dev/sdc
```

Observe that the user is "absent" and try again with `--luks-sector-size=4096`:
```
# homectl create test1 --storage=luks --image-path=/dev/sdc --luks-sector-size=4096
```

Observe that nothing has changed.  :frowning_face: 

----

Full boot log with `systemd.log_level=debug`: [vm3-homectl-image-path.log](https://github.com/systemd/systemd/files/13623775/vm3-homectl-image-path.log)

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by scarlet-storm**
Mostly consists of fixes to 

- use the same sector_size as the fdisk context we are using, when converting between sectors returned by libfdisk to bytes. Fixes #30394 , Fixes #30393 
- Use the explicit sector size if specified in the home record when are probing the image file using libblkid. Fixes #30393 

Also contains some other improvements with using physical block devices.

- Automatically probe sector size of physical block device, if user does not pass luks-sector-size explicitly.
- Assign partitions to 1 MiB boundaries, as it is the standard practice followed by all tools, fdisk, gptfdisk, gnu parted etc.
- Avoid stacking of loop device on top of physical block device in home_create_luks as it leads to degradation of discard operations, and mkfs getting stuck.

### CODE REVIEW

File: src/home/homework-luks.c [hunk 1]
```diff
@@ -1,5 +1,6 @@
 /* SPDX-License-Identifier: LGPL-2.1-or-later */
 
+#include <libfdisk.h>
```
Comment (poettering) [inline src/home/homework-luks.c]: we so far don't include this directly but only via fdisk-util.h. no need to change that...

File: src/home/homework-luks.c [hunk 2]
```diff
@@ -1901,27 +1903,31 @@ static int make_partition_table(
         if (r < 0)
                 return log_error_errno(r, "Failed to place partition at first free partition index: %m");
 
+        // Use same sector size as the fdisk context when converting to bytes
```
Comment (poettering) [inline src/home/homework-luks.c]: coding style: in our tree we use `/* */` style coments for explanatory stuff, and `//` style comments for "fixme" style stuff. this here is explanatory, hence please change comment style.

(coding style is documented here: https://systemd.io/CODING_STYLE)

File: src/home/homework-luks.c [hunk 3]
```diff
@@ -1901,27 +1903,31 @@ static int make_partition_table(
...
+        fdisk_sector_size = fdisk_get_sector_size(c);
+        assert(fdisk_sector_size);
```
Comment (poettering) [inline src/home/homework-luks.c]: coding style: for arithmetic values we prefer explicit non-null comparisons. only for bools (and boolean-like values) and pointers we are fine with using C's "downgrade-to-bool" syntax.

or in other words:

`assert(fdisk_sector_size > 0);`

here please

File: src/home/homework-luks.c [hunk 4]
```diff
@@ -2743,14 +2750,16 @@ static int prepare_resize_partition(
                 if (fdisk_partition_has_start(p) <= 0 || fdisk_partition_has_size(p) <= 0 || fdisk_partition_has_end(p) <= 0)
                         return log_error_errno(SYNTHETIC_ERRNO(EINVAL), "Found partition without a size.");
 
-                if (fdisk_partition_get_start(p) == partition_offset / 512U &&
-                    fdisk_partition_get_size(p) == old_partition_size / 512U) {
+                fdisk_sector_size = fdisk_get_sector_size(c);
+                assert(fdisk_sector_size);
```
Comment (poettering) [inline src/home/homework-luks.c]: as above

File: src/home/homework-luks.c [hunk 5]
```diff
@@ -1866,6 +1867,7 @@ static int make_partition_table(
         _cleanup_free_ char *disk_uuid_as_string = NULL;
         uint64_t offset, size, first_lba, start, last_lba, end;
         sd_id128_t disk_uuid;
+        fdisk_sector_t fdisk_sector_size;
```
Comment (poettering) [inline src/home/homework-luks.c]: that's such a weird type. I think it would be better to just use uint64_t here.

and maybe drop the "fdisk" prefix, we don't name ther other fields we retrieve from libfdisk with such a prefix either

File: src/home/homework-luks.c [hunk 6]
```diff
@@ -2853,17 +2853,6 @@ static int apply_resize_partition(
...
-        if (!two_zero_lbas)
-                return log_oom();
-
-        /* libfdisk appears to get confused by the existing PMBR. Let's explicitly flush it out. */
-        n = pwrite(fd, two_zero_lbas, ssz * 2, 0);
-        if (n < 0)
-                return log_error_errno(errno, "Failed to wipe partition table: %m");
-        if ((size_t) n != ssz * 2)
-                return log_error_errno(SYNTHETIC_ERRNO(EIO), "Short write while wiping partition table.");
-
```
Comment (poettering) [inline src/home/homework-luks.c:2886]: why remove this? i added this explicitly because libfdisk got confused by the old partition table, and its pmbr.

File: src/home/homework-luks.c [hunk 7]
```diff
@@ -2780,6 +2780,7 @@ static int get_maximum_partition_size(
 
         _cleanup_(fdisk_unref_contextp) struct fdisk_context *c = NULL;
         uint64_t start_lba, start, last_lba, end;
+        fdisk_sector_t fdisk_sector_size;
```
Comment (poettering) [inline src/home/homework-luks.c]: as above, just use uint64_t and drop the fdisk prefix

File: src/home/homework-luks.c [hunk 8]
```diff
@@ -2316,9 +2317,17 @@ int home_create_luks(
                 log_info("Allocating image file completed.");
         }
 
+        if ( h->luks_sector_size == UINT64_MAX) {
```
Comment (poettering) [inline src/home/homework-luks.c]: spurious space

File: src/home/homework-luks.c [hunk 9]
```diff
@@ -2316,9 +2317,17 @@ int home_create_luks(
...
+                /* if sector size is not specified, select UINT32_MAX, i.e. auto-probe */
+                image_sector_size = UINT32_MAX;
+                /* Let cryptsetup decide if the sector size if not specified in home record */
+                luks_sector_size = 0;
+        } else {
+               luks_sector_size = image_sector_size = user_record_luks_sector_size(h);
+        }
```
Comment (poettering) [inline src/home/homework-luks.c:2376]: coding style: no {} around single line if blocks

Comment (poettering) [reply src/home/homework-luks.c:2376]: indetnation is off

File: src/home/homework-luks.c [hunk 10]
```diff
@@ -2316,9 +2317,17 @@ int home_create_luks(
                 log_info("Allocating image file completed.");
         }
 
+        if ( h->luks_sector_size == UINT64_MAX) {
+                /* if sector size is not specified, select UINT32_MAX, i.e. auto-probe */
+                image_sector_size = UINT32_MAX;
```
Comment (poettering) [inline src/home/homework-luks.c:2365]: man, this type confusion everywhere is confusing. libcryptsetup wants 32bit, libfdisk wants somathing opaque. I am pretty sure we should just use uint64_t everywhere and convert to the right types at the latest moment possible.

hence I think we should really use UINT64_MAX here for probing, and then inside of image_sector_size() map that to UINT32_MAX (and refuse any values > UINT32_MAX and < UINT64_MAX

Comment (poettering) [reply src/home/homework-luks.c:2365]: ah, christ, our own loop_device_make() already gets that wrong... grmbl. i guess it's fine then to leave that cleanup to another day

File: src/home/homework-luks.c [hunk 11]
```diff
@@ -1377,7 +1386,14 @@ int home_setup_luks(
...
 
-                r = luks_validate(setup->image_fd, user_record_user_name_and_realm(h), h->partition_uuid, &found_partition_uuid, &offset, &size);
+                r = luks_validate(
+                        setup->image_fd,
+                        user_record_user_name_and_realm(h),
+                        h->partition_uuid,
+                        h->luks_sector_size == UINT64_MAX ? UINT32_MAX : user_record_luks_sector_size(h), /* if sector size is not specified, select UINT32_MAX, i.e. auto-probe */
+                        &found_partition_uuid,
+                        &offset,
+                        &size);
```
Comment (poettering) [inline src/home/homework-luks.c]: we indent function parameters to twice the regular indentation, according to our coding style

File: src/home/homework-luks.c [hunk 12]
```diff
@@ -757,6 +765,7 @@ static int luks_validate(
         if ((uint64_t) size > UINT64_MAX / 512U)
                 return -EINVAL;
 
+        /* libblkid returns partitions size in count of 512-sectors */
```
Comment (poettering) [inline src/home/homework-luks.c]: maybe emphasize that this is *not* the native sector size

File: src/home/homework-luks.c [hunk 13]
```diff
@@ -2354,7 +2359,32 @@ int home_create_luks(
 
         log_info("Writing of partition table completed.");
 
-        r = loop_device_make(
+        if (fstat(setup->image_fd, &st) < 0)
+                return -errno;
+        /* Ensure we don't create a loop device over block device as it leads to huge overhead for discard operations
+         * if the device does not support discard_zeroes_data */
```
Comment (poettering) [inline src/home/homework-luks.c:2394]: i am not sure i get this. wouldn't the more correct fix to simply disable discard on the loopback device if the underlying device cannot do this?

File: src/home/homework-luks.c [hunk 14]
```diff
@@ -2354,7 +2359,32 @@ int home_create_luks(
...
+                if (setup->image_fd < 0)
+                        return setup->image_fd;
+                r = loop_device_open_from_path(
+                        partition_path,
+                        O_RDWR,
+                        LOCK_EX,
+                        &setup->loop);
+                if (r < 0) {
+                        return log_error_errno(r, "Failed to open newly written partition device: %s", partition_path);
+                }
```
Comment (poettering) [inline src/home/homework-luks.c]: coding style: no {} around single line if blocks

File: src/home/homework-luks.c [hunk 15]
```diff
@@ -2354,7 +2359,32 @@ int home_create_luks(
...
+                setup->image_fd = safe_close(setup->image_fd);
+                (void) wait_for_devlink(partition_path);
+                setup->image_fd = open_image_file(h, ip, &st);
+                if (setup->image_fd < 0)
+                        return setup->image_fd;
+                r = loop_device_open_from_path(
+                        partition_path,
+                        O_RDWR,
+                        LOCK_EX,
+                        &setup->loop);
```
Comment (poettering) [inline src/home/homework-luks.c]: coding style: please indent function param lists to double the usual indentation

**Comment by poettering** [comment]
hmm, i am tempted to say we should use 4k sectors everywhere by default, unless specified in the user record otherwiwse. (and of course the gpt partition table should use the native sector size if we are talking about raw block devices).

afaik there's now downside of using larger sector sizes on the luks and fs level, but it makes our images more portable...

**Comment by scarlet-storm** [comment]
> hmm, i am tempted to say we should use 4k sectors everywhere by default, unless specified in the user record otherwiwse. (and of course the gpt partition table should use the native sector size if we are talking about raw block devices).
> 
> afaik there's now downside of using larger sector sizes on the luks and fs level, but it makes our images more portable...

Hi, thanks for the review.
I was also thinking about using a 4k image size by default. Most of the filesystems use 4k sector size by default anyways even when the underlying sector size is 512. There should be downsides to using 4k by default for file based images.
The concerns  might be
- Small filesystems or lot of small files with sizes < 4k. xfs by default still uses a 512 default sector size, if the underlying image supports it and ext4 uses 512  sector size if filesystem < 2G iirc.
- With respect to backwards compatibility we will have to always probe image files we are opening assuming a sector size of 512 & 4k, as the image might have been created with an old version of systemd-homework. This should be fine to implement and not an issue.

Also my thoughts were that these functions can be rewritten to use an internal systemd-repart  library in the future. I think all the partition, luks & fs creation / resizing operations can be handled by the repart library. It will require creation of an repart api and add an additional dependency for homed

File: src/home/homework-luks.c (hunk 6 above)
Comment (scarlet-storm) [reply src/home/homework-luks.c:2886]: I did not face an issue with writing out the new partition table.  Also I was not able to understand the exact issue that the pmbr is causing from the earlier commit message. I'm not sure why fdisk wouldn't like the existing partition table.
Could you explain the issue in detail, and I will try reproducing it.

File: src/home/homework-luks.c (hunk 13 above)
Comment (scarlet-storm) [reply src/home/homework-luks.c:2394]: The problem is this
- loop device historical semantics dictates that when the device is discarded, it needs to return zero data on read. This can be implemented easily on a filesystem. since fallocate zero-range would return immediately & the holes are handled at the filesystem level to return zero data on read.
- For a raw block device, the feature (discard_zeroes_data) depends on the capabilities of the physical device that is exposed to the block device by the driver.

This means that to guarantee that the loop device stacked on a block device returns zero on discarded data, it needs to convert discarded range into write_zero on the block device.
https://github.com/torvalds/linux/blob/63676eefb7a026d04b51dcb7aaf54f358517a2ec/drivers/block/loop.c#L773
For example on a local nvme I see

cat /sys/class/block/nvme1n1/queue/write_zeroes_max_bytes
131072
cat /sys/class/block/nvme0n1/queue/discard_max_hw_bytes
2199023255040

This means maximum size of a write_zero operation can be 128KiB & maximum size of discard operation can be 2TiB. So discarding for example 1TB of data, which would be a single block device operation, gets split into 8.3 million block device operations when issued on top of loop device.
 So the issue is not with the block device supporting the feature, but loop device adding extra overhead since it's trying to add additional guarantees on the discarded data.

**Comment by GreyXor** [comment]
Hi @scarlet-storm 
I have a 4k ssd and I'm interested in this patch. Do you need any tests? or do we miss anything?

**Comment by scarlet-storm** [comment]
I will work on cleaning up some of the code style issues mentioned in this PR.
I think the other changes can be follow up patches.

**Comment by GreyXor** [comment]
Hi @scarlet-storm,
Just wanted to check in regarding the code style cleanup and the follow-up patches you mentioned. Did you had a chance to make any progress or if there’s anything I can do to help move things forward.
Thanks!

**Comment by GreyXor** [comment]
> I will work on cleaning up some of the code style issues mentioned in this PR. I think the other changes can be follow up patches.

Hello, gentle ping :) any news about it ? thank you

**Comment by scarlet-storm** [comment]
I have addressed the code style issues. For the open comments

- zeroing of PMBR, I don't understand why this is needed. Could you provide a simple example to reproduce this ? I did not face any issue with allowing fdisk to write out the partition table, without zeroing.
- Changing default sector size to 4k for file based images. I think this can be taken up as part of a future PR. As I mentioned earlier, I think ideally we could rewrite the image creation to use systemd-repart

File: src/home/homework-luks.c (hunk 6 above)
Comment (keszybz) [reply src/home/homework-luks.c:2886]: Yeah, I think that it should be fine to drop this, if current libfdisk works without it. Maybe it was a bug in an old version, maybe it was a misunderstanding. If the issue pops up again, we'll revert the removal.

File: src/home/homework-luks.c [hunk 16]
```diff
@@ -65,16 +65,16 @@
 #include "user-record.h"
 #include "user-util.h"
 
-/* Round down to the nearest 4K size. Given that newer hardware generally prefers 4K sectors, let's align our
- * partitions to that too. In the worst case we'll waste 3.5K per partition that way, but I think I can live
+/* Round down to the nearest 1 MiB size. Given that most tools generally align partitions to 1 MiB boundaries, let's align our
+ * partitions to that too. In the worst case we'll waste 1 MiB per partition that way, but I think I can live
```
Comment (keszybz) [inline src/home/homework-luks.c:70]: Why do you want to do this? The commit describes what is being done, but not really why. Doing something the same as others is not enough motivation, unless the difference is causing problems.

After those changes, the comment doesn't quite make sense. The sentence about wasting 4k bytes was partially a joke. If we're wasting 1MB, a better explanation is needed.

File: src/home/homework-luks.c [hunk 17]
```diff
@@ -695,6 +697,12 @@ static int luks_validate(
         if (r != 0)
                 return errno_or_else(ENOMEM);
 
+        /* Set probing sector size if explicitly specified */
+        if (sector_size != UINT32_MAX) {
+                r = sym_blkid_probe_set_sectorsize(b, sector_size);
+                if(r != 0)
```
Comment (keszybz) [inline src/home/homework-luks.c]: Missing space after `if`.

File: src/home/homework-luks.c [hunk 18]
```diff
@@ -2335,9 +2336,17 @@ int home_create_luks(
...
         }
 
+        if (h->luks_sector_size == UINT64_MAX) {
+                /* if sector size is not specified, select UINT32_MAX, i.e. auto-probe */
+                image_sector_size = UINT32_MAX;
+                /* Let cryptsetup decide if the sector size if not specified in home record */
+                luks_sector_size = 0;
+        } else {
+               luks_sector_size = image_sector_size = user_record_luks_sector_size(h);
+        }
```
Comment (keszybz) [inline src/home/homework-luks.c:2376]: Please drop {} here.

File: src/home/homework-luks.c (hunk 13 above)
Comment (keszybz) [reply src/home/homework-luks.c:2394]: Please put this comment in the commit message.

EDIT: this is not clear without context. I was refererring to the long comment made in the review thread, not the comment in the code.

File: src/home/homework-luks.c [hunk 19]
```diff
@@ -2373,24 +2377,48 @@ int home_create_luks(
...
+                                0,
+                                LOCK_EX,
+                                &setup->loop);
+                if (r < 0) {
+                        if (r == -ENOENT) { /* this means /dev/loop-control doesn't exist, i.e. we are in a container
+                                * or similar and loopback bock devices are not available, return a
+                                * recognizable error in this case. */
+                                log_error_errno(r, "Loopback block device support is not available on this system.");
+                                return -ENOLINK; /* Make recognizable */
+                        }
```
Comment (keszybz) [inline src/home/homework-luks.c]: This out `if (r < 0)` check is not necessary. Please dedent the check for `r == -ENONET` by one level.
And keep the block comment formatted as before, with `*` aligned.

File: src/home/homework-luks.c [hunk 20]
```diff
@@ -2362,7 +2362,13 @@ int home_create_luks(
                 /* Let cryptsetup decide if the sector size if not specified in home record */
                 luks_sector_size = 0;
         } else {
-               luks_sector_size = image_sector_size = user_record_luks_sector_size(h);
+                if (S_ISBLK(st.st_mode)) {
+                        /* for physical block devices always use the actual device logical
+                         *sector size. Else the partition will not be discoverable by kernel/udev. */
```
Comment (keszybz) [inline src/home/homework-luks.c]: `* For`
`* sector`

**Review by keszybz — COMMENTED** [review]
Those changes look generally reasonable, but I don't think I grok all the implications. Some small comments on style.

File: src/home/homework-luks.c (hunk 13 above)
Comment (scarlet-storm) [reply src/home/homework-luks.c:2394]: I have added the explanation in the commit message. I can reword it to be more elaborate to match this thread. 716e94bd74803fb847db2065589f4ac921b5c1b2

File: src/home/homework-luks.c (hunk 19 above)
Comment (scarlet-storm) [reply src/home/homework-luks.c]: Sorry, I didn't quite understand this. Why do we not want to check if `r < 0` ?

File: src/home/homework-luks.c (hunk 13 above)
Comment (scarlet-storm) [reply src/home/homework-luks.c:2394]: I have reworded the commit in 15b92902af08bb687c91cd64618b3e24e3695e58

File: src/home/homework-luks.c (hunk 18 above)
Comment (scarlet-storm) [reply src/home/homework-luks.c:2376]: It doesn't look like this code is from HEAD

File: src/home/homework-luks.c (hunk 16 above)
Comment (scarlet-storm) [reply src/home/homework-luks.c:70]: - For standardization. the code does not explicitly set the alignment when using fdisk as 4k, so by default fdisk is already using 1MiB alignment for initial partition creation. So the comment says 4k, but the created partition is already aligned to 1MiB boundary. Moreover during resize, fdisk_partition_size_explicit is called with enable=1 . This means that fdisk no longer will align the partitions. So we have a mix of partitions where the initial partition is aligned to 1MiB & if any resize is applied, the partition is aligned to 4KiB.
- As for the reason why 1MiB is used a standard partition size by all linux tools (fdisk, gparted, gptfdisk), it's probably because it is a multiple of most common sector sizes. Note that even for 4K disk, the sector size of 4k is applicable for read/write operations. Other operations like discard might have much higher granularity like 8k / 16k. Also for nand cells probably write amplification also plays a part.
- wasting 1 MiB is still a joke imo.

**Comment by scarlet-storm** [comment]
> Those changes look generally reasonable, but I don't think I grok all the implications. Some small comments on style.

Thank you for the review. If there is anything particular you want to discuss in detail, let me know.

File: src/home/homework-luks.c (hunk 18 above)
Comment (poettering) [reply src/home/homework-luks.c:2376]: indentation is off

Comment (keszybz) [reply src/home/homework-luks.c:2376]: > It doesn't look like this code is from HEAD

It's the code from your patch.

File: src/home/homework-luks.c [hunk 21]
```diff
@@ -2373,24 +2377,48 @@ int home_create_luks(
...
+                        if (r == -ENOENT) { /* this means /dev/loop-control doesn't exist, i.e. we are in a container
+                                             * or similar and loopback bock devices are not available, return a
+                                             * recognizable error in this case. */
+                                log_error_errno(r, "Loopback block device support is not available on this system.");
+                                return -ENOLINK; /* Make recognizable */
+                        }
 
-                return log_error_errno(r, "Failed to set up loopback device for %s: %m", setup->temporary_image_path);
+                        return log_error_errno(r, "Failed to set up loopback device for %s: %m", setup->temporary_image_path);
+                }
```
Comment (keszybz) [inline src/home/homework-luks.c]: The general structure we expect is:
```C
if (r == -ENOENT) {
 ...
} 
if (r < 0)
    return log_error_errno(r, ...);
```

File: src/home/homework-luks.c (hunk 18 above)
Comment (scarlet-storm) [reply src/home/homework-luks.c:2376]: just to clarify what I meant is this code seems to be from some old dangling commit & not HEAD of this PR.
I don't see this code in my homework-luks.c from HEAD, nor do I see this particular comment & corresponding lines in the github UI files changed tab, or in the diff of this patch
https://patch-diff.githubusercontent.com/raw/systemd/systemd/pull/35776.diff

Comment (scarlet-storm) [reply src/home/homework-luks.c:2376]: This is fixed now, the diff from a earlier commit in the series, which was rewritten in later commit.

**Comment by yuwata** [comment]
Sorry for late review, but now this needs to be rebased.

**Comment by scarlet-storm** [comment]
@poettering , @keszybz Is there any pending action items to merge this PR ?

File: src/home/homework-luks.c [hunk 22]
```diff
@@ -2375,21 +2379,45 @@ int home_create_luks(
...
-                        LOCK_EX,
-                        &setup->loop);
-        if (r == -ENOENT) /* this means /dev/loop-control doesn't exist, i.e. we are in a container
-                           * or similar and loopback bock devices are not available, return a
-                           * recognizable error in this case. */
-                return log_error_errno(SYNTHETIC_ERRNO(ENOLINK), "Loopback block device support is not available on this system.");
-        if (r < 0)
-                return log_error_errno(r, "Failed to set up loopback device for %s: %m", setup->temporary_image_path);
+        if (fstat(setup->image_fd, &st) < 0)
+                return -errno;
```
Comment (keszybz) [inline src/home/homework-luks.c]: Elsewhere in this function, we log on error. So this needs to be
`return log_error_errno(errno, "Failed to stat …`.

**Review by keszybz — CHANGES_REQUESTED** [review]
Looks reasonable. Still some style comments.

File: src/home/homework-luks.c [hunk 23]
```diff
@@ -1924,27 +1924,31 @@ static int make_partition_table(
...
                 return log_error_errno(r, "Failed to place partition at first free partition index: %m");
 
+        /* Use same sector size as the fdisk context when converting to bytes */
+        fdisk_sector_size = fdisk_get_sector_size(c);
+        assert(fdisk_sector_size > 0);
+
         first_lba = fdisk_get_first_lba(c); /* Boundary where usable space starts */
-        assert(first_lba <= UINT64_MAX/512);
-        start = DISK_SIZE_ROUND_UP(first_lba * 512); /* Round up to multiple of 4K */
+        assert(first_lba <= UINT64_MAX/fdisk_sector_size);
```
Comment (yuwata) [inline src/home/homework-luks.c]: Please insert space around `/`.
(Yeah, it is not your fault, and we sometimes do not insert spaces for constant arithmetic, but never with variable(s).)

File: src/home/homework-luks.c [hunk 24]
```diff
@@ -1924,27 +1924,31 @@ static int make_partition_table(
...
 
         log_debug("Starting partition at offset %" PRIu64, start);
 
         if (start == UINT64_MAX)
                 return log_error_errno(SYNTHETIC_ERRNO(ERANGE), "Overflow while rounding up start LBA.");
 
         last_lba = fdisk_get_last_lba(c); /* One sector before boundary where usable space ends */
-        assert(last_lba < UINT64_MAX/512);
-        end = DISK_SIZE_ROUND_DOWN((last_lba + 1) * 512); /* Round down to multiple of 4K */
+        assert(last_lba < UINT64_MAX/fdisk_sector_size);
```
Comment (yuwata) [inline src/home/homework-luks.c]: Also here.

File: src/home/homework-luks.c [hunk 25]
```diff
@@ -2801,13 +2808,15 @@ static int get_maximum_partition_size(
         if (r < 0)
                 return log_error_errno(r, "Failed to create fdisk context: %m");
 
+        /* Get the probed sector size by fdisk */
+        fdisk_sector_size = fdisk_get_sector_size(c);
         start_lba = fdisk_partition_get_start(p);
-        assert(start_lba <= UINT64_MAX/512);
-        start = start_lba * 512;
+        assert(start_lba <= UINT64_MAX/fdisk_sector_size);
```
Comment (yuwata) [inline src/home/homework-luks.c]: Also here.

File: src/home/homework-luks.c [hunk 26]
```diff
@@ -2801,13 +2808,15 @@ static int get_maximum_partition_size(
...
+        start = start_lba * fdisk_sector_size;
 
         last_lba = fdisk_get_last_lba(c); /* One sector before boundary where usable space ends */
-        assert(last_lba < UINT64_MAX/512);
-        end = DISK_SIZE_ROUND_DOWN((last_lba + 1) * 512); /* Round down to multiple of 4K */
+        assert(last_lba < UINT64_MAX/fdisk_sector_size);
```
Comment (yuwata) [inline src/home/homework-luks.c]: And here.

File: src/home/homework-luks.c [hunk 27]
```diff
@@ -2888,6 +2888,14 @@ static int apply_resize_partition(
...
 
+        /* Before writing our partition patch the final size in */
+        r = fdisk_partition_size_explicit(p, 1);
+        if (r < 0)
+                return log_error_errno(r, "Failed to enable explicit partition size: %m");
+
+        r = fdisk_partition_set_size(p, new_partition_size / ssz);
+        if (r < 0)
+                return log_error_errno(r, "Failed to change partition size: %m");
         r = fdisk_create_disklabel(c, "gpt");
```
Comment (yuwata) [inline src/home/homework-luks.c:2952]: Please insert an empty line between the error handling and the next function call.

File: src/home/homework-luks.c [hunk 28]
```diff
@@ -3536,7 +3544,7 @@ int home_resize_luks(
         if (new_fs_size < old_fs_size) { /* → Shrink */
 
                 /* Shrink the LUKS device now, matching the new file system size */
-                r = sym_crypt_resize(setup->crypt_device, setup->dm_name, new_fs_size / 512);
+                r = sym_crypt_resize(setup->crypt_device, setup->dm_name, new_fs_size / 512U);
```
Comment (yuwata) [inline src/home/homework-luks.c:3602]: If it is not necessary to use sector size here, maybe better to add a short comment about that?

File: src/home/homework-luks.c (hunk 27 above)
Comment (yuwata) [reply src/home/homework-luks.c:2952]: Oh you did it in the second commit. Please move to the first commit.

File: src/home/homework-luks.c [hunk 29]
```diff
@@ -66,16 +66,16 @@
 #include "user-record.h"
 #include "user-util.h"
 
-/* Round down to the nearest 4K size. Given that newer hardware generally prefers 4K sectors, let's align our
- * partitions to that too. In the worst case we'll waste 3.5K per partition that way, but I think I can live
+/* Round down to the nearest 1 MiB size. Given that most tools generally align partitions to 1 MiB boundaries, let's align our
+ * partitions to that too. In the worst case we'll waste 1 MiB per partition that way, but I think I can live
  * with that. */
-#define DISK_SIZE_ROUND_DOWN(x) ((x) & ~UINT64_C(4095))
+#define DISK_SIZE_ROUND_DOWN(x) ((x) & ~UINT64_C(1048575))
```
Comment (yuwata) [inline src/home/homework-luks.c]: I prefer `(U64_MB - 1)`

File: src/home/homework-luks.c [hunk 30]
```diff
@@ -66,16 +66,16 @@
...
 
-/* Rounds up to the nearest 4K boundary. Returns UINT64_MAX on overflow */
+/* Rounds up to the nearest 1 MiB boundary. Returns UINT64_MAX on overflow */
 #define DISK_SIZE_ROUND_UP(x)                                           \
         ({                                                              \
                 uint64_t _x = (x);                                      \
-                _x > UINT64_MAX - 4095U ? UINT64_MAX : (_x + 4095U) & ~UINT64_C(4095); \
+                _x > UINT64_MAX - 1048575U ? UINT64_MAX : (_x + 1048575U) & ~UINT64_C(1048575); \
```
Comment (yuwata) [inline src/home/homework-luks.c]: Also here. `(U64_MB - 1)`, rather than 1048575.

File: src/home/homework-luks.c [hunk 31]
```diff
@@ -1401,7 +1410,14 @@ int home_setup_luks(
                 if (!subdir)
                         return log_oom();
 
-                r = luks_validate(setup->image_fd, user_record_user_name_and_realm(h), h->partition_uuid, &found_partition_uuid, &offset, &size);
+                r = luks_validate(
+                                setup->image_fd,
+                                user_record_user_name_and_realm(h),
+                                h->partition_uuid,
+                                h->luks_sector_size == UINT64_MAX ? UINT32_MAX : user_record_luks_sector_size(h), /* if sector size is not specified, select UINT32_MAX, i.e. auto-probe */
```
Comment (yuwata) [inline src/home/homework-luks.c]: The line is too long. Please move the comment before the argument:
```c
/* if sector size is not specified, select UINT32_MAX, i.e. auto-probe */
h->luks_sector_size == UINT64_MAX ? UINT32_MAX : user_record_luks_sector_size(h),
```

File: src/home/homework-luks.c [hunk 32]
```diff
@@ -1403,7 +1403,6 @@ int home_setup_luks(
                 assert(setup->root_fd < 0);
                 assert(!setup->crypt_device);
                 assert(!setup->loop);
-
```
Comment (yuwata) [inline src/home/homework-luks.c:1397]: Please keep the empty line after the assertions.

File: src/home/homework-luks.c [hunk 33]
```diff
@@ -2375,21 +2379,45 @@ int home_create_luks(
...
-                        &setup->loop);
-        if (r == -ENOENT) /* this means /dev/loop-control doesn't exist, i.e. we are in a container
-                           * or similar and loopback bock devices are not available, return a
-                           * recognizable error in this case. */
-                return log_error_errno(SYNTHETIC_ERRNO(ENOLINK), "Loopback block device support is not available on this system.");
-        if (r < 0)
-                return log_error_errno(r, "Failed to set up loopback device for %s: %m", setup->temporary_image_path);
+        if (fstat(setup->image_fd, &st) < 0)
+                return log_error_errno(errno, "Failed to fstat home image: %m");
+        /* Ensure we don't create a loop device over block device as it leads to huge overhead for discard operations
```
Comment (yuwata) [inline src/home/homework-luks.c:2393]: Please insert an empty line between the error handling and the comment for the next.

File: src/home/homework-luks.c [hunk 34]
```diff
@@ -2375,21 +2379,45 @@ int home_create_luks(
...
+         * if the device does not support discard_zeroes_data */
+        if (S_ISBLK(st.st_mode)) {
+                _cleanup_free_ char *partition_path = NULL;
+                assert(!sd_id128_is_null(partition_uuid));
+                if (asprintf(&partition_path, "/dev/disk/by-partuuid/" SD_ID128_UUID_FORMAT_STR, SD_ID128_FORMAT_VAL(partition_uuid)) < 0)
+                        return log_oom();
+                /* Release the lock, so that udev can find the partition */
+                setup->image_fd = safe_close(setup->image_fd);
```
Comment (yuwata) [inline src/home/homework-luks.c:2402]: Please insert an empty line after the error check.

File: src/home/homework-luks.c [hunk 35]
```diff
@@ -2375,21 +2379,45 @@ int home_create_luks(
...
+                (void) wait_for_devlink(partition_path);
+                setup->image_fd = open_image_file(h, ip, &st);
+                if (setup->image_fd < 0)
+                        return setup->image_fd;
+                r = loop_device_open_from_path(
```
Comment (yuwata) [inline src/home/homework-luks.c:2408]: Also here.

**Review by yuwata — CHANGES_REQUESTED** [review]
Several coding style requests.

**Review by yuwata — APPROVED** [review]

**Comment by GreyXor** [comment]
Thank you everyone for this PR!
@scarlet-storm :tada:

**Comment by GreyXor** [comment]
Hello @scarlet-storm, I just tried a new homectl 260.1
This PR should `Automatically probe sector size of physical block device, if user does not pass luks-sector-size explicitly.`

I created my user like so:
```
homectl create greyxor \
    --shell=/usr/bin/zsh \
    --member-of="wheel" \
    --disk-size="max" \
    --auto-resize-mode="off" \
    --luks-extra-mount-options compress=zstd
```

```bash
sudo fdisk -l                      
[sudo: authenticate] Password:         
Disk /dev/nvme0n1: 931,51 GiB, 1000204886016 bytes, 244190646 sectors
Disk model: CT1000T500SSD8                          
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 4F8C2039-A66D-4BF2-9DD7-0D346F4CC561

Device            Start       End   Sectors   Size Type
/dev/nvme0n1p1      256    524543    524288     2G EFI System
/dev/nvme0n1p2   524544   2621695   2097152     8G Linux swap
/dev/nvme0n1p3  2621696  36176127  33554432   128G Linux root (x86-64)
/dev/nvme0n1p4 36176128 244190463 208014336 793,5G Linux home


Disk /dev/loop0: 779,97 GiB, 837484019712 bytes, 1635710976 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/home-greyxor: 779,95 GiB, 837467242496 bytes, 1635678208 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

Shouldn't `/dev/mapper/home-greyxor` and `/dev/loop0` would be 4096 luks-sector-size ? My nvme ssd is 4kn native and all my partitions too

**Comment by scarlet-storm** [comment]
Hi @GreyXor ,
The automatic probing of sector size is for block device based home images not file based images. In your case it would be something like `homectl create <args>... --image-path=/dev/nvme0n1p4` **(this will erase data on /dev/nvme0n1p4)** . 
The reason it has to be done for block devices is mentioned in #30394 . The kernel will not be able to detect the partition table if it does not match sector size of the block device.
In case of file-based both 4k and 512b values should work fine. But we also need to account for backwards compatibility with old home images which were created with 512b sector size. That's why I'm using the same default. You can always override using `--luks-sector-size=4096` if you want a 4k file image.
Also note: If you are concerned about i/o performance, it won't make much difference for ext4 & btrfs. Both of them default to 4k block size even on 512 sector disk. So there won't be any overhead of realigning i/o.
Only xfs defaults to 512 block size if possible, and can face a penalty overhead if used with default 512 sector file image on a 4k disk

**Comment by GreyXor** [comment]
Thanks @scarlet-storm, very informative.
Are you sure that I can do `homectl create <args>... --image-path=/dev/nvme0n1p4` ? Seem not possible: see [this issue](https://github.com/systemd/systemd/issues/15273).

**Comment by scarlet-storm** [comment]
@GreyXor , I was not aware of the issue. You are right, it might not be possible to directly use the raw partition device because the kernel will not be able to autodetect the nested partition table. You can use one of the workarounds mentioned in the issue.
Another possibility is to create a systemd service that calls `losetup -fP -b 4096 /dev/nvme0n1p4` during boot and use the resultant loop device as the home image.
I can check if it's possible to add support for any block device as backing image instead of full disks.

**Comment by GreyXor** [comment]
@scarlet-storm Hi! by any chance did you find if it's possible to add support for any block device ?
Seem that there's a solution here: https://github.com/systemd/systemd/issues/15273#issuecomment-5285031038
