### PR TITLE
core: fix logic of merging units

### LINKED ISSUE #24577: init: Assertion 'hashmap_isempty(m->jobs)' failed at src/core/manager.c:1474, function manager_clear_jobs_and_units(). Aborting.
### systemd version the issue has been seen with

251.3

### Used distribution

Debian Bullseye

### Linux kernel version used

5.15.46

### CPU architectures issue was seen on

x86_64

### Component

_No response_

### Expected behaviour you didn't see

No crash

### Unexpected behaviour you saw

```
Broadcast message from systemd-journald@133m11 (Tue 2022-09-06 12:18:06 UTC):

systemd[1]: Caught <ABRT> from our own process.


Broadcast message from systemd-journald@133m11 (Tue 2022-09-06 12:18:06 UTC):

systemd[1]: Caught <ABRT>, dumped core as pid 3960.


Broadcast message from systemd-journald@133m11 (Tue 2022-09-06 12:18:06 UTC):

systemd[1]: Freezing execution.

Sep 06 12:18:06 133m11 systemd[1]: Reloading.
Sep 06 12:18:06 133m11 systemd[1]: Assertion 'hashmap_isempty(m->jobs)' failed at src/core/manager.c:1474, function manager_clear_jobs_and_units(). Aborting.
Sep 06 12:18:06 133m11 systemd[1]: Caught <ABRT> from our own process.
Sep 06 12:18:06 133m11 systemd[1]: Caught <ABRT>, dumped core as pid 3960.
Sep 06 12:18:06 133m11 systemd[1]: Freezing execution.
```

### Steps to reproduce the problem

I seemed to manage to trigger this twice during early-boot (over serial console) by calling `systemctl stop` on two service units and one path unit, right as some initialisation routine calls `systemctl daemon-reload`.
I'm not sure how to put the system into debug mode from boot. I can tweak the kernel cmdline if necessary, but this happens so early that it's hard to do anything before the window passes.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### LINKED ISSUE #24990: There is a heap-use-after-free in manager_clear_jobs_and_units
### systemd version the issue has been seen with

systemd-251.4-53.fc37.x86_64

### Used distribution

Fedora 37

### Linux kernel version used

Linux localhost.localdomain 5.19.7-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Sep 5 15:09:01 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

I have a script just like test below with special 'M-BM-' character in /etc/rc.d/init.d/test.  systemd will crash if  "Provides" and "Required-Start" have the same word even though it's not 'M-BM-'.
```
[root@localhost init.d]# cat -A test
#!/bin/bash$
$
### BEGIN INIT INFO$
# Provides:M-BM-  M-BM-  M-BM-  M-BM-  M-BM- test$
# Required-Start:M-BM-  M-BM- $remote_fs $network$
# Required-Stop:M-BM-  M-BM-  $remote_fs $network$
# Description:for test$
# Short-Description:Test$
### END INIT INFO$
$
case "$1" in$
    start)$
        sleep 1000 &$
        ;;$
    stop)$
        sleep 10 &$
        ;;$
    *)$
        echo "Usage: service test {start|stop|restart|status}"$
        ;;$
esac$

```

### Unexpected behaviour you saw

Systemd is killed by the SEGV signal.

### Steps to reproduce the problem

1. setenforce 0
2. put test script in /etc/rc.d/init.d/test with no 'M-BM-'
```
[root@localhost init.d]# pwd
/etc/rc.d/init.d
[root@localhost init.d]# cat test
#!/bin/bash

### BEGIN INIT INFO
# Provides:test1 test2 
# Required-Start: $remote_fs $network
#### Required-Start:test1 $remote_fs $network
# Required-Stop:test1 $remote_fs $network
# Description:Test
# Short-Description: Test
### END INIT INFO

case "$1" in
    start)
        sleep 1000 &
        ;;
    stop)
        sleep 10 &
        ;;
    *)
        echo "Usage: service test {start|stop|restart|status}"
        ;;
esac

```
3.chmod 777 test; systemctl daemon-reload;systemctl start test
4.change /etc/rc.d/init.d/test with '####' while test.service is running.
```
[root@localhost init.d]# cat test
#!/bin/bash

### BEGIN INIT INFO
# Provides:test1 test2 
#### Required-Start: $remote_fs $network
# Required-Start:test1 $remote_fs $network
# Required-Stop:test1 $remote_fs $network
# Description:Test
# Short-Description: Test
### END INIT INFO

case "$1" in
    start)
        sleep 1000 &
        ;;
    stop)
        sleep 10 &
        ;;
    *)
        echo "Usage: service test {start|stop|restart|status}"
        ;;
esac
```
5. run
```
while true;do systemctl daemon-reload;done
```

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes several bugs introduced by 15ed3c3a188cf7fa5a60ae508fc7a3ed048d2220 (v249).

Fixes #24990. Also, hopefully fixes #24577.

### CODE REVIEW

**Comment by yuwata** [comment]
(Hm, still GC logic needs to be updated.)

**Comment by yuwata** [comment]
The commit for unit GC is dropped.

File: src/core/unit.c [hunk 1]
```diff
@@ -1076,7 +1076,7 @@ static void unit_merge_dependencies(
                         if (back == u) {
                                 /* This is a dependency pointing back to the unit we want to merge with?
                                  * Suppress it (but warn) */
-                                unit_maybe_warn_about_dependency(u, other->id, UNIT_DEPENDENCY_FROM_PTR(dt));
+                                unit_maybe_warn_about_dependency(u, u->id, UNIT_DEPENDENCY_FROM_PTR(dt));
```
Comment (keszybz) [inline src/core/unit.c]: This doesn't make sense, because `unit_maybe_warn_about_dependency()` will always say `<id>: Dependency Type=<id> dropped`, where `<id>` is the destination unit that we're merging things into. It didn't have this dependency, so this message would be outright wrong.

File: test/units/testsuite-26.sh [hunk 2]
```diff
@@ -284,6 +292,110 @@ systemctl unset-environment IMPORT_THIS IMPORT_THIS_TOO
...
+    *)
+        echo "Usage: service test {start|stop|restart|status}"
+        ;;
+esac
+EOF
+
+    chmod +x /etc/init.d/issue-24990
+    systemctl daemon-reload
+    [[ -L /run/systemd/generator.late/test1.service ]]
+    [[ -L /run/systemd/generator.late/test2.service ]]
```
Comment (keszybz) [inline test/units/testsuite-26.sh:328]: `test -L /run/systemd/generator.late/test1.service`
`test -L /run/systemd/generator.late/test2.service`
?

File: test/units/testsuite-26.sh [hunk 3]
```diff
@@ -284,6 +292,110 @@ systemctl unset-environment IMPORT_THIS IMPORT_THIS_TOO
...
+    assert_in "After=test1.service" "$output"
+    assert_in "After=remote-fs.target" "$output"
+    assert_in "After=network-online.target" "$output"
+    assert_in "Wants=network-online.target" "$output"
+    assert_in "ExecStart=/etc/init.d/issue-24990 start" "$output"
+    assert_in "ExecStop=/etc/init.d/issue-24990 stop" "$output"
+    systemctl status issue-24990 || :
+    systemctl show issue-24990
+    assert_not_in "issue-24990.service" "$(systemctl show -property=After --value)"
+    assert_not_in "issue-24990.service" "$(systemctl show -property=Before --value)"
```
Comment (keszybz) [inline test/units/testsuite-26.sh]: `-property` is missing a dash and there's unit name argument. `systemctl show -P After issue-24990.service` instead.

RFE: It'd be nice if `-p` and `-P` would complain if the given property names are not valid.

File: test/units/testsuite-26.sh [hunk 4]
```diff
@@ -284,6 +292,110 @@ systemctl unset-environment IMPORT_THIS IMPORT_THIS_TOO
...
+    *)
+        echo "Usage: service test {start|stop|restart|status}"
+        ;;
+esac
+EOF
+
+    chmod +x /etc/init.d/issue-24990
+    systemctl daemon-reload
+    [[ -L /run/systemd/generator.late/test1.service ]]
+    [[ -L /run/systemd/generator.late/test2.service ]]
```
Comment (keszybz) [inline test/units/testsuite-26.sh:382]: As above.

File: test/units/testsuite-26.sh [hunk 5]
```diff
@@ -284,6 +292,110 @@ systemctl unset-environment IMPORT_THIS IMPORT_THIS_TOO
...
+    output=$(systemctl cat issue-24990)
+    assert_in "SourcePath=/etc/init.d/issue-24990" "$output"
+    assert_in "Description=LSB: Test" "$output"
+    assert_in "After=remote-fs.target" "$output"
+    assert_in "ExecStart=/etc/init.d/issue-24990 start" "$output"
+    assert_in "ExecStop=/etc/init.d/issue-24990 stop" "$output"
+    systemctl status issue-24990 || :
+    systemctl show issue-24990
+    assert_not_in "issue-24990.service" "$(systemctl show -property=After --value)"
+    assert_not_in "issue-24990.service" "$(systemctl show -property=Before --value)"
```
Comment (keszybz) [inline test/units/testsuite-26.sh]: Here too.

File: src/core/unit.c [hunk 6]
```diff
@@ -1055,12 +1055,22 @@ static void unit_merge_dependencies(
         if (u == other)
                 return;
 
+        /* First, remove dependency to other. */
+        HASHMAP_FOREACH_KEY(deps, dt, u->dependencies) {
+                UnitDependencyInfo di_other;
```
Comment (keszybz) [inline src/core/unit.c]: `di_other` is initialized, but it isn't really used for anything. Maybe write this as
```C
if (hashmap_remove(deps, other) != NULL)
    unit_maybe_warn_about_dependency(u, other->id, UNIT_DEPENDENCY_FROM_PTR(dt));
```
?

File: test/units/testsuite-26.sh (hunk 2 above)
Comment (yuwata) [reply test/units/testsuite-26.sh:328]: That's mostly equivalent with the current code, right?

File: test/units/testsuite-26.sh (hunk 3 above)
Comment (yuwata) [reply test/units/testsuite-26.sh]: Ouch!

File: test/units/testsuite-26.sh (hunk 2 above)
Comment (keszybz) [reply test/units/testsuite-26.sh:328]: It is, but it's a bash syntax, and we generally prefer plain sh unless there's a reason to do otherwise, and this style is generally used in tests.

Comment (yuwata) [reply test/units/testsuite-26.sh:328]: But the shbang of the script requests bash, and similar checks already exists in the test. I'd like to address your point more consistently in another PR if we need to drop bashism from the test.

File: src/core/unit.c (hunk 1 above)
Comment (yuwata) [reply src/core/unit.c]: Should be addressed now.

**Comment by yuwata** [comment]
@keszybz Thank you for the review. All points, except for the bashism in the test, are addressed. PTAL!

File: test/units/testsuite-26.sh (hunk 2 above)
Comment (keszybz) [reply test/units/testsuite-26.sh:328]: Ack.

File: src/core/unit.c [hunk 7]
```diff
@@ -956,10 +959,19 @@ static void unit_maybe_warn_about_dependency(
...
+        log_unit_warning(u, "Dependency %s=%s%s%s is dropped%s%s%s%s.",
+                         unit_dependency_to_string(dependency),
+                         strna(target->id),
+                         show_owner ? " in " : "",
+                         show_owner ? strna(owner->id) : "",
+                         reason_id ? ", as " : "",
+                         reason_id,
+                         reason_id ? " is merged into " : "",
+                         reason_id ? strna(u->id) : "");
 }
```
Comment (keszybz) [inline src/core/unit.c:951]: Hmm, so I think this helper is just too complicated. It has three callers and the logic here is just sooo complicated. Wouldn't it be better to reduce this to
```
static bool warn_about_dependency(UnitDependency dependency) {
      return IN_SET(dependency, …);
}
```
and move the warning logic into the callers?

Comment (keszybz) [reply src/core/unit.c:951]: If you prefer, we can merge this as-is and refactor later, but I'd prefer to update it, because it's hard to review in current form.

Comment (yuwata) [reply src/core/unit.c:951]: Done. PTAL!

File: src/core/unit.c [hunk 8]
```diff
@@ -1057,8 +1045,10 @@ static void unit_merge_dependencies(Unit *u, Unit *other) {
 
         /* First, remove dependency to other. */
         HASHMAP_FOREACH_KEY(deps, dt, u->dependencies) {
-                if (hashmap_remove(deps, other))
-                        unit_maybe_warn_about_dependency(u, other->id, UNIT_DEPENDENCY_FROM_PTR(dt));
+                if (hashmap_remove(deps, other) && unit_should_warn_about_dependency(UNIT_DEPENDENCY_FROM_PTR(dt)))
+                        log_unit_warning(u, "Dependency %s=%s is dropped, as %s is merged into %s.",
+                                         unit_dependency_to_string(UNIT_DEPENDENCY_FROM_PTR(dt)),
+                                         strna(other->id), strna(other->id), strna(u->id));
```
Comment (keszybz) [inline src/core/unit.c]: We don't need `strna` here. In the previous version, `strna` was used around `other_id`, because the helper could be called with NULL. But we cannot have a unit without `id`.

File: src/core/unit.c [hunk 9]
```diff
@@ -1085,7 +1075,11 @@ static void unit_merge_dependencies(Unit *u, Unit *other) {
                         if (back == u) {
                                 /* This is a dependency pointing back to the unit we want to merge with?
                                  * Suppress it (but warn) */
-                                unit_maybe_warn_about_dependency(u, other->id, UNIT_DEPENDENCY_FROM_PTR(dt));
+                                if (unit_should_warn_about_dependency(UNIT_DEPENDENCY_FROM_PTR(dt)))
+                                        log_unit_warning(u, "Dependency %s=%s in %s is dropped, as %s is merged into %s.",
+                                                         unit_dependency_to_string(UNIT_DEPENDENCY_FROM_PTR(dt)),
+                                                         strna(u->id), strna(other->id), strna(other->id), strna(u->id));
```
Comment (keszybz) [inline src/core/unit.c]: Same here.

File: src/core/unit.c [hunk 10]
```diff
@@ -3074,7 +3067,9 @@ int unit_add_dependency(
 
         /* We won't allow dependencies on ourselves. We will not consider them an error however. */
         if (u == other) {
-                unit_maybe_warn_about_dependency(original_u, original_other->id, d);
+                if (unit_should_warn_about_dependency(d))
+                        log_unit_warning(u, "Dependency %s=%s is dropped.",
+                                         unit_dependency_to_string(d), strna(u->id));
```
Comment (keszybz) [inline src/core/unit.c]: Same here.

**Review by keszybz — COMMENTED** [review]
LaGTM. (*almost* good)

**Comment by yuwata** [comment]
@keszybz Thank you for your review. All comments are addressed. Upgrading the green label.

> LaGTM. (_almost_ good)

I like the abbreviation!

File: src/core/unit.c [hunk 11]
```diff
@@ -1085,6 +1086,7 @@ static void unit_merge_dependencies(Unit *u, Unit *other) {
                                 /* This is a dependency pointing back to the unit we want to merge with?
                                  * Suppress it (but warn) */
                                 unit_maybe_warn_about_dependency(u, other->id, UNIT_DEPENDENCY_FROM_PTR(dt));
+                                hashmap_remove(other_deps, back);
```
Comment (poettering) [inline src/core/unit.c:1083]: hmm, now you are changing the hashmap you are iterating through. It's something I so far avoided

**Comment by poettering** [comment]
looks good, but iterating through a hashmap that we modify is problematic, iirc our hashmap implementation is not safe against arbitrary changes during iteration

**Comment by yuwata** [comment]
> looks good, but iterating through a hashmap that we modify is problematic, iirc our hashmap implementation is not safe against arbitrary changes during iteration

It _is_ safe. Please see the comment in `hashmap_iterate_in_internal_order()`.

**Review by bluca — APPROVED** [review]

**Comment by keszybz** [comment]
This was already included in v252.4.
