### PR TITLE
home: fix heap-use-after-free

### LINKED ISSUE #21767: home: heap-use-after-free
https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/8908/artifact//systemd-centos-ci/index.html
```
[TASK START] Mon Dec 13 07:54:49 PM UTC 2021
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-01-BASIC_sanitizers-nspawn_PASS.log ***
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-01-BASIC_sanitizers-qemu_PASS.log ***
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-04-JOURNAL_1_PASS.log ***
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-13-NSPAWN-SMOKE_1_PASS.log ***
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-15-DROPIN_1_PASS.log ***
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-17-UDEV_1_PASS.log ***
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-22-TMPFILES_1_PASS.log ***
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-29-PORTABLE_1_PASS.log ***
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-46-HOMED_1_FAIL.log ***
[  158.559571] systemd-homed[288]: ==288==ERROR: AddressSanitizer: heap-use-after-free on address 0x61c0000006dc at pc 0x7f47cd290cec bp 0x7fffff333ed0 sp 0x7fffff333ec8
[  158.561677] systemd-homed[288]: READ of size 4 at 0x61c0000006dc thread T0
[[0;32m  OK  [0m] Stopped [0;1;39mPermit User Sessions[0m.
systemd-logind.service: Deactivated successfully.
[[0;32m  OK  [0m] Stopped [0;1;39mUser Login Management[0m.
[  159.103897] systemd-homed[288]:     #0 0x7f47cd290ceb in bus_pid_changed /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3592:21
[  159.104343] systemd-homed[288]:     #1 0x7f47cd262105 in sd_bus_emit_object_removed /systemd-meson-build/../build/src/libsystemd/sd-bus/bus-objects.c:2704:9
[  159.108024] systemd-homed[288]:     #2 0x55e5aa8ba16b in bus_home_emit_remove /systemd-meson-build/../build/src/home/homed-home-bus.c:947:13
[  159.111752] systemd-homed[288]:     #3 0x55e5aa8bb455 in home_free /systemd-meson-build/../build/src/home/homed-home.c:180:24
[  159.117286] systemd-homed[288]:     #4 0x55e5aa8f3978 in __unique_prefix_static_free_wrapper14 /systemd-meson-build/../build/src/home/homed-manager.c:69:1
[  159.120963] systemd-homed[288]:     #5 0x7f47cd0f3ce1 in _hashmap_clear /systemd-meson-build/../build/src/basic/hashmap.c:919:33
[  159.124699] systemd-homed[288]:     #6 0x7f47cd0f36ce in _hashmap_free /systemd-meson-build/../build/src/basic/hashmap.c:888:17
[  159.128404] systemd-homed[288]:     #7 0x55e5aa8e25e8 in hashmap_free /systemd-meson-build/../build/src/basic/hashmap.h:102:24
[  159.132117] systemd-homed[288]:     #8 0x55e5aa8e25e8 in manager_free /systemd-meson-build/../build/src/home/homed-manager.c:270:9
[  159.133884] systemd-homed[288]:     #9 0x55e5aa8ff4d6 in manager_freep /systemd-meson-build/../build/src/home/homed-manager.h:76:1
[  159.137580] systemd-homed[288]:     #10 0x55e5aa8ff4d6 in run /systemd-meson-build/../build/src/home/homed.c:49:1
[  159.141338] systemd-homed[288]:     #11 0x55e5aa8ff4d6 in main /systemd-meson-build/../build/src/home/homed.c:51:1
[  159.145047] systemd-homed[288]:     #12 0x7f47cc24ab24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
[  159.148785] systemd-homed[288]:     #13 0x55e5aa8b182d in _start (/usr/lib/systemd/systemd-homed+0x5582d)
[  159.150554] systemd-homed[288]: 0x61c0000006dc is located 1628 bytes inside of 1800-byte region [0x61c000000080,0x61c000000788)
[  159.154229] systemd-homed[288]: freed by thread T0 here:
[  159.222540] systemd-homed[288]:     #0 0x7f47cd9f8c49 in __interceptor_free (/usr/lib/clang/13.0.0/lib/linux/libclang_rt.asan-x86_64.so+0xf7c49)
[  159.222806] systemd-homed[288]:     #1 0x7f47cd29fbda in bus_free /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:226:16
[  159.224740] systemd-homed[288]:     #2 0x7f47cd29ec4a in sd_bus_unref /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1798:1
[  159.228507] systemd-homed[288]:     #3 0x7f47cd29edaa in sd_bus_close_unref /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1775:16
[  159.234095] systemd-homed[288]:     #4 0x7f47cd29edaa in sd_bus_flush_close_unref /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1786:16
[  159.237919] systemd-homed[288]:     #5 0x55e5aa8e22ad in manager_free /systemd-meson-build/../build/src/home/homed-manager.c:256:9
[  159.241680] systemd-homed[288]:     #6 0x55e5aa8ff4d6 in manager_freep /systemd-meson-build/../build/src/home/homed-manager.h:76:1
[  159.247333] systemd-homed[288]:     #7 0x55e5aa8ff4d6 in run /systemd-meson-build/../build/src/home/homed.c:49:1
[  159.251431] systemd-homed[288]:     #8 0x55e5aa8ff4d6 in main /systemd-meson-build/../build/src/home/homed.c:51:1
[  159.255173] systemd-homed[288]:     #9 0x7f47cc24ab24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
[  159.260769] systemd-homed[288]: previously allocated by thread T0 here:
[  159.306067] systemd-homed[288]:     #0 0x7f47cd9f8f09 in __interceptor_malloc (/usr/lib/clang/13.0.0/lib/linux/libclang_rt.asan-x86_64.so+0xf7f09)
[  159.306328] systemd-homed[288]:     #1 0x7f47cd290460 in malloc_multiply /systemd-meson-build/../build/src/basic/alloc-util.h:103:16
[  159.308313] systemd-homed[288]:     #2 0x7f47cd290460 in sd_bus_new /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:236:13
[0;1;39msystemd-homed.service: Main process exited, code=exited, status=1/FAILURE[0m
[  159.312258] systemd-homed[288]:     #3 0x7f47cd29a7e9 in sd_bus_open_system_with_description /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1291:13
[0;1;39msystemd-homed.service: Killing process 1675 (llvm-symbolizer) with signal SIGKILL.[0m
[  159.321131] systemd-homed[288]:     #4 0x7f47cd29b17a in sd_bus_open_system /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1322:16
[0;1;38;5;185msystemd-homed.service: Failed with result 'exit-code'.[0m
[  159.324965] systemd-homed[288]:     #5 0x7f47cd2b0b41 in bus_default /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3899:13
systemd-homed.service: Unit process 1675 (llvm-symbolizer) remains running after unit stopped.
[  159.335535] systemd-homed[288]:     #6 0x7f47cd2b098a in sd_bus_default_system /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3912:16
[  159.338290] systemd-homed[288]:     #7 0x55e5aa8eaaff in manager_connect_bus /systemd-meson-build/../build/src/home/homed-manager.c:947:13
[  159.342045] systemd-homed[288]:     #8 0x55e5aa8e73f8 in manager_startup /systemd-meson-build/../build/src/home/homed-manager.c:1580:13
[  159.343825] systemd-homed[288]:     #9 0x55e5aa8ff36a in run /systemd-meson-build/../build/src/home/homed.c:38:13
[  159.347566] systemd-homed[288]:     #10 0x55e5aa8ff36a in main /systemd-meson-build/../build/src/home/homed.c:51:1
[  159.351330] systemd-homed[288]:     #11 0x7f47cc24ab24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
[  159.355152] systemd-homed[288]: SUMMARY: AddressSanitizer: heap-use-after-free /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3592:21 in bus_pid_changed


Dec 13 19:41:01 H systemd-homed[288]: ==288==ERROR: AddressSanitizer: heap-use-after-free on address 0x61c0000006dc at pc 0x7f47cd290cec bp 0x7fffff333ed0 sp 0x7fffff333ec8
Dec 13 19:41:01 H systemd-homed[288]: READ of size 4 at 0x61c0000006dc thread T0
Dec 13 19:41:01 H systemd-homed[288]:     #0 0x7f47cd290ceb in bus_pid_changed /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3592:21
Dec 13 19:41:01 H systemd-homed[288]:     #1 0x7f47cd262105 in sd_bus_emit_object_removed /systemd-meson-build/../build/src/libsystemd/sd-bus/bus-objects.c:2704:9
Dec 13 19:41:01 H systemd-homed[288]:     #2 0x55e5aa8ba16b in bus_home_emit_remove /systemd-meson-build/../build/src/home/homed-home-bus.c:947:13
Dec 13 19:41:01 H systemd-homed[288]:     #3 0x55e5aa8bb455 in home_free /systemd-meson-build/../build/src/home/homed-home.c:180:24
Dec 13 19:41:01 H systemd-homed[288]:     #4 0x55e5aa8f3978 in __unique_prefix_static_free_wrapper14 /systemd-meson-build/../build/src/home/homed-manager.c:69:1
Dec 13 19:41:01 H systemd-homed[288]:     #5 0x7f47cd0f3ce1 in _hashmap_clear /systemd-meson-build/../build/src/basic/hashmap.c:919:33
Dec 13 19:41:01 H systemd-homed[288]:     #6 0x7f47cd0f36ce in _hashmap_free /systemd-meson-build/../build/src/basic/hashmap.c:888:17
Dec 13 19:41:01 H systemd-homed[288]:     #7 0x55e5aa8e25e8 in hashmap_free /systemd-meson-build/../build/src/basic/hashmap.h:102:24
Dec 13 19:41:01 H systemd-homed[288]:     #8 0x55e5aa8e25e8 in manager_free /systemd-meson-build/../build/src/home/homed-manager.c:270:9
Dec 13 19:41:01 H systemd-homed[288]:     #9 0x55e5aa8ff4d6 in manager_freep /systemd-meson-build/../build/src/home/homed-manager.h:76:1
Dec 13 19:41:01 H systemd-homed[288]:     #10 0x55e5aa8ff4d6 in run /systemd-meson-build/../build/src/home/homed.c:49:1
Dec 13 19:41:01 H systemd-homed[288]:     #11 0x55e5aa8ff4d6 in main /systemd-meson-build/../build/src/home/homed.c:51:1
Dec 13 19:41:01 H systemd-homed[288]:     #12 0x7f47cc24ab24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
Dec 13 19:41:01 H systemd-homed[288]:     #13 0x55e5aa8b182d in _start (/usr/lib/systemd/systemd-homed+0x5582d)
Dec 13 19:41:01 H systemd-homed[288]: 0x61c0000006dc is located 1628 bytes inside of 1800-byte region [0x61c000000080,0x61c000000788)
Dec 13 19:41:01 H systemd-homed[288]: freed by thread T0 here:
Dec 13 19:41:01 H systemd-homed[288]:     #0 0x7f47cd9f8c49 in __interceptor_free (/usr/lib/clang/13.0.0/lib/linux/libclang_rt.asan-x86_64.so+0xf7c49)
Dec 13 19:41:01 H systemd-homed[288]:     #1 0x7f47cd29fbda in bus_free /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:226:16
Dec 13 19:41:01 H systemd-homed[288]:     #2 0x7f47cd29ec4a in sd_bus_unref /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1798:1
Dec 13 19:41:01 H systemd-homed[288]:     #3 0x7f47cd29edaa in sd_bus_close_unref /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1775:16
Dec 13 19:41:01 H systemd-homed[288]:     #4 0x7f47cd29edaa in sd_bus_flush_close_unref /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1786:16
Dec 13 19:41:01 H systemd-homed[288]:     #5 0x55e5aa8e22ad in manager_free /systemd-meson-build/../build/src/home/homed-manager.c:256:9
Dec 13 19:41:01 H systemd-homed[288]:     #6 0x55e5aa8ff4d6 in manager_freep /systemd-meson-build/../build/src/home/homed-manager.h:76:1
Dec 13 19:41:01 H systemd-homed[288]:     #7 0x55e5aa8ff4d6 in run /systemd-meson-build/../build/src/home/homed.c:49:1
Dec 13 19:41:01 H systemd-homed[288]:     #8 0x55e5aa8ff4d6 in main /systemd-meson-build/../build/src/home/homed.c:51:1
Dec 13 19:41:01 H systemd-homed[288]:     #9 0x7f47cc24ab24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
Dec 13 19:41:01 H systemd-homed[288]: previously allocated by thread T0 here:
Dec 13 19:41:02 H systemd-homed[288]:     #0 0x7f47cd9f8f09 in __interceptor_malloc (/usr/lib/clang/13.0.0/lib/linux/libclang_rt.asan-x86_64.so+0xf7f09)
Dec 13 19:41:02 H systemd-homed[288]:     #1 0x7f47cd290460 in malloc_multiply /systemd-meson-build/../build/src/basic/alloc-util.h:103:16
Dec 13 19:41:02 H systemd-homed[288]:     #2 0x7f47cd290460 in sd_bus_new /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:236:13
Dec 13 19:41:02 H systemd-homed[288]:     #3 0x7f47cd29a7e9 in sd_bus_open_system_with_description /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1291:13
Dec 13 19:41:02 H systemd-homed[288]:     #4 0x7f47cd29b17a in sd_bus_open_system /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1322:16
Dec 13 19:41:02 H systemd-homed[288]:     #5 0x7f47cd2b0b41 in bus_default /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3899:13
Dec 13 19:41:02 H systemd-homed[288]:     #6 0x7f47cd2b098a in sd_bus_default_system /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3912:16
Dec 13 19:41:02 H systemd-homed[288]:     #7 0x55e5aa8eaaff in manager_connect_bus /systemd-meson-build/../build/src/home/homed-manager.c:947:13
Dec 13 19:41:02 H systemd-homed[288]:     #8 0x55e5aa8e73f8 in manager_startup /systemd-meson-build/../build/src/home/homed-manager.c:1580:13
Dec 13 19:41:02 H systemd-homed[288]:     #9 0x55e5aa8ff36a in run /systemd-meson-build/../build/src/home/homed.c:38:13
Dec 13 19:41:02 H systemd-homed[288]:     #10 0x55e5aa8ff36a in main /systemd-meson-build/../build/src/home/homed.c:51:1
Dec 13 19:41:02 H systemd-homed[288]:     #11 0x7f47cc24ab24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
Dec 13 19:41:02 H systemd-homed[288]: SUMMARY: AddressSanitizer: heap-use-after-free /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3592:21 in bus_pid_changed


 ____________________________________________
/ Found   2 sanitizer errors (  2 ASan,   0  \
| UBSan,   0 MSan). Looks like you need to   |
\ look at the log                            /
 --------------------------------------------
 \
  \
     __
    /  \
    |  |
    @  @
    |  |
    || |/
    || ||
    |\_/|
    \___/
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-46-HOMED_2_PASS.log ***
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-50-DISSECT_1_PASS.log ***
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-55-OOMD_1_PASS.log ***
*** Processing file /build/vagrant-arch-sanitizers-clang-testsuite.us1/TEST-58-REPART_1_PASS.log ***
[TASK END] Mon Dec 13 07:54:50 PM UTC 2021
```

### PR DESCRIPTION
**Pull request by yuwata**
`bus_home_emit_remove()` may be called from manager_free() -> home_free().
In that case, manager->bus is already unref()ed.

Fixes #21767.

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

**Comment by keszybz** [comment]
09:31:17 TEST-46-HOMED_1_sanitizer_errors

<details>

```
08:53:20 [[0;32m  OK  [0m] Stopped [0;1;39mPermit User Sessions[0m.
08:53:20 [  172.635106] systemd-homed[331]:     #0 0x7ff9ceed869b in bus_pid_changed /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3592:21
08:53:20 [  172.635714] systemd-homed[331]:     #1 0x7ff9ceea9ab5 in sd_bus_emit_object_removed /systemd-meson-build/../build/src/libsystemd/sd-bus/bus-objects.c:2704:9
08:53:20 [  172.636441] systemd-homed[331]:     #2 0x55c7838111d7 in bus_home_emit_remove /systemd-meson-build/../build/src/home/homed-home-bus.c:953:13
08:53:20 [  172.637336] systemd-homed[331]:     #3 0x55c7838125c5 in home_free /systemd-meson-build/../build/src/home/homed-home.c:180:24
08:53:20 [  172.638989] systemd-homed[331]:     #4 0x55c78384aae8 in __unique_prefix_static_free_wrapper14 /systemd-meson-build/../build/src/home/homed-manager.c:69:1
08:53:20 [  172.639796] systemd-homed[331]:     #5 0x7ff9ced3b691 in _hashmap_clear /systemd-meson-build/../build/src/basic/hashmap.c:919:33
08:53:20 [  172.640697] systemd-homed[331]:     #6 0x7ff9ced3b07e in _hashmap_free /systemd-meson-build/../build/src/basic/hashmap.c:888:17
08:53:20 [  172.642376] systemd-homed[331]:     #7 0x55c783839758 in hashmap_free /systemd-meson-build/../build/src/basic/hashmap.h:102:24
08:53:20 [  172.643172] systemd-homed[331]:     #8 0x55c783839758 in manager_free /systemd-meson-build/../build/src/home/homed-manager.c:270:9
08:53:20 [  172.644046] systemd-homed[331]:     #9 0x55c783856646 in manager_freep /systemd-meson-build/../build/src/home/homed-manager.h:76:1
08:53:20 [  172.645723] systemd-homed[331]:     #10 0x55c783856646 in run /systemd-meson-build/../build/src/home/homed.c:49:1
08:53:20 [  172.646530] systemd-homed[331]:     #11 0x55c783856646 in main /systemd-meson-build/../build/src/home/homed.c:51:1
08:53:20 [  172.647483] systemd-homed[331]:     #12 0x7ff9cde77b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
08:53:20 [  172.649128] systemd-homed[331]:     #13 0x55c78380882d in _start (/usr/lib/systemd/systemd-homed+0x5582d)
08:53:20 [  172.649947] systemd-homed[331]: 0x61c0000006dc is located 1628 bytes inside of 1800-byte region [0x61c000000080,0x61c000000788)
08:53:20 [  172.650808] systemd-homed[331]: freed by thread T0 here:
08:53:20 [  172.749611] systemd-homed[331]:     #0 0x7ff9cf647c49 in __interceptor_free (/usr/lib/clang/13.0.0/lib/linux/libclang_rt.asan-x86_64.so+0xf7c49)
08:53:20 [  172.750036] systemd-homed[331]:     #1 0x7ff9ceee758a in bus_free /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:226:16
08:53:20 [  172.750929] systemd-homed[331]:     #2 0x7ff9ceee65fa in sd_bus_unref /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1798:1
08:53:20 [  172.752716] systemd-homed[331]:     #3 0x7ff9ceee675a in sd_bus_close_unref /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1775:16
08:53:20 [  172.753630] systemd-homed[331]:     #4 0x7ff9ceee675a in sd_bus_flush_close_unref /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1786:16
08:53:20 [  172.754820] systemd-homed[331]:     #5 0x55c78383941d in manager_free /systemd-meson-build/../build/src/home/homed-manager.c:256:9
08:53:20 [  172.755391] systemd-homed[331]:     #6 0x55c783856646 in manager_freep /systemd-meson-build/../build/src/home/homed-manager.h:76:1
08:53:20 [  172.756248] systemd-homed[331]:     #7 0x55c783856646 in run /systemd-meson-build/../build/src/home/homed.c:49:1
08:53:20 [  172.757155] systemd-homed[331]:     #8 0x55c783856646 in main /systemd-meson-build/../build/src/home/homed.c:51:1
08:53:20 [  172.758928] systemd-homed[331]:     #9 0x7ff9cde77b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
08:53:20 [  172.759788] systemd-homed[331]: previously allocated by thread T0 here:
08:53:20 [  172.832507] systemd-homed[331]:     #0 0x7ff9cf647f09 in __interceptor_malloc (/usr/lib/clang/13.0.0/lib/linux/libclang_rt.asan-x86_64.so+0xf7f09)
08:53:20 [  172.832889] systemd-homed[331]:     #1 0x7ff9ceed7e10 in malloc_multiply /systemd-meson-build/../build/src/basic/alloc-util.h:103:16
08:53:20 [  172.833785] systemd-homed[331]:     #2 0x7ff9ceed7e10 in sd_bus_new /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:236:13
08:53:20 [  172.835605] systemd-homed[331]:     #3 0x7ff9ceee2199 in sd_bus_open_system_with_description /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1291:13
08:53:20 [  172.836464] systemd-homed[331]:     #4 0x7ff9ceee2b2a in sd_bus_open_system /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1322:16
08:53:20 [  172.837396] systemd-homed[331]:     #5 0x7ff9ceef84f1 in bus_default /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3899:13
08:53:20 [  172.839146] systemd-homed[331]:     #6 0x7ff9ceef833a in sd_bus_default_system /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3912:16
08:53:20 [  172.840000] systemd-homed[331]:     #7 0x55c783841c6f in manager_connect_bus /systemd-meson-build/../build/src/home/homed-manager.c:947:13
08:53:20 [  172.840910] systemd-homed[331]:     #8 0x55c78383e568 in manager_startup /systemd-meson-build/../build/src/home/homed-manager.c:1580:13
08:53:20 [  172.842690] systemd-homed[331]:     #9 0x55c7838564da in run /systemd-meson-build/../build/src/home/homed.c:38:13
08:53:20 [  172.843605] systemd-homed[331]:     #10 0x55c7838564da in main /systemd-meson-build/../build/src/home/homed.c:51:1
08:53:20 [  172.844575] systemd-homed[331]:     #11 0x7ff9cde77b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
08:53:20 [  172.926315] systemd-homed[331]: SUMMARY: AddressSanitizer: heap-use-after-free /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3592:21 in bus_pid_changed
08:53:20 
08:53:20 
08:53:20 Dec 14 07:34:16 H systemd-homed[331]: ==331==ERROR: AddressSanitizer: heap-use-after-free on address 0x61c0000006dc at pc 0x7ff9ceed869c bp 0x7ffd6be79d10 sp 0x7ffd6be79d08
08:53:20 Dec 14 07:34:16 H systemd-homed[331]: READ of size 4 at 0x61c0000006dc thread T0
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #0 0x7ff9ceed869b in bus_pid_changed /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3592:21
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #1 0x7ff9ceea9ab5 in sd_bus_emit_object_removed /systemd-meson-build/../build/src/libsystemd/sd-bus/bus-objects.c:2704:9
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #2 0x55c7838111d7 in bus_home_emit_remove /systemd-meson-build/../build/src/home/homed-home-bus.c:953:13
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #3 0x55c7838125c5 in home_free /systemd-meson-build/../build/src/home/homed-home.c:180:24
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #4 0x55c78384aae8 in __unique_prefix_static_free_wrapper14 /systemd-meson-build/../build/src/home/homed-manager.c:69:1
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #5 0x7ff9ced3b691 in _hashmap_clear /systemd-meson-build/../build/src/basic/hashmap.c:919:33
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #6 0x7ff9ced3b07e in _hashmap_free /systemd-meson-build/../build/src/basic/hashmap.c:888:17
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #7 0x55c783839758 in hashmap_free /systemd-meson-build/../build/src/basic/hashmap.h:102:24
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #8 0x55c783839758 in manager_free /systemd-meson-build/../build/src/home/homed-manager.c:270:9
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #9 0x55c783856646 in manager_freep /systemd-meson-build/../build/src/home/homed-manager.h:76:1
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #10 0x55c783856646 in run /systemd-meson-build/../build/src/home/homed.c:49:1
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #11 0x55c783856646 in main /systemd-meson-build/../build/src/home/homed.c:51:1
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #12 0x7ff9cde77b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #13 0x55c78380882d in _start (/usr/lib/systemd/systemd-homed+0x5582d)
08:53:20 Dec 14 07:34:17 H systemd-homed[331]: 0x61c0000006dc is located 1628 bytes inside of 1800-byte region [0x61c000000080,0x61c000000788)
08:53:20 Dec 14 07:34:17 H systemd-homed[331]: freed by thread T0 here:
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #0 0x7ff9cf647c49 in __interceptor_free (/usr/lib/clang/13.0.0/lib/linux/libclang_rt.asan-x86_64.so+0xf7c49)
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #1 0x7ff9ceee758a in bus_free /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:226:16
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #2 0x7ff9ceee65fa in sd_bus_unref /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1798:1
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #3 0x7ff9ceee675a in sd_bus_close_unref /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1775:16
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #4 0x7ff9ceee675a in sd_bus_flush_close_unref /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1786:16
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #5 0x55c78383941d in manager_free /systemd-meson-build/../build/src/home/homed-manager.c:256:9
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #6 0x55c783856646 in manager_freep /systemd-meson-build/../build/src/home/homed-manager.h:76:1
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #7 0x55c783856646 in run /systemd-meson-build/../build/src/home/homed.c:49:1
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #8 0x55c783856646 in main /systemd-meson-build/../build/src/home/homed.c:51:1
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #9 0x7ff9cde77b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
08:53:20 Dec 14 07:34:17 H systemd-homed[331]: previously allocated by thread T0 here:
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #0 0x7ff9cf647f09 in __interceptor_malloc (/usr/lib/clang/13.0.0/lib/linux/libclang_rt.asan-x86_64.so+0xf7f09)
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #1 0x7ff9ceed7e10 in malloc_multiply /systemd-meson-build/../build/src/basic/alloc-util.h:103:16
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #2 0x7ff9ceed7e10 in sd_bus_new /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:236:13
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #3 0x7ff9ceee2199 in sd_bus_open_system_with_description /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1291:13
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #4 0x7ff9ceee2b2a in sd_bus_open_system /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:1322:16
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #5 0x7ff9ceef84f1 in bus_default /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3899:13
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #6 0x7ff9ceef833a in sd_bus_default_system /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3912:16
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #7 0x55c783841c6f in manager_connect_bus /systemd-meson-build/../build/src/home/homed-manager.c:947:13
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #8 0x55c78383e568 in manager_startup /systemd-meson-build/../build/src/home/homed-manager.c:1580:13
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #9 0x55c7838564da in run /systemd-meson-build/../build/src/home/homed.c:38:13
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #10 0x55c7838564da in main /systemd-meson-build/../build/src/home/homed.c:51:1
08:53:20 Dec 14 07:34:17 H systemd-homed[331]:     #11 0x7ff9cde77b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
08:53:20 Dec 14 07:34:17 H systemd-homed[331]: SUMMARY: AddressSanitizer: heap-use-after-free /systemd-meson-build/../build/src/libsystemd/sd-bus/sd-bus.c:3592:21 in bus_pid_changed
08:53:20 
08:53:20 
08:53:20  ____________________________________________
08:53:20 / Found   2 sanitizer errors (  2 ASan,   0  \
08:53:20 | UBSan,   0 MSan). Looks like you need to   |
08:53:20 \ look at the log                            /
08:53:20  --------------------------------------------
```

</details>

**Comment by yuwata** [comment]
Updated. PTAL.

File: src/home/homed-manager.c [hunk 1]
```diff
@@ -265,7 +265,7 @@ Manager* manager_free(Manager *m) {
         m->deferred_auto_login_event_source = sd_event_source_unref(m->deferred_auto_login_event_source);
         m->rebalance_event_source = sd_event_source_unref(m->rebalance_event_source);
 
-        sd_event_unref(m->event);
+        m->event = sd_event_unref(m->event);
 
         hashmap_free(m->homes_by_uid);
```
Comment (keszybz) [inline src/home/homed-manager.c]: What about those here? Shouldn't those be nullified too?

Comment (yuwata) [reply src/home/homed-manager.c]: Indeed. Addressed.

**Review by bluca — APPROVED** [review]
