### PR TITLE
network: fix routing policy rule issue #11280

### LINKED ISSUE #11280: RoutingPolicyRule does not always apply - applies alternately?
**systemd version the issue has been seen with**
> 239.303-1 (had noticed the issue in earlier versions too)

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Routing rules should remain constantly on networkd restart

**Unexpected behaviour you saw**
 >  Routing rules appear / disappear alternately on networkd restart

**Steps to reproduce the problem**

**Note:** This is long description and seems complicated but if you are comfortable with ip rules then its not complicated. To easily understand please focus on RoutingPolicyRule sections and not Route sections.

I have following config with 1 LAN and 3 WAN connection. 1 of the WAN connection is PPPoE based, however that should not be relevant here.

**25-eth0.network (LAN connection)**
```
[Match]
MACAddress=aa:bb:cc:dd:ee:f1

[Network]
ConfigureWithoutCarrier=true
Address=192.168.0.250/24
```

**25-eth1.network (tata WAN - associated route table number 101)**
```
[Match]
MACAddress=aa:bb:cc:dd:ee:f2

[Network]
ConfigureWithoutCarrier=true
Address=1.1.1.58/30

[Route]
Gateway=1.1.1.57
Metric=20

[Route]
Gateway=1.1.1.57
Table=101
Metric=20

[Route]
Gateway=1.1.1.57
Destination=1.1.1.56/30
Table=101
Metric=20

[RoutingPolicyRule]
From=1.1.1.58
Table=101
Priority=29001

[RoutingPolicyRule]
To=1.1.1.56/30
Table=101
Priority=29002

[RoutingPolicyRule]
FirewallMark=0x101
Table=101
Priority=30001
```

**25-eth2.network (airtel - associated route table number 102)**
```
[Match]
MACAddress=aa:bb:cc:dd:ee:f3

[Network]
ConfigureWithoutCarrier=true
Address=192.168.1.2/24

[Route]
Gateway=192.168.1.1
Metric=20

[Route]
Gateway=192.168.1.1
Table=102
Metric=20

[Route]
Gateway=192.168.1.1
Destination=192.168.1.0/24
Table=102
Metric=20

[RoutingPolicyRule]
From=192.168.1.2
Table=102
Priority=29003

[RoutingPolicyRule]
To=192.168.1.0/24
Table=102
Priority=29004

[RoutingPolicyRule]
FirewallMark=0x102
Table=102
Priority=30002
```

**25-eth3.network (pppoe / pppoelan - associated route table numbers 103 / 104)**

```
[Match]
MACAddress=aa:bb:cc:dd:ee:f4

[Network]
ConfigureWithoutCarrier=true
Address=192.168.5.2/24

[Route]
Gateway=192.168.5.1
Metric=20

[Route]
Gateway=192.168.5.1
Table=104
Metric=20

[Route]
Gateway=192.168.5.1
Destination=192.168.5.0/24
Table=104
Metric=20

[RoutingPolicyRule]
From=192.168.5.2
Table=104
Priority=29005

[RoutingPolicyRule]
To=192.168.5.0/24
Table=104
Priority=29006

[RoutingPolicyRule]
FirewallMark=0x104
Table=104
Priority=30004

# pppd places routes in this table after connection
# is established over PPPoE
[RoutingPolicyRule]
FirewallMark=0x103
Table=103
Priority=30003
```

Now lets see what routing policy rules are created when systemd-networkd starts.

```
$ systemctl start systemd-networkd
$ ip ru l
0:      from all lookup local
28995:  from all to 10.10.10.10 lookup pppoe
28996:  from 11.11.11.11 lookup pppoe
28997:  from all to 192.168.0.0/24 lookup main
29001:  from 1.1.1.58 lookup tata
29002:  from all to 1.1.1.56/30 lookup tata
29003:  from 192.168.1.2 lookup airtel
29004:  from all to 192.168.1.0/24 lookup airtel
29005:  from 192.168.5.2 lookup pppoelan
29006:  from all to 192.168.5.0/24 lookup pppoelan
30001:  from all fwmark 0x101 lookup tata
30002:  from all fwmark 0x102 lookup airtel
30003:  from all fwmark 0x103 lookup pppoe
30004:  from all fwmark 0x104 lookup pppoelan
32766:  from all lookup main
32767:  from all lookup default
```

First three rules above are added by pppd (ip-up script) which you may please ignore. But rest are added by systemd-networkd.

**As we can see, all rules are above are as expected.**

Now lets restart systemd-networkd and check what happens:

```
$ systemctl restart systemd-networkd
$ ip ru l
0:      from all lookup local
28995:  from all to 10.10.10.10 lookup pppoe
28996:  from 11.11.11.11 lookup pppoe
28997:  from all to 192.168.0.0/24 lookup main
29005:  from 192.168.5.2 lookup pppoelan
29006:  from all to 192.168.5.0/24 lookup pppoelan
30001:  from all fwmark 0x101 lookup tata
30002:  from all fwmark 0x102 lookup airtel
30003:  from all fwmark 0x103 lookup pppoe
30004:  from all fwmark 0x104 lookup pppoelan
32766:  from all lookup main
32767:  from all lookup default
```

**Boom!** IP based rules of tata and airtel vanish!! (but fwmark based rules remain)

Lets restart systemd-networkd one more time and check what happens:

```
$ systemctl restart systemd-networkd
$ ip ru l
0:      from all lookup local
28995:  from all to 10.10.10.10 lookup pppoe
28996:  from 11.11.11.11 lookup pppoe
28997:  from all to 192.168.0.0/24 lookup main
29001:  from 1.1.1.58 lookup tata
29002:  from all to 1.1.1.56/30 lookup tata
29003:  from 192.168.1.2 lookup airtel
29004:  from all to 192.168.1.0/24 lookup airtel
29005:  from 192.168.5.2 lookup pppoelan
29006:  from all to 192.168.5.0/24 lookup pppoelan
30001:  from all fwmark 0x101 lookup tata
30002:  from all fwmark 0x102 lookup airtel
30003:  from all fwmark 0x103 lookup pppoe
30004:  from all fwmark 0x104 lookup pppoelan
32766:  from all lookup main
32767:  from all lookup default
```

**BINGO!! And the rules are back!!!**

This is consistent and alternate. One restart they disappear and 2nd restart they appear.

journalctl shows this: (with coredump)
```
$ journalctl --file /var/log/journal/XXXXXXX/system.journal -n 100  -u systemd-networkd.service
-- Logs begin at Mon 2018-12-24 10:10:51 IST, end at Thu 2018-12-27 16:43:05 IST. --
Dec 27 16:28:01 myfw systemd-networkd[31226]: eth0: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: lo: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: eth1: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: ppp1: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: eth0: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: lo: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: ppp1: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: eth0: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: lo: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: ppp1: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: lo: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: eth2: Could not drop routing policy rule: No such file or directory
Dec 27 16:28:01 myfw systemd-networkd[31226]: eth2: Could not drop routing policy rule: No such file or directory
Dec 27 16:28:02 myfw systemd-networkd[31226]: eth0: Configured
Dec 27 16:28:06 myfw systemd[1]: Stopping Network Service...
Dec 27 16:28:06 myfw systemd[1]: systemd-networkd.service: Main process exited, code=dumped, status=11/SEGV
Dec 27 16:28:06 myfw systemd[1]: systemd-networkd.service: Failed with result 'core-dump'.
Dec 27 16:28:06 myfw systemd[1]: Stopped Network Service.
Dec 27 16:28:06 myfw systemd[1]: Starting Network Service...
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth3: Gained IPv6LL
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth2: Gained IPv6LL
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth1: Gained IPv6LL
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth0: Gained IPv6LL
Dec 27 16:28:06 myfw systemd-networkd[31243]: Enumeration completed
Dec 27 16:28:06 myfw systemd[1]: Started Network Service.
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth1: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth0: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: lo: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: ppp1: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth2: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth1: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth0: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: lo: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: ppp1: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth0: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: lo: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: ppp1: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: lo: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: ppp1: Link is not managed by us
Dec 27 16:28:07 myfw systemd-networkd[31243]: eth0: Configured
Dec 27 16:28:18 myfw systemd-networkd[31243]: eth3: Configured
Dec 27 16:28:18 myfw systemd-networkd[31243]: eth2: Configured
Dec 27 16:28:18 myfw systemd-networkd[31243]: eth1: Configured
Dec 27 16:29:04 myfw systemd[1]: Stopping Network Service...
Dec 27 16:29:05 myfw systemd[1]: systemd-networkd.service: Main process exited, code=dumped, status=11/SEGV
Dec 27 16:29:05 myfw systemd[1]: systemd-networkd.service: Failed with result 'core-dump'.
Dec 27 16:29:05 myfw systemd[1]: Stopped Network Service.
Dec 27 16:29:05 myfw systemd[1]: Starting Network Service...
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth3: Gained IPv6LL
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth2: Gained IPv6LL
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth1: Gained IPv6LL
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth0: Gained IPv6LL
Dec 27 16:29:05 myfw systemd-networkd[31303]: Enumeration completed
Dec 27 16:29:05 myfw systemd[1]: Started Network Service.
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth1: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth2: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: ppp1: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: lo: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth0: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth1: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: ppp1: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: lo: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth0: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: ppp1: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: lo: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth0: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: ppp1: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: lo: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth2: Could not drop routing policy rule: No such file or directory
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth2: Could not drop routing policy rule: No such file or directory
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth0: Configured
Dec 27 16:29:09 myfw systemd[1]: Stopping Network Service...
Dec 27 16:29:09 myfw systemd[1]: systemd-networkd.service: Main process exited, code=dumped, status=11/SEGV
Dec 27 16:29:09 myfw systemd[1]: systemd-networkd.service: Failed with result 'core-dump'.
Dec 27 16:29:09 myfw systemd[1]: Stopped Network Service.
Dec 27 16:29:09 myfw systemd[1]: Starting Network Service...
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth3: Gained IPv6LL
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth2: Gained IPv6LL
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth1: Gained IPv6LL
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth0: Gained IPv6LL
Dec 27 16:29:09 myfw systemd-networkd[31323]: Enumeration completed
Dec 27 16:29:09 myfw systemd[1]: Started Network Service.
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth0: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth2: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth1: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: lo: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: ppp1: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth0: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth1: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: lo: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: ppp1: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth0: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: lo: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: ppp1: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: lo: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: ppp1: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth0: Configured
Dec 27 16:29:21 myfw systemd-networkd[31323]: eth3: Configured
Dec 27 16:29:21 myfw systemd-networkd[31323]: eth2: Configured
Dec 27 16:29:21 myfw systemd-networkd[31323]: eth1: Configured
```

**Its a live system so it would be difficult for me to run gdb on it.**

But I hope that above information does provide some useful hints.

### PR DESCRIPTION
**Pull request by yuwata**
cc @ssahani, @amishmm, and @CharlesMCruz.

Fixes #11280.

### CODE REVIEW

**Comment by amishmm** [comment]
I dont have any feedback about code, as i dont know about internal functions.

But may be the title of PR should include word "rule".

"network: fix routing policy **rule** issue"

because that will probably go in to final changelog

File: src/network/networkd-routing-policy-rule.c [hunk 1]
```diff
@@ -1235,18 +1235,40 @@ int routing_policy_load_rules(const char *state_file, Set **rules) {
...
 
         SET_FOREACH(rule, m->rules_saved, i) {
+                bool found = false;
+
                 existing = set_get(m->rules_foreign, rule);
                 if (!existing)
                         continue; /* Saved rule does not exist anymore. */
 
+                HASHMAP_FOREACH(l, m->links, j) {
+                        if (!link->network)
```
Comment (keszybz) [inline src/network/networkd-routing-policy-rule.c]: This is wrong — `l` is never used.

I think it'd make a lot of sense to split out this internal loop over links into a separate function, `manager_links_have_routing_rule(Manager *m, const Rule *rule)` or smth. Then `found` will not have to be defined because you can return `true` or `false` directly.

Comment (yuwata) [reply src/network/networkd-routing-policy-rule.c]: Ouch!

**Comment by yuwata** [comment]
@keszybz Thank you for the review. Now the internal loop is moved to new `manager_links_have_routing_rule()`. PTAL.

File: src/network/networkd-routing-policy-rule.c [hunk 2]
```diff
@@ -1244,15 +1244,18 @@ void routing_policy_rule_purge(Manager *m, Link *link) {
...
-                        link->routing_policy_rule_remove_messages++;
+                r = routing_policy_rule_remove(rule, link, NULL);
+                if (r < 0) {
+                        log_warning_errno(r, "Could not remove routing policy rules: %m");
+                        continue;
                 }
+
+                link->routing_policy_rule_remove_messages++;
+
+                assert(set_remove(m->rules_foreign, existing) == existing);
```
Comment (poettering) [inline src/network/networkd-routing-policy-rule.c]: must be assert_se() otherwise the full expression might disappear if people use -DNDEBUG

**Comment by yuwata** [comment]
Updated. The change is only `assert()` -> `assert_se()`.

**Comment by keszybz** [comment]
```
======================================================================
FAIL: test_routing_policy_rule_issue_11280 (__main__.NetworkdNetWorkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 692, in test_routing_policy_rule_issue_11280
    self.assertRegex(output, '111:	from 192.168.100.18 tos (0x08|throughput) iif test1 oif test1 lookup 7')
AssertionError: Regex didn't match: '111:\tfrom 192.168.100.18 tos (0x08|throughput) iif test1 oif test1 lookup 7' not found in ''

----------------------------------------------------------------------
```

**Comment by yuwata** [comment]
Hmm??? Let's restart the CI. Just rebased.

**Comment by poettering** [comment]
lgtm, if the CI also likes it
