### PR TITLE
network: do not bring down bonding port on reconfigure

### LINKED ISSUE #31165: Reconfiguring network brings down bonded interface
### systemd version the issue has been seen with

253.5 

### Used distribution

Ubuntu 22.04

### Linux kernel version used

5.15.0-92-generic

### CPU architectures issue was seen on

x86_64

### Component

networkctl, systemd-networkd

### Expected behaviour you didn't see

When (re)configuring an interface I would expect it to stay online when not making any changes.

### Unexpected behaviour you saw

An interface which is part of a bond is brought down by systemd-networkd when reconfiguring it, restarting systemd-networkd or running netplan apply even if we make no changes.

### Steps to reproduce the problem

I upgraded a test machine's systemd towards v253.5 to ensure [this](https://github.com/systemd/systemd-stable/commit/9f913d37a01f71e559d099bff280827f8817d8c5) fix would be present for [this](https://github.com/systemd/systemd/issues/25067) issue (the machine is running Ubuntu 22.04).

I found the issue by continuously running `netplan apply` without making any changes. Each time it took down the interface and (as a result) all interfaces dependent on it. After some more debugging I figured out `networkctl reconfigure pn1` would cause the same behaviour. At first I expected it to be a quirk of our Mellanox NIC's (ConnectX-6), but then I found this in the logs when running reconfigure:
```
Jan 31 15:43:46 unique-slug systemd-networkd[2430]: pn1: Bringing link down
```

E.g. systemd-networkd purposely taking down the link, so it seems not related to our Mellanox NIC's.

### Additional program output to the terminal or log subsystem illustrating the issue

Logs: https://gist.github.com/Wouter0100/1596e8224bd170a094d4de3baf5e7f61
Config of systemd (generated by our netplan config): https://gist.github.com/Wouter0100/cec375057eeb1e217c62ae5f8eb5973b

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #31165.

### CODE REVIEW

File: src/network/networkd-setlink.c [hunk 1]
```diff
@@ -559,6 +550,15 @@ static int link_is_ready_to_set_link(Link *link, Request *req) {
                         return -EALREADY; /* indicate to cancel the request. */
                 }
 
+                /* Do not check link->set_flgas_messages here, as it is ok even if link->flags is outdated,
```
Comment (poettering) [inline src/network/networkd-setlink.c]: might as well fix the "flgas" typo here
