### PR TITLE
journal: Avoid duplicated call to get cgroup path from pid

### LINKED ISSUE #5058: journald: cg_pid_get_path_shifted() shall be invoked only once
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> v232 and upstream master

### Used distribution

> embedded environment on ARM and x64

### Expected behavior

As discussed in the systemd-devel mailing list,
(https://lists.freedesktop.org/archives/systemd-devel/2016-December/038051.html)
we found that the function cg_pid_get_path_shifted() in journald-server.c is invoked twice and is heavy on embedded environment.

From the reply,
(https://lists.freedesktop.org/archives/systemd-devel/2016-December/038052.html)
my understanding is the function shall be only invoked once by passing the value got before.

By doing this, it should reduce the cpu time used by journald.

### PR DESCRIPTION
**Pull request by namhyung**
The cg_pid_get_path_shifted() is called twice during
server_dispatch_message().  We can get rid of the second by passing the
path to dispatch_message_real().  Fixes #5058.

### CODE REVIEW

File: src/journal/journald-server.c [hunk 1]
```diff
@@ -1175,7 +1180,10 @@ void server_dispatch_message(
                                       NULL);
 
 finish:
-        dispatch_message_real(s, iovec, n, m, ucred, tv, label, label_len, unit_id, priority, object_pid);
+        /* restore cgroup path for logging */
+        if (c)
+                *c = '/';
+        dispatch_message_real(s, iovec, n, m, ucred, tv, label, label_len, unit_id, priority, object_pid, path);
```
Comment (martinpitt) [inline src/journal/journald-server.c:1188]: Is it really safe to pass `path` here if `c == NULL`? In that case it was not a ≥ 3 component path and `path` contains something undefined. Maybe pass `c ? path : NULL`?

I don't know the details of this though, so this could well work fine.

File: src/journal/journald-server.c [hunk 2]
```diff
@@ -846,7 +847,10 @@ static void dispatch_message_real(
                 }
 #endif
 
-                r = cg_pid_get_path_shifted(ucred->pid, s->cgroup_root, &c);
+                if (cgroup)
+                        c = cgroup, r = 0;
```
Comment (martinpitt) [inline src/journal/journald-server.c]: This comma syntax, while legal C, is a bit rare and misleading IMHO. Perhaps move the `if (r >= 0)` into the `else` branch instead?

Comment (namhyung) [reply src/journal/journald-server.c]: I'm not sure how I can move it into the else branch.  I just wanted a minimal change - what about making the comma expression separate lines?

File: src/journal/journald-server.c (hunk 1 above)
Comment (namhyung) [reply src/journal/journald-server.c:1188]: But passing NULL will use same cgroup path anyway since `cg_pid_get_path_shifted()` in `dispatcch_message_real()` will return the same path for the pid IMHO.

Comment (martinpitt) [reply src/journal/journald-server.c:1188]: I was thinking about what happens if `path` contains two components, and the code above didn't find a third `/'. But indeed, then we'd never truncate `path` in the first place, and line 1185 would just overwrite an existing `/` with another `/`, so should be a no-op. So this should be fine after all.

File: src/journal/journald-server.c (hunk 2 above)
Comment (martinpitt) [reply src/journal/journald-server.c]: Hmm, how about just setting `r = 0` before the `if`?

Comment (namhyung) [reply src/journal/journald-server.c]: That would work, will change. Thanks!

**Comment by namhyung** [comment]
I updated the code to move `r = 0;` before the if statement.  Sorry for pushing it multiple times.

**Comment by namhyung** [comment]
@martinpitt ping!

**Comment by namhyung** [comment]
Thanks! :)
