### PR TITLE
 core: make ExecRuntime be manager managed object

### LINKED ISSUE #7790: daemon-reload + restart of service using JoinsNamespaceOf broken
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 236

### Used distribution

> Archlinux

### Unexpected behaviour you saw

> A service that uses JoinsNamespaceOf will break after executing `systemctl daemon-reload` and restarting the service saying 

```
Failed to set up mount namespacing: No such file or directory
Failed at step NAMESPACE spawning /bin/sh: No such file or directory
```

### In case of bug report: Steps to reproduce the problem

> Create two services, `test-base.service`:
```
[Unit]
Description=test base

[Service]
PrivateTmp=true
ExecStart=/bin/sh -c 'sleep 999'

[Install]
WantedBy=multi-user.target
```
> `test-dep.service`
```
[Unit]
Description=test dep
JoinsNamespaceOf=test-base.service

[Service]
PrivateTmp=true
ExecStart=/bin/sh -c 'sleep 999'

[Install]
WantedBy=multi-user.target
```

> Now start both test-base and test-dep (in that order). Everything works fine, and test-dep can be restarted. Now execute `systemctl daemon-reload; systemctl restart test-dep`. The test-dep fails with the above error message about the namespace, presumable because the daemon-reload makes systemd 'forget' the namespace

### PR DESCRIPTION
**Pull request by yuwata**
Before this, `ExecRuntime` objects are owned by units. However, they are shared with other units specified in `JoinsNamespaceOf=`. Thus, by serialization/deserialization process, its sharing information, more specifically, reference counter is lost, and causes issue #7790.

This makes `ExecRuntime` objects be managed by manager, and changes the serialization/deserialization process.

Fixes #7790.

### CODE REVIEW

**Comment by yuwata** [comment]
Note that because of #7790, when upgrade systemd from the one without this PR, all information about `ExecRuntime` in serialized text is simply ignored. I think we cannot safely migrate them.

**Comment by keszybz** [comment]
Looks all good, but I have one question: cleanup is not performed when the deserialized objects are dropped. This means that if the deserialization fails, we'll leave stuff around. This *might* be the correct solution, I'm not quite sure. Can you comment a bit on this?

**Comment by yuwata** [comment]
After re-consider this, now I think we should support to migrate from the current(v237) serialized text at least the current buggy level, rather than completely dropping the current format. This is harmless when the units do not use `JoinsNamespaceOf=`. Of course, when several units use the setting, then it causes #7790, but I expect potentially it does not provide no new bugs.

**Comment by keszybz** [comment]
Thanks. I agree it'd be great to provide an upgrade path. I was considering how we'd handle upgrades without it, and there's really no way. We basically always need to support live upgrades. They might sometimes be a bit lossy, but the machine and various services must generally stay up.

**Comment by yuwata** [comment]
OK. Thanks. So, I will update this in that way.

**Comment by yuwata** [comment]
Updated. Now, (I expect that) `ExecRuntime` objects can be migrated from old serialization format.

Sorry, I have not tested this yet. But I want to see the CIs pass or not. After testing, I will remove 'dont-merge' tag. Thank you.

File: src/core/execute.c [hunk 1]
```diff
@@ -4523,224 +4524,413 @@ int exec_command_append(ExecCommand *c, const char *path, ...) {
...
-        assert(rt);
-        assert(c);
+        assert(m);
         assert(id);
 
-        if (*rt)
-                return 1;
+        r = hashmap_ensure_allocated(&m->exec_runtime_by_id, &string_hash_ops);
+        if (r < 0)
+                return r;
```
Comment (keszybz) [inline src/core/execute.c]: There's an inconsistency here: all checks below use log_oom(), but this one is silent. I think it'd be OK to make this function not log at all and require the callers to log if necessary.

Comment (yuwata) [reply src/core/execute.c]: Indeed. Fixed. Thank you.

**Comment by yuwata** [comment]
Updated. Now migration from old serialization texts works fine.
Fortunately, if the units related with `JoinsNamespaceOf=` do not use `PrivateNetwork=`, then migration works fine :-)
Only the case that `JoinsNamespaceOf=` with `PrivateNetwork=`, we cannot safely migrate the `ExecRuntime` parameters, and the corresponding units may need to restart after updating systemd.

Please take a look. Thank you.

File: src/core/unit.c [hunk 2]
```diff
@@ -4695,15 +4679,12 @@ int unit_setup_exec_runtime(Unit *u) {
...
         HASHMAP_FOREACH_KEY(v, other, u->dependencies[UNIT_JOINS_NAMESPACE_OF], i) {
-
-                *rt = unit_get_exec_runtime(other);
-                if (*rt) {
-                        exec_runtime_ref(*rt);
-                        return 0;
-                }
+                r = exec_runtime_acquire(u->manager, NULL, other->id, false, rt);
+                if (r == 1)
+                        return 1;
```
Comment (keszybz) [inline src/core/unit.c:4684]: I think that this needs a log line in case `r < 0`. This shouldn't happen, but if it does, `exec_runtime_acquire` does not do any logging on its own, so we wouldn't ever know.

Comment (yuwata) [reply src/core/unit.c:4684]: Yeah, that is true in general. But the function returns only 0 or 1 when the fourth parameter is false...

Comment (keszybz) [reply src/core/unit.c:4684]: OK. It seems all the callers log the failure at some point.
