### PR TITLE
backlight: support multiple graphics cards system

### LINKED ISSUE #24223: systemd-backlight service not restoring backlight brightess on amdgpu_bl0
### systemd version the issue has been seen with

251

### Used distribution

Arch Linux

### Linux kernel version used

5.18.16-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Backlight setting restored after rebooting.

### Unexpected behaviour you saw

Backlight setting was never restored. Screen brightness is always at maximum after rebooting.

### Steps to reproduce the problem

On the following hardware:
```
        Manufacturer: LENOVO
        Product Name: 82K8
        Version: Legion S7 15ACH6
```
Change screen backlight setting and reboot.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Aug 05 20:26:20 hemera systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0...
Aug 05 20:26:20 hemera systemd-backlight[674]: amdgpu_bl0: Maximum brightness is 255
Aug 05 20:26:20 hemera systemd-backlight[674]: sd-device-enumerator: Scan all dirs
Aug 05 20:26:20 hemera systemd-backlight[674]: sd-device-enumerator: Scanning /sys/bus
Aug 05 20:26:20 hemera systemd-backlight[674]: sd-device-enumerator: Scanning /sys/class
Aug 05 20:26:20 hemera systemd-backlight[674]: Skipping backlight device amdgpu_bl0, since device nvidia_wmi_ec_backlight is a platform device and takes prec>
Aug 05 20:26:20 hemera systemd[1]: Finished Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0.
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #24223.

### CODE REVIEW

File: src/backlight/backlight.c [hunk 1]
```diff
@@ -44,6 +44,47 @@ static int help(void) {
...
+                const char *s;
+                unsigned long c;
+
+                if (sd_device_get_sysattr_value(dev, "class", &s) < 0)
+                        continue;
+
+                if (safe_atolu(s, &c) < 0)
+                        continue;
+
+                if (c != 0x30000)
```
Comment (bluca) [inline src/backlight/backlight.c]: maybe add a define or at least a comment to explain what this number means?

File: src/backlight/backlight.c [hunk 2]
```diff
@@ -210,12 +215,13 @@ static int validate_device(sd_device *device) {
                 if (same_device(parent, other_parent) > 0) {
                         /* Both have the same PCI parent, that means we are out. */
                         if (DEBUG_LOGGING) {
-                                const char *other_sysname = NULL;
+                                const char *other_sysname = NULL, *other_type = NULL;
 
                                 (void) sd_device_get_sysname(other, &other_sysname);
+                                (void) sd_device_get_sysattr_value(other, "type", &other_type);
```
Comment (bluca) [inline src/backlight/backlight.c:281]: were these changes meant for the previous commit? same below

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
@bluca Thank you for the review. The above comments are addressed. Upgrading the green label.
