### PR TITLE
network: call ethtool after link is initialized by udevd

### LINKED ISSUE #22538: networkd does not reliably configure hot-plugged interface
**systemd version the issue has been seen with**
 > 250.3

**Used distribution**
 > Debian (unstable branch)

**Linux kernel version used** (`uname -a`)

 > `Linux ip-10-0-0-236 5.16.0-1-cloud-amd64 #1 SMP PREEMPT Debian 5.16.7-2 (2022-02-09) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > networkd applying .network configuration to hot-plugged interface

**Unexpected behaviour you saw**
 > networkd failed to associate interface with .network file. `networkctl` reports "Network File: n/a" and interface is not configured.

**Steps to reproduce the problem**
 > Construct a .network file matching a hot-pluggable interface that will configure higher level protocol (DHCP/IP, etc). Attach interface.

Two notable details:
1. This does not happen 100% of the time. However, it's pretty reliably reproducible. Guessing at least 30% of attachments are impacted.
2.  This seems to be a regression from systemd 249. I have not experienced it with that version and have been unable to trigger a reproduction with targeted attempts (running attach/test/detach a loop).

The .network file is:

```text
[Match]
Driver=ena

[Link]
MTUBytes=9001

[Network]
DHCP=yes
IPv6DuplicateAddressDetection=0
LLMNR=no

[DHCPv4]
UseHostname=no
```

When an interface is hotplugged and properly configured (the expected case), `networkctl status IFNAME` reports:
```text
admin@ip-10-0-0-80:~$ networkctl status ens6
● 3: ens6                                                                      
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/20-eni.network
                          Type: ether
                         State: routable (configured)
                  Online state: online                                         
             Alternative Names: enp0s6
                          Path: pci-0000:00:06.0
                        Driver: ena
                        Vendor: Amazon.com, Inc.
                         Model: Elastic Network Adapter (ENA)
                    HW Address: 02:3f:ef:3b:20:71
                           MTU: 9001 (min: 128, max: 9216)
                         QDisc: mq
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 2/2
                       Address: 10.0.0.8 (DHCP4 via 10.0.0.1)
                                2600:1f14:eeb:2203:5dbb:f7c8:9e47:822e
                                2600:1f14:eeb:2203:8ff0:610d:6df4:6b3e
                                fe80::3f:efff:fe3b:2071
                       Gateway: 10.0.0.1
                                fe80::8f:53ff:fe6f:64ef
                           DNS: 10.0.0.2
             Activation Policy: up
           Required For Online: yes
               DHCP4 Client ID: IAID:0x6618dd42/DUID
             DHCP6 Client IAID: 0x6618dd42
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab11b98c8625365b63860000
```

And the following is logged to the journal:
```text
Feb 16 17:01:32 ip-10-0-0-220 kernel: pci 0000:00:06.0: [1d0f:ec20] type 00 class 0x020000
Feb 16 17:01:32 ip-10-0-0-220 kernel: pci 0000:00:06.0: reg 0x10: [mem 0x00000000-0x00003fff]
Feb 16 17:01:32 ip-10-0-0-220 kernel: pci 0000:00:06.0: reg 0x18: [mem 0x00000000-0x000fffff pref]
Feb 16 17:01:32 ip-10-0-0-220 kernel: pci 0000:00:06.0: reg 0x20: [mem 0x00000000-0x0000ffff]
Feb 16 17:01:32 ip-10-0-0-220 kernel: pci 0000:00:06.0: BAR 2: assigned [mem 0xc0000000-0xc00fffff pref]
Feb 16 17:01:32 ip-10-0-0-220 kernel: pci 0000:00:06.0: BAR 4: assigned [mem 0xc0100000-0xc010ffff]
Feb 16 17:01:32 ip-10-0-0-220 kernel: pci 0000:00:06.0: BAR 0: assigned [mem 0xc0110000-0xc0113fff]
Feb 16 17:01:32 ip-10-0-0-220 kernel: ena 0000:00:06.0: enabling device (0000 -> 0002)
Feb 16 17:01:32 ip-10-0-0-220 kernel: ena 0000:00:06.0: ENA device version: 0.10
Feb 16 17:01:32 ip-10-0-0-220 kernel: ena 0000:00:06.0: ENA controller version: 0.0.1 implementation version 1
Feb 16 17:01:32 ip-10-0-0-220 systemd-udevd[489]: Using default interface naming scheme 'v249'.
Feb 16 17:01:32 ip-10-0-0-220 kernel: ena 0000:00:06.0: Elastic Network Adapter (ENA) found at mem c0110000, mac addr 02:3f:ef:3b:20:71
Feb 16 17:01:32 ip-10-0-0-220 kernel: ena 0000:00:06.0 ens6: renamed from eth0
Feb 16 17:01:32 ip-10-0-0-220 systemd-networkd[365]: eth0: Interface name change detected, renamed to ens6.
Feb 16 17:01:32 ip-10-0-0-220 systemd-networkd[365]: ens6: Link UP
Feb 16 17:01:32 ip-10-0-0-220 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): ens6: link becomes ready
Feb 16 17:01:32 ip-10-0-0-220 systemd-networkd[365]: ens6: Gained carrier
Feb 16 17:01:33 ip-10-0-0-220 systemd-networkd[365]: ens6: Gained IPv6LL
Feb 16 17:01:33 ip-10-0-0-220 systemd-networkd[365]: ens6: DHCPv6 address 2600:1f14:eeb:2203:5dbb:f7c8:9e47:822e/128 (valid for 7min 30s, preferred for 2min 20s)
Feb 16 17:01:33 ip-10-0-0-220 systemd-networkd[365]: ens6: DHCPv6 address 2600:1f14:eeb:2203:8ff0:610d:6df4:6b3e/128 (valid for 7min 30s, preferred for 2min 20s)
Feb 16 17:01:35 ip-10-0-0-220 systemd-networkd[365]: ens6: DHCPv4 address 10.0.0.8/24 via 10.0.0.1
```

When an interface is hotplugged and configuration fails (the error case), the same output is:

```text
admin@ip-10-0-0-165:~$ networkctl status ens6
● 6: ens6                                                               
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: n/a
                          Type: ether
                         State: off (unmanaged)
                  Online state: unknown
             Alternative Names: enp0s6
                          Path: pci-0000:00:06.0
                        Driver: ena
                        Vendor: Amazon.com, Inc.
                         Model: Elastic Network Adapter (ENA)
              Hardware Address: 02:3f:ef:3b:20:71
                           MTU: 1500 (min: 128, max: 9216)
                         QDisc: noop
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 2/2
             Activation Policy: up
           Required For Online: yes
```

And the journal contains:
```text
Feb 15 23:11:56 ip-10-0-0-165 kernel: pci 0000:00:06.0: [1d0f:ec20] type 00 class 0x020000
Feb 15 23:11:56 ip-10-0-0-165 kernel: pci 0000:00:06.0: reg 0x10: [mem 0x00000000-0x00003fff]
Feb 15 23:11:56 ip-10-0-0-165 kernel: pci 0000:00:06.0: BAR 0: assigned [mem 0x80000000-0x80003fff]
Feb 15 23:11:56 ip-10-0-0-165 kernel: ena 0000:00:06.0: enabling device (0000 -> 0002)
Feb 15 23:11:56 ip-10-0-0-165 kernel: ena 0000:00:06.0: ENA device version: 0.10
Feb 15 23:11:56 ip-10-0-0-165 kernel: ena 0000:00:06.0: ENA controller version: 0.0.1 implementation version 1
Feb 15 23:11:56 ip-10-0-0-165 kernel: ena 0000:00:06.0: LLQ is not supported Fallback to host mode policy.
Feb 15 23:11:56 ip-10-0-0-165 kernel: ena 0000:00:06.0: Elastic Network Adapter (ENA) found at mem 80000000, mac addr 02:3f:ef:3b:20:71
Feb 15 23:11:56 ip-10-0-0-165 kernel: ena 0000:00:06.0 ens6: renamed from eth0
Feb 15 23:11:56 ip-10-0-0-165 systemd-udevd[517]: Using default interface naming scheme 'v250'.
Feb 15 23:11:56 ip-10-0-0-165 systemd-networkd[371]: eth0: Interface name change detected, renamed to ens6.
```

udev seems to properly identify the interface in all cases:
```text
admin@ip-10-0-0-220:~$ udevadm info /sys/class/net/ens6
P: /devices/pci0000:00/0000:00:06.0/net/ens6
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:06.0/net/ens6
E: INTERFACE=ens6
E: IFINDEX=85
E: SUBSYSTEM=net
E: USEC_INITIALIZED=4185012962
E: ID_NET_NAMING_SCHEME=v249
E: ID_NET_NAME_MAC=enx023fef3b2071
E: ID_NET_NAME_PATH=enp0s6
E: ID_NET_NAME_SLOT=ens6
E: ID_BUS=pci
E: ID_VENDOR_ID=0x1d0f
E: ID_MODEL_ID=0xec20
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Amazon.com, Inc.
E: ID_MODEL_FROM_DATABASE=Elastic Network Adapter (ENA)
E: ID_PATH=pci-0000:00:06.0
E: ID_PATH_TAG=pci-0000_00_06_0
E: ID_NET_DRIVER=ena
E: ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
E: ID_NET_NAME=ens6
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/ens6
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #22538.

### CODE REVIEW

File: src/network/networkd-link.c [hunk 1]
```diff
@@ -2024,6 +2024,85 @@ static int link_update_master(Link *link, sd_netlink_message *message) {
...
+        assert(message);
+
+        /* Driver is already read. Assuming the driver is never changed. */
+        if (link->driver)
+                return 0;
+
+        /* When udevd is running, read the driver after the interface is initialized by udevd.
+         * Otherwise, ethtool may not work correctly. See issue #22538.
+         * When udevd is not running, read the value when the interface is detected. */
+        if (link->state != (path_is_read_only_fs("/sys") > 0 ? LINK_STATE_PENDING : LINK_STATE_INITIALIZED))
```
Comment (poettering) [inline src/network/networkd-link.c]: given you need this multiple times, and the connection between /sys/ and udev isn't obvious (i mean you added a comment for a reason), maybe wrap the check in a trivial helper function somewhere:

```c
static bool udev_available(void) {
        static int cache = -1;
        if (cache >= 0)
                return cache; 

        cache = path_is_read_only_fs("/sys/") <= 0;
}
```

(and then add a comment there explaining it)

Comment (yuwata) [reply src/network/networkd-link.c]: Sounds nice!

**Comment by yuwata** [comment]
@poettering Thank you for the suggestion. 
- `udev_available()` is added, and used now.

PTAL.
