### PR TITLE
core,run0: fixlets/tweaks around $SHELL handling

### LINKED ISSUE #35007: run0 wrongly sets SHELL=/bin/bash environment variable for root
### systemd version the issue has been seen with

256

### Used distribution

Arch Linux

### Linux kernel version used

6.11.6-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-run, run0

### Expected behaviour you didn't see

When running `run0` while having the root's shell set to `/usr/bin/zsh`, the `SHELL` environment variable should be set to that shell and not `/bin/bash`.

### Unexpected behaviour you saw

When running `run0` while having the root's shell set to `/usr/bin/zsh`, the `SHELL` environment variable is set to `/bin/bash`

### Steps to reproduce the problem

Set ZSH as root shell:
```bash
chsh -s /usr/bin/zsh
touch ~/.zshrc
```
In a new terminal, as root:
```
echo $SHELL
run0
echo $SHELL
echo $ZSH_VERSION
grep -oaP 'SHELL=[a-z/]+' /proc/$$/environ
```

### Additional program output to the terminal or log subsystem illustrating the issue

```bash
# echo $SHELL
/usr/bin/zsh
# run0
# echo $SHELL
/bin/bash
# echo $ZSH_VERSION
5.9
# grep -oaP 'SHELL=[a-z/]+' /proc/$$/environ
SHELL=/bin/bash
```

I had a look into the source code and I think it is related to the [call to `get_fixed_user`](https://github.com/systemd/systemd/blob/d980aee1e8e057b12fcbd20e8300248091d000d5/src/core/exec-invoke.c#L1862) which will end up setting the `SHELL` variable to `DEFAULT_USER_SHELL`, a build-time parameter that defaults to `/bin/bash`.

This could apparently be fixed by setting `User=root` in the transient unit created by run0 (not tested).

### PR DESCRIPTION
**Pull request by YHNdnzj**
Fixes #35007

### CODE REVIEW

File: src/core/exec-invoke.c [hunk 1]
```diff
@@ -4904,7 +4906,13 @@ int exec_invoke(
                         u = NULL;
 
                 if (u) {
-                        r = get_fixed_user(u, &username, &uid, &gid, &pwent_home, &shell);
+                        /* We can't use nss unconditionally for root without risking deadlocks if some IPC services
+                         * will be started by pid1 and are ordered after us. But if SetLoginEnvironment= is
+                         * enabled explicitly, or PAM shall be invoked, let's consult NSS even for root,
```
Comment (yuwata) [inline src/core/exec-invoke.c]: Are there any implicit ordering dependency or so to avoid deadlocks when these settings specified??

Comment (YHNdnzj) [reply src/core/exec-invoke.c]: Nope, the idea is that PAM will be doing its own nss anyways. It doesn't matter if we query that in this case

**Comment by eworm-de** [comment]
Does not look like this fixes the issue...

**Comment by YHNdnzj** [comment]
> Does not look like this fixes the issue...

Hmm, can you give it another go?

**Comment by eworm-de** [comment]
Oh, wait, no...

User `nepu` and `root` have set their shell to `/bin/zsh`:

```
% getent passwd nepu
nepu:x:1000:1000:Nepu User:/home/nepu:/bin/zsh
% ps         
    PID TTY          TIME CMD
   4660 pts/0    00:00:01 zsh
   5668 pts/0    00:00:00 ps
% echo $SHELL
/bin/zsh
% run0
# getent passwd root
root:x:0:0:root:/root:/bin/zsh
# ps
    PID TTY          TIME CMD
   5698 pts/1    00:00:00 zsh
   5720 pts/1    00:00:00 (sd-pam)
   5761 pts/1    00:00:00 ps
# echo $SHELL
/bin/zsh
```
This looks like expected now.

But let's configure `/bin/bash` for `root` now:

```
% getent passwd nepu
nepu:x:1000:1000:Nepu User:/home/nepu:/bin/zsh
% ps
    PID TTY          TIME CMD
   4660 pts/0    00:00:01 zsh
   5845 pts/0    00:00:00 ps
% echo $SHELL
/bin/zsh
% run0
# getent passwd root
root:x:0:0:root:/root:/bin/bash
# ps
    PID TTY          TIME CMD
   5881 pts/1    00:00:00 zsh
   5902 pts/1    00:00:00 (sd-pam)
   5954 pts/1    00:00:00 ps
# echo $SHELL
/bin/bash
```

Judging from documentation the shell from originating user is used:

> [...] If no command line is specified an interactive shell is invoked. The shell to invoke may be controlled via --setenv=SHELL=...  and currently defaults to the originating user's shell (i.e. not the target user's!) if operating locally, [...]

So the shell from `nepu` should be used, which is `/bin/zsh`. It is used, but why is `SHELL` set to `/bin/bash` then? Why is `nss` involved at all? The used process and the content of the variable should be taken from user, not `nss`?

**Comment by YHNdnzj** [comment]
> Judging from documentation the shell from originating user is used

Ugh, I wasn't aware of this behavior at all. Thought it was the other way around...

File: test/units/TEST-74-AUX-UTILS.run.sh [hunk 2]
```diff
@@ -248,13 +248,17 @@ if [[ -e /usr/lib/pam.d/systemd-run0 ]] || [[ -e /etc/pam.d/systemd-run0 ]]; the
     run0 ls /
     assert_eq "$(run0 echo foo)" "foo"
     # Check if we set some expected environment variables
-    for arg in "" "--user=root" "--user=0" "--user=testuser"; do
-        assert_eq "$(run0 ${arg:+"$arg"} bash -c 'echo $SUDO_USER')" "$USER"
-        assert_eq "$(run0 ${arg:+"$arg"} bash -c 'echo $SUDO_UID')" "$(id -u "$USER")"
-        assert_eq "$(run0 ${arg:+"$arg"} bash -c 'echo $SUDO_GID')" "$(id -u "$USER")"
+    for arg in "" "root" "0" "testuser"; do
```
Comment (yuwata) [inline test/units/TEST-74-AUX-UTILS.run.sh]: Not a matter, but `arg` -> `user` ?

File: test/units/TEST-74-AUX-UTILS.run.sh [hunk 3]
```diff
@@ -248,13 +248,17 @@ if [[ -e /usr/lib/pam.d/systemd-run0 ]] || [[ -e /etc/pam.d/systemd-run0 ]]; the
...
+        assert_eq "$(run0 ${arg:+"--user=$arg"} bash -c 'echo $SUDO_UID')" "$(id -u "$USER")"
+        assert_eq "$(run0 ${arg:+"--user=$arg"} bash -c 'echo $SUDO_GID')" "$(id -u "$USER")"
 
         # Validate that we actually went properly through PAM (XDG_SESSION_TYPE is set by pam_systemd)
-        assert_eq "$(run0 ${arg:+"$arg"} bash -c 'echo $XDG_SESSION_TYPE')" "unspecified"
+        assert_eq "$(run0 ${arg:+"--user=$arg"} bash -c 'echo $XDG_SESSION_TYPE')" "unspecified"
+
+        # Validate that $SHELL is set to login shell of target user when cmdline is supplied (not invoking shell)
+        TARGET_LOGIN_SHELL="$(getent passwd "$arg" | cut -d: -f7)"
+        assert_eq "$(run0 ${arg:+"--user=$arg"} printenv SHELL)" "$TARGET_LOGIN_SHELL"
```
Comment (yuwata) [inline test/units/TEST-74-AUX-UTILS.run.sh]: maybe better to add test case with --machine=, to test the first commit ?

**Comment by eworm-de** [comment]
Do you want to fix CI before I start another round of testing?

File: test/units/TEST-74-AUX-UTILS.run.sh (hunk 3 above)
Comment (YHNdnzj) [reply test/units/TEST-74-AUX-UTILS.run.sh]: We actually can't. To test that run0 must be called without cmdline, which spawns an interactive shell...

**Comment by eworm-de** [comment]
> Do you want to fix CI before I start another round of testing?

Did anyway... Works for my use cases. 👍 Thanks! ❤️

File: test/units/TEST-74-AUX-UTILS.run.sh (hunk 3 above)
Comment (YHNdnzj) [reply test/units/TEST-74-AUX-UTILS.run.sh]: An appropriate test case will be added in #37071

**Review by yuwata — APPROVED** [review]

File: src/core/exec-invoke.c [hunk 4]
```diff
@@ -4906,7 +4908,13 @@ int exec_invoke(
                         u = NULL;
 
                 if (u) {
-                        r = get_fixed_user(u, &username, &uid, &gid, &pwent_home, &shell);
+                        /* We can't use nss unconditionally for root without risking deadlocks if some IPC services
+                         * will be started by pid1 and are ordered after us. But if SetLoginEnvironment= is
```
Comment (yuwata) [inline src/core/exec-invoke.c:4912]: Hm, I noticed that SetLoginEnvironment= is enabled by default when User= or DynamicUser= is enabled.
So, many processes may be affected with the change, like resolved, networkd, timesyncd, and so on. Is it really safe?
If an NSS requires networking,,, what happens?

Comment (YHNdnzj) [reply src/core/exec-invoke.c:4912]: It's effectively enabled in the sense of exec_context_get_set_login_environment. The field itself is tristate.

Comment (yuwata) [reply src/core/exec-invoke.c:4912]: Ah, "enabled _explicitly_".
Could you extend the comment to mention that? Otherwise, we might mistakenly replace the condition with `exec_context_get_set_login_environment()` in a future.

**Review by yuwata — APPROVED** [review]
LGTM.
