### PR TITLE
teach link_tmpfile() to optionally replace files

### LINKED ISSUE #21787: 'systemd-hwdb update' may leak disk space via temporary files in /etc/udev
Please see the following console output.  I've noticed some systems eventually run out of disk space, apparently due to temporary files left in /etc/udev.  My working theory is that aborted power-ups are the culprit, i.e. if power is pulled before systemd-hwdb update can complete, files are orphaned in /etc/udev.  I've been able to reproduce behavior in support of this theory by running systemd-hwdb update from the console and interrupting it a few seconds later.

root@LEA-SuperDARC(192.168.100.132):/etc/udev# systemctl --version
systemd 247 (247.6+)
-PAM -AUDIT -SELINUX +IMA -APPARMOR -SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ -LZ4 -ZSTD -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=hybrid

root@LEA-SuperDARC(192.168.100.132):/etc/udev# uname -a
Linux LEA-SuperDARC 5.10.21-yocto-standard #1 PREEMPT Tue Mar 9 04:04:38 UTC 2021 armv7l GNU/Linux

root@LEA-SuperDARC(192.168.100.132):/etc/udev# ls -la
drwxr-xr-x    4 root     root          4096 Dec 15 15:41 .
drwxr-xr-x   26 root     root          4096 Dec 11 00:19 ..
-r--r--r--    1 root     root      10718569 Dec 15 15:41 hwdb.bin
drwxr-xr-x    2 root     root          4096 Mar  9  2018 hwdb.d
drwxr-xr-x    2 root     root          4096 Dec 11 00:17 rules.d
-rw-r--r--    1 root     root           305 Mar  9  2018 udev.conf

root@LEA-SuperDARC(192.168.100.132):/etc/udev# systemd-hwdb update
^C

root@LEA-SuperDARC(192.168.100.132):/etc/udev# ls -la
drwxr-xr-x    4 root     root          4096 Dec 15 15:45 .
-r--r--r--    1 root     root      10718569 Dec 15 15:45 .#hwdb.bin1jpKH5  <---- orphaned file
drwxr-xr-x   26 root     root          4096 Dec 11 00:19 ..
-r--r--r--    1 root     root      10718569 Dec 15 15:41 hwdb.bin
drwxr-xr-x    2 root     root          4096 Mar  9  2018 hwdb.d
drwxr-xr-x    2 root     root          4096 Dec 11 00:17 rules.d
-rw-r--r--    1 root     root           305 Mar  9  2018 udev.conf

### PR DESCRIPTION
**Pull request by poettering**
This should more or less fix #21787

Fixes: #21787

### CODE REVIEW

File: src/basic/tmpfile-util.c [hunk 1]
```diff
@@ -328,24 +329,72 @@ int fopen_tmpfile_linkable(const char *target, int flags, char **ret_path, FILE
...
+                return r;
 
-        return RET_NERRNO(linkat(AT_FDCWD, FORMAT_PROC_FD_PATH(fd), AT_FDCWD, target, AT_SYMLINK_FOLLOW));
+        r = link_fd(fd, AT_FDCWD, tmp);
+        if (r < 0)
+                return -EEXIST; /* propagate original error */
+
+        r = RET_NERRNO(rename(tmp, target));
+        if (r < 0) {
+                (void) unlink(tmp);
```
Comment (yuwata) [inline src/basic/tmpfile-util.c:389]: Maybe, better to use `_cleanup_(unlink_and_freep)` and `tmp = mfree(tmp)` on success?

File: src/basic/tmpfile-util.c [hunk 2]
```diff
@@ -328,24 +329,72 @@ int fopen_tmpfile_linkable(const char *target, int flags, char **ret_path, FILE
...
+         * system under a temporary name) is very short. */
+
+        r = tempfn_random(target, NULL, &tmp);
+        if (r < 0)
+                return r;
 
-        return RET_NERRNO(linkat(AT_FDCWD, FORMAT_PROC_FD_PATH(fd), AT_FDCWD, target, AT_SYMLINK_FOLLOW));
+        r = link_fd(fd, AT_FDCWD, tmp);
+        if (r < 0)
+                return -EEXIST; /* propagate original error */
```
Comment (yuwata) [inline src/basic/tmpfile-util.c]: Not a matter, if `r` is not used, you can shorten the code a bit: `if (link_fd(...) < 0)`

**Review by yuwata — APPROVED** [review]

File: src/basic/tmpfile-util.c (hunk 1 above)
Comment (poettering) [reply src/basic/tmpfile-util.c:389]: but that would end up being more involved, since we acquire `tmp` through tempfn_random(), but the auto-unlinking should only be done once we actually issue link_fd(), i.e. one step later. So I figured doing the unlink() here in the error path manually is ultimately shorter.

Comment (yuwata) [reply src/basic/tmpfile-util.c:389]: OK. That makes sense for me.

**Comment by keszybz** [comment]
Thanks. I didn't read the code in detail, but it seems to work great:
```
openat(AT_FDCWD, "/etc/udev", O_WRONLY|O_CLOEXEC|O_TMPFILE, 0640) = 3</etc/udev/#3638401>(deleted)
newfstatat(3</etc/udev/#3638401>(deleted), "", {st_mode=S_IFREG|0444, st_size=0, ...}, AT_EMPTY_PATH) = 0
newfstatat(3</etc/udev/#3638401>(deleted), "", {st_mode=S_IFREG|0444, st_size=12395978, ...}, AT_EMPTY_PATH) = 0
readlinkat(AT_FDCWD, "/proc/self/fd/3", "/etc/udev/#3638401 (deleted)", 4096) = 28
openat(AT_FDCWD, "/etc/udev", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 4</etc/udev>
linkat(AT_FDCWD, "/proc/self/fd/3", AT_FDCWD, "/etc/udev/hwdb.bin", AT_SYMLINK_FOLLOW) = -1 EEXIST (File exists)
linkat(AT_FDCWD, "/proc/self/fd/3", AT_FDCWD, "/etc/udev/.#hwdb.bina9299051a1e42940", AT_SYMLINK_FOLLOW) = 0
rename("/etc/udev/.#hwdb.bina9299051a1e42940", "/etc/udev/hwdb.bin") = 0
```
