### PR TITLE
struct rfkill_event read/write size leniency

### LINKED ISSUE #18677: systemd-rfkill: Couldn't write rfkill event structure, too short.
current git head:

```console
$ journalctl -b -u systemd-rfkill.service
-- Journal begins at Sun 2020-10-25 02:19:13 CEST, ends at Thu 2021-02-18 10:03:34 CET. --
Feb 18 09:34:37 krowka systemd[1]: Starting systemd-rfkill.service...
Feb 18 09:34:37 krowka systemd-rfkill[1189]: Couldn't write rfkill event structure, too short.
Feb 18 09:34:37 krowka systemd-rfkill[1189]: Couldn't write rfkill event structure, too short.
Feb 18 09:34:37 krowka systemd-rfkill[1189]: Couldn't write rfkill event structure, too short.
Feb 18 09:34:38 krowka systemd-rfkill[1189]: Couldn't write rfkill event structure, too short.
Feb 18 09:34:38 krowka systemd[1]: Started systemd-rfkill.service.
Feb 18 09:34:43 krowka systemd[1]: systemd-rfkill.service: Succeeded.
```

strace shows that we try to write 9 bytes, but only 8 go through. 9 bytes matches the size defined in /usr/include/linux/rfkill.h.

```
write(3</dev/rfkill>, "\3\0\0\0\0\2\0\0\0", 9) = 8
writev(2</dev/pts/0>, [{iov_base="\33[0;1;31m", iov_len=9}, {iov_base="Couldn't write rfkill event structure, too short.", iov_len=49}, {iov_base="\33[0m", iov_len=4}, {iov_base="\n", iov_len=1}], 4Couldn't write rfkill event structure, too short.
) = 63
```

Smells like a kernel bug, no?

EDIT: above is with kernel-core-5.10.16-200.fc33.x86_64.

With kernel-core-5.11.0-0.rc7.20210210gite0756cfc7d7c.150.fc34.x86_64 I get a different error:
```
Feb 17 21:36:41 krowka systemd[1]: Listening on systemd-rfkill.socket.
Feb 17 21:36:41 krowka systemd[1]: Starting systemd-rfkill.service...
Feb 17 21:36:41 krowka systemd-rfkill[981]: Read event structure of invalid size.
Feb 17 21:36:41 krowka systemd[1]: systemd-rfkill.service: Main process exited, code=exited, status=1/FAILURE
Feb 17 21:36:41 krowka systemd[1]: systemd-rfkill.service: Failed with result 'exit-code'.
Feb 17 21:36:41 krowka systemd[1]: Failed to start systemd-rfkill.service.
```

### PR DESCRIPTION
**Pull request by keszybz**
Fixes #18677.

### CODE REVIEW

**Comment by yuwata** [comment]
LGTM.

**Comment by poettering** [comment]
Hmm, I guess the kernel people fucked up their binary compatibility: my guess this is old systemd built with new kernel headers on an old kernel? because in that case we'll read the structure as defined in the kernel headers, and that's gonna be the large one, but the kernel will only give us the short one.

we should probably disconnect ourselves from the kernel headers on this, and define our own structure matching the old definition and shun the new definition, so that we can take benefit of the kernel's compat codepaths. After all we don#t need the extra field.

this reminds me of the statx situation where we also have to define our own structure...

File: src/rfkill/rfkill.c [hunk 1]
```diff
@@ -332,9 +335,15 @@ static int run(int argc, char *argv[]) {
...
-                        return log_error_errno(SYNTHETIC_ERRNO(EIO), "Read event structure of unexpected size (%zd, not %d)",
+                if (l < RFKILL_EVENT_SIZE_V1)
+                        return log_error_errno(SYNTHETIC_ERRNO(EIO), "Short read of struct rfkill_event: (%zd < %d)",
                                                l, RFKILL_EVENT_SIZE_V1);
+                log_debug("Reading struct rfkill_event: got %zd bytes.", l);
+
+                /* The event structure has more fields. We only care about the first few, so it's OK if we
+                 * don't read the full structure. */
+                assert_cc(offsetof(struct rfkill_event, op) < RFKILL_EVENT_SIZE_V1);
+                assert_cc(offsetof(struct rfkill_event, type) < RFKILL_EVENT_SIZE_V1);
```
Comment (poettering) [inline src/rfkill/rfkill.c:346]: i figure you want to check `offsetof(struct rfkill_event, type) + sizeof(*&event.type)`, i.e. to actually inlude the field?

File: src/rfkill/rfkill.c [hunk 2]
```diff
@@ -171,14 +171,17 @@ static int load_state(Context *c, const struct rfkill_event *event) {
                 .op = RFKILL_OP_CHANGE,
                 .soft = b,
         };
+        assert_cc(offsetof(struct rfkill_event, op) < RFKILL_EVENT_SIZE_V1);
+        assert_cc(offsetof(struct rfkill_event, soft) < RFKILL_EVENT_SIZE_V1);
 
         ssize_t l = write(c->rfkill_fd, &we, sizeof we);
```
Comment (poettering) [inline src/rfkill/rfkill.c:177]: use RFKILL_EVENT_SIZE_V1 as 3rd param here?

Comment (keszybz) [reply src/rfkill/rfkill.c:177]: I vacillated a bit on this, but in the end I think it's nice to use the full size because then we get information what the kernel supports in the logs. The kernel is actually fine (both old and new versions) with whatever size.

File: src/rfkill/rfkill.c (hunk 1 above)
Comment (keszybz) [reply src/rfkill/rfkill.c:346]: The whole check is more documentation for the reader than a real check. And the field is one byte, so the sizeof isn't necessary.

**Comment by keszybz** [comment]
> Hmm, I guess the kernel people fucked up their binary compatibility: my guess this is old systemd built with new kernel headers running on an old kernel? because in that case we'll read the structure as defined in the kernel headers, and that's gonna be the large one, but the kernel will only give us the short one.

Not exactly. Our code was being to strict with the size check.

> we should probably disconnect ourselves from the kernel headers on this, and define our own structure matching the old definition and shun the new definition, so that we can take benefit of the kernel's compat codepaths. After all we don#t need the extra field.

No, there is really no need. This patch should work just fine.

**Comment by keszybz** [comment]
I'll go ahead and merge this without another round of reviews. It seems to work as expected on both kernel-core-5.10.16-200.fc33.x86_64 and kernel-core-5.11.0-0.rc7.20210210gite0756cfc7d7c.150.fc34.x86_64.
