### PR TITLE
tests: explicitly enable user namespaces for TEST-13-NSPAWN-SMOKE

### LINKED ISSUE #11173: TEST-13-NSPAWN-SMOKE seems to be failing under KVM
**systemd version the issue has been seen with**
> 239 (latest master)

**Used distribution**
 > CentOS 7.6

In attempts to further improve the CentOS CI, I'd like to run the integration test suite under both systemd-nspawn and KVM (systemd/systemd-centos-ci#29). However, there's a one test, which keeps failing under KVM (TEST-13-NSPAWN-SMOKE).

```
...
Remounting /nc-container/sys/fs/cgroup/cpuset (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting cgroup on /nc-container/sys/fs/cgroup/systemd (MS_NOSUID|MS_NODEV|MS_NOEXEC "none,name=systemd,xattr")...
Remounting /nc-container/sys/fs/cgroup (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_STRICTATIME "mode=755")...
Failed to fork inner child: Invalid argument
(sd-namespace) failed with exit status 1.
[[0;1;31mFAILED[0m] Failed to start [0;1;39mTestsuite service[0m.
See 'systemctl status testsuite.service' for details.
```

Full log: https://ci.centos.org/job/systemd-ci-build/32/artifact/artifacts_agNShu/testsuite-logs.DBo/TEST-13-NSPAWN-SMOKE-kvm.log
CI job: https://ci.centos.org/job/systemd-ci-build/32/

### PR DESCRIPTION
**Pull request by mrc0mmand**
Fixes #11173.

### CODE REVIEW

File: test/TEST-13-NSPAWN-SMOKE/test.sh [hunk 1]
```diff
@@ -4,6 +4,11 @@
 set -e
 TEST_DESCRIPTION="systemd-nspawn smoke test"
 TEST_NO_NSPAWN=1
+# if user namespaces are supported on the host, enable them
+# in the VM/container as well
+if unshare -U sh -c :; then
+    KERNEL_APPEND="user_namespace.enable=1"
```
Comment (evverx) [inline test/TEST-13-NSPAWN-SMOKE/test.sh]: I don't think KERNEL_APPEND should be overwritten completely because it will make it impossible to run something like `make run KERNEL_APPEND=systemd.unit=rescue.target`.

Comment (mrc0mmand) [reply test/TEST-13-NSPAWN-SMOKE/test.sh]: Good point, fixed.

File: test/TEST-13-NSPAWN-SMOKE/test.sh [hunk 2]
```diff
@@ -4,6 +4,11 @@
 set -e
 TEST_DESCRIPTION="systemd-nspawn smoke test"
 TEST_NO_NSPAWN=1
+# if user namespaces are supported on the host, enable them
+# in the VM/container as well
```
Comment (evverx) [inline test/TEST-13-NSPAWN-SMOKE/test.sh]: I'd add that it's CentOS-specific. Maybe it'd even make sense to guard it with something like `if $LOOKS_LIKE_CENTOS`, but I'm not sure.

Comment (mrc0mmand) [reply test/TEST-13-NSPAWN-SMOKE/test.sh]: Guarding this part definitely makes sense (imo).

Comment (evverx) [reply test/TEST-13-NSPAWN-SMOKE/test.sh]: In theory, it's possible to run any kernel with `KERNEL_BIN=` so technically we can't use this check to make sure that the kernel that is about to be booted supports user namespaces. Maybe it would be better to remove this part and pass `KERNEL_APPEND` explicitly on CentOS CI. What do you think?

Comment (mrc0mmand) [reply test/TEST-13-NSPAWN-SMOKE/test.sh]: I already override `KERNEL_BIN` and `INITRD`, so I see no issues here. Will drop this part completely then, thanks!

File: test/TEST-13-NSPAWN-SMOKE/test.sh [hunk 3]
```diff
@@ -70,6 +70,7 @@ if [[ -f /proc/1/ns/cgroup ]]; then
 fi
 
 is_user_ns_supported=no
+sysctl -w user.max_user_namespaces=10000
```
Comment (poettering) [inline test/TEST-13-NSPAWN-SMOKE/test.sh:77]: could you add a comment here what this is about?

Comment (mrc0mmand) [reply test/TEST-13-NSPAWN-SMOKE/test.sh:77]: Absolutely, should be fixed.

**Comment by mrc0mmand** [comment]
I don't want to push anybody or something, but it would be great to have this merged, so we can add the KVM testsuite into the CentOS CI.
