### PR TITLE
Fix `NeedDaemonReload=` for masked units with drop-ins

### LINKED ISSUE #33672: `systemctl status` always shows daemon-reload warning for a masked service with drop-ins
### systemd version the issue has been seen with

current main

### Used distribution

Fedora 40

### Linux kernel version used

6.9.6-200.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

No warning.

### Unexpected behaviour you saw

Warning: The unit file, source configuration file or drop-ins of foo.service changed on disk. Run 'systemctl daemon-reload' to reload units.

### Steps to reproduce the problem

1. Create a unit (e.g., `foo.service`) and a drop-in for it.
2. Run `systemctl daemon-reload` .
3. Mask the unit.
4. Run `systemctl status foo.service` .

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by dtardon**
Fixes #33672.

### CODE REVIEW

File: src/core/unit.c [hunk 1]
```diff
@@ -3813,7 +3813,7 @@ bool unit_need_daemon_reload(Unit *u) {
         if (fragment_mtime_newer(u->source_path, u->source_mtime, false))
                 return true;
 
-        if (u->load_state == UNIT_LOADED)
+        if (UNIT_IS_LOAD_COMPLETE(u->load_state))
```
Comment (YHNdnzj) [inline src/core/unit.c]: Well, this was changed intentionally in 19a44dfe4525ab01caf593a9c2beada4b412910d, since drop-ins really doesn't matter for masked units. Instead, let's skip the check for drop-ins entirely (I have a commit ready in https://github.com/YHNdnzj/systemd/commit/d7474c816032a4d6690e3112a8d0fe9da3136ab8, but didn't submit it. Consider just cherry-picking that?)

Comment (dtardon) [reply src/core/unit.c]: Done.
