### PR TITLE
networkd: Don't stop networkd if CONFIG_FIB_RULES=n in kernel.

### LINKED ISSUE #7027: systemd-networkd Could not enumerate rules: Operation not supported
### Submission type

 - Bug report

### systemd version the issue has been seen with

235

### Used distribution

Gentoo
Linux kernel 4.9.34

### In case of bug report: Expected behaviour you didn't see

systemd-networkd should start successfully.

### In case of bug report: Unexpected behaviour you saw

```
Oct 08 10:22:24 naomi systemd[1]: Starting Network Service...
Oct 08 10:22:24 naomi systemd-networkd[983]: Could not enumerate rules: Operation not supported
Oct 08 10:22:24 naomi systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
```

### PR DESCRIPTION
**Pull request by ssahani**
If FIB Rules is not supported by the kernel then networkd fails to
start as it retuns error=-EOPNOTSUPP.
In this case just ignore and let start networkd.

```
sendto(5, {{len=28, type=RTM_GETRULE, flags=NLM_F_REQUEST|NLM_F_ACK|NLM_F_DUMP, seq=8, pid=0}, {family=AF_UNSPEC, dst_len=0, src_len=0, tos=0, table=RT_TABLE_UNSPEC, action=FR_ACT_TO_TBL, flags=0}}, 28, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 16) = 28
recvmsg(5, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=128->12, msg_iov=[{iov_base=NULL, iov_len=0}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_NETLINK, cmsg_type=0x3}], msg_controllen=24, msg_flags=MSG_TRUNC}, MSG_PEEK|MSG_TRUNC) = 48
recvmsg(5, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=128->12, msg_iov=[{iov_base={{len=48, type=NLMSG_ERROR, flags=0, seq=8, pid=8856}, {error=-EOPNOTSUPP, msg={{len=28, type=RTM_GETRULE, flags=NLM_F_REQUEST|NLM_F_ACK|NLM_F_DUMP, seq=8, pid=0}, {family=AF_UNSPEC, dst_len=0, src_len=0, tos=0, table=RT_TABLE_UNSPEC, action=FR_ACT_TO_TBL, flags=0}}}}, iov_len=7416}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_NETLINK, cmsg_type=0x3}], msg_controllen=24, msg_flags=0}, MSG_TRUNC) = 48
```

```
Oct 08 10:22:24 naomi systemd[1]: Starting Network Service...
Oct 08 10:22:24 naomi systemd-networkd[983]: Could not enumerate rules: Operation not supported
Oct 08 10:22:24 naomi systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
```

Fixes #7027

### CODE REVIEW

**Comment by floppym** [comment]
The markdown coding in the commit message is a little screwy: you have 4 backticks instead of 3, and this seems to cause the rest of the message to be treated as a code block.

File: src/network/networkd.c [hunk 1]
```diff
@@ -133,10 +133,8 @@ int main(int argc, char *argv[]) {
         }
 
         r = manager_rtnl_enumerate_rules(m);
-        if (r < 0) {
-                log_error_errno(r, "Could not enumerate rules: %m");
-                goto out;
-        }
+        if (r < 0)
```
Comment (keszybz) [inline src/network/networkd.c]: Shouldn't it check for ENOSYS or another particular return value instead? It'd probably be nicer to put this check into the first call inside of `m_r_enumerate_rules`, and simply return 0 from that function in that case (and not even warn, just log it at debug level, because if the support is compiled out in the kernel, then there are no rules, so just doing nothing is exactly correct).

Comment (floppym) [reply src/network/networkd.c]: > Shouldn't it check for ENOSYS or another particular return value instead?

If routing policy rules are not supported, the netlink calls return `-EOPNOTSUPP`.

Comment (ssahani) [reply src/network/networkd.c]: updated

**Comment by ssahani** [comment]
@floppym could you please verify this patch. I don't have the kernel to test it.

**Comment by floppym** [comment]
systemd-networkd starts successfully. Also, I see the relevant log message when the log level is set to debug.

Looks good to me!

**Comment by keszybz** [comment]
And what about the idea to move the check inside of `m_r_enumerate_rules`?

**Comment by floppym** [comment]
> And what about the idea to move the check inside of m_r_enumerate_rules?

The latest commit does that already.

File: src/network/networkd-manager.c [hunk 2]
```diff
@@ -1454,8 +1454,14 @@ int manager_rtnl_enumerate_rules(Manager *m) {
                 return r;
 
         r = sd_netlink_call(m->rtnl, req, 0, &reply);
-        if (r < 0)
+        if (r < 0) {
+                if (r == -EOPNOTSUPP) {
+                        log_debug("FIB Rules is not supported by the kernel. Ignoring.");
```
Comment (keszybz) [inline src/network/networkd-manager.c]: "FIB rules are not supported by the kernel, ignoring."

**Comment by keszybz** [comment]
> The latest commit does that already.

Oh, right. Thanks for correcting me.

File: src/network/networkd-manager.c (hunk 2 above)
Comment (ssahani) [reply src/network/networkd-manager.c]: rupdated
