### PR TITLE
 cryptenroll,cryptsetup: only call `mlockall` if we have `CAP_IPC_LOCK`

### LINKED ISSUE #40315: systemd-cryptenroll crashes while opening an argon2id keyslot if not running as root
### systemd version the issue has been seen with

258.2

### Used distribution

NixOS unstable

### Linux kernel version used

6.18.2

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

I am trying to enroll a new keyslot (e.g. a recovery key) on a LUKS2 disk image file with a pre-existing Argon2id keyslot created with plain `cryptsetup`:
```
$ systemd-cryptenroll crypt.img --recovery-key
🔐 Please enter current passphrase for disk /tmp/tmp.1so1TKYhhI/test.img: (press TAB for no echo)
```

### Unexpected behaviour you saw

However, after I enter the correct passphrase, systemd-cryptenroll fails with the following error:
```
$ systemd-cryptenroll --recovery-key test.img
🔐 Please enter current passphrase for disk /tmp/tmp.1so1TKYhhI/test.img: ••••
Not enough available memory to open a keyslot.
Password not correct, please try again: Cannot allocate memory
🔐 Please enter current passphrase for disk /tmp/tmp.1so1TKYhhI/test.img: (press TAB for no echo)
```

Using `gdb`, I've traced this down to the call to the `libcryptsetup` function `crypt_volume_key_get` in [`src/cryptenroll/cryptenroll-password.c:84`](https://github.com/systemd/systemd/blob/15bd1496c9b59c1ec8ee05e78c65eeb3f148c898/src/cryptenroll/cryptenroll-password.c#L84), which in turn internally calls the openssl function `EVP_KDF_derive` in [`lib/crypto_backend/crypto_openssl.c`](https://gitlab.com/cryptsetup/cryptsetup/-/blob/v2.8.1/lib/crypto_backend/crypto_openssl.c#L637). Then, this function tries to `malloc` 1GiB of memory via `OPENSSL_secure_calloc`. The `malloc` call inside the function stack returns a null pointer, and `errno` is set to `ENOMEM` afterwards.

However, enough RAM is available, and the following C program outputs a non-null pointer when run on my machine:
```
#include <stdio.h>
#include <stdlib.h>

int main() {
	void* ptr = malloc(1024*1024*1024);
	printf("%p", ptr);
}
```

Manually calling `malloc` at the failing location in the openssl code with `gdb` with smaller sizes (i.e. `1024 * 1024` bytes) works a bunch of times, until these smaller calls start returning errors too. Since enrolling a new keyslot with vanilla `cryptsetup` works fine, I strongly suspect that `systemd-cryptenroll` imposes some kind of inappropriate memory allocation limit on itself. I haven't found out what kind of limit yet though - I've checked by calling `getrlimit` that `RLIMIT_AS` and `RLIMIT_DATA` are set to the maximum values of `uint64_t`.

### Steps to reproduce the problem

```
$ truncate -s 100M test.img
$ cryptsetup luksFormat test.img
$ systemd-cryptenroll test.img --recovery-key
```

### Additional program output to the terminal or log subsystem illustrating the issue

systemd-cryptenroll stack trace at the failing malloc call:

```sh
#0  CRYPTO_malloc (num=num@entry=1073741824,
    file=file@entry=0x7ffff7690748 "providers/implementations/kdfs/argon2.c",
    line=line@entry=739) at crypto/mem.c:213
#1  0x00007ffff7459ac3 in CRYPTO_zalloc (num=1073741824,
    file=file@entry=0x7ffff7690748 "providers/implementations/kdfs/argon2.c",
    line=line@entry=739) at crypto/mem.c:224
#2  0x00007ffff745aea3 in CRYPTO_secure_zalloc (num=<optimized out>,
    file=file@entry=0x7ffff7690748 "providers/implementations/kdfs/argon2.c",
    line=line@entry=739) at crypto/mem_sec.c:191
#3  0x00007ffff7453bda in CRYPTO_secure_calloc (num=<optimized out>, size=size@entry=1024,
    file=file@entry=0x7ffff7690748 "providers/implementations/kdfs/argon2.c",
    line=line@entry=739) at crypto/array_alloc.c:93
#4  0x00007ffff761cccd in initialize (ctx=ctx@entry=0x5555555c9190)
    at providers/implementations/kdfs/argon2.c:739
#5  0x00007ffff761e52a in kdf_argon2_derive (vctx=0x5555555c9190, out=0x5555555b8b00 "", outlen=<optimized out>, params=0x0) at providers/implementations/kdfs/argon2.c:1111
#6  0x00007ffff742d121 in EVP_KDF_derive (ctx=ctx@entry=0x5555555c9170, key=key@entry=0x5555555b8b00 "", keylen=keylen@entry=64, params=params@entry=0x0) at crypto/evp/kdf_lib.c:145
#7  0x00007ffff7f95629 in openssl_argon2 (type=<optimized out>, password=password@entry=0x7ffff7f9a7ad "salt", password_length=password_length@entry=18446744073709551615,
    salt=salt@entry=0x4 <error: Cannot access memory at address 0x4>, salt_length=salt_length@entry=93824992685168, key=0x5555555b8b00 "",
    key@entry=0x555500000005 <error: Cannot access memory at address 0x555500000005>, key_length=64, iterations=<optimized out>, memory=<optimized out>, parallel=<optimized out>)
    at lib/crypto_backend/crypto_openssl.c:637
#8  0x00007ffff7f96187 in crypt_pbkdf (kdf=<optimized out>, hash=0x400000000 <error: Cannot access memory at address 0x400000000>, password=0x7ffff7f9a7ad "salt",
    password@entry=0x5555555c2c70 "1234", password_length=18446744073709551615, password_length@entry=4, salt=0x4 <error: Cannot access memory at address 0x4>, salt_length=93824992685168,
    salt_length@entry=32, key=<optimized out>, key_length=<optimized out>, iterations=<optimized out>, memory=<optimized out>, parallel=4) at lib/crypto_backend/crypto_openssl.c:668
#9  0x00007ffff7f79249 in luks2_keyslot_get_key (cd=0x55555556edb0, jobj_keyslot=<optimized out>, password=0x5555555c2c70 "1234", passwordLen=4, volume_key=0x5555555bdb40 "", volume_key_len=64)
    at lib/luks2/luks2_keyslot_luks2.c:379
#10 luks2_keyslot_open (cd=0x55555556edb0, keyslot=<optimized out>, password=0x5555555c2c70 "1234", password_len=4, volume_key=0x5555555bdb40 "", volume_key_len=64)
    at lib/luks2/luks2_keyslot_luks2.c:599
#11 0x00007ffff7f760b9 in _open_and_verify (cd=0x55555556edb0, hdr=0x55555556ee48, h=0x7ffff7fb8f00 <luks2_keyslot>, keyslot=0, password=0x5555555c2c70 "1234", password_len=4,
    r_vk=0x7fffffffcad0) at lib/luks2/luks2_keyslot.c:365
#12 LUKS2_open_and_verify (cd=cd@entry=0x55555556edb0, hdr=hdr@entry=0x55555556ee48, keyslot=0, segment=segment@entry=-2, password=password@entry=0x5555555c2c70 "1234",
    password_len=password_len@entry=4, vk=0x7fffffffcad0) at lib/luks2/luks2_keyslot.c:418
#13 0x00007ffff7f762e1 in LUKS2_keyslot_open_priority (cd=cd@entry=0x55555556edb0, hdr=<optimized out>, priority=priority@entry=CRYPT_SLOT_PRIORITY_NORMAL,
    password=password@entry=0x5555555c2c70 "1234", password_len=password_len@entry=4, segment=segment@entry=-2, vk=0x7fffffffcad0) at lib/luks2/luks2_keyslot.c:450
#14 0x00007ffff7f76c29 in LUKS2_keyslot_open (cd=0x55555556edb0, keyslot=-1, segment=-2, password=0x5555555c2c70 "1234", password_len=4, vk=0x7fffffffcad0) at lib/luks2/luks2_keyslot.c:591
#15 0x00007ffff7f5b9f4 in get_luks2_key_by_passphrase (cd=<optimized out>, kc=0x7fffffffcb20, keyslot=<optimized out>, segment=<optimized out>, r_vk=<optimized out>) at lib/keyslot_context.c:29
#16 0x00007ffff7f35d78 in crypt_volume_key_get_by_keyslot_context (cd=cd@entry=0x55555556edb0, keyslot=keyslot@entry=-1, volume_key=volume_key@entry=0x5555555be2b0 "\036\344\016",
    volume_key_size=volume_key_size@entry=0x7fffffffcd38, kc=kc@entry=0x7fffffffcb20) at lib/setup.c:5947
#17 0x00007ffff7f36298 in crypt_volume_key_get (cd=cd@entry=0x55555556edb0, keyslot=keyslot@entry=-1, volume_key=volume_key@entry=0x5555555be2b0 "\036\344\016",
    volume_key_size=volume_key_size@entry=0x7fffffffcd38, passphrase=passphrase@entry=0x5555555c2c70 "1234", passphrase_size=<optimized out>) at lib/setup.c:5901
#18 0x000055555555cff1 in load_volume_key_password (cd=0x55555556edb0, cd_node=<optimized out>, ret_vk=ret_vk@entry=0x5555555be2b0, ret_vks=ret_vks@entry=0x7fffffffcd38)
    at ../src/cryptenroll/cryptenroll-password.c:84
#19 0x000055555555ba38 in prepare_luks (ret_cd=ret_cd@entry=0x7fffffffcdc0, ret_volume_key=ret_volume_key@entry=0x7fffffffcdf0) at ../src/cryptenroll/cryptenroll.c:813
#20 0x0000555555559b7c in run (argc=<optimized out>, argv=<optimized out>) at ../src/cryptenroll/cryptenroll.c:860
#21 main (argc=<optimized out>, argv=<optimized out>) at ../src/cryptenroll/cryptenroll.c:922
```

### PR DESCRIPTION
**Pull request by cyclic-pentane**
Fixes #40315.

Back in 2010 in b853f6e9d60c0eab2038227718ee1ed1266f94de, Lennart Poettering added an `mlockall` call right at the beginning of `systemd-cryptsetup`, presumably to prevent sensitive cryptographic material from being swapped to disk. Later, this was cargo-culted to `systemd-cryptenroll` in 97fb1fc4b10153bac96814c424008939a66507d0.

However, this means that it's much easier to hit the `RLIMIT_MEMLOCK` limit for locked memory. In particular, this made it impossible to unlock argon2 keyslots if you're not running `systemd-cryptenroll` as root.

~~I think it's fine to just remove these calls. Vanilla `cryptsetup` doesn't use them, and nowadays it should be common practice to encrypt your swap anyway.~~ This PR makes the `mlockall` invocation conditional upon us having the `CAP_IPC_LOCK` capability, as discussed below.

### CODE REVIEW

**Comment by YHNdnzj** [comment]
Dunno, in our codebase we tend to be extra cautious and avoid swapping out sensitive information wherever we can, including employing noswap for tmpfs backing service credentials. There even exists a TODO entry for the next level:

```
paranoia: whenever we process passwords, call mlock() on the memory first. i.e. look for all places we use free_and_erasep() and augment them with mlock(). Also use MADV_DONTDUMP. Alternatively (preferably?) use memfd_secret().
```

Doing this honestly feels like a step back.

**Comment by poettering** [comment]
not convinced either. argon2 stuff sizes its memory needs based on the system it runs on. if this triggers oom issues, this means something went wront there. typically this might happen if you enroll a luks key on a beefy machine, and then try to unlock it on a weak one...

**Comment by cyclic-pentane** [comment]
I think there's a misunderstanding here. The LUKS2 key was enrolled with `cryptsetup` on the same machine as the one `systemd-cryptenroll` is being run on, with the same memory constraints. The issue here is that `systemd-cryptenroll` tries to allocate the pages for the Argon2 KDF with memlocking, while `cryptsetup` (or rather the openssl shared library that performs the Argon2 key derivation) does not. And since there typically are comparatively tight restrictions for the maximum number of memlocked pages a non-root process is allowed to allocate (see `prlimit` - 8MiB on my system)

I did some thinking, and IMHO, memory-locking pages with sensitive data is damage reduction. In my book, I treat everything in the RAM of a machine with an unencrypted swap as potentially compromised, as there are no guarantees on Linux that all sensitive data will land on memlocked pages (for instance, doing something like this is just not possible in higher-level languages like Python). Therefore, afaict, memory-locking such pages is an incremental effort to reduce the probability of secrets leaking if the swap has been set up without encryption. I don't think it's worth to reduce the feature set of `sd-cryptenroll` for that, and I was pretty quick to propose removing the `mlockall` call especially since the comment called it a "delicious drop of snake oil".

There's some precedence for this: `cryptsetup` (and `openssl`, which is used by `cryptsetup`) also seem to tread memlocking as a best effort, and not as a hard requirement: `cryptsetup` only *attempts* to call `mlock` on the newly-allocated pages, and doesn't complain if it's not successful (see https://github.com/mbroz/cryptsetup/blob/388664627328ff2e59ea65eb64b21924aa1b1cea/lib/utils_safe_memory.c#L57). Previously, `cryptsetup` used `mlockall` too, but stopped doing that after running into similar issues as #40315 (see https://github.com/mbroz/cryptsetup/blob/388664627328ff2e59ea65eb64b21924aa1b1cea/docs/v2.6.0-ReleaseNotes#L82). Also, afaict, `openssl` only tries to memlock pages if the `OPENSSL_SEC_MEM` env var is set (https://github.com/openssl/openssl/blob/master/apps/openssl.c#L301).

As an immediate bugfix, I'd propose only calling `mlockall` if the current user is root. Would that be acceptable to you?

**Comment by keszybz** [comment]
My comment from #40319:
> I don't quite understand how mlocking of future pages is supposed to work. That line was added in b853f6e9d60c0eab2038227718ee1ed1266f94de with the explanation "cryptsetup: lock ourselves into memory as long as we deal with passwords". IIUC, we want to make sure that the pages with secrets are not swapped out. But this only works if those secrets are only placed in pages that were newly mapped. But e.g. our stack and parts of the heap could already be mapped and unused. In other words, changing `MCL_FUTURE` to `MCL_FUTURE|MCL_ONFAULT` seems reasonable, but I don't understand why we don't have `mlockall(MCL_CURRENT)` here too.

By calling `mlockall(MCL_CURRENT)` as an unprivileged user, we essentially set a trap for future code, which may do a completely normal `malloc` call and that call can fail with -ENOMEM. (https://github.com/openssl/openssl/blob/master/crypto/mem.c#L214 in this case.)  I don't think that library code handle this in any graceful way, the only thing it can do is fail.

The man page says
> Since  Linux 2.6.9, no limits are placed on the amount of memory that a privileged process can lock and the RLIMIT_MEMLOCK soft resource limit instead defines a limit on how much memory an unprivileged  process  may lock.

I guess that this means CAP_IPC_LOCK. We should conditionalize the calls to mlockall on CAP_IPC_LOCK. Please adjust the patch. (But note that we want to merge https://github.com/systemd/systemd/pull/40319 first, so rebase on top of that or maybe wait until it is merged.)

**Comment by poettering** [comment]
sorry, i don't get it. cryptsetup sizes the argon2 memory needs on the physical RAM that's available on the system (iirc it takes half of it). thus, it shouldn't matter if we mlock or don't. what am i missing?

**Comment by cyclic-pentane** [comment]
On Linux, there's a limit for how much virtual memory space processes can memlock:

https://www.man7.org/linux/man-pages/man2/getrlimit.2.html - `RLIMIT_MEMLOCK`

This limit typically is much lower than the amount of physical RAM available on the system. For instance, on my machine, it's 8 MiB:
```console
$ prlimit --memlock
RESOURCE DESCRIPTION                           SOFT    HARD UNITS
MEMLOCK  max locked-in-memory address space 8388608 8388608 bytes
```
which is nowhere near enough to match the 1GiB which the vanilla `cryptsetup` binary allocated during keyslot creation - even though it's being run on the same host - the vanilla `cryptsetup` binary doesn't attempt to call `mlock` on the buffer used for argon2. However, `systemd-crypt{setup,enroll}` do (indirectly via the `mlockall` calls).

**Comment by poettering** [comment]
> On Linux, there's a limit for how much virtual memory space processes can memlock:

yeah, but it has no effect on systemd-cryptsetup, which is privileged, where RLIMIT_MEMLOCK does not apply...

**Comment by cyclic-pentane** [comment]
Yes, exactly - the crash I described in #40315 occurs when `systemd-cryptenroll` is being run without root privileges to enroll keyslots to an image file instead of a block device.

As for systemd-cryptsetup, the possibility of it being run in a otherwise privileged context with just `CAP_IPC_LOCK` taken away is somewhat more remote (probably mostly relevant in sandboxing stuff), but I still think it's worth covering that case there too.

My plan is to proceed as @keszybz proposed and change this PR to only call `mlockall` if the process has the capability in question.

File: src/cryptsetup/cryptsetup.c [hunk 1]
```diff
@@ -2581,8 +2582,17 @@ static int verb_attach(int argc, char *argv[], void *userdata) {
         log_debug("%s %s ← %s type=%s cipher=%s", __func__,
                   volume, source, strempty(arg_type), strempty(arg_cipher));
 
-        /* A delicious drop of snake oil */
-        (void) mlockall(MCL_CURRENT|MCL_FUTURE|MCL_ONFAULT);
+        /* Memlock everything into physical RAM if we have the CAP_IPC_LOCK capability */
+        cap_t current_caps = cap_get_proc();
+        if (current_caps) {
+                cap_flag_value_t val;
+                if (!cap_get_flag(current_caps, CAP_IPC_LOCK, CAP_EFFECTIVE, &val)) {
```
Comment (YHNdnzj) [inline src/cryptsetup/cryptsetup.c]: we have a helper for this... have_effective_cap()

Comment (cyclic-pentane) [reply src/cryptsetup/cryptsetup.c]: oh, nice! Just pushed another commit to use that helper.

File: src/cryptenroll/cryptenroll.c [hunk 2]
```diff
@@ -849,8 +850,10 @@ static int run(int argc, char *argv[]) {
         if (r <= 0)
                 return r;
 
-        /* A delicious drop of snake oil */
-        (void) mlockall(MCL_CURRENT|MCL_FUTURE|MCL_ONFAULT);
+        /* Memlock everything into physical RAM if we have the CAP_IPC_LOCK capability */
+        if (have_effective_cap(CAP_IPC_LOCK) == 1) {
```
Comment (yuwata) [inline src/cryptenroll/cryptenroll.c]: Coding style nitpicks:
- `have_effective_cap()` returns boolean or negative errno. In such case, please use `> 0` rather than `== 1`.
- Please drop unnecessary `{}`.

File: src/cryptsetup/cryptsetup.c [hunk 3]
```diff
@@ -2581,8 +2582,10 @@ static int verb_attach(int argc, char *argv[], void *userdata) {
         log_debug("%s %s ← %s type=%s cipher=%s", __func__,
                   volume, source, strempty(arg_type), strempty(arg_cipher));
 
-        /* A delicious drop of snake oil */
-        (void) mlockall(MCL_CURRENT|MCL_FUTURE|MCL_ONFAULT);
+        /* Memlock everything into physical RAM if we have the CAP_IPC_LOCK capability */
+        if (have_effective_cap(CAP_IPC_LOCK) == 1) {
```
Comment (yuwata) [inline src/cryptsetup/cryptsetup.c]: Same here.

File: src/cryptenroll/cryptenroll.c (hunk 2 above)
Comment (cyclic-pentane) [reply src/cryptenroll/cryptenroll.c]: done

**Comment by cyclic-pentane** [comment]
> Please do not stack fix on fix. Please squash commits.

Alright, just did so - was assuming that you were going to squash them during the merge.

File: src/cryptenroll/cryptenroll.c [hunk 4]
```diff
@@ -849,8 +850,9 @@ static int run(int argc, char *argv[]) {
         if (r <= 0)
                 return r;
 
-        /* A delicious drop of snake oil */
-        (void) mlockall(MCL_CURRENT|MCL_FUTURE|MCL_ONFAULT);
+        /* Memlock everything into physical RAM if we have the CAP_IPC_LOCK capability */
+        if (have_effective_cap(CAP_IPC_LOCK) > 0)
+                (void) mlockall(MCL_CURRENT|MCL_FUTURE|MCL_ONFAULT);
```
Comment (poettering) [inline src/cryptenroll/cryptenroll.c]: hmm, can you add a helper call for this, maybe to src/basic/process-util.c that does this logic, and then also debug logs? (including showing the mlockall() error code if things fail via log_debug_errno().

and then call this here, and in cryptsetup, as well as in shutdown.c?

Comment (poettering) [reply src/cryptenroll/cryptenroll.c]: maybe call this safe_mlockall() or so?

Comment (cyclic-pentane) [reply src/cryptenroll/cryptenroll.c]: Decided to call this function `try_mlockall` and have it return `1` upon success, `0` if we don't have the capability and `-errno` if the `mlockall` call failed.

File: src/basic/process-util.c [hunk 5]
```diff
@@ -2227,6 +2229,21 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
         return 0;
 }
 
+int try_mlockall(int flags) {
+        int err;
+
+        if (have_effective_cap(CAP_IPC_LOCK) > 0) {
+                log_debug("Calling mlockall since we have CAP_IPC_LOCK.");
```
Comment (yuwata) [inline src/basic/process-util.c]: Well, I do not think logging here is necessary.

But, please add debugging log message when `have_effective_cap()` failed.

File: src/basic/process-util.c [hunk 6]
```diff
@@ -2227,6 +2229,21 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
...
+                if (mlockall(flags) < 0) {
+                        err = errno;
+                        log_debug_errno(err, "Failed to call mlockall: %m");
+                        return -err;
```
Comment (yuwata) [inline src/basic/process-util.c]: You can use simpler form:
```c
if (mlockall(flags) < 0)
        return log_debug_errno(errno, "...");
```

File: src/cryptenroll/cryptenroll.c [hunk 7]
```diff
@@ -849,8 +850,7 @@ static int run(int argc, char *argv[]) {
         if (r <= 0)
                 return r;
 
-        /* A delicious drop of snake oil */
-        (void) mlockall(MCL_CURRENT|MCL_FUTURE|MCL_ONFAULT);
+        try_mlockall(MCL_CURRENT|MCL_FUTURE|MCL_ONFAULT);
```
Comment (yuwata) [inline src/cryptenroll/cryptenroll.c]: Please voidify the call.

File: src/cryptsetup/cryptsetup.c [hunk 8]
```diff
@@ -2581,8 +2582,7 @@ static int verb_attach(int argc, char *argv[], void *userdata) {
         log_debug("%s %s ← %s type=%s cipher=%s", __func__,
                   volume, source, strempty(arg_type), strempty(arg_cipher));
 
-        /* A delicious drop of snake oil */
-        (void) mlockall(MCL_CURRENT|MCL_FUTURE|MCL_ONFAULT);
+        try_mlockall(MCL_CURRENT|MCL_FUTURE|MCL_ONFAULT);
```
Comment (yuwata) [inline src/cryptsetup/cryptsetup.c]: Also here.

File: src/shutdown/shutdown.c [hunk 9]
```diff
@@ -402,8 +402,8 @@ int main(int argc, char *argv[]) {
         init_watchdog();
 
         /* Lock us into memory */
-        (void) mlockall(MCL_FUTURE|MCL_ONFAULT);
-        (void) mlockall(MCL_CURRENT);
+        try_mlockall(MCL_FUTURE|MCL_ONFAULT);
+        try_mlockall(MCL_CURRENT);
```
Comment (yuwata) [inline src/shutdown/shutdown.c]: Hmm, I do not think it is necessary to convert here, as this is always privileged, no?

Comment (cyclic-pentane) [reply src/shutdown/shutdown.c]: I agree - I was deferring to @poettering here though (https://github.com/systemd/systemd/pull/40316#discussion_r2700947231)

File: src/basic/process-util.c (hunk 6 above)
Comment (cyclic-pentane) [reply src/basic/process-util.c]: I thought it was a good idea to return the errno if the syscall fails, in case we later add new invocations of `try_mlockall` that need to know the errno - and the errno could be overridden by some syscall inside of `log_debug_errno` before it's being returned (see errno(3)).

OTOH it should also be find to just not return the errno, what do you think?

Comment (yuwata) [reply src/basic/process-util.c]: `log_debug_errno(errno, ...)` should not update errno.

Comment (cyclic-pentane) [reply src/basic/process-util.c]: Oh, nice. Wasn't aware of that. Fixed :)

File: src/basic/process-util.c [hunk 10]
```diff
@@ -2227,6 +2229,17 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
         return 0;
 }
 
+int try_mlockall(int flags) {
+        if (have_effective_cap(CAP_IPC_LOCK) > 0) {
+                if (mlockall(flags) < 0) {
+                        log_debug_errno(errno, "Failed to call mlockall: %m");
+                        return -errno;
```
Comment (yuwata) [inline src/basic/process-util.c]: As said, please use the shorter form: `return log_debug_errno(errno, ...);`

Comment (cyclic-pentane) [reply src/basic/process-util.c]: Fixed just now. Sorry :sweat_smile:

File: src/basic/process-util.c [hunk 11]
```diff
@@ -2227,6 +2229,22 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
         return 0;
 }
 
+int try_mlockall(int flags) {
+        int ret;
```
Comment (yuwata) [inline src/basic/process-util.c]: Please use `int r`, rather than `ret`. That's our coding style.

File: src/basic/process-util.c [hunk 12]
```diff
@@ -2227,6 +2229,22 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
...
+
+        ret = have_effective_cap(CAP_IPC_LOCK);
+        if (ret < 0)
+                return log_debug_errno(-ret, "Failed to determine if we have CAP_IPC_LOCK: %m");
```
Comment (yuwata) [inline src/basic/process-util.c]: It is not necessary to pass positive error code to the logger.
`log_debug_errno(r, ...)` handles negative value gracefully, and returns negative error code.

File: src/basic/process-util.c [hunk 13]
```diff
@@ -2227,6 +2229,22 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
...
+
+        if (ret == 1) {
```
Comment (yuwata) [inline src/basic/process-util.c]: Maybe better to invert the condition to reduce indentation:
```c
if (r == 0)
        return 0;

if (mlockall(flags) < 0)
        return log_debug_errno(errno, ...);

return 1;
```

File: src/basic/process-util.c [hunk 14]
```diff
@@ -2227,6 +2229,22 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
...
+                if (mlockall(flags) < 0) {
```
Comment (yuwata) [inline src/basic/process-util.c]: Unnecessary `{}`. Please drop.

**Review by yuwata — CHANGES_REQUESTED** [review]
Several coding style nitpicks. One more round please.

File: src/basic/process-util.c [hunk 15]
```diff
@@ -2227,6 +2229,22 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
...
 
+int try_mlockall(int flags) {
+        int r;
+
+        r = have_effective_cap(CAP_IPC_LOCK);
+        if (r < 0)
+                return log_debug_errno(r, "Failed to determine if we have CAP_IPC_LOCK: %m");
+
+        if (r == 0)
+                return 0;
```
Comment (YHNdnzj) [inline src/basic/process-util.c]: please debug log here too: return log_debug_errno(SYNTHETIC_ERRNO(EPERM), "Lacking CAP_IPC_LOCK, skipping mlockall().")

File: src/basic/process-util.c [hunk 16]
```diff
@@ -2227,6 +2229,22 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
         return 0;
 }
 
+int try_mlockall(int flags) {
+        int r;
+
+        r = have_effective_cap(CAP_IPC_LOCK);
+        if (r < 0)
+                return log_debug_errno(r, "Failed to determine if we have CAP_IPC_LOCK: %m");
+
```
Comment (YHNdnzj) [inline src/basic/process-util.c]: please remove this empty line

File: src/basic/process-util.c [hunk 17]
```diff
@@ -2227,6 +2229,22 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
...
+        if (r == 0)
+                return 0;
+
+        if (mlockall(flags) < 0)
+                return log_debug_errno(errno, "Failed to call mlockall: %m");
+
+        return 1;
```
Comment (YHNdnzj) [inline src/basic/process-util.c]: and then return 0 here

File: src/basic/process-util.c [hunk 18]
```diff
@@ -2227,6 +2229,22 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
         return 0;
 }
 
+int try_mlockall(int flags) {
```
Comment (YHNdnzj) [inline src/basic/process-util.c]: I'd also like to call this safe_

File: src/basic/process-util.c (hunk 15 above)
Comment (yuwata) [reply src/basic/process-util.c]: Yeah, sounds better.

File: src/basic/process-util.c [hunk 19]
```diff
@@ -2227,6 +2229,21 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
...
+        int err;
+
+        if (have_effective_cap(CAP_IPC_LOCK) > 0) {
```
Comment (poettering) [inline src/basic/process-util.c]: can you invert the check and exit early please? we generally prefer early-exit over deep nesting of if checks.

also, maybe return a recognizable error code, just in case. maybe `return -EADDRNOTAVAIL` or so.

and maybe debug log here too, altogether hence:

```c
r = have_effective_cap(CAP_IPC_LOCK);
if (r < 0)
        return log_debug_errno(r, "Unable to determine if we possess, CAP_IPC_LOCK);
if (r == 0)
        return log_debug_errno(SYNTHETIC_ERRNO(EADDRNOTAVAIL), "Refusing to memory lock, because we lack CAP_IPC_LOCK"); 
```

File: src/basic/process-util.c (hunk 6 above)
Comment (poettering) [inline src/basic/process-util.c]: you can shorten this to:

```c
if (mlockall(flags) < 0)
        return log_debug_errno(errno, "Failed to call mlockall(): %m");

log_debug("Successfully called mlockall().");
```

i.e. log_debug_errno() always returns `-abs(r)` with `r` being the first argument, precisely to make it possible to shorten things like this.

File: src/basic/process-util.c (hunk 5 above)
Comment (poettering) [inline src/basic/process-util.c]: i'd instead show a message that indicates success if mlockall() worked.

File: src/basic/process-util.c [hunk 20]
```diff
@@ -2227,6 +2229,22 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
...
+        int r;
+
+        r = have_effective_cap(CAP_IPC_LOCK);
+        if (r < 0)
+                return log_debug_errno(r, "Failed to determine if we have CAP_IPC_LOCK: %m");
+        if (r == 0)
+                return log_debug_errno(SYNTHETIC_ERRNO(EPERM), "Lacking CAP_IPC_LOCK, skipping mlockall().");
+
+        if (mlockall(flags) < 0)
+                return log_debug_errno(errno, "Failed to call mlockall: %m");
```
Comment (yuwata) [inline src/basic/process-util.c]: Please suffix the function name with `()`, like the above.

File: src/basic/process-util.c [hunk 21]
```diff
@@ -2227,6 +2229,22 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
...
+
+        log_debug("Successfully called mlockall.");
```
Comment (yuwata) [inline src/basic/process-util.c]: Also here: `mlockall` -> `mlockall()`

**Review by yuwata — CHANGES_REQUESTED** [review]
Two more nitpicks.

File: src/cryptenroll/cryptenroll.c (hunk 7 above)
Comment (poettering) [inline src/cryptenroll/cryptenroll.c]: please keep the `(void)` cast in place. We use that wherever we knowingly ignore return values. This is understood by static checkers btw.

**Comment by poettering** [comment]
lgtm

File: src/cryptenroll/cryptenroll.c [hunk 22]
```diff
@@ -849,8 +850,7 @@ static int run(int argc, char *argv[]) {
         if (r <= 0)
                 return r;
 
-        /* A delicious drop of snake oil */
```
Comment (YHNdnzj) [inline src/cryptenroll/cryptenroll.c:852]: i'd probably keep these comments, but doesn't matter ;-)

File: src/shutdown/shutdown.c [hunk 23]
```diff
@@ -402,8 +402,8 @@ int main(int argc, char *argv[]) {
         init_watchdog();
 
         /* Lock us into memory */
-        (void) mlockall(MCL_FUTURE|MCL_ONFAULT);
-        (void) mlockall(MCL_CURRENT);
+        (void) safe_mlockall(MCL_FUTURE|MCL_ONFAULT);
+        (void) safe_mlockall(MCL_CURRENT);
```
Comment (YHNdnzj) [inline src/shutdown/shutdown.c]: you can do:

```c
if (safe_mlockall(MCL_FUTURE|MCL_ONFAULT) >= 0)
        (void) mlockall(MCL_CURRENT);
```

to avoid redundant capability checks

File: src/basic/process-util.c [hunk 24]
```diff
@@ -2227,6 +2229,22 @@ int proc_dir_read_pidref(DIR *d, PidRef *ret) {
         return 0;
 }
 
+int safe_mlockall(int flags) {
+        int r;
+
```
Comment (poettering) [inline src/basic/process-util.c:2234]: hmm, one last thing. can you add a comment here, explaining why we do this. Maybe something like this:

```c
/* When dealing with sensitive data let's lock ourselves into memory. We do this only when privileged however, as otherwise the amount of lockable memory that RLIMIT_MEMLOCK grants us is typically too low to make this work. The resource limit has no effect on CAP_IPC_LOCK processes, hence that's the privileged we check for. */
```

or something like that.

File: src/cryptenroll/cryptenroll.c (hunk 22 above)
Comment (cyclic-pentane) [reply src/cryptenroll/cryptenroll.c:852]: i don't have strong opinions on them, so i added them back in :D

File: src/shutdown/shutdown.c (hunk 23 above)
Comment (cyclic-pentane) [reply src/shutdown/shutdown.c]: yeah, good point

File: src/basic/process-util.c (hunk 24 above)
Comment (cyclic-pentane) [reply src/basic/process-util.c:2234]: done :)

File: src/shutdown/shutdown.c [hunk 25]
```diff
@@ -401,9 +401,9 @@ int main(int argc, char *argv[]) {
 
         init_watchdog();
 
-        /* Lock us into memory */
-        (void) mlockall(MCL_FUTURE|MCL_ONFAULT);
-        (void) mlockall(MCL_CURRENT);
+        /* Lock us into memory. If the first mlockall call fails, don't attempt it again. */
+        if (safe_mlockall(MCL_FUTURE|MCL_ONFAULT) >= 0)
+                (void) safe_mlockall(MCL_CURRENT);
```
Comment (YHNdnzj) [inline src/shutdown/shutdown.c]: hmm, no need for safe_ here?

Comment (cyclic-pentane) [reply src/shutdown/shutdown.c]: true

**Comment by cyclic-pentane** [comment]
Thanks for the extensive reviews everyone!! :)
