### PR TITLE
network: dhcp6: logs only new address

### LINKED ISSUE #16731: systemd-networkd: DHCPv6 client logs an information message upon every single renew/reply
**systemd version the issue has been seen with**

systemd 246 (246-2)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**

debian-testing, armhf

**Expected behaviour you didn't see**

Extrapolating from DHCPv4, I would expect that *no* information message is emitted upon a successful renew/reply cycle

**Unexpected behaviour you saw**

tcpdump shows nominal behaviour with my ISP, as far as I can tell:
```
18:10:32.502584 IP6 (flowlabel 0x92343, hlim 1, next-header UDP (17) payload length: 170) fe80::xxxx:xxxx:xxxx:xxxx.546 > ff02::1:2.547: dhcp6 renew (xid=63b09c (server-ID hwaddr/time type 1 time 627062587 525400f96d9c) (IA_NA IAID:760556473 T1:1000 T2:2000 (IA_ADDR zzzz:zzzz:zzzz:zzzz::10 pltime:3000 vltime:4000)) (Client-FQDN) (IA_PD IAID:760556473 T1:1000 T2:2000 (IA_PD-prefix pppp:pppp:pppp::/48 pltime:3000 vltime:4000)) (option-request DNS-server DNS-search-list NTP-server SNTP-servers rapid-commit) (client-ID vid 0000ab114c44c213) (elapsed-time 0))
18:10:32.512246 IP6 (class 0xe0, hlim 255, next-header UDP (17) payload length: 187) fe80::yyyy:yyyy:yyyy:yyyy.547 > fe80::xxxx:xxxx:xxxx:xxxx.546: dhcp6 reply (xid=63b09c (client-ID vid 0000ab114c44c213) (server-ID hwaddr/time type 1 time 627062587 525400f96d9c) (IA_NA IAID:760556473 T1:1000 T2:2000 (IA_ADDR zzzz:zzzz:zzzz:zzzz::10 pltime:3000 vltime:4000)) (DNS-server nnnn:nnnn:nnnn:nnnn::10 nnnn:nnnn:nnnn:nnnn::20) (IA_PD IAID:760556473 T1:1000 T2:2000 (IA_PD-prefix pppp:pppp:pppp::/48 pltime:3000 vltime:4000)) (Client-FQDN))
18:27:18.070637 IP6 (flowlabel 0x92343, hlim 1, next-header UDP (17) payload length: 170) fe80::xxxx:xxxx:xxxx:xxxx.546 > ff02::1:2.547: dhcp6 renew (xid=5f3bfc (server-ID hwaddr/time type 1 time 627062587 525400f96d9c) (IA_NA IAID:760556473 T1:1000 T2:2000 (IA_ADDR zzzz:zzzz:zzzz:zzzz::10 pltime:3000 vltime:4000)) (Client-FQDN) (IA_PD IAID:760556473 T1:1000 T2:2000 (IA_PD-prefix pppp:pppp:pppp::/48 pltime:3000 vltime:4000)) (option-request DNS-server DNS-search-list NTP-server SNTP-servers rapid-commit) (client-ID vid 0000ab114c44c213) (elapsed-time 0))
18:27:18.080438 IP6 (class 0xe0, hlim 255, next-header UDP (17) payload length: 187) fe80::yyyy:yyyy:yyyy:yyyy.547 > fe80::xxxx:xxxx:xxxx:xxxx.546: dhcp6 reply (xid=5f3bfc (client-ID vid 0000ab114c44c213) (server-ID hwaddr/time type 1 time 627062587 525400f96d9c) (IA_NA IAID:760556473 T1:1000 T2:2000 (IA_ADDR zzzz:zzzz:zzzz:zzzz::10 pltime:3000 vltime:4000)) (DNS-server nnnn:nnnn:nnnn:nnnn::10 nnnn:nnnn:nnnn:nnnn::20) (IA_PD IAID:760556473 T1:1000 T2:2000 (IA_PD-prefix pppp:pppp:pppp::/48 pltime:3000 vltime:4000)) (Client-FQDN))
```
At the same time stamps, the journal shows:
```
Aug 14 18:10:32 gateway systemd-networkd[385]: eth2: DHCPv6 address zzzz:zzzz:zzzz:zzzz::10/128 timeout preferred 3000 valid 4000
Aug 14 18:27:18 gateway systemd-networkd[385]: eth2: DHCPv6 address zzzz:zzzz:zzzz:zzzz::10/128 timeout preferred 3000 valid 4000
```
I would *not* expect an information message upon each successful renew/reply cycle (in my case every 1000 seconds). DHCPv4 doesn't do this either. Could this message be downgraded to "debug" level?

**Steps to reproduce the problem**

- Enable DHCPv6 client
- Connect to DHCPv6 server
- Watch the journal

### PR DESCRIPTION
**Pull request by yuwata**
Closes #16731.

### CODE REVIEW

File: src/network/networkd-dhcp6.c [hunk 1]
```diff
@@ -992,8 +992,10 @@ static int dhcp6_update_address(
         addr->cinfo.ifa_valid = lifetime_valid;
 
         (void) in_addr_to_string(addr->family, &addr->in_addr, &buffer);
-        log_link_info(link, "DHCPv6 address %s/%u timeout preferred %d valid %d",
-                      strna(buffer), addr->prefixlen, lifetime_preferred, lifetime_valid);
+
+        if (!set_contains(link->dhcp6_addresses, addr))
```
Comment (poettering) [inline src/network/networkd-dhcp6.c]: maybe use `log_link_full(link, set_contains(…) ? LOG_DEBUG : LOG_INFO)` or so?

Comment (poettering) [reply src/network/networkd-dhcp6.c]: (i.e. just downgrade to debug log if it's an existing message, given it might still be interesting?

Comment (yuwata) [reply src/network/networkd-dhcp6.c]: Sorry for late response. Updated.
