### PR TITLE
 tests: skip the rest of test_mnt_id after getting any error

### LINKED ISSUE #8286: `test-mount-util` seems to fail on CentOS and Debian Jessie when it is run after `test-process-util`
There is a kernel bug presumably fixed in https://github.com/torvalds/linux/commit/bbd5192412fdedbae00888316bfe350bf89d0458 that makes it possible to have a non-existent mount point listed in `/proc/self/mouninfo`.
```sh
$ sudo sh -c 'touch /tmp/cmdline; mount --bind /tmp/cmdline /proc/self/mountinfo'
$ grep cmdline /proc/self/mountinfo
38 15 8:1 /tmp/cmdline /proc/965/mountinfo rw,relatime shared:1 - ext4 /dev/sda1 rw,errors=remount-ro,data=ordered
$ ls /proc/965/mountinfo
ls: cannot access /proc/965/mountinfo: No such file or directory
```
```sh
$ sudo ./build/test-process-util
...

$ sudo ./build/test-mount-util
mnt id of /sys/fs/cgroup/net_cls,net_prio is 33
mnt id of /proc/fs/nfsd is 72
mnt id of /dev/shm is 21
mnt id of /dev/pts is 22
mnt id of /sys/fs/pstore is 26
mnt id of /proc is 18
mnt id of /sys/fs/cgroup/pids is 35
mnt id of /proc/1009/cmdline is 35
Assertion 'path_equal_ptr(hashmap_get(h, INT_TO_PTR(mnt_id2)), p)' failed at ../src/test/test-mount-util.c:99, function test_mnt_id(). Aborting.
Aborted

$ sudo strace -s500 -f -y -vv ./build/test-mount-util
...
name_to_handle_at(AT_FDCWD, "/proc/1009/cmdline", {handle_bytes=128}, 0x7ffe27955964, 0) = -1 ESRCH (No such process)
writev(2</dev/pts/0>, [{"mnt id of /proc/1009/cmdline is 32", 34}, {"\n", 1}], 2mnt id of /proc/1009/cmdline is 32
) = 35
...
```
I've prepared a patch which I'm going to send as soon as I find a way to receive my 2FA authentication code :-)
```diff
diff --git a/src/test/test-mount-util.c b/src/test/test-mount-util.c
index c95baa8..8267a11 100644
--- a/src/test/test-mount-util.c
+++ b/src/test/test-mount-util.c
@@ -88,6 +88,10 @@ static void test_mnt_id(void) {
                         log_debug("Can't access %s\n", p);
                         continue;
                 }
+               if (r < 0) {
+                       log_debug_errno(r, "Failed to get the mnt id of %s: %m\n", p);
+                       continue;
+               }

                 log_debug("mnt id of %s is %i\n", p, mnt_id2);

diff --git a/src/test/test-process-util.c b/src/test/test-process-util.c
index 0e5a9d8..1a0164e 100644
--- a/src/test/test-process-util.c
+++ b/src/test/test-process-util.c
@@ -193,6 +193,8 @@ static void test_get_process_cmdline_harder(void) {
         assert_se(pid == 0);
         assert_se(unshare(CLONE_NEWNS) >= 0);

+        assert_se(mount(NULL, "/", NULL, MS_PRIVATE|MS_REC, NULL) >= 0);
+
         fd = mkostemp(path, O_CLOEXEC);
         assert_se(fd >= 0);
```

### PR DESCRIPTION
**Pull request by evverx**
This mainly gets around a kernel bug making it possible to
have non-existent paths in /proc/self/mountinfo, but it should also
prevent flaky failures that can happen if something changes immediately
after or during reading /proc/self/mountinfo.

Closes #8286.

### CODE REVIEW

**Comment by evverx** [comment]
I would have been very surprised if the Fedora CI hadn't failed :-)

File: src/test/test-mount-util.c [hunk 1]
```diff
@@ -88,6 +88,10 @@ static void test_mnt_id(void) {
                         log_debug("Can't access %s\n", p);
                         continue;
                 }
+                if (r < 0) {
+                        log_debug_errno(r, "Failed to get the mnt id of %s: %m\n", p);
+                        continue;
+                }
```
Comment (keszybz) [inline src/test/test-mount-util.c]: I think it'd be nicer to fold all those three checks into one:
```C
if (r < 0) {
         log_debug_errno(r,
                     r == -EOPNOTSUPP ? "%s doesn't support mount IDs\n" :
                     "Failed to get the mnt id of %s: %m\n",
                     p)
  continue;
}
```

Comment (evverx) [reply src/test/test-mount-util.c]: Why do you think it would be nicer? I was considering this option, but in the end decided not to do it because I usually prefer not to break crazy `grep`s searching for particular strings that can exist out there.

Comment (keszybz) [reply src/test/test-mount-util.c]: grep would not be impacted, all the strings would still be there. It's nicer because it makes clear that only the log line is different, but otherwise the same handling is applied to all three cases. Also, it's significantly shorter.

Comment (evverx) [reply src/test/test-mount-util.c]: I'm not sure what strings would still be there because the string "Can't access" is a bit different from the strings "Operation not permitted" and "Permission denied".

Comment (evverx) [reply src/test/test-mount-util.c]: More generally, I prefer not to break not only crazy `grep`s but all testing tools that somehow handle the output of the tests. It would be very annoying to get a false report from a tool comparing the output of subsequent runs just because something looks prettier.

Comment (keszybz) [reply src/test/test-mount-util.c]: I don't think there's any danger of that. Right now the code looks like this
```C
r = ...;
if (r == -EOPNOTSUPP) {
    ...
}
if (IN_SET(r, -EACCES, -EPERM)) {
    ...
}
if (r < 0) {
   ...
}
```
All this verbosity serves no purpose.

Comment (evverx) [reply src/test/test-mount-util.c]: I'm pretty aware of how the code looks like and I agree that it is far from perfect. Life would probably be easier if the commit where this verbosity was introduced had been reviewed as thoroughly as this one.

Why do you not think that there is any danger of that?

Comment (evverx) [reply src/test/test-mount-util.c]: @keszybz, I've changed the code, but I decided not to distinguish `EOPNOTSUPP` from any other error, because it doesn't seem to make any sense. I've also pushed one more commit skipping `g_dbus_message_new_from_blob` under `asan`.

Comment (evverx) [reply src/test/test-mount-util.c]: By the way, this whole thread made me remember my complaining about the breakage of `systemtap` scripts when something had been changed in `libsystemd` :-) I think it is totally fine to make generalizations about what people use and what can and cannot break due to a small change, but it would also be great to somehow clarify why generalizations are made.
