### PR TITLE
hwdb: Fixed thumb buttons reversed on CHERRY MW 2310 (#12914)

### LINKED ISSUE #12914: thumb buttons reversed on CHERRY MW 2310
**systemd version**
```
systemd 242 (242.29-3-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Used distribution**
```
   Operating System: Arch Linux
             Kernel: Linux 5.1.15-zen1-1-zen
       Architecture: x86-64
```

**Hardware affected**
Wireless USB mouse CHERRY MW 2310
```
Input device ID: bus 0x3 vendor 0x1a81 product 0x1701 version 0x111
Input device name: "G-Tech Wireless Dongle Mouse"
```

**Expected behaviour you didn't see**
 > Pressing fore thumb button navigates back, pressing aft thumb button navigates forward.

**Unexpected behaviour you saw**
> The thumb buttons are reversed.
 > See https://bugzilla.kernel.org/show_bug.cgi?id=204025

**Proposed fix**
I've managed to create a local HWDB file `/etc/udev/hwdb.d/71-mouse-local.hwdb` that swaps the thumb buttons:
```
#:name:G-Tech Wireless Dongle Mouse:
evdev:input:*v1A81*p1701*
 KEYBOARD_KEY_90005=back
 KEYBOARD_KEY_90004=forward
```

I'd like to know if/how this solution can be contributed to other users.

### PR DESCRIPTION
**Pull request by taniishkaaa**
Fixes #12914

### CODE REVIEW

File: hwdb.d/70-mouse.hwdb [hunk 1]
```diff
@@ -812,4 +821,4 @@ mouse:usb:v3057p0001:*
 mouse:usb:v1af3p0001:name:Kingsis Peripherals ZOWIE Gaming mouse:*
  MOUSE_DPI=400@125 *800@125 1600@125 3200@125 400@500 800@500 1600@500 3200@500 400@1000 800@1000 1600@1000 3200@1000
  MOUSE_WHEEL_CLICK_COUNT=16
- MOUSE_WHEEL_CLICK_ANGLE=23
+ MOUSE_WHEEL_CLICK_ANGLE=23
```
Comment (yuwata) [inline hwdb.d/70-mouse.hwdb]: Please drop the change.

**Review by yuwata — APPROVED** [review]
