### PR TITLE
basic: restore missing_bpf.h for BPF_JMP_A macro

### LINKED ISSUE #40331: Build failure: implicit declaration of function ‘BPF_JMP_A’
systemd version: 259
libbpf version: 1.6.2
Distro: Gentoo

Downstream report: https://bugs.gentoo.org/968650

When building with `-Dbpf-framework=enabled -Dbpf-compiler=gcc`, we get this error.

```
FAILED: [code=1] src/core/libsystemd-core-259.a.p/bpf-devices.c.o 
x86_64-pc-linux-gnu-gcc -Isrc/core/libsystemd-core-259.a.p -Isrc/basic -I../systemd-259/src/basic -Isrc/fundamental -I../systemd-259/src/fundamental -Isrc/systemd -I../systemd-259/src/systemd -Isrc/version -I../systemd-259/src/version -I../systemd-259/src/libsystemd/sd-bus -I../systemd-259/src/libsystemd/sd-common -I../systemd-259/src/libsystemd/sd-device -I../systemd-259/src/libsystemd/sd-event -I../systemd-259/src/libsystemd/sd-hwdb -I../systemd-259/src/libsystemd/sd-id128 -Isrc/libsystemd/sd-journal -I../systemd-259/src/libsystemd/sd-journal -I../systemd-259/src/libsystemd/sd-json -I../systemd-259/src/libsystemd/sd-netlink -I../systemd-259/src/libsystemd/sd-network -I../systemd-259/src/libsystemd/sd-path -I../systemd-259/src/libsystemd/sd-resolve -I../systemd-259/src/libsystemd/sd-varlink -Isrc/shared -I../systemd-259/src/shared -Isrc/core -I../systemd-259/src/core -I/usr/include/bpf/uapi -I/usr/include/libmount -I/usr/include/blkid -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu17 -Wno-missing-field-initializers -Wno-unused-parameter -Wno-nonnull-compare -Warray-bounds -Warray-bounds=2 -Wdate-time -Wendif-labels -Werror=bool-compare -Werror=discarded-qualifiers -Werror=flex-array-member-not-at-end -Werror=format=2 -Werror=format-signedness -Werror=implicit-function-declaration -Werror=implicit-int -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=missing-declarations -Werror=missing-parameter-name -Werror=missing-prototypes -Werror=overflow -Werror=override-init -Werror=pointer-sign -Werror=return-type -Werror=sequence-point -Werror=shift-count-overflow -Werror=shift-overflow=2 -Werror=strict-flex-arrays -Werror=undef -Wfloat-equal -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-aliasing=2 -Wstrict-prototypes -Wsuggest-attribute=noreturn -Wunterminated-string-initialization -Wunused-function -Wwrite-strings -Wzero-as-null-pointer-constant -Wzero-length-bounds -fdiagnostics-show-option -fno-common -fstack-protector -fstack-protector-strong -fstrict-flex-arrays=3 --param=ssp-buffer-size=4 -Wno-maybe-uninitialized -Wno-unused-result -ftrivial-auto-var-init=zero -Werror=shadow -march=znver3 -mtune=znver3 -mshstk --param=l1-cache-line-size=64 --param=l1-cache-size=32 --param=l2-cache-size=512 -O2 -pipe -fPIC -fno-strict-aliasing -fstrict-flex-arrays=1 -fvisibility=hidden -include config.h -pthread -isystem../systemd-259/src/include/override -isystemsrc/include/override -isystem../systemd-259/src/include/uapi -fvisibility=default -MD -MQ src/core/libsystemd-core-259.a.p/bpf-devices.c.o -MF src/core/libsystemd-core-259.a.p/bpf-devices.c.o.d -o src/core/libsystemd-core-259.a.p/bpf-devices.c.o -c ../systemd-259/src/core/bpf-devices.c
../systemd-259/src/core/bpf-devices.c: In function ‘bpf_prog_allow_list_device’:
../systemd-259/src/core/bpf-devices.c:55:17: error: implicit declaration of function ‘BPF_JMP_A’; did you mean ‘BPF_JMP32’? [-Wimplicit-function-declaration]
   55 |                 BPF_JMP_A(PASS_JUMP_OFF),                      /* jump to PASS */
      |                 ^~~~~~~~~
```
It looks like this happens because /usr/include/bpf/uapi/linux/bpf.h is being included instead of src/include/override/linux/bpf.h.

A full log file is attached to the downstream report.

### PR DESCRIPTION
**Pull request by calm329**
## Problem

When building with `-Dbpf-framework=enabled -Dbpf-compiler=gcc`, compilation fails with:

error: implicit declaration of function 'BPF_JMP_A'; did you mean 'BPF_JMP32'?

This happens because libbpf's pkg-config adds `-I/usr/include/bpf/uapi` which takes precedence over the `-isystem` override paths, causing the system's linux/bpf.h to be included instead of systemd's override header.

## Solution

Restore the `missing_bpf.h` header that provides `BPF_JMP_A` for code that needs it. This is cleaner than the override approach since `BPF_JMP_A` is defined in `linux/filter.h` (a private kernel header), not a public UAPI header.

Fixes #40331

---

Contribution by Gittensor, see my contribution statistics at https://gittensor.io/miners/details?githubId=148254234

### CODE REVIEW

**Comment by hhoffstaette** [comment]
Unfortunately this didn't work for me:
- git clone master
- apply patch from this PR
- meson setup / compile
- same error as before, `-I/usr/include/bpf/uapi` is still in the compile command for `bpf-devices.c`

**Comment by floppym** [comment]
It seems that meson does not attempt to parse `pkg-config --cflags libbpf` into separate `includes` versus `compile_args`. It all ends up in `compile_args`.

Using `libbpf.partial_dependency(compile_args: false)` resolves the build failure here, but I'm not sure if that's really the right approach.

**Comment by floppym** [comment]
I don't see BPF_JMP_A defined anywhere under /usr/include.

I think it would be better to move the definition of BPF_JMP_A to the top of src/core/bpf-devices.c and eliminate the seemingly pointless src/include/override/linux/bpf.h header.

**Comment by floppym** [comment]
~~Also I wonder if this PR is being submitted by an AI bot.~~

**Comment by calm329** [comment]
Sorry, looks like I fixed in incorrect way. Updated it again, please check it

**Comment by calm329** [comment]
> Also I wonder if this PR is being submitted by an AI bot.

No, I'm not

**Comment by floppym** [comment]
Thanks, I like it! Hopefully the maintainers agree.

**Comment by cbricart** [comment]
(maybe giving @yuwata a explicit ping here, as `BPF_JMP_A()` has been moved around with commit 543a48b and commit 0cced29)

**Comment by floppym** [comment]
> Sorry, but no. As written the original definition of the macro comes from kernel header, and moving it around deliberately is not a proper fix.

It's defined in a private kernel header, not a public (uapi) header.

Kludging it into an "override" of linux/bpf.h is a terrible solution.

**Comment by thesamesam** [comment]
And if it must remain (for what reason?), it certainly shouldn't be `linux/bpf.h`.

**Comment by calm329** [comment]
> Sorry, but no. As written the original definition of the macro comes from kernel header, and moving it around deliberately is not a proper fix.

So there are two possible approaches:
- `compile_args: false` to fix include ordering (keeps override header)
- move BPF_JMP_A directly to bpf-devices.c (removes override header)

Which approach do you prefer?

**Comment by YHNdnzj** [comment]
I'd prefer to restore basic/missing_bpf.h. I think @floppym and @thesamesam do have a point that stuffing this into linux/bpf.h is counterproductive.

**Comment by floppym** [comment]
That would be fine by me. 👍

File: src/core/bpf-devices.c [hunk 1]
```diff
@@ -1,11 +1,11 @@
 /* SPDX-License-Identifier: LGPL-2.1-or-later */
 
 #include <fnmatch.h>
-#include <linux/bpf.h>
 #include <linux/bpf_insn.h>
 #include <sys/stat.h>
 
 #include "alloc-util.h"
+#include "missing_bpf.h"
```
Comment (YHNdnzj) [inline src/core/bpf-devices.c]: please sort

Comment (calm329) [reply src/core/bpf-devices.c]: Done!

**Comment by yuwata** [comment]
Please update the cover letter of this PR, as it will be used as commit message of the squashed commit on merge.
Or, please squash the commits and update the commit message.

**Comment by yuwata** [comment]
Basically, I'd like to avoid reintroducing missing_xyz.h header...

**Comment by calm329** [comment]
> Please update the cover letter of this PR, as it will be used as commit message of the squashed commit on merge. Or, please squash the commits and update the commit message.

Done. Squashed the commits and updated the commit message.

**Comment by floppym** [comment]
> Basically, I'd like to avoid reintroducing missing_xyz.h header...

The macro is used in exactly one .c file, so a header file seems pointless to me.

If you really want it to live in a header, please don't call it linux/bpf.h; that's just confusing since no version of the kernel defines it in its public/uapi headers.

This macro only lives in the private linux/filter.h header in the kernel.

**Comment by floppym** [comment]
Hmm, I see several other internal structs/macros are handled in a similar way by sticking them into loosely related files in src/include/override/linux. Seems strange to me, but I guess that was done on purpose.

In any case, with linux/bpf.h, it's always going to conflict with the headers provided by libbpf.

**Comment by yuwata** [comment]
Hmmm, libbpf by default does not add `-I/usr/lnclude/bpf/uapi`. Maybe that is gentoo specific?

**Comment by yuwata** [comment]
Hm, I think the definition of the `BPF_JMP_A` should be moved to `src/include/override/linux/bpf_insn.h`
bpf_insn.h is something special, it is typically not installed at `/usr/include/linux/` (nor `/usr/include/bpf/uapi/linux/`), as it is in the sample of the linux tree. But, we copy it in `src/include/uapi/`. So, I guess we can freely override the header.

So, please try to move the header src/include/override/linux/bpf.h -> src/inculde/override/linux/bpf_insn.h, and update `#include_next`.

**Comment by floppym** [comment]
> Hmmm, libbpf by default does not add `-I/usr/lnclude/bpf/uapi`. Maybe that is gentoo specific?

Ah you're right.

https://github.com/gentoo/gentoo/blob/master/dev-libs/libbpf/files/libbpf-9999-paths.patch

However, even without our patch I think the issue could still occur if libbpf is installed in a different PREFIX.

**Comment by yuwata** [comment]
> > Hmmm, libbpf by default does not add `-I/usr/lnclude/bpf/uapi`. Maybe that is gentoo specific?
> 
> Ah you're right.
> 
> https://github.com/gentoo/gentoo/blob/master/dev-libs/libbpf/files/libbpf-9999-paths.patch
> 
> However, even without our patch I think the issue could still occur if libbpf is installed in a different PREFIX.

I do not think so. Without the patch, uapi headers are installed in /usr/include/linux/, and the option specified in the .pc file is typically `-I/usr/include`, which will be ignored, as the path is a standard system directory. See the following statement from gcc(1):
> If a standard system include directory, or a directory specified with -isystem, is also specified with -I, the -I option is ignored.  The directory is still searched but as a system directory at its normal position in the system include chain.  This is to ensure that GCC's procedure to fix buggy system headers and the ordering for the "#include_next" directive are not inadvertently changed.  If you really need to change the search order for system directories, use the -nostdinc and/or -isystem options.

**Comment by floppym** [comment]
Sorry for the confusion on this one. I'm looking into whether we can update Gentoo to de-customize the libbpf package. 😅
