### PR TITLE
test: skip one test for iszero_safe() on i386

### LINKED ISSUE #25044: test-math-util fails for i686 (32-bit x86) - Assertion '!iszero_safe(DBL_MAX * 2 / INFINITY)' failed
### systemd version the issue has been seen with

252-rc1

### Used distribution

Gentoo

### Linux kernel version used

5.15.70

### CPU architectures issue was seen on

i686

### Component

_No response_

### Expected behaviour you didn't see

Test passes.

### Unexpected behaviour you saw

```
% ./test-math-util
/* test_iszero_safe */
Assertion '!iszero_safe(DBL_MAX * 2 / INFINITY)' failed at src/test/test-math-util.c:57, function test_iszero_safe(). Aborting.
zsh: IOT instruction (core dumped)  ./test-math-util
```

### Steps to reproduce the problem

Configure systemd to build for an i686 target and run the tests.

In my case, I am running the build on a x86-64 system with 32-bit multilib support using the following command:
```
CC="gcc -m32" CXX="g++ -m32" meson setup --prefix /usr --libdir lib --pkg-config-path "/usr/lib/pkgconfig:/usr/share/pkgconfig" -Dlibcryptsetup=false -Dlibiptc=false -Dkmod=false -Dp11kit=false -Dselinux=false -Dseccomp=false build
```

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #25044.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @floppym

File: src/test/test-math-util.c [hunk 1]
```diff
@@ -54,7 +54,14 @@ TEST(iszero_safe) {
         assert_se( iszero_safe(DBL_MIN / -INFINITY));
         assert_se( iszero_safe(DBL_MAX / INFINITY / 2));
         assert_se( iszero_safe(DBL_MAX / -INFINITY * DBL_MAX));
+#if defined(__i386__)
```
Comment (medhefgo) [inline src/test/test-math-util.c]: From the looks of it, `__SSE_MATH__` is defined if `-mfpmath=sse` is in effect, so maybe use that?

Though, shouldn't `iszero_safe` be fixed to deal with this (or declare `-mfpmath=sse` a requirement)?

Comment (yuwata) [reply src/test/test-math-util.c]: Thanks. Now also conditionalized with `__SSE_MATH__`.

> Though, shouldn't `iszero_safe` be fixed to deal with this (or declare `-mfpmath=sse` a requirement)?

At least currently, `iszero_safe()` is only used through `fp_equal()` in json.c. This is only used for parsing or formatting JSON. I do not think it is not necessary to request that all arithmetic give the same value in our code base, as we do not provide any numerical libraries.

File: src/test/test-math-util.c [hunk 2]
```diff
@@ -54,7 +54,14 @@ TEST(iszero_safe) {
         assert_se( iszero_safe(DBL_MIN / -INFINITY));
         assert_se( iszero_safe(DBL_MAX / INFINITY / 2));
         assert_se( iszero_safe(DBL_MAX / -INFINITY * DBL_MAX));
+#if defined(__i386__) && !defined(__SSE_MATH__)
```
Comment (floppym) [inline src/test/test-math-util.c]: One remaining edge case: if SSE2 instructions are not enabled, `-mfpmath=sse` only works for single-precision floats.
```suggestion
#if defined(__i386__) && (!defined(__SSE_MATH__) || !defined(__SSE2__))
```
I have tested this locally and it works as expected.

**Comment by Arfrever** [comment]
Instead of skipping of test, you could try better solution:
* On x86_32, detect if current compiler (with CFLAGS etc.) defines macro `__SSE__`
* If yes, append `-mfpmath=sse` to used flags
* If no, append `-ffloat-store` to used flags

**Comment by Arfrever** [comment]
For checking `__SSE__`, maybe use [`compiler.get_define()`](https://mesonbuild.com/Reference-manual_returned_compiler.html#compilerget_define).

File: src/test/test-math-util.c (hunk 2 above)
Comment (medhefgo) [reply src/test/test-math-util.c]: Maybe use `__SSE2_MATH__` for that case?

Comment (floppym) [reply src/test/test-math-util.c]: Ah, I wasn't aware of that one. Tested locally and it also works.
```suggestion
#if defined(__i386__) && !defined(__SSE2_MATH__)
```

**Comment by yuwata** [comment]
Thank you for the comments. Now `__SSE2_MATH__` is used.

@Arfrever Thank you for the proposal. But, as commented in the [above](https://github.com/systemd/systemd/pull/25053#discussion_r998316098), we do not provide any numerical libraries. Hence, it is not necessary to request that the function provides the same result on different systems. So, adjusting test is enough, and your proposal sounds slightly overkill.

@floppym Could you test again?

File: src/test/test-math-util.c [hunk 3]
```diff
@@ -54,7 +54,17 @@ TEST(iszero_safe) {
...
         assert_se( iszero_safe(DBL_MAX / INFINITY / 2));
         assert_se( iszero_safe(DBL_MAX / -INFINITY * DBL_MAX));
-        assert_se(!iszero_safe(DBL_MAX * 2 / INFINITY));
+#if defined(__i386__) && !defined(__SSE2_MATH__)
+        /* On 32bit x86, -mfpmath=387 is the default and SSE2 is not used. Then, floating point values are
+         * calculated in 80bit, and truncated to the length of the used type (double in this case). Hence,
+         * DBL_MAX * 2 is temporary calculated as a normal value, and goes to zero when divided with
+         * INFINITY. See issue #25044. */
+        log_debug("i386 architecture without SSE2 is detected.");
+        bool expected = true;
```
Comment (floppym) [inline src/test/test-math-util.c]: This will fail if the user has specified "-ffloat-store" in their CFLAGS and doesn't have SSE2 enabled.

I think you should go back to just skipping the test instead of adjusting the expected value.

Comment (yuwata) [reply src/test/test-math-util.c]: Indeed. Reverted. Thanks.

**Review by floppym — APPROVED** [review]

**Review by bluca — APPROVED** [review]
