### PR TITLE
journalctl: do not override explicitly specified -b or -n with -e or -k

### LINKED ISSUE #35248: journalctl: document that --pager-end argument implies last boot and ways to override that
### systemd version the issue has been seen with

255

### Used distribution

Ubuntu 24.04 LTS

### Linux kernel version used

6.8.0-48-generic

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

`journalctl -e` to always display the last 1000 lines from the log as documented in the man page:

> Immediately jump to the end of the journal inside the implied pager tool. This implies -n1000 to guarantee that the pager will not buffer logs of unbounded size. This may be overridden with an explicit -n with some other numeric value, while -nall will disable this cap. Note that this option is only supported for the less(1) pager.
>
> Added in version 198.

### Unexpected behaviour you saw

`journalctl -e` [limits](https://github.com/systemd/systemd/blob/52b0351a154e9ad3f6a62c5de61198e454d86ecb/src/journal/journalctl.c#L459) the output to the last boot by default. This is not documented in the manual page anywhere.

Logs from all boots can be shown by specifying `-ball` **after** and only **after** `-e` option. I think this could be documented documented as well. If possible, it would be nice to have "after and only after" bit resolved to `-ball` anywhere since it is a bit confusing.

### Steps to reproduce the problem

`# journalctl -e -u dbus.service`
```
Nov 18 12:14:50 ubuntuserver systemd[1]: Starting dbus.service - D-Bus System Message Bus...
Nov 18 12:14:50 ubuntuserver dbus-daemon[688]: [system] AppArmor D-Bus mediation is enabled
Nov 18 12:14:50 ubuntuserver systemd[1]: Started dbus.service - D-Bus System Message Bus.
Nov 18 12:14:52 ubuntuserver dbus-daemon[688]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service' requested by ':1.12' (uid=0 pid=702 comm="/usr/lib/snapd/snapd" label="unconfined")
Nov 18 12:14:52 ubuntuserver dbus-daemon[688]: [system] Successfully activated service 'org.freedesktop.timedate1'
Nov 18 13:03:46 ubuntuserver-noble-modax dbus-daemon[688]: [system] Activating via systemd: service name='org.freedesktop.fwupd' unit='fwupd.service' requested by ':1.79' (uid=990 pid=3965 comm="/usr/bin/fwupdmgr refresh" label="unconfined")
Nov 18 13:03:46 ubuntuserver dbus-daemon[688]: [system] Successfully activated service 'org.freedesktop.fwupd'
```
`# journalctl -ball -e -u dbus.service`
```
Nov 18 12:14:50 ubuntuserver systemd[1]: Starting dbus.service - D-Bus System Message Bus...
Nov 18 12:14:50 ubuntuserver dbus-daemon[688]: [system] AppArmor D-Bus mediation is enabled
Nov 18 12:14:50 ubuntuserver systemd[1]: Started dbus.service - D-Bus System Message Bus.
Nov 18 12:14:52 ubuntuserver dbus-daemon[688]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service' requested by ':1.12' (uid=0 pid=702 comm="/usr/lib/snapd/snapd" label="unconfined")
Nov 18 12:14:52 ubuntuserver dbus-daemon[688]: [system] Successfully activated service 'org.freedesktop.timedate1'
Nov 18 13:03:46 ubuntuserver-noble-modax dbus-daemon[688]: [system] Activating via systemd: service name='org.freedesktop.fwupd' unit='fwupd.service' requested by ':1.79' (uid=990 pid=3965 comm="/usr/bin/fwupdmgr refresh" label="unconfined")
Nov 18 13:03:46 ubuntuserver dbus-daemon[688]: [system] Successfully activated service 'org.freedesktop.fwupd'
```
`# journalctl -e -ball -u dbus.service`
```
Nov 18 11:08:04 ubuntuserver dbus-daemon[687]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.559' (uid=0 pid=29069 comm="/usr/bin/gdbus call --system --dest org.freedeskto" label="unconfined")
Nov 18 11:08:04 ubuntuserver dbus-daemon[687]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Nov 18 11:14:03 ubuntuserver-noble-modax dbus-daemon[687]: [system] Activating via systemd: service name='org.freedesktop.fwupd' unit='fwupd.service' requested by ':1.565' (uid=990 pid=29252 comm="/usr/bin/fwupdmgr refresh" label="unconfined")
Nov 18 11:14:03 ubuntuserver dbus-daemon[687]: [system] Successfully activated service 'org.freedesktop.fwupd'
Nov 18 12:14:33 ubuntuserver dbus-daemon[687]: [system] Activating via systemd: service name='org.freedesktop.fwupd' unit='fwupd.service' requested by ':1.572' (uid=990 pid=29761 comm="/usr/bin/fwupdmgr refresh" label="unconfined")
Nov 18 12:14:34 ubuntuserver dbus-daemon[687]: [system] Successfully activated service 'org.freedesktop.fwupd'
-- Boot db9461d4210445528dee9ff3407c5407 --
Nov 18 12:14:50 ubuntuserver systemd[1]: Starting dbus.service - D-Bus System Message Bus...
Nov 18 12:14:50 ubuntuserver dbus-daemon[688]: [system] AppArmor D-Bus mediation is enabled
Nov 18 12:14:50 ubuntuserver systemd[1]: Started dbus.service - D-Bus System Message Bus.
Nov 18 12:14:52 ubuntuserver dbus-daemon[688]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service' requested by ':1.12' (uid=0 pid=702 comm="/usr/lib/snapd/snapd" label="unconfined")
Nov 18 12:14:52 ubuntuserver dbus-daemon[688]: [system] Successfully activated service 'org.freedesktop.timedate1'
Nov 18 13:03:46 ubuntuserver dbus-daemon[688]: [system] Activating via systemd: service name='org.freedesktop.fwupd' unit='fwupd.service' requested by ':1.79' (uid=990 pid=3965 comm="/usr/bin/fwupdmgr refresh" label="unconfined")
Nov 18 13:03:46 ubuntuserver-noble-modax dbus-daemon[688]: [system] Successfully activated service 'org.freedesktop.fwupd'
```

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #35248.

### CODE REVIEW

File: src/journal/journalctl.c [hunk 1]
```diff
@@ -987,11 +981,19 @@ static int parse_argv(int argc, char *argv[]) {
...
+                        arg_lines = 10;
+                else if (FLAGS_SET(arg_pager_flags, PAGER_JUMP_TO_END))
+                        arg_lines = 1000;
+        }
 
-        if (arg_follow && !arg_merge && !arg_boot) {
-                arg_boot = true;
+        if (arg_boot < 0)
+                /* Show the current boot if -f/--follow, -k/--dmesg, or -e/--pager-end is specified unless
+                 * -m/--merge is unspecified. */
```
Comment (YHNdnzj) [inline src/journal/journalctl.c]:
```suggestion
                 * -m/--merge is specified. */
```

File: man/journalctl.xml [hunk 2]
```diff
@@ -474,8 +474,10 @@
         <term><option>-k</option></term>
         <term><option>--dmesg</option></term>
 
-        <listitem><para>Show only kernel messages. This implies <option>-b</option> and adds the match
-        <literal>_TRANSPORT=kernel</literal>.</para>
+        <listitem><para>Show only kernel messages. This adds the match <literal>_TRANSPORT=kernel</literal>.
+        This implies <option>--boot=0</option>, while the implication is overridden by specifying
+        <option>--boot=</option> with some boot specification, especially <option>--boot=all</option> will
+        disables the implication.</para>
```
Comment (YHNdnzj) [inline man/journalctl.xml]: Hmm, this feels unnecessarily verbose to me. "This implies ... unless explicitly specified otherwise" sounds good enough to me?

**Review by YHNdnzj — APPROVED** [review]

**Comment by yuwata** [comment]
@YHNdnzj Thank you for the review. The suggestions are applied.
