### PR TITLE
core: Add trigger limit for path units

### LINKED ISSUE #21802: v250-rc2: Regression in path unit handling regarding not started service unit
**systemd version the issue has been seen with**
 > v250-rc2

**Used distribution**
 > Own build

**Linux kernel version used** (`uname -a`)

 > 5.10.85

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > waiting path unit is waiting until the waited-for file is actually created

**Unexpected behaviour you saw**
 > path unit fails because associated service unit is not started because ConditionFileExists is not fulfilled

**Steps to reproduce the problem**
2 units:

```
# test.path
[Unit]
Description = path check

[Path]
PathExists = /tmp/foo
``` 
```
# test.service
[Unit]
Description = test
ConditionPathExists=/tmp/foo

[Service]
Type = oneshot
ExecStart = /bin/true
RemainAfterExit = true

```
The following actions are performed
- `systemctl daemon-reload`
- `systemctl start test.path`
- Now test.path is active and waiting
- `systemctl start test.service`
- This fails because the ConditionPathExists is not fulfilled
- This also causes failure in test.path, which is the regression 

When performing the same test with v249 the unit test.path remains active and waiting

**Additional program output to the terminal or log subsystem illustrating the issue**
```
# Logs with v250-rc2
2021-12-17 11:53:32.888 init.scope: test.path: Trying to enqueue job test.path/start/replace
2021-12-17 11:53:32.889 init.scope: test.path: Installed new job test.path/start as 380
2021-12-17 11:53:32.889 init.scope: test.path: Enqueued job test.path/start as 380
2021-12-17 11:53:32.890 init.scope: test.path: Changed dead -> waiting
2021-12-17 11:53:32.890 init.scope: test.path: Job 380 test.path/start finished, result=done
2021-12-17 11:53:32.890 init.scope: Started path check.
2021-12-17 11:53:57.941 init.scope: test.service: Trying to enqueue job test.service/reload/replace
2021-12-17 11:54:06.631 init.scope: test.service: Trying to enqueue job test.service/restart/replace
2021-12-17 11:54:06.631 init.scope: test.service: Installed new job test.service/restart as 413
2021-12-17 11:54:06.632 init.scope: test.service: Enqueued job test.service/restart as 413
2021-12-17 11:54:06.632 init.scope: test.service: Job 413 test.service/restart finished, result=done
2021-12-17 11:54:06.632 init.scope: test.service: Converting job test.service/restart -> test.service/start
2021-12-17 11:54:06.632 init.scope: test.service: ConditionPathExists=/tmp/foo failed.
2021-12-17 11:54:06.632 init.scope: test.service: Starting requested but condition failed. Not starting unit.
2021-12-17 11:54:06.632 init.scope: test.service: Job 413 test.service/start finished, result=done
2021-12-17 11:54:06.633 init.scope: test was skipped because of a failed condition check (ConditionPathExists=/tmp/foo).
2021-12-17 11:54:06.633 init.scope: test.path: Failed with result 'unit-condition-failed'.
2021-12-17 11:54:06.636 init.scope: test.path: Changed waiting -> failed
2021-12-17 11:54:06.636 init.scope: test.path: Unit entered failed state.
2021-12-17 11:55:13.999 init.scope: test.path: Changed dead -> failed
2021-12-17 11:55:18.731 init.scope: test.path: Changed dead -> failed

```

From the output of `systemctl list-units` in v250-rc2 after the test:
```
● test.path      loaded    failed   failed    path check
  test.service   loaded    inactive dead      test
```

```
# Logs with v249
2021-12-17 12:15:58.362 init.scope: test.path: Trying to enqueue job test.path/start/replace
2021-12-17 12:15:58.362 init.scope: test.path: Installed new job test.path/start as 1098
2021-12-17 12:15:58.362 init.scope: test.path: Enqueued job test.path/start as 1098
2021-12-17 12:15:58.363 init.scope: test.path: Changed dead -> waiting
2021-12-17 12:15:58.363 init.scope: test.path: Job 1098 test.path/start finished, result=done
2021-12-17 12:15:58.363 init.scope: Started path check.
2021-12-17 12:16:06.483 init.scope: test.service: Trying to enqueue job test.service/start/replace
2021-12-17 12:16:06.483 init.scope: test.service: Installed new job test.service/start as 1131
2021-12-17 12:16:06.483 init.scope: test.service: Enqueued job test.service/start as 1131
2021-12-17 12:16:06.484 init.scope: test.service: ConditionPathExists=/tmp/foo failed.
2021-12-17 12:16:06.484 init.scope: test.service: Starting requested but condition failed. Not starting unit.
2021-12-17 12:16:06.484 init.scope: test.service: Job 1131 test.service/start finished, result=done
2021-12-17 12:16:06.484 init.scope: Condition check resulted in test being skipped.
```

From the output of `systemctl list-units` in v249 after the test:
```
  test.path        loaded    active   waiting   path check
  test.service     loaded    inactive dead      test
```

### PR DESCRIPTION
**Pull request by daandemeyer**
When conditions fail on a service unit, a path unit can cause
PID 1 to busy loop as it keeps trying to activate the service unit.
To avoid this from happening, add a trigger limit to the path unit,
identical to the trigger limit we have for socket units.

Initially, let's start with a high limit and not make it configurable.
If needed, we can add properties to configure the rate limit similar
to the ones we have for socket units.

This is an alternative fix for #17433. The PR also reverts the previous fix which fixes #21802.

### CODE REVIEW

File: src/core/path.c [hunk 1]
```diff
@@ -265,6 +265,9 @@ static void path_init(Unit *u) {
         assert(u->load_state == UNIT_STUB);
 
         p->directory_mode = 0755;
+
+        p->trigger_limit.interval = 2 * USEC_PER_SEC;
+        p->trigger_limit.burst = 200;
```
Comment (daandemeyer) [inline src/core/path.c:270]: I went for the same limits as accept socket units. Not sure if we should be even more lenient for path units.

**Comment by DaanDeMeyer** [comment]
Let me know if the rate limit for path units should be configurable as well.

File: src/core/path.c [hunk 2]
```diff
@@ -494,6 +497,12 @@ static void path_enter_running(Path *p) {
         if (unit_stop_pending(UNIT(p)))
                 return;
 
+        if (!ratelimit_below(&p->trigger_limit)) {
+                log_unit_warning(UNIT(p), "Trigger limit hit, refusing further activation.");
+                path_enter_dead(p, PATH_FAILURE_TRIGGER_LIMIT_HIT);
```
Comment (bluca) [inline src/core/path.c:502]: will it become runnable again automatically later with this?

**Comment by bluca** [comment]
would it be possible to add a unit test for the regression case? it should be simple enough

**Review by bluca — APPROVED** [review]

File: src/core/path.c (hunk 2 above)
Comment (daandemeyer) [reply src/core/path.c:502]: It won't unless the path unit is started again, but if we hit this at all, it very likely means that the path unit is causing pid1 to busy loop so we don't actually want it to trigger again until that's fixed.

Comment (bluca) [reply src/core/path.c:502]: This is an issue though - for example think about a service using the new psi based conditions. Things shouldn't fail forever if a condition is missed. Can't we add a timer event to automatically clean the trigger limit after a while?

Comment (daandemeyer) [reply src/core/path.c:502]: Is it an issue though if you consider that currently, this situation would cause PID1 to busy loop when a condition is missed? The trigger limits for socket units don't have such remediation either unless I missed something.

I figure at the moment, using conditions with path units containing PathExists is completely broken since as soon as conditions fail, you end up busy looping PID 1. There's two problems here, one is that it's possible to cause a busy loop in PID 1 by combined usage of conditions and PathExists. The second problem is figuring out how we should define the interaction between PathExists and failed conditions.

This PR solves the first problem but not the second one. I still think it's an improvement over what we have since we solve the first problem. The second problem is IMO best solved in a second PR and can be delayed to v251.

**Comment by DaanDeMeyer** [comment]
Seems there some issues with UDEV tests. cc @mrc0mmand

**Comment by mrc0mmand** [comment]
> Seems there's some issues with the UDEV tests. cc @mrc0mmand

Both are unrelated - focal-ppc64el is #21603 and TEST-64-UDEV-STORAGE is tracked in https://github.com/systemd/systemd-centos-ci/issues/424.

File: src/core/path.c (hunk 2 above)
Comment (bluca) [reply src/core/path.c:502]: I agree that this is better than the current situation, however we really need to fix the side effect too, as it makes the combination of event triggered services and conditions way less powerful than it could be

**Comment by bluca** [comment]
> Let me know if the rate limit for path units should be configurable as well.

I think it should yeah - added via: https://github.com/systemd/systemd/pull/21818

**Comment by mrc0mmand** [comment]
> @DaanDeMeyer I've seen TEST-63-ISSUE-17433 fail a couple of times in the past few days, eg:
> 
> https://autopkgtest.ubuntu.com/results/autopkgtest-focal-upstream-systemd-ci-systemd-ci/focal/arm64/s/systemd-upstream/20211221_161634_86521@/log.gz (logs at https://autopkgtest.ubuntu.com/results/autopkgtest-focal-upstream-systemd-ci-systemd-ci/focal/arm64/s/systemd-upstream/20211221_161634_86521@/artifacts.tar.gz )

I think this should be "fixed" by #21840 as well, since it happens when the machine is under a heavy load and it misses the tight trigger limit interval. But it's weird that the run is apparently from today, so it still might need some tweaking? Or maybe Ubuntu CI doesn't rebase the PR branch on the latest main? (I can't remember).

```
-- Journal begins at Tue 2021-12-21 17:00:05 CET, ends at Tue 2021-12-21 17:02:03 CET. --
[ 3030.177187] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.185919] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.197937] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.209818] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.221758] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.233733] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.245915] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.257388] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.269134] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.278568] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.291351] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.303220] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.317225] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.328996] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
[ 3030.335592] systemd[1]: test63.service was skipped because of a failed condition check (ConditionPathExists=/tmp/nonexistent).
```

**Comment by bluca** [comment]
the ubuntu builds were not with coverage flags though?

**Comment by mrc0mmand** [comment]
> the ubuntu builds were not with coverage flags though?

Ugh, of course :facepalm: 

So I guess if the `TriggerLimitIntervalSec=` tweak would be done uncoditionally?

**Comment by bluca** [comment]
Yeah, worth a try I think

**Comment by DaanDeMeyer** [comment]
If this is a problem for our tests, won't it turn out to be a problem elsewhere as well? Shouldn't we just relax the default values then?

**Comment by bluca** [comment]
> If this is a problem for our tests, won't it turn out to be a problem elsewhere as well? Shouldn't we just relax the default values then?

The test CI is _really_ slow - but I guess it wouldn't hurt to increase the default timer?

**Comment by DaanDeMeyer** [comment]
I'm not entirely sure. I'm kinda scared about interfering with use cases that trigger path units very often.

**Comment by mrc0mmand** [comment]
> I'm not entirely sure. I'm kinda scared about interfering with use cases that trigger path units very often.

Well, I guess we could tweak the trigger limit only if we're running with coverage or without KVM. With that we'd still have coverage for the "unaltered" test case.
