### PR TITLE
udev: fixes error handling of sd_device_get_parent()

### LINKED ISSUE #16207: systemd-udev: $parent, %P substitution on devices with no parent returns undefined string
**systemd version the issue has been seen with**
v245

**Used distribution**
Fedora 32
systemd - v245.4-1.fc32

**Expected behaviour you didn't see**
When using the %P substitution in a udev rule, and when processing a device with no parent, the result should be an empty string. For example, when processing a LUKS device on systemd <= v242:
**udev rule**: `SUBSYSTEM=="block", RUN+="/usr/bin/echo TEST %P TEST"`
`udevadm test /sys/class/block/dm-3`:
```
...
Reading rules file: /usr/lib/udev/rules.d/99-systemd.rules
Reading rules file: /etc/udev/rules.d/99-test.rules
Reading rules file: /usr/lib/udev/rules.d/99-vmware-scsi-udev.rules
Rules contain 786432 bytes tokens (65536 * 12 bytes), 42467 bytes strings
49699 strings (401095 bytes), 45579 de-duplicated (362749 bytes), 4121 trie nodes used
Invalid inotify descriptor.
DEVPATH=/devices/virtual/block/dm-3
DEVNAME=/dev/dm-3
DEVTYPE=disk
MAJOR=253
MINOR=3
ACTION=add
SUBSYSTEM=block
DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG=1
DM_UDEV_PRIMARY_SOURCE_FLAG=1
DM_UDEV_RULES_VSN=2
DM_ACTIVATION=1
DM_NAME=luksdev
DM_UUID=CRYPT-LUKS2-826b824c02ea4b44924920d4424b7c8d-luksdev
DM_SUSPENDED=0
DEVLINKS=/dev/disk/by-id/dm-name-luksdev /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-826b824c02ea4b44924920d4424b7c8d-luksdev /dev/mapper/luksdev
.ID_FS_TYPE_NEW=
ID_FS_TYPE=
TAGS=:systemd:
SYSTEMD_READY=0
USEC_INITIALIZED=2475937183
dm-3: Failed to apply format '%P', ignoring: No such file or directory
run: '/usr/bin/echo TEST  TEST'
Unload module index
Unloaded link configuration context.
```

**Unexpected behaviour you saw**
Using the same udev rule and LUKS device on systemd v245.4-1.fc32:
```
...
Reading rules file: /usr/lib/udev/rules.d/99-systemd.rules
Reading rules file: /etc/udev/rules.d/99-test.rules
Reading rules file: /usr/lib/udev/rules.d/99-vmware-scsi-udev.rules
Invalid inotify descriptor.
dm-3: Failed to substitute variable '$parent' or apply format '%P', ignoring: No such file or directory
DEVPATH=/devices/virtual/block/dm-3
DEVNAME=/dev/dm-3
DEVTYPE=disk
MAJOR=253
MINOR=3
ACTION=add
SUBSYSTEM=block
DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG=1
DM_UDEV_PRIMARY_SOURCE_FLAG=1
DM_UDEV_RULES_VSN=2
DM_ACTIVATION=1
DM_NAME=luksdev
DM_UUID=CRYPT-LUKS2-826b824c02ea4b44924920d4424b7c8d-luksdev
DM_SUSPENDED=0
DEVLINKS=/dev/disk/by-id/dm-uuid-CRYPT-LUKS2-826b824c02ea4b44924920d4424b7c8d-luksdev /dev/disk/by-id/dm-name-luksdev /dev/mapper/luksdev
.ID_FS_TYPE_NEW=
ID_FS_TYPE=
TAGS=:systemd:
SYSTEMD_READY=0
USEC_INITIALIZED=399536384
run: '/usr/bin/echo TEST CRYPT-LUKS2-826b824c02ea4b44924920d4424b7c8d-luksdev'
Unload module index
Unloaded link configuration context.
```

**Steps to reproduce the problem**
So far, I've reproduced this issue with device-mapper devices (eg luks, lvm) and raid (eg /dev/md0). Reproducing this issue using luks  as an example:

1. Create udev rule using "$parent" or %P:  
  `SUBSYSTEM=="block", RUN+="/usr/bin/echo TEST %P TEST"`
2. Create or use a luks device.  
  `cryptseup luksFormat test.raw && cryptsetup open test.raw luksdev`
  `/dev/mapper/luksdev -> /dev/dm-3` (on my system)
3. Reload udev rules: `udevadm control -R`
4. Test udev rule against opened luks device: `udevadm test /sys/class/block/dm-3`

I've tried this on a few different systemd versions and found that v243 was the first version with this issue. On my other systems running v245, the substituted string can be different depending on what rules ran beforehand and what type of device-mapper dev it is. In my example udev rule, changing the length of the string before %P also changes the output; here's another example:
```
SUBSYSTEM=="block", RUN+="/usr/bin/echo TEST 123412341234 %P TEST"
...
run: '/usr/bin/echo TEST 123412341234 26b824c02ea4b44924920d4424b7c8d-luksdev'
```

It looks like the substitution is still happening even though `sd_device_get_parent` in `udev-event.c` is failing (I assume)?

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #16207.

### CODE REVIEW

File: src/udev/udev-event.c [hunk 1]
```diff
@@ -370,7 +370,7 @@ static ssize_t udev_event_subst_format(
         }
         case FORMAT_SUBST_PARENT:
                 r = sd_device_get_parent(dev, &parent);
-                if (r == -ENODEV)
+                if (r == -ENOENT)
```
Comment (ssahani) [inline src/udev/udev-event.c:373]: oops!
